### ISSUE TITLE
Data source template_file hangs

### ISSUE THREAD

**Issue by ligustah** [hashicorp/terraform#10014]
### Terraform Version
v0.7.9

### Affected Resource(s)
- data source template_file

### Terraform Configuration Files
https://gist.github.com/sl1pm4t/2d2966d701de7a5c94f8007fee5becfd
( provided by @sl1pm4t )

### Debug Output
https://gist.github.com/ligustah/f21d9e18a3f79fd723a3025b537b5540

### Expected Behavior
It should apply or stop with an error.

### Actual Behavior
It hangs.

### Steps to Reproduce
1. `terraform apply`

### References
https://groups.google.com/d/topic/terraform-tool/fDSkh77gtBY/discussion

**Comment by paultyng** [comment]
I'm having a similar problem, I had added a new variable to a template (not a map or list though) and apply just started hanging.  When I backed out the change, it started working again.

**Comment by chadgrant** [comment]
I'm having **tons of issues** with terraform hanging and leaving no state file, 0.7.5 - 0.7.10. I can't figure out the exact resource that is causing it or I would post the config. TF_LOG_* files show no errors. It just hangs, cntrl-c says "exiting gracefully" nope.. that hangs too.

I highly suspect it to be IAM eventually consistent related issues with ecs_services. I can't tell you how painful it is to keep manually fixing all this stuff it creates with no statefile. **PLEASE** fix

**Comment by mitchellh** [comment]
Hey @paultyng, the issue here is somehow being caused by not escaping the variable in the `template_file` which should be `$${joined_list}`. The documentation was updated a few days ago to reflect this and we hope we're very clear about it now. Sorry!

Once you change that, it no longer hangs. 

Terraform 0.8 actually will catch this as an error and show it.

**Comment by mitchellh** [comment]
@chadgrant Also just saw your comment: any hanging issues that we know of I'll prioritize to the top. So please report any (requires a repro though or its hard to fix :(). Note that we're trying to remove hanging as a result of eventual consistency: in TF 0.8 we have a new API providers can opt-in to which allows them to react to Ctrl-C. This will allow hanging API calls to be cancelled for example.

**Comment by ligustah** [comment]
@mitchellh I don't use inline templates in the code that triggers this condition, what else might be the cause?

In my "vars" section of the template_file I'm referencing a variable that somehow seems to break stuff and I assume it is the same problem I ran into at another place (when the template didn't work I tried with a normal inline interpolation, which would yield a completely empty string): https://groups.google.com/forum/#!topic/terraform-tool/BNL6085feX0

**Comment by ligustah** [comment]
Never mind, I found the error. At one point in the module chain I had something like this:
`dns_zone_name = "${dns_zone_name}"` (missing the var.- prefix) and apparently this caused the hang and the other issue as well. Sorry for taking your time! (though I'd still suggest that Terraform somehow catches this and provides an error message)

**Comment by apparentlymart** [comment]
@ligustah there will be an error message for this case in 0.8. The bug in 0.7 is that the variable parsing is allowing these invalid "simple variables" (a single identifier with no periods) but then various parts of Terraform get confused because these variables can never be resolved. In 0.8 these single-identifier references will be a fatal error, but we're waiting for 0.8 because it's a potential backward-compatibility break for those who have been lucky enough to have a situation where this was somewhat-working in spite of it being incorrect.

**Comment by ligustah** [comment]
@apparentlymart Thanks for the note! Looking forward to using 0.8 then.

**Comment by chadgrant** [comment]
@mitchellh Thanks for responding, the hanging is definitely not related to my terraform config, because it does eventually succeed if I try enough, I'm almost positive it's the eventual consistency issues with AWS or possible race conditions.
