### ISSUE TITLE
aws_s3_bucket silently updating existing buckets

### ISSUE THREAD

**Issue by roman-gliffy** [hashicorp/terraform#10031]
Hi there,

### Terraform Version
0.7.7

### Affected Resource(s)
aws_s3_bucket

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}


resource "aws_s3_bucket" "tf-test-connect" {
    bucket = "tf-test-connect"
    acl    = "private"

    tags {
        Name = "tf-test-connect"
        Env  = "test"
        terraform = "true"
    }
}
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform should error out for a resource that already exists.

### Actual Behavior
```
terraform apply
aws_s3_bucket.tf-test-connect: Creating...
  acceleration_status: "" => "<computed>"
  acl:                 "" => "private"
  arn:                 "" => "<computed>"
  bucket:              "" => "tf-test-connect"
  force_destroy:       "" => "false"
  hosted_zone_id:      "" => "<computed>"
  region:              "" => "<computed>"
  request_payer:       "" => "<computed>"
  tags.%:              "" => "3"
  tags.Env:            "" => "test"
  tags.Name:           "" => "tf-test-connect"
  tags.terraform:      "" => "true"
  website_domain:      "" => "<computed>"
  website_endpoint:    "" => "<computed>"
aws_s3_bucket.tf-test-connect: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

It seems very strange that terraform silently updates existing resources. In this case I've added tags and it updated them.

Is this correct behaviour?

**Comment by apparentlymart** [comment]
Hi @roman-gliffy!

Terraform *ideally* will error if a new resource is created that conflicts, but it is constrained by the underlying API model. In the case of S3, the same "put bucket" operation is used both for creating and updating buckets, so Terraform doesn't get any feedback that the bucket already existed.

In principle Terraform could send a GET request to S3 to see if it gets back a NotFound error, but we've generally not done things like this because they can be finicky (e.g. is it failing because it's not found, or because something else is wrong?). It's possible that we should do it here, if we can count on S3 giving us an unambiguous 404 error in the case where the bucket doesn't already exist.

**Comment by roman-gliffy** [comment]
That's interesting, thank you for the explanation. I should've checked the underlying api request terraform was making.
