### ISSUE TITLE
Route53 TXT entry with quoted text is not deployable

### ISSUE THREAD

**Issue by cpelka** [hashicorp/terraform#10048]
Hi,

we're running into troubles with (escaped) quoted texts for deployment. In our case it's for a Route53 TXT entry that should contain variable text with quotation marks. However, it's not possible to deliver such a text to AWS infrastructure using the current Terraform version.

Creating the following by hand is possible and all trials didn't get us to solution. I will explain it with the most obvious way.

### Terraform Version
Terraform 0.7.10

### Affected Resource(s)
aws_route53_record

### Terraform Configuration Files
```
resource "aws_route53_record" "txt_record_main" {
  zone_id = "<my_zone_id>"
  name = "sub.tld.org"
  type = "TXT"
  ttl = "300"

  records = [
    "\"aaa-sub.tld.org\" \"bbb-sub.tld.org\""
  ]
}
```

### Expected Behavior
Exactly **one Route53 record** for _sub.tlx.org_ is created with the value
> "aaa-sub.tld.org" "bbb-sub.tld.org"

### Actual Behavior
Although `terraform plan` runs through and shows up with escaped quotes of the record value, `terraform deploy` exits with error: 

> * aws_route53_record.txt_main_record: [ERR]: Error building changeset: InvalidChangeBatch: Invalid Resource Record
> : FATAL problem: InvalidCharacterString (Value should be enclosed in quotation marks) encountered with '""aaa-sub.tld.org" "bbb-sub.tld.org""'
>         status code: 400, request id: b6977d5c-a7fb-11e6-97c9-d3de708f59d1

Tried other ways as well, resulting in different behaviours.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`
3. `terraform deploy`

### Important Factoids
We're bound to the fact that we to have **one** entry on Route53 with whitespace separated, quoted values.

NOTE: Having two records is not an option here.

**Comment by apparentlymart** [comment]
Hi @cpelka! Sorry for the problems here.

I'm not entirely sure since I'm a little rusty on the details here but I'm wondering if Route53 itself is expecting the value to be escaped somehow. Your use of backslashes is escaping the quotes *in Terraform*, but that just causes Terraform to submit literal quotes to the Route53 API.

A quick look at [the Route53 docs for TXT](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#TXTFormat) leads me to believe that Route53 itself wants the quotes escaped with backslashes, which means that you need to escape the *backslashes* in Terraform, so that they will be present in the resolved string that is sent to the Route53 API:

```hcl
  records = [
    "\\\"aaa-sub.tld.org\\\" \\\"bbb-sub.tld.org\\\""
  ]
```

That is to say:

* `"\\\"aaa-sub.tld.org\\\" \\\"bbb-sub.tld.org\\\""` in the Terraform config
* becomes `\"aaa-sub.tld.org\" \"bbb-sub.tld.org\"`
* which then is interpreted by Route53 as `"aaa-sub.tld.org" "bbb-sub.tld.org"`, which I think is what you want here.

I apologize that I'm not able to test this suggestion myself right now because I'm on the road with a laptop that's lacking my usual tools, but I hope the above will make this work out for you.

**Comment by cpelka** [comment]
Hi Martin,

no need to apologize. Terraform is doing a great job for us and we're happy to store our infrastructure as code.

I just checked your proposal but it's not working. Although the `deploy` runs through and doesn't throw an exception anymore, the record created is wrong:
* Result: `"\"aaa-sub.tld.org\" \"bbb-sub.tld.org\""`

But your point was really a good hint: using the following config works completely out as the outer quotation marks are added/managed by Route 53:
```
records = [
  "aaa-sub.tld.org\" \"bbb-sub.tld.org"
]
```
This one will create the record:
* `"aaa-sub.tld.org" "bbb-sub.tld.org"`

So, I'm really happy to have this back as part of our infrastructure code! However, it's not obvious ;)

Not sure if you want to add some checks for Route 53 resource about the trial of escaping the outer quotation marks or still want to treat it as a bug.

Thanks for your support!

**Comment by apparentlymart** [comment]
Oh, interesting... I guess that works because something (Terraform? The Route53 API?) Is adding quotes around it implicitly. That's pretty counter-intuitive, but I am glad you found a solution that worked for you.

Feels to me like there ought to be a more normal-looking way of specifying what you wanted here but I'm not sure what it would be so I'm going to leave this open here for now so we can think on it a bit more.

**Comment by dkbrummitt** [comment]
@apparentlymart if it helps at all, this comes from Route53.  I do not use Terraform, but discovered this thread researching the error.  
Parameter (CDNTXTValue) required escaping quotes:
`{
                    "Name": {
                        "Ref": "CDNTXTName"
                    },
                    "Type": "TXT",
                    "TTL": "1800",
                    "ResourceRecords": [{
                        "Ref": "CDNTXTValue"
                    }]
}`
Using a raw string did not require the the quotes
`{
                    "Name": {
                        "Ref": "CDNTXTName"
                    },
                    "Type": "TXT",
                    "TTL": "1800",
                    "ResourceRecords": ["CDNTXTValue"]
}`

**Comment by Quantisan** [comment]
I came from Google to this. Note that Terraform automatically add double quotes around all TXT records, https://github.com/hashicorp/terraform/pull/1213
