### ISSUE TITLE
Interpolation in tfvars file

### ISSUE THREAD

**Issue by brendan-rius** [hashicorp/terraform#10059]
It looks like I cannot use interpolation in .tfvars file.
Here is my tfvars for example:

```
access_key        = "XXX"
secret_key        = "XXX"
deploy_key_pub    = "${file("./deploy_key.pub")}"
deploy_key_secret = "${file("./deploy_key")}"
```

the ${file()} seems to be interpreted as a plain string. Is there a way to make interpolation work in tfvars file?

**Comment by Kentzo** [comment]
Another use case: namespace generation based on "${terraform.env}"

**Comment by Legogris** [comment]
Is there any plan to support this in v0.12 or any time soonish? Being able to read configuration from static files in the containing module for passing it to a submodule would be great.

**Comment by apparentlymart** [comment]
Hi all! I'm not sure why I didn't see this issue before, but here we are... :confounded: 

Quite a lot has changed since this issue was opened, so it feels to me that the use-cases that likely motivated this feature request have now been addressed with one or more other language features. For example:

* [Local values](https://www.terraform.io/docs/configuration/locals.html) allow defining named derived values within a particular module, so it's now common to separate the static input variables from other values derived from them, with patterns like this:

    ```hcl
    variable "deploy_key_filename" {
      type = string
    }

    locals {
      deploy_key = file(var.deploy_key_filename)
    }
    ```

    ```hcl
    locals {
      per_workspace = {
        workspace_a = "foo"
        workspace_b = "bar"
      }
      workspace = local.per_workspace[terraform.workspace]
    }
    ```
* The [`jsondecode`](https://www.terraform.io/docs/configuration/functions/jsondecode.html), [`yamldecode`](https://www.terraform.io/docs/configuration/functions/yamldecode.html), and [`csvdecode`](https://www.terraform.io/docs/configuration/functions/csvdecode.html) functions provide various ways of interpreting structured data saved in separate files.

Perhaps there were other use-cases in mind here, but this issue is focused on a particular technical proposal so I'd like to proceed as follows: if you are one of the folks who voted for this issue and you had a use-case in mind that the features above don't seem to meet, please [open a new feature request](https://github.com/hashicorp/terraform/issues/new?labels=enhancement%2C+new&template=feature_request.md) and fill in the template to describe the underlying problem you are hoping to solve. That way we can consider possible solutions to those specific problems, which may take a different form than what was proposed here.

With that in mind, I'm going to close this. I do appreciate the discussion here, and I'm sorry that we didn't respond to this issue before. Hopefully the new features described above will address at least some of the needs that motivated this request. Thanks!
