### ISSUE TITLE
Feature Request:  A way to halt terraform scripts to allow manual provisioning.

### ISSUE THREAD

**Issue by ctro** [hashicorp/terraform#1007]
Automation is great, but some things require too much effort to automate.

In my case I need to terraform a Network, and an IPSec VPN.  There are a couple manual steps involved.  I don't want to invest too much time trying to automating something that is easy to do manually, and that I'll only have to do once ever.

I've been playing with modules to try and split my TF scripts up into different executable "groups" that can still share outputs.  But this is turning into a goose chase inside of a rabbit hole.

I'm wondering if it would be possible to support a simple way to "halt" a terraform script, for instance, allowing me to set up my local VPN before continuing with all other provisioning steps.

**Comment by radeksimko** [comment]
I don't think terraform is here just because of automation, it's also a full description of your infrastructure which you can reproduce anytime, anywhere.

In reality it may turn out that even a VPN box might need creating more often and it will bite you at a point you need it least - e.g. when your VPN box goes down during midnight because of HW failure.

Whatever tool you decide to use for describing your infrastructure (could be terraform), put **everything** there and do not rely on manual setup.

Any wise AWS advisor will tell you that you should consider all your boxes in the cloud to be ephemeral = prepared to die & rebuild and I don't think the situation will be too different for other cloud providers.

**Comment by ctro** [comment]
@radeskimo, I hear you.

But diminishing returns are real, and apply to code too.
I'm trying to be _real_, and the real world has all kinds of tradeoffs.

**Comment by knuckolls** [comment]
If you really want to do this you can find a way to block in a local-exec until you touch a file or something like that. That said, I agree with radeksimko.

**Comment by phinze** [comment]
Here's a working example of @knuckolls idea - it happily waits for the file to appear between the  `tftest1` and `tftest2` resources.

```js
variable "cloudflare_email" {}
variable "cloudflare_token" {}

provider "cloudflare" {
  email = "${var.cloudflare_email}"
  token = "${var.cloudflare_token}"
}

resource "cloudflare_record" "tftest1" {
  domain = "phinze.com"
  name   = "tftest1"
  value  = "127.0.0.1"
  type   = "A"
  ttl    = 600
  provisioner "local-exec" {
    command = "echo '\n\n-= HEY GO DO THAT MANUAL THINGY THEN RUN `touch /tmp/ididit`; I WILL WAIT HERE =-\n\n'; while ! test -f /tmp/ididit; do sleep 1; done"
  }
}

resource "cloudflare_record" "tftest2" {
  domain = "phinze.com"
  name   = "tftest2"
  value  = "127.0.0.1"
  type   = "A"
  ttl    = 600
  depends_on = "cloudflare_record.tftest1"
}
```

![terraform-1007](https://cloud.githubusercontent.com/assets/37534/6316437/0fc32eb8-b9ec-11e4-80ea-43328a651ec4.gif)

**Comment by phinze** [comment]
Feel free to follow up and/or reopen if this doesn't meet your needs, @ctro! :+1:

**Comment by ctro** [comment]
Hey @phinze, @knuckolls 
Super, and Thank You!  

This seems like the right solution to me.  Simple.
