### ISSUE TITLE
data source aws_subnet forces new resource with each run of terrafrom apply

### ISSUE THREAD

**Issue by dmatthis-sm** [hashicorp/terraform#10074]
### Terraform Version
Terraform v0.7.9

### Affected Resource(s)
- data source aws_subnet
- resource aws_instance

### Terraform Configuration Files
```hcl

## Resource will be destroyed and rebuilt each time terraform apply is ran.
resource "aws_instance" "test-a" {
  count                       = 2
  ami                         = "${data.aws_ami.ubuntu16.id}"
  instance_type               = "t2.micro"
  vpc_security_group_ids      = [ "sg-somegroup" ]
  associate_public_ip_address = false
  subnet_id                   = "${data.aws_subnet.publicb.id}"
}

## Resource will not be destroyed and rebuilt with each run.
resource "aws_instance" "test-b" {
  count                       = 2
  ami                        = "${data.aws_ami.ubuntu16.id}"
  instance_type               = "t2.micro"
  vpc_security_group_ids      = [ "sg-somegroup" ]
  associate_public_ip_address = false
  subnet_id                   = "subnet-1234abcd"
}

```
### Expected Behavior
If the subnet id is the same each run, even with a calculated value, then it should not destroy and rebuild the instance for each "terraform apply"

### Actual Behavior
Instance resource that has subnet_id set with a calculated value based off data resource is destroyed and rebuilt with each run of "terraform apply"

```
-/+ aws_instance.test-a.0
.
.
.
  subnet_id:                                         "subnet-1234abcd" => "<computed>" (forces new resource)
```
### Steps to Reproduce
1. `terraform apply`
2. Run `terraform apply` again. (It does not matter if you run terraform plan before hand or not

**Comment by apparentlymart** [comment]
Hi @dmatthis-sm. Sorry for the weirdness here...

Could you also share the `data.aws_subnet.publicb.id` configuration block, and the mention of it in the plan output, if any? It seems like something is causing the data to not be resolvable during initial refresh, but I can't tell that for sure with the configuration subset you've shared so far.

**Comment by dmatthis-sm** [comment]
```
data "aws_subnet" "publicb" {
  filter {
    name   = "tag:Name"
    values = ["${var.subnet_filter} ${var.aws_region}b"]
  }
  vpc_id = "${aws_vpc.vpc.id}"
}
```

**Comment by apparentlymart** [comment]
Hmm... weird. The only reason this should be happening is if the `aws_vpc.vpc` resource is being replaced, and thus forcing Terraform to wait until it has been created in order to populate `vpc_id`... is any other resource showing in the plan when you see the never-ending diffs on that `aws_instance` resource?

**Comment by dmatthis-sm** [comment]
I think I found my problem I have two sets of data resource lookups as I have been trying various things our trying to work with modules and commented out large blocks of code.

The active one right now is on that doesn't have `vpc_id = "${aws_vpc.vpc.id}"` it is actually `vpc_id = "${inf_vpc_id}"`

inf_vpc_id is an output variable from a vpc module. Because output from the module is not calculated until run time there is actually no data there, but instead of throwing an error for null value, from what I can tell it just sends and empty string. 

This gets at the original problem I am trying to work around. It seems counter productive to put the VPC and subnets in a module as you cannot reference the generated data in other modules. In my case I was trying to figure out how to make an instance module that could put the nodes in the correct subnet and AZ by passing an output variable from the VPC. 

Whent his failed I thought I would see if the data_source option would let me get what I needed but I apparently forgot that I am trying to use it in a lookup in the data call in order to find the vpc_id and apparently "inf_vpc_id" is empty when the data resource runs.

So I guess to your point @apparentlymart I am trying to populate vpc_id with a resource that doesn't have a value at the run time. Sorry for the wrong text grab. 

That said do you know of any docs or pages that give a good design pattern for dealing with VPC modules and generating instances based on the subnets that are part of those VPCs?

**Comment by apparentlymart** [comment]
Hi again, @dmatthis-sm.

What you're trying to do should be possible. I think the trick is just figuring out the right way to express it.

In particular, the following config from your latest message is not valid:

```hcl
vpc_id = "${inf_vpc_id}"
```

Note that `inf_vpc_id` is not a fully-qualified variable. If it's coming from a child module as you say, then it should be something like `"${module.foo.inf_vpc_id}"`.

The intent is that it's fine to use a resource attribute (whether directly or via a module) as a dependency of a data source configuration, but it will cause the data lookup to be deferred until `apply` time so that the value can be known. I have a feeling that there's still some sort of Terraform issue tripping you up here, but it's tricky to tell. I'm curious to see what happens if you replace your `${inf_vpc_id}` interpolation with a fully-qualified module one.

**Comment by dmatthis-sm** [comment]
thanks I feel stupid 😃  That helped and seems to make all the difference.

**Comment by apparentlymart** [comment]
Cool, @dmatthis-sm... I'm glad we got to the bottom of this!

I'm going to close this since I think your problem is solved now... if I'm wrong, please let me know and I'm happy to re-open and work on this with you some more.
