### ISSUE TITLE
[Feature] Provider AWS - Instance migration

### ISSUE THREAD

**Issue by JulienChampseix** [hashicorp/terraform#10094]
Hi Team,

### Terraform Version
`Terraform v0.7.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

### Debug Output
N/A.

### Panic Output
N/A.

### Feature details

Sometimes, AWS require their customers to migrate instance to a new one due their "Retirement Policy".

That will be great to have an option maybe inside aws_instance for support this kind of migration for keep terraform up to date interm of ressource/inventory.

This migration require here to create an AMI from the instance which will be retired + boot a new instance from this "fresh" AMI + destroy only the old instance which will be retired.

### Current issues / trouble

If i do it manually over aws console or aws cli, terraform wont be updated. I didnt find the right way to do it using terraform without service degradation.

**Comment by apparentlymart** [comment]
@JulienChampseix I've generally been able to do this by just stopping and then starting again the instance that has been retired, which seems to move it on to new hardware. But I assume you have a use-case where that isn't suitable, such as needing to spin up the new instance before the old one is destroyed?

Honestly, Terraform is not particularly good at this sort of multi-stage scripted action, because it's not really consistent with its model of automatically figuring out what the differences are and then trying to reconcile them. In cases where there are multiple different ways to reconcile the differences, Terraform's configuration language isn't expressive enough to tell it which path to take.

In the short term I'd suggest looking into ways to do your task via outside scripting and then update Terraform's state to match. Terraform has some commands that could be incorporated into your scripts that might get the effect you need here:

* Use [`terraform state rm`](https://www.terraform.io/docs/commands/state/rm.html) to make Terraform "forget" about the old (now destroyed) instance
* Use [`terraform import`](https://www.terraform.io/docs/commands/import.html) to add the new resource into the state in its place, by providing the same resource address but using the *new* (now created) instance id.

If you do the above, Terraform should end up believing that your new instance is the object it is managing, instead of the one that was destroyed. Since the new instance presumably has a matching configuration aside from its id, Terraform should then see no difference between the config and the state and be able to proceed as if nothing happened.

A different way to get here, using Terraform itself to do more of the work, would be two write a temporary configuration file within your module that:

* Uses [the `aws_ami_from_instance` resource](https://www.terraform.io/docs/commands/import.html) to create the AMI (which may cause your instance to temporarily pause)
* Uses the `aws_instance` resource to create a new resource from that AMI.

You can then `apply` that configuration to create both the AMI and the new instance, alongside the old. Now you can use `terraform state rm` as above followed by [`terraform state mv`](https://www.terraform.io/docs/commands/state/rm.html) to "rename" the new instance to have the address of the old instance. You can then delete that temporary configuration file, which will cause Terraform to delete the temporary AMI on the next `apply`.

There are several other formulations with similar building blocks, using different combinations of Terraform features and outside scripting, so I can't possibly describe them all here but I hope the above gives you some ideas for how you could use Terraform as all or part of your process in the absence of a first-class feature for this.

**Comment by stack72** [comment]
Hi @JulienChampseix 

I am looping back on this issue - as @apparentlymart has pointed out, there isn't a way that we can do this in Terraform. Terraform doesn't allow the ability to start / stop instances. I think the options that @apparentlymart points out above are the best way that you can achieve this

Hope this is ok - sorry again for taking so long to getting back to it

thanks

Paul
