### ISSUE TITLE
Real users will never report "Experimental feature failure" bugs

### ISSUE THREAD

**Issue by christopher-demarco** [hashicorp/terraform#10108]
### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
n/a

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
1. Clever dev decides to run unit/integration tests for Version Q during users' production runs of Verision P.
2. User trips on V.Q bug and is given output to put in GitHub issue.
3. User invests 30 seconds pasting the templated output into GitHub and goes on her merry way.
4. Clever dev reaps useful work.

### Actual Behavior
1. [as above]
2. [as above]
3. User is faced with a GitHub form which requires her to run other commands, dig up her config, and invoke externalities like Gists.
4. User is insufficiently invested in the issue (after all, it's not really her bug) and ragequits.
5. Dev gets vastly fewer bug reports.

**Comment by mitchellh** [comment]
While I appreciate your input, we've had a good number of experimental failure issues reported which has led to a much more stable 0.8.0 beta series so far and has fixed issues that would've been quite bad otherwise. Given this, I think that you underestimate the interest of the community in helping ensure future Terraform versions are shipped with stable features. :)

**Comment by christopher-demarco** [comment]
Glad to hear it.
All things considered, it *is* a stupid-good idea!

**Comment by mitchellh** [comment]
Thanks! I also am very aware that in the last few 0.7.x releases it has been quite annoying to see them but I have to stress that the changes being tested are HUGE and we probably won't have core changes that large again for awhile.
