### ISSUE TITLE
"Terraform show" in subfolder requires passing the .tfstate file

### ISSUE THREAD

**Issue by stevenmdatt** [hashicorp/terraform#10124]
Hi, 

I've noticed an inconsistency in how parameters are being parsed/detected between "terraform plan" and "terraform show". 

### Behaviour

When running "terraform show", and passing a folder name as a parameter to the command, the resulting output specifies the following error: 

"Error reading file: seek foldername: The handle is invalid."

To bypass this, I've passed the .tfstate file to the command. For example: 

terraform show foldername\terraform.tfstate

And have had this work as expected.

### Expected Behaviour

Passing a folder as a parameter to terraform show, should result in the current build configuration being output to the console. 

Example: passing the folder as a parameter to "terraform plan" will result in the planned output (as expected)

**Comment by stevenmdatt** [comment]
Update. 

When starting anew, and creating a first resource from a build.tf file within a subfolder, the terraform.tfstate and terraform.tfstate.backup files are created in the root, and not the subfolder from where the build.tf file is located/has been run from.

To have the terraform.state file create within the same folder as the build.tf file, I had to cd into that directory, and then run "terraform apply". 

The folder structure ends up being:

terraform `[root folder]`
- terraform.exe
- terraform.tfstate
- terraform.tfstate.backup
-- foldername `[subfolder]`
--- build.tf
--- terraform.tfstate

I'm not sure if this is intended, though to keep the current state of a machine, the terraform.tfstate file should be in the same location as where the build file is located when running "terraform apply" with a folder as a switch

**Comment by teamterraform** [comment]
Hi @stevenmdatt! Sorry for the long silence here.

We know that the Terraform commands are currently inconsistent in how and whether they understand a command line argument to select a different configuration directory. The idea of overriding the configuration directory worked okay when Terraform only had a few simple commands, but it hasn't scaled well to the various additional commands we have today that have the need for different signatures, and so while for the moment we've retained the existing cases where this worked we are generally not adding this facility to any new commands and we recommend that you prefer to `cd` into the target directory first, and run all of the Terraform commands with the current directory as the implicit configuration root.

We are still considering how to resolve this situation in the long term. It's likely that this will head towards removing the configuration directory override support from individual commands and instead having a single way to set it statefully, such as in the `terraform init` argument, but that remains to be designed and so for the moment the process of switching to the configuration directory first is the supported way to use Terraform.

With that said, the `terraform show` command has changed a lot since you opened this issue, and now works with remote backends rather than local state files. It can still _support_ local state files, but the way it works is quite different than it was when you opened this issue, and should not return the error you saw.

We're going to close this now because the direct problem it represents should no longer be present, and because splitting the working directory and the configuration directory isn't a usage pattern we can recommend. We know it's been a long time since you opened this, so your situation is probably quite different by now, but hopefully the above makes sense. Thanks for reporting this!
