### ISSUE TITLE
terraform does not plan changes when the only ingress rule is deleted from aws_security_group 

### ISSUE THREAD

**Issue by drscre** [hashicorp/terraform#10267]
terraform v0.7.11

I have an aws_security_group with a single ingress rule
```
resource "aws_security_group" "mysql" {
  name = "mysql"

  ingress {
    from_port = "3306"
    to_port = "3306"
    protocol = "tcp"
    cidr_blocks = ["192.168.100.5"]
  }
}
```
Then i delete that single ingress rule, which leaves me with an empty security group:
```
resource "aws_security_group" "mysql" {
  name = "mysql"
}
```

But terraform does not detect changes: terraform plan says nothing has changed.

**Comment by catsby** [comment]
Hey @drscre – I'm going to close this as a duplicate (https://github.com/hashicorp/terraform/issues/2151). It's a known issue that we'd like to resolve but don't have a solid solution for at this time. 

The rules here are of type `Optional` and `Computed`, so when the last element of an `Optional` and `Computed` item is removed, Terraform then just assumes the configuration option wasn't provided, and the element it has in state is fine to remain because it's a computed element that came from the remote API. 

The best workaround right now is to taint the resource. This kind of detection is something we need to add but do not have an ETA for at the moment.
