### ISSUE TITLE
provider/aws: Allow adding an RDS instance to an OpsWorks stack

### ISSUE THREAD

**Issue by mcheshier-switch** [hashicorp/terraform#10278]
Hi HashiCorp, I was building out my OpsWorks layer and noticed that the documentation for OpsWorks mySQL layers at:

https://www.terraform.io/docs/providers/aws/r/opsworks_mysql_layer.html

appears to be a duplicate of a regular application layer.

Are mySQL layers currently supported? I'm hoping this is just a simple copy/paste error or something, but I'd really like to know before proceeding with Terraform on OpsWorks.

Thanks!

**Comment by stack72** [comment]
Hi @mcheshier-switch 

Please can you tell me if this is still an issue for you? Sorry it took so long to get back to you :(

Paul

**Comment by mcheshier-switch** [comment]
Yes, it still looks wrong. The page appears to be a copy of this one:

https://www.terraform.io/docs/providers/aws/r/opsworks_custom_layer.html

instead of talking about mySQL layers specifically.

**Comment by apparentlymart** [comment]
Hi @mcheshier-switch!

All of the Opsworks layer types have very similar structure, so their documentation is intentionally very similar. With that said, it's possible that we missed something while writing these docs. Is there something specific you see missing from the MySQL docs page that you were hoping to use?

**Comment by apparentlymart** [comment]
@mcheshier-switch unfortunately your screenshot didn't come through to github, but I did dig into the code and it looks like the two additional attributes for the MySQL layer type (compared to the custom layer type) are `root_password` and `root_password_on_all_instances`, which are presumably the ones you saw and thought were not correct.

It's very possible that OpsWorks has added some additional attributes since we implemented this resource, but I wasn't able to see any extra ones in [the relevant docs](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_CreateLayer.html#API_CreateLayer_RequestParameters).

If you wouldn't mind trying again to send that screenshot (maybe drag it in via the web IO rather than trying to reply via email?) that might help us to map back from what you're seeing there to how it's expressed in the API.

**Comment by mcheshier-switch** [comment]
OK, sending the screenshot this way.

![rds_opsworks](https://cloud.githubusercontent.com/assets/15003169/24431764/d0d1372a-13d2-11e7-9da0-a89b180bb76a.png)

**Comment by apparentlymart** [comment]
Oh, I see... you are attempting to connect an RDS instance into your Opsworks stack, which is different than a MySQL layer. (A MySQL layer is an EC2 instance managed by OpsWorks that has MySQL installed on it.)

Terraform does not currently support attaching RDS instances into a stack, but that'd be a good thing to support! Let's consider this issue to be a feature request for that.

For the future reference of someone implementing this, it looks like the new API action we need to wrap is [RegisterRdsDbInstance](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_RegisterRdsDbInstance.html).

**Comment by mcheshier-switch** [comment]
Sounds good. Thanks for taking a look!

**Comment by apparentlymart** [comment]
Actually @mcheshier-switch I apologize... in my quick skimming I missed it.

We actually do have a resource [aws_opsworks_rds_db_instance](https://www.terraform.io/docs/providers/aws/r/opsworks_rds_db_instance.html), which I think is what you're looking for here.

So I'm going to close this, but please let me know if I'm mistaken and this resource doesn't actually do what you need here.
