### ISSUE TITLE
Joint destroy and apply command to avoid "human single point of failure"

### ISSUE THREAD

**Issue by dgonzalez** [hashicorp/terraform#10285]
This is a feature request.

So far, and as far as I am aware, terraform gives control to one user to apply or destroy changes. This is ok for the majority of the cases but up to a certain extent, some organisations might want to have a joint actuation on infrastructure. As an example, Vault, in order to unseal the database, can be configured to have a key spread across many users so that, not a single user can reveal the secrets stored.

It would be fantastic if Terraform could be configured to do something similar to that.

**Comment by mitchellh** [comment]
This is a feature we provide with [Terraform Enterprise](https://www.hashicorp.com/terraform.html).

I believe this is out of scope for Terraform itself. The reason we put it into TFE is because TFE has a server component where it can centralize all approvals. **Please note that I'm not saying no here just because its in TFE (on the contrary, I've brought down many features that were originally only TFE to TF OSS).** What you're suggesting is that we bring in some sort of Shamir's secret sharing into TF OSS for the purpose of approvals. I think this is out of scope of TF itself. I'd rather see another tool wrap Terraform with Shamir's (similar to TFE, but it can be OSS, just not in TF itself), since I don't believe that fits with the architecture of the OSS.
