### ISSUE TITLE
Releasing Manic?

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#10323]
This is not really an issue but I notice Terraform is being released multiple times a week recently.  Do you have a criteria on what causing a release?  Because of a major bug fixing or it's just random hitting the releasing button?

Thanks.

**Comment by mitchellh** [comment]
Hello!

We haven't been releasing more than usual, or at least much more than usual. We try to get a patch release out every week to two weeks, since they generally contain a number of new resources people are excited for. You can see our 0.7.x history to see that.

We've also been releasing 0.8 betas alongside 0.7.x but they're pretty unrelated: we've done both in parallel since we treat 0.7.x as our stable tree and 0.8.0 is currently in beta.

We did mess up a couple releases during 0.7.x that caused us to release again within 24 hours. These mistakes are generally constrained to just a single resource, and not a critical core Terraform flaw. 

In general:

  * We try to release every 7 to 14 days
  * We will prioritize a release for new features (for example we prioritized 0.7.12 this week for AWS Lambda env vars, otherwise we may not have released until next week)
  * We do betas/RCs in parallel to a stable tree

So you should expect probably at least one TF release every 7 to 14 days.

You don't need to upgrade to every one! Not at all. Its actually very rare that people do. Check the changelogs and see what has changed and if you want to upgrade. We only recommend upgrading to the latest major (0.x) release before the NEXT major release is out. For example: if you're on 0.6, we're about to release 0.8 and you'll be quite a bit behind at that point since we're still introducing backwards incompatibilities during 0.x that you want to stay up to date on.

**Comment by mitchellh** [comment]
I should add that something that'll slow down our release cycle a LOT is when we split out providers into separate release cycles. We plan on doing that only when we have a mechanism in place in Terraform itself to manage these updates.

When we do that, we'll be able to update for example AWS separately from Google. This will let Terraform core (which doesn't change too often) update relatively infrequently while the providers update whenever there are enough changes.

Since everything is bundled into a single "terraform" at the moment we have to release quite rapidly.
