### ISSUE TITLE
Route53 Multiple MX Records aren't being created when using JSON syntax

### ISSUE THREAD

**Issue by max-l-weaver** [hashicorp/terraform#10339]
I am using JSON syntax to create records in Route53. When I try to create multiple MX records in JSON it only creates one, whereas if I replicate this using HCL it works as expected

### Terraform Version
0.7.13

### Affected Resource(s)
aws_route53_record

### Terraform Configuration Files

Json:
```
{
    "resource": {
        "aws_route53_record": {
          "domaincom": {
                "domaineumx": {
                     "records": [ 
                    "10 ASPMX3.GOOGLEMAIL.COM.",
                    "5 ALT2.ASPMX.L.GOOGLE.COM.",
                    "10 ASPMX2.GOOGLEMAIL.COM.",
                    "5 ALT1.ASPMX.L.GOOGLE.COM.",
                    "1 ALT1.ASPMX.L.GOOGLE.COM."
                ],
                "ttl": "3600", 
                "type": "MX", 
                "zone_id": "${aws_route53_zone.mediaeu.zone_id}", 
                "name": "domain.com"
            }
        }
     }
}
```

HCL:
```
resource "aws_route53_record" "infecteu_mx_test": {
                          zone_id = "${aws_route53_zone.mediaeu.zone_id}"
                          name = "domain.com"
                          type = "MX"
                          ttl = "600"
                          records = [
                          "10 ASPMX3.GOOGLEMAIL.COM.",
                          "5 ALT2.ASPMX.L.GOOGLE.COM.",
                          "10 ASPMX2.GOOGLEMAIL.COM.",
                          "5 ALT1.ASPMX.L.GOOGLE.COM.",
                            "1 ALT1.ASPMX.L.GOOGLE.COM."
                        ]
}
```

### Debug Output
Output when using HCL:

```
 fqdn:               "" => "<computed>"
  name:               "" => "domain.com"
  records.#:          "" => "5"
  records.1230088543: "" => "5 ALT1.ASPMX.L.GOOGLE.COM."
  records.1673871233: "" => "1 ALT1.ASPMX.L.GOOGLE.COM."
  records.2184021452: "" => "10 ASPMX2.GOOGLEMAIL.COM."
  records.844049340:  "" => "5 ALT2.ASPMX.L.GOOGLE.COM."
  records.93015695:   "" => "10 ASPMX3.GOOGLEMAIL.COM."
  ttl:                "" => "600"
  type:               "" => "MX"
  zone_id:            "" => "xxxxxxxxxxxxxxx"
```
output when using JSON:

```
aws_route53_record.infectiouseu_google10_1: Modifications complete

```
no other reference to domain

### Expected Behavior
should have created 5 MX records under the name 'domain.com' in Route 53

### Actual Behavior
What actually happened?
only created one, which seemed to be randomly selected from the list every time I destroyed / re-created

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by max-l-weaver** [comment]
It appears now that even doing it in HCL fails to create the records correctly, yet the terminal output confirms the records have been created

**Comment by apparentlymart** [comment]
Hi @max-l-weaver! Sorry this isn't working as expected.

I think you might have an error in your JSON input: you have an extra level of nesting of `"domaineumx"` inside `"domaincom"`, so as far as Terraform's parser is concerned I guess it sees the resource as having only one attribute `"domaineumx"`, which is then ignored because it's not an expected attribute for `aws_route53_zone`.

Assuming I'm reading that right, the fix would be to adjust this so that there isn't this additional level of nesting. For example:

```js
{
    "resource": {
        "aws_route53_record": {
            "domaineumx": {
                "records": [ 
                    "10 ASPMX3.GOOGLEMAIL.COM.",
                    "5 ALT2.ASPMX.L.GOOGLE.COM.",
                    "10 ASPMX2.GOOGLEMAIL.COM.",
                    "5 ALT1.ASPMX.L.GOOGLE.COM.",
                    "1 ALT1.ASPMX.L.GOOGLE.COM."
                ],
                "ttl": "3600", 
                "type": "MX", 
                "zone_id": "${aws_route53_zone.mediaeu.zone_id}", 
                "name": "domain.com"
            }
        }
    }
}
```

It is curious that Terraform isn't raising an explicit error saying that `domaineumx` is not a valid argument to `aws_route53_record`. That feels like a bug to me, but not one that should be a blocker for you getting the behavior you want here.

**Comment by max-l-weaver** [comment]
Hi @apparentlymart , thanks for the reply. Sorry I think that was a typo on my part. Checking it back against my actual code it seems I have done as your example suggests. I am currently working around this issue by using HCL for creating MX records. Thanks

**Comment by apparentlymart** [comment]
Hi again @max-l-weaver! Sorry that didn't work out.

It's tricky to figure out what's going on with your original examples because the HCL and JSON don't seem consistent with one another. I assume this is because you did some editing of one or both of these examples before sharing. Would you mind sharing literally what you tried in each case, so we can better understand what is causing the difference in behavior? If you'd prefer not to show your true domain then that's fine, but please be sure to redact both examples consistently so that we can see what is *really* different between the two versions.

**Comment by max-l-weaver** [comment]
Hi @apparentlymart, sorry for the delay, been on annual leave. I'll upload asap

**Comment by teamterraform** [comment]
Hi @max-l-weaver!

We didn't hear back from you, so hopefully you found a suitable path forward here.

One of the improvements in Terraform 0.12 was improving the handling of JSON input so that it would always follow a consistent set of rules. The mapping from native Terraform syntax to JSON constructs is documented as [JSON Configuration Syntax](https://www.terraform.io/docs/configuration/syntax-json.html).

We do still recommend preferring native syntax unless a particular configuration file is being automatically generated by some other software, but this new JSON syntax implementation should make it easier to understand how to translate a particular construct from native syntax into equivalent JSON.
