### ISSUE TITLE
Wrong version shown - v0.7.13 shows as v0.8.0-dev

### ISSUE THREAD

**Issue by vincentkwok** [hashicorp/terraform#10357]
Just updated to 0.7.13 but it says it is v0.8.0-dev

```shell
$ terraform --version
Terraform v0.8.0-dev
```

**Comment by stack72** [comment]
Hi @vincentkwok 

Apologies for the error here - we will try and get this rectified asap!

Paul

**Comment by mitchellh** [comment]
![2016-11-25 at 12 15 pm](https://cloud.githubusercontent.com/assets/1299/20634735/df04f956-b308-11e6-8b41-8f983c52edee.png)

This appears to be incorrect. Did you build from the tag? The tag is pointing to the wrong commit.

**Comment by cblecker** [comment]
@mitchellh I know Homebrew builds off the tarball generated by the tag. That's how I'm seeing this issue:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb#L6-L7

**Comment by mitchellh** [comment]
Whoooops big mistake on my part. I'll retag (signed) right now.

**Comment by mitchellh** [comment]
Retagged. Darn. Sorry folks.

**Comment by cblecker** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/7239 to get the re-tag updated in Homebrew. Thanks @mitchellh !

**Comment by Ninir** [comment]
Thanks @mitchellh !

**Comment by cblecker** [comment]
Homebrew fix has been merged, and bottles rebuilt. If you were experiencing this issue using Homebrew, try this now:
```
brew reinstall terraform --force
```

**Comment by MikeMcQuaid** [comment]
Cross-posting from https://github.com/Homebrew/homebrew-core/pull/7239:

In future: please don't retag Git-based projects for a few reasons:
- when you retag you break the from-source build for anyone using Homebrew (and also possibly other projects)
- when you retag we don't know until a PR is filed whether it was intentional or you've been hacked
- we (and you) now can't easily differentiate between users using the old tag or the new one as they have the same Homebrew version number (@mistydemeo: on our end we should probably make retags mandate revisions)
- when you retag anyone who has done `git fetch --tags` and runs it again will not receive an updated tag. This is because Git is designed to not update tags as they are meant to be permanent. Retagging in Git-land is equivalent to force-pushing to a public branch (i.e. bad)

As a result of all this the best thing to do in this case is a `0.7.14` or `0.7.13.1` release. Thanks!

**Comment by jamtur01** [comment]
+1 - not just Homebrew - re-tagging is bad all around. Much better to do a new release. Learned that the hard way a couple of times. :)

**Comment by mitchellh** [comment]
Agreed!

**Comment by xueshanf** [comment]
Anyway to get a v0.8.0 binary version? I brew-upgraded to 0.8.0 thinking I was on 0.7.13 and have done some work with v0.8.0. Now some of the terraform states are on version 0.8.0. In an attempt to re-run brew, I got down-graded to 0.7.13, now I cannot run terraform against resources that are already in v0.8.0...

**Comment by xueshanf** [comment]
Never mind. I get 0.8.0-dev from backup.

**Comment by stack72** [comment]
Hi @xueshanf - sorry for the trouble here! You can download the 0.8.x binaries from https://releases.hashicorp.com/terraform/

**Comment by xueshanf** [comment]
@stack72 Got it. Thank you!

**Comment by philipl** [comment]
So, if we've done this and now have a state file that is marked for 0.8.0, how do we get it back to work with 0.7.13?

**Comment by Ninir** [comment]
@philipl If you didn't use any of the 0.8.X features / resources, you can probably try to open the `.terraform/terraform.tfstate` file, and update the `terraform_version: 0.8.X` line to `terraform_version: 0.7.13`.
Let us kknow if you still have issues!

**Comment by philipl** [comment]
@Ninir Thanks! That actually worked. The last time we had a prematurely upgraded state file, I couldn't edit it back no matter what I did. I'm glad it was simple here.
