### ISSUE TITLE
Missing source_security_group_id in aws_security_group_rule causes terraform to timeout on rule creation

### ISSUE THREAD

**Issue by lopopolo** [hashicorp/terraform#10377]
### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group_rule

### Terraform Configuration Files
```hcl
variable "bastion_security_group_id" {}

resource "aws_security_group" "backend" {
  name_prefix = "${var.name}-backend-sg-"
  vpc_id      = "${var.vpc_id}"

  tags {
    Name = "${var.name}-backend"
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ssh from bastion
resource "aws_security_group_rule" "ssh-to-backend" {
  type                     = "ingress"
  protocol                 = "tcp"
  from_port                = 22
  to_port                  = 22
  security_group_id        = "${aws_security_group.backend.id}"
  # source_security_group_id = "${var.bastion_security_group_id}"
}
```

### Expected Behavior
Terraform should have reported an error on security group rule creation

### Actual Behavior
The rule did not get created and terraform kept checking for its existence fore 5 minutes before timing out

### Steps to Reproduce
`terraform apply`

**Comment by rvandegrift** [comment]
I've hit this too - the problem seems to be that terraform accepts security group rules that have no source.  I bet adding `cidr_blocks` or `self` to @lopopolo's config would also result in a successful creation.  Ideally, rules with no source would trigger an error.

The docs are also misleading here - even though each of these three is optional, at least one must be specified.
