### ISSUE TITLE
Using outputs as resources inputs doesn't force execution order

### ISSUE THREAD

**Issue by blaltarriba** [hashicorp/terraform#10392]
Hi there,

As far as I know, when we want to force an order execution one way is to use element's outputs as an input of anothers. 

I have project with a module and resources and I want the module is executed first of all. To force that, I'm using a module output as input of resources but this is not working and resources are executed before the module.

### Terraform Version
Terraform v0.7.10

### Terraform Configuration Files
```hcl
module "rest-api-add-http-method-post" {
         source = "....."   
         rest_api_id = "${var.rest_api_id}"
         rest_api_resource_id = "${var.rest_api_resource_id}"
         rest_api_resource_path = "${var.rest_api_resource_path}"
         http_method = "${var.http_method}"
         resource_integration_type = "${var.resource_integration_type}"
         region = "${var.region}"
         account_id = "${var.account_id}"
         aws_lambda_function_name = "${var.aws_lambda_function_name}"
}

##############################
# HTTP code responses for POST method
resource "aws_api_gateway_method_response" "201" {
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.rest_api_resource_id}"
  http_method = "${module.rest-api-add-http-method-post.http_method}"
  status_code = "201"
}

resource "aws_api_gateway_integration_response" "integration-response-201" {
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.rest_api_resource_id}"
  http_method = "${module.rest-api-add-http-method-post.http_method}"
  status_code = "${aws_api_gateway_method_response.201.status_code}"
}

resource "aws_api_gateway_method_response" "400" {
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.rest_api_resource_id}"
  http_method = "${module.rest-api-add-http-method-post.http_method}"
  status_code = "400"
}

resource "aws_api_gateway_integration_response" "integration-response-400" {
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.rest_api_resource_id}"
  http_method = "${module.rest-api-add-http-method-post.http_method}"
  status_code = "${aws_api_gateway_method_response.400.status_code}"
}

resource "aws_api_gateway_method_response" "500" {
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.rest_api_resource_id}"
  http_method = "${module.rest-api-add-http-method-post.http_method}"
  status_code = "500"
}

resource "aws_api_gateway_integration_response" "integration-response-500" {
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.rest_api_resource_id}"
  http_method = "${module.rest-api-add-http-method-post.http_method}"
  status_code = "${aws_api_gateway_method_response.500.status_code}"
}
```

### Expected Behavior
Module is executed before resources.

### Actual Behavior
Resources are executed before the module.

Executing `Terraform plan`:

![execution plan](https://cloud.githubusercontent.com/assets/3491087/20660793/a0c784e8-b54b-11e6-8081-f18611bba50d.png)

### Steps to Reproduce
1. `terraform apply`

**Comment by jbardin** [comment]
Hi @blaltarriba,

The plan here looks like what I would expect. What are you seeing happen out of order during apply?

**Comment by jbardin** [comment]
Sorry, I'm having trouble seeing exactly what's going on here, but it may be because I haven't used the api_gateway much. 

I assume that error is because the `rest_api_id` isn't set correctly? The plan shows that value is being computed, but can you see what the computed value was? You can save the trace log to a file with `TF_LOG=trace TF_LOG_PATH=/path/to/trace.log`, and search for the aws api calls (feel free to sanitize and post the log in a gist or email if you want us to review it). 

I think the problem may be that you need to reference the attributes from the `module.rest-api-add-http-method-post` module, rather than the local vars to get the dependencies you want, but It's hard to tell without a complete config to reproduce the issue. Terraform doesn't execute "modules" as a whole, so a resource referencing a single module output doesn't guarantee the entire module is executed before that resource.

**Comment by blaltarriba** [comment]
Hi @jbardin 

In this case, `rest_api_id` is already set. The problem is that module `rest-api-add-http-method-post`adds the method POST to already exist API at AWS API Gateway and after that I want to add some responses to this method that's why I would like firstly the module were executed.

I'm going to see the trace log as you suggest, but I think it's failing because I'm trying to add a method response to a method which doesn't exist yet.

**Comment by jbardin** [comment]
Thanks, I think I understand what you're doing now.

You're setting the value for`rest-api-add-http-method-post.http_method` from a variable which is already defined, so the `aws_api_gateway_method_response` has no dependency on the `aws_api_gateway_method` inside the module. In other words, both of those resources depend on the variable, but not on each other, so they're likely going to be created in parallel. 

I think what you need here is a separate output from the module, set by the `http_method` attribute from the resource, i.e. `aws_api_gateway_method.METHOD_NAME.http_method`

One other option that's coming in v0.8 is that `depends_on` will now be able to reference an entire module. I'm not necessarily recommending that here, since you should be able fix the dependencies directly, but it's worth noting.

**Comment by mitchellh** [comment]
@jbardin is right: Terraform is doing the right thing here.

Your dependency never leads to the resource that creates that API method so we're not depending on _that_ part of the resource. In 0.8 you can set an entire resources in `depends_on` to wait for the whole thing.

To explain another way, perhaps slightly visually. If you have a module like this where each level of nesting is a dependency (`output.Data` depends on `resource.A` inside `module`):

```
module
|-- resource.A
|-- resource.B
|-- output.Data
    |-- resource.A
```

Then if you depend on `output.Data`, Terraform will only ensure that `resource.A` happens first. `resource.B` is free to happen anytime.

**Comment by blaltarriba** [comment]
I tried what you suggest @jbardin to set the `http_method` attribute from the resource and it works!

With v0.8 all of this will be much cleaner, I will upgrade as soon as it was available.

Thank you guys for your replies and help!
