### ISSUE TITLE
[openstack_compute_instance_v2] local-exec runs before security_groups is applied

### ISSUE THREAD

**Issue by krjensen** [hashicorp/terraform#10393]
I have a local-exec trying to connecting to my newly crated instance, but fails because [security_groups] are applied later than local-exec.

```
resource "openstack_compute_instance_v2" "test-01" {
  name = "ops-lb-01"
  image_name = "NSVPX-ESX-ova"
  flavor_name = "m1.medium"
  key_pair = "${var.key_pair}"

  security_groups = ["default", "${openstack_compute_secgroup_v2.test-01.name}"]
  
  network {
	port = "${openstack_networking_port_v2.lb-vip-port.id}"
  }
  
  provisioner "local-exec" {
	command = "powershell ./../global/netscaler/ns-upload-files.ps1 -nsip ${openstack_networking_floatingip_v2.ops-lb-01-mgmt-ip.address}"
  }
}
```

**Comment by jtopjian** [comment]
@krjensen Sorry for the late reply on this one.

It looks like you're also specifying an `openstack_networking_port_v2`. This resource can have security groups applied to it. I'm curious if this problem goes away if you create the security group using `openstack_networking_secgroup_v2` rather than `openstack_compute_secgroup_v2` and apply it to the port:

```hcl
resource "openstack_networking_secgroup_v2" "test-01" {
  ...
}

resource "openstack_networking_port_v2" "lb-vip-port"
  ...
  security_groups_ids = ["${openstack_networking_secgroup_v2.test-01.id}"]
}
```

Normally, using `openstack_compute_secgroup_v2` _should_ work. It should apply the security group synchronously to the instance so `local-exec` is triggered after it has been applied, but maybe the Neutron driver you are using is altering this behavior.
