### ISSUE TITLE
Error msg "illegal" when specify variable in command terraform plan

### ISSUE THREAD

**Issue by bexie** [hashicorp/terraform#10429]
Hi there,

Terraform showed illegal when I specify a variable thru command, could you help out here?

### Terraform Version
0.7.13

> terraform plan -var 'as_maxsize=2'
illegal
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

**Comment by blaltarriba** [comment]
Hi @bexie 

As the message relates to an error into your configuration file you should check you have that variable correctly defined in your configuration file, you should have something like this:

```
variable "as_maxsize" {}
```

**Comment by jbardin** [comment]
Hi @bexie,

Can you provide a config that can reproduce this error? I'm not sure what could be cause the output with just the single word "illegal".

**Comment by apparentlymart** [comment]
This is an error from the HCL scanner.

I made a config file containing just an `@` sign. Ran terraform against it:

```
$ ~/apps/terraform/terraform plan
illegal
Error loading config: Error parsing /tmp/illegal-tf/foo.tf: At 1:1: illegal char
```

**Comment by mitchellh** [comment]
@apparentlymart It actually looks like the HCL parser/scanner handles this properly, it just shouldn't print out "illegal". It does record an error and eventually show it to the user.

**Comment by mitchellh** [comment]
https://github.com/hashicorp/hcl/pull/172

**Comment by apparentlymart** [comment]
There's still the question about what's invalid in @bexie's config files... @bexie, was there a specific change you made to your config just before you started seeing this error? I expect you made a change that inadvertently introduced a syntax error into the config, and this is just the HCL parser telling you (poorly) that there is a syntax error.

**Comment by bexie** [comment]
Hi guys, 

Thanks for responding :) This is how I define the variable in the main.tf:
variable "as_maxsize"   { description = "Maximun how many instance can be launched in the autoscaling group" }

There are a couple of other variables defined in main.tf having default value in .tfvars, 'as_maxsize' does not have a default value, not sure if that's the cause. If I do not specify variable in the command line but leave it to terraform to ask for variable input, it goes well without any problem. 

This is first time I tried to specify variable in the command, so I can't tell if it appeared only after a specific change.

**Comment by apparentlymart** [comment]
@bexie the same bit of code that we were looking at above is also used, in some cases, to parse the value of a `-var` argument, but I wouldn't expect this to happen here because your variable value is entirely numeric. Are you setting any other `-var` arguments to *non-numeric* values?

If this were an error in parsing the variable value I'd expect there to be an error message starting with something like the following in the Terraform output:

```
Cannot parse value for variable as_maxsize ("2") as valid HCL: ...
```

Unfortunately Terraform issues are not a great place to have ongoing troubleshooting discussions like this because it's easy to lose track of them. If the above doesn't help figure out what's going on, it might be best to move this discussion either onto the mailing list or onto the Glitter chat, depending on what's more comfortable for you. You can find more info on these at [the Community page](https://www.terraform.io/community.html).

**Comment by bexie** [comment]
Hi @apparentlymart , I just did a quick test, I created a new folder with a single file main.tf in it, in the main.tf, there is only one line: 
variable "as_maxsize"   { description = "Maximun how many instance can be launched in the autoscaling group" }
cd to the folder, and this is the result of the command:
> terraform plan -var 'as_maxsize=2'
illegal
illegaTlh
ere are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* Required variable not set: as_maxsize

**Comment by apparentlymart** [comment]
Hi @bexie.

I tried what you said on a build of Terraform v0.7.13 (the version you mentioned in your original comment introducing this issue), but was unfortunately unable to reproduce it:

```
$ terraform plan -var 'as_maxsize=2'
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

This behaved as I would've expected for a configuration that only contains a variable, and doesn't contain any resources.

Since you've now successfully reduced this down to a simple test configuration, would you mind trying that same test on the latest 0.8 release candidate [0.8.0-rc2](https://releases.hashicorp.com/terraform/0.8.0-rc2/)? I'm curious to see if you still get an error, and *if so* whether the error is different than what you saw before.

Also, which OS are you running Terraform on?

**Comment by bexie** [comment]
Hi @apparentlymart 

I installed the latest, and run the plan command, appeared it didn't recognize the -var param, it asked to input param again, which obviously eliminated the error but it's not what is needed, here is the output:

D:\workspace\testTerraformVar
λ terraform --version
Terraform v0.8.0-rc2 (a6ac5bed69d95f8fc7c9bfd04072fd3a795224d0)


D:\workspace\testTerraformVar
λ terraform plan -var 'as_maxsize=2'
var.as_maxsize
  Maximun how many instance can be launched in the autoscaling group

  Enter a value: 2

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.

**Comment by apparentlymart** [comment]
I notice from your latest message that you are using Terraform on Windows. Argument parsing works differently on Windows so it's possible that it is necessary to write this argument in a different way to get the intended effect. I don't have a Windows system on which to test, but I would suggest trying since things like:

```
-var="as_maxsize=2"
-var as_maxsize=2
-var=maxsize=2
```

If you see different behavior when using some if these forms then that would confirm my theory. If I am lucky, maybe one of them will even solve your problem!

The potential issue here is that on Unix-ish systems (Linux, Mac OS X, etc) it is the responsibility of the system shell to split the command line into an array of strings as parameters, but on Windows the whole command line is passed as a single long string to the program and it must do its own parsing. As a result, a syntax that works on a Unix system as a result of the shell might not work the same way on Windows, where Terraform itself (or, more accurately, the Go runtime library) must decide for itself how to do this parsing.

**Comment by apparentlymart** [comment]
I found some MSDN docs on how the arguments are parsed on Windows, since I can see in the Go source code that Go delegates to a Windows API function for this parsing:
https://msdn.microsoft.com/en-us/library/windows/desktop/17w5ykft(v=vs.85).aspx

Based on this it seems that single quotes are not supported on Windows, but double quotes `"` are allowed and so my first example in the previous comment ought to work.

I think your original "invalid" message was caused by Terraform's parser seeing those single quotes and failing to deal with them, since single quotes are not valid in HCL.

**Comment by bexie** [comment]
Hi @apparentlymart 

These 2 worked:
-var="as_maxsize=2"
-var as_maxsize=2

Thanks a lot :)  

btw, any chance to get it updated here: https://www.terraform.io/docs/configuration/variables.html for others reference?

**Comment by apparentlymart** [comment]
Updating the docs does seem like a good idea but I couldn't see any examples on this page of the single quote syntax you used. Did I miss it?

In general the commamd line examples in Terraform docs are likely to be Unix-centric right now because Windows support came later, after the docs were written. There are probably many examples there to update. :concerned:

**Comment by bexie** [comment]
yep, that's true, I saw it in one of the docs using single quotes then I just copied. Never mind, people will google to this answer if they see same issue. Thanks again @apparentlymart , really appreciated :)
