### ISSUE TITLE
aws_instance continously recreated

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10457]
As a user I would expect that running `terraform apply` any finite number of times after a first run with an exit status of 0, will result in no action from Terraform (i.e. "infrastructure is up to date"). This is not what happens. Instead the bastion node is destroyed and recreated after every `apply`.

I am not implying that the below text is enough to recreate this problem as it is part of a larger configuration. My recommendation is to add a debug mode to Terraform which minimizes a given configuration and then cleans it off any company specific tokens. This way your engineers don't need to spend time on finding reproducible cases.

Version: 0.7.13. I'd love to see a new release too.  

```
resource "aws_instance" "bastion" {
  ami = "ami-9398d3e0" 
  instance_type = "t2.micro"
  key_name = "foo"
  associate_public_ip_address = true
  subnet_id = "${aws_subnet.public.0.id}"

  security_groups = ["${aws_security_group.bastion.id}", 
                     "${aws_security_group.ecs_node.id}"  
  ]

  tags {
    Name = "bastion-bar"
    Environment = "bar"
  }
}
```

I would say the problem is that this "0" => "2" change is not correct. (I do not make any changes during runs.)
```
    security_groups.#:           "0" => "2" (forces new resource)
    security_groups.1162657440:  "" => "sg-13c04d75" (forces new resource)
    security_groups.2592457552:  "" => "sg-5cbb393a" (forces new resource)
```

**Comment by stack72** [comment]
Hi @fubarbaz 

My apologies for the issue here - the issue you are facing is that security_groups are for EC2 classic instances only - your instance is in a subnet, therefore, it will require you to specify the config as follows:

```
vpc_security_group_ids = ["${aws_security_group.bastion.id}", 
                     "${aws_security_group.ecs_node.id}"  
  ]
```

This is from this part of the [documentation](https://www.terraform.io/docs/providers/aws/r/instance.html#security_groups)

Please do let us know if you think we should make this clearer then please do let us know! Our documentation can sometimes do with some improvements

Thanks

Paul

**Comment by fubarbaz** [comment]
Yes, just make it barf with the message you have just written down. It is something which can be checked at "compile time". It should be considered to be an invalid configuration.   

Adding another resource type would also work. I.e. an aws_ec2_classic instance and a new one. 

I am very happy with your response time.
