### ISSUE TITLE
aws_vpc reconstruction fails if an aws_internet_gateway is linked to it

### ISSUE THREAD

**Issue by dan-passaro** [hashicorp/terraform#10465]
### Terraform Version
v0.7.7

### Affected Resource(s)
- aws_vpc
- aws_internet_gateway

### Expected Behavior
When changing the CIDR block of a VPC, the VPC is recreated and all resources are rebuilt as a result.

### Actual Behavior
Since the gateway doesn't need to be destroyed, it isn't, but it also is never unassigned, so an attempt to destroy the VPC times out because the Gateway dependency stops it from being removed.

### Steps to Reproduce
1. Make an aws_vpc
2. Make an aws_gateway, using the new VPC's ID for vpc_id
3. `terraform apply`
4. Change the CIDR block of the aws_vpc
5. `terraform plan` and confirm the vpc is due for reconstruction, and the gateway's vpc_id will be modified in-place
6. `terraform apply` and watch the process fail. The VPC cannot be destroyed while the gateway points to it.

**Comment by mitchellh** [comment]
This is tough. There is an issue somewhere that notes that `depends_on` should probably force recreate when it changes and thats probably what we'd have to lean on here. 

Since the dependency between these two is reasonably implicit, Terraform's built-in dependency resolution can't figure this out automatically so we're going to have to rely on some manual work.

There is no way to do this right now, unfortunately, other than `terraform taint` on your gateway. :(
