### ISSUE TITLE
RDS multi_az error

### ISSUE THREAD

**Issue by sp-ruben-simon** [hashicorp/terraform#10487]
Hi there,

I have an RDS configured without MultiAZ but now I want to enable it, if I set multi_az to "true" and apply changes, terraform says that everything is ok but MultiAZ still disabled, if you try to apply again you receive an error.

### Terraform Version
v0.7.13

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "rds" {
  allocated_storage         = 10
  engine                    = "mysql"
  engine_version            = "5.7.11"
  instance_class            = "db.t2.micro"
  identifier                = "identifier"
  name                      = "rds"
  username                  = "user"
  password                  = "password"
  final_snapshot_identifier = "final-snapshot"
  vpc_security_group_ids    = ["${aws_security_group.rds.id}"]
  db_subnet_group_name      = "${aws_db_subnet_group.rds.id}"
  backup_retention_period   = 21
  backup_window             = "03:00-05:00"
  publicly_accessible       = false
  multi_az                  = false
}
```

### Panic Output
```
* aws_db_instance.jarvis-rds: Error modifying DB Instance jarvis-lomt: InvalidParameterCombination: No modifications were requested
	status code: 400, request id: e8d9b34f-b87e-11e6-8a9d-ff2c3fbe494b
```

### Expected Behavior
Update rds with MultiAZ

### Actual Behavior
Error

### Steps to Reproduce
1. Set multi_az to true.
2. `terraform apply`

**Comment by stack72** [comment]
Hi @sp-ruben-simon 

Thanks for opening the issue here - sorry you are getting some inconsistent results

For this specific change, you need to add another parameter:

```
apply_immediately = true
```

What happens with RDS, is that RDS will be notified of a pending change and it will happen during the next maintenance window. By implementing the apply_immediately, RDS will actually reboot your instance and perform the changes

Check out the warning at  the top of the documentation about apply_immediately - https://www.terraform.io/docs/providers/aws/r/db_instance.html

Hope it helps

Paul

**Comment by sp-ruben-simon** [comment]
Thanks @stack72
