### ISSUE TITLE
[feature]Static resource limits

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10574]
In order to have a quick exit path, I would like to see terraform compute the required resources for the plan and compare those with the resource limits configured for the account. This way, if I want to deploy let's say 1000 nodes (something larger than our account supports), it should simply make no changes to the infrastructure and return an informational error message with the service limits that would have to be raised in order for this to work. 

At some later point in time, it could actually ask for a message to be entered, such that a message could be generated which could then be sent to the cloud provider listing the specific number of resources required, which would be beneficial to the cloud provider's resource planning staff. 

I am currently only interested in AWS, but preferably it would work for any provider.

**Comment by mitchellh** [comment]
This heads into the area of Terraform understanding the semantics of a cloud provider more deeply. While this is a grey area for us (we do some basic field validation), we tend to choose the side of Terraform not understanding these semantics. 

The reasoning:

1. The semantics of cloud providers is a particularly large, under-specific domain. We'll likely never reach 100% coverage and we'll probably make mistakes.

2. It adds another thing for us to support as clouds change. We already must support every feature change (which we accept since thats the goal of the project!) but modifying Terraform for every semantic change we've concluded to be overly complex.

3. APIs do a fantastic job of this already: Terraform will try to do something, and the API will say no. This lets the burden of correctness lie on the core agent of change (the cloud control plane).

The primary reason most folks (you included it sounds like) want us to encode semantics into Terraform is faster feedback. I agree that'd be nice but I think faster feedback doesn't outweigh the immense, exceptionally large cost of implementing this.
