### ISSUE TITLE
Terraform doesn't detect conflicting actions

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#10596]
At my work we just experienced a brief outage that was caused by a misunderstanding (or perhaps an oversight) of how Terraform works. Basically, Terraform applied two changes which were conflicting: one change was to create a DNS record and the other change was to destroy the same DNS record. The ordering in which these actions were applied meant that the DNS record was inadvertently removed.

I can reproduce this issue with the following config:

```
resource "aws_route53_zone" "test" {
  name = "mydomain.com"
}

resource "aws_route53_record" "test" {
  zone_id = "${aws_route53_zone.test.zone_id}"
  name    = "app${count.index}"
  type    = "A"
  ttl     = 3600
  records = ["127.0.0.1"]
  count   = 4
}

resource "aws_route53_record" "legacy" {
  zone_id = "${aws_route53_zone.test.zone_id}"
  name    = "app4"
  type    = "A"
  ttl     = 3600
  records = ["127.0.0.1"]
}
```

I then changed the configuration to this:

```
resource "aws_route53_zone" "test" {
  name = "mydomain.com"
}

resource "aws_route53_record" "test" {
  zone_id = "${aws_route53_zone.test.zone_id}"
  name    = "app${count.index}"
  type    = "A"
  ttl     = 3600
  records = ["127.0.0.1"]
  count   = 5
}
```

`terraform plan` shows the following changes to be applied:

```
- aws_route53_record.legacy

+ aws_route53_record.test.4
    fqdn:               "<computed>"
    name:               "app4"
    records.#:          "1"
    records.3619153832: "127.0.0.1"
    ttl:                "3600"
    type:               "A"
    zone_id:            "Z1AO8T26EKO0J1"
```

The resulting state is dependent on the ordering of these steps that Terraform executes them in.

**Comment by apparentlymart** [comment]
Ahh yes... this is an unfortunate problem that arises for resources where the underlying api doesn't distinguish between "create" and "update", and so Terraform can't honor its usual promise not to interact with something it didn't create.

It is a tricky issue. Back in the early days of what later became the "data sources" design we talked about the idea of a resource that lacks a "create" action but still has all of the other resource verbs, in which case Terraform would immediately try to refresh the resource during plan so it could show an update diff rather than a create when appropriate, but that had some scary consequences with Terraform implicitly "importing" a resource, and in any event would not have helped in this specific case because you created and deleted at the same time. :(

In order to understand this situation Terraform would need a way to correlate these two resources and understand that they are really the same thing. That seems hard to generalize into a provider interface, but maybe there is a way if we think hard about it...

**Comment by mitchellh** [comment]
I don't think this is something Terraform should necessarily solve in the short term. In my opinion it did the right thing, there was no real reason for it to think it did anything wrong. I think @apparentlymart is right that we can make Terraform a lot more clever in the future... but for now what I recommend in these scenarios is using `-target`.

I think introducing a way to see the ordering up to a specific `-target` might be interesting too, so you can see the ordering that things will happen...
