### ISSUE TITLE
Keep old Terraform created task definitions around for a configurable number

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10600]
It can be useful to keep a configurable number of previous versions of https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html around. This configurable number could be part of the ecs_task_definition.

**Comment by stack72** [comment]
Hi @fubarbaz 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
