### ISSUE TITLE
How can we use the terraform one terraform state to create another state ?

### ISSUE THREAD

**Issue by vikash009** [hashicorp/terraform#10661]
Hi all,

I am trying to create 20 virtual machine in azure. So i divided this task in 3 steps.
1. Infrastructure creation : It will create all infrastructure like, resource group, virtual network, subnet. availability group etc,
2. 10 virtual m/c with some configuration.
3. 10 virtual m/c with some other configuration.
All my tf files i have kept in different directory. 
So my question is after completion of step 1, How can i use all resources of step 1 in step 2 and step 3

I don't want to copy all .tf files to again to directory 2 and 3.

**Comment by apparentlymart** [comment]
One way to achieve this is using [the `terraform_remote_state` data source](https://www.terraform.io/docs/providers/terraform/d/remote_state.html). This allows one Terraform configuration to read the outputs of another.

In order to do this you must be using [remote state](https://www.terraform.io/docs/state/remote/index.html) so that the results of each configuration are available somewhere and can be retrieved by that data source. The general idea is:

* Use `terraform remote config ...` (as described on the Remote State docs page) on your infrastructure configuration, to publish its state to a remote storage backend.
* Use The `terraform_remote_state` data source your second and third configurations, with the same settings you used in the `terraform remote config` command, to *read* what was published.
* Make sure that your infrastructure config has `output` blocks that expose the elements of the infrastructure that you want to make use of in the other two configurations.

In the above setup, the infrastructure would get created only once and then your configurations 2 and 3 would share it, which I think is what you are asking.

If instead you are planning create two identical copies of the infrastructure, where configurations 2 and 3 each have their own distinct networks, etc then that would be a use-case for [modules](https://www.terraform.io/docs/configuration/modules.html), which would allow you to make the infrastructure configuration a separate repository that can be referenced by both of your other configurations, so you would avoid the need to duplicate the configurations but you would still get a duplicate set of physical resources, keeping the two configurations physically isolated.

It's hard to keep track of ongoing discussion threads within github issues, so if you have more questions or would like more detail I would suggest using either the mailing list or the Glitter chat. You can find out more about both of these on [the community page](https://www.terraform.io/community.html).
