### ISSUE TITLE
Cycle: aws_launch_configuration.ecs (destroy), aws_ecs_service.another

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10698]
During a `terraform apply` I get the following:
```
Cycle: aws_launch_configuration.ecs (destroy), aws_ecs_service.another
```

The problem is that the program claims there is a cycle, but it does so in a format, which is not clear to me as the user. Additionally, if I `terraform destroy` and then recreate everything from scratch, it does work. 

The `ecs` resource might have changed, but it should then be replaced, not destroyed. 

This is with version 0.8.0-dev.

**Comment by mitchellh** [comment]
Can you please share with us a set of configurations we can run from our own machines (not dependent on your infrastructure) with a set of steps (can be as simple as `terraform apply`, we just want to be clear) to reproduce this?

At a bare minimum, we'll need a `TF_LOG=debug` level log. You can get that by setting that env var.

Without reproduction steps it is very difficult for us to fix an issue. Not impossible, but very difficult. :) In this case, there isn't enough information in the issue or us to make meaningful progress.

When you get a repro case please just reopen a new issue following the template given, which guides you to giving us a repro case. Thanks!

**Comment by fubarbaz** [comment]
I think the way to fix this error is to provide a better error message. I.e. something which clearly states the cycle, including the source code which was used to define those and why that would be a problem. Then the error message I can report would be also be more clear. 
Regarding the TF_LOG=debug, do you have some method of removing sensitive data from those? I would not mind sending telemetry data back automatically, assuming it was done properly. In fact, I think on error, it could just run again and produce a bug report automatically. 

Writing bug reports is annoying enough as it is, as is fixing them. Making it easy to report good bugs should have some priority.

**Comment by mitchellh** [comment]
In the error message currently, we're showing everything we know unfortunately. The steps taken are full graph construction and then cycle detection. During cycle detection, we only node the vertices which form the cycle (which we show), not _why_ they are there.

I agree it'd be wonderful to have this information, and if someone opened a PR to do so or even a deeper RFC of how to do so, I'd love to work with them to bring it in. Unfortunately it isn't a priority right now and we're working through other bugs and improvements, but I'll keep this idea in mind.

As for sending log messages: we don't have any automated way to remove sensitive info, and we can't even fully control it (since some 3rd party libraries add sensitive info to their logs that we don't control) so there isn't a 100% way for us to do it. I really wish we could automate it though.
