### ISSUE TITLE
count property referenced using a remote state value

### ISSUE THREAD

**Issue by marranz** [hashicorp/terraform#10705]
Hey,

When the count property is set referencing a value stored into an external state file, it fails returning this error message:

* data.template_file.user-data-standalone: resource count can't reference resource variable: data.terraform_remote_state.rds.standalone_rds

The variable referenced in the count property is '0' or '1'. (checked via output)

when the value is set manually  (=0 or =1) everything works properly.

Using terraform v0.7.13

```

data "terraform_remote_state" "rds" {
    backend = "s3"
    config {
        bucket = "xxxx-state-xxxx"
        key = "xxxxx-rds-play-deploy/terraform.tfstate"
        region = "xxxx"
    }
}


data "template_file" "user-data-standalone" {
    template = "${file("templates/user-data.tpl")}"
    count = "${data.terraform_remote_state.rds.standalone_rds}"
    vars = {
        db_endpoint = "${data.terraform_remote_state.rds.db_endpoint_standalone}"
    }
}
```

The value in the remote state file is the following:

```
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {
                "cluster_rds": {
                    "sensitive": false,
                    "type": "string",
                    "value": "0"
                },
                "db_endpoint_standalone": {
                    "sensitive": false,
                    "type": "string",
                    "value": "tf-20161213161653297661338xhk.cypgspihfcoj.eu-west-1.rds.amazonaws.com:3306"
                },
                **"standalone_rds": {
                    "sensitive": false,
                    "type": "string",
                    "value": "1"**
                }
            },
```

So it seems that the problem is not only when interpolating from modules as seen on the issue #9206 , also from external state.

**Comment by apparentlymart** [comment]
Hi @marranz! Thanks for this report and sorry we let it languish for so long.

As of Terraform 0.9.0 it is possible to use data resource attributes in `count` as long as their values are known during plan, which should be the case for your example here. In future we plan to generalize this further to allow computed values in `count` via a multi-step process as described in #4149, but for most cases the change we made in 0.9 should be sufficient.

I'm going to close this, since the main case is now supported. Thanks again for opening this issue!
