### ISSUE TITLE
Infrastructure as Code / DSL incompatibility

### ISSUE THREAD

**Issue by coen-hyde** [hashicorp/terraform#1071]
First off great project! But I have a bone to pick. Terraform's DSL defeats the purpose of having infrastructure as code. The nature of a DSL is that it's limited in scope for a specific use case. This sounds good at first but it means that any "outside the box" scenarios require functionality to be developed for the DSL. So at the moment Terraform is closer to "infrastructure as configuration". Terraform would be more powerful if terraform scripts were a real scripting language. 

Anyway keep up the good work. Just food for thought. I would like to hear your thoughts on the subject.

**Comment by knuckolls** [comment]
Here are my thoughts on the subject. Having a rigid configuration syntax is important because Terraform is declarative, like SQL. The "query planner" effectively ensures that the correct things are occurring, in the correct order, and corrects drift as it arises. When it comes to maintaining a sufficiently large infrastructure the primary concern is maintainability and reasonability. The HCL format, with it's overrides, supply a way to keep the configuration human readable and visualizeable.

Your concern of course, is valid. There will always be the need for custom logic. The remote-exec and local-exec provisioners allow you to hang code onto the correct places in the execution of the dependency chain. Furthermore, the entire configuration language itself is extendable with plugins written in go. Custom needs can be expressed in the resource CRUD framework, which is actually quite nice. Then you can supply nodes of custom logic to the correct places in your dependency graph.

By limiting the expressiveness of the configuration to just "what should execute and when", we ensure that hardened software under the covers solves that problem and solves it well. We are thereby freed up to introduce imperative logic and the bugs that come along with such at the right parts in the execution graph. Thus it becomes a game of hardening a tier of infrastructure at a time, writing logic for doing post-deploy verification, and composing those tiers together one by one. 

I consider Terraform's declarative nature to be it's defining trait. One that subsequent tooling will likely emulate to optimize for maintainability.

**Comment by coen-hyde** [comment]
Thanks for the in-depth explanation @knuckolls, much appreciated. This makes sense, I understand why Terraform chose declarative DSL now. Closing.

**Comment by mitchellh** [comment]
@coen-hyde I want to just add one small detail to what @knuckolls said (which is all correct and very well written!): HCL is also fully JSON compatible, which we also test in the unit tests (so its not a 2nd class citizen, it was designed specifically to be JSON compatible). While this isn't a true "scripting language", this also avoids the issue of HCL simply being some custom bespoke format: it can be thought of as human-readable/editable syntactic sugar on top of JSON.
