### ISSUE TITLE
TLS handshake timeout when configure s3 as remote backend in v >= 0.8-rc3

### ISSUE THREAD

**Issue by micahlmartin** [hashicorp/terraform#10718]
This previously worked in at least the last 4 version of 7.x to 0.8-rc2. I noticed it break first in 0.8-rc3 and is also breaking in 0.8.0.

### Terraform Version

`Terraform v0.8.0`

### Affected Resource(s)

s3 remote config

### Debug Output

https://gist.github.com/micahlmartin/97db1ddce752a908b56d285145aaadbe

### Expected Behavior
It should configure s3 as the remote backend

### Actual Behavior
Throws a TLS timeout error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```
terraform remote config \
  -backend=s3 \
  -backend-config=bucket=mybucket \
  -backend-config=key=global/vpc_mgmt.tfstate \
  -backend-config=region=us-east-1
```

**Comment by mitchellh** [comment]
I can communicate to S3 (almost exactly your example). The only change that happened in RC3 was we upgraded to Go 1.7.1. 

This includes only two changes, one of which is this security fix for Darwin: https://github.com/golang/go/issues/18141

One other user was getting the same error as you and determined that the cert to talk to a remote service (it wasn't S3, but same error) was explicitly blocked, causing the 1.7.4 security fix to "break" Terraform. Perhaps this is the same with you?

Otherwise, this looks like a system error since we haven't touched any remote state code or S3 remote state backend code in many releases. 

If you can determine more information please let us know, but I tried on two systems (both macs) and this worked for me.

**Comment by shinzui** [comment]
Looks like a homebrew issue. I was getting the same error, but it worked once I switched to the [official macOS binary](https://www.terraform.io/downloads.html).
