### ISSUE TITLE
Please document "(deposed)"

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#10753]
After updating to 0.8.0, I ran `terraform plan` against some existing infrastructure to see if the new version wanted to make any changes. I saw surprised to see a bunch of "deposed" resources:

```
- module.onc-dc2506.aws_instance.apps (deposed)

- module.onc-dc2506.aws_instance.symq (deposed)

- module.onc-dc2507.aws_instance.apps (deposed)

- module.onc-dc2507.aws_security_group.sg_apps (deposed)

- module.onc-dc2507.aws_security_group.sg_blaz (deposed)

- module.onc-dc2507.aws_security_group.sg_colb (deposed)

- module.onc-dc2507.aws_security_group.sg_cust (deposed)

- module.onc-dc2507.aws_security_group.sg_msgx (deposed)

- module.onc-dc2507.aws_security_group.sg_mydb (deposed)

- module.onc-dc2507.aws_security_group.sg_ngnx (deposed)

- module.onc-dc2507.aws_security_group.sg_pgdb (deposed)

- module.onc-dc2507.aws_security_group.sg_sftp (deposed)
```

As a fairly new Terraform user, I didn't know what this meant, so I [searched the documentation](https://www.google.com/search?q=deposed+inurl%3Ahttps%3A%2F%2Fwww.terraform.io%2Fdocs&ie=utf-8&oe=utf-8), but none of the found pages actually use the term "deposed" anywhere, so I'm still not sure what it means.

I still need these resources, and it seems as if terraform is planning to destroy them, so I need to understand deposed to bring them back properly. Could someone please add this to the documentation?

**Comment by egarbi** [comment]
it seems to me that deposed is intended to remove unused (old) resources from your state.
For me this one has been deposed:
- aws_security_group.extended_elb (deposed)

and after "apply" I can still see it in AWS console. so, i think is safe, but agree with you, we need docs

**Comment by apparentlymart** [comment]
Definitely this should be added to the docs somewhere, but in the mean time for folks who are upgrading to 0.8 and seeing this:

"Deposed" is the state a resource goes into when Terraform is dealing with `create_before_destroy`... since there can only be one "primary" instance of a given resource, Terraform will first *depose* the existing one (so it's still tracked in state but no longer used for interpolations), then create the replacement instance before finally deleting the deposed instance.

Errors during that process can cause the *deposed* instance to stick in the state, since Terraform doesn't want to lose track of them before it can delete them. However, this behavior was a little inconsistent in earlier Terraform versions, and also Terraform handled deposed instances silently rather than including them in the plan output.

So all of this is to say: these *deposed* instances are leftovers from a failure during the replacement of these resources with `create_before_destroy`. If you look in the Terraform state file (either `terraform.tfstate` or `.terraform/terraform.tfstate` depending on whether you have remote state enabled) you should find the records of these by searching for the word `deposed`; you can use the data Terraform has stored for these to decide if they are safe to delete before letting Terraform proceed here.

**Comment by rcha86** [comment]
@apparentlymart When you say "this behavior was a little inconsistent in earlier Terraform versions," what exactly do you mean? We are working on upgrading to 0.8, and I remember seeing issues in 0.7 where the _new_ resource ended up in the deposed list due to a failed apply. Then, on a successful apply, the _new_ resource was destroyed. Because that _new_ resource had the same name as the one created during the successful run, we had a very bad time.

Is that the different behavior you are describing? Avoiding that situation is one of the reasons we are moving to 0.8.

**Comment by apparentlymart** [comment]
In 0.7 deposed resources were dealt with silently, so I don't have a good sense of exactly what Terraform was doing with them, but due to limitations/bugs of the graph processing in 0.7 it would frequently accumulate deposed resources and not actually clean them up. Thus when upgrading to 0.8 it can be the case on first run that the new graph processing, which *explicitly* deals with deposed and mentions it in the output, can find a set of deposed resources that were being ignored in 0.7 and try to clean them up.

The new graph rules in 0.8 explicitly support deposed in both the plan and apply phases, so you now see deposed resources appear in the plan output where previously they were just dealt with silently, or not at all. In general this is nothing to worry about, but during an upgrade I would advise checking the state to make sure that these previously-invisible resources are indeed things that should be destroyed. In all cases where I upgraded Terraform on my work infrastructure the resources were all things that actually ought to have been destroyed, so I just let Terraform clean them up and haven't had to deal with it since, but YMMV especially if you saw 0.7 do strange things with deposed.

**Comment by bflad** [comment]
Hi, everyone! 👋 Thank you for this great suggestion of adding documentation.

Fairly recently, a new [Terraform Glossary](https://www.terraform.io/docs/glossary.html) page was introduced on the documentation website to provide a location for various Terraform terminology. A new entry for `deposed` was published today: https://www.terraform.io/docs/glossary.html#deposed

If you have further documentation suggestions, including other missing terminology, please feel free to create [new GitHub issues](). Thanks!
