### ISSUE TITLE
External provider stores full path to command in state file causing thrash when executing on different machines

### ISSUE THREAD

**Issue by lopopolo** [hashicorp/terraform#10777]
### Terraform Version
`Terraform v0.8.1`

### Affected Resource(s)
Please list the resources as a list, for example:
- external data source

### Terraform Configuration Files
```hcl
data "external" "bastion-ingress" {
  program = ["bash", "${path.module}/external/my-ip.sh"]
}
```

### Expected Behavior
What should have happened?

Terraform stores path relative to terraform root in state file

### Actual Behavior
What actually happened?

```json
                "data.external.bastion-ingress": {
                    "type": "external",
                    "depends_on": [],
                    "primary": {
                        "id": "-",
                        "attributes": {
                            "id": "-",
                            "program.#": "2",
                            "program.0": "bash",
                            "program.1": "/Users/lopopolo/x/y/z/terraform/.terraform/modules/ac5c735a3940e3c1dad95eef6511f232/external/my-ip.sh",
                            "result.%": "1",
                            "result.cidr": "x.y.z.a/32"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-8768

**Comment by apparentlymart** [comment]
Hi @lopopolo. Sorry for this surprising behavior.

This is a specific case of the issue described in #7927, namely that using `path.module` anywhere will cause unnecessary diffs when shifting configurations between machines. Also semi-related to #8204, where `path.module` causes a different but similar problem.

Our best workaround for now is to use the `ignore_changes` feature to instruct Terraform to not consider changes to this attribute when producing a diff. This is of course not great because it means *actually* changing the command to run won't do anything, but hopefully this works for you in the mean time.

I'm going to close this to consolidate discussion in #7927, but thanks for taking the time to file this issue!

**Comment by wr0ngway** [comment]
In case anyone tries to use ignore_changes, lifecycle blocks don't seem to work on data sources like external

**Comment by apparentlymart** [comment]
Looking at this again, it occurs to me that the full path being in the state is a little confusing but in most cases should be harmless: since this is a data resource, Terraform will refresh it for each `refresh` or `plan` command anyway, discarding the previous state.

My previous comment about `ignore_changes` was a bad suggestion. I assume at the time that I hadn't noticed we were talking about a data resource, and was instead thinking about the general problem described in #7927, for which that is the workaround.
