### ISSUE TITLE
Support lifecycle rules for S3 buckets as top level resources

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#10770]
It would be useful to be able to delegate the creation of lifecycle rules to modules which own parts of the namespace of a shared S3 bucket (for example, for backups). Currently they must all be specified in line, but in principle it looks like there is no reason in principle this could not be broken out optionally into a top level resource.

**Comment by stack72** [comment]
Hi @jen20 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72

**Comment by jen20** [comment]
This was a request for HashiCorp internal use, so I assume someone there
will pick it up at some point ;-)

>

-- 
James
