### ISSUE TITLE
Dependency not being Honoured

### ISSUE THREAD

**Issue by rmenn** [hashicorp/terraform#10781]
### Terraform Version
v0.8.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_launch_configuration
- aws_autoscaling_group

I am seeing this after an upgrade to 0.8.1, it was working well before. 

### Terraform Configuration Files
TF - Module : https://gist.github.com/rmenn/b1c3f54e92b0447590a5038df18b3cf2

Standard Module which creates and updates an ASG and its Launch Config

Currently unable to update the the AMI in the LC.  Create before destroy mentioned within the LC. From the logs it looks like it is trying to destroy the LC prior to  

Errors out with 
```
* aws_launch_configuration.elb-lc (deposed #0): ResourceInUse: Cannot delete launch configuration green-20161212085914964297100k6p because it is attached to AutoScalingGroup green
```

### Debug Output
https://gist.github.com/rmenn/16ce7cf907479132492ca4857fcbee40

### Expected Behavior
Prior to this we were able to update the AMI in the LC then apply it to the ASG

### Actual Behavior
Errors out with 
```
* aws_launch_configuration.elb-lc (deposed #0): ResourceInUse: Cannot delete launch configuration green-20161212085914964297100k6p because it is attached to AutoScalingGroup green
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Is there a way to downgrade the statefile? i could grab the debug output from the same scenario and post that as well.

**Comment by rmenn** [comment]
Is there a way to downgrade the statefile? i could grab the debug output from the same scenario and post that as well.

**Comment by apparentlymart** [comment]
Hi @rmenn. I'm not really familiar with the issue here but I just wanted to offer a bit of explanation and suggest a possible workaround.

First, what Terraform is trying to do here is delete a resource that was replaced with the `create_before_destroy` flag set; Terraform keeps track of the not-yet-destroyed resource by marking it as "deposed" until it's safe to delete.

You should be able to see the data about the resource Terraform is working with here by running the following command:

```
terraform state show aws_launch_configuration.elb-lc.deposed
```


It seems that some inconsistency has arisen that is preventing Terraform from deleting this resource. I'm not sure why exactly that is (I will have to leave detailed debugging to someone else) but one way to proceed would be to get Terraform to "forget" about this desposed instance so that Terraform can proceed with all of the other work it needs to do:

```
terraform state rm aws_launch_configuration.elb-lc.deposed
```

*However*, I would suggest exercising caution when taking this path: once Terraform has "forgotten" about this resource it will remain in your AWS account until manually cleaned up. You should only do this if you are sure that the resource in question is indeed defunct (i.e. it has been replaced with a new instance that is currently active). You should be sure to make a note of the output of the `terraform state show` command above so that you will be able to track down this resource in the AWS console for manual cleanup later.

This workaround doesn't actually address the immediate problem at hand, but rather side-steps it so that you can continue working with other aspects of your configuration without being blocked. Given the content of the error message it seems likely that there is also a leaked autoscaling group which wuld need similar treatment.

**Comment by rmenn** [comment]
@apparentlymart so here was the work flow prior to this rising

Existing Resources : LC + ASG

Update ami on LC then the new LC(2) would get updated on ASG then then the older LC(1) would get destroyed. Which is why we modeled our AMI deployment in this way, at this time TF seems to know of a non existent LC(x) and tries to destroy the existing LC(1) which AWS does not permit you to do as its associated to an ASG. 

The Behavior that was previously seen was update LC(1) -> LC(2) -> Associate to ASG -> Destroy LC(1). 

This has changed with the upgrade which is why i feel it is to do with the core/graph especially cause it does not honor the create before destroy. TRACE shows that it tries to destroy but no indication of creating the new LC(2) prior to it. 

Please let me know if i can run tests and get the data for you to fix this, or if you point me in the right directions, i could take a whack at it.

**Comment by mitchellh** [comment]
I'm going to try to reproduce this but in the mean time it looks like your debug log was cut short. Do you mind gisting the entire thing? Please check for any sensitive values and scrub. Thanks!

**Comment by rmenn** [comment]
@mitchellh would you consider accepting it on a private channel?

**Comment by mitchellh** [comment]
@rmenn Absolutely, feel free to email me directly (email on GH profile)

**Comment by rmenn** [comment]
@mitchellh done, thank you

**Comment by mitchellh** [comment]
Haven't looked at your debug log yet, will do. But I tried with your config with slight modifications and couldn't get this to reproduce with 0.8.1.

### Configuration

```
variable "nodes" { default = 1 }

resource "aws_launch_configuration" "elb-lc" {
  name_prefix          = "foo"

  image_id             = "ami-25363832"
  //image_id             = "ami-1aa1e370"

  instance_type        = "m3.medium"

  enable_monitoring = false
  ebs_optimized     = false

  placement_tenancy = "default"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "elb-asg" {
  name               = "foobar"
  availability_zones = ["us-east-1b"]

  max_size                  = "${var.nodes}"
  min_size                  = "${var.nodes}"
  desired_capacity          = "${var.nodes}"
  wait_for_elb_capacity     = "${var.nodes}"
  wait_for_elb_capacity     = "${var.nodes}"
  health_check_grace_period = 60
  health_check_type         = "ELB"
  desired_capacity          = "${var.nodes}"
  force_delete              = false
  vpc_zone_identifier       = ["subnet-c4c78b8d"]
  launch_configuration      = "${aws_launch_configuration.elb-lc.name}"
}
```

### Steps

1. `terraform apply`
2. Swap the `image_id` comment to change the image 
3. `terraform plan`: verify that LC is destroy/create, ASG is in-place update
4. `terraform apply`

### Graph

This is the graph I get, which is correct:

![graph](https://cloud.githubusercontent.com/assets/1299/21275050/d6dd6664-c37f-11e6-8e86-f21fae54088c.png)

### Next

I'll take a look at your debug log next to see what I might be missing.

**Comment by rmenn** [comment]
I dont get a failure on plan, so im guessing the graph is formed correctly. Please let me know i am doing something incorrectly.

**Comment by mitchellh** [comment]
@rmenn That was an apply graph, not a plan graph. :) `terraform graph foo.tfplan`

**Comment by mitchellh** [comment]
Ah, I see the issue in your log (won't post any sensitive info):

```
2016/12/17 00:23:28 [INFO] CLI args: []string{"/usr/local/bin/terraform", "apply", "-target=module.foo-01.aws_launch_configuration.elb-lc"}
```

You're targeting the launch configuration directly. The launch configuration change doesn't require updating the ASG (if you targeted the ASG this would all work correctly). 

This is interesting, there is an argument to be made that performing the full LC CBD requires an ASG so targeting should include that as well... I kind of agree with this. I'll take a look.

In the short term: target your ASG, not your LC.

**Comment by mitchellh** [comment]
For what it's worth, I just tried targeting an LC with 0.7.13 as well as 0.8.1 and your same error occurs in 0.7.x as well, so this isn't a regression, this has always been the behavior.

**Comment by rmenn** [comment]
But the LC change in itself does throw an error. Wait, it does not throw an error? :throws self off a bridge: we were using this for like a couple of weeks and never saw it. 

I have sent you the logs with the asg apply, is there a way i can downgrade my statefile to test this, as i believe this was a working solution.

**Comment by rmenn** [comment]
@mitchellh looks like it was bad config on my end, thanks for taking the time to look into it. My colleague @hashfyre figured it out. Adding a `create_before_destroy = true` to the asg resolved the dependency error. 

Again, thank you for taking the time. Looking forward to 0.9
