### ISSUE TITLE
AWS IAM Role Trust Policy not refreshing state

### ISSUE THREAD

**Issue by rjinski** [hashicorp/terraform#10790]
### Terraform Version
0.7.13

### Affected Resource(s)

- aws_iam_role
- aws_iam_role_policy

### Terraform Configuration Files
```hcl
provider "aws" {
    region = "eu-west-1"
}

data "aws_iam_policy_document" "action_policy" {
    statement {
        effect = "Allow"
        actions = [
            "*"
        ]
        resources = [
            "*"
        ]
    }
}

data "aws_iam_policy_document" "trust_policy" {
    statement {
        effect = "Allow"
        actions = [
            "sts:AssumeRole"
        ]
        principals {
            type = "Service"
            identifiers = [
                "ec2.amazonaws.com"
            ]
        }
    }
}

resource "aws_iam_role" "role" {
    name = "test-role"
    assume_role_policy = "${data.aws_iam_policy_document.trust_policy.json}"
}

resource "aws_iam_role_policy" "policy" {
    name = "test-policy"
    role = "${aws_iam_role.role.id}"
    policy = "${data.aws_iam_policy_document.action_policy.json}"
}

```

### Output

_Apply complete! Resources: 0 added, 0 changed, 0 destroyed._

### Expected Behavior
When this code runs it successfully creates my role. However, if manual changes are made to via the console to the trust policy, for example changing `ec2.amazonaws.com` to `lambda.amazonaws.com` and terraform is reapplied it does not refresh state for the role and update the policy. 

This same behavior is observed for a `terraform refresh`.

### Actual Behavior
I'd expect that terraform would reload the actual resources state in AWS, see a different in the trust policy in terraform configuration and update the resource.

### Steps to Reproduce

1. terraform apply
2. make a manual change to the trust policy via AWS console
3. terraform apply
4. validate that the manual change is still present

**Comment by myoung34** [comment]
This just bit me big time with opsworks and is the direct cause of https://github.com/hashicorp/terraform/issues/6605

I use a module to create IAM service role, IAM instance role, and opsworks stack.
If the IAM service wrong is created with `ec2.amazonaws.com`, opsworks stack will fail.
Because state has not completed, terraform cannot remove the IAM roles.

Remove them via UI, `terraform apply` works, gets to opsworks create and gives ` ServiceError: Service Role Arn: Credential has not the necessary trust relationship.`

The only fix is to change the name of the IAM role or purge the history of this from Terraform altogether. At this point without getting rid of it from state, I can never use it because it will always be `ec2.amazonaws.com` despite changes to the trust relationship.

**Comment by btai24** [comment]
@myoung34 I ran into this exact problem today. If I want to use the same name of the IAM role, how do I purge the history of this?

**Comment by myoung34** [comment]
I ended up just using a different name for the IAM role/profile and it was resolved
