### ISSUE TITLE
New provider: compose.io

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform#10793]
Compose.io has recently released a new version of their API which enables all of their database types (MongoDB, PostgreSQL, Redis, Elasticsearch, RethinkDB, RabbitMQ, etcd, MySQL, and Scylla) to be accessed via the API:

* https://apidocs.compose.com/
* https://www.compose.com/articles/database-updates-and-the-new-compose-api/

It'd be great to be able to manage these with Terraform.

**Comment by mwarkentin** [comment]
Came across https://github.com/cam-stitt/terraform-compose, but it doesn't look like it's gotten too far.

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!
