### ISSUE TITLE
Using quotes within functions

### ISSUE THREAD

**Issue by ameir** [hashicorp/terraform#10812]
Hello,

I am using https://github.com/aol/terraform-php to generate HCL configs for Terraform.  When writing the following code:
```php
        $lc->user_data = '${file("userdata.sh")}';
```
it gets expanded to:
```hcl
	user_data = "${file(\"userdata.sh\")}"
```

That all seemed well at first glance, but it turns out that HCL allows quotes within quotes without escaping, and disallows escaping.

Additionally, the following does not work, either:
```hcl
	user_data = "${file('userdata.sh')}"
```
I suspect that many folks using HCL generators and `file()` (or other functions) would run into this issue.

Is it possible to have one of these variations accepted as valid?  This might be more of an HCL or HIL project issue, but figured I'd try here first.

### Terraform Version
Terraform v0.8.1

### Affected Resource(s)
This shouldn't be particular to a resource, but in my issue, I'm hitting it within `aws_launch_configuration`.  My issue is with `file()` overall (although this can be applied to other functions as well).

### Terraform Configuration Files
```hcl
	user_data = "${file(\"userdata.sh\")}"

```

### Expected Behavior
Expression should be parsed.

### Actual Behavior
```
Error loading config: Error loading <path>/terraform.tf: Error reading config for aws_launch_configuration[app-name]: parse error at 1:8: expected expression but found invalid sequence "\\"
```

**Comment by apparentlymart** [comment]
Hi @ameir! Sorry this didn't work out as expected. This is the first time I've seen this `terraform-php` project... looks pretty interesting!

As you've seen, Terraform's `${` and `}` delimiters create an entirely fresh parsing context, so the contents act as if they are not in quotes at all. I don't think we'd want to change this because it would cause extra complexity in the parser and confuse the issue about what is and is not valid HCL/HIL. The current syntax was intentional to allow nesting without creating complex situations where sometimes two or more levels of escaping would be required.

My recommendation would be that Terraform configurations generated programmatically are generally best produced in JSON. As well as being easier to produce in most programming languages, it also creates a very obvious distinction in the resulting config directory between the files that are hand-written and the files that are generated, preventing confusion for human mantainers. The JSON variant of HCL exists primarily for this purpose.

If you're still keen on generating HCL, you could make it valid by following the\ rules that HCL itself follows: quotes within balanced `${` and `}` tokens are implicitly escaped. You can see the rules in detail in [the HCL scanner's `scanString` method](https://github.com/hashicorp/hcl/blob/2b0eb1f52c2ce7e826002550ebdab698c1b594cb/hcl/scanner/scanner.go#L476).

**Comment by ameir** [comment]
No worries; I just made an update to `terraform-php` to handle this case.  The quote handling seemed a bit counter-intuitive, but I can see that it makes things easy, and that's valuable.  Feel free to close this if this isn't something that warrants action on your end.  Thanks!

**Comment by apparentlymart** [comment]
Thanks for your understanding, @ameir. I'm going to close this since you've got a workaround in your generator project.
