### ISSUE TITLE
Can't compare against a lookup or map interpolation

### ISSUE THREAD

**Issue by onlyanegg** [hashicorp/terraform#10847]
### Terraform Version
Terraform v0.8.1

### Affected Resource(s)
- Interpolation

### Terraform Configuration Files
```tf
variable "role" {
  description = "Overwrite the role variable "
  default = "plat"
}
variable "elb_role" {
  type = "map"
  description = "Role name of ELB if provisioning multiple ELBs"
  default = {
    plat = 2
  }
}
```

### Expected Behavior
Should have printed "yes"

### Actual Behavior
Got a type error

### Steps to Reproduce
```
$ terraform console
> lookup(var.elb_count, var.role)
2
> lookup(var.elb_count, var.role) > 1 ? "yes" : "no"
At column 3, line 1: <, >, <= and >= may apply only to int and float values in:

${lookup(var.elb_count, var.role) > 1 ? "yes" : "no"}
> var.elb_count[var.role] > 1 ? "yes" : "no"
At column 3, line 1: <, >, <= and >= may apply only to int and float values in:

${var.elb_count[var.role] > 1 ? "yes" : "no"}
> (var.elb_count[var.role] + 0) > 1 ? "yes" : "no"
yes
>
```

**Comment by apparentlymart** [comment]
Thanks for filing this, @onlyanegg! We discussed this a bit in Glitter chat.

The last line of the reproduction steps above is the workaround I would suggest for anyone running into this issue before it gets fixed.

I believe the issue here is that the comparison operators are not correctly promoting string operands to a numeric type as we'd do for arithmetic operators. This is the same class of problem as hashicorp/hil#43, so I may just fix them both together since it'll be touching similar areas of the code anyway.
