### ISSUE TITLE
Add Support for AWS Service Catalog

### ISSUE THREAD

**Issue by aantono** [hashicorp/terraform#10865]
It would be great to be able to manage AWS Service Catalog via Terraform - https://aws.amazon.com/servicecatalog/

**Comment by stack72** [comment]
Hi @aantono 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
