### ISSUE TITLE
strange interpolation behavior

### ISSUE THREAD

**Issue by JustLeo** [hashicorp/terraform#10879]
Hello, I'm having a strange behavior with an interpolation output and I think this may be a bug.

This is the interpolation I want to use:
```
value = "${element(aws_subnet.subnet.*.id, index(aws_subnet.subnet.*.cidr_block, cidrsubnet(var.cidr_block_vpc, 4, 1)))}"
```

Description of the variables:
`aws_subnet.subnet.*.id`: it's a flat list with all the subnets that has been created with terraform.
`aws_subnet.subnet.*.cidr_block`: same flat list but with the cidr blocks of each subnet

and I'm using `cidrsubnet` to find the index of the CIDR I need on the list of subnets, and with that index I want to get the subnet id so I can use it to create an intance on it.

PROBLEM: The interpolation is returning a subnet that is not even on the list and it also does not belong to the VPC I created. It's returning a subnet that belongs to the default VPC of AWS.

Any idea? Please help.... Thanks...

**Comment by apparentlymart** [comment]
Hi @JustLeo! We were working on this on Glitter yesterday, right?

As I think I suggested on Glitter, a different way to write this is using `zipmap` to produce a map and then look up the value in the map:

```hcl
value = "${lookup(zipmap(aws_subnet.subnet.*.cidr_block, aws_subnet.subnet.*.id), cidrsubnet(var.cidr_block_vpc, 4, 1))}"
```

...but you'd indicated that you got the same unexpected result from that.

So my next question remains the same: what happens if you just evaluate the expression `zipmap(aws_subnet.subnet.*.cidr_block, aws_subnet.subnet.*.id)` alone? If you're on Terraform 0.8 you could use the `terraform console` command to easily evaluate that expression, or if you're on 0.7 you can make a temporary additional output to see how this looks:

```hcl
output "test" {
  value = "zipmap(aws_subnet.subnet.*.cidr_block, aws_subnet.subnet.*.id)"
}
```

These interpolation functions can't access anything that wasn't already retrieved or created by Terraform, so it seems like there's a bug somewhere else in your configuration that is causing extra values to show up in this expression. My hope is that being able to see the map will help identify the issue.

Note that in general we advise against using github issues for general questions like this, because it's easy for the discussion to get lost due to the volume of new issues and that github doesn't provide good features for discussion tracking. [The project's Google Group](https://groups.google.com/forum/#!forum/terraform-tool) is usually a better place for long-form questions, since Google Groups is actually designed for discussion and so it's easier to keep track of things.

**Comment by JustLeo** [comment]
Hello, problem resolved using terraform console. I was using 0.7 and didn't know about this new feature. Do you want me to delete this post? It was not my intention to generate noise here...

**Comment by apparentlymart** [comment]
Glad you got it working @JustLeo! No big deal on opening this issue... mainly just a note that it can be easy to lose track of discussions like this and not see follow-up responses/questions, though in this case I apparently did see it. :grinning:

I'm going to close this since it sounds like you got it figured out.
