### ISSUE TITLE
Crash when trying to create GCE instance with local-ssd disk

### ISSUE THREAD

**Issue by laggyluke** [hashicorp/terraform#1088]
I think [local SSDs](https://cloud.google.com/compute/docs/disks/local-ssd) are not yet supported by Terraform, but I've tied to "brute force" it anyway and it crashed hard :(

Configuration:
```
resource "google_compute_instance" "mongodb_tmp_instance" {
    name = "staging-mongodb-instance-3"
    machine_type = "n1-highmem-16"
    zone = "europe-west1-c"
    tags = ["staging", "mongodb"]

    disk {
        image = "ubuntu-trusty"
        type = "pd-ssd"
    }

    disk {
        type = "local-ssd"
        auto_delete = true
    }

    network {
        source = "default"
    }
}
```

[Gist of crash.log](https://gist.github.com/laggyluke/373916a205e3684c63eb)

**Comment by sparkprime** [comment]
So the crash was due to a bug when specifying type but not source / image.  That is in fact only valid in the case of local ssds but it's fixed now.

The only change you need to make to use local-ssd is to add an extra attribute to the disk: scratch = true, which corresponds to the type = "SCRATCH" attribute from the APIs.  Unfortunately initializeParams.diskType is already represented as "type", causing a name clash, but the enum only has two values in it at present so I represented as a boolean for now.

Long term, I'd like to rewrite the disk support entirely to allow modifying disks without forcenew (as is already done by @phinze for AWS).  Since that will require a deprecation cycle, I will make the attributes more closely align to the GCE API at that time.
