### ISSUE TITLE
Documentation: Terraform vs. ...

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/terraform#10884]
Enhancement request on documentation (terraform/blob/master/website/source/intro/vs/index.html.markdown)

* Ansible - would like to see comparison to specifically Ansible as they have official maintained modules as part of their platform, it is probably most used platform next to Terraform for this area.  For AWS this is the single biggest competitor.
* CloudFormation - learned at a Meetup that CloudFormation is not idempotent, which is a important issue when considering which solution.  It's the difference between destroy and recreate vs. update.
* Chef/Puppet - wish there was more detail.  Some experience with Chef Provision (aka Chef Metal) and was horrible experience, often buggy, and complex (many moving parts).

In scope of a solution, most are not looking for cross-IaaS solution, but usually a particular cloud provider, e.g. AWS, and then the best of the batch for that solution.  In the scope of AWS, some shops may use AWS CLI, Boto, Fog, if they are developer centric, and with Ops look at one of the change configs (chef, puppet) or remote execution (ansible, salt), or CloudFormation.  I could not even imagine how to organize it this way, maybe have sub-sections, and high level categories, and then drill down.

**Comment by stack72** [comment]
Hi @darkn3rd 

Thanks for the request here

There is some [documentation](https://www.terraform.io/intro/vs/chef-puppet.html) available on this

Thanks

Paul

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity and the number of changes our documentation has undergone since this was opened.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
