### ISSUE TITLE
Missing documentation for null_data_source

### ISSUE THREAD

**Issue by olafure** [hashicorp/terraform#10898]
### Terraform Version
All

### Affected Resource(s)
Documentation

The documentation for the "null_data_source" data source is missing.

**Comment by evankroske** [comment]
Terraform team, would you accept a PR of this documentation?

**Comment by grubernaut** [comment]
@evankroske Absolutely!

**Comment by apparentlymart** [comment]
We initially left this a bit hidden because it didn't have a clear use-case. Much like `null_resource` it turned out to be useful as a workaround for some of Terraform's current limitations, so it does seem reasonable to document it though we should approach it as something you should rarely need to use and describe the specific scenario where it has proven useful (stashing intermediate values), so that people finding this documentation can understand what it's for and in what situations it should be used.

**Comment by abdelhegazi** [comment]
We definitely need it added to the documentation

**Comment by discordianfish** [comment]
Please add it to the documentation with the remark that it should be only used as a workaround.
