### ISSUE TITLE
Hello, is there any plan to implement a resource for AppStream2.0 in the AWS provider?

### ISSUE THREAD

**Issue by elitaylor** [hashicorp/terraform#10906]
I apologize if I raised this issue in duplicate. I wasn't able to find any other information regarding plans for AppStream 2.0. 

Thank you!

**Comment by apparentlymart** [comment]
Hi @elitaylor,

Generally supporting stuff that AWS offers is a goal, but of course that's a big surface area to cover so it helps to have some details about use-cases people want to solve to help prioritize.

Could you say a little about what you're working on that would benefit from Terraform supporting AppStream 2.0? I won't speak for anyone else but I'm totally unfamiliar with this product apart from what I just learned from skimming its product page so it's be super helpful to have a sense of what concepts from this product would be useful in Terraform and how they relate to each other, since that helps to figure out what resources would be the most useful to implement first.

**Comment by stack72** [comment]
Hi @elitaylor 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
