### ISSUE TITLE
Trigger null_resource in each run

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#10930]
Hi all,

I am looking for a way to trigger the `null_resource` to run each time I run `terraform`. Is there a way to enable `triggers` always so that I can run `null_resource` each time? I provision `docker containers` in my provision script and rerunning the provisioner even though nothing has changed in the infrastructure.

Currently I pass current timestamp as trigger to `null_resource`  so that it runs each time. is there a more clean way of doing it?

**Comment by noizo** [comment]
+1

**Comment by apparentlymart** [comment]
Hi @Puneeth-n,

This is certainly not an intended use of `null_resource`, since usual uses of Terraform expect to converge on a stable state rather than taking an action each time. Passing a timestamp as a trigger is what I would've suggested; I don't expect there would be a first-class feature added for doing this since it's considered a strange thing to do.

**Comment by Puneeth-n** [comment]
@apparentlymart Thanks for the info. Closing this issue since this approach of mine has been working without hiccups for over months now :)
