### ISSUE TITLE
[aws]ECS Task placement

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#10968]
Please add support for the following feature to aws_ecs_service:

![image](https://cloud.githubusercontent.com/assets/23215674/21561807/24e94fa6-ce72-11e6-8250-0ef8d7a07a92.png)

This is *not* part of the task definition attribute as it exists in Terraform.

**Comment by catsby** [comment]
Should be covered in https://github.com/hashicorp/terraform/pull/11030

**Comment by mykyta-protsenko** [comment]
#11030 covers placement_constraints for ECS *tasks definitions*

ECS now supports different placementStrategies for ECS *services*, which is a different thing and should be defined on aws_ecs_service level:

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html

It is a part of AWS' CreateService call:

http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html
...
`   "placementConstraints": [ 
      { 
         "expression": "string",
         "type": "string"
      }
   ],
   "placementStrategy": [ 
      { 
         "field": "string",
         "type": "string"
      }
   ],`

**Comment by spy-tech** [comment]
@catsby It isn't. https://github.com/hashicorp/terraform/issues/11077.

**Comment by catsby** [comment]
Ok I'll take a look thanks

**Comment by radeksimko** [comment]
The following attributes were introduced:
 - `placement_strategy` for `aws_ecs_service` - https://github.com/hashicorp/terraform/pull/11201
 - `placement_constraint` for `aws_ecs_service` - https://github.com/hashicorp/terraform/pull/11242
 - `placement_constraints` for `aws_ecs_task_definition` - https://github.com/hashicorp/terraform/pull/11030 - already released; part of `v0.8.4` and `v0.8.3`

The `aws_ecs_service` updates will be part of a next release.

Related documentation for ECS service is also being fixed in https://github.com/hashicorp/terraform/pull/11338

I think it's time to close this issue. Thanks to all involved. 🙂  🎉

**Comment by spy-tech** [comment]
@radeksimko No, it's not time to close this, because it does not work. 

Using Terraform v0.8.5-dev (cb4ffd466222a2bc6839ce5989a73a63ed911202+CHANGES)

I get: 
```
InvalidParameterException: distinctInstance expression should not be specified.
        status code: 400, request id: `<snip>
```
for the following placement_constraints definition as part of a `aws_ecs_service` definition. 

```
  placement_constraints {
     type = "distinctInstance"
  }
```


@catsby Based on the fact that I now had to reopen this two times now, please improve your QA processes. Don't claim something works, when you have obviously not tested it. Additionally, the documentation which has been written for these features is also wrong.

**Comment by grubernaut** [comment]
@spy-tech I apologize for that one. I had created that issue when I pushed #11298. However, I just pushed #11465 which fixes the issue, and includes the appropriate acceptance test to verify the fix. Thanks.
