### ISSUE TITLE
Escaping Remote ENV in Interpolation

### ISSUE THREAD

**Issue by delianides** [hashicorp/terraform#1098]
When using systemd on CoreOS, consider the following:

```
   - name: docker.service
      command: start
      content: |
        [Unit]
        After=flannel.service
        Wants=flannel.service
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io

        [Service]
        EnvironmentFile=/run/flannel/subnet.env
        ExecStartPre=/bin/mount --make-rprivate /
        ExecStart=/usr/bin/docker -d --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} -s=overlay -H fd://

        [Install]
        WantedBy=multi-user.target
``` 

If I place this in a heredoc (hashicorp/hcl#6) it fails because terraform tries to interpolate the FLANNEL environment variables. Is there anyway to escape those so terraform doesn't try to expand them?

**Comment by mitchellh** [comment]
Use a second dollar sign: `$${FLANNEL_SUBNET}`.

**Comment by bitglue** [comment]
Maybe this could be documented somewhere? I don't see it in the [configuration syntax](https://terraform.io/docs/configuration/syntax.html) or the [interpolation syntax](https://terraform.io/docs/configuration/interpolation.html).

But also, it doesn't seem to work. While it does avoid the syntax error due to the invalid interpolation, it also puts a literal `$$` in the resulting parsed string.

**Comment by bentterp** [comment]
I ran into the same issue with an AWS policy as a heredoc as per the documentation:

    policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iam:*LoginProfile",
        "iam:*AccessKey",
        "iam:*AccessKey*"
      ],
      "Resource": "arn:aws:iam::564070118781:user/$${aws:username}"
    },

This results in the policydocument on AWS having double $'s - which of course doesn't work
Using single $ makes terraform try to interpolate, and fail
