### ISSUE TITLE
AWS: key_pair name sometimes not resolvable before reference

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/terraform#10983]
~~Found another issue caused by AWS' eventual consistency, this time around ssh key pair creation.~~

If I declare a resource such as the following:

```
resource "aws_key_pair" "hsimpson" {
    key_name_prefix = "hsimpson"
    public_key = "${file("/Users/hsimpson/.ssh/id_rsa.pub")}"
}
```

Then subsequently refer to it:

```
resource "aws_instance" "test_instance" {
   key_name = "${aws_key_pair.hsimpson.key_name}"
   # etc
}
```

It's quite possible the key name will not yet be known by the time the instance provisioner runs:

```
Error applying plan:

1 error(s) occurred:

* Resource 'aws_key_pair.hsimpson' does not have attribute 'key_name' for variable 'aws_key_pair.hsimpson.key_name'
```

~~As with other objects, we'll need to poll for a reasonable amount of time until the name can be determined.~~

**Comment by apparentlymart** [comment]
Hi @mfischer-zd! Thanks for reporting this.

In this case that error is actually coming from Terraform itself, rather than from AWS. So I think this issue is actually a Terraform core bug rather than the usual AWS eventual consistency issue.

This error indicates that the variable lookup within Terraform itself failed. If this were an eventual consistency bug I'd expect to see a different error message that includes the actual generated key name. Terraform's graph walk is supposed to guarantee that `aws_key_pair.hsimpson` is complete before `aws_instance.test_instance` is evaluated, so this smells like a core bug to me, though might alternatively be an AWS provider bug with it not correctly populating the `key_pair` attribute.

**Comment by mfischer-zd** [comment]
Oh, ok.  FYI, running `terraform apply` when this happens does resume correctly.

**Comment by mfischer-zd** [comment]
> though might alternatively be an AWS provider bug with it not correctly populating the key_pair attribute

I think this is what's happening.  I think we need a line like:

```
d.Set("key_name", keyPair.KeyName)
```

Somewhere in `aws.resourceAwsKeyPairCreate`.

I'll see whether I can devise an effective patch.  Be gentle, please; I've barely looked at the code. :)
