### ISSUE TITLE
UnknownValue uuid makes for hard to debug issues

### ISSUE THREAD

**Issue by jagregory** [hashicorp/terraform#10990]
Hey folks,

I think I have a module dependency ordering issue, which I'll try and raise separately to this; however, whilst debugging it I kept finding the value `74D93920-ED26-11E3-AC10-0800200C9A66` in my state file, which I ultimately traced down to the [`UnknownValue` constant in HIL](https://github.com/hashicorp/hil/blob/master/convert.go#L14).

It took me a while to realise what this uuid represented. It would've been clearer had my state file contained something like `<unknown value>` or whatever, rather than a seemingly random uuid which I initially thought was a legit value (from a bad substitution perhaps).

I don't know what the intention of `UnknownValue` is, whether it represents something which can never be known or something yet to be resolved, but I guess either making Terraform go bang if it shouldn't ever make it to the state file or at least making the presence of `UnknownValue` more noticeable would be useful.

Cheers

**Comment by mitchellh** [comment]
We're well on our way to removing this UUID from usage and we'd really rather not use sentinel UUIDs at all. As it stands, this UUID is deeply entrenched and cannot simply be removed (or we'd have done it a long time ago!). We're working towards removing it, with the major step necessary being richer types diffs/states (rather than maps of strings). This would allow us to cleanly recognize (via types, versus a UUID) an "unknown value".

We're working on this but it probably will take another couple major releases before we get all the foundational nuts and bolts in place to fully rip this out.
