### ISSUE TITLE
Import an API into API Gateway from a Swagger

### ISSUE THREAD

**Issue by n-my** [hashicorp/terraform#11034]
## Context

The AWS API let us import an API from a JSON Swagger (v2.0) (see [here](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html) and [here](http://docs.aws.amazon.com/cli/latest/reference/apigateway/import-rest-api.html))

It would be nice to support this feature in Terraform. This has been already asked in [#3675](https://github.com/hashicorp/terraform/issues/3675) but it was not the original request of the issue.

As a note :
The API Gateway extensions to the Swagger specification support the AWS-specific authorization and API Gateway-specific API integrations (see [here](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html))

## Potential solutions
We could either use directly JSON files or use a data source `aws_api_swagger` to store to swagger.
Then we could update the resource `aws_api_gateway_rest_api` to specifiy a swagger.

**Comment by MarechJ** [comment]
+1

**Comment by 9bryan** [comment]
+1
Is there a way to find out if this is on the roadmap?

**Comment by richarddevers** [comment]
+1

**Comment by Vinnl** [comment]
I stumbled into this while looking for something unrelated, but it looks like https://github.com/hashicorp/terraform/pull/6175 is looking to implement this.

(As for the other commenters: you can press the Thumbs Up on the original post to +1, that saves some redundant emails.)

**Comment by stack72** [comment]
Hi @n-my 

Hi @timmytofu 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72

**Comment by combinatorist** [comment]
I've spent a couple weeks trying to get this to work. IMO, terraform needs a "doesn't really support API Gateway" on the front page / README.

If anyone has found a way to actually use API Gateway from terraform in production (without lots of manual setup), I'd love to pick your brain. Right now, I'm forced to consider alternatives like [serverless](https://serverless.com/), [Zappa](https://github.com/Miserlou/Zappa), or [CloudFormation](https://aws.amazon.com/cloudformation/).

**Comment by gtmtech** [comment]
@combinatorist , you could use a null resource with an aws cli call to upload json as a workaround - I think that's what I'll try, I just came across this issue too.

**Comment by combinatorist** [comment]
Thanks for the suggestion, @gtmtech. FWIW, I'm not as concerned about Swagger as I am about stateless support for AWS API Gateway (more below).

So, in case anyone else is curious, here's my more general solution to a more general problem. And please, if anyone knows better than I do, jump into correct me.

### API State (and Swagger)
I got the impression terraform doesn't actually support AWS API Gateway, but the fundamental issue is that **AWS API Gateway is stateful** - i.e. it cannot report out its complete, exact current state to terraform, so terraform can't know whether it needs to be modified, rebuilt, or left alone. 

The biggest advantage of Swagger would be a complete stateless description of the API, but I don't think AWS is doing it's part, so there'd still be no way to know exactly how it connects to the rest of your AWS infrastructure (e.g. your lamda functions).

So, you would have to `terraform taint` your API every time you want to update it, but this is guesswork and it may have to rebuild the CloudFront Distribution (CDN) AWS API Gateway hides under the hood (which can take a long time). Finally, all the stages in a single AWS API Gateway share the same pre-deployment version of the API so you can't be sure what you're deploying when you make a new deployment.

But I really wanted separation of environments, so I don't let AWS API Gateway manage my "stages". 

### My solution
So, I actually create a separate AWS API per stage (which correspond to my terraform environments). Unfortunately, because AWS API Gateway silently includes its own CloudFront distribution, I ultimately have to have a separate subdomain for each environment / stage of the API like so:
- api.example.com (prod)
- dev.api.example.com
- test.api.example.com

These are all variations of the same (logical) API, but they have different subdomains with different CloudFront distributions, built into separate AWS API Gateways, with separate variations of the same (logical) lambda functions and DynamoDB table.
