### ISSUE TITLE
terraform import of rancher_stack does not import current docker_compose and rancher_compose

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/terraform#11055]
### Terraform Version
v0.8.2

### Affected Resource(s)
- rancher_stack

### Terraform Configuration Files
```hcl
resource "rancher_stack" "foo" {
  name = "foo"
  environment_id = "${var.environment_id}"

  docker_compose =<<EOF
foo:
  image: foo/bar
EOF

  rancher_compose =<<EOF
EOF
foo:
  scale: 1
}
```

### Expected Behavior
Terraform import should import current docker_compose and rancher_compose.

### Actual Behavior
Terraform import does not import current docker_compose and rancher_compose.

**Comment by johnrengelman** [comment]
So you created a stack in Rancher and you're trying to import it into TF?
How was the stack created? Manually or using a catalog entry?

**Comment by mcanevet** [comment]
@johnrengelman exactly. I created the stack using a catalog entry.

**Comment by johnrengelman** [comment]
The `docker_compose` and `rancher_compose` values will not be imported in this case. However, there will be values in `rendered_docker_compose` and `rendered_rancher_compose` that correspond to the config that you can see in the Rancher API.
The `docker_compose` and `rancher_compose` values are incompatible with using the `catalog` entry for a stack.
This is due to how the Rancher API stores this data.

**Comment by mcanevet** [comment]
@johnrengelman actually I have the same issue without using a catalog entry

**Comment by johnrengelman** [comment]
Please post the config and what terraform plan says.

**Comment by stack72** [comment]
Closed via #11500

**Comment by johnrengelman** [comment]
@stack72 - how does this refreneced PR affect this issue? Doesnt seem related.

**Comment by stack72** [comment]
I'm going by the the OP put on the PR...

**Comment by johnrengelman** [comment]
The "closed via" message has the wrong number (11500 vs 11550)

**Comment by stack72** [comment]
d'oh! Sorry! Will fix now
