### ISSUE TITLE
Rancher provider crash when Rancher API key is not valid

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/terraform#11053]
### Terraform Version
v0.8.2

### Affected Resource(s)
- rancher_environment
- rancher_registration_token
- rancher_registry_credential
- rancher_registry
- rancher_stack

### Terraform Configuration Files
```hcl
resource "rancher_stack" "foo" {
  name            = "foo"
  environment_id  = "${var.environment_id}"
  start_on_create = true
}
```

### Expected Behavior
Rancher stack creation

### Actual Behavior
Terraform crashes with
* rancher_stack.foo: unexpected EOF

**Comment by johnrengelman** [comment]
What's the error message that you receive? Is access control enabled on the Rancher server?

**Comment by goffinf** [comment]
Terraform: v 0.8.4
Rancher : v1.3.2

I also see this on both stack, registration_token and registry resources .... not on the first apply (which work successfully) but on any subsequent apply.

I don't have any Access Control enabled in Rancher.

The Rancher API keys are global and definitely valid (I have tried creating new API key .. same error).

```
Error refreshing state: 3 error(s) occurred:

* rancher_registration_token.rancher-env: unexpected EOF
* rancher_registry.rancher-registry: unexpected EOF
* rancher_stack.ecr_credentials_updater: unexpected EOF
```

**Comment by johnrengelman** [comment]
You don't have access control enabled, but you're configuring api keys for terraform? That doesn't make sense.

Curious. I have seen this issue when trying to use Terraform against the hosted demo setup at try.rancher.com, but have not seen it when I run Rancher locally on my machine using docker.

Is there anything else in your set up that's sitting between your machine and Rancher? nginx? Elb? etc?

**Comment by goffinf** [comment]
> That doesn't make sense

Why not, the two things aren't dependant on each other AFAIK.

This is a platform test environment that is not integrated to LDAP or any other authentication method, however, in order to use the Rancher API (and by extension the Rancher Terraform provider) global API keys *are* required. In this case the Rancher API is available via HTTP not HTTPS.

The Rancher servers sit behind an ALB (and their associated target groups) but as I mentioned this does not prevent the Rancher terraform provider working on the first apply. In this case the terraform I am using ...

1. Creates a Rancher environment (using the rancher_environment resource)
2. Create a Rancher registration token (using the rancher_registration_token resource)
3. Create a Rancher registry and registry_credentials (using the rancher_registry and rancher_registration_credential resources and uses the id of the rancher_environment)
4. Spins up some EC2 instance (passing them the rancher registration command from the rancher_registration_token resource output property which is run as part of user_data)
5. The EC2 instances regsister themselves to the Rancher environment created in 1
6. Create a number of stacks (using the rancher_stack resource) which are then started on those rancher nodes.

All of that work fine, so no issue with the Rancher provider or any of the AWS infrastructure or config at that point.

However, running a terraform plan subsequently causes the 'unexpected EOF' errors I mentioned above.

I'm not sure if the Rancher provider is intended to be idempotent or not (the docs don't really say) so I assume that it is ? .. either way I wouldn't expect this type of error, more likely one that states that a duplicate resource exists (which I have seen a few times during testing of the provider and makes perfect sense).

HTHs

**Comment by johnrengelman** [comment]
API keys are not required if access control is not enabled. This is how I set up many demo clusters. 

The provider is idempotent. The error you are seeing is the during a plan, the Rancher API is queried to refresh the local state. This is the same behavior as any other provider. 

For some reason during this query, the data being rwtuened cannot be unmarshalled. 

Would it be possible to try hitting your rancher server directly instead of through the ALB?

**Comment by goffinf** [comment]
I think this might be a remote_state corruption.

I created a new Terraform project and just included resources for rancher_environment, rancher_registry and rancher_registry_credential. All 3 resources created successfully and, as you said, are idempotent. I can run plan or apply as many times as I want and don't see the 'unexpected EOF' error and all terraform resources (from the Rancher provider) correctly report nothing created, changed or destroyed.

I also tried removing the API access and secret key when configuring the rancher.provider and that was fine (as you said it would be). I set up a TCP monitor so I could see the traffic being sent to and returned from the Rancher API calls and can see the headers and payloads (surprised to see the payloads were not simple text ?). Anyway all calls returned 200 so all good. When using the API I see the basic auth header containing the base64 encoded API key:secret.

When I switch back to the other project the error continues to be reported and means that I can't even use Terraform to remove everything and start again.

Anyway I have manually removed all the AWS infra and the Rancher resources and the remote_state in S3. Tomorrow I'll run the TF again and see what happens and report the outcome back here.

Thanks for you help thus far.

Fraser.

**Comment by johnrengelman** [comment]
Ok, I think I found the problem here. All of the rancher resources in their `read` functions, read from the global Rancher api (e.g. `/v1/registrationtokens/<id>` instead of the environment specific one, e.g. `/v1/projects/<environment id>/registrationtokens/<id>`.

This works fine if your API keys have access to the entire global scope but not if it's limited to an environment. In that case querying on the global scope returns a 404 when the resource does actually exist and can be read on the environment specific scope.

I'll have a PR for this shortly (read: the next couple of days), so it'll be fixed in the next TF release.

**Comment by johnrengelman** [comment]
PR here - https://github.com/hashicorp/terraform/pull/11503

**Comment by goffinf** [comment]
I was using global API keys though, which I assumed do have access to everything ?

... and in order to create an environment you have to right (because the environment doesn't have exist yet and therefore can't have any associated API keys) ... or am I missing something ?

BTW does the Rancher provider support the v2 (beta) API in Rancher v1.3.x ?

Also, I have possible enhancement request. As you probably know in Rancher v1.3.x you can create an environment using a specific template. We have a few of our own custom templates which start a number of standard stacks that we want to run in every environment. I know I can simulate this using the rancher_stack resource with the current version, but it would be great if the rancher_environment resource supported passing a template id. What do you think ?

**Comment by johnrengelman** [comment]
>I was using global API keys though, which I assumed do have access to everything ?
>
>... and in order to create an environment you have to right (because the environment doesn't exist yet >and therefore can't have any associated API keys) ... or am I missing something ?

Global keys are tied to a user account, so they are still limited to what that user can do. 
I was testing this against Rancher's hosted cluster at try.rancher.com. My account doesn't have access to everything on that system, but I am allowed to create new environments. But then I would encounter this same error when creating registration tokens in that new environment I created. 
This is most definitely the problem.

> BTW does the Rancher provider support the v2 (beta) API in Rancher v1.3.x ?

We can't use the v2-beta API as we need to support older versions of Rancher. I'm still thinking of a way to make this user selectable.

> As you probably know in Rancher v1.3.x you can create an environment using a specific template.

This was a new feature added in Rancher 1.2 and wasn't available when the original provider was written. I'm pretty sure when I fix https://github.com/hashicorp/terraform/issues/11392 that this will be available.

**Comment by goffinf** [comment]
Thx John,

We really like this provider as it certainly helps us move closer to
fully automated provisioning following best practices around
Infrastructure as Code + 12 factor, both of which are foundations to
our operating model.

The feature enhancements that would benefit us and others are :-

1. The ability to create Infrastructure stacks (currently only user
and system are available). One thing that we need to do is make use of
the Rancher supported EFS catalog item, but because this is within the
Infrastructure templates part of the catalog, Rancher won't create the
mounts properly. So for now we do this with the Rancher API directly,
but it would be nice to include it in the main body of our per
environment Terraform.

2. Support for template id in the rancher_stack resource (including
Infrastructure templates).

3. Support for the v2 API.

Is there somewhere where I could raise these formally ?

Kind Regards

Fraser.
