### ISSUE TITLE
Request to add the feature to pass the variable to the module source parameter

### ISSUE THREAD

**Issue by BalajiVM** [hashicorp/terraform#11103]
In order to create most generic script, it will be helpful to parameterize few attributes.

Here, I am requesting to add the feature to parameterize the source attribute of modules. 
Reasons for parameterization:
 1. It will help us to create the most generic script 
2. I can able to pass the modules as a parameter

Idea behind this, for suppose if i want to use NAT instance or NAT GW, i don't have a facility to choose. for that, I have to write two different scripts, one for NAT instance and another for NAT GW. If we can able to parameterize the source parameter in modules, we can able address lot of issues.

**Comment by BalajiVM** [comment]
@gotascii

**Comment by BalajiVM** [comment]
any updates on the above request ?

**Comment by paddyforan** [comment]
Hi @BalajiVM! I'm, unfortunately, the wrong person to ask--I generally don't work much in the core of Terraform (the config syntax, etc.) and spend more of my time focusing on the providers (specific features for API integrations). We all just help out by categorising issues so the appropriate people can find them. I can't offer any estimates or timelines, but this is tagged correctly, so when the right people have time, they'll get to it. Hope that helps!

**Comment by BalajiVM** [comment]
@paddyforan : Thank you  :+1:

**Comment by teamterraform** [comment]
Hi @BalajiVM! Sorry for the long silence here.

The main way to represent differences like this in Terraform is via [module composition techniques](https://www.terraform.io/docs/modules/composition.html). Taking your specific example, one way to represent that would be to have one module that produces a VPC with no gateways at all, and then two more modules that each handle the creation of an appropriate gateway.

Then, for each configuration you can use the single shared VPC module along with just one of the gateway modules. Each configuration has the specific decision hard-coded, but different configurations can take different decisions.

There are some fuller examples in the module composition guide we linked above. Since module composition is now documented and Terraform 0.12 includes new features that make it easier to use, we're going to close this issue now. Thanks for sharing this use case!
