### ISSUE TITLE
Add customizable 'uniqueness' criteria to resource type -- auto-import resources

### ISSUE THREAD

**Issue by MatthewDaize** [hashicorp/terraform#11151]
Hi,

I've been looking at Terraform as an alternative to several other IaC options we're currently using. Our biggest item stopping us from adopting Terraform full-time is the ability to inject Terraform into an existing environment and not run into issues where it re-provisions resources.

I know that Terraform has the import command and there are other external options (such as Terraforming, etc.). These are great for generating a state based on an existing environment but is also something that is based on the state in that particular point in time. It does not keep the state in sync nor does it provide any flexibility for items that may have changed.

Today I had a thought about a possible solution -- a user-definable **uniqueness** criteria. Not sure what an implementation looks like, if its feasible, or even within the desired scope of Terraforming but I'll try to explain.

This criteria would be a user-defined set of parameters (resource-specific) that Terraform could use to identify whether to attempt to provision new resources or auto-import & update existing ones. This would allow the user to define what they deem as a unique resource and would also improve keeping the tfstate in sync -- or backport changes to keep resources inline with the defined definitoin.

Take AWS S3 bucket for example -- the combination of the name and region makes it unique (and would be defined as such). If it exists in AWS when the Terraform package runs, it could detect this and auto-import it.

Same could go for a VPC -- assuming that we define the uniqueness criteria as [Name tag + VPC CIDR], Terraform could deem this combination as unique and auto-import the resource. In this case however, I understand that you can technically have multiple VPCs with the same Name & CIDR -- however there could be logic to determine if more than one item has been detected and throw an error or something similar.

Once again, sorry if this was already brought up (and subequently closed) or if it is way outside the scope but just something that came to mind and could help make it a better all-in-one IaC tool.

Thanks!

**Comment by mitchellh** [comment]
Hey there! Thanks for the thoughtful issue. This may be a better discussion for the mailing list (and I'm happy to join you there). 

Terraform should already be doing this for you. We uniquely identify resources based on their unique identifier (which differs per resource, some have IDs, some just have unique attributes). After importing a resource, it should "sync" with the state of the world via `terraform refresh`. It should not lose the resource unless the ID changes (meaning you created a new thing outside of Terraform, which it can't currently know about since it ignores things that aren't in its state).

I'm not claiming "operator error" here, but there is likely a mix of both user error and Terraform issues at play here and I'd love to help from the Terraform side if possible. I'd love to talk about this more in the ML though. :)

**Comment by MatthewDaize** [comment]
You're right. I reposted it here: https://groups.google.com/forum/#!topic/terraform-tool/NPHx78a3fH8
