### ISSUE TITLE
Boolean in the schema

### ISSUE THREAD

**Issue by jasminSPC** [hashicorp/terraform#11186]
### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
Possibly all resources which have schema.TypeBool

### Terraform Configuration Files
```hcl
data "profitbricks_image" "test_img" {
  name = "Ubuntu"
  public = false
}
```

Under the data source schema I have following field:
```
"public": {
				Type:     schema.TypeBool,
				Optional: true,
			},
```

if I do this in the code:
```
public, publicOk := d.GetOk("public")
```

`publicOk` is `false` if value in the config is set to false, where it should be set to `true` but the actual value should be set to `false`.

**Comment by mitchellh** [comment]
The current semantics of `GetOk` are as documented: 

```
// GetOk returns the data for the given key and whether or not the key
// has been set to a non-zero value at some point.
```

"whether or not the key has been set to a **non-zero value**"

It is wonky, for sure, but we're afraid to change it at the moment due to the implications it may have across our providers. There is another core bug tracking this at the moment since it is pretty broken. :(

**Comment by mitchellh** [comment]
I'll add more color actually since I'm sure the reaction is "what in the ****?!"

The issue is that at apply time the only data `GetOk` has access to is actually the diff. The diff will contain default values (since it has to show them to the user). But the diff doesn't actually have a field to tell the core WHERE that value came from (configuration, a default, etc.). Because of this, `GetOk` can't actually tell the difference...

The plan in the future is to add a field to the diff so we can know where it came from. :)
