### ISSUE TITLE
Error: <resource> does not have attribute '<attrib>.0' for variable '<resource>.*.<attrib>.0'

### ISSUE THREAD

**Issue by sjwl** [hashicorp/terraform#11205]
### Terraform Version
0.8.4

### Affected Resource(s)
All resources that have these three conditions:
1) A resource has a count > 1
2) The resource has a list attribute
3) A terraform file that needs to interpolate an explicit list index from a list of resources

Using test provider to demonstrate

### Terraform Configuration Files
```resource "test_resource" "test" {
  count    = 2
  required = "${count.index}"

  required_map {
    key1 = "value1"
    key2 = "value2"
  }

  set = ["value1", "value2"]
}

resource "test_resource" "breaks" {
  required = "foo"

  required_map {
    foo = "foo"
  }

  set      = ["${test_resource.test.*.computed_list.0}"] #BREAKS
  optional = "${test_resource.test.0.computed_list.0}"   #WORKS
}

output "works" {
  value = ["${test_resource.test.*.computed_list.0}"] # WORKS
}

provider "test" {}

```

### Debug Output
https://gist.github.com/sjwl/21d4d8e8fdd2114bceda3f2d42a8ae25

### Panic Output
n/a
### Expected Behavior
`terraform plan` completes without error

### Actual Behavior
`terraform plan` errors with 
```* Resource 'test_resource.test' does not have attribute 'computed_list.0' for variable 'test_resource.test.*.computed_list.0'```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by sjwl** [comment]
submitted a pull request to solve this issue: !8888

**Comment by apparentlymart** [comment]
Hi @sjwl! Thanks for this report and the associated PR.

Indexing into lists like that is not something we suggest anymore, since that's a remnant of the rather-limited list support prior to Terraform 0.7. The inconsistent handling of that remnant is rather troubling though and probably worth fixing.

The best-practice way to write this today would be using the indexing operator that was added in 0.7:

```hcl
"${test_resource.test.*.computed_list[0]}"
```

If *that* isn't working in the latest version of Terraform then that'd be a very concerning problem!

**Comment by sjwl** [comment]
thanks @apparentlymart I've closed the issue.
