### ISSUE TITLE
feature request: terraform lint

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#1121]
This has been mentioned before, Github search fails me though.

I think a lot of terraform adopters would love a `terraform lint` command to keep things standardized. 

It doesn't need to be as advanced as `gofmt` that takes actions (though that would be *very* cool(, a mild linter like Puppet's would be great.

**Comment by josephholsten** [comment]
@pmoust this seems relevant to your interests: https://github.com/hashicorp/hcl/pull/24

**Comment by pmoust** [comment]
@josephholsten thanks for this. Read the comments, but did not go through the code. Is the opposite easy to support? A `json2hcl`? So that we can use it as an auto linter?

**Comment by apparentlymart** [comment]
A round-trip from HCL to JSON and back would not quite be equivalent to ``go fmt`` because it would lose non-machine-significant stuff like comments, resource ordering and whitespace intentionally left to communicate organization.

I think to implement something like ``go fmt`` or even just a read-only linter it would be necessary to go down to the level of the lexer in the HCL library and interpret the raw token stream in a different way than the HCL parser normally does, possibly modifying it a little to retain comments and whitespace in the token stream. Thus I think such a thing would end up being largely an HCL change rather than a Terraform change, with just a little bit of UI work in Terraform to make your ``terraform lint`` command work.

**Comment by pmoust** [comment]
Implemented by @fatih at https://github.com/fatih/hclfmt 
(vim plugin provided as as well at: https://github.com/fatih/vim-hclfmt)
works great

**Comment by pmoust** [comment]
Formatting discussion at https://github.com/fatih/hcl/issues/1

**Comment by davewongillies** [comment]
Just for anyone who stumbles across this and isn't familiar with the tool, there's tflint these days which can fill this gap: https://github.com/wata727/tflint
