### ISSUE TITLE
provider/aws: Allow Route53 records creation to be optionally non-blocking

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1124]
If a user is creating DNS records via Route53, it's currently waiting until the record is propagated (which may take quite some time). It's effectively waiting for [`Status=INSYNC`](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Responses.html)

[Similarly to RDS instances](https://github.com/hashicorp/terraform/issues/1097), user may not want to wait for it, if the resource is not intended to be used elsewhere in the graph.

To solve both cases (currently RDS & Route53), would be any value/interest in adding something like `-non-blocking` option to `terraform apply` and `terraform destroy` which would automatically skip `WaitForState()` if the graph allows it?
I just don't know from the top of my head what else could be affected unintentionally by this.

**Comment by scalp42** [comment]
+1 It's really painful

**Comment by phinze** [comment]
I'm going to close this, because I believe taking the opposite position (that each resource must block until it can guarantee that the resource is ready to perform service) is important for the Terraform project to take generally in order to maintain the integrity of the dependency graph.

Feel free to follow up if you'd like to discuss further. :+1:
