### ISSUE TITLE
Missing list of applications for AWS EMR

### ISSUE THREAD

**Issue by MaximF** [hashicorp/terraform#11255]
Hi everyone!
This documentation page seems to be uncompleted: https://www.terraform.io/docs/providers/aws/r/emr_cluster.html#applications. It shows "Hadoop, Hive," with trailing comma, probably it was accidentally removed during one of editions and it doesn't have a full list of available applications for AWS EMR.
Here is a list on AWS website: http://docs.aws.amazon.com//emr/latest/ReleaseGuide/emr-configure-apps.html.

**Comment by teamterraform** [comment]
Hi @MaximF! Sorry for the long silence here.

Because we neglected to label this as being an AWS provider issue, it seems like it got left behind when the AWS provider moved into its own repository. Fortunately, it looks like the documentation issue got fixed along the way anyway, since the website now reflects a longer list:

> Valid values are: `Flink`, `Hadoop`, `Hive`, `Mahout`, `Pig`, `Spark`, and `JupyterHub` (as of EMR 5.14.0).

With that said, we're going to close this out now. If you have any further feedback on the EMR documentation, the best place to record it is now in [the AWS provider's own repository](https://github.com/terraform-providers/terraform-provider-aws). Thanks for reporting this, and sorry again for the delay in responding to it.
