### ISSUE TITLE
Windows console output unreadable

### ISSUE THREAD

**Issue by dlgasser** [hashicorp/terraform#11363]
Terraform v0.8.4

Expected behavior:
Error messages are readable on Windows consoles (PowerShell or Windows Command Shell)

Actual behavior:

Error messages are garbled with stdout output:

C:\platform-engineering\terraform\qless\env\test1>terraform get -no-color
Get: file://C:/platform-engineering/terraform/qless/modules/vpc
Get: file://C:/platform-engineering/terraform/qless/modules/appserver
GEertr:o rf illoea:d/i/nCg: /Tpelrartaffoorrmm:- emnogdiunleee rrionogt/:t emrordaufloer mv/pqcl:e snsa/mmeo diusl enso/ta uar ovraal
id parameter

**Comment by yellowmew** [comment]
workaround for this issue is to redirect console output to anything
like terraform get > c:\temp\temp.txt

**Comment by samirageb** [comment]
I can confirm experiencing this exact behavior. Also, this behavior appears to happens when a .terraform dir already exists.  In my tests, deleting the .terraform dir, would eliminate the garble from the stdout output for 1 run until the directory was created again. Subsequent runs would show the garble returning.

**Comment by samirageb** [comment]
Confirm that this is still happening in v.8.7

**Comment by glennmate** [comment]
```
azEurrreorrm _avpiprltyuianlg_ mpalcahni:n
e
.1e le-rcrhoerf( s()l ooccaclu-rerxeedc:)
:
T*h ea zsuyrnetramx_ voifr ttuhael _cmoamcmhainnde .iesl -icnhceofr:r e1c te.r
ror(s) occurred:

* Error running command '    mkdir -p /c/tmp/vendored_cookbooks
    cd /c/repos/cookbooks/chef
    berks vendor /c/tmp/vendored_cookbooks
    cd /c/repos/cookbooks/sql
    berks vendor /c/tmp/vendored_cookbooks
': exit status 1. Output: The syntax of the command is incorrect.


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
This is a pleasure to deal with.

**Comment by apparentlymart** [comment]
I successfully reproduced this on Windows 10, finally.

![terraform-windows-garble](https://cloud.githubusercontent.com/assets/20180/25645531/d0f2fa2a-2f63-11e7-8bdb-5ad10ddd7224.png)

It seems like it's specifically _errors_ that get garbled, as opposed to other non-error output. That suggests it's either the red coloring of the text that's creating trouble or the fact that errors get written to `stderr` instead of `stdout`. My gut tells me the latter is the problem here since we seem to have no problem producing output of other colors, such as in the plan output shown here.

**Comment by apparentlymart** [comment]
I have narrowed this down to our use of [`colorable`](https://github.com/mattn/go-colorable) to fake out support for VT100 color codes on Windows.

On Windows we wrap a writer from that library around each of stderr and stdout and then write to those handles through those writers. Internally `colorable` deals with the data one rune at a time so that it can pick out the `ESC[` introduction sequence and emit the relevant Windows console API calls to implement the escape sequence.

The problem is that even when `stderr` and `stdout` are actually the same underlying handle (the console) we still create two separate colorable wrappers, and concurrently write different buffers to each of them, causing their output to be interleaved.

This sort of interleaving is actually theoretically possible on other platforms too, but because we tend to write to `stdout` and `stderr` in whole lines it's normally only the _lines_ that can get interleaved. Colorable makes this a lot more visible by doing character-by-character writes to the console, allowing the interleaving to happen at the individual character level.

**Comment by apparentlymart** [comment]
Thanks everyone for the patience here! This should be fixed in the next release.
