### ISSUE TITLE
Are there plans to support Parameter Store in AWS?

### ISSUE THREAD

**Issue by n8gard** [hashicorp/terraform#11433]
Some searching did not turn anything up for me. This would be a very useful integration. I'm building a weird work-around now. Would love to be able to use this service via Terraform.

https://aws.amazon.com/ec2/systems-manager/parameter-store/

**Comment by anshulshrivastava** [comment]
+1

**Comment by nathaniela** [comment]
+1

**Comment by oflo-suplari** [comment]
+1

**Comment by UncleBarney** [comment]
+1

**Comment by CraigTRichards** [comment]
+1

**Comment by apparentlymart** [comment]
Hi @n8gard, et al,

Thanks for opening (or voting on) this feature request!

When it comes to prioritizing implementation of entirely new AWS resources it's helpful to have some sense of what people are doing with them so we can figure out what would be the most valuable resources to implement first.

We (the Terraform team) don't have any immediate plans to implement support for this service ourselves, so this issue is likely to remain stale. We're trying to prune the stale enhancement requests (that aren't going to be addressed anytime soon) by closing them.

With all of that said, if anyone has the time and the motivation, we'd gladly review pull requests for Parameter Store resources!

**Comment by sshvetsov** [comment]
+1

**Comment by pedrofranceschi** [comment]
+1

**Comment by apparentlymart** [comment]
This issue seems to be attracting +1 comments, which creates noise for the many people following this issue, so I'm going to close comments here until there's something more to share.

There's also PR #14043 in progress that makes a start on this. Thanks for that!
