### ISSUE TITLE
Wait for ALB Target Group health threshold

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#11451]
There's a common pattern with autoscaling groups in Terraform of having the `aws_autoscaling_group` resource wait until a certain number of instances are healthy in an associated ELB before considering the autoscaling group as created.

This pattern doesn't work for the new *Application Load Balancer* because there's an extra indirection in the form of a *target group*.

A naive attempt to use the usual pattern with ALB might look like this:

```hcl
resource "aws_alb" "example" {
  # ...
}

resource "aws_alb_target_group" "example" {
  name = "example-${var.version_id}"
  # ...

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "example" {
  name = "example-${var.version_id}"
  target_group_arns = ["${aws_alb_target_group.example.arn}"]
  min_elb_capacity = 2
  # ...

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_alb_listener" "example" {
  load_balancer_arn = "${aws_alb.example.arn}"
  # ...

  default_action {
    target_group_arn = "${aws_alb_target_group.example.arn}"
    type = "forward"
  }

  # Don't update target_group_arn to new target group until
  # the autoscaling group has healthy instances.
  depends_on = ["aws_autoscaling_group.example"]
}
```

The problem here is the non-obvious dependency cycle that causes a deadlock: the `min_elb_capacity` attribute on `aws_autoscaling_group` causes that resource to block completion until it sees instances in the ELB, but the instances can't get into the ELB until the `aws_alb_listener` resource is updated to include the new target group.

---

[The `DescribeTargetHealth` operation](http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeTargetHealth.html) allows us to ask for the healthcheck status of the members of a target group without first attaching the target group to an ALB.

Terraform could detect that `target_group_arns` is set on the `aws_autoscaling_group` resource and prefer to use the ALB `DescribeTargetHealth` operation instead of the ELB status operation, which would then allow the subsequent `aws_alb_listener` update to complete only once the target group has become healthy enough to satisfy the constraint.

It seems that we could do this without changing the configuration schema at all, because `wait_for_elb_capacity` can just be treated as the minimum value of (number of healthy classic ELB instances + number of distinct healthy instances across all ALB target groups), without the user needing to think about whether it's a classic ELB or an ALB that's providing the capacity.

**Comment by owenmorgan** [comment]
Thanks @apparentlymart. how this looks in the console is that you will have a new target group created along side a new asg, the target ec2s are populated onto the target group and stay as status of "unused". which is the deadlock.  

![image](https://cloud.githubusercontent.com/assets/10656664/22365703/e8952970-e470-11e6-90b2-7cbb28f7b1ba.png)

It may be an issue even using the DescribeTargetHealth operation that the EC2s may report as "unused" rather than healthy. i hope not.

As a back ground to this, creating a new target group is required to not have a new asg attached to the same target group during the scale up of the new asg.. and to achieve a precise blue/green update without a period of both asgs being in service.
