### ISSUE TITLE
user_data in aws_launch_configuration can't be gzip/base64

### ISSUE THREAD

**Issue by dodwmd** [hashicorp/terraform#11488]
Hi there,

Not really a bug. Most likely could be dealt with a documentation update to state that user_data in a aws_launch_configuration shouldn't be encoded when using template_cloudinit_config and doing multi-part configs.

**Comment by apparentlymart** [comment]
Hi @dodwmd! Thanks for this documentation suggestion.

Is there some documentation from AWS that reflects this limitation?

It was my impression that `user_data` is just an arbitrary string that can be whatever format you want it to be, since it's up to code running in the EC2 instance to decode it and handle it. Thus if the launch configuration is booting an AMI that has cloudinit installed then `template_cloudinit_config` ought to be fine, but it wouldn't work if the AMI does something different to handle `user_data`.

**Comment by dodwmd** [comment]
To be honest I did very little investigation. I tried multi-part configs with the encoding turned on.. it wouldn't load.. i cut and pasted the encoded output into a instance user_data and manually spun it up, it worked.. i disabled the encoding and remade the lc and everything started working.. i've other asg's that use cloudinit without doing multiple parts and they work fine encoded or not.. it just seems to be when your doing multiple template parts encoding them b64/gzip and trying to use it on a asg that doesn't.. 

Also of note the decoded b64 created with template_cloudinit_config has lots of ^M's at the end of each line that it adds in (headers) around the template parts.. don't think it's causing any issues.. just being ocd..
