### ISSUE TITLE
provider/aws taking "ownership" of existing resources?

### ISSUE THREAD

**Issue by gliptak** [hashicorp/terraform#11506]
I might have missed this in the documentation, but I would like to take "ownership" of an existing resource and set its attributes.

As an example, creating a ```lambda``` function also creates a ```default``` ```log group``` with unlimited retention.

I would like to be able to add a ```resource``` entry into my configuration, and set ```retention_in_days```. When using:

```
$ terraform -v
Terraform v0.8.5
```
this throws

```
aws_cloudwatch_log_group.lambda_log_group: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
```

Thanks

**Comment by mitchellh** [comment]
Please ask usage questions on the mailing list or chat. Issues are left for bugs/feature requests. Sorry! This isn't just for our sanity as maintainers, but because far more people who are experienced in the usage and edges of resources don't read issues at all. 

I'm not 100% familiar with the resources you mentioned, but AWS in particular often creates "default" resources if an explicit one isn't specified. One solution may be to from the beginning specify explicit values (destroy all existing resources). If destruction isn't an option, you may want to look into `import` though I'm unsure if that is supported for this resource. Finally, AWS often has special default things that can't be managed via the API (default volume on instances for example), which is annoying. I don't know if that's the case here, but someone more familiar with these resources on AWS should be able to help you.

**Comment by gliptak** [comment]
I didn't get any additional pointers in the chat.

But as it seems to be a more generic operational issue, I opened a feature request as https://github.com/hashicorp/terraform/issues/11760
