### ISSUE TITLE
terraform plan to calculate the deployment cost

### ISSUE THREAD

**Issue by nicolas-g** [hashicorp/terraform#11531]
Would be cool when by running `terraform plan` to also show an estimated cost based on the current AWS price for the service/region.

**Comment by ravibhure** [comment]
+1 This will be nice feature to have with `terraform plan`

**Comment by catsby** [comment]
Hello – Thank you for opening the issue here. Right now our stance on this idea is that we'd like to see 3rd party support for this, and not include it as a feature of Terraform itself. If we can improve Terraform's output or make it more machine readable to enable this, we'd be open for suggestions. Thanks!

**Comment by Bjorn248** [comment]
Hey there, I tried to write a tool that does this, but it's still in its infancy. https://github.com/Bjorn248/terraform_cashier

**Comment by sieben** [comment]
thanks @Bjorn248 for this article: https://www.mobiquityinc.com/thought-leadership/estimating-aws-infrastructure-cost-from-terraform-templates :-) I'm working for a different cloud provider with a much simpler pricing model. I would really like to understand how to make billing estimation easier to get as it is a very important part of a deployment.

**Comment by Bjorn248** [comment]
@sieben it's pretty simple at the highest level. You need to know which and how many resources you are planning on creating, which is available in the terraform plan. Then you need a place to query the pricing data for each resource type, which is why I wrote a pricing API. Your cloud provider might not have an API available, so you might have to write your own, unfortunately. Am happy to take this conversation to email if you'd like.

**Comment by FWirtz** [comment]
I know this is not exactly what's wanted here, but it probably is still helpful:
https://www.hashicorp.com/blog/announcing-cost-estimation-for-terraform-cloud-and-enterprise
