### ISSUE TITLE
create_before_destroy documentation is outdated

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#11597]
![image](https://cloud.githubusercontent.com/assets/23215674/22503504/551ed2b2-e872-11e6-9b72-db389427bdf0.png)

on https://www.terraform.io/docs/configuration/resources.html#create_before_destroy

OK, so it will result in a dependency graph cycle. Is that something which happens only during the planning phase or will it potentially result in actual broken infrastructure? 

If it is the former, add 
`of which you will be notified with an error message during terraform plan`.

Additionally, the statement as it stands is also incorrect. I have a resource which depends on a `aws_iam_role_policy`-resource (which doesn't have `create_before_destroy`), and no such cycle is being created.

**Comment by marco-m** [comment]
@stack72 any news ?

**Comment by apparentlymart** [comment]
This warning is actually outdated since Terraform has been doing automatic graph adjustments to propagate `create_before_destroy` for a number of versions now.

Our current project is to integrate an improved configuration language parser and interpreter, and after that all of the configuration-related documentation will get an overhaul where we'll make sure everything is up-to-date and accurate, including this.

**Comment by marco-m** [comment]
Thanks @apparentlymart, it is always a pleasure to get an answer from you :-)

**Comment by apparentlymart** [comment]
Hi all!

The documentation for `resource` blocks has had an overhaul in preparation for the v0.12 release. You can see [the current draft in the `master` branch](https://github.com/hashicorp/terraform/blob/009534d1016cd3b1d0d911f151520b04f8db453a/website/docs/configuration/resources.html.md#lifecycle-customizations), which will become the new resource configuration documentation page once v0.12.0 final is released.

As I mentioned in my previous comment, the warning shown in this issue was no longer relevant since Terraform takes care of the necessary graph adjustment automatically. Therefore the warning is no longer present on the new page, and instead the documentation warns that for many resource types there are unique name constraints that must be worked around in a resource-type-specific way.

Thanks for reporting this, and sorry it took so long to get it updated!
