### ISSUE TITLE
Security groups not identifying state change

### ISSUE THREAD

**Issue by N4R3N** [hashicorp/terraform#11606]
When ingress and egress rules as part of the aws_security_group then, any changes made in AWS console are picked up by terraform as expected.
```
resource "aws_security_group" "sftp_sg" {
  vpc_id = "${module.vpc.id}"
  name = "SFTPSG"

  ingress {
    from_port = 20
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["${var.admin_cidr}", "${var.vpc_cidr}"]
  }
}
```
If the same security group is setup as a blank group and then the rules reference the security groups then, Terraform does not pick the changes made on the AWS console.

``` 
resource "aws_security_group" "sftp_sg" {
  vpc_id = "${module.vpc.id}"
  name = "SFTPSG"
}

resource "aws_security_group_rule" "sftp_inbound" {
  from_port = 20
  to_port = 22
  protocol = "tcp"
  security_group_id = "${aws_security_group.sftp_sg.id}"
  type = "ingress"
  cidr_blocks = ["${var.admin_cidr}", "${var.vpc_cidr}"]
}
```
### Terraform Version
0.8.5

### Affected Resource(s)
- aws_security_group

### Expected Behavior
Irrespective of how you create the security groups any difference in state should be picked up.

### Actual Behavior
Terraform does not show that the security group has been externally modified (i.e. someone has modified he rules on the AWS console) if aws_security_group_rule is defined separately and then attached to the security group

### Steps to Reproduce
Create a security group and rules separately as below
``` 
resource "aws_security_group" "sftp_sg" {
  vpc_id = "${module.vpc.id}"
  name = "SFTPSG"
}

resource "aws_security_group_rule" "sftp_inbound" {
  from_port = 20
  to_port = 22
  protocol = "tcp"
  security_group_id = "${aws_security_group.sftp_sg.id}"
  type = "ingress"
  cidr_blocks = ["${var.admin_cidr}", "${var.vpc_cidr}"]
}
```
Apply the changes.
Once the group is created, modify the rules on AWS console for this security group.
Run terraform plan

*Terraform does not state that the script and the actual resource differ.*

Now change the security group to have the rules within the group.
```
resource "aws_security_group" "sftp_sg" {
  vpc_id = "${module.vpc.id}"
  name = "SFTPSG"

  ingress {
    from_port = 20
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["${var.admin_cidr}", "${var.vpc_cidr}"]
  }
}
```
Run 
terraform plan
terraform apply

Now change the rules on AWS console
run terraform plan

Terraform picks up the changes.

**Comment by grubernaut** [comment]
Hi @N4R3N, thanks for the issue!

The `aws_security_group_rule` resource does not establish a strict contract on the rules associated with the specified `aws_security_group` resource. This is by design, as there are several users who either are currently, or are planning on running Terraform in a distributed workflow. This would potentially mean having multiple statefiles that may contain `aws_security_group_rule` resources for the same `aws_security_group` resource. 

We've discussed this internally at length, and have came to the conclusion that it would be nice to allow users to specify a `manage_all_rules` attribute for an `aws_security_group` resource, which would allow Terraform to register a diff on manual rule changes, like requested. However, there are still a couple of core enhancements that would need to be in place before we can fully commit to adding that feature. 

Until that enhancement lands, it's best to think of the `aws_security_group` resource, with inline `egress`/`ingress` rules as a strict contract for the entire `aws_security_group`, while the `aws_security_group_rule` resource only has a contract for managing that exact security group rule inside of the security group, not the entirety of the security group.

Hopefully that answers everything, but going to close this for now. Happy to discuss this further if wanted though. Thanks!
