### ISSUE TITLE
Support for conditional arguments to resources

### ISSUE THREAD

**Issue by eyalzek** [hashicorp/terraform#11629]
The conditional logic introduced starting 0.8 is great and solves a lot of past issues we had with creating resources according to environment, but it is still lacking. In my current task, trying to create an `aws_elasticache_replication_group` with some conditional arguments that depend on the environment being a development environment or not, I'm having a couple of issues implementing it. e.g:

- `availability_zones` depends on the number of cache clusters I pass, which is 1 in case of a dev environment or 3 in other cases. the problem is that it takes a list which is not supported in conditionals.

- `snapshot_window` is not supported in `t2.X` instances (which I'll use for dev environments), but I didn't find any way of disabling it in those cases. Assigning `0/false/""` all do not work...

the only solutions I can think about is either duplicate the resources altogether under a different name (which is obviously not ideal), or comment out arguments manually when creating those resources (which is slightly better, but still beats the purpose of having infrastructure as code).

Those can be solved if the option to conditionally pass arguments to resources would exist. I wouldn't require any fancy interpolation or anything, just passing a specific value if `true`, or omit the argument altogether if `false`.

Is this feature on the road map somewhere?

**Comment by mitchellh** [comment]
Both of these are currently issues somewhere. I don't recall their numbers but I can explain both issues in abstract:

1. Conditionals should support lists, this is part of the new type system that @apparentlymart is working on. I don't think this specifically (list support in conditionals) will make it into 0.9 but the groundwork is being done and parts of it will ship in 0.9.

2. There is an "unsetting a value" enhancement request somewhere. I think we'll probably introduce a HIL function that returns a special value to denote unsetting. 

Going to close since I'm confident these exist elsewhere! Thanks!

**Comment by jrstarke** [comment]
It would be helpful to link the issues, so that we could weigh in on them. Having spent hours searching for those issues, I keep repeatedly ending up on this issue.

**Comment by apparentlymart** [comment]
I think the issues that Mitchell was referring to here are #12453 and #14037.
