### ISSUE TITLE
Add the ability to retrieve unsorted list of map keys 

### ISSUE THREAD

**Issue by talf** [hashicorp/terraform#11627]
Hello, 

When using the keys() function, the list is always sorted. This causes resources recreation when not nessecarily needed. 

This is a terraform core behavior. 

for example:
```hcl
module "gcp-hub-zones"  {
  source        = "../modules/dns_zone"
  num_of_zones  = "${length(var.dns_zones)}"
  zones         = "${var.dns_zones}"
}


variable "dns_zones" {
        type = "map"
        default = {
          in-addr-arpa-120-10 = [ "120.10.in-addr.arpa.", "10.120/16 network reverse zone" ]
          in-addr-arpa-121-10 = [ "121.10.in-addr.arpa.", "10.121/16 network reverse zone" ]
          in-addr-arpa-122-10 = [ "122.10.in-addr.arpa.", "10.122/16 network reverse zone" ]
          in-addr-arpa-123-10 = [ "123.10.in-addr.arpa.", "10.123/16 network reverse zone" ]
        }
}


## "../modules/dns_zone/main.tf"

variable zones {
  type = "map"
}

variable num_of_zones {
  default = "1"
}

resource "google_dns_managed_zone" "dns" {
  count       = "${var.num_of_zones}"
  name        = "${element(keys(var.zones), count.index)}"
  dns_name    = "${element(var.zones[element(keys(var.zones), count.index)], 0)}"
  description = "${element(var.zones[element(keys(var.zones), count.index)], 1)}"
}
```

This will create 3 DNS zones accordingly. 
after applying, when passing the following variable

```hcl
variable "dns_zones" {
        type = "map"
        default = {
          in-addr-arpa-120-10 = [ "120.10.in-addr.arpa.", "10.120/16 network reverse zone" ]
          in-addr-arpa-121-10 = [ "121.10.in-addr.arpa.", "10.121/16 network reverse zone" ]
          in-addr-arpa-122-10 = [ "122.10.in-addr.arpa.", "10.122/16 network reverse zone" ]
          in-addr-arpa-123-10 = [ "123.10.in-addr.arpa.", "10.123/16 network reverse zone" ]
          gcp-example-com      = [ "gcp.example.com.", "Example GCP" ]
        }
}
```

will force a recreation of all zones since the element "position" is different. 
We need to have a consistent order of map keys, so we can just add a key/value pair without breaking the existing state. 

```hcl
$ terraform -v
Terraform v0.8.5
```

Expected behaviour: 
Only "gcp-example-com" dns zone should be created.

Actual behaviour: 
All dns zones should be recreated since "gcp-example-com" is now the first element in a sorted list.

**Comment by talf** [comment]
EDIT: Moved the "gcp-example-com" to the end of the the map variable for better understanding.

**Comment by jbardin** [comment]
Hi @talf,

Thanks for the extensive example and use cases. The `keys` interpolation function specifically returns the sorted list of keys so that they can be indexed deterministically, like in your example. 

I don't think an unsorted list is really what you're looking for, because maps are fundamentally an unordered data structure. If `keys` didn't sort the list, it would return a possibly different order every time. If you want an ordered data structure, you need to use a list.

**Comment by jnj16180340** [comment]
@jbardin The sorting in `keys` also means one can't reversibly transform maps to lists, for example
```
zipmap(keys(map("k2","v1","k1","v2","k3","v3")),values(map("k1","v1","k2","v2","k3","v3")))
{
  k1 = v1  k2 = v2  k3 = v3}
```
doesn't return the original map.

This would be helpful when a resource type doesn't follow convention re: types, such as `aws_autoscaling_group` which expects `tags` as a list, while most other AWS resources expect `tags` as a map.

**Comment by jbardin** [comment]
Hi @jnj16180340,

I'm not sure what you mean, since the `values` interpolation function returns the values in the same order as the keys, so that it specifically _is_ reversible. You're zipping 2 different maps together, which is why the result doesn't make sense. It's no different than i.e.:

```
> zipmap(keys(map("X","2","Y","3","Z","1")),values(map("A","11","B","2","C","4")))
{
  X = 11  Y = 2  Z = 4}
```

If you zip the same keys/value pairs in both cases, it returns the same result

```
> zipmap(keys(map("k2","v1","k1","v2","k3","v3")),values(map("k2","v1","k1","v2","k3","v3")))
{
  k1 = v2  k2 = v1  k3 = v3}
```
