### ISSUE TITLE
Terraform plan to have ability generate resultant target state for the resource

### ISSUE THREAD

**Issue by gauravbhandare** [hashicorp/terraform#11667]
*** Enhancement Request ***
We are using terraform for configuring network resources. Over time with multiple rollouts, the plan output isn't sufficient to decide if the change taking place is good. Having an ability to generate the resultant target state of the resource incase the plan is applied will provide complete details of how the target network configuration will look. This will enable the network configuration approvers to decide if the resultant resource configuration complies with the overall rules.

**Comment by mitchellh** [comment]
Thanks for submitting this. 

This currently isn't easily possible since there would be a lot of edge cases to answer MAINLY around computed fields and we don't have a great way to reconcile those issues into a clean merge. With a complete/non-computed diff we of course do this as part of `apply` but for your issue I understand that is too late. :) 

I don't see ourselves getting to this anytime soon, but I'm not against the idea either. If someone wants to come along and take a stab at this I'd be happy to talk through it and see if we can get anywhere. 

Because we don't want issues we don't plan on resolving to remain open (historically they just remain open for years), I'm going to close this, but all the above stands.

**Comment by apparentlymart** [comment]
This reminds me a bit of the "conservative" flag I was considering in [a comment on the Partial Apply issue](https://github.com/hashicorp/terraform/issues/4149#issuecomment-165506985): instead of leaving computed values in the plan and resolving them during apply, instead create a partial plan that only makes as much progress as can be reported explicitly in the plan and then gradually converge on the intended result over multiple runs.
