### ISSUE TITLE
Handling empty set of outputs in automatable way

### ISSUE THREAD

**Issue by ljfranklin** [hashicorp/terraform#11696]
## Use Case

I'm working on an automated wrapper around Terraform for use in our CI system. This wrapper runs an apply and writes the outputs to a JSON file. However, if no Terraform outputs are defined the CLI throws this error:

```bash
$ terraform output -json
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.
```

It would be helpful if there was an automatable way to check that no outputs were defined aside from regexing on the error output (brittle). I could also read the state file directly, but that feels like a leaky abstraction. Thanks!

## Terraform Version

Terraform v0.8.5

**Comment by apparentlymart** [comment]
Hi @ljfranklin! Thanks for opening this issue.

Seems reasonable to me that when `-json` is provided the command should exit successfully with an empty value in this case, rather than this error.

This error is a guide to help new users understand the concept of an output, but I think supplying `-json` is a reasonable indication that the user is beyond that initial stage and so the specific error message is not so important and the JSON-friendliness of the output is more important.

With that said, in the current state this command exits with status 1 in this scenario, so it could potentially be detected that way: if exit status is zero, parse stdout as JSON. if exit status is nonzero, capture stderr and print it verbatim to your stderr before exiting.

We might find that we are wedded to the current behavior, if others are already doing what I describe above to detect the error via the exit status. :thinking:

**Comment by ljfranklin** [comment]
@apparentlymart thanks for the quick response! Having an empty value when `-json` is provided sounds perfect.

I was hesitant to use the exit code as that might accidentally mask other classes of errors, e.g. "The module root could not be found. There is nothing to output." In my case, I'm always running `output` after `apply`, so an empty set of outputs is acceptable but any other error I would re-raise to the user.

**Comment by apparentlymart** [comment]
@ljfranklin That's a good point... "everything worked okay but there are no outputs in this config" is a different sort of error than "there's no state at all" or "there was an error retrieving the state". For a generic wrapper script (which I expect is what you're doing here) it'd be convenient to be able to distinguish those cases.

Even though this is a small compatibility break it seems like something we could cover pretty easily in major version upgrade docs, particularly since there are some much-more-substantial changes to the CLI workflow coming in 0.9 anyway. A big question is whether this could get done before 0.9 is cut... if someone wanted to take a stab at a PR on this, I think it'd just be some rearranging to make it so [the emptiness check](https://github.com/hashicorp/terraform/blob/0d39123cb0cf052379204bf2a33782c83451aef2/command/output.go#L78) doesn't happen when JSON mode is active, and some tests to validate that behavior.

**Comment by ljfranklin** [comment]
@apparentlymart Took a swing at a PR to address this, let me know if anything looks amiss: https://github.com/hashicorp/terraform/pull/11721
