### ISSUE TITLE
providers/vsphere: vsphere_virtual_disk doesn't preserve its size

### ISSUE THREAD

**Issue by akshaykarle** [hashicorp/terraform#11722]
It seems that terraform is unable to preserve the state of the size of the virtual disk. 

### Terraform Version
Terraform v0.8.5

### Vsphere Version
6.0.0 Build 3634794

### Affected Resource(s)
Please list the resources as a list, for example:
- vsphere_virtual_disk

### Terraform Configuration Files
https://gist.github.com/akshaykarle/fcf9c4f3b1e7019138aadc389d414fe8

### Terraform Output
https://gist.github.com/akshaykarle/407b163ded7943536a1fb66084d109cf

### Expected Behavior
Should've preserved the size of the disk after create/updating the disk resource

### Actual Behavior
Doesn't preserve the size, hence attempting to recreate everytime you run terraform apply.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jeroenjacobs1205** [comment]
Suffering from the same issue here. Any estimates on a fix?

**Comment by tchemineau** [comment]
Got the same issue here.

I found the following steps useful:

```
# Manually do a refresh step
$ terraform refresh

# Manually update disk size into the `terraform.tfstate`

# Skip the refresh step when doing the plan step
$ terraform plan --refresh=false

# Skip the refresh step when doing the apply step
$ terraform apply --refresh=false
```

Not ideal, but it works fine for my use-case.

**Comment by peay** [comment]
Seems like a bug with thin provisioning (`type=thin`).

From a quick glance, [refresh uses the file size](
https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/builtin/providers/vsphere/resource_vsphere_virtual_disk.go ) of the `.vmdk` file in the datastore. With thin provisioning, this may be much less than the virtual disk size.

[The file size is then converted to GBs and rounded down](https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/builtin/providers/vsphere/resource_vsphere_virtual_disk.go#L196). If your `.vmdk` is less than 1GB in the datastore, `refresh` will see a size of 0. If your `.vmdk` is in between 1GB and 2GB, I think `refresh` should update the state with a size of 1 instead.

I am not too familiar with `govmomi`, but I assume a different API should be used to get the virtual disk size instead of the actual file size in datastore.
