### ISSUE TITLE
Template_file -> data.template_file has different hash

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#11727]
### Terraform Version
0.8.5

### Affected Resource(s)
- template_file
- data.template_file

### Expected Behavior
Swapping `template_file` for `data.template_file` should result in no work done.

### Actual Behavior
Swapping `template_file` for `data.template_file` creates a plan which will re-launch an EC2 instance when using a template for user_data. The data source has a different hash than the resource, even though the template contents are identical.

### Important Factoids
Migrating from 0.7 TF.

**Comment by Ninir** [comment]
Hey @pikeas,

Could you share your template files, and also the data source calling them?

Thanks

**Comment by apparentlymart** [comment]
Hi @pikeas. Thanks for reporting this.

Agreed that it's annoying that the transition between these two isn't clean, but unfortunately I suspect if indeed the hash changed between the two then it would be too late to fix this now because it would cause a change for anyone who is *already* using `data.template_file`.

With that said, the hash wasn't intentionally changed so I wonder if something else is going on here. Could it be that your `data.template_file` resource is depending on another non-data resource, which would then cause the data lookup to be deferred until `apply` time? That would cause the hash to *appear* to change because it would be computed during plan, but possible that the hash would end up the same in the end anyway.

You can see if this is the case by whether the `data.template_file` resource shows up in the plan. Most of the time data sources should *not* appear in the plan because they are resolved during the initial refresh.

If this seems to be the problem then you could try running with `-target=data.template_file.your_template_resource` to force Terraform to get the template into a stable state first, and then afterwards run Terraform normally where it should be able to see that the hash hasn't changed after all.

**Comment by pikeas** [comment]
Before:

    resource "aws_instance" "foo" {
        count = "${var.foo_count}"
        <other settings>
        user_data = "${template_file.userdata_single_ebs_volume.rendered}"
    }

    resource "template_file" "userdata" {
        template = "${file("${path.module}/userdata")}"
        vars {
            mountdevice = "${replace("${var.foo_name}", "/sd", "/xvd")}"
            mountpoint = "${var.foo_mount_point}"
        }
    }

After:

    resource "aws_instance" "foo" {
        count = "${var.foo_count}"
        <other settings>
        user_data = "${data.template_file.userdata_single_ebs_volume.rendered}"
    }

    data "template_file" "userdata" {
        template = "${file("${path.module}/userdata")}"
        vars {
            mountdevice = "${replace("${var.foo_name}", "/sd", "/xvd")}"
            mountpoint = "${var.foo_mount_point}"
        }
    }

The template file:

    #cloud-config

    bootcmd:
      - /usr/bin/test -z "$(lsblk -no FSTYPE ${mountdevice})" && (mke2fs -t ext4 -L data_volume -M ${mountpoint} -T ext4 ${mountdevice} && mkdir -p ${mountpoint})

    mounts:
      - [ ${mountdevice}, ${mountpoint}, ext4, "defaults,rw,noatime,nodiratime,nobootwait", "0", "1" ]

Running a plan with `-target=module.foomod` shows a warning for the template_file resource but no changes.

After swapping to the data source:

    -/+ module.foomod.aws_instance.foo
        ...
        user_data: "fe65d1faf29cbc09606ca663e5c951d6ca97c214" => "91b72340096afa0377354a74a7221f2c1c9610ff" (forces new resource)

    <= module.foomod.data.template_file.userdata
        rendered:         "<computed>"
        template:         "#cloud-config\n\nbootcmd:\n  - /usr/bin/test -z \"$(lsblk -no FSTYPE ${mountdevice})\" && (mke2fs -t ext4 -L data_volume -M ${mountpoint} -T ext4 ${mountdevice} && mkdir -p ${mountpoint})\n\nmounts:\n  - [ ${mountdevice}, ${mountpoint}, ext4, \"defaults,rw,noatime,nodiratime,nobootwait\", \"0\", \"1\" ]\n"
        vars.%:           "2"
        vars.mountdevice: "/dev/xvdd"
        vars.mountpoint:  "(redacted)"

    - module.nexia_home.template_file.userdata

**Comment by apparentlymart** [comment]
It does seem like something strange is going on here. the plan suggests that the `data.template_file.userdata` resource doesn't depend on anything computed, since we can see in the plan output all of the finalized values, so the template should be getting rendered during the refresh phase and never appearing in the plan.

So this smells like a core bug to me. Something is causing that `template_file` data resource to think that it is depending on computed data, but the plan output isn't showing anything as computed.

**Comment by pikeas** [comment]
A-ha! Behavior above only happens with `-refresh=false`. Allowing a state refresh produces the correct plan, which only removes the `module.foomod.template_file.userdata` resource.

**Comment by apparentlymart** [comment]
Ah, that makes sense @pikeas, since by disabling refresh you effectively prevented the data source from running before plan, forcing it to be deferred until apply.

It seems like things are working as expected here then, though admittedly this is a little surprising if you don't know that data sources are dealt with during refresh. Perhaps we should add a note about this to the docs for the `-refresh`option, but for now I'm going to close this out.
