### ISSUE TITLE
AWS SNS delivery status support

### ISSUE THREAD

**Issue by pjungermann** [hashicorp/terraform#11739]
Hej Terraform team,

It would be great to support the SNS delivery status logging. This was already asked for at issue #5386, but got closed due to inactivity.

You can find an example for how to enable it at the console and via the Java API at
- https://aws.amazon.com/blogs/mobile/using-the-delivery-status-feature-of-amazon-sns/
- http://docs.aws.amazon.com/sns/latest/dg/msg-status-topics.html#msg-status-sdk

I think it would fit either as a new attribute to the "aws_sns_topic" resource or maybe even better as  a new:

```
resource "aws_sns_topic_delivery_status" "sqs_delivery_status" {
  topic_arn           = "${aws_sns_topic.my_sns_topic.arn}"
  endpoint            = "sqs" # application, http, lambda, sqs, * / all (default)
  success_sample_rate = 50 # default: 100
  success_role_arn    = "${aws_iam_role.cloud_watch_logging.arn}"
  failure_role_arn    = "${aws_iam_role.cloud_watch_logging.arn}"
}
```

**Comment by gazoakley** [comment]
The list of topic attributes is here: http://docs.aws.amazon.com/sns/latest/dg/msg-status-topics.html#w1ab1c25c11b7

I'd add this as attributes to the existing `aws_sns_topic` resource, since you can only specify one success ARN/success sample rate/failure ARN for each type of endpoint. The mappings would be pretty similar to what the console lets you setup too:

![Imgur](http://i.imgur.com/ZL176TY.png)

Maybe have new attributes on the SNS topic named:

- `application_success_feedback_role_arn`
- `application_success_feedback_sample_rate`
- `application_failure_feedback_role_arn`
- `http_success_feedback_role_arn`
- `http_success_feedback_sample_rate`
- `http_failure_feedback_role_arn`
- `lambda_success_feedback_role_arn`
- `lambda_success_feedback_sample_rate`
- `lambda_failure_feedback_role_arn`
- `sqs_success_feedback_role_arn`
- `sqs_success_feedback_sample_rate`
- `sqs_failure_feedback_role_arn`
