### ISSUE TITLE
Instart Logic Provider

### ISSUE THREAD

**Issue by ngenator** [hashicorp/terraform#11754]
Instart Logic is an application delivery platform with features beyond just a regular CDN. Their api is well documented and can manage all aspects of their service. It would be awesome if I could use Terraform to manage it's resources.

https://www.instartlogic.com/company/support/api-documentation

**Comment by mitchellh** [comment]
If someone wants to take a stab at this we'd be interested in making it happen. We generally don't keep these sorts of issues around (although I think some really older ones are lingering) since they're not very actionable and are large tasks. 

People submit new providers all the time and we merge them. So if someone wants to go for it, that sounds good!!
