### ISSUE TITLE
New provisioner request: remote-http

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#11845]
I would like to propose a new provisioner called `remote-http`.

Usage looks like:

````
provisioner "remote-http" {
    url = "https://c.io/bash/setup.sh"
    destination = "/tmp/setup.sh"
}
````

This results in the remote host making a `wget` request that downloads to `destination`.

**Comment by apparentlymart** [comment]
Hi @nodesocket! Thanks for this feqture request.

If I'm understanding correctly your use case it might make sense to think of this as a data source rather than a provisioner, thus allowing data to be retrieved for use in the configuration without needing to write a temporary file to disk:

```hcl
data "http_get" "example" {
  url = "https://c.io/bash/setup.sh"
}

provisioner "remote-exec" {
  inline = ["${data.http_get.example.body}"]
}
```

What do you think? This way we can provide a building block that can be used for a number of uses, and avoid the need to write a temporary file to disk, which we generally try to avoid because it adds extra external state that Terraform can't easily track.

(I assumed that you were intending here to download a script to separately execute, so I wrote the example with that in mind. If you just wanted to download the file and place it verbatim on the remote host then the `file` provisioner could be used instead of the `remote-exec` provisioner, using its `content` attribute to specify the downloaded data.)

**Comment by nodesocket** [comment]
@apparentlymart data source makes more sense, much cleaner. I think the problem would be the dependency on `wget`, but that would be a local dependency not remote right?

**Comment by apparentlymart** [comment]
@nodesocket if it were implemented the way I were imagining, it would actually be the terraform process that downloads the file, and then it would get uploaded to the target host over SSH as part of the `remote-exec` provisioner.

This would be quite similar to the existing `aws_s3_bucket_object` data source I suppose, but for talking to generic HTTP servers rather than specialized to S3.

I must admit on the first pass I didn't catch that you were intending the file to be downloaded directly onto the remote host. If we were just logging into the host and running `wget` then that would just be the same as using the the `remote-exec` provisioner to run `wget`, right?

**Comment by eranreshef** [comment]
Was this issue resolved some how?
I have a similar use case as @apparentlymart where I want a file to be downloaded from the web to the remote host during it's creation. Any suggestions?
