### ISSUE TITLE
AWS Added an additional AZ to us-east-1 and now `terraform plan` causes a state change

### ISSUE THREAD

**Issue by davidvuong** [hashicorp/terraform#11928]
### Terraform Version

```
Terraform v0.8.5

Your version of Terraform is out of date! The latest version
is 0.8.6. You can update by downloading from www.terraform.io
```

### Affected Resource(s)

aws_availability_zones

### Terraform Configuration Files

```hcl
data "aws_availability_zones" "available" {}

resource "aws_subnet" "main" {
  count             = 4
  cidr_block        = "${cidrsubnet(aws_vpc.main.cidr_block, 8, count.index + 1)}"
  availability_zone = "${data.aws_availability_zones.names[count.index]}"
  vpc_id            = "${aws_vpc.main.id}"

  map_public_ip_on_launch = true

  tags {
    Name        = "public-${data.aws_availability_zones.names[count.index]}"
    Environment = "${var.environment}"
  }
}
```

### Expected Behavior

`aws_availability_zones` should return the same AZ so long as I don't upgrade TF to a newer version.

### Actual Behavior

`aws_availability_zones` returned a new AZ `us-east-1d` which wasn't there originally. Looks like the API call to `DescribeAvailabilityZones` was the cause of this.

https://github.com/hashicorp/terraform/blob/039701fa512c052ec9afff52f2009dbc047621db/builtin/providers/aws/data_source_aws_availability_zones.go#L33-L69

My solution was to hardcode everything into a variable and use that. At least I know sudden changes externally won't affect my infrastructure:

```hcl
variable "availability-zones" {
  default = [
    "us-east-1a",
    "us-east-1b",
    "us-east-1c",
    "us-east-1e"
  ]
  type = "list"
}

resource "aws_subnet" "main" {
  count             = 4
  cidr_block        = "${cidrsubnet(aws_vpc.main.cidr_block, 8, count.index + 1)}"
  availability_zone = "${var.availability-zones[count.index]}"
  vpc_id            = "${aws_vpc.main.id}"

  map_public_ip_on_launch = true

  tags {
    Name        = "public-${var.availability-zones[count.index]}"
    Environment = "${var.environment}"
  }
}
```

Thoughts?

**Comment by mitchellh** [comment]
Hm, I see the problem but I also think that the data source is working as intended here. It refreshes and returns the availability zones in the order that AWS gave them to us. I don't think its safe to preserve order (or easy) because if AWS were to remove an AZ then really bad things would happen to people's configs who assume it doesn't change once created.

I don't think AWS ever introduces a new AZ re-using an old letter... I'm not sure though. But one option may be to sort the results? I'm going to tag this and let the provider team think on itmore.

**Comment by mwarkentin** [comment]
@mitchellh in our case, the availability zone added was us-east-1a, so I'm not sure sorting would always work either.

**Comment by davidvuong** [comment]
Any updates on this?

**Comment by apparentlymart** [comment]
A potential solution to this would be the `foreach` construct we discussed a few times already, which would be similar to `count` but could map the instances by map key rather than index. With the AZ name as the map key it would be safe to add a new one without throwing off the correspondences of the existing ones and causing unnecessary churn.

**Comment by davidvuong** [comment]
I couldn't find any docs around foreach, the closest I could find was an issue opened 2 years ago (https://github.com/hashicorp/terraform/issues/58). Could you provide an example or point me to the docs?

Another potential solution would be to call length of the list of AZ and use that for the count value. At least this won't accidentally destroy a subnet if a new one were to be added (e.g. abce => abcde). However, it would mean if a new AZ were to be added again, I'd be provisioning an additional subnet when I didn't expect to.

I think hardcoding the AZ I want to use is still a better solution.

**Comment by apparentlymart** [comment]
I don't think this `foreach` idea has ever had an issue of its own, since it's usually discussed in conjunction with other language features and use-cases, but I did find [the comment where I proposed it for the first time](https://github.com/hashicorp/terraform/issues/3310#issuecomment-162073715).

Manually specifying a list of AZs manually in a variable is a fine thing to do if you want a system that only changes when you deliberately alter the configuration, which I expect is the use-case for *most* Terraform users. (That is essentially how we have things working at my employer too, though we do it by instantiating the same module multiple times rather than by having a variable... same result, but a different way to get there.)

This data source has been used by some folks to create a situation where they (for example) spread an autoscaling group across all of the AZs available to them in a particular region and don't really care about exactly which AZs are in use and just want to maximize redundancy. I think supporting this has some value, but it's tricky to do right now since changes to the AZ list cause churn on the network infrastructure, as you saw. The `foreach` idea, given the ability to use the AZ list as keys, would fill in the gap to make this use-case work.

**Comment by davidvuong** [comment]
Yeah totally agree. I think being able to run `terraform apply` multiple times and give the same result every time without having changed anything explicitly is one of Terraform's main selling point.

When I started using Terraform a few months ago, a lot of tutorials out there mention the use of data sources to pull things like AZ. Is it worth having some kind of warning on the docs page, mentioning data sources won't always give the same response because providers can change their API at any time?

**Comment by gbmpgb** [comment]
resource "aws_subnet" "public" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.1.1.0/24"
  map_public_ip_on_launch = true
  availability_zone = "${data.aws_availability_zones.available.names[2]}"

  tags {
    Name = "public"
  }
}

resource "aws_subnet" "private1" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.1.2.0/24"
  map_public_ip_on_launch = false
  availability_zone = "${data.aws_availability_zones.available.names[0]}"

  tags {
    Name = "private1"
  }
}


resource "aws_subnet" "private2" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.1.3.0/24"
  map_public_ip_on_launch = false
  availability_zone = "${data.aws_availability_zones.available.names[1]}"

  tags {
    Name = "private2"
  }
}
