### ISSUE TITLE
aws_instance - Attach IAM role without re-creating

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform#11992]
Looks like AWS just added this functionality a few days ago:  https://aws.amazon.com/about-aws/whats-new/2017/02/new-attach-an-iam-role-to-your-existing-amazon-ec2-instance/

Currently, terraform triggers a destroy/recreate on any change to `iam_instance_profile`

**Comment by apparentlymart** [comment]
Looks like the key to this is the new API operations [AssociateIamInstanceProfile](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateIamInstanceProfile.html) and [DisassociateIamInstanceProfile](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DisassociateIamInstanceProfile.html).

I think the only annoying wrinkle here is that the Disassociate... operation takes an *association id* rather than an instance profile name, so we'll need either to retain that association id in a new attribute on the instance or look it up each time we need it using [DescribeIamInstanceProfileAssociations](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeIamInstanceProfileAssociations.html).

**Comment by stack72** [comment]
Hi @dcosson 

This has been asked for in #11852 - I am going to close this as a duplicate

Thanks

Paul
