### ISSUE TITLE
Unable to delete after failed apply

### ISSUE THREAD

**Issue by johnjelinek** [hashicorp/terraform#1200]
I tried to deploy a Windows AMI (without CYGWIN installed) and it failed during provision steps because nothing was listening on port 22. I shut down the `apply` forcefully to pick another AMI with SSH support. I can't `destroy` as it doesn't pick up anything to destroy, and I can't apply because the ELB already exists. I'm going to have to manually clean up :'(

**Comment by mitchellh** [comment]
If you shut down forcefully, partial state won't be saved for things in-progress (things already done will have it as of master, 0.4). We'll make this warning more clear for 0.4, I already have a branch working on this with a big warning. 

This is similar to #581 since now you're talking about taking something not under management and putting it under management. Closing for that dup.
