### ISSUE TITLE
Allow schema validation at plan time

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#12021]
Following up from #11993

For cloudflare, there are interdependent values such as the value of `cloudflare_record.proxied` can only be `true` if the value of `type` is one of `A`, `AAAA` or `CNAME`.

It would be very useful to validate this at plan time.

**Comment by grubernaut** [comment]
Depends on https://github.com/hashicorp/terraform/pull/4348, or similar solution to allow validation to occur at `plan` time.

**Comment by apparentlymart** [comment]
Hi @jleclanche! Sorry for the long silence here.

The use-case of validating across multiple arguments during the plan phase can now be met using [the `CustomizeDiff` function](https://www.terraform.io/docs/extend/resources.html#customizing-differences). Although its scope is larger than that -- it can also be used to _customize_ certain aspects of the diff -- the crucial thing for this issue is that it can return an error to block completion of the plan.
