### ISSUE TITLE
lookup doesn't like interpolation in the first arg

### ISSUE THREAD

**Issue by BastienM** [hashicorp/terraform#12043]
### Terraform Version

```
$ terraform version
Terraform v0.8.1
```

### Affected Resource(s)
**Core** (interpolation function lookup)

### Terraform Configuration Files
```hcl
variable "ec2_metrics" {
    default = [
        "CPUUtilization",
        "DiskReadBytes",
        "DiskReadOps",
        "DiskWriteBytes",
        "DiskWriteOps",
        "NetworkIn",
        "NetworkOut"
    ]
}
 
variable "alerts_list" {
    type = "list"
 
    default = [
        "myApp_cpu_alert"
    ]
}
 
variable "myApp_cpu_alert" {
    default = {
        "name"                  = "myApp CPUUtilization"
        "comparison_operator"   = "GreaterThanOrEqualToThreshold"
        "evaluation_periods"    = "2"
        "metric_name"           = "CPUUtilization"
        "namespace"             = "myApp"
        "period"                = "120"
        "statistic"             = "Average"
        "threshold"             = "80"
        "description"           = "Metric to monitor myApp CPU utilization"
        "actions"               = ""
    }
}
 
variable "myApp_cpu_alert_dimensions" {
    type = "map"
 
    default = {
        "AutoScalingGroupName" = "myApp"
    }
}
 
resource "aws_cloudwatch_metric_alarm" "standard_metric" {
    count               = "${length(var.alerts_list)}"
 
    alarm_name          = "${element(var.alerts_list, count.index)}"
    alarm_description   = "${lookup(format("var.%s", var.alert_list[count.index]), "description")}"
    alarm_actions       = ["${split(",",lookup(format("var.%s", var.alert_list[count.index]), "name"))}"]
 
    namespace           = "${lookup(format("var.%s", var.alert_list[count.index]), "namespace")}"
    metric_name         = "${lookup(format("var.%s", var.alert_list[count.index]), "name")}"
    comparison_operator = "${lookup(format("var.%s", var.alert_list[count.index]), "comparison_operator")}"
    period              = "${lookup(format("var.%s", var.alert_list[count.index]), "period")}"
    evaluation_periods  = "${lookup(format("var.%s", var.alert_list[count.index]), "evaluation_periods")}"
    statistic           = "${lookup(format("var.%s", var.alert_list[count.index]), "statistic")}"
    threshold           = "${lookup(format("var.%s", var.alert_list[count.index]), "threshold")}"
 
    dimensions          = "${element(alerts_list, count.index)}_dimensions"
}

output "test_format()" {
    value = "${format("var.%s", var.alert_list[0])}"
}
# returns "var.myApp_cpu_alert"

output "test_lookup()" {
    value = "${lookup(var.myApp_cpu_alert, "name")}"
}
# returns "myApp CPUUtilization

output "test_lookup(format())" {
    value = "${lookup(format("var.%s", var.alert_list[0]), "name")}"
}
# returns "lookup: argument 1 should be type map, got type string
```

### Debug Output
https://gist.github.com/BastienM/17af55eff030d8f8a98dba22db6b29ee

### Expected Behavior
`lookup()` should be able to interpret the dynamic string as a variable reference (`lookup(var.myApp_cpu_alert, [...])`) and moving on

### Actual Behavior
The said dynamic string is treated as a simple string (like `lookup("var.myApp_cpu_alert", [...])`)

### Steps to Reproduce
1. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @BastienM. Thanks for reporting this!

This is a strange issue. It looks like `lookup` is still doing the weird behavior it used to do in 0.6 and prior where Terraform didn't properly support maps yet and so a trick was used to make them appear to work for variable references only. Probably some legacy code left somewhere that we need to track down and eliminate.

**Comment by BastienM** [comment]
You're welcome.
Let me if you need further information.

**Comment by valentinbud** [comment]
I am also hitting this issue. Any updates on it? Thank you.

**Comment by apparentlymart** [comment]
Hi again, everyone!

Now that I'm looking at this issue a second time with fresh eyes, I see that you're both doing something unusual that I didn't catch on the first read.

The main focus of this issue, if I'm understanding it correctly, is expressions like this:

```
name = "" "${lookup(format("var.%s", var.custom_layers[count.index]), "name")}"
```

(I think I must've been looking at the wrong part of the configuration on my first read of this issue.)

It looks like what you're both trying to do here is to dynamically generate a variable name, but that's not how Terraform's configuration language works: expressions are not string-replacement macros. When you write the above, you're passing to `lookup` a string and a string, whereas this function expects a map and a string. Dynamic variable references cannot be supported since Terraform needs to be able to find all of the variables used during its graph-building pass in order to properly understand the relationships between the resources and the variables.

I think your use-case here is to use different values depending on a string given in a variable. In which case, the suggested approach is to invert how these are specified so that each of the values is in a map from the app name (or layer name, in @valentinbud's case) to the given value, like this:

```hcl
variable "app_name" {}

variable "app_alert_period" {
  type = "map"
  default = {
    app1 = "120"
    app2 = "240"
  }
}

resource "aws_cloudwatch_metric_alarm" "standard_metric" {
  # ...
  period = "${var.app_alert_period[var.app_name]}"
  # ...
}
```

Of course in the situations both of you are describing this formulation is pretty inconvenient, because you're trying to parameterize essentially all of the arguments of a given resource. We will likely add features in future that make it work better to have maps of maps, which could make this _somewhat_ more convenient, but in general I would suggest not to over-generalize and instead make use of Terraform modules to model the common aspects of apps/layers.

To take @valentinbud's example, I'd first define a child module called "layer" which looks like this:

```hcl
variable "name" {}
variable "short_name" {}
# ... all of the other keys from your layer configuration map ...
variable "stack_id" {}

resource "aws_opsworks_custom_layer" "main" {
  name       = "${var.name}"
  short_name = "${var.short_name}"
  stack_id   = "${var.stack_id}"
}

# ... any other resources you need for a layer ...
```

Then in the root you can instantiate that module once for each stack you want to create, without any indirection:

```hcl
module "aerospike" {
  source = "./layer"

  name                        = "Aerospike"
  short_name                  = "aerospike"
  stack_id                    = "${aws_opsworks_stack.main.id}"
  auto_assign_elastic_ips     = false
  auto_assign_public_ips      = false
  custom_security_group_ids   = ""
  auto_healing                = false
  install_updates_on_boot     = true
  instance_shutdown_timeout   = "120"
  elastic_load_balancer       = ""
  use_ebs_optimized_instances = false
  custom_setup_recipes        = "apt,deploy::system_config,system::infrastructure,deploy::aerospike"
  custom_configure_recipes    = "deploy::aerospike_monitor"
}

module "app_configurator_service" {
  source = "./layer"

  name = "App Configurator Service"
  short_name                  = "app_configurator_service"
  stack_id                    = "${aws_opsworks_stack.main.id}"
  auto_assign_elastic_ips     = false
  auto_assign_public_ips      = false
  custom_security_group_ids   = ""
  auto_healing                = true
  install_updates_on_boot     = true
  instance_shutdown_timeout   = "120"
  elastic_load_balancer       = ""
  use_ebs_optimized_instances = false
  custom_setup_recipes        = "deploy::system_config,system::infrastructure"
  custom_configure_recipes    = "deploy::app_configurator_service"
}
```

This different formulation is more consistent with Terraform idiom, shorter, and less complicated.

As mentioned above, in future we are planning to fix up some of the quirks with nested data structures that could make this sort of generality easier to achieve, but I would recommend that where possible it's better to do things explicitly and directly with Terraform configuration, rather than essentially creating a new proprietary configuration language inside variables.

So with all of that said, I'm going to close this not because we're not going to make things better in this area but because the specific approach requested here -- dynamically constructing variable names from strings -- is incompatible with Terraform's core architecture and so can't be implemented as stated. We're in the early stages of planning a revamp of how Terraform deals with data structures, which will likely surface as one or more other issues once we have something concrete enough to share.

Thanks again for the reports here and sorry I didn't quite understand what you were asking about at first.
