### ISSUE TITLE
index(list, var.element) throws error when element not found

### ISSUE THREAD

**Issue by in4mer** [hashicorp/terraform#12066]
### Terraform Version
```
% tf --version
Terraform v0.8.7
```

### Affected Resource(s)
Please list the resources as a list, for example:
- core

This is a core issue.

### Terraform Configuration Files
```
variable "list" {
  default = [ "one", "two", "three" ]
}

data "null_data_source" "indextest" {
  inputs = {
    result = "${index(var.list, "four")}"
  }
}
```

### Debug Output
I don't think that's necessary

### Expected Behavior
index should return -1.

### Actual Behavior
index threw an error that halted execution:
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * index: Could not find 'four' in '[{Variable (TypeString): one} {Variable (TypeString): two} {Variable (TypeString): three}]' in:

${index(var.list, "four")}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. ???
3. ...

### Important Factoids
This is dumb bug.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- couldn't find anything relevant

**Comment by Zevran** [comment]
I am experiencing the same behavior.

**Comment by dkolb** [comment]
While I'm not adverse to the error, it is making it very difficult to do some conditional interpolation.  For instance, in AWS we have two accounts, one for production and production-like and another for testing.

The problem becomes attempting to do something like:

```terraform
variable "detection_list" {
  type = "list"
  default = [ "prod", "uat", "prototype" ]
}

variable "environment" {
  type = "string"
  default = "not_prod"
}

output "use_prod_account" {
  value = "${index(var.detection_list, var.environment) > -1 ? "true" : "false"}"
}

output "use_prod_account_other_way" {
  value = "${coalesce(index(var.detection_list, var.environment), -1) > -1 ? "true" : "false"}"
}

output "even_another_way" {
  value = "${coalesce((index(var.detection_list, var.environment) > -1 ? "true" : "false"), "false")}"
}
```

It appears the error prevents any further evaluation.  NONE of those outputs even show up.  I don't mind the error but can I at least get the nil back and continue evaluating?  At least then I can coalesce the result of the call to index().

**Comment by teamterraform** [comment]
Hi all,

Terraform 0.12 has now fixed the issue where a conditional expression would evaluate both result expressions and possibly fail on the unselected one, making it possible to now write a plain conditional expression, like this:

```hcl
contains(var.list, "foo") ? index(var.list, "foo") : -1
```

We prefer this explicit conditional form because it's clear in the expression source that the author expects that the item might not exist and that the default value in that case is `-1`, rather than both of those details being implicit.

With that said, we're going to close this out now and recommend the above as the solution. Thanks for sharing this use-case, and sorry for the delay in addressing it.
