### ISSUE TITLE
Unable to set corrent Router mode for openstack_networking_router_v2

### ISSUE THREAD

**Issue by krjensen** [hashicorp/terraform#12106]
Hi,

I have 4 different Router Modes in Openstack, but i'm unable to use the `Centralized/Exclusive ` from terraform `openstack_networking_router_v2`, I can only set it to Distribute. Is the any way to do this?

![image](https://cloud.githubusercontent.com/assets/6542379/23123466/b9de49bc-f768-11e6-94aa-ae1aa945caab.png)

Terraform v0.8.7

**Comment by jtopjian** [comment]
@krjensen It's my understanding that "Centralized/Shared" is the opposite of distributed -- so just setting `distributed` to `false` will create the "Centralized/Shared" type of router.

I have never heard of "Centralized/Exclusive". The only documents that come up in Google are related to VMWare? I also did a search of the word "exclusive" at https://github.com/openstack/horizon and can't find anything related to a router-type. Are you using a VMWare-based OpenStack distro? It might be specific to that.

I imagine "Use Server Default" would be a config setting that makes one of the other 3 default.

**Comment by krjensen** [comment]
Hi,

Sorry for the lag of informations, but you are right i'm using VIO(vmWare Integrated Openstack). 
So this must be a VIO issue only and for now I'm creating the routers by hand and referring the by ID in terraform. Was just wondering if I was doing anything wrong.

**Comment by jtopjian** [comment]
@krjensen Nope, you're not doing anything wrong.

It might be possible to configure the other option through Terraform. You'll have to do some investigation, though.

1. Create a router through the command-line with the `--debug` flag set:

```shell
$ neutron router-create --debug ...
```

Note the `POST` request and look for a router type setting.

2. Create a `openstack_networking_router_v2` resource and use the [`value_specs`](https://www.terraform.io/docs/providers/openstack/r/networking_router_v2.html#value_specs) argument to add any VMWare-specific key/values you found:

```hcl
resource "openstack_networking_router_v2" "router_1" {
  ...
  value_specs {
    key = "value"
  }
}
```

The next release of Terraform will include enhanced OpenStack debugging so that you will be able to see the `POST` request that Terraform is sending. By doing this, you can compare Terraform's with Neutron's and try to get the two to match.

I'm going to close this issue, but let me know if you have any questions!

**Comment by krjensen** [comment]
I solved this - it was really simple!

```
  value_specs {
	router_size = "large"
	router_type = "exclusive"
  }
```

Thank you for helping me out

**Comment by jtopjian** [comment]
That's great news!

No problem at all :)
