### ISSUE TITLE
Conditional processing on resources

### ISSUE THREAD

**Issue by cemo** [hashicorp/terraform#12125]
I would like to use conditional processing which was introduced in 0.8.x but seems having something wrong. Here is the relevant part 

```
resource "aws_route53_record" "aws_alb_internal_dns_record" {
  count   = "${var.tld-internal-id != "0" ? 1 : 0}"
  name    = "${ var.cname}"
  records = ["${aws_alb.alb.dns_name}}"]
  ttl     = "300"
  type    = "CNAME"
  zone_id = "${ var.tld-internal-id }"
}
```

And the error message is: 

```
 * aws_route53_record.aws_alb_internal_dns_record: value of 'count' cannot be computed
```

I saw some examples in that https://github.com/hashicorp/terraform/issues/1604 and this is something very similar to them.  Why is this causing an error?

**Comment by tomdavidson** [comment]
related to https://github.com/hashicorp/terraform/issues/10857 ?

**Comment by apparentlymart** [comment]
Hi @cemo! Sorry for the issue here.

Would I be correct to assume that this resource is in a child module and the `tld-internal-id` variable is being passed in from a resource attribute in the parent module? That is the one situation in which a variable can be "computed" (which means that Terraform can't predict what the value will be until some other resource has been created).

Unfortunately if that's true then there's no good short-term fix for this other than to use the `-target` argument to help Terraform understand that it must first create the resource that this count depends on, and then (as a separate step, without `-target`) deal with this resource.

The proper fix for this issue would be something like what I proposed in #4149, which gives Terraform the ability to detect situations where multiple steps are required and essentially do the `-target` workaround for you automatically, with some better UI.

**Comment by cemo** [comment]
@apparentlymart It helped a lot. Should I leave this ticket open?

**Comment by apparentlymart** [comment]
@cemo if my assumption was correct then I think this issue ends up just being an example use-case for  #4149, so I'm going to close this one to keep discussion consolidated over there. Thanks for reporting it!

**Comment by cemo** [comment]
@apparentlymart Is terraform aware that which resources exactly will be created at the beginning of its lifecycle? I mean is it not possible to delegate some decision of some resource creation to runtime? 

PS: Sorry for asking on a closed issue but I think this is better than opening a new one.

**Comment by apparentlymart** [comment]
There are some subtleties to this which are difficult to quickly summarize, but the high-level idea is that Terraform wants to know the full set of resources early on so that the dependency graph can be constructed, but defers the _attribute values_ of the resources until runtime.

The key effect of this approach is that Terraform can describe in plan exactly which resources of which types will be created, updated and destroyed, even if it can't yet tell you what some of the attributes of those resources will be. This is considered to be a fundamental goal of Terraform, since it reduces uncertainty about what a given plan could affect, both from the perspective of avoiding unwanted downtime and of avoiding surprising cost.

**Comment by tinyzimmer** [comment]
I'm not sure I see why that would leave out the possibility of having a `block` like element, similar to ansible actually, for which you could apply a condition based on a variable's value. For example, only include this block of resources if some outside condition is met. 

While I can see the difficulty in applying this to the exported attributes of resources, it could still see many other use cases being able to act on the attributes of `data`, `backend`, and `variable` declarations. 

A quick example that I just came across was when I have my "environment" variable set to "prd" instead of a lower environment, I wanted additional routing policies applied to an Application Load Balancer in AWS.  I'm sure I could accomplish this with lists, or maps, and some fancy `count` + conditional interpolation, but a block-like structure like described above would read a lot nicer and be more approachable to novices.
