### ISSUE TITLE
Support for AWS Batch

### ISSUE THREAD

**Issue by awm33** [hashicorp/terraform#12187]
It doesn't look like Terraform currently supports [AWS Batch](https://aws.amazon.com/batch/).

**Comment by vpalos** [comment]
Yes, this would be an excellent feature for TF.

**Comment by stack72** [comment]
Hi @awm33 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72

**Comment by ashinohara** [comment]
Hi @stack72 I was wondering if you are aware of anyone that is working on a contribution for AWS batch?  Our organization is thinking about committing some resources to work on it but we don't want to duplicate any other community efforts that may be ongoing.  Thanks!

**Comment by stack72** [comment]
Hi andrew

I can say that there is no one from the Terraform team actively working on
AWS Batch

If your team are interested in adding the resources then that would be most
grateful. Let me know if there's anything you need

Thanks

Paul

**Comment by jonnyshaw89** [comment]
@ashinohara Did your team ever start anything on this?

**Comment by ashinohara** [comment]
@jonnyshaw89 We have started work and are waiting on https://github.com/terraform-providers/terraform-provider-aws/pull/1048 to merge, which contains support for `aws_batch_compute_environment`. Once that merges we plan on submitting our support for `aws_batch_job_definition` and `aws_batch_job_queue`.

**Comment by dtserekhman-starz** [comment]
Hi guys, any traction on this? Do you have any updates on AWS Batch support?
Thanks!
