### ISSUE TITLE
Security Groups should be able to rename without destroy/create

### ISSUE THREAD

**Issue by mcraig88** [hashicorp/terraform#12216]
### Terraform Version
v.0.8.7
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group

### Terraform Configuration Files

Changing this resource's Name, and Tag causes a destroy/create:

```hcl
resource "aws_security_group" "infra_common_endpoints" {
  provider    = "aws.${var.region}"
  name        = "${var.env_prefix}-INFRA_COMMON_ENDPOINTS"
  description = "Allows connectivity to: DNS, AppD, Splunk, AD, and other common services"

  tags {
    Name = "${var.env_prefix}-INFRA_COMMON_ENDPOINTS"
  }

  vpc_id = "${aws_vpc.main.id}"
}
```

```hcl
resource "aws_security_group" "infra_common_endpoints" {
  provider    = "aws.${var.region}"
  name        = "${var.env_prefix}-INFRA-COMMON-ENDPOINTS"
  description = "Allows connectivity to: DNS, AppD, Splunk, AD, and other common services"

  tags {
    Name = "${var.env_prefix}-INFRA-COMMON-ENDPOINTS"
  }

  vpc_id = "${aws_vpc.main.id}"
}
```

### Expected Behavior
The resource should be renamed without destroying and recreating.

### Actual Behavior
The resource is destroyed and recreated

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Sine the resource name is staying the same, I would image the underlying ID would remain the same, and only the Name would be modified. I can modify the Name through the console, and I would expect the same through TF.

**Comment by stack72** [comment]
Hi @mcraig88 

Thanks for raising the issue here - the Name parameter actually maps to the Group Name in the aws console. Once you create a security group, you cannot modify anything other than the rules of the tags. Updates rules and the tags are supported in Terraform, the former being a deletion and a recreation of the rule - the same way that AWS handles it. The description and the name (group name) are actually fixed

there is no way to do this via CLI or SDK or console. 

Unfortunately, I don't think we can support a way to do this in Terraform.

Thanks

Paul
