### ISSUE TITLE
provider/vcd - vApp/VM mismatched parameters and required states

### ISSUE THREAD

**Issue by nekarkedoc** [hashicorp/terraform#12234]
Thanks to all for implementing the Vcloud provider, it's initial state makes it basic enough to be useful for me trying to learn go and how to create a provider, as well as run against our Vcloud Director 5.5 lab projects, but I ran into issues attempting to create a vapp. My initial confusion began with the absence of a vm resource, but then assumed that the vapp resource was actually the vm resource based on the parameter set given in the vcd configuration guide for a vapp resource.
I'm going to blame VMware for much of the confusion, because outside the context of Vcloud, the term vapp is typically interpreted as referring to an appliance/vm. In Vcloud, however, a vapp is a collection of vms, networks, firewall defs, etc..
I should preface this by mentioning that I have a noob-level understand of go, and am a Vcloud novice so may be wrong on certain assumptions.
My initial configuration included all elements for the vms and networks, and plan ran ok, but the apply was crashing due to a panic condition in resource_vcd_network.go with a sigsev attempting to provide the edge_gateway value for the new OrgVDCNetwork.
When I looked at resource_vcd_network.go I noticed that edge_gateway was a required parameter, but further investigation into the data type structures in govcloudair api showed it was actually optional.
I grabbed the go compiler, cloned the latest Terraform from git, and modified resource_vcd_network to simply eliminated edge_gateway as a required parameter, and from the list provided to create OrgVDCNetwork. 
This fixed my issue partially, but then I continued to get failures regarding "cannot find vapp name nnnnnnn", I assume was due to the fact that no vm of that name existed in the catalog. So then I tried an existing vm in the catalog, and still same failure. 
I then provided the name to an existing pre-built, Vcloud vApp which contained multiple vms, but began having failures on "required parameter omitted"" for the various Terraform resource_vapp parms which were related to vms and not vapps. Again, the govcloudair types for those parameters also indicated they were not required but the Terraform  resource_vcd_vapp.go source had them as required.
When I modified resource_vcd_vapp to make them optional as well, the apply ran, but timed out eventually, and increasing the timeout to 20 minutes did not help. 
I then captured the dataflow between Terraform and our Vcloud Director, and found that the vApp had been instantiated just as it was in the catalog, but that Terraform was attempting to assign the same IP address to each VM in the Vcloud vApp, and failing, and then retrying.
Once I fully eliminated all vm specific parameters from the logic and parameters for resource_vcd_vapp.go, the vapp successfully deployed. The only parameters required to make that happen was vapp name, catalog_name, and template_name, which is about all you can specify in the GUI as well when choosing a vapp from a template. I'm fairly certain that when creating a vapp from scratch, you need nothing more than a name.
Admittedly, my approach was a sad hack, and if I were more comfortable with go I would have a better idea of how to fix it properly, but it seems to me that much of the code is already there, it just needs to be moved out of the vapp resource and placed within a new vm resource. 
Again, thanks, and I'm happy to provide whatever follow up information or doc you might need.

**Comment by robcoward** [comment]
Hi @nekarkedoc. Sorry your initial experiences with the vCloud provider have been a little painful. There is a current limitation in the provider and the underlying govcloudair library that only supports a single VM per vApp, and as such expects a vApp Template to only contain a single VM too. As you have discovered, it does clone the vApp, but then fails when making assumptions about the vApp only containing a single instance.

UKCloud are undertaking to enhance the functionality in the vCloud terraform provider and underlying library, and one feature that we will certainly be adding is the capability to deploy multiple VMs in a vApp. We are not quite there yet in terms of submitting a PR for merging, but watch this space.

If you have any other asks for feature enhancements, feel free to tag me in any issues etc - we may already have them on our backlog, or otherwise can take a view on adding them.

Regards,
Rob
