### ISSUE TITLE
aws elb ssl security policies

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#1226]
If you create an ELB, I think you get the current default policy, but there's no way to update them or configure them. Personally I would be happy with support for the predefined security policies, but others might want to be able to select their own list of ciphers:

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-policy-options.html

**Comment by phinze** [comment]
Hey there - we're consolidating Requests for AWS API Coverage over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next!

**Comment by ketzacoatl** [comment]
Making an update here, rather than in 28, so as to avoid the mail-bomb for a question that probably only needs to be reviewed by just a few: I ran into this issue while looking into SSL security policies (cipher suite configuration), and I see the redirect to 28, though 28 has no confirmation of SSL / cipher suite configuration, and (more confusingly), the google doc shows:
CreateLoadBalancerPolicy	TRUE	2	1226		jbiel, rlister

Though this issue doesn't provide the feature and I do not see any mention on https://terraform.io/docs/providers/aws/r/elb.html or as another resource in EC2.. so my question: if I'd like to see cipher suite support happen, where should I put in that vote or effort to make that reality happen?

**Comment by bruno** [comment]
:+1: I've added my name to the list on #28 as requested, however as @ketzacoatl mentions, this issue is referenced on the spreadsheet for a number of ELB api issues that seem to be unrelated to this particular one.

**Comment by darend** [comment]
:+1: on feature request, and the confusion with the spread sheet. Currently you are unable to associate a custom security policy with an ELB listener.
