### ISSUE TITLE
Please expand docs on lists in terraform

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform#12299]
I'm trying to understand how terraform handles lists.  I want to write configs that allow flexible parameters - for example, I'd like to have a resource with a terraform-created security group, plus a mandatory security group ID parameter, plus a list of optional additional security group ids.

Some things I'm not understanding: When do I need brackets around list types?  Behavior seems to change if the config mixes variables and computed resource attributes, is there something special I need to do?  The docs on lists are pretty thin, this might just be a request for more detail or non-trivial examples.

### Terraform Version
`Terraform v0.8.7`, but going back through 0.7 too.

### Affected Resource(s)
Any resource that has a list parameter.

### Terraform Configuration Files
```hcl
variable "subnets" {
  type = "list"
}

variable "mandatory_sg_id" {
  type = "string"
}

variable "optional_sg_ids" {
  type = "list"
  default = []
}

resource "aws_securty_group" "health-checks" {
  ...
}

resource "aws_elb" "elb" {
  subnets = "${var.subnets}"
  security_groups = "${distinct(concat(
            list(aws_security_group.health-checks.id),
            list(var.mandatory_sg_id),
            var.optional_sg_ids
        ))}"
}
```

### Expected Behavior
I expect consistent behavior of lists in terraform configs.

distinct and concat are documented as functions from lists to lists, but the above `security_groups` parameter only works if I wrap it in square brackets.  That seems wrong - wont that be a list of lists instead of a list of strings?

Meanwhile, the `subnets` parameter (also a list) is happy without them.

### Actual Behavior
Without additional square brackets around the `security_groups` expression:

Errors:

  * aws_elb.elb: security_groups: should be a list

**Comment by apparentlymart** [comment]
Hi @rvandegrift! Sorry for the long silence here.

As you saw, Terraform 0.11 and earlier had some quite inconsistent handling of list values. In particular, the "should be a list" error you saw was generally caused by Terraform not correctly handling a list containing an element whose value won't be known until the apply step: it was mis-detecting that as being of a type other than list.

Although we never did fully document all of the quirks you mentioned, Terraform v0.12.0 has an entirely new evaluation engine in the language which handles lists in a more consistent way. The seemingly-redundant extra list brackets are never required and are in fact no longer even _allowed_, because the result would then be a list of lists rather than a single list.

We rewrote all of the language documentation as part of the Terraform 0.12.0 release, so you can see some general information about the new type behavior in [Expressions](https://www.terraform.io/docs/configuration/expressions.html) and in [Type Constraints](https://www.terraform.io/docs/configuration/types.html). However, our hope is that the new behaviors will generally be intuitive if you're bringing experience from other languages that have a type system where lists have a specific element type (as opposed to a dynamic language where lists can contain any combination of types, which is not true for Terraform).

Because this was such a broad issue it's hard to say whether it's now "done", but that's understandable since your feedback here was that lists were generally inconsistent. We've done our best to make them behave more consistently now, but would welcome anyone to open separate issues if they find that any of these inconsistencies -- or indeed any _new_ inconsistencies -- are still present in Terraform v0.12.0 or later.

Thanks, and sorry again for the long silence.
