### ISSUE TITLE
Web Site - Documentation 503

### ISSUE THREAD

**Issue by eedwardsdisco** [hashicorp/terraform#12306]
https://www.terraform.io/docs/providers/aws/index.html

Clicking on any individual documentation item for a provider in the aws list results in a 503:

e.g.
https://www.terraform.io/docs/providers/aws/r/sqs_queue.html
https://www.terraform.io/docs/providers/aws/r/sns_topic.html

**Comment by eedwardsdisco** [comment]
AWS is having S3 issues in us-east-1

I suspect the docs are served out of a bucket in us-east-1 and this will auto-resolve once the upstream problems are resolved.

**Comment by stack72** [comment]
Hi @eedwardsdisco 

Thanks for opening the issue here - unfortunately, due to the issues that are being seen with AWS S3 right now, we are seeing issues serving our content. We are trying to restore the content via a different medium

Please do let us know if there are any other issues

Thanks

Paul
