### ISSUE TITLE
data aws_security_group changes every time

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#12335]
Terraform 0.8.7

I have an aws_security_group data point:

```
data "aws_security_group" "domaincontrollers" {
    name        = "${aws_directory_service_directory.microsoft_ad.id}_controllers"
    depends_on  = ["aws_directory_service_directory.microsoft_ad"]
}
```

I use this to look up the security group that is automatically created when I spin up an aws_directory_service_directory by the way.

This works a treat, and I can add rules to the corresponding security group.

Except every time a plan is run, it does this:

```
~ data.aws_security_group.domaincontrollers
    name:   "" => "d-1234567890_controllers"
    tags.%: "" => "<computed>"
    vpc_id: "" => "<computed>"
```

which means that all the aws_security_group_rule resources i have against this data.aws_security_group get blown away and recreated on every terraform apply. 

Is there a way to stop this happening?

**Comment by apparentlymart** [comment]
If you remove the `depends_on` attribute (already implied by your interpolation anyway) then this should work. Currently `depends_on` always forces a data resource to be refreshed during apply because Terraform can't tell what aspect of the dependency should trigger a refresh so it is pessimistic for safety.

**Comment by mitchellh** [comment]
Closing due to answer
