### ISSUE TITLE
Feature Request: Kubernetes provider

### ISSUE THREAD

**Issue by vise890** [hashicorp/terraform#12343]
After terraforming things like a `"google_service_account"`, it would be great to terraform k8s `Secrets` or `ConfigMap`s containing the details. This, in conjunction with #12342 would pretty much eliminate the need for glue bash scripts.

**Comment by radeksimko** [comment]
Hi @vise890 
I'm currently working on the K8S provider and aim to submit PR _very soon_ with first resources and more to follow.

I'll keep you posted here.

**Comment by vise890** [comment]
sweet :)

**Comment by radeksimko** [comment]
It doesn't include the resources you mentioned but feedback is welcomed for the initial PR: https://github.com/hashicorp/terraform/pull/12372

**Comment by radeksimko** [comment]
Hi @vise890,
the K8S provider + `kubernetes_namespace` was just merged and here is `kubernetes_config_map`: https://github.com/hashicorp/terraform/pull/12753

Feel free to chime in with any feedback on the merged provider or the new resource.

**Comment by vise890** [comment]
Awesome work @radeksimko !

I had a look at the `kubernetes_config_map` PR and it  also looks great;

 I was gonna try my hand at building a resource for a k8s `Secret` and I reckon it'd be extremely similar to what you have in the `ConfigMap` one; to the point where it'd probably be mostly a copy paste job.... Would you mind me doing that? I completely understand if you want to do it, since you put in all the work!

**Comment by radeksimko** [comment]
Feel free to pick up `secret`. I'm currently working on PVs and PVCs, then probably moving onto Pods.

One important thing to keep in mind is that we'll have to use PATCH for updating all K8S resources, instead of the standard 1-for-1 update. See https://github.com/hashicorp/terraform/pull/12945 for more details.

Also feel free to leverage https://github.com/radeksimko/terraform-gen for the initial work, I will soon add support for generating PatchOperations too.
