### ISSUE TITLE
aws_api_gateway_deployment needs a delay between "something" and being created.

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#12416]
It seems that `aws_api_gateway_deployment` needs a slight delay before being created.

### Terraform Version
0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_api_gateway_deployment
- ???

### Terraform Configuration Files
```hcl
resource "aws_api_gateway_integration_response" "slack-commands" {
  rest_api_id                 = "${aws_api_gateway_rest_api.slack-commands.id}"
  resource_id                 = "${aws_api_gateway_resource.slack-commands.id}"
  http_method                 = "${aws_api_gateway_method.slack-commands.http_method}"

  status_code                 = "${aws_api_gateway_method_response.slack-commands-200.status_code}"

  response_templates          = {
    "application/json"        = ""
  }
}
```
(I can provide the rest of the manifest if requested).

### Expected Behavior
The integration to be created.

### Actual Behavior
First time I got
```
* aws_api_gateway_integration_response.slack-commands: Error creating API Gateway Integration Response: NotFoundException: No integration defined for method
        status code: 404, request id: 827dcc64-002d-11e7-ac10-6573201d9a04
```

Second time, a few (twenty perhaps?) seconds later, it worked.

**Comment by apparentlymart** [comment]
Hi @FransUrbo,

It's been a while so I'm a bit rusty here, but I remember that when using the API gateway resources it was necessary to add explicit dependencies between the resources to ensure that Terraform creates them in the right order, since there are validation checks that happen implicitly on various operations.

For this case I would suggest interpolating the attributes from your `aws_api_gateway_integration` resource rather than your `aws_api_gateway_method` resource, which will help Terraform understand that the integration must be created before the integration response.

**Comment by sullivandl** [comment]
I'm experiencing this same issue.  Thank you @apparentlymart for the response, but I believe this is specific to the `aws_api_gateway_deployment`.  I have the explicit dependencies you suggest, but unfortunately it does not help.  

As @FransUrbo suggests running a simple 'apply' a second time results in success.  It does feel like the method integration is not immediately available.

**Comment by steve-gray** [comment]
@sullivandl: It gets worse: for this kind of thing, I've often found that a suitably fast usage of the AWS CLI directly in a bash script (my initial attempt to work around this) would yield the same problem. I'd create a method, only to reference it immediately after and fail. Re-running would work, but it was particularly exasperating.

Potentially what's needed is some sort of opt-in resource behaviour to allow time-based retries - so when you get a 404 error, it can do a back-off retry cycle for 1, 2, 4, 8 seconds etc, until eventually a timeout is hit or the resource is reference-able. The real problem is that resources are created on API gateway asynchronously in some cases it seems, and the CLI/Go-SDK is reporting back a success prematurely rather than hanging on.
