### ISSUE TITLE
provider/google: container enginer node_version should be read-only

### ISSUE THREAD

**Issue by paddyforan** [hashicorp/terraform#12435]
In the `google_container_cluster` resource, we have a `node_version` field that sets the `InitialClusterVersion` of the cluster. But according to [the docs](https://godoc.org/google.golang.org/api/container/v1#Cluster) that appears to be an output-only (read-only) property, and not something that will be taken into account when creating the cluster.

This came up when investigating the following test failure:

```
=== RUN TestAccContainerCluster_withVersion
 --- FAIL: TestAccContainerCluster_withVersion (0.35s)
 testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:

 * google_container_cluster.with_version: 1 error(s) occurred:

 * google_container_cluster.with_version: googleapi: Error 400: Version is invalid., badRequest

 FAIL
```

**Comment by paddyforan** [comment]
Tagging @radeksimko, who originally added the attribute. Also tagging @danawillow, who I know is doing some GKE work. Anyone have thoughts on whether this is wrong docs upstream or our code is out of date? Also, can anyone find info on what a valid version would be so we can green this test?

**Comment by danawillow** [comment]
The documentation on this is sadly, inconsistent. I'm pretty sure the answer is that it's not actually output-only. I filed a bug to get that fixed.

In the meantime, here's a list of versions: https://cloud.google.com/container-engine/release-notes

1.5.3 sounds like a good choice.

**Comment by radeksimko** [comment]
I think this is actually documented well, just the name used in the schema may be confusing in this context as it basically has 2 counterparts in the API:

 - `DesiredNodeVersion` of [`ClusterUpdate`](https://godoc.org/google.golang.org/api/container/v1#ClusterUpdate) which is read/write (for upgrading the cluster)
 - `CurrentNodeVersion` of [`Cluster`](https://godoc.org/google.golang.org/api/container/v1#Cluster)

See our discussion from the initial PR - https://github.com/hashicorp/terraform/pull/2357/files#r34348452

Are you perhaps getting the 400 error because we have too old version in the test [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_container_cluster_test.go#L319)? Either way the error message could be improved on the server side.

**Comment by paddyforan** [comment]
That's incredibly frustrating. Yeah, this came up when I was investigating bumping the version to make the test pass. :) Thanks for the explanation, appreciate the correction.
