### ISSUE TITLE
Bug when running plan with an added count

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#1245]
This happened with an aws_subnet, but i'm going to assume it could happen else where. Steps to get there:

1. create a subnet without a count parameter
2. set count = 1
3. run plan
4. state file now has 2 entries "subnet" and "subnet.0". They both point to the same aws resource.

**Comment by catsby** [comment]
Hey @ryanking are ou getting this on 0.3.7? I'm not seeing this behavior on the `master` branch

**Comment by mitchellh** [comment]
Core has changed so much with regards to counts and how resources in state are managed that I'm 99% sure that this problem is gone or just completely different on master. We did a LOT of added unit tests and refactors around count that should greatly improve stability here in 0.4.

@catsby This would be a core issue. No worries on AWS :)

**Comment by ryanking** [comment]
Yeah, I think this was on 0.3.6. Just tried again on 0.3.7 and couldn't
reproduce.

**Comment by mitchellh** [comment]
@ryanking Ah yeah, 0.3.6 had a lot of count problems we fixed. :)
