### ISSUE TITLE
Splitting an empty string does not produce an empty list. Causing unexpected results.

### ISSUE THREAD

**Issue by beanaroo** [hashicorp/terraform#12472]
### Terraform Version
`0.8.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route
- possiibly core

### Terraform Configuration Files
```hcl
resource "aws_route_table" "public" {
  vpc_id           = "${aws_vpc.mod.id}"
  propagating_vgws = ["${var.public_propagating_vgws}"]
}
```
Being passed as:
```
    public_propagating_vgws   = "${split(",",var.vpc["public_propagating_vgws"])}"
```
### Expected Behavior
Split on empty string should produce an empty list. (i.e. resource attribute should not be added.

### Actual Behavior
```
module.preview_vpc.aws_route_table.public: Modifying...
  propagating_vgws.#: "0" => "1"
  propagating_vgws.0: "" => ""
```
Will result in error:
`* aws_route_table.public: MissingParameter: The request must contain the parameter gatewayId`

### Steps to Reproduce
1. Split a string on an empty string for an attribute expecting a list.
2. `terraform plan`

### Important Factoids
Using configuration guidelines and examples straight from the documentation.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1720

**Comment by beanaroo** [comment]
As suggested by another user, the following workaround:
```
public_propagating_vgws   = "${compact(split(",",var.vpc["public_propagating_vgws"]))}"
```

**Comment by tcrall** [comment]
Thanks - solved my problem

**Comment by teamterraform** [comment]
Hi @beanaroo! Sorry for the long silence.

Both the current behavior and your expected behavior for `split` are defensible as correct behavior depending on how you think about this operation.

Terraform interprets it as partitioning the given string around any instance of the given delimiter, so if there are no delimiters at all then you get a single string.

If the function were instead defined as returning only _non-empty_ strings after doing that partition then having `split(",", "")` return an empty list would make sense. However, for consistency that ought to also be true for `split(",", ",")` (both strings are empty), and `split(",", "foo,")` would need to return `["foo"]` because the second string is empty here.

Changing this behavior now would be a breaking change, so we can't do it. Fortunately, as you found the `compact` function already implements the behavior of eliminating any empty strings from the result, so the combination of the two gets the result you wanted. In the end, the current design has the advantage that there's a way to get both behaviors, whereas if `split` were to remove empty strings by default then there'd be no way for another function to recover those empty strings.

With that said, we don't plan to make any changes to `split` here. The `compact` function is a good way to explicitly ignore empty strings in the result.

Furthermore, Terraform's handling of rich types in variables should now be good enough to avoid the need for this historical hack of passing lists as delimited strings and splitting them at the last moment. Instead, we can define this `vpc` variable as a set or list and then assign it directly without splitting:

```hcl
variable "vpc" {
  type = object({
    # (any other VPC attributes)
    public_propagating_vgws = set(string)
  })
}
```

Since other features of Terraform have caught up with this use-case, and since `compact` can be used to address it in any remaining situation, we're going to close this out now. Thanks for opening this, and sorry again that it sat with no response for so long.
