### ISSUE TITLE
Unable to output aws_ebs_snapshot tags as a map

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#12478]
I am using Terraform 0.8.8 and am trying to output the tags from an EBS snapshot returned by the `aws_ebs_snapshot` data source. This code almost works:

```
data "aws_ebs_snapshot" "snapshot" {
  most_recent = true
  owners      = ["self"]

  filter {
    name   = "status"
    values = ["completed"]
  }

  # REDACTED
}

output "tags" {
  value = "${data.aws_ebs_snapshot.snapshot.tags}"
}
```

The problem here is that `tags` contains a list of key-value pairs, whereas I want a map. Specifically, the output looks like this:

```
tags = [
    {
        key = key_one,
        value = value_one
    },
    {
        key = key_two,
        value = value_two
    },
    {
        key = key_three,
        value = value_three
    }
]
```

It seems like the `zipmap` function should do what I want, but it doesn't seem to work:

```
data "aws_ebs_snapshot" "snapshot" {
  most_recent = true
  owners      = ["self"]

  filter {
    name   = "status"
    values = ["completed"]
  }

  # REDACTED
}

output "tags" {
  value = "${zipmap(data.aws_ebs_snapshot.snapshot.tags.*.key, data.aws_ebs_snapshot.snapshot.tags.*.value)}"
}
```

When I run this code, no outputs are produced.

```
data.aws_ebs_snapshot.snapshot: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by joshuaspence** [comment]
Here is some relevant output from running with `TF_LOG=1`

```
2017/03/07 10:31:18 [WARN] Output interpolation "tags" failed: At column 3, line 1: zipmap: argument 1 should be type list, got type string in:

${zipmap(data.aws_ebs_snapshot.snapshot.tags.*.key, data.aws_ebs_snapshot.snapshot.tags.*.value)}
2017/03/07 10:31:18 [TRACE] [walkPlan] Exiting eval tree: output.tags
...
2017/03/07 10:31:18 [WARN] Output interpolation "tags" failed: Resource 'data.aws_ebs_snapshot.snapshot' does not have attribute 'tags.*.value' for variable 'data.aws_ebs_snapshot.snapshot.tags.*.value'
```

**Comment by apparentlymart** [comment]
Hi @joshuaspence! Sorry for the long silence here.

Back in Terraform 0.8.8 there wasn't really any good way to deal with this problem, because the splat operator only worked for whole resources and Terraform's type system didn't have the idea of object types yet.

Terraform 0.12 provides a few more features that make this easier to wrangle. The way you tried here could work due to the generalization of the splat operator:

```hcl
output "tags" {
  value = zipmap(
    data.aws_ebs_snapshot.snapshot.tags.*.key,
    data.aws_ebs_snapshot.snapshot.tags.*.value,
  )
}
```

Alternatively, this could be done using a `for` expression:

```hcl
output "tags" {
  value = { for obj in data.aws_ebs_snapshot.snapshot.tags : obj.key => obj.value }
}
```

As we discussed over in #14233, it'd be better if the `aws_ebs_snapshot` data source would return the tags in a more usable way to start with, but at least with these new features in Terraform 0.12 it's possible to compensate for this unusual design decision by constructing the map value afterwards.
