### ISSUE TITLE
Cannot reference mapped variable component in TF

### ISSUE THREAD

**Issue by westredd** [hashicorp/terraform#12491]
### Terraform Version
0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group

The issues is to do with a mapped variable that a resource cannot reference. In this case its a security group but could be any resource.

### Terraform Configuration Files

```hcl
variable "siteDetailsGlobal" {
  type = "map"
  default = {
  internalIpRange = "10.100.0.0/16"
  vpnGatewayExtInterface = "10.20.61.129"
  publicIpRange1 = "20.20.61.128/26"
  publicIpRange2 = "30.30.167.0/24"
  }
}

resource "aws_security_group" "sg_devalb" {
  name = "sg_devalb"
  description = "Sec Group for inbound requests to DEV ALB"
  tags {
    Name = "sg_devalb"
	environment = "Development"
  }
} 
 
 resource "aws_security_group_rule" "mfd-test-rule" {
    type = "ingress"
    from_port = 443
    to_port = 443
    protocol = "tcp"
    cidr_blocks = 	["$${var.siteDetailsGlobal[internalIpRange]}"
					]			
    security_group_id = "${aws_security_group.sg_devalb.id}"
}
```

### Debug Output
https://gist.github.com/westredd/1f0e45c93eb414db658af18160f714fb

### Panic Output
NA

### Expected Behavior
IP from the references mapped var var should be used 

### Actual Behavior
See debug error

### Steps to Reproduce
Create the above TF under TF configuration files
I was originally used a single $ here:

```hcl
cidr_blocks = 	["$${var.siteDetailsGlobal[internalIpRange]}"
```

But TF told me to use 2x $. When i did that i was able to get a TF plan to run. 

### Important Factoids
NA

### References
NA

**Comment by apparentlymart** [comment]
Hi @westredd! Sorry for the long silence here.

I'm not sure what was going on here, but the expected syntax for accessing an attribute from a map would be this:

```hcl
  cidr_blocks = ["${var.siteDetailsGlobal.internalIpRange}"]
```

The meaning of `var.siteDetailsGlobal[internalIpRange]` is to use the value of some symbol called `internalIpRange` as the key, but no such symbol exists. A different way to write this would be `var.siteDetailsGlobal["internalIpRange"]`, which uses a literal string as the key and thus allows the key to potentially contain characters that Terraform would not permit in an attribute name.

There have been lots of changes to Terraform's configuration engine since 0.8.8 so I expect this behavior is different now, and I'm going to close this out. I'm sorry that there was no response before this; I've just been working through some older issues that use an older labeling scheme and thus were missed on previous passes. If you're still seeing similar problems on the latest release of Terraform, please do feel free to open a new issue about that just to capture the latest behaviors.

**Comment by westredd** [comment]
Thanks for the help. Appreciated
