### ISSUE TITLE
Outputs of type map may be interpolated unexpectedly or lead to panic

### ISSUE THREAD

**Issue by janschumann** [hashicorp/terraform#12546]
Hi there,

I came across an unhandled exception (my first one in terraform :smirk:), when using remote state output of type `map`.

It occurs when the keys of that map contain more than three dots in it (`foo.bar.baz.boom`). As dots are used as separators to convert maps to their representation in state files, this issue might be expected, but instead of an exception, a warning should be issued, saying that dots in keys are not allowed. 

### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- terraform_remote_state

This issue might also occur on any other data resources.

### Terraform Configuration Files
As this issue affects mainly remote states, it cannot be reproduced using a simple snippet. I created a repo that documents the described behavior.: https://github.com/janschumann/terraform_remote_state_output_interpolation

### Debug Output
The debug output is included in the repo.

### Panic Output
The `crash.log` is included in the repo.

### Expected Behavior
Outputs of type `map` from remote states (and maybe other data resources) should be interpolated in the same way as local variables.

### Actual Behavior
In interpolation, if outputs of remote states of type map contains dots, it is split up to an undefined type using the dots as separators.

If there are more than 3 dots in the key, a panic occurs.

Local variables with the same values as the remote ones are interpolated correctly.

### Steps to Reproduce
Please see the README in that repo for steps to reproduce.

### Important Factoids
In the examples only `null` provider and `local` remote states are used.

**Comment by teamterraform** [comment]
Hi @janschumann! Thanks for reporting this and sorry for the long delay in responding.

Your example repository is not there anymore, which is understandable given how long it's been since you opened this issue. However, the relevant portion of Terraform that would've caused this crash was completely rewritten for Terraform 0.12, and so this should now work correctly.

The problem was a consequence of how in 0.11 and earlier the state for a resource instance was represented as a dot-delimited path through attributes, and so dots in the keys themselves would make the result ambiguous. That is no longer true, because the state for a resource instance is now represented as a proper nested data structure, with the `outputs` attribute on `terraform_remote_state` represented as an object value.

However, along with that Terraform 0.12 no longer allows output value names to contain dots in the first place, so the exact situation you described cannot arise any longer.

Thanks for reporting this and sorry again for the delay in responding to it.
