### ISSUE TITLE
Terraform as a Library

### ISSUE THREAD

**Issue by DaveBlooman** [hashicorp/terraform#12582]
I'm looking to do some custom CI pipelines with TF, but I don't want to use the command line interface.  To that end, I have written a wrapper around plan/apply, but I'm having trouble building and running.  

My current situation is that TF can't seem to find the internal AWS provider, I'm guessing its the way in which TF is built that specifies the location?  

In any case, is there any guidance for using TF in this way, as a dependency?

**Comment by alexsomesan** [comment]
I believe your problem might have to do with the fact that all stock providers are built into the same binary which terraform then re-execs into when calling a provider.
I assume that a custom binary which wraps terraform has to allow for that behaviour.

For example, to use the TLS provider, Terraform would exec it's own binary with this command line:
```
terraform internal-plugin provider tls
```

whose output on a terminal looks like this:
```
2017/03/10 21:33:17 [INFO] Terraform version: 0.8.8
2017/03/10 21:33:17 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.8.8/bin/terraform", "internal-plugin", "provider", "tls"}
2017/03/10 21:33:17 [DEBUG] Detected home directory from env var: /Users/alex
2017/03/10 21:33:17 [DEBUG] Detected home directory from env var: /Users/alex
2017/03/10 21:33:17 [DEBUG] Attempting to open CLI config file: /Users/alex/.terraformrc
2017/03/10 21:33:17 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/03/10 21:33:17 [DEBUG] Detected home directory from env var: /Users/alex
tls-provider (internal) 2017/03/10 21:33:17 [INFO] Starting provider plugin tls
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

**Comment by munjeli** [comment]
I use terraform this way, and packer too. I have a CLI that does build and deploys of standardized environments and infrastructure objects on AWS and Azure. The only issue I've run into is on exit - it sometimes takes a while for tf to finish the operation and in my current version I can't run tf commands in parallel. I had to consider my dependencies and set up modules accordingly. The thing I like best about Hashicorp stuff is the bare bones interfaces that make metaprogramming easy, it's like BYOI (bring your own interface!).

**Comment by paddyforan** [comment]
Hi there! While this is an interesting and worthwhile discussion that we totally support users having, we _do_ have a lot of open issues on the Terraform repo already, and we're trying to manage the number of them, just to make it easier for our contributors to find issues to work on. Because this issue isn't tracking a unit of work for our contributors and is about discussion, I'm going to close it out. But I encourage you to continue the conversation on [Gitter](https://gitter.im/hashicorp-terraform/Lobby) or the [mailing list](https://groups.google.com/group/terraform-tool)! Thanks for your interest in Terraform, and I hope you find a good solution. :)

**Comment by cristim** [comment]
@paddycarver I hope it's fine to also discuss this here, now that we have this issue with a certain amount of context.

I was also contemplating to use Terraform as a library, instead of wrapping the command-line arguments and outputs. At the moment a colleague of mine is in the process of building a Python wrapper against the cli, but I think a native go program hooking natively into the underlying code(assuming the interfaces are stable enough) would be a better option.

For a small deployment orchestration tool I'm mostly interested in programmatically planning/applying the terraform code stored in a given directory against a given remote state file stored in Amazon S3 using some custom parameters generated dynamically based on environment variables or command-line arguments, and getting the stack outputs of a previous apply run into a data structure in order to avoid parsing command-line output.

Can someone show the best way to achieve this?

**Comment by munjeli** [comment]
@cristim I opened a thread on the mailing list: https://groups.google.com/forum/#!topic/terraform-tool/8-q6NDa1nsU I'm writing a new version of my own tooling that metaprograms with Packer and Terraform. I'd be glad to discuss the patterns I'm working. This is the third version of my CLI which I've been using for the last 2 years and was originally written in Ruby. I'm now writing Go, and looking for better ways to interface.

**Comment by apparentlymart** [comment]
Hi @cristim,

It's currently possible in principle for a Go program to import and use the Terraform packages, and this is okay to do with the following caveats in mind:
* The APIs are not really _designed_ for external use, and assumes a certain amount of knowledge about Terraform's internal architecture. It'll probably take more code than you'd hope to call into Terraform as a library, just because that's not a use-case we've optimized for at this time.
* We're not currently making any guarantees about backward compatibility of the Terraform package APIs, since we're still doing frequent reorganization of the code as we converge on "the right design" for the internals, so an application calling into Terraform as a library is likely to be broken by future Terraform changes and thus I'd encourage the use of vendoring.

For most purposes we'd currently recommend interacting with Terraform via the CLI. We have [a guide on this](https://www.terraform.io/guides/running-terraform-in-automation.html) that covers the most common use-cases. The advice here _may_ change slightly in forthcoming major releases, but in general we put much more effort into preserving compatibility with the CLI workflows than with the Go package APIs at this time.

**Comment by tboerger** [comment]
I'm also planning to use Terraform as a library for some kind of demo launcher system, but after reading this issue it doesn't sound like a really good idea :(

**Comment by munjeli** [comment]
@tboerger I think that you're not understanding the architecture. The guide they made is great for how to write a wrapper on terraform, and there's no reason to 'use it as a library' for a demo launcher system unless you need to package a single binary for public distribution. Why not just wrap it? That's how I built the first couple of versions of my own tooling.

**Comment by tboerger** [comment]
I'm understanding the architecture, but it looks like it's not recommended to use Terraform as a library. Of course you can just wrap the binary, but for me personally this is not a proper solution :)

**Comment by jcarley** [comment]
Although I agree with using the CLI, we are finding it very limiting to use it in some automation scenarios where we would like to be able to read the results of a plan.  Something more machine readable (e.g. JSON).  I've heard rumors this is on the roadmap, is that still the case?

**Comment by invidian** [comment]
@jcarley Terraform 0.12 will have `terrafrom show -json` command, which will output terraform plan in JSON format. https://www.terraform.io/docs/commands/show.html
