### ISSUE TITLE
Output on plugin API mismatch is misleading

### ISSUE THREAD

**Issue by rtizzy** [hashicorp/terraform#12580]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)

Custom providers that have API mismatches

### Expected Behavior

A clear error should be provided that indicates the plugin version is mismatched with the current API version of terraform. It should then output the version of each.

The output should be something like the following.

```
* Incompatible API version with plugin '_terraform-provider-example_'. Terraform API version: 4, Plugin API Version: 2
```

### Actual Behavior

The error provided has misleading language that does not clarify what actually has the version mismatch (Terraform or the Provider). "Ours" would seem to indicate the API version of terraform but instead indicates the version of the plugin

* Incompatible API version with plugin. Plugin version: 4, *Ours*: 2

### Steps to Reproduce

1. Install a provider with a API mismatch. 
2. Attempt to interact with the plugin. 

**Updated with suggestions by @ekhaydarov.**

**Comment by ekhaydarov** [comment]
How does one actually change the plugin version? I cant seem to find it in the docs

**Comment by mitchellh** [comment]
We should definitely be able to improve this in every way recommended here. Thanks!

**Comment by elricsfate** [comment]
@mitchellh Thanks!

@ekhaydarov Can you clarify what you mean by update the vendors? I'm working on upgrading my Vultr provider so it works with the latest version of Terraform. Would appreciate it :)

**Comment by apparentlymart** [comment]
Sorry for the long silence here, all!

The situation here has already changed quite a lot since v0.8.8 because we switched to downloading and installing providers separately during `terraform init`. However, we've been using this issue to represent making sure that Terraform is able to produce better error messages when protocol versions mismatch during that automatic installation step.

The recent PRs #19977, #19976, and #19981 have introduced new messages that talk about which available versions are compatible rather than directly about the protocol versions. We will continue to iterate on this in future releases, since the existing installer architecture constrained how much we could change without risky refactoring, but I think what we've done so far is enough to close this out since it is now far more actionable than it was in v0.8.8.

Thanks for reporting this @rtizzy, and sorry for taking so long to address it!
