### ISSUE TITLE
Unable to interate through similarly named variables

### ISSUE THREAD

**Issue by damacus** [hashicorp/terraform#12607]
Hi, 

I have a number of VPCs with a very predictable naming convention dev{01,20}. We currently use maps to pass in `cidr_block` & `pcx-`. However as the map is unsorted, we cannot guarantee ordering between applies. Leading to routing changing, and possibly routes being dropped during the apply stage whilst it removes a route from the table and re-adds it later on. 

A preferable option would be to access the remote state of the connecting account, and iterate the data_sources for the information. 

### Current explicit config Example 1
```HCL
resource "aws_route" "route-to-external-dev01-vpc" {
  route_table_id            = "rtb-123456"
  vpc_peering_connection_id = "${data.terraform_remote_state.dev01.peering_connection_request_id}"
  destination_cidr_block    = "${data.terraform_remote_state.dev01.cidr_block}"
}
```
### With interpolation Example 1
```HCL
resource "aws_route" "route-to-external-vpc" {
  count                     = 20
  route_table_id            = "rtb-123456"
  vpc_peering_connection_id = "${format("data.terraform_remote_state.dev%02d.peering_connection_request_id", count.index + 1)}"
  destination_cidr_block    = "${format("data.terraform_remote_state.dev%02d.cidr_block", count.index + 1)}"
}
```

### Example 2. 
```HCL
variable "foo-01" {
  default = "foo"
}

variable "foo-02" {
  default = "bar"
}
```

```HCL
resource "github_repository" "test" {
  count       = 2
  name        = "${element(var.foo_*, count.index + 1)}"
  description = "I am just a test in counting interpolated variables"
}
```

### Terraform Version
`Terraform v0.8.9-dev (8173c76a782c3c8fc0e3b295cbf344d237602ede)`

### Affected Resource(s)
Please list the resources as a list, for example:
-core 

### Expected Behavior
Format function completes before variable interpolation.

### Actual Behavior
Variable is not interpolated

### Steps to Reproduce
1 . Take any resource 
2 . Add count
3 . Add interpolation that points at a variable or data_source.

**Comment by teamterraform** [comment]
Hi @damacus! Sorry for the long silence here.

We're planning to meet this use-case by implementing the feature discussed in #17179. That will not allow references themselves to be dynamic as you proposed, but will allow you to create one resource instance per entry in your map and have Terraform use the keys from your map to track the individual instances, rather than incrementing integers as it does with `count`.

We're going to close this issue now just to consolidate into #17179, which we're working on the implementation of right now. Thanks for sharing this use case!
