### ISSUE TITLE
Crash in vSphere provider (Network Configuration / Distributed Switch)

### ISSUE THREAD

**Issue by jackprice** [hashicorp/terraform#12627]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
The minimum configuration which produces this error is below (some sections redacted for security).

```hcl
resource "vsphere_virtual_machine" "web" {
  name   = "terraform-web"
  vcpu   = 1
  memory = 1024
  datacenter = "pcc-x-x-x-x"

  network_interface {
    label = "pcc-x-x-x-x/VM Network"
  }

  disk {
    size = 2
    name = "terraform"
    datastore = "pcc-x"
  }
}
```

Where `VM Network` is a Distributed Port Group.

### Debug Output
https://gist.github.com/JackPrice/1105ab0022059c2d178f4bc29085d3d6#file-terraform-log

### Panic Output
https://gist.github.com/JackPrice/1105ab0022059c2d178f4bc29085d3d6#file-crash-log

### Expected Behavior
Terraform creates a VM under vSphere as specified

### Actual Behavior
Terraform crashes.

### Steps to Reproduce
1. Create a configuration file specifying a vSphere Virtual Machine with a network on a Distributed Vitual Switch
1. `terraform apply`

### Important Factoids
We have vSphere 5.5 provided by OVH as a managed resource, so some permissions may be slightly different to expected.

I'm attempting to deploy a VM with a network inside a Distributed Port Group on a DVS.

### References
Not that I know of!

---

Thanks for your time - If I can provide any further information, logs etc. let me know!

**Comment by ewypych** [comment]
Hi Jack!

I've reproduced your problem and it doesn't look like a bug. And not in Terraform for sure. This behaviour appears when you try to set DATACENTER/LABEL. Your code should be made like this:

```HCL
resource "vsphere_virtual_machine" "web" {
  name   = "terraform-web"
  vcpu   = 1
  memory = 1024
  datacenter = "pcc-x-x-x-x"

  network_interface {
    label = "VM Network"
  }

  disk {
    size = 2
    name = "terraform"
    datastore = "pcc-x"
  }
}
```
Label should be set as the name of DPG, without DATACENTER path. 

I've tried to check code of [govmomi mo.go file](https://github.com/vmware/govmomi/blob/master/vim25/mo/mo.go), where you can find DistributedSwitch structures mentioned in your debug logs:

```
panic: reflect.Set: value of type mo.DistributedVirtualSwitch is not assignable to type mo.VmwareDistributedVirtualSwitch
```

but I think I don't have enough Go knowledge. I am not sure if my explanation is a workaround or an expected behaviour, but please try it. I use vDS and standard VS in my infrastructure and everything works properly. Maybe problem is in a lack of vSphere Provider documentation - many variables need a full path, so it can be misleading.

**Comment by tigelane** [comment]
Found this looking for an issue where Terraform wasn't finding the DPG.  Label should be set to the switch name and port group.
Example:  
label = "mySwitchName/myPortGroupName"
