### ISSUE TITLE
Feature request: add the ability to parse and transform time.Durations

### ISSUE THREAD

**Issue by sean-** [hashicorp/terraform#12622]
If you're dealing with the `string` representation of Go's `time.Duration`, it would be very convenient to interact with the value in math expressions.  Ideally it would be possible to do something like:

```
# my_resource.intstance.ttl is a string with the value "60s"
period = "${duration(3 * duration(my_resource.instance.ttl))}"
```

`period` would then be assigned the value `180s` (or whatever is returned from `time.Duration`'s `Stringer` interface).

The current workaround works, but is pretty gross:

```
period = "${3 * replace(my_resource.instancel.ttl, "/[^\\d]+/", "")}${replace(my_resource.instance.ttl, "/[\\d]+/", "")}"
```

It's possible to get the job done now, but safely qualifies as a hack.

**Comment by artburkart** [comment]
Adding a `duration` function is easy, but the syntax parser panics during the interface conversion (from Duration to int) and gives up at the prospect of multiplying a TypeInt with a TypeAny. I don't know if it's possible—within Terraform—to achieve functionality like `3 * 10s` => `30s`, but since there aren't a lot of valid [Duration intervals](https://github.com/golang/go/blob/8a44c8efaefbbda6dd7ab4ee9a5e449fefbf5e1a/src/time/time.go#L632-L639), maybe we could succeed at getting something like `3 * 10s` => `30`. However, I'm not sure if that's of interest.

Perhaps this ticket is more appropriate in the [hil](https://github.com/hashicorp/hil) repo?

**Comment by teamterraform** [comment]
Hi @sean-!

Since this issue was opened, we added [the `timeadd` function](https://www.terraform.io/docs/configuration/functions/timeadd.html) which uses duration syntax in its second argument. Just as with the convention of using RFC 3339 timestamps, this function has established the convention of using duration strings to represent time differences in Terraform, though this need hasn't arisen nearly as much as full timestamps have in provider arguments.

If we find further use-cases for duration-related manipulations, we're intending to support them via additional functions rather than via native language support for durations. For example, if multiplying durations as in the example here were to become a common ask, we might add a function to multiply durations by numbers, though it doesn't seem that that has been a common enough situation to warrant adding that.

We're going to close this one now, in favor of opening more specific issues to propose specific duration-related functions. We're likely to require a particularly compelling use-case to add such functions, since thus far it seems like durations have not appeared very often in provider interfaces. Thanks!
