### ISSUE TITLE
azurerm_container_service.agent_pool_profile is limited to 1

### ISSUE THREAD

**Issue by privatwolke** [hashicorp/terraform#12652]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- azurerm_container_service

### Terraform Configuration Files
```hcl
resource "azurerm_container_service" "kubernetes" {
  name                   = "myacsname"
  location               = "West Europe"
  resource_group_name    = "someresourcegroup"
  orchestration_platform = "Kubernetes"

  master_profile {
    count      = 1
    dns_prefix = "xxxmaster"
  }

  linux_profile {
    admin_username = "xxxx"

    ssh_key {
      key_data = "${file("authorized_keys")}"
    }
  }

  agent_pool_profile {
    name       = "default"
    count      = 2
    dns_prefix = "xxxagent"
    vm_size    = "Standard_F1s"
  }

  agent_pool_profile {
    name       = "default2"
    count      = 2
    dns_prefix = "xxxagent2"
    vm_size    = "Standard_A0"
  }

  service_principal {
    client_id     = "xxx"
    client_secret = "xxx"
  }

  diagnostics_profile {
    enabled = false
  }
}
```

### Output
azurerm_container_service.kubernetes: agent_pool_profile: attribute supports 1 item maximum, config has 2 declared

### Expected Behavior
Multiple agent pool profiles should be supported.

### Actual Behavior
Multiple agent pool profiles don't seem to be supported.

### Steps to Reproduce
1. `terraform plan`

### References
- https://serverfault.com/questions/837906/does-azure-support-multiple-agent-profiles-for-kubernetes-with-container-service

**Comment by pmcatominey** [comment]
Hi @privatwolke,

The error message is due to a validation in the schema for that resource [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_container_service.go#L106). The answers on the ServerFault thread seem to suggest that multiple agent pool profiles aren't supported yet by the ARM API.

Have you been able to create multiple agent pool profiles outside of Terraform?
