### ISSUE TITLE
Elasticsearch provider

### ISSUE THREAD

**Issue by protomouse** [hashicorp/terraform#12651]
It would be very useful if Terraform could manage Elasticsearch resources, such as indices, index templates, search templates, etc. I've started prototyping an implementation that covers my current needs, which are limited to index templates. Opening this issue to track API, work, feedback, etc.

I'm currently targeting Elasticsearch 5 and up.

**Index templates**

```hcl
resource "elasticsearch_index_template" "test" {
  name = "terraform-test"
  template = "tf-*"
  order = 1

  settings {
    index.number_of_shards = 5
  }

  mapping {
    type = "reports"

    date_property {
      name = "created_at"
      format = "EEE MMM dd HH:mm:ss Z YYYY"
    }

    keyword_property {
      name = "subject"
    }
  }
}
```

API reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

PUT _template/terraform-test
```json
{
  "template": "tf-*",
  "order": 1,
  "settings": {
    "index.number_of_shards": 5
  },
  "mappings": {
    "reports": {
      "properties": {
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        },
        "subject": {
          "type": "keyword"
        }
      }
    }
  }
}
```

**Comment by stack72** [comment]
Hi 

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune these type of issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

**Comment by synhershko** [comment]
For anyone looking for an Elasticsearch provider (for snapshot repositories and index templates) there is a nice and useful implementation here: https://github.com/phillbaker/terraform-provider-elasticsearch
