### ISSUE TITLE
bug report: 0.4.0 Cycle error when no cycle exists

### ISSUE THREAD

**Issue by ctro** [hashicorp/terraform#1265]
I'm running terraform off of the master branch (Terraform v0.4.0-dev (d3135c1b2bac4c6b6f1934b18ec58dd2f0ef1110+CHANGES))
When I `terraform plan` the following script I get a Cycle Error, but I don't see a cycle.

```
# Switchboard DNS format convention:
#  public_ip=1.2.3.4 => sb-1-2-3-4
resource "aws_route53_record" "switchboard" {
  count = 2

  zone_id = "SOME ZONE ID"
  name = "sb-${replace(element(aws_instance.switchboard.*.public_ip, count.index), ".", "-")}"
  type = "A"
  ttl = "300"
  records = ["${element(aws_instance.switchboard.*.public_ip, count.index)}"]
}

###
# Switchboard
###
resource "aws_instance" "switchboard" {
  ami = "blerg"
  instance_type = "t2.micro"

  count = 2

  lifecycle = {
    create_before_destroy = true
  }

  provisioner "remote-exec" {
    inline = [
    "echo ${aws_instance.consul_server.0.private_ip} | sudo tee /etc/CONSUL_IP"
    ]
  }

}

###
# Consul Servers
###
resource "aws_instance" "consul_server" {
  ami = "blah"
  instance_type = "t2.micro"

  count = 3
}
```

The error that I receive is

```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* Cycle: aws_route53_record.switchboard, aws_instance.switchboard, aws_instance.switchboard (destroy), aws_instance.consul_server (destroy), aws_instance.consul_server
```

**Comment by rvangundy** [comment]
@ctro, did you find a workaround for this? I'm encountering the same issue. It seems like it's something that could be resolved by rearranging dependencies or setting some depends_on flags? Would be nice to use the 0.4.0 features as currently I'm swapping between terraform versions for certain tasks.

**Comment by rvangundy** [comment]
@ctro, I'm beginning to understand the complications involved here, and finding that there may be a sort of workaround in 0.4.0 by using the --target option for destroying/creating resources. While I don't see any dependency issues in your configuration, there are still some interdependencies. You can get a better picture of this by running "terraform plan" followed by "terraform graph". Take that output and put it in to http://graphviz-dev.appspot.com/ to see a visualization of your infrastructure.

Using this, try individually creating or destroying resources (may need to temporarily downgrade terraform to create your initial infrastructure) using the --target option and see what happens. You might find there's an order-of-operations that works for you. Whether this can provide a fix, I think it will shed some light on what the specific dependency issues are. I'm going to post my findings here.

My guess is this also relates to an issue I was previously having, where "terraform destroy" doesn't successfully destroy VPCs and security groups due to instances still being dependent on them.

**Comment by phinze** [comment]
Hey folks, thanks for the report, and sorry for the trouble here.

It is indeed possible to express some difficult-to-grok cycles when using `create_before_destroy` on resources with non-CBD dependencies. 

In your example, @ctro, here's what the dependency graph ends up looking like:

![output](https://cloud.githubusercontent.com/assets/37534/7071383/87759e86-deaa-11e4-9394-d9d233fc9982.png)

It's a bit noisy, but here it is with the cycle highlighted:

![output](https://cloud.githubusercontent.com/assets/37534/7071484/401f6aa2-deab-11e4-95a5-59216eefc1cd.png)

This points us to the solution, which is to add `create_before_destroy` to the `consul_server` since a CBD resource depends on it.

Doing that yields a successful plan and a much happier looking graph:

![output](https://cloud.githubusercontent.com/assets/37534/7071619/0b2742ec-deac-11e4-8bfa-812de027cdd3.png)

**Comment by rvangundy** [comment]
@phinze, how did you manage to get the dependency graph to include the (destroy), etc. indicators? Here's a graph of what's giving me a cycle error, and I can't seem to see the same results in my graph...

![graph_0 4 0](https://cloud.githubusercontent.com/assets/1909616/7071761/819930c6-deb5-11e4-940b-859c15f1ea86.png)

**Comment by rvangundy** [comment]
I've attached an easier-to-read output of my dependency graph. This is definitely related to the create_before_destroy flag. If I add this to my aws_instance.inbox-test, I get the cycle error. If a state & infrastructure already exist, it's just performing an update, and everything seems to work fine. But running this initially with no previous state throws the cycle error. So for now, I have to leave this out, create my infrastructure, then put it back in.

Probably one way to work around this in terraform is to ignore this flag under certain conditions, particularly when no previous state/infrastructure exists.

![graph_0 4 1](https://cloud.githubusercontent.com/assets/1909616/7076369/e2551eb8-ded6-11e4-847f-b0e69ee78eb6.png)

**Comment by arubis** [comment]
I found that, similarly, `create_before_destroy` created a cyclic dependency error where there shouldn't have been one between a `aws_instance` and an `aws_security_group` that was included in the instance's `security_groups` block.

**Comment by phinze** [comment]
>  how did you manage to get the dependency graph to include the (destroy), etc. indicators? 

@rvangundy it's behavior that I'd like to bake into core at some point, but for now it's a bit of a manual process

(1) Run `TF_LOG=1 terraform plan`

(2) Find the point in the output after the final graph transformation. Currently that's just after this line:

> Graph after step *terraform.TransitiveReductionTransformer

(3) Copy the plaintext graph output

(4) Pipe it through this [janky little ruby script I wrote](https://github.com/phinze/terragraph) and into Graphviz:

```
pbpaste | ~/src/terragraph/terragraph | dot -Tpng > output.png; open output.png
```

**Comment by ctro** [comment]
@phinze I've been away for a while, it's so nice to come back to this thoughtful explanation.  This works, and is of course sorta obvious in hindsight :)

 Thank You.
