### ISSUE TITLE
provider/aws aws_elasticache_cluster: cache_nodes list behaves strangely

### ISSUE THREAD

**Issue by tothandras** [hashicorp/terraform#12878]
### Terraform Version

`Terraform v0.9.1`

### Affected Resource(s)

- provider/aws:
  - aws_elasticache_cluster

### Terraform Configuration Files

The relevant parts:
```hcl
# this works:
output "nodes" {
  value = ["${format("%s:%s", aws_elasticache_cluster.redis.cache_nodes.0.address, aws_elasticache_cluster.redis.cache_nodes.0.port)}"]
}

# this doesn't:
# output "nodes" {
#  value = ["${formatlist("%s:%s", aws_elasticache_cluster.redis.cache_nodes.*.address, aws_elasticache_cluster.redis.cache_nodes.*.port)}"]
# }
```

Also:

```hcl
At column 3, line 1: element: argument 1 should be type list, got type string in:

${element(aws_elasticache_cluster.redis.cache_nodes.*.port, count.index)}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tothandras** [comment]
@grubernaut I'd like to contribute with a PR by fixing this bug. Can you help me where I should look for the root issue? Could it come from the [resource](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elasticache_cluster.go#L185) itself or somewhere else?

**Comment by joelhandwell** [comment]
@mitchellh Related with https://github.com/hashicorp/terraform/pull/10657 ?

**Comment by teamterraform** [comment]
Hi @tothandras! Sorry for the long silence here.

This looks like a symptom of a known limitation in Terraform 0.11 and earlier where any list containing an unknown value would itself become an unknown value and no longer be accepted as a list by the type checker.

Terraform 0.12 has addressed that by improving the representation of unknown values so that a list can contain a mixture of known and unknown elements and so that unknown values still track type information.

The handling of these language features was completely rewritten for Terraform 0.12, so if anyone is still seeing problems related to these features we'd ask that you open a new issue so we can capture (via the issue template) information about the bug as it relates to the new implementation. Thanks for reporting this, and sorry again it took so long to respond to it.
