### ISSUE TITLE
Add `secret` flag to variables

### ISSUE THREAD

**Issue by tarrant** [hashicorp/terraform#1288]
Terraform allows you to prompt a user for info, like a password. It would be convenient if you could mark the field as a secret, such that the key was not encoded into the state and had to be reentered every time terraform ran.

**Comment by radeksimko** [comment]
Related issue: https://github.com/hashicorp/terraform/issues/516

**Comment by mitchellh** [comment]
I'd say this is close enough to a dup to #516.

**Comment by gserra-olx** [comment]
@tarrant @radeksimko I disagree on this being a duplicate of #516, as that is covering stored secrets

I want to input a password, and I don't want it to be echoed on screen

**Comment by inequity** [comment]
@mitchellh 
I agree with @gserra-olx . For providers that don't support any sort of key based authentication (vSphere, Artifactory backend are the ones I'm familiar with) it's pretty reasonable to want to prompt for a password instead of storing it on disk, and not having it echoed to screen is fairly important.

**Comment by jbroq** [comment]
Same here : credentials prompting and hiding the input password, thanks ;)
