### ISSUE TITLE
Openstack: No warning that adding additional volumes detaches existing volumes

### ISSUE THREAD

**Issue by carlpett** [hashicorp/terraform#12923]
When running `plan` on adding a new volume to a running instance, the output does not indicate that the operation can be destructive. Here is some plan output:

```
openstack_compute_instance_v2.my-instance: Modifying...
  volume.#:                    "1" => "2"
  volume.352688767.volume_id:  "72080762-d836-44e9-a494-670d46bb8be1" => "72080762-d836-44e9-a494-670d46bb8be1"
  volume.3620689714.device:    "" => "<computed>"
  volume.3620689714.id:        "" => "<computed>"
  volume.3620689714.volume_id: "" => "b4aed69c-d751-4d3c-8734-135780105bb3"
```

I would have expected this to be a no-op for the first volume, where it doesn't list any actual change. However, `apply` then detaches the volumes from the host, and then reattaches them. This can be very bad (for instance, when adding more disks to a database cluster). Also noteworthy is that at least on my Centos machines, this causes new /dev names, so if your fstab references those directly, they will no longer be valid (we did reference by /dev/disk/by-id, thankfully).

The relevant code seems to be [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_compute_instance_v2.go#L760). Does it actually need to detach the volumes, or is it something that is done to reduce risk of inconsistency?

If it needs to do the detachment, a better warning would be nice.

### Affected Resource(s)
- openstack_compute_instance_v2
- openstack_blockstorage_volume_v2

### Terraform Configuration Files
Before

```hcl
resource "openstack_compute_instance_v2" "my-instance" {
  name = "i-123"
  image_name = "centos-7-1605"
  flavor_name = "m1.large"

  volume {
    volume_id = "${openstack_blockstorage_volume_v2.vol-1}"
  }
}
```

After

```hcl
resource "openstack_compute_instance_v2" "my-instance" {
  name = "i-123"
  image_name = "centos-7-1605"
  flavor_name = "m1.large"

  volume {
    volume_id = "${openstack_blockstorage_volume_v2.vol-1}"
  }
  volume {
    volume_id = "${openstack_blockstorage_volume_v2.vol-2}"
  }
}
```

**Comment by jtopjian** [comment]
@carlpett Thanks for reporting this.

Yeah, it looks like the detachment should only be happening for `volume` entries that were removed, not all of them.

In general, using the `openstack_compute_volume_attach_v2` resource is an all-around better way of handling volume attachments, rather than the `volume` parameter in `openstack_compute_instance_v2`. In fact, I have been planning on deprecating the `volume` parameter for a few months now --  I've just wanted to make sure `openstack_compute_volume_attach_v2` is working correctly first.

Can you try using `openstack_compute_volume_attach_v2` for your attachments and let me know how it works out?

**Comment by carlpett** [comment]
I did try `openstack_compute_volume_attach_v2` first, because it seemed better, but "something" failed. I seem to have closed down the tab where I ran it, so I lost the history. I'll see if I can recreate it (not on the database cluster, though...)

**Comment by carlpett** [comment]
I'm unable to replicate any problems with using the volume_attach resource, so I'm willing to put that one down to some sort of user error on my part.

**Comment by jtopjian** [comment]
@carlpett Thanks for trying that out! A patch has just been merged to officially deprecate the `volume` attribute. Since `openstack_compute_volume_attach_v2` is the recommended best way for attaching volumes, I'm going to close this issue, but please let me know if you have any other questions or comments.
