### ISSUE TITLE
Feature Request: "Better" terraform plan output

### ISSUE THREAD

**Issue by manojlds** [hashicorp/terraform#12957]
Came across this - 
https://github.com/coinbase/terraform-landscape

It would be nice if this kind of output was an option or even default within terraform.

**Comment by apparentlymart** [comment]
Hi @manojlds! Sorry for the long silence here... we missed this issue when posting updates because it was labelled in an old labeling scheme and so didn't come up in our searches.

The good news is we've been working on this over in #15180, and that change is now in master ready to be included in the forthcoming v0.12.0 release. I posted some examples in a comment on that issue.

Thanks for requesting this, and sorry again for the late response.
