### ISSUE TITLE
Support for gcp Folders & XPN

### ISSUE THREAD

**Issue by joe-boyce** [hashicorp/terraform#12975]
Hi,

Are you planning on supporting creation of Google Cloud Folders & XPN resources within Terraform soon?

Thanks in advance,

Joe

**Comment by danawillow** [comment]
Hi @joe-boyce, since the folders API is in alpha we can't add support quite yet but it's on our radar. However, XPN should already be working. Are you having issues getting it to work? Here's a test case that shows what an XPN config would look like: https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance_test.go#L1247

**Comment by joe-boyce** [comment]
Great to hear you are already aware of folders in gcp and will no doubt roll out functionality when they are in general release

I wasn't aware of the XPN functionality already in terraform as it wasn't in the docs (more than likely due to XPN not being in general release as well i assume), many thanks for pointing me to the example and if I have any problems I will open a case

Thanks again,

Joe

**Comment by danawillow** [comment]
Is there somewhere in the docs you'd expect to see it? Since it doesn't require a full resource, it didn't make sense at the time to have it on its own resource page. The only field that has to change to enable XPN is subnetwork_project, which is documented [here](https://www.terraform.io/docs/providers/google/r/compute_instance.html#subnetwork_project). I guess I could mention XPN in that field- is that what you meant? I'd love to know where you expected it to be so other people don't assume terraform doesn't support it yet.

**Comment by joe-boyce** [comment]
As you said maybe just a mention of it in the relevant gcp resources where it could potentially be referenced

Thanks,

Joe

**Comment by xcalibre0** [comment]
Well, let's assume i dont want to learn whatever programming language you are using in your use case.

That being the case I dont know how you set up your google provider.  Is the project for the provider the xpn parent project or the xpn child project?  Where is the service account? In the child project or the parent?

The documentation makes it sound like that the subnetwork_project field is the name of the xpn parent project, but its definitely not clear.

**Comment by danawillow** [comment]
Hi @xcalibre0, I'm sorry I don't quite understand what you mean by the first sentence you wrote.

For the rest, the project for the provider would be the child project. The network/subnet lives in the host project, but everything else (I believe) should be the child project. You'll also need to already have XPN enabled for this to work.

**Comment by skanchin1** [comment]
Hi, How to address the below error:

"Required 'compute.organizations.enableXpnResource' permission for projects/project-id '

So far could not come across the enableXpnResource permission against the XPN Host project to enable it (so that a service project can leverage the XPN host project ...)

Thanks,
Sharma

**Comment by danawillow** [comment]
Hey @skanchin1, you'll need an organization admin to set the `roles/compute.xpnAdmin` permission on the organization itself. This can be done at https://console.cloud.google.com/iam-admin/iam/organization?authuser=1&organizationId={YOUR_ORG_ID}. Alternatively, you can create a [custom role](https://cloud.google.com/iam/docs/creating-custom-roles) with the specific `compute.organizations.enableXpnResource` permission. Hope that helps!
