### ISSUE TITLE
DigitalOcean: resize droplet disk while preserving current CPU and RAM

### ISSUE THREAD

**Issue by skovorodkin** [hashicorp/terraform#13007]
### Terraform Version
v0.9.1

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files

```hcl
provider "digitalocean" {
  token = "TOKEN"
}
resource "digitalocean_droplet" "droplet-01" {
  image = "ubuntu-16-04-x64"
  name = "droplet-01"
  region = "nyc3"
  resize_disk = false
  size = "512mb"
}
```

### Expected Behavior
Droplet disk should be resized.

### Actual Behavior
State is updated, but disk stays the same.

### Steps to Reproduce

1. Create a droplet: `terraform apply`.
2. Resize only CPU and RAM: change config to `size = "1gb"` and run `terraform apply`.
3. Try to resize disk: change config to `resize_disk = true` and run `terraform apply`.

### Related Issues and PRs

- GH-9402
- GH-9573

**Comment by stack72** [comment]
Hi @skovorodkin 

Thanks for opening the issue here - apologies this isn't working as expected for you. From what I can gather, you have performed the following:

* created a droplet
* changed the size to 1gb but said not to resize the disk at the same time
* then decided that you wanted to resize the disk

Is this correct?

Paul

**Comment by skovorodkin** [comment]
Hi @stack72 

Yes, it's correct.

I've made a pull request (#13059) with a fix.
