### ISSUE TITLE
Same prevent_destroy option for RDS is not available in AWS cli/Console

### ISSUE THREAD

**Issue by SydOps** [hashicorp/terraform#13031]
Hi there,

### Terraform Version
0.9.1

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "main" {
  ...
  lifecycle {
    prevent_destroy = true
  }
}
```
### Debug Output
run `terraform plan` and `terraform destroy`, get same error.
```
Error running plan: 1 error(s) occurred:

* module.db.aws_db_instance.main: aws_db_instance.main: the plan would destroy this resource, but it currently has lifecycle.prevent_destroy set to true. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or adjust the scope of the plan using the -target flag.
```

### Panic Output
As above.

### Expected Behavior
That's the right error message in fact. But when I try to manually disable lifecycle option `prevent_destroy` in aws cli or console, I can't find the similar options. 

### Actual Behavior
I have to manually delete the database directly from aws console. 

### Steps to Reproduce
detail above. 

### Important Factoids
This is a special request. I applied the codes to create DB instance,  modified the terraform codes, and terraform plan/apply, it will change DB instance on purpose. 

But the problem is, I don't want to `terraform apply` the change with lifecycle prevent_destroy to `false` first, because my codes are not ready to apply.

Normally I face this situation, I can manually disable the prevent destroy option, similar as EC2 prevent terminate option. 

But I can't find the same option in RDS DB instance. 

>So the question is should we create a new option for AWS but it is not available in aws cli/console.

**Comment by sethvargo** [comment]
Hey @SydOps 

Thank you for opening an issue, and I'm sorry this is causing you problems. As you discovered, `prevent_destroy` is not part of AWS; it is one of many [lifecycle hooks](https://www.terraform.io/docs/configuration/resources.html#lifecycle) in Terraform. Other examples include `create_before_destroy` and `ignore_changes`. These arguments are not specific to a provider (like aws or azure), but affect the way Terraform interacts with those providers internally. 

`prevent_destroy` is something that happens at the Terraform layer. Just like `variable` and `output`, `prevent_destroy` is not a function of AWS (or any other provider). It's a _built-in_. Because of this, there's no associated API call you can use.

Since you have other changes, I would recommend using your source control management system to save/stash your current changes and then make the single-line change of removing the `prevent_destroy` option. If you're using git, there are many visual tools like gitx and tower which make it easy to do per-line commits.
