### ISSUE TITLE
Documented syntax feature gives parsing error

### ISSUE THREAD

**Issue by amanjeev** [hashicorp/terraform#13055]
Hello terraform devs:

We are currently seeing that the documentation on the [page for syntax](https://www.terraform.io/docs/configuration/syntax.html) does not conform to the behavior. The answers to the questions are below.

### Terraform Version

`Terraform v0.8.7`

### Terraform Configuration Files
All you need in a file is this syntax -
```hcl
variable = [{
  "ami": {
    "description": "the AMI to use",
  }
}]
```

### Expected Behavior
It should not complain, that is, throw no parsing error and create the variable as it would with the normal syntax.

### Actual Behavior
`Error loading config: Error parsing /a/b/c/bugreport/root.tf: At 2:8: illegal char`

### Steps to Reproduce
1. Create a file called `root.tf`
2. Use (paste) the variable syntax mention on the [documentation page](https://www.terraform.io/docs/configuration/syntax.html) and save
```hcl
variable = [{
  "ami": {
    "description": "the AMI to use",
  }
}]
``` 
3. Run `terraform plan`

### Notes and reason

The reason we need that syntax is because we need to be able to set a whole bunch of static Consul keys using terraform. Instead of having a large number of repeated `key` sections in the `resource` `consul_keys`, we want to be able to set them outside, like using `external` data source and set them once in an array as the documentation claims we can. 

The documentation says that `variable` and `resource` allow a syntax as said above. I tried using the similar syntax for `resource` but that does not work either.  In fact, another request is that if you could update the documentation to show how `resource` section would be used. For example, I tried 

```hcl
resource = [{
    consul_keys = [{
        "myconsulkeys" = {
          key = [
           # planning to repeat this outside using external data source 
           # and set once but not sure if this is feasible or correct.
            {
              path = "path/to/consul/key"
              value = "my awesome value"
            }
          ]
        }
      }]
  }]
```

**Comment by apparentlymart** [comment]
Hi @amanjeev! Sorry for the long silence here.

The documentation you were referring to is now updated for Terraform v0.12 syntax, but I can see the example you were talking about in [the archived Terraform v0.11 documentation](https://www.terraform.io/docs/configuration-0-11/syntax.html#terraform-syntax).

That example was, as far as I can tell, never correct. The old parser did allow for some quite unusual combinations of lists and blocks, but that particular one could not have worked because Terraform expected the variable name or resource type and name to appear in the header with the block.

The example no longer exists in the Terraform 0.12 documentation and no such syntax is available in Terraform 0.12. The way to achieve your intended goal of generating multiple `key` blocks from a variable in Terraform 0.12 is to use a [`dynamic` block](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks):

```hcl
resource "consul_keys" "example" {
  dynamic "key" {
    for_each = var.any_map
    content {
      path  = "prefix/${key.key}"
      value = key.value
    }
  }
}
```

Although in this particular case, you could alternatively use [the `consul_key_prefix` resource type](https://www.terraform.io/docs/providers/consul/r/key_prefix.html) that I think was added to the provider after this issue was already open:

```hcl
resource "consul_key_prefix" "example" {
  path_prefix = "prefix/"
  subkeys     = var.any_map
}
```
