### ISSUE TITLE
aws_alb_target_group can`t recreate with attached listeners

### ISSUE THREAD

**Issue by AlexShuraits** [hashicorp/terraform#13076]
Hi there,

I have change the port for aws_alb_target_group, that forces new resource.
Than while trying to delete the target group. I get following error:

`
Error deleting Target Group: ResourceInUse: Target group 'xxxx' is currently in use by a listener or a rule
        status code: 400, request id: 747913f1-1213-11e7-916c-3f605d5e091b
`

So, I assume that it should delete the listener first. That's what I've done manually to resolve the problem.

### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
- aws_alb_target_group
- aws_alb_listener_rule

**Comment by desponda** [comment]
I ran into this problem as well, what should be happening is on destroy, the listener needs to be destroyed before the target group,Alex is correct

**Comment by nwhite-sf** [comment]
Running into this with v0.9.4 as well.

**Comment by mancej** [comment]
Running into this with v0.9.5

**Comment by nmarchini** [comment]
Running into this with v0.9.6

**Comment by jox** [comment]
Running into this with v0.11.4.

Manually deleting the listener can not be the solution.

**Comment by frenchie4111** [comment]
I solved this by renaming my listener resources. (Also not an ideal solution)

**Comment by knope** [comment]
:(  make the hurt stop

**Comment by mildwonkey** [comment]
Hi all,

This issue has been moved to the [aws provider repository](https://github.com/terraform-providers/terraform-provider-aws), and any conversation should continue in the [new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/636).

Since comments (and reactions) on this issue are generating notifications to subscribers, I am going to lock it and encourage you to view the [moved issue](https://github.com/terraform-providers/terraform-provider-aws/issues/636).

Please continue to open new issues here for any other Terraform Core problems that you come across, and thanks!
