### ISSUE TITLE
Want to destroy disk but the whole instance was gone

### ISSUE THREAD

**Issue by snowsky** [hashicorp/terraform#13070]
Coming from #12859 
### Terraform Version
Terraform v0.9.2-dev (bbc6ea6f6cc9584b3a4a4283fc2371bb3ebe4db9+CHANGES)

### Affected Resource(s)
Google GCE instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
see #12859
```

### Expected Behavior
The instance should not have been destroyed

### Actual Behavior
```
@Howa ➜  tmp rbenv:(2.3.1) git:(init_doc) ✗ ../bin/terraform destroy -target google_compute_disk.blog
Do you really want to destroy?
  Terraform will delete the following infrastructure:
  	google_compute_disk.blog
  There is no undo. Only 'yes' will be accepted to confirm

  Enter a value: yes

google_compute_disk.blog: Refreshing state... (ID: blog)
google_compute_instance.blog: Destroying... (ID: blog)
google_compute_instance.blog: Still destroying... (ID: blog, 10s elapsed)
google_compute_instance.blog: Destruction complete
google_compute_disk.blog: Destroying... (ID: blog)
google_compute_disk.blog: Destruction complete
```

**Comment by snowsky** [comment]
Deleting the disk triggered the function resourceComputeInstanceDelete.

**Comment by snowsky** [comment]
@tombuildsstuff it seems it is a core bug

**Comment by danawillow** [comment]
Hey @snowsky, does the compute instance in your config file reference the disk? If so, then I would expect deleting the disk to delete the instance since otherwise terraform wouldn't know what to fill in the config for the disk once it's gone. If not, can you provide a configuration file that explains the issue you're having?

**Comment by danawillow** [comment]
Also note that this behavior is documented at https://www.terraform.io/docs/commands/destroy.html:
`The -target flag, instead of affecting "dependencies" will instead also destroy any resources that depend on the target(s) specified.`

**Comment by snowsky** [comment]
Yes, I saw the document. Would this be reversed? Like if the user destroyed an instance, all the dependencies on the instance should be destroyed, instead of the user trying to destroy a disk, Terraform destroyed the whole instance.

**Comment by danawillow** [comment]
I'm not quite following your logic. Let's say you have a config that looks like this (this is very obviously contrived and are not real names of things):
```
instance1:
- disk_name: {disk.name}

instance2:
- disk_name: {disk.name}

disk:
- name: foo
```

If disk is destroyed, then instance1 would be very confused when trying to run plan, because it knows it has to fill in something for disk_name, but the resource it's referring to is gone. Because it can't do anything regarding the instance, it's deleted.

However, if instance1 was destroyed, then disk shouldn't be destroyed because instance2 is still using it.

IMO, unless you have a strong reason to be using `destroy -target`, just make your config file be the setup you want to see. So if you want to delete the disk, just remove it from the config (and update the reference to it accordingly).

**Comment by snowsky** [comment]
maybe a message asking users if deleting the whole instance would be better?

**Comment by danawillow** [comment]
Hmm, the difficulty of that approach is that it's not something specific to a GCP instance, but any resources that have a dependency on each other. Rather than adding it into just one resource type (and then having inconsistent behavior between resources), this is a feature request better suited for terraform core. It seems like the real bug here is that when it said `Terraform will delete the following infrastructure:` it should have included the instance as well as the disk. Does that sound right? If so, want to file a new issue against terraform core for that?

**Comment by snowsky** [comment]
That makes sense. I went through the codes and it is Core related issue instead of GCP. I'll create the other issue for follow-up. Thanks @danawillow .

**Comment by apparentlymart** [comment]
Agrees with @danawillow that this error message is misleading and worth fixing. It would be great to have a core issue for that!
