### ISSUE TITLE
Problems with windows line endings when using remote-exec

### ISSUE THREAD

**Issue by shorn** [hashicorp/terraform#1310]
I'm running Terraform 0.3.7 from Windows 8.1, to create resources on AWS.
When I try to use remote-exec with a script attribute, or in combination with a file provisioner, the windows line endings are ending up on the linux ec2 instance and causing the script not to execute properly.

This is my current workaround:

    provisioner "file" {
      source = "${path.module}/provision-resource.sh"
      destination = "/home/ec2-user/provision-resource.sh"
    }
    provisioner "remote-exec" {
      inline = [
        "tr -d '\015' < provision-resource.sh > provision-resource-converted.sh",
        "chmod +x provision-resource-converted.sh",
        "sudo provision-resource-converted.sh"
      ]
    }

Another workaround is to use `user_data = "${file(\"provision-resource.sh\")}"`, which seems not to care about the windows line endings for some reason.

**Comment by phinze** [comment]
Going through and reviewing some old issues here. I believe the behavior is still as described, but I'm not sure it's worth us trying to handle this scenario specifically. Terraform has no knowledge of the guest operating system, which is what would be required to implicitly convert line endings. So we'd be left with a config option, which seems like it would have limited value over either (a) doing something like what you're doing here, or (b) just storing scripts destined for unix machines w/ unix line endings.

I'm going to close this for now since I'm doing a sweep of old issues, but feel free to make a case for a core feature here. If you believe there's a feature to be had - can you sketch out what the config option would be and how it might work?
