### ISSUE TITLE
AWS ELB Access Logs create location

### ISSUE THREAD

**Issue by JasonSilva-CTP** [hashicorp/terraform#13127]
I would like the feature / capability for the Access log location of the ELB to be created if it isn't there.

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#enable-access-logs-console

This feature of the AWS console is under bullet 5D in the above mentioned URL.

**Comment by stack72** [comment]
Hi @JasonSilva-CTP 

Thanks for the feature request here. We try to keep Terraform's internals as simple as we can, and its operations clearly visible to the user. Since it's possible to accomplish this by explicitly creating the S3 bucket and using its reference in the ELB resource, we prefer not to add implicit actions under the hood.

Thanks

Paul
