### ISSUE TITLE
Terraform fmt expects only a single variable following a comment

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform#13155]
### Terraform Version
v0.9.2

### Terraform Configuration Files
```hcl
# Global Variables
variable "account_number" {}
variable "active_region" {}
variable "aws_region" {}
variable "env_name" {}
```

### Expected Behavior
`terraform fmt` should be happy with this code block.

### Actual Behavior
`terraform fmt` resulted in the following:
```hcl
# Overall
variable "account_number" {}

variable "active_region" {}
variable "aws_region" {}
variable "env_name" {}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add a single-line comment to the top of a block of similar variables
2. `terraform fmt`

**Comment by tombuildsstuff** [comment]
Hi @jaygorrell 

Tracing through the code for `terraform fmt` - it appears the formatting is handled within the [HCL Repository](https://github.com/hashicorp/hcl), where [I've opened an issue](https://github.com/hashicorp/hcl/issues/191) about this :)

Thanks!

**Comment by jaygorrell** [comment]
Great, following it over there as well, then - thanks!

**Comment by mildwonkey** [comment]
This was fixed upstream and working as expected in Terraform 0.12 - thanks!

Note that the hcl issue is not closed yet because the fix is in [HCL2](https://github.com/hashicorp/hcl2) - eventually we will merge the repositories, at which point [#191](https://github.com/hashicorp/hcl/issues/191) can be closed.
