### ISSUE TITLE
Detect mismatching AWS AZ and subnet at plan time

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#13185]
How to reproduce:

- Create an `aws_subnet` with the availability zone `us-east-1b`
- Create an `aws_instance`, specify the subnet *and* specify the availability zone as something other than `us-east-1b` (eg. `us-east-1c`)

The instance creation will error:

```
* aws_instance.test_01: Error launching source instance: InvalidParameterValue: Value (us-east-1c) for parameter availabilityZone is invalid. Subnet 'subnet-aff9fe92' is in the availability zone us-east-1b
status code: 400
```

This can be caught at plan time; ideally by checking that the AZ and subnet AZ match, or by making AZ and subnet mutually exclusive.

**Comment by grubernaut** [comment]
Hey @jleclanche, thanks for the issue!

Unfortunately, we cannot catch this at plan time because we cannot yet validate multiple schema values at the same time during plan time. (I believe we've discussed this numerous times in the past 😄)

I'm definitely in favor of improving our plan-time validation, and think it has significant benefits for our users. However, it's currently not possible without some core changes and improvements. We can validate this for you at apply time, but I don't believe, after having spoken with you on this issue before, that it will fully solve the request here. 

So, once again, I'm truly sorry we cannot add this enhancement yet at this time, but will keep the issue open for when we can improve plan-time validation to include more than one schema item. ❤️

**Comment by jleclanche** [comment]
@grubernaut Yeah I remember now, I filed another plan time validation issue (IIRC something to do with cloudflare). Maybe dedicate a label to this?

**Comment by grubernaut** [comment]
@jleclanche yeah it was validating cloudflare record types based on the `proxy` field IIRC. It's a well known core issue, however it's also one that requires a lot of modifications in core to be able to expose these fields during validation time. I've been conversing with core members of the team internally as well, but we'll need to add it to the roadmap as a must-fix to get some traction. Perhaps @apparentlymart wants to dive into this one? 😉 
@apparentlymart, this is a benefit of fully solving #4348, happy to discuss internally as well. There are several other issues that would benefit from this change as well.

**Comment by apparentlymart** [comment]
This sort of "resource-wide" validate is one of the use-cases of what I proposed in #8769. I've not looked at that for a while, but agreed that this (along with several other similar issues) are a good motivator to spend some more time on that.
