### ISSUE TITLE
data source for referencing common contextual configuration variables

### ISSUE THREAD

**Issue by aebaugh** [hashicorp/terraform#13193]
After using terraform fairly extensively for AWS infrastructure management, it is apparent we have a need to reference a number of predefined ARNs or IDs for a given context that could possibly be managed outside of terraform. Some examples:
- current EC2 AMI ID to use based on account and region
- wildcard SSL cert ARN for an environment based on account, (customer-defined) environment, and region (for use in ELBs)
- preferred availability zone based on account and region
It's possible these could all above resources could be in terraform and remotely referenced, but often the values are managed by a separate team.

To deal with this we have built a "default variables" module that can pull the necessary values based on an interpolated lookup, like a map of needed keys to values, such as:
currentAmi = ${lookup(module.defaultVars.ecs_amis, format("%s.%s", var.aws_account_alias, var.aws_region))}

This works pretty well and allows the module and associated values to be managed in source control. But it is also means all of the outputs of the referenced "defaultVars" module are present in every terraform state file that references the module. Not terrible, but not great as it means a lot of copies of config data that may change.

So wondering 1) are we doing it wrong? 2) Could we define a map-like data source specifically for looking up pre-defined config values such as this?

**Comment by apparentlymart** [comment]
Hi @aebaugh! Some good questions here!

It sounds like you're concerned about those copies of the configuration data getting stale in the state. If so, don't worry: Terraform will refresh those at the appropriate time on each apply. Honestly the cached copies of that data in the state are not actually used for much, but rather they end up stored as a side-effect of the mechanism that allows the *root* module to export its outputs to other configurations using `terraform_remote_state`.

With that said, data sources are another way to get the job done here. Data sources are generally used to *avoid* putting a certain change in version control because e.g. it's something that changes independently of the current config. A common pattern, for example, is to use the `aws_ami` data source to retrieve the latest AMI matching a tag, assuming that there's some separate build process that produces new AMIs to use and tags them once they've been tested. For changes that you specifically *do* want to include in your code repository, a module with just some outputs in it is a fine approach.

Note that data source results are also cached in the state, but again Terraform will refresh them on each run, unless the user specifically overrides that using `-refresh=false`. Again this is primarily for internal reasons: Terraform needs to retain the last result *in case* the user runs with `-refresh=false`; otherwise it is immediately discarded during refreshing and replaced with the latest result.

I hope this answers your question. If you have follow-up questions it's often better to ask them via the gitter chat or mailing list (both linked from the community section of the website) since it's hard to keep track of long threads on github and there are more people to help in those forums. I'm going to close this issue just because we try to keep the issue queue reserved for bug and feature requests rather than questions.
