### ISSUE TITLE
Website search functionality

### ISSUE THREAD

**Issue by rmammina** [hashicorp/terraform#13190]
I keep referring to your documentation, but every time I have to look up a resource, I continue to scroll through the page, for example, aws has a lot of resources.

Please make this experience better by adding a search box.

**Comment by tombuildsstuff** [comment]
Hi @rmammina 

Thanks for raising this - it's definitely something we're thinking about :)

Adding search functionality to the website has requested previously in #9589 (which has a proposed PR #13067). Rather than have multiple issues tracking the same thing, I'm going to close this issue in favour of that one - would you mind tracking/adding a 👍 to that issue instead?

Thanks!
