### ISSUE TITLE
Ask users confirmation to destroy instance

### ISSUE THREAD

**Issue by snowsky** [hashicorp/terraform#13231]
I'd like to submit a feature request based on the discussion at #13070.
When we destroy an instance, all the resources for the instance will be destroyed.
When I used -target to destroy a resource, TF will calculate all the dependencies and then it will destroy the whole instance. For this case, it would be better to ask users to double confirm. This is not something urgent to fix but nice to have for TF core.

### Affected Resource(s)
Please list the resources as a list, for example:
- disk
- instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
What should have happened?
- Notify users that the instance will be destroyed and ask if go ahead.
### Actual Behavior
What actually happened?
The whole instance was destroyed instead of just a resource of the instance.

**Comment by apparentlymart** [comment]
Hi @snowsky! Sorry for the long silence here.

PR #7251 changed the behavior of `terraform destroy` so that it now includes a list of resources that will be destroyed before the confirmation prompt. While this isn't exactly what you asked for, I think it's in the spirit of your use-case here, since it allows you to see which resources were matched by `-target` before approving the action.

This change isn't yet in a stable release but you can see a preview of it in v0.10.0-rc1. It should be included in the final v0.10.0 release, which will come out soon.

I'm going to close this since I think this change has addressed the spirit of your request here. Please do let me know if you think there's something missing in this resolution. Thanks for this request!
