### ISSUE TITLE
QUESTION: ElastiCache, aws-sdk-go

### ISSUE THREAD

**Issue by blacked** [hashicorp/terraform#1323]
Hi,

I started working on elasticache implementation for terraform. I see that all resources in aws provider use `github.com/hashicorp/aws-sdk-go/ ` but at least elasticache package in that library is different from original aws package. It even calls elastiCCache in that fork, which is not right. AWS repo have latest implementation of it and update it often. 

My question is, should I use that fork or can I use original aws repo?

PS. I was read `github.com/hashicorp/aws-sdk-go/blob/master/README.md` but still have that question.

**Comment by catsby** [comment]
Hey @blacked – we forked to maintain stability until after awslabs finished their refactoring and merged their develop branch into their master, which happened used yesterday. 

We will move back over to their implementation as soon as possible, but I can't say for sure when. Next week would be great, but I can't promise that as I don't know :/

**Comment by tmtk75** [comment]
Hi guys,

Several day ago, I also started working on implementation for elasticache and it has been almost finished just now.
https://github.com/hashicorp/terraform/compare/master...tmtk75:dev/aws_ecache

I use `github.com/hashicorp/aws-sdk-go/` as is for now because it is not so hard to fix if the package name is changed.

@blacked I should have announced here before I started my implementation.
How do I deal with my implementation? Have you already implemented a lot?

**Comment by blacked** [comment]
Hi @tmtk75 
Not a lot, thanks to let us know. I hope you will finish soon, because I really need elasticache implementation, that's why I start working on it too :)

Will you make it for both, memcached and redis type of clusters?

**Comment by tmtk75** [comment]
> I hope you will finish soon

Sure! It's almost done. I'm now tweaking comments or cosmetic changes like blank lines :smiley: 

> Will you make it for both, memcached and redis type of clusters?

I think it can.

Just in case, I tried to run acceptance test with [this fix](https://github.com/tmtk75/terraform/commit/db75ac2b76e74156cd8757ec527c9e7c016c0a94) in order to check if it properly launches clusters in redis engine. It ended with `ok`.

During the test, a redis cluster appeared in my console.
![elasticache_management_console](https://cloud.githubusercontent.com/assets/425100/6879959/f5cab5be-d55a-11e4-973a-14395f021168.png)

**Comment by tmtk75** [comment]
FYI: @blacked I created a pull request https://github.com/hashicorp/terraform/pull/1331

**Comment by juniorplenty** [comment]
@catsby any update?

**Comment by gposton** [comment]
Really excited about seeing Elasticache support in terraform :+1:

**Comment by phinze** [comment]
ElastiCache support has landed in master via #1331!

**Comment by catsby** [comment]
Hey all – sorry I dropped the ball here, a bit _vacation_, a bit _scatterbrained_ 

Thanks for the update @phinze and thanks for #1331 @tmtk75 :smile:
