### ISSUE TITLE
GCloud  compute destroyed and created on every apply

### ISSUE THREAD

**Issue by pratapsingh** [hashicorp/terraform#13266]
Hi ,

I am trying to do some activity on Google cloud using terrform but I am stuck with this issue 

### Terraform Version
`Terraform v0.9.2`

### Affected Resource(s)
- GCloud Compute

### Terraform Configuration Files
```
resource "google_compute_instance" "www" {

  name         = "${var.servername}"
  machine_type = "g1-small"
  zone         = "${var.region_zone}"
  tags         = ["www"]

  disk {
    image = "ubuntu-os-cloud/ubuntu-1404-trusty-v20160602"
  }

  network_interface {
    network = "default"

    access_config {
      # Ephemeral
    }
  }

  lifecycle {
    create_before_destroy = true
  }

  metadata {
    ssh-keys = "devops:${file("${var.public_key_path}")}"
  }

  provisioner "file" {
    source      = "${var.install_script_src_path}"
    destination = "${var.install_script_dest_path}"

    connection {
      type        = "ssh"
      user        = "devops"
      private_key = "${file("${var.private_key_path}")}"
      agent       = false
    }
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "devops"
      private_key = "${file("${var.private_key_path}")}"
      agent       = false
    }

    inline = [
      "chmod +x ${var.install_script_dest_path}",
      "sudo ${var.install_script_dest_path}",
    ]
  }
}
```

### Debug Output
[https://raw.githubusercontent.com/pratapsingh/vars/master/terraform_trace_file.txt](https://raw.githubusercontent.com/pratapsingh/vars/master/terraform_trace_file.txt)

### Expected Behavior
Should create Gcloud compute without deleting 

### Actual Behavior
Its deleting/destroying previously created computes and launching new compute.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply -var="servername=www-server-1"`
I have provided other required variables in variable.tf file.
https://raw.githubusercontent.com/pratapsingh/vars/master/terraform/gcloud/variables.tf

**Comment by apparentlymart** [comment]
Hi @pratapsingh! Sorry this isn't working as expected.

Could you run `terraform plan` with the same variables and share the console output describing Terraform's plan? That will help to see what Terraform thinks has changed and hopefully thus why that is not converging on a stable state.

**Comment by pratapsingh** [comment]
Here is the complete output with debug messages

https://raw.githubusercontent.com/pratapsingh/vars/master/terraform/gcloud/terraform_plan_trace_log.txt

**Comment by apparentlymart** [comment]
Hi @pratapsingh,

It looks like it is the name change that is forcing Terraform to remake the instance, which you can see by the `(forces new resource)` annotation on that particular diff.

If you want to update the server in place then you need to make sure its name does not change. In your config it looks like that'd  be achieved by setting the `servername` variable to be `www-server-2` to match the existing name, or by using a literal string for the name instead of a variable.

**Comment by pratapbirdeye** [comment]
Hi @apparentlymart,

Got your point but what if I have to increase server on daily or hourly basis. In my case I am trying to add more servers. These server are also not under auto-scale or load-balancer. I have some independent application running for which I have to launch multiple servers/computes on demand. So I am running this Terraform configuration provided above and it deletes the resource which I have created earlier automatically. Though I might need to delete it in some time later but not while launching another server. I guess my requirement is very simple one. Launch compute instances whenever there is a demand.

**Comment by apparentlymart** [comment]
I'd be interested to see your equivalent AWS config since I'm not sure I totally understand your use-case, but here are some ideas anyway:

---

The most common way to vary the number of resources of a particular type (assuming auto-scaling can't be used) is to use the `count` meta-argument to instruct Terraform to create multiple instances for a given configuration block:

```hcl
resource "google_compute_instance" "www" {
  count = "${var.server_count}"
  name  = "example-server-${count.index}"

  # with the rest of the config the same as before...
}
```

You can then change the `server_count` variable each time you run Terraform to change the number of instances, although the caveat with this (compared to auto-scaling systems) is that Terraform assigns a particular index to each instances, so if you decrease the count it will always be the instances with the highest indices that get destroyed first, rather than e.g. destroying the oldest instances or the ones that are closest to the end of their billing hour (in EC2).

---

A more flexible (but more complex/fiddly) approach would be to treat your config here as a child module and programmatically generate a top-level (root) module that instantiates it once for each separate server you want to have active:

```hcl
module "www-server-1" {
  source = "./www-server"
  server_name = "www-server-1"
}
module "www-server-2" {
  source = "./www-server"
  server_name = "www-server-2"
}
# server 3 not needed right now
module "www-server-4" {
  source = "./www-server"
  server_name = "www-server-4"
}
```

If you write a script to generate a configuration like the above and run it each time you want to change the number of servers then Terraform can automatically keep track of which servers are currently present and which are not and create/destroy as appropriate.

This is not a common/idiomatic approach, but it would work.

**Comment by pratapbirdeye** [comment]
Hi @apparentlymart  

Below is my aws terraform configuration file 

```
# Render a part using a `template_file`
resource "template_file" "script" {
  template = "${file("www_user_data.sh")}"
}


resource "aws_instance" "www" {
    ami = "${data.aws_ami.ubuntu1404.id}"
    instance_type = "${var.instance_type}"
    tags {
        Name = "${var.tag_name}"
        Email = "${var.tag_email}"
        Environment = "${var.tag_environment}"
        Builder = "${var.tag_builder}"
    }
    key_name = "${var.aws_key_name}"
    security_groups = ["${var.aws_sg}"]
    subnet_id = "${var.aws_subnet}"
    user_data     = "${template_file.script.rendered}"
    associate_public_ip_address = true

  root_block_device {
    volume_type = "standard"
    volume_size = "8"
    delete_on_termination = "true"
  }
}

```

Command which I run to launch instance  

`terraform plan -var 'availability_zone=ap-southeast-1a' -var 'aws_sg=sg-51046036' -var 'instance_type=t2.medium' -var 'profile=default' -var 'shared_credentials_file=/home/pratap/.aws/credentials' -var 'region=ap-southeast-1' -var 'vpc_name=www-test-1' -var 'aws_subnet=subnet-50f5a634'`

Below is the output of plan command:
```
There are warnings related to your configuration. If no errors occurred,
Terraform will continue despite these warnings. It is a good idea to resolve
these warnings in the near future.

Warnings:

  * template_file.script: using template_file as a resource is deprecated; consider using the data source instead

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.



data.aws_ami.ubuntu1404: Refreshing state...
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_instance.www
    ami:                                       "ami-cd16aaae"
    associate_public_ip_address:               "true"
    availability_zone:                         "<computed>"
    ebs_block_device.#:                        "<computed>"
    ephemeral_block_device.#:                  "<computed>"
    instance_state:                            "<computed>"
    instance_type:                             "t2.medium"
    ipv6_addresses.#:                          "<computed>"
    key_name:                                  "devops"
    network_interface_id:                      "<computed>"
    placement_group:                           "<computed>"
    private_dns:                               "<computed>"
    private_ip:                                "<computed>"
    public_dns:                                "<computed>"
    public_ip:                                 "<computed>"
    root_block_device.#:                       "1"
    root_block_device.0.delete_on_termination: "true"
    root_block_device.0.iops:                  "<computed>"
    root_block_device.0.volume_size:           "8"
    root_block_device.0.volume_type:           "standard"
    security_groups.#:                         "1"
    security_groups.366651315:                 "sg-51046036"
    source_dest_check:                         "true"
    subnet_id:                                 "subnet-50f5a634"
    tags.%:                                    "4"
    tags.Builder:                              "terraform"
    tags.Email:                                "devops@example.com"
    tags.Environment:                          "Production"
    tags.Name:                                 "WebServer"
    tenancy:                                   "<computed>"
    user_data:                                 "4255cf85d5661316217254d28adaaffb51b62d10"
    vpc_security_group_ids.#:                  "<computed>"

+ template_file.script
    rendered: "<computed>"
    template: "#!/bin/bash ......"

Plan: 2 to add, 0 to change, 0 to destroy.
```

In the above plan output, no resources are being forced similar to gcloud -> (forces new resource)

I just add new instances whenever there is demand/request for it in aws but unable to do it for GCloud as it terminates old computes.

**Comment by apparentlymart** [comment]
@pratapsingh the situation in your AWS case looks different because there wasn't already an instance created for `aws_instance.www`. I think if you were to try to run Terraform again with different settings it would either replace or update your existing instance (depending on which attribute you changed) rather than creating a new one, since Terraform remembers which instance id is associated with the name `aws_instance.www`.

**Comment by pratapsingh** [comment]
Hi @apparentlymart  I used another serve to run plan but there are servers created using terraform. Let me run it from my regular server.

**Comment by pratapsingh** [comment]
@apparentlymart  you are right .. we had multiple aws accounts for which we had just created one instance in each aws account (6 instances total) so far while recreating another instance it terminated old instances.

**Comment by apparentlymart** [comment]
Thanks for testing again @pratapsingh. If I'm understanding correctly it sounds like you're now seeing the same instance update/replace behavior for both AWS and Google instances, as I had expected.

Your use of Terraform here is a little unusual -- most people use it to model mostly-static infrastructure or they delegate dynamic needs to systems like AWS auto-scaling -- but my suggestions in my earlier comment may work to help you get what you need here.

A further possibility is to use a separate Terraform state for each instance, thus allowing them to each have an independent lifecycle, but that's a trickier workflow that is not supported well by the Terraform CLI so you'd probably need to write some sort of wrapper program to manage those states to reduce the risk of mistakes.

Since it sounds like there isn't really a bug to fix here -- though I understand that Terraform isn't behaving quite the way you expected -- I'm going to close this issue. Thanks again for taking the time to file this and work through the diagnosis with me!
