### ISSUE TITLE
aws_api_gateway_deployment stage_description behavior

### ISSUE THREAD

**Issue by jazzsasori** [hashicorp/terraform#13269]
### Terraform Version

0.9.2

### Affected Resource(s)

- aws_api_gateway_deployment

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_deployment" "deployment" {
  rest_api_id       = "${aws_api_gateway_rest_api.example.id}"
  stage_name        = "test"
  #stage_description = "example"
}
```

### Expected Behavior

Please warn me when I forgot stage_description param.

### Actual Behavior

When I `terraform apply` without stage_description, command succeed without error.
But "test" stage does not exists on AWS console.
This behavior confused me.

**Comment by Ninir** [comment]
Hi @jazzsasori 

Sorry for the noise here. I tried to replicate the issue you have locally using TF 0.9.3 but sadly couldn't. I made a test using a local config (which I can provide), and the stage do appears in the console, from a fresh provisionning.

Do you think you could provide your whole configuration, so that it's better for us to replicate and check?

Thanks!
