### ISSUE TITLE
Crash when passing nested hash to module containing resource reference

### ISSUE THREAD

**Issue by bsiegel** [hashicorp/terraform#13297]
The magic combination seems to be:
1. A module that defines a variable, which is a nested hash (i.e. the variable is a hash, and contains keys whose value is also a hash)
2. An instance of that module, with a value inside the nested hash that refers to a resource's attribute

### Terraform Version
v0.9.2

### Affected Resource(s)
`aws_lambda_function` but this appears to be a bug in core, not resource-specific

### Terraform Configuration Files
main.tf:
```hcl
provider "aws" {
  region  = "us-east-1"
}

# Could be any other resource, doesn't seem to crash with a simple variable reference
resource "aws_s3_bucket" "example" {
  bucket = "my-example-bucket"
}

module "test_module" {
  source = "test_module"

  configuration = {
    environment_vars = {
      BUCKET = "${aws_s3_bucket.example.arn}"
    }
  }
}
```

test_module/main.tf:
```hcl
variable "configuration" {
  default = {
    environment_vars = {}
  }
}

resource "aws_lambda_function" "function" {
  filename      = "file.zip"
  function_name = "function"
  handler       = "handler.handler"
  role          = "arn:aws:iam::123456:role/function-role"
  runtime       = "nodejs4.3"

  environment {
    variables = "${var.configuration["environment_vars"]}"
  }
}
```

### Panic Output
https://gist.github.com/bsiegel/99f90ad9c7e4d4f10c590d21f37f98f8

### Expected Behavior
No crash

### Actual Behavior
Crash

### Steps to Reproduce
1. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @bsiegel! Sorry for this crashing bug.

Currently there are some annoying oddities with how maps (which is the term we use for what you called "hashes" here) pass between different parts of Terraform. This certainly should *not* be crashing, but putting the crash aside there is a general oddness here with how values get from configuration into Terraform's core and the interpolation language which is unlikely to get resolved as part of fixing the crash here.

To avoid this weirdness, I would first suggest flattening out your structure so that the elements of the `configuration` map are top-level module variables in their own right:

```hcl
module "test_module" {
  source = "test_module"

  environment_vars = {
    BUCKET = "${aws_s3_bucket.example.arn}"
  }
}
```

This will probably then work as-is, but in case of further weirdness we can force the map to be constructed properly by using the `map` function instead of the braces syntax:

```hcl
module "test_module" {
  source = "test_module"

  environment_vars = "${map("BUCKET", aws_s3_bucket.example.arn)}"
}
```

We will hopefully spend some time on cleaning up some of these weird interactions in the configuration language parsing in the near future, but for now let's consider this ticket to represent producing a more friendly error message in this scenario rather than crashing, and we'll attend to the language design problems as part of a later, broader change.
