### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by babibza** [hashicorp/terraform#13304]
Hi, 

```hcl
variable "my_region" { 
  type = "list"
default = [ "east", "west", "central" ] }
variable "instance_count" { 
default = [ "4" ] }

resource "aws_cloudwatch_metric_alarm" "alarm" {
  count               = "${var.instnce_count * 4}"
  alarm_name          = "name-${format("%s", var.my_region[ceil(count.index / 3)])}--${format("%d", count.index + 1)}"
```

If i was passing my instance_count & my_region same count or my_region count morethan(greaterthan) instance count , i was running as expected without  any issues.
If i was passing instance_count greaterthan my_region count , it was throwing below error.
  **index 4 out of range for list var.my_region (max 3) in:**

is there anything i was doing wrong in my syntax ??

**Comment by apparentlymart** [comment]
Hi @babibza! Thanks for this question.

With that said, we prefer not to use the issue tracker for questions since Github issues makes it hard to keep track of the discussion and there aren't as many people looking here as, for example, the Google Group or gitter chat.

I think [the `element` function](https://www.terraform.io/docs/configuration/interpolation.html#element_list_index_) will help you here. If you have any further questions or would like a more detailed answer I suggest posting in [the Google Group](https://groups.google.com/forum/#!forum/terraform-tool).
