### ISSUE TITLE
-var-file failed to read file from URL

### ISSUE THREAD

**Issue by shlomir** [hashicorp/terraform#13315]
I'm trying to run terraform with -var-file from S3, like:
terraform plan -var-file=https://s3-eu-west-1.amazonaws.com/promotv-public/aws_config.tfvars
(The file is public)
i'm getting "no such file or directory" error, while local drive file is working fine.
Does -var-file should work with url? 

### Terraform Version
v0.9.2

### Expected Behavior
Should read file from URL as local file 

### Actual Behavior
failed to read file and abort operation.

**Comment by audioboxer217** [comment]
I'm curious about this one as well.  Based on the tags that @tombuildsstuff added, it sounds like this isn't currently supported but something that Hashicorp will look into possibly adding later.  Is that accurate?

Also, as an update to the original, I tested with the latest version, 0.10.4

**Comment by apparentlymart** [comment]
Hi @shlomir, @audioboxer217. Sorry for the silence here.

Downloading variables files is not currently supported. The download must be done as a separate step (e.g. with `curl` or `wget`) and then the file referenced from local disk.

We don't currently have any plan to support direct references to URLs in `-var-file`. We do have a longer-term plan to support a set of variables associated with each [workspace](https://www.terraform.io/docs/state/workspaces.html) that would be stored within the backend, though not to support generically fetching from any URL. This is not something we're working on right now, but is something we're intending to do eventually as part of some other enhancements to the capabilities of backends.

If the use-case here is to make use of data stored remotely, the usual way to get this done with Terraform is using [data sources](https://www.terraform.io/docs/configuration/data-sources.html). The various data sources supported by Terraform's providers allow data to be fetched or computed for use in configuration. At this time there isn't a way to fetch a set of values from a single S3 object, but [the `aws_s3_bucket_object` data source](https://www.terraform.io/docs/providers/aws/d/s3_bucket_object.html) and [the `http` data source](https://www.terraform.io/docs/providers/http/data_source.html) both allow fetching entire resources from S3 or arbitrary HTTP, returning the content as a string.

We suggest using data sources since that allows the fetch to happen as part of Terraform's normal processing, while traversing dependencies, so that the data source can potentially depend on values from elsewhere.
