### ISSUE TITLE
aws_kms_key : cannot move between regions because of incomplete state

### ISSUE THREAD

**Issue by awilkins** [hashicorp/terraform#13322]
### Terraform Version

0.92

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kms_key

### Expected Behavior

* Changed the provider on an existing `aws_kms_key` resource to one with a different region
* Expected `terraform apply` to cope with removing key from region 1 and recreating in region 2

### Actual Behavior

Terraform composites an ARN for the key from the provider region and the stored ID value in the state.

Therefore if you take an action that changes the region of the resource, it cannot be found during state discovery and you get

```
* aws_kms_key.healthcheck: aws_kms_key.healthcheck: NotFoundException: Key 'arn:aws:kms:us-east-1:<censored>:key/<censored>' does not exist
	status code: 400, request id: 2928add4-1927-11e7-85b2-41bf5eb3228a
```

- key is actually in `eu-west-2`, not `us-east-1` as in the ARN in the error message

### Steps to Reproduce

Create an `aws_kms_key` resource in one region, then use a provider attribute to change the region of that resource and re-apply.

### Suggested resolution

Store the full ARN of key resources in the state instead of compositing them from ID and region.

### Workaround

? Manually create a new key and edit the state file to point to that one instead

**Comment by awilkins** [comment]
Hah ; checking through the state file, it does actually store the full ARN. It just doesn't seem to be using it for lookups during state discovery.

**Comment by catsby** [comment]
Hey @awilkins there are a few things going on here.

1) The kms key resource is not handling the "not found" case gracefully. It should declare it "missing" and offer to recreate it. Note that in your case above, it won't remove the old version from the other region. This is because:

1) The provider block is not managed like a resource is. It's the "foundation" of everything that lives in that provider. When you change that, you can (possibly) change the entire foundation, so in this case you've changed regions which is a very distinct unit in AWS. By changing the region, you've reframed all queries that we're sending to AWS, so Terraform is now looking for that kms key in the new region, which it can't find. 

So even if we fix 1) above (which we should/will), by shifting the `region` in the `provider` block, you've changed the frame of reference so Terraform won't be able to reach out and remove the old one. IT will simply remove it from state (orphaning it) and create you a new one in the new region. Which doesn't seem like what you're looking for.

I hope that explains what I see is happening here. As I mentioned, 2) isn't something that's likely we'll change, but 1) needs to be cleaned up

**Comment by awilkins** [comment]
Yeah ; I can understand why my situation is a bit of an edge case.

Although ; in the case of aws_kms_key, the ARN includes the region. I've not changed the region in the provider - I've changed the provider associated with the key (the state caches the reference to the provider used to create the key, which still exists, and still points to the same region - I just have another provider for healthchecks pointing to us-east-1 because that's the only place you can do them). It should still be possible for Terraform to remove the old key, it will only break when you modify the providers themselves, rather than changing the provider associated with the resource.
