### ISSUE TITLE
AWS RDS MSSQL instance to join Directoryservices  domain argument is not available in current terraform. From AWS cli option is Domain to join RDS instances to Directory servcies

### ISSUE THREAD

**Issue by MangeshRege** [hashicorp/terraform#13329]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by krstosavic** [comment]
This is something I need also. Cannot create RDS instance from terraform because Amazon directory integration is not supported. Can you please take a look at it?

**Comment by nckslvrmn** [comment]
Bump +1, This is a critical feature I would love to start using ASAP.

**Comment by paddycarver** [comment]
Hey @nckslvrmn, sorry for the inconvenience, but AWS provider issues have moved to the [aws provider repository](https://www.github.com/terraform-providers/terraform-provider-aws). Development has also moved there, which means #14425 would need to be reopened against that. I don't know if @mikewalker125 is interested in undertaking that or if one of the maintainers should just move their code for them--I'll leave this for a couple days in case they chime in and say they want to do it. If not, I'll tackle it and try to preserve git authorship appropriately. :)

But the best way to track this issue is to reopen it in the AWS provider repository, where it will receive more attention. Sorry for the trouble.
