### ISSUE TITLE
provider/openstack: Destroying an instance removes the attached network port, causing creation to fail due to missing network port

### ISSUE THREAD

**Issue by fatmcgav** [hashicorp/terraform#13365]
Given the below TF code, taken from here [`openstack_compute_instance_v2`](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html), I am able to create a network port and an instance within Openstack. 

If I then need to rebuild the `openstack_compute_instance_v2` resource, then the attached `openstack_networking_port_v2` resource gets deleted automatically by Openstack upon removing the instance. 
However, Terraform doesn't attempt to re-create the `openstack_networking_port_v2` resource before recreating the `openstack_compute_instance_v2` resource. This results in a failed run, and having to re-plan and re-run the instance creation. 

Naively, I'd expect TF be able to pick up this scenario and recreate the port before it attempts to create the compute instance.

@jtopjian Thoughts? 
Is this missing functionality in the Openstack provider, or Terraform core, or both?

### Terraform Version
`Terraform v0.9.2`

### Terraform Configuration Files
```hcl
resource "openstack_networking_port_v2" "port_1" {
  name           = "port_1"
  admin_state_up = "true"

  network_id = "0a1d0a27-cffa-4de3-92c5-9d3fd3f2e74d"

  security_group_ids = [
    "2f02d20a-8dca-49b7-b26f-b6ce9fddaf4f",
    "ca1e5ed7-dae8-4605-987b-fadaeeb30461",
  ]
}

resource "openstack_compute_instance_v2" "instance_1" {
  name = "instance_1"

  network {
    port = "${openstack_networking_port_v2.port_1.id}"
  }

  connection {
    user        = "root"
    host        = "${openstack_networking_port_v2.port_1.fixed_ip.0.ip_address}"
    private_key = "~/path/to/key"
  }

  provisioner "remote-exec" {
    inline = [
      "echo terraform executed > /tmp/foo",
    ]
  }
}
```

**Comment by jtopjian** [comment]
I'm going to tag openstack on this, too, as it might be specific to the OpenStack provider and/or specific OpenStack configuration.

@fatmcgav Thanks for reporting this. I'll take a look and see if I can figure out what's going on.

**Comment by jtopjian** [comment]
@fatmcgav What are the steps to reproduce this error? Are you tainting the instance and then reapplying?

**Comment by fatmcgav** [comment]
@jtopjian Yeh, that's correct. 

Taint the instance, plan and then apply. 

I did come up with a workaround for time being which is to taint the port resource rather than the instance. Terraform then correctly flags the instance as requiring recreation aswell.

**Comment by fatmcgav** [comment]
@jtopjian Have you had a chance to look at this?

Another scenario I've just hit is creating a `openstack_blockstorage_volume_v2` resource which forms the boot volume for an `openstack_compute_instance_v2` resource. Tainting the instance causes the volume to be deleted, but then TF doesn't re-create it before attempting to create the new instance...

**Comment by jtopjian** [comment]
@fatmcgav I looked into this today and had some discussion about it. OpenStack deleting resources behind the scenes is the core cause of the problem. There are two things you can do at the moment to get around this:

1. Taint both resources, or
2. Delete the dependent resource (in this case, the instance) outside of Terraform. Doing an "apply" afterwards will end up recreating both since neither no longer exist.

A better way to handle this is if the Instance had full native support for ports and volumes _within_ the instance resource. I'm on the fence about this. It would certainly solve the problems you're seeing, but at the cost of modeling the Terraform resources differently than being directly aligned with the OpenStack API. I'm not opposed to the idea, but it would require a good amount of work.

So with all of the above in mind, I am going to remove the `core` label from this since it's not a core bug. I'm happy to leave the Issue open for anyone else to come across and comment on the options and because this is a legitimate issue with using Terraform and OpenStack.

**Comment by jtopjian** [comment]
So I've been thinking about this over the past few days and realized that adding full support for "ports" in the Instance resource will cover that specific use-case, it will not help with the boot-from-volume. For boot-from-volume, the you could just use set the `delete_on_termination` attribute to `false`. 

But this highlights that this is always going to be a case-by-case basis and there's a balance between making the OpenStack resources bigger to account for all of these cases (ie: nesting full port support within the instance) and documenting cases where one should do things like taint multiple resources in order for them to rebuild correctly. In addition, some of the cases only exist for certain OpenStack configurations (I've heard that some configurations do not delete the port when the instance has been deleted).

Because of this, I'm going to lean on documenting and user education. It's certainly possible to add more support for Neutron Ports within the instance, but since that is a large amount of work for only certain situations, it's going to take a lower priority from other issues.

I'm going to close this issue for now so it doesn't become stale. If someone wanted to work on adding support for these types of situations within the resources, I would be happy to help answer questions and review code.

**Comment by fatmcgav** [comment]
@jtopjian Fine by me... I'll see if I can find some time to take a stab at docs :)
