### ISSUE TITLE
Help Using Local file backend

### ISSUE THREAD

**Issue by TraGicCode** [hashicorp/terraform#13372]
Can anyone provide an dummy example of having 2 terraform files, like below and being able to reference data from the disk.tf's teraform state file in the web-server.tf file.  I see the docs show terraform has a local backend but i cannot find any good examples of using it.

elastic-ip.tf

web-server.tf

**Comment by pselle** [comment]
Hello @TraGicCode! A lot of time has passed on this issue, and I hope you found some guidance elsewhere! I'm going to close this, as we use GitHub issues for tracking bugs and enhancements rather than for questions.

We suggest that folks use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
