### ISSUE TITLE
Terraform remote config does not work in 0.9.2

### ISSUE THREAD

**Issue by ChiliMonanta** [hashicorp/terraform#13382]
Hi there,

Upgraded to latest version 0.9.2 and terraform can't find the remote command anymore!

### Terraform Version
Terraform v0.9.2 (Windows 64-bit)

### Expected Behavior
```
$ terraform --help remote
Usage: terraform remote <subcommand> [options]

  Configure remote state storage with Terraform.

Options:

  -no-color   If specified, output won't contain any color.

Available subcommands:

  config      Configure the remote storage settings.
  pull        Sync the remote storage by downloading to local storage.
  push        Sync the remote storage by uploading the local storage.
```

### Actual Behavior
```
$ terraform --help remote
Usage: terraform [--version] [--help] <command> [args]

The available commands for execution are listed below.
The most common, useful commands are shown first, followed by
less common or more advanced commands. If you're just getting
started with Terraform, stick with the common commands. For the
other commands, please read the help and docs before usage.

Common commands:
    apply              Builds or changes infrastructure
    console            Interactive console for Terraform interpolations
    destroy            Destroy Terraform-managed infrastructure
    env                Environment management
    fmt                Rewrites config files to canonical format
    force-unlock       Manually unlock the terraform state
    get                Download and install modules for the configuration
    graph              Create a visual graph of Terraform resources
    import             Import existing infrastructure into Terraform
    init               Initialize a new or existing Terraform configuration
    output             Read an output from a state file
    plan               Generate and show an execution plan
    push               Upload this Terraform module to Atlas to run
    refresh            Update local state file against real resources
    show               Inspect Terraform state or plan
    taint              Manually mark a resource for recreation
    untaint            Manually unmark a resource as tainted
    validate           Validates the Terraform files
    version            Prints the Terraform version

All other commands:
    debug              Debug output management (experimental)
    state              Advanced state management
```

### Steps to Reproduce
1. `terraform --help remote`

### References
This was reported  in another issue (version 0.9) but should have been fixed, https://github.com/hashicorp/terraform/issues/12762, currently it's not

**Comment by pioneerit** [comment]
@ChiliMonanta, if you'd read the #12762 or release notes before upgrade: https://www.terraform.io/docs/backends/legacy-0-8.html
You probably would learn that it is gone.

**Comment by mitchellh** [comment]
Hey! As the CHANGELOG says (for 0.9.0) as well as the [upgrade guide to 0.9.0](https://www.terraform.io/upgrade-guides/0-9.html), the `remote config` command was removed.

It has been replaced with `terraform init` picking up that functionality since backend configuration now lives in the Terraform configuration files themselves. You can mimic the `remote config` functionality there: it accepts k/v from the CLI. It now also accepts k/v from files as well and user interactive input.

0.9.3 (unreleased, next week) fixes a few issues around this. Namely, `-input` will prevent state migration prompts. And migration won't occur if the states are the same. However, this shouldn't stop you from adopting the new command. Sorry for the breaking change!
