### ISSUE TITLE
support EC2 spot instances

### ISSUE THREAD

**Issue by spenczar** [hashicorp/terraform#1339]
I'd like to be able to spin up spot EC2 instances, setting the price in my .tf file.

My particular use case is managing a moderately large Apache Spark cluster. Spot pricing cuts costs considerably - 70% off, often - and the possibility of nodes getting interrupted and stolen is actually totally fine in Spark - like any Hadoop, it expects node failure as a matter of course.

I'd like to be able to make requests for spot instances much like I'd request normal instances, but I'm open to any API really.

**Comment by vlk-charles** [comment]
I am dealing with the same problem. Although [the documentation](https://terraform.io/docs/providers/aws/r/launch_config.html) does not mention it, from examining [resource_aws_launch_configuration.go](https://github.com/hashicorp/terraform/blob/045c020244baf7c918ed142bb7b0288d08b005cf/builtin/providers/aws/resource_aws_launch_configuration.go) it looks like launch configurations might support Spot Instances.

**Comment by vlk-charles** [comment]
I was able to create a Spot Instance request liek this:
```
resource "aws_launch_configuration" "myconf" {
    name = "myconf"
    image_id = "ami-394ecc4e"
    instance_type = "t1.micro"
    key_name = "${aws_key_pair.mykey.key_name}"
    associate_public_ip_address = true
    spot_price = 0.005
}

resource "aws_autoscaling_group" "mygroup" {
    name = "mygroup"
    launch_configuration = "${aws_launch_configuration.myconf.id}"
    min_size = 1
    max_size = 1
    availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    vpc_zone_identifier = ["subnet-a001c3d7", "subnet-923ddccb", "subnet-480baf2d"]
}
```
The problem now is that I cannot reference the instance from the configuration so I cannot, for examle, assign a DNS name to its public IP address.

**Comment by dalehamel** [comment]
@vlk-charles did you ever find a solution? I'm currently evaluating terraform (have not yet used it).

From the look of it, it would seem that you can, at least, use terraform's 'provisioners' to act on spot instances. Since they are called upon resource creation (for spot instances, I would assume this would be called assuming spot price resolution and successful bid have occurred, and the instance has come up). So in your case, it looks like you could for instance us a 'local command' to set the DNS name.

I'm confused by your statement "I cannot reference the instance from the configuration".

Are you talking about interpolating the instance? How is this possible elsewhere within the template? Since the instances are actually members of an autoscaling group, I don't see how they would be exposed directly.

Pardon my ignorance, i'm still reading docs and combing through source code - haven't gotten my hands dirty yet.

**Comment by dalehamel** [comment]
It would be nice if there were direct support for an aws_spot_instance resource as well (rather than just through autoscaling).

**Comment by vlk-charles** [comment]
@dalehamel I put Terraform aside for now.

Yes, I was talking about interpolation. For example, I can do this with regular ("on demand") instances:
```
resource "aws_instance" "myserver" {
    ami = "ami-394ecc4e"
    instance_type = "t1.micro"
    key_name = "${aws_key_pair.mykey.key_name}"
}

resource "digitalocean_record" "myserver_domain" {
    domain = "mydomain.net"
    type = "A"
    name = "myserver"
    value = "${aws_instance.myserver.public_ip}"
}
```
to make `myserver` available at `myserver.mydomain.net`.

**Comment by dalehamel** [comment]
thanks for your response @vlk-charles!

I'm going to try and develop a 'aws_spot_instance' resource and submit it as a PR. I think it should be fairly similar to the aws_instance resource, only it would need to handle the spot price resolution.

**Comment by ketzacoatl** [comment]
@dalehamel++

**Comment by vlk-charles** [comment]
@dalehamel Great!

**Comment by dalehamel** [comment]
Spot instance support has landed thanks to @phinze !!!

:clap:

**Comment by dalehamel** [comment]
can a collaborator please close this issue?

**Comment by phinze** [comment]
:+1:

**Comment by ketzacoatl** [comment]
:clap:
