### ISSUE TITLE
is there any plan to support eucalyptus cloud ?

### ISSUE THREAD

**Issue by shamimgeek** [hashicorp/terraform#13485]
Is there any plan to support eucalyptus cloud [ a aws compatible cloud ] ?

**Comment by zvainio** [comment]
Actually I've been able to create instances with Eucalyptus.  There are some gotchas and differences.  I'm using terraform with Eucalyptus 4.4 and 4.3.

AWS provider definition is something like this

provider "aws" {
  # access_key = "AKIAA..."
  # secret_key = "xkVQJ..."
  # Eucalyptus .ini file
  # key-id => aws_access_key_id, secret-key => aws_secret_access_key
  shared_credentials_file = "${var.cred_path}"
  profile = "user 000123456789:foobar"
  insecure  = true
  skip_credentials_validation = true
  skip_region_validation = true
  region = "eucalyptus"
  endpoints {
    ec2 = "ec2.cloud.foo.net:8773"
    iam = "iam.cloud.foo.net:8773"
    elb = "elasticloadbalancing.cloud.foo.net:8773"
  }
}

**Comment by stack72** [comment]
Hi @shamimgeek 

I think we can close this out - thanks to @zvainio for the explanation on how to get started with it

Paul

**Comment by shamimgeek** [comment]
@zvainio : Thanks alot for this configuration it worked.  

@stack72 & all contributors of terraform: Please also consider eucalyptus officially supported. 

Thanks
Shamim Akhtar

**Comment by apparentlymart** [comment]
Currently support for these "AWS-like" platforms using the AWS provider is on a "best effort" basis: we try to build the AWS provider in such a way that it's possible to configure it to work, but the UX isn't optimized (i.e. it requires some verbose configuration, as seen above) and we don't pro-actively run the automated acceptance tests against these other platforms.

Since AWS is not intended to be a "standard", these other platforms often have subtle- and not-so-subtle incompatibililties which we try to address but can't always catch. If anyone finds bugs with or blockers for using these other workalike platforms with the AWS provider they are welcome to open a Github issue about it, though since we don't necessarily all have ready access to these platforms ourselves it helps a lot if the requester can share as much information as possible about what's going on and what the solution might be. We are also very happy to review PRs for changes to make these alternative platforms easier to use, as long as they don't hurt the UX and behavior when talking to the real AWS APIs.

For now the focus must be on the "real AWS" since it's already a lot of work to keep up with the changes there, though of course this may change in the future as these other platforms evolve. More info and discussion on this can be seen in #6535.
