### ISSUE TITLE
provider/google-cloud: Running Google Cloud Dataflow jobs

### ISSUE THREAD

**Issue by dasch** [hashicorp/terraform#13537]
There's an API for running templated Google Cloud Dataflow jobs: https://cloud.google.com/dataflow/docs/templates/executing-templates

It's also possible to update and cancel these from the API.

**Comment by danawillow** [comment]
Thanks for filing this, @dasch! We'd love to see support for this, but it's not something that the GCP maintainers are going to be able to get to in the immediate future. We're happy to review PRs if you (or anyone else reading this) want to take a stab at it, otherwise user interest (most helpfully expressed by 👍 -ing the issue) will help us prioritize the features with the most demand from the community.

**Comment by dasch** [comment]
OK, I'll see what I can do. I've got to learn Go first, though...

**Comment by dasch** [comment]
@danawillow I've added a PR here: #14174

**Comment by dasch** [comment]
@danawillow I'm not quite sure how to proceed now...

**Comment by danawillow** [comment]
Are you talking about the closed issue? If so, issues were moved over to https://github.com/terraform-providers/terraform-provider-google automatically. I don't think they've moved PRs over yet. In the meantime, you can continue working on this as you were before (as long as you don't merge/rebase onto master). If it's ready to merge and we still haven't heard about what to do, we can just move it over manually.

**Comment by dasch** [comment]
@danawillow unfortunately I've moved on to other things and so probably won't have time to continue working on this. I hope someone else can take over the code and move it along.

**Comment by danawillow** [comment]
Ok, thanks for the update! I should be able to take it from here some point soon.
