### ISSUE TITLE
Support updating customData on Azure RM VM Scaling Sets

### ISSUE THREAD

**Issue by lmickh** [hashicorp/terraform#13547]
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
azurerm_virtual_machine_scale_set

### Expected Behavior
Allow the update to the customData.

### Actual Behavior
Get the following message:
```
compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="PropertyChangeNotAllowed" Message="Changing property 'customData' is not allowed."
```

### Steps to Reproduce
Create an `azurerm_virtual_machine_scale_set` resource with generated customData in the os_profile.
Generate new customData (change a cloud-init template file or ignition resource for example)
Run `terraform apply` against the scale set.

### Important Factoids
My understanding is that the Azure Compute API was updated to allow for changes to customData.  A later version of the api ( > "2016-03-30" possibly "2016-08-30") may need to be used.  I tried confirming the specific version of the change, but have had troubles do to the lack of documentation for the Azure API.

**Comment by tombuildsstuff** [comment]
Hi @lmickh 

Thanks for reporting this.

I've [opened a bug on the Azure SDK for Go repository](https://github.com/Azure/azure-sdk-for-go/issues/585) to upgrade the version of the Compute API to a version which supports this functionality. Once the SDK is updated - we can investigate adding support for this :)

Thanks!

**Comment by GreatSnoopy** [comment]
I would add that at least it should be possible to skip the error. Adding 
  lifecycle {
    ignore_changes = "*"
  }
 for that vm does nothing.
In my case, I get this because since the creation of the VM, the custom_data(cloudinit data in our case)  that is used has changed. However, as custom data is not really used in our case for anything else that initial kickstart, i do not even need to change it for an existing vm that has already been created and kickstarted. Also, for various reasons, recreating those vm's is not practical, so it would be sensible to be able to ignore this type of change.
