### ISSUE TITLE
EMR Cluster Terminates when adding CORE

### ISSUE THREAD

**Issue by bam0382** [hashicorp/terraform#13600]
### Terraform Version

`Terraform v0.9.2`

### Affected Resource(s)

- aws_emr_cluster

### Terraform Configuration Files
```hcl
# Create EMR Cluster
resource "aws_emr_cluster" "default" {
  name          = "${var.application_name}-emr-${var.environment}"
  release_label = "emr-5.1.0"
  applications  = ["Spark","Hive","Hue","Zeppelin","HCatalog"]

  termination_protection = true
  keep_job_flow_alive_when_no_steps = true

  ec2_attributes {
    key_name                          = "${var.application_name}-emr-${var.environment}"
    subnet_id                         = "${element(split(",", data.terraform_remote_state.vpc.private_subnets), 0)}"
    emr_managed_master_security_group = "${aws_security_group.master.id}"
    emr_managed_slave_security_group  = "${aws_security_group.slave.id}"
    service_access_security_group     = "${aws_security_group.serviceaccess.id}"
    instance_profile                  = "${module.ec2.iam_instance_profile}"
  }

  master_instance_type = "m4.xlarge"
  core_instance_type   = "m4.xlarge"
  core_instance_count  = 2

  tags {
    Name = "${var.application_name}-emr-${var.environment}"
  }

  log_uri = "s3://${var.application_name}-emr-${var.environment}/emr-logs/"

  configurations = "${file("configurations/emr-conf.json")}"

  service_role = "${aws_iam_role.emr.arn}"
}
```

### Debug Output

```
aws_emr_cluster.default: Still creating... (18m50s elapsed)
Error applying plan:

1 error(s) occurred:

aws_emr_cluster.default: 1 error(s) occurred:

aws_emr_cluster.default: [WARN] Error waiting for EMR Cluster state to be "WAITING" or "RUNNING": unexpected state 'TERMINATING', wanted target 'WAITING, RUNNING'. last error: %!s(<nil>)
```

### Expected Behavior

The EMR cluster should goto status "Waiting".

### Actual Behavior

The EMR cluster terminates after ~20 minutes of provisioning with:

"Terminated with errors Bootstrap failure"

There is no bootstrap enabled.

### Steps to Reproduce

1. `terraform apply`

**Comment by radeksimko** [comment]
Hi @bam0382 
in most (if not all) cases when the EMR cluster is being terminated there isn't much we can do on Terraform's side I think. The best thing to do from user's side is probably to re-apply (i.e. recreate) the cluster if the issue is intermittent or figure out what caused the issue and fix it before re-applying.

Terraform is dealing with high-level API here, it doesn't see inside the instances being launched as part of the cluster.

The error message you mentioned certainly isn't ideal - I have improved it to include reason of the termination in https://github.com/hashicorp/terraform/issues/15117

Is this error intermittent or can you reliably reproduce it every single time? What do you suggest we do to recover?

**Comment by bam0382** [comment]
@radeksimko thank you! Sorry for the late reply.
