### ISSUE TITLE
Interpolation: allow turning maps into lists

### ISSUE THREAD

**Issue by dasch** [hashicorp/terraform#13624]
I'm using Terraform to launch a local-exec command that takes named parameters, and would like to configure those parameters using a `map`. However, I can see no way to turn the map into a list that can be joined using a separator.

Current setup:

```hcl
variable "parameters" {
  default = []
}

resource "null_resource" "thing" {
  provisioner "local-exec" {
    command = "/bin/something --params=${join(",", var.parameters)}"
  }
}
```

This forces me to set the parameters in a weird way, e.g. `parameters = ["height=20", "width=30"]`.

This is what I'd like to do:

```hcl
variable "parameters" {
  default = {} # it's a map!
}

resource "null_resource" "thing" {
  provisioner "local-exec" {
    # `tolist` takes a separator that goes between the key and the value, and the map.
    command = "/bin/something --params=${join(",", tolist("=", var.parameters))}"
  }
}
```

That would allow me to pass in the parameters like this: `parameters = { height = 20, width = 30 }`.

**Comment by apparentlymart** [comment]
Hi @dasch! Sorry for the long silence here.

There's a new feature now in master, ready to be included in the forthcoming v0.12.0 release, which should address your use-case here:

```hcl
variable "parameters" {
  default = {} # it's a map!
}

resource "null_resource" "thing" {
  provisioner "local-exec" {
    # `tolist` takes a separator that goes between the key and the value, and the map.
    command = "/bin/something --params=${join(",", [for k, v in var.parameters: "${k}=${v}"])}"
  }
}
```

You can find more about this feature in [the preview blog post about it](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each).

Since this change is already in master, I'm going to close this out now. Thanks for this feature request, and sorry again for the long delay in responding to it.
