### ISSUE TITLE
Feature suggestion: Provider-independent resources

### ISSUE THREAD

**Issue by OliverCole** [hashicorp/terraform#13655]
As far as I know, resources are all subordinate to providers. Perhaps it might be useful to have resources that were provider agnostic?

Say we wanted to keep our DNS on multiple platforms, e.g. cloudflare and route 53, like [the guys at StackOverflow](http://blog.serverfault.com/2017/04/11/introducing-dnscontrol-dns-as-code-has-arrived/). (And further assume they don't support RFC 2136, so we can't use the [DNS provider](https://www.terraform.io/docs/providers/dns/index.html).

Wouldn't it be interesting to define the resource generically, and pass/link/send/attach it to a provider or multiple providers for implementation?

**Comment by catsby** [comment]
Hey @OliverCole – could you elaborate here? Maybe provide some sample Terraform configuration of what you're imagining this would look like?

**Comment by OliverCole** [comment]
OK, some boilerplate:

    variable "aws_access_key" {}
    variable "aws_secret_key" {}
    variable "region" {
        default = "eu-west-1"
    }
    
    provider "aws" {
        access_key = "${var.aws_access_key}"
        secret_key = "${var.aws_secret_key}"
        region = "${var.region}"
    }
    
    provider "cloudflare" {
      email = "${var.cloudflare_email}"
      token = "${var.cloudflare_token}"
    }
    
    resource "aws_route53_zone" "example" {
        name = "example.com"
    }
    
    resource "shared_dns_a_record_set" "www" {
      zone = "example.com."
      name = "www"
      addresses = [
        "192.168.0.1",
        "192.168.0.2",
        "192.168.0.3",
      ]
      ttl = 300,
    }

And then a few options for linking them together - not sure which is the best:
A list of providers on the resource?

    resource "shared_dns_a_record_set" "www" {
      zone = "example.com."
      name = "www"
      addresses = [
        "192.168.0.1",
        "192.168.0.2",
        "192.168.0.3",
      ]
      ttl = 300,
      providers = ["aws", "cloudflare"]
    }

Or maybe a 'linking resource'?

	resource "shared_dns_link" "wwwlink" {
		recordset = "${shared_dns_a_record_set.www}",
		providers = ["aws", "cloudflare"]
	}

**Comment by grubernaut** [comment]
Hi @OliverCole, thanks for the issue!

Thanks so much for the request for this new feature! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Currently, the best path forward for creating "provider-agnostic" resources, is to use a Terraform Module, that requires the common DNS variables needed to create the two separate resources for each provider inside of the module. 

Thanks!
