### ISSUE TITLE
terraform deletes provisioning-key even if its present in aws. My code didn't change

### ISSUE THREAD

**Issue by rakesh-nd** [hashicorp/terraform#13667]
Hi there,

```
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

- aws_key_pair.provisioner
```

its deleting the provisioner key even if its not interfered with at all. The resource is still available in aws.

Why does this happen ? Can anyone please help me out ?

**Comment by apparentlymart** [comment]
Hi @rakesh-nd! Sorry things are not working as expected here.

The most common reason for the output you presented here would be that the resource has been removed from the configuration, either by removing it outright or by changing its name (which Terraform would see as creating a new one and destroying the old one).

It's hard to say what's going on here without more examples. Generally we try to keep general questions out of github issues since it's hard to keep track of and follow discussions here, so if the above doesn't answer your question I recommend using one of the community forums linked from [our Community page](https://www.terraform.io/community.html), or ask on [Server Fault](https://serverfault.com/). Either way some more information about your configuration is likely to be needed to give a more in-depth answer.

Thanks!

**Comment by rakesh-nd** [comment]
Ok sure. resource name was not changed at all. Thanks for a quick response !
