### ISSUE TITLE
Add support for tags on Lambda

### ISSUE THREAD

**Issue by MrGossett** [hashicorp/terraform#13746]
AWS recently announced tagging support for Lambda functions.

**Comment by harkamals** [comment]
+ Add support for encrypted environment variables for lambda

**Comment by davidski** [comment]
@harkamals Would you open a separate issue for this? This issue is focused on the new tagging feature. For encrypted environment variables, you may want to flesh out what you're looking for, as the existing Lambda resource does have a kms_arn parameter which is used for decrypting environment variables.

**Comment by stack72** [comment]
Closed via #13873

This will be available in Terraform 0.9.4
