### ISSUE TITLE
Two chat rooms and a google(!) group are poor support for general questions

### ISSUE THREAD

**Issue by KidPluto** [hashicorp/terraform#13756]
As you can tell, not a issue/bug.

I have used gitter and not gotten any response.  If there was a proper forum I would be able to search there for my answer.  

Thanks.

**Comment by apparentlymart** [comment]
Hi @KidPluto! Thanks for this feedback.

We've been growing aware of this issue ourselves as we struggle a bit to keep up with the influx of questions, particularly given that neither Gitter nor Google Groups have a great story for discovering questions that have already been asked and answered, and Gitter makes it hard to work "asynchronously", and thus answer questions concurrently with other work.

We (the Terraform team at Hashicorp) have been discussing this internally and are planning to address it in the near future. For now I'd ask for patience as we work through some of the challenges of scaling our tools around this project.

I'm going to close this for now, since as you said it's not an issue/bug. But we *are* working on this internally and should hopefully have more to share soon. Thanks again for sending this feedback!
