### ISSUE TITLE
Console doesn't support lists?

### ISSUE THREAD

**Issue by Wenzil** [hashicorp/terraform#13770]
### Terraform Version
0.9.3

### Expected Behavior
The list should be printed

### Actual Behavior
The following error is printed: `parse error at 1:3: expected expression but found "["`
 
### Steps to Reproduce
1. Run `terraform console`
2. Type `["a", "b", "c"]` in the console

**Comment by apparentlymart** [comment]
Hi @Wenzil! Sorry things aren't working as expected here

What you've found here is one of the rough edges in Terraform's configuration language, or rather that Terraform in fact has a number of different languages within it. This list syntax with `[ ... ]` is part of the top-level, *structural* configuration language HCL while the console is dealing with the interpolation expression language HIL, which is what exists inside `${ ... }` delimiters in config.

Smoothing the "edge" between these is a medium-term goal, since of course this implementation detail should not be visible in "the UI" as it is today. But for now the workaround for what you want to do here is to use the `list` function, which is defined in the interpolation language as dynamically constructing lists:

```
list("a", "b", "c")
```

There's a similar function for creating maps dynamically:

```
map("foo", "a", "bar", "b")
```

The above corresponds to a map that might be expressed in JSON like `{"foo": "a", "bar": "b"}`.

I hope that helps! This is part of a set of configuration language warts that are already on our radar and captured by other documents both here on Github and internally within Hashicorp, so I'm going to close this just to keep the queue a bit more manageable, but this sort of issue is definitely something we intend to fix in future via more holistic changes to the configuration language.
