### ISSUE TITLE
Join in Modules/Remote State

### ISSUE THREAD

**Issue by fii** [hashicorp/terraform#13781]
Hi, any idea/s why the top one works but not the bottom one via remote state ? 

```hcl
output "private_subnets" {
  value = "${join(",", aws_subnet.private_subnets.*.id)}"
}
```

```hcl
output "private_subnets" {
  value = "${join(",", module.vpc-ops.aws_subnet.private_subnets.*.id)}"
}
```

thanks.

**Comment by apparentlymart** [comment]
Hi @fii!

This "splat syntax" with the `*` symbol is specifically for resources with `count` specified. Since modules don't currently support count, and since a module can't currently export a complex value like that.

The way to express what I think you're trying to do here is to have an output in the `vpc-ops` module that exports the `private_subnets`, like in your first example, and then to interpolate directly the result of that in your parent module:

```hcl
output "private_subnets" {
  value = "${module.vpc-ops.private_subnets}"
}
```
