### ISSUE TITLE
assign_ipv6_address_on_creation bad plan

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#13829]
Just upgraded from 0.8.7 to 0.9.3.

There appears to be a new `aws_subnet` property, `assign_ipv6_address_on_creation`.

Each of my subnets has a plan to:

    ~ module.foo.aws_subnet.bar.0
        assign_ipv6_address_on_creation: "" => "false"

This would be fine, except it wants to recreate all of my EC2 instances:

    -/+ module.foo.aws_instance.aws
        ipv6_addresses.#:                          "" => "<computed>" (forces new resource)

I am Very Surprised by this!

**Comment by stack72** [comment]
Hi @pikeas

Apologies you are running into this error, sorry it is causing you issues. In order to try and work through what the pain points for you are, please can you post the terraform config you are using that is causing the unexpected change? Please remember to exclude any sensitive information

Thanks

Paul
