### ISSUE TITLE
Unable to destroy instance that is part of autoscaling group

### ISSUE THREAD

**Issue by cheburakshu** [hashicorp/terraform#13888]
On Terraform v0.9.2

In terraform (also on ec2 console), the launch configuration is created first and then the autoscaling group is created.
When deleting the autoscaling group needs to be deleted first before deleting the launch configuration. But terraform quits doing the opposite with the below error.

```
1 error(s) occurred:

* module.launch_configuration.aws_launch_configuration.aws_launch_configuration (destroy): 1 error(s) occurred:

* aws_launch_configuration.aws_launch_configuration: ResourceInUse: Cannot delete launch configuration hello-world-minion-group-us-west-2a because it is attached to AutoScalingGroup hello-world-minion-group-us-west-2a
	status code: 400, request id: 2dca1290-28a2-11e7-8233-471ad7ac7672

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by catsby** [comment]
Hey @cheburakshu if you have a configuration setup that demonstrates this we can take a closer look. Thanks!

**Comment by cheburakshu** [comment]
@catsby You can pull the repo github.com/cheburakshu/terrakube and do a ./run.sh and destroy -var-files=config/config.dev.tfvars.

It will create a master t2.micro (standalone) and minion t2.micro (autoscaling group min 1 max 1). Try destroying it with destroy.

**Comment by catsby** [comment]
Hello – I took a look briefly and see that you're not using resource interpolation to define dependencies. https://github.com/cheburakshu/terrakube/blob/master/modules/aws_autoscaling_group/main.tf and https://github.com/cheburakshu/terrakube/blob/master/modules/aws_launch_configuration/main.tf should likely be combined, so that the former can reference the latter directly. 

So this:

    launch_configuration = "${var.launch_configuration}" 

becomes:

    launch_configuration = "${aws_launch_configuration.aws_launch_configuration.name}"

This kind of interpolation allows Terraform to build a dependency graph and correctly determine the order in which resources should be created and destroyed. By referencing the names as you have it currently setup, this will likely work for construction as Terraform at least knows that it needs to create the Launch Configuration first to get the _name_ output from the module, in order to feed that to the ASG module. Constructing them this way however does not establish the dependency between the resources, just in calculating the name. Terraform cannot derive the relationship when it comes to destroying or otherwise modifying. 

Please see the following resources:

- https://www.terraform.io/docs/configuration/interpolation.html
- https://www.terraform.io/docs/internals/graph.html#building-the-graph

**Comment by cheburakshu** [comment]
@catsby I don't think that is accurate.

The autoscaling module (https://github.com/cheburakshu/terrakube/blob/master/aws.tf#L332) uses an implicit dependency on launch_configuration. 

It is not var.launch_configuration. It is module.launch_configuration! The module wraps the resource and hence there is no need to reference the resource directly.

> `launch_configuration = "${var.launch_configuration}" 
> `

I used [this](https://www.terraform.io/intro/getting-started/dependencies.html#implicit-and-explicit-dependencies) as reference.

**Comment by catsby** [comment]
I made a mistake in assuming the module usage wasn't using the interpolation, my apologies. 

Unfortunately I'm not able to reproduce this yet. I created a minimal reproduction using modules to demonstrate that Terraform using properly configured modules/resources, will correctly create and destroy resources in the correct order without conflict:

- https://github.com/catsby/asg_lc_destroy

The repo I've shared demonstrates creation and deletion with interpolation are working as expected. Our nightly acceptance tests confirm that Launch Configurations and AutoScaling Groups (without modules) are also working as expected, in regards to creating and destroying and the order of operations. 

If you can find error in my configuration example please let me know. Unfortunately I cannot spend any more time debugging your terrakube configuration , unless you can demonstrate to me that there is an issue beyond misconfiguration there. Please feel free to fork my example code if that's helpful.
