### ISSUE TITLE
Terraform crashes for a  floating point value in `capacity' in azurerm_redis_cache resource

### ISSUE THREAD

**Issue by horsey** [hashicorp/terraform#13884]
### Terraform Version
v0.9.2
### Affected Resource(s)
- azurerm_redis_cache

### Terraform Configuration Files
```hcl
resource "azurerm_redis_cache" "test" {
  name                = "test"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  capacity            = 2.5
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = false

  redis_configuration {
    maxclients = "1000"
  }
}
```

### Panic Output
https://gist.github.com/horsey/0958c4675a3c53098a7415f75abcc261

### Expected Behavior
Terraform should have successfully applied/converged the plan.

### Actual Behavior
I tried to create a Azure Redis resource with a capacity of 2.5GB (a float value, not a integer value) and it creashed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
None.

**Comment by tombuildsstuff** [comment]
Hi @horsey 

Thanks for reporting this.

Unfortunately [the Terraform documentation for Redis Cache](https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html) doesn't make this particularly clear - but in this context the field `capacity` is referring to the Redis SKU Size to launch, rather than the amount of memory allocated to the instance.

To better explain that, the value for the field `Capacity` is based on the `Cache Name` from [the Redis Pricing Page](https://azure.microsoft.com/en-gb/pricing/details/cache/) - where a `Cache Name` of `C2` would translate into a capacity value of `2`. I've opened PR #13893 to update the documentation to better match [the Microsoft documentation](https://docs.microsoft.com/en-us/rest/api/redis/redis).

Looking at your configuration, can you confirm if updating the value for `capacity` to `2` rather than `2.5` provisions the Redis Cache as expected? :)

Thanks!

**Comment by horsey** [comment]
@tombuildsstuff, isn't this a bug? Considering that Azure supports Redis caches with 2.5GB capacity, and it looks like the resource in question is not handling floating point values? 
https://azure.microsoft.com/en-in/pricing/details/cache/

**Comment by horsey** [comment]
@tombuildsstuff you're right!  I think I completely misunderstood Capacity with Memory of the Redis instance.

**Comment by tombuildsstuff** [comment]
@horsey cool, thanks for confirming that - I'm hopeful that PR #13893 helps to clarify this documentation going forward. I'm going to close this issue in the interim :)
