### ISSUE TITLE
Unable to update tags (OR the lack of tags support)  for the azurerm_redis_cache resource

### ISSUE THREAD

**Issue by horsey** [hashicorp/terraform#13892]
### Terraform Version
v0.9.2

### Affected Resource(s)
azurerm_redis_cache

### Terraform Configuration Files
```hcl
resource "azurerm_redis_cache" "redis" {
    name                = "redis1"
    location            = "East US"
    resource_group_name = "${azurerm_resource_group.production.name}"
    capacity            = 1
    family              = "C"
    sku_name            = "Standard"
    enable_non_ssl_port = false

    redis_configuration {
        maxclients = "1000"
    }

    tags {
        role = "redis"
        environment = "production"
    }
}
```

### Debug Output
https://gist.github.com/horsey/355b4caa85cb10b3135d828fc554c63b

### Panic Output
None

### Expected Behavior
The tags updated  inside  the .tf file should reflect on the resource. 

### Actual Behavior
Terraform converges successfully saying that the tags were updated, but one can't see the tags on the portal. 

### Steps to Reproduce
1. Create a azurerm_redis_cache resource with empty tags.
2. Converge the resource successfully.
3. Update tags as shown in the snippet above. 
4. `terraform apply`

### Important Factoids
When the azurerm_redis_cache resource was converged for the first time, the resource did not have any tag field absolutely.  It was not checked if the tags were added to the resource for the first time.

### References
None.

**Comment by tombuildsstuff** [comment]
Hi @horsey 

Thanks for reporting this issue.

I've spent some time looking into this - and from what I can see this looks like a bug in the Redis API (we're posting the updated Tags to the API, but it looks like it's not being set, even after a ~15m delay to allow for an eventual consistency issue).

In order to get this fixed, [I've opened an issue about the Redis API](https://github.com/Azure/azure-rest-api-specs/issues/1152). Unfortunately, given this is an API issue, there's not a great deal we can do to work around this in the interim - sorry :(

Once that's fixed, we'll also going to add a test to cover this use-case - apologies for the inconvenience here :(

Thanks!
