### ISSUE TITLE
AWS Provider key_name in instances only loads the first key.

### ISSUE THREAD

**Issue by kendawg2** [hashicorp/terraform#1391]
Although Terraform does not complain if key_name is used more than one in aws_instance, it only loads the first key.   It would be very useful to be able to add multiple keys to root.   On large infrastructures it is quite common to have several people working at the same time.   

So if it could be used more than once in an instance, that would be good, or if it could be a list, that would be just as good.

**Comment by tricker** [comment]
:+1:

**Comment by apparentlymart** [comment]
The public key part of a key pair is an OpenSSH authorized_keys entry, so I wonder (but an not close enough to a computer to test) whether you can put multiple keys in there separated by newlines, with the goal of having them all get written into the authorized_keys file together?

**Comment by apparentlymart** [comment]
Thanks for this request @kendawg2, and sorry for letting it sit here ignored for so long.

Terraform here is reflecting a limitation of the underlying EC2 API, which only allows a single keypair to be selected for instance boot. Supporting additional users requires modifying files within the instance's filesystem, which is not something that Terraform is built to do.

There are some options here:

* Use a `remote-exec` provisioner to run some sort of configuration management tool on your new instance that installs the users and keys you need.

* Use an AMI that is able to populate users based on the value of `user_data` and pass in that data from Terraform. Many "standard" AMIs, e.g. the official Ubuntu ones, use `cloud-init` to process `user_data` which allows, amongst many other features, [specifying users and groups](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups)

* Use AWS OpsWorks, which has its own set of resources in Terraform. OpsWorks is essentially a managed solution for running Chef on EC2 instances, and one of its features is to install a consistent set of users and SSH keys on all of the hosts within a stack. OpsWorks supports both some pre-defined machine configurations for common software, like a web server ready to run a PHP application, and the ability to upload your own Chef recipes for more custom configurations.

Aside from the above solutions, which are all already possible in Terraform, there unfortunately isn't anything more Terraform can do to support your use-case due to the design of EC2 itself. I'm therefore going to close this. Thanks again for opening this request!
