### ISSUE TITLE
module source ref=TAG not freshening local module on a terraform get.

### ISSUE THREAD

**Issue by LudwigHoff** [hashicorp/terraform#13981]
### Terraform Version
0.9.3

### Affected Resource(s)
module

### Terraform Configuration Files
```hcl
module "neil_test" {
  source = "git::http://my-stash/scm/foo/module.bar.git?ref=TAG_NAME"
}
```

### Debug Output
https://gist.github.com/LudwigHoff/be196196a6cfb498915dd0f1ce24406c

### Panic Output
n/a

### Expected Behavior
If the [ref](https://www.terraform.io/docs/modules/sources.html#ref) is a tag, then an
```
terraform get -update=true
```
where the commit this tag this points to has changed i.e. a deliberately mutable tag (e.g. SNAPSHOT or LKG) should freshen.

### Actual Behavior
If the [ref](https://www.terraform.io/docs/modules/sources.html#ref) is a tag, then an update to that tag i.e. a deliberately mutable tag (e.g. SNAPSHOT or LKG) does not get freshened.  (This **_does_** work OK if the ref is a branch.)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. a module with a source whose ref is a tag
2. terraform get
3. update the tag to point to a new commit
4. terraform get -update=true

### Important Factoids
Not that I can think if.

### References
n/a

**Comment by LudwigHoff** [comment]
Obviously there is an easy workaround:

```
rm -rf .terraform/modules && terraform get
```

but raising this as this is a nasty little gotcha if you don't know it is there.

**Comment by ppuschmann** [comment]
@apparentlymart Is [go-getter](https://github.com/hashicorp/go-getter) update / changed in the meanwhile? Or is/was there any issue at go-getter we can link this issue to?

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
