### ISSUE TITLE
Add Command Execution Data Source

### ISSUE THREAD

**Issue by Miserlou** [hashicorp/terraform#14050]
This ticket is a descendant of #13991 .

There should be a data source for executing a command and getting the standard output.  Currently, using `data "external"` requires using a bizarre, non-standard JSON variant, so any programs used by that data source have to specially written or modified to conform to that "standard."

Instead, there should be a data source which simply reads normal UNIX stdout, so that it can be used with all standard UNIX distributions without and modifications, which is obviously a far more common use case than a program which happens to speak Terraform-JSON.

Looking at the history of past and present hacks recommended to achieve this functionality, it's really peculiar that this hasn't been implemented yet. 

Call a program, get the output. Really simple stuff.

**Comment by ThisGuyCodes** [comment]
There is a strange workaround to this:
```hcl
resource "null_resource" "data_cmd" {
  triggers {
    always_changes = "${uuid()}"
  }
  provisioner "local-exec" {
    command = "some-command > iterim.txt"
  }
}
resource "null_resource" "data_file" {
  triggers {
    data = "${file("iterim.txt")}"
  }
}
```

which I think if anything highlights how silly this is

**Comment by apparentlymart** [comment]
In the meantime since this issue was opened, all of the providers except the built-in "terraform" provider have moved into their own separate repositories and are developed independently of Terraform CLI and Core.

Therefore to complete this issue would involve either adding this functionality to an existing provider or creating a new one. There are some community providers in the Terraform Registry that claim to offer something like what's described here, although I've not tried them myself so I cannot vouch for any specific one. 

The `external` provider was built around the limitations of much older versions of Terraform that were not well-equipped to perform parsing operations directly in the Terraform language, and so that provider has a JSON parser embedded in it as the original writeup describes. That design is not very well suited to modern Terraform where JSON parsing could be performed on a single string returned by a data source, but the `external` provider remains as it is for backward compatibility. Other providers are likely to be a better choice for modern Terraform.

Since there's nothing we would change in _this_ repository to introduce a data source like what is described, I'm going to close this. However, this might be a reasonable feature request to open in an existing provider codebase.
