### ISSUE TITLE
Garbled error output

### ISSUE THREAD

**Issue by OliverCole** [hashicorp/terraform#14112]
### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
Multiple. Core issue?

### Terraform Configuration Files
For example. Also reproducible with other resources/configs.

```hcl
resource "aws_s3_bucket" "config_bucket" {
  bucket = "LambdaBackend-dev-config"
  acl    = "private"

  tags {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

resource "aws_s3_bucket_object" "env_production" {
  bucket = "${aws_s3_bucket.config_bucket.bucket}"
  key    = "production/env-config.json"
  source = "env-config-production.json"
  kms_key_id = "${aws_kms_key.LambdaBackend_S3.arn}"
}
```

### Debug Output
https://gist.github.com/OliverCole/8bfb3f56fc5cc24474b4b6c96e31b123

### Panic Output
No panic.

### Expected Behavior
Readable error message.

### Actual Behavior
```
  Ewrreobrs iatpep_leynidnpgoi nptl:a n :
 "
" 1= >e r"r<orc(so) mopccuurtreedd:
>"

* aws_s3_bucket.config_bucket: 1 error(s) occurred:

* aws_s3_bucket.config_bucket: Error validating S3 bucket name: only lowercase alphanumeric characters and hyphens allowed in "LambdaBackend-dev-config"
```

Reruns produce a different output: eg

```
  Ewrreobr saiptpleyi_nge ndplpaoni:n
t:
  1  "e"r r=o>r( s"<)co mpoutced>c"u
rred:
```

### Steps to Reproduce
1. `terraform apply`

Reproduces in Windows command prompt and cmder/conemu.

### Important Factoids
None.

### References
None.

**Comment by apparentlymart** [comment]
Hi @OliverCole! Sorry about this.... very strange behavior.

It looks like two or more messages are getting interleaved in the output. I wasn't able to tear them apart entirely but from your second message I deleted different characters from different copies and recovered some parts of familiar Terraform messages:

```
  Error applying plan:

  1 error(s) occurred:
```

```
  website_endpoint: "" => "<computed>"
```

So this smells like two goroutines trying to write to the console at the same time, and for some reason doing so in a character-by-character way rather than a line-by-line or otherwise buffered way.

**Comment by apparentlymart** [comment]
It looks like this is the same issue as #11363, so I'm going to close this to consolidate the discussion over there.
