### ISSUE TITLE
provider/azurerm: azurerm_servicebus_namespace does NOT resolve implicit dependencies on apply

### ISSUE THREAD

**Issue by scottzilla** [hashicorp/terraform#14119]
### Terraform Version
0.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_servicebus_namespace

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group}"
  location = "${var.location}"
}

resource "azurerm_servicebus_namespace" "test" {
  # depends_on          = ["azurerm_resource_group.rg"]
  name                = "${var.unique}ServiceBus"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group}"
  sku                 = "standard"
}

resource "azurerm_servicebus_topic" "test" {
  name                = "${var.unique}Topic"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group}"
  namespace_name      = "${azurerm_servicebus_namespace.test.name}"

  enable_partitioning = true
}

resource "azurerm_servicebus_subscription" "test" {
  name                = "${var.unique}Subscription"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group}"
  namespace_name      = "${azurerm_servicebus_namespace.test.name}"
  topic_name          = "${azurerm_servicebus_topic.test.name}"
  max_delivery_count  = 1
}
```

### Debug Output
https://gist.github.com/scottzilla/bc8ac56f52164b29fc94fded77290694

### Expected Behavior
`azurerm_servicebus_namespace` resource to wait until the resource group is created, as it should depend on it.

### Actual Behavior
`azurerm_servicebus_namespace` fails stating the resource group does not exist (since it is still being created)

### Steps to Reproduce
`terraform apply`

### Important Factoids
Public Azure

### Workaround
The resource group is required to be specified in a `depends_on` within the `azurerm_servicebus_namespace` block, but this should be resolved automatically.

**Comment by tombuildsstuff** [comment]
Hi @scottzilla

Thanks for opening this issue :)

The configuration language used in Terraform (HCL) is Declarative, as such dependencies between resources need to be defined either through references (i.e. `azurerm_resource_group.test.name`, or through the `depends_upon` attribute (there's more details on the [Load Order and Semantics](https://www.terraform.io/docs/configuration/load.html) page).

In the case of the configuration pasted above - there's a relationship defined between `azurerm_servicebus_namespace` -> `azurerm_servicebus_topic` -> `azurerm_servicebus_subscription` - however the `azurerm_resource_group` has no relationships to the order resources, as shown in the resource ordering graph below:

![original](https://cloud.githubusercontent.com/assets/666005/26394839/2901a686-4066-11e7-91de-4cd77a92e344.png)

Changing the references to the resource group to reference `${azurerm_resource_group.rg.name}` rather than `${var.resource_group}` will ensure the resources are created in the correct order:

```
resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group}"
  location = "${var.location}"
}

resource "azurerm_servicebus_namespace" "test" {
  name                = "${var.unique}ServiceBus"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  sku                 = "standard"
}

resource "azurerm_servicebus_topic" "test" {
  name                = "${var.unique}Topic"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  namespace_name      = "${azurerm_servicebus_namespace.test.name}"
  enable_partitioning = true
}

resource "azurerm_servicebus_subscription" "test" {
  name                = "${var.unique}Subscription"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  namespace_name      = "${azurerm_servicebus_namespace.test.name}"
  topic_name          = "${azurerm_servicebus_topic.test.name}"
  max_delivery_count  = 1
}
```

As mentioned above it's also possible to set the `depends_upon` attribute - which in either case gives the resource ordering graph:

![updated](https://cloud.githubusercontent.com/assets/666005/26394863/369a14a4-4066-11e7-8b32-18c5c4267a64.png)

Can you confirm if updating the reference to the resource group solves this issue?

Thanks!

**Comment by scottzilla** [comment]
Oh duh, I'm referencing a variable, not the resource group; rookie mistake, hate to see it. 😆 

Thanks @tombuildsstuff, sorry to waste your time!

**Comment by tombuildsstuff** [comment]
Hi @scottzilla 

Not at all, thanks for raising this issue - I'm going to close this out for now :)

Thanks!
