### ISSUE TITLE
Dynamically updated Route53 records are not destroyed

### ISSUE THREAD

**Issue by willmcg** [hashicorp/terraform#1413]
I have a configuration in which I create a bunch of A records in route53 into pre-existing hosted zones (both public and private). These creation of these records is intended to be managed by Terraform, but they are dynamically updated during runtime (not by Terraform) to point to instances created by autoscaling groups as necessary.

This is all working great with the exception of destruction of these A records when tearing down with Terraform. Terraform reports that all the resources, including the A records, were destroyed successfully but the A records still exist in route53.

I suspect this is because the original placeholder IP address for the A records was changed outside of Terraform and that it is submitting a Route53 change-set to delete the record with the original IP address as the record value. Because Route53 finds no matches for the original values, it does nothing.

**Comment by catsby** [comment]
What properties of the Route 53 record are being updated? 
Do you have any additional how-to steps so I can try and reproduce this?
What steps are you taking to attempt to destroy them?
Thanks!

**Comment by willmcg** [comment]
The properties of the record that would be changed are the IP and the comment. The cut-down version of the Boto python code that does the out-of-band update is this:

    zone = route53_conn.get_zone('example.com.')
    zone.update_a('server.example.com', '10.0.5.5', ttl=60, comment="Updated by DNS utility")

The placeholder record in the Terraform configuration looks like this:

    resource "aws_route53_record" "server" {
        zone_id = "${var.dns-zone-public}"
        name    = "server.example.com"
        type    = "A"
        ttl     = "60"
        records = [
            "10.0.0.1"
        ]
    }

To destroy them I have to either go to the AWS Route53 console and do it manually or run a clean-up script to delete them.

**Comment by catsby** [comment]
Pretty sure I've reproduced this now, working on a fix

**Comment by catsby** [comment]
I've found the issue(s) and have sent a PR to address this (#1430).

There is a bug in our Route 53 Record code that happens we update our state file with what AWS reports. We were incorrectly storing the `records` (IP addresses, for example) for each Route 53 Record. Unfortunately we were ignoring this error, so nothing was changing. 

In the event(s) you describe (updating externally), any `terraform plan` _should_ have noticed the changes and stored them in the state file, then generated a plan to make the remote and config match. In this case, it _should_ have picked up the new IP address, stored it in the state, and then output a plan to change it back to match the config. The bug however prevented the records from being updated, so it didn't notice a change.

This also caused issues with deletion. When trying to delete, we sent a request with the record information we have in the state, which no longer matched what Route 53 had. Because they didn't match, Route 53 rejected the deletion. We then incorrectly assumed the record was deleted :frowning: 

In #1430, we correctly update the Route 53 record in state, and subsequent plans detect the difference. Destroy's should also now work, because we send the correct information. 

Please let me know if this doesn't resolve things, and thanks for opening the issue!

**Comment by willmcg** [comment]
I've run this change against my full configuration and can confirm that the modified DNS A records are now being correctly deleted during destroy.

Thanks! You guys rock.

This pace of evolution and responsiveness to issues is why I chose Terraform.

**Comment by NicolasMas** [comment]
Is this ticket still opened? I am experimenting it with Terraform v0.6.3. Whatever dynamic route53 dns created will still be there after a terraform destroy. (Should I create a new ticket?)
