### ISSUE TITLE
Error in output claims to be a terraform bug.  Two runs successfully apply the template.

### ISSUE THREAD

**Issue by polliard-jmfe** [hashicorp/terraform#14177]
### Terraform Version
0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_key_pair.keypair
- null_resource.ssh
- null_resource.ssh-keygen

### Terraform Configuration Files
```hcl
resource "null_resource" "ssh" {
  triggers = {
    public-keyname = "${var.DeploymentStage}_${var.AppName}-${var.AppId}.pub"
    private-keyname = "${var.DeploymentStage}_${var.AppName}-${var.AppId}"
  }
}

resource "null_resource" "ssh-keygen" {
  depends_on = [
    "null_resource.ssh"
  ]

  provisioner "local-exec" {
    command = <<EOC
      echo -e  'y\n' | ssh-keygen -t rsa -b 4096 -f ${null_resource.ssh.triggers.private-keyname} -N ''
      # vault write secret/environment-ssh-keys/${null_resource.ssh.triggers.private-keyname} private=@${null_resource.ssh.triggers.private-keyname} public=@${null_resource.ssh.triggers.public-keyname}
    EOC
  }

  provisioner "local-exec" {
	  when = "destroy"
	  command = <<EOC
        rm ${null_resource.ssh.triggers.public-keyname} ${null_resource.ssh.triggers.private-keyname}
        # vault delete secret/environment-ssh-keys/${null_resource.ssh.triggers.private-keyname}
    EOC
  }
}



# This is the public_key name that was uploaded to AWS that should be deployed as the ec2-user key to allow
# ssh access for a UNIX machine or on a windows machine the key used to allow retrieval of the Administrator password.
resource "aws_key_pair" "keypair" {
  key_name   = "${null_resource.ssh.triggers.private-keyname}"
  public_key = "${file(null_resource.ssh.triggers.public-keyname)}"
  depends_on = ["null_resource.ssh-keygen"]
}
```

### Debug Output
https://gist.github.com/polliard-jmfe/32175b67e49004161f53940b46b958ea

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?  The second run in the log shows the expected behavior. The key generated and the template to successfully complete.

### Actual Behavior
Requires two runs to successfully complete due to an error that states its a terraform bug.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by polliard-jmfe** [comment]
After spending some time playing with this, I think the root cause is the need for the file() to have the file already exist.  I think what is happening is that prior to the apply, terraform seems to plan/validate the template and when it does it requires the filename to exist.  This force the existence of an empty file, that then is validated/planned but when the actual apply runs the file is updated and then when it compares it sees a mismatch.  Is there a different way to handle files other then using the file method for files that won't exist until the apply is run?

**Comment by apparentlymart** [comment]
Hi @polliard-jmfe! Sorry for the long silence here.

It sounds like you correctly inferred that the `file` function executes as part of configuration loading rather than during apply time. It's intended for reading files that are provided statically along with the configuration, rather than for generated files.

At the time you opened this issue there wasn't a great answer beyond that, but in the mean time we've added [the `local` provider](https://www.terraform.io/docs/providers/local/index.html) which has [the `local_file` data source](https://www.terraform.io/docs/providers/local/d/file.html) that serves as a way to read files that participates in the dependency graph.

In order to use it in your example it's necessary to include an interpolation of a value from the `null_resource` so that Terraform can tell that the data source must wait until the null resource is complete, like this:

```hcl
resource "null_resource" "ssh-keygen" {
  depends_on = [
    "null_resource.ssh"
  ]
  triggers = {
    filename = "${path.module}/${null_resource.ssh.triggers.private-keyname}"
  }

  provisioner "local-exec" {
    command = <<EOC
      echo -e  'y\n' | ssh-keygen -t rsa -b 4096 -f ${self.triggers.filename} -N ''
      # vault write secret/environment-ssh-keys/${null_resource.ssh.triggers.private-keyname} private=@${null_resource.ssh.triggers.private-keyname} public=@${null_resource.ssh.triggers.public-keyname}
    EOC
  }

  provisioner "local-exec" {
	  when = "destroy"
	  command = <<EOC
        rm ${null_resource.ssh.triggers.public-keyname} ${null_resource.ssh.triggers.private-keyname}
        # vault delete secret/environment-ssh-keys/${null_resource.ssh.triggers.private-keyname}
    EOC
  }
}

data "local_file" "key" {
  # This creates the dependency on null_resource.ssh-keygen, telling
  # terraform to read this only during apply if the null_resource didn't run yet.
  filename = "${null_resource.ssh-keygen.triggers.filename}"
}

resource "aws_key_pair" "keypair" {
  key_name   = "${null_resource.ssh.triggers.private-keyname}"
  public_key = "${data.local_file.key.content}"
  depends_on = ["null_resource.ssh-keygen"]
}
```

Note that since provisioners only run on create, any time you re-apply this configuration for updates you'd need to ensure that the file generated on the first create is still available, which is inconvenient if you have multiple team members working on the same configuration. Another option for this particular use-case is to use [`tls_private_key`](https://www.terraform.io/docs/providers/tls/r/private_key.html) to generate a key directly within Terraform itself, saving it in the Terraform State.

Note that _all_ of these different approaches result in the state file containing the private key, so it's important to think about the issues and recommendations on [the _Sensitive Data in State_ guide](https://www.terraform.io/docs/state/sensitive-data.html).

Since there are now solutions to this available, I'm going to close this out. Thanks for reporting it, and sorry for the delay in responding.
