### ISSUE TITLE
No way to create regional gcp backend service

### ISSUE THREAD

**Issue by datianshi** [hashicorp/terraform#14178]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.9.4
### Affected Resource(s)
google_compute_backend_service

### Terraform Configuration Files
```
resource "google_compute_backend_service" "lb" {
  name        = "lb"
  description = "Target my instance"
  port_name   = "http"
  protocol    = "HTTP"
  timeout_sec = 10
  enable_cdn  = false

  backend {
    group = "${google_compute_instance_group.webservers.self_link}"
  }
  region = "us-east1"

  health_checks = ["${google_compute_http_health_check.lb.self_link}"]
}
```

### Debug Output

```
google_compute_backend_service.lb: "region": [DEPRECATED] This parameter has been removed as it was never used
```

### Expected Behavior

I would expect to create a regional backend service

### Actual Behavior

Looks like there is no way to create a regional backendservice

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

GCP now supports internal load balancing (Non internet facing)
https://cloud.google.com/compute/docs/load-balancing/internal/
But have to create a backend service with scope regional instead of global

**Comment by danawillow** [comment]
Hey @datianshi, you can actually use the [Region Backend Service](https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html) resource for this. (We decided to make it a separate resource to keep it close to the way the Google API defines it).

I'm going to leave this open because I do think we should add some documentation, both in that error message (to point users to the right place) and in the docs for backend service itself. Thanks for the report!

**Comment by datianshi** [comment]
Got it.... thanks a lot

**Comment by josh-padnick** [comment]
Reviving an old thread because it took me a bit to figure out what was going on. While setting up a TCP Proxy Load Balancer, I received this error:

```
* google_compute_forwarding_rule.default: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.backendService': 'https://www.googleapis.com/compute/v1/projects/vault-999999/global/backendServices/josh-vault'. Scope mismatch between forwarding rule and backend service, forwarding rule scope: region us-west1, backend service scope: global., invalid
```

My HCL was as follows:

```hcl
resource "google_compute_forwarding_rule" "default" {
  ...
}

resource "google_compute_backend_service" "vault" {
  ...
}
```

What's confusing here is that there are resources for:

- `google_compute_forwarding_rule` and `google_compute_global_forwarding_rule`
- `google_compute_backend_service` and `google_compute_region_backend_service`

So I actually needed the following to configure things correctly. 

```hcl
resource "google_compute_forwarding_rule" "default" {
  ...
}

resource "google_compute_region_backend_service" "vault" {
  ...
}
```

I would have expected the "default" resource to be global in all cases or regional in all cases, but not a mix. Since fixing this probably can't justify a breaking change, perhaps consider amending the error message to suggest another Terraform resource to try.

**Comment by danawillow** [comment]
Hey @josh-padnick, the `googleapi` there in the error message means that we've forwarded the error message directly from GCP. So unfortunately, that's not wording that we can change in Terraform. I agree that the resources could be named more clearly, but they're in line with what GCP publishes: https://cloud.google.com/compute/docs/reference/rest/v1/. There's probably stuff we can do easily in the documentation to make this more clear on the Terraform side. If you have any ideas or just want to make sure it's on our radar, I'd recommend filing an issue or PR in the google-specific provider repo: https://github.com/terraform-providers/terraform-provider-google.

**Comment by awolde** [comment]
@josh-padnick Did you find a way to fix your issue? I have the same problem. All I want is have an external load balancer that will forward traffic to internal vault nodes. It's 2020 and the issue still lingers :) @danawillow any example on how to do tcp load balancing would be nice. It's straightforward on GCP console.

**Comment by danawillow** [comment]
@awolde check out https://github.com/terraform-google-modules/terraform-google-lb
