### ISSUE TITLE
aws_instance tag does not work version: v0.9.4

### ISSUE THREAD

**Issue by shamimgeek** [hashicorp/terraform#14183]
Hi all creator,

i am getting below error while creating instance with tag. However, if i remove tags block it works fine. 

### Terraform Version

Terraform v0.9.4

### Affected Resource(s)

- aws_instance 
  - tags

### Terraform Configuration Files
```
provider "aws" {
  access_key = "xxxxxxxxxxxxxxxxxxx"
  secret_key = "xxxxxxxxxxxxxxxxxxxxxxx"
  insecure  = true
  skip_credentials_validation = true
  skip_region_validation = true
  region = "eucalyptus"
  endpoints {
    ec2 = "http://compute.xxxxxxxxxxxxxxxxx:8773"
    iam = "http://iam.xxxxxxxxxxxxxxxxxx:8773"
    elb = "http://compute.xxxxxxxxxxxxxxx:8773"
  }
}

resource "aws_instance" "example" {
  count = 1
  ami           = "emi-6962b3cf"
  instance_type = "m1.medium"
  availability_zone = "es-ka-eu-dhn-09_2"
  key_name = "sakhtar" 
  tags {
    Name = "master-sakhtar-002"
    Role = "master"
    Hostname = "master-sakhtar-002"
    PaaS-name = "sakhtar"
    Master-nb = 2  	
  }

}

```

### Debug Output

https://gist.github.com/shamimgeek/ed44afeacec9c15713708650cb0d3c7e

**Comment by tomelliff** [comment]
I'd guess it's because of https://github.com/hashicorp/terraform/pull/13945 and Eucalyptus not supporting the [new tagging on creation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TagSpecification.html).

**Comment by shamimgeek** [comment]
+ in addition to this
I checked with older version Terraform v0.9.2 and it is working fine with this version. 

 **## apply output** 

https://gist.github.com/shamimgeek/5b621852e0e537cc004dd58aacc02b40

**Comment by stack72** [comment]
Hi @shamimgeek 

Currently support for these "AWS-like" platforms using the AWS provider is on a "best effort" basis: we try to build the AWS provider in such a way that it's possible to configure it to work, but the UX isn't optimized (i.e. it requires some verbose configuration, as seen above) and we don't pro-actively run the automated acceptance tests against these other platforms.

Since AWS is not intended to be a "standard", these other platforms often have subtle- and not-so-subtle incompatibililties which we try to address but can't always catch. If anyone finds bugs with or blockers for using these other workalike platforms with the AWS provider they are welcome to open a Github issue about it, though since we don't necessarily all have ready access to these platforms ourselves it helps a lot if the requester can share as much information as possible about what's going on and what the solution might be. We are also very happy to review PRs for changes to make these alternative platforms easier to use, as long as they don't hurt the UX and behavior when talking to the real AWS APIs.

Sorry for the bad news here

@stack72
