### ISSUE TITLE
Feature request: Kapacitor / TICK provider

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#14213]
A Kapacitor provider would allow users to manage Kapacitor TICK scripts with Terraform. 

This would be similar intent as the Datadog provider.

There is an existing InfluxDB provider but it's somewhat limited. Alternatively, maybe there should be a single `TICK` provider that manages all components of the TICK stack (Telegrah, InfluxDB, Chronograf, Kapacitor).

### References

- [kapacitor#1313](https://github.com/influxdata/kapacitor/issues/1313) - Load tick scripts from a dir
- [InfluxDB Provider](https://www.terraform.io/docs/providers/influxdb/index.html)
- [Kapacitor HTTP API Reference](https://docs.influxdata.com/kapacitor/v1.2/api/api/) (TICK docs are amazing)

**Comment by stack72** [comment]
Hi @devth,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

@stack72

**Comment by mkuzmin** [comment]
Hi @devth 
Check out my provider for Kapacitor tasks at https://github.com/mkuzmin/terraform-provider-kapacitor

It's pretty basic, but I'd love to hear your feedback.

There are precompiled binaries at [Releases](https://github.com/mkuzmin/terraform-provider-kapacitor/releases) page.
