### ISSUE TITLE
Allow an easy to follow convention for managing separate staging and production environments

### ISSUE THREAD

**Issue by woodhull** [hashicorp/terraform#1422]
There is no suggested convention for managing a single infrastructure configuration that has multiple different environments. 

We maintain separate tfstate files for staging, production, (and soon, long running feature branches) -- we've written our own workflow for this, but a standardized convention recommended by hashicorp would be nice. 

How should we arrange the tfstate files? Shouldn't terraform have a straightforward way that the same recipe might be applied to different environments?

**Comment by willejs** [comment]
:+1:

**Comment by radeksimko** [comment]
Related https://github.com/hashicorp/terraform/issues/1295

**Comment by dschaaff** [comment]
+1

**Comment by pmoosh** [comment]
:+1:

**Comment by satvidh** [comment]
+1

**Comment by krisdigitx** [comment]
+1

**Comment by mooperd** [comment]
+1

**Comment by teamterraform** [comment]
Hi all! It's been a while with this one; sorry for the long silence.

In the time since this was originally opened, we observed a number of different approaches and concluded that there isn't a single solution that fits all situations, but we do now have some more specific recommendations for different use-cases:

The main case, and the default we'd recommend for anyone unsure about how to choose between these options, is to factor out the common elements between environments into one or more child modules and use [module composition](https://www.terraform.io/docs/modules/composition.html) for a separate configuration (and, along with it, a separate backend+state) in each environment. This gives the most flexibility in modelling any differences between the environments, particularly over time as needs inevitably evolve and different change-management strategies are needed for production environments vs. less valuable environments.

For simpler situations where infrastructure is largely identical between environments, [Workspaces](https://www.terraform.io/docs/state/workspaces.html) offer a built-in solution for easily associating multiple named states with a single configuration and switching between them. The documentation on that page describes some situations that Workspaces are particularly good for, but it also suggests caution in more complex scenarios.

In practice, we've seen some teams employ a combination of these techniques: the biggest variance between tends to be in the low-level infrastructure, where perhaps production has a significantly more complex network architecture and stricter security rules while development environments tend to be simpler. Teams can use the one-configuration-per-environment technique for this low-level infrastructure, but then split higher-level per-application infrastructure into separate configurations that use multiple workspaces, using [data-only modules](https://www.terraform.io/docs/modules/composition.html#data-only-modules) to access information about the shared lower-level infrastructure.

This advice is likely to continue to evolve as we hear more feedback from operators, so a task like this is never really "done". However, we hope the above is useful as a current set of recommendations to build on, and so we're going to close out this issue now while keeping an eye out for possible improvements to this advice in the future. Thanks for starting this discussion!
