### ISSUE TITLE
State file shows initial public_ip and not an eip

### ISSUE THREAD

**Issue by alexclifford** [hashicorp/terraform#1425]
During the initial creation (for example during https://www.terraform.io/intro/getting-started/provision.html) if you have an EC2 instance with an EIP associated to it during apply `terraform show` lists the public_ip as what is presumably the IP address before the EIP is attached. Re-running `terraform refresh` fixes the state file. Should this detail be correct on first orchestration?

**Comment by robertfirek** [comment]
I have similar issue with my outputs. These outputs generate different public_ip during the first apply. The second apply fix that issue and output contains the right values. Adding depends_on doesn't help. 

resource "template_file" "example_template" {
    depends_on = ["aws_eip.some_instance"]
    filename = "template-some_instance"
    vars {
        some_instance_public_ip     = "${aws_instance.some_instance.public_ip}"
    }
} 

output "public_ips" {
    value = "${template_file.example_template.rendered}"
}

**Comment by phinze** [comment]
Hey folks, definitely see the issue here. Terraform is simply reflecting the upstream behavior of the AWS API, which changes the reported value of `PublicIP` after an EIP is attached.

Since the `aws_eip` is attached after the `aws_instance` resource is fully created, Terraform doesn't have any way of knowing that one of those attributes will report differently, nor do we currently have any core facilities for "revisiting" a node after a downstream change has occurred.

I'm wondering if this is a scenario that we can handle with a documentation warning on the field? Something like:

 > If you are using an `aws_eip` with an instance, you should refer to the EIP's address directly and not use public_ip, as it will change after the EIP is attached.

What do you think?

**Comment by alexclifford** [comment]
Hi @phinze,
Thanks for reviewing this and your explanation of how this interacts with the AWS API.
Until Terraform can refresh its state for aws_instance, after an aws_eip action updates it, the documentation workaround seems good to me.
