### ISSUE TITLE
Suggestion: Documentation discoverability

### ISSUE THREAD

**Issue by OliverCole** [hashicorp/terraform#14266]
When browsing the documentation for a resource, it would be very helpful if related resources were more easily accessible. 

For example, if I'm browsing [aws_network_acl](https://www.terraform.io/docs/providers/aws/r/network_acl.html), it's likely that I might want to browse [aws_network_acl_rule](https://www.terraform.io/docs/providers/aws/r/network_acl_rule.html) next.

But to do so I have to either scroll down the massive list on the left of the page, or use a browser search.

Some options:
- Link the resource names in code examples in child resources so you can at least go back from, e.g. [aws_network_acl_rule](https://www.terraform.io/docs/providers/aws/r/network_acl_rule.html) to [aws_network_acl](https://www.terraform.io/docs/providers/aws/r/network_acl.html).
- Bump the current resource category (term?) up to the top of the left hand list
- Repeat the entire category list underneath the resource documentation, e.g. "See also:"

**Comment by OliverCole** [comment]
I might be able to take care of this myself. Will open a PR if I get anywhere.

**Comment by grubernaut** [comment]
@OliverCole, @sethvargo may have some suggestions as to where to start, or he may have a plan for this already. Would be worth it to check in with them and verify.

**Comment by sethvargo** [comment]
Something _like_ this is coming very shortly:

![terraform-filter-none 2x](https://cloud.githubusercontent.com/assets/408570/25861494/ef6b4f8a-34b2-11e7-876f-5c77a9e9a0fb.jpg)
<img width="1258" alt="terraform-filter" src="https://cloud.githubusercontent.com/assets/408570/25861495/ef6d2288-34b2-11e7-9515-6fa6d6d3453c.png">
![terraform-filter 2x](https://cloud.githubusercontent.com/assets/408570/25861497/ef7206a4-34b2-11e7-8eee-f4566e5d251b.jpg)
![terraform-hierarchy 2x](https://cloud.githubusercontent.com/assets/408570/25861498/ef721f68-34b2-11e7-9c9e-6951f351a1a8.jpg)
![terraform-provider-child 2x](https://cloud.githubusercontent.com/assets/408570/25861499/ef75fbba-34b2-11e7-96b8-b35004b9732e.jpg)
![terraform-provider 2x](https://cloud.githubusercontent.com/assets/408570/25861496/ef71c1e4-34b2-11e7-832b-150a2bdc619c.jpg)

There will also be global site search to jump from aws to gcp, for example. We are working on this internally (design wise) a bit before we open it up for public discussion though. I would appreciate if you hold any feedback until we've finalized the design and implementation (hopefully this month). Thanks!

**Comment by OliverCole** [comment]
Hey @sethvargo - how is this coming along?

**Comment by apparentlymart** [comment]
Hi @OliverCole, and anyone else watching here.

The changes in Seth's screenshots above did not get implemented, as I'm sure everyone has noticed. We unfortunately had to make some compromises in how the website is built to support the core/provider split and since the primary concern has been working towards making that process more tenable now that providers have their own release cycles separate from core. This will cause the website to be built in a pretty different way, and so we're going to hold off on any significant changes to the design and functionality of it until that work is complete.

The most pressing goal right now is to have each provider's documentation be deployed separately on its own release cycle. This can in turn allow versioned documentation, so that older provider versions can be documented on the website along with the latest. We are still discussing the best way to achieve this goal, and the outcome of that will in turn inform how we might approach implementing this sort of site navigation change so that it can apply to both current and historical versions of the documentation, etc.

More information on this will come once we have it.
