### ISSUE TITLE
Editing name or description of Security Group deletes EC2 instance

### ISSUE THREAD

**Issue by alexclifford** [hashicorp/terraform#1428]
Is it possible to edit the name or description of an AWS Security Group (for example in https://github.com/hashicorp/terraform/blob/master/examples/aws-two-tier/main.tf) and do it in-line without re-creating the entire EC2 instance it is applied to?

I'm aware there may be some API limitations here but could you create another group and then apply it to the instance then remove the old group? I feel like there should be some more smarts in here so entire resources don't need to be re-created from such a trivial change.

**Comment by catsby** [comment]
Hey @alexclifford – sorry for the long, long silence here :smile: 

You've linked to the master branch version of that main.tf file and I fear it's changed since. The example shown does allow you to update the name of a security group and _not_ destroy the instance: 

```
~ aws_instance.web
    vpc_security_group_ids.#: "" => "<computed>"

-/+ aws_security_group.default
    description:                          "Used in the terraform" => "Used in the terraform"
    [...]
    name:                                 "terraform_example" => "terraform_example_debug" (forces new resource)
    [...]

Plan: 1 to add, 1 to change, 1 to destroy.
```

Perhaps when you originally linked that was not the case. I know that, for EC2 instances in a VPC, you can do this update if you're using `vpc_security_group_ids` (not `security_groups`), which may not have been the case when you linked it.

Anyway, sorry again for the silence! Let me know if you need anything else.
