### ISSUE TITLE
changing a template, that is used in a file provisioner, in a null_resource does not result in a tainted resource

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#14290]
### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource
  - (file provisioner)

### Terraform Configuration Files
```hcl

data "template_file" "consul_config" {
  template = "${file("${path.module}/consul_server.json.tpl")}"

  vars {
    datacenter = "${ var.datacenter  }"

    acl_datacenter = "${ var.datacenter}"
    data_dir         = "/var/consul"
    node_name        = "${ element(var.node_names, count.index)  }"
    client_addr      = "${ element(var.private_ips, count.index) }"
    bootstrap_expect = "${length(var.public_ips)}"
    encrypt          = "${ random_id.encrypt_key.b64 }"
    retry_join       = "${ var.retry_join }"

    acl_master_token = "${ random_id.master_token.b64 }"
    acl_replication_token = "${  random_id.master_token.b64 }"
    acl_token = "${ random_id.master_token.b64 }"
    acl_ttl = "300s"
    advertise_addr = "consul.service.consul"
  }
}

resource "null_resource" "configure" {
  count = "${var.num_servers}"

  # provide some connection info
  connection {
    type        = "ssh"
    user        = "root"
    private_key = "${var.ssh_private_key}"
    host        = "${element(var.public_ips, count.index)}"
  }

  provisioner "file" {
    content     = "${data.template_file.consul_config.rendered}"
    destination = "/etc/consul_server.json"
  }
...
}
```

### Expected Behavior
If I make a modification to the content of `${file("${path.module}/consul_server.json.tpl`,  terraform should detect that the `null_resource.configure` resource has changed and re-run it.

### Actual Behavior
terraform did not pick up the change, and did not re-run the resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. change the template content
4. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @dansteen! Sorry things aren't working as you expected here.

Provisioners are dealt with only during the initial creation of a resource, so it's by design that updates to them do not cause them to re-run.

However, since you are using `null_resource` already, you can exploit its `triggers` mechanism to cause the resource to be recreated (and thus its provisioners to re-run) whenever the rendered template changes:

```hcl
resource "null_resource" "configure" {
  count = "${var.num_servers}"

  triggers = {
    template = "${data.template_file.consul_config.rendered}"
  }

  # provide some connection info
  connection {
    type        = "ssh"
    user        = "root"
    private_key = "${var.ssh_private_key}"
    host        = "${element(var.public_ips, count.index)}"
  }

  provisioner "file" {
    content     = "${data.template_file.consul_config.rendered}"
    destination = "/etc/consul_server.json"
  }
...
}
```

Note that the content of `triggers` is opaque to `null_resource` and so you can put whatever you like in here. The rule is just that any time the contents of that map change the resource will be recreated, because changes to that argument "force new resource".

**Comment by dansteen** [comment]
Ah!  I missed that in the docs.   That will do perfectly.  Thanks so much!
