### ISSUE TITLE
Any plan to support terraform import aws_lb_ssl_negotiation_policy?

### ISSUE THREAD

**Issue by chhuang0123** [hashicorp/terraform#14339]
### Terraform Version
terraform 0.9.4

### Affected Resource(s)
- aws_lb_ssl_negotiation_policy

### Debug Output
Error importing: 1 error(s) occurred:

* aws_lb_ssl_negotiation_policy.foo (import id: load_balancer=bar): import aws_lb_ssl_negotiation_policy.foo (id: load_balancer=bar): resource aws_lb_ssl_negotiation_policy doesn't support import

### Expected Behavior
We would like to customize SSL cipher base on existed resources.
May I know terraform team have any plan to implement terraform import command to support aws_lb_ssl_negotiation_policy?
It could import aws_lb_ssl_negotiation_policy by load_balancer's id.

**Comment by apparentlymart** [comment]
Hi @chhuang0123!

Ideally all resources would support import, but naturally the Terraform team only has so much capacity and so must focus on resources that are most commonly used. However, we are always happy to review PRs for new import implementations if members of the community have the time and motivation to work on them.

I'm going to close this not because importing this resource isn't something we want to support, but because it doesn't really scale to have an open issue for every resource that doesn't support import. However, I appreciate you taking the time to let us know of your interest in being able to import resources of this type!

**Comment by chhuang0123** [comment]
ok... thank you so much... :)
