### ISSUE TITLE
Variable cannot contain interpolation?

### ISSUE THREAD

**Issue by olalonde** [hashicorp/terraform#14343]
```hcl
variable "cluster_name" {
  default = "${var.environment}.${var.domain_name}"
}
```

Why is the above not possible and is there a workaround to compute a default variable value from other variables?

**Comment by jbardin** [comment]
Hi @olalonde,

This isn't possible at the moment because of how interpolation in implemented. The default values need to be loaded early on before there is enough context to run the interpolation. While we would like to be able to implement this along with some related functionality, there is no set timeline for this feature.

Similar functionality can be created by using a module to set variables value and return it through the output.

**Comment by andrewsav-datacom** [comment]
>Similar functionality can be created by using a module to set variables value and return it through the output.

@jbardin is there an example?

**Comment by apparentlymart** [comment]
Hi @andrewsav-datacom,

This is a pretty old issue. In the mean time since this discussion, there was a new feature added called [Local Values](https://www.terraform.io/docs/configuration/locals.html) that doesn't address exactly what was requested in this issue, but does serve the most common use-case presented for interpolating into defaults: factoring out repeated expressions to use in multiple places.

We aren't always able to monitor closed/old issues well due to limitations of our tooling, so if you find that your use case isn't served by this feature please feel free to open a new top-level issue referencing this one where we can discuss ways forward.
