### ISSUE TITLE
[bug] AWS provider is not loading role_arn from CLI config file under each profile

### ISSUE THREAD

**Issue by ju2wheels** [hashicorp/terraform#14356]
### Terraform Version
0.9.4

### Affected Resource(s)
- aws provider

### Terraform Configuration Files
```hcl
provider "aws" {}

# My resources here
```
In combinartion with `~/.aws/config`:

```
[profile myprofile]
region = us-east-1
role_arn = arn:aws:iam::000000:role/admin
```

### Expected Behavior
When I run my Terraform module with an empty AWS provider block, I expect that it will use the combination of environment variables and the AWS CLI configuration file profile without having to add an assume_role block with the role_arn property to the AWS provider

Running:

```
AWS_PROFILE=myprofile terraform apply
```

### Actual Behavior
The Terraform AWS provider ignores the profile role specified in `~/.aws/config` and runs it using the AWS credentials for the profile only resulting in it being put in the wrong role.

### Steps to Reproduce
1. Create an AWS CLI config that leverages a role configured per [AWS guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html) under a profile that also has its  credentials configured in `~/.aws/credentials`.
2. Specify the created profile name via AWS_PROFILE environment variable as shown above when running terraform.
3. Run apply on any AWS resource with an empty AWS provider block as shown above and the resource will not be created under the proper role as specified by the profile configuration. Instead the only way to get it to work is to add an assume_role block to the AWS provider.

**Comment by stumyp** [comment]
Need this feature as well, doesn't exist in 0.9.5.
The usecase here would be reusable configuration, where remote state is saved on S3.
Example:
`~/.aws/credentials` contain 2 profiles:
```
[main]
#account ID is 123
aws_access_key_id = xxx
aws_secret_access_key = xxx

[second]
#account ID is 567
source_profile=main
role_arn=arn:aws:iam::567:role/some_role
```
in case of `AWS_PROFILE=second` I expected this code to work:
```
provider "aws" {
  region              = "some-region-1"
  allowed_account_ids = ["567"]
}
```
as well as this one:
```
terraform {
  backend "s3" {
    bucket  = "some-state-bucket"
    key     = "some_key"
    region  = "some-region-1"
  }
}
```
(note, without `role_arn ` setting, it should be imported from profile configuration)

What happens now:
- `provider_aws` fails to check `allowed_account_ids`, seeing "123" instead of "567"
- terraform block also uses `main` configuration, instead of `second`
