### ISSUE TITLE
"terraform plan" output escapes newlines in policy documents, is difficult to read/verify

### ISSUE THREAD

**Issue by kevinburke** [hashicorp/terraform#14409]
### Terraform Version
v0.9.5

### Affected Resource(s)
- aws_iam_role_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "s3_change_permissions_role" {
  name = "s3-change-permissions"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}

```

### Expected Behavior

The goal of "terraform plan" is to let you verify that the plan is correct. It's difficult to do this with policy statements, since newlines are not escaped.

### Actual Behavior
The newlines and spaces appear in the output from "plan":

```
+ module.services.aws_iam_role_policy.s3_change_permissions_policy
    name:   "s3-change-permissions"
    policy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"logs:CreateLogGroup\",\n        \"logs:CreateLogStream\",\n        \"logs:PutLogEvents\",\n        \"logs:DescribeLogStreams\"\n      ],\n      \"Resource\": \"arn:aws:logs:*:*:*\"\n    },\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"s3:GetObject\",\n      ],\n      \"Resource\": [\n        \"arn:aws:s3:::segment-billing-raw-logs/*\"\n      ]\n    }\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"s3:PutObject\"\n      ],\n      \"Resource\": [\n        \"arn:aws:s3:::segment-change-permission-destination-stage/*\"\n      ]\n    }\n  ]\n}\n"
    role:   "${aws_iam_role.s3_change_permissions_role.id}"
```

This makes it difficult to verify that you have correctly specified the policy, especially if you are doing anything with variable interpolation.

### Steps to Reproduce

1. `terraform plan`

### Errata

Also affected:

- aws_iam_user_policy.policy
- aws_iam_role.assume_user_policy

(Probably also others)

**Comment by davidvartan** [comment]
FYI, as an alternative, can use this resource to avoid writing the JSON by hand:

```hcl
data "aws_iam_policy_document" "lambda" {
  statement {
    actions = [""] # may put e.g. sts:AssumeRole

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}
```

To use it with your `aws_iam_role`:

`  assume_role_policy = "${data.aws_iam_policy_document.lambda.json}"`

To debug generated JSON:

```hcl
output "policy" {
  value = "${data.aws_iam_policy_document.lambda.json}"
}
```

**Comment by josephholsten** [comment]
@kevinburke do you have any ideas as to how this should work? I don't think we want to attempt a JSON parse for every string to see if something should use a JSON render. Any thoughts on how a policy could be rendered? Just unescaped?

**Comment by b-dean** [comment]
@davidvartan while the `data.aws_iam_policy_document.lambda.json` is nicer for writing the policy documents in HCL, it doesn't really solve the diff problem for `terraform plan`.

@josephholsten, maybe if there was some way to get something other than `"current" => "planned"` in the terraform plan? Maybe if there are multiline values in any diff (since you could get the same problem with multiline triggers in null_resource or ... really just about anywhere your values are multiple lines") it represents it as a unified diff or something? 

Maybe something like this: 
```
+ module.services.aws_iam_role_policy.s3_change_permissions_policy
    name:   "s3-change-permissions"
    policy: 
        --- current
        +++ planned
        @@ -0,0 +1,33 @@
        +{
        +  "Version": "2012-10-17",
        +  "Statement": [
        +    {
        +      "Effect": "Allow",
        +      "Action": [
        +        "logs:CreateLogGroup",
        +        "logs:CreateLogStream",
        +        "logs:PutLogEvents",
        +        "logs:DescribeLogStreams"
        +      ],
        +      "Resource": "arn:aws:logs:*:*:*"
        +    },
        +    {
        +      "Effect": "Allow",
        +      "Action": [
        +        "s3:GetObject",
        +      ],
        +      "Resource": [
        +        "arn:aws:s3:::segment-billing-raw-logs/*"
        +      ]
        +    }
        +    {
        +      "Effect": "Allow",
        +      "Action": [
        +        "s3:PutObject"
        +      ],
        +      "Resource": [
        +        "arn:aws:s3:::segment-change-permission-destination-stage/*"
        +      ]
        +    }
        +  ]
        +}
    role:   "${aws_iam_role.s3_change_permissions_role.id}"
```

I have no idea how terrible it would be to make a change like that, just thinking about ways it might be nicer to see multiline diffs.

**Comment by jmisur** [comment]
Hey, I had the same problem. I wrote a small stupid script which shows you diffs in a nicer way. Run it after plan and see actual policy changes.

policy_diff.sh
```bash
#!/bin/bash
#
# terraform plan <dir> | tee output.log
# ./policy_diff.sh
#

cat output.log | grep "policy" | grep -v "Refreshing" > policies.log

while read line
do
    if [[ $line =~ .*assume_role_policy.* ]]
    then
        # not interesting
        continue
    elif [[ $line =~ .*aws_iam_role_policy.* ]]
    then
        echo $line
    else
        # sanitize JSONs
        echo "$line" | sed -e 's/\\//g; s/n //g; s/"{/{/g; s/n}/}/g; s/^.*policy://; s/" =//' | cut -d'>' -f1 | jq . > before.json
        echo "$line" | sed -e 's/\\//g; s/n //g; s/"{/{/g; s/n}/}/g; s/}"/}/g' | cut -d'>' -f2 | jq . > after.json

        if [[ $line =~ .*(=>).* ]]
        then
            # change
            diff -u before.json after.json
        else
            # added or removed
            diff -u after.json before.json
        fi
    fi
done < policies.log

rm policies.log
rm before.json
rm after.json
```

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

Over in #15180 I shared some results of some UI prototyping we did about improving the handling of complex-typed values and multi-line strings in the plan output, which we're intending to implement once we've got some necessary infrastructure in place through our current project to improve the configuration language. While those two things may seem disconnected, the new configuration language implementation retains more type information that allows the diff renderer to make better decisions about how to present each value, vs. the current approach of just a flat map from strings to strings.

I believe once we resolve #15180 this issue will be resolved automatically as a side-effect, since it'll produce something similar to what @b-dean proposed above. Therefore I'm going to close this one just to consolidate the discussion over there.

Thanks to everyone for sharing their ideas here!
