### ISSUE TITLE
Feature request: Please provide functionality to configure a dynamic number of block devices within an aws_instance resource

### ISSUE THREAD

**Issue by katherinealbany** [hashicorp/terraform#1442]
Feature request: Please provide functionality to configure a dynamic number of block devices within an aws_instance resource. Currently each block device (ephemeral/ebs) has to be specified separately as follows:

```
  ephemeral_block_device {
    virtual_name = "ephemeral0"
    device_name  = "/dev/sdb"
  }

  ephemeral_block_device {
    virtual_name = "ephemeral1"
    device_name  = "/dev/sdc"
  }
```

It would be useful to be able to state the number of each given type of block device when creating the instance, much like "count" can be used at the resource level, something similar would be useful at the block device level.

Below is an example, in pseudo-syntax, in an attempt to convey my intent.

```
  resource "aws_instance" "name" {
    ephemeral_devices = 2
    ebs_devices = 3

    ephemeral_block_devices {
      ephemeral_block_device {
        virtual_name = "ephemeral${ephemeral_devices.index}"
        device_name  = <user derived, maybe from a lookup table using ephemeral_devices.index as a key>
      }
    }

    ebs_block_devices {
      ebs_block_device {
        device_name = <user derived, maybe from a lookup table using ebs_devices.index as a key>
        volume_size = 10
        volume_type = "gp2"
      }
    }
  }
```

This would be useful as it would allow DRYer configurations.

**Comment by bitglue** [comment]
Similar: #996

**Comment by catsby** [comment]
Hey @katherinealbany – sorry for the very long time of silence here. Shortly after you requested this, I added support for `aws_volume_attachment`, which as it's own resource fully supports `count` et. al, so I'm going to consider this closed. Thanks!

**Comment by tomelliff** [comment]
@catsby I'm not sure how that actually solves the requirement. As it stands `aws_volume_attachment` takes strings for the `volume_id` parameter so it looks like you'd need to statically define each of the volumes instead of being able to use `count` on the `aws_ebs_volume` resource and pass the splat into the `aws_volume_attachment` resource.

Even with that change that looks like it would only work for single instances and not when you use `aws_instance` with a count as you'd then need to be able to loop through EBS volumes per instances and then loop through the instances and I can't see how you could do that with Terraform as it stands right now but might be missing a trick here.

The idea should be that it's easy to create a module that creates multiple instances with a configurable amount of both ephemeral and EBS based volumes attached. Right now you have to create separate modules depending on the amount (and type) of disks that you want to provide and then make sure that the calling code knows which module to call based on what disk configuration it wants.

**Comment by jpancoast-kenzan** [comment]
We've run into something similar. While our "solution" doesn't involve terraform here's what I discovered.

If you create an AMI with any type of ephemeral block device mapping you can use that AMI to launch any instance that has ephemeral storage and the new instance will have whatever block devices go with that instance type. So for the one service for which we use instance stores we're probably just going to modify it's AMI to have a an ephemeral block device mapping and use that.

ex.:
I launched an r3.8xlarge (2 x 320 SSD) with the instance volumes added and created an image from that.
I launched an m3.medium (1 x 4 SSD) and it had ephemeral disk attached of appropriate size. (1 4 gig volume)
I then launched an cc2.8xlarge (4 x 840 HDD) and it had the 4 volumes, 840gig each, attached and available via lsblk

**Comment by alexebird** [comment]
I ran into this issue, but found a solution in the official Terraform registry ASG module.

- https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/examples/asg_elb/main.tf
- https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/modules/launch_configuration/main.tf
