### ISSUE TITLE
Terraform crashes when trying to select an element from a concat containing a potentially empty list

### ISSUE THREAD

**Issue by betabandido** [hashicorp/terraform#14438]
I am trying to build a module to configure a swagger endpoint that allows for either placing the endpoint under the root resource path or under a path named 'swagger'. I am following a similar approach to the one shown by Gruntwork ([link to the article](https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9))

When I run terraform, it crashes with the following message: `panic: runtime error: invalid memory address or nil pointer dereference` (more details below).

I am including a minimal example that reproduces the error. In this example, the endpoint is represented just as an API gateway method (no integration, integration response or response resources are present).

### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_api_gateway_method

Based on the nature of the problem, it might well be related to the core components, though.

### Terraform Configuration Files

The module contains:

```
variable "api" {}
variable "parent" {}
variable "location" {}
variable "use_swagger_path" {
    default = true
}

resource "aws_api_gateway_resource" "swagger" {
  count       = "${var.use_swagger_path}"
  rest_api_id = "${var.api}"
  parent_id   = "${var.parent}"
  path_part   = "swagger"
}

resource "aws_api_gateway_method" "method" {
  rest_api_id   = "${var.api}"
  resource_id   = "${element(concat(aws_api_gateway_resource.swagger.*.id, list(var.parent)), 0)}"
  http_method   = "GET"
  authorization = "NONE"
}
```

The main file contains:

```
provider "aws" {
  profile = "${var.profile}"
  region  = "${var.region}"
}

variable "swagger_location" {
  default = "a_url"
}

resource "aws_api_gateway_rest_api" "api" {
  name = "api"
}

module "swagger_root" {
  source   = "modules/swagger"
  api      = "${aws_api_gateway_rest_api.api.id}"
  parent   = "${aws_api_gateway_rest_api.api.root_resource_id}"
  location = "${var.swagger_location}"
  use_swagger_path = false
}
```

### Debug Output
https://gist.github.com/betabandido/2bcdcfbde244fdee016fc0f8f11d39ad

### Panic Output
https://gist.github.com/betabandido/d516d992ef83f95e5d285daebcfdeb41

### Expected Behavior
The API gateway resources should be created correctly.

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform get`
2. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @betabandido! Sorry for this crash, and thanks for reporting it.

I'm looking into this now, and will hopefully have an explanation (and ideally, a fix!) soon.

**Comment by apparentlymart** [comment]
Okay! This is a rather insidious edge-case.

The following is a minimal repro for this:

```hcl
# root.tf

module "child" {
  source = "./child"
}
```

```hcl
# child/child.tf

resource "null_resource" "a" {
  count = 0
}

resource "null_resource" "b" {
  triggers = {
      a_ids = "${join(" ", null_resource.a.*.id)}"
  }
}
```

The issue arises because of the shape of the intermediate state we're in when we resolve that `null_resource.a.*.id` variable in the child.

Normally by the time we resolve that `null_resource.a.*.id` expression there would be instances of `null_resource.a` in the module's state, but since we have `count = 0` here no instances were created. A module's state isn't created until the first time a resource is written into it, so when we reach this point the module has no state at all, but this is not a situation this code was built to expect and so it crashes.

The extra-edgey part of this edge case is that it only applies to non-root modules, since Terraform creates an empty state for the root module very early on its processing, but non-root modules don't get a state until the first resource is created.

I'm working on a fix and will have a PR for it soon.
