### ISSUE TITLE
Make a pre-comiled arm64 build

### ISSUE THREAD

**Issue by Knight1** [hashicorp/terraform#14474]
### Problem
There is only a pre-compiled arm version for Terraform available the arm64/aarch64 versions is missing. I was able to build it with go 1.8.1 without any errors on a Thunder X.

### Fix
Please make a pre-compiled arm64 version from Terraform available unter the download section.

Thanks!

### Terraform Version
0.9.5

**Comment by Knight1** [comment]
Consul fixed it with this commit: https://github.com/hashicorp/consul/commit/437222fbe7231189213977d164a00dc1310f88c3

Vault with this: https://github.com/hashicorp/vault/commit/7bce60290f2103365c4fedd9e28fbb28c0930fa1

**Comment by apparentlymart** [comment]
Hi @Knight1! Thanks for this request.

Right now we are doing some other release-engineering-type work internally, which will change how Terraform and its providers are built and packaged. Since there's already work underway there that we don't want to disrupt, we'll come back to this once the current tranche of work is done and see what it would take to do this under the new approach.

**Comment by vielmetti** [comment]
Thanks @apparentlymart - any sense for how the build reorg work is going, and what timeframe that is planned to appear in? 

We are about to engage in some more work on improving the Terraform provider at Packet (which will touch the ARMv8 servers there, hence the continuing interest).

**Comment by necrose99** [comment]
I have @Scaleway  i can make a compile run.

**Comment by vielmetti** [comment]
Thanks @necrose99 - and thanks for following through on this.

@apparentlymart there are CI resources available at Packet for doing this, but I don't know your existing build environment well enough to suggest which of them might work best.

**Comment by necrose99** [comment]
i'm just using Gentoo in a chroot on debian host 
https://gpo.zugaina.org/app-admin/terraform  
https://gitlab.com/chaoslab/chaoslab-overlay.git 
layman to add overlay , however eselect  repository 

can try to emerge after cleaning out tinderbox , 

ebuild terraform-0.11.8.ebuild  rpm will also spit out a redhat rpm , 
forcing it via alien a deb.. 
fakeroot alien --target=arm64 terraform-0.11.8.rpm 

as being a src based distro /var/tmp and /usr/portage/package  ""/distfiles start to fill up...

**Comment by necrose99** [comment]
[Uploading terraform-0.11.8-r0.aarch64.rpm.zip…]()

**Comment by necrose99** [comment]
dump of rpm spec , auto generated from ebuild rpm.... from gentoo ebuild... 

```
scw-0321f9 /var/tmp/portage/app-admin/terraform-0.11.8/temp # ls
build.log  eclass-debug.log  environment  go-build201936607  logging  rpmbuild  terraform-0.11.8.spec
scw-0321f9 /var/tmp/portage/app-admin/terraform-0.11.8/temp # cat terraform-0.11.8.spec
Summary: A tool for building, changing, and combining infrastructure safely/efficiently
Name: terraform
Version: 0.11.8
Release: r0
License: GPL
Group: portage/app-admin
Source: terraform-0.11.8.tar.gz
%description
A tool for building, changing, and combining infrastructure safely/efficiently

https://www.terraform.io

%prep
%setup -c

%build

%install

%clean

%files
/
scw-0321f9 /var/tmp/portage/app-admin/terraform-0.11.8/temp #

```

**Comment by vielmetti** [comment]
@grubernaut what is the necessary to get this build of Terraform for arm64 into your main build system? We are hoping to target something for Hashiconf in October, and it looks like things work and are tested if the artifacts can be built.

**Comment by grubernaut** [comment]
@vielmetti I'm not sure, as I haven't been an HC employee for almost a year now :smile:. But @apparentlymart would likely be the best point of contact for this question.

**Comment by apparentlymart** [comment]
Hi all,

I think the answer to this is similar to my answer in #18708. The summary is: a bunch of other stuff needs to be updated in order for a new architecture to be useful/supported.

Given this, I expect the most likely thing here would be that we hold on this for the moment and then make a set of supported-platform changes all at once so we can amortize that effort, probably also in conjunction with a forthcoming revamp of the build process for other reasons that is being driven by HashiCorp's internal engineering services team (and thus not something driven by the Terraform team's own planning/schedule.)

It is not likely that any new architectures will be officially supported before HashiConf in October, since all of the teams that would need to coordinate on this are occupied with other work.

**Comment by necrose99** [comment]
https://github.com/ascherer/debbuild  also can use the spec ebuild rpm autogenerated.

**Comment by arno01** [comment]
That would be useful, specifically for those who are running things like Samsung DeX.

**Comment by vielmetti** [comment]
Ran into this again - any chance to update the build process to add one more architecture?

**Comment by vielmetti** [comment]
Just put in PR #21064 with the two-line patch to the build script that should make this work. (There's probably a documentation PR that will need to go in as well, but as a start...!)

**Comment by vielmetti** [comment]
A note that #21064 was closed as it was not sufficient to do what it requested here.

**Comment by vielmetti** [comment]
re-upping this issue for the new year

**Comment by ktham** [comment]
I'd love to be able to run terraform on my Surface Pro X through WSL2, but there's no arm64 build 😢 . Also note that MacOS is also moving to ARM64 soon, so we may want to prioritize the groundwork needed for this sooner rather than later 🙏

**Comment by necrose99** [comment]
###**Quick And dirty** 
https://github.com/gentoo-mirror/chaoslab/blob/master/app-admin/terraform/terraform-0.11.11.ebuild 

https://github.com/sakaki-/gentoo-on-rpi-64bit 
**an RPI3 or RPI4** 

`layman -L && layman -a chaoslab`   
**else** `eselect repository enable chaoslab`

`emerge -av app-shells/fish  app-arch/alien `
app-arch/alien , rpm dpkg etc will install with them . 
**ALEIN to make debs. or Slackware etc packages.** 
(emerge layman eselect-repository if required.)  

###**chaoslab   added fish use dep**. 

cd /var/lib/layman/chaoslab/app-admin/terraform
  
or /var/db/repos/chaoslab/app-admin/terraform  
 (eselect repository / main gentoo repo hear too /var/db/repos)  


`ebuild terraform-0.11.11.ebuild  {rpm,package,clean} `
{rpm,package,merge.clean}  merge will force add to gentoo host..  package reate gentoo binary package.. 

generation of rpmspec and aarch64 rpm  /var/tmp/portage/app-admin/terraform...... vrsion etc RPMS , etc.. 

##**dh-make-golang**
**https://github.com/Debian/dh-make-golang**  created deps etc for debian automatic packaging on salas. 
however bit less strait forward creates git repos , deb rules though however more involed.. 
however Teraform devs or debian packagers can likewise add to autobuild.

**Comment by necrose99** [comment]
[dh-make-golang-terraform.log.txt](https://github.com/hashicorp/terraform/files/4871827/dh-make-golang-terraform.log.txt)
remote host atm  i need to reboot and or add ssh keys.  webconsole to ssh tem bit limited.

**Comment by rymcol** [comment]
Given the impending release of Apple Silicon darwin_arm64 and the use case of android_arm64 on things like the fold2, for me personally, this would be a very high priority. I am happy to contribute as well if there are any places that make sense outside of the internal build/release cycle.

**Comment by danieldreier** [comment]
I wanted to draw everyone's attention to the fact that the [latest beta has a linux arm64 build](https://releases.hashicorp.com/terraform/0.14.0-beta1/). Please try it out and let us know if you run into any issues with it!

**Comment by rymcol** [comment]
Seems to run okay on Ubuntu for arm64 for me. 

**Just my personal thoughts:**
My biggest targets (personally) are really `darwin_arm64` (because of the impending Apple silicon, which I'm sure you are working on) and `android_arm64` (which I am unsure if you have plans for, however with devices like the fold2 being essentially a 5G portable terminal with an 8 inch screen, this would be massively useful in my Ops life). 

Android is kinda-sorta-mostly linux. The `linux_arm64` binary doesn't run correctly for me inside of Android (I get connection refused to our cloud storage backend), but if you directly checkout the v0.14 branch and build it with go it does work (aside from having no available plugins in the registry).

**Comment by apparentlymart** [comment]
Terraform CLI v0.14.0 is now available for `linux_arm64` and we plan to continue to support that platform for the foreseeable future. As long as the providers you want to use _also_ have `linux_arm64` releases (which is true of several providers already) you should be able to use Terraform on arm64 Linux systems.

`darwin_arm64` will probably follow in the not-too-distant future too, but for now I'd recommend using the `darwin_amd64` builds under emulation on the new Apple hardware. As with `linux_arm64`, we must wait for a critical mass of providers to begin supporting the new platform before a Terraform CLI release on that platform would be useful, so we'll keep monitoring what the major providers are supporting and decide when to introduce `darwin_arm64` support based on that.

We have no plans to support Android or any other operating systems on arm64 at this time.
