### ISSUE TITLE
Terraform OPC provider doesn't use orchestration rather its Launchplan causing server shape change almost impossible

### ISSUE THREAD

**Issue by pranay-oracle** [hashicorp/terraform#14502]
Hi there,

### Terraform Version
Terraform 0.9 is the one I checked.

### Affected Resource(s)
Please list the resources as a list, for example:
- OPC provider

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

As Terraform uses laucnhplan kind of mechanism its makes impossible for us to change Shape of the instance or to attach new volumes to remain persistent accross orchestrations start.

customer d choose orchestration stop start mechnism in pay-per-use kind of environment. 

use case :
Shutdown all non-prod on weekend to reduce cost and bing it up on monday once developers are backp.

**Comment by grubernaut** [comment]
Hey @pranay-oracle, thanks for the issue!

I'm currently adding in the functionality to change an instance's state from `running` to `shutdown` and back. However, changing the instance's `shape` is currently not possible via the Oracle API. 

Also, can you elaborate on what you mean via "Attach new volumes to remain persistent across orchestrations start"? Terraform doesn't use Orchestrations, and instead launches instances via the `LaunchPlan` API endpoint, as that's the only way to create an instance via the API. 

cc: @scross01 

Thanks

**Comment by scross01** [comment]
@pranay-oracle Terraform can be used to change the shape and attach new storage volumes. I wouldn't mix the use of OPC Orchestrations and Terraform. Terraform manages the resource directly and is really an alternative to OPC Orchestrations.

To change the shape of an instance, take a look at the example https://github.com/oracle/terraform-provider-compute/blob/master/examples/opc/instance-with-persistent-boot-volume/main.tf
If you apply this example, then change the shape from `oc3` to `oc4`  and run `terraform apply` again the instance will be destroyed and recreated with the new shape using the same persistent storage. Note, this example is using a persistent boot volume, if the instance is using instance storage for the boot then the boot volume is destroyed and recreated)

Additional storage volumes can be added by adding a storage references in the `opc_compute_instance` resource.  @grubernaut we should allow storage volumes to added/removed without destroying the instance by using the [storage attangement](https://docs.oracle.com/cloud/latest/stcomputecs/STCSA/api-StorageAttachments.html) api

**Comment by grubernaut** [comment]
Aye, agreed @scross01. Taking this as a feature request for the storage attachment changes then.

**Comment by gupraj** [comment]
Hi @scross01 -
Thank you so much for valuable input, I followed your all the example and build full infrastructure. Thanks for you all effort.

I am having few open question, request you to please do the needful.

-Suppose I am having directory- terraform and I placed my terraform .exe (Binary) file there and more than one terraform- configuration.tf and Test.tf is placed on same direcotroy- My question is how we can call individual .tf file from same directory or can we create separate .tf file for individual work and one common place for terraform.exe?

-Suppose I am having one .tf file and I applied the same, after one day i just add some more resource in same file, then how I can run those changes only instead of applying all the changes again?

-Just example- If I create one cloud instance/server and added 1 persistant boot vol. and 1 persistent disk, and later wanted to add one more persistent disk then changed the same .tf file and used terraform init command and then checked the plan but its show 1 object to be destroyed and when run its create new persistent storage but destroyed the instance and recreate and add new storage? but I just wanted to execute only newly added storage resource and add the same to instance without destroying the instance.

- How we can assign auto generated public IP to instance using IP network only.

-	We did not found any orchestration after creating instance using terraform. Is it fine behavior? This is fine behavior, as per above its fine but what about If my customer need that ?

-	Using attributes we can create Jason file but what about logs, during terraform apply we can see logs but is there any option to route the log to different log location. Please share example for -output in terraform.

- Please also let me know how we can refresh changes we done in configuration using terraform prompt.

Sorry I am very new in terraform and wanted to learn on this.

I tried my best and create many setup using terraform.. As i said I build full DEV infra with help of your example but still unable to confirm to client so just wanted to crosscheck all before producing to client.

Thanks
Raj Gupta
