### ISSUE TITLE
FEATURE: option for `terraform fmt` to indent to global distance (per file)

### ISSUE THREAD

**Issue by spanktar** [hashicorp/terraform#14586]
### Terraform Version
0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `terraform fmt`

### Terraform Configuration Files

**For example**

```
resource "aws_elb" "elb-private-tf" {
  name                        = "${var.env}-elb-private-tf"
  subnets                     = ["${var.vpc_public_subnets}"]
  security_groups             = ["${aws_security_group.elb-private-sg.id}"]
  cross_zone_load_balancing   = true
  idle_timeout                = 60
  connection_draining         = true
  connection_draining_timeout = 120
  internal                    = true

  listener {
    instance_port             = "${var.elb_listener_instance_port_http}"
    instance_protocol         = "http"
    lb_port                   = "${var.elb_listener_lb_port_http}"
    lb_protocol               = "http"
  }

  health_check {
    healthy_threshold         = 2
    unhealthy_threshold       = 6
    interval                  = 10
    target                    = "HTTP:${var.elb_listener_lb_port_http}"
    timeout                   = 5
  }

  tags {
    "terraform"               = "true"
    "env"                     = "${var.env}"
  }

  lifecycle {
    ignore_changes            = ["instances"] # Terraform doesn't manage instances
  }
}
```

### Desired Behavior
An *option* to have `terraform fmt` indent all variable's values to the same indent rather than per block.  Basically, scan the entire file for the longest parameter, and indent everything to that. 

### Actual Behavior
The indenting decision is made on a per block basis, which is also fine but the option would be nice.  Right now we don't use `fmt` and maintain our indents by hand. If I had the chops, I'd write this feature myself and submit a PR! ;-)

**Comment by apparentlymart** [comment]
Hi @spanktar! Thanks for this feature request.

The goal of `terraform fmt` is for there to be _one_ canonical form for Terraform config, similar to `go fmt`. I think we'd be very cautious about adding more optional permutations as a result, since it's in conflict with the goal.

Implementation-wise I think this would require some rework of how the HCL printer is built, to give it enough context to do this.

So both of these things together make me think that the answer has to be "no" here. I understand why the layout you showed here could be useful for certain configs, but the results of `terraform fmt` are somewhat frozen at this point and so it would take a very strong rationale to change it.

Thanks again for the request!
