### ISSUE TITLE
Terraform apply exitcode due to locked state file

### ISSUE THREAD

**Issue by HighlandRim** [hashicorp/terraform#14590]
### Terraform Version
Terraform v0.9.5

### Terraform Configuration Files
terraform {
  backend "s3" {
   bucket = "somebucket"
    key    = "somefolder/terraform.tfstate"
    region = "us-east-1"
	encrypt = "true"
	lock_table = "sometablename"
	}

### Expected Behavior
If two users initiate apply using remote state storage, the user that is blocked due to locking should exit with exitcode of non-zero

### Actual Behavior
If two users initiate apply using remote state storage, the user that is blocked due to locking exits with an exitcode of zero

### Steps to Reproduce
1. Setup backed with S3 dynamodb locking
2. `terraform apply & echo %ERRORLEVEL%` as user 1 
Results: The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.
0
3. `terraform apply & echo %ERRORLEVEL%` as user 2
Results: Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed .......
0
4. Both users return exit code of 0

**Comment by HighlandRim** [comment]
Find successful error code also in situation where init fails due to defining more than one terraform block in module

**Comment by bursson** [comment]
I just wanted to ask if there is any plans on fixing this? The same issue is present when using Azure Blob as the backend.

**Comment by apparentlymart** [comment]
Hi again!

Since nobody responded to my previous comment, I'm going to assume that this is now fixed in modern versions of Terraform, and close it. If you see something which seems similar to this problem in a modern Terraform release, please _open a new issue_ to record it, and be sure to complete all of the parts of our bug report template so that we can understand exactly what's happening; the information in this issue is unfortunately no longer relevant for modern Terraform because the related codepaths are now considerably different than they were in Terraform v0.9.

Thanks!
