### ISSUE TITLE
PROBLEM : how to create Openstack's VM with TERRAFORM ?

### ISSUE THREAD

**Issue by daoudiahmed** [hashicorp/terraform#14613]
@jtopjian
Hello, I want to be able to create a virtual machine on CloudWatt (Openstack) by terraform. I have problems. I am on windows, my version of terraform is 0.9.5, my key pem is in the same folders as my files deploy.tf, provider.tf, variables.tf

Now I am told that * openstack_compute_instance_v2.web.1: Error creating OpenStack server: Expected
HTTP response code [201 202] when accessing [POST https: //compute.fr1.cloudwatt
.com / v2 / ************* I hide my personal information here ********************* / servers], purpose Got 407 instead

Would you have a concrete, complete and accurate example of creation of VM on Openstack going through Terraform?

Thank you.

Ahmed DAOUDI.

**Comment by stack72** [comment]
Hi @daoudiahmed

Thanks for raising your question here - we try (as much as possible) to keep the github issue list for bugs and enhancement requests. I am going to suggest that you have a look on the [community](https://www.terraform.io/community.html) page. It has links to the google group and also Gitter where we have a lot of community that help each other out

Thanks

Paul

**Comment by daoudiahmed** [comment]
@stack72 This question was not yours. Thank you for not answering if you can not help me. Most people are being helped here. And not only for bugs.

I asked the question here https://github.com/hashicorp/terraform/issues/14436#issuecomment-302279366 and was told to create a new topic. 

@jtopjian can you help me please . i can't create a VM on openstack with terraform . 

Thank you . 

Ahmed DAOUDI. 
PARIS - FRANCE

**Comment by stack72** [comment]
Hi @daoudiahmed 

I am sorry that this response wasn't what you expected. Unfortunately, with over 1900 issues in the list, we are really trying to keep the issue tracker for bugs. It seems as though you need some help in designing your terraform code rather than facing a specific issue

If this isn't actually the case, then please do give us more details about what the issue you are facing is. Ideally, this would include your terraform code and a debug log so we can help diagnose the issue

Paul

**Comment by daoudiahmed** [comment]
i can't create a virtual machine ...


C:\Program Files\terraform>terraform apply
There are warnings related to your configuration. If no errors occurred,
Terraform will continue despite these warnings. It is a good idea to resolve
these warnings in the near future.

Warnings:

  * openstack_compute_instance_v2.web: "floating_ip": [DEPRECATED] Use the opens
tack_compute_floatingip_associate_v2 resource instead

openstack_compute_instance_v2.web: Creating...
  access_ip_v4:               "" => "<computed>"
  access_ip_v6:               "" => "<computed>"
  all_metadata.%:             "" => "<computed>"
  availability_zone:          "" => "<computed>"
  flavor_id:                  "" => "3"
  flavor_name:                "" => "<computed>"
  floating_ip:                "" => "84.**.**.*** " 
  force_delete:               "" => "false"
  image_id:                   "" => "*****************my perso informations**************************"
  image_name:                 "" => "<computed>"
  key_pair:                   "" => "C:/Program Files/terraform/keylinux.pem"
  metadata.%:                 "" => "1"
  metadata.this:              "" => "that"
  name:                       "" => "*********my perso informations *****************"
  network.#:                  "" => "3"
  network.0.access_network:   "" => "false"
  network.0.fixed_ip_v4:      "" => "<computed>"
  network.0.fixed_ip_v6:      "" => "<computed>"
  network.0.floating_ip:      "" => "<computed>"
  network.0.mac:              "" => "<computed>"
  network.0.name:             "" => "*****************"
  network.0.port:             "" => "<computed>"
  network.0.uuid:             "" => "<computed>"
  network.1.access_network:   "" => "false"
  network.1.fixed_ip_v4:      "" => "<computed>"
  network.1.fixed_ip_v6:      "" => "<computed>"
  network.1.floating_ip:      "" => "<computed>"
  network.1.mac:              "" => "<computed>"
  network.1.name:             "" => "<computed>"
  network.1.port:             "" => "<computed>"
  network.1.uuid:             "" => "***************************************"
  network.2.access_network:   "" => "false"
  network.2.fixed_ip_v4:      "" => "<computed>"
  network.2.fixed_ip_v6:      "" => "<computed>"
  network.2.floating_ip:      "" => "<computed>"
  network.2.mac:              "" => "<computed>"
  network.2.name:             "" => "<computed>"
  network.2.port:             "" => "*********my perso informations*************"
  network.2.uuid:             "" => "<computed>"
  region:                     "" => "fr1"
  security_groups.#:          "" => "1"
  security_groups.3814588639: "" => "default"
  stop_before_destroy:        "" => "false"
openstack_compute_instance_v2.web: Still creating... (10s elapsed)
Error applying plan:

1 error(s) occurred:

* openstack_compute_instance_v2.web: 1 error(s) occurred:

* openstack_compute_instance_v2.web: Error creating OpenStack server: Expected H
TTP response code [201 202] when accessing [POST https://compute.fr1.cloudwatt.c
om/v2/*****************my perso informations***************/servers], but got 407 instead
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>407 Proxy Authentication Required</title>
</head><body>
<h1>Proxy Authentication Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jen20** [comment]
The error suggests that you are connecting to your openstack installation via a proxy server that requires authentication - what is your network topology?

**Comment by daoudiahmed** [comment]
@jen20 Thanks for your reply, I know that sometimes I have proxy problems. But even when I log in 4G with my phone (I use my phone as a router with connection sharing) I have the same error message.
In my file "configuration.tf" I put my identifiers. I see that terraform connects to CloudWatt (Openstack) but the worry is that I can not create a virtual machine.

**Comment by gregoryyoung** [comment]
This should be on hackernews.

**Comment by daoudiahmed** [comment]
sorry ?

**Comment by jtopjian** [comment]
@daoudiahmed as @jen20 mentioned, this does sound like a connectivity issue between your workstation and your cloud provider. While I did request that you open a new issue for this, @stack72 is also correct when he says that there are other mediums available for discussion of troubleshooting _until_ it's confirmed that there's an actual bug in the code. This was my mistake and I apologize for the confusing direction of this.

I noticed that you did post to the Terraform mailing list and I followed up with a reply shortly after.

In addition, I would recommend that you're first able to use the standard `openstack` command-line tool to create instances with your cloud provider. A lot of the knowledge and configuration required to use the `openstack` command is directly transferable to the Terraform OpenStack provider. Since each OpenStack cloud can vary from one to the other, most cloud providers have documentation about how to tune certain configurations to get the `openstack` command to work with their provider.

As one final method of troubleshooting, you could also try creating an instance _within_ the cloud provider (probably through the provider's web interface), remotely connecting to that instance, installing either the `openstack` command-line tool or Terraform, and then trying. While this method is certainly tedious and agreeably a bit of a hassle, it's a possible way of circumventing any connectivity issues (proxy et al) your workstation might have.

I understand if these methods sound troublesome when all you want to do is launch an instance using Terraform, and I certainly sympathize with that.

**Comment by daoudiahmed** [comment]
@stack72 @jtopjian Why does terraform destroy my old VM when I create a new one?
