### ISSUE TITLE
Self variables are only valid on resources

### ISSUE THREAD

**Issue by scriptjs** [hashicorp/terraform#14684]
### Terraform Version
0.9.5

### Affected Resource(s)
All modules

Using self to reference attributes is just as important to modules as resources but it is not available and will throw with 

```
invalid scope, self variables are only valid on resources
```

**Comment by apparentlymart** [comment]
Hi @scriptjs,

Could you please share an example of what you are trying to do? It's not clear how exactly self variables for modules would work, since self variables are used for `connection` blocks and `provisioner` blocks, but neither of these are relevant to modules.

**Comment by scriptjs** [comment]
The use case for self in modules is pretty much the same as resources. I may have a static attribute that becomes part of a name in another attribute. I don't want to duplicate the original attribute but call it. There is no interpolation of variables so there can only be interpolation in the module.

**Comment by apparentlymart** [comment]
@scriptjs today a resource cannot refer to its own attributes with `self`. It's used only for referring to the resource from a provisioner or connection block, like this:

```hcl
resource "aws_instance" "foo" {
  # ...

  connection {
    host = "${self.private_ip}"
  }
}
```

Self-referential things are not permitted in general because that would create a dependency cycle.

It sounds like your root concern is having a way to say something in one place and then refer to it in other places, like #4084. We couldn't allow a module block to reference its own arguments, but we could allow two arguments in a module block to both reference the same intermediate variable, should such a concept exists.

Does that seem fair, or am I misunderstanding what you're asking for?

**Comment by scriptjs** [comment]
I am using data sources created with null_resources to obtain the effect of vars I can use everywhere I need atm which is good. The challenge than brought me to this issue is perhaps more of trying to work around is modules without count.

I have to create resources for multiple tenants in openstack and I cannot loop with an alias tenant in a resource. Therefore I have had to go to creating modules where tenant ids are static. So even if the id is short I don't want to type it more than once as a key to a map lookup in a data source. 

Probably I just need to wait for some movement in count and that would dry up my code. Many thanks for your considered reply.

**Comment by apparentlymart** [comment]
Although some of the details are different, I think this is basically the same use-case as #3267, or at least is likely to be addressed in the same way as we're discussing over there. I'm going to close this one out just to consolidate the discussion.
