### ISSUE TITLE
When Azure provider recreates VM, when destroying the original VM it doesn't delete the VHD

### ISSUE THREAD

**Issue by stevehwinwood** [hashicorp/terraform#14715]
When Azure provider recreates a VM, upon destroying the original VM it doesn't delete the VHD and therefore the VM recreation fails.

Error message
'Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="TargetDiskBlobAlreadyExists"'

To workaround I must manually delete the VHD from the storage container

### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
resource "azurerm_virtual_machine"

### Expected Behavior
VHD should be deleted when VM is deleted

### Actual Behavior
VHD remains

### Steps to Reproduce
1. `terraform apply` after making changes to a .tf file that requires the VM to be recreated

**Comment by tombuildsstuff** [comment]
Hi @stevehwinwood 

Thanks for reporting this issue :)

The `azurerm_virtual_machine` resource contains a couple of fields for this purpose, [`delete_os_disk_on_termination`](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#delete_os_disk_on_termination) and [`delete_data_disks_on_termination`](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#delete_data_disks_on_termination) - which will automatically delete the OS/Data Disks when the VM is destroyed. Given these are destructive operations, they're both opt-in / disabled by default - but they can be set as follows:

```
resource "azurerm_virtual_machine" "test" {
  ..
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true
}
```

Would it be possible to confirm if setting this value deletes the VHD's as expected? If not - would it be possible to link to a reproducible terraform config so that we can investigate this further? :)

Thanks!

**Comment by stevehwinwood** [comment]
Thanks for pointing this out :-)

I can confirm when I set this to true the VHD is deleted

Thanks

**Comment by TechnicalVegeta** [comment]
but, this will going to delete my custom VHD image ryt ?
which i don't want to do
