### ISSUE TITLE
Only interpolate variables passed to module if variable is used in module

### ISSUE THREAD

**Issue by ThePletch** [hashicorp/terraform#14797]
This is a feature request for a bit of a stopgap measure until modules support `count`.

The use case is something like the following:
main.tf
```
resource "aws_lambda_function" "foo_lambda" {
  count = "${var.lambda_enabled}"
  # ...config...
}

module "foo_lambda_api" {
  enabled = "${var.lambda_enabled}"
  source = "./modules/api_gateway"
  lambda_function_arn = "${aws_lambda_function.foo_lambda.arn}"
  # ...more config...
}
```

api_gateway.tf
```
variable "enabled" { default = true }
variable "lambda_function_arn" {}
# ...other variables...

# ...resources...
resource "aws_api_gateway_integration" "foo_integration" {
  count = "${var.enabled}"
  # ...config...
  uri = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${var.lambda_function_arn}/invocations"
  # ...more config...
}
# ...more resources...
```

Currently, this errors on plan because `aws_lambda_function.foo_lambda.arn` is undefined - the desired behavior would be that the value would not be interpolated unless a resource within the module referenced the variable that the lambda function's ARN is passed into.

This is essentially lazy evaluation, which I know Terraform's evaluator has limited-if-any support for, but it would allow users to toggle certain features entirely across environments without jumping through nearly as many hoops.

**Comment by teamterraform** [comment]
Hi @ThePletch! Sorry for the long silence here.

We considered this feature as part of the planning for language improvements in Terraform 0.12, but ultimately decided not to implement it.

The main concern we had with this feature is that it makes the interface of a module be dependent on the entire module rather than just the `variable` and `output` declarations, and therefore it'd be harder for a user of a module to determine how to use it correctly. It would also mean that adding a new reference to a variable could end up being a breaking change to the module, even though there is no obvious construct in the configuration to indicate that.

The recommended way to represent differences between environments is to factor out the _common_ elements of environments out into one or more modules and then have a separate root configuration for each environment that instantiates those child modules in a suitable combination for that environment. We recommend that approach because it makes it straightforward to review the root module for each of these configurations and understand how a particular environment is configured, rather than spreading those decisions throughout all of the child modules. In the idealized model, the root module in each case consists only of `module` blocks, and the differences between the environments are in which subset of the shared modules are instantiated for each environment.

There's more detail on this recommendation in the documentation guide [Module Composition](https://www.terraform.io/docs/modules/composition.html), and in particular the section _Conditional Creation of Objects_. There's also some commentary on this in the documentation section [When to use Multiple Workspaces](https://www.terraform.io/docs/state/workspaces.html#when-to-use-multiple-workspaces); although that section is talking specifically about the Terraform workspaces feature, the same general concerns and advice apply to any situation where the same entire configuration is deployed multiple times to create separate states, even if workspaces aren't used to orchestrate that.

With all of that said, we're going to close this issue now to represent the decision not to make the proposed change. We hope the above rationale makes sense, and that the documentation we linked here helps to describe the alternative model that makes use of Terraform's existing features.
