### ISSUE TITLE
Artifactory backend: URL cannot end with a trailing slash (/)

### ISSUE THREAD

**Issue by DavidR91** [hashicorp/terraform#14795]
### Terraform Version
0.9.4

### Affected Resource(s)
`terraform`
` backend "artifactory" `

### Configuration
```
terraform {
  backend "artifactory" {
    url      = "https://squaredup.jfrog.io/squaredup/"
    repo     = "terraform"
    subpath  = "uksouth/buildlab"
  }
}
```

### Expected Behavior
Accessing remote state on Artifactory with a valid URL + repo + basepath should function for both push and pull

Having or omitting a trailing slash from the URL should not matter (as a user I expected a smart combine was occurring between each part of the URL)

### Actual Behavior
It seems that a trailing slash screws up the request URLs. The result is 403s (even after giving the user admin etc.)

This was difficult to figure out (since proxying its requests to see the URLs does not work for some reason? + TF_LOG on trace still doesn't show requests) but I found this in the Artifactory request log:

```
20170524135909|1|REQUEST|terraform_production|GET|//terraform/uksouth/buildlab/terraform.tfstate|HTTP/1.1|404|0
20170524135909|1|REQUESTterraform_production|GET|//terraform/uksouth/buildlab/terraform.tfstate|HTTP/1.1|404|0
20170524135909|0|REQUEST|terraform_production|PUT|//terraform/uksouth/buildlab/terraform.tfstate|HTTP/1.1|403|21665
```

Note how each request starts with // rather than just / 

After correcting my URL to ` "https://squaredup.jfrog.io/squaredup"` the requests work as expected

### Steps to Reproduce
Add a trailing slash to the Artifactory URL

**Comment by mildwonkey** [comment]
I'm going to close this since I believe it's been covered by a documentation update: https://www.terraform.io/docs/backends/types/artifactory.html

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
