### ISSUE TITLE
Proposal: New data source for TLS cert

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/terraform#14856]
I would like to propose a new data source under `TLS` provider named `tls_cert` (or something like that).

Arguments:
- You would be able to either supply a path to TLS certificate as argument, or supply a PEM, which could be read by `${file('path/to/cert.pem')}`.

Attributes:
- `signature_algo`
- `public_key_algo`
- `serial_number` (represented as integer)
- `serial_number_hex` (represented as hex delimited with `:`)
- `is_ca`
- `version`
- `issuer`
- `subject`
- `not_before`
- `not_after`

Possibly even more.

Please share your view on introducing such provider.

**Comment by apparentlymart** [comment]
Hi @martinssipenko!

This seems like a reasonable idea to me, though if you have a specific use-case in mind I'd be interested to hear it, since it can be helpful to include these things in the docs to help people understand whether a particular resource/data source is appropriate for their problem. (Especially in this case, where we also have cert resources that could be confusing to new users.)

Regarding the arguments, whereever possible we avoid arguments that take paths to local files on disk, because it causes absolute paths to get written to the Terraform state and thus causes useless updates when Terraform is run on different machines. In this case it sounds like there is no downside to using the `file()` function to read the PEM file into an attribute, so I would suggest taking that path.

**Comment by martinssipenko** [comment]
@apparentlymart, we upload our TLS certificates to S3 bucket using `aws_s3_bucket_object ` along with information about them (serial number). We also use the serial number to grant access to object using IAM. Instead of having to hardcode serial number we could have it red dynamically.
