### ISSUE TITLE
TF_VAR and -var don't pass variables through CLI

### ISSUE THREAD

**Issue by MaximF** [hashicorp/terraform#14874]
### Terraform and OS Version
Terraform v0.9.6
Ubuntu 16.04

### Affected Resource(s)
CLI variables are not passing through

### Terraform Configuration Files
**broken config file:**
```hcl
variable "server_type" {}

module "any_server" {
  source = "../modules/tomcat"
}
```

**working config file**
```hcl
module "any_server" {
  source = "../modules/tomcat"
  server_type = "web"
}
```

### Debug Output
```
  module.any_server.output1 error(s) occurred:
* module root: module any_server: required variable "server_type" not set
```

### Expected Behavior
Pass variable to terraform call through CLI

### Actual Behavior
Variable is not set in TF

### Steps to Reproduce
1. Define a module with empty variables 
2. Call this module using mengioned configs with following commands:
```shell
TF_VAR_server_type=web terraform plan 
```
or this:
```shell
terraform plan -var server_type=web
```

**Comment by Dogers** [comment]
Worth adding your OS? It certainly works for me with 0.9.6 on Windows, although I'm setting it before running terraform rather than on the same line.

**Comment by MaximF** [comment]
@Dogers It is running on Ubuntu 16.04

**Comment by tombuildsstuff** [comment]
Hi @MaximF

Thanks for opening this issue :)

Terraform will only prompt for variables which are defined in the current folder and not specified through [one of the methods listed in the documentation](https://www.terraform.io/docs/configuration/variables.html) - variables outside the current root (such as in Modules) need to be explicitly passed through when referencing the module.

The error message from the Terraform Configuration posted above is because the variable `server_type` in the module `any_server` is defined but isn't threaded through, and doesn't have a default value.

```
variable "server_type" {}

module "any_server" {
  source = "./modules/tomcat"
}
```

```
$ terraform plan -var server_type=web
1 error(s) occurred:

* module root: module any_server: required variable "server_type" not set
```

When updating the configuration to thread the variable through to the Module - this works as expected:

```
variable "server_type" {}

module "any_server" {
  source      = "./modules/tomcat"
  server_type = "${var.server_type}"
}
```

```
$ terraform plan -var server_type=web
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

Would it be possible for you to confirm if threading this variable through this solves the issue?

Thanks!

**Comment by Telling** [comment]
I've had a similar issue for a while now (having vars read from terraform.tfvars and using modules), been unable to figure out what was going on. You solution, @tombuildsstuff works for me.

**Comment by MaximF** [comment]
@tombuildsstuff 
Thank you a lot, your solution works like a charm! :)

P.S. Sorry for a long time to respond - was on a vacation and then spent some time catching up!

**Comment by tombuildsstuff** [comment]
@MaximF @Telling awesome - thanks for confirming that - as such I'm going to close this issue :)
