### ISSUE TITLE
terraform 0.9.6 is counting resource adds twice

### ISSUE THREAD

**Issue by stmarier** [hashicorp/terraform#14950]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
- aws_lambda_function
- aws_iam_role
- a module containing more AWS resources

I suspect this affects terraform core, but it might also just be the AWS provider core (if there is such a thing).

### Terraform Configuration Files
I imagine this is either heavily reliant on state (I am using remote state in s3) or the hcl isn't relevant at all.

### Debug Output
I have secrets and partial configuration that I'd really rather not share.  This should either be pretty easy to reproduce or it is probably only affecting me due to some strange edge case.  Let me know how you'd like me to attempt to reproduce or identify my edge case.

### Expected Behavior
Running plan with `0.9.6` should have the same results as `0.9.5`

### Actual Behavior
plan from `0.9.6` appears to count each new resource twice in the output:
```
Plan: 5 to add, 0 to change, 0 to destroy.
Plan: 10 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
None that I could find

**Comment by apparentlymart** [comment]
Hi @stmarier! Sorry for this strange issue.

I wasn't able to quickly track down an obvious change from 0.9.6 that would've caused this, since it seems like the diffing and plan rendering code didn't change at all in that release.

I understand that you aren't able to share the config or plan output due to it containing sensitive information. Can you confirm though that the rendered plan alongside that summary _does_ have five resources that are all shown as create (`+`) actions? If there's anything else included (data sources, for example) that would be interesting to know.

The tally you see there is made by inspecting each resource diff as it is created. The first number is incremented for any create (`+`) or replace (`-/+`) diff.

**Comment by stmarier** [comment]
Howdy, thanks for getting back to me so quickly.

Yeah, I can confirm that the rendered plan output only had 5 `+` actions associated with it.  It also doesn't attempt to create twice or anything of that nature, it was completely harmless actually.

After digging some more, I can state that:

- the issue was isolated to one of our testing amazon accounts
- it appears to have resolved itself after running terraform apply
- I'm not able to intentionally reproduce it anywhere else yet

If my understanding of any of these issues changes, I'll be happy to re-open this ticket, but I think we're safe to close this for now.  Thanks a bunch for your help.

**Comment by apparentlymart** [comment]
Thanks for following up, @stmarier! Sounds like a rather strange quirk, but if it's gone away for now I'm satisfied to wait until we see it again before digging in any deeper.

**Comment by nmarley** [comment]
Related: #14905. I had this same issue with the DigitalOcean provider, which I've described there.

**Comment by rkroboth** [comment]
I am seeing this same thing, starting with 0.9.6.

**Comment by apparentlymart** [comment]
Hi all,

Let's use #14905 for further discussion of this issue, since there's more information over there at this point. Thanks!
