### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by devinbernosky** [hashicorp/terraform#15000]
Hi there,

### Terraform Version
0.9.6

### Affected Resource(s)
ns1_zone

### Actual Behavior
Rate Limits being hit

### Steps to Reproduce
Create zone with 300+ records

![image](https://cloud.githubusercontent.com/assets/29133319/26705112/cdaa45b6-46e8-11e7-88e3-b2006cb78c4a.png)

**Comment by tombuildsstuff** [comment]
Hi @devinbernosky 

Thanks for reporting this issue :)

Whilst the NS1 Provider should handle Rate Limting, until it does it may be possible to throttle Terraform under the Rate Limit by taking advantage of the [`-parallelism` flag](https://www.terraform.io/docs/commands/apply.html#parallelism-n). NS1's [Rate Limiting Documentation](https://ns1.com/articles/api-rate-limiting) references ~3 requests a second - so it might be worth setting this to -`parallelism=2` for the moment and seeing if that helps?

Obviously this isn't ideal - but hopefully that should work around this issue until this is fixed :)

Thanks!

**Comment by pashap** [comment]
@tombuildsstuff Do you have any examples of how other providers handle rate limiting? 

The [ns1 provider](https://github.com/hashicorp/terraform/blob/master/builtin/providers/ns1/config.go#L41) uses a naive/simple [strategy](https://github.com/ns1/ns1-go/blob/v2/rest/client.go#L235-L256) of sleeping based off of the rate limit headers returned by the ns1 api. This problem is that the strategy only works for a single goroutine.
