### ISSUE TITLE
Modify the dependent terraform resource before destroying the resource?

### ISSUE THREAD

**Issue by sakshiag** [hashicorp/terraform#15010]
Suppose we have two terraform resources R1 and R2.

R2 is dependent on resource R1.

We modified the R1 which lead to force new of R1

As Resource R2 is using R1, it should modify the resource R2 before destroying the resource R1 and then create the new resource and again modify the resource R2 with the new value.

For example -

resource "some_resource" "R1" {
     name       = "test"
}

resource "some_resource" "R2" {
     R1_id       = ["${some_resource.R1.id}"]
}

Suppose we change the name of resource  R1 which leads to force new.

Expectation - It should process R2 first so that Update of R2 is called and then remove R1 and then Update R2 again with the new ID of R1

Actual Result: It is trying to delete resource R1 first and then trying to update the resource R2 which leads to an error

**Comment by catsby** [comment]
Hey @sakshiag can you give me more concrete information on the resources and errors you're getting?

Take this example configuration from the [Getting Started documentation](https://www.terraform.io/intro/getting-started/dependencies.html#assigning-an-elastic-ip):

```
resource "aws_eip" "ip" {
  instance = "${aws_instance.example.id}"
}
```

In this example, R1 would be the `aws_instance` and R2 would be `aws_eip`. Here we can't modify R2 until R1 has finished it's update. We don't know the ID until the update is finished. 

> Expectation - It should process R2 first so that Update of R2 is called and then remove R1 and then Update R2 again with the new ID of R1

Many times this isn't possible, because the value R1 is providing to R2 is a required value for R2 to function; it can't simply be removed and left empty for a time. 

>  It is trying to delete resource R1 first and then trying to update the resource R2 which leads to an error

This behavior can depend on the implementation of the resource and the backing API, so without more information I can't do much here. If you have some more concrete examples I can try though!

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!
