### ISSUE TITLE
Teach apply (without an input plan) to prompt the user to confirm changes

### ISSUE THREAD

**Issue by dougbarth** [hashicorp/terraform#15033]
### Terraform Version
Terraform v0.9.6

### Feature Request
Running `terraform apply` without first running `terraform plan` can causes unexpected changes to be applied. To help users apply changes safely, it would be nice if `terraform apply` would show them the plan and ask for confirmation before applying it.

We currently have a wrapper script that does this by always running `terraform plan --out`, and then `terraform apply --input`. This mostly works, except it runs into issues with `terraform apply` commands that pass additional arguments (eg. passing `-target` to the plan, not the apply).

Is this behavior that the project would be interested in?

**Comment by bclodius** [comment]
@dougbarth we rely heavily on targeted plans.  One of my nightmares is someone on the team forgetting to provide the plan file argument.

The drawback of adding this I feel is it will create a huge amount of churn from those who may not check the release notes closely; especially for automated pipelines.

I've thought about managing a patch so that when terraform was installed it would REQUIRE the plan file; but I know I won't be able to continuously maintain it for the org.

**Comment by apparentlymart** [comment]
Hi @dougbarth!

I think what you're describing is the same thing being discussed in #7251. We're currently leaning towards making the interactive prompt optional for the next major release and then making it the default in a subsequent major release, to give people time to update their wrapper scripts and other tooling to expect it.

**Comment by dougbarth** [comment]
> I think what you're describing is the same thing being discussed in #7251.

Indeed it is. I'll close this out and follow #7251 instead.
