### ISSUE TITLE
Any way to access old documents?

### ISSUE THREAD

**Issue by ozbillwang** [hashicorp/terraform#15058]
Hi there,

### Terraform Version
v0.8.X

The environment has locked terraform version which is `v0.8.8`. I'd like to go through the terraform documents only on that version because I am not sure which `resource/data store` I can't use in that version.

So how can I read the legacy documents on particular terraform version?

**Comment by apparentlymart** [comment]
Hi @ozbillwang!

Right now the only way to do this is to read the documents directly inside the git repository, looking at how they were in the tag for the version you are using. You can find the provider docs in `website/docs/providers`.

In the long run we are planning to have a proper solution for this, but haven't been able to prioritize yet figuring out all the details for that since it will require reworking somewhat how the website is built.

**Comment by dewang** [comment]
Hi @apparentlymart 

It would seem that a few days after your comment there was a restructure of the documentation, so history is now lost. 

https://github.com/hashicorp/terraform/commits/master/website/docs/provisioners/connection.html.markdown now only shows the restructuring commit. Any way to get the history?

**Comment by mrlesmithjr** [comment]
This would awesome to get to the previous doc versions, especially when a complete rewrite of a plugin has been made and everything no longer works. Pinning a provider plugin works as expected but no way to get back the previous version of docs really sucks.

**Comment by djmitche** [comment]
I can't even find a file with "google" in it in the repository, to try to find the docs for the google provider.  Has it been moved to another repo?
