### ISSUE TITLE
Order to destroy dependent resources 

### ISSUE THREAD

**Issue by blaltarriba** [hashicorp/terraform#15111]
Hi there,

Having two resources like:
- "Resource 1"
- "Resource 2" (depends on "Resource 1")

What I would expect is:
Order of execution during apply:
- Create "Resource 1"
- Create "Resource 2"

Order of execution during destroy:
- Destroy "Resource 2"
- Destroy "Resource 1"

But the execution order during destroy is not always like this and could make to let some resources created.

My use case is:
- "aws_cloudwatch_log_group"
- "aws_lambda_function" (depends on "aws_cloudwatch_log_group")

If is destroyed first "aws_cloudwatch_log_group" could happen that the "aws_lambda_function" is executing and will create a new "aws_cloudwatch_log_group" with the result of this execution. Then Terraform will destroy the "aws_lambda_function" and the new "aws_cloudwatch_log_group" keep existing.

### Terraform Version
0.9.5

### Affected Resource(s)
- core?

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "role" {
    name = "my-test-role"
    description = "My test role"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_cloudwatch_log_group" "lambda-cloud-watch-log-group" {
  name = "my-test-lambda-cloud-watch-log-group"
  retention_in_days = "14"
}

resource "aws_lambda_function" "lambda-function" {
    depends_on = ["aws_cloudwatch_log_group.lambda-cloud-watch-log-group"]

    function_name = "my-test-lambda"
    description = "My test lambda"
    runtime = "Java8"
    s3_bucket = "my-s3-bucket"
    s3_key = "my-s3-key"
    role = "${aws_iam_role.role.arn}"
    handler = "dummy-handler"
    memory_size = "512"
    timeout = "60"
    publish = true
}
```

### Expected Behavior
Order of execution during apply:
- Create "aws_cloudwatch_log_group"
- Create "aws_lambda_function"

Order of execution during destroy:
- Destroy "aws_lambda_function"
- Destroy "aws_cloudwatch_log_group"

### Actual Behavior
Order of execution during apply:
- Create "aws_cloudwatch_log_group"
- Create "aws_lambda_function"

Order of execution during destroy is random.

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

**Comment by apparentlymart** [comment]
Hi @blaltarriba!

The destroy ordering you expected is how Terraform is intended to behave. If it's not, that suggests a critical bug. If you would be able to share the output of `terraform apply` showing the incorrect ordering (with any sensitive info redacted), that would be very helpful to see what's going on here.

I have a suspicion that there's some asynchronicity going on in AWS here, where Terraform is deleting the Lambda function, then deleting the log group, but there's some async buffering going on in Lambda for the log result and so it ends up flushing one more set of logs to cloudwatch after both were deleted, thus re-creating the log group. If that's true, unfortunately this may be hard or impossible to resolve since Terraform can't "see" when the log buffers in Lambda have been completely flushed. :confounded:

**Comment by blaltarriba** [comment]
Hi @apparentlymart !

Sorry for my delayed reply. I've been trying to reproduce this situation(before open this issue I had it in a few times) to give detailed information but since then I haven't been able to reproduce it :-(

I think is better to close this issue and if in the future I have the same problem I'll open a new issue or reopen this one.

Thank you for your aclaration @apparentlymart !

**Comment by aawilson** [comment]
I have a specific instance of this that I can reproduce.

An instance group foo-ig composed of fooinstance[1-n] is being split into two instance groups, foo-bar-ig and foo-baz-ig, with fooinstance[1-k] and fooinstance[k-n]. The dry-run shows the correct sequence of steps (lbs referring to the old ig are updated to point to the new split igs, old ig is destroyed and new igs are created), but attempting to execute the plan results in errors based on double-populating fooinstances within igs.

Here is the (abridged) dry run output:

```
..load modules, refresh state, etc..
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  + module.foo.google_compute_backend_service.foo-bar-backend
      id:                                        <computed>
      backend.#:                                 "1"
      ...etc...
      backend.~etc.group:                 "${google_compute_instance_group.foo-bar-group.self_link}"
      ...etc...

  - module.foo.google_compute_backend_service.foo-backend

  + module.foo.google_compute_backend_service.foo-baz-backend
      id:                                        <computed>
      backend.#:                                 "1"
      ...etc...
      backend.~etc.group:                 "${google_compute_instance_group.foo-baz-group.self_link}"
      ...etc...

  + module.foo.google_compute_instance_group.foo-bar-group
      ...etc...
      instances.etc:                      "https://www.googleapis.com/compute/v1/redacted_project_and_zone/instances/foo1"
      name:                                      "foo-bar-group"
      ...etc...

  - module.foo.google_compute_instance_group.foo-group

  + module.foo.google_compute_instance_group.foo-baz-group
      ...etc...
      instances.etc:                      "https://www.googleapis.com/compute/v1/redacted_project_and_zone/instances/foo2"
      name:                                      "foo-baz-group"
      ...etc...

  ~ module.foo.google_compute_url_map.foo-lb
      default_service:                           "https://www.googleapis.com/etc/foo-backend" => "${google_compute_backend_service.foo-bar-backend.self_link}"

  ~ module.fib.google_compute_url_map.fib-lb
      path_matcher.0.path_rule.0.service:        "https://www.googleapis.com/etc/" => "${var.foo_bar_backend}"  # via a variable export not shown here
      path_matcher.0.path_rule.1.service:        "https://www.googleapis.com/etc/" => "${var.foo_baz_backend}"

Plan: 4 to add, 2 to change, 2 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

And here is the (again, abridged) output from the non-dry-run:

```
...execution plan as above...

module.foo.google_compute_backend_service.foo-backend: Destroying... (ID: foo-backend)
module.foo.google_compute_instance_group.foo-bar-group: Creating...
...etc as plan above...
module.foo.google_compute_instance_group.foo-bar-group: Creation complete after 22s (ID:etc)
module.foo.google_compute_backend_service.foo-baz-backend: Creating...
...etc...

Error: Error applying plan:

3 error(s) occurred:

* module.foo.google_compute_backend_service.foo-bar-backend: 1 error(s) occurred:

* google_compute_backend_service.foo-bar-backend: Error creating backend service: googleapi: Error 400: Validation failed for instance 'projects/etc/instances/foo1': instance may belong to at most one load-balanced instance group., instanceInMultipleLoadBalancedIgs
* module.foo.google_compute_instance_group.foo-baz-group: 1 error(s) occurred:

* google_compute_instance_group.foo-baz-group: Error adding instances to InstanceGroup: googleapi: Error 503: Code: 'etc', backendError
* module.foo.google_compute_backend_service.foo-backend (destroy): 1 error(s) occurred:

* google_compute_backend_service.foo-backend: Error deleting backend service: googleapi: Error 400: The backend_service resource 'projects/etc/foo-backend' is already being used by 'projects/etc/foo-lb', resourceInUseByAnotherResource
```

Maybe this isn't resolvable declaratively? It seems like foo-lb can't be made to refer to foo-bar-backend unless the backend (and therefore the ig) are created, but it also can't create the new ig (and therefore the backend) until the old ig is deleted.

**Comment by sudaxl** [comment]
I too have this issue with Azure resources . When destroying Azure app service environment and its subnets. App service environment is deployed using ARM templates and hence cannot be deleted using destroy command. But when trying to destroy subnets associated with this app service environment they fail saying that a resource ( ASE) is using this subnet and hence can't be destroyed.

**Comment by bksaurabh96** [comment]
I too have the issue with terraform. While destroying the resources in azure, it's doesn't destroy the lock.

2 error(s) occurred:

* azurerm_role_assignment.push (destroy): 1 error(s) occurred:

* azurerm_role_assignment.push: authorization.RoleAssignmentsClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="ScopeLocked" Message="The scope '/subscriptions/ae1cfcb2-743efe4dddd8/resourceGroups/tahexampletest01/providers/Microsoft.ContainerRegistry/registries/tahexampletest01registry/providers/Microsoft.Authorization/roleAssignments/1fcc852c-759e-54c0-e1e0ae039260' cannot perform delete operation because following scope(s) are locked: '/subscriptions/ae1cfcb2-743efe4dddd8/resourceGroups/tahexampletest01'. Please remove the lock and try again."
* azurerm_role_assignment.pull (destroy): 1 error(s) occurred:

* azurerm_role_assignment.pull: authorization.RoleAssignmentsClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="ScopeLocked" Message="The scope '/subscriptions/ae1cfcb2-2928-743efe4dddd8/resourceGroups/tahexampletest01/providers/Microsoft.ContainerRegistry/registries/tahexampletest01registry/providers/Microsoft.Authorization/roleAssignments/5bd5dadc-f0b7-dba0-fbac-1c9f44082209' cannot perform delete operation because following scope(s) are locked: '/subscriptions/ae1cfcb2-743efe4dddd8/resourceGroups/tahexampletest01'. Please remove the lock and try again."
