### ISSUE TITLE
provisioner/chef: gracefully detect a reboot request

### ISSUE THREAD

**Issue by onedumslack** [hashicorp/terraform#15134]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
Please list the resources as a list, for example:
- provisioner
  - chef
  - connection

### Terraform Configuration Files
resource "null_resource" "bootstrap_chef" {
  depends_on = ["aws_instance.ec2"]
  count      = "${var.ec2_num_instances}"

  provisioner "chef" {
    environment            = "${var.environment}"
    node_name              = "${var.environment_short}-${var.project}-${var.uniq_env_id}-${count.index}-${element(aws_instance.ec2.*.id, count.index)}"
    server_url             = "${var.chef_server_url}"
    recreate_client        = true
    os_type                = "windows"
    run_list               = ["ll_aws_windows"]
    user_name              = "${var.chef_username}"
    user_key               = "${file("${var.chef_userkey}")}"
    attributes_json        = <<EOF
      {
        "host_settings": {
          "hostname": "${var.environment_short}-${var.project}-${var.uniq_env_id}-${count.index}"
        }
      }
EOF
    connection {
      type           = "winrm"
      https          = true
      port           = 5986
      insecure       = true
      host           = "${element(aws_instance.ec2.*.private_ip, count.index)}"
      user           = "${var.ec2_user}"
      password       = "${var.ec2_password}"
      timeout        = "10m"
    }
  }
}

### Expected Behavior
With the chef provisioner when a chef bootstrap reboots a node, during the bootstrap it should detect this gracefully and wait a timeout period for it to come back online and continue the chef bootstrap.

### Actual Behavior
Reboots of a node terminate the current terraform apply session immediately and don't recover.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Nothing non standard I believe.  Just a simple powershell_script resource in a recipe that requests the node to reboot after changing it's hostname.

### References
Test kitchen supports this functionality by looking for a windows exit code 35 and then it has a retry count and timeout for reconnecting back in and finishing running.

**Comment by onedumslack** [comment]
Another feature associated with this that would be extremely helpful is that if you could pass an argument to the provisioner telling it that when it detects a reboot to just exit successfully but don't try to reconnect.  This will allow to run cookbooks that do things like change the local admin password and then to reconnect again after the provisioner with different credentials using a local-exec.

**Comment by smastrorocco** [comment]
+1

**Comment by lokiwins** [comment]
+1

**Comment by ikari7789** [comment]
This would be a highly appreciated new feature!

**Comment by davelaramee-ssense** [comment]
+1

**Comment by bp8017** [comment]
+1

**Comment by SAPDanJoe** [comment]
+1

**Comment by OperationalDev** [comment]
+1

**Comment by pryorda** [comment]
+1

**Comment by cookiecurse** [comment]
+1 so many of us are still dealing with this issue :(

**Comment by vikrantkataria** [comment]
null_resource.chef_client (chef): [2020-07-15T12:14:17+00:00] FATAL: Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Reboot by Chef Infra Client", :timestamp=>2020-07-15 12:14:01.2509495 +0000, :requested_by=>"Restart Computer"}

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
