### ISSUE TITLE
Documentation: IAM role export attributes → reference within IAM role policy

### ISSUE THREAD

**Issue by kfrn** [hashicorp/terraform#15136]
Hi there, I’m looking at the documentation for [aws_iam_role_policy](https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html) and I think I have noticed a discrepancy.

In the [provided example](https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html#example-usage), an IAM role is declared, which is then referenced within the IAM role policy as so:

`role = "${aws_iam_role.test_role.id}”`

But, according to the [aws_iam_role](https://www.terraform.io/docs/providers/aws/r/iam_role.html) page, `aws_iam_role` doesn’t export an ID.
The documentation says that these [attributes](https://www.terraform.io/docs/providers/aws/r/iam_role.html) are exported:

* `arn` - The Amazon Resource Name (ARN) specifying the role.
* `create_date` - The creation date of the IAM role.
* `unique_id` - The stable and unique string identifying the role.
* `name` - The name of the role.
* `description` - The description of the role.

Unless I’m missing something, it doesn’t seem to add up. Should `role` within `aws_iam_role_policy` use a different attribute than ID (`unique_id`?), or is an ID in fact exported from the `aws_iam_role`?

### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
- documentation for
  - aws_iam_role
  - aws_iam_role_policy

Thanks in advance.

**Comment by radeksimko** [comment]
Hi @kfrn 
we typically don't document the `id` attribute as it is exported by design from _all_ resources and data sources.

We have some long-term plans for improving the documentation overall - e.g. generating parts of the documentation and documenting ID would probably fall into this category. I can't tell when we're going to get to it nor how would the real solution look like at this point, but it is something we're aware of.

I don't mind anyone raising PR which adds the ID to the docs in this context, but we plan to solve this in much wider context instead of chasing such changes across currently hundreds of resources. 😅

**Comment by kfrn** [comment]
Hi @radeksimko, thanks for the reply. That makes sense! I must have had happened to look at other resources which _did_ explicitly mention `id` as an export, hence my confusion.  
I may do a pull request, but glad to know that you are planning a global solution.
