### ISSUE TITLE
provider/google: add external IP resource

### ISSUE THREAD

**Issue by dgolja** [hashicorp/terraform#15147]
Similar as [AWS EIP](https://www.terraform.io/docs/providers/aws/r/eip.html) would be nice to have google provider support creation of an external IP. 

Suggested name `google_addresses`.

## Arguments Reference
The following arguments are supported:

* ip_version - (Optional) define the IP version. Valid value are ipv4 or ipv6. This default to ipv4
* type - (Required) Valid value are global or region.
* region - (Optional) if type is region you need to define a valid region
* instance - (Optional) instance ID

## Attributes Reference
* public_ip - Contains the public IP address

## Example

```hcl
resource "google_addresses" "static_ip" {
  ip_version = 4
  type      = "regional"
  region  = "us-central1
}
```

More info https://cloud.google.com/compute/docs/reference/latest/?hl=en_US

**Comment by rileykarson** [comment]
Hey @dgolja!
We have the [google_compute_address](https://www.terraform.io/docs/providers/google/r/compute_address.html) and [google_compute_global_address](https://www.terraform.io/docs/providers/google/r/compute_global_address.html) resources available for representing regional and global external IP address resources respectively.

It's worth noting that both of these resources only support ipv4 addresses in Terraform right now. If ipv6 support is a requirement for you, check out the [GCP Beta](https://cloud.google.com/compute/docs/reference/beta/globalAddresses) docs, and file an issue against Terraform so that we know there is demand for that feature.

**Comment by dgolja** [comment]
Legend !!! Looks like I missed that one. For now no need for `ipv6`. Closing this issue.
