### ISSUE TITLE
Interpolating computed subnets from a module into aws_db_subnet_group results in error

### ISSUE THREAD

**Issue by choppedpork** [hashicorp/terraform#15168]
### Terraform Version
v0.9.7

### Affected Resource(s)
- aws_db_subnet_group

### Terraform Configuration Files
Subnet module (trimmed down for brevity):
```hcl
data "aws_availability_zones" "azs" {}

resource "aws_subnet" "subnet" {
  vpc_id            = "${var.vpc_id}"
  cidr_block        = "${cidrsubnet(var.cidr_block, 10, 4 * var.subnet_octet + count.index)}"
  availability_zone = "${data.aws_availability_zones.azs.names[count.index % length(data.aws_availability_zones.azs.names)]}"
  count             = 4
}

output "ids" {
  value = "[${aws_subnet.subnet.*.id}]"
}
```

RDS module (trimmed down for brevity):

```hcl
resource "aws_db_subnet_group" "rds" {
  name        = "${var.environment}-db-access"
  description = "${var.environment} db subnet group"
  subnet_ids  = ["${var.subnets}"]
}
```

Plan (also trimmed):

```hcl
module "subnet" {
  source       = "../../modules/aws/subnet"
  environment  = "${var.environment}"
  cidr_block   = "1.2.3.0/16"
  subnet_octet = "2"
  vpc_id       = "${data.terraform_remote_state.vpc.vpc_id}"
}

module "rds" {
  source          = "../../modules/aws/rds"
  environment     = "${var.environment}"
  subnets         = "${module.subnet.ids}"
  instance_class  = "db.m4.xlarge"
  storage_size    = "250"
  multi_az        = "true"
  security_groups = ["${module.subnet.security_group}"]
}
```

### Debug Output
I'm pasting partial DEBUG output here as it seems to confirm my hypothesis below - note the empty `SubnetIds: []`:

```
2017/06/07 18:46:23 [DEBUG] plugin: terraform: aws-provider (internal) 2017/06/07 18:46:23 [DEBUG] No meta timeoutkey found in Apply()
2017/06/07 18:46:23 [DEBUG] plugin: terraform: aws-provider (internal) 2017/06/07 18:46:23 [DEBUG] Matching ^aws: with env
2017/06/07 18:46:23 [DEBUG] plugin: terraform: aws-provider (internal) 2017/06/07 18:46:23 [DEBUG] Create DB Subnet Group: {
2017/06/07 18:46:23 [DEBUG] plugin: terraform:   DBSubnetGroupDescription: "xx db subnet group",
2017/06/07 18:46:23 [DEBUG] plugin: terraform:   DBSubnetGroupName: "xx-db-access",
2017/06/07 18:46:23 [DEBUG] plugin: terraform:   SubnetIds: [],
2017/06/07 18:46:23 [DEBUG] plugin: terraform:   Tags: [{
2017/06/07 18:46:23 [DEBUG] plugin: terraform:       Key: "env",
2017/06/07 18:46:23 [DEBUG] plugin: terraform:       Value: "xx"
2017/06/07 18:46:23 [DEBUG] plugin: terraform:     }]
2017/06/07 18:46:23 [DEBUG] plugin: terraform: }
2017/06/07 18:46:23 [DEBUG] plugin: terraform: aws-provider (internal) 2017/06/07 18:46:23 [DEBUG] [aws-sdk-go] DEBUG: Request rds/CreateDBSubnetGroup Details:
2017/06/07 18:46:23 [DEBUG] plugin: terraform: ---[ REQUEST POST-SIGN ]-----------------------------
2017/06/07 18:46:23 [DEBUG] plugin: terraform: POST / HTTP/1.1
2017/06/07 18:46:23 [DEBUG] plugin: terraform: Host: rds.ap-southeast-1.amazonaws.com
2017/06/07 18:46:23 [DEBUG] plugin: terraform: User-Agent: aws-sdk-go/1.8.25 (go1.8; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.6
2017/06/07 18:46:23 [DEBUG] plugin: terraform: Content-Length: 194
2017/06/07 18:46:23 [DEBUG] plugin: terraform: Authorization: AWS4-HMAC-SHA256 Credential=accesskey/20170607/ap-southeast-1/rds/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=8d2008306a65902b0188xxxxxxxxxxa4041226683907ce84d20aa31
2017/06/07 18:46:23 [DEBUG] plugin: terraform: Content-Type: application/x-www-form-urlencoded; charset=utf-8
2017/06/07 18:46:23 [DEBUG] plugin: terraform: X-Amz-Date: 20170607T174623Z
2017/06/07 18:46:23 [DEBUG] plugin: terraform: Accept-Encoding: gzip
2017/06/07 18:46:23 [DEBUG] plugin: terraform: 
2017/06/07 18:46:23 [DEBUG] plugin: terraform: Action=CreateDBSubnetGroup&DBSubnetGroupDescription=xx+db+subnet+group&DBSubnetGroupName=xx-db-access&SubnetIds=&Tags.Tag.1.Key=env&Tags.Tag.1.Value=xx&Version=2014-10-31
```

### Expected Behavior
aws_db_subnet_group successfully created using the subnet IDs exposed by the subnet module

### Actual Behavior
(slightly edited for brevity - removed tags)
```
terraform apply -target module.rds.aws_db_subnet_group.rds
data.terraform_remote_state.vpc: Refreshing state...
data.aws_availability_zones.azs: Refreshing state...
aws_subnet.subnet.3: Refreshing state... (ID: subnet-abbd8add)
aws_subnet.subnet.2: Refreshing state... (ID: subnet-435a5727)
aws_subnet.subnet.1: Refreshing state... (ID: subnet-0ebd8a78)
aws_subnet.subnet.0: Refreshing state... (ID: subnet-57595433)
module.rds.aws_db_subnet_group.rds: Creating...
  arn:          "" => "<computed>"
  description:  "" => "xx db subnet group"
  name:         "" => "xx-db-access"
  name_prefix:  "" => "<computed>"
  subnet_ids.#: "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* module.rds.aws_db_subnet_group.rds: 1 error(s) occurred:

* aws_db_subnet_group.rds: Error creating DB Subnet Group: InvalidSubnet: Subnet IDs are required.
	status code: 400, request id: 5c53b26c-4ba7-11e7-a171-11553023b181
```
### Steps to Reproduce
1. `terraform apply -target module.rds.aws_db_subnet_group.rds`

### Important Factoids
This works perferctly fine when instead of `${module.subnet.ids}` I specify a list variable containing all the subnets. ~My uneducated guess would be that what's happening here is terraform tries to create the subnet group without the IDs and then add them in afterwards?~

Looking at the DEBUG log it definitely looks like terraform is creating a db subnet group without specifying any subnets (I'm assuming that it wants to configure the subnet IDs in the next step which doesn't work here as subnet IDs are mandatory).

At the time of running `terraform apply -target module.rds.aws_db_subnet_group.rds` the subnet module is already applied (the subnets exist).

edit:
removed efs reference as after more testing this seems to also affect aws_efs_mount_targets

**Comment by apparentlymart** [comment]
Hi @choppedpork! Sorry for this weird behavior...

I concur that from the debug output it seems like the DB subnet group is being created before the subnets have been populated.

I notice that you're passing most (all?) of your lists with extra wrapping `[]` brackets, like in `value = "[${aws_subnet.subnet.*.id}]"`. This is an old requirement that we're still trying to support for backward compatibility but you may have tripped over here a scenario where the compatibility isn't quite working right.

Are you able to try again with the config updated to _not_ include those extra list brackets? They are redundant because Terraform already knows that the value inside is a list, and so logically it represents a list of lists, which we're trying to flatten out for compatibility with the old behavior. It should only be required to use the brackets in cases where you are constructing a list from several non-list values.

**Comment by choppedpork** [comment]
Hello @apparentlymart, thanks for looking into this!

You're absolutely right - this was indeed the problem here. After getting rid of the square brackets both in my outputs and when passing parameters to the module the behaviour is exactly as expected and both `aws_db_subnet_group`s and `aws_efs_mount_target`s are created correctly. I think what threw me off here was that some other modules I've created did not exhibit this behaviour and worked correctly with the extra brackets.

Is the backward compatibility something you intend on supporting past 0.10? I'm wondering if this is something that could be validated during the planning stage if that's the case?

**Comment by apparentlymart** [comment]
Thanks for the update, @choppedpork. We ended up in a bit of a sticky spot with those wrapping brackets due to some core changes that exposed some faulty assumptions we needed to patch up. Unfortunately it seems that some edge cases remained where we weren't _quite_ following the old behavior, and this looks like one of them.

This compatibility mode will remain through the 0.10 line at least, since there are still lots of people depending on it in the simpler cases, but we _will_ phase it out in a later version as part of some other updates (still in early planning/prototype stages) to the configuration language that depend on this ambiguity being resolved. Perhaps somewhere along the way we'll start introducing some deprecation warnings to prepare people for the change, but we weren't able to do that so far due to the way we were forced to implement this compatibility mode, which is in a part of the codebase that can't currently emit warnings.
