### ISSUE TITLE
s3 backend for remote state requires "region" to be set while doc says it's an optional parameter.

### ISSUE THREAD

**Issue by VincenzoDo** [hashicorp/terraform#15188]
Hi there,

### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
- s3 backend

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket = "testbucket"
    key    = "test"
    endpoint = "myendpoint"
    access_key = "xxxxx"
    secret_key= "xxxx"
  }
}

```

### Debug Output
terraform asking for region and not accepting empty string:
https://paste.ubuntu.com/24808114/

### Expected Behavior
I shouldn't be prompted to enter the region value OR I the doc needs to be changed (Region -> Required and not Optional) see: https://www.terraform.io/docs/backends/types/s3.html#region

### Actual Behavior
I'm prompted to enter the region value.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. paste the backend into your main.tf
2. terraform init

### Important Factoids
Working with an S3 capable API which doesn't need region specified.

**Comment by ktf** [comment]
I've a similar problem. Moreover our S3 backend simply uses the "default" region and while that works fine with aws cli, terraform insist in having an actual one.

**Comment by deitch** [comment]
This remains an issue. It looks like it won't even source it from the profile, e.g.

```hcl
terraform {
  backend "s3" {
    bucket = "testbucket"
    key    = "test"
    profile = "someprofile"
  }
}
```

and then with `~/.aws/config` set to:

```toml
[profile someprofile]
region="us-east-1"
```

You get the same error message.

Has anything changed in 0.12 for this? Looks like a lot of the backend code was broken out into https://github.com/hashicorp/aws-sdk-go-base

**Comment by apparentlymart** [comment]
The documentation here is indeed incorrect. I suspect it was originally marked as "Optional" originally because the phrasing was something like "Required unless the `AWS_DEFAULT_REGION` environment variable is set", but the docs were later reworked to show the names and environment variables in a more compact way, without accounting for the fact that it would then seem to imply that everything is optional, when in fact there are several arguments that must be set _somehow_ but there are in practice a number of different ways to set them:

* `region` is required unless `AWS_DEFAULT_REGION` is set.
* `access_key` and `secret_key` are required unless the credentials environment variables are set or suitable credentials can be obtained from the `~/.aws/credentials` file, some other configured source, etc.

I think it'll be necessary to have a separate section of the page describing these details because the interactions between these different settings are a little too subtle to described concisely in a flat argument list.

The behavior of these arguments is actually handled by some code shared with [the AWS provider](https://github.com/terraform-providers/terraform-provider-aws) so any changes to their _behavior_ would need to be made in the AWS provider first and then the backend can follow suit. With that in mind, I'm going to label this as a documentation bug for now to represent the work to make the documentation clearer, and I would suggest opening in issue in the AWS provider if you see missing capabilities in the current implementation; we'll bring in any upstream changes from the AWS provider once they are merged over there.

**Comment by deitch** [comment]
> I think it'll be necessary to have a separate section of the page describing these details because the interactions between these different settings are a little too subtle to described concisely in a flat argument list.

Yes, quite agree. It is something like, "you must have _one_ of the following combinations:

* `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
* `AWS_PROFILE` set and available in your credentials file, plus one of 
* `access_key` and `secret_key` set in the backend config
* `profile` set in the backend config and available in your credentials file

In addition, you must have one of:

* `AWS_DEFAULT_REGION` is set
* `region` is set in backend config

Separately, any idea why it does not source the `region` from the specified profile? It doesn't matter if I use `AWS_PROFILE` env var or `profile` in backend setting, it doesn't source it from `~/.aws/config` and fails unless I explicitly set `AWS_DEFAULT_REGION` or `region` in backend setting.

**Comment by apparentlymart** [comment]
I don't know why the region from the provile is not used. The AWS provider team probably has a better idea of why it is implemented that way; as far as I know, the shared credentials library that is used by both this backend and the AWS provider (maintained by the AWS provider team) is using standard credentials mechanisms implemented in the AWS SDK, so I would've expected it to behave consistently with the AWS tools (and indeed, that is our goal) so if that isn't the case then I think we'd consider that to be a bug, but I will leave the AWS provider team to make that determination.

**Comment by deitch** [comment]
> I will leave the AWS provider team to make that determination

Makes sense. Do you know who to @ flag on that team so they can see it? More than happy to open an issue there, too, although with 2,061 open issues (and counting), I think it might be better if I actually flagged someone specific.

**Comment by apparentlymart** [comment]
Opening an issue in the AWS provider is the best way, since that's where any changes would be made for this first. (We'd just pull in whatever changes are made upstream in a future Terraform Core release)

**Comment by deitch** [comment]
Will do. I will reference this issue there.

By the way, I looked at the code base for backend off of master, it looks like a lot of it is abstracted out to https://github.com/hashicorp/aws-sdk-go-base ?

**Comment by deitch** [comment]
Opened. Thanks @apparentlymart

**Comment by mildwonkey** [comment]
Since the linked issue was closed and the s3 backend (and documentation) updated since this was opened, I am going to close this issue.

If you still are experiencing this problem in Terraform v0.13, please open a new issue and fill out the template.
Thanks!
