### ISSUE TITLE
Interpolation order issue

### ISSUE THREAD

**Issue by raphink** [hashicorp/terraform#15192]
Using the following MWE with Terraform 0.9.8 fails:

```hcl
data "template_file" "infra" {
  template = "1234"
}

resource "rancher_environment" "environment" {
  name          = "foo"
  description   = "foo"
  orchestration = "cattle"
  member        = ["${map("external_id", data.template_file.infra.rendered, "external_id_type", "github_team", "role", "owner")}"],
}
```

Error is:

```shell
3 error(s) occurred:

* rancher_environment.environment: "member.0.external_id": required field is not set
* rancher_environment.environment: "member.0.external_id_type": required field is not set
* rancher_environment.environment: "member.0.role": required field is not set
```

Use static string or a variable instead of the data source works file.

**Comment by apparentlymart** [comment]
Hi @raphink! Sorry things aren't working as expected here.

This sort of dynamic construction of blocks is not supported at this time. While there are some ways to make it work in some cases, it's more a side-effect of the implementation than an intentional decision, and if you _do_ manage to get it working it will likely be broken by future Terraform versions as we continue to improve the configuration language.

There was some previous discussion about this in #7034, and we will be starting to look at some configuration language improvements in the near future that might include a way to do this, though it's too early to say right now what order these things will get done.

I assume your example here was just a cut-down, contrived one to illustrate your point, and in reality you've got a variable-length list or something similar, but in case anyone else finds this issue in future and might be wondering about this, for simple cases like that example it can be expressed using the more natural block syntax:

```hcl
resource "rancher_environment" "environment" {
  name          = "foo"
  description   = "foo"
  orchestration = "cattle"

  member {
    external_id = "${data.template_file.infra.rendered}"
    external_id_type = "github_team"
    role = "owner"
  }
}
```

Since we already have #7034 open, I'm going to close this one just to keep the discussion consolidated over there. If you'd like to share some information on your use-case over in that issue for posterity that'd be welcome and very helpful when we come to design features to solve this class of problem.

Thanks, and sorry again about the current limitations in this area.

**Comment by raphink** [comment]
@apparentlymart yes indeed, my actual case includes a variable list of maps, passed as an argument to a module (and empty by default) and a default map that must be added to that list. I haven't found another way to perform this, but then the interpolation fails, as outlined in this issue.

**Comment by raphink** [comment]
Here's the full code that I'm trying to make work:

```hcl
variable "environment_name" {}

variable "environment_description" {
  default = ""
}

variable "members" {
  default = []
}

data "github_team" "infra" {
  slug = "infrastructure-division"
}

resource "rancher_environment" "environment" {
  name          = "${var.environment_name}"
  description   = "${var.environment_description}"
  orchestration = "cattle"
  member        = ["${concat(var.members, list(map("external_id", data.github_team.infra.id, "external_id_type", "github_team", "role", "owner")))}"],
}
```
