### ISSUE TITLE
Delete an S3 Object ?

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#15216]
### Terraform Version
0.9.8 

### Question / Feature Request
Is there an option to delete an S3 Object? If not, can you please take this as a feature request? Thanks.

**Comment by apparentlymart** [comment]
Hi @vikas027! Thanks for this feature request.

I want to make sure I understand what you're asking here. It should be the case today that any S3 object created by Terraform will be deleted after the resource is removed from configuration. If that's not true then that's a bug. Terraform does not delete (or interact in any way) with objects it doesn't manage.

**Comment by vikas027** [comment]
Hey @apparentlymart ,

My idea is to delete an S3 object(s) or file(s) which are not created by Terraform. I know I can get this done through `null_resource`, but was just looking if it can natively be done by Terraform.

**Comment by apparentlymart** [comment]
That isn't really within Terraform's usual model; since Terraform is declarative, is is based around a description of what *should* exist, and can't really describe a _negative_ in a reasonable way.

This sort of imperative action is better done with direct API calls, AWS CLI, etc.

The closest that can be done with Terraform is to `terraform import` the resource you want to delete and then apply a configuration without it, thus causing Terraform to think it created it and must now delete it.

**Comment by vikas027** [comment]
Thanks. I wanted to close this yesterday, but my iPhone app doesn't allows me to do so
