### ISSUE TITLE
Plan version magic byte should be updated upon every release.

### ISSUE THREAD

**Issue by carlosonunez** [hashicorp/terraform#15234]
Howdy, Hashicorp people!

### Terraform Version

`Terraform v0.9.8`

### Affected Resource(s)

Core Terraform code.

### Terraform Configuration Files
```hcl
resource "aws_vpc" "infrastructure" {
  cidr_block = "10.1.0.0/16"
  tags = {
    Name = "vpc.carlosnunez.me"
    Environment = "dev"
  }
}
```

### Debug Output
https://gist.github.com/carlosonunez/af38d604bd48eb771b4cdb9bbd0bd761

### Panic Output
No panic reported.

### Expected Behavior
What should have happened?

```bash

[2017-06-09 16:22:54 carlosnunez@DESKTOP-RHPB7LP <<master>> infrastructure] $: terraform show failing_temp.tfplan
Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

Plan read error: unknown or outdated plan file version: 1. (Current plan version: 4)
# 4 is an example
```

### Actual Behavior
```bash
[2017-06-09 16:22:54 carlosnunez@DESKTOP-RHPB7LP <<master>> infrastructure] $: terraform show failing_temp.tfplan
Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Decoding state file version failed: invalid character 'f' in literal true (expecting 'r')

Plan read error: gob: wrong type (map[string]string) for received field InstanceState.Meta
```

### Steps to Reproduce
See the gist to reproduce.

### Important Factoids
Nothing out of the ordinary!

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
None that I know of.

**Comment by apparentlymart** [comment]
Hi @carlosonunez! Thanks for reporting this.

We are currently not updating the version here because the plan format is still evolving quickly and this would add unnecessary additional process around releases. While I agree that the error message you got here is not user-friendly, using an old plan on a new version of Terraform is considered an edge case and so for the moment we're accepting the strange error message as a compromise.

In general it should be assumed that plan files do not survive Terraform upgrades. As things stablize we will likely to start making better use of this version numbering scheme to produce a better error message in this scenario, but for now we are specifically not supporting parsing plan files by any other tool than Terraform itself since we're not ready to commit to a compatibility guarantee in this area, since the plan format is expected to change significantly.

**Comment by carlosonunez** [comment]
That makes a lot of sense. Thanks for the explanation, Martin.

Carlos

**Comment by ctippur** [comment]
Are there any workaround?

**Comment by apparentlymart** [comment]
Hi @ctippur!

I'm not sure what exactly you need to work around here, since this issue was about producing a better error message in this case. Could you be more specific? Thanks!

**Comment by ctippur** [comment]
My bad. I was wondering if there is a prescribed way to tackle corrupted tfstate. I have a backend resource and I seem to get the same cryptic message.

**Comment by apparentlymart** [comment]
@ctippur it sounds like you have a different problem here, since this issue is about plan files rather than state files. I'd encourage you to open a new top-level issue so we can dig into that some more.

**Comment by carlosonunez** [comment]
Martin, I'm good with closing this as "won't do." Your reasons made sense.

Carlos

**Comment by apparentlymart** [comment]
Thanks @carlosonunez. We likely will start doing what you asked eventually, but agreed that we don't need to leave this issue open to mark that, since it'll just be a natural part of eventually stabilizing the plan format.
