### ISSUE TITLE
provisioner/chef: knife exit code on Windows is always 0 causing install issues

### ISSUE THREAD

**Issue by dhoer** [hashicorp/terraform#15287]
Chef client download is hardcoded and can't be changed.  This causes issues because you can be black listed by Chef causing "The remote server returned an error: (405) Method Not Allowed." error.  

Note how Terraform's error summary statement erroneously gives the impression that Chef client name already exists on Chef server when this occurs on Windows OS:

```
aws_instance.windows_example (chef): Downloading Chef Client...
aws_instance.windows_example (chef): Installing Chef Client...
aws_instance.windows_example (chef): Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (405) Method Not Allowed."
aws_instance.windows_example (chef): At C:\Temp\ChefClient.ps1:32 char:1
aws_instance.windows_example (chef): + $downloader.DownloadFile($url, $dest)
aws_instance.windows_example (chef): + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aws_instance.windows_example (chef):     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
aws_instance.windows_example (chef):     + FullyQualifiedErrorId : WebException

aws_instance.windows_example (chef): Creating configuration files...
aws_instance.windows_example: Still creating... (3m10s elapsed)
aws_instance.windows_example (chef): Generate the private key...
aws_instance.windows_example (chef): Cleanup user key...
Releasing state lock. This may take a few moments...
Error applying plan:

1 error(s) occurred:

* aws_instance.windows_example: 1 error(s) occurred:

* Chef client "my.example.i-0b5b56a0d47f48997" already exists, set recreate_client=true to automatically recreate the client
```

**Comment by svanharmelen** [comment]
Thanks for the report! These are actually 2 different things... The first issue is about the URL being hardcoded. For this I would like to refer you to issue #6455 which is about the exact same thing.

The second issue is actually a problem with `knife` running on Windows. It doesn't seem to use the same exit codes as on *ux 😞 

So let me just tweak your issue message and see if I can make some time for this in the near future...

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
