### ISSUE TITLE
Triggering null_resource by recreation of dependent resources

### ISSUE THREAD

**Issue by mandelsoft** [hashicorp/terraform#15282]
### Terraform Version
0.9.8

### Problem

I'm using a `null_resource` to execute a command.
With `depends_on` it is possible to assure that this command is executed after a given other resource
is generated. 

But it does not retrigger the execution, if the given resource is regenerated. 
Even the `trigger` feature does not help because the resource (for example `local_file`) does not offer
an attribute reflecting the generation version/sequence number or something like this.

Also a file content cannot be used as trigger, because `file()` leads to an error, if the file is not available.

The only way I found to reexecute the `null_resource` is to manually taint it.

It would be nice to be able to trigger the execution by the recreation of another resource.

Thanks
Uwe

**Comment by apparentlymart** [comment]
Hi @mandelsoft,

If re-triggering the `null_resource` provisioner when the file contents change is your goal, the following should work:

```hcl
resource "local_file" "example" {
  content  = "..."
  filename = "${path.module}/example.txt"
}

resource "null_resource" "example" {
  triggers = {
    content = "${local_file.example.content}"
  }
  provisioner "..." {
    # ...
  }
}
```

Note that in this scenario it's not necessary to _also_ use `depends_on`, because the interpolation into the `content` trigger value creates the dependency implicitly.

**Comment by mandelsoft** [comment]
Hi @apparentlymart,

I already know your proposal, but unfortunately it does not solve my problem. 
It retriggers the `null_resource` execution if the INTENDED file content changes, but NOT when the file is just recreated by the other resource. Unlike resources like the `aws_security_group_rule`, where a new resource id is provided if the resource (with the same content) is recreated (because someone has probably deleted it), there is not such trigger for `local_file`

In general it would be very useful to have triggers based on the existence of a file, as mentioned above the functon `file` cannot be used here because it fails for non-existent files. May be just an optional parameter could be added to allow specifying a default content.

**Comment by shantanugadgil** [comment]
hi @apparentlymart 

my use case is the similar to @mandelsoft. I too have a script which runs as part of a `null_resource`.

For me, I `tainted` the main resource and ran a `terraform apply`. I was hoping that the `null_resource` would rerun the script, which would be necessary as the script does necessary "bootstrap" activity.

For now, I am making do by tainting the `null_resource` as well.

FWIW; I am using this with Terraform 0.11.7 and the LXD provider.

Regards,
Shantanu

**Comment by apparentlymart** [comment]
Sorry I apparently missed your reply some months ago, @mandelsoft. It's tough to keep track of discussion threads here in GitHub issues, which is one of the reasons why we try to encourage asking questions in other forums. :confounded:

Reading this again, I think I understand better what you are both trying to achieve. If you want the provisioner to be re-run each time the `local_exec` resource changes (in @mandelsoft's example) then the provisioner can be attached directly to that resource, rather than to the separate `null_resource` resource:

```hcl
resource "local_file" "example" {
  content  = "..."
  filename = "${path.module}/example.txt"

  provisioner "..." {
    # ...
  }
}
```

The `local_file` resource could potentially offer something like a uuid that just gets assigned on each update so there'd be something to use to trigger changes elsewhere. This is not really an intended use of Terraform (it's more about making infrastructure match configuration rather than executing arbitrary actions with side-effects) but I understand that it's often convenient to use provisioners to deal with actions Terraform doesn't natively support, so if you'd like to request that it could be done in [the `local` provider repository](https://github.com/terraform-providers/terraform-provider-local). The team is currently focused elsewhere and so wouldn't be able to jump on that right away, but having the issue recorded there will make it more visible when planning future work.
