### ISSUE TITLE
Terraform state commands should prompt before running

### ISSUE THREAD

**Issue by xocasdashdash** [hashicorp/terraform#15283]
I'm trying to fix a state issue (not related) and while exploring the terraform state command i accidentally deleted it after running:

`terraform state rm`

IMHO this command should not destroy the state when run without any arguments. 

### Terraform Version
Terraform v0.9.8

### Expected Behavior
Nothing should have been deleted from the state.

### Actual Behavior
Everything was deleted 

### Steps to Reproduce
1. `terraform state rm`

**Comment by apparentlymart** [comment]
Yikes, @xocasdashdash! Sorry for this startling behavior.

This "match everything by default" behavior is common to several commands but I completely agree that it's a bad default for this command, given how destructive it is. At the very least we should make this command fail if no arguments are given.

Prompting for approval is also an interesting idea, but might be trickier since these commands tend to be used by people in scripts. Let's start with just making it be mandatory to provide at least one argument, and see if having to correctly type out a resource address serves as confirmation enough, since that way we can avoid making a breaking change to scripts. (Except scripts that are intentionally deleting _everything_, but that seems unlikely.)

**Comment by xocasdashdash** [comment]
@apparentlymart that sounds reasonable. Maybe change the  `terraform state` output to reflect that too.

**Comment by apparentlymart** [comment]
Thanks for pointing this out @xocasdashdash! I just merged the change we discussed and so it should be included in the forthcoming 0.10.0 release.
