### ISSUE TITLE
index() function returns nothing when item not found

### ISSUE THREAD

**Issue by trung** [hashicorp/terraform#15291]
### Terraform Version
```
$ terraform -v
Terraform v0.9.8
```

### Terraform Configuration Files
```hcl
variable "myList" {
  type = "list"
  default = ["item1", "item2"]
}

variable "item" {
}

output "found" {
  value = "${index(var.myList, var.item) >= 0 ? true : false}"
}
```

### Debug Output
```
2017/06/14 16:26:50 [WARN] Output interpolation "found" failed: index: Could not find 'xxx' in '[{Variable (TypeString): item1} {Variable (TypeString): item2}]' in:

${index(var.myList, var.item) >= 0 ? true : false}
```

### Actual Behavior
Should display `found = false`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Enter `xxx`

It is a simple fix in `interpolate_funcs.go#interpolationFuncIndex()` but i'm not sure the current behaviour is intentional

**Comment by trung** [comment]
Please let me know if this is ok so i can create a PR

**Comment by apparentlymart** [comment]
Hi @trung,

At present it is intentional that this function returns an error if the given value is not found, since it assumes you're controlling the input list and want to find a known value. I can definitely see the use-case for a _different_ function to test if a given value is present in the list at all:

```hcl
    value = "${contains(var.mylist, var.item)}" # returns a boolean result
```

In principle that could be used to conditionally evaluate an expression that _also_ uses `index`, though right now that would be blocked by hashicorp/hil#50. We're planning to address that limitation, but for the moment a `contains` function would be limited to the above use-case, which I think gets you what you need here. If you'd like to work on such a function, I'd be happy to review a PR for it!

**Comment by trung** [comment]
Hi @apparentlymart, I'd love to fix the root rather than creating a new function just to cover an edge case for an existing one. 

Currently I have a smelly workaround
```hcl
value = "${length(var.myList) == length(compact(split(",", replace(join(",", var.myList), var.item, "")))) ? false : true}"
```
which works.

Regarding https://github.com/hashicorp/hil/issues/50, does it mean the boolean expression would catch error and evaluted to *false* so without changing `index()`, we can still do `
value = "${index(var.myList, var.item) >= 0 ? true : false}"`?

**Comment by apparentlymart** [comment]
I don't consider having a separate function to be a _workaround_; there are legitimate uses for the `index` function to return an error if the given value isn't found, and if we were to make it return `-1` there would be no reasonable way to recover that previous behavior, and the result would usually be a different, confusing error message.

For interpolation functions we prefer each one to solve an orthogonal problem: determining whether a particular item is in a list is a different problem than finding the index where an item can be found. Your stated use-case is finding out whether a given item is in a list, which doesn't require knowing the _index_ of that item at all.

The problem that hashicorp/hil#50 is describing relates to an expression like this:

```hcl
  value = "${contains(var.mylist, var.item) ? index(var.mylist, var.item) : var.default_index}"
```

The expected behavior of the above would be that if the given item is not in the list it would return `var.default_index`, but due to bug hashicorp/hil#50 what would actually happen is that this would fail due to still trying to evaluate `index(var.mylist, var.item)`. Once that issue is fixed, the above expression would work and return a valid result in all cases.

**Comment by trung** [comment]
@apparentlymart thanks for the explanation. It makes sense. 
Let me work on the `contains()` function.

**Comment by trung** [comment]
@apparentlymart please review the above commit, i'll create a PR if it's ok

**Comment by apparentlymart** [comment]
Looks okay to me. Please do create the PR!

**Comment by trung** [comment]
thanks. PR https://github.com/hashicorp/terraform/pull/15322
