### ISSUE TITLE
Repeats security group creation / deletion

### ISSUE THREAD

**Issue by civitaspo** [hashicorp/terraform#15316]
Hi there, I think this is a bug.
I wrote the reproduce case, could you see this? https://github.com/civitaspo/terraform-issue-aws_security_group_rule

### Terraform Version
0.9.8

### Terraform Configuration Files
See. https://github.com/civitaspo/terraform-issue-aws_security_group_rule/blob/master/terraform.tf

### Debug Output
See. https://github.com/civitaspo/terraform-issue-aws_security_group_rule#log

### Expected Behavior
See. https://github.com/civitaspo/terraform-issue-aws_security_group_rule#whats-the-issue

### Actual Behavior
See. https://github.com/civitaspo/terraform-issue-aws_security_group_rule#whats-the-issue

### Steps to Reproduce
See. https://github.com/civitaspo/terraform-issue-aws_security_group_rule#how-to-reproduce-the-issue

### Important Factoids
Nothing, this issue is occurred in any aws account.

### References
- https://github.com/civitaspo/terraform-issue-aws_security_group_rule

**Comment by stack72** [comment]
Hi @civitaspo 

Sorry for the issue here, it seems to be that you are mixing security groups with inline rules and then using security_group_rules as well

We have a [notice](https://www.terraform.io/docs/providers/aws/r/security_group.html) at the top of the docs that suggests that this isn't currently possible to do

Sorry for the issue

Paul

**Comment by civitaspo** [comment]
Oh...I see. Thanks a lot for the comment!
