### ISSUE TITLE
Terninary in outputs cannot contain resources that have 0 count

### ISSUE THREAD

**Issue by ctompkinson** [hashicorp/terraform#15333]
I want to use variable resources so that I can flag spot instances on and off using a terninary which works perfectly fine apart from rolling both of my ASGs into one unified output.

Outputs are missing when one of the resource counts is zero when my expected output would be the remaining resource.

I've rewritten my problem to be using simple local_file resources to focus the actual issue.

Is there a way to do what I want to accomplish that I'm missing or is this an expected result?

### Terraform Configuration Files
```hcl
variable "foo" { default = "-1" }

resource "local_file" "foo" {
    count    = "${var.foo == "-1" ? 0 : 1}"
    content  = "foo!"
    filename = "${path.module}/foo"
}

resource "local_file" "bar" {
    count    = "${var.foo == "-1" ? 1 : 0}"
    content  = "bar!"
    filename = "${path.module}/bar"
}

# No Output
output "output_file" { value = "${var.foo == "-1" ? local_file.bar.filename : local_file.foo.filename}" }

# Has Output
output "bar" { value = "${var.foo == "-1" ? local_file.bar.filename : "x"}" }
```

### Expected Behavior
```
$ terraform apply
local_file.bar: Refreshing state... (ID: 3811e1a645e5371113584e6d18ff4843378ae590)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

output_file = /Users/ctompkinson/Desktop/bar
bar = /Users/ctompkinson/Desktop/bar
```

### Actual Behavior
```
$ terraform apply
local_file.bar: Refreshing state... (ID: 3811e1a645e5371113584e6d18ff4843378ae590)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bar = /Users/ctompkinson/Desktop/bar
```

**Comment by apparentlymart** [comment]
Hi @ctompkinson! Sorry this isn't working as expected.

What you're seeing here is the issue captured as hashicorp/hil#50.

For now, there is a different way to write what you're trying to achieve here:

```
output "output_file" {
  value = "${element(concat(local_file.bar.*.filename, local_file.foo.*.filename), 0)}"
}

output "bar" {
  value = "${element(concat(local_file.bar.*.filename, list("x")), 0)}"
}
```

This works because the splat operator `*` evaluates to an empty list when `count = 0`.

For now, this is the recommended workaround. It will take some refactoring of the interpolation language to fix hashicorp/hil#50, so it should get done eventually but not in the immediate term.

Thanks for reporting this! Since we already have the problem captured in that other issue, I'm going to close this just to keep the discussion consolidated.
