### ISSUE TITLE
Terraform template file not rendering

### ISSUE THREAD

**Issue by fstuck37** [hashicorp/terraform#15337]
I'm having an issue similar to one mentioned in #11144 with variables within a script used in a template_file using Terraform v0.9.8
This is the portion of the script that I'm having issues with:

for i in "$${arr[@]}"
do
   var1=$${i%:*};
   var2=$${i#*:};
done;

When used individually this errors within all three of the double dollar locations.
For example on the first line:
failed to render : parse error at 1:17: expected expression but found invalid sequence "@"

I'm thinking that since we escape the $ (using the double $) terraform should ignore what's with the {}.

This works as expected when the variable is a simple name for example:
   echo " port = $${PORT}"

Any suggestions would be appreciated.
Thanks
Fred

**Comment by apparentlymart** [comment]
Hi @fstuck37! Sorry this isn't working as expected.

If you are able it would help to see the `data "template_file" ...` block from your configuration, to see how you are calling into this template. There are unfortunately some differences in approach depending on whether the template is being used inline in your configuration or referenced from an external file.

**Comment by fstuck37** [comment]
Hi Martin,
First off thank you so much for the prompt reply.
Currently, I'm doing it inline but I'm not opposed to using an external file if that will help.

Here is a larger snippet of code:
data "template_file" "shell_script" {
  template = <<-EOF
#!/bin/bash -x

....
declare -a arr=(${var.apps});
COUNTER=1;
for i in "$${arr[@]}"
do
  var1=$${i%:};
  var2=$${i#:};

....

  COUNTER=$[$COUNTER +1]
done;

.....
  EOF
}

Thanks again,
Fred

**Comment by apparentlymart** [comment]
Hi @fstuck37,

This issue was migrated automatically over to the repository for the template provider, as terraform-providers/terraform-provider-template#9, but I'm going to reply here since you'd already posted your config here and I think I see the problem.

To understand what's going on here, it's important to understand what levels of parsing are going on:

* First, the configuration language parser locates the `data` block and the arguments within it, extracting the contents of your "heredoc" as a raw string.
* Second, Terraform does an interpolation pass over all of the strings found in configuration, producing the final string that gets passed through to the provider.
* The template provider then looks at its `template` argument -- which has, by now, already had one "pass" of template parsing -- and does _another_ interpolation pass, using the variables given in `vars`.

The important detail here is that both Terraform itself (in the configuration processing) _and_ the template provider are both trying to parse a template here. Because of this, it's necessary to escape for _both_ passes, by including a third dollar sign:

```hcl
data "template_file" "shell_script" {
template = <<-EOF
#!/bin/bash -x

....
declare -a arr=(${var.apps});
COUNTER=1;
for i in "$$${arr[@]}"
do
var1=$$${i%:};
var2=$$${i#:};

....

COUNTER=$[$COUNTER +1]
done;

.....
EOF
}
```

Now Terraform's first pass will remove one dollar sign, and then the template provider will remove the second, leaving one left over for the shell to interpret in the final template.

Alternatively, you can avoid this extra level of escaping by placing the template in a separate file and loading it with the `file` function, which then causes terraform to treat the template as a literal string and pass it directly to the provider:

```hcl
data "template_file" "shell_script" {
  template = "${file("${path.module}/script.sh.tmpl")}"
}

```

In this particular example it looks like you're not actually using the `vars` attribute on the `template_file` data source. If your goal is to just include this string verbatim somewhere else, you can cut out this middleman altogether and just use the `file` function directly in whatever resource attribute should have this script.

I'm going to close the new issue that the migration bot created, but if you think the above does not explain what you're seeing please let me know in the _other_ issue and I'll reopen it.

Thanks for opening this, and sorry for this confusing multi-layer interpolation business!

**Comment by fstuck37** [comment]
Hi Martin,
Thank you again for the swift comments and detailed update on this issue.

I did find that four dollar signs were required not the recommended three.

Based on your analysis what I would guess is that the first pass replaces 4 ($$$$) with 2 ($$) and the second pass replaced the 2 ($$) with 1 ($).

Since this works as expected it does resolve my issue.

Here is a simple example I put together to show the output:

data "template_file" "shell_script" {
  template = <<-EOF
#!/bin/bash -x

declare -a arr=('app1.domain.com:internal-app1-internal-2073728995.us-east-1.elb.amazonaws.com' 'app2.domain.com:internal-confluence-internal-649008587.us-east-1.elb.amazonaws.com' 'app3.domain.com:internal-stash-internal-73755237.us-east-1.elb.amazonaws.com');
COUNTER=1;
for i in "$$$${arr[@]}"
do
   var1=$$$${i%:*};
   var2=$$$${i#*:};
   echo "$$$${var1}";
   echo "$$$${var2}";
done;
  EOF
}

output "rendered" {
  value = "${data.template_file.shell_script.rendered}"
}

Thanks for all the help,
Fred
