### ISSUE TITLE
Remote state is not a drop in replacement for -state=statefile.tfstate

### ISSUE THREAD

**Issue by ayashjorden** [hashicorp/terraform#15332]
Hi all,

### Terraform Version
Terraform v0.9.7

### Expected Behavior - _what I thought is should do, not the product design expected one_
Remote state should be a replacement for `-state=state_file.tfstate` CLI switch.
This should allow simultaneous TF runs to interact with the same `State`.
Meaning, that TF should read, sync/lock and write the State against the backend.
### Actual Behavior
Remote state, as specified in https://github.com/hashicorp/terraform/issues/11682#issuecomment-277400299 , is a read-only data source for common infrastructure configuration.

### References
Clarification provided in https://github.com/hashicorp/terraform/issues/11682#issuecomment-277400299
[Remote state](https://www.terraform.io/docs/state/remote.html) page should emphasize the `read-only`-ness nature of it. the fact that remote state is *not* a replacement for State files.

Thank you,
Jorden

**Comment by apparentlymart** [comment]
Hi @ayashjorden!

First, I should clarify that when I wrote the comment you linked to here I was an open source contributor to Terraform, but in the mean time I've become a Hashicorp employee and now work on Terraform full time.

So with that said, since I wrote that I've become more familiar with how backends behave in 0.9. I think the root issue here is that we have not done a good job distinguishing two different concepts:

* _Remote state backends_, which allow Terraform to persist the state for the _current_ configuration to a remote, shared location, instead of the `terraform.tfstate` file.
* The `terraform_remote_state` _data source_, which provides read-only access to the state from a _different_ Terraform configuration.

By default, in the absense of any special configuration, Terraform uses the "local" backend, which stores all state on the local disk. To have Terraform store state somewhere other than local disk, it's necessary to configure a backend that supports [remote state](https://www.terraform.io/docs/state/remote.html). For example, a common choice for AWS users is [the `s3` backend](https://www.terraform.io/docs/backends/types/s3.html), which stores the state itself in Amazon S3 and optionally uses DynamoDB for locking to prevent concurrent runs.
 
To use this, a configuration like the following is added to one of your configuration files (`.tf` files):

```hcl
terraform {
  backend "s3" {
    bucket = "mybucket"
    key    = "path/to/my/key"
    region = "us-east-1"
  }
}
```

After adding this, you can [run `terraform init` to activate the new backend](https://www.terraform.io/docs/backends/init.html). If there is existing local state, Terraform will offer to migrate it to the new location. After this, any future Terraform operations will automatically write the resulting state to S3, or indeed whichever other backend you choose.

This is a separate idea from `data "terraform_remote_state" "..."`. Using this _data source_ is an advanced technique used to create dependencies between separate Terraform configurations in a larger deployment. This is the recommended strategy when managing _large_ infrastructures, so that changes can easily be made to smaller portions of the system in isolation, while still sharing certain data from one configuration to the next. It's recommended to get familiar with using Terraform with a single configuration and remote state first, and only once comfortable with the general workflow to look into split-configuration architectures using the data source.

**Comment by ayashjorden** [comment]
Thank you @apparentlymart for the detailed explanation :thumbsup:

My collegue explained me just that ( different TZs :) took a day to catch up )

If you can add the above info to the `remote` and `remote_state` sections of the State documentation page that will probably help others as well.

Best,
Yarden
