### ISSUE TITLE
Specific variable value blank when passed to aws_ami data source

### ISSUE THREAD

**Issue by evanstachowiak** [hashicorp/terraform#15348]
### Terraform Version
Terraform v0.9.8

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "us-east-1"
}

terraform {
  required_version = "~> 0.9"
}

data "aws_ami" "image_ami" {
  most_recent = "true"
  owners = ["self"]

  filter {
    name = "tag:vcs_revision"
    values = ["${var.vcs_revision}"]
  }
}

variable "vcs_revision" {}
```

### Debug Output
```
2017/06/20 15:46:44 [DEBUG] plugin: terraform: aws-provider (internal) 2017/06/20 15:46:44 [DEBUG] [aws-sdk-go] DEBUG: Request ec2/DescribeImages Details:
2017/06/20 15:46:44 [DEBUG] plugin: terraform: ---[ REQUEST POST-SIGN ]-----------------------------
2017/06/20 15:46:44 [DEBUG] plugin: terraform: POST / HTTP/1.1
2017/06/20 15:46:44 [DEBUG] plugin: terraform: Host: ec2.us-east-1.amazonaws.com
2017/06/20 15:46:44 [DEBUG] plugin: terraform: User-Agent: aws-sdk-go/1.8.34 (go1.8.3; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.9.8
2017/06/20 15:46:44 [DEBUG] plugin: terraform: Content-Length: 128
2017/06/20 15:46:44 [DEBUG] plugin: terraform: Authorization: AWS4-HMAC-SHA256 Credential=credential, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=signature
2017/06/20 15:46:44 [DEBUG] plugin: terraform: Content-Type: application/x-www-form-urlencoded; charset=utf-8
2017/06/20 15:46:44 [DEBUG] plugin: terraform: X-Amz-Date: 20170620T194644Z
2017/06/20 15:46:44 [DEBUG] plugin: terraform: X-Amz-Security-Token: token
2017/06/20 15:46:44 [DEBUG] plugin: terraform: Accept-Encoding: gzip
2017/06/20 15:46:44 [DEBUG] plugin: terraform:
2017/06/20 15:46:44 [DEBUG] plugin: terraform: Action=DescribeImages&Filter.1.Name=tag%3Avcs_revision&Filter.1.Value.1=&Owner.1=self&Version=2016-11-15
2017/06/20 15:46:44 [DEBUG] plugin: terraform: -----------------------------------------------------
```

Please let me know if you want the complete output, I can provide a secret gist link.

### Expected Behavior
The DescribeImages request should have included the sha `38768ec` in its request. For some reason this seems to be some sort of 'magic string'. Other string values will be added to the request normally.

### Actual Behavior
What actually happened?
The vcs_revision variable was not interpolated into the ami request.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -var vcs_revision=38768ec`

**Comment by apparentlymart** [comment]
Hi @evanstachowiak! Sorry this isn't working as expected.

If I'm reading your log correctly, it looks like it's sending the value as `%7D`, which is the closing brace (`}`) character. In your config for this tag you _do_ have an extra brace there:

```hcl
values = ["${var.vcs_revision}}"]
```

That explains where the brace is coming from, but not why the variable was not interpolated. If you remove that extra brace, does it then start sending the empty string for this value?

Note that AWS provider development is now happening in [a separate repository](https://github.com/terraform-providers/terraform-provider-aws), so our migration bot will eventually close this issue and create a new copy over there. If you'd like to, you can close this issue yourself and open a new one with details about the result of moving that brace, in which case the new issue will be owned by you (not the migration bot) and is more likely to be seen by the primary maintainers of the AWS provider. No worries if not... the bot will take care of it before too long, otherwise!

**Comment by evanstachowiak** [comment]
@apparentlymart thanks for the quick response! I am indeed still experiencing the issue without the brace, I have updated the description accordingly. I also created a new ticket here:
https://github.com/terraform-providers/terraform-provider-aws/issues/930
