### ISSUE TITLE
"external" provider returns an invalid json

### ISSUE THREAD

**Issue by rzubin** [hashicorp/terraform#15346]
### Terraform Version
Terraform v0.9.8

### Terraform Configuration Files
```hcl
data "external" "get_ip" {
  program = ["python", "get_ip_from_ipam.py"]
  query = {
    network = "10.190.170.0"
  }
}
```

### Debug Output
```data.external.get_ip: Refreshing state...
  Error refreshing state: 1 error(s) occurred:
  data.external.get_ip: 1 error(s) occurred:
  data.external.get_ip: data.external.get_ip: command "python" produced invalid JSON: invalid 
  character 'S' looking for beginning of value
```

### Expected Behavior
    ipv4_address = "${data.external.get_ip.result["ip"]}" 
ipv4_address should have been set to 10.190.170.37

### Actual Behavior
Here is what the returned json looks like 
`"{'ip': '10.190.170.37', 'network': '10.190.170.0'}"`

**Comment by apparentlymart** [comment]
Hi @rzubin! Sorry this didn't work out.

I'm not sure where this "character 'S'" is coming from, but the JSON you specified is using single quotes `'`, while JSON requires double quotes `"`.

The format of your program's output should therefore be:

```json
{"ip": "10.190.170.37", "network": "10.190.170.0"}
```

If possible I'd recommend using [the `json` module](https://docs.python.org/2/library/json.html) to produce valid JSON from a Python `dict`, thus avoiding the need to deal with the serialization details manually.

**Comment by rzubin** [comment]
Hey @apparentlymart.

Thank you for your quick responce

I converted it to a json format. Verified that the json is valid and passed it to stdout and still got the invalid character error

```result= json.load(sys.stdin)
result = get_free_ip_address(result['network'], result['host_fqn'])
result = json.dumps(result)
demjson.decode(result)
json.dump(result, sys.stdout)
```

I even tried this
```
json.dump({
    "ip": result["ip"],
}, sys.stdout)
```
same error

**Comment by apparentlymart** [comment]
@rzh It looks like you are double-encoding the JSON: the line `json.dumps(result)` returns a string resulting from JSON encoding the `result` value, and then the line `json.dump(result, sys.stdout)` JSON encodes _that string_ before printing it.

I'm not sure what `demjson` is here, but here is a way to write this where it only gets encoded once:

```python
result = get_free_ip_address(result['network'], result['host_fqn'])
json.dump(result, sys.stdout)
```

However, you said that you tried the simpler version where this wouldn't be an issue and still got the same error. This leads me to suspect that there is some other output from your program that is being printed before the JSON object. I'd suggest running your program directly from the command line, outside of Terraform, and verifying that it produces _only_ the JSON object, and does not produce any other debug/log output.

**Comment by rzubin** [comment]
Hey @apparentlymart 

I did try that. 

```
sys.stdout = open('log.txt', 'w')
input = {
    "network": "10.190.170.0",
    "host_fqdn": "abc.com"
}
result = get_free_ip_address(input['network'], input['host_fqdn'])
print(result)
json.dump(result, sys.stdout)
sys.stdout.close()
```
Below is the log.txt file that shows the sys.stdout

```
{u'ip': u'10.190.170.37'}
{"ip": "10.190.170.37"}
```

**Comment by apparentlymart** [comment]
You will need to remove the line `print(result)` in order for the result to be valid JSON. Your output currently includes both the JSON object _and_ a Python-flavored string serialization of the object.

**Comment by rzubin** [comment]
@apparentlymart I don't really have that in the actual code. I just wanted to show you what get_free_ip_address returns. When I tested it with terraform plan I removed the print statement and removed redirecting sys.stdout to the log.txt file

**Comment by apparentlymart** [comment]
Unfortunately at this point I don't know what else to suggest. The error message you received suggests that the literal letter `S` appears at the start of your program's output; none of the code examples or output examples you've shown include that, which suggests that the program is behaving differently when launched from Terraform.

The usual cause of unexpected alphabetic characters is that the script is producing some sort of error message. Of course, with only the first letter of the message it's hard to guess what it might be.

My only remaining idea is that the external program protocol actually calls for the external program to read all data provided on `stdin`, which your program isn't doing. It seems unlikely to me that this would cause the problem you are seeing, but perhaps it's worth trying this to eliminate it. In python, this would be achieve by adding the following statement to the start of the program:

```python
os.stdin.read()
```

Since you aren't expecting any input parameters, you can discard what is read, but the protocol requires you to still read it.

**Comment by rzubin** [comment]
@apparentlymart I really appreciate the help.  I have tried what you have suggested. But I am using sys instead of os. I don't think that should make a difference right?

This works perfectly fine 
```
result = {
    "ip": "10.190.170.37"
}
json.dump(result, sys.stdout)
```
So its really confusing why when I get the IP from a get_free_ip_address (even converted it to a string) I get that invalid character

**Comment by apparentlymart** [comment]
Hi @rzubin,

Sorry for the mistake... I'm a bit rusty on Python since I've not written it in a while. `sys.stdin` was indeed what I meant.

If you have this working with your simpler script then this suggests that _something_ in your more complex script is producing extraneous output. I expect that there's something special about the `get_free_ip_address` function that is causing problems when invoked from Terraform, but unfortunately that's outside of Terraform's scope so I don't think I can be of any more help here. I would suggest reviewing the implementation of `get_free_ip_address` to see if anything about it would behave differently when run from Terraform (different environment variables available, or different working directory, etc) and whether any path in that function would print output to stdout.

It seems like this isn't actually a bug in Terraform, so I'm going to close this. You may wish to take your question to one of the forums listed on [the community page](https://www.terraform.io/community.html) to see if anyone in the community has some insight to offer.

Sorry we weren't able to get to the bottom of this!

**Comment by rzubin** [comment]
Hey @apparentlymart,

I was able to resolve this issue. The `get_free_ip_address` had a `print` statement  which was logged to stdout. I removed the print statement and it worked fine. Thank you once again for your time!
