### ISSUE TITLE
Consul backend security options

### ISSUE THREAD

**Issue by loicalbertin** [hashicorp/terraform#15354]
Hi,

The Consul backend configuration has a relatively limited number of options compared to the Consul provider. Especially, it doesn't have options to specify a ca_file to verify the remote agent's certificate (workaround provided in GH-3203) and cert & key file options to interact with a Consul instance configured with the `verify_incoming` enabled.

I think it would be great to have this in the backend configuration, what do you think?

### Terraform Version
v0.8.9

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-3203

**Comment by loicalbertin** [comment]
Hi @apparentlymart if you agree that adding such options could be useful I'm interested in contributing this feature.

**Comment by apparentlymart** [comment]
Hi @loicalbertin!

Supporting the same options on the backend seems sensible to me, and if you're willing to implement it then that's great! I suggest following the option names and any associated environment variables they use as closely as possible so that there's consistency between both sets of settings.

**Comment by apparentlymart** [comment]
#15405 was merged. Thanks, @loicalbertin!
