### ISSUE TITLE
Stop colouring a destruction of a resource in green

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#15350]
terraform 0.8.7

An idea, not a bug per se, but still...:

terraform handily outputs the removal of a resource in red, the change of a resource in yellow, and the creation of a resource in green. 

However where the change consists of a re-creation of a resource (destroy then create), it uses green. As this is actually a destructive action, it should either be in red, or something like purple. 

Its too easy to assume that a terraform plan isnt being destructive because its all green, when in fact its blown away half your infrastructure and data you can never get back.

**Comment by apparentlymart** [comment]
Hi @gtmtech!

Agreed that this is weird and confusing... there isn't a great reason for it to be _green_ anyway; if anything, I'd expect it to be yellow since it's trying to present as a funny sort of update.

But agreed that we should make this more obvious. I don't know about making the whole header red, since that would give the impression that there would be no resource at all afterwards, but I'm wondering if we can find a unique presentation that creates the right connotation without overloading an existing convention.

Initial idea:

* Change the `-/+` "icon" so that the minus is shown in red and the plus is shown in green.
* Show the header text that indicates the resource address in yellow, but include some additional red text after it on the same line saying `(requires new resource)`

Maybe in practice that'd be some multi-color overload, but we can give it a try and see how it looks.
