### ISSUE TITLE
jsonencoding with list not working?

### ISSUE THREAD

**Issue by gnowxilef** [hashicorp/terraform#15378]
### Terraform Version
Terraform v0.9.8

### Terraform Configuration Files
iam.tf
```hcl
// Firehose S3 Role
resource "aws_iam_role" "kinesis_firehose" {
  name        = "${var.firehose_stream_name}_firehose_role"
  description = "iam role for ${var.firehose_stream_name}"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "firehose.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "23729874",
      "Effect": "Allow",
      "Principal": {
        "AWS": "${jsonencode(var.cross_account_storm_arn)}"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}
```

module.tf
```hcl
module "swift"
..snip..
  cross_account_storm_arn = [ "arn:aws:iam::777509510706:role/Storm-TC1", "arn:aws:iam::777509510706:role/Storm-TC2", "arn:aws:iam::777509510706:role/Storm-ON1" ]
..snip..
}
```

### Debug Output
https://gist.github.com/gnowxilef/1bf725695aed16787445f2fd858ab3ff

### Expected Behavior
list should have been rendered into iam policy

### Actual Behavior
an error occurs:
```
1 error(s) occurred:

* module.swift.aws_iam_role.kinesis_firehose: "assume_role_policy" contains an invalid JSON: invalid character 'a' after object key:value pair
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
none

### References

**Comment by apparentlymart** [comment]
Hi @gnowxilef,

I think the problem here is that in your `assume_role_policy` expression you are inserting the result of the JSON encoding between quote marks, thus causing the result to be "double-quoted":

```
"AWS": "["arn:aws:iam::777509510706:role/Storm-TC1", "arn:aws:iam::777509510706:role/Storm-TC2", "arn:aws:iam::777509510706:role/Storm-ON1"]"
```

As you can see, this would cause the JSON parser to see the string as just `"["` followed by a naked `a` from `arn:`, which is consistent with the error message.

Removing these extra quote marks from outside the expression should fix this, I suspect.

**Comment by gnowxilef** [comment]
ah, much better, thanks.

i was not aware that you did not need quotes for a variable inside the heredoc.
