### ISSUE TITLE
depends_on resource that doesnt change forces new resource

### ISSUE THREAD

**Issue by aep** [hashicorp/terraform#15392]
### Terraform Version
Terraform v0.9.8

### Terraform Configuration Files
```hcl
data "template_cloudinit_config" "foo" {
    depends_on = ["data.external.bar"]
    // not necessary to actually use data.external in interpolation. makes no difference
}

```

### Debug Output
```
-/+ aws_instance.bla
    user_data:  "some hash" => "different hash" (forces new resource)

<= data.template_cloudinit_config.foo
      rendered:            "<computed>"
```

### Expected Behavior
data.external.bar didn't change, so neither should the hash of data.template_cloudinit_config.foo

### Actual Behavior
hash changed despite identical rendered content.
oddly enough, it also causes everything else using data.external.bar to be invalidated. simply removing the depends_on made all my (forces new resource) problems go away.

**Comment by apparentlymart** [comment]
Hi @aep! Sorry for this strange behavior.

The issue here is that `depends_on` behaves in a specific way for data sources: it forces them to _always_ be processed at apply time, rather than at plan time. Terraform is being a little _too_ conservative in this case, since you're actually depending on another data source, but that's a limitation of the current implementation.

In general we do not recommend using `depends_on` in a `data` block except in exceptional circumstances. It's always better to just interpolate a value from the resource or data source you wish to depend on, which creates an implicit dependency and -- most importantly -- allows Terraform to understand specifically which attribute you intend to use, which then allows it to see that this attribute is already known and not defer the read until apply time.

The other oddity here is that the `user_data` attribute has a special behavior where it shows a hash of the content, which obscures the fact that the "different hash" in your case here is actually a hash of the empty value that represents `<computed>`. Really, Terraform is trying (and failing) to tell you this:

```
-/+ aws_instance.bla
    user_data:  "some hash" => "<computed>" (forces new resource)
```

This behavior of showing the hash rather than the computed placeholder is a known issue, and is indeed rather unfortunate as it obscures what's going on here.

**Comment by aep** [comment]
@apparentlymart that's a pretty good explanation. Would it be possible shirt term to change the output to exactly what you said? That would make it much easier to understand what's going on.

**Comment by apparentlymart** [comment]
Unfortunately the reasons for it rendering this way are rather arcane and it's not a quick fix. It _is_ something we intend to fix, since you certainly aren't the first person to be misled by it, but it will unfortunately need to wait for some other deeper work on how plans are internally represented before we can properly propagate this information up to the UI.

**Comment by LTMenezes** [comment]
> The issue here is that depends_on behaves in a specific way for data sources: it forces them to always be processed at apply time, rather than at plan time. Terraform is being a little too conservative in this case, since you're actually depending on another data source, but that's a limitation of the current implementation.

@apparentlymart That's a good explanation. I have searched but I haven't found this in any of the documentation regarding "depends_on", do you think we could improve the documentation to inform this behavior?
