### ISSUE TITLE
adding provider for Rage4 DNS

### ISSUE THREAD

**Issue by anuaimi** [hashicorp/terraform#15394]
Hi there. I've created a terraform provider for Rag4 DNS. Rage4 is a high quality provider in that they do geo balancing and allow weighted distribution for IPs.

I'd like to share it with the larger community.  What is the process for getting the provider added to Terraform (on github.com/terraform-providers)?  

Here is my provider
https://github.com/anuaimi/terraform-rage4

thanks

**Comment by apparentlymart** [comment]
Hi @anuaimi! Thanks for sharing this.

First of all, I just want to clarify that we do not expect _all_ providers to be hosted in the `terraform-providers` organization; that's a container for the ones that Hashicorp is currently building and distributing, but third-party providers hosted in outside repositories are still welcome and encouraged. The user-experience for installing these will improve in future versions.

With that said, we have a few criteria for the ones distributed from the official repository:

* Must have at least one active maintainer to review any issues and PRs that might come in, and just generally be a point of contact for any announcements or discussion related to the providers in general. The definition of "active" is of course a subjective one, and will vary depending on the popularity, complexity, and issue volume of the provider. This criterion is intended to help ensure that the provider doesn't become "stale" as the underlying APIs evolve.
* Must have acceptance tests that can be used to automatically verify the correct operation of the provider, and a way for Hashicorp to run those tests in automation. This usually means having a test account with the provider that is used only for automatic runs of the tests. This criterion helps ensure that new releases do not contain significant regressions.
* Must have a repository structured in a manner similar to the other providers in `terraform-providers`, follow Go and Terraform idiom, use `go fmt`, etc. This criterion is primarily so that it can work well with the release automation used to deploy the providers to the repository, which expects a certain repository structure, but also makes it easier in the cases where changes need to be made across several providers at once since certain details can be automated.

Historically we've adopted some providers that didn't meet these criterion, which are "grandfathered in" but are suffering from some maintenance challenges as a result, so moving forward we're trying to be more deliberate in ensuring that new providers can be supported in a sustainable way. Alongside this, as mentioned above we're going to be taking steps in forthcoming versions to make it easier for users to use providers that _aren't_ built and distributed by Hashicorp.

With all of that said, I hope this helps give some context about what we'd be looking for to include this provider in the official repository. We'll be working to specify better these items soon as we get into this new rhythm of maintaining providers in separate repositories, so I apologize that some of these items are currently rather vague and subjective. In the mean time, I'm happy to answer any further questions you might have here.

Thanks again for writing this, and for your interest in incorporating it into the `terraform-providers` organization!

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, please feel free to reply to this issue and we'll reopen it. Thanks!
