### ISSUE TITLE
File provisioner doesn't display full reply from server

### ISSUE THREAD

**Issue by blckct** [hashicorp/terraform#15400]
### Terraform Version
Terraform v0.9.8

### Expected Behavior
Reply from ssh server should be displayed fully

### Actual Behavior

The output seems to be missing the first letter

* aws_instance.staging1: 1 error(s) occurred:
* Upload failed: lease login as the user "ubuntu" rather than the user "root".

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.Don't configure ssh user
2. Use file provisioner
3. terraform apply

**Comment by tyrostone** [comment]
+1

**Comment by poveyd** [comment]
+1

**Comment by blckct** [comment]
```
2018-08-03T15:33:33.996+0200 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/08/03 15:33:33 [DEBUG] Beginning file upload...
2018/08/03 15:33:34 [ERROR] root: eval: *terraform.EvalApplyProvisioners, err: Upload failed: lease login as the user "ubuntu" rather than the user "root".
2018/08/03 15:33:34 [ERROR] root: eval: *terraform.EvalSequence, err: Upload failed: lease login as the user "ubuntu" rather than the user "root".
```

It seems to be caused by the code copy/pasted from Packer and been mentioned there previously.

It's probably not worth fixing unless in a case like hashicorp/packer#4237

**Comment by vadimslu** [comment]
Not using packer in my setup but still getting this error while trying to run provisioner

2018-10-16T09:34:27.284-0400 [DEBUG] plugin.terraform: file-provisioner (internal) 2018/10/16 09:34:27 [DEBUG] Beginning file upload...
2018/10/16 09:34:27 [ERROR] root: eval: *terraform.EvalApplyProvisioners, err: Upload failed: lease login as the user "ubuntu" rather than the user "root".
2018/10/16 09:34:27 [ERROR] root: eval: *terraform.EvalSequence, err: Upload failed: lease login as the user "ubuntu" rather than the user "root".
2018/10/16 09:34:27 [TRACE] [walkApply] Exiting eval tree: aws_instance.deploy_server

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
