### ISSUE TITLE
intersection interpolation function

### ISSUE THREAD

**Issue by tomdavidson** [hashicorp/terraform#15410]
# proposed intersection interpolation function

We have `join` (aka union) and I think it would be great to implement intersection of lists as well.  If I had intersection I could:

```hcl
value = "${intersection(
    var.regions,  
    split(".", aws_elastic_beanstalk_environment.default.cname)
  )}"
```

instead of (which does not verify the string is found in the approved var.regions but is allread messy and assumes the location with 'length()-3'):

```hcl
value = "${element(
      split(".", aws_elastic_beanstalk_environment.default.cname), 
      length(split(".", aws_elastic_beanstalk_environment.default.cname))-3
    )}"
```

**Comment by apparentlymart** [comment]
In #20014 we've added some new functions for working with values of type set, implementing set-theory-style operations including a set intersection, [`setintersection`](https://github.com/hashicorp/terraform/blob/ae0be75ae09efb191ecd22f27389b16521c771fb/website/docs/configuration/functions/setintersection.html.md).

Because Terraform will automatically convert lists to sets when calling these functions, `setintersection` can also be used with lists, with the caveat that the result will itself be a set and thus will not preserve the ordering of any of the given lists.

A function [`setunion`](https://github.com/hashicorp/terraform/blob/ae0be75ae09efb191ecd22f27389b16521c771fb/website/docs/configuration/functions/setunion.html.md) is also included. It is true that this is functionally equivalent to using `join` and then converting to a set -- duplicate elements will be removed and the ordering lost in that conversion -- but having set-specific operations makes the intent clearer and thus, we hope, improves readability.

This new approach is possible for Terraform v0.12 because the whole language has sets as a first-class type, whereas before that concept only existed within providers themselves. By making sets first-class we were able to address many of the limitations of working with them in expressions, including deriving other values from them elsewhere in a configuration.

These features are already in the master branch ready to be included in the forthcoming v0.12.0 release, so I'm going to close this out now.
