### ISSUE TITLE
Plan ignores the -state flag

### ISSUE THREAD

**Issue by JDiPierro** [hashicorp/terraform#15418]
### Terraform Version
```
$ terraform -v
Terraform v0.9.9
```

### Terraform Configuration Files

Should be irrelevant

### Debug Output

https://gist.github.com/JDiPierro/387882b4b34636c57efc1b9b26745ba4

### Expected Behavior

Terraform should perform a plan using the state file passed to the -state flag

### Actual Behavior

Terraform is unable to find the state file

### Steps to Reproduce
Have the following directory structure:
```
.
└── terraform
    └── test
        ├── README.md
        ├── main.tf
        ├── terraform.tfstate
        └── terraform.tfstate.backup
```
Attempt to run a plan from the top-level directory pointing to the terraform.tfstate file:
`terraform plan -state=terraform/test/terraform.tfstate`

**Comment by jbardin** [comment]
Hi @JDiPierro,
The output from terraform here shows `No configuration files found`. Your config is in the directory `./terraform/test`, which terraform would need in order to execute the plan. 

You should always run terraform from within the directory where you ran `terraform init`. If you are always executing terraform from that top level directory, you will need to pass the config directory as the final argument just like if for `terraform apply`.
