### ISSUE TITLE
Problems with sets/hashes, and we need an easier way to create nested objects

### ISSUE THREAD

**Issue by StephenWeatherford** [hashicorp/terraform#15420]
From my work on azurerm so far, one issue keeps coming up...  sets and hashes and lack of nested object support.  Here's my best attempt at summarizing the related issues according to my current understanding, not sure how to simplify this any more.

1) When should sets be used?

The documentation for schema.Set says "Set defines a function to determine the unique ID of an item so that a proper set can be built."  This to me implies that the hash function schema.Set is supposed to generate identify uniquely identify the object in the context of the resource being modeled.  But that's not true (see #10520).  It's instead expected to be a hash of *all* the properties in the object, or you'll get bugs.  So once you change any property, no matter how minor, the set "identity" is lost (#10520).  So I'm not really sure why sets exist as opposed to simply an ordered list.

See also https://github.com/hashicorp/terraform/pull/2336 and https://groups.google.com/forum/#!topic/terraform-tool/tsnWzWfkzaQ and https://github.com/hashicorp/terraform/pull/14261.

2) We need better guidance for set usage (the comments for schema.Set are wrong or misleading)

According to #10520, "it's actually no longer suggested to use an explicit Set function since there's a default implementation that 'does the right thing' of hashing the entire nested data structure".  My reading of this is that you should *not* set an explicit schema.Set function at all for new code, but the comments for schema.Set do not say this.  Also, @whiskeyjay tried implementing a new resource this way but ran into troubles with import (don't know the full details).

3) The current behavior of sets causes lots of problems:

a) A change in any property in the set acts as if the entire set has changed (and if any of the properties in the set are ForceNew=true, then the entire resource gets re-created)
b) If any of the properties of the set has ForceNew=true, then the entire resource will be recreated any time *any* of the properties in the set changes (even if not marked ForceNew)
c) The diff shown to the user by this is way more complex than it needs to be and is actively confusing (see #5179, #15180)
d) If someone adds a new property to a set and forget to modify the schema.Set function for it, terraform will not notice any changes to that property.  This caused lots of bugs in the azurerm provider.  And you can't fix these bugs without changing the hash value (needing a state migration? I'm a little unclear on that currently).

4) Sets are overused/misused because of the lack of support for nested objects

For instance, I've been adding VM encryption to the azurerm_virtual_machine resource.  The natural structure if following the example of the REST API leads to a resource looking like this:

```hcl
  resource "azurerm_virtual_machine" "test" {
      ....
      storage_os_disk {
          encryption_settings {
              enabled = true
              disk_encryption_key {
                  secret_url = "https:..."
                  source_vault_id = "/subscriptions/..."
              }
              key_encryption_key {
                  key_url = "https:..."
                  source_vault_id = "/subscriptions/..."
              }
          }
      }
  }
```

There's some question as to whether this should be flattened, but the pattern and guidance I was given was to leave it nested like this for consistency (https://github.com/hashicorp/terraform/pull/14261).  However, the only way to currently do this is to use a list or set with maxelems = 1.

Using a set leads to all the aforementioned issues with sets, even though these are simple objects having nothing to do with sets.  (Using a list IMHO makes more sense - is there a reason that shouldn't be the standard practice?) 

Either way, it seems like if we had a simple way of nesting objects then we wouldn't need to use sets so much and drag in their complications.

So as far as specific asks go:
1) Can we get better guidance around using sets?
2) Can we get some of the issues fixed or the design reconsidered? (given other comments I've seen, I'm assuming that won't happen any time soon)
3) Can we get support for nested objects so we don't have to overuse sets?
4) In the meantime, is there a better way to deal with nested objects in schemas?  Lists instead of sets?

thx,
Stephen

**Comment by apparentlymart** [comment]
Hi @StephenWeatherford!

These are all good questions. I don't have good answers for all of them right now, but I do have _some_ things I can say:

* For a nested object, the current best practice (which we can try to document better) is to use a list with `MaxItems: 1`, as you suggested. The distinction between sets and lists (ordered vs. not) doesn't matter when there can only be zero or one items, and so the list semantics work out simpler and are a better fit.
* We suggest to not set an explicit hashing function in new code, as you saw. There _are_ some issues when sets are nested inside sets, due to the cascading hash updates that causes, but a custom hash function only addresses that if it erroneously excludes the nested set from consideration, which causes other bugs as you have seen.
* The reason that sets and lists exist as independent ideas is to deal with the fact that some APIs themselves have set-like constructs that don't match our expectations for lists.

My general advice at this point would be: default to lists unless the underlying API does not behave like a list. Our expectations for a list are that either the underlying API preserves the given order and guarantees to return objects in the same order, or that the nested object has some locally-unique attribute that we can sort by to _recover_ a consistent order where one doesn't exist.

I'll leave this issue here as a documentation issue to record the fact that we've got some outdated and incomplete docs in this area. In the mean time, I hope the above clarifications are useful.

**Comment by apparentlymart** [comment]
Oh, I forgot to mention: the ability to create a nested object _without_ the list indirection is on our radar, and we can hopefully solve it as part of some more general work coming in future to how typed values are represented internally in Terraform. Currently things are rather complex due to some legacy behavior dating back to when Terraform only dealt with simple string values. We're planning to improve things in this area, which would then indirectly make it simpler to add support for single nested objects.

There isn't a single issue for this because it's a broad area that's not yet defined enough to break down into concrete work. We'll make some issues/PRs for it when we get further down this path.

**Comment by StephenWeatherford** [comment]
That does help, thanks.  Improving the documentation would definitely be good, too, especially around schema.Set recommendations and list vs set recommendations.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. There have been many, many updates to the SDK since it was opened, and it now has it's own repository: https://github.com/hashicorp/terraform-plugin-sdk

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
