### ISSUE TITLE
Duplicate variables in tfvars should warn or error

### ISSUE THREAD

**Issue by lopopolo** [hashicorp/terraform#15455]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```console
$ terraform -v
Terraform v0.9.10

```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform should error when there are duplicate variable definitions in a *.tfvars file like it does for duplicate variable definitions in *.tf files.

### Actual Behavior
No error, no warning. The last definition wins.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by apparentlymart** [comment]
Hi @lopopolo! Sorry for the long silence here.

I've verified that as of Terraform v0.12.0-alpha1 -- a prerelease version of the forthcoming v0.12.0 major release -- Terraform will now produce an error if the same variable is assigned a value multiple times in _the same_ `tfvars` file.

It is intentional that assignments in _separate_ files (or separate assignments directly from the command line using `-var=`) have a "last assignment wins" rule, since that allows the user to "layer" variable values, such as by having a file with values that are used in most cases and then another separate file that selectively overrides it e.g. for special deployment environments.

We have also updated the documentation for setting variables in an attempt to be clearer about the override behavior and the value precedence when using overrides. This is not visible on the website yet since it is still showing the v0.11.10 documentation, but the changes will be published in conjunction with the v0.12.0 final release.

Since the duplicate-checking behavior is now present on `master` and will be included in the final release, I'm going to close this out. Thanks for reporting this, and sorry again for the delay in getting back to you about it.
