### ISSUE TITLE
Reconfigure flag in terraform init

### ISSUE THREAD

**Issue by s-maj** [hashicorp/terraform#15463]
Hi,

When I am using S3 backend, what exactly terraform init -reconfigure is doing? Will it discard local state an pull version from the bucket (act as an opposite of force-copy) or it's doing something else?

**Comment by jbardin** [comment]
Hi @s-maj,

The `-reconfigure` flag is there to allow one to modify the backend configuration during init, without loading the previous backend config or state for comparison. It's specifically meant to avoid migrating the state, while still saving the backend config from the config files. 

For example, if you needed to change the `dyanamodb_table` value in the backend config because the table was no longer accessible, you could use the `-reconfigure` flag to change the saved config value without terraform attempting to check the remote state, which would fail.

This of course allows you to bypass the state migration and point the backend to an entirely new state file without confirmation, which may be desired, but use the usual caution and take backups as needed.

**Comment by s-maj** [comment]
Cool, thanks @jbardin for clarification.

**Comment by b-dean** [comment]
might be useful to have this in [the docs for `terraform init`](https://www.terraform.io/docs/commands/init.html). I know it's in `terraform init -help`

**Comment by jbardin** [comment]
Hi @b-dean,

The `-reconfigure` flag is mentioned under [Backend Initialization](https://www.terraform.io/docs/commands/init.html#backend-initialization). That page however could probably use some reformatting to make all the options more discoverable.

Thanks!
