### ISSUE TITLE
Feature Request: aws_vpn_connection BGP ASN Attribute

### ISSUE THREAD

**Issue by vcaixeta** [hashicorp/terraform#15489]
Hi guys,
Under aws_vpn_connection it would be great if we could have the an attribute 'aws_bgp_asn', so we can fetch the bgp asn that aws selected, they use a few different ones when setting up new VPNs. I can see that its included in the attribute customer_gateway_configuration, that is a XML file with the full vpn config, but I just can't find a way to parse and get only their ASN. 

This would help a lot setting up VPNs using BGP from different providers (e.g: google gcp) towards aws, in fact that's exactly what I am doing and the only step still manual is the aws bgp asn number, everything else I can get from terraform attributes quite easily :)

Eg: On gcp side would be great to be able to add the peer_as from an aws_resource attribute instead of manual when deploying an aws+gcp vpn with bgp:

resource "google_compute_router_peer" "gcp-peer-router-1" {
  name                      = "tf-gcp-router-1"
  router                    = "${google_compute_router.gcp-router.name}"
  peer_ip_address           = "${aws_vpn_connection.tunnel_1.tunnel1_vgw_inside_address}"
  peer_asn                  = 9059  **<<<<--- This guy**
  advertised_route_priority = 100
  interface                 = "interface-1"
}

Terraform Version: 0.9.11
Thank you very much!

Regards,
Vinicius Caixeta

**Comment by apparentlymart** [comment]
Hi @vcaixeta,

We discussed this on Gitter IM but I'll close this out here so others can see where we landed:

This feature was introduced in [the 0.1.2 release](https://github.com/terraform-providers/terraform-provider-aws/blob/v0.1.2/CHANGELOG.md) of the now-separated AWS provider, in terraform-providers/terraform-provider-aws#973. Since 0.10 is not final yet, there is no automatic way to get access to that provider version, but those still on 0.9 who need this feature can [manually download that version](https://releases.hashicorp.com/terraform-provider-aws/0.1.2/) and place its binary in the same directory as  `terraform` itself. Due to changes between 0.9 and 0.10, it will be necessary to rename the downloaded file to just `terraform-provider-aws`, removing the version number portion from the filename.

Once 0.10 final is out, this new AWS provider version will be available for automatic installation via `terraform init`.
