### ISSUE TITLE
split behaving unintuitively

### ISSUE THREAD

**Issue by xenoterracide** [hashicorp/terraform#15492]
```
Calebs-MacBook-Pro:terraform calebcushing$ terraform -version
Terraform v0.9.11
```
code
```
output "justjoin" {
  value = "${join( ".", list( "a", "b" ) ) }"
}

output "split" {
  value = "${ length( split( ".", "c.com.") ) }"
}

output "parts" {
  value = "${concat( list( "a", "b" ), split( ".", "c.com.") ) }"
}

output "join" {
  value = "${join( ".", concat( list( "a", "b" ), split( ".", "c.com.") ) )}"
}
```

```
Calebs-MacBook-Pro:terraform calebcushing$ terraform output justjoin
a.b
Calebs-MacBook-Pro:terraform calebcushing$ terraform output split
3
Calebs-MacBook-Pro:terraform calebcushing$ terraform output parts
a,
b,
c,
com,

Calebs-MacBook-Pro:terraform calebcushing$ terraform output join
a.b.c.com.
```

and I think this might be a regression, I had code similar to this working on 0.9.7, can't confirm though. I believe that `split` should only return 2 elements in the second case

for giggles, `chomp` doesn't fix it

```
output "split" {
  value = "${ length( split( ".", chomp("c.com.") ) ) }"
}

output "parts" {
  value = "${concat( list( "a", "b" ), split( ".", chomp("c.com.") ) ) }"
}
```
```
Calebs-MacBook-Pro:terraform calebcushing$ terraform output split
3
Calebs-MacBook-Pro:terraform calebcushing$ terraform output parts
a,
b,
c,
com,
```

**Comment by apparentlymart** [comment]
Hi @xenoterracide,

It's intentional that the period at the end of that string would create an extra split. If you want to eliminate empty elements from the resulting list, the `compact` function can be used to achieve that:

```hcl
output "split" {
  value = "${ length( compact(split( ".", "c.com.")) ) }"
}
```

**Comment by xenoterracide** [comment]
there is nothing after the period, so no element, meaning an element that does not exist should not be created....  I'm confident split doesn't work like that in most other languages, you are creating a character that does not exist

```java
import java.util.*;
import java.util.regex.*;

class Main {
  public static void main(String[] args) {
    String[] array = "c.com.".split(Pattern.quote(".") );
    System.out.println( Arrays.toString( array ) + " " + array.length );
  }
}
```

but whatever... python, and javascript work this way, pretty sure perl results in 2 elements. if this is how you guys want it to work, I think it's overly verbose, and unintuitive.

**Comment by apparentlymart** [comment]
Python and JavaScript behave the same way as Terraform here:

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> "c.com.".split(".")
['c', 'com', '']
```

```
$ node
> 'c.com.'.split('.')
[ 'c', 'com', '' ]
```

Perl does indeed disagree, dropping that trailing empty string. This is a situation where both approaches are valid depending on how the function is defined; what is intuitive will thus depend on what languages you're most experienced with.

In Terraform's definition of `split`, the empty string is considered a valid string, and the result is always a list of n+1 strings where n is the number of separator substrings. I can definitely see that there are use-cases where empty string elements aren't interesting, like this one, but there are other situations where the caller _does_ need these empty strings.

Using the `compact` function with `split` means that both behaviors are possible, whereas if `split` by default dropped empty elements it wouldn't be possible to have a function to recover them. I understand that it makes it more verbose, but it also keeps these two concerns (split on delimiter, and remove empty elements) separated so that they can each be applied when necessary and not applied when unwanted.

I'm sorry Terraform didn't meet your expectations here. It's tough to be intuitive to everyone when everyone is coming from different backgrounds and experiences. We can, at least, attempt to clarify this in the docs since the behavior here is currently unspecified.

**Comment by xenoterracide** [comment]
I'm still looking for someone to give me an example of where the empty string is useful (only one I have heard was someone operating on /etc/password, but /etc/passwd is column oriented, split isn't actually a good way to parse a column oriented thing. like parsing html with regex.
