### ISSUE TITLE
Feature request / RFC: data sources should not error with 404

### ISSUE THREAD

**Issue by veetow** [hashicorp/terraform#15493]
### Terraform Version
v0.9.11

### Expected Behavior
My specific use case is for resources that return a `EntityAlreadyExists` error when attempting to create something that isn't in the state but does actually exist.  I would love to be able to query a resource, and only have Terraform create it if it does not already exist.

### Example: AWS IAM Roles
```hcl
provider "aws" {
  region = "us-east-1"
}

variable "role_name" {
  default = "might_not_exist"
}

data "aws_iam_role" "instance_role" {
  role_name = "${var.role_name}"
}

resource "aws_iam_role" "instance_role" {
  count = "${data.aws_iam_role.instance_role.id == "" ? 1 : 0}"
  name  = "${var.role_name}"

  assume_role_policy = <<EOP
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOP
}
```

### Current Behavior
The above example currently results in the following `NoSuchEntity` error:
```hcl
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_iam_role.instance_role: Refreshing state...
Error refreshing state: 1 error(s) occurred:

* data.aws_iam_role.instance_role: 1 error(s) occurred:

* data.aws_iam_role.instance_role: data.aws_iam_role.instance_role: Error getting roles: NoSuchEntity: Role not found for might_not_exist
        status code: 404, request id: 775082e5-6275-11e7-81c0-4711b98c34e4
```

### Proposed Behavior Change
I believe that (perhaps optionally) handling the `NoSuchEntity` and returning something like an empty string would allow greater flexibility to users.  It would allow writing Terraform code with greater reusability and DRYness.

**Comment by veetow** [comment]
Right now I'm working around this with an external data source using the AWS SDK, but it feels wrong and gross and I feel dirty now.

**Comment by veetow** [comment]
Even this doesn't really work, now that I think about it.

**Comment by teamterraform** [comment]
Hi folks,
Sorry for the long silence on this. Now that terraform 0.12 is released, we are addressing older issues. 

The sort of dynamic decision-making that is being requested here runs counter to Terraform's design goals, since it makes the configuration a description of what might possibly be rather than what is. We are not going to change the behavior of data sources when the response is empty or 404, and will close this issue.

We feel that there are better patterns to follow when managing the differences between environments: composing different modules in different ways, rather than trying to use the same modules in all environments but make them take different actions based on data source results.

Please take a look at the [module composition documentation](https://www.terraform.io/docs/modules/composition.html) - specifically, the section that describes [conditional creation of objects](https://www.terraform.io/docs/modules/composition.html#conditional-creation-of-objects
) - for a full description.

I realize that this will be an unsatisfying response to some. I encourage you to visit [the community forum](https://discuss.hashicorp.com/c/terraform-core) if you have any questions about restructuring your configuration to achieve the results you need without this feature.

Thank you!
