### ISSUE TITLE
push command ignores -atlas-address argument

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#15517]
`terraform push` command ignores the `-atlas-address` argument ([docs link](https://www.terraform.io/docs/commands/push.html#atlas-address-lt-url-gt-)). If I set the `address` in the `atlas` backend, it works, but the CLI argument should still take precedence.

### Terraform Version
- v0.9.8
- v0.9.11

### Terraform Configuration Files
```hcl
terraform {
  backend "atlas" {
    name         = "clstokes/cameron-push-atlas-address"
    #address = "cameron.example"
  }
}
```

### Debug Output
https://gist.github.com/clstokes/70e5b93a515ef64da700ed50ac7a8426

### Expected Behavior
Terraform should use my `-atlas-address` argument as described in the [docs](https://www.terraform.io/docs/commands/push.html#atlas-address-lt-url-gt-).

### Actual Behavior
It still uses the default address of atlas.hashicorp.com.

### Steps to Reproduce
1. With a minimal config (such as an AWS keypair) and the backend config above...
1. `terraform push -name=clstokes/cameron-push-atlas-address -atlas-address=https://cameron.example`

**Comment by apparentlymart** [comment]
Hi @clstokes,

We've actually been talking about removing these options altogether and _requiring_ the backend config to be set correctly, but this issue suggests that there's a valid use-case for pushing to a different TFE than configured in backend... if so, I'd like to know about it!

However, it not behaving as the docs suggest is definitely a bug, so we can put aside the ideal behavior for the moment and just get this fixed.

**Comment by clstokes** [comment]
I can think of a use case for pushing to a different named environment with `-name`, but I cannot think of a need to push to a different address _dynamically_. I think the user that ran into this was using `-atlas-address` because it was there. I've recommended they set the address attribute in their backend configuration as that seems more maintainable long-term.

To summarize, I think the `-atlas-address` argument can be removed, but not _all_ backend configurations should be removed, ie. `-name` should remain.

**Comment by apparentlymart** [comment]
Hi @clstokes! Sorry for the long silence here.

Since Atlas is now end-of-life and shut down, the `terraform push` command is nonfunctional and will be removed from Terraform in the v0.12.0 release. As you may have seen, a separate [TFE CLI tool](https://github.com/hashicorp/tfe-cli) is now serving the equivalent purposes for Terraform Enterprise, and [remote operations](https://www.terraform.io/docs/enterprise/run/cli.html) will eventually provide the new integration between Terraform CLI and Terraform Enterprise.

Since this command is no longer available, I'm going to close this out.
