### ISSUE TITLE
fail to read terraform_remote_state generated by tf0.9.8 with tf0.8.8

### ISSUE THREAD

**Issue by pradeepbhadani** [hashicorp/terraform#15516]
Hi ,

I am running terraform 0.8.8 version code to read remote terraform state file(generated using tf 0.8.8 and then upgraded to tf0.9.8) but it fails with the following error 
```
data.terraform_remote_state.test_remote: Decoding state file failed: json: cannot unmarshal object into Go struct field InstanceState.meta of type string
```

I tried searching for ```InstanceState``` in remote state but cannot find any text matching this.
So I am not sure which part of JSON terraform is trying to unmarshal here.

### Terraform Version
Terraform v0.8.8 and
Terraform v0.9.8

### Terraform Configuration Files (main.tf)
```hcl

provider "aws" {
  region					        = "us-west-2"
}

data "terraform_remote_state" "test_remote" {
  backend = "s3"
  config {
     bucket = "terraform-remote-state"    
     key    = "tf-state"
     region = "us-west-2"
   }
}
```

### Terraform Remote state File
```hcl
{
    "version": 3,
    "terraform_version": "0.9.8",
    "serial": 222,
    "lineage": "************",
....
...
}
```

### Expected Behavior
main.tf should be able to read remote state 

### Actual Behavior
Failing with error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a remote state file with terraform v.0.8.8
2. Upgrade it to terraform v0.9.8
3. Try to read remote state file using terraform v0.8.8

**Comment by iceycake** [comment]
I think that's expected behavior, no?  I don't think you can use an older version of terraform to read a newer version of terraform state file.

**Comment by pradeepbhadani** [comment]
@iceycake  Can you please share the reference document to see in more details?

If this is expected behavior then it would be very hard to upgrade all terraform codes to newer version simultaneously. I never came across this for terraform < 0.9

**Comment by iceycake** [comment]
@pradeepbhadani There is always breaking changes between minor version upgrade (0.7 to 0.8, 0.8 to 0.9, and soon 0.9 to 0.10).  In the changelog, Hashicorp does a great job on warning breaking changes.

We have been using Terraform since 0.7.4 and we have seen a lot of backward compatiability between even within the same minor version (e.g. 0.8.7 can’t use 0.8.3 state file etc)

May be I would let Hashicorp answer this question but we always tell our developers DO NOT use older terraform binary to access any state file that is touched by newer version.

**Comment by apparentlymart** [comment]
Hi @pradeepbhadani! Sorry for the delayed response here.

At present, this is unfortunately expected behavior since the Terraform state format is not stable between versions and is only upgradeable _upwards_ to newer versions.

You're right that this causes some problems when using `terraform_remote_state` across different Terraform versions. Currently it's necessary to upgrade things in a "leaf-first" order, so that a newer version of Terraform is used to apply a config that reads an older state rather than the other way around.

We know this is not ideal but is a compromise we have to make right now while Terraform's internals are still changing quite a lot between releases. As we get closer to 1.0 we will be able to stabilize these file formats and thus likely relax some of these restrictions, but that remains to be seen.

I'm sorry for the inconvenience this causes, and that this was not better documented. In the short term, we should add a note to the `terraform_remote_state` docs about this limitation. For complex systems with many Terraform configs, it can be a better idea to reduce coupling by writing shared values out to a specialized config store such as Consul (e.g. using `consul_key_prefix`), since that then serves to isolate better the details of separate configurations and, where it's useful, also make use of that data with other tools such as `consul-template`.

**Comment by pradeepbhadani** [comment]
@apparentlymart Thanks for details.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity, and the changes that have happened over the years. Modern versions of terraform are (mostly) able to read remote state written in other (relatively modern) versions of terraform - terraform v0.12 can read state written in v0.11, for example.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
