### ISSUE TITLE
Terraform generate config after import

### ISSUE THREAD

**Issue by kdvlr** [hashicorp/terraform#15518]
According to the documentation for import existing resources, it states - 

> The current implementation of Terraform import can only import resources into the state. It does not generate configuration. A future version of Terraform will also generate configuration. 

Is there a release/ETA by which this will be supported ? This would be extremely useful for managing infrastructure created outside of Terraform.

**Comment by apparentlymart** [comment]
Hi @kdvlr! Thanks for the interest in this feature.

In general we cannot commit to things being done at particular times since that's not how Terraform work is planned, but this is definitely still something that we want to get done, and have some early sketches of how it might work. It'll need some more prototyping and design before it can be implemented "for real". We'll post more when we have it.

**Comment by dolvany** [comment]
I just started using terraform and I consider the lack of config import to be the biggest gap in functionality. After import is working, it would be ideal to take it a step further and implement a terraform discover function. +1

**Comment by andrewcrowly2** [comment]
Hey I want to reiterate what @dolvany said above. This gap is really what is stopping us from using Terraform more broadly in our organization.

**Comment by isaac88** [comment]
+1

**Comment by val-litvak** [comment]
+1

**Comment by colin92** [comment]
+1

**Comment by 2color** [comment]
+1

**Comment by apparentlymart** [comment]
I'm going to close this one just to consolidate into #15608, since they are both covering the same request.
