### ISSUE TITLE
Access to Provider properties from the same Provider's Resource

### ISSUE THREAD

**Issue by BenPhegan** [hashicorp/terraform#1551]
We have a use case where a property that is required by the provider setup is also required by multiple of that provider's resources.  It is not an ideal or clean problem to work around, but it is based on integrating to providers with particular constraints.

From what we can see there does not appear to be an easy way to do this within the resource code.  There is also no clear way to do this as a variable within the DSL, other than using a user variable and applying that value to both the provider and the resource (we can do this, but it is not ideal).

So, is there a way to:
1. Programmatically from a resource access the provider properties
2. From the DSL access a providers properties

Happy to provide further details if required, but the use case should probably be abstracted somewhat from the actual case in point, as it is a bit messy!  :)

**Comment by BenPhegan** [comment]
@phinze hopefully this makes more sense than the previous 140 characters!

**Comment by phinze** [comment]
Hi @BenPhegan, thanks for following up with the more detailed report. :grinning: 

> We have a use case where a property that is required by the provider setup is also required by multiple of that provider's resources. It is not an ideal or clean problem to work around, but it is based on integrating to providers with particular constraints.

If I'm understanding this correctly, I think this the sort of use case we were considering when we decided to go with a generic `meta interface{}` instead of a rigid config struct for providers.

Whatever you return from your `ConfigureFunc` will be what's yielded into the `meta` argument for your resources, so there's no reason you couldn't attach arbitrary fields to that struct and have them available in all your resources.

Just to pick a concrete example, here's the Google provider setting up its config struct:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/provider.go#L48-L60

That makes `meta` a `(*Config)`, which can be accessed like this:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_firewall.go#L122

You see we have `AccountFile`, `Project`, and `Region` as available fields here, and there's no stopping us from adding more.

Hope this helps! Let me know if this makes sense to you, or if there's something I'm missing from your question.

**Comment by mitchellh** [comment]
Closing since this looks answered.
