### ISSUE TITLE
Initializing providers for hundreds of modules makes plan and apply slow

### ISSUE THREAD

**Issue by vvondra** [hashicorp/terraform#15520]
### Expected Behavior
What should have happened?

Running a plan or apply should re-use the provider configured in the root modules

### Actual Behavior

The same provider is configured/initialized for each module, slowing down plan tremendously. If the provider doesnt change from the root/parent module, it should be re-used in the module traversal.

Sample log:
```
module.foo_bar_sns_topic.aws_cloudwatch_metric_alarm.event_bus_topic_queue_alarm", waiting for: "module.foo_bar_sns_topic.provider.aws"
module.bar_baz_sns_topic.aws_sqs_queue.event_bus_topic_queue", waiting for: "module.bar_baz_sns_topic.provider.aws"
...
...
and hundreds more like this
```

### Description

We have a large generated terraform template which includes a few hundred instances of the same locally sourced module. It contains about 5 resources (sns, sqs, policy, subscription).

If we run plan, it runs very very slow. If I enabled debug output, it seems to be running ConfigureFunc of the AWS provider for each instance of the module. This generates a lot of API calls to set up the client (most slow ones are in GetAccountInfo)

Feel free to correct me that this is an AWS provider only ticket, but my feeling is it affects all providers.

**Comment by jbardin** [comment]
Hi @vvondra,

The handling of provider has been overhauled in the terraform core, and should now initialize the providers only the minimum number of times. As of 0.11.0-rc1, each provider is only instantiated once globally for each configuration (though there may still be duplicate configurations), rather than once for each module that uses it. Additionally, provider passed into a module via the new module/providers mapping will use the root provider even though the module has an empty provider block.

You can see some of the examples being worked on in the upgrade guide https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-11.html.markdown

**Comment by vvondra** [comment]
Awesome 🙌
