### ISSUE TITLE
Different syntax causes state inconsistency

### ISSUE THREAD

**Issue by bitbrain** [hashicorp/terraform#15534]
### Terraform Version
Terraform v0.9.11

### Terraform Configuration Files

**module_a/main.tf**:
```hcl
resource "aws_ecr_repository" "foo" {
  name = "bar"
}
```
**module_b/main.tf**:
```hcl
module "module_a" {
  source = "../module_a"
}
```

### Expected Behavior
Regardless of which module I execute, both should behave the same, since both modules are logically referring to the same resource (`aws_ecr_repository`)

### Actual Behavior
Terraform detects infrastructure changes, when executing first `module-a` and then `module-b`, even if nothing has changed logically.

### Steps to Reproduce
1. `terraform get module_b`
2. `terraform apply module_a`
3. `terraform apply module_b`

### Workaround

A workaround right now is to create a 3rd module:

**_internal/module_c/main.tf**:
```hcl
resource "aws_ecr_repository" "foo" {
  name = "bar"
}
```
And then let all other modules refer to this one, e.g.:
**module_a/main.tf**:
```hcl
module "module_c" {
  source = "../_internal/module_c"
}
```
**module_b/main.tf**:
```hcl
module "module_c" {
  source = "../_internal/module_c"
}
```
Executing the steps above to reproduce will then lead to the expected result. The state has not changed. However, this should be inbuilt inside Terraform so it "knows" about the logical state and doesn't make it dependent on syntax (inside or outside of a module).

**Comment by jbardin** [comment]
Hi @bitbrain 

Thanks for creating a nice example to document this.

This is inherent in how Terraform operates, as resources are addressed by their location in the config, which is all relative to the root module. Changing the module hierarchy changes the address of the resources in the modules, and there isn't a way for Terraform to map known resources to the new configuration. In practice this is no different than changing the name of the "foo" resource to "module_b_foo"; it's conceptually the same but terraform sees it as a different resource. 

The fact that the same module can create multiple resources is how modules are designed, and while it might be theoretically possible to implement, this isn't something we have planned for Terraform. 

This is also related to #15459

**Comment by bitbrain** [comment]
@jbardin That's for clearing this up. Could you please elaborate why this isn't planned for Terraform?

**Comment by jbardin** [comment]
No problem. 

It's really just a departure from how modules are implemented and generally used. Terraform would need to have a way to "rescue" an orphaned resource, determine if it is an exact match for another planned resource, and move it in the state instead of creating the new one. While this might work for refactoring, it has the issue of assuming the user's intent, which may have been to destroy and create a new resource. For one-time refactoring, we can do this already with `terraform state mv`. 

If we start from the concept in the issue linked above, we could probably come close by requiring the user to set some sort of flag on a resource indicating that it should be tracked as a unique global resource outside of its namespace. That however would be a rather complex feature that would require a equally beneficial use case. We also already have ways to create shared resources by creating the resources at a higher level and passing them down into dependent modules, or by using multiple configurations and states.
