### ISSUE TITLE
tilde in terraform plan -out flag creates a directory at current dir

### ISSUE THREAD

**Issue by jaoracle** [hashicorp/terraform#15541]
# PROVIDER ISSUES

**PLEASE NOTE:** Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

- https://github.com/terraform-providers

All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here. 

------

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.9.11

### Expected Behavior
What should have happened?

Terraform should honor the tilde expansion to the users home dir.

### Actual Behavior
What actually happened?

The tilde is just part of the filename string and a directory+file local to where the command is run is created with the path `./~/foo/tf.plan`. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform plan -out ~/foo/tf.plan`

**Comment by jbardin** [comment]
Hi @jaoracle,

How exactly are you executing Terraform? 

Tilde expansion is handled by the shell, so terraform should never see the `~`, and only have the path. This is roughly equivalent to using `${HOME}`, but does have slightly different quoting rules. For example, If I run the literal command you pasted using a bash shell, terraform get the arguments:

    2017/07/17 18:17:55 [INFO] CLI args: []string{"terraform", "plan", "-out", "/home/jbardin/foo/tf.plan"}

**Comment by jaoracle** [comment]
Here's the direct paste of my run:
`~/bin/terraform plan -out=~/foo/tf.plan -state=~/terraform/state/qa/terraform.tfstate`

It created a dir in the folder this was run from:
`drwxr-xr-x  3 jnhrens staff   102 Jul 18 08:56 '~'/`

Bash expansion worked for the path to run the binary and for the `-state` option, but not `-out`. And `~/foo/` existed prior to running the command.

**Comment by jbardin** [comment]
OK, this makes more sense. You've stumbled onto an edge case where you essentially "tricked" the shell into ignoring the tilde. 

The shell doesn't expand the tilde if it's not a prefix or if it doesn't look like a variable assignment. The combination of the `-` at the beginning of `-out`, and the `=` character directly before the `~` prevent the shell from expanding it.

Your original example works, because the `~` is the prefix for the path, but your second example replaces the space with a `=`. You can see the same behavior directly in the shell:

```
$ echo +X ~/foo
+X /home/jbardin/foo

$ echo +X ~otheruser/foo
-X /home/otheruser/foo

$ echo X=~/foo
X=/home/jbardin/foo

$ echo +X=~/foo
+X=~/foo
```

Tilde expansion is strictly a feature of some shells, and not something that we are going to implement in Terraform itself.
