### ISSUE TITLE
Improve `import` feature documentation

### ISSUE THREAD

**Issue by dilchenko** [hashicorp/terraform#15569]
Hi,

I would like to suggest a simple but important documentation improvement. Currently, the [import feature docs ](https://www.terraform.io/docs/import/usage.html) suggest that:

```The above command imports an AWS instance with the given ID to the address aws_instance.bar.```

While technically correct, this makes little sense as a default (and only) example on the page. As the feature name suggests, it is about importing existing resource. Thus, a sane default would be to give a resource the same name in the state file as it's current name/ID at the source. This could be achieved by changing documentation so that an example of how to import a resource preserving it's name is provided and it is the topmost item on the documentation page.

### Suggested language:
...
Using terraform import is simple. The most basic operation is to import a resource preserving it's name. An example is shown below:
```
$ terraform import aws_instance.i-abcd1234 i-abcd1234
$ terraform import aws_iam_user.backup-db backup-db
$ terraform import aws_s3_bucket.my_site_static_files my_site_static_files
```
The above commands:
* Imports the state of the instance `i-abcd1234` into the state file under resource `aws_instance.i-abcd1234`
* Imports the state of the `backup-db` user into the state file under resource `aws_iam_user.backup-db`
* etc.

It is also possible to give the resource a different name in the state file while importing:

```$ terraform import aws_instance.bar i-abcd1234```

The above command imports an AWS instance with the given ID to the address `aws_instance.bar`.
...

**Comment by apparentlymart** [comment]
Hi @dilchenko! Thanks for this suggestion.

The import workflow is changing a little for version 0.10, so there have already been some updates to the docs, which you can see here: 
https://github.com/hashicorp/terraform/blob/7ed70bb/website/docs/import/usage.html.md

The key change here is that it'll now be required to write at least an empty configuration block for a given resource before importing into it. This is intended as a sort of confirmation of the correct resource name being used, since before it was common for people to make typos when running `terraform import` and end up importing something under the wrong name, which would then be destroyed by Terraform on a subsequent run.

I think the new wording addresses some of the things you were looking for here, albeit in a different way. What do you think?

**Comment by dilchenko** [comment]
Thank you for prompt response. I looked at the updated docs, and I agree with you - the new docs and the requirement to create at least empty configuration address the issue. However, with only one example on the page, I would still like it to show how to import a resource with the same name instead of some abstract `bar`. If you agree, I can send you a pull request.

**Comment by apparentlymart** [comment]
We generally _don't_ recommend using the AWS id as the local resource name, since Terraform names are intended to be local to the module, rather than global things, and indeed it could get confusing if later changes cause the resource to get replaced and thus issued a new id entirely. This is, of course, less significant for resources that have user-assigned names rather than ids, but even then the name used in the API often has additional qualifies to account for the fact that API names are global while Terraform names are module-local.

What about if we were to change it to `aws_instance.main`? That is still rather generic but it is at least a name someone is likely to use in a real-world configuration -- it's common to use "main" as the name of a single resource of a given type in a module.

**Comment by dilchenko** [comment]
Then how about this?

Generally, the syntax of the command is:
```terraform import <tf_resource_type>.<tf_resource_name> <cloud_provider_resource_name>```

For example:
```$ terraform import aws_instance.bar i-abcd1234```

Also, this documentation page might be a good place to state or remind about your recommendation to avoid using cloud provider resource IDs as local resource names. If you feel these suggestions are too extensive - feel free to close this issue.

As for my issue,  we are not really following your general recommendations internally and utilize AWS resource names/IDs as local resource names/IDs. That was clearly at least part of my confusion. Thanks again for replying to the issue and providing the background behind the feature behavior - this is very helpful.

**Comment by apparentlymart** [comment]
In reading the doc page again, I just noticed that there's a typo of "Console" instead of "Consult". I'm going to leave this issue open as a reminder to do another editorial pass on this page before we get to 0.10 to try to improve it in response to your feedback and to fix that typo. Thanks again for opening this!

**Comment by apparentlymart** [comment]
I made some revisions in #15589 with the intent of being more explicit about how each of the arguments is used, including the clarification about the separation between the names used in Terraform and the names used in the remote providers.

This does indeed duplicate some things that are mentioned a few times elsewhere, but it seems like the right compromise because often `terraform import` is one of the earliest things people do with Terraform as they're getting started (once they've learned the basics through the guide) so I tried to write it with the "completed the guide but still learning" audience in mind.
