### ISSUE TITLE
Provider Bundle Files Naming Convention

### ISSUE THREAD

**Issue by iceycake** [hashicorp/terraform#15561]
When using the `terraform-bundle` to download/package the providers, I notice the provider filename has the format of

`terraform-provider-xyz_v0.1.2_x4`

I'm wondering what does `x4` stands for as `v0.1.2` obviously is the version of the provider.

**Comment by apparentlymart** [comment]
Hi @iceycake,

This number is the plugin protocol version. It will increase if we make a breaking change to the protocol used between Terraform core and the provider plugins, so Terraform knows not to try to use a plugin version that is incompatible.

It is a bit redundant for these bundles since they are combined with a specific version of Terraform anyway, but this is the same convention used for the auto-installed plugins so that Terraform knows it needs to fetch new plugins on the next init after an upgrade past a breaking change.

**Comment by iceycake** [comment]
I am trying to build some of the providers with cherry picking unaccepted PRs.  By simply using the provided makefile, it will simply build the binary with the name `terraform-provider-aws` without the additional information in the file name.

Am I missing anything?  Is there anyway to have the build output the binary file name same as the bundle?

**Comment by apparentlymart** [comment]
Currently the version naming is added at release time, so if you build your own binaries you'd need to assign a version number yourself. The `_x4` portion is actually optional and you can safely omit it as long as you know you're building compatible plugins, which is always true right now since protocol version 4 is the only version currently supported.

There isn't an established way to assign a version number to a build that hasn't been officially released, but I suppose you could use a version number one patch release higher than the latest official release and add a suffix like `-iceycake` (or your company name, or any other string) and then the version system will treat it like a funny sort of beta/pre-release, newer than the previous version but older than the next version.

**Comment by apparentlymart** [comment]
Hi again, @iceycake!

Looking back at this, I see that you had also asked if we could make the local build process produce binaries that match the naming convention. Unfortunately that isn't possible right now for the reason I noted in my previous commit: it's the release process that assigns the version number.

We don't plan to change that for now, and instead expect that those building providers will rename the binary to include a suitable version number (ideally including a pre-release modifier to avoid conflicts with official releases) as part of their own build process.

We do in future plan to have a more robust mechanism for dealing with providers that aren't coming from the main repository, but have some foundational work to do in the way the repository works before we can support that; currently it's depending on some implementation details of how releases.hashicorp.com works that won't generalize well to other servers.

We'll have more to share on third-party provider builds once we've completed some design and prototyping work in this area. For now, manually renaming the binaries (or, renaming them with a custom build script) is the recommended solution, though I understand that this is non-ideal.
