### ISSUE TITLE
Terraform not initializing azure backend with interpolation in .tfvars file 

### ISSUE THREAD

**Issue by gangadhar01a** [hashicorp/terraform#15574]
Terraform version 0.9.8

Terraform config files
backend.tfvars:   

```hcl
      storage_account_name =  "erpterraform"
      container_name       =  "gpdbterraform"
      key                  =  "gpdbterraform"
      resource_group_name  =  "enterpriseapps-storage"
      access_key           =  "${var.access_key}"
```

main.tf

```hcl
  terraform {
backend "azure" {}
  }
```

I would like to initialize the backend (Azure), I ran the command `terraform init -backend-config=backend.tfvars`.

Expected output: 
It has to initialize the backend and ask to push the tfstate file to azure

Actual output:

```
Error loading backend config: 1 error(s) occurred:

* terraform.backend: configuration cannot contain interpolations

The backend configuration is loaded by Terraform extremely early, before
the core of Terraform can be initialized. This is necessary because the backend
dictates the behavior of that core. The core is what handles interpolation
processing. Because of this, interpolations cannot be used in backend
configuration.

If you'd like to parameterize backend configuration, we recommend using
partial configuration with the "-backend-config" flag to "terraform init"
```

**Comment by gangadhar01a** [comment]
Error suggested to use the partial backend with "backend-config" file in order to parametrize the required key's for backend, which doesn't worked in this scenario. Did I missed anything here?

**Comment by apparentlymart** [comment]
Hi @gangadhar01a! Sorry this error message isn't clearer.

This message is suggesting that since you can't use interpolations in backend configuration -- even _if_ it's in a separate `tfvars` file -- that you need to write the values directly into that external vars file.

Although we usually recommend setting per-user security credentials via environment variables to avoid issues like this, if you _need_ to include this directly via backend config then the way to do it is to place the access key directly into the `backend.tfvars` file. If you have a mixture of things that need to always be set the same and things that need to change per-user then you can split the settings between the `backend` block and potentially multiple `-backend-config` files.
