### ISSUE TITLE
Support "count" in route items within aws_route_table

### ISSUE THREAD

**Issue by paulrowlands** [hashicorp/terraform#15583]
I am creating an aws_route_table module for our relatively simple build which I would like to support the typical public & private route tables, whereby public subnets go via an IGW and private subnets go via a NAT instance.

I would like to have a single module to handle both subnets, but am struggling to see how to specify the different routes (in the public routing via a "gateway_id" and for the private routing via an "instance_id"); I thought it would simply be a case of seeing whether one or the other is set and using a "count", but it looks like count isn't supported within a "route { ... }" declaration.

`resource "aws_route_table" "rt" {
        vpc_id          = "${var.vpc_id}"

        route {
                count           = "${var.nat_instance ? 1 : 0}"
                cidr_block      = "${var.cidr}"
                instance_id     = "${var.nat_instance}"
        }

        route {
                count           = "${var.igw ? 1 : 0}"
                cidr_block      = "${var.cidr}"
                gateway_id      = "${var.igw}"
        }

        tags {
                "Name"          = "${var.name}"
        }
}
`

When I do "terraform plan", I get:
4 error(s) occurred:

* module.ks-private-rt.aws_route_table.rt: route.0: invalid or unknown key: count
* module.ks-private-rt.aws_route_table.rt: route.1: invalid or unknown key: count
* module.ks-public-rt.aws_route_table.rt: route.0: invalid or unknown key: count
* module.ks-public-rt.aws_route_table.rt: route.1: invalid or unknown key: count

It'd be handy if I could use count there.

**Comment by apparentlymart** [comment]
Hi @paulrowlands! Thanks for this feature request.

This is a more specific case of what's been discussed in #7034. We're currently doing some initial planning on a set of improvements to the configuration language, and trying to incorporate as many of these use-cases as we can, but it's still early so we don't have details to share yet.

I'm going to close this one to consolidate discussion in #7034, but please feel free to share your use-case there as another example to inform the design of a feature for this. (It may not be exactly using `count` here, since that mechanism has some details specific to resources as a whole, but we'd like to do _something_ to address this kind of use-case, so more examples are helpful to put bounds on the problem.)
