### ISSUE TITLE
Not able to destroy a nested resource

### ISSUE THREAD

**Issue by rzubin** [hashicorp/terraform#15584]
Hey,
I am getting a no match found when trying to delete a nested resource. The resource does appear in the plan output when I try to remove the entire module

### Terraform Version
Terraform v0.9.8

### Debug Output
Output when destroying the entire module -https://gist.github.com/rzubin/2c46f018a48a9c7fbd77192e3c81c6ba

Output when destroying a nested resource - https://gist.github.com/rzubin/e4c7d549e645663f5316d6a2d15e7d4a

### Expected Behavior
Destroy the nested resource and leave the rest of the module untouched

### Steps to Reproduce
1. `terraform plan -destroy -target=module.service1.vsphere_virtual_machine.node[1]`

**Comment by apparentlymart** [comment]
Hi @rzubin! Sorry for this strange behavior.

It looks like your shell (`zsh`) is intepreting the `[ .. ]` part before launching Terraform, and failing due to it actually being Terraform syntax. I'm not very familiar with `zsh`, but I would suggest trying to put the `module.service1.vsphere_virtual_machine.node[1]` argument in quotes to tell the shell that you wish to pass it through literally. At that point, Terraform should be able to get the string as you typed it and parse it as a resource address.

**Comment by rzubin** [comment]
Hey @apparentlymart. 
That worked! Thank you so much for the quick response and helping me resolve this

**Comment by apparentlymart** [comment]
Glad it worked out!

**Comment by dpuig** [comment]
Thanks, worked!!!
