### ISSUE TITLE
allow negative indices for the `element` function

### ISSUE THREAD

**Issue by rafalcieslak** [hashicorp/terraform#15582]
Since `element( list, index )` supports indices that are greater than the length of the list (by wrapping around the list using `mod`), it would also make sense for it to accept negative values, by wrapping around in the opposite direction.

An especially useful case would be using `-1` to get the last element of a list.

**Comment by thiagolsfortunato** [comment]
+1

**Comment by apparentlymart** [comment]
Hi @rafalcieslak! Sorry for the long silence here while we've been mostly heads-down on v0.12.0 development work.

Since the behavior you are describing is complementary with the modulo it takes for positive numbers, I agree that this is a reasonable thing to implement. We require being more explicit when using the native index syntax with square brackets, but the `element` function is intentionally more "helpful" so that common patterns can be expressed succinctly. (This is a situation where we compromised our usual rule that "explicit is better than implicit" for pragmatic reasons.)

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

Please note that the function implementations in the `config` package are no longer actually used and will be removed in the near future as part of some post-v0.12 code cleanup. The function implementations now live in [the `lang/funcs` package](https://godoc.org/github.com/hashicorp/terraform/lang/funcs), where you can find a function called `Element` which is a wrapper for calling the function definition in the `ElementFunc` variable.

We're currently in an informal feature freeze period while we finish up the v0.12.0 release so we won't be able to merge a PR for this at least until after v0.12.0 final is out, but we can look at at afterwards.

**Comment by darren-recentive** [comment]
Hello @apparentlymart,
With informal feature freeze period for `v0.12.0` being over, is there any possibility we could get some resources to help with this feature request? 🙏

**Comment by crw** [comment]
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!
