### ISSUE TITLE
Terraform + Docker Hub = Why you no release?

### ISSUE THREAD

**Issue by flyinprogrammer** [hashicorp/terraform#15593]
### Terraform Version
`0.9.10`
`0.9.11`

### Expected Behavior
We cut and release version tagged Docker containers when we release Terraform.

### Actual Behavior
`0.9.10` is tagged with `full`, `latest`, and `light`
There is no `0.9.10` tag. 
There is no `0.9.11` Docker release.

### Steps to Reproduce
1. Open a browser to here: https://hub.docker.com/r/hashicorp/terraform/tags/
2. Witness the non-existance of version tags or even a release.

---

I know it's annoying that I keep bugging you guys about this - it's only because I ❤️  you!

![Image of a heeler](https://s-media-cache-ak0.pinimg.com/736x/8c/b6/5f/8cb65f4ade9d9432921c58d33473800f--blue-heelers-australian-cattle-dog.jpg)

**Comment by tombennett** [comment]
+1

**Comment by BrentDorsey** [comment]
+1

**Comment by apparentlymart** [comment]
Sorry for the rather inconsistent releasing to dockerhub. The honest truth is that this step exists outside of our usual release process, is very manual, and works poorly. Due to this, we often get it wrong.

In #15596 you can see a step towards making this more streamlined, but unfortunately we were blocked from taking this any further forward right now because docker hub does not allow changing the source github repository of an existing docker repository.

Thus for the moment we will unfortunately need to continue maintaining the docker builds on a best-effort basis. For those who need quick access to new releases, for the moment the best path is to download the official builds from the releases server. We will try to get this working more smoothly once we can figure out how to make dockerhub play ball.

Sorry again for the weirdness here. :confounded:

**Comment by lattwood** [comment]
@apparentlymart 

would this work?

1. pull all the images locally
2. destroy the docker hub repo
3. create the new one linked to this repo
4. push the old images

What I just did for a workaround was...

```sh
hub checkout hashicorp/terraform
pushd terraform
git checkout v0.9.11
git cherry-pick 8666d3660961c445e4d262a63fcc3f631095772f -m 1
git tag -d v0.9.11
git tag -a v0.9.11 -m "v0.9.11"
pushd scripts/docker-release
IMAGE_NAME=terraform:0.9.11 hooks/build
docker tag terraform:0.9.11 REDACTED/terraform:0.9.11
docker push REDACTED/terraform:0.9.11
```

**Comment by apparentlymart** [comment]
Sorry for the delay in getting these recent releases onto dockerhub. I manually built and deployed 0.9.10 and 0.9.11 this afternoon so they should now be available for use. We're continuing to try to get in a better posture for releasing these promptly, with #15667 being in an interim step in this direction.
