### ISSUE TITLE
Precedence for variables defined by TF_VAR_ vs command line?

### ISSUE THREAD

**Issue by veetow** [hashicorp/terraform#15595]
I found documentation on variable precedence with regards to command line arguments, however, there is nothing mentioned regarding using `TF_VAR_` in conjunction with those.

I have found that when a `var-file` is used, that file will take precedence over anything defined via `TF_VAR_`.  That feels "wrong" to me, hence my ticket.

## Environment
* Terraform v0.9.11
* OS: macOS Sierra 10.12.4

**Comment by rorybrowne** [comment]
Personally I have a different feeling, ie that a var-file specified on the command line should override environment variables, or rather that the current behaviour is correct.

This would be mainly because environent variables are often set in advance, while options set on the commandline itself, are a little closer to the action, and I'd expect them to override pretty much anything else.

**Comment by veetow** [comment]
@rorybrowne, that's fair, and I see your point.  Which every way it _should_ work, I think we can agree that it's important the documentation is explicit about the order of precedence.

**Comment by apparentlymart** [comment]
Hi @veetow, @rorybrowne! Sorry the docs aren't clearer on this issue.

It's intended that `-var-file` behave the same way as `-var` here, with `-var-file` just being a more compact way to set a number of variables at once. Both of these override the environment variables, because we consider the CLI options to be conceptually "more local" to a specific invocation, with the environment variables providing defaults for these.

We'll get the docs updated for this. Thanks for pointing this out, @veetow!

**Comment by mcascone** [comment]
I agree with `-var-file` overriding TFVARS. But I would like to suggest that CLI options override `-var-file`, since as you say, CLI is closer to the action, and can be used for testing or manual config without changing any files.
