### ISSUE TITLE
Add the ability to create custom interpolate functions via a plugin.

### ISSUE THREAD

**Issue by joestump** [hashicorp/terraform#15603]
It would be nice if there was a way to write your own interpolation functions in Go using the TF plugin framework. e.g. `terraform-interpolation-function-myfunc` would surface as `${myfunc(arg1, arg2, ...)}`

On a second glance, it's not clear if `data` resources can be created via plugins either.

**Comment by apparentlymart** [comment]
Hi @joestump! Thanks for this feature request.

At this time we're not planning to allow custom functions, since it creates another compatibility surface to maintain over time and is thus likely to hamper our attempts to improve the configuration language over the next few major versions. However, we may do this eventually when things are more stable, since indeed it would be useful to be able to add custom behavior here.

Data sources are part of a provider, so they _can_ be implemented by plugins... in fact, that is the _only_ way they are implemented. Provider plugins include both managed resource and data source implementations, since the two are usually closely related.

I assume you're interested in data sources as an alternative to a custom function to do some custom behavior, and indeed that is possible. Data sources are in fact often more useful than functions because they participate in the dependency graph and can thus take actions that require earlier work to already have been done, though of course the syntax for using them is decidedly more verbose.

Another option -- with some caveats -- is [the `external` data source](https://www.terraform.io/docs/providers/external/data_source.html). This allows an external program implementing a specific protocol to be used as a data source, as a lighter-touch way to extend Terraform.

**Comment by apparentlymart** [comment]
In reviewing some older issues I noticed that this one actually duplicates #2771, so I'm going to close this just to consolidate discussion over here.

At this time we're still not planning to support plugin functions in the short term, but we'll keep the other issue open to remember the use-case and revisit it at a later time.
