### ISSUE TITLE
Can Terraform be used to filter trough the existing architecture and perform actions?

### ISSUE THREAD

**Issue by ss6851** [hashicorp/terraform#15635]
I am using `Terraform v0.9.11`. I want to know that if Terraform can be used to implement policies such as first identifying the unencrypted EBS from the existing infrastructure and then deleting the same? Or, identifying the public and unencrypted RDS instances and terminating the same?

**Comment by apparentlymart** [comment]
Hi @ss6851,

Terraform is not aimed at this sort of use-case. Generally, Terraform's role is to initially create objects and then, on an ongoing basis, apply changes to these objects based on changes to configuration. Terraform does not take actions on objects it didn't create.

Although the `terraform import` command does allow Terraform to take ownership of objects it didn't originally create, it does not have this sort of query functionality so an external program would be required to find the interesting objects and run `terraform import` on them, but with that external program in play it would probably be simpler to just call directly into the underlying API's delete action rather than bring Terraform into play.

The sort of functionality you describe -- pattern-matching on existing infrastructure and applying specific actions to it -- is not in the set of problems Terraform intends to solve. It's likely that the `import` functionality will grow more sophisticated eventually and may be able to import batches of objects matching certain constraints, but the goal here would be to import objects in their current form, rather than to delete them; further work outside of Terraform would still be required to automate updates or deletion of matched resources.

I hope this helps!
