### ISSUE TITLE
terraform 0.10 changes to init args break terragrunt

### ISSUE THREAD

**Issue by jre21** [hashicorp/terraform#15655]
The init change in #15032 removes functionality which terragrunt heavily relies on, as described in @brikis98 's comment in that pull request.

> Deleting this behavior is a major backwards incompatibility. It seems like at the minimum, this should have had a deprecation warning for one release, and then been removed. Better yet:
>
>> We can later reintroduce fetching modules with init without breaking this new behavior, by adding the source as an optional second argument.
>
> Can this be added before 0.10.0 comes out? Without this, this change is completely backwards incompatible and has no workaround. Re-implementing the fetch behavior of Terraform (i.e. with support for http, git, versioning, etc) is not something you can replace with a one-liner!

**Comment by apparentlymart** [comment]
Thanks for letting us know that terragrunt depends on this, @jre21 and @brikis98.

This usage was removed as another step towards `terraform init`'s new meaning of being an idempotent command that you can run to prepare a working directory for running other commands, which was started in 0.9. I'm sorry that there wasn't a more explicit deprecation cycle here, and that we didn't notice on our first pass that terragrunt was depending on this feature.

The "we can later reintroduce..." part of that comment is referring to some changes that are still in the early planning stages (and thus details are still rather loose) to improve how Terraform manages modules, including addressing things like #15613 and #15614 that currently create friction due to the current approach of packing so much into the module source strings.

After some internal discussion this morning we think we've found a suitable subset of what was planned to be introduced later to get back the previous functionality without preventing progress to the end goal. While we can't do this with the existing CLI workflow as it was in 0.9, we are thinking about supporting the following alternative usage for 0.10 to recover the lost functionality here:

```
$ terraform init -from-module=<module-source-string> <dir>
```

Does this look like something Terragrunt could reasonably support when running against Terraform 0.10 or above? The later changes will build on this by extending the "module-source-string" syntax and possibly adding other flags/commands into the mix, but we expect to be able to remain broadly compatible with the above usage given the initial design work done so far.

I'm planning to get this implemented before the 0.10.0 final release, modulo any tweaks we might need to make based on your feedback.

**Comment by brikis98** [comment]
@apparentlymart Would running `terraform init -from-module=<module-source-string> <dir>` do exactly what `terraform init <module-source-string> <dir>` does today? For example, if I run `terraform init -from-module=git::git@github.com:foo/bar.git/module-baz?ref=v0.0.2 .`, will it check out `module-baz` from tag `v0.0.2` of the `foo/bar` repo into the current directory?

If so, then I believe that would work perfectly for Terragrunt, and it would be easy to update it accordingly. Thanks!

**Comment by apparentlymart** [comment]
Yes, following the behavior of the old usage is definitely the goal here!

Thanks for the feedback. I'll be working on this imminently.

**Comment by brikis98** [comment]
Awesome, thank you!
