### ISSUE TITLE
feature request: pretty print JSON/user_data diffs

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#15662]
### Context

When applying updates to AWS IAM policies (or other resources with either JSON or `user_data`), the current diffs are difficult to inspect and scrutinize. For example, an update might look like:

```
policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Action\":[\"s3:ListBucketMultipartUploads\",\"s3:ListBucket\",\"s3:GetBucketLocation\"],\"Resource\":\"arn:aws:s3:::foo-bar-bucket\"},{\"Sid\":\"\",\"Effect\":\"Allow\",\"Action\":[\"s3:PutObject\",\"s3:ListMultipartUploadParts\",\"s3:GetObject\",\"s3:DeleteObject\",\"s3:AbortMultipartUpload\"],\"Resource\":\"arn:aws:s3:::foo-bar-bucket/*\"}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"s3:ListBucketMultipartUploads\",\n        \"s3:ListBucket\",\n        \"s3:GetBucketLocation\"\n      ],\n      \"Resource\": \"arn:aws:s3:::foo-bar-bucket\",\n      \"Principal\": {\n        \"AWS\": []\n      }\n    },\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"s3:PutObject\",\n        \"s3:ListMultipartUploadParts\",\n        \"s3:GetObject\",\n        \"s3:DeleteObject\",\n        \"s3:AbortMultipartUpload\"\n      ],\n      \"Resource\": \"arn:aws:s3:::foo-bar-bucket/*\",\n      \"Principal\": {\n        \"AWS\": []\n      }\n    }\n  ]\n}"
```

(well, imagine that with line wrapping...)

As a user concerned about security, I _must_ stick that into a text editor, reformat, and run a diff between the old and new policy. It's a little painful, to say the least.

### Proposal

It would be so incredible if TF were more helpful for us reviewing these diffs, and I'd like to propose that resources with JSON or `user_data` (any others with large blocks of text that change often?) render a more readable diff that can be easily reviewed by the operator looking to apply the plan, without resorting to `vim`/ `jq` and `diff`.

### References

#5179 is similar, but I think this proposal is specific to details not covered by that existing ticket.

**Comment by ketzacoatl** [comment]
Now that Terraform uses a SHA to refer to the rendered `user_data`, doing this diff manually is not even possible. It would really awesome if Terraform gave us a way to _see_ what the `user_data` will actually be.. otherwise we're playing with fire, and while that's fine in some scenarios, it'd be nice if we could be a little more confident in those other scenarios where an error is less forgiving.

**Comment by roman-cnd** [comment]
It is impossible to work without this feature with google provider. Google "merges" IAM policies for a project into one giant json file. Always generated on the fly, unsorted but terraform still can't detect changes. It's just impossible to verify what they are.

**Comment by apparentlymart** [comment]
Hi @ketzacoatl,

We've been doing some prototypes recently of using the new type system introduced by the configuration language improvements work in progress to give us more information to produce richer diffs, which includes line-by-line diffs of multi-line strings.

I posted a longer comment about this in #15180, which includes an example with some placeholder data. You're right that the hashing of `user_data` makes this attribute in particular quite hard to deal with, so we'll undoubtedly need to do some further work there to expose its true value again to produce a useful diff.

Now that we have a more concrete plan for improving the diff output, I'm going to close this just to consolidate the discussion over in #15180. I expect that we'll make all of the diff improvement changes together, since the new format is a total rewrite of the diff renderer with a new approach.
