### ISSUE TITLE
aws rds describe-db-instances --query

### ISSUE THREAD

**Issue by tuinho** [hashicorp/terraform#15686]
Hi,
Here is the Synopsis of describe-db-instances

 [--db-instance-identifier <value>]
 [--filters <value>]
 [--cli-input-json <value>]
 [--starting-token <value>]
 [--page-size <value>]
 [--max-items <value>]
 [--generate-cli-skeleton <value>]
I want to know what values in I should use for -db-instance-identifier, --filters, ... ?

If I want to use aws rds describe-db-instances --query, what values I must use in the --query ? Below is the example I got from internet: where are these values from (DBInstanceArn, Engine, DBInstanceIdentifier in --query) ???

aws rds describe-db-instances \
    --query 'DBInstances[*].[DBInstanceArn,Engine,DBInstanceIdentifier]' \
    --output text
And what is the syntax of --query 'DBInstances[*].[DBInstanceArn,Engine,DBInstanceIdentifier]'

**Comment by tombuildsstuff** [comment]
Hey @tuinho 

Thanks for opening this issue :)

From what I can see I believe this issue is related to the AWS CLI - whilst we could probably help with that, we're not aware of the specifics of the CLI - instead I think you may get a faster response to this question by re-opening this issue [on the AWS CLI Repository](https://github.com/aws/aws-cli).

As such I'm going to close this issue for the moment - however please feel free to re-open this if I've mis-understood this?

Thanks!
