### ISSUE TITLE
Feature Request: tags for spot fleet requests launch specification

### ISSUE THREAD

**Issue by taylorsmithgg** [hashicorp/terraform#15685]
[Reference from AWS](https://aws.amazon.com/about-aws/whats-new/2017/07/tag-your-spot-fleet-ec2-instances/?sc_channel=em&sc_campaign=Launch_Release_Notes_20170729&sc_publisher=aws&sc_medium=em_&sc_content=launch_la_nontier1&sc_country=&sc_geo=&sc_category=mult&sc_outcome=launch&mkt_tok=eyJpIjoiTkdFek56Sm1OMk15WkdVNSIsInQiOiJITjNcL2RPRmRSeXVESEhcL0l4QU1JRmxYWnBYemZMTnJmVFFsN2ZrSFZtR295R2ZjTlltOWp5XC9YcVFVbnBZYXoreXhDdWRkSys3OHRcL0o0MFZMdU53XC8xbHhEVGVqaXdmZ2kxRWRqUEFTVW9zcWlcL25US016TjlYbk16UlRTdzdneiJ9)

While previously not supported on AWS, this is now possible and should be added.

My particular use case involves using kubelet for auto registering nodes to a kubernetes cluster which requires a tag to find the instance.

**Comment by tombuildsstuff** [comment]
Hey @taylorsmithgg 

Thanks for opening this issue :)

This functionality has previously been requested in https://github.com/terraform-providers/terraform-provider-aws/issues/1232 - as such rather than having multiple issues tracking the same feature request, I'm going to close this issue in favour of that one.

Thanks!
