### ISSUE TITLE
Alternative `terraform import` workflow broken on terraform v0.10.0

### ISSUE THREAD

**Issue by ljfranklin** [hashicorp/terraform#15704]
It looks like terraform intentionally made a breaking change that requires imported resources to be specified in the config file before they can be imported. This breaks an, admittedly non-standard, workflow I've been using to ensure the list of firewall rules in GCP exactly matches those specified in my terraform templates and delete any extra rules. To do this, I use the gcloud cli to get a list of all firewall rules currently present in the IaaS, import all those rules (all good rules should already be present in the config files), then run terraform apply which deletes all the rules that were created out-of-band. Maybe an admin temporarily created an SSH rule and forget to remove it.

I understand this workflow maybe isn't the intended use of `import`, but it does provide a nice additional layer of security. Is there a way to still have this workflow in TF v0.10.0 and onwards?

**Comment by ljfranklin** [comment]
cc @apparentlymart

**Comment by apparentlymart** [comment]
Hi @ljfranklin,

Sorry we broke this workflow for you.

The intent of this change was effectively to prevent what you are doing here, since we got feedback that people were doing this sort of thing _accidentally_ and then deleting things they needed. The additional requirement here is intended as a sort of confirmation.

My best idea for getting back your workflow for now would be to have your program also generate a temporary config file with stub config blocks, and then delete it after the import are all completed.

We are planning to further improve import in future to make it _generate_ config, which will unfortunately make your workflow even trickier, so we'll need to have a think about how to support this sort of thing in the long run.

**Comment by ljfranklin** [comment]
@apparentlymart makes sense, agree that the UX of accidentally deleting something you wanted to keep is pretty bad. I guess what I'm trying to simulate is giving Terraform control over an entire project and having it delete things that shouldn't be there. Ensures reproducability and is a neat little security feature, e.g. an attacker managed to open a port in the firewall but a periodic Terraform job automatically closes it back down. Looking like `import` isn't going to be the right fit for this going forward. Closing this out, thanks for the explanation!
