### ISSUE TITLE
Replace ressource id (index) by string (dict, instead of index) 

### ISSUE THREAD

**Issue by derBroBro** [hashicorp/terraform#15720]
Hi there,

we have a issue with the definition of counted resources. It is some kind of hard to describe but I try my best.

Currently we have something like this:
```hcl
resource "aws_alb_target_group" "target" {
  name     = "${var.feature_ids[count.index]}"
  port     = "${8000+count.index}"
  protocol = "HTTP"
  vpc_id   = "${var.vpc_id}"
  count = "${length(var.feature_ids)}"
  lifecycle {
    create_before_destroy = true
  }
}
```
feature_ids is an array of features we work on. And here the problem starts. 
Lets say we start with this: ```["feature-1","feature-2","feature-3"]```

For this terraform creates a state in the background like this:
```json
{
 "aws_alb_target_group.target.0" : "name=feature-1, target_id=123",
 "aws_alb_target_group.target.1" : "name=feature-2, target_id=345",
 "aws_alb_target_group.target.2" : "name=feature-3, target_id=678",
}
```

If we change the working list to: ```["feature-1","feature-3""feature-4"]```
Terraform will start recreating every resource except feature-1 as the state is:

```json
{
 "aws_alb_target_group.target.0" : "name=feature-1, target_id=123",
 "aws_alb_target_group.target.1" : "name=feature-3, target_id=345,FORCE RECREATION",
 "aws_alb_target_group.target.2" : "name=feature-4, target_id=678,CREATE",
}
```

What we would like to get is, that feature-2 is removed and 4 added. But as HCL creates IDs based on the index in the background we get forced to destroy in general correct configurations.

The idea we had is if we can use a custom key instead of the index.
Example: 
```json
{
 "aws_alb_target_group.target.feature-1" : "name=feature-1, target_id=123",
 "aws_alb_target_group.target.feature-2" : "name=feature-3, target_id=345 DELETE",
 "aws_alb_target_group.target.feature-3" : "name=feature-3, target_id=678",
 "aws_alb_target_group.target.feature-4" : "name=feature-4, target_id=, CREATION",
}
```

For me it looks like the IaC definition itself gets some kind of "dirty" as TF injectecs indices.

### Terraform Version
0.9.2

Any ideas are welcome.  
  
Best regards  

Malte

**Comment by jbardin** [comment]
Hi @derBroBro,

I'm not exactly sure what you mean by a "custom key", or where that would be defined.

Relying on `count` is always going to force you to rely on an ordered list at some point. 
Can you ensure that changing changing the `feature_ids` list keeps unchanged entries at the same index? i.e. `["feature-1", "feature-4", "feature-3"]`, which is semantically what you are trying to do.

Or if that is generated externally, can you use an separate index of those names, either a second list or a map? That requires a little duplication, but will decouple the `feature_ids` from the instances.

**Comment by derBroBro** [comment]
Hi @jbardin ,

thank you for your reponse. You are right in some constraints the list ordering could be an option. The issue here is that the length and the content of the list can mostly not be controlled. 

If I define the whole thing "manualy" or via a "code generator" this should also work.

This snipped would work:
```hcl
resource "aws_thing" "thing_feature_1"{
  param = "123"
}
resource "aws_thing" "thing_feature_2"{
  param = "345"
}
resource "aws_thing" "thing_feature_3"{
  param = "678"
}
```
I think this would not be able to archive through a count function as terraform reflects the order (index) as part of the definition. Form my perspective the order should not be reflected in infra as code as these is just a internal "helper.

Best greards

Malte

**Comment by derBroBro** [comment]
I would be super happy about any feedback or workarround.

**Comment by apparentlymart** [comment]
Hi @derBroBro!

If I'm understanding correctly what you're asking for here, this sounds like the same problem discussed in #14275.

Our current plan to deal with this is to add a new attribute `foreach`, alongside `count`, that can be assigned some sort of collection (either a list or a map) and will then use the keys of that collection as the identifiers, rather than assuming indices. (Of course, using a list with `foreach` would _still_ use indices, since that's just the nature of lists!)

Unfortunately there's some other foundational work we need to do before we can implement this. The beginning of that work is being planned now and will start soon, but being able to support `foreach` is still a few steps away due to how deeply embedded the count-oriented assumptions are in Terraform right now.

In the short term, generating config is the only good _general_ workaround here, but I know this is frustrating because it requires an additional step outside of Terraform.

Another thing people sometimes do is to move the thing they want to duplicate into a child module and instantiate that module multiple times. This is still more verbose than simply defining a list of strings, but at least it avoids duplicating the things that are common between the instances. Modules are already identified by their names, so this index problem doesn't apply there.

Since we already have #14275 open, I'm going to close this one to consolidate the discussion. Thanks for sharing your use-cases here!
