### ISSUE TITLE
Interpolating an unused undefined value into a list results in empty list

### ISSUE THREAD

**Issue by refinitive** [hashicorp/terraform#15787]
This issue was revealed whilst trying to do the following (using AWS providers):

1. Create up to 3 networks using a module.
2. Use the route table id output from each of these to populate the routes using a second module.

The first module has an output:

```
output "route_table_id" {
  value = "${aws_route_table.rt.id}"
}

```
The second module expects:

`route_tables_count` - How many route tables to work on in the following array
`route_tables` - The list of route table ids to work on

### Requirement:

The basic idea is that the same code can be used to provide a variable number of route tables to the second module to modify depending on variables provided by json. Some of the networks may not have been created (depending on the config) so the count parameter is intended to only process the number which have been created. 

### Problem:

Any reference to an undefined value in the creation of the list, even if it is not used, results in the whole list being empty. In this example the network 1 and 2 route_table_ids are defined, network3 route_table_id is undefined. The result is an empty list:

  ```
route_tables = "${list(
    module.network1.route_table_id,
    module.network2.route_table_id,
    module.network3.route_table_id}"
```
Even with a ternary operator in place to prevent this variable from being used the same occurs:

  ```
route_tables = "${list(
    module.network1.route_table_id,
    module.network2.route_table_id,
    false ? module.network3.route_table_id : "")}"
```
 
Without the ternary operator, with just the variable directly the same empty list occurs. 

The debug output indicate the following for the above:

`2017/08/11 13:52:34 [DEBUG] Setting Unknown Variable Value for computed key: route_tables
`
### Terraform Version
0.9.11

### Expected Behavior
route_tables would be a list with three values, the third being an undefined value (example 1) or empty string (example 2)

### Actual Behavior
route_tables appears to be an entirely empty list

**Comment by apparentlymart** [comment]
Hi @refinitive! Sorry this isn't working as expected.

I think there are a couple different things doing on here. The first is that it's considered an error to refer to a module that doesn't exist. But along with that, due to #9080 the error for this is suppressed when used in an output; this expression would've been a fatal error in any other context.

With that said, there may be a different way to express what you are doing here, but I'm not sure I understand it fully yet. It sounds like you have a module that you've instantiated some number of times, and that number varies from one run to the next. What strategy are you using here to dynamically vary the number of modules? AFAIK Terraform doesn't currently support this, so I think I am missing something.

If you can share a little more context from your various configurations, I think that'll make it easier to follow what you've got so far and possibly to find a different way to express what you want here.

**Comment by refinitive** [comment]
Hi @apparentlymart , thanks for the quick reply.

That sounds about right. This is in effect to work around not being able to call a module with a count, which would have been the obvious thing to do. Rather than do this, the module itself is deciding whether to create resources (subnets and route tables) based on the input values:

  count = "${length(var.cidr_blocks) > 0 ? 1 : 0}"

As a result the outputs are undefined when the module decides not to create the resources. We are using logic after this to only create routes on the tables that we expect to have been created. Even a mere mention of one that hasn't been created is enough to invalidate that list.

At a high level what we are trying to do is:

- Use a module to create one or more subnets
- Use a second module to create a set of routing rules and apply it to the subnets created

The same code must be used for each different number of subnets and the configuration is provided in json.

It may be there there is no pattern available that would do this. 

In relation to #9080 will this issue be resolved at some point? I will need to check through our codebase to ensure we are not dependent on this defect elsewhere.

**Comment by apparentlymart** [comment]
Thanks for the extra detail, @refinitive.

Given your situation, the next thing I'd try is to make your child module output be a _list_ of route table ids, rather than just a single route table id that might be unset. This list will then either have zero or one elements, depending on whether the route table was actually created.

You can get this list using a "splat expression":

```hcl
output "route_table_ids" {
  value = "${aws_route_table.example.*.id}"
}
```

Then when you build your aggregated list of _all_ the route tables, you'd use `concat` instead of `list`, like this:

```hcl
  route_tables = "${concat(module.network1.route_table_ids, module.network2.route_table_ids, module.network3.route_table_ids, module.network4.route_table_ids)}"
```

Since Terraform doesn't currently have a "null" concept, a list of zero or one elements is commonly used as a substitute for it, due to the fact that such a thing is easy to create with a splat expression. (A true `null` is something we're considering for the forthcoming round of configuration language enhancements, which we'll have more details on soon once things are a bit more firm.)

#9080 will indeed get addressed somehow eventually, but we'll approach it carefully to minimize compatibility problems of the sort you're thinking of. We expect that the impact should be low since any _child module_ outputs that are actually being used would be failing already as you see in this bug, so the risk is mainly around root module outputs that are consumed via the `terraform_remote_state` data source from elsewhere, since indeed right now it is in theory possible to write a config that leaves an output unset if its value is invalid.

**Comment by refinitive** [comment]
Hi @apparentlymart,

Thanks for the excellent detailed reply. I've modified the code to use the approach you have proposed and the issue is now resolved. I'll keep my eyes peeled for the upcoming changes you mentioned so that maybe things can be represented more simply when they are optional items. 

Happy for you to close this issue as the defect is already represented elsewhere and it is not directly the cause of the issue reported.

Thanks again.

Adam.
