### ISSUE TITLE
Feature request: shorthand for setting variables

### ISSUE THREAD

**Issue by boompig** [hashicorp/terraform#15784]
Is it possible to have a shorthand for variables? Something like

```
variable "varname" = { "value" }
```

Typing

```terraform
variable "varname" {
    default = "value"
}
```

is not only cumbersome, it means less code can fit on screen. This results in unnecessary long files.

**Comment by apparentlymart** [comment]
Hi @boompig! Thanks for this suggestion.

The particular syntax you proposed here can't really fit within the constraints of the configuration format right now, but that doesn't mean we could try to find a _different_ concise way to declare variables.

I'm curious though: do you find that your modules generally have a _lot_ of variables? If so, I'm curious how you would characterize the usage of variables:

* Are there a lot because currently Terraform makes it hard to pass complex structures as a single value, and so you're unpacking a bunch of resource attributes into separate variables?
* Are you using variables with defaults as a way to factor out commonly-repeated strings, expecting that they _won't_ be overridden by the calling module?
* Something else?

The reason for this question is that we've been looking at some other language improvements that may help with the above in some different ways. With #15449 (which we should be able to land soon, after we get through some 0.10.0 fixes) we'll have a different way to deal with the second problem above. For the first, we're still in the early planning stage but we're planning to make it possible to pass complex object structures as variables, which I expect would result in certain modules requiring many fewer variables than before.

Of course neither of those things directly address the verbosity of individual `variable` blocks, but will ideally cause there to be _fewer_ variable blocks, and thus perhaps make the verbosity of each not feel _as_ heavy as it does today.

**Comment by boompig** [comment]
I find that factoring out those values which are likely to change in variables at the top of files is helpful. In practice this ends up being file paths mostly.

**Comment by in4mer** [comment]
Along these lines, I'd find it way, way better to be able to alias certain strings.  At this point I'm quite tired of typing null_data_source.  If we could come up with a way to alias strings to objects, that'd be nice.  I'd much rather type .nds.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

In Terraform 0.10.3 we added the concept of [local values](https://www.terraform.io/docs/configuration/locals.html) as a way to factor out a particular expression and give it a name, separately from the concept of input variables.

With that feature in place, we now recommend using `variable` blocks _only_ for values that are to be provided by the caller, and use the `locals` block for the situation described here where an expression is extracted so that it can be easily reused and changed in one place.

Local values have a more concise syntax because they don't have all of the other requirements that input variables need to deal with:

```hcl
locals {
  template_file = "${path.module}/example.tmpl"
}
```

While this change hasn't changed the `variable` block syntax at all, it does tend to reduce the number of `variable` blocks in a configuration since there's no longer a need to declare input variables just to reuse their values in multiple locations. Therefore I'm going to close this issue, since the current syntax complexity is necessary for the intended use-case of variable blocks (defining what is expected from the caller) and there's now a more concise way to achieve the other emergent use-case of factoring out values.

Thanks for sharing this use-case, and sorry again I didn't find this issue while we were preparing the 0.10.3 release.
