### ISSUE TITLE
Downloading provider from terraform init is terribly slow 

### ISSUE THREAD

**Issue by synthdnb** [hashicorp/terraform#15798]
I'm working in South Korea, and our connection to fastly CDN is terribly slow (<100KB/s). 
Before 0.10.0, every provider plugin was bundled in terraform binary so it was fine, but It became problematic now. 

Is there any way to mirror `releases.hashicorp.com`?

Also, is there any plan to cache providers downloaded from other Terraform projects somewhere in local (home dir or somewhere)? It may help us a lot.

**Comment by jbardin** [comment]
Hi @synthdnb,

I can totally sympathize with the issue. Most locations should have good access to Fastly edge nodes, but there are definitely going to be gaps. We are actively working in improving the overall workflow for plugins. 

In the meantime, you can always download and cache the providers you require manually.
Placing them in a directory within your config named `terraform.d/plugins/OS_ARCH` (with the appropriate OS_ARCH values) will allow them to be automatically discovered by terraform. 

You can also override the entire automatic installation process by providing a `-plugin-dir=` argument pointing to the location of the providers.

**Comment by apparentlymart** [comment]
Hi @synthdnb,

In addition to what @jbardin said, there's some additional info in the discussion of #15481 which reported a similar issue. In particular, there is a helper tool linked there that can produce a zip file of Terraform and a set of providers; extracting that zip file to a directory somewhere will create a Terraform install with certain plugins already available. This is equivalent to manually placing them in the same directory as the `terraform` executable, but perhaps easier to share a consistent set of plugins across a team by distributing that zip file from an internal server.

**Comment by alkar** [comment]
Another concern is that the current system uses way too much disk for no good reason. Each directory with a terraform state will have copies of the (most likely identical) binaries. Can't terraform place them in say `~/.terraform.d/plugins` by default and symlink in `.terraform/plugins` ?

**Comment by apparentlymart** [comment]
The change in #16000 will allow configuring an optional cache directory to be shared across different configuration directories, including creating hardlinks or symlinks where possible. I'm hoping to get that in soon.

**Comment by synthdnb** [comment]
Newly added cache feature helped us a lot. Thanks!

**Comment by sgendler-stem** [comment]
This is not a slow network problem.  It is a badly configured routing problem.  Period.  Let's not pretend otherwise. I am on an exceedingly well-connected network within the continental US, less than 5 miles from MAE West.  I couldn't be more well-connected.  Traceroute to release.hashicorp.com results in totally broken routes.  I'm guessing that with enough retries, it eventually resolves a host that is routable, but the more common response gives a host that cannot be accessed, which results in timeouts and retries before it eventually gets through.  The difference between accessing the server on roadrunner's network (sucks) and the Charter network at my house is the difference of seconds versus tens of minutes for provider downloads.  This is a bug in someone's config, either Lastly's, roadrunner's or hashicorp's.  The fact that the problem exists for people not on roadrunner's network implies that the problem is higher up the dependency chain than that - either lastly or hashicorp.

**Comment by sgendler-stem** [comment]
Here's an example traceroute

```
$ traceroute releases.hashicorp.com
traceroute to dualstack.s.shared.global.fastly.net (151.101.25.183), 64 hops max, 52 byte packets
 1  linksys26757 (192.168.1.1)  3.409 ms  3.248 ms  1.914 ms
 2  192.168.0.1 (192.168.0.1)  7.398 ms  11.830 ms  12.994 ms
 3  142.254.236.145 (142.254.236.145)  66.160 ms  29.186 ms  50.743 ms
 4  agg60.lsapcawv01h.socal.rr.com (24.30.169.105)  38.205 ms  26.028 ms  164.576 ms
 5  agg20.lsaicaev01r.socal.rr.com (72.129.19.8)  62.957 ms  39.310 ms  31.924 ms
 6  agg26.lsancarc01r.socal.rr.com (72.129.17.0)  94.504 ms  93.440 ms  106.055 ms
 7  bu-ether26.lsancarc0yw-bcr00.tbone.rr.com (66.109.3.230)  88.229 ms  67.098 ms  95.195 ms
 8  bu-ether11.tustca4200w-bcr00.tbone.rr.com (66.109.6.5)  121.601 ms
    bu-ether45.chctilwc00w-bcr00.tbone.rr.com (107.14.19.36)  79.806 ms
    bu-ether11.tustca4200w-bcr00.tbone.rr.com (66.109.6.5)  107.241 ms
 9  0.ae2.pr1.lax10.tbone.rr.com (107.14.19.54)  115.830 ms
    0.ae3.pr1.lax10.tbone.rr.com (107.14.19.56)  95.851 ms  72.528 ms
10  * * *
11  * * *
12  * * *
13  * * *
```

**Comment by jbardin** [comment]
Hi @spangenberg,

There may be something to that, but don't go by what traceroute shows. The intermediate routers aren't required to response to the icmp probes, not are the edge servers themselves. Traceroute goes nowhere for me too (as expected for most things outside my provider's network), but I have <10ms response times from the edge server. 

Something like `curl -s -v --trace-time https://releases.hashicorp.com/terraform-provider-aws/ >/dev/null` might provide some useful info. 

Can you provide the exact error returns by terraform? If the timeout is only during TLS handshakes, that's something we've seen before, but I haven't been able to replicate in a test environment.

**Comment by sgendler-stem** [comment]
I don't get an error from terraform. I just get unbelievably slow downloads that do not report an error.  It takes each provider, no matter how large or small, many minutes before it is downloaded.  When I simply browse to the same address via a web browser, it appears to work just fine.  My browser can pull providers from releases.hashicorp.com in seconds, while terraform requires 5-10 minutes each.

Downloading a provider directly via curl also results in no perceivable delay, so there is some distinct difference between that and how it is being downloaded by terraform, but there's not enough debug information available to determine what it is.  The slow downloads when running via terraform init are totally consistent - always slow.  Similarly, they are consistently NOT slow when accessing outside of terraform init.

**Comment by sgendler-stem** [comment]
Is terraform setting a header that results in lastly going to the origin for every request?  Something else that is causing work to happen on the server?  It doesn't make much sense that it would be slow only when downloading via terraform, but that is most definitely the case.

**Comment by jbardin** [comment]
Do you possibly have a proxy involved here? The main difference between terraform and curl is that terraform is will be using http2. If this is consistent for you, I would probably rule out a broken edge node, so something else is amiss. 

Try a minimal config like `provider "null" {}` with just http/1.1

    GODEBUG=http2client=0 tf init

If that helps at all, you can get the debug output from the http2 connection like so (warning, that trace log this will be large since it contains a lot of the provider binary data)

    GODEBUG=http2debug=1 TF_FORK=0  tf init 2> http2.trace

**Comment by sgendler-stem** [comment]
And while not every hop needs to respond to ICMP packets, it would be highly unusual for not a single hop outside of roadrunner's network to fail to respond, unless roadrunner's network is blocking incoming ICMP, which is unlikely.  I have allowed it to run through an additional 30 hops without getting a single valid response, ad I've tried increasing the timeout for each to be as high as 10 seconds. We know the default TTL is 64 hops, so it really ought to find some node along the route which responds, but it isn't.

**Comment by sgendler-stem** [comment]
No proxies anywhere, other than any transparent proxies that may exist out in the wider internet. And just for the record, I am one of 5 people responsible for inventing transparent proxying and WCCP at Cisco, was an early engineer at Akamai - building all of their dynamic content assembly infrastructure from scratch. I was the original engineer at Cedexis, and just spent 4 years at Google.  I know a few things about proxies, CDNs, HTTP performance, and networking.  I might not be surprised to see a few hops along the way which don't respond to traceroute, but I'd be very surprised to find the same problem at every hop after a single point - unless there's a routing problem.

I get much farther when running traceroute against hashicorp's main website, for example, despite traversing the same router at step 8 which is the last positive response when going to releases.hashicorp.com, so I have little reason to think that router is configured to block ICMP packets from coming back through.

```
$ traceroute www.hashicorp.com
traceroute to hashicorp-prod.netlify.com (104.198.106.181), 64 hops max, 52 byte packets
 1  linksys26757 (192.168.1.1)  1.393 ms  1.963 ms  3.346 ms
 2  192.168.0.1 (192.168.0.1)  10.664 ms  6.880 ms  6.369 ms
 3  142.254.236.145 (142.254.236.145)  19.113 ms  24.090 ms  16.451 ms
 4  agg60.lsapcawv01h.socal.rr.com (24.30.169.105)  16.491 ms  18.977 ms  26.745 ms
 5  agg20.lsaicaev01r.socal.rr.com (72.129.19.8)  28.611 ms  36.726 ms  47.129 ms
 6  agg26.lsancarc01r.socal.rr.com (72.129.17.0)  56.489 ms  36.424 ms  32.062 ms
 7  bu-ether16.lsancarc0yw-bcr00.tbone.rr.com (66.109.6.102)  29.815 ms  32.810 ms  28.587 ms
 8  0.ae1.pr1.lax00.tbone.rr.com (107.14.17.250)  24.387 ms
    ae2.lsancarc0yw-bpr01.tbone.rr.com (66.109.1.41)  21.141 ms
    0.ae0.pr1.lax00.tbone.rr.com (107.14.17.248)  36.723 ms
 9  ix-ae-24-0.tcore1.lvw-los-angeles.as6453.net (66.110.59.81)  24.226 ms  31.515 ms  28.074 ms
10  72.14.219.150 (72.14.219.150)  25.461 ms
    72.14.195.102 (72.14.195.102)  21.222 ms  41.603 ms
11  108.170.237.16 (108.170.237.16)  33.342 ms
    108.170.247.180 (108.170.247.180)  32.554 ms
    108.170.247.212 (108.170.247.212)  27.219 ms
12  108.170.234.38 (108.170.234.38)  32.690 ms
    108.170.247.212 (108.170.247.212)  30.990 ms
    108.170.247.147 (108.170.247.147)  109.298 ms
13  108.170.234.38 (108.170.234.38)  29.566 ms
    209.85.143.154 (209.85.143.154)  72.426 ms
    108.170.230.135 (108.170.230.135)  25.209 ms
14  64.233.174.125 (64.233.174.125)  72.821 ms
    216.239.41.85 (216.239.41.85)  88.250 ms
    64.233.174.99 (64.233.174.99)  74.209 ms
15  * * 209.85.142.20 (209.85.142.20)  78.193 ms
16  * * 
```

and here's a traceroute to google.com:
```
$ traceroute www.google.com
traceroute to www.google.com (216.58.216.4), 64 hops max, 52 byte packets
 1  linksys26757 (192.168.1.1)  6.353 ms  2.384 ms  1.329 ms
 2  192.168.0.1 (192.168.0.1)  8.637 ms  14.466 ms  33.763 ms
 3  142.254.236.145 (142.254.236.145)  33.239 ms  30.823 ms  23.718 ms
 4  agg60.lsapcawv01h.socal.rr.com (24.30.169.105)  25.912 ms  40.641 ms  20.471 ms
 5  agg20.lsaicaev01r.socal.rr.com (72.129.19.8)  29.458 ms  32.706 ms  29.821 ms
 6  agg26.lsancarc01r.socal.rr.com (72.129.17.0)  31.160 ms  57.910 ms  25.493 ms
 7  bu-ether16.lsancarc0yw-bcr00.tbone.rr.com (66.109.6.102)  34.954 ms  38.874 ms  37.540 ms
 8  * ae2.lsancarc0yw-bpr01.tbone.rr.com (66.109.1.41)  23.653 ms  40.105 ms
 9  ix-ae-24-0.tcore1.lvw-los-angeles.as6453.net (66.110.59.81)  37.508 ms  34.725 ms  33.145 ms
10  72.14.195.102 (72.14.195.102)  30.434 ms
    72.14.219.150 (72.14.219.150)  34.701 ms
    72.14.195.102 (72.14.195.102)  26.993 ms
11  * * *
12  108.170.225.68 (108.170.225.68)  41.365 ms
    lax02s21-in-f4.1e100.net (216.58.216.4)  31.893 ms
    108.170.225.122 (108.170.225.122)  35.899 ms
```

**Comment by sgendler-stem** [comment]
I don't really have the ability to modify the terraform init command with GODEBUG since I am running via terragrunt.  I have no clue if that variable will get passed all the way through to terraform.

Setting that variable didn't appear to have any impact at all.  Each plugin required at least 90 seconds to download, while grabbing them with curl or my browser takes 4-5 seconds, at most.

**Comment by sgendler-stem** [comment]
No difference at all with http2 disabled, even after I dissected the terragrunt terraform commands and ran them manually with with the variable set as you suggested.

I'm running the version with http2 and trace right now, but it will be awhile before I get a result.

**Comment by sgendler-stem** [comment]
Interestingly, I always assumed your plugin-cache functionality was simply broken, since it had absolutely NO impact on the speed of provider downloads, but now that I can see the trace, I can see why. The delay isn't in downloading the plugin, which isn't even happening.  The delay appears to be happening between plugin discovery and fetching provider info, since the large elapsed times are always occurring there.  It's not clear what it is actually doing when it is doing 'provider discovery' and 'fetching provider info'

```
2017/11/20 16:52:51 [DEBUG] plugin requirements: "terraform"=""
2017/11/20 16:53:36 [DEBUG] fetching provider info for template version 1.0.0
2017/11/20 16:53:51 [DEBUG] getting provider "template" version "1.0.0"
```

```
2017/11/20 16:53:51 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"template", Version:"1.0.0", Path:"/var/folders/xr/t6gsrby97350k0r85qr7blzh0000gn/T/terragrunt/mWsJuGe2dd9Pey43FjcJ5R3rdWU/N7YR7JXFv_AHrQ_vUpC9GGTlLbM/ecs/.terraform/plugins/darwin_amd64/terraform-provider-template_v1.0.0_x4"}:struct {}{}}
2017/11/20 16:54:37 [DEBUG] fetching provider info for aws version 1.3.1
2017/11/20 16:54:52 [DEBUG] getting provider "aws" version "1.3.1"
```

```
2017/11/20 16:54:52 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws", Version:"1.3.1", Path:"/var/folders/xr/t6gsrby97350k0r85qr7blzh0000gn/T/terragrunt/mWsJuGe2dd9Pey43FjcJ5R3rdWU/N7YR7JXFv_AHrQ_vUpC9GGTlLbM/ecs/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.3.1_x4"}:struct {}{}}
2017/11/20 16:55:39 [DEBUG] fetching provider info for terraform version 1.0.2
2017/11/20 16:55:54 [DEBUG] getting provider "terraform" version "1.0.2"
```

Those are all of the large gaps in the output.  Here's the whole thing as an attachment:


[http2.trace.txt](https://github.com/hashicorp/terraform/files/1489650/http2.trace.txt)

**Comment by sgendler-stem** [comment]
Here's the output of the identical command, this time with my .terraformrc modified to comment out the line about the plugin cache.

Now we have similar gaps, but different text:
```
2017/11/20 17:08:12 [DEBUG] plugin requirements: "template"=""
2017/11/20 17:08:57 [DEBUG] fetching provider info for template version 1.0.0
2017/11/20 17:09:12 [DEBUG] getting provider "template" version "1.0.0"
2017/11/20 17:09:12 [DEBUG] plugin cache is disabled, so downloading template 1.0.0 from https://releases.hashicorp.com/terraform-provider-template/1.0.0/terraform-provider-template_1.0.0_darwin_amd64.zip?checksum=sha256:d6169370178182eed6daed2c79880498d3be2b2269544458bbee4b4547916c3c
2017/11/20 17:09:28 [DEBUG] looking for the template 1.0.0 plugin we just installed
```

```
2017/11/20 17:09:28 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"template", Version:"1.0.0", Path:"/var/folders/xr/t6gsrby97350k0r85qr7blzh0000gn/T/terragrunt/mWsJuGe2dd9Pey43FjcJ5R3rdWU/N7YR7JXFv_AHrQ_vUpC9GGTlLbM/ecs/.terraform/plugins/darwin_amd64/terraform-provider-template_v1.0.0_x4"}:struct {}{}}
2017/11/20 17:10:14 [DEBUG] fetching provider info for aws version 1.3.1
2017/11/20 17:10:29 [DEBUG] getting provider "aws" version "1.3.1"
2017/11/20 17:10:29 [DEBUG] plugin cache is disabled, so downloading aws 1.3.1 from https://releases.hashicorp.com/terraform-provider-aws/1.3.1/terraform-provider-aws_1.3.1_darwin_amd64.zip?checksum=sha256:a4f5724de40eea724f9de3a68dd1d586781e9549602d8844a0b577a81abc2c84
2017/11/20 17:10:47 [DEBUG] looking for the aws 1.3.1 plugin we just installed
```

```
2017/11/20 17:10:47 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws", Version:"1.3.1", Path:"/var/folders/xr/t6gsrby97350k0r85qr7blzh0000gn/T/terragrunt/mWsJuGe2dd9Pey43FjcJ5R3rdWU/N7YR7JXFv_AHrQ_vUpC9GGTlLbM/ecs/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.3.1_x4"}:struct {}{}}
2017/11/20 17:11:32 [DEBUG] fetching provider info for terraform version 1.0.2
2017/11/20 17:11:47 [DEBUG] getting provider "terraform" version "1.0.2"
2017/11/20 17:11:47 [DEBUG] plugin cache is disabled, so downloading terraform 1.0.2 from https://releases.hashicorp.com/terraform-provider-terraform/1.0.2/terraform-provider-terraform_1.0.2_darwin_amd64.zip?checksum=sha256:21557e9a548beb83fa8462b026eab5971bcb4a39e3e29f98d587b7ed0eb5d366
2017/11/20 17:12:05 [DEBUG] looking for the terraform 1.0.2 plugin we just installed
```
[http2_without_cache.trace.txt](https://github.com/hashicorp/terraform/files/1489671/http2_without_cache.trace.txt)

**Comment by sgendler-stem** [comment]
The big time gap is always before it outputs the 'fetching provider info' line, though there is always a sizeable (15-20 second) gap after that line, too.  Unfortunately, there's no clue what it is actually doing in there.

**Comment by sgendler-stem** [comment]
And just for completeness' sake, here's the trace if I don't blow away my local copies (.terraform directory, not my cache, which doesn't speed the processing up at all) of the plugins first.  This is effectively instantaneous:

[http2_cached.trace.txt](https://github.com/hashicorp/terraform/files/1489698/http2_cached.trace.txt)

**Comment by jbardin** [comment]
@sgendler-stem:

I've been able to reproduce the log timings you have here with a broken ipv6 network in issue #16804. 

Can you confirm if this is the case for your host as well? The verbose output from `curl` would show that it's falling back to an ipv4 address, and specifying the `-6` option should hang, or at least give the same degraded performance as Terraform. 

We're going to fix the dual stack issue in Terraform, but if you are still experiencing other problems please add any further information to the new issue.

Thanks!

**Comment by sgendler-stem** [comment]
I don't need to test.  I know that ipv6 is disabled on the local router.

If using ipv6 and waiting for timeout (without any kind of warning or error
message) is some kind of Go default, someone needs to ensure that every
developer who ever ships a Go product includes instructions for how to
eliminate the problem and makes it abundantly clear that Go is basically
broken if you don't have ipv6 routing on your network.  I've lost, quite
literally, DAYS of time to waiting for init to complete while actively
developing a full AWS infrastructure from scratch over the course of the
last 3 weeks. Days which could have been preserved with little more than a
log statement which would have allowed me to either enable ipv6 or figure
out how to disable it in Go globally.

It'd be really nice if any patch was backported to 0.10 releases, since
0.11 has its own totally backwards-incompatible change that isn't
compatible with, really, ANY of the terraform code that is out there today,
including all of the code I've already written and the library of modules
I've pulled in from elsewhere.

**Comment by jbardin** [comment]
@sgendler-stem,

If your host has an ipv6 configured interface, then dual stack capable applications will try to connect to ipv6 first by default. If the ipv6 path is not working, then there are going to be delays connecting to any host that returns an AAAA record. This is one of the reasons [RFC-6555](https://tools.ietf.org/html/rfc6555) was drafted and implemented by many browsers and other utilities, `curl` included. 

Backporting changes to previous major releases isn't something we normally support in Terraform OSS. As for Go's decision to not enable the workaround in the default http Dialer until recently, that's a separate matter of opinion.

If your host has a globally scoped ipv6 address, but the router isn't configured for ipv6, then we can be fairly certain that this is the root cause of the issue. Another cause could be that AAAA dns queries are being dropped by a network device, but that's much less common than it used to be. If your host and network ipv6 configuration turns out to not be the underlying cause, we can continue discussion in the open issue #16804.

**Comment by omarabid** [comment]
Not sure why this is a closed issue. I'm having the same problem with OSX Catalina (10.15) and Terraform 0.12.11; except it doesn't even finish the download.

I think there should be better UI feedback for the downloading. It's not clear at which stage the installer is, maybe have something like a progress bar?

I ended up downloading from releases.hashicorp.com.
