### ISSUE TITLE
Terraform ignores symlinked provider bins

### ISSUE THREAD

**Issue by lblackstone** [hashicorp/terraform#15790]
### Terraform Version
Terraform v0.10.0

### Expected Behavior
From the [official docs](https://www.terraform.io/docs/plugins/provider.html#provider-plugin-codebases):
> This terraform executable will find and use the template provider plugin alongside it in the bin directory in preference to downloading and installing an official release.

The following symlinks are located in `/usr/local/bin`:
```
terraform@ -> ../Cellar/terraform/0.10.0/bin/terraform
terraform-provider-openstack@ -> <GOPATH>/bin/terraform-provider-openstack
```

Terraform should have used the provided `terraform-provider-openstack` binary rather than downloading a release.

### Actual Behavior
Terraform ignored the provider symlink and installed the default release:
```
Initializing provider plugins...
- Downloading plugin for provider "openstack"...
```

### Steps to Reproduce
1. `brew install terraform`
2. `go install github.com/terraform-providers/terraform-provider-openstack`
3. `ln -sf <GOPATH>/bin/terraform-provider-openstack /usr/local/bin`
4. Run a plan requiring the openstack provider

**Comment by nbering** [comment]
There's a great explanation of the plugin search order in [this comment](https://github.com/hashicorp/terraform/issues/15705#issuecomment-320809212) by @apparentlymart.

I think the simplest way to solve this would be with a `~/.terraformrc` file. Maybe something like this:

```hcl
providers {
  openstack = "<GOPATH>/bin/terraform-provider-openstack"
}
```

**Comment by lblackstone** [comment]
Thanks for the link @nbering 

From that comment:
> In the absense of a .terraformrc path override, Terraform then looks for locally-installed plugins in the following locations:
...
The directory where the terraform executable is installed.

I would expect the symlinks to work here, so I think the related implementation is bugged.
```
$ which terraform
/usr/local/bin/terraform

$ which terraform-provider-openstack
/usr/local/bin/terraform-provider-openstack
```

**Comment by nbering** [comment]
I suppose it's possible that terraform is following the symlink and checking `/usr/local/Cellar/terraform/0.10.0/bin/` for the plugin. I haven't checked to be certain, though.

**Comment by apparentlymart** [comment]
That does sound plausible, @nbering.

Terraform is asking the OS for the path to the running executable, and then deriving its search directory from that. On OS X we use the `sysctl` syscall to do this, with `KERN_PROC_PATHNAME`. The docs are unclear as to whether this returns the original or resolved path, but given that we're asking the kernel here it seems pretty likely that it's the resolved path it's using.

Since homebrew wants to create a separate bin dir for each package, in this situation I'd suggest using one of the other search paths instead. For example, in your home directory you can create `~/.terraform.d/plugins` and place the symlinks in there instead. Terraform will search this other directory regardless of the location of the Terraform binary.

**Comment by lblackstone** [comment]
Thanks @apparentlymart, that did the trick. My current working configuration looks like this:

```
$ ls -alh ~/.terraform.d/plugins/
...
terraform-provider-openstack@ -> /Users/<user>/workspace/go/bin/terraform-provider-openstack

$ ls -alh /usr/local/bin/
...
terraform@ -> ../Cellar/terraform/0.10.0/bin/terraform
```

**Comment by apparentlymart** [comment]
Great @lblackstone, thanks!

Part of me wants to find somewhere to document this but since we don't have a great obvious place for it I'm inclined to leave this for now and see if this becomes a "frequently asked question"; it seems like you've primarily hit it because you're building your own providers from source, which most users don't do. We'll keep an eye out for others hitting the same problem and re-evaluate if it seems common.

Thanks for reporting this @lblackstone, and thanks @nbering for digging in to help debug this!

**Comment by jbardin** [comment]
Hi,

The package Terraform uses to resolve the location of the `terraform` always tries to resolve the binary being executed, rather than any intermediary symbolic links. Therefor the plugin discovery in this case is looking in `/usr/local/Cellar/terraform/0.10.0/bin/`. 

I would avoid using the legacy `providers` section in the `.terraformrc` file, as that can't allow for versioned plugins. The primary recommended locations for pre-installed plugins right now are the `terraform.d/plugins/OS_ARCH` directory located with the configuration, or a directory provided by the `-plugin-dir` flag.

Due to an oversight, the global location `~/.terraform.d/plugins/OS_ARCH` is currently skipped, but that is fixed and will be in the next release.

**Comment by jbardin** [comment]
(and my browser window hadn't updated, so ignore anything that @apparentlymart already covered ;) )
