### ISSUE TITLE
Multiple list definitions merge, documentation says they overwrite

### ISSUE THREAD

**Issue by Zordrak** [hashicorp/terraform#15843]
terraform 0.9.11

The documentation says:
```
Variable Merging

When variables are conflicting, map values are merged and all other values are overridden. Map values are always merged.
```

But having defined a list twice accidentally in tfvars, the result was a list with all the values present twice. The first definition of the list was concatenated with the second. The documentation says the second should overwrite the first.

**Comment by apparentlymart** [comment]
Hi @Zordrak. Sorry for the confusing and inconsistent behavior, and for the slow response.

In v0.12 the behavior has been simplified so that variables of all types will now override. Therefore the behavior matches what used to be documented for everything except maps, and the behavior for maps has changed to match.

This fix is already in `master` along with a documentation update that no longer mentions the special map merging behavior. Both the new behavior and the docs will be released as part of the v0.12.0 release, and are already included in the special alpha1 build.

Because this is already addressed, I'm going to close this out. Thanks for reporting this, and sorry again for taking so long to respond.
