### ISSUE TITLE
DCOS tasking hour on still creating master (digitalocean)

### ISSUE THREAD

**Issue by ntk860** [hashicorp/terraform#15847]
I am trying to create my DC/OS cluster on digitalocean, when I do terraform apply, it creates the master (I can see the machine on digitalocen) but it is taking hours on this step

digitalocean_droplet.dcos_master: Still creating... (1h11m30s elapsed)

can someone help me please

**Comment by nbering** [comment]
@ntk860 I'm not familiar with the Digital Ocean provider, but with other providers, if the resource appears to have created without error and it Terraform isn't reporting complete for so long, I would probably interrupt terraform (Ctrl+C) and try again. This could cause further complications, but I would guess something has gone wrong either in Terraform or the Digital Ocean API.

Before interrupting though, I'd do some manually checking to be sure the droplet was actually started and finished provisioning. I've seen Virtual machines on other platforms appear, but not finish provisioning for 45+ minutes if there is some slowness on the provider's systems.

If you stop it, and try to run again and it still takes forever, or you have some other problem, please come back with the version of Terraform you're using, and your configuration (with secrets removed), so that someone with more knowledge of the Digital Ocean provider could more easily help you.

**Comment by ntk860** [comment]
Thank you for responding. I've stopped and tried again more than once. 

Terraform version : v0.10.2

terraform.tfvars

digitalocean_token = ""

region = "NYC1"

master_size = "4GB"

agent_size = "4GB"

boot_size = "4GB"

dcos_cluster_name = "xxxxx-dcos"

dcos_master_count = "1"

dcos_agent_count = "4"

dcos_public_agent_count = "1"

dcos_installer_url = "https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh"

dcos_ssh_key_path = "./do-key"

dcos_ssh_public_key_path = "./do-key.pub"

ssh_key_fingerprint = ""

please if someone can help, I will be very thankful, because digitalocean is the only provider that offer the prices that fit on my company's budget.

**Comment by nbering** [comment]
v0.10.0 introduced separate repositories for each plugin, rather than rolling everything into core as was the case for some time. You might also consider filing an issue at [terraform-providers/terraform-provider-digitalocean](https://github.com/terraform-providers/terraform-provider-digitalocean), where the digital ocean provider lives now. You could also try asking on the [hashicorp-terraform/Lobby](https://gitter.im/hashicorp-terraform/Lobby) on Gitter.

You could also try [Stack Overflow](https://stackoverflow.com/questions/tagged/terraform), or [DevOps Stackexchange](https://devops.stackexchange.com/questions/tagged/terraform) to see if anyone else has encountered your issue. Cross-posting the this issue URL would help both sides.

You'll want to include the contents of your .tf or .tf.json file with requests. .tfvars doesn't tell us a lot.

**Comment by jbardin** [comment]
Hi @ntk860,

Sorry you're having an issue with this. It's possible this is a bug in the DO provider, in which case it's probably more useful to file a new issue there with the necessary config and logs. Otherwise the other community resources @nbering listed may provide you with assistance, as it's possible other Digital Ocean users have encountered similar issues.

**Comment by viswanath608** [comment]
I'm also having the same issue. I've ran the script and waited for 36 hours and still it's showing me as "Creating Droplets....". I'm using MacOS Sierra.
Video/Gif - http://recordit.co/u5tfT7E2cm
