### ISSUE TITLE
Adjust Salt Masterless arguments to make it more configurable

### ISSUE THREAD

**Issue by benosman** [hashicorp/terraform#15870]
I'm evaluating the new Salt Masterless provisioner, and although I've run into an issue using it in #15867, I've also got a suggestion / feature request for it.

It was mentioned in the pull request for the provisioner (https://github.com/hashicorp/terraform/pull/14720) that it was mostly carried over from packer, but since packer works on a more general basis, I feel there are some areas for improvement

There are two arguments that may need to be configured on a per node basis:

* minion_config (string) - The path to your local minion config file. This will be uploaded to the /etc/salt on the remote. This option overrides the remote_state_tree or remote_pillar_roots options.

* grains_file (string) - The path to your local grains file. This will be uploaded to /etc/salt/grains on the remote.

Currently they only upload files from the local machine to the remote machine. To me it would be very useful to allow upload of the file contents - so I could create my own custom grain file / config dynamically using template_file and upload it directly rather than having to create a local file first.

I'm not sure if it's best to add new arguments for the file content, or change the current arguments to do that, and require using file() if people want the current behaviour.

[Salt Masterless provisioner docs](
https://github.com/hashicorp/terraform/blob/08670763aa9b3f0a22ebf73f859f3b73a36351e2/website/docs/provisioners/salt-masterless.html.md)

**Comment by benosman** [comment]
On further examination, despite the above docs referring to the parameter `grains_file`, it doesn't seem to exist in the provisioner or the test.

**Comment by apparentlymart** [comment]
Thanks for pointing this out, @benosman!

Terraform's usual pattern is to expect the contents of a file to be provided directly as a string and use `file()` when they need to actually be loaded from disk, for the reasons you state. I think as you assumed this is the way it is because of inheriting the style of the packer provisioner, where different conventions apply.

Since we've now shipped with these file-specific arguments we would normally not want to change them in-place to avoid breaking compatibility. We _might_ be able to make an exception here if it turns out that #15867 was making the provisioner essentially impossible to use anyway, since by that token there will be no working uses to break! But we'll need to confirm that first.

Since the name `grains_file` has a `_file` suffix this would _suggest_ that it takes a filename, so we should definitely either rename this to `grains_file_content` or support both (depending on the compatibility constraint) to make it clear that it doesn't take a filename directly.

`minion_config` already has the "right" name for it to take the full config (should ideally have been `minion_config_file` to take a filename) so in the event that we're able to break compatibility here I think we should change it in-place to accept the content directly, but we may have to make a compromise if it turns out that we need to maintain compatibility in this case.

We have some mechanisms for handling a deprecation cycle on a change like this (from a filename to raw content) for when we did some similar changes in other providers, so if we _do_ need to preserve compatibility we should be able to make `minion_config` take either a filename or file contents for a deprecation period, as long as a naked filename is never a valid value for the minion config contents.

**Comment by benosman** [comment]
@apparentlymart 

I agree with what you've said above, and the need not to break things for others. 

You are probably aware, but one thing to note is this provisioner hasn't yet appeared in a release yet - it was merged just after 0.10.2 and docs are not live on the site yet.

As I've been working through my salt config - I've also been wondering about the merits of being able to upload custom pillar data per node as well.  The current parameter is ```local_pillar_roots``` which of course indicates that multiple files are uploaded.

Ideally I'd like an additional argument like ```pillar_content``` to upload a single file contents to the pillar directory e.g. `/srv/pillar/top.sls` that could be templated. I realise this idea may need further thought / discussion, if my go skills were not so rudimentary, I'd have a go at a pull request myself for that part.

**Comment by apparentlymart** [comment]
Oh @benosman actually I _hadn't_ noticed that it wasn't already in the 0.10.2 release; the merge date fooled me, and it looks like we'd forgotten to log it in the changelog. Thanks for pointing that out! I've updated the changelog now.

Since it's not been in a release yet we have the freedom to make any changes to it before the release, since we don't promise backward compatibility with code that wasn't included in a commit. We're not planning a release this week, so we've got some time to make some changes here. Unfortunately I'm not sure I will have time this week to actually work on these changes, though I'd be happy to review a PR if someone else has the time and motivation to work on it.

I'm also interested as to whether @sevagh, who authored this provisioner, has any thoughts on the proposal here. I don't really know Salt at all, to be honest, so I'm interested to here from both of you (presumably Salt users!) on what feels best here, since I can only weigh in on the design principles we generally apply across all resources/provisioners.

**Comment by sevagh** [comment]
@benosman @apparentlymart I think I understand the confusion here.

When I copy/pasted the provisioner __code__ from Packer, `grains_file` was not yet added (https://github.com/hashicorp/packer/commit/912fc9c2af5b5e7b587322e1dc5556641ee21cab). However, I did a git pull before copying the doc, so the doc contains `grains_file`.

**Comment by apparentlymart** [comment]
Hi again!

I just wanted to drop a note here that unfortunately due to other unexpected stuff coming up we weren't able to get to this in time for the 0.10.3 release and so I instead made a smaller change to rename `minion_config` to `minion_config_file`. The intent here is to allow the change proposed by this issue at a later date without backward compatibility.

For the near future the Terraform team at HashiCorp is going to be focused elsewhere and so likely won't have time to work on this for a little while. If someone else has the time and motivation to work on it in the mean time then we'd love to review a PR.

**Comment by sevagh** [comment]
I'm working on a PR for adding `grains_file` to the Terraform provisioner. Once that's done, I will see about doing the templatized thingy.

**Comment by sevagh** [comment]
https://github.com/hashicorp/terraform/pull/15989

**Comment by sevagh** [comment]
After #15989 is merged I'll work on the templated file.

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested.

For the time being, the best option if you want to see this built, is to build a standalone provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. 

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
