### ISSUE TITLE
Document $TF_WORKSPACE

### ISSUE THREAD

**Issue by Vinnl** [hashicorp/terraform#15874]
### Terraform Version
0.10.2

### Expected Behavior
Since TerraForm 0.10 renamed `env` to `workspace`, I manually guessed the the environment variable `$TF_ENV` was now named `$TF_WORKSPACE`. I'd expected this to be documented and to work the same.

### Actual Behavior
There is no mention of `$TF_WORKSPACE` on either the [Workspaces](https://www.terraform.io/docs/state/workspaces.html) or the [Environment Variables](https://www.terraform.io/docs/configuration/environment-variables.html) documentation.

It also seems to work slightly different. Before, I'd set `$TF_ENV` (not sure if that was even an official thing), and then either create or select it using

    terraform env select $TF_ENV || terraform env new $TF_ENV

However, replacing `env` with `workspace` and `$TF_ENV` with `$TF_WORKSPACE` brings up the following message:

> The selected workspace is currently overridden using the TF_WORKSPACE
environment variable.
> 
> To select a new workspace, either update this environment variable or unset
it and then run this command again.

Now I'm not sure whether I can simply leave out the `workspace select || workspace new` commands, since I can't find what `$TF_WORKSPACE` is supposed to do.

### Steps to Reproduce
1. `export TF_WORKSPACE="arbitrary_workspace"`
1. `terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE`

### Important Factoids
This is in GitLab CI (i.e. Docker).

**Comment by apparentlymart** [comment]
Hi @Vinnl! Sorry for the confusion here.

This environment variable was added at the same time as the terminology shifted, so it seems like before you were using `TF_ENV` for your own purposes and by coincidence after renaming it is now conflicting with a variable Terraform itself respects.

This environment variable is intended only for use in automation, so currently it's documented only as part of [the guide to running Terraform in automation](https://www.terraform.io/guides/running-terraform-in-automation.html).

However, I can see that it'd be useful to have a central page on the site that sums up all of the environment variables Terraform respects across all of its functionality, since it can be confusing when you accidentally stumble across one and, as you say, can't figure out what it's actually doing.

Until we _do_ get the docs updated, to answer your specific question: when the variable is set, it bypasses the usual stateful means of selecting a workspace via `terraform workspace select`, so as long as the named workspace actually already exists you don't need to run any explicit selection commands. However, if you're creating a new workspace that still needs to be done explicitly using `terraform workspace new`.

**Comment by Vinnl** [comment]
Haha OK, I guess it would've made sense for me to consider `$TF_` as a "reserved" namespace for TerraForm - lesson learned. And I guess `$TF_WORKSPACE` is actually documented, just not at the place I was looking for, which makes sense, as you usually don't just "run into" the environment variables.

Thanks for the explanation, anyway. I guess I'll keep using my existing `||` script then, as I'm automatically creating new workspaces based on the branch CI is running at. Might be an interesting use case in itself, but I guess that'd be a new Issue.

Thanks again for the explanation.

**Comment by tomdavidson** [comment]
TF_INPUT is meant for automaiton and is describe at https://www.terraform.io/docs/configuration/environment-variables.html ... TF_WORKSPACE would probably feel at home

What would it take for TF_WORKSPACE to create if it does not exist already?

**Comment by lkysow** [comment]
It appears in my testing that setting `TF_WORKSPACE` to a new workspace **does** create the workspace if it doesn't already exist. I've tested this with the s3 and local backends.

**Comment by apparentlymart** [comment]
Hi @lkysow!

Unfortunately that is a backend-specific implementation coincidence rather than an intended feature: I expect it happens because these backends implement both "create" and "update" as a "put" action, and so if you bypass Terraform's existence check (which happens in `terraform workspace select`) then the new workspace is "created" just as a side-effect of writing its new state, not as an explicit action.

At the moment the intent is that workspace creation is an explicit action since it's often undesirable that e.g. a typo would lead to implicitly creating a new workspace. However, we can think about ways to make a more "implicit" workspace creation possible, such as opting into that with an explicit option in other commands. For now, we don't have any plans to enforce the existence check in more places so you can continue to rely on the implicit behavior of some of the backends for the foreseeable future.

**Comment by lkysow** [comment]
Okay good to know! I won't rely on that behaviour then. Thanks for the quick reply!
