### ISSUE TITLE
problem with 'terraform get/init': x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by orelhinhas** [hashicorp/terraform#15892]
I try to get my modules from my private Git, but I haven´t a certificate signed. Exists some way to bypass this ssl check?

### Terraform Version
Terraform v0.10.2

### Terraform Configuration Files
```hcl
module "keypair_one" {
  source     = "https://git.myinternal.corp/terraform/aws_modules/key_pair"
  key_name   = "keypair_one"
  public_key = "ssh-rsa AAAAB..."
}
```

### Debug Output
$ terraform init
Downloading modules...
Get: https://git.myinternal.corp/aws_modules/key_pair
Error downloading modules: Error loading modules: error downloading 'https://git.myinternal.corp/terraform/aws_modules/key_pair': Get https://git.myinternal.corp/terraform/aws_modules/key_pair?terraform-get=1: x509: certificate signed by unknown authority

### Expected Behavior
Download the modules from my private git

### Actual Behavior
An error because I don´t have a signed certificate in my git

### Steps to Reproduce
1. Configure your SCM with https and self signed certificate
2. try to get modules from there

**Comment by apparentlymart** [comment]
Hi @orelhinhas! Sorry for the inconvenience here.

One thing I notice here is that the source you've written is not actually telling Terraform to use git here. Since your URL starts with `https:`, Terraform is treating it as a URL for an archive file hosted on your server. To tell Terraform that this is a Git server using https, you need the extra `git::` prefix:

```hcl
module "keypair_one" {
  source     = "git::https://git.myinternal.corp/terraform/aws_modules/key_pair"
  key_name   = "keypair_one"
  public_key = "ssh-rsa AAAAB..."
}
```

With this `git::` prefix, it will actually be the `git` command that talks to your server rather than Terraform itself, and so if you already have `git` working when you run it directly it should _also_ work when Terraform runs it.

If that isn't true, there are some other options:
* Both Terraform and Git should respect your system's trusted certificate store, so you could add the CA certificate used on your Git server as a trusted certificate and then this should make it work for various tools, including `curl`.
* If your private git server supports it, you could instead use SSH for access to the git server. SSH doesn't use TLS, so TLS certificate issues will not apply, though you would need to use an SSH key for authentication in that case.

**Comment by orelhinhas** [comment]
Great @apparentlymart , I tried now with git::ssh:// and work fine!! 
Thanks for your help ;D
