### ISSUE TITLE
Variable Interpolation for Provider Version

### ISSUE THREAD

**Issue by veetow** [hashicorp/terraform#15896]
### Terraform Version
0.10.2

### Terraform Configuration Files
```hcl
variable "region" {
  default = "us-east-1"
}

variable "provider_aws_version_constraint" {
  default = "~> 0.1"
}

provider "aws" {
  version = "${var.provider_aws_version_constraint}"
  region  = "${var.region}"
}
```

### Expected Behavior
The correct version of the provider should be downloaded and installed.

### Actual Behavior
```hcl
$ terraform init
Error getting plugins: module root: 1 error(s) occurred:

* provider.aws: invalid version constraint "${var.provider_aws_version_constraint}": Malformed constraint: ${var.provider_aws_version_constraint}
```

### Steps to Reproduce
Create a file with the above code and run `terraform init`.

**Comment by veetow** [comment]
According to the documentation, this should work.
https://www.terraform.io/docs/configuration/providers.html#interpolation

**Comment by apparentlymart** [comment]
Hi @veetow! Sorry this doesn't work.

The documentation is not entirely accurate here, since `version` is a special "meta-argument" that is handled by Terraform itself, whereas the section you referred to is talking about the provider-specific arguments. We'll get the docs updated for that.

This attribute is one of those things that can't support interpolation because it needs to be dealt with very early on in Terraform's processing, before anything else has happened.

That aside, it seems strange to parameterize the version like this since this is a statement about what version of the provider _this module_ is assuming. So I'm curious to hear more about your use-case here, since there may be a different way to address what you are trying to do here.

**Comment by veetow** [comment]
I'm not really exploring a specific use-case, but just getting familiar with the changes in 0.10.x and trying things out.  I was thinking it might one day be useful to have different `environments\workspaces` using different versions of the providers.

**Comment by apparentlymart** [comment]
Hi @veetow,

Allowing providers to vary between workspace is something we're investigating. It's a bit of a strange situation since we don't currently have a way for the _config_ to vary between workspace, and provider compatibility is a property of the config, but we are looking into whether there's a suitable usage model for this.

This discussion is currently very early, so I don't have any concrete details to share, but it's feeling like such a thing would probably come as part of a more holistic integration between Terraform and version control so that we can solve for the general problem of "try this change in our staging environment first", whether that change is a new provider version, different child modules, or different root module config.

**Comment by cunymatthieu** [comment]
Hi @apparentlymart ,

I have a use case, if I want to force version of provider (stability issues,...). It would be good to have this posibility.

```tcl
variable "region" {
  default = "us-east-1"
}

variable "provider_aws_version_constraint" {
  default = "= 1.0.0"
}

provider "aws" {
  version = "${var.provider_aws_version_constraint}"
  region  = "${var.region}"
}
```

**Comment by apparentlymart** [comment]
Via a separate issue we ended up creating #15613 to explore this idea more. Sorry I neglected to add a link to it here before.

This issue is representing the need to update the docs to say that the `version` argument doesn't currently support interpolation, though indeed it did fall off the radar so I'm going to just do that now so we can consolidate the ongoing discussion in #15613.

**Comment by apparentlymart** [comment]
Oh sorry, I was confused for a moment... you're talking about providers, rather than modules. Please disregard my previous comment!

**Comment by kpkrishnamoorthy** [comment]
The (merged) PR 16212 appears to have text in it that still does not exist on the website documentation here: https://www.terraform.io/docs/configuration/providers.html
