### ISSUE TITLE
Allow the use of lookup() on var.

### ISSUE THREAD

**Issue by joestump** [hashicorp/terraform#15908]
TF doesn't support maps of maps nor does it allow you to mix types in map values. Perhaps a happy medium on adding more complicated type support would be to allow dynamically looking up `var` by name with an HCL function. Maybe via `lookup`? Or perhaps `var("var.name to look up")`? 

```hcl
variable "subnets_us-west-1" {
  default = {
    a = "1"
    b = "2"
    c = "2"
  }
}

variable "region" {
  default = "us-west-1"
}

data "template_file" "test" {
  template = "${join(", ", numbers)}"

  vars {
    numbers = "${lookup(var, "subnets_${region}")}"
  }
}
```

**Comment by teamterraform** [comment]
Hi @joestump,

Terraform 0.12 now has a new "object" type kind, which is a map-like type that tracks a separate type for each of its attributes. While maps themselves still have only a single element type common to all elements (which is what allows Terraform to track the element type even when the exact set of elements isn't known yet during planning), you can use an object type to create a mixed structure:

```hcl
variable "example" {
  type = object({
    region = string
    subnets = map(string),
  })
  default = {
    region = "us-west-1"
    subnets = {
      a = "1"
      b = "2"
      c = "2"
    }
  }
}
```

Terraform 0.12 also supports maps of maps, as well as (as we can see above) object types with map attributes inside.

Terraform cannot support dynamic selection of variables or any other first-class object because it uses the references in configuration to derive the dependency graph. Supporting something like `var[var.anything]` would create situations where Terraform could not know which variable will be selected until after evaluation begins, and thus it would have to make a very conservative dependency graph where the resource depends on _all_ variables. That sort of over-conservative graph is very likely to cause dependency cycles, which would then cause an error that would likely be difficult to debug.
