### ISSUE TITLE
Count value

### ISSUE THREAD

**Issue by jfgibbins** [hashicorp/terraform#15902]
How do I return the value of 'count' within a resource?  Not looking for count.index.  Example:

resource "lxd_container" "test" {
  count    = 5
  name     = "${count > 1 ? format("test%02d", count.index) : "test"}"

**Comment by Remigius2011** [comment]
@jfgibbins In my setup I inject count as a variable, which avoids this problem. Also I use modules (which unfortunately don't support count - therefore I pass the count into them).

**Comment by jfgibbins** [comment]
@Remigius2011 I was afraid of that.  There's a couple resources I'd like to pull, like count and name, but doesn't seem to be capable of doing that outside the provisioners.  I was hoping to utilize count, but between user-data, network-config, and such, seems to much work to attempt to abstract in terraform with variables and templates, what can easily be done with php.  Think I'll just stick with how I do it currently and expand the php code to handle count.

**Comment by apparentlymart** [comment]
Hi @jfgibbins! Sorry we missed this issue before.

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people ready to help. The GitHub issues here are generally monitored only by our few core maintainers, and indeed this issue is a good example of the consequences of that: sometimes questions get lost in the sea of other requests.

You asked this question a long time ago so I expect this exact question is not relevant anymore, but again I'm sorry we didn't see and respond to it at the time.

**Comment by jfgibbins** [comment]
It wasn't a question appropriate for the forum, but rather, yet another flaw in the program to be resolved by the programmers.  But don't worry about missing it from two years ago.  This, along with so many other issues that still haven't been solved in three years, I've long since moved onto products that work.

**Comment by Remigius2011** [comment]
@jfgibbins with which product have you replaced terraform if I may ask?
