### ISSUE TITLE
* stat : no such file or directory error when file is empty

### ISSUE THREAD

**Issue by evgeniagusakova** [hashicorp/terraform#15932]
Hi Team!

I faced with error 
`* stat : no such file or directory `
when  empty file was provided as source file  to be  uploaded to AWS instance.

### Terraform Version
```
$ terraform version
Terraform v0.10.2
```
```
$ uname  -mprsv
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64 i386
```
### Issue explanation
Terraform failed during AWS instance creation when chef server key was replaced with empty file 
(it is not usual use case, just human mistake but anyway it should not failed  instance creation)

Code snippet:
```
resource "aws_instance" "instance" {
    connection {
        type        = "ssh"
        user        = "${var.instance_user}"
        host        = "${aws_instance.instance.public_ip}"
        private_key = "${file("${var.ssh_key_path}")}"
    }

<SKIPPED>
    provisioner "file" {
        content     = "${var.chef_key}"
        destination = "/tmp/client.pem"
    }

 <SKIPPED>
```
When file "${var.chef_key}" is empty instance creation fails with error:
```
* stat : no such file or directory
```
### Workaround:
`echo "some-data-i-do-not-need" > /path/to/source/file`

### Expected Behavior
Instance is created with empty file

### Actual Behavior
Instance creation failed with error:
```
* stat : no such file or directory
```

### References
Looks like very close to this issue: 
https://github.com/hashicorp/terraform/issues/10531

**Comment by exarkun** [comment]
It would be great if this error message could just be changed to:

```
* stat "": no such file or directory
```

And *super* great if the error message could refer to the resource and provisioner involved (perhaps by line number since provisioners don't have names).

**Comment by brikis98** [comment]
I hit the `stat: no such file or directory` error while writing some automated tests. I had some code that was calling `terraform apply` and accidentally passing a blank space as an extra argument. So the command was roughly becoming `terraform apply " "`. I think Terraform was treating this as the path where it was supposed to run, and as there was no folder named space (`" "`), it just reported a very unhelpful `state: no such file or directory` error. 

It took a looooong time to find such a simple error, so a big +1 on making that error message clearer!

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
