### ISSUE TITLE
Proposal: Environment Variables Lookups

### ISSUE THREAD

**Issue by nocode99** [hashicorp/terraform#15967]
With the more recent versions of terraform allowing a remote state configuration via a file, a major hurdle I can see for  users is  not being able to use interpolation inside the `terraform` block.  I understand the design decision to do this, but I was wondering if it was possible for terraform to do environment variable lookups but by not using `TF_VAR_` prepended to the environment variable? The idea behind this is it would not require the variable to be declared in the .tf files either.

**Example**:
```
terraform {
    backend "s3" {
         bucket      = "${lookup.MYBUCKET}"
         key         = "${lookup.ENVIRONMENT}/terraform.tfstate"
         kms_key_id  = "${lookup.KMSKEYID}"
         region      = "us-east-1"
    }
}

$ ENVIRONMENT=prod MYBUCKET=s3-bucket KMSKEYID=arn:aws:kms:us-east-1:1234567890:key/some-key-id terraform apply
```

I know we would use a `workspace` to differentiate the environment, but our environments are not so cut/dry with our applications.  Often times our environments are not repeatable (ie vpc peering) and if our resource is already using `count` there would be no way to have a conditional creation of a resource.

We use Makefiles to perform our terraform changes and I inject the application environments and sometimes build-versions as variables into the plan/apply.  I can't see our stack using workspaces to differentiate environments so we will continue to inject the environment (there's a separate issue of trying to import an existing state into a workspace too).  As in the example above, the key contains an environment "directory" for our s3 remote state.  We had the environment injected automatically based on the path of the terraform config and it eliminated any manual intervention.  This also greatly reduces accidental applies across different environments.

I realize you can't please everyone, but I'd at least like to try :)

If there's no traction for this, my resort would be to have a dynamically generated terraform provider block via script/Makefile.

**Comment by mildwonkey** [comment]
While we don't support directly referencing environment variables, we do support [`TF_VAR_{variable_name}=foo` environment variables](https://www.terraform.io/docs/commands/environment-variables.html#tf_var_name) as a way to set values for variables in the root module.

Based on that, and the fact that we don't intend to allow general access to environment variables, I am going to close this issue (note that this issue was specifically about environment variable lookups - the general request for variables in provider configuration is still an open issue).

Thanks!
