### ISSUE TITLE
New Provider: JumpCloud

### ISSUE THREAD

**Issue by voltechs** [hashicorp/terraform#16049]
Please consider supporting [JumpCloud](http://jumpcloud.com)!

Primarily, user provisioning. It would be excellent to centralize all user management!

Update:
Third-party [JumpCloud provider](https://github.com/geekmuse/terraform-provider-jumpcloud)! [Thanks](https://github.com/hashicorp/terraform/issues/16049#issuecomment-387437776) @clebio! 🎉

**Comment by apparentlymart** [comment]
Hi @voltechs! Thanks for this feature request.

While I agree it would be great to support this service in Terraform, at this time the Terraform team at HashiCorp is not planning to take on development of new in-house-maintained providers since the existing set is already keeping us pretty busy.

As we scale the development process, we've been moving towards a model where providers can be maintained in partnership between the Terraform team at HashiCorp and third-party contributors -- often representatives of the vendor in question. There are more details on this in [the guide on the Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html).

So with that said, although we are unlikely to develop such a provider ourselves in-house, we would be happy to work with either representatives of JumpCloud itself or with community contributors who are willing and able to take on development and ongoing maintenance of such a provider. The Provider Development Program guide includes some information on how to reach out.

In the mean time, we usually like to begin provider design/development by gathering use-cases, so if you have (or anyone else has) ideas for one or two JumpCloud concepts that would be good starting points for a Terraform provider -- that is, the first few things that could be implemented that would address some common use-cases -- it'd be great to gather them in this issue both to gauge interest and to inform priorities should someone wish to work on this provider.

**Comment by clebio** [comment]
https://github.com/geekmuse/terraform-provider-jumpcloud

**Comment by pkolyvas** [comment]
Hi folks! As Terraform Open Source is now separate from Providers, I'm working on cleaning up our issue list by closing down open issues that no longer pertain directly to this repository.

Thanks for your ongoing contributions to our project.
