### ISSUE TITLE
Moving the DAG package to a separate repository

### ISSUE THREAD

**Issue by advanderveer** [hashicorp/terraform#16048]
Hey fellow terraform lovers!

The DAG package in terraform is easily one of the best and well tested graph libraries in the Go ecosystem. It is also has a well defined API and a clear responsibility, the data structure itself is of course very versatile and can be used for numerous other projects. Would Hashicorp consider hosting this package in a separate repository. Similar to:

- github.com/mitchellh/cli
- github.com/armon/go-radix
- github.com/hashicorp/memberlist

It would make reusing it a lot easier by not needing to download the whole Terraform code base to use it. I do understand that it is a very fundamental part of Terraform, but hopefully there is some way to make this possible!

Kind Regards,

Ad van der Veer

**Comment by apparentlymart** [comment]
Hi @advanderveer,

I'm glad to hear you find this package useful!

Currently we'd rather keep it all together in one repository, since it makes it easier for us to track, and easier to make changes that affect multiple packages at once. This might change later as Terraform's internal architecture grows more stable. This particular package hasn't changed much recently, but we are planning to make some bigger architectural changes over the next few major releases that may or may not affect this package.

If you'd like to it, it would be fine if you'd like to fork the library into a separate repository yourself and use it from there. Although we don't have any specific plans to change the API or capabilities of this package. that would also insulate you against hypothetical future changes to the package, which are possible because at this time we're not considering it to have a stable API for external callers.

Sorry about that! I hope this doesn't cause you too much trouble. :disappointed:

**Comment by advanderveer** [comment]
Hi @apparentlymart, I find it actually good to hear that you guys are looking ahead! So thank for the response, i'll look into setting up a fork and link it in this thread.
