### ISSUE TITLE
tf state mv  and tf_remote_state causes 'forces new resource' during plan from old configuration.

### ISSUE THREAD

**Issue by zirpu** [hashicorp/terraform#16056]
We're having an issue trying to migrate a large single statefile configuration with modules in subdirectories.

I've created a demo at:  https://github.com/zirpu/tf.state.mv.example

The issue is when we move the ./vpc module to a top level repo, then replace it with just
an outputs.tf file that uses terraform_remote_state references, it still wants to recreate
the test_host ec2 instance claiming that the subnet in that vpc "forces new resource", even though
it hasn't changed.

I could not find a bug/issue about this, so opening this.  Any pointers to issues or docs appreciated.

-allan

**Comment by jbardin** [comment]
Hi @zirpu,

Thanks for the work of creating a full example config and steps. While I have seen this issue before, I'll keep this one open since I can reproduce it this time 👍 

The key part here is that the interpolated `subnet_id` is not only not being resolved, but is also not showing up as `<computed>` and the interpolation string is getting passed through:

    subnet_id:                    "subnet-06768561" => "${var.vpc_subnet_id}"

Also of note, is that `apply` works correctly, and a subsequent `plan` show the same bug. This means we can get the correct value, but the plan graph is doing something slightly different.

**Comment by zirpu** [comment]
I've updated the example repo with a workaround we found.  Basically not using the ./vpc/ module outputs, and instead directly using the terraform_remote_state references.

So apparently using the outputs from the module was the issue.  Double dereference bug maybe?

**Comment by jbardin** [comment]
Yes, still trying to track down the root cause, but that is essentially the way around it. 
The problem appears to stem from a remote state within one module being passed to another.

**Comment by jbardin** [comment]
@zirpu,

OK, this one was embarrassingly simple, yet took so long to trace. 

The issue is the `remote_state` config, specifically the path is `../../vpc/terraform.tfstate`, but a provider has no notion of the module it's being called from, so the path being loaded is relative to the `test1` directory. 

A workaround in _some_ cases would be to use the module path in the config: `${path.module}/../../vpc/terraform.tfstate`. This however only works if the remote state file is inside another module! Because modules are actually run from a (usually symlinked) path within `.terraform/` that relative path doesn't resolve correctly. So in your case, because the remote state doesn't reside within any module, you will need to provide an absolute path to the file, or a path relative to the working directory.

Another part of the problem here was that for various reasons in the code, outputs can't generate errors, and because the output is what is accessing the data that doesn't exist, the error is silently swallowed. 

At a minimum I think we need to document this better. 
We'll definitely think this over to see if there are other improvements that could help make the path handling more consistent.

**Comment by armenr** [comment]
I ran terraform mv on a module's namespace, and then renamed the module according to what I mv'ed it to in my main.tf. 

...so now, terraform wants to force a new resource on my entire VPC...which means all of my ec2's that go with it. This is a VPN server we're talking about. A long-lived, specifically addressed, VPN server. 

How do I even begin to back out of this?

**Comment by armenr** [comment]
When I tried to revert, by mv'ing it back to its original namespace, and resetting my main.tf file to its original state, it's fine with that, but still wants to force new resources. This is pretty concerning, as I can no longer do anything in this particular subset of my infrastructure.

Please help?

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. The documentation has changed quite a bit since this was opened, as well as terraform itself!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
