### ISSUE TITLE
Allow auth to bastion host to be a combo of public,keyboard-interactive 

### ISSUE THREAD

**Issue by dannenberg** [hashicorp/terraform#16106]
For reasons beyond our control, we have to enable multifactor authentication for ssh. We followed the instructions [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7) and did [the optional portion which allows the google_authenticator portion to pass automatically when it is not configured for a user](https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7#tip-3-—-avoiding-mfa-for-some-accounts).

From our local machines we are able to log into the bastion host using the same user and private key that terraform does. However when terraform attempts to do so we receive an error. I believe this is because terraform is not attempting to use the ssh auth method publickey,keyboard-interactive and instead only attempts publickey. Since the keyboard-interactive portion should fall through to allow the connection, I think all I'd need to get around this is a way to tell terraform to attempt to connect via publickey,keyboard-interactive, not just publickey (`Error connecting to bastion: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`). After sending the privatekey, terraform would be able to access the bastion host.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please try upgrading because your issue may have already been fixed.
0.10.4

### Terraform Configuration Files
The config isn't particularly relevant except insofar as we are using a bastion host to initial our ec2 instances and accessing it via publickey.
```resource "aws_instance" "core_api_instance" {
  count                  = "${var.instance_count}"
  ami                    = "${var.ami}"
  instance_type          = "${var.instance_type}"
  key_name               = "tpt-in-aws"
  monitoring             = true
  ebs_optimized          = true
  vpc_security_group_ids = ["${var.vpc_security_group_ids}"]
  subnet_id              = "${element(var.subnet_ids, count.index)}"

  tags {
    Name       = "${format("core-api-%03d", var.numbering_offset+count.index)}.${var.environment}.aws"
    BillingEnv = "${title(var.environment)}"
    Terraform  = "true"
  }

  root_block_device {
    volume_type           = "${var.root_block_device_type}"
    volume_size           = "${var.root_block_device_size}"
    delete_on_termination = "${var.root_block_device_delete_on_termination}"
  }

  connection {
    type                = "ssh"
    user                = "centos"
    host                = "${self.private_ip}"
    private_key         = "${var.aws_instance_private_key}"
    agent               = false
    bastion_host        = "${var.bastion_ip}"
    bastion_private_key = "${var.aws_instance_private_key}"
  }

  provisioner "chef" {
    attributes_json = <<-EOF
          {
            "system":  {
                "short_hostname": "${format("core-api-%03d", var.numbering_offset+count.index)}"
            }
          }
          EOF

    environment     = "${var.environment}"
    run_list        = ["role[core-api]"]
    node_name       = "${format("core-api-%03d", var.numbering_offset+count.index)}.${var.environment}.aws"
    secret_key      = "${var.chef_encrypted_data_bag_secret_key}"
    server_url      = "https://api.opscode.com/organizations/<chef_org>"
    recreate_client = true
    user_name       = "${var.chef_user_name}"
    user_key        = "${var.chef_user_key}"
    version         = "${var.chef_version}"
  }
}

output "core_api_instance_id" {
  value = ["${aws_instance.core_api_instance.*.id}"]
}
```

### Debug Output
```
2017-09-15T19:11:38.584Z [DEBUG] plugin.terraform: chef-provisioner (internal) 2017/09/15 19:11:38 connecting to TCP connection for SSH
2017-09-15T19:11:38.584Z [DEBUG] plugin.terraform: chef-provisioner (internal) 2017/09/15 19:11:38 [DEBUG] Connecting to bastion: <bastion_ip>:22
2017-09-15T19:11:38.749Z [DEBUG] plugin.terraform: chef-provisioner (internal) 2017/09/15 19:11:38 connection error: Error connecting to bastion: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2017-09-15T19:11:38.749Z [DEBUG] plugin.terraform: chef-provisioner (internal) 2017/09/15 19:11:38 Retryable error: Error connecting to bastion: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

### Crash Output
It did not crash!

### Expected Behavior
What should have happened?
Terraform should have attempted to connect via the accepted publickey,keyboard-interactive AuthenticationMethod, sent its private key, and received access.

### Actual Behavior
What actually happened?
Terraform attempted only to connect via publickey, which in turn errors, so it is never able to connect to the bastion host.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. Configure a bastion host as per https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7
2. Attempt to spin up a server via this bastion host.

### Important Factoids
If I configure sshd to allow publickey only as an AuthenticationMethod, it completely disables MFA for all our other users as publickey is a strict subset of publickey,keyboard-interactive.

### References
https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7 again
and in particular https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7#tip-3-—-avoiding-mfa-for-some-accounts

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.

**Comment by danieldreier** [comment]
Oops - I closed this incorrectly
