### ISSUE TITLE
Terraform Enterprise website issue

### ISSUE THREAD

**Issue by chaim-sw** [hashicorp/terraform#16105]
sorry if this isn't the right place but does anyone know the following issue is happening?

![image](https://user-images.githubusercontent.com/24903186/30500338-b34bd81a-9a12-11e7-8099-ab11871a0857.png)

it shows all the runs as "a few seconds ago" and you can't click on any of the links. guessing it's something with the JS framework. the number of boxes shown does correspond to the number of actual runs, but I can only get to the runs by manually putting them in the URI indicator; i.e, the links are broken, not just the text.

**Comment by apparentlymart** [comment]
Hi @chaim-sw! Sorry for this issue.

The Terraform Enterprise team is aware of this issue and is working on fixing it as we speak. Thanks for reporting!

**Comment by apparentlymart** [comment]
The latest updates about this issue will be posted on [the Terraform Enterprise status page](https://status.hashicorp.com/incidents/xnj18jvmx73x). I'm going to close this just because the fix won't require changes to Terraform itself; the Enterprise team is still working on it and will share further updates when they have them.

Thanks again for reporting!

**Comment by chaim-sw** [comment]
fixed, thanks
