### ISSUE TITLE
Terraform Crashes on Specifying a Provider Version as a Variable

### ISSUE THREAD

**Issue by hylaride** [hashicorp/terraform#16125]
Hi there,

Having recently just upgraded to TF 0.10, we'd like to have a variable set the provider version so we can increment it separately for our environments, some of which call the provider multiple times.  However, TF seems to hard crash on it.  I'm expecting that this is a problem with terraform and not the provider as it's crashing before it can extrapolate any version.

### Terraform Version
0.10.5

### Terraform Configuration Files
```hcl

variable "aws_provider_version" {
  type = "string"
  default = "0.1.4"
}

provider "aws" {
  version = "${var.aws_provider_version}"
  region  = "${var.region}"
}
```

### Debug Output
https://gist.github.com/hylaride/08db7ebe845675e870f631b1fcd102ad

### Crash Output
https://gist.github.com/hylaride/87a9f3c1310f118a2516a005883ac1f7

### Expected Behavior
TF should lookup the variable and set it as the version we'd like to have for the aws provider.

### Actual Behavior
TF crashed.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform plan`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #6017

**Comment by apparentlymart** [comment]
Hi @hylaride! Sorry for this crash and thanks for reporting it.

I think this is the same as #15742, so I'm going to close this to consolidate discussion over there.

It is intentional that interpolation is not supported here, since it's not possible to change version each time a variable change (installation only happens during `init`) but indeed it should be a proper error describing the problem rather than a crash.
