### ISSUE TITLE
Add CoreDNS provider

### ISSUE THREAD

**Issue by ThinkBriK** [hashicorp/terraform#16130]
This CNCF project is getting bigger, initial work was started a few month ago in PR #15255.
Any chance to get it supported in the future ?

**Comment by apparentlymart** [comment]
Hi @ThinkBriK!

Although I can't speak to its feature-completeness, I found [a third-party CoreDNS provider](https://github.com/shelmangroup/terraform-provider-coredns) that may meet your needs here.

At this time the Terraform team at HashiCorp is not able to take on new providers for entirely-in-house maintenance/development since the existing providers are keeping us pretty busy. However, we could be open to collaborating with the authors of this plugin to bring it into the HashiCorp-distributed set if they are interested and have the resources to support it (responding to issues, reviewing PRs, etc).

**Comment by ThinkBriK** [comment]
Fine thank you for your quick response and your clear direction !

**Comment by lsjostro** [comment]
@apparentlymart we (as in shelman group) are happy to officially support the coredns provider. The process of getting a repo in terraform-provider org has been unclear. Can you please point me in the right direction on how to get that rolling?

**Comment by johnmarcou** [comment]
Look forward to use CoreDNS via Terraform ! Very useful for on-prem infrastructure. :)

**Comment by pkolyvas** [comment]
Hi folks! 

As Terraform Open Source is now separate from Providers, I'm working on cleaning up our issue list by closing down open issues that no longer pertain directly to this repository.

Regarding official provider status, if the [documentation here](https://www.terraform.io/guides/terraform-provider-development-program.html) isn't proving helpful, please reach out to me (contact info is on my GitHub profile page) and I'll follow up.

However, official provider status may not be the route you want to take. Instead, you may want to simply go the [community route](https://www.terraform.io/docs/providers/type/community-index.html). You can find the form here: https://docs.google.com/forms/d/e/1FAIpQLSeenG02tGEmz7pntIqMKlp5kY53f8AV5u88wJ_H1pJc2CmvKA/viewform#responses
