### ISSUE TITLE
support count variable for s3_bucket lifecycle transition

### ISSUE THREAD

**Issue by apremalal** [hashicorp/terraform#16179]
Hi there,

AWS Singapore Regions doesn't support GLACIER storage type for S3.. I have a multi region setup scripted using terraform. Requirement is to disable GLACIER transition if the region is Singapore. However it seems the count variable is not supported for this purpose. 

### Terraform Version
v0.10.6

### Terraform Configuration Files
```hcl
lifecycle_rule {
    id = "log"
    enabled = true

    prefix = "logs/"
    tags {
      "rule" = "log"
      "autoclean" = "true"
    }

    transition {
      days = 30
      storage_class = "STANDARD_IA"
    }

    transition {
      count = "${var.name == "sg" ? 0 : 1}"
      days = 60
      storage_class = "GLACIER"
    }
    expiration {
      days = 90
    }
  }
```

### Debug Output
` module.sg.aws_s3_bucket.regional: lifecycle_rule.0.transition.1: invalid or unknown key: count`

**Comment by apparentlymart** [comment]
Hi @apremalal! Sorry this didn't work as expected.

Indeed this is not supported today, since `count` applies only to whole resources, not to nested blocks within resources. At this time unfortunately the best solution would be to duplicate the entire bucket resource block and use `count` to enable only one of the two instances depending on which mode is needed.

#7034 is an issue tracking the general problem here. We are planning to work on this problem once we've addressed some more fundamental improvements to the configuration language that this feature would ultimately depend on.

Since we already have an issue tracking this, I'm going to close this one just to consolidate the discussion over there. Thanks for reporting this!
