### ISSUE TITLE
Provider support for AWS Aurora

### ISSUE THREAD

**Issue by doyouevensunbro** [hashicorp/terraform#16175]
If this is the wrong place for this I apologize. I noticed that Terraform has a MySQL provider but it doesn't have an Aurora provider. Right now there are two main differences between the two:

- 'host' field in 'mysql_user' and 'mysql_grant' is optional and defaults to 'localhost'. That isn't a valid option for Aurora.
- No support for using IAM authentication with database users (http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Creating).

So I forked the MySQL provider and made the changes for Aurora. 

https://github.com/SeismicGames/terraform-provider-aurora

Let me know what else you would like done, or if this belongs somewhere else. 

Thanks

**Comment by SingleMalt** [comment]
Hey @apparentlymart just a quick question: this wasn't just a request for a new provider. I wrote the code for it. I've been using this provider with Aurora since I wrote it. Any reason why there is no traction on how to get it a official provider? Just trying to understand. 

Thanks?

**Comment by erran** [comment]
@doyouevensunbro Check out https://www.terraform.io/guides/terraform-provider-development-program.html

**Comment by doyouevensunbro** [comment]
Ok, will do. Thanks!

**Comment by apparentlymart** [comment]
Hi @doyouevensunbro! Sorry for the delayed reply here, and thanks for working on that Aurora provider.

I thought I'd already replied to this somewhere but maybe that was a different issue. :confounded:

The crux of my intended earlier reply to this was that I worry about the maintenance overhead of adopting this as an entire fork of the provider, rather than adding features to the existing `mysql` provider.

For example, the `IDENTIFIED WITH <plugin> AS <hash_string>` is a part of [the standard `CREATE USER` syntax in MySQL](https://dev.mysql.com/doc/refman/5.7/en/create-user.html), so we could potentially support this by extending the `mysql` provider to allow writing something like the following:

```hcl
resource "mysql_user" "example" {
  user = "example"

  # NOT YET IMPLEMENTED
  auth {
    plugin = "AWSAuthenticationPlugin"
    as     = "${aws_iam_user.example.arn}"
  }
}
```

Since password authentication remains the common case for "normal" MySQL usage, I'd leave that as a top-level attribute, but we could offer `auth` as an alternative (which conflicts with `password` and `plaintext_password`) to cover the remaining cases in the `auth_option` production:

* `IDENTIFIED BY 'auth_string'` if either `password` or `plaintext_password` is set
* `IDENTIFIED WITH auth_plugin` if `auth` block is present with only the `plugin` attribute set.
* `IDENTIFIED WITH auth_plugin BY 'auth_string'` if `auth` block is present with both `plugin` and `by` attributes set
* `IDENTIFIED WITH auth_plugin AS 'hash_string'` if `auth` block is present with both `plugin` and `as` attributes set

The above implies that `plugin` is required if the `auth` block is present, and that `by` and `as` are configured to conflict with one another so that only one can be set.

This _does_ require more configuration overhead to deal with Aurora, but this feels like a more sustainable approach since otherwise any new features or bugs fixed in the `mysql` provider would need to also be replicated in the separate Aurora provider.

It looks like @joshuaspence already started working in this direction in terraform-providers/terraform-provider-mysql#11 (I think the "[WIP]" tagging on that caused it to get de-prioritized for review) so maybe using that as a starting point for the above would help get us where we need to be.

**Comment by doyouevensunbro** [comment]
It totally makes sense extending the existing provider. If @joshuaspence isn't working on that pull request I have no problem taking it on in the manner you suggest. Just don't want to step on any toes :)

**Comment by doyouevensunbro** [comment]
@apparentlymart ok, I moved everything over to the MySQL provider and will submit a pull request. One question, the test for setting `AWSAuthenticationPlugin` will only work with Aurora, as MySQL has no idea what that plugin is and you get this error (not really a surprise):

`Error 1524: Plugin 'AWSAuthenticationPlugin' is not loaded`

What are your thoughts on testing? 

Thanks!

**Comment by apparentlymart** [comment]
@doyouevensunbro I'm not sure, but if there is an authentication plugin that we _could_ add to the open source MySQL for testing perhaps we could use that for testing instead. It looks like there is [a test plugin](https://dev.mysql.com/doc/refman/5.5/en/test-pluggable-authentication.html) that we could perhaps use.

**Comment by doyouevensunbro** [comment]
That works for me. Thanks!

**Comment by doyouevensunbro** [comment]
Created pull request https://github.com/terraform-providers/terraform-provider-mysql/pull/26, going to close this issue. Thanks again for the help.
