### ISSUE TITLE
terraform fmt collapses comments inside of empty locals map definition

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform#16199]
Hi there, I wasn't sure if I should record this here on in `hcl`..

### Terraform Version

```
$ terraform version
Terraform v0.10.6
```

### Terraform Configuration File (input)
```hcl
locals {
  cloud_trail_enabled_input_parameters = {
    # HCL doesn't support null, so we can't set these to the "default" - uncomment and set if needed
    # s3BucketName = ""
    # snsTopicArn = ""
    # cloudWatchLogsLogGroupArn = ""
  }
}

locals {
  db_instance_backup_enabled_input_parameters = {
    # HCL doesn't support null, so we can't set these to the "default" - uncomment and set if needed
    # backupRetentionPeriod = ""
    # preferredBackupWindow = ""
    checkReadReplicas = "false"
  }
}
```

### Terraform Configuration File (output)

```hcl
locals {
  cloud_trail_enabled_input_parameters = {
    # HCL doesn't support null, so we can't set these to the "default" - uncomment and set if needed  # s3BucketName = ""  # snsTopicArn = ""  # cloudWatchLogsLogGroupArn = ""
  }
}

locals {
  db_instance_backup_enabled_input_parameters = {
    # HCL doesn't support null, so we can't set these to the "default" - uncomment and set if needed
    # backupRetentionPeriod = ""
    # preferredBackupWindow = ""
    checkReadReplicas = "false"
  }
}
```

### Expected Behavior
Comment structure is retained inside of empty map structure.

### Actual Behavior
Comments are collapsed into one line.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform fmt`

### Important Factoids

* This is only an issue because I haven't been able to find a way to set a `null` value for those map items - this local is being used in a `jsonencode` call which expects `null` for optional values (AWS managed config rules).

**Comment by apparentlymart** [comment]
Hi @mwarkentin! Sorry for this weird behavior, and for the delay in replying.

I just tested this in the v0.12.0-alpha1 release, which includes a new implementation of HCL and its formatter, and it seems that this issue is now fixed. Running `terraform fmt` on your given input didn't change it at all. The new `terraform fmt` is in general quite a bit less aggressive than the old one, focusing mainly on keeping things aligned horizontally.

This fix is already in master and will be included in the forthcoming v0.12.0 release, so I'm going to close this out. Thanks for reporting this, and sorry again for the delayed response.
