### ISSUE TITLE
Terraform Doesn't Honour Floats

### ISSUE THREAD

**Issue by DWSR** [hashicorp/terraform#16250]
### Terraform Version
0.10.6

### Expected Behavior
If I run `ceil(1 / 2)`, I expect to receive `1`.

### Actual Behavior
I receive `0`.

### Steps to Reproduce
1. `terraform console`
2. `ceil(1 / 2)`

**Comment by jbardin** [comment]
Hi @DWSR,

This i the expected behavior, since `1` and `2` are both defaulting to integers, and `0` is the result of integer devision of `1 / 2`. You would need to use a float to indicate you want floating point division. 

```
> ceil(1/2.0)
1
```

This works the same in many other languages as well, take python for example

```
>>> math.ceil(1/2)
0.0
>>> math.ceil(1.0/2)
1.0
```

**Comment by apparentlymart** [comment]
The forthcoming revamp of the configuration language will remove the integer vs. float distinction, since it is indeed confusing to have behavior like what you describe here. More on this to come soon! For now, @jbardin is right that this is expected behavior for 0.10 and can be worked around by explicitly using the `.0` notation for the time being.

**Comment by DWSR** [comment]
It would appear that Terraform also treats variables internally as ints. For example:
```hcl
locals {
 num_azs = "${length(data.aws_availability_zones.zones.names) * 1.0 }"
}

locals {
  still_an_int = "${ceil(local.num_azs / 5)}"
}
```
`local.still_an_int` is 0, even though it ought to be 1. Will this behaviour also be fixed?

**Comment by apparentlymart** [comment]
Currently what's going on there is that internally Terraform treats all expression results as strings, so `num_azs` is being saved as `"5"`, and then when it's referenced again in the `still_an_int` expression Terraform interprets that string as an int because it lacks the `.0` suffix. This is exactly the sort of confusing behavior we're intending to address with the forthcoming change.

In the future state, _all_ numeric values will be arbitrary-precision floats, so indeed this odd behavior should be fixed. Integer division will not be possible at all, although the `floor` function can still be used to obtain the integer part of a division result for use in conjunction with the modulo operator.
