### ISSUE TITLE
Unable to create lambda function in 0.10.7 anymore

### ISSUE THREAD

**Issue by Eddman** [hashicorp/terraform#16267]
### Terraform Version
0.10.7 (windows_amd64)

### Terraform Configuration Files
```hcl
resource "aws_lambda_function" "tagging" {
    depends_on    = [ "data.archive_file.zip_lambda" ]

    filename      = "${data.archive_file.zip_lambda.output_path}"
    function_name = "my-lambda"
    role          = "${aws_iam_role.lambda_role.arn}"
    handler       = "tagging_lambda.lambda_handler"
    runtime       = "python2.7"
    timeout       = "60"
    memory_size   = "128"

    tags          = "${var.tags}"
}
```

### Expected Behavior
Lambda will be created.

### Actual Behavior
Lambda creation hangs forever. Normally its done in few seconds. When I revert to 0.10.6 (without running `terraform init` again) the lambda is created without any issues.

### Steps to Reproduce
1. Use the config above
1. `terraform init`
1. `terraform apply`

**Comment by jbardin** [comment]
This seems to be an issue with core, rather than with the aws provider seeing how it works with the same provider binary on 0.10.6, but there is very little different between 0.10.6 and 0.10.7 as it was mostly released to fix a regression during `init`. 

Can you provide the debug logs to see if there is any indication of what terraform is doing?

**Comment by Eddman** [comment]
Here is the verbose output:
[debug.out.tar.gz](https://github.com/hashicorp/terraform/files/1368329/debug.out.tar.gz)

**Comment by Eddman** [comment]
Ok my bad. The issue was in incorrect assumed role policy for the lambda.
