### ISSUE TITLE
About plugin cache feature 

### ISSUE THREAD

**Issue by papiveron** [hashicorp/terraform#16262]
Hi,

I am usier tf v0.10.7 and would like to know why `terraform init` still downloads providers plugins into the current directory each time I run the command, instead of using plugins with the same version in `~/.terraform.d/plugin-cache/`.

Regards,
Eugène NG

**Comment by WillMorrey** [comment]
Hi,

I've just encountered this behaviour too, also running Terraform v0.10.7 (as this separate plugin cache feature would be a massive win for us).  I have configured my machine with a .terraformrc file to use:

`plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"`

The screenshot is from Ubuntu 16.04 LTS x64, where I've got it downloading plugins into the plugin-cache directory, but it's also downloading them into the project's directory too.

![image](https://user-images.githubusercontent.com/32159193/31185589-412dc0a6-a924-11e7-8e1c-bb4b4bb98d41.png)

I was wondering if another variable like this might exist to relocate the plugins directory?

`plugin_dir = "$HOME/.terraform.d/plugins"`

Testing the same thing on Win7 x64, the terraform.rc file just seems to be ignored and the behaviour seems unchanged from Terraform v0.10.6.

I'm content to be shown I'm doing something wrong! ;)

Will

**Comment by apparentlymart** [comment]
Hi @papiveron, @WillMorrey!

The behavior when caching is enabled is that Terraform should download the plugins into the cache directory and then create a _link_ (hardlink if possible, symlink otherwise) in `.terraform/plugins`. Since @WillMorrey appears to be on a Linux system, I expect a hardlink is being created here unless the home directory and the `.terraform` directory are on different filesystems.

You can verify this using `stat`:

```
$ stat .terraform/plugins/linux_amd64/terraform-provider-template_v1.0.0_x4 
  File: '.terraform/plugins/linux_amd64/terraform-provider-template_v1.0.0_x4'
  Size: 11711744  	Blocks: 22896      IO Block: 4096   regular file
Device: 2ch/44d	Inode: 10879597    Links: 2
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    apparentlymart)   Gid: ( 1000/    apparentlymart)
Access: 2017-10-05 08:44:33.695199850 -0700
Modify: 2017-10-05 08:44:33.687199612 -0700
Change: 2017-10-05 08:44:33.691199731 -0700
 Birth: -

$ stat /home/apparentlymart/.terraform.d/providers-cache/linux_amd64/terraform-provider-template_v1.0.0_x4
  File: '/home/apparentlymart/.terraform.d/providers-cache/linux_amd64/terraform-provider-template_v1.0.0_x4'
  Size: 11711744  	Blocks: 22896      IO Block: 4096   regular file
Device: 2ch/44d	Inode: 10879597    Links: 2
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    apparentlymart)   Gid: ( 1000/    apparentlymart)
Access: 2017-10-05 08:44:33.695199850 -0700
Modify: 2017-10-05 08:44:33.687199612 -0700
Change: 2017-10-05 08:44:33.691199731 -0700
 Birth: -
```

On my system they both have the Inode value `10879597`, which tells us that this is two references to the same file on disk, rather than two separate files. Although the file appears in two directories, it is only stored on disk once.

The `.terraform/plugins` directory is still the source consulted by every command except `terraform init` since this directory is used to "fix" plugins so that running `terraform init` in another configuration directory (which may select different versions) would not implicitly upgrade plugins in other configurations. This also retains the ability to manually install certain plugins for a particular configuration only, which is important for some Terraform users. Speaking generally, the design requirement here was to retain the guarantee that plugin versions for a given working directory may only change during `terraform init` within that directory.

----

On Windows we are not currently able to create these links and so Terraform will copy the files from the cache directory. However, Windows users to still get the benefit of not _re-downloading_ the plugins each time: instead, Terraform will just copy the file from the cache dir into the `.terraform` directory locally, after confirming that the needed version is already in the cache.

We may be able to make the linking behavior work on Windows too in a later release; we saw some strange behavior in initial testing and so disabled it to be safe, but NTFS _does_ have the concept of a symbolic link and so we could use it if we can get confident that it won't cause strange side-effects for Terraform running on Windows.

**Comment by WillMorrey** [comment]
Hi @apparentlymart,

Thanks for your reply, that certainly made a lot of sense.  I can confirm that the copies of the file from my previous screenshot are indeed on the same volume and are in reality only one file, as per your notes:

![image](https://user-images.githubusercontent.com/32159193/31239950-ccae27ba-a9f6-11e7-9f02-e19376445ec3.png)

This feature would be extremely useful on Windows too.

I will also ensure that we have `.gitignore` configured to omit `.terraform/` from the configurations in our repository, as per the documentation, since that will help prevent clogging up our Git server - especially with the `.terraform/plugins` directory.

Many Thanks,

Will

**Comment by apparentlymart** [comment]
Thanks for following up, @WillMorrey! I'm glad things are working as expected for you.

We are not currently working on hardlink/symlink support for Windows in the immediate term, but hopefully we can take a look at it before too long.
