### ISSUE TITLE
Terraform hangs when profile used to init doesn't match plan/apply profile

### ISSUE THREAD

**Issue by spanktar** [hashicorp/terraform#16271]
When Terraform gets confused about AWS credentials/profiles, it hangs forever. Ctrl-C won't exit. I realize this is vague, because I haven't 100% worked out the issue. We were switching back and forth between IAM users and SAML/federated users and in the process I didn't have all of the AWS credentials in the same profiles.

I think this is what was happening: Terraform had been initialized using an AWS profile that was correct, but then our TF files defined a different, possibly incomplete profile for use with the AWS provider block. When planning, it would get through some of its data providers refresh, then hang.

When I re-init'd and redefined the "working profile" to match, it ran fine.

### Terraform Version
0.10.6-7, possibly earlier

### Expected Behavior
TF should give up with an error, or at least recognize CTRL-C to exit.

### Actual Behavior
TF just hung, CTRL-C didn't work and I had to kill all processes at the command line.

### state file

Note the profile name here `spanky-5g`:

```
{
    "version": 3,
    "serial": 1,
    "lineage": "c388a89c-bebd-402c-aeb1-1da7822e4d2c",
    "backend": {
        "type": "s3",
        "config": {
            "bucket": "qwerty-sandbox-us-east-1-tfstate",
            "key": "us-east-1/spanky/terraform.tfstate",
            "profile": "spanky-5g",
            "region": "us-east-1",
            "role_arn": "arn:aws:iam::1234567890:role/sandboxAdminAccessRole"
        },
        "hash": 9345827190033900985
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

### aws.tf

Here `var.aws_profile_name` was set to something different (global-5g) than what the environment had been initialized with (spanky-5g).

```
data "aws_caller_identity" "current" {}

provider "aws" {
  profile = "${var.aws_profile_name}"
  region  = "${var.aws_regions[0]}"
  version = "~> 0.1"

  assume_role {
    external_id  = "${var.company}_${var.aws_account_name}_external_id"
    role_arn     = "arn:aws:iam::${lookup(var.aws_account_numbers, var.aws_account_name)}:role/${var.aws_account_name}AdminAccessRole"
    session_name = "${var.company}_${var.aws_account_name}_session"
  }
}

# SEE: https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances
provider "aws" {
  alias   = "secondary"
  profile = "${var.aws_profile_name}-secondary"
  region  = "${var.aws_secondary_regions[0]}"

  assume_role {
    external_id  = "${var.company}_${var.aws_account_name}_external_id_secondary"
    role_arn     = "arn:aws:iam::${lookup(var.aws_account_numbers, var.aws_account_name)}:role/${var.aws_account_name}AdminAccessRole"
    session_name = "${var.company}_${var.aws_account_name}_session_secondary"
  }
}

output "AWS INFO" {
  value = ">>>>>>>>>>>>>>>>>> ${var.aws_account_name} (${data.aws_caller_identity.current.account_id}): ${var.environment} <<<<<<<<<<<<<<<<<<"
}
```

**Comment by MooreDerek** [comment]
I've found that Ctrl+\ works when the Crtl+c is ignored.

**Comment by dgrizzanti** [comment]
I'm seeing this issue as well (using SAML), but Ctrl-C does work (when executed twice), though not without warnings.

```
% terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
^CTwo interrupts received. Exiting immediately
```

Running with `TF_LOG=DEBUG` displays the failed security token errors.

**Comment by annania** [comment]
Thanks for this! I had to update my token and then `terraform apply` worked

**Comment by mhvelplund** [comment]
TF still hangs on expired credentials in TF 0.11.13 as of this writing. There are no error messages and you have to press ^C twice to get out.

**Comment by dgrizzanti** [comment]
There is an open bug on the aws provider repo as well - https://github.com/terraform-providers/terraform-provider-aws/issues/1351

**Comment by anyeone** [comment]
This happens with kubernetes provider as well if your AKS token has died.  Thank you to his thread for guiding me in the right direction on what was happening, I was pretty stumped because Azure still behaves like you're logged in if the token is expired :(

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
