### ISSUE TITLE
Allow Chef Provisioner to fetch chef-client package from internal repository

### ISSUE THREAD

**Issue by thechefcookbookie** [hashicorp/terraform#16293]
This is an enhancement request.

### Terraform Version and the issue
In the current version of Terraform V 0.10.XXX, Terraform chef provisioner seems to call the install script from the chef.io site which in turn interact with the Chef repository to get the chef-client installed. It calls for the usage of proxy in corporate environments. 

### Terraform Configuration and the workaround used
I am currently using Terraform to provision the VMs through VMware VSphere provider. As I am not allowed to use proxy in production, as a workaround, I am pre-baking my VM template with chef-client inorder to allow the usage of Terraform chef-provisioner and skipping the chef-client installation with this line:

skip_install        = "${lookup(var.vms[count.index], "chef-skip_client_install", lookup(var.default, "chef-skip_client_install", false))}"

### Requested feature
I am looking for an additional argument for Terraform Chef Provisioner :

a. like "Chef_client_source" or "Chef_client_url" which would allow me with an option to specify the path to my
repository server which stores the chef-client package inorder to get the package from internal repository server rather than fetching it from chef official repo and thus avoiding 
the need to pre-bake the VM template with chef-client and avoiding the usage of proxy in order to use Terraform chef provisioner.

or

b. like "client_installation_script" to which I can feed my custom installation script (bypass the usage of install.sh from chef.io site) which fetches the chef-client from my internal 
repository and does the installation.

**Comment by joerg** [comment]
Hi,

Just stumbled upon this because I also need this "chef_instastallation_script" option. Most of my customers have servers behind the airgap, so without Internet access, and I can only rely on custom scripts and a local artifactory mirror. So basically without this option the chef provisioner can currently not be used without dirty workarounds.

**Comment by mrhearn** [comment]
Is there any likely hood  this request will be fulfilled.  My work-around is to use a local-exec provisioner call to _knife_ which in turn utilises the  --bootstrap-template argument (the template file includes an internal repo location)    
A similar argument in the Chef Provisioner would be most useful.

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
