### ISSUE TITLE
The *new* module-subdir.json file

### ISSUE THREAD

**Issue by cypherhat** [hashicorp/terraform#16324]
Recently upgraded to 0.10.7. After running `terraform init`, I noticed a curious file in my `.terraform/modules` directory: `module-subdir.json`:

```
{
  ".terraform/modules/03bded0c507664450265cd5663bcaeec": "aws/tf_aws_dhcp",
  ".terraform/modules/53bdd8231774896ec67cd8558e052385": "aws/tf_aws_vpc",
  ".terraform/modules/927aef463cc6b7cb2c2afcbdf2d05cee": "aws/tf_aws_az",
  ".terraform/modules/c97d2a406bb3c70820ae69acdfabbbfb": "aws/tf_aws_vpg"
}
```

First off, I'd like to say that I **really** like this file; and, I hope it doesn't go away. Second, I'd like to ask if it would be possible to add one thing to this file: the ?ref query (e.g.,`?ref=v0.1.2`) With this information, we could create a data source that would read this file and use it to tag resources with the specific version of code that was used to provision the resource.

Thoughts?

**Comment by sunckell** [comment]
I really like the idea....

**Comment by jbardin** [comment]
Hi @cypherhat,

Thanks for filing the issue.

First, I'd like to state that this file is _entirely_ and implementation detail. It was a workaround to maintain compatibility with unexpected uses of subdirectories in modules. Also, you cannot count on anything in the `.terraform/` directory being stable between releases, that's terraform's "private" workspace, and things often need to change in there.

I'm not sure what your use case would be though, as that file doesn't reference every module, and it basically records what was after a `//` in a module source. 

As for tooling, it would be better to directly parse the configuration for the `source` attributes, rather than relying on the storage layer itself. There's some work being done in this area already for the terraform registry, some of which may make it back into the terraform OSS tooling itself.

**Comment by mildwonkey** [comment]
Hi, I'm going to close this issue since there is a suggested better path for getting this information. If you are interested in a parsing the configuration to get `sources` for modules as jbardin suggested, I recommend you take a look at terraform-config-inspect: https://github.com/hashicorp/terraform-config-inspect

Thanks!
