### ISSUE TITLE
Is these necessary to update the dependency package to v0.10.x version.

### ISSUE THREAD

**Issue by runzexia** [hashicorp/terraform#16333]
Hi ,

I want to contribute a provider.  
Now there is a version depend on github.com/hashicorp/terraform v0.9.1.
Is these necessary to update the dependency package to v0.10.x version.

**Comment by apparentlymart** [comment]
Hi @runzexia,

There is no strong requirement to update the vendored version of Terraform in a provider repository, since there were no _significant_ changes to the plugin protocol or to the helper libraries within the range of versions you mention.

With that said, I'd encourage updating to the latest version to benefit from any bugfixes and other enhancements that were made to the provider framework more recently.

**Comment by runzexia** [comment]
@apparentlymart  thanks
