### ISSUE TITLE
terraform_remote_state silently swallows S3 key errors

### ISSUE THREAD

**Issue by kelledge** [hashicorp/terraform#16359]
When using the "terraform_remote_state" data source with the S3 backend, key
errors are silently swallowed. This makes troubleshooting and debugging very
cumbersome -- especially when initially experimenting with remote data and a
user is unsure of where the issue may be arising from.

I spent far longer that I would like to admit running combinations of various
terraform state commands and manually downloading the state files from S3 to
inspect them for issues.

In the end, like most things, it was a very simple user error and oversight. I
was simply referencing the incorrect key path. I hope the error reporting can be
improved to save someone else some troubleshooting time down the line.

### Terraform Version
```
Terraform v0.10.7
```

### Terraform Configuration Files
```hcl
data "terraform_remote_state" "network" {
  backend = "s3"

  config {
    bucket = "my_bucket"
    key    = "path/with/typo/or/other/error" // Specified key does not exist
    region = "us-east-1"
  }
}

output "debug" {
  value = "${data.terraform_remote_state.network.id}" // raises 'does not have attribute' error
}
```

### Debug Output
TF_LOG=1 terraform plan
```
2017/10/15 13:47:12 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>terraform/module2.tfstate</Key><RequestId>071F60DA1E16492B</RequestId><HostId>svTPbdYPBABwlsFMzYHEiYIHQH8NEI6kb3OuKcFkbQL3KAtjJwIIvQS/SzpsZ89zfMr8zIc+j0I=</HostId></Error>
2017/10/15 13:47:12 [DEBUG] [aws-sdk-go] DEBUG: Validate Response s3/GetObject failed, not retrying, error NoSuchKey: The specified key does not exist.
	status code: 404, request id: 071F60DA1E16492B, host id: svTPbdYPBABwlsFMzYHEiYIHQH8NEI6kb3OuKcFkbQL3KAtjJwIIvQS/SzpsZ89zfMr8zIc+j0I=
2017/10/15 13:47:12 [DEBUG] New state was assigned lineage "411a0d52-7a20-4d0f-82a0-2ff6dcfb636e"
2017/10/15 13:47:12 [INFO] terraform: building graph: GraphTypeInput
2017/10/15 13:47:12 [TRACE] ConfigTransformer: Starting for path: []
2017/10/15 13:47:12 [TRACE] Graph after step *terraform.ConfigTransformer:
```

### Expected Behavior
It is my opinion, when the data source fails to find the user specified key, the
entire planning process should exit with a message informing the user that the
data source could not be loaded -- with specifics about the error.

At the very least, the user should receive a warning to the same effect.

### Actual Behavior
Currently the error is silently swallowed. The data source appears to be 
initialized as an empty data source. Execution continues and the user has no 
idea that anything is wrong until data references begin to error.

**Comment by jbardin** [comment]
Hi @kelledge,

Sorry this was an issue for you. If I understand the situation here, it wasn't a problem with the data source specifically, the underlying problem was that outputs don't generate errors. Had `data.terraform_remote_state.network.id` been referenced directly from any resource, it would have halted with an error as you expected. 

If my understanding is correct, there is already a pending fix in master. This won't go into full effect until the 0.11 release however, since it has the possibility of breaking existing configurations.

**Comment by kelledge** [comment]
Hi @jbardin,

> If I understand the situation here, it wasn't a problem with the data source specifically, the underlying problem was that outputs don't generate errors. Had data.terraform_remote_state.network.id been referenced directly from any resource, it would have halted with an error as you expected.

This isn't quite correct. I believe the root of my issue can be rephased as follows:

When using the "terraform_remote_state" data source with S3, if the user specifies a non-existent key, the data is initialized to an "empty" data source rather than displaying the underlying "key not found" error to the user in a friendly, accessible, and obvious way.

Instead, in order to figure out why my configuration was not working as I expected, I had to run `TF_LOG=1 terraform plan` and sift through trace level output to find the root cause of my problems:

```
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>terraform/module2.tfstate</Key><RequestId>071F60DA1E16492B</RequestId><HostId>svTPbdYPBABwlsFMzYHEiYIHQH8NEI6kb3OuKcFkbQL3KAtjJwIIvQS/SzpsZ89zfMr8zIc+j0I=</HostId></Error>
```

I probably would not classify this as a bug, but I believe the behavior of the data source should be to loudly fail when the configured key can not be found, so that future users do not have to dig through trace logs if/when they repeat my mistake of having a typo in my key.

**Comment by jbardin** [comment]
Thanks for the clarification @kelledge.

I missed that the debug value was looking for the actual `id`. Any other attribute would have produced the interpolation error I expected.

In most cases terraform treats a missing state the same as an empty state. When this empty state comes back, it has an `id` because all resources have an `id`.  If it were the wrong bucket you would have gotten an error too.

Since remote state access is read only, there may be room to handle the state slightly differently, unfortunately the interfaces in place don't allow for that at the moment.

**Comment by AlainODea** [comment]
This is still an issue. I took quite a bit of time this week to debug an issue which was rooted in this problem.

It interacts particularly badly with map constructions as it leaves them in a state that prevents count from working. The map ends up with a dep on data.terraform_remote_state.ses_metrics, which will resolve to an empty map since the key in missing in S3. If you pass that map to another module, it stays unevaluated even though the map construction would break it. This behaviour happens regardless if it's a map interpolation or a map literal.

Say you have this:
```terraform
data "terraform_remote_state" "ses_metrics" {
  backend = "s3"

  config {
    region = "${var.terraform_state_aws_region}"
    bucket = "${var.terraform_state_s3_bucket}"
    key    = "us-east-1/${var.vpc_name}/support/ses-metrics/terraform.tfstate"
  }
}
```

And the key referenced there does not yet exist.

Then you use intermediate-variable to compose default environment variables and any custom ones callers to your module might supply:

```terraform
module "default_env_vars" {
  source = "git::git@github.com:gruntwork-io/package-terraform-utilities.git//modules/intermediate-variable?ref=v0.0.3"

  map_value = "${map(
"SES_METRICS_DIMENSION", data.terraform_remote_state.ses_metrics.event_destination_dimension
  )}"
}

module "env_vars" {
  source = "git::git@github.com:gruntwork-io/package-terraform-utilities.git//modules/intermediate-variable?ref=v0.0.3"

  map_value = "${merge(module.default_env_vars.map_value, var.extra_env_vars)}"
}
```

Then you try to build the environment variable JSON for the ECS task:

```terraform
# Merge the default env vars with any extra env vars passed in by the user into a single map
module "all_env_vars" {
  source    = "git::git@github.com:gruntwork-io/package-terraform-utilities.git//modules/intermediate-variable?ref=v0.0.3"
  map_value = "${merge(module.default_env_vars.map_value, var.extra_env_vars)}"
}

# Convert the env vars into a JSON format used by ECS container definitions.
data "template_file" "all_env_vars" {
  count = "${length(module.all_env_vars.map_value)}"

  template = <<EOF
{
  "name": "${element(keys(module.all_env_vars.map_value), count.index)}",
  "value": "${lookup(module.all_env_vars.map_value, element(keys(module.all_env_vars.map_value), count.index))}"
}
EOF
}
```

It blows up trying to do `count = "${length(module.all_env_vars.map_value)}"`:

```
* module.acme-demo.data.template_file.all_env_vars: data.template_file.all_env_vars: value of 'count' cannot be computed
```

**Comment by gdavison** [comment]
This issue seems to have been resolved since it was submitted. If you are still seeing this problem, please create a new issue
