### ISSUE TITLE
Pack Linux release binaries in .bz2

### ISSUE THREAD

**Issue by abitrolly** [hashicorp/terraform#16366]
Packing `terraform` into .bz2 on Linux will save CDN bandwidth.
```
-rwxrwxr-x. 1 anatoli anatoli 55358048 Oct  2 21:45 terraform
-rw-r--r--. 1 anatoli anatoli 13501640 Oct  2 21:47 terraform_0.10.7_linux_amd64.zip
-rw-r--r--. 1 anatoli anatoli 11909436 Oct 16 19:49 terraform.bz2
```
It also allows downloading binary and unpacking without saving archive to disk:

    curl -s https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.bz2 | tar xj

**Comment by apparentlymart** [comment]
Thanks for this suggesetion, @abitrolly!

At the moment we're using `zip` for all platforms because we use a common build process for all of them. We don't have any _immediate_ plans to change this since the build process is "working", though indeed the size savings here are interesting and so we'll consider this next time we're doing work on the build/release system to see if we can do this without too much extra complexity.

We also need to be careful in making this change because people have (for better or worse) hard-coded the current URL scheme into configuration management scripts and other build systems; it may be necessary for us to either hold this change for a major release and mention this prominently in the release notes, or to temporarily release two builds as a transitional period. We'll investigate this further next time we're working on the build system.

**Comment by abitrolly** [comment]
The problem for scripting is that it is impossible to unpack .zip through pipe.

Releasing separate build with URL scheme without duplicate version fields can make less lookup requests for  #16365.

    curl -s https://releases.hashicorp.com/terraform/$(curl -s https://releases.hashicorp.com/terraform/releases.txt)/linux_amd64/terraform

or compressed:

    curl -s https://releases.hashicorp.com/terraform/$(curl -s https://releases.hashicorp.com/terraform/releases.txt)/linux_amd64/terraform.bz2 | tar xj

**Comment by mwgamble** [comment]
If the primary concern is bandwidth, `xz` should be used in favour of `bz2` because it achieves better compression, especially for binaries.

**Comment by abitrolly** [comment]
@mwgamble true
```
55361536 terraform
11911168 terraform.bz2
 9043968 terraform.xz
```

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity and the fact that we don't plan on making this change. Thanks!
