### ISSUE TITLE
Add stable.txt with latest non-beta release tag to releases CDN

### ISSUE THREAD

**Issue by abitrolly** [hashicorp/terraform#16365]
For scripting downloads of latest `terraform` version it is convenient to record stable release tag - 0.10.7 - into https://releases.hashicorp.com/terraform/releases.txt file. Then download URL can be constructed as:

VER=$(curl -s https://releases.hashicorp.com/terraform/releases.txt)
URL=https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.bz2

### References
 -

**Comment by apparentlymart** [comment]
Hi @abitrolly! Thanks for this request.

Currently the releases server has [a JSON manifest](https://releases.hashicorp.com/terraform/index.json) of all available Terraform releases, which is being used by others to achieve the goal you have here. I understand that parsing JSON is not as convenient as just taking the entire result of a particular HTTP resource into an environment variable, but at this time we don't have the resources to support new features within the releases system (which is common across all HashiCorp products, rather than just a Terraform system) so we cannot commit to adding other machine-readable interfaces to the system.

I will leave this open to remember the suggestion, since the situation may change in future.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. We're unlikely to make any changes like this to our release pipeline.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!

**Comment by abitrolly** [comment]
For the reference, I am using this command for refreshing TF.
```
(export TFURL=$(curl -s https://www.terraform.io/downloads.html | grep -o -E "https://.+?_linux_amd64.zip"); echo "Fetching $TFURL"; curl -sSL "$TFURL" > terraform.zip && unzip terraform.zip)  # latest Terraform
```
