### ISSUE TITLE
Terraform should individually destroy/apply changes per instance

### ISSUE THREAD

**Issue by gregusr01** [hashicorp/terraform#16378]
When multiple instances are being changed, Terraform should individually destroy then apply.  This would prevent total environment destruction in instances where a large number (or all) of instances are being changed and would allow for no loss of service.

**Comment by eliaoggian** [comment]
I think that for immutable infrastructure this is a must-have feature! 

Are there any updates on this?

**Comment by apparentlymart** [comment]
Hi all! Sorry for the lack of updates here.

This issue seems to be covering the same use-cases as #7631, so I'm going to close this one out just to consolidate. As I mentioned in a comment over there, attention is in other areas right now but we are likely to return to that problem at some point.

The intended way to solve this right now is to use Terraform to configure some other agent/system that can manage the rolling deploy itself, such as using AWS CloudFormation's UpdatePolicy mechanism through `aws_cloudformation_stack`, rolling updates in Elastic Beanstalk, Azure ScaleSet rolling updates, Google Cloud Managed Instance Groups, or a high-level scheduler system like ECS, Nomad, etc as an extra layer over your compute infrastructure. These systems are all better suited to this sort of work because they are long-running agents that can monitor the cluster state, integrate with monitoring/metrics to "know" if a deploy has succeeded (in some cases), etc.

However, we understand that a simple control over multiple instance parallelism would be helpful in some simpler cases and intend to spend more time on that problem when time allows. In the mean time, feel free to leave a :+1: reaction on the original comment on #7631 since we use those counts to guide prioritization of work.
