### ISSUE TITLE
Provider called when resource count is zero

### ISSUE THREAD

**Issue by johnstudarus** [hashicorp/terraform#16386]
Should the Provider be called/setup when the resource count is zero? I have a use-case where I want to turn on/off DNS setup so I set count to true/false in the DNSimple records. However, the Provider is setup and queries for the API and Account information even when no resources are required.

Seems like the correct response would be for the Provider to do nothing if no resources are required.

Version:
Terraform v0.10.7
"dnsimple" (0.1.0)

Sample file DNS.tf:
provider "dnsimple" {
}

resource "dnsimple_record" "foo-dns" {
  count  = 0
  domain = "foo.com"
  name   = "www"
  value  = "127.0.0.1"
  type   = "A"
  ttl    = 3600
}

$ terraform plan
provider.dnsimple.account
  The account for API operations.

  Enter a value:
Ctrl-C...

Expected output would be for nothing to be queried and nothing done by Terraform.

**Comment by apparentlymart** [comment]
Hi @johnstudarus,

Currently this happens because of an implementation detail where the provider gets dealt with before the `resource "dnsimple_record" "foo-dns"` block has been evaluated to determine that `count = 0`; unfortunately today Terraform doesn't know that there are actually no instances in this resource until the provider has already been initialized.

We may be able to do better here but it's not entirely clear how we'd proceed given the order of operations required: although a literal value of `0` is straightforward here, `count` can contain interpolations and thus we handle it as part of the normal graph traversal in case there are dependencies to deal with.

A better path here may emerge once we've completed some forthcoming refactoring of how we deal with configuration in Terraform. In the short term I can't promise any action here, but we'll revisit once the new internal structures are clearer and thus we'll have a better sense of whether it's feasible to change the order in which things happen here so that we can avoid redundantly instantiating the provider.

**Comment by frank-bee** [comment]
Is this fixed (maybe with the major changes in 0.12)?

**Comment by johnstudarus** [comment]
Looks like it has been fixed in 0.12! This is a different example using a null resource since the DNS provider isn't available for 0.12.

$ ./terraform -v
Terraform v0.12.0-beta1
+ provider.null v2.1.0

$ more hi.tf
resource "null_resource" "hi" {

    count = "0"

    provisioner "local-exec" {
        command = "echo hi"
    }
}

$ ./terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
