### ISSUE TITLE
State persists in deleted and recreated Atlas key

### ISSUE THREAD

**Issue by begriffs** [hashicorp/terraform#1640]
* Mac OS 10.10.3
* Terraform 0.3.7

I configure Terraform to save its state to Atlas like so

```bash
terraform remote -name="organization/project" -access-token="etcetc"
```

Then apply a plan. Later on I encountered some other problems which caused me to manually destroy my VPC. I deleted the `organization/project` value in Atlas. Later on I chose to reuse that remote name on Atlas and surprisingly all the old state information was still inside the key, as if it wasn't truly deleted on Atlas but just hidden.

Is there a way to truly delete Atlas state so that I can reuse the key name later with a blank slate?

**Comment by phinze** [comment]
Sorry for the confusing experience here. This is an Atlas-side issue - the state is indeed archived in Atlas, which is taking up the namespace. In the meantime you'll have to work around the problem by using a new project name to get a blank slate.

I've made sure we have filed in our internal issue tracker. Since this isn't really a TF thing I'm going to close this thread. If you'd like to track progress, though, you're welcome to send support AT hashicorp an email. :+1:
