### ISSUE TITLE
Q: How to specify a Lambda trigger for Cognito user pool?

### ISSUE THREAD

**Issue by piterpong** [hashicorp/terraform#16408]
Hi @all. 

I would appreciate some guidance here from anyone who has managed to successfully configure lambda trigger for cognito user pool using terraform (http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html). 

Much appreciated for your help.

**Comment by apparentlymart** [comment]
Hi @piterpong,

For this sort of specific usage question I think you may get a better answer from one of [the community forums](https://www.terraform.io/community.html), since the issues here are mostly monitored only by Terraform maintainers whereas there's a lot more varied expertise out in the community.

This sort of integration between services is often tricky to wire up due to the documentation being fragmented across different services. I'm not entirely sure if all of the relevant pieces are in Terraform to wire this up; if you find from community forums that there's something missing here then please feel free to open an issue in [the AWS provider's repository](https://github.com/terraform-providers/terraform-provider-aws) to record what's missing.

I'm going to close this, just because it's not describing a specific bug or enhancement and we try to keep the queue focused on development tasks. I hope you can find someone in the community who has experience with this combination of features.

**Comment by zakkg3** [comment]
```
resource "aws_cognito_user_pool" "main" {
  name = "hello-world"
  lambda_config {
    pre_sign_up                    = "${aws_lambda_function.presignup.arn}"

  }
```
