### ISSUE TITLE
Policies token are revoked before expire time 

### ISSUE THREAD

**Issue by hmlingesh** [hashicorp/terraform#16419]
Hello Team ,
In Vault 0.6.0, We are having below role which we have associated to policies.  vault write auth/token/roles/TEST -explicit_max_ttl=315569520. And we have made it default lease ttl is 4 hours for LDAP users.
vault mount-tune -default-lease-ttl=4h /auth/ldap

Whenever we created a token from LDAP login , token expires shows 10years , but after 4 hours its getting revoked automatically. Please suggest how we can overcome this ?? or is this is expected behavior of vault.

we are having consul as back end for vault and consul having back up with AWS s3.

Regards
Lingesh M

**Comment by apparentlymart** [comment]
Hi @hmlingesh! Sorry things aren't working as expected here.

It seems like this may be a Vault problem rather than a Terraform problem. If so, it'd be better to report it in [the Vault repository](https://github.com/hashicorp/vault/).

If you _are_ having a problem with Terraform and Vault used together, it'd be helpful if you could share the relevant parts of your Terraform configuration.

**Comment by apparentlymart** [comment]
Hi @hmlingesh!

Since I didn't hear back from you, I'm going to assume that opening this issue here was a mistake and close this. As noted before, the Vault repository may be a better place to report this issue, if you are still having problems.

Thanks!
