### ISSUE TITLE
Import Microsoft Azure ARM Template

### ISSUE THREAD

**Issue by cpatte7372** [hashicorp/terraform#16425]
Hello Community,

Can someone let me know if its possible to import an Azure ARM template in JSON format into HCL Terraform?

Cheers

Carlton

**Comment by apparentlymart** [comment]
Hi @cpatte7372,

The issues in this repository are looked at mainly by the core development team of Terraform, rather than by users. Usually people get better answers by using one of the [community forums](https://www.terraform.io/community.html), since the wider community has a larger wealth of experience with different permutations of usage.

I'm going to close this just because we use the issue tracker primarily to track development tasks, and I don't expect any of the maintainers in this repository will know the answer to your question. I watch out for Terraform questions on the Stack Exchange sites linked from the community page and I see that in most cases they get good answers, so I would suggest starting with one of those.

**Comment by cpatte7372** [comment]
Ok, no worries apparently,

I'll post to the community you suggested.

Thanks

Carlton
