### ISSUE TITLE
Consul provider can't connect: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sirmax123** [hashicorp/terraform#16432]
Hi!

I'm trying to use the following configuration:
```
provider "consul" {
    address = "${var.consul_address}"
    scheme  = "${var.consul_scheme}"
}

data "consul_agent_self" "consul" {}
```
```
terraform plan -var consul_scheme=https ...
. . .
Get https://some-consul.tld:8501/v1/agent/self: x509: certificate signed by unknown authority
```

Conusl is configured with self-signed certificate and I do not have access to http without encryption.
Also I do not have CA so can't  verify certificate.

Are any options like `curl -k` or `export VAULT_SKIP_VERIFY=true`  for consul provider?

**Comment by apparentlymart** [comment]
Hi @sirmax123!

There isn't an option to just disable verification altogether. Often people deal with the situation you have either by creating a CA (which you specifically said you don't have) or by just supplying the server's self-signed certificate directly to the `ca_file` option. The latter should work, but has the limitation that you'll need to keep updating the clients each time the self-signed cert expires or otherwise changes; _true_ CA certificates generally have a longer lifetime, reducing this burden.

Turning off certificate verification altogether isn't supported, since it doesn't really provide much advantage over just using cleartext http.

I hope this helps! If you have further questions I'd recommend using [the community forums](https://www.terraform.io/community.html) since there are many more people monitoring these with broader experience; the issues in this repository are generally only read by the Terraform core maintainers.

**Comment by sirmax123** [comment]
As workaround if it is possible to get CA:
```
export CONSUL_CA_FILE="/path/ca.pem
export VAULT_CACERT="/path/ca.pem
```

**Comment by zippoobbiz** [comment]
export CONSUL_HTTP_SSL_VERIFY=false
