### ISSUE TITLE
Dependency graph not handling resource errors?

### ISSUE THREAD

**Issue by zytek** [hashicorp/terraform#16438]
# Summary

Trying to add ECS service + ECS task definition via terraform. ECS task definition has an error in json definition file. Instead of error report from terraform I get error about unmet dependencies from ECS service.

### Terraform Version
Terraform v0.10.7
### Terraform Configuration Files
```hcl
resource "aws_ecs_service" "pmm-server" {
  name = "pmm-server-${var.environment}"
  cluster = "${aws_ecs_cluster.ecs.id}"
  task_definition = "${aws_ecs_task_definition.task_pmm_server.arn}"
  desired_count = 1
  deployment_maximum_percent = 100
  deployment_minimum_healthy_percent = 0
  iam_role = "ecsServiceRole"
 /* NOTE: this doesnt help depends_on = ["aws_ecs_task_definition.task_pmm_server"] */
}

resource "aws_ecs_task_definition" "task_pmm_server" {
  family = "pmm-server-${var.environment}"
  container_definitions = "${data.template_file.ecs_task_pmm_server.rendered}"
}
```

### Expected Behavior
Terraform should report error that there is JSON unmarshalling error in ECS task definition

After commenting out ecs_service I get proper error message:
```
Error running plan: 1 error(s) occurred:

* module.ecs.aws_ecs_task_definition.task_pmm_server: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal object into Go value of type []*ecs.ContainerDefinition
```
### Actual Behavior

Hard to debug error related to unmet dependencies:

```
Error running plan: 1 error(s) occurred:

* module.ecs.aws_ecs_service.pmm-server: 1 error(s) occurred:

* module.ecs.aws_ecs_service.pmm-server: Resource 'aws_ecs_task_definition.task_pmm_server' not found for variable 'aws_ecs_task_definition.task_pmm_server.arn'
```

Note: adding explicit depends_on to aws_ecs_service doesn't help.

### Important Factoids

The erroneous json file was just a "full dump" of ECS Task from AWS Console - so it had also volumes configuration etc and not just a "container_definition".

**Comment by apparentlymart** [comment]
Hi @zytek! Sorry for this strange behavior.

I think this is the same problem as terraform-providers/terraform-provider-aws#1644; it seems like there's some faulty error handling in the `aws_ecs_service` resource that's causing this to get buried and then that's causing downstream confusion for Terraform core.

I'm going to close this just to consolidate the discussion in the other issue for now. If the conclusion of that issue is that there's something to be fixed in Terraform Core as well then we can open a specific issue for it when we know what that problem looks like. Thanks for reporting this!
