### ISSUE TITLE
How to retrieve Terraform template parameters?

### ISSUE THREAD

**Issue by ktt3ja** [hashicorp/terraform#16440]
Hi,

I have a use case where I would need to retrieve Terraform parameters that a template would need to create resources. What are some ways I could extract such parameters from a template or a collection of templates?

**Comment by apparentlymart** [comment]
Hi @ktt3ja,

We try to keep the GitHub issues for development tasks rather than general questions, since the set of people watching this queue is much smaller than those participating in the various [community forums](https://www.terraform.io/community.html). You're likely to get a better answer that way.

With that said, from your question it's not entirely clear to me what you are trying to do. If you could share some examples -- even if not working -- I think that would help. Though as I say above, it'd probably be more fruitful to do this via one of the community forums such as the Stack Exchange sites because the people answering questions there have a wider variety of experiences with different use-cases and so you're more likely to get good ideas that way.

**Comment by ktt3ja** [comment]
Hi @apparentlymart,

Sorry, by "parameters" above, I was referring to input variables.

Anyway, my use case is that I would like to write a tool to parse out all the input variables that can be specified for `terraform apply` on a template, without actually running that command. In addition, I'd also like to output metadata about those variables such as type and any default value.

At the time of asking this question, I thought that the `variable` blocks are optional and I'd need to parse out all the instances of `${var. }`, but now I see that the task is a lot simpler since I only need to parse out all the `variable` blocks.

Nevertheless, I'm wondering whether there's already an existing parser module that performs this type of functionality. Since it'd be officially supported, I would not need to worry about it not keeping up with future changes.

Example:

Say I have a template with:

```
variable "foo" { default = [] }
variable "bar" { type = "map" }
variable "baz" {} 
```

Running the tool on it would output:

```
[
{ name: "foo", type: "list",  default: [] },
{ name: "bar", type: "map", default: None },
{ name: "baz", type: "string", default: None }
]
```

For "baz", I'm assuming that the type is "string" by default if nothing is defined, but please correct me if I'm wrong. (I'm still not too familiar with Terraform)

Thanks for the pointer to the community forums. For questions that are specific to Terraform implementation like this one, would it be best to ask here or on Gitter/mailing list? 

Sincerely,
Kiet Tran

**Comment by ktt3ja** [comment]
Hi,

Based on the tags that you added, it seems that you would be open to adding a CLI command to Terraform to do this. If no one has picked up this task yet, is it okay if I start looking into how to implement this?

Since I'm not familiar with Go and would also need to get familiar with the code base, it would be great if you could point me to:

1. The entry-point where things begin executing for `terraform apply`.
2. The part where the templates are parsed into a graph.
3. The data structure(s) used to represent input variables and store information about those variables.

**Comment by apparentlymart** [comment]
Hi @ktt3ja,

In principle we are open to features like this but we are currently being conservative about adding them because they become compatibility constraints for future releases, and we know we're going to be making some major changes to Terraform's configuration language and other internals in forthcoming releases which may then require such behavior to change.

In the short term I'd like to hold off on implementing this, and wait for the current in-flight configuration language improvements to be more mature so we can make sure we're not committing to supporting something that is the wrong design. In particular, we are expecting to drop the idea of variables having an explicit "type" in a forthcoming release, so that's at least one way in which the output of this command would probably need to change if it were implemented today.

In principle you could implement a tool to do what you want here by writing a new program that calls into the APIs of [Terraform's config package](https://godoc.org/github.com/hashicorp/terraform/config), in particular [the `LoadDir` function](https://godoc.org/github.com/hashicorp/terraform/config#LoadDir). We can't yet promise that this API won't change in future versions of Terraform, but we do not change this _often_ so if you are willing to make occasional updates this shouldn't be too bad. (There will be at least one significant reorganization of that package in the near future as we switch to the improved version of the configuration language that is currently under development, but we will probably make all of the major changes there in a single release.)

**Comment by ktt3ja** [comment]
Hi @apparentlymart,

Thanks for the heads up about potential change in the configuration language for future releases of Terraform.

Is there a place where you have documented plans or outstanding designs for this new language?

**Comment by apparentlymart** [comment]
The new version of the configuration language is currently being developed as [HCL2](https://github.com/hashicorp/hcl2), though it will eventually just be called "HCL" once it is stable and released.

Along with improvements to the syntax and expression semantics, there will also be changes to Terraform's internal model that are not reflected in that repository. There is no central place to link to for these at this time, but more information will surface once we get further along the stream of work here.

**Comment by mildwonkey** [comment]
Hello!
In Terraform 0.12 and later, you can use [`terraform show -json ($planfile)`](https://www.terraform.io/docs/commands/show.html#json-output) to inspect the contents of a plan or statefile, including the configured variables.
If you prefer to inspect configuration files directly, instead of a plan or state file, you can use the [`terraform-config-inspect`](https://github.com/hashicorp/terraform-config-inspect) library to parse the config file, including all variables.
Thanks!
