### ISSUE TITLE
installing Application on Azure VM provisioned using Terraform

### ISSUE THREAD

**Issue by Terra870** [hashicorp/terraform#16471]
i am in process of learning Terraform. And as part of the intial exercise i have to prosvision Windows Azure VM, Storage TF state at Azure Stroage account. So far this has been done.Now the next step is to install an application on the provisioned machines.

Can someone guide how can we install software on provisioned machine

**Comment by apparentlymart** [comment]
Hi @Terra870,

The issues on this repository are primarily read by the maintainers of Terraform Core, who are not experts on the details of particular providers. You're must more likely to get a good answer to your question via one of [the community forums](https://www.terraform.io/community.html), since the broader community has a lot more people with experience in a variety of different situations.

We use the issue tracker in this repository to track bugs and enhancements to Terraform Core, so I'm going to close this just because it doesn't represent a bug or change request. I hope you can get help with your question from someone in the community!
