### ISSUE TITLE
Terraform crash with parameterized AWS provider version

### ISSUE THREAD

**Issue by giorgio-v** [hashicorp/terraform#16472]
Maybe it’s not supported, but it’s the wrong behavior nonetheless.

### Terraform Version
Terraform v0.10.8

### Terraform Configuration Files
```hcl
variable "aws_vers" {
    default = "1.1.0"
}

provider "aws" {
    version = "${var.aws_vers}"
    region = "eu-west-1"
}

```

### Debug Output
https://gist.github.com/giorgio-v/a22c54fca50f970fc95e238ce37d4def

### Crash Output
https://gist.github.com/giorgio-v/a22c54fca50f970fc95e238ce37d4def

### Expected Behavior
https://gist.github.com/giorgio-v/a22c54fca50f970fc95e238ce37d4def

### Actual Behavior
https://gist.github.com/giorgio-v/a22c54fca50f970fc95e238ce37d4def

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### Important Factoids
NA

### References
NA

**Comment by apparentlymart** [comment]
Hi @giorgio-v! Sorry for this crash.

This seems to be the same as #15742. Indeed this isn't supposed to crash, but it also isn't intended to work either, because the provider dependency is a property of the configuration itself dealt with during `terraform init`, rather than something that can dynamically change per-run. (Variables are a per-run thing, so they are not usable in `terraform init`.)

As noted in #15742, we'll fix this by making it generate a proper error message rather than a crash, but making version constraints settable by variables is not possible.

I'm going to close this just to consolidate the discussion in #15742. Thanks for reporting this!
