### ISSUE TITLE
Should undefined local variables result in an error?

### ISSUE THREAD

**Issue by CrankyDragon** [hashicorp/terraform#16529]
### Terraform Version
Terraform v0.10.8

### Terraform Configuration Files
```hcl
output "anything" {
    value = "${local.anything}"
}
```

Running this through plan doesn't currently raise an error. Is this intended?

**Comment by apparentlymart** [comment]
Hi @CrankyDragon!

I suspect (though didn't confirm) that the issue here is something different than it appears: in 0.10.8 (and all versions before it) errors in _output values_ are silently ignored due to how they are evaluated optimistically during planning/etc.

This was actually changed recently and the new behavior will be in the forthcoming `0.11.0-beta1` release. Now, as expected, errors are caught and reported.

If you're able to build from `master` and test, I'd be curious to see if you still see the same issue there. If you're not able to run a custom build, then the `0.11.0-beta1` release should allow the same verification once it's out. (Should be coming soon, once we finish up some remaining known issues.)

**Comment by CrankyDragon** [comment]
@apparentlymart Sorry for the late reply to this. Can confirm that this is fixed in the beta build.

**Comment by apparentlymart** [comment]
Thanks for checking this @CrankyDragon, and sorry it isn't fixed.

If you could re-test this with the `TF_LOG=trace` environment variable set and share the result via a [gist](https://gist.github.com/) that would be very helpful to understand what is going on here and how this situation differs from what @jbardin fixed in #16204.

**Comment by CrankyDragon** [comment]
@apparentlymart Sure, you can find the output here: [trace.log](https://gist.github.com/CrankyDragon/9cf9370267425fdcecdf8adf894dfb8d)

**Comment by apparentlymart** [comment]
Thanks for that, @CrankyDragon!

Sorry I wasn't clearer, but I was actually hoping for a trace log from the 0.11.0-beta1 release, so we can see if the manifestation of the problem in the logs has changed.

In 0.10.8, which you seem to have used for this trace, it was expected that such errors would be treated just as warnings when appearing in outputs, which we can see in the logs you shared here:

```
2017/11/06 09:39:53 [WARN] Output interpolation "anything" failed: local.anything: no local value of this name has been declared
```

In 0.11.0-beta1 this same message should appear as a user-visible error, but it sounds like that didn't work for you, so I'd love to see what's written to the logs in this case to see if it's _still_ being handled as a warning or if something else is going on here now that @jbardin's change is included.

Thanks!

**Comment by CrankyDragon** [comment]
@apparentlymart It seems to be working now. I may have just copied the wrong binary. I'm seeing the error now with the beta build. Will go ahead and close this. Sorry for the mixup.

**Comment by apparentlymart** [comment]
Great, @CrankyDragon! Thanks for following up. I'm glad this worked out!
