### ISSUE TITLE
terraform plan -destroy mistakenly shows an additional item

### ISSUE THREAD

**Issue by wasimj** [hashicorp/terraform#16534]
Terraform v0.9.11

`terraform plan -destroy` on an EC2 instance mistakenly shows an additional item (subnet) in red whereas the "Plan: " summary shows just a single item.

Output from `terraform plan -destroy`:

```
- module.instances.aws_instance.instanceName
- module.instances.data.aws_subnet_ids.subnetDataName

Plan: 0 to add, 0 to change, 1 to destroy.
```

**Comment by apparentlymart** [comment]
Hi @wasimj! Sorry for this strange behavior.

I think what you're describing here is the same as #14048, where data resources were being erroneously shown as being destroyed even though internally they are just removed from the Terraform state.

This was fixed in #15884, which was released in v0.10.4. I believe the output should be correct from v0.10.4 and above.

Since a fix has already been released, I'm going to close this issue. Thanks for reporting this!
