### ISSUE TITLE
Question using modules which both have the same variable

### ISSUE THREAD

**Issue by SurferL** [hashicorp/terraform#16570]
Hi,

I'm trying to get my head around using modules, and passing variables through them, for automating some infrastructure on Vsphere.

I have a `build.tf` file which calls the same modules twice, something like: 
```
module "vsphere_deploy_1" {
	source = "...?ref=v0.0.8"
	vm_name	        = "${var.vm_name}"
	vm_folder	= "${var.vm_folder}"
	vm_template	= "${var.vm_template}"
}
module "vsphere_deploy_2" {
	source = "...?ref=v0.0.8"
	vm_name	        = "${var.vm_name}"
	vm_folder	= "${var.vm_folder}"
	vm_template	= "${var.vm_template}"
}
```
And I'm using python templating to keep adding more, or fewer modules depending on how many vm's I want to create.

The main issue is that they both have `${var.vm_name}` within them, and hence would both be called the same thing. 

I'm calling Terraform plan within python as below:
```
	terraform_plan_cmd = (
		'terraform plan '
		'-out=tfplan '
		'-input=false '
		'-var "vm_name={}" '
		'-var "vm_folder={}" '
		'-var "vm_template={}" '
	).format(
		config.vm_name,
		config.test_folder,
		config.template_name,
	)
	subprocess.check_call(terraform_plan_cmd, shell=True, stdout=sys.stdout)
```
How do I go about adding more VMs programatically with something that I have at the moment using the modules? (Or have I misunderstood them somewhat in how I am parsing my variables?)

Thanks!

**Comment by apparentlymart** [comment]
Hi @SurferL!

Please note that the issue tracker here is not the best place to ask questions since the audience here is pretty small (just a few core maintainers) and this queue is primarily for development tasks.

Since you are generating your configuration anyway, I would suggest just inserting directly into the configuration the literal values you need for each module as part of your generation script:

```hcl
module "vsphere_deploy_1" {
	source = "...?ref=v0.0.8"
	vm_name	        = "vm-1"
	vm_folder	= "vm-folder-1"
	vm_template	= "some-template"
}
module "vsphere_deploy_2" {
	source = "...?ref=v0.0.8"
	vm_name	        = "vm-2"
	vm_folder	= "vm-folder-2"
	vm_template	= "some-template"
}
```

Note that generally-speaking we do not recommend "over-generalizing" configurations through techniques such as code generation unless what is being generated truly is entirely methodical and derived from some other source. If humans are going to be editing whatever data source the Python script is reading anyway, it may prove simpler to just directly maintain the Terraform configuration in version control to get the full benefits of thinking of infrastructure as code.

If you have any further questions here I recommend using one of [the community forums](https://www.terraform.io/community.html), where there are many more participants with a wider spectrum of experience that may be able to offer various options and tradeoffs.

Since this issue does not describe some Terraform Core development work, I'm going to close it. Thanks!
