### ISSUE TITLE
Bug: terraform init skips module download and uses a cached one with the same name

### ISSUE THREAD

**Issue by ktham** [hashicorp/terraform#16596]
### Terraform Version
0.10.8

### Terraform Configuration Files
Refer to https://github.com/ktham/terraform_modules_bug 

### Expected Behavior
`terraform init <working_dir>` should download all modules

### Actual Behavior
`terraform init <working_dir>` does not download all modules, and  instead skips modules that have been downloaded before that has the same name, but from a different module directory.

### Steps to Reproduce
```bash
➜  terraform_modules_bug git:(master) ✗ terraform workspace new w1
Created and switched to workspace "w1"!

You're now on a new, empty workspace. Workspaces isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
```

```bash
➜  terraform_modules_bug git:(master) ✗ terraform init workspace1
Downloading modules...
Get: file:///Users/kevintham/dev/terraform_modules_bug/modules1/module_a
Get: file:///Users/kevintham/dev/terraform_modules_bug/modules1/base

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

```bash
➜  terraform_modules_bug git:(master) ✗ terraform workspace new w2
Created and switched to workspace "w2"!

You're now on a new, empty workspace. Workspaces isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
```

```bash
➜  terraform_modules_bug git:(master) ✗ terraform init workspace2
Downloading modules...
Get: file:///Users/kevintham/dev/terraform_modules_bug/modules2/module_b
Error getting plugins: module root:
  module example.root: module base: bar is not a valid parameter
```

**Comment by apparentlymart** [comment]
Hi @ktham!

Modules are downloaded into the directory `.terraform/modules` in the current working directory, so if you are using the form of `terraform init` where you supply an explicit path as an argument you may be causing Terraform to try to re-use the same `.terraform` directory between multiple configurations.

In general we always recommend changing the current working directory (e.g. with `cd`) into the root module before running Terraform commands, since this removes confusion about the relationships between `.terraform` directories and root modules. If you run Terraform from another directory, you must ensure that you use a separate directory for each distinct path you pass to `terraform init` to avoid collisions like this.

**Comment by ktham** [comment]
I see, ok, thanks for the prompt response @apparentlymart

**Comment by ktham** [comment]
@apparentlymart thinking about this further, is there a way to configure where we place `.terraform/modules`? I'm writing automated tests that would run in both CI and local dev environment, and would want these tests to start from a clean slate and then run in isolation without affect local dev
