### ISSUE TITLE
Terraform graph includes root elements

### ISSUE THREAD

**Issue by xpolb01** [hashicorp/terraform#16608]
Terraform graph includes too many elements. Actual:
![graph](https://user-images.githubusercontent.com/13209628/32623173-3913d2ac-c553-11e7-8dce-ff7412464836.png)

Expected:
<img width="1680" alt="screen shot 2017-11-09 at 1 39 22 pm" src="https://user-images.githubusercontent.com/13209628/32623283-9c8e7652-c553-11e7-8fb1-3493132e857c.png">

**Comment by apparentlymart** [comment]
Hi @xpolb01! Thanks for reporting this.

We're aware that a few implementation details (like the "meta.count-boundary" node) are currently leaking into the graph output; this is covered by #14511.

You also removed from your "expected" graph many things that are _intentionally_ present, though: module variables and outputs are important participants in the graph (they include interpolation expressions) and the resources from child modules are illustrated as such (with the `module.foo.` prefix) because they can have conflicting names with resources in the root.

The `[root]` prefix showing up here _is_ a bug, resulting from the fact that not all of the graph nodes have a proper implementation of graph caption. That's not explicitly captured by #14511 but when we get to that we will be doing a holistic cleanup of the graph output that will cover this too.

Since we already have #14511 open, I'm going to close this just to consolidate the discussion over there. Unfortunately since the graph functionality is not "core workflow" it is, naturally, lower priority than other UX improvements we might make, but we do intend to eventually rework how it's constructed to focus on details that are interesting to users, rather than details about Terraform's implementation.

**Comment by xpolb01** [comment]
@apparentlymart Thanks a lot for very clear explanation!

**Comment by dmitrytokarev** [comment]
@xpolb01 see if this helps - https://github.com/hashicorp/terraform/issues/14511#issuecomment-366505121
