### ISSUE TITLE
Add terraform simulate or terraform check-permissions

### ISSUE THREAD

**Issue by coryodaniel** [hashicorp/terraform#16625]
I have had a few times where I have run a plan and then upon running the plan fails due to missing permissions. 

It would be useful to either have another CLI command to check permissions or to have `plan` have a flag to check permissions so that you could avoid partially applying a plan when the issue is permissions related.

Some CLI command such as:
`terraform simulate`
`terraform check-permissions`
`terraform plan -check-permissions`

This would obviously be very dependent on the individual providers.

**Comment by apparentlymart** [comment]
Hi @coryodaniel,

We've recently added a feature to the provider framework that allows providers to take custom actions during the plan phase, to do things like reaching out to their underlying API to do checks like you describe here.

Our goal is that, as far as possible, Terraform should detect problems during a normal run of `terraform plan`.

Unfortunately most APIs don't offer a "dry run" sort of mode for permissions checking, so we are ultimately limited by what the underlying API can do. For situations where there _is_ such a policy, I expect issues and PRs in the respective providers would be welcome.

Since the necessary core feature is already present, I'm going to close this... but please do open a provider repository issue if you know of a case where Terraform could do such a check with the available API features!

**Comment by coryodaniel** [comment]
I like during the plan phase much better. That's good to know!  Thanks @apparentlymart. I'll add a ticket to the aws provider since it may be possible during the plan phase.
