### ISSUE TITLE
Support for running multiple versions of the same provider

### ISSUE THREAD

**Issue by rochdev** [hashicorp/terraform#16641]
This is not supported right now and results in an error.

**Comment by apparentlymart** [comment]
Hi @rochdev,

In the initial design for explicit provider versions we decided to require a single version of each provider across the entire configuration because providers can use mechanisms such as in-process caching and semaphores to optimize their work, and this wouldn't work dependably if there were multiple instances of the same provider running.

At this time we don't plan to support multiple versions of the same provider for the above reason. This restriction may be relaxed in future if we are able to provide other ways to handle synchronization between plugins, but other work will prevent us from making such a change for the time being.

**Comment by m4h3** [comment]
This makes terraform module registry barely usable at the moment as you'll likely end up in different provider versions enforcement.
