### ISSUE TITLE
Embedding terraform

### ISSUE THREAD

**Issue by waghanza** [hashicorp/terraform#16648]
Hi there,

I love `terraform` as a cloud agnostic building tool.

However, I'd like to embed it into a third-party tool.

I have two options :

* Writing a RESTful API that use terraform (#415)
* Creating a dynamic module (I now that a `go` **app** could be compiled as a `so` file)

Those two solutions has their pros/cons, but I think a dynamic module is more flexible (to embed it into a desktop application).

What do you think ?

Regards,

**Comment by apparentlymart** [comment]
Hi @waghanza,

Since we're still heavily developing Terraform's internal architecture, we aren't yet committing to maintaining internal API compatibility between versions, and indeed are expecting some quite significant refactoring in the near future. However, Terraform's Go packages _can_ be used as libraries if desired, with the caveat that you should vendor a particular version of Terraform and expect to have to make updates when moving to new versions. This constraint applies whether you wrap Terraform in a REST API or via a shared library wrapper.

At present we recommend using Terraform via its CLI as a child process, following the guidelines in our [Running Terraform in Automation](https://www.terraform.io/guides/running-terraform-in-automation.html) guide. The workflows suggested there are more likely to remain stable between releases (breaking changes are still possible but will be called out prominently in the changelog) and `terraform` is a statically-linked Go binary so it is relatively easy to distribute as part of a larger package.

**Comment by waghanza** [comment]
Hi,

Thanks for this information. However, I do not understand when you speak about a `statically-linked` binary.

Regards,

**Comment by apparentlymart** [comment]
"Statically-linked binary" means that the `terraform` program has no external library dependencies (apart from, on some platforms, some mandatory system libraries) and so generally you can copy it onto any system of the same operating system and architecture and it should work.

This is not true of some applications that may require shared libraries and thus would be harder to distribute without special compilation steps.

**Comment by waghanza** [comment]
Understood ;-)

I'll create a REST api using go code
