### ISSUE TITLE
Recreate Autoscaling Group when recreating attached launch configuration

### ISSUE THREAD

**Issue by fbe** [hashicorp/terraform#16662]
Hi, 
I'm using Terraform 0.10.8 and I changed the volume_size for my root_block_device in a launch configuration. Terraform wants to recreate the launch configuration but it fails, because it's attached to a running auto scaling group.

### Error message:

```
Error: Error applying plan:

1 error(s) occurred:

* aws_launch_configuration.bastion_as_launch_config (destroy): 1 error(s) occurred:

* aws_launch_configuration.bastion_as_launch_config: ResourceInUse: Cannot delete launch configuration
bastion_launch_config because it is attached to AutoScalingGroup bastion_autoscale
        status code: 400, request id: cfa832c4-c9f0-11e7-9aa3-3984fb31dc55

```

### Expected Behavior
Terraform should recreate the autoscaling group when removing an attached launch configuration, too

### Terraform version
Terraform v0.10.8

**Comment by bitbrain** [comment]
Terraform is unable to recreate the autoscaling group which is expected behaviour (as far as I know). In order to avoid `ResourceInUse` put the following configuration to your autoscaling group and launch configuration:
```hcl
lifecycle {
    create_before_destroy = true
}
```

**Comment by fbe** [comment]
Hi @bitbrain , 

yep, that solved my problem - but I would expect terraform to know that a create before destroy is necessary - or am I wrong with this assumption?

**Comment by jbardin** [comment]
Hi @fbe,

I'm glad you got a resolution here. No, there's no way terraform can currently know the particular details of a resource that would make it require `create_before_destroy`. Many times it's not even theoretically knowable by terraform, since it requires knowledge of how the resources are being used.

Of course, future versions of terraform may be able to improve the situation, reducing the places this needs to be set ;)
