### ISSUE TITLE
Output variable causes error about "Resource 'x' not found for variable 'y'" when resource ends up with count=0

### ISSUE THREAD

**Issue by kwach** [hashicorp/terraform#16681]
I do use terraform with aws provider but I don't think this is provider issue.

When a resource has count=0 referencing variables cause error:
* output.ec2_example_ip: Resource 'aws_instance.example' not found for variable 'aws_instance.example.private_ip'

### Terraform Version
```sh
$ terraform --version
Terraform v0.11.0
+ provider.aws v1.3.0
```
### Terraform Configuration Files
```hcl
resource "aws_instance" "example" {
  ami           = "ami-2757f631"
  instance_type = "t2.micro"

  key_name = "${aws_key_pair.tf-deployer.id}"
  associate_public_ip_address = "false"

  count = 0
}
output "ec2_example_ip" {
  value = "${aws_instance.example.private_ip}"
} 
```

### Expected Behavior
Output variable should be empty or absent. That was the case with version 10.8

### Actual Behavior
2017/11/17 00:50:27 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error running plan: 1 error(s) occurred:

* output.ec2_example_ip: Resource 'aws_instance.example' not found for variable 'aws_instance.example.private_ip'

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @kwach,

This was working prior to 0.11 because there was a bug where any errors in an output expression would be ignored. In order to give better feedback about errors in outputs, Terraform 0.11.0 now treats them the same as they would be treated in any other location in a Terraform configuration.

There is some guidance on this in [a section of the 0.11 upgrade guide](https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0).

**Comment by kwach** [comment]
Nice! Thank you for almost immediate answer!
This solves it but I must say it makes the code way harder to read. 

Changing the following works like a charm:
```
output "ec2_example_ip" {
  value = "${element(concat(aws_instance.example.*.private_ip, list("")), 0)}"
}
```

**Comment by apparentlymart** [comment]
Hi @kwach,

The fact that it's an error to refer to an attribute with `count = 0` is an annoyance we're aware of, and are planning to fix it indirectly as part of #15605 so it's possible to write the expression as a simple conditional expression rather than as a bunch of nested function calls. The work to make that possible is underway and should show up as part of a set of configuration language improvements in a forthcoming version of Terraform.

**Comment by kwach** [comment]
Understood. I have other issue but I'll submit it under different ticket.

**Comment by KrystianMarek** [comment]
This issue is still there in `Terraform v0.11.8`
