### ISSUE TITLE
Terraform timeout message very misleading

### ISSUE THREAD

**Issue by Dogers** [hashicorp/terraform#16689]
### Terraform Version
0.11

### Expected Behavior
Terraform should have said it was unable to connect to AWS, due to lack of proxy settings. Something like:

```Connection timed out talking to x.y.z.aws.amazon.com```

### Actual Behavior
https://gist.github.com/Dogers/63828486c88cf13472e7a5b38e8f60bb

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
To get out to the internet from our office we **have** to use a proxy server. Normally this is set, but in this case it wasn't. The error message is incredibly misleading - TF wouldn't have been able to get anywhere, so it shouldn't be a message saying it couldn't assume the role, it should be stating that it can't even get to AWS' endpoint. Then mad panics checking to see who has changed what code don't happen :)

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. The underlying code paths have changed quite a bit since this was opened, so it may no longer be relevant.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
