### ISSUE TITLE
Print range of resources

### ISSUE THREAD

**Issue by jonathan-kosgei** [hashicorp/terraform#16687]
Assuming a resource with a count of 5, is there a way I can get the last 3 or the first 2 only?

**Comment by apparentlymart** [comment]
Hi @jonathan-kosgei,

If you want _only_ the first or last elements of a particular count, you can use the `slice` function to achieve that:

```hcl
  value = "${slice(example.foo.*.id, 0, 2)}"
  # ...or...
  value = "${slice(example.foo.*.id, length(example.foo.*.id) - 3, length(example.foo.*.id))}"
```

Another option is to use the `chunklist` function, which splits the list into chunks of a given length, thus giving you access to both the first set _and_ all of the subsequent sets:

```hcl
  value = "${chunklist(example.foo.*.id, 2)}"
```

Unfortunately the `chunklist` function can only work relative to the _start_ of the list, so a "right-aligned" chunking isn't possible in this case.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas github issues here are generally monitored only by our few core maintainers.
