### ISSUE TITLE
Chef Provisioner reporting success - but not doing anything.

### ISSUE THREAD

**Issue by stobias123** [hashicorp/terraform#16692]
Chef provisioner is returning success but nothing is actually happening. This is using a windows2016 AMI in aws.

### Terraform Version
Terraform version: 0.11.0

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "jenkins_windows_slave" {
  count                  = 1
  ami                    = "${data.aws_ami.windows2016_containers_ami.id}"
  instance_type          = "t2.large"
  subnet_id              = "${data.terraform_remote_state.subnets.b_private-id}"
  vpc_security_group_ids = ["${data.terraform_remote_state.security-groups.security_group}"]
  monitoring             = "true"
  key_name               = "keyname"
  iam_instance_profile   = "standard-server"

  root_block_device {
    volume_size = 120
    volume_type = "gp2"
  }

  tags {
    Name         = "${var.tag_name}-${count.index}"
    Stack        = "${var.tag_stack}"
    Environment  = "${terraform.workspace}"
    Backup       = "* */24 * * *"
    Role         = "${var.tag_role}"
    businessUnit = "${var.tag_businessunit}"
  }

  provisioner "chef" {
    connection {
      type     = "winrm"
      user     = "vagrant"
      password = "${data.vault_generic_secret.windows_bootstrap_password.data["password"]}"
    }

    environment     = "hub"
    run_list        = ["cookbook::java"]
    node_name       = "jenkins_windows_container_slave_${count.index}"
    server_url      = "https://api.chef.io/organizations/my-company"
    recreate_client = true
    user_name       = "self_register_validation"
    user_key        = "${file("./validator.pem")}"
    version         = "12.4.1"
    log_to_file     = true

    # If you have a self signed cert on your chef server change this to :verify_none
    #ssl_verify_mode = ":verify_peer"
  }
}
```

### Debug Output
https://gist.github.com/stobias123/8ca88191aa72f415cadd07aa3615d3d1

### Expected Behavior
I should at least have chef installed on the instance. Ideally have it bootstrapped.

### Actual Behavior
Nothing happens.  There is no `C:/Chef` or anything therein. I cannot run `chef-client`. There are no data in the created log file.

### Steps to Reproduce
1. `terraform apply`

**Comment by mcascone** [comment]
I am having a related problem - chef is being passed incorrect FQDN/IP addresses during the Terraform run. 

Are you sure the node you're connecting to, to check if anything happened, is actually the node that chef thinks it should be?

for example: my current experience is:
terraform run:
``` 
Outputs:

ip addrs = [
    10.12.235.76
]
machines = [
    MTPCTSCID139
]
```

immediately after:
```
> knife node show terraform-chef-test-1
Node Name:   terraform-chef-test-1
Environment: _default
FQDN:        MTPCTSCID422.consilio.com
IP:          10.12.235.82
```

I have NO idea where those incorrect values are coming from, since Terraform seems to know nothing about them.

What ends up happening is the Chef run is applied to the wrong machine! I've installed my software on random machines in our private cloud. This is not good.

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
