### ISSUE TITLE
Terraform init should symlink the plugins to ~/.terraform if at all possible

### ISSUE THREAD

**Issue by djandruczyk** [hashicorp/terraform#16732]
When using a large terraform setup with lots of dirs, each time terraform init is run it downloads and shoves some large binaries in .terraform/plugins/linux_amd64 (linux host),  one the order of 50-100 megs,  A smarter method would be to download those in ~/.terraform and just symlink to them on unix-style platforms.  This saves over 50-100 megs per terraform path which can save a lot on a large setup (I have 143 of these, so it saves 14.3 gigabytes on my setup alone.  Right now I need to do it manually and frankly it sucks.

  Not 100% sure what you'd do on windows, though I believe windows now has the concept of symbolic links. 

### Terraform Version

```
...v0.11.0
```

**Comment by erran** [comment]
@djandruczyk I have a use case where we install our own provider plugin into`~/.terraform.d/plugins/linux_amd64`. It doesn't look like the `.terraform/plugins/linux_amd64` directory duplicates what's in there.

Also looks like there's a [plugin cache option](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) you can leverage for both third party and hashicorp provider plugins.

**Comment by jbardin** [comment]
Hi @djandruczyk,

The terraform `init` command only downloads plugins that it can't locate in the discovery paths, otherwise it runs them directly from the discovered location with no symlinks required. Symlinks to provider binaries are followed if they are in one of the discovery paths. 

We've created a few different methods for using specific provider binaries for different use cases. You can add binaries manually from with the config directory in a `./terraform.d/plugins/OS_ARCH/` subdirectory, you can add them globally in a `~/.terraform.d/plugins/OS_ARCH` directory, you can override all search locations with the `-plugin-dir` flag, or use the previously mentioned plugin cache functionality. The legacy paths of the current directory and the directory containing the terraform binary are also still supported.

**Comment by djandruczyk** [comment]
Even using the plugin cache, it STILL copies that plugin to the .terraform dir for each tree I have, which still wastes massive amounts of disk space on a large terraform setup.  It should symlink back to the plugincache in ~/.terraform.d/plugin-cache/OS_ARCH/  Otherwise it's wasting 60-100megs PER terraformed block.
