### ISSUE TITLE
Feature: Flag the use of certain workspaces

### ISSUE THREAD

**Issue by istairbn** [hashicorp/terraform#16797]
Problem: Here are my workspaces.

default
dev
test
prod

I don't want anyone to use default. I want people to be careful using prod.  

Solution: Some way of flagging the use of certain workspaces. 
I'd imagine something along the lines of a workspaces.tf file

workspace "default" {
  flag = "Do not use this, use dev, test or prod"
}
workspace "prod" {
  flag = "Please be careful Bob"
}

If you run tf plan/apply in default it would say 
"default workspace Do not use this, use dev, test or prod"

If you run tf plan/apply in prod, it would say 
"Prod workspace Please be careful Bob"

If there is no workspace with the flag link, do nothing. 

It's not as powerful as adding user access controls, but it could be a quick way of allowing teams to document each workspace, perhaps giving reasons for the usage or a number of the support guy to call if it  

Apologies if there is anything like this already, but I couldn't find anything. My original aim was actually to lock default so no one could use it - but I see that's an enterprise level feature!

**Comment by CrankyDragon** [comment]
Why not just have the default workspace be the development workspace? That would produce one less workspace that needs to be managed and forces everyone into a development workspace by default.

If this not desirable, what you're really asking for is the ability to define policies around your terraform projects, which is precisely what the [Sentinel](https://www.hashicorp.com/sentinel) project aims to do.

**Comment by apparentlymart** [comment]
Thanks for this suggestion, @istairbn!

I expect that we will remove the requirement that there be a `default` namespace in the future, since it was largely a transitional thing to support moving from earlier versions where there were no workspaces at all. That would, at least, address your concern about the "default" workspace.

Workspaces are a concept that lives in the backend, so it's a little architecturally weird to have configuration for them in the Terraform config. This is an interesting idea though, and it'd be interesting to think of a way to include it in the backend API so that the backend itself could support such a thing, settable by the user.

In the shorter term, there is an open issue (which I wasn't able to find quickly, unfortunately) for the idea of including the workspace name in the approval message for `terraform apply`, so it would say something like:

```
Do you want to perform these actions for workspace "prod"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

While not as flexible as a custom message, this does at least remind the user in the approval prompt that they are working with the production environment, and thus hopefully being careful is implied. This is a much easier thing to achieve within the current workspaces design, so something we could do in the near future to partially address the request here.
