### ISSUE TITLE
EvalValidateResource incorrectly throws an error for a list type

### ISSUE THREAD

**Issue by khosrow** [hashicorp/terraform#16801]
### Terraform Version
```
Terraform v0.11.0
+ provider.aws v1.5.0
```

### Terraform Configuration Files
Slightly sanitized, since it's part of a larger module.

`main.tf` using the module:
```hcl
module "ecs" {
  source = "../"

  name = "test-ecs-service"
  cluster_id = "${aws_ecs_cluster.this.id}"
  load_balancer = [
    {
      target_group_arn = "${aws_alb_target_group.this.id}"
      container_name = "helloworld"
      container_port = "80"
    }
  ]
  placement_strategy = [ 
    { 
      type = "spread"
      field = "attribute:ecs.availability-zone"
    }
  ]

  user_data = "${data.template_file.task_defn.rendered}"
}
```

module code:
```hcl

variable "load_balancer" {
  default = []
}

variable "placement_strategy" {
  default     = []
}

resource "aws_ecs_service" "service" {
    name = "${var.name}-ecs-service"

    task_definition = "${aws_ecs_task_definition.this.arn}"
    desired_count = "${var.desired_count}"
    cluster = "${var.cluster_id}"
    iam_role = "${aws_iam_role.ecs_role.arn}"

    load_balancer = "${var.load_balancer}"
    placement_strategy = "${var.placement_strategy}"

    depends_on = ["aws_iam_role_policy.ecs_policy"]
}
```

### Debug Output
https://gist.github.com/khosrow/813e005163e36c252b1b84a0fb811e7c

### Crash Output
```
Error: module.ecs.aws_ecs_service.service: load_balancer: should be a list
```

### Expected Behavior
TF should accept `var.load_balancer`.

### Actual Behavior
TF complains about the data type for `var.load_balancer` even though the data type is correct.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Important Factoids
The input variable `var.load_balancer` is a list similar to `var.placement_strategy`. TF accepts `var.palcement_strategy` but not `var.load_balancer` and it's unclear why.

**Comment by apparentlymart** [comment]
Hi @khosrow! Sorry for the inconsistent behavior here.

Unfortunately Terraform does not _actually_ support assigning to a block as if it were a list, although indeed as you've seen it can be tricked into supporting it in some cases just due to some coincidences of how these different structures are represented internally. (To be specific, both are `map[string]interface{}` in Go's type system, but Terraform has different expectations about what it will find in each case, and so it only "works" if you stay within the subset of situations which happen to have the same underlying representation.)

So with that said, the _correct_ behavior today would be for both of these to be rejected, though I understand that you'd like to find a way to create a dynamic number of blocks here.

It seems like what you've seen here is the same as what was reported in #16582: `${aws_alb_target_group.this.id}` is `<computed>`, and handling of computed values is one of the ways in which maps are different from child blocks, and so this prevents the coincidence that made it work and causes Terraform to raise a confusing error.

#7034 is the issue where we're discussing a proper way to support dynamically creating blocks. We're currently doing some configuration language improvement work that should then allow us to implement that feature, so we do plan to address this but we need to do some other work first to enable it.

I'm going to close this just to consolidate the discussion in #7034. Thanks for reporting this!
