### ISSUE TITLE
build map from list ?

### ISSUE THREAD

**Issue by ebarault** [hashicorp/terraform#16820]
Hi,

Currently, the `map()` interpolator seems to support only an even number of arguments of type `string`.
e.g. `map("foo", "bar", "bar", "baz")`

Is there a way to make it work with a list of those argument instead ?
`map(["foo", "bar", "bar", "baz"])`

This would allow programatic map creation of arbitrary size

**Comment by apparentlymart** [comment]
Hi @ebarault!

Currently the closest thing is the `zipmap` function, which expects the keys and values to come from two different lists:

```
zipmap(list("foo", "bar"), list("bar", "baz"))
```

The new version of the configuration language that we are currently working on integrating has a more sophisticated, generalized syntax for constructing lists and maps called a "`for` expression" (known as a _list comprehension_ in languages like Python) which could achieve what you wanted here, albeit with some more complexity:

```
# (not yet implemented, and may change before release)
{for pair in chunklist(["foo", "bar", "bar", "baz"], 2): pair[0] => pair[1]}
```

It's going to take some time to get the new version of the language rolled out since there are some breaking changes as a result of the new, generalized syntax, so we're going to roll it out cautiously but should have an opt-in preview version of it available soon to start trying out these new capabilities in real-world situations.

**Comment by ebarault** [comment]
hi @apparentlymart !
thanks for getting back to me.
ok, let's wait then.
