### ISSUE TITLE
State manipulation operations via terraform plan and terraform apply

### ISSUE THREAD

**Issue by chriswhelix** [hashicorp/terraform#16860]
## Description
This issue proposes addition of a "formerly_known_as" meta-parameter for all resources. This optional parameter would accept a list of previous names for the resource that, if found in the state file, should be treated as the same resource, and renamed to the current resource name in any updated state file.

## Use Case
Suppose the following configuration, a simplified form of our real use case:

```hcl
// stacks/generic_service/main.tf
module "service_with_alb" {
  source = "../../modules/service_with_alb"
  // ...
}

// modules/service_with_alb/main.tf
resource "aws_alb" "default" {
  // ...
}
resource "aws_alb_target_group" "default" {
  // ...
}
resource "aws_alb_listener" "alb_443" {
  load_balancer_arn = "${aws_alb.default.arn}"
  default_action {
    target_group_arn = "${aws_alb_target_group.default.arn}"
  }
  // ...
}
resource "aws_ecs_service" "default" {
  load_balancer {
    target_group_arn = "${aws_alb_target_group.default.arn}"
  }
  // ...
}
```

So we currently have a module that provides an ECS service with a load balancer, with a bunch of services using it. Now we have a new need for an ECS service _without_ a load balancer. We want to refactor our module into three distinct modules, like this:

```hcl
// modules/alb/main.tf
resource "aws_alb" "default" {
  // ...
}
resource "aws_alb_target_group" "default" {
  // ...
}
resource "aws_alb_listener" "alb_443" {
  load_balancer_arn = "${aws_alb.default.arn}"
  default_action {
    target_group_arn = "${aws_alb_target_group.default.arn}"
  }
  // ...
}
output "target_group_arn" {
  value = "${aws_alb_target_group.default.arn}"
}

// modules/ecs_service/main.tf
variable "target_group_arn" {
  default = ""
}
resource "aws_ecs_service" "default" {
  load_balancer {
    target_group_arn = "${var.target_group_arn}"
  }
  // ...
}

// modules/service_with_alb/main.tf
module "alb" {
  source = "../../modules/alb"
  // ...
}
module "service" {
  source = "../../modules/service_with_alb"
  target_group_arn = "${module.alb.target_group_arn}"
  // ...
}
```

This is, in theory, an identical configuration for the existing services; there is no need for any change to any existing resources. But currently, terraform would want to tear down and recreate everything. Using create_before_destroy frequently is not sufficient to avoid downtime in such situations, due to limitations in its implementation, limitations in provider resource naming, and most unavoidably when the resource involved contains state that must be saved (e.g. database, file store).

In order to perform this migration, I would need to manually run:

```bash
terraform init
terraform state mv module.service_with_alb.aws_alb.default module.service_with_alb.module.alb.aws_alb.default
terraform state mv module.service_with_alb.aws_alb_target_group.default module.service_with_alb.module.alb.aws_alb_target_group.default
terraform state mv module.service_with_alb.aws_alb_listener.alb_443 module.service_with_alb.module.alb.aws_alb_listener.alb_443
terraform state mv module.service_with_alb.aws_ecs_service.default module.service_with_alb.module.ecs_service.aws_ecs_service.default
terraform apply # Should now be no-op
```

The chief difficulty with this is that there are many services using the service_with_alb module, both directly and indirectly; it is difficult to ensure that each service, when updating to the new version of the module, runs the above "state mv" commands before applying changes. We must rely upon a human operator reading the release notes and correctly performing manual tasks. Multiplied by 20+ projects, the chance of nobody screwing up approaches 0.

## Solution
Instead of relying on out-of-band "state mv" commands as above, I propose being able to tell terraform how to perform the rename automatically; the new configuration would then look as follows:

```hcl
// modules/alb/main.tf
resource "aws_alb" "default" {
  formerly_known_as = [“^.aws_alb.default”]
  // ...
}
resource "aws_alb_target_group" "default" {
  formerly_known_as = [“^.aws_alb_target_group.default”]
  // ...
}
resource "aws_alb_listener" "alb_443" {
  formerly_known_as = [“^.aws_alb_listener.alb_443”]
  load_balancer_arn = "${aws_alb.default.arn}"
  default_action {
    target_group_arn = "${aws_alb_target_group.default.arn}"
  }
  // ...
}
output "target_group_arn" {
  value = "${aws_alb_target_group.default.arn}"
}

// modules/ecs_service/main.tf
variable "target_group_arn" {
  default = ""
}
resource "aws_ecs_service" "default" {
  formerly_known_as = [“^.aws_ecs_service.default”]
  load_balancer {
    target_group_arn = "${var.target_group_arn}"
  }
  // ...
}

// modules/service_with_alb/main.tf
module "alb" {
  source = "../../modules/alb"
  // ...
}
module "service" {
  source = "../../modules/service_with_alb"
  target_group_arn = "${module.alb.target_group_arn}"
  // ...
}
```

### What the Caret

In order to disambiguate multiple references to the same module for renaming purposes, entries in “formerly_known_as” must provide a relative path. Say a project uses the same module three times, and thus has the same resource at three places in the tree:

Old:
```
module.service_with_alb.aws_alb.default
module.foo.module.service_with_alb.aws_alb.default
module.bar.module.service_with_alb.aws_alb.default
```

New:
```
module.service_with_alb.module.alb.aws_alb.default
module.foo.module.service_with_alb.module.alb.aws_alb.default
module.bar.module.service_with_alb.module.alb.aws_alb.default
```

How do we know which old occurrence gets renamed to which new occurrence? By applying the formerly_known_as relative to each occurrence where the resource is encountered. The proposed rules for interpreting formerly_known_as are:

1. Start with the scope in which the new resource appears
2. For each “^” element in the formerly_known_as entry, go up one module level
3. Add the remaining elements from formerly_known_as to that scope to get the old name

So for a resource named “module.a.module.b.aws_alb.new_name”, the following formerly_known_as entries would have the listed “state mv” equivalents:

```bash
# “module.c.aws_alb.old_name”
terraform state mv module.a.module.b.module.c.aws_alb.old_name \
                   module.a.module.b.aws_alb.new_name
# “aws_alb.old_name”
terraform state mv module.a.module.b.aws_alb.old_name \
                   module.a.module.b.aws_alb.new_name
# “^.aws_alb.old_name”
terraform state mv module.a.aws_alb.old_name \
                   module.a.module.b.aws_alb.new_name
# “^.^.aws_alb.old_name”
terraform state mv aws_alb.old_name \
                   module.a.module.b.aws_alb.new_name
```

## Related

#591 originally added the “state mv” functionality, representing a less maintainable solution to the same problem.

## Implementation Status

I haven't started looking at how to implement this, but if there's enthusiasm for the feature, I'll work up a PR. Suggestions on approach welcomed.

**Comment by apparentlymart** [comment]
Hi @chriswhelix! Thanks for this proposal.

The general idea here seems very plausible. We're currently doing some quite significant reorganization in core as part of integrating the new configuration language parser/evaluator, so I don't think now is the right time to attempt to implement such a thing, but that doesn't mean we can't discuss the design in the mean time...

---

The main thing I like about this proposal is that it fits within Terraform's model of deciding on a set of actions that will make the state match the configuration: it allows Terraform to produce a workable plan _without_ modifying the state, and then make the changes (actually move the objects around in the state structure) during the "apply" phase.

With that said, I think this consistency with Terraform's model must also extend to Terraform's goal of being transparent with the user about what will happen on apply, so that the user can use `terraform plan` and have confidence that the result will be what is expected. Therefore I think we'd need to find a way to work this "renaming"/"moving" idea into the plan output:

```
-/+ module.foo.null_resource.test (moved from null_resource.test) (new resource required)
      id:           "4701081665954482904" => <computed> (forces new resource)
      triggers.%:   "1" => "1"
      triggers.foo: "2" => "3" (forces new resource)
```

The above is a bit "cluttered", but shows the minimum information we'd want to include in the plan output to be clear about what's going to happen.

This presents some challenges for our internal plan model because it currently uses the resource's full address (some transformations aside) as the key for an instance, and so we'd need to take some care to ensure that we're able to resolve interpolations that use the new address against a state that still uses the old, since actions like validation and planning happen against the _existing_ state, rather than the _updated_ state. Not insurmountable, but some extra complexity to think about.

---

A further challenge with this approach of including an attribute _within_ the `resource` block is that it forces the _new_ location to be aware of the _old_ location, which you addressed here with the relative addressing syntax that supports walking "up" the module tree, but that is bothersome in cases where a module is used by a number of different callers that may have different structures.

Although I've not delved deep into this idea yet to see if there are other implications, an alternative approach I'd consider is to separate the renaming idea into its own configuration construct that can then be placed in any module where all of the affected resources/modules are children:

```hcl
renamed {
  # old address = new address
  "module.service_with_alb.aws_alb.default" = "module.alb.aws_alb.default"
}
```

By expressing this in a separate block we can avoid the need for addressing "up the module tree", and instead treat these strings as just normal resource addresses resolved relative to the module that contains the `renamed` block, which will generally be the caller that is affected by the refactoring.

If the refactoring happens within a re-usable module that has its own child modules, then the `renamed` block can be placed within that main re-usable module and thus any caller of that module doesn't need to do anything special to adopt the renaming, even if (as you indicated) the re-usable module is instantiated multiple times with different arguments.

---

I'm curious to hear your thoughts on the above. As I mentioned at the start of this comment, now isn't the best time to start implementing something as complex as this due to other cross-cutting refactoring work going on, but if we can work through the design now then we can do our best to make room for this future work in our current work (to avoid painting ourselves into a corner) and be ready to get started on implementing this when the time is right.

Thanks again for the proposal!

**Comment by chriswhelix** [comment]
Hi @apparentlymart, thanks for the prompt feedback!

I totally agree about providing a preview of renaming during plan. Without having looked at the relevant code at all, what I was naively imagining was a layer that sits immediately on top of whatever reads the state file in, that would perform the renames by transforming the state at load-time during both plan and deploy. That way the actual process of calculating a path from the current to target state would not require any changes or additional complexity to support the rename. Does that seem feasible?

The most direct approach to what I'm describing would probably necessitate outputting the renames at the top of the plan, separately from any other transforms on the resource (vs. as part of the overall statement about that resource, as you illustrated). That might be slightly less intuitive, but I imagine it would avoid some complexity. It also would have the advantage of outputting renames in the same way for resources with no changes as for changing resources.

---

The issue of where the rename directive should live is something I struggled with, and I've gone back and forth on it while formulating this proposal.

Having the renames be a distinct root-level directive, as you illustrate, is certainly the most flexible approach. My concern is that it would allow a potential build-up of scattered "renamed" directives at multiple levels, from multiple points in history, eventually becoming difficult to understand. Of course, good discipline on the part of the user could avoid that problem -- but I'm a believer in designing systems in a way that naturally discourages patterns that are likely to get the user into trouble.

The advantage, from my point of view, of having the directive within the resource block of the current resource is that it ensures that all the historical information (former names) related to a particular resource are immediately associated with that resource in the config. This means that, for instance, if I want to remove a resource, it's easy to remove all related statements. Whereas if there were multiple "renamed" directives in multiple files, even a global search for the current resource name wouldn't necessarily turn up all related statements.

I do agree that the major drawback of the embedded approach is that it requires a module to know about its users, which is bad from an encapsulation perspective. From a practical point of view, that would not be problematic in our environment, because we don't use modules that live outside our own configuration repository. I'm not sure how common use of external modules is in the community.

Fundamentally, either approach would solve our challenges, and I don't feel very strongly one way or the other -- so I'm interested to hear what others would prefer.

**Comment by mmcguinn** [comment]
I'm a little behind timing-wise, but I found this proposal while searching for a way to handle the same sort of situation @chriswhelix described in his original post - we have several dozen instances of the same terraform deployments (which all have their own deployment/update schedules), which has made refactoring into/out of modules functionally impossible to manage safely with side-channel state commands.

As far as preference between the two proposed solutions, I think the `renamed` construct would be easier to manage, able top treated essentially like a deprecation as far as development goes, rather than needing to specify backwards. That said - any way to do this explicitly in-band with terraform plan/apply would vastly improve the situation in my case.

@apparentlymart Any idea at this point if this is something closer to consideration for future improvements?

**Comment by apparentlymart** [comment]
We will not be working on this in the near future due to other work already in progress, but I do like the direction of using historical "breadcrumbs" in configuration to drive this sort of refactoring and it's very likely that we'll move forward with the general principle here for all of the commands that currently modify state directly, so that they can _all_ work through the plan+apply approval flow.

My latest sketch of this idea is to create a new top-level block -- let's call it `refactoring` just for the sake of this example -- which always lives in the _root_ module of a configuration and gives these hints to encourage Terraform's planning code to make some different decisions than it would by default. For example:

```hcl
# Not yet implemented. May change significantly before release.

refactoring {

    # A "move" block applies in the following cases:
    # - its "from" address refers to an instance that is in the state, AND
    # - its "to" address _does not_ refer to an instance in the state, AND
    # - that instance has the "generation id" matching the gen_id argument
    # If it matches, then Terraform will plan to move the existing object
    # rather than destroy the old and create the new. Any updates
    # that would've been planned had the instance _not_ moved
    # will still be applied to the object.
    move {
        from   = aws_alb_listener.alb_443
        to     = module.alb.aws_alb_listener.alb_443
        gen_id = "1234abcd"
    }

    # A "forget" block applies when:
    # - its "from" address refers to an instance that is in the state, AND
    # - that instance has the "generation id" matching the gen_id argument
    # If it matches, Terraform will plan to discard the object from the state
    # without first destroying it. This is useful if an object is moving to
    # another configuration altogether, e.g. to now be accessed via data sources.
    forget {
        from   = aws_vpc.default
        gen_id = "abcd1234"
    }

}
```

The `forget` block assumes a new idea of a "generation id", which is an id unique in time and space that Terraform will generate each time it performs a "create" operation. If an instance is updated then its generation id remains the same, but if it is replaced then it gets a new one. This gives us then a robust way to talk about _which_ object you want to "forget", so you don't accidentally also forget some later object that happens to be created with that same address.

Having this in the root module, rather than in each module separately, has a few advantages:
* We can use absolute resource addresses like in this example, without inventing a new syntax for relative traversals into parent modules.
* The state conceptually belongs to the whole configuration rather than to individual child modules anyway, and a move for one configuration may not apply in the same way to another configuration that calls that same module. In other words, this mitigates the problem of a module in some sense "depending on" the implementation of its caller.
* Terraform can potentially automatically generate blocks like these in response to CLI commands like `terraform refactor mv` and `terraform refactor forget`, where it is only appropriate to make such modifications to the root module -- others may be coming from a remote source that isn't directly mutable. (Driving this with CLI commands also allows Terraform to insert the correct `gen_id` value automatically, so the user doesn't need to manually look it up somehow.)

There are certainly still some non-ideal parts of the workflow with this alternative design, but I think there's the beginning of a reasonable story for how you might refactor an object into a child module as described in the original problem description:

1. Write your new module, copying the `aws_alb_listener.alb_443` configuration into it and adjusting as necessary (e.g. referencing input variables rather than other resources directly)
1. Write the `module` block for that module into the root module and delete the old `resource "aws_alb_listener.alb_443"` block.
1. Run `terraform refactor mv aws_alb_listener.alb_443 module.alb.aws_alb_listener.alb_443` to generate the `refactor { move { ... } }` construct, and optionally then edit the generated code to add a comment noting the context of that move for the aid of code reviewers.
1. Commit this result to version control all together.
1. Plan/apply as usual, noting the extra annotation in the plan about the move.
1. Optionally remove the `move` block once you know the change has been applied in all workspaces. (This is _optional_ because the `gen_id` in there will prevent that rule from every applying again, and so it's just a matter of config cleanliness.)

If the new module will be in a separate repo, then there's just an extra "step 1b" of doing code review, etc of that separately before referencing it as a remote `source` address in step 2.

In conjunction with several new language improvements coming in [the next major release](https://www.hashicorp.com/blog/terraform-0-1-2-preview), we plan to more strongly encourage a "flat" configuration architecture where there's only the root module and child modules (no grandchild modules, etc) since that's shaping up to be the most practical architecture for a number of reasons, and that also has the nice side-effect of simplifying the problem here by assuming that _most of the time_ users won't need to do with moves between _transitive_ dependencies. (If they do, some extra coordination will be required.)

This is all just a design sketch for now. We won't be doing any further work on this until after the next major release at least, and even then subject to the usual prioritization, etc.

**Comment by alex** [comment]
Is this the same as #19354

**Comment by ChristophP** [comment]
Sorry if the answer to this question seems obvious but why can't terraform detect that a resource name has changes and rename it in the state automatically? Why the need for an explicit rename in the code?

**Comment by apparentlymart** [comment]
Hi all!

Apparently we had this use-case captured in more issues than I realized and so I missed this one on my previous pass, but I just want to belatedly let you all know that an initial feature for this (an evolution of the ideas I was discussing above) is planned to arrive in Terraform v1.1.0, which is currently in beta.

If anyone is able to try it out with v1.1.0-beta1 in non-production settings and has any feedback about it, we'd love to hear from you via new issues in this repository, rather than comments here, just so we can make sure we can track each feedback item separately and minimize the risk of missing anything.

Since the main development work for this has already completed, I'm going to close this issue. Thanks again for the proposal, and I'm sorry I didn't spot this one on the first pass of looking for related issues to update.
