### ISSUE TITLE
Terraform ignores oversized DNS messages

### ISSUE THREAD

**Issue by toxatoor** [hashicorp/terraform#16873]
### Terraform Version
```
$ terraform -v
Terraform v0.11.1
```

### Terraform Configuration Files
```hcl
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}


provider "aws" {
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region     = "${var.aws_region}"
}
```

### Expected Behavior
Download and install required providers plugins. 

### Actual Behavior
```
toxa@toxa $ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": Get https://releases.hashicorp.com/terraform-provider-aws/: dial tcp: lookup releases.hashicorp.com on 10.1.25.1:53: read udp 10.1.25.156:60413->10.1.25.1:53: i/o timeout.
[...] 

toxa@toxa $ host releases.hashicorp.com 10.1.25.1
Using domain server:
Name: 10.1.25.1
Address: 10.1.25.1#53
Aliases:

releases.hashicorp.com is an alias for dualstack.s.shared.global.fastly.net.
dualstack.s.shared.global.fastly.net has address 151.101.65.183
[...] 

toxa@toxa $ echo "nameserver 8.8.8.8" > /etc/resolv.conf 
toxa@toxa $ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.5.0)...

[...] 

* provider.aws: version = "~> 1.5"
Terraform has been successfully initialized!

toxa@toxa $ host releases.hashicorp.com 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

releases.hashicorp.com is an alias for dualstack.s.shared.global.fastly.net.
dualstack.s.shared.global.fastly.net has address 151.101.65.183
[...] 
```

**Comment by jbardin** [comment]
Hi @toxatoor,

This looks like it's strictly DNS response timeout:

    read udp 10.1.25.156:60413->10.1.25.1:53: i/o timeout

Unfortunately if the lookup times out, there's not much that Terraform can do about it. While we could institute some retry mechanisms, we usually prefer `init` to fail more quickly, so the user can make the decision to retry if necessary. 

Is this repeatable in your configuration? If it is, can you get a packet capture showing which query is failing?

**Comment by toxatoor** [comment]
Nope, that's not. 
Local DNS serves whole the office - and there's no problem with resolving at all - as I've mentioned above. 

``` 
$ time host releases.hashicorp.com 10.1.25.1
[...] 

releases.hashicorp.com is an alias for dualstack.s.shared.global.fastly.net.
[...] 

real	0m0.075s
user	0m0.005s
sys	0m0.016s
``` 

Yes, that's reproducible. 
Packets dump: https://gist.github.com/toxatoor/8bcc25803309396c2859c005c71b2a8f 

I assume, the resolving code doesn't rely on system resolver and uses own connection to DNS - and it's probably buggy. 

By the way, this issue occurs in every resolving - for instance, I've run into when tried to switch state storing to S3. It couldn't resolve S3 bucket URL.

**Comment by jbardin** [comment]
@toxatoor,

It's been a while since I've read DNS messages from a tcpdump, but the first thing I notice is that it looks like the server is sending back oversized messages. The RFC-1035 limit for message size is 512 bytes, so there is lost data here, but I'll have to dig a little further to see if the resolver is waiting for more data and timing out because of this.

I'm also not sure why an MX record was requested, that's not something that comes from Terraform or the standard resolver. 

This doesn't appear to be a Terraform issue, as it's using the standard Go resolver which is widely used and has no open issues that look similar. I'm going to keep this open for a while to see if we can gather more information to report upstream.

**Comment by jbardin** [comment]
Ok, I confirmed that the only issue here is that the DNS server is returning invalid DNS messages that are longer than the max allowed size. The server should be truncating the message and setting the TC bit indicating to the client that a TCP request needs to be made to fetch the full payload. The client isn't waiting for extra data, it just ignores invalid messages so the response isn't recorded at all.

For reference, the upstream discussion about workarounds for non-compliant servers is at https://github.com/golang/go/issues/21160

**Comment by toxatoor** [comment]
Thanks, I got it. 
Bad news, infact. Could affect alot of stuff.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity; there have been many changes since this was opened, including fixes to the upstream that i _think_ resolved the problem: https://go-review.googlesource.com/c/go/+/37879/ 

If there is a still an issue present in terraform v0.13, please open a new issue and fill out the template.
Thanks!
