### ISSUE TITLE
Incorrect error messages when remote state version is incompatible

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform#16910]
The error messages displayed suggest an invalid configuration as opposed to a version incompatibility. Should the state file version number have changed between 0.10.x and 0.11?

We're currently using terraform v0.10.8 and haven't updated to v0.11.1 due to how some interpolation rules have changed.

One of our developers accidentally ran a configuration using v0.11.0, and when another developer tried executing `terraform init` with v0.10.8, we got the following errors: `Provider "provider" not available for installation.` and `Provider "module" not available for installation.`

It looks like the actual cause of the error is that the provider format in the state file has changed, e.g. from `"provider": "aws"` to `"provider": "provider.aws"`. Similarly, a provider with an alias declared inside a module may be stored as `"provider": "module.mymodule.provider.aws.myalias"`. It took a while to track down the version issue because we assumed the configuration was incorrect.

**Comment by jbardin** [comment]
Hi @gdavison,

Sorry for the confusion here. The state file is never guaranteed to be backwards compatible, which is why we always block operations if the terraform version is newer than the running process. 

Unfortunately there's not much we can do here to prevent the errors you saw, since it's the old versions of Terraform that will output the cryptic error messages if the state isn't compatible. 

Going forward, `init` should probably check the terraform version as well.

**Comment by gdavison** [comment]
Makes sense, we didn't expect backwards compatibility, especially before v1.0 :)

**Comment by dking3876** [comment]
How do you resolve this issue. do i need to revert back to version 10.X and destroy before upgrding to 11.x and performing an action. Currently i am stuck with an environment i can't update because ive bought a new computer installed terraform 11 and can't initialize any of my terraform projects.. Please help
