### ISSUE TITLE
Wrong error that "required field is not set"

### ISSUE THREAD

**Issue by UvaK** [hashicorp/terraform#16935]
### Terraform Version
```
Terraform v0.11.1
+ provider.dns v1.0.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.vsphere v1.1.1
```

### Terraform Configuration Files
```hcl
...
locals {
  lv1 = [
    {
      network_id = "${element(data.vsphere_network.networks.*.id, 0)}"
    },
    {
      network_id = "${element(data.vsphere_network.networks.*.id, 1)}"
    },
  ]
}

resource "vsphere_virtual_machine" "vm" {
  network_interface = ["${local.lv1}"]
...
}
```

### Expected Behavior

I shouldn't get any errors.

### Actual Behavior
```
Error: module.mirror.vsphere_virtual_machine.vm: "network_interface.0.network_id": required field is not set
```
### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Important Factoids
If I move value of `lv1` local variable into `network_interface` everything works fine. Please see below.
```hcl
...
resource "vsphere_virtual_machine" "vm" {
  network_interface = [
    {
      network_id = "${element(data.vsphere_network.networks.*.id, 0)}"
    },
    {
      network_id = "${element(data.vsphere_network.networks.*.id, 1)}"
    },
  ]
...
}
```

**Comment by jbardin** [comment]
Hi @UvaK,

This can be a little confusing at first glance, as the config structure does looks the same. Technically if this were to work, you wouldn't want a list of lists, you would just want `network_interface = "${local.lv1}"`, but that will throw a slightly different error. 

The difference here is that `local.lv1` is a simple list of maps , while the `network_interface` is a list of schemas with individually typed fields. 

While I don't think we could support this exact construct as you have shown here, we should at least be able to provide better errors around the types of values allowed.

**Comment by apparentlymart** [comment]
At this time, attempting to assign a value to a nested block as if it were a list can appear to work due to some coincidences in how the two are handled internally, but this is not generally supported.

The existing issue #7034 is describing the general problem of dynamically producing nested blocks as you wanted to do here. This will be addressed as a follow-up to the current work to revamp the configuration language to improve its flexibility. At the moment though, Terraform cannot reliably support this sort of dynamic configuration and so instead it's necessary to specify the `network_interface` blocks explicitly:

```hcl
 network_interface {
   network_id = "${element(data.vsphere_network.networks.*.id, 0)}"
 }
 network_interface {
   network_id = "${element(data.vsphere_network.networks.*.id, 1)}"
 }
```

Any attempt to treat a nested block as an attribute will unfortunately cease to work once the new configuration language is in use, because the coincidence that makes it appear to work in certain limited cases no longer applies.

Since #7034 is already open, I'm going to close this one just to consolidate further discussion over there. Thanks for opening this issue!
