### ISSUE TITLE
Resolving datasources before validating resources inputs

### ISSUE THREAD

**Issue by ebarault** [hashicorp/terraform#16959]
### Terraform Version
Terraform v0.11.1

### Description
I'm running into an issue with validation of some resources input when the content of the inputs depends on datasources evalution (such as `terraform_remote_state`, or `null_data_source`, etc.)

Consider the following situation:

`aws_elastic_beanstalk_environment` expects an arbitrary number of `setting {}` blocks. The standard config would be similar to:

```hcl
resource "aws_elastic_beanstalk_environment" "this" {
  # ...
  setting {
    namespace = "aws:elasticbeanstalk:application:environment"
    name      = "foo"
    value     = "bar"
  }
  # ...
}
```

That specific resource enforces a validation on the `setting` input to make sure required fields `namespace`, `name`, `value` are set.

The issue comes when I want to define some of the `setting` blocks programmatically such as in :

```hcl
variable "env_vars" = {
  type = "list"
  default = [
    "foo=bar"
  ]
}

data "null_data_source" "env_vars" {
    count = "${length(var.env_vars)}"
    inputs = {
      namespace = "aws:elasticbeanstalk:application:environment"
      name = "${element(split("=", var.env_vars[count.index]), 0)}"
      value = "${element(split("=", var.env_vars[count.index]), 1)}"
    }
}

resource "aws_elastic_beanstalk_environment" "this" {
  # ...
  setting = ["${data.null_data_source.env_vars.*.inputs}"]
  # ...
}
```

The `aws_elastic_beanstalk_environment` resource inputs validation occurs before the `null_data_source` is evaluated/resolved/computed, and I get the following error:

```
Error: aws_elastic_beanstalk_environment.this: "setting.0.name": required field is not set
Error: aws_elastic_beanstalk_environment.this: "setting.0.namespace": required field is not set
Error: aws_elastic_beanstalk_environment.this: "setting.0.value": required field is not set
```

because as that time, `["${data.null_data_source.env_vars.*.inputs}"]` is still not computed.

The exact same thing happens if a similar construct is waiting for a `terraform_remote_state` to be resolved. 

I thought at first it was a dependency graph issue, tried all the well known workarounds to make sure the modules and resources are loaded in the correct order, before concluding I had no way to get the data sources evaluated before the resources inputs are validated.

The closest issue I found is https://github.com/hashicorp/terraform/issues/11264, but my error happens before data sources are evaluated, not after.

**Comment by apparentlymart** [comment]
Hi @ebarault! Sorry for this strange behavior.

What you are trying to do here seems to be the same sort of thing discussed in #7034. You can see some discussion there about the direction we're planning to take to address this use-case, which depends on some other general configuration language improvement work we're doing now.

As you've seen, due to some coincidences in Terraform's implementation today you can sometimes trick Terraform into treating a nested block as an attribute by assigning a list of maps that happens to have the same internal representation as is currently used for nested blocks (a Go `map[string]interface{}`), but this is not an officially-supported feature and, as we see here, does not work robustly.

The reason for the errors you see here due to one of the internal differences between a map and a nested block: since the nested block structure is statically-specified in the configuration (similar to a struct or class in a statically-typed programming language) its structure is always available at validation time, whereas map values can have arbitrary keys that we don't necessarily know at validation time. The error message you see here results from the fact that the internal representation of map values doesn't _exactly_ match the internal representation of nested blocks when dynamic data is present.

At this time it is, unfortunately, not possible to achieve the sort of dynamic configuration you're trying to write here. Solving #7034 will make this possible via new syntax:

```hcl
# NOT YET IMPLEMENTED: details may change before release

variable "env_vars" {
  type = "list"
  default = [
    "foo=bar"
  ]
}

locals {
  # this is a "for expression", which is a new language feature we plan to add
  # to enable more convenient transformations of lists and maps, avoiding
  # the need for the null_data_source workaround.
  env_vars_map = { for str in var.env_vars: split("=", str)[0] => split("=", str)[1] }
}

resource "aws_elastic_beanstalk_environment" "this" {
  # ...

  dynamic "setting" {
    foreach = "${local.env_vars_map}"
    content {
      namespace = "aws:elasticbeanstalk:application:environment"
      name      = "${dynamic.foreach.key}"
      value     = "${dynamic.foreach.value}"
    }
  }
}
```

An important characteristic of this `dynamic` block syntax, rather than simply assiging a list of maps, is that the nested block structure (the arguments inside the `content` block) is visible to Terraform's validator even though the value of `local.env_vars_map` may not be known yet.

This feature depends on other work that is currently in progress. Once the foundations are in place, we'll work on getting this implemented.

Since the work here is captured by #7034, I'm going to close this issue just to consolidate the discussion over there. Thanks for reporting this, and sorry we don't have a short-term workaround for this particular functionality.

**Comment by gaui** [comment]
I'm also having this issue, see issue: https://github.com/terraform-providers/terraform-provider-null/issues/18

Is it possible to solve this somehow?

**Comment by apparentlymart** [comment]
Apparently I neglected to close this after my previous comment, even though I said I would. As noted before, the main issue for this is #7034 and that is where we'll post future news related to lifting this limitation.

The special `dynamic` block syntax I showed my earlier comment is now slated for inclusion in [the next major version of Terraform](https://www.hashicorp.com/blog/terraform-0-1-2-preview).
