### ISSUE TITLE
provider interpolation

### ISSUE THREAD

**Issue by arminbuerkle** [hashicorp/terraform#16974]
Not sure if bug or feature request or even possible:

### Terraform Version
```
terraform --version
Terraform v0.11.1
```

### Terraform Configuration Files
```hcl
# main.tf
module "dns" {
  source = "aws/dns/"
}
```
```hcl
# aws/dns/dns.tf
module "credentials" {
  source = "../../variables/credentials"
}

provider "aws" {
  region                  = "${lookup(module.credentials.mapping_dns_provider_credentials["aws"], "region")}"
  shared_credentials_file = "${format("%s/%s",path.root,lookup(module.credentials.mapping_dns_provider_credentials["aws"], "credentials"))}"
}

resource "aws_route53_record" "main" {
  zone_id = "${aws_route53_zone.primary.zone_id}"
  name    = "example"
  type    = "A"
  ttl     = "300"
  records = ["127.0.0.1"]
}


```
```hcl
# variables/credentials/credentials.tf
variable "mapping_dns_provider_credentials" {
  description = "Mapping of a provider to a credential file."
  type        = "map"

  default = {
    "aws" = {
      "credentials" = "credentials/aws/credentials"
      "region"      = "eu-central-1"
    }
  }
}

output "mapping_dns_provider_credentials" {
  description = "Mapping of a provider to a credential file."
  value       = "${var.mapping_dns_provider_credentials}"
}

```
### Expected Behavior
Remove `module "dns"` from `main.tf` without errors.

### Actual Behavior
It cannot find any provider configurations:
```yaml
Error: module.dns.aws_route53_record.main: configuration for module.dns.provider.aws is not present; a provider configuration block is required for all operations
```

### Steps to Reproduce
1. terraform init
2. terraform apply
3. remove `module "dns"` from `main.tf`
4. terraform plan

### Important Factoids
When using a module like this, it's possible to call for example aws resources with a specific configuration in a gce module.
This makes it easy to work with deeply nested modules while still being able to control resources from a different provider.

I found it is especially helpful for DNS records since it's possible to create AWS records within a GCE module without having to pass AWS credentials.

The problem is, you can only remove it by explicitly calling `terraform -target=module.dns destroy` first and then removing it from you `.tf` file.

**Comment by jbardin** [comment]
Hi @arminbuerkle,

Sorry for the confusion here, but this is working as expected. Previously this would probably just fail during apply using an incorrectly configured provider. Now we can specify the provider explicitly outside of the module so that it can be cleanly removed. 

See [Interactions Between Providers and Modules](https://www.terraform.io/upgrade-guides/0-11.html#interactions-between-providers-and-modules) in the 0.11 upgrade guide, and the [Provider in Modules](https://www.terraform.io/docs/modules/usage.html#providers-within-modules) section of the documentation. 

I'm closing this as it's working correctly, but feel free to reply here if you still have nay questions.
