### ISSUE TITLE
Terraform issue if we gitignore .terrafrom directory

### ISSUE THREAD

**Issue by codingmaths** [hashicorp/terraform#16989]
### Terraform Version

```
v0.11.0
```

### Terraform Configuration Files

```
terraform {
  backend "s3" {
    bucket = "terraform-remote"
    key    = "dev/terraform.tfstate"
    region = "us-east-1"

 }
}
...
```
### Issue

I have used the terraform backed in my project, where I store terrafrom.state file in s3 bucket. As per my understanding we should not send the .terrafrom folder in git repo.
but with this I am facing one limitation, whenever anyone else is pulling same code from git for same stack,new infra(AWS SErvices) is getting created even though it's already exist and nothing has changed. 
i.e. Terraform is not directly pulling the state file from S3,when user is running terraform init.

**Comment by apparentlymart** [comment]
Hi @codingmaths! Sorry for this strange behavior.

I'm not sure what's going on here. Indeed Terraform's expected behavior is to access the state file in S3 given the configuration you showed here.

In order to better understand what's going on here, it'd be great if you could run `terraform init` with the environment variable `TF_LOG=trace` set, which will then produce verbose debugging information. Please share this in a [gist](https://gist.github.com/) rather than inline here, since trace output is very verbose and so hard to read in a comment box.

The trace log should not contain any credentials but please do review it and feel free to redact any details about specific S3 bucket names, account ids etc that you'd rather not expose here.
