### ISSUE TITLE
How to edit state values in terraform

### ISSUE THREAD

**Issue by Jeyanthinath** [hashicorp/terraform#17007]
### Terraform Version

```
jeyanthinath@jeyanthinath-ThinkPad:~$ terraform version
Terraform v0.11.1

```

### Question

Hi Guys , I am working on a new terraform provider, in my use case my api server will provide extra columns and extra values to some fields in addition to the request I am sending. 

**e.g (these values are just assumptions to show my use-case):**

If I send : 

{ 
name: 'test',
ref: 'student'
}

**e.g-response:**
{
id: '123',
'name': 'test'
ref: '/class/123?type=student'
}

In my use case , the diff which is getting created is showing changes while trying to apply the same configuration file for the second time.

How to make the diff not to show any difference without using `custom-diff`, so I thought it would be the best to edit the state , then it would be good to go while doing diff, how come I do that ?

**1. How to edit the values in the state directly while doing a terraform plan ?
2. If not (1), is there is any solid documentation to implement `custom-diff` ?
3. If not (2), How to avoid this the above scenario without changing the api's ?**

please help me :smiley:

**Comment by tombuildsstuff** [comment]
hey @Jeyanthinath

Thanks for opening this issue

> 1. How to edit the values in the state directly while doing a terraform plan?
> 3. If not (2), How to avoid this the above scenario without changing the api's?

The `Read` function is invoked during a `terraform plan` - which is where the values are set in the State. The issue you're facing is that the value submitted to the API (from the user input) is different to the value being returned (however the Response value contains the original user input as a query string value) - which is leading to a perpectual diff (e.g. where `student` doesn't match `/class/123?type=student`).

There's a couple of ways to solve this issue:

1) Parsing the URI to obtain the relevant value from the query string
2) Adding a DiffSuppressFunc to ignore the prefixed value

Whilst both approaches are possible - I'd recommend using the first approach to parse the value out of the query string if possible. It's also possible to suppress the diff (if that's intentional) which I've documented below - but I suspect you're trying to fix a genuine issue rather than just hiding it?

We have a similar requirement in the Azure Provider where the URI contains key-value pairs (such as `/subscriptions/123/resourceGroups/foo`) which we then parse out to use as needed. Specifically, in the Read method for each resource [we parse the URI as shown here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_resource_group.go#L61) which uses [this method to Parse the URI into Key-Value Pairs](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resourceid.go#L26). When we've obtained that information - we can set it via `d.Set("name", "value")` which sets the value in the State.

I believe you should be able to use the same approach to obtain the values from the query string - and then set them in the Read method as shown above. Would you be able to take a look and see if this solves your issue?

> 2. If not (1), is there is any solid documentation to implement custom-diff?

AFAIK the documentation for this is mainly in the Code itself - in this case [you could use a `DiffSuppressFunc` to achieve this within the Schema which is documented here](https://github.com/hashicorp/terraform/blob/0df8da59f776b211960d9ce52e57a4fa397fdf0a/helper/schema/schema.go#L207) (and I've in-lined below)

```
// SchemaDiffSuppresFunc is a function which can be used to determine
// whether a detected diff on a schema element is "valid" or not, and
// suppress it from the plan if necessary.
//
// Return true if the diff should be suppressed, false to retain it.
type SchemaDiffSuppressFunc func(k, old, new string, d *ResourceData) bool
```

I'm not sure if you've already seen it - but [there's a guide on the Terraform Website on developing custom providers](https://www.terraform.io/guides/writing-custom-terraform-providers.html) which could also be helpful :)

Hope that helps?

Thanks!
