### ISSUE TITLE
Consider not depending on the AWS provider for the S3 backend

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#17010]
Issue terraform-provider-aws#2745 arises from the S3 backend depending on the AWS provider repository, which in turn depends on this repository. I don't know of the update policy here, but the vendored version needs to be updated to deal with a new region, but no release has been made yet. It would be cleaner to implement the S3 backend directly in this repository rather than depending on the provider.

**Comment by jen20** [comment]
terraform-providers/terraform-provider-aws#2745 is related to this.

**Comment by jbardin** [comment]
Hi @jen20,

We started using the provider code for the backend because there was a substantial chunk of initialization code that could be shared between the two, and it solved a number of open issues where behavior between the provider and backend would diverge slightly. I was thinking about moving the client types and initialization into a separate package for a little better modularity, but sharing the code has made keeping things in sync easier (minus vendoring of course). The GCS backend for example doesn't use the provider code, and took a lot of time recently to patch up to match the behavior of the provider. 

Isn't #2745 just a matter of updating the aws provider in core for the next release?

**Comment by jen20** [comment]
For #2745 it could be a case of just vendoring the updated code, but that depends on whether you're happy to have an unreleased dependency in the core. If so, it's straightforward. Another thing to consider might be delegating the back ends themselves to the provider plugins in order that you don't have to drag all the code around in core?

**Comment by jbardin** [comment]
Yeah, it would be cleaner to only vendor released versions, but because the backend uses a small subset of the provider it may not be too big an issue to verify manually.

I've wanted to make backends pluggable for a while, and we've recently been brainstorming some options for how the RPC would work (backends will have to encompass more than just the "remote state" case). Once we have that ironed out, putting it in the provider may be good solution.

Thanks!

**Comment by bflad** [comment]
This was actually resolved awhile ago when we split off https://github.com/hashicorp/aws-sdk-go-base/ to handle the shared authentication bits between the Terraform S3 Backend and Terraform AWS Provider. Terraform Core now only depends on aws-sdk-go and that library, instead of terraform-provider-aws directly. 👍
