### ISSUE TITLE
Terraform HTTP not working with content-type json

### ISSUE THREAD

**Issue by pimpolderman** [hashicorp/terraform#17027]
### Terraform Version
```
Terraform v0.11.1
```

### Terraform Configuration Files

```hcl

data "http" "example" {
  url = "https://api.github.com/meta"

  request_headers {
    "Accept" = "application/json"
  }
}

```

### Expected Behavior
I was hoping to use the JSON key values from the Github endpoint in my security group rules to whitelist github.com CIDR's. 

A curl -v against the endpoint shows the correct content-type

< HTTP/1.1 200 OK
< Server: GitHub.com
< Date: Wed, 03 Jan 2018 16:57:02 GMT
< Content-Type: application/json; charset=utf-8

### Actual Behavior
Terraform doesn't seem to understand the data it get's from the endpoint. 

```
* data.http.github_meta: 1 error(s) occurred:

* data.http.github_meta: data.http.github_meta: Content-Type is not a text type. Got: application/json; charset=utf-8

```

### References
The bug was already reported before, but doesn't seem to be solved at this point. https://github.com/hashicorp/terraform/issues/15164

**Comment by pimpolderman** [comment]
Let me know if you need more info on this 👍

**Comment by apparentlymart** [comment]
Hi @pimpolderman! Sorry for this confusing behavior.

This has been fixed in terraform-providers/terraform-provider-http#5, but that wasn't yet included in a release. However, it's been a while since the `http` provider was released and so it seems due for one, so we'll look at doing that this week.

Since this is already fixed in master I'm going to close this; look out for the 1.0.1 release of the `http` provider with the fix, soon.
