### ISSUE TITLE
Attach network interface device to ec2 instance AWS via terraform

### ISSUE THREAD

**Issue by rapullur** [hashicorp/terraform#17028]
Hello, everyone !! Need some help on attaching network interface device in terraform. I have tried testing with the code below but when creating an instance, aws already makes an eni, before you attach anything. So when you attach something, you will end up with a second eni. I need only one primary private IP and it results in 2 private IP's. Please help as this is urgent. Thanks in advance.

resource "aws_network_interface" "test" {
subnet_id = "${aws_subnet.public_a.id}"
private_ips = ["10.0.0.50"]
security_groups = ["${aws_security_group.web.id}"]

attachment {
instance = "${aws_instance.test.id}"
device_index = 1
}
}

**Comment by apparentlymart** [comment]
Hi @rapullur!

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few Terraform Core maintainers. This question seems to require AWS-specific expertise, so I expect you'll find knowledgeable people on one of the Stack Exchange sites who are able to help here.
