### ISSUE TITLE
How to add version info to custom provider?

### ISSUE THREAD

**Issue by runzexia** [hashicorp/terraform#17051]
### Terraform Version
Terraform v0.11.1

### Expected Behavior
provider.qingcloud (v1.1)

### Actual Behavior
provider.qingcloud (unversioned)

**Comment by jbardin** [comment]
Hi @runzexia,

The provider version is determined from the executable file name by appending `_v` and the semver string. 

Naming your provider `terraform-provider-qingcloud_v1.1.0` should get you the behavior you're expecting. 

I've marked this for documentation, since I don't see the filename versioning mentioned in the custom provider docs.

**Comment by apparentlymart** [comment]
This is currently mentioned in [the _Third-party Plugins_ section](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins), but the audience of that doc is plugin users rather than plugin developers. I think our docs for plugin _developers_ are a bit stale here and mostly date to before we had plugin versioning, so we can find a good place to mention it for developers too.

@runzexia, do you remember which doc pages, if any, you referred to when developing this provider? If you can recall, that will help us decide where is a good place to mention this so that future developers are likely to find it.

**Comment by runzexia** [comment]
https://www.terraform.io/guides/writing-custom-terraform-providers.html

**Comment by apparentlymart** [comment]
Thanks @runzexia! I think what we should do here is add a new section to that guide on how to package a custom plugin for distribution, which can mention the naming scheme @jbardin described, along with other distribution-related concerns such as cross-compilation and testing.

**Comment by mildwonkey** [comment]
The various docs and guide (as well as most of the underlying code) have changed since this issue was opened, so I am going to close it.  Thanks!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
