### ISSUE TITLE
[Doc] Environment variables documentation is contradictory

### ISSUE THREAD

**Issue by DBarthe** [hashicorp/terraform#17065]
Current documentation about variables passed from environment is contradictory.

From `https://www.terraform.io/intro/getting-started/variables.html` :
```
Environment variables can only populate string-type variables. List and map type variables must be populated via one of the other mechanisms.
```

From `https://www.terraform.io/docs/configuration/environment-variables.html`:
```
export TF_VAR_region=us-west-1
export TF_VAR_ami=ami-049d8641
export TF_VAR_alist='[1,2,3]'
export TF_VAR_amap='{ foo = "bar", baz = "qux" }'
```

Also, I can't understand reading the doc, if such variables are stored in state file or not...

Thanks,

**Comment by apparentlymart** [comment]
Hi @DBarthe! Thanks for pointing this out.

The statement in the Getting Started guide is outdated, since support for setting other types of variables is now present. We'll get that Getting Started guide reference revised to describe the current state, as documented in _[Configuring Input Variables](https://www.terraform.io/docs/configuration/environment-variables.html)_.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. The relevant documentation has had many updates since this issue was opened.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
