### ISSUE TITLE
plugin functionality seems utterly broken with modules(?)

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#17079]
Terraform 0.11.1

I cannot make head nor tail of why at the moment, but terraform plugin functionality seems utterly broken in my repository which has multiple modules.

Here is the behaviour:

```
$ terraform init 
...
Initializing provider plugins
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.6.0)...
...

$ terraform get resources
- module.one
  Getting source "../modules/one"
- module.two
  Getting source "../modules/two"
...

$ terraform plan -var-file=environments/type_one.tfvars resources
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
1 error(s) occurred:

* provider.template: no suitable version installed
  version requirements: "1.0.0"
  versions installed: none
```

So note here, it successfully worked out it needed the aws plugin - so downloaded v1.6.0 (which I have specified in my provider resource). It did not successfully work out that it needed the template plugin so did not download it.. however it then goes on to complain that no suitable version is installed. 

In my case I have "optional" modules. That is, I have many modules in the repository, and I call them like this:

``` 
module "one" {
    enabled = "${var.enable_one}"
}
```

All resources in the module "one" have count set to "${var.enabled}" - with appropriate variable declaration to see that the enabled value gets passed through to the module. By setting enabled to false, I can therefore set all of the resources in this module to count=0, thus effectively featureflagging the entire module out. 

Back to my case above - when I terraform init, it does not get supplied the --var-file that terraform plan does - so it does not know from an set of environment flags in that var-file whether a particular module is enabled or not. 

I assume therefore that terraform init works out which plugins to install from the state-file only. but how can that possibly work? - imagine you were terraforming for the first time, it would have a blank statefile, so would install nothing - and then you would get errors. No, it must read the code - but be unaware of the runtime variables and not know which resources have count=0 and which ones dont, so hence try and install plugins for all the modules under the code path. 

If it reads the code to determine the plugins, it is missing the template plugin because half of my modules reference data "template_file" type resources. 

Not only that, but if you look at the above error, you see that for the template provider, version installed= none. 

Well in my ~/.terraformrc I have:

```
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
```

And looking under this directory I can see both the aws provider and the template provider plugins ARE installed. 

```
$ ls ~/.terraform.d/plugin-cache/darwin_amd64/terraform-provider-*

~/.terraform.d/plugin-cache/darwin_amd64/terraform-provider-aws_v1.6.0_x4
~/.terraform.d/plugin-cache/darwin_amd64/terraform-provider-template_v1.0.0_x4
```

So that part is also lying.

I am thoroughly confused, but I have a situation where when I terraform plan module one, it installs two providers (it needs two of them) during the init phase, and plans fine - but when I terraform plan module two, it only installs one provider (it only needs one of them) during the init phase, but the plan complains that another provider is not installed, WHEN IT IS!! - EVEN THOUGH ITS NOT REQUIRED for that module. 

I appreciate that is probably the worst explanation ever, but its quite a tricky problem to explain - does it ring any bells?

**Comment by apparentlymart** [comment]
Hi @gtmtech! Sorry for this odd behavior.

The first strange thing that sticks out to me is that you had to run `terraform get` separately from `terraform init` in your first example. `terraform init` has subsumed the responsibilities of `terraform get` since Terraform 0.9, which is required for the correct behavior here since modules must be installed _before_ provider plugins in order for Terraform to be able to see what providers are in use by the modules.

I notice in your example that you pass an extra argument `resources` to both `terraform get` and `terraform plan`, but not to `terraform init`. I assume this is a sub-directory with configuration in it, in which case you'd need to provide that directory to `terraform init` too in order for it to look at the right set of configuration files to decide which modules to install and thus which plugins are needed.

I suspect that if you run `terraform init` with that additional `resources` argument then you should see the correct behavior.

---

Aside from that, here's some additional background on Terraform's behavior that may help understand what you've seen here, if you're interested:

Terraform uses a static analysis of the configuration to decide which plugins to install and activate, which means it effectively uses the presence of a `resource` block in configuration to decide, regardless of whether that resource is in practice disabled using `count = 0`. It behaves in this way so that the value of `count` can dynamically change based on e.g. data sources or variables without needing to re-run `terraform init`.

Terraform _also_ inspects the state as a secondary source of plugin requirements information, because there may be a resource present in state that has been removed from configuration and so the plugin is needed to successfully destroy it.

**Comment by gtmtech** [comment]
Thanks - thats a great explanation, and helped a lot. 

I have managed to fix my issue by removing the terraform get resources, and ensuring the init has the resources folder as well.
