### ISSUE TITLE
transform graph can not finish over 12 hours when deleting a large quantity of resources

### ISSUE THREAD

**Issue by zengchen1024** [hashicorp/terraform#17095]
### Terraform Version
```
Terraform v0.11.0
```

### Terraform Configuration Files
```hcl
variable "engine_count" {
  default = 1000
}

variable "image_id" {
  default = **
}

variable "availability_zone" {
  default = **
}

variable "flavor_name" {
  default = **
}

variable "network_id" {
  default = **
}

resource "opentelecomcloud_blockstorage_volume_v2" "sys-vol" {
  count = "${var.engine_count}"
  name  = "sys-vol-${count.index}"
  size  = 40
  image_id = "${var.image_id}"
  availability_zone = "${var.availability_zone}"
  volue_type = "SATA"
}

resource "opentelecomcloud_blockstorage_volume_v2" "data-vol" {
  count = "${var.engine_count}"
  name  = "data-vol-${count.index}"
  size  = 1
  image_id = "${var.image_id}"
  availability_zone = "${var.availability_zone}"
  volue_type = "SATA"
}

resource "opentelecomcloud_compute_instance_v2" "engine" {
  count = "${var.engine_count}"
  name  = "engine-${count.index}"
  flavor_name = "${var.flavor_name}"
  availability_zone = "${var.availability_zone}"
  security_groups = ["default"]
  network {
    uuid = "${var.network_id}"
  }
  
  block_device {
    uuid = "${element(opentelecomcloud_blockstorage_volume_v2.sys-vol.*.id, count.index)}"
	source_type = "volume"
	boot_index = 0
	destination_type = "volume"
	delete_on_termination = false
  }
}

resource "opentelecomcloud_compute_volume_attach_v2" "engine_volume_attach" {
  count = "${var.engine_count}"
  instance_id = "${element(opentelecomcloud_compute_instance_v2.engine.*.id, count.index)}"
  volume_id = "${element(opentelecomcloud_blockstorage_volume_v2.data-vol.*.id, count.index)}"
}
```

### Expected Behavior
All the resources should be deleted in an accepted time

### Actual Behavior
Terrafrom blocked at here https://github.com/hashicorp/terraform/blob/master/terraform/transform_destroy_edge.go#L245-L251 and printed that log all the time.  The command of "terraform destory" did not finish when I waited at least 12 hours.

### Steps to Reproduce
Use that configuration file and run the following commands:
1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

**Comment by apparentlymart** [comment]
Hi @zengchen1024! Sorry for this issue and thanks for reporting it.

The graph algorithms in Terraform are not currently optimized for large graphs, and unfortunately I think this configuration is causing a graph that is bigger than it might first appear, due to the use of splat expressions like `${element(opentelecomcloud_blockstorage_volume_v2.data-vol.*.id, count.index)}`.

When Terraform analyses the dependencies here it sees the reference to `opentelecomcloud_blockstorage_volume_v2.data-vol.*.id` and infers that all 1000 instances of `opentelecomcloud_compute_volume_attach_v2.engine_volume_attach` depends on all 1000 of the `opentelecomcloud_blockstorage_volume_v2.data-vol` instances, thus creating 1,000,000 dependency edges from that reference alone. This would also be true for every other splat reference here, resulting in more than 3,000,000 graph edges.

This overly-conservative dependency resolution is a known issue, but usually it just results in reduced parallelism rather than a failure to finish altogether, since `count` is usually set to relatively-small values (less than 10, say) in an average Terraform configuration.

We do hope to be able to address this dependency analysis issue in future so that Terraform can detect references like `opentelecomcloud_blockstorage_volme_v2.data-vol.*.id[count.index]`, but that depends on us first completing the integration of the improved configuration language parser/interpreter we're currently working on. In the mean time, we unfortunately cannot support graphs of this size with the current implementation, and must therefore recommend finding a different strategy to manage this infrastructure.

One alternative approach, if you wish to continue using Terraform here, would be to switch to using code generation rather than `count` to achieve your goals, which will then allow Terraform's current dependency resolver to better understand the resource relationships. For example, you could create a Terraform module with the following content:

```hcl
variable "image_id" {
  default = **
}

variable "availability_zone" {
  default = **
}

variable "flavor_name" {
  default = **
}

variable "network_id" {
  default = **
}

resource "opentelecomcloud_blockstorage_volume_v2" "sys-vol" {
  name  = "sys-vol-${count.index}"
  size  = 40
  image_id = "${var.image_id}"
  availability_zone = "${var.availability_zone}"
  volue_type = "SATA"
}

resource "opentelecomcloud_blockstorage_volume_v2" "data-vol" {
  name  = "data-vol-${count.index}"
  size  = 1
  image_id = "${var.image_id}"
  availability_zone = "${var.availability_zone}"
  volue_type = "SATA"
}

resource "opentelecomcloud_compute_instance_v2" "engine" {
  name  = "engine-${count.index}"
  flavor_name = "${var.flavor_name}"
  availability_zone = "${var.availability_zone}"
  security_groups = ["default"]
  network {
    uuid = "${var.network_id}"
  }
  
  block_device {
    uuid = "${opentelecomcloud_blockstorage_volume_v2.sys-vol.id)}"
	source_type = "volume"
	boot_index = 0
	destination_type = "volume"
	delete_on_termination = false
  }
}

resource "opentelecomcloud_compute_volume_attach_v2" "engine_volume_attach" {
  instance_id = "${opentelecomcloud_compute_instance_v2.engine.id}"
  volume_id = "${opentelecomcloud_blockstorage_volume_v2.data-vol.id)}"
}
```

...and then write a small program to generate a root module that consists of 1000 instances of this module:

```hcl
module "instance_0" {
  source = "./instance"
}
module "instance_1" {
  source = "./instance"
}
module "instance_2" {
  source = "./instance"
}
module "instance_3" {
  source = "./instance"
}
# ...
```

While I'll be the first to admit that this is a hack, it would effectively separate the dependency graphs of each instance to avoid the N*N dependency edge explosion, instead giving Terraform 1000 separate simple graphs to work with.

**Comment by zengchen1024** [comment]
@apparentlymart Thank you very much for your detailed explanation! I got a better understanding of Terraform through your comments. Thanks again!

**Comment by jbardin** [comment]
This is definitely a situation that comes up, though usually not at this scale. 
It's pretty easy to get exponential graph growth with far fewer resource because of the splat syntax, and a couple releases ago this config probably couldn't be applied at all.

I think there's probably some low hanging fruit in the destroy graph creation that we can cut off. While optimizing the graph as a whole is going to take considerable effort, I don't like that the destroy graph is so much more intensive that you can get into a situation where you can create an infrastructure that you can't feasibly destroy.

**Comment by mildwonkey** [comment]
There have been several optimizations to the graph since this issue was opened (and several new issues opened over the years), so I am going to close it. If you are experiencing this issue with terraform v0.13, please open a new issue and fill out the template.
Thanks!
