### ISSUE TITLE
Terraform init doesn't pick backend configuration

### ISSUE THREAD

**Issue by kevinrobayna** [hashicorp/terraform#17137]
### Terraform Version
```
Terraform v0.11.1
```

### Expected Behavior
I was expecting to be able to set all the backend configuration in the CLI so the state in my s3 bucket is used

### Actual Behavior
Terraform is trying to create the whole infrastructure again

### Steps to Reproduce
1. 
```    
terraform init
    -no-color 
    -force-copy 
    -backend-config="backend=s3" 
    -backend-config="bucket=terraform-buckets" 
    -backend-config="region=us-west-2" 
    -backend-config="key=tf-state-dev" 
    -backend-config="profile=learning-account" 
    artifact
```
2.
```
terraform apply
        -no-color
        -var "deployment_bundle_s3_artifact_name=example-app.jar"
        -var "deployment_bundle_s3_source_directory=./"
        -var "environment"=dev 
        -var "region=us-west-2"
        artifact
```

### Additional Context
I already have a bucket with the state saved of what I have currently deployed in aws

**Comment by jbardin** [comment]
@kevinrobayna, Sorry for the unexpected behavior here.

You haven't provided any configuration here, but I assume because of the `-backend-config="backend=s3"` line it means you're trying to add one only through the command line, which isn't supported. The `-backend-config` flag is meant to parameterize a backend in your configuration, it can't declare one on it's own. See the [Partial Configuration](https://www.terraform.io/docs/backends/config.html#partial-configuration) in the backends documentation.

**Comment by kevinrobayna** [comment]
Thanks @jbardin for replying this quickly! You're assuming correctly we have the need to only store the states for dev uat and prod but for example for ci what we were planning to do is apply infrastructure, run test and then destroy infrastructure. Thanks for the note info!
