### ISSUE TITLE
Defining provisioner connection block globally for a resource

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#17164]
Is there a way to prevent duplicating the `connection` block for each provisioner in a resource? See:

```tf
    provisioner "file" {
        source = "${path.module}/logstash-syslog.conf"
        destination = "/tmp/logstash-syslog.conf"

        connection {
            type = "ssh"
            user = "ubuntu",
            private_key = "${file(var.ssh_private_key)}"
        }
    }

    provisioner "remote-exec" {
        inline = [
            "sudo mv /tmp/logstash-syslog.conf /etc/logstash/conf.d"
        ]
        connection {
            type = "ssh"
            user = "ubuntu",
            private_key = "${file(var.ssh_private_key)}"
        }
    }

    provisioner "remote-exec" {
        inline = [
            "sudo mv /tmp/foo /etc/bar"
        ]
        connection {
            type = "ssh"
            user = "ubuntu",
            private_key = "${file(var.ssh_private_key)}"
        }
    }
```

Can you define the connection block globally?

**Comment by teamterraform** [comment]
Hi @nodesocket! Sorry for the slow response.

You can define a `connection` block as a direct child of a `resource` block and it will serve as a default connection configuration for all `provisioner` blocks on that resource.

There is currently no means to define a `connection` configuration globally in the sense of sharing it between multiple resource blocks. The closest to that is to factor out the relevant settings into one or more Local Values and refer to them inside the connection blocks, so that the specific values themselves are not duplicated.

The issue #353 is representing the use-case of sharing such configurations in a more fluid way, but as full disclosure it is unlikely that this issue will get further investment in the near future because provisioners are not a current area of investment for the Terraform team; that feature exists as a last resort when better alternatives (custom machine images with software preinstalled, and/or passing settings from Terraform to the instance using features like EC2 `user_data`), and so the team is prioritizing investment in other parts of the application at this time.

Since we already have #353 open tracking the bigger use-case, we're going to close this out now. Sorry again for the slow response.
