### ISSUE TITLE
Regarding Path in the terraform (../)

### ISSUE THREAD

**Issue by ManasviMahalwar** [hashicorp/terraform#17171]
Hi All,

I am new to terraform and you can point me if this is already solved..

When I use Linux path node in terraform i.e. I like to refer main.tf outside the current folder which has main.tf with below one line only:

../main.tf

Whenever I write like that it gives me the error of indent, I am using Gitbash on Windows 10 and Ubuntu (I got the error on both). 
kindly suggest.

+++++

$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing C:\Users\manasvi.mahalwar\Documents\GitHub\test\infra\terraform\main.tf: At 1:1: expected: IDENT | STRING | ASSIGN | LBRACE got: PERIOD
++++++++

Regards, 
Manasvi

**Comment by jbardin** [comment]
Hi @ManasviMahalwar,

If I understand correctly, you have a `main.tf` file which only contains the text `../main.tf`?

Unfortunately that's not a valid configuration. You can find reference to the load order and syntax in the [configuration documentation](https://www.terraform.io/docs/configuration/index.html). 

In general, configuration files are grouped together by directory, and you want your working directory to be where the configuration for the root module resides.

**Comment by wrschneider** [comment]
I found this issue because of a related issue.

I had a module that was being pulled from Git, and there were symlinks inside that module.

On Windows, the symlinks were being translated to a one-line file with the target of the link.  That was breaking `terraform init`, and it had the appearance of looking like a one-line file with `../main.tf` should have worked.

**Comment by danscarf** [comment]
I've got a similar issue with Terraform on Windows. One of our modules has a file named common_variables.tf. The content of the file is:
`../variables.tf`

and during `terraform init` I get the same error as reported above.
`common_variables.tf: At 1:1: expected: IDENT | STRING | ASSIGN | LBRACE got: PERIOD`

**Comment by danscarf** [comment]
Hi @jbardin , should I open a new issue or should we re-open this one?

Thanks and regards,

**Comment by apparentlymart** [comment]
Hi @danscarf,

If I'm understanding correctly, you've got the same invalid config that was described in the original request here. In that case, the fix is to either delete your `common_variables.tf` file or update it to be valid. It seems like perhaps you were intending it to be a symlink rather than a regular file, which can work as long as all target systems where you will apply this configuration have operating systems and filesystems that support symlinks.

As @wrschneider mentioned, Git on Windows may not properly support symlinks, so since you are working on a Windows system you may need to avoid using symlinks in that way. You may also wish to try using Git inside [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), running Linux via Docker, if the configuration you are working with is assuming Unix symlink support.

(I don't actually know whether git under WSL can support symlinks; it may have similar problems if it is unable to map the symlinks to the underlying filesystem. You may be able to find someone with more experience with Git under Windows in [one of the community forums](https://www.terraform.io/docs/extend/community/index.html). We use GitHub issues for tracking bugs and enhancements; we may be able to help with certain simple problems here it's generally better to use the community forums where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.)
