### ISSUE TITLE
Error when destroy last openstack instance: output Resource 'openstack_compute_instance_v2.cluster' does not have attribute 'id'

### ISSUE THREAD

**Issue by jsecchiero** [hashicorp/terraform#17181]
Hi there!, here is the issue.

### Terraform Version
```
v0.11.2
```

### Terraform Configuration Files
```
# Create ssh keypair
module "keypair" {
  source = "github.com/entercloudsuite/terraform-modules//keypair?ref=2.4"
  ssh_pubkey = "${var.ssh_pubkey}"
  region = "${var.region}"
}

# Create ssh firewall policy
module "ssh" {
  source = "github.com/entercloudsuite/terraform-modules//security?ref=2.4"
  name = "ssh"
  region = "${var.region}"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  allow_remote = "0.0.0.0/0"
}

module "lan-influxdb" {
  #source = "github.com/entercloudsuite/terraform-modules//instance?ref=2.4"
  source = "instance"
  name = "lan-influxdb"
  region = "de-fra1"
  quantity = 0
  flavor = "e3standard.x3"
  network_name = "production-internal-network"
  sec_group = ["${module.ssh.sg_id}"]
  keypair = "${module.keypair.name}"
  tags = {
    "influxdb" = ""
  }
}
```

### Debug Output
https://gist.github.com/jsecchiero/f283c72ad4efa0a4d7646fa02fd6a6cc

### Expected Behavior
No errors

### Actual Behavior
Error when destroy last instance.
```
* module.lan-influxdb.output.instance: Resource 'openstack_compute_instance_v2.cluster' does not have attribute 'id' for variable 'openstack_compute_instance_v2.cluster.*.id'
```
Anyway the instance is destroyed

This line trigger the error:
https://github.com/entercloudsuite/terraform-modules/blob/867bd5cc6ffd3b1db4b165b9c34d8a2f514237d6/instance/main.tf#L7

### Steps to Reproduce
1. `terraform init`
2. `quantity = 1` # Create instance
3. `terraform apply`
4. `quantity = 0` # Destroy instance
5. `terraform apply`

**Comment by jbardin** [comment]
Hi @jsecchiero,

Unfortunately removing resources by setting `count = 0` can be tricky at times.
I'm not able to directly replicate this, since the modules referenced don't seem to be complete. 

The simple "splat" interpolation string `openstack_compute_instance_v2.cluster.*.id` usually works around the edge cases by returning an empty list when there aren't any resources, but obviously it's getting caught here. 

A quick look at the openstack provider doesn't look like it's doing anything incorrect for that resource type either.

If this is blocking you right now, you should be able to work around the issue by setting the `TF_WARN_OUTPUT_ERRORS=1` environment variable, which will prevent output errors from being fatal.

**Comment by jsecchiero** [comment]
Thanks @jbardin for the prompt reply.

If you want to replicate the complete module is in this [folder](https://github.com/entercloudsuite/terraform-modules/tree/867bd5cc6ffd3b1db4b165b9c34d8a2f514237d6/instance)

I think as a workaround i can use TF_WARN_OUTPUT_ERRORS=1
