### ISSUE TITLE
feat: allow module sources to use keybase

### ISSUE THREAD

**Issue by andrewrynhard** [hashicorp/terraform#17215]
Keybase offers encrypted git repos: https://keybase.io/blog/encrypted-git-for-everyone.
This could be a useful place to put modules that contain sensitive information. For example, using the kubernetes provider to create secrets in a cluster.

```
terraform init --backend-config=backend.tfvars
Initializing modules...
- module.secrets
  Getting source "keybase://team/X/Y"
Error downloading modules: Error loading modules: download not supported for scheme 'keybase'
```

**Comment by apparentlymart** [comment]
Hi @andrewrynhard! Thanks for this interesting feature request.

I'm not yet very familiar with this Keybase feature, but from reading the blog post you linked I _think_ this could work already if we can figure out what is the right syntax to put in the `source` argument, since behind the scenes Terraform is just running `git clone` here, and so the remote helpers should be usable.

If I understood correctly what's needed here, I think a `source` value like `git::keybase://team/X/Y` should work here, via the same mechanism that supports `git::ssh://...` and `git::https://...` .

If you happen to have a keybase git repo handy to test, could you give that a try and see if it works?

When it comes to directly supporting this by recognizing the `keybase` URL scheme natively, I'm not close to those but I'm a little concerned about adding more patterns to the [already-quite-complex module source pattern set](https://www.terraform.io/docs/modules/sources.html), and it also feels a little "obscure" to access a git repository without the word "git" appearing anywhere in the configuration. (This is different for the `git clone ...` command line because the context is already clearly a git repository.) I'd prefer to wait and see what usage emerges around the `git::keybase://` form -- assuming that works as I expect -- before we consider adding a shorthand special-case for it.

Thanks again for pointing this out! It does look pretty cool.

**Comment by andrewrynhard** [comment]
Thanks @apparentlymart! Looks like the following works:
```
source = "git::keybase://team/X/Y"
```
I think this is fine and don't really see the need to support natively.

**Comment by apparentlymart** [comment]
Great! Thanks for trying it out and following up, @andrewrynhard.

Since we're not going to do anything further for this right now, I'm going to close this issue. We'll keep an eye out for if this becomes a common question and, if so, document it more explicitly in the module sources docs.
