### ISSUE TITLE
Terraform removes and reapplies OpenStack security group when no changes are necessary

### ISSUE THREAD

**Issue by davebiffuk** [hashicorp/terraform#17268]
### Terraform Version

```
Terraform v0.11.3
```

### Terraform Configuration Files

```hcl
  security_groups = ["${openstack_networking_secgroup_v2.secgroup.id}"]
```
Full template is at https://gist.github.com/davebiffuk/7447d3edb81aef94a81b37c672c12c1e

### Debug Output

https://gist.github.com/davebiffuk/dbb9ea59be4da51262b24294bdd25360

### Crash Output

(no crash)

### Expected Behavior

Terraform should notice that the security group is unchanged, and not make changes to the running instance.

### Actual Behavior

When applying an unchanged plan, Terraform removes and reapplies the security group to the running instance, even though no change is necessary. This is possibly because OpenStack is reporting the instance's current security group by name, and the Terraform template refers to it by ID.

### Steps to Reproduce

Using the template at https://gist.github.com/davebiffuk/7447d3edb81aef94a81b37c672c12c1e (and appropriate credentials:

1. `terraform init`
2. `terraform apply`
3. `terraform apply`

and note that the second apply causes changes, though the template has not been changed.

### Additional Context

Referring to the security group by name prevents this misbehaviour.

**Comment by apparentlymart** [comment]
Hi @davebiffuk! Sorry for this odd behavior.

In the output you provided I see the following plan:

```
openstack_compute_instance_v2.dh3tf
      security_groups.2874544763: "tf_wideopen" => ""
      security_groups.540877331:  "" => "47d4ae75-9802-4d16-8b13-c343b84c7e28"
```

This looks like an issue in the OpenStack provider itself where either the provider or the remote API is "normalizing" the UUID you provided into a name, which then appears to Terraform as a diff on the next run.

I'm going to have our issues bot re-open this issue in the OpenStack provider repository, since I believe the fix for this must be made over there.

Thanks!
