### ISSUE TITLE
Can not init backend S3

### ISSUE THREAD

**Issue by vinhnglx** [hashicorp/terraform#17295]
Hi there,

My terraform version is 0.11.3, and I'm going to run `terraform init` with backend S3. I'm following the [documentation](https://www.terraform.io/docs/backends/types/s3.html). And I'm facing the issue

```
Error configuring the backend "s3": 1 error(s) occurred:

* : invalid or unknown key: terraform
```

Here is my configuration 

```
# backend.tf

terraform {
  backend "s3" {
    bucket = "sample-ops"
    region = "ap-southeast-1"
  }
}
```

The command: `terraform init -backend=true -backend-config=backend.tf`

The full log when I run the command:

```
terraform init -backend=true -backend-config=backend.tf
Initializing modules...
- module.registry
- module.registry.admin_ecr

Initializing the backend...
key
  The path to the state file inside the bucket

  Enter a value: sample.tfstate

Error configuring the backend "s3": 1 error(s) occurred:

* : invalid or unknown key: terraform
```

**Comment by nicholasjackson** [comment]
I think the key the error message is referring to is the bucket key which is a required parameter:

```
terraform {
  backend "s3" {
    bucket = "mybucket"
    key    = "path/to/my/key"
    region = "us-east-1"
  }
}
```

**Comment by vinhnglx** [comment]
@nicholasjackson yeah, I also tried your suggestion before I try to delete the `key` and enter the value for key from the terminal.

**Comment by nicholasjackson** [comment]
@vinhnglx could you re run your init command please and add `TF_LOG=DEBUG`and paste the contents.  Please make sure that you redact any sensitive info in the logs.

What happens if you just run a `terraform init` without specifying any flags?

**Comment by jbardin** [comment]
Hi @vinhnglx

Yes, this is rather confusing output because of a couple of combined issues. 

You're missing the `key` value in the config, which was noted above, and is causing terraform to prompt you to enter a value. 

You then pass in `-backend-config=backend.tf`, which isn't a backend configuration and is already being read by terraform. The `terraform` block isn't a valid part of a backend config, which is what is returning the `invalid or unknown key: terraform`. If you do want to pas in extra parameters to `-backend-config` from a file, the file needs to be a set of key=value pairs, in the same format as a tfvars file. 

You never need to specify `-backend=true`, since true is the default value for the flag.

**Comment by vinhnglx** [comment]
@jbardin thanks, man. I understand. I added 

```
terraform {
  backend "s3" {}
}
```

to my `main.tf` file and my backend config is a key=value pairs file. And then I can run `terraform init -backend-config=backend.tfvars`. It works perfectly.
