### ISSUE TITLE
cidrhost function doesn't work with subnetting

### ISSUE THREAD

**Issue by pipoe2h** [hashicorp/terraform#17331]
### Terraform Version

```
Terraform v0.11.3
...
```

### Terraform Configuration Files

```
module "compute" {
    source = "modules/compute"
    vmw_virtual_machine_network_address = "172.17.135.128/26"
    vmw_virtual_machine_gateway = "172.17.135.129"
    vmw_virtual_machine_ip_address_start = "130"
}

resource "vsphere_virtual_machine" "worker" {

 ...omitted...

  clone {

...omitted...

      network_interface {
        ipv4_address = "${cidrhost(var.vmw_virtual_machine_network_address, var.vmw_virtual_machine_ip_address_start + count.index)}"
        ipv4_netmask = "${element(split("/", var.vmw_virtual_machine_network_address), 1)}"
      }
    }
  }
}
...
```

### Debug Output

[https://gist.github.com/pipoe2h/bdf333cbbd59c89b78c232e0799b7af1](https://gist.github.com/pipoe2h/bdf333cbbd59c89b78c232e0799b7af1)

### Crash Output

[https://gist.github.com/pipoe2h/1b297bffae212dc74578801a823e9487](https://gist.github.com/pipoe2h/1b297bffae212dc74578801a823e9487)

### Expected Behavior

The function should work since the subnetting is correct

### Actual Behavior

The Terraform plan fails. It looks like the function only works when the last octet value on the network is 0.

On this example the subnet is 172.17.135.128/26.

### Steps to Reproduce

You just need to use the function cidrhost like as follow:
${cidrhost("172.17.135.128/26", 130)}

**Comment by apparentlymart** [comment]
Hi @pipoe2h! Sorry for the confusing behavior here.

As far as I can tell, the error message you're seeing here is correct. Your network address has a prefix length of 26 bits, which leaves only six bits remaining for the host number:

```
10101100.00010001.10000111.10 HHHHHH
11111111.11111111.11111111.11 000000
```

You are assigning host numbers starting at 130, which is `10000010` in binary and thus requires eight binary digits to represent.

To make this work, you have two options:

* Shorten the network prefix to `/24`, which will then leave the full eight bits to assign in that host number of 130. `cidrhost("172.17.135.0/24", 130)` -> `172.17.135.130`
* Start your host numbering at 2, which is `000010` when expressed as six binary digits, and that will then combine with the leading `10` bits in your network prefix to produce `10000010` so that the final octet will be 130 when expressed in decimal. `cidrhost("172.17.135.128/26", 2)` -> `172.17.135.130`

The key here is that the `cidrhost` function thinks of the host number as being an _n_-bit integer, where n is 32 minus the prefix length. It doesn't "think about" the octets you see in the decimal representation of an IP address, since the purpose of this `cidr...` family of functions is to make it easier to calculate networks and addresses that _don't_ fall on the octet boundaries, without needing to so the necessary bitwise arithmetic manually in the expression language. (Indeed, there are no bitwise arithmetic operators in the language, so this would not be possible any other way.)

I hope that helps! Please let me know if I've misunderstood what you were trying to do here.

**Comment by pipoe2h** [comment]
Hi @apparentlymart ,

Thanks for the detailed explanation. I thought it was decimal and there the confusion.

I'll give a try with the second approach since I want to reuse the mask for the ip4_netmask attribute:
`ipv4_netmask = "${element(split("/", var.vmw_virtual_machine_network_address), 1)}"`

If I choose the first approach it will have inconsistent connectivity with hosts on the same network range but different mask.

Regards,
Jose
