### ISSUE TITLE
feature request: prerequisite flag on data sources

### ISSUE THREAD

**Issue by GeoffMillerAZ** [hashicorp/terraform#17388]
I think it would be useful to add a flag to all data sources allowing them to be indicated as a prerequisite. For example, what if I have a password for a RDS instance that I will be storing in a ssm secure string. I put in my readme that you must manually create the secure string ssm parameter and have it in the expected path/name. Then I have a data source that pulls the value of that ssm secure string and uses it in my module for the RDS password so I don't have secrets in my code.

It would be nice to be able to indicate that certain data sources are prerequisites and have terraform check that immediately and fail the job if it doesn't exist. It could even be useful to have another field that allows for a custom message to appear if that resource doesn't exist. Like:

```
Prereq check failed!
Please see the README.md on this module. A ssm secure string located in /env/region/vpc/rds/password is required for module tf_module_myrds.
```

```
data "aws_ssm_parameter" "foo" {
  name  = "/env/region/vpc/rds/password"
  type    = "SecureString"

  prereq = {
    message = "Please see the README.md on this module. A ssm secure string located in /env/region/vpc/rds/password is required for module tf_module_myrds"
  }
}
```

This is admittedly a low priority feature. Just thought of it while I was explaining stuff to a coworker.

**Comment by apparentlymart** [comment]
Hi @GeoffMillerAZ! Thanks for this feature request.

I'm a little confused by the use-case since it should _already_ be true that if the object referenced by a `data` configuration does not exist then Terraform will fail with an error message. Are you finding that this isn't true for the `aws_ssm_parameter` data source? If so, there may be a bug in this data source that's preventing it from failing as expected.

The ability to set a custom error message for a data source failing is an interesting idea. I suppose we could show it in addition to any error message provided by the remote service, as additional context for situations where there's a specific step required in order to resolve the problem.

**Comment by GeoffMillerAZ** [comment]
I should have saved the apply output. I'll see if I can get it to reproduce and get you that but a coworker was saving passwords manually in ssm and then had terraform make a data source to get that password and pass it to a resource to keep secrets out of the code base. It then proceeded to do applies and then eventually failed. I guess it's not that big of a deal since it does eventually fail and not really cause harm. I was more just saying it could check this type of thing sooner.
