### ISSUE TITLE
OpenStack Swift state, support for clouds.yaml

### ISSUE THREAD

**Issue by avoidik** [hashicorp/terraform#17392]
OpenStack provider already supports clouds.yaml as the configuration source. It would be great if the same mechanics will be adopted to Swift state storage backend.

https://github.com/terraform-providers/terraform-provider-openstack/pull/154
https://github.com/terraform-providers/terraform-provider-openstack/issues/122

**Comment by jgraichen** [comment]
This has been working for us for a while already:

```tf
terraform {
  backend "swift" {
    cloud             = "project-name"
    container         = "terraform-state"
    archive_container = "terraform-state-archive"
    state_name        = "project-name.tfstate.tf"
  }
}

provider "openstack" {
  cloud = "project-name"
}
```

**Comment by jhg03a** [comment]
Considering that the swift backend is deprecated and from my testing broken in newer terraform releases, I leverage the S3 compatibility of swift instead.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Swift backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
