### ISSUE TITLE
Enable Caching

### ISSUE THREAD

**Issue by tusharmath** [hashicorp/terraform#17405]
### Terraform Version

```
Terraform v0.11.3
```

### Expected Behavior
`terraform init` command should download provider packages only once and cache it somewhere.

### Actual Behavior
Every time `terraform init` is called the provider is re-downloaded

### Steps to Reproduce
1. Run `terraform init` 
2. Delete `.terraform`
3. Again run `terraform init` [Takes the same amount of time as the first time]

**Comment by apparentlymart** [comment]
Hi @tusharmath!

There is [an opt-in caching mechanism](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) already available. We do not enable this by default because Terraform does not want to silently install files to locations outside of the target working directory without user consent.

**Comment by tusharmath** [comment]
Thanks a tone!
