### ISSUE TITLE
Document "value of 'count' cannot be computed"

### ISSUE THREAD

**Issue by eschwartz** [hashicorp/terraform#17421]
[Based](https://github.com/hashicorp/terraform/issues/15172) on the [number](https://github.com/hashicorp/terraform/issues/10857) of [issues](https://github.com/hashicorp/terraform/issues/12570) [related](https://github.com/hashicorp/terraform/issues/13980) to this [terraform](https://github.com/hashicorp/terraform/issues/15471) [bug](https://github.com/hashicorp/terraform/issues/17287), I'd say this is a fairly common problem people are running into.

I know the current line is "this will be addressed in HCL 2.0" (which I fully understand, and I'm greatly looking forward to). But can we at least document this bug in [_Configuring Resources > Using Variables with Count_](https://www.terraform.io/docs/configuration/resources.html#using-variables-with-count).

We have [a decent workaround in place](https://github.com/hashicorp/terraform/issues/10857#issuecomment-368059147), but it is not at all obvious. Would it be possible to point users to this workaround in the docs?

**Comment by pixelicous** [comment]
encounter this as well, azurerm provider verified compute module, cannot pass an image id from a datasource, it just fails on the same error as everyone else

**Comment by colindean** [comment]
I just got bit by this hard, losing several hours because I was _sure_ that I, a Terraform newb, was misconfiguring something. Documenting this is important; I've tried to document my own thrashing on it in https://github.com/Eiara/terraform_container_definitions/issues/3. The proposed workarounds aren't working for me even when making local changes to that module.

**Comment by colindean** [comment]
I ended up working around the problem in my particular case by templating environment variables and applying the template with the real environment variables: https://github.com/Eiara/terraform_container_definitions/issues/3#issuecomment-401448102

**Comment by simonmacklin** [comment]
Sounds good 

Many thanks

**Comment by alex-gottschalk-roostify** [comment]
very annoying and fragile behavior.  My use case is provisioning security group rules.  I would like something like this:

    resource "aws_security_group_rule" "sg" {
        count = "${length(var.source_security_groups})"
        source_security_group_id = "${var.source_security_groups[count.index]}"
        [... other params ...]
    }

**Comment by mildwonkey** [comment]
Hi all! Sorry for the long silence here.

We have updated the [resource count documentation](https://www.terraform.io/docs/configuration/resources.html#count-multiple-resource-instances) to explain this limitation in detail, and terraform v0.12 also outputs a much clearer error message in this case.

I am going to close this specific issue, since the documentation has been updated. If you are interested in the count limitation, I suggest you follow (and 👍) #12570. Thank you!
