### ISSUE TITLE
Global Variable Namespace

### ISSUE THREAD

**Issue by wazoo** [hashicorp/terraform#1742]
Instead of passing variables in and out of modules it seems like it would be interesting if there was a global namespace, so I could do something like:
```
module "test_core" {
source = "./test"
subnet = "10.10.10.0/24"
vpc_id = "xxxxxxxxx"
}
```
Then in the module something maybe like:
```
resource "aws_subnet" "sub_public_a" {
  vpc_id                  = "${var.vpc_id}"
  availability_zone       = "us-west-1"
  cidr_block              = "${var.subnet}"
  map_public_ip_on_launch = false
  register_global = true
}
```

which might let me do this in another module:
```
resource "aws_instance" "is_test_n01" {
  .....
  subnet_id             = "${global.sub_public_a.id}"
  .....
}
```
This would save a lot of time and keep code modular, it would also make sure that you have some uniqueness globally.  It also would be cool to be able to protect things from getting re-defined (or allow it), for example if I have a module that contains a firewall that re-defines the public subnet.

**Comment by wazoo** [comment]
Thinking more about this, it might make more sense to just make a global variable scope option like such:
```
variable "sub_public_a_id" {
value = "${aws_subnet.sub_public_a.id}"
global = true
}
```

**Comment by phinze** [comment]
Hi @wazoo! This is a very interesting idea, but I think that ultimately it would be the wrong move for Terraform's modularity. We were intentional about our choice to force module inputs and outputs to be explicitly declared (via `variable {}` and `output {}`, respectively). While this does make for more verbose config, it has the benefit of making every module's dependencies very clear.

If it were possible to reference out to a global namespace on any line of config, it would mean the only way to be sure of a module's dependencies would be to read all its source code, which goes against the "black box of config" concept that modules were designed around.

I'm happy to chat more with you on this thread about the problems you're trying to solve with this idea to see if there's another strategy we can bring to bear - but in the meantime I'm going to close the issue because I don't believe a global namespace is the direction we'll take.

**Comment by wazoo** [comment]
That is a great point.  I actually thing with the introduction of templates this solves my problem as I was having to use modules as templates previously (to build a prod/stage environment) but I think I can refactor now using templates and it will be perfect.

**Comment by jdblack** [comment]
@phinze  I would be very  happy to have a conversation with you on this issue!   The current variable scoping for terraform has been very painful for us.     We have a large number of cross dependencies, and it's just killing us....
