### ISSUE TITLE
'invalid endpoit' when passing module output variables to provider.docker.host

### ISSUE THREAD

**Issue by Nopx** [hashicorp/terraform#17420]
### Terraform Version
```
Terraform v0.11.3
```

### Terraform Configuration Files
```hcl
module "google_server" {
	source="google_module"
	name_machine = "server"
}

provider "docker" {
	alias="abc"
	host="tcp://${module.google_server.ip_address[0]}:2375"
}

resource "docker_container" "container" {
	provider = "docker.abc"
	...
}

...

provider "google" {
	...
}

resource "google_compute_instance" "vm" {
        ...
}

output "ip_address" {
  value = "${google_compute_instance.vm.*.network_interface.0.access_config.0.assigned_nat_ip}"
}
```

### Debug Output
Error: Error running plan: 1 error(s) occurred:
\* module.docker.provider.docker.abc: Error initializing Docker client: invalid endpoint

### Expected Behavior
The docker provider and resource are provisioned on the VM. The docker host is resolved once the VM is up and running.

### Actual Behavior
The 'plan' step fails with the message "Error initializing Docker client: invalid endpoint"

### Steps to Reproduce
1. `Create module that produces an output`
2. `Create a docker provider`
3. `Use the module's output for the 'host' argument of the docker provider`
4. `terraform init`
5. `terraform apply`

### Workaround
Use remote execution to execute Docker commands on the VM.

**Comment by apparentlymart** [comment]
Hi @Nopx! Sorry this didn't work as expected.

The issue you're describing here is the one discussed in #4149. We plan to address that at some point after we complete the current work to improve the configuration language interpreter, but in the mean time the usual workaround is to use the `-target` argument to force Terraform to create the docker server before trying to use the docker provider against it, like this:

```
$ terraform apply -target=module.google_server
# ... works only on the resources required by that module ...
$ terraform apply
# ... now works on all resources, with the server IP address already known from the previous step ...
```

Since we already have #4149 open to represent this issue, I'm going to close this just to consolidate the discussion. Thanks for reporting this!
