### ISSUE TITLE
ccccccgnbubkejigefgvnrehtgikhjietdlbcjcfjdnl

### ISSUE THREAD

**Issue by anders-awelyn** [hashicorp/terraform#17433]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by radeksimko** [comment]
Hi @anders-awelyn ,
I assume this issue was created accidentally by pressing a Yubikey button.

FYI - if you're running on MacOS I'd suggest looking at https://github.com/pallotron/yubiswitch which may prevent situations like this. 😉 

I'm going to close this, but if there's any particular genuine issue you wish to report you're more than welcomed to do so.
