### ISSUE TITLE
Terraform init downloads 2 different version of azure plugins

### ISSUE THREAD

**Issue by sibh8** [hashicorp/terraform#17469]
Hello,

I am trying to execute terraform from jenkins and its failing with the following error.

* provider.azure: Insufficient configuration data. Please specify either a 'settings_file'
or both a 'subscription_id' and 'certificate'.

On further debuging, I found that the error is mainly because of the plugins getting downloaded during terraform init. Following is the log for terraform init.

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "azure" (0.1.1)...
- Downloading plugin for provider "azurerm" (1.1.2)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.azure: version = "~> 0.1"
* provider.azurerm: version = "~> 1.1"

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

However, the jenkins builds that have been successful gives following output for terraform init.
Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.[0m

[0m[1mInitializing provider plugins...[0m
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "azurerm" (1.1.2)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.azurerm: version = "~> 1.1"

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary

Please help me understand the root cause as to why 2 plugins are getting downloaded where previously there was only one. Also I feel that provider azure is deprecated as it referred to the Azure classic portal.

**Comment by tombuildsstuff** [comment]
hi @sibh8 

Thanks for opening this issue

Terraform will download Providers which are either referenced explicitly in a Provider block, as shown below:

```
provider "azure" {
  # ...
}
```

.. or that are referenced as Resources or Data Sources - which it does by checking the prefix of the Resource/Data Source type and downloading the relevant provider (e.g. `azurerm_resource_group` will download the `azurerm` provider). Given Terraform's downloading both Providers my guess would be that there's a Resource or a Data Source from the older Azure (Classic) Provider - but it's not possible to tell without looking at your Terraform Configuration.

Would you be able to take a look at your Terraform Configuration and see if there's any references to the older Azure (Classic) provider (resource names which use the prefix  `azure_`)?

Thanks!

**Comment by sibh8** [comment]
Hello,

Thanks for the reply. I had used a resource azure instead of azurerm for nsg creation. It has been resolved now. Please close the issue.

Thanks
sibh8

**Comment by tombuildsstuff** [comment]
@sibh8 great to hear, thanks for confirming :)

**Comment by RamlaBen** [comment]
hi

please, I want to deploy an infra with config terraform using jenkins. and I can not configure it.it shows me


Démarré par l'utilisateur unknown or anonymous
Building in workspace C:\Program Files (x86)\Jenkins\workspace\project
[terraform-plugin] $ "C:\Program Files (x86)\Jenkins\tools\org.jenkinsci.plugins.terraform.TerraformInstallation\terraform1\terraform.exe" get
[terraform-plugin] $ "C:\Program Files (x86)\Jenkins\tools\org.jenkinsci.plugins.terraform.TerraformInstallation\terraform1\terraform.exe" apply -input=false "-state=C:\Program Files (x86)\Jenkins\workspace\project\terraform-plugin\terraform-plugin.tfstate"
[0m[1m[33mPlugin reinitialization required. Please run "terraform init".[0m
[33mReason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

[0m[31m1 error(s) occurred:

* provider.azurerm: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

[0m[33mTerraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".
[0m
[31m
[1m[31mError: [0m[0m[1merror satisfying plugin requirements[0m

[0m[0m[0m
FATAL: java.lang.Exception: Terraform Apply failed: 1
	at org.jenkinsci.plugins.terraform.TerraformBuildWrapper.executeApply(TerraformBuildWrapper.java:249)
	at org.jenkinsci.plugins.terraform.TerraformBuildWrapper.setUp(TerraformBuildWrapper.java:269)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Finished: FAILURE

**Comment by sibh8** [comment]
Hello,

Please can you share your terraform file

Thanks and regards
Siddhesh Bhandarkar
