### ISSUE TITLE
Habitat provisioner should be idempotent

### ISSUE THREAD

**Issue by smartb-pair** [hashicorp/terraform#17486]
There are some cases where an operator might use a `null_resource` together with the Habitat provisioner to reconfigure Habitat services on a running host. For this reason we think the Habitat provisioner should be idempotent - that is, not fail if services (or a subset of services) on the host already match the state defined in our Terraform code.

Happy to discuss if this violates provisioner principles.

cc: @nsdavidson & @bixu

**Comment by apparentlymart** [comment]
Hi @smartb-pair,

Provisioners are usually _not_ idempotent _in general_ because they are arbitrary actions. However, if there's a meaningful idempotent usage model for Habitat then it seems reasonable to support it for this provisioner in particular, as an extra guarantee.

The Terraform team at HashiCorp does not currently have in-house expertise with Habitat, but if you or the other contributors to the provisioner have some thoughts on what might make sense here I'm happy to provide context/feedback to help work towards a plan here.

My main concern would be making sure that the behavior can be described in a straightforward way so users know what to expect, since complex provisioners can often be hard to debug when they behave in an unexpected way. You all certainly know better than I do what a Habitat user would expect though, so I'd love to hear your ideas!

**Comment by arashzandi** [comment]
@apparentlymart, there's a boolean we could support, `--force` in the Habitat CLI, that would allow for this. The responsibility for correctness and graceful handling of service updates/reload then rests with the Habitat Supervisor and the Terraform Provisioner would just pass the `force` option to our service(s): https://www.habitat.sh/docs/habitat-cli/#hab-svc-load

We just ran into this again today, but now that Habitat has it's own way to dealing with this the change seems pretty straightforward?

cc: @bixu

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, Habitat, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested.

For the time being, the best option if you want to see this built, is to build a standalone habitat provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. 

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
