### ISSUE TITLE
Terraform State Show: Returns 0 on not found

### ISSUE THREAD

**Issue by nbering** [hashicorp/terraform#17516]
### Terraform Version

```
Terraform v0.11.3
```

### Terraform Configuration Files
Nothing specific needed.

### Expected Behavior

If I run `terraform state show` against a resource that does not exist, the return code should be non-zero (error) so that scripts will fail if the resource does not exist.

### Actual Behavior

Running terraform state show on a non-existent resource fails silently.

### Steps to Reproduce

```
$ terraform state show foo.bar
$ echo $?
0
```

### Additional Context

Not sure if you consider this a bug, or a feature.

**Comment by apparentlymart** [comment]
Hi @nbering! This is a good idea.

I suppose it behaves the way it does because this command can potentially return _multiple_ resources, if e.g. you request a module, and arguably requesting an _empty_ module isn't an error, while requesting a non-existent one should be.

It seems right to me in principle that we should return an error if the object being directly requested on the command line doesn't exist. Unfortunately that will probably require some rethinking of how this command works so that it's able to distinguish "does not exist" situations from "empty" situations.

We've been planning to do another iteration of the machinery that `terraform state show` relys on -- resource addresses, state filters, etc -- and so I'd consider this a good use-case for that work, when we get there.

In the mean time, as a stop-gap measure, I think it'd be reasonable to have a special case in this command where if the given resource address exactly specifies a resource (effectively, if its `Name` field is non-empty) then we return an error if there are no results, but for now we'd continue to consider it a success if a less-granular address is used, such as a module-path-only address. Would that get you what you need here?

Unfortunately the Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd love to review a pull request if you or someone else has the time and motivation to implement it.

**Comment by nbering** [comment]
No problem. I have other ways to work around this for now (counting lines in output, for example). I just felt this break from typical command return code conventions should be reported.

Thanks for your time, and keep up the amazing work!

**Comment by nbering** [comment]
Thanks @DJAlPee.

This issue is so old that I didn't even remember creating it. 😄  Good catch, and yes... I'll proactively close it.
