### ISSUE TITLE
Terraform graph on a particular module?

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#17576]
I am not sure if we can terraform graph on a particular module.

Something like

```bash
$ terraform graph -type=plan -module=<module_name>
```

This command does not work in v0.11.3 (latest as on date).

**Comment by jbardin** [comment]
Hi @vikas027,

Modules don't really exist in the graph itself, they are just an abstraction for configuration. Since the graph is the description of the dependencies between individual resources, a module is often not a discrete subgraph of the entire graph to begin with. This means that whatever method one would use to create a graph of a "module", it may not be representative of the dependencies in the graph as a whole.

The easiest option is probably to treat the module as a root module for the purpose of creating the graph output, though you'll of course need to provide any variables being passed in manually. Temporarily running `init` from within the module itself, then `graph` should give you something usable. 

Once we have support for `-target` in the graph command (#17290), it might make sense to create the graph from based on targeting the module resources you're interested in, though this again would likely create a slightly different graph from the previous method too.
