### ISSUE TITLE
Error Refreshing State

### ISSUE THREAD

**Issue by polireddynakka** [hashicorp/terraform#17583]
### Terraform Version

```
...Terraform v0.11.3
```

### Terraform Configuration Files

```hcl
...
```
###OUTPUT
Error refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 

can any one help me regarding this error !

**Comment by bflad** [comment]
Hi, @polireddynakka. 👋  Sorry you ran into trouble here.

Questions for you to hopefully narrow this down a little:
* Did you modify the state file in S3 at all? (manually or with the Terraform CLI)
* Can you describe what you see in the state file in S3? (is it empty or very empty JSON contents or large JSON contents?)

You may also be able to find out or provide additional information by enabling [debug logging](https://www.terraform.io/docs/internals/debugging.html).

**Comment by ibrokethecloud** [comment]
I have run into a similar issue as well.

I have tried both TF version 0.11.3 and 0.11.5

The trace log indicates that TF cannot query the s3 object:

2018/03/31 05:51:13 [DEBUG] [aws-sdk-go] DEBUG: Validate Response s3/GetObject failed, not retrying, error NoSuchKey: The specified key does not exist.

However i can see the file in s3 bucket and it does look to have valid content.

**Comment by ibrokethecloud** [comment]
Turns out the issue was that the `init` command tries to look up the state file available at the root "/" of the s3 bucket. Because the workspace has not been switched yet the error happens.

I fixed this by putting a dummy state file at / in the s3 bucket and associated key in dyanamodb and that works fine.

**Comment by patil16nit** [comment]
I faced the same issue but just updating the Digest value in dynamo db helped me out.

**Comment by SARUNAR** [comment]
Me too, faced the same issue?
 refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value:

Is any worked around this?

**Comment by SARUNAR** [comment]
> Me too, faced the same issue?
> refreshing state: state data in S3 does not have the expected content.
> 
> This may be caused by unusually long delays in S3 processing a previous state
> update. Please wait for a minute or two and try again. If this problem
> persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
> to manually verify the remote state and update the Digest value stored in the
> DynamoDB table to the following value:
> 
> Is any worked around this?

I fixed the issue by updating the digest in dynamodb state file

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. This seems to have been a question and not a bug in terraform.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!

**Comment by SARUNAR** [comment]
Thanks
