### ISSUE TITLE
element list check doesn't account context.

### ISSUE THREAD

**Issue by omeid** [hashicorp/terraform#17617]
Considering the conditional, the error makes no sense.

```bash
Error: Error refreshing state: 1 error(s) occurred:

* module.node-sydney.module.db_core.output.identifier: element: element() may not be used with an empty list in:

${aws_db_instance.this.count == 0 ?  "" : element(aws_db_instance.this.*.identifier, 0)}

```

**Comment by jbardin** [comment]
Hi @omeid,

Sorry you were tripped up by this. Since the `*` operator may return an empty list, we usually suggest wrapping it in a `concat`, like so `concat(aws_db_instance.this.*.identifier, list(""))`. This ensure that a valid value is always passed to `element`.

I'm not sure I understand the issue title though, since element doesn't have any context to take into account, and can only error if it's passed an invalid argument. If you're referring to the fact that element is called at all if the first expression is true -- conditional statements are not short-circuiting. Adding that feature is already a planned enhancement for the the configuration language. 

I'm going to close this issue out, since everything described here is working as expected.

**Comment by cornfeedhobo** [comment]
@jbardin I don't think your assessment is correct and would be happy to open another ticket. Consider the following:

```hcl-terraform
variable "foobar" {
  default = 0
}

resource "null_resource" "foobar" {
  count = "${var.foobar}"
}

output "foobar" {
  value = "${element(concat(null_resource.foobar.*.id, list("")), 0)}"
}
```

This results in:
`terraform apply -var='foobar=1' -auto-approve`
```
null_resource.foobar: Creating...
null_resource.foobar: Creation complete after 0s (ID: 2667543645679167593)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

foobar = 2667543645679167593
```

Then remove the resources and hit the error:
`terraform apply -var='foobar=0' -auto-approve`
```
null_resource.foobar: Refreshing state... (ID: 2667543645679167593)
null_resource.foobar: Destroying... (ID: 2667543645679167593)
null_resource.foobar: Destruction complete after 0s

Error: Error applying plan:

1 error(s) occurred:

* output.foobar: Resource 'null_resource.foobar' does not have attribute 'id' for variable 'null_resource.foobar.*.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by jbardin** [comment]
Hi @cornfeedhobo,

That's a different error condition, which is covered in #17464, and should be fixed in the latest release.

**Comment by cornfeedhobo** [comment]
@jbardin Cornfirmed ;-)  Thank you very much for the prompt response!
