### ISSUE TITLE
Terraform plan output is not sorted properly

### ISSUE THREAD

**Issue by omeid** [hashicorp/terraform#17619]
Currently when terraform displays a plan (whatever using plan function or asking for approval for apply or destroy), it does not list the actions in the order that it will _need_ and _will_ do the actions, this makes reading through the plan a bit hard as you have to jump up and down trying to piece together the whole picture.

I could add an example, but it is very general and applies to just about any non-trivial (has dependencies, implicit or explicit) configuration.

**Comment by apparentlymart** [comment]
Hi @omeid!

As you've seen, the output is currently sorted by resource address with the intent that it's therefore easy to find a particular item in the list if you know its address. It sounds like you'd prefer to have Terraform do a topological sort so that the list is approximately the graph traversal order. (It can't be _exactly_ that order because some actions will execute concurrently and so the execution sequence is not deterministic.)

From the way you described it, I think what you're doing here is reading the plan for a particular resource and then want to refer to the resources it depends on in order to see what the resulting value might be, and you'd find that easier to do if the dependencies were close to their dependents in the ordering. Is that right?

**Comment by omeid** [comment]
Hello!

> As you've seen, the output is currently sorted by resource address with the intent that it's therefore easy to find a particular item in the list if you know its address. It sounds like you'd prefer to have Terraform do a topological sort so that the list is approximately the graph traversal order. 

Yes. :)

> (It can't be exactly that order because some actions will execute concurrently and so the execution sequence is not deterministic.)

That is fine, as long as dependent items are list after their dependencies and group together.

- resource.main
- resource.child.a   `<- depends on main`
- resource.otherchild.a  `<- depends on child.a`
- resource.child.b  `<- depends on main`
- resource.otherchild.b  `<- depends on child.b`
- resource.child.extra
- resource.alt
- resource.alt.dep `<- depends on alt`
 
and so forth.



> From the way you described it, I think what you're doing here is reading the plan for a particular resource and then want to refer to the resources it depends on in order to see what the resulting value might be, and you'd find that easier to do if the dependencies were close to their dependents in the ordering. Is that right?

While being able to find a particular resource dependents and figuring out the resulting value is often useful, the main pain point for me is when confirming/validating a large plan, specially the first time.

That is, I work with somewhat large plans and want to read-through/confirm the plan, the current sorting order makes this fairly hard as I have to go up and down trying to piece together the whole picture. In fact, I often grab a pen and paper to do this now. I believe topological sort would make this easier.

Hope that makes sense.

**Comment by amckenna-pinterest** [comment]
Looks like someone has written a tool to make diff display a little more intuitive:  https://github.com/coinbase/terraform-landscape

https://stackoverflow.com/questions/43532785/can-terraform-plan-show-me-a-json-diff-for-a-changed-resource

**Comment by AMMullan** [comment]
Yeah I'm seeing the same thing - a plan on something like an IAM Policy sorts everything which isn't ideal because we should be seeing it exactly how it's written in the TF, not sorted (got quite confused as to why it's sorting it and now PRESUME that it's not actually going to deploy it liket hat)....

This issue hasn't been updated in almost 2 years - is there anything actively happening to resolve ?
