### ISSUE TITLE
Crash caused by braces instead of "map" in variable type declaration

### ISSUE THREAD

**Issue by willemveerman** [hashicorp/terraform#17629]
This isn't really a bug since the user must do something incorrect in order to trigger it, but I thought I would notify you anyway because the app doesn't handle the situation gracefully and just outright crashes.

In a variable definition, if you declare a type value to be literally a pair of curly braces - i.e. {} - instead of the correct value - "map" - terraform will crash.

Any other incorrect value - such as [] - will throw an insightful error message.

### Terraform Version

```
0.11.4
```

### Terraform Configuration Files

```hcl
data "aws_iam_user" "example" {
  user_name = "${var.un}"
}

variable "un" {
  description = "user name"
  type        = {}
}
```

### Crash Output

https://gist.github.com/willemveerman/6ffbfce508812e9d4c5847136c81b063#file-crash-log

### Expected Behavior

Error message with insight as to the cause.

### Actual Behavior

Crash - see gist.

### Steps to Reproduce

Paste code above into a new file, save with `.tf` extension, run `terraform plan`.

**Comment by apparentlymart** [comment]
Hi @willemveerman! Sorry for this crash, and sorry for the slow response.

We've been working for several months now on a new implementation of the configuration language that is more robust in how it processes configuration. I just tried your example in the v0.12.0-alpha1 prerelease build and verified that this problem is now fixed:

```
$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid type specification

  on invalid-variable-type.tf line 7, in variable "un":
   7:   type        = {}

A type specification is either a primitive type keyword (bool, number, string)
or a complex type constructor call, like list(string).
```

This fix is now in master ready to be included in the forthcoming v0.12.0 final release, so I'm going to close this out. Thanks for reporting this, and sorry again for the long delay in replying.
