### ISSUE TITLE
Terraform JSON config not working

### ISSUE THREAD

**Issue by shenshengkafei** [hashicorp/terraform#17721]
Hi there,

I was trying to use a config file in Json. But it was not working as "**kubernetes_pod.nginx: resource repeated multiple times**". 

Is there anything wrong with the syntax? I checked and it was a valid Json.

```json
{
    "resource": {
		"kubernetes_pod": {
			"nginx": {
				"metadata": {
					"name": "nginx1",
					"labels": {
						"App": "nginx2"
					}
				},
				"spec": {
					"container": {
						"image": "nginx:1.7.8",
						"name": "nginx3",
						"port": {
							"container_port": 80
						}
					}
				}
			}
		}
	}
}
```

**Comment by shenshengkafei** [comment]
Sorry for the format, not sure why it is not keeping the way I pasted it.

**Comment by bflad** [comment]
@shenshengkafei no worries -- GitHub has helpful formatting information here: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Triple backticks surrounding your code or configuration will format it nicely. 😄

**Comment by shenshengkafei** [comment]
Thanks @bflad! It worked :)

**Comment by erwbgy** [comment]
We ran into this issue. If you look at the code you'll see that fields like metadata and spec are arrays:  

```
func resourceKubernetesPodCreate(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*kubernetes.Clientset)

	metadata := expandMetadata(d.Get("metadata").([]interface{}))
	spec, err := expandPodSpec(d.Get("spec").([]interface{}))
```

so you need to use something like:

```
                               "metadata": [ 
                                   {
					"name": "nginx1",
					"labels": {
						"App": "nginx2"
					}
				   },
                               ], 
```

**Comment by shenshengkafei** [comment]
Thanks a lot @erwbgy ! It worked like a charm

**Comment by apparentlymart** [comment]
Hi @shenshengkafei! Sorry for the long silence here.

I'm glad that you found the fix of using array brackets here, and I'm sorry Terraform wasn't giving more helpful error messages about this.

We've recently merged to master a set of significant changes to the Terraform configuration language implementation that improve its validation capabilities. In the forthcoming v0.12 release Terraform will respond to a configuration like this with a more helpful error message explaining what was expected. The JSON configuration loader is also now more robust, so it should now actually accept the configuration you originally attempted as equivalent to the one with the single-element arrays.

Unfortunately I wasn't able to test your example directly with the v0.12.0-alpha1 build because we didn't include the kubernetes provider in that prerelease, but I've verified similar examples with this build and have seen that it's now working, so I'm going to close this out.

Thanks for reporting this, and sorry again for the poor error message.
