### ISSUE TITLE
getting-started docs do not consider VPC-only accounts (and result in errors)

### ISSUE THREAD

**Issue by e1nh4nd3r** [hashicorp/terraform#17752]
### Terraform Version

```
$ terraform -v
Terraform v0.11.5
+ provider.aws v1.11.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
  access_key = "REDACTED"
  secret_key = "REDACTED"
  region     = "us-east-1"
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_instance" "example" {
  ami           = "ami-b374d5a5"
  instance_type = "t2.micro"
  subnet_id     = "REDACTED"

  provisioner "local-exec" {
    command = "echo ${aws_instance.example.public_ip} > ip_address.txt"
  }
}

resource "aws_eip" "ip" {
  instance = "${aws_instance.example.id}"
}
```

### Debug Output
https://gist.github.com/e1nh4nd3r/7e18d27664d3fc3d9ef7245e17c34de4

### Crash Output
N/A.

### Expected Behavior
`aws` provider should automatically set `vpc = true` for various resources where Classic is no longer an option (such as newly-created AWS accounts) or where no Classic resources exist.

### Actual Behavior
Using the [getting-started/dependencies.md -> assigning an elastic ip](https://www.terraform.io/intro/getting-started/dependencies.html#assigning-an-elastic-ip) documentation results in an error relating to "allocation id", which is required for VPC configurations:

```
* aws_eip.ip: Failure associating EIP: InvalidParameterCombination: You must specify an allocation id when mapping an address to a VPC instance
```

### Steps to Reproduce
Follow the getting-started documentation with a _brand new_ AWS account that requires VPC.

### Additional Context
I have a VPC-only AWS account (as most new AWS accounts are).

### References
N/A.

**Comment by apparentlymart** [comment]
Hi @e1nh4nd3r!

I'm sorry nobody replied to you about this before now. I think at around the time you opened this we were in the process of replacing the guides you were referring to here with new guides written by the HashiCorp Education team, which are therefore not maintained as part of this repository. (The closest equivalent to the old intro guide is the tutorial [AWS Get Started](https://learn.hashicorp.com/collections/terraform/aws-get-started).)

I'm going to close this because the documentation you were referring to here is no longer present on the website, and the education team has replaced it with tutorials they wrote and tested themselves. Thanks for reporting this, and again I'm sorry that we lost track of this while working on that migration. :confounded:
