### ISSUE TITLE
Getting Started guide does not include a final "terraform destroy" step

### ISSUE THREAD

**Issue by satishrao84** [hashicorp/terraform#17782]
### Terraform Version

```
...Terraform v0.11.5
+ provider.aws v1.13.0


```

### Terraform Configuration Files

```hcl
...
bash-3.2$ cat example.tf 
provider "aws" {
  access_key = ""
  secret_key = ""
  region     = "us-east-1"
}

resource "aws_instance" "example" {
  ami           = "ami-2757f631"
  instance_type = "t2.micro"
  depends_on = ["aws_s3_bucket.example"]
}

resource "aws_eip" "ip" {
  instance = "${aws_instance.example.id}"
}

resource "aws_s3_bucket" "example" {
  # NOTE: S3 bucket names must be unique across _all_ AWS accounts, so
  # this name must be changed before applying this example to avoid naming
  # conflicts.
  bucket = "terraform-getting-started-guide"
  acl    = "private"
}


```
Hello,
I am just getting started with terraform, going through the terraform.io tutorials. 
When I run a "terraform apply" , It seems to be reading from a cached .tf file in the directory. For example, when I run a terraform apply with the above config, I get the below error:

```
bash-3.2$ ./Downloads/terraform apply
aws_s3_bucket.example: Refreshing state... (ID: sob-terraform-getting-started-guide)

Error: Error refreshing state: 1 error(s) occurred:

* aws_s3_bucket.example: 1 error(s) occurred:

* aws_s3_bucket.example: aws_s3_bucket.example: error reading S3 bucket "sob-terraform-getting-started-guide": Forbidden: Forbidden
	status code: 403, request id: D0CE9EC364D2AC61, host id: ZQa2AsKW5Z6VMSXzU1g4Q7hT3HfEds/T4Xq7SplFXW0w4ez/HtDj6cgfbwI3ytehEzrRSs0rINs=
```

It seems to be trying to read from a sob-terraform-getting-started-guide - which is the name of the bucket I had earlier. Not from terraform-getting-started-guide - which is the current name of bucket. 
I do not have another .tf file which has the "sob-terraform-getting-started-guide". But the tfstate file seems to be holding on to that value too. 

```
bash-3.2$ cat terraform.tfstate
{
    "version": 3,
    "terraform_version": "0.11.5",
    "serial": 5,
    "lineage": "7113de4a-e051-ab2e-918e-2eaac3bdfddd",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
                "aws_s3_bucket.example": {
                    "type": "aws_s3_bucket",
                    "depends_on": [],
                    "primary": {
                        "id": "sob-terraform-getting-started-guide",
                        "attributes": {
                            "acceleration_status": "",
                            "acl": "private",
                            "arn": "arn:aws:s3:::sob-terraform-getting-started-guide",
                            "bucket": "sob-terraform-getting-started-guide",
                            "bucket_domain_name": "terraform-getting-started-guide.s3.amazonaws.com",
                            "force_destroy": "false",
                            "hosted_zone_id": "Z3BJ6K6RIION7M",
                            "id": "terraform-getting-started-guide",
                            "logging.#": "0",
                            "region": "us-east-2",
                            "replication_configuration.#": "0",
                            "request_payer": "BucketOwner",
                            "server_side_encryption_configuration.#": "0",
                            "tags.%": "0",
                            "versioning.#": "1",
                            "versioning.0.enabled": "false",
                            "versioning.0.mfa_delete": "false",
                            "website.#": "0"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.aws"
                }
            },
            "depends_on": []
        }
    ]
}

```

I just want my aws instance to depend on the S3 bucket, but I don't know how to get rid of this "sob-terraform-getting-started-guide" reference, because I don't even know where it is being defined at this point.

**Comment by apparentlymart** [comment]
Hi @satishrao84,

Terraform's state file keeps track of objects that Terraform has created and not yet destroyed. It looks like you followed the getting started guide with one set of AWS credentials and then switched over to another with the same state file, and so Terraform is now trying to discover the status of the S3 bucket that is recorded in the state file but failing because these new credentials do not have access to it.

Probably the easiest path here is to start with a fresh state by removing that `terraform.tfstate` file. This will cause Terraform to "forget" that S3 bucket and stop trying to read its status before taking other actions.

Note that if you do this and the bucket still exists in S3 Terraform will never actually destroy it. If you no longer need that bucket, you should log in to the AWS Console and manually delete it.

---

After reviewing the Getting Started guide, I see that because we introduce the `terraform destroy` command before introducing resource dependencies, there is no explicit step in the guide for destroying the S3 bucket created in that step.

In a future revision of the guide we'll change this so that the "Destroy Infrastructure" page mentions that the user should run `terraform destroy` once finished with the getting started guide, in case the user doesn't work through all the steps to the end, and then also mention destroying the remaining infrastructure as part of the "Next Steps" page.

**Comment by pkolyvas** [comment]
As the Terraform Getting Started guide is now owned by another team internal to HashiCorp, I've added the request to their issue tracker and will close this one out. 

Thanks!
