### ISSUE TITLE
Crash report  (0.4.2)

### ISSUE THREAD

**Issue by kad3nce** [hashicorp/terraform#1779]
Got this crash going through the Terraform getting started tutorial.

https://gist.github.com/kad3nce/efd4f4276fea5231ffb5

**Comment by catsby** [comment]
Hello – thanks for writing in. I _believe_ this is an issue when using EC2 Classic, in `us-east-1`, the same as in https://github.com/hashicorp/terraform/issues/1403. This has been fixed in the `master` branch and will be released shortly. 

I'm going to close for now, please re-open if you have more information that suggests it's not fixed in `master`.

Thanks!
