### ISSUE TITLE
Terraform - merge local map error

### ISSUE THREAD

**Issue by satyasc** [hashicorp/terraform#17805]
Hello,
I am using below code  and getting an error.  Any idea what is wrong?
**aws_instance.test: tags (default): '' expected type 'string', got unconvertible type 'map[string]interface {}'**

```
variable "application_name"{
    default     = "cps-dr"
}

locals  {  common_tags {
    type        = "map"
    default     = {
                    "Vertical"                    = "My Vertical",
                    "AppShortName"       = "INTERPOLATION HERE"
             }
}  }
resource "aws_instance" "test" {
  ami           = "ami-25615740"
  instance_type = "t2.micro"
  tags = "${merge(  local.common_tags,
                                map( "Name",    "lskfl" )
                  )
          }" 
}
```

**Comment by satyasc** [comment]
Thank you


*Thanks,Satya*

**Comment by apparentlymart** [comment]
Hi @satyasc! Sorry for the late response.

Looking at your example, I think the problem is how the `locals` block is written. The contents are written in a way similar to `variable` blocks, but locals have a simpler syntax:

```hcl
locals {
  common_tags = {
    "Vertical"                    = "My Vertical",
    "AppShortName"       = "INTERPOLATION HERE"
  }
}
```

In your example, you defined the `common_tags` local as being an object value with `type` and `default` attributes:

```
$ terraform console
> local.common_tags
{
  "default" = {
    "AppShortName" = "INTERPOLATION HERE"
    "Vertical" = "My Vertical"
  }
  "type" = "map"
}
```

After rewriting as I did above, I get the value expected:

```
$ terraform console
> local.common_tags
{
  "AppShortName" = "INTERPOLATION HERE"
  "Vertical" = "My Vertical"
}
```

The error you got was confusing, because Terraform tried to merge the complex object with the map and could not do so because it found the `default` value was a map instead of a string, and the `tags` argument expects a map of strings.

**Comment by satyasc** [comment]
Thank you Martin.


*Thanks,Satya*
