### ISSUE TITLE
OpenStack compute_secgroup resources - fails destroy when in use

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/terraform#1782]
```ini
resource "openstack_compute_instance_v2" "blendle" {
  depends_on = [
    "openstack_networking_router_v2.blendle",
    "openstack_compute_secgroup_v2.blendle"
  ]

  security_groups = ["blendle"]
}
```

```ini
resource "openstack_compute_secgroup_v2" "blendle" {
  name = "blendle"
  description = "Security rules for all \"blendle\" nodes"
}
```

the above fails on destroy, because Terraform tries to remove the security group while the machine is still active (being destroyed).

**Comment by jtopjian** [comment]
Can you try setting `security_groups` to:

```
security_groups = [ "${openstack_compute_secgroup_v2.blendle.name}" ]
```

That should resolve the order issue.

**Comment by phinze** [comment]
The verbose graph looks correct here:

![tf](https://cloud.githubusercontent.com/assets/37534/10835500/1b42d8ca-7e71-11e5-818d-2a6e922b50da.png)

( Quick guide: Arrows can be read like "foo -> bar" ~ "foo depends on bar" ~ "bar must be completed before foo" )

So in this case, the graph says that `_instance` must be deleted before `_secgroup`... which makes me wonder if the instance's `Delete` function is not properly waiting:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_compute_instance_v2.go#L767-L778

@jtopjian ^ perhaps this is related to #2671

**Comment by phinze** [comment]
All that being said, @jtopjian's suggestion is also an improvement to the config. :smile:

**Comment by jtopjian** [comment]
The problem is similar to #2671 and I think the same method of solution would apply to both, but I think they're two separate issues altogether.

I think there are a few other issues, either closed or open, that are having this problem and it's something I occasionally run into as well. 

Definitely correct: there needs to be some type of wait/block in the Delete function.

I worked on a fix a few months ago, but IIRC, I ran into an edge case and have been meaning to get back to it. I'll review my fix and prioritize this.

**Comment by jtopjian** [comment]
The edge case was for situations where a user created a security group through Terraform, then added instances outside of Terraform, and then tried to delete the security group. Since Terraform never deletes the instances that were added out of band, the Delete process will hang for 10 minutes and eventually error out.

I think it's safe to ignore this situation, unless there's a known pattern to deal with it?

**Comment by phinze** [comment]
> I think it's safe to ignore this situation, unless there's a known pattern to deal with it?

Yeah there's nothing we can do in this situation today. Perhaps someday executing resources will have access to a richer context with information to be able to take smarter action in cases like this, but not today. :grinning:
