### ISSUE TITLE
Terraform plugin endpoint unreliable

### ISSUE THREAD

**Issue by FrenchBen** [hashicorp/terraform#17831]
It's pretty often that I see the following failing in our ci:
`curl: (7) Failed to connect to releases.hashicorp.com port 443: Network is unreachable`

We usually pull the latest plugins via a simple curl request, eg if we wanted the aws plugin:
`curl -fsS -O "https://releases.hashicorp.com/terraform-provider-aws/1.13.0/terraform-provider-aws_1.13.0_linux_amd64.zip"`

Is there a more reliable way to do this?

**Comment by jbardin** [comment]
Hi @FrenchBen,

If you're trying to pull them, out of band for some reason, you could stash them in a known location, and either use the [Provider Plugin Cache](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache), or the `-plugin-dir` option to locate them. 

You need to run `init` anyways, is there a reason you're not allowing `terraform init` to download the plugins itself?

If it helps, `network is unreachable` isn't going to be a problem with the release site, the CDN is globally distributed and quite reliable.  If the network is created on demand for the CI host, it's possible the configuration isn't complete yet, or ipv6 is misconfigured and is sometimes returning ICMP 0 faster than the ipv4 probe can connect. IIRC `curl --retry <num>` will also retry on `ENETUNREACH` if you want to continue using curl.

**Comment by FrenchBen** [comment]
@jbardin the issue is that we've seen in our CI that `terraform init` failed to download the proper plugins; to prevent that from happening, we've added the above curl, which also seems to fail. 
The machine that pulls the plugin is an EC2 instance, which seems like it shouldn't have any network issues; thus I'm trying to understand the point of failure, which seems to happen often enough to be a concern.

**Comment by jbardin** [comment]
By "failed to download the proper plugins", do you mean it failed with the same routing error as curl, or it was fetching the incorrect version?

You have full control over the plugin versions required by providing constraints in the config, but the latest should always be the default. The plugin cache and `-plugin-dir` options can also allow multiple configuration to share plugins and reduce the time spent fetching them.

**Comment by jbardin** [comment]
If you want to troubleshoot the network issue, `curl -v https://releases.hashicorp.com/ > /dev/null` will show some of the network info happening during connect, and may indicate the failure. 

Being on EC2 doesn't necessarily mean the network is configured correctly -- it's quite easy to add an ipv6 cidr block to a subnet, but forget to add a corresponding route in the routing table since ipv4 and a lot of http tools will continue to work.

**Comment by FrenchBen** [comment]
@jbardin that's correct, it failed with the same error as curl. Since the ec2 instance is able to pull outside resources beforehand, it's odd that it fails randomly while connected to hashicorp.com.
We curl about 10 different plugins, and occasionally will see failures when pulling from release.hashicorp.com

**Comment by jbardin** [comment]
If the host has a globally scoped ipv6 address, my best guess right now for intermittent failures is going to be bad ipv6 routing, especially since "happy eyeballs" http connections are essentially a race to see what connects first. You can of course try the endpoint directly with `curl -6` or `ping6` to see what happens.

Otherwise  a `tcpdump` would be useful too to see what connections are actually in flight at the time, though I'm not sure if there's anything terraform can do if both terraform and curl are failing, since they are each using different resolution and http libraries altogether.

**Comment by FrenchBen** [comment]
Thanks for the help/steps to get to the bottom of this - Since Fastly is the CDN used, I was maybe hoping that one could look at their stats and perhaps see the same errors bubbled. 
With the network being unreachable, there's a good chance it never actually reaches the CDN, and thus couldn't be debugged that way.

I'll try to gather more information on this.
