### ISSUE TITLE
Integrate Gandi LiveDNS provider ?

### ISSUE THREAD

**Issue by drazzib** [hashicorp/terraform#17842]
Hi!

Since 2015, Gandi has launched a new LiveDNS service which is based on a new [RESTful HTTP API](http://doc.livedns.gandi.net/). This new LiveDNS platform has more features plus new gifts planned (automatic zone signing, new records including ALIAS, etc.)

@tiramiseb has already a working provider inside this repository [terraform-provider-gandi](https://github.com/tiramiseb/terraform-provider-gandi)

Is there plan to integrate this provider into Terraform core ?

**Comment by apparentlymart** [comment]
Hi @drazzib!

Since Terraform 0.10, providers are no longer distributed as part of Terraform Core. Instead, they have their own repositories in [the `terraform-providers` github organization](https://github.com/terraform-providers) and are released separately so that they can be downloaded and installed by `terraform init`.

Our [Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html) is the process by which new providers can be brought into that organization and published into the HashiCorp-maintained plugin repository. This process is primarily aimed at vendors who wish to develop plugins for their own services (in this case, for Gandi themselves to develop a provider to this service) and we acknowledge that this process is more "heavy" than ideal for a third-party developer, but we are open to discussing bringing in a community-maintained provider if the maintainer(s) are willing to [support the provider](https://www.terraform.io/guides/terraform-provider-development-program.html#6-support) and to collaborate with the vendor on maintenance if they later wish to join the program themselves.

For more information, please reach out to the contact email address given in the program guide, linked above, to talk with the provider development program team.

Since the provider onboarding process happens outside of the Terraform repository, and so there's no further action we could take here on this, I'm going to close this out.

Thanks!
