### ISSUE TITLE
Terraform development - provider/provisioner relationship

### ISSUE THREAD

**Issue by skywalk7** [hashicorp/terraform#17860]
I'm trying to create provider specific provisioner. So I got couple of questions:
1) Can ServeOpts both contain ProvisionerFunc and ProviderFunc?
2) Can it be in one binary or need build 2 with different names like `terraform-provider-customprov` and `terraform-provisioner-customprov`?
3) Is it possible to access provider configuration from provisioner code?
4) ~~Is it possible to access resource attributes from provisioner code?~~ (yes, via ctx.Value(schema.ProvRawStateKey).(*terraform.InstanceState))
Thanks a lot in advance!

**Comment by apparentlymart** [comment]
Hi @skywalk7!

At the moment, provider plugins and provisioner plugins are totally separate. It's not possible to build a single binary that can serve both. There is some old discussion about this in #2756 (which I opened before I was a HashiCorp employee) but at the moment we're not planning any changes in this area due to our focus being elsewhere.

Although as you've seen you can in principle access the raw instance state, this is not intended to be part of the public interface. Instead, the user should explicitly pass in the necessary attributes to avoid an implicit dependency:

```
  provisioner "example" {
    argument = "${self.any_attribute}"
  }
```

This way it's clear where the values are coming from, and the resource and provisioner are not implicitly coupled.

**Comment by skywalk7** [comment]
Hi @apparentlymart !
Thanks a lot for your feedback. May be you can help with `ConnSchema` for `schema.Provisioner`.
This is my provisioner configuration:
```
func Provisioner() terraform.ResourceProvisioner {
	return &schema.Provisioner{
		ConnSchema: map[string]*schema.Schema{
			"os_user": &schema.Schema{
				Type:        schema.TypeString,
				Description: "The user name for vm guest operations.",
				Required:    true,
			},
			"os_password": &schema.Schema{
				Type:        schema.TypeString,
				Description: "The user password for vm guest operations.",
				Required:    true,
			},
```
This is my resource config:
```
resource "vsphere_virtual_machine" "vm" {
...
  provisioner "vmcert" {
    connection {
      os_user     = "vagrant"
      os_password = "vagrant"
    }
    ...
```
And on apply terraform throws error:
```
Error: vsphere_virtual_machine.vm: unknown 'connection' argument "os_password"
Error: vsphere_virtual_machine.vm: unknown 'connection' argument "os_user"
```

**Comment by apparentlymart** [comment]
Hi @skywalk7,

To be honest I'm not sure why we have that `ConnInfo` field there... it's not used by any of the built-in provisioners, and indeed that's expected because the `connection` block is separate from the `provisioner` block and has its own schema.

The `connection` block belongs to [the `communicator.New` function](https://godoc.org/github.com/hashicorp/terraform/communicator#New), which is used by the `remote-exec` and `file` provisioners so that they can support both SSH and WinRM connections. If you are not using a `Communicator` in your provisioner then you should ignore the `connection` block altogether and just access the content of the `provisioner` block itself, using the following in your apply function:

```go
data := ctx.Value(schema.ProvConfigDataKey).(*schema.ResourceData)
```

While in principle it is possible for your provisioner to handle the connection block contents itself _without_ delegating to `communicator.New`, I would not recommend it since it would be a poor user-experience if the behavior does not exactly match how the block is interpreted by the `file` and `remote-exec` provisioners.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
