### ISSUE TITLE
file() depends_on

### ISSUE THREAD

**Issue by stefanthorpe** [hashicorp/terraform#17891]
Not sure if this is a bug, feature request or just me missing something.

I have a situation where I need to pass file(my-file.yml) into a provider.
However, this file is created either by a symlink or download a little earlier on the project. However, I can't get beyond the planning stage because the file is trying to load before its created.
I've added a depends_on but put still causes issues. If I manually add the file it works fine and creates just fine.

**Comment by apparentlymart** [comment]
Hi @stefanthorpe!

The `file` function is for including files that are considered a fixed part of the configuration, and so it doesn't participate in the dependency graph. However, you can use [the `local_file` data source](https://www.terraform.io/docs/providers/local/d/file.html) to read files in a way that _does_ participate in the graph.

In general we'd recommend doing this sort of thing sparingly since Terraform isn't really designed for manipulating local data, but that data source is provided for specialized situations where it can be used carefully to read generated files.

In most cases having a Terraform configuration generate a file can be considered a missing feature in Terraform, since it is effectively circumventing interpolation as the intended way to pass data between resources in an explicit way, so if you're able to share some more detail on the use-case that is causing you to create a file and then later read it, I'd love to hear more about it in a separate issue.
