### ISSUE TITLE
"Unknown resource" error should be suppressed when count is 0

### ISSUE THREAD

**Issue by mrubin** [hashicorp/terraform#17929]
I am using Terraform v0.11.7 and am seeing the below:

```
Error: resource 'aws_elastic_beanstalk_environment.foo-service' config: unknown resource 'aws_s3_bucket.bar' referenced in variable aws_s3_bucket.bar.id
```

It is true that the variable is not there. However, `aws_elastic_beanstalk_environment.foo-service` has a `count` of 0 at the moment , so it won't even be created.

Is it possible to not complain about errors like this when the resource in question is "commented out" (via the `count` of 0)?

**Comment by jbardin** [comment]
Hi @mrubin,

Yes, this can be a common pitfall when using `count` to "disable" resources. We can't suppress the error, because the field needs to be be assigned _some_ value for `variable aws_s3_bucket.bar.id`, but the interpolation is not valid.

This will be easier once we get short-circuiting conditionals in the config, but in the meantime you can use the same patterns using `*` we recommend for "disabled" values in outputs: https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0
