### ISSUE TITLE
Terraform crashes when interpolating tags on aws_instance

### ISSUE THREAD

**Issue by clebio** [hashicorp/terraform#17921]
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.15.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" repro {
  ami = " ami-1853ac65"
  instance_type = "t2.micro"
  tags = ["${map()}"]
}
```

### Debug Output
ASCII armor gpg encrypted:
https://gist.github.com/clebio/4356e88d7d0399431b6d67a52084f11a

Highlights:
`!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!`

### Crash Output
https://gist.github.com/clebio/4356e88d7d0399431b6d67a52084f11a

### Expected Behavior
`terraform plan` should give an error message about invalid nesting of list and map, or something of the sort.

### Actual Behavior
`plan` crashes Terraform.

### Steps to Reproduce
```terraform init
terraform plan
```

### Additional Context
using just `tags = []` or `tags = [{}]` does not cause a crash. Using `tags = ["${map()}"]` does crash, however. I wouldn't normally do `["${map()}"]`, but my common use case is `"${var.tags}"`. I realize that `tags` should be a map, not a list, but as the crash output says, Terraform should never actually crash.

**Comment by mackenbach** [comment]
I have encountered the same crash, so +1. It happens on more than just `aws_instance`, I checked and the same thing occurs on `aws_elb` and `aws_security_group` too. 

If I'd had to guess, it has something to do with the interpolation parsing. 

```
Terraform v0.11.7
+ provider.aws v1.19.0"
```

**Comment by apparentlymart** [comment]
Hi @clebio and @mackenbach! Sorry for this crash, and for the delay in responding.

We've recently merged to master the result of a multi-month project to rework the configuration language handling to be more robust. It now has an explicit prior validation pass before attempting any evaluation, where it checks that the types of all expressions are as expected.

I ran the example configuration from the original comment through the v0.12.0-alpha1 prerelease build and got a proper error message, as expected:

```
$ terraform apply

Error: Incorrect attribute value type

  on /home/mart/Devel/terraform/v0.12-issue-blitz/cases/17921-tags-map-crash/tags-map-crash.tf line 8, in resource "aws_instance" "repro":
   8:   tags          = ["${map()}"]

Inappropriate value for attribute "tags": map of string required.
```

I believe the reason why the crash only occurred when using the map function is that previously the validation pass would skip over values that contained interpolations to be evaluated, with the intent of checking them at a later point. However, as you found, in some cases like this one that later point never came and it would instead crash. Now we validate expressions at the same time as literal values; the new behavior is also present for the `[{}]` syntax and for a variable of the wrong type:

```
Error: Incorrect attribute value type

  on /home/mart/Devel/terraform/v0.12-issue-blitz/cases/17921-tags-map-crash/tags-map-crash.tf line 8, in resource "aws_instance" "repro":
   8:   tags          = [{}]

Inappropriate value for attribute "tags": map of string required.
```

```
Error: Incorrect attribute value type

  on /home/mart/Devel/terraform/v0.12-issue-blitz/cases/17921-tags-map-crash/tags-map-crash.tf line 13, in resource "aws_instance" "repro":
  13:   tags          = var.foo

Inappropriate value for attribute "tags": map of string required.
```

Since this fix is merged and ready for release in the forthcoming v0.12.0 release, I'm going to close out this issue. Thanks for reporting this, and sorry again for the slow response.

**Comment by ajmatty** [comment]
defining your locals like so: 
```
locals {
  common_tags = "${map(
    "project", "myproject",
    "environment", "${var.env}",
    "owner", "someGuy"
  )}"
}
```

you can use this in the code block: 
`tags = local.common_tags`
