### ISSUE TITLE
feature request: prereq flag on data sources

### ISSUE THREAD

**Issue by GeoffMillerAZ** [hashicorp/terraform#17935]
## Issue
Suppose you are making a module. This module requires that other modules have stood up resources. You know what tags they should have so you can use data sources to filter and import those resources. I also use data sources to enforce a job fails if certain resources weren't created first just to enforce prerequisites to the module. But I have noticed that the job can fail in the middle of it when actually trying to use the data source. I think it would be nice to be able to flag certain data sources as "prereqs" that would simply tell the plan to check if they exist first thing.

## example
I have a module that creates an aws load balancer and it assigns a security group to it that was made from another module. I had a data source for that security group. I forgot to make the security group so the job is going to fail. But I noticed it checked many things before failing.

**Comment by apparentlymart** [comment]
Hi @GeoffMillerAZ,

The behavior for data resources is that Terraform will try to read them during the plan phase as long as their configuration can be fully known at that phase. If the data resource's configuration includes references to resources that haven't been created yet, Terraform must defer the read until apply time so that the result can be known.

It sounds like in your case you may have interpolated a resource attribute into your security group data resource configuration, causing the read to be delayed. If that isn't true, please share the relevant parts of your configuration so we can better understand what's going on, since the behavior you've requested here is the current expected behavior.

**Comment by apparentlymart** [comment]
Hi again @GeoffMillerAZ!

Since I didn't hear back from you, I'm going to assume that you figured something out here. If not, please do feel free to open a new issue and fill out the issue template to give us some more details to work with.

Thanks!
