### ISSUE TITLE
feature request: lifecycle rename_to_replace

### ISSUE THREAD

**Issue by GeoffMillerAZ** [hashicorp/terraform#17934]
## Issue:
If you want to change a attribute of a resource that require a deletion and recreation but other resources are tied to that resource, you'd need to do a `create_before_delete` lifecycle. But what if more than one of that resource by the same name are not allowed? It would be useful to have some sort of lifecylce flag that indicated that it is ok to create a new resource that is identical to the one being replaced except with a different name; like with `-old` appended to the end. Then a resource with the actual desired settings is made with the actually desired name. When that is fully updated, then the `-old` temporary resource can be safely deleted.

## Example:
I have an `aws_lb` of type network. It has a `aws_lb_listener` that has an assigned `aws_lb_target_group`. I made the target group with the wrong type. So I changed it and applied. It fails because the listener is depending on it and you can't have a listener with no target. 

## Manual fix
I applied the create_before_destroy but then you get the error that a target group named https (it's name) already exists. So then I put `-old` at the end of the target group name and it works. Then I remove the `-old` and apply again. It works.

## Alternative
you could allow people to declare a resource and flag it as a resource that is only to be created in such a situation as a placeholder. Then have lifecycle entries that point to such a resource that is then used for the swap and deleted right after.

**Comment by GeoffMillerAZ** [comment]
PS I'm sure there are better names for the lifecycle flag I proposed.

**Comment by jbardin** [comment]
Hi @GeoffMillerAZ,

Thanks for opening the issue.

This isn't something that terraform can handle generically, because the details of renaming, and if it's even allowed, are dependent on resource and provider in question.

In such cases, the provider needs to implement it's own provisions for resources that would fail with `create_before_destroy`. In this particular case, `aws_lb_target_group` has the `name_prefix` field to allow for unique names for each instance.
