### ISSUE TITLE
Cannot Pass a Nested Map Element to a Module

### ISSUE THREAD

**Issue by rpattcorner** [hashicorp/terraform#17943]
```
Terraform v0.11.5
+ provider.aws v1.16.0
```
Have a module that needs to be passed a map of values representing cloud accounts, and the individual account map that is passed will vary according to the account we want the module to create.  Other modules, which require a separate state, also need these values, so in the other modules we're reading the value maps from the remote state of the first module.  Works fine with individual maps of values.

We need scalability and are therefore trying to avoid creating a new map output variable for every account value map we need by creating a homogenous account_map of the individual child maps to be passed, then passing one of the child maps by named key to the account module, like this:

### The map of maps
```
variable "account_map" {
  type = "map"
  default = {
    account_one {
      type = "map"
      default = {
        name = "account-one"
        email = "emailone@foo.com"
      }
    },
    account_two {
      type = "map"
      default = {
        name = "account-two"
        email = "emailtwo@foo.com"
      }
    }
}
```
etc. 

## Module invocation, just pass one map from the map of maps
```
module accounts_one {
  source = "../../modules/accounts"
  account = "${var.account_map["account_one"]}"
}

output "problem_child" {
  value = "${var.account_map["account_one"]}"
}
```
Note that there's no double bracket syntax involved or other oddities, and that the map of maps is absolutely homogenous, containing nothing but other maps.

## Module Implementation
Tries to pick the name attribute from the map it was supposedly passed from the map of maps:
```
resource "aws_organizations_account" "generic" {
  name  = "${var.account["name"]}"
  email = "${var.account["email"]}"
  role_name = "somerole"
}
```
The module works fine when passed a simple standalone map as noted.

When running from the map passed in from the map of maps, though, we get the following error:
```
Error: module.account_one.aws_organizations_account.generic: 1 error(s) occurred:

* module.account_one.aws_organizations_account.generic: At column 14, line 1: map "var.account" does not have homogenous types. found TypeString and then TypeMap in:

${var.account["name"]}
```
Just to doublecheck, I edit and make the module happy by passing it a standalone map, and observe the output from the output stanza in the invoking module.  The looked up map looks as if it were 'dehydrated' into some internal representation -- all the parts are there, but everything is flattened into an array of strings:
```
problem_child = {
  default = map[name:account_one email:emailone@foo.com]
  type = map
}
```    
(strings replaced for confidentiality)

I have a bad feeling this has something to do with a comment that maps return everything as a string.  Is there some way to "rehydrate" the returned map from the map of maps, or work around this issue?  

Thanks for your thoughts!

## References
[17227](https://github.com/hashicorp/terraform/issues/17227)
[14309](https://github.com/hashicorp/terraform/issues/14309)

But the current case deals with passing a map within a map to a module, not outputting it (except as a debug technique)

@apparentlymart seems to know a lot about these internals

**Comment by apparentlymart** [comment]
Hi @rpattcorner! Sorry for this confusing behavior, and for the slow response.

I think the maps it is complaining about when it says that the types are non-homogenous are the nested ones, like this one:

```hcl
{
  type = "map"
  default = {
    name = "account-one"
    email = "emailone@foo.com"
  }
}    
```

This is a homogenous map because `type` is a string while `default` is a map. But given that these are the names used in `variable` blocks, I assume what you were really trying to achieve here is to just create a simple nested map value, which would be written instead like this:

```hcl
variable "account_map" {
  type = "map"
  default = {
    account_one = {
      name = "account-one"
      email = "emailone@foo.com"
    }
    account_two = {
      name = "account-two"
      email = "emailtwo@foo.com"
    }
  }
}
```

Terraform 0.11 and earlier don't really properly support maps of maps like this and I expect there'd be further trouble even with the above. But on the plus side, we've recently merged a revamped implementation of the configuration language into master in preparation for the forthcoming v0.12.0 release, and one of the improvements is proper support for complex types in variables. Here's how we'd write that variable declaration using the new features:

```hcl
variable "account_map" {
  type = map(object({ # we can specify the type of each attribute separately, though they are all strings here
    name  = string
    email = string
  }))
  default = {
    account_one = {
      name = "account-one"
      email = "emailone@foo.com"
    }
    account_two = {
      name = "account-two"
      email = "emailtwo@foo.com"
    }
  }
}
```

This new type specification syntax will then allow Terraform to fully check the value provided by the calling module.

It's possible that rewriting the `variable` block to be like my second example above would fix this even for v0.11, but at the very least the forthcoming v0.12.0 release should behave the way you expected, and also give you the ability to define exactly what element types are required rather than just specifying that it's a "map".

Since these changes are already in master and ready for inclusion in the v0.12.0 release, I'm going to close this out. Sorry again for the delay in responding to this.
