### ISSUE TITLE
Feature Q: Is there a generic "hook" for terraform apply, regardless of resources changed?

### ISSUE THREAD

**Issue by lizhubertz** [hashicorp/terraform#17957]
Is there a built-in way to "hook" into any terraform apply action, regardless of resources changed?

My use case is that, running terraform, I want to notify an external ticketing service before any  terraform apply is run in a given workspace, and after the apply is completed (with the result of what has been done).

I've considered a few solutions, and all seem a little hack-y:

- write a bash wrapper around the `terraform` command. Gross.
- write a custom terraform provider for creating tickets. This doesn't make a whole lot of sense, since this ticketing service isn't a traditional CRUD resource. We just "create" the ticket and are done with it.
- use the `null_resource` provider with a trigger on `uuid()`, so it's run every time terraform is run. This `null_resource` would have a `local-exec` provisioner to run a command that will send the ticket request. 

An issue with the second two is also that, with terraform's parallelism, I would need to set up a lot of dependencies in order to make sure that this thing is done before/after anything is created.

It just seems like terraform might have some built-in way to hook into the apply method, and call a function before or after. I can't seem to find it in the docs or in StackOverflow answers, however.

### Terraform Version

`Terraform v0.11.7`

**Comment by byF** [comment]
I'd like to hook into post-apply to regenerate the TF JSON output which is consumed by a custom Node cli app.

**Comment by apparentlymart** [comment]
Hi @lizhubertz! Thanks for sharing this use-case, and sorry for the long delay in responding.

In most cases we've seen that once a team reaches the point that they want to start building a more formal workflow around Terraform they achieve this by running Terraform inside some sort of automation (e.g. a CI system) and ceasing to run it on individual developer/operator workstations. Running Terraform locally is a good way to get started, but doesn't scale well past a one or two team members.

This is similar to your first potential solution here in that it happens outside of Terraform in some sort of wrapper, rather than inside Terraform itself. But doing this inside automation ensures that Terraform _always_ runs in the context of that wrapping automation.

At this time, that's the solution we suggest for implementing a stronger workflow around Terraform on teams. This not only allows for interactions with other systems (like your ticket system) but also ensures that Terraform always has access to the same outside system in cases where it runs shell commands using `local-exec`, etc.

Handling these integrations _outside_ of Terraform also ensures that the integration can still succeed in cases where Terraform itself fails, such as if an error during apply prevents Terraform from running to completion successfully.

We have a guide [_Running Terraform in Automation_](https://www.terraform.io/guides/running-terraform-in-automation.html) which covers some of the recommendations and challenges for running Terraform in this sort of environment. Lots of users have successfully implemented this inside systems like CircleCI, Buildkite, etc. For larger organizations, Terraform Enterprise also follows these same guidelines to run Terraform in a more controlled environment.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
