### ISSUE TITLE
Conditional expression evaluates unreachable substitution 

### ISSUE THREAD

**Issue by wschult23** [hashicorp/terraform#17960]
### Terraform Version 0.11.5
I have a conditional data resource and I want to obtain a value from this resource. If the ressource doesn't exist, I want to set the value to an empty string.

```
data "aws_instance" "not_exist" {
 
  filter {
    name   = "tag:Name"
    values = ["non_existing"]
  }
}

locals {
  name = "${data.aws_instance.not_exist.count==0?"":data.aws_instance.not_exist.tags["Name"]}"
}
```

### Expected Behavior
Due to the fact that the expression evaluates to true, I would expect, that the second term 
```
data.aws_instance.not_exist.tags["Name"]
```
would not be evaluated and the value of locals.name is "". 

### Actual Behavior
Terraform produces a error message, that it can't find the ressource after applying the plan:
```
* local.name: local.name: Resource 'data.aws_instance.some_ressource_that_does_not_exist' not found for variable 'data.aws_instance.not_exist.tags'
```
### Steps to Reproduce
`terraform apply`

**Comment by jbardin** [comment]
Hi @wschult23,

Thanks for filing the issue. This is correct that conditional statements don't short-circuit.
We are working on including this in a suite of changes to the configuration language that will come in a future release.

**Comment by jbardin** [comment]
We're leaving the early issue #15605 open to track this feature.

**Comment by wschult23** [comment]
Hi James,
is there a workaround? I want to access data within a „data“ resource only if the resource itself exists.

Best regards,

Wolfgang.

**Comment by jbardin** [comment]
Hi @wschult23,

There's no workaround if the resource does not exist in the configuration at all (I'm actually not sure yet if that will work in the next version, but it's not something that should be counted on).

If the resource doesn't exist because the count is 0, you can reference it as an empty list using the `*` operator. There's an example in the 0.11 upgrade guide here: https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0
