### ISSUE TITLE
Iterate through list of maps to define resources

### ISSUE THREAD

**Issue by jwsomis** [hashicorp/terraform#17988]
### Terraform Version
```
0.11.7
```
HI, I am quite new to Terraform, but have found that it is typically cleaner to declare things in variable than in a lot of resource blocks, but there are some things that make it impossible to do this. 
For example, I would love to be able to do something like this
```hcl
resource "aws_security_group" "sec_groups" {
  count         = "${length(var.security_groups)}"

  name          = "${lookup(var.security_groups[count.index], "name")}"
  description = "${lookup(var.security_groups[count.index], "name")}"
  ingress        = {} #Get stuck on this
  tags             = {} #  and this somewhat
}
```
where var.security_groups is a list of maps.. However, there is currently no way to pass in ingress rules.
One solution would be to allow ingress to take a list of maps, but this would also require lookup to return a list, like:
```
 ingress = "${lookup(var.security_groups[count.index], "ingress")}
```
where security_group was
```
default = [{
  ... #stuff
  ingress = [{
    from_port   = 0
    to_port     = 65535
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  },..]
```
Not sure if there is a better implementation of this, but the end goal would be to allow me to declare lists of resources in variables and then iterate through that variable in a resource block. Some aws resources this is straightforward to do with, but others not so much. And really very few if you want specific (not templated) tags. If there is already some way to do this, I look forward to learning it. 

Thanks

**Comment by apparentlymart** [comment]
Hi @jwsomis! Thanks for sharing this use-case.

I think the missing part here for what you are trying to do is what we've been discussing in #7034. Later in that discussion thread I posted some notes about the special `dynamic` block we're planning to introduce as a way to dynamically produce nested blocks, like `ingress` here.

This is planned for the next major release of Terraform, along with some other improvements to the configuration language that would allow something like this:

```hcl
# Not yet implemented, and details may change before release.
resource "aws_security_group" "sec_groups" {
  count = length(var.security_groups)

  name        = var.security_groups[count.index].name
  description = var.security_groups[count.index].description
  tags        = var.security_groups[count.index].tags

  dynamic "ingress" {
    # An "ingress" block is created for each element of this list...
    for_each = var.security_groups[count.index].ingress
    # ...with the content generated from the this block...
    content {
      from_port   = ingress.value.from_port
      to_port     = ingress.value.to_port
      protocol    = ingress.value.protocol
      cidr_blocks = ingress.value.cidr_blocks
    }
  }
}
```

We usually recommend against writing modules that just pass through to resource blocks like this, since it's generally more straightforward and explicit to have the security groups be defined directly with `resource` blocks and pass their _ids_ through to the module that uses them, but we know that there are some legitimate reasons to do this sort of wrapping and so we're hoping that this new `dynamic` block makes that easier to accomplish in the cases where it's helpful.

Since we already have the dynamic block feature covered by #7034, and the other syntax features in this  example ("naked" expressions, better index/attribute syntax) are already underway, I'm going to close this just to consolidate in #7034. Thanks for taking the time to describe this use-case!
