### ISSUE TITLE
targetprocess provider

### ISSUE THREAD

**Issue by nbirnel** [hashicorp/terraform#18016]
Feature request
============

It would be nice to have a provider for targetprocess https://dev.targetprocess.com/

A few use cases: 
* tagging resources with story numbers
* logging terraform applies to deploy stories
* storing resource ids, IPs, etc to targetprocess test cases

**Comment by apparentlymart** [comment]
Hi @nbirnel! Thanks for this feature request.

At this time the Terraform team at HashiCorp is not generally working on new providers in-house, because the existing ones are already keeping us pretty busy. However, we do have a process for bringing in providers developed either by the vendor of the system in question or by a sufficiently-motivated person in the community. The process is documented in the [Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html) guide.

The process as written there is mainly aimed at vendors who wish to develop a Terraform provider for their own platform, but the general process also applies to the situation where a provider is developed in the community, with just some different details in exactly what'll happen in each of these steps.

If you or anyone else is interested in working on such a provider, please reach out via the contact form on the guide page I linked above, and the providers team will get back to you. Thanks! We don't really have any precedent for providers interacting with project management and task tracking tools, so might be worth reaching out there to discuss some of the potential use-cases first, to see how they'd fit in with other Terraform providers.
