### ISSUE TITLE
count logic does not work, bug or docs issue?

### ISSUE THREAD

**Issue by flypenguin** [hashicorp/terraform#18015]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.17.0
```

### Terraform Configuration Files
[Attached as ZIP file](https://github.com/hashicorp/terraform/files/1988693/bug_report.zip). The relevant files are:

* `team-groups-policies.tf`
* `helpers/group-role-with-policies/main.tf`

The most relevant parts are:

```hcl
# "main" tf file
module "team_ci_group" {
  source = "helpers/group-role-with-policies"

  create_group = 1
  team         = "team"
  name         = "ci"

  policies = [
    "arn:aws:iam::aws:policy/AWSBatchFullAccess",
    "${aws_iam_policy.gen_get_ecr_token.arn}",
  ]
}
```

... and ...

```hcl
# module
resource "aws_iam_group" "group" {
  count = "${var.create_group}"
  name  = "${var.prefix}-${var.team}-${var.name}"
  path  = "/groups/${var.team}/"
}

resource "aws_iam_group_policy_attachment" "group_policy" {
  count = "${length(var.policies) * var.create_group }"

  group      = "${aws_iam_group.group.name}"
  policy_arn = "${element(var.policies, count.index)}"
}
```

### Debug Output

In ZIP archive, a file called "TRACE"

### Crash Output

No crash.

### Expected Behavior

It should have created a group with two policy attachments.

### Actual Behavior

Error message: `* [...]: value of 'count' cannot be computed`

### Steps to Reproduce

* Unzip
* `terraform init`
* `terraform plan`

### Additional Context

N/A

### References

N/A

**Comment by flypenguin** [comment]
by the way, I am using the *exact same code* in an existing larger TF folder, and *it works*.

Well, sometimes.

### That works

```
module "language_batch" {
  source = "helpers/group-role-with-policies"

  create_role = 1
  team        = "language"
  name        = "batch"

  policies = [
    #"${aws_iam_policy.language_batch_evaluation.arn}",
    "1234",
  ]

  assume_role_policy = "${data.aws_iam_policy_document.gen_assume_role_default.json}"
}
```

### That does not

```
module "language_batch" {
  source = "helpers/group-role-with-policies"

  create_role = 1
  team        = "language"
  name        = "batch"

  # THIS CHANGED ....
  policies = [
    "${aws_iam_policy.language_batch_evaluation.arn}",
    #"1234",
  ]

  assume_role_policy = "${data.aws_iam_policy_document.gen_assume_role_default.json}"
}
```

**Comment by jbardin** [comment]
Hi @flypenguin,

Sorry this is causing you trouble. The count issue here can be somewhat hard to decipher if you don't know what's going on. 

The value for `count` needs to be known at apply time in order to determine the full list of dependencies. While in this case the the value is actually statically known, because the value at index 0 is not known, the value of the list is also considered unknown (or to be "computed" later) when count needs to be resolved, resulting in the `value of 'count' cannot be computed` error.

This is a known shortcoming of the current HCL libraries, which we intend to handle in the next major release. We're tracking this in a number of open issues already, with #16712 being the most similar.

**Comment by flypenguin** [comment]
I ... fully don't understand that explanation, sorry 🤷‍♂️ 

Could you elaborate a bit further?
