### ISSUE TITLE
`terraform fmt` silently removes malformed attribute, other commands ignore syntax error.

### ISSUE THREAD

**Issue by extemporalgenome** [hashicorp/terraform#18056]
### Terraform Version
```
Terraform v0.11.7
```

### Terraform Configuration Files
`main.tf` is as follows:
```hcl
locals {
  v = }
}
```

The following also produces identical results (the number of opening square-brackets don't matter):
```hcl
locals {
  v = [[[}
}
```

### Expected Behavior
`terraform fmt` and other commands (such as `plan` or `apply`) report a syntax error.

### Actual Behavior
`terraform apply` produces the following output:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

`terraform fmt` rewrites the file to:
```hcl
locals {}
```

### Steps to Reproduce
1. copy sample input into `main.tf` file.
2. run `terraform plan` or `terraform fmt --diff`

### Additional Context

If the curly braced section contains attributes before the malformed list, those will be retained in the formatted output. If there are any attributes after the malformed line, terraform will report a syntax error.

**Comment by apparentlymart** [comment]
Hi @extemporalgenome! Sorry for this strange behavior, and thanks for reporting it.

The next major release of Terraform will include a new implementation of the configuration language parser that will handle unexpected input more robustly, and so I expect this bug will be fixed automatically once we adjust `terraform fmt` to use the new parser rather than the old. We've not yet completed that part of the work, so I'm going to leave this issue here for the moment and we'll revisit it once we've made the necessary change and make sure it is indeed fixed.

Thanks again for reporting this.

**Comment by mildwonkey** [comment]
I can confirm that Terraform 0.12 properly catches this syntax error:

```
$ terraform plan

Error: Invalid expression

  on main.tf line 2, in locals:
   2:   v = }

Expected the start of an expression, but found an invalid expression token.
```
