### ISSUE TITLE
Chef povisioner fails while provisioning instances - knife vault remove

### ISSUE THREAD

**Issue by aknarts** [hashicorp/terraform#18117]
### Terraform Version
```
Terraform v0.11.6
+ provider.aws v1.14.0
+ provider.null v1.0.0
```

### Terraform Configuration Files
```hcl
resource "null_resource" "server-provisioner" {
  count      = "${aws_instance.server.count}"
  depends_on = ["aws_volume_attachment.server-data"]

  provisioner "chef" {
    environment     = "${var.chef["environment"]}"
    server_url      = "${var.chef["ext_server_url"]}"
    version         = "${var.chef["version"]}"
    user_name       = "${var.chef["user_name"]}"
    user_key        = "${file("${var.chef["key_path"]}")}"
    node_name       = "${aws_instance.server.*.tags.Name[count.index]}"
    recreate_client = true
    ohai_hints      = ["ec2.json"]

    run_list = [
      "role[base]",
    ]

    attributes_json = "${var.server_attributes_json}"

    vault_json = "${var.server_vault_json}"

    connection {
      host         = "${aws_instance.server.*.private_ip[count.index]}"
      user         = "${var.server_ami["user"]}"
      bastion_host = "${var.chef["bastion_host"]}"
      bastion_user = "${var.chef["user_name"]}"
    }
  }

  triggers {
    instance = "${aws_instance.server.*.id[count.index]}"
  }
}
```

### Expected Behavior
Node gets created

### Actual Behavior
`* module.server.null_resource.provisioner[0]: error executing "sudo knife vault remove users aws -C \"server.example.com\" -M client -c /etc/chef/client.rb -u terraform --key /etc/chef/terraform.pem": wait: remote command exited without exit status or exit signal`

### Additional Context
I think there is a missing condition here: https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/resource_provisioner.go#L583

That block of code gets run even if there was no node with such name present previously

Saving if it is actual recreation from before(https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/resource_provisioner.go#L528) would probably help the issue

This happens to us on new instances and when recreating instances where the name changed

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
