### ISSUE TITLE
Create multiple resource instances without count

### ISSUE THREAD

**Issue by s1mark** [hashicorp/terraform#18145]
### Terraform Version
`Terraform v0.11.7`

### Requested feature (option 1)
```json
{
  ...
  "resource": {
    "openstack_compute_instance_v2": {
      "instance_app": [
        {
          "name": "name",
          ...
        },
        {  
          "name": "name",
          ...
        }
      ]
    }
  }
}
```
#### Current error when using this approach
`Error: Error loading /tmp/json.tf: position -: resource must be followed by exactly two strings, a type and a name`
Was hoping that this would work due to how the `openstack_compute_secgroup_v2` rule declaration works:
```json
...
    "rule": [
      {
        "from_port": 1,
        "to_port": 65535,
        "ip_protocol": "tcp",
        "self": true
      },
      {
        "from_port": 1,
        "to_port": 65535,
        "ip_protocol": "udp",
        "self": true
      }
    ]
...
```
### Requested feature (option 2)
```json
{
  ...
  "resource": {
    "openstack_compute_instance_v2": {
      "instance_app": { 
        "0": {
          "name": "name",
          ...
        },
        "1": {  
          "name": "name",
          ...
        }
      }
    }
  }
}
```
#### Current error when using this approach
`Error: openstack_compute_instance_v2.instance_app: resource repeated multiple times`

### Terraform Configuration Files with count
```json
{
... 
  "resource": {
    "openstack_compute_instance_v2":
    {
      "instance_app": {
        "count": 2,
        "name": "name",
        ...
      }
    }
  }
}
```
#### Result
The output of `terraform show`:
```
openstack_compute_instance_v2.instance_app.0:
  ...
  name = name
  ...
openstack_compute_instance_v2.instance_app.1:
  ...
  name = name
  ...
```
Interaction with `terraform console`:
```
> openstack_compute_instance_v2.instance_app
openstack_compute_instance_v2.instance_app: resource variables must be three parts: TYPE.NAME.ATTR in:

${openstack_compute_instance_v2.instance_app}
> openstack_compute_instance_v2.instance_app.0
Resource 'openstack_compute_instance_v2.instance_app' not found for variable 'openstack_compute_instance_v2.instance_app.0'
> openstack_compute_instance_v2.instance_app[0]
openstack_compute_instance_v2.instance_app: resource variables must be three parts: TYPE.NAME.ATTR in:

${openstack_compute_instance_v2.instance_app[0]}
> openstack_compute_instance_v2.instance_app[0].id
parse error at 1:48: expected "}" but found "."
```

**Comment by mildwonkey** [comment]
Hi @s1mark ! Sorry for the long silence on this feature request.

Using multiple separate resource blocks is the only supported way of creating multiple resource instances without count. The syntax for `rule` works because it is a nested block attribute, specifically designed for repeated configurations. 

We are working on enabling [`for_each`](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each) for resources, which isn't exactly what you are asking for, but I suspect it will help solve the same root complaint. We don't have a timeline on that yet. 

Since we do not plan on adding this capability, I am going to close this issue. Thanks again, and sorry for the unsatisfying response!
