### ISSUE TITLE
The terraform registry will sometimes fail to navigate to the listing from the module page.

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#18165]
1. Go to https://registry.terraform.io/modules/mediapop/certificate/aws/1.1.0/examples/empty-domains
2. Click *return to module certificate*
3. Click *mediapop*

Here's a recording:

<img src="http://g.recordit.co/41WUwBo8oQ.gif">

I can pretty reliably cause this to happen on latest chrome.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. The registry has changed quite a bit in the past years!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
