### ISSUE TITLE
TF Cloudfront (origin {  domain_name ) not accepting s3 website_endpoint for s3 redirects

### ISSUE THREAD

**Issue by sandyfox** [hashicorp/terraform#18188]
### Terraform Version
RUNNING TERRAFORM 0.11.7 

```
...
```

### Terraform Configuration Files

```hcl

cloudfront:
resource "aws_cloudfront_distribution" "s3_distribution" {
  origin {
    domain_name = "${aws_s3_bucket.s3bucket.website_endpoint}"



s3: standard s3 condifg with s3  redirect request

 website {
     redirect_all_requests_to = "https://abcd.com"
  }

...
```

### Expected Behavior

TF should accept the s3 website_endpoint  in domain_name as its working fine when I update the cloudfront origins config from AWS console manually.

### Actual Behavior

aws_cloudfront_distribution.s3_distribution: InvalidArgument: The parameter Origin DomainName does not refer to a valid S3 bucket.

### Steps to Reproduce

create s3 bucket by configuring s3 static website by checking "redirect requests" on and provide Target bucket or domain with protocol.

configure cloudfront by setting website endpoint as origin.

run terraform apply.

### Additional Context

We need this feature for setting up the s3 redirects.
When you configure your CloudFront distribution, for the origin, enter the Amazon S3 static website hosting endpoint for your bucket. This value appears in the Amazon S3 console, on the Properties page under Static Website Hosting. For example:

http://bucket-name.s3-website-us-west-2.amazonaws.com

```When you specify the bucket name in this format as your origin, you can use Amazon S3 redirects and Amazon S3 custom error documents.```

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html#concept_S3Origin_website

**Comment by GregSharpe1** [comment]
@sandyfox Hey, are you still recieveing this issue, because I am :(

**Comment by ashanir** [comment]
@sandyfox Is this issue fixed ? I am facing the same issue.. I need it for url redirects..

**Comment by mildwonkey** [comment]
Hi all,

This issue has been moved to the [aws provider repository](https://github.com/terraform-providers/terraform-provider-aws), and any conversation should continue in the [new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/4757).

Since comments on this issue are generating notifications to subscribers, I am going to lock it and encourage you to view the [moved issue](https://github.com/terraform-providers/terraform-provider-aws/issues/4757).

Please continue to open new issues here for any other Terraform Core problems that you come across, and thanks!
