### ISSUE TITLE
Provide shorter alphanumeric PrefixedUniqueIds

### ISSUE THREAD

**Issue by danielhochman** [hashicorp/terraform#18208]
26 characters is a lot to consume when using a [PrefixedUniqueId](https://github.com/hashicorp/terraform/blob/fce30c14f051bed407216117cd36394a8f78c401/helper/resource/id.go#L35) due to the length constraints of some resources.

One way to do this might be to encode base-10 as base-35, i.e. `20180601195142368000000001` becomes `3YA2OB5D2JX5V6KJD`.

26 digit integers are also relatively difficult to compare for the human eye.

**Comment by bflad** [comment]
Hi @danielhochman 👋  Thank you for raising this.

Since it was created, the `PrefixedUniqueId` function was migrated along with other provider development framework functionality into the separate https://github.com/hashicorp/terraform-plugin-sdk repository. It appears there is a covering feature request in that repository here: https://github.com/hashicorp/terraform-plugin-sdk/issues/475

Since this is no longer relevant in this repository and there is a tracking issue in its new location, I'm going to close this issue. Thanks again.
