### ISSUE TITLE
Ec2 instance script Error 

### ISSUE THREAD

**Issue by anoopsrawat** [hashicorp/terraform#18215]
Hi There

i have facing some error in run terraform script ec2 inctance. below the error.

* aws_instance.server2: 1 error(s) occurred:

* aws_instance.server2: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        status code: 400, request id: d9d20b5a-baa8-4b56-b692-aad3ab8747b6
* aws_instance.server1: 1 error(s) occurred:

* aws_instance.server1: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        status code: 400, request id: 5ad96e16-6a29-413f-98f0-77487203817e

**Comment by bk9001** [comment]
The problem is terraform example that you likely copied from their learning site is WRONG.

The problem is vpc instance tenancy property.

Change this instance_tenancy = "dedicated" to instance_tenancy = "default".

It should work.

The reason is that dedicated instances are supported only for m5.large or bigger instances so your VPC and ec2 instance types are in conflict. You can look at the dedicated instances here.

https://aws.amazon.com/ec2/pricing/dedicated-instances/
