### ISSUE TITLE
https error while using consul as terraform backend

### ISSUE THREAD

**Issue by Prabhakar-cg** [hashicorp/terraform#18232]
terraform version 0.8.6

hi everyone,

i am using consul as terraform backend for storing state files.
  
terraform remote config -backend=consul -backend-config="address=xx.xx.xx.xx" -backend-config="skip_cert_verification=true" -backend-config=scheme=https -backend-config="path=some/path/terraform_state"
for skipping ssl verification i have given the env variable CONSUL_HTTP_SSL_VERIFY=false 

but still iam getting the following error
Error loading Terraform: Error reloading remote state: Get https://xx.xx.xx.xx/v1/kv/some/path/terraform_state: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs

in consul ui i could see the empty state file yet it is failing with above error.

Note : we are using self signed ssl certificate for consul with nginx and this setup absolutely working with http (xx.xx.xx.xx:8500).

**Comment by apparentlymart** [comment]
Hi @Prabhakar-cg! Sorry this isn't working as expected.

The `CONSUL_HTTP_SSL_VERIFY` variable is handled by Consul's own SDK (embedded into Terraform) rather than by Terraform itself, so I had a look into the Consul SDK code and it appears that this setting just passes through directly to the TLS settings for the HTTP client in the SDK.

However, you are using a particularly old version of Terraform here (from February 2017) and so it is possible that this version embeds an older version of the Consul SDK that predates this option, or has more limited support for it.

Are you able to connect to the same Consul server using the `consul` CLI tool and equivalent settings (including that environment variable)?

**Comment by Prabhakar-cg** [comment]
It is working fine with non HTTPS port {8500}.

However, i have noticed out of last 10 trials it was succeeded once with CONSUL_HTTP_SSL=true CONSUL_HTTP_SSL_VERIFY=false.  

But if i retrigger the same job, it is failing again with the same error

Error loading Terraform: Error reloading remote state: Get https://xx.xx.xx.xx/v1/kv/some/path/terraform_state: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs.
i am totally confused with this strange behavior.

**Comment by Prabhakar-cg** [comment]
Finally it worked, i believe it is the problem with root cacert so we have recreated new selfsigned ssl certificate and upgraded the terraform and consul version as well. @apparentlymart  thanks for the advice.

**Comment by apparentlymart** [comment]
Thanks for following up, @Prabhakar-cg! I'm glad you found a working solution.
