### ISSUE TITLE
"terraform console" wonky input handling on Windows

### ISSUE THREAD

**Issue by Dogers** [hashicorp/terraform#18242]
### Terraform Version
```
0.11.7
```

### Expected Behavior
Running "terraform console" gives you a ">" prompt which you can type commands in and delete text

### Actual Behavior
Running "terraform console" gives you a "[J>" prompt. You can type in, but deleting text just moves the cursor left and then overtypes.

### Additional Context
Specifically Windows - appears fine on Linux, so I'm guessing there's some funny input/text handling going on?

**Comment by apparentlymart** [comment]
Hi @Dogers! Sorry for this odd behavior, and thanks for reporting it.

I just want to confirm: are you using the native Windows build of Terraform, or are you using the Linux build inside Windows Subsystem for Linux (WSL)? I ask because the output shown here looks like a VT100 escape sequence as we'd use in the Linux build.

**Comment by apparentlymart** [comment]
Thanks for that extra detail, @Dogers!

It seems like our console routines are not correctly handling the Windows console, instead apparently treating it as a Unix-style terminal.

The team's focus right now is on preparing the configuration language improvements changes for the next major release, but we're planning to shift our focus to the UI and CLI workflow after that, so we can hopefully spend some time finding a more robust interactive console mechanism that has better cross-platform compatibility. Perhaps a newer version of our existing library [`readline`](https://github.com/chzyer/readline) will help, or we can evaluate something else like [`go-prompt`](https://github.com/c-bata/go-prompt).

Sorry for this oversight. We'll take a look as soon as we have some spare cycles!

**Comment by apparentlymart** [comment]
Ahh, another possible explanation here is misbehavior in the filtering code we have in order to simulate VT100 sequences from other commands using the Windows Console API. When we look at this more deeply, we should check whether that is interfering when the console code attempts to access the  Windows Console API directly.

**Comment by Dogers** [comment]
Not a problem - the console works, it's just _really odd_!

**Comment by JustinGrote** [comment]
Related to this item, terraform console doesn't accept "standard in" from either windows cmd, windows powershell, or powershell core (pwsh) on windows. So the following:

echo "1+5" | terraform console
doesn't work, it seems to just ignore the standard input and go straight to the prompt.

Works fine with both bash and pwsh on Linux.

The main reason I want this is to test rendered templates like so:

```powershell
function Get-RenderedTemplate ($templatename) {
  $target = "template_file.$templatename"
  terraform refresh > $null
  echo "data.$target.rendered" | terraform console
}

This works perfectly fine in PWSH on Linux, fails in PWSH or powershell on windows (I just get the interactive prompt)

**Comment by JustinGrote** [comment]
I did some testing with the https://github.com/chzyer/readline library and std input seems to work fine with the latest version, so a bump may be all that is required.

**Comment by andydix** [comment]
The output when using PowerShell is unusable too. I use VSCode with a PS terminal and the TF console actually works it's way *up* the screen when you hit Enter :)

I suspect the same fix for a standard command prompt will work in PowerShell too. Just need to not output the escape chars when on Windows. I wouldn't even care if there's no colour on the output. I just need it to be readable.

**Comment by trevor-viljoen** [comment]
Using cygwin on Windows 7, `terraform console` does not return a prompt at all. It just hangs. I've tried setting the `TERM` environment variable to `xterm` or `vt100`, but that has no effect.

**Comment by drewbiehd** [comment]
Terraform 12.20 with PSCore 6 issue still present.

**Comment by Dogers** [comment]
Oddly, it actually works better when using it through the new Windows Terminal! They must be handling the codes being printed, I guess?

**Comment by apparentlymart** [comment]
@Dogers yes, I believe a Windows 10 update last year sometime added vt100 support to the Terminal, so I expect that is what has helped here.

Some related issues about Windows terminal handling in general are #23053 and #22487, just to establish some links between them here for future reference.

**Comment by paultyng** [comment]
I'm able to repro this in automation in terraform-exec: https://github.com/hashicorp/terraform-exec/pull/64 This PR was for support for the console subcommand and works in Linux but not Windows (tested 0.11, 0.12, and 0.13). 

I attempted bumping the readline package, but I think that only affects the interactive handling not the stdin handling.

**Comment by apparentlymart** [comment]
Hi all,

As a side-effect of my work in #27487, to remove the legacy console emulation layer from Terraform, I ended up finding the root cause for both of the quirks discussed in this issue, and both are now fixed as a side-effect of that PR.

* The problem with the visible control characters in the prompt resulted from the fact that previous versions of Terraform have an additional filter on the output streams to translate virtual terminal control sequences into the classic Windows console API operations, but that only works for simple output and so the interactive prompt implementation used by `terraform console` was bypassing that layer and reading/writing the terminal handle directly.

    Because Terraform was otherwise working with the classic Console API, the console wasn't configured to accept raw virtual terminal sequences and so it just rendered them literally into the console buffer. After #27487, Terraform now places the console in virtual terminal mode before doing any other work and uses VT control sequences throughout, which means the console is able to properly process the VT sequences in the `terraform console` prompt.

    (As @JustinGrote noted, newer versions of the "readline" library we use for the `terraform console` prompt have their own special cases for dealing with Windows, and so upgrading might have been another way to fix this, but the special handling in the readline library is moot now that Terraform is putting the console in VT mode anyway.)

* The problem with the "piped" or "batch" mode not working on Windows was actually something different, although it was in the same neighborhood and so I ended up finding and fixing it at the same time anyway: Terraform does some rather odd stuff on startup in order to implement its special error message for a program crash (in Go terminology, a "panic"), part of which involves sending the standard error stream indirectly via a pipe so that it can sniff for panic messages.

    Terraform then has some other code that tries to work around that oddity by recovering the _original_ stdin/stdout/stderr handles to see if they are connected to a terminal. Unfortunately the implementation of that on Windows was incorrect: rather than finding the original stdin/stdout/stderr it requested specifically the _console_ handles, and therefore the question "is Terraform running in a terminal" would always return `true` on Windows, even if some of these handles were actually connected to a pipe or to a file via I/O redirection.

    The new behavior in #27487 now does the terminal initialization earlier, prior to the odd behavior with pipes and panic handling, so that it can be sure it's interacting with the _actual_ standard I/O handles. It therefore now correctly detects whether stdin is a pipe or a terminal on Windows, and thus should now behave as expected when accepting batch expressions via a pipe, as hashicorp/terraform-exec#64 wants to do.

The main point of #27487 was removing the compatibility layer for the classic Windows console API, so Terraform v0.15 and later will be officially supported only on sufficiently new versions of Windows to support virtual terminal mode in the console, which effectively means Windows 10 versions new enough to support WSL. Windows 8.1 is no longer officially supported although we did make a best-effort to verify that Terraform v0.15.0 will _broadly_ work there, although it's worth noting that the original odd `terraform console` behavior that prompted this issue _will_ persist when running v0.15.0 on older versions of Windows, because they don't support VT mode and will therefore continue to interpret the control characters as literals.
