### ISSUE TITLE
Crash with non-fast-forwarded git branches

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform#18276]
Terraform version 0.11.7

```hcl
module "example" {
  source = "github.com/example/example?ref=example"
}
```

If the example git branch is updated with non-fast-forward changes, `terraform init -upgrade=true` produces.

```
Error downloading modules: Error loading modules: error downloading 'https://github.com/example/example.git?ref=example': /usr/bin/git exited with 128: From https://github.com/example/example
 + 0ef7196...40f1552 example -> origin/example  (forced update)
fatal: Not possible to fast-forward, aborting.
```

**Comment by neomantra** [comment]
I just had this same problem.  To workaround, I went into the module's directory inside the `.terraform` folder, manually pulled, and then did a `terraform init -upgrade=true -reconfigure`.   Kinda janky but worked for my situation.

**Comment by zRosenthal** [comment]
You can run this script to force update all the remote git modules. 
```shell
initial_wd=$(pwd)
for d in .terraform/modules/*/; do
  if [ -d $d/.git ]; then
    cd $d
    git fetch --all
    git reset --hard origin
    cd $initial_wd
  fi
done
```

**Comment by pauldraper** [comment]
I use a more brute solution: `rm -fr .terraform; terraform init`

**Comment by danieldreier** [comment]
@pauldraper are you still able to reproduce this on current versions of Terraform, e.g. 0.13.x or the 0.14 beta releases?

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
