### ISSUE TITLE
Creating aws_sqs_queue with variable name cannot terraform destroy

### ISSUE THREAD

**Issue by KathrynN** [hashicorp/terraform#18314]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
variable "queue_name" {
  type        = "string"
  description = "ID for the KMS key used to encrypt SQS queues"
  default     = ""
}

variable "kms_key_id" {
  type        = "string"
  description = "ID for the KMS key used to encrypt SQS queues"
  default     = ""
}

resource "aws_sqs_queue" "my_queue" {
  name                        = "${var.queue_name}"
  receive_wait_time_seconds   = 2
  fifo_queue                  = true
  content_based_deduplication = true
  kms_master_key_id           = "${var.kms_key_id}"
}

```

Called with
```
terraform apply --var "queue_name=testing-terraform-destroy.fifo"
```

### Debug Output
None

### Expected Behaviour
Terraform destroys the queue with name testing-terraform-destroy.fifo

### Actual Behaviour
Terraform fails to destroy with message 
```
$ terraform destroy -auto-approve
Error: aws_sqs_queue.my_queue: only alphanumeric characters and hyphens allowed in "name"
```
### Steps to Reproduce
`terraform init`
`terraform apply --var "queue_name=testing-terraform-destroy.fifo"`
`yes`
`terraform destroy`

### Additional Context
Happens regardless of where the terraform is run, both in Jenkins and locally it fails to destroy the queue.  Is quite happy to make it though, and declaring the queue_name with a string within terraform also destroys without error!

**Comment by KathrynN** [comment]
Note, this is because I wasn't passing the var into terraform destroy.

**Comment by mildwonkey** [comment]
Hi @KathrynN  - 

This is expected behavior occurring because your default value for `queue_name` is an empty string `""`. When you run `terraform destroy` without assigning a value to the variable, terraform interprets the queue name as `name  = ""`. I

f you did not have a default value for `queue_name` set, the terraform cli would prompt you to specify that `queue_name`.

Your workaround is actually the expected workflow, though another option is to include a `terraform.tfvars` file with the queue_name variable set.

Reference: https://www.terraform.io/intro/getting-started/variables.html#assigning-variables
