### ISSUE TITLE
Ability to change periodic progress reporting interval in UI

### ISSUE THREAD

**Issue by jthimer** [hashicorp/terraform#18317]
#6162 and #5932 added a feature to the UI to display progress every 10s.

I'd like to be able to change that interval attribute.

I have some very long running workloads where a progress interval of 1m would be a much better; and perhaps even 5-min for my one workflow which takes 1-wk to run.  It would reduce the terraform log file considerably.

**Comment by apparentlymart** [comment]
Hi @jthimer! Thanks for this feature request.

We don't intend to make the progress interval configurable at this time, since each additional option represents additional maintenance burden and testing overhead. Terraform is designed for performing operations that take a few minutes at most, and definitely not operations that take more than one hour.

For an operation that takes a whole week to run, Terraform is probably not the best tool to use. While we're happy for Terraform to be used in ways we don't expect, our development focus is on the main intended use-cases.

Thanks again for sharing this request, and I'm sorry that it's not within Terraform's intended scope.
