### ISSUE TITLE
Add a way to debug/dump variable that don't pass the validation phase

### ISSUE THREAD

**Issue by sebastien-prudhomme** [hashicorp/terraform#18315]
Hi,

I'm facing "myvariable: should be a list" (or whatever validation constraint) error when applying Terraform and even with TF_LOG=1, it's hard to guess where the problem come from.

Will it be possible to add a "dump" interpolation function that dump the internal Terraform structure of a variable as a string and that i can use as an "output" to see what really happens?

Thanks

**Comment by mildwonkey** [comment]
Hi @sebastien-prudhomme -

Thank you for this request for a function! 

Something you can do now is use the `terraform console` command to see the structure of your variable. Here's a very simple example:

```hcl
$ cat main.tf
variable "list" {
  default = [ "1", "2", "3" ]
}

$ terraform console
> var.list
[
  "1",
  "2",
  "3",
]
> exit
```

**Comment by sebastien-prudhomme** [comment]
@mildwonkey Thanks, didn't the "console" command. Will try it as soon as i can.

**Comment by brycefisher** [comment]
I've tried using `terraform console` (which is awesome), but I've found lists to be treated differently during `terraform plan` in at least some cases.

I can't provide full details for a repro given the nature of my project, but here's the gist of the problem:

resource.tf
```
resource "aws_route_table" "private" {
  vpc_id = "${var.vpc_id}"
  count  = "${var.cidr_count))}"

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = "${element(split(",", var.nat_gateway_ids), count.index)}"
  }
}

resource "aws_vpc_endpoint" "s3" {
    vpc_id = "${var.vpc_id}"
    service_name = "${var.service_name}"
    route_table_ids = "${aws_route_table.private.*.id}"
}
```

When running terraform plan I get this error:

> Error: aws_vpc_endpoint.s3: route_table_ids: should be a list

Trying this in the console:

```
$ terraform console

> "${aws_route_table.private.*.id}"
[
  "rtb-c12345678",
  "rtb-b12345678",
  "rtb-a12345678",
]
```

I don't know if this a problem related to using remote state, or an issue with the AWS provider, but I think its more a problem with the interpolation itself since I can get the list to display in the console but not in the plan.

**Comment by apparentlymart** [comment]
Hi @brycefisher! Sorry for that weird error.

I think what you are hitting here is a bug in Terraform 0.11 and earlier (that is, all _released_ versions) where any list containing an unknown value (`<computed>` in the plan output) is turned into an unknown value itself, and current versions of Terraform don't consider an unknown value to be a list for the purpose of this validation.

This should work properly in the forthcoming 0.12 releases of Terraform, where both of the above problems are addressed: a list containing a mixture of known and unknown items remains as such during evaluation, and Terraform is able to retain type information for unknown values so it can understand the difference between (for example) "unknown string" and "unknown list of strings" during validation.

In the mean time, I think the usual workaround for this is to first run Terraform with `-target=aws_route_table.private` so Terraform can focus on making sure all of the route tables have known ids, and then run Terraform again as normal to complete the apply.

**Comment by brycefisher** [comment]
Great news! Thanks @apparentlymart !

**Comment by apparentlymart** [comment]
Hi @sebastien-prudhomme! Sorry for the long silence here.

In the master branch we have a new feature (ready for inclusion in the v0.12.0 release) where expression evaluation and validation errors will include in their output information about the values of any  variables mentioned in the expression, as in this example:

```
Error: Error in function call

  on cidrsubnet-crash.tf line 23, in resource "aws_subnet" "ecs_subnet_prv":
  23:   cidr_block              = "${cidrsubnet(local.cidr_block_private_ecs, ceil(log(var.max_subnets_prv, var.newbits_prv)), (var.netnum_private_ecs + count.index))}"
    |----------------
    | count.index is 0
    | local.cidr_block_private_ecs is "10.20.102.0/24"
    | var.max_subnets_prv is "16"
    | var.netnum_private_ecs is "6"
    | var.newbits_prv is "1"

Call to function "cidrsubnet" failed: not enough new bits for network number 12
```

This will be included in messages automatically, without the need for any configuration changes. Since there are lots of different errors in Terraform that relate to expression evaluation or validation it will take some time before we've updated all of them to collect the information required to make this happen, but a number of them are already updated in master and we'll catch stragglers in subsequent minor releases as we find them.

This should allow for the sort of debugging you mention without the need for a new function, so I'm going to close this one out. You'll be able to see this in action for most errors in the v0.12.0 release, and then we'll discuss improvements for error messages we haven't updated yet in separate issues/PRs after that.

Thanks for this feature request, and thanks for your patience while we laid the groundwork to make this sort of error reporting possible.

**Comment by brentarias** [comment]
Is there a way to print/echo a value *without* creating an output variable?  This would be particularly useful in a case where modules are nested more than one deep.  It is a pain to write output variables at each level of a module-invocation hierarchy simply so that the output values can finally percolate level-by-level to the root...so that I can see them when I'm trying to debug.
I am using TF 0.11.14.
