### ISSUE TITLE
No complaints when passing a bogus resource name to `-target`

### ISSUE THREAD

**Issue by vide** [hashicorp/terraform#18324]
When running `terraform plan|apply` with an `-target` restriction, Terraform will output a different result when handling a non-existent resource depending on if the target is a basic resource or a module.

```
$ terraform plan -target=foobar
Releasing state lock. This may take a few moments...

Error: Error asking for user input: invalid resource address "foobar"

$ terraform plan -target=module.foobar
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Releasing state lock. This may take a few moments...
```

Moreover the first command exits with status 1 (error) while the second command exits with status 0 (everything's fine)

### Terraform Version

```
$ terraform -version
Terraform v0.11.7
+ provider.aws v1.24.0
+ provider.null v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0

```

### Expected Behavior

Both commands should fail the exact same way given that the resources do not exist

### Actual Behavior

If the resource name starts with `module.` of actually if it has a dot in the name `-target=foo.bar` Terraform thinks that everything is ok, there are just no changes to apply.

**Comment by apparentlymart** [comment]
Thanks for pointing this out, @vide!

The distinction between these two situations in the current implementation is that the first is detecting invalid address syntax, whereas the second is structurally valid but doesn't match anything.

However, I agree with you that there's no real use-case for filtering out _all_ of your resources using `-target`, and so it should be an error if nothing is left after the target filtering is complete. That's not going to be a simple change given how targets are implemented today (it's a post-processing filter on the generated graph) but I can imagine us doing a pre-validation step where before we even start _building_ the graph we make sure that everything referenced is something that exists.

Our attention is focused elsewhere right now (on the configuration language) but we can look into this a bit more at some point after the next major release.

**Comment by vide** [comment]
@apparentlymart Thanks for the explanation! It's not a big deal, nothing breaks seriously but sometimes it makes difficult spotting a typo. I will wait:)

**Comment by 007** [comment]
Happy Birthday #18324!

Is there any use-case where you would want a `target` that doesn't exist to pass silently? I've had this bug hit several times, and always wondered what I broke when it showed no diff.

I would suggest a further refinement, in that if I specify `N` targets then all `N` should exist for the plan to proceed. If I'm trying to do an "atomic" change of 2 resources and mistype one it could cause downtime until it's realized.

**Comment by vide** [comment]
@apparentlymart I think this still applies to 0.12 which it's now officially out, do you think this issue (although minor) can have some attention now?

**Comment by apparentlymart** [comment]
Hi all!

I tried to spend a little time on this today, but quickly found it's more complicated than it first appears, particularly now that Terraform supports `count` and `for_each` for modules and so there are many possible dynamic addresses for a particular configured module or resource, and we can't know which are valid until long after we already constructed the graph and thus filtered out anything that didn't match at least one target.

Since we suggest `-target` only for exceptional use, the maintenance cost of some complex logic to dynamically recognize whether each `-target` argument matched something unfortunately doesn't really seem to pay for itself in terms of impact. While I would like to return an explicit error message here in an ideal world, I don't think we can justify a non-trivial algorithm for deciding whether to show that error message for a feature that is supposed to be rarely used and therefore has low impact by definition.

At this point we are constrained by [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html) anyway, and so my initial attempt here was to emit a warning rather than an error, but the unjustified complexity would still be there even so.

I'm sorry we ended up leaving this open so long before reaching this conclusion, but sometimes the complexity of a feature isn't clear until you actually try to implement it. Given that we're unlikely to change this behavior for the foreseeable future, I'm going to close this. Thanks!
