### ISSUE TITLE
Can't abort "terraform plan" during refresh

### ISSUE THREAD

**Issue by sgrimm-sg** [hashicorp/terraform#18345]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.14.1
```

### Terraform Configuration Files

The resource configuration doesn't seem likely to be relevant, but we are using remote S3 state:

```hcl
data "terraform_remote_state" "payment" {
  backend = "s3"

  config {
    bucket         = "REDACTED"
    key            = "REDACTED"
    region         = "us-east-1"
    encrypt        = "true"
    dynamodb_table = "terraform-state-lock"
  }
}
```

### Debug Output

https://gist.github.com/sgrimm-sg/42c73d35d1a52b1701e6fdfea401778c

### Crash Output

N/A

### Expected Behavior

Hitting control-C during `terraform plan` should exit immediately, perhaps after doing whatever cleanup it needs to do.

### Actual Behavior

A message is immediately printed saying the command is shutting down, but it continues to run to completion, refreshing all the resources from AWS and then printing the plan.

### Steps to Reproduce

With an AWS configuration of nontrivial size, such that it takes substantial time to refresh, and with remote state:

`terraform plan -out=/tmp/plan`

Hit control-C early on, before it starts printing messages about refreshing resources. Then observe that the entire refresh runs.

### Additional Context

Running Terraform on OS X High Sierra.

### References

#16571 seems similar to this but a fix was merged in December.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @sgrimm-sg!

Currently the same cancellation mechanism is used for all Terraform commands, but you're right that in principle the `terraform plan` command could have a more "graceless" shutdown since it doesn't have any externally-visible side-effects. We're hoping to shift our focus to UI-ish work after the next major release (which is focused on configuration language) and so I'd like to spend some more time investigating this when we get there.

**Comment by nick4fake** [comment]
I'm a bit confused about https://github.com/hashicorp/terraform/issues/16571 being closed.
Technically we still can not interrupt terraform plan on some stages, so one needs to force-close it.

**Comment by raxod502-plaid** [comment]
Can we at least get a better message than the FUD-inducing `Please wait for Terraform to exit or data loss may occur`? Sometimes it's just not an option to wait for Terraform to exit, e.g. network connectivity problems meaning it will never finish refreshing. In that case it is urgently important to inform the developer of what will actually happen if the process is interrupted. And if it's actually possible for data loss to occur during a **read-only** plan operation, something seems seriously, urgently, the-world-is-on-fire wrong with Terraform. That could happen for a million different reasons, e.g. terminal emulator crashes, accidental keypress, wifi cut out, battery died, etc. This is especially important because if your Terraform state gets corrupted, you are extremely screwed due to the complete lack of any bulk import support. I am confused why this issue has not been prioritized.

**Comment by jbardin** [comment]
The current master branch and upcoming 0.14 release will no longer use a separate refresh walk, which means this specific issue will no longer be a concern. 

Thanks!
