### ISSUE TITLE
Targeted destroy on multiple instances removes outputs for all instances

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#18348]
### Terraform Version

```
$ terraform version
Terraform v0.11.7
+ provider.aws v1.25.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "eu-west-2"
}

data "aws_availability_zones" "available" {}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  count                       = "${length(data.aws_availability_zones.available.names)}"
  ami                         = "${data.aws_ami.ubuntu.id}"
  instance_type               = "t2.micro"
  availability_zone           = "${data.aws_availability_zones.available.names[count.index]}"
  associate_public_ip_address = true

  tags {
    Name = "Radek ReproCase ${count.index}"
  }
}

output "ip" {
  value = "${zipmap(
    aws_instance.web.*.id,
    aws_instance.web.*.public_ip
  )}"
}

output "zones" {
  value = "${data.aws_availability_zones.available.names}"
}
```

### Expected Behavior
(output from the second `terraform output`)
```
ip = {
  i-01504c8d27f0317c1 = 35.177.101.147
  i-076ff38cec16029a1 = 18.130.125.51
}
zones = [
    eu-west-2a,
    eu-west-2b,
    eu-west-2c
]
```

### Actual Behavior
(output from the second `terraform output`)
```hcl
zones = [
    eu-west-2a,
    eu-west-2b,
    eu-west-2c
]
```

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`
1. `terraform output`
1. `terraform destroy -target=aws_instance.web[1]`
1. `terraform output`

**Comment by apparentlymart** [comment]
Hi @radeksimko,

Looking at this one again with fresh eyes :eyes:, I think this behavior is technically correct, or at least as correct as it can be within Terraform's current semantics.

By destroying one out of the set of instances used to construct the output here, you've created a similar situation to what happens before _any_ of the resources have been created, where there isn't enough information to compute the output value. That is, the full output value as seen in expressions in the caller would effectively be this (pseudo-syntax because there's no real syntax for writing an unknown value):

```
ip = {
  i-01504c8d27f0317c1 = 35.177.101.147
  (unknown) = (unknown)
}
```

Since partially-unknown values are only allowed during the course of plan/apply, must treat this output as a whole as not set yet when saving it in the state.

If this were in a child module rather than the root module then a subsequent `terraform plan` would produce that partially-unknown map from above and the unknown values would propagate through as normal. The weirdness with `terraform output` is just because it's looking at a snapshot of the subset of the outputs that were complete at the time `terraform apply` (or, in this case, `terraform destroy`) completed, excluding any of them that were not fully complete at that point.

This is a tricky edge case, but since `-target` is for exceptional use only and destroying only one instance out of a set is a rare operation I don't think we can justify additional complexity in the output handling behavior to do something else in this case.

I'm going to close this out for now. In future we might come up with a way to tweak the behavior here to do something different, but in the short term I think we must just accept this as a quirky natural consequence of the normal expression resolution behaviors.
