### ISSUE TITLE
Terraform version un-awareness?

### ISSUE THREAD

**Issue by Binternet** [hashicorp/terraform#18342]
### Terraform Version

```
0.11.7
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

```
$ terraform console

Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.7'

Please run at least that version of Terraform to continue.

$ tf -v
Terraform v0.11.7
```

### Actual Behavior

Terraform doesnt understand the version is correct...

**Comment by apparentlymart** [comment]
Hi @Binternet! Sorry for that strange behavior.

I'm honestly not sure what's going on here, since I don't have a lot of context to work with.  However, based on what you shared I do have a question: does that `tf` alias you used to run `terraform version` refer to the same Terraform binary as was run when you ran `terraform console`?

**Comment by Binternet** [comment]
terraform is named `tf` on my machine and located in `/usr/local/bin/tf`
so yes, thats the same one...

**Comment by Binternet** [comment]
wow totally my fault terraform was older than tf (different files)
