### ISSUE TITLE
terraform returns a cryptic error when credentials file is missing

### ISSUE THREAD

**Issue by czka** [hashicorp/terraform#18369]
```
$ terraform version
Terraform v0.11.7
+ provider.google v1.15.0
```
I'm referring to a non-existent file `key-qa.json` in my Terraform code (my bad):
```
$ grep credentials 01_init.tf 
    credentials = "key-qa.json"
  credentials = "${file("key-qa.json")}"
```
```
$ ls key-qa.json
ls: cannot access 'key-qa.json': No such file or directory
```
But `terraform` is not helping. It returns a cryptic message:

```
Error initializing new backend: 
Error configuring the backend "gcs": Error parsing credentials 'key-qa.json': invalid character 'e' looking for beginning of value
```
I'd rather have it say:
```
Look, you stupid bastard - you've got no 'key-qa.json' in place.
```
Or something along these lines.

**Comment by apparentlymart** [comment]
Hi @czka! Sorry for this unhelpful error message, and thanks for reporting it.

It looks like the problem here is that this argument accepts either a filename _or_ an inline key JSON, and so if the string doesn't refer to a file that exists it tries to parse the string itself, which is then not valid JSON in your case.

This seems to be mimicking similar behavior from the Google Cloud provider. In retrospect the design of this is unfortunate: it would be better for this to be two separate arguments `credentials` and `credentials_file`, so Terraform can understand your intent better. It looks like this strange behavior is an attempt to preserve compatibility with earlier versions that expected a filename after switching to expecting inline JSON.

Because the original behavior change here comes from 2015, it's likely that we could phase it out now and switch to having two separate arguments. However, since the behavior here is trying to be consistent with the Google Cloud provider, any change to this interface should be led [over there](https://github.com/terraform-providers/terraform-provider-google/).

In the mean time, I could see us reworking this code so that if the string is neither the path to a valid file nor valid JSON then it would return a tailored error message that mentions both possibilities, rather than returning just the error message for the JSON parsing since that happens to be the last thing tried.

The Terraform Core team is focused elsewhere right now (on [configuration language changes for v0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview)) so we won't be able to look at this immediately, but we'll leave this on the list so we can remember to fix it up later. If anyone else has the time and motivation in the mean time, we'd love to review a PR for this.

Thanks again for pointing this out!

**Comment by mildwonkey** [comment]
I'm going to close this issue; changes to the configuration are in the hands of the goole provider developers, and the documentation has been updated to specify that you should use `file()` when using a credentials file.

If this is still an issue with the latest version of terraform, I recommend opening an issue with the google provider. Thanks!
