### ISSUE TITLE
external network - openstack

### ISSUE THREAD

**Issue by HassanIstanbouli** [hashicorp/terraform#18364]
### Terraform Version

`0.11.7`
...
```

### Terraform Configuration Files
<!--
Paste the relevant parts of your Terraform configuration between the ``` marks below.

For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file. For security, you can also encrypt the files using our GPG public key.
-->

```hcl
...
```

### Expected Behavior
it seems like ,terraform dose not support "External Network " in OpenStack Provider because i can't create it . in other words there isn't an "External Network" Attribute .
i can make it shared but i can't make it external :( 

### References
https://www.terraform.io/docs/providers/openstack/r/networking_network_v2.html

**Comment by tdmalone** [comment]
This is probably better posted at https://github.com/terraform-providers/terraform-provider-openstack/issues

**Comment by HassanIstanbouli** [comment]
Thanks, i'll posted there too

**Comment by apparentlymart** [comment]
Hi @HassanIstanbouli,

As @tdmalone noted, this is related to a provider-specific feature and so it'll need to be handled inside the provider's own repository. Since I see you already opened terraform-providers/terraform-provider-openstack#356 for this, I'm going to close this one just to consolidate the discussion over there, since I believe implementation of that would happen entirely within the other repository.

Thanks!

**Comment by HassanIstanbouli** [comment]
Thanks @apparentlymart 
you're right , it's better to continue with this issue there .
and i noticed a commit to "Terraform OpenStack Provider" repository related to this issue .
i hope this problem be solved in the next release .
Thanks!
