### ISSUE TITLE
Terraform v0.10.7 panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mauriziod** [hashicorp/terraform#18370]
### Terraform Version

```
Terraform v0.10.7
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

GIST: https://gist.github.com/mauriziod/e8c0c87a01ddc033a7b0845dfef3740f

### Expected Behavior

While trying to run terraform plan on working directory.

### Actual Behavior

Terraform tried to update the providers and crashed. 

### Steps to Reproduce

1. `terraform init`

**Comment by apparentlymart** [comment]
Hi @mauriziod! Sorry for this crash, and thanks for reporting it.

Based on the stack trace in the crash report, it looks like this was a bug in the configuration language decoder where it was trying to report an error but encountered another error in the process of doing so.

The error it was trying to report is that an argument in the configuration was expected to be a string but was actually something else. I _think_ it's finding an empty block `{}` where a string is expected, but then crashing when trying to include the location of that block in the error message because it's empty :man_facepalming: .

With that said, I expect you could work around this if you can figure out where in your configuration there is a mistyped argument, and fix it so that a string is used instead. I think the problem will be inside `variable` block, based again on the stack trace.

The good news is that the crashing codepath here has been entirely replaced as part of [the configuration language improvements in progress for 0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview), so I expect this is already fixed on the development branch. We'll leave this issue open here as a reminder to test it once we're closer to release. If you are able to track down a configuration example that triggers the crash then that'd be very helpful in verifying the fix in the forthcoming release.

**Comment by mauriziod** [comment]
Thanks for the quick reply, I will revisit the issue and comment if that solves it. Apologies for my late reply.

**Comment by mauriziod** [comment]
Found the variable, terraform was expecting a type = "list" and for some reason (fat-finger probably) the content was replaced with variable "myvar" { type [] }
