### ISSUE TITLE
Passing list elements from module output inside looped resources with count

### ISSUE THREAD

**Issue by Unb9rn** [hashicorp/terraform#18395]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files
Let's say I have a module, which generates some ids and then outputs them:

```hcl
output "etcdapiserver_hostname_list" {
  value = ["${random_id.etcdapiserver-id.*.hex}"]
}

resource "random_id" "etcdapiserver-id" {
  byte_length         = 4
  count               = "3"
}
```
Now I want to pass it inside a resource in main.tf:

```hcl
resource "openstack_compute_instance_v2" "etcdapiserver" {
  count   = "3"
  name    = "etcdapi-node-${element(module.ignition.etcdapiserver_hostname_list.*, count.index)}"
}
```
Which gets me an error:
`Error: resource 'openstack_compute_instance_v2.etcdapiserver' config: "etcdapiserver_hostname_list.*" is not a valid output for module "ignition"`
### Expected Behavior

Elements of list from module get assigned to openstack_compute_instance_v2.etcdapiserver.*.name by count.index.
### Actual Behavior

Error "not a valid output for module"
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @Unb9rn,

The general syntax for accessing the element of a list is `list[index]`. In your case, that would be something like `module.ignition.etcdapiserver_hostname_list[count.index]`.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
