### ISSUE TITLE
Feature request: Add 'stage' meta variable to Terraform

### ISSUE THREAD

**Issue by tiwood** [hashicorp/terraform#18401]
Hi,

we currently have to use some external data sources to gather details about resources created by the same Terraform configuration.

Obviously during 'Plan' stage the custom data source query won't return any results, as we did not create the resources just yet.

If I would know the stage I'm in, in this case 'Plan', I could easily provide a computed or dummy value for the custom data source, but as of now that seems impossible.

I suggest adding a new Terraform meta variable which I could pass down to external data sources or custom provisioning scripts.

For example:
```hcl
data "external" "get_some_stuff" {
  program = ["pwsh", "${path.module}/myquery.ps1"]

  query = {
    terraform_stage = "${terraform.stage}"
  }
}
```

terraform.stage would be one of the following strings: plan, apply, destroy

**Comment by apparentlymart** [comment]
Hi @tiwood! Thanks for sharing this use-case.

Unfortunately I don't think we can do exactly what you described here because correct behavior of Terraform requires that expressions produce the same value during plan as during apply.

In principle it would be possible to support this special variable only inside `data` blocks, since they are evaluated only either during plan _or_ apply, but so far there are no differences in what is available for interpolation in `resource` vs. `data` blocks and I'm nervous about changing that due to the implementation and documentation complexity it'd cause.

Based on how you described your use-case, I'd suggest one of the following paths:

* If you want to return a dummy value when the real resources haven't existed yet, have the external script check itself whether the resources in question exist and return the dummy value if not, regardless of what "stage" Terraform is running. If you need to distinguish "created but empty" from "not created at all" then this would require some sort of marker resource that _always_ exists once the configuration has been applied which the script can use to detect it.

* If the data source is truly only useful after the configuration has been applied once, interpolate a computed attribute from one of your resources into its `query` and that'll force Terraform to read it only during the apply phase, so the script then won't need to deal with the "not yet applied" case at all. If there's no resource already available for you to interpolate, you could use a standalone `null_resource` as a placeholder:

  ```hcl

  resource "null_resource" "example" {
  }

  data "external" "get_some_stuff" {
    program = ["pwsh", "${path.module}/myquery.ps1"]

    query = {
      # The id of a null_resource is the time it was created, so passing this
      # here will force Terraform to defer the initial fetch of this data source
      # until after the null_resource is created (during the apply step) but will
      # allow it to be fetched during the plan step on subsequent runs.
      applied_timestamp = "${null_resource.example.id}"
    }
  }

  ```

  If the Terraform configuration is creating something that the data source then reads information about, it'd be clearer to interpolate a computed attribute from the resource for _that_ object, making the relationship between the two explicit.

Please note that if you are using a data resource to fetch data that depends on side-effects of the Terraform configuration then your plans will always be one step behind, and so you may never reach a stable state if each plan ends up building on the result of applying the previous one. We'd usually recommend against self-reflective configurations like this because they can be hard to maintain over time, but if you write the data source script carefully then this sort of thing can potentially work.
