### ISSUE TITLE
provider/variable sharing in modules

### ISSUE THREAD

**Issue by a14m** [hashicorp/terraform#18406]
not to convolute the repo with a similar [question](#6510)... but is there a way of abstracting the provider for all the modules defined in a project.

for example, I have this project

    ├── modules
    │   ├── RDS
    │   └── VPC
    └── stacks
        ├── production
        │   └── main.tf
        └── staging
            └── main.tf

and it works fine...
the problem is with the definition of modules

    ├── RDS
    │   ├── README.md
    │   ├── main.tf
    │   ├── providers.tf
    │   └── variables.tf
    └── VPC
        ├── README.md
        ├── main.tf
        ├── providers.tf
        └── variables.tf

the provider in both of these modules are exactly the same

    # providers.tf
    provider "aws" {
      region = "${var.region}"
      version = "~> 1.26"
    }

and the variables in each module are different but they all have the `region` variable.

    # variables.tf
    variable "region" {
      default     = "eu-central-1"
      description = "AWS region."
    }
    # other module dependent variables...

is there a way to define those bits of information on the modules level
so that I end up with something roughly like this

    ├── modules
    │   ├── providers.tf  <<< include the *shared* provider definition block
    │   ├── variables.tf  <<< include the *shared* region vaiable definition block
    │   ├── RDS
    │   │   ├── README.md
    │   │   ├── main.tf
    │   │   └── variables.tf
    │   └── VPC
    │       ├── README.md
    │       ├── main.tf
    │       └── variables.tf

Thanks in advance.

**Comment by apparentlymart** [comment]
Hi @a14m!

In Terraform 0.11 we refined the ways in which providers pass between modules to better support this situation. As of that release, we recommend that most users put `provider` blocks _only_ in the root module, with child modules then inheriting the root provider configurations or being passed them explicitly.

In your case then, the `provider "aws"` block would belong in `stacks/production` and `stacks/staging` (the two root modules, presumably) and there would be no `provider` blocks in the modules at all.

At present this pattern will hit the limitation discussed in #16835, preventing those child modules from declaring which version of the `aws` provider they need. [The next major version of Terraform](https://www.hashicorp.com/blog/terraform-0-1-2-preview) will include the new syntax discussed in that issue so that the modules will be able to declare their provider version requirements separately from the provider configurations themselves:

```hcl
# (not yet implemented and details may change before release)

terraform {
  required_providers = {
    aws = "~> 1.26"
  }
}
```

There is more information on this in the [Providers within Modules](https://www.terraform.io/docs/modules/usage.html#providers-within-modules) section of the documentation, including an optional syntax for explicitly passing providers into child modules for situations where the default inheritance behavior is insufficient.

I believe that this (except for the forthcoming change discussed in #16835) covers your use-case. Please let me know if I missed something!

**Comment by a14m** [comment]
Thanks a lot... this covers the use-case of provider configuration...
as for the shared variable part (I did some research after opening this -sorry for not thoroughly doing the research before opening this issue- ) and I found those issues who discuss the issue in details and the conclusion (TLDR: sharing variables between modules against terraform clarity principle)

adding those issues here for future reference:
- We've discussed global variables in the past:
- #5480
- #4585
- #2714
- #1742
