### ISSUE TITLE
Obsolete remote_state web docs

### ISSUE THREAD

**Issue by Skardian** [hashicorp/terraform#18430]
Hi,

The [remote_state data documentation](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) is still referencing the deprecated `environment` argument. I noticed that both [this repository](https://github.com/hashicorp/terraform/blob/5c58ef16f7b57784e1be810364566ae4236ccf48/website/docs/providers/terraform/d/remote_state.html.md) and the [terraform-provider-terraform](https://github.com/terraform-providers/terraform-provider-terraform/blob/master/website/docs/d/remote_state.html.md) markdown files are updated with the `workspace` argument.

The web should reflect those changes. Am I missing something?

**Comment by apparentlymart** [comment]
Hi @Skardian,

The website usually gets updated only as part of our release process, so I expect what's happened here is that there just hasn't been a release since those updates were made. It'll get fixed up at the time of the next release.

Thanks for pointing this out!

**Comment by jamesrwhite** [comment]
In case this has been forgotten about the docs are still out of date after the release of `0.11.8`.

**Comment by apparentlymart** [comment]
Thanks for the reminder, @jamesrwhite!

Our Terraform Core team is currently focused on work for the Terraform 0.12 release and so we've not been able to get to this yet, but at the very least we should be able to get this updated as part of the doc updates for 0.12 (which will include some changes to `terraform_remote_state`), if not before.

The problem (which I think is also covered in another GitHub issue, though I couldn't find it quickly to reference it) is that the `terraform-website` repository is still set up to publish the docs from the separate `terraform-provider-terraform` repository, rather than from the integrated version of this provider that is now maintained in _this_ codebase.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

With the v0.12.0-alpha1 build out and us shifting into a bug-fixing mode rather than a full-on development mode we finally had some spare time to look into this. @mildwonkey got this fixed up in hashicorp/terraform-website#538 (always amazing how much simpler something looks when it's already been done!) and the latest docs are now published on the website.

There will be some more revisions of these docs as we prepare for the v0.12.0 final release, but getting the doc build process pointed at the right copy of the docs was the prerequisite for getting things working again here.

Thanks for pointing this out, and sorry again for it taking so long for us to be able to take a look at it.
