### ISSUE TITLE
[question] Building a custom AMI, like Packer?

### ISSUE THREAD

**Issue by fmunteanu** [hashicorp/terraform#18432]
I was wondering if we have the capability in Terraform to build a custom AMI, similar to Packer. For example, I take an existing CentOS7 AMI available into market and execute multiple commands to install rpm packages, enable services with systemd or copy files from a git repo into specific OS directories.

I understand the logic of using Packer, but having everything coded with Terraform is much more convenient for me. One tool for everything, porting code to infrastructure.

**Comment by apparentlymart** [comment]
Hi @fmunteanu! This is a great question, and so I'd like to answer it in some detail.

In principle, you can use the `aws_instance`, provisioners, and `aws_ami_from_instance` to emulate the sort of thing packer does, but it'll take a lot of custom scripting on your part to e.g. have Terraform destroy the instance after the AMI has been created but not destroy the AMI itself. Packer has all of this behavior built in, since its configuration model and workflow understands explicitly the difference between the target artifact and the temporary infrastructure required to build it. Terraform does not make these distinctions itself, because it is aimed at solving a different problem.

We provide these AWS provider features to give users some flexibility to solve unusual problems, but we do not recommend using Terraform as a build tool. We believe in composing multiple tools to solve a problem so that each can play to its strengths. While of course Packer is the most familiar tool for us at HashiCorp, we encourage users to use whatever tool makes sense for building artifacts to pass in to Terraform. "One tool for everything" is not the way we tend to approach problems, since the workflow requirements are different even though the underlying actions (populating an EC2 instance and then copying it to make an AMI) are the same.

Lots of users enjoy the flexibility that comes from separating build and deploy steps. For example, if you build an AMI using a tool like Packer separately from your Terraform configuration then you can more easily deploy that same AMI multiple times in different environments, and thus you can test your AMI in a development or staging environment before deploying an identical image to production. If you find that after deployment there is an issue with the image, you can easily roll back to the previous AMI with a Terraform configuration change rather than having to rebuild it.

This is an application of [our general principles](https://www.hashicorp.com/blog/the-tao-of-hashicorp). In this case in particular, the most relevant are "Simple, Modular, Composable" (Terraform intends to solve the problem of provisioning infrastructure), "Workflows, not Technologies" (you are free to use whichever tool you want to build an AMI, or even build it manually) and "Pragmatism" (we provide `aws_ami_from_instance` because we know there are unusual situations that warrant different approaches than we'd normally expect or recommend).

I hope that helps, and thanks again for this great question! We are not dogmatic about particular approaches, so if you feel that Terraform is the right solution to your particular problem we're happy for you to use it, but we believe (from experience as users of the product ourselves, and based on user feedback) that separating these steps is best in the common case, and so Terraform's design is (and will continue to be) optimized for that approach.
