### ISSUE TITLE
Add Pingdom provider

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1844]
I was thinking about automating our pingdom checks management and it would be nice if we could use Terraform for this.

There are only two Go libraries for Pingdom at the moment (at least from what I was able to find on Github) and this one seems to be more complete https://github.com/russellcardullo/go-pingdom

**Comment by knuckolls** [comment]
This is a good idea. :+1:

**Comment by chrisferry** [comment]
Any news on this?

**Comment by radeksimko** [comment]
@chrisferry have you tried using https://github.com/russellcardullo/terraform-provider-pingdom ?

Does it work well?

**Comment by hsingh6764** [comment]
Any update?

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!
