### ISSUE TITLE
Rich template language

### ISSUE THREAD

**Issue by errordeveloper** [hashicorp/terraform#1845]
As #1778 has provided a way of doing interpolation in files, next step would be to see whether there could be a richer language available from inside a template file.

Such language would help for generating provisioning data that could be passed to a provide as metadata for setting up VMs or basic configuration files to be uploaded to VMs.

**Comment by errordeveloper** [comment]
In one instance I have implemented [a shell script][1] that looks rather quite ugly for what it's able to do. It is being called from [`infra/main.tf#L44`][2] and [`main.tf#L126`][3].

[2]: https://github.com/errordeveloper/weave-demos/blob/4fd2bcb0e353b70016df9fea1408acad8f0bbc3c/terraform-example/infra/main.tf#L44
[3]: https://github.com/errordeveloper/weave-demos/blob/4fd2bcb0e353b70016df9fea1408acad8f0bbc3c/terraform-example/infra/main.tf#L126

[1]: https://github.com/errordeveloper/weave-demos/blob/4fd2bcb0e353b70016df9fea1408acad8f0bbc3c/terraform-example/genenv.sh

**Comment by errordeveloper** [comment]
I should also clarify that in my use-case it's CoreOS that is being provisioned, and many other folks would probably suggest that a configuration management tool is what I want. However, I believe that this this kind of mechanism would be of use when one needs to seed the initial configuration files for their configuration management tool to run.

**Comment by apparentlymart** [comment]
It could be nice to use the same template language as consul-template, but with access to Terraform resources and variables within the calling module rather than access to Consul concepts like services and keys.

This could then allow Terraform provisioning to do the same sorts of things consul-template does, but for configurations that only vary per-deploy, rather than those that can vary at runtime. Having the template be able to access the resources directly means being able to easily iterate over list attributes and resource wildcards, which wouldn't be so easily to achieve with the explicit variables map in the existing template implementation.

Example haproxy template fragment, based on the one for consul-template:

```
listen http-in
    bind *:{{var "load_balancer_listen_port"}}{{range resource "aws_instance.server.*"}}
    server {{.id}} {{.private_ip}}:{{var "server_instance_listen_port"}}{{end}}
```

Of course, to achieve this would require a rather unusual resource type whose dependencies are defined by the contents of the external template file, rather than by interpolations within the resource definition itself.

**Comment by mitchellh** [comment]
I think we should just extend the `template_file` resource to support a `type` parameter that specifies the template type and we can support a variety there.

**Comment by errordeveloper** [comment]
:+1:

**Comment by progrium** [comment]
`template_file` with a way to provide types would be nice, but ideally if `shell` were one of them. Or perhaps support https://github.com/gliderlabs/sigil directly, as that's what I'll be using.

**Comment by 7heo** [comment]
@mitchellh :+1: that would be really great.

**Comment by ketzacoatl** [comment]
Saltstack makes the template/rendering engine plugable, so users can pick which renderer to use - it has worked out very well in practice and I believe that would be a great addition to Terraform's template provider!

**Comment by lbernail** [comment]
A richer templating engine would definitetly help!
:+1:

**Comment by errordeveloper** [comment]
We had been using [Jsonnet](http://jsonnet.org/) in [Kubernetes Anywhere project](https://github.com/kubernetes/kubernetes-anywhere/blob/1747396c9445ba4cea51633f660dacc661ac7694/phase1/gce/gce.jsonnet), and it provides quite a few extra features for generating Terraform JSON as well as reacher tooling for inlining file like show below.

```
metadata_startup_script: std.escapeStringDollars(importstr "configure-vm.sh"),
```

**Comment by errordeveloper** [comment]
Please note, that with Jsonnet you would still make some use of Terraform interpolation, but only in case where you have enforce dependencies. I think this is something worse documenting a bit more. Unlike some other kind of methods one could find for generating Terraform code, Jsonnet still keeps it declarative.

**Comment by flypenguin** [comment]
I'd also go for @apparentlymart's suggestion to use the consul templating languate. Make Hashi products consistent, and while it might not be the most intuitive one, it's "part of the family", already out there and being used.
