### ISSUE TITLE
Formatter adding too much space

### ISSUE THREAD

**Issue by aman-wolde-ck** [hashicorp/terraform#18458]
### Sample code
```hcl
terraform {
  required_version = ">= 0.10.4"
  backend "gcs" {}
}
```

### Expected behavior
Formatter should not change the code.

### Actual behavior
Here's the code after running terraform fmt
```
terraform {
  required_version = ">= 0.10.4"
  backend          "gcs"            {}
}
```

**Comment by apparentlymart** [comment]
Hi @aman-wolde-ck! Sorry for this weird behavior, and thanks for reporting it.

The formatter will be overhauled in [the next major release](https://www.hashicorp.com/blog/terraform-0-1-2-preview) in order to introduce support for the new configuration language features, so probably here we will hold on working on this until we're further along with the development for that release and then check this before release to ensure that it's behaving better. I've labelled this so that it'll be included in our pass of testing and review in preparation for the release.

In the mean time, we usually recommend leaving a blank space between a block's attributes and each of the nested blocks within it anyway, to help the eye follow the visual hierarchy, and I believe if you do that here (a blank line before the `backend` block) the formatter will then not attempt to erroneously align the block label with the attribute above it. This is just a workaround until we get the formatter fixed.

**Comment by aman-wolde-ck** [comment]
@apparentlymart Thanks for the getting back so quickly. Indeed leaving a line will fix the issue for now.
```
terraform {
  required_version = ">= 0.10.4"

  backend "gcs" {}
}
```

**Comment by apparentlymart** [comment]
Hi again, @aman-wolde-ck!

The changes I mentioned before are now merged into master in preparation for the forthcoming v0.12.0 release. I tried your example with the v0.12.0-alpha2 prerelease build and found that, as expected, it does not make any changes.

Since this fix is now in master, I'm going to close this out. Thanks again for reporting this, and for your patience while we got this fix merged.
