### ISSUE TITLE
feature request: ability to selectively reverse dependency graph

### ISSUE THREAD

**Issue by SamWhited** [hashicorp/terraform#18463]
Current version:

    $ terraform -v
    Terraform v0.11.7

Consider the following example in which we have a database, a web server, and a snapshot of the database:

```hcl
resource "triton_machine" "db" {…}

resource "triton_machine" "web" {…}

resource "triton_snapshot" "last_deploy" {
  name       = "last-deploy"
  machine_id = "${triton_machine.db.id}"

  depends_on = [
    "triton_machine.web",
  ]
}
```

The snapshot will be taken after each change to the "web" machine. However, it may be desirable to have the snapshot taken before we redeploy the web machine, so that if our changes have broken something we can roll our data back to the snapshot relase we took just before we rolled out a new version of our web infrastructure.

It would be nice if there were some way to reverse the creation order of these resources, despite the dependency order, so that the snapshot was created first before the changes to the web machine was applied.

**Comment by jbardin** [comment]
Hi @SamWhited,

Thanks for the filing the issue, though I'm not exactly sure I understand what it is you want to accomplish here.

The first problem I see is your description of what this configuration does. You say `The snapshot will be taken after each change to the "web" machine` -- which doesn't appear correct. The `depends_on` block effects ordering, but does not automatically trigger changes, so changing only `triton_machine.web` should do nothing to the snapshot resource. 

As for selectively reversing the dependency graph, that's not something that can be implemented in a general sense, since reversing 2 nodes in the graph will usually cause a cycle preventing the graph from resolving the dependencies. This can be achieved more coarsely with `create_before_destroy` which has to reverse the entire dependency subgraph. 

I don't think what you describe can be done with the `triton_snapshot` resource as it is right now, since there doesn't seem to be a way to "trigger" updating the snapshot without changing a `machine_id` to snapshot. Perhaps I'm missing something in how that resource is implemented, but I think it would need a field that can be updated in order to create a new snapshot.

**Comment by SamWhited** [comment]
> The first problem I see is your description of what this configuration does. You say The snapshot will be taken after each change to the "web" machine -- which doesn't appear correct. The depends_on block effects ordering, but does not automatically trigger changes, so changing only triton_machine.web should do nothing to the snapshot resource.

Yes sorry, this part didn't make sense. It's not really relavant though, I probably should have left it out.

> Thanks for the filing the issue, though I'm not exactly sure I understand what it is you want to accomplish here.

I'll try to be more clear this time, apologies. If I have a resource A which depends on resource B and B is modified, A will also be modified. What I want to do is control the order of those changes so that if B already exists and is modified in place, A is modified first, and then B is modifeid.

**Comment by SamWhited** [comment]
> I think the underlying issue here is that triton_snapshot doesn't do what you need, nor does it seem especially useful if it can't be updated. The type of behavior you want is usually implemented within the provider for specific resources, and the triton provider would need to add this functionality.

Are there other providers that offer this functionality somehow? As far as my very limited understanding of the providers API goes (I've only implemented one, so I'd love to be wrong here) this isn't something you can do at all in the provider and would require changes to terraform. Otherwise I'll just go submit a PR against the provider or maintain my own. Do you have examples of other providers that can create one resource before another? If so, this issue is most certainly invalid and the configuration construct you mentioned at the end of your reply might be unnecessary, or am I misunderstanding you?

**Comment by jbardin** [comment]
Sorry, I wasn't clear. Re-ordering of the overall resource operations is not possible with a provider. The behavior I was referring to was the general idea of a "snapshot before delete" which I think AWS implements on a resource or two, but if we're going by the original example here then the snapshot is happening against a different machine so it wouldn't be useful. 

It's hard to say what alternatives might be with examples out of context. Making some assumptions, something like the following would provide what you describe more directly:

```
resource "triton_machine" "db" {
}

resource "triton_machine" "web" {
  image = "${var.web_image}"
  depends_on = [
    "triton_snapshot.last_deploy"
  ]
}

resource "triton_snapshot" "last_deploy" {
  name       = "last-deploy-${var.web_image}"
  machine_id = "${triton_machine.db.id}"
}
```

This would create a new snapshot whenever the image for `triton_machine.web` machine was changed, and that snapshot would be applied before `triton_machine.web`.

**Comment by apparentlymart** [comment]
Embedded in this proposed solution I see the following use-case:

> Before destroying a particular `triton_machine`, I want to create a snapshot of that machine so I can roll back to that snapshot if the new machine does not function correctly.

The first part of this (creating the snapshot) could be achieved by adding a new flag to `triton_machine`:

```hcl
resource "triton_machine" "web" {
  # ...

  snapshot_before_destroy = true
}
```

The implementation of `triton_machine` could then check for this flag when asked to destroy the resource and create a snapshot itself if requested.

The rest of this requirement is trickier.

Firstly, I don't see any way in `triton_machine` right now to create a machine _from_ a snapshot, and even if there were the "normal" state of the configuration would presumably not set it and so this "roll back" would involve changing the configuration to add a new snapshot argument, applying it, and then removing the snapshot argument again, which would probably cause the machine to be replaced.

Secondly, Terraform wouldn't natively be tracking the id of that created snapshot and so it wouldn't be able to later destroy it unless the `triton_machine` resource itself kept track of the instance id. But that sort of tracking wouldn't survive the machine being replaced (since the record of the snapshot would be destroyed along with the old version of the machine).

---

The more common pattern for this sort of scenario has been instead to have some process outside of Terraform generate an image and then change that image id each time you want to push a new version. Since a process outside of Terraform is managing the building of those images, it's up to that process when they get deleted, and so your upgrade process can potentially leave one or more historical images intact.

You can then roll back to the original image, rather than the snapshot. This is of course not exactly equivalent, since it won't have any of the modifications to the machine that were made since it booted, but organizations using Terraform directly for deployment are usually employing immutable architecture principles, and so rolling back to the previous image is "good enough".

Terraform is an infrastructure provisioning tool rather than an application deployment tool, and so if you're not using immutable infrastructure then it's likely that Terraform is not the right tool for the job here. You may be better off writing a small program against Triton's own API that can handle your deployment lifecycle (in addition to taking the snapshot during deploy, I expect you'd also want to manage cleaning up historical snapshots, have a special mode for "rolling back", and keep an audit log of what was deployed when) and use Terraform for just managing the surrounding infrastructure, such as the networking fabric.

**Comment by SamWhited** [comment]
> This would create a new snapshot whenever the image for triton_machine.web machine was changed, and that snapshot would be applied before triton_machine.web.

Thanks for the help. I don't understand how this would work, as that appears to me as if it would create the snapshot after the web machine had been updated. There's either some fundamental misunderstanding of what's happening with my setup on my end, or I'm not communicating my intent very clearly. Either way this issue can be closed and I'll experiment with it. Thanks again for your patience.

> Before destroying a particular triton_machine

Not exactly; before "changing" would be more appropriate. Destroying a machine (in Triton land at least) would also destroy all snapshots if I'm not mistaken. But the general idea is sound, it seems like I need to do some work on this particular provider instead of filing an issue against Terraform itself.

> Firstly, I don't see any way in triton_machine right now to create a machine from a snapshot

It wouldn't need to (yet). At least as far as the example I gave went, I don't think that's important since it's meant to be a last resort: if you broke your database (or whatever the case may be) an ops person can log into the web UI and and hit the revert button to roll back the machine.

> The more common pattern for this sort of scenario has been instead to have some process outside of Terraform generate an image and then change that image id each time you want to push a new version.

> Terraform is an infrastructure provisioning tool rather than an application deployment tool, and so if you're not using immutable infrastructure then it's likely that Terraform is not the right tool for the job here.

I am using immutable infrastructure for the most part, but there is important data on some of these machines never the less. It gets backed up out of band, but having a machine snapshot at a given point in time is a much quicker way to do data recovery if the given machine still exists and can still be rolled back. Writing a custom tool is not an option.

Thanks again for the help all! Seems like this isn't an issue with Terraform so I'll close this now.
