### ISSUE TITLE
Docs: UI input for maps and lists

### ISSUE THREAD

**Issue by endofcake** [hashicorp/terraform#18464]
Hi,

This snippet from the [variables tutorial](https://www.terraform.io/intro/getting-started/variables.html) got my attention:

```
Note: UI Input is only supported for string variables. List and map variables must be populated via one of the other mechanisms.
```

I've run some tests, and it appears like this is no longer the case, as I was able to assign values to both a list and a map and then use these values during `apply`. I'm guessing this was changed some time ago, but the docs weren't updated.

I can open a PR with a quick fix if someone could confirm that this has changed.

Cheers.

### Terraform Version
0.11.7

**Comment by apparentlymart** [comment]
Hi @endofcake! Thanks for pointing this out.

We've recently reworked the handling of interactively-set variable values in the development branch for the next release, so it may be best for us to wait until that branch is merged into master and confirm what the behavior is then, before updating the documentation to match. From my memory of working on that code it didn't seem like we were _intentionally_ prompting for list and map variables, but perhaps it began working at some point as a side-effect  of another change.

Once we're further along with development we'll revisit this and confirm the new behavior and make sure it's acceptable. I'm going to label this issue so that we'll find it again during the testing phase.
