### ISSUE TITLE
Docs: broken link in Terraform Enterprise docs

### ISSUE THREAD

**Issue by endofcake** [hashicorp/terraform#18478]
Hi,

The [page detailing recommended practices](https://www.terraform.io/docs/enterprise/guides/recommended-practices/part3.2.html) contains a link which a) leads to an insecure site and b) results in 404 even if you click through all the warnings.

Text snippet in question:

```
If you already have established VCS workflows, layouts, and access control practices, great! If not, this is a good time to make these decisions. (We consider this advice to be a good starting point.)
```

The link: https://www.drupalwatchdog.com/volume-4/issue-2/version-control-workflow-strategies

It may make sense to replace this link with something else, maybe [this post](https://www.hashicorp.com/blog/version-controlled-infrastructure-with-github-and-terraform) from the Hashicorp blog, or [this chapter](https://www.git-scm.com/book/gr/v2/Distributed-Git-Distributed-Workflows) from the Git book.

I couldn't find where these docs are mastered.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
