### ISSUE TITLE
Terraform plan should show changes (diff) to outputs

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#18472]
This is a feature request. When using `terraform plan`, changes to outputs are not shown. If you add an output, and misspell it, `tf plan` does not give you the opportunity to review it. If you use TF for all config distributed through remote state, you'll never see a diff of the outputs you manage in the env.

It would be really great if `terraform plan` included in its diff, any changes to outputs (just like resources, so any new outputs, removals, or edits/changes).

I apologize if there is an existing ticket on this, I looked but did not find one.

**Comment by apparentlymart** [comment]
I'm also not sure if there is an existing issue for this, but we are planning to do this at the same time as what I described in #15180 so we'll use this issue to track that part. Thanks!

**Comment by zanthorn** [comment]
I would love to see changes to outputs during plans as well!

**Comment by galartsi** [comment]
Any updates about it?
If i run 'tf plan' I get the green 'No changes' but it does create an output file.

**Comment by apparentlymart** [comment]
The first time I looked at this I apparently forgot that this use-case is already part of #15419, which is about not only _showing_ the changes to outputs, but also considering those to be changes that need to be approved and applied even if nothing else has changed.

So far there hasn't been any work on that beyond the UI mock I shared where we were exploring some general ideas about making state-only changes first-class in the plan. Terraform v0.12.0 has laid some groundwork for this by making room in the in-memory plan model and plan file format for storing before and after values for the outputs, but there is still work remaining to change how Terraform's core graph engine deals with outputs so that the changes can be properly represented as such: today, Terraform just updates the output values in-place on each walk, rather than following the same plan/apply distinction used for resources.

We'll look into that more at a later date, though we don't yet know when that will be. If you're interested in the feature, please add a :+1: reaction to the leading comment on the other issue, since we use those reactions as one of the inputs to prioritization. I'm going to close this issue now just to consolidate the discussion over in the other issue.
