### ISSUE TITLE
I am trying to schedule automation with Azure SQL and running into issues with the interval.  I understand this was fixed in June with Release 1.7......but I can't seem to find the download.  Can you please assist?

### ISSUE THREAD

**Issue by dmtanner16** [hashicorp/terraform#18505]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by apparentlymart** [comment]
Hi @dmtanner16!

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with some simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help; the GitHub issues here are generally monitored only by our few core maintainers, who are not Azure experts.

If you've found a bug or limitation with the Azure provider, feel free to open an issue in [the provider's own GitHub repository](https://github.com/terraform-providers/terraform-provider-azurerm).

Thanks!
