### ISSUE TITLE
Split docs for Data Sources / Resources

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/terraform#18530]
Please split the documentation for data sources and providers, as it is cumbersome (particularly for AWS) to Ctrl-F through to find the correct object. Many of the core objects appear as both a data source and provider.

**Comment by apparentlymart** [comment]
Hi @jhmartin!

Each provider's repository is responsible for its own website content, so this isn't something we can fix in _this_ repository even though I do agree with you that the AWS provider navigation in particular has become very unwieldy.

I'm going to have our bot move this over to the AWS provider because that seems to be the one that's hurting the most and so if any temporary re-org is possible then that'll be the extreme case with which to spearhead it, and then we can see about making similar changes in the other providers too.

In the long run the per-provider documentation is likely to switch to a new structure that is generated, at least in part, from the provider source code. At that point a more "global" solution is likely to be possible, but that's a longer effort that's only just getting started now and so there may be a stopgap solution possible in the mean time.
