### ISSUE TITLE
Nullable arguments link from TF 0.12 preview blog post points to the previous Conditional improvements post

### ISSUE THREAD

**Issue by dvishniakov** [hashicorp/terraform#18558]
Blog link: https://www.hashicorp.com/blog/terraform-0-1-2-preview
Compare
```
<a href="https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements">Conditional improvements.</a>
```
```
<a href="https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements">Nullable arguments.</a>
```
Unfortunately, manually crafted link also doesn't work: https://www.hashicorp.com/blog/terraform-0-12-nullable-arguments

**Comment by apparentlymart** [comment]
Thanks for pointing this out, @dvishniakov!

This is actually intentional: the two topics were combined into a single article during editing, though it's confusing because the final form of the article says "Conditionally-omitted Arguments" instead of "Nullable arguments" and so it's not clear that these two are the same topic.

Next week I'll pass this on to the team that maintains the HashiCorp Blog to see if we can get the main summary post updated so that the relationships between the items there and the articles are more obvious.

Thanks again for reporting this!

**Comment by apparentlymart** [comment]
Hi again, @dvishniakov! Along with the publishing of [the latest installment](https://www.hashicorp.com/blog/terraform-0-12-rich-value-types) today, the original article was updated to combine those two items into a single bullet point, just as the articles themselves were combined together during editing.

Thanks again for pointing this out!
