### ISSUE TITLE
Terraform 0.11.7 does not pickup changes in sub-modules

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/terraform#18592]
### Terraform Version
```
Terraform v0.11.7
+ provider.alicloud v1.9.5
+ provider.ansible v0.0.4
+ provider.cloudflare v1.0.0
+ provider.digitalocean v0.1.3
+ provider.google v1.13.0
```

### Terraform Configuration Files
My setup uses sub modules:
`main.tf` references `modules/multi-provider` which references `modules/google-cloud` module.
Inside of the `modules/google-cloud/mian.tf` I have a firewall setup:
```hcl
locals {
  open_ports = ["22", "655", "8000", "8301", "${var.open_ports}"]
}

resource "google_compute_firewall" "host" {
  name    = "test"
  network = "default"
  allow {
    protocol = "tcp"
    ports    = ["${local.open_ports}"]
  }
}
```

### Expected Behavior
The thing is no matter what I change(even make syntax breaking changes) `terraform apply` does not notice anything being changed.
If I make changes inside of `modules/multi-platform` I can see them affecting the plan, but not if I change anything in `modules/google-cloud`.
Also if I try to run `terraform apply` inside of `modules/multi-provider` it does notice changes made inside of `modules/google-cloud`.

### Actual Behavior
File changes should have been detected.

**Comment by jakubgs** [comment]
Oh interesting. I completely removed `.terraform`, did `terraform init`, and then `terraform apply` picked up changes in `modules/google-cloud`. Wat?

**Comment by apparentlymart** [comment]
Hi @jakubgs! Sorry for this confusing behavior.

Assuming you're using a local path to reference this module, the expected behavior in 0.11 is for Terraform to create a symlink for it in `.terraform/modules`, assuming you're on a Unix system (which I assume because you used forward-slashes in your paths here).

Could you try `ls -lah .terraform/modules` and share the output here? Feel free to redact anything you consider to be sensitive; the main thing I'm looking to see is what in there is a symlink and what isn't. Since I don't your file system layout in detail, it'd be helpful if you _do_ see symlinks in there to note how they relate to the different modules you referenced in your initial description here, just for context.

Assuming they _are_ symlinks then changing the original files should work, because Terraform would follow the symlink and find the files you changed. If for some reason they _aren't_ symlinks then that would explain the behavior you're seeing, because Terraform would have copied the files instead of linking and thus you would be editing the original files and not the copies Terraform is looking at.

It'd also be helpful to see exactly which values you are passing to the `source` argument inside each of the modules you mentioned, in case the value there is causing Terraform some sort of confusion.

---

(Note for anyone who finds this comment in future, after the 0.12 release: 0.12 will switch away from this symlink technique and will instead just refer directly to the original directory on disk, and so what I said above doesn't apply there. If you encounter similar symptoms on a 0.12 or later release once available, please open an new issue as the cause is likely to be different.)

**Comment by jakubgs** [comment]
Okay, I see what happened now. That was my own fault. I was switching from working on my desktop to workin on my laptop and I `rsync`ed my `~/work` directory between hosts. But that clearly messed with the symlinks, copying them as files:
```
 infra-misc% ls -la .terraform/modules                                                                                       [08/02/18 14:52:31]
total 48
drwxr-xr-x 11 sochan sochan 4096 Aug  2 08:01 .
drwxr-xr-x  4 sochan sochan 4096 Jul 24 11:38 ..
drwxr-xr-x  2 sochan sochan 4096 Jul 24 11:37 079674e26dbea9b88b35ee0bcfcb41ad
drwxr-xr-x  3 sochan sochan 4096 Jul 24 11:37 252f556bff766e4b4fb98d8b399f3692
drwxr-xr-x  2 sochan sochan 4096 Jul 24 11:38 3c2bab02fe78d7f83bbcd4e0002f8e2d
...
```
Which caused them not to be updated. I guess I must have forgotten `-l` option to preserve symlinks.
Although it's interesting that re-running `terraform init` did not detect that those became regular directories instead of symlinks. I had to remove `.terraform` in order for them to be re-created.

I'm gonna close this as this is solved. Thanks for the explanation. Now I know how terraform keeps track of modules and where to check.
