### ISSUE TITLE
 Error parsing terraform file At 1:1: illegal char

### ISSUE THREAD

**Issue by Horusiath** [hashicorp/terraform#18618]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
provider "aws" {
  access_key = "<access key>"
  secret_key = "<secret>"
  region = "eu-west-1"
}

resource "aws_instance" "example" {
  ami = "ami-072eb17e"
  instance_type = "t1.micro"
}
```

### Crash Output

Console output after calling `terraform init`:

```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing <windows-file-path>\example.tf: At 1:1: illegal char
```

### Expected Behavior

Initialized terraform environment.

### Actual Behavior

Console error has been thrown.

### Steps to Reproduce

1. `terraform init`

### Additional Context

This is a configuration taken from your quick-step introduction site executed on windows machine in AWS Ireland region. The same error happens directly when example terraform file is anything but empty one.

The example file was created from PowerShell with ` "" > example.tf` command. I'm suspecting that the encoding may not be recognized by terraform parser.

**Comment by mildwonkey** [comment]
Hi @Horusiath ,

I am sorry to hear you're having this issue. I'm able to run the config you supplied from my laptop (MacOSX) so I also suspect an encoding issue. Are you able to run `terraform fmt` after creating the file?

**Comment by cbryant-zspace** [comment]
Sorry, this error message is useless. It appears that any file produced via Windows powershell can't be read by terraform. It would really help if terraform displayed what the illegal character is and why it considers it invalid.

**Comment by apparentlymart** [comment]
My guess would be that this file is getting written with a [UTF-8 byte-order mark](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8), which the HCL parser doesn't support. Since it's a non-printable character, it won't generally be visible if you inspect this file in a text editor, but you may be able to see it in a hex viewer as the following sequence of bytes at the start of the file: `0xEF,0xBB,0xBF`

I found [a StackOverflow question](https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom) that seems to confirm that PowerShell will write out files with byte-order marks by default, and gives some suggestions on ways to avoid it.

To make this more ergonomic in future we might just change the HCL parser to check for a leading byte-order mark and strip it out, since it does seem like lots of tools in Windows insert it even though this goes against the recommendations in the relevant standards. Since we're in the middle of shifting to a new implementation of the HCL parser for Terraform 0.12 we won't be able to embark on this immediately, but I expect it won't be hard to deal with it in a later release once we get past the current set of work, since it should be a backward-compatible change.

This poor error message is also an artifact of the current version of HCL, and will be improved in the next version. We'll need to check what exactly it does in this case, since as mentioned the BOM is a non-printable character and thus probably won't render directly in an error message string; we may have to adjust the error message to show the hex values of the bytes in situations where an invalid token contains unprintable unicode characters.

I'm going to assume for the moment that a BOM is the problem here and tag this issue accordingly, but please let me know if either of you are able to look at your files in a hex editor and determine that there is _not_ a BOM present, and thus some other problem is indicated.

**Comment by i255d** [comment]
C:\tf\tf-windows> terraform plan -out='.\output.tf'
Error: Error parsing C:\tf\tf-windows\output.tf: At 1:7: illegal char
This keeps happening, I am using PowerShell 5 on a Windows 10 Workstation.   I have Azure CLI 2 loaded on this computer also.

**Comment by kecklerr** [comment]
I am using latest fedora linux with bash  and get errors on all plans I create.  If I was to do another terraform plan or show I get the error plan.tf illegal char

**Comment by kecklerr** [comment]
So the issue is naming the out file for the plan with a .tf .
name the file with something else like .data or .out

**Comment by i255d** [comment]
> So the issue is naming the out file for the plan with a .tf .
> name the file with something else like .data or .out

Perfect!  
Thanks for the insight.  I will make the adjustment.

**Comment by apparentlymart** [comment]
In the forthcoming v0.12.0 release, Terraform will accept files that begin with a UTF-8 byte order mark but otherwise ignore that mark.

**Comment by Jyoti492** [comment]
Did anyone fine the solution for it ? I am also facing same issue with terraform version 0.11.11 and not even able to update to 0.12.0 if that has resolve the issue. @apparentlymart @Horusiath

**Comment by kecklerr** [comment]
Only name files with.tf if it is a terraform script. All outputs and doc
files must be some other name other than ending with .tf.

**Comment by JustinGrote** [comment]
@apparentlymart, having the same problem after 0.12, it doesn't recognize the BOM that Powershell Inputs by default.

```powershell
@"
credentials "app.terraform.io" {
  token = "mycred.atlasv1.morestuff"
}
"@ | out-file -encoding utf8 $ENV:APPDATA\terraform.rc
```

Here is the effective workaround to write without the BOM in Powershell, this works fine.
```powershell
$myRCFile = @"
credentials "app.terraform.io" {
  token = "mycred.atlasv1.morestuff"
}
"@

[IO.File]::WriteAllLines("$ENV:APPDATA\terraform.rc",$test,[Text.UTF8Encoding]::New($false))
```

> ~> terraform -v
> Terraform v0.12.0

**Comment by apparentlymart** [comment]
The CLI config files are still loaded with the old HCL implementation in 0.12.0, so that failure is expected, though indeed unfortunate. Please open a new issue for that (since it is about CLI Config files rather than `.tf` files and we'll see about switching these other files over to be loaded with new HCL in a later release.
