### ISSUE TITLE
Do not create or delete existing Resources in Azure

### ISSUE THREAD

**Issue by torstenstern** [hashicorp/terraform#18627]
Hi there,

i have at the moment the situation that i already deployed a complete environment.
No i have a second script where i want to add addiotnal resources in the environment but i will use existing resources and i defined them in my acctual script to use them.

No i have the issue that Terraform tried to delete the existing resource and or create them from scratch. This will fail because it is in use.

Is there anyway to avoid deletion or creation of existing resources?

Thanks for your help

Torsten

**Comment by mildwonkey** [comment]
Hi @torstenstern,

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

Having said that, I think you might want to look into the [terraform import command](https://www.terraform.io/docs/import/). This allows you to import resources into your terraform state - so terraform knows not to create things that already exist.

**Comment by tombuildsstuff** [comment]
hi @torstenstern 

(I've re-opened this on this repository since there's already comments here)

As @mildwonkey has mentioned you can use the [`terraform import`](
https://www.terraform.io/docs/import`) command to import existing resources into the state - or you can reference them using Data Sources ([which are documented in the sidebar here](https://www.terraform.io/docs/providers/azurerm/index.html)), for example to reference an existing resource group:

```
data "azurerm_resource_group" "test" {
  name = "test"
}

output "example" {
  value = "${data.azurerm_resource_group.test.name}"
}
```

Would you be able to take a look and see if either of those approaches works for you? Given this is a question rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!
