### ISSUE TITLE
Autocomplete asking for v0.10.7 

### ISSUE THREAD

**Issue by spanktar** [hashicorp/terraform#18649]
### Terraform Version
0.11.7

I just fired up a whole new machine and installed terraform from Homebrew using the excellent `chtf` tool (it just uses brew, too).  What I noticed shortly thereafter was the automcomplete was going a little bonkers. Every time I would try to tab complete anything (even a filesystem path) it would give me the following error. In this example I typed `terraform <tab>`:

```terraform compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
```

and then hang. First I was like "oh yeah, I need to install the autocomplete tools", so I did. Same problem. So then I looked at the error message and say that it inexplicably wants terraform version _0.10.7_ (I'm running 0.11.7).  So I installed that version using `chtf 0.10.7` and the problem went away and autocomplete works fine.

Any reason for this version to be required/pinned? Like I said, brand new system so I haven't really done anything funky yet, this was straight "out of the box" as it were.

### Expected Behavior
Tab completion should work in v0.11.7 without having to have v0.10.7 installed.

### Actual Behavior
Without v0.10.7 installed you get the following error:
```compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform```

### Steps to Reproduce
1. Install Homebrew on OSX 10.13.6 (17G65) 

2. Install [chtf](https://github.com/Yleisradio/homebrew-terraforms):
```brew tap Yleisradio/terraforms
brew install chtf
```

3. source it:
`source "/usr/local/share/chtf/chtf.sh"`

4. Install Terraform:
`chtf 0.11.7`

Try autocomplete.

**Comment by apparentlymart** [comment]
Hi @spanktar,

I sense a strange interaction between the various systems you have in play here.

Terraform itself has [some commands for configuring completion](https://www.terraform.io/docs/commands/index.html#shell-tab-completion), and running `terraform -install-autocomplete` will register with your shell the absolute path of that `terraform` binary as the completion program.

I expect that _something_ ran `terraform -install-autocomplete` while you had `v0.10.7` selected, causing that path to be configured in your shell. That'll stick until the registration is undone using, e.g.:

```
/usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform -uninstall-autocomplete
```

Since it also uses the absolute path to _deregister_, I think it won't work to uninstall using a different version.

Once it's deregistered you could optionally re-register with a different version of `terraform`, though indeed if you are regularly switching between releases it's probably best to just not enable completion at all since completion is a global thing.

A possible workaround -- which I haven't tested, since I'm not on a Mac -- would be to temporarily place a Terraform binary at the location where Homebrew places its symlink (`/usr/local/bin/terraform`, I think?), run `terraform -install-autocomplete` from _there_, and then let homebrew put the symlink back. Then I believe your shell will use the symlink to run the autocomplete helper, and so it should always select the version of Terraform you're currently using.

**Comment by spanktar** [comment]
I agree, but I never had 0.10.7 installed which is the weird part. My first install of TF was 0.11.7. Trying your suggestion now...

Here's what I've got:

```
➜  /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform -uninstall-autocomplete
➜  cd /usr/local/Caskroom
➜  Caskroom lsd
total 0
drwxrwxr-x   5 spanky  admin   160B Aug  9 12:32 ./
drwxr-xr-x  15 root    wheel   480B Aug  1 10:04 ../
drwxr-xr-x   4 spanky  admin   128B Aug  1 10:04 font-source-code-pro/
drwxr-xr-x   4 spanky  admin   128B Aug  9 12:32 terraform-0.10.7/
drwxr-xr-x   4 spanky  admin   128B Aug  8 10:48 terraform-0.11.7/

➜  Caskroom mv terraform-0.10.7 ~/Desktop

➜  Caskroom terraform compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform

➜  Caskroom which terraform
/usr/local/Caskroom/terraform-0.11.7/0.11.7/terraform
➜  Caskroom /usr/local/Caskroom/terraform-0.11.7/0.11.7/terraform -install-autocomplete
Error executing CLI: 2 error(s) occurred:

* already installed in /Users/spanky/.bash_profile
* already installed in /Users/spanky/.zshrc
➜  Caskroom terraform compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform
compgen:96: no such file or directory: /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform

➜  Caskroom lsd ~/.terraform.d
total 16
drwxr-xr-x   4 spanky  staff   128B Aug 10 11:34 ./
drwxr-xr-x@ 31 spanky  staff   992B Aug 10 12:04 ../
-rw-r--r--   1 spanky  staff   315B Aug 10 11:34 checkpoint_cache
-rw-r--r--   1 spanky  staff   394B Aug  8 10:53 checkpoint_signature

➜  Caskroom less ~/.terraform.d/checkpoint_cache
5wi<FB>^F^@^@^@0.11.7{"product":"terraform","current_version":"0.11.7","current_release":1523381188,"current_download_url":"https://releases.hashicorp.com/terraform/0.11.7/","current_changelog_url":"https://github.com/hashicorp/terraform/blob/v0.11.7/CHANGELOG.md","project_website":"https://www.terraform.io","alerts":[]}

➜  Caskroom brew link terraform
Error: No such keg: /usr/local/Cellar/terraform

➜  Caskroom brew install terraform

➜  Caskroom  brew link terraform
Warning: Already linked: /usr/local/Cellar/terraform/0.11.7
To relink: brew unlink terraform && brew link terraform

➜  Caskroom brew unlink terraform && brew link terraform
Unlinking /usr/local/Cellar/terraform/0.11.7... 1 symlinks removed
Linking /usr/local/Cellar/terraform/0.11.7... 1 symlinks created
```

You know what? Ignore all that (leaving for posterity).

I copied my .zshrc custom.zsh file from an old machine.  Guess what was hiding in it?

`complete -C /usr/local/Caskroom/terraform-0.10.7/0.10.7/terraform terraform`

Sorry for the noise...

**Comment by apparentlymart** [comment]
No worries! I'm glad we got to the bottom of it. :smile:
