### ISSUE TITLE
Output multiple list map

### ISSUE THREAD

**Issue by wang415** [hashicorp/terraform#18659]
### Terraform Version

```
terraform v0.11.7
```

### Terraform Configuration Files

```hcl
output "vm_information" {
  value = "${join(",",vsphere_virtual_machine.example_virtual_machines.*.name,vsphere_virtual_machine.example_virtual_machines.*.guest_ip_addresses.0)}"

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

vm_information = wade0,wade1,192.168.139.120,192.168.139.121
}


```
### I want to implement the ouput output as follows, how to write the syntax.

```hcl
Outputs:

wade0  = 192.168.139.120
wade1  = 192.168.139.121
```

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

Having said that, I suggest you look into the [`formatlist()` function](https://www.terraform.io/docs/configuration/interpolation.html#format-format-args-), which can be used to craft outputs. 

I think what you're looking for is something like this (not guaranteed to be 100% correct syntax!):

```hcl
output "vm_information" {
  value = "${formatlist(
    "%s = %s", 
    vsphere_virtual_machine.example_virtual_machines.*.name,
    vsphere_virtual_machine.example_virtual_machines.*.guest_ip_addresses.0
  )}"
}
```

**Comment by wang415** [comment]
@mildwonkey  Thank you for your reminder. I will ask questions from the community later. At the same time, according to your instructions I made changes to meet my needs. Thank you.

I will close question
```hcl
output "vm_information" {
  value = "${formatlist(
    "%s = %s", 
    (vsphere_virtual_machine.linux_vm.*.name),
    (vsphere_virtual_machine.linux_vm.*.guest_ip_addresses.0)
  )}"
}
```
