### ISSUE TITLE
Getting the Error "The required information to complete authentication was not provided"

### ISSUE THREAD

**Issue by geeshans** [hashicorp/terraform#18673]
### Terraform Version

```
terraform -v
Terraform v0.11.7
+ provider.oci v2.1.3

```

### Terraform Configuration Files

```
# Gets a list of Availability Domains

data "oci_identity_availability_domains" "ADs" {
  compartment_id = "${var.tenancy_ocid}"
}

```

### Debug Output

https://gist.github.com/geeshans/c5231c1f6b6f98d99c3046652ab71583

### Expected Behavior

Terraform to apply successfully
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
### Additional Context

I have already double checked the 
  tenancy_ocid 
  user_ocid 
  fingerprint 
  private_key_path
  region

**Comment by apparentlymart** [comment]
Hi @geeshans! I'm sorry this isn't working as expected.

This seems to be a problem specific to the OCI provider, which the Terraform Core team is not familiar with. I'd recommend opening an issue in [the OCI provider's own repository](https://github.com/oracle/terraform-provider-oci), where hopefully the maintainers can be of more help due to their knowledge of OCI.

Thanks for reporting the issue and sorry the Core team can't help with it.
