### ISSUE TITLE
Make instance name available within module

### ISSUE THREAD

**Issue by dleske** [hashicorp/terraform#18694]
### Current Terraform Version

```
Terraform v0.11.7
```
(But I don't see anything about this in the Terraform 0.11.8 release notes.)

### Use-cases

I am using a module to create a resource.  I call this module several times to create similar resources for different purposes, using different instance names.  It would be helpful if I could use the module instance name from within the module to name the resource:

Calling the module:
```
module "thing1" {
   source = "my-module"
   param1 = "value the first"
   param2 = "value the second"
}
```

Within the module:
```
resource "resource_type" "doesntmatter" {
   name = "${self.name}"
   ...
}
```

I would like the resource to be named `thing1`.  I could use a module parameter to pass in the desired name, but the end resource only needs a unique descriptive name, not a pretty one, so the instance name would be ideal (and wouldn't violate DRY).

### Attempted Solutions

* Looked for undocumented variables with a bit of trial-and-error and use of `TF_LOG=DEBUG` and searching for the instance name

### Proposal

I would propose to create a context for `self` that could be used in modules (currently, according to the documentation, `self` only applies to provisioners) and provide a `name` attribute.

### References

I found no related issues.

Asked on
* [Gitter](https://gitter.im/hashicorp-terraform/Lobby?at=5b75a5dc637ee66082fc5855)
* [Server Fault](https://serverfault.com/questions/926738/terraform-use-module-instances-name-inside-module)

**Comment by apparentlymart** [comment]
Hi @dleske! Thanks for sharing this use-case.

We've seen similar requests to this before and have shied away from it because it would create a new form of potentially-surprising coupling between modules. Module names are required to be unique only within their calling module and not globally, but doing something like what you described here would create the surprising situation that suddenly the module name is _actually_ required to be globally unique across all calls in any configuration that talks to the same remote account.

By passing a name in as a variable explicitly, you can document that variable as taking a value that must be unique across all instantiations of this module across all calling configurations, and thus there is less chance of surprising collisions.

A possible compromise that avoids this concern would be to allow the module name to be interpolated within its _own_ block, like this:

```hcl
# Hypothetical example; not actually implemented

module "thing1" {
  source = "my-module"

  name = "${self.name}"
}
```

This ensures that the caller is the one making the decision to use that name in a way that requires it to be globally-unique, which avoids creating that accidental extra dependency.

This seems like a situation where a little copying winds up being simpler in the end, since both mentions of that name are very close together in the source code anyway. Therefore I don't feel certain that the extra complexity of adding that special interpolation form (which I expect in practice would be called something other than `self.name`, since `self` is already established as having a different meaning in resources) is offset by the benefit it provides, but I'll let this issue soak for a little while and return to it later when we've finished the current planned round of configuration language changes for 0.12 (which is already a big enough release as it is).

Thanks again for sharing the use-case!

**Comment by mildwonkey** [comment]
Hi @dleske ,
Now that Terrafrom 0.12 has released, we've had a chance to re-visit issues such as this one. It's had no upvotes (👍) or other comments, and it seems like a lot of complexity to avoid writing a short string twice, so  I am going to close this particular request. 
I'm sorry for the unsatisfying response, and I want to thank you for opening the issue and sharing your use-case!
