### ISSUE TITLE
Module configuration block change suggestion

### ISSUE THREAD

**Issue by ryanisnan** [hashicorp/terraform#18727]
Hello,

In tracing down an issue with some of our terraform code recently, we fell into a (probably easy) trap with module definitions.

In a module, the following three attributes are important to the module:

1. source
2. version
3. providers

Our module also incorrectly accepted the `version` variable. This is definitely our fault, but in uncovering this problem, I recognized a potential improvement to module definition. I propose a dedicated `vars` block for modules that explicitly identifies which attributes are variables, and which are reserved for the module itself.

Thanks!

### Current Terraform Version

```
0.11.8
```

### Use-cases

Any users of terraform modules.

### Attempted Solutions

N/A

### Proposal

An existing module would be defined as such:

```
module "derp" {
    source = "blerp"
    version = "whyme"
    foo = "bin"
    bar = "baz"
}
```

In this example, the module attributes are all siblings, and it is easy for someone to mistake a property like `version` for something that the module might expect. To add clarity, a structure like such could be helpful:

```
module "derp" {
    source = "blerp"
    version = "whyme"
    
    vars {
        foo = "bar"
        bin = "baz"
    }
}
```

### References

N/A

**Comment by apparentlymart** [comment]
Hi @ryanisnan! Sorry for the trouble here, and thanks for the proposal.

Unfortunately it's too late now for us to make such a disruptive change to the syntax of `module` blocks, but I agree that the collisions here are unfortunate. The same tradeoff exists for special `resource` block arguments, like `count`.

What we're planning to do for Terraform 0.12 is to actually properly reserve all of the names that are treated as "special" by Terraform, so that e.g. a `variable "version"` block will be an error at declaration, rather than just failing strangely at usage.

This is definitely a _compromise_, since of course it's still a breaking change for anyone already using these names, but at least this way it affects only the subset of uses where those reserved names are in use (which presumably weren't working fully _anyway_), rather than requiring changes for everyone.

**Comment by ryanisnan** [comment]
That's a great idea. Also good food for thought on any API design. Cheers for the response.

**Comment by ryanisnan** [comment]
I wonder if a backwards-compatible workaround could be achieved by identifying a block of configuration within a module? I know nothing about the internals of Terraform, but AFAIK other than `providers`, a block would stand out as deserving special treatment?

**Comment by apparentlymart** [comment]
Hi again, @ryanisnan! Sorry for the long silence here.

The changes for v0.12 are now merged into master as we work through the prerelease phase. In v0.12.0-alpha2 we can see the new error message I was talking about:

```
Error: Invalid variable name

  on module-version-reserved.tf line 1, in variable "version":
   1: variable "version" {

The variable name "version" is reserved due to its special meaning inside
module blocks.
```

The three names you mentioned will have similar behavior. We're also planning to reserve `count`, `for_each`, `depends_on` and `lifecycle` in the same way to allow for future planned features without further breakage. The `lifecycle` block, similar to with resources, will serve as a catch-all for future additions we haven't thought of yet that aren't significant enough to justify reserving even more variable names.

Since this change is now merged, I'm going to close this out. Thanks for pointing out this issue, and for your patience while we worked through the changes required to get these better error messages in place.
