### ISSUE TITLE
aws_security_group_rule InvalidPermission.Duplicate - Should be additive

### ISSUE THREAD

**Issue by chrisferry** [hashicorp/terraform#1874]
I have a module which creates an ASG tied to an ELB
Within that module there is:

``` js
resource "aws_security_group_rule" "allow_elb_http_in" {
  type                     = "ingress"
  from_port                = "${var.elb_listen_port}"
  to_port                  = "${var.elb_listen_port}"
  protocol                 = "tcp"
  security_group_id        = "${var.security_group}"
  source_security_group_id = "${var.elb_security_group}"
}
```

I have several ASGs in the same APP-SG and several ELBs in the same ELB-SG
Some have overlapping listen ports which causes the following error when I try to apply:

```
* Error authorizing security group rules rules: InvalidPermission.Duplicate: the specified rule "peer: sg-xxxxxxxx, TCP, from port: 80, to port: 80, ALLOW" already exists
```

I think that the resource should allow for additive rules due to how the modules work

**Comment by phinze** [comment]
Thanks @chrisferry - this comes out of a chat we had in IRC.

Tagging this `thinking` since I'd like to see if there's any way for terraform to support this use case, which to me seems pretty common ( multiple disparate modules each wanting to slap rules onto a security group, some of which could overlap ).
