### ISSUE TITLE
Variable inside Variable doesnt work 

### ISSUE THREAD

**Issue by kay07949** [hashicorp/terraform#18789]
Hi All, 

This line of code below doesnt work, please help:

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.vpc-"${terraform.workspace}".id}"

.....}

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by apparentlymart** [comment]
Hi @kay07949,

It is intentional that references cannot be generated dynamically like that, since Terraform needs to know exactly what the name is early on in order to build the dependency graph.

It looks like you have a rather unusual situation where you've got a single configuration that creates multiple VPCs for different workspaces but then you only want to create _one_ internet gateway for the current workspace. The effect of this would be that each time you switch workspaces you'd get an entirely new set of VPCs (named after all of your workspaces again) and one more IGW.

`terraform.workspace` is normally used only to help with generate unique names _in the remote system_ that include the current workspace to avoid collisions when you create a new workspace. There's no need to include the workspace name in the local names used within Terraform itself, because they already have a separate namespace per workspace.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
