### ISSUE TITLE
Rename aws_instance to aws_ec2_instance

### ISSUE THREAD

**Issue by ajlanghorn** [hashicorp/terraform#1880]
Should `aws_instance` be renamed to `aws_ec2_instance` to match the naming conventions in use across other resources in the AWS provider? This will need to be backward compatible so that it doesn't break everyone's use of `aws_instance`, or if it's not, then it'll need to be introduced in a major version in future.

**Comment by phinze** [comment]
Yeah the lack of symmetry across resources has been bothering me too. It's mostly just an accident of history, but let us think instead of a bright future! :rocket: :grinning: 

The implementation actually allows us to trivially "alias" resources - there would be a bit of work in wiring in some deprecation messaging so we could remove the old ones though.

Tagged `thinking` since I want to check in with @mitchellh about his feelings on this.

**Comment by mitchellh** [comment]
I don't think this is worth it until some farther point in the future. It just doesn't affect anything and I think `aws_instance` everyone knows what you're talking about. I agree that for perfect symmetry we should rename it but I think practically its not worth the effort to deal with aliasing, since existing resources can never be renamed since we don't do state migrations so we'd have to think about that. 

It's a whole thing where the engineering effort probably isn't justified. We'll come back when we're relaxin' on the project. :)

**Comment by ajlanghorn** [comment]
@phinze @mitchellh Sure. I raised this not for an immediate fix, but just because it's been bugging me for a while - and the new resources in 1.5.0 exacerbated that. Can most definitely wait until a much quieter time!
