### ISSUE TITLE
A list of computed resources force recreation of all resources using the computed list

### ISSUE THREAD

**Issue by neerkuma** [hashicorp/terraform#18821]
### Terraform Version
Terraform v0.11.8

### Terraform Configuration Files
Step 1
resource "null_resource" "1" {}
locals {
  nullr = "${list(null_resource.1.id)}"
}
resource "null_resource" "d" {
  triggers {
    nullrsid = "${local.nullr[count.index]}"
  }
  count = 1
}

Step 2
resource "null_resource" "1" {}
resource "null_resource" "2" {}
locals {
  nullr = "${list(null_resource.1.id, null_resource.2.id)}"
}
resource "null_resource" "d" {
  triggers {
    nullrsid = "${local.nullr[count.index]}"
  }
  count = 2
}

### Debug Output
It can easly reproduce

### Expected Behavior
It should only create the null_resource.d[1]
### Actual Behavior
It forces the recreation of null_resource.d[0] in addition of creation of  null_resource.d[1]
### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply to Step 1`
3. `terraform plan Step 2`

### Additional Context
 terraform.exe plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.1: Refreshing state... (ID: 2512199771223556897)
null_resource.d[0]: Refreshing state... (ID: 8218870896985576576)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  + null_resource.2
      id:                <computed>

-/+ null_resource.d[0] (new resource required)
      id:                "8218870896985576576" => <computed> (forces new resource)
      triggers.%:        "1" => <computed> (forces new resource)
      triggers.nullrsid: "2512199771223556897" => "" (forces new resource)

  + null_resource.d[1]
      id:                <computed>
      triggers.%:        <computed>

Plan: 3 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

### References
-->

**Comment by teamterraform** [comment]
Hi @neerkuma! Sorry for this awkward behavior.

You've described a known limitation of Terraform 0.11 and prior, which is that any list containing a value that isn't known yet makes Terraform consider the entire list to be unknown, which then potentially affects other references to that list.

The good news is that this limitation is fixed as of Terraform 0.12: it can now support a list with only certain elements being unknown, and thus avoid causing churn for references to other elements in the list which _are_ known.

Since this fix is already included in several stable releases, I'm going to close this out. Sorry for the slow response!
