### ISSUE TITLE
terraform state show not "easy to parse on the command line" as advertised for some data

### ISSUE THREAD

**Issue by lvh** [hashicorp/terraform#18836]
### Current Terraform Version

```
$ terraform version                                                                                                                                        [master] 11:06:40
Terraform v0.11.7
+ provider.aws v1.11.0
+ provider.template v1.0.0
+ provider.tls v1.1.0

Your version of Terraform is out of date! The latest version
is 0.11.8. You can update by downloading from www.terraform.io/downloads.html
```

### Use-cases

I am trying to extract some data out of a state for debugging. The docs claim this format would be easy to parse from the CLI, but instead that's super complicated because the thing I'm trying to extract is a PEM and as such it has both newlines and equals signs in it.

### Attempted Solutions

Workaround: copy-paste manually.

### Proposal

- `--json` so I can use `jq` and not worry about these sorts of in-band signaling issues
- allow `terraform state show` to access attributes _of_ an address, essentially any expression you'd be able to interpolate elsewhere should work there too

JSON is more general since it means I can also use it if I don't know which keys exist yet or what values I have; for example if I have to do something else based on this being an ECDSA or an RSA key. 

### References

N/A

**Comment by apparentlymart** [comment]
Hi @lvh,

At the moment Terraform does not have much machine-readable output since we would not be able to promise compatibility for it without constraining planned future development. However, if you are willing to tolerate some churn when upgrading to new Terraform versions, you can directly parse the Terraform state JSON produced by `terraform state pull`.

This format _will_ see some significant changes in the forthcoming Terraform 0.12 release in order to properly support the new language type system. After that, changes are likely to be relatively minor but compatibility still won't be guaranteed until we feel confident that the format is "right" and will not need to change to support new features.

I agree with you that the `terraform state show` output is not ideal for machine parsing, and we do plan to support JSON output from more commands in future, once the underlying data formats stabilize enough.

**Comment by lvh** [comment]
Sure thing, that sounds reasonable :) This was just a one-off so I don't care a ton for now.

**Comment by ms4720** [comment]
just for reference if you do a loop over `terraform state list` and do a `terraform state show $item` you get a very easy to load set of hashes to use

**Comment by mildwonkey** [comment]
Thanks for submitting this feature request! 
Terraform 0.12 introduced the `-json` flag to [`terraform show`](https://www.terraform.io/docs/commands/show.html#json-output) command, used to show either a state or planfile, which was specifically designed to be parsed by third-party tools.
