### ISSUE TITLE
Terraform 0.11.8 is printing incorrect help for workspace command.

### ISSUE THREAD

**Issue by phillipsj** [hashicorp/terraform#18832]
Help for Terraform workspace is incorrect.

```
$ terraform version
Terraform v0.11.8
```

When running *terraform workspace* command the help displays.

```
$ terraform workspace
Usage: terraform workspace

  Create, list, change and delete Terraform workspaces.
```

Executing *terraform workspace create* returns the help.

```
$ terraform workspace create
Usage: terraform workspace

  Create, list, change and delete Terraform workspaces.
```

Actual command is supposed to be *terraform workspace new*.

**Comment by skinofstars** [comment]
This one is pretty frustrating. Simple fix here is to change the message to `New, list, select and delete Terraform workspaces`

**Comment by phillipsj** [comment]
I already put in a PR with that change.

**Comment by phillipsj** [comment]
@svanharmelen was there something wrong with the PR that I submitted to correct the issue? I noticed you accepted a different one.  Thanks

**Comment by svanharmelen** [comment]
No there was nothing wrong with your PR @phillipsj! And I'm very sorry I didn't see this one before I saw the other PR, because in that case I would probably have merged this one first and then the other one.

The other PR would still have been needed as PR #18833 only changed `Creates` to `new`, where PR #18990 also changed `change` to `select`. Both verbs were named incorrectly in the help message, so by merging PR #18990 both are fixed now.

But again sorry for missing your PR as we could have merged both in this case.

**Comment by phillipsj** [comment]
Thanks for the clarification.
