### ISSUE TITLE
provider/dme: 500 errors on rapid DNS record insertions

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/terraform#1883]
```
resource "dme_record" "vpn" {
  count = "${var.coach_machines}"

  domainid = "xxx"
  name = "cluster.${var.stack}.vpn"
  type = "A"
  value = "${element(aws_instance.coach.*.public_ip, count.index)}"
  ttl = 60
}
```

the above snippet causes two `500` errors from DME:

```
* Failed to create record: Error creating record: API Error: 500 Internal Server Error
```

the problem is (probably) that you can't create duplicate records in rapid sucession. If I rerun `plan` and `apply` two more times, the records get created as expected (the second run giving one more `500` error, and the last run correctly creating the last missing entry)

I already created a ticket at the DME side, so we can either wait for them to resolve this, or make this not run in parallel?

**Comment by phinze** [comment]
Thanks for the report!

A third option here would be to augment the [upstream client](https://github.com/soniah/dnsmadeeasy) to retry through 500 errors, similar to the [AWS client's strategy](https://github.com/awslabs/aws-sdk-go/blob/master/aws/service.go#L138-L155).

Over in #1834 there's work to expose `parallelism` as a configurable, but I think something like a per-provider tunable is a bit more complexity than we'd like to take on at this point.

Since I think the best fixes here are in the service itself or the client, I'm going to close this as an upstream issue. Feel free to reopen if you'd like to discuss further or you believe strongly that a fix for this belongs in Terraform.
