### ISSUE TITLE
Add multiple items in Dynamo DB

### ISSUE THREAD

**Issue by Mohitg06** [hashicorp/terraform#18846]
### Current Terraform Version

```
...
```

### Use-cases
<!---

I can create Dynamo DB table , add multiple attributes and add one item per atrbute. How can I add multiple items?
In order to properly evaluate a feature request, it is necessary to understand the use-cases for it.
I followed this: https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html

Please describe below the _end goal_ you are trying to achieve that has led you to request this feature.

**Comment by Mohitg06** [comment]
I can create Dynamo DB table , add multiple attributes and add one item per atrbute. How can I add multiple items?
In order to properly evaluate a feature request, it is necessary to understand the use-cases for it.
I followed this: https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html

**Comment by apparentlymart** [comment]
Hi @Mohitg06! This seems like more of an AWS Provider question than a question about Terraform itself, so unfortunately the maintainers of this repo aren't really equipped to help with it.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
