### ISSUE TITLE
Support variables in naming

### ISSUE THREAD

**Issue by EximChua** [hashicorp/terraform#18876]
### Current Terraform Version

```
Terraform v0.11.8
+ provider.archive v1.1.0
+ provider.aws v1.36.0
```

### Use-cases

Support variable names in Terraform names.

### Attempted Solutions

# terraform.tfvars
version_prefix = "103"
key_pair_prefix = "awskeypair"
# variables.tf
variable "version_prefix" {}
variable "key_pair_prefix" {}
# main.tf
resource "aws_key_pair" "some_name1_${var.key_pair_prefix}${var.version_prefix}xxxxx" {
}
resource "aws_key_pair" "some_name2_${var.key_pair_prefix}${var.version_prefix}yyyyy" {
}

resource "aws_...." "some_other" {
  key_name = "${aws_key_pair.some_name1_${var.key_pair_prefix}${var.version_prefix}xxxxx}" // this refers to the first keypair above
}

### Proposal

Support variables in the names of any Terraform resource, data.
This allows re-using a module by just changing the variable assignment.
eg, by changing version_prefix = "104", I can now re-use the entire main.tf without changing anything at all.

See above attempted solution.

**Comment by apparentlymart** [comment]
Hi @EximChua! Thanks for this feature request.

Terraform cannot allow dynamically-generated names and references, because it is necessary for Terraform to know all of the names of objects and references _before_ any expressions can be evaluated, in order to build the dependency graph. This is similar to how in a statically-type programming language you generally can't dynamically generate class and field names.

However, these names are _already_ namespaced by module, so dynamically setting them should not be necessary: you can just give them simple names that are unique only within the single module and then instantiate the module multiple times. Terraform will generate a fully-qualified address for each resource that incorporates any module names, like: `module.foo.aws_key_pair.xxxxx` vs. `module.bar.aws_key_pair.xxxxx`.

Since these names have no significance outside of the module in which they are defined, they should be named with a short name that contains only enough information to differentiate resources of the same type within the same module.

**Comment by EximChua** [comment]
Hi there,

I'm not sure if you're misunderstanding me, or I'm misunderstanding you.

The names are not dynamically generated. By the time Terraform evaluates it, the data in variables.tf is already fixed. What dynamic generation are you talking about?

**Comment by apparentlymart** [comment]
"Dynamic" in this context means results from evaluating expressions, as opposed to literal values. `var.version_prefix` is an expression, and so the dependency graph must be built before it can be evaluated.

Terraform's workflow is, approximately:

1. Read the configuration _shallowly_, decoding all of the top-level constructs (`resource` blocks, etc) but leaving everything else in raw expression form.
2. Analyze the top-level constructs along with references in the expressions (like `var.version_prefix`) to understand what depends on what, and thus what order the constructs must be processed in.
3. Walk through those constructs in the determined order, evaluating the rest of the expressions as we go.

During step 2, all of the references in expressions and all of the object names must be known in order to understand how they relate to one another, but we can't yet _evaluate_ the expressions because they may depend on results that aren't known yet.

In the case of variables in the root module, indeed that expression evaluation doesn't depend on anything else because you provide the constant value on the command line, as the default, or in a variables file, but Terraform only knows that because it builds the dependency graph (step 2) and finds that the variable doesn't depend on anything. This special situation doesn't generalize to variables in a child module, where the value of that variable could depend on anything else, including a resource attribute that won't be known until apply time.

**Comment by ketzacoatl** [comment]
I would recommend using modules to "namespace" resources in the way "interpolated resource names" would allow.

**Comment by teamterraform** [comment]
Hi again!

We're planning to meet some use-cases in this area by implementing the resource `for_each` feature discussed in #17179. We're working on the implementation of that right now and it will be included in a near-future release.

Using that feature, if a set of similar objects are to be systematically created based on the contents of a collection, they could be described using a single `resource` block containing the `for_each` argument, which is a special argument similar to `count` which is handled by Terraform Core itself.

It's never necessary to include dynamic values in resource names just for uniqueness between instances of a module. Each module instance has its own separate namespace of module names, and so the names within one module only need to be unique within that module, and will usually have very simple names containing only a single noun.

To see updates about the `for_each` feature, please follow #17179. We're going to close this now as part of some issue consolidation in preparation for that feature being released. Thanks!
