### ISSUE TITLE
Request to have Terraform remote state track provider versions

### ISSUE THREAD

**Issue by unacceptable** [hashicorp/terraform#18911]
### Terraform Version

```
11:20 MacOS: Terraform/ >$ terraform -v
Terraform v0.11.8
+ provider.aws v1.37.0

11:20 MacOS: Terraform/ >$
```

### Terraform Configuration Files
```hcl
terraform {
    backend "s3" {
        bucket  = "bucket.terraform.tfstate"
        key     = "Project/terraform.tfstate"
        region  = "us-west-2"
        encrypt = "true"
        profile = "work"
    }
}
```

### Crash Output
```
11:15 MacOS: Terraform/ >$ terraform plan

Error: aws_lb_listener.grafanaHTTP: "default_action.0.target_group_arn": required field is not set



Error: aws_lb_listener.grafanaHTTP: default_action.0: invalid or unknown key: redirect



Error: aws_lb_listener.grafanaHTTP: expected default_action.0.type to be one of [forward], got redirect

11:15 MacOS: Terraform/ >$ cat alb.tf 
... Blah blah blah
resource "aws_lb_listener" "grafanaHTTP" {
    load_balancer_arn = "${aws_lb.grafana.arn}"
    port          = "${lookup(var.lb,"list_port")}"
    protocol      = "${lookup(var.lb,"list_proto")}"

    default_action {
        type            = "redirect"
        redirect {
            port          = "${lookup(var.lb,"list_port2")}"
            protocol      = "${lookup(var.lb,"list_proto2")}"
            status_code   = "HTTP_301"
        }
    }
}
... Blah blah blah
11:18 MacOS: Terraform/ >$ terraform -v
Terraform v0.11.8
+ provider.aws v1.30.0

11:18 MacOS: Terraform/ >$
```

### Expected Behavior
I would expect that Terraform would track and check the provider's version in remote state and throw an error if the local provider is out of date with the provider most recently used.  Maybe something like the following:

``` diff
  {
      "version": 3,
      "terraform_version": "0.11.8",
+     "terraform_provider_versions": [
+         {
+             "provider1": "version"
+         }
+     ]
      "serial": 13,
      "lineage": "f8120afa-17e6-fab7-bead-d97cfda284d2",
      "modules": [
          {
              "path": [
                  "root"
              ],
              "outputs": {},
              "resources": {},
              "depends_on": []
          }
      ]
  }
```

### Actual Behavior
In my case, a co-worker used v1.36.0, while I was still using v1.36.0.  This caused the above error on my machine and I only figured this out after asking him to provide me the version that he was using.

### Steps to Reproduce
This is kind of hard to reproduce.  Just install the AWS provider v1.30.0 on a testing server and try to create a listener on one machine with an update to date AWS provider.  On your testing server try to do a `terraform plan` and you will see this issue.

The only way that I have found to mitigate this is to delete the .terraform folder locally and to do a `terraform init` again.

**Comment by mildwonkey** [comment]
I'm sorry you ran into this, @ScriptMyJob; that sounds frustrating on many levels! Terraform warns a user if they use an older version than what the state reports; it's reasonable that one would want the same warning if the plugin version differs. And it's odd and unfortunate that the aws provider version bump from 1.30 to 1.36 introduced breaking changes like that. 

I'll flag this as an enhancement, it's a good one. Having said that, especially since you're working on terraform configuration files with co-workers, you can avoid the problem in the future by [explicitly pinning the provider version](https://www.terraform.io/docs/configuration/providers.html#provider-versions). I can't recommend this enough if you've got multiple humans running terraform on their own machines.

**Comment by ScriptMyJob** [comment]
@mildwonkey Awesome!  I will have to ensure that I include that in my future projects.  

Thanks for the feedback!
