### ISSUE TITLE
terraform_remote_state data source doesn't get updated properly

### ISSUE THREAD

**Issue by aivanov1** [hashicorp/terraform#18964]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
data "terraform_remote_state" "mydevops_rs" {
  backend = "s3"
  config {
    region = "us-east-2"
    bucket = "mydevops"
    key = "terraform-state/mydevops"
  }
}
```

### Crash Output
I can reproduce this if needed.

### Expected Behavior

The expected behavior is that if we have a list variable in the output vars of the remote state, and an item is added to the list (in our case it is a list of maps, so a new map was added to the list), the data source will reflect the change.
### Actual Behavior

The behavior is mostly as expected, with the exception of an output variable in the remote state, which gets passed to a module, and then in the module it gets used as an input to an AWS provider, i.e. to select a region. In this case the key in the map is NOT available.
### Steps to Reproduce

1. Have a list of maps in your remote state, e.g.
```
remote_list = [
    { "region": "us-east-1", "other": "abc" },
    { "region": "us-east-2", "other": "def" }
    #### { "region": "us-west-2", "other": "NEW ENTRY (see Step 6)" }
]
```
2. Look up a value from the map, and use it as an input var to a module:
```
module "some_module" {
    source = "modules/foobar"
    target_region = "${lookup(data.terraform_remote_state.mydevops_rs.remote_list[0], local.vpc_region)}"
}
```
3. Inside the module, use the var in an aws provider block:
```
provider "aws" {
  alias = "internal"
  region = "${var.target_region}"
  version = "~> 1.9"
}
```
4. Now create a resource using the provider, e.g.
```
resource "aws_route" "source_to_target_public" {
  provider = "aws.internal"
  route_table_id            = ...
}
```
5. Congratulations, it all works fine!
6. Now add a new map entry to the _remote_list_, and be sure to use it in your code, i.e.
```
module "some_module" {
    source = "modules/foobar"
    # Note "0" index changed to "2"
    target_region = "${lookup(data.terraform_remote_state.mydevops_rs.remote_list[2], local.vpc_region)}"
}
```
7. If you do _terraform apply_ now you'll see it's complaining that it can't find the variable in the _foobar_ module.
### Additional Context

The workaround I had to use is to delete _data.mydevops_rs_ from the terraform state for the parent project via _terraform destroy -target data.mydevops_rs_ which prompted me to delete zero resources, but after I did, the next time I ran _terraform apply_ it all worked.

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
