### ISSUE TITLE
terraform output should not error when no outputs defined

### ISSUE THREAD

**Issue by aggallim** [hashicorp/terraform#18975]
### Current Terraform Version
```
Terraform v0.11.1
```

### Use-cases
We run Terraform in an automated pipeline for 100's of terraform projects over many AWS accounts and love the tool. We would like to include 'terraform output' in our standard pipeline to run against every project we maintain. However, if the project has no outputs defined Terraform will error.

```
+ terraform output
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the 
`terraform console` command to assist.
```

Having no outputs in a project is not an error and should not return error code 1. Returning a message informing the user of 'no outputs exist' with a return code 0 would be more appropriate.

### Attempted Solutions
Options are:
1. Have an output defined in every project as standard. 
2. Remove terraform output from our automated pipelines (losing value in showing the output)

### Proposal
Either:
1. Remove the error on the terraform output command with a message 'no outputs exist' where there are no outputs and return 0.
2. Include an option to the 'terraform output' command to 'ignore no outputs' or something to that extent.

**Comment by mildwonkey** [comment]
Thanks for submitting this, @aggallim! This definitely isn't the only command which returns error code 1 and arguably shouldn't.

I'm labeling this as a bug, because it's a personal pet peeve of mine :) I like to think that terraform successfully determined that there are no outputs and should return 0, just like you suggested.

It's not something the core team is going to be able to address in the near future, as we're all heads down on [0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview), but please add 👍 to the issue to help us prioritize our future work. PRs are also welcome, though I highly recommend waiting until the v0.12-dev branch is merged into master as it introduces a lot of changes.

**Comment by praveensastry** [comment]
Hi @mildwonkey this looks a nice bug for me to start understanding the codebase and contribute to terraform, so i would like to work on this enhancement (by adding an ignore-no-output option) / bug fix (by returning status 0, I personally tend to agree this with this). what do you think?
