### ISSUE TITLE
plan.tf: At 1:7: illegal char on destroy

### ISSUE THREAD

**Issue by Somebi** [hashicorp/terraform#18989]
Getting this error when trying to do terraform destroy
`plan.tf: At 1:7: illegal char`

After getting timeout on terraform apply via saved plan.tf, it seems plan somehow got corrupted...
`* hcloud_ssh_key.k8s_admin: Get https://api.hetzner.cloud/v1/ssh_keys/121203: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""`

Using:
```
Terraform v0.11.8
+ provider.hcloud v1.3.0
```

Or plan was already corrupted after doing terraform plan -out plan.tf etc.

**Comment by apparentlymart** [comment]
Hi @Somebi! Sorry for this confusing result.

By naming your saved plan file `plan.tf`, you've made it appear to Terraform as a configuration file, and so Terraform is then trying to parse it as if it were config. Since the plan file is a binary file, the configuration file parser quickly encounters a character it doesn't expect and exits.

The solution here is to name your file something that doesn't end in `.tf`. A common convention is to call it `tfplan`, for example.
