### ISSUE TITLE
Provider Versions html page not found

### ISSUE THREAD

**Issue by mkozjak** [hashicorp/terraform#19028]
From https://www.terraform.io/docs/providers/google/index.html there's a link to https://www.terraform.io/docs/provider/google/provider_versions.html which is not found.

Should probably lead to https://www.terraform.io/docs/configuration/providers.html#provider-versions?

**Comment by sportebois** [comment]
The page https://www.terraform.io/docs/providers/google/provider_versions.html exists. and my assumption is that it should be the correct target. 
The issue is that the link in providers/google/index is pointing to https://terraform.io/docs/provider/google/provider_versions.html  (without the `www.`)
This might or might not be caused by some website config changes (or maybe it was always broken).

If this assumption is correct, PR [#2193](https://github.com/terraform-providers/terraform-provider-google/pull/2193) fixes this

**Comment by rileykarson** [comment]
Thanks for the report! 

We mixed up `/providers/` with `/provider/` in several places in the Google provider including in index.html, so I've made PRs downstream to catch them all.

* https://github.com/terraform-providers/terraform-provider-google/pull/2196 will resolve this issue
* https://github.com/terraform-providers/terraform-provider-google/pull/2197 (backed by https://github.com/GoogleCloudPlatform/magic-modules/pull/538) will resolve all the references that https://github.com/terraform-providers/terraform-provider-google/pull/2196 does not.
