### ISSUE TITLE
Don't [just] use the AWS public IP when using the "connection" provisioner

### ISSUE THREAD

**Issue by iangelov** [hashicorp/terraform#1902]
Hello,

We're making use of terraform to provision ephemeral (performance testing) environments in addition to its regular usage. The way we're doing it is that we're running it from within AWS and not externally to it. This lead me to the discovery that terraform only uses the public IP for the "connection" provisioner when provisioning resources of the "aws_instance" type as opposed, for example, the public host. I've no idea about the rationale behind this choice, but I'd like to explore two different use cases:
- what would happen if we're provisioning new instances from within the same VPC the target instances are supposed to be living in?
- what would happen if we're provisioning new instances without public addresses?

What I see as possible improvement:
- try the public hostname instead of the public IP - then Amazon's DNS servers would transparently direct you to instance's internal hostname (unfortunately that would only work in EC2 Classic, but lots of people are still using it)
- and also try using the internal hostname/IP - which would allow for instances without public IPs or such that are inside the same VPC or are in VPC peering with it to establish connectivity

Of course right now I've a workaround in place to overcome this limitation, but terraform has become so feature rich with the last 2 major releases that I'd rather not stray from its way.

**Comment by apparentlymart** [comment]
Have you tried setting the ``host`` attribute in your ``connection`` block? You should be able to use interpolations there to get all four addresses for your instance. (public/private ip/host)

...or maybe I just misunderstand what you're looking for.

**Comment by mikeyhill** [comment]
I think what he's saying is there needs to be the option of using the internal IP when provisioning the instance. My use case is that I can only connect to an instance via the VPN and no instances in my VPC ever receive a public IP (aside from NAT instances).

**Comment by apparentlymart** [comment]
I still think I'm not understanding what's being asked here, but here's how I provision some not-publicly-reachable EC2 instances in my application (the security group on these instances only allows SSH access from our internal network, so the public IP wouldn't work):

```js
resource "aws_instance" "example" {
    # (other EC2 instance config attributes)

    connection {
        host = "${self.private_ip}"
        user = "provisioning-user"
        key_file = "provisioning-private-key"
    }

    # (and then some provisioner blocks)
}
```

``self`` works when the connection block is nested inside the resource block. If you have a provisioner outside of the resource, you can write this the long way:

```js
connection {
    host = "${aws_instance.example.private_ip}"
    user = "provisioning-user"
    key_file = "provisioning-private-key"
}
```

Does that solve the problem, or am I continuing to misunderstand?

**Comment by knuckolls** [comment]
^^ this is exactly what we do to provision against the private_ip.

**Comment by kuberkaul** [comment]
@apparentlymart  - What about google compute engine ? I try the same but gives me : 

```Error applying plan:

1 error(s) occurred:

* Resource 'google_compute_instance_group_manager.djin-dev-search.0' does not have attribute 'private_ip' for variable 'google_compute_instance_group_manager.djin-dev-search.0.private_ip'
```

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

(At the time I posted my earlier comments I was just a Terraform user, but since then I have become a Hashicorp employee working on Terraform.)

The example I shared before generalizes to any resource that exposes an IP address as an attribute. However, it can't be used with `google_compute_instance_group_manager` or with `aws_autoscaling_group` because in those cases Terraform is not directly managing the individual instances but is rather managing a remote service that creates and destroys resources automatically.

Terraform can only provision resources that it directly created. To provision "auto-scaling"-type instances, it's necessary to make use of mechanisms provided by the service that is handling the auto-scaling. The most common ways to achieve this are:

* Creating a custom machine image, e.g. using [Packer](https://www.packer.io/), that has the necessary start up actions incorporated into it.
* Using the `metadata_startup_script` argument (for `google_compute_instance_group_manager`) and `user_data` (for `aws_launch_configuration`) arguments to define actions for the instances to take when they start up.

From reviewing the discussion above it seems like what's being requested is already possible, so I'm going to close this. Thanks to everyone for the discussion here and sorry it sat here idle for so long.
