### ISSUE TITLE
named parameters in format strings

### ISSUE THREAD

**Issue by rmalchow** [hashicorp/terraform#19058]
### Current Terraform Version
```
v0.11.8
```

### Use-cases

we often have specific needs for "Name" tags in AWS and hostnames. such as:

`     customer-project-mongo-awseuc1-01-prod.example.com`

### Attempted Solutions

we currently use very long format strings such as:

    `format("%s-%s-%s-%s%02d-%s.%s", "customer", "project", "type", count.index+1, "stage", "example.com")`

this makes it difficult to read, and it's not exactly easy to change things like the order of replaced tokens. 

### Proposal

it would be very nice to have named parameters in the format string, i.e.:

`     "%customer:s-%project:s-%count:02d"`

or maybe:

`     "%(customer)s-%(project)s-%(count)02d"`

(i'm not so passionate about the exact format) and then pass this into the format function along with one or more maps containing those keys. this way, we could predefined those naming templates, and fill them with values without having to know the exact right order.

**Comment by apparentlymart** [comment]
Hi @rmalchow! Thanks for sharing this use-case and feature request.

I think many users manage not to run into these situations because Terraform's interpolation syntax is often a more convenient way to build strings and so `format` is usually relegated to very simple situations. Indeed, in principle what you suggested here could be expressed using interpolation for everything except the special decimal formatting part:

```hcl
"${customer}-${project}-${format("%02d", count)}"
```

I feel a _little_ hesitant to introduce what could be thought of as a second, slightly-different interpolation syntax, but I can see that there are some cases where the format _itself_ might be dynamic (e.g. set by a variable), and so being able to express more complex formats in strings could be valuable in that case.

As part of the Terraform 0.12 work we are introducing a new implementation of `format` (with [better docs](https://github.com/hashicorp/terraform/blob/c6804959be3207b1c38b46bce5f36026dfa5c8f7/website/docs/configuration/functions/format.html.md)) that is designed to work with the improved configuration type system, so I think we'll at least have to hold on this until after that release (its scope is already pretty large, so we're not planning to add anything new to it) but I'd be open to digging into more details about this later on.

Since as you noted there's a number of variant `printf` spin-off formats that include named parameters, part of that would involve deciding which of those seems like the best fit for Terraform, which is a decision I'd expect to make based on familiarity with some other language that users are likely to be comfortable with already.

The other thing to figure out is how to add this functionality in a compatible way: although I believe it's not commonly used, it technically possible today to pass a map as a real argument to apply a formatting verb to, and so we may unfortunately be required to add a separate function entirely to compatibly introduce the new interface of passing one format string and a map. At that point, since it would no longer be possible to use the traditional printf positional style at all (the argument can't be both a map single map and a variadic list at the same time) and so it might make more sense to step away from the `printf` format style altogether and use something with a syntax more intuitive for named arguments.

This seems like one of those situations where the design phase is more important and possibly trickier than the implementation phase, so let's use this issue to reach a conclusion on what best to do before moving forward to implementation. An outcome of this discussion _might_ be that this ends up being so close to the interpolation syntax that it would be confusing, or it might be that we find a good compromise to avoid that confusion.

As noted above, we won't be able to make any _implementation_ progress on this until after 0.12.0 at least, but that doesn't mean we can't discuss possible approaches in the mean time.

**Comment by rmalchow** [comment]
hi martin,

thank you for taking the time to write such a detailed and thoughtful response. your reasoning is clear, and i fully understand. a couple more details from my side, though. i agree that in many cases, the interpolation syntax is doing just fine. however, the situation we find ourselves in is this: we try to have as much information as possible attached to an object, so we can tell where it is, what it's doing, and how urgent fixing it is once it's broken. so, giving a customer of "foo" and a project of "bar", a hostname might look like this:

` {cust}-{project}-{purpose}-{type}-{region}{az}-{num}-{env_type}.{domain}`

resulting in:

`      foo-bar-mongors1-db-awseuc1a-001-prod.example.com`

the same goes for many, many, other things such as vpcs, subnets, security_groups, nat/internet/customer gateways, rds instances, efs/ebs volumes etc. 

they all share certain parts, with other parts being optional or non-existant. currently, we have two apprroaches. one, obviously, is:

`format("${local.customer}-${local.project}-mongors1-${local.aws_region}${var.availability_zones[count.index % length(var.availability_zones)]}-${count.index + 1}-${local.env_dev}.${local.domain}", .... )
`
and this has to go (with slight modifications) into more or less every resource. with all the lack of readibility and off-by-one errors that come with it.

and the second one, while shorter, is still ugly: we preassemble common parts, and replace some format specs with another format spec .... so that we have a "partially" filled format string:

`     a = format("%s-%s-%s", "foo", "bar", "%02d")

and then:

`    b = format(a,count.index + 1)`

would give us:

`      b == "foo-bar-01"`

as for backwards compatibility - i would think that it should be possible to switch to named parameters only if you encounter any in the format string, and otherwise just stay with the old behaviour. this would raise the question how many people put:

`     %(name)s`

or

`     %(number)02d`

in their format string AND have a map that contains the corresponding key, but actually want this to go into the result verbatim. i think that limits the number of people affected by any incompatibilities dramatically.

as for implementation: yes, this should be easy - the current implementation is, as far as i understand it, basically a wrapper around Sprintf. here is a basic idea of the rest:

[https://play.golang.org/p/S_wYkYJXJh8](https://play.golang.org/p/S_wYkYJXJh8)

or maybe:

```
func interpolationFuncFormat() ast.Function {
	return ast.Function{

                // does this mean only args of type String (or implicit casts thereof) are accepted?
		ArgTypes:     []ast.Type{ast.TypeString},
		Variadic:     true,
		VariadicType: ast.TypeAny,
		ReturnType:   ast.TypeString,
		Callback: func(args []interface{}) (interface{}, error) {

			format := args[0].(string)

			// not sure if "\\w*" for the format specs is actually 
			// what we want here
			r, _ := regexp.Compile("(%)(\\((\\w+)\\))(\\w*)")
			
			matches := r.FindAllStringSubmatch(format,-1)

			// not so certain about the best way of getting 
			// this map - maybe iterate over args?
			// anyway, this is my own (dummy) map
			m := map[string]string{
				"foo":"bar"
			}
			
			for _,match := range x {
				s := match[3]
				t, p := m[s]
				if p {
					// yes, it exists in the map, run the format separately
					u := fmt.Sprintf(match[1]+match[4],t)
					input = strings.Replace(format,match[0],u,-1)
				}
			}
			return fmt.Sprintf(format, args[1:]...), nil
		},
	}
}
```
(sorry, i usually don't do go ... )

anyway, as you said, the organizational issues around this would probably be more difficult than the actual implementation, so i do appreciate your time, and i would be happy if this might find its way in, ideally making other people happy as well.

**Comment by mildwonkey** [comment]
Hi @rmalchow !

In terraform 0.12, you can use the [`template_file`](https://www.terraform.io/docs/providers/template/d/file.html) datasource and an inline [string template](https://www.terraform.io/docs/configuration/expressions.html#string-templates) to get the same output in an easier-to-read manner:

```
data "template_file" "longname" {
  count = 3
  template = "${var.cust}-${var.project}-${var.purpose}-${var.type}-${var.region}${var.az}-${count.index}-${var.env_type}.${var.domain}"
}
```

(I used `var.thing` in this example, but you can also use `local.thing`).

I am going to close this issue since there is a workaround and we don't have any current plans to implement named parameters. Thanks!
