### ISSUE TITLE
list modules for a Terraform configuration

### ISSUE THREAD

**Issue by EximChua** [hashicorp/terraform#19126]
### Current Terraform Version

```
Terraform v0.11.8
```

### Use-cases

It's tough to figure out the modules available in a Terraform configuration, that can be used in terraform output -module=xxxxx where xxxx are the modules.

### Attempted Solutions

terraform show shows a lot of output, including the module names

### Proposal

terraform list-modules to list all the available modules that can be used in terraform output -module=xxxx

**Comment by mchodson** [comment]
alt solution `terraform state list | awk -F'[/.]' '{print $2}' | uniq`

**Comment by mildwonkey** [comment]
Since this issue was opened, we open-sourced a tool called [terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect) which you might find useful in this instance.

Here's an example of the output run against a configuration with two modules, `pets` and `more_pets `:

```
$ terraform-config-inspect

# Module `.`

Core Version Constraints:
* `>= 0.12`

Provider Requirements:
* **random:** (any version)

## Input Variables
* `pet_count` (default `3`)

## Managed Resources
* `random_pet.my_pet` from `random`

## Child Modules
* `more_pets` from `./modules`
* `pets` from `./modules
```

**Comment by mildwonkey** [comment]
Hi all! I am going to close this issue, both because there is a workaround, but also the original problem no longer applies to the current version of terraform.

* `terraform-config-inspect` can be used to list modules referenced in the current configuration
* In terraform 0.12, only root-level outputs are stored in state, so the flag `-module=xxxx` is deprecated. If you want to access an output from a module, you need to directly reference it in the root module:

`main.tf`:
```
module "my_module" {
  source = "./my_module"
}

output "module_output" {
   value = module.my_module.some_output
}
```

`my_module/main.tf`:
```
output "some_output" { value = "hi!" }
```

Thanks for opening this feature request, and please don't hesitate to open new feature requests or issues!
