### ISSUE TITLE
Module outputs are not latched until completed.

### ISSUE THREAD

**Issue by nowhammies** [hashicorp/terraform#19158]
Hi there,

Terraform Version 0.11.8

Expected Behaviour

I have 3 Machine resources I am creating. The scenario is I bring them up. Use a module to provision them to a existing windows domain through sssd

Once that is complete I want to provision a set of ssh keys so a specific user can shell into machines without a password. Each of the modules outputs a list of host_ips given the number of machines created in the module.

They they go and join to the domain and the join domain module outputs the same host_ips that were input to it. The same goes for the Worker machines that are joined to the module.

The next module runs with the joined domain credentials and connects to the management machine. Inside it uses the join domain credentials to install ssh keys for that user to the worker machines.

After terraform apply completion The worker machines have ssh keys installed for the domain user.

Actual Behavior:

Some of the machines have the key installed because as soon as the computed ip from the machines are resolved all other module provisoners are trying to run and in certain interleaves the MGMT box may be created and the other machines be created but the join domain modules for the WORKERS are not completed or have failed. SSH keys only get installed to the boxes that have completed.

module "MGMT-MACHINE" {
  source              = "../modules/linux-private"
  datacenter_id = "${module.datacenter.datacenter_id}"
  resourcepool_id = "${module.compute.resourcepool_id}"
  network_id = "${module.network_internal.network_id}"
  datastore_id = "${module.datastore_1.datastore_id}"
  folder_name = "${var.parent_folder}/${var.folder_name}"
  internal_addr_range = "${var.addr_range_internal}"
  internal_addr_start = "${var.addr_start_internal +1}"
  linux_server_number = "1"
  template_name = "${var.test_template_name}"
  machine_name = "MGMT"
  default_gateway = "${var.default_gateway_internal}"
  env_name =  "${var.env_name}"
}
module "WORKER1-MACHINE" {
  source              = "../modules/linux-private"
  datacenter_id = "${module.datacenter.datacenter_id}"
  resourcepool_id = "${module.compute.resourcepool_id}"
  network_id = "${module.network_internal.network_id}"
  datastore_id = "${module.datastore_1.datastore_id}"
  folder_name = "${var.parent_folder}/${var.folder_name}"
  internal_addr_range = "${var.addr_range_internal}"
  internal_addr_start = "${var.addr_start_internal +2}"
  linux_server_number = "${var.count_TEST}"
  template_name = "${var.test_template_name}"
  machine_name = "WORKER1"
  default_gateway = "${var.default_gateway_internal}"
  env_name =  "${var.env_name}"
}
module "WORKER2-MACHINE" {
  source              = "../modules/linux-private"
  datacenter_id = "${module.datacenter.datacenter_id}"
  resourcepool_id = "${module.compute.resourcepool_id}"
  network_id = "${module.network_internal.network_id}"
  datastore_id = "${module.datastore_1.datastore_id}"
  folder_name = "${var.parent_folder}/${var.folder_name}"
  internal_addr_range = "${var.addr_range_internal}"
  internal_addr_start = "${var.addr_start_internal +3}"
  linux_server_number = "${var.count_TEST}"
  template_name = "${var.test_template_name}"
  machine_name = "WORKER2"
  default_gateway = "${var.default_gateway_internal}"
  env_name =  "${var.env_name}"
}
module "MGMT-join-domain" {
  source = "../modules/join-domain"
  search_domain = "${var.domain_search_internal}"
  resource_count = "${var.count_MGMT}"
  resource_ips = "${module.MGMT-MACHINE.host_ips}"
  resource_names = "${module.MGMT-MACHINE.host_names}"
  dns_servers = "${var.dns_servers_internal}"
  domain_username = "${var.domainadmin_username_internal}"
  domain_password = "${var.domainadmin_password_internal}"
  admin-username = "${var.admin-username}"
  admin-password = "${var.admin-password}"
}
module "WORKER1-join-domain" {
  source = "../modules/join-domain"
  search_domain = "${var.domain_search_internal}"
  resource_count = "${var.count_WORKER1}"
  resource_ips = "${module.WORKER1-MACHINE.host_ips}"
  resource_names = "${module.WORKER1-MACHINE.host_names}"
  dns_servers = "${var.dns_servers_internal}"
  domain_username = "${var.domainadmin_username_internal}"
  domain_password = "${var.domainadmin_password_internal}"
  admin-username = "${var.admin-username}"
  admin-password = "${var.admin-password}"
}
module "WORKER2-join-domain" {
  source = "../modules/join-domain"
  search_domain = "${var.domain_search_internal}"
  resource_count = "${var.count_WORKER2}"
  resource_ips = "${module.WORKER2-MACHINE.host_ips}"
  resource_names = "${module.WORKER2-MACHINE.host_names}"
  dns_servers = "${var.dns_servers_internal}"
  domain_username = "${var.domainadmin_username_internal}"
  domain_password = "${var.domainadmin_password_internal}"
  admin-username = "${var.admin-username}"
  admin-password = "${var.admin-password}"
}
module "workflow-ssh-config-internal" {
  source = "../modules/ssh-key-config"
  search_domain = "${var.domain_search_internal}"
  resource_count = "1"
  resource_ips = "${module.MGMT-join-domain.host_ips}"
  management-username = "${var.domain_installer_username_internal}"
  management-password = "${var.domain_installer_password_internal}"
  domain-username = "${var.domain_installer_username_internal}"
  domain-password = "${var.domain_installer_password_internal}"
  ssh_ips = "${join(",",concat(split(",",module.WORKER2-join-domain.host_ips),split(",",WORKER1-join-domain.host_ips),))}"
}

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

Additional Context. 

Is there a way to only expose the output variables in a module only after it successfully executes. or set the the output variables inside the module to be computed. ?

**Comment by apparentlymart** [comment]
Hi @nowhammies! Sorry things aren't working as expected here.

In Terraform's dependency graph, each individual output value and variable is a separate node in the graph, which then allows actions from one module to begin before all actions from another module have completed, for maximum concurrency.

However, it sounds like in your case this model is causing problems because there are some side-effects that are not fully captured in the dependency graph, and so downstream actions are beginning before all of their upstream actions are resolved. Since I can't see the internals of your modules here I can't say exactly why that would be, but I assume it's caused by those side-effects being triggered by a resource that the output values do not themselves depend on, and so Terraform doesn't know that the side-effect must complete before considering the output "ready".

The usual way to resolve this is to give Terraform more information about when a particular output is ready. In your case, it sounds like the modules are exporting a `host_ips` output value with IP addresses that do not become fully usable until the side-effect has completed. You can tell Terraform this by adding an extra `depends_on` argument to the `output` block:

```hcl
output "host_ips" {
  value = (whatever value you already have)

  # Host IP addresses are not usable until the provisioners in null_resource.foo
  # have completed, since otherwise SSH keys are not registered.
  depends_on = ["null_resource.foo"]
}
```

With an extra dependency annotation like this, any resource or other provisioner that depends directly or indirectly on this output will wait for `null_resource.foo` to be fully created/updated before proceeding.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by nowhammies** [comment]
I did try the gitter page. I did not get any responses. You suggestion fixed our issue thank you! I will see what I can contribute to docs and examples to help clarify for future users.

Just wanted to say the software your team has built has us from an application environment from a  2-3day long manual process with varying degrees of consistency to creating an application environment on demand down 6 minutes with a high degree on consistency. 

Kudos to everyone on the Hashicorp Team!
