### ISSUE TITLE
"terraform plan" should produce an error when given a plan file

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/terraform#19235]
### Terraform Version
```
v0.11.10
```

### Terraform Configuration
s3 backend with terraform files containing aws data sources

### Actual Behavior
running `terraform plan <plan_name>` updates the remote state

### Expected Behavior
running `terraform plan <plan_name>` does not update the remote state

### Steps to Reproduce
1. `terraform init` with s3 backend config (remote state file does not exist)
2. `terraform plan -out=tfplan .` (remote state file does not exist)
3. `terraform plan tfplan` (state file now exists)

### Additional Context
running inside concourse ci pipeline

according to documentation, state should not be updated on a plan, e.g.:
https://www.terraform.io/guides/running-terraform-in-automation.html
> Although the plan step updates the state to match real resources, thus ensuring an accurate plan, the updated state is not persisted, and so this command can safely be used to produce "throwaway" plans that are created only to aid in code review.

https://www.terraform.io/docs/commands/plan.html
>This command is a convenient way to check whether the execution plan for a set of changes matches your expectations without making any changes to real resources or to the state.

I'm trying to use the `terraform plan <plan_name>` command to view an existing plan, so that an operator can confirm the changes

I want to use `-refresh=true` because the operator should know what the actual effects will be when ran

However, the state file should not be updated when viewing the plan, instead it should refresh and then 'throwaway' the state, correct?

**Comment by eedwards-sk** [comment]
Is there anything I can do to help surface this issue better?

As it stands, I cannot use "viewing planfiles" in my workflow, or I risk unintended changes to the remote state.

**Comment by apparentlymart** [comment]
Hi @eedwards-sk! Sorry for this strange behavior, and thanks for reporting it.

Passing an already-existing plan file to `terraform plan` is, I think, not something that is intentionally allowed but rather something that came as a consequence of how some code is shared between the various main Terraform commands. The behavior is, therefore, strange and unexpected. I expect the way we will resolve this issue is to make `terraform plan tfplan` generate an error, since that command doesn't really make sense within the intended Terraform workflow.

To view a plan file that was already created, you can use `terraform show tfplan` instead. That will _just_ render the plan to the terminal, in a similar way to what `terraform plan` generated in the first place.

**Comment by eedwards-sk** [comment]
@apparentlymart 

Thanks so much for the response and clarity over the workflow. I'm trying to build a CI pipeline with a 'view plan' step, so this was throwing quite the wrench in it. I'm excited to try the `show` command instead.

Generating an error when running against a plan file would definitely help, as would updating the docs on the plan command. That's where I mostly got set on this trail, specifically these two lines from https://www.terraform.io/docs/commands/plan.html:

>Usage: terraform plan [options] **[dir-or-plan]**

>If the command is given an existing saved plan as an argument, the command will output the contents of the saved plan. In this scenario, the plan command will not modify the given plan. **This can be used to inspect a planfile.**

Thanks again.

**Comment by apparentlymart** [comment]
Thanks for pointing out the docs there. I'm not sure what is the story behind that; perhaps this used to be the way to do this prior to the implementation of the `terraform show` command and the docs have grown outdated.

I'm going to rescope this issue slightly to cover updating that documentation and removing what seems to be vestiges of an earlier usage that is no longer fully functional.

**Comment by apparentlymart** [comment]
From a quick inspection of the code, I see that the error message I mentioned is already in place in master ready to be included in the forthcoming v0.12.0 release:

https://github.com/hashicorp/terraform/blob/f4cdb9945b76a134481cd214a27fc45f33e31b90/command/plan.go#L61-L68

So the remaining work here is to get the docs updated. Since the behavior change here is already included in the v0.12.0 scope I'm going to add this issue to the v0.12.0 milestone to represent the need to update the docs as well before release.

**Comment by elliot-resdiary** [comment]
@apparentlymart 

>Passing an already-existing plan file to terraform plan is, I think, not something that is intentionally allowed but rather something that came as a consequence of how some code is shared between the various main Terraform commands. 

The documentation for the plan command continues to state the following:
>If the command is given an existing saved plan as an argument, the command will output the contents of the saved plan. In this scenario, the plan command will not modify the given plan. This can be used to inspect a planfile.

However, it seems this behavior was made unavailable in 0.12 and `terraform show` displays a lower resolution view of the plan than what's shown when the `terraform plan` command was run previously. Has this functionality been lost?
