### ISSUE TITLE
google_compute_instance unable to properly utilize lifecycle of create_before_destroy

### ISSUE THREAD

**Issue by rockholla** [hashicorp/terraform#19255]
### Terraform Version

```
Terraform v0.11.10
```
Tested with both `google` and `google-beta` provider versions:
```
* provider.google: version = "~> 1.17"
* provider.google-beta: version = "~> 1.19"
```

### Terraform Configuration Files

```hcl
resource "google_compute_instance" "my_vm" {
  depends_on                  = ["google_project_service.compute"]
  project                     = "${module.project.id}"
  name                        = "my-vm"
  machine_type                = "${var.vm_machine_type}"
  zone                        = "${var.google_region}-a"
  allow_stopping_for_update   = true
  network_interface {
    subnetwork  = "${element(module.project.subnetwork_uris, 0)}"
    access_config {
      // Ephemeral IP
    }
  }
  boot_disk {
    device_name = "my-vm"
    initialize_params {
      type  = "${var.vm_boot_disk_type}"
      image = "..."
      size  = "${var.vm_boot_disk_size_gb}"
    }
  }
  metadata {
    startup-script = "${file("${var.vm_startup_script_path}")}"
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output

Pretty sure the error alone should be enough:

```
Error: Error applying plan:

1 error(s) occurred:

* google_compute_instance.my_vm: 1 error(s) occurred:

2018-11-01T17:13:57.624-0600 [DEBUG] plugin.terraform-provider-google_v1.17.1_x4: 2018/11/01 17:13:57 [ERR] plugin: plugin server: accept unix /tmp/plugin104039794: use of closed network connection
* google_compute_instance.my_vm: Error creating instance: googleapi: Error 409: The resource 'projects/.../zones/.../instances/my-vm' already exists, alreadyExists
```

### Expected Behavior

We should be able to create a new instance of the same name in the same project/zone before destroying the previous one.

### Actual Behavior

I don't think `create_before_destroy = true` can work in the case of a VM trying to be replaced in the same project/zone with the same name, unless I'm missing another clever way to do this other than via `lifecycle`.

### Steps to Reproduce

With the above `google_compute_instance` definition:
1. `terraform apply ...`
2. `terraform taint google_compute_instance.my_vm`
3. `terraform apply ...`

With the `lifecycle` rule for creating the replacement instance before destroying the old one, you'll hit the error above.

### Additional Context

I realize this issue may simply be considered "won't fix" because of GCP's lack of support for renaming an existing instance, but figured I'd bring it up nonetheless in case there were ideas around solutions or workarounds. Thanks.

**Comment by apparentlymart** [comment]
Hi @rockholla! Sorry for this annoying behavior.

The way we usually address this is for the provider itself to offer an alternative prefix specification argument -- I think that'd be `name_prefix` in this case, if I understood correctly -- and then have the provider generate a random suffix to append to it for each `Create` call. Since Terraform Core itself doesn't know which attributes have a uniqueness constraint, this functionality must be implemented in the provider itself.

An example of this pattern is in the AWS provider's [`aws_elb` resource type](https://www.terraform.io/docs/providers/aws/r/elb.html). It too has a name uniqueness constraint, and so it offers `name_prefix` as an alternative to `name` so that a unique name can be produced for each generation of the load balancer during a create-before-destroy replace operation.

Since this is not something Terraform Core will address directly, I'd suggest opening an issue about it in [the Google Cloud provider's repository](https://github.com/terraform-providers/terraform-provider-google), to see if the maintainers of this provider would consider adding a similar `name_prefix` argument or if there is some other pattern commonly used with the Google Cloud provider in this situation that I don't know about.

**Comment by rockholla** [comment]
Thanks @apparentlymart, I suppose the `name_prefix` route is the best option for now. It does present some extra hurdles in other automated tooling around interacting with this instance in this case.

Appreciate you taking the time to elaborate here, and will reach out the provider team specifically on other advice.
