### ISSUE TITLE
"Error releasing the state lock!". Executing force-unlock is impossible as no lock id is provided.

### ISSUE THREAD

**Issue by Lasering** [hashicorp/terraform#19296]
### Terraform Version
```
Terraform v0.11.10
```

### Terraform Configuration Files
```hcl
terraform {
    backend "consul" {
      address = "my.address.local"
      scheme = "https"
      datacenter = "datacenter1"
      access_token = "${random_uuid.consul-terraform-state-token.result}"
      path = "a/path/to/the/state"
      gzip = true
    }
  }
```

### Actual Behavior
While running `terraform apply` I sometimes get:

```
Error releasing the state lock!

Error message: consul lock was lost

Terraform acquires a lock when accessing your state to prevent others
running Terraform to potentially modify the state at the same time. An
error occurred while releasing this lock. This could mean that the lock
did or did not release properly. If the lock didn't release properly,
Terraform may not be able to run future commands since it'll appear as if
the lock is held.

In this scenario, please call the "force-unlock" command to unlock the
state manually. This is a very dangerous operation since if it is done
erroneously it could result in two people modifying state at the same time.
Only call this command if you're certain that the unlock above failed and
that no one else is holding a lock.
```

I would like to execute the force-unlock but to do that I need a lock id, which in this scenario seems impossible to acquire.

### References
#14312
#17535

**Comment by remilapeyre** [comment]
Hi @Lasering, thanks for reporting the issue.

The lock ID is now given when Terraform fails to acquire the lock. There is however an issue when running `terraform force-unlock $ID` that is tracked in https://github.com/hashicorp/terraform/issues/22174 and should be fixed by https://github.com/hashicorp/terraform/pull/25837.

I think we can close this issue as it is no longer relevant, feel free to open it again to give more information if you think I'm missing something.
