### ISSUE TITLE
0.12alpha2 - can't add tags to aws instance, Blocks of type "tags" are not expected here.

### ISSUE THREAD

**Issue by alanmcg** [hashicorp/terraform#19325]
### Terraform Version

```
Terraform v0.12.0-alpha2
+ provider.aws v1.40.0-6-gb23683732
```

### Terraform Configuration Files

```resource "aws_instance" "bastion" {
  ami                         = "ami-00035f41c82244dab"
  instance_type               = "t2.micro"
  associate_public_ip_address = true
  tags {
    Name = "testTag"
  }
}
~   
...
```

### Expected Behavior
Instance should be created with tags applied

### Actual Behavior
$ terraform plan 

Error: Unsupported block type

  on instances/bastion.tf line 5, in resource "aws_instance" "bastion":
   5:   tags {

Blocks of type "tags" are not expected here. Did you mean to define attribute
"tags"?

###

**Comment by apparentlymart** [comment]
Hi @alanmcg,

The correct way to write this configuration is to use the equals sign, since `tags` is a map attribute rather than a nested configuration block:

```hcl
  tags = {
    Name = "testTag"
  }
```

This is one of the situations where the HCL parser was a little too forgiving, allowing using certain syntax elements interchangeably even though they are quite different internally. Many weird bugs in Terraform 0.11 and prior resulted from HCL allowing constructs that the underlying Terraform features did not totally support, and so v0.12 uses a stricter parsing strategy here which also allows for the new benefit that the tag keys may now themselves be arbitrary expressions / interpolations, which wasn't possible before.

This is one of the changes that the 0.12 configuration upgrade tool will be able to do automatically once it is complete. We plan to get that tool into place before the v0.12.0 final release.

I'm going to leave this issue open here both in case others encounter the same situation (so they can see my answer here) and also to represent the need for the fixup for this to be implemented in the upgrade tool. We will hopefully also be able to make the error message for this situation more actionable by having it suggest directly to add the equals sign rather than simply allude to it.

Thanks for reporting this!

**Comment by alanmcg** [comment]
Excellent answer, using "=" fixes the issue, thank you!

**Comment by ravitandonrt** [comment]
Ref-counting on this issue -> +1

While the error was clear, either the config upgrade tool needs to address this or a backcompat in parser is needed. 

@apparentlymart Will the config tool ship separately, or is it the `0.12upgrade` command in alpha2? Although it's help text mentions modules.

Reference from OCI provider tf example: https://github.com/terraform-providers/terraform-provider-oci/blob/master/docs/examples/load_balancer/lb_full/lb_full.tf#L125

**Comment by apparentlymart** [comment]
The `0.12upgrade` command will do it, but it is not yet functional in the alpha builds.

**Comment by apparentlymart** [comment]
Hi again, @alanmcg!

In the 0.12.0-alpha4 build we have an extended error message for this which includes a more direct instruction to add the equals sign:

```
Error: Unsupported block type

  on tags-as-block.tf line 5, in resource "aws_instance" "foo":
   5:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.
```

0.12.0-alpha4 also includes an initial version of the configuration upgrade tool, and although we know it's still missing a number of features it does already have handling for this particular problem:

```diff
--- tags-as-block.tf.orig	2018-12-17 17:38:17.826066092 -0800
+++ tags-as-block.tf	2018-12-17 17:38:23.638301559 -0800
@@ -2,7 +2,8 @@
   ami                         = "ami-00035f41c82244dab"
   instance_type               = "t2.micro"
   associate_public_ip_address = true
-  tags {
+  tags = {
     Name = "testTag"
   }
 }
```

So it looks like we have in master fixes for both the error message and the upgrade path, and so I'm going to close this out. We'll continue to add more capabilities to the upgrade tool so that it's in good shape for 0.12.0-beta1 soon; as of right now it is missing some key features, and not ready for general use.

**Comment by dotnetpiper** [comment]
The correct way to do this as shown below, it worked for me.

`tags = {
      Owner = "Sachin Kalia"
    }`

Sachin Kalia
