### ISSUE TITLE
provider/aws: Invalid resource address

### ISSUE THREAD

**Issue by rohityadav-agilets** [hashicorp/terraform#19321]
### Terraform Version
v0.11.10

### AWS provider Version
v1.43.0

### Terraform Configuration Files
```
resource "aws_network_acl_rule" "private_inbound_${terraform.workspace}" {
  network_acl_id = "${aws_network_acl.("${terraform.workspace}-private.id")}"
  egress         = false
  rule_number    = 100
  rule_action    = "allow"
  protocol       = -1
  cidr_block     = "${var.vpc_cidr_start_ip}/20"
}
```
### Debug Output
```
Error asking for user input: Error parsing address 'aws_network_acl_rule.private_inbound_${terraform.workspace}': invalid resource address "aws_network_acl_rule.private_inbound_${terraform.workspace}"
```

### Steps to Reproduce
terraform init

**Comment by apparentlymart** [comment]
Hi @rohityadav-agilets!

Although the error message here is not very helpful, it is correct that this is not a valid resource address. Interpolations are not allowed in resource names. In practice there is never any need to include the workspace name in a resource name because the resource names already have a separate namespace per workspace per module, so you can literally just call this `private_inbound` and Terraform itself will take care of keeping track of the separate instances of this in one workspace vs. another.

This will generate a better error message in the forthcoming v0.12.0 release explaining more directly that interpolation expressions are not valid in that context.

**Comment by rohityadav-agilets** [comment]
@apparentlymart Thanks
