### ISSUE TITLE
Referring Statefile for specific subnet id to attach with NAT gateway with module

### ISSUE THREAD

**Issue by amrit3327** [hashicorp/terraform#19345]
I am trying to get particular  subnet id  with specific tag name form data source to use with NAT within the module but getting error

```hcl
data "terraform_remote_state" "vpcfile" {
  backend = "s3"
  config {
    bucket = "test"
    key = "vpc/test.tfstate"
    region = "us-east-1"
    profile = "default"
  }
}

resource "aws_eip" "tuto_eip" {
  vpc      = true
}

data "aws_subnet_ids" "all" {
  vpc_id = "${var.aws_vpc}"
}
#data "aws_subnet_ids" "all" {
 # vpc_id = "${var.aws_vpc}"
  #tags {
   #     Name = "Private_az3"
    #}

#}


resource "aws_nat_gateway" "ngw" {
  allocation_id = "${aws_eip.tuto_eip.id}"
  subnet_id  = "${data.aws_subnet_ids.all.id}"
 # subnet_id = "${data.terraform_remote_state.vpcfile.aws_subnet.main_az3.primary.id}"
   tags {
    Name = "NAT_az3"
  }
}
```

But I see no name base subnet id is statefile. Am I missing something or we can achieve it in different way. This I am doing it in aws_nat module for vpc automation aws.

**Comment by apparentlymart** [comment]
Hi @amrit3327,

In order to access a value from `terraform_remote_state` it must be declared as [an output value](https://www.terraform.io/docs/configuration/outputs.html) in the root module of the VPC configuration. You would then access it using the declared output name.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
