### ISSUE TITLE
Terraform provisioner can not winrm to Windows on Azure

### ISSUE THREAD

**Issue by nicknameyu** [hashicorp/terraform#19358]
Terraform version v0.11.7, AzureRM provider 1.17.0

Problem description: Provisioner can successfully provision script to new built Linux VMs, but cannot connect to new built windows VMs on Azure. 

Terraform code for provisioner
````
    connection {
      type     = "winrm"
      host   = "${azurerm_network_interface.vmstamp.private_ip_address}"
      user     = "${var.admin_username}"
      password = "${var.admin_password}"
      https    = true
      insecure = true
      timeout = "1m"
#      use_ntlm =true
    }
````
  
Error messages:
````
azurerm_virtual_machine.vmstamp: Still creating... (5m50s elapsed)
azurerm_virtual_machine.vmstamp (remote-exec): Connecting to remote host via WinRM...
azurerm_virtual_machine.vmstamp (remote-exec):   Host: 10.237.249.146
azurerm_virtual_machine.vmstamp (remote-exec):   Port: 5985
azurerm_virtual_machine.vmstamp (remote-exec):   User: azadmin
azurerm_virtual_machine.vmstamp (remote-exec):   Password: true
azurerm_virtual_machine.vmstamp (remote-exec):   HTTPS: true
azurerm_virtual_machine.vmstamp (remote-exec):   Insecure: true
azurerm_virtual_machine.vmstamp (remote-exec):   NTLM: false
azurerm_virtual_machine.vmstamp (remote-exec):   CACert: false
azurerm_virtual_machine.vmstamp: Still creating... (6m0s elapsed)
 
Error: Error applying plan:
 
1 error(s) occurred:
 
* azurerm_virtual_machine.vmstamp: timeout - last error: unknown error Post https://10.237.249.146:5985/wsman: dial tcp 10.237.249.146:5985: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
````
Several things I have tried.
1.	Was thinking about firewall issue. But packer can launch connect to the new built windows VM on the same laptop with below code:
````
  "communicator": "winrm",
  "winrm_use_ssl": "true",
  "winrm_insecure": "true",
  "winrm_timeout": "3m",
  "winrm_username": "packer",
 ````
2.	Tried https=true and https=false, both failed.
3.	Tried use_ntlm=true and use_ntlm=false, both failed.
4.	Tried port=5985 and port=5986, both failed. 5986 is actually not listening in a new windows VM from market image. 

what's the correct configuration for provisioner?

**Comment by mildwonkey** [comment]
Hi @nicknameyu. 

I'm sorry you're having trouble with the remote-exec provisioner. Your connection configuration in packer does not match the connection in terraform - have you confirmed that you have the correct username and password and can connect from the machine that's running terraform? 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
