### ISSUE TITLE
Droplet name with ternary op and element

### ISSUE THREAD

**Issue by webchi** [hashicorp/terraform#19351]
### Terraform Version

```
v0.11.10
```

### Terraform Configuration Files
```hcl
locals {
  name = "${var.is_server ? "serv" : "node"}"
}

variable client_zones {
    default = ["fra1", "lon1", "ams3"]
}

resource "digitalocean_droplet" "consul" {
    name   = "consul-${local.name}-${var.is_server ? count.index + 1 : element(var.client_zones, count.index) }"
}
```

### Crash Output
```
Error: module.consul-nodes-do.digitalocean_droplet.consul: 3 error(s) occurred:

* module.consul-nodes-do.digitalocean_droplet.consul[1]: __builtin_StringToInt: strconv.ParseInt: parsing "lon1": invalid syntax in:

consul-${local.name}-${var.is_server ? count.index + 1 : element(var.client_zones, count.index) }
* module.consul-nodes-do.digitalocean_droplet.consul[2]: __builtin_StringToInt: strconv.ParseInt: parsing "ams3": invalid syntax in:

consul-${local.name}-${var.is_server ? count.index + 1 : element(var.client_zones, count.index) }
* module.consul-nodes-do.digitalocean_droplet.consul[0]: __builtin_StringToInt: strconv.ParseInt: parsing "fra1": invalid syntax in:

consul-${local.name}-${var.is_server ? count.index + 1 : element(var.client_zones, count.index) }
```

### Expected Behavior
I think should be generated names like `consul-node-fra1`

### Actual Behavior
Everything crushes. But if I use `element` without ternary operator like this
```hcl
resource "digitalocean_droplet" "consul" {
    name   = "consul-${local.name}-${element(var.client_zones, count.index) }"
}
```
... everything is fine

**Comment by apparentlymart** [comment]
Hi @webchi! Sorry for this very strange behavior, and thanks for reporting it.

I think what's going on here is a consequence of the type-checking rule that a conditional must return the same type regardless of which of the expressions are selected. The current language type checker has a very simple behavior where in most cases (including this one) the type of the "true" expression decides the result type, and since you used `count.index + 1` there it therefore concluded that both of the results must be integers.

When the "false" path is taken then, it tries to convert the resulting string to an integer, causing the error you saw. This clearly doesn't align with what you intended here, and the low quality of this error message makes matters even worse.

Within current versions of Terraform as I write this, I think the workaround would be to use some technique to force the true expression to be a string as well, thus avoiding the unwanted conversion to integer. For example, using the `format` function should work because its result is _always_ a string:

```hcl
    name   = "consul-${local.name}-${var.is_server ? format("%d", count.index + 1) : element(var.client_zones, count.index) }"
```

I'm happy to report that the new language interpreter that is in master ready to be included in the forthcoming v0.12 release has a more sophisticated type checking algorithm that has a different behavior: it looks at both the true and false expression types and chooses the _most general_ type as the result, which means for your original input it chooses to return string because it knows that all numbers can convert to string but not all strings can convert to number.

I tried a variant of your configuration against the v0.12.0-alpha2 prerelease build to confirm:

```hcl
variable "is_server" {
  default = "false"
}

locals {
  name = "${var.is_server ? "serv" : "node"}"
}

variable client_zones {
  default = ["fra1", "lon1", "ams3"]
}

resource "null_resource" "consul" {
  count = 2

  triggers = {
    name = "consul-${local.name}-${var.is_server ? count.index + 1 : element(var.client_zones, count.index)}"
  }
}
```

(I switched to `null_resource` here just because the alpha builds don't include `digitalocean` provider support.)

```
$ terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.consul[0] will be created
  + resource "null_resource" "consul" {
      + id       = (known after apply)
      + triggers = {
          + "name" = "consul-node-fra1"
        }
    }

  # null_resource.consul[1] will be created
  + resource "null_resource" "consul" {
      + id       = (known after apply)
      + triggers = {
          + "name" = "consul-node-lon1"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

I also tried it with two types where conversion is impossible in either direction to make sure the error message was more specific in the new implementation:

```
Error: Inconsistent conditional result types

  on index-misbehave.tf line 17, in resource "null_resource" "consul":
  17:     name = "consul-${local.name}-${var.is_server ? [count.index + 1] : element(var.client_zones, count.index)}"
    |----------------
    | count.index is 0
    | var.client_zones is tuple with 3 elements
    | var.is_server is "false"

The true and false result expressions must have consistent types. The given
expressions are tuple and string, respectively.
```

This new message correctly indicates exactly which part of the expression is wrong (when rendered in my terminal, the true and false expressions in the conditional are underlined, though that was lost copy-pasting into this comment) and what the problem actually was, rather than reporting the final conversion error.

Since the fix for this bug is already in master and will be included in the forthcoming v0.12.0 release, I'm going to close this out. The workaround of forcing the first expression to be a string as I showed above should get things working in v0.11.10 for now.

Sorry again for this weird behavior!
