### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by nzimmerman-isp** [hashicorp/terraform#19353]
---
name: Bug report
about: Let us know about an unexpected error, a crash, or an incorrect behavior.

---

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.43.1
```

### Terraform Configuration Files

This is a terraform config generated by KOPS for building a Kubernetes cluster. Not sure what the relevant parts would be.

```hcl
...
```

### Crash Output

[crash.log](https://github.com/hashicorp/terraform/files/2574143/crash.log)

### Steps to Reproduce

terraform plan

**Comment by apparentlymart** [comment]
Hi @nzimmerman-isp,

Unfortunately there isn't enough information in this report to understand what problem you are seeing. In order to get enough information, please edit your issue to use [the full issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and then fill in the sections as indicated, and then we can try to reproduce the issue and fix it.

Thanks!

**Comment by nzimmerman-isp** [comment]
Updated. Not sure what further information is needed. I thought I had uploaded the crash.log on the first attempt, but apparently that failed. The file is present now.

**Comment by apparentlymart** [comment]
Thanks for the extra details, @nzimmerman-isp!

This crash seems to be in the AWS provider, so I'm going to have our bot migrate this issue over to that provider's own repository so that the maintainers can review it.
