### ISSUE TITLE
Don't require confirmation to deploy

### ISSUE THREAD

**Issue by mcandre** [hashicorp/terraform#19360]
I understand why `--force`/`--auto-approve` is required for `destroy`, in order to prevent accidental resource deletion. But do we really need confirmation when creating resources? I wonder if the convenience would be worth implicitly assuming `--force`/`--auto-approve` for deployments.

**Comment by apparentlymart** [comment]
Hi @mcandre! Thanks for this suggestion.

What you describe here is actually how Terraform behaved until v0.11.0 when `apply` was unified with `destroy` because in practice an apply action can be just as risky as a destroy action -- it might itself contain destroy actions, or it could create something that would disable or degrade another object already existing.

The `-auto-approve` option is provided for low-risk situations (e.g. development/staging environments), but we consider requiring confirmation to be a better default since it is the safer and more conservative position.

If this additional confirmation step is never useful to you, you can override it in your shell by setting the following environment variable:

```
TF_CLI_ARGS_apply="-auto-approve"
```

With this environment variable set, Terraform will behave as if `-auto-approve` were provided each time you run `terraform apply`, without you needing to explicitly type it.

**Comment by apparentlymart** [comment]
@mcandre, as I previously described, it was a conscious decision to move away from the behavior you are requesting. We provide the environment variable I mentioned as a way to override the safe default if you would rather optimize for convenience. We have no plans to change the default behavior of interactively prompting for confirmation.

I hope you can appreciate that the design of any software requires tradeoffs and in this case we took the safer path based on feedback from users sharing experiences of accidentally applying changes that were, in retrospect, harmful. We knew that there were some use-cases where the non-interactive behavior would be preferable, so we retained the ability to disable it via the `-auto-approve` option and the environment variable for setting that on by default.

Since we won't be making any changes to this behavior for the foreseeable future, I'm going to close this out. Thanks for sharing this feedback.
