### ISSUE TITLE
SE Hangout, Security in depth with Terraform and Vault. What patterns did person had in mind when replied to question?

### ISSUE THREAD

**Issue by vasilij-icabbi** [hashicorp/terraform#19386]
I was watching this SE Hangout:

https://www.hashicorp.com/resources/security-in-depth-terraform-vault

There was an interesting question: "**Are the secrets stored in Terraform state as well as Vault?**"

Replies on it, you can listen here: https://youtu.be/W30HKivEFWg?t=1163

The second reply literally was: **_There are actually patterns out there where you can do references from terraform into vault and actually have terraform call into vault where those secrets, so that you do not have to store them inside your state file._**

Also he said that they will post links to that patterns, that is here:  https://github.com/HappyPathway/Security-In-Depth

The only link I see is into Vault provider to terraform and first thing I read:

> **Important** Interacting with Vault from Terraform causes any secrets that you read and write to be persisted in both Terraform's state file and in any generated plan files. For any Terraform module that reads or writes Vault secrets, these files should be treated as sensitive and protected accordingly.

I have not done deep dig yet, but my question is: 

**What actual patterns person had in mind (that will help me avoid secrets to be exposed in state file) when was answering question and where I can read about them?**

Thank you.

**Comment by apparentlymart** [comment]
Hi @vasilij-icabbi!

I'm not sure exactly who was speaking when giving that answer (since they were audio-only) and so I'm not sure exactly what they were referring to, but it is generally true that any value Terraform can reference in expressions is always stored in the state, since the state is where references are resolved from.

Currently the best practice is to store state encrypted at rest and protect access to it, as Dave said in the video. Some people avoid credentials in state by requesting them directly from Vault prior to running Terraform and setting environment variables, which is a good pattern if the values are only used in provider configuration, but is of course not a fully-integrated solution. This may have been what the person in the video was referring to.

We have several ideas for how to improve on this in a future release, including some shorter-term solutions such as a way to request that a data source result only be retained in-memory for a single run (or in a saved plan) rather than being retained between runs, and more complex solutions for being able to encrypt parts of the state file in isolation. 

The umbrella issue for this problem is #516, so that is the place where we'll post any outcomes of future design or implementation work. Since there are already issues open for this, I'm going to close this out just to keep things consolidated.

**Comment by vasilij-icabbi** [comment]
Hello @apparentlymart,
Thank you for your reply and hope that the progress on this matter will be visible soon! :)\

Have one question though, you said:

> Some people avoid credentials in state by requesting them directly from Vault prior to running Terraform and setting environment variables, which is a good pattern if the values are only used in provider configuration, but is of course not a fully-integrated solution.

Did I get it right, that use of Environment variables assures that data will not appear in state? Or you meant that people run vault or instance setting environment variables?

**Comment by apparentlymart** [comment]
Hi @ vasilij-icabbi,

The important detail here is that provider settings are not written into the state. Therefore you can use the mechanisms the providers offer to set those settings via environment variables to avoid them ever appearing in the configuration _or_ state.

Data resource results _do_ get written to state, which is why requesting data from Vault that way causes it to be saved in state, regardless of what you do with that data.

**Comment by vasilij-icabbi** [comment]
Thank you @apparentlymart
