### ISSUE TITLE
Can't create method POST, GET with same parent with modules terraform.

### ISSUE THREAD

**Issue by yeumatbeo** [hashicorp/terraform#19383]
### Terraform Configuration Files
**Modules api:**
resource aws_api_gateway_resource api_gateway_resource {
  rest_api_id = "${var.rest_api_id}"
  parent_id   = "${var.parent_id}"
  path_part   = "${basename(var.path)}"
}
resource aws_api_gateway_method api_gateway_method {
  authorization = "${var.authorization}"
  authorizer_id = "${var.authorizer_id}"
  http_method   = "${var.http_method}"
  resource_id   = "${aws_api_gateway_resource.api_gateway_resource.id}"
  rest_api_id   = "${var.rest_api_id}"
  #api_key_required = "true"
}
resource aws_api_gateway_integration api_gateway_integration {
  rest_api_id             = "${var.rest_api_id}"
  resource_id             = "${aws_api_gateway_resource.api_gateway_resource.id}"
  http_method             = "${aws_api_gateway_method.api_gateway_method.http_method}"
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri = "arn:aws:apigateway:${var.region}:lambda:path/2015-03-31/functions/${var.lambda_arn}/invocations"
}
resource aws_lambda_permission lambda_pemission {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = "${var.lambda_arn}"
  principal     = "apigateway.amazonaws.com"
  source_arn    = "arn:aws:execute-api:${var.region}:${data.aws_caller_identity.current.account_id}:${var.rest_api_id}/*/${var.http_method}/${basename(var.path)}"
}

**And i have 2 file endpoint with GET, POST method:**
module students-get-endpoint {
  function_name = "students-get"
  http_method   = "GET"
  lambda_arn    = "${module.students-get-lambda.arn}"
  parent_id     = "${aws_api_gateway_rest_api.lambda-gateway.root_resource_id}"
  prefix        = "${var.prefix}"
  region        = "${var.region}"
  rest_api_id   = "${aws_api_gateway_rest_api.lambda-gateway.id}"
  authorizer_id = "${aws_api_gateway_authorizer.demo.id}"
  source        = "../modules/endpointStudents"
}

module students-post-endpoint {
  function_name = "students-post"
  http_method   = "POST"
  lambda_arn    = "${module.students-post-lambda.arn}"
  parent_id     = "${aws_api_gateway_rest_api.lambda-gateway.root_resource_id}"
  prefix        = "${var.prefix}"
  region        = "${var.region}"
  rest_api_id   = "${aws_api_gateway_rest_api.lambda-gateway.id}"
  authorizer_id = "${aws_api_gateway_authorizer.demo.id}"
  source        = "../modules/endpointStudents"
}

### Crash Output
* aws_api_gateway_resource.api_gateway_resource: Error creating API Gateway Resource: ConflictException: **Another resource with the same parent already has this name**: Students

### Actual Behavior
If I run only one method, create done well, but i want to create same time with them.
It means can't create 2 method GET, POST same time with modules terraform :( Or I got mistake somewhere? Please help me to know about this.

**Comment by apparentlymart** [comment]
Hi @yeumatbeo!

Since this is an AWS provider question it would've been better placed in [the AWS provider repo](https://github.com/terraform-providers/terraform-provider-aws), but in this case I think I see a problem: your "endpoint" module contains a `aws_api_gateway_resource` and you can only have one of those per path. To get what you want here you'll either need to redesign your module to be instantiated once per path (and create _multiple_ `aws_api_gateway_method` resources) or split the endpoints and methods into separate modules which you can compose together.

I can't help in more detail than that because I've not used API gateway for some time, but I hope that hint is helpful. Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
