### ISSUE TITLE
More user friendly error messages

### ISSUE THREAD

**Issue by leesdolphin** [hashicorp/terraform#19399]
### Current Terraform Version
```
Terraform v0.11.10

```

### Use-cases

I have written some terraform code has invalid syntax, and I would like to be pointed to the file, line and if possible character of the error

### Attempted Solutions

Note: I'm not looking for a solution to *my* syntax error, but a better way of exposing those errors to the user so that they can find them

#### Using `head -c` to convert the character to a location
```
$ terraform validate

Error: Error loading modules: module instance: Error loading .terraform/modules/3ca3ab722661e0d3600834990e86e826/main.tf: Error reading config for openstack_compute_instance_v2[instance]: parse error at 1:62: expected "}" but found "."

$ cat .terraform/modules/3ca3ab722661e0d3600834990e86e826/main.tf
< the contents of `compute/instance/main.tf` >
$ head -c 62 compute/instance/main.tf
provider "openstack" {}

resource "openstack_blockstorage_volu$
$
```

#### Using grep to find all references to a variable

```
$ terraform validate

Error: module 'compute': unknown variable referenced: 'subnet'; define it with a 'variable' block

$ grep -Hn 'subnet' compute/*.tf
compute/cron.tf:22:      fixed_ip_v4 = "${cidrhost(lookup(var.subnet, "cron"), count.index)}"
compute/db.tf:27:      fixed_ip_v4 = "${cidrhost(lookup(var.subnet, "db"), count.index)}"
compute/lb.tf:22:      fixed_ip_v4 = "${cidrhost(lookup(var.subnet, "lb"), count.index)}"
...
$ # No wait, the error is in the calling module
$ grep -Hn 'subnet' *.tf
main.tf:12:  network_subnet   = "${var.network_subnet}"
main.tf:16:  subnet  = "${var.subnet}"
variables.tf:9:variable "network_subnet" {}
variables.tf:11:variable "subnets" {
```

### Proposal
Errors that occur should be listed with the actual file name that the error came from, and the line number of the error.

I propose for in-tree modules(like the one above) it resolves the `.terraform/modules/3ca3ab722661e0d3600834990e86e826` to the path of the module(relative if it's a subfolder of the root dir; absolute otherwise); 

### References

- #1889

**Comment by mildwonkey** [comment]
hi @leesdolphin!

I'm sorry you've run into this - you're certainly not alone in your frustration with terraform's error messages. 

Improved error messages are coming in terraform 0.12, and they will include file name, line number, and containing block information. You can see a preliminary example in this [blog post](https://www.hashicorp.com/blog/terraform-0-12-reliable-json-syntax).

These improvements are already available in the alpha release, if you're interested in playing around with it (but keep in mind that it is very alpha, and should not be used against existing production infrastructure): https://releases.hashicorp.com/terraform/

Since these improvements are already in the master branch, I am going to close this issue. Thank you for reporting this, and happy terraforming!
