### ISSUE TITLE
Can't pass a list as a cli arg: unexpected token while parsing list: IDENT

### ISSUE THREAD

**Issue by arcotek-ltd** [hashicorp/terraform#19401]
### Terraform Version

`Terraform v0.11.10`

### Terraform Configuration Files

```hcl
variable "myVariable" {
    type = "list"
}
output "testOutput" {
    #value = ["${var.myVariable}"]
    value = "${var.myVariable}"
}
```

### Debug Output
```
2018/11/19 15:00:06 [INFO] Terraform version: 0.11.10  17850e9a55d33c43d7c31fd6ac122ba97a51d899
2018/11/19 15:00:06 [INFO] Go runtime version: go1.11.1
2018/11/19 15:00:06 [INFO] CLI args: []string{"C:\\Terraform\\terraform.exe", "apply", "-var", "'myVariable=[value1]'"}
2018/11/19 15:00:06 [DEBUG] Attempting to open CLI config file: C:\Users\john\AppData\Roaming\terraform.rc
2018/11/19 15:00:06 Loading CLI configuration from C:\Users\john\AppData\Roaming\terraform.rc
2018/11/19 15:00:06 [INFO] CLI command args: []string{"apply", "-var", "'myVariable=[value1]'"}
2018/11/19 15:00:06 [DEBUG] plugin: waiting for all plugin processes to complete...
```

### Expected Behavior
I'd expect a testOutput of "value1".

### Actual Behavior
```
invalid value "myVariable=[value1]" for flag -var: Cannot parse value for variable ("[value1]") as valid HCL: At 1:6: unexpected token while parsing list: IDENT
Usage: terraform plan [options] [DIR-OR-PLAN]
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform apply -var 'myVariable=["value1"]' `

### Additional Context
I am trying this from the DOS (command line) prompt on Windows 10. I have tried multiple variations of quotes and nothing works, including the confirmation that I am doing it correctly, given by @jbardin in  #17032.

### References

- #17032

**Comment by arcotek-ltd** [comment]
Thanks @apparentlymart. We actually want to use PowerShell, but couldn't get it to work, so we tried to simplify things by using "DOS". 

I'll try your suggestion and update here.

Thanks.

**Comment by arcotek-ltd** [comment]
Mmm, not a nice experience. @apparentlymart mentioned in #17032 that they use DOS to test. May I suggest that when testing Windows, you concentrate on PowerShell over DOS.

Anyway, @apparentlymart's suggestion worked in DOS, and I was able to get it to work by using backslash `\`.

PowerShell has been a little harder. Referencing the answer [here](https://stackoverflow.com/questions/18923315/using-in-powershell), I've been able to cobble together a mess:

```
$env:Var1 = "MyVal1"
$env:Var2 = "MyVal2"

terraform apply --% -var "myVariable=[\"%var1%\",\"%var2%\"]" 
```

I prefer to run CLI stuff through `Start-Process`, but I couldn't get it to work. Here's what I tried:

```
$a = "$([char]34)Var1$([char]34)"

$Arguments = @(
"apply" 
#"-var `"myVariable=[$([char]34)Var1$([char]34)]`""
"-var `"myVariable=[$a]`""
)

Start-Process -FilePath terraform.exe -ArgumentList $Arguments -NoNewWindow -Wait -Verbose -PassThru
```

The above example was one of a number of attempts, replacing backtick (PS escape character) and double-quote with the ASCII code. I also tried using back-slash and escaping that.

Thanks

**Comment by apparentlymart** [comment]
Thanks for confirming that the escaping worked in the standard Windows command interpreter, @arcotek-ltd.

Since we already have #17032 open for problems with powershell usage I'd like to consolidate the discussion back over there rather than having two parallel issues. Honestly the issues there are coming from how PowerShell interacts with traditional CLI processes (as opposed to its own applets) rather than anything Terraform itself can really solve -- by the time Terraform is running, PowerShell has already parsed and re-formatted all of the CLI arguments -- and so as I mentioned in the other issue I think the only strong path forward here would be to have a special Terraform PowerShell cmdlet that can work with the PowerShell API directly to extract the arguments and pass them to Terraform in a robust way.

Since the usage with the standard command interpreter is now solved, I'm going to close this out and we can continue investigating PowerShell usage over in #17032. Thanks!

**Comment by arcotek-ltd** [comment]
@apparentlymart, could you enlighten me as to what the "PowerShell API" is that you speak of please?

Thanks

**Comment by apparentlymart** [comment]
Hi @arcotek-ltd,

In the discussion in the other issue there was the idea of writing a [Cmdlet](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/cmdlet-overview) that could then accept arguments as cmdlet parameters and escape them properly to pass to Terraform.
