### ISSUE TITLE
Error: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by coolaqua23** [hashicorp/terraform#19416]
### Terraform Version
0.12.0-alpha2
 AWS provider version 1.45.0
```
...
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output
 Error: Failed to instantiate provider "aws" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

**Comment by apparentlymart** [comment]
Hi @coolaqua23! Thanks for reporting this.

I think you've run into the situation described in #19221. There's more discussion over there on possible causes and solutions but the summary is that it looks like you've got an official release of the `aws` provider installed there rather than the special one bundled inside the alpha2 zip file.

Since we already have #19221 open to track this, I'm going to close this just to consolidate. Thanks again for reporting it!
