### ISSUE TITLE
aws_ssm_maintenance_window_task timeoutSeconds parameter bug

### ISSUE THREAD

**Issue by debu99** [hashicorp/terraform#19449]
when you provide timedout parameter on maintenance window,

`  task_parameters {
    name   = "commands"
    values = ["pwd"]
  }
  task_parameters {
    name   = "workingDirectory"
    values = ["/"]
  }
  task_parameters {
    name   = "executionTimeout"
    values = ["1800"]
  }
  task_parameters {
    name   = "timeoutSeconds"
    values = 1200
  }`

it report error "Error: module.ssm.aws_ssm_maintenance_window_task.task_malware_check: task_parameters.3.values: should be a list"

but actually, after I checked with AWS cli, this parameter is not a list

#aws ssm describe-maintenance-window-execution-task-invocations --profile infra-terragrunt --region eu-central-1 --window-execution-id $WINDOW_ID --task-id $TASK_ID

{
    "WindowExecutionTaskInvocationIdentities": [
        {
            "WindowExecutionId": "123123123-f8b3-48ed-91c2-123143243",
            "TaskExecutionId": "424234-b96c-46f2-90e2-2342342",
            "InvocationId": "13123-204a-46e4-a5a3-24234234",
            "ExecutionId": "131231-3e0f-4061-9fd7-343434",
            "TaskType": "RUN_COMMAND",
            "Parameters": "{\"documentName\":\"AWS-RunShellScript\",\"maxConcurrency\":\"100%\",\"maxErrors\":\"1\",\"outputS3BucketName\":\"vincent-lambda-test\",\"outputS3KeyPrefix\":\"ssm\",\"parameters\":{\"executionTimeout\":[\"1800\"],\"workingDirectory\":[\"/\"],\"commands\":[\"pwd; ls -al /etc/\"]},\"targets\":[{\"targetKey\":\"tag:Name\",\"targetValues\":[\"aaaa-test-infra-bastion\"]}],\"timeoutSeconds\":1200}",
            "Status": "SUCCESS",
            "StatusDetails": "Success",
            "StartTime": 1542956595.713,
            "EndTime": 1542956601.684
        }
    ]
}

**Comment by mildwonkey** [comment]
Hi @debu99, sorry to hear you're having a problem. The terraform provider syntax does not necessarily match the AWS CLI syntax exactly. Have you tried updating the values in to a list? 

```hcl
  task_parameters { 
    name = "timeoutSeconds" 
    values = ["1200"] 
  }```

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by debu99** [comment]
no, you can not use list for timeoutSeconds

**Comment by apparentlymart** [comment]
This issue is about an AWS provider resource, so I'm going to have our bot migrate the issue to the AWS provider repository.
