### ISSUE TITLE
escaping of ${ does not work

### ISSUE THREAD

**Issue by kiney** [hashicorp/terraform#19462]
### Terraform Version
```
Terraform v0.11.10
+ provider.azurerm v1.19.0
```

### Terraform Configuration Files

```hcl
4 variable "foo" {
5   default = "foo$${bar"
6 }
```

### Expected Behavior
foo contains foo${bar

### Actual Behavior
```
Error: Error parsing /...path.../secrets.tf: At 6:2: literal not terminated
```

### Steps to Reproduce
terraform plan

### Additional Context
The parser seems to count if { and } match. When adding } to the string it works, but i need values containing just ${.
It should not count the { when the $ before it is escaped.

### References

I stumbled accross #2909. The difference is, that i have no closing } in my string.

**Comment by dh-harald** [comment]
```
resource "kubernetes_config_map" "filebeat" {
data {
    "filebeat.yml" = <<EOF
filebeat.registry_file: /var/log/filebeat/filebeat.registry
logging.level: ${LOG_LEVEL:info}
EOF
}
```
Gives error:
```

**Comment by apparentlymart** [comment]
Hi all! Sorry for this annoying behavior and thanks for reporting it.

It looks like you've hit the same root problem as described in #18069: Terraform is validating that interpolation sequences are not allowed by the language parser is still handling them (incorrectly) anyway for the purpose of allowing `${` sequences that have nested `{` inside them.

Over in #18069 I verified that this is fixed in master and ready to be included in the forthcoming v0.12.0 release, so I'm going to close this out. The way this is fixed is by having the parser accept `${ ... }` sequences in all quoted strings but to forbid _references to variables_ in the `default` instead, so the syntax is always handled consistently.

Unfortunately the workaround shared in that other issue of accepting the duplicate dollar signs and then fixing it via a `replace` call elsewhere won't work in the case where there is no closing `}`. For that situation, I think you'd additionally need to use a unicode escape on that second dollar sign to prevent the language parser from starting its logic of counting braces:

```hcl
variable "foo" {
  default = "foo$\u0024{bar"
}
```

**Comment by dh-harald** [comment]
Unfortunately, it's not interpolating `$\u0024` to `$`

**Comment by af6140** [comment]
Me have the same issue.

**Comment by apparentlymart** [comment]
The workaround I suggested must be combined with the one in #18069.
