### ISSUE TITLE
Add support for ".terraform-ignore"

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1948]
Ignore file, with syntax like standard VCS (e.g. `.gitignore`) would be helpful for situations when I'm pushing my code up to Atlas and I may not want to upload certain directories, yet keep those versioned in git.

https://www.terraform.io/docs/commands/push.html

I know that TF can detect existing VCS ignore files or I can use the `exclude` flag for Atlas backend, but I'm more looking for a systematic approach that can be shared across the team.

The only real use-case I see now is really Atlas, so you could say it should be called `.atlasignore`, but I was eventually thinking of using it even for ignoring `*.tf` and [`*.tfvars`](https://github.com/hashicorp/terraform/issues/1084) files when these are being autoloaded, so I can put some templates/examples into the repository and not prepend these with a dot to hide it away and without being worried that someone will accidentally execute this.

**Comment by JeanMertz** [comment]
I like this idea. How about `.tfignore`?

**Comment by pierrebonbon** [comment]
:+1:  An ignore file would be also helpful with the `file` provisioner, notably when copying a whole directory or directories.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

Starting in 0.9 and looking forward to future versions we have changed significantly how Terraform interacts with Terraform Enterprise (formerly "atlas"). The `terraform push` workflow will phase out in favor of having Terraform Enterprise as a remote backend.

It's likely that ignoring files when working with a remote backend will still be useful, but since there is broader work going on to redesign the relationship between Terraform and its Enterprise offering I'm going to close this out and we'll think about this some more once the transition is complete.

@pierrebonbon the use-case of ignoring files in the `file` provisioner seems like a good idea, but it seems distinct from what @radeksimko was proposing here and would probably be implemented just as another argument within the provisioner itself rather than as a separate file. With that said, we (the Terraform team) likely wouldn't work on such a thing in the near future, though if someone were interested in working on it we'd welcome a discussion in a fresh issue about how best to design it.
