### ISSUE TITLE
Terraform read details of existing resource

### ISSUE THREAD

**Issue by goelhimanshu** [hashicorp/terraform#19491]
I am facing an issue in terraform where I want to read details of some existing resource (r1) created via AWS web console. I am using those details in creation on new resource (r2) via terraform.

Problem is that it is trying to destroy and recreate that resource which is not desired as it will be failed. How can I manage not to destroy and recreate r1 when I do terraform apply.

Here is how I am doing it :

main.tf

```
resource "aws_lb" "r1"{

}

...

resource "aws_api_gateway_integration" "r2" {

  type                    = "HTTP"
  uri                     = "${aws_lb.r1.dns_name}}/o/v1/multi/get/m/content"
}

```

first I import that resource

` terraform import aws_lb.r1 {my_arn}`
next I apply terraform

`terraform apply`
error

` aws_lb.r1: Error deleting LB: ResourceInUse: Load balancer 'my_arn' cannot be deleted because it is currently associated with another service`

**Comment by apparentlymart** [comment]
Hi @goelhimanshu,

If you don't want to replace the load balancer then you need to review the changes planned by Terraform for that resource and update the configuration to match the _old_ values so that Terraform will not see the load balancer as needing to be changed at all.

Since you didn't share the full plan output I can't offer specific advice on that, but you should see in the output somewhere at least one value change annotated with "(forces new resource)". If you make sure that all of the configured values match the old values then Terraform won't detect a change and thus won't attempt to replace the object.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
