### ISSUE TITLE
Interpolation for custom provider version

### ISSUE THREAD

**Issue by qi-liu67** [hashicorp/terraform#19510]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
variable "version" {
  type = "string"
  default = "0.0.0"
}

terraform {
  # Version of Terraform to include in the bundle. An exact version number
  # is required.
  version = "0.11.8"
}

# Define which provider plugins are to be included
providers {

  # Include a custom plugin to the bundle. Will search for the plugin in the
  # plugins directory, and package it with the bundle archive. Plugin must have
  # a name of the form: terraform-provider-*, and must be build with the operating
  # system and architecture that terraform enterprise is running, e.g. linux and amd64

  customplugin = ["${var.version}"]
}

```

### Expected Behavior

a bundle archive should be generated
### Actual Behavior

Failed to read config: providers.sf: Malformed constraint: ${var.version}

### Steps to Reproduce

I am following this tutorial to generate bundle file https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle#installing-a-bundle-in-on-premises-terraform-enterprise

**Comment by apparentlymart** [comment]
Hi @evelyn-qi-liu! Thanks for sharing this use-case.

The `terraform-bundle` tool was not intended to be used in this way; instead, it expects that you'll edit the configuration file each time you want to change versions.

This tool is intended to be replaced by full support for installing custom plugins from the Terraform Registry. If you are using Terraform Enterprise (which it sounds like you are, per the link you gave at the end there) then it will be possible to use its private registry for distribution of providers. The implementation work for this is in progress already with the team that works on Terraform Registry.

Since the bundle tool will be deprecated once that is possible, we don't have plans to make any further changes to it aside from bug fixes, since development time is instead being spent on the providers-in-registry functionality.

In the mean time, you could potentially implement a wrapper program that generates the configuration file from a template to insert the version you need, thus getting a similar effect. I understand that this is more complex then you wanted, but hopefully it's a reasonable stop-gap solution until provider distribution via the Terraform Enterprise private registry is available.

**Comment by qi-liu67** [comment]
Thanks!

**Comment by qi-liu67** [comment]
Thanks!
