### ISSUE TITLE
AWS CLI installation

### ISSUE THREAD

**Issue by Bhavithrask** [hashicorp/terraform#19550]
Hi, 
  I'm trying to install AWS CLI which is needed by lambda in my working environment. I have installed the packages but by default a file named "aws" is being installed in /usr/bin/

I was tring to copy file from /usr/bin to my local machine using provisioner but the provisioner scripts returns **timeout - last error: dial tcp :22: connect: connection refused** 

Is there any means of copying files from /usr/bin to any path by using terraform

**Comment by apparentlymart** [comment]
Hi @Bhavithrask,

This seems like a misconfiguration of your instance (not accepting SSH connections on port 22) rather than a Terraform-specific problem.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
