### ISSUE TITLE
Can't access encrypted attribute of block_device_mappings list/map

### ISSUE THREAD

**Issue by estein9825** [hashicorp/terraform#19574]
I need to confirm whether a particular AMI has encryption enabled.  My data/output calls to aws_ami are:

```
data "aws_ami" "target_ami" {
 
  filter {
    name   = "image-id"
    values = ["${var.ami_id}"]
  }
}

output "block device mappings" {
  value = "${data.aws_ami.target_ami.*.block_device_mappings}"
}
```
results in
```
[
    [
        map[virtual_name: device_name:/dev/sda1 ebs:map[volume_type:gp2 
encrypted:1 iops:0 snapshot_id:snap-XXXXXXXXX delete_on_termination:1 volume_size:20]
 no_device:]
    ]
]
```

However, for the life of me, I can't seem to grab that "encrypted" value.

I've tried accessing the `data.aws_ami.target_ami.*.block_device_mappings.#.ebs.encrypted` attribute like they suggested in the [documentation](https://www.terraform.io/docs/providers/aws/d/ami.html#block_device_mappings-ebs-encrypted) and neither 0 nor * work.  It keeps saying 

```
Resource 'data.aws_ami.target_ami' does not have attribute 
'block_device_mappings.0.ebs.encrypted' for variable 'data.aws_ami.target_ami.*.block_device_mappings.0.ebs.encrypted'
```

The purpose is to ensure that I only grab the appropriate AMI when I create an ec2 instance dynamically.

In otherwords, for 

```
resource "aws_instance" "ec2" {
  count                       = "${var.num_instances}"
  ami                         = "${var.ami_id}"
  associate_public_ip_address = "${var.associate_public_ip_address}"
  instance_type               = "${var.instance_type}"
```
I want to make sure var.ami_id is encrypted.  

I am currently using Terraform v0.11.10.

Hopefully someone knows a way.

**Comment by jbardin** [comment]
Hi @estein9825,

Sorry you're having an issue with this. The AWS provider defined the `block_device_mappings` as a set, which isn't of much use when you want to access data from that attribute.

While we don't have a good solution at the moment for indexing into a set, the next major release will allow you to iterate over the set to find the data you need. The syntax to generate a map of the set contents would look something like:

```
locals {
  block_device_mappings = {
    for bd in data.aws_ami.target_ami.block_device_mappings:
    bd.device_name => bd
  }
}
```

This would allow you to access the local `block_device_mappings` map by device name.

**Comment by apparentlymart** [comment]
Hi @estein9825,

James was suggesting to use a local value like he showed (once 0.12 is released) and then access that elsewhere to get to the encrypted flag:

```hcl
locals {
  block_device_mappings = {
    for bd in data.aws_ami.target_ami.block_device_mappings:
    bd.device_name => bd
  }
}

# (just for example)
output "example" {
  value = local.block_device_mappings["/dev/sda1"].encrypted
}
```

This isn't directly accessible because for some reason `block_device_mappings` is defined as a set rather than a list or map in this data source, and so there is no key by which to access these objects.

I don't think there's anything further that can be done in Terraform Core to improve the situation here, beyond the new feature James mentioned. Improving on this will require some changes to the AWS provider, such as changing `block_device_mappings` to be a map keyed by device name rather than a set, and also correcting the currently-incorrect documentation.

Since the required changes must happen in the AWS provider repository, I'm going to have our bot migrate this issue over there where the AWS provider maintainers can see it and decide what is the best path to take here to make these objects directly accessible.
