### ISSUE TITLE
Terraform Binary Builds archive filenames have changed since 0.12.0-alpha2

### ISSUE THREAD

**Issue by djgoku** [hashicorp/terraform#19588]
Since 0.12.0-alpha2 all binary archives for downloading have an extra prefixed `terraform_0.12.0-alpha#`.

Download for 0.12.0-alpha2 is 
https://releases.hashicorp.com/terraform/0.12.0-alpha2/terraform_0.12.0-alpha2_darwin_amd64.zip vs 
https://releases.hashicorp.com/terraform/0.12.0-alpha4/terraform_0.12.0-alpha4_terraform_0.12.0-alpha4_darwin_amd64.zip

**Comment by apparentlymart** [comment]
Hi @djgoku,

Thanks for pointing this out. This was a result of the custom process used to build the alphas and is known. The normal filename style will be restored for v0.12.0 final and subsequent builds because they will be built and released in the standard way, using our automated release process.
