### ISSUE TITLE
terraform refresh -target doesn't refresh templates in state

### ISSUE THREAD

**Issue by JustinGrote** [hashicorp/terraform#19601]
### Terraform Version

v0.11.9
provider.template v1.0.0
```
...
```

### Terraform Configuration Files

```hcl
data "template_file" "example" {
  template = "this is a test5"
}
```

### Expected Behavior
updating a template followed by terraform refresh -target template_file.example should show in the state as the new state and "Refreshing state..." for the resources should show.

### Actual Behavior
No Output. 

### Steps to Reproduce
Edit template file template and update "template" attribute to something else
terraform refresh -target="template_file.example"

### Workarounds
Choosing a resource that is dependent on a template works correctly, so a dummy resource can be used to refresh a template without having to refresh the entire state.

**Comment by mildwonkey** [comment]
Hi @JustinGrote - 

I'm sorry you've run across this behavior. I found a [workaround](https://stackoverflow.com/questions/53540407/updating-a-count-in-a-template-file-is-not-affecting-the-output) in a similar issue, #18724 . 

The workaround is to use `resource "template_file"`  instead of `data "template_file"`. Without seeing the rest of your configuration, I can't promise that this will work, but it's worth trying.

**Comment by apparentlymart** [comment]
Hi @JustinGrote,

The resource address syntax for data resources includes the `data.` prefix, so you need to write this:

```
terraform refresh -target=data.template_file.example
```

**Comment by jbardin** [comment]
This appears to be resolved, and the template provider is no longer maintained, so closing this out.
