### ISSUE TITLE
Out-of-order representation of assets in configs.File/configs.Module

### ISSUE THREAD

**Issue by metmajer** [hashicorp/terraform#19603]
Hi, and thank you for considering my request.

I am the maintainer of https://github.com/segmentio/terraform-docs,  currently working on [integrating Terraform 0.12's rich value types](https://github.com/segmentio/terraform-docs/issues/62) to be prepared for prime time.

Since the integration of HCL2, `Locals`, `Outputs`, and `Variables` are stored in maps in Terraform's `configs.File` and `configs.Module` (see https://github.com/hashicorp/terraform/blob/master/configs/module.go). Because Golang's map iteration order is random, this causes some pain when there are established use-cases where order of elements needs to be preserved.

##### Why useful?

We have users using `terraform-docs` and `pre-commit` to automatically populate a Jenkinsfile's parameters from a Terraform module's variables, which are ultimately displayed to the end-user in a web form when the pipeline gets triggered in Jenkins' web UI. Here, preserving the order of variables preserves context and increases usability.

##### How to reproduce?

```
import (
    terraform_configs "github.com/hashicorp/terraform/configs"
)

parser := terraform_configs.NewParser(nil)
if !parser.IsConfigDir(path) {
    return nil, fmt.Errorf("Unable to find a single Terraform configuration file at %s", path)
}

module, diags := parser.LoadConfigDir(path)
if diags.HasErrors() {
    return nil, errors.New(diags.Error())
}

for _, item := range module.Variables {
    fmt.Printf("Name: %v\n", item.Name)
}
```

As a suggestion, have you considered storing references to elements in lists and maps to have an order-preserving data structure for those in need?

Thank you! Thoughts?

**Comment by apparentlymart** [comment]
Hi @metmajer!

I can see how what you are doing would benefit from the items being in order. Terraform itself does not generally consider top-level declarations to have any order since they can be arbitrarily spread over multiple files, but I assume that this tool you are writing is intended for use in an environment where it is conventional to keep all of the variables together in a particular file in a reasonable order.

The `configs` package (as with most packages in this repository) are not intended to be used as library dependencies, since Terraform is an application rather than a library. This package is designed to meet the needs of Terraform itself, not any external callers.

For now, I think the best path would be to use the HCL2 library directly to get what you need, since that'll retain the ordering of nested blocks.

**Comment by metmajer** [comment]
Hey, @apparentlymart! Thanks for making me aware that `configs` is not the right way to solve this problem and will look into HCL2 instead.
