### ISSUE TITLE
Terraform compatibility issue currently local is on 11.7 but state is reporting at 11.10

### ISSUE THREAD

**Issue by venkaa6** [hashicorp/terraform#19600]
This is not a blocker but trying to run init and seem to be getting
```
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.11.10'
```
Everything ran fine before I ran docker pull on a repo and installed airflow using pip. any way to point it back to 11.7 version?

thanks

### Terraform Version

```
Terraform v0.11.7

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html

...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by jbardin** [comment]
Hi @venkaa6,

In general you should revert your state using a recent backup. It is possible to modify the state file and change the version manually, but you do so at your own risk, since there may have been upgrades to the state since it was last saved.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
