### ISSUE TITLE
Implement error recovery mechanism for http backend

### ISSUE THREAD

**Issue by jbolla** [hashicorp/terraform#19619]
### Current Terraform Version

```
Terraform v0.11.10
```

### Use-cases
I want to use the http backend to persist state. Http backends can sometimes fail (500, timeout, etc) in a transient manner such that subsequent requests succeed.

### Proposal
Support a retry / backoff policy for the http reqeusts. I notice that hashicorp has implemented a https://github.com/hashicorp/go-retryablehttp wrapper around the go http library that the http backend is currently using. Perhaps that could be used.

**Comment by apparentlymart** [comment]
Hi @jbolla! Thanks for this feature request.

Supporting retries in the backend does seem like a good improvement. Since backend writes are idempotent, I expect we could enable a reasonable amount of retrying by default (for a few seconds, so Terraform doesn't appear to hang if the backend is down) and then allow that default to be increased/decreased via configuration if desired.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.
