### ISSUE TITLE
Failed  to use Terraform's standard CLI tools to execute runs in TFE

### ISSUE THREAD

**Issue by Enjolras67** [hashicorp/terraform#19645]
### Terraform Version

```
Terraform v0.11.8
+ provider.customplugin vX.Y
```

### Terraform Configuration Files

```hcl
terraform {
    backend "remote" {
    hostname = "hostname.XXXX.XXX"
    organization = "XXXX"

    workspaces {
      name = "XXXX"
    }
  }
}

provider customplugin {
}
```

### Debug Output

https://gist.github.com/e76ad50bab942c9bfc1b16322d5b468f.git
### Crash Output

```
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.
To view this plan in a browser, visit:
https://hostname.XXXX.XXX/app/orgname/workspace/runs/run-JE178FDzphGCSESY

Waiting for the plan to start...

Terraform v0.11.8


Setup failed: Failed to copy tfVars file: Failed copying file "/tmp/terraform-build-worker198096323/terraform.tfvars" to "0d19d9ee-6704-bd55-b13a-77b297dee96d:/terraform/sf/terraform.tfvars": exit status 1
Output:
Error: No such container:path: 0d19d9ee-6704-bd55-b13a-77b297dee96d:/terraform/sf
```

### Expected Behavior

We use bundle tool to bundle our custom plugin and terraform together on PTFE. We can run it successfully through UI/VCS driven Run Workflow.
I expect it running through CLI-driven Run Workflow successfully. 

### Actual Behavior

It failed through CLI-driven Run Workflow.
### Steps to Reproduce

terraform init
terraform plan
### Additional Context

Refer to the link https://www.terraform.io/docs/enterprise/run/cli.html
and https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle#installing-a-bundle-in-on-premises-terraform-enterprise

**Comment by apparentlymart** [comment]
Hi @Enjolras67! Sorry for this weird error, and thanks for reporting it.

This seems to be reporting a problem inside your Private Terraform Enterprise issue rather than within Terraform CLI itself: the "container" it is referring to is part of the execution worker inside Terraform Enterprise.

To understand what happened here, please contact Terraform Enterprise support and include the same great detailed information from this issue in your support ticket. Thanks!
