### ISSUE TITLE
Terrafrom code in gitbub

### ISSUE THREAD

**Issue by varmaraju** [hashicorp/terraform#19669]
Hi Sir/Madam,

Using terraform, I am able to create the infrastructure successfully. 
We are planning to setup my terraform  in Github, As  soon as I commit the terraform  code, using Jenkins fork feature, my terraform  script should run. 

My terraform code always should be in github only( all .tf files).
May I know how can we do this, As per my knowledge we can create only terraform  state file in github.

May I know how can I do this?. PLease let me know any suggestions.

**Comment by jbardin** [comment]
Hi @varmaraju,

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
