### ISSUE TITLE
Add force_path_style to S3 backend documentation

### ISSUE THREAD

**Issue by keelson** [hashicorp/terraform#19672]
Just learned from https://github.com/hashicorp/terraform/issues/13194 that `force_path_style` was added to the S3 backend. 

Please add this to the documentation, too :)
https://www.terraform.io/docs/backends/types/s3.html

**Comment by bflad** [comment]
Hi @keelson 👋 Thanks for reporting this and sorry for the trouble here.

If you are interested in contributing, the documentation page lives in this repository here: https://github.com/hashicorp/terraform/blob/master/website/docs/backends/types/s3.html.md otherwise if we don't hear back, someone else can submit the change. Thanks again for bringing this to our attention!

**Comment by keelson** [comment]
@bflad how about https://github.com/hashicorp/terraform/pull/19689 ?
