### ISSUE TITLE
File provisioner crashes when there is too many files to copy

### ISSUE THREAD

**Issue by Platou** [hashicorp/terraform#19677]
### Terraform Version

```
Terraform v0.11.10
```

### Terraform Configuration Files

```hcl
resource "null_resource" "copy" {
  triggers {
    always = "${timestamp()}"
  }

  connection {
    host        = "${var.ip_address}"
    type        = "ssh"
    user        = "user"
    private_key = "${var.ssh_private_key}"
  }

  provisioner "file" {
    source      = "."
    destination = "/home/user/files"
  }
}
```
### Expected Behavior

All the files should be copied successfully.

```
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] SCP: starting directory upload: files
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] Beginning file upload...
[...]
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] Beginning file upload...
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] SCP session complete, closing stdin pipe.
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] Waiting for SSH session to complete.
Apply complete!
```
### Actual Behavior

When there is a lot of files to be copied (>=2000) the provisioner just crashes before the end of the process.

```
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] SCP: starting directory upload: files
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] Beginning file upload...
[...]
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] Beginning file upload...
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] SCP session complete, closing stdin pipe.
****[There is many files remaining to be uploaded at this point]
[DEBUG] plugin.terraform: file-provisioner (internal) [DEBUG] Waiting for SSH session to complete.
[DEBUG] plugin.terraform: file-provisioner (internal) [ERROR] Process exited with status 1
[ERROR] root.hive: eval: *terraform.EvalApplyProvisioners, err: Upload failed: Process exited with status 1
[ERROR] root.hive: eval: *terraform.EvalSequence, err: Upload failed: Process exited with status 1
[TRACE] [walkApply] Exiting eval tree: null_resource.copy
[TRACE] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
[TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
[TRACE] dag/walk: upstream errored, not walking "provider.null (close)"
[TRACE] dag/walk: upstream errored, not walking "provisioner.file (close)"
[TRACE] dag/walk: upstream errored, not walking "root"
[DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error applying plan:

1 error(s) occurred:

* null_resource.copy: Upload failed: Process exited with status 1
```
### Steps to Reproduce

(with around 2000 files)
1. `terraform apply`

**Comment by ragarcia26** [comment]
@apparentlymart are there any known resource limits for terraform? Also is there a better place I can discuss this?

**Comment by apparentlymart** [comment]
Hi @Platou, @ragarcia26,

There are no intentional limits on how many files or what size of files Terraform can upload using this provisioner.

When Terraform uploads files over SSH, it launches the `scp` program on the remote host and then uses the SCP protocol to communicate with it. The error returned in the original message here indicates that the _remote_ `scp` process exited with status 1, so it's hard to say what would've caused that: Terraform is just reporting what the remote system sent.

From a quick look at [the relevant code](https://github.com/hashicorp/terraform/blob/a2ee9fc8f9a8517a421e8a4c0f990b3fe63d36ab/communicator/ssh/communicator.go#L524-L546) I see that Terraform would display any error messages printed by the `scp` process on stderr if it had printed any, so it seems like for some reason the `scp` program exited unsuccessfully but without producing any error output.

Since the problem seems to be reported by the remote system, and we know nothing about the remote system here, I can't really say what might be causing this failure. It could be that `scp` is not installed correctly on the server, or it could be that the system ran out of disk space, or that Terraform's implementation of the scp protocol is not quite what the remote system is expecting, or many other various problems. :confounded: 

I will say though that most uses of the `file` provisioner are for uploading single files constructed by Terraform during the apply process, rather than large directory trees. The ideal way to use Terraform with compute instances is to use a separate build process to construct a custom disk image containing most of the required files, and then use Terraform just to make any final customizations required to provide any system-specific configuration that isn't known until Terraform does other work.

Even then, it's better to provide such customizations using a mechanism like AWS EC2 "user data", where the necessary files are already present and Terraform just passes some configuration to the machines as they boot, but the provisioner feature is there in recognition of the fact that sometimes a ready-to-run system image isn't practical, and so some final adjustments are needed after the instance boots.

With that said then, while there are not any hard technical limitations imposed by Terraform, interacting with remote systems is unpredictable and so there's only so much we can do to normalize over what are arbitrary remote systems that could be running any software configuration. Provisioners are sometimes unavoidable, but if there's some other reasonable path you can take I think you' could get much more predictable (and probably more efficient) results by avoiding use of provisioners.

**Comment by ragarcia26** [comment]
Actually my case wasn't specifically the file provisioner. We are seeing terraform crashes more frequently as our build size increases. As of now our  main pipeline has past 4k+ resources (2.5k infoblox, 1.5k null_resources) and crashes on plan. I was trying to see if there was any known issues of terraform crashing on plans for such a high volume of resources. Right now i'm working with the devops guy to get me a log, which is too vast for the pipeline right now. Are there any recommendations for TF_LOG severity in this aspect? as 4k+ resources has a massive log size

**Comment by apparentlymart** [comment]
If your concern is not specifically about the file provisioner, please open a new issue for it. Unfortunately I can't really suggest any way to work around log size... if you have a complicated configuration then the logs will necessarily be large to capture all of the information.

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
