### ISSUE TITLE
Aliased git module sources are not linked but cloned

### ISSUE THREAD

**Issue by c33s** [hashicorp/terraform#19681]
### Terraform Version
```
terraform -v
Terraform v0.11.10
+ provider.external v1.0.0
+ provider.hcloud v1.6.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.uptimerobot v1.0.0
```

### Terraform Configuration Files
```hcl
module "hcloud_server1" {
  fqdn = "foo.example.com"
  source = "git::ssh://git@gitlab.com/myuser/terraform/modules/hcloud-server.git?ref=master"
}
module "hcloud_server2" {
  fqdn = "bar.example.com"
  source = "git::ssh://git@gitlab.com/myuser/terraform/modules/hcloud-server.git?ref=master"
}
module "hcloud_server3" {
  fqdn = "foobar.example.com"
  source = "git::ssh://git@gitlab.com/myuser/terraform/modules/hcloud-server.git?ref=master"
}
```

### Expected Behavior
`terraform init` should clone the repo one time and use the single repo for all aliases of the module or at least same 
as for the local modules only create one hash link for each alias to one clone of the repo.

### Actual Behavior
for each module alias a speparate directory is created and git clone of the same repo is called.

### Steps to Reproduce
1. add the code above to your main.tf file (change the repo url to a valid url of a module you have access too)
2. run `terraform init`
3. look into `.terraform/modules` (for each alias you will find one full clone of the repo)

this is a waste of space and very imperformant. if you create your server with module aliases, you have for example 30 clones of the same repo in your `.terraform/modules` path. additional cloning so many repos takes time.
if you use local modules `source = "./modules/hcloud-server"` this does not happen because the hashes link from `.terraform/modules/<hash_for_the_alias>` to `./modules/hcloud-server`

**Comment by apparentlymart** [comment]
Hi @c33s,

It looks like you're describing the same thing as discussed in #11435, which has already been fixed in the master branch ready for inclusion in the forthcoming v0.12.0 release. You can find a comment from me on that other issue with details of how this now behaves.

In particular, you'll note that for the first pass we intentionally addressed only the problem of downloading multiple times and retained the multiple copies because this avoids the risk of breaking anyone who was assuming that each module has its own separate installation directory. We don't plan to change that in the short term until we get more experience with the new behavior, but we do plan to look into optimizations for local storage in a later release too, most likely as part of some other general changes to how Terraform manages dependencies, still to be fully designed.

Since the change for this is already merged, I'm going to close this issue. Thanks for reporting this!
