### ISSUE TITLE
remote-exec cares about the last exit code only

### ISSUE THREAD

**Issue by frafra** [hashicorp/terraform#19734]
### Terraform Version

```
$ terraform -v
Terraform v0.11.11
+ provider.hcloud v1.6.0
```

### Terraform Configuration Files

```hcl
  provisioner "remote-exec" {
    inline = [
      , "sh -c 'exit 1'"
      , ":"
    ]
  }
```

### Expected Behavior

If any command fail, the resource should be mark as tainted.

### Actual Behavior

Only the last exit code is considered.

**Comment by che** [comment]
Up! :-(

**Comment by WraithCadmus** [comment]
Just hit this today, my first thought would just be `&&` my commands together, but I agree that any command exiting non-zero should be a taint.

**Comment by seemethere** [comment]
Yeah this is something that is on my radar as well, would any previous contributors know where to start on this one?

Would like to help if I could.

**Comment by teamterraform** [comment]
Hi @frafra,

The `inline` argument for for `remote_exec` collects the commands and executes them as a script using `/bin/sh`. The default behavior for POSIX shell scripts is that they are run in their entirety and only the final exit code is reported.

You can call `set -e` for the shell at the start of the commands if you choose, though in more complex situations it may often be better to format the logic you want in a standalone script rather than write them inline and rely on the default system `/bin/sh`.

While adding the `-e` option to the shell would enable the ability to exit early by default, it would change the default for all users who may expect and rely on the current behavior.
