### ISSUE TITLE
v0.12.0-alpha4 requires a slash in the path of the module source

### ISSUE THREAD

**Issue by prehor** [hashicorp/terraform#19745]
### Terraform Version
```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Terraform Configuration Files
```hcl
# main.tf
module "test" {
  source = "test"
}
```
```hcl
# test/test.tf
provider "random" {}
```

### Expected Behavior
Terraform v0.11.11 initialize without error. 

### Actual Behavior
Terraform v0.12.0-alpha4 initialize with error:
```
$ terraform init
Initializing modules...
Downloading test for test...

Error: Failed to download module

  on main.tf line 2, in module "test":
   2:   source = "test"

Error attempting to download module source code from "test": error downloading
'file:///.terraform/modules/test/test': source path error: stat
/.terraform/modules/test/test: no such file or directory


Error: Failed to download module

  on main.tf line 2, in module "test":
   2:   source = "test"

Error attempting to download module source code from "test": error downloading
'file:///.terraform/modules/test/test': source path error: stat
/.terraform/modules/test/test: no such file or directory
```

When I change the path in `main.tf ` to `source = "./test"`, Terraform v0.12.0-alpha4 initializes without error:
```
$ terraform init
Initializing modules...
- test in test

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.random: version = "~> 2.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

The same error occurs if the module uses the parent directory as the source path with `source = ".."`.

**Comment by apparentlymart** [comment]
Hi @prehor! Thanks for reporting this.

We've actually been _attempting_ to require relative paths to begin with `./` or `../` (as indicated in [the module source docs](https://www.terraform.io/docs/modules/sources.html#local-paths) since 0.11 when we introduced the module registry path syntax which is like `namespace/module/provider`. However, some legacy forms managed to continue working due to some holes in the parsing logic that allowed the underlying library `go-getter` to handle it.

We've intentionally firmed that up for 0.12 so that the behavior is more predictable and consistent, but it does look like there are still some bugs there where it's _trying_ to interpret it as a relative path via `go-getter`, so we'll need to plug those up. This is also a good reminder that the 0.12 upgrade tool ought to detect this old usage and fix it.

The work represented by this issue, then, is:
* Make sure the module installer detects anything that looks like it might be a relative path (essentially, any registry module source that doesn't have enough segments to be valid) and produce a specific error for that situation, directly suggesting to add `./` to the source string.
* Add a rule to the upgrade tool to use similar logic to detect what appears to be a use of a relative path and add `./` to the front of it so that it's explicitly a local path as per the documentation.

**Comment by mitchellh** [comment]
Comment from the 0.12 test at CfgMgmtCamp: another user hit this same thing and was equally confused. Improved error messages would be very helpful here.
