### ISSUE TITLE
terraform: openstack issue: openstack_compute_instance_v2.terraform: Failed to parse key file "-----BEGIN RSA PRIVATE KEY-

### ISSUE THREAD

**Issue by mauryarr** [hashicorp/terraform#19764]
This is what I'm using to connect to my instance.  

connection {
      type = "ssh"
      user = "cloud-user"
      private_key = "${file("/Users/mrangineni/pf99/admin.pem")}"
      timeout = "2m"
      agent = false
  }

**Comment by apparentlymart** [comment]
I'm not sure what the original problem was here, but @k4ch0 in your case the problem is that `private_key` expect to be given the _contents_ of your key file, not the filename of it. So you can rewrite it as:

```hcl
private_key = "${file(var.ssh_key_public)}"
```

...assuming that `var.ssh_key_public` is `~/.ssh/id_rsa.pub`, as it appears from this message. But note also that `private_key` must be a _private_ key, not a _public key_, so you may also want to change that value to `~/.ssh/id_rsa` if your private key is in the conventional location.
