### ISSUE TITLE
Terraform crashes when trying to create dynamodb

### ISSUE THREAD

**Issue by joshuamkite** [hashicorp/terraform#19902]
### Terraform Version

```
0.11.11
```
Behaves the same with Terraform 0.11.8

### Terraform Configuration Files

```
resource "aws_dynamodb_table" "rds_proxy" {
  name         = "rds_proxy_ssh_keys_${var.environment}_${var.aws_account}_${var.aws_region}"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "UserPublicSshKey"

  attribute {
    name = "UserPublicSshKey"
    type = "S"
  }

  ttl {
    attribute_name = "TimeToExist"
    enabled        = true
  }

  timeouts {
    create = 5
    update = 5
    delete = 5
  }

  tags = "${var.tags}"
}

```

### Debug Output

https://gist.github.com/joshuamkite/40fa7c1988968941b89548314ec8c9b4

### Crash Output

https://gist.github.com/joshuamkite/7004c0915296ef251d265fd922bf9137

### Expected Behavior

Terraform should have planned the creation of a dynamodb resource or given a usable error message

### Actual Behavior

Terraform crashed

### Steps to Reproduce

Try to create a dynamodb resource with the above. Breaks

### Additional Context

This was originally part of a bigger terraform plan running with terraform version 0.11.8 via Drone CI/CD server. That plan was fine until I added the section reproduced above. When I created a new plan supporting **only** this section I got the same result./ The referenced result and logs are with terraform version 0.11.11

### References

None I am aware of

**Comment by apparentlymart** [comment]
Hi @joshuamkite! Sorry for the crash, and thanks for reporting it.

Based on the error message, my guess is that the provider SDK is crashing because it's expecting the timeout values to be strings (in quotes) rather than numbers. If I'm right then putting those values in quotes may help.

It may also be necessary to add a unit suffix, since the timeout values are expected to be duration strings. For more information, see [the timeouts documentation](https://www.terraform.io/docs/configuration/resources.html#timeouts).

Of course it is a bug that this was a crash rather than a normal validation error. I think this is already fixed in master ready for the forthcoming 0.12.0 release because this is now validated in Terraform Core as well as within the SDK, and so Terraform Core should be protecting the provider SDK code from this invalid input. I've added this to our v0.12.0 milestone to remind us to verify that it is indeed fixed.

**Comment by joshuamkite** [comment]
Thanks @apparentlymart Your surmise is correct- both quoting and units are required, e.g. 
```
  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }
```
works.

If you would like, then I would be more than happy to submit a pull request on the documentation for this, summarising your successful advice here.

**Comment by jbardin** [comment]
We do validate it now in 0.12, but there might be room for improvement in the errors.

The numeric value is coerced into a string internally, and then we get the error `missing unit in duration`. However if a user attempts to fix the issue by directly adding the unit to the bare number, i.e. `create = 5m`, it then results in a rather confusing parsing error: `Missing newline after argument`.

**Comment by apparentlymart** [comment]
I have forked off the error message improvements into #19999 so we can keep this one just about the crash, which is now fixed.
