### ISSUE TITLE
resource names starting with numbers cause error

### ISSUE THREAD

**Issue by dimitriosoodle** [hashicorp/terraform#19919]
### Terraform Version

```
terraform -v
Terraform v0.12.0
+ provider.aws v1.51.0


...
```
compiled on linux mint 19 with parser from https://github.com/hashicorp/terraform/blob/master/vendor/github.com/hashicorp/hcl/hcl/parser/parser.go golang 1.11.4 from snap

### Terraform Configuration Files

```
resource "aws_kms_key" "555555aac-5aa5-55a5-55a5-aa5555aa555a" {
    description             = "Default master key that protects my EBS volumes when no other key is defined"
    key_usage               = "ENCRYPT_DECRYPT"
    is_enabled              = true
    enable_key_rotation     = true

...
```

### Expected Behavior

resource names starting with number should be accepted

### Actual Behavior

```
Error: Invalid resource name

  on kmsk.tf line 1, in resource "aws_kms_key" "555555aac-5aa5-55a5-55a5-aa5555aa555a":
   1: resource "aws_kms_key" "555555aac-5aa5-55a5-55a5-aa5555aa555a" {

A name must start with a letter and may contain only letters, digits,
underscores, and dashes.
```

### Steps to Reproduce

create configuration with terraforming from an environment that includes encrypted EBS
run terraform validate

**Comment by apparentlymart** [comment]
Hi @dimitriosoodle! Thanks for reporting this.

This new restriction was intentional because otherwise the resource name would not be usable in HCL expressions due to not being a valid identifier. It's not a valid identifier because it would be ambiguous with number values in expressions.

This is one of the small number of situations where we had to accept an incompatibility in order to move the language forward, and so unfortunately it will be required to rename this resource before upgrading to 0.12. The configuration upgrade tool will flag this as something requiring manual intervention, since you'll need to decide what new name to use and to run `terraform state mv` to apply the rename also in the state.

This incompatibility will also be discussed specifically in the final upgrade guide which we'll write during the beta/rc phase.

I'm going to use this issue to represent the task of documenting the incompatibility in the upgrade guide and making sure it does something reasonable in the upgrade tool. (The upgrade tool itself is not fully functional in the alpha releases but will be more complete in the forthcoming beta1 release.)

**Comment by dimitriosoodle** [comment]
Thank you for your anwer, although not the one I was hoping for. What would be an acceptable workaround - I tried inserting an _ in the beginning of the resource name and it seems to pass validation.

**Comment by apparentlymart** [comment]
Adding any non-digit character to the start of the resource name should be sufficient; the message says "a letter" for simplicity's sake, since that's usually what human-readable names begin with, but it should accept an underscore too.

I've not seen uuids as resource names before so I'm not sure what exactly your intent is with that but if you're generating these resource configurations programmatically rather than having humans write them then I suppose adding an underscore as a prefix is a systematic change you could make so that _all_ generated names would work.

Note that you'll need to use `terraform state mv` to rename any existing resources in state too, or Terraform will treat it as destroying the old resource and creating the new one. The upgrade tool I mentioned will give more detailed guidance on that, but for example to add an underscore as you proposed:

```
terraform state mv aws_kms_key.555555aac-5aa5-55a5-55a5-aa5555aa555a aws_kms_key._555555aac-5aa5-55a5-55a5-aa5555aa555a
```

**Comment by kojoa** [comment]
> 
> Note that you'll need to use `terraform state mv` to rename any existing resources in state too, or Terraform will treat it as destroying the old resource and creating the new one. The upgrade tool I mentioned will give more detailed guidance on that, but for example to add an underscore as you proposed:
> 
> ```
> terraform state mv aws_kms_key.555555aac-5aa5-55a5-55a5-aa5555aa555a aws_kms_key._555555aac-5aa5-55a5-55a5-aa5555aa555a
> ```

It's worth noticing that `terraform state mv` will also fail on terraform 0.12 when resource name starts with a digit character. Had to temporarily install terraform 0.11 to be able to execute the `mv` command.
