### ISSUE TITLE
Unresolved dependency in module

### ISSUE THREAD

**Issue by ccakes** [hashicorp/terraform#19938]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.52.0
```

### Terraform Configuration Files

```hcl
# ./module_a/main.tf
variable role {}

data "aws_iam_role" "role" {
  name = "${var.role}"
}

# ./iam.tf
resource "aws_iam_role" "test" {
  name               = "test-role"
  path               = "/system/"
  assume_role_policy = "${var.assume-role-policy}"
}

module "a" {
  source = "./module_a"
  role   = "${aws_iam_role.test.name}"
}
```

### Output
```
Error: Error refreshing state: 1 error(s) occurred:

* module.module_a.data.aws_iam_role.role: 1 error(s) occurred:

* module.module_a.data.aws_iam_role.role: data.aws_iam_role.role: Error reading IAM Role test-role: NoSuchEntity: The role with name test-role cannot be found.
	status code: 404, request id: fa9677a2-1335-11e9-8ecb-4d4223e2ef9d
```

### Expected Behavior
Given that `module_a` has a dependency on the IAM role, I'd have expected it to create the role before trying to load `module.module_a.data.aws_iam_role.role`

### Actual Behavior
See output

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
It's possible I've misunderstood something. I understand why Terraform would try to load all data segments first, however in this case it causes issues. There may be a config workaround but after a fair bit of searching I wasn't able to find anything.

**Comment by bennycornelissen** [comment]
@bflad Since there is no actual dependency on a computed value of `iam_role.test`, would it be possible that Terraform tries create things in parallel? The data source doesn't care about `iam_role.test` since it just talks to AWS, and `module.a` only cares about `iam_role.test.name` which is given.

**Comment by jbardin** [comment]
@bennycornelissen, the `data.aws_iam_role.role` within the module depends on the actual resource (well, I have to assume so, but we don't have the config here), so it's not going to run until the resource completes. However, because some things are only eventually consistent, the resource can be created while the datasource may not yet be able to locate it. 

@ccakes, normally one would pass in whatever data is required directly from a resource being created, rather than an identifier for another data source to lookup. While using the intermediary data source does work in most cases, it is much more difficult with eventually consistent resources. 

(As a bonus, in 0.12 it will be possible to structure the module to accept a complete `aws_iam_role` type rather than individual values, which can make this type configuration much easier to manage)

**Comment by bennycornelissen** [comment]
@jbardin so if I understand correctly, a resource 'A" depending on a _non-computed_ attribute of  resource 'B' means it becomes fully dependant on resource 'B' even if, theoretically, it doesn't need to be?

**Comment by jbardin** [comment]
@bennycornelissen, yes that's correct. While we may know the value from the configuration alone (which is often visible in the plan output), when the user references a resource's attributes it creates a dependency graph edge, ensuring that the referenced resources is created in full before any of it's attributes are used. It's also not possible to always reference a _computed_ attribute for a resource, because the dependent resource often does not have an appropriate attribute in which to place whatever is being computed.

**Comment by bennycornelissen** [comment]
@jbardin it makes sense now. Thanks for explaining 😃

**Comment by ccakes** [comment]
Apologies all, I haven't had too much time to dig into this further. Will close for now to keep this off the list
