### ISSUE TITLE
Issues with variables not passing via command line

### ISSUE THREAD

**Issue by rmuller95** [hashicorp/terraform#19965]
Got a weird issue that I have just come across on command line variable passing.. 

Terraform version: v0.11.11 (Haven't tested previous versions)
OS's tested: Mac 

Terraform file
```
variable "test" {
  default = "hi"
}

output "testing" {
    value = "${var.test}"
}
```

Test output:
```
$ terraform --version
Terraform v0.11.11


$ terraform apply -var "test=hello"

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

testing = hello

$ terraform apply -var "test=7e"

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

testing =
```

For some reason the "7e" input via command line input will not work. This does work fine if it is in a `-var-file` being passed in but not on the command line.

**Comment by apparentlymart** [comment]
Hi @rmuller95! Sorry for this strange behavior.

It seems like you've discovered the same bug discussed in #15626. The issue here is that "7e" is matching a heuristic that tries to detect if this is a valid number because "e" is the exponentiation syntax for numbers, but obviously here you were intending it to be taken as a literal string.

That bug has been fixed in master ready for the forthcoming v0.12.0 release. Until then, unfortunately the only workarounds are either to pass the value via a file using `-var-file` or to include a prefix/suffix on the string to make it clearly _not_ a number and then trim it off with `substr` in the configuration. I understand that neither workaround is ideal; this will work as expected once v0.12.0 final is released.
