### ISSUE TITLE
0.12.0-alpha4 cannot run under alpine, dynamically linked?

### ISSUE THREAD

**Issue by sjwl** [hashicorp/terraform#19969]
I cannot run the prebuilt binary of terraform downloaded from
https://releases.hashicorp.com/terraform/0.12.0-alpha4/terraform_0.12.0-alpha4_terraform_0.12.0-alpha4_linux_amd64.zip
within an alpine container

If instead, I compile from source within the alpine container, the executable runs successfully.

### Terraform Version
0.12.0-alpha4

```
/usr/local/bin # ls -l terraform
-rwxr-xr-x    1 root     root     100214848 Jan 10 23:10 terraform
/usr/local/bin # ./terraform version
/bin/sh: ./terraform: not found
/usr/local/bin #
```

### References

- #6714

**Comment by apparentlymart** [comment]
Hi @sjwl! Sorry for this weird inconsistency.

The alpha builds were constructed in an unusual way so that we could release them with bundled providers, and I guess our unusual process here didn't set all the same build flags our normal build process would. From beta1 onwards we'll be releasing in the usual way, so things will return to normal.

We're not planning to make any more alpha releases before beta1, so I don't think there's really any specific action to be taken here in the code -- the standard build process is in a different repository and unchanged from the latest 0.11 release -- so I'm going to close this out, but I'm sorry we didn't catch this for the custom build process.
