### ISSUE TITLE
How to migrate existing ec2 instance flavour (t2/m4...etc) to M5 flavour with the old volume with out loosing the data

### ISSUE THREAD

**Issue by pradeepaasuri** [hashicorp/terraform#19972]
### Current Terraform Version

```
...
```

**Comment by abiydv** [comment]
You should ask this on stackoverflow. This is not the right place for seeking guidance.

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
