### ISSUE TITLE
illegal character for provider

### ISSUE THREAD

**Issue by christopherlynnsmith** [hashicorp/terraform#19983]
### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
+ provider.google v1.20.0
```

### Terraform Configuration Files

```hcl
provider "google" {
credentials = "${file("account.json")}"
project = “corded-tensor-164401”
region = “us-central1”
version = "~> 1.20"
}
```

**Comment by christopherlynnsmith** [comment]
I am  using ubuntu 18.04 LTS and visual code.

**Comment by christopherlynnsmith** [comment]
This has been an error for version .10 and .11 .  I tried .12 alpha same error

**Comment by apparentlymart** [comment]
Hi @christopherlynnsmith,

It looks like your configuration contains "curly quotes": `“` and `”`. Terraform doesn't accept these, and instead requires ASCII quotes: `"`.

It might be particularly visible on my machine due to different font choices, so in case it's not so clear to you: the curly quotes are in the `project` and `region` arguments. The `credentials` and `version` arguments are using ASCII quotes as expected.

**Comment by christopherlynnsmith** [comment]
Exactly, apparentlymart, you saved the day.

Using visualcode with the terraform plugin it still did not highlight well enough for me that this was the problem.

I would clearly have the system auto change all types of "quotes" to ascii quotes.

Thanks
