### ISSUE TITLE
FR: support direct output to tfvars file format

### ISSUE THREAD

**Issue by SPhu** [hashicorp/terraform#19996]
Terraform v0.11.11

### Use-Case
My use case is to make it easier to run multiple terraform projects within a team that have different roles.  I would like to use shared outputs but not shared tfstate.

**Example:**

I run terraform for all our infrastructure and the devs can't access it.
I want to allow them terraform access for their apps and to be able to extend new infrastructure.
Me - VPC, subnets, security, etc..
DEVs - ecs fargate instances, servers, etc...

So instead of giving the ability to change the VPC they just need the VPC and subnet ID.  This is a pain in the butt to manage across multiple projects and I would like to give a single file they can pull into their projects.

### Attempted Solutions
1) I am able to run terraform output and get something close to what I need but then I have to manually adjust each line for quotes

terraform output: `vpc-production = vpc-123456`
tfvars requires:  `vpc-production = "vpc-123456"`

2) There may be a way to shell script this using a couple of sed commands but that does seem very elegant.

3) I have looked at modules but that doesn't appear to give the independence and ease of sharing I am looking .

### Proposal

I would like one of 2 options:
A) I would like as default or a command line option (`terraform output --fmt-tfvars`) to generate an output that can be used directly in a tfvars file.  This would allow me to safely share areas of responsibility in our infrastructure using the existing terraform tools and have the least impact to anyone else.

B) tfvars supports unquoted string values allowing use of direct output from terraform output.  This would allow being able to share references between projects quickly doing something like `terraform output > output.tfvars`.  Assuming this doesn't have any unintended side effects this would be very great if it was part of the core.

### References
I have not found anything that similar yet.

**Comment by mildwonkey** [comment]
Hi @SPhu, thanks for opening this feature request!

As a workaround, you could use the `format` function to format your outputs to include the quotes. Here's an example:

main.tf
```hcl
variable "pet_count" {
  default = 3
}

output "variable" {
  value = format("\"%s\"", var.pet_count)
}

```

Output:
```bash
variable = "3"
```

**Comment by abiydv** [comment]
Just thinking out loud here, have you tried to simply query for these resources directly from AWS rather than depending on TF.

As an example, to get the right results for subnets you need, you could tag the subnets, vpcs etc appropriately at launch through terraform.

From the official (docs)[https://www.terraform.io/docs/providers/aws/d/subnet_ids.html]

```
data "aws_subnet_ids" "private" {
  vpc_id = "${var.vpc_id}"
  tags = {
    Tier = "Private"
  }
}

resource "aws_instance" "app" {
  count         = "3"
  ami           = "${var.ami}"
  instance_type = "t2.micro"
  subnet_id     = "${element(data.aws_subnet_ids.private.ids, count.index)}"
}
```

**Comment by apparentlymart** [comment]
It seems very reasonable to me to support a new mode on `terraform output`, like this:

```
terraform output -tfvars >foo.tfvars
```

This follows the same principle as `-json` but would be expressly documented as generating something that can be accepted by `-var-file` on a Terraform run. I think for simplicity's sake the first version of it should produce an error if the `NAME` argument is provided, since it doesn't really make sense to ask for only a single value in tfvars format and making it fail now will leave room for us to potentially make this do something else in future, once we have a real use-case for it to help decide how it should work.

[The `hclwrite` package](https://godoc.org/github.com/hashicorp/hcl2/hclwrite) could be used to implement the HCL generation portion of this, by creating a `NewEmptyFile` and then calling `SetAttributeValue` repeatedly on the file's top-level body. For readability and consistency of output across multiple runs with no changes, we should sort the outputs lexicographically by their names. 

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

(I would say, though, that if anyone _is_ interested in contributing a PR for this it'll be best to wait until after 0.12.0 final is out, since the 0.12 scope is already quite large and we're trying to avoid adding anything new to it so we can release it as soon as possible.)

**Comment by SPhu** [comment]
I am .using data blocks in some cases and they work but there are 2 cons to that:
1) it slows down the terraform process to query a bunch of extra stuff that rarely changes.
2) i still have to hand type everything out.  The hope here was output already provides something so close to tfvars compatible it would make export and updates in other projects really easy.

I will use midlwonkey's work around in the mean time as that seems reasonable for what I need.   Codewise I think this would be a pretty small addition.  I can probably write it and submit as a pull request if you think it has a chance of being accepted.

**Comment by SPhu** [comment]
I'm going to close my request since there is a suitable workaround that I am now using.   I will reopen if I can provide a pull request.  Thank you for the feedback.
