### ISSUE TITLE
Terraform backend.tf via modules

### ISSUE THREAD

**Issue by WoodProgrammer** [hashicorp/terraform#20009]
I 've modules in another directory. So I want to add the backend.tf and set the provider data from linux environment variable .

But terraform giving error .

My Structure is showing as below .

main.tf
└── vpc
├── backend.tf
├── export.sh
├── vars.tf
└── vpc.tf

## main.tf
        module "my_vpc" {
              source = "../../vpc"
              instance_tenancy = "default"

        }

## backend.tf
        terraform {
        backend "s3" {
                region = "${var.aws_region}"
                bucket = "${var.TERRAFORM_BUCKET}-vpc"
                profile = "${var.ORGANISATION}"
                key    = "${var.ORGANISATION}"

            }
         }

        provider aws {

                profile = "${var.ORGANISATION}"
            region = "${var.aws_region}"
        }
I've exported variables ORGANISATION,REGION and TERRAFORM_BUCKET variables from terminal , but it give this error :

        Error: module "my_vpc": missing required argument "aws_region"

        Error: module "my_vpc": missing required argument "TERRAFORM_BUCKET"

        Error: module "my_vpc": missing required argument "ORGANISATION"
How Can I solve this issue ?

Notice : call backend.tf from module via environment variables . (Dynamic and default variables )

Please Help !

**Comment by abiydv** [comment]
This is what the [docs](https://www.terraform.io/docs/backends/config.html) say about variables in backend config.

> Only one backend may be specified and the configuration may not contain interpolations. Terraform will validate this

This might help - https://github.com/hashicorp/terraform/issues/17288

**Comment by mildwonkey** [comment]
Hi! @abiydv 's response is accurate - thanks!

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
