### ISSUE TITLE
0.12 Datasource Test Errors

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/terraform#20035]
### Terraform Version

```
commit: 2ad9f0513a2bd57ef49e88f9de0d2f2cc1592ff3
```

It looks like there were some changes with testing datasources from [here]( https://github.com/hashicorp/terraform/blob/master/helper/resource/testing_config.go#L155). This [test](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_vpc_dhcp_options_test.go#L46) isn't passing with the above commit because there is an error when refreshing the datasource (as expected) and the destroy isn't happening. 

TestAccDataSourceAwsVpcDhcpOptions_Filter is being run off this [branch](https://github.com/terraform-providers/terraform-provider-aws/tree/v0.12-sdk-updates) in aws. It is currently failing with ` Error: errors during refresh: Multiple matching EC2 DHCP Options found` which is the expected error from the test. Both test steps are passing so it looks like it's being done in the destroy step of tests.

**Comment by apparentlymart** [comment]
After some review and comparison with the 0.11 SDK behaviors we concluded that the previous behavior of this test was actually incorrect, and the new error returned by the updated SDK is legitimate.  In particular, the test was previously succeeding but leaving behind the remote objects it created. For more information, see terraform-providers/terraform-provider-aws#7370.

We're not planning to make any changes within the SDK itself for this, but there may be other providers relying on the prior behavior. These can hopefully be fixed in a similar way as terraform-providers/terraform-provider-aws#7370, which should both fix the test failure _and_ the dangling resources it was silently leaving behind before.
