### ISSUE TITLE
Cannot start terraform apply from scratch after a fork has been created.  Terraform needs a function to remove entire terraform state after manual deletion of a VPC to start from scratch..

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#20045]
### Terraform Version

```
v0.11.11
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m0s elapsed)
module.pcoipgw.aws_instance.pcoipgw: Still creating... (1m0s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m10s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m10s elapsed)
module.pcoipgw.aws_instance.pcoipgw: Still creating... (1m10s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m20s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m20s elapsed)
module.pcoipgw.aws_instance.pcoipgw: Still creating... (1m20s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m30s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m30s elapsed)
module.pcoipgw.aws_instance.pcoipgw: Still creating... (1m30s elapsed)
module.vpc.module.vpc.aws_nat_gateway.this[1]: Creation complete after 1m38s (ID: nat-0dd62dc942e89c333)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m40s elapsed)
module.pcoipgw.aws_instance.pcoipgw: Still creating... (1m40s elapsed)
module.vpc.module.vpc.aws_nat_gateway.this[0]: Creation complete after 1m48s (ID: nat-0687633ab217ae0b1)
module.pcoipgw.aws_instance.pcoipgw: Creation complete after 1m47s (ID: i-0594d5715133014f4)
Failed to save state: truncate terraform.tfstate: bad file descriptor

Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate

### Expected Behavior
After deleting an AWS VPC and all its contents,
I did a terraform rm manually on each module.

```
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.pcoipgw
1 items removed.
Item removal successful.
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.*
1 items removed.
Item removal successful.
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.*
1 items removed.
Item removal successful.
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.softnas
1 items removed.
Item removal successful.
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.softnas
1 items removed.
Item removal successful.
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.vpn
1 items removed.
Item removal successful.
user@ubuntu:/data/mac/GitHub/firehawk-compute-batch$ terraform state rm module.vpc
1 items removed.
Item removal successful.
```
I would expect that the next terraform apply would start from scratch, but it says that it created a forked state.
  
### Actual Behavior
...it errors and says that its creating a forked state.

it would be helpful to have a command like 
terraform nuke state
Which would assume you have deleted all resources manually, so that the next terraform apply would  behave as if you have started from scratch.

### Steps to Reproduce
I don't think this is easily reproducable by others.  I'm not sure how I created the forked state in the first place.

**Comment by apparentlymart** [comment]
Hi @queglay! Sorry for this strange behavior.

I've never seen this "bad file descriptor" error before, and that seems to be the root of the problem here. Unfortunately without the full trace log it's hard to guess what might've caused that.

When Terraform encounters this sort of fatal error writing state, it tried to avoid loss of the updated state by writing it out to `errored.tfstate` as a last resort. The usual way to recover from this is to run `terraform state push errored.tfstate` to have Terraform try again to write the locally, as the error message here mentioned.

You only get a "forked state" here if you attempt to run `terraform apply` again _without_ first recovering from the error.

Terraform has no built-in way to entirely destroy the state without also destroying, because that is a very rare operation. Instead, in the rare situation where that is necessary we expect the user to do operate directly against the backend. Since you are using the local backend here, deleting the state to start fresh is just a matter of running `rm terraform.tfstate`, though of course this will cause Terraform to lose track of any remote objects that already exist.

**Comment by queglay** [comment]
I set the tf log variable, but the documentation doesn't describe where to get the log.
https://www.terraform.io/docs/internals/debugging.html
I don't know what stderr is.

**Comment by queglay** [comment]
so I tried to just go back to basics, and make a vpc in a new simple vpc repo to demonstrate the bug.
https://github.com/queglay/debug-broken-vpc

...and it breaks the same way when it comes to creating the gateway.

when I check terraform-aws-modules/vpc/aws on github, it looks like it has had updates in the last 8 hours, which could explain why I was fine yesterday, but not today.  but I can't be sure since I've only been using this software for about 2 months.

https://github.com/terraform-aws-modules/terraform-aws-vpc

this was the error in the simple repo.

```

module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m10s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m10s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m20s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m20s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m30s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m30s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m40s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m40s elapsed)
module.vpc.vpc.aws_nat_gateway.this.0: Still creating... (1m50s elapsed)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (1m50s elapsed)
module.vpc.module.vpc.aws_nat_gateway.this[0]: Creation complete after 1m57s (ID: nat-0c43cab2209d903aa)
module.vpc.vpc.aws_nat_gateway.this.1: Still creating... (2m0s elapsed)
module.vpc.module.vpc.aws_nat_gateway.this[1]: Creation complete after 2m8s (ID: nat-0c2d07115dd7cc3e7)
Failed to save state: truncate terraform.tfstate: bad file descriptor


Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate




```

**Comment by queglay** [comment]
After about 7 hours of trying to work this out - rebooting my ubuntu in vmware workstation made the problem just go away.  That hurts!  Must have been memory corruption or something within the vm.  My ECC ram didn't help.

Would still love to know were to locate stderr debug output for the future, apologies for the noob question, but the documentation doesn't explain where the logs are unless I totally missed it.

**Comment by queglay** [comment]
I spoke to soon, I just had the issue return in the ubuntu vm

**Comment by antonbabenko** [comment]
@queglay It is sad that you've faced such issues with Terraform.

The latest version of terraform-aws-modules [v1.52.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v1.52.0) which was released yesterday has nothing to do with the problem you are describing.

Sometimes there can be situations when you need to manually clean up resources in AWS due to some locks on aws_internet_gateway which can't be deleted when in use. The solution is to delete resources manually one by one prior to the internet gateway.

**Comment by queglay** [comment]
I have isolated one issue, the error in my initial post - to running the terraform template within my ubuntu 18.04 VM in vmware workstation.  The host OS is RHEL 7.5, and running terraform apply in RHEL there is no issue.  I have attempted to disable transparent hugepages in RHEL to see if this helps in the future, because I've read that this can conflict with VMware.  I'd love to hear if anyone else has witnessed vmware issues in a linux host.

In RHEL, I successfully did a terraform apply, but I did just witness a one off event when I attempted terraform destroy - on an instance with 4 EBS volumes attached (RAID 6 in softnas).  EBS detachment was timing out on all of them (probably because they were in use from a software update.  I also couldn't manually detach the instances through the AWS UI, so its likely that AWS is able to prevent this detachment from happening!
Stopping the instance first was required to force detachment, which resolved the issue.

So it might be worth noting that when doing a destroying an instance with ebs volumes attached, that an instance should be turned off prior to EBS detachment.

**Comment by antonbabenko** [comment]
I think you will get a better response if you ask VMware question somewhere else, as this is not related to Terraform and this issue can be closed here.

**Comment by apparentlymart** [comment]
Hi @queglay,

I'm glad you were able to narrow down the problem here. I'm afraid @antonbabenko is right that we don't have lots of detailed VMware expertise in the Terraform team so I can't be sure what might have happened here. If you were using Terraform in a directory exported from your host machine using the "shared folders" mechanism then perhaps that special filesystem does not behave in the "normal" way Terraform expects. However, our limited knowledge here means that unfortunately we can't help any further with debugging that. :confounded: 

It sounds like you have also found a quirk of the AWS provider behavior, in which case you may wish to see if that issue is already covered in [the AWS provider issues](https://github.com/terraform-providers/terraform-provider-aws/issues). Some AWS constraints cannot feasibly be reflected within Terraform, but it may be possible for the provider to do something to mitigate this particular problem. The AWS provider team is in a better position to comment on that part.

The name `stderr` refers to the stream where programs write their error output. By default when you run a command at a shell prompt this is connected to your terminal, causing the error output to appear directly in the terminal along with other output. Therefore if you just set `TF_LOG=trace` and run Terraform you should notice a lot of extra log output appearing in your terminal, mixed in with the normal Terraform output. You can also set `TF_LOG_PATH` to a filename in order to capture the log into a separate file on disk, which avoids the log interfering with the normal Terraform output.

Since you've now fixed the issue by rebooting your VM, I'm going to close this out. I'm sorry we weren't able to figure out exactly what happened here, but I'm glad you found a solution nonetheless.

**Comment by queglay** [comment]
Before I go, could someone let me know how to get the path to the log trace
output for my own future reference?  The documentation doesn't appear to
explain this.

Thanks for all your help.


Andrew Graham

**Comment by queglay** [comment]
Thanks Martin!
