### ISSUE TITLE
What is meta.count-boundary in terraform graphs? 

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform#20063]
![image](https://user-images.githubusercontent.com/6265399/51454553-49b9ac80-1d13-11e9-9e5b-bd0019058809.png)

I see this meta.count-boundary node under root. What is it for and what does it do? Just confused about why its there- dont understand it in the context of the graph

**Comment by abitrolly** [comment]
I am interested to know about this too.

**Comment by red8888** [comment]
@abitrolly https://github.com/28mm/blast-radius

**Comment by apparentlymart** [comment]
Hi @red8888,

Each node in the Terraform graphs performs some action on the plan or on the state. This particular node has the responsibility of detecting when the number of `count`ed instances for a resource has changed from one to greater than one or vice-versa and adjusting the saved resource addresses to match, so that e.g. `aws_instance.foo.example` is recorded instead as `aws_instance.foo.example[0]` or vice-versa. This happens after all other operations so that we can make sure that the state is saved in a consistent way before Terraform completes.

It's not a particularly interesting node from an end-user standpoint, but currently the `terraform graph` output is a faithful rendering of the entire graph, including both the nodes that map on to real objects in the configuration and the utility nodes that Terraform creates to handle this sort of preparation or fixup in the graph walk.

**Comment by abitrolly** [comment]
I see `count-boundary` is a node type that contains references to some specific resource types. Is that right? There is a link from it to `output` resource type, but no links to `aws_security_group` resources. It the link only type dependent? Or the link appears only when resource `count` in some specific state?

**Comment by red8888** [comment]
I could manually edit the graph to remove it i guess, but is there any support for something like predefined "schemes" or something that will create graphs without meta/less interesting stuff for me?

**Comment by apparentlymart** [comment]
The count boundary node depends on any node that can affect the resource instances in the state, which in practice means nodes representing resources. Anything that can't add/remove resource instances in the state is not a dependency of that node.

Currently the `terraform graph` command shows a faithful representation of the full, physical Terraform graph. In future we may repurpose it to generate "logical graphs" that reflect the relationships in the configuration only, but the output of `terraform graph` is not something we are currently investing in, due to priorities being elsewhere. Changes to it would need to be carefully considered since I believe there is software out there depending on this output for various purposes; before we make any changes to it, we'll need to design carefully what its new purpose is and ensure it's still able to generate consistent results even though it would be, in effect, ignoring various nodes in the real graph.

There is already issue #14511 for the idea of making the graph output describe the user model of the graph rather than the physical model of the graph. If you're interested in that, I'd encourage adding a :+1: reaction to the lead comment on that other issue, which we use as an input for prioritization of future work. If anyone is interested in working on this, the first step would be to discuss and achieve consensus on a proposal for what exactly it should do and how it should work, and a rollout plan for it that would minimize impact for those depending on the current graph output.
