### ISSUE TITLE
Hide the passwords on screen

### ISSUE THREAD

**Issue by SkypLabs** [hashicorp/terraform#20068]
### Current Terraform Version

```Terraform v0.11.11```

### Use-cases

It is usual to submit passwords as input variables. According to the documentation, there is no way not to display these sensitive information on screen.

### Proposal

Adding a variable type `password` which would act as a regular string but its value won't be displayed on screen when the user is prompted to type it and in the `plan` and `apply` outputs.

### References

I haven't found any other issue or PR about this topic.

**Comment by SkypLabs** [comment]
I just realised that the output of the `random_string` resource is already hidden when doing `terraform plan` or `terraform apply`. It should be even easier to implement than what I thought.

**Comment by apparentlymart** [comment]
Hi @SkypLabs! Thanks for sharing this use-case.

The concept of a sensitive attribute is currently something the provider itself defines, and not something that is propagated through from the _source_. So to prevent passwords from appearing in the rendered plan, currently the only option is to use them only in attributes that are marked as sensitive in providers. If there are attributes that ought to be sensitive but aren't, I'd recommend opening an issue in the provider's own repository to request that.

The idea of making sensitivity "propagate" so that any use of a sensitive variable is itself sensitive is being discussed over in #8076, so I'm going to close this one just to consolidate the discussion over there. You can find over there a comment from me about the investigation work we did so far and the questions we still need to answer before moving forward with that feature.

Thanks again!
