### ISSUE TITLE
0.12 TypeMap Validation Issue

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/terraform#20076]
It looks like TypeMap forces the configuration to specify `key` when instantiating a TypeMap blockin 0.12. 
```
    testing.go:568: Step 0 error: config is invalid: Missing key for permissions: All permissions blocks must have 1 labels (key).
``` 

There is a [resource](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_document.go#L129) in the aws provider that uses different names for the keys. Is this functionality being lost with the swap to 0.12?

**Comment by apparentlymart** [comment]
Hi @mbfrahry,

A `TypeMap` schema field with a non-primitive type was not supported by Terraform 0.11 and earlier due to ambiguities in the flatmap serialization. I'm not sure how this was ever working in 0.11, but 0.12 allows this for the first time with a new syntax that expects the map key to be provided as a label on the block:

```hcl
permissions "foo" {
  type        = "bar"
  account_ids = "baz"
}
```

I assume that before this was working due to a combination of a missing `InternalValidate` rule and, perhaps, use of syntax like this? (I couldn't find any examples of its use in the tests or in the docs)

```hcl
permissions = {
  foo = {
    type = "bar"
    account_ids = "baz"
  }
}
```

We added support for the new map block syntax to the 0.12-supporting part of the SDK, but the 0.11 compatibility codepath can't support it, so I don't think there's any way to write a config for this particular block that would work in both 0.11 and 0.12, since it was never supposed to work at all in 0.11.

One path forward here would be to introduce a new attribute `permission` alongside, also defined as `TypeMap` with a `schema.Resource`, and document that the following usage (with the singular block type name) is required for 0.12:

```hcl
permission "foo" {
  type        = "bar"
  account_ids = ["baz"]
}
```

This exploits the change to singular (which is what we expect for nested block type names) to also allow the new and old attributes to coexist here. I also took the opportunity to redefine `account_ids` as a list or set since it has a plural name and is therefore presumably not a single string.

We can then leave `permissions` (plural) unchanged and let it continue working to whatever extent it was working in 0.11 (buggily, I assume), removing it in whatever future release ends support for Terraform 0.11 in the provider.

**Comment by bflad** [comment]
Another example of this seems to be in the `aws_cognito_identity_pool_roles_attachment` resource:

```go
			"roles": {
				Type:     schema.TypeMap,
				Required: true,
				ForceNew: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"authenticated": {
							Type:         schema.TypeString,
							ValidateFunc: validateArn,
							Optional:     true, // Required if unauthenticated isn't defined.
						},
						"unauthenticated": {
							Type:         schema.TypeString,
							ValidateFunc: validateArn,
							Optional:     true, // Required if authenticated isn't defined.
						},
					},
				},
			},
```

Previously, in the testing framework and various opened issues, this syntax was working in Terraform 0.11:

```hcl
  roles {
    "authenticated" = "${aws_iam_role.authenticated.arn}"
  }
```

Not that anything needs to be done, but just providing another example in case its more prevalent. In this case we'll likely want to make the breaking change of:

```go
			"roles": {
				Type:     schema.TypeList,
				Required: true,
				ForceNew: true,
				MaxItems:  1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"authenticated": {
							Type:         schema.TypeString,
							ValidateFunc: validateArn,
							Optional:     true, // Required if unauthenticated isn't defined.
						},
						"unauthenticated": {
							Type:         schema.TypeString,
							ValidateFunc: validateArn,
							Optional:     true, // Required if authenticated isn't defined.
						},
					},
				},
			},
```

**Comment by apparentlymart** [comment]
Hmm, interesting... it looks like the SDK here was essentially ignoring the `Elem` entirely here and just treating it as a map of string. The schema defined in `Elem` (as far as I can tell) ignored entirely, and the SDK would just as readily accept nonsense like this:

```hcl
  roles = {
    "blahblah_anything" = "invalid"
  }
```

If we can verify that this is the case, there is a potential path forward for compatibility here: change the rules for how we map a `map[string]*schema.Schema` onto a v0.12 core schema so that instead of generating a nested block backed by a map here it will instead generate an attribute typed as `map(string)`.

Since a nested block backed by a map was never actually possible in prior versions, it should be safe for us to change this rule because no existing provider can be relying on the _new_ behavior. This means that we won't be able to use the new behavior until the SDK revamp, but that was true anyway because Terraform Core v0.11 can't properly support nested blocks backed by a map itself.

Would one of you mind doing a quick test to confirm whether my guess is correct here that the keys of these maps are not being validated at all? The test would be to add a random new key to the `permissions` or `roles` blocks for these resources and see if it produces a validation error. If my understanding is correct, I think the fix here would be relatively straightforward, and the rules already in the configuration upgrade tool will take care of adding the `=` sign that is required because of this being defined as an attribute rather than a block.

**Comment by bflad** [comment]
> Would one of you mind doing a quick test to confirm whether my guess is correct here that the keys of these maps are not being validated at all?

```hcl
resource "aws_cognito_identity_pool_roles_attachment" "main" {
  identity_pool_id = "${aws_cognito_identity_pool.main.id}"

  roles {
    "authenticated" = "${aws_iam_role.authenticated.arn}"
    "invalid"       = "${aws_iam_role.authenticated.arn}"
  }
}
```

No schema validation error -- fails trying to send `invalid` over the wire.

```
--- FAIL: TestAccAWSCognitoIdentityPoolRolesAttachment_basic (8.44s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_cognito_identity_pool_roles_attachment.main: 1 error occurred:
        	* aws_cognito_identity_pool_roles_attachment.main: Error creating Cognito Identity Pool Roles Association: ValidationException: 1 validation error detected: Value '{authenticated=arn:aws:iam::187416307283:role/cognito_authenticated_6w1h21x0qi, invalid=arn:aws:iam::187416307283:role/cognito_authenticated_6w1h21x0qi}' at 'roles' failed to satisfy constraint: Map keys must satisfy constraint: [Member must satisfy regular expression pattern: (un)?authenticated]
```

**Comment by apparentlymart** [comment]
Ahh, great... that seems like it confirms my suspicion. (I assume that regexp-y error is coming from the remote API, since we don't have any validation rule like that defined in the provider.)

In that case, I think we should proceed with the change I proposed before, which should allow these to work as before aside from an equals sign now being required (which the upgrade tool will fix).

Optionally we could choose to delete the `Elem` of these to avoid future readers being misled into thinking that this is either validating the keys or producing a map of objects, but that isn't a release requirement so much as a code cleanup task which could in principle happen at any time. If you (_plural_ you :wink:) feel motivated to do that now, we could potentially add a new check for this in `InternalValidate` so the acctests will catch cases of it across all the providers, but I think I would lean towards leaving that until some time after we get the first protocol-5-compatible releases out just so we don't add more roadblocks into the mix.
