### ISSUE TITLE
Safari can't load docs site

### ISSUE THREAD

**Issue by sj26** [hashicorp/terraform#20073]
Visiting the [terraform docs site](https://www.terraform.io/docs/) in Safari 12.0.2 (14606.3.4) on macOS 10.14.2 (18C54) just hangs forever for me. I've tried clearing caches, etc, to no avail. It looks like it's blocked on typekit analytics (which is a css file?!) which is blocking page render:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/14028/51506207-41f72680-1e3f-11e9-8331-5921d53c80b9.png">

Seems to work in incognito for some reason, though:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/14028/51506209-458aad80-1e3f-11e9-9610-a13bf31f977b.png">

I do have the Nope extension installed, but I disabled it for the site and it makes no difference.

**Comment by jescalan** [comment]
Hey @sj26! We're trying to replicate this issue with the same Safari build on OSX and none of us are able to do so. Is there any more information you could give us on how you have Safari set up, or are there any other extensions in use that might be interfering with the page loading?

As far as this specific issue, typekit gives us a stylesheet url which contains the licensed font embeds, and as you mentioned, also loads a small, empty stylesheet with some querystring params for analytics (as you mentioned) via `@import` internally. Unfortunately, if this load hangs, it causes everything to hang, which is why web devs in general tend [to try to avoid `@import`](https://www.stevesouders.com/blog/2009/04/09/dont-use-import/). But in this case, there's not much we can do other than trying to reproduce the issue and reaching out to typekit!

**Comment by sj26** [comment]
It's loading now! I only reported it after it continued for a couple of days, but it seems to have sorted itself out somehow? Sorry for the trouble!
