### ISSUE TITLE
Render raw references in partially known strings in plan (0.12)

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#20075]
Strings can be entirely unknown, which in the new HCL syntax allows user to omit the quotes, e.g.

```hcl
  description = aws_iam_policy.another.arn
```
or just partially known, which (AFAIK) requires the existing HIL/HCL syntax, e.g.

```hcl
  description = "Example ${aws_iam_policy.another.arn}"`
```

----

If there's a change in the partially known field (2nd example), 0.11 renders it like this:

```
  description: "My example" => "My example ${aws_iam_policy.another.arn}"
```
whereas 0.12 just prints out "(known after apply)", omitting the known part of the string.
```
~ description = "My example policy" -> (known after apply)
```

The fix doesn't seem to be as simple as tuning the diff formatter as the formatter already receives "unknown string" in cty's language.

## Repro case

I'm sure we could come up with something even simpler with `random` provider, but this is the one I had on hand 🤷‍♂️ 

### Before

```hcl
resource "aws_iam_policy" "example" {
  name        = "example-radek"
  path        = "/"
  description = "My example"

  policy = <<EOF
{
  "Statement": [
    {
      "Action": [
        "ec2:Describe*",
        "ec2:Create*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ],
  "Version": "2012-10-17"
}
EOF
}
```

### After

```hcl
resource "aws_iam_policy" "another" {
  name        = "example-another"
  path        = "/"
  description = "My example policy"

  policy = <<EOF
{
  "Statement": [
    {
      "Action": [
        "ec2:Describe*",
        "ec2:Create*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ],
  "Version": "2012-10-17"
}
EOF
}

resource "aws_iam_policy" "example" {
  name        = "example-radek"
  path        = "/"
  description = "My example ${aws_iam_policy.another.arn}"

  policy = <<EOF
{
  "Statement": [
    {
      "Action": [
        "ec2:Describe*",
        "ec2:Create*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ],
  "Version": "2012-10-17"
}
EOF
}
```

**Comment by apparentlymart** [comment]
The behavior in 0.11 was a consequence of the interpolator just mutating the data structure it received and then leaving unknown things unchanged in that data structure. That was therefore an unintended consequence of HCL and HIL being separate and is impossible to replicate in the new combined language, since that uninterpolated "string" doesn't exist anywhere except the original source code.

"Breaking" this accidental but useful behavior was one of the compromises we had to make to get reasonable, predictable expression evaluation behavior. (In 0.11 and earlier those uninterpolated strings would also sometimes make their way into providers during validate/plan, etc, which led to other odd bugs). I don't expect there is anything reasonable we can do to recover the old behavior here, even though it was indeed useful sometimes. To get something approaching the old behavior would require the diff renderer to have access to the orignal source code and somehow extract the relevant part to include in the diff.

I'm going to close this just because I don't really see any reasonable thing we could do to address it. Unless we come up with some bright idea in a later release, users must refer to the configuration source code to understand why a particular attribute isn't known.
