### ISSUE TITLE
Example to deploy a java hello-web application?

### ISSUE THREAD

**Issue by javabrown** [hashicorp/terraform#20101]
I am stuck on a basic  application need.  I have a spring-boot hello-world application (web jar), I want to deploy it to aws using terraform.  
Could someone suggest how to do that? Sample example is appreciated.
Thanks in advance.

**Comment by apparentlymart** [comment]
Hi @javabrown,

Terraform is not an application deployment tool, but rather a tool for managing infrastructure. In principle you could use Terraform to start up a virtual server (EC2 instance, etc) with a machine image containing your Java application, but what is running on a virtual server is outside of Terraform's scope and the responsibility of some other tool.

There are lots of different options here and I can't advise on any specific path since I don't know your situation, but here are some common approaches that will hopefully help with your ongoing research:
* Some organizations build virtual machine images that are configured to load their applications on boot and then use Terraform to provision the virtual machines using those images. In the HashiCorp ecosystem, [Packer](https://packer.io/) is a common way to customize a default Linux distribution image to add additional software and configuration to it, though other options are available too.
* Some organizations prefer to make a larger separation between infrastructure and application deployment by using Terraform to deploy another system responsible for running an application. HashiCorp's own [Nomad](https://www.nomadproject.io/) has [built-in support for running Java applications](https://www.nomadproject.io/docs/drivers/java.html), or you could use (Kubernetes)[https://kubernetes.io/] (either hosted on a virtual machine you run or using Amazon's hosted Kubernetes service) to deploy a [Docker](https://www.docker.com/) container running your application.
* [AWS Fargate](https://aws.amazon.com/fargate/) is another mechanism for running Docker containers without separately maintaining the virtual servers that host them.

Whichever option you choose, Terraform can potentially help with the part of the problem that involves creating infrastructure objects in AWS itself, but installing an application into a server is not part of Terraform's scope and is better handled by other tools.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by javabrown** [comment]
Thanks very much
