### ISSUE TITLE
Download zip file name format has changed

### ISSUE THREAD

**Issue by michael-mcguinness** [hashicorp/terraform#20117]
### Terraform Version
0.12.0-alpha4

### Additional Context
The format of the name of the download zip file has changed after 0.12.0-alpha2.
from:
terraform_0.12.0-alpha2_linux_amd64.zip

to:
terraform_0.12.0-alpha4_terraform_0.12.0-alpha4_linux_amd64.zip

The version is duplicated in the name. We have an automated process that retrieves these files and checks the sha256sum. This change breaks that.

**Comment by apparentlymart** [comment]
Hi @michael-mcguinness!

This is the same as #19588, so please see my response over there. Given that alpha4 is a very early prerelease with several known bugs, using it with automated processes is probably not the best idea anyway, but (as I mentioned in the other issue) the usual naming scheme will be restored for the final releases of 0.12 because they will not be constructed manually using an exceptional process.
