### ISSUE TITLE
support variable indirection

### ISSUE THREAD

**Issue by jhoblitt** [hashicorp/terraform#2016]
This is a general feature request.  My immediate use case is the desire to reuse the same set of configuration files to create multiple VPCs in the same region.  This actually seems to be, but it's a bit "scary" when watching the console output or inspecting the tfstate file.

This intended to convey the intent, not suggest syntax.

```
resource "aws_internet_gateway" "${var.my_namespace}" {
    vpc_id = "${aws_vpc.${var.my_namespace}.id}"
}
```

Or even more meta:
```
resource "aws_internet_gateway" "${var.my_namespace}" {
    vpc_id = "${aws_vpc.${self.id}.id}"
}
```

**Comment by phinze** [comment]
Hi there!

This is the use case that modules were designed to solve. Because each instantiated module represents an independent namespace, there's no need to do any interpolation to get unique resource names.

For a relevant example, I just pushed the Terraform module I've been using to create VPCs:

https://github.com/terraform-community-modules/tf_aws_vpc/tree/f-phinze-revamp

Take a look and let me know if that makes sense to you - I'd be happy to discuss further.
