### ISSUE TITLE
When compute instance is tainted with reduced count, non-tainted instance should not be deleted

### ISSUE THREAD

**Issue by kamaltherocky** [hashicorp/terraform#20193]
### Current Terraform Version
$ terraform -v                                                                              
Terraform v0.11.11
+ provider.google v0.1.2
+ provider.null v0.1.0
+ provider.random v2.0.0
+ provider.template v1.0.0

### Use-cases
Basically, this is an ability to delete targeted instances without replacing with new one.

Lets say we are having 10 compute instances (with index of 0-9) and we want to delete specific instances (For this example, we wanted to delete the instance 3, 4 and 5 ) and also reduce the number of instances to a lesser number (in this case, lets say it is 8). we use the `taint` command to mark the compute instances which needs to be deleted and then we apply.

The expected behavior is that it should delete only the tainted resources (3 of them) and match the count of the instances requested by creating/deleting instance (create one new one to match the count of  8). 

Currently, the way it works is the tainted resources (3, 4, 5) are deleted then created and the other non-tainted resources(9, 10) at the end of the index are deleted. so unnecessarily, 2 good resources (9,10) are getting deleted which should not be even touched.

### Attempted Solutions
Tried to use the `create_before_destroy` flag but it is not working with google compute instance.

### Proposal
The resources which are not tainted should not be affected if the count can be satisfied by just deleting the tainted resources.

**Comment by apparentlymart** [comment]
Hi @kamaltherocky!

The idea behind `count` is to create a number of equivalent copies of the same kind of object such that all are considered equivalent to one another. As such, it identifies the instances only by their numeric index, and so asking for a reduction of `count` effectively makes the indices greater than that count no longer exist in configuration, causing them to be deleted.

It sounds like in your case you are instead using `count` to create a number of similar objects where each one has something special about it, such that when you reduce the number you care about which ones are deleted. That is not an intended use-case for `count`, though we know that it has been used that way by many users in practice.

For this reason, we are planning to implement the feature described in #17179 in a future release. This feature will allow you to create multiple objects from a single resource block while also controlling the key Terraform users to refer to each of them, thus allowing more precise control over which individual objects are acted on when the set of keys changes or when an instance is tainted.

Since we already have #17179 open, I'm going to close this one out just to consolidate the discussion there. Please follow that issue for updates when we implement `for_each` within resource blocks.

**Comment by kamaltherocky** [comment]
Thanks @apparentlymart . what is the release date for v0.12 and will the `for_each` will be part of the release?
