### ISSUE TITLE
AWS Secrets Manager stores secrets in plaintext within statefile

### ISSUE THREAD

**Issue by sce81** [hashicorp/terraform#20207]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.45.0
...
```

### Terraform Configuration Files

```hcl

data "aws_secretsmanager_secret" "db_password" {
    name = "Testing"
}

data "aws_secretsmanager_secret_version" "db_password" {
    secret_id = "${data.aws_secretsmanager_secret.db_password.id}"
}

module "RDS" {

  db_secret     = "${data.aws_secretsmanager_secret_version.db_password.secret_string}"  

}
...
```

### Expected Behavior

AWS Secret should not be stored in state

### Actual Behavior

AWS Secret is stored in state

**Comment by apparentlymart** [comment]
Hi @sce81,

Any value you can interpolate in configuration will be stored in the state because that is where the interpolated values come from. If you wish to work with sensitive values in Terraform the current options are:

* Treat the state itself as sensitive: use access control and encryption at rest, such as using encryption in S3 along with a restrictive IAM policy.
* Instead of retrieving the sensitive value using a data source, pass it in as a variable and use it only in `provider`, `provisioner`, and `connection` blocks. This works because those features do not require storage in state.

In a future release we plan to tackle more fine-grain encryption of state data, or perhaps some other solution for limiting exposure of certain data. Further design work is required to find the best approach to ensure it ends up being an overall usability improvement vs. the coarse solutions I listed above. When that work begins, we will discuss it in #516. I'm going to close this issue just to consolidate discussion over there.
