### ISSUE TITLE
Unknown root level key

### ISSUE THREAD

**Issue by sujith-siva** [hashicorp/terraform#20218]
Hi,

I am trying to create a bucket using terraform.
The bucket should be encrypted and only access to the internal users of a certain ip address range.

This is the error I am seeing while running the terraform plan.

```
Error: Unknown root level key: backup.test.com

Error: Unknown root level key: server_side_encryption_configuration

Error: resource 'aws_s3_bucket_public_access_block.public_access_block' config: unknown resource 'aws_s3_bucket.backup' referenced in variable aws_s3_bucket.backup.id

Error: resource 'aws_s3_bucket_policy.backup_test_policy' config: unknown resource 'aws_s3_bucket.backup' referenced in variable aws_s3_bucket.backup.id
```

------------------------------------------------------------------------------------------------------------------
My terrafrom file is as follows:-

```hcl
### S3 bucket for internal access only with encryption
### Test S3 bucket
resource "aws_s3_bucket" "backup" {
  bucket = "backup.test.com"
}

resource "aws_s3_bucket_policy" "backup_test_policy" {
  bucket = "${aws_s3_bucket.backup.id}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "Backup-Internal-Access-Policy",
  "Statement": [
    {
      "Sid": "IPAllow",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::backup.test.com/*",
      "Condition": {
         "IpAddress": {"aws:SourceIp": "10.x.x.x/21"}
      }
    }
  ]
}
POLICY
}

server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
   }
 }


resource "aws_s3_bucket_public_access_block" "public_access_block" {
  bucket = "${aws_s3_bucket.backup.id}"

  # Block new public ACLs and uploading public objects
  block_public_acls = true

  # Retroactively remove public access granted through public ACLs
  ignore_public_acls = true

  # Block new public bucket policies
  block_public_policy = true

  # Retroactivley block public and cross-account access if bucket has public policies
  restrict_public_buckets = true
}
```

Thanks for the help

Regards
Siva

**Comment by mildwonkey** [comment]
Hi @siva! So you know, I edited the formatting (only) on this issue so it's easier to folks read. 


It looks like you have a mis-placed bracket. I was able to run this terraform configuration with just one minor change: move the closing `}` after the last `POLICY` to below the `server_side_encryption_configuration` block.

This may be easier to see as a patch:

```
$ git diff main.tf
diff --git a/main.tf b/main.tf
index 8ed3108..544ef73 100644
--- a/main.tf
+++ b/main.tf
@@ -25,7 +25,6 @@ resource "aws_s3_bucket_policy" "backup_test_policy" {
   ]
 }
 POLICY
-}

 server_side_encryption_configuration {
     rule {
@@ -34,7 +33,7 @@ server_side_encryption_configuration {
       }
    }
  }
-
+}
```

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by sujith-siva** [comment]
ok thanks for the reply.
I was speaking to one of my friend and he said I have the server_side_encryption_configuration should be inside the bucket section and I have changed the code accordingly but still I am getting an error while running the plan.


Error: Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.backup: 1 error(s) occurred:

* aws_s3_bucket.backup: Error creating S3 bucket: InvalidArgument: 
	status code: 400, request id: E6F2496DA5632908043, host id: 1xwu8Cpr8WdYTGTYUyzYNWRp8YlpsfANLZnWIOcvzPBuG+a6LFI4MuytKzMSt2QnICt1ThcIh8=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by sujith-siva** [comment]
### S3 bucket for internal access only
### Test S3 bucket
resource "aws_s3_bucket" "backup" {
  bucket = "backup.test.com"
  acl	 = "priavte"

server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
   }
 }
}
resource "aws_s3_bucket_policy" "backup_test_policy" {
  bucket = "${aws_s3_bucket.backup.id}"
  
  
  

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "Backup-Internal-Access-Policy",
  "Statement": [
    {
      "Sid": "IPAllow",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::backup.test.com/*",
      "Condition": {
         "IpAddress": {"aws:SourceIp": "10.x.x.x/21"}
      }
    }
  ]
}
POLICY
}




resource "aws_s3_bucket_public_access_block" "public_access_block" {
  bucket = "${aws_s3_bucket.backup.id}"

  # Block new public ACLs and uploading public objects
  block_public_acls = true

  # Retroactively remove public access granted through public ACLs
  ignore_public_acls = true

  # Block new public bucket policies
  block_public_policy = true

  # Retroactivley block public and cross-account access if bucket has public policies
  restrict_public_buckets = true
}

**Comment by apparentlymart** [comment]
Hi @sujith-siva! Sorry for the weird AWS error there.

That particular issue is coming from the S3 API itself, rather than from Terraform, and so the folks who watch this repo (Terraform Core maintainers) are not the best to help with that. I'd suggest opening a new issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) to see if the AWS provider team can identify what is failing there, and possibly to improve that un-actionable error message in future releases.

**Comment by sujith-siva** [comment]
ok will do Martins.
Thanks for the response.
