### ISSUE TITLE
Data sources and Variable returning different values (interpolation)

### ISSUE THREAD

**Issue by marceloalmeida** [hashicorp/terraform#20259]
A data source is returning a different value of the same variable that he receives has input. I think that when the variable is processed by the data source are being interpolated

### Terraform Version
```
Terraform v0.11.11
+ provider.null v2.0.0
```

### Terraform Configuration Files
```hcl
variable "this" {
  type = "map"

  default = {
    a = true
    b = "true"
    c = false
    d = "false"
  }
}

data "null_data_source" "this" {
  inputs = "${var.this}"
}

output "data" {
  value = "${data.null_data_source.this.outputs}"
}

output "map" {
  value = "${var.this}"
}
```

### Expected Behavior
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data = {
  a = 1
  b = true
  c = 0
  d = false
}
map = {
  a = 1
  b = true
  c = 0
  d = false
}
```
### Actual Behavior
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data = {
  a = 1
  b = 1
  c = 0
  d = 0
}
map = {
  a = 1
  b = true
  c = 0
  d = false
}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @marceloalmeida! Sorry for this strange behavior.

I think you've recreated #13512 here. That issue has already been fixed in the master branch ready for inclusion in the forthcoming v0.12.0 release, so I'm going to close this out. You should be able to see this working as expected in the alpha4 release if you'd like to try it, but please don't use the alpha releases for any "real" infrastructure.
