### ISSUE TITLE
Terraform + SageMaker full support- Roadmap?

### ISSUE THREAD

**Issue by saritajoshi9389** [hashicorp/terraform#20262]
Hi there,

Do we have any roadmap for SageMaker integration with Terraform. Per https://github.com/terraform-providers/terraform-provider-aws/issues/2493, we only have it for the notebook instance and not modeling/hosting

**Comment by apparentlymart** [comment]
Hi @saritajoshi9389,

This repository is for Terraform Core, and so AWS features (aside from the S3 backend) are not developed here. The AWS provider's repository is a better place to ask that question, though it looks like terraform-providers/terraform-provider-aws#2493 is already covering your question.

Since SageMaker support requires no changes in this repository, I'm going to close this out.
