### ISSUE TITLE
Partial Configuration Swift backend not working

### ISSUE THREAD

**Issue by Leletir** [hashicorp/terraform#20277]
Hello,

I'm trying to use the partial configuration with swift backend, but impossible to make it works. Terraform still need credentials to use the object storage as a backend.

### Terraform Version

```
v0.11.11
provider.openstack v1.15.0
```

### Terraform Configuration Files

main.tf:

```hcl
data "terraform_remote_state" "foo" {
  backend = "swift" 
  config = {
    container = "${var.swift_container}"
    auth_url = "${var.swift_auth_url}"
    region_name = "${var.swift_region_name}"
  }
}
```

vars.tf
```hcl
variable "swift_container" {
    type = "string"
}
variable "swift_auth_url" {
    type = "string"
}

variable "swift_region_name" {
    type = "string"
}
```

### Debug Output

https://gist.github.com/Leletir/86d6ba1fe7259950d7dcd4c6b88c749a

### Expected Behavior

If I have understood the aim of partial configuration, terraform should retrieve this information and merge it. To me, I should not give again my credential to log in to my object storage.

### Steps to Reproduce

1. terraform init
```bash
terraform init -backend-config="container=terraform-tfstate-test-2" \
          -backend-config="auth_url=<my_auth_url>" \
          -backend-config="password=<my_pwd>" \
          -backend-config="user_name=<my_username>" \
          -backend-config="domain_name=<my_domain>" \
          -backend-config="region_name=<my_object_storage_region>" \
          -backend-config="tenant_name=<my_tenant_name>" \
          -backend-config="archive_container=terraform-tfstate-test-2-archive"
```

2. terraform apply

What do you guys think, is it a bug or I misunderstood the documentation ? 
Thank you for your help.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Swift backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
