### ISSUE TITLE
Add Additional Documentation for remote-exec

### ISSUE THREAD

**Issue by kmishra9** [hashicorp/terraform#20283]
Hey there,

I've been banging my head against the wall for days now while using remote-exec because of an issue with "getting locks" that I finally found solution to, which is documented [here](https://github.com/terraform-providers/terraform-provider-hcloud/issues/43). It would be _incredibly useful to know_  within the provisioner documentation (or potentially useful to integrate within Terraform itself) that sleeping for a few seconds before beginning the bulk of your provisioning can help avoid errors due to an instance starting up and getting set up.

**Comment by apparentlymart** [comment]
Hi @kmishra9! Thanks for requesting this.

I think "sleep for a few seconds" isn't general advice that we'd want to give here (indeed, if that _were_ true, I expect we'd just change the provisioner to always sleep), but I agree it would be helpful to say _something_ here about dependencies during startup.

I think the general issue that terraform-providers/terraform-provider-hcloud#43 is seeing is that on a modern Linux distribution the system daemons often come up concurrently and in an unpredictable order, and so it is possible for the SSH server to become ready to accept connections before the rest of the system has stabilized.

With that said, I think the general advice we could offer here is that the provisioner command will run very soon after the SSH daemon starts up, and so it's important to either ensure that the SSH daemon doesn't start up too soon (e.g. by carefully configuring its dependencies in `systemd`) or to include some sort of precondition command at the start of the script that blocks until the system is ready. That advice should generalize well for all sorts of different boot-ordering-related problems.

For the specific issue in terraform-providers/terraform-provider-hcloud#43 I assume something during the boot process is running `apt` -- perhaps to check if there are system updates available? -- and that is temporarily taking the lock at just the wrong time for the provisioner to try to run. Making the `ssh.service` depend on whatever unit is doing that would be the most robust solution there, rather than just trial-end-error choosing different amounts of sleep in order to guess a suitable time to run. However, that's a problem very specific to `apt` and I don't that we should be giving detailed advice on third-party software (which may change outside of our control over time) in Terraform's docs.

**Comment by kmishra9** [comment]
Yup, totally reasonable response. I would agree adding _something_ about the provisioner running very soon after the SSH daemon starts up (and that that can be configured by the user to customize when they want provisioners to run) is probably the best advice/documentation update to include.

I actually, just for some context, wasn't able to get my remote-exec provisioners working, even though I moved the provisioning away from the boot time process by creating the EC2 => attaching a volume => triggering a null resource to run provisioners and even having loops in the code that would wait until the locks unlocked. They just never did on their own (despite trying everything documented). Maybe that's something to do with my specific AMI or whatever but it just became easier to do it myself on the machine.

**Comment by apparentlymart** [comment]
Hi @kmishra9,

The Terraform provisioners concept is there as a sort of last-resort for situations where logging in and running commands is the only option (e.g. legacy base images that can't be modified, etc), but if possible it's usually more predictable and robust to use the EC2 `user_data` mechanism to pass data from Terraform into the EC2 instance. If your AMI includes `cloud-init` then you can put shell scripts directly in `user_data` to execute them on boot. This still requires careful thought about what order operations run in, since `cloud-init` itself runs during boot (and, indeed, often much sooner than the SSH server starts up), but at least startup actions this way will run at a more predictable time in the boot process.

Another unrelated advantage of `user_data` over provisioners is that it can survive an instance rebooting, because the `user_data` blob is saved inside EC2 at create time.

That is not to say that we won't make the documentation changes we've discussed here, but I just wanted to note that extra option and the fact that we recommend it over using provisioners in most cases. While we're updating the `remote-exec` docs as we already discussed I think we should also make sure we're clear about that recommendation directly on the `remote-exec` page.

**Comment by kmishra9** [comment]
Yup, that would be helpful as well -- I had no idea alternative mechanisms like that existed (let alone were recommended over provisioning).

**Comment by JKHeadley** [comment]
For an alternative approach in my case it seemed cleaner to use a `user_data` script to just reboot the EC2.  My provisioner was set to run after the EC2 instance was created so it just continued to try to connect via ssh until the EC2 had rebooted. Once it connected all the commands ran clean.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence on this one.

Over the years we've seen folks run into various confusing and complex problems using provisioners, and that led us to the conclusion that this idea of automatically logging in to a freshly-booted system over the network and trying to run commands against it has so many tricky hurdles to overcome that it would be better to suggest alternatives rather than to continue to write out increasingly complicated (and always very context-specific) advice about the provisioner model.

That is what ultimately led to us publishing the documentation section [Provisioners are a Last Resort](https://www.terraform.io/docs/language/resources/provisioners/syntax.html#provisioners-are-a-last-resort), which aims to cover some of the main reasons we see folks try to use provisioners and suggest some better alternatives that cooperate better with the design of the various cloud compute systems, and avoid dealing with hard-to-debug concerns like automatically issuing SSH keys for authentication, or trying to orchestrate correct order of operations during boot.

Along with this, the new HashiCorp Learn system (which wasn't created yet when I last posted) includes some more tutorial-style content on provisioning compute resources, in the section [Provision Infrastructure](https://learn.hashicorp.com/collections/terraform/provision). At the time I'm writing this there are two good tutorials on some commonly-available alternatives to provisioners: making custom "ready to run" machine images using HashiCorp Packer, and using the third-party software cloud-init to perform image customization tasks during the first boot of a new virtual machine.

For the specific issue we were discussing here, about interactions between different boot-time operations, I'd recommend the cloud-init tutorial in particular as the best alternative because cloud-init allows for much more precise control over when in the boot process each operation will occur, and doesn't require you to have an SSH daemon running at all because it obtains its configuration via user-data/meta-data mechanisms built in to each supported cloud compute platform.

Given all of that, I'm going to belatedly close this issue now. While we've not written documentation of exactly the kind I originally had in mind when I commented before, I think what's currently documented is _better_ advice and should hopefully help folks avoid some of the troubles we saw in that other issue. If you have any questions or concerns after reading the guides and documentation sections I mentioned here, please do open a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core) (_also_ new since my last comment) where we can work through specific problems and, for problems that come up frequently, consider what new advice we might add to the documentation. Thanks!
