### ISSUE TITLE
salt masterless provisioner cannot be run more than once

### ISSUE THREAD

**Issue by azban** [hashicorp/terraform#20323]
### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
resource "null_resource" "provisioner" {
  provisioner "salt-masterless" {
    local_state_tree = "${path.root}/../../salt/srv/salt"
    local_pillar_roots = "${path.root}/../../salt/srv/pillar"
    minion_config_file = "${path.root}/../../salt/etc/salt/studio-minion-${terraform.workspace}"
    log_level = "warning"
    connection = {
      host = "${aws_instance.main.public_ip}"
      type = "ssh"
      user = "ubuntu"
      # requires near-prod.pem to be symlinked
      # into top level of ops
      private_key = "${file("${path.root}/../../near-prod.pem")}"
    }
  }
}
```

### Debug Output
```
null_resource.provisioner (salt-masterless): Uploading local state tree: /home/azban/near/ops/studio/terraform/../../salt/srv/salt
null_resource.provisioner (salt-masterless): Creating directory: /tmp/salt/states
null_resource.provisioner (salt-masterless): Removing directory: /srv/salt

Error: Error applying plan:

1 error(s) occurred:

* null_resource.provisioner: Unable to clear salt tree: error executing "rm -rf '/srv/salt'": Process exited with status 1
```

### Expected Behavior
The provisioner should be able to run more than once. These files were moved with sudo and thus need to be removed with sudo.

### Actual Behavior
The provisioner fails on subsequent runs because it doesn't have permission to remove dirs it created previously with sudo.

### Steps to Reproduce
1. add salt-masterless provisioner in null resource to config
2. apply
3. taint provisioner resource
4. apply

### Workaround
Adding the following provisioner block unblocked me
```HCL
  provisioner "remote-exec" {
    inline = [
      "sudo rm -rf /srv/salt /srv/pillar",
    ]
    connection = {
      host = "${aws_instance.main.public_ip}"
      type = "ssh"
      user = "ubuntu"
      # requires near-prod.pem to be symlinked
      # into top level of ops
      private_key = "${file("${path.root}/../../near-prod.pem")}"
    }
  }
```

**Comment by azban** [comment]
[this](https://github.com/azban/terraform/pull/new/azb-salt-remove-dir-fix) fixes the issue, but unsure how to test

**Comment by denis-kalinin** [comment]
To overcome that I delete files on the remote host just before salt-masterless:
```
provisioner "remote-exec" {
        inline = [
            "sudo rm -rf /srv/salt",
            "sudo rm -rf /srv/pillar"
        ]
}
provisioner "salt-masterless" {}
```

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested.

For the time being, the best option if you want to see this built, is to build a standalone provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. 

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
