### ISSUE TITLE
Git clone to branch fails for Git in Azure DevOps

### ISSUE THREAD

**Issue by ystrte** [hashicorp/terraform#20358]
### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
module "splunkstorage" {
  source                = "git::ssh://git@vs-ssh.visualstudio.com/v3/test/test/tfmodules//storage?ref=mybranch"
}
```

### Expected Behavior
Load the module from the active branch 

### Actual Behavior
Loads the module in the master branch

### Steps to Reproduce
1. `terraform init`

### References

- #18869

**Comment by Dilergore** [comment]
Hey,

I am kinda struggling with the same. I am reluctant to use the SSH key approach since those are bound to users and I don't think it is a good idea to use user based auth for automation purposes.

Basically I've read through all the issues related to this and similar problems and I was unable to find a proper response...

Any idea how to do this properly from/inside Azure DevOps Repos and Pipelines?

**Comment by Dilergore** [comment]
Also according to several forum posts and documentation it should be possible to use PATs like:
https://{ADDPATHERE}@dev.azure.com/orgname/projectname/_git/reponame

But sadly it is not possible to use variables in the source param of modules. Adding the PAT to the code is not an approach which is okay from the security perspective....

**Comment by jsburckhardt** [comment]
Hi guys, i had this issue today and fixed as follows:
In the TF resources I called the modules:
``` 
source = git::https://<AzDOorganization>@dev.azure.com/<AzDOorganization>/<Project>/_git/<GitRepoWithTheModules>//<DirectoryWithMyModule>?ref=<branch>
example:
source             = git::https://myorg@dev.azure.com/myorg/theproject/_git/terraform_modules//key-vault/policy?ref=feat/adding-kv-policy
```
Then in the build pipeline I enable access to the system token
```
steps:
- checkout: self
  persistCredentials: true
```
Don't forget to include the clean up step
```
steps:
- checkout: self
  clean: true
```
Now that I have access to the token, I'll need to use it in the tf steps. Since the TF task is not smart enough to use $(System.AccessToken) variable, I do a simple search replace in all .tf files as a script task before running TF tasks
```
steps:
- bash: |
   echo replacing creds for modules
   cd <directory you want to work in - or update the find . to search in all directories>
   find . -type f -name '*.tf' -exec sed -i "s~git::https://<AzDOorganization>~git::https://<AzDOorganization>:$AZURE_DEVOPS_PAT~g" {} \;
  displayName: 'Bash Script'
  env:
    AZURE_DEVOPS_PAT: $(System.AccessToken)
```

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
