### ISSUE TITLE
undefined in svchost.go

### ISSUE THREAD

**Issue by hiscal2015** [hashicorp/terraform#20354]
I'm using dep for dependency management, when doing go build, it reports below errors:

```
# github.com/terraform-providers/terraform-provider-myprovider/vendor/github.com/hashicorp/terraform/svchost
go/src/github.com/terraform-providers/terraform-provider-myprovider/vendor/github.com/hashicorp/terraform/svchost/svchost.go:38:22: undefined: idna.New
go/src/github.com/terraform-providers/terraform-provider-myprovider/vendor/github.com/hashicorp/terraform/svchost/svchost.go:39:2: undefined: idna.MapForLookup
go/src/github.com/terraform-providers/terraform-provider-myprovider/vendor/github.com/hashicorp/terraform/svchost/svchost.go:40:2: undefined: idna.Transitional
go/src/github.com/terraform-providers/terraform-provider-myprovider/vendor/github.com/hashicorp/terraform/svchost/svchost.go:131:17: undefined: idna.Lookup
go/src/github.com/terraform-providers/terraform-provider-myprovider/vendor/github.com/hashicorp/terraform/svchost/svchost.go:155:17: undefined: idna.Lookup
```

Gopkg.toml:
```
[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"
```

Please help, thanks

**Comment by apparentlymart** [comment]
Hi @hiscal2015,

I'm not sure what's going on there. `idna` here is [`golang.org/x/net/idna`](https://godoc.org/golang.org/x/net/idna), which has the functions mentioned in those error messages. My only idea is that perhaps you have vendored an older version of that package that doesn't include those functions, but it seems unlikely that there would be a version of this package that lacked function `New`, so that is quite baffling.

With that said, I'm more surprised that provider code would be importing this package at all. Provider code should be importing only the packages under `github.com/hashicorp/terraform/helper`, and so the `svchost` package shouldn't be built at all. I assume it's getting dragged in due to some of the transitive dependencies the SDK has on the `github.com/hashicorp/terraform/terraform` package, which is unfortunate. We are planning to better separate the plugin SDK from Terraform Core in a future release to avoid this sort of "dependency contamination".

**Comment by hiscal2015** [comment]
changed to go module now issue disappeared.
