### ISSUE TITLE
How not to destroy parent module

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#2035]
I have two templates "global" and "service". Global setups up, well, global stuff - creates VPC, route table tc. And I have "service" which sets up subnets, security groups, IAM roles for concrete service.

Folder structure is like this:

```
global
   global.tf
service
   service.tf
```

Then global is included as module inside service.tf and some outputs are used - vpc id, routing table id etc.

The problem now is that when I destroy service with `terraform destroy` it also destroys whole global environment. And when I try to create new service (by removing tfstate file, so it's not related to first service) then it creates new global environment. 

What I would like to have is a single global template, which creates stuff once and never duplicates it or something else. And service templates, that can be used to easily roll out resources for new service inside global environment.

How do I do this kind of dependency with terraform?

**Comment by mikeyhill** [comment]
Why not have all in a single file and use the target= instead?  I do the same thing, basically setup my VPC, NAT and various 'global' elements and then I have things like admin instances (subnets, roles) db instances etc... that are constantly being modified.  This method so-far has worked well for me with the target.  I'm curious to hear other ideas though since this was just the one I decided to go with.

**Comment by Fodoj** [comment]
I've did it another way around: there is a service module, and inside global template all required new services are attached using module resource. Basically switched from "global module included in service template" to "service modules included in global template". 

Quiet satisfied with this setup now, I think also makes usage of target easier. Closing the issue. Thanks for support!
