### ISSUE TITLE
Terraform cannot create lock on NFS

### ISSUE THREAD

**Issue by sedwards58** [hashicorp/terraform#20373]
### Terraform Version

```
Terraform v0.11.11
...
```

### Terraform Configuration Files

```hcl
I don't think the error is dependent on my config.
...
```

### Debug Output

https://gist.github.com/sedwards58/ef6f1e86e88374cfdecbb205d2ecb286

### Expected Behavior

'terraform init' should succeed.

### Actual Behavior

Terraform fails with:

Error locking state: Error acquiring the state lock: 2 error(s) occurred:

* no locks available
* open .terraform/.terraform.tfstate.lock.info: no such file or directory

Terraform acquires a state lock to protect the state from being written

### Steps to Reproduce

1) Copy your project directory to an NFS volume.
2) `terraform init`
3) Note that 'init' fails.
4) Copy your project directory to /tmp/
5) `terraform init`
6) Note that 'init' succeeds.
### Additional Context

) Both the workstation and the file server are running Lubuntu 18.10.
) The file server is running ZFS 0.7.5-1ubuntu16.4. (This is the version installed with L18.10.)
) The workstation mounts the NFS share like:
mount | grep /source/
fs10:/source/ on /source type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.0.57,mountvers=3,mountport=54355,mountproto=udp,local_lock=none,addr=192.168.0.57)

**Comment by jbardin** [comment]
Hi @sedwards58,

Sorry you're having difficulty with this. It looks like you're using NFS3, which doesn't support locking without an NLM server handling the sideband protocol. Even if you had locking enabled, support is difficult and the combination of NFS3 and ZFS is quite unusual, so there may be other complications.

Due to the limited support for locking over NFS in general, and the multitude of configurations which may change how locking support is implemented, locking over NFS is only done on a best effort basis. Also, since posix locks are often only advisory, attempting to use them over a networked filesystem is not a guarantee of safety. If you must have the working directory for Terraform on an NFS mounted volume that doesn't support locking you will need to use the `-lock=false` CLI option.
