### ISSUE TITLE
Error: Error asking for user input when adding tag to aws_ebs_volume

### ISSUE THREAD

**Issue by stefano-cherchi** [hashicorp/terraform#20384]
Terraform returns the following error while adding a tag to a resource of type "aws_ebs_volume" if the tag references an attribute of a resource of type "aws_ebs_volume_attachment"

    Error: Error asking for user input: 1 error(s) occurred:

    * Cycle: aws_ebs_volume.opt, aws_volume_attachment.opt_attachment

All other tags referencing attributes of other resource types are added to the volume without errors

### Terraform Version

    $ terraform --version
    Terraform v0.11.11
    + provider.aws v1.57.0

### Terraform Configuration Files

instances.tf 
```

resource "aws_instance" "frontend" {
  ami   = "${var.ami}"
  instance_type = "${var.instance_type["frontend"]}"

  [...]

  tags = "${merge(local.common_tags,
    map(
      "Name", "${local.name}-frontend${count.index+1}",
      "Role", "frontend",
    )
  )}"
  count = "${var.instance_count["frontend"]}"
}

resource "aws_ebs_volume" "opt" {
  availability_zone = "${aws_instance.frontend.*.availability_zone[count.index]}"
  size = 200
  tags = "${merge(local.common_tags,
    map(
      "Name", "${local.name}-frontend${count.index+1}",
      "instance_id", "${aws_instance.frontend.*.id[count.index]}",
      "device", "${aws_volume_attachment.opt_attachment.*.device_name[count.index]}",
    )
  )}"
  count = "${aws_instance.frontend.count}"
}
resource "aws_volume_attachment" "opt_attachment" {
  device_name = "/dev/xvdb"
  volume_id   = "${aws_ebs_volume.opt.*.id[count.index]}"
  instance_id = "${aws_instance.frontend.*.id[count.index]}"
  count = "${aws_instance.frontend.count}"
}
```

If the row 

      "device", "${aws_volume_attachment.opt_attachment.*.device_name[count.index]}",

is removed, terraform plan executes with no errors

### Expected Behavior

Terraform plan should complete with no errors, produce an output similar to the following

```
Terraform will perform the following actions:

  ~ aws_ebs_volume.opt
      tags.%:           "8" => "9"
      tags.device:      "" => "/dev/xvdb"
```

### Actual Behavior

$ terraform plan

```
Error: Error asking for user input: 1 error(s) occurred:

* Cycle: aws_volume_attachment.opt_attachment, aws_ebs_volume.opt

```

### Steps to Reproduce

1. terraform plan

**Comment by mildwonkey** [comment]
Hi @stefano-cherchi ,
I'm sorry you've come across this unexpected behavior.

I think the problem lies in the order of operations. The error message isn't clear at all (much-needed enhancements to error messages [coming with the 0.12 release](https://www.hashicorp.com/blog/terraform-0-12-reliable-json-syntax)), but our hint was the word "cycle".  The `aws_ebs_volume` must be created before the `aws_volume_attachment` is created, but you're trying to tag the volume with information from the attachment. This is causing a cyclical dependency, where the volume depends on the attachment, which depends on the volume.

In this example you could hard code the device_name tag to `"/dev/xvdb"` but I presume your actual configuration is more complicated. If your `device` tag is a hard requirement, you may need to restructure your configuration to allow for hard-coding of the device name (for example, having one block for `/dev/xvdb` volumes, another for `/dev/somethingelse`, etc). 

I hope this helps!

**Comment by stefano-cherchi** [comment]
Hi @mildwonkey, 

thank you for the hint. I should have added, though, that both the ``aws_ebs_volume`` and the ``aws_volume_attachment`` already exist and the volume has already tags. 

Does this change your analysis?

**Comment by mildwonkey** [comment]
Unfortunately not. It's still a cyclical dependency, so terraform cannot build the dependency graph properly. You will need to find a way to refactor this configuration so you do not have the cyclical dependency between `aws_ebs_volume` and `aws_volume_attachment`.

**Comment by mildwonkey** [comment]
I'm going to close this due to inactivity - if you have any further questions, I recommend [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help. Cheers!
