### ISSUE TITLE
deps for v0.5.1 are missing

### ISSUE THREAD

**Issue by swills** [hashicorp/terraform#2040]
deps/v0-5-0.json is present, but v0-5-1.json is not.

**Comment by catsby** [comment]
We had a slight mishap with the release of 0.5.1, we'll get the deps recorded for the next release :smile:

**Comment by swills** [comment]
Ok, but if you could at least go ahead and commit them to the repo, that would help.

**Comment by phinze** [comment]
@swills unfortunately it's non-trivial to reconstruct them after the fact if they're not captured. all of the dependencies have had a few days of development since then, so we'd have to go figure out the SHAs from release time from each dep.

We'll likely be cutting an 0.5.3 tomorrow, for which I will make sure we capture the deps.

**Comment by swills** [comment]
Ok, thanks for the update. BTW, have you considered using godep and committing the deps to the git repo?

**Comment by phinze** [comment]
Indeed we have. It's still somewhat up in the air, but we're actively talking about it. I'm hoping we'll nail down a dep mgmt strategy within the next few months.
