### ISSUE TITLE
extend a module to add more outputs?

### ISSUE THREAD

**Issue by Rohithzr** [hashicorp/terraform#20412]
So I have a terraform script that uses a module from a git repo. It only has 3 outputs defined at the source. 
I want to access more information which I *can* output with `terraform output --module=dcos.dcos-infrastructure` but *cannot* access in the terraform script itself.

```
...
module "dcos" {
  source  = "dcos-terraform/dcos/aws"
  version = "~> 0.1"
...
}
...
// i'd like to use module.dcos.dcos-infrastructure.dcos-vpc.id in this tf script
```

**Comment by jbardin** [comment]
Hi @Rohithzr,

Sorry about the misleading output here. The `terraform output` command is reading some outputs directly from within the state from other modules imported by your `dcos` module. In the next release this will return an error like

```
error: Unsupported option

The -module option is no longer supported since Terraform 0.12, because now
only root outputs are persisted in the state.
```

If you want the output at the top level, then you need to modify the module source in order to add outputs to the configuration. In general, we recommend controlling the source of the modules for your own infrastructure. You can fork the module source and add the outputs you need, or submit a PR to the module developers.

**Comment by Rohithzr** [comment]
@jbardin thanks for clarifying this. I will fork then.
