### ISSUE TITLE
Terraform get stuck during a remote_exec call

### ISSUE THREAD

**Issue by ashfondu** [hashicorp/terraform#20436]
I am using Terraform to deploy a VM in azure and then run a remote_exec call to install docker. The installation always hang during the remote exec call. please see image for details. Every once in a while if i close this window and do another tf>plan>apply it seems to complete without issues. But always fails if i am starting from scratch. I have even tried moving the scripto a sh file and running it remotely but it runs into the same issue.

![image](https://user-images.githubusercontent.com/34550337/53263740-2033ce00-368f-11e9-9e08-8f85b9350621.png)

**Comment by danieldreier** [comment]
@ashfondu I apologize for the long wait for a response here. Are you still seeing this issue in Terraform 0.13.x or the 0.14 alpha releases?

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
