### ISSUE TITLE
remote state in 0.12 alpha 4 not working

### ISSUE THREAD

**Issue by suared** [hashicorp/terraform#20442]
### Terraform Version
```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
+ provider.aws v1.40.0-6-gb23683732-dev
...
```

### Terraform Configuration Files
```
# Note:  without the = after "config", I was getting a syntax error in the alpha4 whereas previous version worked fine.  Added the =, if that is the error need to know how to get through syntax check.  This might be the root cause if alternate approach for this syntax in this version

data "terraform_remote_state" "core_infra_dev" {
  backend = "local"

  config = {
    path = var.core_infra_state_filepath
  }
}

...
```

### Crash Output
not crashed, just saying there are no outputs in state though I can see them when I vi the state file in both plan from other folder as well as when using terraform output.

### Expected Behavior
I should have been able to reference the output variables.  This is a resource which is the primary reason I was planning to use this alpha version in the interim to save some typing

### Actual Behavior
It cannot see the outputs

### Steps to Reproduce
I created an API gateway as part of core infrastructure project in a separate directory.  All went well, outputs listed and appear in state file.

I try to reference the created resource in a separate project directory using the full path name in the resource state (see example terraform output shown above), same as the variable referenced.  Outcome is there are no outputs defined in state.

### Additional Context
nothing special, all running on local machine

### References
* None - other than the one saying the feature to reference a resource is now available
* Snippets of Vi of the state file showing the outputs here:
 - line 6:    "outputs": {
    "api_dns": {
      "value": {
        "alias": [
          {.... lots of data
 - line 105:     "api_gw": {
      "value": {
        "api_key_source": "HEADER",
        "binary_media_types": null,
        "body": null,
        "created_date": "2019-02-22T16:17:18Z",
        "description": "Terraform Primary API Gateway for all REST APIs.  Any recreate of this gateway will require updates of children Terraforms",

**Comment by suared** [comment]
Noticed my wording wasn't great on the crash section.  Clarifying here.  terraform output and the plan are saying the output is not there.  If I vi the state file I can see it.  Nothing in trace file appears off.  If there are any other ways to troubleshoot I am happy to try alternate approaches.

**Comment by suared** [comment]
If it helps, I ran terraform output from same directory and it does show the variable.  If I run it from the other directory with the -state flag it shows it as well.

**Comment by apparentlymart** [comment]
Hi @suared,

The alpha4 build is very old at this point, so I'd like to confirm that the behavior you are seeing is still present in a recent version. We have uploaded [some snapshot builds](http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/) that reflect the state of things in the Terraform master branch as of last Friday.

If you wouldn't mind, it would be helpful to see how this behaves with [last week's Terraform Core release](http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/terraform/0.12.0-dev20190216H00/). The `terraform` provider is built in, so you don't need to download any other archives to test that, but if you are using any other providers in your configuration you'll need to also update with the provider releases in the snapshots bucket because the alpha4 providers are no longer compatible.

It sounds like you're working with an existing configuration here for your testing, in which case you could also try using the `terraform 0.12upgrade` command to save you from manual updates. It's not 100% complete in the snapshots, but most of the functionality is in place, so it should be able to do a lot of the work for you in updating.

With that said, I'd suggest the following:

* Delete the `.terraform` subdirectory of the directory where you are testing, to ensure a clean working directory.
* Reset any changes you've made manually to configuration to how you had them before trying to use 0.12-alpha4.
* Download the snapshot build of Terraform along with any other providers you are using in this configuration and place them in the directory where you previously installed v0.12.0-alpha4, making sure you don't have any alpha4 providers still present.
* In the configuration directory you are trying, run:
  * `terraform init` to check that all of the necessary providers are present and prepare the directory.
  * `terraform 0.12upgrade` to see what changes to your configuration it proposes.
  * Use `git diff` (or similar, if you are using a different VCS) to review the changes the upgrade tool made.
  * If it looks good, try `terraform plan` to see if it works.

**Comment by suared** [comment]
Thank you for the response!  Will try the above, coincidentally I just found a work around.  If I include "outputs" in the references like below it works which I am sure is not intended.  See below how the "outputs" keyword is needed after the remote state reference in the current alpha4.  Will do above and share outcome shortly:
  rest_api_id = data.terraform_remote_state.core_infra_dev.outputs.api_gw.id
  parent_id   = data.terraform_remote_state.core_infra_dev.outputs.api_gw.root_resource_id

**Comment by apparentlymart** [comment]
Ahh, thanks for following up @suared! If you try what I suggested previously you should find that the upgrade tool will make that adjustment automatically, to add the extra `.outputs` attribute that is now needed in Terraform 0.12.

**Comment by suared** [comment]
ahh... so it is required!  I just used the latest and yes, still required.  I assumed it wouldn't be incorrectly since it is supposed to point to the outputs.  I guess this ticket can be closed.  Thanks a ton for the help!!!

**Comment by apparentlymart** [comment]
Great, thanks for confirming @suared!

The reason for this change is to allow the attributes to be used like a single map value rather than only as separate attributes, in situations where that makes sense:

```hcl
output "settings" {
  value = terraform_remote_state.settings.outputs
}
```

Exporting the whole mapping of outputs together won't always be the right answer, but we wanted to make it possible to do that without exporting the remote state data source object as a whole, or use the mapping in other expressions elsewhere in the configuration.
