### ISSUE TITLE
self.count.index interpolation not available within provisioners.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#2044]
```
* 1 error(s) occurred:

* Resource 'aws_instance.consul.1' does not have attribute 'count.index' for variable 'aws_instance.consul.1.count.index'
```

**Comment by phinze** [comment]
Can you share the config you're using? I'm pretty sure just plain old unprefixed `count.index` should work inside provisioners.

**Comment by c4milo** [comment]
yes, without the `self` prefix it worked fine. However, it is sort of unexpected as the documentation says otherwise regarding referring to the resource's own attributes from provisioners.

**Comment by phinze** [comment]
I took a quick look at the docs to try and make this clearer, but I couldn't figure out what would be helpful to add:

https://github.com/hashicorp/terraform/blob/master/website/source/docs/configuration/interpolation.html.md

Originally I was going to add something like "note: count.index is not a self variable", but it seemed a little redundant since "To reference count information" shows up just below.

I'm going to close this for now, but feel free to follow up with a docs PR if you can see a way to clarify this better! :+1:
