### ISSUE TITLE
Referencing modules output variables across independent terraform directories

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#20469]
Is it possible  to have a directory structure like the following:

    ├── environments
    │   └── production
    │       ├── app1 (own Terraform state)
    │           ├── instances.tf
    │       ├── app2 (own Terraform state)
    │           ├── instances.tf
    │       └── shared (own Terraform state)
    │           ├── iam.tf
    │           └── security_groups.tf
    └── modules
        └── iam
        └── node

Where `environments/production/{app1, app2, shared}` all each have their own Terraform state and each are independent of each other. However, from app1 and app2 I need to reference module output variables like security groups, IAM etc from shared.

So `environments/production/shared/iam.tf` looks like:

    module "iam" {
        source = "../../../modules/iam"
        var1 = "foo"
        var2 = "bar"
        var3 = "car"
        var4 = "nar"
    }

How then, from `app1`, or `app2` do I reference the instance of `iam` from `shared`?

`environments/production/app1/instances.tf`:

    module "app1" {
        source = "../../../modules/node"
        iam_profile_id = { how do I reference the IAM module from shared here? }
        // shared.module.iam.profile_id?
    }

**Comment by mildwonkey** [comment]
Hi @nodesocket !
What you are trying is indeed possible. To access a resource attribute from a module, need to configure an `output` in the module. You can see our documentation on module outputs [here](https://www.terraform.io/docs/modules/usage.html#outputs).

Here's a short pseudo-code (because I'm guessing at resource names) version:

In your module:
```
output "profile_id": {
  value = "${iam_profile.id}"
}
```


In `app1`:
```
module "app1" {
 iam_profile_id = $"{module.iam.profile_id}"
}
```


Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by nodesocket** [comment]
@mildwonkey I appreciate the response, but I know how to reference a module output variable. The question is how to reference a module output variable from a completely separate Terraform base directory/project with its own state?

**Comment by mildwonkey** [comment]
I'm sorry @nodesocket, I should have read more carefully. You can use the `terraform_remote_state` datasource to access outputs from different states:
https://www.terraform.io/docs/providers/terraform/d/remote_state.html

**Comment by nodesocket** [comment]
@mildwonkey thanks again. It seems only root level exported outputs can be used, not module level outputs[1]. That is unfortunate. Might make more sense to use data source to dynamically pull values from the provider instead of trying to reach into other Terraform projects and state.

[1] https://www.terraform.io/docs/providers/terraform/d/remote_state.html#root-outputs-only

**Comment by mildwonkey** [comment]
I'm going to close this due to inactivity - if you have any further questions, I recommend the [community forum](https://discuss.hashicorp.com/c/terraform-core), and of course if you have a bug or feature request please open another Github issue and fill out the template.  Thanks!
