### ISSUE TITLE
How to include all resource parameters in plan output?

### ISSUE THREAD

**Issue by whage** [hashicorp/terraform#20475]
Is it possible to get not just the changed attributes (the "delta") of resources in `terraform plan`'s output, but all the other attributes as well?

The use case would be validating resource parameters. Sometimes knowing just the changed ones are not sufficient for validation.

**Comment by mildwonkey** [comment]
Hi @whage!

There currently isn't any way to get all of the attributes for a given resource during `terraform plan`. You can compare the output of `terraform state show $resource` to the plan output, but I will admit that's pretty awkward. 

The terraform 0.12 (release date TBD) includes a new output format for `terraform show $planfile`: `terraform show -json $planfile`. The output of this command will include the entire planned state - not just resources or attributes being changed.

Our website documentation won't be updated until terraform 0.12 releases, but if you're interested in looking at it right now, it's [here in github](https://github.com/hashicorp/terraform/blob/master/website/docs/commands/show.html.markdown).

You can download one of our [dev snapshots](http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/) if you'd like to run the command yourself, but please do not use the snapshots with any real production infrastructure. 

Since this feature is available now in master, I'm going to close this issue. Thanks!
