### ISSUE TITLE
v0.12: Division computation results in floating point value for indices

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20496]
### Terraform Version

```
Terraform v0.12.0-dev
```

### Terraform Configuration Files

```hcl
instance_id     = "${oci_core_instance.TFInstance.*.id[count.index / var.NumParavirtualizedVolumesPerInstance]}"
```

### Debug Output

```
Error: Invalid index

  on block.tf line 15, in resource "oci_core_volume_attachment" "TFBlockAttach":
  15:   instance_id     = "${oci_core_instance.TFInstance.*.id[count.index / var.NumIscsiVolumesPerInstance]}"
    |----------------
    | count.index is 5
    | oci_core_instance.TFInstance is tuple with 3 elements
    | var.NumIscsiVolumesPerInstance is "2"

The given key does not identify an element in this collection value.
```

### Expected Behavior

In v0.11 this would have succeeded because the result of the division was a valid integer index.

### Actual Behavior

In v0.12 this division within the index value results in a floating point value.

### Steps to Reproduce

Run `terraform plan`

### Additional Context

Adding further context from @apparentlymart 

For the second of these, I think the problem is something different: 5 divided by 2 is 2.5, which is indeed not not a valid index into that list. Terraform 0.11 had a tendency to prefer to convert variable values to integers and thus perform integer division in most cases, but Terraform 0.12 now always does floating point division, requiring explicit rounding down if that is desired, like this:

```terraform
instance_id     = "${oci_core_instance.TFInstance.*.id[floor(count.index / var.NumParavirtualizedVolumesPerInstance)]}"
```

Due to our principle of "explicit is better than implicit", I think we'd instead change this to return a more specific error message if you try to index a list with a number that isn't whole, to guide the user to adding the explicit `floor` in this situation, and thus make the resulting configuration explicit about what mode of rounding is happening. (As much as possible, we try to design the language so that even people who aren't experts on Terraform can correctly guess what an expression is doing, by using familiar constructs and minimizing implicit behaviors.)

We did have this on our list of things the upgrade tool might check for, though indeed it would need to be contextual, such as applying the rule only in indexing brackets so we can assume that integer rounding was being relied on in the old configuration. We'll see during the beta process how common this situation is and thus whether it warrants automatic upgrading or whether we can just rely on a more actionable error message about it.

### References

This is a spin-off of comment on this bug:
https://github.com/hashicorp/terraform/issues/20200#issuecomment-467670961

**Comment by paultyng** [comment]
This should be something in the upgrade tool.

**Comment by apparentlymart** [comment]
We've now added a section to the upgrade guide about this and made HCL return a more specific error message when it's asked to index a list with a non-integer number.

Addressing this in the upgrade tool seems pretty complicated, so for the moment we're going to prioritize other work for v0.12.0 and lean on this new error message plus the upgrade guide to help users update their configurations for this situation. So far it seems like the problem is relatively rare, and most commonly occurs in indexing operations where our new error message will diagnose it. If the remaining pre-release cycles suggest that this problem is more pronounced than we currently suspect or commonly arises in some situation _other than_ indexing then we may revisit that decision, but for now we think it's better to focus on the other remaining v0.12.0 blockers, and rely on the error message and upgrade guide for migration purposes.
