### ISSUE TITLE
terraform destroy with target remove output on another modules

### ISSUE THREAD

**Issue by sebglon** [hashicorp/terraform#20493]
### Terraform Version

```
$ terraform version
Terraform v0.11.11
+ provider.google v2.0.0
```

### Terraform Configuration Files

```hcl
module "module1" {
  source                       = "./module1"

  gcloud_project_name          = "akecld-sgl-test"
  gcloud_region                = "europe-west1"
}

module "module2-1" {
  source                       = "./module2"
  gcloud_project_name          = "${module.module1.gcloud_project_name}"
  gcloud_region                = "${module.module1.gcloud_region}"
  prefix = "module2-1"
}

module "module2-2" {
  source                       = "./module2"
  gcloud_project_name          = "${module.module1.gcloud_project_name}"
  gcloud_region                = "${module.module1.gcloud_region}"
  prefix = "module2-2"
}

module "module2-3" {
  source                       = "./module2"
  gcloud_project_name          = "${module.module1.gcloud_project_name}"
  gcloud_region                = "${module.module1.gcloud_region}"
  prefix = "module2-3"
}

```

### Debug Output

https://gist.github.com/sebglon/b588bb8ece6c48f0c4de1732e84caf62
At line 1272, we cahnsho `  module.module1.output.gcloud_project_name (destroy) - *terraform.NodeDestroyableOutput`

The question is why terraform destroy this resources, when the target destroy is not on this module?

### Crash Output

```
$ terraform output -module=module1 gcloud_project_name
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the 
`terraform console` command to assist.
```

### Expected Behavior

Terraform can output the value

### Actual Behavior

Terraform can't output the value

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform output -module=module1 gcloud_project_name`
4. `terraform destroy --target module.module2-2`
5. `terraform output -module=module1 gcloud_project_name`

**Comment by jbardin** [comment]
Hi @sebglon,

Sorry you're having an issue here. Without the module source I can't say for sure, and the logs posted here are missing pieces that make it hard to discern what's happening exactly. 

It is possible that the output reference is being picked up erroneously in the targeted destroy. Module outputs should not be important, and will be recomputed on the next apply. In 0.12, module outputs are removed entirely (except the root module for remote state applications), and not persisted in the state. Running this command with 0.12 will show;

```
$ terraform output -module=module1 gcloud_project_name

Error: Unsupported option

The -module option is no longer supported since Terraform 0.12, because now
only root outputs are persisted in the state.
```

Closing this for now, since this behavior can't happen in the current master branch.
