### ISSUE TITLE
fork/exec /var/jenkins_home/workspace/deploy-infra/.ctx/terraform/.terraform/plugins/linux_amd64/terraform-provider-aws_v1.60.0_x4: permission denied

### ISSUE THREAD

**Issue by tinder-jlee** [hashicorp/terraform#20500]
### Terraform Version

```
Terraform v0.11.11
```

### Crash Output

Error: Error asking for user input: 1 error(s) occurred:

* provider.aws: fork/exec /var/jenkins_home/workspace/deploy-infra/.ctx/terraform/.terraform/plugins/linux_amd64/terraform-provider-aws_v1.60.0_x4: permission denied

### Steps to Reproduce

1. Create a docker container that has terraform installed. Also create a volume created for that container.
2. Create a regular user in the Dockerfile (not root user) and set as the default user.
3. SSH into the docker container, and create a set of terraform configuration files in the directory on the bound volume.
4. run: terraform init && terraform apply

### Additional Context

It was working fine until yesterday morning, but somehow something has changed in the logic (i think it's related to the provider version upgrade?) that caused this problem.
Due to this issue, the whole automation pipeline for deploying infrastructure has stopped. Please take a look at the issue ASAP.

### References

https://github.com/hashicorp/terraform/issues/15909
https://github.com/hashicorp/terraform/issues/16756

**Comment by apparentlymart** [comment]
Hi @tinder-jlee,

Based on the error message, it seems like the provider plugin executable file does not have the executable mode set.

Fixing this _could_ just be a matter of changing the mode of the file (`chmod a+x ...`) if the mode was just mis-set during the upgrade, perhaps. Could also be that the file is owned by the user that installed it, rather than the regular user you created, and the executable mode is set only for the owner.

If the mode looks right then I'd look into other possibililties such as whether the `.terraform` directory is on a filesystem that is mounted with the `noexec` flag set, causing all executable permissions to be forced off.

**Comment by tinder-jlee** [comment]
@apparentlymart thanks a lot for suggestion. yeah that was the first work-around we took, and it worked.
but after further investigation, it turned out that the issue was caused not by terraform, but by on our end -- our process uploads the terraform configuration files into s3 bucket and another worker downloads it. In that uploaded file, the entire `.terraform` directory was happened to be included, which is stripped off the exec permission. 
Any successive terraform init would just skip downloading the plugin files if they are present, and terraform apply fails due to the permission.
