### ISSUE TITLE
Diff of multiple nested blocks adding unexpected values to count (`.#`) in 0.12 SDK

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform#20507]
### Terraform Version

```
Running a Google provider acceptance test with 
github.com/hashicorp/terraform v0.12.0-alpha4.0.20190226230829-c2f653cf1a35 vendored.
```

`master` is in this state.

### Terraform Configuration Files

```hcl
resource "google_dataproc_cluster" "with_labels" {
	name   = "dproc-cluster-test-%s"
	region = "us-central1"

	labels = {
		key1 = "value1"
	}

	# This is because GCP automatically adds its own labels as well.
	# In this case we just want to test our newly added label is there
	lifecycle {
	    ignore_changes = ["labels"]
	}

}
```

### Debug Logs

https://gist.github.com/rileykarson/4d5fb9ed973d20c8bd3c3edbf6285d69

### Expected Behavior

There should be no diff

### Actual Behavior

Full diff: https://gist.github.com/rileykarson/8407a58ab753d20939609792a914f67c

Relevant bits:

```
          cluster_config.0.delete_autogen_bucket:                                                                                 "false" => "false"
          cluster_config.0.encryption_config.#:                                                                                   "" => "0"
          cluster_config.0.gce_cluster_config.#:                                                                                  "1" => "1"

...

          cluster_config.0.gce_cluster_config.0.subnetwork:                                                                       "" => ""
          cluster_config.0.gce_cluster_config.0.tags.#:                                                                           "" => "0"
          cluster_config.0.gce_cluster_config.0.zone:                                                                             "us-central1-b" => "us-central1-b"


...

and several more occurences
```

### Steps to Reproduce
```
make testacc TEST=./google TESTARGS='-run=TestAccDataprocCluster_withLabels '
```

### Additional Context

Other dataproc tests didn't have the same error; this was the only one. This is probably the interaction of multiple nested blocks that are all `Optional` + `Computed`, and possibly the `ignore_changes`.

**Comment by rileykarson** [comment]
Apologies for the title- I don't have a great way of explaining this one in title form.

**Comment by apparentlymart** [comment]
This may be the same root cause as #20486.

**Comment by jbardin** [comment]
I think might be a recurring manifestation of the empty/null differentiation that `helper/schema` isn't consistent with, and we have to attempt to normalize in the shims. This looks like it's another layer deep than the examples I've worked with. I'll see if this is something that we can' normalize, or if there's something the provider can do to avoid it.

**Comment by jbardin** [comment]
I spent some time reviewing what's happening in this resource, and the skew in the config is arising from the large blocks being set in the Read function, like `cluster_config`.

Because the new value being set has subtle differences from what's already in the config. For example, one of the changes is a diff of "0" and "1" in `disk_config` because the value is set if even when there's no config. Change the value like so removed that particular diff:

```
-       data["disk_config"] = []map[string]interface{}{disk}
+       if len(disk) > 0 {
+               data["disk_config"] = []map[string]interface{}{disk}
+       }
```

There's also the likelihood that because changes to these computed configs aren't planned, some of the values are lost during apply. Since most of this structure has the possibility of being computed, this may be as simple as calling `d.SetNewComputed("cluster_config")` on any change, but that is probably equally likely to compound the issue if the problem is completely on the Read side.

I think this particular resource is going to need some time spent on reviewing what these config structures look like in the ResourceData, and making sure that they are applied in the same manner.

**Comment by rileykarson** [comment]
Part of the problem on our side is that this field is a nested object in the API; `disk_config` is always present whether the user provided it or not. Terraform has no notion of a nested object, so we're forced to deal with list semantics in cases like this.

The choice of how we represent this is schema (using `Computed` + `Optional`) is certainly unfortunate given the changes to the SDK, but accurately mirrors the API. Unfortunately, we're unable make it `Required` or exclusively `Optional` since that would be a breaking change.

**Comment by jbardin** [comment]
So this one turns out to be full of red herrings; because we internally have to suppress or ignore certain minor changes, i.e. it turns out . those `"0"->""` to changes aren't the actual reason for the perpetual diff in this case.

I think the key issue here is actually the `"labels"` field, which for some reason isn't showing with a diff at all. Adding a `DiffSuppressFunc` to the schema to ignore the diff when only missing "computed" labels allowed this test to run to completion. 

As for why the labels aren't even the ones showing in the test error output, I still have to look into that.

**Comment by jbardin** [comment]
Sorry, forgot to mention why it's not completely solved with `ignore_changes = ["labels"]`.
This allows the diff to happen each time, then requires core to reset the changed values. Unfortunately the legacy sdk itself is causing some of the skew on the container counts, and that still needs some work to try and resolve better than is being done at the moment.

**Comment by rileykarson** [comment]
So this is a similar issue to https://github.com/hashicorp/terraform/issues/18209?

**Comment by jbardin** [comment]
It's only partly related, in that the provider has no knowledge of `ignore_changes`, which means it may produce a diff more changes than intended even if core is going to ignore parts of the diff later.

In this particular case, those _extra_ changes are just the small inconsistencies between empty and Null values, which would otherwise be ignored. Adding the `DiffSuppressFunc` will help prevent the extra diffs and other issues later, but I intend to clean up the 0/Null issues in a forthcoming PR. (this test now passes as-is on my WIP branch right now)
