### ISSUE TITLE
local-exec: add chdir feature

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#2054]
Would be helpful if one could set the currently executing directory for the local-exec provisioner such as:

```
provisioner "local-exec" {
    command = "ansible-playbook setup.yml"
    chdir = "${path.module}/myplaybook"
}

```

The reason for this is some executables look for config files etc in the current working directory.

**Comment by rossedman** [comment]
:+1: This would be nice. @franklinwise how are you handling provisioning with Ansible now? I have to trigger a bash script and it still fails. Was trying to make a plugin that adds IP addresses to an inventory file.

**Comment by IanVS** [comment]
This would be very nice indeed.

@rossedman I'm also trying to provision with Ansible.  I found https://github.com/adammck/terraform-inventory, but I haven't tried yet.

**Comment by sporokh** [comment]
This would be great. Faced an issue running binary that located in another folder, and wasn't to make it work properly.

**Comment by apparentlymart** [comment]
Hi @franklinwise, and everyone!

Sorry for the long silence on this old issue. Adding this feature to the `local-exec` provisioner does seem like a good idea!

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it.

I suggest using the argument name `working_dir` instead of `chdir`, just because we generally try to minimize abbreviations where possible. (`dir` is a notable exception to the rule we've made elsewhere, since `directory` is a long word and we expect most people are familiar with this abbreviation.)

**Comment by danieldreier** [comment]
@franklinwise it looks like this was actually added in PR #17105 back in 2018, so I'm going to close this issue.
