### ISSUE TITLE
Add Description as GetSchema result

### ISSUE THREAD

**Issue by keiichi-hikita** [hashicorp/terraform#20564]
#### Current Terraform Version

0.11.10

#### Use-cases

What I would like to propose is "Add Description as Attribute property so that GetSchema can return schema.Description"

I'm working as Custom Provider developer for our company's cloud service named Enterprise Cloud 2.0.

Now this provider is niether Official nor Community provider, we try to prepare website directory(source of document web site) same as other provider.

And we try to auto generate those documents by using Schema property.
(We could not find those kind of tools, so we try to implement website auto generation tool)

But it looks impossible to extract Description property of schema by GetSchema.
If we can get Description by above method, it becomes really convenient.

Let me take https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/ami.html.markdown as example.

For example, each entry in *Argument Reference* has three information.

ex: `name - (Required) A region-unique name for the AMI.` includes followings.

1. name of argument
2. Required or Optional
3. Short description about argument

1 and 2 can be extracted by GetSchema definition in current implementation.
But it is not possible to get 3 from GetSchema.
Because in current implementation, Attribute(config/configschema/schema.go type Attribute) does not have Description field.

If GetSchema returns schema.Description as result of GetSchema, it is possible to utilize schema.Description as above 3 in auto generation logic.

#### Proposal

What I want to propose is add Description field into Attribute type(config/configschema/schema.go type Attribute)
and add it into other relevant place as well.

**Comment by apparentlymart** [comment]
Hello @keiichi-hikita,

[A `Description` field](https://github.com/hashicorp/terraform/blob/d72defd0448f5b81177323c1b3a1099ccdaf8bcd/configs/configschema/schema.go#L35) was already added during the v0.12.0 development period and will be included in the forthcoming v0.12.0 release.

Please note that although `configschema` is included in the v0.11.x releases (due to us developing it in the master branch before v0.12 branched off), the implementation of it there is incomplete and very likely to have bugs. If you build your provider against the SDK in the latest master branch of Terraform you should hopefully get better results.

**Comment by keiichi-hikita** [comment]
Hello @apparentlymart,

Thank you for looking this issue, and giving me a good information!
I didn't know that v0.12.0 already has Description field.

I'll try to implement document tool with v.0.12!

Let me close this issue. Thanks!
