### ISSUE TITLE
v0.12 testing: TypeSet Count Mismatch

### ISSUE THREAD

**Issue by jtopjian** [hashicorp/terraform#20562]
I'm running into an issue with the OpenStack Provider where the length of a TypeSet is being calculated incorrectly.

You can see the test output here:

http://logs.openlabtesting.org/logs/59/559/68760b7eefc5536645c911b5af7319596166c604/check/terraform-provider-openstack-acceptance-test/febc61e/

via the job-output.txt.gz file.

The error is:

```
--- FAIL: TestAccNetworkingV2Port_noFixedIP (38.33s)
    testing.go:568: Step 2 error: Check failed: Check 2/2 error: openstack_networking_port_v2.port_1: Attribute 'all_fixed_ips.#' expected "0", got "1"
```

However, if I add a debug line above [here](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_port_v2.go#L342):

```go
log.Printf("FOO: expandNetworkingPortFixedIPToStringSlice(p.FixedIPs))
d.Set("all_fixed_ips", expandNetworkingPortFixedIPToStringSlice(p.FixedIPs))
```

The result is a correct `[]string{}`, but the following test is failing:

```
resource.TestCheckResourceAttr("openstack_networking_port_v2.port_1", "all_fixed_ips.#", "0"),
```

What's interesting is that it is Step 2 of the test that fails. Step 0 runs this same fixture and passes:

Step 0: Port with No Fixed IPs
Step 1: Update the port to have 1 Fixed IP
Step 2: Update the port to have 0 Fixed IPs
- Failure: `all_fixed_ips.#` expected 0, got 1

The API is really returning no Fixed IPs and changing the test to look like this allows the test to pass: https://github.com/terraform-providers/terraform-provider-openstack/pull/559/commits/9316c2e78a60fae59f60ab7c1e377bb9d5083463

Please let me know if you need any more information or if there's anything I can try.

**Comment by jbardin** [comment]
Thanks @jtopjian, this was a good one 👍

The primary issue here is that the resource is attempting to set the `all_fixed_ips` value to something other than what was planned. Since that value needs to be recomputed there should be a `CustomizeDiff` func that calls `d.SetNewComputed("all_fixed_ips")` so the plan has the correct information.

This however is probably a common mistake in providers, and since these are list values the shims should be able to return the "wrong" value, which terraform core will accept and warn about. 

You can add a `CustomizeDiffFunc` to the resource to fix the warning later if you so choose, but I'll have a PR to restore the legacy behavior for this case coming.

**Comment by jtopjian** [comment]
@jbardin Thank you for looking into this :)

> The primary issue here is that the resource is attempting to set the all_fixed_ips value to something other than what was planned. Since that value needs to be recomputed there should be a CustomizeDiff func that calls d.SetNewComputed("all_fixed_ips") so the plan has the correct information.

Can you help me understand this a little more? My current understanding of a computed-only field is that it's a read-only field that the remote API has authoritative control over. Whatever the remote API sets is the read-only truth.

**Comment by jbardin** [comment]
Yes, that is correct at a basic level. The issue here is that Terraform needs to know this at Plan time, not after Apply. The basic contract is that Plan returns what the provider intends to do, and Apply executes that plan, _only_ setting the values of unknown computed fields. (This is much easier to follow in the new protocol, but for now provider still have to deal with ResourceDiff, ResourceData, etc).

The problem with not planning the change to `all_fixed_ips`, is that any other resources referencing `all_fixed_ips` will see the old value during Plan, and plan themselves accordingly. When that value is unexpectedly changed, the changes cascade through the dependent resources, causing their application to be incorrect, have new diffs afterwards, or hit the dreaded "diffs didn't match after apply".

So while we still need to allow for these to happen because there are simply too many misbehaving resources, core will output a warning like so to help diagnose the issue:

```
[WARN] Provider "test" produced an unexpected new value for test_resource_list.foo, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - . all_fixed_ips: was cty.Value{ty: cty.List(cty.String), v: []interface {}{"1.2.3.4"}}, but now null
```

**Comment by jtopjian** [comment]
@jbardin Ah, thank you! I think I have a better understanding now. This is something I can look at fixing once the dust settles :)
