### ISSUE TITLE
Support for multiple hops to instance (RE: bastion_host)

### ISSUE THREAD

**Issue by ToddA316** [hashicorp/terraform#20574]
### Terraform Version

```
Terraform v0.11.10
```

### Terraform Configuration Files

```hcl
resource "null_resource" "dp-host-setup" {
  provisioner "remote-exec" {
    connection {
      agent = true
      timeout = "5m"

      bastion_host = "${var.bastion_instance}"
      bastion_user = "${var.ssh_username}"

      bastion_host = "${var.jump_instance}"
      bastion_user = "${var.ssh_username}"

      host = "${var.scanner_instance}"
      user = "${var.ssh_username}"
      script_path = "/home/${var.ssh_username}/execute_dp_host_setup.sh"
    }

    inline = [
      "sudo chmod 755 /tmp/dp_host_setup.sh",
      "sudo bash /tmp/dp_host_setup.sh"
    ]
  }
}
```

The need is to support one bastion and one jump host before getting to the instance resource we need with the several of the provisioners (file, local-exec, remote-exec).   Typical Oracle OCI environment, just trying to use the provisioner with multiple bastion_host in some way.  I see this: https://github.com/hashicorp/terraform/issues/14523 but do not see a solution for it.

**Comment by apparentlymart** [comment]
Hi @ToddA316,

This does appear to be the same request as #14523, so I'm going to close this just to consolidate the discussion over there. Please do add a :+1: reaction to it to vote for the issue since that is one of the inputs we use to prioritize work for the Terraform team at HashiCorp.

There was [an earlier PR for this](https://github.com/hashicorp/terraform/pull/16933) but because we were in the middle of refactoring the configuration language for Terraform v0.12.0 it was not completed and merged. We're still open to review a PR with a design like what I described in that PR, which should be easier to implement once v0.12.0 is out since we're now using a new strategy for parsing `connection` blocks that can properly support nested blocks like that `bastion` block I proposed.
