### ISSUE TITLE
Interpolation: map("a", list()) produces a map<string, map> instead of map<string, list)

### ISSUE THREAD

**Issue by jvassev** [hashicorp/terraform#20579]
### Terraform Version

```
Terraform v0.11.11

```

### Terraform Configuration Files

```hcl
# not releveant
```

### Debug Output
```
terraform console
> list()
[]
> map("a", list())
{
  "a" = {}
}
> map("a", list(""))
{
  "a" = [
    "",
  ]
}
>  

```

### Crash Output
No crash, just unexpected behavior.

### Expected Behavior
The expression `map("a", list())` should have produced a map with an empty list.

### Actual Behavior
The expression `map("a", list())` produces a value for "a" which is an empty map instead of an empty list

### Additional Context
I am playing with nested maps whose leaf values are lists. To achieve a notion of a default value of empty list I `merge` two maps where the first one is a fake. I notice just passing `list()` produces an empty map instead of list. As a workaround I now create a `list("")` then  `compact` the final result to get rid of the empty string.

**Comment by apparentlymart** [comment]
Hi @jvassev,

In Terraform v0.11 the language doesn't support very well nested collections like this; most functions require lists or maps of strings, and those that don't are generally doing so only due to missing checks, and may have strange behavior when used in this way.

The forthcoming Terraform v0.12 supports nested collection types properly and also has a more intuitive syntax for what you were trying to do here:

```
> {"a" = []}
{
  "a" = []
}
```

The `map` and `list` functions are deprecated in v0.12, but we can get the same result using the `map` function instead of the native syntax:

```
> map("a", [])
{
  "a" = []
}
```

I'm not sure what Terraform 0.11's `map` function was doing here to make this be converted to a map instead of a list, and so unfortunately I don't have a ready workaround for v0.11 here.
