### ISSUE TITLE
Final command hangs for 5 minutes

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/terraform#2059]
Terraform always seems to hang for at least 5minutes on the last command.

**Comment by knuckolls** [comment]
If you gist a reproduction case, we might be able to help debug this. The DNS resources are certainly slow, but that's because they want for DNS propagation to occur. That could possibly be a problem.

**Comment by mitchellh** [comment]
The only things I can think of that last 5 minute are route53, RDS, and waiting for ASG. 

Providers right now cannot output to the UI, so there is a lack of information of what they're doing except in the debug log (which isn't generally UX-friendly since it is a debug log). There is another issue where we'd like to add more output to providers but we haven't been able to do this yet.

But @knuckolls is asking a good question: Can you post a repro case? Can you show us your config? We'd love to help, but need some more context in order to do so!

**Comment by jwaldrip** [comment]
I think you are right, its hanging on route53 and on autoscaling groups. I think more verbosity here would would help. Configuration is at github.com/brandfolder/infrastructure.
