### ISSUE TITLE
Provider Cache always creating a hard link

### ISSUE THREAD

**Issue by aaron-ballard-530** [hashicorp/terraform#20609]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v2.1.0

```

### Terraform Configuration Files

```hcl
plugin_cache_dir="$HOME/.terraform.d/plugin-cache"
```

### Expected Behavior

I would expect the folder .terraform/plugins/linux_amd64 to contain a symbolic link to the provider in the plugin_cache_dir folder

### Actual Behavior

A hard link is created instead of a symbolic link

### Steps to Reproduce

1. `rm -rf .terraform`
2. `terraform init`
3. `ls -la .terraform/plugins/linux_amd64/`

**Comment by apparentlymart** [comment]
Hi @aaron-ballard-530,

[The documentation](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) states that Terraform will use hardlinks when possible, symlinks when hardlinks fail, and a full copy otherwise, so what you are seeing is the intended behavior.

I assume you're reporting this because you've found that the hardlinks are the root cause for some broader problem. If so, please let us know, and we can do our best to address that.

**Comment by aaron-ballard-530** [comment]
Hi @apparentlymart,

The documentation doesn't say specifically which one it will use just that it will try to use one or the other if possible.  

> When possible, Terraform will use hardlinks or symlinks to avoid storing a separate copy of a cached plugin in multiple directories. At present, this is not supported on Windows and instead a copy is always created.

I assumed that a symbolic link would get created first to keep the disk from being cluttered with a copy of the same provider file in each child directory that scripts are run from.

For my particular case is that my source control isn't attached in the environment that I build and edit my terraform environment so I have to copy the files down to push them to source control.  However doing that copies the provider file over and over again for each directory and I haven't found a good way to do a recursive copy of the parent folder and exclude the .terraform folder during the scp call.

Is it possible to be able to specify that I want symbolic links to be created as the default?

**Comment by apparentlymart** [comment]
Hi @aaron-ballard-530,

The preference for hardlinks is motivated by a similar problem, but from a different angle: those running Terraform in automation scenarios often wish to transport their working directory (including `.terraform` dir) from one machine to another, and so using hardlinks by default allowed us to introduce the provider cache without potentially breaking that workflow, since hardlinks are completely indistinguishable from a copy unless you go out of your way to inspect the inodes. (Note that a hardlink is not a copy; all of the references to the file share the same bytes on disk.)

Symlinks are a fallback because they are not transparent in this way... naively copying a directory containing symlinks -- or performing certain other operations with them -- can result in a broken result.

At the moment we have no direct way to force a particular preference here, and to be honest I think we'd rather not introduce one since that would add further complexity for a relatively-rare situation. There are some less-ideal ways you may be able to work around this with Terraform's current capabilities:

* If you put your plugin cache directory on a different filesystem than your working directory then a hardlink will be impossible to create, and so Terraform will use a symlink as a fallback. (This is the very situation the symlink fallback is designed for, though we assumed _this_ was the compromise when originally implementing the cache.)
* Alternatively, the `-plugin-dir` option to `terraform init` allows you to force a particular directory for plugins and not make _any_ links or copies at all. It essentially overrides the use of `.terraform/plugins` with this other directory, presuming you already populated it with the plugins you want and so no plugins need to be downloaded, copied, or linked at all.
* Taking a different angle entirely, you could consider using `rsync` instead of `scp` directly (if it's available on your target host) and use the `--exclude` option to omit the `.terraform/plugins` directory. `rsync` can execute over SSH just as `scp` does, if you use the `-e ssh` option.

I realize that neither of these alternatives is as convenient as the behavior you were looking for. We are always cautious about adding more permutations of behavior, since they inevitably make maintenance harder due to having more situations to regression test, etc; we need to focus on the most impactful options to ensure we and the community can work productively on Terraform on an ongoing basis.
