### ISSUE TITLE
Wrong path for plugin installation, i386

### ISSUE THREAD

**Issue by IizunaK** [hashicorp/terraform#20602]
HI,

For some reason I couldnt terraform init on a fresh installation (i386) because I couldnt get the aws plugin.
And the path the error message gave me was the wrong one.

 For the code in terraform/command/init.go
`
In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    %[2]s`

It gave me (as a relative path I suppose ?) :
  `terraform.d/plugins/linux_386`
However the good one was:
`.terraform/plugins/linux_386`

I could make it work and it s a detail, but just so you know.

**Comment by mildwonkey** [comment]
Thanks for reporting this, @IizunaK! Can you share what version of terraform with which you are experiencing this issue?

**Comment by jbardin** [comment]
Hi @IizunaK,

What was the result when you tried using `terraform.d/plugins/linux_386`? That is the correct path for manually installed plugins, and should have worked. You shouldn't be manually changing the contents of `.terraform/`, since terraform takes ownership of that directory and can override any changes you make.

**Comment by IizunaK** [comment]
- I am using Terraform v0.11.11 + provider.aws v2.0.0
- I couldnt locate an existing `terraform.d/plugins/linux_386`, should I have created it ?

In that case maybe it was a misusage on my part.

**Comment by teamterraform** [comment]
Hi @IizunaK! Sorry for the slow response.

Indeed, the `terraform.d` directory is one that Terraform expects you to create yourself as part of your configuration if you wish to use it. However, that directory is primarily for distributing locally-developed providers that are not available from the official releases repository.

It sounds like instead your challenge was that you could not reliably access the official `aws` plugin from the HashiCorp repository. In that case, rather than creating a separate copy for each configuration you are working with you can instead place the plugin executable file in the same directory where the `terraform` executable is found, and then Terraform should find it there and use it for any configuration that is compatible with it.
