### ISSUE TITLE
count.index + 1 doesn't work for aws_launch_template

### ISSUE THREAD

**Issue by 80kk** [hashicorp/terraform#20601]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.null v2.1.0
+ provider.template v2.1.0
```

### Terraform Configuration Files
```
grafana-launch-template.tf
resource "aws_launch_template" "grafanatest-launch-template" {
  name = "grafanatest-launch-template"

  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_size = 12
      volume_type = "gp2"
    }
  }

  iam_instance_profile {
    name = "github-ansible-access"
  }

  user_data              = "${base64encode(data.template_file.grafana_user_data.rendered)}"
  image_id               = "${var.grafana-ami}"
  instance_type          = "${var.grafana-instance-type}"
  key_name               = "${var.key_name}"
  vpc_security_group_ids = ["${aws_security_group.ssh_internal.id}", "${aws_security_group.grafanatest_GUI_access.id}"]

  tag_specifications {
    resource_type = "instance"
    tags {
      Name            = "grafanaServer0${count.index + 1}"
      Environment     = "${var.environment-tag}"
      EnvironmentType = "${var.environmentType-tag}"
      Owner           = "${var.owner-tag}"
      Managed_by      = "${var.managed-by}"
      ansibleGroup    = "grafanaServer"
    }
  }

  tag_specifications {
    resource_type = "volume"
    tags {
      Name            = "grafanaServer0${count.index + 1}"
      Environment     = "${var.environment-tag}"
      EnvironmentType = "${var.environmentType-tag}"
      Owner           = "${var.owner-tag}"
      Managed_by      = "${var.managed-by}"
      ansibleGroup    = "grafanaServer"
    }
  }

  tags {
    Name            = "grafanaServer0${count.index + 1}"
    Environment     = "${var.environment-tag}"
    EnvironmentType = "${var.environmentType-tag}"
    Managed_by      = "${var.managed-by}"
    Owner           = "${var.owner-tag}"
    ansibleGroup    = "grafanaServer"
  }
}

data "template_file" "grafana_user_data" {
  template = "${file("grafana-user-data.tpl")}"
  vars {
    iam_instance_profile = "${aws_iam_instance_profile.grafana-iam-role.name}"

  }
}
```

### Expected Behavior

Like in aws_instance it should create two (or more) instances with Name grafanaServer01 and grafanaServer02.

### Actual Behavior

Instead of that it creates two instances with grafanaServer01. As mentioned above, it works fine with aws_instance.

**Comment by apparentlymart** [comment]
Hi @80kk,

From Terraform's perspective there is only a single `aws_launch_template` here. I assume elsewhere in the configuration you are creating an autoscaling group where you've asked AWS Autoscaling to create two instances, but those two instances are created by the AWS autoscaling mechanism, not by Terraform. Both instances share the same single launch template with the name set to `grafanaServer01`, because `count.index` is Terraform's concept, not AWS autoscaling's.

In order to use different tags per instance in your autoscaling group you would need to configure autoscaling itself to do this. I don't know of any feature to support this -- as far as I know, the tags are required to match for all instances in the group -- but you may wish to investigate further in the AWS autoscaling documentation to verify whether that is true.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
