### ISSUE TITLE
aws_route53_record.main: aws_route53_record.main: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [hashicorp/terraform#20612]
* aws_route53_record.main: aws_route53_record.main: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.11
    Resource ID: aws_route53_record.main
    Mismatch reason: attribute mismatch: records.1605703144
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"records.3076313085":*terraform.ResourceAttrDiff{Old:"34.209.115.132", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.1605703144":*terraform.ResourceAttrDiff{Old:"", New:"10.0.0.26", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"records.3076313085":*terraform.ResourceAttrDiff{Old:"34.209.115.132", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.1263836238":*terraform.ResourceAttrDiff{Old:"", New:"10.0.0.84", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

**Comment by apparentlymart** [comment]
Hi @krestivo-kdinfotech! Sorry for this strange behavior and thanks for reporting it.

This particular class of error usually results from an upstream resource making an unexpected change to a result that disagrees with what the provider predicted during the plan. In Terraform v0.11 this fails "downstream" because the `aws_route53_record.main` plan was derived from the planned result of the other resource, and thus during apply the inputs changed.

To figure out where this bug lies, we'll need to see how you are building the `records` value in your configuration. I would expect to see in one of the elements a reference to an attribute exported by some other resource; the bug is in that referenced resource. Once we know which provider that resource type belongs to, this is likely to be an issue to be fixed within that provider, but we'll deal with that once we know which provider it is.

---

(Terraform 0.12 will include some additional safety checks to detect this problem at its source. It won't be enabled for existing providers immediately to avoid a sudden breakage, but it'll be gradually enabled as providers migrate to new SDK conventions and then the error message will be able report the resource that caused the problem, rather than the resource that was impacted by it. Provider developers can see a preview of these errors as `[WARN]` messages in the Terraform logs when they run the provider against Terraform 0.12, in case that helps with debugging.)

**Comment by krestivo-kdinfotech** [comment]
Was a couple days ago, but I am pretty sure it was this:

```terraform
resource "aws_instance" "db-proxy" {
  ami  = "${var.ubuntu_ami}"
  instance_type = "t2.micro"
  vpc_security_group_ids = [ "${aws_security_group.private.id}", "${aws_security_group.geneious.id}" ]  
  key_name = "${aws_key_pair.prod_root.id}"
  subnet_id = "${aws_subnet.private.id}"
  source_dest_check = false
  tags {
    Name = "db-proxy"
  }
  lifecycle {
    create_before_destroy = true
  }
}



resource "aws_route53_record" "db-proxy" {
  zone_id = "${aws_route53_zone.prod.id}"
  name = "db-proxy"
  type = "A"
  ttl = "60"
  records = ["${aws_instance.db-proxy.private_ip}"]
}
```

**Comment by apparentlymart** [comment]
Thanks for that additional context, @krestivo-kdinfotech!

It looks like this is a slightly different example than what caused the error since this resource is called `aws_route53_record.db-proxy` rather than `aws_route53_record.main`, but I assume it was following a similar pattern since I see that the record value that changed was indeed a private IP address.

My guess here is that the plan you were applying included an update to your `aws_instance` that changed its private IP address somehow, but the plan step for the `aws_instance` didn't anticipate that change by marking `private_ip` as not-yet-known and so Terraform assumed the IP address would not change. That's a bug in the `aws_instance` resource, so I'm going to have our bot move this over to the AWS provider to get some input from the AWS provider team.

If you can remember what changes you were making to the `aws_instance` when this problem showed up, I expect that'll help to get to understand why the IP address changed and thus what the AWS provider needs to check for in order to correctly anticipate changes to the IP address to avoid this problem.
