### ISSUE TITLE
CHANGELOG.md doesn't list v0.11.12 / v0.11.13

### ISSUE THREAD

**Issue by jeohist** [hashicorp/terraform#20643]
Same issue as in #19666. https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md doesn't contain the release notes for v0.11.12 or v0.11.13. 

It would be nice if the GitHub Releases also contained the version's changes in addition to the CHANGELOG.md, don't know if that's been considered :-)

**Comment by apparentlymart** [comment]
Once the master branch switches to a new major release, new releases for the previous major release will be tracked in the branch for that release, which is [the `v0.11` branch](https://github.com/hashicorp/terraform/blob/v0.11/CHANGELOG.md) in this case. The canonical place to find the release notes for a particular release is in the `CHANGELOG.md` associated with that release's _tag_, which you can find from [the releases page](https://github.com/hashicorp/terraform/releases).

We are indeed planning to include detailed information in the changelog in future, once we have time to update the release process to include that step. We've been focusing all of our efforts on feature development recently, but will hopefully be able to spend some time on various build/release-process tooling improvements in the not-too-distant future. I copied a few in manually to the releases list for now since, as you point out, the notes for the ongoing v0.11.x releases are harder to find right now.

**Comment by jeohist** [comment]
Thanks @apparentlymart, that's great to hear. I'll close the issue for now, looking forward to the improvements post-0.12 👍
