### ISSUE TITLE
0.12-Beta1 crash at init

### ISSUE THREAD

**Issue by dantontech** [hashicorp/terraform#20653]
### Terraform Version

```
Terraform v0.12.0-beta1
```
### Terraform Configuration Files

```hcl
# Create the dns resource group
module "resourceGroup" {
  source            = "git::https://github.com/dantontech/terraformModules.git//azure/resourceGroup"
  location          = var.location
  resourceGroupName = var.resourceGroupName
  tags              = var.tags
}

# Create the mysql server
module "mysqlServer" {
  source                 = "git::https://github.com/dantontech/terraformModules.git//azure/wip/mysqlServer"
  name                   = var.dbServerName
  location               = var.location
  resourceGroupName      = module.resourceGroup.groupName
  administratorLogin     = var.administratorUsername
  administratorPPassword = var.administartorPassword
  version                = var.dbVersion
  ssl_enforcement        = var.sslEnforcement

  sku = [
    {
      skuName    = "B_Gen4_2"
      skuCapcity = "2"
      skuTier    = "Basic"
      skuFamily  = "Gen4"
    },

  ]

  storageProfile = [
    {
      storageMb           = "5120"
      backupRetentionDays = "7"
      geoRedundantBackup  = "Disabled"
    },
  ]

}

```
### Crash Output

https://gist.github.com/dantontech/e9aa8d050daac82e75428345feaf3363

### Expected Behavior

Terraform Initialization 

### Actual Behavior

Terraform Panic

### Steps to Reproduce

terraform init

**Comment by apparentlymart** [comment]
Hi @dantontech! Thanks for reporting this.

It's definitely a bug that this was a crash rather than a proper error message, but note that `version` must be a literal string value like `v1.0.0` rather than a variable: it's resolved during `terraform init`, before any variables are available, so it must have a fixed value that decides what gets installed to use in other operations.

I think setting it to a constant string will get you past this crash. We'll fix this up to return a proper error message rather than crashing.
