### ISSUE TITLE
Building Dockerfile fails on remote-state 

### ISSUE THREAD

**Issue by Emptyless** [hashicorp/terraform#20651]
### Terraform Version
```
v0.12-dev
```

### Crash Output
```
1 errors occurred:
--> linux/amd64 error: exit status 1
Stderr: backend/remote-state/azure/backend.go:8:2: 
vendor/github.com/Azure/azure-sdk-for-go/storage/odata.go:1:1: expected 'package', found 'EOF'
```

### Expected Behavior
The Dockerfile should build a docker image with a Terraform binary according to `/scripts/build.sh`

### Actual Behavior
The Dockerfile build crashes on a vendor package being incorrect

### Steps to Reproduce
`docker build .`

**Comment by apparentlymart** [comment]
I'm not sure what exactly is going on here... it seems like the file in question didn't transfer correctly into the Docker container being used for the build. I was able to run `docker build` myself locally and get a working image, so it seems that something is different between our two systems.

---

In looking closer at the `Dockerfile` though, I noticed it's using `golang:alpine` as its basis rather than `golang:1.11.5-alpine` to fix the current version we use. It doesn't seem to make any practical difference right now -- the Go 1.12 runtime is compatible enough with 1.11.5 that Terraform still behaves the same -- but ideally we'd have this in sync with the other two places we record the current Go version (`.go-version` and `.travis.yml`) to ensure that the full docker builds are built in a consistent way to everything else.

**Comment by Emptyless** [comment]
@apparentlymart it seems to be the vendor directory. If i add the local `vendor/` directory to a `.dockerignore` file:

```
#.dockerignore
vendor/
```

And change the `Dockerfile` to: 
```
#Dockerfile 
FROM golang:alpine
LABEL maintainer="HashiCorp Terraform Team <terraform@hashicorp.com>"

RUN apk add --update git bash openssh

ENV TF_DEV=true
ENV TF_RELEASE=1
ENV GO111MODULE=on

WORKDIR $GOPATH/src/github.com/hashicorp/terraform

RUN go get -u github.com/kardianos/govendor
RUN go get -u golang.org/x/tools/cmd/stringer
RUN go get -u golang.org/x/tools/cmd/cover
# To utilize Docker caching
COPY go.mod go.mod
RUN go mod vendor
COPY . .
RUN /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["terraform"]
```

Is there at the moment a reason to not vendor inside the Dockerfile? I believe this would improve the consistency of building releases.

**Comment by apparentlymart** [comment]
The purpose of vendor get is to have all of dependencies locally in the repository so that they don't need to be re-downloaded at build time. Running `go mod vendor` inside the docker build would therefore defeat the object.

The big question left unanswered here is why copying the vendor directory into the container didn't work for you. It seems like an empty file was copied instead of the source file that was failing during the build.

Is there anything unusual about your docker setup, or are you using an unusual filesystem for your Terraform working directory?

**Comment by Emptyless** [comment]
As long as the go.mod file does not change it can utilize Docker caching with intermediate containers. Hence the 'double' copy of the `go.mod` file. 

But I'll also look into my local setup, I'll try on a fresh machine when I get home

**Comment by Emptyless** [comment]
The problem is resolved in a VM with `go version go1.11.5 darwin/amd64` and fresh clone of master so I think my development setup has an error somewhere. Still, I think it is safer to vendor inside the Dockerfile but that is not related to this issue anymore then (#20666).

**Comment by Emptyless** [comment]
Reopened PR with from correct branch

**Comment by mildwonkey** [comment]
I think we're all good here, so I'm going to close this - thanks!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
