### ISSUE TITLE
Terraform list support A-B set theory

### ISSUE THREAD

**Issue by pasalkarsachin1** [hashicorp/terraform#20683]
Need a A-B set theory to be supported 
e.g.
```
> setminus(["a", "b"], ["b", "c"])
[
  "a",
]
```

**Comment by apparentlymart** [comment]
Hi @pasalkarsachin1! Thanks for this feature request.

Would you mind sharing what problem you are trying to solve with this function? Knowing the real-world use-cases for feature requests helps with prioritization and may also, in some cases, allow us to identify other existing features that might already meet your needs.

**Comment by pasalkarsachin1** [comment]
Hi @apparentlymart,

We have a use case, where we have a list of permissions for S3 api in common module. This list is shared across multiple actions section in s3 policy, but when other module uses the common module we need to remove some part of s3 permissions. So with A-B approach, it will help us duplicating/re-writing at multiple place.

**Comment by apparentlymart** [comment]
Thanks for sharing the use-case, @pasalkarsachin1.

It sounds like the generalization of that problem is that you have a set of all objects that you know you need to create, and you maybe have a module that creates a subset of them based on some criteria, and so you then want to know which objects are left to create once that module has done its work.

That seems reasonable to me, and indeed I can't think of a convenient way to do it with any other existing function or Terraform feature.

I think we would name such a feature `setdifference`, since that matches well with the existing `setproduct` and I think "Set Difference" is a common way to refer to this operation in other contexts.

We'd need to be careful to explain in the documentation that this function implements what is technically called the "relative complement", as opposed to the "symmetric difference" (or "disjunctive union") operation. We should additionally include an example of using the other functions together to produce a symmetric difference, in case that is needed: `setunion(setdifference(a, b), setdifference(b, a))`.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Because we're in the process of releasing v0.12.0 right now I would encourage waiting until the v0.12.0 final release before starting work on it, because the way the built-in functions are implemented has changed significantly in Terraform v0.12.0.

Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by danbf** [comment]
adding a new function would be something like this: https://github.com/hashicorp/terraform/pull/20014/files

looks like it's present in the underlying library as `SetSymmetricDifference`: https://github.com/zclconf/go-cty/blob/3ccef1ae92b0ac73b92d86f274f0ff781e2d9b3b/cty/function/stdlib/set.go#L159

**Comment by jamesgoodhouse** [comment]
I'll chime in on a use case for this.

I am attempting to do some auditing of what exists in the real world for a provider vs what Terraform is managing. For this I'm using a data source to get a list of all the resources in said provider, and them am using the `remote_state` data resource to find out what Terraform is managing. I then want to do a difference of two sets to find any outliers so I can use that as an input to a resource.

**Comment by jamesgoodhouse** [comment]
I'd like to tackle this, as we have an immediate need for the functionality.

I would vote more toward calling it `setsubtract`, since the symmetric difference would be covered by `setunion(setsubtract(a, b), setsubtract(b, a))`, so calling it `setdifference` seems like it'd be more confusing. Thoughts @apparentlymart or others?

**Comment by jamesgoodhouse** [comment]
I opted to go the route of many of the other set functions available and utilize the functions available in the `[go-cty](https://github.com/zclconf/go-cty/)` that is already part of the Terraform codebase.

**Comment by apparentlymart** [comment]
Hello!

It looks like we neglected to close this along with merging #23424, but that PR responds directly to this request and so I think this is now done.

Thanks for the request and thanks for the PR to implement it!
