### ISSUE TITLE
Documentation points to unreleased version by default

### ISSUE THREAD

**Issue by oliversalzburg** [hashicorp/terraform#20691]
I just wanted to note that it's really frustrating that your documentation points to (apparently) 0.12 syntax by default, which is not always compatible with 0.11, which is the default download version right now.

I was reading https://www.terraform.io/docs/modules/composition.html and got errors when I attempted the same in my own code. I only realized this issue after I hit https://www.terraform.io/docs/configuration-0-11/variables.html

**Comment by apparentlymart** [comment]
Hi @oliversalzburg,

The situation you described was a temporary compromise to allow us to release the beta along with its documentation. As you noted, it was confusing and non-ideal in a number of ways, but that compromise was part of what allowed us to get Terraform 0.12 beta tested and finally shipped.

Since Terraform 0.12 is now current, the docs are now "correct". We've retained the Terraform 0.11 docs still to support those who are unable to upgrade yet.

Sorry for the temporary confusion!
