### ISSUE TITLE
Default map value results in error when overriding with var

### ISSUE THREAD

**Issue by jasonwilson** [hashicorp/terraform#20720]
### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
// main.tf
variable some_map {
  type="map"
  # when default is not provided no errors occur
  default= {} 
}

output "data" {
  value = "${var.some_map}"
}

// overrides.tfvars
some_map = {
  bar = "${abcd}"
}



# terraform apply -var-file=overrides.tfvars

```

### Debug Output
https://gist.github.com/jasonwilson/2879417bbfc9a038f05303baecfb0586

### Expected Behavior
Should allow for variable string when a default is present

### Actual Behavior
`Error: variable "some_map": default may not contain interpolations`

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -var-file=overrides.tfvars`

### Additional Context

Trying to expose optional configuration via tfvars for users of our system. The goal is to allow them to specify a custom tfvars that we pull into our build for templating. 

In trying to support no specified overrides I added `default = {}` but this seems to cause the error described above. When I remove `default = {}` terraform executes successfully without error and the downstream interpolation works as expected. It seems like terraform is replacing the default value with the supplied value then failing.

Thanks!

**Comment by apparentlymart** [comment]
Hi @jasonwilson! Thanks for reporting this.

I agree that something funny is going on here, but I think I have the opposite sense of what behavior here is problematic: Terraform should have returned an error telling you that interpolations cannot be used in the `tfvars` file in the first place, since indeed they cannot.

I tried this with Terraform v0.12.0-beta1 and got the result I expected, so at least the bug seems fixed in `master`:

```
$ terraform apply -var-file=overrides.tfvars

Error: Variables not allowed

  on overrides.tfvars line 2:
   2:   bar = "${abcd}"

Variables may not be used here.
```

Adding an extra `$` to escape that interpolation sequence gets the desired result:

```
$ cat overrides.tfvars 
some_map = {
  bar = "$${abcd}"
}
$ terraform apply -var-file=overrides.tfvars

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

data = {
  "bar" = "${abcd}"
}
```

(unfortunate that the "Outputs" in result look like Terraform syntax but yet don't escape the `${` in that string, but I think the alternative would be equally confusing in the other direction.)

Unfortunately this workaround of escaping the interpolation in the `.tfvars` file won't work for Terraform v0.11 because there are known bugs in that release around escaped interpolations in variable `default` anyway, and I expect Terraform's failure to detect and report on the interpolation in the `.tfvars` file also indicates that it would also fail to handle the escaped `${` there, so sadly I don't think there is any resolution for this possible in v0.11. Instead, we'll need to wait for v0.12.0 final and then your `.tfvars` file will need to be updated to use escaping to avoid the (now correct) error message about it.

**Comment by mildwonkey** [comment]
Since this was fixed in master and terraform has since been released, I will close this issue. Thanks!
