### ISSUE TITLE
cant access a value in this property (secondary_ip_range)

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform#20723]
initially asked on SO: https://stackoverflow.com/questions/55191480/how-do-you-access-a-value-in-a-list-of-maps?noredirect=1#comment97132594_55191480

Terraform v0.11.10
+ provider.google v2.1.0

the value of google_compute_subnetwork.subnetwork.secondary_ip_range looks like this:

```
[
    {
        ip_cidr_range = 10.1.0.0/16,
        range_name = my-range
    }
]
```
I cant figure out how to loop over that, this doesnt work:

```
resource "aws_security_group_rule" "sdfsdfsdf" {
 count = "${length(data.google_compute_subnetwork.mysubnetwork.secondary_ip_range)}"
 type      = "ingress"
 from_port    = 0
 to_port     = 0
 protocol    = "-1"
  cidr_blocks = ["${data.google_compute_subnetwork.mysubnetwork.secondary_ip_range[count.index]}.ip_cidr_range}"]
}
```

**Comment by red8888** [comment]
Is this something the latest terraform version can do? or Is my syntax just bad here?

**Comment by apparentlymart** [comment]
Hi @red8888! Sorry for the slow response.

The latest version of Terraform should support something like this:

```hcl
cidr_blocks = data.google_compute_subnetwork.mysubnetwork.secondary_ip_range[count.index].ip_cidr_range
```

I'm not personally familiar with the `google_compute_subnetwork` data source in particular, so I'm not sure if that is a correct attribute path, but the above is correct syntax for attribute access and list indexing in Terraform 0.12.0 and later.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are more people ready to help. Stack Overflow can also be helpful, and I see some people have already been answering you there. The GitHub issues here are generally monitored only by our few core maintainers.
