### ISSUE TITLE
Unknown root level key - resources

### ISSUE THREAD

**Issue by sumitraj1491** [hashicorp/terraform#20726]
i am new to the coding and building my 1st program to create AWS EC2 Instance via Terraform.

however when i try to run : terraform plan / terraform init in cmd (windows 7)

i get below message 
**Error :  Unknown root level key - resources**

![image](https://user-images.githubusercontent.com/48655541/54495951-4efc3780-490f-11e9-91c0-4f4aec216af1.png)

Please help !!

**Comment by apparentlymart** [comment]
Hi @sumitraj1491,

Because you didn't share your configuration here I can't be sure, but the error message suggests that you have a block in your configuration whose type is `resources`, but Terraform expects that block type to bce called `resource` (singular).

**Comment by sumitraj1491** [comment]
Hello @apparentlymart 

Thanks for the response, please find the code i used. (this is very simple code to launch an ec2 instance using only required fields)

provider "aws" {
  region     = "ap-south-1"
  access_key = "XXXXXXX"
  secret_key = "XXXXXXX"
}

resources "aws_instances" "my1stterra" {
  ami = "ami-0889b8a448de4fc44"
  instance_type = "t2.micro"
}

Thanks a advance !!!

**Comment by apparentlymart** [comment]
Hi @sumitraj1491! Thanks for sharing your configuration.

To fix this, change your `resources "aws_instances" "my1stterra" {` line instead to `resource "aws_instances" "my1stterra" {`. Each block only represents _one_ resource.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
