### ISSUE TITLE
Dynamic blocks in override file confuses validation

### ISSUE THREAD

**Issue by libc** [hashicorp/terraform#20751]
Hello,

Apologies if there's already ticket like that, I couldn't find anything.

### Terraform Version
```
Terraform v0.12.0-beta1
+ provider.fastly v0.7.0-dev20190216h01-dev
```

### Terraform Configuration Files

main.tf
```hcl
resource "fastly_service_v1" "test" {
  name = "test"

  dynamic "domain" {
    for_each = ["a", "b"]
    content {
      name = domain.value
    }
  }
}
```

test_override.tf
```hcl
resource "fastly_service_v1" "test" {
  dynamic "backend" {
    for_each = ["a", "b"]

    content {
      name    = backend.value
      address = backend.value
    }
  }
}
```

### Expected Behavior
```
$ terraform validate
Success! The configuration is valid.
```

### Actual Behavior
```
$ terraform validate

Error: Insufficient domain blocks

  on main.tf line 1, in resource "fastly_service_v1" "test":
   1: resource "fastly_service_v1" "test" {

At least 1 "domain" blocks are required.
```

### Additional Context

If I unroll `test_override.tf` to
```hcl
resource "fastly_service_v1" "test" {
  backend {
    name = "a"
    address = "a"
  }
  backend {
    name = "b"
    address = "b"
  }
}
```

It works just fine. Changing `main.tf` not to use `dynamic` block also makes the problem disappear. The problem occurs only when `dynamic` block is used in different files. I guess because `dynamic` blocks from `_override` file override blocks from the main one

**Comment by apparentlymart** [comment]
Hi @libc! Thanks for reporting this.

I think you've identified the cause here indeed: the override-processing logic happens long before dynamic blocks are expanded, and so it sees them as just normal blocks that get processed per the normal block override rules: any block of a given type overrides all existing blocks of that type.

Seems like we need an exception in the override-processing logic to recognize `dynamic` blocks in particular and use the first label as the discriminator instead.

I think we'll need to add some new settings to `mergeBody` (the component that deals with the block content merging behavior) so that we can handle this during the merging of the blocks:

https://github.com/hashicorp/terraform/blob/50a101afbd3cabbd2ed1adce02213ae16e894f5d/configs/module_merge_body.go#L85-L103

There is some complexity here in that the merging behavior here doesn't itself have access to the information about which block types can and cannot be `dynamic` in each context, so I think we'll need to add a new argument to `MergeBodies` to specify the block types that cannot and then have the various callers pass that in using their block-type-specific knowledge, such as here in the call for resource blocks where we'd need to tell it that `provisioner` and `connection` are not `dynamic`-able:

https://github.com/hashicorp/terraform/blob/50a101afbd3cabbd2ed1adce02213ae16e894f5d/configs/module_merge.go#L233

This seems doable, though will require a little reorganization.
