### ISSUE TITLE
.12 test framework doesn't correctly handle deletions from state

### ISSUE THREAD

**Issue by katbyte** [hashicorp/terraform#20763]
We have tracked down some test failures to the .12 test harness not correctly handling resources being deleted from the state. These would pass in .11:

```go
	deleteNatPoolState := func(s *terraform.State) error {
		return s.Remove("azurestack_lb_nat_pool.test")
	}
...
			{
				Config: testAccAzureStackLoadBalancerNatPool_basic(ri, natPoolName, testLocation()),
				Check: resource.ComposeTestCheckFunc(
					testCheckAzureStackLoadBalancerExists("azurestack_lb.test", &lb),
					testCheckAzureStackLoadBalancerNatPoolExists(natPoolName, &lb),
					deleteNatPoolState,
				),
				ExpectNonEmptyPlan: true,
			},
```
We have determined we no longer require the tests but as this seems to be a bug have opened this issue. (tests have been removed in azurerm but are still in azurestack)

### Terraform Version
azurestack and aurerm build with `terraform@pluginsdk-v0.12-early5`

### Terraform Configuration Files
see the test here: https://github.com/terraform-providers/terraform-provider-azurestack/blob/92e88f8fd06bf039f8bfa347e17d9f548b967c42/azurestack/resource_arm_loadbalancer_nat_pool_test.go#L108

### Expected Behavior
Test should pass as in .11

### Actual Behavior
got the error: `testing.go:568: Step 0 error: Expected a non-empty plan, but got an empty plan!`

### Steps to Reproduce
build `azurestack@012/early4` and run the `TestAccAzureRMLoadBalancerNatPool_reapply` test

**Comment by apparentlymart** [comment]
Thanks for raising this, @katbyte!

While this is a change of behavior from before, I don't know that we ever _expected_ check functions to be making modifications to the state... the contract for those is to _inspect_ the state and make assertions about it.

I think the reason thus has stopped working is because the test harness now operates on a copy of the state because Terraform internally uses entirely new types for state and so must shim to the old types just in time to call into the test code. Since this test is no longer present, and since this was arguably not expected to work in the first place, I think we will leave this unresolved for now unless we find that there are other tests depending on it and there's no reasonable way to rewrite them so that they _don't_ try to mutate the state during check functions.

**Comment by katbyte** [comment]
Sounds good to me, thanks for the explanation @apparentlymart !

**Comment by apparentlymart** [comment]
Great, thanks for confirming @katbyte!

In that case, I'm going to close this out for now and we can reopen it again if we find that we need some sort of resolution here. If we do, I expect it'll probably come in the form of a new feature in the test harness that is explicitly _for_ making modifications to the state, since then we can try to build it in a higher-level way that doesn't rely on direct mutations of the old-world data structure.
