### ISSUE TITLE
Requesting assistance over in terraform-provider-kubernetes

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform#20788]
I'm sorry for making noise here - I'm well aware it's not the right place.

The official Terraform Kubernetes provider is unusable for many cases due to the merge of https://github.com/terraform-providers/terraform-provider-kubernetes/pull/50 in August 2017. Despite many calls for that to be reverted ([here](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/50#issuecomment-356752501), [here](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/50#issuecomment-451719662), and especially [here](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/199) and [here](https://github.com/terraform-providers/terraform-provider-kubernetes/pull/244)), this still remains an unresolved issue in March 2019.

Several people have put in effort to try to resolve something that probably shouldn't have been merged in the first place, but these efforts have been waiting for feedback from maintainers since December 2018.

Are additional resources able to be applied to the Kubernetes provider to get it back to a working state?

Alternatively - something I have [suggested before](https://github.com/hashicorp/terraform/pull/18462) - if there is an official Terraform provider that is not in a working state, it shouldn't be listed as official.

**Comment by paultyng** [comment]
@tdmalone I don't think anyone disagrees with you, including us, that the situation with annotations (and other server side mutations) complicates a lot of normal use cases with Kubernetes. The underlying issues are that the diff Terraform does is different from the diff `kubectl apply` does (really looking forward to server side apply), etc. and there are additional issues with `Computed` (returned from the API) state in Kubernetes vs Terraform's assumptions.

Much of that logic though is in flux in the SDK a little during the 0.12 work and we were hoping to let that settle before solving it in a more holistic manner, but we are definitely aware of the issue. Due to 0.12's delays the work just kept getting pushed out farther and farther.

Regarding "official" providers, I also agree that its not entirely clear what is supported by HashiCorp and what is not within the `terraform-providers` org, the org was a historic shortcut we used so we could release a lot more providers with our signing key for security, not something we meant to indicate we support all of them directly. The work on the provider registry though will make this all a lot more clear in the future, allowing providers to be released (for use within `terraform init`) from their own organizations and repos.

**Comment by paultyng** [comment]
Also, just to be entirely clear, we have a person on my team whose primary work is the Kubernetes provider (and Helm), and there are use cases where that provider works perfectly well for people now despite this missing piece.

Feel free to reach out to me directly via email (ptyng@hashicorp.com) or on HangOps or something if you'd like to discuss further. Going to close this issue in the core repo.
