### ISSUE TITLE
Crash after switching from 11.10 to 11.13. Resolves after deleting .terraform folder

### ISSUE THREAD

**Issue by pcp-tcp** [hashicorp/terraform#20796]
### Terraform Version

```
Terraform v0.11.13
...
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

<script src="https://gist.github.com/pcp-tcp/43c98532d1267c33e012464ae95b0020.js"></script>

### Steps to Reproduce

1. Download and installed terraform v0.11.13
2. Navigate to my terraform configuration folder
3. Run terraform init
4. Run terraform apply
5. Observe crash

### Additional Context

I have a couple of environment variables set, but they are not referenced in the configuration that I was attempting to run. I also should mention that after I deleted my .terraform folder and let it rebuild with a terraform init again, everything worked fine

**Comment by pcp-tcp** [comment]
Adding link to Gist

https://gist.github.com/pcp-tcp/43c98532d1267c33e012464ae95b0020

**Comment by apparentlymart** [comment]
Hi @pcp-tcp! Sorry for this crash and thanks for reporting it.

This is the same problem as being discussed in #20712, so I'm going to close this to consolidate the discussion. You already found the workaround that was discussed there, of deleting `.terraform` and reconstructing it from scratch; the bug is in some logic that was attempting to upgrade a file in that directory to a slightly different format.
