### ISSUE TITLE
How to create multiple aws_instance resources with configuration template containing each instance's  attribute(e.g private_ip)?

### ISSUE THREAD

**Issue by Odko** [hashicorp/terraform#20808]
How to create multiple aws_instance resources with configuration template containing each instance's  attribute(e.g private_ip)?

I came up with the following config but it results 
`* Cycle: data.template_file.vault_config, aws_instance.vault`
```
data "template_file" "example_config" {
  count         = "${var.instance_count}"
  template      = "${file("config/default.tpl")}"
  vars          = {
    private_ip = "${aws_instance.example.*.private_ip[count.index]}"
  }
  depends_on = ["aws_instance.example"]
}
resource "aws_instance" "example" {
  count         = "${var.instance_count}"
  provisioner "file" {
    content     = "${element(data.template_file.example_config.*.rendered,count.index)}"
    destination = "/tmp/config"
  }
}
```

**Comment by apparentlymart** [comment]
Hi @Odko,

As you've seen, you can't have a template that depends on a resource also be used in the provisioning of that resource, because there is no ordering Terraform could process those resources in that would lead to a correct result.

In Terraform 0.11, the best options here are either to have the instances find their own IP addresses some other way (e.g. using DHCP) or to include the template inline in the `content` argument of the `provisioner "file"` block where it can refer to `self.private_ip` to get the IP address.

In the forthcoming Terraform 0.12, the `template_file` data source has been recast as a built-in function [`templatefile`](https://www.terraform.io/docs/configuration/functions/templatefile.html), which will make this easier:

```hcl
resource "aws_instance" "example" {
  count         = "${var.instance_count}"
  provisioner "file" {
    content     = templatefile("${path.module}/config/default.tpl", { private_ip = self.private_ip })
    destination = "/tmp/config"
  }
}
```

`templatefile` will fill in the missing capability here of both having the template sourcefactored out into a separate file _and_ using references that are only valid in localized contexts like this.

**Comment by Odko** [comment]
Thanks, That's what i was looking for.

Since `Terraform 0.12` is not yet been released, i came up with solution copying template file with `file provisioner` block and substituting variables with `remote-exec provisioner` block using `sed` command :smiley: . 

Like:
```
resource "aws_instance" "example" {
  count         = "${var.instance_count}"
  provisioner "file" {
    source      = "config/default.tpl"
    destination = "/tmp/config.tpl"
  }
  provisioner "remote-exec" {
    inline = [
      "sed -i 's|\$\{private_ip\}|${self.private_ip}|g' /tmp/config.tpl",
    ]
  }
}
```
