### ISSUE TITLE
The argument "host" is required, but no definition was found.

### ISSUE THREAD

**Issue by wesmartin17** [hashicorp/terraform#20816]
### Terraform Version
```
Terraform v0.12.0-beta1
+ provider.aws v1.60.0-dev20190216h00-dev
+ provider.local v1.2.0
+ provider.random v2.1.0
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "default" {
  ami                   = var.dsm_ami
  instance_type         = var.dsm_instance_type
  security_groups       = var.dsm_security_groups
  iam_instance_profile  = var.dsm_iam_instance_profile
  key_name              = var.dsm_key_pair
  tags                  = local.tags

  /* copy up private keyfile for chef-solo to use */
  
  provisioner "file" {
    source = "~/.ssh/Oregon.pem"
    destination = "/home/ec2-user/.ssh/Oregon.pem"
    connection {
      type = "ssh"
      user = "ec2-user"
      private_key = "${file("~/.ssh/Oregon.pem")}"
    }
  }
}
```

### Debug Output
```
2019/03/25 11:38:43 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
Error: Missing required argument

  on main.tf line 27, in resource "aws_instance" "default":
2019-03-25T11:38:43.461-0400 [DEBUG] plugin: plugin process exited: path=C:\Terraform\terraform.exe pid=2384
2019-03-25T11:38:43.461-0400 [DEBUG] plugin: plugin exited
  27: resource "aws_instance" "default" {
2019-03-25T11:38:43.463-0400 [DEBUG] plugin: plugin process exited: path=C:\Users\wesleym\AppData\Roaming\terraform.d\plugins\windows_amd64\terraform-provider-aws_v1.60.0-dev20190216H00-dev_x4.exe pid=15504

2019-03-25T11:38:43.463-0400 [DEBUG] plugin: plugin exited
The argument "host" is required, but no definition was found.
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan` or `terraform apply`

**Comment by jbardin** [comment]
Hi @wesmartin17,

Sorry about the rather unhelpful error output here. This is the expected result because you're missing the required `host` field in the connection block. You most likely want `host = self.public_ip` for an `aws_instance`.

I'm going to keep this open, and see if we can't improve the validation output here to provide more context and possibly catch it earlier in validation.

**Comment by apparentlymart** [comment]
There is more information about this in the upgrade guide section [Default settings in `connection` blocks](https://www.terraform.io/upgrade-guides/0-12.html#default-settings-in-connection-blocks).

**Comment by wesmartin17** [comment]
Great! Thank you so much for getting to this so quickly @jbardin @apparentlymart I must have missed that i

**Comment by apparentlymart** [comment]
It seems like there is a bug somewhere in the vicinity of [`validateConnConfig`](https://github.com/hashicorp/terraform/blob/1f241f8f836678fab3da9ca7df1a9f3d99a5c1af/terraform/eval_validate.go#L162:35) because the source location reported for this error is, somehow, the header of the containing `resource` block rather than the the `connection` block where the problem is. With that said, at first glance it's not clear to me how that could be since this codepath doesn't even have access to the containing block to report it as a location; perhaps this is actually being reported elsewhere too and whatever other codepath is validating this is not setting the source location properly.

**Comment by jbardin** [comment]
It's actually not caught in validation, and the error isn't found until provisioning (`EvalApplyPost`). 
I don't think there's there's any context, and it's simply reporting which resource failed to provision.

**Comment by bgarcial** [comment]
I am following the Azure guide, and when I added `host = self.public_ip` as a default setting in connection IP I get this:
```
⟩ terraform plan -out tfprov

Error: Unsupported attribute

  on main.tf line 198, in resource "azurerm_virtual_machine" "vm":
 198:       host = self.public_ip

This object has no argument, nested block, or exported attribute named
"public_ip".
```

Finally I had to put `host = "${azurerm_public_ip.publicip}"` which reference my azurerm_public_ip resource previously defined, and it's works.

**Comment by apparentlymart** [comment]
Hi @bgarcial!

It seems that something has changed in the Azure provider itself that has affected what is shown in the getting started guide. For that, it may be best to ask in [the AzureRM provider's own repository](https://github.com/terraform-providers/terraform-provider-azurerm) to see if the documentation needs to be updated and whether the update you made here is the best one.

**Comment by shurick81** [comment]
For me it worked like this:

```
  provisioner "remote-exec" {
    connection {
      user     = "${var.vm_admin_username}"
      password = "${var.vm_admin_password}"
      port     = 5986
      https    = true
      timeout  = "10m"

      # NOTE: if you're using a real certificate, rather than a self-signed one, you'll want this set to `false`/to remove this.
      insecure = true
      host = azurerm_public_ip.main.ip_address
    }
    inline = [
      "powershell.exe -command \"Write-Host '$(Get-Date) Provisioning is done'\""
    ]
  }
```

```
resource "azurerm_public_ip" "main" {
  name                = "unionen-sharepoint-${var.environmentId}-${var.vm_name}-pip"
  location            = "westeurope"
  resource_group_name = "${var.vm_resource_group_name}"
  allocation_method   = "Dynamic"
  domain_name_label   = "${var.vm_domain_name_label}"
}
```

**Comment by bgarcial** [comment]
Hi @apparentlymart, thanks for your support

I've changed  the `host = "${azurerm_public_ip.publicip.name}"` by `host = "${azurerm_public_ip.publicip.ip_address}"` like @shurick81 suggest and it's works.

Of anyway, there are several details which would be nice were updated on the guide.
One of them is related to the `tags` attribute, ([which you already pointed to someone in the right path](https://github.com/hashicorp/terraform/issues/19325))

Also in the definition of the `azurerm_public_ip` resource, in this 0.12 version, the `public_ip_address_allocation` attribute was deprecated in favor of `allocation_method`

How can I report this small details in order to be corrected in the guide? 
Maybe here in the [Azure RM provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues) repo like you told me?

**Comment by apparentlymart** [comment]
The "Getting Started" guides are unusual in that while they are provider-specific we think of them as guides for Terraform Core -- they are primarily about how to use Terraform itself rather than how to use the provider.

With that said, if you make a new issue in this repository then we'll label it so the team who maintains the learning guides can find it. Thanks!

**Comment by bgarcial** [comment]
@apparentlymart  Ok, nice. I still doing the Azure Guide. I will share the issues here when it has finished

**Comment by zacharybk** [comment]
I encountered the same error on DigitalOcean. It was fixed by specifying `host = "self.public_ip"`

```
connection {
        user = "root"
        type = "ssh"
        private_key = "${var.pvt_key}"
        timeout = "2m"
        host = "self.public_ip"
}
```

**Comment by danrl** [comment]
FYI: On Google Compute Engine (GCE) `host = "self.public_ip"` works fine.

**Comment by danrl** [comment]
I am using `host = "${google_compute_instance.default.network_interface.0.access_config.0.nat_ip}"` for Google Compute Engine ephemeral, external IP addresses.

**Comment by petervandenabeele** [comment]
For Google Compute Engine, the `terraform 0.12upgrade` command, initially suggested this:

```
     access_config {
-      nat_ip = "${data.google_compute_address.<name-of-static-ip>.address}"
+      nat_ip = data.google_compute_address.<name-of-static-ip>.address
     }

...
   provisioner "remote-exec" {
     connection {
+      host = coalesce( # TF-UPGRADE-TODO: Simplify this to reference a specific desired IP address, if possible.
+        concat(
+          # Prefer any available NAT IP address
+          flatten([
+            for ni in self.network_interface : [
+              for ac in ni.access_config : ac.nat_ip
+            ]
+          ]),
+
+          # Otherwise, use the first available LAN IP address
+          [
+            for ni in self.network_interface : ni.network_ip
+          ],
+        )...
+      )
       type = "ssh"
```

With this config of a static IP, this code worked ok:

```
host = data.google_compute_address.<name-of-static-ip>.address
```

**Comment by apparentlymart** [comment]
Hi @petervandenabeele!

Indeed, there are lots of different ways to configure IP addresses for Google Compute and the upgrade tool isn't smart enough to understand those different ways, so it produces this complex expression that is essentially a direct port of the logic the provider itself would've used in Terraform 0.11 and prior. We added that `# TF-UPGRADE-TODO` comment because in practice there's usually a much simpler expression to replace it with, as in your case, but it requires some knowledge about how the rest of the configuration is built and is thus better done via human intuition than by heuristic.

**Comment by fosskers** [comment]
Note that the docs for `Provisioner Connections` still claims:
```
host - The address of the resource to connect to. This is usually specified by the provider.
```
https://www.terraform.io/docs/provisioners/connection.html#host

**Comment by ricardojlrufino** [comment]
I encountered the same error on DigitalOcean.
Change: SERVERNAME

```
    connection {
      type     = "ssh"
      private_key = "${file("~/.ssh/id_rsa")}"
      user     = "root"
      timeout  = "2m"
      host = "${digitalocean_droplet.SERVERNAME.ipv4_address}"
    }
```

**Comment by pablofmorales** [comment]
@ricardojlrufino 

```
    host = "${digitalocean_droplet.name.ipv4_address}"

```

**Comment by SAi0401** [comment]
aws_instance.sunday (remote-exec): Connecting to remote host via SSH...
aws_instance.sunday (remote-exec):   Host: self.public_ip
aws_instance.sunday (remote-exec):   User: root
aws_instance.sunday (remote-exec):   Password: false
aws_instance.sunday (remote-exec):   Private key: true
aws_instance.sunday (remote-exec):   Certificate: false
aws_instance.sunday (remote-exec):   SSH Agent: false
aws_instance.sunday (remote-exec):   Checking Host Key: false
aws_instance.sunday: Still creating... [5m50s elapsed]
aws_instance.friday: Still creating... [5m20s elapsed]

aws_instance.friday (remote-exec): Connecting to remote host via SSH...
aws_instance.friday (remote-exec):   Host: self.public_ip
aws_instance.friday (remote-exec):   User: root
aws_instance.friday (remote-exec):   Password: false
aws_instance.friday (remote-exec):   Private key: true
aws_instance.friday (remote-exec):   Certificate: false
aws_instance.friday (remote-exec):   SSH Agent: false
aws_instance.friday (remote-exec):   Checking Host Key: false
aws_instance.friday: Still creating... [5m30s elapsed]


Error: timeout - last error: dial tcp: lookup self.public_ip: no such host



Error: timeout - last error: dial tcp: lookup self.public_ip: no such host

Hi @jbardin I did the same as according to your earlier response, But the issue still exists.
