### ISSUE TITLE
Regex issue for `listener_arn`

### ISSUE THREAD

**Issue by mohitm108** [hashicorp/terraform#20821]
I need to give two values to listener_arn. These are `aws_alb_listener.xyz.arn` and `aws_alb_listener.xyz_https.arn`. I tried to make a list but listener_arn accepts only string values. I got this error `listener_arn must be a single value, not a list`. Is it possible I can give two values to this using regex like *

**Comment by mildwonkey** [comment]
Hi @mohitm108 ,
Unfortunately, without more information about your terraform configuration it's hard to answer your question. Can you update this issue with the relevant configuration files (removing any sensitive information)? 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by mohitm108** [comment]
resource "aws_alb_listener" "xyz" {
  load_balancer_arn = "${aws_alb.myloadbalancer.arn}"
  port              = "80"
  protocol          = "HTTP"

  default_action {
    target_group_arn = "${aws_alb_target_group.my_tg.arn}"
    type             = "forward"
  }
}

resource "aws_alb_listener" "xyz_https" {
  load_balancer_arn = "${aws_alb.my_alb.arn}"
  port              = "443"
  protocol          = "HTTPS"


  default_action {
    target_group_arn = "${aws_alb_target_group.my_tg.arn}"
    type             = "forward"
  }
}


resource "aws_alb_listener_rule" "test" {
  count        = 1
#This is the listener arn where i want to give values of two aws_alb_listener's arn but I am able to give only one
  listener_arn = "${aws_alb_listener.xyz_*.arn}"

  priority     = 100

  action {
    type             = "forward"
    target_group_arn = "${aws_alb_target_group.abc.arn}"
  }

  condition {
    field  = "host-header"
    values = ["www.google.com"]
  }

  lifecycle {
    create_before_destroy = true
  }
}
