### ISSUE TITLE
TFE Plan crashes Terraform

### ISSUE THREAD

**Issue by gregglowrimore** [hashicorp/terraform#20833]
### Terraform Version

```
0.11.11
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

I don't have access to the crash.log (Use TFE), but here's the workspace log link: https://app.terraform.io/app/Nutrien/workspaces/data-lake-sandbox/runs/run-XdEcdTA5JzTYvUUx

**Comment by apparentlymart** [comment]
Hi @gregglowrimore! Sorry for this crash, and thanks for reporting it.

The Terraform Core engineering team doesn't have access to arbitrary customer Terraform Enterprise accounts, so we can't see what you shared there. Since you are a Terraform Enterprise customer, please instead contact the Terraform Enterprise customer support team: they _do_ have the required access to see what you are sharing and will be able to provide relevant, non-sensitive subsets of that information to the Terraform Core engineering team if necessary to address the problem.

**Comment by apparentlymart** [comment]
Hi again, @gregglowrimore!

I didn't hear from you again, so I'm going to close this in the hope that you reached out to Terraform Enterprise customer support and they were able to help you. Thanks!
