### ISSUE TITLE
AzureRM backend support for AD auth (no need for keys)

### ISSUE THREAD

**Issue by scott1138** [hashicorp/terraform#20831]
### Current Terraform Version
0.11.13

### Use-cases
Authenticating to Azure Storage using the current credential

### Attempted Solutions
Storage Key works but doesn't offer granular control, stores the storage key in the state file, and changing keys can be difficult in a possible compromise.

### Proposal
MS has added support for adding AzureAD/AD users to roles like "storage blob data contributor" to that the proliferation of keys is not required.  Allow Terraform to use these credentials the same way the az cli does to access the storage account.

**Comment by tombuildsstuff** [comment]
hi @scott1138 

Thanks for opening this issue.

The next major version of Terraform, Terraform 0.12 adds support for authenticating using both the Azure CLI and a Managed Service Identity - [more information is available here](https://www.terraform.io/docs/backends/types/azurerm.html). Unfortunately the website's a little misleading since this isn't available in Terraform 0.11 - but once Terraform 0.12 is out you should be able to take advantage of this; would you be able to take a look and see if that solves your use-case?

Thanks!

**Comment by scott1138** [comment]
Thanks for the reply @tombuildsstuff - that makes sense.  I'll try it as soon as I can and report back.

**Comment by J0F3** [comment]
Actually also with 0.12 is is only partially true that AAD Credentials are used to access the backend storage account. 

While you can configure the backend to use AD credentials it still uses the Access Key behind the scenes.
https://github.com/hashicorp/terraform/blob/3085da3dd5d3b520d67a72da601789d326afbecc/backend/remote-state/azure/arm_client.go#L134

So the "storage blob data contributor" role is not enough for the azurerm backend. The account or service principals/MSI used to access the the backend still needs at least also the "Storage Account Key Operator Service Role" role. Which means the Terraform backend has always access the the Access Key and therefore full access to the wohle Storage Account (not only the Blobs)...

Maybe this should be at least stated in the documentation and I think long term it should be considered that the backend access the blob storage truly with AAD Credentials instead of Storage Account Keys.

**Comment by tombuildsstuff** [comment]
@J0F3 unfortunately Active Directory authentication for Storage requires non-default permissions which most users don't have; thus I believe we'll need to default to Shared Key authentication for the foreseeable future.

From our side support from this is blocked on migrating to [the Giovanni Azure Storage SDK](https://github.com/tombuildsstuff/giovanni) which @mbfrahry will be looking into - once that's done we should be able to take a look into this.

Thanks!

**Comment by J0F3** [comment]
@tombuildsstuff thanks for your respond. 
However I am not sure what you mean by "requires non-default permissions"? To access the blob storage with Azure AD authentication (which is the recommend way now)  the builtin "Storage Blob Data Contributor" and "Reader" role is needed on the Storage Account level at least. 
These are standard Azure Roles and if someone has higher roles assigned (e.g. Contributor or Owner on the Subscription) he has the required permissions also. So when someone can read the Storage Account Access Keys he has anyway enough access on the storage account to use also Azure AD authentication. Or I am wrong?

Thanks!

**Comment by tombuildsstuff** [comment]
@J0F3 

>  To access the blob storage with Azure AD authentication (which is the recommend way now) the builtin "Storage Blob Data Contributor" and "Reader" role is needed on the Storage Account level at least.
> These are standard Azure Roles and if someone has higher roles assigned (e.g. Contributor or Owner on the Subscription) he has the required permissions also. So when someone can read the Storage Account Access Keys he has anyway enough access on the storage account to use also Azure AD authentication. Or I am wrong?

We released this change in AzureRM a while back and users reported authentication errors even when they had Contributor rights to the Subscription (and thus were able to access the keys) -unless they had the additional `Storage Blob Data Contributor|Reader` roles then they were unable to access the storage account using AzureAD, at least through the API; as such we ended up needing to revert to using SharedKey authentication for these users.

As such whilst we plan to offer support for this functionality, unfortunately we can't make this the default authentication method since the `Contributor` permissions aren't necessarily sufficient (at least for pre-existing users/assignments).

Thanks!

**Comment by tombuildsstuff** [comment]
@J0F3 

> Maybe for long term some sort of 'flag' (true or false setting) could be added. So you could define if the backend should use the Storage Account Key or use only Azure AD authentication (when you are sure that the right role assignment are made).

Yep, that's vaguely the plan - something like `use_azuread_authentication` (as an example) which defaults to false.

From our side we need to switch over to using [Giovanni](https://github.com/tombuildsstuff/giovanni) first - but once that's done this should be possible for someone to take a look at :)

**Comment by tcz001** [comment]
Hi @tombuildsstuff is this still in your roadmap, we can help to implement this

**Comment by ChrisF987** [comment]
I think that this issue is preventing me using AD authentication to access a remote state of another terraform configuration (ie as a **data.terraform_remote_state** resource). Theoretically I only need read access to this other terraform state file, so was hoping that Storage Blob Data Reader would be enough access. However, when I run the plan it's trying to do the listKeys action. As assigning this access provides full read/write access to the Storage Account I do not want to do this. 

```
  on provider.tf line 24, in data "terraform_remote_state" "management_groups":
  24:   backend = "azurerm"

error loading the remote state: Error retrieving keys for Storage Account
"<storageaccountname>": storage.AccountsClient#ListKeys: Failure responding to
request: StatusCode=403 -- Original Error: autorest/azure: Service returned an
error. Status=403 Code="AuthorizationFailed" Message="The client
'<service-principal-object-id>' with object id
'<service-principal-object-id>' does not have authorization to perform
action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope
```

**Comment by stazz** [comment]
The existance of this functionality would be particularly important for us, as we would like to have one storage account containing several TF states (each in its own container) for pipelines which we wish to keep isolated. With access keys, any pipeline will be able to get full access to the TF state of other pipelines (either accidentally or on purpose). With AD authentication, we could assign each pipeline identity corresponding role only on the matching container (or maybe just write access to own state + read access to some other states, if so needed), thus achieving the isolation requirements.

**Comment by sirlatrom** [comment]
@tombuildsstuff I see the plan is to switch to [Giovanni](https://github.com/tombuildsstuff/giovanni), but when [searching for it](https://github.com/terraform-providers/terraform-provider-azurerm/issues?q=is%3Aissue+is%3Aopen+giovanni) in the terraform-provider-azurerm repo I don't see any specific issue for that work. Is it considered included in the other issues? Or should I search in hashicorp/terraform?

**Comment by edoboker** [comment]
Hey guys,
Any update on this? This is a really critical feature, which is currently preventing us from migrating to terraform for all of our Azure deployments...

**Comment by mathiasch** [comment]
@tombuildsstuff : May I help to switch to Giovanni? I am depending on that, so if you need help...

**Comment by ams0** [comment]
Bump into this when implementing exactly the scenario @stazz mentioned. I'd love to see this move forward and happy to help test out builds if needed.

**Comment by matt-FFFFFF** [comment]
I think the initial confusion around the permissions model requiring `Storage Blob Data Contributor` may have been further confused by the fact that it can take a period of time before the IAM permissions are effective. So if you have just created the role assignment and immediately run an `init` then it may fail until things have coalesced.

**Comment by randywallace** [comment]
This is a fun one to explain at work, but essentially, the "management" roles (Owner, Contributor, Reader) provide no access to Data, hence the "Data" roles; the same problem applies for the Event Hub, Service Bus Queues, and so on.  I'm all for requiring the "Storage Blob Data *" Roles being assigned to the requisite users because, in the long run, it is more secure.  That being said, so far our experience has been that you can't both directly access an Azure Storage Account container via REST+AzureAD JWT Token Authorization *and* have a strict firewall in place.. so there is that.  Certainly, playing the listKeys game to pull the current Key is a reasonable workaround (as these values are only stored in memory); that said, I'd like to see Azure get rid of these Full access keys, if only b/c it would finally remove our requirement to regenerate (rotate) the keys on all our storage accounts all the time..

I can't say Azure documents any of this very well (at all), but the model, once teased out, makes sense.

**Comment by J0F3** [comment]
> Certainly, playing the listKeys game to pull the current Key is a reasonable workaround 

I don't think so. Especially not that the Terraform documentation does not state a single word about it and instead speaks about Service Principal and MSI Authentication which is just misleading. And that is exactly where all the confusion starts. Because the Terraform backend still uses the Shared Key authorization in the background (even when using MSI or Service Principal) the "Data" Roles do not apply and you still need one of the "management" roles to read the Access Keys. 

> I'd like to see Azure get rid of these Full access keys, if only b/c it would finally remove our requirement to regenerate (rotate) the keys on all our storage accounts all the time..

That is on the way and is available a a preview already today:
https://docs.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal

> I can't say Azure documents any of this very well (at all), but the model, once teased out, makes sense.

I do not agree I think the Azure documentation is quite clear about that: 
https://docs.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal

But as I written above the documentation which is not clear is the one about the Terraform backend. It say it uses MSI or Service Principal for authentication but this actually not true. It only uses the Service Principal or the MSI to get the Shared Access key. From then on the actual access to the Blob Storage works the very old way, anonymously, using the Shared Access key authorization. So I strongly believe there should be at least a note in the Terraform documentation about that fact. 

But what I find really concerning is the fact that form Hashicorp side there is no answer for about more than a year now about this topic while it is a really critical point if you want to use Terraform in a productively in a lager enterprise with strict security requirement. 

@tombuildsstuff Any updates?

**Comment by ams0** [comment]
I agree with @J0F3 . If I can write and read from a blob with an SP credential with correct RBAC permissions, why can't TF do the same? Retrieving keys should not be necessary now that we have the correct way of accessing storage.
