### ISSUE TITLE
Terraform crash after upgrading from v0.11.8 to v0.11.13

### ISSUE THREAD

**Issue by simonlegeek** [hashicorp/terraform#20844]
I upgraded my terraform binary to v0.11.13 and ran a terraform plan in one of my deployment and I received the typical crash message.

Haven't done much reseach yet, but crash message encouraged me to submit this crash so here it is!

Crash log is included

[crash.log](https://github.com/hashicorp/terraform/files/3014174/crash.log)

**Comment by CyanMass45** [comment]
Same here, upgraded from 0.11.11 to 011.13 and crash immediately. logs attached as well, similar to above crash tho.

[crash.log](https://github.com/hashicorp/terraform/files/3017194/crash.log)

**Comment by simonlegeek** [comment]
@CyanMass45 I found that if I delete the .terraform folder and run `terraform init` again in the configuration folder, it recreates the .terraform folder solves the issue. 

Hope it helps!

**Comment by teamterraform** [comment]
Hi all! Sorry for this crash, and thanks for reporting it.

Unfortunately there was a bug in v0.11.13 where it didn't correctly handle a legacy file format in a file in the `.terraform` directory. Deleting the directory and then running `terraform init` worked around it because then Terraform could recreate that file from scratch rather than trying (and failing) to upgrade it.

This bug was fixed for v0.11.14, so we're going to close this now.
