### ISSUE TITLE
Formatting error on docs for azurerm_storage_account

### ISSUE THREAD

**Issue by philipstreet-hiscox** [hashicorp/terraform#20840]
Occasionally the sidebar does not appear in the documentation. An example page where this happens is;

https://www.terraform.io/docs/providers/azurerm/r/storage_account.html

Instead of the sidebar I get the following text at the top of the page;

"layout: "azurerm" page_title: "Azure Resource Manager: azurerm_storage_account" sidebar_current: "docs-azurerm-resource-storage-account" description: |-"

**Comment by mildwonkey** [comment]
thank you for reporting this @philipstreet-hiscox !

**Comment by apparentlymart** [comment]
It looks like there's a formatting error in the source document that is preventing the website renderer from detecting the YAML metadata block at the top. Since this page comes from the AzureRM provider's docs the fix will be over in that repository, so I'm going to ask our bot to migrate the issue over there.
