### ISSUE TITLE
Network AWS ACL ICMP Issue

### ISSUE THREAD

**Issue by rainmanh** [hashicorp/terraform#2085]
Hi

Currently using version 0.5.2
I am trying to upload a simple ACL containing port 1 so ICMP and it does not matter how I mix and match it get errors.

I have tried:

```````
resource "aws_network_acl" "external" {
    vpc_id = "${var.aws_vpc_production_id}"
    subnet_ids = "${var.subnet_external}"
  tags {
    Name = "external"
  }
    ingress = {
        protocol = "icmp"
        rule_no = 9996
        action = "allow"
        cidr_block =  "192.168.1.0/24"
        from_port = 0
        to_port = 0
    }
}




resource "aws_network_acl" "external" {
    vpc_id = "${var.aws_vpc_production_id}"
    subnet_ids = "${var.subnet_external}"
  tags {
    Name = "external"
  }
    ingress = {
        protocol = "1"
        rule_no = 9996
        action = "allow"
        cidr_block =  "192.168.1.0/24"
        from_port = 0
        to_port = 0
    }
}

```````

and I get:

* Error creating ingress entry: %!s(<nil>)

Any idea?

thanks!

**Comment by catsby** [comment]
Hello @rainmanh – sorry for the trouble here. The error is being hidden because of a typo in the code which I will fix (thanks!)

I've reproduced the case and this is the error:

```
* Error creating ingress entry: MissingParameter: The request must contain the parameter icmpTypeCode.type
	status code: 400, request id: []
```

You're using the ICMP protocol, but Terraform doesn't let you set the type or code required :frowning: 

Those too can be added, but I admit I'm unfamiliar with their details. Do you have an example of what type/code you are seeking to use? 

Thanks!

**Comment by catsby** [comment]
Hey @rainmanh – I submitted #2148 to address this, hopefully you can check it out

**Comment by rainmanh** [comment]
Hey @catsby . That sounds really good. thanks!
