### ISSUE TITLE
How to download files from Azure blob using terraform file provider 

### ISSUE THREAD

**Issue by Sas002** [hashicorp/terraform#20864]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-aws)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

How to download file from Azure blob using terraform file or storage module. I do not see any command .

**Comment by Sas002** [comment]
azurerm_storage_container.blobstorage  .

I can see the upload and get the url as output . But there is no way to specify download from azure blob as source 

resource "azurerm_storage_blob" "blobobject" {
  depends_on             = ["azurerm_storage_container.blobstorage"]
  name                   = "index.html"
  resource_group_name    = "${azurerm_resource_group.resgrp.name}"
  storage_account_name   = "${azurerm_storage_account.storageaccount.name}"
  storage_container_name = "${azurerm_storage_container.blobstorage.name}"
  type                   = "block"
  source                 = "index.html"
}

**Comment by jbardin** [comment]
Hi @Sas002, this seems to be a question about using a particular provider. I'll move the issue over there for now.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
