### ISSUE TITLE
auto.tfvars fails without explaining the tfvars file is malformated

### ISSUE THREAD

**Issue by toxik-io** [hashicorp/terraform#20873]
### Terraform Version
```
Terraform v0.11.13
```

### Terraform Configuration Files
```hcl
invalid_key=stringsshouldbequoted
```

### Debug Output
https://gist.github.com/toxik-io/53be0593de75143e625ef72415df7249

### Expected Behavior
I expected it to print the troublesome config error, so as to guide users to correctly format their configs.

### Actual Behavior
It prints usage info without indicating the problem.

### Steps to Reproduce
1. init a project
2. realize you want to automate stuff with a tfvars file (like any newb will realize)
3. make a malformed `*.auto.tfvars` file.
4. run terraform plan
5. get unhelpful feedback

### Additional Context
I like terraform. It just doesn't log problems very well. You sit around for ages wondering... why couldn't it log just where it failed without the whole debugger output enabled?

If we have the error it's mad about... it would be really helpful to print /that/ to the user, not usage :disappointed:.

### References
I'm not entirely sure which other issues help with this one.

**Comment by apparentlymart** [comment]
Hi @toxik-io! Sorry for this confusing output.

In the example you shared, the following line is Terraform trying to report the problem:

```
invalid value "hello.auto.tfvars" for flag -var-file-default: Error parsing hello.auto.tfvars: At 2:9: nested object expected: LBRACE got: ASSIGN
```

However, I agree that it is not very visible when displayed along with the full usage output, and even if you do see it the error message is not very helpful.

Terraform 0.12 has a different error message for this situation:

```
$ terraform apply

Error: Variables not allowed

  on foo.auto.tfvars line 1:
   1: invalid = baz

Variables may not be used here.
```

It now indicates the specific location of the problem. The error reports "variables may not be used here" because in Terraform 0.12 a bare identifier is used to refer to a variable.

Ideally this message would also advise that the user may wish to quote the value, since variables are never valid in `.tfvars` files anyway. However, this message is currently coming from the language parser and so such a specialized error message is not technically feasible. While improving this further would be ideal, I don't think we can prioritize that in the near because it would require quite a large change. I'm going to close this for now to represent that we're going to accept the 0.12 improvement, even though it isn't perfect. We may revisit this in future if we're doing other development in the area of processing `.tfvars` files, but for the foreseeable future our focus will be elsewhere.

Thanks for reporting this!
