### ISSUE TITLE
Unable to pass API_Gateway invoke_url as input variable to Lambda

### ISSUE THREAD

**Issue by harshildesai2** [hashicorp/terraform#20878]
### **Terraform version** : 
0.11.11

### **Issue**
I have an API Gateway with multiple methods, and lambda integrations to each of the methods.
One of my Lambda requires an API Method invoke url from the same API Gateway as an input.
I am unable to achieve this using Terraform.

### **Steps followed**
- Added the invoke url as output of the "api_gateway" module (Getting expected value on printing this output variable)
`/module/api_gateway/output.tf`
```
output "merge_api_url" {
  value = "${aws_api_gateway_deployment.myapi.invoke_url}"
}
```
- passed it as input variable in the main.tf present at root:
`/main.tf`
```module "lambda" {
  source = "lambda"
   merge-api-url = "${module.api_gateway.merge_api_url}"
}
```
### **Actual behavior:**
`Terraform plan` fails with following
```
Error: module "lambda": "merge-api-url" is not a valid argument
```
### **Expected Behaviour:**
The output variable from `/module/api_gateway` should get passed in the `/module/lambda` module, as similar approach is working fine when i pass the `/module/lambda` output variable to `/module/api_gateway`

Can you confirm if this is possible, if not, is there an alternative?

**Comment by apparentlymart** [comment]
Hi @harshildesai2,

Based on that error message, it sounds like the function in the `lambda` directory doesn't have a `variable "merge-api-url"` block to declare that input variable. (Note also that idiomatic style calls for variables names to use underscores rather than dashes, though that is just a cosmetic thing and would not be responsible for this error.)

**Comment by harshildesai2** [comment]
Hi @apparentlymart , thanks for ur response

I had added the `merge-api-url` in the `/module/lambda/variables.tf` file too as below, but still getting the same error:
```
variable "merge-api-url" {
  description = "dummy description text"
}
```

**Comment by apparentlymart** [comment]
The cycle message means that the dependencies you've created in your configuration are not resolvable because something depends (indirectly) on itself.

The error message refers to some items you didn't include in your configuration snippet earlier, so I don't know exactly what's going on there, but you should look at all of the resources listed in the error message and make sure that there is a valid order Terraform could evaluate those resources in that would ensure that the result of one resource is ready before applying another one that depends on it.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers. Since Terraform appears to be behaving correctly here, I'm going to close this out.
