### ISSUE TITLE
create multiple resources through list of objects in terraform 0.12-beta1

### ISSUE THREAD

**Issue by balan2010** [hashicorp/terraform#20893]
Hi there,

   I am trying to create same resource multiple times with below datastructure in terraform 0.12-beta1

```
groups = [
    {
        group_id = "gcp-org-admin"
        permissions = [ "roles/resourcemanager.organizationAdmin",
                        "roles/resourcemanager.folderViewer",
                        "roles/viewer",
                        "roles/iam.organizationRoleViewer",
                        "roles/orgpolicy.policyViewer"
                      ]  
    },
    {
        group_id = "gcp-security-ops"
        permissions = [ "roles/resourcemanager.folderViewer",
                        "roles/logging.viewer",
                        "roles/monitoring.editor",
                        "roles/iam.securityReviewer"
                      ]
    },
    {
        group_id = "gcp-network-ops"
        permissions = [ "roles/compute.networkViewer",
                        "roles/resourcemanager.folderViewer",
                        "roles/dns.reader",
                        "roles/browser"
                      ]  
    },
    {
      group_id = "gcp-cloud-operators"
      permissions = [ "roles/storage.objectViewer",
                      "roles/resourcemanager.folderViewers",
                      "roles/viewer",
                      "roles/logging.viewer",
                      "roles/monitoring.editor",
                      "roles/bigquery.dataViewer"
                    ]                       

    }
]
```

Pseudo code:

```
for group in var.groups:
   for permission in group.permissions:
        role = permission
        group = group.group_id
```

Is there anyway to achieve this ?

Resource I am trying to create is

```
resource "google_organization_iam_member" "role" {
   count = var.groups  ## not sure if I have to count on permissions rather than groups
  
   role = var.groups[count.index].permissions ## I am lost here
   member = var.groups[count.index].group_id
}

**Comment by apparentlymart** [comment]
Hi @balan2010,

I think the easiest way to get what you need here is to flatten down your data structure into just (group, permission) pairs. Something like this:

```hcl
locals {
  group_permissions = flatten([
    for group in var.groups: [
      for permission in group.permissions: {
        group_id = group.group_id
        permission = permission
      }
    ]
  ])
}

resource "google_organization_iam_member" "role" {
   count = length(local.group_permissions)
  
   role   = local.group_permissions[count.index].permission
   member = local.group_permissions[count.index].group_id
}
```

This works by transforming your data structure into a single list and working with that:

```hcl
[
  { group_id = "gcp-org-admin", permission = "roles/resourcemanager.organizationAdmin" },
  { group_id = "gcp-org-admin", permission = "roles/resourcemanager.folderViewer" },
  # ... etc ...
  { group_id = "gcp-security-ops", permission = "roles/resourcemanager.folderViewer" },
  # ... etc, etc ...
]
```

Note that because `count` uses the indexes in that list to identify the individual resource instances, adding new elements to these permission lists is likely to cause a very noisy plan diff as Terraform thinks it has to update all of the subsequent instances to deal with the renumbering. This may also cause problems during apply if the underlying API does not allow two different declarations of the same role/member pair to coexist at once.

The fuller solution to this will be #17179, which we are planning to introduce in a subsequent release after v0.12.0. That would allow you to tell Terraform to identify the individual instances by arbitrary strings of your choosing -- in this case, presumably a string containing both the group id and the permission name -- and thus model more accurately the relationships between individual resource instances and the entries within the `var.groups` data structure.

**Comment by balan2010** [comment]
Thanks a lot @apparentlymart. I was stuck in this part for a bit. Its all working now as expected.
