### ISSUE TITLE
How to build a custom Terraform provisioner

### ISSUE THREAD

**Issue by jenyss** [hashicorp/terraform#20896]
Hi, I am looking for a tutorial describing the steps to build a custom Terraform provisioner. 

I found a lot of resources specifying how to build a custom provider but am still looking for one for provisioner.

Can you please advise me where to start.

Thank you!

**Comment by apparentlymart** [comment]
Hi @jenyss,

At this time I would not recommend building third-party provisioners. Although in principle it is possible, there is no automatic-installation mechanism for provisioners and so usability of such a provisioner will not be as good as for the ones built in to the Terraform binary.

We intend to revisit the design of provisioners in a future release to find a better compromise than the current one. Exactly which direction we'll take will depend on future research, but some ideas on the table are to make provisioners be a feature of providers instead of standalone plugins (#2756) or, on the other hand, to rework the primitive provisioners `remote-exec` and `file` so that they are better building blocks for various use-cases and then to deprecate all of the higher-level ones.

The lack of documentation for third-party provisioners is reflective of the fact that we don't recommend building them. If you'd like to build one anyway, you can use [the `remote-exec` provisioner](https://github.com/hashicorp/terraform/blob/16778fea9219913d3621aba27a8c76507094f7d8/builtin/bins/provisioner-remote-exec/main.go) as a relatively simple reference point, with the caveat that the provisioner plugin mechanism is subject to change in future releases, so you may need to re-compile or tweak your provisioner as you upgrade Terraform.

**Comment by jenyss** [comment]
Hi @apparentlymart,

Thank you for the thorough reply! 
I was hoping to explore the option to create a single provisioner where the user can specify the location of a binary and provide some configuration parameters and then the provisioner would execute a script (that is included in the provisioner) which installs the binary on a created instance. 
Currently I am using the existing file and local-exec provisioners to achieve the above and while it is fairly easy to do it I wanted to save the hassle for the users of my app. 

Looking forward to see what the next steps for the provisioners would be.

**Comment by robfig** [comment]
Is this still accurate? This section of the documentation implies that custom provisioners are well supported:

https://www.terraform.io/docs/extend/plugin-types.html

"""
The official Terraform Provisioners are included in the Terraform Core codebase and are compiled into the terraform binary. While they are built in, Provisioners are still executed in a separate process over RPC, and benefit from the same discovery process as Terraform Providers, making custom Provisioners just as easy to create and use.
"""

**Comment by jenyss** [comment]
Hi @robfig,

I don't think anything has changed although I am looking forward to it.
In the documentation you reference above it is stated that: The official Terraform Provisioners are included in the Terraform Core codebase and are compiled into the terraform binary.

There is no way currently to contribute custom provisioners to Terraform and distribute it as part of Terraform.

**Comment by kmott** [comment]
Hi @apparentlymart, I am not sure if I should be posting on this ticket, or filing a new one, my apologies if I'm overloading this ticket.

I was looking through the Habitat Provisioner in the main terraform repo (to get it updated to support recent versions of Habitat + Terraform 0.12, and some other bug fixes).  However, I am finding it difficult to figure out how the provisioner is wired in to the rest of terraform (can't seem to find many docs)--I then found this GitHub ticket that makes it seem like 3rd party provisioners aren't really supported moving forward (or at the very least, will be significantly overhauled in the future).

So, I wasn't sure if I should continue on my path for updating the built-in Habitat provisioner, or if I should abandon that, and maybe write a custom module with several `null_resources` & `remote_exec's` to replace it.  What do you think?

Here's an example of the error I am getting from inside the `validateFn` in the provisioner:

```
Warning: Builder Url: 74D93920-ED26-11E3-AC10-0800200C9A66 (74D93920-ED26-11E3-AC10-0800200C9A66)

Warning: Builder Url: 74D93920-ED26-11E3-AC10-0800200C9A66 (74D93920-ED26-11E3-AC10-0800200C9A66)

Warning: Builder Url: https://foo.bar (https://foo.bar)
```

The first 2 "URLs" are UUIDs, which are from string interpolation of an input variable like this:

```
  provisioner "habitat" {
    [ ... ]
    url                = "${var.hab_bldr_url}"
    [ ... ]
  }
```

The third one verifies successfully, but only if I hard-code the string to a URL: "https://foo.bar"

I am not sure how I can get the post-interpolation string value inside my `validateFn`, which I can then use to validate my URL (or other items) against.
