### ISSUE TITLE
Provision client-facing s3 bucket (and mechanism) for transferring tenant file feeds.

### ISSUE THREAD

**Issue by srikanth205** [hashicorp/terraform#20905]
Can anyone help me out provisioning S3 bucket fir transferring tenant file feeds

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by srikanth205** [comment]
Done
