### ISSUE TITLE
Provider development: How to define a block (for a resource) in which the user can define a custom set of parameters.

### ISSUE THREAD

**Issue by jenyss** [hashicorp/terraform#20916]
I am writing a provider and I would like to have a block (in a resource) in which I can define a custom set of parameters by providing name and value for each of them. The user who is writing the block using the provider should be able to define his set of parameters. E.g.

resource "myresource" "env" {
  name        = "environment_name"
  description = "description"
  type        = "environment_type"

  properties {
    name1 = "value1"
    name2 = "value2"
    name3 = "value3"
    name4 = "value4"
  }
}
  
How can I define such a block in my provider?

**Comment by apparentlymart** [comment]
Hi @jenyss!

The idea of nested blocks is to establish a nested container with its own set of predefined keys that are validated in the same way as the top-level ones.

When the keys are to be defined by the end-user, what you need is a map value, using the map expression syntax:

```hcl
resource "myresource" "env" {
  name = "environment_name"
  description = "description"
  type = "environment_type"

  properties = {
    name1 = "value1"
    name2 = "value2"
    name3 = "value3"
    name4 = "value4"
  }
}
```

You can declare this by setting the `Type` of `properties` to `schema.TypeMap`. The reason for using a map expression rather than a nested block here is that it allows the user to potentially generate the property names dynamically using an arbitrary expression that returns a map result. For example, in Terraform v0.11:

```hcl
  properties = "${merge(var.global_properties, var.resource_properties)}"
```

The forthcoming Terraform 0.12 grows these capabilities even further by allowing users to construct maps dynamically using [`for` expressions](https://www.terraform.io/docs/configuration/expressions.html#for-expressions), to use arbitrary expressions in the keys, etc.

**Comment by jenyss** [comment]
Thanks for the reply @apparentlymart!
