### ISSUE TITLE
Nested maps in helper/schema

### ISSUE THREAD

**Issue by MalloZup** [hashicorp/terraform#20927]
Hi all

i was thinking if `nested maps` in Schema are possible. I couldn't find any documentation,  so one could describe it as following: ( this fail with error currently, but maybe we are doing it wrong? :thinking: )

```golang
              "pool_type": {     
                Type:     schema.TypeMap,
                Required: true,
                ForceNew: true,
                Elem: &schema.Resource{
                    map[string]*schema.Schema{
                        "dir": {
                            Type: schema.TypeMap,
                            Required: true,
                            Elem: &schema.Resource{
                                Schema: map[string]*schema.Schema{
                                    "path": { 
                                        Type: schema.TypeString,
                                        Required: true,
                                        ForceNew: true,
                                    },
                                },
                            },
                        },
                    },
                },
            },

```

Thx for your info/help!

**Comment by apparentlymart** [comment]
Hi @MalloZup,

As reflected in [the documentation](https://godoc.org/github.com/hashicorp/terraform/helper/schema#Schema), there are some constraints on `TypeMap`:

```go
    // Elem represents the element type. For a TypeMap, it must be a *Schema
    // with a Type that is one of the primitives: TypeString, TypeBool,
    // TypeInt, or TypeFloat. Otherwise it may be either a *Schema or a
    // *Resource. If it is *Schema, the element type is just a simple value.
    // If it is *Resource, the element type is a complex structure,
    // potentially with its own lifecycle.
```

There is currently no way to specify a "map-of-resource" structure, because the wire format used to communicate between Terraform Core and provider plugins cannot represent such a structure unambiguously.

For now, you must use a `TypeList` or `TypeSet` with your "key" as one of the attributes inside the nested block.

Terraform v0.12.0 is introducing the possibility of map-backed blocks in the wire protocol, but the SDK will not support it immediately because it's still implemented in terms of the 0.11 wire protocol. A subsequent version of the SDK is likely to introduce this capability, but I don't know when such a change might occur since the SDK update project is separate from the Terraform v0.12.0 project.

**Comment by apparentlymart** [comment]
This request is the same as in #6215, so I'm going to close this to consolidate the discussion over there. I see that I previously left some comments there giving some more detail on what I was alluding to in my previous comment here, in case you are interested.

**Comment by MalloZup** [comment]
thx @apparentlymart for your answer :+1:
