### ISSUE TITLE
Resolving overrides that introduce conflicting fields

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20938]
### Current Terraform Version

```
0.11.7
```

### Use-cases

We have a use case where a configuration file is auto-generated and users are modifying the values via override files.

In such cases, the user may wish to override the configuration with another attribute that conflicts with the original attribute.

Take this example. We have a resource `foo` which contains attributes `A` and `B`. `A` and `B` conflict with one another according to the resource schema and shouldn't be specified together.

Suppose the original configuration had:
```
resource foo foo1 {
  A = "abc"
}
```

And we wish to override this with:
```
resource foo foo1 {
  B = "def"
}
```

This currently results in a conflict error (which I assume is due to merging of "A" and "B").

### Proposal

Is there a mechanism to achieve the above? For example, could a user specify that the resource in the override file should take precedence over the entire resource in the original configuration?

**Comment by apparentlymart** [comment]
Hi @alexng-canuck,

As far as I know there isn't a way to resolve this in Terraform v0.11. In v0.12, it should be possible for the override file to explicitly null out the other argument:

```hcl
resource foo foo1 {
  A = null
  B = "def"
}
```

The meaning of `null` in 0.12 is to treat that argument as if it were not specified at all. It was introduced to allow for _conditional_ omission (like `cond ? "foo" : null`), but I think it should work for this override case too, due to how the override mechanism works.

**Comment by mildwonkey** [comment]
I can confirm that this (specifically, using `null` in an override file) works in terraform v0.12:

main.tf:
```hcl
resource "random_pet" "foo" {
    prefix = "abc"
    length = "2"
}
```

main_override.tf:
```hcl
resource "random_pet" "foo" {
    prefix = null
    length = "2"
}
```

```
$ terraform apply --auto-approve
random_pet.foo: Refreshing state... [id=cosmic-humpback]
```
