### ISSUE TITLE
v0.12: GetOkExists returning not found for nested TypeSet blocks that worked in v0.11

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20958]
### Terraform Version

```
pluginsdk-v0.12-early6 - v0.12.0-alpha4.0.20190401192225-916f900d1d56
```

### Terraform Configuration Files

```hcl
resource "oci_core_route_table" "tf-route-table1" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "${oci_core_virtual_network.tf-vcn1.id}"
  display_name   = "tf-route-table1"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_internet_gateway.tf-ig1.id}"
  }
}
```

### Debug Output

https://gist.github.com/alexng-canuck/05d4b95a51e7500853276fb111e836a1#file-debug-txt

### Expected Behavior

With v0.11 CLI, running `terraform apply` succeeds with above.

Internally, the provider is calling `GetOkExists` with a key like this: `route_rules.3233329590.destination`.

This looks for an element in a TypeSet and finds the `destination` attribute within one of those nested elements.

### Actual Behavior

With v0.12 CLI, the above fails because the `GetOkExists` call returns false. It cannot find the above key.

### Steps to Reproduce

`terraform apply`

**Comment by alexng-canuck** [comment]
Upon doing some further investigation, I suspect something changed with respect to how hashcode for TypeSet objects are stored in the diff level source. The hashcode that we used to call `GetOkExists` results in a match at diff-level when calling with v0.11.

In v0.12, there is no match at the diff-level because the hashcode used for the key has a different value.

**Comment by jbardin** [comment]
Hi @alexng-canuck,

Thanks for filing the issue. I want to ty and replicate this, since I want to make sure we are correctly generating the set hashes to avoid inadvertently re-inserting duplicate values into a set. The diff values are no longer the reference for changes in terraform and are not stored, and now only exists internally within the legacy SDK, and the set hashes are not stored at all, since the new typed attribute values use a very different set implementation.

For clarification, this isn't really an intended or supported use of the set type, since a "set" data structure is not meant to be internally addressable. That address is only accessible at all due to implementation details of the attribute storage, and a general rule of thumb is that set addresses should not appear in the provider source, though we make concessions for test fixtures. To handle sets, one would normally iterate over the list of values from the set, rather than attempting to address individual elements.

**Comment by alexng-canuck** [comment]
Aside from addressing individual elements for reading attributes, we had also taken a dependency on the `HasChange` method which can only work with individually addressed elements. Not sure if iterating over individual elements can get us the same information about whether attributes have changed.

**Comment by jbardin** [comment]
Hi @alexng-canuck,

Can you provide the config (or combination of configurations if it was an update) that triggered the issue for you?

Thanks!

**Comment by alexng-canuck** [comment]
Hi @jbardin,

I repro'ed this using the following config:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/networking/vcn_default/vcn.tf

A `terraform apply` should reproduce it. There was no previous state necessary.

**Comment by jbardin** [comment]
Thanks for the updates @alexng-canuck! I've managed to track this down to how the legacy sdk conflates "unknown" with "computed", which ended up inserting an `UnknownConfigValue` string in the `cidr_block` field. `ResourceData` will still compute the set correctly when asked, but the actual diff produced may have different indexes. 

While accessing the set elements like this may not be advised, we want to keep the data format as close as possible to what was seen in 0.11 to prevent other unintended consequences. This looks fixable, so I'll have a patch for this soon.

**Comment by alexng-canuck** [comment]
Thanks for the update @jbardin and I'm looking forward to the fix!

There are a couple of reasons that we individually address set elements like this:
1) Using `GetOkExists` tells us definitively whether an attribute within a set element has been set or not. We've noticed that retrieving this value by iterating over set elements will assign a zero-value to missing attributes; making it hard to distinguish whether the attribute was set to zero-value or whether it doesn't exist.

2) We also use the `ResourceData.HasChange` method to tell us whether an attribute within a set element has changed. This method requires set elements to be individually addressable.

If there are better alternatives to the above use-cases, it would be nice to know.

**Comment by jbardin** [comment]
@alexng-canuck,

Thanks for the clarification on your use case. This information is very useful as we start to plan out the future of the provider SDK.

I think a large part of this confusion is because the custom `SchemaSetFunc` function allows some abuse of the set type. In theory, if an attribute within a set element has changed, that element itself has changed (which will always be the case in the new type system). As has often happened, features to add a little flexibility have proven to be more flexible than anticipated.

For situation 1: that is an interesting (if unintended) solution, though it still won't be able to detect various combinations of zero-values vs unset during Update. (note the wording in the doc: "has been set to a non-zero value _at some point_", and the various caveats in `GetOkExists` which was only intended for `bool` values.)

As for 2: This comes back to trying to keep a set value the same while internal elements have changed. It's hard to say now, but I have a feeling this is sort of the opposite of the original `SchemaSetFunc` function intent, where it would allow the provider to modify a set value _without_ showing a change, i.e. for normalization or unavoidable modification of values by an API.

This is really all academic at this point, as the existing SDK is defined by it's behavior. Moving forward however we want to prevent this sort of unexpected flexibility, but still provide an API that covers providers use cases.

Is there any reason that your `route_rules` block couldn't be a list? It seems that would solve the issues of reliable addressing of the value. The only difference to the user would be the lack of automatic de-duplication of blocks, but for most cases the number of configuration blocks is small enough where it's not an issue.
