### ISSUE TITLE
[Question] Can i call another provider from my custom provider?

### ISSUE THREAD

**Issue by rahulwa** [hashicorp/terraform#20954]
I am planning to build a custom terraform provider, but for some tasks, it needs to call aws. Can I use/call here aws provider inside my provider.
I can't import just [terraform aws go package](https://godoc.org/github.com/terraform-providers/terraform-provider-aws/aws) as most of the stuff are unexported.
What is best to go here, should I write those function myself?

**Comment by apparentlymart** [comment]
Hi @rahulwa,

In general no, it is not possible for one provider to directly interact with another. Instead, you can design your provider to export attributes that can then be used to set the arguments of AWS provider resource types so that the connection between your provider and the AWS provider is defined by the user, rather than hard-coded into your provider.

Each provider plugin runs in a separate OS process, so even if you _could_ import the AWS provider code, you would essentially have your own copy of it inside your plugin without any ability to access the configured credentials, etc.

**Comment by dunnill** [comment]
Hi @apparentlymart ,

Just come across this question and wondered if you can expand on what you mean by "design your provider to export attributes".  I am looking, I suspect, at a similar use case as the OP.  In effect I want to create AWS resources but provide additional functionality than the AWS provider.  Currently some of this I have created via modules but I keep hitting limitations to this approach.  Often due to limitations on dynamic data or the DSL.

Thanks

**Comment by apparentlymart** [comment]
If either of you can share a specific example of what you want to do, I may be able to provide a more specific example. It's hard to answer this question properly with only a general use-case. Thanks!

**Comment by rahulwa** [comment]
I was thinking to create a provider that provided a bunch of alerting rules on top of aws, newrelic etc. for my company. Think of it as this will have standardization that each alert needs to follow like severity, who to do alerting, documentation on what to do after an alert, predifened set of alerts for application etc.
Sole idea was to have this as the provider is to define whatever we want and have the flexibility of a programming language, not constrained by terraform modules. And it would make our lives lot easier if we could have just called terraform implemented provider. 

But after your [reply](https://github.com/hashicorp/terraform/issues/20954#issuecomment-480893059), I saw that how complex this can be, so I dropped this idea and went ahead with terraform modules and just so know that I have dropped some standardization rule as manual as this can't be done with terraform modules. I understand that this requires a drastic change in terraform but calling terraform providers programmatically is like a dream come true, It opens a door for lot of things. 

For a specific example, let’s say that i want to add `todo_doc` parameter  on each alerts schema, it can be easily be done on [aws as it supports it](https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html#alarm_description) but [not on newrelic](https://www.terraform.io/docs/providers/newrelic/r/infra_alert_condition.html).

**Comment by dunnill** [comment]
@apparentlymart I started with modules but I want a degree of customisation that tends to barely (or not) work in modular fashion.  For example, we have a standard deployment web stack (i.e. LB -> ASG).  I can (and have) created a module for this that also enforces a desired tagging policy.  The part I tend to hit on is when AWS modules have different "options".  E.g. a listener can have a forward or a fixed default response.  Or when something just does not exist in AWS Tf ... e.g. getting an ASG's list of scheduled.  Sometimes I want one of my modules to be optional.   Not only that - the module I have created is much more complex and can make it harder for others to contribute to. 

I hope that all makes sense.  I'm hoping that the "design your provider to export attributes" may be the ray of sunshine needed.  As rahulwa states, adding additional constraints would be highly desirable.   This would make it easier for others (perhaps less Terraform pro) to use this custom module.  And therefore avoid any mess, mis-configation or other mishap.  

Hope that all makes sense.   It is somewhat tempting to just clone the AWS plugin ... but I'd rather not go that far.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence.

When I was talking about providers exporting attributes I meant implementing something like the "compute-only" data sources in some of the existing Terraform providers, like `template_file`, `aws_iam_policy_document`, etc. These data sources don't interact with any external system at all, but they do perform some computation that a Terraform module can't do on its own (or at least, could not in earlier versions of Terraform; 0.12 has rendered some of them somewhat redundant now), and the results they produce can then be passed in to resources on other providers.

For example, imagine if you had a `dunnil_tags` data source which takes in a bunch of arguments and then exports attributes like `aws_tags`, `gcp_tags`, etc that present the information given in the arguments in a way that conforms to your tagging policy.

```hcl
provider "dunnil" {
  # Anything value that will be global to the whole configuration
  # can be set just once in the provider settings.
  environment_name = "production"
  application_name = "exampleapp"
}

data "dunnil_tags" "example" {
  component_name = "network"
}

resource "aws_vpc" "example" {
  # ...

  tags = data.dunnil_tags.example.aws_tags
  # perhaps in this case, aws_tags would be:
  # {
  #   Name = "exampleapp production network"
  #   Environment = "production"
  #   Application = "exampleapp"
  #   Component = "network"
  # }
}
```

A different way to think about this is as something similar to a Terraform module that doesn't contain any resource definitions and instead just defines some `variable` and `output` blocks. Writing a provider containing a compute-only data source gives essentially the same result but allows you to implement the computation in Go rather than in the Terraform language.

I hope that helps explain what I was referring to before! This issue isn't really reflecting a specific work item for the Terraform codebase, so I'm going to close it out now. If you'd like to discuss these ideas more, please feel free to start a new topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
