### ISSUE TITLE
[conditional statement] loop is not working

### ISSUE THREAD

**Issue by sahotay** [hashicorp/terraform#20961]

**Comment by sahotay** [comment]
@apparentlymart Will you please help me with this request, Thank you so much!

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by mildwonkey** [comment]
Hi @sahotay!

I want to clarify some of your terminology and make sure I understand what you expect to see here:

Terraform 0.11 does not have any concept of loops. You can use `count` to create multiple instances of a resource, but it would only _run_ once. 

Your example `aws_lb_target_group` has two conflicting count statements:

```
  count = "${var.is_http_on ? 1 : 0}"
 [ ... ]

  count       = "${local.private_alb_ports["length"]}"
```

I'm surprised that even passes validation. You might want to try fixing that resource and seeing how that changes the behavior.

**Comment by sahotay** [comment]
I have resolved the problem, Not sure if i can delete this issue

**Comment by mildwonkey** [comment]
I can close it for you! Thanks for letting me know. 

It's up to you, but if you wanted to share the solution here it might be helpful for others!
