### ISSUE TITLE
Proper error message for HTTP 409 while provisioning Google Cloud SQL instance

### ISSUE THREAD

**Issue by gtirloni** [hashicorp/terraform#20972]
The issue is described in detail in #4557:

```
* google_sql_database_instance.default: Error, failed to create instance master-instance: googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState
```

This happens because instance names cannot be reused for up to a week after it's deleted.

The enhancement landed in #4577 but it's not showing properly which is leading to confused users.

Terraform 0.11.13

**Comment by apparentlymart** [comment]
Hi @gtirloni! Sorry for this unhelpful error message.

It looks like this message comes from inside the Google Cloud Platform provider code, rather than from the Terraform Core code. Back in 2016 when #4577 was merged, all of the providers were inside this codebase too, but they've since been split out into their own repositories.

I'm going to ask our bot to migrate this over to [the Google Cloud Platform provider repository](https://github.com/terraform-providers/terraform-provider-google) so that the provider team can see it and decide what to do about it.

Thanks for reporting this!
