### ISSUE TITLE
add support for open nebula provider

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform#20999]
Seems like OpenNebula is getting attention and wondering if Terraform can support it in the future.

https://opennebula.org
 http://docs.opennebula.org/5.8/integration/system_interfaces/go.html

**Comment by apparentlymart** [comment]
Hi @lmayorga1980! Thanks for this feature request.

The Terraform team at HashiCorp does not have the capacity to take on sole maintainership of any additional providers at this time, but a provider for OpenNebula could potentially be developed under our [Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html).

The most ideal case for that program is to partner with the vendor in question, so that we can ensure that the provider is true to the design goals of the product by working directly with its developers, but in some cases providers are also developed and maintained by motivated third-party developers.

**Comment by pkolyvas** [comment]
Closing this, as the Open Nebula Provider is a thing!

https://github.com/terraform-providers/terraform-provider-opennebula
