### ISSUE TITLE
Enforce the provider version within the module

### ISSUE THREAD

**Issue by chenrui333** [hashicorp/terraform#20996]
Recently, I have run into a issue that the module is using the latest available provider feature ([PR details](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/334)). 

I wonder if I can enforce the provider version within the module, something like:
```
module "vpc" {
  source             = "terraform-aws-modules/vpc/aws"
  version            = "1.60.0"
  provider          = "">= 2.0.0""
```

In other words, the peerDependency between the modules.

**Comment by mildwonkey** [comment]
Hi @chenrui333 !

I'm sorry, but I'm not quite following your question. Can you explain a bit more about what you are trying to achieve? Are you trying to override the provider version set in the module?  

If the provider version is set in the module itself, terraform will use that version. There can only be one version of any given provider, so you don't need to "repeat" the provider version. If you have a module that is not setting the provider version, you can always set the provider version at the top-level `.tf` file and terraform will use that version (there can only be one version of any given provider used, so that version would be used by any and all modules using that provider).

**Comment by chenrui333** [comment]
> If the provider version is set in the module itself, terraform will use that version.
@mildwonkey That sounds pretty cool, where can I see the example?

**Comment by mildwonkey** [comment]
Sure, here's a (made-up) example. If you have this `main.tf`:

```hcl
module "foo" {
   source = "./bar"
}
```

And this module in `./bar/main.tf`: 

```hcl
provider "random" {
    version = ">= 2.0.0"
}

resource "random_string" "example" {
     [ ... ]
}
```

Terraform will use the random provider >= v2.0. 


Alternatively, if the module does not have a provider version specified, you can get the same behavior by putting the provider version in `main.tf`:

```hcl
provider "random" {
    version = ">= 2.0.0"
}

module "foo" {
   source = "./bar"
}
```


Keep in mind that this would cause an error, because the provider versions specified cannot be reconciled:

`main.tf`:
```hcl
provider "random" {
    version = "1.0.0"
}

module "foo" {
   source = "./bar"
}
```

 `./bar/main.tf`: 

```hcl
provider "random" {
    version = ">= 2.0.0"
}

resource "random_string" "example" {
     [ ... ]
}
```

Does this help?

**Comment by chenrui333** [comment]
@mildwonkey yeah, that is certainly help, I have to play around to see how the error message looks like.

Also, I have found this issue, https://github.com/hashicorp/terraform/issues/16835, sounds like very much the same idea does get implemented in the tf 0.12 version. :)

**Comment by chenrui333** [comment]
Works pretty good for me, thanks @mildwonkey !

**Comment by chenrui333** [comment]
@mildwonkey. not sure if it is relevant, I do encounter a issue to pass the version as variable to the provider block within the module:

./bar/main.tf:
```
variable "region" {
  default = "us-west-2"
}

provider "aws" {
  version = ">= 2.0.0"
  region 	= "${var.region}"
}
```

When I do terraform plan, it complains about missing the provider region declaration.
