### ISSUE TITLE
No warning when backend config is not being used

### ISSUE THREAD

**Issue by henrytk** [hashicorp/terraform#21023]
I just spent an hour debugging why Terraform wanted to create resources that already exist. I eventually discovered it was because I omitted this by mistake:

```terraform
terraform {
  backend "s3" {}
}
```

### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

N/A

### Expected Behavior

The `terraform init` was called with backend configuration enabled, so I expect it to either fail - or at least very clearly warn me - when it does not end up using said configuration.

Also, why do I even need to add that source code snippet? Seems redundant if I have initialised a backend configuration on the command line.

### Actual Behavior

It silently fails to use the backend configuration.

**Comment by mildwonkey** [comment]
Hi @henrytk !

I am sorry that you experienced this issue, and I understand how frustrating it can be. 
By default, terraform uses the [local backend](https://www.terraform.io/docs/backends/), which requires no configuration. That's why there was no error. 

There is an info-level message if you run `TF_LOG=debug terraform init`, but of course you need to know what you are looking for and how to read this message:
```2019/04/16 12:19:14 [INFO] command: backend <nil> is not enhanced, wrapping in local```

I am going to label this as a feature request as it is reasonable for us to consider printing a friendly warning message in this case.

Thank you for reporting this to us, and I'm sorry again for the frustration.

**Comment by apparentlymart** [comment]
Hi @henrytk!

Could you please let us know what your `terraform init` command line looked like here? `terraform init` doesn't have a way to select a backend type, so if you run with no configuration at all it will select the `local` backend by default as @mildwonkey suggested. I'd like to understand better what command you were running here to see if there's a good way for us to detect your intent to use a remote backend to conditionally produce an error/warning, which could avoid emitting a confusing warning in the case where the user is _trying_ to use the default local backend configuration.

Thanks!

**Comment by henrytk** [comment]
Hi @mildwonkey and @apparentlymart 

Here was my command, partially redacted:

```bash
terraform init -input=false -backend=true -backend-config=bucket=<bucket-name-redacted> -backend-config=key=path/to/statefile -backend-config=region=eu-west-2 -var-file=path/to/var-file dir/
```

> terraform init doesn't have a way to select a backend type

True, but you can tell it to use backend config, so it is pretty confusing when it decides not to do that.

**Comment by apparentlymart** [comment]
Thanks for sharing that additional context, @henrytk!

In that case, I think probably the ideal thing to do here would be to fail altogether if `-backend-config` is used without a backend block.

We already have validation of the backend configuration arguments in the case where a backend is explicitly selected:

```
$ terraform init -backend-config=foo=bar

Initializing the backend...

Error: Invalid backend configuration argument

The backend configuration argument "foo" given on the command line is not
expected for the selected backend type.
```

...but that codepath doesn't currently run when a `backend` block isn't present, because in that case Terraform constructs a synthetic configuration and (as you've seen) apparently ignores the command line options altogether.

Using `-backend-config` on the command line is a good proxy for intent to use a non-default backend, so I think it's reasonable for that to produce an error if used when a `backend` block isn't present. If custom configuration for the `local` backend is needed, that can be declared by writing the backend block for _that_ explicitly, to record the intent of using custom settings:

```hcl
terraform {
  backend "local" {}
}
```

**Comment by henrytk** [comment]
Thanks @apparentlymart

An error sounds reasonable, and will no doubt save people from having to debug a confusing issue.
