### ISSUE TITLE
Error unexpected EOF occurs when filter, prefix, tags are missing in aws_s3_bucket_metric

### ISSUE THREAD

**Issue by papalagichen** [hashicorp/terraform#21029]
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v1.60.0
+ provider.null v2.1.1
+ provider.template v2.1.1
```

### Terraform Configuration Files

```hcl
resource aws_s3_bucket_metric bucket-metric-prefix-root {
  bucket = "${aws_s3_bucket.bucket.bucket}"
  name = "prefix-root"
}
```

### Expected Behavior

According to [s3_bucket_metric document](https://www.terraform.io/docs/providers/aws/r/s3_bucket_metric.html), `filter` argument is optional. `filter` should be ok to be absent. Further, `prefix` and `tags` configurations under `filter` argument are both optional. It should allow `filter` argument to be empty.

Since AWS S3 allows empty prefix / tags, it makes sense to support empty string in `prefix` and `tags` under `filter` argument.

### Actual Behavior

```
* aws_s3_bucket_metric.bucket-metric-prefix-root: 1 error(s) occurred:

* aws_s3_bucket_metric.bucket-metric-prefix-root: unexpected EOF 
```

### Steps to Reproduce

`terraform init`
`terraform plan`
`terraform apply`

### Additional Context

I have a workaround by putting `prefix = "/"` under `filter`, S3 metric filter will be created and becomes empty finally.

The Terraform command was executed directly from MacOS 10.14.4 with Bash shell 5.0.

**Comment by apparentlymart** [comment]
Hi @papalagichen! Sorry for this strange error.

This particular error message suggests that the AWS provider itself crashed while performing an operation. Normally we see some more details about the crash printed out in that case, but it seems like for some reason the provider exited prematurely without an error this time.

I'm going to ask our bot to move this over to the AWS provider repository since the maintainers of the provider will have a better chance of understanding what's going on here. If it turns out to be a bug in Terraform CLI that a proper error message didn't get printed out to the UI here then we can open a new issue to represent that, but I think the main thing here is to figure out why the AWS provider is exiting ungracefully.
