### ISSUE TITLE
Creating and tracking ECR repos is not working as expected

### ISSUE THREAD

**Issue by michaelgeorgeattard** [hashicorp/terraform#21022]
### Terraform Version

```
v0.11.13
```

### Terraform Configuration Files

```hcl
variable "repos" {
  description = "Repositories to create."
  default     = ["a", "b", "c"]
}

resource "aws_ecr_repository" "repos" {
  count = "${length(var.repos)}"
  name  = "${element(var.repos, count.index)}"
}
```

### Expected Behavior

Removing "b" from the repo list should attempt to destroy repo "b".

### Actual Behavior

Terraform attempts to destroy "b" and "c", and recreate "c" (due to new index).

**Comment by apparentlymart** [comment]
Hi @michaelgeorgeattard,

With the design of `count`, this is the correct behavior, but indeed it means that `count` is not a good solution for creating an object for each element in a collection. The feature we intend to use to solve this is discussed in #17179, and we intend to include it in a v0.12.x point release, at which point you'll be able to write what you wrote here in a different way:

```hcl
variable "repos" {
  description = "Repositories to create."
  default     = ["a", "b", "c"]
}

resource "aws_ecr_repository" "repos" {
  for_each = { for x in var.repos : x => x }

  name  = each.value
}
```

The trick with `for_each` is that Terraform will identify the resources by the key in the map produced by the `for_each` expression, rather than by index. That means you'll have instances named `aws_ecr_repository.repos["a"]`, `aws_ecr_repository.repos["b"]`, `aws_ecr_repository.repos["c"]` rather than `aws_ecr_repository.repos[0]`, `aws_ecr_repository.repos[1]`, `aws_ecr_repository.repos[2]`, and so Terraform will be able to detect when `b` is no longer present and understand which of the instances that maps to.

Because we already have #17179 representing this work, I'm going to close this out. Thanks for sharing the use-case!
