### ISSUE TITLE
terraform state show doesn't output an error when resource address is wrong

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform#21024]
### Terraform Version
**0.11.13**

### Expected Behavior
`terraform state show <resourceAddress>` should output a message when the targetted resource doesn't exist in the state file.

### Actual Behavior
There is no output at all.

**Comment by apparentlymart** [comment]
Hi @dimisjim,

In Terraform v0.11 and prior, `state show` is implemented as a filter over all of the objects in the state, and so the lack of output is a result of the filter not matching anything. This was a result of using the same filtering code as used by some other commands that can potentially work on multiple resources at once, such as `terraform state rm`.

However, in the `master` branch for the forthcoming v0.12.0 release this command has been rewritten to try to exact-match a single resource instance from the state and produce an error message if not. Because that fix is already in place and ready for release, I'm going to close this out.

Thanks for reporting this!
