### ISSUE TITLE
terraform state commands do not work in jenkins pipeline

### ISSUE THREAD

**Issue by ronaldegmar** [hashicorp/terraform#21028]
Hi,

I got the following message every time I tried to run "terraform state list" inside a jenkins scripted pipeline.
************************************************************************88
+ terraform state list aws_instance.experiment-ec2

No state file was found!

State management commands require a state file. Run this command

in a directory where Terraform has been run or use the -state flag

to point the command to a specific state location.

Terminated

script returned exit code 1
***********************************************************************************
I'm able to run "terraform plan" and "terraform apply" without any problems.
I notice "terraform state list" works when running it like this "terraform init && terraform state list"
However, it shouldn't be needed to initialize the backend again because it's already initialized.
My terraform version is: 
Terraform v0.11.3
+ provider.aws v1.9.0
+ provider.null v1.0.0
+ provider.vault v1.7.0

**Comment by apparentlymart** [comment]
Hi @ronaldegmar,

The fact that running `terraform init && terraform state list` works suggests that somehow the working directory is becoming _uninitialized_ before running this command. Without knowing more about how you've got this set up I can't say why that would be, but hopefully the following additional context will help with debugging:

The backend initialization step in `terraform init` creates the file `.terraform/terraform.tfstate`. It has that name for historical compatibility reasons, but it isn't actually a state file itself but rather just stores the backend configuration so that other Terraform commands can use it.

If that `.terraform/terraform.tfstate` file is missing or if it disagrees with the backend configuration in the configuration then most commands will generate an error message telling you to run `terraform init`. Based on what you shared here, it looks like there's a bug in `terraform state list` which is causing it to return a more generic error message instead, probably because it has special behavior of being able to accept a state filename on the command line instead of retrieving it from the backend.

To continue debugging, my next step if I you would be to include `cat .terraform/terraform.tfstate` as part of the Jenkins step to write it out into the log and make sure it contains the expected configuration.

**Comment by apparentlymart** [comment]
Hi again, @ronaldegmar!

Since I didn't hear back from you, I'm going to close this in the hope that my previous comment helped you find a working solution.

If you have any follow-up questions, [the community forum](https://discuss.hashicorp.com/c/terraform-core) is a great place to ask them, since there are more people ready to help. The GitHub issues here are generally monitored only by our few core maintainers. Thanks!
