### ISSUE TITLE
Azurerm backend authentication with Azure CLI is not working when running Terraform init

### ISSUE THREAD

**Issue by raykao** [hashicorp/terraform#21032]
**Terraform Version:**
0.11.13

**Terraform Template:**
```terraform
terraform {
    required_version = ">= 0.11.13"
    backend "azurerm" {
        resource_group_name = "<rg_name>"
        storage_account_name = "<account_name>"
        container_name       = "<container_name>"
        key                  = "test.terraform.tfstate"
    }
}
```

**Azure CLI Version:**
2.0.62

**Command**
```terraform init```

**Error Message:**
```shell
Error configuring the backend "azurerm": resource_group_name and credentials must be provided when access_key is absent

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

**Expected Behavior**
Terraform init is successful and can use my Azure Credentials after running az login to setup Azure as the Backend store for state

**Actual Behavior**
terraform init errors with the above message and does not connect to backend or initialize TF

**Comment by tombuildsstuff** [comment]
hi @raykao 

Thanks for opening this issue.

Using the Azure CLI to authenticate with the Azure Backend is only supported in Terraform 0.12 and above, which is why you're seeing this error; in Terraform 0.11 you instead must specify either the Access Key for the Storage Account, or a Service Principal. Unfortunately due to the Terraform website not supporting multiple versions of the documentation at once this functionality went live before we planned it to - which makes this a little unclear.

At this time I'd recommend using a Service Principal with the Azure Backend - once Terraform 0.12 is released you should be able to switch over to using the Azure CLI to authenticate instead - would you be able to see if that works for you?

Thanks!

**Comment by raykao** [comment]
@tombuildsstuff - Verified that the Service Principal works! Thanks for clarifying that it's a 0.12 feature.

**Comment by cloudpea** [comment]
I am also having the same issue i want to authenticate to the backend via azure cli i am running version 0.11.13.

```
cloudpea$ terraform version
Terraform v0.11.13
+ provider.azurerm v1.24.0
+ provider.null v2.1.0
+ provider.random v2.1.2
+ provider.template v2.1.2

cloudpea$ terraform init
Initializing modules...
- module.network
- module.storage
- module.keyvault
- module.automation
- module.oms
- module.recoveryservices
- module.policy
- module.auth

Initializing the backend...

Error configuring the backend "azurerm": resource_group_name and credentials must be provided when access_key is absent

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

See Backend Configuration below:
```
# Remote State Backend
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-dwp-test-ts-tst-core"
    storage_account_name = "strdwptesttststtfstate"
    container_name       = "tfstate"
    key                  = "pdu.terraform.tfstate"
  }
}
```
