### ISSUE TITLE
The template provider parses every variable, even those that are undeclared.

### ISSUE THREAD

**Issue by 7heo** [hashicorp/terraform#2104]
The syntax of the template variables is `${variable}`. With such a simple syntax, it is very likely to collide with existing syntaxes (shell script is one of those). For this reason, it should verbosely ignore undeclared and syntactically incorrect template variables, rather than crash.

How to reproduce:

1. Write a terraform template that contains an invalid/undeclared variable.
2. Write a terraform file that uses that template.
3. Execute terraform.

**Comment by dupuy** [comment]
My experience with this was that I had a bunch of comments in the template for a cloud-config file that included the Terraform code for using the template; these caused parse failures because the template provider didn't know anything about `${var.something}`.  Once I understood the problem, I just stuck a space between `$` and `{` so the template provider wouldn't be confused, but this is an easy trap to fall into, and the error messages didn't make it immediately clear what the problem was.  Having an alternate syntax for template variables might be best, but even just ignoring template variables with `.` in them would have eliminated the problem that I had.

**Comment by 7heo** [comment]
@dupuy actually, it is possible to get it to work by prefixing the shell variables with `$`, like so: `$${shell_variable}`. It will be rendered as `${shell_variable}` in the rendered template. However, I think that it would be better to only parse the variables that are declared, and allow the other ones to exist while not crashing terraform. That way, the ONLY moment where `$${variable}` would still be necessary is for when there are a shell variable AND a terraform variable of the same name.

**Comment by mitchellh** [comment]
Thanks for the feedback. I think template parsing should be strict, and you should escape all conflicting syntax. We'll introduce other template formats in the future, and perhaps some of those will be more lax. But for our template syntax, the way it works now is the way we want it to, with `$$` for escaping.
