### ISSUE TITLE
Configuration language function to reverse a string

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform#21075]
We'd like to be able to reverse a string value.

### Proposal

Name the new function `strrev` as `reverse` is already [taken](https://www.terraform.io/docs/configuration/functions/reverse.html).

```console
$ terraform console
> strrev("hello")
olleh
```

**Comment by mildwonkey** [comment]
Hi @ewbankkit !

Terraform 0.12 - currently in beta - includes the [`strrev`](https://github.com/hashicorp/terraform/blob/7d58643f272a8d4f792da49320f261f7a8273286/lang/functions.go#L102) function from go-cty. 

Since this feature is available in the master branch, and we do not plan on any more 0.11 enhancements, I will close this issue. Thank you.

**Comment by mildwonkey** [comment]
Whoops - the function exists, but not the documentation. We'll get that fixed before the general release!

**Comment by apparentlymart** [comment]
When we document this, it'd be good to be explicit that it reverses in terms of unicode characters rather than bytes, similar to what we say for [`substr`](https://www.terraform.io/docs/configuration/functions/substr.html). We could include a similar example where the string includes an emoji character along with latin letters to illustrate that the emoji is preserved even though it's made up of multiple bytes and of multiple unicode codepoints.

**Comment by ewbankkit** [comment]
@apparentlymart / @mildwonkey Our use case is to obfuscate (not cryptographically) an object ID and ensure that the operation is two-way.

**Comment by edwardluke-iw** [comment]
I have a use case for a domain name I would like to reverse

**Comment by mildwonkey** [comment]
Thanks @edwardluke-iw! This function is currently available in terraform 0.12.0 (released _yesterday_ 🎉).
