### ISSUE TITLE
Terraform init not reading provider aws variable

### ISSUE THREAD

**Issue by igoratencompass** [hashicorp/terraform#21083]
### Terraform Version

```
$ terraform -v
Terraform v0.11.13
+ provider.aws v1.60.0
+ provider.null v2.1.0
+ provider.template v2.1.0
```

### Terraform Configuration Files

```
# provider.tfvars
provider = {
  access_key = "xxx"
  secret_key = "xxx"
  region     = "eu-west-2"
  version    = "~> 1.60"
}

# vars.tf
provider "aws" {
    access_key = "${var.provider["access_key"]}"
    secret_key = "${var.provider["secret_key"]}"
    region     = "${var.provider["region"]}"
    # Not working with special characters, see https://github.com/hashicorp/terraform/issues/16745
    #version    = "${var.provider["version"]}"
    # have to hardcode it
    version    = "~> 1.60"
}

# terraform-state.tf
terraform {
    backend "s3" {
      encrypt        = true
      bucket         = "my-bucket"
      dynamodb_table = "my-lock"
      region         = "my-region"
      key            = "my-key"
    }
}
```

### Expected Behavior
I expect terraform to read the content of `provider aws` and use the credentials provided.

### Actual Behavior
The expected does not happen and I get:
```
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: AccessDenied: Access Denied
	status code: 403
```
when I run `terraform init`. I don't see an option for this command to pass environment file, why is this not supported?

### Additional Context
I don't have the `~/.aws/credentials` file setup but why would I need one when I set the provider credentials via variable? The credentials are valid and all is working fine once they are put into `~/.aws/credentials` file.

### References
Seems this issue is asking the same question: https://github.com/hashicorp/terraform/issues/13857

**Comment by apparentlymart** [comment]
Hi @igoratencompass!

The S3 backend is a separate component, not part of the AWS provider. Therefore it requires [its own configuration](https://www.terraform.io/docs/backends/types/s3.html), separate from the AWS provider.

The usual way to use the S3 backend and AWS provider together in Terraform is to not specify any credentials in Terraform at all and instead have Terraform read the credentials from either the usual environment variables or from `~/.aws/credentials`. That then allows you to apply the Terraform configuration in any situation where AWS credentials are available -- including an EC2 instance with a suitably-privileged instance profile -- without making any changes to the configuration.

We support explicit configuration of credentials for pragmatic reasons to allow for unusual situations, but you should consider them a last resort and prefer to use "ambient" credentials from the environment instead unless there is a strong (and unusual) reason to set them using input variables.

Note that backend configuration _cannot_ be configured via input variables, so if you wish to use explicit credentials directly in the Terraform configuration you will need to hard-code them into a backend configuration file and pass it to `terraform init -backend-config=...` . But if you use ambient credentials instead you can avoid that requirement.

**Comment by igoratencompass** [comment]
@apparentlymart thanks for the the time you put into this detailed explanation, much appreciated.

**Comment by igoratencompass** [comment]
@apparentlymart just an additional question I just thought of ... in case when running on a EC2 instance that has IAM instance profile set plus `~/.aws/credentials` file, which credentials will be used for the API calls?

**Comment by apparentlymart** [comment]
Hi @igoratencompass!

From taking a quick look at [the relevant code](https://github.com/hashicorp/terraform/pull/21035/commits/a8dabd2b21761fb8bce9793aa3d36c4e51f79426) (this is a library we share with the AWS provider for this common configuration functionality) it looks like the order of preference is:

* Credentials in the configuration
* Environment variables
* Credentials file (either `~/.aws/credentials` by default or whatever explicit file is configured)
* ECS remote credentials, if `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set
* IAM instance profile, if the EC2 metadata service appears to be reachable

The earlier ones in that list override the later ones, so in the situation you described the credentials file would take precedence over the IAM instance profile.

That seems to be confirmed by [the AWS provider documentation](https://www.terraform.io/docs/providers/aws/index.html#authentication), which makes sense because the AWS provider and the S3 backend both call into the code I linked above to obtain credentials.

**Comment by igoratencompass** [comment]
Thanks again @apparentlymart , I was able to confirm this running `TF_LOG=trace terraform init` with and without `~/.aws/credentials` file and all worked as described: when the file was not present the EC2 instance credentials were used otherwise the credentials from the static file took priority.
