### ISSUE TITLE
Support for authentication with client certs for HTTP backend

### ISSUE THREAD

**Issue by AshleyDumaine** [hashicorp/terraform#21087]
Currently the only authentication method for the http backend is a username and password (https://www.terraform.io/docs/backends/types/http.html)

It would be useful to also support authentication using client certificates:
```
terraform {
  backend "http" {
    address = "http://myrest.api.com/foo"
    lock_address = "http://myrest.api.com/foo"
    unlock_address = "http://myrest.api.com/foo"
    cert_file = "/path/to/my/client.crt"
    key_file = "/path/to/my/client.key"
    ca_file = "/path/to/my/ca.pem"
  }
}
```

**Comment by apparentlymart** [comment]
Hello!

It seems like this was previously implemented in https://github.com/hashicorp/terraform/pull/31699, which was associated with the duplicate issue https://github.com/hashicorp/terraform/issues/31700 so we missed closing this one when that was merged.

The feature has been available since Terraform v1.4, so I'm going to belatedly close this issue. Thanks for the suggestion, and sorry that we lost track of this issue!
