### ISSUE TITLE
Provisioner local-exec should kill the terraform process and exit with code 1

### ISSUE THREAD

**Issue by hendrixroa** [hashicorp/terraform#21088]
### Terraform Version

```
0.11.13
```

### Terraform Configuration Files

```hcl
resource "null_resource" "should_kill_all_process" {
  triggers {
    "update_at" = "${uuid()}"
  }

  provisioner "local-exec" {
    command     = "echo $foo && exit 1"
    on_failure  = "fail"

    environment = {
      foo = "bar"
    }
  }
}
...
```

### Expected Behavior

Should stop or kill the current terraform process and exit with code 1.

### Actual Behavior
Show the logs and terraform continue provisioning other resources

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
- #20671

**Comment by jbardin** [comment]
Hi @hendrixroa,

Can you explain a little what problem you're attempting to solve?
Unfortunately this approach can't work, because plugins are all run in an entirely separate process. Even if the command were executed by the cli process however, it's a shell command and the shell is what will exit, not the parent process.

**Comment by hendrixroa** [comment]
@jbardin  I'm trying to import a swagger file to API gateway, so for this, I'm using the [aws sdk js](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#importRestApi-property) with a custom script `.js` to import my API spec, sometimes the swagger file has some issues what can be rejected passing the param `failOnWarnings: true | false`, then I catch up the error and return the process with `process.exit(1);`, later on, I need to stop the parent process (Terraform process) because that error is considered fatal and the process can not continue. 

My question is I added the attribute `on_failure = "fail"` terraform should kill itself or I need to do that outside of terraform process?

**Comment by jbardin** [comment]
`on_failure = "fail"` is the default behavior, and the resource will be left in a "tainted" state. This also produces an error, which will prevent dependent resources from being applied. This will not halt other operations already in progress, since they must be independent of the resource being provisioned. 

Terraform does its best to prevent the main process from being inadvertently terminated, because doing so is likely to lose the state for some or all of the resources which may have already been provisioned.

**Comment by hendrixroa** [comment]
@jbardin  Make sense, thanks for you quickly response
