### ISSUE TITLE
formatdate(spec, timestamp) "unknown function called: formatdate

### ISSUE THREAD

**Issue by mfergus1** [hashicorp/terraform#21101]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
module "my_api" {
  source         = "./modules/api"
  region         = "${var.region}"
  stage_name     = "${local.environment}-${formatdate("DD-MMM-HH-m", timestamp())}"
  resource_paths = ["my", "resource"]
}
```

**Comment by apparentlymart** [comment]
Hi @mfergus1!

Since you didn't fill out the issue template I can't tell which version of Terraform you are using, but I'm guessing that you are using Terraform v0.11 where this function is not yet available. This feature is currently available only in v0.12.0-beta1 and v0.12.0-beta2; it'll be included in the forthcoming v0.12.0 final release too.

For the list of functions available in Terraform v0.11, please refer to [the v0.11 _Built-in Functions_ documentation](https://www.terraform.io/docs/configuration-0-11/interpolation.html#built-in-functions).
