### ISSUE TITLE
Can't import 'github.com/hashicorp/terraform/plans/planfile'

### ISSUE THREAD

**Issue by bitfield** [hashicorp/terraform#21121]
Minimal program to reproduce:

1. Create a temporary module:

```
go mod init tmp
```

2. Create the following `main.go`:

```go
package main

import "github.com/hashicorp/terraform/plans/planfile"

func main() {
	_, _ := planfile.Open("test.plan")
}
```

3. Build:

```
go build

go: finding github.com/hashicorp/terraform/plans/planfile latest
go: finding github.com/hashicorp/terraform/plans latest
build tmp: cannot load github.com/hashicorp/terraform/plans/planfile: cannot find module providing package github.com/hashicorp/terraform/plans/planfile
```

More information:

```
go build -v

go: finding github.com/hashicorp/terraform/plans/planfile latest
go: finding github.com/hashicorp/terraform/plans latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
build tmp: cannot load github.com/hashicorp/terraform/plans/planfile: cannot find module providing package github.com/hashicorp/terraform/plans/planfile

go get -v github.com/hashicorp/terraform/plans

go: finding github.com/hashicorp/terraform/plans latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go get github.com/hashicorp/terraform/plans: no matching versions for query "latest"
```

**Comment by jbardin** [comment]
Hi @bitfield,

The `github.com/hashicorp/terraform/plans/planfile` module doesn't exist in the latest stable release of terraform. If you want to fetch the module from master, first use the command:

    go get github.com/hashicorp/terraform/plans/planfile@master

This will fetch the terraform module and it's dependencies from the master branch, and add the necessary entries to your `go.mod` file.

**Comment by bitfield** [comment]
Oh, well that would explain it :) 

Can you give me an idea when this will be in stable? It's for the Terratest library, so I can't very well ask them to use the tip version.

**Comment by apparentlymart** [comment]
Hi @bitfield,

None of Terraform's Go packages are considered public API, so any application depending on them is likely to run into troubles like this. While we're pragmatic and don't actively prevent such imports via technology, we also can't support them: we will change the Terraform Go package APIs at any time in order to improve the product, whose only supported interface is as a CLI program.

With that said, we've added in the master branch (ready for forthcoming v0.12.0 release) a new command [`terraform show -json PLANFILE`](https://www.terraform.io/docs/commands/show.html#json-output) which _is_ a publicly-consumable interface for reading plans. That is the interface I would suggest using for external tools like Terratest, since this is much less likely to need to change in breaking ways in future releases, and will eventually (once it's been proven in real-world use) have compatibility guarantees around it.

**Comment by bitfield** [comment]
Yes, that makes sense, thank you. In a sense Terratest is the 'public API' version of Terraform, in that it exposes a stable Go interface for programmatically managing Terraform operations (for example in automated tests). So I'd like it to be as robust as possible, and if the contract is with the CLI, that's evidently the way to go.

Maybe the right thing is to try the `show -json` command first; if that doesn't work, assume Terraform pre-0.12, and read the plan with `terraform.ReadPlan()`. Does that sound reasonable?

**Comment by apparentlymart** [comment]
Sorry for the slow response @bitfield, but indeed... what you suggested there sounds like a reasonable way to support both Terraform 0.12 and older versions at the same time.

Another option to consider is to make a fork of my earlier experiment [go-tfplan](https://github.com/apparentlymart/go-tfplan), which is essentially the same struct types Terraform 0.11 and earlier used to represent the plan file structure (using `encoding/gob`) but extracted out into a separate package. I have no plans to continue to maintain that codebase as-is because the format it relates to is now defunct (I made it long before we started working on the Terraform 0.12 plan format), so I would not suggest depending on those packages directly, but you could potentially use that work as a basis for a terratest-specific package to parse the Terraform 0.11 plan format in a self-contained way, without an external dependency on Terraform CLI's packages. (The `v2` subdirectory is the one that applies to Terraform 0.10 and 0.11.)

Since this issue doesn't relate to a specific work item for the Terraform codebase, I'm going to close it now. Hopefully the above discussion was helpful!
