### ISSUE TITLE
Error loading state: etcdserver: mvcc: database space exceeded

### ISSUE THREAD

**Issue by innocencex** [hashicorp/terraform#21138]
I used Etcd as b backend, when I run terrafom init, it show the error message, I checked my etcd size, its about 2.5M, and I can put or get data from it. So I don't know how to solve it

**Comment by mildwonkey** [comment]
Hi @innocencex ! I am sorry you've come across this issue. Can you please edit this issue to include all of the information that was requested in the [bug report template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? If it's easier, you can close this, open a new github issue, and fill out the provided template.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
