### ISSUE TITLE
`init -reconfigure` required after upgrading to 0.12 with remote backend

### ISSUE THREAD

**Issue by mildwonkey** [hashicorp/terraform#21189]
After upgrading my (0.11.13) configuration using 0.12upgrade, `terraform` reported an error with a message that I needed to run `init` again. `init` then errored out with a message that `init -reconfigure` was required. 
This could be a more precise message - it would have been nice to know from the start why `init` was required (and it is notable that this step was not required with the local backend, including one using remote state), and also that `init -reconfigure` was required.
Failing that, we should make a note in the upgrade guide.

```
$ terraform version
Terraform v0.12.0-beta2
+ provider.random v2.1.2
```

configuration:
```hcl
terraform {
  backend "remote" { [redacted] }
}

resource "random_pet" "my_pets" {
  count = 2
}
```

Output after running 0.12upgrade (which made no changes to the configuration above):

```
$ terraform plan
Backend reinitialization required. Please run "terraform init".
Reason: Backend configuration changed for "remote"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.


Error: Initialization required. Please see the error message above.

$ terraform init

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



Error: Failed to decode current backend config

The backend configuration created by the most recent run of "terraform init"
could not be decoded: missing expected {. The configuration may have been
initialized by an earlier version that used an incompatible configuration
structure. Run "terraform init -reconfigure" to force re-initialization of the
backend.

```

**Comment by apparentlymart** [comment]
I think if nothing else we could improve the terminology in that final error message: it's using "backend config" to refer to the final resolved config we cache in `.terraform/terraform.tfstate`, but the usual meaning of "configuration" is stuff inside `.tf` files, so the message is pretty misleading about where the syntax error it's reporting actually lies.

Perhaps we could say "initialized backend settings" instead, which hopefully makes it clearer that we're talking about something that `terraform init` does rather than something the user wrote. "Settings" and "configuration" are not really meaningfully different words in this context, but I think it at least avoids using the exact same words we use in the documentation to refer to the contents of the `backend "..."` block.

Ideally we'd also detect that parse error inside `terraform plan` here and report something like that error immediately, in which case I'd like to use this alternative terminology in that other error message to, as well as being clear that running `terraform init -reconfigure` is only appropriate if the only thing that's changed since the last `terraform init` is upgrading Terraform.

**Comment by apparentlymart** [comment]
We'll run with the upgrade guide text already added for now, and see if further work is warranted via separate issues.

**Comment by jbardin** [comment]
There's 2 different, related bugs that will cause this behavior.

The first issue, and what most users will see, is that the new config `cty.Value` will contain `Null` values from config, while the `cty.Value` loaded from the stored "state" will have empty zero values. Since these don't compare as equal,  it will trigger `init` to prompt for migration.

The second issue, is that the hash stored for the backend config contains the cli `-backend-config` options. Since these extra options aren't available in the config during a subsequent plain ` terraform init`, the hashes won't match and it triggers a migration prompt.
