### ISSUE TITLE
Complaining that file doesn't exist before it's even created

### ISSUE THREAD

**Issue by cawilliamson** [hashicorp/terraform#21187]
### Terraform Version

`0.11.13`

### Terraform Configuration Files

```
# main.tf

  source                 = "./modules/ssh"

  cluster_name                = "${var.cluster_name}"
  config_output_path     = "${var.config_output_path}"

  ssh_private_key_path   = "${var.ssh_private_key_path}"
  ssh_public_key_path    = "${var.ssh_public_key_path}"
}

# modules/ssh/main.tf:

resource "tls_private_key" "ssh_key" {
  algorithm        = "RSA"
  rsa_bits         = 4096

  count            = "${var.ssh_private_key_path == "" ? 1 : 0}"
}

resource "local_file" "ssh_private" {
    count             = "${var.ssh_private_key_path == "" ? 1 : 0}"

    content           = "${tls_private_key.ssh_key.*.private_key_pem}"
    filename          = "${var.config_output_path}/ssh_private_${var.cluster_name}"

    count             = "${var.ssh_private_key_path == "" ? 1 : 0}"
    depends_on        = [ "tls_private_key.ssh_key" ]
}

resource "local_file" "ssh_public" {
    content     = "${tls_private_key.ssh_key.*.public_key_openssh}"
    filename    = "${var.config_output_path}/ssh_public_${var.cluster_name}"

    count       = "${(var.ssh_private_key_path == "")  ? 1 : 0}"
    depends_on  = [ "tls_private_key.ssh_key" ]
}

# modules/ssh/outputs.tf:

output "ssh_private_key_path" {
  value = "${var.ssh_private_key_path == "" ? local_file.ssh_private.0.filename : var.ssh_private_key_path}"
}

output "ssh_public_key_path" {
  value = "${var.ssh_public_key_path == "" ? local_file.ssh_public.0.filename : var.ssh_public_key_path}"
}

```

### Crash Output
N/A

### Expected Behavior
I expect when I pass in the output from `${module.ssh.private_key_path}` to a var on another module and reference `"${file(var.ssh_private_key_path)}"` I will be given the file contents of that file.

### Actual Behavior
When I try to run `terraform plan` I am told:

```
: file: open .terraform/tmp/ssh_public_apollo: no such file or directory in:

${file(var.ssh_public_key_path)}
```

### Steps to Reproduce
```
1. terraform plan
2. ???
3. Don't profit. :(
```

### Additional Context
Nothing odd about the setup other than that it's not working! 👎 

### References
N/A

**Comment by apparentlymart** [comment]
Hi @cawilliamson!

Unfortunately this behavior is expected, because functions do not participate in the dependency graph: functions are called while Terraform is planning, not during apply. Files read during `file` should be considered as part of the configuration (checked in to version control along with the `.tf` file referring to it), not part of the result.

We've tried to clarify this situation better in [the new `file` function documentation for the forthcoming v0.12 release](https://www.terraform.io/docs/configuration/functions/file.html). Although that documentation section is for v0.12, this particular aspect applies to `v0.11` in the same way, and the suggested solution still applies: you can use [the `local_file` data source](https://www.terraform.io/docs/providers/local/d/file.html) to read the file, which tells Terraform that this is something dynamic that it should process as if it's a remote object, taking the dependency graph into account.

In your case though, since the same configuration is both generating the file and then reading the file back in, the more idiomatic approach would be to not read in the on-disk file at all, and instead just access either `tls_private_key.ssh_key.*.public_key_openssh[count.index]` or `local_file.ssh_public.*.content[count.index]` directly to get the value that's already in memory.

(Note also that you're currently assigning the full result of a splat expression to `content` in both of those `local_file` blocks. Terraform isn't currently reporting that error because the `file` function is failing before validation gets that far, but `content` expects a single string rather than a list so you'll need to add `[count.index]` to the end of those to select the appropriate single value from the list.)

**Comment by apparentlymart** [comment]
Hi again @cawilliamson!

Since we didn't hear from you again, I'm going to close this in the hope that my previous comment helped you find a working solution.

If you have followup questions, [the community forum](https://discuss.hashicorp.com/c/terraform-core) is a good place to ask since there are more people there ready to help than here in GitHub, which is only monitored by our few Terraform core team members. Thanks!
