### ISSUE TITLE
terraform_remote_state map default

### ISSUE THREAD

**Issue by pgmillon** [hashicorp/terraform#21188]
Hi,
How can I use a output of type map in a terraform_remote_state with a default ?

kms.tf
```
resource "aws_kms_key" "kms" {
  count = 2
  key_usage               = "ENCRYPT_DECRYPT"
  deletion_window_in_days = "${var.DELETION_WINDOW_IN_DAYS}"
  is_enabled              = true
  enable_key_rotation     = true
}
output "kms_ids" {
  value = "${map(
    "eu-west-1", "${aws_kms_key.kms.0.key_id}",
    "eu-west-2", "${aws_kms_key.kms.1.key_id}"
    )}"
}
```
instance.tf
```
data "terraform_remote_state" "kms" {
  backend = "s3"
  config {
    ...
  }
  defaults {
    kms_ids = ""
  }
}
locals {
  kms_id = "${lookup(data.terraform_remote_state.kms.kms_ids, var.REGION)}"
}
```
The defaults are here so that Terraform doesn't fail if the remote state doesn't exist but the previous code fails with
`lookup: argument 1 should be type map, got type string`

Thanks.

**Comment by apparentlymart** [comment]
Hi @pgmillon,

Unfortunately what you want to do here isn't possible in Terraform v0.11 because the `defaults` argument is defined in the schema as being a map of strings, and so it won't accept any other type. This is actually already fixed in the master branch ready for the forthcoming v0.12 release, so while I don't have workaround to offer for current Terraform I can at least say a fix will be available soon.

**Comment by pgmillon** [comment]
Hi @apparentlymart,
Too bad but thanks for taking time to answer.
