### ISSUE TITLE
provisioner/chef: terraform not running chef install/converge

### ISSUE THREAD

**Issue by rkondakindi** [hashicorp/terraform#21194]
### Terraform Version
```
Terraform v0.11.13
+ provider.aws v2.8.0
+ provider.template v2.1.2
```

### Terraform Configuration Files
```
provisioner "chef" {
  connection {
    type = "ssh"
    user = "centos"
    private_key = "${file("/Users/rkondakindi/.ssh/id_rsa")}"
  }
  prevent_sudo    = false
  use_policyfile  = false
  environment     = "test"
  server_url      = "https://mychef.example.com/organizations/test"
  user_name       = "rkondakindi"
  user_key        = "${file("/Users/rkondakindi/.chef/rkondakindi.pem")}"
  node_name       = "test.example.com"
  run_list        = ["role[jenkins-master]"]
  secret_key      = "${file("/Users/rkondakindi/.chef/secret_key")}"
  recreate_client = true
  on_failure      = "continue"
  fetch_chef_certificates = true
}
```

### Debug Output
I ran `terraform apply` and got below output where I can see `aws_instance.pnp_jenkins_master: Provisioning with 'chef'...` But it never tried to bootstrap chef node. 

```
ws_s3_bucket_policy.bucket_policy: Creation complete after 0s (ID: xxxxxxx)
aws_security_group_rule.http_egress_rule1: Creation complete after 2s (ID: sgrule-xxxxxx)
aws_security_group_rule.http_ingress_rule1: Creation complete after 3s (ID: sgrule-xxxxxxx)
aws_dynamodb_table.tfstate-lock: Creation complete after 9s (ID: test-tests)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Still creating... (10s elapsed)
aws_instance.pnp_jenkins_master: Still creating... (10s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (10s elapsed)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Still creating... (20s elapsed)
aws_instance.pnp_jenkins_master: Still creating... (20s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (20s elapsed)
aws_instance.pnp_jenkins_master: Provisioning with 'chef'...
aws_instance.pnp_jenkins_master: Creation complete after 24s (ID: i-xyxyxyxyxyxy)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Still creating... (30s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (30s elapsed)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Still creating... (40s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (40s elapsed)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Still creating... (50s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (50s elapsed)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Still creating... (1m0s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (1m0s elapsed)
module.app-loadbalancer.aws_lb_target_group.lb_target_group: Creation complete after 1m7s (ID: elb)
module.app-loadbalancer.aws_lb.lb: Still creating... (1m10s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (1m20s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (1m30s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (1m40s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (1m50s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (2m0s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (2m10s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (2m20s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (2m30s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (2m40s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (2m50s elapsed)
module.app-loadbalancer.aws_lb.lb: Still creating... (3m0s elapsed)

```

### Crash Output
It didn't crash. But Chef bootstrap not started not even chef-client install 

### Expected Behavior
Chef-client install and converge my role.

### Actual Behavior
nothing

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context
1. My SSH key configured with passphrase. I was expecting an prompt to enter my passphrase to my SSH key. 
2. I couldn't find an option to provide passphrase in` chef provisioner `
3. Same code works fine with SSH keys doesn't have passphrase.

**Comment by mcascone** [comment]
I am having a similar, intermittent problem. On some runs, the chef provision/converge works just fine. On others, it gets to the `Creating configuration files...` step, and then stops doing anything. TF continues waiting endlessly until timeout. 

It was working consistently as 3 individual resources in my `main.tf`. I refactored to use modules, and now, i just had a case where one module worked, and the other didn't. They're each exactly the same outside of the `run-list` applied.

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner, fix this in it, and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
