### ISSUE TITLE
Oracle Cloud Infrastructure (OCI) as Terraform http backend  for .tfstate file

### ISSUE THREAD

**Issue by tama1214** [hashicorp/terraform#21208]
**Version: Terraform v0.11.13**

We use OCI Object Storage as[ http backed](https://www.terraform.io/docs/backends/types/http.html) to store the tfstate file.

There is no problem with the file storage function, everything is working properly using below script. 

```
terraform {
   backend "http" {
     update_method = "PUT"
     address = "https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate"
      }
 }

 data "terraform_remote_state" "project_a" {
  backend = "http"
  config {
    address = "https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate"
  }
}
```
However, we want to use lock/unlock features for  .tfstate file when using it in the big Team of engineers _(in order to avoid attempts of simultaneous changes .tfstate by several engineers)._

On github, I managed to find an[ excellent example](https://github.com/l2fprod/serverless-terraform-backend/blob/master/terraform/backend.tf) of script for locking / unlocking .tfstate file on http backend _(but it is not for OCI Object Storage)_

I tried to use this example for OCI Object Storage, but when I try to run the updated script (below) I get the following error:

```
terraform {
   backend "http" {
     update_method = "PUT"
     lock_method = "PUT"
     unlock_method  = "DELETE"
     address = "https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate"
     lock_address = "https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate"
     unlock_address = "https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate"
   }
 }

 data "terraform_remote_state" "project_a" {
  backend = "http"
  config {
    address = "https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate"
  }
}
```

**ERROR:**

```
Acquiring state lock. This may take a few moments...

Error releasing the state lock!

Error message: Unexpected HTTP response code 404

Terraform acquires a lock when accessing your state to prevent others
running Terraform to potentially modify the state at the same time. An
error occurred while releasing this lock. This could mean that the lock
did or did not release properly. If the lock didn't release properly,
Terraform may not be able to run future commands since it'll appear as if
the lock is held.

In this scenario, please call the "force-unlock" command to unlock the
state manually. This is a very dangerous operation since if it is done
erroneously it could result in two people modifying state at the same time.
Only call this command if you're certain that the unlock above failed and
that no one else is holding a lock.


Error: Error loading state: Decoding state file version failed: json: cannot unmarshal string into Go struct field jsonStateVersionIdentifier.version of type int



Error: Unexpected HTTP response code 404
```
I tried different options: PUT, GET, POST  - but nothing helped.

Has anyone encountered a similar problem and how did you manage to solve it? Is it possible to use lock / unlock for terraform .tfstate file stored in OCI Object Storage? Does OCI Object Storage support this option? Thank you in advance.

**Comment by bnestelroad** [comment]
I have good news...you are not crazy.  I just tried the same code with my OCI object store and I got the same error you did.  Taking this one step further it appears that my tfstate file got clobbered in the process
```json
{
   "ID":"15ef6709-ef02-510d-8dac-71d6d02363ac",
   "Operation":"OperationTypeApply",
   "Info":"",
   "Who":"vagrant@localhost.localdomain",
   "Version":"0.11.11",
   "Created":"2019-05-20T20:39:17.450730554Z",
   "Path":""
}
```
Not only is this broken, but its dangerously broken.

**Comment by apparentlymart** [comment]
Hi all,

The `http` backend can support locking only with a server that has a locking implementation. The backend itself just makes the request you told it to make, which in the example here is to make a `PUT` request to `https://objectstorage.us-ashburn-1.oraclecloud.com/p/**************/n/netcloud01/b/TEST/o/net_terraform.tfstate`. That is exactly the same request you configured for updating the state, so indeed with this configuration the lock operation would overwrite the state.

I wasn't able to find any information online about support for locking over HTTP in OCI object storage. Unless there is a way to do this that I didn't find, enabling locking against that server will not be possible. If it _were_ possible, it would at least require using a different method and/or address for locking than for updating, in order to allow the server to distinguish a request for a lock for a request to update the state.

The `http` backend is usually used either with a generic write-enabled HTTP server without locking (using just the conventional `GET`/`PUT` methods on a particular URL) _or_ against a specially-written server that can respond to locking requests. Without support on the server for lock/unlock operations, locking is not available.

**Comment by tama1214** [comment]
@bnestelroad , I am glad to here, that I am not crazy =)
@apparentlymart , unfortunately we will have to use another service for this purpose. I tend to use [Consul](https://www.terraform.io/docs/providers/consul/index.html), at least it supports lock
