### ISSUE TITLE
Error reading billing accounts: googleapi: Error 500: Internal error encountered

### ISSUE THREAD

**Issue by mark-00** [hashicorp/terraform#21216]
### Terraform Version

```
2019/05/06 18:27:17 [INFO] Terraform version: 0.12.0 beta2
2019/05/06 18:27:17 [INFO] Go runtime version: go1.11.5
+ provider.google v2.5.1
```

#### main.tf ####

```hcl
module "myProject-test1" {
  source = "./modules/uz_google_project"
  name   = "test1"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test2" {
  source = "./modules/uz_google_project"
  name   = "test2"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test3" {
  source = "./modules/uz_google_project"
  name   = "test3"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test4" {
  source = "./modules/uz_google_project"
  name   = "test4"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test5" {
  source = "./modules/uz_google_project"
  name   = "test5"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test6" {
  source = "./modules/uz_google_project"
  name   = "test6"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test7" {
  source = "./modules/uz_google_project"
  name   = "test7"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test8" {
  source = "./modules/uz_google_project"
  name   = "test8"
  folder      = "folders/xxxxxxxx"
}

module "myProject-test9" {
  source = "./modules/uz_google_project"
  name   = "test9"
  folder      = "folders/xxxxxxxx"
}
```

#### modules/uz_goole_project/main.tf ####

```hcl
resource "google_project" "myProject" {
  name = var.name
  project_id = var.name
  folder_id  = var.folder
  billing_account = "${data.google_billing_account.myBillingAccount.id}"
}

data "google_billing_account" "myBillingAccount" {
  display_name = "xxxxxxxxxxxxxxx"
  open         = true
}
```

### Crash Output

```
Error: Error reading billing accounts: googleapi: Error 500: Internal error encountered., backendError

  on modules/uz_google_project/main.tf line 9, in data "google_billing_account" "myBillingAccount":
   9: data "google_billing_account" "myBillingAccount" {
```

### Expected Behavior
plan should be created

### Actual Behavior
Half of the time there is no problem
Half of the time it gives an error   Error reading billing accounts: googleapi: Error 500: Internal error encountered.

### Steps to Reproduce
repeatedly execute the statement below. 10 times, 100 times, ...
 
rm terraform.tfstate terraform.tfstate.backup myplan.out ;terraform init; terraform plan -out myplan.out -no-color

about half of the time it gives an error. 

### Additional Context

The higher the number of projects defined in `main.tf` the more likely the error occurs.

**Comment by apparentlymart** [comment]
Hi @mark-00! Thanks for reporting this.

Given the formatting of the error, this seems to be coming from the remote Google Cloud Platform API rather than Terraform itself. Given your observation that it seems to happen more often when you have more projects, I wonder if there's some sort of rate limit on this API which you are hitting here.

In this particular case it may be best to raise this issue in [the Google Cloud Platform provider repository](https://github.com/terraform-providers/terraform-provider-google) since that team is likely to have a better sense of whether there _is_ rate limiting on this operation and what, if anything, can be done to work around it.

If this feels like a Terraform v0.12 regression (by which I mean: you've also tried this with earlier versions of Terraform and didn't see this error or any similar error) then we can debug further to see if Terraform v0.12 is, for some reason, perhaps making more requests than earlier versions did.

**Comment by mark-00** [comment]
Did the regression testing. Same problem with 
Terraform v0.11.13
+ provider.google v2.5.1

I will raise an issue in the google provider repo

**Comment by mark-00** [comment]
setting -parallelism=5 solves the problem
see https://github.com/terraform-providers/terraform-provider-google/issues/3574
