### ISSUE TITLE
Feature Request: Show instances when using autoscaler/launch configs?

### ISSUE THREAD

**Issue by shaiguitar** [hashicorp/terraform#2123]
Loving terraform!

Feature request (if this already exists apologize in advance) ... Would be great if there was some way to show instance information if the resources I've created is autoscalers/launch configs but no specific `aws_instance`. 

Something in `terraform show` output would work, although I understand it doesn't necessarily belong there. But it should at least be possible to query it through other means. 

I can find the instances via `aws autoscaling describe-auto-scaling-instances` but I'd rather have my system depend on terraform rather than introducing something else.

Thoughts?

**Comment by matthewrees** [comment]
Simply put, this would be amazing.

I have a quite a few use cases where I could simplify my infrastructure configuration considerably if I was able to reference the instances of an ASG, and there is no way to reference them or their attributes in CloudFormation either.

Massive +1 from me for this request!

**Comment by phinze** [comment]
I understand the desire for this, but there's a bit of an impedance mismatch that prevents us from integrating ASG instances into Terraform. The problem is: the set of instances in an ASG can change at any time.

So picture this hypothetical feature:

```
variable "asg_size" { }
resource "aws_autoscaling_group" "foo" {
  // ...
  desired_capacity = "${var.asg_size}"
}
resource "aws_route53_record" {
  type = "A"
  count = "${var.asg_size}"
  name = "asg-instance-${count.index}.myapp.com"
  value = "${element(aws_autoscaling_group.foo.instances.*.public_ip, count.index)}"
}
```

That might theoretically work for the first set of instances launched into the ASG, but what should happen when the set changes - when an instance is replaced or the group scales up or down? Terraform's not currently designed to deal with scenarios like that, so exposing that information in the config directly could lead users into building configs that exhibit confusing behaviors.

As to adding the information into `terraform show` as a convenience, unfortunately that command does not make any provider API calls - it exists purely to show the state as Terraform sees it, so we don't really have room to add additional external information there.

I'd recommend continuing to do what you're doing to list ASG instances - dropping down to the AWS CLI - that will always be able to give you the most current set of instances in the group.

**Comment by shaiguitar** [comment]
What if we had a different state file that wasn't just the resources listed in the terraform file but the full graph of dependencies (ie, for autoscaler/launch configs, the actual aws instances) and one could do a `terraform update` that would maintain a different state file with the "full" graph of backend infrastructure data?
