### ISSUE TITLE
resource not found with ternary while using random resoruces

### ISSUE THREAD

**Issue by atrakic** [hashicorp/terraform#21243]
### Terraform Version

```
0.11.13
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.11.13"
}

variable "use_random" {}

locals {
 random = "${var.use_random == "true" ? 1 : 0}"

 foo = "${local.random ? random_pet.master_username.id : "default"}"
 bar = "${local.random ? random_id.master_password.b64 : "default"}" 
}

resource "random_pet" "master_username" {
  count = "${local.random}"
}

resource "random_id" "master_password" {
  count = "${local.random}"
  byte_length = 10
}

output "test_random" {
 value = <<-MSG

 foo=${local.foo} 
 bar=${local.bar}
 MSG

```

### Expected Behavior

When var.use_random = "false" no random res should be used.

### Actual Behavior

Ternary fails with attempt to use random resource with following error: 
```
* local.bar: local.bar: Resource 'random_id.master_password' not found for variable 'random_id.master_password.b64'
* local.foo: local.foo: Resource 'random_pet.master_username' not found for variable 'random_pet.master_username.id'

```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. When prompted enter "false".

**Comment by apparentlymart** [comment]
Hi @atrakic! Sorry for this confusing behavior.

This problem arises because in Terraform 0.11 a reference to an attribute of `random_pet.master_username` or `random_id.master_password` is evaluated even if it's inside a conditional on the "arm" that isn't being selected. That then fails in your case when `count = 0`, because there is nothing to refer to.

This limitation is fixed in Terraform 0.12 and later: Terraform will totally ignore the arm of the conditional that isn't selected by the boolean expression result.

To work around this in Terraform 0.11, the most common approach was to use splat expressions in conjunction with `concat`, to ensure that the expression can always be evaluated without error:

```
 foo = "${element(concat(random_pet.master_username.*.id, ["default"]), 0)}"
```

This works because `random_pet.master_username.*.id` produces an empty list when `count = 0` on that resource, and so the resulting list is just ["default"]` and selecting the zeroth element therefore produces `"default"`. When `count = 1` though, the list is then two elements long with the random value as the first element, and so the random value is selected and the `"default"` string is ignored.

Since this bug is already fixed in 0.12, I'm going to close this out. If you can't yet upgrade to Terraform 0.12, I'd suggest using the above workaround to make it work in Terraform 0.11. Thanks for reporting this!
