### ISSUE TITLE
File not found with template_file after switching from "atlas" to "remote"

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform#21247]
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.6.0
+ provider.cloudflare v1.13.0
+ provider.datadog v1.8.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

Relevant structure (omitted lots for brevity)
```
/env
    /dev - entrypoint / working directory
/modules
    /infra
        /main - where the below hcl lives
    /iam
        /data
            /iam_policy
                /app - where the referenced policy lives
```

```hcl
data "template_file" "k8s-accounting-service" {
  template = "${file("${path.module}/../../iam/data/iam_policy/app/k8s-accounting-service.json")}"
}
```

### Expected Behavior

The file is found as it is with the atlas backend.

### Actual Behavior

After switching from the "atlas" backend to "remote", I get the following error:
```
Error: module.kubernetes_app_global.data.template_file.k8s-accounting-service: 1 error(s) occurred:

* module.kubernetes_app_global.data.template_file.k8s-accounting-service: file: open /terraform/terraform/_env/dev/.terraform/modules/3dc222e281606495b0f3f550529da81b/../../iam/data/iam_policy/app/k8s-accounting-service.json: no such file or directory in:

${file("${path.module}/../../iam/data/iam_policy/app/k8s-accounting-service.json")}
```

### Additional Context

We have a very similar issue where sometimes files like this need to exist in a subdirectory of the calling module to be found -- but not always. I haven't been able to find the common cause for those but we had a support ticket a couple years ago (4462). In this case though, it's just a matter of switching to the remote backend and having all of them fail. Before using the remote backend, plans would run fine with the same code -- both locally and in TFE.

This is our oldest project and I don't see the same issue in new projects with the exact same structure/module, even after switching to the remote backend. Is there any possibility of some stale data in the state that could break it?

This project does have a `TERRAFORM WORKING DIRECTORY` set in TFE as well. Again, not a problem with "atlas" backend, but perhaps it's relevant for this issue.

**Comment by jaygorrell** [comment]
Small addendum:

On the new projects that didn't have this issue -- once I pushed my changes to TFE and applied them, I get the same path failures locally now. I thought that was supposed to be a non-issue with the remote backend? It really seems like applying changes somehow broke this... I can't think of anything else that would have played a role.

**Comment by apparentlymart** [comment]
Hi @jaygorrell! Sorry for this confusing behavior.

When you run `terraform plan` or `terraform apply`, does the output from it start with the following message?

```
Running plan in the remote backend. Output will stream here.
```

If so, that suggests that Terraform is running the operation remotely in Terraform Enterprise, and just showing you the logs locally. This is one of the features of the `remote` backend, but in order for it to work it does require all of the files needed for the plan to be discoverable by the process that uploads the configuration to the remote server. I believe there are ways to arrange things so that the remote backend can understand that your current directory is a subdirectory of the containing repository, but I'm not sure of all of the details myself.

Since you are presumably a Terraform Enterprise customer, I would suggest sending this question instead to the Terraform Enterprise support team, who are better able to help with problems where Terraform CLI and Terraform Enterprise are interacting.

**Comment by jaygorrell** [comment]
Thanks @apparentlymart -- I can send it to support.

Just to answer your question, though... yes, it does start with that line and does indeed run in TFE. The odd part is that TFE itself understands the directory structure but when doing a remote plan it fails, even though they both run on TFE.

You can close this though if it's not the appropriate location. I have a related issue about modules and paths that doesn't involve TFE that I can open separately.

**Comment by apparentlymart** [comment]
We may find that a change to Terraform's behavior is warranted once you talk to the support team, so for now I'd suggest mentioning this issue in your support request and we can decide what to do with it once the support team has had a chance to weigh in.

One difference between the remote backend and having Terraform Enterprise trigger a run itself is that the remote backend must upload the local configuration to Terraform Enterprise itself, whereas in the normal case Terraform Enterprise clones a git repository and works with that. It's possible then that the remote backend is not correctly detecting where the "root" of your repository is, and is thus missing things in a parent directory when uploading. I'm not sure though, since the interactions between the remote backend and Terraform Enterprise are maintained primarily by the Terraform Enterprise teams, and so they have a better sense of all of the details than I do. I'm sorry I don't have a more specific answer to share at the moment, but I'm interested to see what comes from your support request.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
