### ISSUE TITLE
0.12-rc1 file function fails due to UTF-8 error 

### ISSUE THREAD

**Issue by sgript** [hashicorp/terraform#21260]
Hey there,

I'm trying to upload lambda code using the archive_file function, however, keep running into this error:
```
Error: Error in function call

  on ../../modules/aws/lambda/main.tf line 13, in resource "aws_lambda_function" "lambda_at_edge":
  13:   source_code_hash = "${base64sha256(file("${data.archive_file.lambda.output_path}"))}"
    |----------------
    | data.archive_file.lambda.output_path is "../../modules/aws/lambda/lambda_at_edge.zip"

Call to function "file" failed: contents of
../../modules/aws/lambda/lambda_at_edge.zip are not valid UTF-8; use the
filebase64 function to obtain the Base64 encoded contents or the other file
functions (e.g. filemd5, filesha256) to obtain file hashing results instead.

Exited with code 1
```

The code looks like:
```data "archive_file" "lambda" {
  type        = "zip"
  source_dir  = "${path.module}/lambda_at_edge"
  output_path = "${path.module}/lambda_at_edge.zip"
}

resource "aws_lambda_function" "lambda_at_edge" {
  filename         = "${data.archive_file.lambda.output_path}"
  function_name    = "${var.application}-lambda-at-edge"
  role             = "${var.iam_role_arn}"
  handler          = "index.handler"
  runtime          = "nodejs6.10"
  source_code_hash = "${base64sha256(file("${data.archive_file.lambda.output_path}"))}"
  publish          = "true"
}
```

The lambda function itself is just a regular node function.

I have looked at the official docs and other examples and can't seem to see what the issues are. Is this related to the new version of Terraform?

Thanks.

**Comment by apparentlymart** [comment]
Hi @sgript! Sorry for this difference in behavior.

In Terraform v0.12, the `file` function can only load text files (UTF-8 encoded) because Terraform language strings are always unicode and so loading raw binary data into them can risk corruption of that data. Although in this particular case this used to work in Terraform 0.11 (because the `file` result was immediately passed to the `base64sha256` function in memory), the `file` function is conservative now to avoid that risk.

The fix for this is, thankfully, straightforward: the new function [`filebase64sha256`](https://www.terraform.io/docs/configuration/functions/filebase64sha256.html) combines the functionality of `file` and `base64sha256` together, avoiding the need to return the raw binary data as a string, so if you rewrite your `source_code_hash` as follows then I think it should work:

```hcl
  source_code_hash = filebase64sha256(data.archive_file.lambda.output_path)
```

The `terraform 0.12upgrade` command described in [the upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html) includes a rule to make this change automatically, so I'd recommend using that tool to apply all of the upgrade rules at once, to see what else it proposes. If you were to make the above change manually then the upgrade tool wouldn't be able to read it anymore (because it's no longer valid 0.11 syntax), so best to run `terraform 0.12upgrade` first -- before making any other changes -- and then see what else might need tweaking from there.

**Comment by sgript** [comment]
This seemed to work, thanks @apparentlymart!
