### ISSUE TITLE
0.12.0-rc1 - Provider version being stripped

### ISSUE THREAD

**Issue by sgript** [hashicorp/terraform#21268]
Hi there,

I'm getting this strange error with provider versions being stripped, although it's being set in the root .tf call that calls all the modules:
```
#!/bin/sh -eo pipefail
source $BASH_ENV
cd environments/$TERRAFORM_ENVIRONMENT
terraform plan -out=../../terraform.plan


Error: Provider configuration not present

To work with
module.staging-infrastructure.module.product_selector.module.aws_cloudfront_distribution.data.aws_acm_certificate.certificate
its original provider configuration at
module.staging-infrastructure.module.product_selector.module.aws_cloudfront_distribution.provider.aws.eu-west-1
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.staging-infrastructure.module.product_selector.module.aws_cloudfront_distribution.data.aws_acm_certificate.certificate,
after which you can remove the provider configuration again.

Exited with code 1
```

Any advice?

The provider version is usually set in:
environments/staging/main.tf
- This calls product_selector module
   - product_selector module calls aws_cloudfront_distribution

Thanks.

**Comment by jbardin** [comment]
Hi @sgript,

Thanks for filing the issue. Can you provide a sample of how the configuration is laid out, and how you define the module blocks?

The error looks like there is (or was) a provider in the module named `aws.eu-west-1` in the `aws_cloudfront_distribution` module. A named provider is not going to inherit a global provider set in a parent module, so we need to see how it was originally configured.

**Comment by sgript** [comment]
Hi @jbardin,

Our configuration layout is as followed:
```
├── cms
│   ├── account.tfvars
│   ├── launch_config
│   └── terraform.tfvars
├── csi
│   └── account.tfvars
├── environments
│   ├── preproduction
│   │   ├── main.tf
│   │   ├── terraform.tfvars
│   │   └── variables.tf -> ../../shared/variables.tf
│   └── staging
│       ├── main.tf
│       ├── terraform.tfvars
│       └── variables.tf -> ../../shared/variables.tf
├── modules
│   ├── aws
│   │   ├── acm_certificate
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── cdn
│   │   │   ├── lambda_at_edge
│   │   │   │   ├── index.js
│   │   │   │   └── package.json
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── eb
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── eba
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── iam_policy
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── iam_role
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── internet_gateway
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── lambda
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── nat_gateway
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── rds
│   │   │   ├── main.tf
│   │   │   └── variables.tf
│   │   ├── route53_record
│   │   │   ├── main.tf
│   │   │   └── variables.tf
│   │   ├── route_table
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── route_table_association
│   │   │   ├── main.tf
│   │   │   └── variables.tf
│   │   ├── s3
│   │   │   ├── main.tf
│   │   │   ├── outputs.tf
│   │   │   └── variables.tf
│   │   ├── security_group
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── security_group_rule_cidr
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── security_group_rule_sg
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── subnet
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   └── vpc
│   │       ├── main.tf
│   │       ├── output.tf
│   │       └── variables.tf
│   ├── infrastructure
│   │   ├── cassie
│   │   │   ├── main.tf
│   │   │   ├── security_groups
│   │   │   │   ├── main.tf
│   │   │   │   ├── output.tf
│   │   │   │   └── variables.tf
│   │   │   └── variables.tf
│   │   ├── csi
│   │   │   ├── main.tf
│   │   │   ├── security_groups
│   │   │   │   ├── main.tf
│   │   │   │   ├── output.tf
│   │   │   │   └── variables.tf
│   │   │   └── variables.tf
│   │   ├── main.tf
│   │   ├── network
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── pricing
│   │   │   ├── main.tf
│   │   │   ├── security_groups
│   │   │   │   ├── main.tf
│   │   │   │   ├── output.tf
│   │   │   │   └── variables.tf
│   │   │   └── variables.tf
│   │   ├── product_selector
│   │   │   ├── main.tf
│   │   │   └── variables.tf
│   │   ├── rentals
│   │   │   ├── main.tf
│   │   │   ├── security_groups
│   │   │   │   ├── main.tf
│   │   │   │   ├── output.tf
│   │   │   │   └── variables.tf
│   │   │   └── variables.tf
│   │   └── variables.tf
│   └── state
│       ├── main.tf
│       └── variables.tf
├── old
│   ├── README.md
│   ├── cassie
│   │   ├── _environment_configs
│   │   │   ├── preproduction.tfvars
│   │   │   ├── production.tfvars
│   │   │   └── staging.tfvars
│   │   ├── acm_certificate
│   │   │   └── terraform.tfvars
│   │   ├── acm_certificate_validation
│   │   │   └── terraform.tfvars
│   │   ├── eb
│   │   │   └── terraform.tfvars
│   │   ├── eba
│   │   │   └── terraform.tfvars
│   │   ├── kms_rds
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db_replica
│   │   │   └── terraform.tfvars
│   │   ├── route53
│   │   │   ├── route53_eb_record
│   │   │   │   └── terraform.tfvars
│   │   │   └── route53_validation_record
│   │   │       └── terraform.tfvars
│   │   └── security_groups
│   │       ├── database_security_group
│   │       │   └── terraform.tfvars
│   │       ├── instance_security_group
│   │       │   └── terraform.tfvars
│   │       └── loadbalancer_security_group
│   │           └── terraform.tfvars
│   ├── cms
│   │   ├── _environment_configs
│   │   │   ├── preproduction.tfvars
│   │   │   ├── production.tfvars
│   │   │   └── staging.tfvars
│   │   ├── acm_certificate
│   │   │   └── terraform.tfvars
│   │   ├── acm_certificate_validation
│   │   │   └── terraform.tfvars
│   │   ├── eb
│   │   │   └── terraform.tfvars
│   │   ├── eba
│   │   │   └── terraform.tfvars
│   │   ├── kms_rds
│   │   │   └── terraform.tfvars
│   │   ├── mysql_db
│   │   │   └── terraform.tfvars
│   │   ├── route53
│   │   │   ├── route53_eb_record
│   │   │   │   └── terraform.tfvars
│   │   │   └── route53_validation_record
│   │   │       └── terraform.tfvars
│   │   └── security_groups
│   │       ├── database_security_group
│   │       │   └── terraform.tfvars
│   │       ├── instance_security_group
│   │       │   └── terraform.tfvars
│   │       └── loadbalancer_security_group
│   │           └── terraform.tfvars
│   ├── csi
│   │   ├── _environment_configs
│   │   │   └── staging.tfvars
│   │   ├── acm_certificate
│   │   │   └── terraform.tfvars
│   │   ├── acm_certificate_validation
│   │   │   └── terraform.tfvars
│   │   ├── eb
│   │   │   └── terraform.tfvars
│   │   ├── eba
│   │   │   └── terraform.tfvars
│   │   ├── kms_rds
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db_replica
│   │   │   └── terraform.tfvars
│   │   ├── route53
│   │   │   ├── route53_eb_record
│   │   │   │   └── terraform.tfvars
│   │   │   └── route53_validation_record
│   │   │       └── terraform.tfvars
│   │   └── security_groups
│   │       ├── database_security_group
│   │       │   └── terraform.tfvars
│   │       ├── instance_security_group
│   │       │   └── terraform.tfvars
│   │       └── loadbalancer_security_group
│   │           └── terraform.tfvars
│   ├── environments
│   │   ├── preproduction
│   │   │   ├── account.tfvars
│   │   │   └── terraform.tfvars
│   │   ├── production
│   │   │   ├── account.tfvars
│   │   │   └── terraform.tfvars
│   │   └── staging
│   │       ├── account.tfvars
│   │       └── terraform.tfvars
│   ├── errors-and-troubleshooting.md
│   ├── kubernetes
│   │   ├── _environment_configs
│   │   │   ├── preproduction.tfvars
│   │   │   ├── production.tfvars
│   │   │   └── staging.tfvars
│   │   ├── config
│   │   │   ├── ambassador-rbac.yaml
│   │   │   ├── ambassador-service.yaml
│   │   │   └── eks-admin-service-account.yaml
│   │   ├── dns
│   │   │   └── terraform.tfvars
│   │   ├── eks
│   │   │   └── terraform.tfvars
│   │   └── scripts
│   │       └── setup.sh
│   ├── pricing
│   │   ├── _environment_configs
│   │   │   ├── preproduction.tfvars
│   │   │   ├── production.tfvars
│   │   │   └── staging.tfvars
│   │   ├── account.tfvars
│   │   ├── acm_certificate
│   │   │   └── terraform.tfvars
│   │   ├── acm_certificate_validation
│   │   │   └── terraform.tfvars
│   │   ├── eb
│   │   │   └── terraform.tfvars
│   │   ├── eba
│   │   │   └── terraform.tfvars
│   │   ├── kms_rds
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db_replica
│   │   │   └── terraform.tfvars
│   │   ├── route53
│   │   │   ├── route53_eb_record
│   │   │   │   └── terraform.tfvars
│   │   │   └── route53_validation_record
│   │   │       └── terraform.tfvars
│   │   ├── security_groups
│   │   │   ├── database_security_group
│   │   │   │   └── terraform.tfvars
│   │   │   ├── instance_security_group
│   │   │   │   └── terraform.tfvars
│   │   │   └── loadbalancer_security_group
│   │   │       └── terraform.tfvars
│   │   └── terraform.tfvars
│   ├── remove-staging-security-group.sh
│   ├── rentals
│   │   ├── _environment_configs
│   │   │   ├── preproduction.tfvars
│   │   │   ├── production.tfvars
│   │   │   └── staging.tfvars
│   │   ├── acm_certificate
│   │   │   └── terraform.tfvars
│   │   ├── acm_certificate_validation
│   │   │   └── terraform.tfvars
│   │   ├── eb
│   │   │   └── terraform.tfvars
│   │   ├── eba
│   │   │   └── terraform.tfvars
│   │   ├── kms_rds
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db
│   │   │   └── terraform.tfvars
│   │   ├── postgres_db_replica
│   │   │   └── terraform.tfvars
│   │   ├── route53
│   │   │   ├── route53_eb_record
│   │   │   │   └── terraform.tfvars
│   │   │   └── route53_validation_record
│   │   │       └── terraform.tfvars
│   │   ├── security_group_rules
│   │   │   ├── europcar_cidr_egress
│   │   │   │   └── terraform.tfvars
│   │   │   └── europcar_cidr_ingress
│   │   │       └── terraform.tfvars
│   │   └── security_groups
│   │       ├── database_security_group
│   │       │   └── terraform.tfvars
│   │       ├── instance_security_group
│   │       │   └── terraform.tfvars
│   │       ├── loadbalancer_security_group
│   │       │   └── terraform.tfvars
│   │       └── rental_providers_security_group
│   │           └── terraform.tfvars
│   └── utils
│       └── sed_cms_secrets.sh
├── rentals
│   ├── account.tfvars
│   ├── launch_config
│   └── terraform.tfvars
└── shared
    └── variables.tf
```

- All our root configurations live inside `environments/<environment_name>/`
  - `<environment_name>` being production, preproduction, staging.
- That then calls **infrastructure** modules (found in `/modules/infrastructure/`)
   - Infrastructure modules then build up their components from AWS modules (found in `/modules/aws`).
- What we are trying to do, inside `modules/aws/cdn/` we use:
   `provider = "us-east-1"`
- This is as CDN uses lambda on edge and [requires to be set in US-East-1](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html)

Any advice on what we might be doing wrongh here?

**Comment by apparentlymart** [comment]
Hi @sgript!

This error tends to occur when `provider` blocks appear inside child modules. While we do support that for pragmatic reasons (sometimes it's the most effective way to model something), it does cause a problem where removing the entire module then removes both the provider configuration and all of the resources at the same time, which means Terraform doesn't have a provider configuration to use when destroying the resources in the module. That is what this message is trying to say.

To avoid this problem, [we recommend in the documentation](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules) that `provider` blocks be placed only in the _root_ module, which in your case would be the various modules under `environments/<environment_name>`. In simple cases the automatic inheritance is sufficient to make that work, but because you are using provider aliases you'll need to pass them explicitly so that Terraform knows how to map them:

```
module "staging-infrastructure" {
  source = "../modules/infrastructure"

  # (any arguments required to set the module input variables)

  providers = {
    # Any aws resources in this module will use the `us-east-1` alias configuration.
    "aws" = "aws.us-east-1"
  }
}
```

There are some more examples of different patterns, including passing multiple distinct aliased providers to a child module, in the documentation section [Passing Providers Explicitly](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly).

Of course, your existing infrastructure already has those `provider` blocks in the cloudfront distribution module. If you were to rework everything to use provider passing like the above and then run `terraform apply` before you remove the module then it should work, but assuming that you don't want to do all of that reorganization work before removing the module there is a potential simpler workaround:

* With all of the module blocks still in place (i.e. restore whichever one you removed just before seeing this error), run `terraform destroy -target=module.staging-infrastructure.module.product_selector.module.aws_cloudfront_distribution` to destroy the resources in that module and anything that depends on them. (Be sure to review the plan before approving it to make sure it's not destroying anything you want to keep!)
* After that destroy succeeds, _then_ remove the module block you were trying to remove, and run `terraform apply` as normal. It should complete successfully and detect that no further changes are required.

In the above I've assumed it was the `module "aws_cloudfront_distribution"` block you were trying to remove. If it was instead one of the parent modules, you should use the parent module's address instead in the `-target` argument, to ensure that all of the resources managed by the module you are removing are destroyed first.

I would still recommend refactoring to move all of the provider blocks into the root modules though, to avoid this problem occurring again.

**Comment by sgript** [comment]
Hey @apparentlymart thanks for the response.

So our current permanent setup is: 
We have one root provider block. One each for per environment.

So in practice, this means we set `provider` in `environments/staging/main.tf` set as:
```
provider "aws" {
  version = "2.9.0"
  region  = "${var.region}"
}
```
The region variable is fed in from the same directory in `environments/staging/terraform.tfvars`.

I have followed the advised steps by removing the parenting module - product selector. I then removed the call to the product selector module itself and the apply completed successfully.

Moving forward with this, do you suggest I pass providers in explicitly? Therefore, have another provider block at root, giving it an alias - hence making it non-default, then use this inside product selector module?

**Comment by sgript** [comment]
So in essence, if `environment/staging/main.tf` is holding multiple pieces of infrastructure, for example:
- A
- B
- C

How do we make it so C applies a region, but A and B follow default? Is this legal:
```
module "staging-infrastructure" {
  providers = {
    aws = aws.use1
    aws = aws.euw1
  }
  ...
  ...
}
```

Then staging's infrastructure would choose which it would want itself - by referencing only the one it wants in its `providers` block? US-East-1 or EU-West-1, etc.

**Comment by apparentlymart** [comment]
Thanks for the additional context, @sgript!

When a child module needs to work with more than one provider configuration (more than one region, in your case) we can use provider aliases _within_ the module too, though we usually prefer to give them more "semantic" names that correspond to what they are used for, rather than their physical location, so that the module can be applied to different regions without editing it.

To do this, the child modules (in your case, your `staging-infrastructure` module, and possibly others beneath it) will need _proxy configuration blocks_, which declare that the module needs a particular aliased provider without actually configuring that provider. In your case it sounds like you need a us-east-1 provider because Cloudfront services are only available there, so I might choose the name "cloudfront" for that alias. In your `infrastructure` module then, you would write a proxy configuration block like this:

```hcl
provider "aws" {
  alias = "cloudfront"
}
```

Because the above doesn't have any settings other than `alias`, it is not valid alone. However, when used in a child module you can pass a provider from the parent module to replace this one, making it valid. So in your root module, you would pass the providers like this:

```hcl
provider "aws" {     # default / already defined.
  version = "2.9.0"
  region  = "${var.region}"
}

provider "aws" {    # non-default / needed only for product selector's lambda at edge and certificate.
  alias   = "use1"
  version = "2.9.0"
  region  = "us-east-1"
}

module "staging-infrastructure" {
  providers = {
    # The child module's default AWS provider is the same as the parent
    "aws"            = "aws"

    # The child module's "cloudfront" alias is the same as the parent module's "use1" alias.
    "aws.cloudfront" = "aws.use1"
  }
}
```

The result of the above is that any resource that has `provider = "aws.cloudfront"` in the child infrastructure module will use the `aws.use1` configuration defined in the root. In this particular case there's no strong reason to ever use a different region with that `aws.cloudfront` provider, because these Cloudfront services are available only in us-east-1 by definition, but the idea here is to have the root module decide how we access cloudfront and any child modules to follow that direction, rather than configuring the provider themselves.

The example in [the documentation](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly) shows a different use-case for this feature of setting up a VPN tunnel between regions. In that case, the behavior of that module can be applied to _any_ pair of regions, so its aliases are named `src` and `dst` for "source" and "destination", to reflect that the module itself just needs any two provider configurations and doesn't particularly care which regions they are configured with.

---

With all of that said, I'd like to clarify something: had you previously tried to do something similar in Terraform v0.11 and found that it worked, but then the behavior was different in Terraform v0.12.0-rc1? We didn't intentionally change anything about the provider passing and resolution logic in Terraform v0.12, so if you saw different behavior between versions that might suggest an unintended regression that we'd like to investigate further.

However, if you tried this for the first time on v0.12 and had no prior experience doing similar operations on Terraform v0.11 then that's fine... I expect that you would've seen a very similar error message had you tried the same thing in Terraform v0.11, but I just want to make sure.

**Comment by sgript** [comment]
Hi @apparentlymart 

Apologies for the repeated queries, but as our configuration is quite nested and perhaps I've not explained it in the best possible way, I am still receiving:
```
Error: missing provider module.staging-infrastructure.provider.aws.use1
```

So if I omit everything that I'm uninterested in, in the minute, our folder structure is:
```
.
├── environments
│   └── staging                       # everything in here is root
│       ├── errored.tfstate
│       ├── main.tf                    # this calls /modules/infrastructure/main.tf as a module
│       ├── terraform.tfvars
│       └── variables.tf
├── modules
│   ├── aws
│   │   ├── acm_certificate
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── cdn
│   │   │   ├── lambda_at_edge
│   │   │   │   ├── index.js
│   │   │   │   └── package.json
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── iam_role
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   │   ├── internet_gateway
│   │   │   ├── main.tf
│   │   │   ├── output.tf
│   │   │   └── variables.tf
│   ├── infrastructure
│   │   ├── main.tf                                # this then calls product_selector/main.tf as a module
│   │   ├── network
│   │   ├── product_selector/
│   │   │   ├── main.tf                         # this then calls modules/*/main.tf files as modules
│   │   │   └── variables.tf

```

This is the only stuff I'm currently interacting with - I've labelled besides them, the ordering.

---

Based on my current understanding of your approach is:
1. In the root, we must define a new `provider` block, within it, giving it an alias.
2. However, you reference `cloudfront` in the root (`environments/staging/main.tf`), however, this is only given the _proxy configuration_ in the child module (`infrastructure/main.tf`) - so how does that work? Perhaps there's some confusion here.

Currently I have implemented the following:

Root (`environments/staging/main.tf`):
```
provider "aws" {
  version = "2.9.0"
  region  = "${var.region}"
}

provider "aws" {
  alias   = "use1"
  version = "2.9.0"
  region  = "us-east-1"
}

terraform {
  backend "s3" {
    bucket  = "veygo-staging-state-file"
    key     = "terraform.tfstate"
    region  = "eu-west-1"
    encrypt = true
  }
}


module "staging-infrastructure" {
  providers = {
    "aws"            = "aws"                    # notice not referenced `cloudfront` here as that from your example is aliased below?
  }
    source      = "../../modules/infrastructure"
}
```

Then the next child module is  `modules/infrastructure/main.tf` which is as followed:
```
provider "aws" {
  alias = "cloudfront"
}

module "product_selector" {
  providers = {
    "aws"            = "aws"
    "aws.cloudfront" = "aws.use1"        # cloudfront has now been aliased above in this file, so using here.
  }
  source = "./product_selector/"
}
```

Next child module as seen to be called is `./product_selector/main.tf`, which is as followed:
```
provider "aws" {
  alias = "cloudfront"
}
module "cdn_components" {
  providers = {
    "aws"            = "aws"
    "aws.cloudfront" = "aws.use1"
  }
  source          = "../../aws/cdn/"              # It's in CDN where we actually define the lambda
```

Next module then is `modules/aws/cdn/main.tf`, as followed:
```
resource "aws_lambda_function" "lambda_at_edge" {
  filename         = "${data.archive_file.lambda.output_path}"
  function_name    = "${var.application}-lambda-at-edge"
  role             = "${var.iam_role_arn}"
  handler          = "index.handler"
  runtime          = "nodejs6.10"
  source_code_hash = "${filebase64sha256("${data.archive_file.lambda.output_path}")}"
  publish          = "true"
  provider = "aws.cloudfront"          # I now reference by alias here
}

resource "aws_cloudfront_distribution" "s3_distribution" {
  ...
  ...
}
```

As you can then see, in the final resource `aws_lambda_function`, I then set `provider = "aws.cloudfront"`. However, I'm having no success, but the error I mentioned (see very above).

Is there something I'm doing fundamentally wrong here or misunderstanding? I apologise if that is the case. If it helps, I can send a full trace of a plan - which is where it's failing.

**Comment by sgript** [comment]
@apparentlymart Any updates with this? Still having issues, may be caused by nesting.

Root `environments/staging/main.tf`, is as you have specified:
```
provider "aws" {
  version = "2.9.0"
  region  = "${var.region}"
}

provider "aws" {
  alias   = "use1"
  version = "2.9.0"
  region  = "us-east-1"
}
```

Then at the top of every subsequent module `main.tf` specifies:
```
provider "aws" {
  alias   = "cloudfront"
}
```

Then within each `module` block in which it needs to be passed:
```
  providers = {
    "aws" = "aws"
    "aws.cloudfront" = "aws.use1"
  }
```

And finally, in the `resource` block where it needs to be consumed:
```
  provider         = "aws.cloudfront"
```

Let me know if this is the correct way to go about it. Unfortunately the nesting in our project may be the issue here.

**Comment by ElayneB** [comment]
> With all of that said, I'd like to clarify something: had you previously tried to do something similar in Terraform v0.11 and found that it worked, but then the behavior was different in Terraform v0.12.0-rc1? We didn't intentionally change anything about the provider passing and resolution logic in Terraform v0.12, so if you saw different behavior between versions that might suggest an unintended regression that we'd like to investigate further.
> 
> However, if you tried this for the first time on v0.12 and had no prior experience doing similar operations on Terraform v0.11 then that's fine... I expect that you would've seen a very similar error message had you tried the same thing in Terraform v0.11, but I just want to make sure.

Stumbled here while upgrading to terraform 12 and wanted to let you know that I experienced behavior change in provider resolution. Terraform 0.12. threw the same error that @sgript posted, and terraform 0.11.4 worked. 

I tracked it down to a module not passing the provider to its child module + the child module not having a provider alias block. Adding both fixed the error.

My module hierarchy
```
rootconfig -> child1 -> child2
```
`terraform 0.11.4` works if the provider is passed + aliased from the `rootconfig` to `child1`. `child2` is never explicitly passed the provider, but runs fine in `terraform 0.11.4`. In `terraform 0.12` it does not run fine and child2 needs to be passed the provider. 

Nesting maybe a factor.
```
terraform/
├── composable
│   └── child1
│       ├── child1.tf
│       └── child2
│           └── child2.tf
└── environments
    └── cloud_forest
        └── rootconfig.tf
```
Hope this helps.

**Comment by canassa** [comment]
I also got this error when I tried to migrate a project to Terraform 0.12, I works without issues on Terraform 0.11.

This is the error that I get:

```
Error: Provider configuration not present

To work with module.main.module.rds.data.aws_security_group.vpn its original
provider configuration at module.main.module.rds.provider.aws.intranet is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.main.module.rds.data.aws_security_group.vpn, after which you can remove
the provider configuration again.
```

`terraform providers` on 0.11:

```
├── provider.aws 2.15.0
├── provider.aws.frankfurt 2.15.0
├── provider.aws.intranet 2.15.0
├── provider.aws.ireland 2.15.0
├── provider.aws.virginia 2.15.0
├── provider.template 2.1.2
└── module.main
    ├── provider.aws (inherited)
    ├── provider.random
    └── module.rds
        ├── provider.aws (inherited)
        └── provider.aws.intranet (inherited)
```

`terraform providers` on 0.12:

```
├── provider.aws 2.15.0
├── provider.aws.frankfurt 2.15.0
├── provider.aws.intranet 2.15.0
├── provider.aws.ireland 2.15.0
├── provider.aws.virginia 2.15.0
├── provider.template 2.1.2
└── module.main
    ├── provider.aws (inherited)
    ├── provider.random
    └── module.rds
        ├── provider.aws (inherited)
        └── provider.aws.intranet <- Notice that it lacks the "(inherited)"
```

We are using the following project structure:

```
├── dev
│   ├── main.tf
│   └── provider.tf
└── modules
   ├── main
   │   └── main.tf
   └── rds
       └── rds.tf
```

We execute the Terraform command from within the `dev` directory, the `provider.tf` contains the following content:

```hcl
provider "aws" {
	version = "2.15.0"
	region  = "eu-west-1"
}

provider "aws" {
	alias   = "ireland"
	version = "2.15.0"
	region  = "eu-west-1"
}

provider "aws" {
	alias   = "frankfurt"
	version = "2.15.0"
	region  = "eu-central-1"
}

provider "aws" {
	alias   = "virginia"
	version = "2.15.0"
	region  = "us-east-1"
}

provider "aws" {
	alias   = "intranet"
	version = "2.15.0"
	region  = "eu-west-1"
}

provider "template" {
	version = "2.1.2"
}

...
```

The dev/main.tf just calls the main module:

```hcl
module "main" {
  source = "../modules/main"
  ...
}
```

And modules/main/main.tf calls the rds module:

```hcl
module "rds" {
  source = "../rds"
  ...
}
```

And on modules/rds/rds.tf we have a `data` resource that causes the problem:

```hcl
data "aws_security_group" "vpn" {
  name     = "openvpn-public"
  provider = "aws.intranet"
}
```

This configuration works fine on 0.11. Is there any workaround for the 0.12? Maybe there is better way to implement this?

Thanks,

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity - all of the relevant code has changed in terraform v0.13.0.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
