### ISSUE TITLE
Destroy -target after using count to create is selecting wrong dependencies.

### ISSUE THREAD

**Issue by sec23206** [hashicorp/terraform#21270]
Provisioning VMs in Azure using the count model to create two identical resources.  Am trying to use destroy to remove just one VM and its associated NIC, but when trying to remove the NIC, Terraform sees it as related to the other VM.

### Terraform Version

```
$ terraform -version
Terraform v0.11.13
```

### Terraform Configuration Files

```
resource "azurerm_network_interface" "botvm-nic" {
  count = 2
...
resource "azurerm_virtual_machine" "botvm" {
  count = 2
...
  network_interface_ids         = ["${element(azurerm_network_interface.botvm-nic.*.id, count.index)}"]

```

### Expected Behavior

When using:
```
terraform destroy -target azurerm_network_interface.botvm-nic[0]
```
I would have expected it to identify NIC[0] and VM[0] which depends on it.

### Actual Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - azurerm_network_interface.botvm-nic[0]

  - azurerm_virtual_machine.botvm[0]

  - azurerm_virtual_machine.botvm[1]


Plan: 0 to add, 0 to change, 3 to destroy.
```
Even after destroying VM[0] by itself and then trying to destroy NIC[0] again, it still wanted to destroy VM[1] with it:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - azurerm_network_interface.botvm-nic[0]

  - azurerm_virtual_machine.botvm[1]


Plan: 0 to add, 0 to change, 2 to destroy.
```
### Steps to Reproduce

"terraform apply" to create both VMs and associated NICs.
"terraform destroy -target azurerm_network_interface.botvm-nic[0]" to try to destroy VM[0] and NIC[0].

### Additional Context

N/A
### References

N/A

**Comment by apparentlymart** [comment]
Hi @sec23206! Sorry for this confusing behavior and thanks for reporting it.

Unfortunately this is currently the expected behavior for this case, for an unfortunate reason: the configuration for `azurerm_virtual_machine.botvm` has a reference to `azurerm_network_interface.botvm-nic.*.id`, which returns the ids of all of the network interface instances together, and thus as far as Terraform is concerned it _does_ depend on them all.

Although you've used the `element` function to retrieve just one item from that list, the dependency resolver only understands references and doesn't know what `element` means in this case.

In future we may introduce a special case for the index operator so that `azurerm_network_interface.botvm-nic.*.id[count.index]` (or, in Terraform 0.12, `azurerm_network_interface.botvm-nic[count.index].id`) can be treated as a special case that connects to the current `count.index`, but that is not currently possible.

Terraform's dependency resolver behavior is designed to conservatively ensure correct ordering during a normal operation (without `-target`), so normally these extra dependency edges do not hurt anything. The `-target` option is one situation where an imprecise dependency graph can cause a problem, and so we would like to improve it in future, but because `-target` is intended only for occasional use the complexity required to handle it better has unfortunately been prohibitive so far in terms of prioritization and maintainability.

I'm not very familiar with Azure resource types, so I'm not sure: would it work here to _just_ destroy the VM, and then have Terraform create a new VM and attach the existing network interface to it?

---

If this were Terraform 0.12 rather than 0.11, an improvement in it would offer a different path: running `terraform taint` with both `azurerm_network_interface.botvm-nic[0]` and `azurerm_virtual_machine.botvm[0]` would mark them both for replacement in the next operation, and Terraform would be able to see for itself that `azurerm_virtual_machine.botvm[1]` is not affected.

Unfortunately that doesn't work as expected in Terraform 0.11, because `azurerm_network_interface.botvm-nic.*.id` when any one of the instances is planned for replacement causes the entire result to be unknown until apply time, making Terraform conservatively assume it needs to replace both of the virtual machines.

Terraform 0.12 fixes that by making `azurerm_network_interface.botvm-nic.*` return a list where only element zero is unknown, leaving element 1 untouched and thus allowing Terraform to correctly determine that the id of network interface 1 will not be changing.

**Comment by sec23206** [comment]
Thanks for the response.  What you describe make sense, and actually explains other strange behavior ... I'm using provisioner remote-exec to perform post-deployment configuration, and assumed I would need similar syntax:

```
connection {
    host     = "${element(azurerm_network_interface.botvm-nic.*.private_ip_address, count.index)}"
...
```
It seemed like the remote-exec was happening more times than just twice (once for each VM), so perhaps it **was** executing on both NICs for each VM?

> I'm not very familiar with Azure resource types, so I'm not sure: would it work here to just destroy the VM, and then have Terraform create a new VM and attach the existing network interface to it?

Perhaps so will investigate.  While using ```count``` seemed like a great option to provision a large number of resources (I was just testing with two to start) without having to maintain individual template files, this particular behavior may rule out my using it (at least until 0.12 is generally available).  I'll call this topic "closed", and thanks again.
