### ISSUE TITLE
Running Terraform init on s390x fails to install Provider Plugins

### ISSUE THREAD

**Issue by james-crowley** [hashicorp/terraform#21283]
### Terraform Version
```
root@0d5a563921ea:/tmp/test# terraform -v
Terraform v0.11.13
```

### Terraform Configuration Files
```hcl
provider "openstack" {
  user_name   = "${var.user_name}"
  password    = "${var.password}"
  tenant_name = "${var.tenant_name}"
  domain_name = "${var.domain_name}"
  auth_url    = "${var.auth_url}"
}

resource "random_pet" "label" {
  separator = "-"
  length    = "2"
}

resource "openstack_compute_instance_v2" "_vm" {
  depends_on = ["openstack_networking_floatingip_v2.ten_dot", "openstack_blockstorage_volume_v2._vm_vol"]
  name              = "${random_pet.label.id}-${format("${lower(var.instance_name)}")}"
  image_name        = "TEST"
  flavor_name       = "TEST"
  availability_zone = "${var.availability_zone}"
  user_data         = "${local.cloud_init_file}"
}

resource "openstack_blockstorage_volume_v2" "_vm_vol" {
  size        = 150
  name        = "${random_pet.label.id}-${format("${lower(var.instance_name)}-docker")}"
  description = "Docker Volume for ${random_pet.label.id}"
}

resource "openstack_compute_volume_attach_v2" "_vm_vol_attach" {
  instance_id = "${openstack_compute_instance_v2._vm.id}"
  volume_id   = "${openstack_blockstorage_volume_v2._vm_vol.id}"
}

resource "openstack_networking_floatingip_v2" "nine_dot" {
  pool = "TEST"
}

resource "openstack_networking_floatingip_v2" "ten_dot" {
  pool = "TEST"
}

resource "openstack_compute_floatingip_associate_v2" "_ip_associate" {
  floating_ip = "${openstack_networking_floatingip_v2.ten_dot.address}"
  instance_id = "${openstack_compute_instance_v2._vm.id}"
}
```

### Debug Output
```
root@0d5a563921ea:/tmp/test# terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

No available provider "random" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.


No available provider "openstack" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.
```

### Expected Behavior
Should install the Openstack and random provider plugins.

### Actual Behavior
Even though Openstack and the random provider plugins work on Terraform `v0.11.13`, they produce the error above. They should not being producing that error, and should install fine.

### Steps to Reproduce
- Install Terraform on s390x, https://github.com/linux-on-ibm-z/docs/wiki/Building-Terraform and https://github.com/linux-on-ibm-z/scripts/issues/6
- `Terraform init`

### Additional Context
I am not sure how much testing has been done with Terraform and s390x. So this might be a bug in how plugins are handle on different archs.

On my Mac, I am running Terraform `v0.11.13` and the above code works fine. 

### References
Resources for install Terraform `v0.11.13` on s390x
https://github.com/linux-on-ibm-z/scripts/issues/6
https://github.com/linux-on-ibm-z/docs/wiki/Building-Terraform

**Comment by apparentlymart** [comment]
Hi @james-crowley!

x390x is not an architecture supported by official Terraform releases. Therefore there are no x390x builds of any providers available.

While you _can_ build Terraform from source yourself on other architectures, that only gives you a build of Terraform Core. The providers themselves also need to be built, and `terraform init` expects to find already-built packages for the target architecture available for installation. It is not capable of building providers from source.

To use Terraform on any unsupported architecture then requires also building from source the providers you want to use. These can be built, in principle, using a similar procedure you used for building Terraform itself. I can't promise that all of them will follow the same exact procedure or that they will all work on an otherwise-unsupported architecture, because each is its own codebase with its own build scripts/etc, but for any you _are_ able to build you can place the generated executable (named something like `terraform-provider-random_v1.0.0`, to indicate the correct provider type and version number) in the same directory where the `terraform` executable is, and then `terraform init` should find and use those local builds rather than trying to download and install an official build.

We can't provide any more specific guidance on this, because we only officially support the architectures listed on [the download page](https://www.terraform.io/downloads.html). While we don't make any effort to _block_ building Terraform from source and using it on other architectures, we also cannot provide assistance in doing so.

With that said, the behavior you are seeing is expected when you build from source on an unsupported architecture. The path forward here is either to also build the providers you need from source code or to use Terraform on a supported platform. We don't have any plans to add any new supported platforms to the matrix in the near future, so I'm going to close this out.

We have an existing issue #18708 covering potential support for new platforms, which you may wish to add a note to about `x390x` for future consideration, but we don't expect to be adding support for any new platforms in the near future due to current priorities being elsewhere.

**Comment by james-crowley** [comment]
@apparentlymart Thanks for the quick response. I am a little disappointed that `s390x` support won't be coming anytime soon, but happy to hear its not out of the running completely. 

When you guys do come around to support other archs, s390x, PowerPC, etc, feel free to reach out to me. I am more then willing to work with you guys. 

IBM has some resources for developers like the LinuxOne Community Cloud where you can develop against `s390x` for free. 

I personally love your products and have been working with Packer Team to get s390x support. Would love to see more Hashicorp products running on `s390x`!
