### ISSUE TITLE
Running apply with -target blows away some outputs 

### ISSUE THREAD

**Issue by voroniys** [hashicorp/terraform#21317]
### Terraform Version

```
0.11.13
...
```

### References

#9287 

It is closed without being solved. The issue exists already for over 4 years and still not fixed.
The ticket was closed though.

**Comment by jbardin** [comment]
Hi @voroniys,

Sorry you're having a problem with this; it's certainly possible there had been a regression since the original issues in the 3 years since they were closed out.

I took the original example however, and confirmed that works as expected in the upcoming release. If you have an example that still does not work, please feel free to file an issue against 0.12 so that we can reproduce the problem.

Thanks!

**Comment by voroniys** [comment]
I see this situation for a several months already - bugs in 0.11 are ignored under the statement it is solved in 0.12 which will be released in some far future.

Your current release is 0.11 and you have to support it at least till 0.12 is GA of course if you have just a minimal respect to your customer base. But looks like you don't.

SO I know a better solution - I abandon terraform with its absolutely shity support, with bugs being open for over 3 years and start using CloudFormation. At least it will solve for me all issues with features supported by terraform
