### ISSUE TITLE
string comparison

### ISSUE THREAD

**Issue by kzw** [hashicorp/terraform#21318]
### Current Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.5.0
+ provider.null v2.1.0
+ provider.pagerduty v1.2.1
+ provider.template v2.1.0

```

### Use-cases

We use `aws_autoscaling_schedule` to spin up and down machines on schedule.  But AWS automatically deletes these objects after the schedule date.  So our usage was going to be 

```
resource "aws_autoscaling_schedule" "this" {
  count = "${var.start_time > timestamp() ? 1 : 0}"
...

}
```
but this does not appear to work because I believe that terraform comparison operators are for numbers only.
### Attempted Solutions

Please see above.
### Proposal

Extend `>` and `<` to also work with string.
### References

https://www.terraform.io/docs/configuration/expressions.html

**Comment by apparentlymart** [comment]
Hi @kzw! Thanks for this feature request.

The Terraform language is designed to perform automatic type conversions to avoid having to worry about situations like a string containing decimal digits or passing a number where a string is expected, because the language will automatically convert types where possible to make things work in most cases.

A big part of that design is that Terraform's operators serve as _type implications_, so currently when you use the `<` and `>` operators you're implicitly telling Terraform that it needs to convert both of the arguments to number before doing the comparison. That's important in situations where strings contain decimal digits, since converting to numeric and then comparing can produce a different result than just comparing the string byte-for-byte.

With that said, overloading the comparison operators to have different behavior per type is not a path we can take without impacting existing use-cases, but that doesn't mean we can't implement some _other_ way to compare strings or to compare timestamps, both of which would address your use-case here.

One optional that should work with existing functionality already built for Terraform 0.12 is to reformat the timestamp so that it _can_ be compared numerically. The new [`formatdate`](https://www.terraform.io/docs/configuration/functions/formatdate.html) function would allow that, as long as both timestamps are expressed in the same timezone:

```
formatdate("YYYYMMDDhhmmss", var.start_time) > formatdate("YYYYMMDDhhmmss", timestamp())
```

However, adding `stringcompare` and/or `timecompare` function that returns `-1`, `0`, or `1` for "before", "equal", and, "after" would make the intent clearer here. I think for your use-case in particular a specialized time comparison function would be better because then it could potentially also take into account the UTC offset in the timestamp and produce the correct result when the two timestamps are in different timezones, though I understand that in your case you probably just ensured both timestamps were in UTC to avoid that problem.

---

Unfortunately a more fundamental problem with your specific use-case is that `timestamp` is the time of _apply_, not the time of _plan_, and so it doesn't have a known value during planning. The `count` argument is constrained to accept only values that are known during planning, so even if we were to add a way to compare these timestamps you'd then see the following error instead:

```
Error: Invalid count argument

  on example.tf line 2, in resource "aws_autoscaling_schedule" "this":
   2:   count = "${var.start_time > timestamp() ? 1 : 0}"

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

The message is a little misleading in this particular case because `timestamp()` isn't a resource you can "apply first": its value changes for every run, so it never converges.

I think the main tension in this case is that `aws_autoscaling_schedule` is a rather strange resource that doesn't really meet Terraform's expectations: it expects to be managing the full lifecycle of an object, and so an object that just vanishes at some future date doesn't fit well within Terraform's featureset.

I wonder if it would be better to try to address this need within the `aws_autoscaling_schedule` resource itself, since that resource is the odd thing in this situation and usually we expect providers to be responsible for adapting the quirks of remote APIs to Terraform's model. Off the top of my head, a different design I might consider would be:

* Add a new computed attribute to `aws_autoscaling_schedule` called `expired`, which is set to true for an autoscaling schedule that no longer applies because it's in the past.
* During initial create, if the provider receives the error from AWS that indicates the `start_time` is invalid, it _still lets the create succeed_ but immediately sets `expired` to true. (In a future SDK version when providers are able to return warnings from any operation it would be useful to have the provider also return a warning in this situation, because it is likely to indicate user error in most cases.)
* During refresh, if the provider finds that the schedule no longer exists, it would set `expired` to true rather than deleting the object as would normally be true.
* During planning, if `expired` is true and the `start_time` has changed compared to the previous object then mark the `start_time` as "requires replacement" (or "forces new resource", in v0.11 terminology) to cause the schedule object to be re-created on apply.

In this proposed model, Terraform's model of `aws_autoscaling_schedule` is slightly looser than EC2's own in that rules from the past are treated as no-op rather than error. This means you can safely leave an expired rule in the Terraform configuration until any later point where it's time to update or remove it. The configuration for your use-case would be much more straightforward/intuitive then:

```hcl
resource "aws_autoscaling_schedule" "this" {
  start_time = "${var.start_time}" # no problem if this is in the past; will just be no-op
  end_time   = "${var.end_time}" # no problem if this is in the past; will just be no-op

  # etc, etc
}
```

A change like this would need to happen in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) rather than this Terraform Core repository, so I think _this_ issue can represent just the idea of having string and/or time comparison functions, but we know that won't be completely sufficient for your use-case because conditionally disabling something based on time is not part of Terraform's model, and seems rare enough in practice that it'd be better solved at the provider level rather than via a Terraform Core feature.

---

Thanks again for sharing this use-case! It's an interesting one, and I hadn't previously known about the quirky lifecycle behavior of AWS Autoscaling Schedule objects.

**Comment by apparentlymart** [comment]
Looking at this again some time later, I think I'm going to close this out for the moment because:

* For the purposes of time comparison, the `formatdate` comparison I suggested can work in the mean time, having a first-class time comparison function alone wouldn't actually address this problem for the other reasons I described.
* We now have terraform-providers/terraform-provider-aws#8646 open to represent this usability problem from the AWS provider's perspective, and I expect AWS provider team prioritization to be the main driver for that even if it does lead to some changes in Terraform Core. There's no immediate action we can take in Terraform Core without some design work on the AWS provider side, so this issue therefore isn't representing something actionable right now.

If the AWS provider issue does lead to some feature requests in Terraform Core, I expect we'll open new issues representing those more specific needs.

Thanks again for reporting this @kzw! I see that you already found and subscribed to the AWS provider issue, so you'll see any ongoing discussion about this over there.
