### ISSUE TITLE
Terraform 0.12.0 crashes on init - module with version and fully qualified filepath source

### ISSUE THREAD

**Issue by sl1pm4t** [hashicorp/terraform#21328]
### Terraform Version

```
Terraform v0.12.0-rc1
```

### Terraform Configuration Files

```hcl
module "mod" {
  source  = "/full/path/to/module"
  version = "0.1.2"
}
```

### Crash Output

crash.log = https://gist.github.com/sl1pm4t/094fc414fdb2359849484053367c5f94

### Expected Behavior

Init without panic, or print error message that `version` attribute is not valid for module sources with path.

### Actual Behavior

Panic and crash

### Steps to Reproduce

1. Create a `main.tf` file with the following contents:
```hcl
module "mod" {
  source  = "/full/path/to/module"
  version = "0.1.2"
}
```

2. Update the source to the fully qualified path to a Terraform module on your local filesystem.

3. Run `terraform init` (with Terraform 0.12.0-rc1)

### Additional Context

The same issue is not observed if the module source has a relative path:

```hcl
module "mod" {
  source  = "./mod"
  version = "0.1.2"
}
```

The following error is reported:
```
Error: Invalid version constraint

Cannot apply a version constraint to module "mod" (at main.tf:1) because it
has a relative local path.

```

**Comment by apparentlymart** [comment]
Thanks for finding and reporting this, @sl1pm4t!

It looks like Terraform is trying to compare two version constraints where one of them is `nil` for some reason, so I think the fix here will be to determine why it is `nil` and either fix so it isn't (could perhaps be an empty version constraint instead) or to make the comparison logic resilient to `nil` being provided.

Initial skimming of the stack trace indicates that the crash is originating here:
https://github.com/hashicorp/terraform/blob/bec4641867b47b660a6254cda67d29e1a7f88756/configs/configload/loader_load.go#L67-L77

I assume (though haven't verified) that `record.Version` is `nil` here, possibly because this is a local filesystem path where independent versioning is not supported.

It would probably crash in the same way with the relative path except that there's already a check to ensure that version constraints cannot be used with relative paths. Perhaps part of the solution here would be to fix that validation rule so that absolute filesystem paths can't be used with version constraints either, since the `version` argument should only actually be accepted for Terraform Registry addresses.

**Comment by apparentlymart** [comment]
Oh, sorry I didn't see that there was a PR attached to this when I was first commenting! We'll take a look at that soon. Thanks, @sl1pm4t!
