### ISSUE TITLE
Terraform concat strings

### ISSUE THREAD

**Issue by tama1214** [hashicorp/terraform#21320]
Terraform v0.11.13

I want to connect two strings into one, but I could not find a suitable terraform function to do it

```
variable "var1" {default = "abcd"}
variable "var2" {default = "1234"}
```

result value should be  "**abcd1234**"  ( "var1"+"var2")

**concat** function not suit, because it is work only for lists (not for strings)
**merge** function not suit, because it is work only for maps (not for strings)

Is there a function to concat strings in terraform v0.11.13?

Thank you.

**Comment by apparentlymart** [comment]
Hi @tama1214,

The usual way to write this in Terraform would be to use the string template syntax:

```hcl
"${var.var1}${var.var2}"
```

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by tama1214** [comment]
@apparentlymart , Thank you for reply.
