### ISSUE TITLE
Terraform interpolate MAP variable in template file.

### ISSUE THREAD

**Issue by wajahatch888** [hashicorp/terraform#21354]
### Terraform Version

```
 0.11.13
```

### Terraform Configuration Files

```hcl
variable "global" {
    type  = "map"
    default = {
        NAME = "TEST"
        ADDR = "Test123"
    }
}

data "template_file" "june-web" {
  template = "${file("${path.module}/web.tpl")}"
  vars = {
    GLOBAL = "${jsonencode(var.global)}"
  }
}

**web.tpl**
My Name is ${jsondecode(GLOBAL)["Name"]}


```

### Expected Behavior
After rendering it should show the following output.
My Name is TEST

### Actual Behavior
failed to render : parse error  expected "}" but found "["

**Comment by apparentlymart** [comment]
Hi @wajahatch888!

What you are trying to do here is, unfortunately, not possible in Terraform v0.11. You are using some features in this example that are coming very soon in the v0.12.0 release, and already available in [its release candidate](https://www.hashicorp.com/blog/releasing-terraform-0-12-0-rc1).

If you use Terraform v0.12 then you won't actually need the `template_file` data source or the JSON encoding at all, because the new [`templatefile`](https://www.terraform.io/docs/configuration/functions/templatefile.html) function is available:

```hcl
variable "global" {
    type  = "map"
    default = {
        name = "TEST"
        addr = "Test123"
    }
}

output "example" {
  value = templatefile("${path.module}/web.tpl", {
    global = var.global
  })
}
```

```
My name is ${global.name}.
```

**Comment by wajahatch888** [comment]
Thanks @apparentlymart for very quick reply.

How can I achieve this in 0.11.13 ?  Anyway around?

**Comment by apparentlymart** [comment]
No, unfortunately the 0.11.13 release does not have a `jsondecode` function and `template_file` does not permit passing maps, so this is impossible. The only way to do it is to pass individual keys into the `template_file` vars:

```hcl
data "template_file" "june-web" {
  template = "${file("${path.module}/web.tpl")}"
  vars = {
    name = "${var.global.name}"
    addr = "${var.global.addr}"
  }
}
```

**Comment by wajahatch888** [comment]
Got it. Thanks alot @apparentlymart

**Comment by apparentlymart** [comment]
Hi again @wajahatch888!

Terraform v0.12 has now been released, so I'm going to close this out. The `templatefile` function (or, for smaller templates, just inline interpolation sequences) are our recommended way to use templates in Terraform v0.12, and can support values of any type due to a tighter integration with Terraform Core.
