### ISSUE TITLE
Error during apply - diffs didn't match during apply

### ISSUE THREAD

**Issue by ntodd** [hashicorp/terraform#21351]
When lowering `count` of "web_server" from 4 to 1, diffs did not match during apply.

I attempted to use `droplet_tag = "app_web"` instead of `droplet_ids` in the load balancer config, and that did appear to work (apply began to error on other resources that also use the `${digitalocean_droplet.web_server.*.id}` splat).

Increasing the count works as expected, only lowering the count fails.

### Terraform Version

```
Terraform v0.11.13
+ provider.digitalocean v1.3.0
+ provider.local v1.2.2
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
resource "digitalocean_droplet" "web_server" {
  image              = "${var.web_server_image}"
  name               = "app-prod-web-${count.index + 1}"
  region             = "nyc1"
  size               = "s-1vcpu-1gb"                                  
  monitoring         = true
  private_networking = true
  count              = 1
  ssh_keys           = ["${digitalocean_ssh_key.ssh_key.fingerprint}"]
  tags               = ["app_web", "production"]

  lifecycle {
    create_before_destroy = true
  }
}

resource "digitalocean_loadbalancer" "web_loadbalancer" {
  name                   = "app-prod-loadbalancer-1"
  region                 = "nyc1"
  enable_proxy_protocol  = true
  redirect_http_to_https = true

  sticky_sessions {
    type               = "cookies"
    cookie_name        = "app_lb"
    cookie_ttl_seconds = 3600
  }

  forwarding_rule {
    entry_port     = 443
    entry_protocol = "https"

    target_port     = 80
    target_protocol = "http"

    certificate_id = "${digitalocean_certificate.cert.id}"
  }

  healthcheck {
    port     = 22
    protocol = "tcp"
  }

  droplet_ids = ["${digitalocean_droplet.web_server.*.id}"]
}
```

### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* digitalocean_loadbalancer.web_loadbalancer: digitalocean_loadbalancer.web_loadbalancer: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.13
    Resource ID: digitalocean_loadbalancer.web_loadbalancer
    Mismatch reason: attribute mismatch: droplet_ids.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"droplet_ids.#":*terraform.ResourceAttrDiff{Old:"4", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "droplet_ids.1802451866":*terraform.ResourceAttrDiff{Old:"144310937", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "droplet_ids.1920207579":*terraform.ResourceAttrDiff{Old:"144310936", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "droplet_ids.3975620437":*terraform.ResourceAttrDiff{Old:"144310938", New:"0", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "droplet_ids.850927182":*terraform.ResourceAttrDiff{Old:"144308461", New:"144308461", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

### Expected Behavior
3 of the digitalocean_droplet resources should have been destroyed and the digitalocean_loadbalancer should have been updated with the new list of droplet_ids.

### Actual Behavior
Apply failed.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
None.

**Comment by apparentlymart** [comment]
Hi @ntodd! Thanks for reporting this and sorry for the delayed response.

This class of error means that the provider produced a different plan during the apply step than it had during the plan step, which Terraform treats as an error to raise the fact that something different has happened than what was planned.

In this case, based on the error message, it seems like somehow the `droplet_ids` argument was already updated by the time Terraform visited `digitalocean_loadbalancer.web_loadbalancer` during the plan step, even though that planned change hadn't been applied yet, and so now there's no change to make at all.

Unfortunately the reason for this is likely something specific to DigitalOcean itself or to the DigitalOcean provider; perhaps deleting the droplet somehow pre-emptively updates the load balancer, for example. I'm going to ask our bot to move this over to the DigitalOcean provider repository because the maintainers of the provider are more familiar with DigitalOcean and the provider logic and can therefore hopefully see what might be causing this problem. The key requirement here is that the `droplet_ids` value stay consistent between the plan step and the apply step.

(Note for provider developers: if you are testing this on Terraform 0.12, the specific error message is now different. It will instead lead with the message "Provider produced inconsistent final plan". That new error message reports the same situation as "diffs didn't match during apply", but gives a more specific indication of what was inconsistent.)
