### ISSUE TITLE
Plugins directory - /usr/local/bin - not documented

### ISSUE THREAD

**Issue by Constantin07** [hashicorp/terraform#21365]
### Terraform Version
```
v0.11.13
```

### Terraform Configuration Files
Any, not important.

### Expected Behavior
It should mentions the missing `/usr/local/bin` as search directory too.

### Actual Behavior
The documentation page https://www.terraform.io/docs/plugins/basics.html mentions only `~/.terraform.d/plugins` as a search directory for custom/community providers.

### Steps to Reproduce
Place a custom provider in `/usr/local/bin` and run `terraform init`

### Additional Context
Documentation page should be updated.

**Comment by apparentlymart** [comment]
Hi @Constantin07!

The "Plugin Basics" page is aiming to give more direct instruction about a single option because it's introductory material. The user plugins directory in the home directory is the main place we recommend users place third-party plugins, so that is the one covered there.

The section also links from "How Terraform Works: Plugin Discovery" to the [Discovery](https://www.terraform.io/docs/extend/how-terraform-works.html#discovery) documentation, which includes all of the search locations and different less-common reasons why one might choose each one.

This sort of tradeoff is often necessary in documentation because for introductory material it's typical to show only the most common approach that solves the user's problem -- or else the introduction would become overwhelmed with detail about what is, at that point in the guide, ancillary to what's being discussed. Since it was intentional that the full details are split out into a separate section outside of the initial guide, and most users don't need to know about any search path other than the primary one in the home directory, I don't expect we will make significant changes here. However, we could tweak the language used to link to the other documentation to perhaps make it more explicit that there are some further possibilities documented there.

**Comment by Constantin07** [comment]
Thanks @apparentlymart for prompt and comprehensive response.

I'm just sharing my experience as a user of the tool. To me, it wasn't obvious that this subject is placed (or can be found) under "How Terraform Works: Plugin Discovery". 

Secondly, this documentation is placed under "Extending Terraform" which as a simple/basic user of the tool I'm not expecting to look into. To me it's a bit confusing that in order to know of additional directories, I have to search under advanced docs.

To give you more context: I'm runnig terraform in a Docker container as an unprivileged user, which actually doesn't exist in container (via Jenkins pipeline). So, to keep it minimalistic I don't want to create a user just for the sake of home directory required to place the terraform provider in.

PS: In my opinion, adding this dir to plugin basics page would be much beneficial so it can be found in one place (honestly, I don't see the reason of treating `/usr/local/bin` as advansed topic incontrast to home dir which is treated as introductory). It just makes finding docs much harder.

**Comment by mildwonkey** [comment]
All of the documentation (and underlying code, for that matter!) has changed as of terraform v0.13, so I am going to close this issue. Thanks!
