### ISSUE TITLE
TF_CLI_CONFIG_FILE not respected

### ISSUE THREAD

**Issue by ambis** [hashicorp/terraform#21376]
### Terraform Version

```
0.11.14
```

### Debug Output
See line 4
```
2019/05/21 14:28:22 [INFO] Terraform version: 0.11.14
2019/05/21 14:28:22 [INFO] Go runtime version: go1.12.4
2019/05/21 14:28:22 [INFO] CLI args: []string{"/bin/terraform", "init"}
2019/05/21 14:28:22 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2019/05/21 14:28:22 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/21 14:28:22 [INFO] CLI command args: []string{"init"}
2019/05/21 14:28:22 [DEBUG] plugin: waiting for all plugin processes to complete...
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
```

### Expected Behavior
2019/05/21 14:28:22 [DEBUG] Attempting to open CLI config file: /tmp/foo

### Actual Behavior
2019/05/21 14:28:22 [DEBUG] Attempting to open CLI config file: /root/.terraformrc

### Steps to Reproduce
Run:
```bash
docker run -e TF_CLI_CONFIG_FILE='/tmp/foo' -e TF_LOG=trace hashicorp/terraform:0.11.14 init
```

**Comment by mildwonkey** [comment]
Hi @ambis, thank you for reporting this!

I initially labeled this as a bug, as I could confirm that it was working on 0.12.0-rc1 and the TF_CLI_* env vars were added back in terraform 0.9, but it turns out that this _specific_ variable was added in terraform 0.12: https://github.com/hashicorp/terraform/pull/20834

In 0.11.14 and earlier you can use the `TERRAFORM_CONFIG` environment variable to get the same result: `TERRAFORM_CONFIG='/tmp/foo'`
