### ISSUE TITLE
Chef Provisioner doesn't create log file even with log_to_file : true 

### ISSUE THREAD

**Issue by sunilagrawal86** [hashicorp/terraform#21385]
Chef Provisioner doesn't create log file even with log_to_file : true 

### Terraform Version
```
$:terraform -v
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
server_url      = “${var.cms_chef_server_url}”
 user_name       = “camadmin”
 use_policyfile = “true”
 policy_group = “${var.policy_group}”
 policy_name =   “${var.policy_name}”
 user_key        = “${file(“${var.cmschefKeyFile}“)}”
 node_name       = “${var.name}.${var.domain}”
 client_options = [“verify_api_cert     false”, “log_location  ‘/var/chef/cache/chef.log’“]
 ssl_verify_mode = “:verify_none”
 skip_install    = “true”
 recreate_client = “false”
 skip_register = “true”
 log_to_file = “true”
```

### Debug Output
```
null_resource.ChefBootstrap (chef): Starting initial Chef-Client run...
null_resource.ChefBootstrap (chef): Writing Chef Client output to logfiles/satstwin1206.sunil.com
null_resource.ChefBootstrap: Still creating... (20s elapsed)
```

### Expected Behavior
As per chef provisioner documentation , We should see logfiles folder as well satstwin1206.sunil.com file on the VM 

### Actual Behavior

I don't find logfiles folder as well satstwin1206.sunil.com file on the VM 

### Steps to Reproduce

Logs : 

```
null_resource.ChefBootstrap (chef): Starting initial Chef-Client run...
null_resource.ChefBootstrap (chef): Writing Chef Client output to logfiles/satstwin1206.sunil.com
null_resource.ChefBootstrap: Still creating... (20s elapsed)
null_resource.ChefBootstrap: Still creating... (30s elapsed)
null_resource.ChefBootstrap: Still creating... (40s elapsed)
null_resource.ChefBootstrap: Still creating... (50s elapsed)
null_resource.ChefBootstrap: Still creating... (1m0s elapsed)
null_resource.ChefBootstrap: Still creating... (1m10s elapsed)
null_resource.ChefBootstrap: Still creating... (1m20s elapsed)
null_resource.ChefBootstrap: Still creating... (1m30s elapsed)
null_resource.ChefBootstrap: Still creating... (1m40s elapsed)
null_resource.ChefBootstrap: Still creating... (1m50s elapsed)
null_resource.ChefBootstrap: Still creating... (2m0s elapsed)
null_resource.ChefBootstrap: Still creating... (2m10s elapsed)
null_resource.ChefBootstrap: Still creating... (2m20s elapsed)
null_resource.ChefBootstrap: Still creating... (2m30s elapsed)
null_resource.ChefBootstrap: Still creating... (2m40s elapsed)
null_resource.ChefBootstrap: Still creating... (2m50s elapsed)
null_resource.ChefBootstrap: Still creating... (3m0s elapsed)
null_resource.ChefBootstrap: Still creating... (3m10s elapsed)
null_resource.ChefBootstrap: Still creating... (3m20s elapsed)
null_resource.ChefBootstrap: Still creating... (3m30s elapsed)
null_resource.ChefBootstrap: Still creating... (3m40s elapsed)
null_resource.ChefBootstrap: Still creating... (3m50s elapsed)
null_resource.ChefBootstrap: Still creating... (4m0s elapsed)
null_resource.ChefBootstrap: Still creating... (4m10s elapsed)
null_resource.ChefBootstrap: Still creating... (4m20s elapsed)
null_resource.ChefBootstrap: Still creating... (4m30s elapsed)
null_resource.ChefBootstrap: Still creating... (4m40s elapsed)
null_resource.ChefBootstrap: Still creating... (4m50s elapsed)
null_resource.ChefBootstrap: Still creating... (5m0s elapsed)
null_resource.ChefBootstrap: Still creating... (5m10s elapsed)
null_resource.ChefBootstrap: Still creating... (5m20s elapsed)
null_resource.ChefBootstrap: Still creating... (5m30s elapsed)
null_resource.ChefBootstrap: Still creating... (5m40s elapsed)
null_resource.ChefBootstrap: Still creating... (5m50s elapsed)
null_resource.ChefBootstrap: Still creating... (6m0s elapsed)
null_resource.ChefBootstrap: Still creating... (6m10s elapsed)
null_resource.ChefBootstrap: Still creating... (6m20s elapsed)
null_resource.ChefBootstrap: Still creating... (6m30s elapsed)
null_resource.ChefBootstrap: Still creating... (6m40s elapsed)
null_resource.ChefBootstrap: Still creating... (6m50s elapsed)
null_resource.ChefBootstrap: Still creating... (7m0s elapsed)
null_resource.ChefBootstrap: Still creating... (7m10s elapsed)
null_resource.ChefBootstrap: Still creating... (7m20s elapsed)
null_resource.ChefBootstrap: Still creating... (7m30s elapsed)
null_resource.ChefBootstrap: Still creating... (7m40s elapsed)
null_resource.ChefBootstrap: Still creating... (7m50s elapsed)
null_resource.ChefBootstrap: Still creating... (8m0s elapsed)
null_resource.ChefBootstrap: Still creating... (8m10s elapsed)
null_resource.ChefBootstrap: Still creating... (8m20s elapsed)
null_resource.ChefBootstrap: Still creating... (8m30s elapsed)
null_resource.ChefBootstrap: Still creating... (8m40s elapsed)
null_resource.ChefBootstrap: Still creating... (8m50s elapsed)
null_resource.ChefBootstrap: Still creating... (9m0s elapsed)
null_resource.ChefBootstrap: Still creating... (9m10s elapsed)
null_resource.ChefBootstrap: Still creating... (9m20s elapsed)
```

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to fix this bug, is to work with the community and build a standalone chef provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
