### ISSUE TITLE
I am looking for terraform script to convert the existing cloud formation

### ISSUE THREAD

**Issue by mydearmuthu1978** [hashicorp/terraform#21389]
### Current Terraform Version

```
...
```

**Comment by apparentlymart** [comment]
Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

There is no official tool to automatically convert from CloudFormation to Terraform, but I believe there are some third-party tools that can convert a subset of CloudFormation features into equivalent Terraform features.

Another option is to use [`aws_cloudformation_stack`](https://www.terraform.io/docs/providers/aws/d/cloudformation_stack.html) to use Terraform to manage your existing CloudFormation stack, after importing it, and then optionally gradually migrate individual resources out of CloudFormation over time as needed.

The AWS provider is developed in [its own repository](https://github.com/terraform-providers/terraform-provider-aws), so that's a better place to open issues if you run into problems or have feature requests.

Thanks!
