### ISSUE TITLE
Interpolation characters don't appear in Resource Dependencies documentation

### ISSUE THREAD

**Issue by RetWolf** [hashicorp/terraform#21394]
While going through the AWS tutorial on learn.hashicorp.com, I ran into an issue with the documentation on [this page](https://learn.hashicorp.com/terraform/getting-started/dependencies). When assigning an Elastic IP, you are required to specify an EC2 instance ID using interpolation. The image of the code on the website looks like this:

![image](https://user-images.githubusercontent.com/28321156/58217866-aa152680-7cd2-11e9-8f6b-9f7f339fe520.png)

This code is invalid, as the instance ID needs to be inside a string, so we need to use interpolation to access the value inside a string.

The original documentation, found [here](https://github.com/hashicorp/terraform/blob/master/website/intro/getting-started/dependencies.html.md) properly contains the special characters to use interpolation. 

![image](https://user-images.githubusercontent.com/28321156/58217946-0d9f5400-7cd3-11e9-8d2b-517a0f54665d.png)

I'm not familiar with the way Hashicorp's documentation platform works, however if I had to take a guess I would think that the Markdown renderer is escaping the interpolation characters.

**Comment by ndobbs** [comment]
Terraform `0.12.0` was just released, the first example is for the new first class expressions. Since the`0.12.0` is releases as stable now, try upgrading and use the example from the docs, all should be well.

**Comment by mvaldes14** [comment]
Running 0.12 and the examples in the documentation do not work.

```
provider "aws" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region
}
```

variables.tfvars
```
access_key = "HEREMATE"
secret_key = "ORHEREMATE"
```

Getting
```
terraform plan                             

Error: Reference to undeclared input variable

  on example.tf line 2, in provider "aws":
   2:   access_key = "${var.access_key}"

An input variable with the name "access_key" has not been declared. This
variable can be declared with a variable "access_key" {} block.


Error: Reference to undeclared input variable

  on example.tf line 3, in provider "aws":
   3:   secret_key = "${var.secret_key}"

An input variable with the name "secret_key" has not been declared. This
variable can be declared with a variable "secret_key" {} block.
```

Also tried using "${}" and it won't work. What am i missing?

**Comment by apparentlymart** [comment]
Hi @mvaldes14,

I think the missing piece in what you are trying there is the very first snippet in the guide:

```hcl
variable "access_key" {}
variable "secret_key" {}
variable "region" {
  default = "us-east-1"
}
```

These blocks declare that these input variables are required to use this configuration. The `variables.tfvars` file you wrote then assigns values to some of those variables.

**Comment by mvaldes14** [comment]
Thanks @apparentlymart
So i need to have 2 files in order to use variables?

One file to declare them and another one with the actual values?

**Comment by apparentlymart** [comment]
There are [several ways to assign values to root module variables](https://www.terraform.io/docs/configuration/variables.html#assigning-values-to-root-module-variables). You always need a declaration, in the form of a `variable` block. You may also choose to put values in a file, or you can set them on the command line, or via environment variables, etc.

Think of it as being a bit like a function in a general-purpose programming language: in most languages you need to define the function's signature first -- what parameters it accepts and what results it produces -- and then each time you call the function you provide specific arguments to populate those parameters. The language compiler uses the signature to check that the function is written correctly, regardless of how (or whether) it is being called. That's a separate question from whether the function is being _called_ correctly, which is part of checking the _caller's_ code.

In Terraform's case, these parameters are called "Input Variables", but the principle is the same. Terraform provides a few different ways to set the ones on the root module because in that case the "caller" of the module is the `terraform apply` command typed at the shell prompt, rather than part of the Terraform configuration itself. If you use [child modules](https://www.terraform.io/docs/configuration/modules.html#calling-a-child-module) then the "function call" analogy is a little more apparent, because you write the values for those arguments directly in the caller's source code.

**Comment by RetWolf** [comment]
I've upgraded to Terraform 12 and that syntax is now working as expected. Really glad that the team added that feature, it feels like a big improvement over the interpolation syntax!

I am still running into an issue where the VS Code Terraform plugin doesn't recognize the new syntax, however that is completely understandable considering this was just released yesterday. I understand that plugin isn't maintained by Hashicorp, so I'll head over to that [repo](https://github.com/mauve/vscode-terraform)and see what progress is being made on that and potentially help out there.

Thanks for the quick responses everyone, I'm closing this issue as it was just an error on my end.

**Comment by mvaldes14** [comment]
Thank you @apparentlymart it makes sense, guess i picked a bad week to start learning terraform since most docs use interpolation and some don't and my package was old so i got super confused.
