### ISSUE TITLE
0.12upgrade adds unnecessary blank line at the end of every tf file

### ISSUE THREAD

**Issue by invidian** [hashicorp/terraform#21428]
### Terraform Version

```
Terraform v0.12.0
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

After upgrading, Terraform should produce files which are ready to commit.

### Actual Behavior

Terraform adds additional newline at the end of the file, which shouldn't be there:
```diff
 variable "kubernetes_version" {
-  type        = "string"
+  type        = string
   description = "Kubernetes version for RKE provider."
   default     = "v1.13.5-rancher1-2"
 }
+
diff --git a/03-hcloud.tf b/03-hcloud.tf
index 1376746..0f9d9f3 100644
--- a/03-hcloud.tf
+++ b/03-hcloud.tf
```

**Comment by apparentlymart** [comment]
Hi @invidian,

As a side-effect of rewriting configuration, the upgrade tool is inevitably forced to reformat the whitespace to a particular canonical style because whitespace information is not preserved by the old language parser. The formatting style it is using is that every line ends with a newline character, which I understand is different than what you had before where you would omit the newline character at the end of the final line in each file.

As always with formatting decisions, any decision the tool makes is going to seem "wrong" to one group or the other, because the decision is in the end an arbitrary one. Now that `terraform 0.12upgrade` has shipped with this particular decision in place, we don't plan to change it since that would cause the results to be different depending on what version you were on when you upgraded, and thus potentially different between different modules within the same organization if they happened to upgrade Terraform in the midst of upgrading their modules.

I'm sorry that the decision made by `terraform 0.12upgrade` disagrees with your preferences here. The Terraform parser has no strong preference about whether or not that newline is there, so you can feel free to ignore that particular change.

**Comment by sixcorners** [comment]
So when I use 0.12upgrade I get two newline characters at the end of every file.
I understand that every line can or should end with a newline character but then after that character there is another newline character.
Not really saying this format is wrong. Just clarifying... That's what is happening to everyone else's files too right?

**Comment by invidian** [comment]
Hi @apparentlymart, thanks for your lengthy explanation. I understand, that this might be something difficult to change and I don't insist on fixing that.

However, after playing a while with 0.12.0 I found few others formatting weirdnesses, especially when using EOF inside arrays. Sometimes the code ends up being misaligned a lot across several resources.I'll update the issue after the weekend with examples.

**Comment by geekofalltrades** [comment]
I have the same issue as @sixcorners. Before running 0.12upgrade, all of my .tf files already ended with a newline. After running it, all of my .tf files end with two newlines.

**Comment by apparentlymart** [comment]
The style this tool is following is to have a blank line after each top-level block. One edge of that rule is that there's a blank line at the end of the file too, because that blank line is after the final block in the file.

We're not planning to change this detail since (as noted before) layout decisions are arbitrary and you are free to ignore those proposed changes if you wish, though equally you can just keep them because Terraform will accept it either way.

If you find any other unexpected behaviors in `terraform 0.12upgrade`, please open a separate issue for each one.
