### ISSUE TITLE
tf 0.12.0: Call to function "matchkeys" failed: lists must be of the same type.

### ISSUE THREAD

**Issue by lorengordon** [hashicorp/terraform#21432]
### Terraform Version

```
> terraform012 -version
Terraform v0.12.0
```

### Terraform Configuration Files

```hcl
locals {
  foo = ["foo", "bar", "baz"]
  match = "${matchkeys(local.foo, local.foo, var.search)}"
}

output "match" {
  value = "${local.match}"
}

variable "search" {
  type = "list"
  default = ["foo"]
}
```

### Expected Behavior

```
> terraform012 apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

match = [
  "foo",
]
```

### Actual Behavior

```
> terraform012 apply

Error: Error in function call

  on main.tf line 3, in locals:
   3:   match = "${matchkeys(local.foo, local.foo, var.search)}"
    |----------------
    | local.foo is tuple with 3 elements

Call to function "matchkeys" failed: lists must be of the same type.
```

### Steps to Reproduce

1. `terraform apply`

### Additional Context

This appears to happen if the `searchset` is a variable. If I hardcode the searchset or use a local, then I get the "expected behavior".

**Comment by apparentlymart** [comment]
Thanks for reporting this, @lorengordon!

We are looking into this and understand where this bug is coming from: the function's type check is not handling the fact that during validation a variable of type "list" is presented as having an unknown element type because we don't know yet what the element type will be during actual evaluation. The function is incorrectly understanding "unknown" as being a distinct type from "string", whereas it should instead be deferring the check until more information is available.

A fix is on the way, but nonetheless you may wish to consider replacing this with a `for` expression, if your use-case is similar to one of [the examples on the `matchkeys` documentation page](https://www.terraform.io/docs/configuration/functions/matchkeys.html#examples). The `matchkeys` function was added to the language as a workaround for the lackluster support for list filtering in Terraform 0.11 and prior, but `for` expressions now offer general support for filtering and so will tend to be more readable than a `matchkeys` call in most cases.

A `for` expression could also be a workaround for this `matchkeys` bug in the mean time, while we're working on the fix.

**Comment by lorengordon** [comment]
I can confirm that 0.12.1 resolves the issue. Thanks!
