### ISSUE TITLE
0.12.0 -  force-unlock fails with strconv.ParseInt: parsing invalid syntax

### ISSUE THREAD

**Issue by invidian** [hashicorp/terraform#21447]
### Terraform Version

```
Terraform v0.12.0
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

```
Do you really want to force-unlock?
  Terraform will remove the lock on the remote state.
  This will allow local Terraform commands to modify this state, even though it
  may be still be in use. Only 'yes' will be accepted to confirm.

  Enter a value: yes

Failed to unlock state: strconv.ParseInt: parsing "gs://<mybucket>/default.tflock": invalid syntax
```
### Expected Behavior

State should be properly unlocked.

### Actual Behavior

Terraform fails to unlock remote state
### Additional Context

Content of the lock (with some parts redacted):
```
$ gsutil cat gs://<mybucket>/default.tflock
{"ID":"2cf38a93-4520-a254-a8d3-7a0a43556bbe","Operation":"OperationTypeApply","Info":"","Who":"root@localhost","Version":"0.12.0","Created":"2019-05-24T22:01:07.381737931Z","Path":"gs://<mybucket>/default.tflock"}
```

Terraform configuration:
```
terraform {
  required_version = "= 0.12.0"

  backend "gcs" {
    bucket = "<mybucket>"
    prefix = "<prefix>"

    # Generate with 'openssl rand -base64 32'
    encryption_key = "<encryptionkey>"
    credentials    = "<path to JSON file"
  }
}
```

**Comment by invidian** [comment]
Ah, by bad, I should pass ID of the lock to `force-unlock`, not the path to the lock file :man_facepalming: 

I think error message could definitely be improved though.

**Comment by apparentlymart** [comment]
Thanks for following up, @invidian! Indeed, that is not a very helpful error message, so we'll leave this issue open to represent the task of improving it.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being on more workflow-centric v0.12.0 issues, but we'd be happy to review a pull request if someone has the time and motivation to implement it.

Ideally it would be nice to switch this over to using new-style error diagnostic messages rather than the legacy error style, but it looks like that codepath isn't ready to use the new diagnostics system yet, so a more actionable error message string in the place of that one would still be a nice improvement in the short term.

**Comment by invidian** [comment]
I'll try to post some quick patch for that, since it should be just a one liner for now. New diagnostic system can be done in separated issue I guess. Thanks for giving some insights about it BTW!
