### ISSUE TITLE
TF 0.12 - gitlab module checkout fails using git::ssh

### ISSUE THREAD

**Issue by ntmggr** [hashicorp/terraform#21440]
### Terraform Version

```
Terraform v0.12.0

```

### Terraform Configuration Files

```
provider "azurerm" {
  version = "~> 1.28.0"
}

module "rg" {
  source         = "git::ssh://git@gitlab.XXXXXXXXXXXXXXXXX/tf-modules.git?ref=master//rg"
  location       = "northeurope"
  resource_group = "mytest"
}
```

### Debug Output

https://gist.github.com/ntmggr/f0145854433eab44b987f373df12ae9e
### Expected Behavior

It should be able to pull the module as terraform `v0.11.14` does

### Actual Behavior

Fails to pull the module through ssh

**Comment by apparentlymart** [comment]
Hi @ntmggr! Thanks for reporting this.

The error message seems to be suggesting that Terraform is interpreting `//rg` as part of the `ref=` argument, which is the behavior I would've expected. I'm surprised to hear this was working on Terraform 0.11.

Could you give it a try with the sub-path portion moved into the path of the URL, rather than the query string? Something like this:

```hcl
  source         = "git::ssh://git@gitlab.XXXXXXXXXXXXXXXXX/tf-modules.git//rg?ref=master"
```

(I'm assuming here that your goal was to use the `rg` subdirectory inside the master branch of the repository, rather than to use a branch called "master//rg".)

**Comment by ntmggr** [comment]
@apparentlymart thanks for coming back. I have removed some stuff in purpose so my bad for not copy pasting the exact git ssh which was working in 0.11.
```git::ssh://git@gitlab.XXXXXXXXXXXXXXXXX/tf-modules.git?ref=master//azure/rg```

**Comment by ntmggr** [comment]
So adding the `?ref=master` at the end as you suggested works but what i typed above used to work in previous versions (for any branch really).

**Comment by apparentlymart** [comment]
Thanks for checking, @ntmggr!

Terraform delegates to a separate codebase called `go-getter` to handle these strings, so I assume some details have subtly changed between the version v0.11 was depending on and the version v0.12 is depending on. I'm sorry we didn't catch that and deal with it in the automatic upgrade tool or upgrade guide.

The new behavior is correct though, because query string arguments can contain slashes and the correct place for the sub-path is in the path portion of the URL. I verified that we have documented it this way in [the relevant documentation](https://www.terraform.io/docs/modules/sources.html#modules-in-package-sub-directories), so I don't think we will take any action based on this issue, but I'm going to leave it open for the moment (while we work through some other 0.12.0 bug reports) in case someone else encounters the same problem, so it'll be more visible in the "similar issues" section in the GitHub issues UI. If this turns out to be a common problem then we'll see about adding a note about it to the upgrade guide.

**Comment by apparentlymart** [comment]
Hi again @ntmggr!

I'm going to close this out now, since it's been long enough now that this issue is unlikely to rise to the top of the "related issues" in the GitHub UI anyway. I have seen at least one other question about this, but it was asked in a different forum than GitHub. Fortunately it seems that not too many people had put the sub-path portion in the query string. :disappointed_relieved: 

Thanks again for reporting this!
