### ISSUE TITLE
Feature Request: Set block arguments using a map

### ISSUE THREAD

**Issue by kinghuang** [hashicorp/terraform#21458]
### Current Terraform Version

```
Terraform v0.12.0
```

### Use-cases

I would like to be able to set block arguments from a map of key-values. For example, suppose I have a map containing four argument values for a `aws_vpc` data source. These values might be loaded from an external source. To pass them to the block, I have to unpack and assign the four values manually.

```hcl
locals {
  vpc_data = {
    id         = "vpc-12345678"
    cidr_block = "10.0.0.0/16"
    # default    = false
    # state      = "available"
  }

  vpc_args = ["id", "cidr_block", "default", "state"]
}

data "aws_vpc" "selected" {
  id         = lookup(local.vpc_data, "id", null)
  cidr_block = lookup(local.vpc_data, "cidr_block", null)
  default    = lookup(local.vpc_data, "default", null)
  state      = lookup(local.vpc_data, "state", null)
}

```

This becomes very repetitive for a large number of arguments.

### Attempted Solutions

Terraform 0.12 introduces [`for` expressions](https://www.terraform.io/docs/configuration/expressions.html#for-expressions) and [expanding function arguments](https://www.terraform.io/docs/configuration/expressions.html#expanding-function-arguments). I tried to use them to set arguments.

```hcl
data "aws_vpc" "selected" {
  for arg in local.vpc_args: arg => lookup(local.vpc_data, arg, null)
}
```

<pre>
Error: Invalid block definition

  on config.tf line 101, in data "aws_vpc" "selected":
 101:   for attr in local.attrs: attr => lookup(local.cc_aws_vpc, attr, null)

Either a quoted string block label or an opening brace ("{") is expected here.
</pre>

```hcl
data "aws_vpc" "selected" {
  { for arg in local.vpc_args: arg => lookup(local.vpc_data, arg, null) }...
}
```

<pre>
Error: Argument or block definition required

  on config.tf line 101, in data "aws_vpc" "selected":
 101:   { for attr in local.attrs: attr => lookup(local.cc_aws_vpc, attr, null) }...

An argument or block definition is required here.
</pre>

### Proposal

There should be a way to set block arguments from a map. Perhaps a special argument name like `*` can be used to accept a map of arguments.

```hcl
data "aws_vpc" "selected" {
  * = { for arg in local.vpc_args: arg => lookup(local.vpc_data, arg, null) }
}
```

For arguments that are defined in both the map and directly in the block, the latter should take precedence. So, the following block:

```hcl
data "aws_vpc" "selected" {
  *  = { for arg in local.vpc_args: arg => lookup(local.vpc_data, arg, null) }
  id = "vpc-abcdefgh"
}
```

would effectively be equal to:

```hcl
data "aws_vpc" "selected" {
  # id         = lookup(local.vpc_data, "id", null)
  cidr_block = lookup(local.vpc_data, "cidr_block", null)
  default    = lookup(local.vpc_data, "default", null)
  state      = lookup(local.vpc_data, "state", null)
  id         = "vpc-abcdefgh"
}
```

**Comment by apparentlymart** [comment]
Hi @kinghuang! Thanks for starting this discussion.

The requirement to explicitly define each argument inside a block was an intentional language design decision, following our design principle of prioritizing the reader over the writer. While I can see that it feels laborious to write out each of these arguments separately, doing so creates a configuration that more explicitly and completely shows which attributes are set and how they are set, avoiding the need for the reader to work backwards and investigate exactly which keys are set in one or more maps and what they are set to.

This requirement also serves a secondary purpose: Terraform's validation pass checks that all of the required arguments are set and that no additional arguments are set, and to do that thoroughly requires the set of arguments to be statically-defined, not dynamically set by a value that might not be known until apply time. This also ensures that the documented interface to a module (its defined variables and their types) cannot be implicitly changed by a provider upgrade: instead, if a provider makes a breaking change then it will be flagged immediately as a problem in the module itself, rather than inadvertently passing that breaking change onto the module's callers.

---

I would generally not recommend this sort of generic "wrapper module": if your goal is to allow arbitrary use of any property of a particular resource type, it's better to just let the caller instantiate the resource itself and pass the relevant aspects of that result into your module, per the principles of [module composition](https://www.terraform.io/docs/modules/composition.html). A module should introduce a higher-level abstraction, not just pass through directly the features of some existing abstractiion/feature.

In your case it looks like your module needs access to a pre-existing VPC, and you're trying to allow the caller to use arbitrary filters to select it. Instead, in module composition style we would have the caller use its own means to fetch the VPC id -- which could be by the `aws_vpc` data source, or it could be by being the direct manager of an `aws_vpc` managed resource, or it could come from a `terraform_remote_state`, etc:

```hcl
data "aws_vpc" "selected" {
  id = "vpc-abc123"
}

module "needs_vpc" {
  source = "./modules/needs-vpc"

  vpc = data.aws_vpc.selected
}
```

Inside this hypothetical "needs vpc" module, we'd use a type constraint to request the relevant attributes of the VPC that we need:

```hcl
variable "vpc" {
  type = object({
    id         = string
    cidr_block = string
  })
}
```

The Terraform language type system uses structural typing to achieve loose coupling here: this type constraint just says "must be an object with `id` and `cidr_block` attributes", without imposing any restrictions on how the caller obtained such an object. The caller could also choose to construct that object directly, if they know the information some other way:

```hcl
module "needs_vpc" {
  source = "./modules/needs-vpc"

  vpc = {
    id         = data.terraform_remote_state.example.outputs.vpc_id
    cidr_block = module.network.base_cidr_block
  }
}
```

The intent of the module composition style is to have modules focus only on the objects directly related to the abstraction they are creating, and to let the caller be responsible for obtaining and supplying any dependencies of that abstraction. This will lead to modules as small building-blocks with small interfaces, that can be used together to produce a system.

You can see in [the module composition guide](https://www.terraform.io/docs/modules/composition.html) that passing EC2 VPC objects into another module was the motivating use-case there too. I expect this will be a common situation for AWS users, given that many different services can make use of a VPC. Over time it may be useful to have a de-facto standard object structure for passing a VPC and its subnets to a module, similar to the recordset convention in the experimental [Terraform DNS project](https://terraformdns.github.io/about/) (a side-project of mine), to make it easier to plug a full VPC network cnofiguration into a module that needs it:

```hcl
module "network" {
  source = "./modules/aws-regional-network"

  base_cidr_block = "10.1.0.0/12"
  max_subnets = 8
  subnets = [
    {
      availability_zone_suffix = "a",
    },
    {
      availability_zone_suffix = "b",
    },
    {
      availability_zone_suffix = "c",
    },
  ]
}

module "consul_cluster" {
  source = "./modules/aws-consul-cluster"

  aws_network = module.network
}
```

For now there is no such general conventions, but no reason individual organizations can't establish such conventions for their own modules where they are useful.

---

With all of this said, I think we will not plan on introducing additional features for dynamically populating blocks, both because it runs counter to some intentional language design goals and because the module composition pattern can achieve a similar result without such tight a coupling between modules.

**Comment by kinghuang** [comment]
I actually hadn't considered using remote states as a way to pass information. That actually sounds like a really good idea for some use cases. Thanks for the detailed explanation!
