### ISSUE TITLE
terraform 0.12upgrade support .tf.json files

### ISSUE THREAD

**Issue by kapilt** [hashicorp/terraform#21456]
version: terraform 0.12.0

issue: running ` 0.12upgrade` does modify or affect .tf.json files.

proposal: tf.json suffixed files should also be upgraded

**Comment by apparentlymart** [comment]
Hi @kapilt,

The upgrade tool intentionally does not work with `.tf.json` files, because these are recommended for use only when the file is being generated by some other software, and so it is that other software which must be altered in that case.

Fortunately, many of the upgrade rules in `terraform 0.12upgrade` apply only to the native syntax anyway. For example, JSON syntax cannot support first-class expressions, so these must remain as string interpolations even in 0.12.

There are a few expression-related changes that may need some adjustment after upgrading, but `terraform validate` should be able to identify and report on these so that you can decide what to do for them. 

Although indeed it would be nice if the upgrade tool could automatically upgrade JSON files, it would essentially be an entirely separate set of upgrade rules and so I think the opportunity cost of implementing it would not outweigh its impact, because (as noted above) JSON syntax is for machine-generated configuration only, and Terraform would not be able to automatically update the program that generates the JSON.

Therefore we don't plan to offer this feature. I expect that for some unusual use-cases this will be more inconvenient due to extensive use of JSON, and I'm sorry for that, but we must prioritize other work to fix bugs reported in 0.12.0 and then to implement the next set of features.

Thank you for raising this!
