### ISSUE TITLE
state list command ignore -state flag

### ISSUE THREAD

**Issue by ayashjorden** [hashicorp/terraform#21457]
### Terraform Version
Terraform v0.11.13
+ provider.archive v1.2.2
+ provider.aws v2.11.0
+ provider.template v2.1.2

Upgrade to 0.12.0 is in our pipeline, can't use it now.

### Terraform Configuration Files
No config files needed as I'm interacting with TF state subcommand

### Expected Behavior
```
terraform state list -state=/path/to/local/state.tfstate
```
Should list the resources in the specified state file.

### Actual Behavior
Lists **all** the resources from the original tfstate file in the s3 bucket, not the local one the I specified using the `-state` flag.

### Steps to Reproduce
1. Run TF init and configure an existing s3 bucket that holds a `tfstate` files.
2. Select certain `workspace`
3. Pull the tfstate into a local file
4. Move some module into another tfstate file - `terraform_0.11.13 state mv -state=/path/to/local/state.tfstate -state-out /path/to/local/another-state.tfstate module.cloudtrail-us-west-2 module.cloudtrail-us-west-2`
4. Run `terraform state list -state=/path/to/local/state.tfstate`

### References
I've searched for similar issues, found only #15359

Thank you,
Yarden

**Comment by apparentlymart** [comment]
Hi @ayashjorden,

The documentation for `-state` mentions that is not available when remote state is in use, so it seems like it is behaving as documented here. With that said, we'll take this issue as a feature request for a way to select a local file _even when_ remote state is in use, effectively overriding the backend selection and forcing the local backend to be used.

I don't think this will be possible in the short term because the current design has that `-state` argument consumed directly by the local backend, and so no other backend knows to look for it. It will require some refactoring to make the backend initialization code aware of the option and switch to a different backend, and I expect there will be some other consequences because Terraform generally does not expect the backend configuration to change except by running `terraform init`.

With that said, I'm going to mark this as a feature request but I suspect we won't be able to prioritize it for a while, at least until next time we're doing other work in the backend-related subsystems of Terraform.

**Comment by ayashjorden** [comment]
Thank you @apparentlymart for clarifying
