### ISSUE TITLE
0.12.0 Error: Terraform settings not allow "required_providers" 

### ISSUE THREAD

**Issue by jcmaasb** [hashicorp/terraform#21467]
### Terraform Version

```
Terraform v0.12.0
provider.azurerm v1.29.0
```

### Terraform Configuration Files

```hcl
# Configure the Azure Provider
provider "azurerm" {
  version         = "= 1.29.0"
  subscription_id = var.azure_conn["subscription_id"]
  client_id       = var.azure_conn["client_id"]
  client_secret   = var.azure_conn["client_secret"]
  tenant_id       = var.azure_conn["tenant_id"]
}

terraform {
  required_version = ">= 0.11.13"

   required_providers {
     local = "= 1.2.2"
   }

  backend "azurerm" {
    key = "test.terraform.tfstate"
  }
}
....
```

### Crash Output
```hcl
Error: Unrecognized block type

  on main.tf line 13, in terraform:
  13:   required_providers {

Blocks of type "required_providers" are not expected in terraform.
```

### Expected Behavior

Donwload the required providers

### Steps to Reproduce

`terraform 0.12upgrade`

### Additional Context

With previous version of terraform, it's work fine
In the documentation not indicated that this configuration is wrong

### References

https://www.terraform.io/docs/configuration/terraform.html

"Specifying Required Provider Versions"  section

**Comment by jcmaasb** [comment]
Hi @apparentlymart 
Today I am trying this issue again and not get any error.
I don't know what happens, but I guess it's a human error. You can close this issue.

Thanks!!

**Comment by jcmaasb** [comment]
Hi @apparentlymart
I have reviewed this incidence, the error occurs only when using **terraform 0.12upgrade**

**Comment by apparentlymart** [comment]
Thanks for that additional context, @jcmaasb!

I'm a little confused by that since `required_providers` didn't exist in Terraform 0.11 and so it would be unexpected for it to already be present when running `terraform 0.11upgrade`. Perhaps the upgrade rules are not accounting for it for that reason, and are thus upgrading it incorrectly. The upgrade tool is expecting to receive an unmodified configuration that was working on Terraform 0.11, so it may not behave correctly if it is given a configuration that has already been partially upgraded.

With that said, we may be able to add an additional rule for this specific case. If that's simple to do then maybe we'll do it just to avoid it creating an incorrect result in this situation, even though it isn't recommended.

**Comment by jcmaasb** [comment]
Hello @apparentlymart
You're right, I recently started using this configuration with Terraform 0.11, _I did not see that it's only for Teerraform 0.12 (mistake ;)

The key, does not generate errors with Terraform 0.11 and downloads the providers, but ... (deepening) always downloads the latest version of the providers whitout match the constraints specified.

Conclusion, you can close this issue because it is not a problem of Terrafom 0.12

Thanks for your time!
