### ISSUE TITLE
Feature Request: Function to get type of value

### ISSUE THREAD

**Issue by kinghuang** [hashicorp/terraform#21460]
### Current Terraform Version

```
Terraform v0.12.0
```

### Use-cases

When I'm loading JSON/YAML data from external sources, I sometimes need to be able to inspect if certain data I've loaded is a string, list, or map.

### Attempted Solutions

I'm encoding data to JSON and checking the first character as a way to determine if a value is a string, list, or map. For example, this `for` expression picks out map values from a list.

```hcl
locals {
  bag_of_values = [
    "a string",
    [
      "item-1",
      "item-2"
    ],
    {
      key = "value"
    }
  ]

  map_values = [
    for v in local.bag_of_values:
      v if substr(jsonencode(v), 0, 1) == "{"
  ]
}
```

```sh
# terraform console
> local.map_values
[
  {
    "key" = "value"
  },
]
```

### Proposal

There should a way to get or check the type of a value. For example, there could be a `typeof`  operator that works with the same [type constraints](https://www.terraform.io/docs/configuration/variables.html#type-constraints) used for input variables.

```hcl
locals {
  map_values = [
    for v in local.bag_of_values:
      v if v typeof map(any)
  ]
}
```

Alternatively, `typeof()` could be a function that returns the basic type of a value as a string.

```hcl
locals {
  map_values = [
    for v in local.bag_of_values:
      v if typeof(v) == "map"
  ]
}
```

**Comment by marco-m-pix4d** [comment]
See also: #24761

**Comment by sworisbreathing** [comment]
This would also be really handy when troubleshooting for-each/expressions that operate on complex types during development of a terraform template/module. Right now I'm trying to write something that uses nested dynamic blocks on `list(map(list(string)))` types and having trouble getting the types right ("I get a syntax error when I use `each` here, but `each.value` is okay... but that doesn't seem right").

If I could just change one of those to a `typeof(each)` and then run a terraform plan I'd be able to figure out what I'm doing wrong much faster than my current approach of throwing spaghetti at the wall and seeing what sticks.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

At the time this issue was originally filed, we didn't really have any good ways to make decisions based on the types of values. 

Since the Terraform language doesn't treat types as a kind of value (i.e. there isn't a "type type" with which to use types directly in calculations), it isn't really viable to define a function which returns a type in a form that would actually be useful for further computation.

However, we do now have two language features which you can in principle use together to make decisions based on dynamic type information:
* The type conversion functions like [`tostring`](https://www.terraform.io/language/functions/tostring) and [`tobool`](https://www.terraform.io/language/functions/tobool) allow explicit conversion to a particular type, raising an error if such a conversion isn't possible.
* The special [`can`](https://www.terraform.io/language/functions/can) function allows treating the success or failure of some other expression as a boolean value rather than as an error.
* The special [`try`](https://www.terraform.io/language/functions/try) function allows trying to evaluate an expression and using a replacement value if evaluation fails.

Taken together, these features allow making decisions based on types in a way that takes into account Terraform's typical type conversion behaviors. Instead of programming with types directly, we can instead program with Terraform's type conversion behaviors.

Taking the example in the original issue writeup, one way to write that with these features would be as follows:

```hcl
locals {
  map_values = [
    for v in local.bag_of_values: v
    if can(tomap(v))
  ]
}
```

Another pattern I've seen folks use is for consuming formats where a value is logically a list of strings but as a convenience it's allowed to use a single string to represent a 1-element list:

```hcl
locals {
  items = tolist(try([tostring(local.example)], local.example))
}
```

The above expression first tries to convert `local.example` to a string, returning that string inside a 1-element tuple if possible, and otherwise it just returns `local.example` directly. In both cases `tolist` turns the result into a list, so that logic elsewhere in the module doesn't need to worry about dynamically deciding whether it's a list or not.

In recognition of these subsequent additions to the language, I'm going to close this issue. Thanks for sending this feature request, and sorry we didn't notice it when we were closing out the language features I mentioned above.
