### ISSUE TITLE
Possible Regression -> Error: Reference to "count" in non-counted context 

### ISSUE THREAD

**Issue by cappetta** [hashicorp/terraform#21477]
I'm seeing this error on terraform v0.12.0 in my circleci env.  When I revert the terraform container image back to v0.11.4 it passes as expected.  I suspect there is a regression issue.  Also note curl had to be added into the container [on line 40](https://github.com/cappetta/CyberRange/pull/22/files#diff-1d37e48f9ceff6d8030570cd36286a61)

Output on [build failure 287](https://circleci.com/gh/cappetta/CyberRange/287)
> Error: Reference to "count" in non-counted context
>
> on ../../modules/infrastructure/modules/secdevops/malware.tf line 53, in resource 
> "aws_instance" "cuckoo-host-ubuntu":
>  53:   subnet_id = "${element(local.malware_subnet_ids, count.index)}"
>
> The "count" object can be used only in "resource" and "data" blocks, and only
> when the "count" argument is set.

**Comment by jbardin** [comment]
Hi @cappetta,

Can you confirm that `count.index` is set on the resource that is causing the error? A complete sample config may help track down the the issue. It also appears that you may have missed running the `0.12upgrade` tool on this particular config, which should point out this type of error. Double check that you've gone through the [upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html) when switching to 0.12.

**Comment by cappetta** [comment]
Thanks for highlighting the upgrade tool. I'll perform that check/analysis and review the release notes a bit closer.  Hoping to circleback over the weekend.  RE: sample config - [here is a link to the count.index reference](https://github.com/secdevops-cuse/CyberRange/blob/master/terraform/modules/infrastructure/modules/secdevops/malware.tf)

**Comment by apparentlymart** [comment]
Hi @cappetta!

The resource indicated in the error doesn't seem to have `count` set in your config, so the error you got here is correct. In Terraform 0.11 `count.index` would've always been zero here, but we made it into an explicit error in 0.12 to help users see when they have made a (common, it turns out) error if forgetting to set `count` and then inadvertently connecting all instances of a downstream resource to only the first instance of upstream.

The fix here would be to replace `count.index` with `0` if that is the behavior you were expecting, or to set the `count` meta-argument if not. I think in this case the upgrade tool may not be able to totally fix this, but I would still recommend running it first and using it as a baseline for subsequent updates.

**Comment by cappetta** [comment]
Thanks Martin.  Great eyes - I upgraded multiple installs, performed the 0.12upgrade chk, confirmed CircleCI was green, & all is looking good. Error was on my end, nice to see the alert of the issue & appreciate the quick assist.
