### ISSUE TITLE
download state file from terraform enterprise and amend

### ISSUE THREAD

**Issue by im-dofoborh** [hashicorp/terraform#21499]
### Terraform Version

```
0.11.13
```
Need some direction. I have a corrupt state file due to the original resources being deleted manually from third part service. 

Want to download state file from terraform enterprise, amend and then push back to terraform enterprise.  `aware it is not recommended - can't afford to delete entire infrastructure!`

Simply want to correct or taint resource so I can carry on with development for now. Any help appreciated.

**Comment by apparentlymart** [comment]
Hi @im-dofoborh!

Manual changes can be made using the following workflow:

* `terraform state pull >temp.tfstate`
* edit `temp.tfstate` carefully as needed
* increment the integer in the top-level `serial` property so Terraform Cloud can see that the change was intentional
* `terraform state push temp.tfstate`

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers. If you are a Terraform Enterprise customer then you can also reach out to the Terraform Enterprise customer support team.

**Comment by im-dofoborh** [comment]
Thank you for that. 
Acknowledged. Will use this only for issues.
