### ISSUE TITLE
interpolation of files

### ISSUE THREAD

**Issue by payneio** [hashicorp/terraform#215]
I believe it would be useful to extend the file(..) function to allow for variable replacement. This would allow, for example, passing in terraform variables into a cloud-config.yaml.

Perhaps as simple as opening up the interpolation function:
user_data = ${interpolate(file("cloud-config.yaml"))}

Or maybe just an optional attribute on the file function: 
user_data = ${file("cloud-config.yaml", true)}

**Comment by chipi** [comment]
@MerlinDMC I am using latest TF build (v0.3.6) and seems that heredoc within for file provisioner is not supported since I get error on inline_script attribute and syntax error when applying heredoc to source attribute. What I am doing is specifying a file provisioner within aws_instance resource to copy over and interpolate a file. 

```
resource "aws_instance" "name" {
  bla
  bla

  provisioner "file" {
        inline_script = true
        source = <<EOF
bla
bla
        EOF
        destination = "/etc/my.conf"
    }
}
```

Am I missing something on how to use heredoc?

**Comment by MerlinDMC** [comment]
@chipi I did branch terraform and added functionality for that one :/

**Comment by mwitkow-io** [comment]
The problem with heredocs is that if you want to use the same piece of inlined configuration in multiple places, you probable want to have them in a separate file and source that in. But then, you can't use parameters in them and you end up with code duplicaiton.

There's another Feature Request: gsub #1029, and it may allow to do something like:

```${gsub("$MY_VAR", ${var.my}, file("../")}```

Yes, it would require you to specify the parameters to be substituted manually manually but it would be explicit for the user that there's something fishy happening.

**Comment by mwitkow-io** [comment]
Or maybe even piggy-backing on the `gsub` implementation, can we have an optional parameter to `file` that would take interpolations map?

e.g.:
```${file("../myfile", {"variable_name": "${var.somevar}"})}```

**Comment by mitchellh** [comment]
@mwitkow-io That is the plan, we just don't support that syntax yet but that is what we'd like to do.

**Comment by tayzlor** [comment]
:+1:

**Comment by apparentlymart** [comment]
Rather than this being a simple function, could it instead be a resource so that it can participate normally in the dependency graph?

```
resource "string_from_template" "example" {
    template_file = "template.txt"
    vars {
        ip_addr = "${aws_instance.example.public_ip}"
    }
}
```

...then elsewhere in the config, use ``${string_from_template.example.rendered}`` to get the result of rendering the template.

Unless I'm missing something, this allows both the filename and the variables to be dynamic by re-using the existing dependency management mechanisms, at the expense of a more verbose (but arguably more readable) usage syntax.

**Comment by josharian** [comment]
@apparentlymart I started implementing your suggestion and have a basic working version. (It is missing a few things, such as the lookup function, but the basics seem to work.)

Having done so, I'm not sure it is the right approach. I'm new to terraform, though, so perhaps I'm doing it wrong.

The main problem I see with having templates be resources is that there is no way that I can see to sanity check the template at plan time. This is because interpolation might not be done, so things like the template filename might not be available. As a result, any errors in the template (syntax errors, missing keys, etc.) won't show up until execution time, which is pretty unfortunate.

One could get around this by having to declare all the templates and variables in

**Comment by apparentlymart** [comment]
@josharian... That is fair. Seems true of many resources, though... If I create an AWS VPC and use it to create a subnet then the subnet id can't be checked until apply time, for example.

Seems like the plan tells you what terraform will attempt, not what will succeed.

With that said, I am pretty new to this tool to so I wouldn't take my opinion too seriously. I'd love to hear from a hashicorp staffer on this.

**Comment by josharian** [comment]
>  I'd love to hear from a hashicorp staffer on this.

Me too. I'd like to do the work to get this issue fixed, but I want to make sure I go down the right path. @mitchellh, care to weigh in about your preferred direction? Thanks!

**Comment by mitchellh** [comment]
@josharian You're right, but the template can also fail at runtime. The partial state nature of Terraform will allow this to happen pretty gracefully. I think its the best we can do.

**Comment by apparentlymart** [comment]
In case anyone finds this years later: I've now gone from being "pretty new to this tool" to working on is as my day job 🙃 and also in Terraform 0.12 we finally had all the necessary parts in place to make this be a function like originally proposed: [`templatefile`](https://www.terraform.io/docs/configuration/functions/templatefile.html).

The `template_file` data source is still there, but is no longer the primary way to render templates from separate files.
