### ISSUE TITLE
Having issue in attaching a policy to role

### ISSUE THREAD

**Issue by abhinaya04** [hashicorp/terraform#21524]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-google)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

```hcl
resource "aws_iam_role_policy_attachment" "sto-readonly-role-policy-attach" {
  role       = "${aws_iam_role.sto-test-role.name}"
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "aws_iam_role" "sto-test-role" {
  count = "${var.enablelogging == "yes" ? 1 : 0}"
  path = "/"
  name = "awsconfigiamrole"
  assume_role_policy = <<EOF
{
  "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Service": [ "config.amazonaws.com" ] },
              "Action": [ "sts:AssumeRole" ]
             }
          ]
  }
EOF
}
```

Getting the below error : 

```
 on C:\LEARNINGS\TERRAFROM\Test03\instance.tf line 9, in resource "aws_iam_role_policy_attachment" "sto-readonly-role-po
licy-attach":
  9:   role       = "${aws_iam_role.sto-test-role.name}"
   |----------------
   | aws_iam_role.sto-test-role is tuple with 1 element

his value does not have any attributes.
```

**Comment by apparentlymart** [comment]
Hi @abhinaya04,

Because `resource "aws_iam_role" "sto-test-role"` has the `count` meta-argument set, `aws_iam_role.sto-test-role` is a collection of instances of that resource rather than a single object. Therefore you need to specify an instance index when accessing it.

Your policy attachment resource must also be created only if logging is enabled -- otherwise it will have no role to attach -- so you'll need to put a similar conditional `count` in there, and then you can use `count.index` as the index like this:

```hcl
variable "enable_logging" {
  type    = bool
  default = false
}

resource "aws_iam_role_policy_attachment" "sto_readonly_role_policy_attach" {
  count = var.enable_logging ? 1 : 0

  role       = aws_iam_role.sto_test_role[count.index].name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "aws_iam_role" "sto_test_role" {
  count = var.enable_logging ? 1 : 0

  path = "/"
  name = "awsconfigiamrole"
  assume_role_policy = <<EOF
{
  "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Service": [ "config.amazonaws.com" ] },
              "Action": [ "sts:AssumeRole" ]
             }
          ]
  }
EOF
}
```

I've also renamed your resources to use names containing underscores rather than dashes, since that is the proper Terraform naming style. (Identifiers with dashes are supported only for when a remote system has a naming scheme involving dashes.)

Finally, I wrote a declaration of the `enable_logging` variable that is marked as a boolean, so you can set it to `true` rather than `"yes"` and avoid the need for that extra comparison in each of the `count` expressions.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers. If you have any follow-up questions, please use one of the community forums instead. Thanks!

**Comment by abhinaya04** [comment]
Thanks Team for the solution. It worked perfect
RegardsAbhinaya
    On Saturday, 1 June 2019, 22:48:25 GMT+5:30, Martin Atkins <notifications@github.com> wrote:  
 
 
Hi @abhinaya04,

Because resource "aws_iam_role" "sto-test-role" has the count meta-argument set, aws_iam_role.sto-test-role is a collection of instances of that resource rather than a single object. Therefore you need to specify an instance index when accessing it.

Your policy attachment resource must also be created only if logging is enabled -- otherwise it will have no role to attach -- so you'll need to put a similar conditional count in there, and then you can use count.index as the index like this:
variable "enable_logging" {
  type    = bool
  default = false
}

resource "aws_iam_role_policy_attachment" "sto_readonly_role_policy_attach" {
  count = var.enable_logging ? 1 : 0

  role       = aws_iam_role.sto_test_role[count.index].name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "aws_iam_role" "sto_test_role" {
  count = var.enable_logging ? 1 : 0

  path = "/"
  name = "awsconfigiamrole"
  assume_role_policy = <<EOF
{
  "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Service": [ "config.amazonaws.com" ] },
              "Action": [ "sts:AssumeRole" ]
             }
          ]
  }
EOF
}
I've also renamed your resources to use names containing underscores rather than dashes, since that is the proper Terraform naming style. (Identifiers with dashes are supported only for when a remote system has a naming scheme involving dashes.)

Finally, I wrote a declaration of the enable_logging variable that is marked as a boolean, so you can set it to true rather than "yes" and avoid the need for that extra comparison in each of the count expressions.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the community forums where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers. If you have any follow-up questions, please use one of the community forums instead. Thanks!
