### ISSUE TITLE
Not able to get the string from list from external json data using jq (OCI)

### ISSUE THREAD

**Issue by RanganathNangineni** [hashicorp/terraform#21532]
Hi,
I have the below JSON data and I am not able to get the individual string from list of arrays.
Not sure whether my syntax is correct or not.

## create_tags62716.json
```json
{
    "tenancy_ocid": "xyz", 
    "compartment_name": "XYZ-CONTAINER", 
    "tag_namespace_id": "XYZNMMMLJLJJLJLJLJ", 
    "job_execid": "62960", 
    "tag_names": [
        "tagname1", 
        "tagname2", 
        "tagname3"
    ], 
    "compartment_ocid": "xyzabc, 
    "region": "iad", 
    "namespace": "default_NameSpace", 
    "tag_description": [
        "desc1", 
        "desc2", 
        "desc3"
    ], 
    "json_dir": "/home/iam-tags", 
    "tenancy_name": "sample1", 
    "job_name": "Tags :  create tags"
}
```

The below is the Terraform template also.

```hcl
### external json data source
data "external" "create_tags62716" {
  program = ["jq", ".", "${path.module}/create_tags62716.json"]
  query   = {}
}

### create new tags
######SAMPLE #####3
resource "oci_identity_tag" "create_tags62716" {
    count = 3
    name = "${jsonencode(element(data.external.create_tags62716.result.tag_names, count.index))}"
    description = "${jsonencode(element(data.external.create_tags62716.result.tag_description, count.index))}"
    tag_namespace_id = "DEFAULT_NAMESPACE_ID"
    is_retired = false
 lifecycle {
    prevent_destroy = true
  }

}
```

## Error

```
* module.iam-tags.data.external.create_tags62716: 1 error(s) occurred:
--
 
* module.iam-tags.data.external.create_tags62716: data.external.create_tags62716: command "jq" produced invalid JSON: json: cannot unmarshal array into Go value of type string
```

**Comment by apparentlymart** [comment]
Hi @RanganathNangineni,

The `external` data source, as described in [its documentation](https://www.terraform.io/docs/providers/external/data_source.html#external-program-protocol), only supports JSON string values. It does not support any other type, and it is not intended as a generic way to read JSON data but rather as a way to create Terraform-specific integrations with external software.

It seems like you are using this just to decode a specific file from disk, without doing any processing on it. If that is true, then I would recommend [upgrading to Terraform 0.12](https://www.terraform.io/upgrade-guides/0-12.html) and then using the new [`jsondecode`](https://www.terraform.io/docs/configuration/functions/jsondecode.html) built-in function instead:

```hcl
locals {
  create_tags = jsondecode(file("${path.module}/create_tags62716.json"))
}

resource "oci_identity_tag" "create_tags62716" {
  count = 3

  name             = local.create_tags.tag_names[count.index]
  description      = local.create_tags.tag_description[count.index]
  tag_namespace_id = "DEFAULT_NAMESPACE_ID"
  is_retired       = false

  lifecycle {
    prevent_destroy = true
  }
}
```

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers. If you have any follow-up questions, please use one of the community forums. Thanks!

**Comment by RanganathNangineni** [comment]
Thanks for the alternative.  I am able to achieve the required output with the below format.

### external json data source
data "external" "create_tags64033" {
  program = ["jq", ".", "${path.module}/create_tags64033.json"]
  query   = {}
}

### create new tags
######SAMPLE #####3
resource "oci_identity_tag" "create_tags64033" {
    count = "${length(split(",", data.external.create_tags64033.result["tag_names"]))}"
    description = "${element(split(",", data.external.create_tags64033.result["tag_description"]),count.index)}"
    name = "${element(split(",", data.external.create_tags64033.result["tag_names"]),count.index)}"
    tag_namespace_id = "${data.external.create_tags64033.result["tag_namespace_id"]}"
    is_retired = false
 lifecycle {
    prevent_destroy = true
  }

}
