### ISSUE TITLE
Vsphere Ipaddress as variable with count

### ISSUE THREAD

**Issue by gowthamakanthan** [hashicorp/terraform#21540]
Hi there,

 I am using "terraform" to create multiple by using count.index. I would like to pass the IP as a run time variable instead of hard coding it. Have tried with several methods but no luck.  Any suggestions?

`network_interface {
        #ipv4_address = "10.1.24.${64 + count.index}"
        ipv4_address = "${var.micro-iprange}.${64 + count.index}"
        ipv4_netmask = "24"
}`

**Comment by gowthamakanthan** [comment]
Or someway like this?

`network_interface { 
   ipv4_address = "${var.micro-iprange}+${count.index}" 
   ipv4_netmask = "24" }`

**Comment by apparentlymart** [comment]
Hi @gowthamakanthan,

I think you can get the result you want here using the [`cidrhost`](https://www.terraform.io/docs/configuration/functions/cidrhost.html) function. Something like `cidrhost("10.1.24.0/24", count.index)`.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by gowthamakanthan** [comment]
Apologies for using this space for this question. Recommended CIDR function is working perfectly for me. Thank you.
