### ISSUE TITLE
Error with attributes when using `count` on google_container_cluster

### ISSUE THREAD

**Issue by RexBelli** [hashicorp/terraform#21557]
### Terraform Version

```
Terraform v0.11.14
+ provider.google v2.7.0
```

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "test" {
  count = "1"
  name = "test"
  project = "test"
}

output "client_certificate" {
  value = "${google_container_cluster.test.*.master_auth.0.client_certificate}"
}

output "endpoint" {
  value = "${google_container_cluster.test.*.endpoint}"
}
```

### Debug Output

https://gist.github.com/RexBelli/91011e0d4709b0bfba9a9b0f4fa45166
### Crash Output

```
output.client_certificate: Resource 'google_container_cluster.test' does not have attribute 'master_auth.0.client_certificate' for variable 'google_container_cluster.test.*.master_auth.0.client_certificate'
```
### Expected Behavior

A valid plan should be generated without error.
### Actual Behavior

Trying to access `google_container_cluster.test.*.master_auth.0.client_certificate` returned an error.
### Steps to Reproduce

Run `terraform init && terraform plan` on the above code.
### Additional Context

I'm not sure if this is a provider issue or not.  Note that only one of the `Output` blocks errors.  It's really strange to me that `google_container_cluster.test.*.endpoint` works as intended but `google_container_cluster.test.*.master_auth.0.client_certificate` does not.

`cluster_ca_certificate` and `client_key` under `master_auth.0` also produce the same error.

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
