### ISSUE TITLE
helper/acctest/random module returns duplicate values (from Windows Git Shell/MINGW64)

### ISSUE THREAD

**Issue by mattdot** [hashicorp/terraform#21550]
### Terraform Version

```
0.12.0
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

```
    t.Logf("rand=%d", tf.AccRandTimeInt())
    t.Logf("rand=%d", tf.AccRandTimeInt())
    
    ----- outputs ------- 
    
    data_source_virtual_network_gateway_connection_test.go:14: rand=190531090628781397
    data_source_virtual_network_gateway_connection_test.go:15: rand=190531090628781397
```
### Expected Behavior

Subsequent calls of random.go functions should produce different random numbers

### Actual Behavior

Calling `RandStringFromCharSet` in rapid succession returns the same "random" number multiple times.

### Additional Context

This only happens on Windows Git Bash (MINGW64). It does not happen on Windows/WSL, Mac, Linux, etc.  The time precision within Git Bash seems to be low enough that calling `time.Now().UTC().UnixNano()` multiple times can return the same result. 

### References

This affects testacc tests which need to generate multiple random identifiers 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3573

**Comment by jbardin** [comment]
Thanks @mattdot,

That is only showing up on Windows because, because the standard windows clock resolution is too coarse to provide different values between function calls. 

This should not be a problem though, because a PRNG should only ever be seeded once! That code calls `rand.Seed` ever call, which defeats the purposed of the PRNG essentially making it an obfuscated timestamp.
