### ISSUE TITLE
terraform crash during apply

### ISSUE THREAD

**Issue by aakanshaverma1310** [hashicorp/terraform#21563]
Hi, Im attaching the terraform log file. can you please help?
im getting EOF error. 

-
Aakansha Verma

**Comment by mildwonkey** [comment]
Hi @aakanshaverma1310 ! 
I'm not sure what happened, but your crash.log is not attached.

We'll also need to see your configuration files, or a simplified reproduction case, in order to figure out what's going on here. Can you please update this ticket with the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Remove any sensitive information first.

Thanks again!

**Comment by mildwonkey** [comment]
I'm going to close this due to lack of response. If you are still experiencing a problem, please open a new issue and fill out the provided issue template. Thanks!
