### ISSUE TITLE
conditional produces incorrect result with boolean map field arguments

### ISSUE THREAD

**Issue by vasili-zolotov** [hashicorp/terraform#21574]
### Terraform Version
```
$ terraform --version
Terraform v0.11.13
+ provider.archive v1.2.1
+ provider.aws v2.12.0
+ provider.template v2.1.1
```

### Terraform Configuration Files
```hcl
locals {
  accounts = {
    "abc123" = {
      "flag" = true
    }
  }
}

locals {
  value_1 = "${lookup(local.accounts["abc123"], "flag", false) ? "correct" : "not correct"}"
  value_2 = "${lookup(local.accounts["abc123"], "flag", false) == true ? "correct" : "not correct"}"
}

output "debug_var" {
  value = {
    value_1 = "${local.value_1}"
    value_2 = "${local.value_2}"
  }
}
```

### Expected Behavior
```
Outputs:

debug_var = {
  value_1 = correct
  value_2 = correct
}
```

### Actual Behavior
```
Outputs:

debug_var = {
  value_1 = correct
  value_2 = not correct
}
```
### Steps to Reproduce
Apply the template above.

### Additional Context
I also observed that if I change `== true` above to `== "true"`, then the conditional evaluates to true. Somehow the map value must be losing its boolean type?

### References
May or may not be related to #13389, but @apparentlymart asked me open a separate issue for this one.

**Comment by jbardin** [comment]
Hi @vasili-zolotov,

Thanks for filing the issue. I'm not able to reproduce this, as the release and master both produce the expected output. Are you certain this is the entire configuration?

**Comment by vasili-zolotov** [comment]
@jbardin ok, it turns out you are correct, thanks for looking into this. My simplified config above does indeed produce expected results with 0.12.0 (and incorrect result when using 0.11.x). 

However, my original (more complex) config produces incorrect results with both 0.11.x and 0.12.0. I need to spend some more time on isolating the repro.

**Comment by apparentlymart** [comment]
Hi @vasili-zolotov! Thanks for confirming.

I wanted to add some additional context here in case it helps with your efforts to isolate the reproduction:

Most of the operators in the Terraform language have automatic type inference and type conversion behavior associated. For example:

* the `+` operator implies converting both of its operands to number and always returns number
* the `<` operator implies converting both of its operands to number and always returns bool
* the `&&` operator implies converting both of its operands to bool and always returns bool

However, the `==` operator doesn't have enough information to perform that sort of inference, so it is defined as "values both have the same type _and_ the same value". Consequently, `true == "true"` will evaluate to `false`, even though `true && true` would evaluate to `true`.

You touched on this in your report above, and I think you are on the right track: one of your bools is probably coming from a source that implicitly converted it to a string, such as it being an element of a map whose other elements are also strings.

It might be that this is not something we can solve, but if you can figure out what is causing that conversion to string and it's something that _shouldn't_ be converting to string then we'll see about fixing that.

However, I'd also suggest avoiding comparisons to `true` and `false` using the `==` operator like this, due to this type equality requirement. The `? :` operator knows that the operand before the `?` must be boolean, so it's able attempt automatic conversion with that in mind, while introducing the equality check defeats that.

If you are using a boolean value in a context where boolean type is _not_ implied, and there's no other way to rewrite the expression to imply that, you can force it using the [`tobool`](https://www.terraform.io/docs/configuration/functions/tobool.html) function.

---

In a future release I'd like to introduce a linting feature that can detect this sort of thing and suggest a less-problematic formulation. Right now we only support errors and warnings as results, but it'd be nice in future to introduce a new "notice" diagnostic type that could perhaps be returned by a special opt-in command like `terraform validate -lint`.

This issue indicates two example lint rules:

* Using the `==` operator when one of the operands is literally `true` or `false`. The former is redundant and the latter is better written using the `!` operator.
* Using the `==` operator in any situation where both of the arguments are provably of different types using the information we have at validation time. Such an operator can only ever return `false`, so it'd be better to flag that so the user can seek a different formulation of the same idea, such as including explicit type conversion functions.

**Comment by vasili-zolotov** [comment]
@apparentlymart thanks for that info. I will be on the lookout for expressions that may change the type. I updated the bug description with the actual version I tested my script with.

**Comment by mildwonkey** [comment]
I am going to close this as a stale issue - much has changed since this was opened (we're now on terraform v0.13), and we aren't fixing issues with v0.11 anymore.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
