### ISSUE TITLE
Provisioner "file" fails

### ISSUE THREAD

**Issue by chris1248** [hashicorp/terraform#21570]
### Terraform Version
```
Terraform v0.12.0
+ provider.aws v2.12.0
```

### Terraform Configuration Files
```
	provisioner "file" {
		source      = "../cmake/.ssh"
		destination = "c:/users/administrator"
	}

	connection {
		type        = "ssh"
		user        = "Administrator"
		password    = "${rsadecrypt(aws_instance.stuff.password_data, file("foo.pem"))}"
		host        = "${aws_instance.stuff.public_ip}"
	}
```

### Debug Output
```
2019-06-03T08:56:29.447-0600 [DEBUG] plugin.terraform.exe: file-provisioner (internal) 2019/06/03 08:56:29 [DEBUG] connecting to TCP connection for SSH
2019-06-03T08:56:30.450-0600 [DEBUG] plugin.terraform.exe: file-provisioner (internal) 2019/06/03 08:56:30 [ERROR] connection error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.
2019-06-03T08:56:30.450-0600 [DEBUG] plugin.terraform.exe: file-provisioner (internal) 2019/06/03 08:56:30 [WARN] retryable error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.
2019-06-03T08:56:30.450-0600 [DEBUG] plugin.terraform.exe: file-provisioner (internal) 2019/06/03 08:56:30 [INFO] sleeping for 1s
```

### Expected Behavior
It should have connected

### Actual Behavior
It failed to provision the ec2 instance and instead gave this error:
"connection error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it."
I am trying to set this on using an Amazon supplied AMI of a windows server image. Something like Windows server 2019. I can log into the instance just fine when I don't attempt to provision the machine.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @chris1248,

This error message suggests that either the remote host isn't running an SSH server at all or some other intermediate router is rejecting the SSH connection.

Unfortunately this appears to be a problem with the remote system configuration rather than Terraform itself. The configuration you shared seems correct, assuming that the remote system is running an SSH server on the standard port 22.

Possibly there is a delay after the OS booting but before the SSH server is started where the system is returning this error. Terraform will normally retry for some time until it's able to connect, but if the system boot takes too long then it will eventually give up and return the latest error.

**Comment by chris1248** [comment]
Yes, terraform will retry for quite a while before bailing out with a return error. 
I'll look into starting an SSH server.

**Comment by Cricen** [comment]
Running into this today as well... 

       resource "aws_instance" "nginx1" {
           ....
           connection {
                 user        = "ec2-user"
                 private_key = file(var.private_key_path)
                 host = aws_instance.nginx1.host_id
         }
     ..... 
     }

I verified I can log in with the file and permission is at 400.

**Comment by chris1248** [comment]
How do I check if the Image is running an SSH server?

**Comment by apparentlymart** [comment]
Hi @chris1248,

The answer to that unfortunately depends on lots of details about what OS is installed in your image, how it's configured, etc. The Terraform team can't help with that sort of thing, since it's not within the scope of Terraform.

Since running an SSH server is a general system administration thing and not specific to Terraform, I expect you will be able to find documentation on it elsewhere if you search online for information about whatever specific operating system and version you are using, or possibly ask in forums that cover more general system administration topics, like [Server Fault](https://serverfault.com/).

Since this issue isn't representing a work item for the Terraform Core team, I'm going to close it now.

**Comment by chris1248** [comment]
ok, thanks.
