### ISSUE TITLE
panic: Unknown: <invalid reflect.Value> when terraform_remote_state reads v0.12.x state snapshot

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#21571]
### Terraform Version
Terraform v0.11.14
+ provider.aws v2.13.0
+ provider.random v2.1.2
+ provider.template v2.1.2

### Terraform Configuration Files
```hcl
data "aws_ecr_image" "service_image" {
  registry_id     = "${data.terraform_remote_state.tfstate-tools-ecr.tools_ecr_api_nginx_registry_id}"
  repository_name = "${data.terraform_remote_state.tfstate-tools-ecr.tools_ecr_api_nginx_name}"
  image_tag       = "${var.KIMI}"
}


data "terraform_remote_state" "tfstate-tools-ecr" {
  backend = "s3"

  config {
    bucket   = "${var.s3bucket-tfstate}"
    role_arn = "arn:aws:iam::${var.AccountID}:role/Role"
    key      = "tools/ecr/terraform.tfstate"
    region   = "${var.region}"
  }
}
```

### Expected Behavior
Accessing a remote data source that is running on tf 0.12 from a module that is on tf 0.11.14, should be able to access its resource

### Actual Behavior
tf crashes when pulling the remote state file from s3

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by FernandoMiguel** [comment]
[crash.log](https://github.com/hashicorp/terraform/files/3251365/crash.log)

**Comment by FernandoMiguel** [comment]
here's the tf code
https://gist.github.com/FernandoMiguel/f00945d20bceae1b04546be338d49cf7

**Comment by apparentlymart** [comment]
Hi @FernandoMiguel! Sorry for the slow response.

The code in Terraform 0.11.14 to parse the Terraform 0.12 format does its best to translate the 0.12 type system back into Terraform 0.11's more limited type system, but apparently there is still at least some situation it's not handling correctly.

My bet is that it's `output "ecr"` that's tripping it up... that'll be an object value following the schema of `aws_ecr_repository`, and there's probably something the schema of that resource type that 0.11 can't handle. That's unfortunate, but I suspect it would be impossible to make _everything_ map correctly because the 0.11 type system is considerably more limited than 0.12's.

Our intent with supporting 0.12 state in 0.11.14 was mainly as a short-term helper to allow upgrading to Terraform 0.12 across a few different dependent configurations without needing to strictly order them. That'll work best, though, if the outputs of those other configurations continue to use only 0.11-friendly types until everything is updated to 0.12. I'd suggest keeping everything largely 0.11-limited in your output values until all of the dependencies are also running Terraform 0.12.

It's unfortunate that this is crashing rather than returning a helpful error message, but we're not planning to make any more 0.11.x releases (barring some critical security issue, for example) so sadly I think we may have to just live with this non-ideal error case. Since the error happens on a read operation rather than on a write operation the risk of the error is at least relatively low.

I'm going to leave this issue open for now in the hope that it might be helpful to anyone else who encounters a similar problem. Thanks for reporting this!

**Comment by FernandoMiguel** [comment]
@apparentlymart thanks for looking into this.
I've moved all our code base to 0.12, so we are no longer affected by this issue.

**Comment by teamterraform** [comment]
Since we were keeping this open just as a helper for others who might hit this error during migration, and it's been a few months now, we're going to close this out. Thanks for reporting this @FernandoMiguel, and we're glad to hear that you were able to complete your upgrade.
