### ISSUE TITLE
0.12upgrade command not upgrading submodule

### ISSUE THREAD

**Issue by ndench** [hashicorp/terraform#21581]
I have updated to terraform 0.12 and am running the `0.12upgrade` command over my projects. However when I run the command, it does not upgrade any submodules that are used from another directory. Is there something I'm missing or some other way to upgrade the submodule?

### Terraform Version

```
$ terraform -v
Terraform v0.12.0
+ provider.archive v1.2.2
+ provider.aws v2.12.0
+ provider.null v2.1.2
+ provider.random v2.1.2
```

### Terraform Configuration Files

```
production/main.tf
staging/main.tf
modules/infra/main.tf
```

```hcl
# (staging|production)/main.tf
module "infra" {
    source = "../modules/infra"

    # Variables
}
```

### Expected Behavior

Running `terraform 0.12upgrade` from the `staging/` directory, should not only upgrade `staging/main.tf` but also `modules/infra/main.tf`.

### Actual Behavior

`staging/main.tf` is upgraded, but `modules/infra/main.tf` is left untouched.

**Comment by jbardin** [comment]
Hi @ndench,

This is the expected behavior, modules need to be upgraded individually. The `0.12upgrade` command only works on configuration in a single directory:

> This command will rewrite the configuration files in the given directory ...

**Comment by apparentlymart** [comment]
Some additional context:

Because an upgrade can only be performed once per directory (upgrading an already-upgraded directory is not possible) the upgrade happens on a per-directory basis, leaving you in control of when each of your shared modules is upgraded in case you're trying to upgrade once configuration at a time and need to hold some modules back on 0.11.

However, the upgrade command _does_ take a directory as an argument, so if you wish to just upgrade everything used by a particular configuration you can run `terraform init` in that configuration's main directory and then run `terraform 0.12upgrade` multiple times with each of the module directories in turn, allowing it to use the provider plugins installed to support the whole configuration:

```
terraform init
terraform 0.12upgrade
terraform 0.12upgrade ../modules/infra
terraform 0.12upgrade ../modules/something-else
```

If you have hundreds of modules and their layout follows a systematic pattern then you could potentially write a small script to automate the above, if you're ready to upgrade everything all at once.

**Comment by ndench** [comment]
Thanks for the quick reply @jbardin, and for the context @apparentlymart. I didn't realise that you could pass in the directory, which is the exact thing I was looking for. I missed the option when I checked `-help`.
