### ISSUE TITLE
Elements in for expressions not available as map keys in transformation

### ISSUE THREAD

**Issue by alexharv074** [hashicorp/terraform#21605]
### Terraform Version

```
▶ terraform012 -v                                     
Terraform v0.12.1
```

### Steps to Reproduce

Given this code:

```hcl
locals {
  arr = ["host1", "host2", "host3"]
}

output "test" {
  value = [for s in local.arr: {
            s = upper(s)
          }]
}
```

I run terraform apply.

### Expected Behavior

I expect to see:
```text
Outputs:

test = [
  {
    "host1" = "HOST1"
  },
  {
    "host2" = "HOST2"
  },
  {
    "host3" = "HOST3"
  },
]
```

### Actual Behavior

Instead,

```text
Outputs:

test = [
  {
    "s" = "HOST1"
  },
  {
    "s" = "HOST2"
  },
  {
    "s" = "HOST3"
  },
]
```

Is this a bug?

**Comment by apparentlymart** [comment]
Hi @alexharv074,

Terraform interprets an attribute name as a literal string by default, mainly because in prior versions of Terraform variables weren't permitted in object keys at all and so 0.12 had to remain compatible with a very common usage pattern.

You can make it work as expected by adding either parentheses or the interpolation syntax around that key expression so Terraform can understand that you mean to evaluate it: either `(s)` or `"${s}"` .

**Comment by alexharv074** [comment]
Thanks @apparentlymart , confirming this returns the expected output:

```hcl
locals {
  arr = ["host1", "host2", "host3"]
}

output "test" {
  value = [for s in local.arr: {
            "${s}" = upper(s)
          }]
}
```

Is there any plan to change this?

**Comment by apparentlymart** [comment]
There are no plans to change this. Specifying literal attribute names is the far more common situation and to change it would break most Terraform configurations in existence, so this is an example of language design pragmatism.

**Comment by alexharv074** [comment]
Thanks for the explanations @apparentlymart
