### ISSUE TITLE
Using naked local reference as key in map literal fails with "Error: Ambiguous attribute key ... wrap it in parentheses"

### ISSUE THREAD

**Issue by andresvia** [hashicorp/terraform#21602]
### Terraform Version

```
Terraform v0.12.1
```

### Terraform Configuration Files

```hcl
//root module
locals {
  key = "key"
}

module "mod" {
  source = "./mod"
  v = {
    foo = "bar"
    baz = "qux"
    local.key = "value"
  }
}

output "mod_o" {
  value = module.mod.o
}

// mod module
variable "v" { type = "map" }
output "o" {
  value = jsonencode(var.v)
}
```

### Debug Output

```
Error: Ambiguous attribute key

  on main.tf line 10, in module "mod":
  10:     local.key = "value"

If this expression is intended to be a reference, wrap it in parentheses. If
it's instead intended as a literal name containing periods, wrap it in quotes
to create a string literal.
```

### Expected Behavior

Replaced `local.key` -> with `(local.key)` , then expected.

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

mod_o = {"baz":"qux","foo":"bar","key":"value"}
```

### Actual Behavior

But instead got.

```
Error: Ambiguous attribute key

  on main.tf line 10, in module "mod":
  10:     (local.key) = "value"

If this expression is intended to be a reference, wrap it in parentheses. If
it's instead intended as a literal name containing periods, wrap it in quotes
to create a string literal.
```

### Steps to Reproduce

1. Create 

```
locals {
  key = "key"
}

module "mod" {
  source = "./mod"
  v = {
    foo       = "bar"
    baz       = "qux"
    "${local.key}" = "value"
  }
}

output "mod_o" {
  value = "${module.mod.o}"
}
```

2. run `terraform 0.12upgrade`

3. obtain

```
locals {
  key = "key"
}

module "mod" {
  source = "./mod"
  v = {
    foo       = "bar"
    baz       = "qux"
    local.key = "value"
  }
}

output "mod_o" {
  value = module.mod.o
}
```

**Comment by apparentlymart** [comment]
Thanks for reporting this, @andresvia.

In this case, it is the upgrade tool behavior that is incorrect. The expression in question must remain as an interpolated string so Terraform can know you intend it to be a reference to a local value rather than a literal name.

In your error message I see it shown with parentheses, which is also supposed to work and so if that is what the upgrade tool did then it was correct after all, but you then ran into the same issue as #21566. The workaround in that case is to use the interpolation syntax instead of the parentheses.

**Comment by andresvia** [comment]
Thanks @apparentlymart , the upgrade tool did not wrap it, I did after seeing the error message, both are getting ambiguity errors, as a workaround I'm using interpolation syntax for now. You are right about #21566 it seems like I duplicate it.

**Comment by apparentlymart** [comment]
Thanks for confirming, @andresvia.

Terraform v0.11 didn't actually support interpolation sequences in map like that, so the upgrade tool ought to have converted it in the following way in order to ensure the same interpretation as in Terraform v0.11:

```hcl
   "$${local.key}" = "value"
```

The extra dollar sign here would escape the special meaning and cause it to be interpreted literally, just as Terraform 0.11 would've.

So it does seem like there is an upgrade tool bug here separate from what's discussed in #21566. Let's use _this_ issue to represent that upgrade tool bug, and we'll use #21566 to represent the fact that adding parentheses to the expression didn't help even though that was exactly what the error message suggested to do.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity (and I believe the issue has been resolved). We're not making any more changes to the 0.12upgrade tool now that v0.13 is available.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
