### ISSUE TITLE
terraform "Are you sure you want to continue connecting (yes/no)?" how to handle

### ISSUE THREAD

**Issue by ajoysinhactc** [hashicorp/terraform#21603]
I am trying to connect to private ec2 instance through Bastion server using Terrafrom. But Terrafrom script ask the question "Are you sure you want to continue connecting (yes/no)?" and i am not able to pass the answer "yes" to it. hence execution is not complete.

I have tried with -input=false also .. but no success

```

# ---------------------------------------------------------------------------------------------------------------------
# Update the instnaces by installing newrelic agent using remote-exec
# ---------------------------------------------------------------------------------------------------------------------

resource "null_resource" "copy_file_newrelic_v_15" {

  count = "${length(aws_instance.bastion.*.ami)}"

  triggers = {
    cluster_instance_ids = "${join(",", aws_instance.bastion.*.id)}"
  }

  connection {
    host = "${element(aws_instance.bastion.*.public_ip, count.index)}"
    user = "ec2-user"
    private_key = "${file("C:/keys/nvirginia-key-pair-ajoy.pem")}"
    agent = "true"
  }

  provisioner "remote-exec" {

    connection {
        agent = "true"
        bastion_host = "${element(aws_instance.bastion.*.public_ip, count.index)}"
        bastion_user = "ec2-user"
        bastion_port = 22
        bastion_private_key = "${file("C:/keys/nvirginia-key-pair-ajoy.pem")}"
        user = "ec2-user"
        private_key = "${file("C:/keys/nvirginia-key-pair-ajoy.pem")}"
        host = "172.31.2.218"
    }

    inline = [
      "ssh ec2-user@172.31.2.218" 
    ]
  }

}

```

Actual execution should be pass through after getting answer to "Are you sure you want to continue connecting (yes/no)?" question. manually or programetically.

I need to pass "yes" to Terraform for this question, which will be accepted by Terraform and will complete the execution. This should be done through Terraform configuration.

**Comment by apparentlymart** [comment]
Hi @ajoysinhactc!

I don't think that message is coming from Terraform itself. This looks like a message from OpenSSH about host verification.

If so, the need here is to pre-configure the host in the SSH known hosts file before running Terraform. I think if you search for the message you got here you can find some guides on this topic, which comes up in any situation where OpenSSH is used as part of a non-interactive process.

Since this isn't a message from Terraform, unfortunately we can't provide detailed help on how to configure OpenSSH.
