### ISSUE TITLE
Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404. Opc request id:

### ISSUE THREAD

**Issue by gsamraj** [hashicorp/terraform#21616]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by gsamraj** [comment]
Terraform Version - v0.11.14
Provider oci v3.26.0

**Comment by mildwonkey** [comment]
Hi! I am sorry that you're having an issue.

We'll need to see your configuration files, or a simplified reproduction case, and the debug log in order to figure out what's going on here. Can you please update this ticket with the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Remove any sensitive information first.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by gsamraj** [comment]
This issue is resolved after adding the provider details. (provider = "oci_")
