### ISSUE TITLE
Propagation of create_before_destroy = true

### ISSUE THREAD

**Issue by Lasering** [hashicorp/terraform#21610]
### Terraform Version
```
Terraform v0.12.0
+ provider.random v2.1.2
+ provider.tls v2.0.1
```

### Terraform Configuration Files
```hcl
resource "random_integer" "bits" {
  min = 2048
  max = 4096
}
resource "tls_private_key" "terraform" {
  algorithm = "RSA"
  rsa_bits = random_integer.bits.result
  lifecycle {
    create_before_destroy = true
  }
}

```

### Expected Behavior
Only the `tls_private_key` should be created before destroy.

### Actual Behavior
Both resources will create the replacement first then destroy the old instance.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform taint random_integer.bits`
4. `terraform taint tls_private_key.terraform`
5. `terraform plan`

### Additional Context
Output from terraform plan (simplified):
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+/- create replacement and then destroy

Terraform will perform the following actions:

  # random_integer.bits is tainted, so must be replaced
+/- resource "random_integer" "bits" {
      ~ id     = "3232" -> (known after apply)
        max    = 4096
        min    = 2048
      ~ result = 3232 -> (known after apply)
    }

  # tls_private_key.terraform is tainted, so must be replaced
+/- resource "tls_private_key" "terraform" {
        algorithm                  = "RSA"
        ecdsa_curve                = "P224"
      ~ id                         = "3ff51c9479f37e8906fd4bda0c07cce5bccbc57a" -> (known after apply)
      ~ private_key_pem            = "<ommited for simplicity>" -> (known after apply)
      ~ public_key_fingerprint_md5 = "85:40:0e:0c:06:c1:dd:c5:58:e2:2a:14:00:67:d7:1b" -> (known after apply)
      ~ public_key_openssh         = "<ommited for simplicity>" -> (known after apply)
      ~ public_key_pem             = "<ommited for simplicity>" -> (known after apply)
      ~ rsa_bits                   = 3232 -> (known after apply)
    }

Plan: 2 to add, 0 to change, 2 to destroy.

```
Setting a lifecycle with `create_before_destroy = false` for `random_integer` has no effect.

Seems like the `create_before_destroy = true` is being propagated via the graph. I don't know if it is a bug or an undocumented feature (I hope its a bug). Even if it is a feature "overriding" the `create_before_destroy` on `random_integer` should work.

The terraform configuration given is just an example chosen for its simplicity. The problem will also arise with other resources.

**Comment by jbardin** [comment]
Hi @Lasering,

What you're seeing here is the expected behavior. Because the `tls_private_key` depends on `random_integer`, the `random_integer` can't be destroyed until after the `tls_private_key`. The new `tls_private_key` depends on the new `random_integer`, so that has to be made first, hence forcing the `random_integer` to be `create_before_destroy` as well. 

You can't override `create_before_destroy` on `random_integer`, because the ordering of resource requires it, and there would otherwise be dependency cycles in the graph.

**Comment by Lasering** [comment]
That makes sense. I guess then the docs should explain it, or at least mention it (at least I couldn't find any explanation).

I don't understand why overriding the `create_before_destroy` would cause cycles. What I can see as a "problem" is using the "old" value instead of the "new" value.

**Comment by jbardin** [comment]
There may some place that this makes sense to add. These details generally aren't documented other than that Terraform will order the resource dependencies as necessary.

Examples of this get convoluted easily, but simplest way I've found to state the problem is: in any non-trivial acyclic subgraph, reversing half the edges is likely to result in a cycle ("overriding" `create_before_destroy` on a subset of the graph amounts to reversing the dependencies).

**Comment by Lasering** [comment]
The documentation could mention it here: https://www.terraform.io/docs/configuration/resources.html#create_before_destroy

Checking if a graph/subgraph has loops isn't that expensive computationally. The plan/apply could check and if there were loops it could complain, or if an overridden create_before_destroy was present hint that it could be the cause.

**Comment by jbardin** [comment]
Yes, the docs at one point had something like that (back when users have to manually add `create_before_destroy`). Declaring that all dependencies have to be able to handle this parameter should suffice.
