### ISSUE TITLE
Terraform merge two tf.files together

### ISSUE THREAD

**Issue by SirWayne** [hashicorp/terraform#21627]
First i execute `terraform init` and `terraform apply` for all our infrastructure components. Next i execute some powershell scripts to modify those components which are currently not supported by the terraform provider (azure). Lastly I execute `terraform init` and `terraform apply` for a second terraform file, with a second state file, which adds azure locks to the resource groups. This worked fine before I upgraded to terraform 0.12.1.
After the upgrade the azure locks state file is refreshed and terraform tries to delete all components from the first state file. The terraform files are seperated into different folders.

The folder structure looks like:
```
azure_infrastructure.tf
 --lock-folder
  --- azure_locks.tf
```

If i am looking in the second azure state file, it seems that the first state file is included completely. I don't understand why the two files arg merged together.
Anybody an idea?

**Comment by SirWayne** [comment]
Ok i see on the log of the build server:
```
Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.


Do you want to copy existing state to the new backend?
  Pre-existing state was found while migrating the previous "azurerm" backend to the
  newly configured "azurerm" backend. No existing state was found in the newly
  configured "azurerm" backend. Do you want to copy this state to the new "azurerm"
  backend? Enter "yes" to copy and "no" to start with an empty state.
```

How can i say no?

**Comment by mildwonkey** [comment]
Hi! I think `-reconfigure` is the `init` option that will do what you are looking for here: https://www.terraform.io/docs/commands/init.html#backend-initialization  

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by SirWayne** [comment]
For me this is a bug, when it works before the upgrade to terraform 0.12.x. I don't understand why it should change the lifecycle.

**Comment by apparentlymart** [comment]
Hi @SirWayne,

After `terraform init` is completed, Terraform tracks the backend settings in `.terraform/terraform.tfstate` so that they are available for subsequent commands run from that same working directory.

If you then run `terraform init` again from another directory, Terraform sees that `.terraform/terraform.tfstate` is already present and assumes that you want to migrate from the already-cached backend configuration to the one present in the new directory. This behavior is as intended, and I'm not sure why it didn't behave this way in Terraform 0.11.

As @mildwonkey mentioned, `-reconfigure` is a way to tell Terraform to ignore the backend configuration that is cached in `.terraform/terraform.tfstate` and instead behave as if no backend configuration was previously present, which seems to be what you wanted to achieve here.

The more usual way to do this would be to run `terraform init` separately in each configuration directory, so your second step would be: `cd lock-folder; terraform init` with no configuration directory. In that case, both directories will have their own separate `.terraform` directories and thus Terraform will not be confused into thinking that you intend to share the same backend between the two.

Because this behavior is as intended, I must assume that there was a bug in Terraform 0.11 that was preventing it from detecting and handling this situation.

**Comment by SirWayne** [comment]
Hey @apparentlymart,

Thanks for your detailed explanation. Then maybe it was a bug in 0.11.x.
In the meantime, we have done it with 2 different folder, which works great
