### ISSUE TITLE
Terraform Custom CA Chain

### ISSUE THREAD

**Issue by danieladams456** [hashicorp/terraform#21632]
**Note**: SSL intercepting proxy
### Terraform Version
```
Terraform v0.11.14
```

### Terraform Configuration Files
```hcl
provider "aws" {}
```

### Debug Output
[gist](https://gist.github.com/danieladams456/caa376e711fc6d74c4d8112471afc678)

### Expected Behavior (version 0.11.13)
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (2.13.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.13"

Terraform has been successfully initialized!
```

### Actual Behavior (version 0.11.14)
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": Get https://releases.hashicorp.com/terraform-provider-aws/: x509: certificate signed by unknown authority.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. set proxy environment variables for SSL intercepting proxy
2. `rm -rf .terraform/ && terraform init` works (version 0.11.13)
3. `rm -rf .terraform/ && terraform1114 init` fails

### Additional Context
I see what appears to be the same issue in 0.12.1, but I figured staying within the 0.11.X line would be easier to test.

The same thing was happening with the checkpoint api in 0.11.X and discovery api in 0.12.X.  AWS SDK seems to be fine since I'm using the `AWS_CA_BUNDLE` environment variable.

### References
none I can find

**Comment by danieladams456** [comment]
@apparentlymart just curious why this was labeled an enhancement when it has worked in past versions and now doesn't?

Do you know what change might have introduced this behavior?  I looked through the changelog and commits and didn't see anything that stood out as an obvious culprit.

**Comment by apparentlymart** [comment]
Sorry... I did write a comment here as I was doing that but apparently I neglected to actually send it. 🤦‍♂️

The short version is that what you were doing here was never intended to be supported and has apparently been "fixed" by some upstream change, probably in the Go runtime library Terraform is using here.

The "enhancement" is to design and implement a specific mechanism for enabling interception by a specific proxy server whose certificate is known to Terraform, similar to the AWS provider environment variable you mentioned.

Until we learn more about what happened here (and why your configuration had been working before) I don't have any workaround to suggest except to stay on Terraform 0.11.13.

(For provider installation in particular Terraform 0.11 also checks the installed archives against the HashiCorp software signing key, so it will not install unsigned providers regardless of the interception of a proxy server. The situation for 0.12 is more complicated because it now uses Terraform Registry as an intermediate index, so we need a mechanism that works for both the registry and the releases server.)

**Comment by danieladams456** [comment]
Makes sense, thank-you for the explanation!

We are interested in trying out the 0.12 functionality - should I be able to use the the [user plugins directory](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations), with pre-downloaded plugins, or does that signature checking still require internet access?

I saw [terraform bundle](https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle), but that might be more than necessary.

**Comment by apparentlymart** [comment]
If you use [`-plugin-dir`](https://www.terraform.io/docs/commands/init.html#plugin-dir-path) with `terraform init` then it will disable all of the network-driven installation functionality and expect to find all of the required plugins in the given directory. I think that'll be your best bet for your current goal.

Populating a user plugin directory can potentially work too, but Terraform will still try to reach out to the registry index in some cases to verify that the locally-installed plugins are up to date, whereas `-plugin-dir` will explicitly disable all such behaviors and force only the use of the given directory.

**Comment by danieladams456** [comment]
Issue is fixed for mac!
- go to `Keychain Access`
- select `Certificates` panel on bottom left
- double check each corporate intermediate certificate, expand `Trust`, and select `Always Trust`
