### ISSUE TITLE
drop specific cassandra instance

### ISSUE THREAD

**Issue by rajpaly** [hashicorp/terraform#21649]
Hello All,

Trying to remove cassandra faulty node.  i used terraform destroy  -target RESOURCE_TYPE.NAME. then changed the instance count from 7 to 6. Plan shows dropping the exiting instance(last instance created ) and creating new instance. is there away to handle this like delete with terraform destroy and if i change the instance_count it should pick the dropped and no change in the plan.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
