### ISSUE TITLE
0.12 - import should attempt to write out `depends_on` blocks into the state file

### ISSUE THREAD

**Issue by a13xb** [hashicorp/terraform#21647]
When creating new resources with Terraform, resources in the state file get a `depends_on` block (which matches the set of references to other resources that this resource definition is using).

However when importing existing resources into Terraform, `depends_on` is missing. I can understand it will be missing for partially imported resources because not all resources could be known yet, but when a complete graph of resources is known, they should ideally be written out. (I have not tested, but I suspect a similar problem exists when you edit a resource to replace a hardcoded ID with a reference to another Terraform resource.)

I have not actually _tried_ modifying imported infrastructure, but I have a feeling if I do, it may lead to unexpected results, or exhibit behaviour different from when resources are created from scratch.

### Current Terraform Version
```
Terraform v0.12.1
+ provider.aws v2.13.0
```

**Comment by pkolyvas** [comment]
@a13xb Thanks for contributing this request. I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. 

Because `depends_on` is a manual addition where Terraform isn't properly relating resources the way a practitioner, operator or configuration author would like, it's nigh on impossible for Terraform to  link resources automatically with that particular relationship. 

From the docs: 
```
Use the `depends_on` meta-argument to handle hidden resource dependencies that Terraform can't automatically infer.
```
Ref: https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

I think while we could probably come up with a way for practitioners to include that inference during import, it's unlikely to our first target where it comes to improving importing. I think there is a future (a long-way off) where we are able to better able to link together resources in the way practitioners expect; one that's more in-line with use cases that don't rely on explicitly defining dependencies. As a quick example: importing a VPC, its subnets, routing tables, and having the dependencies between them be properly defined would be closer to the goal we currently have in mind. As noted though, we're not even close to that.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
