### ISSUE TITLE
`remote-exec` provisioner in the Azure Getting Started guide - Error: timeout - last error: dial tcp :22: connect: connection refused 

### ISSUE THREAD

**Issue by bgarcial** [hashicorp/terraform#21665]
### Terraform Version

```
⟩ terraform -v
Terraform v0.12.1

...
```

### Terraform Configuration Files

When we define a provisioner, it needs to add the `host` field in the `connection` block. Currently in the documentation, we can find it of this way:

```
resource "azurerm_virtual_machine" "vm" {

    <...snip...>

    provisioner "file" {
        connection {
            type     = "ssh"
            user     = "${var.admin_username}"
            password = "${var.admin_password}"
        }

        source      = "newfile.txt"
        destination = "newfile.txt"
    }

    provisioner "remote-exec" {
        connection {
            type     = "ssh"
            user     = "${var.admin_username}"
            password = "${var.admin_password}"
        }

        inline = [
        "ls -a",
        "cat newfile.txt"
        ]
    }

}
```

When I create my plan, I get the following:
```
⟩ terraform plan -out tfprov

Error: Missing required argument

  on main.tf line 196, in resource "azurerm_virtual_machine" "vm":
 196:     connection {

The argument "host" is required, but no definition was found.
...
```
- I've added the host attribute of this way: `host = "${azurerm_public_ip.publicip.ip_address}"`
I mean: 

```
# Create a Linux virtual machine
resource "azurerm_virtual_machine" "vm" {
  name                  = "${var.resource_prefix}TFVM"
  location              = "${var.location}"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  network_interface_ids = ["${azurerm_network_interface.nic.id}"]
  vm_size               = "Standard_DS1_v2"

  storage_os_disk {
    name              = "${var.resource_prefix}OsDisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
  }

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04.0-LTS"
    version   = "latest"
  }

  os_profile {
    computer_name  = "${var.resource_prefix}TFVM"
    admin_username = "${var.admin_username}"
    admin_password = "${var.admin_password}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
 
  provisioner "file" { 
    connection {
      type = "ssh"
      host = "${azurerm_public_ip.publicip.ip_address}"  # ----> HOST PARAMETER ADDED
      user = "${var.admin_username}"
      password = "${var.admin_password}"
    }
    
    source = "newfile.txt"
    destination = "newfile.txt"
  }

  provisioner "remote-exec" {
    connection {
      type = "ssh"
      host = "${azurerm_public_ip.publicip.ip_address}"  # ----> HOST PARAMETER ADDED
      user     = "${var.admin_username}"
      password = "${var.admin_password}"
      
    }

    inline = [
      "ls -a",
      "cat newfile.txt"
    ]
  }
}

```

But I get this error

```
`Error: timeout - last error: dial tcp :22: connect: connection refused`
``` 

- Then, I've decided add the `port`, `timeout` and `agent` parameters to the provisioners, of this way:

```
provisioner "file" { 
    connection {
      type = "ssh"
      host = "${azurerm_public_ip.publicip.ip_address}"
      user = "${var.admin_username}"
      password = "${var.admin_password}"
      port = 22 # ----> HOST PARAMETER ADDED
      timeout     = "1m" # ----> TIMEOUT PARAMETER ADDED
      agent       = false # ----> AGENT PARAMETER ADDED
    }
    
    source = "newfile.txt"
    destination = "newfile.txt"
  }

  provisioner "remote-exec" {
    connection {
      type = "ssh"
      host = "${azurerm_public_ip.publicip.ip_address}"
      user     = "${var.admin_username}"
      password = "${var.admin_password}"
      port = 22 # ----> HOST PARAMETER ADDED
      timeout     = "1m" # ----> TIMEOUT PARAMETER ADDED
      agent       = false # ----> AGENT PARAMETER ADDED
    }
```
And I get this error 

```
Error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to 
https://management.azure.com/subscriptions/4e65758d-dbf5-456f-bb55-6b92273772dd/providers/Microsoft.Compute/locations/westeurope/operations/79a47793-041a-4c3d-918a-e6cd1bac267d?api-version=2018-06-01: 
StatusCode=0 -- Original Error: Manually created ServicePrincipalToken does not contain secret material to retrieve a new access token
```
I've deleted entirely the resources infrastructure and create them again, and I get again the connection refused error 

```
Error: timeout - last error: dial tcp :22: connect: connection refused
```
- But it is strange, because the ssh port 22 is open
```
⟩ ssh plankton@137.117.199.22
The authenticity of host '137.117.199.22 (137.117.199.22)' can't be established.
ECDSA key fingerprint is SHA256:LiR0l3QPWHH2jZdUXUVr/t0WDUiCg2ck/FelBjPHQDg.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '137.117.199.22' (ECDSA) to the list of known hosts.
plankton@137.117.199.22's password: 
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1045-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

plankton@myTFVM:~$ 
```

What could be happening with the process to connect to my virtual machine via ssh using a `remote-exec` provisioner?

**Comment by apparentlymart** [comment]
Hi @bgarcial!

Based on the error message here, it seems that Terraform did attempt to reach the host on port 22 and was unable to connect, which suggests a problem with the configuration on the remote host rather than with your Terraform configuration or with Terraform itself.

"Connection refused" means that when Terraform tried to connect, the running machine sent back a specific "refused" response to Terraform, as opposed to the connection request not being received at all. This could happen if, for example, the SSH server were slow to start up and so it was not running when Terraform tried to connect, but then by the time you ran `ssh plankton@137.117.199.22` it _had_ started up.

Terraform supports provisioning over SSH as a last resort for situations where nothing else is possible, but requiring an additional direct connection to the host adds a lot of extra complexity and potential for failure. We'd always recommend taking other approaches if at all possible, to simplify the process and thus make it easier to debug and (in most cases) faster. For Azure in particular, there are two alternative approaches that I'd recommend using instead of provisioners:

* Ideally, make a custom machine image that already contains the additional files needed for your use-case, so that the machine will just start up and immediately start doing its work without any further intervention. There are lots of ways to do that, but for example one way is to use [HashiCorp Packer's `azure` builder](https://packer.io/docs/builders/azure.html), which allows you to describe a series of changes to apply to a stock machine image to prepare it for a specific use-case.
* If the software running in the virtual machine requires information that Terraform itself has determined during `terraform apply`, you can use the `custom_data` argument within the virtual machine configuration to pass that data through the Azure API to the virtual machine, so that it will be available immediately on system boot. If you are working with an Ubuntu image, I believe `custom_data` is interpreted as a configuration for [cloud-init](https://cloudinit.readthedocs.io/en/latest/), and so you can instruct cloud-init to run arbitrary commands on boot to get a similar result to your provisioners, but without the complexity and delay of starting up an SSH server and having Terraform connect to it first.

Unfortunately the Terraform team generally can't help with general system configuration problems, because our focus is on the implementation of Terraform itself. If you have further questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are more people ready to help. The GitHub issues here are generally monitored only by our few core maintainers, and used primarily to track specific work items for the Terraform team.

**Comment by JerryMSFT** [comment]
Hello, 

I am having the same issue and this is not VM related as I can SSH into the VM while the terraform script is running:

See below for screen output while main.tf is running:
________________________________________________________________________________________
azurerm_virtual_machine.vm (remote-exec): Connecting to remote host via SSH...
azurerm_virtual_machine.vm (remote-exec):   Host:
azurerm_virtual_machine.vm (remote-exec):   User: someuser
azurerm_virtual_machine.vm (remote-exec):   Password: true
azurerm_virtual_machine.vm (remote-exec):   Private key: false
azurerm_virtual_machine.vm (remote-exec):   Certificate: false
azurerm_virtual_machine.vm (remote-exec):   SSH Agent: false
azurerm_virtual_machine.vm (remote-exec):   Checking Host Key: false
azurerm_virtual_machine.vm: Still creating... [6m30s elapsed]

Error: timeout - last error: dial tcp :22: connect: connection refused
_____________________________________________________________________________________
Yet, while this is waiting to time out -- I can SSH into the VM. here are some snippets of my tf code. 
....
resource "azurerm_public_ip" "pip" {
    name                               = "terraformIaaSpubIP"
    location                           = "eastus"
    resource_group_name    = "${azurerm_resource_group.rg.name}"
    allocation_method          = "Dynamic"
}
.....
    connection {
    host = "${azurerm_public_ip.pip.ip_address}"
    agent = false
    type = "ssh"
    user     = ""
    password = ""
 }

provisioner "remote-exec" {
    inline = [
    "echo $jerry@r00t123 | sudo -S apt-get-update",
    "apt-get upgrade -y",
    "apt-get -y install nginx",
     "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
  ] 
 }
}

**Comment by srimukh** [comment]
Hi, i was also struggling with this issue for a week , for me the fix was updating the public_ip_address_allocation to "**static**".

resource "azurerm_public_ip" "publicip" {
name = "${var.resource_prefix}TFPublicIP"
location = "${var.location}"
resource_group_name = "${azurerm_resource_group.rg.name}"
public_ip_address_allocation = "static"
}

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
