### ISSUE TITLE
base64decode function no longer decodes ec2 resource password_data

### ISSUE THREAD

**Issue by ericbrumfield** [hashicorp/terraform#21669]
We recently upgraded from 0.11.13 to 0.12.1 and have ran into an unexpected issue.  Our Terraform script at one point will take an ec2 resource's password data and run a terraform function of base64decode against it.  We get an error now that the string is not valid UTF-8, which I suppose is expected now with the version change, so I guess it's not technically a bug.

`"${base64decode(aws_instance.ec2_bootstrapped.password_data)}"`

Is there anything currently built into the Terraform language where we can convert the string to something valid base64decode can handle?  Maybe an opportunity for a feature request here, like an option to convert the format?

Currently I've been able to dance around this through a few local-exec provisioner commands to get the data massaged to where we need it for further processing.

**Comment by apparentlymart** [comment]
Hi @ericbrumfield! Sorry for this extra friction.

This new check in Terraform 0.12 is trying to prevent an unfortunate situation in prior versions where Terraform would silently corrupt non-UTF8 string data by just assuming all strings are UTF-8 but not actually checking them. We now check so we can produce a hard error rather than silently corrupting them. However, I know that in some cases such usage was _not_ leading to corruption and was just (by lucky coincidence) working before, so it's frustrating that Terraform now seems to be being overly cautious in 0.12.

With that said, our intent here is that when you're working with small binary blobs in the Terraform language you should be able to leave them in base64 format -- our convention for representing raw binary data -- and that whatever other component is receiving them should be designed to accept them in base64 format too, handing the decoding itself.

I'm not familiar with the full workflow for dealing with an EC2 instance `password_data`, so I'm not sure exactly what to suggest here. From a quick read of the docs it sounds like `password_data` is a ciphertext encrypted with some key.

If it's in a form that is compatible with [`rsadecrypt`](https://www.terraform.io/docs/configuration/functions/rsadecrypt.html) then you could use that, but beware that if you use that in a resource argument the resulting cleartext will be saved in the state. You can safely use this in a `connection` block to configure credentials for remote provisioning though, because provisioner connection configurations exist only temporarily in memory during the apply step and are not saved in the state.

```hcl
connection {
  # ...

  password = rsadecrypt(
    aws_instance.ec2_bootstrapped.password_data,
    local.password_private_key, # wherever you have this key stored
  )
}
```

The [GetPasswordData](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetPasswordData.html) documentation doesn't mention what encoding is used for that ciphertext, so I can't be sure if it's in the form `rsadecrypt` is expecting, but from reviewing #16647 (where this function was introduced) it seems like dealing with this `password_data` was in fact the original use-case here, and so hopefully this gets you what you need here!

**Comment by ericbrumfield** [comment]
No worries, I had already been using kind of a chain of local-exec provisioners around my use case, which we're more or less dog fooding the ec2 keypair data back into vault for an emergency/break glass scenario for admins to remote into a machine.  I ended up using base64 cli on the host machine instead of the Terraform function for decoding it.

That's good info to know about the connection example you gave as an option and I may give the rsadecrypt a try as it might remove one of the local-exec provisioners in our chain.

I've been careful to where we aren't exposing sensitive data with the keys in either the shell output or within the Terraform state by using combinations of sensitive flags and environment vars when doing local-exec shell calls.  Also careful to ensure the shell calls don't write to history although we're currently using Windows.  It sounds like I fell into the lucky coincidence category in 0.11 for this one.

I understand the change made in 0.12 and it probably keeps Terraform simpler for it to only deal with UTF-8, rather than an option where a caller specifies the input encoding format for Terraform to convert it from something to UTF-8 internally, of course given they know what it is in.  Feel free to close this if that wouldn't be a handy feature/option/parameter.

Thanks again!

**Comment by apparentlymart** [comment]
Hi @ericbrumfield,

I think what you are alluding to at the end of your comment there is, in a different sense, first-class support for a "binary blob" data type in Terraform. We did consider that as a solution here, but ultimately concluded that raw binary data is not a common situation in Terraform (though it does arise from time to time, as we see here) and we already had a pre-existing convention of using base64 strings to represent it and so it was less disruptive to just adopt that convention formally and ensure that any features that _do_ need to deal with binary data are written to expect base64 inputs.

While a function to convert text with some other character encoding to a Terraform string would be possible in theory, it would not be a general solution to this problem because not all raw binary data is text. In particular, I don't think this `password_data` value is an alternative encoding of text, but rather a packed binary encoding. If we were to represent this without the base64 encoding, the only alternative would be a new data type that is essentially a raw byte array.

Given that, I'm going to close this as you suggested. Base64 strings are, in effect, Terraforn's "byte array" type by convention, and we intend to make sure that any feature that is designed to use small binary data arrays either produces or consumes base64 data so that these features are composeable. Of course, if you send data _outside_ of Terraform as in your case then the external system must unfortunately then shoulder the burden of decoding the data, but fortunately base64 is a common enough standard that it's usually reasonable to do so.

Thanks again for reporting this!

**Comment by e96wic** [comment]
Hi @apparentlymart,

our setup involves reading base64 encoded binary JKS certificate data from vault, decoding it in terraform and writing this to a kubernetes secret. When I understand you correctly this is not possible anymore with terraform 0.12? Can we at least read the binary data directly from vault and write to kubernetes?

**Comment by apparentlymart** [comment]
Hi @e96wic,

In order to support that, the Vault provider should export the data base64-encoded (which it sounds like it already is, per your message) and then the Kubernetes provider resource type that accepts it should support receiving the data base64-encoded, thus avoiding any need for it to be decoded within the Terraform configuration itself.

If either end of that are not currently using base64 to represent the data as a Terraform value, please open an issue in the provider repositories to make the provider development teams aware of the use-case.
