### ISSUE TITLE
Terraform 12 doesn't support tilde when specifying backend config

### ISSUE THREAD

**Issue by kenorb** [hashicorp/terraform#21672]
### Terraform Version

```
Terraform v0.12.0
```

### Expected Behavior

```
Terraform has been successfully initialized!
```

### Actual Behavior

```
Initializing the backend...

Error: Failed to read file

The file "~/.file.conf" could not be read.
```

### Steps to Reproduce

1. Create an empty file at: `~/.file.conf'`.
1. Run: `terraform init -get=true -upgrade=true '--backend-config=~/.file.conf'`.

### Additional Context

Using tilde when specifying config file worked in Terraform v0.11.14, doesn't work in v0.12.0.

### Workaround

The workaround is to use `$HOME` instead of `~`.

```
terraform init -get=true -upgrade=true "--backend-config=$HOME/.file.conf"
```

**Comment by emilymye** [comment]
Please copy this over to Terraform core! The Google provider doesn't actually manage the GCS backend or how configuration is parsed.

**Comment by jbardin** [comment]
Hi @kenorb,

The `~` representing the `$HOME` directory is an expansion performed by the shell you're using, and is not normally handled by individual applications. 

You actually have 2 things that are preventing the tilde-expansion. The first is that a shell uses single quote to prevent interpolation of special characters in the string, and the second is that having the `=` sign directly preceding the `~` disables the expansion because it's no longer a bare prefix. 

As you've discovered, the `$HOME` environment variable works well here, as would removing the `=` and single quote from the option: `--backend-config ~/.file.conf`

**Comment by kenorb** [comment]
It's not about a single quote, as using double quotes like `"--backend-config=~/.file.conf"` also fails, secondly exactly the same syntax works fine in Terraform v0.11.14. Although `--backend-config ~/.file.conf` syntax make sense.

**Comment by kenorb** [comment]
@jbardin To summarize, the documentation reads to use `-backend-config=path` syntax (with `=`, no space), but it doesn't work like: `-backend-config=~/path` (without quotes), which doesn't work.

**Comment by jbardin** [comment]
Without the single quotes, the `~` still not being interpreted by the shell, because it is prefixed by the `=` symbol. This is one of the many quirks of the shell you're using, but but trying to alter that behavior leads to other problems.

It appears that the flags like `-backend-config` were a special case in terraform 0.11 where it would make a second attempt at expanding a `~`. It's generally ill-advised to replicate shell features within a cli program, because it's more likely to cause confusing results when the behavior doesn't match, or when you don't want the behavior at all. For example, there would be no way to pass a literal `~/` in a flag. It also would fail to correctly handle `${HOME}` or any of the other tilde expansions: https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

Leaving the shell to interpret its own special characters and variables makes for more consistent, and predictable behavior.
