### ISSUE TITLE
0.12.1 upgrade offsets comments in maps

### ISSUE THREAD

**Issue by lookfirst** [hashicorp/terraform#21685]
Super miner issue but figured I'd report it since it wasn't expected behavior.

### Terraform Version
```
Terraform v0.12.1
+ provider.cloudflare v1.15.0
+ provider.scaleway v1.10.0
```

### Terraform Configuration Files
```hcl
 variable "addresses" {
   type = "map"
   default = {
    "0" = "foo", # foo
    "1" = "bar", # bar
    "2" = "ack", # ack
  }
 }
```

### Expected Behavior

Leave the comments on the same lines after an upgrade.

### Actual Behavior

The comments were offset by one line lower.

![image](https://user-images.githubusercontent.com/85355/59277984-5a030180-8c8b-11e9-9a35-912cad9f3a4c.png)

### Steps to Reproduce
1. `terraform 0.12upgrade`

**Comment by apparentlymart** [comment]
Hi @lookfirst! Sorry for this odd behavior and thanks for reporting it.

Due to how comments were tracked by the Terraform 0.11 configuration language parser, the upgrade tool uses a best-effort algorithm to try to place comments in a similar location as in the input, by tracking whether each construct is before or after each comment in the input using the source location information.

Unfortunately this doesn't always get exactly the right result, though the example you found here is particularly odd indeed, and not something we noticed in our testing.

These comments are supposed to be [handled as line comments attached to the items](https://github.com/hashicorp/terraform/blob/a1c1d7cad43015833f57268e8d734b281368a496/configs/configupgrade/upgrade_expr.go#L216-L221), but based on this behavior it looks like in some cases (including this one) they are not attached directly to the items and so the upgrade tool is just inserting them at the next available opportunity where "ad-hoc comments" are handled. :thinking: 

I'm sorry this happened. Given that it is (as you say) relatively minor and that we've not seen other reports of it so far, I think for the moment we'll leave this open but deprioritize it in favor of other bugs that are opened. We can see then if we see more reports of this. Thanks again!

**Comment by teamterraform** [comment]
Hi again, @lookfirst!

We didn't hear any similar reports of this problem, and we aren't planning to make any further changes to `terraform 0.12upgrade` unless we become aware of a very serious issue (that can't be worked around), so we're going to close this out now. Sorry again for this strange behavior, and thanks for reporting it.
