### ISSUE TITLE
"Attribute redefined" error when a variable is set more than once in the same .auto.tfvars file

### ISSUE THREAD

**Issue by vivanov-dp** [hashicorp/terraform#21682]
I'm getting "Attribute redefined" errors in variables.auto.tfvars files that repeat the values of some of the variables. This used to work in 0.11.14 and back and the documentation states that there shouldn't be a change in the behavior - newer values should overwrite older ones. The `validate` command also says the configuration is ok, but `apply` gives the error.

It's a hierarchical directory structure, the .auto.tfvars file is generated by a tool and the overwrites of variables are intentional. I found that if the offending variables are split in multiple .auto.tfvars files everything works, so I implemented that as a workaround in my tool, relying on alphabetical order of the files to achieve the proper overwrites.

I've prepared a minimal reproduction below.

### Terraform Version
```
v0.12.1
```

### Terraform Configuration Files

maint.tf:
```hcl
variable "test" {
    type = "string"
}
```

variables.auto.tfvars:
```hcl
test = "test1"

test = "test2"
```

### Expected Behavior
Should accept the two values and use the second one, as per documentation: https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence

### Actual Behavior
```
velko.ivanov@SOFMBL001 MINGW64 /d/prg/tftest
$ terraform_12.1.exe apply

Error: Attribute redefined

  on variables.auto.tfvars line 3:
   3: test = "test2"

The argument "test" was already set at variables.auto.tfvars:1,1-5. Each
argument may be set only once.

velko.ivanov@SOFMBL001 MINGW64 /d/prg/tftest
$ terraform_12.1.exe validate
Success! The configuration is valid.

velko.ivanov@SOFMBL001 MINGW64 /d/prg/tftest
$ terraform_11.14.exe apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce
`terraform apply`

**Comment by apparentlymart** [comment]
Hi @vivanov-dp! Thanks for reporting this and sorry for the undocumented behavior change.

This error is reported by the configuration parser itself, in an attempt to catch what tends to often be an error with confusing results: in larger files, a maintainer is likely to see the first definition of a variable and assume it's the one being used, and not notice that the same value is defined further down in the same file.

The "variable definition precedence" documentation is describing how values from the various different sources are combined, not the handling of variables from a _single_ source. As you saw, if you split the definitions across multiple separate files then Terraform will allow that, under the assumption that you're attempting to use an overriding strategy such as having a general defaults `.tfvars` file and then an environment-specific override `.tfvars` file, which is a common pattern and is intentionally still supported.

This check is an intentional feature of the configuration language parser and we don't intend to change it because it was added as a usability improvement to help catch a common user error.

For variables files generated by a tool then, we expect that the tool would handle overriding itself so that it's only generating one definition for each variable depending on its own sense of precedence. Generating multiple files and letting Terraform handle the overriding is another option, but having the tool load the intended values into a map data structure and then generate the file from a map is the more common pattern we have seen, which (due to the nature of a map data type) ensures that each name will appear only once in the output.

**Comment by vivanov-dp** [comment]
Thanks for the thorough response, @apparentlymart 

Doing it with a map is a natural solution, it's just that the tool in question is simpler at this stage and doesn't actually touch the files - it simply walks the folders, gathers files named variables-values.tf.tmpl and puts them together into a variables-values.auto.tfvars file. It does the same with variables.tf and this way I can have whatever is defined in the parent folders trickle down to the subfolders. Only a few specially marked strings get replaced with a simple string.replace() to allow for setting up different backend keys.

Anyway, since this error is the intended behavior, I will just keep the files separated and named alphabetically.

I'm leaving the issue open in case you intend to update docs based on the report - close it if you have no use of it.

**Comment by mildwonkey** [comment]
Indeed, the [override](https://www.terraform.io/docs/configuration/override.html) documentation should be updated to reflect this. Thanks!
