### ISSUE TITLE
title() function doesn't appear to work with AWS tags

### ISSUE THREAD

**Issue by wblakecannon** [hashicorp/terraform#21689]
**Terraform version v0.12.1
provider.aws v2.14.**

We use tags for cost control and organization at my company. I created an all caps variable because we use all caps for the environment tag in the AWS `Name:` tag:

```
variable "environment" {
  default = "DEV"
}
```

I used the `title()` function for the `Environment:` AWS tag:

```
resource "aws_instance" "jobserver" {
  count                   = "${var.jobservers}"
  ami                     = "${var.ami_jobserver}"
  instance_type           = "${var.instance_type}"
  subnet_id               = "${var.subnet}"
  key_name                = "${var.key}"
  security_groups         = ["${var.security_group}"]
  iam_instance_profile    = "DefaultEC2Role"
  disable_api_termination = false

  tags = {
    Name        = "${var.service}_${var.environment}_ENERGY_JOBSERVER_${count.index + 1}"
    Service     = "${title(var.service)}"
    Contact     = "${var.contact}"
    Environment = "${title(var.environment)}"
    Terraform   = "true"
  }
```

Both the output of `terraform plan` and when the instance is created, the AWS `Environment` tag still appears in all caps:

```
      + tags                         = {
          + "Contact"     = "xxxxxxx"
          + "Environment" = "DEV"
          + "Name"        = "TALEND_DEV_ENERGY_JOBSERVER_1"
          + "Service"     = "TALEND"
          + "Terraform"   = "true"
  }
```

**Comment by jbardin** [comment]
Hi @wblakecannon,

The `title` function is working as described here: https://www.terraform.io/docs/configuration/functions/title.html

> `title` converts the first letter of each word in the given string to uppercase.

Since the strings are fully uppercase, nothing is changed.

**Comment by wblakecannon** [comment]
Thank you. I guess I was assuming camel case. I will adjust my `var.tf` file to all lowercase and make use of `upper()` and `title()` according to our specs.

**Comment by apparentlymart** [comment]
It sounds like you wanted to also convert the other characters to lowercase, in which case perhaps the combination of `title` with `lower` would get the result you wanted: `title(lower(var.environment))`. Though indeed if it was camelcase you wanted then `title` cannot help with that because its definition of "word" is based on whitespace, not on underscores or other similar delimiters.

This reminds me of #18210, which added some conversion functions along the lines of what you wanted here but unfortunately collided with the language runtime switch in Terraform 0.12 and thus needs to be adapted to the new language runtime, which we've not had time to do yet.
