### ISSUE TITLE
Mechanism for incorporating manual state operations into a terraform plan

### ISSUE THREAD

**Issue by alex** [hashicorp/terraform#21686]
### Current Terraform Version
```
Terraform v0.12.1
+ provider.aws v2.14.0
+ provider.template v2.1.1
```

### Use-cases

Sometimes you refactor your terraform resources -- the classic example of this is moving something from being a top-level resource into a module.

If you perform a `terraform plan` on this, it'll result in the deletion and re-creation of all the moved resources. Luckily `terraform state mv` exists!

Unfortunately, `terraform state mv` mutates real live state. This makes it difficult to use in conjunction with a code review workflow, since generally the way I work is to write up my terraform resources, do a `terraform plan`, and send a pull request with those. Mutating production _before_ doing a pull request is a no-no, but so is sending a PR that I haven't even done a realistic `plan` on!

### Attempted Solutions
- Doing the `state mv` before submitting a pull request
- Submitting a pull request where the result is a create/delete cycle and making sure to do the `state mv` between merge and `terraform apply`.

### Proposal

Integrate `terraform state mv` into `terraform plan`. Allow me to produce a single plan file which is a combination of `mv` operations and the resource changes.

This would allow me to incorporate the `state` operations into code review, as well as provide a very readable plan file.

**Comment by apparentlymart** [comment]
Hi @alex! Thanks for reporting this.

There is another issue open covering a similar idea, though I wasn't able to find it quickly to post here... I will dig it up later and link it.

What you're proposing here though is indeed a goal, which I'd express succinctly as: any change made to state or to real infrastructure should be preformed via the normal `terraform apply` flow.

The candidate design (awaiting further prototyping) is to record such changes in the configuration as special "refactoring" blocks, which might look something like this: (I'm doing this from memory since I don't have the other issue handy, so I may have some details wrong)

```hcl
refactoring {
  move "1da87d53-ec68-4148-9d55-2704dba31ed3" {
    from = aws_instance.foo
    to   = aws_instance.bar
  }
}
```

This `move` block would then serve as a hint to the Terraform plan generator that if it would normally have generated a plan to remove `aws_instance.foo` and create `aws_instance.bar` then it should instead generate a plan to just rename the instance.

The UUID in the header is a change-tracking id which would be recorded in the Terraform state after the change is applied, for as long as this block still remains in the configuration, to allow the same refactoring to be rolled out across multiple different environments without causing problems for the environments where it was already provided. Once the change has been applied everywhere, the block can then be removed at your leisure and the next apply will then follow suit and remove it from the state.

Because generating those uuids would be annoying, the thought is that we'd make a `terraform mv` command that would do all of the configuration manipulations: actually rename the `resource` block _and_ generate the `move` refactoring block as shown above.

This is all just a design sketch so far and we've not actually built a real prototype, so building a real prototype to try this out and see how it feels in practice will be the next step. Unfortunately we won't be able to do more work on this in the near future because other work is taking priority, but we do intend to make changes to align better with the principle that `terraform apply` is the primary way to make changes.

**Comment by alex** [comment]
It sounds like the design you're considering precisely solves the issue I'm encountering, great to hear it!

That's too bad that you won't be able to work on this in the near future, but thank you for the prompt reply.

**Comment by apparentlymart** [comment]
Hi @alex,

After a more careful second search I found #16860 as the issue I was thinking of. I re-titled it to make it a more direct description of the problem at hand so we can find it more easily next time, and I'm going to close this one now just to consolidate the discussion. Thanks!
