### ISSUE TITLE
Cannot get rid of warning for inconsistent plan in simple provider

### ISSUE THREAD

**Issue by jerome-quere** [hashicorp/terraform#21694]
### Terraform Version
```
Terraform v0.12.1
```

### Description
When updating a tf file with a simple custom provider

from 
```
resource "test_server" "base" {
	address = "1.1.1.1"
}
```
to 
```
resource "test_server" "base" {
}
```

I cannot get rid of the  inconsistent plan warning in a simple provider
```
Provider "test" produced an unexpected new value for test_server.base, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .address: was null, but now cty.StringVal("")
```

### Steps to Reproduce

https://github.com/jerome-quere/terraform-provider-test

**Comment by jbardin** [comment]
Hi @jerome-quere,

This is an unfortunate shortcoming of the legacy SDK, as it cannot always differentiate between empty strings an unset values. While we could possibly remove the empty string in simple cases during apply, it would be immediately re-added during a subsequent Read. We often need to ensure that we follow the old behavior as closely as possible, even when it may not be optimal, because many providers are relaying on the behavior provided by the the SDK.

We don't expect providers to be able to avoid all warnings presented by Terraform 0.12 when using the legacy SDK, but they do provide an invaluable reference when attempting to track down bugs in their resources. So while the warning itself is not a concern, the particular issue being warned about may require further investigation to prevent errors when users attempt to reference attributes that weren't possibly `null` in the past.

**Comment by jerome-quere** [comment]
Hi @jbardin,

TY for your answer but if this is a legacy SDK, I could not find any documentation on how to use the latest one.

I used
```
require github.com/hashicorp/terraform v0.12.1
```

**Comment by jbardin** [comment]
That's a good question @jerome-quere! 
The current SDK is often referred to as being "legacy" because it does not directly match up with the new core plugin protocol, nor does it support the new type system in terraform. It still is however the current SDK for providers while work is being done on a replacement.

**Comment by jbardin** [comment]
We have merged a fix for the simple case with primitive attributes in #21721, which takes care of this specific issue. 

Unexpected changes with more complex types are not always solvable, which is why this remains a warning with the existing SDK.

**Comment by jbardin** [comment]
Hi @jerome-quere,

Just to update on this issue, I'm reverting the change that removes the extra values from the apply, since it's turns out to be too disruptive to existing providers dependent on the old behavior. I'm going to leave this closed, since there's not really anything we can do about all the warnings from the legacy SDK, but you should expect to see these particular warnings back from the SDK after updating.
