### ISSUE TITLE
Defining object collection value in modules

### ISSUE THREAD

**Issue by astorath** [hashicorp/terraform#21716]
### Current Terraform Version
```
Terraform v0.12.2
+ provider.external v1.1.2
+ provider.google v2.7.0
```

### Use-cases
-  using recommended way to define object collection in modules [see docs](https://www.terraform.io/docs/configuration/attr-as-blocks.html#defining-a-fixed-object-collection-value)
- using **dynamic** block syntax in modules

E.g.:
```hcl
module "gce_vm_es2" {
  source = "../modules/gce-vm"
  name   = "es-sandbox"
  env    = "sandbox"

  image          = "centos-cloud/centos-7"
  machine_type   = "n1-standard-1"
  gce_subnetwork = "infra-mgmt"

  attached_disk {
    device_name = "data"
    type        = "pd-standard"
    size        = "20"
  }
  attached_disk {
    device_name = "backup"
    type        = "pd-standard"
    size        = "20"
  }
}
```

### Attempted Solutions
1. Before 0.12 this was *undocumented feature* and worked well enough
2. 0.12 breaks this pattern in favor of argument syntax:
```
Error: Unsupported block type

  on elastic.tf line 38, in module "gce_vm_es2":
  38:   attached_disk {

Blocks of type "attached_disk" are not expected here. Did you mean to define
argument "attached_disk"? If so, use the equals sign to assign it a value.
```
3. So now we have to:
```hcl
module "gce_vm_es2" {
  source = "../modules/gce-vm"
  name   = "es-sandbox"
  env    = "sandbox"

  image          = "centos-cloud/centos-7"
  machine_type   = "n1-standard-1"

  attached_disk = list({
    device_name = "data"
    type        = "pd-standard"
    size        = "20"
    }, {
    device_name = "backup"
    type        = "pd-standard"
    size        = "20"
  })
}
```

### Proposal
- Allow using both syntax (Argument Syntax and Block Syntax)
- Document this change or future plans about changing it

**Comment by apparentlymart** [comment]
Hi @astorath! Thanks for opening this feature request.

In Terraform 0.12, nested block syntax has a special meaning in how the contents are processed: each argument inside is validated separately, may separately have its own default values, etc. That was also the intent in Terraform 0.11, though as you saw the configuration language parser failed to validate it.

Terraform 0.12's parser must be stricter here because it needs to understand which construct is being used in order to correctly interpret the characters between the braces: an object constructor (which is what the `{ ... }` construct means in an expression) allows for the `for` expression syntax and for arbitrary expressions as keys, while a nested block has a static set of supported arguments which must be written literally in the configuration.

Therefore we had to fix the validation bug that allowed this to work in Terraform 0.11 in order to fix what would otherwise have been a language ambiguity that would've prevented Terraform from generating good error messages for incorrect usage, because the intent would not be clear.

Because variables are just values, they are each assigned using a single expression in order for various other semantics to be reasonable. For example, if a variable isn't set then its default value might be used or we might return an error. It isn't meaningful to ask whether a nested block "is set", because each nested block is a separate object, and so the only meaningful question is how many blocks there are.

With that said, we don't have any plans to support using the nested block syntax for assigning module variable values because it would add no additional meaning compared to using a list of objects, as previously discussed in #3388. Where possible we prefer to have only one canonical way to write a given idea in Terraform configuration, and use different syntax only when there is some difference in behavior or semantics to communicate.

Thanks again for opening this issue! I'm going to close it because we don't have any current plans to support block syntax as an alias for argument syntax in this context. In future block syntax may take on a _separate_ meaning inside `module` blocks for additional features, but there are no specific features planned that would do so, and so we'll wait until such features are better defined before opening issues for them.

**Comment by astorath** [comment]
That is sad :( 
Thanks for reply!
