### ISSUE TITLE
Upgraded to v0.12.2 - terraform init returns "Error: Failed to read modules manifest file"

### ISSUE THREAD

**Issue by Aussie007** [hashicorp/terraform#21730]
### Terraform Version

```
Terraform v0.12.2
+ provider.aws v2.12.0
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

ran terraform init after upgrading to v0.12.2

Initializing modules...

Error: Failed to read modules manifest file

Error reading manifest for .terraform\modules: snapshot file contains two
records for path 1.module_stack;../../modules/module_stack.

### Expected Behavior

terraform init complete with no errors and ouput the message as per upgrade doc page:

Terraform has initialized, but configuration upgrades may be needed.

### Actual Behavior

terraform init fails with above output 
### Steps to Reproduce

upgrade terraform.exe from v0.11.14 to v0.12.2
run terraform init

**Comment by apparentlymart** [comment]
Hi @Aussie007! Sorry for this odd behavior, and thanks for reporting it.

It seems that somehow a previous version of Terraform generated an invalid manifest of modules (in the `.terraform/modules` directory) which 0.11.14 was tolerating but 0.12.2 is detecting as an error. We've not seen an invalid manifest like this before, but I think Terraform 0.12.2 is correct to flag it because the same module being recorded multiple times makes the manifest ambiguous.

As a workaround, I'd suggest deleting the `.terraform/modules` directory so that Terraform 0.12.2 will then recreate it from scratch rather than trying to update the existing manifest. Hopefully that will avoid Terraform 0.12.2 from encountering the invalid entry and thus allow `terraform init` to complete successfully by re-installing the modules fresh.

**Comment by Aussie007** [comment]
Hi @apparentlymart 

thanks for the quick reply.

That is exactly what I did - deleted the modules folder and ran terraform init again.

For you reference the modules.json contained the following:

{"Modules":[{"Source":"../../modules/eks_stack","Key":"1.eks_stack;../../modules/eks_stack","Version":"","Dir":".terraform/modules/35c9e3ddf00a28772ca542c53a25755c","Root":""},{"Source":"../../modules/eks_stack","Key":"1.eks_stack;../../modules/eks_stack","Version":"","Dir":".terraform/modules/35c9e3ddf00a28772ca542c53a25755c","Root":""},{"Source":"../../modules/eks_stack","Key":"1.eks_stack;../../modules/eks_stack","Version":"","Dir":".terraform/modules/35c9e3ddf00a28772ca542c53a25755c","Root":""},{"Source":"../../modules/eks_stack","Key":"1.eks_stack;../../modules/eks_stack","Version":"","Dir":".terraform/modules/35c9e3ddf00a28772ca542c53a25755c","Root":""},{"Source":"../../modules/eks_stack","Key":"1.eks_stack;../../modules/eks_stack","Version":"","Dir":".terraform/modules/35c9e3ddf00a28772ca542c53a25755c","Root":""}]}


After deleting the modules folder and running terraform init, the newly created modules.json file contained:

{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"eks_stack","Source":"../../modules/eks_stack","Dir":"..\\..\\modules\\eks_stack"}]}


Many thanks
