### ISSUE TITLE
templating for loop miss the implicit loop index

### ISSUE THREAD

**Issue by omerlin** [hashicorp/terraform#21732]
### Current Terraform Version
v0.12.2

### Use-cases
Unable to find a way to get the loop index in a for loop function in a HCL template

### Attempted Solutions
I didn't found any workaround to get the index of the loop in a template for loop function called by a templatefile() call.
This is a big limitation.
I wanted to generate the host.ini file of ansible using something like :

```
resource "local_file" "ansible_hosts" {
  content = templatefile( "templates/gen_hosts.tpl", {
    master_ips = var.map_master_ips
    worker_ips = var.worker_ips
    prefix     = var.vm_name_prefix
    user       = var.vm_user
  })
  filename = "config/hosts.ini"
}
```

 

### Proposal
something similar to the iterate() function in python gives the index as first element
so we could have in template file:
```
%{ for index,ip in iterate(master_ips) ~}
${prefix}-master-${index} ansible_host=${ip} ansible_user=${user}
%{ endfor }
```
 

### References
No reference

**Comment by apparentlymart** [comment]
Hi @omerlin! Thanks for sharing this feature request.

I think I'm missing something about the request, because what you suggested here should already be the natural behavior of iterating over a list, without requiring any special function:

```
%{ for index, ip in master_ips ~}
${prefix}-master-${index} ansible_host=${ip} ansible_user=${user}
%{ endfor }
```

If `master_ips` is of a _different_ collection type (a map or a set) then its keys will not be indices, because those types don't have a natural ordering, but you can get that result by performing some operation that will convert the collection into a list in some specific order, such as by passing a set to the `sort(...)` function to sort the elements lexically.

If the above doesn't help, could you please share some more information about what happened when you tried the configuration you included under "Attempted Solutions"? I think that will help us better understand how what you are proposing is different than the current behavior. Thanks!

**Comment by omerlin** [comment]
Hi Martin,
Sorry you are right - this syntax work as expected ! This is exactly what i
needed to simplify all my code
In fact i didn't see this kind of examples with indices in the template
loop ... so i imagined and tried other alternatives - but not the simplest
one 😂
Thanks a lot for your quick answer and for the very good job
cheers
Olivier

Le ven. 14 juin 2019 à 20:15, Martin Atkins <notifications@github.com> a
écrit :

**Comment by omerlin** [comment]
Hi Martin,
just one remark that anyway could help enhance the template generation with the for loop  ...
The loop:
```
%{ for index, ip in master_ips ~}
${prefix}-master-${index} ansible_host=${ip} ansible_user=${user}
%{ endfor }
```
generate an extra \n (LF) at the end of the loop
So if you have several loops - you have blank lines in between which is i think not expected.
In my case this is not a problem but for sure will be in the future i bet

**Comment by apparentlymart** [comment]
Thanks for confirming, @omerlin! Since what you requested is already possible I'm going to close this.

If you put a `~` at the end of the `endfor` marker then you can avoid the final newline:

```hcl
%{ endfor ~}
```
