### ISSUE TITLE
terraform plan produces invalid hcl when there are colons in property identifiers

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#21749]
### Terraform Version
```
Terraform v0.12.1
+ provider.aws v2.13.0
```

### Steps to Reproduce
I created a `resource "aws_iam_role"` with an `assume_role_policy` which changed. Part of that role policy had a key called `SAML:aud`. That key needs to be quoted in order to be valid in the plan output, but it was not.

![image](https://user-images.githubusercontent.com/235410/59599285-76c18e00-90fe-11e9-982c-8f84393a37c5.png)

### Additional Context

Since the plan output is not actually meant to be used directly it shouldn't matter, but this may reflect a deeper potential issue with unquoted keys / keys with colons / etc.

**Comment by apparentlymart** [comment]
Hi @jleclanche! Thanks for reporting this.

Indeed this output is only configuration-language-like to aid in human understanding, and so this bug is just cosmetic in the renderer, but it would be better for the renderer to detect when the key isn't a valid identifier and render it in quotes as it would be in configuration input.

Because it is just a cosmetic thing we won't be able to prioritize working on this right now -- there are some other 0.12-related bugs we're working through already -- but we'll leave this on the list as something to polish at a later time. Thanks again!

**Comment by jleclanche** [comment]
@apparentlymart One concern is that whatever generates this output may be used elsewhere and the same bug will surface in situations where it'll actually be a problem, but I didn't look at the code to double check.

**Comment by apparentlymart** [comment]
Hi @jleclanche,

The code in question here is only ever used to produce output for human consumption. We don't use that codepath to create output for machine consumption; all of the machine-readable output codepaths produce JSON instead.
