### ISSUE TITLE
Add pretty print option to jsonencode

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform#21755]
### Current Terraform Version

```
Terraform v0.12.2
```

### Use-cases

I use jsonencode to create JSON config.

Often, I want to keep that in a readable form, rather than have it on one line with all spaces removed.

### Attempted Solutions

I could use a inline or file template.

However, that lacks the automatic escaping, syntax validation, etc., that I have with jsonencode.

### Proposal

Add an optional argument to `jsonencode({ a = 1 }, "pretty")`

**Comment by apparentlymart** [comment]
Hi @pauldraper! Thanks for opening this feature request.

For things like this we must always make a cost/benefit tradeoff of the complexity of supporting multiple options rather than having just one behavior that works "well enough" for most cases. In this case, we offer the `jsonencode` function primarily as a way to prepare data for machine consumption rather than human consumption, and I believe that is why it uses the compact serialization. We'd rather keep this function simple and have only one case rather than introducing the complexity of multiple modes.

As a compromise, in Terraform 0.12 we added a special mode to the rendered plan output where it will detect if a string seems to contain a JSON object or array and will decode the object to render it in a formatted way. This means that the compactly-serialized JSON can still be reviewed by humans during planning, even though it'll be compact in the remote system. That was the intentional compromise we made right now to address the immediate concern of unreadable plans without adding complexity to the `jsonencode` function.

With that said, I don't think we want to add another mode to `jsonencode`, since it would make the interface and behavior of this function more complex and thus add more language surface area for a reader to understand when reading an existing configuration. If we were implementing this function from scratch today I expect we'd probably have made it generate indented output by default as a compromise for human readability without hurting machine consumption, but we cannot make that change today without breaking compatibility, but software that presents JSON to humans these days will often do its own formatting (similar to what `terraform plan` does), and even if it doesn't there are tools readily available to format arbitrary JSON.

Thank you again for sharing this use-case. I hope the above context helps to explain why in this case we don't plan to address it directly.

**Comment by pauldraper** [comment]
Alright

**Comment by apparentlymart** [comment]
Should someone be motivated enough to develop a more complicated JSON serializing function for Terraform, they can now do it in a provider plugin using [Terraform v1.8's support for provider-defined functions](https://www.hashicorp.com/blog/terraform-1-8-improves-extensibility-with-provider-defined-functions).

Terraform's built-in functions are focused on tightly solving very common use-cases, but the ability to extend Terraform with other functions using provider plugins means that those with different needs can build either functions that force different opinions than Terraform's do such as forcing indentation and wrapping for JSON, or can provide more elaborate options for customizing behavior such as offering an object argument that accepts a bag of tweakable settings.
