### ISSUE TITLE
integer division no longer returns an integer

### ISSUE THREAD

**Issue by pmcevoy** [hashicorp/terraform#21751]
### Terraform Version
Terraform v0.12.1

With terraform 0.11,  `1 / 2` would yield `0`:

```
[master ≡ +35 ~27 -0 !]> . C:\tools\terraform_0.11\terraform.exe console
> 1 / 2
0
```

With, 0.12 it now yields `0.5`:
```
[master ≡ +35 ~27 -0 !]> . C:\tools\terraform_0.12\terraform.exe console
> 1 / 2
0.5
```

### Additional Context
The v11 docs indicate that for Simple Math, but this seems to be a regression for 0.12

> The supported operations are:
> Add (+), Subtract (-), Multiply (*), and Divide (/) for float types
> Add (+), Subtract (-), Multiply (*), Divide (/), and Modulo (%) for integer types

In the absence of `for_each` and nested looping constructs in 0.11, it was possible to use integer `div` and `mod` behaviour with a single `count` index so simulate a nested loop.  

### Work around:
```
floor( 1 /  2 )
```
But I hope that works in all scenarios

**Comment by jbardin** [comment]
Hi @pmcevoy,

Sorry this tripped you up. The 0.12 upgrade guides covers this topic here: https://www.terraform.io/upgrade-guides/0-12.html#integer-vs-float-number-types

Terraform no longer assumes integer division in the configuration, but since the upgrade tool cannot infer your intent, this is a point that needs to be manually updated to match the current behavior.

**Comment by pmcevoy** [comment]
@jbardin Thanks for super-quick reply and sorry for wasting your time on already documented issue - I guess once my initial upgrade was done, I didn't think to look at the upgrade docs again..
