### ISSUE TITLE
`terraform state show ADDR` outputs ANSI sequences

### ISSUE THREAD

**Issue by abitrolly** [hashicorp/terraform#21779]
### Terraform Version

```
Terraform v0.12.2
+ provider.aws v2.12.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Actual Behavior

```
✗ cat testtf.py     
#!/usr/bin/env python3

from subprocess import check_output

out = check_output('terraform state show aws_security_group.allow_ssh', shell=True)
print(out)
```
```
✗ ./testtf.py 
b'# aws_security_group.allow_ssh: \nresource "aws_security_group" "allow_ssh" {\n    \x1b[1m\x1b[0marn\x1b[0m\x1b[0m                    = "arn:aws:ec2:us-east-1:71897290:security-group/sg-09570458c5"\n    \x1b[1m\x1b[0mdescription\x1b[0m\x1b[0m            = "Allow SSH via 22 (standart)"\n    \x1b[1m\x1b[0megress\x1b[0m\x1b[0m                 = []\n    \x1b[1m\x1b[0mid\x1b[0m\x1b[0m                     = "sg-09570458c5"\n    \x1b[1m\x1b[0mingress\x1b[0m\x1b[0m                = [\n        {\n            cidr_blocks      = [\n                "0.0.0.0/0",\n            ]\n            description      = ""\n            from_port        = 22\n            ipv6_cidr_blocks = []\n            prefix_list_ids  = []\n            protocol         = "tcp"\n            security_groups  = []\n            self             = false\n            to_port          = 22\n        },\n    ]\n    \x1b[1m\x1b[0mname\x1b[0m\x1b[0m                   = "allow_ssh"\n    \x1b[1m\x1b[0mowner_id\x1b[0m\x1b[0m               = "71897290"\n    \x1b[1m\x1b[0mrevoke_rules_on_delete\x1b[0m\x1b[0m = false\n    \x1b[1m\x1b[0mtags\x1b[0m\x1b[0m                   = {}\n    \x1b[1m\x1b[0mvpc_id\x1b[0m\x1b[0m                 = "vpc-d99a3"\n\n    timeouts {}\n}\n\n\x1b[0m\x1b[0m\n'
```

### Expected Behavior

```
# aws_security_group.allow_ssh: 
resource "aws_security_group" "allow_ssh" {
    arn                    = "arn:aws:ec2:us-east-1:...:security-group/sg-..."
    description            = "Allow SSH via 22 (standart)"
    egress                 = []
    id                     = "sg-..."
    ingress                = [
        {
            cidr_blocks      = [
                "0.0.0.0/0",
            ]
            description      = ""
            from_port        = 22
            ipv6_cidr_blocks = []
            prefix_list_ids  = []
            protocol         = "tcp"
            security_groups  = []
            self             = false
            to_port          = 22
        },
    ]
    name                   = "allow_ssh"
    owner_id               = "..."
    revoke_rules_on_delete = false
    tags                   = {}
    vpc_id                 = "vpc-..."

    timeouts {}
}
```

### Additional Context

I wrote parser for `terraform state show` to generate Ansible inventory, but I didn't expect to deal with ANSI sequences.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @abitrolly.

The `terraform state show` output is intended for human consumption via a terminal rather than for machine consumption, so it's subject to change at any time to improve Terraform's UI. With that said, if it's going to include escape sequences in its output then it should support the same `-no-color` option we support on other commands that generate escape sequences, so I think this issue will represent making sure that option works for this command so that escape sequences can be disabled in scenarios where they aren't appropriate, such as capturing Terraform output into log systems that don't support terminal sequences.

Terraform 0.12 introduced [`terraform show -json`](https://www.terraform.io/docs/commands/show.html#json) as a machine-oriented way to look at the state in [a JSON format](https://www.terraform.io/docs/internals/json-format.html#state-representation). If possible I'd recommend using that command to obtain state data for further analysis; although its structure is still subject to change for the moment as we gather feedback on it, we intend to be very conservative about changes and eventually make compatibility promises about it.

**Comment by abitrolly** [comment]
@apparentlymart when I execute `state show ADDR` from my terminal, I don't see any colors. Why ANSI colors appear when I run the command through the script?

I took a second look at `terraform show -json` format. It is less friendly for humans and I need to pass it through `jq .` to make sense of it, but it looks like it is much easier to parse. I will try it.

**Comment by 007** [comment]
@abitrolly The ANSI escapes that it's outputting are all "resets", where they set the state back to default / nocolor / nohighlight / etc. So the effect on a terminal that has no existing state is a no-op. To illustrate:
```
tput setaf 2;echo "this is green";echo "this is still green?"
```
shows two green lines, versus
```
tput setaf 2;echo "this is green";terraform state show $SOMETHING;echo "this is still green?"
```
Which shows one green line, one green line of the resource, and then resets to terminal-default for the rest of the lines and the `green?`.

@apparentlymart In 0.12 is there any way to reproduce `terraform state show` in a way that is machine-consumable? Or a way to get `-json` as an option for `state show` instead of just `show`?

**Comment by ausfestivus** [comment]
Ive put this issue on the radar of our SE to see if we can get this issue under the nose of the product manager for consideration in 0.12.7. Hopefully thats the correct way to get this issue some visibility.

Ive got some chunky import work in the pipe and this issue is going to bite the customers plans.

**Comment by dohoangkhiem** [comment]
`terraform state show -json` would be much convenient.

**Comment by camerondavison** [comment]
a lot of the other commands have the `-no-color` option, it seems like even if the json option exists it would still be good to support a no color option.

I have been running it throw a sed operation to remove all the ANSI chars so that I can copy paste it into tickets and other places.

**Comment by tdmalone** [comment]
Further to @007's comment above on the docs for `state show`, the help shown for `terraform state -h` also states:

> The structure and output of the commands is specifically tailored to work
> well with the common Unix utilities such as grep, awk, etc. We recommend
> using those tools to perform more advanced state tasks.

We have a script that has been doing exactly that, and has broken after the upgrade to 0.12. While changes in output are not unexpected, debugging our `grep`s to find out they were failing due to invisible ANSI colour codes _was_ unexpected 😅 

If these commands are no longer designed to be used programmatically, the help and docs should be updated to note that. But, a `-no-color` option would be excellent too!

(And yes - we will eventually rewrite to use `terraform show -json` and parse appropriately, was just hoping to at least make some slight changes to existing scripts first).

**Comment by tdmalone** [comment]
Workaround:
```terraform state show "your_resource_address" | sed -Ee 's/\x1B\[[0-1]m//g'```
(disclaimer: YMMV, depending on your version of sed)

**Comment by abitrolly** [comment]
It would be more fun if it could be sponsored by my employee (and I don't have any), but it looks like I could probably write a patch for it. 

https://github.com/hashicorp/terraform/blob/master/command/state_show.go#L131

There might be a bug that even if the `Color` is disabled for `state show`, it still outputs the invisible sequences. Or just explicitly hardcode color disability here.

**Comment by trycrmr** [comment]
On terraform v0.13.7, and `terraform state show -no-color [resource]`, like `terraform state show -no-color aws_cloudwatch_metric_alarm.test-cloudwatch-alarm` doesn't output the problematic ANSI characters for me 😺 . 

It is a bit confusing though because terraform -help state show doesn't describe that option 🤷🏻 : 
```
user@03:50 PM:terraform$ tf -help state show # tf is a bash alias to terraform
Usage: terraform state show [options] ADDRESS

  Shows the attributes of a resource in the Terraform state.

  This command shows the attributes of a single resource in the Terraform
  state. The address argument must be used to specify a single resource.
  You can view the list of available resources with "terraform state list".

Options:

  -state=statefile    Path to a Terraform state file to use to look
                      up Terraform-managed resources. By default it will
                      use the state "terraform.tfstate" if it exists.

```

**Comment by ppar** [comment]
This problem still exists on terraform 1.1.9, the latest version.

**Expected behaviour**
- terraform doesn't write control characters to output _that is intended for machine parsing_
- Features that _can print_ ANSI control characters, _disable_ them automatically when STDOUT is not a terminal (i.e. when output is piped to another program). This common and de facto standard behavior in grep, ls, git, etc. etc.
- Available command line arguments are documented

**Actual behaviour**
- Running `terraform state show <ADDR>` outputs invisible ANSI control characters:
  ```
  $ ~/Downloads/terraform state show hetznerdns_zone.my_name | grep id | od -ax
  0000000  sp  sp  sp  sp esc   [   1   m esc   [   0   m   i   d esc   [
  2020    2020    5b1b    6d31    5b1b    6d30    6469    5b1b
  0000020   0   m esc   [   0   m  sp  sp  sp   =  sp   "   y   c   A   s
  6d30    5b1b    6d30    2020    3d20    2220    6379    7341
  ```
- Despite the above behaviour, `terraform  -help state` prints out a text which includes the following 
  promise: 
    - "**The structure and output of the commands is specifically 
      tailored to work well with the common Unix utilities such as grep, awk, etc. We recommend
      using those tools to perform more advanced state tasks.**". 
- The help text does not document the `-no-color` option at all.

**Related suggestion**
- Please provide an option to print out the state in JSON format. The `jq` tool has been ubiquitous for quite a while, as is the skill to quickly write robust parses using it. OTOH, parsing the custom output requires pulling out grep, sed, awk and friends and spending time on ad-hoc parsers.

**Comment by apparentlymart** [comment]
Hi all,

Just checking in on some old issues to see if the situation has changed since we last looked at them.

For a long while now we've supported a JSON format for state produced by the following command:

```
terraform show -json
```

The documentation for the structure of that output is in [JSON Output Format](https://www.terraform.io/internals/json-format). "State Representation" in particular is the format produced by the above command.

In modern Terraform, no command produces machine-oriented output without an explicit command line option to enable that. Any documentation or messages that suggest otherwise are incorrect. I do see the incorrect message in `terraform state -help`, and so I'm going to open a fresh issue representing just that so we don't lose that detail in this old issue. However, I'm going to close this issue since I believe the JSON state output addresses the use-case of obtaining state data in a way that's suitable for machine processing.
