### ISSUE TITLE
State snapshot Conflict after upgrading from 0.12.1 to 0.12.2

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform#21773]
### Terraform Version

```
0.12.1 to 0.12.2
```

### Terraform Configuration Files
```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    workspaces { name = "ceng-eks-dev" }
    organization = "name"
  }
}
```

### Crash Output

```
Failed to save state: Error uploading state: Conflict

The MD5 hash of the state provided does not match what is currently
known for the same serial number


Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```
### Actual Behavior

Erroring with conflicts when trying to run with an upgraded version;

```
terraform init -backend-config=backend_configs/test.backend && terraform validate && terraform apply -var-file=vars/test.tfvars
```

### Additional

I am simply trying to upgrade my terraform version from 0.12.1 to 0.12.2. After upgrading it I am getting a conflict and I can't push our state to remote storage (terraform cloud). 

Please advise

**Comment by apparentlymart** [comment]
Hi @marcincuber! Sorry for this odd behavior, and thanks for reporting it.

I think the first order of business here is to make sure you were able to get back into a consistent state. Did running `terraform state push errored.tfstate` as suggested succeed, or did you see the same error again?

If you _did_ see the same error again, then I think the following workaround should work, to let Terraform Cloud know that the state is supposed to have changed: open the `errored.tfstate` file in an editor and locate the top-level `"serial"` property and increment it. Then try running the `terraform state push errored.tfstate` command again, which should now succeed because it's no longer "the same serial number", as the error message mentioned.

I think once the errored state is pushed back up to Terraform Cloud, everything should work okay again. That then leaves the question of how this happened in the first place...

---

The check in question here is a safety check made by Terraform Cloud to protect against inconsistent state updates. Specifically, Terraform Cloud by default requires that after an initial state snapshot is created every subsequent state snapshot must have the same `"lineage"` value, and a greater `"serial"` value. The same lineage+serial pair can only be reused if the content of the snapshot is byte-for-byte identical.

Therefore this message would seem to suggest that somehow Terraform tried to submit a different snapshot with the same serial. I suspect this arose because of #21380, where we fixed a bug where Terraform would sometimes fail to update the `terraform_version` setting when saving a snapshot. The `terraform_version` property is header metadata and thus not included in the check for whether the state changed, and so I think the state manager therefore didn't detect that as a change and update the serial.

However, this situation should only occur if Terraform were trying to write a state that was otherwise identical to the previous state, and thus if this explanation is correct no data loss would occur: if anything changed in the body of the state snapshot then Terraform would detect the change and increment the serial as expected.

I think perhaps the most straightforward fix here is for Terraform to just skip sending the state to the server if it doesn't detect any changes. Currently it seems that Terraform will re-send the state in `terraform apply` even if nothing has changed, which ought to be a harmless thing to do (this change-detection bug notwithstanding) but is also unnecessary. If we were to skip submitting the change in that case, we'd avoid re-serializing the same data using a newer version of Terraform and thus tripping this Terraform Cloud consistency check.

**Comment by marcincuber** [comment]
Thanks for very comprehensive explanation and all the detailed information.

To answer your question; running `terraform state push errored.tfstate` fails with the same error. 

I will be test the upgrade tomorrow and update this comment once I confirm that the workaround worked.

**Comment by apparentlymart** [comment]
Unfortunately the "header information" in the state snapshot belongs only to the snapshot and not to the state itself, so it's processed only when loading the snapshot and isn't available when re-serializing it later. This is one of the crucial differences between "the state" (a mutable data structure) and a state _snapshot_ (an immutable snapshot of the state at a particular point in time), and it would be very invasive to change that behavior.

The other option would be to change the server-side check to only consider the body of the snapshot (the state data itself) in this check, but the server currently isn't deeply aware of the state structure and just does a byte-for-byte comparison, and so I expect the Terraform Cloud team would not want to introduce a lot of extra awareness about the state format into it that would then cause it to be more tightly coupled with particular releases of Terraform Core.

Submitting unchanged state to the server doesn't really serve any purpose and to stop doing it is the least risky change here. When it comes to fixing bugs (as opposed to implementing new features or making architecture changes), we prefer to take the simplest and least risky option to reduce the risk of introducing other regressions at the same time. That doesn't mean this can't change again in a future release, but right now the priority is addressing this issue quickly so that this problem won't occur on each future Terraform CLI upgrade.

**Comment by marcincuber** [comment]
As promised, I did what you (@apparentlymart) suggested and it worked. 

So summarising the **solution/workaround:** 
1. After upgrading terraform version and running terraform apply, pushing new state failed with above errors. It locked the workspace so that had to be unlocked manually.
2. Running  `terraform state push errored.tfstate` errored with the same error as previously.
3. As suggested by @apparentlymart, I had to open the errored.tfstate file in an editor and locate the top-level "serial" property and increment it.
4. Run `terraform state push errored.tfstate` again after incrementing the serial.

Everything works as expected now.

Regarding the fix, I agreed based on your explanations that the most straightforward fix here is for Terraform to just skip sending the state to the server if it doesn't detect any changes.

And again many thanks.
