### ISSUE TITLE
Terraform validate missing options present in 0.11

### ISSUE THREAD

**Issue by RommelLayco** [hashicorp/terraform#21790]
### Terraform Version

```
0.12.2
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

terraform validate missing options
### Expected Behavior

Terraform to display the following
```
Usage: terraform validate [options] [dir]

By default, validate requires no flags and looks in the current directory for the configurations.

The command-line flags are all optional. The available flags are:

-check-variables=true - If set to true (default), the command will check whether all required variables have been specified.

-no-color - Disables output with coloring.

-var 'foo=bar' - Set a variable in the Terraform configuration. This flag can be set multiple times. Variable values are interpreted as HCL, so list and map values can be specified via this flag.

-var-file=foo - Set variables in the Terraform configuration from a variable file. If "terraform.tfvars" is present, it will be automatically loaded first. Any files specified by -var-file override any values in a "terraform.tfvars". This flag can be used multiple times.
```

### Actual Behavior

Terraform only displays the following
```
Usage: terraform validate [options] [dir]

  Validate the configuration files in a directory, referring only to the
  configuration and not accessing any remote services such as remote state,
  provider APIs, etc.

  Validate runs checks that verify whether a configuration is
  internally-consistent, regardless of any provided variables or existing
  state. It is thus primarily useful for general verification of reusable
  modules, including correctness of attribute names and value types.

  It is safe to run this command automatically, for example as a post-save
  check in a text editor or as a test step for a re-usable module in a CI
  system.

  Validation requires an initialized working directory with any referenced
  plugins and modules installed. To initialize a working directory for
  validation without accessing any configured remote backend, use:
      terraform init -backend=false

  If dir is not specified, then the current directory will be used.

  To verify configuration in the context of a particular run (a particular
  target workspace, operation variables, etc), use the terraform plan
  subcommand instead, which includes an implied validation check.

Options:

  -json        Produce output in a machine-readable JSON format, suitable for
               use in e.g. text editor integrations.
```
As show in this documentation https://www.terraform.io/docs/commands/validate.html

### Steps to Reproduce

1. `terraform validate --help`

**Comment by apparentlymart** [comment]
Hi @RommelLayco! Thanks for reporting this.

The issue is that the documentation has not been updated to reflect what has changed in Terraform 0.12. The documentation is currently intended to cover both 0.11 and 0.12 possibilities, but this particular page is lacking annotations for the fact that the scope of this command was reduced in Terraform 0.12, as mentioned in the "incompatibilities and notes" section of [the 0.12.0 changelog](https://github.com/hashicorp/terraform/blob/v0.12.0/CHANGELOG.md).

We'll get the documentation updated to note the different behaviors of this command in Terraform v0.12.

**Comment by apparentlymart** [comment]
Seeing the referencing issue cloudposse/terraform-aws-cloudtrail#24, I can see that it's `-check-variables=false` you are mainly worried about here.

`-check-variables=false` is now the only behavior available for `terraform validate`, so removing that option entirely will get the equivalent behavior. `terraform validate` checks if the module implementation itself is valid, not whether a particular plan for it is valid. Variables are part of a plan rather than part of the module itself, so `terraform validate` does not do any checks of their values. (it does, however, detect if they are being _used_ consistently in the module, such as producing an error if a string variable is used where a list is expected.)

**Comment by adrianbn** [comment]
@apparentlymart, 

we run into this problem as well. We were relying on the old `--check-variables=false` behaviour to not fail when a variable is not defined in a sub-module. For example, we have a top level module that will instantiate all the other submodules required to create our configuration, so many of our modules define variables such as `variable "region" {}`. The variables will be defined by the instantiating module, not in the submodule where `terraform validate` is being run. 

We would like to be able to invoke the old behaviour so that we can have a quick `validate` of the submodules upon changes upon changing the code.

**Comment by eedwards-sk** [comment]
I'm also seeing this issue. I'm unable to run validate with `0.12.3` against an initialized terraform directory without specifying required variables.

**Comment by apparentlymart** [comment]
The bug that `terraform validate` enforces required attributes in implied `provider` configurations is a separate issue that is being tracked as #21408.
