### ISSUE TITLE
Best practice for implementing Terraform? Terraform and Chef integration?

### ISSUE THREAD

**Issue by ngeegoh** [hashicorp/terraform#21795]
Hi,

What would be the best practice for implementing Terraform? 

My case: Ideally, I want to use build a CI/CD pipeline in Azure DevOps that will use Terraform to provision infrastructure resources in Azure, then configure them by using Chef (ChefSolo atm, will just Chef Server later in a long run)

I have created a working pipeline that helps me provision a basic Azure VM. However, the structure of Terraform is very basic and not using any Terraform variables files. All the variables are stored as pipeline variables which will be replaced by tokens in Terraform files during the build/release process. 

In the long run, we want to use Terraform to create resources for different environments: development, QA, production. And for each environment, there are some certain machine types with different specifications. How would I then structure all my Terraform files in the most effective ways as well as how to manage all the variables files for those machine types terraform file. 

And if I want to integrate Chef to the Terraform CI/CD pipeline, how would I achieve that? I know that there is a provisioner step in Terraform that we could use to install and connect the resource to Chef server? But is that a good way though, and what if I only use ChefSolo, how would I integrate ChefSolo into this Terraform pipeline? 

Thanks so much.

**Comment by apparentlymart** [comment]
Hi @ngeegoh,

Unfortunately we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are more people ready to help.

This is too broad a question for us to address in a GitHub issue, because there are many different questions packed in here and the answer to each one will depend on details of your specific situation.

I'm going to close this just because it doesn't represent a specific bug or other work item for the Terraform CLI codebase. Please do feel free to ask this or a similar question in the community forum instead! Thanks.
