### ISSUE TITLE
Functionality to provide hexadecimal hash of the object inside google cloud bucket

### ISSUE THREAD

**Issue by sourabh2311** [hashicorp/terraform#21791]
### Current Terraform Version

```
0.12.1
```

### Use-cases

Google cloud has a facility to give md5 hash in hexadecimal format as well by using `-h` flag, see [here](https://cloud.google.com/storage/docs/gsutil/commands/hash). But terraform only provides the md5 hash which is obtained by converting this hexadecimal hash to binary and then doing base 64 encoding to it which is unusual. It would be helpful if terraform could simply leverage this built in feature provided by GCP.
### Attempted Solutions

I couldn't find any way in terraform by which I could convert terraform provided md5 hash to its binary form (base 64 decoding) and then converting it to hexadecimal form.

**Comment by apparentlymart** [comment]
Hi @sourabh2311,

Terraform's `md5` function returns the MD5 hash in the conventional hexadecimal form. Can you share a real example of what you tried and what result you got?

**Comment by sourabh2311** [comment]
I was talking about [this].(https://www.terraform.io/docs/providers/google/r/storage_bucket_object.html#md5hash)

**Comment by apparentlymart** [comment]
Ahh yes, indeed. Sorry I didn't know enough about the `google_storage_bucket_object` resource type to understand what you were referring to.

This is an example of a design practice we try to use in Terraform: we have conventional string representations of certain common concepts, like timestamps, durations, hashes, etc, and we assume providers will adapt whatever representations are returned by the remote APIs to match those conventions so that these values can be passed between different resource types and different providers in a straightforward way, without lots of manual conversions.

Ultimately this decision is up to the Google Cloud Platform provider team though; thank you for re-opening your issue in the provider's own repository.
