### ISSUE TITLE
issue with variables in resources (google) in v0.12.2 but work in v0.11.7

### ISSUE THREAD

**Issue by alexandershelega** [hashicorp/terraform#21819]
Hello i have this kind of problem which appeared in new version of terraform.

I had a few variables which contains some ip addresses. I use them to  manage firewalls 

```
variable "aaaa" {
  type = "list"
  default = [ "46.162.192.34/32", "46.162.192.35/32" ]
}

variable "bbbb" {
  type = "list"
  default = [ "46.162.192.36/32", "46.162.192.37/32" ]
}
```

in 0.11.7 i can use this variables in firewall source_range section and its works 

```
  source_ranges = [
                        "${var.aaaa}", 
                        "${var.bbbb}"
                ]
```

now when i do same in 0.12.2 it give me this error

  on firewall.tf line 32, in resource "google_compute_firewall" "access-jenkins":
  32:   source_ranges = [ "${var.aaaa}" ,"${var.bbbb}" ]

Inappropriate value for attribute "source_ranges": element 0: string required.

**Comment by jbardin** [comment]
Hi @alexandershelega,

Sorry about the this confusing situation here. It looks like the config was incorrect from the start, but due to some quirks in older versions of terraform, the data would end up in the correct place.

The `source_ranges` attribute takes a set of strings as its argument, but you are providing nested lists of strings in the configuration. If you expand out the variables, the assignment would look like:

    source_ranges = [["46.162.192.34/32", "46.162.192.35/32"],["46.162.192.36/32","46.162.192.37/32"]]

which would be assignable to a type of `set(list(string))`, not a `set(string)`.

You need to provide a single list, which you can do with `concat`:

    source_ranges = concat(var.aaaa, var.bbbb)

I would also recommend double checking the [0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html), which will rewrite the type declarations and references to the new syntax, among many other fixes it can do.
