### ISSUE TITLE
Possible import+resource destruction scenario in automated setups

### ISSUE THREAD

**Issue by nyurik** [hashicorp/terraform#21846]
Many organizations automate `terraform apply` on git merge or periodically to ensure that the `.tf` files are in sync with the production.  They also tend to use a shared state file, e.g. stored in a Google bucket.  This setup works fine except it creates a race condition when using `terraform import`, with the possibility of destroying the imported resource.

Assuming `terraform apply` is done periodically, and the state file is shared, any user importing an unmanaged resource into the state file with `terraform import` is risking that that resource will be destroyed before the user has a chance to implement and merge the needed .tf file changes.

## Steps
* a user runs `terraform import` on their machine, adding an unmanaged resource to the shared state.
* a user starts modifying their local .tf files to match the imported resource, and repeatedly runs `terraform plan` until they see "0 changes". This could take hours and even days before the .tf changes are merged to the master.
* at the same time, on some server, something triggers automated `terraform apply` (as part of the build pipeline), applying the "master version" of the .tf files that do not have the imported resource yet.
* result -- imported resource is destroyed because it hasn't yet been described in the master .tf files.

The only semi-realistic solution is for the organization to disable all automated `terraform apply` until after all importing is done and merged - something that could be relatively difficult to do.

Related:  #15608

**Comment by mildwonkey** [comment]
Hi @nyurik !

Can you tell us a bit more about when and where you've experienced this race condition? 
The google backend supports state locking, and both `import` and `apply` *should* lock the state, so this should not be a problem - if it is, there may be a bug in either import or apply, or in the backend itself (note: not all backends support state locking, but your listed example does)

**Comment by nyurik** [comment]
@mildwonkey state locking only works during the operation itself (i.e. `import`). In the scenario I described, it won't help:
* user runs `terraform import` on their machine, adding new resource to the shared state.
* user starts modifying their local .tf files to match the imported resource, and repeatedly runs `terraform plan` until they see "0 changes".
* at the same time, something else triggers automated `terraform apply` (as part of the server build pipeline) for the "master version" of the .tf files - they do not have the new resource yet.
* result -- your imported resource is destroyed because it hasn't yet been described in the merged .tf files.

**Comment by mildwonkey** [comment]
That makes more sense, thanks for the clarification.

**Comment by jbardin** [comment]
Hi @nyurik,

As you implied, the state locking is only intended to protect the integrity of the state itself. Any workflow with more complex locking requirements, is meant to be handled externally, because terraform itself cannot determine the business logic required to complete multistep operations. 

In the basic use case, if a user wanted to generate a configuration for an imported resource, the import and config need to be committed at the same time. If the configuration takes time to iterate over, it's probably best to not import it into the same state used in automation, because like you said, the automation could rewrite that at any time. 

I would suggest importing the resource into a local state for iteration, and once the configuration is complete, then the final import can be done along with committing the configuration. That still leaves a window where the state is imported but the configuration is not yet committed, which requires coordination with whatever automation you are using. At a basic level, this is a lock on the automation process to halt it during the import. This isn't something that terraform itself can accomplish, but would be more appropriate for the system providing the workflow and collaboration functionality.

**Comment by nyurik** [comment]
@jbardin thx for your reply!  How is it possible to switch from shared to local state management?  E.g. if the .tf file has a `terraform { backend "gcs" {}}`, it is already using shared state the moment configuration has a `bucket` variable defined.

BTW, I just realized that other state manipulations like  `terraform mv` have the same issue. Do you think it would make sense for the terraform to support some sort of a pending status on a resource which stays there until the first `terraform apply` ?  TBH I am not sure myself if this is the right solution.

**Comment by jbardin** [comment]
@nyurik, To experiment without altering the remote state, you would need to copy the state locally, then modify the configuration to remove the `backend` block.

Yes, external synchronization is required when working on with teams or automation systems. This isn't something that terraform itself is expected to handle, and is generally in the domain of the tools driving the automation workflow (Terraform Enterprise for example). 

Allowing the addition of provisional resources to a state without configuration isn't something we're likely to do, since that greatly issues around resource dependencies, and detection of orphaned resources in state. I think we would rather see this solved at a higher level with external tooling, instead of adding exceptions within the state format.

You seem to have a handle on the details required, so I'm going to close this since it's not an intended use case of the terraform cli.
