### ISSUE TITLE
Error: Missing newline after argument

### ISSUE THREAD

**Issue by jasonmoo-we** [hashicorp/terraform#21847]
### Terraform Version
Terraform v0.12.2

### Terraform Config
```
resource "aws_subnet" "private_a" {
  vpc_id = "${aws_vpc.awselk.id}" cidr_block = "10.10.3.0/24" availability_zone = "us-east-1a"
  map_public_ip_on_launch = false tags = { "Name" = "awselk-private-a" }
}
```

### Expected Behavior
Inlining parameters inside blocks never caused an error before

### Actual Behavior
```
Error: Missing newline after argument

  on vpc.tf line 20, in resource "aws_subnet" "private_a":
  20:   vpc_id = "${aws_vpc.awselk.id}" cidr_block = "10.10.3.0/24" availability_zone = "us-east-1a"

An argument definition must end with a newline.
```

### Steps to Reproduce
```
terraform init
terraform plan
```

### Additional Context
This is part of a larger configuration file but the error seems targeted at the formatting.

**Comment by jbardin** [comment]
Hi @jasonmoo-we,

It appears you missed some of the [0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html). The syntax here is not valid for 0.12, and the `0.12upgrade` tool should rewrite it correctly. 

The fact that multiple attributes on the same line parsed previously is surprising, but because it can be handled by the old parser, means it can be upgraded to the new syntax automatically.
