### ISSUE TITLE
String append to  Jq output for terraform template

### ISSUE THREAD

**Issue by RanganathNangineni** [hashicorp/terraform#21851]
Hi,

I have the below requirement where I need to get the jq output and concat/append it with other string which has spaces in it.

Ex:
Required output : "orgname-applications.App ID"

The jq output I can get it from the below is "orgname" .
 "${data.external.Ranga_tags_test2.result["tags_org"]}"

I have to append  the rest of the desired string "-applications.App ID" to the above jq output.

The terraform template tried to get the desired output it is 
"${data.external.Ranga_tags_test2.result["tags_org"]}-applications.App ID"

But it is giving errors , What is the best interpolation to get the string(which has spaces) added to json jq  .

Thanks
Ranganath

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
