### ISSUE TITLE
Incorrect attribute value type error for map variable

### ISSUE THREAD

**Issue by dsantanu** [hashicorp/terraform#21856]
Hello Everyone,
Wondering if anyone can help me out a  bit......
Just upgraded to terraform **_v0.12.2_** and number of variable to type _map_ don't seem to work any more. One of the example as shown below:

#### _security_groups.tf_ ####
```
// SecurityGroup: default access
resource "aws_security_group" "default" {
  count        = "${length(var.s_zones)}"
  vpc_id       = "${element(aws_vpc.vpcs.*.id, count.index)}"
  name         = "${var.vpc_names[count.index]}-default"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${var.vpn_cidrs["lan"]}",
                   "${var.vpn_cidrs["ovp"]}"]
    description = "SSH from vpn"
  }
}
```
#### _vars.tf_ ####
```
### Variable: vpn_cidrs  ###
variable "vpn_cidrs" {
  type = "map"
  default = {
    lan = ["10.0.11.0/28", "10.0.12.0/28"]
    ovp = ["10.1.13.0/28", "10.1.14.0/28"]
  }
}
```
With v0.12.2, it returns:
> Error: Incorrect attribute value type
> 
>    on ../../modules/vpc/security_groups.tf line 55, in resource "aws_security_group" "default":
>    55:     cidr_blocks = ["${var.vpn_cidrs["lan"]}",
>  
> Inappropriate value for attribute "cidr_blocks": element 0: string required.

It was working absolutely files up until this morning, before upgrading the version.  Is this behaviour now changed or is it a bug? How do I go past that error?

-S

**Comment by dsantanu** [comment]
okay, I see the `map` constructor has changed completely in v0.12.x, so I tried to user the new way:

```
// Variable: vpn_cidrs
variable "vpn_cidrs" {
  type = map(string)
  default = {
    lan1 = "10.0.11.0/28",
    lan2 = "10.0.12.0/28",
    ovp1 = "10.1.13.0/28",
    ovp2 = "10.1.14.0/28",
  }
}
```
and then I couldn't figure out how to iterate through the  `vpn_cidrs` to create the rule sets. Any idea how do I do that?

**Comment by jbardin** [comment]
Hi @dsantanu,

Sorry you're having an issues here. From the looks of the first example, you need should start by going through the [0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html). The `0.12upgrade` tool should fixup most of the syntax for you.

The map constructor hasn't changed, though you are correct that the type declaration has changed the syntax to allow for more precise types to be represented. The issue here is that you were assigning a list of lists to `cidr_blocks`, which only accepts a list of strings. Due to various bugs in terraform, some cases of nested lists would be flattened, which hid this configuration problem in 0.11.

Your original `vpn_cidrs` structure is fine, and the new type can be declared as `map(list(string))`, and you simply need to concatenate the lists to get the correct type.

    cidr_blocks = concat(var.vpn_cidrs.lan, var.vpn_cidrs.ovp)

**Comment by dsantanu** [comment]
Thanks @jbardin! that worked.
Out of curiosity,  what does this new `map(list(string))` type actually represent as the variable type?

-S

**Comment by jbardin** [comment]
@dsantanu, the outermost type is a map, the values in the map are lists, and the values in the lists are strings.
