### ISSUE TITLE
depends_on utilizing "${format}" vs direct reference behaves incorrectly

### ISSUE THREAD

**Issue by tenpaiyomi** [hashicorp/terraform#21890]
### Terraform Version
```
0.12.2
```

### Terraform Configuration Files
```hcl
data "aws_ecs_task_definition" "app" {
  task_definition = "${aws_ecs_task_definition.app.family}"
  depends_on = ["${aws_ecs_task_definition.app}"]
}

data "aws_ecs_task_definition" "app" {
  task_definition = "${aws_ecs_task_definition.app.family}"
  depends_on = [aws_ecs_task_definition.app]
}

resource "aws_ecs_service" "app" {
  name                                = "${var.instance_name}-app-service"
  cluster                             = "${aws_ecs_cluster.primary.id}"
  deployment_maximum_percent          = 100
  deployment_minimum_healthy_percent  = 0
  desired_count                       = 1
  launch_type                         = "EC2"
  task_definition                     = "${aws_ecs_task_definition.app.family}:${max("${aws_ecs_task_definition.app.revision}", "${data.aws_ecs_task_definition.app.revision}")}"

  lifecycle {
    create_before_destroy             = true
  }
}
```

### Debug Output
```
Error: Failed getting task definition ClientException: Unable to describe task definition.
        status code: 400, request id: 6efee117-97d0-11e9-bdb1-eb00771b4cfc "beta-app-task"

  on ../modules/instance/cluster/data.tf line 44, in data "aws_ecs_task_definition" "app":
  44: data "aws_ecs_task_definition" "app" {
```

### Expected Behavior
With a new stack, Terraform should properly handle the scenario where `aws_ecs_task_definition.app` does not exist yet.

### Actual Behavior
When utilizing `depends_on = ["${aws_ecs_task_definition.app}"]` upon initial creation, the above error is output.  Only  when using `depends_on = [aws_ecs_task_definition.app]` does terraform not complain and properly allows me to create the stack.

### Steps to Reproduce
1. Init a stack with the above mentioned setup
2. `terraform plan`

### Additional Context
Another github issue has [a comment](https://github.com/hashicorp/terraform/issues/11806#issuecomment-483698797) that states the `depends_on` is redundant.  This is false, as without the `depends_on` statement in the setup as laid out above, the same error is given.  With the `depends_on` in the proper setup from above, the stack is able to successfully be created, and in a case where the stack is being updated, it properly updates the revision to reflect the latest, if any change has occurred between state and resource.

**Comment by jbardin** [comment]
Hi @tenpaiyomi,

The other issue comment is correct, `depends_on` is not required when you already have a reference to same resource in the configuration, so there must be something else at going on here. In general you should not have `depends_on` within a data source, since that is going to prevent you from reaching a stable state as the data source will always show that it needs to be refreshed.

The `depends_on` meta attribute is also now defined as taking a list if references, however I believe strings are still accepted for some backwards compatibility. The interpolation string `"${aws_ecs_task_definition.app}"` would not be a valid reference though, as that would resolve to the set of instances created by that resource, not the resource address itself. 

Another issue here, is that the data source is referencing the resource that it intends to read, which is redundant in the configuration. You should generally read attributes directly from the resource itself within the config. If for some reason a resource is missing attributes that the corresponding data source has, it should be filed as a bug with the provider.

We have a couple related issues where users aren't getting the desired output from data sources, even when attempting to force things with `depends_on`, so I'm going to combine this with #21917 and track it there.

**Comment by tenpaiyomi** [comment]
@jbardin Thanks for the response, sorry it has taken a while to get back, I missed it for some reason.

I'm not sure what the general variation might be.  My configuration is the same as you see above (sans the extraneous rule that was not working for me), so that is sort of a Schrodinger's issue that exists unless you're looking for it, I guess, lol.

It's odd that you state that the interpolated string wouldn't work, because for my initial setup of existing instances it seemed to work fine.  The non-interpolated reference works too, of course.  The main reason for this is to ensure that, in the case of the `task_definition` attribute of the `aws_ecs_task_definition` resource, we always have the latest.  Otherwise the state is saved for the resource at a certain task definition, and then if anything else triggers the task definition value to update (in our case, we have a AWS CodeBuild project that compiles a new docker image and deploys is out), the value gets incremented to the latest version, but terraform does not see that and wants to roll back to whatever version it had at the last state.

**Comment by jbardin** [comment]
By the sounds of things, the main problem here is that you're using both a resource and a datasource for the same thing in the configuration, however they have different purposes and lifecycles. 

The purpose for a data source like `aws_ecs_task_definition` would be if that resource was _not_ managed by the same configuration. If `aws_ecs_task_definition.app` exists in the configuration, that is what you should be referencing to obtain its attributes, and you should not have it also referenced as a data source. A data source is supposed to be read as early as possible, which means if it's going to read another resource created by the same configuration, it's not going to return any pending changes because they haven't happened yet.

Adding `depends_on` "breaks" the data source (which is documented here: https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies), forcing it to be called during the Apply phase. This usually would allow the data source to return the correct data (at the expense of Terraform never being able to return an empty plan), however many resources are only eventually consistent and may not be immediately available to read (which might be part of your symptoms, but it is a common problem with various services which data source used this way would exacerbate)

**Comment by tenpaiyomi** [comment]
@jbardin Sort of.  The `aws_ecs_task_definition` defines an ECS Task that is utilized by an AWS ECS container.  When you want to deploy an updated image, you define a new version of the task and then the `aws_ecs_service` declares it's new `task_definition` in the form of `task-name:version`.

So, with that setup, the resources I have are `aws_ecs_service` and `aws_ecs_task_definition`.  I also have a data object, also named (poorly, really) `aws_ecs_task_definition`.  For the sake of the explanation, let's say my task definition is just named `app`.

When I first declare the stack, the ECS Service is created, and it is told to use the task definition `app:1` automatically by us just specifying to use 'app`.  Then several code changes occur, a new revision goes out, and the command is sent to the ECS service telling it to update the service and force a deployment with the service of just `app`, which ECS interprets to say 'for the service named `app`, deploy whatever the latest revision is.'

This all works great, up until we need to perform anything with terraform, at which point it performs the changes as laid out in the state and tells ECS "hey, you need to set your task to `app:1`" which it happily does, reverting us back to an old revision.

The purpose of the `depends_on` and circular structure here is to just ensure that we always have the latest revision of the `app` service running, and it works, albeit with the downside that there is always a "change" for the ECS Service because it always recognizes that we are updating the `task_definition` parameter to something, which we will only know about after the apply happens.

An ideal scenario would be able to tell Terraform that it should update a particular parameter within the state as part of the apply cycle, such that I could say something like `task_definition = "${aws_ecs_task_definition.app.family}:${latest(aws_ecs_task_definition.app.revision)}" and Terraform would know to update the `aws_ecs_task_definition` revision to whatever it exists as on AWS and utilize it here.  I don't believe there is any way to do that right now, outside of the hacky type method used above.

**Comment by jbardin** [comment]
Thanks for the extra info @tenpaiyomi.

Relying on a broken behavior of adding `depends_on` to a data source is not something we can support (`depends_on` will need to be supported correctly by data sources at some point), nor is this the intended use case for data sources.

There still may be a bug around some data source ordering cases, and the behavior you saw before may return with that, or it may not. The question about getting the correct information from ECS is something that is going to have to be resolved in the aws resources first. While you've probably already seen the issue, I'm going to link back to https://github.com/terraform-providers/terraform-provider-aws/issues/632 to tie these together.
