### ISSUE TITLE
Pulling Modules from Terraform Enterprise functionality change from v0.11

### ISSUE THREAD

**Issue by Criegg** [hashicorp/terraform#21902]
### Terraform Version

```
Terraform v0.12.3
+ provider.aws v1.32.0
+ provider.cloudflare v1.15.0
+ provider.tls v2.0.1
```

### Terraform Configuration Files

```hcl
module "elasticsearch5" {
  source  = "<module source>"
  version = "5.0.1"
  env     = "${var.env}"
  group   = "${var.group}"
  service = "${var.service}"
  domain  = "${var.domain}"
  version              = "5.3.0"
```

### Expected Behavior
Terraform v0.11.8 handles the version variable after the source for Terraform Enterprise hosted modules gracefully in the presence of other variables with the same name

### Actual Behavior
Error: Attribute redefined

  on elasticsearch5.tf line 16, in module "elasticsearch5":
  16:   version              = "5.3.0"

The argument "version" was already set at elasticsearch5.tf:3,3-10. Each
argument may be set only once.

Terraform v0.12.3 does not see the distinction here.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Additional Context
We have dozens of modules and do not want to have to update all of them to fix this use case. We adopted modules hosted in Terraform Enterprise after we were already established with the modules we have and did not notice this issue until upgrading to the latest version

**Comment by jbardin** [comment]
Hi @Criegg,

This was a conscious decision when upgrading to the new configuration format, since previously it would not have been clear which version should be used, and in fact may not have been deterministic at all resulting different configurations when running `init` from a clean setup.

This is something that is going to be enforced by the configuration going forward to prevent any confusion going forward.
