### ISSUE TITLE
Docs: "Passing Providers Explicitly" has an incorrect assertion

### ISSUE THREAD

**Issue by talton-heb** [hashicorp/terraform#21923]
### Terraform Version

```
▶ terraform -v
Terraform v0.12.3
+ provider.aws v2.16.0

```

### Terraform Configuration Files

main.tf
```hcl
provider "aws" {
  region = "us-west-1"
}
provider "aws" {
  alias = "other"
  region = "us-west-2"
}


data "aws_region" "current" {}
data "aws_region" "other" {
  provider = "aws.other"
}


module "child" {
  source = "./child"
  providers = {
    aws = aws
    aws.other = aws.other
  }
}
```

child/main.tf:
```hcl
provider "aws" {
  alias = "other"
}


data "aws_region" "current" {}
data "aws_region" "other" {
  provider = "aws.other"
}
```

resulting terraform.tfstate:  (snipped for relevance)

```json
{
  (...),
  "resources": [
    {
      "mode": "data",
      "type": "aws_region",
      "module": "module.child",
      "name": "current",
      "provider": "provider.aws",
      (...)
    },
    {
      "mode": "data",
      "type": "aws_region",
      "name": "current",
      "provider": "provider.aws",
      (...)
    },
    {
      "module": "module.child",
      "mode": "data",
      "type": "aws_region",
      "name": "other",
      "provider": "provider.aws.other",
      (...)
    },
    {
      "mode": "data",
      "type": "aws_region",
      "name": "other",
      "provider": "provider.aws.other",
      (...)
    }
  ]
}
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

From the last part of [Passing Providers Explicitly](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly):

> At this time it is required to write an explicit proxy configuration block even for default (un-aliased) provider configurations when they will be passed via an explicit providers block:
>
> ```
> provider "aws" {
> }
> ```
>
> If such a block is not present, the child module will behave as if it has no configurations of
> this type at all, which may cause input prompts to supply any required provider
> configuration arguments. This limitation will be addressed in a future version of Terraform.

As the child module did not have an explicit proxy configuration block, I would have expected something along the lines of:
* `terraform validate` to fail 
* The data resource object in the state file with name = `"current"` and module = `"module.child"` to have provider = `"module.child.provider.aws"`
* _something_ to indicate `the child module will behave as if it has no configurations of this type at all`

### Actual Behavior

* `terraform validate` succeeded
* The data resource object in the state file with name = `"current"` and module = `"module.child"` has provider = `"provider.aws"`
    * Implying that the implicit provider was inherited correctly despite the warning in the docs

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by talton-heb** [comment]
NB: Nothing in the "Actual Behavior" section changes if main.tf is updated to not pass the `aws` provider; eg:
```hcl
module "child" {
  source = "./child"
  providers = {
    aws.other = aws.other
  }
}
```

**Comment by jbardin** [comment]
Hi @talton-heb,

It looks like you have a "proxy configuration block" in your module exactly as described in the documentation:

```
provider "aws" {
  alias = "other"
}
```

As for the un-aliased provider, the docs state ["a child module automatically inherits default (un-aliased) provider configurations from its parent"](https://www.terraform.io/docs/configuration/modules.html#implicit-provider-inheritance), which is for convenience, but also because we don't currently require providers in configuration. This means you would get the same behavior whether or not you passed the `aws` provider to the child module.

**Comment by jbardin** [comment]
However, I just tried a slightly different example, and it appears that you can override a default provider with an aliased provider. This was a deliberate decision on 0.11 which was to be removed in 0.12, and I have a feeling that this doc was written with the intent of changing that, but the implementation is what is failing to match. 

While this should be a CLI bug, due to the requirement that it changes the configuration, we may just need to update the docs until the net major release.

**Comment by talton-heb** [comment]
Later on in the docs it also says:

> Once the providers argument is used in a module block, it overrides all of the default inheritance behavior, so it is necessary to enumerate mappings for all of the required providers. This is to avoid confusion and surprises that may result when mixing both implicit and explicit provider passing.

It seems weird that in example from my second comment the default inheritance behavior is still in effect.

**Comment by mildwonkey** [comment]
Both the functionality and documentation have been updated since this issue was opened, so I am going to close it. Please open a new issue if you continue to have a problem with terraform v0.13!
