### ISSUE TITLE
Provider profile, shared_credentials_file don't propagate to alias

### ISSUE THREAD

**Issue by BizShuk** [hashicorp/terraform#21946]
### Terraform Version
```
Terraform v0.12.3
+ provider.aws v2.17.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
    profile = "tf"
    region = "us-west-1"
}

provider "aws" {
    alias = "east"
    region = "us-east-1"
}
resource "aws_sqs_queue" "1" {
}

resource "aws_sqs_queue" "2" {
    provider = aws.east
}
```

### Expected Behavior
Even without setting the `profile` and `shared_credentials_file` in alias, these two attributes should propagate to alias.

### Actual Behavior
resource which should be created by alias provider is showing AccessDeny.

### Steps to Reproduce
common procedure

**Comment by jbardin** [comment]
Hi @BizShuk,

Just to clarify, are you expecting the setting of `profile` in the first `aws` provider block to also apply to the second `aws` provider block? If that's the case, it's not how provider configuration is intended to work. The purpose for individual, aliased providers is so that they can be configured independently. 

If that's not the case, could you describe in a little more detail how you expect each provider to be configured?

**Comment by BizShuk** [comment]
Hi @jbardin,

Yes, it is the case.  Of course, all aliases can be configured individually.  But, first, what I feel is like that the alias should inherit the default provider (non-alias) and can override the attributes in alias provider block. It can make the alias block less configurations, just difference between default provider and alias.  And, second, if provider should be only configured individually. For the syntax of multiple providers, it should be more like below.
```
Provider "aws" "default" {} 
Provider "aws" "<name1>" {} 
Provider "aws" "<name2>" {}
resource "<resource_type>" "<resource_name>" {
    provider = Provider.aws.<name1>
}
```
I found this when I tried to build a module that is to build multiple-regions resources.  This is my opinion.

I think that you have explained idea from Terraform. If there will be no plan to rethink this, this issue can be closed. Thanks.

**Comment by jbardin** [comment]
Thanks for following up.

We feel that the configuration in general should always err on the side be being more explicit, rather than implicit. We also found that some the provider functional which did rely on inheritance and merging of configuration was often the source of unexpected behavior for users, and have been working to remove in recent releases. 

Thanks again!
