### ISSUE TITLE
tool similar to AWS cloudformation designer 

### ISSUE THREAD

**Issue by scheung38** [hashicorp/terraform#21942]
Terraform has drag and drop tools in the future, similar to AWS Cloudformation designer? this would be cool feature to have to see at a glance all the interrelations.

**Comment by phinze** [comment]
Hi @scheung38 - thanks for the idea! this is indeed something we're considering building in the future. This functionality would likely land in our Terraform Cloud and Terraform Enterprise products. It's not something we currently have scheduled on our roadmap though. I'm going to close this issue since we're not planning to do any work relating to this idea on this project.
