### ISSUE TITLE
comparison operators apply only to bool, float, int, and string in terraform

### ISSUE THREAD

**Issue by vkforums** [hashicorp/terraform#21961]
**### Terraform Version**
Terraform v0.11.7
+ provider.aws v1.42.0
+ provider.external v1.2.0

### **Terraform Configuration Files**
My variables.tf below : 

```
cidrblock_enabled = “${local.cidr_block[terraform.workspace] == “<none>” ? 0 : 1}“

```
```
locals {
cidr_block_ = {
    QA  = ["10.10.0.0/16"]
    PROD = ["<none>"]
  }
}
```
### Expected Behavior
Expected that cidrblock_enabled would evaluate to true or false depending on the workspace.

### Actual Behavior
It no longer evaluates the boolean comparison and throws error "comparison operators apply only to bool, float, int, and string in terraform"

**Comment by jbardin** [comment]
Hi @vkforums,

This is the expected behavior, and the error is also highlighting a problem in your conditional expression; you are comparing a list of strings to a single string.

Even if it were allowed, the evaluation of `["<none>"] == "<none>"` should not ever be able to evaluate to true. I would suggest not attempting to compare the equality of complex structures, but it is possible if you explicitly format them as a string. If you are simply looking for the `"<none>"` string, you could index your list, or use the `contains` function.
