### ISSUE TITLE
In Terraform 0.11, you can index a set (acts like it's a list). This is not the case in 0.12

### ISSUE THREAD

**Issue by gmrodgers** [hashicorp/terraform#21974]
### Terraform Version

We tested against two majors of terraform:
```bash
$ terraform-12 version              
Terraform v0.12.3
+ provider.google v2.10.0
```

```bash
$ terraform-11 version              
Terraform v0.11.11
+ provider.google v2.10.0
```

### Terraform Configuration Files
Below is an working example configuration we had for 0.11:
```hcl
provider "google" {
  credentials = "creds..."
  project = "our-project-id"
  region = "europe-west1"
}

resource "google_compute_network" "example-network" {
  name = "test-network"
}

resource "google_compute_firewall" "example-firewall" {
  name    = "test-firewall"
  network = "${google_compute_network.example-network.name}"

  source_ranges = ["0.0.0.0/0"]

  allow {
    ports    = ["22", "555"]
    protocol = "tcp"
  }

  target_tags = ["first-tag", "second-tag"]
}

# Output can be indexed
output "erroring-output" {
  value = "${google_compute_firewall.example-firewall.target_tags[0]}"
}
```

### Debug Output
Terraform 0.11 https://gist.github.com/gmrodgers/5922315e2e77e84545633c05eb962370
Terraform 0.12 https://gist.github.com/gmrodgers/01b15a283a18a818cb5377e2a6aead8a

### Std Output
```bash
$ terraform-11 apply
...
Outputs:

erroring-output = second-tag
```

```bash
$ terraform-12 apply
...
Error: Invalid index

  on main.tf line 26, in output "erroring-output":
  26:   value = "${google_compute_firewall.example-firewall.target_tags[0]}"

This value does not have any indices
```

### Expected Behaviour
We expect consistent behaviour or documented changes.
ie
Both terraform 11 and 12 error out when trying to index a set.
or
Document that sets were indexable in 11, then were not in terraform 12? We could not find this documentation.

### Actual Behaviour
Now in 0.12, we have to do this to access the target tags although the `tolist` doesn't guarantee the correct order (as expected)

```hcl
output "erroring-output" {
  value = "${tolist(google_compute_firewall.example-firewall.target_tags)[0]}"
}
```

This was done through trial and error as we could not find documentation on this change.

### Steps to Reproduce
For the two versions above with our `main.tf` file above:
1. `terraform init`
2. `terraform apply`

### References
Not that we could find.

cc @alamages

**Comment by jbardin** [comment]
Hi @gmrodgers,

Sorry you had a problem with this, it is the expected behavior in 0.12. The fact that you could almost reliably index a set like a list was an accident of the legacy internal representation of the data, and definitely not intended to be used that way.  Now that we have richer data structures and strong types in terraform, this implementation detail has changed and removes the list-like stricture of sets.

Set are by definition an un-ordered data type, and attempts to index into were the cause of numerous bugs.

If you need reliable ordering of the set data, you have to explicitly impose that yourself. In this case you can use the `sort` function to order the set of strings. 

You may also want to go back through the [0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html), as it appears this config has not been upgraded and you may encounter other behavior changes in the new version.

**Comment by realflash** [comment]
I think we are still missing some documentation on this. I read the upgrade guide and it doesn't mention this. I took quite some time to find this issue in order to discover what was going. Please can the upgrade guide and tool be extended to address this issue?
