### ISSUE TITLE
Terraform validate not checking for variables

### ISSUE THREAD

**Issue by sce81** [hashicorp/terraform#21986]
### Terraform Version

```
0.12.3
```

### Terraform Configuration Files

```hcl
module - populated main.tf, empty variables.tf
```

### Expected Behavior

terraform validate should list the undeclared variables
### Actual Behavior

terraform validate does not report issues with variables
terraform validate -check-variables=true asks for -json option

**Comment by jbardin** [comment]
Hi @sce81,

This is the expected behavior now, and there is no longer a `-check-variables` option to `validate`.
Configuration can be valid without all variables defined, as they are often passed in via the cli or environment, and modules leave them undefined as required arguments.

Validation is not meant to ensure variables have values assigned, but rather it is used to determine if the structure, syntax, and types used in the configuration are valid, regardless of the values of the variables.
