### ISSUE TITLE
Crash 0.12.3 GCP

### ISSUE THREAD

**Issue by sce81** [hashicorp/terraform#21988]
### Terraform Version

```
0.12.3
google_provider 2.10
google_beta_provider 2.10
```

### Terraform Configuration Files

```hcl
locals {
  labels = {
      name                      = var.name
      environment               = var.env
      application               = var.app_name
      team                      = var.team
      cost_type                 = var.cost_type
  }
}

resource "google_compute_global_address" "public_ip" {
  provider = google-beta

    name                        = "${var.env}-${var.name}-ip-address"
    description                 = "${var.env} google compute address"
    network_tier                = var.network_tier
    dynamic "labels" {
        for_each = local.labels 

        content {
            key                 = labels.key
            value               = labels.value
        }

    }
}
```

### Crash Output

https://gist.github.com/sce81/2a4e592b4e26466873ebfcd153520454

### Expected Behavior

testing for_each loops
### Actual Behavior

terraform crashed
### Steps to Reproduce

terraform plan

**Comment by mildwonkey** [comment]
Thanks for reporting this @sce81 , and I'm sorry you've experienced it!\

The crash was easy to reproduce with the example configuration (thanks!), but I found out that it does not crash when I switch to the google provider (instead of google-beta), so I am going to move this report to the google provider repository. 

Thanks again!
