### ISSUE TITLE
Terraform 0.12 does not seem to store dependencies correctly in the terraform.tfstate file

### ISSUE THREAD

**Issue by vaneyckt** [hashicorp/terraform#21987]
Hi there,

I have a terraform file which creates 3 instances of a `ctrl` resource, as well as 3 instances of a `worker` resource. Notice how I set the name for the `ctrl` resources in such a way that each `ctrl` resource is dependent on exactly one respective `worker` resource.

```
resource "vsphere_virtual_machine" "ctrl" {
  count            = "3"
  name             = "${format("ctrl-%s", vsphere_virtual_machine.worker[count.index].name)}"
  folder           = "PROJECT"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 4
  memory   = 2048
  guest_id = "centos7_64Guest"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label = "disk1"
    size  = 20
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }
}

resource "vsphere_virtual_machine" "worker" {
  count            = "3"
  name             = "${format("worker-%02d.project.az1.eng.pdx.wd", count.index+1)}"
  folder           = "PROJECT"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 4
  memory   = 2048
  guest_id = "centos7_64Guest"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label = "disk1"
    size  = 20
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }
}
```

After applying the above using Terraform 0.12, I can see the following contents in the resulting `terraform.tfstate` file.

```
"mode": "managed",
      "type": "vsphere_virtual_machine",
      "name": "ctrl",
      "each": "list",
      "provider": "provider.vsphere",
      "instances": [
        {
          "index_key": 0,
          ...
          "depends_on": [
            "data.vsphere_datastore.datastore",
            "data.vsphere_network.network",
            "data.vsphere_resource_pool.pool",
            "data.vsphere_virtual_machine.template",
            "vsphere_virtual_machine.worker"
          ]
        },
```
It seems that the `vsphere_virtual_machine.ctrl[0]` node is dependent on all the `vsphere_virtual_machine.worker` nodes. The same is true for the `ctrl[1]` and `ctrl[2]` nodes.

This is unfortunate as this means that running `terraform destroy -target vsphere_virtual_machine.worker[0]` causes all 3 `ctrl` nodes to be deleted, instead of just the one that has a dependency on it.

**Comment by apparentlymart** [comment]
Hi @vaneyckt! Sorry for this surprising behavior.

Currently dependencies between resources are tracked between whole resource blocks rather than individual instances, because the plan graph (which is the one that `-target` primarily applies to) includes the blocks from the configuration (not yet expanded) rather than the instances that result from handling `count`.

I do agree that it would be better if Terraform could track these dependencies more precisely. It's not clear right now how exactly we'd implement such a thing given the constraints of the current architecture, but we'll use this issue to track the use-case and look out for opportunities to address it through changes to the graph-building architecture in future releases.
