### ISSUE TITLE
Confusing error message on `lifecycle = {`

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#21995]
### Terraform Version

```
Terraform v0.12.4-dev
```
@ 37a6331eb

### Terraform Configuration Files

```hcl
resource "anything" "something" {
  # ...

  # ! invalid code !
  lifecycle = {
    # ...
  }
}
```

### Expected Behavior
Something like:
```
Error: Bad syntax

  on something.tf line x, in resource "anything" "something":
 x:   lifecycle = {

Expected `{`, but got `=`.
```
### Actual Behavior
```
Error: Unsupported argument

  on something.tf line x, in resource "anything" "something":
 x:   lifecycle = {

An argument named "lifecycle" is not expected here.
```

### Steps to Reproduce
1. Write broken terraform
2. `terraform plan`

**Comment by tsmalls93** [comment]
Remove the `=` after `lifecycle`

**Comment by OJFord** [comment]
I know the problem with the code, and I understand it's wrong. The issue is about the error message, which is correctly an error message, but could be more helpful.

**Comment by apparentlymart** [comment]
Hi @OJFord! Thanks for reporting this.

Normally this type of error message includes a prompt that you may have meant to write a nested block rather than an argument and to remove the equals sign if so, but I think it doesn't appear in this case because of a detail of how Terraform has to handle these special elements within `resource` blocks that are resolved by Terraform itself, rather than by the provider.

To be specific, I expect what's happening here is that the initial work done by Terraform itself is looking for the `lifecycle` _block_ and not finding it, but because that step is intentionally ignoring anything it doesn't understand (assuming they are resource-type-specific arguments) it proceeds anyway, and then the errant attribute then finally gets caught in the resource-type-specific validation, because `lifecycle` doesn't appear in the schema for this resource type.

I think it is feasible to fix this, but it is likely to require some special cases to deal with the resource "meta-arguments" in particular, vs. our existing message which is generic for any block defined as part of a resource type schema. For example, perhaps we'd need to speculatively ask HCL to decode with `lifecycle` specified as an argument and produce an error if that _does_ succeed, since that would suggest that `lifecycle` is being used incorrectly.

**Comment by OJFord** [comment]
@apparentlymart I see, thanks. Naïve thought though: couldn't this first pass look for valid block-starting keywords, rather than blocks themselves, since those are fixed in tetragonal core aren't they?

I suppose there's potential for the opposite problem, in that you typo the block keyword and get an error about needing an `=`, or it not being a valid attribute.

Now I'm wondering if there's an LSP implementation for terraform...

**Comment by juliosueiras** [comment]
https://github.com/juliosueiras/terraform-lsp *cough*

**Comment by OJFord** [comment]
🎉  🙇

**Comment by OJFord** [comment]
With this so old and little interest I assume it's no longer an issue or at least hasn't confused people enough to bring them here, so closing. Happy to reopen if you are following this with interest, just ping me.
