### ISSUE TITLE
0.12upgrade failed on count

### ISSUE THREAD

**Issue by ThomasVdBerge** [hashicorp/terraform#22014]
### Terraform Version

```
$ terraform --version
Terraform v0.12.3
```

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "app" {
  count                = "${var.enabled}"
  task_definition = "${aws_ecs_task_definition.app[count.index].arn}"
}
```

### Expected Behavior

TF Converted the resource to the 0.12 syntax
### Actual Behavior

```
Error: Invalid interpolated string

  on main.tf line 29:
  (source code not available)

Interpolation parsing failed: parse error at 1:39: expected "}" but found "."
```
### Steps to Reproduce

```
terraform 0.12upgrade -yes -force
```

**Comment by jbardin** [comment]
Hi @ThomasVdBerge,

The config being upgraded by the `0.12upgrade` tools needs to be valid `0.11` configuration in order to be parsed. 

`aws_ecs_task_definition.app[count.index].arn` is already in a syntax used for 0.12. You probably had something like `aws_ecs_task_definition.app.*.arn[count.index]`, but in general you should not be attempting to manually update parts of the config the config until after the upgrade tool has run.
