### ISSUE TITLE
null_data_source `for` block evaluated too early

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22032]
### Terraform Version
```
Terraform v0.12.4-dev
```

### Terraform Configuration Files

```hcl
data "null_data_source" "ingress_hosts" {
  inputs = {
    for host in vultr_instance.master : host.hostname => host.ipv4_address
  }
}
```

### Expected Behavior
`data.null_data_source.ingress_hosts.outputs` should be a map of the post-`apply` instances.

### Actual Behavior
It's a map of the pre-`apply` hosts, so the first run (with no instances) requires `-target=data.null_data_source.ingress_hosts` if anything consumes this `data`, and subsequent runs need a second pass in order to update anything that depends on it.

### Steps to Reproduce
1. config as described
2. `terraform apply`
3. `terraform plan` to note changes even though just applied

**Comment by apparentlymart** [comment]
Hi @OJFord,

This is unfortunately the expected behavior right now, because data resources are resolved during the "refresh" step. We do have an issue open for reworking the data resource lifecycle so it would happen in the plan step, and thus could consider changes that are still pending, but that is a big refactoring that we can't tackle right now without derailing other work.

With that said, it looks like this is an example of the old 0.11 workaround of using a `null_data_source` as a place to stash values for referencing elsewhere. That shouldn't be necessary anymore; Local Values cover most of that use-case and `for` expressions in 0.12 covered the remaining hole of using `count` on `null_data_source` to transform a list. Could you use these features instead?

**Comment by OJFord** [comment]
Ahah, I'd forgotten about `locals` - thank you - I can shorten so many lines! 😅
