### ISSUE TITLE
Count issue on tuple attributes

### ISSUE THREAD

**Issue by geass** [hashicorp/terraform#22033]
Hello,

I've a variable file as below;

```
terraform.tfvars
abc = {

  create = true
  enable  = true
}
```

and on my main file, I'm merging this variable with some other variables as below;

```
main.tf

module "test" {

source = "git::blabla"

abc = merge(var.abc, {test=module.vpc.id}) // vpc is another module I'm running

}
```

and on my remote module I'm trying to create a resource;

```
resource "aws_sns_topic" "this" {
  count = var.abc.create && var.abc.enable ? 1 : 0

  name = "test-sns"
}
```

but when I want to run it, I'm getting this error : 
```
on .terraform/modules/test/main.tf line 14, in resource "aws_sns_topic" "this":
  14:   count = var.abc.create && var.abc.enable ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

With the terraform console, I've tested my variables and they are there and merge works. So what might be the problem? 

My terraform version is : 

```
 terraform12 -v
Terraform v0.12.3
+ provider.archive v1.2.2
+ provider.aws v2.18.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
```

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
