### ISSUE TITLE
When provisioning with Ansible in Terraform (local_exec) a failed playbook will not halt terraform.

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#22067]
### Terraform Version

```
Terraform v0.11.13
```

### Expected Behavior
Any Ansible playbook I run during terraform provisioning will not halt terrraform if the playbook fails.  This is using a null resource local connection shell.
This is problematic because  digging up the reason why something wasn't provisioned correctly can make things difficult to determine when going through terraform logs that are really long, and it takes longer than necessary to provision infrastructure that won't work-  it would help if I could halt terraform immediately on any Ansible failures (in local_exec) to catch the error immediately.

I believe this could occur if the shell looked to the exit code to determine if terraform should continue.
 
### Actual Behavior
Terraform keeps provisioning

### Steps to Reproduce
Execute any playbook that fails in local_exec.

**Comment by queglay** [comment]
Although I think it would be great to solve this one as default behavior / an option, I'm wondering if there would be a possible workaround I could implement in the meantime?

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
