### ISSUE TITLE
backend/azure: auto create storage container

### ISSUE THREAD

**Issue by omar** [hashicorp/terraform#22066]
### Current Terraform Version
```
Terraform v0.12.4
+ provider.azurerm v1.31.0
```

### Use-cases
Each of our applications is responsible for their own set of infrastructure. The way that manifests is each app has an `infrastructure` folder with the necessary Terraform code. This provides developers the freedom to evolve and experiment from code to infrastructure without having to go to a central infrastructure repository.

Terraform state is stored in an environment specific (i.e. dev, prod) Azure Storage Account with each app having something like this in their infrastructure folder:

```
terraform {
  backend "azurerm" {
    storage_account_name = "terraform-state-dev"
    container_name       = "app-name"
    key                  = "tfstate"
  }
}
``` 

Note that we choose to use a different container for each app while the state file is named the same for each container. This gives us the flexibility to quickly see all of the existing application being managed by Terraform in the storage account and we can quickly and safely remove dead or unused containers as we obsolete apps. This also provides a nice boundary for workspaces to be housed within the same container for each app. In addition, developers debugging their Terraform code can quickly find their remote state file if they ever need to.

Here's an example of what the storage account would look like with this setup:

![image](https://user-images.githubusercontent.com/196368/61187703-638cda00-a63a-11e9-83ca-e156a0f4d1b5.png)

This all works well but with this flow developers have to remember to create a new container for each app when adopting Terraform. This is because the Azure backend provider doesn't automatically create the container like it does with the blobs for each state file.

### Attempted Solutions
We've had to resort to written documentation for our production engineers to create these containers for new applications.

### Proposal
Allow the Azure backend provider to automatically create the storage container if it doesn't exist. This is similar to what it currently does with the blobs that contain the state file. The provider access key already has access to create the container so no additional permissions are needed.

This feature would streamline the initial process of bringing an application into Terraform and would aide in the progression of those changes from dev to production where the access controls are different. 

### References
This behavior is some what expected because the backend provider already auto creates blobs. Extending it to also auto create containers would remove a manual additional step.

- #21531

**Comment by apparentlymart** [comment]
Hi @omar! Thanks for opening this feature request.

It is a general design principle for backends (not just the Azure one) that they do not automatically allocate a storage container/bucket, because in the common situation where multiple configurations are sharing the bucket it would then be unclear which one is the "owner" of it for the purpose of tracking that it exists, destroying it when it is no longer required, etc. That doesn't apply to the individual snapshot objects, because (if Terraform is configured correctly) each configuration has its own separate object which it is fully responsible for.

Instead, the common pattern is to have a separate Terraform configuration that manages your storage containers, so that the containers are managed the same way as any other infrastructure. That configuration will of course _also_ have a Terraform state which must be persisted somewhere, but since there is only one of this many teams just accept creating that one manually (it's a special case for bootstrapping) and then have that first configuration be responsible for managing the storage for all the others.

For teams that are particularly keen on having even the storage for that first configuration managed by Terraform, it's possible to bootstrap like this:

* Write the initial configuration containing the definition of the storage container that will eventually host the state snapshots for this very configuration.
* Apply the configuration first with no `backend` block at all, thus creating a `terraform.tfstate` locally tracking the existence of that bucket.
* Now add the `backend "azure"` block to the configuration, using the settings to access the container that was just created.
* Run `terraform init` and it will offer to migrate the local state snapshot into the Azure storage, which now exists.

This approach means that this special initial configuration cannot be used with `terraform destroy` without first switching back to local state -- otherwise its own storage would need to be deleted out from under it -- but that compromise is often okay because this initial configuration's state storage should outlive any other infrastructure being managed by Terraform.

**Comment by omar** [comment]
Thanks for the thorough answer@apparentlymart.

I get the principled approach here, but I'd like to point out that in Azure, users have to create 2 things before they can begin using remote state; storage account, and storage container. I'm advocating for automatically creating the storage container (not the account) since the operation would be idempotent and in theory it could be thought of like a blob in the S3 sense: `STORAGE_CONTAINER_NAME/WORKSPACE_STATE.TF`

I'll close this issue since I know changing this design principle will not happen here. However, I've come across a couple of other answers to questions and feature requests where this design principle was mentioned, but I feel like it gets in the way of creating a simpler user experience. 

The steps required to go from local state to remote state can be shortened and made automated which in my mind is far more valuable than having to designate a configuration as the "owner" of the storage. This is because the operation here can be non-destructive for the container while keeping it destructive for the individual state file blob.
