### ISSUE TITLE
Assign a resource to an another resource based on a condition

### ISSUE THREAD

**Issue by KumarManoj-S** [hashicorp/terraform#22078]
Hi,

we have different environments such as `prod|staging|showcase`. I found a way how to create a resource based on the environments using [count](https://github.com/hashicorp/terraform/issues/2831#issuecomment-298751019). Is there any way to assign a resource to an another resource based on a condition?

To be more specific,
we have WAF setup. Web ACL has list of rules and I want to attach a rule based on a condition.
Below is my acl resource, (I want this whitelisting rule needs to be there for all the three environments)

```hcl
    resource "aws_wafregional_web_acl" "waf_acl" {
      name        = "${local.aws_resource_naming}-acl"
      metric_name = "MetricName"

      default_action {
         type = "BLOCK"
      }

      rule {
       action {
        type = "ALLOW"
       }

      priority = 1
      rule_id  = "${aws_wafregional_rule.ips_whitelist_waf_rule.id}"
      type     = "REGULAR"
     }
    }
```

And I want to attach one more rule but based on a condition, below is the rule that I want to add only on `showcase and staging`.

```hcl
    rule {
     action {
       type = "ALLOW"
     }
    priority = 2
    rule_id  = "${aws_wafregional_rule.integration_tests_rule.id}"
    type     = "REGULAR"
    }
```

Is there a way in terraform to achieve this? Can anybody help me how to handle this?

**Comment by jbardin** [comment]
Hello,

Terraform now has dynamic block and for-expressions for constructing and assigning complex types, so I'm going to close this out. If you have more questions, we use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
