### ISSUE TITLE
Error: Invalid template interpolation value

### ISSUE THREAD

**Issue by AndreiBrajnicov** [hashicorp/terraform#22072]
Hello everyone. Till today I was using an older version of terraform, but today I upgraded it to the latest available version:
``Terraform v0.12.4
+ provider.aws v2.19.0

After that terraform plan is failing with following error:
```
Error: Invalid template interpolation value

  on eks.tf line 149, in resource "aws_eks_cluster" "xxx-eks":
 149:     subnet_ids = ["${aws_subnet.eks-public.*.id}, ${aws_subnet.eks-private.*.id}"]
    |----------------
    | aws_subnet.eks-public is tuple with 3 elements

Cannot include the given value in a string template: string required.


Error: Invalid template interpolation value

  on eks.tf line 149, in resource "aws_eks_cluster" "xxx-eks":
 149:     subnet_ids = ["${aws_subnet.eks-public.*.id}, ${aws_subnet.eks-private.*.id}"]
    |----------------
    | aws_subnet.eks-private is tuple with 3 elements

Cannot include the given value in a string template: string required.
```

I can't understand what is going on, moreover that it was working before update.
Here you can find piece of code which makes the problem:
```
resource "aws_eks_cluster" "xxx-eks" {
  name = var.cluster-name
  role_arn = aws_iam_role.eks-cluster.arn
  version = "1.12"

  vpc_config {
    security_group_ids = [aws_security_group.eks-cluster.id]
    subnet_ids = ["${aws_subnet.eks-public.*.id}, ${aws_subnet.eks-private.*.id}"]
  }

  depends_on = [
    aws_iam_role_policy_attachment.GP-cluster-AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.GP-cluster-AmazonEKSServicePolicy,
  ]
}
```

Please help me to solve this issue.

**Comment by apparentlymart** [comment]
Hi @AndreiBrajnicov,

If you want to produce a single collection of all of those subnet ids, the correct syntax for that would be as follows:

```hcl
subnet_ids = concat(aws_subnet.eks-public.*.id, aws_subnet.eks-private.*.id)
```

Your configuration is failing because you've asked Terraform to interpolate a non-string value ("a tuple with 3 elements", according to the error message) into a string, and that's impossible. (Quite why that was working in prior versions isn't clear to me.)

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are more people ready to help. The GitHub issues here are generally monitored only by our few core maintainers.

**Comment by AndreiBrajnicov** [comment]
Hi @apparentlymart .
Thank you very much. You solved my day.
