### ISSUE TITLE
Allow terraform backend arguments to use functions and variables

### ISSUE THREAD

**Issue by ofirule** [hashicorp/terraform#22088]
version: Terraform v0.12.4

## Example1:

```
locals {
  my_dir     = basename(abspath(path.module))
}

terraform {
  backend "s3" {
    bucket = "b1"
    key    = format("terraform_remote_state/%s/terraform.tfstate", local.my_dir)
    region = "eu-central-1"
  }
}
```
Output:
```
Initializing the backend...

Error: Function calls not allowed

  on terraform.tf line 8, in terraform:
   8:     key    = format("terraform_remote_state/%s/terraform.tfstate", local.my_dir)

Functions may not be called here.
```
## Example2:
```
locals {
  my_dir = basename(abspath(path.module))
  my_key = format("terraform_remote_state/%s/terraform.tfstate", local.my_dir)
}

terraform {
  backend "s3" {
    bucket = "b1"
    key    = local.my_key
    region = "eu-central-1"
  }
}
```
Output:
```
Initializing the backend...

Error: Variables not allowed

  on terraform.tf line 9, in terraform:
   9:     key    = local.my_key

Variables may not be used here.

```

**Comment by tep** [comment]
I wouldn't really call this an _enhancement_; that might lead people to believe that it warrants a low priority which may or may not be resolved any time soon (or ever).

I'd instead view the fact that variables are forbidden in this context as a _serious deficiency_ bordering on _reckless design flaw_.

tl/dr; This should be rectified ASAP.

**Comment by NadOby** [comment]
Clearly second this as deficiency.
Have same problem using artifactory backend.

**Comment by teamterraform** [comment]
Hi all,

Terraform cannot support arbitrary expressions in the `backend` block because the configuration inside it must be processed to even retrieve the latest state snapshot, and the latest state snapshot is required in order to evaluate expressions.

If you are using Terraform in an environment where statically configuring the location of your workspaces is not appropriate or where the location can be determined systematically by some transform from some other known value, you can omit the settings in question from the Terraform configuration altogether and provide them on the `terraform init` command line using the `-backend-config` argument. By [running Terraform in automation](https://learn.hashicorp.com/terraform/development/running-terraform-in-automation) you can put the logic for determining those settings in an external script and make it do whatever you want using information locally available on the system.

We have no plan to support arbitrary expressions in the `backend` block because it is technically impossible: the backend stores the state and the state is needed to evaluate expressions, so _something_ has to be statically configured in order to give Terraform a starting point to fetch the data it needs for the rest of the work.

**Comment by atrauzzi** [comment]
I think the idea is to not leverage all of terraforms functions. Just some utility functions that have no dependencies.
