### ISSUE TITLE
Design and Use of Terraform with disjoint state files

### ISSUE THREAD

**Issue by udayanms** [hashicorp/terraform#22118]
Hi, 

One of my team is implementing using TF, Go, Python and deploying resources with independent State files. Do you see any benefits of such implementation?  As they are storing the config requirements as JSON in a DB and creating the tf request on the fly. 

Regards
Udayan

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
