### ISSUE TITLE
Enforcing Tagging and Naming standard

### ISSUE THREAD

**Issue by udayanms** [hashicorp/terraform#22120]
### Current Terraform Version

I am using 0.12
```
...
```

### Use-cases

I want to ensure that each resource deployed as part of TF automation should enforce Tagging and Naming standard. e.g. Certain set of Tags (although values may be supplied as part of execution) are required. I am aware I can ensure the same by mandating tags as part of TF. but can we have a construct in TF which enforced Tags and naming standards.

**Comment by teamterraform** [comment]
Hello @udayanms,

From Terraform 0.12.0 onwards, Terraform can produce a JSON representation of a saved plan that you can use with a program of your own to impose whichever rules are appropriate in your system:

```
terraform plan -out=tfplan
terraform show -json tfplan
```

You can find details on the format of that JSON output in [JSON Output Format](https://www.terraform.io/docs/internals/json-format.html).

For checking tagging standards, the most straightforward answer would be to iterate over the objects you can find in the array at `resource_changes`, which is a flat list of all of the changes in the plan across all modules, and run your checks against resource types that participate in your tagging scheme. For example, in pseudocode:

* For each `r` in `plan.resource_changes`:
  * If `r.mode` is `"managed"` and `r.type` is a resource type subject to the tagging standard:
    * Let `new_object` = `r.change.after`
    * If `new_object.after` is null, skip to the next `r`
    * Let `new_tags` = `new_object.tags`
    * If `new_tags` does not comply with the tagging standard, produce an error

Terraform will sometimes be unable to predict a value until apply time, if it is derived from some other attribute that can't be predicted. Therefore imposing conventions on a part of the plan will necessarily also impose the requirement that its value not be dependent on any unknown values. For tags naming schemes in particular that is usually fine because the expected tags are static strings identifying environment, application, etc, but it's worth keeping that in mind; unknown values will not be present in the `new_object.after` value at all, and so your logic must be prepared to deal with them being absent and to produce a suitable error in that case if that ought to be forbidden.

Hopefully that helps! This JSON output is the mechanism by which Terraform aims to allow team-specific standards to be enforced, so we're going to close this out now. If you have further questions, please feel free to ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
