### ISSUE TITLE
"panic: reflect: call of reflect.Value.Type on zero Value" during SDK validation

### ISSUE THREAD

**Issue by MaT1g3R** [hashicorp/terraform#22147]
### Terraform Version

```
0.12.4
```

### Crash Output

https://gist.github.com/MaT1g3R/0edb87a2fdd5256883a8af8731197ca8
### Expected Behavior

Terraform not crashing

### Actual Behavior

Terraform crashed

### Steps to Reproduce

1. `terraform apply`

**Comment by teamterraform** [comment]
Hi @MaT1g3R! Sorry for this crash and thanks for reporting it.

This crash seems to have happened inside the Google provider when Terraform asked it to refresh the state for `google_compute_target_http_proxy.lighthouse_ipv4`.

Could you please share the configuration of that resource and perhaps any information about any changes you might've made to that resource recently, either via Terraform or via the Google Cloud console? It would also be useful to see the part of the `terraform show` output that relates to `google_compute_target_http_proxy.lighthouse_ipv4` in case the problem is with something already in the state.

This issue seems to be in the validation logic inside the common SDK that all providers share, so we've labelled it as being an SDK bug for now, pending more information to see what might have happened here.

**Comment by MaT1g3R** [comment]
We do not use the GUI to change any properties, it's all managed by terraform.

Here's a minimal configuration to cause the crash (insert your own gcloud project):



```hcl
provider "google" {
  project = "foo-project"
}

data "google_compute_ssl_certificate" "foo" {
  name = "foo"
}

resource "google_compute_target_https_proxy" "foo_ipv4" {
  name = "foo-http-target-ssl-proxy-ipv4"
  ssl_certificates = [
  data.google_compute_ssl_certificate.foo.self_link]
  url_map = google_compute_url_map.foo_http.self_link
}

resource "google_compute_backend_service" "foo_backend" {
  name                  = "foo-backend"
  protocol              = "HTTP"
  port_name             = "http"
  load_balancing_scheme = "EXTERNAL"

  backend {
  }
  health_checks = [google_compute_health_check.http_basic_check.self_link]
}

resource "google_compute_url_map" "foo_http" {
  name            = "foo-http"
  default_service = google_compute_backend_service.foo_backend.self_link
}
resource "google_compute_health_check" "http_basic_check" {
  name                = "http-basic-check"
  timeout_sec         = 5
  check_interval_sec  = 5
  healthy_threshold   = 2
  unhealthy_threshold = 2

  http_health_check {
    port         = 80
    request_path = "/"
  }
}
```
