### ISSUE TITLE
Convertion from octal to decimal not working

### ISSUE THREAD

**Issue by JrCs** [hashicorp/terraform#22143]
### Terraform Version

```
Terraform v0.12.5
```

### Terraform Configuration Files

```hcl
provider "ignition" {
  version = "~> 1.1"
}

data "ignition_file" "hostname" {
  count      = var.num_servers
  filesystem = "root"
  path       = "/etc/hostname"

  content {
    content = format("%s%03d", var.hostname_prefix, count.index + 1)
  }

  mode = format("%d","0644")
}

```

### Expected Behavior

Expected that mode was 420 (0644 -> 420 in decimal)
### Actual Behavior

mode is set to 644 instead of 420

### Another test
I have try without the quotes:
```hcl
  mode = format("%d",0644)
}
```
but i obtain the same behaviour.

**Comment by teamterraform** [comment]
Hi @JrCs!

Terraform intentionally only supports decimal when converting from string to number, to avoid a common pitfall where converting a zero-padded number could interpret it as octal.

The usual convention is for a provider that wishes to accept a number in another base to accept it as a string itself and do its own conversion, so that the alternative base representation is explicit. It looks like the ignition provider isn't following that convention, so you may wish to open an issue with that provider to see about having the provider itself accept `mode = "644"` (or, more likely `mode = "0644" for backward compatibility) there. POSIX-style file modes are essentially the only situation where octal numbers are idiomatic, so Terraform's conventions treat them as an exception rather than us having first-class features for them.

**Comment by JrCs** [comment]
Thanks a lot for clarification.
