### ISSUE TITLE
S3 state backend fails if `/` in secret access key

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22153]
### Terraform Version
I was using
```
0.11.14
```
when it occurred, but I'm happy to test master if it's believed it might be fixed in 0.12.x. 

### Steps to Reproduce
1. Configure S3 remote state
1. Generate access keys (for a user with permissions to the state bucket)
1. Repeat until a `/` character appears in the secret access key
1. Set keys in environment
1. `terraform plan`

### Expected Behavior
Connection to S3, plans as normal.

### Actual Behavior
```
Error configuring the backend "s3": error validating provider credentials: error calling sts:GetCallerIdentity: IncompleteSignature: [...] not a valid key=value pair (missing equal-sign) [...]
```

### References

terraform-providers/terraform-provider-aws#6050 appears to be the same issue, but opening it here on request as in my case it pertains to the S3 backend.

(Though note that since that's an early fail, I can't say that it doesn't affect everything else as well.)

### Workaround

Re-generate keys until it does not contain a `/`.

**Comment by jmnsf** [comment]
Also happens if the key contains a `+`

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.

**Comment by OJFord** [comment]
No problem @danieldreier, I use v0.14 personally and v0.13 for work; I'm pretty confident this is fixed in those versions because I use session tokens, so I'd be surprised if I've just been lucky enough not to hit it since.
