### ISSUE TITLE
v0.12 - fractional number being converted to whole one when zero was specified after the point

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform#22159]
### Terraform Version

```
Terraform v0.12.5
```

### Terraform Configuration Files

```hcl
variable "test" {
  default = 1.0
}

output "test" {
  value = var.test
}
```

### Expected Behavior
```hcl
Outputs:
test = 1.0
```

### Actual Behavior

```hcl
Outputs:
test = 1
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context

Some resource arguments requires values to be in the float format. For example [type_handler_version](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html#type_handler_version) of the `virtual_machine_extension` but value is being converted to the whole number when zero is placed after the point .

**Comment by apparentlymart** [comment]
Hi @t3mi!

This `type_handler_version` argument is defined as being a string, not a number. Terraform can automatically convert from number to string, but because a number value doesn't retain any formatting information the conversion must make an arbitrary formatting decision, and the conversion rule is that any whole number is converted to decimal digits with no fractional part and no decimal point.

Since this argument requires a string in a specific format, I'd suggest skipping that conversion altogether and just passing the string in the format the resource type expects, like `"1.0"`. Alternatively, if this number is coming from an outside source whose type you cannot control, you could format it into a string in the format needed using [the `format` function](https://www.terraform.io/docs/configuration/functions/format.html): `format("%.1f", value)`.

Note that in the Terraform language, `1.0` is _not_ a fractional number, no matter how you write it. Whether a number is fractional in Terraform is decided based on its value, not based on the syntax that was used to write it: the expressions `1.0`, `1`, `1.000`, etc all produce identical number values.

**Comment by t3mi** [comment]
@apparentlymart 
Thanks for taking a look into this. I agree ```hcl type_handler_version ``` is not a valid example here.
But regarding the note - wouldn't be better to put it in the docs?
