### ISSUE TITLE
Is terraform state lock supported by gcp now?

### ISSUE THREAD

**Issue by Bharathkumarraju** [hashicorp/terraform#22154]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-google)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

**Comment by teamterraform** [comment]
Hi,
as mentioned in the [docs section of this backend type (gcs)](https://www.terraform.io/docs/backends/types/gcs.html) it does support locking.

If you have questions about that backend we'd suggest to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
