### ISSUE TITLE
attaching multiple SCPs to a single target

### ISSUE THREAD

**Issue by zdogan** [hashicorp/terraform#22178]
Hi there,
I try to attach multiple SCPs to a single target in my code. would like to know if I can use a nested loop in terraform for the following case?
count = "${var.org_type == "root" ? 1 : 0}" 
count = " ${length (var.policy_id)}"

Typical behavior should be asking for org type and read the policy id. However, it does not. 

resource "aw_organizations_policy_attachment" "root" {
count = "${var.org_type == "root"  ? 0:1 length (var.policy_id) }"
policy_id = "${element(var.policy_id, count.index)}"
target_id = "${var.target_id_root}"
}

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
