### ISSUE TITLE
Values of keys in a list of maps are cast to strings

### ISSUE THREAD

**Issue by arthurio** [hashicorp/terraform#22185]
### Terraform Version

```
Terraform v0.12.5
```

### Terraform Configuration Files

```hcl
variable "not_cast" {
  type = list(any)

  default = [{
    a_string = "1"
    a_number = 1
    a_bool   = true
  }]
}

variable "cast" {
  type = list(map(any))

  default = [{
    a_string = "1"
    a_number = 1
    a_bool   = true
  }]
}
```

### Debug Output

```shell
$ terraform console
> var.not_cast
[
  {
    "a_bool" = true
    "a_number" = 1
    "a_string" = "1"
  },
]
> var.cast
[
  {
    "a_bool" = "true"
    "a_number" = "1"
    "a_string" = "1"
  },
]
>
```

### Expected Behavior

Values should keep their respective types.

### Actual Behavior

Values are cast to strings.

### Steps to Reproduce

1. `terraform console`
2.  Type: `var.cast`, then press `enter`

### Additional Context

Also the type checking seems wrong when using `list(map(any))` because the following will fail with error:

```hcl
# my_module/main.tf
variable "worker_groups" {
  type = list(map(any))
}

module "cluster" {
  version = "5.0.0"
  source = "terraform-aws-modules/eks/aws"
  # ...
  worker_groups = var.worker_groups
}
```

```hcl
# main.tf
module "test_type_check" {
  source       = "./my_module"
  worker_groups = [
    {
      instance_type         = "t2.medium"
      asg_min_size          = 1
      asg_max_size          = 15
      autoscaling_enabled   = true
      protect_from_scale_in = true
    },
    {
      instance_type        = "t2.small"
      asg_min_size         = 1
      asg_max_size         = 1
      asg_desired_capacity = 1
      # ⚠️ The following causes the error ⚠️
      subnets              = [aws_subnets.vpc[0].id]
    },
  ]
```

```shell
$ terraform plan

  on main.tf line 50, in module "test_type_check":
  50:   worker_groups = [
  51:     {
  52:       instance_type         = "t2.medium"
  53:       asg_min_size          = 1
  54:       asg_max_size          = 15
  55:       autoscaling_enabled   = true
  56:       protect_from_scale_in = true
  57:     },
  58:     {
  59:       instance_type        = "t2.small"
  60:       asg_min_size         = 1
  61:       asg_max_size         = 1
  62:       asg_desired_capacity = 1
  63        subnets              = [aws_subnets.vpc[0].id]
  64:     },
  65:   ]

The given value is not suitable for child module variable "worker_groups"
defined at my_module/variables.tf:6,1-25: element 1: all map elements must have the
same type.
```

**Comment by apparentlymart** [comment]
Hi @arthurio,

[The `any` keyword](https://www.terraform.io/docs/configuration/types.html#dynamic-types-the-quot-any-quot-constraint) in Terraform is _not_ itself a type, but rather a placeholder for a type that you want Terraform to select automatically. It's an instruction to Terraform to automatically select a single concrete type to replace it.

In your first `variable "cast"` example, Terraform saw the `any` in your `list(map(any))` and examined the default value you provided and found a string, a number, and a bool. Because the language has automatic conversions from number and bool to string, Terraform therefore selected `string` as the concrete type to replace `any`, thus interpreting this value as `list(map(string))` and converting the values to match that type.

In your `variable "not_cast"` case you would've seen the same effect if you had multiple elements in your `list(any)`:

```hcl
variable "another" {
  type = list(any)

  default = ["a", 1]
}
```

In this case, Terraform must once again select a type to replace the `any` placeholder, and in this case it will choose `list(string)` and convert the second element to a string.

The failure you saw in your final example is because the given type constraint cannot be resolved: there is no single type that strings, numbers, bools and lists can all convert to, and so there's no possible type Terraform can select to replace `any` in `list(map(any))`. That is why it reported "all map elements must have the same type".

The Terraform language behaves this way so that Terraform can know the type of `var.example["foo"]` even if `var.example`'s _value_ isn't known yet. That key to how `terraform plan` is able to detect type errors even though the actual value of some resource attributes won't be known until the apply step. This is a similar mechanism to how a compiler in a statically-typed programming language can tell you that you've passed a value of an incorrect type even though the actual value won't be known until runtime.

---

In order to have a mixture of different types for different elements, we must instead use [structural types](https://www.terraform.io/docs/configuration/types.html#structural-types) to specify the concrete type for each element. In your `worker_groups` case in your second example, it looks like the appropriate type here would be as follows, using an object type as the list's element type:

```hcl
variable "worker_groups" {
  type = list(object({
    instance_type         = string
    asg_min_size          = number
    asg_max_size          = number
    asg_desired_capacity  = number
    autoscaling_enabled   = bool
    protect_from_scale_in = bool
    subnets               = set(string)
  }))
}
```

Then Terraform will accept any object value that has the specified set of attributes with suitable types:

```hcl
module "test_type_check" {
  source       = "./my_module"
  worker_groups = [
    {
      instance_type         = "t2.medium"
      asg_min_size          = 1
      asg_max_size          = 15
      asg_desired_capacity  = null
      autoscaling_enabled   = true
      protect_from_scale_in = true
      subnets               = []
    },
    {
      instance_type         = "t2.small"
      asg_min_size          = 1
      asg_max_size          = 1
      asg_desired_capacity  = 1
      autoscaling_enabled   = false
      protect_from_scale_in = false
      subnets               = [aws_subnets.vpc[0].id]
    },
  ]
}
```

**Comment by arthurio** [comment]
@apparentlymart Thanks a lot for the detailed explanation, it makes a lot of sense :)
