### ISSUE TITLE
Plan: 5 to add, 0 to change, 1 to destroy

### ISSUE THREAD

**Issue by akshaymurali1209** [hashicorp/terraform#22194]
Hello All,

I am new to Terraform here . So when i am about to Plan my Script i get the below

Plan: 5 to add, 0 to change, **1 to destroy**

1 to destroy : Is this going to really destroy my resource group which i had modified ? 

I have some queries too , it would be better if i can reach out to anyone . Please provide me your email address whoever can help me on terraforms here. But please answer this question

Also after changing the Resource names , the terraform was trying to delete my resource group from azure . Is this correct? 

azurerm_resource_group.main: Destroying... [id=/subscriptions/ac08ff04-872a-49fb-81f2-2565aec0cabd/resourceGroups/newResourceUS]
azurerm_resource_group.main: Still destroying... [id=/subscriptions/ac08ff04-872a-49fb-81f2-2565aec0cabd/resourceGroups/newResourceUS, 10s elapsed]
^CInterrupt received.

Please help me out here

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
