### ISSUE TITLE
Error downloading modules: Error loading modules: error downloading

### ISSUE THREAD

**Issue by Damarla499** [hashicorp/terraform#22197]
Hi there,

I am getting this issue and unable to come back, when i roll back to 0.11.14 from v12. I am using my windows and this is error when i fire "terraform init" 
Initializing modules...
- module.aws_security_group
  Getting source "../../../../../../modules/aws/network/security-groups"
Error downloading modules: Error loading modules: error downloading 'file://C:/Users/sdamrala/Desktop/terraform/modules/aws/network/security-groups': failed to run mklink .terraform\modules\96f8aeb75410a7374f8ea6557a08407c C:\Users\sdamrala\Desktop\terraform\modules\aws\network\security-groups: exec: "cmd": executable file not found in %PATH% ""

**Comment by teamterraform** [comment]
Hi @Damarla499,

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
