### ISSUE TITLE
How to infer reader endpoint address from aws_elasticache_replication_group with cluster mode disbaled

### ISSUE THREAD

**Issue by rampaldheeraj** [hashicorp/terraform#22201]
I am new to terraform and aws. I have a requirement for provisioning elasticache redis with cluster mode disabled. I have gone through the documentation of aws_elasticache_replication_group resource and it specifies primary_endpoint_address as the address of the endpoint for the primary node in the replication group, if the cluster mode is disabled.

And according to the aws docs:

> For Redis (cluster mode disabled) clusters, use the Primary Endpoint for all write operations. Use the Reader Endpoint to evenly split incoming connections to the endpoint between all read replicas. Use the individual Node Endpoints for read operations (In the API/CLI these are referred to as Read Endpoints).

My question is on how can we get the reader_endpoint_address from aws_elasticache_replication_group?

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
