### ISSUE TITLE
Wrong provider intermittently used with multiple providers in one config source

### ISSUE THREAD

**Issue by codycushing** [hashicorp/terraform#22203]
### Terraform Version
```
0.11.13
```

### Terraform Configuration Files
```hcl
terraform {
  backend "local" {
    path = ""
  }
}

provider "oci" {
  version = ">= 3.0.0"
  tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaa---6lalbq" // dev account
  user_ocid = "ocid1.user.oc1..aaaaaaaa---6ksyoa"
  fingerprint = "ef:28:---:ff:11"
  private_key_path = "/Users/dev/oci.pem"
  region = "us-phoenix-1"
}

provider "oci" {
  version = ">= 3.0.0"
  alias = "test"
  tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaa---56ssva" // test account
  user_ocid = "ocid1.user.oc1..aaaaaaaa---7uplra"
  fingerprint = "ef:28:---:ff:11"
  private_key_path = "/Users/dev/oci.pem"
  region = "us-phoenix-1"
}

resource "oci_core_virtual_network" "debug_vcn"  {
  cidr_block = "10.55.0.0/16"
  compartment_id = "ocid1.compartment.oc1..aaaaaaaa---k3nfrq" // dev compartment
  display_name = "dev_vcn"
}

resource "oci_core_virtual_network" "debug_admin_vcn"  {
  provider = "oci.test"
  cidr_block = "10.66.0.0/16"
  compartment_id = "ocid1.compartment.oc1..aaaaaaaa---6gb6ga" // test compartment
  display_name = "test_vcn"
}
```

### Debug Output
https://gist.github.com/codycushing/0264df99558f0c39903c19db8fd0824c

### Expected Behavior
1. Terraform should use the same provider instance to manage resources previously created with that provider block.
2. When this behavior occurs, `terraform plan` should indicate that a resource was not found and fail.
3. Stored plan output that does not indicate a destructive action should never result in a destructive apply action.

### Actual Behavior
1. Terraform _usually_ employs the correct provider instance for the related resource, but perhaps %10 of the time uses the wrong provider instance. This results in 404s when the resource data is refreshed. Eventually the retry on 404s is exhausted and an error is returned. Terraform tries to make sure the resource exists and creates a new one. Dependencies mapped to the now abandoned resource are mapped to the new resource, or worst case, destroyed and new ones are mapped to the new resource.
2. In every instance, `terraform plan` always passed and showed no difference, in the case where this behavior occurred during plan, it merely took longer as the retry logic needed to be exhausted.
3. Even saved plan output that does not indicate any destructive action can result in destructive action when applied.

### Steps to Reproduce
1. `terraform init -input=false -backend-config="path=./terraform_state"`
2. `terraform plan`
3. `terraform apply -auto-approve`

Generally this results in a noop:
> Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

However, around 1 in 10 repeats of steps 1-3 results in the creation of a new resource and abandonment of the previous resource.

### Additional Context
The special conditions for this scenario are employing two oci provider blocks, each configured with distinct users from different accounts, with a mapping from one provider (via alias) to one portion of resources. 

We investigated internally and found this was not an availability issue with the service (the 404s themselves were not intermittent API failures), rather, requests for operations on the resource in question were being made by a user from an account used in a different provider instance (not the one that originally created the resource).

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
