### ISSUE TITLE
not able to deploy templates in virtual machine scale sets with autoscaling 

### ISSUE THREAD

**Issue by hemapriyamaheswaran** [hashicorp/terraform#22224]
In azure, I am trying to create templates for azure virtual machine scale sets with autoscaling. That templates fully in JSON format. I got one example template and try it as my convenient. almost it completed but virtual machine scale set cannot created. It shows the following error. I don't understand this error.
While I apply the terraform i got the error
-> Terraform apply

Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'rules' on object of type 'TemplateResource'. Path 'properties.template.resources[2].rules', line 1, position 1735.'.
Kindly send me a solution to solve this...
Another error is
Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'networkProfile' on object of type 'TemplateResource'. Path 'properties.template.resources[1].networkProfile', line 1, position 623.'.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
