### ISSUE TITLE
how to add a security group depending upon count 

### ISSUE THREAD

**Issue by safdarq19** [hashicorp/terraform#22225]
Hello,
I am using Terraform 11  version, was wondering how to add a security group that is being created depending on count variable to be added to another security group. 

This works fine when count is true but run into issue when count is false.

Error Message : Error authorizing security group ingress rules: InvalidGroupId.Malformed: Invalid id: "aws_security_group.sg1.id" (expecting "sg-...")

provider "aws" {
  version = ">= 1.38.0"
}

resource "aws_security_group" "sg1" {
  count  = var.required_sg1 ? 1 : 0
  name   = "${var.env}-sg1"
  vpc_id = var.vpc_id
}

resource "aws_security_group" "sg2" {
  name   = "${var.env}-sg2"
  vpc_id = var.vpc_id

  ingress {
    from_port       = 80
    to_port         = 80
    protocol        = "TCP"
    security_groups = ["aws_security_group.sg1.id"]
    self            = true
  }
}

deployment.tf
module "test" {
  source                         = "../terraform/"
  required_sg1 = "false"
  env                            = "testing"
  vpc_id                         = "vpc-xxxxx"
}

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
