### ISSUE TITLE
aws_db_instance engine_version doesn't apply as an update

### ISSUE THREAD

**Issue by nevir** [hashicorp/terraform#2223]
1. Creating a `aws_db_instance` with `engine_version = "9.4.1"`
2. Apply the resource.
3. Modify it so that `engine_version = "9.4"`
4. The provider attempts to apply the change as an update; but it doesn't stick

**Comment by nevir** [comment]
nevermind - `apply_immediately`!

**Comment by nevir** [comment]
(This occurs regardless of `apply_immediately` being set)

**Comment by catsby** [comment]
Hello – Sorry for the silence here. I believe this has been fixed along the way, I tried to reproduce with this confifguation:

```hcl
resource "aws_db_instance" "bar" {
  identifier = "foobarbaz-test-terraform-test"

  allocated_storage = 5
  engine            = "postgres"
  engine_version    = "9.4.1"
  instance_class    = "db.t1.micro"
  name              = "baz"
  password          = "barbarbarbar"
  username          = "foo"

  apply_immediately = true

  backup_retention_period = 0
}
```

Flipping `engine_version    = "9.4.1"` to `9.4.4` worked as expected. After the database rebooted, `terraform plan` reported no changes. Note that in the interim time, it shows a continuous plan/diff because the update hasn't taken affect yet.

Thanks!
