### ISSUE TITLE
unable to convert custom resource type in cloud formation to terraform

### ISSUE THREAD

**Issue by Athulia123** [hashicorp/terraform#22249]
Hi, 

I am trying to convert the below cloud formation custom resource type into terraform .
Is it possible to do this directly convert custom type resource "BucketACL" into terraform?
Or is there a different approach ?

        "BucketACL": {
            "DependsOn": "LambdaPutBucketACL",
            "Type": "Custom::BucketACL",
            "Version": "1.0",
            "Properties": {
                "DeletionPolicy": "Retain",
                "ServiceToken": {
                    "Fn::GetAtt": [
                        "LambdaPutBucketACL",
                        "Arn"
                    ]
                },
                "BucketName": {
                    "Ref": "Bucket"
                },
                "Owner": {
                    "Ref": "CanonicalOwner"
                },
                "Grants": [
                    {
                        "Grantee": {
                            "ID": {
                                "Ref": "CanonicalOwner"
                            },
                            "Type": "CanonicalUser"
                        },
                        "Permission": [
                            "FULL_CONTROL"
                        ]
                    },
                    {
                        "Grantee": {
                            "ID": {
                                "Ref": "CanonicalElastiCache"
                            },
                            "Type": "CanonicalUser"
                        },
                        "Permission": {
                            "Fn::Split": [
                                ",",
                                {
                                    "Ref": "ACLPermissions"
                                }
                            ]
                        }
                    }
                ]
            }
        }

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
