### ISSUE TITLE
Not able to select different partition_fields for different tables using terraform

### ISSUE THREAD

**Issue by ashuclh** [hashicorp/terraform#22268]
### Terraform Version

```
...
```
2.5.0
### Terraform Configuration Files

```hcl
...
```

### Actual Behavior

Able to define table partition column globally for two tables.
I have a file with two timestamp columns .I want to create a table for each timestamp column as a partition_field.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
