### ISSUE TITLE
Corruption of tfstate file

### ISSUE THREAD

**Issue by nikhil226** [hashicorp/terraform#22283]
Hi there,
If terraform state is corrupted how to recover it using automation?

**Comment by teamterraform** [comment]
Hi, @nikhil226. Could you share some more details about the problem?
Do you know how the state file became corrupted?
What commands did you run, and what were their outputs?

**Comment by theTranqu** [comment]
I am facing a similar problem, you could say my statefile is "corrupted".

We have a module for an ELK-Stack deployment, which is stable thus far with TF 0.11.x.
I migrated it to terraform 0.12.6 and ran various tf-plan runs, until it was in a state where I could comfortably run the tf apply, as the plan went through perfectly.

When I actually ran the apply, it failed for a problem that we can replicate with the aws-provider, it is about acm certificate creation and it's validation through route53. (i will open an issue in the provider-section soon)

But this was not a big deal in itself, because on the other modules where we use acm, we could simply apply terraform again and it would go through with finishing the validation everything is fine(it seems to maybe be related to how long terraform waits for the cert validation).

Yet now in our ELK-Stack Module case, when I tried to run the job a second time, after it had failed, I am now stuck with the following error:

> Error: insufficient items for attribute "listener"; must have at least 1

(i have x-ed out some of the ids)
```
... refreshing other resource states ...
10:32:34  module.elk.aws_elb.elb_elk_logstash[0]: Refreshing state... [id=elb-logstash]

10:32:34  module.elk.aws_elasticsearch_domain_policy.policy1: Refreshing state... [id=xxxxx]

10:32:34  module.elk.aws_route53_record.elk_elb_logstash_record[0]: Refreshing state... [id=xxxxxx]

10:32:34  module.elk.aws_launch_configuration.launch_configuration_kibana_01: Refreshing state... [id=xxxxxx]

10:32:34  module.elk.aws_launch_configuration.launch_configuration_logstash_01[0]: Refreshing state... [id=lxxxxxx]

10:32:34  module.elk.aws_acm_certificate.cert: Refreshing state... [id=xxxxxx]

10:32:34  module.elk.aws_autoscaling_group.asg_logstash_01[0]: Refreshing state... [id=xxxxx]

10:32:34  module.elk.aws_autoscaling_policy.scale-in-logstash[0]: Refreshing state... [id=logstash-dev-iss-2-scale-in]

10:32:34  module.elk.aws_autoscaling_policy.scale-out-logstash[0]: Refreshing state... [id=logstash-dev-iss-2-scale-out]

10:32:34  module.elk.aws_cloudwatch_metric_alarm.scale-in-logstash[0]: Refreshing state... [id=logstash-dev-iss-2-scale-in]

10:32:34  module.elk.aws_elb.elb_elk_kibana: Refreshing state... [id=elb-kibana]

10:32:34  module.elk.aws_cloudwatch_metric_alarm.scale-out-logstash[0]: Refreshing state... [id=logstash-dev-iss-2-scale-out]

10:32:35  module.elk.aws_autoscaling_group.asg_kibana_01: Refreshing state... [id=xxxxx]

10:32:37  Error: insufficient items for attribute "listener"; must have at least 1
```
I must assume that the error is related to either the kibana or logstash elb, because it is the only resource that has a listener attribute.

I looked into the state-file, and can clearly see an map/object in the list, which is attached to the listener attribute. 

For Kibana elb:
```
"listener": [
              {
                "instance_port": 5601,
                "instance_protocol": "https",
                "lb_port": 443,
                "lb_protocol": "https",
                "ssl_certificate_id": "xxx-apparently-valid-arn-xxx"
              }
            ],
```

For logstash elb:
```
"listener": [
              {
                "instance_port": 5044,
                "instance_protocol": "tcp",
                "lb_port": 5044,
                "lb_protocol": "tcp",
                "ssl_certificate_id": ""
              }
            ],
```
What was surprising to me is the line:
```                 "ssl_certificate_id": "" ```, I would have expected the value to not be an empty string, but instead "null" - as there is no reference to a ssl_certificate_id in the code whatsoever, it is a tcp listener.
( I am aware of this issue here: https://github.com/terraform-providers/terraform-provider-aws/issues/9304 , which is the only one with our error message- yet our module is in source code and there never was a deployment with a listener setup as https, without ssl_certificate_id)

But all the same, it is a really big problem now for us, the application is broken and I can neither apply nor destroy, because of previous error.

I don't want to manually delete all scraps of the deployment and the statefile, and start from the beginning as we would lose quite a bit of data in our elasticsearch domain and I can not easily run tf-import, because we run terraform through jenkins in a fixed pipeline script.

**Comment by teamterraform** [comment]
Hi @theTranqu ,

Please file a new issue rather than adding to this one, since the original intent here is unknown, and  was likely an unrelated issue. We're going to close this for now, but can continue with the original issue if more information is added.

Thanks
