### ISSUE TITLE
How to define actions in a custom Terraform Provider

### ISSUE THREAD

**Issue by jenyss** [hashicorp/terraform#22288]
Hi, 
Our team is currently writing a custom Provider. The API on which this Provider is based exposes the option to create various resources in a given system. Besides the resources we can also trigger some actions in this system and I would like to ask what is the corresponding Terrafom definition which we need to implement for the actions. For the resources we define the resource block e.g. resource "cda_environment" "firstEnvironment" {}, what should we do for the actions?

Thanks,
Jenya

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. You can also find more information on the [community](https://www.terraform.io/docs/extend/community/index.html) website. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
