### ISSUE TITLE
Is there a way to use a variable when referencing a resource?

### ISSUE THREAD

**Issue by roeezab** [hashicorp/terraform#22309]
Hi,
Now that we finally have for_each for resources (thank you very much for this!), I wanted to reference a resource's attribute, when the resource name is a variable/local I'm using.
It's working for lists, but not for resources. e.g.:
```
locals {
    amis_us-east-1 = {
        ubuntu-18_04 = "ami-07d0cf3af28718ef8"
    }
    
    ec2instances = {
        instance1 = {
            ami           = "ubuntu-18_04"
            subnet_name   = "subnet1"
            ...
        }
    }
}

resource "aws_instance" "ec2instances" {
    for_each        = local.ec2instances
    ami             = local.amis_us-east-1["${each.value.ami}"]   <----- works
    subnet_id       = aws_subnet.${each.value.subnet_name}.id     <----- doesn't work
    ...
}
```

I tried several things with no luck, and eventually I used a workaround to just change the local to include the subnet_id itself, but I wonder if it's possible somehow.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by mildwonkey** [comment]
Hi @roeezab !
You cannot have a variable with an attribute name, as in your example, but you can use the format function to achieve the same goal:

```
subnet_id = format("aws_subnet.%s.id", local.amis_us-east-1[each.value.subnet])
```
I hope this helps!

**Comment by roeezab** [comment]
Hi @mildwonkey,
Thanks for your suggestion! But it doesn't work :/
The example you wrote is not accurate, it should be:
```
subnet_id = format("aws_subnet.%s.id", each.value.subnet_name)
```
But it just creates the string `aws_subnet.subnet1.id` and doesn't translate into the id itself, so when I run `terraform plan` I get:
```
...
~ subnet_id                 = "subnet-XXXXX" -> "aws_subnet.subnet1.id" # forces replacement
...
```
I looked in the documentation if there's a function to complete this translation, but didn't find any. Maybe I should open it as a feature request? 🤔
