### ISSUE TITLE
Unable to destroy resources automatically when my terraform script fails.

### ISSUE THREAD

**Issue by nikhilpulluri-gep** [hashicorp/terraform#22326]
Hi team,

I am unable to destroy a resource when my script fails.
i need to go to portal and delete it manually and then recreate it when there are dependencies.

Please help me what can be done for this.

Thanks.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
