### ISSUE TITLE
[Question] depends_on for kubernetes and helm_release resources 

### ISSUE THREAD

**Issue by yarko686** [hashicorp/terraform#22329]
Hi there,

Does k8s resources and helm resources support dependencies using depends_on?
For example, I want to execute helm modules only after k8s cluster is created.

Also, I am getting the following error:
The name "depends_on" is reserved for use in a future version of Terraform.

It appeared after adding 'depends_on' to module call in main.tf.
Currently, I'm using Terraform v0.12.6

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by mildwonkey** [comment]
To give some additional information:
`depends_on` is only used for resources, not modules. There are several ways to achieve the same goal; the [module composition](https://www.terraform.io/docs/modules/composition.html#dependency-inversion) documentation has some suggestions.
