### ISSUE TITLE
Escape Characters for remote-exec

### ISSUE THREAD

**Issue by montge** [hashicorp/terraform#22327]
I'm trying to figure out the best way to implement the following remote-exec below.  While this appears to be valid JSON, I get a `Error: Invalid reference` with the following details `A reference to a resource type must be followed by at least one attribute access, specifying the resource name.` I was trying to do things natively vs. a embedded bash script.

```
provisioner "remote-exec" {
    inline = [
"sudo grep -qxF 'http_proxy=\"${HTTP_PROXY}\"' /etc/sysconfig/docker || echo 'http_proxy=\"${HTTP_PROXY}\"' | sudo tee -a /etc/sysconfig/docker",
]
}
```

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
