### ISSUE TITLE
[Question] Can I change a classic ELB to AELB with existing configuration

### ISSUE THREAD

**Issue by mbm-rafal** [hashicorp/terraform#22323]
Hello,

I have terraformed setup for AWS classic load balancer, which I want to migrate into AELB. Can I do it by changing configuration file or I'd need to recreate the whole setup?

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

In this case, the [aws provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws) is likely the best place to ask this question.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
