### ISSUE TITLE
Provider Development: Expected type 'string', got unconvertible type '[]interface {}' - with complicated block

### ISSUE THREAD

**Issue by donglev91** [hashicorp/terraform#22346]
Hi there,

I am working on provider development. My template file should support a complicated block like that

```hcl
resource "myresource" "my_resource" {
  name = "my name"
  description = "description"

  deployment_map = {
    "database" = ["target1", "target2", "target3"]
    "comp" = ["target4", "target5"]
  }
}
```

When I run terraform plan, it got error as below

```
'' expected type 'string', got unconvertible type '[]interface {}'
```

In debug mode, the message is as below
```
config is invalid: Incorrect attribute value type: Inappropriate value for attribute "deployment_map": element "database": string required.
```

I think it comes from terraform config/language. Please have a look at that.

Thanks,

**Comment by teamterraform** [comment]
Hi @donglev91 
can you please share the schema for that resource, especially the schema of `deployment_map`?

As the log message suggests, the default type of map values is `TypeString`, when not defined (via `Elem`), while according to your example you seem to need `TypeList`.

**Comment by donglev91** [comment]
Hi there,
I truly forgot to define Elem type, and it got the default one is TypeString as you said. Now I fixed it with more complex schema as your suggestion, it got another error "panic: Unknown validation type: 6". It seems Map value does not support TypeList now (I saw supported types are TypeBool, TypeInt, TypeFloat, TypeString). Please check that. Below is my schema of deployment_map

```
"deployment_map":{  
   Type:schema.TypeMap,
   Elem:&schema.Schema   {  
      Type:schema.TypeList,
      Elem:&schema.Schema      {  
         Type:schema.TypeString,

      },

   },
   Optional:true,

},
```

Thanks for your support.

**Comment by apparentlymart** [comment]
Hi @donglev91,

Indeed, the `schema.TypeMap` type only supports primitive types for `Elem` in the current SDK.

The usual design workaround for situations where more complex nested types are needed is to define the attribute as a string and name it like `deployment_map_json`, and parse the string as JSON inside your implementation.

Terraform 0.12 laid the groundwork for supporting maps of other compound types, but the SDK does not yet expose that functionality because it's currently still supporting both Terraform 0.11 and 0.12, and thus can only offer features that will work with both. There's an existing issue #6215 tracking this limitation, (including some earlier comments from me about exactly why this limitation exists right now, if you're interested). Once it's resolved, the migration path providers using the `_json` string workaround will be to introduce the unsuffixed name as a separate attribute and deprecate the `_json` one, eventually removing it altogether in a major release.

Since we already have #6215 representing this limitation, I'm going to close this one just to keep the discussion consolidated over there. Thanks!

**Comment by donglev91** [comment]
Hi @apparentlymart,

Many thanks for your response. I got your point and waiting for this limitation's resolving :)

BRs,
Dong
