### ISSUE TITLE
Potential case-insensitive import collision

### ISSUE THREAD

**Issue by unknwon** [hashicorp/terraform#22341]
Due to GitHub handle change (to lowercase) for long term purpose, `go get` may fail fetching `github.com/Unknwon/com`. 
Please consider take some time to update it to `github.com/unknwon/com` in the `go.mod` file.
I truly apology for the inconvenience and unintended troubles caused.

**Comment by radeksimko** [comment]
Hi @unknwon 
thank you for the notice.

It looks like we depend on your library through the OpenStack provider, which is a dependency of the Swift backend. I see you [already notified](https://github.com/terraform-providers/terraform-provider-openstack/issues/827) the OpenStack provider. 👍 

The only reason Terraform itself depends on OpenStack is because it shares authentication logic from the OpenStack provider. This has already been extracted to [`gophercloud/utils`](https://github.com/gophercloud/utils/pull/81) (which doesn't depend on your library).

The long term plan is therefore leveraging auth logic in `gophercloud/utils` and avoid any unnecessary transitive dependencies which come with the OpenStack provider.

**Comment by unknwon** [comment]
>It looks like we depend on your library through the OpenStack provider, which is a dependency of the Swift backend. I see you already notified the OpenStack provider. 👍

If the OpenStack provider is not able to update in a timely manner, use `replace github.com/Unknwon/com => github.com/unknwon/com` in `go.mod` file might help!

**Comment by ozerovandrei** [comment]
OpenStack provider dropped usage of this library in https://github.com/terraform-providers/terraform-provider-openstack/pull/865

I guess this issue could be closed.

**Comment by pmalek** [comment]
This is still broken.

```
GO111MODULE=on go get -v -u github.com/hashicorp/terraform@v0.12.24
...
go get: github.com/Unknwon/com@v0.0.0-20151008135407-28b053d5a292 updating to
        github.com/Unknwon/com@v1.0.1: parsing go.mod:
        module declares its path as: github.com/unknwon/com
                but was required as: github.com/Unknwon/com
```

Probably the reason for this is that [as of today - `43c1ec6`](https://github.com/hashicorp/terraform/blob/43c1ec6/go.mod#L118) `terraform` still relies on `github.com/terraform-providers/terraform-provider-openstack v1.15.0` which doesn't have the above mentioned fix https://github.com/terraform-providers/terraform-provider-openstack/pull/865.

So I'm willing to push a PR upgrading `github.com/terraform-providers/terraform-provider-openstack` (let's say to https://github.com/terraform-providers/terraform-provider-openstack/releases/tag/v1.23.0 which is the first version to have the fix) but that might or might not break things.

Anyone here can confirm if it's OK doing this?

**Comment by jbardin** [comment]
Closing as no longer relevant to the current release.
