### ISSUE TITLE
Interpolation/Expressions v0.12

### ISSUE THREAD

**Issue by SnazzyBootMan** [hashicorp/terraform#22350]
Terraform v0.12.5
+ provider.aws v2.20.0
+ provider.null v2.1.2
+ provider.template v2.1.2

With reference to #21411

After reading this https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables and upgrading this doesn't work anymore:

    resource "aws_nat_gateway" "nat_gw" {
      count = local.nat_gw_count

      allocation_id = element(aws_eip.nat_gw.*.id, count.index)
      subnet_id = element(data.terraform_remote_state.remote_state.outputs.subnet_ids_frontend, count.index)
      tags = merge(
        local.default_tags,
        {
          "Name" = "${var.project}_${var.env}_natgw_${count.index}"
        },
      )
    }

Output error is:

    Error: Incorrect attribute value type

      on nat_gw.tf line 56, in resource "aws_route_table_association" "public":
      56:   subnet_id = element(data.terraform_remote_state.remote_state.outputs.subnet_ids_proxy, count.index)

    Inappropriate value for attribute "subnet_id": string required.

**Comment by teamterraform** [comment]
Hi @SnazzyBootMan,

The error indicates that the value for `subnet_id` isn't a string, but unfortunately it does not record what value was actually seen. Can you show the definition of the `subnet_ids_frontend` output in the remote state?

**Comment by soneil123** [comment]
I'm having the same issue:

```
variable "subnet_ids" {
  type        = "list"
}

data "aws_subnet" "subnet" {
  count = "${length(var.subnet_ids)}"
  id    = "${element(var.subnet_ids,count.index)}"
}
```

Error:
```
Error: Incorrect attribute value type

  on main.tf line 3, in data "aws_subnet" "subnet":
   3:   id    = "${element(var.subnet_ids,count.index)}"

Inappropriate value for attribute "id": string required.
```

Output from the remote state (with ids changed):
```
subnet_ids = [
  "subnet-0975fc5f747c85f20",
  "subnet-024f8d953b50b1fba",
  "subnet-0018ff3873856422f",
]
```

**Comment by SnazzyBootMan** [comment]
subnet_ids_frontend = [
  [
    "subnet-03b44ca6123456789",
    "subnet-02e6bf55123456789",
  ],
]

**Comment by SnazzyBootMan** [comment]
So this output is a list of lists and doesn't seem to play nicely with element is this particular instance. I use lists of lists a lot, not through choice but because the remote state file is littered with them.

The answer seems to be this:

    data.terraform_remote_state.remote_state.outputs.subnet_ids_frontend[0][count.index]

I wonder if anyone knows why? I have used the following (which do not try it identify a single element):

    subnets                          = flatten([data.terraform_remote_state.remote_state.outputs.subnet_ids_proxy])

    alb_subnet_ids       = [data.terraform_remote_state.remote_state.outputs.subnet_ids_backend]

    
In Terraform v0.11.* this works:

    subnet_id = "${element(data.terraform_remote_state.remote_state.subnet_ids_egress, count.index)}"

**Comment by teamterraform** [comment]
Hi @SnazzyBootMan,

It appears you were leveraging a bug in 0.11, which would often allow you to assign a nested structure where a single value was required. Since the types are checked for correctness in 0.12, this is no longer possible. 

You will need to refactor the configuration to use the correct types, before Terraform 0.12 can apply them.

**Comment by SnazzyBootMan** [comment]
Interesting, a single value was obtained in v0.11.

**Comment by Jim420** [comment]
Hi, 

I am also hitting the same problem. The module creating the subnets is working fine and returning 2 subnet ids as output. However I am unable to use them when I am trying use then in my module to create instances. I can paste the code here if it helps. 

Thanks

**Comment by Jim420** [comment]
I am using Terraform v0.12.6.
I am using modules to create a VPC,Subnets and EC2 instances.
root.tf 
   vpc.tf
   pub_subnet.tf
   web_server.tf 

vpc.tf and pub_subnet.tf are working fine and displaying the required output. However, I am unable to use the subnet_id from the module pub_subnet.tf as input to my web_server.tf.

The reason being that it is a list and I am getting Inappropriate value for attribute "subnet_id": string required ( I think) 

Looks like I have to read the terraform.tfstate file.

Here is my present code -
root.tf
provider "aws" {
      region = "us-east-1"
    }
    data "terraform_remote_state" "public_subnet" {
    backend = "local"
    config = {
      path = "terraform.tfstate"
    }
    }
    module "my_vpc" {
      source = "../modules/vpc_flowlogs"
      vpc_cidr = "10.0.0.0/16"
  
       }

    module "vpc_igw" {
      source = "../modules/vpc_igw"  
      vpc_id  = "${module.my_vpc.vpc_id}"

    }
    module "public_subnets" {
      source="../modules/pub_subnets"
      vpc_id  = "${module.my_vpc.vpc_id}"
    }

     module "web_servers" {
    source = "../modules/webservers"
    vpc_id  = "${module.my_vpc.vpc_id}"
    subnet_id = 
    "${data.terraform_remote_state.public_subnet.outputs.subnet_id[0]}"
    } 
web_servers.tf

resource "aws_instance" "web-srvs" {
count="${var.instance_count == "0" ? "1" : var.instance_count}"
ami = "ami-035b3c7efe6d061d5"
instance_type = "t2.nano"
key_name="xxx-dev"
subnet_id = "${var.subnet_id}"
vpc_security_group_ids = ["${aws_security_group.pub_sg.id}"]
associate_public_ip_address=true
}


I am trying to use of the two subnet_ids created. I have tried different ways but now running out of ideas. Just as an FYI, my tfstate file is located in the same directory as root.tf

Is it because I using local storage ?
