### ISSUE TITLE
Referencing resource instances created by "for_each"

### ISSUE THREAD

**Issue by jallaix** [hashicorp/terraform#22407]
### Terraform Version
```
Terraform v0.12.6
+ provider.azuread v0.5.1
+ provider.azurerm v1.32.1
+ provider.helm v0.10.1
+ provider.kubernetes v1.8.1
+ provider.null v2.1.2
+ provider.random v2.1.0
```

### Terraform Configuration Files

**azure.tf**
```hcl
variable "customers" {
  type = map(object({name=string}))
}

resource "azurerm_storage_account" "provisioning-datalake" {

  for_each = var.customers

  name                              = "mydatalake${each.key}"
  resource_group_name               = "${azurerm_resource_group.provisioning-group.name}"
  location                          = "${azurerm_databricks_workspace.databricks.location}"
  account_kind                      = "StorageV2"
  account_tier                      = "Standard"
  account_replication_type          = "GRS"
  is_hns_enabled                    = true
  enable_advanced_threat_protection = true

  tags = {
    environment = var.environment
    customer = each.value.name
  }
}

resource "azurerm_key_vault_secret" "key-vault-datalake-secret" {

  for_each = var.customers

  name         = "mydatalake-shared-key-${each.key}"
  value        = azurerm_storage_account.provisioning-datalake[each.key].primary_access_key
  key_vault_id = azurerm_key_vault.key-vault.id

  tags = {
    environment = var.environment
    customer = each.value.name
  }
}
```

**build.tfvars**
```hcl
environment = "Build"
customers = {
  dev = {
    name = "Development"
  },
  int = {
    name = "Integration"
  },
  stg = {
    name = "Staging"
  }
}
```

### Debug Output
[plan.log](https://gist.github.com/jallaix/e4168a9d0019dedc8b21ff0448b8a3b9)

### Expected Behavior
I expect "keyvault-datalake-secret" entries to be created with the matching keys of the generated "provisioning-datalake" resources.

### Actual Behavior
When I run ``terraform plan --var-file=build.tfvars``, I get the following error:
```
Error: Invalid index

  on azure.tf line 45, in resource "azurerm_key_vault_secret" "key-vault-datalake-secret":
  45:   value        = azurerm_storage_account.provisioning-datalake[each.key].primary_access_key
    |----------------
    | azurerm_storage_account.provisioning-datalake is object with 52 attributes
    | each.key is "stg"

The given key does not identify an element in this collection value.


Error: Invalid index

  on azure.tf line 45, in resource "azurerm_key_vault_secret" "key-vault-datalake-secret":
  45:   value        = azurerm_storage_account.provisioning-datalake[each.key].primary_access_key
    |----------------
    | azurerm_storage_account.provisioning-datalake is object with 52 attributes
    | each.key is "int"

The given key does not identify an element in this collection value.


Error: Invalid index

  on azure.tf line 45, in resource "azurerm_key_vault_secret" "key-vault-datalake-secret":
  45:   value        = azurerm_storage_account.provisioning-datalake[each.key].primary_access_key
    |----------------
    | azurerm_storage_account.provisioning-datalake is object with 52 attributes
    | each.key is "dev"

The given key does not identify an element in this collection value.
```

### References

This was originally discussed [on Stack Overflow](https://stackoverflow.com/questions/57412821/referencing-resource-instances-created-by-for-each-in-terraform).

**Comment by apparentlymart** [comment]
I think [this question on the community forum](https://discuss.hashicorp.com/t/output-is-different-between-v0-11-and-v0-12-and-v0-12-will-report-error-if-the-resource-was-created-with-v0-11/2300) may have the same root cause, although the symptoms are different.

It looks like in both of these cases for some reason `azurerm_storage_account.provisioning-datalake` or `aws_instance.this` are returning a single object representing one of the instances of the resource, rather than a map of all of the instances as expected.

In the case described in the initial comment on the issue, that seems to cause an attribute error because `"dev"` (etc) is not a valid attribute for a single `azurerm_storage_account` object.

In the other case shared in the community forum, I think the `for` expression is iterating over the attributes and associated values of a single `aws_instance` object, which is causing a selection of different errors because the attribute values in that object all have different types, and so the value `instance` could be `null` for one attribute, a string for another, an object for another, etc.

In order to get the expected behavior here, referring to either `azurerm_storage_account.provisioning-datalake` or `aws_instance.this` alone must return a map from the instance keys to the objects representing each instance, and then both indexing and iteration over those values would get the expected results in each of these cases.

**Comment by jallaix** [comment]
Write down I have the same problem with the **azurerm_eventhub** resource. I'll use "count" until the problem is solved.
