### ISSUE TITLE
How to map scripts to instances in terraform

### ISSUE THREAD

**Issue by zenvenki** [hashicorp/terraform#22426]
i have two bash scripts A and B and i am requesting two instances in terraform using vra7 provider. how to run script A to instanceA and script B to instance B using remote-exec. tried with the below code. but getting error.

```
resource_configuration = {
              rvar.ip_address = ""
                          }


provisioner "file" {
    source = "/work/scripts/runit.sh"
    destination = "/tmp/runit.sh"

    connection {
    type     = "ssh"
    user     = "${var.username1}"
    host = "${self.resource_configuration.rvar.ip_address[0]}"
    password = "${var.password1}"
    }
  }

  provisioner "remote-exec" {
    inline = [
      "sudo -S <<< ${var.password1} chmod +x /tmp/runit.sh",
      "sudo /tmp/runit.sh"
    ]

    connection {
    type     = "ssh"
    user     = "${var.username1}"
    host = "${self.resource_configuration.rvar.ip_address[0]}"
    password = "${var.password1}"
    }
}

  #second proviioner (file and remote-exec)
  provisioner "file" {
    source = "/work/scripts/runit1.sh"
    destination = "/tmp/runit.sh"

    connection {
    type     = "ssh"
    user     = "${var.username1}"
    host = "${self.resource_configuration.rvar.ip_address[1]}"
    password = "${var.password1}"
    }
  }

  provisioner "remote-exec" {
    inline = [
      "sudo -S <<< ${var.password1} chmod +x /tmp/runit.sh",
      "sudo /tmp/runit.sh"
    ]

    connection {
    type     = "ssh"
    user     = "${var.username1}"
    host = "${self.resource_configuration.rvar.ip_address[1]}"
    password = "${var.password1}"
    }
}
}

```

while running i am getting the below error

`invalid index operation into non-indexable type: TypeString in:`

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
