### ISSUE TITLE
How to create a google compute instance with a docker container?

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#22427]
Hello,
I want to run a single docker container instance on a single compute instance. I can do that manually in the GCP console, specifying the "Deploy a container image to this VM instance" option during the instance setup. How can I do the same by Terraform?

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
