### ISSUE TITLE
Cycle in local-exec

### ISSUE THREAD

**Issue by pszypowicz** [hashicorp/terraform#22436]
I got the `Cycle: aws_instance.web_instances[0], aws_instance.web_instances[1]` error when `web_instance_count` > 1

```
resource "aws_instance" "web_instances" {
  count                  = var.web_instance_count
  ami                    = data.aws_ami.vw_ami.id
  instance_type          = var.web_instance_type
  subnet_id              = aws_subnet.application_private[count.index].id
  vpc_security_group_ids = [aws_security_group.ec2_web_instances.id]
  iam_instance_profile   = aws_iam_instance_profile.instance_profile.name

  provisioner "local-exec" {
    when    = "destroy"
    command = " echo ${aws_instance.web_instances[count.index].id"
  }

}
```

### Terraform Version
```
Terraform v0.12.2
+ provider.aws v2.23.0
+ provider.local v1.3.0
+ provider.random v2.2.0
+ provider.template v2.1.2
```

### Expected Behavior

echo of all instances id

### Actual Behavior

Cycle error

### References

**Comment by teamterraform** [comment]
Hi @pszypowicz!

For destroy-time provisioners, accessing `count.index` like that can be problematic because the index of an instance might be changing as part of destroying others, and so we can end up with effectively one instance depending on another like this, which creates a dependency cycle.

To avoid this, you can use the special `self` reference inside `connection` and `provisioner` blocks, which always refers to the current instance, regardless of its instance key:

```hcl
  provisioner "local-exec" {
    when    = "destroy"
    command = " echo ${self.id}"
  }
```

Destroy-time provisioners unfortunately do tend to have some other issues with dependencies due to their unique characteristics: they are the only situation where we refer to the attributes of an object during its own destruction. Switching to the above may lead to some other errors depending on how the rest of the configuration is written. If you run into more error messages or if you have any other follow-up questions, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
