### ISSUE TITLE
terraform apply -var parsing and quoting issue

### ISSUE THREAD

**Issue by pallxk** [hashicorp/terraform#22431]
I'm seeing discrepancy around `terraform apply -var` between terraform 0.11 and 0.12, and not found related BREAKING CHANGES or issue reports.

I'm going to demonstrate two problems here. One for double quotes parsing, and the other for string variable starting with a number and ending with an equal sign.

### Terraform Version

```
0.11.14
0.12.6
```

### Terraform Configuration Files

```hcl
variable "name" {}

output "name" {
  value = "${var.name}"
}
```

### 0.11.14 Behavior

```
$ terraform apply -var 'name="value"'

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

name = value
```

```
$ terraform apply -var name=1a=

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

name = 1
```

### 0.12.6 Behavior

```
$ terraform apply -var 'name="value"'

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

name = "value"
```

```
$ terraform apply -var name=1a=

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

name = 1a=
```

**Comment by teamterraform** [comment]
Hi @pallxk! Sorry for this weird behaviors in Terraform 0.11.

The Terraform 0.12 behaviors are the correct ones here, and the behaviors you saw in 0.11 were buggy:

* In Unix shells, single quotes `'` are supposed to cause anything inside to be interpreted literally, except escaped single quotes. Therefore it was incorrect that the quotes were stripped off in Terraform 0.11.
* We're honestly not really even sure what strange thing Terraform 0.11 was doing with the value `1a=`, but stripping off any part of the value is incorrect behavior.

Nobody had previously reported these buggy Terraform 0.11 behaviors, so we're sorry we didn't know they'd been fixed in order to document the change in the CHANGELOG. The Terraform 0.12 behaviors are a natural consequence of standard command line processing rules in Unix shells, and are the correct behavior moving forward.

If you have any follow-up questions about this, feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
