### ISSUE TITLE
map value results in error when overriding with var

### ISSUE THREAD

**Issue by arestarh** [hashicorp/terraform#22448]
### Terraform Version

```
Terraform v0.12.6
```

### Terraform Configuration Files

```hcl
// main.tf
# Configure the Azure Provider
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=1.32.1"
}

# Create a resource group
resource "azurerm_resource_group" "rg" {
    name     = "TFRG"
    location = "eastus"
}

# Access information about an existing Key Vault
data "azurerm_key_vault" "key_vault" {
  name                = "${lookup(var.keyvaultinfo, "keyvaultname")}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
}

# Access information about an existing Key Vault Secret
data "azurerm_key_vault_secret" "vmsecret" {
  name         = "${lookup(var.keyvaultinfo, "keyvaulsecretname")}"
  key_vault_id = "${data.azurerm_key_vault.key_vault.id}"
}

// variables.tf
variable "keyvaultinfo" {
    type = "map"

    default = {
        keyvaultname = "tfkeyvault"
        keyvaulsecretname = "password"
    }
}

# terraform apply -var='keyvaultinfo={"keyvaultname":"tfkeyvaultnew","keyvaulsecretname":"passwordnew"}'

```

### Debug Output

https://gist.github.com/arestarh/1877c7090b34cf0bc6ef215b063fa378
### Expected Behavior

Should allow for map variable definition on command line
### Actual Behavior

```
Error: Variables not allowed

  on <value for var.keyvaultinfo> line 1:
  (source code not available)

Variables may not be used here.
```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply -var='keyvaultinfo={"keyvaultname":"tfkeyvaultnew","keyvaulsecretname":"passwordnew"}'`
### Additional Context

Seems like pretty similar issue was opened some time ago:
https://github.com/hashicorp/terraform/issues/20720

In my case it does not matter if I define default value for map variable inside variables.tf or not.

**Comment by teamterraform** [comment]
Hi @arestarh!

Unfortunately I think the issue here lies with the format of the command line rather than with Terraform's main behavior. The error is complaining that variables can't appear in a variable value, which seems strange at first because it doesn't seem like there _are_ any variable references in there, but in the debug log we can see the command line that was passed to Terraform:

```
2019/08/13 17:22:25 [INFO] CLI args: []string{"c:\\Install\\terraform\\terraform.exe", "apply", "-var=keyvaultinfo={keyvaultname:tfkeyvault1,keyvaulsecretname:password}"}
```

You can see here that the quotes have been removed altogether, and so Terraform is seeing those as identifiers that refer to variables rather than as literal strings.

Windows doesn't conventionally accept single quotes as a restrictive quoting character in the same way that Unix shells do, so I think maybe you were using an alternative shell (such as PowerShell, or the Windows port of Bash?) which did the initial parsing of your command line and removed the single quotes, giving this:

```
apply -var=keyvaultinfo={"keyvaultname":"tfkeyvaultnew","keyvaulsecretname":"passwordnew"}
```

...but then that result is subject to the conventional Windows command line handling in [`CommandLineToArgvW`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw) (in Terraform's case, actually the Go port of it, but the same behavior) where quote characters toggle whether space characters end a token or not, but since there aren't any spaces in that second argument anyway the quotes just get stripped out, giving what we saw in the log above.

The easiest way to avoid this sort of problem altogether is to use `-var-file` instead and put your value in a `.tfvars` file. That way it will only be subject to Terraform's own parsing, and won't be interpreted by one or more layers of external command line parsing first.

If that's not an option, you'll unfortunately need to use a different escaping strategy that is compatible with the conventional Windows interpretation of command line arguments, perhaps like this:

```
terraform apply -var=keyvaultinfo={\"keyvaultname\":\"tfkeyvaultnew\",\"keyvaulsecretname\":\"passwordnew\"}
```

If you _are_ using an alternative shell like PowerShell or Bash then things get even more complicated because you need to deal with two levels of escaping: first to make the quotes get interpreted literally by the Windows-style parsing and then again to make sure that result doesn't get altered by the alternative shell on top. For simplicity, we'd suggest running the command with the standard Windows command interpreter (`cmd.exe`), whose escaping rules are designed to work better with the normal Windows command line processing algorithm.

Unfortunately there isn't really anything Terraform can do to compensate for this rather awkward command line handling situation on Windows: by the time Terraform is seeing the arguments they've already passed through these layers. Because of that, we're going to close this out. If you have any further questions about this, please feel free to start a new topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core).
