### ISSUE TITLE
terraform output --module doesn't work

### ISSUE THREAD

**Issue by instigardo** [hashicorp/terraform#22442]
Hi

while executing 
`terraform output --module=abc`  doesn't work and gives error
The -module option is no longer supported since Terraform 0.12
This breaks our current process where we are building modules on target basis.
Is there any workaround to get this done?

**Comment by teamterraform** [comment]
Hi @instigardo,

The `-module` argument was removed from `terraform output` because the Terraform state format no longer tracks anything except root module variables from Terraform 0.12 onwards. The `-target` option [is for exceptional circumstances only](https://www.terraform.io/docs/commands/plan.html#resource-targeting) and should not be used as a regular part of your workflow.

If your system is decomposed such that different modules represent different independent parts of it, you should instead treat each of those modules as a separate configuration and use [data sources](https://www.terraform.io/docs/configuration/data-sources.html) to share values between them as needed. This means that each separate root module will have its own state and its own root outputs which you can read by running `terraform output` in that specific module directory. Running `terraform apply` in one of those separate root modules will naturally scope the change to that specific module, without the need for the `-target` argument.

If you have any follow-up questions about how to move to the recommended workflow we described above, feel free to open a topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core). We use GitHub issues only for tracking specific work items, not for general discussion and questions.

Thanks!
