### ISSUE TITLE
Need terraform to set up Aws system patch manager, please suggest how to proceed.

### ISSUE THREAD

**Issue by amit15277** [hashicorp/terraform#22464]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-google)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
