### ISSUE TITLE
Unable to output AWS subnets ids

### ISSUE THREAD

**Issue by janusz-bb** [hashicorp/terraform#22475]
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.23.0

```

### Terraform Configuration Files

```hcl
resource "aws_subnet" "main" {
  count = length(data.aws_availability_zones.available.names)
  cidr_block = "10.0.${count.index}.0/24"
  vpc_id = var.vpc_id
  map_public_ip_on_launch = true
  availability_zone = data.aws_availability_zones.available.names[count.index]
}
```

The code above creates subnets in all available AZ in a custom VPC.  In order to be able to access these subnets I output (in output.tf in the module directory):

```hcl
output "subnets_ids" {
  value = [aws_subnet.main.*.id]
}
```
I run terraform apply and get all the subnets created but the output is empty.

**Comment by teamterraform** [comment]
Hi @janusz-bb! Sorry for this strange behavior.

Could you share the output of `terraform output -json`, so we can see exactly what value is being saved for this output?

That assumes that it's an output from the _root_ module... if it's an output from a child module then it won't appear in `terraform output` because those outputs are exposed only to references in the calling module. If you want to see them as top-level outputs you'll need to re-export them in the root module:

```hcl
output "subnet_ids" {
  # Assuming your module is declared as: module "example"
  value = module.example.subnet_ids
}
```
