### ISSUE TITLE
Crash with dynamic block using for_each

### ISSUE THREAD

**Issue by rsalmond** [hashicorp/terraform#22481]
### Terraform Version

```
$ terraform12 version
Terraform v0.12.6
+ provider.google v2.12.0
```

### Terraform Configuration Files

```hcl
$ cat main.tf
module "foo" {
  source         = "./testmodule"
  buckets = ["sweet_storage_bucket_one", "sweet_storage_bucket_two"]
}

$ cat ./testmodule/main.tf
variable "buckets" {
  type = list(string)
}

resource "google_storage_bucket" "results" {
  location      = "US-CENTRAL1"
  storage_class = "REGIONAL"
  dynamic "name" {
    for_each = var.buckets
    content {
      name = name.value
    }
  }
}
```

### Debug Output

https://gist.github.com/rsalmond/a2e23c7151423e540c30aa6b6d0f7dae

### Crash Output

https://gist.github.com/rsalmond/f92f5757416f7ec8d7c2cbe51a5df1a6

### Expected Behavior

I dunno tbh I've never used the dymanic construct or the for_each operator. Just testing it out and it is likely I am doing something wrong.

### Actual Behavior

Crashed.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by teamterraform** [comment]
Hi @rsalmond! Sorry for this crash, and thanks for reporting it.

This particular situation ought to have been a validation error rather than a panic, so it's likely our fix here will be to replace this case with an error message rather than to make it do something successful.

The trick here is that `name` is a string argument rather than a nested block, so it's not meaningful to use the `dynamic` block syntax with it.

We think perhaps you were intending to declare one bucket per entry in `var.buckets`, in which case what you need here is resource-level `for_each`, rather than a `dynamic` block. A `dynamic` block is essentially a macro construct for producing zero or more nested blocks of a given type by repetition over a collection, whereas resource-level `for_each` integrates more deeply with Terraform itself and creates multiple instances of the resource in a similar way to `count`.

Here's how to write it with resource `for_each`:

```hcl
variable "buckets" {
  # This is defined as a _set_ of strings rather than a _list_
  # of strings, because the ordering isn't important and we
  # want to identify these buckets by their names rather
  # than their list positions.
  #
  # The calling module can still set this using ["foo", "bar"]
  # syntax, and Terraform will convert it to a set
  # automatically the same way it does for set-typed
  # arguments on resources.
  type = set(string)
}

resource "google_storage_bucket" "results" {
  # for_each over a set creates instances identified by the strings in the set
  for_each = var.buckets

  # each.value is an individual element from the set
  name          = each.value
  location      = "US-CENTRAL1"
  storage_class = "REGIONAL"
}
```

If you plan this with `var.buckets` containing names `"foo"`, `"bar"` then you'll see Terraform plan to create `google_storage_bucket.results["foo"]` and `google_storage_bucket.results["bar"]`, rather than `google_storage_bucket.results[0]` and `google_storage_bucket.results[1]` as it would have with `count`. When elements are added and removed from that `var.buckets` set, Terraform will plan to create or destroy the corresponding resource instances.

We'll keep this issue open to represent fixing the crash, but hopefully the above helps you get a working solution in the mean time. Thanks again for reporting this!

**Comment by rsalmond** [comment]
Heya thanks for the detailed reply, this achieved the desired outcome!

**Comment by danieldreier** [comment]
@rsalmond I re-ran this using 0.13.0 beta 1, and got errors instead of a crash, so I think that the fixed @apparentlymart proposed have been made. I'm going to close this for now. Thank you for reporting this!
