### ISSUE TITLE
terraform init -upgrade doesn't provide adequate steps to remedy error

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#22498]
When updating provider versions I run into this issue frequently enough, but not frequently enough that the answer is obvious to me.  I will get errors like -
```
No provider "aws" plugins meet the constraint "~> 1.66.0".
The version constraint is derived from the "version" argument within the
provider "aws" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.
```
-relaxing the version constraint to nothing is rarely an option, and probably not best practice since that would mean an update could break infrastructure.

-also running terraform providers doesn't shed any light on the way forward.

I'd like to suggest that if this is common enough that better procedures are outlined in the errors output in the terminal.  currently they are are not detailed enough to resolve the problems encountered and each time this occurs it takes a long time to figure out how to update.

I have attempted to use 
either original modules such as-
```
source = "terraform-aws-modules/vpc/aws"
```
or my own updated fork without success.
```
source = "../terraform-aws-vpc"
```

I'm doing this to ensure provider versions are using latest supported version for the last .11.14 release in order to prepare to transition to .12

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "${var.aws_region}"
  version = "~> 1.66.0"
}
```

### Crash Output
```
vagrant@openfirehawkserverdev:/vagrant$ terraform init -upgrade
Upgrading modules...
- module.vpc
  Updating source "./modules/vpc"
- module.bastion
  Updating source "./modules/bastion"
- module.softnas
  Updating source "./modules/softnas"
- module.workstation
  Updating source "./modules/workstation_pcoip"
- module.node
  Updating source "./modules/node_centos"
- module.vpc.vpc
  Updating source "../terraform-aws-vpc"
- module.vpc.vpn
  Updating source "../vpn"
- module.vpc.vpn.openvpn
  Updating source "../tf_aws_openvpn"

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "null" (2.1.2)...
- Downloading plugin for provider "random" (2.2.0)...

No provider "aws" plugins meet the constraint "~> 1.66.0".

The version constraint is derived from the "version" argument within the
provider "aws" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.

vagrant@openfirehawkserverdev:/vagrant$ terraform providers
.
├── provider.aws ~> 1.66.0
├── provider.null ~> 2.0
├── provider.random ~> 2.0
├── module.bastion
│   ├── provider.aws (inherited)
│   └── provider.null (inherited)
├── module.node
│   ├── provider.aws (inherited)
│   ├── provider.null (inherited)
│   └── provider.random (inherited)
├── module.softnas
│   ├── provider.aws (inherited)
│   ├── provider.null (inherited)
│   └── provider.random (inherited)
├── module.vpc
│   ├── provider.aws
│   ├── provider.null (inherited)
│   ├── module.vpc
│       └── provider.aws (inherited)
│   └── module.vpn
│       └── module.openvpn
│           ├── provider.aws (inherited)
│           └── provider.null (inherited)
└── module.workstation
    ├── provider.aws (inherited)
    └── provider.null (inherited)
```

### Expected Behavior
if it can't update, it would be good to provide accurate steps to remedy the behaviour.  I've run into this a few times since I started with terraform.  the steps provided are not adequate to remedy the problem.

### Actual Behavior
no update performed.

```
No provider "aws" plugins meet the constraint "~> 1.66.0".
```

### Steps to Reproduce
```
terraform init -upgrade
```

**Comment by teamterraform** [comment]
Hi @queglay,

We'd like to understand a little better the context for when you saw this error. There is no AWS provider release `1.66.0`, so we're guessing that this was a typo when trying to select a different version... `1.60.0` perhaps?

We're not sure what other advice Terraform could offer in this case because all that Terraform knows here is that there are no versions matching the given constraint. The next step here is to adjust the constraint to be valid, by selecting a version that actually exists. However, if you can share specifically how you got into this situation that might help guide some better messaging for that scenario.

---

For preparing to upgrade from Terraform 0.11 to 0.12, please note that there is a special [upgrade checklist command](https://www.terraform.io/upgrade-guides/0-12.html#pre-upgrade-checklist) in Terraform 0.11.14 intended for this specific purpose: if you initialize your working directory with Terraform 0.11.14 prior to making any other changes and then run `terraform 0.12checklist` it will suggest a specific version constraint to set for each provider to ensure you've selected a 0.12-compatible one.

Note that the suggestion in the upgrade guide is to upgrade to the latest provider version _first_, while still on Terraform 0.11.14, and then only upgrade to Terraform 0.12 once you've seen everything working with the new provider versions. That's because then you can separate responding to any provider-specific breaking changes from the task of updating your configuration for Terraform 0.12, rather than trying to tackle all of these steps at once.

**Comment by queglay** [comment]
I tried to go over again to see where I was provided the information to go to 1.66.0, but it escapes my memory, apologies we can close the ticket -  I was able to transition to 0.11.14, relax the version constraint completely for that purpose, and have upgraded succesfully to .12 now.
