### ISSUE TITLE
Using terraform for loop for flexible assignment of variable 

### ISSUE THREAD

**Issue by DarthVader2409** [hashicorp/terraform#22514]
I am trying to change terraform modules to flex however many "domains" as needed. How can I use new for loop feature in terraform if I want to add any number of domains. For example-

    variable "domains" {
      type = list(string)
    }

    domains = [
      "174.15.22.20",
      "174.15.12.21"
    ]

    domains_1 = element(var.domains, 0) #domain_1=174.15.22.20
    domains_2 = element(var.domains, 1) #domain_2=174.15.12.21

I want to do something like-

     count = length(var.domains)
     for domain in domains:
     domain_$(count.index)= ${element(var.domains, count.index)}

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
