### ISSUE TITLE
Unable to use for_each in resource with array of objects

### ISSUE THREAD

**Issue by EPinci** [hashicorp/terraform#22522]
### Current Terraform Version

```
Terraform v0.12.6
+ provider.azurerm v1.32.1
+ provider.random v2.1.2
```

### Use-cases
I need to create a number of similar resources with different configuration based on an array of maps (or objects).
Basically I'm trying to use the for_each in resource in the same way that dynamics do but this is failing.

### Attempted Solutions

I tried the following but it crashes with "panic: not a string".

`var.spec.databases` is an array of maps (can also be a more complex object).

``` hcl
resource "azurerm_sql_database" "sqldb" {
  for_each = var.spec.databases

  name                             = each.value.name
  resource_group_name              = "some_fixed_value"
  location                         = azurerm_resource_group.resource_group.location
  server_name                      = "some_fixed_value"
  edition                          = each.value.edition
  requested_service_objective_name = each.value.sku
}
```

### Proposal
Allow the for_each to be used in reources the same way that dynamic do.
Also having the iterator will be nice.

**Comment by teamterraform** [comment]
For the crash, this is a known issue with 0.12.6, and will be fixed in 0.12.7 https://github.com/hashicorp/terraform/pull/22279.

However, the way to get the behavior you're seeking is to use a map as `for_each` is designed:

```
{
  dev = { ... some dev settings ... },
  staging = {... some staging settings ... }
}
```

You would then be able to use the [`lookup` function](https://www.terraform.io/docs/configuration/functions/lookup.html) in your configuration on `each.value`. `for_each` does not support lists because it creates resources identified by the keys in the map (or set of strings, if one is used).
