### ISSUE TITLE
Local values failing in resources

### ISSUE THREAD

**Issue by stormfleet** [hashicorp/terraform#22531]
Hi,

Currently using a locals value module to concatenate and execute the result of several variables as follows.
```
resource "null_resource" "test" {
  variable "cmd1" {
    default = "cat"
  }
  variable "cm2" {
    default = "foo.txt"
  }
  variable "bar.txt" {
    default = "cat"
  }
  locals {
    command = "${var.cmd1} ${var.cmd2} ${var.cmd3}"
  }
  provisioner "local-exec" {
    command = "${local.command}
  }"
}
```
However I am getting the error:
```
Error: Reserved block type name in resource block

  on test.tf line 14, in resource "null_resource" "test":
  14:  locals {

The block type name "locals" is reserved for use by Terraform in a future
version.
```

This error is resolved when placing the variables and local value blocks outside of the resource block.
```
variable "cmd1" {
  default = "cat"
}
variable "cmd2" {
  default = "foo.txt"
}
variable "bar.txt" {
  default = "cat"
}
locals {
  command = "${var.cmd1} ${var.cmd2} ${var.cmd3}"
}
resource "null_resource" "test" {
    provisioner "local-exec" {
       command = "{$local.command}"
  }"
}
```

Is this correct syntax to use? I feel like I'm missing something as to why the local values can't be contained within the resource block but that they have to be external to it.

### Reference
- #17229

**Comment by teamterraform** [comment]
Hello! 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

(that said, `variable` and `locals` declarations should indeed be outside the resource declaration, so your second example is correct -- resources should have attributes related to that resource, so that's why you wouldn't put variables in there -- declare them outside the resource and reference them inside the resource :) )
