### ISSUE TITLE
 __builtin_StringToInt: strconv.ParseInt: parsing "$LATEST" of lambda version - invalid syntax

### ISSUE THREAD

**Issue by Punith13** [hashicorp/terraform#22554]
### Terraform Version

```
Terraform v0.11.14
...
```

### Terraform Configuration Files

```hcl
variable "lambda_version" {
  type = "map"

  default = {
    "$LATEST" = "$LATEST"
  }
}

resource "aws_lambda_alias" "lambda_alias" {
  depends_on       = ["aws_lambda_function.createuser"]
  name             = "prod"
  function_name    = "${aws_lambda_function.createuser.arn}"
  function_version = "${lookup(var.lambda_version , aws_lambda_function.createuser.version , aws_lambda_function.createuser.version - 1  )}"

  routing_config = {
    additional_version_weights = "${map("${aws_lambda_function.createuser.version}" , "0.2")}"
  }
}
...
```

### Crash Output

Error: Error refreshing state: 1 error occurred:
	* module.createuser.aws_lambda_alias.lambda_alias: 1 error occurred:
	* module.createuser.aws_lambda_alias.lambda_alias: __builtin_StringToInt: strconv.ParseInt: parsing "$LATEST": invalid syntax in:

${lookup(var.lambda_version , aws_lambda_function.createuser.version , aws_lambda_function.createuser.version - 1  )}

### Actual Behavior

It should handle $LATEST lambda version

**Comment by teamterraform** [comment]
Hi @Punith13,

It looks like part of the issue here is that `function_version` and `version` are both strings, so the expression `aws_lambda_function.createuser.version - 1` may return unexpected results. In this case the value for `aws_lambda_function.createuser.version` is stored as `$LATEST` and it can't be converted to an integer to subtract one.

While the type system in 0.12 generally helps with these things, for backwards compatibility we still allow implicitly converting a string to a number in some cases, which would give you the same result.  The best solution would be to avoid mathematical operations on strings.

This isn't something we can fix in Terraform, but if having access to numeric versions is required, you can open an issue with the AWS provider.

Thanks
