### ISSUE TITLE
Aws Reserved Instance 

### ISSUE THREAD

**Issue by kapilsingh421** [hashicorp/terraform#22566]
Hi there,

I am not able to buy AWS Reserved instance using terraform

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
