### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by erikgreen-x** [hashicorp/terraform#22571]
### Terraform Version

```
0.11.14
```

### Terraform Configuration Files

```hcl
locals {
  deployments = [
    "aaa",
    "bbb",
    "ccc",
    "ddd",
    "eee",
    "fff",
    "ggg",
    "hhh",
    "iii",
    "jjj",
    "kkk",
    "lll",
    "mmm",
    "nnn",
    "ooo",
    "ppp",
    "qqq",
    "rrr",
    "sss",
    "ttt",
  ]
}

module "blahblah" {
  source                     = "../../path/to/module"

  deployments = "${local.deployments}"
}
```

And then in the module:

```hcl
resource "aws_sqs_queue" "primary" {
  count                             = "${length(var.deployments)}"
  name                              = "${var.queue_name}_${var.deployments[count.index]}.fifo"
```

### Debug Output
```
Error: Error refreshing state: 3 errors occurred:
	* module.blahblah.aws_sqs_queue_policy.sqs_policy: 1 error occurred:
	* module.blahblah.aws_sqs_queue_policy.sqs_policy[19]: index 19 out of range for list data.aws_iam_policy_document.sqs_policy.*.json (max 19) in:

${data.aws_iam_policy_document.sqs_policy.*.json[count.index]}
```
The other two errors are of the same type.

### Expected Behavior
The expected behavior is a new queue and policy will be generated for the new deployment type.

### Actual Behavior
_terraform plan_ gives the error listed above.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### Additional Context
After adding a new deployment type to the deployment locals, I began receiving this error.

### References

Originally discussed [in the community forum](https://discuss.hashicorp.com/t/is-there-a-maximum-length-for-lists/2452).

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
