### ISSUE TITLE
Proposal: Add a string match operator =~

### ISSUE THREAD

**Issue by alexjurkiewicz** [hashicorp/terraform#22637]
### Current Terraform Version
```
0.12
```

### Use-cases

It's common to want to test strings against a regular expression, especially in conditional expressions. For example:
1. Check if `var.instance_type` starts with `t2` or `t3`
2. Check if `var.availability_zone` is in `var.region`

### Attempted Solutions

The [`regex(pattern, string)`](https://www.terraform.io/docs/configuration/functions/regex.html) (and sometimes `substr(string, start, length)`) functions provide equivalent functionality.

I think this check is common enough that it deserves a first-class operator.

### Proposal

A new `string =~ pattern` operator which returns a boolean.

Example uses (from above use-cases):

1. Check if `var.instance_type` starts with `t2` or `t3`
```hcl
resource "aws_cloudwatch_alarm" "low_surplus_credits" {
    # Current
    count = regex("^t", vars.instance_type) == "t" ? 1 : 1
    count = substr(vars.instance_type, 0, 1) == "t" ? 1 : 0 # alternate for simple patterns
    # Proposed
    count = vars.instance_type =~ "^t.*" ? 1 : 0
[...]
}
```

2. Check if `var.availability_zone` is in `var.region`
```hcl
# Current
regex("^${var.region}", var.availability_zone) == var.region
# Proposed
var.availability_zone =~ "^${var.region}[a-z]"
```

**Comment by teamterraform** [comment]
Hi @alexjurkiewicz! Thanks for sharing this proposal.

When it comes to designing the Terraform language, we choose between operators vs. functions not by how common a situation is but rather by the (subjective) readability of the resulting expressions.

We use operators for operations like `==`, `+`, etc because these operations have close analogs in mathematical notation such that an expression like `1 + 1` is intuitive to most readers. The set of built-in operators is intentionally minimal because punctuation-based operators are clear only to those who are already familiar with them, and they tend to be difficult to search for when you're unsure what they mean.

The pattern match operator `=~` does not have any such direct analog in mathematics, and is likely familiar only to those who have expertise in a few specific other languages, such as Perl and Ruby. For that reason, we prefer to use a function in this case because then the operation is expressed as a word that the reader can easily search for if they are unfamiliar with it.

For that reason, we don't plan to introduce an operator for regular expression pattern matching. The [`regex`](https://www.terraform.io/docs/configuration/functions/regex.html), [`regexall`](https://www.terraform.io/docs/configuration/functions/regexall.html), and [`replace`](https://www.terraform.io/docs/configuration/functions/replace.html) functions already cover the usual set of functionality we expect based on regular expressions, and we consider the function-based syntax to be superior for the reasons given above.

Thanks again for sharing this proposal! Hopefully the above rationale makes sense.

**Comment by alexjurkiewicz** [comment]
My biggest issue with the function-based syntax is the repetition it causes:

```hcl
# Check if x starts with y
# Current
regex("^${var.region}", var.availability_zone) == var.region
# Proposed
var.availability_zone =~ "^${var.region}.*"
```

Can anything be done about this?
