### ISSUE TITLE
Filename is default.tfstate instead of terraform.tfstate when using prefix under backend config in GCS backend 

### ISSUE THREAD

**Issue by bhegazy** [hashicorp/terraform#22635]
### Terraform Version

```
→ terraform -v
Terraform v0.12.7
```

### Terraform Configuration Files
```hcl
terraform {
  backend "gcs" {
    bucket = "test-bucket-tfstate"
    prefix = "test-folder/terraform.tfstate"
  }
}
```

### Debug Output
https://gist.github.com/bhegazy/607b3bf0c9ad8a53913eaaed75e4930d

### Expected Behavior
Should create Terraform state file `terraform.tfstate` under `test-folder` path

### Actual Behavior
Creates `default.tfstate` file instead of `terraform.tfstate`
example:  `test-folder/terraform.tfstate/default.tfstate`

### Steps to Reproduce
1. `terraform init`
2. `gsutil ls gs://test-bucket-tfstate/test-folder/terraform.tfstate`

### Additional Context
I saw an issue opened in https://github.com/terraform-providers/terraform-provider-google/issues/4158 but it was closed by @rileykarson as he mentioned 

> GCS remote state is managed by a group other than the one that manages the Google provider

### References
https://github.com/terraform-providers/terraform-provider-google/issues/4158
https://github.com/hashicorp/terraform/issues/22333

**Comment by mildwonkey** [comment]
Hi @bhegazy ! Thanks for opening this issue - I'm sorry you got bounced between the provider and here; it's confusing for all of us. 

This is expected behavior according to the [gcs backend documentation](https://www.terraform.io/docs/backends/types/gcs.html#configuration-variables):
```
prefix - (Optional) GCS prefix inside the bucket. Named states for workspaces 
are stored in an object called <prefix>/<name>.tfstate.
```

Since your prefix is `test-folder/terraform.tfstate` and you are in the `default` workspace, the file will be `test-folder/terraform.tfstate/default.tfstate`. If you instead want your state file under `test-folder`, change the `prefix` to `test-folder`.

The state file name (in this case, default.tfstate) is not configurable; we can open a new feature request for that enhancement if it is something you would like to see.

**Comment by bhegazy** [comment]
Hey @mildwonkey  thanks for the explanation, that makes sense, I missed the word *workspaces*. We don't use workspaces for environment separation maybe that is why I did not notice. I think for now the feature is not required for me, so I will be closing the issue. Thanks again!
