### ISSUE TITLE
Dependency graph not applied properly.

### ISSUE THREAD

**Issue by lipsa-vlad** [hashicorp/terraform#22656]
### Terraform Version

```
Terraform v0.12.7
+ provider.aws v2.7.0
+ provider.ignition v1.1.0
+ provider.null v2.1.2
+ provider.template v2.1.2

```

### Terraform Configuration Files

```hcl

# in one module I create a file on s3:
resource "aws_s3_bucket_object" "test" {
  bucket  = var.s3_bucket
  key     = "test.json"
  content = "World!"
  acl     = "private"
}

# and output it:
output "some_content" {
  value = aws_s3_bucket_object.test.content
}

# a different module is using the output from the previous one:

module "mod1" {
  source       = "./subf"
  some_content = module.mod2.some_content
  s3_bucket    = aws_s3_bucket.ignition.bucket
}

# in the content of an ignition file
data "ignition_file" "hello" {
  filesystem = "foo"
  path       = "/hello.txt"
  content {
    content = "Hello ${var.some_content}"
  }
}

data "ignition_filesystem" "data_fs" {
  name = "data"

  mount {
    device = "/dev/xvdb"
    format = "xfs"
  }
}

# the file and filesystem are used to create the ignition config:
data "ignition_config" "test" {
  filesystems = [
    data.ignition_filesystem.data_fs.id,
  ]

  files = [
    data.ignition_file.hello.id,
  ]
}

```

### Expected Behavior

Applying the configuration should have worked.

### Actual Behavior

module.test.aws_s3_bucket.ignition: Creating...
module.test.aws_s3_bucket.ignition: Still creating... [10s elapsed]
module.test.aws_s3_bucket.ignition: Creation complete after 11s [id=com-uberresearch-vlad-k8s-test]
module.test.module.mod2.aws_s3_bucket_object.test: Creating...
module.test.module.mod2.aws_s3_bucket_object.test: Creation complete after 2s [id=test.json]
module.test.module.mod1.data.ignition_file.hello: Refreshing state...
module.test.module.mod1.data.ignition_config.test: Refreshing state...

Error: invalid filesystem "a8392bb17f2efcdafdd004bc8564e2601df2a6f05b23b791dd731ea42e5cc2a7", unknown filesystem id

  on ../test/aws/subf/main.tf line 1, in data "ignition_config" "test":
   1: data "ignition_config" "test" {

### Additional Context

Note that if I remove the ignition_filesystem or the ignition_file from the ignition_config terraform apply runs successfully. Seems to happen only when combining the two resources. Also if the ignition file content is some hardcoded string this also works.

Running terraform apply once more creates the resources without error.

The dependency graph seems ok:

![image](https://user-images.githubusercontent.com/6258883/64028329-1e215f00-cb4b-11e9-9fee-6f087f1677a1.png)

### References

https://github.com/terraform-providers/terraform-provider-ignition/issues/55

**Comment by teamterraform** [comment]
Hi @lipsa-vlad! Sorry for this confusing behavior, and thanks for reporting it.

In situations like this where the graph has all of the right edges but there's still a failure, the common cause has been that the remote system (in this case, the Ignition API) does not have read-after-write consistency and so even though the create call reported success, a subsequent read immediately afterwards detects an error.

Terraform Providers tend to run into this sort of problem because they make many API calls in very quick succession, and so can end up moving faster than the consistency model of the remote system can permit.

It's the role of the provider to do its best to mitigate this sort of problem, by taking whatever actions are possible to make the create behave _as if_ it were read-after-write consistent. A brute-force last resort when no explicit consistency-check API is available is to have the create call spend a little time polling the read endpoint after the create call to await a successful read.

The Ignition provider in particular seems to follow an unusual model of maintaining its own in-memory cache of remote data, and the error you saw here seems to be returned when the given filesystem id is not present in the cache. That cache is managed by the provider itself rather than by Terraform Core, so it's the provider's responsibility to maintain it correctly.

With all of this said, this appears to be an issue with the logic in the provider rather than a problem with Terraform Core. Normally we'd ask our bot to move the issue over to the Ignition provide repository automatically in that case, but it seems like /terraform-providers/terraform-provider-ignition#55 already represents a similar problem, so in this case we're going to just close this out on the assumption that this issue is already covered in the provider. However, if you disagree with that assessment please feel free to open a new issue about this in the provider repository.

Thanks again for reporting this!

**Comment by lipsa-vlad** [comment]
Thanks for the detailed answer.
