### ISSUE TITLE
if Statements terraform 0.12

### ISSUE THREAD

**Issue by wrighbr** [hashicorp/terraform#22663]
Hi There

Are you able to use an if statements in terraform 0.12 within the main.tf. I can see that this is can be done within a template file. But being able to do this within the main.tf would be fantastic.  

I was under the impression that this would be possible in version 0.12? Instead of using the count function as an if statement.

Cheers,

Brett

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
