### ISSUE TITLE
Connection change should trigger null_resource replacement

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22662]
### Terraform Version

```
0.12.7
```

### Terraform Configuration Files

```hcl
resource "null_resource" "blah" {
  connection {
    host = someprovider.server.ip
  }

  provisioner "remote-exec" {
    inline = [
      "echo Important setup",
    ]
  }
}
```

### Expected Behavior
`null_resource.blah` replaced when `someprovider.server.ip` changes.

### Actual Behavior
Once `null_resource.blah` exists, changes in `someprovider.server.ip` do not trigger a change.

### Steps to Reproduce
1. Per above
2. `terraform plan`

### Additional Context
Adding:
```hcl
triggers = {
  ip = someprovider.server.ip
}
```

fixes it of course, but I think it would be less surprising if `connection` was an implied `triggers`.

**Comment by teamterraform** [comment]
Hi @OJFord,

The `connection` block is not really part of a resource. It is part of the provisioner configuration, which can be separated from multiple provisioner blocks for convenience. Terraform does not change a resource with a change in provisioners, as the provisioners are only invoked during specific phases of the resource lifecycle. 

Since this is triggering a logical provisioner on another resource, the correct and expected configuration is to use the `triggers` attribute to cause the resource to be recreated.
