### ISSUE TITLE
v0.12 path.module in submodule - can not find file.

### ISSUE THREAD

**Issue by tomdavidson** [hashicorp/terraform#22660]
I am having troubles with the sue of path.module in a sub module.  The sub module has an external data source with a bash script. When I include the sub module in my plan, terraform can not find the bash script.  If I replace `${path.module}` with the actual full system path, then the plan works as expected so this seems to be an issue with path.module.

### Terraform Version

```
Terraform v0.12.7 (and v0.12.0)
+ provider.external v1.2.0

Bug does not manifest with v0.11.14.
```

### Terraform Configuration Files

```hcl
data "external" "find_files" {
  program = ["bash", "${path.module}/find.sh"]
  
  working_dir = var.search_dir

  query = {
    filter = var.filter
  }
}
...
```

### Debug Output

https://gist.github.com/tomdavidson/26a05aff8b31ee85338ae3b348732dd8

### Crash Output

```shell
Error: failed to execute "bash": bash: src/find-files/find.sh: No such file or directory


  on src/find-files/main.tf line 13, in data "external" "find_files":
  13: data "external" "find_files" {
```

### Expected Behavior

When the external data source is created, the bash script should be found and ran without error - just as it does with v0.11.14.

### Actual Behavior

The above crash error stating the file can not be found. 

### Steps to Reproduce

Create a sub module 'find_files' with the following plan:
https://gist.github.com/tomdavidson/0a41dbbea486ff2ba64b18881c2e57ed

The bash script does not matter, just as long as the file is there.

Next, create a parent module such that:

```hcl
module "team_files" {
  source  = "./src/find-files"

  filter = "*.teams.yaml"
  search_dir = "./teams/"
}
```

```shell
$ terraform init
$ terraform plan
```

### Additional Context

No wrappers. Nothing special

### References

There are five other v0.12 issues with "path.module" mentioned, none seem relevant:
https://github.com/hashicorp/terraform/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Av0.12+%22path.module%22

**Comment by teamterraform** [comment]
Hi @tomdavidson,

The issue here appears to be because you are changing the working directory with the `working_dir` argument, but are passing in the relative directory of the module.

You can use the [`abspath`](https://www.terraform.io/docs/configuration/functions/abspath.html) function to get the full pathname in special cases where it's required.

**Comment by tomdavidson** [comment]
Sure, except that the module work fine with 0.11.14 and the var.search_dir was set to '.', commenting out the working_dir argument yields the exact same behavior ... and `abspath` is just prefix current working directory, why would I want terraform's cwd to be part of the script path?

This issue was closed far too hastily. Please reopen.

**Comment by teamterraform** [comment]
Hi @tomdavidson,

The reason for the change in 0.12 was specifically to _remove_ the working directory from the script path. The `path.module` value in 0.11 may have been passed in as the full path to the stored module source, usually something like

     /home/user/module/.terraform/modules/11c3d4172413463903bcbbc547d52e36/

0.12 now ensures that `path.module` is always relative to the root module, both to prevent changes to resources when applying the same configuration from different systems, and so that paths stored in a plan file are portable across systems. The `abspath` function was added for edge cases where the full path is still required.

Running your example with `working_dir = var.search_dir` commented out seems to work as expected, and adding `abspath` restores the behavior to work from different working directories. The actual path provided is likely different now, due to differences in module storage between 0.11 and 0.12, but that should be transparent as long as the module paths are not being stored in the output.
