### ISSUE TITLE
A reference to resource type must be followed by at least one attribute access, specifying the resource name

### ISSUE THREAD

**Issue by rvashishth** [hashicorp/terraform#22687]
### Terraform Version

```
0.12.7
```

### Terraform Configuration Files

```hcl
locals {
  name_suffix = "${var.namespace != "" ? var.namespace : var.env}"
}

resource "azurerm_container_registry" "link_gateway_acr" {
  name                = "myacr${replace(name_suffix, "-", "")}"
  location            = "${azurerm_resource_group.location}"
  resource_group_name = "${azurerm_resource_group.name}"
  sku                 = "Basic"
  admin_enabled       = true
} 
```

### Expected Behavior

I should see a string concatenation with the use of plain string and string interpolation with a string function
### Actual Behavior

Error: A reference to resource type must be followed by at least one attribute access, specifying the resource name

### Steps to Reproduce

`terraform init`

**Comment by teamterraform** [comment]
Hi @rvashishth,

This error is returned because Terraform thinks that when you wrote `name_suffix` you meant a resource type `name_suffix`, as if there were a block like `resource "name_suffix" "example"` in your configuration.

To access the local value, you need a `local.` prefix, giving `local.name_suffix`.

If you have any follow-up questions about this, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core)!
