### ISSUE TITLE
[Question] Cloud-init security considerations

### ISSUE THREAD

**Issue by tecris** [hashicorp/terraform#22696]
Hi,
First of all thank you for the great work.

I am using terraform to provision vms in azure and for vm customization I am using [template_cloudinit_config](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html).

From clound-init documentation:
[when specifying private keys in cloud-config, care should be taken to ensure that the communication between the data source and the instance is secure](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ssh)

Can you please explain what care should be taken when using [template_cloudinit_config](https://www.terraform.io/docs/providers/template/d/cloudinit_config.html) in general (not only about ssh keys).

thank you

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
