### ISSUE TITLE
Assign Resource or DataSource to a variable fails

### ISSUE THREAD

**Issue by digitalkaoz** [hashicorp/terraform#22713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.8

### Terraform Configuration Files

```hcl
# locals.tf
locals {
	create_db = somecondition
}
```

```hcl
# s3.tf
resource "aws_s3_bucket" "foo" {
	count = local.create_db ? 1 : 0
        bucket = "foo"
}
```

```hcl
# data.tf
data "aws_s3_bucket" "default" {
	count = local.create_db ? 0 : 1
        bucket = "foo"
}
```

when i try the following now:

```hcl
# test.tf
locals {
	bucket_resource = local.create_db ? aws_s3_bucket.foo[0] : data.aws_s3_bucket.default[0]
}
```

i get the following error:

```
Error: Inconsistent conditional result types

  on test.tf line 2, in locals:
  27: 	bucket_resource = local.create_db ? aws_s3_bucket.foo[0] : data.aws_s3_bucket.default[0]
    |----------------
    | aws_s3_bucket.foo[0] is object with 24 attributes
    | local.create_db is true
```

So i want simply use the one or the other resource (created or imported) in my stack!

### Debug Output

-

### Panic Output

-

### Expected Behavior

Terraform should assign the result of the ternary to this variable (resource or datasource)

### Actual Behavior

```
Error: Inconsistent conditional result types

  on test.tf line 2, in locals:
  27: 	bucket_resource = local.create_db ? aws_s3_bucket.foo[0] : data.aws_s3_bucket.default[0]
    |----------------
    | aws_s3_bucket.foo[0] is object with 24 attributes
    | local.create_db is true
```

### Steps to Reproduce

1. `terraform apply` (the above files)

**Comment by teamterraform** [comment]
Hi @digitalkaoz!

Unfortunately Terraform is working as designed here: it requires that both of the result expressions for the conditional have the same type so that it can decide the type of the conditional expression as a whole.

In order to get the result you wanted here, you'll need to decide on what subset of the attributes of each of those objects you need and write expressions to extract those attributes such that the resulting object has the same attributes in both cases. For example, if the other expressions referring to `local.bucket_resource` need the `bucket`, `arn`, bucket_domain_name` and `hosted_zone_id` attributes that are common to both the `aws_s3_bucket` resource type and the `aws_s3_bucket` data source then you could write something like this:

```hcl
locals {
  bucket_resource = local.create_db ? {
    bucket             = aws_s3_bucket.foo[0].bucket
    arn                = aws_s3_bucket.foo[0].arn
    bucket_domain_name = aws_s3_bucket.foo[0].bucket_domain_name
    hosted_zone_id     = aws_s3_bucket.foo[0].hosted_zone_id
  } : {
    bucket             = data.aws_s3_bucket.default[0].bucket
    arn                = data.aws_s3_bucket.default[0].arn
    bucket_domain_name = data.aws_s3_bucket.default[0].bucket_domain_name
    hosted_zone_id     = data.aws_s3_bucket.default[0].hosted_zone_id
  }
}
```

Now in both cases the result is an object with the same set of attributes and thus the result types are consistent.

---

If these variables and resources are in a child module rather than in the root module, we'd recommend considering using [Module Composition patterns](https://www.terraform.io/docs/modules/composition.html) instead. In this specific case, that might mean having three separate smaller modules:

* One that declares a new S3 bucket.
* One that retrieves an existing S3 bucket.
* One that takes arguments describing an S3 bucket and uses them.

The caller will then choose to use either of the first two modules in conjunction with the third in order to decide which S3 bucket to use.

To use a new S3 bucket:

```hcl
module "s3_bucket" {
  source = "./modules/new-s3-bucket"

  # (any required arguments for the bucket)
}

module "uses_s3_bucket" {
  # This is a placeholder for a module that will make use of a given S3 bucket
  source = "./modules/uses-s3-bucket"

  s3_bucket = module.s3_bucket
}
```

To use an existing S3 bucket:

```hcl
module "s3_bucket" {
  source = "./modules/existing-s3-bucket"

  # (any required arguments to _select_ a bucket)
}

module "uses_s3_bucket" {
  # This is a placeholder for a module that will make use of a given S3 bucket
  source = "./modules/uses-s3-bucket"

  s3_bucket = module.s3_bucket
}
```

By splitting up the problem here we can make it easier to introduce other permutations in the future, such as indirectly discovering the appropriate S3 bucket from an explicit configuration service such as SSM Parameter Store or HashiCorp Consul. Separation of concerns often (though certainly not always) makes systems easier to understand and maintain.

Inside the `uses-s3-bucket` module you can declare the `s3_bucket` variable like this:

```hcl
variable "s3_bucket" {
  type = object({
    bucket             = string
    arn                = string
    bucket_domain_name = string
    hosted_zone_id     = string
  })
}

# Other resources in uses-s3-bucket can now refer to the S3 bucket
# values like var.s3_bucket.bucket, var.s3_bucket.arn, etc.
```

...and then in both of the `s3_bucket` module variants you can declare a matching set of outputs so that both module results will conform to that [type constraint](https://www.terraform.io/docs/configuration/types.html):

```hcl
# (using the new-s3-bucket one as an example; the other one would be similar
# but would refer to the data source instead)
output "bucket" {
  value = aws_s3_bucket.example.bucket
}

output "arn" {
  value = aws_s3_bucket.example.arn
}

output "bucket_domain_name" {
  value = aws_s3_bucket.example.bucket_domain_name
}

output "hosted_zone_id" {
  value = aws_s3_bucket.example.hosted_zone_id
}
```

---

What both of these approaches have in common is deciding what aspects of an S3 bucket your referring code needs to access and using a specific object type to represent that idea of an S3 bucket. In the first case we did that inline within a single module using a conditional expression, and in the second case we split the problem up into smaller chunks and let the interfaces between modules explicitly describe the object type and how the data flows.

Since Terraform's type checker is working as designed here we're going to close this out. Hopefully one of the above approaches is useful to help achieve your goal! If you have any follow-up questions, please feel free to start a new topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core).

**Comment by digitalkaoz** [comment]
might somehow be related to https://github.com/hashicorp/terraform/issues/22450 but i didnt get how it might work in my situation

**Comment by digitalkaoz** [comment]
@teamterraform thanks for the explanation! i get it :) thanks
