### ISSUE TITLE
Data source: `remote_file`

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22738]
### Current Terraform Version

```
0.12.8
```

### Use-cases
To read and provision local files, we have `data.local_file` and the `local_file` resource;
to provision remote files we have the `file` provisioner;

but I often find myself wanting to _read_ remote files, for example:
- public keys, certificates
- config generated during provisioning (e.g. a kubeconf file)
- some property of the system exposed in resource attrs

### Attempted Solutions
```hcl
data "external" "myfile" {
  program = ["${path.module}/get-myfile"]
  query = local.ssh_conn
}
```

or if feeling particularly brave, inline with something like:
```hcl
program = ["ssh", "${local.user}@${local.host}", "--", "sh", "-c", "jq -n --arg myfile \"$(cat myfile)\" '{$myfile}"]
```
or switching around `jq` and `ssh` to avoid it on the server, for example, to download a kubeconf I use:
```hcl
data "external" "kubeconf" {
  program = [
    "sh",
    "-c",
    "jq -n --arg kubeconf \"$(ssh ${local.user}@${local.host} cat /etc/kubernetes/admin.conf)\" '{$kubeconf}'",
  ]
}

resource "local_file" "kubeconf" {
  sensitive_content = data.external.kubeconf.result.kubeconf
  filename          =  local.kubeconf_path
}
```

### Proposal
I imagine it being something like:
```hcl
locals {
  ssh_conn = {
    agent = true
    host = "example.com"
    user = "root"
  }
}

data "remote_file" "myfile" {
  # attr because this isn't a provisioner, but analogous to connection block
  remote_conn = local.ssh_conn
  filename = "/etc/myfile"
}

# exported attrs analogous to data.local_file:
locals {
  myfile_contents = data.remote_file.myfile.content
  mybinfile = data.remote_file.myfile.content_base64
}
```

**Comment by teamterraform** [comment]
Hi @OJFord! Thanks for sharing this use-case.

This is something we've pondered before, particularly in the vicinity of #2756 which would -- if implemented as imagined so far -- likely lead to there being an `ssh` provider that could then be home to an `ssh_file` resource type and an `ssh_file` data source.

We'd probably go for being specific and calling it `ssh_file` rather than just `remote_file` because we tend to think it's better to be explicit about this sort of thing: the behavior of SSH and WinRM is different enough that we've often considered the conflation of them for provisioner connections to be something of a mistake; the design of _those_ is already quite entrenched at this point and so not easy to change without some significant rework, but for introducing a new data source doing it in an SSH-specific provider (and optionally, if there's demand for it, a similar `winrm` provider) from the outset seems clearer and more consistent with the level of abstraction Terraform resource types and data sources normally work at.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere. If others would also like to see this implemented we'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

Normally we'd encourage PRs in this case too, but since this would be a new provider the procedure here is a bit different: providers (with the exception of the special `terraform` provider) live in separate repositories, and so there's no way to contribute one via a PR to _this_ repository. Instead, providers normally start their lives as Git repositories in some other account, and can then be adopted into the HashiCorp-hosted set via [the provider development program](https://www.terraform.io/guides/terraform-provider-development-program.html). We're also still planning to introduce automatic installation for third-party-maintained providers in a future release, which will decrease the overhead of making relatively simple providers like this one available for Terraform users.

(Please don't leave new _comments_ with :+1: and similar upvote messages, because they just create noise for those who are subscribed to the issue, and don't create any signal that the Terraform team can report on.)

**Comment by OJFord** [comment]
I've rarely used Go and not for some time, so I'm not well placed to write a provider.

I have abstracted my workaround as described in OP to a module though, which is now published on Terraform Registry: https://registry.terraform.io/modules/OJFord/ssh_file

I followed the suggestion above to call it `ssh_file` instead of `remote_file`, and tried to keep the API consistent with provisoner `connection`s  and `local_file` attrs/outputs. Any feedback welcome on its repo: https://github.com/OJFord/terraform-module-ssh_file

If anyone else wishes to make a provider for `data "ssh_file`, that's a better API for it than `module`s, so I'd still be a keen user!

**Comment by romanvilu** [comment]
Up. Terraform definitely needs this for better integration with non-native providers (Kubernetes is a typical example).

**Comment by OJFord** [comment]
I have written and contributed to a few providers since my above comment (one at least before actually..) - but I just did a quick search and found https://registry.terraform.io/providers/tenstad/remote/latest/docs/resources/file, so I think that's probably the way to go for someone looking for this currently.

(Certainly probably don't use the module I wrote & haven't touched in years over it! 😅)
