### ISSUE TITLE
[docs] Configuration language > functions menu behaves weirdly

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22736]
This may seem like an odd minor nitpick, but I find the functions docs quite frustrating, since they're under 'Configuration language' when not open, but when opened that menu closes and 'functions' is promoted to the the level above. Nested menus exist in another places, and indeed under 'functions' itself, so perhaps this isn't deliberate?

I recorded a video but GH doesn't allow attaching it, so this is before:
https://www.terraform.io/docs/configuration/index.html
<img width="180" alt="Screen Shot 2019-09-07 at 15 52 53" src="https://user-images.githubusercontent.com/3946014/64476542-a9bc7080-d187-11e9-84b3-8cb6a9bd779f.png">

and after clicking 'Functions':
https://www.terraform.io/docs/configuration/functions.html
<img width="180" alt="Screen Shot 2019-09-07 at 15 53 06" src="https://user-images.githubusercontent.com/3946014/64476546-b04ae800-d187-11e9-84b5-6360b16cd1cb.png">

Note also that when 'Functions' is promoted to the top-level, it replaces all other siblings of 'Configuration Language' - e.g. to get from 'Functions' to 'Providers' you have first to click into 'Configuration Language', even though it doesn't contain 'Providers' once you do.

**Comment by teamterraform** [comment]
Hi @OJFord! Thanks for reporting this.

Indeed, it's typical on the Terraform website that navigation more than two levels deep behaves this way. The navigation currently only supports navigation two levels deep, which is awkward for situations like this where one section of documentation contains a two-level hierarchy of its own.

It's unlikely anything can change here in the near future, but we'll keep this open to record the limitation to see if a future redesign of the site (which is planned eventually to bring the site under the new HashiCorp documentation site design, currently visible for [Vault](https://www.vaultproject.io/)) can address it.

Another thing we're hoping to do eventually, which might give another path to address this, is to rework the information architecture so that "Terraform Language" is a top-level navigation item separate from "Terraform CLI". The current navigation is a historical artifact of when "Terraform CLI" was the _only_ thing documented here, but now there's various other Terraform components alongside.

**Comment by mildwonkey** [comment]
The page has been updated since this issue was opened, and I know that there's internal efforts ongoing, so I am going to close this issue - it's being handled outside of this repository now. Thanks!

**Comment by OJFord** [comment]
Ok, thanks, to be clear it is still an issue with the page as it is today, and it seems to me like it still comes from `/website/layouts` & `/website/docs` in this repository, but I assume you just mean you're not using this issue tracker for docs/site stuff.

Cheers.
