### ISSUE TITLE
Update golang to 1.13

### ISSUE THREAD

**Issue by karuppiah7890** [hashicorp/terraform#22748]
### Proposal
Update the golang version while building - for dev environment and CI/CD too

I'm willing to raise a PR for the same. Will surely need help after raising the PR as I don't know all the places where golang versions are referred

### References
https://golang.org/doc/go1.13#godoc

**Comment by teamterraform** [comment]
Hi @karuppiah7890,

We do not plan to switch to Go 1.13 yet, because upgrading will lead to some breaking changes in the released executables that we need to release carefully. The Terraform team will manage the upgrade process and will represent when Terraform has switched to Go 1.13 for development by updating the `.go-version` filein the root of this repository.

Until then, Terraform continues to be developed and built with Go 1.12.

Thanks for your interest! Please look out for updates to the `.go-version` file to see when Terraform has switched to building with Go 1.13.

**Comment by karuppiah7890** [comment]
Oh. I didn't know there will be breaking changes. I assumed minor version upgrading has no breaking changes. Have to check golang docs to understand better 😅 thanks for the prompt response! Hoping to contribute to terraform in the future 😄
