### ISSUE TITLE
Plan rendering for unknown number of dynamic blocks is misleading

### ISSUE THREAD

**Issue by geekifier** [hashicorp/terraform#22743]
### Terraform Version

```
Terraform v0.12.8
```

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~> 2.1"
  region  = "ap-southeast-1"
}

data "aws_availability_zones" "available" {
  state = "available"
}

variable "tf_region" {
  default = "ap-southeast-1"
}

locals {
  subnets_private      = ["10.10.10.0/24", "10.10.11.0/24", "10.10.12.0/24"]
  vpc_cidr             = "10.10.8.0/21"
  az_ids               = ["apse1-az1", "apse1-az2", "apse1-az3"]
  vpc_name             = "test"
  r53_resolver_subnets = { for subnet in aws_subnet.private : subnet.availability_zone => subnet.id... if length(local.subnets_private) > 0 }
  common_tags = {
    Environment = "Foo"
    Terraform   = "True"
  }
  selected_tags = merge(local.common_tags, {})
  selected_az_suffixes     = [for az in local.az_ids : substr(az, -3, 3)]

}

resource "aws_vpc" "vpc" {
  cidr_block = local.vpc_cidr

  tags = merge(local.selected_tags, { Name = local.vpc_name })
}

resource "aws_subnet" "private" {
  count                = 3
  vpc_id      = aws_vpc.vpc.id
  cidr_block           = element(local.subnets_private, count.index)
  availability_zone_id = element(local.az_ids, count.index)

  tags = merge(local.selected_tags, { Type = "Private" }, { Name = "${local.vpc_name}-private_${count.index + 1}-${element(local.selected_az_suffixes, count.index)}" })
}

resource "aws_security_group" "r53_outbound" {
  name        = "serviceR53InboundResolver"
  description = "Route53 Inbound Resolver SG"
  vpc_id      = aws_vpc.vpc.id

  tags = merge(local.selected_tags, { Name = "serviceR53InboundResolver" })
}

resource "aws_security_group_rule" "InboundDnsQueries" {
  type        = "ingress"
  from_port   = 53
  to_port     = 53
  protocol    = -1
  cidr_blocks = ["${local.vpc_cidr}"]

  security_group_id = aws_security_group.r53_outbound.id
}

resource "aws_security_group_rule" "OutboundDnsQueries" {
  type        = "egress"
  from_port   = 53
  to_port     = 53
  protocol    = -1
  cidr_blocks = ["0.0.0.0/0"]

  security_group_id = aws_security_group.r53_outbound.id
}

resource "aws_route53_resolver_endpoint" "outbound" {
  count              = length(local.subnets_private) > 0 ? 1 : 0
  name               = "${local.vpc_name}-Outbound"
  direction          = "OUTBOUND"
  security_group_ids = ["${aws_security_group.r53_outbound.id}"]
  tags               = merge(local.common_tags, { Name = "${local.vpc_name}-Outbound" })
  dynamic "ip_address" {
    for_each = local.r53_resolver_subnets
    content {
      # select only 1 private subnet from each AZ in the VPC
      subnet_id = ip_address.value[0]
      ip        = null
    }
  }
}

output "r53_resolver_subnets" {
  value = local.r53_resolver_subnets
}

output "resolver" {
  value = aws_route53_resolver_endpoint.outbound
}
```

### Debug Output

https://gist.github.com/geekifier/2c13ba6957f5e1477c52f1f23c8e86a2

Encrypted with Hashicorp's GPG Key.

### Expected Behavior

Diff showing replacement of 1 of the aws_route53_resolver_endpoint ENIs.

### Actual Behavior

Diff shows removal of ALL ip_address blocks and replacement with ONE block.
In this example, the improper resource computation causes a failure to remove the resolver IPs from the subnet, thus preventing subnets from being replaced.

```hcl
 # aws_route53_resolver_endpoint.outbound[0] will be updated in-place
  ~ resource "aws_route53_resolver_endpoint" "outbound" {
        arn                = "arn:aws:route53resolver:ap-southeast-1:<REMOVED>:resolver-endpoint/rslvr-out-9055cef531c842a49"
        direction          = "OUTBOUND"
        host_vpc_id        = "vpc-06dcab44f9bd3544e"
        id                 = "rslvr-out-9055cef531c842a49"
        name               = "test-Outbound"
        security_group_ids = [
            "sg-064e6fad5f7507a0b",
        ]
        tags               = {
            "Environment" = "Foo"
            "Name"        = "test-Outbound"
            "Terraform"   = "True"
        }

      - ip_address {
          - ip        = "10.10.10.182" -> null
          - ip_id     = "rni-948c0c26750c46abb" -> null
          - subnet_id = "subnet-0537f0be6db880e63" -> null
        }
      - ip_address {
          - ip        = "10.10.11.136" -> null
          - ip_id     = "rni-dc9224c65bdf4acbb" -> null
          - subnet_id = "subnet-0ccea91fda1b8e097" -> null
        }
      - ip_address {
          - ip        = "10.10.12.176" -> null
          - ip_id     = "rni-db8170e223cc4b87a" -> null
          - subnet_id = "subnet-0efba701a0683f494" -> null
        }
      + ip_address {
          + ip        = (known after apply)
          + ip_id     = (known after apply)
          + subnet_id = (known after apply)
        }
    }
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Change local `az_ids` to `["apse1-az1", "apse1-az2"]` (remove one item from list)
4. terraform apply

**Comment by teamterraform** [comment]
Hi @geekifier! Sorry for this strange behavior.

What you're seeing here is a bit of an edge-case in the `dynamic` block behavior: `local.r53_resolver_subnets` is itself unknown during planning, and so Terraform _doesn't know_ how many `ip_address` blocks there will be after apply. Because `dynamic` blocks work as a sort of macro expansion, they respond to a totally-unknown input collection by producing just one block with all of its contents unknown (that is, `(known after apply)`) and then wait to produce the full expansion until the apply step. This is because blocks themselves cannot be unknown, only arguments within them.

The reason this arises in this _particular_ case is that you're using the availability zone strings as keys but you're setting `availability_zone_id` on the subnets, and so the values of `availability_zone` aren't known until after apply. The AWS provider could potentially mitigate this by looking up which `availability_zone` name corresponds to each `availability_zone_id` at plan time (assuming there's an API action available for that) and thus populating `availability_zone` early, but as long as the provider isn't doing that we'd recommend considering using the `availability_zone_id` strings as the map keys instead, and then the map will be known at plan time and Terraform should be able to produce a more specific plan that will indiciate the correct number of blocks.

Over here in Terraform Core we're going to use this to represent the fact that the representation of an unknown number of blocks is confusing, and hope to resolve it by finding a better way to represent it. Unfortunately this is not just a UI-level problem because the handling of `dynamic` blocks happens during configuration evaluation, long before the plan output is rendered, but hopefully we can eventually find a way to adjust the internal representation of this to give the UI a hint so it can indicate this better.

It might also be worth opening in an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) to discuss whether it's feasible for the `aws_subnet` resource to predict the `availability_zone` value at planning time if `availability_zone_id` is set, which would then give Terraform more information during planning and allow it to produce a more precise plan. The core team isn't sure if such a thing is technically possible with the AWS API; the AWS provider team will have a better sense of that.

**Comment by geekifier** [comment]
Thank you for the detailed response.

It might be interesting to note, that when creating the resource for the first time, it does correctly determine the amount of objects that will need to be created:

```hcl
 # aws_route53_resolver_endpoint.outbound[0] will be created
  + resource "aws_route53_resolver_endpoint" "outbound" {
      + arn                = (known after apply)
      + direction          = "OUTBOUND"
      + host_vpc_id        = (known after apply)
      + id                 = (known after apply)
      + name               = "test-Outbound"
      + security_group_ids = (known after apply)
      + tags               = {
          + "Environment" = "Foo"
          + "Name"        = "test-Outbound"
          + "Terraform"   = "True"
        }

      + ip_address {
          + ip        = (known after apply)
          + ip_id     = (known after apply)
          + subnet_id = (known after apply)
        }
      + ip_address {
          + ip        = (known after apply)
          + ip_id     = (known after apply)
          + subnet_id = (known after apply)
        }
      + ip_address {
          + ip        = (known after apply)
          + ip_id     = (known after apply)
          + subnet_id = (known after apply)
        }
    }
```

Similarly, when I changed to using availablity_zone_ids as keys, the diff produced does look much better:

```hcl
  # aws_route53_resolver_endpoint.outbound[0] will be updated in-place
  ~ resource "aws_route53_resolver_endpoint" "outbound" {
        arn                = "arn:aws:route53resolver:ap-southeast-1:736176406297:resolver-endpoint/rslvr-out-c4fa0b13271a4c059"
        direction          = "OUTBOUND"
        host_vpc_id        = "vpc-0ad061ebc5941ec58"
        id                 = "rslvr-out-c4fa0b13271a4c059"
        name               = "test-Outbound"
        security_group_ids = [
            "sg-0aff877d7066a4015",
        ]
        tags               = {
            "Environment" = "Foo"
            "Name"        = "test-Outbound"
            "Terraform"   = "True"
        }

        ip_address {
            ip        = "10.10.10.189"
            ip_id     = "rni-c155d5b603e547eaa"
            subnet_id = "subnet-03fac71c002c40fac"
        }
        ip_address {
            ip        = "10.10.11.76"
            ip_id     = "rni-b917084b8a114b4b8"
            subnet_id = "subnet-0d61a22daf3ac3f84"
        }
      - ip_address {
          - ip        = "10.10.12.82" -> null
          - ip_id     = "rni-1e44f05623e9432a9" -> null
          - subnet_id = "subnet-0c3a0fb5e89e2f001" -> null
        }
    }
```
However, the order of operations still does not seem right to me. Terraform is still _not destroying_ the resolver listener ENIs from the subnets being removed.

This causes the subnet deletion to fail (since you cannot delete a subnet with ENIs in that subnet).

```hcl
Plan: 1 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_subnet.private[2]: Destroying... [id=subnet-0c3a0fb5e89e2f001]
aws_subnet.private[2]: Still destroying... [id=subnet-0c3a0fb5e89e2f001, 10s elapsed]
aws_subnet.private[2]: Still destroying... [id=subnet-0c3a0fb5e89e2f001, 20s elapsed]
aws_subnet.private[2]: Still destroying... [id=subnet-0c3a0fb5e89e2f001, 30s elapsed]
aws_subnet.private[2]: Still destroying... [id=subnet-0c3a0fb5e89e2f001, 40s elapsed]
aws_subnet.private[2]: Still destroying... [id=subnet-0c3a0fb5e89e2f001, 50s elapsed]
aws_subnet.private[2]: Still destroying... [id=subnet-0c3a0fb5e89e2f001, 1m0s elapsed]

Error: Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 1m0s)
```

Let me know if it would be helful to provide a debug log of this run (with az IDs as keys, proper plan, but still failing to remove resources).

**Comment by apparentlymart** [comment]
Hello again! Sorry for the long silence.

I mentioned previously that a root constraint here is that blocks can't be unknown, but I didn't actually say _why_ that is true. Revisiting this again now, I want to add that the special constraints around blocks are a concession to the behaviors and limitations of the old SDK that Terraform providers have been written against for many years now, which has certain special assumptions about blocks -- including that the set of blocks as a whole may never be unknown -- which we preserved in Terraform v0.12 in order to avoid breaking the large corpus of existing Terraform provider code.

The Terraform SDK team has been working on [a new provider development framework](https://github.com/hashicorp/terraform-plugin-framework) that's designed from the beginning around the Terraform v0.12-and-later type system, and so it no longer needs these special block behaviors and generally prefers to treat everything as an attribute using the `=` assignment syntax, instead of the old block syntax.

Given that the block behaviors are constrained by old SDK behavior that existing providers depend on (which we can't change retroactively) and the new SDK treats blocks as a deprecated/legacy mechanism, it seems very unlikely to me that we'll be able to change the behavior for unknown numbers of dynamic blocks and will instead gradually phase out using `dynamic` blocks altogether, as more providers start to use the new SDK and thus no longer need that special syntax in order to enforce the invariants expected by the old SDK.

For that reason, I'm going to close this just to be explicit that we're treating this as an "it is what it is" sort of situation: we agree that it's non-ideal but it seems as good as it can be within the constraints it's designed under, and we have a plan to gradually move away from it anyway.

Thanks for reporting this!
