### ISSUE TITLE
Include a specific -target argument in "Invalid count argument" and "Invalid for_each argument" error messages

### ISSUE THREAD

**Issue by canozokur** [hashicorp/terraform#22768]
Hello!

Thanks for keeping Terraform updated with fantastic additions, like for_each expressions. But I think for_each expressions should be more informative with its errors. Let's see the use case and let me explain if I can.

Use-Case
-----------
Suppose on Amazon we're creating two instances, a LB target group and try to attach those two instances to the target group.

```
resource "aws_instance" "webserver" {
  count                       = 2
  ...other arguments...
}

resource "aws_lb_target_group" "webserver" {
}

resource "aws_lb_target_group_attachment" "webserver" {
  for_each = toset(aws_instance.webserver[*].id)
  target_group_arn = aws_lb_target_group.webserver.arn
  target_id = each.value
  port = 80
}
```
This, of course, causes the following error because we still don't know the instance IDs. They are not yet created.
```
Error: Invalid for_each argument

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

Okay, fine. We can find the for_each and its dependency on `aws_instance.webserver` resource easily because we don't have many resources (or modules). Imagine doing this in a lot of resources.

I think if Terraform somehow can inform the users which line this `for_each` resides on or (even better) which resource they need to `-target` first, this would go really smoother for them. No more searching for every `for_each` expression to see which resource they **may** have referred (which is not created, yet).

Thanks!

**Comment by apparentlymart** [comment]
As part of resolving https://github.com/hashicorp/terraform/issues/30937, the two error messages discussed in this issue are going to be removed altogether in favor of Terraform automatically detecting that certain resources cannot be planned and automatically "deferring" their actions to a future plan.

What we're implementing for that is essentially the same as what was proposed here except that rather than just telling the user what to target and making them run a separate command to achieve it Terraform will use its conclusion to _automatically_ skip planning what it can't plan. This won't be exactly the same as `-target` because Terraform will still visit and shallowly-validate the resources in question, but it'll achieve a similar result.

Therefore I'm going to close this issue just to consolidate it with the broader issue that'll eventually address it.

Thanks!
