### ISSUE TITLE
Destroy Bug: event rules should be deleted after resources they are depending of

### ISSUE THREAD

**Issue by mihaibaumgarten** [hashicorp/terraform#22767]
### Terraform Version
```
Terraform v0.12.8
+ provider.archive v1.2.2
+ provider.aws v2.12.0
+ provider.template v2.1.2
```

### Terraform Configuration Files
```
resource "aws_cloudwatch_event_rule" "my-schedule" {
  name                = "my-schedule"
  description         = "Fires every day at 4PM CEST / 7 AM PST."
  schedule_expression = "cron(0 14 * * ? *)"
}
resource "aws_cloudwatch_event_target" "my-target" {
  rule      = "${aws_cloudwatch_event_rule.my-schedule.name}"
  target_id = "my-lambda"
  arn       = "${aws_lambda_function.my-lambda.arn}"
}
```

### Crash Output
```
* aws_cloudwatch_event_rule.my-schedule: Error deleting CloudWatch Event Rule: ValidationException: Rule can't be deleted since it has targets.
	status code: 400, request id: XXXXXX
```

### Expected Behavior
Terraform should have removed the lambda function before attempting to remove the cloudwatch events rule linked to this lambda function. In this case, the events rule is only used to one lambda function and they are both deployed and updated only with Terraform.

### Actual Behavior
Terraform attempts to remove the CW events rule before the Lambda function that used it, so everything is okay at the end but the CW events rule is not removed and the error message pasted above is displayed.

### Steps to Reproduce
Create a template with a lambda function and associated CW event periodic scheduling, appy this template and then attempt to modify it (rename resources) or delete it

### NOTE
This is a follow up on the https://github.com/hashicorp/terraform/issues/18095 because it can still be reproduced on 0.12.8

**Comment by teamterraform** [comment]
Hi @mihaibaumgarten! Sorry for this annoying behavior.

Could you please provide debug output as requested in our issue template, so that we can understand how Terraform is evaluating the configuration for you here?

> Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

If you don't wish to share the entire debug log then the specific part that would help here is any log lines containing either the text "completed graph transform" or the text "terraform: building graph", since those will show us Terraform's work in building the graph. If you can provide only this subset then we may then have follow-up questions about additional log lines that appear between certain lines in the subset, so please retain the full log to refer to later.

Thanks!

**Comment by jbardin** [comment]
Hi @mihaibaumgarten,

There doesn't look to be any reason in this config for the resource to be evaluated out of order (i.e. there are known issues around multiple modules and `create_before_destroy`). To verify this, running a destroy operation on a config containing these exact resource definitions produces this subgraph

```
2019/09/19 15:14:42 [TRACE] Completed graph transform *terraform.TransitiveReductionTransformer with new graph:
aws_cloudwatch_event_rule.my-schedule (destroy) - *terraform.NodeDestroyResourceInstance
  aws_cloudwatch_event_target.my-target (destroy) - *terraform.NodeDestroyResourceInstance
...
```

Indicating that `aws_cloudwatch_event_rule.my-schedule` depends on `aws_cloudwatch_event_target.my-target`, meaning that the target will be destroyed before the rule (and transitively, the lambda function and role are removed before the target, which I didn't expand here).

The destroy also succeeded in the reproduction tests, further confirming that this is more likely an eventual consistency issue with these particular resources in AWS. I'll re-tag this as a provider issue so that team can take a look into any possible mitigations.
