### ISSUE TITLE
On-premises Private Terraform Registry

### ISSUE THREAD

**Issue by jlosito** [hashicorp/terraform#22771]
### Use-cases

Currently, I believe the only way of storing private providers is through Terraform Cloud without having to write your own server. Due to restrictions, Terraform Cloud is not a viable solution for me. I was wondering if there are any plans of releasing a registry which I can install and configure on one's private infrastructure.

**Comment by teamterraform** [comment]
Hi @jlosito! Thanks for sharing this.

The Terraform team at HashiCorp does not plan to offer an official private registry product other than what is in Terraform Cloud and Terraform Enterprise (the latter of which is an on-premises option), but there are several community-developed implementations of the protocol at various stages of development. The Terraform team doesn't have direct experience with them and thus cannot recommend any one specifically, but we'd encourage you to search for them and review them to see if they will meet your needs.

[The registry protocol](https://www.terraform.io/docs/registry/api.html) is documented to allow for third-party implementations. For simple cases, that protocol could be implemented through solutions such as generated static index files on an S3 website.

Since we aren't planning to include a registry implementation in this repository we're going to close this out. Hopefully the above is helpful in finding a path forward that will meet your requirements. Thanks!
