### ISSUE TITLE
Terraform configuration with Azure Firewall with multiple Public IP

### ISSUE THREAD

**Issue by pbej** [hashicorp/terraform#22790]
Hi Team,

I am having issue to create the Azure Firewall with multiple public IPs.
Is there any sample code that I can refer to resolve the issue because I didn't find anything on the documentation.

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
