### ISSUE TITLE
terraform -from-module does not work in alphine

### ISSUE THREAD

**Issue by rifaterdemsahin** [hashicorp/terraform#22791]
terraform init -from-module="git::ssh://xxxx

Init works with the repo my local using -from-module but does not work in docker alphine that was provided by hashicorp!!!!

What other libraries do i need ?

How can i see the error on my container? ( the terraform does not give me the reason I had to find it after trying multiple points )

Here is my docker file I am using at the moment

FROM hashicorp/terraform:0.11.14 AS main
 
RUN apk -v --update add ncurses
RUN apk -v --update add bash
RUN apk -v --update add git
RUN apk -v --update add openssh
RUN apk -v --update add openssl-dev
RUN apk -v --update add expect
RUN apk -v --update add python
RUN apk -v --update add py-pip
      
RUN pip install --upgrade awscli==$aws_cli_version
RUN pip install azure-devops==5.0.0b9
 
RUN apk -v --purge del py-pip curl && \
   rm /var/cache/apk/*

**Comment by rifaterdemsahin** [comment]
also asked here but there is no response https://www.reddit.com/r/Terraform/comments/d3qnjx/terraform_frommodule_does_not_work_in_alphine/

**Comment by JoshCooley** [comment]
What does "does not work" mean? What are you doing, what is the outcome, and what is the expected outcome?

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
