### ISSUE TITLE
 google_compute_firewall.web: diffs didn't match during apply

### ISSUE THREAD

**Issue by dhilton** [hashicorp/terraform#2280]
When using google compute firewall, on first run we sometimes see the following error; we then rerun the terraform apply and the change is applied cleanly. This possibly could be to do with a creation order issue, i.e. this resource has a dependency that isn't met.

Terraform version 0.5.3 targeting GCE.

```
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* google_compute_firewall.web: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Run again:

```
google_compute_firewall.web: Creating...
  allow.#:                           "" => "1"
  allow.1100366991.ports.#:          "" => "3"
  allow.1100366991.ports.1889509032: "" => "80"
  allow.1100366991.ports.32925333:   "" => "8080"
  allow.1100366991.ports.3638101695: "" => "443"
  allow.1100366991.protocol:         "" => "tcp"
  description:                       "" => "Security group for web that allows web traffic from internet"
  name:                              "" => "mr-ben-web-tsuru"
  network:                           "" => "mr-ben-tsuru-network1"
  self_link:                         "" => "<computed>"
  source_ranges.#:                   "" => "4"
  source_ranges.1305432134:          "" => "104.155.95.73"
  source_ranges.1307486980:          "" => "80.194.77.90/32"
  source_ranges.3141742107:          "" => "104.155.108.211"
  source_ranges.4126882382:          "" => "80.194.77.100/32"
  target_tags.#:                     "" => "1"
  target_tags.365508689:             "" => "web"
google_compute_firewall.web: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by mtekel** [comment]
We get similar issue when configuring DNS records:
```
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* google_dns_record_set.docker-registry: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**Comment by sparkprime** [comment]
Does this occur only when updating infrastructure?

Can you give A.tf and B.tf for a simple 3 step reproduction:

1) Starting from blank slate (no tfstate file) deploy A.tf
2) Change to B.tf and re-apply, get diff error
3) Re-apply B.tf which works successfully

**Comment by dhilton** [comment]
Even better a link to the full project: https://github.com/alphagov/tsuru-terraform/tree/master/gce

We destroy everything in GC then run plan, then run apply which then gives us the issue. So, it's usually from a clean slate (i.e. nothing in the project as far as infrastructure goes). We've removed the tfstate and the backup file but that hasn't made any difference AFAIK. I'll try and generate a cleaner example tomorrow.

**Comment by mtekel** [comment]
Hi,

it also occurs when updating existing infrastructure. For some reason the issue has been always happening with `google_compute_firewall.web` even though there's nothing special about this [resource](https://github.com/alphagov/tsuru-terraform/blob/master/gce/security-groups.tf#L42). Recently however I've also seen `google_dns_record_set.docker-registry` error. This time terraform was just `google_dns_record_set.docker-registry: Refreshing state... (ID: 509)`. Could this be be due to different API replies returned by google? Perhaps ordering of some elements is different and terraform then fails to match the diffs?

**Comment by lwander** [comment]
Hi,

@dhilton, I'm having trouble reproducing the error using the project you linked to. Is this still an issue? Do you have a smaller reproduction of the problem?

Thanks!
Lars

**Comment by mitchellh** [comment]
Hey there. It has been a long time since there has been activity on this issue (our fault, sorry!), and the last known repro was against a very old version of Terraform. It is possible this issue still exists but we've addressed dozens of issues with the same type of error message in the past year. Could you please try again on the latest version and let us know if it doesn't work? The easiest way would be to simply open a new issue. Thanks!
