### ISSUE TITLE
Shell Script inside Terraform

### ISSUE THREAD

**Issue by dhineshbabuelango** [hashicorp/terraform#22803]
Hi All, We are using Terraform to provision EKS cluster.
I am trying to run a shell script inside terraform after the EKS master and autoscaling group completed., the module looks like below

![image](https://user-images.githubusercontent.com/51995628/64929535-e0fee180-d859-11e9-9de8-11c6959a8dbe.png)

I want to pass the eks cluster name in the shell script.

**Comment by kmoe** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
