### ISSUE TITLE
x86 build fails in upgrade_state_v2_test.go:99: Count was migrated incorrectly for computed_set

### ISSUE THREAD

**Issue by glaubitz** [hashicorp/terraform#22807]
On 32-bit openSUSE, ```terraform``` the testsuite fails with:

```
[  547s] cd .
[  547s] /usr/lib/go/1.12/pkg/tool/linux_386/link -o $WORK/b1029/terraform.test -importcfg $WORK/b1029/importcfg.link -s -w -buildmode=exe -buildid=z9pf_8-9aCcHkM7Ait0m/sCtYA7WwRac9PmGW0L_0/SGqtVnJklHamKtVHuT1d/z9pf_8-9aCcHkM7Ait0m -extld=gcc $WORK/b1029/_pkg_.a
[  548s] rm -r $WORK/b1037/
[  550s] $WORK/b1029/terraform.test -test.testlogfile=$WORK/b1029/testlog.txt
[  556s] rm -r $WORK/b1029/
[  556s] --- FAIL: TestReadUpgradeStateV2toV3 (0.00s)
[  556s]     upgrade_state_v2_test.go:99: Count was migrated incorrectly for computed_set
[  556s] FAIL
[  556s] FAIL	github.com/hashicorp/terraform/terraform	5.652s
[  556s] ok  	github.com/hashicorp/terraform/tfdiags	0.014s
[  556s] ?   	github.com/hashicorp/terraform/tools/loggraphdiff	[no test files]
[  556s] ?   	github.com/hashicorp/terraform/tools/terraform-bundle	[no test files]
[  556s] ok  	github.com/hashicorp/terraform/tools/terraform-bundle/e2etest	6.103s
[  556s] ?   	github.com/hashicorp/terraform/version	[no test files]
[  556s] error: Bad exit status from /var/tmp/rpm-tmp.0WtzCj (%check)
```

Full log in https://build.opensuse.org/build/openSUSE:Factory/standard/i586/terraform/_log

**Comment by apparentlymart** [comment]
Thank for reporting this, @glaubitz.

Although we are still producing 32-bit x86 releases for Linux on a best-effort basis, we are no longer actively supporting that architecture and so we don't intend to fix build system bugs that only affect that platform in the future. This issue is an old one and so I suppose the situation might well have changed in the meantime anyway.

While I expect that Linux distribution packages are typically built from source anyway and thus can potentially be built for platforms not on our official support list, we've documented [the platforms we are actively supporting](https://www.terraform.io/docs/language/v1-compatibility-promises.html#supported-platforms) as part of the Terraform v1.0 Compatibility Promises and we can't promise that Terraform will continue to build on an ongoing basis on any other platform, even though we are not actively _trying_ to remove support.

(From a technical standpoint, we're producing releases for some others only in the sense that Go is good at cross-compiling and its standard library has good portability; if that were to change in future versions of Go or in future versions of an unsupported OS then we would be more likely to cease releasing packages for that platform than to invest in making it work again.)

Thanks again for reporting this, and sorry we left it unattended here for so long.
