### ISSUE TITLE
Start or Stop GCP Instance

### ISSUE THREAD

**Issue by manggiardi** [hashicorp/terraform#22801]
I'm a newbie for terraform, is it possible to start and stop instances using terraform? I read the documentation and haven't found it yet.

**Comment by kmoe** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
