### ISSUE TITLE
Provider Development: How to force triggerring new execution regardless of template changes

### ISSUE THREAD

**Issue by donglev91** [hashicorp/terraform#22816]
Hi there,

I am working on provider development. My provider has a "resource", called "workflow_execution" that triggers to create new execution. It should always create a new execution regardless of the resource's change. Do we have any mechanism or trick to do that? I saw in some samples, the provider should define a resource with the "triggers" attribute, e.g. null_resource and the 'triggers' attribute should be changed in the template to trigger new execution. In my case, I need the resource to always trigger new execution, regardless of the template ("triggers" attribute) changes or not.

BRs,
Dong

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
