### ISSUE TITLE
remote-state/pg: Per schema/state locking

### ISSUE THREAD

**Issue by holstvoogd** [hashicorp/terraform#22833]
### Current Terraform Version

```
v0.12.8
```

### Use-cases

When using schema's to seperate multiple states in one DB, locking states is (semi-) global. It would be nice if it was scoped so one can run terraform against multiple states/schema's at once.

### Attempted Solutions

Since the advisory lock name contains the state id only, it collides between multiple states that happen to have the same ID. Since I am using only the default workspace, both state tables have only one row with ID=1.
After incrementing one of the IDs, all works fine.

### Proposal

Use the schema/state name in the advisory lock name so that locks are scoped to their state.

**Comment by thundertaker** [comment]
Same for me: I use multiple states in one database (mostly because it simplifies configuration: I only need one db and credentials to it to create a new Terraform environment). @holstvoogd 's proposal to use schema name in locking seems to be good.

@mars could you please have a look at this? It will greatly simplify backend's usability "out of the box"
