### ISSUE TITLE
Add ability to target outputs for refresh

### ISSUE THREAD

**Issue by tmccombs** [hashicorp/terraform#22864]
### Current Terraform Version

```
Terraform v0.12.8
+ provider.aws v2.28.1
```

### Use-cases

Running a full refresh on my environment takes quite a while due to the number of resources. It would be nice to be able to just refresh a new output and it's dependencies (or possibly limit a plan to just the dependencies of an output).

### Attempted Solutions

```
terraform refresh -target=output.my-target
```

```
terraform plan -target=output.my-target
```

Neither of which do anything.  Running a full `terraform refresh` does add the output to the state, but in my case takes  a long time.

### Proposal

For commands that support the `-target` option, allow passing an argument of the form `output.my-output` to target an output and make sure it is in the state.

### References

#17280

**Comment by teamterraform** [comment]
Hi @tmccombs! Thanks for sharing this use-case.

Supporting this would require that we introduce a new absolute address form for outputs, so that it's possible to identify outputs in nested modules. A syntax like `module.foo.output.bar` is probably where we'd end up with that. It's a little unfortunate that this doesn't align with how one refers to module outputs inside configuration (it would be `module.foo.bar` there) but the inclusion of `.output` would help disambiguate the interpretation as a resource type.

We'll need to think about how this interacts with other Terraform functionality that works with absolute addresses, to decide if supporting outputs makes sense for each of them and add a suitable error message for any that don't make sense. This includes (but might not be limited to):

* `terraform taint`
* `terraform state rm`
* `terraform state mv`
* `terraform state show`

In the meantime, the way to get the behavior you seek would be to look at the `value` argument inside the `output "my-output"` block and make a list of all of the resources that the result depends on, and then include a `-target` attribute for each of them. Terraform's targeting behavior will update outputs as long as all of the contributing resources are present. Of course, that's particularly inconvenient for any output whose `value` expression is complex and derives from many other resources, or refers to resource values only indirectly; having outputs be targetable directly would allow Terraform to calculate the dependencies of the output and thus get the same result automatically.

Since `-target` is provided only for exceptional circumstances, we don't tend to prioritize extensions to it that might encourage it being used routinely, and this _does_ seem to be one of those cases. Ideally, we'd prefer to implement batch refresh requests as discussed in #7388 so that `terraform refresh` could be faster in cases where there are many resource instances of the same type, or when the underlying API supports type-agnostic batching. The next phase of design for that is likely to wait until after the current effort to upgrade the Terraform SDK to support Terraform 0.12-only features, but is still something we intend to address to make Terraform easier to use for larger configurations with many objects.

**Comment by tmccombs** [comment]
It looks like it's now possible to run plans and applies that update the output even if there are no other changes, which mostly alleviates my need for this.

**Comment by crw** [comment]
Hi @tmccombs, would it be safe to close this issue, and possibly open a new issue with a narrower use case given the new functionality? Or do you find the original use case is still useful / needed?

**Comment by tmccombs** [comment]
I'm fine with that.
