### ISSUE TITLE
Read Custom Provider Value in the backend

### ISSUE THREAD

**Issue by udaykiran19** [hashicorp/terraform#22861]
I am looking for some help in order to read the parameters defined in the custom provider block - the values of which are passed NOT as env variables, but through the variables.tf / main.tf / *.auto.tfvars

For ex:

provider.go
func Provider() terraform.ResourceProvider {
            return &schema.Provider{
                    Schema: map[string]*schema.Schema{
                            "myvar": &schema.Schema{
                                    Type:     schema.TypeString,
                                    Required: true,
                                    Description: "Account var",
                            },
    .......
    ........

How do I read the “myvar” in resource_cert.go in the Terraform Create function?

If its a resource variable, I am able to read it using
myvar := d.Get(“myvar”).(string)

But how do I read the provider values declared in the variables.tf or the *.auto.tfvars file and NOT in environemnt variables.

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
