### ISSUE TITLE
Help to rewrite part of code from 0.11 to 0.12 data template_file 

### ISSUE THREAD

**Issue by KursLabIgor** [hashicorp/terraform#22872]
### Terraform Version

```
0.11
```

### Terraform Configuration Files

terraform 0.11
```hcl
data "template_file" "this_code_build_networkinterface_policy" {
  count = "${length(var.vpc_private_subnets)}"
  template = "${file("${path.module}/codebuild_subnet_policy.json.tpl")}"
  
  vars {
    region = "${var.region}"
    user = "${data.aws_caller_identity.aws_user_info.account_id}"
    subnet = "${var.vpc_private_subnets[count.index]}"
  }
}
```
terraform 0.12
```hcl
data "template_file" "this_code_build_networkinterface_policy" {
  count = length(var.vpc_private_subnets)
  template = file("${path.module}/codebuild_subnet_policy.json.tpl")
  
  vars = {
    region = var.region
    user = data.aws_caller_identity.aws_user_info.account_id
    subnets = var.vpc_private_subnets[count.index]
  }
}
```
json.tpl file
```
{
    "Version": "2012-10-17",
    "Statement": [
    {
      "Effect": "Allow",
      "Action": [
          "ec2:CreateNetworkInterfacePermission"
      ],
      "Resource": "arn:aws:ec2:${region}:${user}:network-interface/*",
      "Condition": {
          "StringEquals": {
              "ec2:Subnet": [
                  "arn:aws:ec2:${region}:${user}:subnet/${subnet}"
              ],
              "ec2:AuthorizedService": "codebuild.amazonaws.com"
          }
      }
    }
    
    
    ]
}
```
### Crash Output

no rash
### Expected Behavior

Help rewrite according to 0.12 syntax
### Actual Behavior

Error: Incorrect attribute value type

```
  on modules/_ci_cd/build.tf line 30, in data "template_file" "this_code_build_networkinterface_policy":
  30:   vars = {
Inappropriate value for attribute "vars": element "subnets": string required.
```

Actually i want to rewrite from scratch code from 0.11 to 0.12 version. And cant figure out how to iterate over list that terraform creates several templates files and substitute subnet to policy file

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
