### ISSUE TITLE
Error iin creating "aws_volume_attachment" in 0.12.9 version

### ISSUE THREAD

**Issue by vishal169** [hashicorp/terraform#22876]
I'm using terraform 0.12.9, migrating from 0.11.14 

resource "aws_volume_attachment" volumne-attachment" {
  device_name = "/dev/sde"
  volume_id   = aws_ebs_volume.home.id
  instance_id = module.instance.id
}

Error: Incorrect attribute value type

  on file.tf line 96, in resource "aws_volume_attachment" volumne-attachment":
  96:   instance_id = module.volumne-attachment.id 
Inappropriate value for attribute "instance_id": string required.

I have tried all cases like  module.volumne-attachment.id[0], module.volumne-attachment.id[1], 
tolist(module.volumne-attachment.id)[0].

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by adefemi171** [comment]
Hi, the issue to the problem @vishal169  is that you need to put your volume_id in parenthesis as well as your instance_id. So you might want to do something like:
`resource "aws_volume_attachment" volumne-attachment" {
device_name = "/dev/sde"
volume_id = "${aws_ebs_volume.home.id}"
instance_id = "${module.instance.id}"
}`
