### ISSUE TITLE
Rules for implicit dependencies

### ISSUE THREAD

**Issue by marcoliceti** [hashicorp/terraform#22874]
I'm sorry if this is explained somewhere else but I couldn't find it.

Suppose you have 3 resources A, B and C, with C being just a way to track A-B pairs. Also suppose that C identifies A resources through an attribute that is not an id:

```hcl
resource "res_a" "some_a" {
  some_property = "foo"
}

resource "res_b" "some_b" { ... }

resource "res_c" "some_c" {
  my_a = res_a.some_a.some_property # implicit dependency (?)
  my_b = res_b.some_b.id # implicit depency
}
```

I'm sure that the line `my_b = res_b.some_b.id` produces an implicit dependency (`some_c` needs `some_b`, so `some_b` will be created first).

I'm not sure that `my_a = res_a.some_a.some_property` produces an implicit dependency, so I'm not sure that `some_a` will exist when `some_c` is created.

What if I need `some_a` before creating `some_c`? Can I rely on implicit dependencies or should I use `depends_on`?

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
