### ISSUE TITLE
A block definition must have block content delimited by "{" and "}", starting on the same line as the block header.

### ISSUE THREAD

**Issue by fip-post-cz** [hashicorp/terraform#22875]
After upgrade from v0.11.x to v0.12.9 there are a lot of errors:

A block definition must have block content delimited by "{" and "}", starting on the same line as the block header.

terraform 0.12upgrade was solved those errors, but all *.tf files was spoiled with confusing formating, which moves "{" to the unsuitable place and *.tf files are harder to read now. Please revert parser to 0.11.x mode.

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
