### ISSUE TITLE
lifecycle: force_recreate

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#22902]
### Current Terraform Version
Terraform 0.12 (or, what is reflected in the documentation as of today)

### Use-cases
Sometimes a resource is able to Update in place via the provider (Update function), but other times it is unable to. The provider will be limited in its ability to differentiate between these situations. For example, the resource `aws_ssm_document` for the AWS provider can be Update if the schema is version >= 2.0, but must be Destroy and then Create if the schema is a lower version.

### Attempted Solutions
I have scoured the documents, especially regarding the `lifecycle` block, and have not seen this feature available. Additionally it could be implemented in the providers' code when invoking CRUD methods, and this would be ideal, but in some situations like the above it will just not be possible.

I am aware this could performed manually by doing a `taint` after inspecting a `plan` that would attempt to Update the resource, but this seems rather non-ideal, especially in a pipeline situation.

### Proposal
Add a `lifecycle` block argument called something like `force_recreate`. It would trigger if the provider detects an Update should be attempted, and then instead would attempt a Destroy followed by a Create.

### References
None to my knowledge.

**Comment by OJFord** [comment]
Cf. #8099, in particular the comment:
https://github.com/hashicorp/terraform/issues/8099#issuecomment-252664896

in which @apparentlymart proposes pretty much what you describe:
```hcl
resource "foo" "bar" {
    foobar = "${file("foobar")}"
}

resource "bar" "foo" {
    lifecycle {
        replace_on_change {
            foo_bar_foobar = "${foo.bar.foobar}"
        }
    }
}
```

**Comment by teamterraform** [comment]
Thanks for sharing this use-case, @mschuchard!

As @OJFord mentioned, this is similar to what we were discussing in #8099. The use-case is a little different here because we think you're asking for Terraform to treat _any change at all_ as a replace, overriding the possibility that it might be an update. `replace_on_change`, on the other hand, was to allow using values changes to values that aren't otherwise part of the resource configuration to trigger an instance replacement.

With that said, the implementation and design for both is very closely related, so let's track this as a variant of the use-case in #8099 and consolidate the discussion over in that other issue, so that future design/investigation on #8099 will be sure to consider this use-case as well.

Thanks!
