### ISSUE TITLE
List parsing infor for.each as a value.

### ISSUE THREAD

**Issue by t5unamie** [hashicorp/terraform#22906]
Trying to parse a list into a module using a for.each loop. I want the content of the map(map(list)) to correct be processed in the module.

### Terraform Version
Terraform v0.12.9
```
Module
 
resource "aws_route53_record" "record" {
  for_each = var.records_list
 
  zone_id = var.zone_id
  name    = each.key
  type    = lookup(each.value, "type", "A")
  ttl     = lookup(each.value, "ttl", "60")
  records = [ lookup(each.value, "records", "8.8.8.8") ]
}
 
Module call
 
module "example" {
  source = "../../modules/coreDNS/"
  zone_id = aws_route53_zone.example.id
 
  records_list = var.example
}
 
Variable pasred in
 
variable "example" {
  default = {
    rebot = {
      ttl = "60"
      type  = "A"
      records  = [ "1.1.1.1", "2.2.2.2" ]
    }
  }
  description = "This is a list for "
  type = map(map(any))
}
```
### Crash Output
none

### Expected Behavior
Should create an A record with two values.

### Actual Behavior
No DNS entry is created

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

No errors show

**Comment by teamterraform** [comment]
Hi @t5unamie! Sorry for this strange behavior.

The first thing we noticed looking at your example is that the default value for `variable "example"` isn't valid for the given type `map(map(any))`. The `any` placeholder in a type constraint is a request for Terraform to select a type automatically by analyzing the value, but the result must always be a single type for all elements of the map because that's how the map type is defined. Since your map contains a mixture of string and list values, Terraform should have produced an error validating that `default`.

A correct type constraint for the default value shown in your configuration would be as follows:

```hcl
  type = map(object({
    ttl     = number
    type    = string
    records = list(string)
  }))
```

It is a bug that Terraform didn't report your current configuration as an error. We'd be curious to know if replacing your type constraint in `variable "example"` either makes Terraform behave as you wanted here or produces an error message that might give a better clue as to what's causing `for_each` to misbehave here.

It could also be useful to temporarily add an output to your root module to see how Terraform is understanding the value of `var.example`:

```hcl
output "temp_example" {
  value = var.example
}
```

If you're able to successfully apply then Terraform should include in the apply output the final value of that output, which we can then check to see if it matches the value you intended to set for that variable.

**Comment by t5unamie** [comment]
thanks was able to work out a solution based on the above input. I can have a list of 1 and just parse in loads of of lists if I want.
