### ISSUE TITLE
Attache different multiple policies to multiple users with for_each 

### ISSUE THREAD

**Issue by mo-saeed** [hashicorp/terraform#22920]
### Terraform Version
0.12.7

### Terraform Configuration Files
```
resource "aws_iam_user" "test" {
  for_each = "${var.svcMap}"
  name = "${var.svcMap[each.key]}"

}

resource "aws_iam_user_policy_attachment" "test-attach" {
  for_each = "${var.svcMap}"
  user = "${var.svcMap[each.key]}"
  
  policy_arn = "??"
}
```

### Debug Output
It's just a question, How to

### Crash Output
N/A

### Expected Behavior
To be able to attach different policies to multiple users with `for_each`

### Actual Behavior
Not possible as policy_arn accept only string not list

### Steps to Reproduce
N/A

### Additional Context
I need to automate creation of users using terraform, mainly i have map "svcMap" like that {user1=[policy_arn1, policy_arn2] user2=[policy_arn3, policy_arn4]}, it's easy to create users but not easy to attach policies:

```
resource "aws_iam_user" "test" {
  for_each = "${var.svcMap}"
  name = "${var.svcMap[each.key]}"

}

resource "aws_iam_user_policy_attachment" "test-attach" {
  for_each = "${var.svcMap}"
  user = "${var.svcMap[each.key]}"
  
  policy_arn = "??"
}
```
Is there anyway to achieve that ?

### References
N/A

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
