### ISSUE TITLE
Cannot pass complex input variable to child module

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/terraform#22922]
### Terraform Version
```
terraform -v
Terraform v0.12.9
+ provider.google v2.16.0
+ provider.google-beta v2.16.0
+ provider.helm v0.10.2
+ provider.kubernetes v1.9.0
+ provider.null v2.1.2
```

### Terraform Configuration Files
I am effectively trying to do something like this:

```
  -    Child Module ~ vpc 
root Module ~ GCP Account
  -    Child Module ~ prom 
       - Nested module within Prom module ~ http load balancer 
```
Where I create networks in the VPC module & then pass the entire VPC network resource out of the VPC module, pass it into the prom module and then have the prom module pass that entire resource into the http load balancer module. 

Is something like this possible in 0.12 or does Terraform still impose limits due to the possible complexity of the graph?

```hcl
# Within Root
module "prometheus-thanos" {
  source                           = "./modules/prometheus-thanos"
  project_id                       = "${module.project.project_id}"
  vpc_network                      = "${module.vpc.network}"       <------
  vpc_subnetwork                   = "${google_compute_subnetwork.vpc_subnetwork}"
}

# Within Prometheus-thanos module
module "https-load-balancer" {
  source          = "../https-load-balancer"
  project_id      = "${var.project_id}"
  region          = "${var.region}"
  name            = "prometheus"
  subdomain       = "prometheus.${var.project_id}"
  vpc_network     = var.vpc_network                                    <--------
}

# Within the https-load-balancer module
resource "google_compute_firewall" "health_check_firewall" {
  name        = "external-${var.name}-health-check"
  description = "Allow Google's load balancer to health check and forward traffic from the external internet."
  network     = var.vpc_network.name                                 <---------

  allow {
    protocol = "tcp"
    ports    = ["${var.port_number}"]
  }
}
```

### Debug Output
No Crash

### Crash Output
None

### Expected Behavior
I should be able to pass the resource variable into the child module so it can choose what attributes to use of the passed in resource.

### Actual Behavior
It appears that it only passes one of the strings from the complex variable to the child module.

```
Error: Unsupported attribute

  on ../../modules/https-load-balancer/main.tf line 43, in resource "google_compute_firewall" "health_check_firewall":
  43:   network     = var.vpc_network.name
    |----------------
    | var.vpc_network is "https://www.googleapis.com/compute/v1/projects/my-project/global/networks/my-network"

This value does not have any attributes.
```

### Steps to Reproduce
Try to pass a complex input variable to a child module.

**Comment by mildwonkey** [comment]
Hi @sidewinder12s !
To understand what's going on, it will help us to see more of your configuration, especially the output block from `module "prometheus-thanos"` and the relevant variable definitions. 

Generally speaking, passing complex variables works - which is to say that we don't know of any major bugs -  so at a glance I would ask if it's possible that the module is only outputting a string and not the entire resource.

**Comment by sidewinder12s** [comment]
Hey @mildwonkey, 

So that's the weird thing, I am using the vpc_network variable within the prometheus-thanos module and accessing it as expected, it's only once I try to pass the vpc_network variable down another level that it seems to get auto-converted to a string instead of a variable with attributes (which so far has always been the self_link attribute). 

Here is our VPC module output:
```hcl
output "network" {
  description = "This is the full complex VPC resource. Support for outputting values like this was added as part of Terraform 0.12"
  value       = "${google_compute_network.vpc_network}"
}
```

And another resource within prometheus-thanos that is using the vpc_network.ATTRIBUTE variable as expected:
```hcl
resource "google_compute_firewall" "thanos_store_api" {
  name        = "internal-thanos-store-api"
  description = "Expose the thanos store api port internally for thanos query nodes to access it."
  network     = var.vpc_network.self_link

  allow {
    protocol = "tcp"
    ports    = ["${local.thanos_store_api_port}"]
  }

  # This cannot be 'source_tags' because these instances are connected across projects in a VPC, so
  # we need to allow VPC internal 10.* traffic.
  source_ranges = ["10.0.0.0/8"]

  target_tags = ["${local.thanos_sidecar_network_tag}", "${local.store_gateway_tag}"]
  priority    = "1000"
}
```

It then comes in as a variable for the prometheus-thanos module and I just try passing it to the nested module within there, so prometheus-thanos is not outputting anything network related. 

The variable definition for prometheus-thanos is:
```hcl
variable "vpc_network" {
  description = "VPC Network resource object"
}

variable "vpc_subnetwork" {
  description = "VPC Subnetwork resource object"
}
```

Would I need to output the vpc_network variable from the prometheus-thanos module for the variable to be accessible to a nested module?

**Comment by mildwonkey** [comment]
That's interesting information, @sidewinder12s , thank you! It's certainly something I would expect would work.

I was unable to reproduce your issue, admittedly with a very simple case: I created a `random_pet` and passed it down through two levels of nested modules, and was still able to access the individual attributes.

It would help if you could share your full debug log (as a gist, please, removing any sensitive data), and it would be fantastic if you could share a simplified reproduction case so we can reproduce this locally.

**Comment by apparentlymart** [comment]
Hi @sidewinder12s!

Terraform 0.12 does not include any behaviors to automatically convert an object into the value of one of its attributes. Indeed, the core Terraform language doesn't have enough information to know that `self_link` might be an interesting attribute to use on that resource type; `self_link` is just like any other attribute to the Terraform language engine.

To try to narrow down where the problem is arising here, I'd suggest adding some more type annotations in your configuration. While the Terraform language is designed such that we can often get away without them, including specific annotations is helpful when errors like this occur so we can stand the best chance of the error being reported close to its cause.

I'm not sure I fully followed where all of the code you shared is located relative to one another, so I might not get this quite right but hopefully the following examples are useful to help you find interesting places to add type annotations.

For variables, we can directly add [type constraints](https://www.terraform.io/docs/configuration/types.html) to them, which Terraform will then enforce within the calling `module` block:

```hcl
variable "vpc_network" {
  description = "VPC Network resource object"

  type = object({
    name = string
    # and any other attributes of the network that this module will use
    # (you don't need to list any attributes that this module isn't using)
  })
}
```

For outputs unfortunately things are trickier because although Terraform does have some type conversion functions, there isn't currently one for forcing a value to be of an object type. However, the function [`merge`](https://www.terraform.io/docs/configuration/functions/merge.html) has a side-effect of checking that its argument is a mapping type and always produces an object value as its result, so we can use it as a sort of implicit type assertion on the output value:

```hcl
output "network" {
  description = "This is the full complex VPC resource. Support for outputting values like this was added as part of Terraform 0.12"
  value       = merge(google_compute_network.vpc_network)
}
```

Passing a single value to `merge` is unusual, but should serve to produce an error if for _some_ reason this value were not an object. (Seems very unlikely, but while we're debugging anyway we might as well be thorough.)

If there are any other variables or outputs involved along the way here -- for example, if this is passing through multiple levels of module -- I'd suggest adding similar type annotations to any other references, to allow Terraform to identify the problem as closely as possible to its source.

My hope here is that with these annotations in place Terraform will be able to give you a different error message that better indicates where the problem is arising, so that we can narrow down what's going on here. (If you can gather a trace log at the same time as testing this, as @mildwonkey asked, that'd be helpful too!)

**Comment by sidewinder12s** [comment]
It appears I may have missed a spot in our first layer of modules where I was passing a string (old way) when the nested module was expecting an object. My error message appears to be Terraform erroring on the nested module variable when I try to use it (which I think makes sense since I'm not putting any type constraints on the module so it'll take whatever input variables I give it). 

Once I added the type constraints to the nested module terraform threw a type error at a different spot in our first layer of modules that I might have missed while refactoring. The full path for our network variable is as follows so hopefully it makes (more?) sense:

resource.google_compute_network -> module.vpc -> root -> module.promethus-thanos -> module.https-load-balancer -> resource.google_compute_firewall

I'm not sure that helps :sweat_smile:. I missed a second http-load-balancer module invocation within the promethus-thanos module.

Let me sit on it and I'll close it out tomorrow if I confirm user error. Thanks for the tip on the object type constraints, I totally missed the line about Terraform dropping any extra attributes you pass in.

**Comment by sidewinder12s** [comment]
Well, new somewhat related problem. Say I have a module that takes a google_compute_subnetwork resource as a variable:

```hcl
variable "vpc_subnetwork" {
  description = "VPC Subnetwork resource object"
  type = object({
    name      = string
    self_link = string
    secondary_ip_range = map(string)
    # and any other attributes of the network that this module will use
    # (you don't need to list any attributes that this module isn't using)
  })
}
```
Is there a way to deal with an attribute like secondary_ip_range where the resource provider only exports that attribute if it is defined/set, other than just not setting type constraints on the variable?

In most of our modules we don't set that variable on resource creation, but in a couple places we do & we use the attribute so just dropping the attribute fails in some cases where we need it but fails then in most cases when the attribute just doesn't exist.
