### ISSUE TITLE
Couldn't initialize 

### ISSUE THREAD

**Issue by annamreddi03** [hashicorp/terraform#22958]
Hi there,
    When I am trying to initialize the file, I'm getting following message along with error.

Error installing provider "AWS": failed to find installed plugin version 2.9.0; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

Warning: Skipping backend initialization pending configuration upgrade

The root module configuration contains errors that may be fixed by running the
configuration upgrade tool, so Terraform is skipping backend initialization.
See below for more information.

**Comment by teamterraform** [comment]
Hello! Please use the issue template when reporting bugs. Without further details, this appears to be an issue with your environment, as described in the error:

> This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

Since this is more of a question, we suggest using [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Please do feel free to ask your question in the community forum. Thanks!
