### ISSUE TITLE
Allow Working Directory for a Terraform Cloud workspace to be set through the terraform block

### ISSUE THREAD

**Issue by mattddean** [hashicorp/terraform#22959]
### Current Terraform Version

```
Terraform v0.12.9
```

### Use-cases

- Remove the necessity to go to app.terraform.io when creating a new workspace just to set the value of `Terraform Working Directory` under `Settings/General`.
- Better support for workspaces created dynamically, including those created as part of a pipeline.
  - Especially when setting up a pipeline to automatically create a workspace for each environment of your application (dev, prd, etc.)
    - In this case, the ability to set the working directory of each to a subdirectory in which the code is stored for _that_ environment would be exceedingly helpful (`<vcs_root_dir>/dev`, `<vcs_root_dir/prd>`, etc.)

### Proposal

Create a new block type: "workspace" and allow the working directory to be specified here. Using a block would also allow for other workspace options to be passed, like an "auto_apply" option.
```
terraform {
  required_version = "~> 0.12.9"
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "<organization>"

    workspaces {
      workspace "<workspace_name>" {
        working_directory = "dev"
      }
    }
  }
}
```

**Comment by apparentlymart** [comment]
Hi @mattddean! Thanks for reporting this and sorry for the delayed response.

Although the visible UI for what you proposed here would be in the Terraform configuration, I expect that the bulk of the work to implement this would be to redesign how Terraform Cloud itself deals with working directories so that it would be something settable separately for each run rather than globally on the workspace as a whole. For that reason, it's not something that the Terraform Core team (the only folks who monitor issues in this repository) can address directly.

Terraform Cloud is developed by other teams and they prefer to hear about bug reports and feature requests via the customer support system. If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
