### ISSUE TITLE
Double / in DynamoDB table items LockID field when using S3 bucket folder

### ISSUE THREAD

**Issue by obourdon** [hashicorp/terraform#22965]
### Terraform Version

```
0.11.14
```

### Terraform Configuration Files

backend-test.tfvars
```hcl
bucket = "s3-ACCOUNT_ID-tfstate/eu-west-1/"
dynamodb_table = "dynamodb-ACCOUNT_ID-tflock"
region = "eu-west-1"
```

### Expected Behavior
Entries in DynamoDB table should have their LockID field looking like:
```
s3-ACCOUNT_ID-tfstate/eu-west-1/step1.tfstate-md5
```

### Actual Behavior
Entries in DynamoDB table have their LockID field being:
```
s3-ACCOUNT_ID-tfstate/eu-west-1//step1.tfstate-md5
```
One could argue that we might want to remove the / at the very end of the bucket = entry in backend-test.tfvars. However, doing so will make terraform think eu-west-1 being a bucket file entry and not a directory entry and therefore further steps (this is why step1 is mentioned above) will overwrite each another

### References
Having done a quick lookup in the code I guess this "error" comes from [these lines of code](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/client.go#L397:L399)

**Comment by teamterraform** [comment]
Hello, to better understand this issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by obourdon** [comment]
@teamterraform complete example can be found in [this repository I created on purpose](https://github.com/obourdon/terraform-bug-22965)

**Comment by obourdon** [comment]
Commands used and outputs also included in the repo

**Comment by obourdon** [comment]
@teamterraform I confirm that changing [line 398](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/client.go#L398) from:
```
return fmt.Sprintf("%s/%s", c.bucketName, c.path)
```
to
```
return strings.ReplaceAll(fmt.Sprintf("%s/%s", c.bucketName, c.path), "//", "/")
```
and of course adding strings as import just works

**Comment by obourdon** [comment]
@teamterraform any progress on this ?

**Comment by obourdon** [comment]
@teamterraform any progress on this ?

**Comment by obourdon** [comment]
Any one please ??? this is an easy one

**Comment by obourdon** [comment]
@ewbankkit @bflad @aeschright any body ?

**Comment by obourdon** [comment]
Any news ?

**Comment by obourdon** [comment]
Anybody to integrate the fix ?

**Comment by ewbankkit** [comment]
Maybe related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7583

@obourdon https://github.com/terraform-providers/terraform-provider-aws/pull/7584 I found I had to use
`key = regexp.MustCompile(`/+`).ReplaceAllString(key, "/")`
to treat multiple '/'s as a single '/'.
Can you see if the same applies here?
Thanks.

**Comment by obourdon** [comment]
@ewbankkit I've just checked your version of terraform-provider-aws with my example but unfortunately, and as I expected, the behaviour is still the same. From what I've seen in the code and as mentioned above the fix seems to be relative to terraform core code (which I have checked to be working on my side). Thanks anyways for pointing this out

**Comment by obourdon** [comment]
@teamterraform any progress on this easy one ?

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
