### ISSUE TITLE
aws_dx_gateway_association - destroy causing error message

### ISSUE THREAD

**Issue by krishnamurthydasari** [hashicorp/terraform#22961]
Greetings!

Destroying dx gateway association causing below error,

----------------------------------
Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_dx_gateway_association.vgw[0]: Destroying... [id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]

Error: error deleting Direct Connect gateway association: DirectConnectServerException: Unable to process request
        status code: 400, request id: 39146154-19b7-475b-9954-16d5158b8da3
--------------

Below is the code snippet, Association works fine but destroying / disassociation throws error.

data "aws_dx_gateway" "dxgw" {
  name = "test"
}

#Dx gateway association to VGW
resource "aws_dx_gateway_association" "vgw" {
  count  = var.create_vgw && length(module.vpc.vpc_id) > 0 ? 1 : 0
  dx_gateway_id = data.aws_dx_gateway.dxgw.id
  associated_gateway_id = aws_vpn_gateway.main[0].id
}

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

You might also direct your question to the [AWS forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws) specifically.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by krishnamurthydasari** [comment]
Are we sure this is not a bug?
I felt this is a bug so created issue on this forum.

**Comment by mikhail-bardash** [comment]
I'm having the same issue. I think this ticket should be reopened.  

```
module.vpn.aws_dx_gateway_association.dx_gateway_association: Destroying... [id=ga-3e7a2bef-cff0-654a-be7a-8904564beb42vgw-056af8780b86f14bc]

Error: error deleting Direct Connect gateway association: DirectConnectServerException: Unable to process request
	status code: 400, request id: 56e68678-019a-4fad-09cb-6d7ee40d0b09
```
