### ISSUE TITLE
Feature Request: support --target in backend remote

### ISSUE THREAD

**Issue by saitotqr** [hashicorp/terraform#22972]
### Current Terraform Version
```bash
$ terraform --version
Terraform v0.11.13
+ provider.archive v1.3.0
+ provider.aws v2.30.0
+ provider.template v2.1.2
```

### Use-cases
I'm using Terraform Cloud and sets buckend `remote`
```backend.tf
provider "aws" {
  access_key = "${var.aws_access_key_id}"
  secret_key = "${var.aws_secret_access_key}"
  region  = "ap-northeast-1"
  version = "2.30.0"
}

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "my-organization"
    workspaces = {
      name = "my-workspace"
    }
  }
}
```

Then local terraform plan with `--target` doesn't work.

```bash
$ terraform plan -target=module.my.target.name

Error: Resource targeting is currently not supported!

The "remote" backend does not support resource targeting at this time.

```

### Proposal
It make us happy if it support. `plan` that takes a long time will be shortened

**Comment by gchamon** [comment]
`terraform plan` already supports `-state` to pass an arbitraty state file. If it is passed with a remote backend enabled, `plan` should then execute with this arbitraty state locally, disabling or rendering any output plan unusable.

`apply` should never happen locally with a remote backend configured.

**Comment by bendrucker** [comment]
This was released in 0.12 as https://github.com/hashicorp/terraform/pull/24834

**Comment by nathanielks** [comment]
@bendrucker to clarify, this is for CLI-driven runs, correct? Terraform Cloud/VCS-driven runs don't yet support targeted plans?

**Comment by bendrucker** [comment]
https://www.terraform.io/docs/cloud/api/run.html#create-a-run

The API supports target addresses, which is what allows the CLI to support it. 

There's no UI in Terraform Cloud for this at the moment, but it's definitely possible to call the API to create targeted runs for existing configurations, including those received from a VCS integration.

That's different from a CLI-driven run, where Terraform is uploading configuration from your local machine and then calling the run API with that new config version. 

I've been looking to put some more time into fleshing out https://github.com/bendrucker/terraform-cloud-cli and this seems like a nice utility to offer, i.e. `terraform-cloud run create --workspace foo --target bar`. Stay tuned on that!

**Comment by nathanielks** [comment]
Much obliged, thanks for the detailed explanation @bendrucker!

**Comment by apparentlymart** [comment]
Hi all!

As @bendrucker noted, Terraform Cloud remote operations got support for `-target` a while back, although I wasn't aware of this issue at the time in order to close it. Since this issue was focused on supporting it with remote operations via the remote backend I'm going to close it now, although indeed the support for this in the Terraform Cloud UI itself might improve later.

Terraform Cloud is maintained by other teams outside of this repository, so if you have feedback about how targeting is now presented in Terraform Cloud's API or Web UI, as opposed to Terraform CLI or the remote backend behavior, you'll typically get a more prompt response by contacting Terraform Cloud support at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). Thanks!

**Comment by nathanielks** [comment]
Thank you for the update, @apparentlymart !
