### ISSUE TITLE
old terraform project failed at `terraform plan -out myplan`

### ISSUE THREAD

**Issue by KypMon** [hashicorp/terraform#23006]
I am trying to utilize an old Terraform which last was successfully built in Jul 4th this year

### Terraform Version

running from the hashiCorp/terraform:light image
```
...
Terraform v0.12.9
```

### Terraform Configuration Files

```hcl
...
terraform {
  required_version = ">= 0.12, < 0.13"
}
```

### Debug Output

https://gist.github.com/KypMon/b4b4ae47318af76ec9411b4d7ff01cc5#file-debug-log

### Crash Output

https://gist.github.com/KypMon/b4b4ae47318af76ec9411b4d7ff01cc5#file-crash-log

### Expected Behavior

successfully built

### Actual Behavior

failed as above

### Steps to Reproduce

```
terraform init -reconfigure -backend-config=bucket=$TF_VAR_s3_bucket_name -backend-config=region=$TF_VAR_aws_region 
terraform plan -out myplan -refresh=false
```
### Additional Context

Run in Cloudbee Jenkins with HashiCorp/terraform:light docker image

**Comment by teamterraform** [comment]
Hi @KypMon!

It looks like this configuration was written for Terraform 0.11 or earlier, but you are now trying to use it with Terraform 0.12 without first following [the upgrade procedure](https://www.terraform.io/upgrade-guides/0-12.html).

You can continue using this configuration with Terraform 0.11.14 if you don't wish to upgrade yet. If you _do_ wish to upgrade, you can follow the steps in the upgrade procedure to perform many of the required changes automatically using the upgrade tools.

Since the error messages you shared seem to all be expected errors resulting from not following the upgrade procedure, we're going to close out this issue. If you decide to upgrade and run into any problems during the upgrade process that are not covered by the upgrade guide, please feel free to start a topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
