### ISSUE TITLE
Terraform having issues with special characters

### ISSUE THREAD

**Issue by gangadhar01a** [hashicorp/terraform#23007]
### Terraform Version

```
...Terraform Version 0.12.9
```

### Terraform Configuration Files

```hcl
extra_config = {
       "project.plugin.NodeExecutor.WinRMexe.pass" = "j7FUBa&\:9"
   }
...
```

### Expected Behavior

Terraform should pick the provided password
### Actual Behavior

Showing the following error
27: "project.plugin.NodeExecutor.WinRMexe.pass" = "j7FgfUytrBa/:9"

The symbol ":" is not a valid escape sequence selector.

**Comment by teamterraform** [comment]
Hi @gangadhar01a!

The configuration example you showed uses a backslash `\`, but the error message you shared includes a forward slash `/`.

It's correct for Terraform to reject the sequence `\:` because the symbol `\` introduces an escape sequence but `:` is not a valid escape sequence symbol. If you intend to include a literal backslash then you must escape it using two backslashes:

```hcl
  extra_config = {
    "project.plugin.NodeExecutor.WinRMexe.pass" = "j7FUBa&\\:9"
  }
```

If you got this error message for a forward slash `/` then that _would_ be a bug, because `/` is not a significant character in string literals. Could you please confirm which of the examples shown in your issue correctly represents what you tried? Thanks!

**Comment by gangadhar01a** [comment]
Hi,

Sorry for the confusion, as you expected the password does have backslash. 
I tried 
"extra_config = {
    "project.plugin.NodeExecutor.WinRMexe.pass" = "j7FUBa&\\:9"
  }"

Expected the the terraform will write the password as "j7FUBa&\:9", instead I have "j7FUBa&\\\:9"

**Comment by deepakcpakhale** [comment]
@gangadhar01a  whenever you use backslash(\) in a string then it is considered as the beginning of an escape sequence. This means backslash + subsequent character should be a known pattern to compiler to perform certain actions. In your case \: is not a valid escape sequence.

**Comment by teamterraform** [comment]
@gangadhar01a it is not entirely clear from your last response if you were able to get this working. 

Since this appears to be a question about properly escaping characters and not a terraform bug, we suggest you ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. Thanks!
