### ISSUE TITLE
Error: Error reading /Users/lenny/.terraformrc: read /Users/lenny/.terraformrc: is a directory

### ISSUE THREAD

**Issue by LennyCastaneda** [hashicorp/terraform#23029]
### Terraform Version

```
version 0.12.9
```

### Terraform Configuration Files

```hcl
##################################################################################
#  VERSION
##################################################################################

module "terraform_version" {
  source  = "git@bitbucket.org:ciscoimpactdev/terraform-modules.git//version"
  region  = "us-west-2"
}

##################################################################################
# PROVIDER
##################################################################################

provider "aws" {
	region  = "us-west-2"
}

##################################################################################
# S3 BUCKET
##################################################################################

module "ccit_microservices_remote_state_dev" {
	source         	       = "git@bitbucket.org:ciscoimpactdev/terraform-modules.git//data/s3/backend-bucket"
	aws_account		= var.aws_account
	s3_bucket               = var.s3_bucket
	bucket_policy	        = "${data.template_file.remote_state.rendered}"
	owner                      = "DevOps"
	environment            = "Utility"
}

##################################################################################
# BUCKET POLICY
##################################################################################

data "template_file" "remote_state" {
	template = file("${path.module}/templates/remote_state_bucket_policy.tpl")

	vars = {
		s3_bucket	= var.s3_bucket
		aws_account	= var.aws_account
	}
}

##################################################################################
#  BACKEND
##################################################################################

terraform {
	backend "s3" {
		bucket          = "remote-state"
		key               = "data/s3/remote-state-dev/terraform.state"
		region          = "us-west-2"
		encrypt         = true
		dynamodb_table  = "terraform-tfstatelock"
	}
}
```

### Debug Output

There are some problems with the CLI configuration:

Error: Error reading /Users/lecastan/.terraformrc: read /Users/lecastan/.terraformrc: is a directory

As a result of the above problems, Terraform may not behave as intended.

### Expected Behavior
My configurations build and provision successfully without any unexpected issues, but this error message is disturbing and would to determine root cause and fix it.

### Actual Behavior

Just an error message. All resources and modules provisioned as expected. No unusual behavior detected on my end

### Steps to Reproduce
`terraform init`

### Additional Context

When I look inside the hidden .terraformrc directory on my machine it is empty. Is there suppose to have config files in here?

How do I remediate this issue?

**Comment by teamterraform** [comment]
Hi @LennyCastaneda!

`.terraformrc` is supposed to be a regular file, not a directory. Since your directory is empty, we'd suggest to just delete it. If you _do_ later need to set some [CLI configuration](https://www.terraform.io/docs/commands/cli-config.html) settings, you'll need to create `.terraformrc` as a file using the CLI configuration syntax.

**Comment by LennyCastaneda** [comment]
Thanks for the response. 

I wonder why all of a sudden I got this error message in the CLI? Maybe it was after I upgaded from 0.12.6 to 0.12.9?

Either way, deleting the hidden .terrformrc resolved the issue.

Thanks again.

**Comment by apparentlymart** [comment]
Hi @LennyCastaneda,

Thanks for confirming!

I'm not sure what changed between 0.12.6 and 0.12.9 but it does indeed seem like the validation rules were tightened in between; it was presumably ignoring that case before. While I believe that breaking change wasn't intentional, it doesn't seem to have been a common cause of problems and so we're going to leave that check in place to give better feedback to folks who might misunderstand the docs and _intentionally_ create a directory at that name.

Since you've found a path forward here, I'm going to close this out. Thanks for reporting this change in behavior.
