### ISSUE TITLE
backend:s3 skip_region_validation is deprecated, but there's no replacement

### ISSUE THREAD

**Issue by Karreg** [hashicorp/terraform#23039]
### Terraform Version
```
0.12.8
```

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket = "terraform-bucket-gitlab-ha"
    key    = "terraform-gitlab-ha"
    region = "eu-west-0"
    
  }
}
```

### Debug Output
```
terraform init

Initializing the backend...

Error: Invalid AWS Region: eu-west-0
```

### Additional Context
To bypass this issue, the solution is to use skip_region_validation, but it's referenced as deprecated in the documentation. There is no alternative described : `https://www.terraform.io/docs/backends/types/s3.html#skip_region_validation`

Either there is a lack of documentation, or the region will be validated without any option to work on something else than AWS, which is a very bad news.

Could you give the alternative to this option that is not deprecated, or be more precise on why and when the validation will become mandatory? It will break everything on Flexible Engine for instance...

**Comment by teamterraform** [comment]
Based on documentation in #20374 it seems that the plan was to remove the region validation altogether, but since the S3 backend is maintained by the AWS provider team (since it uses lots of logic from the AWS provider for this and other purposes) we'll leave this open for now until we can clarify the intention behind this deprecation notice in the documentation.

**Comment by bflad** [comment]
Hi @Karreg 👋  Sorry for any confusion here. This functionality still exists and is not deprecated in the Terraform 0.13 release. 👍
