### ISSUE TITLE
Variable type detection

### ISSUE THREAD

**Issue by udondan** [hashicorp/terraform#23070]
### Current Terraform Version
```
Terraform v0.12.7
```

### Use-cases

I want to be able to detect the type of a variable, so I can use it in conditions.

In it's simplest form I want to archive this:

```hcl
variable "details" {
  type = any
}

local {
  name = type(var.details) == map ? var.details["name"] : var.details
}
```

The module containing above code then can be called as

```hcl
module "foo" {
  details = "my-name"
}
```

... or ...

```hcl
module "foo" {
  details = {
    name = "my-name"
    age  = 40
  }
}
```

This is just a minimal example, where the benefit might not be obvious. My **real** use case would be to pass a list of maps/strings with potentially hundreds of items. Since in nearly all cases I only need to pass a single value I would prefer to define it as:

```hcl
module "foo" {
  details = ["a", "b", "c"]
}
```

... instead of ...

```hcl
module "foo" {
  details = [{ name = "a" }, { name = "b" }, { name = "c" }]
}
```

In the case where I need additional details, I can pass it like this:

```hcl
module "foo" {
  details = ["a", "b", "c", { name = "d", age = "40" }]
}
```

In the module the passed list will be used in a dynamic block:

```hcl
  dynamic "statement" {
    for_each = var.details
    content {
      name = type(statement.value) == map ? statement.value["name"] : statement.value
      age  = type(statement.value) == map ? statement.value["age"] : null
    }
  }
```

### Attempted Solutions
```hcl
  dynamic "statement" {
    for_each = var.details
    content {
      name = lookup(statement.value, "name", statement.value)
      age  = lookup(statement.value, "age", null)
    }
  }
```

But `lookup()` of course will fail if the variable isn't a map.

```
Error: Invalid function argument

...

Invalid value for "inputMap" parameter: lookup() requires a map as the first
argument.
```

### Proposal

I propose to introduce functions to detect the type of a variable.

A general `type(x)` returns the type of the variable. For every variable type we can have an `is*()` function, e.g. `isstring(x)`, `isnumber(x)`, `ismap(x)` etc which return either `true` or `false`

I'd be happy to create a PR implementing the new functions. Just wanted to check if such feature would be welcomed or rejected.

### References

https://stackoverflow.com/questions/58327314/get-type-of-a-variable-in-terraform?noredirect=1

**Comment by teamterraform** [comment]
Hi @udondan! Thanks for proposing this, and sorry for the delay in responding.

As Martin mentioned in his answer on Stack Overflow, the intended idiom for the Terraform language is to select one specific type for each variable and have the caller use that consistently. The aim is for there to ideally be only one way to express a particular idea, and thus future maintainers of the configuration that might not be intimately familiar with the details of the module can more easily understand from existing examples what the capabilities of the module are and how to use them.

For that reason, we're hesitant to add new functions to Terraform that might encourage using weaker type constraints (like `any`, as in your example) that would make the interface to a module less clear to someone who is reviewing only the variables and the outputs, and who isn't looking at the module's implementation.

Using the example from your Stack Overflow question to illustrate, it seems like it would cause there to be declarations like the following in callers:

```hcl
module "example" {
  source = "./example"

  detail = "foo"
}
```

An unfamiliar person viewing the above would see no indication that `detail` could be an object instead of a string, and would have to review the body of the module in order to learn what attributes are expected for such an object.

For that reason, we'd rather not include type-checking functions for now, to avoid sending the message that `type = any` should be a common usage pattern and that modules should commonly have type-variant arguments. The `any` type is there primarily to deal with situations where arbitrary data is being sent to the remote API, such as if a remote system is defined as accepting arbitrary JSON input and so the module will use `jsonencode` with the untyped variable to support that.

We may in future consider making the type constraint mechanism more flexible so that it can _explicitly_ represent that a variable can take one of a specific selection of types, in which case it would make sense to then have functions for type-testing, but generally speaking the Terraform language design prioritizes the reader over the writer and one way we achieve that is to minimize situations where there are multiple ways to say the same thing.

Hopefully the above seems like a reasonable rationale. For these reasons, we're going to close this issue. Thanks again for making this proposal!

The existing issue #19653 is representing the broader idea of putting higher-level constraints on variable values; if we make some changes in that area, that might change the situation depending on whether that feature manifests in a way that allows making it clear to module consumers (without reading the module source code) what values are permitted for a given variable. However, we are not currently working on any design work for that feature, so it's too early to say what form that might take and whether that might make variant-typed variables more palatable from a language design standpoint.
