### ISSUE TITLE
Swift state lock error

### ISSUE THREAD

**Issue by gdelaney** [hashicorp/terraform#23080]
### Terraform Version
```
Terraform v0.12.10
```

### Terraform Configuration Files
A very simple config with swift as the backend, no versioning container.
```hcl
terraform {
  backend "swift" {
    container = "test-terraform"
  }
}
resource "openstack_compute_instance_v2" "machine1" {
  region            = "region1"
  name              = "machine1"
  image_name        = "centos-7"
  flavor_name       = "0010"
  key_pair          = "cloud"
  availability_zone = "zone1"
}
```

### Debug Output
https://gist.github.com/gdelaney/1de359877f7869ea596085d5aeee1100

### Expected Behavior
It should create and use the lock file in the swift container.

### Actual Behavior
Its posting trying to create the lock file, but its reporting its unable to read the lock info.
Swift is returning a http 412 precondition error. Running the same post via curl creates the lock file as expected. The next 'terraform plan' run reads the file and reports that it is currently locked. I have run the command with OS_DEBUG=1 in the debug output.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
We are running a fairly older version of openstack keystone/swift.
The terraform command is being run after sourcing the openstack-rc.sh file.

### References
https://github.com/terraform-providers/terraform-provider-openstack/issues/733
#20211

**Comment by gdelaney** [comment]
Further digging, the header `If-None-Match: *` being sent is triggering the HTTP 412 from swift.
1. terraform is creating the container in swift
2. terraform tries to create the lock with the header `If-None-Match: *`
3. Swift returns a 412 - https://github.com/openstack/swift/blob/master/swift/obj/server.py#L788
4. terraform tries to get the lock file and gets a 404 as the file does not exist

**Comment by stampit** [comment]
Just found that broken state lock also breaks workspace removal (it's possible to remove with `-lock=false`), but you can't create another workspace with the same name afterwards.
So maybe `-lock=false` is broken too.

**Comment by RomanKrasavtsev** [comment]
Hi team, when can we expect an update? 

Locking should be disabled by default for Swift backend. Now it's now possible to use Terraform v0.12.10 with Swift backend without `-lock=false` and it means it's not possible to use `terraform console` at all, because it doesn't support `-lock` option.

Looking forward to hearing from you.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Swift backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
