### ISSUE TITLE
Provide ulimit advice after EMFILE error

### ISSUE THREAD

**Issue by josephholsten** [hashicorp/terraform#23095]
### Current Terraform Version

```
% terraform -v
Terraform v0.12.10
```

### Use-cases

Terraform is great for managing incredibly large numbers of resources. Unfortunately, sometimes the machines it is run on aren't properly tuned with a high enough user or system maxfiles, and this can lead to confusing errors.

As a user, if I run:
```
ulimit -n 256 # mac default
terraform destroy -parallelism=80
```

I'll see an error message like this in the logs:

```
2019/10/16 11:41:20 [ERROR] <root>: eval: *terraform.EvalSequence, err: Get https://cloud.example.com/instances/anyhqljse3tcuzqcaks6gviexe22h3ygo7p5o4cvtb7mrspeoxsp44hhhuyq: dial tcp 1.2.3.4:443: socket: too many open files
```

### Attempted Solutions

The user needs to modify their system configuration to increase their user or system maxfiles, eg following this on a mac: https://unix.stackexchange.com/questions/108174/how-to-persistently-control-maximum-system-resource-consumption-on-mac

### Proposal

It would be lovely if the main terraform binary could catch these errors when they occur in providers and provide a more helpful error message that would direct them to the right solution for the platform they are running terraform on.

**Comment by teamterraform** [comment]
Hi @josephholsten!

We agree that it would be nice to make errors like this more actionable. Unfortunately though, since there isn't a central place in Terraform where all sockets are opened, this isn't something that can be solved unilaterally. Instead, every codepath that opens a socket (many of which are in the individual provider codebases, and also often wrapped up in SDK abstractions that might mask the underlying error) would need to handle this separately.

For that reason, we're going to close this just because it doesn't seem like there's any general way to solve this that would cover all situations. Instead, if there's a situation where this arises more commonly for a particular provider, it could be reasonable to open an issue specifically for that situation (which, given what you showed in your error message, seems to be with in a particular provider codebase) and see if that particular codepath can return a more actionable message.

One positive here is that searching for that error message on popular search engines seems to produce plenty of information on likely causes, including guidance on how to set `ulimit`, so while ideally we'd be able to give direct feedback on that (which would, we suspect, end up being platform-specific) at least it seems that the consequences of us not being able to do so unilaterally are not dire and that hopefully making some targeted adjustments to a few common cases will be a reasonable compromise.

Thanks again for opening this! We're closing this not because we don't see the opportunity improvement, but because there isn't a general solution and thus this would need to be more specific in order to be actionable.

**Comment by josephholsten** [comment]
Thanks! I totally agree, I wasn't sure if there was a way to pass these errors up from providers gracefully. Hopefully this issue will help people encountering the error in future!
