### ISSUE TITLE
Can't upload module to private terraform registry - not found

### ISSUE THREAD

**Issue by antonputra** [hashicorp/terraform#23114]
Terraform cloud - private registry.
Not able to upload module, when I click "publish module" I get "not found"

Repository contains following files "\<org>/terraform-google-networking"

main.tf
outputs.tf
README.md
variables.tf

![Screen Shot 2019-10-17 at 9 35 56 PM](https://user-images.githubusercontent.com/9362325/67066190-3b73b200-f126-11e9-9f7a-6ce342c7629d.png)

**Comment by osulli** [comment]
I also get this. @antonputra did you find a solution?

**Comment by Chirag1233** [comment]
@antonputra  I am also getting the same error. when I try to import the module. do we have work around for it at all or do we know if this is been resolved or not?

**Comment by mhester-nutrien** [comment]
We are also getting this error. Any updates, workarounds, help?

**Comment by mhester-nutrien** [comment]
In our case this was a permissions issue. We had to have an owner of the organization add the module, and then afterwards any of us could update.

Hashi really needs a better error message for this

**Comment by apparentlymart** [comment]
Hi @antonputra, and everyone else! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
