### ISSUE TITLE
Default value for map variables

### ISSUE THREAD

**Issue by phrawzty** [hashicorp/terraform#2312]
Hello,

As suggested by @jdotpz in [the google group](https://groups.google.com/forum/#!topic/terraform-tool/jUOqb2J0D9s) it would be handy if map variables were able to have a default value. Example:

``` ini
variable "ec2_type" {
    default = {
        stage = "r3.large"
        prod = "r3.2xlarge"
        * = "m3.medium"
    }
}
```

Such that:

``` ini
## defined (actual behaviour)
$environment="stage"
${lookup(var.ec2_type, var.environment)} == "r3.large"

## catch all (proposed behaviour)
$environment = "foo"
${lookup(var.ec2_type, var.environment)} == "m3.medium"
```

Another possible extension would be to allow for differentiating between "catch-all" and "empty / undefined" - this should be debated first, however. :smirk: :

``` ini
variable "ec2_type" {
    default = {
        stage = "r3.large"
        prod = "r3.2xlarge"
        default = "m3.medium"
        none = "t1.micro"
    }
}
```

Such that:

``` ini
## defined (actual behaviour)
$environment="stage"
${lookup(var.ec2_type, var.environment)} == "r3.large"

## catch all (proposed behaviour)
$environment = "foo"
${lookup(var.ec2_type, var.environment)} == "m3.medium"

## undef (possible behaviour)
${lookup(var.ec2_type, var.environment)} == "t1.micro"
```

**Comment by ryangraham** [comment]
I was just looking for something like this for selecting PV versus HVM AMIs by instance_type.

**Comment by phinze** [comment]
@ryangraham you might be interested in https://github.com/terraform-community-modules/tf_aws_virttype :grinning:

**Comment by gozer** [comment]
:+1:

**Comment by joshuajabbour** [comment]
I'd find this incredibly handy, in either the form above, or as a third parameter to `lookup` as described in #1505.

**Comment by arshdeeptinna** [comment]
Isn't this functionality supported sine 0.7 in the following form?
```
lookup(var.amis, var.env, 'Default-AMI')
```

**Comment by joshuajabbour** [comment]
Yes, it got implemented but many of the PRs asking for it were updated slowly. Here's another reference, demonstrating how you can use a `*` or `default` param in a map to achieve it (with the third param in `lookup`). Not quite as clean as an automatic fallback, but more explicit so maybe better.

**Comment by apparentlymart** [comment]
Hi all,

As @arshdeeptinna pointed out, the `lookup` function now has a third argument for specifying defaults. Terraform 0.7 added the first-class index operator like `var.amis[var.env]`, which has been generalized for the forthcoming v0.12.0 release to work with any expression rather than just with variables, so from that v0.12.0 onwards the `lookup` function's primary purpose will be providing a fallback value, and the index operator should be used in all other cases.

Since there's already a solution for this, I'm going to close this out. Sorry for letting this sit here for so long.
