### ISSUE TITLE
Can not specify tags for VCS branch

### ISSUE THREAD

**Issue by marko7460** [hashicorp/terraform#23131]
### Terraform Version
```
Terraform Cloud 0.12.12
```

### Steps to Reproduce
1. Using UI or API try to set VCS branch of a workspace to a tag

### Results
I keep getting
```
Error saving version control settings
Branch doesn't exist
```

### Additional Context
Usual development process:
1. dev environment can be deployed/modified using terraform code in any non master branch.
1. stg environment can be deployed/modified using terraform code from master branch only.
1. prd environment can be deplyed/modified using terraform code from the tags only

**Comment by debovema** [comment]
Any news on this one ?

The usual development process in additional context makes a lot of sense.

**Comment by apparentlymart** [comment]
Hi @marko7460! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
