### ISSUE TITLE
Indexes on null resources no longer return null

### ISSUE THREAD

**Issue by bwhaley** [hashicorp/terraform#23140]
### Terraform Version

```
Terraform v0.12.12
```

### Terraform Configuration Files

```hcl
variable "create_null_resource" {
  type    = bool
  default = false
}

resource "null_resource" "example" {
  count = var.create_null_resource ? 1 : 0
}

output "null_output" {
  value = null_resource.example[0].id
}
```

### Debug Output

https://gist.github.com/bwhaley/ec3bde44cb6e58d46177d64c22af3420

### Expected Behavior

The value for `null_output` output should be empty if `var.create_null_resource` is false.

### Actual Behavior

The following index error occurs:

```
Error: Invalid index

2019/10/21 09:34:02 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
  on test.tf line 11, in output "null_output":
  11:   value = null_resource.example[0].id
    |----------------
    | null_resource.example is empty tuple

The given key does not identify an element in this collection value.
```
 
### Steps to Reproduce

1. Use the configuration defined above.
2. Run `terraform plan`

### Additional Context

This behavior changed between `v0.12.10` and `v0.12.11`. Previously, indexed resource references with null values produced a null output. so the configuration above was valid even if `create_null_resource` was `false`. Now, references to indexed resources that have null values creates an invalid index error.

Is this now the expected behavior, or is it a bug?

### References

Possibly introduced in this PR? https://github.com/hashicorp/terraform/pull/22846/files#diff-5

**Comment by jbardin** [comment]
Hi @bwhaley,

Sorry this tripped you up, but it is the expected behavior. The expression actually returned "unknown" in this case, but depending on the context, the value may have been coerced to `null` The original config should not have been valid, and fixing the bugs caused by this requires correctly evaluating the expression in all cases. 

The errors were ignored most of the time in resource, in data sources however the config would delay evaluation and then show an error during apply (even when guarded by a conditional). It would also generally cause hard to diagnose errors when the unexpected unknown values cascade throughout the configuration, either by effecting other computed attributes, or by causing errors like `provider X produced an invalid new value for ...` which could in turn cause changes in other dependent resources. 

The good news is that the same fix should allow proper evaluation of a conditional containing that expression, so guarding with the same check should work as expected:

```
resource "null_resource" "example" {
  count = var.create_null_resource ? 1 : 0
}

output "null_output" {
  value = var.create_null_resource ? null_resource.example[0].id : ""
}
```

**Comment by bwhaley** [comment]
Understood, thanks for the clarification.

**Comment by lorengordon** [comment]
The old tf0.11 hack for outputs on conditional resources still works. The construction is a little simpler:

```
resource "null_resource" "example" {
  count = var.create_null_resource ? 1 : 0
}

output "null_output" {
  value = join("", null_resource.example.*.id)
}
```
