### ISSUE TITLE
static outputs from module not shown after terraform apply -module

### ISSUE THREAD

**Issue by marthag8** [hashicorp/terraform#23158]
For a special workflow, I need to apply a specific module with `terraform apply -target=module.<mymodule>`.  Then, I need to get the outputs from this module with `terraform output -module=<mymodule>`.  This works correctly for outputs that are computed from a resource, but does not output anything for static strings until a general `terraform apply` has been run.

I have a very simple reproduction below.
### Terraform Version

```
Terraform v0.11.14
```

### Terraform Configuration Files

main.tf:
```hcl
module "test" {
  source = "./mod"
}
```
mod/main.tf
```hcl
output "mod-output" {
  value = "123"
}
```
### Expected Behavior
Module output should have been displayed.

### Actual Behavior

Static outputs are not shown.

### Steps to Reproduce

```
$ terraform init
Initializing modules...
- module.test
  Getting source "./mod"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ terraform apply -target=module.test

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
$ terraform output -module=test
The module root.test could not be found. There is nothing to output.
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
$ terraform output -module=test
mod-output = 123
```

**Comment by ShaKann** [comment]
We face same issue... Is there any schedule when we can expect this bug to be fixed?

**Comment by camlow325** [comment]
I encountered this on Terraform v0.12.20. It seems somewhat related to #23073. In all of these cases, I've been able to have the outputs populated (or repopulated back) into state after the apply with "-target" by running `terraform refresh`. That doesn't seem ideal but at least it provides a way to get the missing outputs into state without having to do a full apply (without "-target" arguments).

**Comment by jecnua** [comment]
Still present in Terraform v0.13.4

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

In this particular case, I'm aware that several comments describe seeing it in 0.12 and 0.13, but I think the issue you're running into is that outputs from child modules are not expected to be printed. According to the [docs](https://www.terraform.io/docs/language/values/outputs.html), only root module outputs are printed to CLI output. The primary purpose of outputs from child modules is to expose values to be used elsewhere, and often this means they get fed into other modules rather than necessarily being printed as outputs.

I think I've explained this issue, so I'm going to close it, but if I've misunderstood this and you're confident you're seeing a bug please please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
