### ISSUE TITLE
Having Issues with Terraform Apply Just hanging

### ISSUE THREAD

**Issue by blong5** [hashicorp/terraform#23155]
I'm new to posting issues on here, so if this is the wrong place please let me know

Here recently in the last 2 weeks Whenever I do a Terraform plan or apply the window will refresh the state load a bunch of items and then will hang for a while. I often have to close the window or restart the session and do my apply again to get it to go through. I'm still running v. 11 as I haven't have time to update the syntax on my repos to use. V.12 What can I do to fix this?

**Comment by mildwonkey** [comment]
Hi @blong5 ! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. It's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) for questions, where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

Thank you!
