### ISSUE TITLE
0.12.8 Error: Attribute name required

### ISSUE THREAD

**Issue by sharpjl** [hashicorp/terraform#23166]
The following statement was broken after upgrading from 0.11.14 => 0.12.8.

```
  lifecycle {
    ignore_changes = ["tags.%", "tags.kubernetes"]
  }
```

The upgrade utility stated that nothing needed to be changed.

```
$ terraform 0.12checklist
Looks good! We did not detect any problems that ought to be
addressed before upgrading to Terraform v0.12.

This tool is not perfect though, so please check the v0.12 upgrade
guide for additional guidance, and for next steps:
    https://www.terraform.io/upgrade-guides/0-12.html
$ terraform version
Terraform v0.11.14
+ provider.aws v2.12.0
+ provider.random v2.1.2
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.0. You can update by downloading from www.terraform.io/downloads.html
```
Here's the terraform validate output from 0.12.8:
```
$ terraform validate

Error: Attribute name required

  on subnet.tf line 19, in resource "aws_subnet" "public_subnets":
  19:     ignore_changes        = ["tags.%", "tags.kubernetes"]

Dot must be followed by attribute name.


Error: Attribute name required

  on subnet.tf line 41, in resource "aws_subnet" "private_subnets":
  41:     ignore_changes        = ["tags.%", "tags.kubernetes"]

Dot must be followed by attribute name.


Error: Attribute name required

  on vpc.tf line 14, in resource "aws_vpc" "main":
  14:     ignore_changes = ["tags.%", "tags.kubernetes"]

Dot must be followed by attribute name.
```
Removing the "tags.%" solves the problem and I can successfully execute the terraform 0.12upgrade. Or I can proceed with the 0.12upgrade and get code that works. However, it causes a problem with how the code functions. 

The terraform 0.12.8 code looks like this:
```
  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      tags,
      tags.kubernetes,
    ]
  }
```
Previously, I was able to add tags in the console and terraform apply would ignore them. I've read on another reported issue that the removal of .% is expected. That the syntax was never officially supported and was working only due to an implementation detail of how maps were stored in the state of terraform 0.11. 

Is there a way to have terraform apply ignore the tags add via the console? Would I have to add them individually to the terraform code??

**Comment by teamterraform** [comment]
Hi @sharpjl,

If you wish to have Terraform ignore changes to a tag, you can define an _initial_ value for that tag in Terraform and then ignore it with `ignore_changes`:

```hcl
  tags = {
    kubernetes = "placeholder-value"
  }

  lifecycle {
    ignore_changes = [tags.kubernetes]
  }
```

It's important that the tag already exist because adding a new item to a map is considered to be a change to that map as a whole (because now expressions like `length(aws_vpc.main.tags)` would return a different value even though it doesn't refer to that individual tag). If Terraform only sees the value of that existing tag changing, and it was already known to Terraform, then it will be treated only as a change to the `kubernetes` element specifically.

If you have any follow-up questions about this, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
