### ISSUE TITLE
Feature Request:  If Exists Use Else Create

### ISSUE THREAD

**Issue by frugecn** [hashicorp/terraform#23178]
Feature Request

Need the ability to check to see if an object already exists and then be able to use it else create a new object.

### Current Terraform Version
0.12.12

```
...
```

### Use-cases
Example, in AWS, if a security group name xyz_sg already exists get the id of that security group for use in other parts of the terraform scripts.  If the group doesn't exist, create the xyz_sg group to be used.

### Attempted Solutions
Data aws_security_group sg {
    name = "xyz_sg"
}

resource aws_security_group sg {
    name = xyz_sg
    count = data.aws_security_group.sg.id == "" ? 1 : 0
}

Unfortunately the data.aws_security_group throws an error

**Comment by teamterraform** [comment]
Hi @frugecn! Thanks for sharing this use-case.

This pattern is intentionally not supported in Terraform because it would make it unclear to future readers of the configuration whether a particular object is managed by Terraform or not. Instead, you should decide for each situation whether the object is expected to exist already or whether it needs to be created and state that decision explicitly in your configuration.

There's some information on alternative approaches in the Terraform documentation page [Module Composition](https://www.terraform.io/docs/modules/composition.html), and in particular in the subsection [Conditional Creation of Objects](https://www.terraform.io/docs/modules/composition.html#conditional-creation-of-objects).

Since the capability you are describing is intentionally not supported, we're going to close this. Thanks for taking the time to share it, though! If you have any questions about the module composition patterns, please feel free to start a new topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
