### ISSUE TITLE
Add Unmarshal func to jsonplan package

### ISSUE THREAD

**Issue by jwenz723** [hashicorp/terraform#23170]
### Current Terraform Version

```
Terraform v0.12.12
```

### Use-cases

I would like to build a simple application that could be run in a CI pipeline that could run policy enforcements on terraform files. For instance, don't allow IAM policies to be defined with '*' permissions, or only allow certain EC2 instance types.
### Attempted Solutions

* My first attempt was to write some policies using terraform sentinel, then use sentinel simulator in a CI pipeline. Unfortunately, the simulator can't be executed on a real terraform plan output (afaik).
* My next (and current) attempt is to write a simple application in go that parses the json output of `terraform show -json mytfplan`, then search through the json for particular policy violations. I have gotten this working, but I am manually copying over the json schema by reverse engineering the [Marshal](https://github.com/hashicorp/terraform/blob/90ecd17bd536cdcb16ea1293b4aff4e247679215/command/jsonplan/plan.go#L89) func. It would be much nicer if there was a simple `Unmarshal()` func that you could pass a json string to.
### Proposal

Add an `Unmarshal()` func into the [jsonplan](https://github.com/hashicorp/terraform/blob/90ecd17bd536cdcb16ea1293b4aff4e247679215/command/jsonplan/plan.go) package near the `Marshal()` func.
### References

Not that I am aware of

**Comment by jwenz723** [comment]
I should add that the reason why I can't just use `json.Unmarshal()` is because the struct types that are used within the jsonplan `func Marshal()` are unexported, so I cannot reference them within my application.

**Comment by jwenz723** [comment]
I think something as simple as this could work:
```golang
func Unmarshal(b []byte) (plan, error) {
	var p plan
	err := json.Unmarshal(b, &p)
	return p, err
}
```

This would return a `plan` object, which is helpful since that is an unexported type. All the fields on that type are exported, so they would be accessible once the object was returned.

**Comment by teamterraform** [comment]
Hi @jwenz723,

If you are writing your code in Go, you can use the types in [the `terraform-json` package](https://godoc.org/github.com/hashicorp/terraform-json) to ease implementation. You can use [the `Plan` type](https://godoc.org/github.com/hashicorp/terraform-json#Plan) as your unmarshal target for the JSON plan result.

Please note that Terraform CLI itself (_this_ repository) is not a Go library and its packages should not be imported into other codebases. This repository's tags reflect major/minor releases of Terraform itself, and make no guarantees about the stability of or breaking changes to the Go packages inside.

If you have feedback about the `terraform-json` package, please feel free to open issues in its repository. We're going to close this one just because unmarshalling the JSON is not within the scope of this codebase, and we don't intend to make changes in _this_ repository related to that. Thanks!

**Comment by jwenz723** [comment]
That is exactly what I was looking for. Thank you.
