### ISSUE TITLE
Terraform 0.12.12 format & formatlist no longer output a empty value if precision is 0 (ie %0.0s or %.0s)

### ISSUE THREAD

**Issue by gchristidis** [hashicorp/terraform#23189]
The format and formatlist function do not adhere to a precision of 0 in the format for %s (eg %0.0s or %.0s), it just outputs the entire string.  This worked correctly in terraform 0.11

### Terraform Version
```
Terraform v0.12.12
```

### Terraform Configuration Files
```hcl
output "format" {
  value = "${format( "%.0s", "one" )}"
}
output "formatlist" {
  value = "${formatlist( "%.0s", list("one", "two", "three") )}"
}
```

### Output
Running with terraform 0.11.14 the following is output
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

format =
formatlist = [
    ,
    ,

]
```

Running with terraform 0.12.12 the following is output
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

format = one
formatlist = [
  "one",
  "two",
  "three",
]
```

### Expected Behavior
It should output an empty string and an array of 3 empty values, the same as terraform 0.11

### Actual Behavior
It is outputing the a string and the list elements with the full values of the arguments to format

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
This can also be reproduced in the console
terraform 0.11.14 console
```
> format("%s", "one")
one
> format("%.0s", "one")

> formatlist("%s", list("one", "two", "three"))
[
  "one",
  "two",
  "three",
]
> formatlist("%.0s", list("one", "two", "three"))
[
  "",
  "",
  "",
]
```
terraform 0.12.12 console
```
> format("%s", "one")
one
> format("%.0s", "one")
one
> formatlist("%s", list("one", "two", "three"))
[
  "one",
  "two",
  "three",
]
> formatlist("%.0s", list("one", "two", "three"))
[
  "one",
  "two",
  "three",
]
```

**Comment by teamterraform** [comment]
Hi @gchristidis! Thanks for reporting this.

Terraform 0.12 uses an entirely different implementation of formatting because it's now working with the Terraform 0.12 type system. Some of its behaviors are unfortunately slightly different in the new implementation, either intentionally (due to different semantics of the new type system) or unintentionally (due to bugs in the implementation).

It seems that indeed there is a bug in the new version where it is treating a precision of zero the same as not specifying a precision at all. Unfortunately, to change that now would introduce _another_ breaking change relative to the latest release, so instead it's likely that we'll address this just by documenting that situation, at least in the short term.

Thanks again for opening an issue for this.
