### ISSUE TITLE
Unable to use list with template_file

### ISSUE THREAD

**Issue by sce81** [hashicorp/terraform#23210]
### Terraform Version
Terraform v0.11.14
+ provider.template v2.1.2
+ provider.vault v2.5.0

Terraform v0.12.8
+ provider.template v2.1.2
+ provider.vault v2.5.0

```
...
```

### Terraform Configuration Files

```hcl
path "${brand}/${env}/*" {

  policy = ["read" , "write"]

}
```

### Debug Output

```
  ~ resource "vault_policy" "main" {
        id     = "inseason-DEV5-rw"
        name   = "inseason-DEV5-rw"
      ~ policy = <<~EOT
            path "inseason/DEV5/*" {
          -   //policy = ["read","write"]
          + 
          +   policy = ["read" , "write"]
          + 
            }
        EOT
    }

-----


Code: 400. Errors:

* failed to parse policy: path "inseason/DEV5/*": At 3:12: root.Policy: unknown type for string *ast.ListType

  on ../../tf-module-vault-policy-creation/main.tf line 1, in resource "vault_policy" "main":
   1: resource "vault_policy" "main" {
```
### Expected Behavior

policy should be accepted as static list
### Actual Behavior

Terraform error on presentation of list - single String value works OK.

**Comment by teamterraform** [comment]
Hi @sce81,

This error seems to be coming from the Vault provider's parsing of the policy document, not from `template_file`. For that reason, we're asking our bot to move this issue over to the Vault provider repository.

As an aside, note that for Terraform 0.12 or later the `template_file` data source has been replaced with [the `templatefile` function](https://www.terraform.io/docs/configuration/functions/templatefile.html). The data source continues to exist for 0.11 users, but we recommend those using Terraform 0.12 to migrate to the `templatefile` function instead because it integrates better with the Terraform language and also tends to cause the template rendering to happen in a more appropriate location in your configuration where it's easier to see what the result is used for.

**Comment by sce81** [comment]
Hi, i have tried both template_file in tf0.11.14 and templatefile in tf0.12.8 and neither are able to process this field correctly.
