### ISSUE TITLE
Make `chunklist` work on lists where elements have different types

### ISSUE THREAD

**Issue by seddarj** [hashicorp/terraform#23220]
### Current Terraform Version

```
Terraform v0.12.12
```

### Use-cases

Some functions work well on lists where elements have different types while others don't. It would be nice if all functions including `chunklist` worked on those lists where elements have different types.

For instance, running `chunklist(["a", { "b" = "c" }], 1)` leads to the following error: `Invalid value for "list" parameter: all list elements must have the same type.`

### Attempted Solutions

`chunklist` can be emulated by using a loop along with the `slice` function.

`chunklist(["a", { "b" = "c" }], 1)` can therefore be replaced by: 
```hcl
[ for i in range(0, 2): slice( ["a", { "b" = "c" }], i, i+1)]
```
which is quite verbose.

Increasing the chunksize is also cumbersome and leads to the following syntax: 
```hcl
[ for i in range(0, 1): slice( ["a", { "b" = "c" }], i*2, (i+1)*2)]
```

### Proposal

Make all functions that work on lists (including `chunklist`) work on heterogeneous lists.

**Comment by teamterraform** [comment]
Hi @seddarj,

Thanks for the feed back. A major part of the enhancements for the 0.12 release has to do with the strict type system the was added. The definition of a "list" in this type system is an ordered collection of values of homogeneous type. Because the list type functions need to return a list in order to satisfy the input types for other arguments, they cannot readily accept non-list parameters.

The syntax used in the for expressions is leveraging another type, the `tuple`, which can have differing element types. While there could be other functions added to operate on tuple collections, for now the flexibility of the for expressions should provide a much simpler, albeit slightly more verbose interface for users to work with, as opposed to creating even more functions for manipulating collections.
