### ISSUE TITLE
Missing dict attribute causes coalescelist to error

### ISSUE THREAD

**Issue by holmesb** [hashicorp/terraform#23243]
### Terraform Version: v0.12.12
```
variable "systems" {
 default = [
    {
      hostname = "host-a",
      ip_address = "10.0.0.1",
      disk_pool_a = ["sda", "sdb"]
      disk_pool_b = ["sdc", "sdd"]
    },
    {
      hostname = "host-b",
      ip_address = "10.0.0.2",
      disk_pool_a = ["sda", "sdb"]
    },
]
```
Notice host-b has no `disk_pool_b` attribute.  From this I'm trying to create lists of strings:
```
locals {
  lists_of_volume_groups = [
    for system in var.systems: [
      for disk in concat(coalescelist(system.disk_pool_a, []), coalescelist(system.disk_pool_b, [])):
        format("{\"vgname\": \"vg_%s\"}", disk)
    ]
  ]
}
```

But this errors:
```
Error: Unsupported attribute

  on ../../modules/main.tf line 69, in locals:
  69:       for device in concat(coalescelist(system.disk_pool_a, []), coalescelist(system.disk_pool_b, [])):

This object does not have an attribute named "disk_pool_b".
```
Only a minority of systems have a `disk_pool_b`, and I don't want to have to specify an empty `disk_pool_b = []` in every system without this pool.

### Expected Behavior
Lists of volume groups is created, without having to specify an empty list attribute in every system.

Is there any other way than using `coalescelist`?

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
