### ISSUE TITLE
Possibly wrong remote_state relative path with terraform apply DIR

### ISSUE THREAD

**Issue by bentinata** [hashicorp/terraform#23251]
### Terraform Version
```
0.12.12
```

### Terraform Configuration Files
```hcl
data "terraform_remote_state" "relative" {
  backend = "local"
  config = {
    path = "../terraform.tfstate"
  }
}
```

### Crash Output
```
Error: Unable to find remote state

  on main.tf line 0, in data "terraform_remote_state" "relative":
  0: data "terraform_remote_state" "relative" {

No stored state was found for the given workspace in the given backend.
```

### Expected Behavior
Resolve relative path from `DIR` arguments.

### Actual Behavior
Resolve relative path from current dir.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. Create workspace with relative `remote_state` data dependency.
2. `terraform apply path/to/workspace`

**Comment by teamterraform** [comment]
Hello!

Paths are always relative to the working directory, not the module source. You are likely looking for one of the [`path` references](https://www.terraform.io/docs/configuration/expressions.html#path-module) available for interpolation.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
