### ISSUE TITLE
remote backend does not allow supplying token via environment

### ISSUE THREAD

**Issue by mikepea** [hashicorp/terraform#23262]
### Current Terraform Version

v0.12.14-dev built against f9f73204383953e1b7fb91af6c56573cc0be2c02

also v0.12.13 :)

### Use-cases

I am using the remote backend for Terraform Cloud, and was looking for a way to specify the user token without needing to write it to either my config, or the credentials section of .terraformrc. Both would require it being stored in plaintext.

I've been enjoying using envchain to ensure my AWS creds never sit on disk in plaintext, and was hoping to be able to use the same workflow with the terraform remote backend, eg:
    
    envchain --set mikepea-tfe TF_REMOTE_BACKEND_TOKEN
    envchain mikepea-tfe terraform init

Unfortunately, the remote backend currently doesn't support an envvar means of specifying this token.

### Attempted Solutions

I've checked the code in `backend/remote/backend.go` and can confirm the token can only come from config or the .terraformrc credentials section.

### Proposal

Allow remote backend token to be passed via TF_REMOTE_BACKEND_TOKEN environment variable.

### References

#21275 proposes a similar solution, but I'm not convinced that appending the hostname in the envvar name is a good idea. Certainly not needed for envchain workflow.

**Comment by apparentlymart** [comment]
I've implemented a simple credentials helper plugin [`terraform-credentials-env`](https://github.com/apparentlymart/terraform-credentials-env) that can be used with existing Terraform releases to provide credentials from environment variables. This is a personal project rather than an official HashiCorp project, but I'm sharing it here in the hope that it's useful.

It meets the requirement of being explicit about which token belongs to which hostname by using an environment variable naming scheme that includes a transformed version of the hostname. For example, for Terraform Cloud the environment variable would be `TF_TOKEN_app_terraform_io` to specify the hostname `app.terraform.io`.

**Comment by apparentlymart** [comment]
I see that I originally left my comment about why the hostname-specificity is a requirement in the PR #23263. Given that, I'm going to close this issue just to consolidate with #21275, because both of them represent the use-case of providing tokens via environment variables, and differ only in what they propose the environment variable(s) to be called.

Thanks for sharing this feature request, @mikepea!

**Comment by mikepea** [comment]
This is great, thanks for sharing!
