### ISSUE TITLE
dev build of CLI can break state of Terraform Cloud workspace

### ISSUE THREAD

**Issue by mikepea** [hashicorp/terraform#23264]
### Terraform Version

```
v0.12.4 -- a dev build, running against TFC with max available v0.12.3
```

### Terraform Configuration Files

I was importing this resource when I noticed this failure case:

```hcl
resource "tfe_workspace" "m53-kube-playground" {
  name         = "m53-kube-playground"
  organization = "mikepea"
}
```

### Expected Behavior

Resouce successfully imported via `terraform import tfe_workspace.m53-kube-playground mikepea/m53-kube-playground`

`terraform plan` after import would show plan output for this resource.

### Actual Behavior

`terraform import tfe_workspace.m53-kube-playground mikepea/m53-kube-playground` was successful, updated state in Terraform Cloud:

https://app.terraform.io/app/mikepea-tfe-terraform/workspaces/m53-tfe-terraform/states/sv-82uQSfX3ZCKCb3dg

However, this state now has been created with 'v0.12.4' -- as it was imported with terraform CLI build with 'make dev'.

Subsequent `terraform plan` (CLI or via UI) now fails with:

```
Error refreshing state: state snapshot was created by Terraform v0.12.14, which is newer than current v0.12.13; upgrade to Terraform v0.12.14 or greater to work with this state
```

***A side issue is that I cannot see a way of removing this 'corrupt' state file, so now I can't use this workspace***

### Steps to Reproduce

1. `make dev` from master hashicorp/terraform
2. create a resource to be imported into TFC
3. `terraform import` that resource so TFC state is updated
4. run `terraform plan` -- should fail based on TFC not supporting dev version of CLI

### Additional Context

The important thing to note about this issue is that it has resulted in a broken workspace -- I don't seem to be able to delete the corrupted state file, which now means I can't work with the workspace.

Update: I've tried to 'fix' the broken state by force pushing an older state, but this still results in the 'Error refreshing state: state snapshot was created by Terraform v0.12.14' error.

### References

#21773 seems to refer to a previous case where this could occur on terraform upgrade. I can't tell if that was fixed from the bug report though.

**Comment by apparentlymart** [comment]
Hi @mikepea,

I think we had another issue that was tracking the problem of version mismatches, and therefore we ended up losing track of this one. Recent changes to Terraform Cloud and to the remote backend should have addressed this problem in two different ways:

* When performing local operations against a Terraform Cloud workspace that normally does remote operations, the remote backend will return an error if the local CLI version doesn't match the workspace's configured CLI version, in order to prevent the local operation from potentially creating a state that the remote execution environment would not be able to interpret.
* Recent Terraform CLI releases also now check state compatibility based on the state format version number rather than the Terraform CLI version number that created it, so even if you _do_ somehow end up with the state having been created by a CLI version other than the current one (perhaps you switched back to an earlier CLI patch release, for example), Terraform will still accept it as long as it has a compatible snapshot format version.

For that reason, I'm going to close this out. There are more details in some newer issues and PRs which I unfortunately don't have handy right now, but if you look at the changelogs for recent Terraform releases you can see how the above changes developed and where they are available.

Thanks for reporting this!
