### ISSUE TITLE
credential_source not working when profile switching inside terraform

### ISSUE THREAD

**Issue by lifeofguenter** [hashicorp/terraform#23275]
running terraform with `AWS_PROFILE=foobar`, where `foobar` defines `credential_source = Ec2InstanceMetadata` in the `~/.aws/credentials` works, because the auth happens natively via the go-sdk (see: https://github.com/aws/aws-sdk-go/pull/2201/files).

However, if I specify `profile` in terraform itself (either backend, or provider), then unfortunately a slimmed-down version of the aws-sdk is being used (https://github.com/hashicorp/aws-sdk-go-base/blob/master/awsauth.go) where it does not properly parse `credentials_source` from the aws-config and thus profile switching fails.

**Comment by lifeofguenter** [comment]
@pselle this is also an issue with core terraform, not the aws provider. Remote backend s3 is implemented in this repository. This bug is valid, please do not close 😞

**Comment by pselle** [comment]
@lifeofguenter Thanks for the clarification, that was not clear from my first read, especially since this issue didn't use the issue template.

It looks like your issue might be covered here: https://github.com/hashicorp/aws-sdk-go-base/issues/13, or open another issue on that repo if it doesn't capture it -- the team monitoring this repo doesn't maintain that project, so getting it into their queue is a better call.

Again, thanks for checking in, as I'll close the other issue on the provider since it's not a provider issue.
