### ISSUE TITLE
Tainted CloudWatch Log Group cannot be recreated

### ISSUE THREAD

**Issue by MRostanski** [hashicorp/terraform#23309]
### Terraform Version

```
Terraform v0.12.13
+ provider.aws v2.34.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
...
```

### Terraform Configuration Files

I am trying to replace a cloudwatch log group with taint.

The code in question is a part of module `eks`:

```hcl
resource "aws_cloudwatch_log_group" "eks" {
  name              = format("/aws/eks/%s/cluster", local.cluster_name)
  retention_in_days = var.cloudwatch_logs_retention

  tags = merge(
    map(
      "Name", format("/aws/eks/%s/cluster", local.cluster_name),
    ),
  local.tags)

  lifecycle {
    create_before_destroy = false
  }
}
```

### Expected Behavior

The resource should be destroyed and then created.

### Actual Behavior

```
Terraform will perform the following actions:

  # module.eks.aws_cloudwatch_log_group.eks is tainted, so must be replaced
+/- resource "aws_cloudwatch_log_group" "eks" {
      ~ arn               = "arn:aws:logs:eu-central-1:xxxxxxxxxxxx:log-group:/aws/eks/hroot34-lab-dev-main-eks/cluster:*" -> (known after apply)
      ~ id                = "/aws/eks/hroot34-lab-dev-main-eks/cluster" -> (known after apply)
        name              = "/aws/eks/hroot34-lab-dev-main-eks/cluster"
        retention_in_days = 1
        tags              = {
            "Environment" = "dev"
            "Layer"       = "EKS"
            "Management"  = "Terraform"
            "Name"        = "/aws/eks/hroot34-lab-dev-main-eks/cluster"
            "Owner"       = "hroot34"
            "Project"     = "lab"
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.eks.aws_cloudwatch_log_group.eks: Creating...

Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
	status code: 400, request id: a741b559-4d7b-454a-abbd-fd04493063e1:  The CloudWatch Log Group '/aws/eks/hroot34-lab-dev-main-eks/cluster' already exists.

  on eks/cwlogs.tf line 1, in resource "aws_cloudwatch_log_group" "eks":
   1: resource "aws_cloudwatch_log_group" "eks" {

```

### Steps to Reproduce

1. After using `terraform taint module.eks.aws_cloudwatch_log_group.eks`, terraform behaves as expected:

```
$ terraform taint module.eks.aws_cloudwatch_log_group.eks
Resource instance module.eks.aws_cloudwatch_log_group.eks has been marked as tainted.
```

2. Perform `terraform apply` once again.

### Additional Context

The cloudwatch log group is not empty. Maybe the message is just wrong?

Running on Linux Mint Tara.

### References

(none)

**Comment by teamterraform** [comment]
Hi @MRostanski! Sorry for this strange behavior, and thanks for reporting it.

If one resource refers (directly or indirectly) to another resource that has `create_before_destroy = true` set then the referring resource is forced to be `create_before_destroy = true` because otherwise this would create an impossible situation where there is no correct order to perform the various operations. Do any of `local.cluster_name`, `var.cloudwatch_logs_retention`, or `local.tags` depend (possibly also indirectly) on another resource that has `create_before_destroy` set?

If so, one thing we notice from your example is that Terraform is currently treating an explicit `create_before_destroy = false` the same as not setting `create_before_destroy` at all, and thus allowing it to be overridden with `true` even though you explicitly set it to `false`. It'd be better for Terraform to notice you tried to explicitly set it to `false` and produce a clear error message explaining why that situation is impossible, so if the above paragraph explains what's going on here then we'll use this issue to represent adding a clearer error message for that case.

If none of those variables do depend on something with `create_before_destroy` set then we'll unfortunately need the full trace log that was requested in the issue template in order to debug further, since we'll need to understand what other situation prompted Terraform to use treat this replace action as a create-before-destroy.

**Comment by MRostanski** [comment]
Thanks for quick answer, that was fast :)

I think you may have a point with dependencies. I have a dependency ON an log group in question, so in fact destroying this group _before_ creating a new one would have jeoperdized the entire cluster:

```hcl
resource "aws_eks_cluster" "eks" {
  depends_on = [
    "aws_cloudwatch_log_group.eks",
    "local_file.aws_auth_cm_yaml"
  ]

```
So, just as I thought, the message is a bit misleading. I suggest a very simple solution:

## Actual Behaviour

```
Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
```

## Expected Behaviour

```
Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists or a dependency is in place
```

**Comment by jbardin** [comment]
Hi @MRostanski,

Sorry for the long delay in resolving this.

It looks like everything is working as expected from within Terraform. If The `aws_cloudwatch_log_group` does need to be created before it is destroyed, there is a `name_prefix` attribute to allow for this, which generates unique names for each instance. You cannot override `create_before_destroy`, as that would cause a dependency cycle.

If you feel there is some improvement to be made in the resource error handling, please feel free to file an issue with the aws provider.

Thanks!
