### ISSUE TITLE
Error: Inconsistent conditional result types

### ISSUE THREAD

**Issue by yujunz** [hashicorp/terraform#23316]
### Terraform Version

```
Terraform v0.12.10
+ provider.aws v2.35.0
```

### Terraform Configuration Files

```hcl
locals {
  ## Workaround to solve this problem https://github.com/hashicorp/terraform/issues/11210
  source_documents = ["${concat(list("null"), var.source_documents)}"]

  policies = [
    "${length(local.source_documents) > 1 ? element(local.source_documents, 1) : data.aws_iam_policy_document.empty.json}",
...
  ]
}
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

No error

### Actual Behavior

```
Error: Inconsistent conditional result types

  on .terraform/modules/external_dns_iam_role.aggregated_assume_policy/main.tf line 6, in locals:
   6:     "${length(local.source_documents) > 1 ? element(local.source_documents, 1) : data.aws_iam_policy_document.empty.json}",
    |----------------
    | data.aws_iam_policy_document.empty.json is "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": null\n}"
    | local.source_documents is tuple with 1 element

The true and false result expressions must have consistent types. The given
expressions are tuple and string, respectively.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

N/A

### References

- #22405

**Comment by teamterraform** [comment]
Hi @yujunz,

Terraform is returning this error because your `local.source_documents` value is defined as being a list of lists rather than a list of single strings. You didn't share what `var.source_documents` is, but if we assume that it's empty for the sake of example then the value of `local.source_documents` would be:

```
[
  ["null"],
]
```

It looks like this configuration was originally written for Terraform 0.11 and so it's relying on some of the strange behaviors from the Terraform 0.11 language interpreter (in particular, [Referring to List Variables](https://www.terraform.io/upgrade-guides/0-12.html#referring-to-list-variables)).

Here's an updated version using Terraform 0.12 techniques:

```hcl
locals {
  policies = [
    length(var.source_documents) > 0 ? var.source_documents[0] : data.aws_iam_policy_document.empty.json,
  ]
}
```

Since the error Terraform returned in this case is correct (the conditional results were of inconsistent types), we're going to close this out now. If you have any follow-up questions, please start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
