### ISSUE TITLE
Adding lock table to s3 backend requires terraform init

### ISSUE THREAD

**Issue by gregorzupan** [hashicorp/terraform#23317]
### Terraform Version
terraform -v
```
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.template v1.0.0
```

Everything worked. Workspaces where configured ...

After adding dynamodb_table to  backend cfg

```
 backend "s3" {
    dynamodb_table = "terraform-lock"
  }
```

Need to execute init.

When executing 

```
terraform init -backend-config=stacks/stage/backend.tf
```
The following is shown:

```
Do you want to migrate all workspaces to "s3"?
  Both the existing "s3" backend and the newly configured "s3" backend
  support workspaces. When migrating between backends, Terraform will copy
  all workspaces (with the same names). THIS WILL OVERWRITE any conflicting
  states in the destination.
  
  Terraform initialization doesn't currently migrate only select workspaces.
  If you want to migrate a select number of workspaces, you must manually
  pull and push those states.
  
  If you answer "yes", Terraform will migrate all states. If you answer
  "no", Terraform will abort.
```

Is it possible to leave s3 bucket as it is and just add a locking table?
I don't want to break something.

**Comment by teamterraform** [comment]
Hi @gregorzupan,

The `terraform init` command by default treats any change to the configuration as potentially needing migration, because it can't infer the implications of the change you made. However, if you know that the change you've made does not require the state data to be copied to a new location, you can override that default behavior by using the `-reconfigure` option:

```
$ terraform init -reconfigure -backend-config=stacks/stage/backend.tf
```

If you have any follow-up questions about backend configuration changes, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
