### ISSUE TITLE
Swift state storage backend with versioning enabled restores previous state on workspace deletion

### ISSUE THREAD

**Issue by stampit** [hashicorp/terraform#23344]
I'm trying to use terraform workspaces and swift state storage backend with archive_container option. When i'm trying to delete the workspace, Swift restores its previous state.

This behaviour may be caused by using `VersionsLocation` container option instead of `HistoryLocation`.

### Terraform Version

```
$ terraform -v
Terraform v0.12.13
```

### Terraform Configuration Files

```hcl
terraform {
  backend "swift" {
    container         = "state"
    archive_container = "state-archive"
  }
}
```

### Expected Behavior
Workspace should be deleted.

### Actual Behavior
Workspace remains with previous state version

### Steps to Reproduce

1. Configure terraform to use versioned swift state storage.
2. `terraform init`
3. `terraform workspace new workspace1`
4. `terraform apply`
5. `terraform destroy`
6. `terraform workspace select default`
7.  `terraform workspace delete workspace1`
8. `terraform workspace list`

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Swift backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
