### ISSUE TITLE
When using JSON config, some fields that should be optional become required

### ISSUE THREAD

**Issue by jebotz** [hashicorp/terraform#23347]
I am using the .tf.json format because I need to do some things that HCL can't, so I'm using Jsonnet as a templating language to produce the config.  When trying to create an aws_security_group I got these errors (see below)... a 100% equivalent HCL config doesn't produce these errors.  The work-around is to add the missing "required" attributes with the appropiate null values (which I copied from "terraform show" after creating the security group manually with HCL).

### Terraform Version

```
Terraform v0.12.13
```

### Terraform Configuration Files

```json
{
    "provider": [
	{
            "aws": {
		    "region": "us-east-1",
		    "profile": "default"
	    }
	}
    ],
    "resource": [
        {
            "aws_security_group": [
                {
                    "allow_ssh": [
                        {
                            "description": "Allow Ssh inbound traffic",
                            "egress": [
                                {
                                    "cidr_blocks": [
                                        "0.0.0.0/0"
                                    ],
                                    "from_port": 0,
                                    "protocol": "-1",
                                    "to_port": 0
                                }
                            ],
                            "ingress": [
                                {
                                    "cidr_blocks": [
                                        "0.0.0.0/0",
                                        "::/0"
                                    ],
                                    "from_port": 22,
                                    "protocol": "tcp",
                                    "to_port": 22
                                }
                            ],
                            "name": "allow_ssh"
                        }
                    ]
                }
            ]
        }
    ]
}

```

### Debug Output

I'm not including this because the problem appears to be 100% reproducible.  If you can't reproduce, I'll add the debug output.
### Crash Output

No crash, see "actual behavior".
### Expected Behavior

Create a security group.
### Actual Behavior

$ terraform apply

Error: Incorrect attribute value type

  on secgroup.tf.json line 17, in resource[0].aws_security_group[0].allow_ssh[0]:
  17:                             "egress": [

Inappropriate value for attribute "egress": element 0: attributes
"description", "ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and
"self" are required.

Error: Incorrect attribute value type

  on secgroup.tf.json line 27, in resource[0].aws_security_group[0].allow_ssh[0]:
  27:                             "ingress": [

Inappropriate value for attribute "ingress": element 0: attributes
"description", "ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and
"self" are required.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

No.
### References

No references.

**Comment by teamterraform** [comment]
Hi @jebotz! Sorry for this confusing behavior.

The `ingress` and `egress` blocks are subject to [the "Attributes as Blocks" compatibility exceptions](https://www.terraform.io/docs/configuration/attr-as-blocks.html), due to the unusual behavior in this resource type of treating the absence of any blocks as a request to ignore existing security rules, rather than a request to have _zero_ security rules.

In particular, note the final section on that page "In JSON syntax", which describes that due to the fact that the JSON variant of the language doesn't include any physical difference between attributes and blocks, the decoder must choose one or the other and it chooses to interpret these as attributes so that an empty array value is interpreted as an explicit value, rather than just as [the absence of any blocks](https://www.terraform.io/docs/configuration/syntax-json.html#nested-block-mapping):

```json
{
  "ingress": []
}
```

Unfortunately that does indeed mean that for now you'll be required to write out all of the attributes of these objects, because the checking of the expression value is done using [object value type checking rules](https://www.terraform.io/docs/configuration/types.html#object-) rather than block validation, and value type checking has no concept of "optional".

Over time we are expecting Terraform providers to migrate away from using this special case in order to avoid these rough edges, but since that would be a breaking change for existing configurations this sort of change can only happen in a major release, which the provider teams try to minimize by gathering together related sets of breaking changes to make together.

With that said, the fix for this problem would be for the AWS provider to move away from marking these blocks as being handled in the special "attributes as blocks" mode, which is a change to be made in the AWS provider codebase rather than in the Terraform codebase. For that reason, we're going to close this issue to indicate that the problem will not be addressed by any changes in _this_ repository. The AWS provider team is aware of the inconsistent behavior on these blocks because they specifically turned on this special behavior (for this and a few other situations) as part of introducing Terraform v0.12 support, as a backward-compatibility allowance.

Thanks for reporting this, and sorry there isn't a better answer right now.
