### ISSUE TITLE
AWS api-gw and Lambda Intergration error

### ISSUE THREAD

**Issue by stefysarah** [hashicorp/terraform#23353]
Hi ,

We have terraform code for api-gw and lambda creation, but on trying to execute its failing at integration of both with the following error.

Error: Error creating API Gateway Integration Response: NotFoundException: Invalid Integration identifier specified
status code: 404, request id: f5daa110-94e9-4d35-934b-6d35561cfa57

on ../../../deploy-resource-module/api/main.tf line 77, in resource "aws_api_gateway_integration_response" "MyDemoIntegrationResponse":
77: resource "aws_api_gateway_integration_response" "MyDemoIntegrationResponse" {

Any solution or clue why this is failing.
Tried on terraform Versios- 11.3, 12.3, 12.13

**Comment by radeksimko** [comment]
Hi @stefysarah 
Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
