### ISSUE TITLE
Terraform generates log files in /tmp when piping from `terraform version`

### ISSUE THREAD

**Issue by nocode99** [hashicorp/terraform#23363]
### Terraform Version
```
Linux Mint 19.2
0.12.9
```

### Debug Output
If I run `terraform version`, no log file is generated in `/tmp`. If I run something like `terraform version | head -n1 | awk '{print $2}'`, a log file is created and this is a sample of what is generated:

```
2019/11/13 17:34:26 [INFO] Terraform version: 0.12.9  
2019/11/13 17:34:26 [INFO] Go runtime version: go1.12.9
2019/11/13 17:34:26 [INFO] CLI args: []string{"/home/user/.asdf/installs/terraform/0.12.9/bin/terraform", "--version"}
2019/11/13 17:34:26 [DEBUG] Attempting to open CLI config file: /home/user/.terraformrc
2019/11/13 17:34:26 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/11/13 17:34:26 [INFO] CLI command args: []string{"version", "--version"}
2019/11/13 17:34:26 [DEBUG] checking for provider in "."
2019/11/13 17:34:26 [DEBUG] checking for provider in "/home/user/.asdf/installs/terraform/0.12.9/bin"
2019/11/13 17:34:26 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
```

### Steps to Reproduce
If I run `terraform version`, no log file is generated in `/tmp`. If I run something like `terraform version | head -n1 | awk '{print $2}'`, a log file is created and this is a sample of what is generated:

### Additional Context
I run a custom ZSH script to find what version of terraform I'm running whether there's an env file or not.  If no env file is detected, then I run `terraform version | head -n1 | awk '{print $2}'`

The whole thing slows down my zsh prompt since the log file is being written to each time

**Comment by danieldreier** [comment]
@nocode99 I've tried to reproduce this issue and have not been successful. I brought up a Linux Mint 19 system using the [axjb/mint-19.0](https://app.vagrantup.com/ajxb/boxes/mint-19.0) vagrant image, and downloaded [terraform 0.12.16](https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip).

```bash
root@vagrant:~# ./terraform version | head -n1 | awk '{print $2}'
v0.12.16
root@vagrant:~# ls -lah /tmp/
total 56K
drwxrwxrwt 13 root    root    4.0K Nov 19 17:39 .
drwxr-xr-x 24 root    root    4.0K Nov 19 17:36 ..
-rw-------  1 vagrant vagrant    0 Nov 19 17:36 config-err-FuNByl
drwxrwxrwt  2 root    root    4.0K Nov 19 17:36 .font-unix
drwxrwxrwt  2 root    root    4.0K Nov 19 17:36 .ICE-unix
drwxrwxrwx  2 vagrant vagrant 4.0K Nov 19 17:37 mintUpdate
drwx------  2 vagrant vagrant 4.0K Nov 19 17:36 ssh-nPnFwhoD7OgZ
drwx------  3 root    root    4.0K Nov 19 17:36 systemd-private-4e89c63efc714ed5acd8b99430fc6cba-colord.service-dstUqp
drwx------  3 root    root    4.0K Nov 19 17:36 systemd-private-4e89c63efc714ed5acd8b99430fc6cba-rtkit-daemon.service-HmDgK1
drwx------  3 root    root    4.0K Nov 19 17:36 systemd-private-4e89c63efc714ed5acd8b99430fc6cba-systemd-resolved.service-QEHdFc
drwx------  3 root    root    4.0K Nov 19 17:36 systemd-private-4e89c63efc714ed5acd8b99430fc6cba-systemd-timesyncd.service-Q4MUO0
drwxrwxrwt  2 root    root    4.0K Nov 19 17:36 .Test-unix
-r--r--r--  1 root    root      11 Nov 19 17:36 .X0-lock
drwxrwxrwt  2 root    root    4.0K Nov 19 17:36 .X11-unix
drwxrwxrwt  2 root    root    4.0K Nov 19 17:36 .XIM-unix
```

For completeness, I also tried to reproduce this in zsh on the mint virtualbox machine, tried using terraform 0.12.9  on the mint virtualbox machine on both zsh and bash, and also tried to reproduce it in zsh on OS X with 0.12.16. 

I was only able to get logs to be created on disk following the instructions in the [terraform debugging docs](https://www.terraform.io/docs/internals/debugging.html) when I set both TF_LOG_PATH and TF_LOG.

I wonder if something in your environment is setting TF_LOG_PATH and TF_LOG? If you're able to reproduce this without setting TF_LOG_PATH and TF_LOG I am very interested in the reproduction steps, but I don't know how to investigate further otherwise.

**Comment by nocode99** [comment]
@danieldreier thanks for taking the time to look into this! I also just tried `0.12.6` and the issue is no longer there.  I didn't have any of those env variables set so I'll deem this a bug in an earlier version.  Thanks again!
