### ISSUE TITLE
Inconsistent conditional result types : The given expressions are object and object, respectively.

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/terraform#23364]
### Terraform Version

```
› terraform -v
Terraform v0.12.14
+ provider.aws v2.27.0
+ provider.external v1.2.0

```

### Terraform Configuration Files

```hcl
ipmatch           = merge(var.IPMatch, length(lookup(local.config_files, "ipmatch")) == 0 ? {}
                                                                                            : lookup(local.config_files, "ipmatch")[0])
```

The above code operates on the following data structure

```hcl
{
  "ipmatch" = [
    {
      "BlockLocal" = {
        "ipset" = [
          {
            "cidr_block" = "10.0.0.0/16"
            "type" = "IPV4"
          },
        ]
        "regional" = true
      }
      "BlockLocal2" = {
        "ipset" = [
          {
            "cidr_block" = "10.0.0.0/8"
            "type" = "IPV4"
          },
        ]
        "regional" = true
      }
      "BlockLocal3" = {
        "ipset" = [
          {
            "cidr_block" = "10.0.0.0/16"
            "type" = "IPV4"
          },
        ]
      }
    },
  ]
}
```

And results in the error

```
Error: Inconsistent conditional result types

  on ../variables.tf line 20, in locals:
  20:   ipmatch           = merge(var.IPMatch, length(lookup(local.config_files, "ipmatch")) == 0 ? {}
  21:                                                                                             : lookup(local.config_files, "ipmatch")[0])
    |----------------
    | local.config_files is object with 7 attributes

The true and false result expressions must have consistent types. The given
expressions are object and object, respectively.
```

This appears to be due to the fact that the fields of each map are not the same (two have regional key while the last one doesn't). 

Not sure what that matters with respect to the error message give as the true and false are both objects.

The code above is a bit hacky because local.config_files (which is the result of parsing a set of YAML files) could return an empty array for ipmatch. In which case I want to merge an empty map with var.IPMatch. 

Originally I had just done this

```
ipmatch = merge(var.IPMatch, lookup(local.config_files, "ipmatch")[0])
```

But that fails when ipmatch is an empty list.

**Comment by teamterraform** [comment]
Hi @cyrus-mc! Thanks for reporting this.

The error message here is technically correct, because indeed the two result expressions of the conditional are producing different object types. Terraform requires them to be the same so that it can predict the result type of the overall conditional expression during type checking.

However, this error message is clearly not sufficient to explain the problem: it's just showing the "friendly name" for each of the types, which is unhelpful for object types because for those it's necessary to analyze the differences between the types and produce a more specific error message. To improve this message, we should try to rewrite it so that it can include the result of [`convert.MismatchMessage`](https://pkg.go.dev/github.com/zclconf/go-cty@v1.1.0/cty/convert?tab=doc#MismatchMessage), which will produce a more detailed analysis of what attributes are mismatching between the two object types.

---

One way to avoid the error here could be to formulate this so that the second argument is omitted entirely in the case where the overriding "ipmatch" object isn't provided:

```hcl
  ipmatch = merge(var.IPMatch, [lookup(local.config_files, "ipmatch", [])]...)
```

The `...` symbol after the final argument here causes Terraform to flatten the resulting list into the argument sequence, so the call to `merge` will have only one argument if `ipmatch` isn't set, which then makes it effectively a no-op. If `ipmatch` is set and has one or more items, then they'd then appear as additional arguments to `merge`.

**Comment by jbardin** [comment]
I've confirmed that the types in the conditional presented here are now unified correctly in the latest releases.

Thanks!

**Comment by thor** [comment]
Should this be closed, @jbardin? The error message does not show any more explicit type information.

**Comment by jbardin** [comment]
Hi @thor, I'm not certain what you mean. The I understood the original issue as the type being unify-able, but still producing an error. In the latest release the example now works as expected with no error, due to general improvements in the conversion and unification process upstream in the go-cty package.

**Comment by lawliet89** [comment]
Hi @jbardin is this working in 0.14.8 or in a newer release?

I am encountering something similar to this:

```hcl
  consul_ui_annotations = merge(
    var.consul_ui_service_type == "LoadBalancer" ? {
      "cloud.google.com/load-balancer-type" = "Internal"
    } : {},
    var.consul_ui_annotations,
  )
```

```
Error: Inconsistent conditional result types

  on consul.tf line 21, in locals:
  21:     var.consul_ui_service_type == "LoadBalancer" ? {
  22:       loadBalancerIP           = var.consul_ui_lb_ip_address
  23:       loadBalancerSourceRanges = var.allowed_internal_ip_ranges
  24:     } : {},
    |----------------
    | var.allowed_internal_ip_ranges is list of string with 3 elements
    | var.consul_ui_lb_ip_address is "10.1.5.8"
    | var.consul_ui_service_type is "LoadBalancer"

The true and false result expressions must have consistent types. The given
expressions are object and object, respectively.
```

The types should really be `map(string)` and not `object`. But there's no way to specify this in `locals`.
