### ISSUE TITLE
Terraform v0.12.16: Failed to write state

### ISSUE THREAD

**Issue by lcgkm** [hashicorp/terraform#23412]
### Terraform Version

```
Terraform v0.12.16
+ provider.template v2.1.2
+ provider.vault v2.6.0
```

### Terraform Configuration Files

```hcl
terraform {
  backend "consul" {
    address = "xxxxxx:443"
    scheme  = "https"
    path    = "vault-config/terraform"
    gzip    = true
    lock    = true
  }
}
```

### Expected Behavior

No error.

### Actual Behavior

Get following error message:
```
Error: Failed to write state: invalid character 'R' looking for beginning of value
Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

**Comment by teamterraform** [comment]
Hello, to better understand this issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by lcgkm** [comment]
Hi @teamterraform ,
We use terraform to configure our Vault. So there is some sensitive data in the log.
Could you provide some secure solution to us? Like SFTP.
And then we can upload log files to a secure location.

**Comment by lcgkm** [comment]
Hi @teamterraform ,
Looks like it's Vault provider issue. Thank you for your help!

**Comment by lcgkm** [comment]
I can NOT remove instance from state too.
Could you tell how to force remove the instance from state? I don't want to use 'vault_generic_secret' anymore.

```
$ terraform state rm vault_generic_secret.creds[370]
Removed vault_generic_secret.creds[370]
Error saving the state: invalid character 'R' looking for beginning of value

The state was not saved. No items were removed from the persisted
state. No backup was created since no modification occurred. Please
resolve the issue above and try again.
```

**Comment by teamterraform** [comment]
Hi @lcgkm,

In all of these cases it seems like the remote system is responding with a non-JSON response where Terraform (or the Vault provider) is expecting JSON. The fact that this is happening for both Consul and Vault together is confusing, though. Is there any intermediate proxy in your environment that could be interfering with the connection between Terraform and these remote APIs (the HTTP APIs of Consul and Vault) and causing the response to be something other than JSON?

This doesn't seem to be a bug in Terraform itself, since you're seeing similar symptoms across two entirely separate Terraform subsystems: one is the Consul backend using Consul's Go SDK, and the other is the Vault provider using Vault's Go SDK. Our best guess would be either that there's some intermediate proxy interfering as described above, or that the API URLs you've configured in the Consul backend and the Vault provider are incorrect.

**Comment by lcgkm** [comment]
>Is there any intermediate proxy in your environment
NO. There is no proxy in my environment.

I have delete the 'vault_generic_secret' resource from my terraform configuration file. 
And it worked well after apply the new configuration. 
So, let me close this ticket. Thank you very much for your help!
