### ISSUE TITLE
Signed SSH keys aren't used for connection

### ISSUE THREAD

**Issue by okgolove** [hashicorp/terraform#23441]
### Terraform Version

Doesn't depend on the version
```
Terraform v0.11.14
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
resource "null_resource" "brokers_list" {

  connection {
    host = "x.x.x.x"
    user = "developer"
  }

  provisioner "remote-exec" {
    inline = [
      "touch /tmp/123",
    ]
  }
}
```

### Debug Output

https://hastebin.com/tizuguxaga.pl

### Expected Behavior

Terraform auth successfully.
### Actual Behavior

```
        * null_resource.brokers_list: interrupted - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no sup
ported methods remain
```

### Steps to Reproduce

1. Sign your pub key using Vault and save it to `~/.ssh/id_rsa-cert.pub`
2. `terraform init`
3. `teraform apply`
### Additional Context

In case of Terraform uses ssh-agent for keys it should also respect *-cert.pub keys (signed SSH keys)
https://github.com/openssh/openssh-portable/blob/d637c4aee6f9b5280c13c020d7653444ac1fcaa5/authfile.c#L359

May be it can be added as separated option in `connection` block.

### References

- #16178 
- #16972

**Comment by jbardin** [comment]
Hi @okgolove,

I think what you're looking for is the [certificate](https://www.terraform.io/docs/provisioners/connection.html#certificate) argument for an ssh connection. If I'm not mistaken, the ssh client should also be able to use certificates stored in an agent as well. 

I don't think functionality however is available in 0.11, and since we're no longer developing that version, it's not a feature that can be added. If there is support missing for certificate features in 0.12, feel free to open new issues to address those specifically. 

Thanks!

**Comment by okgolove** [comment]
@jbardin yes, that was about certificate.
But the problem is you can't use certificate + ssh-agent and in case of you use ssh-agent terraform doesn't use *-cert.pub (signed key).
I've just tried certificate + private_key options and it works properly. But what about ssh-agent?

**Comment by jbardin** [comment]
@okgolove, the ssh connection in the provisioner loads all signers from the agent. Certificates loaded there should work as expected. If you have a case that doesn't work with 0.12, please file a new issue showing the steps to reproduce. Thanks!
