### ISSUE TITLE
Crash when setting parallelism less than 0

### ISSUE THREAD

**Issue by pcarles** [hashicorp/terraform#23470]
### Terraform Version

```
Terraform v0.12.13
```

### Crash Output

https://gist.github.com/pcarles/2ed6a3a09978ea3db52685de53076935

### Expected Behavior

Terraform should have returned a proper error like:
Cannot put negative parallelism value

### Actual Behavior

Terraform crashed :(

### Steps to Reproduce

Take any configuration and then:
`terraform init`
`terraform plan -parallelism=-1` or
`terraform refresh -parallelism=-1` or any Terraform command that can take a `-parallelism` option

**Comment by pkolyvas** [comment]
Hi @pcarles! Thanks for reporting this. Would you be willing to describe the use case or workflow where this impacts your use of Terraform because it's not clear to us when a workflow would call for negative parallelism. We'd love to understand the use case.

That said, this would be a clear improvement and we would be willing to accept a PR to improve error handling as you proposed.

**Comment by pcarles** [comment]
This is not impacting my workflow! I just mistyped (I wanted to put `-parallelism=1`) and I discovered that it crash when there is a negative parallelism.

I don't think crashing is a good behavior for this, we should throw a proper error.

**Comment by danieldreier** [comment]
Thanks @pcarles! I agree that this isn't a great way to handle this error. For the time being, this isn't going to be a top-priority bug but a PR is welcome if you're interested in contributing better error handling.

**Comment by pcarles** [comment]
I created #23902

**Comment by apparentlymart** [comment]
It looks like #23902 has been merged to fix this, so I'm going to close this issue too. Thanks @pcarles!
