### ISSUE TITLE
Enhancement: AWS Tags Not Preserved

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#2348]
Hi all

When a box is provisioned in my environment, we have ansible tag that box. When i run terraform in the environment, the extra tags added by ansible are then removed:

```
~ aws_instance.nat
    tags.#:               "4" => "3"
    tags.sensu_monitored: "True" => ""
```

Is there anyway, that we can mark a tag as to not be managed by terraform?

**Comment by josh-padnick** [comment]
I have a similar use case similar to the one shared by @stack72.  We're implementing a High-Availability NAT instance, mostly as outlined at http://blog.bwhaley.com/ha-nat. 

The main benefit here is that the NAT instances can now live in an Auto Scaling Group and recover themselves automatically.  It works by building a custom AMI (using Packer!) for the NAT.  When that AMI is launched, it runs a script which sets up the NAT functionality, discovers its own EC2 instance ID and then calls the AWS API to update a VPC route table to point all `0.0.0.0/0` traffic to the newly launched NAT instance.

The problem is that Terraform wants to manage these same route tables (at least in our setup), and now it wants to revert them back to their initial state.

It doesn't appear there's a way to get Terraform to create / destroy these resources, but to disregard any updates.
