### ISSUE TITLE
add additional role for terraform cloud for managing modules

### ISSUE THREAD

**Issue by dave2535** [hashicorp/terraform#23491]
### Current Terraform Version
this is for terraform cloud not terraform cli

```NA
...
```

### Use-cases
a Terraform cloud user should be able to manage modules without needing to be in the role of owner

### Attempted Solutions
Set user as owner

### Proposal
Add a role to grants permissions to create and manage modules in terraform cloud so that users can be set as members in this role and not needing to be in the elevated privilege role of owner

### References
none

**Comment by apparentlymart** [comment]
Hi @dave2535! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
