### ISSUE TITLE
google-beta/google_cloud_run_service: "An argument named "env" is not expected here"

### ISSUE THREAD

**Issue by tommed** [hashicorp/terraform#23514]
Hi there; your ticketing system asked me to raise this bug in the provider-specific repo, but providers-google-beta says to raise it in this one, and has the bug tracker disabled; so hopefully this is the right place.

### Terraform Version

```
Terraform v0.12.16
+ provider.google v3.0.0-beta.1
+ provider.google-beta v3.0.0-beta.1
```

### Terraform Configuration Files

```hcl
resource "google_cloud_run_service" "ingress_endpoint_cb6" {
  name     = "ingress-endpoint-cb6"
  location = "europe-west2"
  provider = google-beta

  metadata {
    namespace = data.google_project.project.project_id
    labels = {
      env        = "staging"
      app        = "ingress"
      components = "endpoint"
      variant    = "cb6"
    }
  }

  spec {
    containers {
      image = "gcr.io/cloudrun/hello"
      env = [
        {
          name  = "GCP_PROJECT_ID"
          value = data.google_project.project.project_id
        },
        {
          name  = "PUBSUB_TOPIC_NAME"
          value = google_pubsub_topic.ingress_cb6.ingress_cb6
        }
      ]
    }
  }
}
```

### Debug Output

```
Error: Unsupported argument

  on cloudrun.tf line 19, in resource "google_cloud_run_service" "ingress_endpoint_cb6":
  19:       env = [

An argument named "env" is not expected here. Did you mean to define a block
of type "env"?
```

### Expected Behavior

I need to be able to specify the environment variables. The code and the documentation shows `env` is valid here, but it's just not working.

### Actual Behavior

See stderr response above. Separately, I have no idea how to set service account as this isn't documented?

Thanks in advance.

**Comment by jbardin** [comment]
Hi @tommed,

Sorry about the confusion, I'm not certain why this was redirected here from the provider repo. This appears to only be a problem with incorrect syntax. The `env` argument is defined as a "block", which is also suggested in the error output. Using block syntax should work as expected:

```
  env {
    name  = "GCP_PROJECT_ID"
    value = data.google_project.project.project_id
  }
```

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
