### ISSUE TITLE
ValidationError on adding the bucket for access logs

### ISSUE THREAD

**Issue by mightyYaroslav** [hashicorp/terraform#23521]
### Terraform Version

```
terraform -v
Terraform v0.12.16
```

### Terraform Configuration Files

```hcl
locals {
  access_logs_bucket_name = "${var.name}-${var.env}-access-logs"
  access_logs_bucket_prefix = var.env
}

resource "aws_s3_bucket" "this_bucket" {
  bucket = local.access_logs_bucket_name
  region = var.aws_region
  acl = "private"
  force_destroy = true

  versioning {
    enabled = true
  }

}

resource "aws_s3_bucket_policy" "this_aws_s3_bucket_policy" {
  bucket = aws_s3_bucket.this_bucket.id
  policy = data.aws_iam_policy_document.this_aws_s3_iam_policy_document.json
}

# Policy to make instance access bucket without keys

data "aws_iam_policy_document" "this_aws_s3_iam_policy_document" {
  statement {
    effect = "Allow"

    principals {
      identifiers = [
        data.aws_elb_service_account.this_aws_elb_service_account.arn]
      type = "AWS"
    }

    actions = [
      "s3:PutObject"
    ]

    resources = [
      "${aws_s3_bucket.this_bucket.arn}/${local.access_logs_bucket_prefix}/*"
    ]

  }
}

data "aws_elb_service_account" "this_aws_elb_service_account" {}

resource "aws_alb" "this_alb" {
  name = "${var.name}-alb"
  subnets = var.public_subnet_ids
  security_groups = var.security_group_ids

  access_logs {
    bucket = local.access_logs_bucket_name
    prefix = local.access_logs_bucket_prefix
    enabled = true
  }

  tags = {
    Name = "${var.name}-alb"
  }
}
```

### Expected Behavior

Terraform should create s3 bucket for access logs and then create the alb instance. If the alb has already been created, it should create s3 bucket and then update the alb configurations

### Actual Behavior

`terraform apply` returns error of `Failure configuring LB attributes: ValidationError: S3Bucket: <bucket-name> does not exist` when adding s3 bucket config

### Steps to Reproduce

1. `terraform init`
2. Comment out configs for resources `aws_s3_bucket`, `aws_s3_bucket_policy`and `aws_iam_policy_document` data
3. `terraform apply`
4. Now that the alb instance is created, return the code for resources `aws_s3_bucket`, `aws_s3_bucket_policy`and `aws_iam_policy_document` data
5. `terraform apply`

**Comment by jbardin** [comment]
Hi @mightyYaroslav,

Your `aws_alb` resource does not contain any reference to the s3 bucket being created, therefore terraform has no way to infer that the alb creation must come after the bucket creation. Referencing the bucket resource directly in the `access_logs` block will enforce the correct ordering or creation.

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
