### ISSUE TITLE
terraform version is out of date despite same version displayed

### ISSUE THREAD

**Issue by erickellerek1** [hashicorp/terraform#23534]
### Terraform Version

```
Terraform v0.12.6

Your version of Terraform is out of date! The latest version
is 0.12.16. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files
n.a

### Debug Output
n.a.

### Crash Output
n.a.

### Expected Behavior

when the version is the latest the message shall print out up to date!

### Actual Behavior

despite latest version the message prints:
```
Terraform v0.12.6

Your version of Terraform is out of date! The latest version
is 0.12.16. You can update by downloading from www.terraform.io/downloads.html
```

at the time of writing the download linke was:
https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip

### Steps to Reproduce

1. `wget https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip -O /tmp/terraform.zip`
2. `cd /tmp && unzip terraform.zip`
3. ./terraform -v

### Additional Context
n.a.

### References
n.a.

**Comment by danieldreier** [comment]
@erickellerek1 we just released 0.12.17 and I think this is resolved.

When I tested on my OS X machine and an Ubuntu vagrant environment, I found the expected behavior: running 0.12.16 tells me that an update is available to 0.12.17, and running 0.12.17 does not show an unneeded update notice. 

What I'm seeing on OS X:
```bash
❯ terraform-v0.12.16 version                                                                                                          ✔  460  09:27:11
Terraform v0.12.16

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from https://www.terraform.io/downloads.html
~
❯ terraform-v0.12.17 version                                                                                                          ✔  460  09:27:13
Terraform v0.12.17
```

What I'm seeing on Ubuntu 16.04 LTS
```
root@vagrant:~# ./terraform-0.12.16 version
Terraform v0.12.16

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from https://www.terraform.io/downloads.html
root@vagrant:~# ./terraform-0.12.17 version
Terraform v0.12.17
```

I'm pretty confident this is resolved, so I'm going to close this. If you're still seeing an unexpected upgrade notice please re-open it, show the output you're getting, let me know what linux distro and version you're running so I can reproduce it, and I'm happy to keep investigating.
