### ISSUE TITLE
Put downloaded terraform in a parent dir on linux

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#2353]
For the love of all that is holy, when I unzip terraform, have all contents in a versioned terraform directory.

**Comment by phinze** [comment]
I agree that it'd be better to have the binaries archived within a subdir. Unfortunately this would be difficult to change at this point, since there are now a lot of downstream build systems that work with the existing setup. The best I can do for now would be to add a description of the archive format to the documentation page to give users a heads up [1]. Sorry!

[1] https://github.com/hashicorp/terraform/commit/071db417fedfad2ece085b66a37a4f36078612e6

**Comment by jjshoe** [comment]
Why not add a .tar.gz?

**Comment by jjshoe** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2053992/8195409/d77bf38a-1447-11e5-8edb-8f3dbbd7d646.png)

**Comment by phinze** [comment]
@jjshoe and I ended up chatting about this on IRC. Posting here for searchability:

```
10:38 AM <phinze> basically it's a matter of priorities - we are 100% focused on improving terraform's core and feature set and stability right now
10:38 AM <phinze> and we're not prioritizing tweaks to the release pipeline
10:39 AM <phinze> zip has worked well enough for us because it's a singular archive format well supported across operating systems (including windows)
10:39 AM <phinze> adding a second format is just not worth it for us at this point for what is essentially a cosmetic benefit
10:39 AM <phinze> we'll probably revisit the release pipeline when we get closer to 1.0
```
