### ISSUE TITLE
Terraform Cloud - view raw log displays non-printable chars

### ISSUE THREAD

**Issue by raul-gherman** [hashicorp/terraform#23539]
### Terraform Version

```
v0.12.16
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

Clicking on ```View raw log``` opens raw log in default text editor or allows it to be downloaded and opened in a text editor; text editor should display raw log correctly

### Actual Behavior

Raw log contains non-printable chars
![1](https://user-images.githubusercontent.com/24805963/69957748-f48e2000-150b-11ea-8cba-81397a157112.PNG)
![2](https://user-images.githubusercontent.com/24805963/69957749-f48e2000-150b-11ea-9ab7-f9bd1d02cee0.PNG)

**Comment by pkolyvas** [comment]
Quick note for the TFC team:
- Some extra characters appearing in OSX nano/ less
- Same on Ubuntu/Linux
- Displays fine in most GUI text editors, but behaviour isn't consistent and I can confirm/repro the above issue.

**Comment by poolpog** [comment]
"me too"
When I open the raw log in gvim on ubuntu I see all the ascii control sequences for color, etc
"raw log" should not have control characters at all, imo
sed-based workaround that removes most or all control chars:

`sed 's/^[\[[^m]*m//g' run-asdfghjkl123456789-plan-log.txt | gvim -`

**Comment by apparentlymart** [comment]
Hi @raul-gherman! Thanks for reporting this and sorry for the delayed response.

In this case it seems like Terraform Cloud is just returning the raw log buffer, which includes all of the color codes that Terraform CLI printed out as parts of its run. Therefore this seems to be a feature request for Terraform Cloud to post-process that output and strip away all of the VT formatting codes as part of the "View raw log" feature, which would be a change in Terraform Cloud rather than in Terraform CLI.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
