### ISSUE TITLE
State file not backwards compatible for read operations (plan, show)

### ISSUE THREAD

**Issue by mjseid** [hashicorp/terraform#23633]
### Terraform Version

```
0.12.17
```

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {
  }
}

provider "aws" {
  region = var.region
}
```

### Debug Output

```
2019/12/10 15:42:44 [INFO] Terraform version: 0.12.16  
2019/12/10 15:42:44 [INFO] Go runtime version: go1.12.13
2019/12/10 15:42:44 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/1.0.1/versions/0.12.16/terraform", "init", "-upgrade=true", "-reconfigure", "-backend-config=bucket=xxxxxx", "-backend-config=key=xxxterraform.tfstate", "-backend-config=region=us-east-1", "-backend-config=encrypt=true", "-backend-config=dynamodb_table=xxxxxxx"}
2019/12/10 15:42:44 [DEBUG] Attempting to open CLI config file: /Users/xxxxx/.terraformrc
2019/12/10 15:42:44 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/12/10 15:42:44 [INFO] CLI command args: []string{"init", "-upgrade=true", "-reconfigure", "-backend-config=bucket=xxxxx", "-backend-config=key=xxxx/terraform.tfstate", "-backend-config=region=us-east-1", "-backend-config=encrypt=true", "-backend-config=dynamodb_table=xxxx"}
2019/12/10 15:42:44 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
Upgrading modules...

Initializing the backend...
2019/12/10 15:42:56 [TRACE] Meta.Backend: merging -backend-config=... CLI overrides into backend configuration
2019/12/10 15:42:56 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 704415183
2019/12/10 15:42:56 [TRACE] Preserving existing state lineage "59a2a078-ba66-7e4f-54c0-aadb325bd409"
2019/12/10 15:42:56 [TRACE] Preserving existing state lineage "59a2a078-ba66-7e4f-54c0-aadb325bd409"
2019/12/10 15:42:56 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
2019/12/10 15:42:56 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
2019/12/10 15:42:56 [INFO] Setting AWS metadata API timeout to 100ms
2019/12/10 15:42:57 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2019/12/10 15:42:57 [INFO] AWS Auth provider used: "EnvProvider"
2019/12/10 15:42:57 [DEBUG] Trying to get account information via sts:GetCallerIdentity

</GetCallerIdentityResponse>
2019/12/10 15:42:57 [DEBUG] checking for provider in "."
2019/12/10 15:42:57 [DEBUG] checking for provider in "/usr/local/Cellar/tfenv/1.0.1/versions/0.12.16"
2019/12/10 15:42:57 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/12/10 15:42:57 [DEBUG] found provider "terraform-provider-aws_v2.35.0_x4"
2019/12/10 15:42:57 [DEBUG] found valid plugin: "aws", "2.35.0", "/xxxxxxxxxxxxxxx/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.35.0_x4"
2019/12/10 15:42:57 [DEBUG] checking for provisioner in "."
2019/12/10 15:42:57 [DEBUG] checking for provisioner in "/usr/local/Cellar/tfenv/1.0.1/versions/0.12.16"
2019/12/10 15:42:57 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2019/12/10 15:42:57 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
2019/12/10 15:42:57 [DEBUG] [aws-sdk-go] DEBUG: Request s3/ListObjects Details:

-----------------------------------------------------
2019/12/10 15:42:59 [DEBUG] [aws-sdk-go] {"Item":{"Digest":{"S":"2131dc6bdd97c9b7824b5cbcc1358110"},"LockID":{"S":"xxxxxxxxxterraform.tfstate-md5"}}}
Error refreshing state: state snapshot was created by Terraform v0.12.17, which is newer than current v0.12.16; upgrade to Terraform v0.12.17 or greater to work with this state
```

### Expected Behavior

I expect that initializing and doing terraform plan or terraform show operations on a statefile written by a newer minor version of terraform will work.  

### Actual Behavior

The state initialization fails, and I am not able to read the outputs from a statefile created by a newer version of terraform.

When reading a TF 0.12.13 statefile from TF 0.11.14, I get an error on the command line but I am still able to do terraform show commands to successfully read outputs.   
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: 
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.12.13'

A newer version of Terraform is required to make changes to the current
workspace.

```

### Steps to Reproduce

1. create a statefile with terraform 0.12.17
2. tfenv use 0.12.16
3. terraform init
4. terraform show

**Comment by PeterBurner** [comment]
same for `terraform output`!
especially problematic with CI scripts

**Comment by chinuy** [comment]
Probably for readonly method, such as `terraform show` and `terraform output`, we should display state with a warning message like to friendly remind version problem.

**Comment by chinuy** [comment]
Looking at the source code, I think it is probably more reasonable to have an option (e.g., -k, --skip) to skip version checking.

**Comment by brandong1** [comment]
Checking in on this since the last update was over a year ago.

**Comment by apparentlymart** [comment]
For a long time now Terraform has supported reading arbitrary state snapshots without checking which Terraform version created them as long as the state format version is compatible. This means that in most cases older versions of Terraform can read state snapshots created by newer versions of Terraform.

It's important to note that this is not a promise to never make a new version of the state snapshot format that older versions would not be able to read, but rather that Terraform now relies only on the format version to decide compatibility, so forward-compatibility will only be broken when strictly necessary to implement a new feature and not just because a new Terraform CLI version was released.

In practice there has not been a new major version of the state snapshot format since we made this change, although there was an inadvertent non-forward-compatible change to one part of the format in an earlier release that was resolved in the latest patch release of all of the affected versions. If you use the latest patch release of whatever minor release you are using then you should not encounter that problem.

The official position on this subject is in the [Upgrading and Downgrading](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises#upgrading-and-downgrading) section of the Terraform v1.x Compatibility Promises, which at the time I'm writing this currently states (emphasis mine):

> Throughout the v1.x series of releases, we intend that you should be able to switch to a newer Terraform version and use it just as before, without any special upgrade steps.
>
> You should be able to upgrade from any v1.x release to any later v1.x release. You might also be able to downgrade to an earlier v1.x release, but that isn't guaranteed: **later releases may introduce new features that earlier versions cannot understand, including new storage formats for Terraform state snapshots**.
>
> If you make use of features introduced in a later v1.x release, your configuration won't be compatible with releases that predate that feature. For example, if a language feature is added in v1.3 and you start using it, your Terraform configuration will no longer be compatible with Terraform v1.2.

The informal intent behind that statement is that we cannot promise to preserve forward-compatibility with the state snapshot format forever, since the state snapshot format must occasionally change to support new Terraform features, but we intend that to be an infrequent event taken only as a last resort if we cannot find a safe design for forward-compatibility.

My sense is that this new approach is an answer to this issue, and so I'm going to close it. I'm sorry that we didn't remember to respond here when we were originally preparing the changes for the v1.x series.
