### ISSUE TITLE
Resource creation order with count

### ISSUE THREAD

**Issue by hardikshah0513** [hashicorp/terraform#23637]
Is there any way in terraform to order resource creation with count. This is what I am trying to do.

I am trying to create oracle cloud vm instance with multiple nics. this my resource code.

resource "oci_core_vnic_attachment" "pavm_dataplane_nics" {
  count      =  3
  create_vnic_details {
    subnet_id              = "${var.pavm_untrust_nic}" == count.index ? "${oci_core_subnet.untrust_subnet.id}" : "${var.pavm_trust_nic}" == count.index ? "${oci_core_subnet.trust_subnet.id}" : "${oci_core_subnet.mgmt_subnet.id}"
    private_ip             = "${var.pavm_untrust_nic}" == count.index ? "${var.pavm_untrust_ip}" : "${var.pavm_trust_nic}" == count.index ? "${var.pavm_trust_ip}" : null
    display_name           = "dataplane-nic-${count.index}"
    skip_source_dest_check = true
    assign_public_ip       = false
  } 

terraform creates resources dataplane-nic-0, dataplane-nic-1 and dataplane-nic-2 in random order each time. In oracle cloud, vnic attachment to vm instance has to be in order. I did try depends_on module with count.index interpolation which gives me an error "A single static variable reference is required: only attribute access and
indexing with constant keys. No calculations, function calls, template
expressions, etc are allowed here." 

Please provide suggestions.

Terraform v0.12.10
+ provider.null v2.1.2
+ provider.oci v3.51.0
+ provider.random v2.2.1

**Comment by gorpher** [comment]
It seems hard to achieve,resources are created in parallel, with no fixed order.

**Comment by hardikshah0513** [comment]
@gorpher,

Thank you for the quick response, is there any workaround? Is there any way to put delay or wait in count loop to order resource creation?

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
