### ISSUE TITLE
File not found error in file function when running in Terraform Cloud

### ISSUE THREAD

**Issue by NiyiOdumosu** [hashicorp/terraform#23649]
### Terraform Version

```
terraform -v
Terraform v0.12.17
```

### Terraform Configuration Files

```hcl
provider "google" {
  credentials = file("../../../service-key/service-key.json")
  project     = var.composer_project
  region      = "us-east4"
}
```

### Expected Behavior

Plan: 7 to add, 0 to change, 0 to destroy. 
### Actual Behavior

```
Error: Error in function call

  on modules/composer/main.tf line 2, in provider "google":
   2:   credentials = file("../../../service-key/service-key.json")

Call to function "file" failed: no file exists at
../../../service-key/service-key.json.
```
### Steps to Reproduce

1. `terraform plan`

### Additional Context

I went into my terraform cloud account and changed the execution mode from remote to local in my workspace. That was supposed to fix the issue according to the issue referenced below.
### References

#22898

**Comment by seanwalker5** [comment]
Hi Niyi, I have sent you an email.
-Sean

**Comment by apparentlymart** [comment]
Hi @NiyiOdumosu! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
