### ISSUE TITLE
Cannot use VCS branch that contains slashes

### ISSUE THREAD

**Issue by jscheytt** [hashicorp/terraform#23643]
### Terraform Version

```
Terraform v0.12.17
+ provider.aws v2.41.0
```

### Steps to Reproduce

1. I add Bitbucket as a VCS provider in Terraform Cloud (according to https://www.terraform.io/docs/cloud/vcs/bitbucket-cloud.html)
1. I connect a workspace to a Bitbucket repo
1. In https://app.terraform.io/app/{company}/workspaces/{workspace}/settings/version-control I set the VCS branch to a branch name that contains forward slashes (e. g. the branch name starts with "fea/").
1. I click "Update VCS settings"

### Expected Behavior
I receive a success message with the content 
```
Success
Saved version control settings
```

### Actual Behavior
I receive a warning with the content
```
Error saving version control settings
Branch isn't ingressable. Ensure your repository is not empty or in the process of being created.
```

The warning message does not appear when I enter a branch name without slashes.

**Comment by markosamuli** [comment]
I'm seeing this same error on the web UI as well as if using the `tfe_workspace` resource.

**Comment by medicce** [comment]
+1 can we get a look into this?

**Comment by pkrall520** [comment]
Any word on this?

**Comment by sir-gon** [comment]
This is an annoying behavior when I am using gitflow style branches.

Any update?

**Comment by apparentlymart** [comment]
Hi @! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
