### ISSUE TITLE
Puppet provisioner fails to install Puppet on Windows Server 2016 with TLS/SSL Error

### ISSUE THREAD

**Issue by camara-tech** [hashicorp/terraform#23693]
### Terraform Version

```
Terraform v0.12.18
+ provider.aws v2.42.0
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "instance" {
  ami               = data.aws_ami.windows-server.id
  instance_type     = var.instance_type
  key_name          = "provision_key"
  availability_zone = "us-east-1b"
  tags = {
    Name        = "example-vm"
  }
  get_password_data = true
  vpc_security_group_ids = ["sg-1111111111"]

  subnet_id = "subnet-11111111111"
  user_data = <<-DATA
    <script>
      winrm quickconfig -q & winrm set winrm/config @{MaxTimeoutms="1800000"} & winrm set winrm/config/service @{AllowUnencrypted="true"} & winrm set winrm/config/service/auth @{Basic="true"}
    </script>
    <powershell>
      Write-Host "setting up firewall"
      netsh advfirewall firewall add rule name="WinRM in" protocol=TCP dir=in profile=any localport=5985 remoteip=any localip=any action=allow
      Write-Host "restarting winrm"
      Stop-Service winrm
      Start-Service winrm
    </powershell>
  DATA

  provisioner "puppet" {
    server = "puppet.test.com"
    connection {
      host = coalesce(self.private_ip, self.public_ip)
      type = "winrm"
      user = "Administrator"
      password = rsadecrypt(self.password_data, file("~/.ssh/provision_key"))
      timeout = "10m"
    }
    open_source = false
    certname = "example.test.com"
    autosign = false
  }
}
```

### Debug Output
https://gist.github.com/camara-tech/f407b8760def43f6c9da56fc45a88efe

### Crash Output
Not Applicable

### Expected Behavior
The terraform puppet provisioner successfully downloads the puppet agent installer for windows from the puppet enterprise server and successfully installs it.

### Actual Behavior
the terraform puppet provisioner failed with the following error from powershell: 
```
The request was aborted: Could not create SSL/TLS secure channel.
```

### Steps to Reproduce
terraform init
terraform apply

### Additional Context
In our environment, we have completely disabled TLS protocols below TLS 1.2. Also, our puppet enterprise console uses the same Powershell that is present in the puppet provisioner for windows with the addition of the following line: 
```
[System.Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
```
Perhaps that needs to be added to the existing provisioner?

### References
Not Applicable

**Comment by danieldreier** [comment]
@camara-tech I'm not 100% sure if I understand the puppet provisioner correctly, but I think you're hitting an issue downloading the `install.ps1` install script from your Puppet Enterprise master. I wonder if you're hitting a CA trust issue, where the powershell command trying to download the install script doesn't trust the CA that signed your PE SSL certificate?

**Comment by camara-tech** [comment]
I don't think it is due to an untrusted CA because it appears that an untrusted certificate uses a different error. According to an article I found (https://docs.microsoft.com/en-us/archive/blogs/friis/troubleshooting-tls-ssl-scenario-3) the expected error for an untrusted CA would be `The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel`.

Another reason I don't think the problem is an untrusted CA is because I was able to get the puppet provisioner to work with the changes from #23695.

**Comment by pkolyvas** [comment]
In [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997) we announced the deprecation of tool-specific vendor provisioners. Recently, we added a deprecation notice these provisioners in `0.13.4`. 

On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins. 

I realise this issue is overdue for a response and as the product manager of Terraform, that onus is on me for having left these untouched while we developed our near-term plan. 

The long term strategy here is less clear than we'd like, but for the time being I'd encourage the community of Terraform provisioner users and developers (who might also be reading this) to follow in the footsteps of the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible).

Creating provisioner plugins and installing provisioner plugins manually is more involved. My personal hope here is that the ability to improve, fix and repair these tools without us blocking their development, much like providers, will help make a strong case for what's next. 

There are also some technical hurdles to cross.  The Terraform plugin SDK does not support provisioners and so moving beyond the deprecation will require more concrete plans. We’d like to base those plans, in part, on the feedback we receive. I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle.

We didn't make this decision lightly, and removing or no longer supporting features is not ideal for anyone who uses and depends on them. To that end, my door is always open. I'd invite anyone interested or concerned to write me or schedule some time with me to talk about these changes moving forward.
