### ISSUE TITLE
Editing community documentation to update to HCL2 syntax

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform#23706]
I'm not sure if this is the best place to raise this so let me know if this could be discussed elsewhere. I also removed the issue template as this doesn't really fit in any of the options (although maybe that's a flag that it doesn't really belong as an issue and should be somewhere else).

I noticed that https://github.com/terraform-providers/terraform-provider-aws/issues/8950 talked about updating all of the HCL1 syntax in all of the AWS provider documentation to HCL2 at a later time (although not yet defined) and wondered if we should be making the same effort elsewhere across the web.

I've just seen [this Stack Overflow answer](https://stackoverflow.com/a/59379387/2291321) that just provides the HCL2 syntax version for an existing answer without adding anything else right now. I'm of the opinion that that doesn't really add enough and we'd be better as a community working out how we want to handle all the existing answers on Stack Overflow (and other community resources) with respects to the syntax changes in HCL2.

I personally feel like we should do the same as the providers (assuming that the non AWS providers are also planning on the same thing) and try to mass update as much of the existing answers and questions as possible with HCL2 syntax where there is a straight forward way to do so (I'm largely thinking just removing the interpolation style stuff for now). If doing so would invalidate the question or answer then we might want to leave them as is and maybe consider adding a separate answer that can solve the problem in a better way with HCL2 only syntax. I know @apparentlymart has been busy answering old questions with newer and better ways of doing things since 0.12 was released so a lot of that should already be covered.

We don't really have a way to enforce that but at least myself and @apparentlymart are both pretty active on the Terraform tag on Stack Overflow so can maybe rattle through that although I'd appreciate any offers from the community to help as well.

**Comment by apparentlymart** [comment]
Hi @tomelliff! Sorry for the lack of response here. I think we got a bit stuck because this isn't a typical bug report or enhancement request and so it didn't really fit into our usual process for working through issues.

For my part I've been gradually updating answers I wrote when I see them and they seem particularly dated. However, I've been reluctant to update anything I didn't write since that seems like changing the substance of the answer and thus not within the usual spirit of community editing. If you'd like to do similar updates, I expect that would be appreciated!

In the meantime we've started to try to respond to the problem of outdated examples on the web in a different way: modern Terraform versions now generate warnings for some legacy constructs which Terraform 0.12 and later consider valid for backward compatibility, in an attempt to guide folks who refer to old examples towards the new syntax. Continuing along that road, the forthcoming Terraform 0.14 will also include some new `terraform fmt` rules to address _some_ of these cases automatically, although it only really covers simple cases because the formatter isn't currently robust enough to safely do surgical rewrites in the middle of expressions.

Because this issue doesn't really have a clear idea of when it would be "done", I'm going to close it so that it doesn't just sit here forever. I do appreciate you raising this though, and hopefully over time the most prominent examples out there will get updated to new syntax one way or another, with the warnings and automatic formatter hopefully accelerating that a little. Thanks!
