### ISSUE TITLE
`state mv` doesn't remove stale dependencies

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#23711]
### Terraform Version

```
Terraform v0.12.18
```
### Steps to Reproduce

Write a dummy provider with only one schema properties: `name`, then setup following configuration:

```hcl
resource "example_server" "foo" {
  name = "the name"
}

resource "example_server" "bar" {
  name = example_server.foo.name
}
```

Then run `terraform apply`. This will succeeds as expected.

Then run `terraform state mv example_server.foo example_server.baz`, which also succeeds. But the content in *terraform.tfstate* for `example_server.bar` is not correct.

### Expected Behavior

The `dependencies` field of `example_server.bar` is now changed into `example_server.baz`.

### Actual Behavior

Still depends on `example_server.foo`, which is now renamed to  `example_server.baz`:

```
"resources": [                     
  {                                
    "mode": "managed",             
    "type": "example_server",      
    "name": "bar",                 
    "provider": "provider.example",
    "instances": [                 
      {                            
        "schema_version": 0,       
        "attributes": {            
          "id": "id",              
          "name": "the name"       
        },                         
        "private": "bnVsbA==",     
        "dependencies": [          
          "example_server.foo"     # HERE
        ]                          
      }                            
    ]                              
  },                               

```

**Comment by jbardin** [comment]
Hi @magodo,

This is the expected behavior, because terraform does not know what sort of refactoring is going on or why. Renaming or moving a resource does not imply that the config references are also being changed to create the same dependencies. 

Since the dependencies only effect the destruction of resources, and state should normally have been refreshed at least once before destroying anything while refactoring, the state should be updated with the new references before they are needed.

Are you experiencing a problem because of the change?

**Comment by VijayRajagopalan-STW** [comment]
Hello @jbardin,

Thanks for the details. I have a similar issue where I had to rename few modules while moving them to another state file. When checked the new remote state file after the move, I can still see the dependencies point to the old resource names.

I tried "terraform refresh/plan" etc, but still unable to update the dependencies to point to the new resource names. However, I am able to destroy the resources without a glitch.

If the dependencies still point to the old resource names, will there be any impact, if any?

Is there an way to update the dependencies in my scenario?

Thanks.

**Comment by jbardin** [comment]
Hi @VijayRajagopalan-STW,

There should be no impact at the moment. The next major release is planned to use these values in a different manner, and will recalculate them accordingly. 

I do think we should clear them out however, so that stale values are less likely to be carried through an upgrade process. I'll update this issue reflect the change.
