### ISSUE TITLE
Resources created with for_each and prevent_destroy = true can't be destroyed even if targeted

### ISSUE THREAD

**Issue by iorlov1** [hashicorp/terraform#23760]
### Terraform Version

```
terraform version
Terraform v0.12.17
+ provider.azurerm v1.39.0

```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

Resources deleted
### Actual Behavior

Error: Instance cannot be destroyed
Resource
module.yyy.azurerm_virtual_machine.yyy-vms["test.vm.com"]
has lifecycle.prevent_destroy set, but the plan calls for this resource to be
destroyed. To avoid this error and continue with the plan, either disable
lifecycle.prevent_destroy or reduce the scope of the plan using the -target
flag.

even if ran with -target 'module.yyy.azurerm_virtual_machine.yyy-vms["test.vm.com"]' .
### Steps to Reproduce

create module with for_each to create VMs and prevent_destroy = true
create 2 VMs using that module
remove VM
then apply with -target should destroy it, but it does not happen

**Comment by apparentlymart** [comment]
Hi @iorlov1! Thanks for opening this bug report.

Based on what you described here, it seems like Terraform is working as designed: you have set `prevent_destroy` on `azurerm_virtual_machine.yyy-vms` and therefore, as requested, Terraform is preventing you from destroying it.

I assume you tried `-target` here because the error message mentioned it. This error message is intending to direct you to use `-target` to _exclude_ this resource, by targeting something else that doesn't depend on it. I can't give you a real example because you didn't share any configuration, but in order to successfully destroy you'd need to identify some other resource that doesn't depend on `module.yyy.azurerm_virtual_machine.yyy-vms` and target _that_, which would then destroy the resource you selected but leave `module.yyy.azurerm_virtual_machine.yyy-vms` undestroyed.

If you _are_ intending to destroy `module.yyy.azurerm_virtual_machine.yyy-vms["test.vm.com"]` then you will need to remove the `prevent_destroy` setting from it, to tell Terraform that you no longer wish it to prevent you from destroying it.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
