### ISSUE TITLE
need terraform documentation for mcs service for Cassandra

### ISSUE THREAD

**Issue by ansha1** [hashicorp/terraform#23771]
### Current Terraform Version

```
...
```

**Comment by bflad** [comment]
Hi @ansha1 👋 Thank you for submitting this.

For bug reports or feature requests with specific Terraform Providers, such as the Terraform AWS Provider in this case, the recommendation is to create GitHub issues in their respective repository.

The short answer here is that AWS does not currently provide a public API for the MCS service. Terraform resources (with their associated documentation), cannot be created until that is released. Additional information can be found in this Terraform AWS Provider issue and comment: https://github.com/terraform-providers/terraform-provider-aws/issues/11221

Since this feature request does not relate to Terraform CLI functionality shared across all providers and there is already a downstream tracking issue, I'm going to close this. 👍
