### ISSUE TITLE
With Terraform cloud can I have Terraform state that behaves more like cloudformation stacks?

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform#23807]
I like terraform better than cloudformation for almost every reason, but there is one thing I cant do with terraform- delete a state "object" and have all its resources get cleaned up for me

I can delete a CF stack and it cleans everything up for me. That's one command that points to a single object with no dependency on the CF template that generated that object 

With terraform I have to have the terraform config that generated the state and then terraform needs to run that config against the state before it destroys it. This means I can't easily have some external process cleanup my "stacks" for me without having the exact config that generated the state. Trying to use this to deploy _applications_ in a dynamic way is not really possible (without doing the AWFUL hacky things I see some people doing like manually modifying/crawling state files to try and cleanup stuff and destroy)

With terraform cloud it looks like state is a lot more interactive? Like a cloudformation stack. And terraform cloud supports remotely running terraform for you right?

Will I ever be able to just delete a state object in Terraform Cloud and have terraform destroy all the resources in the state for me? I'd like to know if there is some obvious reason why this would never be possible. If terraform cloud can run terraform remotely and it has the state how hard would it be for it to just read the state and destroy all the resources?

**Comment by apparentlymart** [comment]
Hi @red8888,

While the primary workflow of Terraform (including Terraform Cloud) is to keep your configuration under version control and have that version control be the source of record for your configuration, Terraform Cloud _does_ retain a copy of the configurations it has been asked to apply which it can then use when you ask it to run Terraform -- either through the UI or through the API -- without providing a new configuration.

In principle that means you could use Terraform Cloud as the source of record for the latest configuration and have it destroy based on that. It's not the primary workflow intended for the product -- the primary use-case is having your separate version control system be the source of record -- but the technical building blocks are there to do something like what you described.

[The "Apply a Run" operation](https://www.terraform.io/docs/cloud/api/run.html#apply-a-run) operation lets you run Terraform against the latest configuration known to Terraform Cloud (by omitting the explicit configuration version id). You can set `is-destroy` to instruct Terraform Cloud to run `terraform destroy` instead of `terraform apply`.

In order for this to succeed, you must have the remote execution environment configured with suitable credentials to perform the destroy operations. This is likely already true if you have remote operations or VCS workflow enabled on the workspace, but would not be true if you are otherwise running Terraform only locally, outside of Terraform Cloud, and using Terraform Cloud just to store state.

Since this capability is already there, I'm going to close this out. If you have further questions about it, please feel free to start a topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core) where we can potentially get into a deeper discussion about the details. Thanks!
