### ISSUE TITLE
Manage vsphere existing resources through teraform?

### ISSUE THREAD

**Issue by ttrchavis** [hashicorp/terraform#23800]
Hello, Terraform cannot manage the existing resources of vSphere,
The terraform show command cannot be used to obtain existing resources.
Can you help me out?

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
