### ISSUE TITLE
Variable inside a variable

### ISSUE THREAD

**Issue by eladazary** [hashicorp/terraform#23803]
I would like to use a variable inside a variable.

This is my resource:
resource "aws_route" "vpc_peering_accepter" {
  provider                  = "aws.accepter"
  count                     = length(data.terraform_remote_state.vpc.outputs.**${var.region}**-vpc-private_routing_tables)
  route_table_id            = tolist(data.terraform_remote_state.vpc.outputs.**${var.region}**-vpc-private_routing_tables)[count.index]
  destination_cidr_block    = var.vpc_cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.peer.*.id[0]
}

Of course this one is not working.
What's the best practice to do it?

Thanks,
Elad

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
