### ISSUE TITLE
Terraform SDK auto change value of null to 0

### ISSUE THREAD

**Issue by jotruon** [hashicorp/terraform#23813]
### Terraform Version

```
0.11.14
```

### Terraform Configuration Files

```hcl
			// Optional
			"connection_configuration": {
				Type:     schema.TypeList,
				Optional: true,
				Computed: true,
				MaxItems: 1,
				MinItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						// Required
						"idle_timeout_in_seconds": {
							Type:             schema.TypeString,
							Required:         true,
							ValidateFunc:     validateInt64TypeString,
							DiffSuppressFunc: int64StringDiffSuppressFunction,
						},

						// Optional
						"backend_tcp_proxy_protocol_version": {
							Type:     schema.TypeInt,
							Optional: true,
						},

						// Computed
					},
				},
			},
```

### Debug Output

2020/01/07 13:52:17 [WARN] Provider "oci" produced an unexpected new value for oci_load_balancer_listener.test_listener, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .connection_configuration[0].backend_tcp_proxy_protocol_version: was null, but now cty.NumberIntVal(0)
### Expected Behavior

Keep the value as null
### Actual Behavior

Value auto change to 0
### References

https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/load_balancer_listener_resource.go#L55

**Comment by jbardin** [comment]
Hi @jotruon,

It appears you're using Terraform v0.12, rather than 0.11.14, which can't produce the error you're seeing. 
You also should be using `github.com/hashicorp/terraform-plugin-sdk`, not `https://github.com/hashicorp/terraform/` and issues can be filed directly against the SDK in https://github.com/hashicorp/terraform-plugin-sdk.

Not all warnings can be avoided when using the legacy SDK, so it's possible that this situation is unavoidable. Before Terraform v0.12 there was no "null" value, so often times the SDK will have to fill in the zero value of a type.

If you're certain that the resource is never setting that field, and the existence of the zero value is causing an issue, please file a new issue with the plugin sdk.

Thanks!
