### ISSUE TITLE
Computed fields of TypeList show perma diff

### ISSUE THREAD

**Issue by chrisst** [hashicorp/terraform#23814]
Lists that are computed but not set in the config and set to `null` in state are showing up as a diff when running `plan`.

### Terraform Version

Latest in master as of today
```
Terraform version: 0.12.19 dev
```

### Terraform Configuration Files

```hcl
resource "google_monitoring_alert_policy" "http_500_per_hour_policy" {
  display_name = "Sum of http 500 responses in last hour < 100"
  enabled      = true
  combiner     = "OR"
  conditions {
    display_name = "GAE Application - Response count for 500 [SUM] is above 100 per last hour"
    condition_threshold {
      filter          = "metric.type=\"appengine.googleapis.com/http/server/response_count\" resource.type=\"gae_app\" metric.label.\"response_code\"=\"500\""
      comparison      = "COMPARISON_GT"
      duration        = "60s"
      threshold_value = 100
      trigger {
        count = 1
      }
      aggregations {
        alignment_period     = "3600s"
        per_series_aligner   = "ALIGN_SUM"
        cross_series_reducer = "REDUCE_SUM"
      }
    }
  }
}


```

### Debug Output

https://gist.github.com/chrisst/3901854e965b2ef690b9e3d4becbf153

### Expected Behavior
Computed attributes should not trigger a diff. Optional/Computed should not produce a diff if they are not specified in the config. 

### Actual Behavior
The attribute shows a diff and requiring an update:
```
 + labels                = (known after apply)
```

### Steps to Reproduce
1. Create the resource (`terraform apply`)
2. Run `terraform plan` and see the diff for the computed field.

### Additional Context
I compared this behavior with a computed TypeString and did not see a diff for the field. This particular field is Removed and Optional but it appears that those attributes are irrelevant.

**Comment by jbardin** [comment]
Hi @chrisst,

From your description it sounds like the diff is working as expected here. If the field is marked as `computed`, then terraform is going to expect a value to be computed when it's not supplied via the configuration. Terraform itself has no concept of "removed", it is just relaying what is returned by the resource plan.  I think the the confusion here is around the fact that the legacy SDK cannot differentiate between unset and empty strings, while it will attempt to infer the difference in some cases for lists. 

The provider either needs to fill in the field that it declared would be computed, or it needs to remove the `Computed` flag so that terraform is not expecting a value. The latter would be the optimal path, as it makes little sense to signal that an unused field is going to computed. This would also be consistent that an optional removed field should never return a value to prevent creating a diff against the a configuration without the field. 

See related: https://github.com/hashicorp/terraform-plugin-sdk/issues/285

**Comment by chrisst** [comment]
@jbardin I mostly thought this was a bug because this behavior is different for Lists than it is for less complex types like String. A computed typeString does not need a value explicitly set in the provider whereas the typeList does. Additionally when a List is both Optional and Computed I wouldn't expect a `null` in state to present a diff as optional fields should be fine with a null value. Is this still an issue with the sdk given that I would expect either a unset or null field to have the same behavior? 

I also want to reiterate that I didn't meant to focus this issues on the fact that this field is "Removed", it's just coincidental that this particular field is and the behavior is still problematic when the field isn't null.

**Comment by jbardin** [comment]
The differences you're seeing are mostly an artifact of the legacy SDK. Core treats the string and list in the exact same manner, but what is coming back from the provider is different in each case, as it has to pass through flatmap state representation. The shims that convert between the two representations often have to guess what is intended, which will always have problems because the legacy SDK cannot handle the complete type system. The SDK has to return an empty string for a string, as there is no `null`, while the list in some cases can be inferred to be null, and some cases it cant.

**Comment by chrisst** [comment]
I see, so this is best refiled as an SDK bug at this point then? As a clarification, if the SDK was able to correctly differentiate null vs empty vs absent, would I be correct in assuming a optional+computed field should not produce a diff if absent in the config?

**Comment by jbardin** [comment]
If the SDK was able to follow the spec precisely, then any missing optional+computed field would always produce a diff by default, because being computed tells terraform that it should expect a new value after apply.

While not exactly the same question, I think the linked SDK issue sufficiently covers this, and we can decide how a new SDK will handle the situation in the future.

**Comment by chrisst** [comment]
Got it, I'll move behavior discussion to that issue. In the short term it would be good to add something to https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-removal as right now point #5 is recommending something that isn't correct for all attributes.
