### ISSUE TITLE
walking dag in forward and reverse in sorted order

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/terraform#23835]
i'm try to use terraform/dag package in my project and have a question:
why DepthFirstWalk and ReverseDepthFirstWalk calls walrkfunc not in sorted position based on index?
I need to compound pipeline execution from dag, but now i need to first walk, fill slice and sort it.

**Comment by jbardin** [comment]
Hi @vtolstov,

The dag itself has no indexes, because the internal data structures are based on sets. The walks currently sort the vertices so the order is consistent, that is only based upon what can be derived for a vertex name. The walk order however is not guaranteed (nor is any of the API, since this isn't meant to be a separate library), and may not be ordered at all in the near future. Any upcoming changes are targeting specific improvements for Terraform's use case, and may not generalize well.

**Comment by vtolstov** [comment]
Why it not sorted? If vertex in gad have deps on other vertex (have connection) order is determined. I don't need to have always static position for specific vertex, but i need to have guarantee about satisfying dependencies. And as i understand terraform can't break this (if this happened - this is really bug and needs to be fixed), because some resources can be running before dependencies are satisfied.

**Comment by jbardin** [comment]
The iteration order of nodes and edges from sets does not not break the ordering requirements of the edges themselves; it only means the overall ordering that independent vertices are visited may not be deterministic. Any ordering requirements must be specified via edges, and cannot be enforced otherwise. 

The short-term fix for some of the efficiency problems in this package is likely to start with the removal of all the excess sorting.

**Comment by vtolstov** [comment]
So for my case, i'm already use edges to specify connection between vertices. So what you think if i'm provide pr to remove sorting based on vertex names? Does this will be breaking change? Does it can be accepted?

**Comment by jbardin** [comment]
I believe I may have misunderstood your original post, as it seemed to imply that you wanted to walk based on a consistent index value. In general, any PRs not specifically targeted for the benefit of Terraform core itself are not likely to be accepted, as the dag package is not going to transform into generic library. The sorting overhead however (and extra allocations in general) is a concern for us; and the sorting in the primary codepaths will likely be removed with #23811

**Comment by vtolstov** [comment]
May be my issue text is not correct on start. Sorry.
I need to have ability to walk correctly between vertices, (based on edges) nothing more.
So if some vertex is present before another (because previous vertex have edges to both of them) this is not problem for me. May i'm ask when the related pr will be merged? Results are excited and for starting more improvements is very cool
