### ISSUE TITLE
etcdv2 backend with Terraform behind proxy

### ISSUE THREAD

**Issue by AnthonyWC** [hashicorp/terraform#23837]
Does anyone know if it's possible to use etcd backend behind a (SOCK5) proxy?

Setup:
I had setup a dynamic port forwarding via SOCK5 via `ssh -D` option.  I was able to test successfully via curl to the proxy ssh server.  I had set env. variables, e.go.
```
HTTP_PROXY=http://127.0.0.1:8000
HTTPS_PROXY=http://127.0.0.1:8000
http_proxy=http://127.0.0.1:8000
https_proxy=http://127.0.0.1:8000
```

Searching related topics such as https://github.com/hashicorp/terraform/issues/8367 and https://github.com/hashicorp/terraform/issues/17386, and looking through the etcd backend code, I don't see mention of a proxy setting.  So I wonder if it's possible to access an etcd backend in Terraform behind a proxy.

I also checked wireshark and it doesn't look like terraform uses the http proxy environment variable to send any traffic. 

### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
 terraform {
   backend "etcd" {
     endpoints = "https://XXX"
   }
 }
```

### Debug Output
```
Initializing the backend...
2020/01/11 14:31:27 [INFO] command: backend initialized: *legacy.Backend
2020/01/11 14:31:27 [DEBUG] checking for provider in "."
2020/01/11 14:31:27 [DEBUG] checking for provisioner in "."
2020/01/11 14:31:27 [INFO] Failed to read plugin lock file 
2020/01/11 14:31:27 [INFO] command: backend *legacy.Backend is not enhanced, wrapping in local
2020/01/11 14:31:27 [DEBUG] plugin: waiting for all plugin processes to complete...
Error refreshing state: client: etcd cluster is unavailable or misconfigured
```

### Expected Behavior
Sent traffic via ssh tunnel to communicate /w etcd backend

### Actual Behavior
No traffic is sent.

### References #
 - #8367 
 - #17386

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the etcd backends in Terraform v1.3 because they hasn't had a dedicated maintainer for a few versions now and so they were becoming problematic to keep working in newer Terraform versions. Since these backends are no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using one of these backends with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
