### ISSUE TITLE
get vertex from dag

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/terraform#23836]
sometimes to start walking from specific dag is useful to get vertex by name. Now i need to get all vertices and check for each of them name. This is suboptimal.
What you think about adding new method GetVertex(name string) and provide some optimizing to get it without full iteration?

**Comment by apparentlymart** [comment]
Hi @vtolstov,

The `dag` package is, broadly speaking, not optimized for graphs with large number of vertices because they do not occur in mainstream Terraform use. (A graph with many vertices would be indicative of a configuration in need of refactoring.)

Could you share some information about what you intend to do with this?

Please note that the `dag` package is not a stable public API and we may make breaking change to it without warning because we assume that we control all of the callers; the Terraform codebase is not a Go library, even though the Go toolchain allows it to be used as one. If you are asking this with the intention of using it from a separate codebase I'd recommend copying the code into your own codebase and editing it there.

**Comment by vtolstov** [comment]
Thank you. I'm use dag package for saga like pattern in my microservices.
So each micro service call is dag vertex. Edge is linking between services.
If execution failed in some service I'm use compensation, so start in backward direction with compensating actions.
I don't have many vertices, something like 10-12. But i have ability to register each service with such dag. So number of vertices can be 100.
And I'm prefer to have ability to get start vertex fast for recovery case.

**Comment by jbardin** [comment]
Hi @vtolstov,

The vertex name is not guaranteed to be unique, and the dag itself only really uses the vertex name for presentation. It does not use the name for its internal operations (except for some sorting, which is an implementation details likely to be removed).

If your use case requires a mapping of the name to vertex, I suggest you maintain a separate map alongside the dag.
