### ISSUE TITLE
chef provisioner use_policyfile validation fails when its a computed value

### ISSUE THREAD

**Issue by christophermichaeljohnston** [hashicorp/terraform#23852]
### Terraform Version
```
Terraform v0.12.18
```

### Terraform Configuration Files
```hcl
variable use_policyfile {
  type = bool
  default = true
}
resource "aws_instance" "instance" {
...
  provisioner "chef" {
    ..
    use_policyfile = var.use_policyfile
    ..
  }
...
}
```

### Expected Behavior
use_policyfile should work with variables. It only works if true, false, "true", or "false" is directly in the the chef provider section.

### Actual Behavior
Error is returned during validation or plan: 
```
"use_policyfile" must be a boolean
```

### Steps to Reproduce
Set use_policyfile to a variable, instead of directly set.

### Additional Context
I was able to determine this is caused because a variable is considered as computed and Get returns the raw reference string and not the value. The validation for the chef provisioner sees it as a string but it can't be transformed into a boolean since it's the uuid reference and not the value it fails with error above. I'll happily put together a PR to address this but have been unable to figure out how to obtain a computed value during validation, or if its even possible.

Related lines of code:
https://github.com/hashicorp/terraform/blob/272cb44d3d19ad1b68e5f312a92937b09e0dc316/terraform/resource.go#L380
https://github.com/hashicorp/terraform/blob/272cb44d3d19ad1b68e5f312a92937b09e0dc316/builtin/provisioners/chef/resource_provisioner.go#L387

Perhaps something is required in this function:
https://github.com/hashicorp/terraform/blob/272cb44d3d19ad1b68e5f312a92937b09e0dc316/terraform/resource.go#L440

**Comment by rickhlx** [comment]
Wouldn't Terraform handle the validation just by setting the SchemaType here?

https://github.com/hashicorp/terraform/blob/272cb44d3d19ad1b68e5f312a92937b09e0dc316/builtin/provisioners/chef/resource_provisioner.go#L181

In that case we could probably just remove the whole boolean validation portion

**Comment by christophermichaeljohnston** [comment]
That's what I did with a local build. But I also had to remove the remaining validations that require the value of use_chefpolicy. Is there a way to pull the value into the validation step?

**Comment by christophermichaeljohnston** [comment]
@rickhlx I took a look at your commit and unfortunately this line will always result in true whether the value is false or true.

`usePolicyFile = c.IsSet("use_policyfile")`

I'm still trying to find out to get values for computed items during validation. This worked fine with v0.11.14.

**Comment by rickhlx** [comment]
ASAIK there's not way to obtain a computed value, we will always get the "Raw" value, which is why documentation says to pair with 'IsComputed' 

https://github.com/hashicorp/terraform/blob/272cb44d3d19ad1b68e5f312a92937b09e0dc316/terraform/resource.go#L373

**Comment by christophermichaeljohnston** [comment]
I suppose the only fix here is to skip the additional validation if use_policyfile is computed. I can put together a PR for this or leave it to the terraform experts.

**Comment by rickhlx** [comment]
That's what this line here is doing: 

https://github.com/hashicorp/terraform/blob/1bd2d60fb322132e639b85d5d5813507e4d6b9c4/builtin/provisioners/chef/resource_provisioner.go#L383

**Comment by christophermichaeljohnston** [comment]
Yes but then the else clause will always set usePolicyFile to true and break the remaining validation checks for when its computed and false. None of the 3 checks that rely on usePolicyFile can be used when it's a computed value.

https://github.com/hashicorp/terraform/blob/1bd2d60fb322132e639b85d5d5813507e4d6b9c4/builtin/provisioners/chef/resource_provisioner.go#L397

https://github.com/hashicorp/terraform/blob/1bd2d60fb322132e639b85d5d5813507e4d6b9c4/builtin/provisioners/chef/resource_provisioner.go#L403

**Comment by barracksbuilder** [comment]
Anyway to fix this? I ran into it when trying to make a module and pass the true false in. I upgraded to v0.12.26 but that still displays the same use_policyfile must be a boolean.

**Comment by christophermichaeljohnston** [comment]
For a while I ran a custom compiled version, but have since moved away from using the chef provisioner completely. It seems the chef provisioner needs a maintainer as per the added tag.

**Comment by barracksbuilder** [comment]
That makes sense. We run a hybrid so my on-premise stuff is running vsphere. I was thinking about doing a remote_execute where it downloads the chef binary. Then uses command-line options that are filled in from terraform variables to execute. Or run a local_execute and do a bootstrap with terraform variables. 

Our Aws we already have autoscaling groups that have user_data with config scripts that are pulled down from our git repository which works really well.

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to see this built, is to work with the community and build a standalone chef provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
