### ISSUE TITLE
Add provider for Wasabi (S3)

### ISSUE THREAD

**Issue by binaryfire** [hashicorp/terraform#23889]
Hi all

Would it be possible to add a provider for Wasabi? 
https://wasabi.com/

Their API is fully compatible with Amazon's S3 API (https://assets.wasabi.com/wp-content/uploads/2018/07/Wasabi_API_Guide.pdf?x68053) so it should be fairly straightforward to spin this from the AWS S3 provider?

Cheers

**Comment by teamterraform** [comment]
Hi @binaryfire,

After looking at Wasabi and seeing that it seems to be an object store we're guessing that you're asking about a Wasabi _backend_ rather than a Wasabi _provider_, which is to say that you want to be able to store your Terraform state snapshots in Wasabi's data store?

We're not planning to add any new backends for the moment, but if the Wasabi API _is_ truly compatible with S3 then it should be possible to reconfigure the existing S3 backend to use it, using the more advanced [configuration arguments](https://www.terraform.io/docs/backends/types/s3.html#configuration-variables).

In particular, you'll likely need to set `endpoint`, and probably some or all of the arguments whose names start with `skip_` that disable interactions with AWS APIs aside from the S3 API, which Wasabi might not support.

We can't actively support use of "S3 clone" systems with the S3 backend, but if Wasabi has done a good enough job closing the S3 API then it should work. If you run into compatibility problems, you could potentially contact Wasabi to see if they can improve their S3 compatibility.

---

If it _was_ a provider you meant, rather than a backend -- that is, if you want to manage buckets, policies, objects, etc in Wasabi using Terraform, then unfortunately this isn't the right repository to request that, because Terraform providers exist as separate codebases in [their own GitHub repositories](https://github.com/terraform-providers). When it comes to providers that interact with external services, we generally expect to have a partnership relationship with the company in question, as described in [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html), to ensure that the provider's features remain aligned with changes to the system it's interacting with over time. For that reason, it's unlikely that there would be a Wasabi-specific provider unless the Wasabi team were interested in developing one and reached out to participate in the program.

**Comment by binaryfire** [comment]
@teamterraform Thanks for reply. Actually I was talking about a provider (to manage buckets, policies, objects etc) but a backend would certainly be useful too. I'll contact them and point them to the link you provided. Hopefully they'll be interested and reach out.

**Comment by binaryfire** [comment]
On a slightly unrelated note, is there any way to use community providers (such as UpCloud: https://github.com/UpCloudLtd/terraform-provider-upcloud) with Terraform Cloud API-driven runs? Or would they need to join your dev program for that to be possible?

Cheers

**Comment by danieldreier** [comment]
@binaryfire I'm going to close this because it's been open since January without a response. If Wasabi is interested in writing a provider, please take a look at the [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html), and note that in the upcoming Terraform 0.13, it will be [significantly easier](https://www.hashicorp.com/blog/adding-provider-source-to-hashicorp-terraform/) to use community-contributed providers.
