### ISSUE TITLE
Error: Invalid index ... but the index is correct.

### ISSUE THREAD

**Issue by sergiosanche** [hashicorp/terraform#23882]
### Terraform Version
```
terraform -v
Terraform v0.12.19
```

### Terraform Configuration Files
Nothing relevant

### Crash Output
I can't get the first item of an array obtained using data:
```
> data.aws_route_tables.admin-vpc-rts.ids
[
    "rtb-0831fdab7e5cb3f8c",
]
> data.aws_route_tables.admin-vpc-rts.ids[0]
>
Error: Invalid index
> data.aws_route_tables.admin-vpc-rts.ids.0
>
Error: Invalid index
```

### Expected Behavior
I should have obtained the vaule of the first item:
```
> data.aws_route_tables.admin-vpc-rts.ids[0]
"rtb-0831fdab7e5cb3f8c"
```

### Additional Context
This problem is present when I try to deploy and using console too.

**Comment by jbardin** [comment]
Hi @sergiosanche,

While the output may be displayed with the same syntax as a list, the type of `ids` is a `set(string)`, which cannot be indexed because it is unordered. If this is an attribute that one would normally index single values from, it should be of type `list(string)`. I'll transfer the issue to the aws provider repo where the change would have to be made.

In the meantime, you should be able to use the [`tolist`](https://www.terraform.io/docs/configuration/functions/tolist.html) function, or iterate over the set using a [for expression](https://www.terraform.io/docs/configuration/expressions.html#for-expressions).
