### ISSUE TITLE
'Getting Started - Azure / Resource Dependencies' corrupted/ill-formatted code snippet

### ISSUE THREAD

**Issue by ranvit** [hashicorp/terraform#23913]
### Terraform Version

```
Terraform v0.12.18
```
The code snippet of a config file at the bottom of this page (https://learn.hashicorp.com/terraform/azure/dependencies_az) is poorly formatted and missing the first few lines.

- This can be confirmed because Input Variables `var.resource_prefix` and `var.location` are used without being declared.
- This code snippet is supposed to be the complete configuration, so these Input Variable Declarations should be included, but are missing.
- Additionally, the bottom of the code snippet also contains some unnecessary text like 
`>>>>>>> 81d9e53... Updates to TF AZ Getting Started` 
(I think it is some diff output from git)

### Expected Behavior
If you navigate to the next step of this tutorial (https://learn.hashicorp.com/terraform/azure/provision_az), the complete configuration at the bottom of this page **DOES** include the missing Input Variable declarations.

### Actual Behavior
Missing Input Variable declarations on this page: https://learn.hashicorp.com/terraform/azure/dependencies_az

### Steps to Reproduce
- Visit this website: https://learn.hashicorp.com/terraform/azure/dependencies_az
- Scroll to the bottom of the page
- Notice the missing variable declarations and the git diff output in the code snippet

**Comment by bflad** [comment]
Hi @ranvit 👋  It appears that since this issue was raised that the HashiCorp Learn tutorials have since moved or materially changed as both of the links are no longer pointing to active Azure tutorials. Given that, I'm going to close this issue out. I believe it is now possible to provide direct feedback on the tutorial pages so that the team that maintains them, which doesn't typically monitor the issues in this repository, can act on it. Thank you for reporting this.
