### ISSUE TITLE
conditional evaluation for boolean

### ISSUE THREAD

**Issue by bauteb-sci** [hashicorp/terraform#23939]
### Terraform Version

```
v0.11.14
```

### Terraform Configuration Files

```hcl
# Simple example to illustrate the issue.  
# Aware that you can use the shortcut without the == in .11,
# but trying to write code in preparation for an upgrade to .12.
# Hoping for syntax that will work in both versions.

variable "enable_foobar" {
  type        = "string"
  description = "foo bar"
  default     = false
}

enable_foobar = true

# This correctly evaluates as true
count = "${var.enable_foobar == 1 ? 1 : 0}"

# However this evaluates as false
count = "${var.enable_foobar == true ? 1 : 0}"
```

**Comment by apparentlymart** [comment]
Hi @bauteb-sci,

It looks like you're running into [some known limitations of Terraform 0.11](https://www.terraform.io/docs/configuration-0-11/variables.html#booleans) here. Since 0.11 development is now concluded those limitations are unfortunately what we have to work with, but I think it should be possible to write this in a way that can be understood by both Terraform 0.11 and 0.12 like this:

```hcl
variable "enable_foobar" {
  type    = "string"
  default = "false"
}

resource "example" "example" {
  count = "${var.enable_foobar ? 1 : 0}"
}
```

The above can work because using `var.enable_foobar` directly in the first clause of the conditional lets Terraform know that you intend this value to be understood as a boolean value, both in Terraform 0.11 and 0.12. Both versions will then convert the string `"false"` to boolean `false` and the string `"true"` to boolean `true`, getting the desired result.

That doesn't work in the case of `var.enable_foobar == true` because you've asked Terraform if these two values are equal, and `"true"` is not equal to `true` unless Terraform has some way to know to convert the string to a boolean first. (Although I don't recommend doing it in practice, a different way you could make it work is to coerse the value to boolean before comparing by using a boolean operation with it, like `(var.enable_foobar && var.enable_foobar) == true`; the `&&` operator converts both of its arguments to boolean and always returns a boolean, producing a value that can be equal to `true`.

Once you're ready to stop working with Terraform 0.11, you can improve this module by rewriting it like this:

```hcl
variable "enable_foobar" {
  type    = bool
  default = false
}

resource "example" "example" {
  count = var.enable_foobar ? 1 : 0
}
```

This uses Terraform 0.12's first-class support for boolean input variables, and uses the first-class expression syntax for `count`.

One further note here is that recent versions of Terraform 0.12 have started to deprecate the backward-compatibility mechanisms in preparation for phasing them out in a future major release, so I'd suggest not upgrading to a version newer than 0.12.13 until you're ready to end Terraform 0.11 compatibility in your modules. Otherwise, later versions will emit warnings about legacy patterns that Terraform 0.11 cross-compatibility depends on. Once you've completed your migration to Terraform 0.12, you can then upgrade to the latest 0.12.x release and use the warnings to switch your modules over to idiomatic Terraform 0.12 usage.

Since Terraform 0.11 is no longer under active development and we use our issue tracker primarily to track actionable work, I'm going to close this out. If you have any other questions about writing Terraform configuration that is cross-compatible between Terraform 0.11 and Terraform 0.12, please feel free to start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). (If you do, please be sure to mention that you're aiming for compatibility with both versions, since participants of that forum tend to assume 0.12-only syntax is okay unless otherwise indicated.)
