### ISSUE TITLE
Support no_pty argument for ssh connection

### ISSUE THREAD

**Issue by ZsoltFekete** [hashicorp/terraform#2393]
In `communicator/ssh/communicator.go` in `sshConfig struct` there is a member variable `noPty` which is always `false`. In my opinion it would be useful if this variable can be configurable (so I would be able set it `true`). 

I've tried it: enbritely/terraform@13ea1a5abd328fcd11c49e6903c0bbe97db5f996

**Comment by catsby** [comment]
Thanks for the suggestion @ZsoltFekete – I'll bring this up internally, but I can't comment on any kind of delivery time

**Comment by apparentlymart** [comment]
Hi @ZsoltFekete! Sorry for the long silence here.

There aren't currently any plans to implement a feature for this, though if you or someone else were motivated to implement it we'd be happy to review a PR. It would also be useful, were such a PR to be opened, to have a little more info on the intended use-case, since it can be helpful to give guidance in the docs for some more "esoteric" options like this one, where the user e.g. might not be familiar with what a pseudo-terminal is and what the implications are of disabling it.

We're trying to close out some of these older issues where there's no immediate plan of action as part of getting the queue into a more managable state, so I'm going to close this but we'd still be open to a PR for this feature. Thanks for opening this, and sorry again for letting it sit here unattended for so long.
