### ISSUE TITLE
Redis in Terraform

### ISSUE THREAD

**Issue by jmccauley-mandmdirect** [hashicorp/terraform#23933]
Hi all,

Trying to build a redis instance in google. Having some issues with the authorised network argument.

So my argument looks like this

authorized_network = "${element(data.terraform_remote_state.network.network.self_link ,0)}"

But when running a plan / apply, I get the following output

google_redis_instance.redis: At column 3, line 1: element: argument 1 should be type list, got type string in:

${element(data.terraform_remote_state.network.network.self_link ,0)}

Sounds like it might need an array somewhere, but no idea where. Have tried lots of different things.

Cheers.

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
