### ISSUE TITLE
Variable Validations - Existing provider

### ISSUE THREAD

**Issue by craigmonson** [hashicorp/terraform#23947]
Hey there!  I noticed the variable validations addition in 0.12.20, and just wanted to forward you to a provider I wrote (and are currently using).  Maybe it'll help, maybe not, but figured it'd be nice to at least put it on your radar:

https://github.com/craigmonson/terraform-provider-validate

Thanks!

**Comment by apparentlymart** [comment]
Thanks for sharing that, @craigmonson! Using data sources to implement this sort of thing is a nice idea... I had a similar thought in [a provider I built to help with module integration testing](https://github.com/apparentlymart/terraform-provider-testing), but I didn't think about how it might be useful outside of that use-case.

I think an interesting consequence of doing this sort of validation with a Terraform provider and data sources is how it might interact with Terraform's support for concurrent operations. Unless everything that refers to a variable also has an explicit `depends_on` for the corresponding `data "validate"` resource then there is a risk that an action based on the incorrect data may begin prior to the validation check, and thus might allow invalid data to make it to a remote system:

```hcl
variable "example" {
  type = string
}

data "validate" "exact" {
  val   = var.example
  exact = "foo"
}

resource "null_resource" "example" {
  triggers = {
    example = var.example
  }

  # Make sure this resource can't be applied if the validation fails
  depends_on = [data.validate.exact]
}
```

In an earlier design iteration I considered a top-level `validation` block (or similar) which would serve a similar purpose to your `validate` data source of allowing arbitrary checks, maybe like this:

```hcl
validation {
  condition     = var.example == "foo"
  error_message = "Argument \"example\" must be \"foo\"."
}
```

Making that first-class would allow Terraform to have some special handling for it: any object that depends on a value that is included in a validation `condition` expression could automatically depend on the checking of the validation rule, to ensure that the relevant validation rules must always hold before those values can be used.

In the end we moved foward with the variable-specific validation rule because it was a less complex mechanism to start with and fit more neatly with Terraform's existing functionality. Attaching a validation rule directly to a variable also has the nice advantage that when the condition fails we can report the problem at the expression in the calling module, rather than at the `condition` expression itself, which we hope will give a better sense of the module's functionality being encapsulated as we see for resources.

The top-level `validation` block might still arrive later as generalization to meet multi-variable validation use-cases etc, but we'll wait and see how the variable-specific validation plays out first and bring that experience into any future design work.

---

Thanks again for sharing your provider! It has some good common condition types expressed in its interface which I converted into validation rules for the new mechanism just to see whether the new feature can accomplish all of them:

```hcl
variable "test_exact" {
  type    = string
  default = "test_exact"

  validation {
    condition     = var.test_exact == "test_exact"
    error_message = "Argument \"test_exact\" must be \"test_exact\"."
  }
}

variable "test_one_of" {
  type    = string
  default = "test_one_of"

  validation {
    condition     = contains(["test_one_of", "test_one_of_2"], var.test_exact)
    error_message = "Argument \"test_exact\" must be one of \"test_one_of\" or \"test_one_of_2\"."
  }
}

variable "test_regex" {
  type    = string
  default = "test_regex"

  validation {
    # In the provider example the arguments seem to be inverted,
    # unless I misunderstood the intended behavior. I've implemented
    # what I understood of the "regex" documentation here.
    condition     = can(regex("^test_.*$"), var.test_exact)
    error_message = "Argument \"test_exact\" must start with \"test_\"."
  }
}
```

The expressions here are less concise than they would be if we had specific support for "one of" and regex matching, but I _think_ they are still intuitive enough for a reader to be able to determine what they mean.

**Comment by craigmonson** [comment]
Yay!  I'm super glad I could contribute!

Setting this up as a data source was more of a "Best way to implement" at the time.  I'd run into the need many times before, but only encountered the map "missing key" approach to clobber invalid inputs. I didn't think this was the right way to go.   It seemed like the right path was to implement a provider that would accomplish what I needed.  TBH, I was waiting on the registry to open up to providers so I could publish said code, but your setup seems to have precluded it.

There are holes in the data source approach for sure.  I've not explored them to any significant extent, but I'm 100% sure they exist.  Given the graphing nature of TF, you can do some things that'll skip the validation.  Not great.

What I like _most_ about how I implemented the code was that I feel the implementation was really self explanatory.  "one_of" is just sensible.   I mean... the fact you could read my documentation, and understand what I was shooting for makes me super happy!

With all that said, I think the right approach is being able to describe validations in variable descriptions... that's where I'd have tried it originally.  I feel like that's just the next extension of types. I'm not sure where that leads us, but it's a great start.

Definitely want to contribute to this.

**Comment by craigmonson** [comment]
This doesn't need to be open any more.  It's been included in main.
