### ISSUE TITLE
Unexpected failure for Input Variable custom validation

### ISSUE THREAD

**Issue by manishingole-coder** [hashicorp/terraform#23946]
Hi there,

I am excited about the new input variable validation feature and started using it since it released, however, I am having an issue with it.

My variable definition is 

variable "s3bucket" {
   description = "Enter s3 bucket name for wal archive followed by folder name"
   type = string
   validation {
     condition = length(var.s3bucket) == "0"
     error_message = "S3 bucket name cannot be blank."
   } 

When I dont provide s3bucket name then this error message displays on screen however even I provide s3bucket name same error message appear on the screen which is not expected.

**Comment by apparentlymart** [comment]
Hi @manishingole-coder! Thanks for sending in this feedback.

In this case I think the problem is with the `condition` expression itself: the `length` function returns a number rather than a string, so its result can never be equal to `"0"`, and so this validation rule will always fail.

Does it work if you rewrite it to use a number value instead? I notice the expression also seems to be backwards, in that you're _requiring_ that the value be empty, so I've changed it to use `>` instead here:

```hcl
variable "s3bucket" {
  description = "Enter s3 bucket name for wal archive followed by folder name"
  type        = string

  validation {
    condition     = length(var.s3bucket) > 0
    error_message = "S3 bucket name must not be empty."
  }
}
```

**Comment by manishingole-coder** [comment]
Hi apparentlymart,

Thank you for your reply.  Yes you are right problem was in condition expression and before your valuable suggestion I was able to fix this by writing  condition 
validation {
  condition= length(replace("${var.s3bucket}", "","a")) !=1
  error_message = "S3 bucket name must not be empty."
}
}

What I learn here is validation requires boolean value always to print error_message. 

Thanks again
