### ISSUE TITLE
Azure Terraform - Unable to pass Virtual Machine Name from VM Module output to other terraform files

### ISSUE THREAD

**Issue by athangmansing** [hashicorp/terraform#23944]
I got a module created for Azure Virtual Machine with count and outputting the Virtual Machine Name in order to be used in other terraform modules/files.

Module:
```
   resource "azurerm_virtual_machine" "virtual_machine"{
         name = <>
         count = 2
         ......
         ..
   }
```
output.tf
```
output "vm_name" {
  value = "${azurerm_virtual_machine.virtual_machine.*.name}"
}
```

VM.tf
```
module "testworkstation"
{
    source = "/module/virtual_machine"
    .....
}
```

When I pass vm name value to other terraform which creates monitoring alert, it fails.
```
module "cpu-credits-consumed-win-vm" {
  source                                  = "../modules/monitor_metric_alert" 
  name                                    = "test_${module.testworkstation.vm_name}"
````
Below is the error we are getting.
```
Error: Error refreshing state: 1 error occurred:
        * module.cpu-credits-consumed-win-vm.var.name: At column 1, line 1: output of an HIL expression must be a string, or a single list (argument 2 is TypeList) in:

test_${module.testworkstation.vm_name}
```
Terraform versions:
```
Terraform v0.11.14
+ provider.azurerm v1.37.0
+ provider.null v2.1.1
+ provider.template v2.1.1
```

**Comment by teamterraform** [comment]
Hi @athangmansing!

This seems to be a usage question rather than a bug: you're using the result of a splat expression (a list) in a location where only a single string is expected.

We'd encourage you to ask about this in [the community forum](https://discuss.hashicorp.com/c/terraform-core) instead, and share details there about what your ultimate goal is rather than this immediate problem; the forum participants there should be able to help you find a good way to express what you need to express here, which might require approaching the problem a slightly different way.

Thanks!
