### ISSUE TITLE
New Function: flipmap

### ISSUE THREAD

**Issue by janschumann** [hashicorp/terraform#23942]
### Current Terraform Version
Terraform v0.12.19

### Use-cases
Consider the following map of azure locations and corresponding short names:

```hcl
locals {
  locations_by_short_name = {
    WE = "westeurope"
    NE = "northeurope"
  }
}
```

In some cases it might be necessary to get the short name by an azure location name. In that case we need to flip keys and values.

### Attempted Solutions
As a workaround we use the `zipmap` function:

```hcl
locals {
  locations_by_name = zipmap(values(local.locations_by_short_name), keys(local.locations_by_short_name))
}
```

### Proposal
Implement a function flipmap to get this functionality natively.

```hcl
locals {
  locations_by_name = flipmap(local.locations_by_short_name)
}
```

**Comment by jbardin** [comment]
Hi @janschumann,

Thanks for the contribution. In general we prefer to use more flexible expressions rather than dedicated functions, especially for less-common use cases. We can leave the specialized functions to handle more complex cases when necessary, and give user a single clear way to do thing. 

Would the for expression `{for k, v in local. locations_by_short_name : v => k }` accomplish what you're looking for? This also provides a clear error for the user when there are duplicate values, leaving the `zipmap` trick if the user wants to ignore the duplicates and it doesn't matter which keys survive.

**Comment by janschumann** [comment]
Hi @jbardin,

Sure, the expression also works. I thought it would be smarter to have a dedicated function, but I understand your point :-)

I think this can be closed than.

**Comment by jbardin** [comment]
Thanks @janschumann
