### ISSUE TITLE
Use community providers with Terraform Cloud API-driven runs

### ISSUE THREAD

**Issue by binaryfire** [hashicorp/terraform#23955]
Hi all

Would it be possible to allow the usage of community supported providers (such as UpCloud: https://github.com/UpCloudLtd/terraform-provider-upcloud) with Terraform Cloud API-driven runs?

Cheers

**Comment by apparentlymart** [comment]
Hi @binaryfire! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

With that said, I think you opened this issue prior to the release of Terraform v0.13, and since v0.13 there is now a direct answer to this request: provider maintainers can publish their providers via [Terraform Registry](https://registry.terraform.io/) and then Terraform v0.13 and later can automatically install them in a similar way as the providers HashiCorp directly distributed in prior versions.

The provider you mentioned here seems to be available in the registry as [`upcloudltd/upcloud`](https://registry.terraform.io/providers/UpCloudLtd/upcloud), and so you could declare a dependency on this provider in each of your modules that need it using [the Provider Requirements syntax](https://www.terraform.io/docs/configuration/provider-requirements.html):

```hcl
terraform {
  required_providers {
    upcloud = {
      source  = "upcloudltd/upcloud"
      version = ">= 1.0.0"
    }
  }
}
```

Since I think that addresses what you were asking about, I'm going to close this out. The answer wasn't Terraform Cloud specific in the end (this registry installation behavior is a general Terraform CLI feature) but it is usable within Terraform Cloud nonetheless.

Note that the Terraform Cloud teams prefer to receive feedback via their customer support system, so if you have other feature requests for Terraform Cloud in future I'd suggest to send them to the support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.
