### ISSUE TITLE
Type validation of value coming from remote states

### ISSUE THREAD

**Issue by ohmer** [hashicorp/terraform#24012]
```
Terraform v0.12.20
```

### Terraform Configuration Files
```hcl
data "terraform_remote_state" "transit" {
  backend = "s3"
  config = {
    region = "ap-southeast-2"
    bucket = "<abucket>"
    key    = "<akey>"
  }
}

resource "aws_ec2_transit_gateway_vpc_attachment_accepter" "vpc_internal" {
  for_each = toset([
   data.terraform_remote_state.wcc_cumulus_migration.outputs.transit_gateway_attachment_id
  ])

  transit_gateway_attachment_id                   = each.value
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
  tags                                            = var.tags
}
```

### Debug Output
```
$ terraform console
> data.terraform_remote_state.wcc_cumulus_migration.outputs.transit_gateway_attachment_id
tgw-attach-003f0ffa787ddec26
```
### Crash Output
```
$ terraform apply

Error: Invalid for_each set argument

  on r_transit_gateway.tf line 14, in resource "aws_ec2_transit_gateway_vpc_attachment_accepter" "vpc_internal":
  14:   for_each = toset([
  15:     tostring(data.terraform_remote_state.wcc_cumulus_migration.outputs.transit_gateway_attachment_id)
  16:   ])

The given "for_each" argument value is unsuitable: "for_each" supports maps
and sets of strings, but you have provided a set containing type dynamic.
```

I also tried without to tostring() function call. Same result.

### Expected Behavior
Successful plan/apply with the value from the remote state:

```hcl
resource "aws_ec2_transit_gateway_vpc_attachment_accepter" "vpc_internal" {
  for_each = toset([
    "tgw-attach-003f0ffa787ddec26"
  ])

  transit_gateway_attachment_id                   = each.value
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
  tags                                            = var.tags
}
```

Above works as a workaround.

### Actual Behavior
Invalid syntax error.

### Additional Context
Running from CLI with aws-vault (`aws-vault exec <profile> -- terraform <cmd> <options>`)

### References

- maybe #23077

**Comment by bendrucker** [comment]
Hi @ohmer, this is partially a result of `for_each` attributes needing to be able to identify the keys of all the resources it will be creating early on. 

More commonly, users run into this when trying to pass IDs that are not known until apply time into `for_each`. In this case, because everything is dynamically typed once you pass `.outputs`, you'll hit a similar issue. That's not to say this couldn't be made to work, the IDs are known at plan time. Just a bit tricky, as there's no guarantee that the elements of your set are actually strings at eval time.

If you have a specific set of named gateways, this would be a better workaround:

```tf
for_each = {
  a = data.terraform_remote_state.wcc_cumulus_migration.outputs.transit_gateway_attachment_id
  b = data.terraform_remote_state.wcc_cumulus_migration_b.outputs.transit_gateway_attachment_id
}
```

In this case the keys are typed as strings since it's a map literal. The "literal" part is important here, referring to a dynamic map stored in the remote state will hit the same issue.

**Comment by ohmer** [comment]
Hi Ben,

Makes perfect sense, thanks.
Should this be relabeled as a not a bug?
Happy to close this issue-which-aint-one.

**Comment by bendrucker** [comment]
I would leave it open, I think it's worth investigating whether coercing the set to a `set(string)` is possible. Unlike plan versus apply time, it's solvable. 

The evaluator handles `for_each` for sets here:

https://github.com/hashicorp/terraform/blob/9c75cfd403dd5b9f51a21065bf9e3efb890e22de/terraform/eval_for_each.go#L85-L117

And `tostring` should be producing a `cty.String` as far as I can see:

https://github.com/hashicorp/terraform/blob/d4d8812afa63bca35384169ccbcb10d923a80736/lang/functions.go#L118
https://github.com/zclconf/go-cty/blob/1749c82128fa4ecad898591107cd93cf1cdbb23e/cty/function/stdlib/conversion.go#L19

But then `toset` ends up converting us back to a `DynamicPseudoType`:

https://github.com/hashicorp/terraform/blob/d4d8812afa63bca35384169ccbcb10d923a80736/lang/functions.go#L121

It should be possible for the conversion to go over the supplied tuple and use a more specific type if it finds that all elements have the same type.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the slow response, and thanks for reporting this.

The analysis above looks correct to me. Unfortunately I think changing the return type of the `toset` call here wouldn't make it _work_ (the keys are still unknown) but it _could_ produce a better error message talking about unknown values instead.

Another way to address this, which would be localized to `for_each` and avoid potentially-risky changes elsewhere, would be to rework the `for_each` validation logic so it'd check for "known-ness" of the set elements _first_, preferring to produce the error message about that rather than the type mismatch error. It looks like swapping the element type check and the `IsWhollyKnown` check to happen in the opposite order in the `eval_for_each.go` snippet you shared would achieve that.
