### ISSUE TITLE
Add support for running Terraform under WSL on Windows on ARM

### ISSUE THREAD

**Issue by derekbelrose** [hashicorp/terraform#24013]
Good evening,

I initially added this to  #23525 but realized it was closed.  Instead resurrecting that ticket here's a new one.

I am running Ubuntu 18.10, `go version` gives "go version go1.10.4 linux/arm64".

I am trying to get Terraform for compile under Ubuntu on WSL on my Surace Pro X (Windows on ARM). Here are the initial results:

> derek@DESKTOP-7PM1NT1:~/terraform$ make bin
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./backend/remote/backend_mock.go
./backend/remote-state/s3/backend_state.go
./backend/remote-state/s3/backend_test.go
./backend/remote-state/azure/client_test.go
./backend/remote-state/azure/backend_test.go
./backend/remote-state/oss/backend_test.go
./plugin/discovery/get_test.go
./command/meta_backend_test.go
./command/init.go
./builtin/providers/test/diff_apply_test.go
./builtin/providers/test/resource_dataproc_cluster_test.go
./builtin/provisioners/puppet/linux_provisioner_test.go
./builtin/provisioners/chef/linux_provisioner_test.go
./helper/schema/shims_test.go
./helper/schema/schema_test.go
./helper/schema/resource_timeout_test.go
./terraform/context_apply_test.go
You can use the command: make fmt to reformat code.
Makefile:93: recipe for target 'fmtcheck' failed
make: *** [fmtcheck] Error 1

My next step is to try 'make fmt'.

**Comment by derekbelrose** [comment]
After running `make fmt` without issue:

> derek@DESKTOP-7PM1NT1:~/terraform$ make bin
> ==> Checking that code complies with gofmt requirements...
> GOFLAGS=-mod=vendor go generate ./...
> go run: no go files listed
> addrs/resource.go:260: running "go": exit status 1
> go run: no go files listed
> backend/operation_type.go:3: running "go": exit status 1
> go run: no go files listed
> backend/local/hook_count_action.go:3: running "go": exit status 1
> go run: no go files listed
> config/resource_mode.go:3: running "go": exit status 1
> go run: no go files listed
> configs/provisioner.go:175: running "go": exit status 1
> go run: no go files listed
> configs/configschema/schema.go:86: running "go": exit status 1
> go run: no go files listed
> helper/schema/resource_data_get_source.go:3: running "go": exit status 1
> go run: no go files listed
> plans/action.go:15: running "go": exit status 1
> go run: no go files listed
> plugin/mock_proto/generate.go:1: running "go": exit status 1
> go run: no go files listed
> states/instance_object.go:48: running "go": exit status 1
> go run: no go files listed
> states/statemgr/migrate.go:132: running "go": exit status 1
> go run: no go files listed
> terraform/context_graph_type.go:3: running "go": exit status 1
> go run: no go files listed
> tfdiags/diagnostic.go:20: running "go": exit status 1
> Makefile:70: recipe for target 'generate' failed
> make: *** [generate] Error 1

At this point, I'm looking to you all for guidance into where to go next. I'm willing to do some leg work and submit patches but I'm a little out of my element here :)

**Comment by derekbelrose** [comment]
`make test` produces similar errors:

> derek@DESKTOP-7PM1NT1:terraform$ make test
> ==> Checking that code complies with gofmt requirements...
> GOFLAGS=-mod=vendor go generate ./...
> go run: no go files listed
> addrs/resource.go:260: running "go": exit status 1
> go run: no go files listed
> backend/operation_type.go:3: running "go": exit status 1
> go run: no go files listed
> backend/local/hook_count_action.go:3: running "go": exit status 1
> go run: no go files listed
> config/resource_mode.go:3: running "go": exit status 1
> go run: no go files listed
> configs/provisioner.go:175: running "go": exit status 1
> go run: no go files listed
> configs/configschema/schema.go:86: running "go": exit status 1
> go run: no go files listed
> helper/schema/resource_data_get_source.go:3: running "go": exit status 1
> go run: no go files listed
> plans/action.go:15: running "go": exit status 1
> go run: no go files listed
> plugin/mock_proto/generate.go:1: running "go": exit status 1
> go run: no go files listed
> states/instance_object.go:48: running "go": exit status 1
> go run: no go files listed
> states/statemgr/migrate.go:132: running "go": exit status 1
> go run: no go files listed
> terraform/context_graph_type.go:3: running "go": exit status 1
> go run: no go files listed
> tfdiags/diagnostic.go:20: running "go": exit status 1
> Makefile:70: recipe for target 'generate' failed
> make: *** [generate] Error 1
> derek@DESKTOP-7PM1NT1:~/terraform$

**Comment by pkolyvas** [comment]
@derekbelrose If you're building Terraform `0.12.x` you'll need the go version here: `https://github.com/hashicorp/terraform/blob/master/.go-version` (`1.12.13`).

**Comment by apparentlymart** [comment]
In addition to @pkolyvas's advice, you might find [the contributing guide](https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md) useful. It contains information on the recommended way to build Terraform in a development environment, which in particular doesn't use the `Makefile`. (The `Makefile` is used mainly to support our build/release automation, such as the Travis-CI tests on PRs, and so forth.)

None of us develop Terraform on ARM in WSL, so I can't say for certain that the instructions there will work flawlessly for you, but if you follow those commands and run into problems we may be more able to help because they match how we work on Terraform day-to-day.

I will caveat that Terraform development on Windows _outside of_ WSL hasn't historically been supported due to limitations like maximum path lengths which the automated tests violate. I believe it should be possible to _build_ Terraform on Windows (using `go install .`) but last we knew the tests would not work there. More recent Windows versions may have loosened those constraints, and the situation may be different in WSL, but I just want to be transparent that ongoing development friction is likely. :confounded:

With that said, I hear WSL 2 is based on a virtual machine running a real Linux kernel (rather than the system call emulation done in previous versions) so perhaps things will be smoother than before.
