### ISSUE TITLE
Pass blocks to modules

### ISSUE THREAD

**Issue by soldiermoth** [hashicorp/terraform#24029]
### Current Terraform Version

```
Terraform v0.12.20
```

### Use-cases

I've been working with the Datadog Terraform provider to create multiple dashboards that have some shared components but still retain the ability to customize. This requires the ability to reference blocks either in a module or from a module.

Datadog's block syntax is fairly complex so implementing via the workaround in #3388 is not practical.  For example

```
resource "datadog_dashboard" "test" {
  widget {
    group_definition {
      layout_type = "ordered"
      title       = "Some Group"

      widget {
        timeseries_definition {
          title = "RPS"

          request {
            q            = "sum:app_metric.count{$env,app:my_app}.as_rate()"
            display_type = "line"

            style {
              line_width = "thin"
              line_type  = "solid"
            }
          }
        }
      }
```

Which I'd like to include RPS as defined across multiple Dashboards, currently need to duplicate across all of them. This block will be mixed with additional `widget`s that are custom to each dashboard.

### Attempted Solutions
Tried using modules but quickly run into composability problems

### Proposal

Allow passing arbitrary blocks to modules

### References

- #3388

**Comment by teamterraform** [comment]
Hi @soldiermoth,

A lot has changed since 3338 was closed, and we now have the ability to pass around complex values using a structural type system, allowing one to do exactly as you describe here.

While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.
