### ISSUE TITLE
datasources are not always evaluated before providers depending on it

### ISSUE THREAD

**Issue by voroniys** [hashicorp/terraform#24037]
### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.43.0
+ provider.local v1.4.0
+ provider.postgresql v1.4.0
+ provider.random v2.2.1

```

### Terraform Configuration Files

```hcl
data "aws_secretsmanager_secret_version" "pgsql" {
  depends_on = [aws_secretsmanager_secret_version.secret]
  secret_id  = "${aws_secretsmanager_secret.secret.id}"
}

provider "postgresql" {
  host             = aws_db_instance.rds.address
  port             = aws_db_instance.rds.port
  username         = jsondecode(data.aws_secretsmanager_secret_version.pgsql.secret_string)["username"]
  password         = jsondecode(data.aws_secretsmanager_secret_version.pgsql.secret_string)["password"]
  sslmode          = "require"
  connect_timeout  = 15
  expected_version = local.engine_version
  superuser        = false
}

```

### Expected Behavior

It should just work, and for the first time of usage this provider it works

### Actual Behavior

A subsequent run is failing with the message:
```
Error: pq: no PostgreSQL user name specified in startup packet
Error: could not start transaction: pq: no PostgreSQL user name specified in startup packet
```
and the output does not contain the string: 
```
data.aws_secretsmanager_secret_version.pgsql: Refreshing state...
```
### Steps to Reproduce

terraform plan
### References

- #11264

**Comment by jbardin** [comment]
Hi @voroniys,

Your data source depends on a resource, so initially it can't be evaluated until after the resource is applied. This transitive dependency is the same as trying to have the provider depend directly on the resource.

The other issue here is that you cannot use `depends_on` in a data source, because it will cause a perpetual diff on every plan. It also forces the data source to always be read during apply, again preventing it from being available to configure the provider. 

While we can sometimes help with certain simple problems here, if you have any more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks
