### ISSUE TITLE
for_each unsuitable argument value with remote state attributes (type of dynamic)

### ISSUE THREAD

**Issue by iancward** [hashicorp/terraform#24049]
### Terraform Version

```
Terraform v0.12.19
+ provider.aws v2.42.0
```

### Terraform Configuration Files
```hcl
terraform_remote_state "upstream" {
  backend "s3"
  config = {
    foo
  }

locals {
  relevant_nacl_ids = [
    data.terraform_remote_state.upstream.outputsnacl1,
    data.terraform_remote_state.upstream.outputs.nacl2,
    data.terraform_remote_state.upstream.outputs.nacl2
  ]
}

 resource "aws_network_acl_rule" "standard_rule_for_all_nacls" {
  for_each local.relevant_nacl_ids

  network_acl_id = each.value

  ...
}
```

### Expected Behavior
Terraform should create resource as expected

### Actual Behavior
> Error: Invalid for_each argument
>
> The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type tuple.

If I set `for_each = tolist(local.relevant_nacl_ids)` then, I get this error:
> Error: Invalid for_each argument
> 
> The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type list
of dynamic.

I get similar results if I use `toset()`

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
I think what's happening here is that terraform doesn't have any clue what to expect from remote state, so it's leaving the data type as `dynamic`, despite the documentation on `tolist()` says that
> Since Terraform's concept of a list requires all of the elements to be of the same type, mixed-typed elements will be converted to the most general type
https://www.terraform.io/docs/configuration/functions/tolist.html

And effectively the same thing is said in the documentation for `toset()`:
https://www.terraform.io/docs/configuration/functions/toset.html

**Comment by jbardin** [comment]
Hi @iancward,

You're correct that the terraform  cannot know the structure of the remote output data ahead of time, so you are limited in where you can use that data.

The standard input data type for `for_each` however would be a map or object, which you can construct to contain the remote values you want to use. This way all keys are known for planning, and the values can be resolved as needed.

You should be able to use the object syntax like so

```
locals {
  relevant_nacl_ids = {
    nacl1 = data.terraform_remote_state.upstream.outputs.nacl1,
    nacl2 = data.terraform_remote_state.upstream.outputs.nacl2,
    nacl3 = data.terraform_remote_state.upstream.outputs.nacl3,
  }
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

**Comment by iancward** [comment]
Thanks for the response. The documentation says that the `tolist()` and `toset()` forces the the collection to a single data type, so this seemed to be a legitimate bug.

Is there documentation anywhere explaining the behavior you've described?

**Comment by jbardin** [comment]
The `toset` function (`tolist` will not work in this case, because a list isn't a valid `for_each` argument type) will accept the dynamic types and work appropriately. The issue is that the resulting type ("set of dynamic") is not suitable for `for_each`, which must be a set of strings.

**Comment by iancward** [comment]
Ok, so are you saying that `dynamic` is a type? Shouldn't `toset()` convert the collection items to one of the primitives listed here? https://www.terraform.io/docs/configuration/expressions.html#types-and-values

Because, looking at the primitive types documentation (which doesn't list a `dynamic` type), and the `toset()` documentation which says it forces all items to a single type, I expected the code I have above should work.

**Comment by iancward** [comment]
Ah, I found https://www.terraform.io/docs/configuration/expressions.html#values-not-yet-known.

Well, if there's any way to get this behavior documented for the next person, that would be good. :-D

**Comment by jbardin** [comment]
A set can contain any single consistent type, so `toset` doesn't reduce the type to a primitive, just the common base type. If the type is unknown, that would be represented "dynamic" until the type can be resolved. This isn't a valid argument to `for_each` because there's no way to know if it will resolve as `set(string)` or `set(map(list(number)))`, 

We do have some changes to how data sources are handled planned for future releases, and may be able to relax this combination slightly during validation, but that won't be until after another major release. As for now it's working as designed.
