### ISSUE TITLE
Importing "terraform show -json <file>" to python

### ISSUE THREAD

**Issue by SQLJames** [hashicorp/terraform#24053]
I am getting an error when trying to import the terraform json output from the "terraform show -json <file>" command. My steps to replicate are as follows:

- terraform plan -out .\plan.state.tfstate 
- terraform show -json .\plan.state.tfstate > plan.state.show.json

then run the following code in a python script.

```
import json
#terraform plan -out .\plan.state.tfstate 
#terraform show -json .\plan.state.tfstate > plan.state.show.json
with open('plan.state.show.json', 'r') as jsonfile:
    jsonfile.seek(0)
    data = json.load(jsonfile)
print(json.dumps(data, indent=4))
```

This returns the following error
```
Traceback (most recent call last):
  File ".\terraform-validate.py", line 15, in <module>
    data = json.load(jsonfile)
  File "C:\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I am able to import this output into powershell without issue. But I was wondering if someone has run into this prior.

Terraform v0.12.20
+ provider.aws v2.47.0

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
