### ISSUE TITLE
Overrides don't work for local values

### ISSUE THREAD

**Issue by kenchan0130** [hashicorp/terraform#24051]
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
# sample1.tf
locals {
  test_variable = "sample1 variable"
}

resource "xxxxx" "sample1" {
  xxxx = "This is ${local.test_variable}."
}
```
```hcl
# sample2.tf
locals {
  test_variable = "sample2 variable"
}

resource "xxxxx" "sample2" {
  xxxx = "This is ${local.test_variable}."
}
```

### Debug Output

```
2020/02/07 12:32:13 [INFO] Terraform version: 0.12.20
2020/02/07 12:32:13 [INFO] Go runtime version: go1.13.6
2020/02/07 12:32:13 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2020/02/07 12:32:13 [DEBUG] Attempting to open CLI config file: /Users/myuser/.terraformrc
2020/02/07 12:32:13 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/02/07 12:32:13 [INFO] CLI command args: []string{"plan"}
```

### Crash Output

Nothing

### Expected Behavior

Expects local variable value to be overwritten and evaluated.

### Actual Behavior

The following error occurs:

```
Error: Duplicate local value definition

  on sample2.tf line 2, in locals:
   2:   test_variable = "hoge"

A local value named "sample_variables" was already defined at sample1.tf:2,3-26. Local value names must be unique within a module.
```

### Steps to Reproduce

```
$ terraform plan
```

### Additional Context

Even in Terraform v0.12.19

### References

- https://github.com/hashicorp/terraform/issues/18351

**Comment by jbardin** [comment]
Hi @kenchan0130,

Am [override file](https://www.terraform.io/docs/configuration/override.html) must be named with an `_override.tf` suffix, otherwise it's considered part of the normal configuration. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
