### ISSUE TITLE
Simplify all the things with pass-by-reference

### ISSUE THREAD

**Issue by bionicles** [hashicorp/terraform#24066]
### Current Terraform Version

```
12.20
```

### Use-cases
All

### Attempted Solutions
Status Quo

### Proposal
just one man's opinion, Terraform does a ton of valuable stuff and I rely on it for my startup.

I just want to point out, Terraform often includes stuff like this (hundreds of times per project)

  `iam_instance_profile        = aws_iam_instance_profile.migrator_profile.name`

Which reads as, **instance profile equals instance profile dot name.** That’s annoying because this “.name” label is different for different resources and modules. Sometimes it’s an ID, or an ARN, or an IP, or an Endpoint, or a URI, or a URL. The complexity of figuring out the labels of the labels blows up exponentially as you add resources with different labels. It would be OK if everything were just "ID" or something, but it's not. The "label entropy" is high and this forces the developer to hunt through docs, and it's much less fun than it could be if we could just do pass-by-reference by cultural convention

Would it be possible to switch terraform to be more “pass by reference” ?

Just imagine it were instead

  `iam_instance_profile        = aws_iam_instance_profile.migrator_profile`

This is less typing and more robust to refactoring. If one resource renames something, it’s gonna require fewer people to make code changes. 

A resource IS a resource; **to fix this requires we not conflate resources with resource labels**

Perhaps a bit of pain to convert to this style now would yield decades of better productivity in the long run, but it's not something I can personally control, we'd have to agree as a community to switch to this style

**Comment by jbardin** [comment]
Hi @bionicles,

Terraform early on was attempting to do something along these lines, by having an implicit "ID" for every resource. That however isn't practical, because each provider and resource may have a different concept of what an "ID" is, and many resources may not even have a unique identifier. 

Since there's no way for Terraform to know what a provider or resource considers to be the identifier, there's no way to implicitly convert a resource to the required attribute.

With the new type system however, resource could theoretically allow referencing other resources in their entirety, and the resource could then extract the individual attributes that are needed. This is actually something that can be accomplished now by encapsulating resources in modules. Doing so in individual resources is predicated on the adoption of a new SDK for the provider to make use of the complex structural types available, and updating individual resources to make use of them. This is outside of the scope of Terraform core however, and not something that will be possible in core itself. 

Thanks for the feedback!
