### ISSUE TITLE
TF 12.20 purging unused module that is in use

### ISSUE THREAD

**Issue by jbruett** [hashicorp/terraform#24137]
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

https://gist.github.com/jbruett/6a2c3596c0790404deaad99614f9fbe3

### Expected Behavior

When running terraform init I expect all providers to be downloaded as expected

### Actual Behavior

From the Debug output it looks like it's downloaded, but then purged because TF thinks it's not used.  I have a provider statement and a single resource in the configuration, so it's definitely in use.

### Steps to Reproduce

I have completely removed remote state and local .terraform folder, reinitialized, and it still fails on the plan

### Additional Context

nope

**Comment by jbardin** [comment]
Hi @jbruett,

From the portion of the logs you've provided, it looks like you have a deprecated `providers` block in your `.terraformrc` file pointing to an `aviatrix` binary which may not be compatible with your configuration. Since you are requiring a specific version in your config, you may need to remove that from your `.terraformrc` file in order to get the correct binary.

If that does not rectify the problem, please provide a sample of the configuration being used and the output using `TFLOG=trace`.

Thanks!

**Comment by jbruett** [comment]
thanks for pointing me in the right direction @jbardin.  This plugin was not always official and i think that was leftover from when we were trying to build it ourselves (8-10 months ago).  Killed the rc file and it's all running as expected!
