### ISSUE TITLE
Providers can be configured with unknown values

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform#24131]
### Terraform Version
Latest

### Terraform Configuration Files
https://github.com/ironPeakServices/infrastructure/tree/debug/submodulevars

### Debug Output
https://github.com/ironPeakServices/infrastructure/pull/19/checks?check_run_id=450132650#step:9:655

### Expected Behavior
Submodules using the specified variables.
In my case, I pass my submodule arguments via the submodule variables.

### Actual Behavior
Kubernetes (or any other) provider is not using the passed variables.
A workaround is needed by specifying the provider variables in the root module (here commented for the sake of  this issue): https://github.com/ironPeakServices/infrastructure/blob/debug/submodulevars/versions.tf#L7

### Steps to Reproduce
`terraform plan .`

### Additional Context
Possibly related/causing https://github.com/terraform-providers/terraform-provider-kubernetes/issues/708

### References
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/708

**Comment by jbardin** [comment]
Hi @hazcod,

Thanks for filing the issue. The problem here is that you are attempting to configure a provider using computed values from resources not yet created. A provider cannot refer to anything unknown before  it's configured, (see [Provider Configuration](https://www.terraform.io/docs/configuration/providers.html#provider-configuration)), and the kubernetes provider in your configuration is being configured using the values from `scaleway_k8s_cluster_beta.ironpeakbe-main-cluster` which does not exist on the first apply. 

So the configuration you have is passing the data as expected, and using those values with resources would work as expected, but the provider itself is ignoring the unknown values. This should be better validated during plan, so that providers aren't accidentally configured with incorrect values.

**Comment by hazcod** [comment]
Thanks for confirming @jbardin , this was slowly driving me mad. :-)

**Comment by hazcod** [comment]
@jbardin : just to be sure, is the problem here that `plan` should ignore this provider dependency and this should work during `apply`?

**Comment by jbardin** [comment]
@hazcod, This cannot work if the provider needs to use that configuration during plan or refresh which is often the case. The linked PR would only serve to make this fail more quickly with an error directly referring to the unknown values in the config, rather than risking the provider being configured incorrectly. Unfortunately it's been pointed out that some providers rely on this behavior, and it can be useful in a few cases. We still need more safety here, but that is better handled by the provider SDK than in core.

**Comment by jbardin** [comment]
Closing this is preference for https://github.com/hashicorp/terraform-plugin-sdk/issues/331
