### ISSUE TITLE
-target warning is opinionated

### ISSUE THREAD

**Issue by drewhemm** [hashicorp/terraform#24138]
### SDK version

```
N/A
```

### Use-cases

In agreement with this post :

https://discuss.hashicorp.com/t/target-warning-seems-innapropriate/4091

The warning about using `-target` is opinionated and not related to a syntax error or the use of a feature that is deprecated etc. There are perfectly legitimate use-cases for `-target` and being warned about it upon every invocation of Terraform is intrusive. 

### Attempted Solutions

N/A

### Proposal

An informational warning such as this should have a corresponding flag or config option - for those of us who know why we are using it - to disable the warning. 

### References

https://github.com/hashicorp/terraform-plugin-sdk/pull/182/files

**Comment by adamrt** [comment]
We used terraform for over a year with `-target` during application deploys to target our ASG Launch Template. We filter for new AMI images (via filter) and want to isolate changes. Now everyone gets a page full of warnings on every deploy.

**Comment by syl20bnr** [comment]
To my mind `-target` is an _essential_ feature of Terraform. It is poweful in more complex use cases involving bigger states where splitting in smaller states does not make sense, it offers the possibility to create modules just to allow to target them specifically (i.e. create modules for organization sake only with no reusability).

I hope this warning will disappear as Terraform improves, it makes me a bit worried that Terraform ends up to break `-target` driven states at some point as the warning is rather alarmist.

**Comment by adamrt** [comment]
Just bumping this. Is there a plan to deprecate `-target` or will it just remain a warning? I'd rather get ahead of this by reworking our deploys if it will be deprecated. Thanks.

**Comment by agilgur5** [comment]
I have some Terraform code that requires `-target` (to get around an issue in a 3rd party provider) and it is inside of a library consumed by other users. Without the ability to disable this warning, this means my users get a warning and think there is a bug somewhere, even though we are using `-target` _very_ intentionally.

Please add a flag to disable this warning for users who know what they're doing.

**Comment by apparentlymart** [comment]
Hi all!

This warning is _not_ a deprecation warning but rather a notification of some important implications of using this option, which anyone using it must be aware of. If you've considered what the warning describes and decided that you have one of the situations where the benefits outweigh the costs then this message is not intended to stop you using the option, only to make sure you are aware of the consequences of doing so and which situations it's typically appropriate to use it.

We have no plans to remove the `-target` option. Terraform's deprecation warning messages are explicit that something is deprecated and thus possibly pending removal, but this is not an example of that. This is instead advice on appropriate use of this feature, and thus by implication also advice on situations where we don't recommend to use it.

We don't intend to provide any mechanism to disable the warning because the warning is important context for what Terraform is planning to do or has just finished doing. We strongly suggest, but of course cannot force, that you follow the advice in the message and always follow up any targeted plan with an untargeted plan to ensure that your system is always left in a stable state where the configuration and state are fully converged.
