### ISSUE TITLE
"local-exec provisioner command must be a non-empty string" when using a variable in the destroy command

### ISSUE THREAD

**Issue by baens** [hashicorp/terraform#24174]
### Terraform Version
```
$ terraform -v     
Terraform v0.12.21
+ provider.null v2.1.2
```

### Terraform Configuration Files
```hcl
resource "null_resource" "test" {
    provisioner "local-exec" {
        command = "echo Hello"
    }

    provisioner "local-exec" {
        when = destroy
        command = "echo Goodbye ${self.id}"
    }
}
```

### Expected Behavior
To remove the above resource, I would expect to add the `count = 0` line as my first apply step.

### Actual Behavior
I get the following error:

```
Error: local-exec provisioner command must be a non-empty string
```

### Steps to Reproduce

1. Run `terraform apply` with the above configuration file
1. Add `count = 0` to the resource
1. Run `terraform apply`, error should be recreated 

### Workaround

1. Add `count = 1` to the resource
1. Run `terraform apply`
1. Add `count = 0` to the resource
1. Run `terraform apply`
1. Everything worked out

### Additional Context
The [documentation on the destroy time provisioner](https://www.terraform.io/docs/provisioners/#destroy-time-provisioners) states that to remove the resource is to first add `count = 0`. This is why I was using the `count = 0` method to destroy this resource. 

If I remove the `self.id` from the destroy command, this does not appear. It is only when I reference a variable does this happen.

**Comment by jbardin** [comment]
Thanks for bringing this to our attention @baens. 

The issue you're encountering is that `self` in the provisioner configuration has changed to `null_resource.test[0]` while the state only contains a single `null_resource.test`.  Resources with a count are now consistently addressed differently than those without, and the change first needs to be saved in the state. Applying the config with `count = 1` first will update the state to reflect the desired configuration. 

Since this is an edge case specific only to destroy provisioners, we may be able to catch this without adding another step here.

**Comment by fdmsantos** [comment]
I have the same problem and the workaround doesn't work.

```
resource "null_resource" "parameter" {

  count = 1

  triggers = {
    value  = var.value
    region = var.region
  }

  provisioner "local-exec" {
    command = "aws ssm put-parameter --name '${var.name}' --value '${var.value}' --type SecureString --overwrite --region ${var.region}"
  }

  provisioner "local-exec" {
    when = destroy
    command = "aws ssm delete-parameter --name '${self.triggers.value}' --region ${self.triggers.region}"
  }
}

```
I do terraform apply with count =1 and then change count = 0 and with terraform apply I got :

Error: local-exec provisioner command must be a non-empty string

**Comment by jbardin** [comment]
I've confirmed that this works in correct releases.

Thanks!
