### ISSUE TITLE
Allow reference to locals in (experimental) variable validation

### ISSUE THREAD

**Issue by Notarealbear** [hashicorp/terraform#24187]
### Current Terraform Version

```
Terraform v0.12.20
```

### Use-cases

Simplification of mildly complex validation.
I have a variable defining subnets to be built.
Here, a subnet's nat_route should only refer to a valid subnet with "public = true" and "nat = true"

In this example subnet02 is invalid since jump02 has no nat gateway set.
```
variable "subnets" {
  type = map(map(string))
  default = {
    jump01 = {
      cidr_block = "10.0.1.0/24"
      public     = true
      nat        = true
    },
    jump02 = {
      cidr_block = "10.0.2.0/24"
      public     = true
      nat        = false
    },
    subnet01 = {
      cidr_block = "10.0.101.0/24"
      nat_route  = "jump01"
    },
    subnet02 = {
      cidr_block = "10.0.102.0/24"
      nat_route  = "jump02"
    }
  }
  validation {
    condition = length(
      [
        for item in compact([
          for key, value in var.subnets :
          try(value["nat_route"], "")
        ]) :
        item
        if ! contains(compact([
          for key, value in var.subnets :
          try(value["public"] == "true" && value["nat"] == "true" ? key : "", "")
        ]), item)
      ]
    ) == 0
    error_message = "A nat route does not refer to a public subnet with a NAT gateway."
  }
}
```
Instead, it would be nice to be able to break down the logic with locals. Even if the locals refer only to the variable being validated (which is the case here)
```
locals {
  nat_route_list = compact([
    for key, value in var.subnets :
    try(value["nat_route"], "")
  ])
  nat_subnet_list = compact([
    for key, value in var.subnets :
    try(value["public"] == "true" && value["nat"] == "true" ? key : "", "")
  ])
  invalid_nat_routes = [
    for item in local.nat_route_list :
    item
    if ! contains(local.nat_subnet_list, item)
  ]
}
```
Then use :
```
validation {
    condition = length(local.invalid_nat_routes) == 0
    error_message = "A nat route does not refer to a public subnet with a NAT gateway."
  }
```
### Attempted Solutions

See above. I have worked round this, but the logic becomes a bit unwieldy.

**Comment by joeaawad** [comment]
Could we actually expand this to also allow referencing locals within a variable block in other places? For example, I'd like to be able to do the following (in practice with more complex descriptions of options):

```terraform
locals {
  env_options = {
    dev = "Development"
    stg = "Staging"
    prd = "Production"
  }
}

variable "env" {
  description = "Environment, one of ${local.env_options}"
  type        = string

  validation {
    condition = (
      length(var.env) != 3 ||
      ! contains(keys(local.env_options), var.env)
    )
    error_message = "Invalid env value, options are: ${local.env_options}"
  }
}
```

I think that being able to have these descriptions of the options included in the variable description and validation error message like this would be a huge usability improvement and make the validation code a lot DRYer

**Comment by gillg** [comment]
I have typically the same case with AZs and no workaround possible :/
```hcl
variable "azs" {
  type    = list(string)
  validation {
    condition     = try(index(local.valid_azs, var.azs) >= 0, false)
    error_message = "AZs list should be a list of AZ letter (ex: [a,b,c])."
  }
}

locals {
  valid_azs = ["a","b","c","d","e","f"]
}
```

To complete this issue, a "cross-variables" interpolation should be great also.

```hcl
variable "private_subnets" {
  type    = list(string)
  validation {
    condition     = length(var.private_subnets) <= length(var.azs)
    error_message = "Subnets number should not exced azs defined numbers. You can add a duplicated AZ if you need more subnets in AZ."
  }
}
```

**Comment by desertfoxmb** [comment]
This is really needed for use in modules where some common items like required minimum tags or the examples listed above are enforced by standard. As it is, let's say we need to enforce that any given resource has the required tags defined. We have to resort to something like this. Lots of repetition and error prone and this would just be for one module.

```
variable "tags" {
 type = map(string)

  validation {
    condition = length(setintersection(keys(var.tags), ["application","env", "customer"])) == length(["application", "environment", "customer"])
    error_message = join(" ", [coalesce(format("Missing required tags. Required tags are '%v'.", join("', '",["application", "environment", "customer"])),"")],[coalesce(format("You are missing '%v'.", join("', '", setsubtract(["application", "environment", "customer"], keys(var.tags)))),"")])
  }
}
```

Given that locals can rely on dynamic values determined during apply, I understand the limitation. Perhaps the introduction of a "validation constants" concept could solve for this? The behavior would be similar to that of locals with a limitation that any object, list, etc. defined contain only static data or refer only to other validation constants within the same plan would solve for it. The values to use in the condition could then be deterministic pre-apply.

Couple that with a data resource for them so that they could be defined once in a master plan/state file and retrieved for use in conditions in modules or plans without modules. Then the example above could be rewritten as 

```
validation_locals {
  required_tags = ["application","env", "customer"]
}

variable "tags" {
 type = map(string)

  validation {
    condition = length(setintersection(keys(var.tags), validation_locals .required_tags)) == length(validation_locals .required_tags)
    error_message = join(" ", [coalesce(format("Missing required tags. Required tags are '%v'.", join("', '",validation_locals .required_tags)),"")],[coalesce(format("You are missing '%v'.", join("', '", setsubtract(validation_locals .required_tags, keys(var.tags)))),"")])
  }
}
```

And if we had a data resource and a master plan/state to retrieve them from for an entire org
```
data "validation_locals" "validation_values" {
  value = data.remote_state.master_validation_values.outputs
  description = "Global values for use in variable validation
}

variable "tags" {
 type = map(string)

  validation {
    condition = length(setintersection(keys(var.tags), validation_values.required_tags)) == length(validation_values.required_tags)
    error_message = join(" ", [coalesce(format("Missing required tags. Required tags are '%v'.", join("', '",validation_values.required_tags)),"")],[coalesce(format("You are missing '%v'.", join("', '", setsubtract(validation_values.required_tags, keys(var.tags)))),"")])
  }
}
```

**Comment by klemmchr** [comment]
This feature would be great, any updates on this?

**Comment by Bryoo** [comment]
Any update on this?

**Comment by duxbuse** [comment]
Would love this

**Comment by apparentlymart** [comment]
This request got subsumed into a larger request to support referring to any object in the module where the variable is declared, which became stable in https://github.com/hashicorp/terraform/pull/34955 and is planned for inclusion in the forthcoming Terraform v1.9 release.

I didn't remember this issue at the time and so I missed mentioning it in that PR, but I'm going to close it now retroactively since I believe the more general implementation includes everything that this feature request wanted.

Sorry for missing this before. Thanks!
