### ISSUE TITLE
Terraform.tfvars not being loaded in TFC using the API-driven workflow.

### ISSUE THREAD

**Issue by michaelmerrill** [hashicorp/terraform#24192]
I'm using gitlab ci to create a workspace and upload a config/vars to that workspace. I can upload vars, but the workspace does not (also) pick up the terraform.tfvars in the working directory. Is this intended functionality for TFC?

[Here is an example of the api-driven workflow.](https://gitlab.com/kawsark/gitlabci-terraform-cloud-demo/-/blob/master/.gitlab-ci.yml)

In the example above there is a script that deletes/re-creates variables [here](https://gitlab.com/kawsark/gitlabci-terraform-cloud-demo/-/blob/master/.gitlab-ci.yml#L53). I am currently not using this script in hopes to use just the terraform.tfvars, alas TFC does not import the vars into the workspace.

### Terraform Version
```
0.12.21
```

**Comment by AleksandrTitov** [comment]
I got the same issue, but as far as I understand, the file _"terraform.tfvars"_ is managed through the Terraform Cloud Variables section. To set your own variables use the files _*.auto.tfvars_

**Comment by apparentlymart** [comment]
Hi @michaelmerrill! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

With that said, I believe it _is_ intended that `terraform.tfvars` doesn't work in Terraform Cloud, because the variables configured in the remote workspace take the place of that mechanism when you are using Terraform Cloud. There's some documentation on that in [How Terraform Cloud Uses Variables](https://www.terraform.io/docs/cloud/workspaces/variables.html#how-terraform-cloud-uses-variables). That page also has a section [Loading Variables from Files](https://www.terraform.io/docs/cloud/workspaces/variables.html#loading-variables-from-files) which suggests using `.auto.tfvars` files in order to provide variables automatically from files in your repository. However, I'm not a Terraform Cloud expert so if you run into any surprises with that advice then I'd still recommend contacting the Terraform Cloud support team for additional help.

Thanks again!
