### ISSUE TITLE
In Set diff

### ISSUE THREAD

**Issue by sylr** [hashicorp/terraform#24208]
### Use-cases

We are using terraform to manage our network security rules in Azure and to do so we use `azurerm_network_security_group` from the azurerm terraform provider.

`azurerm_network_security_group` defines `security_rule` using a `TypeSet` :

https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.44.0/azurerm/internal/services/network/resource_arm_network_security_group.go#L56-L175

At the moment any changes in our security rules will be seen by terraform as **remove/create operations** instead of **updates**. **This is really annoying because plans do not reflect the essence of the changes we are about to make.**

The `Schema` struct allows to define a `Set` property which holds a function that is used to generate an uniq id for each Set items.

https://github.com/hashicorp/terraform-plugin-sdk/blob/v1.7.0/helper/schema/schema.go#L206

It seems that this uniq id is currently used to know if Set items need to be created or removed instead of comparing the content of the items .

### Proposal

Use `Schema.Set` property to compare Set items contents.

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/5819

**Comment by jbardin** [comment]
Hi @sylr,

The `Schema.Set` type is part of the legacy provider SDK, which the behavior of which is essentially frozen. Issues can be filed in the [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk/issues) repo, but any changes to the behavior of this package are unlikely. 

There are some workarounds the provider itself can do to fit within the constraints of the current SDK, but the open issues with the provider itself would be the best resource to determine what is feasible there.

**Comment by sylr** [comment]
@jbardin Where does the diff of schema happen ? In this repo's code or in terraform-plugin-sdk's ?

**Comment by jbardin** [comment]
The `helper/schema` package used by the providers now comes from the `terraform-plugin-sdk` repo.

**Comment by magodo** [comment]
@jbardin, two quick questions:

1. Do you think setting the default value for the optional value to zero value to workaround this issue make sense?
2. In some provider, e.g. AzureRM, `TypeSet` is use quite prevalent to hold a set of sub-resources (e.g. `security_rule` in [azurerm_network_security_group](https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html)). The reason for using `TypeSet` instead of `TypeList` might because service return a collection of info with arbitrary order, or other reasons. What is the best type in current SDK for this case?
