### ISSUE TITLE
aws_elb.*.source_security_group fails to resolve properly w/ secgroup

### ISSUE THREAD

**Issue by composer22** [hashicorp/terraform#2420]
When defining a secgroup, tying an ingress port range to a load balancer doesn't work.

```
  ingress {
      from_port = 8080
      to_port = 8080
      protocol = "tcp"
      security_groups = ["${aws_elb.foo.source_security_group}"]
}
```

...

* Error authorizing security group ingress rules: InvalidGroup.NotFound: Unable to find group 'amazon-elb-sg'
	status code: 400, request id: []

Explicit also fails:

security_groups = ["amazon-elb/amazon-elb-sg"]

**Comment by scalp42** [comment]
Related to https://github.com/hashicorp/terraform/issues/601 I believe

**Comment by catsby** [comment]
I think I've found the issue here. The `source_security_group` on the ELB is the _name_ of the security group... the API only returns the name to us.

You cannot use the Security Group _name_ as a reference in the AWS API for security group ingress **unless** you're in EC2 Classic, or the default VPC. 

I have a fix for this, I just need to write a test.

**Comment by catsby** [comment]
Hey all – I've opened #3780 to address this. 
The `source_security_group` is only the name, so it's only useful if you're using EC2 Classic or a Default VPC. 

With my PR I introduce/export `source_security_group_id` as part of the ELBs attributes, so you can use that as an ingress to your security groups .

**Comment by catsby** [comment]
#3780 has been merged! Let me know if you need anything else :smile:
