### ISSUE TITLE
"Provider configuration not present" when provider used in module is removed

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/terraform#24213]
### Terraform Version

```
Terraform v0.12.21
```

### Terraform Configuration Files

base config:
```hcl
module "null_test" {
  source = "./module/"
}
```

module config:
```hcl
provider "null" {}
resource "null_resource" "test" {}
```

### Debug Output

https://gist.github.com/mbrancato/ae19975edd9eee9b03170027c9fe80cc

### Expected Behavior

When removing a module, the provider specified in the module should be able to destroy the resources. This example is not aliased, and has no custom config in the module, yet breaks.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. remove the module from the config
4. `terraform apply`

### Additional Context

I'm concerned how to use this when providers in a module where settings to the provider need to be configured. (e.g. Vault namespace in the Vault provider)

### References

- #21416 - this bug is different it is not aliased.
- #22907

**Comment by jbardin** [comment]
Hi @mbrancato,

While the description of #22907 mentions a provider alias, the issue is the same. By removing the module, you've removed the configuration for the provider. To work around this you need to follow the procedures in [Passing Providers Explicitly](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly.

Thanks!
