### ISSUE TITLE
Facing problem in ValidateFunc in Schema attributes while writing custom provider

### ISSUE THREAD

**Issue by sumitAgrawal007** [hashicorp/terraform#24219]
### Terraform Version

```
Terraform v0.12.21
```

### Terraform Configuration Files

```hcl
"provider_type": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
				Default:  "AWS",
				ValidateFunc: validation.StringInSlice
			},
```

### Expected Behavior

Terraform should accept the provided validator function. The validation.StringInSlice function shouldn't throw an error.

### Actual Behavior

Instead it gives me a compilation error 
Cannot use validation.StringInSlice (type func(valid []string, ignoreCase bool) schema.SchemaValidateFunc) as type SchemaValidateFunc less...

- #6017

-->

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
