### ISSUE TITLE
proxy provider can not be used in module with null_resource

### ISSUE THREAD

**Issue by matti** [hashicorp/terraform#24244]
a module which specifies the minimum version for `null_resource` with:
```
provider "null" {
  version = "~> 2.1"
}
```

can not be commented out because:

```
Error: Provider configuration not present

To work with module.fail.null_resource.default its original provider
configuration at module.fail.provider.null is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy module.fail.null_resource.default, after which you
can remove the provider configuration again.
```

a minimal repro with steps here:
https://github.com/matti/repro-terraform-null-resource-module-proxy

**Comment by jbardin** [comment]
Hi @matti,

The issue here isn't specifically with the `null` provider, as they are all treated the same, it's a side effect of the "proxy" provider configuration. Since the `null` provider has no configuration itself, it's unlikely any user would explicitly pass in the desired empty configuration from outside the module, causing terraform to fall back to treating that block as a complete provider.

If you need to specify a specific version of a provider, you should use the `required_providers` option in the `terraform` block

https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions

```
terraform {
  required_providers {
    null = "~>2.1"
  }
}
```
