### ISSUE TITLE
Multi cloud support in single .tf file

### ISSUE THREAD

**Issue by Raphael-AWS** [hashicorp/terraform#24279]
Team,

I am trying to create infrastructure in both aws and azure using my jenkins pipeline.

Like i will give a parameter called provider . If i give aws, it should create infra in aws and if it is azure then it should create in azure.

I thought i can have 2 .tf files (One for aws and one for azure), If there is an option to call "terraform plan <file.tf> it would be great, i can use variable and acheive it.

Do terraform supports multi cloud in single .tf file?

Any thoughts on the same? Please advise

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
