### ISSUE TITLE
Failed to save state: Error uploading state: Conflict

### ISSUE THREAD

**Issue by wroberts** [hashicorp/terraform#24294]
### Terraform Version

```
0.12.21
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "ArtNight"
    workspaces {
      name = "artnight-prod-nl"
    }
  }
}
```

### Crash Output

```
Failed to persist state: Error uploading state: Conflict

This workspace is not locked and will only accept state uploads
when locked
```

### Expected Behavior

Until two days ago, terraform correctly stored state in the remote backend.  I'd like this to work again.

### Actual Behavior

I'm getting this error on `terraform apply`:
```
Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

When I try to do `terraform state push errored.tfstate`, then I get:
```
Failed to persist state: Error uploading state: Conflict

This workspace is not locked and will only accept state uploads
when locked
```

I've tried locking and unlocking the state on app.terraform.io, and force-pushing the state, but everything just returns this error.

Is there something else I can try?

**Comment by wroberts** [comment]
Workaround: Delete the workspace and re-initialise it with the current state.

1. Do `terraform apply`. This fails and makes a file called `errored.tfstate`.
2. Go to https://app.terraform.io, and delete the workspace.
3. Run `terraform init` to recreate the workspace.  On https://app.terraform.io, set execution mode to local again.
4. Run `terraform state push errored.tfstate` to update the remote state.

**Comment by apparentlymart** [comment]
Hi @wroberts! Thanks for reporting this and sorry for the delayed response.

This seems to be an error coming from Terraform Cloud's API rather than from Terraform CLI directly. We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
