### ISSUE TITLE
Module call providers argument does not support override files

### ISSUE THREAD

**Issue by ophelan** [hashicorp/terraform#24291]
### Terraform Version
```
Terraform v0.12.21
+ provider.aws v2.51.0
```

#### main.tf
```
provider "aws" {
  alias   = "cluster"
  region  = "us-east-1"
  assume_role {
    role_arn      = "arn:aws:iam::REDACTED:role/atlantis-preprod"
    session_name  = "terraform-k8s"
  }
}

provider "aws" {
  alias   = "cluster-local"
  region  = "us-east-1"
  profile = "RandomPowerUser"
}

module "testcluster" {
  source = "./core"

  providers = {
    aws = aws.cluster
  }
}
```

#### override.tf
```
module "testcluster" {
  providers = {
    aws = aws.cluster-local
  }
}
```

#### core/main.tf
```
resource "aws_security_group" "testsg" {
  name        = "testsg"
  vpc_id      = "REDACTED"
}
```

### Debug Output
https://gist.github.com/ophelan/3f2c2e55643b13667fe8511e2ee99039

### Expected Behavior
If a module's provider map is overridden, I expect the providers from the overrides (cluster-local) to be used, not the providers from the original module definition (cluster).

### Actual Behavior
The provider from the orignal module definition (cluster) was used. I'm unable to assume that role, so the execution failed.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
I utilize a TF repo via Atlantis as well as locally at times. The AWS provider resource for those two scenarios differs. In this case I'd like to use the AWS profile definition if enabled via an override, instead of the AWS role assumption that is the default.

So long as the contents of the module calls the provider, this behavior is exhibited. This simple example creates an AWS security group.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @ophelan.

From looking at the override implementation for `module` blocks it looks like there is no handling of the `providers` argument there at all:

https://github.com/hashicorp/terraform/blob/6b8d389d5757971de8c1f2b26ef9913f6b0cd879/configs/module_merge.go#L144-L179

So at this time overriding that `providers` argument is not supported at all. The override files mechanism is not commonly used, so unfortunately this has likely been missing right back to the introduction of that argument and nobody has noticed until now. :confounded: 

It looks like it should be possible to implement this, though. Per the usual rules for overriding, I'd expect the merge function to check if `len(omc.Providers) > 0` and, if so, take the value from `omc.Providers` instead of the value from `mc.Providers`.
