### ISSUE TITLE
'terraform fmt' does not correctly format variables with map as default value

### ISSUE THREAD

**Issue by invidian** [hashicorp/terraform#24303]
### Terraform Version
```
$ terraform version
Terraform v0.12.23
```

### Terraform Configuration Files
```hcl
variable "tags" {
  type        = map
  description = "Optional details to tag on AWS resources"
  default     = {
    "ManagedBy" = "Lokomotive"
    "CreatedBy" = "Unspecified"
  }
}
```

### Expected Behavior

Running `terraform fmt` should not produce any diff.

### Actual Behavior

`terraform fmt` formats the code to following:
```console
$ terraform fmt -diff test.tf 
test.tf
--- old/test.tf
+++ new/test.tf
@@ -1,7 +1,7 @@
 variable "tags" {
   type        = map
   description = "Optional details to tag on AWS resources"
-  default     = {
+  default = {
     "ManagedBy" = "Lokomotive"
     "CreatedBy" = "Unspecified"
   }
```

**Comment by carlosjgp** [comment]
I'm also seeing this... is stopping us to adopt GitHub actions to check Terraform format on PRs

**Comment by danieldreier** [comment]
@carlosjgp we treat 👍 as votes on issues, so if you use that emoji reaction on the parent issue that will help us prioritize it more than a comment.

**Comment by carlosjgp** [comment]
> @carlosjgp we treat  as votes on issues, so if you use that emoji reaction on the parent issue that will help us prioritize it more than a comment.

Thanks for letting me know @danieldreier I added my :+1: to the initial comment

**Comment by apparentlymart** [comment]
Hi @invidian,

What you saw here is the intended behavior of `terraform fmt`. Specifically, the alignment of equals signs only happens for consecutive runs of _single-line_ arguments. Multi-line arguments are considered to be an entirely separate "group" (with only one item) for alignment purposes, because the benefit of easily scanning over the values doesn't apply when the value itself isn't positioned relative to the equals sign anyway.

As with all of the `terraform fmt` formatting decisions, this is a subjective and therefore essentially arbitrary decision based on tradeoffs made by the original implementer, and it's unlikely to change because that would cause changes for everyone who had previously formatted examples like this with `terraform fmt` in earlier versions. The bar for changes to existing `terraform fmt` layout behaviors is very high, and would typically need to have a strong and objective (rather than subjective) justification to warrant causing diffs for all existing Terraform configurations after upgrading.

**Comment by invidian** [comment]
Thanks for the explanation @apparentlymart. It make sense. Closing.
