### ISSUE TITLE
changelog for 0.12.23 is empty

### ISSUE THREAD

**Issue by LucaFilipozzi** [hashicorp/terraform#24302]
I mean, I know why you released 0.12.23 because I opened #24301 

I think it would have been good to close that bug with the release of 0.12.23 and included information in the changelog.

**Comment by jbardin** [comment]
Hi @LucaFilipozzi 

Thanks for taking the time to file the issues.

The discrepancy was caught during the release process, and rectified before any new GitHub issues had been triaged. Since this was a change to the release process, and there was no code change in a PR, there was initially no changelog entry. A note about the version error was added after the fact to the changelog in the v0.12 branch.

Thanks!
