### ISSUE TITLE
The terraform docs do not explain what an "Error: Cycle" means.

### ISSUE THREAD

**Issue by flybd5** [hashicorp/terraform#24300]
I cannot find the explanation of what an "Error: Cycle" means inside the Terraform docs. ??

**Comment by meetsdeep** [comment]
It analyzes the dependencies between your resource blocks, data blocks, and other configuration constructs in order to determine a suitable order to process them so that the necessary input data will be available.

For example, consider the following example:

resource "resource" "test1" {
}

resource "resource" "test2" {
  triggers = {
    test1 = null_resource.test1.id
  }
}

Terraform should  analyze the above piece of code  and notice that the configuration of resource.test2 contains a reference to resource.test1, and therefore the operations resource.test1 should happen before resource.test2

Now consider below example:

resource "resource" "test1" {
  triggers = {
    test2 = resource.test2.id
  }
}

resource "resource" "test2" {
  triggers = {
    test1 = resource.test1.id
  }
}

So we can see 'two happen relationship' in above configuration.

The two statements above contradict one another- resource.test2 cannot be processed both before and after resource.test1. Terraform will return back  to this situation by reporting a dependency cycle, using the error message :

Cycle: null_resource.test1, null_resource.test2

**Comment by flybd5** [comment]
Much simpler explanation: It is a flag for a circular reference. It is not a cycle, which has a different formal definition. The concept has been around for 50 years and there is no reason to invent a stupid new word or phrase for it. Thanks.

**Comment by jbardin** [comment]
Hi  @flybd5 

Thanks for you feedback. A "cycle" is the generally accepted term for this situation in a directed acyclic graph: https://en.wikipedia.org/wiki/Cycle_(graph_theory). I'm going to combine this into a more general issue (#26150) to improve the cycle detection, debugging and documentation for users.
