### ISSUE TITLE
aws_network_interfaces datasource cannot create dependency without the use of depends_on

### ISSUE THREAD

**Issue by dsantanu** [hashicorp/terraform#24314]
### Terraform Version
```
Terraform v0.12.23
+ provider.aws v2.49.0
+ provider.null v2.1.2
```

### Terraform Configuration Files
```hcl
// Create: Network load-balancer (NLB)
resource "aws_lb" "network" {
  load_balancer_type = "network"
  .........
}

resource "null_resource" "nlb_subnets" {
  triggers = {
    lb_snets = join(",",aws_lb.network.subnets)
  }
}

// Get the IP address of the LBs
data "aws_network_interfaces" "this_elb" {
  filter {
    name   = "description"
    values = ["ELB net/${aws_lb.network.name}/*"]
  }
  ......
  filter {
    name   = "subnet-id"
    values = split(",",null_resource.nlb_subnets.triggers.lb_snets)
  }
  #depends_on = [aws_lb.network]
}
```
### Debug Output
```
Error: no matching network interfaces found

  on ../../modules/nlb/data.tf line 9, in data "aws_network_interfaces" "this_elb":
   9: data "aws_network_interfaces" "this_elb" {
```
### Expected Behavior
`data.aws_network_interfaces.this_elb` should wait for `aws_lb.network` to run first before executing and will return the ids of the above network_interface.

### Actual Behavior
Without a explicit `depends_on` the _aws_network_interfaces_ datasource cannot find any matching network interface. There are two dependencies established in the data block, through the `description` and the `subnet-id` filters but it only works if depends_on meta-argument NOT commented out.

**Comment by mildwonkey** [comment]
Hi! Thank you for reporting this issue, and I am sorry that you've experienced it.

Can you share the trace-level logs from a terraform run with this issue (`TF_LOG=trace terraform apply`)? Preferably shared as a gist, with any sensitive information removed first.

**Comment by mildwonkey** [comment]
@dsantanu : I have another question for you! If both the `name` and `subnets` referenced in the datasource are taken from variables set in your configuration, instead of computed from the resource `aws_lb`, then the data source has a complete config already and will be read during refresh. If this is the case, then including explicit `depends_on` is indeed the correct (and expected) solution.
 
If that's _not_ the case, it's possible we have an eventual consistency problem with the resource itself. This can happen when the resource is successfully created but not all of the attributes are immediately populated by the provider.

**Comment by dsantanu** [comment]
@mildwonkey please find the log here:
https://gist.github.com/dsantanu/5e96e4875d2df7104f2eb970a9d7cac6

I also found that very similar thing was reported last year in Oct. 
https://github.com/hashicorp/terraform/issues/11806#issuecomment-546911263

-S

**Comment by dsantanu** [comment]
@mildwonkey 
I didn't quite understand your second comment/question, but here is the what I have:

```
// null-resources for resource dependency
resource "null_resource" "nlb_subnets" {
  triggers = {
    lb_snets = join(",",aws_lb.network.subnets)
  }
}

// Create: Network load-balancer (NLB)
resource "aws_lb" "network" {
  name               = "${var.vpc_names[var.idx]}-${var.inst_role}"
  internal           = var.nlb_internal
  load_balancer_type = "network"
  subnets            = var.nlb_internal ? [for sid in range(length(var.subnet_ids)) : var.subnet_ids[sid]] : data.aws_subnet_ids.public.ids
  enable_deletion_protection       = false
  enable_cross_zone_load_balancing = true
  depends_on                       = [null_resource.public_subnet_ids]

  tags = merge(
    var.common_tags,
    { "Name" = "${var.vpc_names[var.idx]}-${var.inst_role}" }
  )
}
```
So, if I understood correctly what you mean, the `lb_snets` is purely computer and the `name` you can say partially provided (through the .tfvars), the `var.vpc_name` is actually supplied as: `vpc_names = module.vpc.vpc_names` in the root module, where name of the vpc is supplied and the from there, rest of the names are computer. Not sure if I able to make it any clearer for you though.

-S

**Comment by jbardin** [comment]
Hi @dsantanu,

Thanks, that configuration explains the issue. Because `name` and `subnets` are both defined in the configuration or coming from another data source, the data source isn't waiting on any values from the resource and will be read immediately.

The issue you linked is also correct, in that using `depends_on` within a data source will cause it to show it always has to be read during apply, because there's no way to determine _why_ it depends on the other resource. 

One normally doesn't use a data source to look up attributes of a resource, rather you get them directly from the resource. If the attributes are not available, and the data source must depend on the resource, you need to make it reference a computed attribute somehow. If this is a common requirement, and the resource does not have a way to extract the value or reference it, an issue can be filed with the AWS provider.

One workaround might be to combine the config value with a computed value, and extract it back out later.

```
locals {
  lb_id_name = "${awl_lb.network.id}|${aws_lb.network.name}"
  lb_computed_name = split("|", local.lb_data)[1]
}

data "aws_network_interfaces" "this_elb" {
  filter {
    name   = "description"
    values = ["ELB net/${local.lb_computed_name}/*"]
  }
  ...
```

Since this is working as expected, and the `depends_on` issue is otherwise being tracked, I'm going to close this out. If you have more questions about how to structure your configuration, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
