### ISSUE TITLE
Error: Error creating subnet: InvalidSubnet.Conflict: The CIDR 'x.x.x.x/x' conflicts with another subnet

### ISSUE THREAD

**Issue by smaillns** [hashicorp/terraform#24317]
I'm meeting the error while trying to provision a new infrastructure

> terraform apply 

 any suggestion please

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help. Thanks!
