### ISSUE TITLE
CFN Signal Not Working with Terraform

### ISSUE THREAD

**Issue by StealthNinj4** [hashicorp/terraform#24359]
### Details
I've got an ASG defined within a Cloudformation resource, I'm using CFN as I need to use Creation and Update policies. 

I have the launch configuration defined as a "aws_launch_configuration" resource. I have attached the 'cloudformation:SignalResource' to the instance profile of the launch config.

### Terraform Version
```
Terraform v0.12.23
```

### User Data
```
#!/bin/bash

set -x

yum update -y

yum install -y aws-cfn-bootstrap 

echo "Region: ${aws_region}, Stack: ${aws_stackname}" > details.txt

//Everything above runs, but not below

/opt/aws/bin/cfn-signal -s true \
                        --region ${aws_region} \
                        --stack ${aws_stackname} \
                        --resource ASG  

echo "SUCCESS" > success.txt
```

### Attempted Solutions
The signalling works when done on Cloudformation alone, but I want to use both CFN and Terraform.
I've tried hard coding instead of using the variables and that doesn't work either.
I can signal manually when I SSH into the instance, so theoretically it should work when done within userdata.

**Comment by jbardin** [comment]
Hi @StealthNinj4 

This doesn't seem to be directly related to Terraform itself. Since this is supplied via `user_data`, there's not much that terraform can do to change the behavior. I would start by making sure that the script is being formatted correctly, and the variable replacements are done in the context you think they are. Maybe add some debugging output to the script itself. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
