### ISSUE TITLE
Terraform fails at calculating count argument due to wrongfully assuming it needs to wait for an apply

### ISSUE THREAD

**Issue by josemaia** [hashicorp/terraform#24369]
### Terraform Version
```
Terraform v0.12.21
+ provider.azurerm v1.36.1
+ provider.null v2.1.2
+ provider.vault v2.5.0
```

### Terraform Configuration Files
Placed it in a gist: https://gist.github.com/josemaia/61cd7cd8b4941b1458a392e712dad488

### Debug Output
Having some trouble reproducing the scenario so I was unable to obtain the log, since I fixed the case I observed this in.

### Expected Behavior
When applying, if the Vault Token has expired, we will need to create a new one. Only after that the count argument should be validated, since there is an explicit dependency in the resource.

### Actual Behavior
Every time the token expires, I am forced to do local terraform applies to all resources using it, unless I remove the dependency from count.

After switching the count to ```  count      = (var.client_token_destination != "") ? var.number : 0```, the problem disappears.

### Steps to Reproduce
1. Define a resource of type "vault_token" and use it as a parameter to configure a "count" argument inside a module
2. Let the vault_token expire
3. Perform a new terraform apply and observe you get an error

### Additional Context
This may be a misunderstanding on my side of how the dependency graph works, but in that case is there anything I can do to restrict that count argument, or at least a documentation improvement that would allow me not to fall into this pit?

**Comment by jbardin** [comment]
Hi @josemaia,

This is the expected behavior, because the `local.config_token_flag` is being derived from the output of the `vault_token` resource. If the resource still needs to be created, then the value of `var.client_token` is unknown during the plan, and hence the value of `local.config_token_flag` will be unknown as well.


While we can sometimes help with certain simple problems here, if you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by josemaia** [comment]
Thank you, as I was typing the issue out that was the feeling I got.
