### ISSUE TITLE
Replacing a `google_compute_instance` requires two applies to replace any `google_compute_network_endpoint` that references it

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform#24363]
### Terraform Version

```
v0.12.19
```

### Terraform Configuration Files

```hcl
data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_network" "default" {
  name                    = "neg-network"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "default" {
  name          = "neg-subnetwork"
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.default.self_link
}


resource "google_compute_address" "endpoint-instance-internal" {
  name         = "endpoint-instance-internal"
  subnetwork   = google_compute_subnetwork.default.self_link
  address_type = "INTERNAL"
  address      = "10.0.0.3"
  region       = "us-central1"
}

resource "google_compute_instance" "endpoint-instance" {
  name         = "endpoint-instance"
  machine_type = "n1-standard-1"
  zone = "us-central1-a"

  metadata_startup_script = "echo 'its_changed_again'"

  boot_disk {
    initialize_params {
      image = data.google_compute_image.my_image.self_link
    }
  }

  network_interface {
    subnetwork = google_compute_subnetwork.default.self_link
    network_ip = google_compute_address.endpoint-instance-internal.address
    access_config {
    }
  }
}

resource "google_compute_network_endpoint_group" "group" {
  name         = "my-lb-neg"
  network      = google_compute_network.default.self_link
  subnetwork   = google_compute_subnetwork.default.self_link
  default_port = "90"
  zone         = "us-central1-a"
}

resource "google_compute_network_endpoint" "default-endpoint" {
  network_endpoint_group = google_compute_network_endpoint_group.group.name

  zone       = "us-central1-a"
  instance   = google_compute_instance.endpoint-instance.name
  port       = google_compute_network_endpoint_group.group.default_port
  ip_address = google_compute_instance.endpoint-instance.network_interface[0].network_ip
}
```

### Debug Output

https://gist.github.com/megan07/4518dec548d35285302ff7e8357ef9af

### Expected Behavior
The initial plan should have known the relationship between the instance resource and the network endpoint group resource and shown both of them needing to be destroyed and recreated.

### Actual Behavior
The plan did not show that the network endpoint group needed a change

### Steps to Reproduce
1. `terraform apply` the above
2. Modify the `metadata_startup_script` attribute of the `google_compute_instance` resource
3. `terraform apply` to recreate the instance
4. `terraform plan` to see that `google_compute_network_endpoint` needs to be created again

### References
Downstream issue: https://github.com/terraform-providers/terraform-provider-google/issues/5798

**Comment by jbardin** [comment]
Hi @megan07,

In the configuration shown here, replacing the `google_compute_instance` doesn't change any of the values referenced in the `google_compute_network_endpoint`, so there is no change planned for the `google_compute_network_endpoint`. I'm not certain what that resource represents on the backend, but the behavior seen by terraform is that the `google_compute_network_endpoint` is effectively deleted outside of terraform after the instance is replaced. This is why the next plan is to create what appears to be the same `google_compute_network_endpoint` again, because that resource has disappeared when the state is refreshed.

If the `google_compute_network_endpoint` resource had referenced a computed value from the instance, there would have at been an attempt to plan a change for that resource, and the ability for the provider to decide to plan its replacement. I'm not familiar enough with the resource details to know if any of the existing attributes would be sufficient for this, or a new one needs to be added to create the required dependency, but either way it is something that needs to be done by the provider itself.

Let me know if you have any more questions.
Thanks!
