### ISSUE TITLE
locals not working within variables

### ISSUE THREAD

**Issue by prashanth-sams** [hashicorp/terraform#24376]
```
locals {
  cool_style = {
    palette = "cool"
    type    = "solid"
    width   = "normal"
  }
  orange_style = {
    palette = "orange"
    type    = "solid"
    width   = "normal"
  }
}

variable "query_timeseries" {
  default = [
    {
      q     = "avg:xx.xxxx{xxx:xx}"
      type  = "bars"
      style = local.cool_style
    },
    {
      q     = "avg:xx.xxxx{xxx:xx}"
      type  = "bars"
      style = local.orange_style
    }
}
```

Unable to re-use the declared variable in .tf file

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/F8qmh.png

**Comment by prashanth-sams** [comment]
**What I need?:**
I need to declare a variable by injecting an existing variable in it

**Comment by jbardin** [comment]
Hi @prashanth-sams,

Sorry about the confusion here, but the error is correct, and variables cannot contain interpolations. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
