### ISSUE TITLE
Puppet provisioner needs support for Bolt 2.x

### ISSUE THREAD

**Issue by nextworking** [hashicorp/terraform#24414]
The bolt task puppet_agent::install fails due to a deprecated bolt 2.x argument "--nodes"

Error: puppet_agent::install failed: Bolt: "bolt task run --nodes ssh://nodename.mydomain.com -u root --run-as root --no-host-key-check --format json --connect-timeout 120 puppet_agent::install": Unknown argument '--nodes'
: exit status 1

Workaround: Downgrade to Bold 1.49.0

**Comment by dutch** [comment]
I really wouldn't like to step outside my system package manager in order to downgrade my bolt installation, so this would be very useful, as without it I can't use the immensely handy Puppet provisioner.

**Comment by thomasxd24** [comment]
how do you downgrade bolt?

**Comment by pkolyvas** [comment]
In [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997) we announced the deprecation of tool-specific vendor provisioners. Recently, we added a deprecation notice these provisioners in `0.13.4`. 

On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins. 

I realise this issue is overdue for a response and as the product manager of Terraform, that onus is on me for having left these untouched while we developed our near-term plan. 

The long term strategy here is less clear than we'd like, but for the time being I'd encourage the community of Terraform provisioner users and developers (who might also be reading this) to follow in the footsteps of the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible).

Creating provisioner plugins and installing provisioner plugins manually is more involved. My personal hope here is that the ability to improve, fix and repair these tools without us blocking their development, much like providers, will help make a strong case for what's next. 

There are also some technical hurdles to cross.  The Terraform plugin SDK does not support provisioners and so moving beyond the deprecation will require more concrete plans. We’d like to base those plans, in part, on the feedback we receive. I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle.

We didn't make this decision lightly, and removing or no longer supporting features is not ideal for anyone who uses and depends on them. To that end, my door is always open. I'd invite anyone interested or concerned to write me or schedule some time with me to talk about these changes moving forward.
