### ISSUE TITLE
destroy -force should not ask for user input when variables have values or defaults

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2443]
The apply command isn't asking for input, but the destroy command (even when using -force) is asking for input even though all variables are either supplied or have default values.

**Comment by mitchellh** [comment]
I can't reproduce this with the following config: 

```
variable "foo" {
    default = "bar"
}

resource "null_resource" "foo" {}
```

Apply asks for a var value. If I set it in a `terraform.tfvars`, it doesn't. And neither does destroy. 

Can you show us a config to repro this? Thanks!

**Comment by xelarate86** [comment]
Just wanted to touch back on this - it still happens if there is no default set.

**Comment by danieldreier** [comment]
@xelarate86 this issue has been pending a clear reproduction case since 2015. If you have a reproduction case it would be tremendously helpful if you could share it here!

I re-ran the same reproduction case that @mitchellh posted back in 2015 and got the same results on terraform 0.12.17 - it seems to work as expected and I can't reproduce the problem. 

If you're still seeing this issue with a recent (e.g. 0.12.x) version of terraform, please post a terraform config and your terraform.tfvars, the exact commands you're running and their output, and any details of your workstation (e.g. linux vs os x).
