### ISSUE TITLE
GitLab-managed state storage (backend)

### ISSUE THREAD

**Issue by ash2k** [hashicorp/terraform#24439]
### Use-cases

Please see https://gitlab.com/groups/gitlab-org/-/epics/2673

> As a DevOps engineer, in order to quickly get started with a Terraform project, I would like to use a GitLab managed Terraform state.
If GitLab CI is used to manage infrastructure using Terraform, it would be convenient if the Terraform state could be stored in GitLab itself instead of having to set up a traditional remote backend (eg. on Amazon S3).

### Attempted Solutions

HTTP backend could be used for that.

### Proposal

Having a native GitLab backend would be more expressive and avoid all the low-level HTTP boilerplate.

There are at least two options of how to implement it.

1. Put GitLab backend API client code into https://github.com/xanzy/go-gitlab and then use it from a Terraform backend implementaion in `backend/remote-state/gitlab`.
2. Add all code as a backend implementation in `backend/remote-state/gitlab` (not adding `xanzy/go-gitlab` as a dependency).

GitLab's preference is to move forward with option 2. What do Terraform maintainers think?

@svanharmelen will you accept a contribution of GitLab's Terraform backend API client to https://github.com/xanzy/go-gitlab?

I'm new to Terraform so I might be completely misunderstanding how things work so please bear with me :)

### References

- I'm tracking my work here https://gitlab.com/gitlab-org/gitlab/-/issues/207348
- The overall epic is here https://gitlab.com/groups/gitlab-org/-/epics/2673

**Comment by svanharmelen** [comment]
@ash2k I'm fine with adding a few API calls to the `go-gitlab` package in order to support Terraform specific API calls. No problem 👍 

As for the two options you mentioned (I've been a long time contributor to Terraform and also worked for HashiCorp for about a year, so I have an opinion 😉), I think that the most common solution is to reuse an existing API client vs writing a new dedicated client from scratch.

If you look at the existing `remote-state` backends, they all have a `client.go` file that is used as a tiny wrapper around an existing API client. The advantage is of course that things like rate limiting, HTTP retries and all logic to create a client and do authentication already exist and if they need to be updated in the future, they can be updated in one place instead of two.

But of course this all doesn't mean that option 1 isn't a valid solution. If you only need a couple of API endpoints and the client (e.g. auth, retry logic, error handling) is straight forward or not needed, then option 1 can of course also work.

If not having control over `go-gitlab` is a worry for them, I'm fine to give them access or even to move over my client to them...
