### ISSUE TITLE
[salt-masterless provisiones] Allow more salt command options

### ISSUE THREAD

**Issue by arbulu89** [hashicorp/terraform#24452]
### Current Terraform Version
Terraform v0.12.23

### Use-cases
I have been trying to use the `salt-masterless` provisioner but I have found it a bit limited in the sense that only `highstate.apply` and `state.sls` are available.
I have a really simple use case where I need to run `state.highstate saltenv=predeployment` but with the current implementation this is not possible.

### Attempted Solutions
Cannot be solved

### Proposal
I see 2 potential solutions:

1. Update the usage of `custom_state` parameter to allow the usage of other forms (`state.highstate saltenv=predeploymen` for example, or any other salt option). This will most probably create non backward compatible issues.

2. Add an additional parameter to provide this feature. `custom_call` or similar. The implementation is really simple in this case.

The involved code is here:
https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/salt-masterless/resource_provisioner.go#L473

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested.

For the time being, the best option if you want to see this built, is to build a standalone provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. 

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.

**Comment by arbulu89** [comment]
@danieldreier Understood. It's not a big deal I already have some workarounds.
Thank you for coming back to answer anyway.
