### ISSUE TITLE
How to skip dependency checks when destroying aws infra

### ISSUE THREAD

**Issue by ado120** [hashicorp/terraform#24459]
### Terraform Version

```
Terraform v0.12.21
```

### Expected Behavior

Expected Terraform to destroy an ec2 instance despite the ami no longer existing.. Is there a way to skip this dependency check as the ami being valid or not has no way of affecting an instance being destroyed?

### Actual Behavior

Terraform spit out this error when attempting to destroy:
```
Error: Your query returned no results. Please change your search criteria and try again.


  on get_ami/main.tf line 1, in data "aws_ami" "selected_ami":
   1: data "aws_ami" "selected_ami" {
```

Basically, we spun up infrastructure using an ami lookup. I deleted the ami manually and now trying to destroy the infrasture. Terraform depends on the ami existing in order to destroy which doesn't really make sense to me.. Is there a way I can skip this dependency check?

**Comment by jbardin** [comment]
Hi @ado120,

This looks like it might be solved by using `-refresh=false` to prevent the reading of the data source. That however may depend on the configuration and what required values from that data source. If you cannot bypass this, you may need to modify the configuration to prevent looking for that resource. This may also be something that is will be better handled with the next major release of terraform. 

If this is still not resolvable, please feel free to file a new issue with a complete example, and we can take a look. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
