### ISSUE TITLE
Doesn't like when AWS Server Certificates already exist

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2447]
I've noticed a few circumstances where Terraform doesn't like working server certificates when they already exist on AWS. The primary one that immediately comes to mind is the creation/modification of ELB's and resources dependent on the ELB. When bringing up the infrastructure on a first run, it won't create the ELB and related subnets. When the infrastructure already exists, it'll just prevent the creation of the ELB.

The error thrown is:
```
[WARN] Error uploading server certificate, error: EntityAlreadyExists: The Server Certificate with name 2014-wildcard-tableprojectqa already exists.
```

Are there any files or examples I can provide to help further debug this?

**Comment by mitchellh** [comment]
AWS requires that that name be unique. If you had created that certificate with a prior TF run, TF won't attempt to create it again. But if the state file is lost, Terraform will not automatically discover it from your existing infra, and it will attempt to create it again. This is so there is a clear separation of TF-managed resources and non-TF managed resources (that TF won't touch).

Pairing this with the other issue you created, I believe that somehow you deleted your TF state, or changed to a diff TF config in another folder and therefore had no state. 

Otherwise, this would be a serious bug indeed. If you can give us the following steps to reproduce it, then we'll take a look:

1. Config to use (with no prior state)
2. `terraform apply`
3. Change config (or maybe no change needed)
4. `terraform apply` and error in the same directory

**Comment by johnhamelink** [comment]
Hey folks,

I seem to be having the same issue, however the correct data is inside the `.tfstate` file, and it matches from what I see from running `aws iam list-server-certificates`

```
<snip>
        {
            "path": [
                "root",
                "ssl"
            ],
            "outputs": {
                "lorem": "arn:aws:iam::440111111111:server-certificate/staging_asterisk_example_com_app_cert"
            },
            "resources": {
                "aws_iam_server_certificate.asterisk_example_com": {
                    "type": "aws_iam_server_certificate",
                    "primary": {
                        "id": "AAAAAAA11ADAAA111AA111",
                        "attributes": {
                            "arn": "arn:aws:iam::440111111111:server-certificate/staging_asterisk_example_com_app_cert",
                            "certificate_body": "a11aa11aaa11aa111111a111a1a1a11a1111a1a1",
                            "certificate_chain": "111111a1a11aa111aaaa11A1111111a11a11111",
                            "id": "AAAAAAA11ADAAA111AA111",
                            "name": "staging_asterisk_example_com_app_cert",
                            "path": "/",
                            "private_key": "111a1a1a11a11111111111111a1aaa1a1111a1a1"
                        }
                    }
                }
            }
        },
<snip>
```

```
<snip>
        {
            "ServerCertificateId": "AAAAAAA11ADAAA111AA111",
            "ServerCertificateName": "staging_asterisk_example_com_app_cert",
            "Expiration": "2017-08-13T18:52:10Z",
            "Path": "/",
            "Arn": "arn:aws:iam::440111111111:server-certificate/staging_asterisk_example_com_app_cert",
            "UploadDate": "2016-02-08T14:16:24Z"
        },
<snip>
```

**Comment by kbroughton** [comment]
This may 
terraform destroy -target aws_iam_server_certificate.your-elb-certificate
