### ISSUE TITLE
Launch an instance then stop it

### ISSUE THREAD

**Issue by frsh-augustin** [hashicorp/terraform#24499]
### Current Terraform Version

```
0.12.7
```

### Use-cases

I know we can't use terraform to control if  an instance is running or stopped, if there is any particular reason why does terraform offer this ability?
### Attempted Solutions

Add an attribute like "state" to control if an instance is running or stopped

**Comment by pkolyvas** [comment]
Hi @frsh-augustin,

Thanks for your suggestion. 

At first glance it would seem this would be provider/service specific as the idea of an instance's state being running/not doesn't apply to all resources Terraform manages.

If this is regarding a specific provider or set of providers, I'd recommend filling the enhancement request with those providers. 

While I'm going to close this issue, I'd love to understand more of your workflow however in order to develop a better idea of use case here, so please feel free to contact me. My info is available on my Github profile.
