### ISSUE TITLE
Can't delete everything in remotestate 

### ISSUE THREAD

**Issue by zhaoyi0113** [hashicorp/terraform#24509]
I am using terraform v0.12.9. My remote state is saved on s3 bucket. I tried to remove all resources by running this command: `terraform rm -state .terraform/terraform.tfstate ""`, but got the error: 
```
Error: Variable name required

  on  line 1:
  (source code not available)

Must begin with a variable name.


Error: Invalid character

  on  line 1:
  (source code not available)

Expected an attribute access or an index operator.
```

It is hard to find out what's going on here. Does it support removing all resources? Did I make anything wrong with the command?

**Comment by danieldreier** [comment]
Hi @zhaoyi0113 are you running terraform with just the state file but no source code?

**Comment by zhaoyi0113** [comment]
Hi @danieldreier , the source code is in a separate folder `infra`. Do I need to specify this folder when run this command? The help menu doesn't say any parameters about source code folder.

**Comment by danieldreier** [comment]
From the source folder, where you'd normally run terraform, can you please try running:

 `terraform state rm ""`

This should remove all stored state - you don't need to try and use a local state file as input for this.

**Comment by danieldreier** [comment]
I'm going to close this issue because it's been waiting for a response for about a month. I'm hoping my last response resolved it. If you're still having this issue, please feel free to let us know, and make sure to link this issue if you file a new one so that we have that context. 

If you're not quite sure whether it's a bug or a question, you might post on [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
