### ISSUE TITLE
AWS FSx Subnet issue

### ISSUE THREAD

**Issue by itdevon** [hashicorp/terraform#24517]
Having issues with AWS FSx, I have two subnets, but the error indicates only a max of 1 subnet. 

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.55.0

### Terraform Configuration Files

resource "aws_fsx_windows_file_system" "orapreshopdbfs" {
  storage_capacity    = 2000
  subnet_ids          = ["subnet-1", "subnet-2"]
  throughput_capacity = 2048

  self_managed_active_directory { 
    dns_ips     = ["10.1.1.1", "10.1.1.2"]
    domain_name = "redacted"
    organizational_unit_distinguished_name = "redacted"
    password    = "redacted"
    username    = "redacted"
  }
}

### Debug Output

Error: aws_fsx_windows_file_system.orapreshopdbfs: subnet_ids: attribute supports 1 item maximum, config has 2 declared

### Expected Behavior

FSx is in mult-zone, so it will need to have two subnets. 

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform plan`

- #6017

-->

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
