### ISSUE TITLE
Lock lease time

### ISSUE THREAD

**Issue by Glen-Moonpig** [hashicorp/terraform#24585]
### Current Terraform Version
0.12.24

### Use-cases
We are using S3 for our terraform state backend. The state lock is contained in DynamoDb, which we do not provide general access to; it is restricted to a certain set of people.
We often have people ask us to remove locks from the state where they have cancelled a deployment before it has completed. We do not want to provide everyone access to the DynamoDb tables where the lock is stored so it looks like we are going to have to build a secured solution that will somehow allow them to remove the state locks.

This could easily be solved by applying a lock lease time to the state lock, passed in as an argument on each command that acquires a state lock. The person deploying would simply have to wait a set time (something reasonably longer than the average deployment time) before the lock would be ignored by another deployment.

### Proposal

Add a `--lock-lease-time` argument (a period of time measured in seconds/minutes?) to each lockable command that specifies a lease time in the lock data stored in the back end.
When a new command attempts to create a lock, if a lock exists, but the lease time has passed then the existing lock is discarded and a new one created.

**Comment by pkolyvas** [comment]
@Glen-Moonpig thanks for taking the time to draft this suggestion so clearly. 

We’re very careful about new command-line arguments as they increase complexity in several ways for both development and users. 

Irrespective of how a feature is implemented, I think a lease-lock timeout on our S3 remote state backend isn’t a feature we’d implement at this time. We might accept a PR for such a feature, it would require some design thought and a vetted proposal that didn’t involve a new command line argument. 

While I very much appreciate the need you’ve found to manage lock lease times, my feeling is that this requirement is quite custom. The best path forward would be to build some automation around the Terraform runs such that locks can be released even when runs don’t complete for whatever reason. 

I'm always open to being convinced otherwise, and if you'd ever like to chat Terraform I have open office hours with a link to my calendar on my GitHub profile page.

**Comment by Glen-Moonpig** [comment]
Thanks @pkolyvas I understand what you're saying. One of the problems we have with reacting to a Terraform run that has not completed is the absence of a lock ID when the Terraform acquires a lock, we only see the lock ID when acquiring a lock has failed. Would it be possible to output the lock ID for a terraform command when the lock is created and then we can be proactive in releasing locks?
