### ISSUE TITLE
for_each type conversions

### ISSUE THREAD

**Issue by favoretti** [hashicorp/terraform#24595]
Given the following variable:
```
locals {
  hubs = ["sep", "fusion", "trip"]
}
```

These 2 pieces of code behave differently:
```
resource "azurerm_storage_account" "this" {
  for_each                 = var.separate_namespaces ? local.hubs : toset(["data-ingest"])
...
}
```
above works fine, although tertiary list argument also requires explicit `toset()` conversion.

```
resource "azurerm_eventhub" "this" {
  for_each            = toset(local.hubs)
```
above requires explicit `toset()` conversion.

I'm not sure I understand why in the first example `local.hubs` just works.

**Comment by pkolyvas** [comment]
Hi @favoretti 

Due to the number of bugs and enhancement requests we receive on GitHub, we encourage our community to ask questions over at our [community forums](https://discuss.hashicorp.com/c/terraform-core/27) where help and guidance is more readily available.

Please do return and file an issue if it's a bug.
