### ISSUE TITLE
Terraform version: 0.12.21 crashed

### ISSUE THREAD

**Issue by anomitrokundu** [hashicorp/terraform#24597]
[crash.log](https://github.com/hashicorp/terraform/files/4450993/crash.log)
<img width="440" alt="TerraformCrash" src="https://user-images.githubusercontent.com/63356726/78795525-bda4ab00-79d2-11ea-80b0-9556bfb85fe8.PNG">

### Terraform Version 
0.12.21

```
...
```

### Terraform Configuration Files

```hcl
...
```

### Actual Behavior
Terraform is getting crashed while doing terraform plan.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by pkolyvas** [comment]
Hi @anomitrokundu  In order for the Terraform team to be able to evaluate a bug report we're unfortunately going to need additional context about the crash as indicated by the bug report format. 

Would you be willing to fill in the additional information for us?

**Comment by danieldreier** [comment]
I'm going to close this issue because it's been waiting for a response for several weeks, and we don't have enough information to work on it. We're very interested in understanding Terraform crashes and would like to understand this better. If you're still having this issue, please feel free to let us know, and make sure to link this issue if you file a new one so that we have that context.
