### ISSUE TITLE
better UI feedback for the downloading

### ISSUE THREAD

**Issue by sdouche** [hashicorp/terraform#24602]
Hi folks,
The download of provider plugins is **very** slow after 18:00 CEST. We have the issue on Linux and Mac and from 2 french ISPs (Orange and Free). It would be cool to have a better UI feedback for the downloading to know exactly what is doing

For the last 10 minutes, I've had this:

```
 terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.56.0...
```

Thanks.

**Comment by pkolyvas** [comment]
Hi Sébastien, 

That's no fun! I appreciate there are improvements we could make around the feedback in Terraform's UI/UX. 

Many engineers have expressed frustration with various areas if the Terraform UI and we are thinking about how to begin making strides in those areas. Unfortunately additional download feedback, beyond what's available in the debug logs, is not something high on our priority list. There are many variables when it comes to debugging network issues and providing actionable information on the CLI would be challenging and could be unhelpful in many cases.

We would, of course, welcome a proposal, including what information would be helpful alongside some concept of how users might act based on said information. 

Improving the UI is important to us, as many open enhancement requests indicate. We appreciate every effort or submission in this regard even if if for this particular request we wouldn't move ahead ourselves. 

I'm always open to being convinced otherwise, and if you'd ever like to chat Terraform I have open office hours with a link to my calendar on my GitHub profile page.
