### ISSUE TITLE
Module state

### ISSUE THREAD

**Issue by marcosmachado81** [hashicorp/terraform#24606]
Hello,

I didn't find this on internet and I don't know if there is a way to do this.

When I use a module, for example I will deploy an application using terraform and I use a module for VPC and database the terraform create all resources inside VPC and database modules.

When a coworker download same modules and run for deploy his application, terraform create VPC and database again, but the idea is not create a new VPC or database but use same VPC and database created. We need share modules not to share terraform configuration files, we share modules to share resources. 

The idea is when a coworker download a module and run terraform apply, terraform take resources if these resources were created. The idea is a module should have a state, because terraform needs known when I run terraform apply if resources in a module already created or not.

**Comment by pkolyvas** [comment]
Hi @marcosmachado81 -

Thanks for taking the time to write us.

What you describe is a common collaborative scenario for which there are many solutions depending on what suits your workflow. You’ll want to look at concepts like [remote state](https://www.terraform.io/docs/state/remote.html) storage to share your state & [outputs](https://www.terraform.io/docs/configuration/outputs.html) to share information about your networking and database layer with other Terraform configurations. 

However, due to the number of issues we work through here, aren't able to answer questions about usage. We do encourage our community to ask questions over at our [Terraform community forums](https://discuss.hashicorp.com/c/terraform-core/27). I hope you'll be able to garner some input into what might work best for you.

**Comment by marcosmachado81** [comment]
Hi @pkolyvas 
Thank you for you answer. I know remote state and outputs.

My point is: If I create something like this:
application/
modules/security
modules/network
modules/database

and share my terraform state.. and if someone get the modules like this:

otherapp/
modules/security
modules/network
modules/database

when someone run terraform apply, terraform will remove all resources created before (inside application/) because in the new project there isn't these files. If i don't share the state terraform will recreate all resources inside modules.

the way I doing this is for each module I create a directory (named data) and I create for each resource a data to "retrieve" the resource from AWS... and others projects use these data directory 

modules/security
modules/security/data

when I create a new project I use source="modules/security/data"

I don't know if I was clear with my bad english (sorry about that) but the main Idea is each module has its states, because if I share a module I prevent other terraform project destroy my application and others thinks created and registered in a global state. In my case I work in a company with many applications using the same vpc, subnets and databases.. and we share many modules and we using this approach, each module has a data dir with data "<resource>" "name" and output.tf for the outputs. Of course we started using terraform last month and we need learn much more about the tool. I will do more tests.

thank you
