### ISSUE TITLE
Please ensure VM Agent is installed on the VM and the osProfile.allowExtensionOperations property is true.

### ISSUE THREAD

**Issue by nbandi413** [hashicorp/terraform#24626]
Running into the same issue adding extensions using Terraform, i created a Windows 2016 custom image and i am trying to extensions to the VM.

### Terraform Version 0.12.24

```
...
```

### Terraform Configuration Files

# Creating Virtual Machine

resource "azurerm_virtual_machine" "web-main" {
  
    count = var.webvmcount
    name = "${var.vmprefix}${count.index}"
    location = var.loc
    tags = merge(map("AssetName", "${var.vmprefix}${count.index}"), var.tags)
    availability_set_id = azurerm_availability_set.webtierAVset.id
    resource_group_name = "#{rgname}#" 
    vm_size = var.webvmsize
    network_interface_ids =  [element(azurerm_network_interface.web-main.*.id, count.index)]
    
    storage_image_reference {
       id = data.azurerm_image.image.id
    }
    
    storage_os_disk {
        name              = "${var.vmprefix}-OSdisk"
        caching           = "ReadWrite"
        create_option     = "FromImage"
        managed_disk_type = "Premium_LRS"    
        
        
    }

    storage_data_disk {

      name = element(azurerm_managed_disk.web-Ddrive.*.name, count.index)
      create_option = "Attach"
      managed_disk_id = element(azurerm_managed_disk.web-Ddrive.*.id, count.index)
      lun = 1 
      disk_size_gb = 40 
          
    } 

    os_profile_windows_config {

        timezone = "Pacific Standard Time"

    }    
    
    os_profile {
      computer_name  = "${var.vmprefix}${count.index}"
      admin_username = "#{localadmin}#"
      admin_password = "#{localadminpass}#"
      allowExtensionOperations = "true"
    }

   boot_diagnostics {
        enabled = "1"  
        storage_uri = data.azurerm_storage_account.bootdiag.primary_blob_endpoint 
        
    }
    depends_on = [azurerm_resource_group.rg] 
    
}

```hcl
...
```

### Debug Output

Terraform apply error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status= Code="OperationNotAllowed" Message="This operation cannot be performed when extension operations are disallowed. To allow, please ensure VM Agent is installed on the VM and the osProfile.allowExtensionOperations property is true."

**Comment by danieldreier** [comment]
@nbandi413 from the information you've provided, Terraform Core is operating as expected, and the AzureRM provider is talking to Azure successfully, even though it's not doing what you had expected it to. I searched, and found a [stackoverflow](https://stackoverflow.com/questions/59194145/terraform-enable-psremoting-on-azure-windows-vm) that describes this situation. 

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core. I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

I'm going to close this for now, because I don't have any evidence of a bug in this project or in the AzureRM provider.
