### ISSUE TITLE
Crash While Doing Basic Terraform Tutorial

### ISSUE THREAD

**Issue by dkeirouz** [hashicorp/terraform#24636]
### Terraform Version

```
Terraform v0.12.24
+ provider.google v3.5.0
```

### Terraform Configuration Files

```provider "google" {
  version = "3.5.0"

  credentials = file("<redacted>.json")

  project = "<redacted>"
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_compute_network" "vpc_network" {
  name = "terraform-network"
}

resource "google_compute_instance" "vm_instance" {
  name         = "terraform-instance"
  machine_type = "f1-micro"
  tags         = ["web", "dev"]

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = google_compute_network.vpc_network.name
    access_config {
    }
  }
}
```

### Crash Output

https://gist.github.com/dkeirouz/d9ae290c89e89a7034c0870dca6fe67d

### Expected Behavior

Should have added tags to an existing google_compute_instance
### Actual Behavior

Crash, with a message saying to report.
### Steps to Reproduce

"Changing Resources" section of: https://learn.hashicorp.com/terraform/gcp/change

### Additional Context

Potentially an unstable network connection.

**Comment by danieldreier** [comment]
Thanks for reporting this! I looked at the log output you provided, and the crash you are showing seems to happening in the GCP provider rather than Terraform core:

```shellsession
2020-04-10T12:52:43.189-0700 [DEBUG] plugin.terraform-provider-google_v3.5.0_x5.exe: panic: runtime error: invalid memory address or nil pointer dereference
```

The `plugin.terraform-provider-google_v3.5.0_x5.exe` part tells me that the GCP provider binary crashed, so I'm going to label it as a GCP provider issue, and the HashiBot will shortly migrate it over to the GCP provider's repository so that they can investigate it.

Thanks again for reporting this, and please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
