### ISSUE TITLE
How to maintain persistent volume using terraform

### ISSUE THREAD

**Issue by kirankh7** [hashicorp/terraform#24641]
I'm trying to keep AWS EBS volume as a persistent data-store, every week my AMI changes so I have to spin-up new VM in aws. At this time I'm expecting my volume to detach from the old VM and attach to a new VM without destroying the EBS volume and data. 

```
resource "aws_instance" "my_instance" {
  count         = var.instance_count
  ami           = lookup(var.ami,var.aws_region)
  instance_type = var.instance_type
  key_name      = aws_key_pair.terraform-demo.key_name
  subnet_id     = aws_subnet.main-public-1.id
//  user_data     = "${file("install_apache.sh")}"

  tags = {
    Name  = "Terraform-${count.index + 1}"
    Batch = "5AM"
  }
}



variable "instances" {
  type = map

  default = {
    "xx" = "sss-console"
    "4xx" = "sss-upload-port"
    "xxx" = "sss"
  }
}

resource "aws_kms_key" "cmp_kms" {
  description = "ssss-ebsencrypt"
  tags        = local.all_labels
}

resource "aws_ebs_volume" "volumes" {
  count             = var.instance_count
  availability_zone = element(aws_instance.my_instance.*.availability_zone, count.index )
  encrypted         = true
  kms_key_id        = aws_kms_key.cmp_kms.arn
  size              = local.volume_size
  type              = local.volume_type
  iops              = local.volume_iops
//  tags              = merge(var.extra_labels, map("Name", "${var.cell}-${element(local.volume_name, count.index)}"))

  lifecycle {
//    prevent_destroy = true
    ignore_changes = [kms_key_id, instance_id]
  }
}

resource "aws_volume_attachment" "volumes-attachment" {
  depends_on   = [aws_instance.my_instance, aws_ebs_volume.volumes]
  count        = var.instance_count
  device_name  = "/dev/${element(local.volume_name, count.index)}"
  volume_id    = element(aws_ebs_volume.volumes.*.id, count.index)
  instance_id  = element(aws_instance.my_instance.*.id, count.index)
  force_detach = true
}

```
ERROR on terraform apply
```
Error: Unsupported attribute

  on instance.tf line 71, in resource "aws_ebs_volume" "volumes":
  71:     ignore_changes = [kms_key_id, instance_id]

This object has no argument, nested block, or exported attribute named
"instance_id".
```
earlier the same code use to work with terraform v0.11 but it's not working with v0.12. what is the replacement for this or how can we re-attach EBS to a different machine without destroying it?

**Comment by danieldreier** [comment]
This does look like a legitimate question, but we aren't categorically treating all 0.11 -> 0.12 upgrade difficulties as bugs, and this issue tracker isn't a place where we are able to provide upgrade support outside of fixing bugs, because we have a small team and a large number of users. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, and I'm going to close this for now, because I think the community forum is the right approach.
