### ISSUE TITLE
Terraform Destroy is not deleting some of the VMs but returning as success

### ISSUE THREAD

**Issue by manohar-balaram** [hashicorp/terraform#24644]
[vmw_destroy.zip](https://github.com/hashicorp/terraform/files/4467999/vmw_destroy.zip)
Have uploaded the .tf file and the destroy log.

vsphere version = 6.5

Please let me know if anymore details are required. Thanks!

**Comment by danieldreier** [comment]
@manohar-balaram I read your `destroy.log`, and according to the log, each VM was destroyed. If that isn't the case when you check vSphere, that suggests that the vSphere provider is returning a success to terraform when the VM is in fact not fully destroyed.

I'm not seeing any evidence of a Terraform core bug here, so I'm going to label your issue as a vSphere provider issue, and HashiBot will move this issue over there. When that happens, I recommend you also add further details to the new issue that describe how you confirmed that the VMs are not actually being deleted, for example listing which VMs are not deleted, and under what circumstances. 

All the information provided here indicates that they are being destroyed, so it would be helpful for troubleshooting. From skimming your example, it also looks like not all the data referenced is present in the terraform config in the zip bundle. The vSphere provider team will need to run this and reproduce it locally in order to help you, so it would help to provide a full example with everything but credentials that they can run.
