### ISSUE TITLE
Expose `download_url_override` in Chef Provisioner install script

### ISSUE THREAD

**Issue by jakereps** [hashicorp/terraform#24651]
### Current Terraform Version

```
Terraform v0.11.7
```
Version is out of date due to needing to migrate the pipeline to 12.x+ still.
Current docs show no additions of this requested behavior yet.

### Use-cases

- Due to the licensing changes in Chef, 14.x is the last version an enterprise would be allowed to download directly from `downloads.chef.io` - which is what the current provisioner uses through omnitruck. It is also EOL at the end of the month.

- Use a version higher than 14.x in accordance with enterprise licensing.

- For enterprise environments to be able to specify an internally hosted `download_url_override` for the Chef client installation script ran by the provisioner. 

### Attempted Solutions

Finding how Chef was installed I dug through the script to see if there were any environment variables that could be set to override the download URL, but it appears that it is only allowed as an option to the shell script at run.

https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/linux_provisioner.go#L14

```

# script_cli_parameters.sh
############
# This section reads the CLI parameters for the install script and translates
#   them to the local parameters to be used later by the script.
#
# Outputs:
# $version: Requested version to be installed.
# $channel: Channel to install the product from
# $project: Project to be installed
# $cmdline_filename: Name of the package downloaded on local disk.
# $cmdline_dl_dir: Name of the directory downloaded package will be saved to on local disk.
# $install_strategy: Method of package installations. default strategy is to always install upon exec. Set to "once" to skip if project is installed
# $download_url_override: Install package downloaded from a direct URL.
# $checksum: SHA256 for download_url_override file (optional)
############

# Defaults
channel="stable"
project="chef"

while getopts pnv:c:f:P:d:s:l:a opt
do
  case "$opt" in

    v)  version="$OPTARG";;
    c)  channel="$OPTARG";;
    p)  channel="current";; # compat for prerelease option
    n)  channel="current";; # compat for nightlies option
    f)  cmdline_filename="$OPTARG";;
    P)  project="$OPTARG";;
    d)  cmdline_dl_dir="$OPTARG";;
    s)  install_strategy="$OPTARG";;
    l)  download_url_override="$OPTARG";;
    a)  checksum="$OPTARG";;
    \?)   # unknown flag
      echo >&2 \
      "usage: $0 [-P project] [-c release_channel] [-v version] [-f filename | -d download_dir] [-s install_strategy] [-l download_url_override] [-a checksum]"
      exit 1;;
  esac
done
```

So there is no way to do it using the existing provisioner setup.

### Proposal

An idea would be to add a new field to the Chef provisioner configuration to allow the user to specify a download URL override, and conditionally append it to the shell script options if it is set, otherwise defaulting to maintain current behavior.

### References

I could not find any relevant GitHub issues in a quick scan of Chef Provisioner.

The License announcement and FAQ are here:
- https://blog.chef.io/chef-software-announces-the-enterprise-automation-stack/
- https://www.chef.io/subscription-model-faq/

**Comment by jakereps** [comment]
I would also be willing to lend a hand in implementing this as well, if need be 👍

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for built-in plugins like the chef provisioner.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested. Similarly, it's tough to accept PRs, even for useful improvements, because we don't have anyone on the core team with deep Chef knowledge, and we have not been able to get community volunteers to own PR review for this codebase, so it's a shot in the dark whether a given PR makes things better or worse from the perspective of an experienced Chef + Terraform user.

For the time being, the best option if you want to see this built, is to work with the community and build a standalone chef provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed.

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
