### ISSUE TITLE
lookup function in data sources works differently than in resources

### ISSUE THREAD

**Issue by tickbox-smc** [hashicorp/terraform#24664]
### Terraform Version

```
terraform -v
Terraform v0.12.19
+ provider.aws v2.57.0

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html

```

### Terraform Configuration Files

```hcl
module "log_bucket" {
...
  server_side_encryption_configuration = {
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = lookup(data.terraform_remote_state.keys.outputs.key, "key_alias", "default")
        sse_algorithm     = var.sse_encryption
      }
    }
  }

#---

data "aws_iam_policy_document" "put_log_events" {
  ...
  statement {
    sid = "AllowDecryption"

    effect = "Allow"
    resources = [lookup(data.terraform_remote_state.keys.outputs.key.alias, "key_alias", "default")]

    actions = [
      "kms:Decrypt",
      "kms:GenerateDataKey",
    ]

```

### Expected Behavior

In the code extracts above I show 2 calls to the 'lookup' function which is retrieving data from state. One is a module call and the other is a data source.
Since both calls are accessing the same state, I would have expected the lookups for both to be coded the same way.
lookup(data.terraform_remote_state.keys.outputs.key, "key_alias", "default")

### Actual Behavior

```
Error: Unsupported attribute

  on data.tf line 157, in data "aws_iam_policy_document" "com_ce_allow_put_log_events":
 157:         lookup(data.terraform_remote_state.keys.outputs.keys, var.com_ce_key_alias, "default")
    |----------------
    | data.terraform_remote_state.keys.outputs is object with 1 attribute "key"
```

In order to get the lookup to work in the data source I have to code the lookup as follows:

lookup(data.terraform_remote_state.keys.outputs.key.alias, "key_alias", "default")

**Comment by danieldreier** [comment]
@tickbox-smc without knowing what data `lookup` is returning, it's really tough for me to reason about this, and I can't tell whether this is expected behavior or not. I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior.

If this is important to you, can you please restate your reproduction case such that I can copy-paste it (or git clone it) and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies, but I understand that's not always possible.

**Comment by apparentlymart** [comment]
Hi @tickbox-smc!

We didn't hear back from you after @danieldreier's comment, so I'm going to close this on the assumption that you found a solution to your problem elsewhere. If so, it'd be great if you could reply and let us know what you learned!

If this is still a problem for you and you're able to provide a reproduction case as @danieldreier requested, please let us know and we can re-open this. Thanks!
