### ISSUE TITLE
aws_network_interface resource private_ips required (not optional),

### ISSUE THREAD

**Issue by TheM0ng00se** [hashicorp/terraform#2467]
in terraform/builtin/providers/aws/aws_network_interface.go:

private_ips is listed as optional, however not specifying this causes a terraform apply to fail with 
"500 Error" instead of simply requesting AWS auto-assign an IP from the subnet.

Manually specifying the private_ips will workaround this issue
`
resource "aws_network_interface" "csr1_priv" {
    subnet_id = "${aws_subnet.tools.0.id}"
    security_groups = [ "sg-93ea0cf4" ]
    tags {
        Name = "csr1_priv"
    }
}
`
plan shows:
`
+ aws_network_interface.csr1_priv
    security_groups.#:         "" => "1"
    security_groups.453606690: "" => "sg-93ea0cf4"
    subnet_id:                 "" => "subnet-ac5126f5"
    tags.#:                    "" => "1"
    tags.Name:                 "" => "csr1_priv"
`
apply does:

aws_network_interface.csr1_priv: Error: 1 error(s) occurred:

* Error creating ENI: InternalError: An internal error has occurred
	status code: 500, request id: []

**Comment by mitchellh** [comment]
We mark the parameter as optional since the API itself says its optional. The 500 response indicates that AWS is also failing to handle this, so I would say its likely a bug on there side... I don't think we should mark it as required since the docs say it is optional. Instead, AWS should fix this issue on their end.
