### ISSUE TITLE
recreating aws_security_group loadbalancer in terraform 

### ISSUE THREAD

**Issue by pzowghi** [hashicorp/terraform#24698]
I am using aws_security_group in my terraform codes.
terraform recreates aws_security_group for loadbalancer always, but I didn't any changes in code.
This issue just happens for SG loadbalancer.
I have this bug in terraform 0.11 and 0.12
How I can fix it?
Thanks

**Comment by danieldreier** [comment]
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). 

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!
