### ISSUE TITLE
AwsBackUp support cross region copy in terraform

### ISSUE THREAD

**Issue by rahulgaitonde** [hashicorp/terraform#24705]
Hi,

Does terraform support aws backup feature for cross region copy (https://www.terraform.io/docs/providers/aws/r/backup_plan.html ) . As i read the document i can see that it does support but i get the following error

Error: Unsupported block type
  on backup_plan.tf line 13, in resource "aws_backup_plan" "example":
  13:     copy_action {
Blocks of type "copy_action" are not expected here.

My terraform file for your reference

resource "aws_backup_plan" "example" {
    name = "example-plan"
    rule {
        rule_name = "MainRule"
        target_vault_name = "primary"
        schedule = "cron(5 8 * * ? *)"
        start_window = 480
        completion_window = 10080
        lifecycle {
            delete_after = 30
        }
        copy_action {
            destination_vault_arn = "arn:aws:backup:us-west-2:123456789:backup-vault:secondary"
        }
    }
}

But when i remove the block copy_action {
            destination_vault_arn = "arn:aws:backup:us-west-2:123456789:backup-vault:secondary"
        }
It works just fine

**Comment by danieldreier** [comment]
Hello!

It looks to me like you're asking for help with the AWS Terraform provider, rather than reporting a particular bug. We use GitHub issues for tracking bugs and enhancements to Terraform Core, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
