### ISSUE TITLE
Firewall: support Service account scope in another project

### ISSUE THREAD

**Issue by vijay-sapient** [hashicorp/terraform#24713]
```
Current firewall provider does not support passing value "Service account scope in another project" Please see screenshot on the feature required.

If we use the mail id of the other project, terraform fails with the below error:

googleapi: Error 400: Invalid value for field 'resource.targetServiceAccounts[0]': 'svc-nodes@$PROJECT_ID.iam.gserviceaccount.com@$HOST_PROJECT_ID.iam.gserviceaccount.com'. Service accounts must be valid RFC 822 email addresses., invalid

Terraform is adding the current projects service account id:- at the end when full service account id is provided. Hence failing
```
### Terraform Version

```
0.12.24
```

### Terraform Configuration Files

```hcl
allow-egr:
  allow:
    - ports: []
      protocol: all
  direction: EGRESS
  disabled: false
  enable_logging: true
  network: network_default
  priority: "65010"
  destination_ranges:
    - 0.0.0.0/0
  target_service_accounts:
    - svc-nodes@$PROJECT_ID.iam.gserviceaccount.com
```

### Expected Behavior

```
Resource should be created with values  Service account scope in another project. 
```

### Actual Behavior

```
fails with below error: 
googleapi: Error 400: Invalid value for field 'resource.targetServiceAccounts[0]': 'svc-nodes@$PROJECT_ID.iam.gserviceaccount.com@$HOST_PROJECT_ID.iam.gserviceaccount.com'. Service accounts must be valid RFC 822 email addresses., invalid
```
### References

<img width="597" alt="Screen Shot 2020-04-20 at 3 29 19 PM" src="https://user-images.githubusercontent.com/55389213/79772397-f2e0bf80-8327-11ea-8422-1e35ed265c9a.png">

**Comment by danieldreier** [comment]
Hi @vijay-sapient! I don't quite understand the issue you've reported. I'm happy to try and help, but will need more information first.

I have two questions:
1. I'm not aware of there being a `firewall` provider. Are you reporting an issue with the google provider? 
2. Can you please provide an example in `HCL` rather than `YAML` format? This doesn't look like valid terraform code to me. I need a full, usable example of terraform config that I can run locally to reproduce this issue in order to process a bug report.
