### ISSUE TITLE
Iothub device

### ISSUE THREAD

**Issue by abhatikar** [hashicorp/terraform#24721]
### Current Terraform Version
Latest

```
...
```

### Use-cases

Can we create a iothub device on the provisioned iothub using terraform script ?

**Comment by pkolyvas** [comment]
Hey there,

Thanks for taking the time to write us.

Due to the number of issues we work through here, we encourage our community to ask questions over at our [community forums](https://discuss.hashicorp.com/c/terraform-core/27) before making feature requests or reporting bugs. That's the best place to start for specific workflows and workflow questions.
