### ISSUE TITLE
Prevent destroy and allow create

### ISSUE THREAD

**Issue by quinn** [hashicorp/terraform#24733]
I have a terraform script that uploads a timestamped object to a bucket. It will always generate a new object, but i don't need it to destroy the old version, because i would like to create a log of builds. 

Is there a way i can allow terraform to create the new storage bucket object and "forget" about the previous one in state, without destroying it?

**Comment by pkolyvas** [comment]
Hi @quinn!

Thanks for taking the time to write us.

I think it would depend how you're creating the object in your configuration. That said, I bet someone in our [community](https://discuss.hashicorp.com/c/terraform-core/27) might have some suggestions or solutions for you. Perhaps you'd be willing to share a little more of your workflow there? It might help prompt discussion.

We try to encourage workflow questions on [our forums](https://discuss.hashicorp.com/c/terraform-core/27) simply due to the number of issues we receive and work through here. If there is a feature enhancement proposal or bug that comes out of the discovery/discussion process, please do return here.
