### ISSUE TITLE
After Load balancer creation not able to associate the backend pool vm using terraform code

### ISSUE THREAD

**Issue by ntmsvicky1** [hashicorp/terraform#24743]
### Terraform Version
Terraform v0.12.24
+ provider.azurerm v2.0.0
+ provider.random v2.2.1

### Terraform Configuration Files

```hcl
...
```

### Crash Output
2020/04/23 02:51:50 [TRACE] dag/walk: upstream of "root" errored, so skipping

### Expected Behavior

The back-end pool should get associated with VM defined 

### Steps to Reproduce

1. `terraform init`
2. `terraform plan shows the list of changes will apply
3. terraform apply -auto-approve fails everytime

**Comment by danieldreier** [comment]
Hi! Thanks for reporting this. I'd like to reproduce it locally. To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, you put in `...` for your config files, and so I'm stuck. Terraform definitely doesn't do this under all circumstances, and I don't know what config you're running to make this happen. Maybe you forgot to put that code in?

Can you please restate your reproduction case such that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies, but I understand that's not always possible.

**Comment by ntmsvicky1** [comment]
Hi Daniel,

Issue is resolved.

Regards,
Vicky.

**Comment by danieldreier** [comment]
Thanks for the update! I'm glad it's working for you!
