### ISSUE TITLE
big_ltm_virtual_server does not work with IPv6 address

### ISSUE THREAD

**Issue by zx1986** [hashicorp/terraform#24747]
### Terraform Version

```
Using Kubernetes executor with image hashicorp/terraform:0.12.24 ...
* provider.bigip: version = "~> 1.1"
```

### Terraform Configuration Files
```hcl
resource "bigip_ltm_virtual_server" "vs" {
   pool        = "/Common/tf_pool_name"
   name        = "/Common/tf_vs_80"
   destination = "aaaa:b034:1001:700:xxxx:xxxx:xxxx:xxxx"
   port        = 80
 }
```

### Crash Output

```
Error: A port number or service name is missing for "aaaa:b034:1001:700:xxxx:yyyy:zzzz:xxxx:80". Please specify a port number or service name using the syntax 
"aaaa:b034:1001:700:xxxx:yyyy:zzzz:xxxx:80.<port>".

 on main.tf line 53, in resource "bigip_ltm_virtual_server" "vs":
  53: resource "bigip_ltm_virtual_server" "vs" {
```

### Expected Behavior
Create an Virtual Server with IPv6 destination.

### Actual Behavior
Apply failed.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

@dan-kriz had told: `BigIP for ipv6 is expecting the separator for the port to be a dot (.) instead of a colon (:)`

### References
- #2301
- https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_virtual_server.html

**Comment by zx1986** [comment]
Could I label this with `bigip`

**Comment by danieldreier** [comment]
Hi @zx1986! Yeah, it looks to me like this is an issue for the [bigip provider](https://github.com/terraform-providers/terraform-provider-bigip) rather than Terraform core. I've labeled it, and HashiBot should move it over there shortly. If that doesn't work, please feel free to close and re-open it in that repository yourself. (give it a day or so, HashiBot runs in batches)
