### ISSUE TITLE
salt-masterless forces to run state.sls

### ISSUE THREAD

**Issue by cathode911** [hashicorp/terraform#24756]
Hello colleagues!

Looks like salt-masterless argument 'custom_state' is not really custom and hardcoded to use state.sls runner (symlink of state.orchestrate from salt perspective)

### Terraform Version
```
terraform -v
Terraform v0.12.24
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.vsphere v1.17.2
```

### Terraform Configuration Files
```hcl
  provisioner "salt-masterless" {
    local_state_tree = "${path.module}/salt/states"
    custom_state = "state.apply consul"
  }
```

### Debug Output
Error: error executing "sudo salt-call --local  state.sls state.apply consul --file-root=/srv/salt --pillar-root=/srv/pillar --retcode-passthrough -l info": Process exited with status 1

### Expected Behavior
custom_state argument should simply provide it's value entered by user to salt-call instead of forcing user to deal with state.sls runner, e.g actual command must have been run like this: ``sudo salt-call --local state.apply consul --file-root=/srv/salt --pillar-root=/srv/pillar --retcode-passthrough -l info``. 
But for some reason terraform prepends user given command with "state.sls" (see debug output).

### Actual Behavior
Instead of what is expected, custom_state has hardcoded state.sls usage, in my case it results in error, as ``salt-call --local  state.sls state.apply consul`` command is ambiguous.

### Steps to Reproduce
1. configure provisioner "salt-masterless" argument "custom_state" with any custom command
2. run `terraform apply`

**Comment by peterschutt** [comment]
I find this works if you exclude the `state.apply`, e.g., `custom_state = "consul"` produces the command `salt-call --local state.sls consul` which is valid per: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls

**Comment by cathode911** [comment]
Indeed it is, but custom_command then in fact is "not-so-custom" due to hardcoded state.sls entry. 
If there's a need to run any other kind of command - it won't work, like in my case where i need to run state.apply. I consider that behavior as a bug that needs to be fixed.

**Comment by peterschutt** [comment]
The point I was making is that using `state.apply` as an argument as to why it is broken for the provisioner to either call `state.highstate` or `state.sls` doesn't seem very compelling as it seems that is what `state.apply` does itself:

[Source](https://github.com/saltstack/salt/blob/2520ae8675185a747dbadd09bc47c305f476886f/salt/modules/state.py#L799-L801)
```py
def apply_(mods=None, **kwargs):
    """
    ...
    """
    if mods:
        return sls(mods, **kwargs)
    return highstate(**kwargs)
```

I agree with you that it would be good if custom command was more flexible. For example, to pass dynamic pillar data to the state run through the command line my first thought was to send `custom_command = "state.apply pillar='${jsonencode({ some = thing })}'`" which didn't work for the same reason you found. I've resorted to using `custom_command = "${join(",", var.states)} pillar='${jsonencode({ some = thing })}'"` where `var.states` is a list of state names and I don't bother with a top file.

The thing is, if `custom_command` was to stop injecting `state.sls` into the command, then the provisioners I've configured are now broken.

**Comment by danieldreier** [comment]
I'm closing this issue because we announced tool-specific (vendor or 3rd-party) provisioner deprecation in [mid-September 2020](https://discuss.hashicorp.com/t/notice-terraform-to-begin-deprecation-of-vendor-tool-specific-provisioners-starting-in-terraform-0-13-4/13997). Additionally, we added a deprecation notice for tool-specific provisioners in 0.13.4. On a practical level this means we will no longer be reviewing or merging PRs for these built-in plugins.

The discuss post linked above explains this in more depth, but the basic reason we're making this change is that these vendor provisioners have been extremely challenging for us to maintain, and are a weak spot in the terraform user experience. People reach for them not realizing the bugs and UX limitations, and they're areas that are difficult for us to maintain because of the huge surface area of integrating with a bunch of different tools (Puppet, Chef, Salt, etc) that each require deep domain knowledge to do right. For example, testing each of these against all the versions of those tools, on multiple platforms, is prohibitive, and so we don't - but users have a reasonable expectation that everything in the Terraform Core codebase is well tested.

For the time being, the best option if you want to see this built, is to build a standalone provisioner and distribute it as a plugin binary, similar to how the [ansible provisioner](https://github.com/radekg/terraform-provisioner-ansible) is distributed. 

I'm aware of the limitations of this approach, but it's the best option compared to coupling provisioner development to the Terraform Core release lifecycle. We believe the benefit to users of having provisioner development decoupled from core, exceeds the convenience of having these provisioners built in to core. We want to provide a better user experience in the future, and our hope here is that the ability to improve, fix and repair provisioners without us blocking their development, much like providers, will help make a strong case for what's next.

I think it’s also important to highlight that we have no plans to remove the generic provisioners or the pluggable functionality during Terraform's 1.0 lifecycle. 

I appreciate your input here to improve Terraform, and am always happy to talk. Please feel free to reach out to me or Petros Kolyvas if you would like to talk more about this change.
