### ISSUE TITLE
terraform crash

### ISSUE THREAD

**Issue by amrikst** [hashicorp/terraform#24750]
### Terraform Version - v0.12.24

```
...
```

### Terraform Configuration Files

```hcl
...
```

### Actual Behavior
 Terraform output is a crash file and the instructions advise to inform terraform via github

**Comment by amrikst** [comment]
[crash.log](https://github.com/hashicorp/terraform/files/4523318/crash.log)

**Comment by amrikst** [comment]
.

**Comment by danieldreier** [comment]
Hi! It looks to me like you had terraform crash, and are trying to follow the instructions. Thanks! In order to make any progress on this, I also need to be able to reproduce your crash. The crash log tells me that this happened in the azurerm provider, but doesn't give me enough detail to understand how to reproduce it.

```
2020-04-23T15:58:53.623+0100 [DEBUG] plugin.terraform-provider-azurerm_v1.44.0_x4: panic: interface conversion: interface {} is nil, not map[string]interface {}
```

Would you please post a full reproduction case? I need a terraform config that produces this failure mode, in addition to the crash log, because I need to reproduce the failure on my own system.

**Comment by amrikst** [comment]
Hi Daniel, were can I find the config file?

**Comment by danieldreier** [comment]
@amrikst the config file I'm talking about is your terraform code - I need to know what to run to trigger this crash, or else I can't troubleshoot it.

**Comment by apparentlymart** [comment]
Hi @amrikst,

We haven't heard from you for a while. The crash log indicates to me that the bug you've found here is in the Azure provider rather than in Terraform Core, so if you'd like to help the Azure provider team to find and fix this bug I suggest to open an issue in [the Azure provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) instead.

I expect that the Azure provider team will ask similar questions as @danieldreier did above, because they too will need to see the Terraform configuration you're running in order to understand what they need to do in order to trigger the same crash on their own systems. Because both Terraform and Terraform Providers are software that run on your own system, the developers unfortunately need your help to observe the same behavior on their own systems in order to understand what caused the crash.

Because this issue is in the Azure provider rather than in Terraform Core, I'm going to close this. Thanks for reporting this issue!
