### ISSUE TITLE
data "aws_prefix_list" is not able to fetch correct CIDR blocks from AWS IP list  https://ip-ranges.amazonaws.com/ip-ranges.json

### ISSUE THREAD

**Issue by nyadav08** [hashicorp/terraform#24754]
We are using data aws_prefix_list to fetch the IP ranges for that region for S3 and currently using below versions of terraform and aws provider.

Terraform v0.12.23
 provider.aws: version = "2.58"
 provider.random: version = "2.2"
```hcl
data "aws_prefix_list" "private_s3" {
  name = "com.amazonaws.us-west-2.s3"
}

resource "aws_security_group" "endpoint-s3" {
  name   = "${var.project_id}-endpoint-s3"
  vpc_id = var.vpc_id  egress {
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
    cidr_blocks = data.aws_prefix_list.private_s3.cidr_blocks
  } 
}
```
We recently noticed that for us-west-2 region this data.aws_prefix_list is only getching IP range 52.218.128.0/17 and not fetching 52.92.32.0/22 and 54.231.160.0/19, which are part of aws IP address list https://ip-ranges.amazonaws.com/ip-ranges.json

jq -r '.prefixes[] | select(.region=="us-west-2") | select(.service=="S3") | .ip_prefix' < ip-ranges.json

or you can use this 

https://awsiprange.com/browse?service=s3&region=us-west-2&show_service=on&show_region=on&show_prefix=on

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
