### ISSUE TITLE
Using conditional member in map converts all member proerties to strings 

### ISSUE THREAD

**Issue by herrbpl** [hashicorp/terraform#24757]
### Terraform Version

```
v0.12.24
```

### Terraform Configuration Files

```hcl
yamlencode(merge({ value = true }, { map = { bool = true, number = 123, string = "dfsdfwf" }}))
yamlencode(merge({ value = true }, { map = true ?  { bool = true, number = 123, string = "dfsdfwf" }: {}}))
```

### Expected Behavior

```hcl
yamlencode(merge({ value = true }, { map = true ?  { bool = true, number = 123, string = "dfsdfwf" }: {}}))
```
Expected result:
```json
"map":
  "bool": true
  "number": 123
  "string": "dfsdfwf"
"value": true
```
### Actual Behavior

actual results (all properties of member are converted to string)
```json
"map":
  "bool": "true"
  "number": "123"
  "string": "dfsdfwf"
"value": true
```

### Steps to Reproduce

```bash
terraform console
yamlencode(merge({ value = true }, { map = { bool = true, number = 123, string = "dfsdfwf" }}))
yamlencode(merge({ value = true }, { map = true ?  { bool = true, number = 123, string = "dfsdfwf" }: {}}))
```

### Additional Context

This behaviour makes generating yaml problematic, as true and "true" have different meaning for example in Kubernetes manifests and could result deployment failure.

**Comment by herrbpl** [comment]
Coould find workaround as:

```hcl
yamlencode(merge({ value = true }, { map = jsondecode( true ?  jsonencode({ bool = true, number = 123, string = "dfsdfwf" }): jsonencode({}) ) } ))
```
which results
```json
"map":
  "bool": true
  "number": 123
  "string": "dfsdfwf"
"value": true
```

**Comment by danieldreier** [comment]
This looks like a valid issue to me. Thanks for reporting it. I especially appreciate you creating this very simple reproduction case that's isolated from your production setup - this made it easy for me to reproduce locally.

I'm looking at the even-simpler reproduction case of:
```
> merge({}, { map = true ? { bool = true, number = 123, string = "dfsdfwf" }: {}})
{
  "map" = {
    "bool" = "true"
    "number" = "123"
    "string" = "dfsdfwf"
  }
}
```

If other people are also running into this, please 👍 the issue to vote for urgency. As legitimate and annoying as an issue as this looks like, my hot take is that with the workaround in place and this being a relative edge case it doesn't seem super urgent, compared to some of the highly voted issues in our backlog. 

If people are widely using conditional map membership managing k8s with Terraform, maybe my assessment is way off and this is higher impact than I'm imagining.

**Comment by alisdair** [comment]
Thanks for reporting this problem! I can see why this behaviour of the conditional operator would be confusing, but this is an intentional outcome of the way types work in Terraform. The solution to this problem is to use `null` instead of `{}` as the `false` value of the conditional expression. See the end of this comment for an example.

Here's what's happening. Consider the following expression evaluated on terraform console:

```
> true ? { x = true, y = 1, z = "a" }: {}
{
  "x" = "true"
  "y" = "1"
  "z" = "a"
}
```

The result of the conditional expression is a `map(string)`. This is because we have provided two values to the conditional expression: the `true` value is `object({ x=bool, y=number, z=string })` and the false value is `map(any)`. Note that the true value is an `object`, because `map` types must have the same type for every value.

When evaluating a conditional expression, Terraform must determine the resulting type, which must be compatible with both the `true` and the `false` value. For this example, it is able to convert both the `true` and `false` values to a `map(string)`. This is why the result we see has all values converted to `string`.

Fortunately there is a type we can use as the `false` value which will create the behaviour you're looking for here: `null`. This is a valid value of any type, including the `true` value's type `object(…)`. Here's another terraform console session:

```
> true ? { x = true, y = 1, z = "a" }: null
{
  "x" = true
  "y" = 1
  "z" = "a"
}
```

In general, when you want an "empty object" value, choose `null` instead of `{}`. I understand that this wasn't obvious, and we'd like to find better ways to surface this information in the future.
