### ISSUE TITLE
Ouput ignores depends_on argument

### ISSUE THREAD

**Issue by voxmaster** [hashicorp/terraform#24766]
### Terraform Version
```
Terraform v0.12.24
+ provider.digitalocean v1.16.0
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
```

### Terraform Configuration Files
```hcl
variable "do_token"{}

provider "digitalocean" {
  token = var.do_token
}

# Get DO Kubernetes cluster data
data "digitalocean_kubernetes_cluster" "cluster0" {
  name = "beerscience"
}

###* Configure Kubernetes Provider *###
provider "kubernetes" {
  load_config_file       = false
  host                   = data.digitalocean_kubernetes_cluster.cluster0.endpoint
  cluster_ca_certificate = base64decode(data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.cluster_ca_certificate)
  client_certificate     = base64decode(data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.client_certificate)
  client_key             = base64decode(data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.client_key)
  token                  = data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.token
}

###* Configure Kubernetes Helm Provider *###
provider "helm" {
  kubernetes {
    load_config_file       = false
    host                   = data.digitalocean_kubernetes_cluster.cluster0.endpoint
    cluster_ca_certificate = base64decode(data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.cluster_ca_certificate)
    client_certificate     = base64decode(data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.client_certificate)
    client_key             = base64decode(data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.client_key)
    token                  = data.digitalocean_kubernetes_cluster.cluster0.kube_config.0.token
  }
}
data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}
###
variable "nginx_chartname_class_map" {
  default = {
    ingress-nginx-debug = "nginx-debug"
  }
  description = "Set map of a HELM_RELEASE_NAME = INGRESS_CLASS"
}
resource "kubernetes_namespace" "ingress_nginx" {
  metadata { name = "ingress-nginx" }
}
resource "helm_release" "ingress_nginx" {
  for_each   = var.nginx_chartname_class_map
  depends_on = [kubernetes_namespace.ingress_nginx]
  name       = each.key
  namespace  = "ingress-nginx"
  chart      = "stable/nginx-ingress"
  values = [
    <<-EOF
controller:
  ingressClass: ${each.value}
EOF
  ]
}
data "kubernetes_service" "ingress_nginx" {
  depends_on = [helm_release.ingress_nginx]
  for_each   = var.nginx_chartname_class_map
  metadata {
    name      = "${helm_release.ingress_nginx[each.key].name}-nginx-ingress-controller"
    namespace = "${helm_release.ingress_nginx[each.key].namespace}"
  }
}
output "ingress_nginx" {
  value = [for chart in data.kubernetes_service.ingress_nginx : chart.metadata[0].labels.release]
  depends_on = [
    data.kubernetes_service.ingress_nginx,
    helm_release.ingress_nginx
  ]

}

```

### Debug Output
https://gist.github.com/voxmaster/e1dbe5b149624ff5d17ad2e37e92edc2

### Crash Output
No crash

### Expected Behavior
Changes should be planned

### Actual Behavior
Error:
```
Error: Attempt to get attribute from null value

  on ingress.tf line 32, in output "ingress_nginx":
  32:   value = [for chart in data.kubernetes_service.ingress_nginx : chart.metadata[0].labels.release]
    |----------------
    | chart.metadata[0].labels is null

This value is null, so it does not have any attributes.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
On levels not lower than metadata, I got expected behaviour (planning changes)
```
output "ingress_nginx" {
  value = [for chart in data.kubernetes_service.ingress_nginx : chart.metadata[0]]
  depends_on = [
    data.kubernetes_service.ingress_nginx,
    helm_release.ingress_nginx
  ]
}
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I'm happy to see people using Terraform like this.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core, though I also don't entirely understand the behavior you're seeing. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  Post this on the community forum. This is a cool use case, and I am wondering if some community troubleshooting might be helpful. We use GitHub issues for tracking bugs and enhancements to Terraform Core itself, rather than for questions, or issues with providers. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug in Terraform Core, it would be helpful if you could work up a simple reproduction case that doesn't involve Kubernetes, ideally just using null resources, to show that outputs and depends_on don't work together, in order to isolate that issue from the k8s reproduction case. Setting up a DigitalOcean Kubernetes test fixture is a pretty big amount of setup to reproduce what looks like either a configuration debugging issue or a core issue between outputs and depends_on.

Do those options make sense? Happy to go either way, this is just a little hard for me to work on as-is.

**Comment by voxmaster** [comment]
Thank you for the response! I'll try to create a simple reproduction case for this and will be back later.
PS. This behavior can be reproduced without actually DigitalOcean setup, on `plan` step.

**Comment by danieldreier** [comment]
@voxmaster when I ran plan, the digitalocean provider prompted me for an API key and failed when I gave it a fake one - it needs that data source or the plan fails before it reproduces your error case here.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
