### ISSUE TITLE
Error: Incorrect attribute value type

### ISSUE THREAD

**Issue by ura718** [hashicorp/terraform#24770]
Hello, not sure if this is correct forum to place issues in but I am running into an issue when trying to add users to specific group.  The group is successfully created, the users are successfully created, but when trying to add users to group it does not work. Is there something that I am doing wrong is is this a bug? I get the following error:  

    Terraform v0.12.24  

#### Error
    Error: Incorrect attribute value type  

    on: main.tf line 46, in resource "aws_iam_group_membership" "team":
    46:   users = each.key  

    Inappropriate value for attribute "users": set of string required.

#### terraform.tfvars    
    user_names = {
      "dummy1"   = {
        path          = "/"
        force_destroy = true
        tag_fullname  = "dummy 1"
      }
      "dummy2"   = {
        path          = "/"
        force_destroy = true
        tag_fullname  = "dummy 2"
      }
    }

    group_memberships = {
      "dummy1" = ["dummy-group"]
      "dummy2" = ["dummy-group"]
    }  

    group  = "dummy-group"

### Create user account
    ### --------------------------------------

    resource "aws_iam_user" "username" {
      for_each = var.user_names
      name          = each.key
      path          = each.value["path"]
      force_destroy = each.value["force_destroy"]

      # Full Name is tag Key, and each.value["tag_fullname"] is tag value
      tags = map("Full Name", each.value["tag_fullname"])
    }

    ### --------------------------------------
    ### Add user to group
    ### --------------------------------------
    resource "aws_iam_group_membership" "team" {
      name = var.group

      for_each = var.group_memberships
      users = each.key
      group = each.value
      depends_on = [aws_iam_user.username]
    }

**Comment by danieldreier** [comment]
Hello @ura718! On the surface of it, this doesn't look like a bug to me. It looks to me like you're asking for help with the AWS Terraform provider, rather than reporting a particular bug. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
