### ISSUE TITLE
GCS terraform_remote_state Backend | Error: Unsupported attribute

### ISSUE THREAD

**Issue by sagarr8130** [hashicorp/terraform#24789]
### Terraform Version
[root@localhost instance]# terraform version
Terraform v0.12.24
provider.google v3.18.0

### Terraform Configuration Files

https://github.com/sagarr8130/Terraform_Issue/tree/master/Network
https://github.com/sagarr8130/Terraform_Issue/tree/master/Instance

### Crash Output
https://github.com/sagarr8130/Terraform_Issue/blob/master/Instance/Instance_terraform_output.txt

### Expected Behavior
Instance Should be launch with the help of terraform_remote_state

### Actual Behavior
Error: Unsupported attribute

### Steps to Reproduce
Attached complete git repo url above which will be helpful for replicate

### Additional Context
I am using GCP service account (account.json) in both locations (Network folder and Instance Folder)

**Comment by sagarr8130** [comment]
Can someone please help me here to proceed with this POC

**Comment by danieldreier** [comment]
Hello!

It looks to me like you're asking for help with a Terraform provider, rather than reporting a particular bug. This looks to me like you're midway through troubleshooting a configuration issue, rather than encountering a bug in Terraform. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
