### ISSUE TITLE
ipv6_cidr_blocks must contain a valid network CIDR, got "2a03:2800:0300::/64"

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#24784]
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.6.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
resource "aws_security_group_rule" "deploy_ssh" {
  type      = "ingress"
  from_port = 22
  to_port   = 22
  protocol  = "tcp"

  cidr_blocks = [
    "185.22.208.0/25",
    "185.22.211.0/24"
  ]

  ipv6_cidr_blocks = [
    "2a00:67a0:a:1::/64",
    "2a03:2800:0300::/64"
  ]

  security_group_id = "${aws_security_group.app.id}"
}
```

### Expected Behavior
These are valid ipv6 CIDR blocks.

### Actual Behavior
```
Error: module.security_groups_eu_central_1.aws_security_group_rule.deploy_ssh: "ipv6_cidr_blocks.1" must contain a valid network CIDR, got "2a03:2800:0300::/64"


Error: module.security_groups_us_west_2.aws_security_group_rule.deploy_ssh: "ipv6_cidr_blocks.1" must contain a valid network CIDR, got "2a03:2800:0300::/64"
```

**Comment by danieldreier** [comment]
We are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now.

Would you please try and reproduce this on Terraform 0.12.24 and see if it's still an issue? I can't quite tell whether this is related to Terraform Core or the AWS provider, but I don't want to refer it over to them on a version of Terraform we're not longer investigating issues for - they will make the same request of you too.
