### ISSUE TITLE
Not able to import aws_volume_attachment using the command provided in terraform documentation

### ISSUE THREAD

**Issue by aykarageorge** [hashicorp/terraform#24790]
I have an EC2, EBS volume, and volume_attachment resources managed by terraform. After deploying it, I removed the EBS volume from EC2 and attached a new EBS volume manually from AWS console. Later I did terraform refresh and terraform import for the new EBS volume, which updated my tfstate with the new volume. But when I tried to import the aws_volume_attachment it throws the following error.

`**Error:** resource aws_volume_attachment doesn't support  import`

I'm using terraform version 0.12.24
![error](https://user-images.githubusercontent.com/10599547/80457015-351f8780-894c-11ea-96c9-9f55e3ff4fcb.jpeg)

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. Not all resources support import. Can you clarify - are you saying there is documentation listing this specific resource as importable, or are you using the import syntax as documented and saying this resource doesn't work with it?

I'm going to label it as an AWS provider issue, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by aykarageorge** [comment]
Hi Daniel,

Yes, it was mentioned as importable and import statement usage was also provided in the documentation.
