### ISSUE TITLE
AWS S3 bucket repeatedly wants to add grant block

### ISSUE THREAD

**Issue by mattw80** [hashicorp/terraform#24819]
terraform v0.12.24
aws provider v2.59.0

I have a canonical user id data source and an s3 bucket resource, snippet below:

```
data "aws_canonical_user_id" "current" { }

resource "aws_s3_bucket" "wcol_s3_ga_flow_log_bucket" {
	provider 			= aws.ire
	bucket 				= local.bucket_name
	force_destroy = false

	grant {
		id          = data.aws_canonical_user_id.current.id
		type        = "CanonicalUser"
		permissions = [ "FULL_CONTROL" ]
	}
....
}
```

The bucket is created successfully, but every time I run apply it thinks it needs to add the grant section, output as follows:

```
      + grant {
          + id          = "e17541c736260bbd734c1a8928178fccdebf787957bddf98bd87adcd6e8fdddc"
          + permissions = [
              + "FULL_CONTROL",
            ]
          + type        = "CanonicalUser"
        }
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
