### ISSUE TITLE
Detaching a root Volume after instance creation

### ISSUE THREAD

**Issue by bnprakash** [hashicorp/terraform#24811]
Hi,
Regarding to terraform aws.
I am trying to create a volume from snapshot and attach it as a root volume.

Is there a possibility to do detach the root volume when instance is created and use volume attachment to attach as a root volume.

Have my lifecycle configured for Snapshots , So I want to check if this option is available to help me instead of creating ami and use it.

I created an instance for TF. Detached the volume manually and tried the script again which is working perfectly.

But working on automating all steps. please help if you have any ideas.

Below is the script
data “aws_ebs_snapshot” “test” {
most_recent = true
owners = [“self”]

filter {
name = “tag:Name”
values = [“Prakash-test-snap”]
}
}

######aws_instance######
resource “aws_instance” “test-dr-instance” {
count = 1
ami = “ data.awsami.test−ami.id"instancetype="m5.large"keyname=" {var.key_pair_name}”
vpc_security_group_ids = [" var.securityid"]subnetid=" {var.subnet_id}"
availability_zone = “${var.az2}”
tags {
Name = “test-dr-inst”
Customer = “Prakash-test”
Environment = “test”
}

private_ip = “10.246.10.1”
associate_public_ip_address = false
lifecycle {
ignore_changes = [“ami”]

}
}

resource “aws_volume_attachment” “testing-dr” {
device_name = “/dev/sda1”
volume_id = “ awsebsvolume.test−dr.id"instanceid=" {aws_instance.test-dr-instance.id}”

}

####Ebs_volume####
resource “aws_ebs_volume” “test-dr” {
availability_zone = “ var.az2"snapshotid=" {data.aws_ebs_snapshot.test.id}”
type = “gp2”

tags = {
Name = “test-dr”
Project = “${var.Project}”
}
}

**Comment by danieldreier** [comment]
Hello!

It looks to me like you're asking for help with a Terraform provider, rather than reporting a particular bug. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
