### ISSUE TITLE
domjoin with count

### ISSUE THREAD

**Issue by ChrisCalzaretta** [hashicorp/terraform#24815]
### Terraform Version
12.24

```DomJoin Code```
resource "azurerm_virtual_machine_extension" "domjoin" {
name = "domjoin"
count = var.GenerateCount
virtual_machine_id    = element(azurerm_virtual_machine.vm,count.index).id
publisher = "Microsoft.Compute"
type = "JsonADDomainExtension"
type_handler_version = "1.3"
settings = <<SETTINGS
  {
  "Name": "${var.Domain}",
  "OUPath": "${var.OUPath}",
  "User": "${var.DomainAdmin}",
  "Restart": "true",
  "Options": "3"
  }
SETTINGS

protected_settings = <<PROTECTED_SETTINGS
{
"Password": "${var.DomainAdminPass}"
}
PROTECTED_SETTINGS
depends_on=[azurerm_virtual_machine.vm]
}
```


```Current Error
Error: Error in function call

  on ..\..\Modules\VM_Fusion\main.tf line 254, in resource "azurerm_virtual_machine_extension" "domjoin":
 254: virtual_machine_id    = element(azurerm_virtual_machine.vm,count.index).id
    |----------------
    | azurerm_virtual_machine.vm is empty tuple
    | count.index is 6

Call to function "element" failed: cannot use element function with an empty
list.
```

This works without a count.. Why cant i put a count on an extension?

**Comment by danieldreier** [comment]
Hello!

According to the error message you're getting, it looks like `azurerm_virtual_machine.vm` is empty. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
