### ISSUE TITLE
Terraform Build error

### ISSUE THREAD

**Issue by rasre28** [hashicorp/terraform#24826]
Hello - I'm trying to do a simple ec2 instance build via terraform but I keep getting this error. I've built in the past but this is something I'm seeing now . Also, the secret keys and access keys are correct and they work when I'm building the ec2 from the awscli.

I get this when I try to do the terraform plan. And this is the same issue with v0.12.24 and v.0.11.14 as well 

 

Error: Error refreshing state: 1 error occurred:
* provider.aws: error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
status code: 403, request id: e2e8e98e-df0c-4213-88e1-81657e38f082
Below is the terraform code where i tried to pass the creds as a file. I also tried to pass the keys directly in code as well. 

```
 cat aws.tf
provider "aws" {
region = "us-west-2"
shared_credentials_file = "/Users/tfsvr/.aws/credentials"
}
resource "aws_instance" "example" {
ami = "ami-0b4fhs8vdbec37f0d0c"
instance_type = "t2.micro"
  tags = {
    Name = "HelloWorld"
  }
 }
 
```

Please advise

**Comment by danieldreier** [comment]
Hello! I also had to take a few tries at getting auth set up correctly; this was not obvious to me the first few times and I had to do a bit of troubleshooting. It's possible that there's a bug here, but it's very difficult to differentiate bugs in this part of the codebase from configuration mistakes. For example, [this person](https://github.com/terraform-providers/terraform-provider-aws/issues/7418#issuecomment-460503690) reported "I've seen this particular error occur when there is no trust relationship between the user and the role that is trying to be assumed.". 

Without more evidence of a bug in terraform, the most likely cause of this is a configuration issue. It looks to me like you're asking for help with a Terraform provider, rather than reporting a particular bug. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
