### ISSUE TITLE
Panic - DNS provider fails to trap error in Zone Name

### ISSUE THREAD

**Issue by SteveBristow** [hashicorp/terraform#24820]
### Terraform Version

```
Terraform v0.12.24
+ provider.dns v2.2.0
```

### Terraform Configuration Files

```hcl 
provider "dns" {
  update {
    server        = "192.168.1.1"
  }
}
resource "dns_a_record_set" "test" {
    zone        = ".lab.environment.local."
    name        = "testrecord"
    addresses   = ["127.0.0.1"]
    ttl         = 300
}
...
```

### Crash Output
[crash.log](https://github.com/hashicorp/terraform/files/4559875/crash.log)

### Expected Behavior
An illegal zone name (preceding dot) should have been reported, and ignored or failed on - ideally at plan stage.

### Actual Behavior
DNS provider crashed Terraform.

### Steps to Reproduce
1. Create a TF template using the code excerpt above.  A functioning DNS server is not necessary.
2. `terraform init` to add the DNS provider to Terraform
3. `terraform apply`
4. Observe the successful plan - respond "yes" to apply.
5. Observe crash state.

### Additional Context
Terraform is running on Ubuntu on WSL.  It seems unlikely that this is the problem, as removing the preceeding dot from the Zone name results in success.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the DNS Terraform provider, rather than in core, because the crash log you provided has the panic happening in the DNS provider binary:
```
2020-04-30T18:00:41.083+0100 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2020-04-30T18:00:41.084+0100 [DEBUG] plugin.terraform-provider-dns_v2.2.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe484d9]
```

I'm going to label it as such, and the HashiBot will shortly migrate it over to the DNS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
