### ISSUE TITLE
Managed Identity for Logic Apps

### ISSUE THREAD

**Issue by Khushroo** [hashicorp/terraform#24829]
**Provider**: AzureRM
**Area of Interest**: Logic App Workflow

**Request**:
Logic App supports managed identity. However, when trying to provision a Logic App Workflow using Terraform one is unable to set the identity block like we can when we create a VM. This is an important feature. I would like this feature to be introduced. 

Cheers,
Khush.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
