### ISSUE TITLE
dynamic block only creates resources for one item in list 

### ISSUE THREAD

**Issue by dwschewe1** [hashicorp/terraform#24833]
I am using dynamic blocks to create environment variables for a list of lambda functions and the environment variables are creating created for the first lambda function but the apply is erroring out when the second lambda is created with this error:
```
 Error: environment: attribute supports 1 item maximum, config has 2 declared
```

tf.vars file : 
```hcl
#Lambda parameters 
lambda-functions =[ 
    {
    filename         = "activityIndexResolver-gj9e-user-filterBuilder.zip"
    function-name    = "air-gj9e-user-filterBuilder-test"
    iam-assume-role  = "air-test-filterBuilder-gj9e-user-exec-role"
    handler          = "filterBuilder.handler"
    runtime          = "nodejs12.x"
    memory-size      = 256
    env_vars         = {
      ActivityFiltersTable = "ActivityFilters-test-ci-custom-changes"
      FILTER_PROCESSOR = "air-test-filterProcessor-ci-custom-changes"
      RoleToProductMapTable = "RoleToProductMap-test-ci-custom-changes"
      UserRolePreferenceTable = "UserRolePreference-test-ci-custom-changes"
      }    
    },
    {
    filename         = "lambda-2.zip"
    function-name    = "lambda-2"
    iam-assume-role  = "user-exec-role2"
    handler          = "loadPrefFilterData.handler"
    runtime          = "nodejs12.x"
    memory-size      = 256
    env_vars         = {
      ActivityTable = "ActivityFiltersname"
      AddUsee = "addusername2
      WriteActivityFilterData = "air-test-writeFilterData-ci-custom-changes"      
      }    
    },
]


####
variable "lambda-functions" {
  type = list(object({
    filename        = string      
    function-name   = string   
    iam-assume-role = string
    handler         = string
    runtime         = string
    memory-size     = string
    env_vars = map(string)
    #tags     = map(string)
    }))
    default = []
    }


resource "aws_lambda_function" "lambda-functions" {
  count      = length(var.lambda-functions)
  
  filename             = lookup(var.lambda-functions[count.index], "filename")
  function_name        = lookup(var.lambda-functions[count.index], "function-name") 
  role                 = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:${join("", list(format("%s%s", "role/", lookup(var.lambda-functions[count.index], "iam-assume-role") )))}"  
  handler              = lookup(var.lambda-functions[count.index], "handler") 
  runtime              = lookup(var.lambda-functions[count.index], "runtime") 
  memory_size          = lookup(var.lambda-functions[count.index], "memory-size")
  tags                 = var.tags

  
    dynamic "environment" {
    for_each = var.lambda-functions
    #for_each = var.env_vars
    content {
      #variables = environment.value.env_vars   #var.env_vars   #env_vars
      variables = environment.value.env_vars 

      }
    }

```

**Comment by danieldreier** [comment]
Hi! Thanks for reporting this. I can't quite tell whether this is a request for help using terraform, or a bug. I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I have this partial code snippet but not a full reproduction case, and so I'm stuck.

Can you please restate your reproduction case such that it's simplified down to the bare essentials of the unexpected behavior so that I can copy-paste it and run it locally? Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies. If you are correct that dynamic blocks in terraform core have a bug, I think it should be possible to reproduce that using null resources.

**Comment by apparentlymart** [comment]
Hi @dwschewe1!

We didn't hear back from you after @danieldreier's recent question, so I'm going to close this issue. It seems like you may have a usage question about the AWS provider, in which case I suggest starting a topic in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). This repository is for Terraform Core only, and so issues here represent bugs or enhancement requests for Terraform Core, not about individual providers. Thanks!
