### ISSUE TITLE
Retrive frontdoorID from Graph

### ISSUE THREAD

**Issue by tikicoder** [hashicorp/terraform#24832]
### Current Terraform Version
```
Terraform Version
Terraform v0.12.24
provider.azurev2.5.0
...
```

### Use-cases
Azure has updated the Front Door Service to have a frontdoorID.  Can TF be updated to pull this information?  This ID is what you can use to lock down services to only accept connections from Front Door.
https://docs.microsoft.com/en-us/azure/frontdoor/front-door-faq

### Attempted Solutions
I manually use postman to get the information.

### Proposal
update TF to use the newer graph API and return the value

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
