### ISSUE TITLE
Elastic Pool vcore not updating

### ISSUE THREAD

**Issue by tikicoder** [hashicorp/terraform#24831]
Terraform Version
Terraform v0.12.24
provider.azurev2.5.0

If I create an elastic pool with the following settings and then someone manually updates the pool and TF tries to update it back it gives a general exception

resource "azurerm_mssql_elasticpool" "elasticpool" {
  name                = ...
  location            = ...
  server_name         = ...
  max_size_gb         = 50

  sku {
    name     = "GP_Gen5"
    tier     = "GeneralPurpose"
    family   = "Gen5"
    capacity = 4
  }

  per_database_settings {
    min_capacity = 0.25
    max_capacity = 2
  }
}

Debug Output
Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '31f2b96f-1f72-4da7-80d9-bd0498da2335'"

  on data/data.tf line 62, in resource "azurerm_mssql_elasticpool" "elasticpool":
  62: resource "azurerm_mssql_elasticpool" "elasticpool" {

##[error]Bash exited with code '1'.
Finishing: Deploy Infrastructure

Crash Output
N/A

Expected Behavior
I would expect TF to update it

Actual Behavior
You get an error

Steps to Reproduce
create an Azure SQL with elastic pool and per DB settings and manually change them.  Run TF and you should get the error.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
