### ISSUE TITLE
Update AWS Instance to allow in-place update of `user_data` or other internal attributes

### ISSUE THREAD

**Issue by julienlavergne** [hashicorp/terraform#2484]
Hi,

Here one issue that i encounter when I attach an ebs volume to an instance.

When i modify the aws_instance resource config (for example embedded user_data value), if my aws_ebs_volume references aws_instance availability_zone:  

    availability_zone = "${aws_instance.videomon.availability_zone}"

the ebs volume is destroyed and recreated. The ebs volume has persistent data and cannot be deleted like that…

but if 

    availability_zone = "${var.region}a"

 where the region value doesn't change, the ebs volume is not destroyed. Correct behavior for me.

Any idea how to ensure that one ebs volume should not be destroyed?

Maybe in the lifecycle { … }  a flag like prevent_destroy = true; but using this flag causes a headache when aws_instance resource needs modification.

Thanks. 

Simple snippet of code:

    resource "aws_ebs_volume" "videomon" {

        /* WRONG BEHAVIOR */
        /* in this case, terraform recreates the ebs volume */
        availability_zone = "${aws_instance.videomon.availability_zone}"
        /* CORRECT BEHAVIOR */
        /* in this case, terraform don't recreate the ebs volume */
        //availability_zone = "${var.region}a"
        snapshot_id = "snap-44beea6b"

        tags {
            Name = "videomon ebs volume"
        }

    }

    resource "aws_volume_attachment" "videomon" {
    device_name = "xvdf"
    volume_id = "${aws_ebs_volume.videomon.id}"
    instance_id = "${aws_instance.videomon.id}"
    }

    resource "aws_instance" "videomon" {

      connection {
        # The default username for our AMI
        user = "ubuntu"
      }

      key_name = "${aws_key_pair.videomon.key_name}"

      instance_type = "t2.micro"

      # Lookup the correct AMI based on the region
      # we specified
      ami = "${lookup(var.aws_amis, "${var.region}")}"

      # Our Security group to allow HTTP and SSH access
      vpc_security_group_ids = ["${aws_security_group.videomon.id}"]

      user_data = "${file(\"build/videomon/runtime.yml\")}"

        subnet_id = "${module.main-vpc.main-vpc-subnet-front-1-id}"

        associate_public_ip_address = false
    }

**Comment by catsby** [comment]
Hello @julienlavergne – 

If I understand correctly, you're wanting the change (or possible change) of the `availability_zone` on the EBS Volume and not destroy the volume, correct? Unfortunately, that doesn't seem like a thing the API allows us to do:

- http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVolumeAttribute.html

If you do not explicitly set the `availability_zone` in your instance, one is chosen for you when the API call is made (AWS makes this choice). Because it's chosen for you in this case, Terraform waits for the new value, and if it's different from what you have, issues the destroy, then recreates it to match the new zone. 

You can explicitly set the `availability_zone` of the `aws_instance`, which should prevent the re-creation.

Unfortunately at this time, I don't think there's anything Terraform can do for you.

**Comment by julienlavergne** [comment]
No. I don't want to change the availability_zone. 

If your modify an attribute like user_data in aws_instance resource, in this case the associated aws_ebs_volume is destroyed and recreated. That's no sense.

Modifiy aws_instance resource ok but it should not be destroy the ebs.

Maybe a modification of the states graph and aws_instance reverberates it to aws_ebs_volume or aws_volume_attachment.

**Comment by catsby** [comment]
Ah, that makes more sense, sorry for the confusion! 

Yes, the changes made to `aws_instance` that require the recreation of the instance will cascade down in certain situations. Yours is such a situation, because of the relationship you've defined by your volume inheriting the `availability_zone` of your instance. 

At present, the `user_data` attribute of `aws_instance` is one that requires recreation of the instance. It does look like we can update `user_data`:

- http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html

Though, the API mentions that some attributes require the instance be stopped. It's not clear which ones. I can take a look.

Thanks for clarifying!

**Comment by julienlavergne** [comment]
The problem does not concern only user_data modification but too security_group etc.

**Comment by catsby** [comment]
Some attributes cannot be modified without re-creation. Which ones are outlined in the schema 

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go

With `security_groups`, those are for use in EC2 Classic (or your default VPC, I think). If you specify the `vpc_security_group_ids` attribute, you can change them without destroying the instance. Specifically speaking about these, it's a limitation of the API on Amazons side, with regards to EC2 classic environment. 

Still, there may be some fields that are incorrectly specified as `ForceNew` in there, such as `user_data`. It's possible that over time the AWS API has changed to allow new updates

**Comment by catsby** [comment]
Hey @julienlavergne – I tried this out and it turns out that in order to modify the `user_data` here, the instance needs to be in a `stopped`. Unfortunately, at this time Terraform does not have the means of starting/stopping in a responsible manner. It's something we aim to add in the future, but there's nothing in place at this time.

**Comment by catsby** [comment]
Closing this for now. Thanks for writing in.
