### ISSUE TITLE
Terraform 0.13 Dev - variables are not recognized in provider block when use count.

### ISSUE THREAD

**Issue by marinsalinas** [hashicorp/terraform#24851]
### Terraform Version

```
Terraform v0.13.0-dev
+ provider registry.terraform.io/hashicorp/aws v2.59.0
```

### Terraform Configuration Files

```hcl
./modules/test/main.tf
variable "region" {}

provider "aws" {
  version = "~> 2.59.0"
  region  = var.region
  alias   = "this"
}

data "aws_region" "current" {
  provider = aws.this
}
```

```hcl
./main.tf
locals {
  secondary_clusters = [
    {
      region        = "us-east-2"
      replicas      = 3
      instance_size = "db4.large"
    },
    {
      region        = "us-east-1"
      replicas      = 5
      instance_size = "db4.large"
    },
    {
      region        = "us-west-2"
      replicas      = 12
      instance_size = "db4.large"
    }
  ]

}

module "test" {
  count  = length(local.secondary_clusters)
  source = "./modules/test"
  region = local.secondary_clusters[count.index].region
}
```

### Debug Output

https://gist.github.com/marinsalinas/8dea55ed182bc9b6991739bf27c5c7a6

### Expected Behavior

Initialize provider by region.

### Actual Behavior

The region variable is not recognized in the provider block when use count.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
We are waiting for this feature on Terraform since we need to create RDS regional clusters dynamically by a list of regions provided.

### References

- https://github.com/hashicorp/terraform/issues/17519

**Comment by danieldreier** [comment]
Hi @marinsalinas! I'm thrilled that you're trying out 0.13. Thanks! The module `count` feature isn't quite done in 0.13, so I'm not surprised you're having problems. I'll talk with the lead engineer on this feature and see what the expected behavior is here.

We are expecting to do a public beta of 0.13.0. Since you're already looking into it, you seem like a great person to get feedback from when that's available.

**Comment by jbardin** [comment]
Hi @marinsalinas,

Thanks for trying things out!

The underlying issue here is that you cannot have a provider configuration within a module that will be expanded. Due to some dependent work being sorted out, we have not implement the validation for this yet. In the future this config would fail with an error explaining the problem, instead of just silently failing to evaluate the provider.

While the ability to iterate over providers is something that would be used with module expansion, it is a separate feature in and of itself. What you are looking for is being tracked in #24476, which is a narrower use case of #9448.

**Comment by marinsalinas** [comment]
Oh, awesome! So following this idea to not use a provider configuration inside modules that will be expanded, I'm wondering if this configuration should work:

```hcl
./modules/test/main.tf

data "aws_region" "current" {}
```

```hcl
./main.tf
locals {
  secondary_clusters = [
    {
      region        = "us-east-2"
      replicas      = 3
      instance_size = "db4.large"
    },
    {
      region        = "us-east-1"
      replicas      = 5
      instance_size = "db4.large"
    },
    {
      region        = "us-west-2"
      replicas      = 12
      instance_size = "db4.large"
    }
  ]

}



provider "aws" {
  count = length(local.secondary_regions)
  region = local.secondary_regions[count.index].region
  alias   = local.secondary_regions[count.index].region
}

module "test" {
  count  = length(local.secondary_clusters)
  providers = {
    aws = "aws.${local.secondary_regions[count.index].region}" //maybe - aws = "aws[count.index]
  }
  source = "./modules/test"
  region = local.secondary_clusters[count.index].region
}
```

**Comment by pselle** [comment]
@marinsalinas Not quite -- your example includes a few things that won't work. I recommend checking out the related issues @jbardin linked as they're relevant to what you're trying to do here :)

Meanwhile, we interpreted the issue you opened here as "provider blocks in modules using `count` aren't working" and I've merged a PR that gives an error message clarifying that you cannot configure providers in a module that will expand (count or for_each).

Thank you for the report!
