### ISSUE TITLE
subnet_name parameter in aci_connecor_linux code block

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [hashicorp/terraform#24853]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
  addon_profile {
    aci_connector_linux {
      enabled = true
      subnet_name = var.subnetName
    }
  }
```

### Debug Output
```
Error: Error creating Managed Kubernetes Cluster "cluster_name" (Resource Group "resource_group_name"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ACIConnectorRequiresAzureNetworking" Message="ACI Connector requires azure network plugin" Target="AddonProfiles.ACIConnectorLinux"
```

### Expected Behavior
AKS cluster gets created

### Actual Behavior
AKS cluster failed with the "subnet_name" parameter

### Additional Context
In the documentation found here:https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

It states that the `subnet_name` parameter `under aci_connector_linux` is optional, but in fact, it is mandatory. An error will be received (attached here) if the subnet_name param is not used. The documentation needs to be updated to be "required" instead of "optional".

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
