### ISSUE TITLE
Child module using wrong Provider/AWS CLI Profile

### ISSUE THREAD

**Issue by krazykhris875** [hashicorp/terraform#24877]
Hi there. I'll provide as much detail as I can.

**Terraform version:** 0.12.24
**OS:**  Windows 10 Pro | 10.0.17763 Build 17763

My basic project structure is: 
```
-environments (directory)
  -preview.tfvars
  -test.tfvars
-version.tf
-variables.tf
-outputs.tf
-terraform.tf
-vpc-security-groups.tf
-ec2-bastion.tf
```

There are also some other files, each of which contains a certain section of the infrastructure. For example, `s3.tf` creates my S3 buckets. All of those files are raw terraform as part of the root module, no child modules or anything. `vpc-security-groups.tf` and `ec2-bastion.tf`, however, use child modules.

I have multiple AWS CLI profiles for multiple AWS accounts setup on my machine. The problem I'm having is that the raw terraform files, as well as the `vpc-security-groups` child module work fine. But when I get to the `ec2-bastion` child module, it doesn't use the named AWS CLI profile I have set in my provider/backend (in `terraform.tf`), and instead uses my default one, attempting to create resources in the wrong account (which then fails because other dependencies are not fulfilled).

**terraform.tf** looks like this: 
```
terraform {
  backend "s3" {
    encrypt = true
    bucket = "client-test-terraform-remote-state"
    region = "us-east-1"
    key = "test_terraform_state"
    profile = "client_test"
  }
}

provider "aws" {
  version = "~> 2.0"
  region  = "us-east-1"
  profile = "client_test"
}

data "terraform_remote_state" "networking" {
  backend = "s3"
  config = {
    bucket  = var.state_bucket
    region  = var.region
    key     = var.key
    profile = var.profile
  }
}

data "terraform_remote_state" "bastion" {
  backend = "s3"
  config = {
    bucket  = var.state_bucket
    region  = var.region
    key     = var.key
    profile = var.profile
  }
}
```

**vpc-security-groups.tf** (this initializes a child module custom built by my co-workers)
```
module "networking" {
  source             = "git@our-networking-module.git"
  client_name        = var.client_name
  profile            = var.profile
  contact            = var.contact
  availability_zones = var.availability_zones
  env                = var.env
  resource_name      = "${var.client_name}-${var.env}-vpc"
  vpc_cidr           = var.vpc_cidr
  region             = var.region
  enable_nat_gateway = var.enable_nat_gateway
  single_nat_gateway = var.single_nat_gateway
  http_ports         = var.http_ports
}
```

**ec2-bastion.tf** (this initializes another child module custom built by my co-workers)
```
module "bastion" {
  source = "./terraform-aws-bastion" #Currently running from a local copy rather than git
  region = var.region
  client_name = var.client_name
  profile = var.profile
  contact = var.contact
  env = var.env
  vpc_security_group_id = module.networking.sshlistener_sg[0]
  core_public_subnet_ids = module.networking.public_subnet_ids[0]
}
```

The ec2-bastion module is very simply, its source files contain only a `main.tf` and `variables.tf`. There is nothing in either to try to initialize a new provider or backend. As I understand it, based on the docs here: https://www.terraform.io/docs/configuration/modules.html -- If no provider is explicitly set for the child module, it should use the default provider from the root module (in my `terraform.tf`, which you can see above). This seems to hold true for my `vpc-security-groups` module, but not for my `ec2-bastion` module. I'm completely out of ideas for what is causing this. Any help would be appreciated it.

**Comment by krazykhris875** [comment]
Forgot to include, to run I am using Powershell and use `terraform init -var-file="environments/test.tfvars"` followed by `terraform apply -var-file="environments/test.tfvars"`

**Comment by jsf9k** [comment]
I am suddenly seeing a very similar problem when applying [this example code](https://github.com/cisagov/molecule-iam-user-tf-module/tree/develop/examples/basic_usage).

**Comment by danieldreier** [comment]
Hello! This is a really well written question, but we use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. If I have misunderstood and you're confident that you're reporting a bug in terraform core, please feel free to reach out at ddreier@hashicorp.com.

**Comment by jsf9k** [comment]
@krazykhris875, the source of our problem turned out to be that we had proxy provider blocks in submodules that contained more variables than just the `alias` variable.  In particular, we were defining `region` inside those blocks in order to make `terraform validate` pass. 

This is because providing the `region` argument actually results in an explicit provider (using the default profile) being created.  As stated in the penultimate paragraph in [this section](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly), "a proxy provider block is one that is either completely empty or that contains only the `alias` argument."

See [this commit](https://github.com/cisagov/molecule-iam-user-tf-module/pull/3/commits/5da4a4c73683d48d494ebf0762580834667e187c) for the change that actually fixed things for us.

Just mentioning all this in case your problem is due to the same mistake.
