### ISSUE TITLE
Tags are not being applied to instances in aws_spot_instance_request resources

### ISSUE THREAD

**Issue by machadovilaca** [hashicorp/terraform#24880]
### Terraform Version

Terraform v0.12.24

### Terraform Configuration Files

```hcl
resource "aws_spot_instance_request" "spot_node" {
  ami = "ami-0e312952b4cc28a7f"
  instance_type = "t3.small"
  
  wait_for_fulfillment = true

  tags = {
    Name   = "Spot-node-1"
  }
}
```

### Expected Behavior

Spot instance with name "Spot-node-1" created.

### Actual Behavior

Spot instance with no name created.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References
- https://github.com/hashicorp/terraform/issues/3263

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
