### ISSUE TITLE
Error: *.terraform.EvalSequence, *.terraform.EvalRefresh Access Denied 

### ISSUE THREAD

**Issue by codewithshri** [hashicorp/terraform#24888]
I am running terraform "Queue Destroy Plan" through tfe workspace and started getting error related to *.terraform.EvalSequence, *.terraform.EvalRefresh Access Denied 
I have tried by setting user permissions to S3:* but still ending with same issue.

### Terraform Version
Terraform v0.12.24

**Comment by danieldreier** [comment]
Hello! It looks like you’ve reported an issue around using terraform on Terraform Cloud or Terraform Enterprise. This is the issue tracker for the open source Terraform tool, and it sounds to me like you're reporting a TFE-specific issue that we can't help with. 

Please open a support ticket at https://support.hashicorp.com/ or email support@hashicorp.com using your work email. I'm going to close this issue because it doesn't seem to be something we can help with from the open source side, and I'm confident that support will take care of you.
