### ISSUE TITLE
Provide link to the latest binary release

### ISSUE THREAD

**Issue by j4zzcat** [hashicorp/terraform#24890]
Kindly provide a download link to the latest binary release, i.e., at the time of writing this feature request, `https://releases.hashocorp.com/terraform/latest/terraform_linux_amd64.zip` will download `https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip`.

**Comment by pkolyvas** [comment]
Hi @j4zzcat,

This is by design. Here's a comment with our reasoning: https://github.com/hashicorp/terraform/issues/9803#issuecomment-257903082

Also a summarized workaround from another issue which may help get you somewhere close: https://github.com/hashicorp/terraform/issues/18290#issuecomment-398716720
