### ISSUE TITLE
aws_eip empty tuple error

### ISSUE THREAD

**Issue by demisx** [hashicorp/terraform#24909]
### Terraform Version
v0.12.24

Running this simple snippet of code:

```tf
resource "aws_eip" "lb" {
  vpc = true
}

resource "aws_lb" "node_port" {
  name = "node-port-nlb"
  internal = false
  load_balancer_type = "network"

  subnet_mapping  {
    subnet_id = "subnet-07d0da*****81f758a"
    allocation_id = aws_eip.lb.id
  }
}
```

Outputs the following error. Not sure if this is a bug or I am missing something obvious:

```sh
$ terraform plan
Error: Unsupported attribute

  on elb.tf line 26, in resource "aws_lb" "node_port":
  26:     allocation_id = aws_eip.lb.id
    |----------------
    | aws_eip.lb is empty tuple

This value does not have any attributes.
```

**Comment by demisx** [comment]
I don't know why, but this works after renaming `lb` -> `lb2`? Is there some kind of cache that needs to be manually purged?

```tf
# This works
resource "aws_eip" "lb2" { # <- changed lb -> lb2
  vpc = true
}

resource "aws_lb" "node_port" {
  name = "node-port-nlb"
  internal = false
  load_balancer_type = "network"

  subnet_mapping  {
    subnet_id = "subnet-07d0da*****81f758a"
    allocation_id = aws_eip.lb2.id # <- changed lb -> lb2
  }
}
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
