### ISSUE TITLE
Provider case mistake fails cryptically without any indication of what the problem may be. 

### ISSUE THREAD

**Issue by mathieulj** [hashicorp/terraform#24914]
### Terraform Version
```                                 
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
provider "AWS" {
    access_key = "..."
    secret_key = "..."
    region = "..."
}
```

### Debug Output
[terraform_failure.log](https://gist.github.com/mathieulj/e45042e7933c9f6a3ffbc5a07cb50aed)

### Expected Behavior
Ether the downloaded plugin should be used or the case mismatch should be reported to the user for them to correct their configuration. 

### Actual Behavior
Terraform claims it did not find a suitable plugin and says it's a bug needing a bug report.

### Steps to Reproduce
1. `terraform init`

### Additional Context
Modifying `AWS` to `aws` in the configuration fixes the error message.

### References
n/a

**Comment by danieldreier** [comment]
Thanks! Good catch. This is super weird behavior and I appreciate you reporting it. I've reproduced it myself.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @mathieulj!

We've be doing a lot of work in the provider installation code for the forthcoming Terraform 0.13 release, which will include a way to auto-install third-party providers as well as official providers. As part of that, we introduced a well-defined addressing scheme for provider names, where `aws` is interpreted as [`hashicorp/aws`](https://registry.terraform.io/providers/hashicorp/aws).

We therefore now have a centralized parser for provider addresses which does consistent normalization of provider addresses. One of the rules that parser implements is that the namespace and type ("hashicorp" and "aws") are both case-insensitive, normalized to lowercase, and because we now use that parser consistently for all situations where provider addresses appear, the configuration you shared is now `terraform init`-able with a `terraform` build from the current master branch...

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v2.61.0...
- Installed hashicorp/aws v2.61.0 (official provider)

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/aws: version = "~> 2.61.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

Unfortunately the problem has now moved downstream one step. I added a resource to the configuration, giving this:

```hcl
provider "AWS" {
  region = "us-west-2"
}

resource "aws_instance" "foo" {
}
```

Terraform assumes that a resource type named `aws_instance` belongs to the `aws` provider by default, but it seems like _that_ lookup is still being done case-sensitively, causing Terraform to complain that there's no configuration for provider "aws":

```
$ terraform validate

Error: Missing required argument

The argument "region" is required, but was not set.
```

Curiously, even explicitly setting the provider (overriding the default mapping) didn't work:

```hcl
provider "AWS" {
  region = "us-west-2"
}

resource "aws_instance" "foo" {
  provider = AWS
}
```

So it looks like there's a bug lurking in here _somewhere_ where it's trying to compare a case-normalized string with a non-normalized string and thus it can never succeed when the provider name isn't given in lowercase.

I'm going to pass this on to the team that's working on these new provider features for Terraform 0.13, because it does seem like something's not quite right here but I'm lacking sufficient context to take a good guess as to where exactly the problem is.

Thanks again for reporting this! It seems that you've pre-emptively caught a bug in the 0.13 release. :wink:

**Comment by mathieulj** [comment]
:smile: Glad to be of help. Thank you for the detailed breakdown, it was quite interesting.
