### ISSUE TITLE
terraform 0.12.9; how to replace a string with a literal \

### ISSUE THREAD

**Issue by tommyjcarpenter** [hashicorp/terraform#24918]
### Terraform Version
0.12.9

How do you replace a string like with a literal backslash `\`? For example `,` -> `\,`

`replace(",", "\,", "\\,")` leads to a literal `\\,`, but `replace(",", "\,", "\,")` complains that you can't escape `,`. Adding more `\` like `\\\` is also not fruitful.

**Comment by danieldreier** [comment]
Hello 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

I'm going to close this because this is a question rather than a bug report or feature enhancement request.
