### ISSUE TITLE
Crash on AWS VPC refresh

### ISSUE THREAD

**Issue by morgan-monzingo** [hashicorp/terraform#24922]
### Terraform Version

```
Terraform v0.12.6
```

### Terraform Configuration Files

https://drive.google.com/file/d/1PboWaRieRjPuJNS2qH9En98L2j34xYgb/view?usp=sharing

### Debug Output

[debug output](https://gist.github.com/morgan-monzingo/59b38ef1306e8953a195c33a79702d9e)

### Crash Output

Crash output never saved. 

### Expected Behavior

Expecting the plan to run or crash to close out and print a crash log. Instead it hangs on the crash without exiting. Happens both in console and terraform cloud instance.

### Steps to Reproduce

> terraform init
> terraform plan

**Comment by danieldreier** [comment]
Hi! Thanks for reporting this. Based on your crash log, I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I don't know what terraform code you wrote that produced this crash, and so I'm stuck.  

Can you please restate your reproduction case such that I can copy-paste it and run it locally?

**Comment by morgan-monzingo** [comment]
@danieldreier  I've attached a link to the configuration to the original comment. Please let me know if you have any issue opening them.

**Comment by danieldreier** [comment]
Can you please put it in a github gist or inline it here? I don't have access to that google doc.

**Comment by apparentlymart** [comment]
Hi @morgan-monzingo,

We didn't hear back from you after @danieldreier's latest question, so I'm going to close this issue. 

I think you've found the same problem as discussed in #22580, which was fixed in Terraform v0.12.8. Upgrading to the latest 0.12 release will therefore hopefully fix this problem for you. If not, please share your reproduction case as a [GitHub gist](https://gist.github.com/) as previously requested, and then we can try to investigate it further. Thanks!
