### ISSUE TITLE
Creating azurerm_data_factory_integration_runtime_managed using SSISDB on managed instance fails.

### ISSUE THREAD

**Issue by MariusEng** [hashicorp/terraform#24926]
Creating SSISDB on managed instance fails as catalog_info block requires pricing_tier, which is not supported on managed instance.

pricing_tier needs to support null values, or not be required.

https://www.terraform.io/docs/providers/azurerm/r/data_factory_integration_runtime_managed.html#pricing_tier

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
