### ISSUE TITLE
Crashes: azurerm_monitor_diagnostic_setting

### ISSUE THREAD

**Issue by Anbukugan** [hashicorp/terraform#24925]
Getting crashed while trying to create a diagnostic setting using azurerm_monitor_diagnostic_setting in Terraform.

### Terraform (and AzureRM Provider) Version
Terraform v0.12.24
provider.azurerm v2.9.0

### Affected Resource(s)
azurerm_monitor_diagnostic_setting

### Terraform Configuration Code
provider "azurerm" {
    features {}
}
resource "azurerm_monitor_diagnostic_setting" "example" {
  name               = "examplediag"
  target_resource_id = "/subscriptions/sub-id/resourceGroups/vm-log-test/providers/Microsoft.Network/virtualNetworks/vnet-name"
  storage_account_id = "/subscriptions/sub-id/resourceGroups/test-policy/providers/Microsoft.Storage/storageAccounts/storage-account-name"

  metric {
    category = "AllMetrics"
  }
}
### Crash log
[crash.log](https://github.com/hashicorp/terraform/files/4614544/crash.log)

### Error Occured
Error: rpc error: code = Unavailable desc = transport is closing
panic: runtime error: index out of range [0] with length 0

### Steps to Reproduce
terraform apply

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. In the crash log, you can see:
```
2020-05-12T14:23:23.144+0530 [DEBUG] plugin.terraform-provider-azurerm_v2.9.0_x5.exe: panic: runtime error: index out of range [0] with length 0
```
This shows that the azurerm provider binary is what crashed.

I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
