### ISSUE TITLE
aws_ami_from_instance doesn't stop EC2 instance while creating an AMI

### ISSUE THREAD

**Issue by ltartarini** [hashicorp/terraform#24934]
### Terraform Version
```
0.12.20
```

### Terraform Configuration Files

```hcl
resource "aws_ami_from_instance" "this" {
  name               = "my_ami"
  source_instance_id = data.aws_instance.this.id
}
```

### Expected Behavior

According to the docs at https://www.terraform.io/docs/providers/aws/r/ami_from_instance.html:
"This resource is best applied to an instance that is stopped when this instance is created, so that the contents of the created image are predictable. When applied to an instance that is running, the instance will be stopped before taking the snapshots and then started back up again, resulting in a period of downtime."

### Actual Behavior

EC2 instance is not stopped at all while the AMI is created.

### References
- #16009

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
