### ISSUE TITLE
Is there any way to know the number of resources used at the provider level ( count the number of resources )

### ISSUE THREAD

**Issue by papineni87** [hashicorp/terraform#24963]
I want to know how many resources are used under single provider. This is needed for some telemetry data i want to get from the provider level.

provider x {
............
}

resource "test1" "example" {
...................
}

resource "test2" "example2" {
........................
}

So where can i get the resources used in current configuration file  in provider initialisation ? or at the terraform core ? If it is not possible at the provider , is there any resource telemetry available in terraform ? like how many resources are being used per provider ?

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
