### ISSUE TITLE
Terraform support kustomize provider

### ISSUE THREAD

**Issue by roman-judin-dragon** [hashicorp/terraform#24966]
### Use-cases
**1.** Delivery basic Kubernetes provisioning via terraform code, which typically came as helm charts with CRD inside for example:
- istio
- cert-manager
- Kong ingress
- HC Vault
- etc

**2.** Increase the feedback on what changes will be applied for Kubernetes resources
In the same way, how we see terraform code to implement (all possible) Kubernetes manifests.
The `helm_release` [1] resource does not show the full plan of expected changes (hidden by helm chart)

**3.** Resources from a previous apply not in the current apply are not purged.
We had that observation for `helm_release` [1] resource during provision few charts - there are a lot leftovers that need to be purged after terminating `helm_release`

**4.** Delivery Kubernetes CRD changes via TFE / app.terraform.io
Otherwise, the community provider [1] has to be imported as binary instead of natively support by terraform in the same way how we saw at kubectl [3] binary.

### Proposal
Include/import `kbst/terraform-provider-kustomize` [2] into terraform providers [4]

### References
[1] https://www.terraform.io/docs/providers/helm/r/release.html
[2] https://github.com/kbst/terraform-provider-kustomize
[3] https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
[4] https://github.com/terraform-providers

**Comment by danieldreier** [comment]
@roman-judin-dragon I think this a great idea. However, this github repository is for bugs and enhancement requests to Terraform core -  just the CLI. The process for getting your provider added to the terraform-providers organization is documented at https://www.terraform.io/guides/terraform-provider-development-program.html#4-review. 

I also want to point out that with Terraform 0.13 coming out soon, it will be [much easier](https://www.hashicorp.com/blog/adding-provider-source-to-hashicorp-terraform/) to use community providers, so the need to do this to support your users will probably go down pretty soon.

I'm going to close this out because it's not quite the right place to have a discussion about it. If you have any trouble getting the information you need, feel free to reach out to me at ddreier@hashicorp.com. I'm the engineering manager for the core team, so I can't approve partner providers, but I'm happy to get you in touch with the right folks if the documented process doesn't work out.
