### ISSUE TITLE
aws_cloudfront_distribution: InvalidArgument: The parameter Logging Bucket does not refer to a valid S3 bucket

### ISSUE THREAD

**Issue by cat-turner** [hashicorp/terraform#24962]
Hi
According to the docs, we need to specify the logging bucket as 

myawslogbucket.s3.amazonaws.com

https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#logging-config-arguments

AWS is planning to deprecate path style access logs in favor of virtual. I am unable to point to the s3 bucket in any other way. Will we need to update this?

https://forums.aws.amazon.com/ann.jspa?annID=6776
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
