### ISSUE TITLE
Cross resource's dependency

### ISSUE THREAD

**Issue by maZahaca** [hashicorp/terraform#24974]
### Terraform Version
v0.12.24

### Terraform Configuration Files

```hcl
locals {
  do_token = ""
  domain = "example.com"
}

provider "digitalocean" {
  token = local.do_token
}

resource "digitalocean_droplet" "web" {
  name = "web-1"
  size = "s-1vcpu-1gb"
  image = "ubuntu-18-04-x64"
  region = "nyc3"
}

resource "digitalocean_loadbalancer" "lb1" {
  name = "loadbalancer-1"
  region = "nyc3"

  forwarding_rule {
    entry_port = 80
    entry_protocol = "http"

    target_port = 80
    target_protocol = "http"

    certificate_id = digitalocean_certificate.cert1.id
  }

  healthcheck {
    port = 22
    protocol = "tcp"
  }

  droplet_ids = [
    digitalocean_droplet.web.id
  ]

  depends_on = [
    digitalocean_domain.domain1,
    digitalocean_certificate.cert1
  ]
}

resource "digitalocean_domain" "domain1" {
  name = local.domain
  ip_address = digitalocean_loadbalancer.lb1.ip

  depends_on = [
    digitalocean_loadbalancer.lb1,
  ]
}

resource "digitalocean_certificate" "cert1" {
  name = "example-com-cert-1"
  type = "lets_encrypt"
  domains = [
    local.domain,
  ]
  depends_on = [
    digitalocean_domain.domain1
  ]
}
```

### Crash Output
```
Error: Cycle: digitalocean_certificate.cert1, digitalocean_loadbalancer.lb1, digitalocean_domain.domain1
```

### Expected Behavior
I want to have an option to do re-provisioning.
For example I pick domain to dummy ip address,  Letsencypt validates domain via DNS and issues a certificate and then it creates loadbalancer and then execute re-provisioning for domain to set correct ip address retrieved from loadbalancer

### Actual Behavior
Currently this behavior not possible to be executed.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by danieldreier** [comment]
Hi @maZahaca! Thanks for asking about this.

Based on the information you've provided, I can't quite tell whether you're asking us to put an enhancement request on our backlog, or if you're looking for guidance about how to solve this particular use case. I see two options:

1.  If you are looking for immediate guidance on how to implement this, I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you want us to be aware of this use case and take it into consideration for future enhancements and refactors, we can label it as an enhancement request. In that case, we'd need a more detailed explanation of your use case, so we can understand your whole workflow. 

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting. I'm going to close this for now, because I think the community forum is the right approach. Feel free to leave a note or contact me at ddreier@hashicorp.com to re-open this if you'd rather work up a more detailed workflow and file this as an enhancement request.
