### ISSUE TITLE
New TF function with nslookup/host functionality

### ISSUE THREAD

**Issue by cgetzen** [hashicorp/terraform#24984]
### Current Terraform Version

```
v0.12.25
```

### Use-cases
For my AWS use-case: Assigning EIPs to MSK's brokers (to enable public access). The output of the resource is hostnames, and there doesn't seem to be a way to resolve the hostnames to IPs.

I'm sure there are other use cases! 

### Attempted Solutions
Using https://github.com/matti/terraform-shell-resource, which seems not great. 

### Proposal
Add terraform function to perform this lookup.

### References
https://github.com/hashicorp/terraform/issues/20444

**Comment by danieldreier** [comment]
@cgetzen I don't quite understand your use case - can you provide a bit of HCL example to show where the EIP and MSK resources don't map up correctly, maybe give an example of what this would look like with an nslookup function?

**Comment by cgetzen** [comment]
`aws_msk_cluster` has the attribute `bootstrap_brokers`, which looks something like:

```
long-amazon-private-hostname:9094,host2:9094,host3:9094
```

The simplest way to expose MSK to the public is [documented here](https://repetitive.it/2020/01/14/aws-msk-how-to-expose-the-cluster-on-the-public-network/index.html), but it involves assigning EIPs to each of the private IPs that the bootstrap brokers resolve to.

I would like to convert bootstrap_brokers to a list of private IPs in HCL using split() and a new lookuphost() function, so that I can create EIPs for each one.

Something like this:
```
locals {
  ips =   [for x in  split(",", aws_msk_cluster.example.bootstrap_brokers)
 : lookuphost(split(":",x)[0])]
}
```

Here's what I've got so far on a dev branch:
```
> [for x in  ["bing.com:543", "reddit.com:543", "example.com:543"]: lookuphost(split(":",x)[0])]
[
  [
    "13.107.21.200",
    "204.79.197.200",
    "2620:1ec:c11::200",
  ],
  [
    "151.101.1.140",
    "151.101.129.140",
    "151.101.193.140",
    "151.101.65.140",
  ],
  [
    "2606:2800:220:1:248:1893:25c8:1946",
    "93.184.216.34",
  ],
]
```

**Comment by apparentlymart** [comment]
Hi @cgetzen,

For operations that interact with external hosts over the network (like DNS servers, in this case) we prefer to use data sources rather than functions so that the operation can be modeled as a node in the dependency graph rather than as part of decoding the configuration.

[The `dns` provider](https://registry.terraform.io/providers/hashicorp/dns) has some data sources for doing various kinds of DNS lookups, including looking up `A` and `AAAA` records as seems to be needed for your use-case here.

_In principle_ the DNS provider could be used to get what you were looking for here, I think:

```hcl
locals {
  addrs = split(",", aws_msk_cluster.example.bootstrap_brokers)
  hosts = toset([for x in local.addrs : split(":",x)[0]])
}

data "dns_a_record_set" "brokers" {
  for_each = local.hosts

  host = each.value
}

data "dns_aaaa_record_set" "brokers" {
  for_each = local.hosts

  host = each.value
}

output "broker_ip_addresses" {
  value = {
    for h in local.hosts : toset(concat(
      data.dns_a_record_set.brokers.addrs,
      data.dns_aaaa_record_set.brokers.addrs,
    ))
  }
}
```

The wrinkle with this today is that Terraform will encounter a chicken/egg problem trying to evaluate this: until `aws_msk_cluster.example` has been created for the first time, the number of elements in `bootstrap_brokers` will be unknown and so Terraform won't be able to produce a plan for those two `data` blocks. Unfortunately this means that in order to follow this strategy today would require an initial apply with `-target` in order to bypass that chicken/egg problem during initial bootstrapping:

```
terraform apply -target=aws_msk_cluster.example
```

Once the cluster is created, subsequent changes would be applyable with `terraform apply` as normal. That's far from ideal, I realize, but I think is the best way to get this done with Terraform as it currently works. #4149 is representing a possible longer-term architecture change to address this, but there are several other incremental things we need to get done before we could get there. :confounded:

I think we cannot accept `nslookup` (or similar) as a built-in function though, because that would then (for example) cause a configuration using it to perform network lookups during `terraform validate`, which violates the expectations of that command being local-only and runnable in an isolated environment.

**Comment by danieldreier** [comment]
@apparentlymart if I understand evaluation order correctly, functions will also only work for hosts that already exist before terraform starts applying, because functions exist outside the graph and run before any resources are created. If you have a working prototype, I suspect that it's only working because your resources already exist. 

This is similar to a common issue where people use the file function to try to read files that were created using a local_file provisioner and then run into these graph dependency problems. I see those come in a lot, reported as bugs by people who don't understand, and I'm concerned that if we add another function like that people will reach for it and hit similar problems. I think Martin is probably correct that a data source is the correct approach.

**Comment by cgetzen** [comment]
Thanks! I really appreciate the run down, it helps a ton (especially why nslookup breaks validation) :)
