### ISSUE TITLE
How to get resource names that are been defined in custom provider ?

### ISSUE THREAD

**Issue by papineni87** [hashicorp/terraform#24980]
I have a provider x,  and i define 3 resources in my .tf file. For telemetry purpose i want to know how many resources are being used in my .tf file at the provider level code ( i.e., provider.go ).

Is there any available option to get the resource telemetry data in terraform ?

I do can get the resource names whenever code touches the resource level code, but i am interested at the provider level to get the current resource usage without going to the resource level code.

**Comment by danieldreier** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. This is a totally valid question, but this isn't where we handle them. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
