### ISSUE TITLE
azure still creating ...

### ISSUE THREAD

**Issue by ravirachamadugucap** [hashicorp/terraform#24997]
Hi,

The build is not getting completed, getting the below output

Terraform v0.12.20
+ provider.azurerm v1.42.0

[buildScript.txt](https://github.com/hashicorp/terraform/files/4654729/buildScript.txt)
[terraform.log](https://github.com/hashicorp/terraform/files/4654730/terraform.log)

azurerm_virtual_machine.avm_genie05: Still creating... [14m41s elapsed]
azurerm_virtual_machine.avm_genie05: Still creating... [14m51s elapsed]

**Comment by danieldreier** [comment]
Hello!

It looks to me like you're asking for help with a Terraform provider, rather than reporting a particular bug. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
