### ISSUE TITLE
Dependency chain error - leads to multiple terraform applies to fix

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#25004]
### Terraform Configuration Files
```hcl
resource "google_storage_bucket" "audit_logs" {
  count              = var.enabled
  bucket_policy_only = true
  depends_on         = [ google_project_service.logs_storage ]
  name               = "my-audit-logs"
  location           = "us-east1"
  project            = google_project.logs[count.index].number

  provider = google.logs
}

resource "google_logging_organization_sink" "audit" {
  count            = var.enabled
  depends_on       = [ google_project_service.logs_logging ]
  name             = "org-wide-audit"
  org_id           = var.org_id
  destination      = "storage.googleapis.com/${google_storage_bucket.audit_logs[count.index].name}"
  filter           = "logName=(organizations/${var.org_id}/logs/cloudaudit.googleapis.com%2Factivity OR organizations/${var.org_id}/logs/cloudaudit.googleapis.com%2Fdata_access OR organizations/${var.org_id}/logs/cloudaudit.googleapis.com%2Fsystem_event)"
  include_children = true
  provider         = google.logs
}

resource "google_project_iam_binding" "logs_writer" {
  count   = var.enabled
  project = google_project.logs[count.index].number
  role    = "roles/storage.objectCreator"
  members = [
    google_logging_organization_sink.audit[count.index].writer_identity,
  ]
  provider = google.logs
}
```

### Expected Behavior

This all terraformed correctly in place. Later on I realised the bucket was created in the wrong region, so I changed the region. Terraform correctly identified that the bucket would have to be replaced, so it was marked as replaced with a plan showing 1 destroy and 1 create. I would have expected the sink and iam binding to be tainted, and also destroyed and created as they have dependenies on the bucket, but terraform does not appear to delete them in the plan. 

### Actual Behavior

On execution, the bucket was replaced. 
Terraform does not list the sink or the iam binding as needing replacing. 
Terraform therefore leads into a state which doesnt work properly. 
A forced taint was required on the dependent resources so that it would rebuild them

### Steps to Reproduce

terraform plan
terraform apply
(change bucket region)
terraform apply again
terraform taint google_project_iam_binding.logs_writer
terraform taint google_logging_organization_sink.audit
terraform apply again

### Additional Context

This was actually a distilled simpler version of a much more thorny problem where I had 70 IAM permissions applied on the bucket. In that case, once again it was listed as 1 destroy 1 create (for the bucket), and on terraform apply the bucket was replaced. A further terraform plan then suddenly realised that 70 IAM permissions needed creating again. 

Obviously terraform should do it all at once, and something is going wrong here.

**Comment by danieldreier** [comment]
This use case makes sense, and I really appreciate you doing the work of simplifying the reproduction case down from 70 IAM permissions. If I'm reading this right, I think that this improvement would have to happen in the Google provider rather than terraform core, because there is no explicit relationship between the `google_logging_organization_sink` resource and the `google_storage_bucket` resource you're recreating - the storage bucket is simply passed along as a string, and isn't explicitly a dependency.

I am curious if you'd get the desired behavior if you add a `google_storage_bucket.audit_logs` `depends_on`, e.g.

```hcl
resource "google_logging_organization_sink" "audit" {
  count            = var.enabled
  depends_on       = [ google_project_service.logs_logging, google_storage_bucket.audit_logs ]
  name             = "org-wide-audit"
  org_id           = var.org_id
  destination      = "storage.googleapis.com/${google_storage_bucket.audit_logs[count.index].name}"
  filter           = "logName=(organizations/${var.org_id}/logs/cloudaudit.googleapis.com%2Factivity OR organizations/${var.org_id}/logs/cloudaudit.googleapis.com%2Fdata_access OR organizations/${var.org_id}/logs/cloudaudit.googleapis.com%2Fsystem_event)"
  include_children = true
  provider         = google.logs
}
```

If that doesn't work, I think we'd need to move this issue to the Google provider.

**Comment by gtmtech** [comment]
Thanks, I'll check it out

**Comment by danieldreier** [comment]
@gtmtech did you still want to address this in the google provider? I'm happy to migrate it over there if you want.

**Comment by apparentlymart** [comment]
Looking at the reproduction case here, I think Terraform worked as designed in this case, but that Terraform's design didn't match your expectations.

An important thing to know about Terraform dependencies is that they relate to _ordering only_. The presence of a dependency will never cause a new action to be included in the plan that wouldn't already have been there; instead, Terraform uses the dependencies to decide which order to apply the changes that were already planned.

Due to the design of some providers the current design often ends up working the way you intended for a different reason: because recreating one object changes its configuration in some way that affects a reference in a downstream object, causing the provider to produce either an update or replace plan for that downstream object in order to apply the configuration change.

Unfortunately, that behavior didn't occur here because replacing the region of the bucket didn't cause any change to any of the attributes of that object that are included in the logging sink configuration: the logging sink includes the bucket name, but due to the design of Google Cloud Storage it's possible to move a bucket between regions without its name changing, and so Terraform sees the configuration of the logging sink as entirely unchanged.

To get the behavior you wanted here would require finding some way to ensure that the log storage configuration changes when the bucket is replaced. I'm not familiar enough with the GCS and log storage resources to make a confident suggestion about that, but I believe [the recommended pattern for the GCP provider](https://www.terraform.io/docs/providers/google/guides/getting_started.html#linking-gcp-resources) is to use the `self_link` argument to create references between objects, which works better because the provider is designed to ensure that `self_link` shows as changed whenever an object is replaced. With that said, I'm not sure if that would work in this specific case because I'm not sure if a `google_storage_bucket` `self_link` uses the same syntax that's expected for `google_logging_organization_sink`'s destination. I do see that the documentation for [`google_logging_organization_sink`](https://www.terraform.io/docs/providers/google/r/logging_organization_sink.html) shows the same usage pattern as in your example, so perhaps `self_link` isn't applicable in this case, or perhaps the documentation is incorrect.

---

Terraform could in theory have concepts in its design to allow it to detect the situation you described here automatically, such as what I discussed over in #22094. I'm not sure that the log-sink-to-bucket connection really fits exactly into one of the specific relationships I discussed there; it's perhaps not really accurate to say that the log sink is "contained inside" the bucket, though perhaps the effect is the same, and in particular I think this paragraph from my writeup applies here:

> The containment relationship also allows for improving Terraform's behavior in the more complex case of `DeleteThenCreate` or `CreateThenDelete` actions: this additional information might allow Terraform to understand both that it needs to replace all of the subnets when a containing VPC is replaced and that these objects are related in a way that requires a specific ordering
of the destroy and create actions to produce a correct result.

The initial ideas in that other issue are nowhere near baked enough to move forward to implementation and we don't have any specific plans to work on that in the near future, but I'm mentioning it here mainly to create the reverse issue link from #22094 so that if we _do_ look at that problem space again in future we'll be able to find this issue as an example use-case to test potential designs against.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
