### ISSUE TITLE
azurerm_virtual_network.main is object with no attributes

### ISSUE THREAD

**Issue by DaniBet** [hashicorp/terraform#25001]
I have a Terraform script:

```
variable "locations" {
  type = "map"
  default = {
    vm1 = "North Europe"
    vm2 = "West Europe"
  }
}
...
resource "azurerm_virtual_network" "main" {
  for_each            = var.locations
  name                = "${each.key}-network"
  address_space       = ["10.0.0.0/16"]
  location            = "${each.value}"
  resource_group_name = "${var.azurerm_resource_group_name}"
}

resource "azurerm_subnet" "internal" {
  for_each             = var.locations
  name                 = "${each.key}-subnet"
  resource_group_name  = "${var.azurerm_resource_group_name}"
  virtual_network_name = azurerm_virtual_network.main[each.key].name
  address_prefix       = "10.0.2.0/24"
}
...
```

Error:
```
Error: Invalid index

  on environment.tf line 33, in resource "azurerm_subnet" "internal":
  33:   virtual_network_name = azurerm_virtual_network.main[each.key].name
    |----------------
    | azurerm_virtual_network.main is object with no attributes
    | each.key is "vm2"

The given key does not identify an element in this collection value.
```
I know that I can modify (hard-code) with "${each.key}-network" the line 33, but why it doesn't work? If I hard code it, it also throws an error at the next uses of the same type of declaration. It is interesting, that sometimes it plans without errors.

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
