### ISSUE TITLE
Unable to find files created by a local-exec script

### ISSUE THREAD

**Issue by gadelkareem** [hashicorp/terraform#25002]
### Terraform Version

```
Terraform v0.12.20
+ provider.archive v1.3.0
+ provider.aws v2.61.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
resource "null_resource" "build" {
  triggers = {
    always_run = timestamp()
  }
  provisioner "local-exec" {
    command = "${path.module}/scripts/build.sh ${local.source_dir} ${var.zip_dir}/${local.name}"
  }
}

data "archive_file" "zip" {
  type        = "zip"
  output_path = var.zip_filename
  source_dir  = var.zip_dir
  depends_on  = [null_resource.build]
}

resource "aws_lambda_function" "lambda" {
  filename         = data.archive_file.zip.output_path
  source_code_hash = data.archive_file.zip.output_base64sha256
  function_name    = var.name
  role             = aws_iam_role.lambda_role[0].arn
  handler          = var.handler
  runtime          = "go1.x"
  timeout          = "120"
  description      = var.description
  vpc_config {
    subnet_ids         = local.subnet_ids
    security_group_ids = [aws_security_group.allow_all.id]
  }
  environment {
    variables = local.env
  }
  depends_on = [data.archive_file.zip]
}
```

### Crash Output
```hcl
Error: Error modifying Lambda Function Code some_func: InvalidParameterValueException: Uploaded file must be a non-empty zip
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "9243c685-cc9b-484c-ab8d-8ea7e7d34243"
  },
  Message_: "Uploaded file must be a non-empty zip",
  Type: "User"
}
```

The build scripts looks like this:
```bash
#!/usr/bin/env bash
set -eo pipefail
SRC=$1
DEST=$2

rm -f "$DEST"
cd "$SRC"
go get ./...
go mod vendor
GOOS=linux go build -o "$DEST" .

```

I am not sure if Terraform does not wait for the local-exec to finish or it cannot recognise that a file was created on the disk so it ends up zipping an empty dir.

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
