### ISSUE TITLE
Add JSON Output Format to terraform plan

### ISSUE THREAD

**Issue by codygman** [hashicorp/terraform#25011]
Copy of #11883, creating because old issues are closed after 30 days of inactivity and this would have helped my team save quite a lot of time. I'm also unclear after reading the the #11883 thread why this still isn't implemented.

**Comment by danieldreier** [comment]
Have you seen https://www.terraform.io/docs/internals/json-format.html?

**Comment by apparentlymart** [comment]
Hi @codygman,

We didn't hear back from you after @danieldreier's response, so I'm going to close this under the assumption that the `terraform show -json` command is sufficient to meet your needs here. If not, please open a new issue and complete the full Feature Request template so that we can understand how your use-case differs from the ones that the existing command was designed to address. Thanks!
