### ISSUE TITLE
Data Section from aws_sqs_queue before create queue error....

### ISSUE THREAD

**Issue by mizaelmontenegro** [hashicorp/terraform#25026]
### Terraform Version
```
Terraform v0.12.25
+ provider.aws v2.63.0
```

### Terraform Configuration Files
```hcl
resource "aws_sqs_queue" "queuetest2" {
  name="fila_test2"  
}

data "aws_sqs_queue" "queuetest-data2" {
  name="fila_test2"  
}
```

### Crash Output
Error: Error getting queue URL: AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
        status code: 400, request id: d02ba379-f13a-52c2-88ec-f43d3519ae81

  on testapi.tf line 48, in data "aws_sqs_queue" "queuetest-data2":
  48: data "aws_sqs_queue" "queuetest-data2" {

When I try to create an AWS SQS along with a "data" section of the same SQS, this error happens. However, if I comment on the data section, execute the command "terraform apply", apply and then uncomment the data section and execute apply again, it works. But if I execute the apply with the data section before the SQS is created, it returns this error. Am I doing something wrong? This is looking like a BUG to me.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
