### ISSUE TITLE
data query should support returning zero results without erroring

### ISSUE THREAD

**Issue by gh02067** [hashicorp/terraform#25033]
### Current Terraform Version

terraform version v0.12.20 
```
...
```

### Use-cases

feature to use data query returning zero results without erroring. This was requested in issue #16380 a while back and since its closed. not sure if this was ever addressed.
https://github.com/hashicorp/terraform/issues/16380

my use-case is to conditionally create additional resources based on data query response.

### Attempted Solutions

I have figured out a workaround and want to share it with the community so that they can comment on it and/or use it for their own requirements.
The workaround is to execute the data with count.
data "aws_security_group" "service1-sg" {
  count = (var.create_service1 ? 1:0)
  tags = {
        Name = "${local.name-pfx}-service1-alb-sg"
  }
}

in my usecase, I am discovering if the service is required outside of TF and passing the var.create_service as a variable. 

### Proposal

ideally, data query must support return of zero values. for backward compatibility, you can add an attribute to the data query like 
zero_value_accepted = true (default is false for backward compatibility)

**Comment by apparentlymart** [comment]
Hi @gh02067,

The Terraform team [posted a comment](https://github.com/hashicorp/terraform/issues/16380#issuecomment-517282340) at the time that issue was closed noting that this is not a behavior we intend to change, and explaining why.

The [Conditional Creation of Objects](https://www.terraform.io/docs/modules/composition.html#conditional-creation-of-objects) subsection of the Module Composition guide in the documentation describes the recommended way to explicitly declare variations between instances of a module. In that model, the decision of whether or not to create an object is made by the author of the configuration directly, so that Terraform can halt with an error if that intent isn't met in practice.

I'm going to close this because the situation hasn't significantly changed since the team closed #16380. If you have any questions about the patterns recommended in the documentation I linked above, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where we can discuss the details of your use-cases in particular. Thanks!
