### ISSUE TITLE
Impossible to output two escaped dollar signs

### ISSUE THREAD

**Issue by analytically** [hashicorp/terraform#25045]
If `$${val}` outputs `${val}` then `$$$${val}` should output `$${val}` but it outputs `$$${val}`

**Comment by danieldreier** [comment]
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). 

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, and then the Terraform maintainers will review it. Thanks!
