### ISSUE TITLE
Please update the vault dependency

### ISSUE THREAD

**Issue by rski** [hashicorp/terraform#25053]
as per the vault maintainers in: https://github.com/hashicorp/vault/issues/7848

Pulling vault before the multiple-modules version causes multiple issues with go getting and importing vault 1.4.x+

**Comment by danieldreier** [comment]
@rski the fact that terraform can be imported and used as a library is essentially an accident. Martin wrote in a [discussion forum post](https://discuss.hashicorp.com/t/terraform-automation-is-there-any-way-to-interact-with-terraform-cli-using-api-golang/4935) that "there is no supported in-process Go library API for Terraform", and that's the current official stance. We maintain stable interfaces via the API, and via HCL, but internally, Terraform is subject to significant changes like you've seen, and we don't (currently) consider those bugs.

I'm empathetic to your situation here - this individually isn't a huge request, so I want to share context about why we won't be doing this. The issue we face is that the aggregate of all the requests needed to support using Terraform as a library is pretty significant, and the work we'd have to do to make that a good experience would at the cost of a significant number of bug fixes and enhancement requests that have a lot more impact helping a wider set of users.

We also have a lot of upcoming internal refactoring coming up, and the interfaces we intend to hold stable are the CLI, HCL, and to a lesser degree the plan file. The internals of terraform may shift significantly, even between z releases, and so I encourage you to interface with terraform via the binary rather than importing it as a go library.

If this is really important to you and using terraform as a binary is not feasible for your workflow, you're welcome to file an enhancement request for a supported way to import terraform, perhaps with something similar to the vault api package. If there is a broader base of community demand for that than we're currently aware of, we may re-evaluate our stance. Until then, we're not planning work in support of using terraform a library, so I'm going to close this request.

**Comment by rski** [comment]
Thanks for this insightful reply. I'm not actually the guy using terraform, I just tend to help with the ci/dependency side of things. I wasn't aware of any of this, I barely know what terraform is used for never mind what we do with it at arista. Certainly if using the cli is preferred, that is great, and I would actually prefer that too, since it makes my ci/dependency work easier. So thanks.

**Comment by rski** [comment]
actually, one thing that I would ask in this case is would it be possible to mention in the README that this repo should not be depended on?

**Comment by danieldreier** [comment]
@rski yes, that's a great idea - I've been working out text for that and haven't quite gotten it finalized and approved yet. I wanted to give you a quick, ad-hoc response before that was done so you wouldn't stay blocked, and you're right that a more official written statement would be useful.

**Comment by rski** [comment]
much appreciated :)
