### ISSUE TITLE
Is it possible in azurerm_storage_data_lake_gen2_filesystem to pass a list of filesystem names?

### ISSUE THREAD

**Issue by klainn** [hashicorp/terraform#25060]
I have the following basic code:

`variable "storage_area_names" {
  type    = list
  default = ["archive", "transient", "raw", "trusted", "refined"]
}`

`resource "azurerm_storage_data_lake_gen2_filesystem" "archive" {
  name = var.storage_area_names
  storage_account_id = azurerm_storage_account.main.id
}`

This doesn't work, I get an error: 
`Error: Incorrect attribute value type`

`  on create_environment.tf line 47, in resource "azurerm_storage_data_lake_gen2_filesystem" "archive":
  47:   name = var.storage_area_names`

`Inappropriate value for attribute "name": string required.`

Is is possible to do this or not with the current version? Is there a better way to create multiple storage areas other than repeating the same code over and over?

**Comment by pkolyvas** [comment]
Hey there,

Thanks for taking the time to write us. 

My intuition would be to use a variable of type `map` and subsequently use `for_each` to create multiple storage areas with one resource block. 

https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings

You could also use `toset` from the `for_each` documentation to convert your list of strings to a set: https://www.terraform.io/docs/configuration/resources.html#using-sets

Because this is a usage question, and due to the number of issues we work through here, we're encouraging our community members to use our [community forums](https://discuss.hashicorp.com/c/terraform-core/27) to ask questions. I'd recommend taking this request there where more help would be readily available for you.
