### ISSUE TITLE
Please adhere to a single commenting standard

### ISSUE THREAD

**Issue by edward2a** [hashicorp/terraform#25095]
Hi! Per your documentation:
```
Comments
The Terraform language supports three different syntaxes for comments:

# begins a single-line comment, ending at the end of the line.
// also begins a single-line comment, as an alternative to #.
/* and */ are start and end delimiters for a comment that might span over multiple lines.
The # single-line comment style is the default comment style and should be used in most cases. Automatic configuration formatting tools may automatically transform // comments into # comments, since the double-slash style is not idiomatic.
```

I believe you should consider adhering to a single commenting standard and either enhance the '#' with something like '#*, *#' or simply drop the '#' in favour of the C++ comment style `// | /*, */`.

I don't believe it to be a good practice nor a good idea to support both commenting styles, while recommending the use of '#' and having block comments only enabled by '/*, */'.

**Comment by jackbritchford** [comment]
I agree that the standardisation needs to be improved.
Personally in my Terraform coding style, I use
`#` for actual comments
`// | /* */` for single/multiline testing/old code/lets keep this here incase we need it later.

I do agree with @edward2a that, `#* *#` comments should be added for actual multiline comments, not temporarily removing things

**Comment by jackbritchford** [comment]
I think `#* *#` should be added and the Comments documentation updated so that "Comments" are `# | #* *#` and another term is used for `// | /* */` comments, which would more be for removing chunks of code in testing/etc

**Comment by apparentlymart** [comment]
Hi @edward2a,

We are already explicit in the documentation that `#` is the recommended quoting style, which is the "single commenting style" that all idiomatic Terraform code should be using:

> The `#` single-line comment style is the default comment style and should be used in most cases. Automatic configuration formatting tools may automatically transform `//` comments into `#` comments, since the double-slash style is not idiomatic.

We don't have any immediate plans to remove any of the other quoting styles or add any new ones. 

It is possible that future versions of Terraform may extend `terraform fmt` to automatically rewrite other comment styles to `#` where possible, as the documentation hints, but I find it very unlikely that we would totally remove the other styles because the cost of continuing to support them seems very low (I rarely see anyone using anything other than the idiomatic style) and the underlying parser is shared with other software which can have different idiom, and so coordinating such a breaking change would be incredibly expensive.

Adding a fourth way to write comments, in addition to the existing three, does not seem like it would add any significant expressive power to the language, and would instead just exacerbate the very problem you presented here of not having a "single commenting style".

**Comment by apparentlymart** [comment]
Hi all,

I'm revisiting this some time later and realizing that I don't think there's any more we can practically do here: Terraform is now subject to [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises) and it would not be in the spirit of those promises to remove the non-idiomatic comment syntaxes.

As I noted before, I don't typically see the non-standard commenting syntax in real-world modules written today, and so I don't think the impact of making `terraform fmt` try to rewrite comments into a different style would be worth the complexity it would imply, and I expect it would annoy people trying to use `/* ... */` to temporarily disable some code, rather than for actual comments.

Because of that, I'm going to close this issue. Thanks for opening it, and sorry we let it sit here for so long.
