### ISSUE TITLE
Terraform doesn't read the exsisting state from s3

### ISSUE THREAD

**Issue by laur1s** [hashicorp/terraform#25094]
### Terraform Version
Terraform v0.12.26 and Terraform v0.12.24
+ provider.aws v2.64.0

### Actual Behavior
Hello,

I've encountered the same bug in Terraform v0.12.24 and v0.12.26. I can see the resource in s3 state file:
```
{
  "version": 4,
  "terraform_version": "0.12.24",
  "serial": 1,
  "lineage": "xxxxx",
  "outputs": {},
  "resources": [
    {
      "module": "module.s3",
      "mode": "managed",
      "type": "aws_kms_alias",
      "name": "s3",
      "provider": "provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:kms:eu-central-1:xxxxx",
            "id": "alias/dev/s3",
            "name": "alias/dev/s3",
            "name_prefix": null,
            "target_key_arn": "arn:aws:kms:eu-central-1:xxxxx",
            "target_key_id": "xxxxx"
          },
          "private": "xxxxxx",
          "dependencies": [
            "module.s3.aws_kms_key.s3"
          ]
        }
      ]
    },
```

However, terraform wants to create the whole module:

```
n execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.s3.aws_s3_bucket.xxx will be created
  + resource "aws_s3_bucket" "xxx" {
```
I'm not sure if this is a bug with terraform or s3 provider. I can confirm thtat the state file exsists in s3. I also use the same module for different environment and in that case terraform is able to read state file from s3.

**Comment by danieldreier** [comment]
Hi! Thanks for reporting this. In order to determine what's going on here, I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I don't have your terraform config and I'm not sure what order you're doing things in, and so I'm stuck.  

Can you please restate your reproduction case such that I can copy-paste it and run it locally?

**Comment by eug-maly** [comment]
Hello @danieldreier
I have the similar situation, but not the same.
We have a layer where we created kubernetes resources and some aws and null resources.
It worked using v0.12.23, and last successful apply was done using v0.12.24.
Now, if I run plan\apply step - it's going to create all kubernetes resources:
---
```data.template_file.kubeconfig: Refreshing state...
data.template_file.init: Refreshing state...
random_string.cb_admin_password: Refreshing state... [id=Ao?MeQOyB46E:bVF]
local_file.kubeconfig: Refreshing state... [id=5c8b24137b3e16450a6da172f3f6594416ca45c1]
null_resource.couchbase-admission: Refreshing state... [id=1169351664992347981]
kubernetes_cluster_role_binding.couchbase_srv_viewer: Refreshing state... [id=couchbase-srv-viewer]
kubernetes_service_account.metricbeat: Refreshing state... [id=kube-system/metricbeat]
kubernetes_service.couchbase_exporter: Refreshing state... [id=default/couchbase-exporter]
kubernetes_service_account.couchbase_srv: Refreshing state... [id=default/couchbase-srv]
kubernetes_storage_class.gp2_multi_zone: Refreshing state... [id=gp2-multi-zone]
kubernetes_config_map.metricbeat_daemonset_modules: Refreshing state... [id=kube-system/metricbeat-daemonset-modules]
kubernetes_service.sync_gateway_exporter: Refreshing state... [id=default/sync-gateway-exporter]
kubernetes_role.couchbase_operator: Refreshing state... [id=default/couchbase-operator]
kubernetes_cluster_role.metricbeat: Refreshing state... [id=metricbeat]
kubernetes_config_map.metricbeat_daemonset_config: Refreshing state... [id=kube-system/metricbeat-daemonset-config]
kubernetes_config_map.sg: Refreshing state... [id=default/sg]
kubernetes_service_account.couchbase_operator: Refreshing state... [id=default/couchbase-operator]
kubernetes_cluster_role_binding.metricbeat: Refreshing state... [id=metricbeat]
kubernetes_service.sync-gateway: Refreshing state... [id=default/sync-gateway]
kubernetes_cluster_role.couchbase_srv: Refreshing state... [id=couchbase-srv]
kubernetes_deployment.couchbase_operator: Refreshing state... [id=default/couchbase-operator]
data.aws_ssm_parameter.elasticsearch_password: Refreshing state...
aws_ssm_parameter.cb_admin_password: Refreshing state... [id=/config/apacprod/couchbase/administrator/password]
kubernetes_secret.cb-admin: Refreshing state... [id=default/cb-admin-secret]
null_resource.couchbase-crd: Refreshing state... [id=8754483791713243858]
null_resource.couchbase-cluster: Refreshing state... [id=2001405872297306026]
kubernetes_role_binding.couchbase_operator: Refreshing state... [id=default/couchbase-operator]
kubernetes_deployment.couchbase_exporter: Refreshing state... [id=default/couchbase-exporter]
kubernetes_daemonset.metricbeat: Refreshing state... [id=kube-system/metricbeat]
kubernetes_deployment.sync-gateway: Refreshing state... [id=default/sync-gateway]
data.aws_route53_zone.private: Refreshing state...
data.aws_acm_certificate.apis_certificate: Refreshing state...
data.aws_acm_certificate.certificate: Refreshing state...
data.aws_vpc.core: Refreshing state...
data.aws_iam_policy_document.srv_rights: Refreshing state...
aws_iam_role_policy.srv_rights: Refreshing state... [id=apacprod-couchbase20191015105625220300000006:couchbase-srv]
kubernetes_deployment.couchbase-srv: Refreshing state... [id=default/couchbase-srv]
kubernetes_service.sync-gateway-private: Refreshing state... [id=default/sync-gateway-private]
data.aws_subnet.pub_zone1a: Refreshing state...
data.aws_subnet.pub_zone1b: Refreshing state...
kubernetes_ingress.sg_ingress: Refreshing state... [id=default/sync-gateway]---
Plan: 25 to add, 0 to change, 0 to destroy.```

terragrunt state list | grep kuber | wc -l
```Running command: terraform state list
24
```
I suppose that the 25s  file is local_file.kubeconfig.

**Comment by apparentlymart** [comment]
Hi @laur1s and @eug-maly,

I'd be interested to see if the behavior changes when you use the `-refresh=false` option to either `terraform plan` or `terraform apply`. My theory is that during the refresh phase the provider is telling Terraform that the object no longer exists, and so then Terraform plans to create a new one to replace it. Terraform creates a new state snapshot only after you apply the plan, so the effect of that refresh would not be visible in the saved state snapshot or in the `terraform state list` result.

For the AWS provider in particular, a relatively common mistake leading to this situation is using an incorrect set of credentials that selects a different AWS account, which can then make it appear that objects don't exist because you don't have access to them. Another variant of this problem is accidentally selecting the wrong region, in which case region-specific objects appear to the AWS provider as non-existent because it is asking the wrong set of regional endpoints.

Running with `-refresh=false` is not something I'd recommend to do routinely -- it's mainly there to help with debugging situations like this -- but if you do see Terraform behave as you expected when you use that option then that's a good hint to make sure the provider configuration is correct and that the object in question does still exist in the remote system.

**Comment by eug-maly** [comment]
Hi @apparentlymart 
If I run just plan:
Plan: 26 to add, 0 to change, 1 to destroy.

If I run  plan -refresh=false
Plan: 0 to add, 3 to change, 0 to destroy.

The last one is the expected result.

**Comment by apparentlymart** [comment]
Hi @eug-maly,

Thanks! That seems to have confirmed my theory, which unfortunately means the next step is on your side: it seems that something has changed in your provider configuration that means that the objects Terraform is managing are no longer readable. As I mentioned in my previous comment, the most common situations I've seen in the past are:

* You're using credentials associated with the wrong account, or with the wrong permissions, and so the remote server is returning "not found" to avoid disclosing the existence of something you don't have rights to see.
* You're using the wrong API endpoint for your Kubernetes server or the wrong region for your AWS objects, and so when the provider tries to read those objects it gets back a "not found" response.

Running Terraform with the environment variable `TF_LOG=trace` and looking in the verbose log output for `terraform-provider-kubernetes` and `terraform-provider-aws` references might give some clues by showing you which requests the providers are making and what responses they are getting.

Unfortunately all of these behaviors are in the provider codebases rather than in Terraform Core, so I can't really give any more specific pointers than that. If you get stuck while debugging I'd recommend opening a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there's a broader audience who might have more familiarity with the Kubernetes and AWS providers in particular and be able to give more direct help.

**Comment by apparentlymart** [comment]
@laur1s, it'd be good if you could give what I suggested above a try too, and let me know how it turns out. Your symptoms seem the same so far so if you also see it work with `-refresh=false` then what I wrote in the previous comment will apply to your situation too.

**Comment by laur1s** [comment]
@apparentlymart Sorry for not responding for a long time. I tried running with `-refresh=false` but that didn't help. Now I can't reproduce the error anymore. But simply running `terraform import` for the s3 bucket solved my problems

**Comment by danieldreier** [comment]
Thanks @laur1s - I appreciate the update. I'm going to resolve this because it's not clear that there's a bug in core. 

@eug-maly if you want to talk your issue through more, [the community forum](https://discuss.hashicorp.com/c/terraform-core) may be a better place than here because you're most likely facing a configuration issue rather than bug in Terraform itself.
