### ISSUE TITLE
Terraform crashed

### ISSUE THREAD

**Issue by mkola0206** [hashicorp/terraform#25102]
When I do terraform plan I got the below response 

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

terraform --version
Terraform v0.11.15-oci
 provider.aws v2.64.0
 provider.template v2.1.2

**Comment by nfplatzke** [comment]
same error here

Terraform v0.11.14
+ provider.aws v2.64.0
+ provider.template v2.1.2

**Comment by danieldreier** [comment]
We are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. In fact, our 0.13 beta 1 is being released on Wednesday this week, so getting onto 0.12 will help you adopt that when it comes out.

Can you please try reproducing this issue on 0.12?

**Comment by mkola0206** [comment]
@nfplatzke downgrade the aws provider version to "2.59" which is working for me
