### ISSUE TITLE
Native support for DigitalOcean Spaces as a Backend

### ISSUE THREAD

**Issue by jaredready** [hashicorp/terraform#25108]
### Current Terraform Version

```
0.12.26
```

### Use-cases

The current `s3` backend technically works due to [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/) having a S3-compatible API, but it's currently not very obvious how to use it outside of AWS S3. The API for the `s3` backend is also built for AWS S3 specifically, which leads to some awkwardness when using it for other S3-compatible services.

I'd like to see a more native provider that provides an API specific to DigitalOcean Spaces that's much more obvious to use.

### Proposal

Since the `s3` backend technically works, I think piggy backing on most of it would be easiest, just providing a different API that's more specific Spaces.

I'm thinking the API will look something like the following:
```tf
terraform {
  backend "spaces" {
    space = "myspace"
    key    = "path/to/my/key"
    region = "nyc1"
    access_key = "acc_key"
    secret_key = "sec_key"
  }
}
```

Instead of the current API to make `s3` work with Spaces:

```tf
terraform {
  required_version = ">= 0.11, < 0.12"
  backend "s3" {
    skip_requesting_account_id = true
    skip_credentials_validation = true
    skip_get_ec2_platforms = true
    skip_metadata_api_check = true
    access_key = "XXXXXXXXX"
    secret_key = "XXXXXXXXXXXXXXXXXXXXXXXXX"
    endpoint = "https://xxx.digitaloceanspaces.com"
    region = "us-east-1"
    bucket = "XXXXXXX" // name of your space
    key = "production/terraform.tfstate"
  }
}
```
### References

#15553

**Comment by jaredready** [comment]
If you guys agree that this would be useful, I'd like to tackle getting this implemented.

**Comment by danieldreier** [comment]
@jaredready we are currently [not adding new state backends](https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#state-storage-backends). I wrote some pretty detailed explanations of why on several recent PRs that we closed https://github.com/hashicorp/terraform/pull/24647 https://github.com/hashicorp/terraform/pull/23481 https://github.com/hashicorp/terraform/pull/22799 if you want to learn more about why. I'm going to close this, because we will not be accepting new state backends until we have a plugin system, and at that point you will no longer need to file an issue with us to create a new backend.

**Comment by jaredready** [comment]
Thanks for the heads up! That makes a lot of sense to me. Is there an issue that I can follow for updates on the plugin system?
