### ISSUE TITLE
The argument "env" is required, but no definition was found

### ISSUE THREAD

**Issue by akoliya01** [hashicorp/terraform#25115]
I have the following directory/files structure:

.
├── main.tf
├── modules
│   └── Resource_group
│       ├── main.tf
│       └── vars.tf

Configuration files

./main.tf

module "app-rg" {
  source = "./modules/Resource_Group"
}

./modules/resource_group/main.tf

provider "azurerm" {
 version = "=2.11.0"
 features { }  
}
resource "azurerm_resource_group" "rg" {
     name     = "${lookup(var.resource_group, var.env)}"
    location = "${lookup(var.location, var.env)}"
}

./modules/resource_group/vars.tf

variable "env" {
  description = "env : dev or prod"
}
variable "resource_group" {
  type = "map"
    default = {
      dev = "rg-dev"
      prod = "rg-prod"
    }  
}
variable "location" {
  type = "map"
    default = { 
      dev  = "westindia"
      prod = "westeurope"
    }  
}

When I run a "terraform plan" I will get a below error.

Error: Missing required argument

  on main.tf line 6, in module "app-rg":
   6: module "app-rg" {

The argument "env" is required, but no definition was found.

**Comment by apparentlymart** [comment]
Hi @akoliya01!

I see that you asked the same question [on Stack Overflow](https://stackoverflow.com/questions/62171080/why-do-i-get-the-argument-env-is-required-but-no-definition-was-found) and there's an answer to it there which seems correct to me.

We use GitHub issues for tracking bugs and enhancements rather than for questions, so I'm going to close this in favor of your Stack Overflow question. Thanks!
