### ISSUE TITLE
Terraform Apply deleting existing resources and creating new ones

### ISSUE THREAD

**Issue by Ankitkoul7** [hashicorp/terraform#25126]
### Terraform Version

Terraform version 0.11
```
...
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

Terraform Plan and Apply with existing state file is forcing new resources. Ideally if the resources are existing in state file, it should not touch them. In my case, older resources are deleted and new and created . I am keeping my .tfvas file same yet instances are forced created

### Expected Behavior

No resources should be deleted or created if state file is not changed 
### Actual Behavior

Existing resources deleted and new resources force created.

### Steps to Reproduce

Running Plan and Apply jobs

### Additional Context

Version 0.11

**Comment by apparentlymart** [comment]
Hi @Ankitkoul7,

Unfortunately since you didn't include any configuration examples in your question we can't really provide any useful response to this. Additionally, Terraform 0.11 is no longer under active development, so whatever bugs it has at this point are unfortunately the bugs it will always have. :confounded: 

With that said, if you'd like I'd encourage you to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) to see if someone can explain what you are seeing and offer some help. I'd recommend including some configuration examples and an example of the `terraform plan` output you are seeing in your question, because otherwise (must as with this issue) it will be difficult for anyone to give a specific answer.

Because Terraform 0.11 is no longer under active development, I'm going to to close this now.
