### ISSUE TITLE
Unexpected conditional resolve order in 0.13.0-beta1

### ISSUE THREAD

**Issue by pielu** [hashicorp/terraform#25122]
Hi, thanks and congrats for getting first 0.13 beta out of the door!

### Terraform Version
```
Terraform v0.13.0-beta1
+ provider registry.terraform.io/hashicorp/aws v2.43.0
```

### Terraform Configuration Files
```hcl
locals {
  secondary_subnet = flatten([
    for secondary_cidr_block in var.vpc.secondary_cidr_block : [
      for i, subnet in secondary_cidr_block.subnet : merge({
        availability_zone    = element(data.aws_availability_zones.aws_helper.names, i),
        public               = false
        tags                 = {}
        cidr_block           = element(local.secondary_cidr_block[secondary_cidr_block.cidr_block], i)
        secondary_cidr_block = secondary_cidr_block.cidr_block
      }, subnet)
      if contains(keys(secondary_cidr_block), "subnet")
    ]
    if contains(keys(var.vpc), "secondary_cidr_block")
  ])
}
```

### Actual Behavior
Getting the following error
```bash
Error: Unsupported attribute

  on (..)/subnet.tf line 22, in locals:
  22:     for secondary_cidr_block in var.vpc.secondary_cidr_block : [
    |----------------
    | var.vpc is object with 2 attributes

This object does not have an attribute named "secondary_cidr_block".
```

### Additional Context
It appears as if the conditional was not resolved in order.

**Comment by apparentlymart** [comment]
Hi @pielu! Thanks for opening this issue.

Terraform seems to be behaving as intended here, as far as I can tell. The `if` clause of a `for` expression is for deciding whether _each individual element_ should be included in the resulting list, so it is evaluated once for each element of `var.vpc.secondary_cidr_block`. Terraform has to evaluate `var.vpc.secondary_cidr_block` first in order to see what elements it has in the first place.

I think a concise way to write what you intended to express here would be to use `try` to fall back on an empty collection if `secondary_cidr_block` isn't present. For example:

```hcl
locals {
  # This expression "normalizes" var.vpc by substituting default
  # values for anything that isn't set in the caller's value.
  vpc = {
    # (...whatever other attributes var.vpc has...)
    secondary_cidr_block = tolist(try(var.secondary_cidr_block, []))
  }
}
```

In the above I'm assuming that `var.secondary_cidr_block` is intended to be a list. If you instead intended it to be a map, use `tomap` and `{}` instead of `tolist` and `[]`.

You can then use `local.vpc` instead of `var.vpc` everywhere else in the module and avoid introducing guard conditionals to deal with situations where the object is not of the expected shape.

The behavior you are describing here hasn't changed since Terraform v0.12, so I think this isn't actually a v0.13 bug. Had you seen this pattern work on Terraform v0.12 before trying it in v0.13?

**Comment by pielu** [comment]
I stand corrected. I have found the issue which was a small sneaky change which made it seem like nothing changed between my 0.12 and 0.13 version of the module. Plus your simplification of the code made it even cleaner. Thank you!
