### ISSUE TITLE
VCS filter is applied when when no VCS is associated

### ISSUE THREAD

**Issue by nicois** [hashicorp/terraform#25125]
### Terraform Version
0.12.26

### Expected Behavior
API push inserts a queue entry

### Actual Behavior
nothing.

### Steps to Reproduce
Associate a TF cloud workspace with a VCS
specify "Only trigger runs when files in specified paths change"
Save
Dissociate a VCS from the workspace
Use the API to submit a job to the queue.

**Comment by apparentlymart** [comment]
Hi @! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
