### ISSUE TITLE
Example in getting started guide fails because t2.micro requires a VPC

### ISSUE THREAD

**Issue by mmiinnovations** [hashicorp/terraform#25130]
This issue was closed previously but every team member on my staff ran into this exact problem so it's not fixed.

Here's previous issue:
https://github.com/hashicorp/terraform/issues/4367

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by bflad** [comment]
Hi @mmiinnovations 👋  Thank you for reporting this. 

Looking at the current iteration of the page (https://learn.hashicorp.com/tutorials/terraform/aws-build), this issue still appears to be valid when you first read through the tutorial, however there is now a [troubleshooting section](https://learn.hashicorp.com/tutorials/terraform/aws-build#troubleshooting) which does provide some information about what to do in the scenario there is not a default VPC. Given this, I'm going to close this issue out. I believe it is now also possible to provide direct feedback on the tutorial pages so that the team that maintains them, which doesn't typically monitor the issues in this repository, can act on it.
