### ISSUE TITLE
terraform 0.13upgrade fails with a filesystem module with same provider as root 

### ISSUE THREAD

**Issue by andpatt** [hashicorp/terraform#25136]
### Terraform Version

```
Terraform v0.13.0-beta1
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

https://gist.github.com/andpatt/b2d1559fd8fe246523c6bb76ea3b4b74
### Expected Behavior

when using a configuration with a root module and filesystem module which both depend on a given provider, terraform 0.13upgrade should upgrades the root module provider source declaration and that of the filesystem module. Or it should assume that the filesystem module uses the same source as the root.
### Actual Behavior

when using a configuration with a root module and filesystem module which both depend on a given provider, terraform 0.13upgrade upgrades the root module provider source declaration, but not that of the filesystem module, causing the subsequent `terraform init` to fail with the same error.
### References

This is the repo that I ran the commands in, with the commands run from the repo root.
https://gitlab.com/the-junkyard/meta/-/tree/github-issue-tag

### Possible solution

If I cope paste the block that the `terraform 0.13upgrade` command creates in versions.tf i
```
terraform {
  required_providers {
    gitlab = {
      source = "terraform-providers/gitlab"
    }
  }
  required_version = ">= 0.13"
}
```

nto the filesystem module's main.tf (./modules/group-label-scope/main.tf) and rerun `terraform init` then it initialises successfully.

Thanks everyone involved in this, it otherwise works great!

**Comment by mildwonkey** [comment]
Hi @andpatt , thank you for opening this issue! 

`terraform 0.13upgrade` - and similar commands, such as `terraform fmt` and earlier upgrade commands - need to be explicitly run on each module. 

We do have this called out in the documentation, but of course that doesn't help beta users because it isn't live on the website yet 😅 

You can view the [0.13upgrade command](https://github.com/hashicorp/terraform/blob/master/website/docs/commands/0.13upgrade.html.markdown) document in this repository (there's a specific section on [batch usage](https://github.com/hashicorp/terraform/blob/master/website/docs/commands/0.13upgrade.html.markdown#batch-usage). I'll keep this issue open with a `documentation` label for now. 

Thanks again!

**Comment by mildwonkey** [comment]
The documentation is being upgraded as we speak, so I am going to close this.
