### ISSUE TITLE
remote-exec not wating for user_data to finish

### ISSUE THREAD

**Issue by jkoscialkowski** [hashicorp/terraform#25137]
### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.64.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
  profile = "default"
  region  = "eu-central-1"
}

resource "aws_instance" "ec2" {
  ami           = "ami-0e342d72b12109f91"
  instance_type = "t2.micro"
  
  associate_public_ip_address = true
  key_name = "MyKeyPair"
  
  user_data = <<EOF
#!/bin/bash
apt-get update
yes Y | sudo apt-get install python3 python3-pip python3-venv nginx
mkdir /opt/python
python3 -m venv /opt/python/venv
/opt/python/venv/bin/pip install --upgrade pip setuptools
EOF
  
  connection {
    type         = "ssh"
    user         = "ubuntu"
    private_key  = file("C:/Users/Jan Kościałkowski/.ssh/MyKeyPair.pem")
    host         = self.public_ip
    agent        = false
  }
  
  provisioner "remote-exec" {
    inline = [
	  "source /opt/python/venv/bin/activate",
	  "python -c \"print('something')\""
	]
  }
}
```

### Debug Output
```
aws_instance.ec2 (remote-exec): Connecting to remote host via SSH...
aws_instance.ec2 (remote-exec):   Host: 3.127.39.154
aws_instance.ec2 (remote-exec):   User: ubuntu
aws_instance.ec2 (remote-exec):   Password: false
aws_instance.ec2 (remote-exec):   Private key: true
aws_instance.ec2 (remote-exec):   Certificate: false
aws_instance.ec2 (remote-exec):   SSH Agent: false
aws_instance.ec2 (remote-exec):   Checking Host Key: false
aws_instance.ec2 (remote-exec): Connected!
aws_instance.ec2: Still creating... [40s elapsed]
aws_instance.ec2 (remote-exec): /tmp/terraform_62807413.sh: 2: /tmp/terraform_62807413.sh: source: not found
aws_instance.ec2 (remote-exec): /tmp/terraform_62807413.sh: 3: /tmp/terraform_62807413.sh: python: not found


Error: error executing "/tmp/terraform_62807413.sh": Process exited with status 127
```

### Expected Behavior
This is a minimal example replicating an issue I have with a larger system. I was trying to install some packages with `user_data` and later run some scripts using the `remote-exec` Provisioner. Correct me if I'm wrong, but my idea is that any provisioning would be allowed only after the `user_data` had finished. In this particular case, Python should print `something` to the console.

### Actual Behavior
I am getting the error message listed in *Debug Output*. Terraform tries to run the Python print in `remote-exec` before cloud init finishes, determined from `syslog` and `cloud-init.log`. After SSH-ing on the instance, I am able to run `/tmp/terraform_62807413.sh` manually and it works (after giving Python time to finish installation).

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
https://github.com/hashicorp/terraform/issues/20540

**Comment by danieldreier** [comment]
@apparentlymart I'm curious about expected behavior here - I think that the expected behavior is that the remote-exec will try to connect as soon as the AWS API says the machine is up, and keep trying until the ssh daemon is available. If that's correct, then what would be needed here is for the user-data script to ensure that sshd is stopped until setup is complete. Does that sound reasonable to you?

**Comment by apparentlymart** [comment]
Yes, that's correct. Terraform will begin trying to connect as soon as the EC2 API signals that the virtual machine is running, expecting that an SSH service will become available shortly afterwards during the system boot process.

`user_data` is, from Terraform's and EC2's perspective, just an arbitrary string for software inside the instance to process, so Terraform has no awareness of when, how, or even whether actions will be taken based on it. It's common -- but not _required_ -- for `user_data` to be interpreted by [cloud-init](https://cloudinit.readthedocs.io/en/latest/) on first boot, but when that happens in relation to when the SSH server begins accepting connections is a matter of how the operation system's boot process is set up.

If you need to guarantee that your provisioner steps won't occur until after `user_data` has been processed then I think you have two main options, assuming your AMI has `cloud-init` installed:

1. Probably the most straightforward option would be to configure the system software to launch `sshd` only after `cloud-init`.

    If you are using a Linux distribution that uses `systemd`, then [cloud-init's _Boot Stages_ documentation](https://cloudinit.readthedocs.io/en/latest/topics/boot.html) suggests that making the SSH server service depend on `cloud-final.service` would delay the SSH server starting up until the boot process is fully completed, which may be more conservative than necessary but should certainly be after `cloud-init` processes `user_data`.

2. If delaying the startup of the SSH server is not an option for some reason then you'll need to instead make your provisioner code itself check for some indication that cloud-init has processed `user_data`.

    For example, your provisioner script could poll the `/var/lib/cloud/instances` directory to await the `boot-finished` file being created, as shown in [cloud-init _Directory Layout_](https://cloudinit.readthedocs.io/en/latest/topics/dir_layout.html), or it could poll for the `/opt/python/venv/bin/activate` file to begin existing. This is a considerably more complex option than the first one because it requires writing custom code to detect when the boot process is completed, rather than merely configuring already-installed software to behave differently.

Either way, this is unfortunately a Linux system configuration problem rather than something Terraform can help with. Terraform is responsible only for making the virtual machine start running, and anything that happens after that is a matter for software installed in the selected AMI.

**Comment by jkoscialkowski** [comment]
@apparentlymart Thank you for your explanation. Both options you mention seem to be exactly what I was looking for. Closing.
