### ISSUE TITLE
templatefile doesn't wait for dependency described in resource block

### ISSUE THREAD

**Issue by d-helios** [hashicorp/terraform#25145]
### Terraform Version
```
Terraform v0.12.26
+ provider.local v1.4.0
```

### Terraform Configuration Files

main.tf
```hcl
variable "templates" {
  type = list(object({
    name = string
    value = string
  }))
}

resource "local_file" "origin" {
  count = length(var.templates)
  filename = "${path.module}/${var.templates[count.index].name}.json"
  content = var.templates[count.index].value
}

resource "local_file" "rendered" {
  count = length(var.templates)
  filename = "${path.module}/${var.templates[count.index].name}.rendered.json"
  content = templatefile(local_file.origin[count.index].filename, {tf_version = "v0.12.26"})
  depends_on = [
    local_file.origin
  ]
}
```

input.tfvars
```
templates = [
  {
    name = "my_template_1"
    value = "tf_version = $${tf_version}"
  },
  {
    name = "my_template_2"
    value = "tf_version = $${tf_version}"
  }
]
```

### Expected Behavior
1. resource **local_file.origin** create a couple of files that are used as input for resource local_file.rendered 

### Actual Behavior
1. terraform ignore depends_on block which leads to the following error.
```Call to function "templatefile" failed: no file exists at my_template_1.json```

### Steps to Reproduce
1. terraform init
2. terraform apply -auto-approve -var-file=input.tfvars

**Comment by danieldreier** [comment]
Hello! I appreciate you reporting this, and I'm sorry this behavior isn't more obvious.

I think that what you're running into here is that functions always run at the very beginning of a terraform run, before any resources are created at all. I totally understand what you're trying to do here, but it won't work like this because files referenced by Terraform functions must exist before the terraform run starts.

I'm going to close this because I created a [meta-issue](https://github.com/hashicorp/terraform/issues/25162) tracking this broader category of issue - I probably triage about an issue a day relate to this, and it's time to start gathering data for a refactor, better documentation, better error messages, something to make this behavior more obvious.

If you want more guidance on how to work around this, your best bet is to seek support on [the community forum](https://discuss.hashicorp.com/c/terraform-core).
