### ISSUE TITLE
Issue with upgrading provider (google-beta) with 0.13-beta

### ISSUE THREAD

**Issue by tvvignesh** [hashicorp/terraform#25153]
### Terraform Version

```
Terraform v0.13.0-beta1
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    google = {
      source = "hashicorp/google"
    }
    google-beta = {
      source = "terraform-providers/google-beta"
    }
  }
}

provider "google" {
  version = "~> 3.3"
}

provider "google-beta" {
  version = "~> 3.3"
}
# terraform {
#   required_providers {
#     google = {
#       source = "hashicorp/google"
#     }
#   }
#   required_version = ">= 0.13"
# }

```

### Debug Output
https://gist.github.com/tvvignesh/2f976fed73ce38a1fd377f1fc97daf4d

Hi. I tried to upgrade from Terraform 0.12 to 0.13-beta and faced issues with the google-beta provider. I tried upgrading by following the instructions as given but still ended up with errors. Screenshot below.

![Screenshot from 2020-06-06 00-03-10](https://user-images.githubusercontent.com/1165845/83911540-105bd280-a78a-11ea-9378-25715315baf8.png)

![Screenshot from 2020-06-06 00-05-58](https://user-images.githubusercontent.com/1165845/83911563-1ce02b00-a78a-11ea-9b0f-dd25c107fa7e.png)

Tried upgrading after this and got the same error. Any help appreciated.

Thanks in advance.

**Comment by danieldreier** [comment]
@tvvignesh I'm so happy you're trying out 0.13! 🎉 

I tried to reproduce this, and wasn't able to. I scripted what I think is the reproduction case you're describing at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/25153 to try and have a better place to collaborate on the exact reproduction details. One detail - you will need `terraform-v0.12.26` and 

When I run `run.sh` in that repository, here's what I see:
```
bash-3.2$ ./run.sh
+ command -v terraform-v0.12.26
/usr/local/bin/terraform-v0.12.26
+ command -v terraform-v0.13.0-beta1
/usr/local/bin/terraform-v0.13.0-beta1
+ rm -rf .terraform
+ terraform-v0.12.26 init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "google" (hashicorp/google) 3.24.0...
- Downloading plugin for provider "google-beta" (terraform-providers/google-beta) 3.24.0...


Warning: Provider source not supported in Terraform v0.12

  on 25153.tf line 3, in terraform:
   3:     google = {
   4:       source = "hashicorp/google"
   5:     }

A source was declared for provider google. Terraform v0.12 does not support
the provider source attribute. It will be ignored.

(and one more similar warning elsewhere)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
+ terraform-v0.13.0-beta1 init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/google versions matching "~> 3.3"...
- Finding terraform-providers/google-beta versions matching "~> 3.3"...
- Installing hashicorp/google v3.24.0...
- Installed hashicorp/google v3.24.0 (signed by HashiCorp)
- Installing terraform-providers/google-beta v3.24.0...
- Installed terraform-providers/google-beta v3.24.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

It would be really helpful if you could make a PR against that that fixes the reproduction case in `run.sh` or the terraform config. Based on your output it sure looks like there's a real issue, I just haven't figured out how to reproduce it on my own machine.

**Comment by tvvignesh** [comment]
@danieldreier Thanks for your quick reply. Sent you a PR with the reproduction editing the same: https://github.com/danieldreier/terraform-issue-reproductions/pull/3

**Comment by alisdair** [comment]
@tvvignesh Thanks for your help with the reproduction!

The issue here is that your configuration doesn't have `required_providers` blocks in the modules. You'll want to run the `terraform 0.13upgrade` command in each module directory to fix this.

[Here are the 0.13 docs for the command](https://github.com/hashicorp/terraform/blob/mildwonkey/ps-docs/website/docs/commands/0.13upgrade.html.markdown#batch-usage) with some example shell commands to make this process easier.

Sorry that this was a confusing error message! I'm looking into improving the diagnostics output to make it clearer in the future.

**Comment by alisdair** [comment]
Thanks again for reporting this bug. We've made a couple of improvements which will ship in the next 0.13 beta to address this:

- #25190 updates the `terraform providers` command to show the source module for each provider requirement. This allows you to see where the unexpected provider is required, so that you can update that module to fix it.
- #25191 improves the output of `terraform init`, suggesting which local modules need to be upgraded with `terraform 0.13upgrade`, and noting any remote modules which also need to be fixed.
