### ISSUE TITLE
InvalidUserData.Malformed: Invalid BASE64 encoding of user data

### ISSUE THREAD

**Issue by imyashvinder** [hashicorp/terraform#25169]
Terraform v0.12.26
+ provider.aws v2.65.0
+ provider.template v2.1.2

terrafrom plan works well. I am using variables to inject into template from userdata. Plan shows all the variables with replaced values but apply doesn't work. I am not using filebase64 for userdata in launch template because when i do variables are not getting replaced, even in plan.

template_file
----------------
```data "template_file" "bootstrap_xxxxxxxxx" {
  template = "${file("${path.module}/userdata/bootstrap_xxxxxxxxx.tpl")}"
  vars = {
    nonprodproperties_branch   = "xxxxxxxxx"
  }
}```

 

aws_launch_template
----------------------------
```resource "aws_launch_template" "generic_lt" {
  name                   = "generic-launch-template"
  image_id               = "xxxxxxxxx"
  instance_type          = "t2.medium"
  key_name               = module.xxxxxxxxx.name
  vpc_security_group_ids = [data.terraform_remote_state.core_state.outputs.xxxxxxxxx]
  #spot_price    = "0.05"

  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      delete_on_termination = "true"
      volume_size           = 30
    }
  }

  iam_instance_profile {
    name = "xxxxxxxxx"
  }

  tag_specifications {
    resource_type = "instance"

    tags = {
      Name = "xxxxxxxxx"
    }
  }

  user_data = data.template_file.bootstrap_xxxxxxxxx.rendered
}```

userdata
------------
```#!/bin/bash
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

ansible-playbook clone.yml -e "ansible_roles_version=refactor" -e "properties_version=${nonprodproperties_branch}"
```

**Comment by apparentlymart** [comment]
Hi @imyashvinder,

This seems like an AWS provider issue rather than a Terraform issue, so if there's a bug here it'd be better to report it in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws).

With that said, I think what you're encountering here may be solvable by changes to your configuration, so before reporting a bug I'd recommend starting a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core), being sure to include all of the relevant parts of your configuration _and_ the exact output you saw from Terraform, and hopefully forum participants can help figure out what's going wrong here. Thanks!
