### ISSUE TITLE
Terraform fmt should convert unquote deprecated quoted references

### ISSUE THREAD

**Issue by umairidris** [hashicorp/terraform#25180]
### Current Terraform Version

```
0.12.26
```

### Use-cases

Our primary use case is we have an e2e Terraform module generator that takes inputs from the users. Our HCL marshalling helpers can output strings, but can't differentiate in the case where the string is a deprecated quoted reference. Since we run `terraform fmt` on the output, it would be great if the format call also fixed these deprecated quotes.

### Attempted Solutions

For now we just ignore the deprecation notice or manually change them. We are also considering adding our own logic to try and unquote deprecated references.

### Proposal

Running `terraform fmt` should automatically unquote quoted references. Thus, when a user goes to run terraform init/apply they don't get a deprecation notice and don't need to do any action.

e.g.

`project = "${var.project}"`

Should become

`project = var.project`

**Comment by apparentlymart** [comment]
Hi @umairidris,

I expect that things like this will become a built-in part of `terraform fmt` eventually, but that command is currently quite conservative because it's avoiding using some less-commonly-used parts of the underlying language parsing library to reduce the risk of introducing incorrect behavior.

In the meantime, since you mentioned that you were considering writing your own implementation of unquoting these, you might find my unofficial side-project tool [`terraform-clean-syntax`](https://github.com/apparentlymart/terraform-clean-syntax) useful: it _does_ use some less-well-trodden parts of the underlying library and so I've already seen and fixed some bugs in it that should eventually benefit an official implementation. The more folks try out `terraform-clean-syntax` and report success the more confident the Teraform team is likely to become about starting to integrate similar transformations into the main `terraform fmt`.

(`terraform fmt` in 0.12 was also constrained to allow folks to continue to maintain modules that are cross-compatible with 0.11, and that does remain a bit of a concern although that will decrease over time as demand for 0.11-compatible modules wanes.)

**Comment by umairidris** [comment]
Hi Martin,

Thanks for pointing me to terraform-clean-syntax. This looks like it is exactly the thing I need! I will give it a go and respond back with any feedback in the respective repo.

Given I am unblocked, feel free to close this!

**Comment by alisdair** [comment]
This was fixed in #26390, which was released in Terraform 0.14.
