### ISSUE TITLE
Module with for_each argument does not work with -target option

### ISSUE THREAD

**Issue by llomgui** [hashicorp/terraform#25186]
Hello,

There is an issue when you try to use -target option on a module.

Example with https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/module-repetition/certificates.tf
If you try to target "example.net". It will ouput "no matches found".

`terraform apply -target=module.certificates["example.net"]`
Using the command above, it will remove `"` in the output.
If you escape  `"`, it will output the same message with  `"`. But still doesn't work.

**Comment by apparentlymart** [comment]
Hi @llomgui,

You didn't use our issue template as requested, but since you referred to the beta guide I'm assuming you are working with v0.13-beta1 here. Can you confirm?

It'd also be helpful if you can show exactly what commands you are running and what output they are producing, and let us know which operating system and shell you are running Terraform on, because the command line escaping is not part of Terraform itself and so it varies depending what you are running Terraform with.

Thanks!

**Comment by llomgui** [comment]
Hello @apparentlymart 

### Linux Version
```
Ubuntu 18.04.4 LTS
```

### Terraform Version
```
terraform -v
Terraform v0.13.0-beta1
+ provider registry.terraform.io/hashicorp/tls v2.1.1
```

### Terraform Configuration Files

https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/module-repetition/certificates.tf

### Debug Output
```
terraform apply -target=module.certificates["example.net"]
zsh: no matches found: -target=module.certificates[example.net]
```
```
terraform apply -target=module.certificates[\"example.net\"]
zsh: no matches found: -target=module.certificates["example.net"]
```

### Expected Behavior
It should target the specified resources.

### Actual Behavior
It does not find the specified resources.

### Steps to Reproduce

1. `git checkout guide-v0.13-beta `
2. `terraform init`
3. `terraform apply -target=module.certificates["example.net"]`
