### ISSUE TITLE
Terraform v0.13.0-beta1 - "data" source does not seem to depend on previous "resource"

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#25200]
This all works as expected in Terraform v0.12.26.
hashicorp/azuread: version =  0.10.0
hashicorp/azurerm: version =  2.13.0

In 0.13.0-beta1 I have the following issue (complete new run, ie removed .terrform dir and started from 100% fresh - no actual setup on Azure and no state file).

** ERROR SHOWN ** 
terraform plan is run:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
module.Cog-Operator.data.azuread_users.users: Refreshing state...
------------------------------------------------------------------------
Error: Error finding Azure AD Group with display name "Cog-Operator": Found no AD Groups matching "displayName eq 'Cog-Operator'"

  on ../modules/users_groups_roles.tf line 10, in data "azuread_group" "group":
  10: data "azuread_group" "group" {
```

** START OF MODULE CODE **  code causing issues is in bold
```
data "azuread_users" "users" {
  user_principal_names = var.users
}

resource "azuread_group" "group" {
  name = var.group
  members = data.azuread_users.users.object_ids
}

**_data "azuread_group" "group" {
  name = azuread_group.group.name
}_**

locals {
  pair = { for p in setproduct(var.roles, var.subscriptions) : "${p[0]}/${p[1]}" => {
    role = p[0]
    subscription = p[1]
    }   
  }
}

resource "azurerm_role_assignment" "roles" {
  for_each = local.pair
  role_definition_name = each.value.role
  scope = each.value.subscription
  principal_id = data.azuread_group.group.id
}
```
** END OF MODULE CODE **

It seems like the block :
```
data "azuread_group" "group" {
  name = azuread_group.group.name
}
```
expects the resource to already be created, rather than it depending on it being created in the previous resource block.

Regards,
Scott

**Comment by jbardin** [comment]
Hi @scott-doyland-burrows,

In most cases, there should be no reason to have a data source representing a resource, and the resource itself in the same configuration. References to the resource's attributes should come from the attribute itself. If the data source exposes attributes that aren't available on the resource, that could be an issues to file against the provider.

For the same reasons, this particular config should have failed in 0.12 too during the first apply, since the data source config is statically defined, and the `azuread_group` resource would not yet be created when the data source is first read. I'm not sure what was preventing that from happening previously.

If you are in a position where the data source really is required, just like if you had 2 managed resources, you need to reference a computed attribute of the resource in order to delay reading the data source. Some resources have an alternate, computed ID of some sort that could be referenced for this purpose, but I'm not sure about these in particular.

The last option, which would only work starting in 0.13 is to use `depends_on` to force the data source to wait until the dependency is fully created. 

The behavior you are seeing here though is correct, and working as intended. If you have more questions feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by scott-doyland-burrows** [comment]
Thanks.  It was my misunderstanding (I have only just started on terraform and as it worked in 0.12 I thought I had set it correctly).  I have now fixed my .tf file.
Thanks,
Scott

**Comment by scott-doyland-burrows** [comment]
Interestingly the 0.12 shows this (when I run it with my original "bad" code):

**Comment by scott-doyland-burrows** [comment]
Almost looks like terraform in 0.12 used to handle the "code error" I had made??

  # module.Cog-Operator.data.azuread_group.group will be read during apply
  # (config refers to values not yet known)
 <= data "azuread_group" "group"  {
      + description = (known after apply)
      + id          = (known after apply)
      + members     = (known after apply)
      + name        = "Cog-Operator"
      + object_id   = (known after apply)
      + owners      = (known after apply)

**Comment by jbardin** [comment]
@scott-doyland-burrows, There were some heuristic checks in place to try and defer data sources to get around the lack of being able to read them during plan, but they weren't very precise. It looks here like it may have been incorrectly deferred for some reason, which was hiding the issue.
