### ISSUE TITLE
Windows 10 terraform docker fails to pull image

### ISSUE THREAD

**Issue by khteh** [hashicorp/terraform#25227]
I have the following terraform file:
```
provider "docker" {
  host = "tcp://localhost:2375"
}

resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginx" {
  image = docker_image.nginx.latest
  name  = "tutorial"
  ports {
    internal = 80
    external = 8000
  }
}
```
Docker settings has been configured to expose `tcp://localhost:2375`. However, executing `terraform apply` results in the following error:
```
docker_image.nginx: Creating...

Error: Unable to read Docker image into resource: Unable to find or pull image nginx:latest

  on main.tf line 5, in resource "docker_image" "nginx":
   5: resource "docker_image" "nginx" {
```
When I try to `docker pull` the image:
```
C:\> docker pull nginx:latest
latest: Pulling from library/nginx
no matching manifest for windows/amd64 10.0.18362 in the manifest list entries
```
It seems that the docker client is able to reach the docker registry. 
### Terraform Version
```
C:\>terraform -v
Terraform v0.12.26
+ provider.docker v2.7.1
```
### Terraform Configuration Files

```hcl
...
```

**Comment by mildwonkey** [comment]
Hi @khteh ,
Since the docker command is failing, this isn't a problem with terraform or the docker provider.

Taking a look at the nginx docker container on [Docker Hub](https://hub.docker.com/_/nginx), I only see reference to a Proof-of-Concept windows compatible container. You would need to reach out to the nginx maintainers about that.
