### ISSUE TITLE
Allow to specify a cutomer managed KMS key  within AWS launch configuration

### ISSUE THREAD

**Issue by ipolishchuk** [hashicorp/terraform#25222]
Currently within an aws_launch_configuration resource, I can specify:

ebs_block_device { device_name = "/dev/xvdcz" volume_type = "gp2" volume_size = 300 encrypted = "True" }

to encrypt an attached EBS volume, but there does not appear to be any way to specify a particular customer-managed key using the kms_key_id parameter as with RDS.

I would like to be able to specify a particular key for EBS volume encryption within a launch configuration.

**Comment by danieldreier** [comment]
Thanks for suggesting this! I think that this is an enhancement to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
