### ISSUE TITLE
Error: Unknown root level key : Provisioner

### ISSUE THREAD

**Issue by mayanksekhar** [hashicorp/terraform#25220]
### Terraform Configuration Files
"
resource "key" "terraformtest" {
key_name = "terraformtest"
public_key = "${file("${var.PATH_TO_PUBLIC_KEY}")}"
}
resource "cloudplatform_compute_instance" "vm" {
flavor_ref = "${var.FLAVOR}"
image_ref = "${var.IMAGE}"
network = "${var.NETWORK}"
key_name = "${key.terraformtest.key_name}"
}
provisioner "file" {
source = "script.sh"
destination = "/tmp/script.sh"
connection {
type ="ssh"
user = "${var.INSTANCE_USERNAME}"
private_key = "${file("${var.PATH_TO_PRIVATE_KEY}")}"
}
}
"
vars.tf file has all the details of the variables mentioned here

ERROR is - unkmnown root level key : provisioner
Cloud used is - cloudplatform a customised Openstack, provider is privately avaliable, provider invoke was a success

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

You should also be aware that we are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. The Terraform 0.13 beta was released last Wednesday, and a second beta is coming next week. I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. I hope you will try and upgrade!
