### ISSUE TITLE
Unable to compile terraform from source

### ISSUE THREAD

**Issue by jbrunetext** [hashicorp/terraform#25239]
Hello , While trying to build Terraform using he  master branch the compilation stops 
could you please help me with it ?

### Current Terraform Version
```
terraform v0.13.0-beta1
```
### Use-cases
i would to compile terraform from source code  because the last version v0.13.0-beta1 doesn't include the fix for module loop...

### Attempted Solutions

```
 go get -v -u 'github.com/hashicorp/terraform@v0.13.0-beta1'
```
i faced an issue : 
package github.com/hashicorp/terraform@v0.13.0-beta1: invalid github.com/ import path "github.com/hashicorp/terraform@v0.13.0-beta1"

### Proposal
Could please give the doc or publish a new release of v0.13

### References

duplicate of #25192

Thank

**Comment by jbrunetext** [comment]
dep does'nt work ... so i try this cmd line ```go get -u -v -f all```

**Comment by jbardin** [comment]
Hi @jbrunetext,

You will need a current installation of `go` (currently `go1.14.4`) to build terraform. The `dep` tool is not supported, and you should be able to build Terraform using only `go` itself. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
