### ISSUE TITLE
Depends_on for module

### ISSUE THREAD

**Issue by TV4Fun** [hashicorp/terraform#25254]
### Current Terraform Version

```
Terraform v0.12.26
+ provider.google v3.25.0
+ provider.kubernetes v1.11.3
+ provider.null v2.1.2
+ provider.random v2.2.1
```

#1178 was closed prematurely. This is still a very badly needed feature. While that ticket provides a workaround, it is very hacky and not what is actually needed here.

### References

- #1178

**Comment by danieldreier** [comment]
@TV4Fun you're in luck! We've been working on this for months and just shipped it in a beta. Terraform 0.13.0 will include this feature. You can [try it in the 0.13.0 beta](https://github.com/hashicorp/terraform/issues/25016). Beta 1 is out, and beta 2 will ship Wednesday this week.

I'm going to close this because having an extra issue is confusing. Please, please please try the beta and give us feedback. We are particularly interested in people's use cases for module depends_on. If you're interested, please email me (ddreier@hashicorp.com) and Petros (petros@hashicorp.com) once you've played with it a little and can describe how you're putting module depends_on to use.
