### ISSUE TITLE
Terraform prohibits certain filter patterns to be created

### ISSUE THREAD

**Issue by ferencbeutel4711** [hashicorp/terraform#25257]
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
filter = {
  filter_pattern = "{$.request=\"*/path/to/resource/*\"}"
}
```

### Expected Behavior
Terraform should accept the string of the filter pattern with /* or */ in it

### Actual Behavior
Terraform interprets the /* and */ char sequences as comment-markers and fails to interpret the string in the intended way

### Additional Context
Hello There,
currently it seems to be impossible to specify any string which includes /* or */ - this is especially bad in the context of a filter pattern for a cloudwatch log filter metric, since every url matching utilising the wilcard * will not be possible because of that. Sadly, I couldnt find a way to escape the comment markers.

### References
- #2248

**Comment by danieldreier** [comment]
@ferencbeutel4711 can you clarify - I think you're using this in the context of the `aws_cloudwatch_log_subscription_filter` resource.

I would like to separate out the behavior of that specific resource, which is something handled by the aws provider, from terraform core behavior of strings.

I created a simple reproduction case just using a local exec at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/25257 to show that terraform can indeed process a string container /* and */ in it.

I got the following successful output:
```
null_resource.example: Creating...
null_resource.example: Provisioning with 'local-exec'...
null_resource.example (local-exec): Executing: ["/bin/sh" "-c" "echo \"/* hello world */\""]
null_resource.example (local-exec): /* hello world */
null_resource.example: Creation complete after 0s [id=5065262998816776078]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

I'm trying to figure out whether this issue should be handled in TF core or in the AWS provider. I think that in #2248 the issue was that *no* strings could contain comment characters. I think I demonstrated that isn't the case in this example. If you are able to reproduce a case where simply making a string with comment characters causes them to be inescapable, please make a PR to demonstrate it so we can fix it.

Otherwise, I think this issue ought to be in the AWS provider, because core just passes the string to the provider and then some kind of parsing happens in there.

**Comment by ferencbeutel4711** [comment]
hi Daniel, thank you for your quick respsonse. Maybe I misunderstood the issue and it is indeed something specific to the provider - your example kind of proofs that. I'll raise this with the provider then, thanks for your input!
