### ISSUE TITLE
provisioner "local-exec" not working with resource calculating with for_each for list variable

### ISSUE THREAD

**Issue by KapilTeotia1** [hashicorp/terraform#25293]
Hi All,

Need your kind help if we can use provisioner "local-exec" with any resource which we are creating with the help of list of map?

In below example I am creating simply two buckets with the help of list variable using for each. And I am just redirecting their ARN and other few details in another file. However I am facing an issue that it is not working with multiple values as could not fetch arn for both the buckets and redirect them.

it is just expecting self.arn and I am not able to use it for all two resources. If I only use it with a resource having only single value not list then it works.

Could you please advise how I can achieve this.

---------------------------------------------main.tf-------------------------------------------

provider "aws" {
  region = "eu-west-1"
}

variable "bucketname" {
  type = "list"
  default = ["mytestbuckettfmodule1", "mytestbuckettfmodule2"]
}

resource "aws_s3_bucket" "mybucket" {
  for_each = toset(var.bucketname)
  bucket = each.value
  acl = "private"

  tags = {
    Company = "MyCompany"
    CostCenter = "21101257"
    Environment = "NonProd"
    Name = "TestInstane"
    Role = "Test"
    Service = "Test"
    User = "kapil.teotia"
  }

provisioner "local-exec" {
    command = <<CMD
    echo '{"Rules":[{"DeleteMarkerReplication": { "Status": "Disabled" },"Status":"Enabled","Priority":1,"Filter":{"Prefix":""},"Destination":{"Bucket":"${**aws_s3_bucket.mybucket[each.value].arn**}"}}]}' >> ./file.json
    CMD

}
}

---------------------------------------------------------

If we just pass only one bucket in resource and use below then it works okay.

  provisioner "local-exec" {
    command = <<CMD
    echo '{"Rules":[{"DeleteMarkerReplication": { "Status": "Disabled" },"Status":"Enabled","Priority":1,"Filter":{"Prefix":""},"Destination":{"Bucket":"${**self.arn**}"}}]}' >> ./file.json
    CMD

}

**Comment by KapilTeotia1** [comment]
Getting below error:

![CaptureTF](https://user-images.githubusercontent.com/49716866/85057227-1a37f980-b1be-11ea-86fa-356f6d455936.JPG)

**Comment by jbardin** [comment]
Hi @KapilTeotia1,

Referencing `aws_s3_bucket.mybucket` creating a dependency between every instance, which ends up creating this cycle. I'm not sure what exactly you're trying to do, because `aws_s3_bucket.mybucket[each.value]` is the same as `self`. If you want to run something based on all instances, you probably need to do it with a separate resource, maybe using `local-exec` in a `null_resource`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
