### ISSUE TITLE
Better Documentation needed ASAP!

### ISSUE THREAD

**Issue by ameyaptk** [hashicorp/terraform#25298]
Been working on creating GCP resources with Terraform for quite some time now and let me tell you- the documentation is a nightmare. It requires much better articulation, formatting, structure and accuracy. Some of the arguments are missing types, default values and sometimes even the descriptions are downright confusing. Users are left guessing this vital information based on errors thrown while planning. Here is an example- 
[https://www.terraform.io/docs/providers/google/r/compute_address.html](url)

What does the `address` field do? Is it internal or external IP?

`address` - (Optional) The static **external IP** address represented by this resource. Only IPv4 is supported. An address may **only be specified for INTERNAL address types**. The IP address must be inside the specified subnetwork, if any.

**Comment by apparentlymart** [comment]
Hi @ameyaptk,

It sounds like you're giving feedback related to the Google Cloud Platform provider here, in which case the right place for that is [the provider's own repository](https://github.com/terraform-providers/terraform-provider-google). Individual providers are separate codebases from Terraform itself and their documentation is maintained by the individual provider development teams, not by the Terraform Core team.

Because the documentation you're referring to is not in this codebase, I'm going to close this issue. Please open an issue in the provider repository to give feedback on the provider-specific documentation. Thanks!
