### ISSUE TITLE
InvalidParameterException: load balancers can have at most 5 items.

### ISSUE THREAD

**Issue by marchof** [hashicorp/terraform#25306]
### Terraform Version

```
Terraform v0.12.26
+ provider.aws v2.46.0
```

### Terraform Configuration Files
```hcl
resource "aws_ecs_service" "main" {
  name            = "javasandboxes"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.javasandboxes.arn
  desired_count   = "1"
  launch_type     = "FARGATE"

  network_configuration {
    security_groups  = [aws_security_group.backend.id]
    subnets          = aws_subnet.backend.*.id
    assign_public_ip = true
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.java11.id
    container_name   = "java11"
    container_port   = "8011"
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.java12.id
    container_name   = "java12"
    container_port   = "8012"
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.java13.id
    container_name   = "java13"
    container_port   = "8013"
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.java14.id
    container_name   = "java14"
    container_port   = "8014"
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.java15.id
    container_name   = "java15"
    container_port   = "8015"
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.java16.id
    container_name   = "java16"
    container_port   = "8016"
  }

  depends_on = [
    aws_alb_listener.sandboxes
  ]
}
```

### Debug Output
https://gist.github.com/marchof/155cebf633f38ad81d90e6c84c1921c1

### Crash Output
No crash, just error message:

```
Error: InvalidParameterException: load balancers can have at most 5 items. “javasandboxes"
```

### Expected Behavior
`apply` would create 6 items as `plan` suggests would happen

### Actual Behavior
The service is destroyed but not created any more with the following error message:

`apply` would create 6 items as `plan` suggests would happen

### Steps to Reproduce

`terraform apply`

### Additional Context

I can create the additional load balancer target manually in the AWS web interface without any problems and it is also working then.

### References

none

**Comment by apparentlymart** [comment]
Hi @marchof,

The error message you saw here is being generated by the AWS provider rather than Terraform Core, so there isn't a change we could make in this repository to make it behave as you expected.

The syntax of the error message makes me suspect that this is a limitation of the underlying API rather than something Terraform's AWS provider is imposing, so it probably isn't possible to support six items via a change to the provider either, but I'm not very familiar with ECS so I may be wrong about that. If you suspect I _am_ wrong, please open an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) about this, and then the AWS provider team can consider how to support six or more load balancer blocks.

Thanks!

**Comment by marchof** [comment]
Thanks @apparentlymart for pointing me in the right direction and sorry for the noise!
