### ISSUE TITLE
Terraform : This object has no argument, nested block, or exported attribute named when using null_resource

### ISSUE THREAD

**Issue by KapilTeotia1** [hashicorp/terraform#25325]
Hi All,

Need your kind help around below issue, I am getting while using null_resource. I have created two buckets and just want to simply run a command for both the buckets with the help of null resource. However I am getting error "**This object has no argument, nested block, or exported attribute named arn**". Could anyone please guide me what I am doing wrong here. Actually I am bit new in Terraform. :)

**Code:**

provider "aws" {
  region = "eu-west-1"
}
provider "null" {}

########################################

variable "bucketname" {
  type = "list"
  default = ["mytestbuckettfmodule1", "mytestbuckettfmodule2"]
}

########################################**below resource to create two buckets**

resource "aws_s3_bucket" "mybucket" {
  for_each = toset(var.bucketname)
  bucket = each.value
  acl = "private"
  tags = {
    Company = "ABC"
    CostCenter = "21102353"
    Environment = "NonProd"
    Name = "TestInstane"
    Role = "Test"
    Service = "Test"
    User = "kapil.teotia@ABC.com"
  }
}

########################################**below null resource to execute command under local-exac for both the buckets**

resource "null_resource" "mybucket" {
depends_on = ["aws_s3_bucket.mybucket"]
  triggers = {
    s3bucket = "${join(",",**aws_s3_bucket.mybucket.id**)}"
  }
  provisioner "local-exec" {
    command = <<CMD
      echo '{"Rules":[{"DeleteMarkerReplication": { "Status": "Disabled" },"Status":"Enabled","Priority":1,"Filter":{"Prefix":""},"Destination":{"Bucket":"${**self.arn**}"}}}]}' >> ./file.json
      CMD
  }
}

########################################

**Comment by KapilTeotia1** [comment]
![Error1](https://user-images.githubusercontent.com/49716866/85232324-b90d6180-b41b-11ea-8bac-0ae770190a0a.JPG)
![Error2](https://user-images.githubusercontent.com/49716866/85232325-bad72500-b41b-11ea-883d-aaed2181944b.JPG)

**Comment by jbardin** [comment]
Hi @KapilTeotia1 

You appears to be attempting to reference a `for_each` resource using `*` which is not valid.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by KapilTeotia1** [comment]
Thanks @jbardin, Could you please guide how I can use null resource to access/refer values from a resource having for_each?
