### ISSUE TITLE
DNSconfig option not visible for azure container instance

### ISSUE THREAD

**Issue by jakond1** [hashicorp/terraform#25329]
Hi Team,

I dont see DNSCONFIG parameter field for creating azure container instance terraform whilch required to mention when integrating ACI with VNET(with custom DNS server). KIndly help with the details if already there.
https://www.terraform.io/docs/providers/azurerm/r/container_group.html

**Comment by apparentlymart** [comment]
Hi @jakond1,

This seems to be feedback about the Azure provider rather than about Terraform Core. If so, you can record it in [the Azure provider repository](https://github.com/terraform-providers/terraform-provider-azurerm). If you do so, please properly complete one of the repository's issue templates.

If this is a usage question rather than a bug report or enhancement request, please create a topic in [the Azure provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) instead. GitHub issues are only for bug reports and enhancement requests.

Thanks!
