### ISSUE TITLE
Terraform plan output as azure devops PR comment

### ISSUE THREAD

**Issue by kalis777** [hashicorp/terraform#25335]
I am using terraform to configure our Azure Traffic Manager profiles using it through Azure DevOps pipeline. One of the goal is to get the terraform plan command output as the PR comment. I am using the "Create PR Comment task" to post the output as the PR comment. It is working but I am missing the format and is appearing in a not easily readable form. 

Has anyone have any suggestions or workaround for this?

**Comment by pkolyvas** [comment]
Hey there,

Thanks for taking the time to write us.

Due to the number of issues & enhancement requests we work through here, we encourage our community to ask questions over at our [community forums](https://discuss.hashicorp.com/c/terraform-core/27). More help outside of bugs and feature requests is available there.
