### ISSUE TITLE
Timeout error while creating aws_api_gateway_vpc_link resource

### ISSUE THREAD

**Issue by prithakundu** [hashicorp/terraform#25344]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-east-1"
  version = "2.43.0"
}

resource "aws_lb" "nlb" {
  name                             = "test-shared-nlb"
  internal                         = true
  load_balancer_type               = "network"
  enable_cross_zone_load_balancing = "true"
  subnets                          = ["${data.terraform_remote_state.environment.vpc_private_subnet_ids}"]

  timeouts {
    create = "15m"
    delete = "15m"
  }
}

resource "aws_api_gateway_vpc_link" "main" {
  name        = "test-shared-gateway"
  target_arns = ["${aws_lb.nlb.id}"]
}
```

### Expected Behavior
aws_api_gateway_vpc_link should create successfully.

### Actual Behavior
1 error(s) occurred:
* aws_api_gateway_vpc_link.main: 1 error(s) occurred:
* aws_api_gateway_vpc_link.main: Error waiting for APIGateway Vpc Link status to be "AVAILABLE": timeout while waiting

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
This is an intermittent issue. Is there any way to increase default timeout?

**Comment by apparentlymart** [comment]
Hi @prithakundu,

This seems to be a question related to the AWS Provider, rather than about a Terraform Core behavior. A better place to ask AWS provider questions is [the AWS provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). If you intended to open an enhancement request for a new feature to enable this, you could alternatively [open a feature request issue in the AWS Provider's repository](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md).

Since this repository is for Terraform Core rather than the AWS Provider, I'm going to close this issue.

Thanks!
