### ISSUE TITLE
Support for scopes in `terraform login` / `login.v1` protocol

### ISSUE THREAD

**Issue by jceresini** [hashicorp/terraform#25354]
We're interested in using our existing identity provider (Identity Server 4) to gate access to our own private terraform module repository. After some testing, I noticed 2 things:

* Identity Server 4 does not allow auth_code flow without being passed the requested scopes
* Terraform doesn't support specifying application scopes in the `login.v1` discovery document

I would like to be able to pass back the scopes required for terraform access in the discovery document. Example:
```
GET /.well-known/terraform.json

{
      "login.v1": {
        "client": "our_client_id",
        "grant_types": ["authz_code"],
        "authz": "our_authorize_endpoint",
        "token": "our_token_endpoint",
        "ports": [10000, 10010],
        "scopes": "terraform_scope"  ### Something like this
      }
    }
```

And I would like `terraform login [our_hostname]` to construct the authorize url with the scopes it saw in the above document.

Oauth2 does not require scopes at the authorize endpoint, but blocking the request on the authorization side is also valid:

https://tools.ietf.org/html/rfc6749#section-4.1.1

>  If the client omits the scope parameter when requesting
>  authorization, the authorization server MUST either process the
>  request using a pre-defined default value or fail the request
>  indicating an invalid scope.  The authorization server SHOULD
>  document its scope requirements and default value (if defined).

So from that point-of-view both terraform, and identity-server-4 adhere to the spec. However, OpenID Connect **does** require the scopes parameter: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

I also opened a feature request for Identity Server 4 to allow auth requests without scopes, but in the past they have stated that its a design choice they don't plan to change:

https://github.com/IdentityServer/IdentityServer4/issues/4254#issuecomment-609029124

https://github.com/IdentityServer/IdentityServer4/issues/4556

**Comment by apparentlymart** [comment]
Hi @jceresini! Thanks for this enhancement request.

Allowing selection of one or more scopes does seem like a reasonable way to make `terraform login` compatible with more existing OAuth implementations. Our underlying OAuth library seems to expect scopes to be specified as a slice of strings which it then presumably concatenates into a space-separated string itself, so I think we'd define this new property as being a JSON array of strings instead of a single string and then copy that slice verbatim into the OAuth client configuration so it can encode it appropriately.

One awkward detail here is that adding this now means that there will be some specific version of Terraform at which scopes are supported, while all prior versions of Terraform with `terraform login` support would silently ignore `scopes` and then presumably the OAuth server will produce a confusing error. We can't retrofit negotiation of that feature into existing versions of Terraform, so unfortunately it would be up to you as the implementer of a Terraform-native service host to document that your server requires a particular minimum version of Terraform and potentially hear from users who tried to use older versions and got a confusing error. With that said, it sounds like you're implementing a private registry with its access limited to folks inside your organization, so that'd only be a temporary problem until all of your in-house Terraform users have upgraded.

We probably won't be able to prioritize a change to implement this in the near future because our focus is currently elsewhere, but if you or somebody else were interested in working on it then we'd be happy to review a pull request. I think the main things to change here would be:

* [`disco.ServiceOAuthClient`](https://github.com/hashicorp/terraform-svchost/blob/d2e4933b91362709122c21cd14b6b51cf6e5bfca/disco/host.go#L127) to decode this extra `scopes` argument, requiring it to be an array of strings, and save it as a new `Scopes` field of type `[]string` in [`disco.OAuthClient`](https://github.com/hashicorp/terraform-svchost/blob/d2e4933b91362709122c21cd14b6b51cf6e5bfca/disco/oauth_client.go#L14).
* Add some new test cases to [the `ServiceOAuthClient` tests](https://github.com/hashicorp/terraform-svchost/blob/d2e4933b91362709122c21cd14b6b51cf6e5bfca/disco/host_test.go#L74) to show that a correct `scopes` is handled, omitting `scopes` is still okay (leaving the `Scopes` field set to `nil`), and that invalid values of `scopes` (such as a single string or an array of something other than strings) return suitable error messages.
* Set the `Scopes` field [when we populate `oauth2.Config`](https://github.com/hashicorp/terraform/blob/fdab1704cc1373095af1b527b44b4bd03ee1cabd/command/login.go#L382), so the client will include those in the authorization request. (Should also do this [in the password grant type handler](https://github.com/hashicorp/terraform/blob/fdab1704cc1373095af1b527b44b4bd03ee1cabd/command/login.go#L475) for consistency, even though the only server we allow for that right now doesn't use it.)
* Add a new permutation to [the `terraform login` tests](https://github.com/hashicorp/terraform/blob/fdab1704cc1373095af1b527b44b4bd03ee1cabd/command/login_test.go) to verify that the scope passes through correctly when discovery includes it, and is omitted when discovery doesn't include it.

**Comment by jceresini** [comment]
Thanks for the detailed response @apparentlymart ! I submitted a PR for `terraform-svchost`, and just finished getting approval for signing the CLA. 

https://github.com/hashicorp/terraform-svchost/pull/5

**Comment by freakinhippie** [comment]
@jceresini I see that the `terraform-svchost` portion of this has been completed, great work! Are there plans to do the `terraform` side as well?

**Comment by jceresini** [comment]
@freakinhippie I just submitted a PR for that here: https://github.com/hashicorp/terraform/pull/26239
