### ISSUE TITLE
Support for Multi-line Conditional Expressions / Ternary

### ISSUE THREAD

**Issue by WilliamABradley** [hashicorp/terraform#25362]
### Current Terraform Version

```
0.12.26
```

### Use-cases

It would be nice if we could use multi-line conditional expressions, especially if we are using conditionals with objects as the result. 

This currently doesn't work properly if you break it into multiple lines.

This will make our Terraform files more readable.

### Attempted Solutions

```tf
locals {
  condition1 = true
  condition2 = false
  obj = (condition1 == true && condition2 != true) ? { prop_aa = "a", prop_ab = "b", prop_ac = "c" } : { prop_ba = "a", prop_bb = "b", prop_bc = "c" }
}
```

### Proposal

```tf
locals {
  condition1 = true
  condition2 = false
  obj = (condition1 == true && condition2 != true) 
    ? { prop_aa = "a", prop_ab = "b", prop_ac = "c" } 
    : { prop_aa = "a", prop_bb = "b", prop_bc = "c" }
}
```

or

```tf
locals {
  condition1 = true
  condition2 = false
  obj = (condition1 == true && condition2 != true) 
    ? { 
          prop_aa = "a"
          prop_ab = "b"
          prop_ac = "c" 
      } 
    : { 
          prop_ba = "a"
          prop_bb = "b"
          prop_bc = "c" 
      } 
}
```

**Comment by apparentlymart** [comment]
Hi @WilliamABradley! Thanks for making this proposal.

The Terraform language is similar to Python in that it considers newline to be the end of a single "statement" (in Terraform's case, an argument definition) _unless_ the newline is inside some sort of bracket.

Because of that, you can wrap any expression over multiple lines by writing it in parentheses:

```hcl
  obj = (
    condition1 == true && condition2 != true ?
    { 
      prop_aa = "a"
      prop_ab = "b"
      prop_ac = "c" 
    } :
    {
      prop_ba = "a"
      prop_bb = "b"
      prop_bc = "c" 
    }
  )
```

When at least one level of parentheses is open, Terraform ignores newlines as with other space characters. This is a general thing that works for any expression type, not just conditionals:

```hcl
  example = (
    1 + 2 + 3 + 4 + 5
  )
```

The parser implements this using a mode-switching technique in the tokenizer, using the `(` and `)` tokens (along with the other "bracket" pair `[]`) to turn newline-sensitive mode on and off. It's not really feasible to implement a special case for a newline followed by a `?`, because the decision about whether the newline is a significant token or not must be taken before the tokenizer has encountered the `?`.

Because the bracket-counting rule already meets this use-case in a more general way, I'm going to close this. Hopefully that approach works for you!
