### ISSUE TITLE
0.12upgrade command leaves empty lines at the end of all converted files, leading to SCM warnings

### ISSUE THREAD

**Issue by jcmcken** [hashicorp/terraform#25370]
### Terraform Version
```
Terraform v0.12.24
```

### Terraform Configuration Files

Happens to any configuration. Try a simple 0.11 config like:

```terraform
variable "foo" {
  type = "string"
}
```

### Expected Behavior

Don't add empty lines to the ends of files. For large workspaces/modules, requires a lot of manual effort to remove these lines so that SCM (e.g. git) doesn't complain about them.

### Steps to Reproduce

* Create a TF 0.11 *.tf file
* Run ``terraform 0.12upgrade`` and confirm
* Review the results. There should be an empty line at the end of the file.

**Comment by jcmcken** [comment]
The ``versions.tf`` file also gets created with an empty line at the beginning of the file

**Comment by apparentlymart** [comment]
Hi @jcmcken,

This seems to be the same as #21428. As noted there, the behavior of `terraform 0.12upgrade` is now frozen, and that is even more true now because mainline Terraform v0.12 development has concluded with Terraform v0.13 about to be released in a few weeks.

I understand that the behavior of this tool doesn't agree with everyone's preferred formatting style. The decisions it makes are consistent but, as with all such style decisions, also arbitrary; there is no set of rules it could use that would've pleased everyone. Its result is just a proposal and you can feel free to rewrite it however you like before you merge to your version control system. For a mechanical rule like "remove all trailing newlines from all `.tf` files" it should be possible to apply such a change programmatically with a script.

Because there will be no further changes to `terraform 0.12upgrade` at this time, I'm going to close this. I'm sorry the formatting decisions this tool makes by default don't agree with your house style.
