### ISSUE TITLE
Improve labeling of docker images in dockerhub

### ISSUE THREAD

**Issue by afischer-opentext-com** [hashicorp/terraform#25388]
Hi once a new version of terraform is released, a new docker image becomes available in dockerhub. 

As it seems the docker labels full/light are always some flavor of latest. This is unfortunate. 13 days ago hashicorp/terraform:full reflected version 0.13.0-beta2, since 8 hours it is 0.12.27. This is somewhat unfortunate. 

### Use-cases

I want to work either with the latest version of production/or development releases of terraform but do not want to care about specific versions as this is for my development but not for production purposes. 

### Proposal

Introduce a better concept for the labels of hashicorp/terraform docker images. 

Preferably I would like to have something like

* 0.1[2|3]_light
* 0.1[2|3]_full
* stable_light -> 0.12_light
* stable_full -> 0.12_full
* dev_light -> 0.13_light
* dev_full -> 0.13_full

and so on... 

### References

* https://hub.docker.com/r/hashicorp/terraform/tags

**Comment by alisdair** [comment]
The Docker tags are intended only to support the most recent generally-available releases of Terraform. The tagging of 0.13.0-beta2 as `full`/`light` was a mistake (noted in #25279) and should not happen again.

At this time we have no plans to publish tags for beta/prerelease versions of Terraform. You should be safe to continue targeting `full` to receive the most recent GA Terraform release.

Sorry for the inconvenience we caused by the mistaken tags last week!
