### ISSUE TITLE
Configuration still contains unknown values during apply

### ISSUE THREAD

**Issue by stbondarenko** [hashicorp/terraform#25383]
### Terraform Version

```
Terraform v0.12.26
```

### Terraform Configuration Files

```
https://www.dropbox.com/s/1vpbd7c8tr9mlrb/configuration.zip
```

### Debug Output

https://gist.github.com/stbondarenko/416741affeae4b1ce9d008ccc8938c8a
### Expected Behavior

aws_ssm_parameter created

### Actual Behavior

Error: configuration for module.example.aws_ssm_parameter.example still contains unknown values during apply (this is a bug in Terraform; please report it!)

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @stbondarenko,

Your configuration has a typo, in the `aws_ssm_parameter`, you have `value = module.example-instance.0.private_ip` with an extra `.0.` in the reference. Changing that to `module.example-instance.private_ip` should resolve the issue.

Unfortunately 0.12 is not able to catch this type of incorrectly indexed module reference, but this will result in an error explaining that it is an invalid index in 0.13!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
