### ISSUE TITLE
No schema available for azurerm_private_link_endpoint.prendpt

### ISSUE THREAD

**Issue by ankushkhatri537** [hashicorp/terraform#25402]
### Terraform Version

``I am using the latest terraform version`
...
```

### Terraform Configuration Files
<!--
Paste the relevant parts of your Terraform configuration between the ``` marks below.
"resource "azurerm_private_endpoint" "prendpt" {
  name                = "privateendpoint-sqlserver-preprod-ibpmqa"
  location            = var.location
  resource_group_name = "rg-bizpreprod-ibpm-qa"
  subnet_id           = data.azurerm_subnet.subnet3.id

   private_service_connection {

     name                                  = "privateendpoint-sqlserver-preprod-ibpmqa"
     is_manual_connection                  = false
     private_connection_resource_id        = azurerm_sql_server.sql.id
     subresource_names              = [
               "sqlServer",
            ] 
     
  }

}"
For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file. For security, you can also encrypt the files using our GPG public key.
-->

```hcl
...
```

### Expected Behavior

"Error: no schema available for azurerm_private_link_endpoint.prendpt while reading state; this is a bug in Terraform and should be reported"

**Comment by ankushkhatri537** [comment]
Hello Team,

I am using azurerm provider version 2.4.0. I tried it with the latest version 2.15.0 as well however while running terraform plan, it is throwing the same error "no schema available for azurerm_private_link_endpoint.prendpt while reading state; this is a bug in Terraform and should be reported".

I have tried with updating terraform version from 0.12.24 to 0.12.28  but no luck.

**Comment by jbardin** [comment]
Hi @ankushkhatri537,

Looking at the changelog for the asurerm provider, it appears the deprecated `azurerm_private_link_endpoint` resource was removed in version 2 of the provider. You will need to manually remove it from the state and clean up any resources using the native Azure tooling.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
