### ISSUE TITLE
Resource: kubernetes_secret  - Dynamic block causes Unsupported block type

### ISSUE THREAD

**Issue by thcp** [hashicorp/terraform#25405]
### Terraform Version

```
0.12.26
```

### Terraform Configuration Files

```hcl
locals {
 sample_secrets = [
  {
   secret_a = "base64value"
   secret_b = "base64 value"  
  }
 ]

}

resource "kubernetes_secret" "secret" {
  for_each = toset(local.envs)
  metadata {
    name = "generic"
    namespace =  each.value
  }
  dynamic "data" {
    for_each = local.sample_secrets
    content  {
      secret_a = data.value["secret_a"]
      secret_b = data.value["secret_b"]
    }
  }

  type = "generic"
}
```

### Actual Behavior
```
<!--
Error: Unsupported block type

  on 60-aks.tf line 187, in resource "kubernetes_secret" "secret":
 187:   dynamic "data" {

Blocks of type "data" are not expected here.

  4,47s user 0,47s system 80% cpu 6,160 total
-->
```

**Comment by jbardin** [comment]
Hi @thcp 

Looking at that provider, it seems that `data` isn't a block, rather it's a simple map. You should be able to construct this dynamically using a [`for` expression](https://www.terraform.io/docs/configuration/expressions.html#for-expressions).

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
