### ISSUE TITLE
Support references between child modules when using for_each

### ISSUE THREAD

**Issue by brandonstrohmeyer** [hashicorp/terraform#25414]
### Current Terraform Version

```
0.13.0-beta2
```

### Use-cases

Using a `for_each` iterator at the module level allows for dynamic outputs to be generated. This is especially helpful for things that have a lot of entries, such as AWS IAM roles or Security Groups. As an example, I can use for_each at the module level to generate an arbitrary number of iam-role modules and then automatically create an output object for each one like so:

```
module "iam-role" {
  source             = "app.terraform.io/..."
  version            = "2.1.0"

  for_each           = local.iam.roles
  role_name          = each.key
  assume_role_policy = try(each.value.assume_role_policy, {})
  aws_managed_policy = try(each.value.aws_managed_policy, [])
  iam_policy         = try(each.value.iam_policy, [])
}

output "iam" {
  value = {
    role = {
      for role in module.iam-role:
      role.name => role.arn
    }
  }
}
```

This works fine and will create an output map automatically without having to manually define every module output you want. Helpful when you have several dozen IAM Roles.

### Attempted Solutions

This breaks when when you attempt to make a resource reference between child modules. For example, if I need to create an IAM role and then reference the ARN from a different IAM role:

```
  iam = {
    roles = {
      eks-cluster-node = {
        iam_policy = [... ]
      }
      other-role-with-eks-dependancy = {
        assume_role_policy = templatefile("${path.module}/files/iam/other-role.json.tpl", { trust_principal_arn = module.iam-role["eks-cluster-node"].aws_iam_role.arn })
        iam_policy = [... ]
      ...
      }
```

This configuration will result in a cycle error, presumably because cross-child resources lookups are not supported and the "other-role-with-eks-dependancy" is attempting to get the value of `module.iam-role["eks-cluster-node"].aws_iam_role.arn`
### Proposal

Reference a child module directly within the scope of the parent module

**Comment by jbardin** [comment]
Hi @brandonstrohmeyer,

If you are asking about referencing a particular instance of a module from another instance of the same module, that is possible in the configuration right now. The difficulty in creating a configuration like this is that these references need to connect only disjoint sets of resources in order to not create a cycle. I'm not sure what your complete configuration entails, but you will have to restructure it in some way to not have any circular dependencies, maybe by having the `trust_principal_arn` created from a separate module.

Even though I understand that Terraform isn't doing what you expect it to, this isn't something that can be changed in Terraform. Please do feel free to ask your question in the [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers. Thanks!
