### ISSUE TITLE
Input validation block for local variables needed

### ISSUE THREAD

**Issue by mapdegree** [hashicorp/terraform#25422]
### Current Terraform Version

```
0.12.28
```

### Attempted Solutions

- we need to sanitise input from data or any other internal calculations using local variables, using only 'input variables' was not sufficient

### Proposal
- introduce same logic for local variables as for input variables

### References

- reuse logic of #25054 from input variables to include in local variables

**Comment by apparentlymart** [comment]
Hi @mapdegree! Thanks for this proposal.

I think this is covering the same use-case as #15469, and there's already some commentary there about some different ways to represent assertions about "internal" values, rather than input variables. It's likely that something will come for this in a future release, but I'm going to close this issue just to consolidate discussion in #15469.

Thanks again!

---

In the meantime, one (admittedly awkward) way you can use the variable validation feature to validate something within a module is to write a child module that consists only of a validation rule:

```hcl
variable "to_validate" {
  type = string

  validation {
    # (whatever rule you need)
  }
}

output "validated" {
  value = var.to_validate
}
```

You can instantiate this module setting `to_validate` to whatever local value you want to validate:

```
module "validate_foo" {
  to_validate = local.foo
}
```

...and then elsewhere in the module you can use `module.validate_foo.validated` instead of `local.foo` to get a result that is guaranteed to have passed your validation rules.

It's too cumbersome for everyday use, but if you have a module that is particularly in need of an internal assertion for some reason then this is a way to get that done with the features as they currently exist.
