### ISSUE TITLE
Apply not applying after adding another local-exec inside aws_sns_topic

### ISSUE THREAD

**Issue by pawanyoda** [hashicorp/terraform#25425]
### Terraform Version
 Terraform v0.12.26
+ provider.aws v2.68.0

### Terraform Configuration Files
```
resource "aws_sns_topic" "email" {
  name = "${var.commonName}-${var.environment}-email"

  provisioner "local-exec" {
    command = "aws --region ${var.aws_region} --profile ${var.aws_profile} sns subscribe  --topic-arn ${aws_sns_topic.email.arn}  --protocol email --notification-endpoint ${var.email_name}"
   }
}
```
The above terraform is working the first time but if I add another email it is not updating, Like the below example.

```
resource "aws_sns_topic" "email" {
  name = "${var.commonName}-${var.environment}-email"

  provisioner "local-exec" {
    command = "aws --region ${var.aws_region} --profile ${var.aws_profile} sns subscribe  --topic-arn ${aws_sns_topic.email.arn}  --protocol email --notification-endpoint ${var.email_name}"
   }
  provisioner "local-exec" {
    command = "aws --region ${var.aws_region} --profile ${var.aws_profile} sns subscribe  --topic-arn ${aws_sns_topic.email.arn}  --protocol email --notification-endpoint ${var.email_client}"
   }
}

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...

**Comment by jbardin** [comment]
Hi @pawanyoda,

Provisioners are run when the resource is is created, and since there was no change to the resource, the provisioner is not going to be executed. If you wish to replace the instance, you can use the `taint` command to do so. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
