### ISSUE TITLE
kubernetes_service_account secret list

### ISSUE THREAD

**Issue by tommyjcarpenter** [hashicorp/terraform#25435]
The docs here: https://www.terraform.io/docs/providers/kubernetes/r/service_account.html

Says that secrets is a list. However, I cannot figure out how to actually do that. Please see the HCL below

### Terraform Version
```
Terraform v0.12.9
+ provider.azurerm v2.14.0
+ provider.helm v1.2.1
+ provider.kubernetes v1.11.3
```

### Terraform Configuration Files

```
resource "kubernetes_service_account" "my-sa" {
  metadata {
    name = "${var.my_sa_name}"
  }
  automount_service_account_token = true

  # A list of secrets allowed to be used by pods running using this Service Account
  secret  {
    name = "${kubernetes_secret.foo.metadata.0.name}"
    # how to add another??
  }

  # invalid
  #secret = [
  #  "${kubernetes_secret.foo.metadata.0.name}"
  #  "${kubernetes_secret.foo2.metadata.0.name}"
  #]

  # invalid
  #secret = [
  #  {
  #  name = "${kubernetes_secret.foo.0.name}"
  #   },
  #   {
  #  name = "${kubernetes_secret.foo2.0.name}"
  # }
  #]
}
```

### Expected Behavior
Some type of list syntax validates and works and the comment "A list of secrets allowed to be used by pods running using this Service Account" holds

### Actual Behavior
Secrets seems to not actually want a list

**Comment by apparentlymart** [comment]
Hi @tommyjcarpenter,

This issue seems to be about the Kubernetes provider rather than Terraform Core. This repository is focused on Terraform Core, and all of the providers are developed in their own repositories.

I'm not sure if your issue here is intended as a bug report or as a question about correct syntax. If it's a question, I think the best thing to do next would be to start a topic in [the Kubernetes provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/kubernetes/40). If you are intending to report a bug, you might instead open an issue in [the `kubernetes` provider repository](https://github.com/hashicorp/terraform-provider-kubernetes).

It doesn't seem like there is anything we could change in this repository to improve the situation you described, so I'm going to close this issue. Thanks!
