### ISSUE TITLE
terraform template_dir issue

### ISSUE THREAD

**Issue by vikaskoppineedi** [hashicorp/terraform#25459]
Hi All, 

Trying to use template_dir terraform function

resource "template_dir" "manifests" {
  depends_on = [
    null_resource.clean_build_output,
    null_resource.create_output_dirs
  ]
  source_dir      = "cluster-manifest-templates"
  destination_dir = "build_output/cluster-manifest-templates"

  vars = {
    CLUSTER_NAME = "${var.cluster-name}-${var.environment}"
    REGION = "${var.region}"
  }
}

I am getting the following error 

Error: open build_output/cluster-manifest-templates/container-insights\cloudwatch-namespace.yaml: The system cannot find the path specified.

If you see the error, most of the path has forward slash "/" and the last file  has backword slash "\". 

Any help? 

running on Windows using Gitbash.

**Comment by alisdair** [comment]
Hi @vikaskoppineedi, thanks for reporting this.

This looks to me like it's probably a bug in the `template` provider. [This provider has been deprecated](https://www.terraform.io/docs/providers/template/index.html#deprecation), which means that the bug won't be fixed.

Instead of using `template_dir`, we recommend that you use the [`hashicorp/dir/template` module](https://registry.terraform.io/modules/hashicorp/dir/template/1.0.1). Hopefully this should allow you to achieve what you're looking for.

If you have any problems using this module, please [ask a question in the Terraform discuss forum](https://discuss.hashicorp.com/c/terraform-core), where hopefully someone will be able to help.

**Comment by vikaskoppineedi** [comment]
@alisdair , Thanks for the reply. I have exactly used the hashicorp/dir/template and I have achieved what I had to. Its took me couple hours last night til 4 am to make it work. Thank you wonderful community for helping me. Thank you so much guys.
