### ISSUE TITLE
Inappropriate value error when accessing resource made with for_each

### ISSUE THREAD

**Issue by keng000** [hashicorp/terraform#25450]
### Terraform Version

```
Terraform v0.12.28
+ provider.aws v2.68.0
```

### Terraform Configuration Files

```hcl
locals {
  map_of_element = {
    name1 = 1
    name2 = 2
  }
}

resource "aws_cloudwatch_event_rule" "rule" {
  for_each = local.map_of_element

  name                = each.key
  schedule_expression = "cron(0 1 * * ? *)"
}

resource "aws_cloudwatch_event_target" "target_for_rule" {
  for_each = local.map_of_element

  rule = aws_cloudwatch_event_rule.rule[each.key]
  arn  = "sample_arn"
}

provider "aws" {
  version = "~> 2.5"
  region  = "us-east-1"
}

```

### Debug Output

https://gist.github.com/keng000/b067a62ede5f2ec105eb68ed636fb440

### Expected Behavior
I thought that `aws_cloudwatch_event_target` will be create for each `aws_cloudwatch_event_rule` made by for_each with the local variable `map_of_element`.
It seems the key accessing to the `aws_cloudwatch_event_rule.rule` object is string, but the error log says "string required.". 
What is the problem?

I'm concerned about the difference that the debug log says, the key accessing to the `aws_cloudwatch_event_rule.rule` is `\"name1\"` not `"name1"`  (first seen in https://gist.github.com/keng000/b067a62ede5f2ec105eb68ed636fb440#file-terraform-debug-log-for-inappropriate-value-when-accessing-resource-made-with-for_each-L790)
### Actual Behavior and Steps to Reproduce

```
terraform init
terraform plan
```

then the output will be like below
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Incorrect attribute value type

  on sample.tf line 18, in resource "aws_cloudwatch_event_target" "target_for_rule":
  18:   rule = aws_cloudwatch_event_rule.rule[each.key]
    |----------------
    | aws_cloudwatch_event_rule.rule is object with 2 attributes
    | each.key is "name1"

Inappropriate value for attribute "rule": string required.


Error: Incorrect attribute value type

  on sample.tf line 18, in resource "aws_cloudwatch_event_target" "target_for_rule":
  18:   rule = aws_cloudwatch_event_rule.rule[each.key]
    |----------------
    | aws_cloudwatch_event_rule.rule is object with 2 attributes
    | each.key is "name2"

Inappropriate value for attribute "rule": string required.


```

**Comment by apparentlymart** [comment]
Hi @keng000,

[The documentation for `aws_cloudwatch_event_target`](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_target.html) says that the `rule` argument expects a rule name, which is a string. In your configuration here you've assigned an `aws_cloudwatch_event_rule` object, which is rejected because it's not of the expected type.

From referring to the examples in the documentation for the resource type it seems like the fix here would be to add the `.name` attribute to the end of your reference:

```hcl
  rule = aws_cloudwatch_event_rule.rule[each.key].name
```

If you have any further questions about this then please feel free to start a topic in [the AWS provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). Thanks!
