### ISSUE TITLE
the content of dynamic blocks not exapanded in order defined

### ISSUE THREAD

**Issue by richpeaua** [hashicorp/terraform#25477]
### Terraform Version

```
v0.12.28
```

### Expected Behavior

The start_time and end_time fields for this Pager Duty provider code needs to be applied in that exact order or else I get an error from the Pager Duty api (I think the Pager Duty provider code is also broken as it _should_ to be able to consume the fields in any order and then parse them correctly to generate the correct api payload). I made the block dynamic to make it optional, as there are two ways to schedule Pager Duty rules.

```terraform
dynamic "active_between" {
      for_each = lookup(var.ruleset_rules[count.index], "active_between")
      content {
        start_time = active_between.value.start_time
        end_time   = active_between.value.end_time
      }
```

should look like this in a `terraform apply/plan`

```
+ time_frame {
          + active_between {
              + start_time   = 30000
              + end_time = 100000
            }
        }
```

### Actual Behavior

I get this in `terraform plan/apply` instead.

```
+ time_frame {
          + active_between {
              + end_time   = 30000
              + start_time = 100000
            }
        }
```
This also happens to all other dynamic blocks I've set, though they don't appear to require this strict ordering. The ordering of the dynamic block content also seems to be in alphabetical order.

e.g same `terraform apply/plan` output  but different dynamic blocks.

#### Example 1
```
    + scheduled_weekly {
          + duration   = 3000
          + start_time = 1000
          + timezone   = "America/Los_Angeles"
          + weekdays   = [
              + 3,
              + 7,
            ]
        }
```

should be 

```
    + scheduled_weekly {
           + weekdays   = [
                        + 3,
                        + 7,
              ]
           + timezone   = "America/Los_Angeles"
           + start_time = 1000
           + duration   = 3000
       }
```

#### Example 2

```
      + parameter {
          + path  = "payload.summary"
          + value = "db"
       }
```

should be

```
      + parameter {
          + value = "db"
          + path  = "payload.summary"
       }
```

### Steps to Reproduce

check the `terraform apply/plan` output of a dynamic block with multiple content fields to see if they are in the order defined.

**Comment by jbardin** [comment]
Hi @richpeaua 

The fields of each object created by the block have no order, and once they are communicated to the provider through the legacy SDK they are contained in a map, which is also an unordered data structure.

Can you provider an example of the problem you're attempting to solve here? I suspect that this is an issue with the provider, rather than Terraform itself. 

Thanks!

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
