### ISSUE TITLE
Docker image build failures due to terraform-bundle versions

### ISSUE THREAD

**Issue by maheshmadpathi** [hashicorp/terraform#25471]
I was trying to build Terraform Docker Image using below `Dockerfile` and it fails with weird errors

```bash
FROM golang:alpine AS terraform-bundle-build

RUN apk --no-cache add git unzip && \
  go get -d -v github.com/hashicorp/terraform && \
  git -C ./src/github.com/hashicorp/terraform checkout v0.13.0-beta3 && \
  go install ./src/github.com/hashicorp/terraform/tools/terraform-bundle

COPY terraform-bundle.hcl .

RUN terraform-bundle package -os=linux -arch=amd64 /go/terraform-bundle.hcl && \
  mkdir -p terraform-bundle && \
  unzip -d terraform-bundle terraform_*.zip
```
and my `terraform-bundle.hcl` looks like below

```bash
terraform {
  version = "0.13.0-beta3"
}

providers {
  aws = {
    versions = ["~> 2.26.0"]
  }

  archive = {
    versions = ["~> 1.3.0"]
  }

  null = {
    versions = ["2.1.0"]
  }

  local = {
    versions = ["~> 1.0"]
  }

  random = {
    versions = ["~> 2.1.2"]
  }

  template = {
    versions = ["~> 2.1.2"]
  }
}
```
I get below error with above files 
```
Failed to read config: this version of terraform-bundle can only build bundles for Terraform v0.13 and later; build terraform-bundle from a release tag (such as v0.12.*) to construct bundles for earlier versions
```
Could you please correct the version of `Terraform` thats available for downloads in `terraform-bundle.hcl` as it results in error below
```
Failed to fetch core package from https://releases.hashicorp.com/terraform/v0.13.0/terraform_v0.13.0_linux_amd64.zip: bad response code: 403
```
https://github.com/hashicorp/terraform/blob/ab93bca6c59c204d91f5ded4ced01a8d66cff82c/tools/terraform-bundle/e2etest/testdata/many-providers/terraform-bundle.hcl#L2

**Comment by hollowsunsets** [comment]
Also have this problem. :'(

**Comment by dantrauner** [comment]
I'm using 0.12.29 and just checked out `tags/v0.12.29` before installing `terraform-bundle` to work around this, but using the same exact syntax as you for the bundle file, I'm getting:

```
Failed to read config: At 7:13: root.providers.archive[0]: unknown type for string *ast.ObjectType
```

**Comment by maheshmadpathi** [comment]
> I'm using 0.12.29 and just checked out `tags/v0.12.29` before installing `terraform-bundle` to work around this, but using the same exact syntax as you for the bundle file, I'm getting:
> 
> ```
> Failed to read config: At 7:13: root.providers.archive[0]: unknown type for string *ast.ObjectType
> ```

@dantrauner looks like the providers syntax in your terraform_bundle.hcl file

**Comment by dantrauner** [comment]
@maheshmadpathi I'm at a loss here – do you see the mistake?

```hcl
terraform {
  version = "0.12.29"
}

providers {
  archive = {
    versions = ["~> 1.3.0"]
  }

  aws = {
    versions = ["~> 3.0.0"]
  }
}
```

**Comment by dantrauner** [comment]
Well, upgrading to 0.13.0 and using `source` appropriately for any third-party providers seems to have fixed this 🤷‍♂️

**Comment by apparentlymart** [comment]
Hi all,

The `terraform-bundle` utility is intended only for use with Terraform CLI versions of the same major release as the bundle tool itself, because the tool is just a thin wrapper around the provider installation functionality in `terraform init`. This tool primarily exists as a way for Terraform Enterprise users to produce custom Terraform packages to use in their Terraform Enterprise execution environments, and its convenience (or not) for other use-cases is, to be honest, rather more incidental.

From Terraform 0.13 and later there are some better options for maintaining local repositories of providers. At the time I'm writing this Terraform Enterprise does not yet include first-class support for these, but for those of you who are using `terraform-bundle` for other purposes, such as populating Docker containers, I have a different procedure to recommend which doesn't require any external tools except Terraform CLI itself:

1. Create a normal Terraform configuration that _at least_ includes the provider requirements for the providers you need. It can either be an existing configuration you're already using or a new one written only to declare the requirements, like this:

    ```hcl
    terraform {
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "~> 2.26.0"
        }
        archive = {
          source  = "hashicorp/archive"
          version = "~> 1.3.0"
        }
        null = {
          source  = "hashicorp/null"
          version = "~> 2.1.0"
        }
        local = {
          source  = "hashicorp/local"
          version = "~> 1.0"
        }
        random = {
          source  = "hashicorp/random"
          version = "~> 2.1.2"
        }
        template = {
          source  = "hashicorp/template"
          version = "~> 2.1.2"
        }
      }
    }
    ```
2. Download and extract the official `.zip` package for whichever version of Terraform CLI you intend to use.
3. In the root module directory of that configuration, run the following command to get local copies of all of the listed providers in the subdirectory `providers`:

    ```
    terraform providers mirror -platform=linux_amd64 providers
    ```

    ```
    - Mirroring hashicorp/local...
      - Selected v1.4.0 to meet constraints ~> 1.0
      - Downloading package for linux_amd64...
      - Package authenticated: signed by HashiCorp
    - Mirroring hashicorp/random...
      - Selected v2.1.2 to meet constraints ~> 2.1.2
      - Downloading package for linux_amd64...
      - Package authenticated: signed by HashiCorp
    - Mirroring hashicorp/template...
      - Selected v2.1.2 to meet constraints ~> 2.1.2
      - Downloading package for linux_amd64...
      - Package authenticated: signed by HashiCorp
    - Mirroring hashicorp/aws...
      - Selected v2.26.0 to meet constraints ~> 2.26.0
      - Downloading package for linux_amd64...
      - Package authenticated: signed by HashiCorp
    - Mirroring hashicorp/archive...
      - Selected v1.3.0 to meet constraints ~> 1.3.0
      - Downloading package for linux_amd64...
      - Package authenticated: signed by HashiCorp
    - Mirroring hashicorp/null...
      - Selected v2.1.2 to meet constraints ~> 2.1.0
      - Downloading package for linux_amd64...
      - Package authenticated: signed by HashiCorp
    ```
4. Arrange for the contents of that `providers` directory to be installed at `/usr/local/share/terraform/plugins` in the environment where Terraform will run. For example, if you are building a Docker image then you should create and populate that directory in your `Dockerfile` so that it will be available in containers created from that image.

   ```
   # These might need "sudo" if you are working as a non-root user.
   mkdir -p /usr/local/share/terraform
   cp -r providers /usr/local/share/terraform/plugins
   ```

When you run `terraform` it will search `/usr/local/share/terraform/plugins` (and [some other directories](https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories)) for providers and for any it finds there it will use the local directory for installation instead of the origin registry for that provider.

If you have some different needs that aren't fully accommodated by the above, I suggest taking a look at [the Provider Installation options in the CLI config](https://www.terraform.io/docs/commands/cli-config.html#provider-installation), which includes some other possibilities such as mirroring providers onto a HTTP server in your local network, in case you want to maintain the provider repository separately instead of copying the needed providers into each docker image.

I believe the Terraform Enterprise team is planning to incorporate support for alternative provider installation sources in a forthcoming release, at which point `terraform-bundle` will be deprecated due to being superseded by these other, better options.

**Comment by dantrauner** [comment]
Thanks for that workaround @apparentlymart! Worked great.

**Comment by mildwonkey** [comment]
There's no bug here, so I am going to close this issue. Thanks all!
