### ISSUE TITLE
aws_api_gateway_deployment doesn't trigger a deployment with new changes in api method/integration resource

### ISSUE THREAD

**Issue by poojasingh-cgi** [hashicorp/terraform#25486]
Description:- We have deployed aws api gateway using swagger import in terraform. The problem here is if I do any changes in aws api gateway method or integration , aws_api_gateway_Deployment doesn’t get updated after a dependents resource change . 

For example: if I make any changes in swagger to modify request template(mapping template) in api gateway integration resource, terraform aws_api_gateway_Deployment resource doesn’t trigger a deployment and the stage specified in the deployment continue to use the old configuration until you do the manual deploy in aws console.

In order to avoid manual deployment, I found a solution for this issue but i would like to know the best approach.

Temporary Solution :-  if i add a variables for deployed_at = timestamp() so every time you do the changes in api method or integration , it will trigger a deployment with new changes in api resources.
Also I thought of adding ignore_changes attribute to my deployment to avoid terraform changing variables on the deployment every time I run it.
 
resource "aws_api_gateway_deployment" "rest_api" {
  rest_api_id = aws_api_gateway_rest_api.rest_api.id
  stage_name  = ""

  variables = {
    deployed_at = timestamp()
  }

  lifecycle {
    ignore_changes = [variables]
  }
}

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
