### ISSUE TITLE
Multiple Terraform errors “no definition was found” & “Argument is not expected here”

### ISSUE THREAD

**Issue by vishal8k** [hashicorp/terraform#25489]
### Terraform Version

```
v0.12.26
...
```

### Terraform Configuration Files
I have a multi-repo setup in terraform.

Repo1: Contains all the source code. (Will be Zipped and uploaded to storage-account or s3)

Repo2: Contains only module file that has the source as the above Zip file

Repo1: main-module.tf file contents:

```
module "kubernetes" {
    source = "./path/to/source-file/source.tf"
    my_dns = var.dnsname
}
```
main-module input_variables.tf contents:
```
variable "dnsname" {
  description = "Internal DNS name"
}
```
Terraform plan and apply goes successful for this repo. No problem at all. The error comes when planning in 2nd repo. Below are the contents of 2nd repo.

2nd Repo Module.tf contents:

```
module "testmodule" {
  source = "path/to/repo1.zip"
  my_dns = var.dnsname
}
```
2nd Repo input_variables.tf contents:
```
variable "dnsname" {
  description = "Internal DNS name"
}
```
Terraform init went well but initiating terraform plan I'm displayed with two errors stating the below

```
Error: Missing required argument

  on module.tf line 7, in module "testmodule":
   7: module "testmodule" {

The argument "dnsname" is required, but no definition was found.


Error: Unsupported argument

  on module.tf line 39, in module "testmodule":
  39:   my_dns = var.dnsname

An argument named "my_dns" is not expected here.
```

No help from any of your communities. That is why posting here. 
https://stackoverflow.com/questions/62757908/multiple-terraform-errors-no-definition-was-found-argument-is-not-expected

**Comment by jbardin** [comment]
Hello!

It looks from the error that you have a variable named `dnsname` defined, but are passing in an a value for `my_dns`, which is not defined. The module configuration must match the declared variables exactly.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
