### ISSUE TITLE
core: Save variable values in state

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#2550]
Variable values may change the state and generally everything and I believe these should be optionally treated as state.

e.g. etcd discovery token definitely isn't something I want to save in my repository, yet I want to share that token with people using that repository and allow them changing that token eventually.

I was thinking there could be a new `variable` attribute:

``` ruby
variable "token" {
  sync_with_state = true
}
```

then if `sync_with_state == true`, the following may happen during `terraform apply` and `terraform plan`:
1. Check value saved in state
2. Check `default` value
3. Check `terraform.tfvars` and/or `-var-file`
4. Check `-var` arguments
5. If nothing of the above has value, ask via prompt

This could also allow us to do the following:

```
resource "aws_instance" "foo" {
    # ...
    count = "${terraform_remote_state.my-module.var.size}"
}
```

It may also help solving https://github.com/hashicorp/terraform/issues/1230

**Comment by kotfic** [comment]
+1

**Comment by shmish111** [comment]
@radeksimko did you ever find a solution for this? There is https://www.tweag.io/posts/2019-04-03-terraform-provider-secret.html which allows you to import something however it doesn't provide default values.

**Comment by shmish111** [comment]
@radeksimko @kotfic I know this issue is a bit old but I want to get your opinion anyway since you had this issue.

I have created a new resource for this provider where you have the following
```
resource "secret_string_variable" "teststring" {
  default = "hello"
}
```
This actually stores 2 values in state, `default` and `value`. If you want to set this value yourself you must do:
```
terraform state rm secret_string_variable.teststring
terraform import secret_string_variable.teststring something
```
There is a small issue with this, when you do `terraform apply` you will get the following
```
Terraform will perform the following actions:

  ~ secret_string_variable.teststring
      default: "" => "hello"
```
This is because I don't think it's possible to import a value and reference the `default` value in the configuration.

What do you think, would this cover your use cases? Is there some way you think I could improve this?

**Comment by iaroslav-nakonechnikov** [comment]
in some cases this is very useful feature. 
especially, when terraform stack is being created and updated automatically via ci/cd things.
but when it is needed to debug something it will help a lot.

**Comment by crw** [comment]
Closing this issue due to extreme age and relevance per conversation with the core team. The design of Terraform is to recompute variables on demand, and to not store the computed value in state. 

@iaroslav-nakonechnikov in this case, it may be useful to use `output` to show the contents of a variable. This is typically how members of the core team do this type of debugging. I hope this helps!
