### ISSUE TITLE
Terraform and passing variables with double quotes

### ISSUE THREAD

**Issue by sandeep444033** [hashicorp/terraform#25502]
I need to pass variables via Terraform to Ansible as follows,

lvs=["lv_opt_san"]

I am passing via command line,

/usr/local/bin/terraform apply -auto-approve -var lvs=["\"lv_opt_san\""]

I tried following different ways for passing lvs variable in above condition (/usr/local/bin/terraform apply -auto-approve -var lvs) and each of following are sending variables as follows,

lvs=['"lv_opt_san"'] --> [lv_opt_san]
lvs=["\\\"lv_opt_san\\\""] --> [\"lv_opt_san\"]
lvs=["\\\\"lv_opt_san\\\\""] --> [\\lv_opt_san\\]
lvs=["\"lv_opt_san\""] --> [lv_opt_san]
lvs=['\\\"lv_opt_san\\\"'] --> [\\\"lv_opt_san\\\"]

I absolutely need lvs variable to be passed as lvs=["lv_opt_san"] to my Ansible.

**Comment by apparentlymart** [comment]
Hi @sandeep444033,

This seems to be a usage question rather than a bug report or a feature request, so I suggest starting a topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core). When you do so, please be sure to mention which operating system you are running and which shell you are using because it seems like this question is about shell escaping syntax rather than Terraform's own behavior.

We use GitHub issues for tracking bugs and enhancements rather than for questions, so I'm going to close this. I do frequently check the community forum so if you ask there I will hopefully be able to work with you to find the answer to your question, if someone else doesn't answer first.

Thanks!

**Comment by sandeep444033** [comment]
Thanks @apparentlymart 

I have this open in community https://discuss.hashicorp.com/t/issue-with-escaping-variables/11261 with all the details mentioned.
