### ISSUE TITLE
Error:  Failed to download module (while trying to download module from external provider)

### ISSUE THREAD

**Issue by rishitsheth94** [hashicorp/terraform#25518]
Hi,

I am trying to download a module from external provider but end up getting error message as show below. I checked couple of threads and it tell to upgrade the terraform version to 0.12.19 or later as a workaround of this issue. I am using terraform with version 0.12.28 which shouldn't cause this issue as it is a latest one. I am stuck here and need an urgent help to resolve this issue

FYI: I am using a windows host machine

**Error: Failed to download module

Could not download module "consul" (modules.tf:1) source code from
"github.com/wardviaene/terraform-consul-module.git?ref=terraform-0.12": error
downloading
'https://github.com/wardviaene/terraform-consul-module.git?ref=terraform-0.12':
git must be available and on the PATH**

**Comment by alisdair** [comment]
To download Terraform modules from git, you need to have git installed on your workstation. Do you have git installed? If you run `git` from your console or shell, does it work?

If not, you may want to try installing [Git for Windows](https://git-scm.com/download/win).

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
