### ISSUE TITLE
Error: error getting S3 Bucket location: timeout while waiting for state to become 'success' (timeout: 2m0s)

### ISSUE THREAD

**Issue by srivaibhavsagar** [hashicorp/terraform#25510]
resource "aws_s3_bucket" "s3_Bucket" {
  bucket = "testing-s3-neet-vaibhav-s"
  acl    = "private"
  force_destroy = "true"
}

trying to create a s3 bucket .The bucket is getting created in the AWS Console instead it is failing.
Terraform v0.12.26
+ provider.aws v2.69.0
Any suggestions ?

**Comment by apparentlymart** [comment]
Hi @srivaibhavsagar,

This seems like a usage question about the AWS provider rather than a bug report or feature request for Terraform Core. Therefore I'd suggest you start a topic in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) instead.

We use GitHub issues for tracking bugs and enhancements rather than for questions, so I'm going to close this issue. Thanks!
