### ISSUE TITLE
Hanging issue with all commands

### ISSUE THREAD

**Issue by j-cbblas** [hashicorp/terraform#25525]
### Terraform Version

```
2020/07/08 15:54:15 [INFO] Terraform version: 0.12.28  
2020/07/08 15:54:15 [INFO] Go runtime version: go1.13.12
2020/07/08 15:54:15 [INFO] CLI args: []string{"/usr/local/bin/terraform", "version"}
2020/07/08 15:54:15 [DEBUG] Attempting to open CLI config file: /Users/myname/.terraformrc
2020/07/08 15:54:15 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/07/08 15:54:15 [INFO] CLI command args: []string{"version"}
Terraform v0.12.28
2020/07/08 15:54:15 [DEBUG] checking for provider in "."
2020/07/08 15:54:15 [DEBUG] checking for provider in "/usr/local/bin"
2020/07/08 15:54:15 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for support requests. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
