### ISSUE TITLE
Terraform error : "project: required field is not set" while importing GCP resource "google_monitoring_alert_policy" 

### ISSUE THREAD

**Issue by shubham061292** [hashicorp/terraform#25537]
Hi,

I have created few "google_monitoring_alert_policy" in my GCP project and I want to import these policies to the terraform to manage them with terraform in future.

However I am facing following error while Importing the "google_monitoring_alert_policy" : 

Error: project: required field is not set

While Project id is mentioned in my terraform resource file.

I am trying to import with following methods : 

1. terraform import google_monitoring_alert_policy.alert_policy_resource_name_in_terraform_file alert-policy-name-in-gcp-project

2. terraform import google_monitoring_alert_policy.alert_policy_resource_name_in_terraform_file 
 projects/project-id/alert-policy-name-in-gcp-project

I am getting same error with both methods. It is a bug or am I missing something.

Please help me on the same.

Regards,
Shubham Awasthi

**Comment by apparentlymart** [comment]
Hi @shubham061292,

This seems like a usage question about the Google Cloud Platform provider rather than a bug report for Terraform Core, so I suggest instead opening an issue in [the Google Cloud Platform provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32).

We use GitHub issues for tracking bugs and enhancements rather than for questions, and this repository is only for Terraform Core (not provider) functionality, so I'm going to close this issue. Thanks!
