### ISSUE TITLE
Terraform command not taking variable values from shell script

### ISSUE THREAD

**Issue by RamanaChowdam** [hashicorp/terraform#25530]
terraform apply -auto-approve -var 'region=$wme_region' -var 'access_key=$wme_access_key' -var 'secret_key=$wme_secret_key' -var 'public_subnet_id=$wme_public_subnet_id' -var 'pemfile=$wme_pemfile' -var 'vpc_id=$wme_vpc_id' -var 'private_keypath=$wme_private_keypath' -var 'wme_installer_url=$wme_setup_url' -var 'admin_user_password=$wme_admin_user_password' -var 'enterpise_name=$wme_enterprise_name' -var 'user_email=$wme_user_email' -var 'user_first_name=$wme_user_first_name' -var 'user_last_name=$wme_user_last_name' -var 'user_password=$wme_user_password' -var 'os_type=$wme_os_type' -var 'rhel_version=$wme_rhel_version'

i am applying the above command for terraform execution
i am passing that variable values from shell script ,the command is placed in inside of shell script

i am passing values to variables from shell script arguments
terraformsetup.sh us-east-2 vpc-id like
but terraform not taking variables from the shell script
how can I pass variables to terraform command from shell script arguments

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
