### ISSUE TITLE
[Docs] Possible inconsistency in documentation concerning the self object in provisionners

### ISSUE THREAD

**Issue by simonlegeek** [hashicorp/terraform#25548]
In the main provisioners documentation, a specific section describe how to use the `self` object and explain why it allows to avoid cycle dependency issues. It explicitely says that a provisioners can't refer to it's parent resource by it's name.

From [https://www.terraform.io/docs/provisioners/index.html#the-self-object](url)

> The self Object
Expressions in provisioner blocks cannot refer to their parent resource by name. Instead, they can use the special self object.
The self object represents the provisioner's parent resource, and has all of that resource's attributes. For example, use self.public_ip to reference an aws_instance's public_ip attribute.
Technical note: Resource references are restricted here because references create dependencies. Referring to a resource by name within its own block would create a dependency cycle.

That being said, in the provisioner example of local-exec, the provisioner specificly use the usual resource address to call it's parent.

From [https://www.terraform.io/docs/provisioners/index.html#how-to-use-provisioners](url)
```terraform
resource "aws_instance" "web" {
  # ...

  provisioner "local-exec" {
    command = "echo ${aws_instance.web.private_ip} >> private_ips.txt"
  }
}
```

Does the first statement is an old restriction from previous version of Terraform or are there special corner case where you can or cannot use the resource address/name to refer to it's attribute?

I hope I am filing this request for precision at the right place.

Thanks

**Comment by apparentlymart** [comment]
Hi @simonlegeek,

It seems like the documentation for the `local-exec` provisioner is incorrect: it should be showing `self.private_ip` there. Let's consider this issue to represent updating the docs to fix that problem.

---

Since it seems like you're curious about the backstory here a bit, some additional context: a key difference between `self` vs typing out the reference to the resource itself occurs when the resource is using either `count` or `for_each`.

In that case, there is a difference between the resource as a whole and the _current instance_ of the resource. Terraform can understand without any further analysis that `self` is a reference only to the current instance, and thus it doesn't need to generate any dependency edges, but an expression like `aws_instance.web[each.key]` contains a dynamic index into `aws_instance.web` and so the dependency static analyzer (which happens before the expressions are evaluated) would conservatively assume that this expression depends on _all_ instances of `aws_instance.web`, which is not the same as depending on the _current_ instance and so all of the instances end up depending on each other, creating a cycle.

When `count` and `for_each` are not present there is no real distinction between the resource as a whole and the single instance of it, so that extra dependency can potentially get filtered out as part of a simple "no node can depend on itself" rule. However, I would still recommend using `self` in order to avoid confusion if future changes make that no longer hold, and so that's why I'm considering this issue to be one about incorrect documentation even though that simple example may happen to work.

**Comment by simonlegeek** [comment]
Wow, thank you for taking the time to explain this behavior with such details and clarity. 

Love what you are doing guys! Keep up the good work!
