### ISSUE TITLE
Terraform docker_registry_image tries connecting to local registry with https

### ISSUE THREAD

**Issue by austenadler** [hashicorp/terraform#25549]
From the example given on the docs: https://www.terraform.io/docs/providers/docker/d/registry_image.html I have:

```
data "docker_registry_image" "xxx" {
  name = "192.168.12.1:5000/xxx"
}
resource "docker_image" "xxx" {
  name    = data.docker_registry_image.xxx.name
  pull_triggers = [data.docker_registry_image.xxx.sha256_digest]
}
```

And terraform always fails on apply with:
```
Error: Got error when attempting to fetch image version from registry: Error during registry request: Get https://192.168.12.1:5000/v2/xxx/latest: http: server gave HTTP response to HTTPS client
```

How to disable https for a local registry?

`/etc/docker/daemon.json` contains this host in `insecure-registries` on local and remote. `docker pull 192.168.12.1:5000/xxx` works on local and remote.

**Comment by apparentlymart** [comment]
Hi @austenadler,

This seems like a usage question about the Docker provider rather than a Terraform Core bug report. This repository only covers the Terraform Core (not provider-specific) functionality, and we use GitHub issues only for bug reports and feature requests, so I'm going to close this.

The Docker provider doesn't have its own community forum, but you could try asking your question in [the general Terraform Providers category of the community forum](https://discuss.hashicorp.com/c/terraform-providers/31). If you'd like to report a bug or feature request for the Docker provider, you can do that in [the Docker provider's repository](https://github.com/terraform-providers/terraform-provider-docker).

Thanks!
