### ISSUE TITLE
Cannot Remove Unused Custom Provider Plugin

### ISSUE THREAD

**Issue by kevinbirch** [hashicorp/terraform#25547]
### Terraform Version

```
Terraform v0.12.28
+ provider.google v3.29.0
+ provider.google-beta v3.29.0
+ provider.helm v1.2.3
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.mysql v1.9.0
+ provider.null v2.1.2
+ provider.postgresql v1.6.0
+ provider.postgresql-mvn v1.6.0  <-- This one right here!
+ provider.random v2.3.0
+ provider.tls v2.1.1
```

### Terraform Configuration Files

I think this is not applicable in this situation?

### Expected Behavior

I added some new functionality to the [Postgresql Provider](https://github.com/terraform-providers/terraform-provider-postgresql/pull/126) which was eventually merged, but in the mean time I used a custom build added to my repository under the `terraform.d/plugins` directory.  Now I want to delete that provider plugin from my repository and scrub the configuration of any references to it in favor of the latest official version.  As you can see above in my list of plugins the `postgresql-mvn` was the custom local build.

However, after changing the provider declarations to refer to `postgresql` instead of `postgresql-mvn`, when I try to remove the `terraform.d/plugins` directory I get an error message:

```
$ tf init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "postgresql-mvn" not available for installation.

A provider named "postgresql-mvn" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

Error: no provider exists with the given name
```

### Actual Behavior

I still see the provider listed with `terraform providers`:

```
$ tf providers
.
├── provider.google
└── module.system
    ├── provider.google (inherited)
    ├── module.dbt
        ├── provider.google (inherited)
        ├── provider.helm
        ├── provider.kubernetes
        ├── provider.local
        ├── provider.null
        ├── provider.postgresql
        ├── provider.postgresql-mvn (from state)
        ├── provider.random
```

If I put back the custom provider files everything works just fine.  I also tried running `terraform apply` (with no pending changes) and `terraform refresh` but neither can clear out the old provider from the state.  Do I actually have to make a *real* change to the resources that were created with the custom provider for the official one to be fully used instead?

### Steps to Reproduce

1. Create a custom build of an official provider.
2. Install custom build into your repository with a name that won't conflict with the official name.
3. Use custom provider.
4. Update `provider` block and any `provider =` expressions to use the official provider instead of the custom build.
5. Run `$ rm -rf terraform.d`
6. Run `$ terraform init`
7. See error output, be confused.

### References

- [This comment](https://github.com/hashicorp/terraform/issues/18104#issuecomment-442706575) from #18104, could be related but was never followed up on that I can see.

**Comment by apparentlymart** [comment]
Hi @kevinbirch,

Unfortunately the behavior you've observed here is, I think, what I'd expect to see from Terraform v0.12 in this situation. As you suspected, Terraform will generally only update the entry for a particular resource in the state if the plan calls for that resource to be changed, and so the old provider addresses can stick around until the next time there's a change that would be shown in a plan, which doesn't apply to changes to provider configuration.

The forthcoming Terraform 0.13 includes a change to this behavior as part of adding explicit support for third-party providers, and so under Terraform 0.13 I would expect what you tried here to work. Terraform 0.13 also includes a new subcommand `terraform state replace-provider` that allows swapping one provider for another in the state as a single operation.

Terraform 0.12 options are more limited though, because Terraform 0.12 isn't really designed to support third-party providers well. One option is to make a "real" change to each of these resources to inspire Terraform to rewrite their entry in the state, as you suspected, but it sounds like you have several and so that would likely not be a practical answer here.

I think my next best option here would be to manually edit the latest state snapshot to refer to the `postgres` provider instead of the `postgres-mvn` provider:

* Make sure anyone or anything else that might apply changes to this configuration do not try to apply for the duration of these steps, to avoid consistency problems.
* Run `terraform state pull >temp.tfstate` to retrieve a local copy of the latest state snapshot.
* Open `temp.tfstate` in your favorite editor and replace the provider associations for `provider.postgresql-mvn` with `provider.postgres` instead, being sure to maintain any `module.foo` prefixes or `.alias` suffixes that those might have. Then locate the top-level `serial` property and increment the number you see there to make it explicit that you are intending to create a new state snapshot.
* Run `terraform state push temp.tfstate` to upload the updated file as a new state snapshot.
* Run `terraform providers` again to verify that `provider.postgresql-mvn` is no longer present.

**Comment by kevinbirch** [comment]
Hi @apparentlymart, thanks for the detailed instructions.

If I were to simply taint the resources created by the old provider would that also force the state to be updated or is your method the only practical solution?

**Comment by apparentlymart** [comment]
If you mark them as tainted then Terraform will still believe that they need to be destroyed (as part of replacing them) and so I expect it will still want to use the `postgres-mvn` provider to do that, because the state records that provider as being the one that is currently managing the object.

There is another similar option in that vein though, if you are willing to recreate these objects anyway (as `terraform taint` would've): you could use `terraform state rm` to remove the existing objects from the state and let Terraform recreate them, and then manually delete the objects left behind. If these resource types support `terraform import` then a further variant could be to re-import them, although you might need to run `terraform refresh` after the `terraform state rm` but before the `terraform import` to make sure that `terraform state rm` (a pretty "surgical" operation on a single resource instance) didn't leave behind any resource-level metadata in the state. (It is conservative in some ways to allow for when folks want to carefully remove an individual instance and import a new one in its place without disturbing any others.)

**Comment by kevinbirch** [comment]
Ok, understood.  It does sound like your original approach is the most practical.  Thank you for your help!

**Comment by danieldreier** [comment]
@kevinbirch I'm going to close issue as resolved because I think Martin has answered your immediate question and clarified that this is improved in 0.13 and expected in 0.12. Thanks for bringing this up, and this definitely validates that we went down the right path in 0.13. I hope you'll be able to switch to 0.13 soon!
