### ISSUE TITLE
helper/schema: TestProviderDiff_timeoutInvalidValue fails on Go 1.15

### ISSUE THREAD

**Issue by kevinburkemeter** [hashicorp/terraform#25553]
Hi,
The error message now includes a quoted string, so this test fails on Go 1.15:

```go
	expectedErrMsg := "time: invalid duration invalid"
	if !strings.Contains(err.Error(), expectedErrMsg) {
		t.Fatalf("Unexpected error message: %q\nExpected message to contain %q",
			err.Error(),
			expectedErrMsg)
	}
```

```
--- FAIL: TestProviderDiff_timeoutInvalidValue (0.00s)
    provider_test.go:346: Unexpected error message: "[ERR] Error decoding timeout: Error parsing \"create\" timeout: time: invalid duration \"invalid\""
        Expected message to contain "time: invalid duration invalid"
```

The failing test is in helper/schema/provider_test.go

**Comment by apparentlymart** [comment]
Hi @kevinburkemeter!

We recently switched our main branch to Go 1.15.2 in #26357, which included an update of this test for the error output in Go 1.15. Therefore I'm going to close this as fixed, although third-party packagers like Homebrew likely should wait until the forthcoming Terraform 0.14 release to switch their local builds. The Terraform 0.13 series will remain on Go 1.14 because Go 1.15 ends support for some versions of our target platforms and has some other minor changes in standard library behavior that may be breaking for some users.
