### ISSUE TITLE
Support for_each on settings blocks

### ISSUE THREAD

**Issue by fdw** [hashicorp/terraform#25551]
### Current Terraform Version
```
v0.12.26
```

### Use-cases
We configure our services with environment variables on elastic beanstalk, that is, using  `setting`s block on `aws_elastic_beanstalk_environment`. In several instances, we would like to dynamically create them based on the contents of a `map` variable (for each map item, we need several settings).

At the moment, we have to manually define all settings, which makes the setup more manual and more brittle than desired.

### Attempted Solutions
Unfortunately, it seems that using `for_each` is not possible in `setting`.

### Proposal
Ideally, it would be possible to use `for_each` also in `setting` to create several of them.

### References
None that I have found.

**Comment by jbardin** [comment]
Hi @fdw 

If I understand correctly, you're looking for [dynamic blocks](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks).

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by fdw** [comment]
Thank you very much!

I hadn't found anything regarding this concept, so I thought I would open a feature request.
