### ISSUE TITLE
Can't use logging with aws_sfn_state_machine

### ISSUE THREAD

**Issue by kuhnboy** [hashicorp/terraform#25579]
### Current Terraform Version

```
0.12.26
```

### Use-cases

Create cloud watch error logs for step functions

### Attempted Solutions

Look at documentation

### Proposal

Would be nice to have the logging configuration exposed in aws_sfn_state_machine.

**Comment by apparentlymart** [comment]
Hi @kuhnboy,

This seems like a feature request for the AWS provider rather than for Terraform Core, so you'd need to record it in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) instead.

Issues in this repository are only for bugs and feature requests of the Terraform Core (provider-agnostic) functionality, so I'm going to close this issue. Thanks!
