### ISSUE TITLE
"try" function returns value from errored expression in arguments

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#25572]
### Terraform Version
```
0.12.28
```

### Terraform Configuration Files
Assume a variable of map object type like the following:

```terraform
variable "variable" {
  type = map(object({
    the_foo = string
    the_bar = string
  }))
}
```

We can optionally add unspecified key value pairs into the variable as inputs, like the following:

```terraform
variable = {
  foo = {
    the_foo = "one"
    the_bar = "two"
    the_baz = "three" # unspecified in type
  }
}
```

Assume we now have a variable `foo` without the key `the_baz`. If we try to use `the_baz` in an exported attribute expression like the following, it will error as we expect:

`attribute_argument = resource.resource_name[var.foo.the_baz].id`

> This object does not have an attribute named "the_baz".

All good thus far. Assume we want to check for the existence of the `the_baz` key. We could use the `can` function like the following:

`attribute_argument = can(var.foo.the_baz) ? resource.resource_name[var.foo.the_baz].id : null`

and this will return the exported attribute value when `the_baz` is defined, and `null` when it is undefined. We are still doing well thus far.

However, it would be better to use the `try` function for various reasons outlined in the documentation, and from general experience with best practices. So, given the following expression:

`attribute_argument = try(resource.resource_name[var.foo.the_baz].id, null)`

(to adhere to the template, this is continued in the expected versus actual sections)

### Debug Output
n/a

### Crash Output
n/a

### Expected Behavior
The `try` function should return `null` in the above expression when `the_baz` is missing as a key, which is confirmed by the behavior when it is accessed directly and the use of the `can` function.

### Actual Behavior
The `try` function returns a value from the first argument, which actually errors, and is displayed as `known after apply` for the specific value during a `terraform plan`. This conflicts with the documentation and the behavior illustrated above.

### Steps to Reproduce
`terraform plan`

### Additional Context
n/a

### References
n/a

**Comment by mschuchard** [comment]
This is not a big deal because I can move forward with the `can` function. However, it would be nice to use the `try` function instead as it is better suited for the use case.

**Comment by apparentlymart** [comment]
Hi @mschuchard! Thanks for reporting this

I've labelled this a bug because we've not investigated deeply yet and so can't be sure what exactly is causing this behavior. However, it's possible that this behavior arises from the interaction of two separate intended behaviors -- `try` function's handling of unknown values and Terraform's conservative handling of references to resources during planning -- in which case this might end up being something we could not change without altering the design in a way that would be detrimental to other use-cases.

Once we're able to dig in and reproduce this and understand the root cause we'll see what's best to do here. In the case where the behavior is a consequence of intended behavior, we'll see about updating the documentation to be clearer about it.

Thanks again!

**Comment by mschuchard** [comment]
I need to amend a statement after further investigation.

> attribute_argument = can(var.foo.the_baz) ? resource.resource_name[var.foo.the_baz].id : null

> and this will return the exported attribute value when `the_baz` is defined, and `null` when it is undefined. 

Actually it always returns `null`, as does `try(var.foo.the_baz)`. That may make a difference here, and is now something else I need to go run down.

**Comment by mschuchard** [comment]
Ok I found root cause on this. Given the example above, if I test the structure with an output like:

```terraform
output "foo" {
  value = var.foo
}
```

then the output will appear perfectly as:

```
foo = {
    the_foo = "one"
    the_bar = "two"
    the_baz = "three"
  }
```

However, if I try to access an individual key that is unspecified in nested object type specification (in this example `the_baz`):

```
terraform
output "foo" {
  value = var.foo.the_baz
}
```

then the returned value will be `null` under every circumstance and situation.

**Comment by mschuchard** [comment]
I should also mention another bizarre behavior from this bug. `can(var.foo.the_baz)` returns `true`, but `var.foo.the_baz` returns `null`. That seems off from expected behavior to me.

**Comment by apparentlymart** [comment]
Hi @mschuchard,

Based on your latest update, unfortunately I think this is a consequence of an intentional design decision, though indeed this particular combination of circumstances is confusing.

The root problem here is that you defined the variable as having the following type constraint:

```hcl
  type = map(object({
    the_foo = string
    the_bar = string
  }))
```

Terraform understands this statement as "I want an object with only `the_foo` and `the_bar` attributes". Per [the type conversion rules](https://www.terraform.io/docs/configuration/types.html#conversion-of-complex-types), Terraform will allow the caller to also include additional attributes but will discard them during conversion, because the module hasn't declared that it expects them.

I think perhaps what you wanted here is a way to specify an optional attribute, as discussed in #19898. The details of how exactly that might work are still to be determined, but the key idea is to have a way to state that a module _could_ use an attribute without also making that attribute _required_.

With the current type constraints, the closest we can get is to write out all of the attributes the module will use and then have the caller set them explicitly to `null` if they don't wish to use them:

```hcl
variable "variable" {
  type = map(object({
    the_foo = string
    the_bar = string
    the_baz = string
  }))
}
```

```hcl
variable = {
  foo = {
    the_foo = "one"
    the_bar = "two"
    the_baz = null # explicitly unset, rather than just omitted
  }
}
```

I don't know yet exactly what form optional attributes will take after detailed technical design, but it seems likely to me that it would be interpreted as "if the caller doesn't set this, default it to `null`", which would mean the conversion result would still include a `the_baz` attribute set to `null` but that the caller wouldn't need to explicitly write it down as I showed in the above example.

Do you think that having the ability to declare an optional attribute would meet whatever need you had that led you into this confusing situation in the first place? If so, my instinct would be to close this issue and treat it as a further use-case for #19898, although we could also potentially use this issue to represent finding some way to make the current behavior more explicit in the documentation, to reduce the risk of others getting stuck in this confusing trap in the meantime.

**Comment by mschuchard** [comment]
Yes, that does appear to be an accurate description of what I am seeing. The reason I wanted to avoid the route with specifying the attribute in the object type specification is because the optional attribute would only be used ~5% of the time. Having hundreds of `arg = null` across all the root configs declaring the module seemed messy to me. In some circumstances, empty arrays or empty hashes provide analogous functionality for the inputs.

I am trying to refactor around this with backend logic whenever I can to avoid the optional attributes, but sometimes it makes the code difficult to read. Thanks for the explanation;, and I will certainly close this issue in favor of the FR.
