### ISSUE TITLE
Forced Replacement of Optional Argument in `aws_db_parameter_group` resource

### ISSUE THREAD

**Issue by aradwyr** [hashicorp/terraform#25582]
### Terraform Version
```
Terraform v0.12.23
+ provider.aws v2.68.0
```

### Expected Behavior
No forced replacement of the optional resource
<img width="763" alt="Screen Shot 2020-07-10 at 2 47 24 PM" src="https://user-images.githubusercontent.com/11345614/87500237-dd222400-c610-11ea-87f9-ee45b169eb65.png">

### Additional Context
- The `description` is unable to be changed once set for any AWS parameter group, so if trying to import the DB resource in-tact (i.e. without replacement) then the only current solution is to copy/create new parameter group and make sure that the description is `Managed by Terraform`, otherwise you will not be able to import the resource as-is. This is not ideal because importing now requires you to swap out the parameter groups on existing AWS DB instances, which involves rebooting/downtime. 
- Even removing the optional `description` argument altogether still forced replacement 

The docs don't indicate that `description` forces replacement either:
<img width="1325" alt="Screen Shot 2020-07-14 at 8 43 18 PM" src="https://user-images.githubusercontent.com/11345614/87500986-ced50780-c612-11ea-8a6a-7fe06165e831.png">

### Steps to Reproduce
1. `terraform plan`

### References
[Terraform docs](https://www.terraform.io/docs/providers/aws/r/db_parameter_group.html)

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
