### ISSUE TITLE
Egress rules - Error when creating Security Group - AWS

### ISSUE THREAD

**Issue by amarjothi** [hashicorp/terraform#25589]
AWS Provider - Security groups, When creating egress rules, TERRAFORM, throws error
the specified rule "peer: ::/0, ALL ALLOW" already exists" and fails with exit code 1.

This happens only for outbound rules, and have noticed it is because of all/all ports open rule as a default IN AWS.

As a workaround, when the all/all rule is deleted manually, then the egress rule gets created.

When following the workaround suggested in
<See https://github.com/hashicorp/terraform/pull/2376> still does not work.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
