### ISSUE TITLE
Update documentation dead links

### ISSUE THREAD

**Issue by Porkepix** [hashicorp/terraform#25586]
I was looking at documentation pages within this repository to maybe update some places.
However, it looks like some of these links are dead, eg. all links providers here https://github.com/hashicorp/terraform/blob/master/website/docs/providers/type/major-index.html.markdown

Which also brings this question: is it possible for a user to easily find from the doc where are the source files if they want to provide a patch/report an issue?

**Comment by danieldreier** [comment]
@Porkepix in the live version of the docs (for example at https://www.terraform.io/docs/providers/type/major-index.html), those docs work, so this looks to me like more of an issue around navigating the docs source in github rather than using the live docs via the website. If I'm understanding this concern wrong please let me know and I can send it to our docs folks.

There's an "edit this page" link at the bottom of each docs page, which links to the doc on github.

I'm going to close this because I think I've resolved your questions - feel free to reach out directly at ddreier@hashicorp.com if I've misunderstood.
