### ISSUE TITLE
How to import an AWS rest api with multiple stages?

### ISSUE THREAD

**Issue by socratesx** [hashicorp/terraform#25581]
### Terraform Version

```
Terraform v0.12.28
+ provider.aws v2.61.0
```
### Actual Behavior

Let's say that I want to import to terraform an already working api in AWS API Gateway that has two stages, A and B. The logic says that I would use the aws_api_gateway_rest_api resource with the body attribute and an export from API gateway. 

The problem is that each stage has a different export swagger file. Is any workaround that would allow me to create a configuration to provision that API with all its stages and then to import them all using terraform import?

### Suggestion

The body attribute should be an attribute of aws_api_gateway_deployment or aws_api_gateway_stage resource. This would allow to use different swagger files per stage as per the example use case.

**Comment by apparentlymart** [comment]
Hi @socratesx,

This seems like a feature request for the AWS provider rather than for Terraform Core. It looks like there's already an existing general issue for API gateway import functionality in #558, so I'm not sure if it's better to add your use-case to that issue (where some folks are already talking about `aws_api_gateway_deployment` import functionality) or to open a new issue that refers to that one, but I would suggest doing one of those two things in order to send this request to the team that maintains the AWS provider. (If you're not sure either, I _think_ I would lean towards a new issue, because it sounds like you're proposing adding new functionality to `aws_api_gateway_deployment` in addition to supporting import for it.)

Only the Terraform Core (provider-agnostic) functionality is developed in this repository, so there's nothing we could change here that would directly serve your use-case of importing different OpenAPI definitions into each stage of a single API gateway. For that reason, I'm going to close this issue. Thanks!

**Comment by socratesx** [comment]
Thanks for your reply. I will open the issue to the related provider.
