### ISSUE TITLE
aws_eip_association resource ignores allow_reassociation argument when it's set to false

### ISSUE THREAD

**Issue by clausa20** [hashicorp/terraform#25580]
A bug was created 3 years ago, but closed automatically and never attended.
You can see details on it: https://github.com/hashicorp/terraform/issues/14553
I see the same problem in version v0.12.16

**Comment by apparentlymart** [comment]
Hi @clausa20,

Our bot closed this the issue you refer to because at that point the AWS provider code moved into [its own separate repository](https://github.com/terraform-providers/terraform-provider-aws), and so the issue was recreated as terraform-providers/terraform-provider-aws#777.

It looks like the new issue was closed due to becoming stale, and the automatic closing message asks that you open a new issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) if you see a similar result. If you do open a new issue, please be sure to complete the AWS provider team's bug report template fully because the original issue was from three years ago and so the reproduction information there is unlikely to still be usable.

The issues in this repository are only for bugs and feature requests in Terraform Core itself, so I'm going to close this. Thanks!
