### ISSUE TITLE
conditionals break interpolated vars

### ISSUE THREAD

**Issue by cloudbeds-dan-baker** [hashicorp/terraform#25592]
### Terraform Version

```
0.12.28 
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

`final_snapshot_identifier = var.skip_final_snapshot == false ? "${var.db_instance_name}-final" : ""`
should set the variable to the instance_name-final if the skip_final_snapshot false
`final_snapshot_identifier = "${var.db_instance_name}-final"`
works as expected

### Actual Behavior

Instead it throws an error
```
Error: only alphanumeric characters and hyphens allowed in "final_snapshot_identifier"

  on main.tf line 39, in resource "aws_db_instance" "db":
  39: resource "aws_db_instance" "db" {
```
### Steps to Reproduce

This occurred within an aws_rds_resource, but the behavior is consistent in other resources.

**Comment by danieldreier** [comment]
Hi @cloudbeds-dan-baker - I've taken a quick look at this, and based on the information you've provided, I don't immediately see evidence of a bug in Terraform core. This looks to me like a syntax issue rather than a bug. It's possible that there's a defect, but there's not quite enough evidence here for me to treat it as one. There are two possible next steps for you:

1.  I think your best bet is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

2. Alternatively, if you're confident that this is a bug, please provide a copy-pasteable example for reproducing this issue, ideally using a null resource rather than a real provider so that we need fewer test fixtures to reproduce it. If this is indeed a bug I would really appreciate help in coming up with a clear reproduction case.

Based on my work so far, I recommend you take this to the community forum for assistance in troubleshooting, but I'm totally open to the possibility I've misunderstood your report and that it's a bug.

**Comment by alisdair** [comment]
I was able to reproduce this error with the following configuration:

```hcl
provider "aws" {
  region = "us-east-1"
}

variable "db_instance_name" {
  type = string
  default = "mydb"
}

variable "skip_final_snapshot" {
  type = bool
  default = true
}

resource "aws_db_instance" "db" {
  allocated_storage         = 20
  engine                    = "mysql"
  instance_class            = "db.t2.micro"
  name                      = "mydb"
  username                  = "foo"
  password                  = "foobarbaz"
  final_snapshot_identifier = var.skip_final_snapshot ? "${var.db_instance_name}-final" : ""
}
```

Running `terraform plan` succeeds, but running `terraform plan -var skip_final_snapshot=false` causes the error as reported.

This is caused by the use of an empty string as the fallback value for the `final_snapshot_identifier` argument. An empty string is not the same as not passing a value, which I think is your intention. Using `null` as the fallback value is the correct way to optionally set this argument:

```hcl
  final_snapshot_identifier = var.skip_final_snapshot ? "${var.db_instance_name}-final" : null
```

With this change, `terraform plan -var skip_final_snapshot=false` succeeds.

If this is not the underlying problem, I second Daniel's request to post in [the Terraform community form](https://discuss.hashicorp.com/c/terraform-core/27) for help, unless you're sure it's a Terraform bug.

Hope this helps!
