### ISSUE TITLE
EntityAlreadyExists on Terraform managed resources

### ISSUE THREAD

**Issue by axc450** [hashicorp/terraform#25614]
I am trying to create some AWS IAM users however I am facing the "EntityAlreadyExists" error. Usually this occurs if you mess with users outside of Terraform, however this is not the case here. I have quite a complex set of Terraform modules, but have essentially narrowed it down to the below. I simply want to create the user **if they do not exist already**. Are there any tricks I can perform to allow this?

### Terraform Version
```
v0.13.0-beta3
```

### Terraform Configuration Files
```terraform
resource "aws_iam_user" "user" {
    name = "user"
}

resource "aws_iam_user" "user2" {
    name = "user"
}
```

### Expected Behavior
Terraform should know that "user" has been created and is managed, and should perform no action on the 2nd resource.
I would expect the 2 resources above to translate to "Ensure a user exists called user. Also ensure a user exists called user".
`terraform plan` should not list "2 to add" and `terraform apply` should not try to create it twice.

### Actual Behavior
```
Error: Error creating IAM User user: EntityAlreadyExists: User with name user already exists.
```

### Additional Context
I have a reusable Terraform module that does various things, one of them being to create a user. Sometimes, this module will be called with the same user argument which is what is leading to this problem.
If there is no workaround, is there a way to just ignore the error? I want to avoid having to create users manually.

**Comment by danieldreier** [comment]
@axc450 Terraform core has no way of knowing that these two resources actually reference the same underlying AWS resource. I understand your use case, and am empathetic to this need, but Terraform core just doesn't have enough information available to de-duplicate these resources.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. I think the community forum is a better place to ask other folks how they're organizing their code to avoid a duplicate resource like this.

**Comment by bflad** [comment]
Related:
* https://github.com/hashicorp/terraform/issues/22094
* https://github.com/hashicorp/terraform-plugin-sdk/issues/224
