### ISSUE TITLE
Variable validation should allow use of other data sources

### ISSUE THREAD

**Issue by mbamber** [hashicorp/terraform#25624]
### Use-cases
It is sometimes useful to use other data sources in order to perform variable validation. In particular, I would like to check that `data.aws_caller_identity.current.account_id` is not equal to a specific value if the variable is not defined:

```hcl
variable "v" {
  type = object({
    id = string
  })
  default = null

  validation {
    condition = var.namespace == null ? can(regex("01234567890", data.aws_caller_identity.current.account_id)) : ""
    error_message = "If v is not supplied then AWS account used in provider must be either 01234567890."
  }
}
```

### References
#23794

**Comment by apparentlymart** [comment]
Hi @mbamber! Thanks for sharing this use-case.

I expect there are other related use-cases where this would not be true, but I just wanted to note that the AWS provider in particular already has a first-class feature for controlling which accounts can be used with it (the `allowed_account_ids` argument in the provider configuration), which is how this particular sort of rule is typically implemented today.

Custom variable validation is specifically aimed at static validation of arguments -- it's equivalent to provider-level validation in that it's not allowed to access anything except the configuration itself, because these run in `terraform validate` -- so a solution to this use-case is unlikely to look exactly like you showed here but we can consider this issue to represent the use-case of making assertions dynamically against data sources to be checked either during `terraform plan` or `terraform apply`, whatever specific syntax that might end up using.

**Comment by apparentlymart** [comment]
I didn't notice this at the time, but https://github.com/hashicorp/terraform/issues/28060 later duplicated this one.

Since there's now more discussion and (marginally) more upvotes on the other one I'm going to close this one as the duplicate, despite the ordering being the opposite. If you voted for this one and not the other one then you might want to transfer your :+1: reaction into the opening comment of the other issue so we can properly gauge that feedback. Thanks!
