### ISSUE TITLE
I am not able to execute the terraform scripts without internet, is it possible to execute terraform scripts without internet access? if possible could you please help me here

### ISSUE THREAD

**Issue by srinivasiyerb** [hashicorp/terraform#25638]
### Terraform Version

```
Terraform v0.12.28
+ provider.aws v2.70.0

...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
