### ISSUE TITLE
google provider account_file does not work with atlas

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#2565]
In the current Google provider you authenticate to the Google api by setting account_file to point to the json file you can download from Google console. Of course you don't want this json file in version control from security perspective. Because of this there seems no easy way to get this to work with Atlas.

Wouldn't it make more sense to alternatively allow the provider to set the following fields which can then be set as variables in Atlas?

private_key_id
private_key
client_email
client_id
type

**Comment by sparkprime** [comment]
In fact all you need is client_email and private_key

**Comment by phinze** [comment]
Thanks for the report! We're addressing this over in https://github.com/hashicorp/terraform/pull/2839 - for now by allowing the `account_file` to be specified as contents rather than as a path.

We're still just keeping it as JSON rather than splitting the individual fields out. Keep an eye on #2839 for details! :+1:
