### ISSUE TITLE
Improve documentation layout to make it lisible(especially for nested block)

### ISSUE THREAD

**Issue by kinwolfqc** [hashicorp/terraform#25659]
I recently opened an issue with azurerm (https://github.com/terraform-providers/terraform-provider-azurerm/issues/7828) because of an error about the certificate block.

It turned out that the problem was simply that the "certificate" block needed to be nested inside a "secret" block and a good soul pointed me to the doc for that.  Also, the secret block required the vault id where the certificate was located.

The problem is, reading the doc, it is **impossible** to know the certificate block should be nested inside a secret block OR that the secret block required the vault id.  Was it not for ArcturusZhang reply, we would still be stuck trying to figure out why it wasn't working.   I would go as far to double dare anyone to take a look at the doc [here](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html#secret) and manage to figure that "certificate" goes inside "secret"

This has been a problem for us here since the first day that we started to explore and use terraform.  The Terraform doc layout makes it almost impossible to know what goes where unless we are lucky enough to have an example to show it to us.

So, it would be nice if the layout could be redone to make the doc usable?

How do people currently manage to know what goes where when things are nested or required attributes goes unlisted?  Do they go read the source code?

**Comment by apparentlymart** [comment]
Hi @kinwolfqc! Thanks for this feedback.

I do agree with what you say here that the typical way that provider docs are structured doesn't lend itself well to resource types that have many nested blocks, especially when some of those nested blocks appear inside other nested blocks.

Unfortunately, the team that works in this repository is the Terraform Core team and we don't have any direct involvement in how Terraform provider documentation is written, and so tracking this issue here is not likely to make it visible to those who could take action based on it. The team that would be most equipped to drive a solution here is the same team that maintains the Terraform plugin SDK, because they generally look after the tools and practices shared across providers, but tracking this request in the SDK repository itself also doesn't really feel right.

@paultyng, where do you think would be the best home for feedback like this, on conventions and standards that apply across providers?

**Comment by paultyng** [comment]
@kinwolfqc the best place to discuss this would probably be https://github.com/hashicorp/terraform-plugin-docs which is where we are working on new documentation generation. 

Each provider right now maintains their own static copy of their docs so there isn't an easy way to affect change across all of them until we standardize on the generator.
