### ISSUE TITLE
TF 0.12.9 & 0.12.7 "An argument named "experiments" is not expected here" in versions.tf 

### ISSUE THREAD

**Issue by hilarykitz** [hashicorp/terraform#25669]
### Terraform Version

```
0.12.9
```

### Terraform Configuration Files

```
terraform {
  required_version = ">= 0.12.9"
  experiments = [variable_validation]
}
```

### Debug Output

```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported argument

  on versions.tf line 3, in terraform:
   3:   experiments = [variable_validation]

An argument named "experiments" is not expected here.
```

### Expected Behavior

From every doc I've read, this should be the place to declare experimental features, and shoud enable those within the variable_validation experiment

### Actual Behavior

Toys are thrown from pram

### Steps to Reproduce

1. `terraform init` OR `terraform validate`

### Additional Context

TF seems to pick up on this implementation fine if I upgrade to 0.13, where is gives the expected "experiment concluded" message. HeLp!

**Comment by jbardin** [comment]
Hi @hilarykitz,

The variable validation experiment was added in `v0.12.20`, and the current release version is `v0.12.29`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
