### ISSUE TITLE
Digital Ocean net/http: TLS handshake  when used in conjunction with AWS providers

### ISSUE THREAD

**Issue by fritzstauff** [hashicorp/terraform#25677]
### Terraform Version

```
Terraform v0.12.29
+ provider.aws v2.61.0
+ provider.digitalocean v1.22.0
+ provider.postgresql v1.6.0
```

### Terraform Configuration Files

```terraform
cat main.tf

# Create Dev VPC
module "do-dev" {
 source = "./do-dev"
}

# Create Dev VPC
module "dev" {
 source = "./dev"
}

cat foo-dev/main.tf
# Configure the DigitalOcean Provider
provider "digitalocean" {
}


                                                                                  
cat dev/main.tf                  
module "aws-vpc" {
  source = "./vpc"
  region = "us-west-2"
  vpc-name = "foo-dev"
  cidr-block = "10.100.0.0/16"
}


### Set VPC
resource "digitalocean_vpc" "foo-do-dev" {
  name     = "foo-dev"
  region   = "sfo1"
  ip_range = "10.100.0.0/16"
}


```

### Debug Output

encrypted debug file
https://www.dropbox.com/s/rwvgaspvt94dpzh/log.txt.gpg?dl=0

### Crash Output
None

### Expected Behavior

terraform plan returns okay

### Actual Behavior

```
module.dev.module.aurora_ui_bff.aws_rds_cluster_instance.cluster_instances[1]: Refreshing state... [id=ui-bff-cluster-dev-1]
module.dev.module.aurora_ui_bff.aws_rds_cluster_instance.cluster_instances[0]: Refreshing state... [id=ui-bff-cluster-dev-0]

Error: Error reading VPC: Get "https://api.digitalocean.com/v2/vpcs/e14918f3-9092-4c47-84c4-f5cbc2e0610b": net/http: TLS handshake timeout



Error: Error retrieving SSH key: Get "https://api.digitalocean.com/v2/account/keys/27927707": net/http: TLS handshake timeout



Error: Error retrieving SSH key: Get "https://api.digitalocean.com/v2/account/keys/27497706": net/http: TLS handshake timeout
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context
Using Aws provider and DigitalOcean providers as submodules for multi-site deployment. The Aws stuff has been in place and working for months. The DigitalOcean sub module runs fine if I only execute it ```terraform plan -target=module.do-dev```. When I attempt to run the full plan together I run into 'net/http: TLS handshake timeout' on the Digialocean endpoints.

**Comment by apparentlymart** [comment]
Hi @fritzstauff!

This message seems to be returned from the DigitalOcean provider rather than from Terraform itself, so unfortunately I don't think there's anything we could change in this repository to improve your situation. Issues in this repository are only for bug reports and feature requests for the Terraform Core (provider-agnostic) behavior, so I'm going to close this issue.

Since it's not clear whether this is a problem with the AWS provider or with the DigitalOcean provider, I might suggest starting by creating a new topic in [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers/31) to see if any of the participants there have experience with this strange interaction between the AWS and DigitalOcean providers. If you conclude that it's a bug in one of the two providers then you could then open an issue in either [the DigitalOcean provider repository](https://github.com/digitalocean/terraform-provider-digitalocean) or in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws). Thanks!
