### ISSUE TITLE
Azure- Provider Terraform

### ISSUE THREAD

**Issue by Lahkurb** [hashicorp/terraform#25670]
I have created multiple key vault secrets in the Azure portal and trying pass them in terraform Data.tf. But i am not sure how to pass multiple secrets and refer in the main.tf. Can someone help on this. My requirement is to pass multiple values in the Name attribute and refer in Main.tf. Here is the code, 

data.tf

data "azurerm_key_vault" "key_vault" {
    name                = "test-key-vault-cts"
    resource_group_name = "gcdmvrlyprd03-30cf06a8"
}

data "azurerm_key_vault_secret" "admin_password" {
    name         = "admin-password"
    key_vault_id = data.azurerm_key_vault.key_vault.id
}

Main.tf

module "location_us-west" {
  source = "./Modules"

  web_server_location      = "westus2"
  web_server_rg            = "${var.web_server_rg}-us-west"
  resource_prefix          = "${var.resource_prefix}-us-west"
  web_server_address_space = "10.0.0.0/22"
  #web_server_address_prefix = "10.0.1.0/24"
  web_server_name  = var.web_server_name
  environment      = var.environment
  size             = var.vm_size
  admin_user       = var.user
  admin_password   = data.azurerm_key_vault_secret.admin_password.value
  web_server_count = var.web_server_count
  web_server_subnets = {
    "web-server"         = "10.0.1.0/24"
    "AzureBastionSubnet" = "10.0.2.0/24"
  }
}

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
