### ISSUE TITLE
Terraform- provider Azure

### ISSUE THREAD

**Issue by Lahkurb** [hashicorp/terraform#25671]
I have created multiple key vault secrets in the Azure portal and trying pass them in terraform -> Data.tf. I am getting error passing the attribute as an index and refer it in the main.tf.  I am passing multiple secret names in the Name attribute and refer in Main.tf. Here is the code and the error,

Error: Unsupported argument

  on data.tf line 8, in data "azurerm_key_vault_secret" "admin_password":
   8:     name1        = "admin-password1"

An argument named "name1" is not expected here
-------------------------
data "azurerm_key_vault" "key_vault" {
    name                = "test-key-vault-cts"
    resource_group_name = "gcdmvrlyprd03-30cf06a8"
}

data "azurerm_key_vault_secret" "admin_password" {
    name         = ["admin-password","admin-password1"]
    key_vault_id = data.azurerm_key_vault.key_vault.id
}
-------------------
module "location_us-west" {
  source = "./Modules"

  web_server_location      = "westus2"
  web_server_rg            = "${var.web_server_rg}-us-west"
  resource_prefix          = "${var.resource_prefix}-us-west"
  web_server_address_space = "10.0.0.0/22"
  #web_server_address_prefix = "10.0.1.0/24"
  web_server_name  = var.web_server_name
  environment      = var.environment
  size             = var.vm_size
  admin_user       = var.user
  admin_password   = data.azurerm_key_vault_secret.admin_password[admin-password1].value
  web_server_count = var.web_server_count
  web_server_subnets = {
    "web-server"         = "10.0.1.0/24"
    "AzureBastionSubnet" = "10.0.2.0/24"
  }
}

**Comment by apparentlymart** [comment]
Hi @Lahkurb,

This seems like an Azure provider question rather than a request for Terraform Core. This repository is only for bug reports and feature requests for the provider-agnostic parts of Terraform, so I'm going to close this.

I'd suggest posting your question in [the Azure provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34), where the participants are much more familiar with Azure and the Azure provider than the Terraform Core maintainers who monitor these GitHub issues. Thanks!
