### ISSUE TITLE
 Terraform Cloud: Implementing of Directories for Workspaces

### ISSUE THREAD

**Issue by AleksandrTitov** [hashicorp/terraform#25688]
### Proposal
During the work with Terraform Cloud, the number of workspaces consistently is increased and you get a huge list of Workspaces, uses the filters isn't convenient in some cases.

So it'll be good to add the possibility to logically separate the workspaces to the group (depends on goals, environments, or whatever) using directories.

**Comment by apparentlymart** [comment]
Hi @AleksandrTitov! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
