### ISSUE TITLE
someting wrong with create vms( timeout waiting for an available IP address)

### ISSUE THREAD

**Issue by zhongc-jiang** [hashicorp/terraform#25696]
I can't find any way to set the IPV4 address, I want to know if there is a problem with my parameter or if TerraForm will be automatically configured.Can VMware automatically configure Linux using Kickstart like Packer? I can find the created VMS in the vSphere Client every time I run, but the terraForm run window has an error.

 //Connect to VMware vSphere vCenter
provider "vsphere" {
  user           = var.vsphere-user
  password       = var.vsphere-password
  vsphere_server = var.vsphere-vcenter

  // If you have a self-signed cert
  allow_unverified_ssl = var.vsphere-unverified-ssl
}

// Define VMware vSphere
data "vsphere_datacenter" "dc" {
  name = var.vsphere-datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vm-datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere-cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vm-network
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "resource_pool" {
  name        = var.vm-resource-pool
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

// get CST Time.      
locals {
   time = "${formatdate("YYYY-MM-DD hh:mm",timeadd(timestamp(),"8h"))}"
}

// Create VMs 
resource "vsphere_virtual_machine" "vm" {
  count = var.vm-count
  name             = "${var.vm-name}-${count.index + 1}"
  resource_pool_id = data.vsphere_resource_pool.resource_pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  annotation       = "${var.vm-annotation}\nVM-Application:${var.vm-application}\nVM-Owner:${var.vm-owner}\nVM-CreateDate:${local.time}"
  num_cpus = var.vm-cpu
  memory   = var.vm-ram
  guest_id = var.vm-guest-id
  
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  
  disk {
    label = "${var.vm-name}-${count.index + 1}-disk"
    size  = var.vm-disk-size
  }

  cdrom {
    datastore_id = data.vsphere_datastore.datastore.id
    path         = "ISO/CentOS-6.8-x86_64-bin-DVD1.iso"
  }
}

==================================================================================
Error：

Error: timeout waiting for an available IP address

  on main.tf line 54, in resource "vsphere_virtual_machine" "vm":
  54: resource "vsphere_virtual_machine" "vm" {

Error: timeout waiting for an available IP address

  on main.tf line 54, in resource "vsphere_virtual_machine" "vm":
  54: resource "vsphere_virtual_machine" "vm" {

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

I think that what you're asking about how to run a script on init to set an IP address. Take a look at the [CloudInit](https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs) provider, and if that doesn't fit your needs, [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) and [terraform core forum](https://discuss.hashicorp.com/c/terraform-core) are the right places to ask for this kind of guidance. I have used CloudInit in the past for this kind of boot-time use case so I think that will work for you.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though this is a valid question for the community forums, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
