### ISSUE TITLE
Unexpected status code:400 while creating signalfx_dashboard_group

### ISSUE THREAD

**Issue by andreamarinaro** [hashicorp/terraform#25698]
### Terraform Version

```
Terraform v0.12.29
```

### Terraform Configuration Files

```
data "aws_ssm_parameter" "dashboard_token" {
  name = "/prd/signalfx_dashboard_token"
  with_decryption = true
}

resource "signalfx_dashboard_group" "SLI" {
  name        = "SLI/SLO dashboard group"
  description = "Dashboard group for SLI/SLO metrics"
  authorized_writer_users = ["data.aws_ssm_parameter.dashboard_token.value"]
}
```

### Expected Behavior

```
Resource created
```
### Actual Behavior

```
signalfx_dashboard_group.SLI: Creating...
Error: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Failed to deserialize payload at: sf.domain.group.DashboardGroup[\"authorizedWriters\"]->sf.domain.AuthorizedWriters[\"users\"]->java.util.HashSet[0]"
}
```

**Comment by alisdair** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the SignalFx Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the SignalFx provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by alisdair** [comment]
Ah, I see that the SignalFx provider has recently been rehomed here: [splunk-terraform/terraform-provider-signalfx](https://github.com/splunk-terraform/terraform-provider-signalfx). I can't move this issue upstream for you, so please re-report it over there. Thanks again!

**Comment by andreamarinaro** [comment]
> 
> 
> Ah, I see that the SignalFx provider has recently been rehomed here: [splunk-terraform/terraform-provider-signalfx](https://github.com/splunk-terraform/terraform-provider-signalfx). I can't move this issue upstream for you, so please re-report it over there. Thanks again!

Done, thanks!
