### ISSUE TITLE
`required_version` constraint ignored

### ISSUE THREAD

**Issue by c10l** [hashicorp/terraform#25703]
### Terraform Version

```
$ terraform version
Terraform v0.12.29
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "0.12.29"
}

provider "kubernetes" {
  required_version = "~> 1.11"
}
```

### Debug Output

https://gist.github.com/c10l/afab8f1fd10c921dbfdf6fdd626514ea#file-debug

### Expected Behavior

`kubernetes` provider version installed should be `>= 1.11.0` and `< 1.12.0`.

### Actual Behavior

`kubernetes` provider version `1.12.0` was installed.

### Steps to Reproduce

```
terraform init
```

**Comment by jbardin** [comment]
Hi @c10l 

The old meta attribute for specifying a provider version is `version`, not `required_version`.
The preferred way now (and only way in the cases of certain module configurations) is to use `required_providers` within the `terraform` block https://www.terraform.io/docs/configuration/providers.html#provider-versions

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by c10l** [comment]
Thank you for the correction.

I did try both `required_version` and `version`, and neither work.

`version` is parsed during a `plan` when it's run before initalizing, but not on the actual `init` (note how `plan` acknowledges the version constraint whereas `init` just installs the latest version):

```
$ terraform plan

Error: Could not satisfy plugin requirements


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".



Error: provider.kubernetes: no suitable version installed
  version requirements: "~> 1.11"
  versions installed: none


$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.12.0...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

The other problem is that this issue was caught after a migration from `0.11` to `0.12`, and neither the [Upgrading to Terraform v0.12](https://www.terraform.io/upgrade-guides/0-12.html) document nor any of the Terraform runs, including running `0.12checklist` on `0.11.14` and `0.12upgrade` on `0.12.29` mentioned this change.

From where I'm standing this is potentially multiple software bugs and at least one documentation bug.

**Comment by jbardin** [comment]
It appears the confusion here is that you have specified `~> 1.11` as the version constraint, which is equivalent to `>= 1.11.0, < 2.0.0`. The shorthand for `>= 1.11.0, < 1.12.0` is `~> 1.11.0` indicating that the pessimistic operator is applying to the patch version. I also verified that this behavior is consistent between 0.11, 0.12 and 0.13.

**Comment by c10l** [comment]
Ah, that makes sense. I had somehow assumed that the constraint was always applied to the minor version.

I guess I should RTFM more carefully.

Thanks for your help!
