### ISSUE TITLE
terraform 013upgrade does not copy version attribute

### ISSUE THREAD

**Issue by craigbryson** [hashicorp/terraform#25714]
### Current Terraform Version
0.13-rc1

### Use-cases
Suppose you have a provider block:

provider "foo" {
version = "1.0"
}

The terraform 013upgrade command creates a new versions.tf file with a required_providers block:

  required_providers {
    foo = {
      source = "hashicorp/foo"
    }

The version attribute of foo is not copied, is there a reason for this since it seems that required_providers is now the preferred place to specify versions?

**Comment by alisdair** [comment]
Thanks for reporting this! You're correct that the version constraint should be moved to the `required_providers` block if possible, and we would advise doing that manually.

Not doing so automatically was an intentional decision made in order to keep the 0.13upgrade command as simple as possible. We want to rewrite as little of your configuration as necessary in order to make it 0.13 compatible, and moving the version constraint would necessitate rewriting (and possibly removing) the `provider` block it came from. This would make the command significantly more complex.

At this time we don't intend to change the functionality of the 0.13upgrade command in this direction, so I'm marking this issue closed for now.
