### ISSUE TITLE
Better (any?) documentation for retrieving values from set data type

### ISSUE THREAD

**Issue by kevinburke1** [hashicorp/terraform#25717]
The terraform-aws provider started using `sets` as output values in version 3, instead of lists or maps, so last night was my first experience using them. I have a set that has a single value in it. I would expect to be able to access this value using a key, or the `[0]` index, or *something*. Instead, the only documentation resources I can see reference accessing the values in sets by iterating over all of them using the `for_each` operator. 

This is awkward in some places, like here (just as an example, don't worry about what this is actually doing)

```hcl
resource "aws_route53_record" "root_validation" {
  count   = (var.https == "" || var.has_lb == false) ? 0 : 1
  name    = aws_acm_certificate.root[0].domain_validation_options.0.resource_record_name
  type    = aws_acm_certificate.root[0].domain_validation_options.0.resource_record_type
  zone_id = var.route53_zone_id == "" ? aws_route53_zone.domain[0].zone_id : var.route53_zone_id
  records = [aws_acm_certificate.root[0].domain_validation_options.0.resource_record_value]
  ttl     = 60
}
```

I tried adding a `for_each` field but this interacts poorly with the `count` field - you can't have both - so I ended up doing this:

```hcl
resource "aws_route53_record" "root_validation" {
  count = (var.https == "" || var.has_lb == false) ? 0 : 1

  name    = tolist(aws_acm_certificate.root[0].domain_validation_options)[0].resource_record_name
  type    = tolist(aws_acm_certificate.root[0].domain_validation_options)[0].resource_record_type
  zone_id = var.route53_zone_id == "" ? aws_route53_zone.domain[0].zone_id : var.route53_zone_id
  records = [tolist(aws_acm_certificate.root[0].domain_validation_options)[0].resource_record_value]
  ttl     = 60
}
```

Which also feels awkward.

I tried searching the Terraform documentation for information about the `set` datatype but found it lacking, particularly for how to get values out. There is this page, which explains that sets are unordered lists with no duplicates, but does not explain how to get values out of a set. https://www.terraform.io/docs/configuration/types.html

Contrast this with the list documentation - if I search Google for "terraform retrieve value from list" the answer is in both the first and third paragraphs of the top search result.

It would be useful to explain (if this is true? I don't know) that the only way to get values out of a set is to use the `for_each` operator and explain how to convert existing resources that might have a `count` field like the one I have above.

**Comment by kevinburkemeter** [comment]
Maybe another way to look at my question is, it seems like the set abstraction makes it difficult to do two things that used to be easy - condition a resource existence on a variable (in the `count` above), and to get the one item in a list _out_ of that list, and I'm struggling to figure out the right ways to do that now with the new abstraction.

**Comment by apparentlymart** [comment]
Hi @kevinburkemeter,

This change of type was a design tradeoff made by the AWS provider team, but based on [what they wrote in the upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate) it seems like they were intending this as a response to the problem that there can potentially be more than one "validation option" _and_ the remote API doesn't consider them to be ordered, and so referring to the "zeroth" one isn't a stable/meaningful idea.

The upgrade guide also includes an example pattern for interacting with the new interface, which matches with some initial ideas I had after first reviewing your issue here. Here's an attempt at implementing the guidance from the upgrade guide in conjunction with what you showed in your comment (I'm not really familiar with this particular resource, so I'm working completely from the AWS provider docs here):

```hcl
resource "aws_route53_record" "root_validation" {
  for_each = (var.https == "" || var.has_lb == false) ? {} : {
    for dvo in aws_acm_certificate.root[0].domain_validation_options : dvo.domain_name => dvo
  }

  allow_overwrite = true
  name            = each.value.resource_record_name
  records         = [each.value.resource_record_value]
  ttl             = 60
  type            = each.value.resource_record_type
  zone_id         = data.aws_route53_zone.public_root_domain.zone_id
}

resource "aws_acm_certificate_validation" "root_validation" {
  certificate_arn         = aws_acm_certificate.root[0].arn
  validation_record_fqdns = [for record in aws_route53_record.root_validation : record.fqdn]
}
```

This would, assuming I'm understanding the `aws_acm_certificate` docs correctly, cause there to be one instance of `aws_route53_record` per element of the `domain_validation_options` set, which seems to follow how ACM certificate validation is intended to work.

As far as I can tell, the provider team made this design decision so that the provider's abstraction would match better with the remote system's abstraction, and so I'm not really sure how to generalize the above advice to _all_ uses of sets: any time a provider team decides to use a set they are presumably doing so because that's the best fit for the design of the remote system, part of which includes there being no meaningful concept of "the first element" (because the items aren't ordered). When a provider uses a set to represent an unordered collection then, the typical intent is to do something with _the entire set_, rather than individual items from the set, but exactly what is intended will depend on the situation.

It does seems like there is an opportunity here to factor out this particular combination of `aws_acm_certificate`+`aws_route53_record`+`aws_acm_certificate_validation` into a shared module in the Terraform Registry, since I assume that it's a pretty common situation to use Route53 to host your ACM validation records but the configuration for achieving that seems to be almost entirely boilerplate, aside from the domain name(s) and the zone id:

```hcl
module "certificate" {
  source = "some-organization/acm-certificate-with-route53/aws" # just a hypothetical; doesn't actually exist
  count  = (var.https == "" || var.has_lb == false) ? 0 : 1

  route53_zone_id = aws_route53_record.www.zone_id
  domain_name     = aws_route53_record.www.name
  subject_alternative_names = [
    aws_route53_record.www.name,
    aws_route53_zone.main.name,
  ]
}
```

**Comment by loganpowell** [comment]
Hi, sorry to highjack this thread, but I have a related question (albeit using the Terraform JSON syntax). When trying to access a set in JSON, I get this error:

```sh
Elements of a set are identified only by their value and don't have any separate index or key to select with, so it's only possible to perform operations across all elements of the set.
```

Here's the JSON that's trying to access it:
```json
{ 
  resource: {             
         "subdomains_record_valid_test1": { 
                "name": "${resource.aws_acm_certificate.subdomains_cert_test1.domain_validation_options[0].resource_record_name}", 
                "type": "${resource.aws_acm_certificate.subdomains_cert_test1.domain_validation_options[0].resource_record_type}", 
                "zone_id": "${data.aws_route53_zone.subdomains_zone.zone_id}", 
                "ttl": 60, 
                "allow_overwrite": true, 
                "records": [${resource.aws_acm_certificate.subdomains_cert_test1.domain_validation_options[0].resource_record_value}"] 
            } 
        }
}
```
I've looked through the [docs](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#conversion-of-complex-types) as well as the reference from @kevinburke1, but it's pretty terse and there's not much to speak of specifically for the JSON syntax, for which I found only this:

> The translation of attribute and output values is the same intuitive mapping from HCL types to JSON types 
> used by Terraform's [jsonencode](https://developer.hashicorp.com/terraform/language/functions/jsonencode) 
> function. This mapping does lose some information: lists, sets, and tuples all lower to JSON arrays while 
> maps and objects both lower to JSON objects. Unknown values and null values are both treated as absent or null.

Any pointers to how I might break into a set via the JSON syntax would be very much appreciated 🙏

**Comment by apparentlymart** [comment]
Hi @loganpowell,

If what you are asking is how to write something like the example I showed above using the JSON version of the Terraform language, that seems like something better suited to [the Terraform community forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Comment by loganpowell** [comment]
@apparentlymart will do. Thank you!

**Comment by loganpowell** [comment]
Ok, I got it working with:
```json
{ 
  "resource": {
      "subdomains_record_valid_test1": {
          "name": "${tolist(resource.aws_acm_certificate.subdomains_cert_test1.domain_validation_options)[0].resource_record_name}",
          "type": "${tolist(resource.aws_acm_certificate.subdomains_cert_test1.domain_validation_options)[0].resource_record_type}",
          "zone_id": "${data.aws_route53_zone.subdomains_zone.zone_id}",
          "ttl": 60,
          "allow_overwrite": true,
          "records":  ["${tolist(resource.aws_acm_certificate.subdomains_cert_test1.domain_validation_options)[0].resource_record_value}"]
         }
    }
}
```

**Comment by crw** [comment]
There does not appear to be a documentation change being requested here after https://github.com/hashicorp/terraform/issues/25717#issuecomment-683975333 -- closing this issue, but will re-open if I missed the outstanding request.
