### ISSUE TITLE
Documentation doesn't show how to support multiple providers in JSON .tf.json format

### ISSUE THREAD

**Issue by lancejpollard** [hashicorp/terraform#25712]
Documentation shows this:

```json
{
  "provider": {
    "aws": {
      "region": "us-west-1"
    }
  }
}
```

However, you are only capable of adding one key this way. In terraform script, it looks like this with aliases:

```
provider "aws" {
  region = "...",
  alias = "one"
}

provider "aws" {
  region = "...",
  alias = "two"
}
```

And you use it like `aws.two` or whatever.

But in JSON that would be like this:

```json
{
  "aws": {
    "region": "...",
    "alias": "one"
  },
  "aws": {
    "region": "...",
    "alias": "two"
  }
}
```

Which doesn't make any sense and is invalid JSON. Is there a way to do this?

**Comment by alisdair** [comment]
Hello! We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
