### ISSUE TITLE
Terraform cannot create records when migrating Cloudflare records that was created via terraform locally to terraform cloud

### ISSUE THREAD

**Issue by pknomad** [hashicorp/terraform#25728]
### Terraform Version

```
v.0.12.29
provider.cloudflare v2.9.0
```

### Terraform Configuration Files

```terraform
resource "cloudflare_record" "mx-10" {
  zone_id  = var.silph_dev_zone_id
  name     = "@"
  type     = "MX"
  ttl      = 3600
  proxied  = false
  priority = 10
  value    = "aspmx1.migadu.com"
}
```

### Debug Output

```
Error: Failed to create record: error from makeRequest: HTTP status 400: content "{\"result\":null,\"success\":false,\"errors\":[{\"code\":81057,\"message\":\"The record already exists.\"}],\"messages\":[]}"

  on silph.tf line 36, in resource "cloudflare_record" "mx-10":
  36: resource "cloudflare_record" "mx-10" {
```

### Expected Behavior

```
It should have recreated/maintained the domain records.
```

### Actual Behavior

```
It failed to apply the records.
```

### Steps to Reproduce

```
1. `removed the old .terraform, .terraform.tfstate, .terraform.tfstate.backup`
2. `terraform init`
3. `git add, git commit, git push -u origin master`
4. `waited terraform cloud to plan and apply the records`
```

### Additional Context

```
I was able to fix the issue by deleting all cloudflare records that was previously generated by locally stored terraform. Terraform import did not fix this issue.
```

### References

```
#10065
https://github.com/hashicorp/terraform/issues/10065
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the CloudFlare Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the CloudFlare provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by pknomad** [comment]
Hey Daniel,

Thanks for correcting my Github issue request!

Cheers,
Jason

**Comment by danieldreier** [comment]
@pknomad I apologize, but it looks like our automation is actually not capable of migrating this issue. Can you please open an issue in https://github.com/cloudflare/terraform-provider-cloudflare instead? I'm going to close it here, because we can't help with this.
