### ISSUE TITLE
Unable to fetch zones in Google Cloud 

### ISSUE THREAD

**Issue by harshchauhan1988** [hashicorp/terraform#25724]
### Terraform Version

```
PS D:\codeRepo\terraformcodes> terraform -v
Terraform v0.12.29

```

### Terraform Configuration Files

```
##################################################################################
# VARIABLES
##################################################################################

variable "region" {
  default = "us-east-1"
}
variable "project" {
  default = "**********"
}

##################################################################################
# PROVIDERS
##################################################################################

provider "google" {
 credentials = file("D:\\Learning\\Terraform\\xxxxxxx-a36ce534feaa.json")
 project     = var.project
 region      = var.region
}

##################################################################################
# DATA Sources
##################################################################################

data "google_compute_zones" "available" {}

output "result_list" {
  value = "${data.google_compute_zones.available.names}"
}
...
```

### Debug Output

PS D:\codeRepo\terraformcodes\azure> terraform apply
data.google_compute_zones.available: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

result_list = []

### Actual Behavior

It should return the list of the zone in a region(which is set in the variable section). But currently returning the empty list.

### Steps to Reproduce

Please use the configuration file given above and run "terraform apply"

**Comment by harshchauhan1988** [comment]
Folks,

Can someone help?

**Comment by danieldreier** [comment]
Hello! It looks to me like this is an issue with the google cloud provider, rather than a bug in Terraform Core. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to. I've labeled this as `provider/google-cloud` to move it over to that provider's github repository, but you might also post to the [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) and see if you can get community support troubleshooting there.
