### ISSUE TITLE
No root module found for aws. Functionality may be limited. You may need to run terraform init and reload your editor.

### ISSUE THREAD

**Issue by amaurybsouza** [hashicorp/terraform#25734]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by danieldreier** [comment]
Hi!

This issue doesn't seem to be following one of the standard issue templates available from [the "New Issue" page](https://github.com/hashicorp/terraform/issues/new/choose). I can see that you submitted this issue using the template, but none of the fields are filled out, so it doesn't provide enough information for us to help you.

I'm closing this issue because it doesn't follow the issue template we provide. Please feel free to open a new issue using either the Bug Report or Feature Request template, as appropriate, fill out the fields and explain what problems you're seeing, and then the Terraform maintainers will review it. Thanks!

**Comment by amaurybsouza** [comment]
Hi Daniel,

Thanks. I'll do some tests again.
