### ISSUE TITLE
error configuring terraform provider

### ISSUE THREAD

**Issue by RamanaChowdam** [hashicorp/terraform#25731]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### References

i have Terraform v0.12.28

provider.aws v3.0.0
provider.null v2.1.2
when i run terraform apply and plan it giving below error
error configuring Terraform AWS Provider: Error creating AWS session: SharedConfigLoadError: failed to load config file, /home/wavemaker/.aws/config
caused by: INIParseError: invalid state with ASTKind {completed_stmt {0 NONE 0 []} false [{section_stmt {1 STRING 0 [78 111 110 101]} true []}]} and TokenType op

on main.tf line 1, in provider "aws":
1: provider "aws" {

but i am passing access_key and secret_key using env variables to the terraform main file

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
