### ISSUE TITLE
for_each over AWS security groups

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#25733]
### Terraform Version
```
Terraform v0.13.0-beta3
+ provider registry.terraform.io/hashicorp/aws v3.0.0
```

### Terraform Configuration Files
```
provider "aws" {
  region = "eu-west-2"
}

locals {
  securitygroupinboundipv4 = {
    "${aws_instance.ec2instance.private_ip}/32" = "8888"
    "0.0.0.0/0"                                 = "80"
  }
}

resource "aws_instance" "ec2instance" {
  ami           = "ami-0a13d44dccf1f5cf6"
  instance_type = "t2.micro"
}

resource "aws_security_group" "securitygroup" {
  name   = "mysecuritygroup"
  vpc_id = "vpc-xxxxxxxx"

  dynamic "ingress" {
    for_each = local.securitygroupinboundipv4

    content {
      cidr_blocks = ["${ingress.key}"]
      from_port   = ingress.value
      to_port     = ingress.value
      protocol    = "tcp"
    }
  }

}
```

### Expected Behavior
Terraform should create an EC2 instance.
Then it should obtain the private IP of the EC2 instance and create a security group containing the private IP allowed on port 8888 and all IPs allowed on port 80.

### Actual Behavior
The first run creates the EC2 instance and then has the error as below when creating the security group.

If I immediately rerun (EC2 already created) it creates the security group successfully.
If I do a destroy (so start from scratch) and then rerun with the line removed for 0.0.0.0/32 port 80, then it also works.
If I split the code, so that I have two distinct "ingress" blocks, once that uses the private IP variable and one that uses 0.0.0.0/0 then it also works.

ERROR on first run:
```aws_instance.ec2instance: Creating...
aws_instance.ec2instance: Still creating... [10s elapsed]
aws_instance.ec2instance: Still creating... [20s elapsed]
aws_instance.ec2instance: Creation complete after 22s [id=i-05e8019237d1a04bc]

Error: Provider produced inconsistent final plan

When expanding the plan for aws_security_group.securitygroup to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.ingress: length changed from 1 to 2.
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by danieldreier** [comment]
Thanks for reporting this!  I've reproduced this using the GA version of terraform 0.13.0. Since the error message is reporting `Provider produced inconsistent final plan`, I suspect that this will need to be fixed in the AWS provider, rather than in core. 

This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by bflad** [comment]
Hi @danieldreier 👋  I'm not sure what we can do in Terraform Providers code differently in this situation since it seems we are receiving a map with 1 key on plan (potentially stripped by the SDK) and 2 keys on apply. In this case, the map length should always be 2, even if the map contains an partially unknown element in a key such as:

```
"${aws_instance.ec2instance.private_ip}/32"
```

Where the value of the `aws_instance` resource `private_ip` attribute can only be known after it is applied. It seems to me that either the Terraform Plugin SDK or Core is handling this incorrectly.
