### ISSUE TITLE
terraform plan -target doesn't fail when module not exists

### ISSUE THREAD

**Issue by kam193** [hashicorp/terraform#25730]
When I use `terraform plan -target`, it does not fail if the requested module doesn't exist.

### Terraform Version
```
Terraform v0.12.29
+ provider.aws v3.0.0
+ provider.sops v0.5.1
+ provider.template v2.1.2
```

### Expected Behavior
Terraform should report error that target doesn't catch any resource.

### Actual Behavior
Terraform reports success with `no changes`.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan -target=module.ldssdagsafdg`

**Comment by mildwonkey** [comment]
Hi! This is expected behavior. It is consistent with terraform plan and apply: even if there are no resources _at all_, it is considered successful. Having no resources - including referencing a module that isn't in the configuration - is not an error. Making this situation an error would break other features. For example, if it were an error situation, you would not be able to import resources into modules that don't exist in the state (yet).

**Comment by kam193** [comment]
Oh, thanks for explanation! So, if in general it's expected behavior, but can be misunderstood when we are not carefully about the expected result - maybe would be helpful to print a warning that given targeting returned no resource?
