### ISSUE TITLE
Terraform v11: External datasource doesn't handle list values in json

### ISSUE THREAD

**Issue by RomeshSharma** [hashicorp/terraform#25744]
### Terraform Version

```
Terraform v0.11.14
```

### Terraform Configuration Files

```terraform
...
```

**Comment by RomeshSharma** [comment]
We are looking for ways to read json which has list attribute values inside terraform and parse the values into terraform variables.
Since we are using terraform v11 therefore tried using external datasource but it fails to load the json because it has list attribute values.
	* data.external.data_plane: data.external.data_plane: command "cat" produced invalid JSON: json: cannot unmarshal array into Go value of type string

Please can you suggest a way to achieve this with terraform v11. jsondecode works perfectly well in this situation but its only available in v12

**Comment by danieldreier** [comment]
Hello!

We are no longer investigating issues reported against Terraform 0.11.x. Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. We're actively working on Terraform 0.13 and the [0.13.0 GA will be released in a few days](https://github.com/hashicorp/terraform/issues/25016). I know that adopting 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
