### ISSUE TITLE
vsts_configuration not working for ADF

### ISSUE THREAD

**Issue by dirkdunn** [hashicorp/terraform#25743]
I am struggling with creating a simple git configuration for devops in ADF./

My ADF resource is setup as such:

```
resource "azurerm_data_factory" "resource_data_factory" {
    name = var.azure_naming_data_factory
    resource_group_name = var.resource_group_name
    location = var.location
    
    tags = var.tags

    vsts_configuration {
        account_name = "<account_name>"
        branch_name = "master"
        project_name = "<project_name>"
        repository_name = "<repo-name>"
        root_folder = "<root>"
        tenant_id = "<tenant-id>"
    }

    identity {
        type = "SystemAssigned"
    }
}
```

We are deploying this through devops, and the pipeline passes, however no git config is created. Everything else is created fine such as linked services etc.

What is going on here?

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
