### ISSUE TITLE
batch "Refreshing state" requests.

### ISSUE THREAD

**Issue by bcsgh** [hashicorp/terraform#25755]
### Current Terraform Version

```
$ terraform version
Terraform v0.12.24
+ provider.aws v3.0.0
```

### Use-cases
I need details about every network interface in the region (actually in several). This is easy to get:

```
data "aws_network_interfaces" "all" {}
data "aws_network_interface" "found" {
  for_each = toset(data.aws_network_interfaces.all.ids)
  id = each.key
}
```

However that is also slow. As in taking ~20 seconds in my case.

### Proposal

Based on the rate that the resulting "Refreshing state..." scroll past, I'm guessing that this is doing one request per resource with internal limited concurrency. Many of AWS API provides the ability to request multiple IDs at once. It would be nice if such cases could take advantage of that.

Without looking at the implementation, I can think of a few way that could get this effect with various side effects:
- Once the concurrency limit, has been reached, merge refresh operations that get queued.
- Merge everything possible before sending anything off (i.e. defer issuing API requests as long as something else can be evaluated).
- Only merge request from a single `for_each` resource.

**Comment by jbardin** [comment]
Thanks for filing the issue @bcsgh 

Terraform core currently has no way to know what types of could possibly can be merged together, as that information would be very specific to individual resources. The concurrency limits are also very specific to individual providers, and there is no way to currently get that information or act on it in core. 

The plugin protocol itself also has no mechanism for batching requests, however that is is long standing feature request that we want to research. Since it is highly dependent on the provider's needs, and must be defined in the both SDK and plugin protocol, we are tracking that in the terraform-plugin-sdk repository. If you are interested in this feature, I suggest following https://github.com/hashicorp/terraform-plugin-sdk/issues/7.

Thanks!
