### ISSUE TITLE
registry.terraform.io not working

### ISSUE THREAD

**Issue by bozerkins** [hashicorp/terraform#25756]
https://registry.terraform.io/ website is showing a blank page. It seems that something is wrong with loaded assets.

![image](https://user-images.githubusercontent.com/5130614/89498797-9f578c00-d7c7-11ea-8ec0-af8df437f8ed.png)

**Comment by alanmcg** [comment]
Same for me, with different console errors: 
![image](https://user-images.githubusercontent.com/43033315/89500680-6963d900-d7c2-11ea-81c5-c14bc954b71e.png)

Seems to be related to X-Content-Type-Options setting on the webserver:

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options](Mozilla dev network)

`The resource from “https://registry.terraform.io/assets/terraform-registry-3c3897b8880537ab9759d2e91a1a39c5.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)`

**Comment by bozerkins** [comment]
If you open the script url, it gives you the 404 page

![image](https://user-images.githubusercontent.com/5130614/89501238-a84a5c80-d7cb-11ea-8947-e6737ce0f6a5.png)

**Comment by petermarchant** [comment]
Same here. The file, https://registry.terraform.io/assets/terraform-registry-3c3897b8880537ab9759d2e91a1a39c5.js is missing, which is then failing the sub-resource integrity check - making the registry inaccessible. 

![image](https://user-images.githubusercontent.com/68903085/89512201-ca8faa80-d7ca-11ea-80b4-0b8dcd3227ff.png)

**Comment by phyber** [comment]
Still seeing this issue this morning. @justincampbell mentioned (on Twitter) that one of the issues was fixed (corrupt JS file), but this issue seems to be a completely missing asset. 🙀

**Comment by justincampbell** [comment]
Thanks for the report! I'm sorry this affected so many people yesterday and today. We're investigating how to prevent it from occurring in the future. In the meantime, the site should now be available for all users.

**Comment by jeffrichie** [comment]
Still not working for me.

**Comment by justincampbell** [comment]
@jeffrichie Could you try force-refreshing or clearing your browser's cache?
