### ISSUE TITLE
Integrate alibaba cloud autoscaling rule with cloud monitor alarm

### ISSUE THREAD

**Issue by singhupendra** [hashicorp/terraform#25764]
### Current Terraform Version
```
Terraform v0.12.18
```

### Use-cases
I want to trigger ESS autoscaling rule when threshold breaches for active messages in the queue in message service but that option is not available while the same is present in the console.

### Attempted Solutions
As a hack, I am working to update the cms alarm using local exec.

### Proposal
Cloud monitor alarm rule should have option to attach and trigger ESS scaling rules.

### References
https://www.terraform.io/docs/providers/alicloud/r/cms_alarm.html
- #6017

**Comment by mildwonkey** [comment]
Hi @singhupendra ! This is a provider-specific request and should be opened in the alicloud repository: https://github.com/aliyun/terraform-provider-alicloud

Our `hashibot` isn't able to automatically move this issue to the alicloud provider repository since it isn't in the terraform-providers organization anymore, so I will close this. Thanks!
