### ISSUE TITLE
aws s3 lifecycle bucket wants to set expiration to null when abort multipart upload is present

### ISSUE THREAD

**Issue by mpodber1971** [hashicorp/terraform#25788]
when i add a lifecycle policy to delete abort multipart uploads and do NOT include an expiration on an AWS s3 bucket, terraform wants to set the expiration to null.  It is misleading and a little concerning as to whether I accidentally implemented a lifecycle policy to delete our production data.

If the multi part upload isn't present, then terraform acts as expected.

I have attached the plan before apply, aws cli showing lifecycle post apply and a second terraform plan showing that it wants to apply these changes.

[test-bucket-post-apply-new-plan.log](https://github.com/hashicorp/terraform/files/5052441/test-bucket-post-apply-new-plan.log)
[test-bucket-lifecycle-post-apply.log](https://github.com/hashicorp/terraform/files/5052443/test-bucket-lifecycle-post-apply.log)
[test-bucket-pre-apply.log](https://github.com/hashicorp/terraform/files/5052444/test-bucket-pre-apply.log)

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
