### ISSUE TITLE
Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError

### ISSUE THREAD

**Issue by SubhakarKotta** [hashicorp/terraform#25797]
Terraform v0.12.24
provider "azurerm" {
version = "~> 2.12.0"
features {}
}

terraform apply throws below error.

Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*errors.errorString)(0xc00115d100), PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:0, Message:"Failed to refresh the Token for request to https://graph.windows.net/0159e9d0-09a0-4edf-96ba-a3deea363c28/servicePrincipals?%24filter=appId+eq+%27af9d7c2f-f3f5-4495-bb43-46696946c39e%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(nil)}

**Comment by danieldreier** [comment]
Thanks for reporting this! This looks like an error specific to the AzureRM provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
