### ISSUE TITLE
Data source looked up before resource creation resulting in an error (0.13)

### ISSUE THREAD

**Issue by AviateX14** [hashicorp/terraform#25796]
### Terraform Version
```
0.13.0
```

### Terraform Configuration Files

./main.tf:
```terraform
provider "azurerm" {
    version = "=2.17"
    features {}
}

resource "azurerm_resource_group" "rg" {
    name = "test"
    location = "uksouth"
}

module "test" {
    source = "./test"

    resource_group_name = "test"
}
```
./test/main.tf:
```terraform
variable "resource_group_name" {
    type = string
}

data "azurerm_resource_group" "test_rg" {
    name = var.resource_group_name
}
```
### Debug Output
[Debug output here.](https://gist.github.com/AviateX14/f916b98400f03212ade50ea5202cf869)

### Expected Behavior
In version 0.12, the resource in the root level/another module could be created and then looked up from another module that implicitly depended on it.

### Actual Behavior
In version 0.13, the data source pointing to a resource which does not yet exist is looked up during the state refresh step of apply/plan, resulting in terraform displaying an error to the effect of `Error: Error: Resource Group "test" was not found`.  

If the module containing the data source is defined with an explicit `depends_on` block the issue goes away, however previously this was implicit. 

### Steps to Reproduce
1. Create the required structure as denoted in the code samples above, with a file at `./main.tf` and a module at `./test/main.tf` with the contents as above.
2. terraform init
3. terraform apply OR terraform plan

### Additional Context
The 0.13 upgrade documentation does not suggest that implicit dependencies for these data sources have been removed or that depends_on in these scenarios is required.

### References
Possibly #25005

**Comment by jbardin** [comment]
Hi @AviateX14 

Does this exact configuration work with 0.12 as well? "Implicit dependencies" have never been a feature of Terraform, as it can only know about dependencies explicitly created through the configuration; so I would not have expect this configuration to work before.

The only way to delay reading of the `azurerm_resource_group` data source is to have it use a computed attribute of the `azurerm_resource_group` managed resource. Starting with 0.13, `depends_on` can be used within the same module, but eliminating the implied dependency is usually a better solution. As a general guideline, a data source should not be used to lookup a resource being created within the same configuration, and the attributes of the managed resource should be referenced directly in order to make it as easy as possible to understand the data flow through the config.

**Comment by AviateX14** [comment]
Hi @jbardin 

Yes, with that exact configuration and terraform v0.12.28 both plan and apply work as I have come to expect - i.e, terraform indicates that the data source will be read during apply, but isn't read until after the resource group is created. 

Using depends on or passing through a computed attribute does make the issue go away, but implementing that change across a ton of modules isn't a task I'd look forward to - so I'm keen to understand if this is a regression that will be fixed, or if terraform was never supposed to do this and thus will be left as is.

Regarding _why_ it's structured like that, it's just a form of decoupling.

**Comment by jbardin** [comment]
Thanks for the confirmation. This is not a regression, since the configuration shown was not expected to work. The simplest example of this type of dependency is using a local file:

```
# main.tf
resource "local_file" "f" {
  content = "testing"
  filename = "file.txt"
}


module "mod" {
  source = "./mod"
  filename = "file.txt"
}
```

```
./mod/main.tf
variable "filename" {
}

data "local_file" "f" {
  filename = "test.txt"
}
```

When `test.txt` does not exist, both 0.12 and 0.13 will produce the same error of `open test.txt: no such file or directory`

I am curios however what the azurerm provider is doing such that this worked on 0.12 and not on 0.13. Could you possibly attach the 0.12 trace log from your example configuration as it's being created from scratch?

**Comment by AviateX14** [comment]
Ineed @jbardin , it seems to be unique to the Azure provider, here's the trace log for an apply with my sample configuration: https://gist.githubusercontent.com/AviateX14/e91a495bb6599864aa47d700acebf32b/raw/6af299f98913169975b7fba7e02092bba0f1391a/tf2

**Comment by jbardin** [comment]
Thanks for the logs @AviateX14,

Are you certain that was with the exact config as shown above? The reason that this works as shown in the logs as

> `module.test.data.azurerm_resource_group.test_rg configuration not fully known yet, so deferring to apply phase`

But the sample config here has no way of making any attributes unknown. If that is the same config verbatim, I'll see if we can replicate this in isolation.

**Comment by jlforester** [comment]
I'm seeing similar behavior here.  I have a main.tf that uses two modules.  The first one creates an Azure resource group and returns the name of that resource group via an output.  That output gets its value directly from the resource itself.
The main.tf passes `module.vnet.resource_group_name` into the second module.
The second module uses that name in a data source:
```
data "azurerm_resource_group" "aks_collection" {
  name = var.resource_group_name
}
```
This data source fails because the resource group has not yet been created.  If you trace back the lineage of the resource group name, it eventually takes you back to the resource to be created by the first module.  It appears that the value it is getting is from the name property in the resource block, because if I change that value, the error references the new value of the name property.

Ultimately, `var.resource_group_name` in the data source is dependent on the resource to be created by a different module.

**Comment by AviateX14** [comment]
@jbardin certain, I can even git commit it if you like, it works fine in 0.12.28, doesn't work in 0.13.0.

**Comment by jbardin** [comment]
Thanks @AviateX14 for confirming. Since the actual observed behavior for 0.12 was incorrect, and 0.13 appears to work correctly, this isn't something we can classify as a bug in terraform 0.13.

The only remaining questionable behavior I see here is why the data source config is reported as unknown during refresh in the 0.13 log, since this error should be caught earlier. I cannot replicate this locally however, as I get `Resource Group "test" was not found` during the refresh walk as expected. In fact, I get this same error when using 0.12 as well, which means there must be something different in your local configuration. Another possibility which often happens in cloud providers is that there is some eventual consistency delay when destroying an creating in succession, and the data source briefly returns old data allowing it to succeed. 

Either way, this is more of a curiosity as to what the provider may be doing to cause it to work with 0.12, but the behavior for 0.13 here is correct.

**Comment by jlforester** [comment]
Is this really "working as designed"?  I have this same issue when no resources have been created.  The failure occurs during the "refreshing" stage BEFORE any resources have been created, so it's not an eventual consistency thing.  Ultimately, the value used in the data source DOES come from a managed resource created in a different module during the same `terraform apply`.

**Comment by jbardin** [comment]
@jlforester, if the data source attribute is derived from a computed value returned from a resource, then it should work. If that is not the case, please file a separate issue. The configuration in discussion here has no connection between the data source and the resource, and hence terraform cannot determine the correct order of operations.

**Comment by jlforester** [comment]
Ok, will do that.  Thanks.
