### ISSUE TITLE
Add namespace object

### ISSUE THREAD

**Issue by amancevice** [hashicorp/terraform#25801]
### Current Terraform Version

```
Terraform v0.13.0
```

### Use-cases

I would love to see a `namespace` object that behaves something like a module but purely for logical grouping of resources.

Something like:

```
namespace my_web_service {
  # ...
}

namespace my_events {
  # ...
}
```

Something like this would also make working with terraform inside an editor that supports code folding more pleasant.

### Attempted Solutions

You can essentially get this feature using modules, but referencing resources when modules are nested becomes cumbersome: 

```
terraform state show module.a.module.b.module.c.resource.name
``` 

vs. 
```
terraform state show a.b.c.resource.name
```

### Proposal

N/A

### References

N/A

**Comment by apparentlymart** [comment]
Hi @amancevice! Thanks for sharing this request.

Is it fair to say that your primary reason _not_ to use modules for this is that you want the resource address syntax to not include the `module.` separators? You also mentioned folding in an editor, but I assume a separate module would be an even better answer to "too much code onscreen"  because it would move the configuration into a separate file altogether.

Those `module.` markers in the address are there to address an ambiguity: Terraform needs to know for each step of the resource address whether it represents a resource type name or a module name. Because resource types can in principle be named anything, there could be a provider with a resource type called `a` (to use one of your examples).

For that reason, I expect that if we were to implement something like the namespace construct you've proposed here then it would still need a disambiguation qualifier, so you'd end up with something like `namespace.a` or `ns.a` instead of `module.a`, but not just `a` on its own.

Given that the commands that take resource addresses as arguments are all ones intended only for occasional use, unfortunately I expect we prefer not to introduce another concept into the user model, or redesign the address syntax to address this ambiguity some other way, if the benefit were felt only for infrequently-used operations.

If I've misinterpreted your use-case here, please let me know!

**Comment by amancevice** [comment]
that pretty much sums it up and I understand the reasons you listed against adopting the proposal.

**Comment by apparentlymart** [comment]
Thanks for confirming, @amancevice! In that case, I'm going to close this issue. Thanks again for sharing the request, and discussing the details with me.
