### ISSUE TITLE
Azure Elastic Pool SKU Block

### ISSUE THREAD

**Issue by erwabo** [hashicorp/terraform#25826]
### Terraform Version

```
v0.12.28
```

### Terraform Configuration Files

```terraform
..
  sku {
    name     = var.ep_name[var.envsize] #PremiumPool for DTU else ie BC_Gen5
    tier     = var.ep_edition[var.envsize] #Premium for DTU  Business Critical
    #family   = "" #var.ep_compute_gen  #Gen5
    capacity = var.vcores[var.envsize]  #250T DTU for Lite
  }
```

### Expected Behavior
The Premium Pool DTU does not have a "family", however the resource for the azurerm_mssql_elasticpool does not allow you to simply set family to null. It requires you to remove it. I would expect we could have ONE elastic pool for either DTU or vCore model.

### Actual Behavior
 You need to create two separate Elastic Pools which forces you to use a count index and duplicate code and refactoring unnecessarily.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
