### ISSUE TITLE
Make order of terraform function arguments consistent where appropriate

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#25879]
### Proposal
The order of arguments in terraform functions is frustratingly inconsistent.

As an example, here's a couple of the string functions:
```
split(separator, string)
trimsuffix(string, suffix)
```
In the 1st example, the string to operate on is the last arg.
In the 2nd example, the string to operate on is the first arg.

It's massively frustrating because despite the fact I know most of the functions off the top of my head, I can never remember the order of the args which means I have to refer to the documentation every single time I use one of these functions.

It'd be nice if there was some consistency e.g. the value to operate on is always first or always last.
I guess any change at this point would be a breaking change so I could understand if you don't want to clean this up but it is really really annoying and maybe it could be considered for 1.0.0?

Thanks

**Comment by apparentlymart** [comment]
Hi @antonosmond,

I agree that this consistency is frustrating. I suspect that the inconsistency reflects some different sources of inspiration over Terraform's life: I think `split`'s signature is mimicking the similar function in Ruby's standard library, which was very familiar to lots of the early Terraform developers, while more recently-added functions have instead tended to follow the example set by the Go standard library unless there is some strong reason to do otherwise, because Terraform's implementation language is Go and many of these functions are thin wrappers around Go standard library functions.

In an ideal world I _would_ like to change the argument order for these to be consistent, but unfortunately I don't think such a change would be practical. We do accept the possibility of tactical breaking changes in the major releases before 1.0, but when we make them we always try our best to either make old examples fail with a good error message explaining what to fix or provide upgrade tools to lower the burden of finding places where changes are needed and making those changes.

The problem with these string functions is that there isn't a way to for Terraform or an upgrade tool to reliably which of the two strings the user intended to use as which argument, and so it would not be practical to give clear and consistent advice in an error message or produce an upgrade tool that can determine whether a change is required. While there are some possible heuristics that could allow us to detect _possible_ inversions of the arguments, they would not (as far as I can see) be precise enough to justify returning an error message or automatically editing a configuration.

With that said, unfortunately I don't really see any practical path forward to address these inconsistencies. Such things seem to inevitably arise along the development path of all languages, because people come with different perspectives about what the conventions _mean_ and reviewers of new contributions can't possibly keep all of the existing language behaviors in mind to reliably detect such inconsistencies. Such is the maintenance burden of a growing library of language features and functions, and why we tend to try to keep the library of available functions relatively small even though most functions don't tend to contain a lot of code.

What we _can_ do is take more care in reviewing future functions to compare them with commonly-used existing functions. As noted above, the late-stage Terraform team we have today tends to default to following Go's example when there isn't a compelling reason to the contrary, and that is likely to be our guiding principle moving forward, even though we know and accept that there are some older functions that don't follow that principle.

Because I don't see a technical change we could make to Terraform to improve the situation described here, I'm going to close it. Closing this doesn't mean that the inconsistency isn't annoying -- it certainly is -- but one of the costs of having an ecosystem of existing Terraform modules is that we are constrained in what sorts of changes and improvements we can make to the language.

Thanks for pointing this out!
