### ISSUE TITLE
The AWS client vpn association resource overwrites and replaces vpn association created previously using same template

### ISSUE THREAD

**Issue by Play9win** [hashicorp/terraform#25896]
### Terraform Version
 0.13

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
 So actually the association should not try to replace each other once created.

### Actual Behavior

```hcl
resource "aws_ec2_client_vpn_network_association" "example" {
 count = 2
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.example.id
  subnet_id              = aws_subnet.example[count.index].id
}
```

The above snipped creates the association the first time but the next time it replaces the association. As expected it will create two associations but the next time when I update my template, one association replaces another association and that results in a crash.
### Steps to Reproduce

Just add the resource association for subnets for client vpn. Make it two. Then :
1. `terraform plan`
2. `terraform apply`

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
