### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by dgonzalezp** [hashicorp/terraform#25909]
### Terraform Version
```terraform
Terraform v0.13.0
```

### Terraform Configuration Files
```terraform
terraform {
  required_version = ">= 0.13"
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.23.0"
    }
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.2.3"
    }
    local = {
      source = "hashicorp/local"
    }
    random = {
      source = "hashicorp/random"
    }
  }
}
```

### Debug Output
```terraform
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/databricks:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/databricks
```

### Expected Behavior
terraform init succeed

### Actual Behavior
terraform init fails

### Steps to Reproduce
1. `terraform init`

**Comment by dgonzalezp** [comment]
It still happens to me trying to user databricks provider... terraform creates a folder - and copies all its own providers to it, but it doesn't copy other providers, for me its databricks

'-' folder
![image](https://user-images.githubusercontent.com/20174436/90559469-41318e00-e163-11ea-9b9a-f5d1b232f939.png)

databrickslabs folder
![image](https://user-images.githubusercontent.com/20174436/90559533-51496d80-e163-11ea-97dc-1e709a752393.png)

workaround... manual copy the folder of the provider to - folder
![image](https://user-images.githubusercontent.com/20174436/90559613-7211c300-e163-11ea-9439-76de03a0483d.png)

![image](https://user-images.githubusercontent.com/20174436/90559658-85249300-e163-11ea-9aa2-84025eb8d2fe.png)

Just need to think If you're going to automate this, creating a scripts that copies the folder while this is fixed

**Comment by mildwonkey** [comment]
Hi @dgonzalezp , thanks for reporting this and I'm sorry you're experiencing this confusing behavior!

Terraform v0.13 pulls a list of providers from both the state and configuration when determining provider requirements - you can run `terraform providers` to see this in action. Terraform v0.12 has no concept of 'namespaces', so when it encounters a provider named "databricks" it queries a special "alises" table in the registry, which is where that odd-looking `"-/databricks"` (and other providers) come from. Since that provider is not a hashicorp provider, it's unable to find it.

You can fix this by using the [`terraform state replace-provider`](https://www.terraform.io/docs/commands/state/replace-provider.html) command to update your statefile with the  databricks providers'  source address : 

`terraform state replace-provider -/databricks registry.terraform.io/databrickslab/databricks`

For anyone else interested in this issue, this information is in the [upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations), but rather hard to find in the in-house providers section. 

Thanks again, and sorry for the confusion!

**Comment by dgonzalezp** [comment]
Great! Thank you for your answer! @mildwonkey
