### ISSUE TITLE
Terraform unable to use list(string) in json file 

### ISSUE THREAD

**Issue by prannoy47** [hashicorp/terraform#25911]
Using below:
Terraform v0.12.26
+ provider.azurerm v2.21.0
+ provider.template v2.1.2

I have in Terraform json configuration file :

```
{
    "res_appgw_sku": {
        "name": "Standard_Small",
        "tier": "Standard",
        "capacity": 2
    },
    "res_appgw_ssl_policy": {
        "policy_name": "AppGwSslPolicy20170401S",
        "policy_type": "Predefined"
    },
    "res_appgw_backend_address_pool": [
        {
            "name": "app-gw-brp",
            "ip_addresses": "${ip_addresses}",
            "fqdns": "contoso.com"
        }
    ]
}
```
and i have a variable ip_addresses defined like this :

```
variable "ip_addresses" {
  type = list(string)
  default = [
    "x.x.x.x/x",
    "x.x.x.x/x",
  ]
}
```
Now i'm calling the Json file this way :

```
data "template_file" "appgw_config" {
  template = "${file("${path.module}/template/appgw_config.json")}"

   vars = {
      ip_addresses= "${jsonencode(var.ip_addresses)}"
   }
}
```
Output file as :

```
output "appgw_config" {
    value = "${jsondecode(data.template_file.appgw_config.rendered)}"
}
```
It is parsing the JSON correctly. But i'm getting this error :

```
Error: Error in function call

  on output.tf line 9, in output "appgw_cofig":
   9:     value = "${jsondecode(data.template_file.appgw_cofig.rendered)}"
    |----------------
    | data.template_file.appgw_cofig.rendered is "{\r\n    \"res_appgw_sku\": {\r\n        \"name\": \"Standard_Small\",\r\n        \"tier\": \"Standard\",\r\n
 \"capacity\": 2\r\n    },\r\n    \"res_appgw_ssl_policy\": {\r\n        \"policy_name\": \"AppGwSslPolicy20170401S\",\r\n        \"policy_type\": \"Predefined\"\r\n
   },\r\n   \"res_appgw_backend_address_pool\": [\r\n        {\r\n            \"name\": \"app-gw-brp\",\r\n            \"fqdns\": \"contoso.com\",\r\n            \"ip_addresses\": \"[\"x.x.x.x/x\",\"x.x.x.x/x\"]\"\r\n        }\r\n    ],\r\n}\r\n"

Call to function "jsondecode" failed: invalid character 'x' after object
key:value pair.
```

**Comment by mildwonkey** [comment]
Hi @prannoy47 !
The Terraform team recommends using the [templatefile](https://www.terraform.io/docs/configuration/functions/templatefile.html) function instead of the `template_file` datasource, and in the linked documentation you'll find some examples of using templatefile to generate json.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
