### ISSUE TITLE
Error status code: 400 -- 

### ISSUE THREAD

**Issue by gurukathirvel** [hashicorp/terraform#25910]
aws_subnet.PVTSUB0101: Creating...
aws_subnet.PVTSUB0102: Creating...
aws_subnet.PUBSUB0101: Creating...
aws_subnet.PUBSUB0102: Creating...

Error: Error creating subnet: InvalidVpcID.NotFound: The vpc ID 'aws_vpc.VPCDEV01.id' does not exist
	status code: 400, request id: 670a5965-b007-42d6-9a87-9ac4f8cd72b5
Error: Error creating subnet: InvalidVpcID.NotFound: The vpc ID 'aws_vpc.VPCDEV01.id' does not exist
	status code: 400, request id: 814a11be-4255-459c-8f38-95cd9ad419e1
Error: Error creating subnet: InvalidVpcID.NotFound: The vpc ID 'aws_vpc.VPCDEV01.id' does not exist
	status code: 400, request id: c513d681-92a3-4887-8830-59b80f20a4ac
Error: Error creating subnet: InvalidVpcID.NotFound: The vpc ID 'aws_vpc.VPCDEV01.id' does not exist
	status code: 400, request id: 43444785-abb3-40bf-b7d0-6d16f75c9e8a

Output Expected : VPC & Subnet, but subnet not created as VPC created little late

Resources tf file:

resource "aws_vpc" "VPCDEV01" {
  cidr_block = "10.1.0.0/16"
  tags = {
    Name : "VPCDEV01"
  }
}
resource "aws_subnet" "PUBSUB0101" {
  cidr_block        = "10.1.1.0/24"
  vpc_id            = "aws_vpc.VPCDEV01.id"
  availability_zone = "us-east-2a"
  tags = {
    Name : "PUBSUB0101"
  }
}

**Comment by mildwonkey** [comment]
Hi @gurukathirvel ,
You are passing a literal string `"vpc_id = "aws_vpc.VPCDEV01.id"` to the `aws_subnet` resource. Remove the surrounding `"` to pass the id of the `aws_vpc` (`"vpc_id = aws_vpc.VPCDEV01.id`).


Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by gurukathirvel** [comment]
Hi

Thanks for your reply

when i searched i found that it is quite issue in old version, thats why i
raised this as issue

Sorry about that, i will use community forum in future

Thanks & Regards,
Kathirvel G
