### ISSUE TITLE
Allow dynamic interpolation capability for module providers in terraform 0.13

### ISSUE THREAD

**Issue by swetli** [hashicorp/terraform#25932]
### Current Terraform Version
Terraform v0.13.0

```
...
```

### Use-cases
With the addition of for_each capability for modules in terraform 0.13 we finally got the missing feature we all wanted but it is still incomplete in case we need to instantiate modules for different providers. This is true especially in the case when calling the same module is needed but for different account/region - and unfortunately many AWS features still need to be managed on per account/ per region level

### Proposal
Have the following structure possible:

```
variable account_list {
  default = [
    "112233445566",
    "223344556677",
  ]
}

variable regions {
  default = [
    "eu-central-1",
    "eu-west-1",
  ]
}

locals {
  accounts_and_regions = { for p in setproduct(var.account_list, var.regions) : "${p[0]}/${p[1]}" => {
    account_id = p[0]
    region     = p[1]
    }
  }
}

module "xxx" {
  for_each = local.accounts_and_regions

  providers = {
    aws = format("aws.account_%s-%s", each.value.account_id, each.value.region)
  }
  
  source = "./modules/module_source"
}
```

**Comment by jbardin** [comment]
Hi @swetli 

Unfortunately this is not something that can be added to the 0.13 release, since it would involve some major internal changes to Terraform to accomplish. We have some open issues requesting the ability to dynamically assign providers already #25244 and #19932. We can track the individual features there.

Thanks!
