### ISSUE TITLE
Terraform Linode Resize VM Issue

### ISSUE THREAD

**Issue by UnderFenex** [hashicorp/terraform#25946]
When I configure a .tf to change the type and disk size in Terraform. I got this issue:

`Error: failed to apply instance disk spec: Error resizing disk xxx: size exceeds disk size for Instance yyy`

It seems that Terraform is not proceding in order, which is first to resize the disk, then resize the VM in linode. Any solutions?

tf file:
```
provider "linode" {
  token = "jjjj"
}

resource "linode_instance" "presm11" {
    label             = "label"
    region            = "us-southeast"
    type              = "g6-standard-4"
    config {
        kernel       = "linode/grub2"
        label        = " Disk Profile"
        root_device  = "/dev/sda"
        devices {
            sda {
                disk_label = "Ubuntu 16.04 LTS Disk"
            }
            sdb {
                disk_label = "512 MB Swap Image"
            }
        }
    }
    disk {
        label            = "Ubuntu 16.04 LTS Disk"
        size             = 160000
    }
    disk {
        label            = "512 MB Swap Image"
        size             = 512
    }
}

```

**Comment by danieldreier** [comment]
Hello!

It looks to me like you're asking for help with a Terraform provider, rather than reporting a bug in Terraform Core. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
