### ISSUE TITLE
Error modifying DB Instance stage-course-service-pg: InvalidParameterCombination: No modifications were requested

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#2595]
terraform apply fails on rds instances that have pending-modifications set..example: setting `multi-az: true` on `aws_db_instance` will succeed on the first terraform apply and set the pending-modification in aws but subsequent terraform applies after that will fail while it's still in the pending-modification state.  Here are the output files from both the successful apply and the next apply which failed:

Successful: https://gist.github.com/PurrBiscuit/640cb6c4c7fea6096fce
Failed: https://gist.github.com/PurrBiscuit/a4837c64e3a13c63899d

**Comment by PurrBiscuit** [comment]
this isn't failing anymore but I'm going to leave this open in case anyone else is having the issue as well.  terraform apply seems ok for me once again with the pending-modification still in aws for the multi-az enabling

**Comment by catsby** [comment]
I suspect this is due to RDS only applying changes in the next maintenance window, unless you're specifying `apply_immediately`: 

- https://terraform.io/docs/providers/aws/r/db_instance.html
- http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html

Even with `apply_immediately`, it can take a few minutes for RDS to apply that change. Were you making multiple changes in multiple applies?
