### ISSUE TITLE
Terraform 0.13 can't deal with custom source containing more than 3 parts

### ISSUE THREAD

**Issue by endofcake** [hashicorp/terraform#25974]
### Terraform Version

```
0.13.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    external = {
      source = "artifactory.<corporate_domain>/hashicorp-remote/hashicorp/external"
    }
  }
  required_version = ">= 0.13"
}
```

### Additional Context

We use Terraform in a regulated environment, where our build tools do not have access to the Internet. Terraform Registry is mirrored on our Artifactory, with the url of https://artifactory.<corporate_domain>/hashicorp-remote/.
Terraform 0.13 supports installing providers from custom sources, but it looks like it's very rigid in its interpretation of the "source" parameter. When I try to install a provider with the following configuration block above, I get an error:

```bash
Error: Invalid provider source string
on versions.tf line 3, in terraform:
3: external = {
4: source = "artifactory.<corporate_domain>/hashicorp-remote/hashicorp/external"
5: }
The "source" attribute must be in the format "[hostname/][namespace/]name"
```

Looks like the current implementation of Terraform can't deal with sources which have more than 3 parts.

**Comment by alisdair** [comment]
[Provider source addresses can indeed only have up to three parts](https://www.terraform.io/docs/configuration/provider-requirements.html#source-addresses): `[<HOSTNAME>/]<NAMESPACE>/<TYPE>`. In this case, your source addresses should be "artifactory.<corporate_domain>/hashicorp/external".

It should be possible to host a full registry source at a non-root URL. The [remote service discovery protocol documentation](https://www.terraform.io/docs/internals/remote-service-discovery.html) describes how to do this:

>The discovery protocol's purpose is to map from a user-provided hostname to the base URL of a particular service. Each host can provide different combinations of services -- or no services at all! -- and so the discovery protocol has a secondary purpose of allowing Terraform to identify _which_ services are valid for a given hostname.
>
> For example, module source strings can include a module registry hostname as their first segment, like `example.com/namespace/name/provider`, and Terraform uses service discovery to determine whether `example.com` _has_ a module registry, and if so where its API is available.

I'm not sure whether or not Artifactory supports the registry protocols, however.

We do intend to implement a simpler approach that might be more suitable for your use case: network-based provider mirrors, rather than full registry API implementations. [Martin Atkins wrote more about this in this discussion thread](https://discuss.hashicorp.com/t/private-provider-registry/7230/2); the feature didn't quite make it into 0.13, but we do still hope to ship it soon.

I hope this explains the error message and the way forward for your use case! I'm going to close this issue as I don't believe it represents a Terraform bug.
