### ISSUE TITLE
Document instance gateway attachment dependency for VPC

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#2600]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html#gatewayattachment

Does Terraform handle this automatically when creating a new `aws_instance?. If so, this should be documented at https://www.terraform.io/docs/providers/aws/r/instance.html.

If Terraform does *not* handle this, a warning note or separate VPC example should be added to the same page.

**Comment by catsby** [comment]
Hey @pikeas – can you help me understand the question/issue here? Terraform is mostly declarative, we try to avoid doing things automatically (like creating gateways) that are explicitly required or requested.

**Comment by pikeas** [comment]
@catsby Sure thing, I can expand on my thoughts.

According to Amazon's docs, an instance (and a few other resource types) in a VPC with a public IP address has an implicit dependency on the VPC's internet gateway. The docs suggest that all resources in this category should be created with an explicit dependency on the gateway.

So, in an ideal world, Terraform should handle this automatically as part of the dependency graph. However, if this is too much magic, an alternative is to update Terraform's docs to add a note recommending an explicit `depends_on` for these resources.

**Comment by catsby** [comment]
Hey @pikeas – turns out I did add a note on this, on the Internet Gateway documentation page back in March:

- https://terraform.io/docs/providers/aws/r/internet_gateway.html
- https://github.com/hashicorp/terraform/commit/cd15c9aaf9bbca910a19b22d68a00c04ce2cbc8e

I'm going to go ahead and close this for now. I think documenting is the best way to go, as opposed to Terraform creating internal, hidden or magical dependencies that the user doesn't immediately know about.

Thanks!

**Comment by pikeas** [comment]
Could you buff the docs a bit? Link back to the AWS page and enumerate the resource types for which a hard dependency link is recommended?
