### ISSUE TITLE
Argument order provided to cidrsubnets can wastefully exhaust IP range

### ISSUE THREAD

**Issue by gmaghera** [hashicorp/terraform#26013]
### Terraform Version

```
0.13.0
```

### Terraform Configuration Files

```terraform
cidrsubnets("10.194.48.0/21", 2, 4, 2, 4, 2, 4)
```

### Expected Behavior
Get a valid split, there are enough IPs in the CIDR to come up with them.

### Actual Behavior
```
Error: Invalid function argument

  on <console-input> line 1:
  (source code not available)

Invalid value for "newbits" parameter: not enough remaining address space for
a subnet with a prefix of 23 bits after 10.194.54.0/25.
```

However, if I supply the arguments in a different order, it works just fine:
```
> cidrsubnets("10.194.48.0/21", 2, 2, 2, 4, 4, 4)
[
  "10.194.48.0/23",
  "10.194.50.0/23",
  "10.194.52.0/23",
  "10.194.54.0/25",
  "10.194.54.128/25",
  "10.194.55.0/25",
]
> cidrsubnets("10.194.48.0/21", 4, 4, 4, 2, 2, 2)
[
  "10.194.48.0/25",
  "10.194.48.128/25",
  "10.194.49.0/25",
  "10.194.50.0/23",
  "10.194.52.0/23",
  "10.194.54.0/23",
]
```

### Steps to Reproduce
1. `terraform init`
2. `terraform console`
3. `cidrsubnets("10.194.48.0/21", 2, 4, 2, 4, 2, 4)`

### Additional Context
Is there a general rule for how to provide arguments to the cidrsubnets functions so it wastes the least amount of IP addresses?

**Comment by mildwonkey** [comment]
Hi @gmaghera ,
What you are seeing is a natural consequence of how subnetting works. There are fixed points that an address range can start: by definition a subnet mask must have all of the subnet bits set to zero, and so this function must skip ahead its allocations to preserve that property. 

This is why the order matters when you are calculating subnets of different sizes. The `cidrsubnets` cannot generate an optimal packing order itself, because the ordering is how it correlates input with output, so it is up to the user to determine an efficient order. 

If you have further questions, I suggest you ask on [the community forum](https://discuss.hashicorp.com/c/terraform-core) where you'll find a lot more folks (and specifically I bet you'll find someone who can explain this better than I!).
