### ISSUE TITLE
how to use the feature Terraform v0.13 Beta: Module for_each and count

### ISSUE THREAD

**Issue by gauravachatrath** [hashicorp/terraform#26019]
Hi ,

I have terraform version 0.13.0

and i am trying to use the feature Terraform v0.13 Beta: Module for_each and count

i specified this

variable “vpc_id” {
type = string
}

variable “subnets” {
type = map(object({
cidr_block = string
availability_zone = string
}))
}

**How do i specify the value for cidr_block and availability_zone ?**

I tried this

subnets = {
test = {
cidr_block = “10.0.0.0/16”
availability_zone = “eu-west-1”
}
test2= {
cidr_block = “10.10.0.0/16”
availability_zone = “eu-west-1”
}}

it gave me this error Error: Unsupported argument . **Any idea how can i fix it ?**

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by gauravachatrath** [comment]
I already posted there but i didn't get a reply and the documentation by terraform is incomplete so it would be better for developers to give a proper example so we can use this amazing feature
