### ISSUE TITLE
Documentation Bug: Provision Infrastructure

### ISSUE THREAD

**Issue by ravi-vijaykumar** [hashicorp/terraform#26058]
### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.70.0

Your version of Terraform is out of date! The latest version
is 0.13.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Documentation File
https://learn.hashicorp.com/tutorials/terraform/aws-provision?in=terraform/aws-get-started#running-provisioners

The example shared does not output anything which is covered in the first part of the sentence, however the second sentence is misleading that one can verify the ip_address.txt. 

```
Terraform will output anything from provisioners to the console, but in this case there is no output. However, we can verify everything worked by looking at the ip_address.txt file:
```

### Expected Behavior
Ideally documentation could have ended with first sentence as below:

```Terraform will output anything from provisioners to the console, but in this case there is no output.```

### Actual Behavior
The example shared does not output anything which is covered in the first part of the sentence, however the second sentence is misleading that one can verify the ip_address.txt. (please remove the screenshot as well.)

```
Terraform will output anything from provisioners to the console, but in this case there is no output. However, we can verify everything worked by looking at the ip_address.txt file:
```

### Additional Context
While reading through the documentation this part misleads and takes away a lot of time. ip_address.txt was created as part of previous exercise hence it will be showing the same ip of old instance always.

**Comment by bflad** [comment]
Hi @ravi-vijaykumar  👋  Thank you for reporting this.

It appears that since this issue was raised that the HashiCorp Learn tutorials have since moved or materially changed as the link is now pointing to a Packer tutorial instead of one featuring Terraform's provisioners. Given that, I'm going to close this issue out. I believe it is now also possible to provide direct feedback on the tutorial pages so that the team that maintains them, which doesn't typically monitor the issues in this repository, can act on it.
