### ISSUE TITLE
Terraform console, incorrect output for object when properties are null

### ISSUE THREAD

**Issue by MaG21** [hashicorp/terraform#26099]
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

```terraform
# main.tf
locals {
  object = {
        "ap-southeast-2": {
            "cognitoMinPasswordLength": null,
            "cognitoTempPasswordValidityInDays": null
        }

        "us-east-1": {
            "cognitoMinPasswordLength": 8,
            "cognitoTempPasswordValidityInDays": 1
        }
  }
}
```

### Expected Behavior

For `local.object.ap-southeast-2 == {}` it should return true, but instead returns false.

The expected behavior should be either:

Return the correct representation of the map without promoting it to {}
```terraform
{
  "ap-southeast-2" = {
    "cognitoMinPasswordLength" = null
    "cognitoTempPasswordValidityInDays" = null
  }
}
```

OR

if terraform is going to promote a map with all the properties null to empty map `{}`, then it should return true when one does this: `local.object.ap-southeast-2 == {}`

### Actual Behavior

See Steps to Reproduce.

### Steps to Reproduce

```text
$ terraform console
> local.object
{
  "ap-southeast-2" = {}
  "us-east-1" = {
    "cognitoMinPasswordLength" = 8
    "cognitoTempPasswordValidityInDays" = 1
  }
}
> local.object.ap-southeast-2
{}
> local.object.ap-southeast-2 == {}
false
> {} == {}
true
> exit
```

**Comment by apparentlymart** [comment]
Hi @MaG21! Thanks for sharing this, and sorry for the confusing result.

The bug here seems to be in the output from `terraform console`. Specifically, it's incorrectly omitting object properties that are `null` when printing out an object, even though the object does actually still have those properties. The correct output from your request to `local.object.ap-southeast-2` would've been:

```
{
  cognitoMinPasswordLength = null
  cognitoTempPasswordValidityInDays = null
}
```

The root cause of this is, I think, the fact that `terraform console` is unfortunately still using some old codepaths from prior to Terraform v0.11, with some shimming to convert from the new type system back to the old type system. Because the old type system had no concept of `null` at all, the shim is approximating it by just omitting the nulls:

https://github.com/hashicorp/terraform/blob/fa4917172dcad5be2ac940fd9be3060b6d564702/configs/hcl2shim/values.go#L181-L183

We've not done much work in `terraform console` for quite some releases now due to attention being elsewhere. I think the best solution to this issue, which would also likely take care of a number of other quirks resulting from lowering a value into the old type system, would be to do what this `FIXME` comment calls for:

https://github.com/hashicorp/terraform/blob/fa4917172dcad5be2ac940fd9be3060b6d564702/repl/session.go#L72-L76

`cty.Value` is the internal representation of any value in the Terraform type system, so writing a new value formatter that works directly with that representation (or, perhaps, adapting the one we already have for `terraform plan`'s output) would allow it to represent the exact value with no misleading approximations.

Along with showing `null` properly, one other change I think would be useful (based on other questions I've seen folks ask about the `terraform console` output) would be to have it detect when the value is of a type that the Terraform language doesn't have a direct constructor syntax for -- lists, sets, and maps in particular -- and include type conversion functions in the output as a way to disambiguate the various similar types:

```
> local.tuple_example
[
  "a",
  "b",
  "c",
]
> local.list_example
tolist([
  "a",
  "b",
  "c",
])
```

This distinction is important for a similar reason as what prompted this issue: a tuple-typed value and a list-typed value are not equal, even if they both have the same sequence of values inside.

**Comment by apparentlymart** [comment]
While I was writing my previous comment I couldn't shake the idea that I'd written code like I was describing _somewhere_ before. Just after posting I remembered it was in my personal side-project provider [`apparentlymart/testing`](https://registry.terraform.io/providers/apparentlymart/testing/latest) where I wrote [`formatValue`](https://github.com/apparentlymart/terraform-provider-testing/blob/0847595f44649286113990765297bea82e6707eb/testing/values.go#L15) with a similar goal in mind: to try to avoid any situation where two values that don't compare equal with `==` would have the same rendered visualization.

Hopefully that code can serve as a useful starting point for a similar function in the `terraform console` command.

**Comment by MaG21** [comment]
After reading the explanation, I believe the tittle is a little misleading. I should probably change it to one that summarizes the problem more precisely so anyone like you with domain knowledge can pick it from the pool of issues without the need of reading the whole issue.
