### ISSUE TITLE
Terraform fmt should handle for statements continued onto the next line cleaner

### ISSUE THREAD

**Issue by v3n** [hashicorp/terraform#26107]
### Current Terraform Version

```
0.13.1
```

### Proposal
Terraform `fmt` formats the following code block like this:

```
locals {
  route_table_to_subnet = {
    for art in data.aws_route_table.all :
    art.route_table_id => art
  }
}
```

This is extremely messy and hard to read.

Following the rules for formatting function calls that are continued onto another line, I would expect this formatting:

```
  route_table_to_subnet = {
    for art in data.aws_route_table.all:
      art.route_table_id => art
  }
```

### References

`terraform fmt` for a functions that are continued to the next line:

```
locals {
  route_table_by_az_subnet_type = setproduct(
    distinct(
      data.aws_subnet[*].availability_zone_id
    ),
    distinct(
      data.aws_subnet[*].tags[var.subnet_tag_key]
    ),
  )
}
```

**Comment by apparentlymart** [comment]
Hi @v3n! Thanks for sharing this.

The formatting you are seeing for function calls results from the function arguments being wrapped in parentheses: the conventional Terraform indentation style calls for one indentation level per pair of "brackets". (that is, `()`, `[]`, and `{}` pairs.)

The `for` expression doesn't include any paretheses around the output expression that would justify the indentation, so that's why `terraform fmt` doesn't insert any. The `for` expression is intended to resemble Python list comprehensions, but reordered so that the local variable declarations appear before their uses to allow for autocomplete functionality in text editors. The formatter therefore arranges multi-line `for` expressions in a flat style that's typical in Python, also resembling how SQL `SELECT` statements are typically wrapped over multiple lines:

```hcl
locals {
  route_table_to_subnet = {
    for k, v in source :
    new_k => new_v
    if condition
  }
}
```

Intended to resemble:

```python
route_table_to_subnet = {
  new_k: new_v
  for k, v in source
  if condition
}
```

...or:

```sql
SELECT new_k, new_v
FROM source
WHERE condition
```

We generally don't make changes to `terraform fmt` that represent differences of opinion about whitespace, because there is no formatting style that will be preferred and familiar to everybody and changes to the existing whitespace style have the significant cost of creating noise in the version control history for those who have already formatted their configurations with previous versions. We tend to reserve changes to `terraform fmt` for situations where we introduce a new canonical style where `terraform fmt` previously had no opinion at all, which can happen when competing idiom develops in the community that harms consistency.

For that reason, I don't think adding additional whitespace on some of the lines of a multi-line `for` expression would add sufficient value to overcome the high cost of making an entirely-cosmetic change to all existing Terraform configurations. I do understand that you have a preference for a different style, but unfortunately that isn't reason enough to change the behavior for everybody, and `terraform fmt` is designed to be opinionated about whitespace formatting.

For that reason, I'm going to close this issue. Thanks again for sharing this feedback.
