### ISSUE TITLE
data_source depends_on count vs for_each

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/terraform#26111]
### Terraform Version
```
Terraform v0.13.0
```

### Terraform Configuration Files

(This issue is related to #10603)

Sample code from [https://stackoverflow.com/questions/56713493/terraform-how-to-get-ip-address-of-aws-lb](url).
We changed count with for_each to test early evaluation of data source block.

```terraform

data "aws_network_interfaces" "this" {
  filter {
    name = "description"
    values = ["ELB net/${aws_lb.this.name}/*"]
  }
  filter {
    name = "vpc-id"
    values = ["${var.vpc_id}"]
  }
  filter {
    name = "status"
    values = ["in-use"]
  }
  filter {
    name = "attachment.status"
    values = ["attached"]
  }
}

locals {
  nlb_interface_ids = "${flatten(["${data.aws_network_interfaces.this.ids}"])}"
}

data "aws_network_interface" "ifs" {
  for_each = toset(local.nlb_interface_ids)
  id = each.value
}

output "nlb_network_interface_ips" {
  value = {
    for ifs_id, ifs in data.aws_network_interface.ifs:
      ifs.availability_zone => ifs.private_ips
  }
}
```

### Expected Behavior

terraform evaluates data source block at apply time (respecting dependencies)

### Actual Behavior

early evaluation of data source block take place returning:

```
Error: Invalid for_each argument

  on main.tf line 494, in data "aws_network_interface" "ifs":
 494:   for_each = toset(local.nlb_interface_ids)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

Using `count` instead of for_each, data source dependencies work without error:

```
data "aws_network_interface" "ifs" {
  count = "${length(local.nlb_interface_ids)}"
  id = "${local.nlb_interface_ids[count.index]}"
}

output "aws_lb_network_interface_ips" {
  value = "${flatten([data.aws_network_interface.ifs.*.private_ips])}"
}
```

What is the difference from count and for_each ? There are not same type of interpolation terraform can use for dependencies calculation ?

### References

- #10603

**Comment by favoretti** [comment]
Hmm, another use-case similar to #26109 behavior?

**Comment by Roxyrob** [comment]
(update)

Using terraform 0.13.1 also count version has same for_each behavior (early evaluation with error)

**Comment by favoretti** [comment]
0.13.1 has more issues that made it unusable for us, but on 0.13.2 we have about the same what you have now, just in a different use-case. See the bug I linked. What is interesting is that `count` works for you. I'll try it in our case to see if it helps.

**Comment by jbardin** [comment]
Hi @Roxyrob,

The difference between `count` and `for_each` here is that while you may know the number of values in `local.nlb_interface_ids` at plan time, the individual values are unknown and can't be used until apply.

Now if you have the `aws_lb.this.name` in the same config as this example implies, you should be accessing the necessary data from that resource directly. While that still means you can't use the values in a `for_each` statement, it will make the configuration easier to reason about.

There's a few other oddities here that may have better solutions, but since we use GitHub issues for tracking bugs and enhancements, rather than for questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks

**Comment by Roxyrob** [comment]
Hi @jbardin,
as I wrote I think this behavior is relate to issue #10603 (defined a bug by @apparentlymart "You're right that this is a bug, but for now I would suggest working around it by adding a "dummy interpolation""). Also here depends_on does not work as expected, I leave depends_on out for this, my first try was depends_on. For that I opened as issue instead of question. @apparentlymart named "dummy interpolation" workaround, can you explain better how to implement such workaround ?

It seems that for_each and count is in the same situation here but count is evaluated at apply time, for_each eraly at plan time, this is odd and it is odd also that count works with terraform 0.13.0 but no more from 0.13.1 and above, this is not consistent !

aws_lb api does not contains ips of the load balancer so it is necessary to use locals to extract ips passing from interfaces (finding from interfaces list conatining load balancer name).

This is not to ask a solution for the specific configuration but to know if there are bugs and inconsistencies or not.

**Comment by jbardin** [comment]
> as I wrote I think this behavior is relate to issue #10603 (defined a bug by @apparentlymart "You're right that this is a bug, but for now I would suggest working around it by adding a "dummy interpolation""). Also here depends_on does not work as expected, I leave depends_on out for this, my first try was depends_on. For that I opened as issue instead of question. @apparentlymart named "dummy interpolation" workaround, can you explain better how to implement such workaround ?
> 

This is unrelated to `depends_on` with data sources. I'm not sure what the unmet expectations are here, but that feature appears to now be working as expected during plan, and doesn't result in this type of error. If you do have an example of a problem with `depends_on`, please file a separate issue, as the ongoing work for 0.14 will be in the same area.

By "dummy interpolation", he means that referencing a computed attribute of a resource, even if it's not necessary, will force the evaluation of the data source to be deferred to apply time.

> It seems that for_each and count is in the same situation here but count is evaluated at apply time, for_each eraly at plan time, this is odd and it is odd also that count works with terraform 0.13.0 but no more from 0.13.1 and above, this is not consistent !
> 

Both `for_each` and `count` _must_ be evaluated during plan without exception. The only difference is that `count` needs to know the number of values, while referencing a set of strings in `for_each` needs to know all the individual values to create each key. Neither will work in this particular case, because `data.aws_network_interfaces.this.ids` is unknown during plan.

> aws_lb api does not contains ips of the load balancer so it is necessary to use locals to extract ips passing from interfaces (finding from interfaces list conatining load balancer name).

If thats the case, then this config is close to what you want, you just cannot use `data.aws_network_interfaces.this.ids` in the `for_each`expression (even if it was a resource attribute), since it's not known during plan. You could target the initial resources or apply the configuration in phases, but the details of how to do that with these resources are better left to the community forum where there are more users experienced with the AWS provider specifically.
