### ISSUE TITLE
Login Azure with SPN doesn't work in terraform 0.13.2

### ISSUE THREAD

**Issue by mvandewouw** [hashicorp/terraform#26128]
According to documentation 
https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html

It should be possible to set with ARM env vars and with provider block.
With provider block it doesnt work anymore (it does work with ARM env vars)

**Comment by mildwonkey** [comment]
Hi! Thank you for reporting this issue, and I am sorry that you've experienced it.

We'll need to see your configuration files, or a simplified reproduction case, and the crash log in order to figure out what's going on here. Can you please update this ticket with the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Remove any sensitive information first.

Thanks again!

**Comment by pselle** [comment]
Hi there! This has been open for some time and does not yet have a reproduction case or sufficient details to reproduce, so I am going to close it.
