### ISSUE TITLE
"Module Sources" page of the documentation

### ISSUE THREAD

**Issue by giridharjayaraman** [hashicorp/terraform#26154]
Hello,
A possible documentation issue: 
In the "Module Sources" page of the documentation, under the "Terraform Registry" section, i see the below line which tells to use Terraform Cloud hostname even when using Terraform Enterprise. But Terraform Enterprise instances would have their own hostnames right? 

Link: [https://www.terraform.io/docs/modules/sources.html#terraform-registry](https://www.terraform.io/docs/modules/sources.html#terraform-registry)

`If you are using a **Terraform Enterprise instance**, its private registry hostname is the same hostname you use to access the **Terraform Cloud application**. `

**Comment by apparentlymart** [comment]
Hi @giridharjayaraman! Thanks for reporting this and sorry for the slow response.

I agree that this seems confusing. I think it's a result of some changes to the product terminology for Terraform Cloud and Enterprise in recent years, where I think for a time there was a sense that Terraform Enterprise was a hosted version of Terraform Cloud. That doesn't match the current positioning on the product website though: [the self-hosted edition is now referred to exclusively as Terraform Enterprise](https://www.hashicorp.com/products/terraform/editions/enterprise).

For that reason, I'm going to open a PR with a small revision to this text to address the ambiguity you mentioned. A later bigger revision of this page might change the description of this further, but for the moment my motivation is only to address the specific confusing text you reported, because I agree that it seems to say that you'd use `app.terraform.io` to access a Terraform Enteprise instance, which is untrue.

**Comment by giridharjayaraman** [comment]
@apparentlymart Martin, thanks for looking into this and the explanation.
