### ISSUE TITLE
Output depends_on doesn't dependencies don't appear to work as desired.

### ISSUE THREAD

**Issue by wimo7083** [hashicorp/terraform#26165]
### Terraform Version
```
Terraform v0.12.28
```

### Terraform Configuration Files
```hcl
# module1
module "use_module2" {
}
resource google_some_resource "dependent_resource" {
  depends_on = [
    module.use_module2.subnet,
  ]
  // this module uses all outputs from module2, but the firewall + iam are not used. They just have to exist prior to this module is ran.
}
```

```hcl
# module2
resource google_compute_subnetwork_iam_policy "it" {
}
resource google_compute_firewall "fw_egress" {
}
resource google_compute_firewall "fw_ingress" {
}
resource google_compute_subnetwork "it" {
}



output "subnet" {
  depends_on = [
    google_compute_firewall.fw_egress,
    google_compute_firewall.fw_ingress,
    google_compute_subnetwork_iam_policy.it
    google_compute_subnetwork.it
  ]
  value = {
    subnet_id = google_compute_subnetwork.it.id        
  }
}
```

### Debug Output
terraform plan/apply attempts to create the dependent resource `resource google_some_resource "dependent_resource" {` prior to creating the resources in the module.

### Expected Behavior

Resources in the module should be created prior to the dependent resource using the outputs.

### Actual Behavior

Dependent resource fails to complete because the firewall, and iam from the module are not available. 

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform graph` dependency tree doesn't show a dependency on the output variables.

### Additional Context

I'm not sure I understand how dependencies of output variables work; this is either a bug or I'm doing something that can't be done in my version of terraform, or I'm using an output of a map improperly. I've tried the RTFM approach and google but I don't see any reason this shouldn't be working.

Thank you for any suggestions.

**Comment by jbardin** [comment]
Hi @wimo7083 

Your example here should work as intended, so I have a feeling that there's something not present in this configuration that is causing the failure you are seeing. If you could create a complete example to reproduce this we may have a better understanding of what is going on. A trace log of the apply process would also show how the graph is being built, and may indicate why you're not seeing the connection.

It would be good to mention however that using `depends_on` is not normally needed in Terraform configuration, as dependencies should be represented by referencing the required attributes directly. The most frequent exception to this guideline is when resources are created in one module, and looked up via data sources in another independently developed module. Even if that were the case here, I would still attempt to use direct references as often as possible, e.g. `dependent_resource` should use the module outputs rather than listing them vie `depends_on`.

**Comment by jbardin** [comment]
I'm going to close this since we have not heard back. If there is still a problem, you may want to test against the current released version before filing a new issue.

Thanks!
