### ISSUE TITLE
terraform state force push: Failed to write state: cannot import state with serial N over newer state with serial N+M

### ISSUE THREAD

**Issue by gvfnix** [hashicorp/terraform#26179]
Hi.
I stumbled upon a situation when my AWS session token expired while Terraform was in the middle of infrastructure deployment. That ended up in errored.tfstate file in working directory. I tried to import a couple of resources manually, then remembered of state push command. So I removed the resources and tried to execute state push.
```
$ terraform version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.1
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
$ terraform state push errored.tfstate 
Failed to write state: cannot import state with serial 1 over newer state with serial 7
$ terraform state push -force errored.tfstate 
Failed to write state: cannot import state with serial 1 over newer state with serial 7
```
`-force` key does not seem to do what it should.

**Comment by pselle** [comment]
@gvfnix Which backend are you using? The `-force` flag is not available for all backend. I'm suspecting that you're using the S3 backend since I see the AWS provider present, and there's an existing request for that functionality here: https://github.com/hashicorp/terraform/issues/25761

I'm going to close this issue, but if I've misinterpreted and you're using a backend that supports `-force`, please share some more information about your configuration, and I am happy to reopen.

**Comment by gvfnix** [comment]
Yes, that is S3 backend.
Thank you for pointing me out to the opened issue.

**Comment by pselle** [comment]
@gvfnix Actually, I believe I made a mistake associating this with the remote backend work, and that this is a bug and should be classified as such. I've updated the linked issue and will see about getting this looked at.
