### ISSUE TITLE
`terraform state list` with module path doesn't recognize nested modules

### ISSUE THREAD

**Issue by v3n** [hashicorp/terraform#26191]
### Terraform Version

```
0.13.1
```

### Terraform Configuration Files

With a module structure like:

- products
- - distributions 

### Expected Behavior

`terraform state list` should show resources in nested sub-modules when using the filter method.

### Actual Behavior

```
$ terraform state list
[...]
module.products-foo.module.distributions["some-distribution"].data.aws_iam_policy_document.delegated_assume_role_policy["some-distribution-1"]
module.products-foo.module.distributions["some-distribution"].data.aws_iam_policy_document.delegated_assume_role_policy["some-distribution-2"]
module.products-foo.module.distributions["some-distribution"].aws_iam_role.delegated_role["some-distribution-2"]
[...]
```

```
$ terraform state list module.products-foo
module.products-foo.data.aws_acm_certificate.product_cloudfront_distribution_certificate[0]
module.products-foo.data.aws_acm_certificate.scd_cloudfront_distribution_certificate[0]
module.products-foo.data.aws_iam_policy_document.product_s3_bucket_policy
module.products-foo.data.aws_iam_policy_document.replication_iam_policy
module.products-foo.data.aws_route53_zone.service-dns-zone[0]
module.products-foo.aws_cloudfront_distribution.product_cloudfront_distribution[0]
module.products-foo.aws_cloudfront_distribution.scd_cloudfront_distribution[0]
module.products-foo.aws_cloudfront_origin_access_identity.product_access_identity
module.products-foo.aws_iam_policy.replication
module.products-foo.aws_iam_policy_attachment.replication
module.products-foo.aws_iam_role.replication
module.products-foo.aws_route53_record.scd-dns[0]
module.products-foo.aws_s3_bucket.product_bucket
module.products-foo.aws_s3_bucket_object.health_check_object
```

No resources from `module.products-foo.module-distributions` show up.

```
$ terraform state list module.products-foo.module.distributions

Error: Unknown module

The current state contains no module at
module.products-foo.module.distributions. If you've just added
this module to the configuration, you must run "terraform apply" first to
create the module's entry in the state.
```

Terraform believes the module does not exist.

### Steps to Reproduce

1. Create a module hierachy with nested modules.
2. Run terraform apply.
3. `terraform state list` filtering to the submodules.

### Additional Context

Using S3 backend, no additional wrappers or command line flags.

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.4.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-providers/ns1 v1.8.6
```

**Comment by apparentlymart** [comment]
Hi @v3n!

I tried to reproduce this on a development build of Terraform 0.14, with the following root module:

```hcl
module "foo" {
  source = "./foo"
}
```

...and then the following `./foo`:

```hcl
module "bar" {
  source = "../bar"
}
```

...and, finally, the following `./bar`:

```hcl
resource "null_resource" "baz" {
}
```

I ran `terraform apply` to create that resource, and then started by running `terraform state list` to confirm that it would work, as you did:

```
$ terraform state list
module.foo.module.bar.null_resource.baz
```

Requesting the nested module directly worked for me, where it seemed like it didn't work for you:

```
$ terraform state list module.foo.module.bar
module.foo.module.bar.null_resource.baz
```

However, requesting the intermediate module `module.foo` returned the error you saw, I suppose because Terraform found no resource instances in that particular module and so incorrectly reported that it didn't exist at all:

```
$ terraform state list module.foo

Error: Unknown module

The current state contains no module at module.foo. If you've just added this
module to the configuration, you must run "terraform apply" first to create
the module's entry in the state.
```

I then updated `./foo` (the first level of nested module) to include a resource too, so I could see how it would behave when at least one resource was present at that level. After I ran `terraform apply` I got the following list result:

```
$ terraform state list module.foo
module.foo.null_resource.boop
```

This now does seem to match the behavior you saw: it's reporting only the resource directly inside that module, and ignoring the descendant module. I still got a non-empty result from the grandchild module though, which I think still differs from what you observed:

```
$ terraform state list module.foo.module.bar
module.foo.module.bar.null_resource.baz
```

Based on what I've seen here, I count two bugs which could possibly have the same root cause:

1. `terraform state list MODULE` only reports resource instances directly inside the specified module, and not in any descendant modules. That seems to be contrary to Terraform's design intent if we trust the following comment in the code:

    https://github.com/hashicorp/terraform/blob/803c95e5521d33db15b068fe6f0fb5be7ad8b79b/command/state_meta.go#L95-L97

2. When asked to list a module that exists but contains no resource instances, Terraform incorrectly reports that the module doesn't exist and prompts the user to run `terraform apply` to apply it. I'd expect `terraform state list` to either produce no output at all in that case, or to return a tailored error message saying that there are no resource instances in that module or any descendant module beneath it.

Your original report seems to suggest a third bug which I was _not_ able to reproduce:

3. When requesting a list for a grandchild module directly, Terraform incorrectly reports that the module doesn't exist _even if_ it contains resource instances.

...however, I have a suspicion that this third one results from that descendant module having `for_each` set on it, which means that there isn't actually a module called `module.products-foo.module-distributions` and you'd instead need to request `module.products-foo.module.distributions["some-distribution"]` to see the instances in there. Can you give that a try and let me know if you see results when you use the full address for that module?

If so, I think that behavior _is_ defensible per Terraform's current design, but we could consider changing the design so that requesting a listing for an un-indexed module is interpreted as requesting a listing for _all_ instances of that module. I'd likely consider that then to be an enhancement request separate from the bug reports above, but it does seem like reasonable behavior so if someone wanted to implement it at the same time as fixing the bugs above then that would seem fine to me. If it's not straightforward to implement at the same time as the two bugs I reproduced above then we can split it off into a separate enhancement request issue so as not to have it block addressing these two bugs.

**Comment by v3n** [comment]
Thanks for the follow-up and verification of the bug.

I want to address this point:

> If so, I think that behavior is defensible per Terraform's current design, but we could consider changing the design so that requesting a listing for an un-indexed module is interpreted as requesting a listing for all instances of that module. I'd likely consider that then to be an enhancement request separate from the bug reports above, but it does seem like reasonable behavior so if someone wanted to implement it at the same time as fixing the bugs above then that would seem fine to me

I would disagree here, given [the Resource Addressing documentation](https://www.terraform.io/docs/internals/resource-addressing.html):

> An address without a resource spec, i.e. `module.foo` applies to every resource within the module if a single module, or all instances of a module if a module has multiple instances.
