### ISSUE TITLE
Not able to import a terraform module from Azure DevOps.

### ISSUE THREAD

**Issue by msldn** [hashicorp/terraform#26197]
I've added my azure devops VCS provider to my terraform organization and added few modules to the organization few days ago. The modules used to receive new versions as soon as a new tag is committed to the source code.

almost 12 hours ago, I found that terraform is no longer pulling new versions when new tags are created.

when I tried to remove the modules and re add them, I don't see the auto complete list showing the compatible azure devops repos. When I try to put the repo name manually, it fails with an error message similar to the attached one.

https://<org>.visualstudio.com/<project>/_git/<repo>

To check if the url of the repo is valid, I tried adding an already existing module and I get an alread exist message.

**Comment by pselle** [comment]
Hello! Apologies for the delay, this issue didn't get tagged with `bug` so it appears we missed it. However, it appears to be more of a question (and more provider specific, if a bug), than an issue with Terraform Core. Sharing information about our community resources below:

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
