### ISSUE TITLE
CSV driven terraform security groups deployment

### ISSUE THREAD

**Issue by skrishsen** [hashicorp/terraform#26213]
Hi,
Currently, I looking for options to create multiple security groups with different sets of rules data for is driven from a csv file. Assume I have the first 5 rows of rules for security group1 & next 5rows of rules for security group2 or on other case i have multiple sheets in csv file were 1st sheet contains rules of security group1 & second sheet contains rules of security group2. Please help me to achieve my requirement for aws terraform deployment. How can i do it. can someone share sample code.

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
