### ISSUE TITLE
Unable to create a nested folder structure more than 2 levels deep

### ISSUE THREAD

**Issue by adhi93** [hashicorp/terraform#26240]
** Terraform v0.12.18
+ provider.azurerm v2.16.0
+ provider.random v2.3.0**

Not able to create a Nested Directory On Azure Storage account.  It accepts 1 level deep, but for more than 2 it throws the following error:

**name must contain only uppercase and lowercase alphanumeric characters, numbers and hyphens. It must start and end with a letter and end only with a number or letter

  on terraform.tf line 180, in resource "azurerm_storage_share_directory" "example":
 180: resource "azurerm_storage_share_directory" "example" {**

**Comment by apparentlymart** [comment]
Hi @adhi93!

This error seems to be returned from the Azure provider rather than from Terraform itself, and so unfortunately it isn't something we can address in this repository.

I'd suggest starting a topic in [The Azure provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where the participants have more experience with the Azure provider. If you post there, it would help to include a full example of the configuration of `resource "azurerm_storage_share_directory" "example"` so that readers can compare what you've written to their working examples and suggest what might need to change to support the use-case you have.

Thanks!
