### ISSUE TITLE
When modifying a VPC to add IPv6 terraform exits with an error that ::/0 egress entry in the default security group already exists

### ISSUE THREAD

**Issue by takeda** [hashicorp/terraform#26275]
When adding `assign_generated_ipv6_cidr_block = true` to the VPC and also adding an entry like this:

```
  egress {
    protocol   = -1
    rule_no    = 101
    action     = "allow"
    ipv6_cidr_block = "::/0"
    from_port  = 0
    to_port    = 0
  }
```

The terraform (tested on 0.13.2) will error out with the following message:
`Error: Error authorizing security group egress rules: InvalidPermission.Duplicate: the specified rule "peer: ::/0, ALL, ALLOW" already exists`

this is happening with the AWS provider.

**Comment by apparentlymart** [comment]
Hi @takeda,

This error message seems to come from the AWS API rather than from Terraform, so unfortunately I don't think we could do anything to address it in this repository, which is for Terraform Core.

I'd suggest asking about this in a new topic in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), where folks who are more familiar with AWS and the AWS Provider can hopefully explain what you're seeing and suggest a different way to achieve the result you're hoping for. If you do start a topic in the forum, I suggest to show the full configuration for this resource, rather than just the two snippets you showed here, so that readers have the best chance of recognizing what might be causing the problem.

Thanks!

**Comment by takeda** [comment]
@apparentlymart the behavior is a bug though, if it isn't the core terraform, then which repo I should report it? I can't find one for the AWS component.

What I believe is happening, is when I allocate IPv6 CIDR for the VPC, AWS most likely automatically is adding ::/0 to the default security group. Terraform then tries to add that entry and fails. There's no good workaround for this, because when I deploy stack from scratch if I don't add that entry the entry won't be present.

I did the same thing with CloudFormation and it works as expected, both when creating from scratch and updating the stack.

BTW: I also discovered another bug when trying to revert this operation (after CIDR was added to subnets) for some reason TF proceeds with removing CIDR from VPC first before making changes to subnets and of course that fails. Once again this works as expected in CF.
