### ISSUE TITLE
Allow state mv to create new resources REOPENED

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#26289]
References:

https://github.com/hashicorp/terraform/pull/23582

#22301
#23569
#23497

I just got the same error on terraform 0.12.24 which was released in March 2020, which supercedes the date of this fix:

```
/Users/me/bin/terraform-0.12.24 state mv module.folder_sandbox.module.toplevel_type.google_billing_account_iam_member.orgadmin_billing_account_user 'module.folder_sandbox.module.toplevel_type.google_billing_account_iam_member.orgadmin_billing_user["v2"]'
Acquiring state lock. This may take a few moments...

Error: Invalid target address

Cannot move
module.folder_sandbox.module.toplevel_type.google_billing_account_iam_member.orgadmin_billing_account_user
to <invalid>..: the target must also be a whole resource.
```

This is marked as fixed, but seems to still be an issue.

**Comment by alisdair** [comment]
@gtmtech Thanks for reporting this and linking to the relevant issues!

I'm unable to reproduce this issue with Terraform 0.12.29 or 0.13.3. Here's what I tried:

- Create `main.tf`:

    ```hcl
    locals {
      nulls = toset(["foo", "bar"])
    }

    resource "null_resource" "null" {
    #  for_each = local.nulls
    }
    ```

- `terraform init`, `terraform apply -auto-approve` to create the single resource
- uncomment the `for_each` in the resource
- `terraform state mv null_resource.null 'null_resource.null["foo"]'` to move the resource (success)
- `terraform plan` shows that only the resource for `"bar"` needs to be created

Can you explain the difference between your configuration or steps and this one? If you can change these reproduction steps to show what you're seeing, that will help us identify the problem.

**Comment by gtmtech** [comment]
My working theory is that the resources were _originally_ created in terraform 0.12.4, or even 0.11, and now im trying to move them with 0.12.24

I'll do some more investigation and get back to you. 

As a workaround, I had to terraform state rm, and then apply the new hashkey-based resources on top, which worked

**Comment by michyliao** [comment]
I am also experiencing this too

resources created in terraform v0.12.13

**Comment by tkent** [comment]
:wave: Also experiencing this issue using terraform `0.12.20`. 

I may have some relevant information because I didn't hit the issue at first. It showed up after resources were moved back and forth. Here's how it went...

We had a bunch of module definitions that created a single resource:

```
module "mod1" {
  .. 
}
module "mod2" {
  .. 
}
```

After refactoring, the same resources were defined using a single resource block and a `for_each`, e.g.

```
resource_name "the_thing" {
  for_each = some_map
  ...
}
```

I then used a series of `terraform state mv` commands move the resources from their old locations to the new locations. __This worked fine__ and I was able to perform a `terraform plan` which showed no changes.

I then moved the resources back to their old locations using `terraform state mv` again,  because I didn't want roll out the change immediately. And again, __this worked fine__. Doing a `terraform plan` against the old terraform definitions also showed no changes.

Later, when I was ready to make the change, I tried to issue the same `terraform state mv` commands and started receiving errors along the lines of. `...to <invalid>..: the target must also be a whole resource`, just like @gtmtech.

In our case, using `terraform import` to the `for_each` indexed resources works just fine, so I just did that. However, if that didn't work, this would be a real show-stopper.

**Comment by apparentlymart** [comment]
At the time of Terraform v0.12 there was a special property in the state format for tracking what we called the "each mode" of each resource: "no each", "count", or "for_each".

The `terraform state mv` command had a special case in it where if the first argument was a resource address it would check if that resource was already tracked in the state with its "each mode" set to "no each", and if so it would consider the first argument to represent a resource instance address rather than a resource address, so that it would be possible to specify a resource instance address with an index part as the second argument.

That special "each mode" field tended to cause trouble for state-only operations like `terraform state mv`, because it works entirely with the state and not with the configuration and so it can't necessarily keep the "each mode" properly synchronized. We just had [some logic to guess the "each mode" based on the instance key type](https://github.com/hashicorp/terraform/blob/a6720edde58be60cc39101fbb9f42af2639f85fe/command/state_mv.go#L379-L391).

My bet -- though of course I don't really have any way to test it -- is that what caused this bug was the resource's "each mode" getting out of sync somehow, so a later attempt to move it made a wrong assumption about the source address being a whole resource rather than just one instance of a resource.

In response to various other similar quirks we later removed this explicit idea of "each mode" and instead changed the rule so that just the presence of a resource instance without an instance key is enough to trigger the special treatment. There's no longer a separate field that can possibly get out of sync, in modern Terraform.

Therefore I don't think it should be possible to hit this bug any longer, and so I'm going to close this. If you think you've found a similar bug in a modern version of Terraform, please open a new issue to discuss it. Since the mechanism that probably caused this bug is no longer present in modern Terraform, we'll need to start over and debug against the new design anyway, so using this old issue would not be helpful.

Sorry we never definitively got to the bottom of this! I do feel pretty confident that this _specific_ incarnation of the bug is fixed, at least.
