### ISSUE TITLE
Can't remove bad providers from local install

### ISSUE THREAD

**Issue by tcrowleyibm** [hashicorp/terraform#26315]
### Terraform Version
```
Terraform v0.13.2
```

### Terraform Configuration Files
So I did something silly, and I can't figure out how to undo it. I made a guess that there was a Terraform provider for IBM Cloud, and I set up a configuration as follows:

```terraform
terraform {
  required_providers {
    ibm = {
      source  = "hashicorp/ibm"
    }
  }
}
```
Of course, that doesn't exist, and I got a nasty error. Fair enough. I went back and read the documentation.

I then downloaded the correct *community* provider and placed it in the ~/.terraform.d/plugins directory. However, whenever I try to run `terraform init`, it continues to refer back to the `registry.terraform.io/hashicorp/ibm` provider.

I've removed all references to `hashicorp/ibm`, but terraform still seems determined to equate any provider name of `ibm` to be `hashicorp/ibm`. How do I get rid of this association?

My current provider.tf file:

```
provider "ibm" {
  ibmcloud_api_key   = var.ibmcloud_api_key
  generation         = 1
  region             = "us-south"
  iaas_classic_username = var.iaas_classic_username
  iaas_classic_api_key  = var.iaas_classic_api_key
}
```

### Debug Output

```
> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/ibm...

Error: Failed to install provider

Error while installing hashicorp/ibm: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/ibm
```

### Expected Behavior

I have tried several approaches to reset this:
 - delete the directory that contains the terraform scripts
 - completely remove the ~/.terraform.d directory 
 - re-install the plugin
 - run every known permutation of `terraform providers`

Nothing seems to get rid of the quest for `hashicorp/ibm`. Is there some secret config file that I need to update to remove this?

### Actual Behavior

It keeps looking for the wrong provider.

**Comment by alisdair** [comment]
Hi @tcrowleyibm!

It looks like you're using an in-house provider, not from the public registry. That means that you need to specify a provider `source` (e.g. `"terraform.ibm.com/ibm/ibm"` or similar), then move the provider binary into the correct directory (e.g. somewhere below `~/.terraform.d/plugins/terraform.ibm.com/ibm/ibm/…`).

Please take a look at the [0.13 upgrade guide section on using in-house providers](https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers) for the precise details on how to make this work.

Since this isn't a bug in Terraform, I'm going to close this issue. But if you haven't already, I'd recommend [posting on the Terraform discussion board](https://discuss.hashicorp.com/c/terraform-core/27) if you have any further questions—hopefully someone will be able to help!

**Comment by tcrowleyibm** [comment]
@alisdair - thank you for the pointer - it's much appreciated! It turns out I had the incorrect instructions for where to place the provider files. Your pointers above were a great help!
