### ISSUE TITLE
creating aws ebs volumes 

### ISSUE THREAD

**Issue by Jordy694** [hashicorp/terraform#26322]
Hello everyone! 

I'm currently facing an issue with Terraform v0.13.3 
I'm trying to launch 3 core instances and two read replica's with the standard 8gb root block device. Besides that i want to create and attach additional data and log disks in AWS. Unfortunately i'm having the following issue. 
Terraform creates all the instances with a root block device but after it has created the instances my terraform code is not creating the extra data and log disks for the core servers. 
`Error: Error waiting for instance ([i-.......................]) to become ready: InvalidInstanceID.Malformed: Invalid id: "[i-......................]"
	status code: 400, request id: 93428705-60a4-44ed-94d3-fc19ee411de0

Error: Error waiting for instance ([i-....................]) to become ready: InvalidInstanceID.Malformed: Invalid id: "[i-........................]"
	status code: 400, request id: 489d115f-a937-450c-afae-9726337c6e7f

Error: Error waiting for instance ([i-...............]) to become ready: InvalidInstanceID.Malformed: Invalid id: "[i-.......................]"
	status code: 400, request id: 77ae894e-849b-4ccc-bc98-9e73d0b7050a

Error: Error waiting for instance ([i-.............]) to become ready: InvalidInstanceID.Malformed: Invalid id: "[i-...............]"
	status code: 400, request id: d3f08c98-4c4f-45d8-a91b-e4bf7e6b8162

Error: Error waiting for instance ([i-..............]) to become ready: InvalidInstanceID.Malformed: Invalid id: "[i-.....................]"
	status code: 400, request id: aa7f7153-9db1-4968-8e58-dfc433ee6907`

My instance code is as follows:
`resource "aws_instance" "example" {
  provider = aws.deployment
  count = 3
  ami           = "ami-..................."
  instance_type = "t2.micro"
  subnet_id = "subnet-............................"
  key_name = "example"
  vpc_security_group_ids = [aws_security_group.internal.id]
  iam_instance_profile = aws_iam_instance_profile.example.name
  tags = {
    Name = element(var.instance_tags_leader, count.index )
`

My EBS code:
`resource "aws_volume_attachment" "data_disk" {
  depends_on = [aws_instance.example]
  count = 3
  device_name = "/dev/sdd"
  instance_id = "[${element(aws_instance.example.*.id, count.index)}]"
  volume_id = "[${element(aws_ebs_volume.data_disk.*.id, count.index)}"
}

resource "aws_ebs_volume" "data_disk" {
  type = "gp2"
  availability_zone = "eu-west-2a"
  size = 20
}

resource "aws_volume_attachment" "log_disk" {
  depends_on = [aws_instance.example]
  count = 3
  device_name = "/dev/sde"
  instance_id = "[${element(aws_instance.example.*.id, count.index)}]"
  volume_id = "[${element(aws_ebs_volume.log_disk.*.id, count.index)}"
}

resource "aws_ebs_volume" "log_disk" {
  type = "gp2"
  availability_zone = "eu-west-2a"
  size = 10
}`

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform community forum](https://discuss.hashicorp.com/c/terraform-core) or the [AWS Provider Forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
