### ISSUE TITLE
Read when there are no changes

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform#26328]
Sorry for not following the template, but I've created a bug in external provider repo yet now I think this may be a core issue. Please move it if it is true: [https://github.com/hashicorp/terraform-provider-external/issues/45](https://github.com/hashicorp/terraform-provider-external/issues/45)

Please take a closer look at my comment [https://github.com/hashicorp/terraform-provider-external/issues/45#issuecomment-696747742](https://github.com/hashicorp/terraform-provider-external/issues/45#issuecomment-696747742)

**Comment by jbardin** [comment]
Hi @mgzenitech,

This issue is likely caused by a convergence of a few different behaviors. The external provider can only handle results with a map of strings, so `null` may be causing unexpected diffs. Any changes to the data source input, even if it results in the same output may also trigger the data source to be read during plan. The `depends_on` reference can force the data source to appear in plan if there are any changes to the dependency, even if it does not effect the data source.

The good news is that the new data lifecycle changes included in the upcoming 0.14 release will take care of most of these issues, and the extra data reads should no longer appear in the plan.

 - #26270
 - #26285
 - #26321

It's possible there still is some improvement to be made to the provider itself, but I would suggest trying to come up with a standalone reproduction, as I was not able to reproduce the issue with the information provided.

Thanks!
