### ISSUE TITLE
Terraform Validate Does Not Warn On Interpolation In Lists

### ISSUE THREAD

**Issue by rbradley-novetta** [hashicorp/terraform#26331]
### Terraform Version

```
Terraform v0.12.28 and 0.13.3
```

### Crash Output

no crash

### Expected Behavior

terraform validate should raise a warning for deprecated string interpolation inside lists
### Actual Behavior

Running `terraform validate` against the following does not return a warning when interpolation is used inside a list:
```terraform
locals {
  network = "network"
  range = "192.168.0.0/24"
}
provider "google" {
}
resource "google_compute_network" "network" {
  name = local.network
  auto_create_subnetworks = "false"
}
resource "google_compute_subnetwork" "subnetwork" {
  depends_on = [google_compute_network.network]
  name = "subnetwork"
  network = local.network
  ip_cidr_range = local.range
}
resource "google_compute_firewall" "firewall" {
  depends_on = [google_compute_network.network]
  source_ranges = ["${local.range}"]
  name = "firewall"
  network = local.network
  allow {
    protocol = "udp"
  }
}
```
But it does if interpolation is used in a lone string:
```
resource "google_compute_network" "network" {
  name = "${local.network}"
  auto_create_subnetworks = "false"
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

**Comment by alisdair** [comment]
Thanks for reporting this! I can confirm this behaviour exists in 0.13 and 0.14.

We recently added more interpolation deprecations in #26105, but nested expressions are not included in that change. I believe that is a reasonable thing to expect to be validated, especially since we're being more strict with these deprecations in the next 0.13 release.
