### ISSUE TITLE
Incorrect dependency resolution for terraform destroy

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform#26332]
We created some AWS WAF resources in a module, used the module, then removed those resources from the module. However, when deploying the new configuration, Terraform attempts to destroy all the WAF resources at once, despite their being dependencies upon them.

I don't know if it matters , but the state we are trying to manipulate is a 0.11.8 version (using a 0.12.x engine). The desired configuration TF is a HCL2 based file.

### Terraform Version

0.12.29

### Terraform Configuration Files

```terraform
resource "aws_waf_ipset" "ipset" {
  count = "${var.enable_cloudfront_distribution ? 1 : 0}"

  name  = "${var.environment_id}-${var.service_name}"

  ip_set_descriptors {
    type  = "IPV4"
    value = "8.8.8.8/32"
  }
}

resource "aws_waf_rule" "wafrule" {
  count       = "${var.enable_cloudfront_distribution ? 1 : 0}"

  name        = "${var.environment_id}-${var.service_name}"
  metric_name = "WAFRule"

  predicates {
    data_id = "${aws_waf_ipset.ipset.id}"
    negated = false
    type    = "IPMatch"
  }
}

resource "aws_waf_web_acl" "waf_acl" {
  count       = "${var.enable_cloudfront_distribution ? 1 : 0}"

  name        = "${var.environment_id}-${var.service_name}"
  metric_name = "WAFACL"

  default_action {
    type = "ALLOW"
  }

  rules {
    action {
      type = "BLOCK"
    }

    priority = 1
    rule_id  = "${aws_waf_rule.wafrule.id}"
    type     = "REGULAR"
  }

  logging_configuration {
    log_destination = "${var.waf_logs_kinesis_arn}"

    redacted_fields {
      field_to_match {
        type = "URI"
      }

      field_to_match {
        data = "referer"
        type = "HEADER"
      }
    }
  }
}
```

### Expected Behavior

TF would destroy the WAF resources in the right order (waf_acl -> wafrule -> ipset)

### Actual Behavior

All 3 attempt to destroy at same time resulting in errors (can't delete something while something elser has a reference to it.

### Additional Context

The dependencies show up in the tfstate file. 
![image](https://user-images.githubusercontent.com/3877391/93911967-c232f680-fcc8-11ea-940a-6e7bf52ef5be.png)

Based on the content in the referenced issue below, I generated a plan and a dot graph from the plan. I see many other dependencies that exist within the TF module. However, the dependencies between the various WAF resources do not show up. This explains why TF destroys them all at once, but not why the state dependencies do not get reflected in the graph.

### References
https://github.com/hashicorp/terraform/issues/18408

**Comment by jbardin** [comment]
Hi @richardgavel 

In general you should not be using 0.12 to update anything until the state has been updated, which usually means successfully running `apply` before attempting to make any configuration changes. The `depends_on` fields you're referring to in the state are not used by 0.13, and have no effect. 

Can you explain the steps you're taking when you see this? I'm guessing that you are removing these resources from the configuration (rather than using `terraform destroy`), and since the state has not been upgraded, Terraform does not know the order in which to destroy the resources.

**Comment by richardgavel** [comment]
You are correct that the resources are being removed via removal from the configuration (followed by `terraform apply`) rather than a `terraform destroy`.

So you are saying that it is not a good idea to, within a single invocation, change the state from a 0.11.x to a 0.12.x AND remove resources (or even apply any changes)?

**Comment by jbardin** [comment]
That is correct. See the [Before You Upgrade](https://www.terraform.io/upgrade-guides/0-13.html#before-you-upgrade) section of the upgrade guide.

**Comment by jbardin** [comment]
Since this cannot be done with 0.11 state, it appear that things are working as intended.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
