### ISSUE TITLE
after upgrade to terraform version v0.13.3 issue with provider

### ISSUE THREAD

**Issue by madhuryg** [hashicorp/terraform#26361]
2 problems:

- Failed to instantiate provider "registry.terraform.io/hashicorp/aws" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/aws"
- Failed to instantiate provider "registry.terraform.io/hashicorp/random" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/random"

### Terraform Version
Terraform v0.13.3

```
this is my versions file
terraform {
  required_version = ">= 0.12.6, < 0.14"

  required_providers {
    aws    = ">= 2.45, < 4.0"
    random = "~> 2.2"
  }
}...
`

**Comment by deanrock** [comment]
This seems to be releated with Terraform state, not configuration.

Can you try running:
```bash
terraform state replace-provider 'registry.terraform.io/hashicorp/aws' 'hashicorp/aws'
```

**Comment by ericamador** [comment]
I'm having the same issue, and `terraform state replace-provider 'registry.terraform.io/hashicorp/aws' 'hashicorp/aws'` has no effect.

**Comment by OJFord** [comment]
`registry.terraform.io/-/aws`, not `...io/hashicorp/aws`

**Comment by apparentlymart** [comment]
Although this `terraform state replace-provider` command is a common answer for similar errors involving `registry.terraform.io/-/aws`, in this case the error is talking about `registry.terraform.io/hashicorp/aws` already so it seems to be a different problem.

Unfortunately, because this issue isn't using [the bug report issue template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md) there isn't enough information here to investigate further. :confounded: @madhuryg, could you please copy the template from that link into the comment box and answer all of the questions included in comments there? That will give a good starting point to understand what you're seeing, and hopefully to suggest a path forward. Thanks!

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the issue template so we can take a look.
Thanks!
