### ISSUE TITLE
Terraform template_file resource not detecting the changes when we do some changes on template file

### ISSUE THREAD

**Issue by suriya91** [hashicorp/terraform#26362]
Tried to change or update the content of template file (change the vars). i did terraform plan it says "No changes. Infrastructure is up-to-date."
i am using the template as custom data for VM . (data.template_file.custom_data.rendered)

code :
data "template_file" "custom_data" {
template = file("../custom_data/test.tpl")
vars = {
azure_login_identity = "xxxx"
}
}
Terraform v0.13.3

provider registry.terraform.io/hashicorp/azurerm v2.28.0
provider registry.terraform.io/hashicorp/template v2.1.2
hashicorp/template v2.1.2
Did anyone find the same issue and any workaround or bugfix helps ?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
