### ISSUE TITLE
AWS route entries deleted and recreated with no need

### ISSUE THREAD

**Issue by jorgegv** [hashicorp/terraform#26363]
in TF 0.13.0 with AWS plugin: when adding a single route to a route table, all previous routes are deleted and created again in the Route table. Apparently this is due to most fields being returned by AWS plugin as "", but TF expecting them as null.

Example output of TF plan:

```
  # aws_route_table.publicdmz_natgw will be updated in-place
  ~ resource "aws_route_table" "publicdmz_natgw" {
        id               = "rtb-038ecd65c384eae0c"
        owner_id         = "XXXXXXXXXXXX"
        propagating_vgws = []
      ~ route            = [
          - {
              - cidr_block                = "0.0.0.0/0"
              - egress_only_gateway_id    = ""
              - gateway_id                = ""
              - instance_id               = ""
              - ipv6_cidr_block           = ""
              - local_gateway_id          = ""
              - nat_gateway_id            = "nat-0c9912665d18ebfde"
              - network_interface_id      = ""
              - transit_gateway_id        = ""
              - vpc_peering_connection_id = ""
            },
          + {
              + cidr_block                = "0.0.0.0/0"
              + egress_only_gateway_id    = null
              + gateway_id                = null
              + instance_id               = null
              + ipv6_cidr_block           = null
              + local_gateway_id          = null
              + nat_gateway_id            = "nat-0c9912665d18ebfde"
              + network_interface_id      = null
              + transit_gateway_id        = null
              + vpc_peering_connection_id = null
            },
(...)
```
The 0.0.0.0/0 route shown has not changed before the plan. This is replicated in all preexisting rules besides the newly added rule. The new rule is shown as expected.

Expected behaviour: unmodified existing rules are not deleted and recreated, and only modified and/or added routes are changed/created.

**Comment by jbardin** [comment]
Hi @jorgegv 

Thanks for filing the issue, though I have a some questions for clarification:

 - Is this a state that was originally created with 0.13, and does it happen again after the initial change has been applied?
 - If you apply the plan, are these changes actually made, or are they only cosmetic in the plan output?
 - Can you verify the same behavior with the latest release?

**Comment by jorgegv** [comment]
> Hi @jorgegv
> 
> Thanks for filing the issue, though I have a some questions for clarification:
> 
> * Is this a state that was originally created with 0.13, and does it happen again after the initial change has been applied?

The state was created with 0.12.x and has been migrated to 0.13.0. This behaviour also happened with earlier releases (0.12.x).

It does not happen again after applying the change. I.e. If no changes are done, the deletion/recreation does not show. But if I add a new rule, all the rest appear as needing deletion/recreation.

> * If you apply the plan, are these changes actually made, or are they only cosmetic in the plan output?

I can't say. For example, if I add a rule to a given route_table, the "plan" output shows the deletion/recreation that "will be done", but then command output says:

```
aws_route_table.partnerdmz_igw: Modifying... [id=rtb-0f83ff7703bdbc8df]
aws_route_table.partnerdmz_igw: Modifications complete after 1s [id=rtb-0f83ff7703bdbc8df]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
Releasing state lock. This may take a few moments...
```

> * Can you verify the same behavior with the latest release?
It's a bit difficult for me, we are several people in the team and we have had some problems with upgrading state in the past, when someone migrated to a version and the others did not.

**Comment by jbardin** [comment]
Thanks @jorgegv

This appears to result from the provider or the plugin SDK not being able to properly normalize the set values, and assigning empty strings to the attributes that should be left null. Because the set data structure is defined by the sum identity of its values, all these changes show up as the entire set being changed. The extra entries should not be effecting the actual resource, since in the end they should be assigning the same route table entries. If they are causing a problem, I would suggest filing an issue with the AWS provider. The AWS provider team would we able to test if they can effect this behavior, or whether fixing this particular behavior will require waiting for the next major SDK version.

It may be more advantageous to use individual route resources rather than the in-line entries, but I'm not familiar enough with the provider to know if there is any drawback to that strategy. The [AWS Provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) may be a better place to ask about that.

Thanks
