### ISSUE TITLE
keybase decrypt not working on windows

### ISSUE THREAD

**Issue by noelmcgrath** [hashicorp/terraform#26377]
### Terraform Version

```
Terraform v0.12.28
```

### Terraform Configuration Files

```
n\a
```

### Debug Output
n\a

### Crash Output
n\a

### Expected Behavior
From [aws_iam_access_key resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key)
Running the following will work:
terraform output encrypted_secret | base64 --decode | keybase pgp decrypt

### Actual Behavior
Results in:
```
/usr/bin/base64: invalid input
- ERROR  (code 1505)
```

### Steps to Reproduce
Keybase and key configured
I used the example [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key)
1. `terraform init`
2. `terraform apply`
3. `terraform output encrypted_secret | base64 --decode | keybase pgp decrypt`

### Additional Context
Works on unix, Confirmed in community question and I have also confirmed by running same command on linux box

### References
[community question](https://discuss.hashicorp.com/t/aws-iam-access-key-encrypted-secret-base64-decode/14531)

**Comment by apparentlymart** [comment]
Hi @noelmcgrath,

Based on our discussion in the community forum so far this feels to me like weird behavior in the `base64` command rather than something Terraform itself is doing, so I'm going to close this for now and we can continue to discuss it in the community forum, just to get it off the radar of the rest of the Terraform team. If we can figure out there how this odd behavior is attributed to Terraform itself then I'll reopen it. Thanks!
