### ISSUE TITLE
Publish a module to a private registry on terraform cloud using Azure devops services fails

### ISSUE THREAD

**Issue by daniel-anova** [hashicorp/terraform#26386]
When trying to setup a private module registry in terraform cloud using Azure Devops Services fails due to it not being able to find any repo.

Instructions where followed as documented here:
https://www.terraform.io/docs/cloud/vcs/azure-devops-services.html
 
More then one person in my organization attempted to create a connection without success.

**Comment by apparentlymart** [comment]
Hi @daniel-anova,

From what you've linked here I think this is a Terraform Cloud question rather than a Terraform CLI issue. The folks that work on Terraform Cloud don't typically monitor issues in this repository because it's for the Terraform Core open source project.

I'd suggest referring to the [HashiCorp Support site](https://support.hashicorp.com/hc/en-us) for help with Terraform Cloud. It includes information on how to open a request with the HashiCorp support team, who are better equipped to help with the HashiCorp hosted services.

Because this doesn't seem to be a problem that we could address with changes to the code in this repository, I'm going to close this issue. Thanks!
