### ISSUE TITLE
Terraform import command unable to parse arguments with additional flagged arguments

### ISSUE THREAD

**Issue by chchadha** [hashicorp/terraform#26381]
When attempting to import an existing resource into terraform, the import command fails to parse the arguments. Please see the example below: 

terraform import azurerm_resource_group.rg /subscriptions/....../..../some-rg -var-file="pathtotfvarsfile" 

Error:
The import command expects two arguments.
Usage: terraform import [options] ADDR ID

This issue occurs regardless of how I pass in vars or add any other flag. The only way I can get import to work is without any additional arguments and pass them in when asked, which makes things difficult when automating the process. 

Terraform using PowerShell v0.13.2

**Comment by apparentlymart** [comment]
Hi @chchadha,

Terraform expects options to appear before positional arguments, so I think the following should work to get the effect you wanted:

```
terraform import -var-file="pathtotfvarsfile" azurerm_resource_group.rg /subscriptions/....../..../some-rg
```

Could you try that and let me know what happens? Thanks!

**Comment by apparentlymart** [comment]
Hi again, @chchadha!

Since I didn't hear back from you after my earlier comment, I'm going to close this in the hope that what I suggested helped you get things working. If you have any further questions, please feel free to start a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core).
