### ISSUE TITLE
VPC Endpoint Policy Bug

### ISSUE THREAD

**Issue by joechchung** [hashicorp/terraform#26397]
We applied a policy to our VPC endpoint, we want to now remove it so we removed the `policy` pararmeter but it does not go to the default like stated in the docs: 

```
policy - (Optional) A policy to attach to the endpoint that controls access to the service. Defaults to full access. All Gateway and some Interface endpoints support policies - see the relevant AWS documentation for more details. For more information about building AWS IAM policy documents with Terraform, see the AWS IAM Policy Document Guide.
```

We applied this policy to the VPC endpoint in Terraform:
```
{
    "Statement": [
        {
            "Action": [
                "events:*"
            ],
            "Condition": {
                "StringLike": {
                    "aws:PrincipalOrgID": "random-orgID"
                }
            },
            "Effect": "Allow",
            "Principal": "*",
            "Resource": "*",
            "Sid": "bug-submission-vpc-endpoint-policy"
        }
    ]
}
```

We tried to remove it by removing the `policy` parameter, but Terraform does not pick up the change and does not change the policy (which should be reset to Full Access):
```
{
    "Statement": [
        {
            "Action": "*",
            "Effect": "Allow",
            "Resource": "*",
            "Principal": "*"
        }
    ]
}
```

Terraform version: `0.12.28`

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to close this issue because it's not something we can fix - please re-open this in their GitHub repository at https://github.com/terraform-providers/terraform-provider-aws.

 Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
