### ISSUE TITLE
provider configuration local is not finding the locally provided provider plugins

### ISSUE THREAD

**Issue by syparth** [hashicorp/terraform#26416]
Hi I am trying to run ./terraform init
below is .terraformrc file 
```
provider_installation {
  filesystem_mirror {
    path = "/proj/dir/.terraform/plugins/"
  }
}
```

and the main.tf is 

```
terraform {
  backend "gcs" {

  }
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "~> 3.4.0"
    }
  }
}
provider "google" {
  project = "myproject"
}

```
and at the location - /proj/dir/.terraform/plugins/registry.terraform.io/hashicorp/google/3.41.0/linux_amd64

I have copied the gcloud provider - terraform-provider-google_v3.41.0_x5

But the init command throws below error, 

> Error: Failed to query available provider packages
> 
> Could not retrieve the list of available versions for provider -/google:
> provider registry.terraform.io/-/google was not found in any of the search
> locations
> 
> - /proj/dir/.terraform/plugins/
> 
> 
> Error: Failed to query available provider packages
> 
> Could not retrieve the list of available versions for provider
> hashicorp/google: no available releases match the given constraints ~> 3.4.0

Have I done anything wrong with folder structure ?

**Comment by apparentlymart** [comment]
Hi @syparth!

In order to investigate this we'll need the information that is requested in [our bug report template](https://raw.githubusercontent.com/hashicorp/terraform/master/.github/ISSUE_TEMPLATE/bug_report.md). Could you copy that text into the comment box and fill in the information it's requesting? Among other things, that would include the trace log output from the provider installer which will then hopefully help explain what the filesystem mirror installation method is doing here.

Thanks!

**Comment by apparentlymart** [comment]
Hi @syparth!

Since you didn't respond to my previous comment I'm going to close this under the assumption that you found a solution to the problem. If you want to discuss this more or have any other questions, please start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
