### ISSUE TITLE
Failing E2E test: TestInitProviderNotFound

### ISSUE THREAD

**Issue by OwenTuz** [hashicorp/terraform#26411]
`TestInitProviderNotFound` fails with current master branch.
Looks like this is just due to a typo in the test, I will raise a PR against this issue to fix.

### Terraform Version
```
v0.14.0-dev
```
### Steps to Reproduce
- Checkout master branch
- Run `TF_ACC=1 go test ./command/e2etest` to run E2E tests with network access allowed

### Test output
```
--- FAIL: TestInitProviderNotFound (1.16s)
    --- FAIL: TestInitProviderNotFound/local_provider_not_found (0.06s)
        init_test.go:361: expected error message is missing from output:

            Error: Failed to query available provider packages

            Could not retrieve the list of available versions for provider
            hashicorp/nonexist: provider registry.terraform.io/hashicorp/nonexist was not
            found in any of the search locations

            -
            /private/var/folders/vm/r5s3k8mx5n5b60ytfdngfgnc0000gn/T/binary-e2etest201542719/empty

FAIL
FAIL	github.com/hashicorp/terraform/command/e2etest	26.718s
FAIL
```

**Comment by danieldreier** [comment]
Thanks for reporting - I've run the E2E test as described and saw the same error on my mac

**Comment by apparentlymart** [comment]
I think the root problem here is that on MacOS the temporary directory is a much longer prefix than the `/tmp` we typically see on other Unix-like systems, and so the path in the error message is long enough to be subject to the error message word wrapping.

I think one tactical way to address this would be to add two spaces in front of the `-` "bullet" of each of the list items, which I believe will make the diagnostic renderer treat it as preformatted text and not try to wrap it. It's not a super elegant answer, but since we know that the only values that appear there are single paths I think it's fine to never try to word-wrap them, and instead let the terminal do its own character-based wrapping if the path gets too long.

**Comment by OwenTuz** [comment]
Ah, amazing - got called away before I could look further into it. Thanks.

That sounds entirely reasonable @apparentlymart, to be honest it's a bit of a silly way to have to fail a test so I don't think the fix was ever going to be particularly elegant. But if it gets people working consistently I'll take it.

**Comment by OwenTuz** [comment]
(PR updated and passing CI)
