### ISSUE TITLE
Error: Incompatible provider version  No compatible versions of provider registry.terraform.io/terraform-providers/azure were found.

### ISSUE THREAD

**Issue by soumyaraja** [hashicorp/terraform#26415]
Hi,
Terraform init failed for azure  terraform version 0.13.3.
provider "google" {
  version = "~> 3.19.0"
  credentials = file(var.gcp_credentials_file_path)
  project = var.gcp_project_id
  region = var.gcp_region

  }

  provider "aws" {
  version = "~> 3.0"
  region  = "us-west-2"
  }

  provider "azurerm" {
  version = "~>2.0"
  features {}
}

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core, because we don't maintain the Azure provider. I'm going to close this, and your next step is to open an issue in the Azure provider GitHub repository at https://github.com/terraform-providers/terraform-provider-azurerm. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by danieldreier** [comment]
Actually, on reflection, I don't think this is an azure issue - this is likely a configuration issue. You need a required providers block like:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.29.0"
    }
  }
}
```

If you need additional support, please use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by soumyaraja** [comment]
Thanks Danial for your promptness and help - but unfortunately  it didn't
work for me - i will raise an issue with azure.

BR// Soumya

**Comment by danieldreier** [comment]
Thanks! Good luck!
