### ISSUE TITLE
AWS Batch compute environment needs recreating after launch template change

### ISSUE THREAD

**Issue by microbioticajon** [hashicorp/terraform#26425]
Hi Guys,

Im having trouble applying changes to my AWS Batch configuration. As part of my batch cluster I use a custom Launch Template for the instances in the compute environment. However when I make a change to the Launch Template the Batch compute environment remains un-modified. 

According to the AWS Batch docs, if the Launch Template is updated with a new version the entire compute environment needs to be destroyed and rebuilt:
[https://docs.aws.amazon.com/batch/latest/userguide/launch-templates.html](https://docs.aws.amazon.com/batch/latest/userguide/launch-templates.html)

> AWS Batch does not support updating a compute environment with a new launch template version. If you update your launch template, you must create a new compute environment with the new template for the changes to take effect.

As a result, the only way to apply changes to the Launch Template is to manually destroy the compute environment before applying the plan.

I performed a quick search and I cannot find a way to trigger a forced re-create on a resource: https://github.com/hashicorp/terraform/issues/8099

Any fixes, help or work-arounds would be greatly appreciated.

Im using the following version of Terraform.

```terraform --version
Terraform v0.13.3
+ provider registry.terraform.io/-/aws v3.8.0
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/null v2.1.2```

### Debug Output
No debug output

### Crash Output
No crash output

### Expected Behavior
aws_batch_compute_environment resource using a modified aws_launch_template resource is forced to be recreated

### Actual Behavior
aws_launch_template resources are updated in-place but aws_batch_compute_environment resources remains unmodified


### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #8099

**Comment by danieldreier** [comment]
Hello! 

It looks to me like you're asking for help with a Terraform provider, rather than reporting a particular bug. This is the GitHub issue tracker for tracking bugs and enhancements in Terraform Core, rather than for general questions, and the questions we can help with are for general Terraform usage, rather than for the AWS provider, which is maintained by a different team. While we can sometimes help with certain simple problems here, it's better to use [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. There will be plenty of people in that forum who are familiar with the AWS provider. The GitHub issues here are monitored only by our few core maintainers, and we don't maintain the providers so cannot help with this issue.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request with Terraform Core, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
