### ISSUE TITLE
remote_file resource

### ISSUE THREAD

**Issue by bcsgh** [hashicorp/terraform#26434]
### Current Terraform Version

"0.12 and newer" (at least that's what the docs refer to themselves as)

https://www.terraform.io/docs/provisioners/file.html

### Use-cases

What I want is a `remote_file` resource that manages file content on (potentially *unmanaged*) hosts.

I have am external host (e.g. a server in a rack, a RasberyPi somewhere in the antic, an industrial control in a shed 30 miles from nowhere, a desktop under my desk, some endpoint specified by a third party government agency, etc. ... which is to say; something that if fundamentally outside the scope of what terraform can aspire to create and deploy) and I want to use tarraform to manage content placed there. For example, I want to SCP/FTP/HTTP POST/git/RCP/[FToAC](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers) files onto it.

### Attempted Solutions
The only things that even look like they are worth considering show up under provisioners, but those seems to start with the assumption the target host is "the newly created resource" that terraform is managing. In this case it isn't, and never will be, managing the thing I want to place files on.

### Proposal
```
resource "remote_file" "foo" {
  source = "local.path"
  destination = "/remote/path"
  protocol = "SCP"
  // ...

  scp {
    host = "example.com"
    user = "root"
    password = "12345"  # And change the combination on my luggage!
  }
}
```

... or something vaguely like that.

[Note: this *might* be better as part of the `external` provider, but I'm not sure it really fits there as it seems to be dealing with "actions outside terraform" where as the point of this would be to bring inside terraform actions on thing outside it.]

**Comment by apparentlymart** [comment]
Hi @bcsgh,

It would in principle be possible to write a provider called `remote` that offers a resource like this. An alternative design would be to write multiple different providers that each handles one remote file access protocol, like having `ssh`, `ftp`, `http`, `git`, etc providers, where each one would then only have to worry about the details of one specific protocol.

Providers are developed separately from Terraform and anyone can write a provider and publish it on [the Terraform Registry](https://registry.terraform.io/). The [Extending Terraform](https://www.terraform.io/docs/extend/) section has information on how to write a provider, and the Terraform Registry docs have a section on [Publishing Providers](https://www.terraform.io/docs/registry/providers/publishing.html) for public consumption.

Because providers don't belong directly in this repository, there isn't really any action we could take in this repository to make this issue be "done", so I'm going to close it only to represent that this isn't the place for such work to occur, not to suggest that this isn't a good idea. For HTTP in particular I should note that there is already [an `http` provider](https://github.com/hashicorp/terraform-provider-http) that can make `GET` requests, so it could be reasonable to add to it a new `http` managed resource type that also knows how to `PUT` or `POST` objects to remote servers. For the other protocols, I'm not sure if there are already providers published in the registry but if there are you should hopefully be able to find them in [the registry providers index](https://registry.terraform.io/browse/providers).

Thanks for suggesting this!

**Comment by bcsgh** [comment]
One provider, many providers. Same difference. I've little preference between them.

While I already knew that community created providers are a thing, I'm not in a position to contribute a provider (for one thing, I find the Go programming language activity infuriating to work with). Also, this seems like the kind of thing that would be best provided by an "official provider"; easier to convince management it's not a security risk, easier to install(?), less likely to turn into abandon-ware, less likely to be buggy, less likely to be an actual security risk or trojan, etc.

So, where do I file a FR against "the set of official providers" asking for the creation of new providers?
