### ISSUE TITLE
0.13.x count on local variable?

### ISSUE THREAD

**Issue by lifeofguenter** [hashicorp/terraform#26452]
the following snippet:

```
locals {
  create_nlb = var.create && var.nlb_arn != null ? true : false
}

resource "aws_lb_target_group" "nlb" {
  count = local.create_nlb ? 1 : 0

  ...
}
```

will fail with:

```
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

However there should be no unknown resource?

**Comment by jbardin** [comment]
Hi @lifeofguenter 

While you are correct that the local value is defined within the module, it is derived from variables which are not present here. Seeing how one of the variables names contains `arn`, I would wager that is being created by an aws resource, and is not available yet during plan. If you have a more complete example where you can ensure the values are known, please file a new issue with all the information requested in the template.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
