### ISSUE TITLE
Using env vars on a workspace that accesses 2 subscriptions fails

### ISSUE THREAD

**Issue by eodonoghue** [hashicorp/terraform#26457]
### Terraform Version
v0.12.28

**Comment by eodonoghue** [comment]
Hi @jbardin - why was this issue closed? I cannot see the comments I had on this issue unless I click on edit comment so for some reason it did not create properly, maybe this the reason it was closed? I have pasted in the full text below. 

### Terraform Version
v0.12.28


### Terraform Configuration Files

**Comment by jbardin** [comment]
@eodonoghue 

The issue was closed because there was no content, and your reply here also has no additional information. If I attempt to edit each post myself, it seems you've commented out all the information in both boxes. The content and title also seem identical to the other issue you opened here: https://github.com/hashicorp/terraform/issues/26453

If you have a separate issue, please open a new one and verify all the information is available in the post.

Thanks!

**Comment by eodonoghue** [comment]
Thanks James,

Yes, it is the same issue, I had problems creating the first one and didn’t realize had saved – thank you
