### ISSUE TITLE
Failure following Backend-Config change

### ISSUE THREAD

**Issue by kaizoku0506** [hashicorp/terraform#2645]
I attempted to modify the backend config to allow for self-signed certs when connecting to OpenStack using:

```
terraform remote config -backend=http -backend-config="address=https://URL" -backend-config="skip_cert_verification=true"
```

I am now getting the following error message:

```
Error while performing the initial pull. The error message is shown
below. Note that remote state was properly configured, so you don't
need to reconfigure. You can now use `push` and `pull` directly.

Error reloading remote state: Decoding state file failed: invalid character '<' looking for beginning of value
```

This occurs both with my .tf config file and with the testopenstack.tf file found here:  https://gist.githubusercontent.com/matjohn2/250cbed0feaf74d44463/raw/549708e628ed1efdbf95f7e0dfd800c664de872c/gistfile1.txt

**Comment by mitchellh** [comment]
This is probably because openstack is returning a bogus return value. Are you able to get the value that it is returning? It looks like it might be returning HTML

**Comment by fabiendelpierre** [comment]
Hi there,
I'm encountering the same issue, trying to use an Openstack Swift container as an HTTP endpoint for `terraform remote`, for lack of a better option (can't use Atlas or S3, don't have Consul). The only difference is I'm not using HTTPS. Since I'd rather not implement my own REST endpoint, I'd really like to help figure this out. How might I get the value that you're asking for? All I could think of to get it was `tcpdump`, the HTTP headers are readable, but the content isn't since it's gzip-encoded.

**Comment by mitchellh** [comment]
Switching tags on this from core to "openstack" even though its not in the provider proper because it would still require an OpenStack cluster to test this against which isn't the easiest to get hold of.

**Comment by mitchellh** [comment]
We've fixed many OpenStack remote state bugs. If this is still an issue please open a new issue. Thank you!

**Comment by jkkathi1** [comment]
Having the same issue . Not related to open stacked.  Have stored some varilable values with in a file and tyring to call this file through backend local and  terraform_remote_state.  I know that the file is being read since the first charter in that file starts with p . The error i get when running 

terraform apply  gives

Error: Error loading state: Decoding state file version failed: invalid character 'p' looking for beginning of value
