### ISSUE TITLE
Optimize Terraform Registry for Google Search SEO

### ISSUE THREAD

**Issue by ryanpodonnell1** [hashicorp/terraform#26454]
### Current Terraform Version
N/A

### Use-cases
Prior to the Terraform Registry documentation update, it was fairly easy to locate terraform resources via a quick google search. After the revamp it seems like the SEO for the terraform documentation has taken a major dive on google.

Example:

Google search: `aws_kms_key`

This used to take me right to the correct terraform documentation as one of the first results but now brings up a bunch of non official documented sites with Hashicorp nowhere in sight:

![image](https://user-images.githubusercontent.com/48141361/94829951-0ca72800-03d9-11eb-8a57-a9671f3210a8.png)

### References
example google search:

```
https://www.google.com/search?q=aws_kms_key&oq=aws_kms_key&aqs=chrome..69i64j69i59j0l6.471j0j7&sourceid=chrome&ie=UTF-8
```

**Comment by apparentlymart** [comment]
Hi @ryanpodonnell1,

The Terraform Registry team doesn't generally monitor the issues in this repository, but I happen to know from other discussions that they are aware of the problem and are working on it. It is likely that some of this is a temporary result from a sudden change in the canonical URL for lots of different pages at once, but the registry team is monitoring the progress of the reindexing and will take other actions as needed to restore these as the highest-ranking results for searches for them.

Since this repository is for issues in Terraform CLI/Core, I'm going to close this just because there is no action we could take in this repository that would cause this issue to be "done", and so otherwise it would likely just sit here open forever. However, I do appreciate you taking the time to report it.

In the meantime, I've heard (and observed myself) that other search engines such as [DuckDuckGo](https://duckduckgo.com/) are not encountering such problems. I know that's not ideal when your muscle memory is to search Google, but may still be faster than navigating directly to a particular resource type from the root of the registry.

**Comment by ryanpodonnell1** [comment]
@apparentlymart yeah no problem. Didn't really know where else to go with this, so figured this would be stop #1
