### ISSUE TITLE
Should implicit dependencies still work in 0.13.x?

### ISSUE THREAD

**Issue by gchappell99** [hashicorp/terraform#26467]
### Terraform Version

```
v0.13.4
```

### Terraform Configuration Files

```terraform
module "core" {
  // this module has an output called "storage-account-name"
  source              = "git::ssh://...."
  resource_group_name = var.resource_group_name

  name = var.name
  tags = var.tags
}

module "redis" {
  // this module accepts the "storage-account-name" variable
  // this is used within the redis module to use an Azure Storage Account creating in the core module as a data source
  source = "git::ssh://..."

  resource_group_name = var.resource_group_name
  storage_account_name  = module.core.storage-account-name

  name = var.name
  tags = var.tags
}

```

### Debug Output
I'll provide this soon once I've been able to make sure there's nothing sensitive

### Expected Behavior
This module works fine when tested/deployed with v0.12.29 - the order of operations is correct

Upgrading from v0.12.29 to v0.13.4 should have resulted in no changes of behaviour; this module should have been able to run an `apply` successfully. The implicit dependency created by using the `core` module output as a `redis` module variable should have enforced the correct order of operations, as with v0.12.29.

### Actual Behavior
It seems that the modules try to run concurrently, and the `redis` module tries to read data from the Storage Account created by `core` before it actually exists.

The below error message is received:
```
Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1;
Error: Error: Storage Account "bnngmtftestssir9rafdu" (Resource Group "bnngmtf-terratest-tf-module-azure-spring-si-redis-9rafdu-RG") was not found

  on .terraform/modules/redis/main.tf line 14, in data "azurerm_storage_account" "storage_account":
  14: data "azurerm_storage_account" "storage_account" {

}
    apply.go:104:
        	Error Trace:	apply.go:104
        	            				spring_si_redis_test.go:71
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1;
        	            	Error: Error: Storage Account "bnngmtftestssir9rafdu" (Resource Group "bnngmtf-terratest-tf-module-azure-spring-si-redis-9rafdu-RG") was not found

        	            	  on .terraform/modules/redis/main.tf line 14, in data "azurerm_storage_account" "storage_account":
        	            	  14: data "azurerm_storage_account" "storage_account" {

        	            	}
        	Test:       	TestSpringSIRedis
```

#### Workaround
If I use the new explicit module dependencies by making the `redis` module explicitly depend on that output:
```
module "redis" {
  depends_on = [
    module.core.storage-account-name,
  ]
  source = "git::ssh://..."
```
Then the module can be applied successfully. But this seems like it should not be necessary because there should already be the exact same dependency expressed implicitly by the fact that this `core` output is already used as an input into `redis` and my concern is that this dependency could be "too rigid" and may cause other problems down the line

**Comment by jbardin** [comment]
Hi @gchappell99 

Without the full configuration it's hard to determine what exactly is happening here. My guess is that you are experience the behavior described in #25961. 

There have never been "implicit" dependencies in Terraform, however particular behavior emerged from how resources are evaluated during the refresh walk. Since this wasn't intended behavior, it wasn't apparent that configurations were depending on it, and there were no tests to check if the behavior had changed.

Since this type of dependency only worked during initial resource creation, and would break down when resources were replaced or updated, it's not recommended to rely on data sources being deferred when even if there configuration is known statically. In most cases you should be able to either pass the desired resource attributes around directly, or provide the data source with a computed output to create the desired ordering.

Since this is an often misunderstood situation with data sources, we have opted to explicitly handle this type of reference in 0.14, and make it a supported behavior. This is only possible in 0.14 because it removed the separate refresh phase, where data sources could not always be correctly evaluated.

Thanks!

**Comment by gchappell99** [comment]
Hmm, that kind of makes sense - perhaps we've been working under a misunderstanding this whole time...

> Explicitly specifying a dependency is only necessary when a resource relies on some other resource's behavior but doesn't access any of that resource's data in its arguments.

source: https://www.terraform.io/docs/configuration/resources.html

To me, that reads as though having the reference to a module output should have been enough, but I guess this was a combination of language (I was considering a module as a "resource" when maybe it actually isn't?) and it just worked accidentally for other reasons. I will commit the change to include `depends_on` which allows the terratest tests to pass successfully and watch out for any issues the next time this stack is deployed anywhere. Thanks for the link to the previous bug for context too
