### ISSUE TITLE
Crash during apply

### ISSUE THREAD

**Issue by jwilmoth-nc** [hashicorp/terraform#26472]
I was applying a small change to a module and the plan succeeded, but running apply resulted in a crash.  I tried a couple of times (after force unlocking the state) and got the same error.  Ultimately, I destroyed the stack and was able to successfully recreate with `apply`.

### Terraform Version

```
Terraform v0.13.3
```

### Crash Output
[crash.log](https://github.com/hashicorp/terraform/files/5319333/crash.log)

### Expected Behavior
Apply updated resources

### Actual Behavior
apply crashed terraform

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

### Additional Context
All commands (plan/apply) were run with terragrunt v0.25.1.

**Comment by pselle** [comment]
Hi @jwilmoth-nc, to better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details? A simplified configuration would help us reproduce this issue so we can fix it -- so we can understand what the state and config before you ran your `plan`/`apply`. 

For future readers, it looks like the panic is coming from an invalid address, as if a `ResourceInstanceChange` has a `nil` `Action`. Finding out how this can happen would be a pointer to the source of the bug.

Thanks.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
