### ISSUE TITLE
Feature request: addition of `env` and `envexists` functions to interrogate envvars.

### ISSUE THREAD

**Issue by clockworksoul** [hashicorp/terraform#26477]
### Current Terraform Version

```
$ terraform version
Terraform v0.13.4
```

### Use-cases

We found ourselves in a situation in which we have to slightly modify our Terraform's behavior according to whether or not it's being applied locally. We tried multiple solutions, but none were entirely adequate, and have for now settled on a hack with an uncomfortable level of complexity.

### Attempted Solutions

We tried using variables, but we were frequently confounded by `Result depends on values that cannot be determined until after "terraform apply".`

We then tried using marker files and the `fileexists` function, but this required us to either uniquely label our production environment (which strikes us as asking for trouble) or mark all of our developer environments. This is doubly complicated by the fact that we're working within Terraform Enterprise for both cases, which makes it a pain to add files to the Terraform environment in a discriminated way.

Since functions are evaluated during configuration parsing rather than at apply time, it seemed that the correct approach would be label the environment and use a function to check for that label.

### Proposal

I propose the addition of two functions, `env` and `envexists`. These would be analogous to `file` and `fileexists`, except that they would provide the value and existence, respectively, of an environment value.

### References

This seemed like something I imagine has already been discussed, but my search didn't turn anything up. It's very possible I missed something obvious though.

Edit: I apologize for getting ahead of myself, but I have already implemented the feature as proposed for your consideration: https://github.com/hashicorp/terraform/pull/26478

**Comment by mariusvniekerk** [comment]
This is of particular importance when using an assume_role pattern when using the aws  provider and wanting to import a resource.

In terraform enterprise/cloud we use a particular role that is granted sufficient permissions to create / destroy resources as needed, but do not wish to expose the ability to assume said role to regular users.

This also applies to various external tools like tflint etc. 

Using an environment variable based check would allow us the easily switch out which roles are assumed in tfe vs locally.

**Comment by apparentlymart** [comment]
Hi @clockworksoul! Thanks for sharing this proposal.

Back when introducing the `TF_VAR_*` convention for using environment variables to set input variables, the team at that time (which didn't yet include me) intentionally constrained the use-case _only_ to setting root module input variables because where possible Terraform's language design tries to avoid situations where a module's definition depends on anything other than its own source code and its input variables.

I think that concern still applies, so before moving forward with this I'd like to first talk about the possibility of addressing your use-case using the existing input variables mechanism, possibly using the `TF_VAR_*` environment variable scheme if the data in question is best provided via environment variables.

You mentioned in your proposal that you tried to use variables but saw an error message in that case. In order for us to understand better what you saw, would you mind sharing an example of the configuration you tried which encountered that error and of the full error message Terraform produced in that case?

Given the previous design decision about constraining what "ambient" local state modules should be able to depend on, I'd rather exhaust possible solutions involving the mechanisms that already exist first, and only then consider introducing an entirely new pattern.

---

With the above all said, it is technically possible today to implement a Terraform provider with a data source that returns values from its own environment, which it would have in turn inherited from the Terraform process. That means it's already possible to get this done today without any modifications to the Terraform language, albeit in a less convenient and more clunky way.

We have existing precedent of allowing things that are not typically recommended for pragmatic reasons, but we tend to try to do it in a way that makes it clearer that it's a pragmatic workaround rather than a recommended design pattern. A provider with suitable disclaimers in its documentation tends to feel "less recommended" than a built-in function, in our experience.

Another _technical_ advantage of implementing it as a data source means that it can solve a problem that the function formulation would otherwise have to somehow address: what to do if the environment variable value changes between plan and apply. It being a data source would answer that question clearly: it would be either read during plan _or_ during apply, with the difference visible in the plan output, and in the apply-time case expressions referring to it would correctly produce "unknown" (that is, `(known after apply)`) during the planning phase, ensuring that it meets all of the invariants Terraform relies on.

Given that third-party providers can now be published into [Terraform Registry](https://registry.terraform.io/), that offers a potential path forward that doesn't require any changes to Terraform Core at all, and is also consistent with how Terraform modules _typically_ import data from outside of their own source code.

**Comment by bflad** [comment]
Another consideration with providing the direct ability to read environment variables and perform state storage with them is that it can be a potential avenue for credential exfiltration. Having the ability to output the value of well known environment variables, such as `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`, `GITHUB_TOKEN`, etc., would (and should 😄 ) be a security concern for environments using that credential strategy.

**Comment by clockworksoul** [comment]
@apparentlymart Thank you for your very thoughtful response. We've put together [a very, very basic provider for this functionality](https://github.com/clockworksoul/terraform-provider-env), and are in the process of testing it against our use case.

@bflad Excellent point, and very worth considering. Would you consider there to be a similar concern with the existing `file` function and the `~/.ssh` directory?
