### ISSUE TITLE
Codepipeline doesn't hash github token

### ISSUE THREAD

**Issue by gauravachatrath** [hashicorp/terraform#26488]
Hi,

I am not sure it is a bug or feature request let me know how to proceed.

in the past when we used to create aws codepipeline using terraform we used to this code 

  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "ThirdParty"
      provider         = "GitHub"
      version          = "1"
      output_artifacts = [format("%s-src", local.application)]

      configuration = {
        Owner  = local.owner
        Repo   = local.github_repo
        Branch = local.branch
      }
    }
  }

And it will work but today when i was creating the pipeline it gave me an error saying "InvalidActionDeclarationException: Action configuration for action 'Get-Deploy-Instructions' is missing required configuration 'OAuthToken""

It is working fine earlier. Not sure where is the problem and how to get it resolve. Past code i never specified oauthtoken

And also when i specify oauthtoken in the configuration the github token is visible in plain sight . My main question is will it be stored in terraform state ? if yes it is sensitive data can we hide it by anyway

**Comment by gdavison** [comment]
Hi @gauravachatrath, this is a change in version 3.0 of the AWS provider. The Version 3 Upgrade Guide [has instructions for dealing with this change](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_codepipeline).

The value of the GitHub token is hashed in Terraform state.

Since this question was related to the AWS provider, in the future you can create the issue in our issue tracker at https://github.com/terraform-providers/terraform-provider-aws/issues

**Comment by gauravachatrath** [comment]
Hi , The pipeline still keeps on failing even the token is fine. It works once fine but then fails later
