### ISSUE TITLE
Vagrant provider 

### ISSUE THREAD

**Issue by robparrott** [hashicorp/terraform#265]
Consider implementing a provider for Vagrant.

Vagrant, by providing an API around virtualization and provisioning, serves as a simple, local IaaS service. Thus for dev work it makes sense to leverage Vagrant as well thru terraform (particularly for configuration management "DevOps" development work).

A general dev workflow could be: 
1. define a server/instance in a terraform setup as a vagrant provided object
2. work on config scripting/puppet/chef/etc. until it works as expected, with source code in a subdir of the terraform working dir
3. modify the tf file to use a remote provider such as AWS of google compute

**Comment by jimmycuadra** [comment]
I'm curious how the implementation of this would work. AFAIK, Vagrant doesn't expose any sort of API that would allow you to treat it as a pseudo cloud platform. Would the Terraform provider for Vagrant just have to generate a Vagrantfile based on the Terraform configuration and shell out to Vagrant to boot things?

**Comment by derek-adair** [comment]
It seems like this isn't all that useful when you can define and build your images in packer, ya?  

Everything you need to shift from dev > staging > prod is all right at your fingertips right there.  Treating Vagrant as a terraform resource seems like it would take Vagrant in a route that it is not meant to go.

**Comment by derek-adair** [comment]
Are you just trying to manage your developers environments?

**Comment by knuckolls** [comment]
Using packer to cut a virtualbox or vmdk image, then having a virtualbox or
vmware fusion provider to run it with seems like a useful flow.

**Comment by jimmycuadra** [comment]
Vagrant is generally sold as being for development environments, but it has a lot of potential as a platform for testing small server infrastructures. Once a cluster of VMs are running and accessible over a network, there are many tools that can be used against them that don't care whether they're talking to AWS, DigitalOcean, Rackspace, or local Vagrant-backed VMs. It'd be a great way to test Terraform configuration without having to launch real cloud resources that cost money.

**Comment by derek-adair** [comment]
I believe you can theoretically get terraform to talk with your own hypervisor as a provider if desired, but i'm not sure that's really worth the effort when you can use the free tier at AWS.  I've been testing various infrastructures for the past... 2 weeks or so and i've only racked up $3.71 - mind you thats before I realized i could deploy consul on a T2 micro.  So if you can't test on 750 hours or so of a micro instance... 

Furthermore, there are ways to mimic architecture within a vagrant config managing multiple machines, etc.

Maybe managing atlas vagrant shares via terraform would be neat though?? seems like that would be some kind of middle ground.

**Comment by ajlanghorn** [comment]
:+1: to this. I'd love to see a Vagrant provider for Terraform.

**Comment by phrawzty** [comment]
:+1:

**Comment by mongrelion** [comment]
:+1:

**Comment by elchudi** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by wricardo** [comment]
:+1:

**Comment by nicolai86** [comment]
:+1:

**Comment by taliesins** [comment]
:+1:

**Comment by maxenglander** [comment]
:+1:

**Comment by jessehub** [comment]
:metal:

**Comment by Morriz** [comment]
:+1:

**Comment by arozhkov** [comment]
+1 for Vagrant support.
I'd like to use the same tool on all stages: dev, test, prod. Any cloud provider is fine for last two stages but developers want their local environment.

**Comment by adjohnson916** [comment]
:+1:

**Comment by st33v** [comment]
:+1:

**Comment by denisura** [comment]
:+1:

**Comment by engine07** [comment]
:thumbsup:

**Comment by meggarr** [comment]
+1

**Comment by antoniou** [comment]
:thumbsup:

**Comment by veetow** [comment]
huge :+1:

**Comment by romanvbabenko** [comment]
+1

**Comment by elleryq** [comment]
+1

**Comment by JeanMertz** [comment]
I'm surprised that this hasn't happened yet, given that Vagrant and Terraform are both Hashicorp products. :+1:

**Comment by peterbourgon** [comment]
:+1: please :)

**Comment by bhurlow** [comment]
:+1:

**Comment by adjohnson916** [comment]
@bhurlow I beat you by 4 months on the ":+1:"... :stuck_out_tongue:

**Comment by adespain** [comment]
(Y)

**Comment by emdem** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by sahilsk** [comment]
![](https://camo.githubusercontent.com/a2840914d539225aaf8d395397d8dbc488a0740d/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67)

+1 for Vagrant support.
I'd like to use the same tool on all stages: dev, test, prod. Any cloud provider is fine for last two stages but developers want their local environment.

**Comment by gedw99** [comment]
+1 me too :)

**Comment by shafiqissani** [comment]
:+1:

**Comment by yamaszone** [comment]
+1

**Comment by wmangano** [comment]
👍

**Comment by gabriellhrn** [comment]
:+1:

**Comment by stanchan** [comment]
👍

**Comment by stephenlauck** [comment]
Why is there no vagrant provider for terraform? Seems like a real thing to go from laptop to production using the same provisioning artifacts.

**Comment by AgilDat** [comment]
:+1:

**Comment by kadamwolfe** [comment]
+1

**Comment by apparentlymart** [comment]
I think a challenge with a Vagrant provider for Terraform is that Terraform generally deals with remote APIs rather than local resources. We *could* have a provider whose implementation is to shell out to run `vagrant up`, etc, but that would be pretty unprecedented and would certainly be useful only when running Terraform on a single machine e.g. in a dev environment. There's also a lot of redundancy of functionality between Terraform and Vagrant, with Terraform having its own providers for various systems, and maintaining its own state file that's essentially equivalent to Vagrant's own record-keeping.

I've had success in the past using the Terraform docker provider with a local docker instance as an alternative to Vagrant. It works pretty well because the model translates nicely between the local case and the remote case. We could do something similar with [`libvirt`](http://libvirt.org/) (e.g. using [digitalocean's Go bindings](https://github.com/digitalocean/go-libvirt), or various others) to get an interface to all of the VM hypervisors it supports, with the same benefit that `libvirt` offers both a local and a remote API interface, giving a reasonable story for sharing a configuration between development and deployment, where the difference is just in how the provider is configured.

**Comment by cyberious** [comment]
While understanding that remote calls vs local calls, I see no reason to not put for effort to allow users to develop and test local than push to provider of choosing. Understanding of course certain provider differences. This would help in providing quick testing for modules and such.

**Comment by bawgeneric** [comment]
Still not available ? Who is the sleeping guy ?

**Comment by djoos** [comment]
👍

**Comment by stack72** [comment]
Hi @robparrott, 

Thanks so much for the request for the Vagrant provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

@stack72
