### ISSUE TITLE
Poor error message when invalid version range is given

### ISSUE THREAD

**Issue by caarlos0** [hashicorp/terraform#26516]
### Terraform Version

```
Terraform v0.13.4
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> v1.81"
    }
  }
  required_version = ">= 0.13"
}

```

### Debug Output

not relevant

### Crash Output
not applied

### Expected Behavior

Version ranges containing the `v` prefix used to work in terraform 0.12 and bellow, but now it gives a cryptic error message instead:

```
Incorrect version constraint syntax: missing comma after "~> ".
```

### Actual Behavior

Either work as before or give a better error message.

### Steps to Reproduce

Create a `versions.tf` with the example above and run `terraform init`.

### Additional Context

Got this while migrating from 0.12 to 0.13. Maybe also a good idea to include it in the migration.
BTW: if you think this a valid bug, I would love to give a try fixing it :)

**Comment by supra08** [comment]
I would like to take this up @caarlos0

**Comment by alisdair** [comment]
Thanks for reporting! I can reproduce this with 0.13.4 and 0.14-dev. 

The bug here is a poor error message. The `v` prefix is not a valid version constraint by the scheme we're using.

If you'd like to fix this, it would need a patch to [the upstream go-versions library](https://github.com/apparentlymart/go-versions). There is already [a better error message for a similar method to the one we use in Terraform](https://github.com/apparentlymart/go-versions/blob/74e39fb0b897869cb139f244635db39bb84ea848/versions/constraints/ruby_style.go#L32-L34):

```go
		case strings.HasPrefix(remain, "v"):
			// User seems to be trying to use a "v" prefix, like "v1.0.0"
			return spec, fmt.Errorf(`a "v" prefix should not be used`)
```

This is in the `ParseRubyStyle` method, but Terraform is using `ParseRubyStyleMulti`: https://github.com/hashicorp/terraform/blob/eb2a02768447bfc7e777f5b4cf54a816c80aab39/internal/getproviders/types.go#L90-L92

[The corresponding error handling for multi doesn't include any of these useful error messages](https://github.com/apparentlymart/go-versions/blob/74e39fb0b897869cb139f244635db39bb84ea848/versions/constraints/ruby_style.go#L86-L92). It would be great to find a way to unify that error handling.

**Comment by caarlos0** [comment]
Already opened the PR to the lib... Thanks for the orientation @alisdair :)
