### ISSUE TITLE
Example or guide for deriving the config information from an existing infrastructure (GKE) and importing it to terraform management

### ISSUE THREAD

**Issue by StevenACoffman** [hashicorp/terraform#26525]
Is there an example or how-to guide for deriving the config information from an existing (non-TF) GKE cluster using [the container cluster datasource provider](https://www.terraform.io/docs/providers/google/d/container_cluster.html) and then [import](https://www.terraform.io/docs/state/import.html) it? I found #19909 as a similar request, but without a full and complete resolution.

### Use-cases
I have an existing GKE cluster that was not created with Terraform, and I wish to automatically export it's configuration and manage it using terraform as if I had created it.

### Attempted Solutions
I appear to be able to use [terraformer](https://github.com/GoogleCloudPlatform/terraformer) to similar effect, but this is not built into Terraform itself, nor well documented.

### Proposal
I would suggest either additional documentation (such as an example or guide), or to build terraformer functionality into terraform.

### References
#19909

**Comment by apparentlymart** [comment]
Hi @StevenACoffman! Sorry for the slow response here.

Since the guidance you're hoping for seems specific to the Google Cloud Platform provider, this sort of documentation would typically live in [the provider's own repository](https://github.com/hashicorp/terraform-provider-google) rather than in the Terraform Core repository, which only covers the general stuff like the configuration language and CLI commands.

For that reason, I'm going to transfer this over to the provider repository so that the provider development team can decide how best to respond to it. Thanks!

If you're interested in a direct answer to your question rather than waiting for a full guide to be written, you could also open a topic to talk about it in [the Google Cloud Platform provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32), where other community members might have some tips or examples to share.
