### ISSUE TITLE
Terraform AARCH64 crashes when using vSphere Provider to deploy OVA

### ISSUE THREAD

**Issue by lamw** [hashicorp/terraform#26534]
Using Terraform AARCH64 and the vSphere Provider to deploy an VMware OVA, it caused Terraform itself to crash. 

### Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/vsphere v1.24.1
```

### Terraform Configuration Files

```terraform
provider "vsphere" {
  user           = "administrator@vsphere.local"
  password       = "VMware1!"
  vsphere_server = "192.168.30.200"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "Primp-Datacenter"
}

data "vsphere_datastore" "datastore" {
  name          = "sm-vsanDatastore"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "pool" {
  name          = "Supermicro-Cluster/Resources/Workload"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_host" "host" {
  name          = "192.168.30.14"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vmFromRemoteOvf" {
  name = "Nested-ESXi-7.0-Terraform-Deploy-1"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id = data.vsphere_datastore.datastore.id
  datacenter_id = data.vsphere_datacenter.datacenter.id
  host_system_id = data.vsphere_host.host.id

  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout = 0

  ovf_deploy {
    remote_ovf_url = "https://download3.vmware.com/software/vmw-tools/nested-esxi/Nested_ESXi7.0_Appliance_Template_v1.ova"
    disk_provisioning = "thin"
    ovf_network_map = {
        "VM Network" = data.vsphere_network.network.id
    }
  }

  vapp {
    properties = {
      "guestinfo.hostname" = "tf-nested-esxi-1.primp-industries.com",
      "guestinfo.ipaddress" = "192.168.30.180",
      "guestinfo.netmask" = "255.255.255.0",
      "guestinfo.gateway" = "192.168.30.1",
      "guestinfo.dns" = "192.168.30.1",
      "guestinfo.domain" = "primp-industries.com",
      "guestinfo.ntp" = "pool.ntp.org",
      "guestinfo.password" = "VMware1!23",
      "guestinfo.ssh" = "True"
    }
  }
}
```

### Crash Output

https://gist.github.com/lamw/0f2acdeabeafd0d18736da7085ca0b08

### Expected Behavior

Successful deployment

### Actual Behavior

OVA deployed but looks like it crashed prior to powering on the VM

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
2. `terraform apply -auto-approve`

**Comment by apparentlymart** [comment]
Hi @lamw! Sorry for this crash and thank you for reporting it.

From reviewing the log you shared, it seems like it was actually the vSphere provider that crashed here, rather than Terraform Core:

```
2020-10-09T17:31:03.754Z [DEBUG] plugin.terraform-provider-vsphere_v1.24.1_x4: panic: runtime error: index out of range [0] with length 0
```

The `plugin.terraform-provider-vsphere_v1.24.1_x4` prefix in that log line indicates that this is some output from the provider plugin which Terraform Core was relaying out into its own logs verbatim.

For that reason I'm going to label this in order to ask our bot to open a new issue based on this one in [the vSphere provider repository](https://github.com/hashicorp/terraform-provider-vsphere). Unfortunately our bot has been having some operational difficulties this week; if it doesn't seem to have done anything in a few hours from now you could perhaps open a similar issue yourself. If you do that, please close this one so that the bot will not find it later and create a duplicate.

Thanks!

**Comment by lamw** [comment]
@apparentlymart I only put the issue under Terraform based on the output stating that this is due to a crash in Terraform and that I should file Issue there. I figured this might be related to the specific provider but might be good to enhance message to be a bit more clear on where issue should be filed to based on providers being used
