### ISSUE TITLE
provider block ignored for hashicorp provider aliased to another one

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#26556]
### Terraform Version
```
v0.13.3
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    google = {
      source  = "hashicorp/aws"
      version = "~> 3.6.0"
    }
  }
}

provider "google" {
  region = "us-east-1"
}

resource "aws_vpc" "example" {
  provider = google
  cidr_block = "10.0.0.0/16"
}
```

### Expected Behavior

```
$ terraform validate
Success! The configuration is valid.
```

### Actual Behavior

```
$ terraform validate

Error: Missing required argument

The argument "region" is required, but was not set.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

--- 

cc @mildwonkey

**Comment by mildwonkey** [comment]
All better! There was bug in the provider transformer - the `configs` package had all the correct information (which is why I was initially confused: the tests in _configs_ all prove that we were properly mapping a given FQN to the local config), but terraform wasn't using that information. 

I back ported the fix into v0.13 so it will be in the next v0.13 release as well as v0.14 beta.

Using the same config: 
```
terraform validate
Success! The configuration is valid.
```
