### ISSUE TITLE
Pinned required_providers version ignored by terraform plan

### ISSUE THREAD

**Issue by odormond** [hashicorp/terraform#26565]
When changing the pinned version of a required provider, `terraform plan` happily ignores it.

### Terraform Version

```
Terraform v0.13.4
```

### Expected Behavior

`terraform plan` fails and tells me to run `terraform init` to update the provider.

### Actual Behavior

A plan is happily produced from invalid code.

### Steps to Reproduce

1. Create a directory and put a similar config in a `main.tf` file:
```terraform
terraform {
  required_version = "0.13.4"
  required_providers {
    github = {
      source  = "hashicorp/github"
      version = "3.0.0"
    }
  }
}

provider "github" {
  token        = var.github_token
  organization = "hashicorp"
}

resource "github_branch_protection" "terraform-master" {
  repository = "terraform"
  branch     = "master"
}

variable "github_token" {
  type = string
}
```
2. run `terraform init`
3. run `terraform plan -var "github_token=$GITHUB_TOKEN"`
4. see a nice plan
5. update the configuration file to bump the github provider version to `3.1.0`
6. run `terraform plan -var "github_token=$GITHUB_TOKEN"`
7. see a nice plan
8. run `terraform init`
10. run `terraform plan -var "github_token=$GITHUB_TOKEN"`
11. see 4 errors being reported instead of a nice plan

**Comment by thiagolsfortunato** [comment]
Same issue here after upgrade github provider to version `3.1.0`

**Comment by apparentlymart** [comment]
Thanks for reporting this, @odormond.

It sounds like Terraform 0.13 is missing the behavior from prior versions of making sure that the items cached in the `.terraform` directory match what was installed by the most recent `terraform init` and that in turn matches the current configuration.

For provider dependencies in particular 0.13 was a bit of a stepping-stone release because we knew that 0.14 was going to include an explicit lock file to allow Terraform to remember version selections in your version control system, so the same versions can be selected even across multiple working directories. It seems like we missed having an interim check to make sure things are consistent even though the lock file isn't present yet.

I expect the behavior will be different on the main branch now as we prepare for the first beta of 0.14. This'll be a good thing for us to test in 0.14.0-beta1 to see if the behavior is better and to fix up anything that's still not quite right about the locking behavior for commands other than `terraform init`.

**Comment by odormond** [comment]
Hi @apparentlymart!

Thanks for the feedback. It's much appreciated. I'll keep an eye on the 0.14 progress then.

**Comment by alisdair** [comment]
I'm able to reproduce this with 0.13.4 and 0.14.0-beta1, and can confirm that the behaviour does not exist in 0.12.29. Simpler repro steps:

Create a config requiring specific `null` provider, and run `terraform init`:

```hcl
terraform {
  required_providers {
    null = {
      version = "2.1.2"
    }
  }
}

resource "null_resource" "none" {}
```

Then `terraform plan` succeeds. Now change the version requirement to `"3.0.0"`. `terraform plan` again succeeds, but should error due to unmet provider requirements.

**Comment by odormond** [comment]
Thanks @alisdair for confirming and finding a simpler way to reproduce. I didn't thought of the null provider! :smile:
