### ISSUE TITLE
S3 backend not working

### ISSUE THREAD

**Issue by gevraud** [hashicorp/terraform#26594]
Hello,

I am trying to use S3 backend with IBM Spectrum Scale.

Reading different posts , I did this config

backend.tf
```
terraform {    
  backend "s3" {    
    region   = "any"    
    access_key = "my_key_id"    
    secret_key = "my_key_secret_id"    
    endpoint = "https://scales.xxx.local:8081"    
    max_retries = 1    
    force_path_style = true                          
    skip_requesting_account_id = true    
    skip_credentials_validation = true    
    skip_get_ec2_platforms = true    
    skip_metadata_api_check = true    
    skip_region_validation = true    
  }    
}    
```

staging.tfbackend
```
key = "staging.tfstate"
bucket = "staging"
```

I run terraform init and I received this error :   

```
2020/10/15 12:46:39 [DEBUG] [aws-sdk-go] <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><RequestId>xxxx</RequestId></Error>
2020/10/15 12:46:39 [DEBUG] [aws-sdk-go] DEBUG: Validate Response s3/GetObject failed, attempt 0/1, error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: xxxx, host id: yyy
Error refreshing state: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: xxxx, host id: yyy
```

Any idea ?  I tested the credentials with Cyberduck and it worked

Regards

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by gevraud** [comment]
OK thx
