### ISSUE TITLE
Error when removing child module resources from state

### ISSUE THREAD

**Issue by magno101** [hashicorp/terraform#26615]
### Terraform Version

```
Terraform v0.13.4
```

### Terraform Configuration Files

```shell
$ terraform state list
module.basevnet.azurerm_virtual_network.vnet
module.local_peers["hub_vnet"].azurerm_virtual_network_peering.peer
module.remote_peers["hub_vnet"].azurerm_virtual_network_peering.peer
module.vnet_resource_group_lock.azurerm_management_lock.lock
module.basevnet.module.routetable.azurerm_route.10_8-route
module.basevnet.module.routetable.azurerm_route.172_12-route
module.basevnet.module.routetable.azurerm_route.192_16-route
module.basevnet.module.routetable.azurerm_route.default-route
module.basevnet.module.routetable.azurerm_route.localnet-route
module.basevnet.module.routetable.azurerm_route_table.routetable
module.basevnet.module.rg.module.rg.azurerm_resource_group.rg
```

### Expected Behavior

Terraform state rm command should remove the listed object from the state.

### Actual Behavior

```shell
Error: Attribute name required

  on  line 1:
  (source code not available)

Dot must be followed by attribute name.
```

### Steps to Reproduce

Any one of the following commands will produce the same error.
```shell
terraform state rm module.basevnet.module.routetable.azurerm_route.10_8-route
terraform state rm module.basevnet.module.routetable.azurerm_route.172_12-route
terraform state rm module.basevnet.module.routetable.azurerm_route.192_16-route
terraform state rm 'module.basevnet.module.routetable.azurerm_route.10_8-route'
terraform state rm 'module.basevnet.module.routetable.azurerm_route.172_12-route'
terraform state rm 'module.basevnet.module.routetable.azurerm_route.192_16-route'
```

**Comment by apparentlymart** [comment]
Hi @magno101,

It seems like this error is appearing because your resource addresses include invalid identifiers like `10_8-route`. A resource name can't start with a number because in the Terraform language a digit starts a numeric literal.

While the error message here can certainly be improved a lot, the fact that it returned an error at all seems like correct behavior. What is unclear to me is how you've ended up with resources with invalid names in the first place... were these created with an earlier version of Terraform?

**Comment by magno101** [comment]
Yes they were. I want to say 0.11, but am not 100% on that.

**Comment by apparentlymart** [comment]
Hi @magno101,

If your goal is just to delete them so that Terraform 0.12 can recreate them with new names then I think the easiest answer would be so delete them with Terraform 0.11 first, before you upgrade. This is one of the actions that the `terraform 0.12checklist` command in the later 0.11 versions would identify, so Is suggest following the 0.12 upgrade guide (which includes running that checklist command) so it can identify any other issues you might need to attend to before upgrading.
