### ISSUE TITLE
Unable to deploy Azure Lighthouse using Terraform : azurerm_lighthouse_definition Error: The argument "scope" is required, but no definition was found.

### ISSUE THREAD

**Issue by AmineBenbouzid** [hashicorp/terraform#26642]
### Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0
```

### Terraform Configuration Files

```terraform
# Configure the Azure Provider
provider azurerm {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "2.0.0"
  features {}
}


data "azurerm_role_definition" "contributor" {
  role_definition_id = "b24988ac-6180-42a0-ab88-20f7382dd24c"
}

resource "azurerm_lighthouse_definition" "example" {
  name               = "test"
  description        = "This is a lighthouse definition created via Terraform"
  managing_tenant_id = "yyyyyyyyy-yyyyyyyyyyy-yyyyyyyy-yyyyyyy"

  authorization {
    principal_id       = "yyyyy-yyyyyy-yyyyyyyy-yyyyyyyy"
    role_definition_id = data.azurerm_role_definition.contributor.role_definition_id
  }
}
```

### Actual Behavior
```
Error: The argument "scope" is required, but no definition was found.
Please,Why it's mandatory to define a "scope" and how can i do it ? 
```

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
