### ISSUE TITLE
Unable to deploy Azure Lighthouse using Terraform : azurerm_lighthouse_definition Error: Invalid resource type

### ISSUE THREAD

**Issue by AmineBenbouzid** [hashicorp/terraform#26640]
Hi,

A few days ago I tried to deploy azure lighthouse using Terraform.

### Terraform Version

```
Terraform v0.13.1
provider registry.terraform.io/hashicorp/azurerm v2.0.0
```

### Terraform Configuration Files

```terraform

# Configure the Azure Provider
provider azurerm {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "2.0.0"
  features {}
}


data "azurerm_role_definition" "contributor" {
  role_definition_id = "b24988ac-6180-42a0-ab88-20f7382dd24c"
}

resource "azurerm_lighthouse_definition" "example" {
  name               = "test"
  description        = "This is a lighthouse definition created via Terraform"
  managing_tenant_id = "yyyyyyyyy-yyyyyyyyyyy-yyyyyyyy-yyyyyyy"

  authorization {
    principal_id       = "yyyyy-yyyyyy-yyyyyyyy-yyyyyyyy"
    role_definition_id = data.azurerm_role_definition.contributor.role_definition_id
  }
}



```

### Actual Behavior

azurerm_lighthouse_definition Error: Invalid resource type

**Comment by danieldreier** [comment]
@AmineBenbouzid that resource was [added to the AzureRM provider](https://github.com/terraform-providers/terraform-provider-azurerm/pull/6560) on September 16th, and the next release that included it was v2.28.0. You are running an older version of the provider that doesn't have that resource yet, and will need to upgrade to v2.28.0 or newer.

If you need more help, your best option is to seek support on the community forum. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.
