### ISSUE TITLE
import with a for_each ressource not working.  The quotes are stripped on Windows version.

### ISSUE THREAD

**Issue by kinwolfqc** [hashicorp/terraform#26664]
Trying to manage the workspaces of Terraform Enterprise using the TFE provider, but since we already created, and used, some workspaces, I need to import them.  The ressource is using for_each to list through our environments name and creates a workspace for each.  The thing is, when I run the import like this:
```
 terraform import tfe_workspace.PesGpTx["Dev"] ws-hTRVKCxBxPnhj1rm  
```
terraform seems to strip the quotes " and gives the error(noticed the removed quotes):

> Error: Index value required
> 
>   on <import-address> line 1:
>    1: tfe_workspace.PesGpTx[Dev]

I tried escaping the character, to no avail. terraform import tfe_workspace.PesGpTx[\"Dev\"] ws-hTRVKCxBxPnhj1rm returns the same error

EDIT:  Some further information:  This is all on a Windows 10 workstation.  I tried running it on ubuntu(using WSL2 on windows10) and the escaping works, the quotes aren't stripped and the import worked.  So, windows version bug only?

### Terraform Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/tfe v0.22.0
...
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    tfe = {
      source = "hashicorp/tfe"
      version = "0.22.0"
    }
  }
}

provider "tfe" {
  # Configuration options
  hostname = var.hostname
  token    = var.token
}

resource "tfe_organization" "default" {
  name  = "<redacted>"
  email = "<redacted>"
}

resource "tfe_workspace" "PesGpTx" {
  for_each      = toset(var.env)
  name          = "PesGpTx-${each.key}"
  organization  = tfe_organization.default.id
}
```

### Debug Output
https://gist.github.com/kinwolfqc/9563847c8ab550a987b56bf89e883d9f

**Comment by apparentlymart** [comment]
Hi @kinwolfqc ,

Unfortunately the handling of command line quoting varies between operating systems and between shell interpreters on each operating system; it's not under Terraform's direct control.

The Windows escaping conventions vary from application to application but Terraform is following the conventions implemented in a standard Windows API function, which call for escaping all of the quotes using one backslash each.

If you are using PowerShell then things get considerably more complicated, because PowerShell's approach to running normal Windows command line programs is to first parse the command line itself, then to reassemble something similar (but not exactly the same) as the input and then pass _that_ to the final program. In that case, you need to deal with both PowerShell escaping _and_ normal Windows command line escaping. For that reason, I'd recommend not using PowerShell to run commands other than its own "cmdlets".

If what I've said above doesn't explain what you are seeing then please let me know. Unfortunately though, there isn't really anything we can do to change the command line handling behaviors because they always happen before Terraform code is even running..😞

**Comment by kinwolfqc** [comment]
Hi @apparentlymart, 

I forgot to mention it, but I tested this on powershell 5.1, 7 and the regular command prompt shell and the problem happens in everyone of them, even the regular  command prompt shell.  And quotes work fine with any other utility, so the problem really looks to be with terraform to me.

In any case, if I understand this correctly, this problem could mean there is no way for a windows user to use "Import" with a for_each resource, and that's kind of a major bug there.

**Comment by lorengordon** [comment]
@kinwolfqc did you try escaping the resource address? it is the shell that interpolates the quotes, it is not terraform stripping them.

not sure this is the correct syntax for your shell, but something like:
```
terraform import tfe_workspace.PesGpTx[\"Dev\"] ws-hTRVKCxBxPnhj1rm
```

in bash, i would wrap the resource address in single quotes like this:
```
terraform import 'tfe_workspace.PesGpTx["Dev"]' ws-hTRVKCxBxPnhj1rm
```

**Comment by kinwolfqc** [comment]
@lorengordon Yes, I did(the syntax you posted is correct)  That's how I typed it in a normal cmd shell, then powershell 5.1 and powershell 7(my default shell).  I wanted to try it on powershell 7 on linux too, to compare, but didn't have the time.  And the linux option with WSL2 is not an option for the company, I only tried for debug purpose.

I'm pondering opening a support ticket with hashicorp on this since it's a feature that simply doesn't work on windows right now and we need it to go forward.

**Comment by lorengordon** [comment]
It definitely works on windows, and it is definitely the shell interpolating the quotes. I just don't know how to help you with the escape syntax for your shell. :/

**Comment by kinwolfqc** [comment]
I got my reply from support to make it work in powershell.  It's a syntax I have never seen but it works.
I can't even type it here because the message editor is interpreting it itself and is removing characters, but it's backslash-backtick-doubleQuotes and the double-quotes will be seen by terraform.

I have never seen such an escape sequence but it works.  

As for the regular cmd shell, I managed to make it work too with the regular escaping (backslash-doublequotes) so I guess the fault for it not working before can be placed on the exhausted guy in front of the keyboard on that day(me) 

Closing this.
