### ISSUE TITLE
local and variable lists treated differently

### ISSUE THREAD

**Issue by Darkbat91** [hashicorp/terraform#26673]
### Terraform Version

```
Terraform v0.13.4
```

### Terraform Configuration Files

```terraform
variable testlist {
  type = list(string)
  default = ["NOTSET"]
}

variable teststring {
  type = string
  default = "NOTSET"
}

locals {
    localstring = "NOTSET"
    test = [
        "NOTSET",
        ]
    comp = ["NOTSET"]
}

output "locallistcompare" {
    value = local.test == local.comp
}

output "outvarlist" {
    value = var.testlist
}

output "varlisttolocallist" {
    value = var.testlist == local.test
}

output "varstringtolocalstring" {
    value = var.teststring == local.localstring
}
```

### Debug Output
Debug located at 
https://gist.github.com/Darkbat91/12c4b74796d8f4366c70ca5d7ba48172

### Expected Behavior

List defined as an input variable should be comparable to a list defined as a local variable or adhoc. as a standard string compare works.

### Actual Behavior

List defined as a variable either as a default or an input does not equal a local or adhoc list

### Steps to Reproduce

```
terraform init
terraform apply
```
### Additional Context

No additional context

### References

- #23562 (Potentially)
- #21978  (May be related to type)

**Comment by alisdair** [comment]
Hi @Darkbat91, thanks for reporting this.

I believe that Terraform is working as designed here, although I can see that it is confusing. The issue here is that the `[]` syntax declares a `tuple`, not a `list`. The type specification in your variable declaration is causing the value to be converted to a `list`, which is not equal to a `tuple`.

You can verify this by running `terraform console` and inspecting the values:

```shellsession
$ terraform console
> var.testlist
tolist([
  "NOTSET",
])
> local.test
[
  "NOTSET",
]
> local.comp
[
  "NOTSET",
]
> local.comp == local.test
true
> var.testlist == local.test
false
> var.testlist == tolist(local.test)
true
```

See also #25798, which we addressed in #26189.

I'm going to close this as I believe that Terraform is working as designed here.
