### ISSUE TITLE
Long running terraform apply

### ISSUE THREAD

**Issue by Snehil03** [hashicorp/terraform#26686]
Hi ,

I am encountering issue with respect to Terraform Apply,
I have executed scripts it's running from last 3:30 hours 

module.ingress.helm_release.cert_manager: Still modifying... [id=cert-manager, 3h27m51s elapsed]

### Terraform Version

```
Terraform v0.12.29
```

### Terraform Configuration Files

```terraform
resource "helm_release" "cert_manager" {
  name       = "cert-manager"
  namespace  = kubernetes_namespace.ingress.id
  repository = data.helm_repository.jetstack.name
  chart      = "cert-manager"
  version    = "v0.16.0"
  depends_on = [module.k8s_manifest_cert_manager_crd.ids]

  values = [file("${path.module}/cert-manager.yaml")]
```

### Debug Output
Not available as it's running in loop.

### Crash Output
No crash report as it's running endlessly into the loop

### Expected Behavior
Certificate manager should have updated ,.

### Actual Behavior
It's running into same state from last 3hr30mins 

### Steps to Reproduce
terraform plan,
terraform apply,

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

If you are having issues creating the resource, I'd suggest looking into the resources in the configuration and how long those are expected to take to create (in this case, Helm), rather than an issue with Terraform itself.
