### ISSUE TITLE
Unable to attach iam_instance_profile to the existing instance which was created manually

### ISSUE THREAD

**Issue by OmPrasadReddy** [hashicorp/terraform#26715]
Hi,

I have created policy, role and instance profile with terraform. My requirement is to attach instance profile to already running instance which was created manually. I have imported running instance ID and used  aws_instance resource top attach instance profile but unfortunately terraform is destroying (terminated)the instance. It would be great if you could let me know how to attach new instance profile to running instance.

resource "aws_iam_instance_profile" "profile" {
  name = "instanceprofile"
  path = "/ca/app/"
  role = aws_iam_role.datascience_role.name
}
resource "aws_instance" "import_instance" {
  ami                  = "ami-0947d2ba12ee1ff7"
  instance_type        = "t2.micro"
  subnet_id            = "subnet-0116b689"
  iam_instance_profile = aws_iam_instance_profile.datascience_profile.name
}

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. Please use [the terraform community forum](https://discuss.hashicorp.com/c/terraform-core), or in this case you may prefer the [aws provider specific forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). Cheers!
