### ISSUE TITLE
Get any provider configuration in the code

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform#26726]
### Current Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.8.0
```

### Use-cases

My use case is this: We have multiple AWS providers defined each with different **shared_credentials_file** file. I need to get either the set path to that file or access key and secret key from that file in one of the downstream modules (3 levels or more deep, so can't use variables here).

```terraform
provider "aws" {
  alias = "a1"
  region = "eu-west-2"
  shared_credentials_file = "../env/credentials1.sec"
}
provider "aws" {
  alias = "a2"
  region = "eu-west-2"
  shared_credentials_file = "../env/credentials2.sec"
}
provider "aws" {
  alias = "a3"
  region = "eu-west-2"
  shared_credentials_file = "../env/credentials3.sec"
}
module "a1" {
  providers = {
    aws = aws.a1
  }
  source = "./a"
  ...
}
module "a2" {
  providers = {
    aws = aws.a2
  }
  source = "./a"
  ...
}
module "a3" {
  providers = {
    aws = aws.a3
  }
  source = "./a"
  ...
}
```

Now **module a** has reference to other module **b** and we pass aws provider to it
```terraform
provider aws {}
module "b" {
  providers = {
    aws = aws
  }
  source = "../b"
  ...
}
```

Now **module b** has reference to other module **c** and we pass aws provider to it
```terraform
provider aws {}
module "c" {
  providers = {
    aws = aws
  }
  source = "../c"
  ...
}
```

Now **module c** has null_resource that needs to know which **shared_credentials_file** is being used in aws provider
```terraform
provider aws {}
resource "null_resource" "c" {
  triggers = {
    credentials_file = ???
  }
  provisioner "local-exec" {
    command = ...
    working_dir = ...
    environment = {
      AWS_SHARED_CREDENTIALS_FILE = self.triggers.credentials_file
    }
  }
}
```

### Proposal

Ideally we would have something like:
```terraform
provider.aws.shared_credentials_file
```

**Comment by apparentlymart** [comment]
Hi @mgzenitech,

The typical way that a provider supports this sort of use-case is to offer a data source that exposes the relevant part of the configuration or, ideally, exposes some higher-level value derived from the configuration. For example, the AWS provider has `aws_caller_identity`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/caller_identity) which, in effect, allows the configuration to react to the effective user that the configured credentials mapped to, and it has [`aws_region`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region) for getting the provider's configured region, which may have come from the `region` argument explicitly or from some environment variables.

Were something like what you proposed to be supported in Terraform, it too should be implemented as a feature of the AWS provider, because that way the AWS provider could (just as with `aws_region`) also reflect a credentials file selected some other way, such as from the `AWS_SHARED_CREDENTIALS_FILE` environment variable.

The AWS provider is a separate project with a different team, so I can't say whether the AWS provider team would want to introduce such a feature, but [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws) would be the best place to discuss the use-case.

We've previously considered a feature like you proposed here of allowing access to the provider configuration directly, but we rejected it for reasons like I've noted above: provider configuration values tend to be settable in various ways and so a mechanism built on access to a value known by the provider ought to work regardless of how that value was determined, because otherwise it can potentially inadvertently make a child module dependent on implementation details of its parent module, which would indeed be true in your case here: if you called that module C in any configuration where the credentials file is found implicitly rather than specified explicitly then it could fail.

For that reason, I'm going to close the issue _here_, and leave the AWS provider team to determine how best to handle this use-case within the provider itself, if you choose to open a feature request issue there to discuss it.
