### ISSUE TITLE
enable/disable module with a providers

### ISSUE THREAD

**Issue by wobeng** [hashicorp/terraform#26729]
Per documentation on [Legacy Shared Modules with Provider Configurations](https://www.terraform.io/docs/configuration/modules.html#legacy-shared-modules-with-provider-configurations)
 you can't use count with providers on modules.

How can I  enable/disable modules with a provider?

```
module "name" {
  source = "../module"

   ...

  providers = {
    aws = aws.east
  }

}

```

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
