### ISSUE TITLE
null[*] should be equivalent to []

### ISSUE THREAD

**Issue by remilapeyre** [hashicorp/terraform#26746]
This bug was found by @theophilechevalier: according to https://discuss.hashicorp.com/t/pattern-to-handle-optional-dynamic-blocks/2384/2 the value of `null[*]` should be `[]`, this is useful to set optional dynamic blocks in a Terraform resource but Terraform currently understands `null[*]` as a dynamic value and will fail during the apply because the value is unknown. The issues is at https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/expression.go#L1322-L1350 where an early exit is made for dynamic pseudo types before checking if `sourceVal` is `null`. I fixed it in https://github.com/hashicorp/hcl/pull/416 but Terraform will need to update this dependency once it is merged.

### Terraform Version

```
Terraform v0.13.4
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    consul = {
      source = "hashicorp/consul"
      version = "2.10.1"
    }
  }
}

provider "consul" {}

locals {
  key = null
}

resource "consul_keys" "app" {
  dynamic "key" {
    for_each = local.key[*]

    content {
      path = key.value
      value = key.value
    }
  }
}
```

### Debug Output
```
➜  terraform plan               
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # consul_keys.app will be created
  + resource "consul_keys" "app" {
      + datacenter = (known after apply)
      + id         = (known after apply)
      + var        = (known after apply)

      + key {
          + delete = false
          + flags  = 0
          + path   = (known after apply)
          + value  = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

➜  terraform apply --auto-approve
consul_keys.app: Creating...

Error: configuration for consul_keys.app still contains unknown values during apply (this is a bug in Terraform; please report it!)

```

### References
https://github.com/hashicorp/hcl/pull/416

**Comment by mildwonkey** [comment]
That's a good point @remilapeyre . I'm not sure if there's a clear error we could catch ahead of time - it doesn't work as written for this precise case, which isn't the same as "this should never work" , but it's absolutely something we can look into.

Also added the `documentation` label, we'll take a look at that section!

**Comment by remilapeyre** [comment]
I tested with the others variables type and it looks like only `null` is handled differently, I don't know whether this was done intentionally or not:


```
➜  ~ terraform console
> 1[*]
[
  1,
]
> true[*]
[
  true,
]
> "foo"[*]
[
  "foo",
]
> ""[*]
[
  "",
]
> {"a": "b"}[*]
[
  {
    "a" = "b"
  },
]
> [1, 2, 3, 4][*]
[
  1,
  2,
  3,
  4,
]
> null[*]

>
Error: Result depends on values that cannot be determined until after "terraform apply".

```

**Comment by apparentlymart** [comment]
This does seem like an interesting subtle case, tricky because it's at the intersection of a few different behaviors and so we must think about how best to compromise between them all.

I think the reason it behaves how it does today is because although we know that `[*]` will always return _some sort of sequence_, we decide whether it should be a list type or a tuple type based on the type of the input: splatting a list produces a new list, and splatting a tuple produces a new tuple. When we don't even know the _type_ of a value, `cty.DynamicVal` is our usual way to signal that.

This current behavior also creates another problem separate from the one you reported here, which is perhaps more significant: `null[*]` can never be anything _other than_ an unknown value, which violates HCL's usual rule that there's no way for an expression result to be unknown if all of the available variables and functions always return known values. That allows us to write a configuration that violates Terraform's core assumption that all values must finally become known during the apply step:

```hcl
resource "null_resource" "test" {
  triggers = {
    fail = join("", null[*])
  }
}
```

```shellsession
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.test: Creating...

Error: configuration for null_resource.test still contains unknown values during apply (this is a bug in Terraform; please report it!)
```

---

With all of that said, this leaves us in a bit of a sticky situation, because the outcome of this operation depends on the type, even for null values: splatting a null value of a list or tuple type is reported as an error rather than returning an empty tuple.

Terraform's usual rules for values changing between plan and apply are:

* If an unknown value has a known type during planning, either the apply-time final value must be of the same type or the expression must return an error.
* If a value is known during planning, then either it must be exactly identical (same type and same value) at apply time or the expression must return an error.

I think the "or return an error" exceptions here give us the leeway required to fix this as proposed in hashicorp/hcl#416: if we make splatting a `cty.NullVal(cty.DynamicPseudoType)` always return an empty tuple, then there are three possible outcomes during apply:

1. The null value is _still_ of an unknown type, perhaps due to being from a literal `null`, in which case an empty tuple is a reasonable outcome. (this would be the new behavior)
2. The null value is now of a type that isn't a list or tuple type, in which case the result would already be an empty tuple today.
3. The null value is now of a list or tuple type, in which case the expression would fail.

Cases 1 and 2 both return the same result, and case 3 returns an error, and so this seems to satisfy the rules.

Given that, I suggest that we move forward with hashicorp/hcl#416 and then update Terraform to include it. The change should fit within our definition of a backward-compatible change because it only makes existing values "more known" and thus it will make existing results more precise, rather than less precise or return an error.

However, I'd like for someone else on the Terraform Core team to check my work here. I've been away from that particular code for a while, and I've come to a different conclusion than the earlier discussion so I'd like to confirm I'm not missing something before we move forward. @mildwonkey, does my reasoning above add up for you? Would you be comfortable with moving forward with the proposed PR in HCL based on this reasoning?

**Comment by mildwonkey** [comment]
That all sounds very reasonable to me @apparentlymart , I just left an approval on  hashicorp/hcl#416 ! Thank you for the detailed comment/explanation.

**Comment by apparentlymart** [comment]
I've merged the upstream change to HCL but because there was already an HCL patch release today I decided not to run another one immediately, because there are various open pull requests waiting review and hopefully we can release several of them together.

With that said, we'll hold this issue open for now to record that there will still be a small amount of work to do in this repository once that change is released upstream (updating the HCL dependency in `go.mod` to the new version).

Thanks for reporting this and proposing a solution, @remilapeyre!
