### ISSUE TITLE
template_cloudinit_config multiple part execution order is wrong

### ISSUE THREAD

**Issue by balamuruganravi** [hashicorp/terraform#26759]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```terraform
data "template_cloudinit_config" "myapp_cloudinit_config" {
  gzip = false
  base64_encode = false

  # Main cloud-config configuration file.
  part {
    content_type = "text/cloud-config" 
    content = "${data.template_file.base_bootstrap_file.rendered}" 
    merge_type = "list(append)+dict(recurse_array)+str()"
  }
  part {
    content_type = "text/cloud-config"
    content = "${module.template_file_appsec_init.appsec_user_data_rendered}"
    merge_type = "list(append)+dict(recurse_array)+str()"
  }

  part {
    content_type = "text/x-shellscript"
    content = "${module.template_file_beat_init.beat_user_data_rendered}"
  }
}
```

### Debug Output
I am using the terraform to build my ec2-instance as part of instance bootstrap, added cloud-init config to run multiple userdata scripts. but the `content_type = "text/x-shellscript"` always executed first. I verified the `cat /var/log/cloud-init-output.log` file. it shows the shellscript is inovked first.

### Expected Behavior

expected the shell script part will be executed at last.

### Actual Behavior

the shell script part is executed first

**Comment by mildwonkey** [comment]
Hi @balamuruganravi ! 

Terraform has changed quite a bit since the v0.12 release, and we are no longer fixing issues reported in v0.11 (or v0.12). I recommend you upgrade to the latest version of terraform - v0.13 - and if you run into new issues there you can open a new ticket.

You may have luck posting your question in [our community forum](https://discuss.hashicorp.com/c/terraform-core) where someone may be able to help you with a workaround.
