### ISSUE TITLE
ignore_changes doesnt apply to aws_iam_access_key resource

### ISSUE THREAD

**Issue by arunraoseattle** [hashicorp/terraform#26754]
**Terraform Version**
0.11.14

**Terraform files**
```
resource "aws_iam_user" "temp-user" {
    name = "temp-iamUser"
}

resource "aws_iam_access_key" "temp-user-access-key" {
    user = "${aws_iam_user.temp-user.name}"

    lifecycle {
        ignore_changes = "*"
    }
}
```

**Expected Behavior**

No changes when access key was rotated behind the scenes using another management tool.

**Actual Behavior**

```
  + aws_iam_access_key.temp-user-access-key
      id:                   <computed>
      encrypted_secret:     <computed>
      key_fingerprint:      <computed>
      secret:               <computed>
      ses_smtp_password:    <computed>
      ses_smtp_password_v4: <computed>
      status:               <computed>
      user:                 "temp-iamUser"
```

PS: The issue is the same even in the latest version if I specified static list of attributes to be ignored - id, secret etc,. I am seeing this issue only for aws_iam_access_key.

**Comment by apparentlymart** [comment]
Hi @arunraoseattle,

Unfortunately we're no longer working on Terraform v0.11, so any bugs it has are now permanent features of that line of releases.

With that said, I think in this case the problem is not really about `ignore_changes` but rather than the remote access key object has been entirely deleted by your rotation process, and so Terraform is planning to create a new one to replace it. `ignore_changes` only applies to updates to the existing object; if there is no longer a remote object to compare the configuration to, then there are no changes to ignore. To avoid seeing this change you'd need to make your rotation process change the object in-place, instead of deleting it.

If you have any further questions about this you could start a topic about it in [the community forum](https://discuss.hashicorp.com/c/terraform-core), although to be honest most of the participants there are using Terraform v0.12 or later and so help for v0.11 may be harder to find. :confounded:
