### ISSUE TITLE
unable to roll back to v0.13 after testing v.0.14

### ISSUE THREAD

**Issue by jurgenweber** [hashicorp/terraform#26774]
### Terraform Version

```
$ tf version
Terraform v0.13.5
+ provider instaclustr/instaclustr/instaclustr v1.6.1
+ provider registry.terraform.io/hashicorp/aws v3.13.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tfe v0.22.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "xxxx"

    workspaces {
      prefix = "environment-"
    }
  }
}
```

after trying out v0.14.0-beta2, I hit this issue: https://github.com/hashicorp/terraform/issues/26772 and decided to go back to v0.13.5 which I am now unable to do. Please be aware, while an init and a plan has been completed agianst this state, a validate never worked and an apply never worked. If I look at the sate in TFCloud:

```
  "version": 4,
  "terraform_version": "0.13.5",
  "serial": 1246,
  "lineage": "cb77fa4f-8d3d-bcc2-4d84-1b319da49756",
  "outputs": {
```

it quite clearly says it is on 0.13.5, it should not be on v0.14. I have tried pushing a state without success.

### Debug Output
```
Error: state snapshot was created by Terraform v0.14.0, which is newer than current v0.13.5; upgrade to Terraform v0.14.0 or greater to work with this state
```

### Expected Behavior
I expect a state on v13 to work on v13, irrelevant of what has happened with v14.

### Actual Behavior
I tested v14, nothing worked... made an issue and attempted to roll back. It is not complaining that its state is v14 even thuugh when I inspect the state it is v13.

**Comment by pselle** [comment]
I see you were able to get an answer to this through other channels, and I'll add resources here for future readers. 

Generally reverting a Terraform Cloud workspace to a previous state would require you to push a state with the needed version to it. Since this would be an older version using the Terraform CLI will not work and what you will need to use the Terraform Cloud API: https://www.terraform.io/docs/cloud/api/state-versions.html#create-a-state-version

In addition to this, before uploading the state you will need to lock the workspace with the same user whose token will be used to authenticate the API call. This can be done from the workspace's Settings > Locking.

Glad you were able to resolve your issue!

**Comment by jurgenweber** [comment]
Yeah, in the end I just worked out the bugs I was having and implemented work arounds, I then found out from cloud support you can do what you describe.

Thanks
