### ISSUE TITLE
0.14.0beta2 but also any other version - super slow execution time

### ISSUE THREAD

**Issue by romeomorcia** [hashicorp/terraform#26807]
Hello,

I'm having troubles in starting terraform as it takes around one minute or more to execute a simple `terraform version`.

Do you know what could cause this issue? I'm the only one with this issue in the entire company and i'm feeling like something might have happened in the files that terraform analyze.

Any idea?

PS: i've opened the same thread on stack overflow but got the ticket closed by the bot.

Thanks!

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
