### ISSUE TITLE
Terraform wants to destroy and create resources after adding count argument as conditional

### ISSUE THREAD

**Issue by ajklotz** [hashicorp/terraform#26809]
#  Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azurerm v2.31.1
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Terraform Configuration Files
```terraform
https://github.com/ajklotz/terraform-issue-count-argument
```

### Debug Output
https://gist.github.com/ajklotz/b15032481173001ba99bd577fd55e459

### Crash Output
n/a

### Expected Behavior
Terraform should see that the resource(s) already exist and should not destroy to recreate what is already there.

### Actual Behavior
Terraform wants to destroy the same resources that were already created, just to create them again.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. Pass in a value of `STG` for the deploymentEnvironment variable.
4. Observe 2 resource groups created
5. Uncomment line 16 in main.tf so that the count argument is used as a conditional.
6. `terraform plan`
7. Pass in a value of `STG` for the deploymentEnvironment variable.
8. Observe that Terraform wants to destroy the secondaryRegion resource just to create it again.

### Additional Context
I'm working with a multi-region module that will create resources in different regions of Azure if it is a PROD or STG environment. For other environments, like dev/qa, we are satisfied with just 1 region. 

### References
n/a

**Comment by jbardin** [comment]
Hi @ajklotz 

I understand how this behavior can be confusing at first. Because the address of the resources is different when you have `count` defined in the module then when you don't, terraform sees those as entirely different instances, e.g. `module.secondaryRegion.azurerm_resource_group.rg`  vs `module.secondaryRegion[0].azurerm_resource_group.rg`. 

If this is in an existing configuration you wish to migrate, then you can use the `state mv` command to rename the resources within the state to match, which would look something like along the lines of:

    terraform state mv 'module.secondaryRegion.azurerm_resource_group.rg' 'module.secondaryRegion[0].azurerm_resource_group.rg'

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. 

Thanks!

**Comment by ajklotz** [comment]
@jbardin Thanks for the tip jbardin. I would suggest that something be added to the documentation of the `count` argument that brings this to light.
