### ISSUE TITLE
Hdinsight Version 4.0 Incompatible with Hbase version

### ISSUE THREAD

**Issue by vinaykeenable** [hashicorp/terraform#26804]
Hello, I'm Vinay,

I'm using multiple azure modules with Terraform. I thought to automate HDInsight cluster with terraform which i was creating using azure portal. I have defined below configuration:
`resource "azurerm_hdinsight_hbase_cluster" "HbaseHDInsightCluster" {
cluster_version = "4.0.1000"
location = var.location
name = var.hdp_clustname
resource_group_name = var.hdp_rgname
tier = "Standard"

component_version {
hbase = "2.1.6"
}`

When i apply above configuration, i found version not compatible error

Error: failure creating HDInsight HBase Cluster "test-dev-hdp" (Resource Group "dhdp-rg"): hdinsight.ClustersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="HDI Version'4.0' is not supported for clusterType 'hbase' and componentVersion '2.1.6'.,Invalid component version for HDInsight version: 4.0 cluster type: HBase"

Could someone assist me to get rid of it?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
