### ISSUE TITLE
different value of path.root in `terraform apply` (".") and terraform console (actual absolute path)

### ISSUE THREAD

**Issue by pisto** [hashicorp/terraform#26813]
As per title. `path.root` evaluates to `"."` in `terraform apply`, which makes the variable arguably useless. In `terraform console` it returns instead the absolute path of the terraform root module. This happens both in terraform 0.13 and 0.14.

Reproducer:
```bash
cat > main.tf <<'EOF'
resource "local_file" "test" {
  filename = "output"
  content  = path.root
}
EOF
terraform init
terraform apply -auto-approve

cat output                          #returns "."
terraform console <<< path.root     #returns the actual current directory
```

**Comment by alisdair** [comment]
Hi @pisto, thanks for reporting this. I was able to reproduce the issue.

This strikes me as a bug in `terraform console`, although I'm not sure what the source is. I believe the `path.root` and `path.module` values are intended to be relative paths. You can [derive the absolute path using the `abspath` function](https://www.terraform.io/docs/configuration/functions/abspath.html), which hopefully helps with whatever your use case is here.

**Comment by pisto** [comment]
But then in what cases `path.root` becomes different than `"."`?

**Comment by alisdair** [comment]
Good question! It's different when specifying a Terraform working directory on the command-line, for example `terraform apply path/to/config`. For example:

```shellsession
$ cat 26813/main.tf
resource "local_file" "test" {
  filename = "output"
  content  = path.root
}
$ terraform apply -auto-approve 26813
local_file.test: Creating...
local_file.test: Creation complete after 0s [id=33a00c60cd8719ef07b7d04b8a3a4337f1e2e610]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ cat output
26813
```

(Note that this approach to specifying a working directory on the command-line is not recommended. See #26087 for the early steps in a future direction.)

If you're implying that `path.root` in its current form isn't as useful as it would be if it was an absolute path, then I tend to agree. But for compatibility reasons, it seems unlikely that we'd be able to change that, especially given the `abspath` function as an easy workaround.

Nonetheless, we should be consistent between `console` and other contexts. My expectation would be to fix `console`, but whoever picks this up may have a different point of view.

**Comment by pisto** [comment]
I understand thank you.

**Comment by apparentlymart** [comment]
Agreed that it seems to be `terraform console` that is "wrong" here; we generally avoid using absolute paths in configuration as much as possible because they can cause unnecessary changes when you apply the same configuration from different directories on different hosts, if you happen to use the path in the configuration of a resource.

I've not done any debugging here yet, but I do have a potential hint for whoever does: we normally pass our paths through [the `normalizePath` function](https://github.com/hashicorp/terraform/blob/master/command/meta_config.go#L29) to get them into the normalized form which is relative to the current working directory. I wonder if `terraform console` is doing something differently than the other commands (e.g. because it's working with expressions from isolated strings rather than reading from a configuration) and in the process it's neglecting to call the `normalizePath` function.

It's also true that `path.root` is largely useless when you are using Terraform as intended. It's mostly a vestige we've kept around for compatibility, but `path.module` is almost always a better thing to use because modules should usually not refer to anything outside of their own directory in order to preserve encapsulation. However, as long as we still have `path.root` implemented (and we currently have no specific plan to remove it) it would be better for it to behave the same in `terraform console` as it does in real configuration.
