### ISSUE TITLE
beta-public-cluster/scripts/wait-for-cluster.sh filter name: should be name=

### ISSUE THREAD

**Issue by samodadela** [hashicorp/terraform#26814]
Hi, 

Sorry if this is the wrong repo, but I couldn't figure out what provider this file belongs to (filename in title).

Terraform v0.12.29

Issue was that when setting up the cluster, it went in an endless loop at the end:
```
module.gke-cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): .
module.gke-cluster.module.gke.module.gcloud_wait_for_cluster.null_resource.run_command[0] (local-exec): WARNING: --filter : operator evaluation is changing for consistency across Google APIs.  name: dev-samo currently matches but will not match in the near future.  Run `gcloud topic filters` for details.
```

Problem was I already had a cluster named dev-samo2... and the original filter in wait-for-cluster.sh was matching two clusters (the new one dev-samo and dev-samo2)... resulting in a warning.

My fix was to change --filter=name:"$CLUSTER_NAME" to --filter=name="$CLUSTER_NAME".

Probably a rare case but it happened to me.

**Comment by jbardin** [comment]
Hi @samodadela 

It's difficult to say what's going on here with limited information, but this does not appear to be a Terraform issue.
Seeing how this is a script, it may belong to a module you are using as opposed to a provider.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by samodadela** [comment]
@jbardin I understand, thanks anyway and sorry for using the wrong 'channel'. 

I found it, the file in question is this one:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/scripts/wait-for-cluster.sh

and the problem mentioned was already fixed on Nov 3, 2020 :)
