### ISSUE TITLE
Manually specifying resource ids in config files.

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#2682]
Currently, if you were to move a resource into a new module and its id was based on a computed value, it will tear down the old thing and bring up a new one. This makes refactoring one's terraform config a pain after you've stood up everything. Of course terraform makes it easy to tear things down and bring them up again, but it would be preferable to not do this if we don't have to.

My idea was to allow the schema to specify which of a resource's attributes is the id by default, but allow one to override this in the config. For example:
```
resource "aws_instance" "foo" {
  id = "foo.aws.mydomain.com"
  …
}
```
I'm not sure if the id is sufficient for tracking a resource when it moves around, but this is mostly just a "thinking" issue to get some thoughts/feedback on the idea.

**Comment by phinze** [comment]
The state storage is organized by module, which would make manually specifying resource IDs like you propose difficult, but I totally agree that the core problem of being unable to move resources between modules is a real one.

The central discussion of this problem is over in #591, which I'll reopen (I think it was closed mistakenly). Over there the key idea is to add a first class "migrate" or "rename" operation to tell terraform to rewrite the state so resource recreation is not necessary after config refactoring.

I'll close this so we can consolidate the discussion, but feel free to chime in over there. :+1:

**Comment by thegedge** [comment]
Ahh, my bad for not checking the closed issues. Thanks, @phinze!
