### ISSUE TITLE
Terraform 0.14 puts quotes around output

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform#26831]
In Terraform 0.13, there were no quotes around variable outputs. I have a test that runs in a CI system that parses a `terraform output` to get a file path. This job broke when I used version `0.14-beta2` with the job. It works with 0.13. A simple reproducer below shows the difference: 0.14 puts quotes around the output.

### Terraform Version

`0.14-beta2` and locally compiled v0.14.0-dev @ 13d70844d7638cd12b67f2cd9184458893eb2032

### Terraform Configuration Files

```terraform
resource "null_resource" "test" {
}

output "null_resource" {
  value = null_resource.test.id
}
```

### Debug Output

```
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=2909257498027488865]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

null_resource = "2909257498027488865"
[dakini@dax 20201105]$ terraform output null_resource
"2909257498027488865"
[dakini@dax 20201105]$ terraform version
Terraform v0.14.0-dev
```

When I try this same Terraform config and command with version 0.13, it does not quote the output.

```
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=432950258144992916]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

null_resource = 432950258144992916
[dakini@dax 20201105]$ terraform0.13.3 output null_resource
432950258144992916
```

### Crash Output
N/A

### Expected Behavior

The output should be the same in 0.14 as 0.13 (unquoted).

### Actual Behavior

0.14 puts quotes around the output, which caused one of my TC test jobs to fail, since the output was a file path.

### Steps to Reproduce

1. Use Terraform version 0.13 to `terraform init; terraform apply; terraform output null_resource`.
2. Use Terraform version 0.14 to `terraform init; terraform apply; terraform output null_resource`.
3. Compare the output between the two versions.

### Additional Context

This failed in a TC test and on my local system (linux).

### References

Here are the state files, in case those help. I thought there might have been a difference in here, but they look pretty much the same.

https://gist.github.com/dak1n1/237f77eb54e386163abd0aa8acefaec4

https://gist.github.com/dak1n1/d31df120ddfd33f109438dcf13d88614

**Comment by jbardin** [comment]
Hi @dak1n1 

Thanks for the feedback. This was likely a result of cleaning up the output to better reflect the underlying types involved, and make the format more consistent, but I'm not certain when that change actually happened. 

From a quick test here, both 0.13 and 0.14 output `null_resource_id = "7965343464315133785"`. Are you certain this was the case with the latest 0.13 release as well?

That output however is not meant to be machine readable. For a stable, machine readable interface, we have the `-json` flag to format the data:

```
% tf show -json | jq .values.outputs.null_resource_id.value
"7965343464315133785"
```

**Comment by pkolyvas** [comment]
Hi @dak1n1,

Thanks for taking the time to report this. It's a discussion we've been preparing to have as we move to Terraform 1.0.

This change, in particular, is part of a group of small changes we're introducing in 0.14 that we don't consider breaking and I'll try to explain why here.

We consider the console output of Terraform human readable, specifically designed and optimized for operators and practitioners to review themselves. As a result we can tweak that output to help improve consistently, clarity, actionability and more. 

In order to provide a stable surface area for using Terraform in automation, we encourage our community to rely on outputs (not to be confused with `terraform output`) produced with the `-json` command line option. This includes `terraform output -json`, `terraform version -json` and `terraform show -json` (for creating versions of the plan and state in JSON).

As we mature and evolve Terraform we're hopeful this delination will produce better results for both interactive, practitioner-focused workflows and automated workflows where Terraform is part of a larger system.

**Comment by jbardin** [comment]
Sorry, i read too quickly, and was assuming `terraform show`, which has a slightly different format. Regardless, @pkolyvas covered the context of the change regarding the _correct_ command here :)

**Comment by dak1n1** [comment]
I see, it's working as designed then. I'll just leave this shell command here because others are probably using `terraform output` like I was in CI jobs and shell scripts. In some cases, they'll have to update those scripts to remove the quotes from the output.

In terraform version < 0.13.5, the command was:

```
$ terraform output
3948372125284964950
```

In version 0.14+, use the -json flag and the quotes can be removed by selecting the resource name in `jq`:

```
$ terraform output -json | jq -r .null_resource.value
3948372125284964950
```

**Comment by alisdair** [comment]
Thanks for that example! In PR #26844 I added it to the output CLI docs, along with some other updates and a more explicit note that we recommend using `-json` for automation tasks.
