### ISSUE TITLE
Behaviour change in 0.13 on plans when using reference and data source

### ISSUE THREAD

**Issue by umairidris** [hashicorp/terraform#26857]
### Terraform Version

```
0.13.5
0.12.29

provider registry.terraform.io/hashicorp/google v3.47.0
```

### Terraform Configuration Files

```terraform
# main.tf
resource "google_compute_network" "network" {
  name = "vpc-network"
  project = "abc"
}

module "impl" {
    source = "./module"
    network = google_compute_network.network.name
    project = google_compute_network.network.project
}

# module/main.tf
variable "network" {}
variable "project" {}

data "google_compute_network" "network" {
  name    = var.network
  project = var.project
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = data.google_compute_network.network.self_link
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["abc"]
}
```

### Debug Output

[tf13.txt](https://github.com/hashicorp/terraform/files/5513507/tf13.txt)
[tf12.txt](https://github.com/hashicorp/terraform/files/5513508/tf12.txt)

### Expected Behavior

`terraform plan` succeeds like it used to in tf 0.12

### Actual Behavior

`terraform plan` fails

```
Error: Required attribute is not set

  on module/main.tf line 10, in resource "google_service_networking_connection" "private_vpc_connection":
  10:   network                 = data.google_compute_network.network.self_link
```

### Steps to Reproduce

1. alias terraform 0.12 binary to `terraform12` and terraform 0.13 to `terraform13`
1. Run `terraform12 init`
1. Run `terraform12 plan`
1. Observe it succeeds
1. Run `terraform13 init`
1. Run `terraform13 plan`
1. Observe the error above 

### Additional Context

- The above error only occurs when either the project or network does not exist (e.g. on the initial terraform plan). It will work if both project AND network exist. Looking at the debug output, it seems in 0.13 it calls the data source lookup func and sees a NOT FOUND error whereas in 0.12 it understands its a reference of a new resource and seems to skip it?

- It seems like the data source for compute network does not return an error on 404s (https://github.com/hashicorp/terraform-provider-google/blob/d7c5cf3906e513e425e2be4d5ea4973bfdc5b6c3/google/data_source_google_compute_network.go#L62) but rather just logs. Had this returned an error it seems like the plan would have failed sooner and shown a not found error.

**Comment by jbardin** [comment]
Hi @umairidris 

The conclusion about the data source implementation is correct, they are usually expected to return an error when the resource is not found. While there is no strict rule to how a data source is implemented, it usually makes sense to fail when a single value was requested and not found; while other semantics can be applied when filtering N number of values to N number of outputs. This is an issue you would have to raise with the Google provider itself. 

In the general case, this is one of the reasons why we do not recommend using a data source to read a resource that is otherwise already defined in the configuration. It would be preferable to pass all the required information into the module directly from the `google_compute_network.network`. The fact that this initially succeeds in 0.12 was mostly accidental, and it would still can fail unexpectedly later on if `google_compute_network.network` were changed, since the data source would read the existing resource before the new one was created. 

Thanks!

**Comment by umairidris** [comment]
Hi @jbardin,

Thanks for your comment. Unfortunately I do believe this is an unintentional breakage caused by supporting depends_on for modules.

When I add an explicit depends_on field on the module then I see the same behaviour as terraform 0.12 respected. Also, the data source explicitly states that it will be read on apply as it refers to values not known.

Config modification:
```
resource "google_compute_network" "network" {
  name = "vpc-network"
  project = "foo"
}

module "foo" {
  source = "./module"
  network = google_compute_network.network.name
  project = google_compute_network.network.project
  depends_on = [google_compute_network.network] # Added this line.
}
```

Plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # google_compute_network.network will be created
  + resource "google_compute_network" "network" {
      + auto_create_subnetworks         = true
      + delete_default_routes_on_create = false
      + gateway_ipv4                    = (known after apply)
      + id                              = (known after apply)
      + mtu                             = (known after apply)
      + name                            = "vpc-network"
      + project                         = "foo"
      + routing_mode                    = (known after apply)
      + self_link                       = (known after apply)
    }

  # module.foo.data.google_compute_network.network will be read during apply
  # (config refers to values not yet known)
 <= data "google_compute_network" "network"  {
      + description            = (known after apply)
      + gateway_ipv4           = (known after apply)
      + id                     = (known after apply)
      + name                   = "vpc-network"
      + project                = "foo"
      + self_link              = (known after apply)
      + subnetworks_self_links = (known after apply)
    }

  # module.foo.google_service_networking_connection.private_vpc_connection will be created
  + resource "google_service_networking_connection" "private_vpc_connection" {
      + id                      = (known after apply)
      + network                 = (known after apply)
      + peering                 = (known after apply)
      + reserved_peering_ranges = [
          + "abc",
        ]
      + service                 = "servicenetworking.googleapis.com"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

**Comment by jbardin** [comment]
Hi @umairidris 

From your the description, this still sounds like the intended behavior. 

When you say that data sources are "no longer respecting references", that sounds like you're referring to the behavior described in #25961. This implicit deferral of data sources was undefined, and also cases other hard to diagnose issues since the data source would not be deferred when the managed resource was updated.

Having a data source that reads a managed resource created elsewhere in the same configuration is still not recommended, and will either require referencing a computed attribute of that resource, or an explicit `depends_on` reference to defer reading. The resolution to 25961 however introduces an exception to this in 0.14 -- as a compromise _direct_ references from a data source to a managed resource will behave the same as a `depends_on` reference. Because his is not a recommended way to change the evaluation order, and we do not want to change how data sources are evaluated in modules not expecting the change, this behavior is not extended transitively through the configuration.

**Comment by umairidris** [comment]
Thanks for the in depth explanation and referencing to the related issue.

I will try to break up our usage of resources + data sources by either using separate deployments or removing the data source (some of these are non trivial as the modules are not maintained by us). We will consider using explicit depends_on as a workaround in the meantime.
