### ISSUE TITLE
Resource dependency fails for resource name used as variable to a module

### ISSUE THREAD

**Issue by josemaia** [hashicorp/terraform#26853]
In a scenario where I am referencing a resource as a parameter to a module, the module attempts to be created before the module, after upgrading to 0.13.x from 0.12.x.

### Terraform Version
```
0.13.5
```

### Terraform Configuration Files

```terraform
resource "azurerm_resource_group" "rg-shared-images" {
  name     = "${var.proj_prefix}-shared-img-gallery-rg"
  location = var.location
}

resource "azurerm_resource_group" "rg-packer-build" {
  name     = "${var.proj_prefix}-packer-build-rg"
  location = var.location
}

resource azurerm_shared_image_gallery main {
  name                = "${var.proj_prefix}_shared_img_gallery"
  location            = azurerm_resource_group.rg-shared-images.location
  description         = "${var.proj_prefix} shared images"
  resource_group_name = azurerm_resource_group.rg-shared-images.name

}

module "ubuntu-base-image" {
  source              = "../../modules/azure/shared-image"
  name_prefix         = var.proj_prefix
  resource_group_name = azurerm_resource_group.rg-shared-images.name
  image_name          = "ubuntu-base"
  gallery_name        = azurerm_shared_image_gallery.main.name

}

```
With this setup, Terraform attempts to create the module ubuntu-base-image before creating the shared image gallery.

Inside the module, the variable gallery_name is being used in a data object, but I'm not sure that is relevant.
```
data azurerm_shared_image_gallery main {
  name                = var.gallery_name
  resource_group_name = var.resource_group_name
}
```

### Expected Behavior
Terraform solves the dependency tree and creates the resource group & gallery before invoking the base_image module.

### Actual Behavior
Critical error when applying the terraform.
```
CRITICAL:abzu_modules.hashicorp.terraform:Terraform error: 
Error: Shared Image Gallery "projname_shared_img_gallery" (Resource Group "projname-shared-img-gallery-rg") was not found

 

  on ../../modules/azure/shared-image/main.tf line 2, in data "azurerm_shared_image_gallery" "main":
   2: data azurerm_shared_image_gallery main {

 ```

### Steps to Reproduce
1. terraform init/plan/apply 
2. verify error happens
3. add explicit definition `depends_on = [azurerm_resource_group.rg-shared-images, azurerm_shared_image_gallery.main]`
4. run again and verify it works

**Comment by jbardin** [comment]
Hi @josemaia 

While you haven't provided the source if the `ubuntu-base-image` module, what you're describing sounds like the expected behavior for this configuration. 

The dependency tree is correct, but data sources are read as early as possible. The order which happens here (in the upcoming 0.14 which has no separate refresh phase) is that `azurerm_shared_image_gallery.main` is planned, and when the `data.azurerm_shared_image_gallery.main` configuration is complete, that resource is read. The only way right now to ensure that it waits for `azurerm_shared_image_gallery.main` to be created, is to use a computed output of that resources. As you've stated, adding `azurerm_shared_image_gallery.main` to `depends_on` can work around this situation.

This is one reason we do not recommend using data sources to read managed resources which are created within the same configuration. The usual pattern here would be to pass all the required information from `azurerm_shared_image_gallery.main` into the module, and forgo the data source altogether. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by josemaia** [comment]
Thank you for the quick reply! Will look into rewriting this module at a later date to avoid the data source, but for now the explicit depends is fine.
