### ISSUE TITLE
Expose crypto/tls.Config.KeyLogWriter for debug packet sniffing

### ISSUE THREAD

**Issue by woodhull** [hashicorp/terraform#26869]
### Current Terraform Version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/http v2.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/trois-six/sendgrid v0.1.3

### Use-cases
We would like to use Wireshark to debug the raw API calls a provider is making and understand the root cause of the problems we're seeing. The API requests are encrypted so we would need to log the TLS keys to decrypt the API traffic between our laptop and the remote service. Some other apps like chromium allow setting a path to a log file via `SSLKEYLOGFILE` env variable. 

It looks like the Go networking config option for this is `crypto/tls.Config.KeyLogWriter`

### Attempted Solutions
The provider in question does not seem to do any debug logging. We'll have to fork it otherwise and modify the go code to log what it's doing more thoroughly. There are probably still some cases where lower level debugging is useful though. 

### Proposal
Either support SSLKEYLOGFILE or some other mechanism for helping people trying to perform debugging of provider's networking behavior. 

There may be some other way to do better HTTP API request debugging with terraform, I'm not so familiar with `go` or terraform internals. Our next move is going to be learning just enough go to fork the provider in question.

**Comment by jbardin** [comment]
Hi @woodhull 

The Terraform providers run in a separate process, so there is no way for terraform to setup their tls configuration. This would have to be done for each provider, and possibly even independently for the various client libraries they use to connect to the remote APIs. Since debugging API calls is not an uncommon need, the providers and/or their client libraries often already have a way to log the complete requests and responses. If that isn't sufficient, or the actual wire requests are really needed, then building a local version for debugging would be necessary.

Since this isn't something that can be done in terraform, I'll close this out here. If you have more questions about debugging, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
