### ISSUE TITLE
Terraform Registry incorrectly cached an API 404 response

### ISSUE THREAD

**Issue by jacobwgillespie** [hashicorp/terraform#26890]
Hello, apologies if this is the wrong place for registry.terraform.io issues, I could not find an obvious place to report them. It appears that the registry's API cache has cached a provider version as a 404, specifically `rancher/rancher2` version 1.10.6.

This request is currently returning 404, even though the release exists: https://registry.terraform.io/v1/providers/rancher/rancher2/1.10.6/download/linux/amd64

Appending a query parameter bypasses the cache and returns the release: https://registry.terraform.io/v1/providers/rancher/rancher2/1.10.6/download/linux/amd64?a=b

Is it possible to get this cache cleared? Or any alternative workarounds that would prevent the issue?

Related to https://github.com/rancher/terraform-provider-rancher2/issues/516

**Comment by apparentlymart** [comment]
Hi @jacobwgillespie,

This repository is indeed not typically monitored by the registry team, but I've labelled it with the "registry" label so that they might find it if they _do_ come and check in here.

In the meantime though, my understanding (which is not 100% certain, because I don't work directly on the Registry) is that the longest cache TTL for any object types in the registry is 24 hours -- with some endpoints using a shorter TTL -- and so even if nobody takes any specific action here I'd expect it to begin working again by this time tomorrow. If not, I'll try my best to draw attention to this with folks who are empowered to investigate it further.

**Comment by jacobwgillespie** [comment]
@apparentlymart perfect thanks, I'll check back tomorrow, hopefully it clears in 24 hours 👍 

Is there a recommended way to report issues to the registry team, besides this repo?

**Comment by rawmind0** [comment]
Terraform registry cache has been refreshed and rancher2 provider v1.10.6 should work properly now

**Comment by jacobwgillespie** [comment]
Working for me - closing this issue. ✅
