### ISSUE TITLE
Data source using dynamic provider fails at plan time if provider variables are not available yet

### ISSUE THREAD

**Issue by saguziel** [hashicorp/terraform#26904]
### Terraform Version
0.13.5

### Terraform Configuration Files
```
terraform {
  backend "s3" {
    bucket         =  "bucket"
    key            = "cluster"
    region         = "us-west-2"
    dynamodb_table = "terraform-state-lock"
  }
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
    }
  }
}
```
### Crash Output
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.databricks_group.admins: Refreshing state...

Error: Host is empty, but is required by basic_auth

### Expected Behavior
Plan should succeed, and the error should not happen at plan time.

### Actual Behavior
The above error happens

### Steps to Reproduce
In a brand new terraform dir, run plan on

```
resource "databricks_mws_workspaces" "this" {
  account_id      = "account"
  workspace_name  = "blah"
  deployment_name = "blah"
  aws_region      = "us-west-2"

  credentials_id            =  "a"
  storage_configuration_id  =  "a"
  network_id                = "a"
  verify_workspace_runnning = true
}

provider "databricks" {
  alias    = "created"
  username = "user"
  password = "pass"
  host     = databricks_mws_workspaces.this.workspace_name
}

data "databricks_group" "admins" {
  provider     = databricks.created
  display_name = "admins"
}
```

This will cause the above error message. Note that replacing the data source with a resource (using the same dynamic provider) will work correctly. Also, putting a `depends_on=...` into the data source to depend on some resource will work as well (especially one using the same dynamic provider).

**Comment by jbardin** [comment]
Hi @saguziel 

In order to read a `databricks` data source, the `databricks` provider must be fully configured. There is no concept in terraform of a "dynamic provider", as the provider will be used as configured when it is needed. In general a provider should not ever require the output of a managed resource for this reason, however some providers do allow being partially configured during planning in order to accommodate some particular use cases.

You may be able to work around this by forcing `data.databricks_group.admins` to depend on `databricks_mws_workspaces.this` by using `depends_on = [databricks_mws_workspaces.this`, as long as the data source is not required for planning purposes.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
