### ISSUE TITLE
How to use for_each with condition

### ISSUE THREAD

**Issue by lynnli92** [hashicorp/terraform#26907]
I want to use for_each in resource, but based on the condition of a variable to decide create this module or not.
My resource will be like

locals {
 iterator = zipmap (name_list, map)
}
resource "monitoring" "alarm" {
 for_each = var.create ?  local.iterator : null
 name = each.value["name"]
 query  = each.value["query"]
...
}
Error :
The given "for_each" argument value is unsuitable: the given "for_each"   
argument value is null. A map, or set of strings is allowed.   

It seems I can not use null over here. What should be a good type for this condition then ?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
