### ISSUE TITLE
local_file with depends_on no longer works in 0.13 - prevents use of dynamic local files

### ISSUE THREAD

**Issue by driskillb43** [hashicorp/terraform#26939]
Terraform appears to no longer respect the depends_on on a local_file data source. It is immediately attempting to open the file on plan/apply. For example, given the following:

```
resource "null_resource" "create_file" {
  triggers = {
    start = timestamp()
  }

  provisioner "local-exec" {
    command = "<create file command>"
  }
}

data "local_file" "created_file" {
  filename = "<create_file_location>"

  depends_on = [null_resource.create_file]
}
```

Using something like above, results in the following error:

Error: open <created_file_location>: no such file or directory

This works fine in 0.12 and before. The note on the following page details this use case: https://www.terraform.io/docs/configuration/functions/file.html. 

"We do not recommend using dynamic local files in Terraform configurations, but in rare situations where this is necessary you can use the local_file data source to read files while respecting resource dependencies."

I assume this change is due to the changes in plan/apply in 0.13

**Comment by jbardin** [comment]
Hi @driskillb43 

The example you provided would work in 0.13 as shown, but I think you may be implying that the file could be removed between runs of terraform, in which case you would et this error. While having a file generated in this manner is not recommended, the file does still need to always exist after the initial creation in order for the data source to succeed. You may be able to work around this by using `-refresh=false` in 0.13, which would prevent the data source from being evaluated before the resource could be planned. 

The changes introduced in 0.14 allow terraform to more accurately plan data sources, as reading the data source can now be made conditional based on the evaluation of managed resources. Testing the configuration here confirms that it can work as expected in 0.14.

Closing as this is both the expected behavior of 0.13, and the 0.14 enhancements will result in the desired behavior in this situation.

Thanks!
