### ISSUE TITLE
Module declaration makes terraform look up provider in hashicorp namespace

### ISSUE THREAD

**Issue by awangc** [hashicorp/terraform#26945]
### Terraform Version

```
❯ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/vinyldns/vinyldns v0.9.5
```

### Terraform Configuration Files

Clone the following repo:
```
https://github.com/awangc/tf_test
```

### Debug Output

https://gist.github.com/awangc/317c53980565e42568d1ec2dad9c7071

### Expected Behavior

Terraform init succeeded. The look up for latest version of vinyldns provider should have been under the `vinyldns` namespace

### Actual Behavior

Terraform init failed, the look up for latest version of vinyldns provider was under `hashicorp` namespace
### Steps to Reproduce

git clone https://github.com/awangc/tf_test
cd tf_test
terraform init

### Additional Context

If the `module` [block](https://github.com/awangc/tf_test/blob/9d8411897501e9890d56c1ac27781d866e33a7c1/main.tf#L10-L12)  is removed, then terraform init succeeds.

**Comment by alisdair** [comment]
Hi @awangc. The issue here is that your module does not include a `required_providers` block for the vinyldns provider. [Provider requirements should be specified for each module which uses the provider](https://www.terraform.io/docs/configuration/provider-requirements.html#requiring-providers), not just the root module. Adding the same `required_providers` block to your child module should resolve the issue. Hope this helps!
