### ISSUE TITLE
Templatefile and object type - Error with object required

### ISSUE THREAD

**Issue by toytown** [hashicorp/terraform#26958]
```terraform

v.0.13.5
```

### Debug Output

Variables.tf

variable "map_roles" {
  description = "Additional IAM roles to add to the aws-auth configmap"
  type = list(object({
    rolearn  = string
    username = string
    groups   = list(string)
  }))
  default = []
}

  eks.tf 

  map_roles = [templatefile("${path.module}/templates/map-roles.tpl", {
           cluster_admin_arn   = aws_iam_role.cluster_admin.arn
  })]

### Crash Output
The given value is not suitable for child module variable "map_roles" defined
at .terraform/modules/eks/variables.tf:62,1-21: element 0: object required.

### Expected Behavior
Not sure what the templatefile function should return incase the type is list of object

### Actual Behavior
Error if variable is of type list of object

**Comment by jbardin** [comment]
Hi @toytown 

Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
