### ISSUE TITLE
Show Rendered Output in terraform plan for template_dir 

### ISSUE THREAD

**Issue by infa-pavakuma** [hashicorp/terraform#26957]
template_dir does not show the rendered output while executing the terraform plan command. However the template_file  shows the rendered output while executing terraform plan. Please add the feature to show the rendered files ( files in the sub-directories also ) while executing terraform plan for template_dir resources. 

Terraform version:
Terraform v0.12.28

**Comment by apparentlymart** [comment]
Hi @infa-pavakuma,

This seems to be a feature request for the `template` provider rather than for Terraform CLI, so there's nothing we could change in _this_ repository to get the result you are requesting.

Normally I'd refer you to [the `template` provider repository](https://github.com/hashicorp/terraform-provider-template), but the team that was maintaining the provider [has now archived it to mark it as deprecated](https://github.com/hashicorp/terraform-provider-template/issues/85). The existing versions of the provider remain available, but my understanding is that the existing functionality is frozen and the team doesn't plan to make any further releases.

The announcement I linked above about the provider being archived includes a link to [the `hashicorp/dir/template` module](https://registry.terraform.io/modules/hashicorp/dir/template/latest) as the suggested replacement for `template_dir`. That replacement module renders templates in memory rather than on disk, so using it might address the concern you raised here about the results not being visible in the plan output, depending on how you use the rendered template.

We use the issues in this repository to represent bugs and enhancement requests in the main Terraform CLI releases, so I'm going to close this issue. If you have further questions about using the `hashicorp/template/dir` module then I'd suggest starting a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), which is a good place for general Terraform questions and concerns. Thanks!
