### ISSUE TITLE
Request to add explicit details of limitation of using Variables

### ISSUE THREAD

**Issue by hashitop** [hashicorp/terraform#27016]
### Current Terraform Version

```
Any version
```

### Use-cases

Going through the content of this document and unable to find limitation of use cases when using Variables, for example, interpolation is not allowed

https://www.terraform.io/docs/configuration/variables.html

### Proposal

Requesting to add a section to explicitly describe limitation on what allowed and what not, for example, 

- Interpolation is not allowed
- Customer Validation support all built-in TF functions

### References

https://www.terraform.io/docs/configuration/variables.html
https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules

**Comment by apparentlymart** [comment]
Hi @hashitop!

Looking at the page you linked to, it already seems to contain statements confirming the rules you mentioned here:

> The variable declaration can also include a `default` argument. If present, the variable is considered to be _optional_ and the default value will be used if no value is set when calling the module or running Terraform. **The `default` argument requires a literal value and cannot reference other objects in the configuration.**

> The `condition` argument is an expression that must use the value of the variable to return `true` if the value is valid, or `false` if it is invalid. **The expression can refer only to the variable that the condition applies to, and must not produce errors.**

and for calling functions, the two examples in the documentation both include function calls.

I assume you're raising this because someone asked a specific question that wasn't covered at all or wasn't described well enough on the documentation page. If so, it would be helpful to know what that question was or what the person who asked the question found confusing, so that we can understand what parts of the existing content we should revise in order to make it clearer.

Thanks!

**Comment by mildwonkey** [comment]
I'm going to close this, since there hasn't been a response, but if you are still experiencing a problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
