### ISSUE TITLE
Azurerm_app_service -> site_config -> Platform-settings -> HTTP Version (1.0/2.0)

### ISSUE THREAD

**Issue by roshanp85** [hashicorp/terraform#27012]
I could not find a terraform settings for the attached image. Could you please guide us for the below, and if we don't have terraform configurations for this, can we create one, over the next Terraform provider.

Go to App-service->Configuration->General Settings->HTTP Version

![image](https://user-images.githubusercontent.com/53309302/99984614-495d2300-2d7b-11eb-8a0a-87fcdc8a199c.png)

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
