### ISSUE TITLE
Include jq in docker.io/hashicorp/terraform:light container image?

### ISSUE THREAD

**Issue by devurandom** [hashicorp/terraform#27025]
### Current Terraform Version

```
v0.13.5
```

### Use-cases

In my CI/CD pipeline I want to apply changes only when certain conditions are met (e.g. changes to certain resources are not allowed without confirmation).

### Attempted Solutions

I would like to use `terraform show -json my.tfplan | jq 'select(.change.actions != ["no-op"]) | .address' | grep ...` to inspect the Terraform Plan and abort the CI/CD deployment if certain conditions are violated.

### Proposal

Include `jq` (<4MB) in the docker.io/hashicorp/terraform:light container image, so I can use it in my CI/CD pipeline in the deployment step.

I could roll my own container image, but then I would have to maintain it and keep it updated with changes to the docker.io/hashicorp/terraform:light image. It seems easier and also more useful to the general public to include `jq` with terraform, given that it already contains `git` and `ssh`, which are likely even larger than `jq`.

### References

I could not find similar requests.

**Comment by apparentlymart** [comment]
Hi @devurandom! Thanks for this feature request.

We don't plan to include any additional software in the official Docker images. You're right that `git` is already included, a historical decision that we are now bound to for backward compatibility, but each new piece of software we might add is another bit of surface area where we need to worry about upgrading it when new releases become available, supporting it if it turns out to be built/installed incorrectly, etc.

The Terraform docker images are intended for direct use with `terraform run` to run _just_ Terraform, and any other software that happens to be installed in the images today is an implementation detail subject to change. If you are using a CI system which uses Docker images as the primary encapsulation for jobs, I would recommend using our images directly because future versions may change which other software is available in ways that could impact your CI jobs, such as no longer including `grep` or including a different version of `grep` with different features.

Instead, I'd suggest to build your own image based on an operating system image that includes the software you want. `terraform` executables are statically linked so you should be able to copy one into any Linux docker image and have it work, regardless of other details of the OS such as which libc it uses.

While I appreciate your use-case, it's not a problem our Docker images are intended to be used for and we don't have the resources to support a full operating system base image for CI systems.

Thanks again for this feature request! If you have any follow-up questions about building docker images with Terraform installed, feel free to start a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core/27).
