### ISSUE TITLE
Allow stopping apply on failure

### ISSUE THREAD

**Issue by saulshanabrook** [hashicorp/terraform#2702]
I would love to be able to stop `apply` on any failure, instead of continuing on.

I am trying to provision an AWS cluster, and when one thing fails (maybe because a resource already exists), I really have to re-run the whole apply again. Because if I don't the `.tfstate` file is left in a weird place. The point is basically, sometimes when it fails it means I have to tear down the whole cluster manually, because `terraform destroy` won't even work after. That is fine, but it would just be helpful if it stopped after the first failure, so that I didn't have as many resources to clean up.

**Comment by catsby** [comment]
Thanks for writing in @saulshanabrook , this is an interesting idea.
Right now we're trying to clean up a bit for a bug fix release soon, so I'm marking this as "thinking" and we'll come back to it and discuss feasibility.

In the meantime, I've found that a single `cntrl+c` will stop the process and generally leaves my `.tfstate` file in good shape. I'm not sure I recommend that regularly, but it's worked enough for me when testing some things out. 

Thanks!

**Comment by saulshanabrook** [comment]
@catsby Makes sense. Yeah I have been using  `cntrl-c`  to stop and that works great, just sometimes tricky to get the timing right and requires monitoring the process closely.

**Comment by apparentlymart** [comment]
Hi @saulshanabrook! Sorry for the long silence here.

Terraform's current behavior is to stop as soon as it encounters an error, although since it can perform multiple operations concurrently it will conclude anything that was already started before exiting. The `-parallelism=1` option on the command line would prevent this sort of concurrent action, ensuring that a failure will stop Terraform as soon as possible, but at the expense of the overall operation taking longer.

Since Terraform already behaves in this way, I'm going to close this out. Since this is an old issue, I can't identify any specific changes that addressed it, but Terraform's current behavior as of the latest release does meet this request. Sorry again for leaving this open so long.
