### ISSUE TITLE
Terraform Plan/Apply Error: AccessDenied: Access Denied status code: 403, request id:

### ISSUE THREAD

**Issue by mohamednazarae** [hashicorp/terraform#27022]
### Terraform Version

0.12.28

### Terraform Configuration Files

```terraform
...
```

### Debug Output

Error: AccessDenied: Access Denied
	status code: 403, request id: XXXXXXX, host id: XXXXXXXXX

### Expected Behavior

Terraform must show the plan and apply the changes.

### Actual Behavior

Its refreshing the state file but not showing plan and not applying the changes. Not able to to find what permission that I dont have

### Additional Context

I do see lot of other conversation but those are all related to backend access problem with S3 but I am able to access S3 while running backend command. I can even refresh the state file information.

**Comment by alisdair** [comment]
Hi @mohamednazarae. This doesn't seem like a Terraform bug report, as the issue is almost definitely a lack of permissions. Instead it looks like a question about how to debug the permissions issue. We use GitHub to track bugs, and [our discussion forum is the best place to ask questions](https://discuss.hashicorp.com/c/terraform-core/27).

To try to diagnose the issue further, I would recommend setting the `TF_LOG=trace` environment variable to get more information, [as described in the Terraform debugging guide](https://www.terraform.io/docs/internals/debugging.html). If that doesn't work out for you, I recommend posting in the forum to ask for suggestions.
