### ISSUE TITLE
Add ability to pass provisioner information on the command line

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#27080]
### Current Terraform Version

```
Terraform v0.12.28
```

### Use-cases

Pass the role_arn of an AWS provisioner on the command line allowing use of different roles without needing to change the provider block in a tf file.  Similar to how a secret, key, token, region can be passed via env vars right now.  Ideally, those, too, could be passed on the command line as well.

Specifically, I'd like to call a terraform module from the HashiCorp repo directly (rather than with a wrapper tf that uses 'module' to invoke the module, passing it provisioner information even though those modules don't have a provisioner block.

### Attempted Solutions

N/A

### Proposal

Add a command line arg, `-default-provisioner` that takes a json object representing the provisioner config.

### References

N/A

**Comment by apparentlymart** [comment]
Hi @silvermy ,

This seems to be a feature request for the AWS provider rather than for Terraform CLI, so you'll need to record it in [the provider's own repository](https://github.com/hashicorp/terraform-provider-aws) rather than here.

With that said, if your need is to configure the AWS provider with `assume_role` for a third-party child module then you can define the provider configuration in your root module and [pass it either implicitly or explicitly](https://www.terraform.io/docs/configuration/meta-arguments/module-providers.html) to the child module. If you have any questions about that, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
