### ISSUE TITLE
Terraform 14, fmt quotes

### ISSUE THREAD

**Issue by dzirg44** [hashicorp/terraform#27102]
I've noticed that since version 14, fmt sub-command  adds quotes to all resources. Maybe I missed something in change logs....

### Terraform Version
```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tfe v0.21.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
+ provider registry.terraform.io/hashicorp/vault v2.16.0
```

### Expected Behavior
Format and doesn't change quotes 

### Actual Behavior
It adds quotes

### Steps to Reproduce
`terraform fmt`

**Comment by apparentlymart** [comment]
Hi @dzirg44,

What you have observed is the intended behavior. Block labels in quotes is the style that the Terraform documentation has always shown.

Over time `terraform fmt` will gradually implement more of the style conventions reflected in the Terraform documentation, due to its goal of establishing a consistent style for Terraform configuration across codebases. You can read more about the goals of the `terraform fmt` command in [its documentation](https://www.terraform.io/docs/commands/fmt.html).
