### ISSUE TITLE
Unwrapping native golang errors from Diagnostics

### ISSUE THREAD

**Issue by 14leeyuchieh** [hashicorp/terraform#27117]
I use Diagnostics in one of our internal projects for static analysis on Terraform DSL, and it would be really nice if I could check if a nativeError is wrapped within a `Diagnostics`, especially since our library will be public and this would help clients unwrap errors from the underlying Diagnostics. For example, referencing https://golang.org/pkg/errors/#Is, the below would be great:
```go
package main

import (
        "github.com/hashicorp/terraform/tfdiags"
	"errors"
	"fmt"
	"os"
)

func main() {
       var retDiags tfdiags.Diagnostics
       var NotFoundErr = errors.New("Slice not found")
       retDiags = retDiags.Append(NotFoundErr)
       retDiags = retDiags.Append(errors.New("another error"))
       fmt.Println(errors.Is(retDiags.Err(), NotFoundErr))
       // Output: true
}

```
This requires [diagnosticsAsError .Error](https://github.com/hashicorp/terraform/blob/c258e8efbb3146a79f3e47ce934722580407036d/tfdiags/diagnostics.go#L196) to wrap native golang errors with `%w` when converting to a single string.

Alternatively, if the receiver  `diagnosticsAsError` is accessible outside the  package or the functionality of[`WrappedError`](https://github.com/hashicorp/terraform/blob/c258e8efbb3146a79f3e47ce934722580407036d/tfdiags/diagnostics.go#L226) is accessible, I can implement my own `Contains` on the diagnostics and achieve the same effect. But I would much prefer option 1.

**Comment by apparentlymart** [comment]
Hi @14leeyuchieh,

Nothing in this repository is supported for use as a Go library. If you find the functionality in the `tfdiags` package useful for your internal application then I'd encourage you to fork some or all of it into a codebase that you control and develop it from there, under the terms of the open source license. Future versions of Terraform may include breaking changes to any of the Go packages in this codebase because we consider this codebase to be an application, not a library.

We don't have the need you mentioned here so we don't intend to change Terraform's own `tfdiags` package to include this capability, but of course if you fork a subset of the package functionality for your own use then you can implement that behavior in your fork if it's useful to you.

Thanks and good luck!
