### ISSUE TITLE
Referencing module twice via file:// results in inconsistent behaviour

### ISSUE THREAD

**Issue by jeromewaibel** [hashicorp/terraform#27146]
### Terraform Version

```
Terraform v0.13.5 and Terraform v0.14.0
...
```

### Terraform Configuration Files

https://github.com/jeromewaibel/terraform-issue

```
./servermodule
./servermodule/main.tf
./servermodule/variables.tf
./project
./project/main.tf

main.tf of project:

module "server1" {
  source = "file:///home/schrom/example/servermodule"
  id = "first"
}
module "server2" {
  source = "file:///home/schrom/example/servermodule"
  id = "second"
}
```

### Expected Behavior

When developing modules I usually temporarily change the source to a local file:// reference so I can test changes to the module locally without the need to push them to a git repository. This works fine as terraform creates a symlink in the .terraform/modules directory so any changes to the module source take effect immediately.

When used multiple times would expect all module references to use a symlink.

### Actual Behavior

When the module is used twice and both source references are changed to the same file://, only the first reference will be a symlink. The second reference will be a full copy. So when making changes to the module source only the first instance of the module will use the new sources, while the second one will be an outdated copy.

This is what my module directory looks like after terraform init:
```
~/example/project$ ls -al .terraform/modules/
total 16
drwxr-xr-x 3 schrom schrom 4096 Dec  4 18:34 .
drwxr-xr-x 4 schrom schrom 4096 Dec  4 18:34 ..
-rw-r--r-- 1 schrom schrom  256 Dec  4 18:34 modules.json
lrwxrwxrwx 1 schrom schrom   33 Dec  4 18:34 server1 -> /home/schrom/example/servermodule
drwxr-xr-x 2 schrom schrom 4096 Dec  4 18:34 server2
```

### Steps to Reproduce

1. Clone my repository
2. Go to project/main.tf
3. Change the source paths to your path
4. run _terraform init_
5. Look into .terraform/modules/
6. Make a change to servermodule/main.tf
7. Spend a lot of time debugging and wondering why only _module "server1"_ applies the change :-(

**Comment by apparentlymart** [comment]
Hi @jeromewaibel!

I think what you're describing here may be a v0.13/v0.14 variant of what's being discussed in #23031. Would you agree? If so, I'd like to consolidate these two together so all the information about it is in one place.

Thanks!

**Comment by jeromewaibel** [comment]
Yes, I agree, that seems to be the same problem.

**Comment by apparentlymart** [comment]
Thanks for confirming, @jeromewaibel! In that case, I'm going to close this one and we'll continue to use #23031 to track this odd behavior.

To be transparent, this behavior has been present for some time and hasn't risen to the top of the priority list because the result ultimately "works" even though I'd agree it's unexpected and non-ideal. My guess would be that we'll probably not attack this behavior as an isolated issue but rather roll it up into some expected future work to generally improve Terraform's handling of remote modules, such as including references to them in [the dependency lock file](https://www.terraform.io/docs/configuration/dependency-lock.html) along with the current records of provider selections, because these and some other concerns all involve doing some technical design work around how Terraform identifies modules and how we might define two module `source` addresses as referring to "the same module" in the presence of complexities like case sensitive vs. insensitive systems, symlinks in the filesystem, HTTP redirects, and various other concerns that make it so that a trivial string comparison would likely be insufficient.

For that reason, it'll likely be some time before we'll be able to spend time on this, but I do appreciate you raising it nonetheless and I do hope we'll be able to improve the behavior eventually.
