### ISSUE TITLE
Terraform Forgetting Resources

### ISSUE THREAD

**Issue by sam-cogan** [hashicorp/terraform#27140]
### Terraform Version

```
0.12.28
```

### Terraform Configuration Files

```terraform

resource "azurerm_subnet_network_security_group_association" "nsg_association" {
  for_each                  = azurerm_subnet.subnet
  subnet_id                 = each.value.id
  network_security_group_id = lookup(var.subnet_definitions, each.value.name).security_group_id
}
resource "azurerm_subnet_route_table_association" "route_association" {
  for_each       = { for subnet in local.route_subnet_list : subnet.name => subnet.name }
  subnet_id      = "/subscriptions/${data.azurerm_subscription.current.display_name}/resourceGroups/${var.resource_group_name}/providers/Microsoft.Network/virtualNetworks/${var.virtual_network_name}/subnets/${each.value}"
  route_table_id = azurerm_route_table.routetable.id
  depends_on = [azurerm_subnet.subnet]
}

```

### Expected Behavior

This code should create a route table and NSG association 
### Actual Behavior

The first time this is run it works as expected, however running the deployment again later generates errors indicating that the Route Table and/or NSG association are not in the state file and need to be imported. 

This seems to happen only on certain deployments of this infrastructure, some never see this issue, some see it occasionally and some all the time. 

Deleting the associations and re-running fixes the issue, until you run it next time.

The plan shows them being created as new resources.
### Steps to Reproduce

Difficult to re-produce to it's somewhat random occurance

**Comment by jbardin** [comment]
Hi @sam-cogan 

Thanks for filing the issue. Without any way to reproduce this, we're not likely to be able to investigate the problem. The logs from the point that this happens would probably be useful too.

The only 2 possibilities I can see are: 
 - Your state storage is not consistent, and you are getting an older version of the state which may not have the same resources.
 - The provider is reporting some of the resources as missing during refresh. This could be because of a bug in the provider, a temporary failure in the remote service, or maybe even incorrect permissions that cannot access some resources (some APIs only return the equivalent of 404 rather than 403 in this case).

Hopefully that help you with the troubleshooting here. You may also find the [the community forum](https://discuss.hashicorp.com/c/terraform-core) helpful, where there are more people ready to help.

Thanks
