### ISSUE TITLE
Terraform 0.13, 0.14 performance terrible using binary, good when self built

### ISSUE THREAD

**Issue by 19h** [hashicorp/terraform#27143]
### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.20.0
+ provider registry.terraform.io/hashicorp/github v4.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Verified on macOS Big Sur 11.0, 11.1 Beta.

Using the GitHub binary distributions of 0.13, 0.14 on macOS Big Sur causes a *serious* slow down of deployment times.

I've been extremely unhappy about this for a while, but chose to compile terraform myself today and it improved the deployment times tenfold.

Since I'm mostly a Rust & C engineer I'm not sure what changes given the custom (non-LLVM / GCC) Go toolchain, but what exactly would change in the network request performance?

**Comment by jbardin** [comment]
Hi @19h,

This is likely stemming from the same issue as #26532. The only difference you could be making when building locally would be to have CGO enabled, which would allow the native host resolver to be used. You could verify by building with `CGO_ENABLED=0`, which should give you an identical binary to the release.

**Comment by danieldreier** [comment]
@19h I think the next troubleshooting steps here are either for you to do your own `CGO_ENABLED=0` build and then check whether that build is equally slow to the binary, or for you to share a reproduction case (e.g. some terraform config) that I can run and benchmark here where you're seeing a big performance change. I'm happy to dig in, just want to make sure I'm running the same things you are in order to reproduce the same performance issue.

**Comment by jbardin** [comment]
Closing since we have not heard back. If this does turn out to be a different issue from #26532, feel free to add more information here and we can re-evaluate the issue.

Thanks!
