### ISSUE TITLE
TF14 -chdir breaks when used together with custom / local provider

### ISSUE THREAD

**Issue by jaceq** [hashicorp/terraform#27166]
### Terraform Version

```
terraform -v
Terraform v0.14.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    pass = {
      source  = "camptocamp/pass"
      version = "2.0.0-custom"
    }
  }
}

```
### Crash Output

```
terraform -chdir=my-state init

Initializing the backend...

Initializing provider plugins...
- Finding camptocamp/pass versions matching "2.0.0-custom"...
- Installing camptocamp/pass v2.0.0-custom...

Error: Failed to install provider

Error while installing camptocamp/pass v2.0.0-custom: after installing
registry.terraform.io/camptocamp/pass it is still not detected in the target
directory; this is a bug in Terraform
```

### Expected Behavior
Provider in terraform.d in main folder (or in subfolder) should work.

### Actual Behavior
In order to understand this issue better I will first describe my folder structure:
```
/playground   <--- this is where I run `terraform -chdir=my-state init` from
 |
 |-- terraform.d/plugins/registry.terraform.io/camptocamp/pass/2.0.0-custom/linux_amd64/terraform-provider-pass
 |
 |-- my-state
     |
     |-- main.tf  <-- I only have provider defined
```

What happens is, terraform enters directory and performs init, so basically it creates a `.terraform` within `my-state` as expected, but then it creates a invalid symlink to my terraform.d like this:
```
/playground/my-state/terraform.d/plugins/registry.terraform.io/camptocamp/pass/2.0.0-custom/linux_amd64
``` 
Above is clearly wrong as my terraform.d is not within `/playground/my-state` but within `/playground`

What I also tried is to put `terraform.d` into `/playground/my-state` but there it's simply not detected.

### Steps to Reproduce

In order to reproduce, try to use custom / local provider provided as described  / with same folder structure in above point and run 
```
terraform -chdir=my-state init
```
*Make sure to `rm -r my-state/.terraform` not to reuse previously configured version

### Workaround

The workaround is to symlink `terraform.d` to `my-state` folder, then it exists in root and sub directory.

**Comment by apparentlymart** [comment]
Hi @jaceq! Thanks for reporting this.

This is certainly an interesting situation, because it's arising from an intentional design decision but it's playing out in a way we honestly didn't really consider in the initial work on `-chdir`.

The trick here is that `-chdir` is explicitly documented as not affecting the processing of the CLI Configuration because that's global rather than command-specific. [The provider installation methods are part of the CLI configuration](https://www.terraform.io/docs/commands/cli-config.html#provider-installation), so Terraform resolves those prior to launching the subcommand (in your case `init`) with the working directory changed.

We typically consider the installation methods to be part of the CLI configuration, rather than part of your actual Terraform configuration, because users tend to want to install local providers just once and use them across many configurations. With that said, I can see why the handling of `terraform.d` surprised you here because in a sense it "feels" like it accompanies your `.tf` files, even though Terraform doesn't see it that way. The implied installation methods are implemented [as if Terraform were automatically writing `filesystem_mirror` blocks for you](https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories), and so that all happens prior to executing the `init` command.

Given that `-chdir` is entirely new in v0.14 and so there is no pre-existing behavior to use as justification for a particular decision, and given that the "best" behavior here isn't obvious (there are reasonable rationales on both sides), and finally given that we continue to support `terraform.d` only as a workaround to submit providers for [Terraform Cloud remote operations](https://www.terraform.io/docs/cloud/run/cli.html) until Terraform Cloud has a first-class private provider registry feature, my instinct here is to keep the behavior as currently implemented. We're expecting to remove `terraform.d` support once there's a compelling alternative in Terraform Cloud anyway, because it was only introduced as a workaround for a missing Terraform Cloud capability.

You mentioned that creating a symlink served as a workaround for you, so I'd encourage you to continue using that "workaround" as the official answer for now. If Terraform's default behavior doesn't work for you then you can also potentially [customize the installation methods entirely](https://www.terraform.io/docs/commands/cli-config.html#provider-installation), asking Terraform to look in whichever local directories you like, or some other possibilities.

If anyone reading this is currently using `terraform.d` for a use-case _other than_ [sending providers to Terraform Cloud's remote execution environment](https://www.terraform.io/docs/cloud/run/install-software.html#installing-terraform-providers), it'd be great if you could open [a new feature request issue](https://github.com/hashicorp/terraform/issues/new?labels=enhancement%2C+new&template=feature_request.md) about that use-case so we can consider it. The `terraform.d` directory has been documented only for Terraform Cloud use, so if you've found it useful for meeting _other_ use-cases then we'd like to discuss that so we can potentially find a design that fits in better with the new provider installation model in Terraform 0.13 and later.
