### ISSUE TITLE
Missing full tag in dockerhub image 

### ISSUE THREAD

**Issue by lisamittmann** [hashicorp/terraform#27190]
Hi there, 

we are missing the full tag in the dockerhub image: 
https://hub.docker.com/r/hashicorp/terraform

According to documentation the full tag is still available but missing in tag list (light tag is still available, though). Could you please look into that?

Thx and cheers
Lisa

**Comment by apparentlymart** [comment]
Hi @lisamittmann,

The `full` image is no longer available, after being deprecated during the v0.13 release period.

Unfortunately DockerHub does not let us update that README because we build releases outside of DockerHub's build process.  Until we can find a way to update it, the README on DockerHub will be incorrect.

The images remaining on Dockerhub are the only ones we can officially support because they contain exact copies of the release executables from our downloads page, whereas the "full" images contained a bespoke build of Terraform from source code that wouldn't necessarily exactly match the released version. We don't have any plans to re-introduce the full image, because we are diverting our limited release management resources onto distributions of the official binaries, including the images that remain on DockerHub.

If you have a use-case that only the "full" image could previously meet, I'd suggest either building your own image using the `Dockerfile` in the root of the Terraform repository, or using a suitable base image that meets your needs and cloning the Terraform source tree into it.

Thanks!
