### ISSUE TITLE
depends_on in data azurerm_resource_group doesn't take any effect (Error: Resource Group was not found)

### ISSUE THREAD

**Issue by kenorb** [hashicorp/terraform#27191]
### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.39.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform
data "azurerm_resource_group" "mc_resource_group" {
  name = azurerm_kubernetes_cluster.main.node_resource_group

  depends_on = [azurerm_kubernetes_cluster.main]
}

resource "azurerm_resource_group" "aks" {
  name     = "rg-${var.cluster_name}"
  location = var.location
}

resource "azurerm_kubernetes_cluster" "main" {
  name                    = var.cluster_name
  location                = azurerm_resource_group.aks.location
  node_resource_group     = "my-node"
  private_cluster_enabled = true
  resource_group_name     = azurerm_resource_group.aks.name
...
}
```

### Crash Output

```
% terraform plan 

Error: Error: Resource Group "rg-node-foo-aks" was not found

  on ../../terraform/modules/aks/resource_group.tf line 16, in data "azurerm_resource_group" "mc_resource_group":
  16: data "azurerm_resource_group" "mc_resource_group" {
```

### Expected Behavior

I'm clearly using `depends_on` which points to `azurerm_kubernetes_cluster.main` which I expect to be created first, so I can read the exported attribute `azurerm_kubernetes_cluster.main.node_resource_group` in `data`, but it doesn't happen.

Secondly this fails on `plan` (and `refresh`), which should show me the plan, and not failing on the missing resources which are not created yet. I know it's not there (the resource group), because I haven't run `apply` yet.

### Actual Behavior

`data` fails to wait for resource specified in `depends_on`.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### References

It's somehow related to #25796, but I'm explicitly using `depends_on`.

**Comment by jbardin** [comment]
Hi @kenorb,

Is this from a clean install, or were there a series of changes applied to this configuration before the error occurred? 
The trace logs may provide more information about what is going on.

There's two likely scenarios here, one is that the data source is already created in the state, and refreshing that after the actual resource group was deleted is failing. You may be able to work around this with a `-refresh=false` or a targeted apply. the second possibility is an eventual consistency error in the provider, which we can't account for within terraform.

The correct way to avoid this issue is to never have a data source attempting to read a resource which is created within the same configuration. You should generally be reading the `azurerm_resource_group.aks` attributes directly, rather than trying to coordinate the data source with the resource creation. Is there a reason you cannot use the resource itself rather than the data source?

**Comment by kenorb** [comment]
Thank you for your suggestions. I've managed to refactor the module and I've removed `data.azurerm_resource_group.mc_resource_group` in favor of using the attributes directly.
I'm going to close the ticket as I won't be able to go back now and reproduce it.
