### ISSUE TITLE
since chef 12.2.0 validator is deprecated

### ISSUE THREAD

**Issue by ramonskie** [hashicorp/terraform#2720]
since chef 12.2.0 no validator is not necessary anymore and deprecated
see this blog post https://www.chef.io/blog/2015/04/16/validatorless-bootstraps/

but it is still enforced 
https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/chef/resource_provisioner.go#L180

**Comment by phinze** [comment]
thanks for the report, @ramonskie,

what do you think @svanharmelen?

**Comment by partamonov** [comment]
Is this blog post applying to knife bootstrap? And as far as I know chef provisioner is not using knife bootstrap, it's just place all the things on the host and run chef client.
To my mind validation key is still required to register node with chef-client command, but I need to check bootstrap code.

And have to be checked in live. I'll try to do it

**Comment by svanharmelen** [comment]
@partamonov is right... What is changed is that now the `knife bootstrap` command is doing the client registration for your new node using your personal credentials configured on the box where you executed the `knife bootstrap` command. By doing this the `knife bootstrap` command is able to retrieve a valid `client.pem` file which it then uploads to the new node instead of the `validation.pem`.

So this "new" feature has no effect on how the `chef` provisioner works and so the `validation.pem` is still required.

Of course we can always have a look at changing the way the provisioner works, but in all cases you need to supply a valid user and pem file. It being either your personal ones, or the validator account ones. Additionally you add more API connections to the mix as now the host that executed the `terraform apply` command also needs access to your Chef API endpoint in order to do the registration for you. So I don't see any immediate benefit for making those changes and think we are good as is as I cannot find any details of this way of working is being deprecated. Could you share your reference for that one? Of course if that is really the case we would have to make some changes to the provisioner in time before the current workflow is killed by Chef.

**Comment by ramonskie** [comment]
the only nice feature i saw when using the client credentials instead of validator
is that you can overwrite the client when redeploying.
for now we need to manual delete the client when redeploying

**Comment by svanharmelen** [comment]
That is indeed a nice option... In Terraform that should be accomplished by adding a `destroy` event to provisioners as well. There is already a lot of talk about this (https://github.com/hashicorp/terraform/issues/649 and https://github.com/hashicorp/terraform/issues/2010), but maybe it's time to actually hack this support in... I'll see if I can free up some cycles.

**Comment by ramonskie** [comment]
i don't see any activity for this anymore

**Comment by svanharmelen** [comment]
I'm closing this issue in favour of #3605. It's a slightly different issue, but at the end of the discussion we had here we came to the conclusion that the one thing we would gain from updating the logic, was having the ability to cleanup an existing node when (re)creating a new one. And that is exactly what issue #3605 is also about...

If anyone feels this one shouldn't be closed, feel free to reopen the issue! Thanks!

**Comment by bixu** [comment]
I'm not sure that this should be closed yet. The other big advantage of being able to use a client .pem key is that we don't have to use a shared validation key between users. At least for me, at $job, telling Terraform something like `${file("~/.chef/<chef_user>.pem")}` would be extremely helpful.

**Comment by svanharmelen** [comment]
Please checkout PR #8577, which adds exactly what you are asking for :wink:

There's one thing that needs to fixed in that PR before it can get merged and I'm away for a few days, but should be fixed coming week...
