### ISSUE TITLE
Terraform crashed: "rpc error: code = Unavailable desc = transport is closing"

### ISSUE THREAD

**Issue by reinelind** [hashicorp/terraform#27221]
### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.20.0
```

### Terraform Configuration Files

```
https://github.com/reinelind/terraform-lamp_stack
```

### Debug Output

https://gist.github.com/reinelind/af2d409366b0c6047f4773bc4e7b08e3
### Crash Output

https://gist.github.com/reinelind/1e11a4f59dc3811657ad70e19be0df24
### Expected Behavior

Infrastructure should have been created as follows: 
VPC, two subnets, Security Group, EIP,  ELB, IGW, NAT Gateway, Two Route tables, Two route tables' associations (as described in `modules/network/main.tf`)
### Actual Behavior

Infrastructure was created partially,
Terraform crashed (in most cases error pops out when Terraform creates an ELB resource).

### Steps to Reproduce

From the root of the repository perform next steps: 
1. terraform init
2. terraform apply

**Comment by danieldreier** [comment]
Thanks for reporting this! This is an issue to be addressed in the AWS Terraform provider, rather than in core; you can see in the log output that it's the AWS provider binary that crashed:

```
2020-12-09T16:20:54.729+0200 [DEBUG] plugin.terraform-provider-aws_v3.20.0_x5.exe: panic: runtime error: invalid memory address or nil pointer dereference
```

James has labeled this as a `provider/aws`issue, so it should be migrated over to their GitHub repository automatically shortly.
