### ISSUE TITLE
Creating inspector assessment template before it gets destroyed completely

### ISSUE THREAD

**Issue by Preethamraj553** [hashicorp/terraform#27231]
![image](https://user-images.githubusercontent.com/27139091/101767090-c3c2cc80-3b09-11eb-888e-411bb545e3c0.png)

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
