### ISSUE TITLE
CloudTrail support

### ISSUE THREAD

**Issue by TheM0ng00se** [hashicorp/terraform#2725]
I believe there was an SDK for this at one point...any way to get it back as a resource?

Thanks

**Comment by catsby** [comment]
Hey @TheM0ng00se – I don't believe we've ever removed a resource before. We're pretty diligent about keeping the [CHANGELOG][1] up to date on any adding, fixing, or removing, and there's no mention of it. If you can find otherwise I'll investigate more but I'm fairly certain we have not yet had support for CloudTrail. 

The [CloudTrail API][2] appears (at a high level) to have a small surface area, so if you're eager to take a dive into Terraform providers I would be happy to review any PR contributing the resource :smile: 


[1]: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md
[2]: http://docs.aws.amazon.com/awscloudtrail/latest/APIReference/Welcome.html

**Comment by TheM0ng00se** [comment]
@catsby Catsby, sounds great, won't have a ton of time in the next few months, but I'll check back then and if there isn't I'd be happy to add it as a resource.
