### ISSUE TITLE
error with x.509  certificate

### ISSUE THREAD

**Issue by charlesanil** [hashicorp/terraform#27278]
Hi ,

I have terraform setup and was working last couple of months. 

Got this error today when was trying  to update my infra using terraform apply.
The same error is thrown for all resource endpoints in my infra. 

Error: Error reading IAM policy arn:aws:iam::xxxxxxxxxx:policy/eprouestError: send request failed
caused by: Post "https://iam.amazonaws.com/": x509: certificate signed

I had downgraded my aws cli from 2.0 to 1.0 . Since there was another SSL bug which got resolved after downgrade.

Can you please let me know if changing aws cli version has any changes way terraform uses certs ?

Also, I have updated the terraform today from visual studio code updates.

Thanks,
Charles

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
