### ISSUE TITLE
Unable to publish to registry

### ISSUE THREAD

**Issue by Richard-Payne** [hashicorp/terraform#27273]
Not sure if this is in the right place, but I couldn't find a repo for the registry.
I’ve written a very small little provider and I’m trying to publish it.

I used goreleaser to package it, as per the instructions:
https://github.com/Richard-Payne/terraform-provider-text/releases/tag/v1.0.1

However, the Terraform publish page is returning:
Error while attempting to publish provider: no valid platform assets found

**Comment by apparentlymart** [comment]
Hi @Richard-Payne,

There isn't a public repository for the Terraform Registry because it isn't itself an open source project. While in theory we can label issues here as "registry", the registry team doesn't routinely monitor this repository because this isn't where they do most of their work.

Given that, I'd suggest opening a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where hopefully we can troubleshoot what's going on. 

With that said, one difference I notice between your provider release an [one of mine which has worked](https://github.com/apparentlymart/terraform-provider-testing/releases/tag/v0.0.2) is that your checksums file seems to be named with the suffix `_checksums.txt`, but mine has the suffix `_SHA256SUMS` instead. I also have a cryptographic signature of that file in `_SHA256SUMS.sig` which I believe the registry requires in order for the release to be considered valid.

Hopefully those hints will help you make some progress, and I'm happy to try to help some more in the community forum if not, and possibly also ping someone on the Registry team if we can't figure it out, but since addressing this doesn't seem like it would involve making a code change in this repository I'm going to close this just because otherwise I suspect it'll end up staying open indefinitely. :confounded:

**Comment by Richard-Payne** [comment]
Thanks.  I already tried using the "community".  No response: https://discuss.hashicorp.com/t/unable-to-publish/18757

Rather than continue manually, I figured I'd try the Github actions route.  I followed the instructions here:
https://www.terraform.io/docs/registry/providers/publishing.html?_ga=2.85803161.12283089.1607617591-474999624.1576585976#preparing-and-adding-a-signing-key

When running the release workflow via a pushed version tag, it fails here:
![image](https://user-images.githubusercontent.com/6730730/102262778-695fac80-3f0b-11eb-9adf-431b70513a3a.png)

Any idea what this means?

I have the private key block in secret GPG_PRIVATE_KEY and the passphrase in secret PASSPHRASE.  The release.yml is:

```
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.0.2
        #uses: paultyng/ghaction-import-gpg@v2.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
```

**Comment by Richard-Payne** [comment]
ok, got it working manually.  Any help you have offer on the github actions method would be appreciated but if you don't know then I guess I'll have to go ask on the ImportGPG action repo.
