### ISSUE TITLE
output specific attribute in for_each resource

### ISSUE THREAD

**Issue by cvkrreddy** [hashicorp/terraform#27284]
I want to ```output``` only storage account names ```stgeastpprdvaprdprivate``` and ```stgeastpprdvaprdpublic```

### Terraform Version
```
Terraform v0.13.4
```

###### Module main file
```
resource "azurerm_storage_account" "stg_acct" {
  for_each                 = var.STG_ACCT
  resource_group_name      = "rgname"
  location                 = "EastUS"
  name                     = lower("stg${var.REGION_LOWERALL}${each.value["APP"]}${each.value["ENV"]}${each.key}")
  account_tier             = each.value["TIER"]
  account_replication_type = each.value["REPTYPE"]
  account_kind             = each.value["KIND"]
}
```
###### variable STG_ACCT is a map
```
STG_ACCT = {
  "public" = {
    "APP"             = "pprdva"
    "ENV"             = "prd"
    "TIER"            = "Standard"
    "REPTYPE"         = "LRS"
    "KIND"            = "StorageV2"
    },
  "private" = {
    "APP"             = "pprdva"
    "ENV"             = "prd"
    "TIER"            = "Standard"
    "REPTYPE"         = "LRS"
    "KIND"            = "StorageV2"
    }

}
```
```
fyi: so storage account names will be stgeastpprdvaprdpublic and stgeastpprdvaprdprivate.
```

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
