### ISSUE TITLE
google_compute_instance_template: Error: doesn't support update

### ISSUE THREAD

**Issue by dawidpogorzelski** [hashicorp/terraform#27287]
### Terraform Version

```
0.14.2
```

### Terraform Configuration Files

```terraform
resource "google_compute_instance_template" "test" {
  name_prefix = "${var.env}-${replace(var.role, "_", "-")}-"

  tags = [
    var.env,
  ]

  labels = {
    env      = var.env
  }

  machine_type = var.size

  scheduling {
    automatic_restart = true
  }

  disk {
    source_image = var.build != "" ? "aproject/test-${replace(var.role, "_", "-")}-${var.build}" : "aproject/test-${replace(var.role, "_", "-")}"
    auto_delete  = true
    boot         = true
    disk_type    = "pd-standard"
  }

  network_interface {
    network = var.vpc_name
    access_config {
      nat_ip = ""
    }
  }



  metadata = {
    role                         = var.role
    env                          = var.env
  }

  service_account {
    email = var.compute_service_account.email
    scopes = [
      "cloud-platform",
    ]
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output

```
 # module.mymodule.google_compute_instance_template.test will be updated in-place
  ~ resource "google_compute_instance_template" "test" {
        id                   = "projects/arpoject/global/instanceTemplates/myenv-myservice-20201208204739443400000010"
        name                 = "myenv-myservice-20201208204739443400000010"
        tags                 = [
            "myenv",
        ]
        # (12 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

...........

Error: doesn't support update
```

### Expected Behavior

When running consecutive apply/plan steps there should be no diff

### Actual Behavior

1: an attempt to "update" the template is performed even though there are no changes to the template.
2: this resource cannot be updated because the provider does not support "update" on this resource

### Steps to Reproduce

Run 2 consecutive `terraform apply `

### References

Original issue submitted to the provider issue tracker:
https://github.com/hashicorp/terraform-provider-google/issues/7971

**Comment by jbardin** [comment]
Hi @dawidpogorzelski,

Sorry to bounce this issue around, but unfortunately there isn't much we can do from the core side here. What is likely happening is there are some trivial changes that were are not showing in `(4 unchanged blocks hidden)`, which are excluded to try and work around shortcomings in the legacy provider SDK. While in theory the provider should not return any planned changes for a resource that does not support Update, the provider itself is still somewhat beholden to the SDK to make the plan correctly. 

Since this resource cannot be updated, perhaps we can short-circuit the plan ahead of time by specifying:

```
lifecycle {
  ignore_changes = all
}
```

While the actual issue here is in the [Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk/issues), the legacy SDK is frozen for compatibility while a new SDK is developed, and I doubt this is an issue that could be resolved.

**Comment by dawidpogorzelski** [comment]
Hey James, thanks a lot for the response, seems like ignoring all makes no difference. This issue popped up right after 0.14 update. Is it correct for me to guess that this is related to the v2 of the plugin sdk and how this affects the interaction with the provider? Do you have any alternative suggestions as to potential solutions on either end or workaround?
Thanks for any input you might have :)

**Comment by jbardin** [comment]
This shouldn't be from the SDK v2 update, since the internal data handling _should_ not have changed, but that should be easy to test if you can compare this configuration with specific versions of the google provider before and after the update. If we can pinpoint the regression to an update to the SDK, that would make it easier to file an issue over there.

I'll see if we can replicate this internally and try to extract some more information about what is going on here, but I can't think of any other workarounds that could be done from the core side.

**Comment by dawidpogorzelski** [comment]
a quick summary of my tests, by terraform and provider version:
```
0.13.5: 3.45 issue 
0.13.5: 3.46 issue
0.14.2: 3.47 issue
0.14.2: 3.48 issue
0.14.2: 3.49 issue
0.14.2: 3.50 issue
0.14.2: 3.51 issue

0.13.5: 3.45 no issue
0.13.5: 3.46 no issue
0.13.5: 3.47 no issue
0.13.5: 3.48 no issue
0.13.5: 3.49 no issue
0.13.5: 3.50 no issue
0.13.5: 3.51 no issue
```

so it doesn't seem like this kicks in at any particular provider version but rather at a specific tf version (>=0.14)

**Comment by dawidpogorzelski** [comment]
I can also add that during my tests i noticed that regardless of provider version only tf > 0.14 will attempt to update resources that don't support update like `google_storage_bucket_object`

**Comment by jbardin** [comment]
Thank you @dawidpogorzelski! That helps a lot. There were a few fixes to plan generation with set types in 0.14, which may be picking up minor changes returned by the provider that were previously missed. 

I'm not that familiar with the google cloud offerings, would it be possible for you to supply a standalone reproduction for debugging purposes? 

Thanks!

**Comment by dawidpogorzelski** [comment]
I'm trying to nail the minimum setup to reliably repro this but as i'm doing this I realize that 2 consecutive applies can produce a different plan without any changes to the code. Meaning sometimes an apply produces clean exit without changes and the next one produces the diff i mentioned in the issue description. just like that. Feels like a race condition somewhere

**Comment by jbardin** [comment]
Even if the problematic resource config is a bit large, having a self-contained config to demonstrate the issue would be great! It's entirely possible that the problem arrises from an oversight in the iteration of maps or sets, which are inherently unordered, and therefore could produce inconsistent results.

**Comment by dawidpogorzelski** [comment]
Finally, i found the issue and here is the repro:
https://github.com/dawidpogorzelski/27287repro

set projectid in https://github.com/dawidpogorzelski/27287repro/blob/main/main.tf#L2
then
```
terraform init
terraform apply
```
repeat `terraform apply` step a few times and the issue should trigger.
i noticed that:
* setting `sensitive` to false https://github.com/dawidpogorzelski/27287repro/blob/main/module2/main.tf#L6 OR
* not relying on the `output` at all OR 
* not referencing the output values in multiple places in module1:

```terraform
  labels = {
    a = var.foobar
  }

  metadata = {
    a = var.foobar
  }
```
vs
```terraform
  labels = {
    a = var.foobar
  }
```

prevents the issue from happening
