### ISSUE TITLE
Feature Request: Store variables in tfstate

### ISSUE THREAD

**Issue by cgetzen** [hashicorp/terraform#27288]
### Current Terraform Version

```
0.14.2
```

### Use-cases
Oftentimes, I need to plan with dummy variables, see the plan output, and modify accordingly to find the original variables that were applied.
If we store input variables in the state, it will be easier to find them.

### Attempted Solutions
- Using tfvars. Terraform workspaces allows one to keep details about each environment out of the repo, but requiring tfvars for each workspace limits the powerful effects of this. 

### Proposal
On each version of the statefile, write the variables that were input to a new root element.
Helm has a similar feature [here](https://helm.sh/docs/helm/helm_get_values/).

**Comment by jbardin** [comment]
Hi @cgetzen,

Thanks for filing the request. If you want to be able to look up the variable values as they were used during `apply`, it sounds like what you want would be achieved by storing the variables in output values. Since it's not the normal use case to store ephemeral values, having the option to configure various outputs would be the preferable compromise. 

Would something like the following work in your case?

```
variable "input" {
}

output "var_input" {
  value = var.input
}
```

This could then be easily inspected with the `show` command.

**Comment by cgetzen** [comment]
That's a fantastic work-around, thank you!
