### ISSUE TITLE
Terraform Cloud: Update Workspace Variable API Updates Variable in a Different Workspace

### ISSUE THREAD

**Issue by mnazir23** [hashicorp/terraform#27298]
### Terraform Version
```
0.14.2
```

### Problem Statement
Hi,

I have two workspaces: workspace A and B. I have a variable called **test_var** in both of these workspaces. I used the Patch/Update Workspace Variable API call to update the **test_var** for workspace A but by mistake I used the variable ID of the **test_var** variable in workspace B. 

However, the workspace ID was for workspace A but still the **test_var** in workspace B got updated.

### Expected Behavior
The **test_var** variable in workspace B should not have been updated and an error should have been thrown.

### Actual Behavior
The **test_var** for workspace B got updated even though the workspace ID was for workspace A

### Steps to Reproduce

1. Create two different workspaces (A & B)
2. Create a variable with the same name in both of the workspaces
3. Use the Update Workspace Variable API and in the request body, use the variable ID for the variable in workspace B and workspace ID of workspace A.
4. The variable in workspace B will get updated.

### Additional Context
The Update Workspace Variable API can be found [here](https://www.terraform.io/docs/cloud/api/workspace-variables.html#update-variables)

**Comment by apparentlymart** [comment]
Hi @mnazir23! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!

**Comment by chrisarcand** [comment]
Hi @mnazir23, I'm from the Terraform Cloud team and did see this issue; ℹ️ this has been fixed on the platform, thanks for reporting it!
