### ISSUE TITLE
aws_dynamodb_table_item Validation exception

### ISSUE THREAD

**Issue by DalePage** [hashicorp/terraform#27290]
Hi,
Trying to create a small number of DynamoDB items as seeds but am getting the following error:

Error retrieving DynamoDB table item: ValidationException: The provided key element does not match the schema
        status code: 400, request id:

Despite the error message one item is created, unfortunately the rest are not but the error occurs even when trying to apply just one item even though that item is created.

I read #24173 and tried adding a range key declaration but that didn't help.

Resource declarations are:

resource "aws_dynamodb_table_item" "domain_motivational" {
  table_name = aws_dynamodb_table.myTableName.name
  hash_key   = aws_dynamodb_table.myTableName.hash_key
  range_key = aws_dynamodb_table.myTableName.range_key
  item       = <<ITEM
{
 "DomainId": {
  "S": "Motivational"
 },
 "order": {
  "N": "5"
 },
.....
}
ITEM
}

resource "aws_dynamodb_table" "myTableName" {
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "DomainId"
  name           = "myTableName"
  range_key      = "order"
  read_capacity  = 0
  stream_enabled = false
  tags           = {}
  write_capacity = 0

  attribute {
    name = "DomainId"
    type = "S"
  }
  attribute {
    name = "order"
    type = "N"
  }

  point_in_time_recovery {
    enabled = false
  }

  timeouts {}

}

Hope you can help.
Many Thanks

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
