### ISSUE TITLE
Error in function call - Call to function "file" failed: no file exists

### ISSUE THREAD

**Issue by desgith** [hashicorp/terraform#27294]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```terraform
data "template_file" "read_text_sql"{
    depends_on = [azurerm_template_deployment.managed_sql,null_resource.getsqlinfo]
    template = "${file("${path.module}/${var.name}check.txt")}"    
}
```

### Expected Behavior

Terraform should have run the script without expecting the file to be present, since it has `depends_on`

### Actual Behavior

Thrown the following error
```
Error: Error in function call

  on get_sqldata.tf line 32, in data "template_file" "read_text_sql":
  32:     template = "${file("${path.module}/${var.name}check.txt")}"
    |----------------
    | path.module is "."
    | var.name is "values15"

Call to function "file" failed: no file exists at values15check.txt.
```

The above file will get generated after the task `azurerm_template_deployment.managed_sql`, but it is expecting the file to be present , i am not sure what am i missing here.

**Comment by jbardin** [comment]
Hi @desgith 

Using `depends_on` within data sources was only fully supported starting in 0.13, and 0.14 further improved the data source handling by removing the separate refresh phase. 

If `azurerm_template_deployment.managed_sql` is the resource creating the file, referencing that resource in `depend_on` using 0.14 should work. The problem users often encounter is that if the file is subsequently removed outside of terraform's control, the `file` function call will fail when the data source is read again. 

If you can reproduce this in 0.14 we can take a closer look at the issue.

Thanks!

**Comment by apparentlymart** [comment]
I answered [this question over on Stack Overflow](https://stackoverflow.com/questions/65316834/call-to-function-file-failed-no-file-exists-terraform) before noticing there was a similar issue open here for it.

I'll repeat my answer here for posterity:

> The reason for the behavior you are seeing is included in [the documentation for the `file` function](https://www.terraform.io/docs/configuration/functions/file.html):
>
> > This function can be used only with files that already exist on disk at the beginning of a Terraform run. Functions do not participate in the dependency graph, so this function cannot be used with files that are generated dynamically during a Terraform operation. We do not recommend using dynamic local files in Terraform configurations, but in rare situations where this is necessary you can use [the `local_file` data source](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) to read files while respecting resource dependencies.
>
> The `file` function is intended for reading files that are included on disk as part of the configuration, typically in the same directory as the `.tf` file that refers to them, and using the `path.module` symbol to specify the path like this:
>
> ```
> file("${path.module}/example.tmpl")
> ```
>
> Your question doesn't explain why you are reading files from a user's home directory rather than from the current module configuration directory, or why one of the files doesn't exist before you run Terraform, so it's hard to give a specific suggestion on how to proceed. The documentation offers [the `local_file` data source](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) as a possible alternative, but it may not be the best approach depending on your goals. In particular, reading files on local disk from outside of the current module is often indicative of using Terraform for something outside of its intended scope, and so it may be most appropriate to use a different tool altogether.

You included some additional information here which implies that you were intending to have a provisioner associated with `null_resource.getsqlinfo` create that file. I expect there will be a better answer to that than to use the `local_file` data source, but in order to show that I'll need to see a fuller example of your configuration. If you create a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and include the full source code of all of the relevant resources here (_at least_ `azurerm_template_deployment.managed_sql` and `null_resource.getsqlinfo`, but also anything that they are also depending on) then I'd be happy to help you find a working solution.

Because the behavior you described here is Terraform behaving as designed, I'm going to close this. I look forward to continuing the discussion in the community forum. Thanks!
