### ISSUE TITLE
Change in the way `count = 0` is handled for modules

### ISSUE THREAD

**Issue by elliot-resdiary** [hashicorp/terraform#27316]
### Terraform Version

this wasn't an issue in 0.12.8
```
0.14.2
```

### Terraform Configuration Files

main.tf
```terraform
provider "null" {}

locals {
  succeed = false
}

resource "null_resource" "first" {}
resource "null_resource" "second" {
  count = 0
}

module "this" {
  source = "./module"
  value = local.succeed ? null_resource.first : null_resource.second[0]
}
```

module/main.tf
```terraform
variable "value" {}
```

### Expected Behavior

The `value` which is passed to the `this` module should be `null` and not error.

### Actual Behavior

```
Error: Invalid index

  on main.tf line 14, in module "this":
  14:   value = null_resource.second[0]
    |----------------
    | null_resource.second is empty tuple

The given key does not identify an element in this collection value.
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

- #25578

**Comment by jbardin** [comment]
Hi @elliot-resdiary 

Sorry this is working as you would expect, but this does appear to be the correct behavior as for as the terraform language is designed. Because `local.succeed` is false, the ternary expression must evaluate `null_resource.second[0]`. The expression `null_resource.second[0]` is not valid, because `null_resource.second` has can have no instances with a count of `0`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
