### ISSUE TITLE
Not able to add multiple conditions in google_monitoring_alert_policy for GCP provider alerting policy

### ISSUE THREAD

**Issue by surabhiSharma12** [hashicorp/terraform#27330]
Please help me adding multiple condition in single alerting policy for GCP provider. I am not able to get anything on documentation & my code is suffering due to it.

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by surabhiSharma12** [comment]
There is no third party support repository for GCP...or i was not able to find one. Please redirect my request if any other support channel exists.

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help, and the [Google Provider category is located here](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32). The GitHub issues here are monitored only by our few core maintainers.
