### ISSUE TITLE
provider/digitalocean: ssh_keys doesn't update on digitalocean_droplet

### ISSUE THREAD

**Issue by shirkevich** [hashicorp/terraform#2733]
I'm trying to add second ssh key to working droplet, terraform output is ok, but in fact, second key is not provisioned:

```
digitalocean_droplet.docker: Modifying...
  ssh_keys.#: "1" => "2"
  ssh_keys.1: "" => "978405"
```

**Comment by cabbiepete** [comment]
This is more of a DO thing than a terraform thing. DO only provisions ssh keys when you create droplets it never updates them post this. You can use a provisioner such as remote exec, chef, puppet to ensure the full list of keys is there.

**Comment by apparentlymart** [comment]
Based @cabbiepete's comment, it sounds like the bug here is that we should have `ForceNew` set on that attribute so that Terraform knows that it has to create a replacement droplet in order to implement an SSH key change.

**Comment by cabbiepete** [comment]
@apparentlymart I'd expect that to be an optional setting and default to not. There are other ways to get the new/updated ssh key to the server in less destructive ways which is a better default for anyone that does not quite know what they want.

**Comment by apparentlymart** [comment]
@cabbiepete is there something that Terraform could do automatically/programmatically when it detects a diff on this attribute? `ForceNew` is how Terraform models things that can only be set at creation time and can't be updated later, so that's the right thing to do unless there's something less destructive that Terraform could do instead, to apply an update here.

Your earlier comment suggested that logging in to the machine and manually tweaking the keys was the only path. If so, this is a similar situation to Amazon EC2, where the corresponding attribute (`key_pair`) is marked as `ForceNew` as I described.

**Comment by danielsreichenbach** [comment]
Adding my two cents here. I just did this on an existing droplet, where I needed to extend set of SSH keys deployed.

This is actually working, if you supply a connection object in the droplet configuration, and then add further entries to the SSH configuration.
