### ISSUE TITLE
depends_on not working well with aws_s3_bucket_object

### ISSUE THREAD

**Issue by yi2020** [hashicorp/terraform#27345]
### Terraform Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.20.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Terraform Configuration Files
```terraform

resource "aws_s3_bucket" "consoleme_files_bucket" {
  bucket = "mybucket20201217213300"
  acl    = "private"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  force_destroy = true
}

resource "aws_s3_bucket_object" "consoleme_zip" {
  bucket = aws_s3_bucket.consoleme_files_bucket.bucket
  key    = "consoleme.tar.gz"

  source = "${path.module}/consoleme.tar.gz"

  etag = md5(filebase64("${path.module}/consoleme.tar.gz"))
}

resource "aws_s3_bucket_object" "consoleme_config" {
  bucket = aws_s3_bucket.consoleme_files_bucket.bucket
  key    = "config.yaml"

  content = "somecontent"

  etag = md5(base64encode("somecontent"))
}

module "server" {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-ec2-instance?ref=v2.16.0"

  name                        = "somename"
  instance_count              = 1
  ami                         = data.aws_ami.amazon_linux.id
  instance_type               = "t2.medium"
  key_name                    = "mykey"
  subnet_id                   = "somesubnet-id"
  user_data                   = "test userdata"

  depends_on = [aws_s3_bucket_object.consoleme_zip, aws_s3_bucket_object.consoleme_config]
}
```

### Expected Behavior
When the S3 object's contents change, causing a new version, the aws_instance should be tainted and rebuilt.

### Actual Behavior
No changes identified for the aws_instance.

### Steps to Reproduce
1. terraform init
2. terrform apply
3. change s3 objects' contents
4. terraform apply (new versions for objects, nothing noticed for aws_instance under the module)

### References
- #16727 had described something similar, which seems to be partially solved in 0.13 but not to cover this case

**Comment by benoit74** [comment]
Hi @yi2020 ,

Unfortunately, as far as I can tell, `depends_on` is not meant to do what you are trying to achieve.

If I understood you well, you would like that every time one of your two files in the S3 bucket are modified, the aws_instance is recreated.

`depends_on` is (so far) only meant to express dependencies between resources in term of creation and destruction orders.

Hence your code is only instructing Terraform that during `terraform apply` it has to wait for the creation of the two files in your S3 bucket before creating the EC2 instance. And vice versa, that it must destroy the EC2 instance before destroy the two files in your S3 bucket if you issue a `terraform destroy`.

You can find a little bit more information in [this documentation](https://learn.hashicorp.com/tutorials/terraform/dependencies) and its own references at the end of the page.

As far as I can tell, I see no solution to your functional problem in Terraform itself, but maybe you might change your way of working a little bit. I imagine that there is probably a script or something which is modifying the S3 files. If possible, this script could also call the `taint` command on the aws_instance so that the next run of Terraform would recreate the intance. I can imagine that this is far from perfect, but maybe still a solution (more information on the `taint` command [here](https://www.terraform.io/docs/commands/taint.html)).

**Comment by jbardin** [comment]
Hi @yi2020,

@benoit74 is correct, `depends_on` is not going to achieve what you are trying to do here, and is likely to cause more confusion as adding `depends_on` for the entire module may cause some resources to be unknown during plan, only to have no changes once the values are known during apply.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
