### ISSUE TITLE
removed upgrade code leads to broken deployments

### ISSUE THREAD

**Issue by drue** [hashicorp/terraform#27359]
I have a number of separate Terraform modules that refer to each other with terraform_remote_state. 

I ran 0.14 on a module that had last been deployed with 0.12.  Terraform gave an error regarding the provider paths in its state and said I needed to run 0.13 to complete the upgrade process.  Running 0.13 failed because one of the remote states used by the module was saved with 0.14, and TF complained that it was incompatible without bothering to upgrade the state.

It doesn't seem possible to upgrade this module from 0.12 without removing all references to state already saved with 0.14 or manually editing the state file.

**Comment by pselle** [comment]
@drue Sorry you've run into this issue. It is true that you need to upgrade to 0.13 from 0.12 before upgrading to 0.14:

> In particular, Terraform v0.14 no longer includes the terraform 0.13upgrade command for automatically inserting provider requirements into existing modules, and the automatic mechanisms to upgrade legacy provider references in the Terraform state. You will need to successfully complete a terraform apply at least once under Terraform v0.13 before upgrading an existing configuration to Terraform v0.14.

https://www.terraform.io/upgrade-guides/0-14.html

And it's also true that you ran into the current issue related to remote state upgrades. [This will be better after 0.14.2 going forward](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md#0141-december-08-2020), but unfortunately you're still impacted at the moment.

If the errors you got in 0.12 were related to provider paths, you could possibly manually follow the steps to explicitly define your provider locations, as laid out [in the 0.13 upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html).

Sorry that you've been caught by this -- since this isn't technically a bug in Terraform, I'm going to close this issue, and encourage you to check the [forums](https://discuss.hashicorp.com/c/terraform-core) in the future since the core team monitors these issues for bugs and enhancement requests, and more people are responsive on the forums.
