### ISSUE TITLE
ECS Cluster Tagging by default 

### ISSUE THREAD

**Issue by ytessema4** [hashicorp/terraform#27354]
I am currently using terraform version 12 to build ECS cluster with task definitions but keep getting an error when running describe task definitions with —include TAGS. How can I tell it to ignore tagging?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
