### ISSUE TITLE
Terraform not picking up providers in the binary directory

### ISSUE THREAD

**Issue by vwood** [hashicorp/terraform#27355]
As of version 13, terraform is no longer able to locate providers in the same directory as the terraform binary, or those present in ~/.terraform.d/plugins/ 

Nor does the TF_LOG=TRACE ./terraform init reveal exactly where it is looking for the binaries, or why providers like terraform-provider-null when placed alongside the terraform binary no longer get found. 

I'm not interested in recreated some madly deep folder structure to replicate what would happen if I were to allow it to make requests for binaries from the internet (because I'm not insane), compiling some band-aid package written in go. 

I should be able to extract the provider release binaries and terraform should just work, bad enough that the number of config blocks keeps expanding.

Terraform used to be usable, why needlessly complicate things?

### Terraform Version

last version to work:
```
Terraform v0.12.24
+ provider.aws v2.58.0
+ provider.null v2.1.2
```

first version to fail:
```
Terraform v0.13.6
+ provider.aws v2.58.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

```terraform

 
provider "null" {
  version = "~> 2.1"
}
```

### Debug Output

https://gist.github.com/vwood/ee832aeded344074b1c6a8f7c1053d1a

### Expected Behavior

terraform should probably have searched the directory it claimed to be searching and to find the provider that is right there

### Actual Behavior

once updating to 13 or 14, terraform is unable to find files located right there next to the binary.

### Steps to Reproduce

1. `terraform init`

### Additional Context

Firewall disallows random binaries like terraform from connecting to random websites to pull down binaries and run them. You know, because I'm not insane.

**Comment by jbardin** [comment]
HI @vwood 

As part of introducing namespaced providers, the legacy search directories were removed in 0.13. You can see the [0.13 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers) on the subject, and the current documentation goes into more detail under [Provider Installation](https://www.terraform.io/docs/commands/cli-config.html#provider-installation)

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
