### ISSUE TITLE
A child module doesn't inherit in-house provider

### ISSUE THREAD

**Issue by vosmax** [hashicorp/terraform#27361]
**Terraform Version** 
0.13.5, 0.14.3

**Terraform Files**
_in-house provider location_
```
/Users/user/.terraform.d
├── checkpoint_cache
├── checkpoint_signature
└── plugins
    └── test.local
        └── plugins
            └── rds
               └── 0.0.1
                   └── darwin_amd64
                       └── terraform-provider-rds_v0.0.1
```
_versions.tf_
```
terraform {
  required_version = ">= 0.13"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.22.0"
    }
    rds = {
      source  = "test.local/plugins/rds"
      version = "~> 0.0.1"
    }
  }
}
```

_rds.tf_
```
module "my-rds" {
  source = "../modules/my-rds"
  tags = merge(
    {
      "Terraform"   = "true"
      "Environment" = "test"
    },
    var.custom_tag
  )
}
```
_../modules/my-rds/main.tf_
```
resource "rds_db_parameter_group" "postgres-10" {
  name        = "postgres-10"
  family      = "postgres10"
  description = "Customised parameter group for PostgreSQL 10"
  tags        = var.tags
  parameter {
    name         = "log_statement"
    value        = "mod"
    apply_method = "immediate"
  }
```

**Command output**
```
terraform providers 
Providers required by configuration:
.
├── provider[test.local/plugins/rds] ~> 0.0.1
├── provider[registry.terraform.io/hashicorp/aws] ~> 3.22.0
└── module.my-rds
   ├── provider[registry.terraform.io/hashicorp/rds]
   └── provider[registry.terraform.io/hashicorp/aws]
```

**Expected Behavior**
The in-house provider should be inherited from the parent and used

**Actual Behavior**
Terraform doesn't use inheritance from parent module

**Comment by jbardin** [comment]
Hi @vosmax 

Sorry about the confusion here, the documentation can probably be improved in this area. Only default providers can be inherited automatically, so the module will also need to declare the required provider.

**Comment by jbardin** [comment]
Hello,

The 0.15 release comes with enhanced validation of module provider configuration, which will help indicate when providers are not correctly passed between modules. We do try to call out that modules must always declare their provider requirements in the [module documentaion](https://www.terraform.io/docs/language/modules/develop/providers.html#implicit-provider-inheritance) as well as the [provider requirements](https://www.terraform.io/docs/language/providers/requirements.html#requiring-providers).

Since this is working as expected, I'm going to close this out. While we can sometimes help with certain simple problems here, if you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks
