### ISSUE TITLE
panic: value is marked, so must be unmarked first - for loop in output

### ISSUE THREAD

**Issue by iamalirezaj** [hashicorp/terraform#27375]
### Terraform Version

```
Terraform v0.14.3
```

### Terraform Configuration Files

```terraform
output "master_nodes" {
  value = {
    for i in range(length(hcloud_server.control_planes)) :
    hcloud_server.control_planes[i].name => {
      name = hcloud_server.control_planes[i].name
      ip = hcloud_server_network.control_planes[i].ip
      connection = {
        host = hcloud_server.control_planes[i].ipv4_address
      }
    }
  }
  sensitive = true
}

```

### Debug Output

https://gist.github.com/iamalirezaj/6886a2805f82b09078777e2658fc3805

### Crash Output

https://gist.github.com/iamalirezaj/6886a2805f82b09078777e2658fc3805

### Expected Behavior

Command succeeded

### Actual Behavior

panic: value is marked, so must be unmarked first

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Im using a for loop to create an object of multiple servers in an output!

### References

- #27107

**Comment by clement-pruvot** [comment]
Same error with a for_each loop too.

**Comment by danieldreier** [comment]
Hi! Thank you for reporting this! Based on your errors, I believe that this is probably a valid issue, and in order to hand it off to engineers to be fixed I need to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, the example case you provided has a bunch of variables that I don't have the data for. It would be super helpful if you could replace those with static data or declare variables so I don't have to invent fake data to reproduce your crash case.

@clement-pruvot the same goes for you - you may, or may not be seeing the same underlying bug, and so if you can come up with a simple reproduction case,  we can confirm whether the fix we make for the parent issue also fixes the issue you're seeing.

Can you both please restate your reproduction cases such that I can copy-paste it and run it locally? If you need to use providers, this would ideally use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies.

**Comment by iamalirezaj** [comment]
@alisdair Yeah, i was trying to explain what i was doing when i got this error.
as you can see, i was using hetzner cloud provider and it was a little bit difficult for me to debug the code to see what was actually happen!
Thanks for checking this out
