### ISSUE TITLE
Error: Resource Group "test-eastus2-poc-rg01" was not found on ../TerraformModules/AzureFirewall/main.tf line 1, in data "azurerm_resource_group" "this": 1: data "azurerm_resource_group" "this"

### ISSUE THREAD

**Issue by ManyaSinghal** [hashicorp/terraform#27397]
Hello Team

I am using the new version of the terraform 0.14.03 and getting the above error while i am deploying RG from anther module and calling that RG in firewall module and getting the error. in Firewall module i am using data source to call the RG.

Is this the issue with the terraform version 0.14.0 because when i changed it back to 12.28 it worked fine.

Can anyone help me on this as i am stuck on this

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
