### ISSUE TITLE
Configured provider not recognized inside module

### ISSUE THREAD

**Issue by welsipieters** [hashicorp/terraform#27394]
### Terraform Version

```
Terraform v0.14.3
```

### Terraform Configuration Files

```terraform
#main.tf
terraform {
  required_version = ">= 0.14"
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "2.3.0"
    }
  }
}

provider "digitalocean" {
  token = var.do_token
}

module "spaces" {
  source     = "./Infrastructure/Spaces"
  stack_name = var.stack_name   
  spaces_key = var.spaces_key  
  spaces_secret = var.spaces_secret
}
```

```terraform
3./Infrastructure/Spaces/main.tf

variable "stack_name" {
}

variable "region" {
}

variable "spaces_key" {
  
}

resource "digitalocean_spaces_bucket" "backend_bucket" {
  name = "${var.stack_name}-state"
  region = var.region
  acl = "private"
}
```

### Debug Output
Output of `terraform init`
https://gist.github.com/welsipieters/0a796f56cd4f9674cc222aba7dc5bf17

Output of `terraform providers`
https://gist.github.com/welsipieters/34fbd24b833cc826d121513861bffc55

### Crash Output
As far as I know, Terraform doesn't panic so there's no crash log.

### Expected Behavior
Terraform should have initialized successfully.

### Actual Behavior
Terraform doesn't initialize. It looks like I define provider `digitalocean/digitalocean` but when I use it inside a module it queries `hashicorp/digitalocean`. I have tried to explicitly pass the provider to the module using the providers block (both with and without provider alias) and it didn't seem to make a difference.

### Steps to Reproduce
1. `terraform init`

**Comment by jbardin** [comment]
Hi @welsipieters 

It appears you're looking for the `providers` meta argument for the module to pass in the provider configuration. See the [Providers Within Modules](https://www.terraform.io/docs/modules/providers.html) documentation for more details.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
