### ISSUE TITLE
zh hashes missing from .terraform.lock.hcl when using plugin cache

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform#27399]
### Terraform Version

```
0.14.3
```

### Terraform Configuration Files

```terraform
  required_providers {
    aws = {
      version = "= 3.20.0"
    }
  }
```

I've scripted a full reproduction case at https://github.com/danieldreier/terraform-issue-reproductions/tree/master/27399

### Expected Behavior
Lock files should be generated identically regardless of whether plugin caches are enabled or not

### Actual Behavior
When lock files are regenerated and plugin cache is in use, `zh` hashes are missing from the generated lock file.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. Configure a plugin cache
2. `terraform init`
3. At this stage, `.terraform.lock.hcl` contains both `h1` and`zh` hashes.
4. `rm .terraform.lock.hcl`
5. Re-run `terraform init`
6. At this point, `.terraform.lock.hcl` will only contain an `h1` hash and the `zh` hashes are absent.

### Additional Context
I'm creating this based on an internal customer escalation via HashiCorp support.

**Comment by pselle** [comment]
Related issue: https://github.com/hashicorp/terraform/issues/27264. There is an extensive response on that issue that likely explains the behavior, because after removing the file, generating the lock from only the cache would be expected to lack the `zh` hashes (see the heading: "Local Filesystem Mirrors don't support the zh: scheme")

**Comment by apparentlymart** [comment]
I took a deeper look into this today because I wondered if we could make a special exception for the cache directory in particular, given that it's behavior is already a little different than for a local mirror.

After some experimentation I found a note I left for myself about this while I was working on this feature:

```go
// NOTE: The behavior here is unfortunate when a particular
// provider version was already cached on the first time
// the current configuration requested it, because that
// means we don't currently get the opportunity to fetch
// and verify the checksums for the new package from
// upstream. That's currently unavoidable because upstream
// checksums are in the "ziphash" format and so we can't
// verify them against our cache directory's unpacked
// packages: we'd need to go fetch the package from the
// origin and compare against it, which would defeat the
// purpose of the global cache.
//
// If we fetch from upstream on the first encounter with
// a particular provider then we'll end up in the other
// codepath below where we're able to also include the
// checksums from the origin registry.
```

This comment reminded me that indeed this is not solvable today for the same reasons as described in #27264: the cache directory is also in the "unpacked" layout and so we don't have any way to check `zh:` checksums against it, and so we have no way to verify that what is cached matches the upstream.

We can potentially address this in future, once we've addressed the design challenges I described in the other issue, by doing the `ProviderMeta` fetch _before_ we check the global cache, and then requiring that the cached package must match the hashes from upstream. That would then allow us to safely use the upstream hashes in the lock file even though we actually copied the package from the cache. We can't do that until the registry is able to report `h1:`-style hashes, though.
