### ISSUE TITLE
Dependency which should be created after *and* deleted after

### ISSUE THREAD

**Issue by hectorj** [hashicorp/terraform#27392]
### Current Terraform Version
```
v0.14.3
```

### Use-cases

Hi!

I'm working on a provider for Google's site-verification API: https://github.com/hectorj/terraform-provider-googlesiteverification

I have one problem with it:

I need to be able to tell Terraform that the verification needs to be created *after* the DNS record, but also needs to be deleted *after* the DNS record.

So I have Resource A and Resource B.

While creating them I want Terraform to create A then create B.
While deleting them I want Terraform to delete A then delete B.

### Attempted Solutions

`depends_on` can only achieve 1 of this 2 things. If B `depends_on` A, then B will be created after A but B will also be deleted before A.

Right now the only workaround I have is to not put any `depends_on`, and rely on the retry mechanism instead but it is not ideal.

### Proposal

I'm not sure what's the best way to achieve this.

This is a niche kind of dependency.

**Comment by jbardin** [comment]
Hi @hectorj 

It is quite odd that this particular resource cannot be destroyed until after its dependency has been destroyed, but if that's the case it isn't an easy problem to solve in terraform. Adding a way to re-order the destroy like this can't be done in general, because changing the destroy ordering as described would cause dependency cycles when resources are replaced. Manually removing the record first would be the only way to reliably do this now. We also have the idea for partial/phased applications in #4149, though there is no satisfactory proposal for that as of yet. 

My initial suggestion would be to see if there is anything in the remote API which could help with this. Since the requirement for destroying the dependency first is so strange, I could imagine there being some option to force the removal or disable the check from preventing the deletion of the siteverification resource.

Since any solution to this would require the ability to automatically partially apply or destroy a configuration in order to prevent cycles, I'm going to close this with the link to #4149. This repo is only monitored by a few core developers, so you may want to try [the community forum](https://discuss.hashicorp.com/) where there may be more provider developers that have encountered similar problems.

Thanks!

**Comment by hectorj** [comment]
I'll try to see if I can contact Google to ask them to remove the requirement from [the API](https://developers.google.com/site-verification/v1/webResource/delete), though I don't have much hope there.

Thanks for the thorough answer, have a nice day!
