### ISSUE TITLE
Output dependency not respected in tf13

### ISSUE THREAD

**Issue by mkondratowicz-gwre** [hashicorp/terraform#27398]
### Terraform Version

```
Terraform v0.13.5
```

### Terraform Configuration Files

ec2 module
```terraform
locals {
  tag_key = "test-tag"
}
resource aws_instance ec2 {
  ami = "ami-08c99b2a0d31e3929"
  instance_type = "t2.small"

  tags = {
    (local.tag_key) ="some-test-tag"
  }
}

output ec2_tag {
  value = {
    key = local.tag_key
    value = aws_instance.ec2.tags[local.tag_key]
  }
  depends_on = [
    aws_instance.ec2
  ]
}
```
Main module
```terraform
module ec2 {
  source = "./ec2"
}

data aws_instance test-ec2 {
  instance_tags = {
    (module.ec2.ec2_tag.key) = module.ec2.ec2_tag.value
  }
}

```

### Expected Behavior

The `output ec2_tag`  shouldn't be available until the `resource aws_instance ec2` is created, hence the `data aws_instance test-ec2` should not be evaluated before the ec2 is created.

### Actual Behavior

Output is available immediately after running apply and it fails with error `Your query returned no results. Please change your search criteria and try again.` as the data tries to get the instance that does not exists yet.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

This setup works fine with terraform v0.12.29.

**Comment by jbardin** [comment]
@mkondratowicz-gwre 

While the order of evaluation in terraform is defined by the configured dependencies, interpolation is always done with all the state available at that time. This means that the `output.ec2_tag` value is known immediately during the plan, since all the referenced values are statically defined in the configuration. Since `module.ec2.ec2_tag.key` and `module.ec2.ec2_tag.value` are known, there is nothing preventing the data source from being evaluated, resulting in the error you see here. Note that adding `depends_on` to the output creates a dependency edge in the graph, but does defer evaluation, and is therefore redundant with the `aws_instance.ec2` reference. 

Since you should generally not be using a data source to represent a resource created within the same configuration, it would be preferable to pass the necessary data directly from the `aws_instance` into the module itself. If the data source is unavoidable, you can also get the desired behavior by using a computed value from the instance rather than something statically defined in the configuration. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, if you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by mgusiew-guide** [comment]
Thank you for detailed explanation @jbardin , that helps ! The reason why we submitted this as an issue was because this works in Terraform 0.12.29 (for some reason data evaluation is pushed to apply phase). We were not aware of the fact that we were depending on implementation detail and that the contract is different. Actually before submitting the issue we created a workaround that works in Terraform 0.13.x. We simply added depends_on = [module.ec2] to the data element in main module which also pushed data evaluation into apply phase and things started to work again. This is short term workaround (I am mentioning it in case if someone else hits that problem when migrating to Terraform 0.13.x), for long term solution we will place main module in separate terraform state and orchestrate from outside (two terraform invocations) using remote state. Unfortunately for our use case pushing the aws_instance vars does not make too much sense, the other option that we considered was to add random suffix to tag value that also pushes data evaluation to runtime but is a hack.

This problem will be hitting us in future, we often try to encapsulate things in modules as we come from Object Oriented languages and then when we orchestrate those modules using Terraform module things may not work as expected cause one module may start before the other finishes (which is not always desirable). We thought that dependencies would address that but as I understand they are only applicable to apply phase, plan can still start to evaluate something even though its dependencies are not evaluated yet. I guess in such case the solution that always works is to orchestrate from outside with remote state, the other option is not to use data elements for things that don't exist before the plan (it is better to pass necessary values) or to somehow force data evaluation to apply phase (which has some other consequences).  

Anyways once again huge thanks for your support and explanation. Now we understand what kind of options are available and have more clarity on how to proceed !
