### ISSUE TITLE
Adding dynamic tags to the aws_vpc and aws_eip

### ISSUE THREAD

**Issue by parjun8840** [hashicorp/terraform#27390]
### Current Terraform Version
```
0.14.3
```

### Use-cases
Using the similar kind of tagging code would make it more user friendly. As most of other resources ( Which I have been using till now) supports this and just for these two I have to remember different syntax. 

`  on modules/vpc/main.tf line 21, in resource "aws_vpc" "mod_vpc":
  21: dynamic "tag" {

Blocks of type "tag" are not expected here.

Error: Reference to undeclared local value

  on modules/vpc/main.tf line 186, in resource "aws_eip" "nat":
 186:   count = var.create_vpc && var.enable_nat_gateway && false == var.reuse_nat_ips ? local.nat_gateway_count : 0

A local value with the name "nat_gateway_count" has not been declared.

Error: Unsupported block type

  on modules/vpc/main.tf line 188, in resource "aws_eip" "nat":
 188:    dynamic tag{

Blocks of type "tag" are not expected here.`

### Proposal
Supporting dynamic tag for: aws_vpc and aws_eip

**Comment by parjun8840** [comment]
I have gone through the comment https://github.com/hashicorp/terraform/issues/24857#issuecomment-623782292 and is helpful. Still it would be a great help if you can consider this as a request.

**Comment by jbardin** [comment]
Hi @parjun8840 

That resource uses a map for the `"tags"` attribute rather than a block, so you cannot use it with `dynamic`. Since it is a map, you can use a [`for` expression](https://www.terraform.io/docs/configuration/expressions/for.html) directly to assign the desired value. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
