### ISSUE TITLE
Unlock state

### ISSUE THREAD

**Issue by bhatanku1** [hashicorp/terraform#27406]
I am stuck with a unlock state problem. I am using dynamoDb to maintain the state locks. After running terraform apply, I forgot to enter "yes". After some time when I realized, a entered "no" and it threw an error regarding state lock. All subsequent terraform apply threw `Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed`
I tried to use the unlock command: `terraform force-unlock -force` it says Local state cannot be unlocked by another process
`. I already checked there are no terraform processes running. I could also not see this lock Id entry in the DynamoDb so that I could remove it manually. Is there anything else I can try?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
