### ISSUE TITLE
Module not auto depend on outside resource

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform#27417]
### Terraform Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
```

### Terraform Configuration Files

`main.tf`

```terraform
resource azurerm_resource_group "rg" {
  name     = var.name
  location = var.location
}

module "vm" {
  source = "../../modules/vm"
  name   = var.name
  rg     = azurerm_resource_group.rg.name
}
```

`modules/vm/vm.tf`
```terraform
data azurerm_resource_group "rg" {
  name = var.rg
}

resource "azurerm_windows_virtual_machine" "vm" {
  name                  = var.name
  resource_group_name   = data.azurerm_resource_group.rg.name
  ...
}
```

### Expected Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

  # azurerm_resource_group.rg will be created
  + resource "azurerm_resource_group" "rg" {
      + name     = "testrg"
      ...
    }
  # module.vm.azurerm_windows_virtual_machine.vm will be created
  + resource "azurerm_windows_virtual_machine" "vm" {
      + resource_group_name        = "testrg"
      ...
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

```
Error: Error: Resource Group "testrg" was not found

  on modules/vm/vm.tf line 43, in data "azurerm_resource_group" "rg":
  43: data azurerm_resource_group "rg" {
```

### Steps to Reproduce

`terraform plan`

### Additional Context

It is possible to workaround with adding `depends_on = [azurerm_resource_group.rg]` into `module "vm" {` but this should not be necessary given that exported attribute `azurerm_resource_group.rg.name` is referenced, causing natural and _obvious_ dependency.

**Comment by jbardin** [comment]
Hi @Tbohunek 

Data sources are designed to be read as soon as possible, so because the value of `var.rg` is known during planning, the data source will be read. There is a dependency added between the two nodes, which will ensure `azurerm_resource_group.rg` is planned before `data. azurerm_resource_group.rg` is read, but that is not helpful in this situation.

In general you should try not to have a data source that represents a resource created within the same configuration, and pass around the values form the resource itself. If that is unavoidable for some reason, you should reference a computed value from the resource to ensure that it is not read during apply.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by Tbohunek** [comment]
Well, I did consider this a bug (given that it works when I force `depends_on`.

However, I also agree that the same can be done without using the `data` source at all, so I will do that.

**Comment by Tbohunek** [comment]
Well, actually no, I cannot do without the `data`. I want to use the `RG's` `.location` and `.tags` within the `vm` module.

@jbardin What's the right practice to do this? when deploying a module resources into a RG created outside that module?

**Comment by jbardin** [comment]
If the resource is lacking attributes which you can get from the data source, that is an issue to be raised with the provider. It's customary for a resource and data source to provide the same information.

If you want to force the data source to be read during the apply phase, then the workaround you mentioned of using `depends_on` is one way to do it.

**Comment by Tbohunek** [comment]
No, the `data` exported attributes work fine, I'm just clarifying its presence inside the `vm` module.

I do not understand why the `depends_on` is required if the module naturally depends on the RG via `rg     = azurerm_resource_group.rg.name`. This to me is a bug.

**Comment by jbardin** [comment]
The reason `depends_on` works in this case, is because it depends on the resource as a whole rather than specific attributes of that resource. This means that _any_ unknown value in the referenced resource requires reading of the data source to be deferred until apply. https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies

**Comment by Tbohunek** [comment]
Thank you. I would argue that the documentation doesn't exactly say that as I set the `depends_on` within `module {}` and I'm not on `Terraform 0.12 and earlier`, but your explanation made it clear.
