### ISSUE TITLE
How to Create Terraform Lambda Layer by specifiying ARN

### ISSUE THREAD

**Issue by mohamednazarae** [hashicorp/terraform#27433]
### Current Terraform Version

```
0.12.28
```

### Use-cases

Manally via AWS console I have created Lambda Layer by specifying ARN. Please check the screenshot below.

![image](https://user-images.githubusercontent.com/70500230/103900604-fcac8c00-511d-11eb-93fe-7d872087efbb.png)

how to I create the same via Terraform code.

I see that feature is not available in Terraform Lambda Layer resource section. Please help

**Comment by jbardin** [comment]
Hi @mohamednazarae,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

If this is a feature missing from the AWS provider, you can file an issue with that provider directly.

Thanks!
