### ISSUE TITLE
How to reference root module variable file to child module

### ISSUE THREAD

**Issue by uniboxdevops** [hashicorp/terraform#27434]
Hi Team,

i am new to terraform and i unable to understand some concepts.

Question: How to reference root module variable file to child modules without creating multiple variable.tf file in child module.

currently i am maintaining all_variable.tf file for any variable reference. and i copied to all child modules  to work properly but still it's not working. hence please help me on this. 
example:
.
├── modules
│   ├── compute
│   │   ├── all_variable.tf
│   │   └── instance.tf
│   └── network
│       ├── firewall
│       │   ├── firewall.tf
│       │   └── firewall_vars.tf
│       └── vpc
│           ├── all_variable.tf
│           └── vpc.tf
└── setup
    ├── all_variable.tf
    ├── main.tf
    ├── provider.tf
    ├── terraform.tfstate
    └── terraform.tfstate.backup

Thanks in advance.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
