### ISSUE TITLE
terraform want to recreate the entire architecture

### ISSUE THREAD

**Issue by lucbrug** [hashicorp/terraform#27443]
Hello everyone.
We used to develop and deploy with Terraform in local on a Windows10 computer. Now that we're moving the pipeline to Jenkins (that is running on CentOS) between our gitlab repository and AWS environment. 
When we execute the plan in jenkins, terraform want to destroy and recreate everything despite been up to date when using my local computer
![image](https://user-images.githubusercontent.com/52967739/104000200-2f966480-519e-11eb-8d70-5b05cf9fe05e.png)

terraform correctly find the tfstate in our backend (_terraform show_ is identical)
init has correctly been done and _terraform provider_ is identical as well

### Terraform Version
```
terraform 12.28
```
![image](https://user-images.githubusercontent.com/52967739/104001615-36be7200-51a0-11eb-8065-9cd3d9d23a01.png)
![image](https://user-images.githubusercontent.com/52967739/104001955-ae8c9c80-51a0-11eb-8c07-a0e0f3ad58e2.png)

![image](https://user-images.githubusercontent.com/52967739/104001685-4e95f600-51a0-11eb-80ce-be6d6605446d.png)

### Terraform environement

jenkins                       2.249.2
terraform Plugin       1.0.10
pipeline AWS Steps  1.43  

jenkins machine: Centos 7.7.1908
local computer: Windows 10

### Expected Behavior
same behaviour in jenkins and in local computer

### Actual Behavior
terraform disregard existing infrastructure and want to recreate everything

### References

- #18780

**Comment by jbardin** [comment]
Hi @lucbrug 

It appears that the individual instances of terraform are accessing different version of your state. I would verify that the same state file is access in each case.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
