### ISSUE TITLE
Incorrect parameter name in policy_set_definition.policy_definition_reference

### ISSUE THREAD

**Issue by jonathanpmay** [hashicorp/terraform#27478]
### Terraform Version

```
Terraform v0.14.4
```

### Terraform Configuration Files

```
resource "azurerm_policy_set_definition" "abc" {
  name                  = "foo"
  display_name          = "bar"
  policy_type           = "Custom"
  management_group_name = azurerm_management_group.xyz.name

  policy_definition_group {
    name         = "foo"
    display_name = "bar"
  }

  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/{GUID}"
    group_names = ["foo"]
  }
}
```

### Expected Behavior

According to the [azurerm_policy_set_definition documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_set_definition#policy_definition_reference), the `policy_definition_reference` block defines `policy_group_names` as an available parameter.

This parameter name can be confirmed in the [azurerm_policy_set_definition](https://github.com/terraform-providers/terraform-provider-azurerm/blob/678402fa93be8e375e9ab676c009349dfe7a9bd5/azurerm/internal/services/policy/policy_set_definition_resource.go#L158-L163) object code.

### Actual Behavior

According to the [azurerm_policy_set_definition documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_set_definition#policy_definition_reference), the `policy_definition_reference` block defines `group_names` as an available parameter.

```
terraform validate

Error: Unsupported argument

  on main.tf line 48, in resource "azurerm_policy_set_definition" "abc":
  48:     group_names = ["foo"]

An argument named "group_names" is not expected here.
```

### Steps to Reproduce

1. Create `azurerm_policy_set_definition` resource with a `policy_definition_reference` block and include the `group_names` parameter
2. `terraform init`
3. `terraform plan`

**Comment by jbardin** [comment]
Hi @jonathanpmay 

It appears you may be using a different version of the AzureRM provider than the current documented version. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help, specifically in the [Azure Category](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

If you feel this is an issue with the azure provider, you can file an issue in that projects repo [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues).

Thanks!
