### ISSUE TITLE
Conditional output of `null` causes permanent 'hidden' diff in plans

### ISSUE THREAD

**Issue by jeohist** [hashicorp/terraform#27490]
### Terraform Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~>3.0"
    }
  }

  required_version = "0.14.4"
}

variable "foo" {
  default = false
}

resource "null_resource" "foo" {
  count = var.foo ? 1 : 0
}

output "foo" {
  value = var.foo ? null_resource.foo.0.id : null
}
```

### Plan Output
```
❯ terraform plan -detailed-exitcode || echo $?

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

2
```

### Debug Output
https://gist.github.com/jeohist/e7e7e51ed06dcbacf6ea89e366f488c5

### Expected Behavior
After applying, `terraform plan -detailed-exitcode || echo $?` should return 0, not 2
Or: After applying, `terraform plan -detailed-exitcode || echo $?` should return 2, and output *why*

### Actual Behavior
After applying, `terraform plan -detailed-exitcode || echo $?` returns 2

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan -detailed-exitcode || echo $?` 

### Additional Context
We can workaround this issue by outputting `""` instead of `null`, but the behaviour is not very intuitive.

**Comment by apparentlymart** [comment]
Hmm yes, this seems like a quirk that results from us having reused the same diff printing code for both resource changes and output changes.

The trick here is that for resource arguments, `null` is exactly the same as not setting an argument at all and so the diff printer is designed to just skip showing changes where both the old and new value are `null`. However, that doesn't hold for output values: for those, the existence of a particular output value is independent of whether it's set to `null`, because the _declarations_ are static, even though the values are dynamic.

It seems like we might need to find a way to make a special case here so that the "Changes to Outputs" section will include an entry for each output value that's defined, even if its dynamic value turns out to be `null`, but without _also_ making a bunch of unnecessary null arguments appear inside resource instance diffs.
