### ISSUE TITLE
Documentation Issue for Terraform Output

### ISSUE THREAD

**Issue by andydkelly-ig** [hashicorp/terraform#27519]
### Terraform Version
0.13.6
-->

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hi @andydkelly-ig 

There doesn't seem to be any info included here. If you have a question, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. If you still have an issue, please fill out the issue template with the required information.

Thanks!

**Comment by andydkelly-ig** [comment]
Sorry for that - i've no idea what i did wrong

**Comment by marcstreeter** [comment]
I am experiencing the same issue but I'm using 0.14.5.  I found the same documentation as the OP mentioned and this also breaks a command line script [in the guide for eks deployment](https://learn.hashicorp.com/tutorials/terraform/eks#configure-kubectl).  The output of the error I get ( as shown above) is also the same:

```
Usage: terraform output [options] [NAME]

  Reads an output variable from a Terraform state file and prints
  the value. With no additional arguments, output will display all
  the outputs for the root module.  If NAME is not specified, all
  outputs are printed.

Options:

  -state=path      Path to the state file to read. Defaults to
                   "terraform.tfstate".

  -no-color        If specified, output won't contain any color.

  -json            If specified, machine readable output will be
                   printed in JSON format
Error parsing command-line flags: flag provided but not defined: -raw
```
two things are seen here:
- it's erroring because the flag `-raw` is not recognized
- the valid options no longer list `-raw` as a valid option.  

So was the option removed? If so should the documentation be updated?


Further for those who will hit this in the future:

I was able to get the value I wanted by changing the original command:

```
terraform output -raw region
```

to a new command

```
terraform output -json | jq -r '.region.value'
```
__that means `jq` is something that will need to be installed and while that's easy to install on linux I'm not sure what it means for other operating systems__

I don't believe this is a bug with the software per se but more a bug with prevalent documentation. As this is not stable software I'm not entirely surprised but I would think this task could be pointed to the right direction to update the documentation. Thoughts?  I *do* miss the `-raw` option as it removes the dependency on `jq`.

**Comment by jbardin** [comment]
Hello,

@andydkelly-ig, the documentation applies only to the current release, which is 0.14.5.  The `-raw` option did not exist prior to 0.14. 

@marcstreeter, Can you please verify the version you are using? The `-raw` option is present in 0.14.5.

```
% terraform -version
Terraform v0.14.5
% terraform output -h
Usage: terraform output [options] [NAME]

  Reads an output variable from a Terraform state file and prints
  the value. With no additional arguments, output will display all
  the outputs for the root module.  If NAME is not specified, all
  outputs are printed.

Options:

  -state=path      Path to the state file to read. Defaults to
                   "terraform.tfstate".

  -no-color        If specified, output won't contain any color.

  -json            If specified, machine readable output will be
                   printed in JSON format.

  -raw             For value types that can be automatically
                   converted to a string, will print the raw
                   string directly, rather than a human-oriented
                   representation of the value.

% echo $(terraform output -raw testoutput)
outputvalue
```

**Comment by marcstreeter** [comment]
Oops -- I need to read better, I'm on `Terraform v0.14.2`. I'm reading `terraform -version`  wrong:

```
$ terraform -version
Terraform v0.14.2

Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

yes ignore me :|

**Comment by marcstreeter** [comment]
k - updated and `-raw` works as documented, sorry for the noise!

**Comment by andydkelly-ig** [comment]
thanks @jbardin my mistake. Thanks for clarifying.
