### ISSUE TITLE
Error with renamed provider alias in nested modules

### ISSUE THREAD

**Issue by jasonhuling** [hashicorp/terraform#27539]
Terraform is treating proxy providers with only aliases in nested modules as fully instantiated providers and returning an error that it is not supported when using `depends_on` or `count` on the top level module.

This error only seems to occur if the alias name is changed between the top level module and the nested module. If you change the alias name between the root configuration and the top level module it will not error.

For example, the following two **will NOT work** from the example repo [examples/level-2-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-count) and [examples/level-2-depends-on](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-depends-on) where the providers are passed like the following:
```
root [aws.us-west-2] -> module.level_2 [aws.us-west-2] -> module.level_1 [aws]
root [aws.other-us-east-1] -> module.level_2 [aws.other-us-east-1] -> module.level_1 [aws.other]
```

But the following **will work** from the example repo [examples/level-2-alt-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-alt-count) where the providers are passed like the following:
```
root [aws.us-west-2] -> module.level_2_alt [aws] -> module.level_1 [aws]
root [aws.other-us-east-1] -> module.level_2_alt [aws.other] -> module.level_1 [aws.other]
```

### Terraform Version
```
Terraform v0.14.4
```
Reproducible from `v0.13.0` to `v0.14.4`

### Terraform Configuration Files

GitHub Repository: https://github.com/jasonhuling/terraform-nested-provider-alias-bug

Repository Layout:
* [examples/level-2-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-count):  An example using `count` in the module which will cause the error.
* [examples/level-2-depends-on](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-depends-on): An example using `depends_on` in the module which will cause the error.
* [examples/level-2-alt-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-alt-count):  An example using `count` in the module with renamed provider aliases which will NOT cause the error.

### Debug Output
https://github.com/jasonhuling/terraform-nested-provider-alias-bug/blob/main/examples/level-2-count/terraform-init-trace.log

### Expected Behavior
Terraform should have initialized without any issues.

### Actual Behavior
The following error occurred:
```
Error: Module does not support count

  on main.tf line 13, in module "level_2":
  13:   count  = 1

Module "level_2" cannot be used with count because it contains a nested
provider configuration for "aws", at ../../modules/level-1/main.tf:4,10-15.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block.


Error: Module does not support count

  on main.tf line 13, in module "level_2":
  13:   count  = 1

Module "level_2" cannot be used with count because it contains a nested
provider configuration for "aws.other", at
../../modules/level-1/main.tf:6,10-15.

This module can be made compatible with count by changing it to receive all of
its provider configurations from the calling module, by using the "providers"
argument in the calling module block.
```

### Steps to Reproduce
1. Navigate to [examples/level-2-count](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-count) or [examples/level-2-depends-on](https://github.com/jasonhuling/terraform-nested-provider-alias-bug/tree/main/examples/level-2-depends-on).
2. Run `terraform init`.

### Additional Context
Using with aws-vault like the following: `aws-vault exec default -- terraform init`

### References
This issue seemed like it could possibly be related: https://github.com/hashicorp/terraform/issues/21699

**Comment by mildwonkey** [comment]
Hi @jasonhuling , thank you for the excellent reproduction repository, and I'm sorry you've run into this issue!

This is, in my professional opinion (😉), Super Weird! I think I see multiple issues: 

- `count`, `for_each`, and `depends_on` are expected to fail when you have a non-aliased provider inside your module, ie the `provider "aws" {}` block in `modules/level-1/main.tf`
- and yet sometimes your example works, ie `examples/level-2-alt-count`
- fixing the provider block in  modules/level-1/main.tf (so it also has an 'alias') does not fix the error when running init from `examples/level-2-count`, which I would have expected. 

I suspect, but do not know for certain, that the problem lies somewhere within [`validateProviderConfigs`](https://github.com/hashicorp/terraform/blob/master/configs/configload/loader_load.go#L113), which at a glance is looking at provider type names instead of fully qualified source addresses. I'm not _positive_ that's where the issue is, but it's where I would suggest whomever looks into this starts.

**Comment by mark-at-nuna** [comment]
Hi! I also made a [reproduction repository](https://github.com/mark-at-nuna/terraform_module_providers/blob/main/main.tf) for what I think is the same issue. I've read the [Passing Providers Explicitly](https://www.terraform.io/docs/language/modules/develop/providers.html#passing-providers-explicitly) doc and I think I'm doing proxy provider blocks correctly.

The root module in [main.tf](https://github.com/mark-at-nuna/terraform_module_providers/blob/main/main.tf) defines the AWS providers `root_east` and `root_west`. It passes them into [first_module](https://github.com/mark-at-nuna/terraform_module_providers/blob/main/local_modules/first_module/main.tf), which has proxy provider blocks with the aliases `first_east` and `first_west`.

That works fine. (Everything applies cleanly at [this commit](https://github.com/mark-at-nuna/terraform_module_providers/tree/ca093087319da8385ea60eae67912300ea4e2d44).) But when first_module tries to pass those providers into second_module, which has proxy provider blocks with the aliases `second_east` and `second_west`, I hit the "because it contains a nested provider configuration" error.

I'm using Terraform 0.13.6.

**Comment by mark-at-nuna** [comment]
If this helps, I reproduced the issue as [a failing test](https://github.com/hashicorp/terraform/compare/v0.13...mark-at-nuna:mark-debugs-providers?expand=1), trying to match the style of the existing tests as closely as possible.
