### ISSUE TITLE
How to read google_cloud_run_service.status.url ?

### ISSUE THREAD

**Issue by alex-pravdin-sn** [hashicorp/terraform#27586]
In the documentation (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#attributes-reference), I see the `status` attribute with the `url` field. But when I try to read it `google_cloud_run_service.sample.status.url` it shows the error with the underlined `url` part: `This value does not have any attributes.` What? What I'm doing wrong? Is anything wrong with the documentation?

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

Additionally, you're asking a question about the Google provider, so I suggest asking/searching on that forum rather than the Core forum.
