### ISSUE TITLE
 terraform  init -reconfigure still read file backend config

### ISSUE THREAD

**Issue by liuyangc3** [hashicorp/terraform#27580]
### Terraform Version
Terraform v0.14.5

### Terraform Configuration Files
```terraform
terraform {
  required_providers {
    alicloud = {
      source = "aliyun/alicloud"
    }
  }

  backend "oss" {
    bucket              = "bucket"
    key                 = "alicloud"
    region              = "cn-zhangjiakou"
    assume_role {
      role_arn = "acs:ram::...."
    }
  }
}
```

### Expected Behavior

`terraform init -reconfigure`  should ignore default backend config block in file.

### Actual Behavior
the assume role was deleted on alicloud, I want to change  `assume_role` to `ecs_role_name` with `-reconfigure` with following command

```shell
terraform -chdir=. init -reconfigure -backend-config "bucket=bucket" -backend-config "region=cn-zhangjiakou" -backend-config "key=alicloud" -backend-config "ecs_role_name=myrole"
```
terraform still trying to assume a not exist role. So I got an SDK.error

Then I removed `assume_role` in the backed config and re-run command, it works fine. I guess `-reconfigure` is still overriding config filed in file from cli.

according to https://www.terraform.io/docs/cli/commands/init.html#backend-initialization
>Re-running init with an already-initialized backend will update the working directory to use the new backend settings. Depending on what changed, this may result in interactive prompts to confirm migration of workspace states. The -force-copy option suppresses these prompts and answers "yes" to the migration questions. The -reconfigure option disregards any existing configuration, preventing migration of any existing state.

my understanding is:

- terraform init -backend-config "key=value" means overriding backend config from cli argument 
- terraform init -reconfigure  -backend-config "key=value" means build new backend from cli argument, and disregards the config file and state

**Comment by alisdair** [comment]
I think the issue here is that you are using `-backend-config` for partial configuration, and `-reconfigure` isn't relevant. This merges the backend configuration from your config files with the arguments on the command-line. [From the docs](https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration):

> You do not need to specify every required argument in the backend configuration. Omitting certain arguments may be desirable if some arguments are provided automatically by an automation script running Terraform. When some or all of the arguments are omitted, we call this a _partial configuration_.
>
> If backend settings are provided in multiple locations, the top-level settings are merged such that any command-line options override the settings in the main configuration and then the command-line options are processed in order, with later options overriding values set by earlier options.

The `-reconfigure` flag disregards any existing remote backend state, but not the configuration files. Because the `assume_role` setting is a block, I don't think there's any way to override it from the command-line. I think the workaround you ended up with is in line with our documentation.

I hope this explanation makes sense! I don't think there's a bug in Terraform here, so I'm going to close the issue.
