### ISSUE TITLE
Allow Data Source to return empty results without failing

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform#27588]
Here is one example where this is needed.

```
data "aws_subnet" "stgAZ1" {
  vpc_id = data.aws_vpc.selected.id

  filter {
   name = "tag:Name"
   values = ["*-${var.stgSubnetSuffix}-AZ1"]
  }
}

data "aws_subnet" "stgAZ2" {
  vpc_id = data.aws_vpc.selected.id

  filter {
   name = "tag:Name"
    values = ["*-${var.stgSubnetSuffix}-AZ2"]
  }
}

data "aws_subnet" "stgAZ3" {
  vpc_id = data.aws_vpc.selected.id

  filter {
   name = "tag:Name"
    values = ["*-${var.stgSubnetSuffix}-AZ3"]
  }
}

resource "aws_db_subnet_group" "rdsSubnetGroup" {
...
  subnet_ids                      = [data.aws_subnet.stgAZ1, data.aws_subnet.stgAZ2, data.aws_subnet.stgAZ3]
```

If only one or two of these subnets exist, TF fails, and so we must have seperate code for non-production and production environments, which is an anti-pattern for my company.

What should be rendered is `[subnet-123456,null,null]` or `[subnet-123456,,]`  if only the AZ1 subnet is discovered.

if we need to add (`not_found = null or "xxx-zzz"  or ""`) or (`allow_not_found = true`) to the block, that would be fine with me.

but "Failure is not an option. (Gene Kranz)"

**Comment by jbardin** [comment]
Hi @DonBower 

The error you're seeing isn't shown here, but I assume it's coming from the AWS provider itself, showing `no matching subnet found`.  While terraform doesn't enforce that data sources return errors when they cannot find a single resource, it would not be advised because in most configurations evaluating to `null` when there should be a value would be incorrect.

If there is enough of a use case, the AWS provider could create a data source that filters for multiple subnets, and in fact there is an [`aws_subnet_ids`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet_ids) which may suit your need.  

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

thanks!
