### ISSUE TITLE
Data Life Cycle Policy

### ISSUE THREAD

**Issue by dirnikk** [hashicorp/terraform#27595]
Hello guys,

I have a question regarding Life Cycle policy. Currently the only supported Resource type is VOLUME. Do you plan to add INSTANCE Resource Type in future? 

resource "aws_dlm_lifecycle_policy" "example" {
  description        = "example DLM lifecycle policy"
  execution_role_arn = aws_iam_role.dlm_lifecycle_role.arn
  state              = "ENABLED"

  policy_details {
    **resource_types = ["VOLUME"]**

resource_types - (Required) A list of resource types that should be targeted by the lifecycle policy. VOLUME is currently the only allowed value.

BR
Thank you

**Comment by jbardin** [comment]
Hi @dirnikk,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. AWS specific questions can be asked in the [AWS Provider category](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), and issues with the provider can be filed directly in their [GitHub project issue tracker](https://github.com/hashicorp/terraform-provider-aws/issues).

Thanks!
