### ISSUE TITLE
in jsonencode output, the `"` should not be is escaped. 

### ISSUE THREAD

**Issue by pierrchen** [hashicorp/terraform#27603]
Hi,

I'm not sure if this is a bug or it is my lack of knowledge of the json format. But here is what I see and what I expected. 

## What I see
```
terraform console
> jsonencode({"hello"="world"})
"{\"hello\":\"world\"}"
```
## what I expected
the `"` should not be escaped, and I expect the output to be:
```
{"hello":"world"}
```
So when this string is write to a file (e.g something like `terraform output json > helle.json`), say `hello.json` it can be used 

`jq '.hello' hello.json` will output `world`, instead of throwing an error as it is with the current output.

```
➜  usrdata git:(master) ✗ cat test2.json
{"hello":"world"}
➜  usrdata git:(master) ✗ jq '.hello' test2.json
"world"
➜  usrdata git:(master) ✗ jq '.hello' test2.json
➜  usrdata git:(master) ✗ cat test.json
"{\"hello\":\"world\"}"
➜  usrdata git:(master) ✗ jq '.hello' test.json
jq: error (at test.json:1): Cannot index string with string "hello"
```

**Comment by remilapeyre** [comment]
Hi @pierrchen, the value is a string and not a map so you get the string representation. I think what you are looking for is `terraform output -raw json >hello.json`.

**Comment by jbardin** [comment]
Hi @pierrchen 

@remilapeyre is correct, the output is going to be in the format of a string, which requires escaping the nested quotes. If you want the raw output in 0.14 you need to use the `-raw` flag. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thank!

**Comment by pierrchen** [comment]
Thanks @remilapeyre  and @jbardin !

`-raw` flag works indeed, and I will be using the community forum in the future.
