### ISSUE TITLE
Updating DynamoDB GSIs

### ISSUE THREAD

**Issue by phstc** [hashicorp/terraform#2760]
Hey

Supposing I have a DynamoDB GSI without a `range`:

```
global_secondary_index {
  name = "email_index"
  hash_key = "email"
  projection_type = "ALL"
  write_capacity = 1
  read_capacity = 1
}
```

Then I decide to add a `range`:

```
global_secondary_index {
  name = "email_index"
  hash_key = "email"
  range = "name"  # *** New range ***
  projection_type = "ALL"
  write_capacity = 1
  read_capacity = 1
}
```

Currently I have to remove the original GSI from my_table.tf, apply, wait for the removal then add it back along with the range field, apply again...

I believe it's a kind of a feature request, but would be cool if Terraform were able to figure out that the GSI is changed then auto drop/create to "update" it.

**Comment by apparentlymart** [comment]
Thanks for this request @phstc, and sorry for taking so long to respond to it.

While this does seem like a good enhancement, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.
