### ISSUE TITLE
TF version 0.14.4 terraform plan no longer showing App Services changes after downgrading to TF version 0.13.x

### ISSUE THREAD

**Issue by sagumss** [hashicorp/terraform#27606]
### Terraform Version

0.14.4
```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
Changes and updates over our terraform environment, should be reflected over terraform plan and over azure pipeline

### Actual Behavior

We’ve recently upgraded our pipeline to TF v0.14.4 and there are instances in which our changes over function apps are showing while changes on app services are not reflecting.
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `Push changes to repo`
### Additional Context

Working on terraform to update our app services and function apps on azure environment. We’ve recently upgraded our pipeline to TF v0.14.4 and there are instances in which our changes over function apps are showing while changes on app services are not reflecting. Have you encountered the same issue? We are approaching major terraform upgrade again for v0.15.

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

Additionally, it appears you are specifically referring to an Azure-related provider rather than Terraform Core, so I suggest checking in those areas.
