### ISSUE TITLE
Blocked between upgrade from terraform version 0.13 and 0.14

### ISSUE THREAD

**Issue by cmaric** [hashicorp/terraform#27615]
Hi 

We are upgrading all our terraform/azure project from terraform version 0.12 to 0.13 and then to 0.14.
terraform init and apply was by mistake applied with the terraform version 0.14 before upgrading with version 0.13.
The terraform 0.14 is no complaining to run the upgrade with terraform 0.13. 
Running terraform apply with version 0.13 complains whit the Error message:

Error: state snapshot was created by Terraform v0.14.4, which is newer than current v0.13.5; upgrade to Terraform v0.14.4 or greater to work with this state

Any advice how to to remove the snapshot created by Terraform v0.14.4?

### Terraform Version
```
Terraform v0.13.5
Terraform v0.14.4
```

### Actual Behavior
1. terraform -v
Terraform v0.13.5
2. terraform init
3. terraform plan
Error: state snapshot was created by Terraform v0.14.4, which is newer than current v0.13.5; upgrade to Terraform v0.14.4 or greater to work with this state

4.  terraform -v
Terraform v0.14.4
5. terraform init
Initializing modules...

Initializing the backend...

Error: Invalid legacy provider address

This configuration or its associated state refers to the unqualified provider
"azurerm".

You must complete the Terraform 0.13 upgrade process before upgrading to later
versions.

**Comment by apparentlymart** [comment]
Hi @cmaric,

It seems like you ran a command with Terraform v0.14 that made only a partial modification to the state, and so it left behind some legacy syntax that the v0.13 upgrade process would normally have fixed. Consequently, you now have an unexpected situation of a snapshot that was most recently updated by Terraform v0.14 but that still contains some historical content that was originally created by Terraform v0.12.

I think to fix this will require you to manually perform some of the steps that the Terraform v0.13 upgrade process would normally have done automatically. I can give you a starting point here although if you have follow-up questions I'll ask you to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), because that's a better place for general discussion and help; we use GitHub only to track work related to changing the code in this repository.

To start with debugging this, try running `terraform providers` to see a list of which providers your current configuration seems to depend on. This will include any providers that your latest state snapshot refers to, and I expect you'll see at least one using the special "legacy" syntax that the Terraform v0.13 upgrade process deals with, where the organization part of the provider address is replaced by `-`. For example, it might say `-/aws` instead of `hashicorp/aws`.

Once you've identified the unqualified providers, you can use [the `terraform state replace-provider` command](https://www.terraform.io/docs/cli/commands/state/replace-provider.html) to replace it with the appropriate fully-qualified provider address, which is what the Terraform v0.13 upgrade process would've done automatically. For example, if it were `-/aws` as I showed in my example above:

```
terraform state replace-provider registry.terraform.io/-/aws registry.terraform.io/hashicorp/aws
```

Not all of the providers that were available for Terraform v0.12 and earlier now belong to this "hashicorp" namespace, so if you see some other provider you can refer to [the providers in the Terraform Registry](https://registry.terraform.io/browse/providers) to see which organization namespace each one belongs to. The easiest way to see it is to look in the URL of the detail page for the provider to see which organization is listed. Using the AWS provider again as an example, its URL is the following:

```
https://registry.terraform.io/providers/hashicorp/aws/latest
```

The `hashicorp` part of this URL is the organization name. Other providers may show a different name there, in which case you'll need to use that name instead when you run `terraform state replace-provider`.

If you run into any problems while working on this, please do start a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where I'll be happy to work through some more debugging steps with you. If you do open a topic, it would help if you share the output from `terraform providers` so we can see what the situation is.

Thanks!
