### ISSUE TITLE
filebase64sha256 returns wrong values

### ISSUE THREAD

**Issue by shaftoe** [hashicorp/terraform#27629]
### Terraform Version

```
Terraform v0.14.5
```

### Terraform Configuration Files

```terraform
output "filebase64sha256" { value = filebase64sha256("test.zip") }
```

### Expected Behavior

I expect the same hashed values both from `filebase64sha256()` and from popular CLI tools, e.g. on macOS:

```sh
shasum -a 256 test.zip | cut -d ' ' -f 1 | base64
# NTIyZDhhYTU4OWQ4MmM4NDA0OTNmODJjYjcwODgzMTdkNmEyYjAyYjZhY2NmMjkyYWY1OTdkMmYxMDNhZGNlMgo=

terraform output -raw filebase64sha256
# Ui2KpYnYLIQEk/gstwiDF9aisCtqzPKSr1l9LxA63OI=
```

### Actual Behavior

Computed hashes differ (with `filebase64sha256()` one being suspiciously short).

### Steps to Reproduce

```bash
#!/usr/bin/env bash
set -Eeuxo pipefail
echo "test Terraform filebase64sha256()" > test.txt

zip test.zip test.txt
#  adding: test.txt (stored 0%)

shasum -a 256 test.zip
# 5a11f22bc3818dd7ff412bc66c98ee5da476765fa6fe22c10ae8f8c6c9aed2f4  test.zip

echo -n '5a11f22bc3818dd7ff412bc66c98ee5da476765fa6fe22c10ae8f8c6c9aed2f4' | base64
# NWExMWYyMmJjMzgxOGRkN2ZmNDEyYmM2NmM5OGVlNWRhNDc2NzY1ZmE2ZmUyMmMxMGFlOGY4YzZjOWFlZDJmNA==

echo 'output "filebase64sha256" { value = filebase64sha256("test.zip") }' > main.tf

terraform version
# Terraform v0.14.5

terraform init
# Initializing the backend...
#
# Initializing provider plugins...
#
# Terraform has been successfully initialized!
#
# You may now begin working with Terraform. Try running "terraform plan" to see
# any changes that are required for your infrastructure. All Terraform commands
# should now work.
#
# If you ever set or change modules or backend configuration for Terraform,
# rerun this command to reinitialize your working directory. If you forget, other
# commands will detect it and remind you to do so if necessary.

terraform apply -auto-approve
# Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
#
# Outputs:
#
# filebase64sha256 = "WhHyK8OBjdf/QSvGbJjuXaR2dl+m/iLBCuj4xsmu0vQ="
```

### Additional Context

My use case: I don't want to commit Lambda zip archives to my TF Git repository, I just want to provide a value to `aws_lambda_function` [`source_code_hash`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#source_code_hash) that's stored on the local filesystem without the need to read that from the source (S3 object) archive at runtime.

**Comment by jbardin** [comment]
Hi @shaftoe 

The command you are using to check the base64 encoded output is incorrect. You are base64 encoding the hexadecimal representation of the hash, while the function itself is returning a base64 encoding of the hash value itself. The base64 encoding is expected to be shorter, because base64 is a higher density encoding using 64 different characters as opposed to 16 for hexidecimal.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by shaftoe** [comment]
@jbardin all right, I'll ask in the forum then, sorry for the noise ✌️
