### ISSUE TITLE
Being able to pass two providers with different alias to child modules

### ISSUE THREAD

**Issue by Ikeajoel** [hashicorp/terraform#27625]
If I have two Providers like this:

provider "google" {
  project = var.project_id
  region = "europe-west1"
  alias = "ex1"
}

provider "google" {
  project = var.project_id
  region = "europe-west3"
  alias = "ex2"
}

I would like to able to pass both those providers to a child module somehow.

module "example_module" {
providers = {
    google = google.ex1
    google = googleex2
  }
}

**Comment by jbardin** [comment]
Hi @Ikeajoel 

What your configuration is trying to do is set to different provider configurations to the same provider in the module, which isn't going to do what you want. The module must have multiple aliases to receive the 2 configurations, see [Providers Within Modules](https://www.terraform.io/docs/language/modules/develop/providers.html) in the documentation.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
