### ISSUE TITLE
Error when reading or editing Subscription: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token

### ISSUE THREAD

**Issue by Ikeajoel** [hashicorp/terraform#27659]
Hi! When we upgraded our terraform infrastructure from 0.12.25 to 0.13.0 this bug above was introduced. 

"Error when reading or editing Subscription: googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token"

Any idea what can be the problem?

The provider we are using is google.

**Comment by jbardin** [comment]
Hi @Ikeajoel 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help (and maybe the [Google Provider category](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) specifically). If there is an issue with the provider, you can file it in their [project repository](https://github.com/hashicorp/terraform-provider-google).

Thanks!
