### ISSUE TITLE
error when targeting module resources

### ISSUE THREAD

**Issue by bluecodefish** [hashicorp/terraform#27660]
### Terraform Version

```
0.12.29, 0.13.6, 0.14.5
```

### Terraform Configuration Files

```terraform
path.root/modules/xxx/

resource "google_bigquery_table" "external_tables" {
  for_each   = local.tables_map
  dataset_id = var.datasets[each.value.dataset].dataset_id
  table_id   = each.value.tablename

  labels = {
    env        = var.env,
    created_by = "terraform",
    zone       = each.value.zone
  }
}
```

### Expected Behavior

terraform destroy -var-file="yyy.tfvars" -target=module.bq_table_creation.google_bigquery_table.external_tables["xxxx"]

should destroy the google_bigquery_table "xxxx"

### Actual Behavior

the command is not executed. "Usage" gets printed. No error messages.

### Additional Context

it is working when the targeted resources reside in the root module.
cannot target any other "nested" module ressources
targeting "module.bq_table_creation.google_bigquery_table.external_tables" will work but will destroy all tables

**Comment by jbardin** [comment]
Hi @bluecodefish 

If the command you are using is entered exactly as shown here, it seems you are not escaping the target string, which means the double quotes are going to be interpreted by the shell, and possibly the square brackets as well. You can see the exact arguments given to terraform in the trace log output. If this is not the case, feel free to reply with more information, but I'm going to close this for now as it does not appear to be a bug in terraform itself.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
