### ISSUE TITLE
Creation of empty aws security group and adding rules destroys and recreates on every run

### ISSUE THREAD

**Issue by kraduk** [hashicorp/terraform#27674]
### Terraform Version

```
$ terraform version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform
resource "aws_security_group" "test" {
  name        = "test"
  description = "test"
  vpc_id      = module.vpc.vpc_id
  ingress = []
  egress = []
}

resource "aws_security_group_rule" "test" {
  description              = "Test"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 0
  protocol                 = "all"
  cidr_blocks = var.allowed_ipv4
  ipv6_cidr_blocks         = var.allowed_ipv6
  security_group_id = aws_security_group.test.id
}
```

### Debug Output

NA
### Crash Output

NA
### Expected Behavior

The security group and rule created on the 1st run.
Any subsequent runs should not create or destroy any rules unless added to the config

### Actual Behavior

The ingress rule is destroyed and recreated on every run after the initial. 

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`
3. `terraform apply`
4. etc

### Additional Context

I am trying to avoid the situation where someone has added a rule manually to the security group outside of terraforms control. Specifying the empty set and then the rules I was hoping the data would be merged to create strictly defined security group. Is this expected behaviour or is there another way to ensure there isnt say another ssh rule to host x in the SG?

**Comment by jbardin** [comment]
Hi @kraduk 

If you want to avoid the configuration from overriding external changes, the meta-parameter you are likely looking for is [`ignore_changes`](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes) in the `lifecycle` block. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
