### ISSUE TITLE
Add tofloat function and float type

### ISSUE THREAD

**Issue by tomcart90** [hashicorp/terraform#27677]
### Current Terraform Version

```
13.3
```

### Use-cases

I have a terraform module which produces a json document that gets stored in an AWS Parameter Store parameter. The contents of the document is populated by a number of variables passed to the module. Several of those values need to be represented as floats, however, if one of these values ends in .0 the decimal point and any preceding zeros are chopped off. This then becomes a problem when the consumer of that json document expects float values.

### Proposal

Ideally I'd like for terraform to respect a float number, even if it only contains zeros after the decimal place. However, I assume this would likely be a breaking change for a number of terraform users. Instead it would be great if there were someway to ensure a number maintained its decimal place via some mechanism such as a `tofloat()` function. Which would essentially convert the value into a new type, much like number though the decimal place could not be dropped without calling `toint()` on it.

**Comment by jbardin** [comment]
Hi @tomcart90,

Thanks for filing the issue. The numbers in terraform are stored as arbitrary-precision floating point values. The fact that the encoded value does not display unnecessary decimals is due to the encoding library used by terraform. Because javascript only has a double-precision float numeric type, most json libraries automatically assume any number as a float regardless of the presence of a decimal point. Regardless of how it is formatted, the json spec itself does not use the format to attribute any type, and it's up to the decoder to interpret the value correctly. That's not to say the consumer of your json isn't free to try and interpret it however they please, just to explain why the encoder wouldn't differentiate the values.

Since this is a fundamental property of the encoding library we use, and it matches the standard reference encoding for the Go language, it's not something we are likely going to change within Terraform itself. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. There may be more users there with similar experiences and with workarounds for handling json in aws services. 

Thanks!
