### ISSUE TITLE
Terraform v14+ does not escape double quotes properly on 'output'

### ISSUE THREAD

**Issue by marcosdiez** [hashicorp/terraform#27688]
original terraform file:

```
output "blah" {
    value = "the book is on the \"table\". "
}
``` 

output from terraform < 14:
```
mdiez@batman:/tmp/p$ ./terraform1306 apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

blah = the book is on the "table".
mdiez@batman:/tmp/p$
```

output from terraform > 14 ( including terraform 14.06):
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

blah = "the book is on the \"table\". "
```

As you can see, until Terraform 13, quotes were not escaped on the `output` and now it is.

**Comment by jbardin** [comment]
Hi @marcosdiez 

Yes, this was an intentional change. See #27332, #27007, and #26831.
For machine parsable output, there is the `-json` flag, and more recently the `-raw` flag was added to get 0.13-like behavior.

Thanks!

**Comment by marcosdiez** [comment]
Hey @jbardin 
I am trying to understand why the behavior was changed.
From the number of issues opened on this topic, clearly people are not very happy with it.

the -json parameter makes sense

I am trying to understand to whom the new output that escapes quotes is useful for.

the -raw, on the other hand, is just awful. mainly because I have to saw which parameter I want with unescaped quotes. I need all of them :(

**Comment by jbardin** [comment]
The quotes are only escaped because they are contained within double quotes themselves, otherwise the output syntax would not be valid in any context. Correct quoting is required to disambiguate more complicated output, like nested quotes or multiple lines. Not properly quoting the output also means that complex types containing strings cannot be output in a consistent, readable fashion, since strings need to somehow be separated from the other syntax. 

Displaying correct syntax fixes many issues, and because the output was not meant to be machine parseable, it was not marked as a breaking change in 0.14. The `-raw` flag was added to specifically define and limit what can be printed as a raw string, and allow customers with complex workflows time to transition to a more stable output. 

Thanks!

**Comment by marcosdiez** [comment]
Well, I am not sure how to migrate to this more "stable" output.


for example, I create now a set of servers with terraform. Also, I created the jumpbox to access these servers.

Then I want to output the SSH command to access these servers.

It happens to be this:


```
ssh_1 = "ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' -o ProxyCommand="ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' ubuntu@JUMPBOX_NAME -i ~/.ssh/THE_KEY nc THE_SERVER_A 22" -i ~/.ssh/THE_KEY_A ubuntu@THE_SERVER_A ;"

ssh_2 = "ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' -o ProxyCommand="ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' ubuntu@JUMPBOX_NAME -i ~/.ssh/THE_KEY nc THE_SERVER_B 22" -i ~/.ssh/THE_KEY_B ubuntu@THE_SERVER_B ;"

ssh_3 = "ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' -o ProxyCommand="ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile=/dev/null' ubuntu@JUMPBOX_NAME -i ~/.ssh/THE_KEY nc THE_SERVER_C 22" -i ~/.ssh/THE_KEY_C ubuntu@THE_SERVER_C ;"


```

There is no way I can change the syntax not to unescape either the quotes or the slashes. Or am I missing something ? Is my use case valid ? Is there a workaround for this new feature ?

Maybe I could add a parameter to "output" saying "format=raw" or something...

**Comment by jbardin** [comment]
Sorry, I'm not sure I understand, adding the `-raw` flag to the `output` command should provide you with the same output you had previously. Because we use GitHub issues for tracking bugs and enhancements, rather than for questions, it would be better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people using terraform in production ready to help with various usage questions. Thanks!

**Comment by marcosdiez** [comment]
the problem is that `-raw` expects an extra parameter with the variable name. So if my output has 10 outputs that are escaped, well, I would have to run terraform 10 times to get the expected output. Anyway, I'll go to the forum. Thank you
