### ISSUE TITLE
EMR terraform complaining for optional parameter (emr_step)

### ISSUE THREAD

**Issue by teotia32** [hashicorp/terraform#27686]
### Terraform Version

```
Terraform v0.12.30
```

### Terraform Configuration Files

```terraform
  dynamic "step" {
    for_each = var.emr_steps
    content {
      action_on_failure = step.value.name
      hadoop_jar_step   = step.value.hadoop_jar_step
      name              = step.value.name
    }
  }
```

### Debug Output
 Error: Incorrect attribute value type

  on .terraform/modules/emr/main.tf line 63, in resource "aws_emr_cluster" "emr":
  63:       hadoop_jar_step   = step.value.hadoop_jar_step

Inappropriate value for attribute "hadoop_jar_step": element 0: attributes
"main_class" and "properties" are required.

### Actual Behavior
 Terrform gave below error while running emr resource with some steps with main_class and proerties populated under hadoop_jar_step.

### Steps to Reproduce

create a resource emr_cluster as per here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_cluster
passed emr_step as below in variable:
emr_steps = [
                  {
                    action_on_failure = "CONTINUE"
                    name = "something"
                    hadoop_jar_step = [
                      {
                        args = [
                          "aws",
                          "s3",
                          "ls",
                        jar = "command-runner.jar"
                      }]
                  },

             ]

**Comment by jbardin** [comment]
Hi @teotia32 

It appears you are having an issue structuring the configuration for a `aws_emr_cluster`. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

As a suggestion, the aws provider appears to expect `step` and `hadoop_jar_step` to be presented as attributes rather than blocks, so you may have more luck structuring them using [for expressions](https://www.terraform.io/docs/language/expressions/for.html). There have been some issue related to blocks like this which have been solved since `v0.12.30` was released, so you may want to try replicating the issue in a newer version.

Since this doesn't appear to be a bug in a current Terraform version, I'm going to close this out for now. Please check out the forums if you have more questions.

Thanks!
