### ISSUE TITLE
Terraform Cloud - sticking variable in private module

### ISSUE THREAD

**Issue by taylorturner** [hashicorp/terraform#27695]
First off, if this isn't the right place for this I'm happy to move it.

I've recently switched to using Terraform Cloud, I "published" 4 modules to the private module registry within Terraform Cloud.

In one of those modules, I had an undefined variable `dockerconfig_filename` (making it required) that was in version 2.0.0 of the module. I've since replaced that variable with another and pushed a new version 2.0.1 of this module. 

When viewing the module in the Terraform Cloud console, it correctly shows the newly added variable but the old one hasn't been removed. The count of input variables went from 22 to 23 from version 2.0.0 to 2.0.1, when it should've stayed the same.

Compounding the problem, now every workspace using that module is complaining that the `dockerconfig_filename` variable is undefined. To get around this, I've switched the source for all my modules to point at Github for now.

**Comment by mildwonkey** [comment]
Hi,  @taylorturner . Thanks for reporting this.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at tf-cloud-support@hashicorp.com. If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!

**Comment by mildwonkey** [comment]
@taylorturner ,
 A little birdie suggested I also point you to our cloud forum, which is also a good place to ask for help: https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44

**Comment by taylorturner** [comment]
Thank you @mildwonkey!!
