### ISSUE TITLE
ECS fargate service, blue green option is not working 

### ISSUE THREAD

**Issue by sreenivasnarayan** [hashicorp/terraform#27704]
When I am running the below code, the ecs service is not getting created with deployment_controller code deploy. 

`resource "aws_ecs_service" "app" {
  name = "app"
  cluster = "app"
  launch_type = "FARGATE"
  platform_version = "1.4.0"
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = 3
  deployment_minimum_healthy_percent = 50
  deployment_maximum_percent         = 200
  scheduling_strategy                = "REPLICA"

#  task_role_arn            = "${var.ecs_task_role}"
 # execution_role_arn       = "${var.ecs_task_execution_role}"

  network_configuration {
    subnets = var.public_subnets
    assign_public_ip = true
    security_groups = var.app_security_groups

  }

  deployment_controller {
    type = "CODE_DEPLOY"
  }

 load_balancer { 
   target_group_arn = aws_alb_target_group.app1.arn
   container_name   = "app"
   container_port   = 8080
 }`

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
