### ISSUE TITLE
Building (or using as a library) the v0.14 tag

### ISSUE THREAD

**Issue by yitsushi** [hashicorp/terraform#27707]
### Terraform Version

`v0.14` tag.

### Terraform Configuration Files

Not applicable.

### Debug Output

```
terraform on  v0.14 via  v1.15.7 [] on   (us-east-1)
❯ git remote -v
origin  git@github.com:hashicorp/terraform (fetch)
origin  git@github.com:hashicorp/terraform (push)

terraform on  v0.14 via  v1.15.7 [] on   (us-east-1)
❯ git status --porcelain

terraform on  v0.14 via  v1.15.7 [] on   (us-east-1)
❯ go get ./...
verifying github.com/hashicorp/go-getter@v1.5.1: checksum mismatch
        downloaded: h1:LZ49OxqBBtdKJymlpX7oTyqGBQRg4xxQDyPW4hzoZqM=
        go.sum:     h1:lM9sM02nvEApQGFgkXxWbhfqtyN+AyhQmi+MaMdBDOI=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

### Crash Output

Not applicable.

### Expected Behavior

I'm able to build the binary.

### Actual Behavior

I'm not able to build the binary.

### Steps to Reproduce

* clone the repo
* checkout v0.14
* call `go get ./...`

### Additional Context

Usually I use the provided binary, but while I tried to upgrade [terraspec](https://github.com/nhurel/terraspec) to use v0.14 (right now it's using v0.13.5), but a big checksum mismatch error hit my face. I tried to find the problem and at the end I tried to check the hashicorp/terraform repo and its dependencies. That's where I met this issue. I filed [an issue there](https://github.com/nhurel/terraspec/issues/14) too, but I don't think it's something that can be fixed there.

**Comment by jbardin** [comment]
Hi @yitsushi 

Sorry you're having trouble with project. It appears the checksum mismatch is coming from the `github.com/hashicorp/go-getter` module, which has a similar issue reported [here](https://github.com/hashicorp/go-getter/issues/211). 

The terraform project is not meant to be imported as a library. There maybe be issues resolving dependencies with v0.14, which will require some `replace` directives in the go.mod in any project attempting to use the terraform module. I'm not sure however what is triggering the sum mismatches. I'm not able to replicate the issue locally, so you may have stale data somewhere, or need to update to go1.15. 

As terraform is not supported as a library itself, a lot of the unintentionally exported functionality is being removed so that we can more easily refactor it internally. As a work of caution, the next release is likely not going to work for this purpose any longer at all. Due to this not being a supported use case, I'm going to close out the issue here. There is always [the community forum](https://discuss.hashicorp.com/c/terraform-core) for discussion about the use and development of terraform.

Thanks!
