### ISSUE TITLE
Azure Provider Storage Account Creation Failed  due region name 

### ISSUE THREAD

**Issue by jcperezamin** [hashicorp/terraform#27705]
Error: Error creating Azure Storage Account "jcpvi1uatorabkp": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="LocationNotValid" Message="Supplied location australiasoutheast is not valid."
  on 0.ResourceGroup-STG.tf line 46, in resource "azurerm_storage_account"

Region Provided:  australiasoutheast and  australia southeast

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
