### ISSUE TITLE
Providers that have been moved out of hashicorp namespace cannot be passed to modules

### ISSUE THREAD

**Issue by anuraaga** [hashicorp/terraform#27718]
### Terraform Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/github v4.4.0
+ provider registry.terraform.io/integrations/github v4.3.2
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "us-west-2"
}

provider "aws" {
  alias = "aoc_integtest"
  region = "us-west-2"
  assume_role {
    duration_seconds = 900
    role_arn = "role_of_another_account"
  }
}

provider "github" {
  organization = "aws-observability"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
    github = {
      source = "integrations/github"
      version = "~> 4.0"
    }
  }
}

module "aws-otel-java-instrumentation" {
  source = "./modules/github-repo"

  name = "aws-otel-java-instrumentation"
  description = "AWS Distro for OpenTelemetry Java Instrumentation Library"
  topics = [
    "opensource",
    "observability",
    "opentelemetry",
    "opentelemetry-api"
  ]

  providers = {
    aws = aws
    aws.aoc_integtest = aws.aoc_integtest
    github = github
  }
}
```

### Debug Output

https://gist.github.com/anuraaga/150da3ca987ec157299e75d1f710616f

### Expected Behavior

Terraform plan succeeds

### Actual Behavior

Plan fails with `Error: missing provider provider["registry.terraform.io/hashicorp/github"]`

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### Additional Context

If I change `integrations/github` to `hashicorp/github` in `required_providers`, then it works, but then there is a warning about the deprecated usage. 

```
Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/hashicorp/github:
- For users on Terraform 0.13 or greater, this provider has moved to
integrations/github. Please update your source in required_providers.
```

**Comment by jbardin** [comment]
Hi @anuraaga 

Sorry you're having trouble here, it seems you have a module or state referencing the incorrect provider. Modules must all declare which providers they require, see the documentation for [Provider Requirements](https://www.terraform.io/docs/language/providers/requirements.html). See also the [0.13 Upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html) for documentation on changing existing provider references within the state.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
