### ISSUE TITLE
depends_on working with complex indices like count.index

### ISSUE THREAD

**Issue by happyfeet23** [hashicorp/terraform#27719]
### Current Terraform Version
```
Terraform v0.12.24
...
```

### Use-cases
We have a requirement to create nested folder structure in Azure Datalake Gen2 Storage account and assign different AD groups permissions on each folder level. The number of levels in folder structure is not fixed. that would be a list of undefined length.

### Attempted Solutions

resource "azuread_group" "read_zone" {
  count                   = length(local.patharray)
  display_name       = join("-", flatten([[var.group_prefix], slice(local.patharray, 0, count.index + 1), ["R"]]))
  description           = "Recursive read access for Data Lake ${join("", flatten([slice(local.patharray, 0, count.index)]))}"
  prevent_duplicate_names = false
  //depends_on          = [azurerm_storage_data_lake_gen2_path.internal[count.index]]
}
resource "azurerm_storage_data_lake_gen2_path" "internal" {
  count                     = length(local.patharray)
  path                       = join("/", slice(local.patharray, 0, count.index))
  filesystem_name    = var.filesystem_name
  storage_account_id = var.storage_account_id
  resource                 = "directory"
  ace {
    id          = azuread_group.read_zone[count.index].id
    permissions = "r-x"
    type        = "group"
    scope       = "default"
  }
//depends_on          = [azurerm_storage_data_lake_gen2_path.internal[count.index - 1]]
}

The problem with this approach is that it creates the inner folders first, then tries to create the outer folders and errors out saying the outer folders exist. eg: ["123","456","789"] is creating 123/456/789 first, then trying to create 123 folder and failing.

This loop structure is needed because we want the read permissions to AD groups as below:
123 -               ADGroup-123-Read
123/456 -       ADGroup-123-456-Read
123/456/789 - ADGroup-123-456-789-Read

### Proposal

if depends_on can work with count.index, then that can be used in either of the commented blocks above to force terraform to create folders from upper level to inner directories level in the order of list. or create a dependency between group creation and folder creation thus bringing order to the resource allocation.  

### References

- #7118 that was closed since that feature could not be implemented. Please help if there is an alternative that works.

**Comment by jbardin** [comment]
Hi @happyfeet23 

`depends_on` create dependencies between entire resources (which are analogous to the resource block in the configuration), not individual instances of those resources. Having a resource refer to itself would create a dependency cycle which cannot be resolved. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. There are likely others with similar requirements, and may have various workarounds, including generating the desired configuration with other tools.

Thanks

**Comment by vpegg** [comment]
@jbardin - I think we can raise this as a bug. When I have used this for example as below:

`# splitting path into list i.e. abc/123/456 into ["abc","123","456"]
locals {
  path1     = replace(var.path, "\\", "/")
  path2     = replace(local.path1, "/+", "/")
  path3     = trim(local.path2, " ")
  path4     = trim(local.path3, "/")
  path5     = replace(local.path4, " ", "_")
  patharray = split("/", local.path5)
}

## Each part of the path has different AD groups with different permissions. 
resource "azurerm_storage_data_lake_gen2_path" "zone" {
  count              = length(local.patharray) 
  path               = join("/", slice(local.patharray, 0, count.index + 1))
  filesystem_name    = azurerm_storage_data_lake_gen2_filesystem.datalake.name
  storage_account_id = azurerm_storage_account.datalake.id
  resource           = "directory"
  ace {
    # no id => owning user (i.e. deployment account)
    permissions = "rwx"
    scope       = "access"
    type        = "user"
  }
  ace {
    permissions = "---"
    scope       = "access"
    type        = "group"
  }
  ace {
    id          = azuread_group.write_zone[count.index].id
    permissions = "rwx"
    type        = "group"
    scope       = "access"
  }
  ace {
    id          = azuread_group.directory[count.index].id
    permissions = "r-x"
    type        = "group"
    scope       = "access"
  }
  ace {
    id          = azuread_group.read_zone[count.index].id
    permissions = "r-x"
    type        = "group"
    scope       = "access"
  }
  ace {
    permissions = "rwx"
    type        = "mask"
    scope       = "access"
  }
  ace {
    permissions = "---"
    scope       = "access"
    type        = "other"
  }
  ace {
    permissions = "---"
    scope       = "default"
    type        = "user"
  }
  ace {
    permissions = "---"
    scope       = "default"
    type        = "group"
  }
  ace {
    id          = azuread_group.write_zone[count.index].id
    permissions = "rwx"
    type        = "group"
    scope       = "default"
  }
  ace {
    id          = azuread_group.read_zone[count.index].id
    permissions = "r-x"
    type        = "group"
    scope       = "default"
  }
  ace {
    permissions = "rwx"
    scope       = "default"
    type        = "mask"
  }
  ace {
    permissions = "---"
    scope       = "default"
    type        = "other"
  }
}

`

As terraform runs in parallel, if azurerm_storage_data_lake_gen2_path.zone[2] is run/completed first, terraform errors when attempting to create count.index[0] or [1] as the path has already been created. It asks for us to do terraform import, because the path already exists. 

What we wish to do is to update the different parts of the path i.e. abc, abc/123, abc/123/456.

**Comment by jbardin** [comment]
@vpegg Terraform is working as designed here, so this would not be classified as a bug itself. It would probably be beneficial to work out the details of a general use case in the discussion forum, and if there is a pattern which could fit into the architecture of Terraform, then an enhancement proposal could be filed.
