### ISSUE TITLE
panic: cannot determine user directories on OS "openbsd"

### ISSUE THREAD

**Issue by jxlambda** [hashicorp/terraform#27726]
Hi,

I'm invoking terraform on an OpenBSD 6.8 (-stable) system, built via the ports infrastructure. As far as I understand, OpenBSD isn't on the list of supported platforms (the port is from the ports contributors), but there doesn't appear to be much in the way of it terraform actually running on it, so I thought I'd give it a shot; it builds, after all.

When invoking, however, it panics with the message in the title and produces the attached crash.log. From the log, I infer that it's trying to figure out some default directories and doesn't have sane defaults for openbsd, or a way to find them. Seems trivial enough.

I was wondering if I could somehow fix this (albeit, with some hand holding), and contribute back a patch?

### Terraform Version
The crash occurs before terraform can print its own version information. The log says 0.13.3, which is admittedly a bit stale. 

### Terraform Configuration Files
No configuration files.

### Crash Output

https://gist.github.com/jxlambda/f95c914019dfbb1a7b6dc560299fb993

### Expected Behavior
Directories should be either determined using an equivalent mechanism as on other unix-like platforms.
 
### Actual Behavior
Panics.

### Steps to Reproduce
0-9. Build terraform from openbsd ports
10. Install it
11. Invoke it with an optional subcommand

**Comment by apparentlymart** [comment]
Hi @jxlambda,

This error message is coming from an upstream library that I happen to be the author of: [github.com/apparentlymart/go-userdirs](https://github.com/apparentlymart/go-userdirs).

However, that library does at least _attempt_ to treat OpenBSD the same as various other Unixes, via [the build tags in `app_unix.go`](https://github.com/apparentlymart/go-userdirs/blob/b0c018a67c137d9ec0877a9e07878a6bf5b51564/userdirs/app_unix.go#L1), and so I'm not sure how this is ending up in [the "not supported" fallback function](https://github.com/apparentlymart/go-userdirs/blob/b0c018a67c137d9ec0877a9e07878a6bf5b51564/userdirs/app_stub.go#L19). It seems like something unusual has happened with the Go toolchain you used to build, where the compiler didn't consider itself to be targeting `openbsd` but yet at _runtime_ somehow the Go runtime's `GOOS` value is set to `openbsd` as expected.

If you'd be willing to debug and figure out why that is then I'd be happy to consider a PR in the upstream repository, which could then potentially make this work for Terraform if the Terraform team chooses to upgrade to the new version. With my "Terraform developer" hat on I'm going to close this because as you noted OpenBSD is at the "best effort" level of support as far as the Terraform team is concerned, but with my "maintainer of that upstream library" hat on I'd be willing to discuss this and review a PR upstream if you're interested. (I don't have any OpenBSD systems to test/debug on, so unfortunately I'd need to rely on you to dig in and try to figure out what's going on.)

The Terraform CLI release process _does_ produce some OpenBSD binaries using cross-compilation (again, on a "best effort" sort of basis), so it might be interesting to give those builds a try and see if you get different results than with your build using OpenBSD ports.

https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_openbsd_amd64.zip
https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_openbsd_386.zip
