### ISSUE TITLE
Enable ways to generate code coverage for terraform modules (and test with terratest)

### ISSUE THREAD

**Issue by ghostsquad** [hashicorp/terraform#27725]
### Use-cases
HCL is growing into a fully-fledged language, and has robust expression, conditions, loops, and you name it. Things start getting complicated, and it would be great to write automated tests for terraform modules.

[Terratest](https://github.com/gruntwork-io/terratest) is a great resource for writing terraform tests, but it's hard to know if your tests are covering all the little bits & branches of your module.

### Attempted Solutions
N/A

### Proposal
> There are many approaches to code coverage measurement. Broadly there are three approaches, which may be used in combination:

> Source code instrumentation
This approach adds instrumentation statements to the source code and compiles the code with the normal compile tool chain to produce an instrumented assembly.

> Intermediate code instrumentation
Here the compiled class files are instrumented by adding new bytecodes, and a new instrumented class is generated.

> Runtime information collection
This approach collects information from the runtime environment as the code executes to determine coverage information.

I've never written a code coverage tool before, and I see HCL as unfortunately very limiting as to what can be injected. So likely there needs to be another component closer to the evaluation process of HCL in order to provide instrumentation.

### References
https://confluence.atlassian.com/clover/about-code-coverage-71599496.html

**Comment by DanielMarquard** [comment]
@jamesnyika Is there any way you could give this a signal boost from your side? We need this to deepen Terraform's integration with GitLab.

See also: https://github.com/gruntwork-io/terratest/issues/556

**Comment by apparentlymart** [comment]
Hi @ghostsquad! Thanks for sharing this use-case.

By coincidence, I'm currently working on a new round of research about testing for Terraform modules, although we're currently at an earlier phase of that research than considering details like code coverage: our current aim is to continue the experiment started by my provider [`apparentlymart/testing`](https://registry.terraform.io/providers/apparentlymart/testing/latest), which aimed to see what sorts of tests might be possible to write in the Terraform language itself, by integrating something like it into Terraform (as an experiment) with a first-class `terraform test` command.

In the long run though, I expect that if we _do_ show that it's practical to write module integration tests within the Terraform language then we'll consider adding first-class language features for it, rather than using a provider to implement it. The provider just serves as a convenient way to try out the workflow with an addition that's confined to only a small part of the codebase.

One of the reasons why I think that having the tests be written using new first-class Terraform language features is indeed that it is the most practical way to make the follow-on tools such as code-coverage work. Code coverage for Terraform is likely to look a bit different than imperative programming languages, because Terraform language code is non-linear. I expect it would be most practical to implement it by adding collection capabilities directly to the language runtime; other techniques such as code instrumentation are only really applicable to general-purpose languages where it's possible to write the data collection logic in the language that's being tested.

With all of that said, I think we're still quite a few steps away from code coverage but I do want to affirm that it's something I'd like to support in the long run, as a later part of a broader effort to integrate testing use-cases into Terraform itself. I'm in the middle of prototyping as I'm writing this, so I don't have anything more to share about it right now but hopefully there'll be an experimental initial attempt at this in a near-future Terraform release.

**Comment by jamesnyika** [comment]
@DanielMarquard - thanks for the new request and point well taken! Will reach out to see if I can support it.

**Comment by 0rc** [comment]
any developments on this matter?

**Comment by yas51ne** [comment]
+1

**Comment by vladdoster** [comment]
+1

**Comment by ghostsquad** [comment]
I'm moving on to Pulumi at this time. I'm closing this issue as I no long wish to be mentioned or owner of this problem statement. If someone else is still in need of this functionality in Terraform, please open a new issue.
