### ISSUE TITLE
Add the ability to put variables in a module source

### ISSUE THREAD

**Issue by mrj1m0thy** [hashicorp/terraform#27724]
I'm aware that there is an existing issue for this:
https://github.com/hashicorp/terraform/issues/1439

However, this was closed and pushed under the rug for some unknown reason. I'd like to reopen this issue and bring it to light because I just came across an annoying situation that this causes.

I have 2 terraform modules that are in separate projects in GitLab that we are versioning using tags for backwards compatibility purposes depending on our deployment process. One module is to launch windows servers and another is centos servers. I have a third module that references the first 2 modules to create a set of servers in a specific format as required by my employer. This third module uses the "ref" in the source to target the tags of the first 2 modules and may change depending on what kind of environment is being launched. The problem this introduces is that every time a new update is made to the first 2 modules, I have to also create a new commit and merge request in the third module just to update the tags every time instead of having an input variable for the third module to select the tag the person wishes to deploy with and defaulting to "master". 

I don't know why this issue was closed with the vast quantity of people who made comments and explained the pains they faced. Please consider reopening this or at least provide a workaround that isn't:
1. Wrapping our terraform with our own scripts to jinja template a language that "supports" jinja
2. Adding an additional file "override.tf" to override our modules source

**Comment by apparentlymart** [comment]
Hi @mrj1m0thy,

It's a typical design decision in most language ecosystems that dependencies between libraries/modules are a static concern handled prior to runtime -- often by a separate command whose entire job is to install dependencies -- rather than something that happens dynamically at runtime.

The same is true for Terraform: the `terraform init` command needs to go and fetch all of the dependencies before the main Terraform language runtime is able to run, because until the modules have been installed the Terraform "program" is not yet complete, and so it cannot execute.

For that reason, there is no practical way to support what you've requested here, even though I agree it would be very convenient in the situation you've described. Instead, you'll need to design your system architecture in a different way so that the version requirements between your modules can be resolved statically.

If you'd like to discuss strategies for doing this then I'd suggest starting a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), which is a better place for open-ended discussion about different techniques in the Terraform language, vs. GitHub issues which we use only to represent actionable work.

If someone were able to make a full, concrete technical proposal that illustrates that I'm wrong about this being impractical to implement then I'd love to discuss that proposal in a new issue, but since _this_ issue is just repeating a previous one without any new information I will unfortunately need to close it.
