### ISSUE TITLE
depends_on shouldn't require static expression

### ISSUE THREAD

**Issue by Carlovo** [hashicorp/terraform#27732]
### Terraform Version

`Terraform v0.13.2`
`aws 3.8.0`
I didn't see any relevant changes between then and the current version, though.

### Terraform Configuration Files

First I tried this:

```terraform
resource "aws_wafv2_web_acl" "example" {
  count = var.production_account ? 1 : 0

  name  = "alb-example"
  scope = "REGIONAL"

  # some more irrelevant config goes here
}

resource "aws_lb" "example" {
  name = "example"

  depends_on = var.production_account ? [aws_wafv2_web_acl.example[0]] : []
  
  # some more irrelevant config goes here
}
```

It errors with:

```
Error: Invalid expression

  on main.tf line 13, in resource "aws_lb" "example":
  13:   depends_on = var.production_account ? [aws_wafv2_web_acl.example[0]] : []

A static list expression is required.
```

But this works perfectly fine:

```terraform
resource "aws_wafv2_web_acl" "example" {
  count = var.production_account ? 1 : 0

  name  = "alb-example"
  scope = "REGIONAL"

  # some more irrelevant config goes here
}

locals {
  timing_depencies = var.production_account ? [aws_wafv2_web_acl.example[0]] : []
}

resource "aws_lb" "example" {
  name = "example"

  depends_on = [local.timing_depencies]
  
  # some more irrelevant config goes here
}
```

### Expected Behavior

Although, I'm happy I found this workaround for now, I would have expected either or neither would have worked. I know I'm pushing the use-case of both `count` and `depends_on` here :stuck_out_tongue: Still, I thought it would be good to point out this inconsistency. I feel both should actually work.

### References

I was trying to find a workaround for [hashicorp/terraform-provider-aws#17527](https://github.com/hashicorp/terraform-provider-aws/issues/17527)

**Comment by jbardin** [comment]
Hi @Carlovo 

I don't think the workaround you have is doing what you think it's doing. 
The `depends_on` meta attribute _must_ use static references, because it is used to build the dependency graph before anything can be evaluated. There are no _conditional_ dependencies, because expressions are only taken into consideration after all dependencies are determined.

The `depends_on` references are only used for creating extra dependency edges, so end result of using the `local.timing_depencies` reference is identical to to using `depends_on = [aws_wafv2_web_acl.example]` directly. 

Since terraform is working as expected here, I'm going to close this out.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. If you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
