### ISSUE TITLE
Provide a built-in guess mimetype function

### ISSUE THREAD

**Issue by alanyee** [hashicorp/terraform#27737]
### Current Terraform Version
```
Terraform v0.14.6
```

### Use-cases
There are objects in Terraform that require mimetype information such as `aws_s3_bucket_object` and `artifactory_file`. Terraform does not infer the mimetype for you nor does it provide a function to guess a mimetype. If no mimetype is given, a default mimetype is chosen regardless of the actual file. This can lead to unexpected behaviors if for instance a html file is treated like binary data.

### Attempted Solutions
I have a python script for creating terraform json files, so I use the built-in [`mimetypes.guess_type`](https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type) to supply the mimetypes I need.

### Proposal
Terraform has a built-in way of guessing a file mimetype.

**Comment by apparentlymart** [comment]
Hi @alanyee! Thanks for sharing this use-case.

I know this isn't exactly what you are asking for, but I just wanted to note that [the `hashicorp/dir/template` module](https://registry.terraform.io/modules/hashicorp/dir/template/latest) achieves a similar goal by matching filename suffixes, in a similar way that static web servers typically do (unless intentionally configured for "mime magic"), and perhaps a strategy like that would approximate what you wanted in the meantime, while we think about the implications of putting a "magic number" table in Terraform.

I think my initial concern here is that magic tables tend to be quite large in order to be comprehensive, and so bundling one inside the `terraform` executable might be too high a cost for folks who don't need this functionality. There's also the fact that type detection is inherently a heuristic sort of thing and having a table built in to Terraform would likely mean it would not be customizable by someone who disagrees with the heuristics.

Neither of those concerns are necessarily show-stoppers for doing this, but a potential path forward here which would mitigate the first concern would be to implement this functionality in a provider containing a data source for doing such a lookup. That provider could then either embed a magic number table inside it (only users who actually depend on the provider would incur that extra cost) or could be designed to read a magic table from an outside file provided by the user and thus address that second concern about tailoring it when you disagree with it.

Certainly a full `data` block is much more intrusive in a configuration than just a function call, but data sources have proven to be a great way to prototype new functionality like this (where it's not clear yet how commonly it'll be needed, or exactly how it should be designed) and if it _does_ end up being used often we will hopefully have a number of examples of how it's being used so we can pick out the main use-cases for a more slender built-in language feature.

**Comment by alanyee** [comment]
I find [the `hashicorp/dir/template` module](https://registry.terraform.io/modules/hashicorp/dir/template/latest) sufficient for what I want. Thank you @apparentlymart!

At the very least, there should be a reference to [the `hashicorp/dir/template` module](https://registry.terraform.io/modules/hashicorp/dir/template/latest) in the documentation for when a provider has a `content_type` but no native way to detect the mimetype.

[OpenStack](https://registry.terraform.io/providers/ftarasenko/openstack/latest/docs/resources/objectstorage_object_v1#detect_content_type) does come with its own way of determining the content type. I am unsure to what extent this feature has cost the provider, but its existence makes for a good point of reference for what can be incorporated. If an exhaustive magic table is costly, it could make sense for the user to supply their own. Speculation: my guess would be that a given user has a only few different mimetypes to consider at a time, so their table might be very small compared to an exhaustive table. It might even make sense to have a small, nonexhaustive table built-in and then allow the user to extend/overwrite the table.

**Comment by crw** [comment]
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!

**Comment by apparentlymart** [comment]
Hi everyone!

Reflecting on this issue some time later, it seems like a good time to close it, because:

- The person who originally requested it was already satisfied with the `hashicorp/dir/template` module's approach of matching filename suffixes.
- As I mentioned in my earlier comment, a full "MIME magic" database tends to be quite large and so would be burdensome to link into all Terraform releases when it would likely be used by only a small subset of Terraform module authors.
- Terraform v1.8 was already released with support for provider plugins to offer their own functions, and using a provider plugin to deliver this functionality means that an included MIME magic database would be retrieved only for those who choose to use the provider, and so this seems like an excellent use-case for provider-contributed functions.
- As suggested above, this hypothetical provider could potentially ship with a relatively-constrained default MIME magic table but allow a user to bring their own MIME magic table if they have specialized needs.

There seems to be a number of different "MIME magic" libraries for Go, so someone building such a provider can hopefully just wrap one of those rather than building the whole thing from scratch.

Thanks for suggesting this!
