### ISSUE TITLE
SchemaConfigModeAttr on block misleads terraform schema to identify blocks as attributes

### ISSUE THREAD

**Issue by boris-tarasov-maersk** [hashicorp/terraform#27745]
Dear Terraform team
I am working on automation tool and I need to programmatically query schema of a terraform provider. Specifically, I am interested in azurerm provider.
I used following command "**terraform providers schema -json**" to populate machine readable schema.
While trying to match the output with documentation presented on the
[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) I have noticed that for many resource inputs are represented as attributes in json file but are in fact blocks in documentation.

I have asked authors of azurerm provider to check if it is something on their side that is creating this mismatch, can you see details here: [https://github.com/terraform-providers/terraform-provider-azurerm/issues/8793](https://github.com/terraform-providers/terraform-provider-azurerm/issues/8793)

Authors sugested that they are using **SchemaConfigModeAttr** on blocks and so they are in no power to fix this issue and recommended to address this to terraform team.

Is there a way to make sure that those blocks annotated with SchemaConfigModeAttr can be correctly exposed in terraform schema? Do you have plans to release a bugfix to generate consistent json? Or there is another way to get machine readable data structure to represent resources in a provider?

FYI, I am building Web based UI so users can compose terrafrom using web drag and drop and if it sounds interesting, I could show you what we have built so far.

Here is another example:

resource azurerm_virtual_network
[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network)

**subnet** is a block according to documentation, but it is shown as attribute in terraform schema:
```json
{
"azurerm_virtual_network": {
"version": 0,
"block": {
"attributes": {
"address_space": {
"type": [
"list",
"string"
],
"description_kind": "plain",
"required": true
},
"bgp_community": {
"type": "string",
"description_kind": "plain",
"optional": true
},
"dns_servers": {
"type": [
"list",
"string"
],
"description_kind": "plain",
"optional": true
},
"guid": {
"type": "string",
"description_kind": "plain",
"computed": true
},
"id": {
"type": "string",
"description_kind": "plain",
"optional": true,
"computed": true
},
"location": {
"type": "string",
"description_kind": "plain",
"required": true
},
"name": {
"type": "string",
"description_kind": "plain",
"required": true
},
"resource_group_name": {
"type": "string",
"description_kind": "plain",
"required": true
},
"subnet": {
"type": [
"set",
[
"object",
{
"address_prefix": "string",
"id": "string",
"name": "string",
"security_group": "string"
}
]
],
"description_kind": "plain",
"optional": true,
"computed": true
},
"tags": {
"type": [
"map",
"string"
],
"description_kind": "plain",
"optional": true
},
"vm_protection_enabled": {
"type": "bool",
"description_kind": "plain",
"optional": true
}
},
"block_types": {
"ddos_protection_plan": {
"nesting_mode": "list",
"block": {
"attributes": {
"enable": {
"type": "bool",
"description_kind": "plain",
"required": true
},
"id": {
"type": "string",
"description_kind": "plain",
"required": true
}
},
"description_kind": "plain"
},
"max_items": 1
},
"timeouts": {
"nesting_mode": "single",
"block": {
"attributes": {
"create": {
"type": "string",
"description_kind": "plain",
"optional": true
},
"delete": {
"type": "string",
"description_kind": "plain",
"optional": true
},
"read": {
"type": "string",
"description_kind": "plain",
"optional": true
},
"update": {
"type": "string",
"description_kind": "plain",
"optional": true
}
},
"description_kind": "plain"
}
}
},
"description_kind": "plain"
}
}
}
```
issue is present in terraform version 12, 13 and 14 (latest builds) and in latest versions of azurerm provider.

**Comment by jbardin** [comment]
Hi @boris-tarasov-maersk,

Providers wanted a method for getting attribute-like behavior from block definition in Terraform. This was not possible in the legacy SDK, because complex types could only be defined through block. In the few cases that attribute assignment is necessary for some operation in the provider, the `SchemaConfigModeAttr` option was added. This tells terraform to treat the object type as an attribute, but for compatibility we still allowed block syntax.

These will be shown as attributes in the schema, because they can be assigned as attribute, and can accept complex expressions as their argument. Because this assignment is possible, and preferred in most cases, the schema must reflect this in order to decode the configuration.

If I understand correctly, the main concern here is that the schema does not match the documentation written for the provider in question?

**Comment by apparentlymart** [comment]
In addition to what @jbardin noted, I just wanted to refer to the docs page [Attributes as Blocks](https://www.terraform.io/docs/language/attr-as-blocks.html), which describes the details of how this mechanism behaves from an end-user perspective.

Since it sounds like you are aiming to build a tool that is in some sense a "user" of Terraform (it will write Terraform language on a user's behalf), hopefully that guidance will be helpful in deciding what your tool ought to generate for those cases. In particular I think you'll be interested in [Arbitrary Expressions with Argument Syntax](https://www.terraform.io/docs/language/attr-as-blocks.html#arbitrary-expressions-with-argument-syntax) which notes that indeed these arguments really are just attributes as far as Terraform is concerned, and so it should work just fine for you to generate them in attribute syntax.

This mechanism is a legacy thing for backward compatibility with provider features written before Terraform v0.12, so we don't intend to change these behaviors. Instead, providers should gradually migrate away from using this legacy behavior over time (which typically happens slowly, due to it being a breaking change), and not make use of it in new designs. Providers should typically link to the documentation page I indicated above as part of the documentation for any attribute that is configured in this way, so users can see how the behavior differs for those specific cases, although I know from answering similar questions in the past that this has not generally been true. Perhaps provider developers would appreciate documentation PRs to add those missing notations where appropriate.

**Comment by boris-tarasov-maersk** [comment]
Dear @apparentlymart and @jbardin 
thank you for such a quick reply. Let me read it through and see if I can use it. 
Again, very much appreciated such a quick response.

**Comment by boris-tarasov-maersk** [comment]
if possible, please keep this thread open for a bit

**Comment by boris-tarasov-maersk** [comment]
so, for considerably basic use case here, do I understand correctly, if block is presented as attribute I could treat is as attributes including generated code in .tf or .tf.json files?

**Comment by boris-tarasov-maersk** [comment]
so, for basic use case here, do I understand correctly, if block is presented as attribute I could treat is as attributes including generated code with attribute structure instead of a block one in .tf or .tf.json files?

**Comment by jbardin** [comment]
@boris-tarasov-maersk, yes that is correct. If a value is defined as an attribute in the schema, it can be assigned as an attribute in the configuration, and the block syntax is not required.

**Comment by jbardin** [comment]
There hasn't been any more activity here, and since there's nothing to be changed within terraform itself I'm going to close the issue for now. @boris-tarasov-maersk, if there's anything else we need to cover here, please feel free to reply and we can re-open the issue.

Thanks!
