### ISSUE TITLE
 TF_IN_AUTOMATION should cause missing variables to be an error

### ISSUE THREAD

**Issue by njlr** [hashicorp/terraform#27744]
If `TF_IN_AUTOMATION` is set, then I think it's fair to assume that no user input is possible. Therefore, if a variable is not given a value, Terraform should exit with an error, rather than wait for input. 

This is a usability improvement because it makes CI/CD jobs fail when they are incorrectly configured, rather than hang indefinitely. 

### Current Terraform Version

```bash
$ terraform version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.23.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Use-cases

Every CI/CD pipeline

**Comment by apparentlymart** [comment]
Hi @njlr! Thanks for raising this concern.

The `TF_IN_AUTOMATION` environment variable is specifically for tailoring Terraform's _output_ so that it makes fewer suggestions to run specific Terraform subcommands directly. That's motivated by the fact that when folks are using automation they typically want to run subsequent operations through that automation too, rather than bypassing the automation.

One of the categories of "automation" covered by that is a wrapper script which users still run from an interactive terminal but which pre-populates certain command line arguments in a systematic way that makes sense for the organization that implemented it. For that reason, we don't overload `TF_IN_AUTOMATION` to _also_ mean disabling interactive input prompts.

However, there is a separate mechanism for telling Terraform that it's running in a non-interactive context: you can set [`TF_INPUT=0`](https://www.terraform.io/docs/cli/config/environment-variables.html#tf_input) (or, if you prefer, `-input=false` on the command line) and that should, if things are working as intended, disable the interactive prompts you're seeing when running `terraform plan` or `terraform apply`.

Can you give that a try and let me know if it gives you the result you needed? Thanks!

**Comment by njlr** [comment]
@apparentlymart That sounds like what I was looking for. Thanks!
