### ISSUE TITLE
Terraform init is not using role_arn in s3 backend

### ISSUE THREAD

**Issue by sblask** [hashicorp/terraform#27754]
### Terraform Version
```
$ terraform --version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.18.0
```

### Terraform Configuration Files
```terraform
terraform {
  backend "s3" {
    bucket         = "bucket"
    key            = "state.tfstate"
    region         = "ap-southeast-2"
    dynamodb_table = "terraform-lock"

    role_arn = "some role"
  }
}

```

### Expected Behavior
`terraform init` should just work without having to delete the terraform folder.

### Actual Behavior
I get the same AccessDenied that I get when not using `role_arn`. In the debug output I see:
```
2021/02/12 14:38:42 [DEBUG] [aws-sdk-go] <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
    <Arn>arn:aws:iam::XXXXXXXXXXXX:user/user-name</Arn>
 
```
After `rm -rf .terraform` and running terraform init it just works. The debug output contains:
```
2021/02/12 15:07:14 [DEBUG] [aws-sdk-go] <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
    <Arn>arn:aws:sts::XXXXXXXXXXXX:assumed-role/role-name</Arn>
 
```

### Steps to Reproduce
1. `terraform init` with a backend that doesn't have a role_arn set, get AccessDenied because the default credentials don't grant permissions other than to assume a role
2. add role_arn that grants permission to read the state file
3. `terraform init`

**Comment by jbardin** [comment]
Hi @sblask 

From the reproduction steps it seems you are storing an incorrect configuration for the backend locally, which need to be overwritten. The option for this is `terraform init -reconfigure`

```
  -reconfigure         Reconfigure the backend, ignoring any saved
                       configuration.
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
