### ISSUE TITLE
Collection function introduce cannot be determined until apply

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/terraform#27753]
### Terraform Version

```
Terraform v0.13.2
```

### Terraform Configuration Files

```terraform
module "iam_role_example" {
  source = "..."

  trusted_role_arns       = local.iam_policy_arns
  trusted_role_services   = []
  role_name               = "myname"
  
  custom_role_policy_arns = compact([
    module.iam_policy1.arn,
    module.iam_policy2.arn,
  ])
}

module "iam_policy1" {
  source = "..."
  ...
}

module "iam_policy2" {
  source = "..."
  ...
}
```

### Expected Behavior

Add module.iam_policy1 and module.iam_policy2 first, Add module.iam_role_example last.

### Actual Behavior

_With_ **concat function**

```
Error: Invalid count argument

  on .../main.tf line xx, in resource "iam_role_policy_attachment" "custom":
     count = var.create_role && length(var.custom_role_policy_arns) > 0 ? length(var.custom_role_policy_arns) : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

Same code _Without_ **concat function**: worked without errors as "Expected Behavior"

**Comment by jbardin** [comment]
Hi @Roxyrob 

Thanks for filing the issue. Without the complete configuration it is not possible to diagnose what may be happening here. You may have success trying the latest version of terraform, since there have been numerous improvements since the 0.13.2 release, in both the 0.13 and 0.14 series. 

If the issue can still be reproduced with the latest release (0.14.6 at the moment), please include a complete, minimal reproducible example demonstrating the issue. If you have questions about how to fix the configuration, while we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by apparentlymart** [comment]
Unfortunately I think in this case it seems like Terraform is working as designed, though I understand that it's not working the way you had hoped.

It seems like the root problem here is that at least one of `module.iam_policy1.arn` and `module.iam_policy2.arn` is derived from a value that the provider can only learn during the apply step, and so when the `compact` function tries to perform its intended function it finds that it can't yet determine whether each of the elements will be an empty string or not, and so it can't predict how long the resulting list will be until the apply step. Then you try to use the length of the list as part of calculating the `count` for `resource "iam_role_policy_attachment" "custom"`, which fails as it should because the result is not knowable during the planning step.

To make this work you'll need to change your approach so that the number of elements in that list is decided some other way that only considers values you've defined statically in the configuration. I can't make a concrete suggestion without seeing more of your configuration, but if you'd like to open a [community forum](https://discuss.hashicorp.com/c/terraform-core/27) topic with a fuller example of your configuration I'd be happy to think through possible alternatives with you there.

**Comment by Roxyrob** [comment]
Hi @apparentlymart,
you can see more details in community forum:

[https://discuss.hashicorp.com/t/collection-function-introduce-cannot-be-determined-until-apply/20929](url)

Some clarification here about your assumptions:
 1. Without concat there is no need for terraform to know same values defined at apply time ?
 2. I'm very interested to find offending code to know how to manage such condition, I hope sample code will be clear to you.
 3. Can be terraform error improved to be  more descriptive to easily find offending code ? and how it is possible to know/debug what is evaluated in which "terraform interpretation" step (plan, apply, etc.) ?

Thank you so much.

**Comment by lucendio** [comment]
Just a thought here: might it be that TF, when building up the dependency tree, is only able to recognize direct references between modules, e.g.
```
module "foo" {
  items = module.bar.list_of_items
}
```

and cannot see an indirect reference like
```
locals {
  some_items_from_bar = [ for _, i in module.bar.list_of_items : i ]
}

module "foo" {
  items = local.some_items_from_bar
}
```

Please note that In my experience, it makes no difference whether the assignment is a `for` expression or a function call, e.g. ( `concat([], module.bar.list_of_items)` ).

**Comment by Roxyrob** [comment]
Hi @apparentlymart, some news on this ? I don't know if it is something related to what @lucendio says, but if so, why TF should have such behavior only using compact function and not without ? Not many contribution in the community.

@jbardin: same issue using lates 0.13.6 tf version.

**Comment by Roxyrob** [comment]
Not a Bug.

Reference discussion in [community forum](https://discuss.hashicorp.com/t/collection-function-introduce-cannot-be-determined-until-apply/20929/8)
