### ISSUE TITLE
Please add support for standard if-then-else construct

### ISSUE THREAD

**Issue by inaun** [hashicorp/terraform#27752]
Please add support for standard if-then-else type construct.

A lot of very ugly work-arounds have been created to simulate "if-then" logic in Terraform. These workarounds typically have severe limitations and make code obtuse. A standard if-then-else type construct would be very helpful to producing more flexible modules. As a simple example:

Instead of this:

    whatever_resource "example" {
      for_each = length(var.resources) > 0 ? var.resources : {}
      <....>

allow something like this:

if var.resources != null {
  whatever_resource "example" {
  for_each = var.resources
  <...>
}

While this simple example does not do justice to the power of if-then-else logic, more complex scenarios become possible by adding this feature.

**Comment by jbardin** [comment]
Hi @inaun 

Thanks for filing the issue. As you have shown in the example, the terraform configuration language does have the ability to process conditional expressions, it just so happens that `if`, `then` and `else`  are spelled more tersely as `?` and `:`. 

Besides the syntax for imperative conditional blocks not fitting in the language itself, the terraform language is declarative and has no order of operations between expressions. For these reasons the common C-style ternary syntax was adopted to allow for conditional expressions within configuration files. 

Since we are not going to be adding any imperative block syntax to the language, I'm going to close this out for now. 
We use GitHub issues for tracking bugs and enhancements, so if you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
