### ISSUE TITLE
Error executing PowerShell command from local-exec: executable file not found in $PATH

### ISSUE THREAD

**Issue by BenWyattMilliman** [hashicorp/terraform#27756]
The example code in my issue is copy-pasted directly from the `local-init` example in the documentation: https://www.terraform.io/docs/language/resources/provisioners/local-exec.html#interpreter-examples

### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.46.1
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "0.13.3" # Update GitHub Actions and Terraform Workspaces at the same time
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "3.0.0"
    }
  }
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "redacted"
    workspaces {
      prefix = "redacted"
    }
  }
}
provider "null" {
  # Configuration options
}

resource "null_resource" "example2" {
  provisioner "local-exec" {
    command     = "Get-Date > completed.txt"
    interpreter = ["PowerShell", "-Command"]
  }
}
```

### Expected Behavior

The script should be executed on the Terraform backend

### Actual Behavior

Apply outputs this error:
`Error: Error running command 'Get-Date > completed.txt': exec: "PowerShell": executable file not found in $PATH. Output: `

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @BenWyattMilliman,

The error appears to indicate that `PowerShell` is not in the PATH for the user executing terraform. Can you verify that you have the `PowerShell` executable in your path, and possible test if it works when providing an absolute path? 

Thanks!

**Comment by BenWyattMilliman** [comment]
@jbardin PowerShell is on _my_ path, but that shouldn't bee relevant in this case, because the Apply operation is running in Terraform Cloud. From the [documentation](https://www.terraform.io/docs/language/resources/provisioners/local-exec.html) for `local-exec`: 

| This invokes a process _on the machine running Terraform_, not on the resource.

I've not been able to find any documentation of what's available on the path when running in Terraform Cloud, but the documentation for `local-exec` certainly led me to believe that PowerShell should be there.

If there's another scripting option available to me, like bash, I'd be happy to use it. Is there any documentation of what interpreters are available in Terraform Cloud?

**Comment by jbardin** [comment]
Thanks @BenWyattMilliman,

Terraform cloud would be running on a linux host, so `bash` (or a bourne compatible shell) would likely be the default there. I'm not certain of the specific details of the hosts, there may be more interpreted language runtimes available, but for more complex use cases you will want to run the command on a host you control so that the environment is ensured to be consistent with your configuration.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. You can also check the [Terraform Cloud specific category](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44) for information regarding the cloud offering specifically.

Thanks
