### ISSUE TITLE
aws_ram_resource_share fails to allow sharing of specific resource types

### ISSUE THREAD

**Issue by dsantanu** [hashicorp/terraform#27764]
Hi there,
I'm not sure if this is actually an issue with the provider or Terrafrom itself but I'm unable to create any RAM share when the IAM role that used by Terraform, has a conditional statement like this:
```
{
    "Sid": "WritePermissions_RAM",
    "Effect": "Allow",
    "Action": [
        "ram:AssociateResourceShare",
	"ram:CreateResourceShare"
    ],
    "Resource": "*",
    "Condition": {
	"StringEquals": {
	    "ram:RequestedResourceType": "ec2:TransitGateway"
	}
    }
}
```
### Terraform Version
```
Terraform v0.13.6
```

### Terraform Configuration Files
```terraform
resource "aws_ram_resource_share" "tgwz" {
  name                      = "Internal_Shared_TGW"
  allow_external_principals = true
}
```
### Error Output
```
Error: Error creating RAM resource share: AccessDeniedException:
	status code: 403, request id: 68b05267-280b-4f7a-943d-a3f2d556ae12
```

### Expected Behavior
Should not get `403` and should have created the share.

### Actual Behavior
Fails with access denied

### Additional Context
It appeared that if the condition key `ram:RequestedResourceType` is applied to the policy, that causes the Access Denied for Terraform, because of the missing `RequestedResourceType` details within the request context that sent by TF. The ability (and the requirement) to specify the `ResourceArn` within the context of the `CreateResourceShare` call, translates the resource back to RAM with the associated Resource Type. This resource type is then compared against the condition key's resource type to determine if the request will be allowed or denied. Terraform doesn't seem to have an option to specify the resource type for `aws_ram_resource_share`

### References
https://docs.aws.amazon.com/cli/latest/reference/ram/create-resource-share.html

**Comment by apparentlymart** [comment]
Hi @dsantanu,

Unfortunately this does seem to be an error returned by the AWS provider rather than by Terraform itself; this `ErrorType: status code: nnn, request id: blahblahblah` message structure matches the typical error message shape the AWS Go SDK tends to produce. It looks like this particular error message is coming from [`resource_aws_ram_resource_share.go` line 68](https://github.com/hashicorp/terraform-provider-aws/blob/cd777a4a509571e9ffbc65aa2a7e7e965a69e4ad/aws/resource_aws_ram_resource_share.go#L68) in the current latest commit of the AWS provider.

For that reason, I'll have to ask you to open this issue in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) instead, if you believe this to be a bug in the provider. With that said, referring to that source code I linked above suggests that the provider is doing nothing here except thinly wrapping the API call to `ram:CreateResourceShare`, so I have a feeling that this will end up perhaps being a feature request to support some more of the fields of `CreateResourceShareInput` to allow you to set whatever is necessary to match your `ram:RequestedResourceType` condition.

Since there's nothing we could practically do to improve this situation for you in the main Terraform repository, I'm going to close this now. Thanks!

**Comment by dsantanu** [comment]
thanks!! @apparentlymart 
Reported as a provider bug: https://github.com/hashicorp/terraform-provider-aws/issues/17606
