### ISSUE TITLE
Command to move all resources to a module 

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#27767]
It would be really useful to have a command to assist with some state manip eg move a set of resources to a module. This is something that can be scripted eg refactor-to-module:
- create folder
- move all files except .terraform, state files, tfvars
- create main.tf that has module statement with relative path to created module, and has tfvars as params
- remove tfvars file
- do `terraform state mv $current -> module.name.$current` for all resources) current in state file
- do terraform init
- do terraform plan to ensure no mods
- provide a way to restore to original state if fails

**Comment by jbardin** [comment]
Rather than attempting to cover all possible operations with a mini-language of command arguments, we are considering the possibility of actions to be handled via the application of configuration changes. 

Since this is not a fully-fledged proposal, I'm going to add this to #9048 as we work on the future solution to these problems. 

Thanks!
