### ISSUE TITLE
Let users ignore datasource field changes

### ISSUE THREAD

**Issue by billietlsfeir** [hashicorp/terraform#27776]
### Current Terraform Version

```
0.14.2
```

### Use-cases

As a terraform user, in order to simplify plans that relies heavily on datasources, I'd like to setup my datasources to ignore changes in unused fields.

In my case, we consume PaaS on Aiven, which provides [a rich provider](https://registry.terraform.io/providers/aiven/aiven/latest) and its `aiven_project` datasource gives values intended to change often (like current balance or available credit), which make every resources using fields from this datasource *potentially* change. Telling terraform to ignore such fields would be neat.

### Attempted Solutions

Since using `lifecycle` meta-argument [is not possible on datasource](https://www.terraform.io/docs/language/data-sources/index.html#meta-arguments), I really don't know how I could achieve my goal without rewriting all my code.

### Proposal

Make `lifecycle.ignore_changes` usable on datasources, so the flagged fields won't be read, or will not impact other resources.

**Comment by jbardin** [comment]
Hi @billietlsfeir,

Regarding the `lifecycle` block, I assume you are referring to the `ignore_changes` argument to prevent changes from being reflecting the resources. The `ignore_changes` feature only prevents changes to _configuration_, it cannot prevent a provider from returning updated data for a resource. 

The situation you mention however is still what `ignore_changes` was designed to handle, but it is meant to be used on the resources with the changing inputs, rather than the source of the changes themselves. This way once the managed resources are created, they can remain static for the duration of their lifetime, while newly added resources will be able to read the most update data data from the state. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
