### ISSUE TITLE
Docs in PDF Format

### ISSUE THREAD

**Issue by shahul01** [hashicorp/terraform#27779]
### Use-cases
I would like to have all these Documentations in PDF so I could print & read them, significantly increases focus.

Link - https://www.terraform.io/intro/index.html

![image](https://user-images.githubusercontent.com/53307156/108003086-99b0ed80-7017-11eb-8b23-e5c3b3b94fcf.png)

Btw I tried to find others who have it but there is not much docs there...

Thanks

**Comment by apparentlymart** [comment]
Hi @shahul01! Thanks for sharing this use-case.

While I do understand your desire to have the documentation in alternate formats, I also want to be honest that such a thing is not likely to happen in the near or medium term because the content on the Terraform website exists only in a form suited for website rendering, and in particular there's no overarching machine-readable structure to act as the outline for a print-oriented version of the documentation.

With the understanding that this doesn't address your use-case entirely, I do want to note that the Terraform documentation web pages all have a print-oriented stylesheet which means that you should at least be able to print out individual pages for offline reading and have them appear in a reasonable way.

Restructuring the documentation to be in a more "book-like" shape to allow for assembling larger PDFs combining many pages together would be a very large project and unfortunately something we don't have the resources to work on right now, due to focus being elsewhere.

**Comment by shahul01** [comment]
Fine, I will save them as pdf manually via chrome print function.

Btw just to clarify, you dont have to change any format just throw the overview at front followed by all info content without any changes in style.
