### ISSUE TITLE
Module registry link rewrite errors

### ISSUE THREAD

**Issue by ranieuwe** [hashicorp/terraform#27794]
There is an issue in the [module registry](https://registry.terraform.io/) site for rewriting URLs, this doesn't seem to be provided specific. Here is an example for the Azure provider:

1. Go to https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine
2. Check the link on the first item:
![image](https://user-images.githubusercontent.com/2513121/108112693-4c4e7380-704b-11eb-8085-708909e964c4.png)
The link goes to https://www.terraform.io../docs#argument-reference where you will see two trailing periods ("..") after the terraform.io
3. The link in the actual markdown file is: ```[using the `features` setting within the Provider block](https://www.terraform.io/docs/providers/azurerm/index.html#argument-reference).```

Somewhere this link is being rewritten (incorrectly). I have seen this behavior on a few pages, but I can't find the source of the registry page (if available) to fix this myself.

### Expected Behavior
Link to https://www.terraform.io/docs/providers/azurerm/index.html#argument-reference 
### Actual Behavior
A mangled link to https://www.terraform.io../docs#argument-reference

### Steps to Reproduce
1. Make any DIRECT link to terraform.io, relative links are not affected

**Comment by ranieuwe** [comment]
Note that this report may not belong here, but I can't figure out where to send it instead, there are no report/contact details on the registry site itself.

**Comment by apparentlymart** [comment]
Hi @ranieuwe! Thanks for reporting this.

Looking at [the corresponding source file](https://raw.githubusercontent.com/terraform-providers/terraform-provider-azurerm/master/website/docs/r/linux_virtual_machine.html.markdown), it looks like the link there is an absolute one to a page on `terraform.io`, which I suspect was an authoring mistake because provider documentation typically uses only relative links when the target is another page within the provider documentation.

The correct resolved target for this link should actually be the following now that the provider documentation has moved to the registry:

```
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#argument-reference
```

...although a relative URL would be the best way to achieve that, because then it would work correctly with the version selector to view older versions of the provider documentation.

It does seem weird to me that the registry is introducing those extra dots when rewriting this, but given that this link ought to be a relative one anyway I'd suggest opening an issue in [the Azure provider repository](https://github.com/terraform-providers/terraform-provider-azurerm) to prompt fixing the link in the docs. The provider team is likely also in a better position to send a bug report upstream to the registry team if necessary, because they'll know better than we (the Terraform core team) do what the expectations are for valid provider documentation in the registry.

There's nothing we could change in _this_ repository that would improve that link, and for that reason only I'm going to close this. It is a valid bug report, but the Azure provider repository would be the better place to work on addressing it. Thanks!
