### ISSUE TITLE
Missing a "Complete" deployment mode (destroy all unmanaged resources) [Critical]

### ISSUE THREAD

**Issue by InspiringCode** [hashicorp/terraform#27815]
At the moment we are using Azure ARM templates to deploy our infrastructure. It is part of our release pipeline and we have set the deployment mode to "Complete" which means that all resources and settings, that are not in our ARM templates are destroyed or reset.

We would really love to switch to terraform, since it is so much better in most regards, but this really is a hard requirement in our company.

### Use case
The use case/reason is, that if a developer changes some settings or adds some resources manually in the Azure portal, we would not notice. This would lead to the follow fatal problem: deployment to PROD is only allowed to the Azure DevOps service user. In this case this would mean that the application would run perfectly fine on the TEST environment, but when deployed to PROD it would suddenly fail because resources are missing or settings are different, which would be a huge problem.

Is there any way this can be accomplished with Terraform? We would *really* love to use it in our company. Are there any plans to support this scenario? Is there any workaround how this could be done?

**Comment by charles-dexter-ward** [comment]
Maybe this could help?

https://www.terraform.io/docs/cli/import/index.html

**Comment by InspiringCode** [comment]
As far as I have seen, I can only import a single resource that I manually have to specify with `import`? Is there any way to say to Terraform _"Please import EVERY object in a certain resource group"_? 

If that is possible my scenario would work. Then every existing resource would be imported to the state but since the previously unmanaged objects are not in the tf file, they would be deleted on `apply`.

**Comment by charles-dexter-ward** [comment]
I have only used the import once and as far as I know it is necessary to define the resources in the tf file and then use the import to align the state.

**Comment by jbardin** [comment]
Hi @InspiringCode,

Since terraform itself cannot know what should exist in the world outside of the given configuration, and Azure has something similar already for their own infrastructure, this would most likely be better suited as a enhancement request for the Azure provider. The provider also already has a template deployment resource which includes a `deployment_mode`: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment. 

As for the possibility to import a large set of resources, terraform does not have that ability yet, but there are some external tools written to create the necessary configuration. The only channel terraform can communicate with any cloud service is through a provider, so this would also be something that must be be implemented by providers as well as the SDK. A starting point for this in terraform would be #26558. We currently have an issue tracking a possible bulk import feature in #22219, and other ideas for enhancing the workflow to import large configuration like #26364.

There doesn't appear to be anything directly actionable here, so I'm going to close this in favor of tracking the enhancements in the linked issues.
