### ISSUE TITLE
DNS zone name "cname" must be fully qualified: "azure.foo.com.br"

### ISSUE THREAD

**Issue by zayanic** [hashicorp/terraform#27817]
I`m creating this cname record set, but when put the command "terraform plan", i got this message " DNS zone name "cname" must be fully qualified: "azure.foo.com.br". I`m using Terraform v0.14.7. In the azure platform in "DNS Zones" i have already created a zone called: foo.com.br 
Anyone could help me ? What should i do ?

provider "azurerm" {
  features {}
}

resource "dns_cname_record" "tech" {
  zone  = "foo.com.br" 
  name  = "tech.foo.com.br"
  cname = "azure.foo.com.br"
  ttl   = 3600
}

**Comment by jbardin** [comment]
Hi @zayanic 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

I'm not certain if this is the issue, but a fully qualified domain name should end in a `.`. If that doesn't help, please feel free to check in the forums for assistance!

Thanks!
