### ISSUE TITLE
Terraform export Azure Importing Existing Infrastructure any easier way

### ISSUE THREAD

**Issue by Scarlettliuyc** [hashicorp/terraform#27856]
### Current Terraform Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v1.44.0
(this is an advice request not related with the version )

```
...
```

### Use-cases
Hi team,
We want to know how to import exist Azure Importing Existing Infrastructure to Terraform.
We have followed this doc https://cloudskills.io/blog/terraform-azure-07
Using man.tf add exist resources in it ,and apply to terraform
However we have 19 subscriptions with thousands resources it's hard to manually add the resources one by one to the man.tf,
Could you please tell us any easier way can we import the resources.

In addition, we want to know any other way to do versioning control for terraform, like github threads.
we know there is a command  **terraform state**, but it's to show the resources state not the edit people or version.

### Attempted Solutions
wrote main.tf
resource "azurerm_resource_group" "rg"{
    name = "cloud-shell-storage-southeastasia"
    location = "southeastasia"
}
resource "azurerm_virtual_network" "example" {
  name                = "testmyvnet"
  address_space       = ["10.0.0.0/16"]
  location            = "eastus"
  resource_group_name = azurerm_resource_group.rg.name

  subnet {
        name           = "default"
        address_prefix = "10.0.0.0/24"
        }
subnet {
    name           = "subnet-terraform-10.0.1.0_24"
    address_prefix = "10.0.1.0/24"
  }
subnet {
    name           = "subnet-terraform-10.0.1.0_25"
    address_prefix = "10.0.2.0/24"
  }
}
and applied the vnet and subnets.

### Proposal
Any other work around to import existing resources ?
and whether we can have deployment version control for terraform 

### References
https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage#:~:text=Terraform%20state%20is%20used%20to%20reconcile%20deployed%20resources,This%20configuration%20isn't%20ideal%20for%20the%20following%20reasons:
https://www.terraform.io/docs/language/state/index.html

**Comment by jbardin** [comment]
Hi @Scarlettliuyc 

Thanks for filing the issue. We are aware that there is a demand for a better import process, and it is on our roadmap to research new ideas in this area. The current mechanism will require some external automation or manual work to import existing resources, but the in most cases this is only to be done once. Import is not intended to be a part of the typical terraform workflow.

This however appears to be two unrelated questions rather than a concrete enhancement proposal.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
