### ISSUE TITLE
How to use Terraform for Infrastructure deployment on Azure China Cloud ?

### ISSUE THREAD

**Issue by syedinfy** [hashicorp/terraform#27886]
Does Terraform have provider for Azure China Cloud? Or can we use azurerm for Azure China Cloud? Please help me.

I had used azurerm provider & tried to create infrastructure in Azure China CLoud. But i am unable to do so.

**Comment by jbardin** [comment]
Hi @syedinfy 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
