### ISSUE TITLE
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#security_groups says is an array of ids but doesnt work

### ISSUE THREAD

**Issue by stevemarksd** [hashicorp/terraform#27883]
Says `security_groups - (Optional, EC2-Classic and default VPC only) A list of security group names (EC2-Classic) or IDs (default VPC) to associate with.`

I tried this:

```
  security_groups = [
    aws_security_group.test.id
  ]
```

Says: `Error: Error launching instance, possible mismatch of Security Group IDs and Names. See AWS Instance docs here: https://terraform.io/docs/providers/aws/r/instance.html.`

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hi @stevemarksd,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core), and maybe more specifically the [AWS Provider category](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help.

Thanks
