### ISSUE TITLE
Feature: Allow configuring default arch(s) for .terraform.lock.hcl

### ISSUE THREAD

**Issue by m1keil** [hashicorp/terraform#27894]
### Current Terraform Version
```
Terraform v0.14.6
```

### Use-cases
At times, we create or update `.terraform.lock.hcl` files locally on our machines before we push the change to the repository. This is done by Terraform automatically (via `terraform init`) and we don't execute `terraform providers lock`.
Our CI/CD pipeline runs on Linux but local machines are a mix of MacOS and Linux. As a result, at times the auto-generated lock file contains the wrong arch and the CI pipeline fails because of failure to install providers due to checksum error.

### Workarounds
This can be handled by whatever wrapper you already have for Terraform: Makefiles, scripts or anything else that wraps your Terraform runs. 

### Proposal
Allow configuring which arch should be added to the lock file during auto lock file generation, either globally or on the project level.

### References
https://github.com/hashicorp/terraform/issues/27388

**Comment by apparentlymart** [comment]
Hi @m1keil! Thanks for sharing this use-case.

I think the tricky part of what you've proposed here is that Terraform is already recording all of the checksums it knows about in the lock file, and so recording any _additional_ checksums would require fetching more information from upstream, potentially to the point of retrieving entire `.zip` packages in order to locally calculate the checksums for those. This requirement is the core reason for the current approach where `terraform providers lock` is separated and is responsible for doing those extra requests when needed.

With that said, if you were installing from origin registries then Terraform should be able to capture all of the `zh:`-style checksums across all platforms from the signed data in the registry itself, and so I'd like to confirm whether you have mirror/caching enabled (thus preventing Terraform from accessing the signed hashes from upstream) to make sure that what you've seen here really is a feature request and not a bug report. If you do have a non-default provider installation configuration, it'd be great if you could share it (possibly with the exact paths/hostnames elided) just so we have some context for what situation you're encountering this problem in.

**Comment by m1keil** [comment]
Hey @apparentlymart,
I don't have anything special configured. My setup pools providers from the default official terraform registry.

> and so recording any additional checksums would require fetching more information from upstream, potentially to the point of retrieving entire .zip packages in order to locally calculate the checksums for those.

Well, I must do that anyway just manually, no?

**Comment by apparentlymart** [comment]
After you ran `terraform init`, what did it record in your lock file? Is expect to see a number of different checksum with the `zh:` scheme matching the hashes provided by the provider publisher, along with at least one `h1:` hash which Terraform calculated itself from the package it downloaded.

**Comment by m1keil** [comment]
I remoted `.terraform` and `.terraform.lock.hcl` and re-ran `terraform init`.

Here's the content of the lock file:

```
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.29.1"
  constraints = ">= 2.45.0, >= 2.53.0, >= 2.54.0, ~> 3.27"
  hashes = [
    "h1:RGjj+AQ36r8UMMa5fRWrQ8ONeMe6z31UXVAYQhPTH2s=",
    "zh:2376f60f59d9c49277ea18d02f6ae316255df214046be87eacdad6ed8e56ba10",
    "zh:48dfd5ad70f26d794911413db14d957abb0bdff5000d5cb486464156201fcdf2",
    "zh:8aec3e84117df4195372ef58a2fd52900338156725da24d62fe7daab14d3ecae",
    "zh:b51fcbc7f2a6d78dfccb82b827f7f9da1ac1e51a5b7b3784f36de3e53b0e963d",
    "zh:c3df4b044020e4a5e13d6532d4e0ba191719b87131ccee07bd35dc819a09412d",
    "zh:c5195102a6411db6a5b96492f5dbe5a637e8063365efc14d13b05cb5e2764e8c",
    "zh:d57da72f95d0d8498d1c42a62241c93c5e30538471585177df6ea9280bf55de3",
    "zh:dec04bb83e3b6424f4e18ce0c48c14f3c75fbdd0d4f9181cb56f846fa9ac51f9",
    "zh:e9b4c360d6572db70e29be95076f2543a562420262c906cff710e662d6223247",
    "zh:ecb606aee05da1b2033874b5a9916d6d2877e748d5478a0d70b6fc4b5d08ab11",
  ]
}

provider "registry.terraform.io/hashicorp/random" {
  version     = "3.1.0"
  constraints = ">= 2.2.0"
  hashes = [
    "h1:rKYu5ZUbXwrLG1w81k7H3nce/Ys6yAxXhWcbtk36HjY=",
    "zh:2bbb3339f0643b5daa07480ef4397bd23a79963cc364cdfbb4e86354cb7725bc",
    "zh:3cd456047805bf639fbf2c761b1848880ea703a054f76db51852008b11008626",
    "zh:4f251b0eda5bb5e3dc26ea4400dba200018213654b69b4a5f96abee815b4f5ff",
    "zh:7011332745ea061e517fe1319bd6c75054a314155cb2c1199a5b01fe1889a7e2",
    "zh:738ed82858317ccc246691c8b85995bc125ac3b4143043219bd0437adc56c992",
    "zh:7dbe52fac7bb21227acd7529b487511c91f4107db9cc4414f50d04ffc3cab427",
    "zh:a3a9251fb15f93e4cfc1789800fc2d7414bbc18944ad4c5c98f466e6477c42bc",
    "zh:a543ec1a3a8c20635cf374110bd2f87c07374cf2c50617eee2c669b3ceeeaa9f",
    "zh:d9ab41d556a48bd7059f0810cf020500635bfc696c9fc3adab5ea8915c1d886b",
    "zh:d9e13427a7d011dbd654e591b0337e6074eef8c3b9bb11b2e39eaaf257044fd7",
    "zh:f7605bd1437752114baf601bdf6931debe6dc6bfe3006eb7e9bb9080931dca8a",
  ]
}
```

Here is the content of the lock file after I force `-platform=darwin_amd64 -platform=linux_amd64`:

```
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.29.1"
  constraints = ">= 2.45.0, >= 2.53.0, >= 2.54.0, ~> 3.27"
  hashes = [
    "h1:RGjj+AQ36r8UMMa5fRWrQ8ONeMe6z31UXVAYQhPTH2s=",
    "h1:vFaEB2VBkZnKUXuVbOLbq6a8mOYNx2ftmTRP0YVbzu8=",
    "zh:2376f60f59d9c49277ea18d02f6ae316255df214046be87eacdad6ed8e56ba10",
    "zh:48dfd5ad70f26d794911413db14d957abb0bdff5000d5cb486464156201fcdf2",
    "zh:8aec3e84117df4195372ef58a2fd52900338156725da24d62fe7daab14d3ecae",
    "zh:b51fcbc7f2a6d78dfccb82b827f7f9da1ac1e51a5b7b3784f36de3e53b0e963d",
    "zh:c3df4b044020e4a5e13d6532d4e0ba191719b87131ccee07bd35dc819a09412d",
    "zh:c5195102a6411db6a5b96492f5dbe5a637e8063365efc14d13b05cb5e2764e8c",
    "zh:d57da72f95d0d8498d1c42a62241c93c5e30538471585177df6ea9280bf55de3",
    "zh:dec04bb83e3b6424f4e18ce0c48c14f3c75fbdd0d4f9181cb56f846fa9ac51f9",
    "zh:e9b4c360d6572db70e29be95076f2543a562420262c906cff710e662d6223247",
    "zh:ecb606aee05da1b2033874b5a9916d6d2877e748d5478a0d70b6fc4b5d08ab11",
  ]
}

provider "registry.terraform.io/hashicorp/random" {
  version     = "3.1.0"
  constraints = ">= 2.2.0"
  hashes = [
    "h1:BZMEPucF+pbu9gsPk0G0BHx7YP04+tKdq2MrRDF1EDM=",
    "h1:rKYu5ZUbXwrLG1w81k7H3nce/Ys6yAxXhWcbtk36HjY=",
    "zh:2bbb3339f0643b5daa07480ef4397bd23a79963cc364cdfbb4e86354cb7725bc",
    "zh:3cd456047805bf639fbf2c761b1848880ea703a054f76db51852008b11008626",
    "zh:4f251b0eda5bb5e3dc26ea4400dba200018213654b69b4a5f96abee815b4f5ff",
    "zh:7011332745ea061e517fe1319bd6c75054a314155cb2c1199a5b01fe1889a7e2",
    "zh:738ed82858317ccc246691c8b85995bc125ac3b4143043219bd0437adc56c992",
    "zh:7dbe52fac7bb21227acd7529b487511c91f4107db9cc4414f50d04ffc3cab427",
    "zh:a3a9251fb15f93e4cfc1789800fc2d7414bbc18944ad4c5c98f466e6477c42bc",
    "zh:a543ec1a3a8c20635cf374110bd2f87c07374cf2c50617eee2c669b3ceeeaa9f",
    "zh:d9ab41d556a48bd7059f0810cf020500635bfc696c9fc3adab5ea8915c1d886b",
    "zh:d9e13427a7d011dbd654e591b0337e6074eef8c3b9bb11b2e39eaaf257044fd7",
    "zh:f7605bd1437752114baf601bdf6931debe6dc6bfe3006eb7e9bb9080931dca8a",
  ]
}
```

From diffing I can see that the only difference is the 2nd `h1:`.

**Comment by apparentlymart** [comment]
Hi @m1keil,

Thanks for sharing that! What you shared here matches the design intent: your first `terraform init` run grabbed all of the checksums provided by the original publisher of the provider (the `zh:` ones), which should then be sufficient to install all of the other platform packages for the provider from the same registry without encountering a checksum error.

Separately, Terraform also generated locally the `h1:` new-style checksum corresponding to the package you actually installed, as part of gradually migrating from the `zh:` style to the `h1:` style, which would be a prerequisite for being able to install that same provider from a mirror in future. That `h1:` checksum covers the same package as one of the `zh:` checksums, but does so in a way that Terraform can compute only from data available in a local mirror rather, vs. data that is only available in the origin registry.

In your opening comment here you mentioned that you'd encountered a checksum error when trying to run `terraform init` later on a system with a different platform. Based on the output you've shared here I don't yet understand why that would have happened, because one of those `zh:` checksums added by the initial run should've been enough to verify the package for the new architecture. Do you still have the logs for that failed run in your CI/CD system and could share them? That'd help me to understand exactly what went wrong there, and try to figure out why the check failed even though you had a full complement of checksums in the lock file.

Thanks!

**Comment by m1keil** [comment]
hm...

You are absolutely right. Just checked doing terraform init in a vanilla VM and everything went on smoothly. I wonder if this is an issue with our pipeline, specifically something related to [atlantis](https://github.com/runatlantis/atlantis).

The relevant errors from the logs:
```
Error: Failed to install provider from shared cache

Error while importing hashicorp/random v3.1.0 from the shared cache directory:
the provider cache at .terraform/providers has a copy of
registry.terraform.io/hashicorp/random 3.1.0 that doesn't match any of the
checksums recorded in the dependency lock file.
```

I'm definitely confused now. But I think I will keep debugging this myself as it's clearly a set of wrong assumptions on my side.

Thank you for your help!

**Comment by apparentlymart** [comment]
Hi @m1keil,

Based on that error message it seems like the system where you saw this error does have a cache directory configured. Unfortunately that can cause some wrinkles like this because the cache can't generate `zh:` hashes due to it skipping the download from the registry in that case, and so the cache entry must match one of the `h1:` hashes in the lock file in order to succeed.

I think the reason you've seen it work this time is that you did the initial lock file creation on the same platform as the system where your automated pipeline is running, but perhaps before you'd initially populated it on a different platform and thus didn't have a lock file entry for the system with the cache enabled.

Turning the cache off would be an "easy" way to get the behavior I described above, but of course that will have some performance implications for your pipeline because it'd begin re-downloading providers on every run rather than using the cache entries.

The `terraform providers lock` command is, unfortunately, the current best answer for using Terraform in a mixed environment where some runs happen in automation with caching while other runs happen on local machines without caching. That command will download the packages for the platforms you indicate and locally compute the necessary checksums to allow later installation of those packages from a local cache/mirror, thus removing the dependency on the registry in order to get passing checksums.

The other issue #27769 is currently representing the friction in the interaction between the caching mechanism and the locking mechanism, so if there are further improvements related to this then we'll post them over there.

Sorry for the roundabout debugging session here! I hope this has at least explained the behavior you saw and helped to find a path forward.

**Comment by m1keil** [comment]
hmm.. I must say this is more confusing then I though. I'm not sure I even understood the explanation, will have to re-read it.

In general, I think that if the price for locking is too high to pay, we might just opt-out of this feature entirely. Will be following #27769. Cheers!
