### ISSUE TITLE
Support plans with dynamic for_each when the source of the count is a data source

### ISSUE THREAD

**Issue by mjulianotq** [hashicorp/terraform#27925]
### Current Terraform Version
```
Terraform v0.14.6
```

### Use-cases
In AWS, I would like to dynamically create 1 subnet per availability zone that supports an instance type given as a variable to a module. This dynamically cascades to other resources including route table associations and the instances, themselves.

### Attempted Solutions
Currently, this requires that I use `-target` to create my dynamic resources one at a time which defeats the purpose of using automation.

### Proposal
In situations where the DAC for a `for_each` has a data source as its root node, it is theoretically possible to determine the number of resources without producing side effects by first evaluating the data source and then carrying that count forward down the graph, assuming resources are already constrained to producing 1 output per input. If resources are not so constrained, then provider developers need a way to mark whether a resource supports carrying counts forward. It won't support every case that someone may wish it to, but that should be enough to enable me to do what I want without violating the inherent constraint of producing a plan without producing side effects.

**Comment by jbardin** [comment]
Hi @mjulianotq,

Thanks for filing the issue. Your description sounds like something that terraform currently does.
If the data source can be used during plan, and the output satisfied the inputs for `count` and `for_each` expressions, then terraform should plan the resources as expected.  

Can you provide an example configuration demonstrating the issue you are having?

Thanks!

**Comment by mjulianotq** [comment]
Hi @jbardin,

I've got 2 dependency chains that have known quantities at their root nodes. I'm realizing that I'm using count on the one that has a data source as its root node while I wait for a PR to be accepted into the provider. This could be throwing things off, but it seems to me it shouldn't considering the count is a static value that is known at plan time. The other crosses module boundaries in a way that makes the value appear to be unknowable if each module builds its own DAC, which I suspect to be the problem. Here's roughly what I've got:

Root Module:
```hcl
module "vpc" {
   ...
}

module "instances" {
    ...
    subnets = module.vpc.private_subnets
}
```

VPC module:
```hcl
data "aws_availability_zones" "azs" {
    state = "available"
}

resource "aws_subnet" "public" {
    ...
    availability_zone_id = data.aws_availability_zones.azs.zone_ids[count.index]
    count = 2
}

# This produces an `Error: invalid for_each argument`
resource "aws_route_table_association" "public" {
    for_each = toset(aws_subnet.public.*.id)
    subnet_id = each.key
    route_table_id = aws_route_table.public.id
}

resource "aws_subnet" "private" {
    ...
}

# The intention is to eventually make this dynamic, so I simulate it for now.
output "private_subnets" {
    value = [ aws_subnet.private ]
}
```

Instances Module:
```hcl
variable "subnets" {
    type = list(object({
        id = string
    }))
}

resource "aws_instance" "instances" {
    for_each = toset(var.subnets.*.id)
    subnet_id = each.key
    ...
}
```

Thanks for taking the time to look at this. Sorry I didn't include these snippets in the original ticket. It was quite a bit of work to extract the essence and anonymize them, and I was more confident than I should have been in my understanding of the situation.

**Comment by jbardin** [comment]
Thanks for the update. 
In this example, while the number of resources is known during planning, their values are not. In order to both `aws_route_table_association.public` and `aws_instance.instances`, we need to know what instances to plan, and in this case the "key" portions of the `for_each` value are unknown. Since terraform cannot determine how to address the instance, it cannot create a plan for that instance.

The only way to create a number of resource instances based on a number of unknown values is `count`, or mapping the unknown values to known keys, for example:

```
for_each =  { for i in range(length(null_resource.a)): (format("%d", i)) => null_resource.a[i].id }
subnet_id = each.value
```
Though the added value of that is limited, as it is approximately the same as using `count`. It'a hard to tell from a limited example what the actual constraints are, but if it all is dependent on the output of `data.aws_availability_zones.azs`, then the configuration should be structured around passing that data between resources. 

I understand that you labeled this as an enhancement, and this is the current expected output, however planning instances with unknown internal addresses is quite a change for the internal architecture of terraform.

I think the most likely resolution would be something along the lines of the "progressive apply" idea captured in #4149. While we don't have any concrete plans to be able to handle that case yet, it is looking to be the most flexible solution for a number of use cases. Until then, what you have here is a configuration that either will need to be split into multiple separate configurations, or will need to be bootstrapped with `-target`.

**Comment by mjulianotq** [comment]
@jbardin I see. That clears up a lot for me. I'll go ahead and close this since it turned out to be a forum question disguised as an enhancement request. Thank you for your time.
