### ISSUE TITLE
The `replace` function regular expression capture group $n sequence "glues" incorectly 

### ISSUE THREAD

**Issue by stawii** [hashicorp/terraform#27937]
### Terraform Version

```
Terraform v0.14.7
```

### Terraform Configuration Files

```terraform
None, just using console.
```

### Expected Behavior

```
> replace("HELLO WORLD!", "/(L+)/", "-$1-")
"HE-LL-O WOR-L-D!"
> replace("HELLO WORLD!", "/(L+)/", "zz$1")
"HEzzLLO WORzzLD!"
> replace("HELLO WORLD!", "/(L+)/", "$1zz")
"HELLzzO WORLzzD!"
```

### Actual Behavior

```
> replace("HELLO WORLD!", "/(L+)/", "-$1-") # works
"HE-LL-O WOR-L-D!"
> replace("HELLO WORLD!", "/(L+)/", "zz$1") # works
"HEzzLLO WORzzLD!"
> replace("HELLO WORLD!", "/(L+)/", "$1zz") # fails, no output!
"HEO WORD!"
```

### Steps to Reproduce
It doesn't matter if it is in resources or from console, so easier way is to run:
```
terraform console
```
and copy-paste examples from above.

### Additional Context

I may be missing something, but I'm running out of ideas.. I've also checked this directly in golang:
```
re := regexp.MustCompile(`(L+)`)
fmt.Println(re.ReplaceAllString("HELLO WORLD!", "-$1-")) // works
fmt.Println(re.ReplaceAllString("HELLO WORLD!", "zz$1")) // works
fmt.Println(re.ReplaceAllString("HELLO WORLD!", "$1zz")) // fails in same way..
fmt.Println(re.ReplaceAllString("HELLO WORLD!", "${1}zz")) // works fine yeah!!
```
However, doing it this way in Terraform:
```
> replace("HELLO WORLD!", "/(L+)/", "${1}zz")
"HE1zzO WOR1zzD!"
```
Um....? What?

Before I finished writing this issue and double checking everyting I came with WORKING solution:
```
> replace("HELLO WORLD!", "/(L+)/", "$${1}zz")
"HELLzzO WORLzzD!"
```
Still, no idea why it has to be so complicated. Curly brackets are documented in golang, but double dollar sign is kinda odd - it wasn't needed in other cases, that's why I've pressed Submit ;)
I guess interpolation syntax is kicking in when it sees `${..}` and `$$` is to avoid this, but it is just a lucky shot..

**Comment by jbardin** [comment]
Hi @stawii

Thanks for filing the issue. The use of regexp pattern within HCL can be confusing. The issue here is that Terraform interprets the `${...}` pattern as a string interpolation, and hence will insert the new value before the `replace` function even can evaluate the string. 

This means that the string `"${1}zz"` as seen by the function appears as `"1zz`" which you can confirm in the console:
```
> "${1}zz"
"1zz"
```

The syntax to escape the interpolation sequence is `$${...}`. 
```
> "$${1}zz"
"${1}zz"
```

This works the same way as regular expressions themselves, when a literal `$` is desired in the output
```
re.ReplaceAllString("HELLO WORLD!", "$$1"))
> HE$1O WOR$1D!
```

Because HCL supports arbitrary string interpolation in this manner, there is no direct way to avoid the escaping issue, but perhaps there is some way we can make this more ergonomic in the future.

Thanks!

**Comment by stawii** [comment]
@jbardin Thank you for the explanation and confirmation of my assumptions. I guess you can close this ticket, or maybe just leave it to update docs/examples to cover this case.
Cheers!

**Comment by jbardin** [comment]
I verified the escape sequences are fairly prominent at the top of the [strings documentation page](https://www.terraform.io/docs/language/expressions/strings.html). Thanks!
