### ISSUE TITLE
Add "smart" plans by allowing providers to define CreateDryRunContext and UpdateDryRunContext

### ISSUE THREAD

**Issue by ari-becker** [hashicorp/terraform#27955]
### Use-cases
When running `terraform plan`, the user should be reasonably confident that a successful plan will result in a successful apply. This is especially important for workflows like those found in Terraform Cloud version-control-driven workspaces, where a GitHub PR will run `terraform plan` and merging to the `main` branch will run `terraform apply`. If `terraform apply` does not succeed, then the `main` branch will be broken, including the possibility of tainted resources.

Currently, `terraform plan` can only provide a level of assurance in so far as to check the Terraform syntax and the impact on the resource state graph. It is currently unable to ascertain whether the remote API will, in practice, accept the user-proposed changes, as Terraform currently only invokes the provider's `ReadContext` to read state from the remote API.

This results in mismatches between `terraform plan` promising to make certain changes that are predictably going to result in errors when attempting to run `terraform apply`. A few examples:

* AWS IAM policies are subject to [various length restrictions](https://aws.amazon.com/iam/faqs/), e.g. managed policies cannot be longer than 6144 characters. When attempting to create a new managed IAM policy that is longer than this limit, `terraform plan` will indicate that Terraform plans to create one IAM policy, but `terraform apply` will fail due to the AWS API not accepting policies of that length.
* Various resources indicate that certain fields are required in certain provider-domain-specific situations. Attempting to add such resources without defining these fields will give the appearance of succeeding in `terraform plan`, but will predictably fail when running `terraform apply`. For example, the [`aws_rds_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster) resource allows the user to define `enable_http_endpoint`, but only if `engine_mode` is `serverless`. Many fields accept `string` values but are documented to only accept specific values (i.e. an enum), causing `terraform plan` to succeed when the user makes a spelling error.

Ideally, `terraform plan` should be able to catch these issues and return an error, indicating that `terraform apply` cannot be run until the user fixes the underlying issues.

### Proposal
Allow Terraform providers to specify "dry run" options for the create and update operations, which ask the provider's remote API to check whether the create or update operation is possible while committing not to de-facto apply the proposed change. Providers that provide these options must commit to such operations being read-only/non-transformative operations, similar to the provider's current `ReadContext`. If the Terraform provider provides a relevant `CreateDryRunContext` or `UpdateDryRunContext` for a resource, then running `terraform plan` that would result in changes to that resource should call the relevant dry-run operation, thus allowing the external provider to provide feedback during the `plan` phase and before attempting to run `apply`.

If a user's proposed `plan` would result in affecting a chain of resources, then `terraform plan` should warn the user that, while the initial resource in the chain would be changed successfully, Terraform cannot perform a "smart plan" on the changes to subsequent resources in the chain. The user can then decide whether such a warning should preclude running `terraform apply` or whether to proceed despite the warning. For example, if resource `b` depends on resource `a`, and the user attempts to change both, then running `plan` would run `UpdateDryRun` on resource `a`, and assuming that the provider shows the dry-run to be a success, Terraform would warn the user that it could not run a "smart plan" on resource `b` since it needs to finish applying the changes to resource "a" in order to run `UpdateDryRun` on resource "b" with all of its dependent / computed fields.

**Comment by jbardin** [comment]
Hi @ari-becker,

Thanks for the proposal and use cases here. I think we need to clarify some details before we can decide where to exactly to route this request. 

The overall concept here of providing as much information as possible to a provider in order to allow it to essentially simulate the apply, a "dry run" in essence, is how Terraform itself operates. The [`PlanResourceChange`](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md#planresourcechange) API call is is intended to allow providers to take all the known configuration data and generate as much of the known final state as possible. The provider is free to validate and even "dry run" the change in order to ensure the end result will apply correctly. In the _optimal_ case, the `ApplyResourceChange` operation is simply saving the values calculated during the plan and adding in the last identifying pieces of computed data with a high assurance that all the necessary validation has already been done. This process is currently limited by the legacy plugin SDK, but work is underway to expose more functionality and flexibility to the provider by the SDK team. If better access to the underlying Provider API is what you seek, then it would be better to file this with the plugin SDK team as they develop the next generation SDK. 

While the examples you've provided should be validated during the planning process, which the provider has the ability to do, if the configuration values are statically known they can be caught even earlier during the `ValidateResourceTypeConfig` call. The ability to validate the configuration during planning and applying may be again limited by the SDK, but also by the fact that all validation has to be implemented by the provider as well, and it is often easiest for providers to simply pass the config along to the apply process and let the remote API validate it. More extensive planning by the providers would help here, as mentioned in the previous paragraph, but often it's just a matter of providers having the development resources to implement the validation in the first place. For common validations that can be caught ahead of time, issues should be filed with the appropriate provider.

Finally we come to the CLI itself, which again, the rough idea here sounds very similar to what Terraform already does during a plan. Showing the user exactly what changes are being made, and which values are known and yet to be computed is the basic idea here, and future provider improvements are going to increase the detail and accuracy of those plans. What we need here is to define what exactly is a "smart plan", and how that differs from the current plan. Regardless of how much planning resources can do ahead of time, there will usually be values unknown until the resources are created, so a plan is generally going to have some unknowns which the user needs to accept. Can you explain further how we would define a "smart plan", and in what cases we would generate warnings to the user about applying the given plan?

**Comment by ari-becker** [comment]
Hi @jbardin , thanks for the quick response.

I do think that the `PlanResourceChange` and `ValidateResourceTypeConfig` calls adequately cover this; I wasn't aware of them. The [documentation](https://www.terraform.io/docs/extend/plugin-types.html#providers) makes clear references to `CREATE`, `READ`, `UPDATE`, `DELETE` (not "plan", "validate", and "apply") and it wasn't clear (without delving into the repository documentation) that there's a distinction between the wire protocol that Terraform already accepts and what the official plugin SDK has yet to expose. I didn't open the issue in the plugin SDK as I presumed that it exposes what Terraform Core permits, which is to say, that Terraform Core only knows the CRUD calls and not the more sophisticated plan/update/apply calls; if Core only supported CRUD then Core would need to add support first to make this possible. Glad to see Core already has support :)

As for the "smart plan", I see that the wire protocol already supports returning warnings for the plan and validate operations, so I presume that Terraform Core will dispense the warnings appropriately when the providers return warnings. I'm just not sure how that looks if the providers I'm using (AWS mostly) can't support them yet, when the plugin SDK doesn't support the new protocols yet.

**Comment by jbardin** [comment]
Thanks @ari-becker, It sounds like we've already got the machinery you're looking for in place. It will take some time, even one the new SDKs are complete, for big providers like AWS to fully convert to the new APIs. The SDK team and providers are working on some incremental upgrades in the meantime however, and these will start to show up over subsequent releases.

Thanks
