### ISSUE TITLE
Error creating route

### ISSUE THREAD

**Issue by umarkhan207322405** [hashicorp/terraform#27957]
#Public
resource "aws_route_table" "public_r" {
    vpc_id     = aws_vpc.main_test.id
    
    route {
        cidr_block = aws_subnet.main_subnet1.cidr_block
    }
  

  tags = {
    Name = "main_public"
  }
  depends_on = [ aws_vpc.main_test, aws_subnet.main_subnet1]
}
resource "aws_route_table_association" "public_assoc" {
  route_table_id = aws_route_table.public_r.id
  subnet_id = aws_subnet.main_subnet1.id

  depends_on = [ aws_route_table.public_r, aws_subnet.main_subnet1 ]
}

#Private

resource "aws_route_table" "private_r" {
    vpc_id     = aws_vpc.main_test.id
    
    route {
        cidr_block = aws_subnet.main_subnet2.cidr_block
    }
  tags = {
    Name = "main_private"
  }
  depends_on = [ aws_vpc.main_test, aws_subnet.main_subnet2 ]
}

ERROR

Error: error creating route: one of `egress_only_gateway_id, gateway_id, instance_id, nat_gateway_id, local_gateway_id, transit_gateway_id, vpc_endpoint_id, vpc_peering_connection_id, network_interface_id` must be specified

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
