### ISSUE TITLE
On the fly filtering from resource count loop

### ISSUE THREAD

**Issue by Jithin-C-V** [hashicorp/terraform#27967]
Hi All,

Thanks in advance for offering any suggestions. Because i am not sure whether below requirement is possible or the way i am thinking is wrong.

My Requirement is to dynamically receive input and create EC2 with Extra EBS.

My Input Like Below,

ec2_config = [
  {
    ec2_name     = ["EC2-1", "EC2-2", "EC2-3"]
    ec2_subnets  = ["subnet-1", "subnet-2"]
    ec2_ami         = ["ami-xxxxxxxxx"]
    ec2_type       = ["t3.large"]
    ec2_ebs_size = ["50", "100"]
    ec2_ebs_type= ["gp3", "gp3"]
  },
  {
    ec2_name     = ["EC2-4", "EC2-5"]
    ec2_subnets  = ["subnet-1", "subnet-2"]
    ec2_ami         = ["ami-yyyyyyyyyyy"]
    ec2_type       = ["t3.xlarge"]
    ec2_ebs_size = ["50", "100", "150"]
    ec2_ebs_type= ["gp3", "gp3", "gp3"]
  }
]

Now what i want is,
1. Create EC2-1 in subnet-1, EC2-2 in subnet-2 & EC2-3 in subnet-1 with AMI ami-xxxxxxxxx, Type t3.large
2. Create EC2-4 in subnet-1 & EC2-4 in subnet-2 with AMI ami-yyyyyyyyyyy, Type t3.xlarge
3. Create 2 EBS Volumes (50 GB & 100 GB) and attach to instance EC2-1
4. Create 2 EBS Volumes (50 GB & 100 GB) and attach to instance EC2-2
5. Create 2 EBS Volumes (50 GB & 100 GB) and attach to instance EC2-3
6. Create 3 EBS Volumes (50 GB, 100GB & 150 GB) and attach to instance EC2-4
7. Create 3 EBS Volumes (50 GB, 100GB & 150 GB) and attach to instance EC2-5

What is the best coding approach for such kind of requirement ? Because if we are using dynamic ebs_block_device inside aws_instance, the problem is when there is requirement of additional EBS in any set of EC2 will lead to destroy and re-deploy.

So i want to create EBS & EBS attchment outside of aws_instance block. 
* When writing the code outside, how to find out the availability zone to create volume for each instance.
* When writing the attachment, how get correct EBS ID & correct instance ID.

**Comment by Jithin-C-V** [comment]
Anyone have any thoughts ?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
