### ISSUE TITLE
Unable to do terraform destroy on a security group

### ISSUE THREAD

**Issue by sr-shan** [hashicorp/terraform#27960]
Hi,
we are using openstack as a provider. While doing terraform destroy on a security group, we are getting an error "security group is in use". After running some neutron commands, it was discovered that to delete a security group, ports needs to be deleted.
If I issue "neutron port-delete <port-id>" followed by "neutron security-group-delete <security-group-id>" commands manually, security group delete goes ok.
How to enforce terraform to delete the ports created by terraform scripts when issuing a terraform destroy?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
