### ISSUE TITLE
go get -u github.com/hashicorp/terraform fails with package not found error 

### ISSUE THREAD

**Issue by balan2010** [hashicorp/terraform#27972]
Hi there

GO111MODULE=on go get -u github.com/hashicorp/terraform@v0.14.7 fails with below error

go: finding module for package k8s.io/api/auditregistration/v1alpha1
go: finding module for package k8s.io/api/settings/v1alpha1
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.5.4), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:26:2: module k8s.io/api@latest found (v0.20.4), but does not contain package k8s.io/api/auditregistration/v1alpha1
/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:54:2: module k8s.io/api@latest found (v0.20.4), but does not contain package k8s.io/api/settings/v1alpha1
The command '/bin/sh -c GO111MODULE=on go get -u github.com/hashicorp/terraform@v0.14.7' returned a non-zero code: 1

go env 

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build488870107=/tmp/go-build -gno-record-gcc-switches"

any idea on how to fix this ?

**Comment by jbardin** [comment]
Hi @balan2010,

The terraform project canner be installed via `go get`, which has subtle differences from building the module itself (`go get` is in fact being deprecated as a method for building packages). The correct way to build the project is to checkout the desired tag in git, then use `go install`  

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

thanks!
