### ISSUE TITLE
Terraform show is super slow with the json flag

### ISSUE THREAD

**Issue by rmb938** [hashicorp/terraform#27974]
### Current Terraform Version

```
Terraform v0.14.5
```

### Use-cases

I put this under feature request because I don't think this is a bug, more of an annoyance. When running `terraform show` on a plan file that has around 15k resources it takes around 30 seconds however when adding the `--json` flag it takes over 12 minutes.

My guess is something with the json conversion is super slow.  

My use case is I need to import the plan into python so it can be parsed and be converted into human readable markdown for users that are not familiar with terraform. The `terraform show --json` command was an easy solution since dictionaries in python are easy to work with. I would like to keep using the `--json` output but being that it is so slow it isn't feasible. 

### Attempted Solutions

None. If this can't be sped up somehow I will have to fall back on writting my own parser for the normal `terraform show` output.

### Proposal

Possibly look into a faster json parser library?

**Comment by alisdair** [comment]
Thanks for reporting this! I attempted to reproduce this situation and found some easy optimizations which made a huge difference in my testing. If #27998 is merged and this issue is closed, I would appreciate it if you could try out the next 0.15.0-beta to verify that it fixes the problem for you. Or if you're up for it, feel free to build the target branch in #27998.

If that doesn't solve the problem you're seeing, we'd have to investigate further. Having a reproducible configuration which demonstrates the issue would help a lot here—I'm sure my trivial `null_resource` config doesn't capture all the sources of slowness you're experiencing.

**Comment by rmb938** [comment]
Oh wow thanks for the quick response. I'll give the PR a quick test early next week (if it wasn't merged and the beta not release yet) and let you know what I find.

For a reproducible configuration, the tf code I am using contains resources from custom terraform providers so I won't be able to send that directly, I can try and make something similar though.

**Comment by rmb938** [comment]
@alisdair I did some quick tests and it looks like it's working as expected. Is this something we can backport to terraform 14?

**Comment by alisdair** [comment]
Glad to hear that it helped!

At this point the 0.14 branch is in maintenance, and we're only merging fixes for critical issues or crashes. However, 0.15.0 is a matter of a few weeks away, and the upgrade should be a very easy one to make.

**Comment by rmb938** [comment]
Ok perfect, wasn't too sure on that timeline. Thanks!
