### ISSUE TITLE
A `go run main.go` fails to compile on macOS

### ISSUE THREAD

**Issue by Integralist** [hashicorp/terraform#27976]
Apologies if this is the wrong place to raise this issue. I cloned the terraform repo and ran `go run main.go` (which, as expected, proceeded to download a bunch of required module dependencies) but then the compilation step failed...

```
$ go run main.go
# command-line-arguments
./main.go:103:30: undefined: ignoreSignals
./main.go:104:31: undefined: forwardSignals
./main.go:119:2: undefined: Ui
./main.go:144:3: undefined: Version
./main.go:144:12: undefined: VersionPrerelease
./main.go:162:3: undefined: Ui
./main.go:192:3: undefined: Ui
./main.go:202:4: undefined: Ui
./main.go:205:4: undefined: Ui
./main.go:216:19: undefined: credentialsSource
./main.go:216:19: too many errors
```

I decided to look at the code to understand why it thought so many identifiers were undefined and it seems they should exist (e.g. the first error is for `ignoreSignals` which is part of the `main` package and so it should be available).

I'm using go version:

```
go version go1.16 darwin/amd64
```

My system information is:

```
macOS 11.2.1 (Big Sur)
Kernel Version: Darwin 20.3.0
```

**Comment by jbardin** [comment]
Hi @Integralist,

The command `go run main.go` only builds and runs that particular file, and is not how one builds a `main` package. Using `go build` or `go install` then executing the resulting binary is what you’re looking for.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

thanks!
