### ISSUE TITLE
Support and EOL schedules

### ISSUE THREAD

**Issue by skyzyx** [hashicorp/terraform#27971]
We'd like to get an understanding about how HashiCorp views EOL dates for Terraform versions. I haven't been able to find anything concrete on the website, so I'm wondering if there's anything that HashiCorp is willing to share.

I know that 0.12.30 was just released, which suggests to me that it is being _maintained_, but not being _actively_ developed. 0.14.x is _current_, 0.13.x is _maintained_, 0.12.x is _maintained_, and 0.11.x is dead as a doornail…

…I _think_.

**Examples from elsewhere in the community:**

* https://devguide.python.org/devcycle/#end-of-life-branches
* https://www.php.net/supported-versions.php
* https://www.php.net/eol.php
* https://nodejs.org/en/about/releases/
* https://github.com/nodejs/Release
* https://golang.org/doc/devel/release.html#policy
* https://github.com/golang/go/wiki/Go-Release-Cycle
* https://tomcat.apache.org/whichversion.html
* https://alpinelinux.org/releases/
* https://github.com/golang/go/wiki/Go-Release-Cycle

**Comment by apparentlymart** [comment]
Hi @skyzyx,

Unfortunately at the moment there isn't anything as structured as I think you are looking for, although there are of course some less formal guidelines that we use to make risk/reward tradeoffs for different sorts of work.

One thing I can say definitively is that the v0.12.30 release was a very special case that came about only because it was removing a restriction that we'd long imposed in order to allow the state file format to continue to evolve, but we've now completed all of the work that was on the horizon that was likely to require breaking changes to the state format and so we retroactively removed that restriction as far back as the format at that time was compatible enough with the current one for `terraform_remote_state` to work.

But broadly speaking, we're currently maintaining v0.14 and developing v0.15. Once v0.15.0 final is out there'll be a fuzzy sort of period where both are maintained together until v0.15.x releases have "settled", and then we'll switch into a mode of maintaining v0.15 and developing the next release.

We make backporting decisions on a case-by-case basis because it's fundamentally a tradeoff about risk (changes designed for a newer version can sometimes not fit well into an older version in ways we don't expect) and opportunity cost (time spent backporting is time not spent working on something else) vs. reward. We typically give stronger backport consideration for changes that address blockers for upgrading to the latest release, as was the justification for those special v0.12.30 and v0.13.6 releases you noticed.

That's as much as I'm able to say right now because the truth is that _it depends_ and we make this tradeoff anew for each potential backport. Because of that, I'm going to close this only because it's not something we can take any immediate action on. However, we are iterating towards a v1.0 release which will bring with it some more definitive constraints and tradeoffs for future development, and so I think you'll see what you're looking for at that point.

**Comment by skyzyx** [comment]
This explanation is appreciated. I wanted to ask because my team and I support a large number of _other_ teams who themselves are using Terraform versions across the board. We have internal modules, internal providers, and trying to find ways to cleverly support teams using 0.11–0.14 is becoming increasingly complex.

The simplest solution for my team is to say that old versions are EOL and we don't support them. The simplest solution for the teams being supported is to receive support for their current version of Terraform into perpetuity. I'm trying to broker a peace between these groups: we will do our best to support older versions for a longer period of time. In exchange, they need to keep updated _enough_ as to not “fall off the back of the wagon” when it comes to Terraform releases.

In _Calvin & Hobbes_, there is [one strip](https://www.gocomics.com/calvinandhobbes/1993/06/15) where Calvin asks his dad where wind comes from. His dad answers that it’s because the trees are sneezing. Calvin, quizzical, asks “really??” And his dad responds with “No, but the truth is more complicated.” To me, I read this as the simpler answer is sometimes better than the accurate answer.

So, what I think I'm reading as the _simplest answer_ is:

* 0.14 is current, and is fully supported.
* 0.15 is next
* 0.13 and older are essentially EOL (barring special exceptions that are not part of any formal software contract)

I'm not looking for a formal statement-as-contract, and I won't take any statements as such. I'm looking for the _summary_. Is this summary accurate?

> Naturally things like a little different if you're talking about "support" in the sense of _asking questions about_ rather than _making changes to_.

I'm talking about _making changes to_; _putting forth development effort into_; _will adjust what we're working on to make room for_.
