### ISSUE TITLE
Support specify var-file in Terraform Cloud.

### ISSUE THREAD

**Issue by PMExtra** [hashicorp/terraform#27975]
### Current Terraform Version
```
Terraform v0.14.2
```

### Use-cases
Sorry I can't find a feedback channel of Terraform Cloud. So I feedback here. You can tell me how should I feedback to the right place, or please forward my request to relevant team.

I'm a user just migrated to Terraform from the local version. I used terraform workspace to manage multiple environments previously. I create the `{env}.tfvars` file for each environment. Then I can change the workspace and specify `-var-file={env}.tfvars` to work with several environments in one repo.

Now, I followed the document https://www.terraform.io/docs/cloud/migrate/workspaces.html and migrated to Terraform Cloud.
But I can't specify `-var-file` now. I know the `*.auto.tfvars` feature. But in my repo, there are several separated environments.

I also won't manage variables in Terraform Cloud, because there is no version control for variables, and manage variables with `tfvars` file is the most convenient way.

So I request a feature in Terraform Cloud that can specify `-var-file`.

**Comment by apparentlymart** [comment]
Hi @PMExtra! Thanks for this feature request.

Unfortunately as you anticipated this repository isn't monitored by the Terraform Cloud teams. Since Terraform Cloud isn't open source there isn't a public issue tracker for it, but you could start a discussion topic in [the Terraform Cloud section of the community forum](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44), which has some Terraform Cloud contributors monitoring it, or alternatively you could send your request to the Terraform Cloud support team.

This particular issue is, of course, at the cusp of Terraform CLI and Terraform Cloud because you're aiming to use the remote operations support to send an additional option to the Terraform Cloud API when creating a run. That means that resolving this request likely _will_ eventually require a change in this repository, but that won't be possible until there's a suitable API in Terraform Cloud for it to interact with, and so the best path will be to request it via Terraform Cloud and then the Terraform Cloud team would propose the necessary change to Terraform CLI as part of their work on it, once they've evaluated the request.

I'm going to close this issue just to represent that it's not a Terraform CLI issue. Thanks!
