### ISSUE TITLE
Change is not expected in 0.12.10

### ISSUE THREAD

**Issue by linuxmaster0620** [hashicorp/terraform#27991]
0.12.10

```
...
```

### Terraform Configuration Files
resource "aws_cloudwatch_log_group" "default" {
  name = "xx-${local.scope}${local.env}-cwLogGroup-cloudTrail"
  tags = "${merge(var.tags, map("Name", "xx-${local.scope}${local.env}-cwLogGroup-cloudTrail",
                                "Description","Cloud Watch group for cloud trail log streams"))}"
}

resource "aws_cloudtrail" "default" {
  name                          = "${local.scope}${local.env}-cloudTrail-default"
  s3_bucket_name                = "${module.s3_bucket.id}"
  include_global_service_events = true
  enable_logging                = true
  cloud_watch_logs_group_arn    = aws_cloudwatch_log_group.default.arn
  cloud_watch_logs_role_arn     = "${aws_iam_role.default.arn}"
  tags                          = "${merge(var.tags, map("Name", "xx-${local.scope}${local.env}-cloudTrail-default",
                                                         "Description","Cloud trail for tracking cloud activity"))}"

  
  is_multi_region_trail      = true

  depends_on                 = ["aws_s3_bucket_policy.default"]
}

```terraform
...
```

### Debug Output

We are running on already existing infrastructure. so there should be zero change.

### Expected Behavior

No Changes. Infrastructure is up-to-date.

### Actual Behavior

~ Resource = "arn:aws-cn:logs:cn-north-1:XXXacountnumberXXX:log-group:xx-globalsandbox-cwLogGroup-cloudTrail:*" -> "arn:aws-cn:logs:cn-north-1:XXXXXaccountnumber:log-group:xx-globalsandbox-cwLogGroup-cloudTrail"

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. terraform init
2. terraform apply

### Additional Context

Already infrastructure is created using terraform version 0.11.13 and then we have upgraded terraform version to 0.12.10.when we run terraform plan we have observed a change that is not expected. it should be zero changes.

Please suggest what needs to be done to neutralize the change.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
