### ISSUE TITLE
TF state file not processing added information and erroring out (EntityAlreadyExists)

### ISSUE THREAD

**Issue by astevenson2** [hashicorp/terraform#27997]
Hi there,

* When running a targeted terraform apply, errors are being produced related to EntityAlreadyExists. We've tried to solve this issue by deleting deleting all of the aws resources and reapplying. The apply will be successful if the Entities have just been deleted however if ran locally again terraform doesn't acknowledge what should be saved in the terraform state file.
* The individual modules are ran in a shell and target applied so that the shell doesn't expire before the job is complete.
* * 2021-03-05T15:35:39.015Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing" - the debug output gives the following warning alongside various others.

-->

`Terraform v0.14.7`

-->

### Debug Output

* 2021-03-05T15:35:39.015Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing" - the debug output gives the following warning alongside various others

### Expected Behavior

* The terraform should be applied and information should be stored in the tf state file 

### Actual Behavior

* The apply runs successfully once but if you want to apply it again errors relating to EntityAlreadyExists: Duplicate names are not allowed, are produced

### Steps to Reproduce

* Please list the full steps required to reproduce the issue, for example:
1. Create shell
2. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @astevenson2,

I'm not sure exactly what is happening here, but if resources are not correctly applied, an issue should be filed with the appropriate provider. If this is a question about managing resources that already exist, the community forum will be a better resource.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
