### ISSUE TITLE
Output of sensitive values is not suppressed if -json or -raw flags are specified

### ISSUE THREAD

**Issue by logyball** [hashicorp/terraform#28005]
### Terraform Version
```
$ terraform version
Terraform v0.14.7
```

### Terraform Configuration Files

```terraform
variable "test" {
  default = "sensitive value"
}

resource "null_resource" "nothing" {}

output "sensitive" {
  value = var.test
  sensitive = true
}
```

### Expected Behavior

When running `terraform output -json`, sensitive values should be suppressed.

### Actual Behavior

When running `terraform output -json`, sensitive values are displayed to the user.

### Steps to Reproduce

1. Create a terraform definition with a sensitive value as an output (see above for a toy example)
2. Run `terraform apply -auto-approve`
3. Run `terraform output -json`

Here's a full workflow using the above definition:

```bash
~/$ terraform apply -auto-approve
null_resource.nothing: Creating...
null_resource.nothing: Creation complete after 0s [id=5984874434018806709]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

sensitive = <sensitive>
~/$ terraform output
sensitive = <sensitive>
~/$ terraform output -json
{
  "sensitive": {
    "sensitive": true,
    "type": "string",
    "value": "sensitive value"
  }
}
```

### References

[I believe that the issue is here](https://github.com/hashicorp/terraform/blob/main/command/views/output.go#L193). 

In this loop:

```go
	for n, os := range outputs {
		jsonVal, err := ctyjson.Marshal(os.Value, os.Value.Type())
		if err != nil {
			diags = diags.Append(err)
			return diags
		}
		jsonType, err := ctyjson.MarshalType(os.Value.Type())
		if err != nil {
			diags = diags.Append(err)
			return diags
		}
		outputMetas[n] = OutputMeta{
			Sensitive: os.Sensitive,
			Type:      json.RawMessage(jsonType),
			Value:     json.RawMessage(jsonVal),
		}
	}
```

if the code were to check the "Sensitive" boolean before writing to the OutputMeta object, and replace any sensitive values with the "\<sensitive\>" string [in the same way it is done here](https://github.com/hashicorp/terraform/blob/main/command/views/output.go#L84), that would likely fix it.

Note that this also occurs with the `raw` flag.  I am wondering if this is indeed the expected behavior?  I imagine this would be more of a discussion.  However, it seems like an error to have the behavior of the sensitive flag be different depending out the output format to the user.

**Comment by alisdair** [comment]
Hi @loganballard. This is indeed the expected behaviour. The goal of marking outputs and variables as `sensitive` is to avoid accidentally exposing them in human-readable user interfaces—the regular output of `terraform plan`, `apply`, `show`, and `output`, for example.

Sensitive values are not encrypted, and we still need to allow programmatic access to those values. This is why the `output` formats designed to be used in automation (`-raw` and `-json`) show sensitive values.

We [document this prominently for `terraform show`](https://www.terraform.io/docs/cli/commands/show.html), but it is not similarly documented in [the `terraform output` documentation page](https://www.terraform.io/docs/cli/commands/output.html). I'm marking this as a documentation bug as a result.

**Comment by loganballard** [comment]
Hey @alisdair thank you for your quick and thorough response.  I agree that the documentation is the correct place to update.   I can see that for programmatic access, writing to stdout then piping to a tool like `jq` is probably a very common workflow and that removing sensitive values would break those workflows.
