### ISSUE TITLE
Option to automatically SMB mount an Azure FileShare or Blob Container to VM when provisioning

### ISSUE THREAD

**Issue by rbavery** [hashicorp/terraform#28015]
### Use-cases
Easily work with cloud storage using local filesystem, which is common in data science.

### Attempted Solutions
There's very little support on google for this, though people are asking for it. The main suggestion is to manually edit /etc/fstab : https://www.reddit.com/r/AZURE/comments/f7ohk7/how_to_mount_azure_file_share_automatically_in/
https://stackoverflow.com/questions/61505944/get-mount-script-from-azure-file-share-terraform

**Comment by jbardin** [comment]
Hi @rbavery,

This appears to be an enhancement request for a terraform provider. If this is meant for the AzureRM provider, you can file an issue in their project repo here: https://github.com/terraform-providers/terraform-provider-azurerm/issues.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
