### ISSUE TITLE
[Feature request] Add more items in "providers schema" command

### ISSUE THREAD

**Issue by ShiChangkuo** [hashicorp/terraform#28023]
### Current Terraform Version

```
Terraform v0.14.5
```

### Use-cases

Hi, Team
I want to use `terraform providers schema -json` to genetate the schema of resources in json format.
but it seems some items are missing in "attributes" and "block_types" block, for example:
- `force_new` and `default` are missing in "attributes"
- `optional`, `required` and `computed` are missing in "block_types" (only contains min_items and max_items)

### Proposal

It'd be very appreciated if such items are added to the json output.

### References
I searched for other issues but nothing jumped out as relevant.

**Comment by jbardin** [comment]
Hi @ShiChangkuo,

The items you are referring to are fields that only exist in the legacy plugin sdk schema. The `force_new` attribute indicates a field that always triggers replacement, but that is only a convenience for having to calculate which attributes cause replacement for every change. The `default` field is really just another form of `computed`. Blocks cannot really be `optional` or `required` in the protocol, but those serve as a proxy for MinItems. And lastly, a block itself is cannot be `computed`. 

The plugin sdk is developed in a separate project in https://github.com/hashicorp/terraform-plugin-sdk/, and work is being done on a new SDK which will more closely align to the data structures used within Terraform itself. 

Since there's nothing we can change in terraform to expose these fields, I'm going to close this for now. If you have questions about the work being done on the plugin SDK, feel free to visit that project's repository, or ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by ShiChangkuo** [comment]
@jbardin Thank you for your prompt response.
