### ISSUE TITLE
The "count" value depends on resource attributes that cannot be determined until apply,

### ISSUE THREAD

**Issue by nuxlux** [hashicorp/terraform#28052]
### Terraform Version
```terraform
Terraform v0.13.6
```

### Terraform Configuration Files

main.tf
```terraform

locals {
  unique_name = "some_unique_name"
}

resource "aws_iam_policy" "this" {
  count = var.sns_arn == "" ? 0 : 1

  name        = local.unique_name
  description = "IAM policy"

  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Action" : "sns:Publish",
        "Resource" : var.sns_arn,
        "Effect" : "Allow"
      }
    ]
  })
}
```
sns/main.tf
```terraform

variable "sns_topic_name" {
  description = "The name of the sns topic."
  type        = string
  default     = "some_topic_name"
}

resource "aws_sns_topic" "this" {
  name = var.sns_topic_name
}

output "arn" {
  description = "The sns topic arn."
  value       = aws_sns_topic.this.arn
}
```
test/main.tf
```terraform
module "iam_sns_policy" {
  source  = "../"
  sns_arn = module.sns.arn

  depends_on = [
    module.sns,
  ]
}

module "sns" {
  source         = "../sns/"
  sns_topic_name = "sns-topic"
}

```

### Crash Output

```terraform
Error: Invalid count argument

  on ../main.tf line 6, in resource "aws_iam_policy" "this":
   6:   count = var.sns_arn == "" ? 0 : 1

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Expected Behavior
The IAM policy should be created or not depending on if, the variable is empty or not.

### Actual Behavior

Stops with the error.

### Steps to Reproduce

Inside test folder

1. `terraform init`
2. `terraform apply`

### Additional Context
The same behavior happened when using for_each instead of count. 
If we pass the sns arn from a resource and not a module, the issue is the same.
Example: replace test/main.tf with

```terraform
module "iam_sns_policy" {
  source  = "../"
  sns_arn = aws_sns_topic.this.arn

  depends_on = [
    aws_sns_topic.this,
  ]
}

resource "aws_sns_topic" "this" {
  name = "some_topic_name"
}
```

If we pass the sns arn directly, the count is true and the resource is created.
Example: replace test/main.tf with

```terraform
module "iam_sns_policy" {
  source  = "../"
  sns_arn = "arn:aws:sns:eu-west-1:########:some_topic_name"

}
```
```terraform

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.iam_sns_policy.aws_iam_policy.this[0] will be created
  + resource "aws_iam_policy" "this" {
      + arn         = (known after apply)
      + description = "IAM policy"
      + id          = (known after apply)
      + name        = "some_unique_name"
      + path        = "/"
      + policy      = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = "sns:Publish"
                      + Effect   = "Allow"
                      + Resource = "arn:aws:sns:eu-west-1:########:some_topic_name"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.iam_sns_policy.aws_iam_policy.this[0]: Creating...
module.iam_sns_policy.aws_iam_policy.this[0]: Creation complete after 1s [id=arn:aws:iam::#######:policy/some_unique_name]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

If we pass the sns arn emptry, the count is false and the resource is not created.
Example: replace test/main.tf with

```terraform
module "iam_sns_policy" {
  source  = "../"
  sns_arn = ""

}
```

```terraform
terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by jbardin** [comment]
Hi @nuxlux,

The ` module.sns.arn` output is being derived from the managed `aws_sns_topic.this` resource, which means that the value will be unknown during planning. You cannot use unknown values for `count` and `for_each`, since terraform must know which resources it needs to plan, even if the configurations still are not fully known. There are a few way to handle this, either by using `-target` as indicated in the error output, or splitting the configuration into multiple steps.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
