### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by IeuanPayneIPO** [hashicorp/terraform#28056]
Hello, 

I have noticed today, some of my pipelines have started failing with the error:
"Error: rpc error: code = Unavailable desc = transport is closing"

After some investigations I found that the provider had updated from version 2.19.0 to 2.19.1 this seems to have broken my pipeline?

For those getting the error you can hard code your version in your provider section like i did

provider "cloudflare" {
	version		= "2.19.0"
	email 		= "__cloudflare_email__"
        api_key     = "__cloudflare_token__"

Please can this be looked into as to why the update of the provider has broken my pipeline and my statefile?

Thanks
Ieuan

**Comment by jbardin** [comment]
Hi @IeuanPayneIPO,

While there's not enough info here to replicate the issue, the error you see is what happens when a provider plugin exits unexpectedly. The full error output will indicate which provider crashed, but as you say you recently updated the cloudflare provider, that would be my first suspect.

You will need to submit an issue to the appropriate provider, along with the crash output and preferably the configuration used to trigger the issue.

Thanks!
