### ISSUE TITLE
Failure while deploying Azure databricks with VNet injection 

### ISSUE THREAD

**Issue by avinashvee** [hashicorp/terraform#28059]
Hello,

I'm trying to deploy Azure Data-bricks with VNet injection, the data-bricks is going to failed state while deploying. In the Terraform it shows deployment got successful but in Azure we can clearly see Data-bricks in failed state.

When I went through the state file for data-bricks, I can see subnet and Vnet properties are missing after deployment.

And when I created manually or with PowerShell it's working fine.
![image](https://user-images.githubusercontent.com/70731384/110859776-cfd93a00-8270-11eb-962a-47f552313a8f.png)

![image](https://user-images.githubusercontent.com/70731384/110838593-80d2db00-8257-11eb-970e-de0cef90f29e.png)
![image](https://user-images.githubusercontent.com/70731384/110839394-57ff1580-8258-11eb-8af4-47c0b5c43c91.png)
![image](https://user-images.githubusercontent.com/70731384/110839949-03a86580-8259-11eb-81d8-3698c4312210.png)
![image](https://user-images.githubusercontent.com/70731384/110840475-9ea13f80-8259-11eb-95df-5758385fa9c4.png)

**Comment by pselle** [comment]
Hi @avinashvee! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at tf-cloud-support@hashicorp.com. If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
