### ISSUE TITLE
Terraform refusing to parse/convert a tuple into a map

### ISSUE THREAD

**Issue by nemrood** [hashicorp/terraform#28064]
Hello, I'm using 0.14.7 TF. I have a problem as show here in this Stackoverflow topic.

Please let me know if you need more details.

And thanks a lot for such a magnificient infra-as-code tool, you guys rock !

https://stackoverflow.com/questions/66597262/terraform-tuple-to-map-or-set-of-strings-conversion

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
