### ISSUE TITLE
random_id resource is failing even when the version is set right

### ISSUE THREAD

**Issue by vikram-yerneni** [hashicorp/terraform#28074]
Fellas,
I am trying to use random_id [resource](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id) for deploying a kafka module. 
We have a child base module with full kafka Terraform repo (random_id resource is set here) and its being called from a main deployment terraform repo.
Here is the syntax I am using:
**resource "random_id" "rand" {
  byte_length = 8
}

resource "aws_msk_configuration" "config1" {
  kafka_versions    = ["****"]
  name              = "${var.env}-mskconfig-${lower(random_id.rand.hex)}"
  server_properties = var.server_properties
}**

And here is my versions.tf file in the child module
**terraform {
  required_version = ">= 0.13"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 2.3.0"
    }
  }
}**

When I am calling this from the main deployment terraform module, its failing on me with:
Error: Invalid resource instance data in state
on .terraform/modules/kafka-msk/main.tf line 16:
16: resource "random_id" "rand" {
Instance module.kafka-msk.random_id.rand data could not be decoded from the
state: unsupported attribute "b64".

I exhausted all possible version setting scenarios and ended up here asking for help.

Let me know what am I missing here folks.

Thanks
Vikram Y

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
