### ISSUE TITLE
Incompatibility with go1.16

### ISSUE THREAD

**Issue by josephzidell** [hashicorp/terraform#28079]
Running `go get github.com/hashicorp/terraform@v0.14.8` in go1.16 fails

### Terraform Version

```
Terraform v0.14.8
```

### Terraform Configuration Files

```terraform
N/A
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

It should have downloaded and installed the package(s)

### Actual Behavior

```shell
➜  terraform git:(master) go version
go version go1.16 darwin/amd64
➜  terraform git:(master) go get github.com/hashicorp/terraform@v0.14.8 
github.com/hashicorp/terraform imports
        github.com/hashicorp/terraform/backend/init imports
        github.com/hashicorp/terraform/backend/remote-state/kubernetes imports
        k8s.io/client-go/kubernetes/typed/coordination/v1: cannot find module providing package k8s.io/client-go/kubernetes/typed/coordination/v1
github.com/hashicorp/terraform imports
        github.com/hashicorp/terraform/backend/init imports
        github.com/hashicorp/terraform/backend/remote-state/kubernetes imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1 imports
        k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1
github.com/hashicorp/terraform imports
        github.com/hashicorp/terraform/backend/init imports
        github.com/hashicorp/terraform/backend/remote-state/kubernetes imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/auditregistration/v1alpha1 imports
        k8s.io/api/auditregistration/v1alpha1: cannot find module providing package k8s.io/api/auditregistration/v1alpha1
github.com/hashicorp/terraform imports
        github.com/hashicorp/terraform/backend/init imports
        github.com/hashicorp/terraform/backend/remote-state/kubernetes imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/settings/v1alpha1 imports
        k8s.io/api/settings/v1alpha1: cannot find module providing package k8s.io/api/settings/v1alpha1
go: warning: k8s.io/client-go@v10.0.0+incompatible: retracted by module author: pre-module versions are obsolete
go: to switch to the latest unretracted version, run:
        go get k8s.io/client-go@latest%
```

### Steps to Reproduce

1. Install go1.16
2. Try to install github.com/hashicorp/terraform@v0.14.8

### Additional Context

This behavior is observed in go1.16 and above. But in go1.15, this works as intended. This inconsistency was reproduced locally (Mac) as well as in Docker `golang:1.16-alpine3.13`. Also, I'm very new to terraform, so I could be missing something.

**Comment by jbardin** [comment]
Hi @josephzidell,

The `go get` command does not build the named package within the context of its module, leading to difference in the build process which may have produced binaries with the incorrect dependencies. In fact, the `get` command is being deprecated as a method for building `main` packages in general.

In go1.16 you can use `go install` to fetch and build most main packages, however that will not work for modules which require `replace` directives, which terraform does. The correct way to build the terraform project is to checkout the source and use `go install` or `go build` from the root directory. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by josephzidell** [comment]
@jbardin Appreciate your feedback! This issue exist even with the `-d` flag instructing `go get` not to build or install packages. 

```shell
go get -d -v github.com/hashicorp/terraform@v0.14.8
```

My Dockerfile follows this up with a `go install`

**Comment by jbardin** [comment]
`go get` is used for managing module dependencies, not for checking the code out of VCS. Since terraform is not intended to be used as a library, it is not guaranteed to be retrievable via `go get`.

**Comment by josephzidell** [comment]
I cloned it with git followed by `go install`, and everything works. Thanks!
