### ISSUE TITLE
Terraform CLI is required VSCODE

### ISSUE THREAD

**Issue by mikeblackk** [hashicorp/terraform#28081]
Hi guys,

I upgraded to 14.8 and everytime I open a tf file in visual code it prompts me with "Terraform (CLI) is required. Install terraform or make it available in $path" 

Checked Path its installed and it keeps prompting me - so annoying. any ideas?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
