### ISSUE TITLE
instance_template/Instance_Group-GCP---on main.tf line 34, in resource "google_compute_region_instance_group_manager" "mig": 34: instance_template = google_compute_instance_template.template.self_link  An argument named "instance_template" is not expected here.

### ISSUE THREAD

**Issue by balagaa** [hashicorp/terraform#28107]
Hi Team , 
Am creating the terraform "google_compute_instance_template" , "google_compute_region_instance_group_manager" . In that case am facing the issue as follows 

**************************************************************************************************************************************
Error: Unsupported argument

  on main.tf line 34, in resource "google_compute_region_instance_group_manager" "mig":
  34:   instance_template  = google_compute_instance_template.template.self_link

An argument named "instance_template" is not expected here.
***************************************************************************************************************************************
provider "google" {
  project = "xxxxxxx"
  credentials="auth.json"
  region  = "europe-west1"
  zone    = "europe-west1-b"
}

resource "google_compute_instance_template" "template" {
  name_prefix = "my-template-"

  machine_type = "n1-standard-1"
  region       = "us-central1"

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "MIGRATE"
  }

  disk {
    disk_type    = "pd-standard"
    source_image = "centos-7-v20190619"
    disk_size_gb = "100"
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_region_instance_group_manager" "mig" {
  name               = substr("my-mig-${md5(google_compute_instance_template.template.name)}", 0, 63)
  base_instance_name = "mig-instance"
  instance_template  = google_compute_instance_template.template.self_link
  region             = "us-central1"
  target_size        = 5
  wait_for_instances = true

  timeouts {
    create = "15m"
    update = "15m"
  }

  lifecycle {
    create_before_destroy = true
  }
}

**Comment by alisdair** [comment]
Hello!

[Looking at the Google provider docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager) shows that the `instance_template` argument should be enclosed in a `version` block. There are some examples of correct configuration in the docs which may help you resolve this error.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by balagaa** [comment]
Thanks alisdair , it is working fine now .. 
I want to create https load balancer from for the instance group i created ,, Am not able to find any IAC for this in terraform ... Can you please share any related links to in this ?
