### ISSUE TITLE
Option to not error when showing a stale Terraform plan

### ISSUE THREAD

**Issue by zachwhaley** [hashicorp/terraform#28136]
### Current Terraform Version

```
Terraform v0.14.8
```

### Use-cases

We use Terraform plan in our PR pipelines to get an idea what infrastructure changes a given code change will make.  We use the commands `terrafom plan -lock=false` and `terraform show -no-color > tfplan.txt` to create a plan and save that plan in a human readable file.

Sometimes, during a plan for a PR there is actually an apply happening in Production which means that the final plan for that PR will be stale and this causes the `terraform show` command to fail with the following `Error: Saved plan is stale`

### Attempted Solutions
I'm not aware of any way around this.

### Proposal
In our use case, we have no intention of ever applying the plans generated from the PR pipeline but would still like to be able to see the plan with possibly a warning that the plan is stale.

Our proposal is to allow `terraform show` to display stale plans, with either an option or by default, with a warning that the given plan is stale.  Note, obviously `terraform apply` should fail to apply a stale plan.

### References
NA

**Comment by apparentlymart** [comment]
Hi @zachwhaley! Thanks for sharing this use-case.

The behavior you're talking about here is a long-standing one and so although I think I was involved in implementing it I'm sorry to say I've lost some of the historical context to time and so I'm trying to recall what I can to think about this.

With that caveat in mind, I _think_ this behavior with `terraform show` just results from that command sharing various logic with the `terraform apply` command given that they both have to deal with the non-trivial process of loading a saved plan file from disk. I can't think of a strong reason why `terraform show` _must_ do this check, since as you point out it exists only to view the saved artifact and doesn't itself have any side-effects that call for us to ensure a correct ordering of operations.

Given that, unless we later identify a compelling use-case for retaining this check, I'd prefer to approach this as removing the unnecessary in all cases, rather than making it an opt-out. I've not dug into the code to see how severe a change that might be, and I assume it will require some refactoring that we'll need to consider carefully, but implementation details aside what you described here seems like the best default behavior.

Even if we _do_ find a use-case for retaining the check, I think it would make more sense for it to be an _opt-in_ check rather than an _opt-out_, because asking "Is this plan applyable?" without actually applying it seems like a pretty unusual need and one that would need the help of some externally-managed locking mechanism to ensure that the answer to that question doesn't become invalid before a subsequent `terraform apply` anyway.

**Comment by zachwhaley** [comment]
@apparentlymart I was looking at this again and found something I thought was interesting.

It seems like the failure occurs before the `show` command even tries to show the plan, instead erroring when it constructs a _context_ from the plan file.

https://github.com/hashicorp/terraform/blob/main/internal/command/show.go#L103-L109

https://github.com/hashicorp/terraform/blob/main/internal/backend/local/backend_local.go#L88-L102

https://github.com/hashicorp/terraform/blob/main/internal/backend/local/backend_local.go#L217-L231

From what I've gleamed looking at the source code, it seems like this issue's desired outcome could be accomplished by using a _backend_ during the show command that does not use a PersistentMeta state manager 🤷🏻

**Comment by alisdair** [comment]
This issue is fixed as of #30205, which was released as part of Terraform 1.1.3.
