### ISSUE TITLE
Using remote exec on multiple EC2 instances

### ISSUE THREAD

**Issue by pocockn** [hashicorp/terraform#28154]
### Terraform Version

```
Terraform v0.14.8
```

### Terraform Configuration Files

```terraform
resource "aws_instance" "huski" {
  count = var.node_count

  ami = data.aws_ami.ecs.id
  associate_public_ip_address = true
  iam_instance_profile = aws_iam_instance_profile.huski_ec2.name
  instance_type = "t2.micro"
  key_name = format("huski_%d", count.index)
  subnet_id = element(var.vpc_public_subnets, 0)

  vpc_security_group_ids = [
	aws_security_group.huski.id]

  lifecycle {
	create_before_destroy = true
	prevent_destroy = false
  }

  depends_on = [
	aws_key_pair.generated_key
  ]

  user_data = join("\n",
  [
	"#!/bin/bash\necho ECS_CLUSTER=${var.ecs_cluster_name} > /etc/ecs/ecs.config",
	data.template_file.script[count.index].rendered
  ])

  provisioner "file" {
	source = format("nodes/node_%d", count.index)
	destination = "/var/tmp"

	connection {
	  type = "ssh"
	  user = "ec2-user"
	  private_key = tls_private_key.huski[count.index].private_key_pem
	  host = self.public_ip
	}
  }

  tags = {
	Name = format("%d-huski-terraform", count.index)
  }
}

resource "null_resource" "move_files" {
  count = var.node_count

  provisioner "remote-exec" {
	inline = [
	  "sudo mv -v ${format("/var/tmp/node_%d/", count.index)} /mnt/efs_node_data/",
	]

	connection {
	  type = "ssh"
	  user = "ec2-user"
	  private_key = tls_private_key.huski[count.index].private_key_pem
	  host = aws_instance.huski[count.index].public_ip
	}
  }

  depends_on = [
	aws_instance.huski
  ]
}
```

### Expected Behavior

Terraform should upload the directories from my local machine to each EC2 instances under `var/tmp` and then should move them to the EFS mount directory.

### Actual Behavior

The directories get successfully uploaded to each EC2 instance's` var/tmp` folder but when we get to the `remote-exec` stage and it attempts to move the files they seem to be removed from the instance.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @pocockn! I'm sorry this didn't work as expected.

From what you've described it sounds like when you applied this configuration you saw the remote-exec provisioner associated with `null_resource.move_files` fail, in a way that suggests that the files previously uploaded don't exist.

Terraform never directly interacts with files in a remote VM except as directed by you in provisioners, so it seems like something strange is happening here but I don't expect that it's a bug in `remote-exec`, because `remote-exec` is only responsible for executing the command you provided exactly as you provided it, and so it can't do anything to ensure that the commands you provided are valid.

It seems like understanding what's happening here is going to require some deeper discussion and debugging, so I'd like to discuss this as a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) instead of as a GitHub issue, because it's easier to have an open-ended discussion over there. If our discussion leads to the indication of a bug in Terraform then we can always reopen this issue or start a new one based on what we've learned. If you do choose to open a topic in the community forum, it would be helpful to include not only the configuration example you shared here but also the output you saw from `terraform apply`, including the exact error messages it printed, so that folks might have a starting point to understand where to debug first.

Thanks!
