### ISSUE TITLE
A function to create maps from lists where the key is the index of the elements in the list

### ISSUE THREAD

**Issue by triarius** [hashicorp/terraform#28155]
### Current Terraform Version

```
0.14.8
```

### Use-cases

When writing terraform with sufficient complexity, there is often need to create a resource for each element of a list of values that are attributes of other data sources or resources that can only be known after an apply. Because the `for_each` meta-attribute does not accept lists as values, the standard approach has been apply the `toset` function. However, it is not possible to from a set from a list without knowing the value of the elements of the list so instead of forming the list, terraform errors out with a message similar to the following:
```
Error: Invalid for_each argument

   on ../modules/asg/main.tf line 90, in resource
"aws_iam_role_policy_attachment" "attach_policies_in_list":
  90:   for_each = toset(var.policy_arns)

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the resources
that the for_each depends on.
```
This would have been be generated by attempting to plan or apply syntax similar to the following:

```hcl
# list of arns for aws_iam_policies that are declared in a different module
var policy_arns {
    type = list(string)
}

resource aws_iam_role_policy_attachment attach_policies_in_list {
  # would force the use of -target as it needs to eagerly evaluate the
  # values in the list for form a set from it, so avoid using it
  for_each = toset(var.policy_arns)

  policy_arn = each.value
  role       = aws_iam_role.my_role.name
}
```

While the acceptance of a set instead of a list allows for the resources to be uniquely identified, it is not necessary to identify them by a value that can only be known after an apply. Instead, the following syntax achieves the same effects without necessitating two passes of `apply`.

### Attempted Solutions

```hcl
# list of arns for aws_iam_policies that are declared in a different module
var policy_arns {
    type = list(string)
}

resource aws_iam_role_policy_attachment attach_policies_in_list {
  # does not force the use of -target as the map may be created lazily
  for_each = { for i, v in var.policy_arns: i => v }

  policy_arn = each.value
  role       = aws_iam_role.my_role.name
}
```
While on one level this is a perfectly acceptable state of affairs, the official documentation of `for_each` does not mention this, and many people therefore only use the `toset` syntax. They then encounter the error and erroneously conclude that it is bug in terraform and, perhaps encouraged by comments in https://github.com/hashicorp/terraform/issues/4149, resort to wrapping the terraform cli in other tooling to apply their plans in two passes.

I believe that at the very least, adding such an example to the documentation will provide significant value to the terraform community and be in line with the sentiments expressed in https://github.com/hashicorp/terraform/issues/26078#issuecomment-713546946. It should be noted that there are also very similar issues for cases where the length of the list could not be known until apply time, but I am NOT proposing doing anything to address that situation. (See https://github.com/hashicorp/terraform/issues/26078, https://github.com/hashicorp/terraform/issues/26682).

### Proposal

I propose that we achieve similar ergonomics to the `toset` syntax and add a function to create this map to terraform itself. I have chosen the placeholder name `listtomap`, but discussion about what to name such a function is perhaps warranted.

With such a function, the syntax will then be:
```hcl
# list of arns for aws_iam_policies that are declared in a different module
var policy_arns {
    type = list(string)
}

resource aws_iam_role_policy_attachment attach_policies_in_list {
  # does not force the use of -target as the map may be created lazily
  for_each = listtomap(var.policy_arns)

  policy_arn = each.value
  role       = aws_iam_role.my_role.name
}
```

### References

- #26078
- #26682
- #4149

**Comment by apparentlymart** [comment]
Hi @triarius! Thanks for sharing these use-cases.

For situations where identifying instances by position in a list is acceptable, the typical approach is to use [`count`](https://www.terraform.io/docs/language/meta-arguments/count.html) which will then cause Terraform to use integers to track the instances, rather than strings:

```hcl
var "policy_arns" {
    type = list(string)
}

resource "aws_iam_role_policy_attachment" "attach_policies_in_list" {
  count = length(var.policy_arns)

  policy_arn = var.policy_arns[count.index]
  role       = aws_iam_role.my_role.name
}
```

Of course, the documentation section [When to Use `for_each` Instead of `count`](https://www.terraform.io/docs/language/meta-arguments/count.html#when-to-use-for_each-instead-of-count) gives some good reasons to avoid doing this and to use `for_each` instead.

However, using `for_each` in the way you described (with the keys set to decimal representations of the list indices) would have all of the same caveats as using `count`, so I don't think it would be justified to recommend that pattern in the documentation, or to implement a function to encourage doing it, while simultaneously recommending _against_ what is essentially the same thing.

For situations like yours where the values are derived from resource attributes that won't be known until apply, our typical suggestion is to have the caller pass those in as a map rather than as a set, and then the module caller can be the one to choose suitable instance keys for them, rather than the module choosing for them:

```hcl
var "policy_arns" {
    type = map(string)
}

resource "aws_iam_role_policy_attachment" "attach_policies_in_list" {
  for_each = var.policy_arns

  policy_arn = each.value
  role       = aws_iam_role.my_role.name
}
```

For configurations that make broad use of `for_each` it's typical to start with a set of keys that are defined statically in the root module and which are then used in various maps throughout he rest of the configuration, so that all of the objects declared across different modules all use correlated keys. That sort of "big picture" information about the interaction of many separate language features doesn't really fit well into our reference documentation format that most of `terraform.io` consists of, and so that sort of content typically appears in guides on `learn.hashicorp.com` instead. It looks like the [Manage Similar Resources with `for_each`](https://learn.hashicorp.com/tutorials/terraform/for-each) guide illustrates this at least in part, showing the flow of sets of keys or of maps using those keys into and out of modules.

Perhaps there are some opportunities to expand that guide or add additional guides to make this design pattern more visible. We could also consider linking to the guide directly from the _When to Use `for_each` Instead of `count`_ documentation section I mentioned earlier, to present it as part of the alternative to that `count` pattern.

**Comment by triarius** [comment]
Thanks for the quick response @apparentlymart you have convinced me that using `count` and indexing the variable directly is a acceptable solution, so I think this proposal is now unnecessary. I think passing the map from the module's var has many benefits if you one day have manually manipulate the state, but users of the module would arguably be confused if the module exposes what to them seems like an implementation detail. So I will use the `count` pattern in my terraform for now instead.
