### ISSUE TITLE
Reference env variables inside tfvars file.

### ISSUE THREAD

**Issue by vchouhan** [hashicorp/terraform#28182]
@apparentlymart The problem is when these _constants_ need to refer to a value that is only available after the variables are all loaded. e.g. Imagine a common scenario where one team provides the terraforming definitions and other teams provide only tfvars. It may be the case that the team providing only the tfvars needs to know something about the environment in which it is running, for example a resource name of id, so that it can assign that to a variable the tfvars-team owns. e.g. a `terraform.tfvars` like:

    env = {
      MY_ELB_IP = "${local.ELB_IP}"
    }

The tfvars-team knows they need to IP address of the ELB and they want to name it `MY_ELB_IP` in their environment. The terraforming-teams can add this user-map to some other resource and without needing to know that the tfvars-team needs access to a particular value.

All that would really be needed is for something like the `to*` functions to provide an option to perform interpolation. Then the terraforming-team can refer to `env` as `tomap(var.env, true)`.

2¢

_Originally posted by @nicerobot in https://github.com/hashicorp/terraform/issues/17229#issuecomment-505531298_

This is exactly my use case. I am being provided the API keys as env variables and I need to reference them into my tfvars file. How would I go about referencing the env variables inside tfvar files?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
