### ISSUE TITLE
CBD side effect that "update depending resource first then delete depended resource" not work since v0.14

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#28193]
As is mentioned [here](https://github.com/hashicorp/terraform/pull/24662#issuecomment-653007506), there is a side effect of CBD: Given resource `A` depends on `B`, if users delete `B` and in the same time update `A` to remove the depending property in the config file, the default `apply` order will be `B (destroy) -> A (update)`, which might cause issues for `B (destroy)` (complaining `B` is still under used by `A`). While if the user specify CBD in resource `A`, the order will be `A (update) -> B (destroy)` in v0.13.

However, this is not the case since v0.14.

### Terraform Version

```
v0.14.0+
```

### Terraform Configuration Files

Given following config:

```hcl
resource "demo_resource_foo" "magodo" {
  name = "magodo"
  job = "xxx"
}

resource "demo_resource_foo" "kinoko" {
  name = "kinoko"
  job = demo_resource_foo.magodo.job
  lifecycle {
    create_before_destroy = true
  }
}
```

If we change it to:

```hcl
resource "demo_resource_foo" "kinoko" {
  name = "kinoko"
  #job = demo_resource_foo.magodo.job
  lifecycle {
    create_before_destroy = true
  }
}
```

Then run `terraform apply`, the output would be:

(expected)

```bash
💤 terraform-0.13.5 apply -auto-approve
demo_resource_foo.magodo: Refreshing state... [id=magodo]
demo_resource_foo.kinoko: Refreshing state... [id=kinoko]
demo_resource_foo.kinoko: Modifying... [id=kinoko]
demo_resource_foo.kinoko: Modifications complete after 0s [id=kinoko]
demo_resource_foo.magodo: Destroying... [id=magodo]
demo_resource_foo.magodo: Destruction complete after 0s
```

(unexpected)

```bash
💤 terraform-0.14.9 apply -auto-approve
demo_resource_foo.magodo: Refreshing state... [id=magodo]
demo_resource_foo.kinoko: Refreshing state... [id=kinoko]
demo_resource_foo.magodo: Destroying... [id=magodo]
demo_resource_foo.magodo: Destruction complete after 0s
demo_resource_foo.kinoko: Modifying... [id=kinoko]
demo_resource_foo.kinoko: Modifications complete after 0s [id=kinoko]

Apply complete! Resources: 0 added, 1 changed, 1 destroyed.
```

**Comment by jbardin** [comment]
Thanks for filing the issue @magodo!

While we have tests for verifying that this dependency works, there was nothing that encompassed a full refresh+plan+apply cycle, which is where the problems now lies.

I believe what has happened here, is that in order to actually remove old dependencies and allow refactoring of configuration, the refresh process needs to be able to update the stored dependencies, but those can only be determined from the configuration. Running a quick check with 0.13 confirms that if you wanted to restructure the configuration such that the store dependency became invalid, there would be no way to move forward because dependencies were only treated as additive until a successful apply. 

This leaves us with the problem of how to decide when the stored dependencies are still correct even if the configuration declares otherwise (which is essentially what is happening here). Now that refreshing is happening during the plan itself, I think we have enough information to make this determination, and can take care of both use cases simultaneously in 0.15.
