### ISSUE TITLE
spec.deviceChange.device.port.switchUuid

### ISSUE THREAD

**Issue by cfaria929** [hashicorp/terraform#28198]
### Terraform Version

```
... Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/vsphere v1.25.0
```

### Terraform Configuration Files

```terraform
...
https://github.com/cfaria929/Terraform_Bug
```

### Debug Output

https://github.com/cfaria929/mygit/blob/master/terraform.txt
### Expected Behavior

When Deploying the OVF the VM should attach to the port group as defined 
### Actual Behavior

Job Fails with "deploy error: An invalid argument "spec.deviceChange.device.port.switchUuid" was specified.
2021/03/05 12:03:53 [TRACE] eval: *terraform.EvalMaybeTainted"
### Steps to Reproduce

1. terraform init
2. terraform plan -out app06
3. terraform apply "app06"

### Additional Context

The build is pointed at Vcenter 6.7, running VM Clusters with two VDS. 1 VDS is 6.7.0 and the 2nd is running 6.0.0.
1st VDS has all cluster host attached and isolated to the cluster
 
Datacenter 1
- Cluster 1 VDS 6.7.0
- Host1
- Host2
- Host3
- Host4
- Host5

- Cluster 2 VDS 6.7.0
- Host1
- Host2
- Host3
- Host4
- Host5

- Cluster 3 VDS 6.7.0
- Host1
- 
- Host2
- Host3
- Host4
- Host5

2nd VDS has multiple host that span the datacenter, version is set to 6.0 to allow for live migrations from legacy environments not running the 6.7 VDS

Datacenter 1 - VDS 6.0.0

- Host5 Cluster 1
- Host5 Cluster 2
- Host5 Cluster 3

When the Job runs and fails 
Host 01. is not a member of VDS Datacenter 1 VSANMigTemp

Repeated runs of the job will be successful when the host is part of both VDS
Created virtual machine NEW_VM on Host5 in Vcenter

I have attempted to add the following code to main.tf to get call for the VDS 6.7.0 Where the new vm is to be deployed
data "vsphere_distributed_virtual_switch" "dvs" {
  name          = var.DSwitch
  datacenter_id = data.vsphere_datacenter.dc.id
}
While not in the code posted here the end result was the same Failure and Success as stated. If the build lands on the host that resides in both VDS all is well. Problem is that is 1 out of 5.

**Comment by apparentlymart** [comment]
Hi @cfaria929! I'm sorry you encountered this error.

Unfortunately based on the log you shared it seems like this error is being returned by the vsphere provider rather than by Terraform itself:

```
2021/03/05 12:03:53 [DEBUG] vsphere_virtual_machine.vm[1]: apply errored, but we're indicating that via the Error pointer rather than returning it: deploy error: An invalid argument "spec.deviceChange.device.port.switchUuid" was specified.
```

The full details of this error message are talking about some implementations of Terraform itself (that it treats this particular error as a special case to ensure that it can subsequently be saved to the state as tainted if needed) but regardless of those details Terraform only reports an error in this way if the provider returned it as part of the delegated call to apply the plan.

The team which maintains Terraform CLI/Core in this repository is unfortunately not familiar with the details of vSphere or the vSphere provider, so I'm afraid I'm going to have to ask you to open a new version of this issue in [the vSphere provider repository](https://github.com/hashicorp/terraform-provider-vsphere) so that the vSphere provider team will see it and will hopefully understand better what is causing it.

Since there isn't anything we could change in this repository to improve this situation, I'm going to close this issue. Thanks!

**Comment by cfaria929** [comment]
Thank you, and Totally understand.
