### ISSUE TITLE
Terraform plan failed with Forbidden error 403

### ISSUE THREAD

**Issue by soumitasardar** [hashicorp/terraform#28203]
s3 bucket and folders are being created from terraform code. everything was working fine.
But all of sudden when trying to create a object under one existing object or folder. 
The **terraform plan** is giving error:
```
Error: Forbidden: Forbidden
	status code: 403, request id: 1FNQVF3ZV111RRYK, host id: KG6nxkbA9a5nnZ0xxxxxxxxxxxxxxxxxxxx6p5ClxiHfTQ1wDnv0ngO+bF1zYCxw=
```
 IAM user policy if having:
```
{
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action":  "s3:*",
            "Resource": "*"
        }
```
Terraform version: v0.12.23
The code was working till March 19th 2021. But suddenly facing issue.

Can anyone please help in the issue. Not even getting exact reason for the error.

**Comment by apparentlymart** [comment]
Hi @soumitasardar,

Is there any other output from Terraform before it prints this error? That could help to understand what part of Terraform's work is failing here.

Our issue template includes a request to share trace-level logs for the operation that failed, which is typically the best way for us to understand how an unexpected error like this occurred. I'm going to copy in the instructions you deleted from the template so you can see them here; if you can do this and share the result in a new comment that would make it much more likely that we'll be able to understand what Terraform was doing when it encountered this error:

> Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a [GitHub Gist](https://gist.github.com/) containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.
>
> Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.

**Comment by soumitasardar** [comment]
Hi @apparentlymart ,

Thanks for your response!

Please fine the `tf_log=trace` logs in the given Github gist
[https://gist.github.com/soumitasardar/3fbc4364c41a303cd0d19fdf15541081](url)

Will looking for your help to understand the reason and solution.

Thanks

**Comment by jbardin** [comment]
Hi @soumitasardar,

The error you seeing is coming from the AWSS provider, meaning that it's is attempting to access something which your account does not have permission to access. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
