### ISSUE TITLE
Configured gcloud cli with my organizational account, but when I m running terraform init from the cli it's picking up my personal mail, 

### ISSUE THREAD

**Issue by saichebrolu006** [hashicorp/terraform#28250]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by saichebrolu006** [comment]
Failed to get existing workspaces: querying Cloud Storage failed: googleapi: Error 403: personal-email@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
