### ISSUE TITLE
jsondecode

### ISSUE THREAD

**Issue by MarcoLagalla** [hashicorp/terraform#28262]
Hi, 
I am trying to populate a template, read with the "template" function, and then rendered as JSON using "jsondecode".
If the string inserted into the template contains an escape char, like: "foo\mvjfo]".
Then, the **\m** leads to the error below.

### Terraform Version

```
0.14
```

### Crash Output

```
Call to function "jsondecode" failed: invalid character 'm' in string escape
code.
```

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
