### ISSUE TITLE
Store values of sensitive variables as SHA hashes in Terraform state

### ISSUE THREAD

**Issue by Yakuza-UA** [hashicorp/terraform#28263]
### Current Terraform Version

```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Use-cases

Currently sensitive data is stored in a clear text within state files. However, according to the documentation, the only reason for this is to be able to track if this data has changed from the perspective of the state. By hashing this data, it will be obfuscated from potential eavesdropper. At the same time any change in the value will force hash to change and as such will signal Terraform that state has changed.

Unless there's a very good reason not to do this? Just trying to understand whys.

### Attempted Solutions

N/A

### Proposal

Apply hashing function of your choice to values of sensitive variables before storing this data in a state file(s)

**Comment by jbardin** [comment]
Hi @Yakuza-UA 

Thanks for filing the proposal. Since variables themselves are not stored in state I assume you are referring to sensitive resource attributes and root modules outputs. Unfortunately in order for terraform to operate, it needs access to the original values. Most attributes returned by resources are returned for a reason, either because they need that data to be sent back later for future API calls, or because other resources may need to reference those fields. If the data is turned into opaque hash value, then neither of those operations can be done. 

We have ideas around both encrypting states a whole (#9556), and on a finer-grained level with individual values (#516). Since we already have multiple proposal in the works already, I'm going to close this out a duplicate. 

Thanks!

**Comment by Yakuza-UA** [comment]
Thank you @jbardin

**Comment by byarbrough** [comment]
@jbardin I was actually about to open an issue with the same title.

From my understanding, aside from metadata, there are four classes of values stored in state files:

|                                  | **Supplied Input**                 | **Known After Apply**              |
|----------------------------|----------------------------------|--------------------------------------|
| **Can be refreshed by API call**      | Tags, CIDR blocks, ect. | IDs of associated vpc, ip, ect. |
| **Cannot be refreshed** | Passwords                     | ID used as input for API        |

Values that are an output of an `apply` and values that are used as inputs to API calls of course have to remain plaintext. But storing passwords in plaintext is heinous, even if the entire state is encrypted.

If every variable marked `sensitive` is hashed before being stored in state, then subsequent plans can simply hash the input value before comparing it to the stored hash. If the hashes do not match, then a change is required. The new value is guaranteed to be available because it is being supplied as an input! There is no need to know the old value.

Consider this example from the [tutorials](https://learn.hashicorp.com/tutorials/terraform/sensitive-variables):
```terraform
variable "db_password" {
  description = "Database administrator password"
  type        = string
  sensitive   = true
}

resource "aws_db_instance" "database" {
  allocated_storage    = 5
  engine               = "mysql"
  instance_class       = "db.t2.micro"
  username             = "admin"
  password             = var.db_password
  name                 = "testingdb"
  db_subnet_group_name = aws_db_subnet_group.private.name

  skip_final_snapshot = true
}
```
Upon apply, the state will save the `password`, but because AWS does not have an API for retrieving the password (nor, I hope, does AWS even save it in plaintext) the password is not refreshed on subsequent plans. You can prove this by manually changing the value in the state and conducting a `refresh` - no change occurs.

**Comment by jbardin** [comment]
Hi @byarbrough,

I think the issue with what you are proposing stems from the misconception about "classes" of attributes, the provider schema has no concept of an attribute that can or cannot be refreshed, and all attributes are technically valid for a provider to refresh. The only classification for control over attributes is the "computed" flag, which determines _when_ a resource is allowed to alter the value (we have a doc showing the overall lifecycle rules in [Resource Instance Change Lifecycle](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md)). 

There is also no differentiation between an attribute that is only needed during create, on refresh, on update, or on destroy (and for destroy it means the data _must_ be stored in state unaltered). While the idea of setting a system `password` seems applicable only on the first apply, there are many other cases where sensitive values are required for every API call, and in fact experience has shown that a large portion of sensitive values are regularly needed by the providers.

This means that a new provider API and schema would need to be designed which allows a resource to declare the lifecycle of each attribute, and allow various attributes to be obfuscated or elided in the protocol. Aside from the major changes this would introduce, it still would not allow the hashing of _all_ sensitive values in the state, which either introduces levels of "sensitivity" putting us back at the original problem, or fails to secure the data overall. 

As you can see it's not impossible, but it's going to set a pretty high bar for what amounts to only a partial solution. IN the meantime securing the state as a whole has proven sufficient for most users, and we are still working on various ideas from the linked open issue above.

**Comment by byarbrough** [comment]
@jbardin Thank you for the thorough reply and the link to the extended doc - that's much more in-depth and useful to me than the main CLI docs!
