### ISSUE TITLE
Template resource breaks bash patterns / code portability

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#28280]
Using the file template module for user data in terraform creates problems with bash portability.  It overrides single curly braces syntax and presumes that strings contained in braces be replaced, when often it shouldn't.  I apologise if I'm wrong about this, if I am it would be helpful to see some docs on solutions to these problems.

1. Take this example function:
```
function log {
  local -r level="$1"
  local -r message="$2"
  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  >&2 log -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}
```
This would normally be fine in bash, but terraform complains that the vars in {} has not been defined.

2. The design constraint also creates problems like:
```
"${somevarA}_suffix"
```
When if the var is set in the script itself (not from terraform), we would be forced to do this:
```
"$somevarA_suffix"
```
...Which isn't valid.

3. There are other functions with curly brackets in bash that probably become ambiguous, like removing a file extension:
```
"${somfe_file_name%.*}"
```
I'm not sure how this is handled honestly...

Although I can see in many scenarios, where a bash script is written for this purpose of being used in a template from scratch it is ok, however I think an option like this would be helpful in the template block:
```
only_replace_within="{{_}}"
```
where the default would be "{_}"

This would allow a user to explicitly define where replacement occurs, and where standard bash functionality can be conserved.

**Comment by jbardin** [comment]
Hi @queglay 

The `${` sequence can be escaped in the Terraform language by using the `$${` escape sequence, shown here: https://www.terraform.io/docs/language/expressions/strings.html#escape-sequences

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by queglay** [comment]
This is a feature request.  Using `$${` by default in bash scripts also breaks portability, terraform requires it, and therefor, the scripts can't be used elsewhere.

That behaviour should be opt in, not opt out.  so I'd like to suggest string replacement should only replacing vars contained in `$${`, and not in all instances of `{}`
