### ISSUE TITLE
Garbage collection for old providers

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform#28286]
### Current Terraform Version

```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/dns v3.1.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
```

### Use-cases

I was a bit surprised to see my Terraform projects were at the top of my largest project working directories and then noticed that Terraform doesn't remove old providers when you upgrade. This means that over time my projects end up with a sizable historical archive of all versions of the provider which have ever been used. This adds up quickly since the larger providers for AWS, GCP, etc. are relatively large files.

```
 14M	./.terraform/providers/registry.terraform.io/hashicorp/http/2.1.0
 14M	./.terraform/providers/registry.terraform.io/hashicorp/http/2.1.0/darwin_amd64
 16M	./.terraform/providers/registry.terraform.io/hashicorp/http/2.0.0
 16M	./.terraform/providers/registry.terraform.io/hashicorp/http/2.0.0/darwin_amd64
 22M	./.terraform/providers/registry.terraform.io/hashicorp/dns/3.1.0
 22M	./.terraform/providers/registry.terraform.io/hashicorp/dns/3.1.0/darwin_amd64
 28M	./.terraform/providers/registry.terraform.io/hashicorp/dns/3.0.0
 28M	./.terraform/providers/registry.terraform.io/hashicorp/dns/3.0.0/darwin_amd64
 28M	./.terraform/providers/registry.terraform.io/hashicorp/dns/3.0.1
 28M	./.terraform/providers/registry.terraform.io/hashicorp/dns/3.0.1/darwin_amd64
 30M	./.terraform/providers/registry.terraform.io/hashicorp/http
 79M	./.terraform/providers/registry.terraform.io/hashicorp/dns
194M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.33.0
194M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.33.0/darwin_amd64
194M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.34.0
194M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.34.0/darwin_amd64
194M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.35.0
194M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.35.0/darwin_amd64
200M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.32.0
200M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.32.0/darwin_amd64
202M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.26.0
202M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.26.0/darwin_amd64
204M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.22.0
204M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.22.0/darwin_amd64
207M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.27.0
207M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.27.0/darwin_amd64
207M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.28.0
207M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.28.0/darwin_amd64
212M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.21.0
212M	./.terraform/providers/registry.terraform.io/hashicorp/aws/3.21.0/darwin_amd64
1.8G	./.terraform/providers/registry.terraform.io/hashicorp/aws
```

### Proposal

* `terraform init` should remove any provider which is not the currently-pinned version or, perhaps, more than a certain amount of time old to accommodate switching branches around upgrades.
* Terraform could use the global cache directory to store providers so they wouldn't be copied per-project and garbage-collect when the access time is more than n days in the past. This would be the greatest space savings but probably also a substantial amount of extra work and risk, likely with a fair chance to make a security-impacting mistake, so I'm not sure it's worth the extra time.

**Comment by apparentlymart** [comment]
Hi @acdha,

For your second point, Terraform already does attempt to create a symlink instead of a full copy when it's using a plugin from the global cache, although it will fall back to creating a full copy if symlinking fails for any reason.

While we certainly can consider making Terraform automatically delete old versions from the local cache directory (`.terraform/providers`) when installing new versions, turning on the global cache and making sure that Terraform has access to create symbolic links could be a way to get closer to what you wanted for now, since at least then the per-directory local caches would be relatively small (just symlink metadata) and you'll only have the global cache directory to worry about.

If you're only using a few providers and you're not on a metered Internet connection then you can also consider deleting that `.terraform/providers` directory and then running `terraform init` again, which will cause Terraform to re-download (or re-link/copy from global cache) only the providers that configuration is currently using.

I think lots of folks don't run into this because once running Terraform "in production" teams typically run it in some sort of automation that runs in temporary, throwaway working directories and thus they are starting over with an entirely new `.terraform/providers` each time. However, I do agree that it would be helpful for Terraform to clean up after itself if we can come up with a suitable definition of when it's safe to do so, for the benefit of those who are using (and re-using) long-lived working directories on a local machine, such as during module development.

**Comment by acdha** [comment]
> Hi @acdha,
> 
> For your second point, Terraform already does attempt to create a symlink instead of a full copy when it's using a plugin from the global cache, although it will fall back to creating a full copy if symlinking fails for any reason.

Interesting, this is apparently pretty silent since I had something like ~14GB of Terraform providers stacking up on this system. Any pointers on how to diagnose that? If that worked, I'd consider this less of an issue since 1 copy per version would be considerably smaller.

> I think lots of folks don't run into this because once running Terraform "in production" teams typically run it in some sort of automation that runs in temporary, throwaway working directories and thus they are starting over with an entirely new `.terraform/providers` each time. However, I do agree that it would be helpful for Terraform to clean up after itself if we can come up with a suitable definition of when it's safe to do so, for the benefit of those who are using (and re-using) long-lived working directories on a local machine, such as during module development.

That's exactly the scenario I'm in: I develop locally and then push to a GitLab server which has credentials for the other environments.

**Comment by apparentlymart** [comment]
If you run `terraform init` with the environment variable `TF_LOG=trace` set then it should print out various diagnostic information. The messages there are primarily aimed at being shared verbatim as part of bug reports and interpreted by folks on the Terraform Core development team, but at least for `terraform init` it should hopefully be reasonably clear what it's doing from what it describes. If you see something in there which seems confusing/unexpected, if you can share the full output you saw in a [gist](https://gist.github.com/) linked into a comment here then I'd be happy to interpret it myself and see what's going on.

The normal `terraform init` output does indeed not distinguish between "I'm linking from the cache" and "I'm copying from the cache", because that fallback to copying happens pretty deep inside the provider installer where the UI code can't see it, but the trace log should hopefully say something about it.

**Comment by acdha** [comment]
Thanks — I apparently had some partial config as I had `$HOME/.terraform.d/plugin-cache`  and it's looking for `$HOME/.terraform.d/plugins`. The directions at  [Implied Local Mirror Directories](https://www.terraform.io/docs/cli/config/config-file.html#implied-local-mirror-directories) are certainly clear enough on that point and it's working now:

```
2021/04/13 16:37:12 [DEBUG] will search for provider plugins in /Users/cadams/.terraform.d/plugins
2021/04/13 16:37:12 [TRACE] getproviders.SearchLocalDirectory: /Users/cadams/.terraform.d/plugins is a symlink to /Users/cadams/.terraform.d/plugins
```

One oddity there is that `getproviders.SearchLocalDirectory` always logs that inaccurate "is a symlink to" message — note  that the source and destination are always the same and not a symlink. If I do not have the plugins directory set, it'll display `getproviders.SearchLocalDirectory: . is a symlink to .`
