### ISSUE TITLE
Terraform State Pull not working

### ISSUE THREAD

**Issue by ElAouane** [hashicorp/terraform#28290]
Hello Everyone. I am facing a weird behaviour from Terraform. I have been using Terraform to build and maintain our cloud infra on Azure. I have a backend configured to save the terraform.tfstate in a storage account in azure. Since yesterday everything was working fine, I was able to update my infra without any issue. But today, when I put in place some update and run `terraform plan` terraform tried to re-create all the resource, it just ignores my remote state. If I do a `terraform state pull` I can see my resources in the terminal, but those don't get saved in the local testate (which is empty now in all my projects)

### Terraform Version
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
```

### Expected Behavior
Update my infra and see only the changes without terraform trying to create all the resources.

### Actual Behavior
I have 4 resources created in the past and saved in the remote state on azure, today I tried to update some configurations and when ii run `terraform plan` the output tries to create all the resource instead of updating them.

### Steps to Reproduce
Unfortunately I cannot share my code as it is proprietary and contains a lot of sensitive data.

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
