### ISSUE TITLE
backend/http: credentials saved in plan file

### ISSUE THREAD

**Issue by fabiomatavelli** [hashicorp/terraform#28294]
Hello,

I noticed that when running the `terraform plan -out=terraform.tfplan`, the configurations of the backend are saved in the plan file, especially the username/password. 

This is a problem when you try to apply the plan with `terraform apply terraform.tfplan` using a CI/CD, if you use different jobs for plan and apply and use job-specific token for authentication (e.g. Gitlab CI/CD pipelines) in the backend. Since the jobs are different, the token will be a different one also.

### Terraform Version

```
Terraform v0.14.9
```

### Terraform Configuration Files

```terraform
terraform {
  backend "http" {}
}
```

Pass the backend config over `terraform init`:

```bash
export TF_ADDRESS="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}"
terraform init \
    -input=false \
    -reconfigure \
    -backend-config="address=${TF_ADDRESS}" \
    -backend-config="lock_address=${TF_ADDRESS}/lock" \
    -backend-config="unlock_address=${TF_ADDRESS}/lock" \
    -backend-config="username=gitlab-ci-token" \
    -backend-config="password=${CI_JOB_TOKEN}" \
    -backend-config="lock_method=POST" \
    -backend-config="unlock_method=DELETE" \
    -backend-config="retry_wait_min=5"
```

### Expected Behavior

When passing a saved plan to `terraform apply` but with different credentials for the http backend, the terraform should be able to authenticate and save the state into the backend.

### Actual Behavior

When trying to use a different credential for http backend with a saved plan it fails with the message:

```bash
Error: Error loading state: HTTP remote state endpoint requires auth
```

Or with lock:

```bash
Error: Error locking state: Error acquiring the state lock: HTTP remote state endpoint requires auth
Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
```

### Steps to Reproduce

1. Using the http backend configuration, run the init:
```bash
export TF_ADDRESS="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}"
terraform init \
    -input=false \
    -reconfigure \
    -backend-config="address=${TF_ADDRESS}" \
    -backend-config="username=gitlab-ci-token" \
    -backend-config="password=${CI_JOB_TOKEN}" \
    -backend-config="retry_wait_min=5"
```
Replace the fields with valid information.
2. Run the plan `terraform plan -out=terraform.tfplan`
3. Invalidate the credential of used in the init command
4. Run the init command again, as in the step 1, with the new credential
5. Try to run the apply with the saved plan: `terraform apply terraform.tfplan`
6. The apply will fail with the error: `Error: Error loading state: HTTP remote state endpoint requires auth`

**Comment by apparentlymart** [comment]
Hi @fabiomatavelli,

It's a general rule that anything you place inside a `backend` block or pass to `-backend-config` (which is, in effect, an extension of the `backend` block) will be included in your backend configuration which Terraform needs to save in both `.terraform/terraform.tfstate` (the working directory record of the backend config) and in plan files. It's by design that when you apply a plan it applies to the backend that was used to create it, because otherwise the plan would not necessarily be applicable.

If you want your credentials to not be seen by Terraform as part of the backend configuration, you can instead use the various environment variables mentioned in [the `http` backend's documentation](https://www.terraform.io/docs/language/settings/backends/http.html). Environment variables are not part of the backend configuration and so the backend will access them directly each time, thus allowing them to vary between plan time and apply time if you wish, although of course at that point it becomes your responsibility to make sure that the changed values only represent who/what is applying the plan, not _where_ the plan is being applied.

For example:

```shellsession
# export TF_ADDRESS="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_COMMIT_REF_SLUG}"
$ export TF_HTTP_USERNAME="gitlab-ci-token"
$ export TF_HTTP_PASSWORD="${CI_JOB_TOKEN}"
$ terraform init \
    -input=false \
    -reconfigure \
    -backend-config="address=${TF_ADDRESS}" \
    -backend-config="retry_wait_min=5"
```

Here I've separated the settings that describe _who or what is running Terraform_ from the settings that describe _the backend location_, which will cause Terraform to remember the state API location as part of the backend config but to allow you to select any other credentials you like as long as they still have access to read/write the state from that location.

From what you've described here it sounds like Terraform is working as intended, so I'm going to relabel this as an enhancement in case we end up using it to discuss a potential new use-case that the current design doesn't meet. However, based on what you described I hope the example above will meet your needs with Terraform as currently designed! Please let us know, either way. Thanks!

**Comment by fabiomatavelli** [comment]
Hey @apparentlymart thanks for the quick answer

So, I've tested the way you said and it worked as expected. Thanks
