### ISSUE TITLE
Dependency to one and the same module from many modules are duplicating creation on of resources that is defined.

### ISSUE THREAD

**Issue by mikaelparkefelt** [hashicorp/terraform#28306]
Hi,

I have used Terraform for a while now and there is a building block in the configuration you call modules.

I have tried to use this concept of grouping resource into modules. But, I was really disappointed how they works and that is not possible to have nested modules.

So, my problem is that i have a modules called security-groups and this on has now dependencies.
Then I have some other modules that i would like to have module security-groups as a dependency. This is to us the resources created in the module in the other modules.

Now here comes the problem. So, if I have multiple module dependent on security-groups the Terraform Cli does not process the dependency graph in a correct way. The problem I have is it will try to create the resources in the module security-groups as many times that I have a dependency to that module from other modules.

The way I want it to work is that I am in my modules dependent on one and the same module and the resources should only be created once and the be reused in all modules. Not, duplicated.

What is the plans to resolve modules as it should work like if I have many dependencies to the same module than Terraform should identify that and not duplicates everything in the referenced module?

**Comment by jbardin** [comment]
Hi @mikaelparkefelt 

Sorry you're having trouble with this. Creating a single module instance will only create the contained resources a single time, and that module can provide outputs which can be used in other parts of the configuration. Without an example it's hard to determine what you are doing to cause the problem here, but what you describe should be possible with terraform.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by mikaelparkefelt** [comment]
Hi,

Thanks for the quick replay. Below is an example:
[example.zip](https://github.com/hashicorp/terraform/files/6276331/example.zip)

The example contains two solutions. One with how  I solved it with a workaround that i don't think is very pretty.
The other one is how I would like the dependencies of modules to work and also creates the problem I having.

I just to be clear why I added this feature. It was because I want a functionality change done in Terraform and module dependencies. 

I want you to improve the modules and dependencies between modules.

Thanks
Mikael
