### ISSUE TITLE
Running Terraform init with Zip files in GCS, fails to initialise submodules 

### ISSUE THREAD

**Issue by jonasvadebo** [hashicorp/terraform#28301]
When running terraform init command for a module with the .zip extension, and stored in a GCS bucket. If that module contains submodules, something like this:

main.tf
modules/submodule/main.tf

Then when running terraform init, pointing to the zip file locally, Terraform initialises all modules as it should. When however running terraform init pointing to the zip file in GCS, the download works fine(I assume, since all files end up under .terraform folder), but it does NOT initialise the submodules in this case as it does locally, hence the terraform plan then fails.   

Terraform version: v0.14.3

**Comment by apparentlymart** [comment]
Hi @jonasvadebo,

I think in order to understand better what's happening here we'd need to see the contents of the `main.tf` and `modules/submodule/main.tf` files you mentioned, and also the calling module that contains the `module` block which refers to this GCS bucket object. It seems like something unusual is happening but in order to understand what we'd need to reproduce it ourselves so we can see the trace log, since you didn't include one.

Thanks!

**Comment by crw** [comment]
Hi @jonasvadebo, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
