### ISSUE TITLE
Continue #28306: Dependency to one and the same module from many modules are duplicating creation on of resources that is defined. 

### ISSUE THREAD

**Issue by mikaelparkefelt** [hashicorp/terraform#28314]
Hi,

Here is a continue on the https://github.com/hashicorp/terraform/issues/28306 because it was closed before I had the opertunitu to response to the response.

Thanks for the quick replay. Below is an example:
[example.zip](https://github.com/hashicorp/terraform/files/6278299/example.zip)

The example contains two solutions. One with how I solved it with a workaround that i don't think is very pretty.
The other one is how I would like the dependencies of modules to work and also creates the problem I having.

I just to be clear why I added this feature. It was because I want a functionality change done in Terraform and module dependencies.

I want you to improve the modules and dependencies between modules.

Thanks
Mikael

**Comment by jbardin** [comment]
Hi @mikaelparkefelt,

Thanks for the contribution, but for enhancement requests we ask that you provide the information requested in the issue template. What we need to see here is the full use case describing what exactly you are attempting to do, along with the minimal example of what you have tried.

It is not clear from the description what the problem is, as dependencies between modules do not cause resources to be duplicated. In most cases it is more likely that you will find a usable solution by asking _how_ to accomplish a certain task in [the community forum](https://discuss.hashicorp.com/c/terraform-core), rather than proposing your attempted solution. The design and engineering work to change the module architecture of terraform would be a substantial change, and not likely to happen in a short timeframe.

Thanks!

**Comment by jbardin** [comment]
Hi, Since we have not heard back in a while I'm going to close this.
As I mentioned dependencies never will cause modules to duplicate resources, but nested modules nested within other modules that are expanded with `for_each` will of course also be created multiple times. Feel free to open a topic on the community forums if you have more questions!
