### ISSUE TITLE
Possible missing function to extract hostname and/or IP address from URL

### ISSUE THREAD

**Issue by ljalbinson** [hashicorp/terraform#28316]
I have been using 'openstack_containerinfra_cluster_v1' and have a requirement to associate a floating IP with the 'api_address' of such a resource.

The 'api_address' returns a URL and not just an IP address. I haven't found a function in the standard list of terraform functions that allows me to extract the hostname and/or IP address. Maybe I have overlooked something suitable.

Advice on this would be most welcome.

Kind regards, Lawrence

**Comment by apparentlymart** [comment]
Hi @ljalbinson,

I think you're right that there isn't currently a specialized function for this.

One of [the examples in the `regex` function docs](https://www.terraform.io/docs/language/functions/regex.html#examples) shows a pattern for extracting parts of a URL that was derived from a regular expression in an RFC so perhaps that will help you in the meantime.

It looks like there's already #23893 open to discuss having a built-in function for this. I think the question remaining there exactly what level abstraction such a function should be at, since as was discussed over there the RFC 3986 regex is for _URLs in general_, rather than HTTP/HTTPS URLs specifically, and so it doesn't go down to the level of detail that you might want for that specific case. Arguably though it could be handled by using multiple functions together; I think we need to do some thinking about what the best design is.

Since that issue is already open for this use-case I'm going to close this. Hopefully the `regex` example is useful in the meantime. Thanks!
