### ISSUE TITLE
Powershell pipeline character not being interrupted correctly in remote-exec provisioner

### ISSUE THREAD

**Issue by GbCaa** [hashicorp/terraform#28325]
In Terraform version 0.14.10, the Powershell pipe character, which looks like this:    |     is not being interrupted correctly. It seems to be treating it as a new line.

Example provisioner:
```
provisioner "remote-exec" {

     connection {
      host     = self.default_ip_address
      type     = "winrm"
      user     = var.localwinadmin
      password = var.localwinadminpass
      https    = true
      insecure = true
    }

    inline = [
    "powershell.exe Get-ScheduledTask -TaskName 'ServerManager' | Disable-ScheduledTask",
    ]

}
```
Example output:
```
vsphere_virtual_machine.VM (remote-exec): Connecting to remote host via WinRM...
vsphere_virtual_machine.VM (remote-exec):   Host: 10.1.1.33
vsphere_virtual_machine.VM (remote-exec):   Port: 5986
vsphere_virtual_machine.VM (remote-exec):   User: local_admin
vsphere_virtual_machine.VM (remote-exec):   Password: true
vsphere_virtual_machine.VM (remote-exec):   HTTPS: true
vsphere_virtual_machine.VM (remote-exec):   Insecure: true
vsphere_virtual_machine.VM (remote-exec):   NTLM: false
vsphere_virtual_machine.VM (remote-exec):   CACert: false
vsphere_virtual_machine.VM (remote-exec): Connected!
vsphere_virtual_machine.VM: Still creating... [4m30s elapsed]

vsphere_virtual_machine.VM (remote-exec): 'Disable-ScheduledTask' is not recognized as an internal or external command,
vsphere_virtual_machine.VM (remote-exec): operable program or batch file.
vsphere_virtual_machine.VM (remote-exec): C:\Users\local_admin>powershell.exe Get-ScheduledTask -TaskName 'ServerManager'   | Disable-ScheduledTask

Error: "C:/Temp/terraform_24753584.cmd" exit status: 255
```

**Comment by apparentlymart** [comment]
Hi @GbCaa,

Terraform's `remote-exec` provisioner is just passing the string you gave directly to the Windows command interpreter (`cmd.exe`), and so the responsibility for parsing it is with the Windows command interpreter rather than Terraform.

I recognize the message you shared ("'Disable-ScheduledTask' is not recognized ...") as what `cmd.exe` prints when you try to run a command that doesn't exist. It's saying that there isn't a program like `Disable-ScheduledTask.exe` or `Disable-ScheduledTask.bat` available.

I think perhaps you intended that to be treated as a PowerShell cmdlet rather than as a command line program. If so, I think you'll need to format your command differently so that the `|` character will be handled by PowerShell rather than by `cmd.exe`. I'm not knowledgable enough about PowerShell to tell you exactly how to do that, but from a quick look at [the docs for `PowerShell.exe`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe) I see the `-Command` option which seems intended to handle this, with command lines like this:

```
powershell.exe -Command "Get-ScheduledTask -TaskName 'ServerManager' | Disable-ScheduledTask"
```

Because that command line contains `"` characters, which are also meaningful to Terraform, I'd suggest passing it as a "heredoc" string instead of a quoted string so that you don't need to escape the quotes:

```hcl
  inline = [
    <<EOT
      powershell.exe -Command "Get-ScheduledTask -TaskName 'ServerManager' | Disable-ScheduledTask"
    EOT
  ]
```

With that said, I'm just guessing at that command line based on the PowerShell documentation. I'm afraid if the above doesn't work then you'll need to ask in a different forum where there are folks with PowerShell expertise, because that'd be a PowerShell question rather than a Terraform question.

Since Terraform does seem to be passing the entire string you shared to `cmd.exe` as expected, and it's the formatting of your command line that's causing the behavior you saw, I'm going to close this. I hope my guesses above are helpful in finding a working solution.
