### ISSUE TITLE
aws_iam_policy-how to create multiple policy

### ISSUE THREAD

**Issue by surendarkaniops** [hashicorp/terraform#28335]
i am trying to create multiple aws iam policies in single block of code using count function.

can anyone help me with the code, how i can do that.

**Comment by surendarkaniops** [comment]
policy document :
------------------------
data "aws_iam_policy_document" "resource_full_access" {
  statement {
    sid       = "FullAccess"
    effect    = "Allow"
    resources = ["arn:aws:s3:::bucketname/path/*"]

    actions = [
      "s3:PutObject",
      "s3:PutObjectAcl",
      "s3:GetObject",
      "s3:DeleteObject",
      "s3:ListBucket",
      "s3:ListBucketMultipartUploads",
      "s3:GetBucketLocation",
      "s3:AbortMultipartUpload"
    ]
  }
}

data "aws_iam_policy_document" "base" {
  statement {
    sid       = "BaseAccess"
    effect    = "Allow"
    resources = ["*"]

    actions = [
      "s3:ListBucket",
      "s3:ListBucketVersions"
    ]
  }
}

resource creation code:
------------------------
locals {
source_documents = ["data.aws_iam_policy_document.base", data.aws_iam_policy_document.resource_full_access" ]
}
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"
  count = length(local.source_documents)
  policy = element(local.source_documents, count.index)
}

i want to create multiple policy using the single resource block and single data source file .

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
