### ISSUE TITLE
element function does not error when referencing a singular resource

### ISSUE THREAD

**Issue by damonconway** [hashicorp/terraform#28350]
We discovered this issue after I recently changed an element() call to count.index for another resource to the built-in index syntax for a user_data template file data source. The code threw an error complaining of an invalid index. The issue is that back in August of 2020, another engineer had removed the count from the user_data template data source. However, the element call did not throw an error as I would expect.

I have crafted an example of this behavior just using data sources. When using element, I get successful plans. If I switch over to the built-in syntax, I get errors when running a plan. I would expect these to both return an error.

### Terraform Version
All versions. I've tested against 0.12.29, 0.13.6, 0.14.10, and 0.15.0-rc2.

```
damonconway@RMT-DCONWAY.local > terraform version
Terraform v0.15.0-rc2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform
data "template_file" "test1" {
  template = file("./test1.sh")
  vars = {
    foo = "FOO"
  }
}

data "template_file" "test2" {
  count    = 2
  template = file("./test2.sh")
  vars = {
    foo = element(data.template_file.test1.*.rendered, count.index)
  }
}

# data "template_file" "test2" {
#   count    = 2
#   template = file("./test2.sh")
#   vars = {
#     foo = data.template_file.test1[count.index].rendered
#   }
# }
```

test1.sh
```bash
#!/usr/bin/env bash

foo = ${foo}
```

test2.sh
```bash
${foo}
```

### Crash Output

https://gist.github.com/damonconway/1d3a3675baa333a6564a0846e39a5efe

### Expected Behavior
I swapped the test2 data sources to generate this output. I expect element() to output something like this when being asked to find count.index in a singular data source or resource.

```
damonconway@RMT-DCONWAY.local >  terraform plan
╷
│ Error: Invalid index
│
│   on main.tf line 20, in data "template_file" "test2":
│   20:     foo = data.template_file.test1[count.index].rendered
│     ├────────────────
│     │ count.index is 0
│     │ data.template_file.test1 is object with 5 attributes
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 20, in data "template_file" "test2":
│   20:     foo = data.template_file.test1[count.index].rendered
│     ├────────────────
│     │ count.index is 1
│     │ data.template_file.test1 is object with 5 attributes
│
│ The given key does not identify an element in this collection value.
╵
```

### Actual Behavior
I got a successful plan

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

To reproduce the error when using the built-in index syntax:
1. Comment out test2 data source that uses element() for foo
2. Uncomment test2 data source that uses built-in index syntax
3. `terraform plan`

### References
I could not find any other github issues regarding this problem.

**Comment by apparentlymart** [comment]
Hi @damonconway! Thanks for opening this issue.

[The `element` function](https://www.terraform.io/docs/language/functions/element.html)'s purpose is to provide a convenient way to spread a collection with many elements over a collection with a smaller number of elements, such as spreading 50 EC2 instances over five availability zones.

If I'm understanding the scenario you described correctly then the behavior you saw seems like a consequence of that intention: in the terms I used above you've asked Terraform to spread two instances of `data.template_file.test2` over one instance of `data.template_file.test1`.

(A quick sidebar here to note that `data.template_file.test1` alone would just be a single object, not a list at all, but `data.template_file.test1.*` turns it into a single-element list as described in [Splat Expressions](https://www.terraform.io/docs/language/expressions/splat.html), which is therefore an acceptable first argument for `element`.)

If you'd prefer to have Terraform produce an error when the index is out of range, you can use the language's built-in index operator to get that effect:

```hcl
data "template_file" "test1" {
  count = 1

  template = file("./test1.sh")
  vars = {
    foo = "FOO"
  }
}

data "template_file" "test2" {
  count = 2

  template = file("./test2.sh")
  vars = {
    foo = data.template_file.test1[count.index]
  }
}
```

Note that I added `count = 1` to the first resource here so that `data.template_file.test1` would be a one-element list for the sake of this example, just so it would end up being an error about there being no index 1 rather than an error about `data.template_file.test1` being an object instead of a list.

Does that help to explain the behavior you saw, or have I misunderstood what you're reporting? Thanks!

**Comment by damonconway** [comment]
If this is desired functionality, it is entirely unclear in the documentation. Prior to opening this ticket, I read over the documentation for the element function that you linked, and I see nothing in there to indicate this behavior is expected. It also does not state that the purpose of element is to "provide a convenient way to spread a collection with many elements over a collection with a smaller number of elements". The very first line describing it's purpose is "element retrieves a single element from a list."

**Comment by damonconway** [comment]
Specifically, there is nothing about element converting a singular resource into a list to operate on it.

**Comment by damonconway** [comment]
This is very confusing syntax, but I see what you are saying now.

**Comment by apparentlymart** [comment]
Hi @damonconway,

Just so I can act on that feedback, can you say which part of the syntax you are referring to here? I'm not sure if you're talking about the `element` function, the splat operator, or both.

Thanks!
