### ISSUE TITLE
Apply fails in Azure Cloud Shell  with "Error: Could not load plugin"

### ISSUE THREAD

**Issue by doherty100** [hashicorp/terraform#28354]
### Terraform Version

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  # client_id       = "REPLACE-WITH-YOUR-CLIENT-ID"
  # client_secret   = "REPLACE-WITH-YOUR-CLIENT-SECRET"    
  # tenant_id       = "REPLACE-WITH-YOUR-TENANT-ID"
}

output "subscription_id" {
  value = var.subscription_id
}

provider "random" {}
```

### Debug Output

[https://gist.github.com/doherty100/ad20d50bfad77df79018c01bd69eed35](https://gist.github.com/doherty100/ad20d50bfad77df79018c01bd69eed35)
### Expected Behavior

Apply should succeed.

### Actual Behavior

```
Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/hashicorp/azurerm" to
obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```
### Steps to Reproduce

This only happens in Azure Cloud Shell (a docker container for CLI hooked up to Azure portal).

This only happens AFTER running multiple other terraform init / terraform apply operations in other directories.

### Additional Context

I run this same combination of terraform init / terraform apply operations using terraform binary installation (not a container) and this problem doesn't occur.

### References

- [#26104](https://github.com/hashicorp/terraform/issues/26104)

**Comment by doherty100** [comment]
Tagging @tombuildsstuff

**Comment by mildwonkey** [comment]
Hi @doherty100 ! I'm sorry you're experiencing this.

Since you say that this is something which only occurs in Azure Cloud Shell, it don't sound like there's a terraform bug for the terraform core developers to address. The debug logs indicates that the provider experienced a segfault. 
I'm not sure if this is more likely to be an azure provider bug, or an issue related to the face this is running in Azure Cloud Shell. 

The relevant log from the debug file is here:
> 2021-04-13T22:57:37.768Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.55.0/linux_amd64/terraform-provider-azurerm_v2.55.0_x5 pid=1073 error="signal: segmentation fault"

I will label this issue so it is transferred to the azure provider repo, but I also suggest asking in the azure provider [community forums](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
