### ISSUE TITLE
Unrelated change causes a big diff in terraform plan

### ISSUE THREAD

**Issue by sblask** [hashicorp/terraform#28377]
This is kind of hard to reduce to a minimal example because I've got the problem in a live environment and I can't actually share the code. I tested it with the latest AWS provider and terraform 14.9 and 15.0 and can aways reproduce it.

I've got a main.tf that looks like this:

```
module "xyz_sydney" {
  source = "../modules/xyz"

  providers = {
    aws = aws.environment_sydney
  }

  default_instance_role_arn       = aws_iam_role.xyz_instance_role.arn
  default_instance_profile_arn    = aws_iam_instance_profile.instance_profile.arn
  update_default_template_version = var.update_default_template_version

  depends_on = [
    aws_iam_role.xyz_instance_role
  ]
}

module "xyz_northern_virginia" {
  source = "../modules/xyz"

  providers = {
    aws = aws.environment_northern_virginia
  }

  default_instance_role_arn       = aws_iam_role.xyz_instance_role.arn
  default_instance_profile_arn    = aws_iam_instance_profile.instance_profile.arn
  update_default_template_version = var.update_default_template_version

  depends_on = [
    aws_iam_role.xyz_instance_role
  ]
}

data "aws_iam_policy_document" "assume_role" {
  provider = aws.environment_global

  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::XXXXXXXXXXXXXXX:root"]
    }

    condition {
      test     = "Bool"
      values   = [true]
      variable = "aws:MultiFactorAuthPresent"
    }
  }

  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "xyz_instance_role" {
  provider           = aws.environment_global
  name               = "role-instance"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

resource "aws_iam_instance_profile" "instance_profile" {
  provider = aws.environment_global
  name     = "role-instance"
  role     = aws_iam_role.xyz_instance_role.name
}
```
The xyz module contains some data providers to retrieve VPC and subnets which are then used in a launch template resource and a few other places.

I figured, that I don't need this bit:

```
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::XXXXXXXXXXXXXXX:root"]
    }

    condition {
      test     = "Bool"
      values   = [true]
      variable = "aws:MultiFactorAuthPresent"
    }
  }
```
So I removed it and suddenly terraform plan gave me a big diff because the VPC id and subnets `forces replacement` on the launch template and some other dependent resources even though VPC and subnets didn't change at all. I didn't dare to apply because this is a live environment. I played around a bit trying to reduce the example and when removing the `depends_on` first before removing the other bit I don't get the problem. I can reproduce the problem with this particular `depends_on` but in the actual code I depend on something else.

I believe the combination of changes triggers a read of data which doesn't actually happen during plan which is something that also caused me trouble in other situations. As the actual data is not known terraform assumes a change.

**Comment by sblask** [comment]
I managed to create a minimal example in the end, consider this main.tf:
```
terraform {}

provider "aws" {

  assume_role {
    role_arn = "arn:aws:iam::XXXXXXXXXXXXXX:role/terraform-admin"
  }
}

module "xyz" {
  source = "./module"

  providers = {
    aws = aws
  }

  depends_on = [
    aws_iam_role.instance_role
  ]
}


data "aws_iam_policy_document" "assume_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::202656505727:root"]
    }

    condition {
      test     = "Bool"
      values   = [true]
      variable = "aws:MultiFactorAuthPresent"
    }
  }

  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "instance_role" {
  name               = "instance"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
  description        = "A role for r-cloud instance"
}

resource "aws_iam_instance_profile" "instance_profile" {
  name = "instance"
  role = aws_iam_role.instance_role.name
}
```

with ./module/main.tf looking like this:

```
provider "aws" {}

data "aws_vpc" "test" {
  tags = {
    Name = "default"
  }
}

resource "aws_security_group" "efs_access" {
  name   = "efs-access"
  vpc_id = data.aws_vpc.test.id
}
```

Now, when I remove:
```
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::202656505727:root"]
    }

    condition {
      test     = "Bool"
      values   = [true]
      variable = "aws:MultiFactorAuthPresent"
    }
  }
```

I get this diff:

```
  # aws_iam_role.instance_role will be updated in-place
  ~ resource "aws_iam_role" "instance_role" {
        arn                   = "arn:aws:iam::081352067163:role/instance"
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Condition = {
                          - Bool = {
                              - aws:MultiFactorAuthPresent = "true"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::202656505727:root"
                        }
                      - Sid       = ""
                    },
                    {
                        Action    = "sts:AssumeRole"
                        Effect    = "Allow"
                        Principal = {
                            Service = "ec2.amazonaws.com"
                        }
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        create_date           = "2021-04-15T09:36:47Z"
        description           = "A role for r-cloud instance"
        force_detach_policies = false
        id                    = "instance"
        managed_policy_arns   = []
        max_session_duration  = 3600
        name                  = "instance"
        path                  = "/"
        tags                  = {}
        unique_id             = "AROARF4HWBBNZMHKLRBIH"

        inline_policy {}
    }

  # module.xyz.data.aws_vpc.test will be read during apply
  # (config refers to values not yet known)
 <= data "aws_vpc" "test"  {
      ~ arn                     = "arn:aws:ec2:ap-southeast-2:081352067163:vpc/vpc-0392b59df9aab82db" -> (known after apply)
      ~ cidr_block              = "172.50.0.0/16" -> (known after apply)
      ~ cidr_block_associations = [
          - {
              - association_id = "vpc-cidr-assoc-0b50d9f69716ca74a"
              - cidr_block     = "172.50.0.0/16"
              - state          = "associated"
            },
        ] -> (known after apply)
      ~ default                 = false -> (known after apply)
      ~ dhcp_options_id         = "dopt-11366a76" -> (known after apply)
      ~ enable_dns_hostnames    = true -> (known after apply)
      ~ enable_dns_support      = true -> (known after apply)
      ~ id                      = "vpc-0392b59df9aab82db" -> (known after apply)
      ~ instance_tenancy        = "default" -> (known after apply)
      ~ ipv6_association_id     = "vpc-cidr-assoc-0272c3454d0bb2122" -> (known after apply)
      ~ ipv6_cidr_block         = "2406:da1c:d11:7d00::/56" -> (known after apply)
      ~ main_route_table_id     = "rtb-0fef3d09dfacaa697" -> (known after apply)
      ~ owner_id                = "081352067163" -> (known after apply)
      ~ state                   = "available" -> (known after apply)
      ~ tags                    = {
            "Name"        = "default"
          - "environment" = "sandpit" -> null
        }
    }

  # module.xyz.aws_security_group.efs_access must be replaced
-/+ resource "aws_security_group" "efs_access" {
      ~ arn                    = "arn:aws:ec2:ap-southeast-2:081352067163:security-group/sg-0a76b35b37514b406" -> (known after apply)
        description            = "Managed by Terraform"
      ~ egress                 = [] -> (known after apply)
      ~ id                     = "sg-0a76b35b37514b406" -> (known after apply)
      ~ ingress                = [] -> (known after apply)
        name                   = "efs-access"
      + name_prefix            = (known after apply)
      ~ owner_id               = "081352067163" -> (known after apply)
        revoke_rules_on_delete = false
      - tags                   = {} -> null
      ~ vpc_id                 = "vpc-0392b59df9aab82db" -> (known after apply) # forces replacement
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```

I wished `# module.xyz.data.aws_vpc.test will be read during apply` wouldn't be in there, but that `# module.xyz.aws_security_group.efs_access must be replaced` is in there is clearly a bug?

The debug output looks like this: https://gist.github.com/sblask/ac921d4ee4fdc7e7dd21e382c16ce2cc

**Comment by sblask** [comment]
Now that I had a toy example, I did actually run apply on the plan and does actually destroy and re-create the security group even though the VPC ID did not actually change.

**Comment by DenWin** [comment]
Having a depends_on in a module block will cause that Terraform marks all data blocks are marked to be read during the apply phase.
This subsequently will lead to the issue that terraform plan cannot determine, whether other blocks that would use these data blocks would need to be updated - as the data block will not be read yet.

Hence the ` ~ vpc_id                 = "vpc-0392b59df9aab82db" -> (known after apply) # forces replacement`

The solution:
A) Do not use data blocks within the module
- Thought in that case you would not have data blocks in the module, which might be a problem by itself

or B) do not use depends_on
- well this will fail, if you are indeed depending on other resources not yet created (A fresh deployment would be fine here, but an update of a given configuratoin might actually fail due to running conditions

**Comment by DenWin** [comment]
As I wrote this comment I had the idea, that might work:

```
module "xyz_data_blocks" {
  source = "./module_data"

  providers = {
    aws = aws
  }
}

module "xyz_resource_block" {
  source = "./module_res"

  providers = {
    aws = aws
  }

  depends_on = [
    aws_iam_role.instance_role,
    module.xyz_data_block
  ]
  aws_vpc_test_id = module.xyz_data_blocks.aws_vpc_test_id 
}
```

with ./module_data/main.tf looking like this:
```
provider "aws" {}

data "aws_vpc" "test" {
  tags = {
    Name = "default"
  }
}

output "aws_vpc_test_id" {
  value = data.aws_vpc.test.id
}
```

and with ./module_res/main.tf looking like this:
```
provider "aws" {}

resource "aws_security_group" "efs_access" {
  name   = "efs-access"
  vpc_id = var.aws_vpc_test_id
}

variable aws_vpc_test_id {}
```


This approach would be a quite a bit overengineered for this example, but once you are also working with for_each it would actually make sense! You would only need to change this line `aws_vpc_test_id = module.xyz_data_blocks.aws_vpc_test_id[each.key]` and use the same key for the data and resource module.

**Comment by jbardin** [comment]
Hi @sblask,

@DenWin is on the right track with the comment shown above. There is never a need to have `depends_on` set for a module, as there is always a way around it, but it can be convenient in some simple situations. 

Your simplified example obviously has no way to connect the dependencies without the `depends_on`, but it should not be needed as there is nothing in that module which needs the role as an input. In your original configuration, the module takes the `aws_iam_role.xyz_instance_role.arn` as an input, so it's likely that you don't actually need the `depends_on` there either.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by sblask** [comment]
I am sorry, but I have a hard time seeing how this is not a bug. Sure it seems like there are ways to work around it, but if what I did is valid Terraform and it destroys infrastructure even though nothing has changed, that is a bug? If there is no way to get `depends_on` work properly for modules and/or it's not necessary, maybe it should not be allowed in modules. 

There is also the inconsistency in behaviour. If I change the VPC directly Terraform does read the data source during plan, if it sees that it's still the same ID, nothing changes. So Terraform is capable of doing the right thing. If I don't touch the VPC at all Terraform assumes it's changed without actually checking and destroys infrastructure. Why does it not do the same (read during plan) as when changing the VPC directly? If you don't want to call it bug, call it feature request, but it should get fixed.

**Comment by techdragon** [comment]
@jbardin I definitely share @sblask 's sentiments that this looks like a bug. I ran into this issue multiple times and it has been a major source of irritation while trying to onboard team members to terraform. It feels inappropriate to simply close this issue. In my case the `depends_on` was absolutely required.

**Comment by DenWin** [comment]
Well I can understand that if a defect is situated so deep in the code, that any fix would need a major re-engineering of said code, I wouldn't call it a bug, but something to be addressed with a major change.

That said, yes it is really unsqatisfying.

Here my solution:
I simply attached the unchanged variables to the resource creation process - meaning giving the resource a fixed index name and ignore the id of the data block.

```
locals {
    identifier                              = format( "%s_%s", var.keyvault.resource_group_name, var.keyvault.name )
}

data azurerm_key_vault "kv" {
    for_each                                = { local.identifier = 1 }
        name                                = var.keyvault.name
        resource_group_name                 = var.keyvault.resource_group_name
}

resource azurerm_key_vault_access_policy "kv_policy" {
    lifecycle {
        ignore_changes                      = [ key_vault_id ]
    }
    for_each                                = { local.identifier = 1 }
        key_vault_id                        = data.azurerm_key_vault.kv[ local.identifier ].id
        tenant_id                           = var.tenant_id
        object_id                           = var.object_id
        secret_permissions                  = var.secret_permissions
        key_permissions                     = var.key_permissions
        certificate_permissions             = var.certificate_permissions
}
```

**Comment by jbardin** [comment]
Sorry for the confusion here, but the reason this is not classified as a bug is that terraform is doing precisely what it is instructed to do by the configuration. 

Let's break down the [simplified configuration from above](https://github.com/hashicorp/terraform/issues/28377#issuecomment-820290085) for example. 

 - Adding `depends_on` to the module block is effectively stating "I want _everything_ thing in this module to depend in the result of any changes to `aws_iam_role.instance_role`". 

- Within the module we have `data.aws_vpc.test`, which now depends on any change to `aws_iam_role.instance_role` and cannot be read during the planning phase. 

- The result of `data.aws_vpc.test.id` is now in the plan, because the data source cannot be read, therefor we also have to plan a change to `aws_security_group.efs_access` because the `vpc_id` is not known.

This is the chain of events that leads to the result you see, and depending on the types of resource and circumstances, this is a perfectly valid use case for some users. 

Now we do understand that as modules and configuration grow, usually with multiple contributors, it gets harder to reason about the overall behavior in this way. We are always working on providing better feedback and errors to help direct users and support staff alike when debugging situations like this. As we explore this area we may end up with new tooling or just in-depth guides, but we have to balance providing powerful language constructs for complex cases and limiting those constructs for ease of use.
