### ISSUE TITLE
Implement AWS WAFv2 "Custom Response Bodies"

### ISSUE THREAD

**Issue by wesleywh** [hashicorp/terraform#28388]
It looks like generate a "Custom Response Bodies" are not supported by terraform? Is this true? This is for AWS WAFv2. I don't see any option to actually generate this with terraform docs which tells me that this might not actually be supported. 

Just putting in a request to get this supported by terraform. Thanks!

**Comment by apparentlymart** [comment]
Hi @wesleywh,

It seems like this is a feature request for the AWS provider. We don't maintain the AWS provider in this repository, so I suggest [opening a feature request in the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=enhancement&template=Feature_Request.md). When you do, please review the provider team's enhancement request issue template so that you can include the information they need in order to consider feature requests. Thanks!
