### ISSUE TITLE
Use API Token for authentication to artifactory backend

### ISSUE THREAD

**Issue by vishmit123** [hashicorp/terraform#28385]
Hi, 
Please include an option to authenticate artifactory backend via **X-JFrog-Art-Api**

**Comment by jgrumboe** [comment]
@vishmit123 
Sorry, but the jfrog/artifactory provider is already supporting api keys
https://registry.terraform.io/providers/jfrog/artifactory/latest/docs#jfrog-api-key-header
Or did I misunderstand your comment?

**Comment by vishmit123** [comment]
@jgrumboe the artifactory remote backend does not have option to authenticate via api key.

**Comment by jgrumboe** [comment]
Aha...thanks, now I understand. Thanks for clarification, I mixed things up.

**Comment by gdubya** [comment]
Related: https://www.jfrog.com/jira/browse/RTFACT-19768

A workaround that seems to work for us is to define an environment variable named ARTIFACTORY_ACCESS_TOKEN with the value of the API token.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Artifactory backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
