### ISSUE TITLE
Provider documentation does not properly describe the filesystem layout

### ISSUE THREAD

**Issue by rnelson0** [hashicorp/terraform#28395]
### Terraform Version
Docs for 0.13+

### Expected Behavior
The URL https://www.terraform.io/docs/cli/config/config-file.html#implied-local-mirror-directories describes the location to download local copies of plugins as `%APPDATA%/terraform.d/plugins`, `$HOME/.terraform.d/plugins/`, and some other locations. I expect that when I download a provider and place it in one of those directories, that `terraform init` will find it.

### Actual Behavior
Terraform does not find the providers. Starting in v0.13, the filesystem layout changed and is documented at https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers. The `config-file.html` doc, and other provider docs, should be updated to properly describe this.

Following the new layout DOES work as expected, but there's no link from the official docs to the upgrade docs so it's only through asking questions on a slack that I found the second link.

### Additional Context
https://www.terraform.io/docs/cli/config/config-file.html#explicit-installation-method-configuration does explain the packed/unpacked layout but I found it confusing. If I'm not installing from a registry (in my case I downloaded from https://github.com/vmware/terraform-provider-vra/releases/latest), it's unclear why I would need a registry, or what it would be.

https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations also needs some update, the `<OS>_<ARCH>` layout appears to no longer work, either.

### References
I did not find any, but there's over 1,300 issues open currently. My apologies if I missed something!

**Comment by mildwonkey** [comment]
Hi @rnelson0 , thanks for opening this issue!
I am working on updating these docs - `how-terraform-works.html`  is in a different repository, in case you wonder why that doesn't show up in the same PR.

I did want to directly address this question: `it's unclear why I would need a registry, or what it would be.`
Since providers are installed in a hierarchical directory structure, unlike the pre-0.13 flat directory layout, Terraform uses that full source address tp determine in which directory it should look for providers: HOSTNAME/NAMESPACE/PROVIDER. The hostname is part of a provider's fully-qualified-name (FQN); if the hostname is omitted terraform assumes that the provider is in registry.terraform.io. 
 
Here's the real _why_ behind the above statement:

It is entirely possible for a single terraform configuration to have, for example, multiple versions of `terraform-provider-vra`. One could plausibly download that provider from the public registry while also using a custom `terraform-provider-vra` provider (I'm not saying this is likely, but there's nothing stopping it from happening!). Or perhaps you use two different community `dns` providers, because each has a resource you need and no overlap. Yes, these are weird examples, and I don't know how likely these situations will arise in reality, but we designed the new provider installation to support these potential provider name collisions. That's why terraform requires the full source address (it's easier for me to think of it as an FQN instead of a source address, even though those are effectively the same things). 

For what it's worth, you can choose any arbitrary hostname for that. It can even be registry.terraform.io as long as the provider is installed in the correct location.

**Comment by rnelson0** [comment]
Thank you for the fix, and also the explanation!
