### ISSUE TITLE
Installation of Terraform via WINGET

### ISSUE THREAD

**Issue by johnwildes** [hashicorp/terraform#28396]
### Current Terraform Version
```
0.15.0
```

### Use-cases
I realize there are many ways to get Terraform installed on a workstation, and some of them are via third party installers, has the organization investigated supporting WINGET repository from Microsoft as a supported way of installing Terraform? 

### Proposal
Create a package manifest for the installation of Terraform on Windows workstations.

Installation in a default location, either on the current PATH variable, or updating it to include the path that TF is installed into. 

https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema

It looks like installation of standalone apps (i.e. zip files, .exe files) is being worked on currently. https://github.com/microsoft/winget-cli/issues/140

**Comment by apparentlymart** [comment]
Hi @johnwildes,

At the moment we're not planning to introduce any new distribution channels for Terraform, since the ones we're already building are a lot of complexity already and we have limited resources, but we know that community members have sometimes contributed recipes or manifests for distribution channels we don't support directly, and if winget's repository allows for such a thing then we'd be happy for someone knowledgeable about that tool to submit one. From some quick research it seems like that would involve opening a pull request in [the `microsoft/winget-pkgs` repository](https://github.com/microsoft/winget-pkgs).

Since implementing this wouldn't involve making any code changes in _this_ repository I'm going to close this, but I do appreciate you bringing this to our attention and would welcome a package manifest being included in the winget repository if you or someone else be willing to write and submit it.

**Comment by johnwildes** [comment]
Thanks @apparentlymart !  Will look into it once the support for single EXE and ZIP files is complete.
