### ISSUE TITLE
error deleting CloudWatch Event Rule

### ISSUE THREAD

**Issue by pawanyoda** [hashicorp/terraform#28404]
### Terraform Version
11.14
 provider.aws: version = "~> 2.56"
Run `terraform version` to show the version, and paste the result between the ``` marks below.

### Terraform Configuration Files
I am using module to creation and deletion but sometimes it does sometimes its not.

### Error Output
module.healthcheck.aws_cloudwatch_event_rule.healthcheck_event_rule: Still destroying... (ID: client-healthcheck, 4m50s elapsed)
 Error: Error applying plan:
 1 error occurred:
 	* module.healthcheck.aws_cloudwatch_event_rule.healthcheck_event_rule (destroy): 1 error occurred:
 	* aws_cloudwatch_event_rule.healthcheck_event_rule: error deleting CloudWatch Event Rule (client-healthcheck): ValidationException: Rule can't be deleted since it has targets.
 	status code: 400, request id: 75fcfe8e-01b3-4907-9ab6-5e114f406c4b
 Terraform does not automatically rollback in the face of errors.
 Instead, your Terraform state file has been partially updated with
 any resources that successfully completed. Please address the error
 above and apply again to incrementally change your infrastructure.

### Expected Behavior
Terraform should have removed the lambda function before attempting to remove the cloudwatch events rule linked to this lambda function. 

-->

### Actual Behavior
Terraform attempts to remove the CW events rule before the Lambda function that used it, its taking 5 minutes to destroy than after displays error.

-->

### Steps to Reproduce

- #6017

-->

**Comment by mildwonkey** [comment]
Hi! Thank you for reporting this issue, and I am sorry that you've experienced it.

We'll need to see your configuration files, or a simplified reproduction case, in order to figure out what's going on here. Can you please update this ticket with all of the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? Remove any sensitive information first.

**Comment by jbardin** [comment]
Hello,

We have not heard back with the requested information, and 0.11 is no longer supported, so we are going to close this issue.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

Thanks!
