### ISSUE TITLE
Support codecommit similar to Amazon's git plugin GRC

### ISSUE THREAD

**Issue by bengaywins** [hashicorp/terraform#28427]
### Current Terraform Version
```
0.14.9
```

### Use-cases
Module sources residing in CodeCommit without the need to use permanent credentials (ssh key) in the same manner that Amazon's [GRC](https://github.com/aws/git-remote-codecommit) uses standard AWS temporary credentials and profiles.

Example git url: `codecommit://demo-profile@MyRepositoryName`

This enables one to use the standard STS session tokens that have a limited validity and removes the need for separate credentials when using codecommit as the module source.

This is probably more relevant to me as a consultant than many others, but I think with most enterprises using SAML-based logins, this is ideal.

### Attempted Solutions
I have none and I do apologize. Though I try to learn and could possibly attempt if one could direct me to where this type of thing would otherwise be implemented.

**Comment by troyready** [comment]
Taking some inspiration from the [module sources documentation](https://www.terraform.io/docs/language/modules/sources.html#generic-git-repository) & apparentlymart's [thoughts here](https://github.com/hashicorp/terraform/issues/21522#issuecomment-497963956), I suspect the ideal thing to do is to configure git ahead of time to use the STS credentials. With the AWS CLI installed, that could look something like:

```
git config --global credential."https://git-codecommit.us-west-2.amazonaws.com".helper "!aws codecommit credential-helper $@"
git config --global credential."https://git-codecommit.us-west-2.amazonaws.com".UseHttpPath true
export AWS_PROFILE=demo-profile
```
(substituting `us-west-2` for the applicable region, or just removing the entire `."https://git-codecommit.us-west-2.amazonaws.com".` string should generally be fine).

Combine this with using the repo URL in its generic HTTPS form (`git::https://git-codecommit.us-west-2.amazonaws.com/v1/repos/MyRepositoryName`) should allow Terraform to download it without needing special handling for CodeCommit repositories.

**Comment by apparentlymart** [comment]
Thanks for sharing those details, @troyready! Indeed, since Terraform is just running normal `git` commands to interact with Git, we typically expect that you've already configured Git appropriately for what you need using Git's own configuration mechanisms, rather than having Terraform try to replicate a subset of Git configuration options (and contend with those potentially conflicting with your global settings).

If you're able to set up Git so that `git clone` will work on your repository then you should find that Terraform's module installer will succeed to with an equivalent source string (adjusted for Terraform's more general module source syntax). If not then we can try to figure out why, although it's typically easier to do that sort of open-ended troubleshooting in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) rather than in GitHub, because then we can focus specifically on finding _some_ way to make your system work rather than on a specific proposed solution.

Given that there seems to be a Git credentials helper available for this already and @troyready has shown how to configure it, I'm going to close this in the sense that it seems to be a problem within Git's scope rather than within Terraform's scope, and also one that Git already has a solution for. Thanks!

**Comment by bengaywins** [comment]
In case anyone else searches for this:

Turns out if you are using the plugin I referenced, just using the generic git repo URLs `git::codecommit://foo@bar` works just like if you cloned directly.
