### ISSUE TITLE
authorisation error for s3 backend

### ISSUE THREAD

**Issue by maheshcheetirala** [hashicorp/terraform#28429]
I am following the tutorials hosted by linkedin learning advanced terraform GitHub repository. I deployed backend resources and when i try using them am getting authorization error. I verified all my locations are set to us-east-2 and my bucket is in us-east-2 only. 

[EDIT: REMOVED IMAGE]

 please let me know  how to fix this error , I am using latest version of terraform.

**Comment by mildwonkey** [comment]
hi @maheshcheetirala ,
I removed the image from this issue because the credentials were still easily visible; I highly recommend you replace those credentials now.

The AWS provider looks in a few places for provider configuration which can cause the problem you're seeing - for example, environment variables and config files with the region set. The AWS provider documentation is [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication)

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. It's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) or the [AWS-specific forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are far more people ready to help. Thanks!
