### ISSUE TITLE
v0.15 - Passing a sensitive value to a non-sensitive module variable causes an error if the module derives a non-sensitive output from that variable

### ISSUE THREAD

**Issue by chrizkim** [hashicorp/terraform#28431]
### Terraform Version

```
0.15.0
```

### Terraform Configuration Files

```terraform
variable "db_username" {
  description = "Database administrator username"
  type        = string
  sensitive   = true
}

module "rds" {
  source  = "terraform-aws-modules/rds/aws"
  version = "2.34.0"

  username = var.db_username

  # additional arguments ...
}
```

### Expected Behavior

Both `plan` and `apply` commands should proceed successfully, redacting the passed in `username` argument (and any derived uses) from CLI output as `(sensitive value)`.

### Actual Behavior

Terraform errors out on plan creation with the message:
```
│ Error: Output refers to sensitive values
│
│   on .terraform/modules/rds/modules/db_instance/outputs.tf line 76:
│   76: output "this_db_instance_username" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```
* Note that the error is coming from an output within the module (actually coming from a submodule output that is getting threaded through).
* The issue occurs regardless of whether the output is used or completely ignored.
* This did not cause an error in Terraform 0.14.x, however Terraform 0.14 ended up not treating the value as sensitive within the module (equivalent to if `username = nonsensitive(var.db_username)` had been passed into the module).
### Steps to Reproduce

1. `terraform init`
2. `terraform plan` or `terraform apply`
### Additional Context

The author of the module did not mark the `username` input variable or the `this_db_instance_username` output as `sensitive = true`, since not all users of the module may consider the administrative username as sensitive for their particular use case or security posture (unlike an argument like `password`, which can be presumed as sensitive in all use cases). However, because the module output `this_db_instance_username` is derived from the input variable `username`, it causes an error when the value passed into `username` is being tracked as sensitive by Terraform.

The requirement for module outputs to be marked with `sensitive = true` should be limited to values and variables defined within the module as sensitive, not values that were marked as sensitive outside the module and then passed into the module through input variables not marked as sensitive. It is impractical for Terraform to force the author of third-party modules to determine what inputs/outputs all users of the module may consider sensitive, as this may vary by use case. Instead, it should allow allow sensitive values passed into a module (and any derived values) to be outputted, without the module author being concerned about whether the passed in value was marked as sensitive by the user. At the very least, the error message is misleading as it implies an issue in the module, when really it was caused by the user passing a sensitive value into the module which the module did not consider sensitive, deriving an output from that value that it did not explicitly mark as sensitive.

**Comment by apparentlymart** [comment]
Hi @chrizkim!

I just wanted to say a little here because I noticed that PR #28472 closed this automatically but we didn't actually talk here about the problem first.

This situation arose because of a safety rule added in Terraform v0.14 where we required setting `sensitive = true` on an output value as a declaration of intent to include a sensitive value in it, because root module output values are consumable via some additional channels than other data in the Terraform configuration and so are worthy of some additional thought and scrutiny.

However, that rationale only really applies strongly to outputs declared in the _root_ module, because descendent module output values only exist transiently in memory during a Terraform operation and so don't get exported in that same way.

As a compromise then, #28472 has adjusted the rule to apply only to output values in a root module, and thus a shared module is no longer required to statically declare an output value as sensitive in order that a dynamically-inferred sensitive value might pass through it. This should therefore resolve the problem that a shared module can't practically anticipate what might be sensitive in arbitrary data provided by a calling module.

The rule still applies to root module input variables for the reason I mentioned above, but we expect that to be okay in practice because the author of the root module is ultimately in control of where all of the output value data is coming from. We also updated the error message to include some more details about why this rule exists and what to do about it.

This fix will be included in the forthcoming v0.15.1 release, which is due soon once we land a few other important fixes that are still in progress.

Thanks for reporting this!

**Comment by chrizkim** [comment]
@apparentlymart Thanks, really appreciate you taking the time to provide an update! I totally agree that the constraint is valid for root module outputs, as the author/runner has full control of configuration input/output values. One question that remains for me, will CLI output of attributes for resource created in the submodule still treat the value as sensitive? For the example in the original description, using 0.14.7 I remember seeing that the `module.rds.aws_db_instance.username` showed up un-redacted in the CLI output, even though the `username` value passed into the module had been marked as sensitive. NBD if unsure, was just curious but I can test it out in 0.15.1.

@alisdair Thanks for jumping on a fix so quickly here!

**Comment by chrizkim** [comment]
@apparentlymart Actually scratch that last question, just peeked at @alisdair's PR and he explicitly mentions it resolving that issue 😅
