### ISSUE TITLE
Access to registry times out when IPv6 connection fails

### ISSUE THREAD

**Issue by MaxiPalle** [hashicorp/terraform#28437]
Same problem as in https://github.com/hashicorp/terraform/issues/27742#issue-806324863

Seems to be a problem if no IPv6 is allowed from client.

Tried the steps @cehoffman mentioned in #27742 and I can see that `getent hosts registry.terraform.io` shows only IPv6 DNS hosts, as `dig registry.terraform.io` only show IPv4 addresses, both pointing to `fastly.net`. 
Checked this with different network environments, same effect.

```bash
$ time curl -4 https://registry.terraform.io/v1/providers/community-terraform-providers/ignition/versions
{"id":"community-terraform-providers/ignition","versions":[{"version":"2.1.0","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"linux","arch":"amd64"},{"os":"windows","arch":"amd64"}]},{"version":"2.1.1","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"}]},{"version":"1.2.2","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"}]},{"version":"2.1.2","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"}]},{"version":"1.3.0","protocols":["5.0"],"platforms":[{"os":"darwin","arch":"amd64"},{"os":"freebsd","arch":"386"},{"os":"freebsd","arch":"amd64"},{"os":"freebsd","arch":"arm"},{"os":"freebsd","arch":"arm64"},{"os":"linux","arch":"386"},{"os":"linux","arch":"amd64"},{"os":"linux","arch":"arm"},{"os":"linux","arch":"arm64"},{"os":"windows","arch":"386"},{"os":"windows","arch":"amd64"}]}],"warnings":null}

real    0m8.859s
user    0m0.030s
sys     0m0.000s
```
and
```bash
$ time curl -6 https://registry.terraform.io/v1/providers/community-terraform-providers/ignition/versions
curl: (7) Couldn't connect to server

real    0m8.536s
user    0m0.008s
sys     0m0.007s
```

I'm working on Windows 10 with WSL2.
WSL does currently not support IPv6 AFAIK.
So it would be helpful, if Terraform would support registry access not only witn IPv6 but also IPv4 as it did in the past.

**Comment by jbardin** [comment]
Hi @MaxiPalle,

Thanks for the information here. The registry does provide both ipv4 and ipv6 addresses, for example:

```
% host registry.terraform.io
registry.terraform.io is an alias for dualstack.q2.shared.global.fastly.net.
dualstack.q2.shared.global.fastly.net has address 151.101.2.49
dualstack.q2.shared.global.fastly.net has address 151.101.66.49
dualstack.q2.shared.global.fastly.net has address 151.101.130.49
dualstack.q2.shared.global.fastly.net has address 151.101.194.49
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42::561
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42:200::561
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42:400::561
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42:600::561
```

It would appear however in your case that the local resolver is only returning ipv6 addresses, which is not compatible with the WSL2 environment. Do you have any more information about how your host DNS and network is configured?

**Comment by MaxiPalle** [comment]
Hi @jbardin ,

resolver on WSL2 is returning both IPv4 and IPv6 addresses:
```bash
$ host registry.terraform.io
registry.terraform.io is an alias for dualstack.q2.shared.global.fastly.net.
dualstack.q2.shared.global.fastly.net has address 151.101.2.49
dualstack.q2.shared.global.fastly.net has address 151.101.66.49
dualstack.q2.shared.global.fastly.net has address 151.101.130.49
dualstack.q2.shared.global.fastly.net has address 151.101.194.49
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42::561
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42:200::561
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42:400::561
dualstack.q2.shared.global.fastly.net has IPv6 address 2a04:4e42:600::561
```
I double-checked on an Azure DevTestLab VM with WSL2 and there I'm not experiencing those problems, so it seems network-related. I don't have any IPv6 related infrastructure here in my homeoffice so definitely will some some workaround for IPv4.

What makes me though-provoking is that those problems first occured in my environment last week. Setting `TF_REGISTRY_CLIENT_TIMEOUT = 20` in `~/.terraformrc` solved the problem until it now occurs again, no matter which timeout I'll set or which Terraform version to use. So for me it looks like some changes in the registry which seems to cause this behaviour.

**Comment by MaxiPalle** [comment]
OK, seems as if I found the root cause. 
I'm currently working in a different homeoffice network in with a quite popular router/firewall called AVM FritzBox. 
I'm limited to use the guest network (Gastzugang) of the FritzBox. This Router limits outgoing IPv6 traffic for guests by default, even de-activating the Teredo filter doesn't help. Connecting the client to the default LAN fixes the problem at least for testing.
As I won't be able to use the LAN and am also experiecing this issue with mobile internet access, I still need a solution to access the registry with IPv4.

**Comment by apparentlymart** [comment]
Hi @MaxiPalle,

Unfortunately this seems like a network or network stack configuration issue on your end and so we can't really help with that because we don't have access to your network configuration in order to understand what's going on. Terraform implements the relevant network standards for dual-stack operation but those mechanisms can only work correctly if the rest of your network path is also following those standards, whereas it seems like you have some equipment that is intentionally _not_ supporting them.

If your network contains devices that are actively blocking IPv6 then you might be better served by disabling IPv6 support on your local host altogether, which should then disable the attempts for any software (including Terraform) to operate in dual stack mode.

We use issues here to represent potential changes to Terraform itself, but I think in your case your issue will be resolved by changing your host or network configuration, rather than by changing Terraform's implementation. For that reason, I'm going to close this issue. However, you could open an issue in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) to discuss your network configuration problem if you like; I can't promise that folks there will be able to help you either, since it seems like you are suffering from an unfortunate interaction of a few specific technology problems that others are unlikely to have encountered exactly, but there is at least a larger pool of people participating in the forum than monitoring the issues in this repository.

Thanks!
