### ISSUE TITLE
Option to show sensitive value

### ISSUE THREAD

**Issue by PePoDev** [hashicorp/terraform#28438]
### Current Terraform Version
```
Terraform v0.15.0
on linux_amd64
```

### Use-cases
Sometimes I need sensitive values from a resource like `random_password` example for use with Database Connector (eg. DBeaver), But Terraform forces me to set sensitive to `true` in the output block. I'm okay with this to protect sensitive values from stdout in the CI server, But in my terminal when run `terraform output` the value is mask as sensitive. The only way I see is getting the value from Terraform state file but it not easy at all to find the value.

> terraform state pull | grep -C 30 random_password

The question is, It's possible to disable output after `terraform apply` complete by default or some flag and let me show output manually that reveal sensitive value when needed by 'terraform output'.

**Comment by jbardin** [comment]
Hi @PePoDev,

Sensitive outputs are  not masked when using the `-raw` or `-json` flags. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
