### ISSUE TITLE
Need far more expression/functions/interpolations

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#28441]
Terraform 0.15.0

Terraform is coming along nicely in terms of new expressions/functions/interpolations, but it still isnt really whats needed to avoid really-ugly code. 

Simple things which are a part of most languages just dont exist. 

For example, there isnt a function to tell me whether string a simply contains string b. This is pretty fundamental usecase but its not covered. 

* I guess you could try and use regex but if it doesnt match it errors, and its more complicated than what you need anyway
* The contains() function covers off some cases, if you can cast your string to an array somehow using split. E.g. for words, you could do contains(split(" ", haystack), "needle") - again quite complicated and doesnt work for nonwords.

Here's another one - why is there no way to calculate the length of a string? Again its pretty fundamental to most languages. 

* You have to do something like length(split("", string)) - because there is a length function for collections/lists but not for strings.

I can think of 20-30 really useful functions that should exist like this but dont. It might seem trivial, but some of my most horrible terraform expressions are horrible because these functions dont exist, and as soon as youre more than 2 brackets deep with something, the whole thing is hard to understand.  

I'd be happy to code up some extra functions to beef up the language a bit - but I don't want to do the work if they are going to be denied, so thought I'd ask first whether or not this is something you'd readily accept into the codebase. 

Thanks

**Comment by apparentlymart** [comment]
Hi @gtmtech,

It's hard to answer the question as you've asked it because you seem to be asking an open-ended question about tens of functions that we've not discussed individually, and so it's impossible to evaluate each of them.

The way we usually prefer to work with proposals like this is to have an issue discussing each use-case individually first, and then once we've got a good collection of use-cases which we've agreed are in Terraform's scope _then_ to design language features or other features to address those use-cases.

You've given two example use-cases here which we could discuss, although we'd prefer to think about them as the underlying problems you are trying to address and how you've _currently_ implemented it alongside your proposal for another way to implement it. For example, while I can imagine some hypothetical reasons why you might want to test if a string is a substring of another string, we'd prefer to hear from you what _your_ use-case is (or use-cases are), because concrete use-cases allow for a better discussion of tradeoffs, and some real examples you've written to meet those use-cases with the features of Terraform as they exist today.

We'd also prefer to have one proposal issue per use-case because otherwise GitHub's flat discussion model (without threading) makes it very hard to have multiple concurrent conversations about different topics.

For what it's worth, we do already have support for strings in [`length`](https://www.terraform.io/docs/language/functions/length.html), which I think addresses your second example:

```
> length("hello")
5
```

Terraform is not aiming to be a fully-fledged programming language, so we do tend to prefer to keep the language relatively small and focused on the most common cases, even at the expense of making less-common situations perhaps more complicated to express. That's a language design tradeoff we have to make on a case-by-case basis, because it's only with real examples that we can decide if something feels like a "common case" within Terraform's intended scope.

With all of this said, I'm going to close _this_ issue but if you'd like to write up a proposal for the use-cases that you've found it most challenging to meet with Terraform as it exists today, considering what I've said above and what our feature request template asks for, then we'd love to discuss whether we'd consider them to be in Terraform's scope and what language design might best meet them if so.

Thanks!

**Comment by gtmtech** [comment]
@apparentlymart Thanks for the info - very useful to understand how you work. 

Interestingly `length()` isnt documented in the String functions list - https://www.terraform.io/docs/language/functions/index.html

I'm guessing there must be others if you new they did exist. Shall I do a PR to update the docs?
