### ISSUE TITLE
terraform reports warning on the map key using a var

### ISSUE THREAD

**Issue by reachlin** [hashicorp/terraform#28453]
terraform gives warnings to a var map key. if I removed the "${}", terraform will report errors.
```
  redis_elasticache_clusters = {
    "${local.redis_suffix}" = {
      redis_replicas  = 1
     ...
```
the warning is:
```
Warning: Interpolation-only expressions are deprecated

  on main.tf line 152, in module "elasticache-aws-addon":
 152:     "${local.redis_suffix}" = {

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

**Comment by jbardin** [comment]
Hi @reachlin,

For map keys you can use a non literal string expression by wrapping in in parentheses, 

    (local.redis_suffix) = {

The error message has ben improved for this in later versions to better indicate the correct syntax, but you can find the documentation here for reference: https://www.terraform.io/docs/language/expressions/types.html#maps-objects

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
