### ISSUE TITLE
Syntax for nested for_each

### ISSUE THREAD

**Issue by choukimasri** [hashicorp/terraform#28463]
Hi there,

It would be very elegant to have nested for_each syntax to tackle some situations as below, what do you say ?

Thanks !

### Current Terraform Version

```
Terraform v0.15.0
```

### Use-cases
 
Provision multiple resources with the same variable, this allows abstraction for complex architectures, ex: for each database in each resource group

### Attempted Solutions
Flattening and remapping nested structure.

### Proposal
Something very cool as: 
```terraform
module "application_sql_database" {
  source              = "../../modules/sql_database"
  for_each            = var.project_resource_groups : rg
  for_each            = rg.databases : db

  resource_group_name   = rg.name
  server_name           = db.server_name
  database_name         = db.name
```
### References
None

**Comment by jbardin** [comment]
Hi @choukimasri,

`for_each` is a single meta argument for various blocks within terraform, but you can achieve what you want using nested [`for expressions`](https://www.terraform.io/docs/language/expressions/for.html).

Depending on the data structures being passed in, you may want something like so:

```
  for_each = for_each = toset(concat([for rg in var.project_resource_groups : rg.databases]...))
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by choukimasri** [comment]
@jbardin Hey, this would also work but it is not readable, that's why I made this proposal to improve the syntax, this would also improve readability for the each keyword by replacing it with custom holders.

**Comment by jbardin** [comment]
Thanks @choukimasri, that is why we do ask for a more detailed description of use cases and attempted solutions, so we know where you are coming from. 

Fundamentally the proposal does not work, because the configuration is not valid HCL and cannot be parsed. Within the syntax of HCL there are numerous way to decompose this, and we offer flexible expressions to manipulate various data structures which may not apply directly to the context of `for_each`. 

If you have ideas around simplifying the expressions, please feel free to start a thread on the community forums and we can toss around some ideas. Since we have to work within the structure of HCL, any new solution however would most likely be in the form of a function, or design patters for composing the needed expressions.

Thanks!
