### ISSUE TITLE
Terraform EKS module is not being processed anymore in version 15

### ISSUE THREAD

**Issue by JordyWTC** [hashicorp/terraform#28464]
Good afternoon,

In terraform version 14.9 i can still plan/apply the EKS module we are using.
When doing the same on version 15 i am getting the following error :
╷
│ Error: Unsupported block type
│ 
│   on .terraform/modules/eks/workers.tf line 115, in resource "aws_autoscaling_group" "workers":
│  115:   dynamic "warm_pool" {
│ 
│ Blocks of type "warm_pool" are not expected here.
╵
╷
│ Error: Unsupported block type
│ 
│   on .terraform/modules/eks/workers_launch_template.tf line 192, in resource "aws_autoscaling_group" "workers_launch_template":
│  192:   dynamic "warm_pool" {
│ 
│ Blocks of type "warm_pool" are not expected here.
╵

The terraform files mentioned do not have any block of type warm_pool.
So i do not know why this error is being thrown.

Regards,

Jordy

**Comment by jbardin** [comment]
Hi @JordyWTC,

The text for the error message is taken directly from the module files, so I suspect you will find `warm_pool` blocks in both `workers.tf line 115` and `workers_launch_template.tf line 192` at the paths specified. 

It's likely that you have changed a version of a module or provider while upgrading terraform, make sure to specify the versions you expect for each in your configuration.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
