### ISSUE TITLE
modify current `module_variable_optional_attrs` implimentation with `optional()` and `defaults()`

### ISSUE THREAD

**Issue by jw-maynard** [hashicorp/terraform#28475]
### Proposal

So I've played around with this experiment and I find the current implementation to be somewhat cumbersome to use. The example given in the docs requires that you use `optional()` to set your optional object items and then run that `var` through the `defaults()` function to set any default values you want for those optional items (unless you are of with the item being `null`).

It would see to be a much simpler and intuitive construction for the `optional()` function to take a second optional parameter that is the default value if `null` is not a suitable default to use.

I do recognize that this does intermingle a value (the default value) with the schema of the variable though and perhaps this is the reason for keeping them separate. If we want to avoid this intermingling then I would suggest changing the behavior of the default variable parameter to work in a similar manner to the `default()` function with some minor tweaks. If an item in the object is not specified under `default` it is required. If you want the default value for an item to be `null` then you would explicitly set that in the variable definition.

**Comment by apparentlymart** [comment]
Hi @jw-maynard,

The current design is motivated at least in part by trying to separate these two concerns so that `defaults` might be useful for other situations in future. However, I will admit that it's hard to see that benefit right now because we've not yet done other work that would make it useful in that way: `defaults` relies on the input value conforming to a well-defined type constraint, and currently the only place in the Terraform language where we can write type constraints is in `variable` definitions.

In my sketch notes of this mechanism I have another function called `convert` which aims to allow using conversion to a type constraint in other parts of the language, perhaps like the following example:

```hcl
locals {
  external_config_raw = convert(yamldecode("${path.module}/config.yml"), object({
    version = string
    instance_types = map(object({
      name = string
      ami  = optional(string)
    }))
  })
  external_config_defaults = defaults(local.external_config_raw, {
    instance_types = {
      ami = "ami-1234"
    }
  })
}
```

However, as we've been working through the various design challenges of `defaults` I've indeed been reconsidering this separation between the type constraint and the defaults. I had originally imagined that folks might want to separately access the original input (to see what's been set vs. left as default) from the revised input with the defaults applied, because in practice that has been a common need in providers where there is a similar mechanism for defaults. But as I've been exploring more examples such as these, I've not found a compelling _user-oriented_ reason to separate the operation of converting the value (which inserts the `null` values where needed) from the operation of inserting the defaults. The above could be rewritten like this, hypothetically, if we had a way to write down the defaults as part of the "type constraint":

```hcl
locals {
  external_config = convert(yamldecode("${path.module}/config.yml"), object({
    version = string
    instance_types = map(object({
      name = string
      ami  = optional(string, "ami-1234")
    }))
  })
}
```

From a language perspective I like this structure a lot, because it keeps everything together and it has the additional advantage of allowing us to explicitly distinguish between a _collection_ having a default value (for when the collection attribute isn't set at all) and a nested attribute inside a collection having a default value, like `ami` above.

The technical design challenge here is that what we have in the second argument of `convert` above (and what would also be in the `type` argument in a variable declaration) is no longer really a "type constraint" anymore, but some other kind of thing which describes both a required type _and_ some transformation rules. We'll need to design whatever this new thing is called and replace the existing concept of type constraints with it in the `variable` block syntax, and then later if we add this `convert` function use it there too.

I certainly think it's doable, but it'll take some further design work and prototyping to see how best to implement it. It's for this and other related reasons that the optional attributes mechanism is remaining experimental for the moment.

Thanks for the feedback!

**Comment by jw-maynard** [comment]
@apparentlymart No problem. It's weird to me for the language to have to concept of a default for the whole variable that is somehow different than the default to some members of collections that are part of the variable. I guess I could be the odd person out in the community but it seems that I would want one default value.

In any case, my main concern with the current implementation (which I know is still just an experiment and subject to change) is that things related to the way a variable is defined and handled end up in `variable` blocks and `locals` blocks where I would prefer to just look at one `variable` block and be able to get a good idea of what types the variable expects, what parts of it are optional, *and* what the values of those optional items will be. It sounds like this is your end goal with is great. Thanks for the clarification. I'll close this issue out to help keep things clean around here.
