### ISSUE TITLE
terraform -install-autocomplete not working on MacBook Pro M1 Silicon Big Sur 11.2.3

### ISSUE THREAD

**Issue by brightblueray** [hashicorp/terraform#28493]
### Terraform Version

```
Terraform v0.15.0-dev
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0
```

### Terraform Configuration Files

```
 .zshrc
...
# updated .zshrc
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
...
```

### Actual Behavior

After executing `terraform -install-autocomplete` and spawning a new shell I would see the error:
`complete:13: command not found: compdef`
### Steps to Reproduce

`terraform -install-autocomplete`
### Additional Context

Changing .zshrc to the following resulted in a working autocompletion:
```
autoload -Uz +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
```

**Comment by apparentlymart** [comment]
Hi @brightblueray! Sorry for the long silence here... apparently I missed this when you first opened it.

I'm revisiting this today and noting that it seems the crucial difference that made this work for you was the additional line in your `.zshrc`:

```
autoload -Uz +X compinit && compinit
```

We delegate to a third-party for this completion-installation behavior, so I'm not personally familiar with how zsh works. However, I do see [some relevant documentation](https://www.csse.uwa.edu.au/programming/linux/zsh-doc/zsh_23.html) including some information about this `compinit` command, which indeed does seem to define the `compdef` command.

However, I'm noticing that this issue only has one upvote in addition to you opening it and I don't see any comparable issue in [the upstream `github.com/posener/complete` repository](https://github.com/posener/complete), and so that leaves me wondering why adding this extra line was apparently necessary for you and one other person here but nobody else seems to have any problem, either with Terraform's use of this library or with any other use.

Does macOS perhaps ship with a default `.zshrc` which includes `compinit`, but that you don't have on your system?

We could potentially ask upstream to consider adding this `compinit` line in addition to the other lines it automatically adds, but before we do so I'd like to understand better why that was necessary for you and whether doing so is likely to cause problems for anyone for which the existing commands are already (somehow) working.

Thanks!

**Comment by crw** [comment]
I am doing clean-up on old `waiting-response` issues. As this issue has not seen a response since the previous post, I am going to close this. Please let me know if you are experiencing this issue and can answer the questions raised in the previous post. Thanks!
