### ISSUE TITLE
How to submit project metadata on GCE

### ISSUE THREAD

**Issue by wint00** [hashicorp/terraform#2849]
How does one submit project metadata in GCE? Not seeing an option in the provider (there is one for instance metadata) I tried to just stick it in one of the resources I was creating by doing a local-exec to gcloud but that seems to get ignored. 

Is there someplace I can put it where it'll run the gcloud script before it does anything else or should I just wrap it in a bash script before executing the apply?

**Comment by sparkprime** [comment]
Sorry for the late reply.  There is nothing yet, but we have a plan to create a resource that represents a key value pair, or a set of them.  So that will let you manage the project metadata.  If you did the bash script thing, that sounds like a reasonable workaround for now.  We'll keep you posted.

**Comment by sparkprime** [comment]
The new resource should be available shortly :)
