### ISSUE TITLE
Has any one worked with attaching multiple Elastic Inference accelerators with EC2 instance in AWS. I am getting error while provisioning this scenario using terraform.

### ISSUE THREAD

**Issue by ashish60808** [hashicorp/terraform#28515]
### Terraform Version

```
v0.14.2
```

### Terraform Configuration Files

```
resource "aws_launch_template" "service" {
  name_prefix   = "***************"
  key_name             = "**************"
  image_id             = "**************"
  instance_type        = "**************"
  # security_groups      = "**************"
  vpc_security_group_ids = "**************"

  iam_instance_profile {
    name = "***************"

  user_data            = var.user_data
  
#attaching first accelrator
  elastic_inference_accelerator {
    type = var.ia_instance_type
  }

#attaching second accelrator
  elastic_inference_accelerator {
    type = var.ia_instance_type
  }

  }

}
```

### Crash Output

```
Error: List longer than MaxItems on main.tf line 9, in resource "aws_launch_template" "service": 9: resource "aws_launch_template" "service" { Attribute supports 1 item maximum, config has 2 declared 
```

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
