### ISSUE TITLE
Terraform count (sometimes) doesn't work with data sources

### ISSUE THREAD

**Issue by nmiculinic** [hashicorp/terraform#28519]
### Terraform Version

```
 △ nmiculinic@atlas grid/infra/global terraform version                                                                                                                                                                 23s nmiculinic/gi-3456-enable-spot-on-be-update-python-api 14m ● ⬢
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.9.4
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/google v3.54.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Terraform Configuration Files

```terraform
data "aws_availability_zones" "available" {}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.78.0"
  name    = var.cluster_name
  cidr    = "10.0.0.0/16"
  azs     = data.aws_availability_zones.available.names
  public_subnets = [
    # 4,096 IPs
    "10.0.16.0/20",
    "10.0.32.0/20",
    "10.0.48.0/20",
  ]
  private_subnets = [
    # 16384 IPs
    "10.0.64.0/18",
    "10.0.128.0/18",
    "10.0.192.0/18",
  ]
  enable_dns_hostnames = true
  enable_nat_gateway   = true
  single_nat_gateway   = true
  tags                 = local.tags

  private_subnet_tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"           = "1"
  }

  public_subnet_tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                    = "1"
  }
}
```

### Debug Output

https://gist.github.com/nmiculinic/df9b2b16ce71fee84ca92c815cbc7548

### Expected Behavior

* Terraform applied without any issues

### Actual Behavior

```
│ Error: Invalid count argument
│ 
│   on .terraform/modules/test_suite_cluster.vpc/main.tf line 371, in resource "aws_subnet" "public":
│  371:   count = var.create_vpc && length(var.public_subnets) > 0 && (false == var.one_nat_gateway_per_az || length(var.public_subnets) >= length(var.azs)) ? length(var.public_subnets) : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context

* I have the same module being used in other terraform state files,....yet they don't exhibit this bug. This vpc is within a module, thus the full address is: `module.test_suite_cluster.module.vpc` . I have other modules importing this module `module.cluster.module.*` and they are operating just fine. 
* Also this wasn't an issue with terraform v0.14.x

**Comment by apparentlymart** [comment]
Hi @nmiculinic,

After doing some digging into your trace log I found the following which seems to suggest a cause for what you've seen here:

```
2021-04-26T17:34:05.290+0200 [TRACE] attachDataDependenciesTransformer: module.test_suite_cluster.data.aws_availability_zones.available depends on [aws_s3_bucket.spot_datafeed aws_spot_datafeed_subscription.main]
```

This log comes from the result of Terraform identifying all of the managed resources that are direct or indirect dependencies of `module.test_suite_cluster.data.aws_availability_zones.available`.

Since those resources belong to the root module (they have no `module.test_suite_cluster.` prefix), I'm guessing that the `module "test_suite_cluster"` block has a `depends_on` declaration like this:

```hcl
  depends_on = [
    aws_s3_bucket.spot_datafeed,
    aws_spot_datafeed_subscription.main,
  ]
```

Configuring `depends_on` for a module means that everything in the module must therefore depend on what you specified, and that includes `module.test_suite_cluster.data.aws_availability_zones.available`. In turn this means that if the plan includes an modifications to either `aws_s3_bucket.spot_datafeed` or `aws_spot_datafeed_subscription.main` then Terraform must wait until the apply step to read `module.test_suite_cluster.data.aws_availability_zones.available`, and thus its result won't be known during planning and therefore you can't use it (indirectly, in this case) in `count`.

Can you confirm whether you have a `depends_on` declared in that way? If so, unfortunately what you've seen here is Terraform working as intended, because you've told Terraform to defer processing everything in that module until after those two managed resources are ready.

**Comment by nmiculinic** [comment]
Wow, first thank you for amazing reply! And you were dead right, I had `depends_on` in the module in question:

```terraform
resource "aws_s3_bucket" "spot_datafeed" {
  bucket = var.spot_datafeed_bucket

  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-data-feeds.html
  # datafeed subscription creates some grant privileges
  # Thus upon re-apply those would be deleted
  lifecycle {
    ignore_changes = [
      grant,
    ]
  }
}

resource "aws_spot_datafeed_subscription" "main" {
  bucket = aws_s3_bucket.spot_datafeed.bucket  
  prefix = var.spot_datafeed_bucket_prefix
}
```
