### ISSUE TITLE
Azure provider do not support user_data

### ISSUE THREAD

**Issue by stonevil** [hashicorp/terraform#2851]
Azure provider do not support user_data. I cannot automatically deploy CoreOS cluster at Azure without this options.

**Comment by stonevil** [comment]
Ok. I can do almost this same with provision file and remote-exec

**Comment by stonevil** [comment]
It cannot do this same with provision file and remote-exec.

Please add support for user_data (custom_data for Azure)

**Comment by mtekel** [comment]
+1

**Comment by saliceti** [comment]
definitely +1

**Comment by keymon** [comment]
+1

**Comment by aznashwan** [comment]
@everyone: sadly; at the time of the writing of the Azure provider for Terraform; the go sdk was based on the old ASM API's which made sending userdata difficult. As a result; even nowadays the go sdk does not support instance user_data over the old ASM API's.

The addition of the new ARM API's should lead to the enablement of all these problems though.
For updates on the status of the transition; please refer to https://github.com/hashicorp/terraform/issues/3212

**Comment by skevy** [comment]
@aznashwan It seems like it IS possible to do user data with the current SDK:

https://github.com/Azure/azure-sdk-for-go/blob/1a29bf058b780f6a05fc67111efae7930c4a1621/management/virtualmachine/entities.go#L349

I know you guys are moving to ARM from ASM, but this would be a relatively easy fix if we do something a bit custom here: https://github.com/Azure/azure-sdk-for-go/blob/1a29bf058b780f6a05fc67111efae7930c4a1621/management/virtualmachine/entities.go#L349, instead of relying on their helper (which doesn't take custom data).

Would you accept a PR for this as a stop gap solution? Not having custom data on azure really limits it's use case for me (and I presume many others).

**Comment by stack72** [comment]
Closed via #8158
