### ISSUE TITLE
Usage of "location" parameter in aws-dx_connection resource

### ISSUE THREAD

**Issue by ShabiaYosuvaraj** [hashicorp/terraform#28526]
Hello there, 
With regards to DX connection creation in AWS provider, t here seems to a tricky part in this resource:
resource "aws_dx_connection" "hoge" {
 name     = "tf-dx-connection"
 bandwidth = "1Gbps"
 location = "EqDC2"
}
The parameter “location” uses a location code which could be fetched from “describelocations” API whose output could be as follows :
[
 {
   "region": "us-west-2",
   "locations": [
     {
       "locationCode" = "EqSe2-EQ",
       "locationName" = "Westin Building Exchange, Seattle, WA | Equinix, SE2, Seattle, WA"
     },
     {
       "locationCode": "EqSe2-EQ",
       "locationName": "Westin Building Exchange, Seattle, WA | Westin Building Exchange - SEA10 - Main FMMR, Seattle, WA"
     },
     {
       "locationCode": "EqSe2-EQ",
       "locationName": "Switch SUPERNAP 8, Las Vegas, NV"
     },
     {
       "locationCode": "EqSe2-EQ",
       "locationName": "EdgeConnex, Hillsboro, OR"
     },
Now, if you could see the location code remains the same and differential part which is location name cannot be passed as a complete string and not even as a map variable.. It just takes the “locationcode” and executes it sequential order.. So.. if I want to get the third location, it is getting deployed only in the third go.. how could this be resolved without having to deploy the code multiple times?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
