### ISSUE TITLE
How long will each version of terraform keep getting updates?

### ISSUE THREAD

**Issue by RayBB** [hashicorp/terraform#28538]
How long will each version of terraform keep getting updates?
In particular how long will you "provide version updates to the 0.14.x branch"

I can't seem to find this mentioned anywhere in the docs or repo.

The reason why this would be helpful because it helps the homebrew team decide what versions to support and for how long. You can read more here: https://github.com/Homebrew/homebrew-core/pull/75981#issuecomment-828273014

I also Tweeted some folks in hopes of getting an answer https://twitter.com/RayScript/status/1387416011842809857

Thanks

**Comment by apparentlymart** [comment]
Hi @RayBB,

I replied over in the Homebrew issue because that seemed like a better place to have this discussion, where it would be more visible to folks interested in it. Since this issue isn't a bug report or a feature request I'm going to close it just to keep our ticket queues moving along, but I'm happy to keep talking about it if you'd like clarifications on what I wrote over there.
