### ISSUE TITLE
Wrong release listed as 'latest' in github

### ISSUE THREAD

**Issue by ajchiarello** [hashicorp/terraform#28530]
I have a system that automatically pulls the release marked as 'latest' on github, and was surprised when it pulled version 0.11.15 this morning instead of 0.15.1 - did you intend to mark 0.11.15 as 'latest'?

**Comment by jbardin** [comment]
Hi @ajchiarello,

I don't think there is any way to define what "latest" means in the GitHub UI. It appears that GitHub uses that to mean "most recent", and 0.11.15 is the most recent tag in the repo.

**Comment by apparentlymart** [comment]
Yes, GitHub's idea of "latest release" is the release with the newest Git tag, and so it's not really a useful signal for anything except GitHub deciding what to show in the UI.

If you noticed this because you built some automation around GitHub's idea of latest then I would suggest using a different strategy to decide "latest", because GitHub's idea of "latest" is not fit for that purpose and isn't something we can customize. One other possibility is to use [the JSON index of releases on `releases.hashicorp.com`](https://releases.hashicorp.com/terraform/index.json), which is something we directly control as part of our release process. The index isn't in any particular order but you can apply your own ordering using typical version precedence functions.

**Comment by ajchiarello** [comment]
Ah - thanks, I had misunderstood how the latest tag was applied, and had gotten lucky in the past. I'll use a different method to pull the version.

**Comment by minamijoyo** [comment]
TIL: The git command can sort tags in semver order.

```
$ git -c 'versionsort.suffix=-' ls-remote --refs --tags --sort='v:refname' https://github.com/hashicorp/terraform | tail -n 1 | cut -d'/' -f3 | sed s/^v//
0.15.1
```
