### ISSUE TITLE
Azure Backend fails with command line parameters

### ISSUE THREAD

**Issue by Christian4K** [hashicorp/terraform#28537]
Hi team,

we need to configure terraform via command line parameter and this worked before 0.15.0. Now we see this function is broken

We use:

```
  terraform init \
      -backend-config="storage_account_name=${tfstateAccountName}" \
      -backend-config="container_name=${tfstateContainer}" \
      -backend-config="access_key=${tfstateAccountKey}" \
      -backend-config="key=${tfstateKeyName}" 
```

together with an empty definition in main.tf

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.56.0"
    }
    azuread = {
      version = "~>1.4.0"
    }
  }

  backend "azurerm" {  
  } 
}
```

When we now run this against a fresh fetch without terraform.tfstate in the working directory terraform asks for input and stops

```
Initializing modules...

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.


container_name
  The container name.

  Enter a value:
```
The same happens for the other parameters if we give others in the main.tf file.

If we cancel this a tfstate file is created and with the second run the processes continues as usual. 

### Terraform Version
Terraform v0.15.1

### Expected Behavior

terraform init can be configured via command line parameters and execute with the first run

**Comment by jbardin** [comment]
Hi @Christian4K,

The behavior here sounds like the incorrect configuration was stored to one point. Can you verify if this works if you add the `-reconfigure` flag to `init` which will ignore any stored configuration?

**Comment by Christian4K** [comment]
Hi,

I added the reconfigure and there is no change in the behaviour. Also checked with 0.15.3 and failing the same.

In our setup for each run the local state etc. is recreated. So there should be nothing from last run

I get prompts for all 4 command line parameter. I can simply type in anything random, but afterwards the parameter as set by the command line is correctly stored in the tfstate and a second run without removing the state etc. is successfull.

**Comment by jbardin** [comment]
Thanks @Christian4K,

Can you show the exact series of commands you use to trigger the issue? It appears you are initializing terraform with the shown backend config, then running `init` again without that configuration which will cause the problem shown. If you want to run `init` without changing the backend at all, you can use the `-backend=false` flag to skip that part of the initialization sequence. However, since you already have run `init` and have the providers and modules installed, you can likely just skip the latter command which is causing the problem.

**Comment by jbardin** [comment]
Hello,

Since we have not heard back in a while I'm going to close the issue.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
