### ISSUE TITLE
Optionally allow for extra arguments to format()

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#28558]
### Current Terraform Version

```
Terraform v0.15.1
on darwin_amd64
```

### Use-cases

In many situation, I like to be able to accept a `format` string as input to allow for customization of things like AWS IAM role names or AWS Parameter Store keys. Because the `format` string allows indexed addressing of variables, this is a very flexible solution, because I can provide a static list of possible inputs and people can rearrange them as they like and omit variables they don't want.

```hcl
  # Construct the SSM parameter store key name for where to store the database user's password
  ssm_key_name = format(var.format_string, var.region, var.stage, var.service, var.db_name, var.db_username)
```
So you can set
```hcl
  var.format_string = "/%[5]v"
```
and `ssm_key_name` will be set to `"/${var.db_username}"`

### Attempted Solutions

This works if, and only if, the `format` string references the last variable in the list. Otherwise, it fails with an error `too many arguments`.

### Proposal

Have some way to disable the check for `too many arguments`. Could be a separate function `format_nocheck`, could be a special flag in the `format` string, could be something else, but should not be a command line option. It should be something completely contained in the code.

### References

- https://github.com/hashicorp/terraform/issues/9256
- https://github.com/hashicorp/terraform/pull/19690

**Comment by apparentlymart** [comment]
Thanks for sharing this use-case, @Nuru.

Although the specific proposal is different, I think the underlying use-case you've shared here is the same as #26838, and so I'm going to close this one just to consolidate the design discussion over there. I expect we'd prefer to meet this use case using Terraform's own template language rather than the `format` minilanguage, because it's a superset of the format language (you can call `format` inside it) and it typically results in a template that is easier to understand without referring to the call in order to see which values are assigned into which positional arguments.

With that said, we'd ideally like to find a way to do it that doesn't lead to the need for writing escaped templates inside templates, because `"$${foo}"` instead of `"${foo}"` is pretty hard to write and maintain correctly. The desire for a more integrated solution is what has caused us to hold on solving this right now, until we have some time to do some more thorough design work.
