### ISSUE TITLE
Issus with aws_network_interface

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#2855]
```
terraform version
Terraform v0.6.2-dev (8ce3d49895095bbb505d61ead7f79985a04172e3)
```

I am trying to create a better solution for NAT using terraform. Basically, I am doing the following:

```
resource "aws_eip" "nat_ip" {
  vpc = true
  network_interface = "${aws_network_interface.nat_eni.id}"
}

resource "aws_network_interface" "nat_eni" {
  subnet_id = "${aws_subnet.primary-public.id}"
  security_groups = ["${aws_security_group.nat.id}"]
  source_dest_check = false
}
```

On each terraform apply, I get the following

```
-/+ aws_network_interface.nat_eni
    private_ips.#:             "1" => "0" (forces new resource)
    private_ips.1571815317:    "10.0.33.72" => ""
    security_groups.#:         "1" => "1"
    security_groups.409314681: "sg-9d4f7ef8" => "sg-9d4f7ef8"
    source_dest_check:         "false" => "0"
    subnet_id:                 "subnet-03e99c66" => "subnet-03e99c66"

~ aws_eip.nat_ip
    network_interface: "eni-7362a214" => "${aws_network_interface.nat_eni.id}"
```

There is nothing in my code changing but the network interface is changing which is making my code changes break

Paul

**Comment by apparentlymart** [comment]
In your code example I don't see ``private_ips`` on your ``nat_eni`` interface. Since your interface apparently already has a private IP assigned it thinks that's a change.

Did you apply this without a ``private_ips`` parameter in the first place, when the interface was created? If so I expect the AWS API is providing a default private IP when none are provided, and so on subsequent runs Terraform is trying to force it back to having no IP addresses again.

Perhaps the fix is for the resource implementation to declare this attribute as ``Computed: true`` so that Terraform will expect the server to provide a value for it:
https://github.com/hashicorp/terraform/blob/b6b3626f90acc22173076ef44d414b723e2af0b8/builtin/providers/aws/resource_aws_network_interface.go#L35

**Comment by stack72** [comment]
@apparentlymart agreed that I haven't specified one. But the docs say it's optional. I would assume that one gets applied on the first run but I wouldn't expect terraform to regenerate the ENI on *every* run

That seems like a bug?

**Comment by apparentlymart** [comment]
Yes, I think it is a bug. Sorry I wasn't clearer, but in my comment I was noting a possible fix in the code, not saying you did something wrong.

**Comment by stack72** [comment]
@apparentlymart looks like this [PR](https://github.com/hashicorp/terraform/pull/2743) may have fixed the issue for me :)

Testing it now

**Comment by stack72** [comment]
@apparentlymart it does indeed fix it :)

```
aws_network_interface.nat_eni: Creating...
  private_ips.#:             "" => "<computed>"
  security_groups.#:         "" => "1"
  security_groups.409314681: "" => "sg-9d4f7ef8"
  source_dest_check:         "" => "0"
  subnet_id:                 "" => "subnet-03e99c66"
aws_network_interface.nat_eni: Creation complete
aws_eip.nat_ip: Creating...
  allocation_id:     "" => "<computed>"
  association_id:    "" => "<computed>"
  domain:            "" => "<computed>"
  network_interface: "" => "eni-619f5306"
  private_ip:        "" => "<computed>"
  public_ip:         "" => "<computed>"
  vpc:               "" => "1"
aws_eip.nat_ip: Creation complete
```

Then on subsequent runs doesn't change anything :)

**Comment by apparentlymart** [comment]
Great! I'm glad someone already caught that and fixed it.
