### ISSUE TITLE
"null_data_source deprecated -> the same can now be achieved using locals" is a false statement(?)

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [hashicorp/terraform#28563]
Hi,
so I'm getting this warning:
```
│ Warning: Deprecated Resource
│ 
│   with module.my_module.data.null_data_source.foo,
│   on ../modules/.../outputs.tf line 1, in data "null_data_source" "foo":
│    1: data "null_data_source" "foo" {
│ 
│ The null_data_source was historically used to construct intermediate values to re-use elsewhere in configuration,
│ the same can now be achieved using locals
│ 
│ (and 2 more similar warnings elsewhere)

```
Let's say that I have a list of strings and now I'd like to remove a dot '.' at the end of each of them, the only reasonable way I found to do so is the following:
```
data "null_data_source" "foo" {
  count = length(aws_route53_zone.selected.*.name)

  inputs = {
    name = trimsuffix(aws_route53_zone.selected[count.index].name, ".")
  }
}
```
I didn't find a way to do the same with `locals`. Please correct me if I'm wrong.

**Comment by jbardin** [comment]
Hi @heprotecbuthealsoattac,

What you want can be achieved using a [for expression](https://www.terraform.io/docs/language/expressions/for.html).

```
locals {
  trimmed = [ for name in aws_route53_zone.selected.[*].name : trimsuffix(name, ".") ]
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. 

Thanks!
