### ISSUE TITLE
Why am I unable to add a depends_on block to a module with provider configuration?

### ISSUE THREAD

**Issue by OliveiraLeonardo17** [hashicorp/terraform#28580]
When writing examples for my Terraform module, I got the error: "Module contains provider configuration" "Providers cannot be configured within modules using count, for_each or depends_on."

I got this error when I tried to add a depends_on block to the module's declaration to avoid trying to run the module plan before the creation of the resource group needed to deploy the resources inside the module.

If I don't add the depends_on block it also breaks, because it can't find the declared resource group that should be created before the module runs to populate the required resource group data source.

I find it is at least uncomfortable to require the removal of the providers block or to remove all the data sources.

I couldn't find any details on this error, or on how to fix it.

[Specific line that raises this error inside Terraform's code.](https://github.com/hashicorp/terraform/blob/6bed3008a5d993bd89b2dafa101ebcd9cbced5a0/configs/provider_validation.go#L103)

**Comment by jbardin** [comment]
Hi @OliveiraLeonardo17,

Providers should not be configured within modules for various reasons, and most configuration expects the desired provider to be passed down from the root module. This will allow modules to use more complex features like `count`, `for_each` and `depends_on`. It is also not recommended to have a data source and a managed resource that represent the same resource within a configuration to avoid dependency issues like this.

In this case if you must have a provider in the module, and you must have separate data and managed resources, you will need to create the dependency for the data sources in some other way. Since all you really need here is for the data source itself to have a `depends_on`, I would suggest passing in the data to the module and storing it in a resource like `null_resource` where the changes can trigger the data source to be re-read as needed.

Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
