### ISSUE TITLE
When creating an NS record, you need to specify a period on the end

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#2858]
The documentation shows the following:

```javascript
resource "aws_route53_record" "dev-ns" {
    zone_id = "${aws_route53_zone.main.zone_id}"
    name = "dev.example.com"
    type = "NS"
    ttl = "30"
    records = [
        "${aws_route53_zone.dev.name_servers.0}",
        "${aws_route53_zone.dev.name_servers.1}",
        "${aws_route53_zone.dev.name_servers.2}",
        "${aws_route53_zone.dev.name_servers.3}"
    ]
}
```

But, if you don't want it to resolve to dev.example.com.example.com, you need to add a period on to the end of the "name" attribute.   I don't know if this is a bug in the documentation, or the way it works, however, I do know that in *all* other circumstances, leaving the period off the end of the name seems to work fine.

(_updated by @catsby for formatting_)

**Comment by catsby** [comment]
Hey @dansteen – sorry for the silence here. I believe this issue is fixed. 
Given this config:

```hcl
resource "aws_route53_zone" "primary" {
   name = "notexample.com"
}

resource "aws_route53_record" "dev-ns" {
    zone_id = "${aws_route53_zone.primary.zone_id}"
    name = "dev.notexample.com"
    type = "NS"
    ttl = "30"
    records = [
        "${aws_route53_zone.primary.name_servers.0}",
        "${aws_route53_zone.primary.name_servers.1}",
        "${aws_route53_zone.primary.name_servers.2}",
        "${aws_route53_zone.primary.name_servers.3}"
    ]
}
```

I'm getting a record as I would expect it `dev.notexample.com`:

<img width="587" alt="screen shot 2015-11-17 at 3 59 38 pm" src="https://cloud.githubusercontent.com/assets/61721/11226230/473a61dc-8d44-11e5-8ac2-d2598433e864.png">


I'm going to go ahead and close this. If I'm misunderstanding something please let me know.
Thanks!

**Comment by dansteen** [comment]
Looks good. Thanks for all your work!
