### ISSUE TITLE
unknown provider "registry.terraform.io/hashicorp/application"

### ISSUE THREAD

**Issue by hequ** [hashicorp/terraform#28596]
### Terraform Version

```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    azurerm = {
      version = "=2.55.0"
    }
  }

  backend "azurerm" {
    container_name       = "terraform"
    key                  = "terraform.tfstate"
    resource_group_name  = ""
    storage_account_name = ""
    subscription_id      = ""
  }
}
```

### Expected Behavior

`terraform plan` should print out the plan like it did yesterday

### Actual Behavior
```
terraform plan
╷
│ Error: Could not load plugin
│
│
│ Plugin reinitialization required. Please run "terraform init".
│
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│
│ failed to instantiate provider "registry.terraform.io/hashicorp/application" to obtain schema: unknown provider "registry.terraform.io/hashicorp/application"
```

### Steps to Reproduce
`terraform plan`

### Additional Context
This worked yesterday just fine. If I go and check terraform registry for that `hashicorp/application` provider, it's not there. Also If I delete the `.terraform` directory and run `terraform init --reconfigure`, then it fails for the same reason that it cannot download the required module `hashicorp/application`.

**Comment by jbardin** [comment]
Hi @hequ,

You haven't shown any configuration here, but you must have something within your configuration that is requiring a provider called "application" . If you're unsure which module to start with, you can use the `terraform providers` command to see what modules require which providers.

Since you are using the azurerm provider, my best guess us that you have a typo in a resource type name like `azurerm_application_insights ` where you left out the `azurerm_`  prefix. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
