### ISSUE TITLE
EC2 Fleet takes longer than usual to get destroyed

### ISSUE THREAD

**Issue by saranpaladugu** [hashicorp/terraform#28590]
The EC2 Fleet which I'm trying to terminate changes the state within 2 minutes but terraform takes 6 minutes to completely destroy the EC2 fleet. The initial state in the AWS dashboard is request-canceled-and-instance-running which then changes to instance-terminated-by-user after about 3 minutes when terraform has to complete the destruction process but the process is elapsed until 6 minutes. Please find attached outputs.

<img width="565" alt="tf1" src="https://user-images.githubusercontent.com/83602359/116907259-f8453b00-ac06-11eb-8c0c-f60c39b0f797.PNG">
<img width="642" alt="tf2" src="https://user-images.githubusercontent.com/83602359/116907261-f8ddd180-ac06-11eb-8cad-50db27731e86.PNG">
<img width="638" alt="tf3" src="https://user-images.githubusercontent.com/83602359/116907264-fa0efe80-ac06-11eb-9cfc-3d649972ccdc.PNG">

The code used to deploy is pasted below
`resource "aws_ec2_fleet" "viewer-tool-fleet" {
  launch_template_config {
     launch_template_specification {
	   launch_template_name = "test"
	   version = 1
	 }
  }
  target_capacity_specification {
    default_target_capacity_type = "spot"
	total_target_capacity = 1	
  }
  terminate_instances  = true
  terminate_instances_with_expiration = true
}`

**Comment by apparentlymart** [comment]
Hi @saranpaladugu,

The behavior you're describing here is implemented in the AWS provider rather than in Terraform CLI, so please open an issue about it in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws). If you do, please pay attention to that repository's bug report template and be sure to provide the information they requested so that they'll be able to start investigating.

Thanks!
