### ISSUE TITLE
Changing provider on exsisting resource

### ISSUE THREAD

**Issue by per-lind** [hashicorp/terraform#28597]
Not sure if this is a bug or by design but the behavior was unexpected. 
Not sure if this is terraform itself or the openstack provider, have not testet it with other providers.

### Terraform Version

```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.41.0
```

### Terraform Configuration Files

```terraform
provider "openstack" {
  auth_url            = "https://xxx:5000"
  region              = "xxx"
  user_domain_name    = "xxx"
  project_domain_name = "xxx"
  use_octavia         = "true"
  tenant_name         = "xxx"
}
provider "openstack" {
  alias               = "sto1hs"
  auth_url            = "https://yyy:5000"
  region              = "yyy"
  user_domain_name    = "yyy"
  project_domain_name = "yyy"
  use_octavia         = "true"
  tenant_name         = "yyy"
}
resource "openstack_compute_instance_v2" "test" {
#  provider        = openstack.sto1hs
  name            = "test"
  image_name      = "CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2"
  flavor_name     = "2C-4GB-50GB"
  network {
    uuid = "5e798b2c-0e8b-4e8a-8c1e-2c307417b56f"
  }
}
terraform {
  required_providers {
    openstack = {
      source = "terraform-provider-openstack/openstack"
    }
    template = {
      source = "hashicorp/template"
    }
  }
  required_version = ">= 0.13"
}
```

### Debug Output

https://gist.github.com/per-lind/bcc433f1fcffa7ba89bc4bef8032c16c
### Expected Behavior

Expected the resource to be replaced or a better error message pointing out the resources causing the error.
### Actual Behavior

Error: Error creating OpenStack compute client: No suitable endpoint could be found in the service catalog.
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `uncomment line with provider`
4. `terraform apply`

**Comment by jbardin** [comment]
Hi @per-lind,

The lack of context in this error was recently fixed by #28543, and should be in the next release.

I don't think changing the provider in the configuration is going do what you assume however. Changing out the `provider` argument in the resource will have the exact same effect as if you changed the configuration of the original provider, meaning that the original resource may be abandoned, and a new resource will be created. The existing resource may also have stored attributes that are not useable in the new environment, which appears to be the issue here. Handling the unexpected resource configuration would be up to the provider to do, however it may not be possible to provide a better error when attempting to read resources from a different provider configuration.

Thanks!
