### ISSUE TITLE
Terraform complains that two input vars sourced from a tfvars file during apply are "not known until after apply"

### ISSUE THREAD

**Issue by amartopoulos** [hashicorp/terraform#28633]
### Terraform Version

0.15.1
```
...
```

### Terraform Configuration Files

The count parameter below is triggering the error

```data "aws_vpc" "peer_vpc" {
  count    = var.adm_account_name != var.account_name ? 1 : 0 && false == var.is_primary_region ? 0 : 1
  provider = aws.peer
  depends_on = [
    aws_vpc.vpc
  ]
}
```

### Expected Behavior

Terraform should have sourced the tfvars values and made them available to the count parameter to use as conditional arguments as it has in past versions.

### Actual Behavior

The following error was returned:
```
│ Error: Invalid operand
│ 
│   on region/vpc/peering-connections.tf line 12, in data "aws_vpc" "peer_vpc":
│   12:   count    = var.adm_account_name != var.account_name ? 1 : 0 && false == var.is_primary_region ? 0 : 1
│     ├────────────────
│     │ var.account_name will be known only after apply
│     │ var.adm_account_name will be known only after apply
│ 
│ Unsuitable value for left operand: bool required.
```
### Steps to Reproduce

terraform plan -detailed-exitcode -input=false -var-file env/adm.tfvars -var-file env/<SNIPPED>.tfvars -out=adm.tfplan

**Comment by jbardin** [comment]
Hi @amartopoulos,

Thanks for filing the issue. Can you supply a complete configuration which demonstrates the problem? Since the configuration reference appears to be within a module, it's possible the variables supplied via the tfvars files may not be directly passed into that module, and only coincidentally have the same name. We need to see how the values within the module are derived to know why they are unknown at that time.

Thanks!
