### ISSUE TITLE
curl: (6) Could not resolve host: github.com

### ISSUE THREAD

**Issue by rutvikpensionwar** [hashicorp/terraform#28630]
### Terraform version

```
0.11.15
```

### Steps to reproduce

**Dockerfile**
```
FROM hashicorp/terraform:0.11.15

RUN apk update && apk add curl
RUN curl https://github.com
```

Go to directory and run `docker build .`

### Error

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
The command '/bin/sh -c curl https://github.com' returned a non-zero code: 6
```

Possible that DNS isn't working properly, not sure. Please help!

**Comment by jbardin** [comment]
Hi @rutvikpensionwar,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific Terraform bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
