### ISSUE TITLE
Need a way to show sensitive changes

### ISSUE THREAD

**Issue by fdw** [hashicorp/terraform#28635]
### Current Terraform Version
```
0.15.1
```

### Use-cases
One resource (`aws_elastic_beanstalk_environment`) has always changes, even though the configuration hasn't changed. Unfortunately, I can only see that the changes are in the `setting`s, but the whole block is hidden, as at least one is senstive. That makes it impossible for me to find out which setting is seen as different.

### Attempted Solutions
I tried to use `terraform show -json`, as that doesn't hide sensitive values. However, that only shows me the current state and not the proposed change.

### Proposal
I would like to have some option to see even sensitive changes. Maybe it would be enough to just see the other `setting`s blocks, or just the context without the sensitive value.

### References
I have found none.

**Comment by jbardin** [comment]
Hi @fdw,

You had the right idea by using the full json output, but you need supply the plan as the argument to show the changes it contains, `terraform show -json plan file` 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by fdw** [comment]
Thanks for your help!

However, using `terraform show` is a very convoluted way to do what I wanted, namely showing the planned changes. I had to parse the json file myself, find the affected resource (because the plan lists all), extract the before and after blocks and compare those.
Instead of that process, I would like to be able to use terraform's usual output at `apply` or `plan` which clearly shows what is about to be changed. Maybe it is possible to add a `-show-senstive` flag that will show changes even if they're marked sensitive.
