### ISSUE TITLE
Uploading a large file to AWS with Resource: aws_s3_bucket_object

### ISSUE THREAD

**Issue by NathanDotTo** [hashicorp/terraform#28678]
### Terraform Version
```
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.39.0
```

### Terraform Configuration Files
```terraform
resource "aws_s3_bucket_object" "object" {
  bucket = "x-ova"
  key    = "x/x.ova"
  source = "/x/x/Virtual Machines.localized/x.ova"

  # The filemd5() function is available in Terraform 0.11.12 and later
  # For Terraform 0.11.11 and earlier, use the md5() function and the file() function:
  # etag = "${md5(file("path/to/file"))}"
  etag = filemd5("/x/x/Virtual Machines.localized/x.ova")
}
```

### Debug Output

https://gist.github.com/NathanDotTo/65c5bb215a9f88090d58145463155a68

### Crash Output
NA

### Expected Behavior
The file should have been copied to the S3 bucket with the given key.

### Actual Behavior
Hard to tell, but the file was not copied, and there was no error output.

Note that the file in question is ~80GB. It is hard to tell whether Terraform will attempt a multipart-upload, as the documentation makes no mention of this. 

### Steps to Reproduce
 `terraform apply`

### Additional Context
I am using this resource:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object

The implication is that the file identified by `source` will be uploaded. In practice, I know that large files have been problematic in the past. See: https://github.com/hashicorp/terraform/issues/14693

I can't tell whether this *should* work for an ~80GB file.

### References
- #14693

**Comment by NathanDotTo** [comment]
I have tried the suggestion of commenting out the `etag` line. There is still an issue, but not with the core code, so see:

https://github.com/hashicorp/terraform-provider-aws/issues/19336

**Comment by apparentlymart** [comment]
Thanks for the follow-up, @NathanDotTo!

For my part I did the optimization I described before in #28681, and so that should be in the next release.

As part of implementing that I revisited the historical context behind those functions and remembered that the backstory here was that these functions were originally a pragmatic workaround for the v0.11-and-earlier pattern of using constructions like `md5(file(...))` to compute hashes for files, which happened to work in v0.11 just because that generation of the language was inconsistent in whether strings were strings of bytes or strings of unicode codepoints. Since v0.12 and later began using unicode strings throughout, `md5(file(...))` was no longer appropriate for binary files and so we added `filemd5(...)` and similar along with an automatic migration in `terraform 0.12upgrade` to use them.

Given that heritage, their implementation was essentially the same as `md5(file(...))` but as an implementation detail within Terraform rather than in the public interface. However, since that _is_ now purely an implementation detail I was able to change it in #28681 while keeping the behaviors functionally equivalent to before, just now using less memory in the case of a huge file.
