### ISSUE TITLE
Terraform scheduled environments

### ISSUE THREAD

**Issue by secureoptions** [hashicorp/terraform#28676]
Hi Team, we are using Terraform Cloud for our workspaces. I'm not sure if there is already a feature like this, but it would be nice if Terraform Cloud came with:

- A "business hour" scheduler per workspace. Allows the owner to set a window of time the stack should remain up, and torn down during off hours.
- Have a "scheduler tagset" -- basically allowing the owner to set special tags on resources they want to be excluded from the off hours teardown, or maybe have its own window of hours.

Something similar to this https://aws.amazon.com/solutions/implementations/instance-scheduler/ except for a whole Terraform stack.

**Comment by apparentlymart** [comment]
Hi @secureoptions! Thanks for sharing this use-case.

This repository is for the Terraform CLI tool rather than for Terraform Cloud, and so there isn't really anything we could do in _this_ repository to respond to the use-cases you've shared and so I'm going to close this issue. However, I will also pass the link to the issue to the Terraform Cloud teams so they can consider it; it being closed _here_ doesn't mean something like this can't be included in Terraform Cloud. Thanks!

For questions and feedback about Terraform Cloud it's typically better to contact [Terraform Cloud support](tf-cloud@hashicorp.support), because they are better equipped to route feedback and requests to the relevant teams. Thanks!
