### ISSUE TITLE
S3 policy: MalformedPolicy

### ISSUE THREAD

**Issue by pavankumarda2136** [hashicorp/terraform#28688]
### Terraform Version

```
Terraform v0.13.7
```

### Terraform Configuration Files

```terraform
resource "aws_s3_bucket_policy" "test_s3_policy" {
  bucket = var.bucket_name
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Action" : [
          "s3:GetBucketLocation",
          "s3:ListAllMyBuckets"
        ],
        "Resource" : "arn:aws:s3:::*"
      },
      {
        "Effect" : "Allow",
        "Action" : ["s3:*"],
        "Resource" : ["arn:aws:s3:::test-bucket"]
      },
      {
        "Effect" : "Allow",
        "Action" : [
          "s3:PutObject",
          "s3:GetObject",
          "s3:DeleteObject"
        ],
        "Resource" : ["arn:aws:s3:::test-bucket/*"]
      },
      {
        "Sid" : "VisualEditor3",
        "Effect" : "Deny",
        "Action" : "s3:*",
        "Resource" : [
          "arn:aws:s3:::test-bucket/*",
          "arn:aws:s3:::test-bucket"
        ],
        "Condition" : {
          "NotIpAddress" : {
            "aws:SourceIp" : "xxxxx/32"
          }
        }
      }
    ]
  })
}
```

### Debug Output

Error: Error putting S3 policy: MalformedPolicy: Missing required field Principal
        status code: 400, request id: 6FTV2T57CP3Y7S9X, host id: xxxx=

  on iam_test_s3.tf line 1, in resource "aws_s3_bucket_policy" "test_s3_policy":
   1: resource "aws_s3_bucket_policy" "test_s3_policy" {
### Expected Behavior

It should create the I am policy for my bucket.
### Actual Behavior

erroring out with the below error.
Error: Error putting S3 policy: MalformedPolicy: Missing required field Principal
        status code: 400, request id: 6FTV2T57CP3Y7S9X, host id: xxxx=

  on iam_test_s3.tf line 1, in resource "aws_s3_bucket_policy" "test_s3_policy":
   1: resource "aws_s3_bucket_policy" "test_s3_policy" {
### Steps to Reproduce

1. terraform plan
2. terraform apply

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

This looks to me to be an issue with your policy definition. [See this similar error and the reply](https://stackoverflow.com/questions/51310312/malformed-s3-policy-from-terraform), which indicates that the issue may be that you cannot use `s3:ListAllMyBuckets` as a bucket policy.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
