### ISSUE TITLE
Azurerm AppService(webapp) Windows Python stack on ASP

### ISSUE THREAD

**Issue by boryanat** [hashicorp/terraform#28691]
Hello,

I am trying to create a WebApp using Azurerm Terraform module. My WebApp have to be a Windows Python one. The problem is that once it is applied the stack version is the default one ASP with .NEt4.8. So i need to modify that to python 3.6 manually. I am trying to understand how this can be achieved without any manual configuration but using terraform only.
I have trying using the option "windows_fx_version" with value "python|3.6", similar to "linux_fx_version" without any success.

I am sending my site config:

site_config {
ftps_state = "Disabled"
min_tls_version = "1.2"
python_version = "3.4"
windows_fx_version = "python|3.6"
}

If we are using Linux, and "linux_fx_version" the stack id the proper one, but for Windows and "windows_fx_version" it is not working and does not set the proper stack.

![image](https://user-images.githubusercontent.com/19604048/118098764-f89abe80-b3dc-11eb-98bd-2b07a6cf9403.png)

**Comment by mildwonkey** [comment]
Hi @boryanat, I'm sorry for the delayed response on this issue. This sounds like a question for the azure provider, and not a terraform core issue. 

We use GitHub issues for tracking bugs and enhancements rather than for questions. I suggest you ask in [the azure provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) or [the terraform community forum](https://discuss.hashicorp.com/c/terraform-core).
