### ISSUE TITLE
Override terraform default script path

### ISSUE THREAD

**Issue by Proximator** [hashicorp/terraform#28707]
I am creating multiple VMs in Azure using cloud-init, they are created in parallel and when any of them fails, I can see in the logs:

> Error: error executing "/tmp/terraform_876543210.sh": Process exited with status 1

But I have no way to figure out which VM is failing, I need to ssh each of them and check The script path seems to be defined for provisioning : https://github.com/hashicorp/terraform/blob/4a93399c604b7d406c4f6ec85f130cced47e5d2d/communicator/ssh/provisioner.go

Is there a way to override it also for cloud-init to something like: 

> /tmp/terraform_vmName_876543210.sh

 ?

**Comment by apparentlymart** [comment]
Hi @Proximator! Thanks for sharing this use-case.

When you say "in the logs", do you mean the output from Terraform itself, or some other logs? I ask because I if you mean Terraform's own output then I expect we could address this problem more easily by changing the Terraform output to give more context about what it was doing when the error occurred, which would then hopefully give you the information you need without any need to change your provisioner configuration.

**Comment by Proximator** [comment]
@apparentlymart  Thanks for your quick reply, I mean terraform logs which I see in my octopus deployment tools
I suppose if I run my terraform script, I will also get the same error issue.
How can I configure terraform output? any documentation, please?

**Comment by jbardin** [comment]
Hi @Proximator,

The logs will show the addresses of each instance where provisioning failed, so I assume you are referring to the normal CLI output. The error output is currently missing the context around the source of the error, which can make it difficult to trace back to the source, however you can find which instances failed by using `terraform show` and looking for the `(tainted)` instances.
