### ISSUE TITLE
Feature Request: Azure - use metadata to make destroy more efficient

### ISSUE THREAD

**Issue by jason-swissre** [hashicorp/terraform#28730]
### Current Terraform Version

Any

### Use-cases

terraform destroy

### Attempted Solutions

All resources are individually destroyed

### Proposal

If terraform were to keep track of which components exist within other components it would be possible to only destroy top level components on a destroy action.  For example, destroying a resource group will destroy everything within the resource group without having to destroy them individually.  Likewise, destroying a keyvault destroys all secrets and policies within that keyvault.

### References

When we need to manually destroy our Azure environments currently we manually destroy the environments we destroy components that are outside of resource groups (e.g. Diagnostic settings) and then destroy the top level groups only.

**Comment by jbardin** [comment]
Hi @jason-swissre,

Thanks for filing the issue. Batching requests is a long sought after feature, but will require some significant architectural changes starting with the provider SDK and plugin protocol. Since the initial design needs to begin with providers, we are tracking the feature in the plugin SDK repo here: https://github.com/hashicorp/terraform-plugin-sdk/issues/7

Thanks!
