### ISSUE TITLE
feat: add Default to attribute struct in jsonprovider

### ISSUE THREAD

**Issue by mavogel** [hashicorp/terraform#28735]
I would like to be able to let `terraform-plugin-docs` (which uses `terraform-json`) generate the documentation for a provider and also append the default value of an attribute, if given.

For example given the entry
```go
"rm": {
	Type:        schema.TypeBool,
	Description: "If true, then <omitted for brevity>.",
	Default:     false,
	Optional:    true,
},
```

I'd like to have the rendered output in the `.md` file as follows:
```md
- **rm** (Boolean) If true, then <omitted for brevity>. Defaults to `false`
```

### Current Terraform Version
```
Terraform v0.15.3
on darwin_amd64
```

### Current tool versions
- terraform-plugin-docs: `v0.4.0`
- terraform-plugin-sdk/v2 `v2.6.1`

### Attempted Solutions

For now I can simply add the value to the `Description` as follows:
```go
"rm": {
	Type:        schema.TypeBool,
	Description: "If true, then <omitted for brevity>. Defaults to `false`",
	Default:     false,
	Optional:    true,
},
``` 

### Proposal

Add the attribute `Default` here: https://github.com/hashicorp/terraform/blob/4b25a07bc796c392e95ce9d8b4228e6b3416803b/command/jsonprovider/attribute.go#L10-L20 then the steps described in https://github.com/hashicorp/terraform-json/issues/35#issuecomment-842303022 can be implemented in the other libraries/layers.

### References
- https://github.com/hashicorp/terraform-json/issues/35
- https://github.com/hashicorp/terraform-plugin-docs/issues/65

**Comment by jbardin** [comment]
Hi @mavogel,

Thanks for the feedback here. The default values you see are implemented by a particular provider SDK, not Terraform itself. The `Default` field is not included in the provider plugin protocol, and is not seen by the terraform cli. Many `Default` values are also filled it via functions evaluated during planning, which are not be representable in the schema protocol at all, leaving the same problem with displaying the defaults even if `Default` was added as part of the schema.

Since this is implemented by the [plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk), that would be the starting point for a discussion about extending the schema protocol to expose default values. See also #28657 for a similar request.

Thanks!
