### ISSUE TITLE
Error getting base64 encode btw local and jenkins in same terraform verison

### ISSUE THREAD

**Issue by gerardgorrion** [hashicorp/terraform#28731]
Hi all, we are trying to add jenkins our terraform IaC. We are deploying the cluster with some configurations, including user data with eks conf. The problem was when try to add the same code into jenkins. The base 64 result of local data show different base 64 string, but when try to decode the result of decoded text is the same!

### Terraform Version

14.11

### Terraform Configuration Files

```
locals {
  eks-node-userdata = <<USERDATA
#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh --apiserver-endpoint '${aws_eks_cluster.eks.endpoint}' --b64-cluster-ca '${aws_eks_cluster.eks.certificate_authority.0.data}' '${aws_eks_cluster.eks.name}'
USERDATA
}

```
```
resource "aws_launch_template" "eks-launch-template" {
 ...
  user_data              = base64encode(local.eks-node-userdata)

```

### Expected Behavior
The user_data will shouldn't change, because if will change after create, replacement force that node group recreate his nodes with new configuration.

### Actual Behavior
Jenkis show the user_data changes with other base 64 string and force replacement.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @gerardgorrion,

If the encoded data is changing, it means the input to the `base64` function is different in each case.
Decoding different base64 strings _must_ produce different data, although simply printing it may not show unprintable characters or whitespace. Can you compare the strings exactly to see what the difference is?

Thanks!

**Comment by apparentlymart** [comment]
One way we've seen this happen in the past is if "local" means a Windows system and the configuration is stored in a Git repository, because in some configurations Git on Windows will automatically rewrite a file stored using Unix-style line endings (just line-feed) to instead use Windows-style line endings (a carriage return followed by a line feed). That then means that your "heredoc" string will contain extra carriage return characters that it didn't contain in the original file stored in Git.

For Terraform files containing heredocs it's important that the characters between the `<<USERDATA` opening marker and the closing `USERDATA` marker are identical for everyone running that Terraform configuration, or else the template will produce a different value.

If the situation I've described above sounds like a likely explanation for what you've seen, you may be able to fix it by telling Git to _not_ modify your files automatically on clone and checkin, thus making sure everyone gets the same files regardless of which platform they are running on. You can do that using various settings in [the `.gitattributes` file](https://git-scm.com/docs/gitattributes). One possible approach, for example, is to tell Git that `.tf` files are not text, and thus Git should check them out exactly as they are in the repository:

```
*.tf -text
```

(The `-` in front of `text` above means "not", as in "not text".)

If what I've described here doesn't seem like it applies to your situation then what James wrote above still applies: we'll need to figure out what exactly is different between these two strings in order to understand what happened here.

**Comment by jbardin** [comment]
Hello,

Since we have not heard back in a while I'm going to close the issue. If the above responses do not answer you question, feel free to ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
