### ISSUE TITLE
Terraform 0.15 cli command - terraform init -plugin-dir="custom path here" not working

### ISSUE THREAD

**Issue by chetanrana2702** [hashicorp/terraform#28749]
Hey

I am using the terraform init command with flag -plugin-dir="custom path here" but its not working and every time it downloads the plugins  as command executes.

-> terraform version is 0.15
-> plugin is azurerm

-> terraform init -plugin-dir="custom path here"

**Comment by jbardin** [comment]
Hi @chetanrana2702,

The `-plugin-dir` flag overrides all other discovery mechanisms, so terraform should fail if the given directory is not correctly structured. Can you please provide the information requests in the issue template, including the log output from `TF_LOG=trace`? 

Thanks!

**Comment by jbardin** [comment]
Hello,

We have not heard back in a while, so I'm going to close the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
