### ISSUE TITLE
Terraform 0.12.xx no longer allows assignments on the command line, without a corresponding variable declaration in root module

### ISSUE THREAD

**Issue by paveli-d9** [hashicorp/terraform#28764]
### Terraform Version

```
0.12.xx
```

### Expected Behavior

Terraform v0.11.xx and earlier allowed assignments to occur on the command line (-var) without a corresponding variable declaration in infrastructure.tf.

### Actual Behavior

This now results in errors such as the following:
```
Error: Value for undeclared variable

A variable named "some_var" was assigned on the command line, but the root
module does not declare a variable of that name. To use this value, add a
"variable" block to the configuration.
```

### Steps to Reproduce

Add "-var some_var=some_value" without a corresponding variable declaration in infrastructure.tf
terraform apply

### Additional Context

We have two use cases affected:
1. Our CI script generates a common set of variables passed on command line shared by multiple infrastucture.tf files. Only a subset of the assignments are referenced in a given infrastructure.tf file. 
2. We are using [Terragrunt](https://terragrunt.gruntwork.io/), terraform wrapper, which provides the way to configure different environments infrastructure, while still using the same terraform module. In order to pass the configuration to module, it uses variables assignments on the command line.

Up until v0.11.xx, assignments on command line without a corresponding variable declaration in a given infrastructure.tf were ignored. As discussed in [#19424](https://github.com/hashicorp/terraform/issues/19424) similar behavior for assignments in terraform.tfvars has been changed to warning.

### References

Related issue: [#19424](https://github.com/hashicorp/terraform/issues/19424)
Fix for #19424: [backend: Undeclared variables in -var-file is a warning, not an error #20057](https://github.com/hashicorp/terraform/pull/20057/files)
[The line in the code that originates the error](https://github.com/hashicorp/terraform/blob/0728d1cefb99ebe4db465fe1ea647cb704ca4d4b/backend/unparsed_value.go#L62)

**Comment by jbardin** [comment]
Hi @paveli-d9,

Sorry you are having an issue here, but what you are seeing is the expected behavior of Terraform.
The ability to use undeclared was limited to prevent a number of issues, however using undeclared variables from within tfvars files remains. In #27795 we finalized this by removing the deprecation warning, however the cli will still report warnings for unused values declared in this manner. 

As we are no longer developing version 0.12 of terraform, I'm going to close this out. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
