### ISSUE TITLE
dependency to a datasource causes recreation

### ISSUE THREAD

**Issue by yupwei68** [hashicorp/terraform#28774]
Because the user may want to create the network in an existing resource group, we use a data source resource group in the module. But After TF 0.13, we have to add a dependency in the module to the resource "resource group". Else, it returns error that the "resource group" is not found. (When you create resource and data source together, you'll need a dependency. Before 0.13, it's not necessary).

But the side effect is that when we update the tags of the resource group, the "network" in the module will be recreated.

Related to issue https://github.com/azure/terraform-azurerm-network/issues/58
https://github.com/azure/terraform-azurerm-vnet/issues/43

### Terraform Version

```
0.15.1
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "my-resources"
  location = "West Europe"
}

module "network" {
  source              = "Azure/network/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = "10.0.0.0/16"
  subnet_prefixes     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  subnet_names        = ["subnet1", "subnet2", "subnet3"]

  tags = {
    environment = "dev"
    costcenter  = "it"
  }

  depends_on = [azurerm_resource_group.example]
}
```

### Expected Behavior

The update of the tags of the resource group should not influence the other resources.

### Actual Behavior

The update of the tags of the resource group causes the virtual network to be recreated

### Steps to Reproduce

1. terraform apply
2. update tags of the resource group
3. terraform apply

### References

- https://github.com/azure/terraform-azurerm-network/issues/58
- https://github.com/azure/terraform-azurerm-vnet/issues/43

**Comment by jbardin** [comment]
Hi @yupwei68,

The issue you linked explain the problem correctly, the module needs to be fixed to allow this type of dependency to work correctly without using `depends_on` for the module. By adding `depends_on` you are stating that everything within the module depends on any changes to the `azurerm_resource_group`, which results in changes that cannot be determined during planning as you see,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by DenWin** [comment]
See here for some additional reasoning why this happens:
https://github.com/hashicorp/terraform/issues/28377#issuecomment-820398608
