### ISSUE TITLE
index() function returns item not found - Call to function "index" failed: item not found

### ISSUE THREAD

**Issue by devendrawagh** [hashicorp/terraform#28778]
**Terraform Version**
$ terraform -v
Terraform v0.15.4

**Terraform Configuration Files**

module "policyset_definitions" {
  source = "./modules/policyset-definitions"

  depends_on = [module.policy_definitions]

  policy_def_set_name           = var.policy_def_set_name
  policy_def_type               = var.policy_def_type
  policyset_definition_category = var.policyset_definition_category

  custom_default_nsg_policies = [
    {
      policyID =  module.policy_definitions.policy_defination_ids[index([module.policy_definitions.policy_defination_ids], [for i in [module.policy_definitions.policy_defination_ids]: i])]      
    }
  ]
}

**Debug Output**

│   on main.tf line 32, in module "policyset_definitions":
│   32:       policyID =  module.policy_definitions.policy_defination_ids[index((var.policy_name),[for i in var.policy_name: i])]               #each.key)]
│     ├────────────────
│     │ var.policy_name is list of string with 13 elements
│
│ Call to function "index" failed: item not found.

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
