### ISSUE TITLE
How to properly upgrade Terraform and avoid state error?

### ISSUE THREAD

**Issue by samuelarogbonlo** [hashicorp/terraform#28783]
Hi there,

### Terraform Version
```
Terraform v0.13.0
```

### Expected Behavior

It should have destroyed my resources but it threw an error then I tried to upgrade and It should have shown me the updated to version of ```v0.15.3``` but the reverse is the case

### Actual Behavior
```
Error: Error locking state: Error acquiring the state lock: state snapshot was created by Terraform v0.15.3, which is newer than current v0.13.0; upgrade to Terraform v0.15.3 or greater to work with this state

Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
```
Then when I try to upgrade, it goes through but the version still shows as displayed below:
```
Your version of Terraform is out of date! The latest version is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. git clone this [repository](https://github.com/hashicorp/boundary-reference-architecture)
2. `terraform init`
2. `terraform apply`
3. `terraform destroy`
3. `terraform --version`
4. `sudo apt install terraform=0.15.3`
5. `terraform --version`

The terraform has refused to upgrade so the destroy command could work. But if you think, I could do anything to circumvent this error, please share!

**Comment by jbardin** [comment]
Hello!

From the error output it appears that the issue here is about configuring your system to use the correct Terraform version, since the state you are referencing has already been updated to v0.15.3.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
