### ISSUE TITLE
azurerm_frontdoor_custom_https_configuration and new Front Door endpoints

### ISSUE THREAD

**Issue by la-sanchez** [hashicorp/terraform#28785]
### Terraform Version

```
0.15.3
```

### Terraform Configuration Files

```terraform
resource "azurerm_frontdoor_custom_https_configuration" "frontend_endpoint_https_config" {
  for_each = var.frontend_endpoints
  frontend_endpoint_id = azurerm_frontdoor.fd.frontend_endpoints[each.value.name]
  custom_https_provisioning_enabled = each.key != "default" ? true : false
  dynamic "custom_https_configuration" {
    ...
  }
}
```

### Error raised

Error: Invalid index
│
│   on ../../modules/network/front_door/main.tf line 4, in resource "azurerm_frontdoor_custom_https_configuration" "frontend_endpoint_https_config":
│    4:   frontend_endpoint_id = azurerm_frontdoor.fd.frontend_endpoints[each.value.name]
│     ├────────────────
│     │ azurerm_frontdoor.fd.frontend_endpoints is map of string with 5 elements
│     │ each.value.name is "contoso-com"
│
│ The given key does not identify an element in this collection value.

### Expected Behavior

New Front Door endpoint is create **BEFORE** the azurerm_frontdoor_custom_https_configuration for that new endpoint is created.

### Actual Behavior

Terraform returns an error trying to create a new azurerm_frontdoor_custom_https_configuration because the new endpoint is not created yet.

**Comment by jbardin** [comment]
Hi @la-sanchez,

Thanks for filing the issue, but unfortunately I'm not able to determine what is going on from the configuration given. Can you supply a more complete configuration, showing how `var.frontend_endpoints` and `azurerm_frontdoor.fd.frontend_endpoints` are derived? 

If this is a question about how to structure your configuration, we can sometimes help with certain simple problems here, but it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by jbardin** [comment]
Thanks @la-sanchez. 

You are referring to 2 different fields in the `azurerm_frontdoor` resource, `azurerm_frontdoor.fd.frontend_endpoints` is a computed value returned by the provider after the resource has been applied, and `frontend_endpoint` is the block you are providing in the configuration. The problem here is that the provider is not indicating that the `frontend_endpoints` map will change based on changes to the `frontend_endpoint` block during the plan, hence terraform is attempting to index the existing values of the `frontend_endpoints` map. This is an issue with the provider, and should be filed in the AzureRM provider project repo.

Thanks!
