### ISSUE TITLE
Error: Upload failed: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by samuelarogbonlo** [hashicorp/terraform#28791]
Hi there, I am trying to provision a TF infrastructure on aws and following some processes

### Terraform Version

`Terraform v0.13.0`

### Expected Behavior

It should work without errors and provide the infrastructure.

### Actual Behavior
`Error: Upload failed: wait: remote command exited without exit status or exit signal`

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1.  git clone `https://github.com/hashicorp/boundary-reference-architecture/tree/main/deployment/aws` then `cd deplyment/aws`
2. `terraform init`
2. `terraform apply`

I'd want some help in avoiding this error

Thanks!

**Comment by jbardin** [comment]
Hi @samuelarogbonlo,

The error you see here is not from Terraform itself, though I'm not certain how it's being triggered in this particular case.
I'm not able to replicate this issue -- could you test this out using a current version of Terraform, so that we can rule out any involvement in the Terraform CLI itself?

Thanks!

**Comment by samuelarogbonlo** [comment]
I upgraded and issue cleared! Thanks
