### ISSUE TITLE
Terraform is using a very old version of consul

### ISSUE THREAD

**Issue by nimrodkor** [hashicorp/terraform#28790]
### Current Terraform Version
0.15.4

### Use-cases
I'm trying to import terraform as part of a new open source tool, which also utilizes github.com/hashicorp/consul/api.
However, it seems terraform is still using a **very** old version of this package:
```
github.com/hashicorp/consul v0.0.0-20171026175957-610f3c86a089
```

### Attempted Solutions
Tried using replace etc, but the module path is not the same as the packaging has changed.

### Proposal
Update the packaging of consul in terraform

**Comment by alisdair** [comment]
> I'm trying to import terraform as part of a new open source tool

We do not support importing `terraform` as a Go module. Depending on your use case, you may find integration tools such as [terraform-exec](https://github.com/hashicorp/terraform-exec) or [terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect) a better fit.

**Comment by apparentlymart** [comment]
Terraform imports Consul's API package only to implement [the `consul` backend](https://www.terraform.io/docs/language/settings/backends/consul.html), and so it'd only be updated if the Consul team (which maintains that backend) wanted to update the backend to use a newer Consul feature that the existing version doesn't yet support.

As @alisdair suggested, Terraform is a command line tool rather than a Go library and so the dependencies listed in `go.mod` are focused on what Terraform CLI needs. We've actually recently moved all of the Terraform CLI Go packages under `internal` to represent that in a way that the Go toolchain understands, and so from the next release onwards you will find that your program is no longer able to implement any packages from this repository at all.

Since any upgrades of this dependency would be driven by proposals by the Consul team rather than by the Terraform team, I'm going to close this issue. If you have questions about how to make use of the alternative libraries @alisdair suggested, or other ways to achieve your goals, please start a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
