### ISSUE TITLE
Support Bring your own kubelet MI

### ISSUE THREAD

**Issue by pmuz** [hashicorp/terraform#28793]
### Proposal
Terraform should support assigning kubelet MI at cluster creation as per microsoft docs:

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#bring-your-own-control-plane-mi

**Comment by apparentlymart** [comment]
Hi @pmuz,

After looking at the documentation you linked to here it seems like this is a feature request for the `hashicorp/azurem` provider rather than for Terraform itself. Terraform providers are plugins maintained by separate teams and released independently of Terraform CLI. If you'd like to request new capabilities in the provider, please open a feature request in [the provider repository](https://github.com/terraform-providers/terraform-provider-azurerm), and when you do so be sure to complete the feature request issue template that the provider team has configured for their repository so that they can understand what you are requesting.

Since I don't think there's anything we could change in _this_ repository to achieve the feature you are asking for, I'm going to close this issue. Thanks!
