### ISSUE TITLE
Deploying Application Gateway with Terraform code

### ISSUE THREAD

**Issue by syedyakoobali** [hashicorp/terraform#28809]
Greetings

I am deploying multiple resources in azure devops pipeline using the Terraform code. Everytime the pipeline is run the application gateway returns the following error. The code for the application gateway is hereby attached. Please waiting for recommendation.

Error: Error Creating/Updating Application Gateway "dbc-pi-appgateway-01" (Resource Group "rg-dbc-pi-shared-001"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /subscriptions/780f9206-52e1-4f07-afa5-8783e9e851c3/resourceGroups/rg-dbc-pi-shared-001/providers/Microsoft.Network/applicationGateways/dbc-pi-appgateway-01/trustedRootCertificates/test-cer-file referenced by resource /subscriptions/780f9206-52e1-4f07-afa5-8783e9e851c3/resourceGroups/rg-dbc-pi-shared-001/providers/Microsoft.Network/applicationGateways/dbc-pi-appgateway-01/backendHttpSettingsCollection/test was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." Details=[]

[applicationgateway.txt](https://github.com/hashicorp/terraform/files/6545761/applicationgateway.txt)

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
