### ISSUE TITLE
Backend settings for Application Gateway

### ISSUE THREAD

**Issue by syedyakoobali** [hashicorp/terraform#28801]
Greetings

I have multiple resources to be deployed with the help of Terraform. Everytime I deploy resources the Application Gateway backend settings, http settings gets destroyed and re-created. Due to this the APIM also gets modified and all its settings are lost. Please need recommendations for this issue.
Using the latest version of Terraform.

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
