### ISSUE TITLE
TypeSet with both Optional and Computed as true doesn't show any change on removal of the attribute from tf file

### ISSUE THREAD

**Issue by ujjwal-ibm** [hashicorp/terraform#28811]
### Terraform Version 15

```
### My provider has this key in schema :

"ids": {
				Type:        schema.TypeSet,
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Set:         schema.HashString,
				Description: "List of ids",
			},
```

### Terraform Configuration Files

```terraform
resource abc xyz {
   ids = ["123-456-789"]
}
```

### Debug Output

On creation it works fine, but if I remove the "ids" from terraform configuration file after creation, it shows "No changes. Infrastructure is up-to-date."

### Expected Behavior

Since my configuration changed, it should show me difference

```
 ~ update in-place

Terraform will perform the following actions:
  ~ resource abc xyz {
      ~ ids                 = [
          - "123-456-789",
        ]
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your configuration and the remote system(s). As a result, there are no actions to take.
```
### Steps to Reproduce
terraform plan

**Comment by jbardin** [comment]
Hi @ujjwal-ibm,

Thanks for filing the issue. This is a known shortcoming of the legacy provider SDK, as HCL blocks cannot be assigned an empty value, so there is no way to differentiate unset from empty.  The workaround in that case is to use `schema.SchemaConfigModeAttr` and configure the block as if it were an attribute of the same type. 

Issues regarding the SDK are tracked in the project repo here: https://github.com/hashicorp/terraform-plugin-sdk

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, if you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

Thanks!
