### ISSUE TITLE
Terraform destroy specific to resource is not working in terraform Terraform v0.15.3 

### ISSUE THREAD

**Issue by sanswarn** [hashicorp/terraform#28816]
<!--
Hi there,

I am working on OCI terraform where I am successfully deploy instances and harden it using remote-exec provisionor  and build image of this instances
Requirement is, I do want destroy instances immediately post image is created, I went through multiple sites and they were suggest to use "terraform destroy -target RESOURCE_TYPE.NAME  or terraform destroy -target=RESOURCE_TYPE.NAME" 
but not of the options is working and it destroy all resource in tf file. 
I do not want to remove the instances code manually from tf file and execute it again.

even I could not file any associate attribute with terraform destroy" 

DO we have any posssible way to automate it so post image build instances destroyed ?

Terraform]$ terraform state list 
data.oci_core_images.images
data.oci_identity_availability_domains.ads
null_resource.remote-exec
oci_core_image.test_image
oci_core_instance.test_vm_tf

terraform destroy -target oci_core_instance.test_vm_tf--------------that destroy everything

**Comment by sanswarn** [comment]
it experience that the core instance is mapped is calling all other instances to destroy ..how to destroy an resource instances that is mapped to other resource ?

**Comment by jbardin** [comment]
Hi @sanswarn,


We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since no information was provided here, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
