### ISSUE TITLE
`terraform state mv` destroys / creates resources

### ISSUE THREAD

**Issue by matteocodogno** [hashicorp/terraform#28810]
### Terraform Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.63.0
```

### Terraform Configuration Files

```terraform
resource "google_compute_instance" "tfer--myvm" {
  boot_disk {
    auto_delete = "false"
    device_name = "persistent-disk-0"
    mode        = "READ_WRITE"
    source      = ""
  }

  can_ip_forward      = "false"
  deletion_protection = "false"
  enable_display      = "false"
  machine_type        = "n1-standard-2"

  metadata = {
    enable-oslogin = "TRUE"
  }

  name = "myvm"

  network_interface {
    access_config {
      nat_ip       = "..."
      network_tier = "PREMIUM"
    }

    network            = "..."
    network_ip         = "..."
    subnetwork         = "..."
    subnetwork_project = ".."
  }

  project = "..."

  scheduling {
    automatic_restart   = "true"
    min_node_cpus       = "0"
    on_host_maintenance = "MIGRATE"
    preemptible         = "false"
  }

  service_account {
    email  = "..."
    scopes = [...]
  }

  tags = ["https-server", "allow-health-checks", "natted-servers", "http-server"]
  zone = "europe-west6-a"
}
```

### Debug Output

[Debug log](https://gist.github.com/matteocodogno/768bf26e1ea92953d35e368824c224fc)

### Expected Behavior

As in your [example](https://www.terraform.io/docs/cli/commands/state/mv.html#example-rename-a-resource) our intention is to retain the existing object but track it under a new name.

### Actual Behavior

It tries to remove a resource with the new name and create a resource with the old name (that already exists).

### Steps to Reproduce

1. `terraform init`
2. `terraform state mv google_compute_instance.tfer--myvm google_compute_instance.myvm`
3. `terraform plan`

**Comment by jbardin** [comment]
Hi @matteocodogno,

The behavior you are describing is indicating that you have not changed the configuration to match the new state, and the configuration for the old resource name still exists. In order to keep the new `google_compute_instance.myvm` instance, you will need to add that to the configuration.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by matteocodogno** [comment]
It was a misunderstanding on my side, it works as expected if I update the configuration.

Thanks
