### ISSUE TITLE
Share provider configuration between an official provider and local fork of that provider assigned a new source address

### ISSUE THREAD

**Issue by bogi0704** [hashicorp/terraform#28823]
### Current Terraform Version
```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.2.0
+ provider <URL>/<Path>/vcd v3.1.28
```

### Use-cases
I want to use the same provider configuration configured in my root module for the vmware/vcd provider to be useable by the child module. But since the child module must use a fork of the vmware/vcd provider, which has some enhancements we needed, this is not possible.

### Attempted Solutions
main.tf child module:
```` hcl terraform
terraform {
   required_version =">= 0.14"
   required_providers {
      vcd = {
         source = "<URL>/<Path>/vcd"
         version = ">=3.1.17"
      }
   }
}
````

root module:
```` hcl terraform
terraform {
   required_version =">= 0.14"
   required_providers {
      vcd = {
         source = "vmware/vcd"
         version = ">=3.2.0"
      }
   }
}

provider "vcd" {
  auth_type            = "token"
  org                  = "System"
  url                  = "<URL>/api"
}


module "child_module" {
  source = "***//modules/child_module"
  #depends_on = [module.different_module]
  providers = {
    vcd = vcd
  }
}
````

Result:

````
terraform init:

╷
│ Error: Invalid type for provider module.child_module.provider["<URL>/<Path>/vcd"]
│
│   on child.tf line 10, in module "child_module":
│   10:     vcd = vcd
│
│ Cannot use configuration from provider["registry.terraform.io/vmware/vcd"] for module.child_module.provider["<URL>/<Path>/vcd"]. The
│ given provider configuration is for a different provider type.
╵

````

### Proposal
I was thinking of some kind of flag which does enable the use of the same provider configuration for different providers. Since our provider is a fork of the official one, they are technically different, but inherently they are the same and therefore compatible.

### References
- #28407

**Comment by jbardin** [comment]
Hi @bogi0704,

Thanks for filing the issue. While we often describe what is being passed around here as a "provider configuration", that configuration is not just the attributes for the provider, but the entire provider configuration including the specific provider instance to be used. This is because while a child module _should_ provide constraints on what provider it can accept, the root module is the one that determines exactly what providers are going to be used. What this means is that if we allowed what you are proposing, it would result it the module resources using the `"vmware/vcd"` provider instead of your fork, which is definitely not what you intend.

You do have an interesting use case here though, so we can keep this open for future development ideas, but because it would take a significant refactoring of the terraform internals to make this work it's not likely to be something seen in the short term.

THanks!

**Comment by bogi0704** [comment]
Hi @jbardin 

Thank you for you explanation. 

The provider configuration holds the URL of the API endpoint I am connecting to. Since we have two environments I have to change this URL inside the provider configuration depending on the evironment used.
As a workaround I have put the provider configuration statically inside the module. This also means that I will have to create two versions of the same module with different URLs.

This is definitely an edge case, but who knows maybe I will be lucky :)

**Comment by apparentlymart** [comment]
Hi @bogi0704,

With Terraform as currently implemented, I would suggest doing something like the following in your root module:

```hcl
terraform {
   required_version =">= 0.14"
   required_providers {
      vcd = {
         source = "vmware/vcd"
         version = ">=3.2.0"
      }
      customvcd = {
        source = "<URL>/<Path>/vcd"
      }
   }
}

locals {
  vcd_config = {
    auth_type = "token"
    org       = "System"
    url       = "<URL>/api"
  }
}

provider "vcd" {
  auth_type = local.vcd_config.auth_type
  org       = local.vcd_config.org
  url       = local.vcd_config.url
}

provider "customvcd" {
  auth_type = local.vcd_config.auth_type
  org       = local.vcd_config.org
  url       = local.vcd_config.url
}

module "child_module" {
  source = "***//modules/child_module"
}
```

The above will configure both of these providers using the same settings derived from the local value object. It achieves that by declaring that the root module _also_ depends on `<URL>/<Path>/vcd`, but assigns it the different module-specific local name `customvcd` so that it doesn't collide with the local name you already assigned to the `vmware/vcd` provider.

Another possible option, if your custom provider is largely the same as the upstream but just has a few temporary tweaks that will hopefully eventually be available in an upstream release, would be to still name your custom provider `registry.terraform.io/vmware/vcd` but to assign it a different version number with a custom build metadata string, like `3.2.0+bogi0704.1`. This will then cause Terraform to see it as just another build of `vmware/vcd` which both of your modules can use with a single configuration. However, I would suggest this only if your custom fork has only light, temporary modifications that you intend to send upstream; if you have changed the behavior in a way that's specific to your team then your approach of assigning it a new name is indeed the best option, though it does come at the expense of having to configure both of these providers separately because Terraform considers them to be completely distinct from one another.

**Comment by bogi0704** [comment]
Hi @apparentlymart ,

Thank you for you suggestion. This has worked like a charm and fits my need exactly. Thank you very much for this!!
