### ISSUE TITLE
Make it easier to find Data documentation

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform#28825]
### Use-cases
Original URL of [Terraform documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network) was changed from `/r/` to `/resources/` and form `/d/` to `/data-sources/`.
This makes it very inconvenient to switch to `data`, which was previously possible simply by changing `/r/` to `/d/`.

### Attempted Solutions
- Scrolling back and forth through the resource menu
- Searching, which often yields too many results
- Manually changing the URL to `/data-sources/`

### Proposal
Add a simple button onto each `resource` page that allows to switch to a relevant `data` source if available.
Or add some redirects so that changing from `/resources/` to `/d/` redirects to `/data-sources/`
Or optimize so that [Google for `data`](https://lmgtfy.app/?q=terraform+data+azurerm_virtual_network) returns `/data-sources/` article instead of `/resource/`

**Comment by fbreckle** [comment]
I, too, am regularly annoyed by the fact that there is no "jump to matching data source/resource" button in the terraform docs.
The level of annoyance is right there at "dang, why is this not a thing", but not quite at the "I'm gonna make an issue about it" or, god forbid, "I'ill fix this myself" level.

But I would very much like the feature!

**Comment by apparentlymart** [comment]
Hi @Tbohunek! Thanks for sharing this feedback.

It seems like this is Terraform Registry feedback, based on the URL you linked to. The Terraform Registry team doesn't typically monitor issues here, and asked for us to suggest sending feedback to the email address terraform-registry@hashicorp.com so that they can discuss it with you and include it in their own (non-public) issue tracker.

I do agree that this is a valid feature request and a feature that would be very helpful, so I'm not closing this to say that it's not valid but only because there's nothing we could change in _this particular repository_ to improve the situation you described, because this repository is for Terraform CLI rather than the Terraform Registry.

Thanks again!

**Comment by Tbohunek** [comment]
Thanks @apparentlymart, I've sent the email.

I'm just a bit surprised though you wouldn't be able to forward this internally. It is a different team but you're the same company.
I will update this thread when (if) I get further response.

>HashiCorp Ticket #49258
Thanks for submitting a request with the Terraform Registry team. Please note that due to high volume, there may be a delay in responding to this request. We are unable to guarantee a response to all requests, with the exception of those from HashiCorp Technology Partners reporting critical issues that are impacting users.
To add additional comments, you may reply to this email.
Thank you!
