### ISSUE TITLE
Maintenance Error Message

### ISSUE THREAD

**Issue by jpillora** [hashicorp/terraform#28822]
I just ran our CI process and got this error

```
Initializing the backend...
Error: Discovery URL returned an unsupported Content-Type "text/html"
  on main.tf line 4, in terraform:
   4:     hostname     = "app.terraform.io"
```

Took me a while to figure it out that Terraform Cloud is currently under maintenance 

It would be nice if it could detect the backend was in maintenance mode and return a more helpful error message. I understand its 1AM in SF though it's still business hours in other parts of the world!

**Comment by apparentlymart** [comment]
Hi @jpillora! Thanks for sending this in.

The Terraform Cloud teams don't typically monitor issues in this repository, so I'd suggest instead sending this feedback through the Terraform Cloud support channels. They will then pass the feedback on to the Cloud teams for consideration.

I'm going to close this issue not because it isn't valid feedback but just because there's nothing we can change in this repository in particular to improve this situation: Terraform CLI correctly reported that the remote server sent an invalid response, and so to avoid this error would require the Terraform Cloud service to send a different sort of response.

Thanks again!

**Comment by jpillora** [comment]
Interesting, I guess I thought the cli could scan the HTML and figure out
why the backend is down and present a different error

**Comment by brandonc** [comment]
@jpillora we resolved the issue with a change to terraform cloud that will return a 503 when you init terraform while maintenance mode is enabled. Thanks for reporting this!

**Comment by apparentlymart** [comment]
Thanks for sharing the update, @brandonc!

With that change in place, the service discovery logic in Terraform will now bail out a little earlier and return a slightly different message which'll look something like this:

```
Error: Failed to request discovery document: 503 Service Unavailable

  on main.tf line 4, in terraform:
   4:     hostname     = "app.terraform.io"
```
