### ISSUE TITLE
Optional attribute incorrectly considered required by terraform (when under list of lists)

### ISSUE THREAD

**Issue by rudo-thomas** [hashicorp/terraform#28833]
When a terraform resource has a field that is a List(List(Resource{inner_field})), terraform incorrectly fails validation with an error saying the inner_field is required (when in fact it is marked Optional in the schema).

### Terraform Version
```
Terraform v0.15.4
on linux_amd64
```

also reproducible on `Terraform v0.14.6`

### Steps to Reproduce
Run `go test` in this repository: https://github.com/rudo-thomas/terraform-required-attribute-bug (a snapshot at 7cc5f08 is [attached](https://github.com/hashicorp/terraform/files/6560228/terraform-required-attribute-bug.tar.gz)).

### Expected Behavior
Both tests should pass.

### Actual Behavior
```
go test
--- FAIL: TestBug (0.29s)
    bug_test.go:48: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: Incorrect attribute value type
        
          on terraform_plugin_test.tf line 6, in resource "test_test" "r1":
           6: 	l = [
           7: 		[
           8: 			{
           9: 				// Attribute "s" is optional here, but if not present,
          10: 				// terraform 0.15.4 (and older) fails and says it is required.
          11: 				// s = "foo"
          12: 			},
          13: 		],
          14: 	]
        
        Inappropriate value for attribute "l": element 0: element 0: attribute "s" is
        required.
```

### Additional Context

I also tried building an actual provider and running it via terraform CLI, with the same results.

Removing one layer of lists under the `l` attribute requires changing the test config to use block syntax rather than `[ ... ]`. In that case, the behaviour is no longer buggy.

**Comment by jbardin** [comment]
Hi @rudo-thomas,

The [`.../terraform-plugin-sdk/v2/helper/schema`](https://github.com/hashicorp/terraform-plugin-sdk) package does not support defining complex nested attributes, and blocks must be used to get the behavior you are looking for. 

The problem here isn't that the attribute is required, it's just that object values must be defined with all their attributes included in order to satisfy the type signature. In this case, setting `s = null` is semantically equivalent to unset, but allows the type to be passed correctly.

The next generation SDK is expected to support complex nested attribute in this manner. You can track issue with the SDK in their project repo here: https://github.com/hashicorp/terraform-plugin-sdk

Thanks!
