### ISSUE TITLE
Monitor services in azure

### ISSUE THREAD

**Issue by ashishsme14** [hashicorp/terraform#28831]
Our task is -

- Write a terraform script in azmonitor.tf to create a storage account, storage container, storage blob to monitor and send log reports everyday.
- Define the variables resourcegroup and location in the variables.tf file, and call those variables in the azmonitor.tf file using string interpolation syntax

With help of vi command we created variables.tf file as

```
variable "resourcegroup"
{
default = "user-ktywkgjskfgc"
}
variable "location"
{ 
default = ["East US"]
}
```

In normal way we can create storage account as -

`az storage account create --resource-group $user-ofbujdqwzbib --name $storageccountName --location $location
`
how to call those variables in the azmonitor.tf and above command in tf file we are not sure. Please suggest us expertise advice.

**Comment by circa10a** [comment]
Refer to the azure provider docs:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs

**Comment by circa10a** [comment]
This is not the appropriate forum to ask for someone to write code for you

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
