### ISSUE TITLE
local_file provider fails on a file without read permission

### ISSUE THREAD

**Issue by yaitskov** [hashicorp/terraform#28837]
```
resource "local_file" "hello" {
  content = "Hello world"
  filename = "${path.module}/hello.txt"
  file_permission = "0200"
}
```

```
terraform apply
```
On attempt to repeat previous terraform fails with:
```
local_file.hello: Refreshing state... [id=3cc31f444eaa77e0537924c3f0ec6f27fea41522]
╷
│ Error: open ./hello.txt: permission denied
│ 
│   with local_file.hello,
│   on main.tf line 4, in resource "local_file" "hello":
│    4: resource "local_file" "hello" {
│ 
╵

```

**Comment by alisdair** [comment]
Terraform needs to be able to read the local file resource during the refresh phase of the plan or apply. As a result, read permissions are required for subsequent runs. This behaviour seems correct to me.

**Comment by jbardin** [comment]
Hi @yaitskov,

Yes, it appears that the provider allows you to write a file which it cannot read back, because the underlying operating system allows this same series of actions. If you think validating this would be useful, please file an enhancement request with the provider itself, which you can do in the project repository here: https://github.com/hashicorp/terraform-provider-local/issues

Thanks!
