### ISSUE TITLE
Terraform Upgrade not updating State File

### ISSUE THREAD

**Issue by ryanps1** [hashicorp/terraform#28859]
Hi,

I have around 300 deployments utilising Terraform, which have steadily been running at 0.12.28 for some time. All of these deployments utilise an azure storage account encompassed within the "backend" block to store their state file remotely.

I have been working through a mass upgrade recently, and upgraded from 0.12.28 to 0.13.6 with no issue. However, at this stage I started to update all these deployments to utilise 0.14.6. At this point, I noticed that the state files were not being updated to the new version of Terraform for the vast majority of releases and would still work with 0.13.6. I thought that this may have been a quirk/bug, as I had seen a post in the forums of someone upgrading from 0.13.6 to 0.14.6 facing the exact same issue with no resolution found - so to proceed with the upgrade, I updated a tag on a resource in each deployment which did force the state file's version of Terraform to be updated.

I'm now looking to move to 0.15.3, and I'm facing the exact same issue. It occasionally updates the state file, but for the vast majority it does not update the state file unless there is a change included in the apply.  Has anyone experienced this/found a resolution?

**Comment by jbardin** [comment]
Hi @ryanps1,

Terraform will n to write a new state if there are no changes to write, so this looks like the expected result when there have been no changes to the structure of the state or resources.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
