### ISSUE TITLE
Add boolean functions to string functions category

### ISSUE THREAD

**Issue by ferozed** [hashicorp/terraform#28855]
### Current Terraform Version

```
$ terraform version
Terraform v0.13.5
```

### Use-cases

We create terraform providers for our infrastructure. In order to make these providers easy to use, we abstract most of the details with modules.

The module ( say `m1` ) has the following variables

```
variable "R1_name" {
   type = string
}

variable "subject_name" {
   default = ""
}
```

Assume that the module is creating 3 resources - R1, R2, R3

If the `subject_name` variable is blank, I need to take assume it will be "${R1_name}-value". Otherwise it should be whatever the user specified in the `subject_name` variable.

In addition if the `subject_name` is `${R1_name}-value` I need to set another `strategy` variable in my `locals` to a specific value.

### Attempted Solutions

Yes, the string functions dont have boolean return value functions such as `contains`, `endsWith`, `beginsWith`

### Proposal

This is my ideal solution...

```
locals {
   subject_name = var.subject_name != null ? var.subject_name : "${R1_Name}-value"
   strategy = local.subject_name.endsWith("-value") ? "topicnamestrategy": "recordnamestrategy"
}
```

**Comment by apparentlymart** [comment]
Hi @ferozed! Thanks for sharing this use-case.

The Terraform language is not an object-oriented language, so it doesn't support values having their own "methods" in the way you showed in your proposal. However, we could consider a normal function named `endswith`, as I think was also previously proposed in #28209.

That issue has some comments which also cover what I was going to propose within the current language features: the `regex` and `regexall` functions are general enough to subsume all of these use-cases, but that does come at the expense of additional complexity compared to the simple single-purpose functions:

```hcl
locals {
  strategy = can(regex("-value$", local.subject_name)) ? "topicnamestrategy": "recordnamestrategy"
}
```

Since we already have #28209 open representing the possibility of the more-specific functions, I'm going to close this one just to consolidate the discussion. We're being pretty cautious about adding new functions that overlap with existing use-cases because Terraform has grown quite an unwieldy collection of builtins over the years, and so we've been considering various ways to allow for externally-defined functions (e.g. #2771) to avoid continuing to grow that set. However, that's not something we'll be working on in the very near future, due to our current focus being elsewhere, so we'll revisit this at a later time and post any updates in those other issues. For now, I hope the `regex`-based answer I showed above will get the result you wanted.
