### ISSUE TITLE
azurerm provider Provide Option to Import Existing resource In Terraform Apply

### ISSUE THREAD

**Issue by gbmarimuthu** [hashicorp/terraform#28871]
Hi,

To Update the existing resource using Terraform we are seeing error to import the resource. e.g., In Storage Account I am trying to add firewall rules. Referring the storage account using date "azurerm_storage_account" "storage" {}

In case of updating the NSG rules we are able to update the NSG rules by referring the NSG  Resource in data element and added "azurerm_nsg_rules" to add the inbound and outbound rule.

With regards,
Marimuthu G B

### Current Terraform Version

```
...
```

**Comment by jbardin** [comment]
Hi @gbmarimuthu,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

If this is about somehow automatically importing resources which are not in the state, that is not possible currently, but a new workflow for import is being designed for future releases. If this is an issue with the AzureRM provider, you can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. 

Thanks!
