### ISSUE TITLE
 Blocks of type "ace_rx" are not expected here.

### ISSUE THREAD

**Issue by MilaMF** [hashicorp/terraform#28882]
Hi 

I have the follwing configuration;

**variables:**
------------------------
variable "archive_ACL_rwx" {
   type        = list(string)
   default     = ["12345","0987t655]
}

variable "archive_ACL_r-x" {
   type        = list(string)
   default     = ["fde4rws"]
}

module call
------------------------
module "storage_filesystem" {
  source              = "./storage_filesystem"
  name                = "archive"
  storage_datalake_id = azurerm_storage_account.datalake.id
  ace_rwx_id          = var.archive_ACL_rwx
  ace_rx_id           = var.archive_ACL_r-x
}

resource:
----------------------------
resource "azurerm_storage_data_lake_gen2_filesystem" "new_fs"{
 name = var.name 
 storage_account_id = var.storage_datalake_id
  dynamic "ace_rwx"      {
    for_each = var.ace_rwx_id
      content { 
        type = "user"
        scope = "access"
        id = ace_rwx.value
        permissions = "rwx"
      }
  } 
  
  dynamic "ace_rx"      { 
   for_each = var.ace_rx_id
      content {
       type = "user"
        scope = "access"
        id = ace_rx.value
        permissions = "r_x"
      }
  }
}

During "terraform plan" the follwong error occurs.

Error: Unsupported block type
│
│   on storage_filesystem\main.tf line 36, in resource "azurerm_storage_data_lake_gen2_filesystem" "new_fs":
│   36:   dynamic "ace_rwx"      {
│
│ Blocks of type "ace_rwx" are not expected here.
╵
╷
│ Error: Unsupported block type
│
│   on storage_filesystem\main.tf line 46, in resource "azurerm_storage_data_lake_gen2_filesystem" "new_fs":
│   46:   dynamic "ace_rx"      {
│
│ Blocks of type "ace_rx" are not expected here.

What is wrong?

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
