### ISSUE TITLE
lifecycle block not working for oicd_client_secret in resource vault_jwt_auth_backend

### ISSUE THREAD

**Issue by mikemikemotorbike** [hashicorp/terraform#28890]
### Terraform Version
v0.14.7

```
...
```

### Terraform Configuration Files

```terraform
resource "vault_jwt_auth_backend" "oidc" {
    description  = "JWT auth backend for namespace ${var.namespace_name}"
    path = "${var.namespace_name}_auth"
    type = "oidc"
    default_role = var.jwt_default_role
    oidc_discovery_url = var.oidc_discovery_url
    oidc_client_id = var.oidc_client_id
    oidc_client_secret = "123"

    lifecycle {
      ignore_changes = [
        oidc_client_secret
      ]
    }
    
    
    tune {
        listing_visibility = "unauth"
        default_lease_ttl  = var.default_lease_ttl
        max_lease_ttl      = var.max_lease_ttl
        audit_non_hmac_response_keys = ["error"]
        audit_non_hmac_request_keys  = ["role"] 
    }
}

...
```

### Debug Output
```terraform
$ terraform apply
vault_policy.admin: Refreshing state... [id=admin]
vault_jwt_auth_backend.oidc: Refreshing state... [id=salesforce_auth]
vault_jwt_auth_backend_role.jwt_role: Refreshing state... [id=auth/salesforce_auth/role/admin]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vault_jwt_auth_backend.oidc will be updated in-place
  ~ resource "vault_jwt_auth_backend" "oidc" {
        id                     = "salesforce_auth"
      - oidc_client_secret     = (sensitive value)
      ~ tune                   = [
          + {
              + allowed_response_headers     = []
              + audit_non_hmac_request_keys  = [
                  + "role",
                ]
              + audit_non_hmac_response_keys = [
                  + "error",
                ]
              + default_lease_ttl            = "4h"
              + listing_visibility           = "unauth"
              + max_lease_ttl                = "8h"
              + passthrough_request_headers  = []
              + token_type                   = ""
            },
          - {
              - allowed_response_headers     = []
              - audit_non_hmac_request_keys  = [
                  - "role",
                ]
              - audit_non_hmac_response_keys = [
                  - "error",
                ]
              - default_lease_ttl            = "4h"
              - listing_visibility           = "unauth"
              - max_lease_ttl                = "8h"
              - passthrough_request_headers  = []
              - token_type                   = "default-service"
            },
        ]
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Crash Output
N/A

### Expected Behavior
Changes to `oidc_client_secret` in vault should be ignored by terraform 

### Actual Behavior
Vault rebuilds `vault_jwt_auth_backend`

### Steps to Reproduce
1. `terraform apply`
2. change `oidc_client_secret` via vault UI, CLI or API 
3. `terraform apply`

### Additional Context
We have an external service to rotate `oidc_client_secret` therefore we do not want terraform to overwrite the value. 

### References
No other github issue found

**Comment by jbardin** [comment]
Hi @mikemikemotorbike,

I have a feeling that the `oidc_client_secret` is not the underlying cause if the change seen here, since the `tune` value also appears to be changing, but I'm not able to replicate the exact output shown here to confirm what is really happening. 

Can you confirm that you still see this issue with a current version of Terraform and the Vault provider?

If you can still replicate the issue with current versions, I think the next clue to look for be warning lines in the logs regarding the values returned by the provider. If the problem is specifically the `tune` block, and ignoring `tune` as well gives you the expected result, then the problem is with the provider itself and you can file an issue in their project repository.

Thanks!

**Comment by mikemikemotorbike** [comment]
Thank you for the response.  Will attempt to reproduce with Terraform 0.15.5

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
