### ISSUE TITLE
releases.hashicorp.com / registry provider download outage

### ISSUE THREAD

**Issue by muthu329024** [hashicorp/terraform#28895]
https://releases.hashicorp.com/terraform/

Error 503 Service Unavailable
Service Unavailable

Guru Mediation:
Details: cache-syd10130-SYD 1623146631 1703223397

Varnish cache server

**Comment by Yilong94** [comment]
Facing a similar issue here

**Comment by naveenkumarsp** [comment]
> https://releases.hashicorp.com/terraform/
> 
> Error 503 Service Unavailable
> Service Unavailable
> 
> Guru Mediation:
> Details: cache-syd10130-SYD 1623146631 1703223397
> 
> Varnish cache server

I too face the same issue.  Infact the pipelines are failing due to this

2021-06-08T10:17:30.6668392Z ##[section]Starting: Install Terraform 0.15.5
2021-06-08T10:17:30.6771250Z ==============================================================================
2021-06-08T10:17:30.6771541Z Task         : Terraform tool installer
2021-06-08T10:17:30.6771831Z Description  : Find in cache or download a specific version of Terraform and prepend it to the PATH
2021-06-08T10:17:30.6772104Z Version      : 0.0.19
2021-06-08T10:17:30.6772293Z Author       : Microsoft Corporation
2021-06-08T10:17:30.6772563Z Help         : [Learn more about this task](https://aka.ms/AA5jd97)
2021-06-08T10:17:30.6772992Z ==============================================================================
2021-06-08T10:17:31.0118928Z Downloading: https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_windows_amd64.zip
2021-06-08T10:17:31.1668785Z ##[error]Error: Failed to download Terraform from url https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_windows_amd64.zip. Error Error: Unexpected HTTP response: 503
2021-06-08T10:17:31.1725407Z ##[section]Finishing: Install Terraform 0.15.5

**Comment by tyrken** [comment]
Cannot even `init` in a folder with everything turned off to try to use local cache

```
$ terraform-0.14.11 init -get=false -get-plugins=false -upgrade=false -verify-plugins=false

Initializing the backend...

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/local versions matching "2.1.0"...
- Finding hashicorp/aws versions matching "3.37.0"...
- Finding hashicorp/external versions matching "1.1.2"...
- Finding newrelic/newrelic versions matching "2.21.1"...
- Finding hashicorp/null versions matching "3.1.0"...
- Finding hashicorp/random versions matching "3.1.0"...
- Finding cloudflare/cloudflare versions matching "2.14.0"...
- Finding opsgenie/opsgenie versions matching "0.6.2"...
- Finding latest version of hashicorp/archive...

Warning: No-op -get-plugins flag used

As of Terraform 0.13+, the -get-plugins=false command is a no-op flag. If you
would like to customize provider installation, use a provider_installation
block or other available Terraform settings.


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/local: could not connect to registry.terraform.io: Failed to request
discovery document: 502 Gateway Error


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
could not connect to registry.terraform.io: Failed to request discovery
document: 503 Service Unavailable


Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/external: could not connect to registry.terraform.io: Failed to
request discovery document: 503 Service Unavailable

... repeated
```

**Comment by Yilong94** [comment]
Might be related to the global outage of many big websites it seems
https://www.cnbc.com/2021/06/08/reddit-and-global-news-sites-go-offline.html?__source=androidappshare

**Comment by lukegriffith** [comment]
All my Terraform pipelines have been hit by this --- Are we using the system wrong by depending on the Terraform registry? What should have been done to mitigate this problem?

**Comment by aristosvo** [comment]
You can check the status here: https://status.hashicorp.com

**Comment by retraut** [comment]
https://status.fastly.com/incidents/vpk0ssybt3bj and this

**Comment by aristosvo** [comment]
Seems resolved, 1.0.0 is working fine for me 🎉

**Comment by jbardin** [comment]
The Fastly issue has been resolved, and we have not had any reports of continuing issues, so closing this out.

**Comment by tyrken** [comment]
Hang on @jbardin - earlier Terraform used to be able to run air-gapped off a local folder, with the local cache being able to act as that folder.  I had expected some combination of flags to `init` would allow me to continue to work in new folders when the global registry was down, as I wasn't changing provider versions since working in other previously `init`'ed folders.  This did not seem possible.

Just because Fastly is working again now, doesn't mean you haven't a flaw from always-phone-home behaviour of `init`.

**Comment by jbardin** [comment]
@tyrken, The Terraform CLI only requires the registry if it cannot satisfy its requirements in some other way. Terraform can use a [local filesystem mirror](https://www.terraform.io/docs/cli/config/config-file.html#filesystem_mirror), which has some default [implied local mirror directories](https://www.terraform.io/docs/cli/config/config-file.html#implied-local-mirror-directories), and also provides a [`terraform mirror` command](https://www.terraform.io/docs/cli/commands/providers/mirror.html) for fetching the desired providers.

**Comment by tyrken** [comment]
Thanks for the links - I already had `plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"` in my ~/.terraformrc, and that folder/subfolders looked populated with all the terraform providers that my `init` insisted on checking with your servers for.  So AFAIK the local implicit mirror should have kicked in, but it appears not to fully work.

Earlier today I was working without a .terraform or .terraform.lock.hcl when I saw the issue reported above, but I can repeat this with both fully populated by needlessly running `terraform init` after temporarily disconnecting my laptop from the network.

FWIW our providers are all explicitly version-locked (as we can't check-in to git the .terraform.lock.hcl files yet owing to #28041), i.e.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 3.37.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "= 2.14.0"
    }
    external = {
      source  = "hashicorp/external"
      version = "= 1.1.2"
    }
...
  required_version = ">= 0.13"
}
```

**Comment by jbardin** [comment]
@tyrken, In order to always force the use of a mirror, you must also declare the [`provider_installation` config](https://www.terraform.io/docs/cli/config/config-file.html#explicit-installation-method-configuration). The `init` command's `-plugin-dir`  for overriding all discovery mechanisms. 

This particular GitHub issue is specifically about the registry outage. If you have an example of something which is not working as documented though, please file a new issue.

Thanks!
