### ISSUE TITLE
New provider suggestion

### ISSUE THREAD

**Issue by rumenavramov** [hashicorp/terraform#28901]
### Current Terraform Version
```
N/A or latest
```

### Use-cases
F5 have a managed WAF service called Silverline. It is based on BigIP and may be part of a family of products.
Silverline itself is a very feature rich service and it does have an API which means it can be automated.

### Attempted Solutions
Not applicable

### Proposal
Please consider creating an F5 Silvelrline provider. This will allow organizations to deploy and configure Silverline proxies and other entities with Terraform. Currently one has to work with the service portal (meaning manual configuration) or write their own automation, which is time consuming and not widely used because of that.

### References
N/A

**Comment by jbardin** [comment]
Hi @rumenavramov,

Terraform provider are not developed by the Terraform project itself, and the majority of 3rd party providers are not developed by Hashicorp at all. Since F5 already maintain an existing provider, I would suggest filing a request with that provider team about support gin new products. 

Thanks!
