### ISSUE TITLE
Proposal: Multi Modules? (Can't come up with a better name ;-))

### ISSUE THREAD

**Issue by lukaszkorecki** [hashicorp/terraform#2891]
I really like the idea of modules as means of organising code.

I was confused though because I expected something like this to work

```

module "machine" {
  source = "./machine"

  name = "app-01"
}


module "machine" {
  source = "./machine"

  name = "app-02"
}

```

(`machine` module simply wraps ec2 instance and route 53 resources, you can think of it as an equivalent of Puppet's class)

As it turns out I can only use one... Fair enough.

However - having a mechanism like that would allow for a nice abstraction of resources, improve re-use and mitigate the problem of not having loops/iterators built into the language.

Apologies if something similar was filled before, but I couldn't find it.

**Comment by BRMatt** [comment]
My (extremely basic and probably wrong) understanding is that you have to give each instance of a resource a unique identifier, and in this case it looks like you're using `"machine"` for both? It [doesn't look like you can use the `name` field on modules](https://www.terraform.io/docs/configuration/modules.html)(?), what happens if you change it to this?

```
module "app-01" {
  source = "./machine"
}


module "app-02" {
  source = "./machine"
}
```

**Comment by lukaszkorecki** [comment]
Huh, I didn't think of that - I'll give it a go (as I might have misread the docs too :-))

**Comment by lukaszkorecki** [comment]
Duh - it works as expected. 
Closing :bow:
