### ISSUE TITLE
Conditional ignore_changes in the Lifecycle block

### ISSUE THREAD

**Issue by nitmatgeo** [hashicorp/terraform#28913]
```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Scenario
I create a VM with random password and the random password gets stored to Keyvault using [azurerm_key_vault_secret](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret). Now, for some reason, admin changes the password and updated in the keyvault-secret; during any future deployment, now the kva terraform script detects a drift between the value in Azure Portal versus Terraform State versus Terraform Code. 
>Note: The scenario is applicable in general and not just to Azure or Key Vault.

### Attempted Solutions
Using [ignore_changes](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html). To my understanding this is not applicable in modules and only works in resource block. Therefore, if I use this at resource block then all modules referring to this gets locked and I cannot update any accidental error in the script for a specific resource.

### Proposal
If my understanding is right, then as a work around- is it possible to toggle the ignore_changes in the lifecycle block? For example,
```
variable "force_ignore" {
  default = false
  type = bool
}
resource "azurerm_key_vault_secret" "key_vault_secret" {
  name            = var.git_name
  value           = var.git_value
  key_vault_id    = var.git_key_vault_id
  content_type    = var.git_content_type
  not_before_date = var.git_not_before_date
  expiration_date = var.git_expiration_date
  tags            = var.git_tags

  lifecycle {
    ignore_changes = [ for arguments in [value, not_before_date, expiration_date,] if var.force_ignore]
  }
}
```

>NOTE: The example cited here is very important in near future in cases when key/secret rotation features are implemented via terraform then the secrets will get updated frequently outside the terraform script/state. Therefore, such alternative is important for smooth implementation.

**Comment by nitmatgeo** [comment]
If this is not possible, then is there any workaround or solution to my problem?

**Comment by jbardin** [comment]
Hi @nitmatgeo,

Thanks for the feature request, we are currently tracking this in #24188.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by nitmatgeo** [comment]
@jbardin apologies for my question; please be kind enough to confirm if my request for this enhancement is rejected? Or your team is already working on a similar feature?

Please refer to

> ### Proposal
> If my understanding is right, then as a work around- is it possible to toggle the ignore_changes in the lifecycle block? For example,
> 
> ```
> variable "force_ignore" {
>   default = false
>   type = bool
> }
> resource "azurerm_key_vault_secret" "key_vault_secret" {
>   name            = var.git_name
>   value           = var.git_value
>   key_vault_id    = var.git_key_vault_id
>   content_type    = var.git_content_type
>   not_before_date = var.git_not_before_date
>   expiration_date = var.git_expiration_date
>   tags            = var.git_tags
> 
>   lifecycle {
>     ignore_changes = [ for arguments in [value, not_before_date, expiration_date,] if var.force_ignore]
>   }
> }
> ```
> 
> > NOTE: The example cited here is very important in near future in cases when key/secret rotation features are implemented via terraform then the secrets will get updated frequently outside the terraform script/state. Therefore, such alternative is important for smooth implementation.

**Comment by jbardin** [comment]
@nitmatgeo, I closed this issue in preference of a more general request for evaluation of arbitrary expressions in the `lifecycle` block. This is currently not possible in the language, because things like `ignore_changes` are lists of relative references rather than values that can evaluated in expressions. 

Supporting a `lifecycle` block for modules is not related to this. Modules themselves do not have a single lifecycle to modify, because they can contain any type of configuration object, not all of which have lifecycles which can be aligned. Adding something like `lifecycle` to modules would take a fair amount of initial research to determine first how it could be implemented, and then all the posible interractions between the objects contained within. Adding `depends_on` to modules was a much smaller, bit similar addition, and it has already proved troublesome with users unable to understand the implications of the additional dependencies.

**Comment by nitmatgeo** [comment]
@jbardin Thanks James, I get your point.
