### ISSUE TITLE
name_regex in aws_ami data source does not filter properly

### ISSUE THREAD

**Issue by johong** [hashicorp/terraform#28926]
### Terraform Version v0.13.7

I'm currently trying to filter our own AMIs by using the `name_regex` field in the aws_ami data source to get something like this:
```
data "aws_ami" "ami" {
  most_recent = true
  name_regex  = "v\\d+\\.\\d+\\.\\d+"

  owners = ["self"]
}
```

We have 2 semantic versioning schemes:
`v1.0.0` is something a release would look like.
`v1.0.0-develop` is something a non-release would look like.

### Expected Behavior
With the constraints of the given regex expression, only the release version `v1.0.0` should be returned as a possible result.

### Actual Behavior
Anything starting `v1.0.0` is returned, so both `v1.0.0` and `v1.0.0-develop` are returned and considered valid.

### Additional Context
The regex expression filter should be more rigid. We can already filter in similar ways using the native filter block, and the regex should provide a tighter layer of filtering on top of it.
Currently, it seems to only care that the AMI name begins with the characters that match the regex. We are currently working around this issue by changing our non-release naming to `develop-v1.0.0`

**Comment by jbardin** [comment]
Hi @johong,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. 

From the example you've given however, it looks like you just want to anchor your regex, to either end of the string, maybe something like: `"^v\\d+\\.\\d+\\.\\d+$$"`. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.


Thanks!
