### ISSUE TITLE
Add support for days, weeks, months and years in timeadd

### ISSUE THREAD

**Issue by czmirek** [hashicorp/terraform#28930]
### Proposal
Add support for days, weeks, months and years in the [`timeadd`](https://www.terraform.io/docs/language/functions/timeadd.html) function.

Currently, the longest unit supported is hour.

### Examples
```hcl
timeadd("2021-06-11T08:04:39Z", "1d")
"2021-06-12T08:04:39Z"

timeadd("2021-06-11T08:04:39Z", "1w")
"2021-06-18T08:04:39Z"

timeadd("2021-06-11T08:04:39Z", "1m")
"2021-07-11T08:04:39Z"

timeadd("2021-06-11T08:04:39Z", "1y")
"2022-06-11T08:04:39Z"
```
### Current workaround
Of course you can calculate number of hours yourself but it's definitely much nicer to write "1y" rather than "8760h"

**Comment by apparentlymart** [comment]
Hi @czmirek! Thanks for sharing this feature request.

The `timeadd` function is currently limited to time increments that are absolute constants, and doesn't include anything that would require reference to a calendar.

That's why there isn't currently support for concepts like days, months, and years: doing that sort of calendar-based arithmetic correctly requires access to calendar information and a constantly-updated data source about which dates include leap seconds. We don't include that sort of thing in Terraform's scope because Terraform is intended primarily for communicating with machines rather than with humans, and calendars are more of a human concept.

With that said, there is a provider [`hashicorp/time`](https://registry.terraform.io/providers/hashicorp/time/latest/docs) which does include some functionality for working with calendar-oriented time increments. That provider is maintained by a separate team so I'm not sure how exactly it defines "day", "month", and "year": it could either be a hard-coded multiple of hours as you noted or it could be by reference to a calendar. It being a separate provider makes it more amenable to updates over time if its rules need to change, and so we tend to prefer to keep that sort of functionality out in plugins rather than in Terraform Core.

Given that, I don't expect we'll extend `timeadd` to include calendar-related time increments, because there will always be differences of opinion about what is "correct" behavior for different situations and so better to delegate that sort of thing to providers where multiple approaches can potentially be supported at once. The capabilities of providers might grow in future to include the ability to provide configuration language functions, although that's still only a hypothetical because there are several design challenges around that. In the meantime, a data source or managed resource type can potentially provide an effect similar to a function, albeit with a more verbose syntax and the capability to violate the rules we typically expect for functions, such as storing data between runs as the `hashicorp/time` provider does.

Thanks again!
