### ISSUE TITLE
Execution Permissions

### ISSUE THREAD

**Issue by 1mamute** [hashicorp/terraform#28934]
### Current Terraform Version
```
v1.0.0
```

### Use-cases
A typical use-case for this is an organizations that only wants the changes to be **applied** or **destroyed** from a pipeline but still wants the developer to be able to run **plan** commands locally against remote state files to facilitate development.

### Attempted Solutions
Locking the state file? I don't think there's any solution for this right now.

### Proposal
Rules that dictates who have permissions to execute a set of commands.  
These rules could be written in HCL.  
Every rule should generate a token. The token could be written to stdout (output block) and saved in Vault, for example.  
An easy way to keep track of these tokens is storing them encrypted in the state files.
These token could be passed through an environment variable or cli argument.  
When running an command, Terraform should evaluate the token in the remote state file, if the token specified has permissions to execute the command, allow it.  
These could be extended to indiviual users, if necessary.  
Ability to choose a default permission and all commands executed without a token should be evaluated against the default permission set.

```
permission "ci_cd" {
  description = "Permissions for CICD to be able to execute terraform commands"
  encrypted = true
  # Default is true for all permissions
  #apply = true (default)
  #plan = true (default)
  #destroy = true (default)
}

permission "devs" {
  description = "Permissions for developers to be able to execute terraform commands"
  default = true
  encrypted = false
  # Default is true for all permissions
  apply = false
  destroy = false
}

output "devs_token" {
  value = permission.devs.token
}

Changes to Outputs:
  + devs_token = aiyuh4o1#1i123++
 
 $ terraform apply
 $ Oops. You don't have a permission token set up and 
 $ the default permission for this remote state doesn't allow terraform apply.
 
 $ export PERMISSION_TOKEN=aiyuh4o1#1i123++
 $ terraform apply -token=$PERMISSION_TOKEN
 $ Oops. You dont have permission to do terraform apply.
```

### References
- #28423
- #13221

**Comment by apparentlymart** [comment]
Hi @1mamute! Thanks for sharing this use-case.

One significant problem with addressing this use-case within Terraform CLI itself is that Terraform CLI is a program entirely under the control of the person/computer running it, and so it isn't really in any permission to enforce any permissions. For example, a user who wanted to bypass the rules could simply change the configuration to have more permissive permissions, or modify Terraform itself to not actually enforce the permissions, or to use their credentials for other systems already issued to take the same actions that Terraform would have when applying the plan via the underlying API instead.

Within the realm of HashiCorp software we tend to consider this sort of use-case to be within the scope of [Terraform Cloud](https://www.terraform.io/cloud) rather than Terraform CLI, because then in principle you can configure the access on a workspace to control which authenticated users can start a remote operation, and also arrange so that the necessary credentials to take the actions that `terraform apply` would run are available only in the remote execution context, and not locally.

I should add that even within Terraform Cloud this isn't an airtight security mechanism: anyone who can run a Terraform Plan with a configuration under their control can potentially submit a configuration which captures data from the execution environment and sends it somewhere else. A Terraform configuration is arbitrary code, and so ultimately these solutions are at best a "guardrail" to help avoid unintended dangerous actions, unless you prevent certain users from creating Terraform runs _at all_ and give them access only to read the results of those runs.

It would also be possible in principle for software other than Terraform Cloud to wrap Terraform CLI in a similar way that Terraform Cloud does, and thus enforce permissions in a different way. I can't recommend any particular existing solution because I only have direct experience with Terraform Cloud, but I mention it only to recognize that architecturally this sort of permissions enforcement is outside of Terraform CLI's intended scope and instead we delegate it to other software which wraps Terraform, typically running Terraform only in a remote execution environment where it can therefore have some measure of control over which Terraform executable is running and what permissions that executable has within its execution context.

I don't expect that we'll expand Terraform CLI's scope to include use-cases like what you've described here, because its position in the architecture (as a CLI program rather than a remote service) means it cannot feasibly enforce any such restrictions, and a purely-advisory mechanism can be implemented just fine in a wrapper around Terraform, as Terraform Cloud illustrates.

For that reason, I'm going to close this. I do appreciate you sharing the use-case, but since it's outside of Terraform CLI's intended scope we don't plan to introduce any new features to meet the use-case within Terraform CLI itself. I suggest that you consider outside solutions to use along with Terraform CLI in order to meet your requirement. Thanks!
