### ISSUE TITLE
'data' needs to allow a 'try' so empty is returned

### ISSUE THREAD

**Issue by dragosnicolaesava** [hashicorp/terraform#28933]
I know about feature https://github.com/hashicorp/terraform/issues/16380 
I encounter this while working on azurerm provider but the problem is generic.

My issue: 
I want to generate a random username/password if a keyvault secret doesn't exist, else the default one should remain.

I can clearly use from provider 'random' a 'random_string' (or the others) to get myself a random value. This is able to generate what I want.
The issue is when I try to apply that value to the keyvault_secret I don't know how to do it.
I clearly want to keep the previous value if one exist.

So the logic I want to have is:
if 'secret' exist leave it as it is, else if this is new get this random value.

The only way to do this is if I am able to read the previous secret, but I cannot do that if it doesn't exist (data.azurerm_key_vault_secret till thow)

An idea of the code (I used data.azurerm_resources.azurerm_key_vault.resources to see if the keyvault exist but if I could have gotten the secret i would have looked if that was null/empty).

length(data.azurerm_resources.azurerm_key_vault.resources) == 0 ? random_string.username.result : data.azurerm_key_vault_secret.key_vault_secret_username.value

This is failing if the keyvault/secret doesn't exist: data.azurerm_key_vault_secret.key_vault_secret_username.value

With modules/outputs I run into the same issue. 
If I have them separated I will get new value each time i run this. And keeping them separated is not our intention, I think the keyvault should live in the same resource group as the resources that are using them.  

A way to force a default (and ignore the failure that the resource does't yet exist seems a good solution)

**Comment by apparentlymart** [comment]
Hi @dragosnicolaesava,

Terraform's design is that you write down what should exist and then Terraform will take actions to try to make the remote system match your description. Therefore there intentionally isn't any way to make statements like "use this if it already exists, otherwise create it" because that would make the configuration an incomplete description of the intended result: it would be unclear whether after applying the plan the object is now managed by this Terraform configuration or not. If you run `terraform destroy` then Terraform might either destroy the object or not, depending on the history.

Instead, you should decide which part of your system is responsible for managing each object and then write a `resource` block _only_ in the configuration for the single component that is responsible for managing that object. In other configurations, you can write a `data` block to retrieve the created object. Terraform will then correctly fail if you try to apply the configurations in the wrong order, because it will detect that the object that the `data` block refers to does not exist. If you apply them in correct dependency order then all of the operations will succeed, because the `data` block will find the existing object and use it.

The documentation section [Module Composition](https://www.terraform.io/docs/language/modules/develop/composition.html) describes some broader patterns for dealing with situations like this, particularly in the section "Conditional Creation of Objects". I recommend reading the full guide for all of the context, but the summary is to design your modules so that they accept via input variables the data they need, and then use your root module to decide for a particular configuration whether that input variable will be populated from a `resource` block or a `data` block. The module shouldn't care about whether the object is managed in the current configuration or in some other configuration.

The solution you're trying to employ here is intentionally not supported by Terraform as part of making it explicit which configuration owns each object, and so I'm going to close this. If you'd like to discuss potential alternative solutions for your specific use-case then I suggest to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core), which is better suited for discussing specific solutions rather than general features. Thanks!
