### ISSUE TITLE
Terraform as docker does not work through ZScaler by default

### ISSUE THREAD

**Issue by semangard** [hashicorp/terraform#28936]
Hello,

I am using Terraform docker official images : https://hub.docker.com/r/hashicorp/terraform/
but my company is also using ZScaler 
so I face the following issue:

![image](https://user-images.githubusercontent.com/57065741/121714955-a71a4800-cade-11eb-8830-2ce887d25047.png)

![image](https://user-images.githubusercontent.com/57065741/121715744-88688100-cadf-11eb-96ec-226944c01286.png)

The reason is that Zcaler's certificate is refused, here is the certificate:

![image](https://user-images.githubusercontent.com/57065741/121692726-aa0a3e00-cac8-11eb-9a27-1ea5f1f23987.png)

=> Would it be possible to get an option like the one for wget _--no-check-certificate_ in order to bypass this issue ?

Of course I can create a custom docker image but I will have to do it each time a new release of Terraform is publishedm which is absolutely not convenient.

Regards

**Comment by apparentlymart** [comment]
Hi @semangard,

Most Terraform components should respect the OpenSSL environment variable `SSL_CERT_DIR` in order to override the search directories for certificates, if you are using Terraform v0.14.0 or later on a Linux system. You can use that to provide Terraform with a custom certificate store that includes a certificate that would allow this middlebox to intercept your requests.

Doing that inside the Docker container will be a little more complicated since you'll need to somehow make the custom certificate available inside the Docker container filesystem, and then ask Docker to set the environment variable to a suitable path when launching the Terraform process. That should be possible with some custom options when running the official Docker image, but I can't give a detailed example here because I'm not a Docker expert; I'd suggest asking about this in Docker help forums if you are unsure.

We don't intend to offer any option to disable certificate checking entirely, because that would be very unsafe for software like Terraform which is installing arbitrary executable code from remote systems. Instead, you should configure your system (or, in Docker, the virtualized system inside the Docker container) to trust the certificate your middlebox uses, and thus Terraform can trust that particular system but would still protect against hypothetical attacks involving other certificates.

Since Terraform already trusts the certificates trusted by your system, I'm going to close this. If you have any follow-up questions then please open an issue in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), although if it's a docker-related question then it may be better to ask in a Docker-specific forum since I can't promise that folks in the community forum will be able to answer Docker questions. Thanks!
