### ISSUE TITLE
Add encryption-at-rest support to the Swift backend

### ISSUE THREAD

**Issue by colans** [hashicorp/terraform#28957]
As per [Sensitive Data in State](https://www.terraform.io/docs/language/state/sensitive-data.html), *some backends can be configured to encrypt the state data at rest*.  However, it doesn't appear that the Swift backend supports this.  Let's add it.

**Comment by ramondeklein** [comment]
I have implemented it for the Azure provider and it's quite trivial: https://github.com/hashicorp/terraform/pull/29289. I just checked the Swift code and it could be added there as well. If it's picked up in more providers, then it would be better to move the crypto code to a higher level.

**Comment by colans** [comment]
I'm fully in favour of closing this if we can make #29272 happen.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Swift backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
