### ISSUE TITLE
Take ownership of google_compute_network_endpoint_group created with GKE kubernetes_service

### ISSUE THREAD

**Issue by pobrien415** [hashicorp/terraform#28966]
Has anyone run into this? If I ask terraform to create a kubernetes_service and include the annotation for example: 
     "cloud.google.com/neg" = "{\"exposed_ports\": {\"80\":{\"name\": \"test_neg\"}}}" then GKE will create the NEG "test_neg" for me and also keep it synced with the pods in the workload. I haven;t found a way to make my own NEG that can do that "on the fly" syncing with the workload. Any GKE experts run into this? 

I was thinking to let GKE create it and then take ownership somehow with terraform but no terrafrom function for that yet. 

I would like the NEGs to be deleted when I do a terraform destroy on the kubernetes_service

**Comment by jbardin** [comment]
Hi @pobrien415, We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) (and specificlly the [Kubernetes category](https://discuss.hashicorp.com/c/terraform-providers/kubernetes/40))where there are more people ready to help.
