### ISSUE TITLE
Unable to update openstack instance after image has been deleted

### ISSUE THREAD

**Issue by screencomuser** [hashicorp/terraform#28965]
### Current Terraform Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.39.0
```

### Use-cases

When a Glance image has been deleted, it is impossible to update the instance that was created with this image as terraform can not find the image and wants to replace the resource.

This blocks all other changes to any resources

### Attempted Solutions

None

### Proposal

Be able to modify the image uuid in-flight with the new uuid so it appears to terraform that the instance was created with the new image, therefore it doesn't need to update the resource.

Alternatively, the openstack service provider would have to update its instances so it references the new uuid, but that would entail some work on their end, which, in all fairness, can not really be the way forward.

### References

#2189 is similar but different in that I used the image name and not the uuid. Also that issue is pretty old, so I'm guessing not many people experience this ;-)

Any help / pointers would be greatly appreciated.

**Comment by apparentlymart** [comment]
Hi @screencomuser! Thanks for sharing this.

From reviewing #2189 I see that it's a very old issue from back when all of the Terraform providers belonged to this repository along with Terraform Core. However, since Terraform v0.10 that hasn't been true and so the OpenStack provider no longer lives in this repository.

I think you are proposing to change something in Terraform Core to address this, because you're asserting that it isn't possible for the OpenStack provider to address it directly itself. Typically specific oddities of certain APIs are the provider's responsibility to address, but I would be interested to hear more about your rationale for why this would be for Terraform Core to address; unfortunately I'm not familiar with OpenStack at all, so I don't follow the situation you are describing and would appreciate if you could describe it in more general terms using Terraform's own concepts, rather than OpenStack's concepts.

Thanks!

**Comment by screencomuser** [comment]
Hi,

I hadn't realized the openstack provider lives in a separate repo. Apologies!

It turns out that the solution was staring me in the face all along.

The instance had been created with an image name, which is saved as a uuid.

Replacing the image_name with the image_id and using the deleted uuid made terraform realise that the resource wasn't changed and it stopped proposing to replace it.

So, for posterity and the odd chance of someone else with the same problem landing here, I changed

```
image_name: "Ubuntu 20.04 (LTS)"
```

with the Image uuid as shown in the openstack dashboard

```
image_id: "40120160-ee10-40d5-91fa-4e792e5bf8e1"
```

(I'm using yml as source configuration as it's easier on the eye)

Thanking you and feeling a lot happier now it's solved :-)

Cheers!
