### ISSUE TITLE
Terraform validate --var-file in 0.15

### ISSUE THREAD

**Issue by dhinakar2707** [hashicorp/terraform#28997]
Hi Team,

I was trying to create tf state in GCP with version 0.15.4 but terraform validate command is throwing below error.
erraform has been successfully initialized!
$ terraform validate -var-file=environment/${CI_ENVIRONMENT_NAME}/variables.tfvars
╷
│ Error: Failed to parse command-line flags
│
│ flag provided but not defined: -var-file
╵
For more help on using this command, run:
terraform validate -help

Cleaning up file based variables
Please can someone help me, if something i'm missing or is there any change in 0.15.4 version, But the same code is working fine with terraform version 0.14.4.

**Comment by jbardin** [comment]
Hello,

The `-var-file` flag was deprecated in 0.12, and should have produced the warning `The -var and -var-file flags are not used in validate. Setting them has no effect."`. These flags have since been removed from the `validate` command.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by dhinakar2707** [comment]
@jbardin 

Sorry for the inconvenience and thanks for the update. I will use the comminity forum for all my quries going forward.
