### ISSUE TITLE
Allow the list of objects for for_each argument

### ISSUE THREAD

**Issue by yuklia** [hashicorp/terraform#29010]
### Current Terraform Version
Terraform v0.14.7

### Proposal
I would like to use the list of objects data structures for **for_each construction.**

example:
the object definition:
```
variable "services_settings" {
  description = "The list of service/conatiner's name for which ECR repository will be created in this module."
  type = list(object({
    service_name = string,
    props = object({
      scan_on_push = bool
    })
  }))
  default = [
    {
      service_name = "test1",
      props = {scan_on_push: true}
    },
    {
      service_name = "test2",
      props = {scan_on_push: false}
    }
  ]
}
```

the use case:
```
resource "aws_ecr_repository" "repositories" {
  for_each = var.services_settings
  name     = "${var.project}-${each.value["service_name"]}"

  image_scanning_configuration {
    scan_on_push = tobool(each.value["props"]["scan_on_push"])
  }
}
```
But my terraform doesn't support it yet.
```
Error: Invalid for_each argument

  on main.tf line 58, in resource "aws_ecr_repository" "repositories":
  58:   for_each = var.services_settings

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type list
of object
```

---
The object data structure is more elegant than a map in case where I want to show a particular object structure in the code. It tremendously increases the code readability. 
For now, the only way to do foreaching is to map and comment which will describe the desired map structure but it is a bad way of coding.

**Comment by apparentlymart** [comment]
Hi @yuklia! Thanks for sharing this use-case.

Considering your resource example:

```hcl
resource "aws_ecr_repository" "repositories" {
  for_each = var.services_settings
  name     = "${var.project}-${each.value["service_name"]}"

  image_scanning_configuration {
    scan_on_push = tobool(each.value["props"]["scan_on_push"])
  }
}
```

What would you expect Terraform to select for the individual instance addresses created by this `for_each`?

When using a mapping, Terraform uses the map key as the instance key. For example:

```hcl
resource "aws_ecr_repository" "repositories" {
  for_each = { for s in var.services_settings : s.service_name => s }

  name     = "${var.project}-${each.value.service_name}"

  image_scanning_configuration {
    scan_on_push = tobool(each.value.props["scan_on_push"])
  }
}
```

With the input data you showed, Terraform would understand this block as declaring the following two resource instances, because the `for` expression projected into a map where the service name is the key:

* `aws_ecr_repository.repositories["test1"]`
* `aws_ecr_repository.repositories["test2"]`

If we were to accept a list then Terraform wouldn't have any way to know that `service_name` is the key to use, and so we'd need to decide some other way to select a unique key for each of the instances.

Thanks!

**Comment by crw** [comment]
Hi @yuklia, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
