### ISSUE TITLE
yamldecode function doesn’t parse octal numbers correctly

### ISSUE THREAD

**Issue by yann-soubeyrand** [hashicorp/terraform#29012]
### Terraform Version

```
Terraform v1.0.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
output "test" {
  value = yamldecode(<<EOT
string: "toto"
decimal: 500
octal: 0600
EOT
  )
}
```

### Output

```
Changes to Outputs:
  + test = {
      + decimal = 500
      + octal   = 600
      + string  = "toto"
    }

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

test = {
  "decimal" = 500
  "octal" = 600
  "string" = "toto"
}
```

### Expected Behavior

octal field should be parsed as an octal number (0600 in octal or 384 in decimal).

### Actual Behavior

octal field is parsed as a decimal number with a leading 0.

### Steps to Reproduce

Copy the Terraform configuration above in this bug report in a file named test.tf, run `terraform init` and `terraform apply`.

**Comment by mildwonkey** [comment]
Hi @yann-soubeyrand !

According to the [`yamldecode`](https://www.terraform.io/docs/language/functions/yamldecode.html) documentation, terraform supports yaml 1.2. In yaml 1.2, octals are represented with a leaded `0o`, instead of 1.1's `0`.  (Some supporting links: https://symfony.com/doc/current/components/yaml/yaml_format.html#numbers, https://yaml.readthedocs.io/en/latest/pyyaml.html).

This change to your example code shows the expected behavior:

```hcl
output "test" {
  value = yamldecode(<<EOT
string: "toto"
decimal: 500
octal: 0o600
EOT
  )
}
```

And the output:
```bash
test = {
  "decimal" = 500
  "octal" = 384
  "string" = "toto"
}
```

There's no bug here, so I am going to close this issue. THanks!

**Comment by yann-soubeyrand** [comment]
Thanks for the solution @mildwonkey 👍
