### ISSUE TITLE
Go mod vendor failure due to invalid tencentcloud-sdk

### ISSUE THREAD

**Issue by ChrisPenner** [hashicorp/terraform#29021]
Hey folks, looks like one of the downstream dependencies has unfortunately broken their go.mod file
When running `go mod vendor` in this project I get

```
terraform> go mod vendor
go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82
```

AFAICT it's from this commit over in tencentcloud: https://github.com/TencentCloud/tencentcloud-sdk-go/commit/6debd5a0482595f736d4ffe82721b09611c04453#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

I've filed an issue with them here: https://github.com/TencentCloud/tencentcloud-sdk-go/issues/125

Not sure if there's anything you folks can do in the meantime, ~but all of our projects which depend on terraform are a bit stuck at the moment as a result.~

I was able to work around this in the meantime by adding a replace rule to our go.mod:

```
replace github.com/tencentcloud/tencentcloud-sdk-go v3.0.82+incompatible => github.com/tencentcloud/tencentcloud-sdk-go v1.0.191
```

Cheers!

**Comment by jbardin** [comment]
Hi @ChrisPenner,

Thanks for filing the issue. The terraform project itself can build correctly (`go mod vendor` only really copies the required parts of the module cache into the `vendor` directory, and changes nothing about the build), so the pinned dependency is building correctly as far as I can tell. We cannot change the requirements for the `cos` remote state backend, and any replacements internally would have no effect outside of the main terraform package.

Since the terraform module itself is not designed to be imported, and there are no longer any exported packages which can be used (aside from `version`, which don't not require any of the remote state code), it means changing the dependency itself would also have no effect externally in the main branch. 

Using the `replace` directive locally would be the suggested workaround for your build.

Thanks!
