### ISSUE TITLE
TF_CLI_ARGS_init clarification

### ISSUE THREAD

**Issue by desesseintes** [hashicorp/terraform#29020]
I'm going to ask about the answer  _Originally posted by @apparentlymart in https://github.com/hashicorp/terraform/issues/20428#issuecomment-470674564_

We are using terraform cloud and we got the following terraform code:

  backend "remote" {
      hostname     = "app.terraform.io"
      organization = "myorganization"
 
      workspaces {
        name = "myorganization-test-global"
     }
   }

We need to pass the workspace name as a variable.
Is TF_CLI_ARGS_init variable a way to solve our problem?
I have some trouble finding the correct way to correctly assign the value I need to TF_CLI_ARGS_init.

**Comment by apparentlymart** [comment]
Hi @desesseintes,

I believe the `remote` backend in particular requires a different approach because `name` is inside a nested block and so isn't settable on the command line. However, I'm not entirely sure about that. I'd suggest asking this question in [the Terraform Cloud community forum](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44) because that forum is monitored by folks who work on Terraform Cloud rather than just the folks who work on Terraform CLI, and so they'll likely be better able to answer this question.

One thing I will note is that the `-backend-config=` option can also accept a filename containing various settings all at once, using the same syntax as the _content_ of the `backend "remote"` block, and so one thing you could try (although I'm not sure it'll work in this case) is to write a file containing a `workspaces` block with `name` inside and pass that file to `-backend-config`. People in the forum might have some other ideas for you, though.

Thanks!
