### ISSUE TITLE
Terraform won't load variables from `terraform.tfvars.json` file

### ISSUE THREAD

**Issue by istvanfedak** [hashicorp/terraform#29038]
### Terraform Version

```
Terraform v1.0.1
on darwin_amd64
```

### Terraform Configuration Files

main.tf:
```terraform
output "variableRead" {
    value = var.jsonDefinedVar 
}
```

terraform.tfvars.json:
```json
{
    "jsonDefinedVar": "This works!"
}
```

### Expected Behavior

The variables should of been automatically loaded from the `terraform.tfvars.json` file

### Actual Behavior

```
│ Error: Reference to undeclared input variable
│ 
│   on main.tf line 3, in output "api_key":
│    3:     value = var.jsonDefinedVar 
│ 
│ An input variable with the name "jsonDefinedVar" has not been declared. This
│ variable can be declared with a variable "jsonDefinedVar" {} block.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`
3. `terraform apply`

**Comment by mildwonkey** [comment]
Hi @istvanfedak,

This error isn't coming about because terraform isn't loading the tfvars file; the variable needs to be declared in your configuration (main.tf or another file) before you can define it's value in the tfvars file. 

If you add the a `variable` block to your main.tf (with whatever configuration makes sense for your actual use case), it will work:
```hcl
variable "jsonDefinedVar" {
   type = string 
}
```

You can find our variable documentation [here](https://www.terraform.io/docs/language/values/index.html).

**Comment by istvanfedak** [comment]
Thank you @mildwonkey!
