### ISSUE TITLE
How to pass Json value to String variable in .tfvars file ?

### ISSUE THREAD

**Issue by NAbiKeerthana** [hashicorp/terraform#29036]
Hello Team,
I am passing a json value to a string variable as follows in the .tfvars file,
String variable= {“apis-demo”: “apis-demo”, “apis-demo.tls”: “apis-demo”}

I am getting the below issue:
Error: No value for required variable

and if I use jsonencode func - Error: Function calls not allowed

Could you please help me to solve this issue. Please tell me how to pass a json value to .tfvars file.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
