### ISSUE TITLE
Cost Estimation: unsupported state format version: expected "0.1", got "0.2"

### ISSUE THREAD

**Issue by travismsmith-acn** [hashicorp/terraform#29030]
### Terraform Version

```
Terraform v1.0.1
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  backend "remote" {
    hostname     = "tfe.hostname"
    organization = "Organization"

    workspaces {
      name = "my-workspace"
    }
  }
}
```

### Crash Output

Cost Estimation encountered an error: 
unsupported state format version: expected "0.1", got "0.2"

### Expected Behavior

Cost estimation to occur

### Actual Behavior

Cost estimation fails with the error: unsupported state format version: expected "0.1", got "0.2"

### Steps to Reproduce

1. Upgrade a workspace to terraform version 1.0.1
2. `terraform plan`

### Additional Context

Terraform plans against a TFE backend with version 1.0.1 creates errors for cost estimation.

**Comment by alisdair** [comment]
Hi! Thanks for reporting this.

The cost estimation team is aware of this issue and a fix is underway. In the interim, you should be able to downgrade to Terraform 1.0.0 as a workaround.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud and Terraform Enterprise are developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud or a Terraform Enterprise contract, please feel free to send this feedback to your usual support contacts. Otherwise, you can ask for help on our [Terraform Cloud & Enterprise forum](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44), or report a bug by contacting the Terraform Cloud support team at tf-cloud-support@hashicorp.com. If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
