### ISSUE TITLE
Please support add OpenBSD to goreleaser on all providers modules!!!

### ISSUE THREAD

**Issue by gred7** [hashicorp/terraform#29043]
### Current Terraform Version

```
terraform version
Terraform v1.0.1
on openbsd_amd64
```

### Use-cases
well, being a DevOps Engineer in software outsourcing company, I have many projects where I use terraform to create infrastructure on different platforms.
my exact problem now is:

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/aws v3.47.0 does not have a package available for your current platform,
│ openbsd_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other
│ versions of this provider may have different platforms supported.
╵
I use OpenBSD as my  workstation, and home server.

### Proposal

my proposal is simple. you should have a working builds of all modules for all OS that you build terraform for.

**Comment by apparentlymart** [comment]
Hi @gred7! Thanks for reporting this.

The platforms supported for each Terraform provider are decided by the team that maintains that provider and not under the control of the team who maintains Terraform Core in this repository. Therefore there's nothing we can change in this repository that would achieve OpenBSD support for the AWS provider or any other provider, and so I'm going to close this.

I believe that the default set of platforms in [the example GoReleaser configuration in the provider boilerplate repository](https://github.com/hashicorp/terraform-provider-scaffolding/blob/4b64ccca450d636b45d2addea708bc74e738520f/.goreleaser.yml#L18-L27) represents the set of platforms that the provider teams at HashiCorp are committed to support, which doesn't include OpenBSD as you've seen.

Similarly, [the Terraform Core team only officially supports Terraform CLI on Linux, macOS, and Windows](https://www.terraform.io/docs/language/v1-compatibility-promises.html#supported-platforms) and we provide the other packages only on a best-effort basis because it happens to be easy to include them in the cross-compilation process we use for releases.

While you certainly can continue to use Terraform on OpenBSD if you wish, unfortunately a consequence of using a platform not officially supported is that you will need to do some additional work yourself in order to ensure that both Terraform and the providers you intend to use continue to be functional on that platform in new releases, and possibly patch them yourself if not. I can only speak for the Terraform Core team and not for the various provider teams, but we do not have the resources to fully support operating systems beyond the most commonly-used three listed in our compatibility promises and I don't expect that to change for the foreseeable future.

I'm sorry I don't have a better answer for you, but unfortunately this is one of the tradeoffs we have to make in order to prioritize impact for as many Terraform users as possible.
