### ISSUE TITLE
list groups for user error

### ISSUE THREAD

**Issue by marklinglon** [hashicorp/terraform#29046]
panic: interface conversion: interface {} is ram.GroupInListGroups, not ram.GroupInListGroupsForUser

provider "alicloud" {}

data "alicloud_ram_groups" "groups_ds" {
  output_file = "groups.txt"
  user_name   = "guang.qu"
}

output "first_group_name" {
  value = "${data.alicloud_ram_groups.groups_ds.groups}"
}

**Comment by apparentlymart** [comment]
Hi @marklinglon,

Without a full stack trace I can't be 100% sure, but this crash seems to have originated in the Alicloud provider rather than in Terraform Core, and so I would suggest reporting it in [the Alicloud provider's repository](https://github.com/aliyun/terraform-provider-alicloud) so the provider maintainers will see it.

We only use this repository for development of Terraform Core, so there's unfortunately nothing we could change here to avoid that provider bug, and so I'm going to close this. Thanks!
