### ISSUE TITLE
'terraform validate' crashes, apparently caused by curly brace in a wrong place

### ISSUE THREAD

**Issue by rmrichesjr1** [hashicorp/terraform#29041]
While trying to figure out the correct syntax for a resource declaration, 'terraform validate' crashed, apparently on the following in main.tf:

```
resource "aws_instance" {var.DeploymentID} {
  ami           = ""
  instance_type = ""

  tags = {
    Name = ""
  }

}
```
[crash.151424376.log](https://github.com/hashicorp/terraform/files/6718360/crash.151424376.log)
[crash.974192919.log](https://github.com/hashicorp/terraform/files/6718364/crash.974192919.log)

**Comment by jbardin** [comment]
Hi @rmrichesjr1,

Thanks for filing the issue. I'm not able to reproduce the crash with the example shown, do you have any more information about your configuration that may help track down the issue? If you do have a single config file that can cause this, could you provide the exact file used rather than the copy&pasted text. I wonder if there is some unprintable characters or data that may   be effecting the printing of the diagnostics. 

Thanks!

**Comment by rmrichesjr1** [comment]
Hi James,

Sorry I had not sent enough of a test to reproduce the crash.  The following single, self-contained main.tf file produced this new crash log.  (Of course, please rename from main.tf.txt back to main.tf before trying to run.)
[main.tf.txt](https://github.com/hashicorp/terraform/files/6718928/main.tf.txt)
[crash.213197840.log](https://github.com/hashicorp/terraform/files/6718931/crash.213197840.log)

Thanks,

Robert

**Comment by jbardin** [comment]
Thanks @rmrichesjr1 , that does it!

Reduced a bit more, this still panics after writing the diagnostics:

```
resource "aws_instance" {var.Var2} {
}

#
```

**Comment by apparentlymart** [comment]
Took me a few tries here to realize that the crucial part of the repro case @jbardin shared is that trailing comment. Without it, Terraform seems to just correctly report the syntax errors. Just sharing this in case it's helpful to someone else trying to repro this too!

**Comment by apparentlymart** [comment]
It seems like this problem is originating in the "snippet" generation logic which produces the data structure we see in the JSON output, which is also used to produce the human-oriented diagnostic messages:

```json
{
  "context": "resource \"aws_instance\"",
  "code": "#",
  "start_line": 3,
  "highlight_start_offset": -1,
  "highlight_end_offset": 0,
  "values": []
}
```

`-1` is not a valid offset into the source code and hence the renderer is panicking trying to find that location in the source code buffer.
