### ISSUE TITLE
is there any scenario to apply rolling update to already deployed terraform module ?

### ISSUE THREAD

**Issue by Umair841** [hashicorp/terraform#29056]
### Current Terraform Version

```
...
```

**Comment by apparentlymart** [comment]
Hi @Umair841,

This seems to be a usage question rather than a feature request, in which case I'd suggest starting a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) to discuss it. If you do, please be sure to include a little more context about what you are trying to do, what you've tried so far, and what happened when you tried it.

Unfortunately there isn't really enough information here for this issue to represent a specific goal for the Terraform team, and so I'm going to close this just because we use GitHub issues only to track bugs to be fixed or new use-cases to consider. If we do discuss in the community forum and find you have an interesting new use-case to consider then we can open a new issue to capture the full details about what we talked about. Thanks!
