### ISSUE TITLE
Drop the need for state files

### ISSUE THREAD

**Issue by mcandre** [hashicorp/terraform#29067]
State files are error prone, and create an extra requirement for the user to remember to carefully manage the state in a cloud bucket (which is a manually provisioned resource). The next version of Terraform would be much improved by dropping the need for state files. Ansible, for example, works without depending on state files.

**Comment by chriswahl** [comment]
Curious if you've read the [Purpose of Terraform State](https://www.terraform.io/docs/language/state/purpose.html) doc?

**Comment by apparentlymart** [comment]
Hi @mcandre! Thanks for opening this issue.

As @chriswahl noted, state snapshots are a crucial part of Terraform's design and so there isn't currently any known path to a situation where Terraform would not use them anymore.

We would of course be open to discussing a more detailed technical proposal that describes how Terraform would meet all of the same use-cases (as described in the documentation linked above) without the need for persistent state snapshots, but in the absence of such a proposal I don't really see a path forward for this issue and so I'm going to close it.

Note that Ansible has different design constraints and so it would not be sufficient to simply state that Terraform should do "what Ansible does" without a more detailed analysis of how Ansible's capabilities and workflow relate to Terraform's. For those that prefer Ansible's workflow and design tradeoffs, they are of course free to use Ansible instead of Terraform where appropriate.

Thanks!
