### ISSUE TITLE
Unable to delete Powershell DSC Extention when deleting windows server

### ISSUE THREAD

**Issue by alexgoldberg1961** [hashicorp/terraform#29076]
I created and attached a powershell DSC script using resource "azurerm_virtual_machine_extension" "sample" {}
When performing destroy, the command times out failing to delete "azurerm_virtual_machine_extension" "sample" {} resource.

**Comment by apparentlymart** [comment]
Hi @alexgoldberg1961,

This seems to be either a bug report for the Azure provider or a usage question for that provider. This repository is for Terraform Core, not for any particular provider, and so the folks who monitor issues here can't help with Azure-related problems and I'm going to close this.

I suggest starting a topic in [the Azure provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34), though if you do please be sure to share some more information about what you're seeing, ideally including your relevant Terraform configuration and the full Terraform output, so that folks in the forum will have a chance of understanding what might be happening.

Thanks!
