### ISSUE TITLE
Include data source / resource in useragent of API call

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform#29094]
### Current Terraform Version

1.0.1

### Use-cases

- Track respurces / data sources in cloudtrail
- Prevent people from using specific resources (like aws iam policy attachment) by checking for a string in the useragent

### Attempted Solutions

n/a

### Proposal

add resources and data sources to useragent

### References

n/a

**Comment by apparentlymart** [comment]
Hi @nitrocode,

I think we discussed this in chat previously when I wasn't at my computer to be able to update GitHub, but just to close this loop: provider plugins are entirely separate programs that are responsible for their own HTTP requests, and so adding anything to the requests made to AWS APIs would need to be handled within the AWS provider.

It's possible that such a thing could be generalized across providers by implementing it in the provider SDK, at least for providers that configure their HTTP clients using logic in the SDK, but I'd suggest starting this discussion in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) and then the AWS provider team can consider this request and, if they want to move forward with it, potentially discuss with the SDK team the possibility of a more general solution.

Since Terraform Core doesn't control how providers make HTTP requests, and therefore there's nothing we could change here to get the effect you are describing, I'm going to close this issue. Thanks!
