### ISSUE TITLE
configuration_aliases throws misleading error in 0.14.x even though  required_version = ">= 0.15"

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform#29109]
### Terraform Version

```
Terraform v0.14.11
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.15"
  required_providers {
    aws = {
      source                = "hashicorp/aws"
      version               = ">= 3.40"
      configuration_aliases = [aws.this]
    }
  }
}
```

### Expected Behavior

Throw the error for unsupported terraform core version first thing on a `terraform init`. This should be the first thing checked because if there is a required version, chances are that a non-supported version is going to have features that will look like errors.

### Actual Behavior

```
$ terraform init

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid required_providers object

  on versions.tf line 4, in terraform:
   4:     aws = {
   5:       source                = "hashicorp/aws"
   6:       version               = ">= 3.40"
   7:       configuration_aliases = [aws.this]
   8:     }

required_providers objects can only contain "version" and "source" attributes.
To configure a provider, use a "provider" block.


Error: Variables not allowed

  on versions.tf line 7, in terraform:
   7:       configuration_aliases = [aws.this]

Variables may not be used here.
```

### Steps to Reproduce

1. terraform init

**Comment by jbardin** [comment]
While we are not planning any further development or releases of Terraform 0.14, I'm going to leave this open for a while to help any other users find it if they run into the error during the upgrade process.

The problem here is that In order to check the `required_version` attribute, the `terraform` configuration block must first be decoded, which in this case also contains the invalid `configuration_aliases` attribute. Unfortunately this combination of backwards incompatible changes was not noticed until after 0.14 development was complete, so it's not likely something that can be changed.

**Comment by grimm26** [comment]
> While we are not planning any further development or releases of Terraform 0.14, I'm going to leave this open for a while to help any other users find it if they run into the error during the upgrade process.
> 
> The problem here is that In order to check the `required_version` attribute, the `terraform` configuration block must first be decoded, which in this case also contains the invalid `configuration_aliases` attribute. Unfortunately this combination of backwards incompatible changes was not noticed until after 0.14 development was complete, so it's not likely something that can be changed.

@jbardin  ok, forget about 0.14.  What about when there is a feature add like this between 1.0 and 1.1?

**Comment by jbardin** [comment]
Hi @grimm26, if there is another backwards incompatible change to the `terraform` block during the 1.0 and 1.1 release cycle, then you would need to be on the latest patch release in 1.0, and 1.1 would be expected to implement the version check before any new feature is parsed.

As for additional meta-arguments in general, that is something we are working on handling differently in the long run. There will probably be some refactoring of the `required_version` check to handle changes in upcoming releases, but we will use this particular issue to track the known bug rather than possible future bugs.

**Comment by grimm26** [comment]
@jbardin is there an issue open to track implementation of "refactoring of the required_version check to handle changes in upcoming releases" that I can follow?
