### ISSUE TITLE
Terraform Crash When Creating Nimbus Alias

### ISSUE THREAD

**Issue by nikkharris** [hashicorp/terraform#29114]
### Terraform Version

```
0.15.1
```

### Terraform Configuration Files

```terraform
...
```

### Crash Output

https://prod.deploy.sky.site.gs.com:8368/api/v1/terraform/spr-039900-prodp/runs/id/1625676343864/output.html

### Expected Behavior

What should have happened?
Nimbus Alias should have been created followed the following step: https://canvas.site.gs.com/#/gsCloud/?tab=about&namespace=nimbus&type=gscloud_nimbus_vserver

### Actual Behavior

Got the following error:
https://prod.deploy.sky.site.gs.com:8368/api/v1/terraform/spr-039900-prodp/runs/id/1625676343864/output.html

### Steps to Reproduce

Added this code and then ran conduit: http://prod.codestream.site.gs.com:19900/review/SELFIDRES-76/revision/202/fileGuid/ec395d7d0fbe67574727db7e9da5cf1d/minRev/200/maxRev/202/diffDetails

**Comment by jbardin** [comment]
Hi @nikkharris,

Thanks for filing the issue. I'm not able to access the resource you've provided, it would be better if they could be supplied through GitHub in some way, gists are often the best way for large amounts of text. 

Before you do that however, I would suggest verifying that the problem exists in the current 1.0.2 release of terraform, as there have been numerous bug fixes released since 0.15.1. 

Thanks!

**Comment by jbardin** [comment]
We have not heard back in a while, so I'm going to close the issue. If you have more information, please feel free to file a new issue, or if there are more questions, you can use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
