### ISSUE TITLE
base64encode for map

### ISSUE THREAD

**Issue by aigdevops84** [hashicorp/terraform#29123]
### Current Terraform Version

```
Terraform v0.14.9
```

### Use-cases

```
In order to create configuration file for kubernetes secret, I need to base64 encode config.json that contains map like below:
{ "auths": {"some docker registry url":{"auth":"ZGVwbG95bWVusdfswkflwekfrl;sjkfopdDpkZXBsb3ltZW50MTIz"}}}
I wish to be able to encode with base64 for map parameter.
Now I have the following error: local.config_json is object with 1 attribute "some docker registry url". Invalid value for "str" parameter: string required. 
```

### Attempted Solutions

```
I tried to use filebase64 function, which allowed me to encode that map correctly from file.
I have the following configuration:
resource "local_file" "secrets" {
  filename = "${path.module}/secret.yaml"
  content          = <<-EOT
   apiVersion: v1
   data:
     .dockerconfigjson: ${filebase64("${local_file.config.filename}")}	
   kind: Secret
   metadata:
     name: name 
     namespace: default
   type: kubernetes.io/dockerconfigjson
  EOT
  depends_on = [local_file.config]
}
resource "local_file" "config" {
  filename = "${path.module}/config.json"
  content     = <<-EOT
   {"auths": ${jsonencode({for x,y in local.secrets_map : x  => {"auth" = base64encode(y.value)}})}}
  EOT
}
But there is another issue on the planning stage that the file, which should be created  doesn't exist even when explicit and implicit dependencies defined. 
```

**Comment by jbardin** [comment]
Hi @aigdevops84,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by aigdevops84** [comment]
Hi @jbardin,
I propose to create a special function which can encode a map.

Thanks!

**Comment by jbardin** [comment]
Sorry @aigdevops84, I'm not sure I understand. Base64 encoding is a way to encode a binary stream, but a map (or object) in terraform is a logical data structure, rather than a series of bytes. If you want to transform a json-encoded representation of a map to base64 encoding, the `base64encode` function with `jsonencode`  can already do that: `base64encode(jsonencode(local.obj))`

**Comment by aigdevops84** [comment]
@jbardin Thanks for your prompt reply.
Yes, you are totally right and I already tried it and base64encode function works fine, but it returns me value with back slashes: {"auths":"{\"some docker registry url\":{\"auth\":\"ZGVwbG95bWVusddwl;k;;kl[pdDpkZXBsb3ltZW50MTIz\"}}"}.
Hence it doesn't work when it comes to kubernetes secret for pulling images.
However I still can't find appropriate solution how to implement it, and just one question, why it's not possible to create function like "filebase64" which can encode different types, without using file.
BR,
Ivan

**Comment by jbardin** [comment]
Can you show an example of data that does not work for your use case? Backslashes are not in the base64 character set, nor are there any characters that require escaping within utf8 strings.

The problem with looking for a function to encode various types of values as base64 is that you have not specified how to encode those values in the first place. The most literal translation of your request would be to base64 encode the internal memory structure of the terraform values, which is not very useful. The file provided to `filebase64` is already a series of byes which can be re-encoded as needed, but for some arbitrary value in terraform you must first must decide _how_ the value will be encoded to stream of bytes, be it json, yaml, hcl, etc. We already provide the `jsonencode` and `yamlencode` functions which can serve this purpose.

**Comment by aigdevops84** [comment]
@jbardin First of all I really appreciate your time and involvement.
Let's consider that example:
resource "local_file" "secrets" {
  filename = "${path.module}/secret.yaml"
  content          = <<-EOT
   apiVersion: v1
   data:
     .dockerconfigjson: ${base64encode(jsonencode({ "auths": jsonencode({for x,y in local.secrets_map : x  => {"auth" = base64encode(y.value)}}) }))}	
   kind: Secret
   metadata:
     name: name 
     namespace: {{ .Release.Namespace }}
   type: kubernetes.io/dockerconfigjson
  EOT
}
It returns file with the following content:

apiVersion: v1
data:
     .dockerconfigjson: eyJhdXRocyI6IntcImV4YW1wbGUuY29tOjgwODRcIjp7XCJhdXRoXCI6XCJaR1Z3Ykc5NWJXVnVkRHBrWlhCc2IzbHRaVzUwTVRJelwifX0ifQ==	
kind: Secret
metadata:
      name: name 
      namespace: {{ .Release.Namespace }}
 type: kubernetes.io/dockerconfigjson 

If you do echo "eyJhdXRocyI6IntcImV4YW1wbGUuY29tOjgwODRcIjp7XCJhdXRoXCI6XCJaR1Z3Ykc5NWJXVnVkRHBrWlhCc2IzbHRaVzUwTVRJelwifX0ifQ==" | base64 -d
you will see the map which contains backslashes and it doesn't work in k8s.
Thank you.

**Comment by jbardin** [comment]
The decoded json object contains backslashes, because `auths` is a string which contains double quotes. This has nothing to do with the base64 encoding, if you don't want the `auths` value to be json encoded as a string, then don't use `jsonencode` for that value (and you probably don't want to double-encode the auth value either)

```
  value = base64encode(jsonencode({
    auths = { for x, y in local.secrets_map :
      x => { auth = y.value }
    }
  }))
```

If you have any more questions, I'm going to suggest again the [community forum](https://discuss.hashicorp.com/c/terraform-core) where there are many more users who can help.

**Comment by aigdevops84** [comment]
Hi @jbardin 
Sorry for a late response (last week I became a father :) ), I just want to say thank you for your provided solution, it's really helped me and resolved my issue.
Thanks,
Ivan
