### ISSUE TITLE
`terraform plan --detailed-exitcode` exits with incorrect exitcode in GitHub Actions workflow

### ISSUE THREAD

**Issue by BryceBeagle** [hashicorp/terraform#29130]
Running `terraform plan --detailed-exitcode` does not work as expected in a GitHub Actions environment. If there are plan changes, the command _prints_ that it's exiting with exitcode 2, but then actually exits with exitcode 1. 

This works as expected when running locally. I can only reproduce this within the GitHub Actions environment.

I have produced an MVCE repo [here](https://github.com/BryceBeagle/mvce-terraform-exitcode
) which executes the following Python script:
```python
import subprocess
import sys
  
command = ["terraform", "plan", "--input=false", "--detailed-exitcode"]
exit_code = subprocess.run(command, check=False).returncode
  
print(f"Exit code: {exit_code}")
  
if exit_code == 0:
    plan_has_changes = False
elif exit_code == 2:
    plan_has_changes = True
else:
    sys.exit(exit_code)
  
print(f"::set-output name=plan-has-changes::{plan_has_changes}")
```

The following gets printed in the GitHub Actions log:

```
/home/runner/work/_temp/c6396210-1359-4c63-9774-440a5081a128/terraform-bin plan --input=false --detailed-exitcode

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # random_uuid.random will be created
  + resource "random_uuid" "random" {
      + id     = (known after apply)
      + result = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
::debug::Terraform exited with code 2.
Error: Terraform exited with code 2.
Exit code: 1
Error: Process completed with exit code 1.
```

(I have tested and observe similar functionality when using a raw bash script)

### Terraform Version

```
1.0.1
```

### Expected Behavior
Terraform should exit with exitcode 2

### Actual Behavior
Terraform prints that it is exiting with exitcode 2, but then exits with exitcode 1

### Steps to Reproduce
MVCE repo with GitHub action.
https://github.com/BryceBeagle/mvce-terraform-exitcode

The result of the GitHub Action run can be seen here: 
https://github.com/BryceBeagle/mvce-terraform-exitcode/runs/3030899426

**Comment by apparentlymart** [comment]
Hi @BryceBeagle! Thanks for reporting this.

I was initially quite confused here because Terraform CLI itself doesn't typically print anything like the following two lines from your output:

```
::debug::Terraform exited with code 2.
Error: Terraform exited with code 2.
```

After some further research though I've learned that the `hashicorp/setup-terraform` GitHub action makes the command `terraform` actually be [a wrapper script](https://github.com/hashicorp/setup-terraform/blob/625cb76050397c6b3a1789261eb129f8f39a206b/wrapper/terraform.js) rather than Terraform CLi itself. That wrapper script seems to be the one printing out Terraform CLI's exit code, but then it signals the unsuccessful run by a call to `core.setFailed`, which seems to be part of `@actions/core`. I'm not familiar with that library but since the call to it doesn't include the exit code from Terraform except as part of the message string I assume that's the place where it's losing the detail of exactly which exit code Terraform generated.

Having concluded this I then found setup-terraform#9 where this problem already seems to be under discussion. Since this problem is in the wrapper around Terraform rather than in Terraform itself, I'm going to close this issue in favor of the one over in the `hashicorp/setup-terraform` repository.

It seems like some of the participants in that other issue have found a different approach where they bypassed the wrapper script, so hopefully something similar could work for you as well, but I'm afraid I don't have enough GitHub Actions knowledge myself to understand what purpose this wrapper serves and thus what the consequences would be of bypassing it.

Thanks again!
