### ISSUE TITLE
how to notify which module or resource  is completed

### ISSUE THREAD

**Issue by jainpratik163** [hashicorp/terraform#29139]
### Current Terraform Version

```
...
```

### Use-cases
Currently we are creating whole infrastructure with terraform using Jenkins and we are running modules in parallel and during run it is very difficult to find which all modules are been installed or still running.
once the installation failed or passed then we need to search for straight like "Apply complete! Resources"
And also i was not able to find a way by which at the end we run command and we will know which all modules installed.

### Attempted Solutions

for now, i am trying to create a txt file using `local_exec `  and `echo "installation done"`

### Proposal

there should be a simple way which fulfills these needs and also make logging simple.

**Comment by jbardin** [comment]
Hi @jainpratik163,

Thanks for filing the issue. Terraform modules are a way to organize mad parameterize configuration, but because resources are applied based on their individual dependencies, there is no indication when a module as a whole has been completed. I'm also not sure what you mean by running a command after all modules are installed, since "all modules" essentially means the "entire configuration", in which case terraform exits when it's complete. 

You may be interested in the [Running Terraform in Automation](https://learn.hashicorp.com/tutorials/terraform/automate-terraform) guide, and may see something useful in the [GitHub Actions](https://learn.hashicorp.com/tutorials/terraform/github-actions) examples as well. If you're looking for machine readable output, you can see documation for that new feature here: [Machine Readable UI](https://www.terraform.io/docs/internals/machine-readable-ui.html).

Since there isn't a clear use case to solve here, I'm going to close this issue. Please feel free to start a thread in [the community forum](https://discuss.hashicorp.com/c/terraform-core), where we can discuss possible alternatives, and maybe craft a new enhancement request if the problems cannot be solved otherwise.

Thanks!

**Comment by jainpratik163** [comment]
Hi,

we are trying to build infrastructure on AWS and we are creating modules for EKS,R53,MSK,RDS etc .
and then we are running all modules parallelly via Jenkins but Jenkins logs are not clear which modules are installed.
so we want some command if we run that say which all modules installed or in-progress or failed.

Thanks,
Pratik
