### ISSUE TITLE
issue with local-exec provisioner using AWS assume role 

### ISSUE THREAD

**Issue by ajinkyajoshi** [hashicorp/terraform#29142]
background-
IAM user created in root AWS account with access key and secret access key that user is assuming role in child accounts
That assumed role in used in Terraform configuration .
Code snippet:
`provider "aws" {
  region     = "us-east-1"
  assume_role {
    role_arn     = "arn:aws:iam::XXXXXXXXXXXX:role/Assumed_CICD"
  }
}`

I am trying to print all the S3 buckets available in one of the child account using local-exec provisioner.
Code snippet:
`resource "null_resource" "aws-command-test" {
    provisioner "local-exec" {
        command = "aws s3 ls"
    }
}`

When I do terraform apply the configuration is executing on my local server but **its picking buckets listed in root account than listing the ones from required child account.**
I understand that we do have option of getting temporary security credentials of child account using "AWS STS" command but we need some direct way to achieve this.

**Comment by jbardin** [comment]
Hi @ajinkyajoshi,

Unfortunately there's not much Terraform can do to help the `aws` CLI command handle it's own authentication. I'm not familiar with all the possible options available with that command, but the first thing I would look at is selecting credentials via a named profile, which you can assign with the `AWS_PROFILE` environment variable.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. 

Thanks!
