### ISSUE TITLE
Sensitive values are sent to stderr if there are type errors

### ISSUE THREAD

**Issue by memriseed** [hashicorp/terraform#29156]
If you define a sensitive variable with a type definition then try to assign a value to it with an invalid type, that value is printed out verbatim.  Terraform is usually very good at not printing sensitive variables so it's possible this is intended behaviour.  However, invalid type definitions or assignments aren't uncommon when making changes so this behaviour could easily leak secrets, hence I've categorised this as a bug. Thanks!

### Terraform Version

```
1.0.1, 0.15.5
```

### Terraform Configuration Files
https://github.com/memriseed/sensitive-vars-example

### Expected Behavior
If a sensitive variable encounters an issue with an invalid value, it should redact or suppress output containing that value.

### Actual Behavior
Terraform prints the following error message, containing the un-redacted contents of the values file:

```
╷
│ Error: Invalid value for input variable
│ 
│   on secrets.auto.tfvars line 5:
│    5: secret_var = ["test"]
│ 
│ The given value is not valid for variable "secret_var": string required.
╵
```

### Steps to Reproduce

1. Clone the repo above
2. `terraform init`
3. `terraform plan`

### References
I couldn't find any references to this in existing issues but there are a lot of them and the Github search tool isn't perfect - please let me know if this has already been raised!

**Comment by jbardin** [comment]
Hi @memriseed,

Thanks for filing the issue. This is slightly different than most cases dealing with sensitive values, since the error is not printing the actual value itself, rather it's just pointing to the context within the configuration file. The data read from the source file was never loaded into the sensitive variable,  because it was not a compatible type.

In order to run terraform one must be able to read the configuration files, hence have access to any hard-coded secrets in those files. I think there may be a relatively simple fix for the use case presented here, but it's going to be very specific to a sensitive root module variable and a tfvars file and it seems like there may have been a less contrived issue that brought this up. Did you have a use-case where secrets could be written out which the operator would not normally have access to?

**Comment by memriseed** [comment]
Hi @jbardin, thanks for responding promptly!

Our Terraform workflow uses Atlantis with Github, with secrets in checked-in encrypted var files and a custom workflow to decrypt secrets at plan or apply time. If this issue occurs in a pull request (ie a variable or a source var file is changed and raises a type error), Atlantis will output the error text in that pull request.  Without printing the Terraform output within pull requests our current flow doesn't work at all so we need some way of filtering it.

I thought it might be possible to redact the data from the source file if the variable trying to read it in is sensitive.  From looking at the Terraform source, whether or not the variable is sensitive should be available at the point where this error is raised:  https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/terraform/variables.go#L258

I understand there may be other reasons not to change this behaviour, but it was surprising enough to us we thought it was worth raising a ticket.  Thanks!
