### ISSUE TITLE
Terraform refresh returns outputs after terraform destroy 

### ISSUE THREAD

**Issue by wilsonandvmware** [hashicorp/terraform#29166]
### Terraform Version

```
Terraform v0.14.8 on darwin_amd64
```

### Terraform Configuration Files

I am using a terraform provider https://github.com/vmware/terraform-provider-vra/  to create some resources, I notice that after running terraform refresh, the previous destroyed output came back and show up in my terminal. I don't think it is a provider issue because I was not able to reproduce it in 0.13 but can reproduce once I upgrade terraform to 0.14. I also checked the changelog but could not find anything related to it.

```terraform
resource "vra_project" "this" {
  name        = "test"
}
output project_name {
  value = vra_project.this.*.name
}
```

### Expected Behavior

shows the original message only
```
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.
```

### Actual Behavior

Note the outputs at the end

```
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.


Outputs:

project_name = [
  "test",
]

```
### Steps to Reproduce

terraform init
terraform apply
terraform destroy
terraform output (up to this point, we can see the output has been destroyed)
terraform refresh

**Comment by apparentlymart** [comment]
Hi @wilsonandvmware! Thanks for reporting this.

I think this odd behavior arises because in recent versions of Terraform there isn't actually really any separate "refresh" step anymore, and instead Terraform handles refresh during planning. In order to keep the `terraform refresh` command working, we change it to effectively just run `terraform plan` and then discard the planned changes.

This creates an odd situation for your particular case because the hidden internal plan can see that `output "project_name"` depends on a value defined in the configuration, and thus it's able to populate it in the same way that we'd normally expect an output value to change if planning were to detect that a value had changed upstream.

While this behavior is certainly pretty _strange_, I don't know that there's really anything we could do about it other than make some sort of exception related to refreshing a totally-empty state, where Terraform just skips doing anything and immediately returns the "Empty or non-existent..." message. However, that would still not _entirely_ achieve the original behavior of `terraform refresh`, because it would still behave in a similar odd way in the following situation...

* Create a configuration file with only one resource defined, and apply it.
* Add a new resource to that file and an output value which depends on that resource, but _don't_ apply it.
* Run `terraform refresh`.

This is a variant of what you saw where the state isn't actually _empty_ but the output value still happens to refer to something that doesn't yet exist.

Although nothing is decided for certain yet, we're considering phasing out `terraform refresh` (e.g. deprecating it) in favor of the newer `terraform plan -refresh-only` and `terraform apply -refresh-only` mechanisms. For that reason, I'd be interested to see what happens in a similar situation when creating a refresh-only plan. I _expect_ the behavior will be more reasonable in that case because the refresh-only plan mechanism is designed to fit better into the planning flow. If it _does_ work better in this case then we could consider addressing this bug by simply making `terraform refresh` an alias for `terraform apply -refresh-only -auto-approve`, in the same sense that `terraform destroy` is really just an alias for `terraform apply -destroy`.

**Comment by wilsonandvmware** [comment]
@apparentlymart  thank you for the confirmation.
