### ISSUE TITLE
Incorrect order of destroy / create for AWS API Gateway domain

### ISSUE THREAD

**Issue by connoravo** [hashicorp/terraform#29174]
### Terraform Version

```
v13.4
```

### Terraform Configuration Files
Using count on a local true : false value to alternate which resource is in use.
```terraform
locals {
use_transition = true
}
```

```terraform

resource "aws_acm_certificate" "api_gw" {
  count             = local.use_transition ? 0 : 1
  domain_name       = "api.domain.com"
  validation_method = "DNS"
  provider          = aws.us-east-1
}

resource "aws_api_gateway_domain_name" "api_gw" {
  count = local.use_transition ? 0 : 1

  provider               = aws.eu-west-1
  domain_name            = aws_acm_certificate.api_gw.domain_name
  certificate_arn        = aws_acm_certificate.api_gw.arn
  security_policy        = "TLS_1_2"
}
```

vs.

```terraform
resource "aws_acm_certificate" "api_gw_transition" {
  count             = local.use_transition ? 1 : 0
  domain_name       = "api.domain.com"
  validation_method = "DNS"
  provider          = aws.eu-west-1
}

resource "aws_api_gateway_domain_name" "api_gw_transition" {
  count = local.use_transition[local.environment] ? 1 : 0

  provider                 = aws.eu-west-1
  domain_name              = aws_acm_certificate.api_gw_transition[0].domain_name
  regional_certificate_arn = aws_acm_certificate.api_gw_transition[0].arn
  security_policy          = "TLS_1_2"

  endpoint_configuration {
    types = ["REGIONAL"]
  }
}
```

### Expected Behavior
Switching an AWS API gateway from edge to regional, with the same domain, using two resources to overcome different resource property names (ie. certificate_arn vs. regional_certificate_arn); should seamlessly destroy the edge resource and create the regional resource.

When `local.use_transition` is set to true, the resource `api_gw_transition` should be created after `api_gw` is destroyed. As AWS provider restricts the use of a domain name to either edge or regional API gateway domain at any one time, not both.

### Actual Behavior
The resource `api_gw_transition` creation is started (according to terraform apply stdout), before the `api_gw` resource is destroyed, causing the errors:

```terraform
Error creating API Gateway Domain Name: BadRequestException: The domain name you provided already exists.

  on api_gateway.tf line 81, in resource "aws_api_gateway_domain_name" "api_gw_transition":
  81: resource "aws_api_gateway_domain_name" "api_gw_transition" {

Error: [ERR]: Error building changeset: InvalidChangeBatch: [RRSet of type CNAME with DNS name api.domain.com. is not permitted as it conflicts with other records with the same DNS name in zone api.domain.com.]
	status code: 400, request id: 123456-randomid
```

A second terraform apply, with the code unaltered, successfully deploys the resources - as the `aws_api_gateway_domain_name.api_gw` has been destroyed in previous apply.

### Steps to Reproduce
Create two certificates resources as above, one in us-east-1, and one in say eu-west-1. This will create a certificate (us-east-1) that can be used for edge optimised API gateways and one that can be used for regional gateways (eu-west-1). With associated certificate validation resources.

With local.use_transition set to false, terraform apply to environment. This will create an edge optimized api_gateway_domain_name.

Switch `local.use_transition` to true and terraform apply to environment. This will attempt to create aws_api_gateway_domain_name.api_gw_transition before it attempts to destroy aws_api_gateway_domain_name.api_gw, causing errors.

### Additional Context
```bash
aws_acm_certificate_validation.cert[0]: Destroying... [id=2021-07-15 08:35:52 +0000 UTC]
aws_acm_certificate_validation.cert[0]: Destruction complete after 0s
aws_acm_certificate.api_cert_transition[0]: Creating...
aws_route53_record.cert_validation[0]: Destroying... [id=123456.api.domain.com._CNAME]
aws_route53_record.api[0]: Destroying... [id=Z123456.domain.com_A]
aws_route53_record.api_transition[0]: Creating...
aws_acm_certificate.api_cert_transition[0]: Creation complete after 6s [id=redacted]
aws_api_gateway_domain_name.api_transition[0]: Creating...
aws_route53_record.cert_validation_transition[0]: Creating...
aws_route53_record.cert_validation[0]: Still destroying... [id=redacted....api.domain.com._CNAME, 10s elapsed]
aws_route53_record.api[0]: Still destroying... [id=redacted....api.domain.com_A, 10s elapsed]
aws_route53_record.cert_validation_transition[0]: Still creating... [10s elapsed]
aws_route53_record.api[0]: Still destroying... [id=redacted....api.domain.com, 20s elapsed]
aws_route53_record.cert_validation[0]: Still destroying... [id=redacted....api.domain.com._CNAME, 20s elapsed]
aws_route53_record.cert_validation_transition[0]: Still creating... [20s elapsed]
aws_route53_record.cert_validation[0]: Still destroying... [id=redacted....api.domain.com_A, 30s elapsed]
aws_route53_record.api[0]: Still destroying... [id=redacted....api.domain.com_A, 30s elapsed]
aws_route53_record.cert_validation[0]: Destruction complete after 32s
aws_route53_record.api[0]: Destruction complete after 32s
aws_api_gateway_domain_name.api_gw[0]: Destroying... [id=api.domain.com]
aws_api_gateway_domain_name.api_gw[0]: Destruction complete after 0s
aws_route53_record.cert_validation_transition[0]: Still creating... [30s elapsed]
aws_route53_record.cert_validation_transition[0]: Still creating... [40s elapsed]
aws_route53_record.cert_validation_transition[0]: Creation complete after 49s [id=redacted....api.domain.com._CNAME]
aws_acm_certificate_validation.cert_transition[0]: Creating...
aws_acm_certificate_validation.cert_transition[0]: Creation complete after 0s [id=2021-07-15 09:21:34 +0000 UTC]
```

**Comment by jbardin** [comment]
Hi @connoravo,

If I understand correctly, your intent here is to toggle between the individual resources, but they cannot exist simultaneously due to constraints in the remote API. I'm not sure if there's anything we're missing from the example, since `local.use_transition` appears to be a different type in each file and the resource references are not indexed, but I'll explain first as if they are.

In this example, since there are no references between the individual groups of resources, there is no way for terraform to know the intended order for removing one and creating the other. In most cases one would want to only have a single resource block for each of these, and modify the configuration as needed to switch the operational mode, this way the replacement can always be strictly ordered. 

It may seem appealing to try and use `depends_on` here, which would work for a single replacement, however you would need to modify the arguments each time you toggle the resources to prevent a cycle when needing to switch back.

Since Terraform is working as expected here, and this does not represent a specific bug in terraform, I'm going to close this. If you have any follow up questions about the behavior here feel free to reply, but we use GitHub issues for tracking bugs and enhancements, rather than for questions so it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
