### ISSUE TITLE
terraform plan doesn't check for cidr_block overlap when using aws provider

### ISSUE THREAD

**Issue by dlsniper** [hashicorp/terraform#2917]
Hi,

I have the following situation:
```
resource "aws_subnet" "eu-west-1a-first" {
  vpc_id = "${aws_vpc.default.id}"

  cidr_block = "10.0.24.0/20"
  availability_zone = "eu-west-1a"
}

resource "aws_subnet" "eu-west-1b-second" {
  vpc_id = "${aws_vpc.default.id}"

  cidr_block = "10.0.28.0/20"
  availability_zone = "eu-west-1b"
}
```

Terraform should be able to detect that the ```cidr_block``` from ```eu-west-1a-first``` overlaps with ```eu-west-1b-second``` and produce an error. Right now it doesn't and the error will be received only at runtime when ```terraform apply``` is ran.

**Comment by catsby** [comment]
Hey @dlsniper – thanks for writing in here, I apologize for the silence.

Right now, there's no way for Terraform to do this. Each provider is ran in it's own process, and each resource doesn't know about the other resources that are in-flight. Each resource only knows values of things that are interpolated for it, and it gets them from Terraform when it's their turn to run. In order to accomplish this, we would have to bubble up validation logic at the provider level and make Terraform consider all points on the graph for validation.

In the future we'd like to add this kind of resource-to-resource validation, but it's some ways off. For now, the runtime error and falling back to the cloud provider for validation of these things is the best we can do.
