### ISSUE TITLE
skip_cert_verification is not taken into account when pass as terraform init argument

### ISSUE THREAD

**Issue by MacPower** [hashicorp/terraform#29183]
### Terraform Version

```
Docker container from tag 1.0.2 from hashicorp/terraform.
```

### Terraform Configuration Files

```terraform

terraform {
  backend "http" {
  }
}
```

### Expected Behavior

There shoud be no error about certificate not trusted. 

### Actual Behavior

```
...
2021/07/15 15:57:52 [ERR] GET https://*************/api/v4/projects/***/terraform/state/gcds-instance request failed: Get "https://*************/api/v4/projects/***/terraform/state/gcds-instance": x509: certificate signed by unknown authority
``` 

### Steps to Reproduce

```bash 
terraform init \
-backend-config=address="${TF_HTTP_ADDRESS}" \
-backend-config=lock_address="${TF_HTTP_LOCK_ADDRESS}" \
-backend-config=unlock_address="${TF_HTTP_UNLOCK_ADDRESS}" \
-backend-config=username="${TF_HTTP_USERNAME}" \
-backend-config=password="${TF_HTTP_PASSWORD}" \
-backend-config=lock_method="${TF_HTTP_LOCK_METHOD}" \
-backend-config=unlock_method="${TF_HTTP_UNLOCK_METHOD}" \
-backend-config=retry_wait_min="${TF_HTTP_RETRY_WAIT_MIN}" \
-backend-config=skip_cert_verification=true
```

### Additional Context

I am using terraform inside a gitlab-ci and use Gitlab http terraform backend.

I was able to bypass certificate verification with : 

```terraform
terraform {
  backend "http" {
    skip_cert_verification  = true
  }
}
```

**Comment by jbardin** [comment]
Hi @MacPower,

It's not clear how this could be the case from looking at the code, as the options from the cli are handled nearly in the same way as options from the configuration. Can you verify that the flags you are passing are exactly as shown in the example here? One common mistake I've seen in shell scripts is an errant space after the `\`, so that the newline is not escaped causing later flags to be ignored.

Can you provide the trace logs from running the above init command, which will show the exact arguments passed in by the shell? You can also check the internal `.terraform/terraform.tfstate` which is where the configuration is stored to see if the `skip_cert_verification` is present.

Thanks!

**Comment by jbardin** [comment]
We have not heard back in a while, so closing the issue.
If you have more information necessary to reproduce the error, feel free to reply here and we can reevaluate the issue.

Thanks!
