### ISSUE TITLE
"Objects have changed outside of Terraform" for unsorted lists, json whitespace changes

### ISSUE THREAD

**Issue by evandam** [hashicorp/terraform#29181]
### Terraform Version

```
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0
```

### Terraform Configuration Files

https://gist.github.com/evandam/4b496cff2a17098260d78e317292fb24

### Expected Behavior

No objects have changed outside of Terraform, no changes to apply.

### Actual Behavior

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_kms_key.test_key has been changed
  ~ resource "aws_kms_key" "test_key" {
        id                       = "d82ff0c1-072b-4279-9caa-0270ffc60a10"
      ~ policy                   = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              - "arn:aws:iam::222222222222:role/admin",
                                "arn:aws:iam::111111111111:role/admin",
                              + "arn:aws:iam::222222222222:role/admin",
                            ]
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                     = {}
        # (8 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

`terraform apply`

### Additional Context

Sorry in advance if this is a duplicate issue or something to be handled in the AWS provider specifically, but seems like something that could be handled in Terraform itself.

Sorting the lists when comparing to external changes seems to make sense, considering Terraform still shows "Your infrastructure matches the configuration."

I also see changes like `~ assume_role_policy    = jsonencode( # whitespace changes`, using similar resources in the gist linked. My best guess is it may be related to the original resource being created with a previous version?

**Comment by apparentlymart** [comment]
Hi @evandam! Thanks for reporting this.

Unfortunately in this situation I don't think Terraform Core has sufficient information to know whether or not the order of this list is important.

You noted that there's no proposal to _undo_ this change, in which case I assume the provider has a "normalization vs. drift" rule which classifies a reordering of that particular list as normalization, and thus the provider doesn't propose to undo it.

From an architectural standpoint, it's the provider's responsibility to recognize that same situation during refresh and preserve your original value if it's functionally equivalent to what the remote API returned. However, in practice that's hard to do today because the mechanism in the Terraform SDK for concisely classifying normalization vs. drift is, due to a historical oversight, only applied during planning and not during refreshing.

Given that, although a purist view on this would technically characterize this as an AWS provider bug, it's a situation that I think would not be straightforward for the AWS provider team to resolve without help from the SDK, because in the current SDK design they'd need to essentially reimplement the same logic in the refresh implementation as they've already specified in the schema. For that reason, I'm going to raise a new issue for this in [the repository for the next-generation SDK](https://github.com/hashicorp/terraform-plugin-framework) to see what the SDK team thinks about addressing this historical oversight in the new SDK, which the AWS provider can hopefully then eventually adopt for this resource type.

**Comment by apparentlymart** [comment]
I've opened hashicorp/terraform-plugin-framework#70 to capture the underlying SDK problem here. In order to only have one issue representing this problem I'm going to close this one for now, though if discussion in that issue does lead to us planning any changes to Terraform Core then I'll either reopen this one or open a new issue to represent whatever we've decided.

Thanks again!

**Comment by evandam** [comment]
Sounds good, thanks @apparentlymart! I'll follow along over there. Looking forward to seeing more on this!
