### ISSUE TITLE
terraform source not able to pull azure devops repository in the pipeline

### ISSUE THREAD

**Issue by ARIY372606** [hashicorp/terraform#29185]
Hi,

I have a terraform repository and this repo has terraform file like below.  This repo has only terraform files and also tries to reach a similar terraform repo inside the same organization and project. I just created azure-pipeline.yml but when the pipeline runs InstallSSHKey and Terraform Installer task is successfully completed then at terraform init task I got an error like in the Gist file. Shortly "remote: Public key authentication failed.fatal: Could not read from remote repository. Please make sure you have the correct access rights  and the repository exists." 

### Terraform Configuration Files
lambda_s3_create_athena_view.tf
`module "some_module" {
  source = "git::ssh://git@ssh.dev.azure.com/v3/MyOrg/MyProject/repo-name-here//src/modules/tfpath/dsci-tf-modules?ref=v0.0.58"
}`
 
azure-pipelines.yml
 
 [Gist](https://gist.github.com/ARIY372606/1d2d94f99d01ad8f93d5f7eea5871652)

### Terraform Version
 
``` 
1.0.2
```

### Debug Output

Install SSH Key task
[Gist](https://gist.github.com/ARIY372606/76ef48bd17b1bb999764d3d7d5be254d)
Terrafrom Init task
[Gist](https://gist.github.com/ARIY372606/66ff134afdaa09b3b23727a199c3d996)
### References

- #20358
- #18869

**Comment by apparentlymart** [comment]
Hi @ARIY372606! Sorry for this odd behavior, and thanks for reporting it.

Unfortunately it seems like this is an error message from Git rather than an error message from Terraform. Internally Terraform is running a `git clone` command to get the content of the repository you linked and so Terraform itself doesn't directly interact with your git credentials in this case. Terraform is correctly handling the error by returning it to you, but it seems like your Git configuration doesn't match Git's expectations.

Unfortunately since this error is coming from Git it doesn't seem like something we could address by making changes to the Terraform code in this repository, and so I'm going to close this. I'd suggest trying a simpler example first where your pipeline just runs `git clone` directly itself and then see about getting that working, after which you should be able to reintroduce Terraform and get a working result. If you _do_ get things working with Git alone but then still find problems when you try to run Terraform, please open a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core) where we can tackle a wider variety of problems, whereas issues in this repository are only for tracking defects and feature requests for Terraform CLI/Core itself.

Thanks!
