### ISSUE TITLE
empty list comparison does not work

### ISSUE THREAD

**Issue by pieterza** [hashicorp/terraform#29187]
Terraform version 1.0.1

While I understand the equality operator does compare types, it is likely bad behavior/design given the example below.

When one does a test of [] == [], it's true that both are of type array but it should be MORE true that they are both empty arrays.

```
variable "myvar" {
  type    = list(any)
  default = []
}

output "if_default_then_should_be_empty" {
  value = var.myvar == [] ? "empty" : "not empty"
}
````

If we don't actually pass myvar, it defaults to []

But it looks like list comparisons don't work here.

Output:

```
pieters@redacted:~/code/test$ terraform plan

Changes to Outputs:
  + equal = "not empty"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
```

The following does work:

`value = length(var.myvar) == 0 ? "empty" : "not empty"`
 
 I see there is a similar issue logged, but it differs in that it assumes the issue only manifests with lists containing objects, where actually it looks simply like list comparisons are broken.
 
 https://github.com/hashicorp/terraform/issues/23562

**Comment by jbardin** [comment]
Hi @pieterza, thanks for the additional example here. The comparison fails for the same reason that linked issue fails, though the reason is even less obvious. 

The `[]` literal, regardless of the context always starts off as a `tuple` type, not a list. This means that you are comparing a `list` type to a `tuple` which is the reason you get `"not empty"` as the output. For comparison, you can change the variable type to `any` which would then make the default an empty tuple, and you can convert the `[]` literal with `tolist([])` to also get the desired result.

This is something where there is definite room for improvements, perhaps a warning for users relying on comparison to an empty tuple rather than checking the length of the collection.

Since any solution here would apply to issue #23562, I'm going to close this issue and we can follow along over in the original issue.

Thanks!
