### ISSUE TITLE
AWS Wafv2 resources missing from documentation table of contents in 3.50.0

### ISSUE THREAD

**Issue by smithje** [hashicorp/terraform#29192]
For example, we can go directly to this link to find a wafv2 resource:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_ip_set

However, the WAFv2 accordion is closed.  If I open that accordion, I only see Data Sources, no Resources.

The documentation worked correctly in 3.49.0, although it seems to be missing some resources that were present in previous versions:
https://registry.terraform.io/providers/hashicorp/aws/3.49.0/docs/resources/wafv2_ip_set

**Comment by apparentlymart** [comment]
Hi @smithje! Thanks for reporting this.

The documentation you've linked to here belongs to [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) rather than to this repository, so I don't think there's anything we could change here to address what you've reported.

I do see [the doc page you're talking about](https://github.com/hashicorp/terraform-provider-aws/blob/c0909519726347c3d375fe12eec96e752e5ab863/website/docs/r/wafv2_ip_set.html.markdown) in the provider repository, so I'm not sure what happened here, but I think the best thing would be to [open an issue in the provider repository](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose) where hopefully the provider dev team can explain what's going on here and make changes to address it.

Because this documentation doesn't belong to this repository, I'm going to close this issue. Thanks again!

**Comment by smithje** [comment]
Sorry for putting this in the wrong spot; I'll open a ticket in the provider repository.  Thanks for pointing me in the right direction.
