### ISSUE TITLE
Error Writing Fields: Source Data must be an array or slice, Got map

### ISSUE THREAD

**Issue by Pushp1403** [hashicorp/terraform#29229]
Terraform CLI 0.15.0

Hi Folks,

I have been struggling with this issue for a while. I have a load balancer provider which We use to create on-perm load balancer. It runs fine and I can see the LB created. But Terraform exits at the end with below ( approx) message:

"There was an issue but we are returning  a pointer not the error itself. Terraform error after apply"

And the issue which terraform reports is "Error Writing Fields endpoints.0.cert: "": Source Data must be an array or slice, Got map"

Here the endpoints is a valid json returned from provider which i am unmarshalling in a struct, which works fine. The endpoints JSON looks like below:

```javascript
"endpoints" : [{
    "profile" : "webssl",
    "cert" :   {
         "ssre_cnam" : "",
         "certname" : "certname",
         "namespace" : "some/name/space"
         "key"   :  "key/to/certificate"  
     }
    "lb_port":  443,
    { few more entries}   
}]
```

I tried debugging in provider, no error there. It works fine till sets ID fine. not sure why terraform complaining about json structure.  Have someone encountered any similar issue ? please help.

**Comment by jbardin** [comment]
Hi @Pushp1403,

I'm not sure how you are seeing the message that you are describing here. There should be no error output like you describe from terraform, though there was a similar debug message internally which was removed from Terraform v0.15, so you may not be using the version you think you are using.

The actual error message of `Error Writing Fields endpoints.0.cert:` must be coming from the provider, since that mapstructure address syntax is no longer used internally in Terraform. 

Since this is not a problem we can solve within Terraform itself, I'm going to close the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
