### ISSUE TITLE
Add default_tags to Module declaration

### ISSUE THREAD

**Issue by bressanmarcos** [hashicorp/terraform#29225]
### Current Terraform Version

```
Terraform v1.0.2
```

### Use-cases
- User can provide `default_tags` for all resources inside a given module, just like we usually do for the `provider` block.

### Attempted Solutions
Simply putting `default_tags` in `provider` block propagates them to all resources in the repository.
It's not a good choice to declare a new provider block per module declaration, just to provide different `default_tags` for each one of them.
I'd rather limit these tags to resources related to a certain module.

### Proposal
Create `default_tags` for `module` blocks, so that all inner resources would also be tagged with the same base tags.

### Related issues
#2283 asks for `default_tags` feature. This appears to have been implemented in the `provider` block.

**Comment by jbardin** [comment]
Hi @bressanmarcos,

Thanks for filing the issue, and the additional use case. Due to the fact that resources and providers do not universally implement "tags" in the same manner, or in many cases, do not have a concept of tags at all; having a dedicated feature for that in the module implementation seems misplaced. This matches the conclusion in #2283, and the reason it was closed.

The use case of defining different provider tags per module would likely handled by the solution to #19932 and #24476. Having a more dynamic method for declaring multiple provider configurations, and passing them to different modules or different instances of a module would essentially allow the same behavior. Since setting different tags for a provider configuration is really no different than any other aspect of the configuration, it would fit in well with the ability to easily configure and handle multiple provider instances.

Since this  feature as described is not something we are likely to implement in terraform, I'm going to close the issue out. We will however keep the use case in mind for future development of the linked enhancement requests.

Thanks!
