### ISSUE TITLE
Issues with terraform commands

### ISSUE THREAD

**Issue by purohitchandra** [hashicorp/terraform#29221]
Hi All,

I am facing issues while running terraform commands on my Mac machine. The commands are taking long time to show results. Also, .tf file is just creation an ec2 instance in AWS, not sure why the commands are taking long time to run. 

For instance, "Terraform plan" is taking more than 20 mins to run. Please suggest how can I fix this issue.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
