### ISSUE TITLE
Terraform init - Does not download plugin

### ISSUE THREAD

**Issue by GioSebis** [hashicorp/terraform#29236]
Hi there,

I just started using Terraform and I am trying to import my Azure resources into Terraform.

But I have a problem and I hope you can help me.

I run code `terraform init` to download plugin for provider (Azure) and I get a success massage. However no plugin is downloaded and no **.terraform**  is created.

My code:
```
provider "azurerm" {
    version = "~>2.0"
    features {}
}

```

Terminal
```
PS C:\Terraform> terraform init

Initializing the backend…

Initializing provider plugins…

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running “terraform plan” to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

```
I am very grateful for any advice = ))

**Comment by jbardin** [comment]
Hello @GioSebis,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
