### ISSUE TITLE
Add support for timezone conversions

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/terraform#29243]
### Current Terraform Version
```
Terraform v1.0.0
on darwin_amd64
```

### Use-cases

Allow for timezone conversions. Most commonly I am interested in local => UTC and back. This is useful for returning expiry information in outputs.

It is also useful for scheduling tasks to occur at "3am" where this could be in another region of the world. Such as I need event X to occur at 2 am in TZ over-there. TF currently has no way to really accomplish this.

### Attempted Solutions

Attempt 1: I had hoped that be specifying `Z` in my `formatdate()`, it would be interpreted as the actual timezone to be used. It's just a placeholder for timezone information. I realized my error on a closer read of the docs.

```
> formatdate("YYYY-MM-DD'T'hh:mm:ssZ", "2021-07-26T10:30:00-05:00")
"2021-07-26T10:30:00-05:00"
```

Attempt 2: Do the math. It is possible to construct a chained formatdate, regex, replace, timeadd, replace sequence to convert a timestamp to UTC. It's ... pretty awful though. Would not recommend.
```
locals {
  run_at = "2021-07-26T12:01:00-05:00"
  # yuck timezone converter
  # "2021-06-26T09:40:00-05:00" => "-05:00"
  tz = formatdate("ZZZZZ", local.run_at)
  # Convert TZ (hh:mm) to a time duration we can pass to timeadd and also flipping the sign
  # ex. +06:30 => -06h30m
  # ex. -06:30 => +06h30m
  # the join/split is a work-around because `$1h$2m` gets parsed incorrectly by TF as `${1h}${2m}`
  tz_dur = join("", split(" ", replace(local.tz, "/^(?:-|\\+)(\\d+):(\\d+)$/", regex("^-", local.tz) == "-" ? "+ $1 h $2 m" : "- $1 h $2 m")))
  # do the TZ math (note the incorrect TZ data at the end)
  # ex. "2021-06-26T09:40:00-05:00" + "+05h00m" => "2021-06-26T14:40:00-05:00"
  time_with_false_tz = timeadd(local.run_at, local.tz_dur)
  # Now replace the bad TZ token with the correct UTC value
  # ex. "2021-06-26T14:40:00-05:00" => "2021-06-26T14:40:00Z"
  run_at_z           = replace(local.time_with_false_tz, local.tz, "Z")
}
```

### Proposal

**Add an optional `tz` argument to format date.**
**Upside**: Avoids need for a new function.
**Downside**: could be interpreted as a this-is-the-timezone-the-given-date-is-in, which would be an unclear behavior.
```
> formatdate("YYYY-MM-DD'T'hh:mm:ssZ", "2021-07-26T10:30:00-05:00", "UTC")
"2021-07-26T15:30:00Z"
```

**New function to do TZ conversions** (preferred)
**Upside**: Intent is communicated better.
**Downside**: Yet another function.
```
> timezone("2021-07-26T10:30:00-05:00", "UTC")
"2021-07-26T15:30:00Z"
> timezone("2021-07-26T15:30:00Z", "local")  # my computer is currently in CDT
"2021-07-26T10:30:00-05:00"
> timezone("2021-07-26T15:30:00Z", "0600")
"2021-07-26T09:30:00-06:00"
```

### References

None that I'm aware of.

**Comment by apparentlymart** [comment]
Hi @dekimsey! Thanks for sharing this use-case.

Terraform intentionally works only with UTC because timezone calculations require access to a database of timezone information, which we'd then either need to distribute along with Terraform (which would mean you'd need to upgrade Terraform each time the timezone rules change) or somehow read from the current system, which is difficult to do in a portable way across various platforms.

(Note that timezones are in many ways a _political_ concept rather than a _technical_ concept, and so there's not a systematic way to implement them entirely as an algorithm: we always need to refer to a data source to know what each timezone represents, what daylight savings rules each location uses, and a few other little inconvenient oddities.)

My instinct then is to say that this is not really a practical thing for Terraform itself to support, but that it could be a good candidate for an external provider plugin to handle. A provider plugin is versioned independently from Terraform itself, and so it could potentially have timezone data bundled inside of it and make a new release each time the the database changes. Because that provider would be independent of Terraform CLI and all of the other providers you use, you could then upgrade that provider alone and be confident that there won't be any other unrelated behavior changes.

Implementing a function like this as a data source does admittedly make the usage more "clunky":

```hcl
data "timezone_conversion" "example" {
  input     = "2021-07-26T10:30:00Z"
  timezone  = "CDT"
}

output "timestamp" {
  value = data.timezone_conversion.example.result
}
```

We are still considering ways to allow providers to extend Terraform with additional functions, but that's not a near-term priority and so I'd suggest using a data source in order to get this result in the meantime.

If you'd be interested in developing such a provider yourself, you could refer to [the Provider Development documentation](https://www.terraform.io/docs/extend/) to see how it works. For a local-compute-only provider like this it might be helpful also to refer to one of the other simpler data-only providers, such as [`hashicorp/http`](https://github.com/hashicorp/terraform-provider-http), to use as a potential skeleton for a provider that contains only a single data source.


Note that a design that just picks up your _current system's_ local timezone automatically is likely to be problematic if you work on a team with people in various different timezones, because each different system where you run Terraform will think it needs to update the root module output value to a different timezone even though the underlying timestamp hasn't changed. Therefore if converting the timestamp to your local timezone is your main use-case, I might also suggest considering making that conversion outside of Terraform, e.g. by feeding the result of `terraform output -raw timestamp` (containing a UTC timestamp) into another program that can convert it for display while keeping the stored value canonical. For example, on a Unix-style system: `date -d "$(terraform output -raw timestamp)"`. (Output values are designed more for machine consumption than human consumption, though indeed the fact that Terraform prints out the root output values as part of the plan does make them sometimes helpful for human review too.)

The main Terraform language is intentionally limited only to UTC and to machine-readable timestamps and the complexity of adding timezone support is too high for something that isn't really a core part of Terraform's scope, and so I'm going to close this issue. Thanks again for sharing this!

**Comment by dekimsey** [comment]
@apparentlymart thank you for taking the time to write up your reasoning. I really appreciate it.

The observation regarding outputs and the local timezone was a definite, "well duh" moment for me. I forgot about the impact of such an output on my colleagues! :(

I was unaware the tz data wasn't readily accessible on Windows . I agree a provider & data source is probably the way to do this to decouple tz database changes from Terraform.  The most common use-case for us is definitely going to be as a region-specific scheduling tool. Right now, performing those calculations is messy and error-prone. A data lookup isn't too terribly for a clunky experience and is a perfectly reasonable option.

Again, thank you for the insight and feedback!
