### ISSUE TITLE
"terraform init" crashes with Swift backend

### ISSUE THREAD

**Issue by sfuml** [hashicorp/terraform#29242]
### Terraform Version
```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.24.6
```

### Terraform Configuration Files
All secrets are removed, but it does not matter whether real or dummy values are used. The initialization crashes in both cases with the same message.

```terraform
terraform {
  required_version = ">= 0.13"
  required_providers {
    opentelekomcloud = {
      source = "opentelekomcloud/opentelekomcloud"
    }
  }
}

provider "opentelekomcloud" {
  access_key  = "<ACCESS KEY>"
  secret_key  = "<SECRET KEY>"
  domain_name = "<DOMAIN NAME>"
  tenant_name = "<TENANT NAME>"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
}

terraform {
  backend "swift" {
    auth_url       = "https://swift.eu-de.otc.t-systems.com/v1"
    container      = "swift-test-terraform-state"
    user_name      = "<my_user_name<"
    password       = "<my_password>"
    user_domain_id = "<my_user_domain_id>"    
    swauth         = true
  }
}
```

### Debug Output
Debug output is the same as the crash output in the following section.

### Crash Output
Content of crash output file: https://gist.github.com/sfuml/57f4a7ef69d9559dacdf87660f5b4cf2#file-gistfile1-txt

### Expected Behavior
When executing `terraform init`, terraform should successfully initialize. 

### Actual Behavior
Terraform crashes.

### Steps to Reproduce

During executing of `terraform init`, terraform crashes.

### Additional Context

Using opentelekomcloud provider but besides this, no atypical steps are performed.

### References
I'm not aware of any existing GitHub issues.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the Swift backend in Terraform v1.3 because it hasn't had a dedicated maintainer for a few versions now and so it was becoming problematic to keep working in newer Terraform versions. Since that backend is no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using this backend with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
