### ISSUE TITLE
EFS restore using terraform

### ISSUE THREAD

**Issue by arunlalsreesylam** [hashicorp/terraform#29259]
Is there any option to restore an EFS volume from the AWS backup using terraform?

**Comment by apparentlymart** [comment]
Hi @arunlalsreesylam!

This seems like a question about the AWS provider rather than about Terraform Core. We use issues in this repository only to track bugs and feature requests for the main (provider-agnostic) Terraform runtime.

I'd suggest asking this question in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), where there is a number of other AWS provider users who can hopefully give information about how they've addressed similar problems. Thanks!
