### ISSUE TITLE
Upload failed with file provisioner

### ISSUE THREAD

**Issue by Madhusudhan-Yerragudi** [hashicorp/terraform#29256]
I am using Terraform v0.15.5 and am getting the below error intermittently. Can some one please look into this and address it.

Code:

```hcl
resource "null_resource" "create_ssh_opc" {
  count      = "${var.windows_instance_count}"
  depends_on = [null_resource.execute_upgrade]
  provisioner "file" {
    connection {
      type     = "winrm"
      timeout = "5m"
      host     = "${var.windows_instance_ip[0]}"
      user     = "opc"
      password = "${var.win_random_password}"
      port     = "5986"
      https    = "true"
      insecure = "true"
    }
    source      = "${var.terraform_directory}/oci_pub_key"
    destination = "C:\\Users\\opc\\.ssh\\authorized_keys"
  }
}
```

Error:

```
│ Error: file provisioner error
│
│   with null_resource.create_ssh_opc[2],
│   on compute_oci.tf line 309, in resource "null_resource" "create_ssh_opc":
│  309:   provisioner "file" {
│
│ Upload failed: Error restoring file from
│ $env:TEMP\winrmcp-9401c342-63a7-4268-7361-e20c372cc345.tmp to
│ C:\Users\opc\.ssh\authorized_keys: restore operation returned code=1`
```

**Comment by apparentlymart** [comment]
Hi @Madhusudhan-Yerragudi! Sorry for this strange error, and thanks for reporting it.

I've not seen this error before so I don't have any quick answer for what it means or how to recover from it, but from some initial research I was able to learn that this error message [comes from the upstream `winrmcp` library that Terraform depends on for WinRM support](https://github.com/packer-community/winrmcp/blob/c76d91c1e7db27b0868c5d09e292bb540616c9a2/winrmcp/cp.go#L35-L38).

It looks like you deleted the issue template rather than including all of the information it requested, and it seems unlikely that we'll be able to reproduce this problem directly because it probably depends on some details of your system in particular, so in order to make some progress here it'd be helpful if you could reproduce the problem with the following two environment variables set:

```
TF_LOG=trace
WINRMCP_DEBUG=1
```

...and then share the resulting verbose logs as a [GitHub Gist](https://gist.github.com/) so that we can see more details details about what happened here.

Alternatively, if you're familiar with PowerShell then it might help to [review the PowerShell code that this "restore" operation is running](https://github.com/packer-community/winrmcp/blob/c76d91c1e7db27b0868c5d09e292bb540616c9a2/winrmcp/cp.go#L117-L148) to see if you can see anything it's doing that seems likely to fail on your specific system, if e.g. the destination path doesn't exist, or the Terraform process doesn't have appropriate permissions to write there, or similar.

Thanks!

**Comment by crw** [comment]
Hi @Madhusudhan-Yerragudi, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
