### ISSUE TITLE
CLI `apply` command does not show replace option

### ISSUE THREAD

**Issue by sshastri** [hashicorp/terraform#29268]
The docs don't specify the -replace option. The Terraform CLI client does not show the -replace option in the help menu either.

https://www.terraform.io/docs/cli/commands/apply.html

**Comment by apparentlymart** [comment]
I'm assuming that this issue was referring to the case of running `terraform apply` in the [Automatic Plan Mode](https://developer.hashicorp.com/terraform/cli/commands/apply#automatic-plan-mode), where it acts as if `terraform plan` and `terraform apply` were both run in sequence with the generated plan only existing temporarily in memory.

The commentary about that in the docs at the time I'm writing this comment says:

> When you run `terraform apply` without passing a saved plan file, Terraform automatically creates a new execution plan as if you had run `terraform plan`, prompts you to approve that plan, and takes the indicated actions. You can use all of the [planning modes](https://developer.hashicorp.com/terraform/cli/commands/plan#planning-modes) and [planning options](https://developer.hashicorp.com/terraform/cli/commands/plan#planning-options) to customize how Terraform will create the plan.

The final link in that quote is to [Planning Options](https://developer.hashicorp.com/terraform/cli/commands/plan#planning-options), where the `-replace=ADDRESS` option is discussed.

Those interactions are reinforced again under [Plan Options](https://developer.hashicorp.com/terraform/cli/commands/apply#plan-options) on the `terraform apply` documentation page.

There's a lot of content under both "Planning Modes" and "Planning Options" which I think would overwhelm the page about `terraform apply` if duplicated there too. However, I wonder if we could compromise in a similar way to how the "Plan Options" section currently mentions `-destroy` and `-refresh-only` in its "Planning Modes" list item, by identifying a small number of the most commonly-used planning options and mentioning their names in the paragraph associated with "Planning Options" so that at least a _Find in Page_ for the string `-replace` would match that paragraph and help the reader learn that they ought to be reading the `terraform plan` documentation instead.
