### ISSUE TITLE
TF_DATA_DIR not working with -chdir param

### ISSUE THREAD

**Issue by alexguevara** [hashicorp/terraform#29287]
### Description
While working with terraform I would like to initialize it only once in a 'parent' directory and read .tf config files / write .tfplan files in nested folders respectively as [stated in the docs](https://www.terraform.io/docs/cli/commands/plan.html#passing-a-different-configuration-directory).
However `-chdir=` param seems to ignore `TF_DATA_DIR` variable and fails with:  `Error: Could not load plugin`

### Terraform Version
```
Terraform v1.0.3
on windows_amd64
```

### Expected Behavior
Execute plan in custom root dir

### Actual Behavior
![image](https://user-images.githubusercontent.com/7500019/127922651-3916fec0-4d11-4dab-acd7-ae51e3505b3f.png)

### Steps to Reproduce

1. `TF_DATA_DIR="C:/Dev/Projects/Terraform/.terraform" ./terraform init`
2. `TF_DATA_DIR="C:/Dev/Projects/Terraform/.terraform" ./terraform -chdir="./nested_dir" plan -out="./out.tfplan"`

**Comment by jbardin** [comment]
Hi @alexguevara,

It appears you forgot the `-chdir` option in the `init` command as well, meaning the `init` and `plan` are using different configurations, and hence the proper initialization could not be done. Testing this situation using the same `-chdir` option in both cases works correctly.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
