### ISSUE TITLE
Terraform Plan failure on upgrading terraform version from v0.12.31 to v0.13.7

### ISSUE THREAD

**Issue by Abhishek-Singh-svg** [hashicorp/terraform#29309]
### Terraform Version

```
Terraform v0.13.7

```

### Terraform Configuration Files

```
resource "newrelic_alert_policy_channel" "alert_policy_additional_channel_binding" {
  count       = local.additional_channels == true ? length(local.policy_id_by_policy_names) : 0
  policy_id   = local.policy_id_by_policy_names[keys(local.policy_id_by_policy_names)[count.index]]
  channel_ids = data.newrelic_alert_channel.email_alert_channels.*.id
}
```

### Debug Output

```
Error: Invalid count argument

  on .terraform/modules/alert_policies/newrelic/policies/policies.tf line 58, in resource "newrelic_alert_policy_channel" "alert_policy_additional_channel_binding":
  58:   count       = local.additional_channels == true ? length(local.policy_id_by_policy_names) : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Expected Behavior
I am upgrading terraform version from `0.12.31` to `0.13.7` and have made all the required changes for v0.13.7 (explicitly defined source for provider location, ran` terraform state replace-provider` command for changing the reference location of providers in terraform state file stored in s3 backend).
Ideally it should run smoothly `terraform plan`, `terraform apply`, `terraform destroy`.

### Actual Behavior
After making the changes, on running `terraform plan` and `terraform apply` for the first time it is going smooth and creating resources successfully but from the **second** execution it starts failing (for terraform plan) while refreshing the resources and throwing the above error. I am not able to destroy the resources as well which got created, since terraform destroy also refreshes the state file.
Not able to run terraform  plan, apply, refresh and destroy.

### Steps to Reproduce
1. Create resource with terraform v0.12.31 where configuration should be similar like the above given in which `count` is being used.
2. Create the same resource with terraform v0.13.7 (you will have to run ` terraform state replace-provider` command before switching to v0.13 from v0.12 as per the [documentation](https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers)
3. After getting created the resources with terraform v0.13.7, run terraform plan or terraform destroy it will reproduce the given error.

### Additional Context
I am using the below providers:

1.  New Relic - v2.19.1
2.  local - v2.1.0
3.  external - v2.1.0 
And s3 configuration for storing the state files.

**Comment by jbardin** [comment]
Hi @Abhishek-Singh-svg,

Without a complete example it's hard to say what in your configuration could be causing the count expression to be unknown. If it is a bug in Terraform, it's likely solved in later releases, as we have not had any related issues with valid configurations. Since there is no longer any development happening on releases before v1.0, even if this were caused by a Terraform bug, the only resolution is to continue the upgrade process to get to a current release.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
