### ISSUE TITLE
The "for_each" value depends on resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by eddadjei** [hashicorp/terraform#29325]
My job is pretty much on the line introducing terraform to my company. below is a snippet of code causing a problem. As you can tell the value of **module.core_setup.main_project_id** is only know at the time of module execution. This use to work until I upgraded to 1.0.4. I am not stuck and can't do anything.

module "gcr_sa" {
  source       = "terraform-google-modules/service-accounts/google"
  version      = "~> 3.0"
  project_id   = module.core_setup.main_project_id
  display_name = "Publisher"
  names        = ["ap-publisher"]
  project_roles = [
    "${module.core_setup.main_project_id}=>roles/storage.admin"
  ]
  depends_on = [
    module.core_setup
  ]
}`
`

**Comment by jbardin** [comment]
Hi @eddadjei,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. 

To get you started here, the one likely problem is the use of `depends_on` in a module, which is almost never what you want to do. This forces every object within the module to depend on the targets, and if there are any data source involved they will cannot be read during planning if their dependencies have changes.

Also, if `project_roles` is used as the key values in a `for_each` expression, it cannot contain unknown values computed by a resource. Terraform cannot control how this value will be used, and it is up to the module authors to determine how the resources within the module are structured. If this was working previously from the first apply, it more likely caused by a change in the module version.

Thanks!

**Comment by eddadjei** [comment]
Turn's out there are some resources that need to be created ahead of executing terraform and not all resources can be fully automated as some modules may make it seem like it's possible.
