### ISSUE TITLE
Module A output fed into module B input recognising dependency/order of events

### ISSUE THREAD

**Issue by originality2** [hashicorp/terraform#29326]
### Context
The issue around this one is when I use modules instead of resources to create pagerduty_escalation_policy and pagerduty_service resources, there is an issue of order of operations that doesn't exist when I just use resources. Specifically, if I try to change the escalation policy associated with a service and delete former escalation policy, Terraform fails to recognise when they are packaged in modules that the pagerduty_service resource needs to be altered before the pagerduty_escalation_policy resource can be deleted, causing an error.

### Terraform Version
0.15.5

### Terraform Configuration Files

```terraform
-- main.tf

module "escalation_policies" {
  source    = "./modules/escalation"
  for_each  = local.escalation_policies
  ...
}

module "services" {
  source   = "./modules/service"
  for_each = local.services

  ...
  escalation_policy_name = module.escalation_policies[each.value.escalation_policy].esc_name
  ...
}

...
-- escalation module
resource "pagerduty_escalation_policy" "this" {
 ...
}

output "esc_id" {
  value = pagerduty_escalation_policy.this.id
}

-- service module 
resource "pagerduty_service" "this" {
  ...
  escalation_policy       = var.escalation_policy_id
}
```

### Crash Output

First there is just a hang on destroying the escalation policy module without trying to modify the service module

```
module.escalation_policies["xxx"].pagerduty_escalation_policy.this: Destroying... [id=XXXX]
module.escalation_policies["xxx"].pagerduty_escalation_policy.this: Still destroying... [id=XXXX, 10s elapsed]
module.escalation_policies["xxx"].pagerduty_escalation_policy.this: Still destroying... [id=XXXX, 20s elapsed]
module.escalation_policies["xxx"].pagerduty_escalation_policy.this: Still destroying...
```

Then there is an error because the escalation policy still has a service associated to it (as the other module has failed to modify)

```Error: DELETE API call to https://api.pagerduty.com/escalation_policies/PAT8AK8 failed 400 Bad Request. Code: 2001, Errors: [Can't delete an escalation policy that contains services.], Message: Invalid Input Provided```

### Expected Behavior
Similar to if they were just resources without being packaged into modules, I believe that the modifying of services and the attempt to delete the escalation policy should happen at the same time. e.g. if my resources are just 

*before*
```
resource "pagerduty_escalation_policy" "this" {
 ...
}

resource "pagerduty_escalation_policy" "that" {
 ...
}

resource "pagerduty_service" "this" {
  ...
  escalation_policy       = pagerduty_escalation_policy.this.id
}
```

*after*
```
resource "pagerduty_escalation_policy" "that" {
 ...
}

resource "pagerduty_service" "this" {
  ...
  escalation_policy       = pagerduty_escalation_policy.that.id
}
```

Then the behaviour is as expected
```
pagerduty_escalation_policy.this: Destroying... [id=XXXXX]
pagerduty_escalation_policy.that: Modifying... [id=YYYYY]
pagerduty_escalation_policy.that: Modifications complete after 1s [id=YYYYY]
pagerduty_service.this: Modifying... [id=ZZZZZ]
pagerduty_service.this: Modifications complete after 0s [id=ZZZZZ]
pagerduty_escalation_policy.first: Destruction complete after 2s
```
### Actual Behavior
see Crash Output Above

### Steps to Reproduce
If you were going to reproduce you'd need to 
1. Create two modules, one that takes in a list of pagerduty escalation policies, one that takes in a list of pagerduty services. The service module needs the escalation policy id, which is output from the escalation policy module 
2. Apply a version of config that creates two escalation policies and one service, which is mapped to escalation policy A
3. re-apply the config, but change the service to map to escalation policy B and delete escalation policy A in the same config change.

### References
I can provide a more in depth module config on request, but it is linked in an enterprise github and so I have just cut it down to bare bones for readibility's sake.

**Comment by jbardin** [comment]
Hi @originality2,

Thanks for filing the issue. In order to assist here, you will need to include some of the details about the modules themselves, as the module declarations alone are not enough to determine the structure within the modules. I would also note that modules do not change the dependency handling of resources, so separating a valid configuration of resources into modules does not change how the dependencies are handled between those resources. The most common mistake is when a resource is registered within another, and replacement requires `create_before_destroy` is used to ensure the correct order of operations. 

Thanks!

**Comment by originality2** [comment]
Thanks @jbardin,

What other info from the modules do you need? I have put above what I think are the relevant content of the modules (under `escalation module` and `service module`, the resources and outputs are listed). Is there more you need?

Regarding the dependencies - it is kind of cyclic in nature which is causing the issue, but I do note that when they are just the resources and not packaged into modules, terraform handles it. The pagerduty service has a dependency on the escalation policy, as the attached escalation policy is defined in the service. However, the escalation policy can not be deleted if any service has an attachment to it. So in the case where I change the service to a different escalation policy and in the same configuration remove the first escalation policy, I'd like the the order of operations to be

1. The service updates to attach to the new escalation policy
2. The old escalation policy now deletes successfully.


Unfortunately, because of the dependency, I believe it instead attempts to make changes to the escalation policy first, which can't be deleted until the service has detached itself from it.

Which makes sense - but my issue is that Terraform handles this kind of cyclic dependency when I test without modules. The same functionality packed into two separate modules (feeling the escalation policy id output out of the escalation module and into the service module) is what is causing the issue, as far as I can see.

**Comment by jbardin** [comment]
I'm not sure exactly what I need, short of a reproducible example of both cases. If the changes being done to the modules are equivalent to example with the standalone resources, then what I find surprising is that the standalone resources would work in the first place. 

If we take the standalone resource example, the order of operations when moving from the first to the second configuration should be:

1. delete `pagerduty_escalation_policy.this` because it is no longer in the configuration.
2. update `pagerduty_service.this` with the new `escalation_policy` value.

The error indicates that a `pagerduty_escalation_policy` cannot be deleted if it is associated with a service, so I would expect this order of operations to fail in the same manner. We can confirm the order of operations as they are reflected in the CLI output as well. I do see that there is a modification planned for the other policy, is that somehow related to the changes taking place here? If you have a minimal reproduction you can run yourself, block of trace log output after the final `TransitiveReductionTransformer` line during apply will show all the expected order of operations, and we can look for any functional differences between the two configurations.

Troubleshooting this further however may not be needed, as the order you are expected is not what the configuration declares. If you explicitly want terraform to update the service before deleting the old policy, then you must use `create_before_destroy` to invert the default ordering of resources, which will force the service to be updated with the new value before attempting to delete the old policy.

**Comment by jbardin** [comment]
Since we have no reproduction case and have not heard back in a while I'm going to close the this issue. If you have more information, feel free to post it here and we can re-evaluate the issue, or file a new one with the requested information. The behavior described sounds correct, and it the likely cause is either a provider issue, or a lack of `create_before_destroy` where it is required.
