### ISSUE TITLE
List of maps breaking conditional

### ISSUE THREAD

**Issue by kylet21** [hashicorp/terraform#29332]
### Terraform Version

```
v1.0.4
```

### Terraform Configuration Files

```terraform
  processed_nginx = merge(local.container_defaults, local.nginx_container_definition)
  processed_firelens = merge(local.container_defaults, local.firelens_container_definition)
  default_containers = var.logging_method == "firelens" ? [local.processed_nginx, local.processed_firelens] : [local.processed_nginx]
```

### Expected Behavior

Successful plan/apply

### Actual Behavior

```
╷
│ Error: Inconsistent conditional result types
│
│   on ../service.tf line 94, in locals:
│   94:   default_containers = var.logging_method == "firelens" ? [local.processed_nginx, local.processed_firelens] : [local.processed_nginx]
│     ├────────────────
│     │ local.processed_firelens is object with 6 attributes
│     │ local.processed_nginx is object with 8 attributes
│     │ var.logging_method will be known only after apply
│
│ The true and false result expressions must have consistent types. The given expressions are tuple and tuple, respectively.
```

### Steps to Reproduce

`terraform plan`

### Additional Context

The two local variables `processed_firelens` and `processed_nginx` contain maps with (possible) different keys. The container definition takes a list of maps. I would expect the conditional not to care about different values inside of the lists. This also worked before when the `list()` function was supported, i.e.,: 
```
default_containers = var.logging_method == "firelens" ? list(local.processed_nginx, local.processed_firelens) : list(local.processed_nginx)
```

**Comment by jbardin** [comment]
Hi @kylet21,

Sorry about the confusion here, the error message is not very helpful, and we are tracking that in a few places like #29226.

As for the actual problem, a `list` alone is not a complete type. A list is a value containing a single element type, `list(string)`, `list(number), `list(map(string))`, etc. A `tuple` is also not a distinct type, but is a container that has a fixed number of possibly heterogeneous element types. Because `local.processed_nginx` and `local.processed_firelens` appear to have have different incompatible object types. Terraform cannot determine a single type for `default_containers`. 

You mentioned that the deprecated `list` function was working, and if that is still the case the `tolist` conversion function may produce the same output. I have a feeling however that the type checking is still going to fail because of the incompatible object types.  Because terraform needs to know what type to expect from `default_containers`, I suggest making sure that the result can be of a single known type based on the inputs provided.

Since we are already tracking the possibility of enhancing the error messages in this case, I'm going to close the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. Feel free to reply here though if you have any further questions about the given example.

Thanks!
