### ISSUE TITLE
Setting TF_DATA_DIR  makes terraform fail to find AWS default credentials in ~/.aws`

### ISSUE THREAD

**Issue by lamba92** [hashicorp/terraform#29352]
```
Terraform v1.0.3 on windows_amd64
```

Setting `TF_DATA_DIR`  makes terraform fail to find AWS default credentials in `~/.aws`. Setting manually `AWS_SHARED_CREDENTIALS_FILE` works.

Happens on macOs x64, Windows x64 and Linux x64

**Comment by jbardin** [comment]
Hi @lamba92,

Can you create a more complete example demonstrating the issue? The `TF_DATA_DIR` setting is used by terraform, but the shared credential file is picked up automatically by the AWS SDK, so I don't see how they could be related. Are you certain this is running under the same user account? The trace logs from the failed command may offer some insight here too.

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to post them here or open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
