### ISSUE TITLE
`terraform add -from-state` should honor `-optional`

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#29367]
### Current Terraform Version

```
Terraform v1.1.0-dev
```

### Use-cases

The `terraform add -from-state` currently doesn't honor the `optional` option, which means both the `Required` and `Optional` properties are output. This can cause issues that some default value of those optional properties can't pass the validation rule as defined in the provide, making the output config useless.

### Proposal

Honor the `-optional` when `-from-state` is on.

**Comment by jbardin** [comment]
Thanks @magodo,

While defaulting to `-optional=true` in `-from-state` was likely intentional, as in practice there are probably few cases where a usable config is generated only from the required fields, I'll do want to check on changing that for consistency sake before releasing the feature.

Do you have an example though of where the default values cannot pass the provider's own validation? With any sufficiently complex configuration it's very unlikely to generate a config that does not require some manual modification, but the goal here is to come as close as possible to give users a starting point.

**Comment by magodo** [comment]
@jbardin I just updated the description to involve the example.
