### ISSUE TITLE
windows vs linux encoding issues

### ISSUE THREAD

**Issue by s4ntos** [hashicorp/terraform#29370]
### Terraform Version

**Windows**
```
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.54.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
```

**LInux**
```
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.54.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
```

### Terraform Configuration Files
```terraform
resource "kubernetes_config_map" "test-windows" {
 metadata {
   name         = "test"
   namespace    = "default"
 }
 data =  {
      template = templatefile("test.yaml",{ test = "this is a test"})
      file = file("test.yaml")
    }
}
```
test.yaml
```
group:
- test
- test2
- ${test}
```

### Debug Output
on windows machine (windows 10)
```
PS C:\Users\dummy> terraform apply
PS C:\Users\dummy> kubectl --kubeconfig .\root-dev get configmaps test -o yaml
apiVersion: v1
data:
  file: "group:\r\n- test\r\n- test2\r\n- ${test}"
  template: "group:\r\n- test\r\n- test2\r\n- this is a test"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-13T15:07:35Z"
  name: test
  namespace: default
  resourceVersion: "36419"
  selfLink: /api/v1/namespaces/default/configmaps/test
  uid: a15bd434-f2df-489d-8ce3-8c8d8f806334
terraform destroy 
```

on linux server
```
$ terraform apply
$ kubectl --kubeconfig root-dev get configmaps test -o yaml
apiVersion: v1
data:
  file: |
    group:
    - test
    - test2
    - ${test}
  template: |
    group:
    - test
    - test2
    - this is a test
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-13T15:20:44Z"
  name: test
  namespace: default
  resourceVersion: "38601"
  selfLink: /api/v1/namespaces/default/configmaps/test
  uid: cc8a3529-fc7a-4720-9178-d16769e2ba10
```

### Expected Behavior
The encoding on the kubernetes should be the same regarless of system where terraform is being executed

### Actual Behavior
windows encoding shows \n\r character as string in linux everything seems OK

### Steps to Reproduce
terraform apply
kubectl get configmap test -o yaml

**Comment by jbardin** [comment]
Hi @s4ntos,

The encoding of the data here is not changed by Terraform, it taking the file contents and sending them to the kubernetes provider. A common problem is having git configured to automatically change the newline characters on windows, which would cause the apparent change in data here. 

Since Windows line endings are technically valid in YAML (though I'm not sure how mixed line endings are supposed to be interpreted), it may be possible for the provider to handle this case, though they may delegate the interpretation of the data to the kubernetes service itself.

Can you confirm which line ending characters are actually present in the file being read on the Windows machine?

**Comment by s4ntos** [comment]
I'm using VSCode and by changing the end of line sequence from CRLF to LF it does change it and everything is then inserted correctly.  Still a bit strange because it adds to kubernetes as a string. 

I will enable this by default on by VSCode so that it doesn't happen.

And closing this ticket with the solution on VSCode by setting the following setting to true.
"files.trimFinalNewlines": true
