### ISSUE TITLE
It would be nice to get resource argument that `ForceNew` using `configs/configschema`

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform#29375]
### Current Terraform Version

```
Terraform 1.0.4
```

### Use-cases

If we can get access to `ForceNew` using [`configschema`](https://github.com/hashicorp/terraform/tree/main/internal/configs/configschema), then we can figure out before hand which arguments would cause a recreation before we do a terraform plan.

### Attempted Solutions

We could scrape certain resources e.g.

1. Identify a resource or data source
2. Download the raw version of the resource e.g. https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_s3_bucket.go
3. Scrape for `ForceNew`
4. Identify what inputs require a recreation

```shell
$ curl -s https://raw.githubusercontent.com/hashicorp/terraform-provider-aws/main/aws/resource_aws_s3_bucket.go | grep ForceNew -B10 | grep -P '"([a-zA-Z-_]+": {)|(ForceNew)' | sed 's/^\t*//g'

"bucket": {
ForceNew:      true,
"bucket_prefix": {
ForceNew:      true,
"object_lock_configuration": {
"object_lock_enabled": {
ForceNew:     true,
```

### References

* https://github.com/minamijoyo/tfschema/issues/34

**Comment by jbardin** [comment]
Hi @nitrocode,

The `ForceNew` option is a feature of the SDK, which is a shortcut for triggering replacement when a single attribute is changed. The plugin schema protocol does not contain this information, and whether replacement is actually triggered or not is determined by the provider during `PlanResourceChange`. 

On the provider side, `ForceNew` is simply a convenience method for triggering replacement in the common case, but planning replacement can still be triggered or suppressed either way regardless of the `ForceNew` setting. Since there would be no way to correctly determine the plan results from this information, it is not exposed to Terraform core. Once the provider has returned the plan for a resource instance, the reason for replacement is saved in the plan itself.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
