### ISSUE TITLE
Terraform destroys then recreate instead recreate then destroy to prevent downtime

### ISSUE THREAD

**Issue by Abhi8968** [hashicorp/terraform#29423]
Hi team,

I am using terraform to create Codepipeline and various other resources on AWS, but once an autoscaling group is created and if I want to change the launch configuration in terraform spec file then after running terraform apply it starts deleting the launch configuration and fails. To sort it, I used depends on tag but it is deleting the autoscaling group which is creating downtime for end-user.

Instead of following destroy and create, how can we switch it to create and destroy to prevent downtime

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

The option you are looking for is [`create_before_destroy`](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#create_before_destroy) in the `lifecycle` meta-argument. 

Thanks!
