### ISSUE TITLE
cannot ignore_changes in kubernetes_manifest

### ISSUE THREAD

**Issue by villesau** [hashicorp/terraform#29443]
### Terraform Version

```
v1.0.3
```

### Terraform Configuration Files

```terraform

resource "kubernetes_manifest" "secrets" {
  manifest = {
    apiVersion = "onepassword.com/v1"
    kind       = "OnePasswordItem"
    metadata = {
      name = "secrets"
      namespace = kubernetes_namespace.ns.metadata[0].name
    }
    spec = {
      itemPath = "path-to-secrets"
    }
  }
}
```

### Expected Behavior
Setting

```
  lifecycle {
    ignore_changes = [object.metadata.finalizers]
  }
```
should ignore changes to that specific property.

### Actual Behavior

It still complains about the drift.

### Steps to Reproduce

1. have above config
2. `terraform init`
3. run `terraform apply`
4. the apply succeeds
5. run `terraform plan`
6. I get following error:

```
  # module.gke.kubernetes_manifest.secrets will be updated in-place
  ~ resource "kubernetes_manifest" "secrets" {
      ~ object   = {
          ~ metadata   = {
              - finalizers = [
                  - "onepassword.com/finalizer.secret",
                ] -> null
                # (2 unchanged elements hidden)
            }
            # (3 unchanged elements hidden)
        }
        # (1 unchanged attribute hidden)
    }

```
7. set 

```
  lifecycle {
    ignore_changes = [object.metadata.finalizers]
  }
```
8. run `terraform plan`
9. the same error still appears

### Additional Context
The resulting state from original apply looks following:

```
{
  "manifest" = {
    "apiVersion" = "onepassword.com/v1"
    "kind" = "OnePasswordItem"
    "metadata" = {
      "name" = "secrets"
      "namespace" = "namespace"
    }
    "spec" = {
      "itemPath" = "path-to-secrets"
    }
  }
  "object" = {
    "apiVersion" = "onepassword.com/v1"
    "kind" = "OnePasswordItem"
    "metadata" = {
      "name" = "secrets"
      "namespace" = "namespace"
    }
    "spec" = {
      "itemPath" = "path-to-secrets"
    }
  }
  "wait_for" = null /* object */
}
```

### References

The example uses 1password operator: https://github.com/1Password/onepassword-operator

**Comment by apparentlymart** [comment]
Hi @villesau,

I'm not familiar with all of the details of this particular provider but based just on the example you shared I notice an inconsistency between the argument you set (`manifest`) and the argument you instructed Terraform to ignore (`object`).

The `ignore_changes` mechanism tells Terraform to handle situations where the configuration differs from the state by retaining what's in the state and ignoring the configuration, and so it only makes sense to use arguments you've set in the configuration as part of `ignore_changes`; otherwise there's no configuration to compare to and thus the option does nothing at all.

I would expect you could get the behavior you were looking for by changing your `ignore_changes` expression to refer to the value you set in the configuration, like this:

```hcl
    ignore_changes = [manifest.metadata.finalizers]
```

...although the details here will depend on how exactly the provider is implemented, so if that doesn't work it might be better to continue discussion over in hashicorp/terraform-provider-kubernetes#1378 for now so that the provider maintainers can describe their intent for how this should work and then we can make a plan from there.

Thanks for reporting this!

**Comment by villesau** [comment]
@apparentlymart yep there indeed is an inconsistency. However, the property that I'd like to ignore is in the `object`, not in the `manifest` since the `object` is which updates and `manifest` doesn't. That's what the error message also complains about. And `ignore_changes = [manifest.metadata.finalizers]` didn't work either.  And yeah, the other repo seems to be more suitable for this.

**Comment by jbardin** [comment]
Closing as there is a relevant issue already open on the kubernetes provider repo.
Thanks!
