### ISSUE TITLE
Cannot build Terraform v1.0.5 due to invalid tencentcloud-sdk-go dependency

### ISSUE THREAD

**Issue by kevinburke** [hashicorp/terraform#29442]
I attempted to check out the source code at tag `v1.0.5` and then run:

```
GO111MODULE=on go install -v ./...
```

When I try this, I get the following error:

```
$ GO111MODULE=on go install -v ./...
go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82
go: downloading github.com/tencentcloud/tencentcloud-sdk-go v3.0.82+incompatible
go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82
```

It seems like this dependency changed their tagging mechanism, or did something to break the reference that Terraform is relying on. See https://github.com/TencentCloud/tencentcloud-sdk-go/issues/125.

Since Terraform no longer vendors the source code it relies on, it's not clear what version of the Tencent dependency I am supposed to be running. Commit b54370584032fbe76a0b74409db1facd736831bf appears to have fixed this issue on tip, though it's not clear that it points at the same commit of the dependency.

As I understand it, 1.0.5 is the most recent stable release of Terraform, not a legacy release, so it seems like a problem that it is no longer possible to build this tag from source code. It would be great if you could release a new version that is possible to build from source.

Note that if you have a cached copy of this dependency locally, you may not be able to reproduce the issue.

Updates cycloidio/inframap#149.
Updates hashicorp/terraform#29021.

**Comment by apparentlymart** [comment]
Hi @kevinburke,

Indeed, the maintainers of this other module have retroactively deleted all of the tags from their repository and switched to using v1 major version tags instead, which has therefore broken all of their downstream dependencies.

As you've seen, we've since switched to referring to the particular commit that the `v3.0.82` tag was previously referring to, which [the developers recorded in a file in their repository](https://github.com/TencentCloud/tencentcloud-sdk-go/blob/6833ca7684bf14d0368330a08aff6705418aef02/commit2tag).

The previously-existing tags are still cached in the official Go module proxy, as we can see by [their documentation still being available](https://pkg.go.dev/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible), and so we're able to still build this tag by using that proxy to obtain the source code. However, I'd expect to see this error if _not_ using the official module proxy, either due to disabling it altogether or by using a different proxy.

We're not planning to make an unscheduled release for this, but v1.0.6 is due next week and will include the updated dependency. Until then, if you need to build from source and can't use the official Go module proxy then an alternative is to locally patch `go.mod` to either use a replace directive for the version currently selected in `main`, or to modify the `require` entry for that dependency directly.

We've not yet seen any response from the maintainers of the upstream repository and so our actions so far have been based on local detective work. Hopefully the upstream maintainers will soon respond and explain what their plan is for this and how they expect downstream dependencies to respond to it.

**Comment by jbardin** [comment]
Hi! The maintainer for that community backend updated the dependencies in #29445, which will be backported to the v1.0 branch.

Thanks!
