### ISSUE TITLE
variable file based on workspace

### ISSUE THREAD

**Issue by robkooper** [hashicorp/terraform#29450]
### Current Terraform Version

```
Terraform v1.0.5
on darwin_amd64

```

### Use-cases

I use a single repository for managing multiple clusters. State is kept in different workspaces. It would be nice if terraform would try to load the input variables from a file based on the workspace name. For example the cluster `prod` would look for a files called `prod.tfvars`.

### Attempted Solutions

I accomplish this using the folllowing command:

```
terraform plan -var-file=$(terraform workspace show).tfvars
```

### Proposal

Adding an additional call for a file to be laoded at https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/command/meta_vars.go#L84. 

proof of concept (first time writing go code):
```
	if workspace, err := m.Workspace(); err == nil && workspace != "default" {
		workspaceVarsFilename :=  workspace + ".tfvars"
		if _, err := os.Stat(workspaceVarsFilename); err == nil {
			moreDiags := m.addVarsFromFile(workspaceVarsFilename, terraform.ValueFromAutoFile, ret)
			diags = diags.Append(moreDiags)
		}
	}
```

**Comment by apparentlymart** [comment]
Hi @robkooper! Thanks for sharing this use-case.

I think here you're describing the same use-case as in #12845, and so I'm going to close this one just to consolidate the discussion.

With that said, at this time we're not planning on adding any new features to the current incarnation of workspaces in Terraform CLI. Instead, we intend to replace that feature with something that better fits the problem of sharing the same configuration across multiple environments.

Our recommendation for today's Terraform is to use a separate configuration for each environment, factoring out the common parts into a shared module which you can then call from each of them. You can then place the variable values that you might otherwise have put in `prod.tfvars` in the `module` block in the configuration for production, along with the backend configuration for that environment, and then switch into that directory to run the Terraform commands without any special options.

If you are beginning to use Terraform for a new system, I would recommend against using workspaces. All of the workspace-related behaviors are explicitly excluded from [the Terraform 1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html) and likely to change significantly in a future Terraform release, once the new design for workspaces is ready.

With that said, #12845 is currently serving to represent the need for the replacement feature to meet the use-case, and _not_ for any addition to the existing (now-frozen) workspace mechanism.

Thanks again for recording this use-case!

**Comment by robkooper** [comment]
Is there a timeline on this rewrite of the workspace? The issue that is linked talks about `env` which is replaced by workspaces.
