### ISSUE TITLE
Terraform doesn't wait for the shell script to complete execution during destroy operation

### ISSUE THREAD

**Issue by ratripathi** [hashicorp/terraform#29465]
### Terraform Version

```
1.0.5
```

### Terraform Configuration Files

```terraform
resource "null_resource" TearDownCluster {
  triggers = {
    ssh_host  = azurerm_network_interface.anic-01.private_ip_address
    ssh_user     = var.admin_username
    ssh_pass       = var.admin_password
  }

  provisioner "remote-exec" {
    when = destroy
    inline = [
      "chmod +x /tmp/config/scripts/tear_down_cluster.sh",
      "/tmp/config/scripts/tear_down_cluster.sh args",
      "sleep 10m",
      "echo COMPLETED"
    ]
  }

  connection {
    host     = "${self.triggers.ssh_host}"
    type     = "ssh"
    user     = "${self.triggers.ssh_user}"
    password = "${self.triggers.ssh_pass}"
    agent    = "false"
    timeout = "30m"
  }
}

```

### Debug Output
```
azurerm_virtual_machine.vm[0]: Still destroying... [id=/subscriptions/3c994c41-79b6-4437-ad0f-...mpute/virtualMachines/itse-BootStrapVM, 40s elapsed]
azurerm_virtual_machine.vm[0]: Destruction complete after 43s
╷
│ Error: remote-exec provisioner error
│
│   with null_resource.TearDownCluster,
│   on bootstrap_vm.tf line 101, in resource "null_resource" "TearDownCluster":
│  101:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1130765551.sh": wait: remote command exited without exit status or exit signal
╵
```

### Expected Behavior

The `remote-exec` provisioner  should wait for the shell script to finish execution before destroying the resources.
### Actual Behavior

The cluster(Azure VM) got deleted before the shell script completed execution
### Steps to Reproduce

1. `terraform apply`
2. `terraform destory`

### Additional Context

This is the shell script(`tear_down_cluster.sh) which is being executed.
```
#!/bin/bash
mycli create cluster test --yes &
process_id=$!
echo "Waiting for cluster to be deleted....."
wait $process_id
sleep 15m
```

**Comment by jbardin** [comment]
Hi @ratripathi,

In the example you have here, the script to execute is in a separate `null_resource` rather than the resource you are intending to destroy, and will be executed in its own lifecycle. 

The configuration here is not complete, but I'm assuming that `azurerm_network_interface.anic-01` is also referenced by the instance in question, which means that with no other resources in the dependencies graph it will be destroyed in parallel with the other instances resulting in the behavior you are seeing here.

Without the rest of the config I cannot say for certain, but It may be possible to reference `null_resource.TearDownCluster` from these other resources to enforce the destroy ordering. You may also be able to put the destroy provisioner directly in the `azurerm_network_interface` or the cluster resource themselves. However there are a number of issues with using provisioners in general (especially when adding an arbitrary `sleep` to ensure completion), and especially destroy-time provisioners which means you may want to look for solutions more tailored to your specific use case.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by ratripathi** [comment]
Thanks @jbardin , I will go through the details you have shared and try to see if that solves my problem. 
Though there could be solutions/hack available but the intention of raising this as a "bug" was to highlight a usability issue when it comes to documentation. I spent a lot of time searching for a solution for this simple use case but unfortunately I couldn't get any direction. I understand the use of states and how Terraform is architected but on a high level, I am looking for a way to trigger script/code outside the maintained state. For example:

tf create:
1.  Create EC2 instance
2.  Create a text file on the instance and write some random text on that note file

tf destroy:
1. Delete the notes file then-->(I am not able to figure out this)
2. Delete the EC2 instance

I am not sure if the above use case is supported by TF?
