### ISSUE TITLE
local_file resource "Error: Provider produced inconsistent final plan"

### ISSUE THREAD

**Issue by justinTM** [hashicorp/terraform#29472]
When using a Grafana Dashboard resource, there is an option to increment the version by 1 upon successful Apply.

If you try to write a local file containing the "version" resource attribute, you will receive the following error:

```console
Error: Provider produced inconsistent final plan
7349│ 
7350│ When expanding the plan for local_file.dashboards_panels_attributes to
7351│ include new values learned so far during apply, provider
7352│ "registry.terraform.io/hashicorp/local" produced an invalid new value for
7353│ .content: was
7354│ cty.StringVal("{\"container_overview.json\":[{\"dashboard_folder\":\"My Dashboard Folder\",\"dashboard_title\":\"My
Dashboard Title\",\"dashboard_uid\":\"asdkwervnas\",
\"dashboard_version\":9,\"id\":23409845,\"template\":\"my_filename.json\"},
...
...
...
but now
7692│ cty.StringVal("{\"container_overview.json\":[{\"dashboard_folder\":\"My Dashboard Folder\",\"dashboard_title\":\"My
Dashboard Title\",\"dashboard_uid\":\"asdkwervnas\",
\"dashboard_version\":10,\"id\":23409845,\"template\":\"my_filename.json\"},
...
...
...
```

Notice the `dashboard_version` attribute of the JSON file has changed from `9` to `10` between Plan and Apply stage.

**Comment by justinTM** [comment]
Temporary workaround until Hashicorp hires more staff:

```yaml
# .gitlab-ci.yml

.tf_plan:
  variables:
    TF_VAR_is_apply: false
    TF_VAR_is_plan: true

.tf_apply:
  variables:
    TF_VAR_is_apply: true
    TF_VAR_is_plan: false
```

```terraform
# dashboards.tf

# gather list of panel ID's and template filepaths per dashboard, to write JSON file
  panels_metadata       = flatten([ for dashboard_id, dashboard_json in local.some_or_all_dashboard_jsons : [ for panel in jsondecode(dashboard_json)["panels"] : {
      dashboard_folder  = local.dashboard_configs[dashboard_id]["folder"]
      dashboard_title   = local.dashboard_configs[dashboard_id]["title"]
      dashboard_uid     = local.dashboard_uids[dashboard_id]
      dashboard_version = var.is_plan ? grafana_dashboard.metrics[dashboard_id].version + 1 : grafana_dashboard.metrics[dashboard_id].version
      id                = panel["id"]
      template          = panel["template_path"] } ] ])
```

^^ notice `dashboard_version`, whose value is being assigned conditionally based on the `is_plan` boolean variable. if the current pipeline job is Terraform Plan, then increment the existing dashboard version by 1. otherwise (if Apply), use the provider-incremented `version` attribute.

**Comment by jbardin** [comment]
Hi @justinTM,

The [grafana](https://registry.terraform.io/providers/grafana/grafana/latest) provider is not developed at Hashicorp, so you would need to file an issue with their project for a resolution here.

However, I would like to understand why this error is being raised from within the `local_file` resource rather than the grafana resource itself, but I need the information requested in the issue template. 

Can you share a more complete version of the configuration that demonstrates the issue?
Can you verify that you are using the latest release of terraform?
In this case I would only be looking for warnings about the behavior, so running the plan and apply with `TF_LOG=warn` may show issues with that particular grafana resource which could explain the behavior.

Thanks!

**Comment by justinTM** [comment]
hey James,

error said it was the local_file provider not the grafana provider

**Comment by jbardin** [comment]
Hi @justinTM, yes, that is mentioned above, but the most likely source of the problem is the grafana resource. We will however need the requested information in order to verify that assumption.

Thanks!

**Comment by apparentlymart** [comment]
Indeed, this does seem like a symptom of an incorrect behavior in the Grafana provider, but one that isn't being caught at the source because of the exceptions we make to tolerate the bugs in the original plugin SDK, which the Grafana provider is using.

Specifically, if the Grafana provider (or the remote system it represents) is going to increment the value of the `version` attribute during the apply phase then it will need to do one of the following:

1. Report in the plan that `version` will change to a particular new value, calculated by adding 1 to the existing value.
2. Report in the plan that it doesn't know what value `version` will take after apply, making it appear as "(known after apply)" in the plan, and thus letting Terraform know that derived values like your `local.panels_metadata` will also be fully known only after apply.

To achieve this, the provider developers would add a `CustomizeDiff` implementation to the resource type, which would then set this `version` attribute in one of the ways described above. I would suggest taking option 1 only if there's a way to make the remote system refuse to update the dashboard if the version number is inconsistent, since that would achieve the effect of detecting whether the dashboard has "drifted" since the plan was originally created. Most systems don't have the capability to detect that sort of inconsistency though, in which case option 2 would be more appropriate to reflect that the final value of `version` will depend entirely on what the server returns during the apply phase.

@jbardin is asking for trace log information because it's likely that there will be a warning in there which confirms what I've said above, which'll say something like:

```
[WARN] Provider registry.terraform.io/grafana/grafana produced an unexpected new value for grafana_dashboard.metrics[0], but we are tolerating it because it is using the legacy plugin SDK.
```

It will then go on to report that `.version` has changed between plan and apply, and that this might be the cause of confusing errors from downstream operations. What you've found here would then be an example of such a "confusing error from a downstream operation": specifically, creating a local file whose content is derived from the dashboard resource.

(It seems like this might also apply to the `config_json` attribute, which appears to have the version specified inside it along with all of the other settings. That one will be harder to deal with because it's a mix of config-supplied and server-decided values; if so, my recommendation would be to exclude the version number from what the configuration is specifying and leave that to be decided entirely by the server, because Terraform's evaluation model doesn't allow for a single string whose content is partially specified in the configuration and partially chosen by the provider or remote system.)

**Comment by jbardin** [comment]
Since we have not heard back with any more information, I'm going to close this issue out for now. If more details about the problem become available, please post them here and we can reevaluate the issue.

If you have more questions, feel free to ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!
