### ISSUE TITLE
Backslash Interpolation Not Working

### ISSUE THREAD

**Issue by rnemeth90** [hashicorp/terraform#29486]
### Terraform Version

```
[10:49:36] C:\..\test on ❯  terraform version
Terraform v1.0.5
on windows_amd64
...
```

### Terraform Configuration Files

```terraform

locals {
  username_fmt = format("%s\\%s", var.netbiosName, var.domainAdminUsername)

  username_command = "$username = New-Object -TypeName string -ArgumentList ${local.username_fmt}"
}

output "test" {
  value = local.username_command
}
```

### Expected Behavior
```
Changes to Outputs:
  + test = "$username = New-Object -TypeName string -ArgumentList contoso\admin"
...
```

### Actual Behavior
```
Changes to Outputs:
  + test = "$username = New-Object -TypeName string -ArgumentList contoso\\admin"
...
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @rnemeth90,

Thanks for filing the issue. The output you have here looks correct, since the `a` character is part of the work `admin` and should not be an escape character. 

Perhaps the confusion is that you are looking at a quoted string, and not the raw value itself. One the plan is applied you can get the unquoted string using the `-raw` flag to the `output` command which will unquote the string. You can also get the value via the `-json` flags and handle it accordingly as well.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by rnemeth90** [comment]
Hi @jbardin ,

When using terraform version 0.13.7, the output returns the expected syntax (in the issue above), without changing any of the code. It's only after upgrading terraform to v1.0.4 (and v1.0.5) that I am seeing the issue of terraform not removing the second backslash. This sure does seem like a bug...

**Comment by jbardin** [comment]
The output since 0.14 has been updated to correctly format string values, and make them consistent in all cases for human readability. For automated use, machine readable formats of the plan and state values can be obtained with the `-json` flag to the `show` and `output` commands.
