### ISSUE TITLE
Duplicate variable declaration when any kind of module is used in darwin_arm64

### ISSUE THREAD

**Issue by NitsujY** [hashicorp/terraform#29526]
Currently, I am using `Terraform v1.0.6 on darwin_arm64`.

When I am using whatever module in my terraform project, for the first time after I am using `terraform init` and `terraform plan`. I can have everything succesfully spawn. But not the second time after applied. And I observed that there is duplicate file in those module. For example, `data.tf` and duplicated file `data 3.tf`, `fargate.tf` and duplicated file `fargate 2.tf` in the modules folder. 

Here is one of the error message
```
Error: Duplicate resource "aws_iam_instance_profile" configuration
│ 
│   on .terraform/modules/eks/workers_launch_template.tf line 599:
│  599: resource "aws_iam_instance_profile" "workers_launch_template" {
│ 
│ A aws_iam_instance_profile resource named "workers_launch_template" was already declared at .terraform/modules/eks/workers_launch_template
│ 3.tf:599,1-62. Resource names must be unique per type in each module.
```

What I can currently do is to reinstall all module `terraform init -upgrade` to make it works again
Please advise whether I have config something incorrectly or doing something wrong

**Comment by jbardin** [comment]
Hi @NitsujY,

Thanks for filing the issue. Can you provide an example with the exact steps used to reproduce the problem?
Web browsers are the usual source of `name N.ext` type files, choosing to modify the name when downloading a file with a conflicting name in the filesystem, but I'm not sure how you could arrive at that when using terraform modules.

Thanks!

**Comment by jbardin** [comment]
We have not heard back in a while, so I'm going to close this issue. The problem likely stems from an external tool manipulating Terraform configuration files, and is outside of the control of Terraform itself. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
