### ISSUE TITLE
Terraform not ignoring changes in latest_restorable_time attribute in aws_db_instance ressource

### ISSUE THREAD

**Issue by achrefbensaadVPaccount** [hashicorp/terraform#29543]
### Terraform Version

```
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.57.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

```

### Terraform Configuration Files

```terraform

resource "aws_db_instance" "this" {
  ....  configs  ....
  
   lifecycle {
    ignore_changes = [
     latest_restorable_time,
    ]
  }
}

```

### Expected Behavior

Terraform should of ignored the changes to latest_restorable_time attribute
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

The latest_restorable_time attribute is updated automatically by AWS on a frequent basis.

**Comment by jbardin** [comment]
Hi @achrefbensaadVPaccount,

Thanks for filing the issue. The `latest_restorable_time` a computed attribute of an `aws_db_instance`, which means it cannot be specified in the configuration. Because that attribute cannot be present in the configuration, there cannot be any change in configuration to ignore. 

I suspect you are seeing changes caused by the provider and reported during the refreshing of the resource. If that is the case, you likely want to follow #28803, which is about finding a way to limit the resource drift information returned by Terraform. For other questions, feel free to ask in the [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by crw** [comment]
Per pull request https://github.com/hashicorp/terraform/pull/30517, a warning is now output in this situation.
