### ISSUE TITLE
Cannot delete resources with dependencies at the same time

### ISSUE THREAD

**Issue by sunyiping-google** [hashicorp/terraform#29554]
### Current Terraform Version
```
v1.0.3
```

### Use-cases

I was trying to delete resource A, and resource B that references A. I cannot do the two operations together since Terraform will run into errors "Could not delete A because it is still being referenced by B".

(I was using Google Terraform Provider, but I think the underlying fix should be on the Terraform side. Please correct me if I'm wrong.)

### Attempted Solutions

The current standard solution is to separate the deletions in different code change-lists. To achieve this, we need to realize that the resources have dependencies first, and then identify the correct order to delete them. Unfortunately, I didn't find useful tools to help us catch such issues - running `terraform plan` still relies on our eyes to identify the problem; running `terraform apply` might could work, but having to do manual testing each time makes me wonder the value of having automation.
 
### Proposal

Is there a way to let Terraform know that the to-be-deleted resources do not have dependencies anymore in the new config, and could delete them all at once. 

### References

**Comment by jbardin** [comment]
Hi @sunyiping-google,

Thanks for filing the issue. Can you elaborate on the use case here? I'm not sure I understand what the underlying problem is. 

For example, terraform does not generate any errors in the form of `"Could not delete A because it is still being referenced by B"`, so I suspect the behavior you are referring to is from the provider. If the resources do have some dependency between them, there should be a reference between the resources in the configuration. If there is no natural attribute to associate the two resources, `depends_on` can be used to create a reference. This dependency is then recorded and used for proper ordering during destroy. If resources invert the logical dependency order, which often happens when one resource "registers" the other, you can use the `create_before_destroy` to alter the order of operations in terraform.

If you have a concrete example that reproduces the problem you are facing, it may help us determine if this is something that Terraform cannot currently handle.

Thanks!

**Comment by sunyiping-google** [comment]
Hi James, thanks for the explanation. Yes, the behavior I described is from the Google Provider.

I didn't make it clear in the original question. I'm deleting a resource and a reference to that resource at the same time.

More specifically, I was deleting a notification channel "my_email" and deleting the reference to "my_email" from "my_alert_policy". 

```
resource "google_monitoring_alert_policy" "my_alert_policy" {
    notification_channels = [
        google_monitoring_notification_channel.my_email.name,
    ]
}

resource "google_monitoring_notification_channel" "my_email" { }
```

**Comment by jbardin** [comment]
Hi @sunyiping-google,

In the given configuration, if `google_monitoring_notification_channel.my_email` cannot be deleted until after `google_monitoring_alert_policy.my_alert_policy` is updated, then you must use `create_before_destroy` in order to change the order of operations. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. This repository is only monitored by a few core maintainers.

Thanks!
