### ISSUE TITLE
Jsonencode unable to encode list of comma separated objects

### ISSUE THREAD

**Issue by saifmahamood** [hashicorp/terraform#29562]
### Terraform Version

```
v0.15.1
```

### Terraform Configuration Files

```terraform
#variables.tf
variable "listen-ports" {
  type = string
  description = "Internet ports that the ALB should listen on"
}

#helm.tf
 set {
    name = "ingress.annotations.alb\\.ingress\\.kubernetes\\.io/listen-ports"
    value = var.listen-ports
  }

#local.tf
ports             = jsonencode([{ HTTP = 80}, {HTTPS = 443}])
```

### Crash Output

```
saif.mahamood@vts-mbp-saifmahamood us_east_2 % terraform plan
var.image_tag
  Enter a value: 0.2.1

module.data-grid-data-service_dev.helm_release.application: Refreshing state... [id=data-grid-data-service]
╷
│ Error: error getting values for a diff: failed parsing key "ingress.annotations.alb\\.ingress\\.kubernetes\\.io/listen-ports" with value [{"HTTP":80},{"HTTPS":443}], key "{\"HTTPS\":443}]" has no value
│
│   with module.data-grid-data-service_dev.helm_release.application,
│   on ../../../infra-module-application-deployment/helm.tf line 17, in resource "helm_release" "application":
│   17: resource "helm_release" "application"
```

### Expected Behavior

It should have been able to encode the list as a list of objects

### Actual Behavior

It gave an error message saying it's unable to read comma separated values 

### Steps to Reproduce

`terraform init`
`terraform plan`
### Additional Context

Running this in a local environment for now 

# #

**Comment by alisdair** [comment]
Hi @saifmahamood, thanks for reporting the issue. Unfortunately there isn't enough detail here for me to reproduce the problem you're seeing, so I can't determine what the cause is.

Can you please provide a small but complete example which demonstrates this behaviour? The partial snippets you've given aren't quite enough. Thanks!

**Comment by saifmahamood** [comment]
As mentioned before, the problem is with `listen-ports`

**Comment by jbardin** [comment]
Hi @saifmahamood,

The output from Terraform looks correct, and the value is a valid json encoding of the two objects.
Since the error is coming from the helm provider, I would suggest opening an issue with them. They will have more context to help better clarify what about the data format isn't acceptable, and how to go about configuring this resource.

Thanks!
