### ISSUE TITLE
Feature : Support aws-marketplace:Subscribe call

### ISSUE THREAD

**Issue by TheM0ng00se** [hashicorp/terraform#2956]
A number of paid AMIs require the AWS account to Subscribe before they become available. It would be nice to have subscribe built-in to eliminate the need to manually subscribe for Marketplace AMIs requiring suscription.

**Comment by apparentlymart** [comment]
I can't find any reference to an API for subscribing to AMIs in the marketplace. Do you know if there is one and if so where its docs are?

It wouldn't surprise me if there isn't a way to do this automatically since many marketplace AMIs require payment and/or agreeing to some terms of service, both of which suggest having a mandatory manual workflow.

**Comment by catsby** [comment]
Closing for now, as I'm unable to find a programatic way to do this. If I'm wrong, please provide a link and I'll look into it.

Thanks!
