### ISSUE TITLE
This problem is still occuring

### ISSUE THREAD

**Issue by Ryukx** [hashicorp/terraform#29575]
This problem is still occuring 

Terraform v0.12.3
provider.azurerm v2.43.0

The destruction is not working as expected, i guess it returns before checking if the resource is completely removed.
The resource azurerm_automation_job_schedule is still exist !
_Originally posted by @Ryukx in https://github.com/hashicorp/terraform-provider-azurerm/issues/4851#issuecomment-918940158_

**Comment by jbardin** [comment]
Hi @Ryukx,

If you have an issue with terraform itself, please fill out the issue template with the requested information to completely reproduce the problem. I would suggest also trying a current release, as v0.12 is no longer being developed. If the issue is with the azure provider, please file a new issue in their repository.

Thanks!
