### ISSUE TITLE
remote backend unauthorized with proper token

### ISSUE THREAD

**Issue by turribeach** [hashicorp/terraform#29586]
### Terraform Version

```
Terraform v0.11.14
```

### Expected Behavior

Terraform init does not fail

### Actual Behavior

Running 
Initializing the backend...

Error configuring the backend "remote": failed to read organization entitlements: unauthorized

Please update the configuration in your Terraform files to fix this error.
If you'd like to update the configuration interactively without storing
the values in your configuration, run "terraform init".

### Steps to Reproduce

terraform init

### Additional Context

Occasionally I get "remote backend unauthorized" error when running any terraform local command like "terraform init" despite having a proper token on my Terraform local config file (C:\Users\\[userid]\AppData\Roaming\terraform.rc). I checked issue #19657 but -reconfigure flag does not fixes the problem. What does fix the problem to login into my Terraform Enterprise web instance on my browser (we use SAML). After I login on the browser "terraform init" starts to work on my PC again. How is this possible? The browser can't touch any Terraform configuration on my PC. Is the server keeping a state on my account to allow my TF token to work? Thanks

**Comment by apparentlymart** [comment]
Hi @turribeach,

Unfortunately it's hard for us to help with this sort of problem via GitHub issues because the details likely depend on how you've configured your credentials, what level of access those credentials have, etc.

Since you are a Terraform Enterprise customer, I'd suggest [opening a support ticket](https://support.hashicorp.com/hc/en-us/requests/new) as a first step here. The support team is better equipped to help with this sort of problem, because they will tend to be aware of anything special about your particular Terraform Enterprise install, whether others in your organization have encountered similar problems, etc.

I'm going to close this for now just because I don't think there's anything we can do here without at least a round of initial troubleshooting with the support team. If that troubleshooting leads to what seems like a Terraform CLI bug then of course we can reopen this to represent it, although I will note that Terraform v0.11 is no longer actively maintained and so the resolution might include upgrading to a newer version of Terraform CLI which either already has the issue fixed or that we can make a new release including a new fix.

Thanks!
