### ISSUE TITLE
Concat function returns a tuple

### ISSUE THREAD

**Issue by brennfoster** [hashicorp/terraform#29602]
Terraform version: 2.77.0

Trying to concatenate ip_addresses from api management instance:
locals {
  apim_ip_addresses = concat(data.azurerm_api_management.default.public_ip_addresses, data.azurerm_api_management.default.additional_location[*].public_ip_addresses)
}

When an api management resource has additional locations it returns as a tuple. Based on the 'splat' documentation, I would think that this should return a list of ip addresses from each location.

Getting this error when trying to loop over the list:
│ Error: Invalid function argument
│      for_each = toset(local.apim_ip_addresses)
│     ├────────────────
│     │ local.apim_ip_addresses is tuple with 2 elements
│
│ Invalid value for "v" parameter: cannot convert tuple to set of any single type.

### Expected Behavior
Concat function should always return a list.

### Actual Behavior
Concat function returned tuple.

**Comment by jbardin** [comment]
Hi @brennfoster,

The `concat` function may return a tuple when the given types cannot all be unified, and in this case you are supplying a list of lists as the second argument to `concat`, giving you a type of `tuple(list(string), list(list(string)))`.

There is the `flatten` function which can help in some cases, but here you can [expand](https://www.terraform.io/docs/language/expressions/function-calls.html#expanding-function-arguments) the second argument using `...`

```
locals {
  apim_ip_addresses = concat(data.azurerm_api_management.default.public_ip_addresses, data.azurerm_api_management.default.additional_location[*].public_ip_addresses...)
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by brennfoster** [comment]
I did not know about that. Thank you!
