### ISSUE TITLE
Error waiting for NAT Gateway  to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by PrateekKhatri** [hashicorp/terraform#29630]
Hello,
Terraform version: v0.15.3
aws provider = 3.59.0

We are using terraform VPC module to deploy 2 private subnets and attaching that subnet to my Redis Elastic Cache. After applying it is working fine. 

But when a new request comes to add 2 more private subnets to the existing infra, we added 2 more private subnets to the existing infra and then run terraform apply command. After running some time we got the below error:

Error: Error waiting for NAT Gateway to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)

Is there any solution for the same?

Because of this error, we are not able to continue with incremental infra deployments.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
