### ISSUE TITLE
changes reported on whitespace changes

### ISSUE THREAD

**Issue by dbbc96** [hashicorp/terraform#29655]
### Terraform Version
```
Terraform v0.12.31
aws provider 3.58.0
```

### Expected Behavior
No updates were made to file but should have received this:
```
Plan: 0 to add, 0 to change, 0 to destroy.

```

### Actual Behavior
Had received this message on a windows pc but running on a linux based host reported no changes.

```
= jsonencode( # whitespace changes

```

### Steps to Reproduce

This problem, whereby Terraform is unnecessarily applying changes due to perceived whitespace change, occurs when two different team members are working on two different operating systems (Unix and Windows).

1.  On a Unix/Mac machine, make some Terraform config change and terraform apply
2.  On the same Unix/Mac machine, do terraform plan and observe that no changes are detected - correctly.
3.  Switch to a Windows machine, check out the latest config used in steps 1&2 and run terraform plan. Observe that it wants to make a change due to whitespace differences, as per output shown above.

The same problem occurs if working the other way round (start with Windows, switch to Unix/Mac).

### Additional Context
we are calling a module that contains a template file (see snipet below).  This template file is where the whitespace is being detected in however no changes have been made within the json.tpl file.
content = templatefile(...

**Comment by jbardin** [comment]
Hi @dbbc96,

Thanks for filing the issue. Terraform needs to use the exact values from the configuration, and while changes to whitespace may not by important in your particular case, they are nonetheless still changes that needs to be tracked. If users are changing the line endings in the `templatefile`, then terraform needs to preserve those changes. See #29623 and #21479 for a similar discussions. 

I also notice that the plan shows the output in `jsonencode`, you may have an easier time creating the json from the data structures themselves using the examples in the [`jsonencode` docs](https://www.terraform.io/docs/language/functions/templatefile.html#generating-json-or-yaml-from-a-template), rather than a template, because templating json can be rather tricky. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
