### ISSUE TITLE
When saving `terraform workspace list` output to a variable in bash, the files present in the directory are included in the output.

### ISSUE THREAD

**Issue by shortpoet** [hashicorp/terraform#29654]
### Terraform Version

```
Terraform v1.0.6
```

### Terraform Configuration Files

Empty, no need for files to repro.

### Debug Output

Just unexpected behavior in bash.

### Expected Behavior

When saving `terraform workspace list` output to a variable in bash, I expect only the workspace names to be included.

### Actual Behavior

The files present in the directory are included in the output.

### Steps to Reproduce

1. `terraform init`
2. `terraform workspace new dev && terraform workspace new test`
3. `workspaces=$(terraform workspace list)`
4. `echo $workspaces`
5. $ default dev terraform.tfstate.d test

If you have more files, they will also be included.

### Additional Context

git bash in Windows 10; WSL2 Ubuntu 20.04 in Windows 10

The files are listed after the currently selected workspace. If you change the current workspace, the placement of the files in the output will change.

I would like to be able to have clean output (even omitting the asterisk) to be able to iterate over all the workspaces programatically. This would be helpful to perform API actions on each of the workspaces by using the prefix combined with the workspace suffixes.

I tested this in powershell and the output saved to a variable is the same as when running it plain. If possible, it would be nice to have clean output without the asterisk there as well. Possibly using a flag such as `terraform workspace list --clean` 

### References

Couldn't find any open issues or other references.

**Comment by jbardin** [comment]
Hi @shortpoet,

The output of `terraform workspace list` contains a `*` character, which your shell may use as a glob expression in the current directory, expanding it into the filenames. This is one of the reason to always enclose shell variables in double quotes, which prevents the output you are seeing:

```
echo "$workspaces"
  default
* test
```

Since the behavior of the shell is not something terraform can effect, (and not all shells are the same, `zsh` for example does not implicitly expand globs like this by default), and it does not represent a bug in terraform I'm going to close this. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by shortpoet** [comment]
Thank you for the explanation! Please pardon the mixup on my end, it had been a long day of working with the API when I came across that and had indeed forgotten to quote the variable 😅
