### ISSUE TITLE
Lifecycle configuration: only_create

### ISSUE THREAD

**Issue by luanhdeandrade** [hashicorp/terraform#29687]
### Current Terraform Version

```
Terraform v1.0.3
on linux_amd64
```

### Use-cases
Creating and managing task definitions in AWS ECS. The user rarely wants to deregister a previous task definition when there is a change into the task definition attributes. The most common is that the user wants to create a new task definition and update the service to use it, but still have the previous one remaining for rollback situations.

As terraform replaces the task definition (i.e deregisters the older and creates a new) by default, the user is forced to use an _ignore_changes_ lifecycle configuration. But this is not good either, as the task definition will have to be managed externally.
There should be a way of letting a resource that does not support updates be only created in case of changes that require replacement, such as the Task Definitions. 

### Proposal
A good feature for this situation would be a new lifecycle configuration: _create_only_ (for example) that would make terraform skip the deletion of a resource in case of replacement and only try to create a new one. Of course, there would be problems with the usage of this configuration if the resource has unique attribute constraints, but in this case it would be up to the user to not use this configuration if that is the case.

**Comment by apparentlymart** [comment]
Hi @luanhdeandrade! Thanks for sharing this use-case.

This seems like an area we've talked through a few times now in the history of Terraform. A previous-job version of me (before I joined HashiCorp) even proposed in #1586 a variant of this with Packer as the artifact-builder!

However, our current take on this problem is that creating a series of artifacts that you can roll forward and back between is a "build process" which is outside of Terraform's scope. Instead, the common approach is to have a build pipeline that creates the new artifacts, writing a location or identifier of the latest artifact to somewhere Terraform can read using a data source, and then have Terraform be responsible only for _activating_ that artifact.

In your case it sounds like the task definition and any container images it refers to are together the "artifact", and so the ECS-specific implementation of the above model would be to write the task definition ARN into whatever location you decide is the source of truth for the currently-selected artifact, and then have Terraform read it and pass it into `aws_ecs_service`. If you need to roll back then your rollback process would write an older task definition ARN into that location and re-run Terraform to have it re-deploy the old definition.

We did some experiments some years ago with different ways to potentially use Terraform itself or Terraform providers as part of a build process instead of a deploy process (some publicly-visible traces of that over in #2789), but we ultimately concluded that those two have different enough user models that building artifacts isn't a good fit for Terraform's workflow and thus outside of Terraform's scope. However, you can see a more modern interpretation some of those ideas in the newer project [HashiCorp Waypoint](https://www.waypointproject.io/), which aims to orchestrate the full build and deploy flow (including explicit support for rolling back) and [has support for targeting ECS](https://www.waypointproject.io/plugins/aws-ecs).

Since previous discussion concluded that the use-case you described here is not an intended part of Terraform's scope, and since HashiCorp now has a newer project aimed more directly at this use-case, I'm going to close this. Thanks again for sharing it, though!
