### ISSUE TITLE
feature: ability to disable the dependency lockfile

### ISSUE THREAD

**Issue by aslafy-z** [hashicorp/terraform#29760]
### Current Terraform Version

```
v1.0.0
```

### Use-cases

I want to use a custom provider binary (locally built) when developing or fixing bugs on it.

### Attempted Solutions

- use the CLI configuration `filesystem_mirror` to host a modified version of the provider: warn for invalid hashes in the lockfile
- then, `terraform providers lock`: regenerates the lock file from the remote source (not local one)

### Proposal

Add a flag `-no-lockfile` that completly ignore the dependency lockfile.

**Comment by terlar** [comment]
I still think this is a valid request, seems a lot of people are requesting the feature to disable the lockfile for many different reasons.

Two on top of my head:
- read only terraform directory
- managing plugins and pinning by themselves

Reference to people having this sentiment can be found in:
- #27241
- #27506
- #29112
- #27158
- #28402

Then there is also a lot of issues opened related to the terraform lock file and using different platforms. I won't link them here though, since that is of topic. But that could also be a reason why people would like to opt out.

I was planning to create an issue for this for some time and was half way through, but unfortunately lost the content. If you think it would be valuable for me to create a new issue for this.

Thanks!

**Comment by apparentlymart** [comment]
Hi @terlar,

For the problem of read-only filesystems (and other related situations where we don't want to modify the filesystem, even if that were possible) we added a `-lockfile=readonly` option to `terraform init` in one of the v0.15 releases, which has therefore been in all of the v1.0 releases. That tells Terraform not to update a lock file, though it does require that someone would've previously put a lock file in place first, perhaps by populating it on some other machine.

We are also aware of the challenges that arise when using the lock file with the optional global provider cache directory, which I assume is what you're referring to with regard to lock file on different platforms. There are documented workarounds for that, and we do intend to improve on it in a later release. That's currently represented by #27811.

If you don't wish to use the lock file to persist selections between runs of Terraform then you can instead treat it as a per-working-directory artifact by putting it in your `.gitignore` file, or equivalent in other version control systems. In that case, `terraform init` will re-construct it each time you start using Terraform in a new working directory, which therefore reproduces the effective behavior of Terraform before it had a lock file. However, anyone doing that should keep in mind that they will defeat one of the mechanisms by which Terraform helps ensure that nobody has tampered with the provider packages most recently selected. There are other parts of that strategy, such as TLS certificate verification of the registry server, but some threat models require a "trust-on-first-use" approach and that in particular will be defeated by not storing the lock file in your version control system.
