### ISSUE TITLE
Adding conditional validation of resource/provider parameters

### ISSUE THREAD

**Issue by svanharmelen** [hashicorp/terraform#298]
As discussed on the mailinglist (so just adding it here as a placeholder), it would be cool to have some more advanced way's to validate resource/provider parameters. Two concrete examples are:

1. A kind of radiogroup behaviour where one (and only one) parameter of a certain subset of parameters can/must have a value. The implementation of this one could be done by adding a new string field to the schema.Schema struct (say called RadioGroup) which value is an identifier for the group. So all other parameters which have the same RadioGroup identifier are then supposed to be a member of that group.

2. A way to make sure a parameter is unique when it can be specified more then once (so this one would only make sense for the TypeList and TypeSet (and maybe also TypeMap?) ValueTypes). The implementation for this one could be done by adding a new bool field called (for example) Unique to the schema.Schema struct, When computing if the given value is indeed unique, special care should be taken for zero-values. Say for example a TypeBool ValueType can have only two possible values, so in this case unique would mean that only one parameter in the list or set can be true and the rest has to be false.

**Comment by jen20** [comment]
Hi @svanharmelen! I think most of the behaviour described here has already made its way into Terraform via the `helper/schema` package, and perhaps this issue can be closed off. Specifically:

1. You can specify `ConflictsWith` on schema elements in order to indicate that only one of a group of options should be set.

2. I'm not 100% certain I follow on this, but if I understand you correctly, it's possible to ensure that values in a set are unique by using a hash function in a similar manner to [rules in a security group in the AWS provider](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_security_group.go#L342-L378). Do you have a more concrete example if that isn't what you mean?

**Comment by svanharmelen** [comment]
@jen20 indeed it sort of covers the use cases, through there are still use cases that could/should be supported to make things easier to use.

But I'm ok with closing this one and opening a PR if (if ever) I get to adding the things I'm thinking of :wink:

Cheers!
