### ISSUE TITLE
Make empty environment variables triggering default values

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#29854]
### Current Terraform Version
1.0.10

### Use-cases
Easier control of default values for input variables.

Example:

```
variable "test" {
  type = number
  default = 1
}
```

```
TF_VAR_test= terraform plan
```
fails with

```
│ Error: Invalid value for input variable
│ 
│ The environment variable TF_VAR_test does not contain a valid
│ value for variable "test": a number is required.
```

It is a lot easier to set an empty value than remove a variable in CI/CD and other automation software.

### Proposal
Something like this would be very helpful.
```
variable "test" {
  type = number
  default = 1
  default_on_empty_env = true
}
```
Or use the default value in case of an empty env variable always, without additional configuration. I personally think it's nonsense to treat input values for numeric variables in the same manner as for strings. Nobody would intentionally set an empty string to a numeric variable. The current behavior is fine for TF developers but not fine for practical usage by humans. I believe the same proposal would be perfect for other non-string types.

Currently, interpreting an empty value as a trigger for the default value requires avoiding setting a type and using excessive code like this:

```
variable "test" {
  default = 1
  validation {
      condition =  var.test != "" && can(tonumber(var.test))
      error_message = "Only number of emptry string are accepted."
  }
}

locals {
    test_value = coalesce(tonumber(var.test), 1)
}
```

**Comment by jbardin** [comment]
Hi @speller,

Thanks for filing the issue. The problem with this type of interpretation, is that there is no way to differentiate between an  empty string and a null input with the syntax proposed here.  Since the shell is interpreting the variable, `TF_VAR_test=` is identical to `TF_VAR_test=""`. 

Only a `null` value is used to trigger a default for module input, and we currently have no way to set a primitive null value via an environment variable. You can track the existing feature request in the open issue #29078.

Thanks!
