### ISSUE TITLE
Escape sequence doesn't work for literal backslash

### ISSUE THREAD

**Issue by gielVanDeVoorde** [hashicorp/terraform#29875]
### Terraform Version

```
C:\Users\giel.van.de.voorde>terraform -v
Terraform v1.0.10
on windows_amd64
```

### Terraform Configuration Files

```
resource "azurerm_virtual_machine_extension" "create-dc" {
  count = var.createDC == "No" ? 0 : 1
  name                 = "create-dc"
  virtual_machine_id   = azurerm_windows_virtual_machine.machine.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.9"
  settings = <<SETTINGS
  {
    "commandToExecute": "powershell.exe -Command \"${local.powershell_command_dc}\""
  }
SETTINGS
}

  credential_command = "$credential = New-Object -TypeName PSCredential -ArgumentList '${var.netbiosName}\\Administrator', $password"
  configure_dc_command = "Install-ADDSDomainController -CreateDnsDelegation:$false -Credential $credential -DomainName ${var.domainName} -InstallDns:$true -SafeModeAdministratorPassword $password -Force:$true"
  powershell_command_dc = "${local.import_command}; ${local.password_command}; ${local.credential_command}; ${local.install_role_command}; ${local.wait_for_domain}; ${local.configure_dc_command}; ${local.shutdown_command}; ${local.exit_code_hack}"
```

### Debug Output
Error: "settings" contains an invalid JSON: invalid character 'A' in string escape code
│
│   with module.machine["test-DC"].azurerm_virtual_machine_extension.create-dc[0],
│   on modules\machine\main.tf line 154, in resource "azurerm_virtual_machine_extension" "create-dc":

### Expected Behavior
According to docs, it should convert my double backslash to a normal backslash
https://www.terraform.io/docs/language/expressions/strings.html

### Actual Behavior
It ignores my first backslash and thinks my second backslash combined with 'A' is an escape sequence

**Comment by apparentlymart** [comment]
Hi @gielVanDeVoorde!

It seems like what you have here is a classic problem that appears when you have multiple languages nested inside one another, particularly when those languages have similar syntax. This error seems to be returned by the Azure provider rather than by Terraform, and it's complaining that the JSON string in `settings` isn't valid, rather than that your Terraform syntax isn't valid.

You can remove at least one layer of tricky escaping here by using Terraform's [`jsonencode`](https://www.terraform.io/docs/language/functions/jsonencode.html) function to produce the JSON, instead of trying to construct JSON via string concatenation:

```hcl
  settings = jsonencode({
    commandToExecute = "powershell.exe -Command \"${local.powershell_command_dc}\""
  })
```

This will allow Terraform to be responsible for handling the _JSON_ escaping for you, which should cause the resulting string to contain the extra backslash necessary to escape `\A` in JSON, but in your case it's extra complicated because you have yet another layer: powershell's own escaping. Terraform doesn't have a built-in function for PowerShell escaping so there isn't such a convenient answer for that, but _hopefully_ as long as you get all of the quoting correct and make sure that none of your strings contain characters that PowerShell will consider significant the JSON escaping should be enough to make this work.

Since Terraform seems to be working correctly here (it interpolated literally `\A` into the template, as you asked it to), I'm going to close this issue. However, if you have further questions about my answer above, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
