### ISSUE TITLE
Terraform CDK adding ssh key to Google Compute Engine 

### ISSUE THREAD

**Issue by bharath79** [hashicorp/terraform#29870]
I've tried adding ssh key to my instances and have failed everytime. 

Source code:

    class MyStack extends TerraformStack {
       constructor(scope: Construct, name: string) {
       super(scope, name);
    
    const credentials = fs.readFileSync(credentials.json).toString();

    new GoogleProvider(this, "Google", {
      region: "us-central1",
      zone: "us-central1-a",
      project: "project",
      credentials,
    });

    new ComputeInstance(this, "ComputeInstance", {
      name: name,
      machineType: "f1-micro",
      bootDisk: {
        initializeParams: {
          image: "debian-cloud/debian-9",
        },
      },
      networkInterface: [
        {
          network: "default",
        },
      ],
      tags: ["web", "dev"],
    });
  }
}

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. There is also a topic specifically for [Terraform CDK](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47).

Thanks!
