### ISSUE TITLE
0.14+ throws "count" value depends on resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by bharathkkb** [hashicorp/terraform#29884]
### Terraform Version
```
v0.14.11 (and v1.0.6)
```

### Terraform Configuration Files

A bit of a contrived example to simplify repro but real code where error is [here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/e1c6a534ff8f69343edb839dc2496d108483ebd3/modules/shared_vpc_access/main.tf#L48) 
```terraform
locals {
  kv = {
    "mykey1" : "foo",
    "mykey2" : "bar",
  }
  tomatch = ["mykey1", "mykey3"]

  matches    = setintersection(keys(local.kv), local.tomatch)
  transformed = length(local.random_res) != 0 ? tolist(setproduct(local.matches, local.random_res)) : []

  random_res     = [for r in random_pet.rands : r.id]
}

resource "random_pet" "rands" {
  for_each = toset(["foo", "bar"])
}

resource "random_pet" "other" {
  count = length(local.transformed)
}
```

### Expected Behavior

apply works (as with v0.13.7)

### Actual Behavior

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @bharathkkb,

Sorry about the change in behavior here, but what you are showing is the correct result. Before 0.14 the `setproduct` function would return incorrect results when the given sets contained unknown values.

The plan time values computed by `setproduct` would be look like:
```
[
  [ "mykey1", Unknown],
  [ "mykey1", Unknown],
]
```

As you can see, if those literal values were combined into a set it would result in a single value. Once the unknown values are known there could be either 1 or 2 values in the set, but that cannot not be known until after all the resources have been created.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
