### ISSUE TITLE
Variable validation of type number fails

### ISSUE THREAD

**Issue by Wuzyn** [hashicorp/terraform#29899]
### Terraform Version

```
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

```terraform
variable "my_number" {
  type = number
  validation {
    condition = contains([1, 2, 3], var.my_number)
    error_message = "Failed."
  }
}

resource "null_resource" "this" {

}
```

### Debug Output

https://gist.github.com/Wuzyn/2d3c435df178ba8147f10b8c0430d6fb

### Expected Behavior
Running terraform plan/apply and providing value from condition list should pass the validation

### Actual Behavior

```
terraform plan
var.my_number
  Enter a value: 1

╷
│ Error: Invalid value for variable
│
│   on main.tf line 1:
│    1: variable "my_number" {
│
│ Failed.
│
│ This was checked by the validation rule at main.tf:3,3-13.
╵
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. Provide correct value, which should pass validation

**Comment by jbardin** [comment]
Thanks for filing the issue @Wuzyn!

The validation here seems to be a result of getting the input from the CLI, and it's not converted to the correct type before validation. The comparison fails because the value is still `cty.StringVal("1")`. It also fails when passing in the value via the `-var` flag.

Thanks!

**Comment by apparentlymart** [comment]
It looks like the problem here is root in some uncertainty about which component in Terraform would be responsible for evaluating variable values in the root module.

For input variable values on _called_ modules, the whole situation is handled inside the graph node that represents each input variable: it first evaluates the variable (which includes both evaluating the expression and converting it to match the given type constraint), then records the values for use in downstream expressions, and runs the validation rules against that result:

https://github.com/hashicorp/terraform/blob/385a3ba879d333c56dc25896993e24988cd6b012/internal/terraform/node_module_variable.go#L145-L177

The story for root module variables is a little different because Terraform Core doesn't actually _evaluate_ those, and instead they get passed in from the caller (the CLI layer) and immediately saved for use elsewhere. The only thing that happens when we visit their graph nodes is running the validation rules:

https://github.com/hashicorp/terraform/blob/385a3ba879d333c56dc25896993e24988cd6b012/internal/terraform/node_root_variable.go#L40-L56

In order for those to be of the correct type (matching the given type constraint) the codepath which originally populated the evaluation context would need to have done it already. However, that codepath just naively copies the raw value coming from the caller without any transformation whatsoever:

https://github.com/hashicorp/terraform/blob/385a3ba879d333c56dc25896993e24988cd6b012/internal/terraform/graph_walk_context.go#L122-L125

To fix this we'll need to decide which layer ought to be responsible for the step of converting the raw values from the caller to match the constraints given in the configuration, and make sure it ends up performing the same conversion step we do for internal calls, prior to checking the custom variable validation rules.
