### ISSUE TITLE
Enable local execution mode with cloud-defined variables

### ISSUE THREAD

**Issue by ronisec** [hashicorp/terraform#29907]
### Current Terraform Version

```
Terraform v1.0.5
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.0.10. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

The end goal I am trying to reach is **fast executions of Terraform**.

### Attempted Solutions

I have noticed there is significant overhead for remote Terraform executions. As a result, during development, I want to run locally to improve velocity (through dev iterations). I noticed that when running locally, I don't have access to all the variables defined in my workspace. This is limiting since some variables are sensitive and can't be copied (+ it is very cumbersome to have to copy them one-by-one to the command line).

### Proposal

Allow local executions to pull workspace variables.

**Comment by apparentlymart** [comment]
Hi @ronisec! Thanks for sharing this use-case.

Unfortunately what you are requesting here is in conflict with a requirement in Terraform Cloud's design: that even the Cloud _API_ won't return the values of sensitive variables, and so Terraform CLI can't access any variables automatically that you couldn't copy manually. Since that is a Terraform Cloud behavior rather than a Terraform CLI behavior it's not something we'd be able to change as code in this repository, so it would probably be best to send that use-case to [Terraform Cloud support](https://support.hashicorp.com/hc/en-us) who might be able to suggest a workaround and can pass on this feedback to the Terraform Cloud team.

It is possible in principle for Terraform CLI to retrieve and use the _non-sensitive_ variables, though. I see some code in the remote backend source that seems like it's already attempting to do that:

https://github.com/hashicorp/terraform/blob/385a3ba879d333c56dc25896993e24988cd6b012/internal/backend/remote/backend_context.go#L94-L99

This may therefore get you part of what you want (aside from the sensitive values, which you'd need to still handle manually) if you run Terraform against your remote workspace but with remote operations forced off using the environment variable `TF_FORCE_LOCAL_BACKEND=1`.

**Comment by ronisec** [comment]
Thanks for the quick response Martin! That makes sense, I'll try mixing `TF_FORCE_LOCAL_BACKEND=1` while providing sensitive vars through the CLI.
