### ISSUE TITLE
Backwards incompatible Terraform plan/apply output in Terraform 0.14

### ISSUE THREAD

**Issue by fardin01** [hashicorp/terraform#29901]
### Terraform Version

```
0.14.11
0.15.5
```

### Terraform Configuration Files

```terraform
resource "null_resource" "test" {}
```

### Expected Behavior

```
$ terraform13 plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------
```

### Actual Behavior

```
$ terraform14 plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

So in Terraform < 0.14, the output of `terraform plan` and `terraform apply` had a delimiter (`------------------------------------------------------------------------`) at the beginning and the end. With Terraform >= 0.14, the first delimiter is removed.

This is a problem because our pipeline/automation (and I imagine other users' pipelines) use these delimiters to fetch the most useful part of the plan and render it. Of course, this output is intended to be reviewed by humans and it is, but running `terraform plan`, gathering the output, and putting them together in a presentable way is automated and done by a machine. When we make Terraform changes, we usually do it in more than one place, so our automation calculates the plan for all the changes and presents it in a comment on the PR. 

Can we get the delimiter back, please? It's very very useful.

### References

https://github.com/hashicorp/terraform/issues/27100

**Comment by jbardin** [comment]
Hi @fardin01,

Thanks for providing this use case. I'm going to reclassify this as an enhancement request since the output is working as designed, and does not represent a bug in the Terraform CLI. Since the current supported versions of terraform are past the v1.0 mark, you can see details about what is classified as a breaking change in the [Terraform v1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html) document.

If you are looking for a currently supported solution, the plan artifact can be provided to the `terraform show` command to display the full contents of the planned changes, separate from the streaming UI output. Also, when building workflows around Terraform, the machine readable output can be used to automation purposes, which `terraform show -json` provides.

You may also find the [Running Terraform in Automation](https://learn.hashicorp.com/tutorials/terraform/automate-terraform) documentation helpful.

**Comment by fardin01** [comment]
Hi @jbardin,

Thanks for your reply. I did try `terraform show` and it actually worked pretty well. Thanks again for your suggestion :)
