### ISSUE TITLE
Invalid for_each argument

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform#29924]
### Terraform Version

```
Terraform v0.14.8
```

### Terraform Configuration Files

```terraform
resource "aws_lb" "test" {
  name = "test"
  internal           = false
  load_balancer_type = "application"
  security_groups = []
  subnets = []
}

resource "aws_wafv2_web_acl_association" "this" {
  for_each     = toset([aws_lb.test.arn])
  resource_arn = each.value
  web_acl_arn  = "arn:aws:wafv2:eu-west-1:012345678912:scope/webacl/name/ID"
}
```

### Expected Behavior

Plan successfully generated

### Actual Behavior

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @mgzenitech,

The key values generated in the `for_each` expression must be known in order for terraform to plan the individual resource instances. The easiest solution here is to use a map with static keys, so that the keys are known for planning purposes and the values can be derived during apply.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by mgzenitech** [comment]
@jbardin I've presented very simple example to repeatable problem. We need to have ability to do things like combining multiple lists of items and feeding them to **for_each**. Shouldn't Terraform take care of that? because this sure looks like a bug or really **must have** enhancement. If the TF can't handle simple situation presented in the example code how can we expect it to handle things like:
```terraform
concat([resourcearns....], [resourcearns....], [resourcearns])
```
Please change this to enhancement then, because this tool needs to support such workloads for really extensive and big infrastructures (we currently have about 400 resources in single workspace). We cannot do everything statically.

**Comment by jbardin** [comment]
@mgzenitech, unfortunately Terraform cannot makes things that are unknown during the plan known, which is a requirement for `for_each` keys. The concept of an `unknown` value is a core part of the language, which gives Terraform the ability to plan accurate resource changes in the face of computed resource attributes. In the case of an invalid `for_each` expression, there is nearly always some way to restructure the configuration so that you can have the keys defined without encountering the above error. If you need guidance with refactoring your configuration, the community forums are a good place to start.

Thanks!

**Comment by mgzenitech** [comment]
Found a workaround via oldschool count...
```terraform
resource "aws_lb" "test" {
  name = "test"
  internal           = false
  load_balancer_type = "application"
  security_groups = []
  subnets = []
}

resource "aws_wafv2_web_acl_association" "this" {
  count = length([aws_lb.test.arn])
  resource_arn = [aws_lb.test.arn][count.index]
  web_acl_arn  = "arn:aws:wafv2:eu-west-1:012345678912:scope/webacl/name/ID"
}
```
