### ISSUE TITLE
Latest Terraform version cannot handle indexes

### ISSUE THREAD

**Issue by ilmax** [hashicorp/terraform#29923]
Looks like I'm running into the same issue #25578 closed as fixed, I opened an issue in terraform azurerm repo (see [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/14139) that got closed because it looks like it's an issue in the core library so I'm opening the same issue here.

From azurerm issue:
>I'm seeing the same issue as #4532 I'm using an azurerm_app_service resource, current state is that the app exists but DOESN'T have MSI enabled, so my change is to add identity { type = "SystemAssigned" } to the pre-existing app service and at the same time use the app service identity to create a role assignment 

### Terraform Version
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/betr-io/mssql v0.2.2
+ provider registry.terraform.io/hashicorp/azuread v2.8.0
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.0.2
```

### Terraform Configuration Files

#Before
```hcl
resource "azurerm_app_service" "web" {
  name                = "${var.prefix}-web-backend-${var.env}"
  location            = azurerm_resource_group.backend.location
  resource_group_name = azurerm_resource_group.backend.name
  app_service_plan_id = azurerm_app_service_plan.backend.id
  https_only          = true
}
```

#After
```hcl
resource "azurerm_app_service" "web" {
  name                = "${var.prefix}-web-backend-${var.env}"
  location            = azurerm_resource_group.backend.location
  resource_group_name = azurerm_resource_group.backend.name
  app_service_plan_id = azurerm_app_service_plan.backend.id
  https_only          = true
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "web_storage_table_contributor" {
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${azurerm_storage_account.storage.resource_group_name}/providers/Microsoft.Storage/storageAccounts/${azurerm_storage_account.storage.name}"
  role_definition_name = "Storage Table Data Contributor"
  principal_id         = azurerm_app_service.web.identity[0].principal_id
}
```

### Debug Output
```
│ Error: Missing required argument
│ 
│   with module.name.azurerm_role_assignment.web_storage_table_contributor,
│   on ../../modules/name/roles.tf line 74, in resource "azurerm_role_assignment" "web_storage_table_contributor":
│   74:   principal_id         = azurerm_app_service.web.identity[0].principal_id
│ 
│ The argument "principal_id" is required, but no definition was found.

```

### Expected Behavior
Enabling managed service identity on the app service and then creating the role assignment

### Actual Behavior
terraform apply fails

### References
- #25578
- [azurerm issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/14139)

**Comment by jbardin** [comment]
Hi @ilmax,

Sorry to bounce you around here, but what you are seeing here is not caused the index expression, nor by any change in the version of terraform. The changes are not being accurately planned for the `azurerm_app_service`, which is causing the `principal_id` value to be planned as `null` when in fact it should be `unknown` at that point. This in turn is causing the schema in the provider's legacy SDK to report `Missing required argument`. 

There's not much we can do from this side, since Terraform can only apply the changes being reported by the provider.

Thanks!

**Comment by aristosvo** [comment]
Hi @jbardin 👋 

How can we fix this? Is there a way to make this value `unknown` based on certain logic on plan input parameters? Because the API cannot predict what the future actions will be towards the API, as far as I'm aware.

**Comment by jbardin** [comment]
@aristosvo, Since `identity` is a list, I think this is possible in the legacy SDK via a `CustomizeDiffFunc` for the resource. I assume the logic here is that the block

```
  identity {
    type = "SystemAssigned"
  }
```

indicates that `principal_id` will be computed. The provider however is not setting that value as computed in the plan so it remains null, hence `azurerm_role_assignment` is complaining that the value is not set. I would first try using `SetNewComputed("identity[0]. principal_id ")`, but since this is a shortcoming of the existing SDK (nested computed fields really weren't fully considered in the initial design), there's not much else that can be done until we can fully adopt the new plugin framework.
