### ISSUE TITLE
Update before destroy

### ISSUE THREAD

**Issue by barroca** [hashicorp/terraform#29925]
Hello, is it possible to change the order of terraform apply so we can update dependent resources before destroying the dependents. 

This feature would be helpful in many situations where the resources cannot be deleted since they are already being used, but some update will happen to remove that usage.

**Comment by jbardin** [comment]
Hi @barroca,

The `create_before_destroy` lifecycle argument creates this ordering of operations, since the create and update actions are logically ordered the same.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by barroca** [comment]
Thanks, It wasn't clear to me that `create_before_destroy` would have the same behavior for updating resources. Thanks for sharing. I will make sure to use the forum next time.
