### ISSUE TITLE
variable bug

### ISSUE THREAD

**Issue by Nouhailakermouss** [hashicorp/terraform#29936]
### Terraform Version

0.11
``` 
...
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output
   health_check_id:                        "${aws_route53_health_check.route53_healthcheck_v6.*.id[count.index]}"

### Expected Behavior
i expected to see a computed health check id and not the source from where he should get the id
What should have happened?
-->

### Actual Behavior

i have a resource that creates a healthcheck and i want to associate that healthcheck with a dns record but the health check id keeps showing the result up there

**Comment by SabrineMihni** [comment]
So the output of the plan was like this 
```
aws_route53_record.route53_lb_prod_use1_v4[1]
      id:                                   <computed>
      allow_overwrite:                      <computed>
      fqdn:                                 <computed>
      health_check_id:                     "${aws_route53_health_check.route53_healthcheck_v4.*.id[count.index]}"
      name:                                 "my.domaine"
      records.#:                              "1"
      records.1619650928:                    "X.X.X.X"
      set_identifier:                         "my-healthcheck-102"
      ttl:                                    "300"
      type:                                   "A"
      weighted_routing_policy.#:              "1"
      weighted_routing_policy.0.weight:       "20"
      zone_id:                                "XXXXXXXX"
```

as you can see the  ` health_check_id` in here should have something like `<computed>` but it has the literal expression used instead

**Comment by jbardin** [comment]
Hi @SabrineMihni,

I believe the output you see is correct for the version of Terraform you are using. Terraform v0.11 is very different from current releases, and most published examples are not going to match the configuration or output you will see.

Since v0.11 is no longer maintained, there wouldn't be any fixes we could offer, other than to update to a current release of Terraform. You may find some help in [the community forum](https://discuss.hashicorp.com/c/terraform-core), but honestly very few users will be familiar with or actively using v0.11.

Thanks!
