### ISSUE TITLE
The "count" value depends on resource attributes that cannot be determined because of set type of variable

### ISSUE THREAD

**Issue by adovy** [hashicorp/terraform#29944]
Terraform fails to determine resource attributes when resource has to be created with count and set type of dependant resource which also has to be created by count from Terraform v0.14, it worked on v0.13. It works with list type of variable.

### Terraform Version
```
Terraform v0.14 and later
```

### Terraform Configuration Files
```terraform
resource "null_resource" "this" {
  count = 2
}

resource "null_resource" "test" {
  count = length(toset(null_resource.this))
}
```

### Debug Output
```terraform
Error: Invalid count argument

  on main.tf line 6, in resource "null_resource" "test":
   6:   count = length(toset(null_resource.this))

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Expected Behaviour
it should create 4 null resources

### Actual Behavior
Fails to determine resource attributes

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @adovy,

Sorry about the change in behavior, but the 0.14+ output is correct -- the result of `toset(null_resource.this)` will be unknown and is not a valid argument for `count`.

There is no requirement that a multiple resource instances from a provider will always be unique, so a set of `{unknown, unknown}` could contain 1 or 2 values, which cannot be determined until after creating those resources. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
