### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by psharm53** [hashicorp/terraform#29949]
We have been using Terraform with following version configuration in AWS .
Terraform - 0.12.24
AWS Provider - 3.23.0

Sample Error -
============================================================
When applying changes to
module.peering_abc_app.aws_vpc_peering_connection.src_peering, provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

============================================================
We have been facing this error for the following resource types:
1. Route Table 
2. Subnet
3. Route Entry
4. Peering connections

Issue History -
===========
We used to get this error intermittently (5 out of 20 executions), but it used get resolved with reapply without any issues in 80% of those executions.

The executions in which the error was not resolved with reapply, we used to get error specific to resource being already available in AWS. So, the issue in those cases was that the terraform was able to create the resource in the first apply but failed to register it in the state file and as such gave conflict in second reapply. In those case, the issue was resolved with a Shell based feature automatically that destroyed the terraform, then any residual conflicting resources with shell and finally trying an apply again from scratch.

Current Status -
===========
The frequency of the issue has increased and we are not able to create the infrastructure with terraform at all without manual intervention. The issue never gets resolved with reapply or destroy and then recreate approach.
We are only able to get an infrastructure available by following the steps as follows:
1. terraform apply resulting with provider inconsistency error for few resources.
2. Manually delete the conflicting resources from AWS console , if created by first apply.
3. Execute reapply. If the error persists repeat jump to step 2.

We also attempted to use latest Provider version 3.64.2 by upgrading the terraform version to 0.12.31(To fulfill the requirements for using latest provider version), but to our surprise we started getting errors related to resource creation terraform in addition to provider in consistency errors.

**Comment by jbardin** [comment]
Hi @psharm53,

Sorry you're having trouble with this. While the error you are seeing usually indicates a problem with the provider, it certainly is possible that bugs in Terraform are triggering it. However since Terraform 0.12 is no longer being maintained, there is not much we could offer other than upgrading to a current release.

If you can recreate the issue with a current release of Terraform, please feel free to re-file the issue, along with the configuration required to reproduce it. If you have other questions, you can also find help in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!
