### ISSUE TITLE
New Outputs do not generate changes

### ISSUE THREAD

**Issue by jamesgeddes** [hashicorp/terraform#29964]
### Terraform Version

```
v0.11.11
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Created new output. Changes should have been picked up as required by the `plan`.
### Actual Behavior

On creating new output, change was ignored by the `plan`. When I executed `apply`, it also said there were no changes but created the outputs anyway.
### Steps to Reproduce

1. Create a new output
2. Run plan
3. Note that the new output is not registered by the plan
4. Run apply. Note that the new output is not registered by the plan but applied anyway.

**Comment by jbardin** [comment]
Hi @jamesgeddes,

What you are describing sounds like the expected behavior for v0.11, output values were not able to b e more precisely planned until much later Terraform releases. Since Terraform v0.11 is no longer supported, there's not much we can do to change the behavior you are seeing. All we can really suggest is working to update to a supported version of Terraform. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by jamesgeddes** [comment]
@jbardin Is this fixed in later versions then?

We are in the process of upgrading but it is taking some time.

**Comment by jbardin** [comment]
Yes, more recent releases will show output changes in the plan.
