### ISSUE TITLE
tomap() map has no element for required attribute

### ISSUE THREAD

**Issue by gidonk-pr** [hashicorp/terraform#29965]
### Terraform Version

```
1.0.11
```

### Terraform Configuration Files

```terraform
locals {
  test = {
    key    = "string_val"
    "key2" = ["list", "type"]
  }

  mybool = false
}

output "test" {
  value = local.mybool ? local.test : tomap({})
}
```

### Debug Output

https://gist.github.com/gidonk-pr/002eb18a10830947732da2bead4f03bb

### Expected Behavior
output:
```
Changes to Outputs:
  + test = {}
```

### Actual Behavior
output:
```
│ Error: Inconsistent conditional result types
│
│   on test.tf line 11, in output "test":
│   11:   value = local.mybool ? local.test : tomap({})
│
│ The false result value has the wrong type: map has no element for required attribute "key".
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hello @gidonk-pr,

Thanks for filing the issue. What the error is trying to explain is that the map must contain a key named "key" in order to be converted to an object of the correct type. The `tomap` conversion here is not valid, because the `local.test` value is not a map, nor can it be converted to a map. 

There are a few ways you could refactor this. Since we don't yet have arbitrary inline type conversions available, if you want an empty placeholder, you can use a variable with a default, e.g.

```
variable "empty" {
  type = object({
    key = string
    key2 = list(string)
  })
  default = {
    key = null
    key2 = null
  }
}

output "test" {
  value = local.mybool ? local.test : var.empty
}
```

Or in most cases, simply using a `null` false value will suffice.

```
output "test" {
  value = local.mybool ? local.test : null
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by gidonk-pr** [comment]
Hi.

@jbardin- Thanks for the response :)
Can you please explain in a little more details what do you mean by "The tomap conversion here is not valid, because the local.test value is not a map, nor can it be converted to a map" - because as far as I am concerned this local is a key-value pairs and most definitely should be regarded as a map.

Moreover- I still think this should be opened as a bug- for two main reasons:

**1. inconsistency -** 
following your explanation- these examples shouldn't work either (but they do):
 ```terraform
locals {
  test = {
    key    = ["list", "string"]
    "key2" = ["another", "list"]
  }

  mybool = false
}

output "test" {
  value = local.mybool ? local.test : tomap({})
}
```
and nor should this:
```terraform
locals {
  test = {
    key    = "string"
    "key2" = "another string"
  }

  mybool = false
}

output "test" {
  value = local.mybool ? local.test : tomap({})
}
```
it is only when mixing primitive and complex types when the error is triggered

**2. null keys are still counted** 
```terraform
locals {
  test = {
    key    = null
    "key2" = null
  }
}

output "null_keys" {
  value = length(local.test)
}

output "empty_map" {
  value = length(tomap({}))
}
```
will yield the following result (also when using your empty variable example):
```
Changes to Outputs:
  + empty_map = 0
  + null_keys = 2
  ```
this one becomes a crucial (and is how I encountered this issue) when passing values to external modules or being used towards count or for_each (e.g `for_each = length(local.test) == 0 ? {whatever = 1} : local.test`)

I would also like to point out that relying on user variable is not always an option because sometimes the maps are created in locals from multiple variables- (and I am not aware that locals can be used with `type` like a variables)

**Comment by jbardin** [comment]
Hi @gidonk-pr,

I think the misunderstanding here is likely related to the type system itself. The type of the variable in your original example must be an object, not a map.  A map type consists of only a single element type, but your first example has 2 different element types, `string` and `list(string)`, which means it can only be described as an object containing exactly 2 keys:

``` 
  type = object({
    key = string
    key2 = list(string)
  })
```

Your first example does work precisely because you have consistent element types, which means a `map(list(string))` type constraint can be applied, and `tomap({})` can be converted to a compatible type. Terraform will try to convert objects and maps to a common unifying type when possible, but in this case it's not possible, so we get the error shown.

I'm not entirely sure what you mean by "null keys are still counted", the keys are defined as part of the type, which will initially have a type constraint of `object({key=any,key2=any})`. The null value has no inherent type, but it does not delete the key from the inferred type. Because the type constraint for the object can be converted to a valid map, the conditional expression with the null values would succeed. 

I agree that relying on a variable to create a specific type is not optimal. Due to the original Terraform language design we are not able to introduce direct inline type declarations and conversions yet, but would like to design a solution for that in a future language edition. In the meantime, typed variables, and sometimes even helper modules can be used to enforce required type constraints in the few cases where type inference does not match the users intent.

**Comment by gidonk-pr** [comment]
okay- fair enough

then might I suggest modifying the length() function that will return 0 on an object that all its values are null?

meaning that following my previous example:

```terraform
locals {
  test = {
    key    = null
    "key2" = null
  }
}

output "null_keys" {
  value = length(local.test)
}

output "empty_map" {
  value = length(tomap({}))
}
```
will yield the result of:
```
Changes to Outputs:
  + empty_map = 0
  + null_keys = 0
```
instead of:
```
Changes to Outputs:
  + empty_map = 0
  + null_keys = 2
```

alternatively, maybe adding a new `isempty()` function?

there must be a way to test if an object is null\empty..

**Comment by jbardin** [comment]
Hi @gidonk-pr,

A key with a `null` value in a map is still an element in the map, and therefore must be counted as part of its length property.
You can however construct arbitrary filters with "for expressions", so from your example:

```
output "null_keys" {
  value = length({ for k, v in local.test : k => v if v != null })
}
```

will output `null_keys = 0`
