### ISSUE TITLE
Migrate from local state to S3 fails if an AWS profile is specified

### ISSUE THREAD

**Issue by gbisaga** [hashicorp/terraform#29963]
### Terraform Version

```
Terraform v1.0.7
```

### Terraform Configuration Files

```terraform
provider "aws" {
    region = "us-east-1"
    profile = "qa"
}
```

### Debug Output

https://gist.github.com/gbisaga/150ae17d50139c6a80ec2c3dd6166f54

### Expected Behavior

I would expect it to migrate from local state to remote S3 state.

### Actual Behavior

It fails with a 403 error on s3/ListObjects.

### Steps to Reproduce

```
terraform init
```

If I remove the `profile` from the AWS provider and set up my default AWS credentials to be the same as the `qa` profile, it does the migration successfully.

**Comment by jbardin** [comment]
Hi @gbisaga,

Thanks for filing the issue. This is quite puzzling, because what you have shown here is a provider configuration, which is entirely separate from the backend configuration. The shown configuration is not even used within the same process, and is only sent to the aws provider plugin; are you also setting the `AWS_PROFILE` environment variable?

Since you state that you are attempting to migrate to the s3 backend, can you show the backend configuration you using? Since we know that configured AWS profiles are working for other users, it would help to have a complete, reproducible example showing everything that is going on here from scratch.

Thanks!

**Comment by gbisaga** [comment]
Ah... I think that may be the answer. I thought I was giving you the full example, but I was assuming the backend configuration used the provider configuration in terms of telling it which AWS profile to use. In the backend configuration, I'm specifying S3 and the region, but NOT the profile. I'd never seen an example of an S3 backend configuration that specifies credentials or a profile, but now looking at the reference page I see that you can. Most likely if I had specified the profile for the backend also, it would have worked. Thanks for the response, I think this is the answer!
