### ISSUE TITLE
terraform 0.12 join function doesn't interpret escape quotes properly

### ISSUE THREAD

**Issue by tinder-terrychu** [hashicorp/terraform#29974]
### Terraform Version
```
v0.12.31
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

We currently have a terraform template where a snippet of the template looks like this:
```
 identifiers = [
        "${join("\",\"", data.terraform_remote_state.region.outputs.iam_provider_role_arns)}",
      ]
```
where the variable `data.terraform_remote_state.region.outputs.iam_provider_role_arns` is a regular list like `[arn1, arn2, arn3]`.

### Expected Behavior
The terraform plan output should be like this for the result of the join function:
```
 Principal = {
    AWS = "arn1", "arn2", "arn3"
}
```

### Actual Behavior
The terraform plan output shows the result of the join function like this 
```
 Principal = {
    AWS = "arn1\",\"arn2\",\"arn3"
}
```

### Additional Context
I tried using double backslash quotes `\\"` and triple backslash quotes `\\\"` and none of worked either. Was wondering if I am doing something or this is a bug?

**Comment by jbardin** [comment]
Hi @tinder-terrychu,

The output you are showing matches exactly what you have passed in, 3 strings joined by `", "`, which means the first and last elements will have no opening or closing quotes. If you want those, you would need to add them to the template string:

```
"\"${join("\",\"", data.terraform_remote_state.region.outputs.iam_provider_role_arns)}\""
```

Can you show an example of how you are intending to use the output value? The output you are showing does not match the format of any data structures used by terraform, and if you want a single string, the output is going to quote the string. In this sense you are either going to get a list of strings, like 

```
  AWS = ["arn1", "arn2", "arn3"]
```

or a single string, like
```
  AWS = "\"arn1\", \"arn2\", \"arn3\""
```

And if you want valid json, which is difficult to do with templating because of the trailing comma rule, you can use the `jsonencode` function:

```
jsonencode(data.terraform_remote_state.region.outputs.iam_provider_role_arns)
```

But 3 separate comma separated strings is not something that you can force Terraform to generate. However since that is only the human readable output, the format doesn't particularly matter, only the actual data structure you need to retrieve as an output, pass to another resource or module argument.

Since this issue doesn't represent a bug in Terraform itself, I'm going to close it out for now. If you have more questions, feel free to reply here, but it's usually better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. 

Thanks!
