### ISSUE TITLE
Filtering of a list during construction

### ISSUE THREAD

**Issue by phatcher** [hashicorp/terraform#29981]
### Current Terraform Version

```
1.0.9
```

### Use-cases

I'm trying to filter a list of Azure locations to pick out the primary ones; primary location in this sense is the first location of a region pair that is in the list e.g. given a list `[ 'westeurope', 'northeurope' ] ` the resulting list should be ` [ 'westeurope' ]`.

So to solve this in the general case, I need to look at the partially generated new list to see if the current value's pair is already present and I can't come up with a syntax/method that works.

### Attempted Solutions

```
locals {
  pairs = {
    # Europe
    northeurope        = "westeurope"
    westeurope         = "northeurope"

    # UK
    uksouth            = "ukwest"
    ukwest             = "uksouth" 

    # Plus lots more ignored for brevity
  }
```

#### Just filter even indices  
```
primaries = [ for x, index in var.locations : x if index / 2 = 0 ]
```
Requires you to put the items in the correct order i.e. would work for  `[ 'westeurope', 'northeurope', 'uksouth', 'ukwest' ] `  but would provide an incorrect response for `[ 'westeurope', 'uksouth', 'northeurope', 'ukwest' ] `

**Comment by jbardin** [comment]
Hello,

Thanks for filing the issue. It sounds like you are asking how to structure the data here rather than for a specific feature. The general "for expressions" in the configuration language do allow one to construct arbitrary filters for the given data. Seeing how you have a map of key value pairs defining the desired locations, it seems you should be able to reorganize that structure to suit your needs.

If I understand correctly what you are describing, the problem is that you need to somehow group items which may be supplied in any order. Since you are already required to define these pairs of values, you could iterate over those to group the values and then pick the first of each pair, e.g.

```
locals {
  regions = {
    europe = ["northeurope", "westeurope"]
    uk     = ["ukwest", "uksouth"]
  }

  locations = [ "westeurope", "uksouth", "northeurope", "ukwest" ]

  ordered = flatten([ for k, v in local.regions : 
    [ for location in local.locations : location if contains(v, location) ]
  ])

  primaries = [ for i, v in local.ordered : v if (i % 2) == 0 ]
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
