### ISSUE TITLE
Terraform version upgrade from 0.14.3 to 1.0.11 adds empty string arguments or other optional arguments with default values

### ISSUE THREAD

**Issue by mavlesv** [hashicorp/terraform#30024]
We found the below code drift when the Terraform version upgrade is done from 0.14.3 to latest 1.0.11. 
We observed the terraform plan adding empty string arguments as below. But when applied for Virtual machines, we didnt see any Infra changes. Would it be safe to proceed to apply the below changes to all resources.

**Virtual Machine (windows/ linux)**
availability_set_id             = ""
dedicated_host_id               = ""
eviction_policy                 = ""
license_type                    = ""
proximity_placement_group_id    = ""
public_ip_address               = ""
source_image_id                 = ""
virtual_machine_scale_set_id    = ""

**Windows VM**
vtpm_enabled              = false
secure_boot_enabled   = false

**Storage Account**
queue_encryption_key_type      = "Service"
table_encryption_key_type      = "Service"

**Data Disk**
on_demand_bursting_enabled = false

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. If you do so, it would help to provide the full output of the Terraform command as printed on the console. Thanks!
