### ISSUE TITLE
Refresh state doesn't load dynamic provider config

### ISSUE THREAD

**Issue by zhenik** [hashicorp/terraform#30021]
Project with issue https://github.com/zhenik/terraform-nomad-acl-test to be able run locally. (require vagrant)

### Terraform Version
terraform version 0.14.9

### Nomad Version
Nomad 1.0.2
Vault 1.6.1

### Provider Configuration
```
terraform {
  required_version = "~> 0.14.0"
  required_providers {
    nomad = {
      version = "1.4.15"
    }
    vault = {
      version = "2.24.0"
    }
    time = {
      version = "0.7.2"
    }
  }
}
```
### Environment Variables
no

### Affected Resource(s)
```
❯ terraform state list
data.vault_generic_secret.nomad_bootstrap_token
nomad_acl_policy.dev
...
```

### Terraform Configuration Files
`main.tf`
```terraform
provider "vault" {
  token = "master"
  address = "http://127.0.0.1:8200"
}

module "some_dependency" {
  source = "./terraform-some-dependency"
//  wait_time = "1s"
}

data "vault_generic_secret" "nomad_bootstrap_token" {
  depends_on = [
    module.some_dependency
  ]
  path = "secret/example/nomad-bootstrap-token"
}

# Configure the Nomad provider
provider "nomad" {
  alias     = "bootstrap_token"
  address = "http://127.0.0.1:4646"
  secret_id = data.vault_generic_secret.nomad_bootstrap_token.data["secret-id"]
}
resource "nomad_acl_policy" "dev" {
  provider = nomad.bootstrap_token
  name        = "tezt1"
  description = "Submit jobs to the dev environment."
  rules_hcl = <<EOT
namespace "dev" {
  policy = "write"
}
EOT
}
```

`terraform-some-dependency/main.tf`

```terraform
variable "wait_time" {
  default = "2s"
}
resource "time_sleep" "simulate_nomad_vm_deploy" {
  create_duration = var.wait_time
}
```

### Debug Output
https://gist.github.com/zhenik/2bbaa8190e385ccc85176e960619ba4b 

### Expected Behavior
Refreshing state without successful for the resource `nomad_acl_policy.dev`

### Actual Behavior
Fail on refreshing state of resource `nomad_acl_policy.dev` due to token Nomad ACL bootstrap token

Error: error checking for ACL policy "tezt1": &errors.errorString{s:"Unexpected response code: 403 (Permission denied)"}

### Steps to Reproduce
Prerequisites. You need running vault and nomad cluster. Nomad cluster is integrated with nomad via nomad secret backend.
1. `terraform init && terraform apply`
```terraform
module.some_dependency.time_sleep.simulate_nomad_vm_deploy: Creating...
module.some_dependency.time_sleep.simulate_nomad_vm_deploy: Creation complete after 2s [id=2021-09-27T09:30:16Z]
data.vault_generic_secret.nomad_bootstrap_token: Reading...
data.vault_generic_secret.nomad_bootstrap_token: Read complete after 0s [id=secret/example/nomad-bootstrap-token]
nomad_acl_policy.dev: Creating...
nomad_acl_policy.dev: Creation complete after 0s [id=tezt1]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```
2. Deployment is successful. terraform exit 0
3. Uncomment line 8 in [main.tf](main.tf)
```terraform
//  wait_time = "1s"
```
to
```terraform
wait_time = "1s"
```
4. `terraform apply`
```
❯ terraform apply
module.some_dependency.time_sleep.simulate_nomad_vm_deploy: Refreshing state... [id=2021-09-27T09:30:16Z]
nomad_acl_policy.dev: Refreshing state... [id=tezt1]

Error: error checking for ACL policy "tezt1": &errors.errorString{s:"Unexpected response code: 403 (Permission denied)"}
```

**Comment by lgfa29** [comment]
Hello Terraform team 👋 

This issue was initially opened against the Nomad Terraform provider, but after further investigation I believe the root cause is an issue in Terraform itself. 

I transferred the issue in order to retain the full context, including @zhenik great reproduction environment.

After a `git bisect` ([log](https://gist.github.com/lgfa29/d3e503b13e5e6a508eddbdbb816e2aa7) for reference) I reached this commit as the first bad one: https://github.com/hashicorp/terraform/commit/be757bd41657a758c9a6edffe3f0b6486a79e8d3 (you will need to apply the changes from 8cef62e45593d553e249685b3199100ffc0748f8 to build properly).

I also verified that this is still an issue in Terraform `v1.0.11` and `1.1.0-beta2`

Thanks!

**Comment by jbardin** [comment]
Hi @zhenik,

Unfortunately the configuration as shown was exploiting a bug in prior versions of Terraform which allowed data sources to be read even if they were going to return stale data. Adding `depends_on=[module.some_dependency]` to the data source is indicating that the data source should not be read until any changes within `module.some_dependency` have been resolved. This means that the change to the `time_sleep.simulate_nomad_vm_deploy` is preventing `data.vault_generic_secret.nomad_bootstrap_token` from being read during the plan, and supplying an unknown value to the the nomad provider `secret_id`. This also happens during the initial apply, however there are no resources yet to be refreshed, so there is no error.

Can you provide some more information about the actual use case, and why the `depends_on` was originally added to the data source?

**Comment by lmjelstad** [comment]
Hello @jbardin,

I'v had a look at our code, and I'm starting to wonder if the `depends_on` in `vault_generic_secret` is added because we have operated with a mindset that "ACL, and therefor everything related to ACL, must be set up after the VM has been deployed". I do not see any reason why the `data.vault_generic_secret.nomad_bootstrap_token` depends on the creation of the VM. 

I tried to remove the `depends_on` in the `data.vault_generic_secret.nomad_bootstrap_token` resource and re-deployed Nomad. Everything works as it should. We ran into this problem when we tried to upgrade terraform from version 0.13.5 to 0.14.0, so I tried to go through this upgrade as well. After the upgrade I triggered a new re-delpoy of the VM, and did not run into any problems with reading the bootstrap token. 

I will continue testing upgrading Nomad towards Terraform 1.0.x, but I think you can close this issue for now. Thank you so much for your help!

**Comment by jbardin** [comment]
Thanks for the follow up @lmjelstad!
