### ISSUE TITLE
Dependency not calculated correctly when using conditional operator

### ISSUE THREAD

**Issue by ribeiroh** [hashicorp/terraform#30032]
### Terraform Version

```
0.14.11
```

### Terraform Configuration Files

```terraform
locals {
  use_personal_role_boundary = true => false
}

data "terraform_remote_state" "default_permission_boundary" {
  backend = "local"
  config = {
    path = "path/to/aws_iam_policy/resource.tfstate"
  }
}

resource "aws_iam_policy" "custom_permission_boundary" {
  count = local.use_personal_role_boundary ? 1 : 0
  name = "custom_permission_boundary"
  policy = file("policy.json")
}

resource "aws_iam_role" "service_role" {
  [...]
  permissions_boundary = local.use_personal_role_boundary ? aws_iam_policy.custom_permission_boundary[0].arn : data.terraform_remote_state.default_permission_boundary.outputs.policy_arn
}
```

### Expected Behavior
When changing `local.use_personal_role_boundary` from `true` to `false`
```terraform
 # aws_iam_policy.custom_permission_boundary[0] will be destroyed
  - resource "aws_iam_policy" "custom_permission_boundary" {
        #
    }

  # aws_iam_role.service_role will be updated in-place
  ~ resource "aws_iam_role" "service_role" {
        #
      ~ permissions_boundary  = "arn:aws:iam::000000000000:policy/custom_permission_boundary" -> "arn:aws:iam::000000000000:policy/default_permission_boundary"
    }

aws_iam_role.service_role: Modifying... [id=xxxxxxxx]
aws_iam_role.service_role: Modifications complete [id=xxxxxxxx]
aws_iam_policy.custom_permission_boundary[0]: Destroying...[id=arn:aws:iam::000000000000:policy/custom_permission_boundary]

```
### Actual Behavior
When changing `local.use_personal_role_boundary` from `true` to `false`
```terraform
 # aws_iam_policy.custom_permission_boundary[0] will be destroyed
  - resource "aws_iam_policy" "custom_permission_boundary" {
        #
    }

  # aws_iam_role.service_role will be updated in-place
  ~ resource "aws_iam_role" "service_role" {
        #
      ~ permissions_boundary  = "arn:aws:iam::000000000000:policy/custom_permission_boundary" -> "arn:aws:iam::000000000000:policy/default_permission_boundary"
    }

aws_iam_policy.custom_permission_boundary[0]: Destroying...[id=arn:aws:iam::000000000000:policy/custom_permission_boundary]

Error: error deleting IAM policy arn:aws:iam::000000000000:policy/custom_permission_boundary: DeleteConflict: Cannot delete a policy attached to entities.
        status code: 409, request id: xxxxx
```

### Steps to Reproduce

1. Use a conditional operator to define the creation **and** use of a dependency on a resource
2. Flip the condition

### Additional Context

I was unable to tell if this issue has to do specifically with the AWS provider, but I would think it's unlikely. The example with AWS resources is just for illustration purposes.

Basically, I'm experiencing an issue with the way Terraform has built a dependency graph for applying this change. Here are a few details:
- `local.use_personal_role_boundary` set to `true`
- During resource creation, the implicit dependency on `aws_iam_policy.custom_permission_boundary` is correctly handled, and that resource is created prior to `aws_iam_role.service_role`;
- When `local.use_personal_role_boundary` is set to `false`, the dependency that `aws_iam_role.service_role` has on  `custom_permission_boundary` moves over to `data.terraform_remote_state.default_permission_boundary.outputs.policy_arn`. However, this should only be true once the `apply` is finished.
- Apparently, Terraform discards the dependency on `aws_iam_policy.custom_permission_boundary[0].arn` prior to building the dependency graph, which means that Terraform attempts to destroy `aws_iam_policy.custom_permission_boundary` prior to detaching it from the role. In this specific case, this fails because AWS doesn't let you do that. However, I believe this shouldn't happen anyway, and the dependant resource should be processed prior to the dependency being removed.

**Comment by alisdair** [comment]
Hi @ribeiroh, thanks for the report. Since the behaviour you're looking for is that the `aws_iam_role` is updated before the `aws_iam_policy` is destroyed, try using [the `create_before_destroy` lifecycle option](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#create_before_destroy) on the `aws_iam_policy` to invert the dependency order.

Terraform cannot always know which resource needs to be updated first in situations like these, which is why the `create_before_destroy` option exists so that you can control the behaviour. This looks like normal Terraform behaviour to me, so unless I'm misunderstanding I don't think there's a bug here.

**Comment by ribeiroh** [comment]
Hey @alisdair,

I can confirm that I've already attempted that, but Terraform will still attempt to destroy the `aws_iam_policy` first. As a matter of fact, thinking that I was maybe getting the concepts wrong, I ended up trying all combinations you could think of:
- `create_before_destroy` on the `aws_iam_policy`;
- `create_before_destroy` on the `aws_iam_role`;
- `create_before_destroy` on both.

I've also tried to force a dependency by adding `depends_on` on the `aws_iam_role` resource. No luck.

**Comment by alisdair** [comment]
Hi @ribeiroh. I'm not sure what's happening for you, but I can't reproduce the problems you're seeing.

The original report does not have a complete reproduction in full detail, and without that it's possible that we're seeing different problems. But I spent some time this morning creating as close of a reproduction as I could. See below:

```terraform
variable "use_alternate" {
  type = bool
  default = false
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_role" "default" {
  name = "tf-30032-role-default"

  managed_policy_arns = [
    var.use_alternate ? aws_iam_policy.alternate[0].arn : aws_iam_policy.default.arn
  ]
  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "s3.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}

resource "aws_iam_policy" "default" {
  name = "tf-30032-policy-default"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetReplicationConfiguration",
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::test"
      ]
    }
  ]
}
POLICY

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_iam_policy" "alternate" {
  count = var.use_alternate ? 1 : 0
  name = "tf-30032-policy-alternate"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::test"
      ]
    }
  ]
}
POLICY

  lifecycle {
    create_before_destroy = true
  }
}
```

The following steps are attempts to reproduce:

1. `terraform init`
2. `terraform apply`: creates the default policy and role
3. `terraform apply -var use_alternate=true`: creates the alternate policy and updates the role
4. `terraform apply -var use_alternate=false`: updates the role and deletes the alternate policy

These steps all succeed. If you remove the `lifecycle` settings from the policies, they fail due to the ordering issue you saw.

Note that if you change the lifecycle of an extant resource, you must run `terraform apply` with no changes to update the state with the new dependencies. Perhaps that's why you weren't seeing the desired behaviour.

If you can provide a complete reproduction of the issue, with all the steps/resources needed for us to see what you're seeing, I'd be happy to take another look.
