### ISSUE TITLE
inconsistency between "for_each" and "count"

### ISSUE THREAD

**Issue by shaunc** [hashicorp/terraform#30039]
### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
```

### Terraform Configuration Files

Here, `cluster_asg_names` are created by module [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)

```terraform
data "aws_autoscaling_group" "asgs" {
  for_each = { for name in var.cluster_asg_names : name => name }
  name      = each.value
}
```
vs
```terraform
data "aws_autoscaling_group" "asgs" {
 count  = length(var.cluster_asg_names)
  name = var.cluster_asg_names[count.index]
}

```
### Expected Behavior

The blocks are functionally the same; they should result in the same data elements, except that the first one labels the resources by name, while the second one labels them by index. If the names are cannonical, the first should be better
practice, as the creation order (or whatever other criteria) may be arbitrary.

### Actual Behavior

The second resource works; the first fails with:

```
The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform
cannot predict how many instances will be created. To work around this, use the -target argument to first
apply only the resources that the for_each depends on.
```

### Steps to Reproduce

n/a

### References

According to [Martin Atkins blog post](https://log.martinatkins.me/2021/06/14/terraform-plan-unknown-values/),  the failure of the `for_each` version is actually a feature, not a bug, because a plan created by the `for_each` would not be idempotent. Yet, if this is a good argument, it applies doubly so to the version with `count`, in which not only which asgs are created is not planned for, but their order, which is an arbitrary artifact, is used instead of their identity, which is even more apt to cause different outcomes on repetition. The version with for_each is arguably not declarative, but it is certainly "more declarative" than the version with count, and should be a best practice.

**Comment by jbardin** [comment]
Hi @shaunc,

This is a common question, and I'm not sure how to better frame things around the confusion some users encounter. 

Terraform requires that all resources have known addresses (i.e. names) in order to plan them, so that they can be planned, applied and correlated with existing state. The difference here is that the indexes of the `count` version are known, since they are just the numerical indexes up to `length(var.cluster_asg_names)`, while the indexes for the `for_each` version are not known, since the keys are derived from unknown values. This means the `for_each` version cannot be planned, because the actual internal names of the resources are unknown and cannot be tracked between plan an apply, nor can they be correlated with existing state.

You can see more detailed discussion in #29957.

Thanks!
