### ISSUE TITLE
File function containing templating not treated like heredocs

### ISSUE THREAD

**Issue by tculp** [hashicorp/terraform#30047]
### Terraform Version

```
1.0.9, 1.0.10, 1.0.11
```

### Terraform Configuration Files

```terraform
resource "local_file" "foo" {
//  content = <<-EOT
//%{ for node in aws_instance.nodes }
//${node.id} ansible_host=${node.public_ip}
//%{ endfor }
//EOT

  content = file("${path.module}/template")
  filename = "${path.module}/output"
}
```

### Debug Output

```
resource "local_file" "foo" {
      ~ content              = <<-EOT # forces replacement
            
          - %{ for node in aws_instance.nodes }
          - ${node.id} ansible_host=${node.public_ip}
          - %{ endfor }
          + i-018293d2aa8b16bf0 ansible_host=<redacted>
          + 
          + i-0287436da5b3c5f2a ansible_host=<redacted>
          + 
        EOT
      ~ id                   = "1027568fc23101ba707b4460c45af90e3a34bec5" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

### Expected Behavior

The output file contains the same information, regardless of whether the contents are specified inline or loaded from a file

### Actual Behavior

The output file contains rendered input when the contents are specified inline, but not when loaded from a file. As the functions do not participate in the dependency graph, I would expect the contents to be considered the same regardless of origin

### Steps to reproduce
- Have the template string in a file
- terraform apply (when contents are pulled from a file)
- the output will not be rendered
- switch to heredoc syntax
- terraform apply
- the output will be rendered

**Comment by jbardin** [comment]
Hi @tculp,

The `file` function does not render the file contents, it only supplies the value of the file contents. This contrasts with the [templatefile](https://www.terraform.io/docs/language/functions/templatefile.html)` function, which interpolates the file contents in. the same manner as string templates. Since the `file` function is working as expected here, I'm going to close the issue.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
