### ISSUE TITLE
Perpetual diff with a dynamic part of a data  resource

### ISSUE THREAD

**Issue by aglarendil** [hashicorp/terraform#30083]
Hi there, 

I have observed a rather bizarre behaviour with tf 1.0.9 and aws provider 3.68.0. It generates diff in a data resource for aws iam policy document if I have an inline dynamic "list comprehension" while if I use a "local" variable there is no diff.

### Terraform Version

```
terraform version
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
...
```

### Terraform Configuration Files
```
with_diff.tf
...
resource "aws_cloudwatch_log_group" "bazs" {
  for_each = toset(local.list_cw_groups)
  'just default values here'
}
data "aws_iam_policy_document" "cw-log-reader" {
statement {
  actions = "logs:*"
  resources = sort(concat(["foo","bar"],[for cw_lg in aws_cloudwatch_log_group]))
 }
}
resource "aws_iam_policy" "cw-log-reader" {
  policy = data.aws_iam_policy_document.cw-log-reader.json
}
```

```
without_diff.tf
...
locals {
 cw_log_groups_list = sort(concat(["foo","bar"], [for cw_log in aws_cloudwatch_log_group.cw_logs: cw_log.arn]))
}
resource "aws_cloudwatch_log_group" "bazs" {
  for_each = toset(local.list_cw_groups)
  'just default values here'
}
data "aws_iam_policy_document" "cw-log-reader" {
statement {
  actions = "logs:*"
  resources = local.cw_log_groups_list
 }
}
resource "aws_iam_policy" "cw-log-reader" {
  policy = data.aws_iam_policy_document.cw-log-reader.json
}
```

### Expected Behavior
no diff in both cases
### Actual Behavior
the first case generates a brand new AWS IAM policy document and triggers the recreation of the policy
### Steps to Reproduce

just run terraform plan  twice - you will see that the data resource gets additional diff and triggers the diff in the policy resource

**Comment by jbardin** [comment]
Hi @aglarendil,

Thanks for filing the issue, unfortunately I'm not able to replicate this with v1.0.9 or the latest release. However, since you are saying that the latter configuration is working correctly, and the only difference is the data source input is indirected through the local value, you are likely seeing the behavior documented in [Data Resource Dependencies](https://www.terraform.io/docs/language/data-sources/index.html#data-resource-dependencies)

> In order to ensure that data sources are accessing the most up to date information possible in a wide variety of use cases, arguments directly referencing managed resources are treated the same as if the resource was listed in depends_on. This behavior can be avoided when desired by indirectly referencing the managed resource values through a local value.

If any resources are still producing unexpected changes, you should file an issue with their respective provider. If you have more questions, please feel free to reply here of open a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people able to help.

Thanks!
