### ISSUE TITLE
output parameters convert list(map(string) to list(string)  

### ISSUE THREAD

**Issue by arunkumar-sankaralingam-tm** [hashicorp/terraform#30084]
I am getting output in the below type while create multiple subnets

type = list(map(string))
module_ids = [ {
            "az1" = "sn234"
            "az2" = "sn231"
            }, 
            {
                "az1" = "sn670"
                "az2" = "sn878"
            }
        ]  

I wanted to convert this into list(string) , like below in the output value itself. please suggest how to convert this 

output "list_ids" {
type = list(string)
value = **Need to convert the above type into list(string) **
}

**Comment by jbardin** [comment]
Hello,

There are lots of ways to reformat the data, so I'm not sure what you're looking for exactly. One possible example would be to take all values present in the objects and collect them into a single list:

```
  value = flatten([for m in var.module_ids :
    [for k, v in m : v]
  ])
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by arunkumar-sankaralingam-tm** [comment]
Thank you very much Sir. The above solution is worked me . thanks  a lot for the quick response.
