### ISSUE TITLE
Url in Modules documentation doesn't exist

### ISSUE THREAD

**Issue by spuder** [hashicorp/terraform#3008]
There are several places in the modules documentation that refer to URL's:

```
module "consul" {
    source = "github.com/hashicorp/consul/terraform/aws"
...
}
```

The url `github.com/hashicorp/consul/terraform/aws` doesn't exist, but `github.com/hashicorp/consul/tree/master/terraform/aws` does. 

Does this need to be changed in the docs (I'm willing to change it)? Or does terraform have some internal magic that converts the url to the right format?

**Comment by radeksimko** [comment]
Even though this code does work, URLs should be probably changed to `github.com/hashicorp/consul//terraform/aws`, since `/terraform/aws` is a subdirectory. I'm not quite sure if there's any reason we support this format without double-slashes.

See https://www.terraform.io/docs/modules/sources.html for further explanation of how it works, specifically the _"Github"_ section.

**Comment by teamterraform** [comment]
Hi @spuder! Sorry for the long silence here.

Since you opened this issue, we launched [the Terraform Registry](https://registry.terraform.io/) and we now use source addresses from there by default, unless the documentation is specifically making some point about another source type.

The current module for Consul on AWS is [`hashicorp/consul/aws`](https://registry.terraform.io/modules/hashicorp/consul/aws/0.7.1), and the URL we used to use for that (shown in the original issue) is now even more invalid than it was then, because the module isn't there at all!

Since there are no longer any references to that old URL in the Terraform docs that we could find, we're going to close this now. Sorry again for leaving this untouched for so long, and thanks for reporting it!
