### ISSUE TITLE
PopOs LInux 21.04 some rubbish when loading new shell

### ISSUE THREAD

**Issue by dodalovic** [hashicorp/terraform#30093]
After installing terraform on my PopOs LInux 21.04, I'm getting the following:

```
Error executing CLI: 2 errors occurred:
	* already installed in /home/dodalovic/.bashrc
	* already installed in /home/dodalovic/.zshrc


➜  ~ 
```

here's my .zshrc

```
.....

complete -C '/usr/local/bin/aws_completer' aws

terraform -install-autocomplete

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#autoload -U +X bashcompinit && bashcompinit

#complete -o nospace -C /usr/bin/terraform terraform

autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit && compinit
complete -o nospace -C /usr/local/bin/terraform terraform


complete -o nospace -C /usr/bin/terraform terraform
```

**Comment by jbardin** [comment]
Hi @dodalovic,

I believe that output is from the `terraform -install-autocomplete` command, which should only be run once to add the `complete` lines to the shell init files. I would remove that command from the `.zshrc` file itself, and remove whichever of the `complete` commands is incorrect from that file. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
