### ISSUE TITLE
ValidationFunc errors should contain the invalid value

### ISSUE THREAD

**Issue by tiwood** [hashicorp/terraform#30094]
```
Terraform v1.0.4
on darwin_amd64
```

### Use-cases

I have validation errors in multiple dynamic blocks, unfortunately the error message is not really helpful in finding out which `for_each` element is causing the validation to fail:

```shell
Error: invalid value for network_rule_collection.26.rule.3.name (The name must begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, underscores, periods, or hyphens.)
```

### Proposal

It would be really helpful if the diagnostics would contain the value that failed the validation and/or the `each.key/iterator` of the block. Something like this would suffice:

```shell
Error: invalid value for network_rule_collection.26.rule.3.name (The name must begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, underscores, periods, or hyphens.)

Current value: th1s i$ invalid
```

This is the ValdiationFunc that raises my current error:

https://github.com/hashicorp/terraform-provider-azurerm/blob/3d0d42b64daad6dc1634fce760ee708ec1360dd2/internal/services/firewall/firewall_policy_rule_collection_group_resource.go#L96

**Comment by apparentlymart** [comment]
Hi @tiwood! Thanks for reporting this.

The error messages you've shared here seem to be coming from the Terraform SDK rather than from Terraform Core, so I think you'd need to raise it in [the Terraform SDK repository](https://github.com/hashicorp/terraform-plugin-sdk) instead of here, since a change to achieve the result you want would be to the SDK code rather than to the Terraform Core code.

However, if what you shared here is the entirety of the error then it's interesting that the error message seems to be lacking context about which resource instance it's emerging from, which might well be a bug in Terraform Core since it ought to know which resource instance the error corresponds with. Can you confirm if there was more in those error messages that you edited out, or if that was the entire message?

**Comment by tiwood** [comment]
@apparentlymart, thanks for looking into this.

Actually there is a bit of context, but its only pointing to the resource definition:

![image](https://user-images.githubusercontent.com/6249819/145175949-9c8af469-9393-4d8f-ba75-00388859b5c7.png)

The rule in questions is actually produced by by nested for_each blocks, like so:

```hcl
resource "azurerm_firewall_policy_rule_collection_group" "test" {
  for_each = toset([
    "DEV", "TEST", "PROD"
  ])
  name               = "APPLICATION"
  firewall_policy_id = azurerm_firewall_policy.environments[each.value].id
  priority           = 5000

  dynamic "application_rule_collection" {
    for_each = var.generated_firewall_application_collections[each.value]
    iterator = collection

    content {
      name     = collection.value["Name"]
      priority = collection.value["Priority"]
      action   = collection.value["Action"]

      dynamic "rule" {
        for_each = collection.value["Rules"]

        content {
          name = rule.value["Name"]
          source_addresses = rule.value["SourceAddresses"]
          destination_fqdns = rule.value["TargetFQDNs"]2
        }
      }
    }
  }
}

```

As there is a at least the resource context, I guess I'm going to open the issue in the SDK repository?

**Comment by apparentlymart** [comment]
Thanks for confirming, @tiwood!

Indeed, the behavior you showed here seems like the correct Terraform Core response to what the SDK is returning.

One other possible enhancement on the SDK side would be for the SDK to report to Terraform (in a machine-readable way) that the problem was with the path `.application_rule_collection[0].rule[0].name`, which should then allow Terraform Core to make a better effort to highlight a more specific nested construct inside that `resource` block; Terraform Core's behavior there might be thwarted a bit by this being a `dynamic` block, but I think we'd need to see how this looks with the SDK returning a more specific attribute path before we could consider possible improvements to the error reporting in response to that.

One extra thing I'll note here for the benefit of the SDK team (since I'm assuming you'll link back to this issue in your new issue) is that although Terraform can sometimes include variable values in the error messages _itself_, appearing immediately after the source code snippet, we don't currently have that capability for errors originating inside the provider itself because we can't necessarily locate a specific expression evaluation to use for that information. We could investigate whether it's viable to make that work in this specific case, if the SDK is able to generate an attribute path referring directly to that `name` attribute here, and if you want to pursue research into that then feel free to tag me in the SDK issue and I can share some more details if needed, but I think it makes sense to discuss this in the SDK context first because addressing this would require making _some sort_ of SDK change, even if we also choose to couple it with a complementary Terraform Core change.

**Comment by apparentlymart** [comment]
Over in #31575 there is some discussion about making Terraform Core make more use of attribute path information when the provider _does_ return it, which might in turn encourage more use of that mechanism in the SDK or in providers when it's practical to do so.

Reviewing what we discussed here it doesn't seem like this issue represents some specific work that we could do in this repository and then call it "done", so I'm going to close it. The other issue I linked above might contribute indirectly to improving the situation we discussed here, but ultimately it'll be up to either the provider SDK or the provider itself to return the information that Terraform Core would use to include that additional context.

Thanks again!
