### ISSUE TITLE
Migrating from template_file to templatefile

### ISSUE THREAD

**Issue by pkleanthous** [hashicorp/terraform#30107]
Hi there,

I have migrated my configuration from `data "template_file"` to `templatefile` Function.
When I'm trying to run plan/apply on a layer that has the `template_file` inside the statefile although the code now has  `templatefile` Function, then terraform stops in the init phase with the following error.

```bash
Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be
located, don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
failed to instantiate provider "registry.terraform.io/hashicorp/template"
to obtain schema: unknown provider "registry.terraform.io/hashicorp/template"
``` 

Please note that's a clean environment and I don't have the `.terraform` directory or `.terraform.lock.hcl` file.

Is there a way to overcome this issue?

**Comment by alisdair** [comment]
Did you try running `terraform init`? The requirement for the `template` provider comes from your state file, and the plugin must still be installed.

Please note that we use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
