### ISSUE TITLE
Terraform 1.1.0 lookup regression

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform#30127]
After upgrading to terraform 1.1.0 from 1.0.11 following expression stopped working:
```
output "sg_id" {
  value = lookup(aws_security_group.lambda_default_sg, "default", { id = null })["id"]
}
```

### Expected Behavior
Plan runs fine

### Actual Behavior
```
Invalid value for "default" parameter: the default value must have the same type as the map elements.
```

**Comment by alisdair** [comment]
Hi @vladimirtiukhtin, thanks for reporting this.

To allow us to reproduce the bug, can you share more of your configuration? I assume that you are using `for_each` with the `aws_security_group.lambda_default_sg`. If so, what is the value used as the expression with the `for_each`?

Anything else you can share about your configuration might help. Thanks in advance!

**Comment by vladimirtiukhtin** [comment]
Hi @alisdair
You are totally right. I use for_each like this
```
resource "aws_security_group" "lambda_default_sg" {
  for_each = length(var.subnet_ids) > 0 ? {
    default = {}
  } : {}
  name                   = local.name_rfc1123
  description            = "${var.name} Default Security Group"
  vpc_id                 = var.vpc_id
  revoke_rules_on_delete = true
  tags = merge(
    {
      Name = "${var.name} Lambda"
    },
    local.common_tags,
    var.extra_tags
  )
}
```

**Comment by alisdair** [comment]
Thanks!

I can reproduce the same error with the following minimal config:

```terraform
provider "aws" {
  region = "us-east-1"
}

variable "subnet_ids" {
  type = list(string)
  default = []
}

variable "name" {
  type = string
  default = "repro-30127"
}

resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_security_group" "lambda_default_sg" {
  for_each = length(var.subnet_ids) > 0 ? {
    default = {}
  } : {}
  name                   = var.name
  description            = "${var.name} Default Security Group"
  vpc_id                 = aws_vpc.default.id
  revoke_rules_on_delete = true
}

output "sg_id" {
  value = lookup(aws_security_group.lambda_default_sg, "default", { id = null })["id"]
}
```

The underlying issue is that the `lookup` call is working with the resource value, which does not have the same type as the fallback value. I can't find the source of this change, but it is most likely in [the upstream `cty` library](https://github.com/zclconf/go-cty).

To construct a default value of the correct type would be quite unwieldy—you would need to specify `null` values for all the keys in the `aws_security_group` object type. Instead, you might want to use `try` instead:

```terraform
output "sg_id" {
  value = try(aws_security_group.lambda_default_sg["default"].id, null)
}
```

I'm marking this as confirmed for now, but it's possible that we might not be able to fix this, as it seems likely that this is the intended behaviour for `lookup`. Thanks again for reporting, and I hope the workaround above is helpful.

**Comment by apparentlymart** [comment]
Hi @vladimirtiukhtin,

Can you confirm whether you were able to _apply_ a plan based on this expression in Terraform v1.0? Terraform v1.1 does include some enhancements to detect certain type inconsistencies sooner (during the plan phase rather than during the apply phase) but we had not intended to introduce any _new_ checks, only to make existing checks happen earlier.

This expression is invalid per the implementation of `lookup`, as @alisdair noted, so if you _were_ able to apply a change containing this expression under Terraform v1.0 then I think our next step would be to try to explain why that is, since that would suggest that there was a previously-undetected bug in Terraform v1.0 which we have inadvertently "fixed" now, and we'll need to therefore do some analysis to try to understand the relative impact between preserving that bug for compatibility or fixing the bug, considering this as a "late-reported regression" as described in [the pragmatic exceptions to our Terraform v1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html#pragmatic-exceptions) after we've understood how many versions that bug had been present.

**Comment by vladimirtiukhtin** [comment]
Hi @apparentlymart. Yes, as I mentioned at the beginning, this expression runs perfectly fine on terraform 1.0.11

**Comment by xlz-jgoutin** [comment]
Hello,

I have something similar here, with a type check error in 1.1.0 that worked perfectly previously:

```
│ Error: Inconsistent conditional result types
│ 
│   on agent.tf line 144, in locals:
│  144:   _instances = var.spot ? aws_spot_instance_request.agent : aws_instance.agent
│     ├────────────────
│     │ aws_instance.agent is a list of object, known only after apply
│     │ aws_spot_instance_request.agent is a list of object, known only after apply
│     │ var.spot is a bool, known only after apply
│ 
│ The true and false result expressions must have consistent types. The given
│ expressions are list of object and list of object, respectively.
```
Source code here: https://github.com/Accelize/acid/blob/48639cb0006493612c42e083cd30b254e9f32543/agents/awsEc2/agent.tf#L144

Depending the condition, the object can be "aws_instance" or "aws_spot_instance_request".

**Comment by ocofaigh** [comment]
We are also seeing this...

`acl_id          = lookup(ibm_is_network_acl.multizone_acl, each.key, { id : null }).id`

is giving:
```
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/vpc/main.tf line 66, in module "vpc_subnets":
│   66:   acl_id          = lookup(ibm_is_network_acl.multizone_acl, each.key, { id : null }).id
│ 
│ Invalid value for "default" parameter: the default value must have the same
│ type as the map elements.
╵
```

Works fine on version 1.0.11
