### ISSUE TITLE
terraform 1.1.0 Error: missing or corrupted provider plugins

### ISSUE THREAD

**Issue by wael-sadek** [hashicorp/terraform#30122]
Terraform version

```
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v3.0.1
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

Expected Behavior, terraform validate
```
Success! The configuration is valid.
```
Actual Behavior, terraform validate
```
Error: missing or corrupted provider plugins:
  - registry.terraform.io/hashicorp/null: there is no package for registry.terraform.io/hashicorp/null 3.1.0 cached in .terraform/providers
  - registry.terraform.io/hashicorp/template: there is no package for registry.terraform.io/hashicorp/template 2.2.0 cached in .terraform/providers
```

I've tried both `terraform init` and `terraform init -upgrade` both pass but I still get the same error from `terraform validate`.
The old terraform 1.0.11 works fine. Interestingly it doesn't download those plugins it complained about in the new version (1.1.0). 
The below is for version 1.0.11 which works

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v3.0.1
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```
As you can see from the below those plugins are not there. However the validate passes just fine.

ls -l .terraform/providers/registry.terraform.io/hashicorp/
```
total 0
drwxr-xr-x 1 wael wael 4096 Dec  9 12:25 aws
drwxr-xr-x 1 wael wael 4096 Dec  9 12:01 cloudinit
drwxr-xr-x 1 wael wael 4096 Dec  9 12:26 helm
drwxr-xr-x 1 wael wael 4096 Dec  9 12:26 kubernetes
drwxr-xr-x 1 wael wael 4096 Dec  9 12:01 local
drwxr-xr-x 1 wael wael 4096 Dec  9 12:01 random
drwxr-xr-x 1 wael wael 4096 Dec  9 12:26 vault
```

**Comment by apparentlymart** [comment]
Hi @wael-sadek! Sorry for this strange behavior, and thanks for reporting it.

You mentioned that under Terraform v1.0.11 you were able to validate this configuration in spite of the `hashicorp/null` and `hashicorp/template` providers not being installed. I'm not sure how to explain that yet, since validation typically starts each provider plugin to ask it to validate the provider configuration and any resource configurations.

Does your configuration contain at least one resource from each of those providers? Specifically, I'm wondering if what might be happening here is that you have a `required_providers` block declaring a dependency but no actual usage of the provider, which may therefore confuse Terraform about whether those providers are actually required.

It is definitely a bug that `terraform init` didn't install everything that `terraform validate` needs to do its work, so even if what I asked above _is_ true that would still be a problem for us to fix rather than a problem on your end, but having that explanation would help narrow down our efforts in creating a reproduction case we can test against. Thanks!

**Comment by wael-sadek** [comment]
Thanks @apparentlymart , no I'm not using any of those two directly, but I'm using modules that might use them.
Surely `.terraform.lock.hcl` has all of the modules listed including the `hashicorp/null` and `hashicorp/template`.
Should I remove both entries manually from the file ?

You may find the below output interesting
For terraform v1.0.11

```
terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/kubernetes]
├── provider[registry.terraform.io/hashicorp/aws]
├── provider[registry.terraform.io/hashicorp/helm]
├── provider[registry.terraform.io/hashicorp/vault]
├── module.postgres
│   ├── module.allow_postgres
│   │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
│   └── module.postgres
│       ├── provider[registry.terraform.io/hashicorp/random] >= 3.1.0
│       ├── provider[registry.terraform.io/hashicorp/aws] >= 2.49.0
│       ├── module.db_instance
│           ├── provider[registry.terraform.io/hashicorp/random] >= 2.2.0
│           └── provider[registry.terraform.io/hashicorp/aws] >= 2.49.0
│       ├── module.db_option_group
│           └── provider[registry.terraform.io/hashicorp/aws] >= 2.49.0
│       ├── module.db_parameter_group
│           └── provider[registry.terraform.io/hashicorp/aws] >= 2.49.0
│       └── module.db_subnet_group
│           └── provider[registry.terraform.io/hashicorp/aws] >= 2.49.0
├── module.vpc
│   ├── provider[registry.terraform.io/hashicorp/aws]
│   ├── module.allow_endpoints
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
│   ├── module.endpoints
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.28.0
│   └── module.vpc
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.63.0
├── module.acm
│   └── provider[registry.terraform.io/hashicorp/aws] >= 2.53.0
├── module.allow_ssh
│   └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
├── module.cluster_dev
│   ├── provider[registry.terraform.io/hashicorp/helm]
│   ├── provider[registry.terraform.io/hashicorp/aws]
│   ├── provider[registry.terraform.io/hashicorp/kubernetes]
│   ├── module.allow_ssh
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
│   ├── module.cluster
│       ├── provider[registry.terraform.io/hashicorp/kubernetes] >= 1.11.1
│       ├── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
│       ├── provider[registry.terraform.io/terraform-aws-modules/http] >= 2.4.1
│       ├── provider[registry.terraform.io/hashicorp/aws] >= 3.56.0
│       ├── provider[registry.terraform.io/hashicorp/local] >= 1.4.0
│       ├── module.node_groups
│           ├── provider[registry.terraform.io/hashicorp/cloudinit] >= 2.0.0
│           └── provider[registry.terraform.io/hashicorp/aws] >= 3.56.0
│       └── module.fargate
│           └── provider[registry.terraform.io/hashicorp/aws] >= 3.56.0
│   ├── module.nlb_ingress
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
│   └── module.allow_efs
│       └── provider[registry.terraform.io/hashicorp/aws] >= 3.0.0
└── module.nlb_dev
    └── module.load_balancer
        └── provider[registry.terraform.io/hashicorp/aws] >= 3.40.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/vault]

    provider[registry.terraform.io/terraform-aws-modules/http]

    provider[registry.terraform.io/hashicorp/helm]

    provider[registry.terraform.io/hashicorp/kubernetes]

    provider[registry.terraform.io/hashicorp/aws]
```

But running it with terraform 1.1.0
```
 terraform providers -no-color

Error: Required plugins are not installed

The installed provider plugins are not consistent with the packages selected in the dependency lock file:
  - registry.terraform.io/hashicorp/null: there is no package for registry.terraform.io/hashicorp/null 3.1.0 cached in .terraform/providers
  - registry.terraform.io/hashicorp/template: there is no package for registry.terraform.io/hashicorp/template 2.2.0 cached in .terraform/providers

Terraform uses external plugins to integrate with a variety of different infrastructure services. To download the plugins required for this configuration,
run:
  terraform init
```

**Comment by apparentlymart** [comment]
Hi @wael-sadek! Thanks for that additional information.

I find it interesting that there's no mention of `hashicorp/null` or `hashicorp/template` anywhere in the `terraform providers` output.

My new theory is that perhaps an earlier version of one of these modules _did_ depend on these providers, but the current versions do not. However, Terraform's still seeing the original lock file entries in `.terraform.lock.hcl` and so believing them to be needed _at runtime_ even though the provider installer can see that they aren't actually required anymore.

Could you have a look in your `.terraform.lock.hcl` file and see if you have entries for these two providers? If so, could you try deleting the two blocks for those and running `terraform init` again? If my theory is correct, I would expect `terraform init` to work after you've removed those two blocks, and it also should not automatically _re-add_ those providers to the lock file because they are no longer needed.

If this theory turns out to be true then I think the work here will be to either make sure `terraform init` proactively removes unneeded providers from the lock file _or_ to make the runtime code which checks consistency of the lock file also take into account the current requirements, ignoring anything that isn't currently required. The advantage of the second option would be that temporarily removing a provider accidentally and re-adding it wouldn't cause the lock file entry to "reset" and potentially change the checksums, but that scenario seems relatively unlikely and should be detectable by noticing unexpected changes to the lock file during code review, and so I would lean towards the first option of having `terraform init` automatically keep the lock file clean of anything that's no longer required.

**Comment by wael-sadek** [comment]
Hi @apparentlymart , yes, removing the two blocks from `.terraform.lock.hcl` solved the problem. Now everything works just fine!

**Comment by apparentlymart** [comment]
Great, thanks for confirming!

Given that then, my proposal to address this is to change `terraform init` so that it will, unless running in the mode where it is forced to treat the lock file as read-only, remove blocks for any providers that aren't required for the current configuration.

In the meantime, the workaround for anyone who encounters this would be to remove the blocks manually yourself, after verifying that the providers mentioned in the error don't appear in `terraform providers`.

**Comment by andrewmwilson** [comment]
This worked for me too, thanks!

**Comment by wael-sadek** [comment]
Thanks @apparentlymart !

**Comment by adamstirk-ct** [comment]
Hi @apparentlymart removing unused providers from the .terraform.lock.hcl fixed this issue for me.
