### ISSUE TITLE
Terraform unable to download module in a different org from within Github Action

### ISSUE THREAD

**Issue by rjaluka** [hashicorp/terraform#30124]
I have a GitHub Enterprise where I have created two organizations.

Org A has two repos each with one Terraform module. Example 

```
resource "aws_db_instance" "testdb" {
        allocated_storage = 20
        engine = "mysql"
        engine_version = "8.0"
        instance_class = "db.t2.micro"
        name = "testdb"
...
}
```

Org B has a repo with one Terraform file and one Github Action. The Terraform file is call two modules in the two repos in Org A

```
module "tier1_vm" {
        source = "git::git@github.mycompany.net:orga/ec2"
}
module "tier2_db" {
        source = "git::git@github.mycompany.net:orga/rds"
}
```
 
error
downloading 'ssh://git@github.mycompany.net/orga/rds':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/tier2_db'...
Host key verification failed.
fatal: Could not read from remote repository.

If I run this on my local repo without Github Action (Terraform calling modules in other orgs) this works perfectly fine. Not sure if this is something Terraform doesn't support - calling modules from other orgs inside Github Action. Or, am I missing some configuration or parameter.

**Comment by apparentlymart** [comment]
Hi @rjaluka! Sorry for this weird behavior, and thanks for reporting it.

Unfortunately what you have here seems to be a Git error rather than a Terraform error. Terraform is internally just running a command roughly like this:

```shell
git clone ssh://git@github.mycompany.net/orga/rds .terraform/modules/tier2_db
```

...and so the responsibility for all authentication/verification is in Git itself. In this case, I think it's actually even one level deeper: because you are using an `ssh://` URL, Git itself is running `ssh git@github.mycompany.net git ...` commands, at which point the SSH client will handshake with `github.mycompany.net` and try to compare its host key with the known host keys on your system.

Since this is an SSH behavior rather than an a Terraform behavior it's outside of my direct expertise, but my _guess_ would be that in the GitHub Actions environment you don't have `github.mycompany.net` tracked in the SSH client's "known hosts" and so _normally_ `ssh` would prompt you to confirm the new key for the first time, but because GitHub Actions is a non-interactive remote environment it can't show that prompt and it is forced to just fail instead. If that's true, it's potentially a common problem with using SSH in GitHub Actions and so you might be able to find non-Terraform-specific advice about it by researching using terms like "ssh", "github actions", "host key", "known hosts", etc.

If you have reason to believe that I'm mistaken that this is a Git/SSH client error then please let me know what leads you to that conclusion and we'd be happy to investigate further. Thanks!

**Comment by rjaluka** [comment]
@apparentlymart Thank you for your response. I don't see a way to specify know hosts in Github Action or in the Terraform plugin for Github Action. My colleague was able to find a workaround with user id and token hardcoded in the source. This leads me to believe that this is not a Github issue, because the credentials are embedded in the Terraform file and Github would have failed to authenticate. 

`source = "git::https://myuserid:mytoken@github.mycompany.net/micro-azure-tf/medium.git"`

To reuse code, I will have multiple source entries which may point to different organizations. Hardcoding the credentials for each doesn't seem scalable or secure.

**Comment by apparentlymart** [comment]
Hi @rjaluka,

By changing to a `https:` URL rather than an `ssh:` URL you've effectively removed the SSH client from the process and so I think it makes sense that you would no longer see this error then. When you use HTTPS instead, the TLS certificate verification process replaces the SSH host key verification process, and so the success in that case is subject to which root TLS certificates are trusted by the operating system inside the container where Terraform is running, rather than which SSH host keys were previously known.

With that said, I agree that it would not be appropriate to include credentials in the source address. There are [other ways to provide credentials to Git](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage), so in principle you could use one of those strategies as a different way to provide those credentials, if you don't want to deal with SSH.

After some research using the terms I suggested in my previous comment I see lots of people encountering similar problems in GitHub actions, such as [a Stack Overflow question about it](https://stackoverflow.com/questions/63012327/ssh-host-key-verification-failed-in-github-actions-but-key-exists-in-known-h). This seems to confirm my theory that SSH running inside GitHub actions cannot prompt for confirmation of a host key and so you need to preconfigure the host keys yourself inside the container.

Detailed help with SSH is beyond my scope here so I can't describe a full solution, but one thing I would try here if I were in a similar situation is to run `ssh-keyscan github.mycompany.net` on a local system where SSH to that host is already working, which should print out the discovered host public keys for that hostname. If you copy that output and arrange for it to be included in your container image in the SSH client's known hosts file (typically, that's `~/.ssh/known_hosts` where `~` is the home directory of whichever user Terraform is running as) then that would effectively bake that trusted host key into the container image itself, so that the SSH client can verify it on every request.

Creating that file with those contents is what the SSH client would typically do itself after you answer "yes" to the prompt about an unknown host key, when running in interactive mode, and so this is just a way to get the same effect but with you doing the host key verification just once and then saving the result in your image, rather than re-trusting the host on every run (which would, in effect, defeat the purpose of the host key verification.)

Since this does seem to be an SSH or Git configuration issue rather than a Terraform bug I'm going to close this issue, but if you would like to work through this more I'd be happy to offer further suggestions if you start a topic in [our community forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!

**Comment by rjaluka** [comment]
@apparentlymart Thank you.
