### ISSUE TITLE
create azurerm_mysql_flexible_server issue

### ISSUE THREAD

**Issue by jiege3324** [hashicorp/terraform#30131]
azurerm_mysql_flexible_server.db_1: Creating...

Error: creating Flexible Server: (Name "mysql-ehr-db-test-01" / Resource Group "rg-ehr-app-test"): mysqlflexibleservers.ServersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'chinanorth2' and API version '2021-05-01' for type 'flexibleServers'. The supported api-versions are '2020-07-01-privatepreview, 2020-07-01-preview, 2021-05-01-preview'. The supported locations are 'chinaeast2, chinanorth2'."

  on mysql.tf line 19, in resource "azurerm_mysql_flexible_server" "db_1":
  19: resource "azurerm_mysql_flexible_server" "db_1" {

**Comment by apparentlymart** [comment]
Hi @jiege3324,

This error message seems to be from the Azure provider rather than from Terraform itself, so I'd suggest asking about it in [the Azure provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). This repository is only for bug reports and enhancement requests for the core Terraform runtime, separate from any individual provider behavior.

Thanks!
