### ISSUE TITLE
Feature proposal: More granular detailed exit codes from "terraform plan"

### ISSUE THREAD

**Issue by worzel666** [hashicorp/terraform#30146]
### Use cases
In instances where the only changes in a plan are changes to outputs, I would like the detailed exit code to reflect this so we may act accordingly.
The detailed exit code functionality currently only exits with a return code of 2 when any changes are detected by Terraform. My proposal is to make this much more granular.

### Attempted solution
I have attempted implementation on this branch: https://github.com/worzel666/terraform/tree/split-exit-codes however this does not include updates to the tests and does not exit 1 on errors, it was more just a proof of concept.

### Proposal
The return code would then be any combination of the numbers >=2 below:
0 - success, no change
1 - error
2 - output changes
4 - resource changes
8 - resource additions
16 - resource destruction
According to what combination of things Terraform would like to perform - inspired by Unix file permissions. I've seen a number of issues on the repo asking for specific extensions to the detailed exit code functionality and I think this provides an approach which should satisfy all.
(NB the exit code of 1 is kept for backwards compatibility)

**Comment by apparentlymart** [comment]
Hi @worzel666! Thanks for sharing this use-case.

We currently have support for a machine-readable (JSON) representation of plans in order to more generally solve problems of the category "I want my automation to behave differently depending on the content of the plan".

To use it, the automated workflow would be:
1. Run `terraform plan -out=tfplan` to create a plan and save it to a file for subsequent inspection.
2. Run `terraform show -json tfplan` to obtain a [JSON representation](https://www.terraform.io/docs/internals/json-format.html) of the plan contents.
3. Run software of your own design to parse the JSON and react to the content of the plan. Aside from the case of an error (which would've failed at step 1), all of the different situations you listed should be answerable by checking the content of `resource_changes` and `output_changes`.
4. If your software decides to proceed with the apply, run `terraform apply tfplan` to apply exactly the plan created earlier.

Would something like the above allow you to meet your use-case? If not, can you say a little more about what the underlying problem is and why this approach doesn't answer it? Thanks!

**Comment by worzel666** [comment]
I guess it does meet our use case :) We were unaware of the above functionality and currently decide whether or not to stop our pipeline based on the return code of `-detailed-exitcode`. Given that the above functionality appears to be more comprehensive, is detailed-exitcode going to stick around or are you planning on deprecating it?

**Comment by apparentlymart** [comment]
That option is included in [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises) and so we intend to preserve it for at least the whole "v1" series, which currently has no explicit end-of-life date other than it being "actively maintained for at least 18 months after v1.0" (quoting from the current compatibility promises doc); in practice, we have no current plans to begin a v2 series at this time, and even if we did we wouldn't _necessarily_ remove this feature as part of it.

**Comment by crw** [comment]
Closing as this conversation seems to have reached a conclusion; if we believe it needs to be open for an (at this point in time) extremely hypothetical v2, we can re-open. Thanks!
