### ISSUE TITLE
Passing different provider configurations to different modules

### ISSUE THREAD

**Issue by elior379** [hashicorp/terraform#30148]
Hi all!

I have a use case where I need to call two different modules from my root module.
Each module has 'count' on top of it, the count meaning is:  1 (if feature enabled) and 0 (if feature disabled)

The problem is, that assign  provider aliases to modules with 'count' / 'for_each' / 'depends_on'. 
I have 4 Okta accounts and each module should use a specific account based on certain conditionals.

Each module from the modules below is a child module of the root, which calls to other child modules of its own.

Here is my code:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
    okta = {
      source = "oktadeveloper/okta"
      version = "3.10.1"
    }
  }
}

provider "okta" {
  alias = "prod"
  org_name  = local.okta_org
  base_url  = local.okta_base_url
  api_token = "123"
}

provider "okta" {
  alias = "dev"
  org_name  = local.okta_org
  base_url  = local.okta_base_url
  api_token = "123"
}

module "example1" {
  count = local.enable_example1
  source = "../../modules/example1"

 providers = {
      okta = okta.prod
  }

  env_name    = var.env_name
  WorkGroup  = var.WorkGroup == var.env_name ? "Main" : var.WorkGroup 
  stage            = var.stage

}

module "example2" {
  source = "../example2"
  count  = local.enable_example2

  providers = {
      okta = okta.dev
  }
  env_name     = var.env_name
  WorkGroup   = var.WorkGroup
  stage             = var.stage
}
```

The code above prompts the following error:

**Providers cannot be configured within modules using count, for_each or depends_on.**

I saw here that its not supported: https://www.terraform.io/docs/language/modules/develop/providers.html
and also this issue: https://github.com/hashicorp/terraform/issues/24476

But I couldn't come with a solution

Is there any workaround for this issue?
Thanks in advance, Elior

**Comment by jbardin** [comment]
Hi @elior379,

The ability to pass provider configurations into modules expanded with `count` or `for_each` is fully supported. The error here is indicating that you cannot configure provider within those modules, which doesn't appear to be your intent. You didn't include the module configurations in the example, but the error is implying that you have one or more `provider` blocks within the module, which is which is not supported. The module should only be declaring the required names and versions of the provider via `required_provider`, and not include any configuration blocks.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
