### ISSUE TITLE
Escape sequences in strings not working correctly

### ISSUE THREAD

**Issue by elias314** [hashicorp/terraform#30156]
### Terraform Version
```
Terraform v1.1.0
on windows_amd64
```

### Terraform Configuration Files
```terraform
output "windows_user" {
    value = "DOMAIN\\user"
}
```

### Expected Behavior
```
windows_user = "DOMAIN\user"
```

### Actual Behavior
```
windows_user = "DOMAIN\\user"
```

### Steps to Reproduce
Run `terraform apply` on the above sample.

### References
The Terraform documentation on [Strings and Templates](https://www.terraform.io/docs/language/expressions/strings.html) suggests that a `\\` in a string should result in a `\`.  While I haven't tested all of the escape sequences, I've also found this to be true when trying to escape quotation marks via `\"`.

It appears this issue may have been previously reported via #29486.

**Comment by alisdair** [comment]
This is expected behaviour. As noted in #29486, the output of Terraform includes the same escaping, which is why you're seeing the double slash.

To show the output value after interpolation, use the `-raw` flag on the `terraform output` command:

```shellsession
$ terraform apply -auto-approve

Changes to Outputs:
  + windows_user = "DOMAIN\\user"

You can apply this plan to save these new output values to the Terraform state,
without changing any real infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

windows_user = "DOMAIN\\user"
$ terraform output -raw windows_user
DOMAIN\user
```

**Comment by elias314** [comment]
Isn't this backwards?

Wouldn't "raw" mean the unperturbed, uninterpolated output? The documentation also supports this; the text between the two examples under the [Use in Automation](https://www.terraform.io/docs/cli/commands/output.html#use-in-automation) section of the output command documentation says:

"_For the common case of directly using a string value in a shell script, you can use -raw instead, which will print the string directly with no extra escaping or whitespace._"

So the expected behavior should be: if `value = "DOMAIN\\user"`, then -raw should produce `DOMAIN\\user`, ignoring the escaping and "print the string directly", whereas not using -raw should honor the escaping and produce `DOMAIN\user`.

**Comment by alisdair** [comment]
Yes, "raw" does mean the unperturbed, uninterpolated output. However, that is not the same as the input, which in Terraform HCL string literal values is always an escaped string. As a result, the behaviour Terraform has here is as intended by our design at present.

Our intent for "raw" is to print the string as known to Terraform's internals, directly and without escaping. This makes it suitable for use in other tools which then do not have to implement the same escaping logic as HCL in order to interpret it.

Is this behaviour causing problems for your use of Terraform? We'd be interested to hear about it if so.
