### ISSUE TITLE
Feature request: `terraform test` provider version parameter support

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#30164]
### Proposal

It would be good if the `terraform.io/builtin/test` provider supported a `version` parameter. I assume the param doesnt exist yet because theres only 1 version. 

### Example

```hcl
  required_providers {
    test = {
      source = "terraform.io/builtin/test"
      version = "0.0.1"
    }
```

**Comment by crw** [comment]
Thanks for this request! I will add it to the triage list.

**Comment by apparentlymart** [comment]
Hi @drewmullen! Sorry I didn't reply here sooner.

Providers in the special `terraform.io/builtin/` namespace do not support version constraints because they are literally compiled into the `terraform` executable and so there isn't the usual opportunity to query an external registry to learn which versions are available, and to dynamically install the newest one matching the constraints.

(The only other provider in this namespace today is `terraform.io/builtin/terraform`, which is the provider that contributes the `terraform_remote_state` data source. That one admittedly doesn't typically appear in the same way because there's a backward-compatibility-oriented special case that the local name `terraform` defaults to being `terraform.io/builtin/terraform`, instead of `registry.terraform.io/hashicorp/terraform` as would be the usual assumption.)

With that said though, this built-in provider was only ever a placeholder for some built-in language syntax for describing assertions, because adding a new built-in resource type was a less disruptive change to make for the purposes of a temporary experiment than to add a new first-class language feature.

In the meantime in v1.2 we've added the concepts of preconditions and postconditions as an expansion of the idea of [custom condition checks](https://www.terraform.io/language/expressions/custom-conditions). It's not yet clear whether those features in particular or just something of a similar shape will end up being the built-in syntax for describing conditions that must hold for a configuration must be valid (including testing configurations), but we are currently intending to remove the experimental provider entirely in favor of some sort of built-in feature in a future iteration of the testing model.

If you'd be willing, I'd like to learn about why you are interested in potentially selecting different versions of this provider. I assume you are imagining the capabilities of the provider evolving separately from the Terraform Core version you are using, which would of course not be possible if it were a direct language feature and so I'd like to understand what you were thinking about in case it's something we need to consider in the design of built-in language features here.

Thanks!

**Comment by drewmullen** [comment]
👋  Yes, it was shortly after opening the issue that I realized there was no version due to `builtin` literally meaning built-in 😅 

> I assume you are imagining the capabilities of the provider evolving separately from the Terraform Core version you are using

Yes this is a correct assuming. I was imagining pinning to a version of the test framework as changes are introduced, which is impossible as you pointed out. The reality is that its _experimental_ and I should accept that changes may be required until GA or hold off on using the feature. I'll close this issue as its irrelevant. 

> but we are currently intending to remove the experimental provider entirely

Can you clarify which provider you plan to remove?

FWIW my team highly anticipates v2 of `test`!

**Comment by apparentlymart** [comment]
The idea (though this is still early, not yet firmly designed) is that `terraform.io/builtin/test` will no longer be included in Terraform once there's a sufficient built-in language feature for describing conditions that must hold in order for the configuration to be considered valid.

Figuring out what exactly that built-in language feature should look like is a big part of the design effort that hasn't started in earnest yet, but will hopefully start soon!
