### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform#30167]
### Terraform Version
1.1.0
### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.89.0"
    }
  }
}
...
```

### Debug Output
 Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/null: could not connect to
│ registry.terraform.io: Failed to request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": net/http: request canceled while waiting for connection
│ (Client.Timeout exceeded while awaiting headers)

### Expected Behavior
Terraform init initialized

### Actual Behavior
(Client.Timeout exceeded while awaiting headers)

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`

**Comment by crw** [comment]
Thanks for the report. This looks to be a transient issue caused by a lack of network connectivity to `registry.terraform.io`. Can you please `ping registry.terraform.io` or otherwise confirm you have a route to that domain? If you can confirm you have a route to that domain but still cannot run `terraform init` with the above example, please re-open this ticket. Thanks!
