### ISSUE TITLE
destroying aws_iam_policy_attachment to a managed policy deletes everyone's attachments 

### ISSUE THREAD

**Issue by bilalasghar931** [hashicorp/terraform#30181]
I am attaching AWS manged policies to a role using "aws_iam_policy_attachment" and when i destroyed the configuration, it detach same policies from all my AWS roles, this causes my production to down and then i realized this terraform bug, I also see one same issue that someone post at 2016 still no solution for this error.

**Comment by alisdair** [comment]
Hello! Without more details I'm not sure of your situation here, but if you managed the AWS policy with Terraform and destroy the configuration, Terraform will destroy the policy too. This does not sound like a bug.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a Terraform bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
