### ISSUE TITLE
AWS IAM Role Trust Policy not refreshing state

### ISSUE THREAD

**Issue by squallsv** [hashicorp/terraform#30180]
Terraform Version
1.1.1

Affected Resource(s)
aws_iam_role
aws_iam_role_policy
Terraform Configuration Files
```
provider "aws" {
    region = "eu-west-1"
}

data "aws_iam_policy_document" "action_policy" {
    statement {
        effect = "Allow"
        actions = [
            "*"
        ]
        resources = [
            "*"
        ]
    }
}

data "aws_iam_policy_document" "trust_policy" {
    statement {
        effect = "Allow"
        actions = [
            "sts:AssumeRole"
        ]
        principals {
            type = "Service"
            identifiers = [
                "ec2.amazonaws.com"
            ]
        }
    }
}

resource "aws_iam_role" "role" {
    name = "test-role"
    assume_role_policy = "${data.aws_iam_policy_document.trust_policy.json}"
}

resource "aws_iam_role_policy" "policy" {
    name = "test-policy"
    role = "${aws_iam_role.role.id}"
    policy = "${data.aws_iam_policy_document.action_policy.json}"
}
```
Output
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Expected Behavior
When this code runs it successfully creates my role. However, if manual changes are made to via the console to the trust policy, for example changing ec2.amazonaws.com to lambda.amazonaws.com and terraform is reapplied it does not refresh state for the role and update the policy.

This same behavior is observed for a terraform refresh.

I'm merely just copying and pasting this issue(https://github.com/hashicorp/terraform/issues/10790) because I'm using the latest Terraform version and this is still happening. I also noticed that this issue, and several other issues related to the same problem(like https://github.com/hashicorp/terraform/issues/5201), were closed without proper testing based on the closing messages.

Actual Behavior
I'd expect that terraform would reload the actual resources state in AWS, see a different in the trust policy in terraform configuration and update the resource.

Steps to Reproduce
terraform apply
make a manual change to the trust policy via AWS console
terraform apply
validate that the manual change is still present

**Comment by crw** [comment]
Hi @squallsv, thanks for re-opening this one. The good news is I do not believe the HashiBot automatically closes tickets anymore, so this should remain open for the life of the issue. 

I will also note that this sounds like an issue with the AWS provider (https://github.com/hashicorp/terraform-provider-AWS) - I will run it past my colleague to see if it needs to be routed to that repository.

**Comment by apparentlymart** [comment]
It is indeed the provider's responsibility to detect changes made in the remote system, during the refresh step. In this case, it sounds like the `aws_iam_role` resource type in the AWS provider didn't read the latest assume role policy from the remote system and return it to Terraform Core, and so Terraform Core in turn didn't react to it having changed.

However, this does seem to be a more subtle problem than just some missing provider functionality, because I can see [code in the AWS provider which appears to be attempting to update this particular attribute](https://github.com/hashicorp/terraform-provider-aws/blob/959df0728b069b74d001c5fa110577812282c1ed/internal/service/iam/role.go#L291-L297). It's not clear to me (as an outside reading that code without any additional context) why external changes would not be detected, and so I expect the AWS provider team will need to do some additional debugging to get to the root of this problem.

Given that, I'm going to close this issue and I suggest instead opening an issue in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws). If you do so, given that #10790 is a very old issue I expect the AWS provider team will want to see a fresh set of answers to all of the questions in their bug report template so that they can debug based on exactly what behavior _you_ have seen, and ask you questions based on that, in order to understand what exactly is happening.

Thanks!

**Comment by squallsv** [comment]
Thank you for the inputs @apparentlymart. I will open up the issue there.
