### ISSUE TITLE
`terraform show` fails with `different state lineage` error on `v1.1.1` if plan uses non-default state file

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform#30195]
### Terraform Version

```
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
```

### Terraform Configuration Files

https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue/blob/main/main.tf.json

#### stdout / stderr
https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue/blob/main/full-log.txt

#### with `TF_LOG=trace`
https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue/blob/main/full-log-trace.txt

### Expected Behavior

Should not fail (works with Terraform `v1.0.7`)

### Actual Behavior

`terraform show test.plan` fails with
```
╷
│ Error: Saved plan does not match the given state
│
│ The given plan file can not be applied because it was created from a different state lineage.
╵
```

### Steps to Reproduce

See https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue

### Additional Context

The `cdk.tf.json` was generated by the CDK for Terraform and based on code from [this tutorial](https://learn.hashicorp.com/tutorials/terraform/cdktf-install?in=terraform/cdktf).

### References
- https://github.com/hashicorp/terraform-cdk/issues/1428

**Comment by alisdair** [comment]
Thanks for the reproduction! I can see the same behaviour and I've reduced the steps a bit further to help with the investigation:

main.tf:
```
resource "null_resource" "none" {}
```

1. `terraform init`
2. `terraform apply -state test.tfstate -auto-approve`
3. `terraform plan -state test.tfstate -out saved.tfplan`
4. `terraform show saved.tfplan`

**Comment by apparentlymart** [comment]
Hi @ansgarm,

This does definitely seem like a regression to be fixed, but I'm separately curious as to what real-world situation led you to discover this bug. The `-state` argument and the related ones (`-state-out`, etc) are [long-deprecated legacy options](https://www.terraform.io/language/settings/backends/local#command-line-arguments) that we've preserved only for backward compatibility with older workflows, and so I'm surprised to see them appear in conjunction with CDK for Terraform.

If CDK for Terraform is using this mechanism to achieve some real use-case then I think it'd be helpful to document that use-case in a separate enhancement request issue so that we can find a more sustainable way to support it, using only currently-recommended features.

**Comment by ansgarm** [comment]
Hi @apparentlymart,

Interesting! I did not know that. Using `-state` has been used in the CDK for Terraform [since quite some time](https://github.com/hashicorp/terraform-cdk/blob/7dc123244eedd4f6e86245cf2a235f48c130ed50/packages/cdktf-cli/bin/cmds/ui/models/terraform-cli.ts#L76). Do you know in which Terraform version it was deprecated?

I don't see any reason why we couldn't switch the CDK for Terraform to explicitly use the [local backend](https://www.terraform.io/language/settings/backends/local) instead. Apparently we always set that `-state` flag but it only has an effect if no `backend` is configured. I'll create an issue to get that sorted!

**Comment by apparentlymart** [comment]
Thanks @ansgarm!

Since you've started that new issue I'll add some notes over there rather than answering you directly here, since hopefully that'll keep the information closer to the issue your team will refer to.

**Comment by alisdair** [comment]
Hi @ansgarm! The fix for this issue has been merged into the release branch, and will ship in the upcoming 1.1.3 patch version.
