### ISSUE TITLE
Extra Provisioners "Overview" page, and dangling "Provisioners are a last resort" links

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#30207]
With the recent move to the new website platform, it seems like what was formerly a single provisioners landing/overview page has now split into two:

* [Overview](https://www.terraform.io/language/resources/provisioners): A very "content-lite" page that doesn't seem to really say anything that isn't already stated elsewhere.
* [Declaring Provisioners](https://www.terraform.io/language/resources/provisioners/syntax): Seems to just be all of the content that was formerly on the "Overview" page on the old site, including our "Provisioners are a Last Resort" guidance.

In addition to that, the various pages about specific provisioners ([`remote-exec`](https://www.terraform.io/language/resources/provisioners/remote-exec), [`file`](https://www.terraform.io/language/resources/provisioners/file), and [`local-exec`](https://www.terraform.io/language/resources/provisioners/local-exec)) all include a hint callout summarizing the "Provisioners are a Last Resort" guidance and linking to "the main Provisioners page" for more detail, but they all link to the "Overview" page described above, which doesn't actually have any useful guidance on that topic.

At first glance it seems like the most reasonable change here would be to remove the "Declaring Provisioners" page and move its content back to the "Overview" page again, perhaps preserving the new navigation title "Declaring Provisioners" since that's a bit more descriptive, but most importantly to retain the overview page _URL_ so that the incoming links will still land in the right place, both from within the site and from various commentary elsewhere on the internet linking to the "Provisioners are a Last Resort" guidance.

In particular, there are various incoming links to variations of `https://www.terraform.io/docs/language/resources/provisioners/#provisioners-are-a-last-resort` which on the new site redirect to the content-lite overview page and therefore don't actually arrive at the "Provisioners are a Last Resort" heading as intended. Given that, an alternative way to go here would be to change the redirect for that old URL to forward to `https://www.terraform.io/language/resources/provisioners/syntax#provisioners-are-a-last-resort` instead, which would also arrive at the intended destination.

**Comment by crw** [comment]
@laurapacilio tentatively assigned to you as an FYI -- feel free to de-assign yourself. :)

**Comment by laurapacilio** [comment]
Hi both! :-) Thank you so much for flagging this.  I put up a PR for this here: https://github.com/hashicorp/terraform/pull/30296 that I am hoping addresses this issue. Please let me know if you have feedback! 

Also - I was thinking through redirects, etc.... and I looked at an old branch I had from a few months back (before the migration) and it looks as though we actually have had this nearly empty "overview" page and the separate "syntax" page with the actual "provisioners are a last resort" content on it for some time. This isn't something that changed in the migration and it's been this way for months it looks like. Because of that, I decided to remove the "Overview" page and keep the one with "syntax" in it because that's been a useful page much longer than "index"/"Overview" has. I was thinking it might be more likely that there are MORE links pointing to "syntax" than "overview" because there's just more content on it. Then, I updated all of our internal references to the "provisioners are a last resort" content, which look like they've been pointing at the nearly empty "Overview" page for some time. 

Just wanted to explain why I took this approach - I'm going to go into `terraform-website` and do a redirect for the overview page to make sure that all external links point to the actual "provisioners are a last resort" content and don't fail/users don't get a 404. Let me know if this doesn't make sense or if you completely disagree!
