### ISSUE TITLE
Registry - multiple hierarchy module collision when using same name

### ISSUE THREAD

**Issue by wideawakening** [hashicorp/terraform#30218]
### Actual Behavior

```
ROOT
/modules
  /permissions
      /A
      /B
  /A
  /B
```
registry convention shows two "A" modules under the selector, and both with same resource link .

Terraform registry is shaping how modules are being structured and there is some hoodoo involved that [terraform module development structure guideliness](https://www.terraform.io/docs/language/modules/develop/structure.html) don't contemplate.

Guess we can fix this with some renaming and/or level flatenning but it would be nice to have less repetitiveness on github

### Expected Behavior

Could it be possible to append the submodule hierarchy instead of flattening it?

```
/permissions/A
/permissions/B
/A
/B
```

**Comment by apparentlymart** [comment]
Hi @wideawakening! Thanks for this bug report.

I'm afraid I'm not sure what exactly you are intending to report here. Are you saying that there's something incorrect in [Standard Module Structure](https://www.terraform.io/language/modules/develop/structure)'s description of the conventions, or are you intending propose _new_ conventions that meet a new need? If the latter, can you say a bit more about what that underlying need _is_, as opposed to the mechanics of how you'd represent that in the module registry?

Thanks!

**Comment by wideawakening** [comment]
Sure! The need would be to be able to differentiate two modules with same name, in different hierarchy, under `/modules` folder.

**Comment by apparentlymart** [comment]
Hi @wideawakening,

It sounds like you're talking about the "nested modules" convention, described in the documentation like this:

> Nested modules. Nested modules should exist under the `modules/` subdirectory. Any nested module with a `README.md` is considered usable by an external user. If a README doesn't exist, it is considered for internal use only. These are purely advisory; Terraform will not actively deny usage of internal modules. Nested modules should be used to split complex behavior into multiple small modules that advanced users can carefully pick and choose. For example, the [Consul module](https://registry.terraform.io/modules/hashicorp/consul) has a nested module for creating the Cluster that is separate from the module to setup necessary IAM policies. This allows a user to bring in their own IAM policy choices.

If so, I think the _good_ news for you here is that Terraform's own module installer and the registry protocol don't _require_ that you follow those conventions: from the registry protocol's perspective, they are just conventions rather than rules, and so you can write a module source path which includes as many levels of nesting in [the "subdirectory" portion](https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories) as you like. For example, the following would all be syntactically-valid registry module source addresses:

* `namespace/name/system//modules/permissions/A`
* `namespace/name/system//modules/permissions/B`
* `namespace/name/system//modules/A`
* `namespace/name/system//modules/B`
* `namespace/name/system//anything-actually` (Terraform CLI doesn't even consider the "modules" directory to be special, so you can technically place a module anywhere you like inside the module package.)

However, it's true that [the public Terraform Registry](https://registry.terraform.io/) _does_ rely on these conventions in order to present module information at a slightly higher level of abstraction. Specifically, the registry's importer seems to treat any direct subdirectory of `modules` as a "submodule" regardless of whether another submodule refers to it, whereas other paths are treated as submodules only if the root or some other submodule refers to them.

With all of that said then, I think what you are asking for is for the public registry in particular to also treat _nested_ subdirectories of `modules` in the same way, making them appear as documented submodules as long as they contain `README.md` files, without first requiring that another submodule refers to them. Is that a correct understanding?

The public Terraform Registry doesn't live in this repository, and isn't open source so it doesn't have its own GitHub repository to record this request in. Therefore if you _are_ intending this as a Terraform Registry feature request then I think it'd be best to send it to [terraform-registry@hashicorp.com](mailto:terraform-registry@hashicorp.com), which is the main contact address for the team which maintains Terraform Registry and will allow them to record your request in their private list of issues. The Terraform Registry team doesn't typically monitor for issues in _this_ repository, and so I can't guarantee that they will see this request here in order to consider it.

Thanks!

**Comment by crw** [comment]
Hi @wideawakening, thanks for this report! As this is a registry issue with a clear next step, I'm going to close this issue. Please let me know if you think this is actually an issue for the core Terraform CLI or language.
