### ISSUE TITLE
Allow dynamic provisioner blocks, at least in null_resource

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#30225]
### Use-cases
I have a null_resource with many provisioner blocks to perform provisioning commands on various triggers. All commands contain data from TF (such as instance names and ids, security groups ids, etc). I would like to put all commands in a list in a local variable and feed it to the dynamic provisioner block. But this is currently not allowed. 

I know that creating a script is a valid workaround, but managing all data used in commands by environment variables adds complexity and mess that overlap the benefits of using a script.

From another issues's explanation:
> As the documentation suggests, provisioner blocks are processed early in Terraform's configuration parsing, long before expression evaluation is possible, so that Terraform can predict the full set of changes required and build the dependency graph.

By the way, I don't understand what dependencies provisioners could apply? And how do they differ from any kind of other dependencies in dynamic blocks when references to other variables and resources can be used?

### Proposal
Allow using dynamic provisioners at least in null_resource.

### References
- #21425

**Comment by apparentlymart** [comment]
Thanks for sharing this use-case, @speller.

At this point we're mainly just preserving the existing provisioner functionality as-is, without any new enhancements, to stay compatible with existing usage. There isn't really anything a provisioner can do that a resource type cannot in principle: a provisioner is functionally equivalent to a resource type that only takes actions "create" or "destroy", and with Terraform now supporting automatic installation of arbitrary third-party providers that is now a ready extension point for any use-cases that require custom logic at any point in the resource lifecycle.

If what you need is to run an arbitrary command as `local-exec` would then instead of implementing an entirely new provider you could potentially use one of the community providers that allow you to execute arbitrary external scripts as the implementation of different parts of Terraform's resource lifecycle. I've not personally used any of them in a real way and so I can't recommend any in particular, but one _example_ of what I mean is [`shell_script_resource` from `scottwinkler/shell`](https://registry.terraform.io/providers/scottwinkler/shell/latest/docs/resources/shell_script_resource), which seems to allow defining an arbitrary shell script to run during `create` _and_ mimics the same sort of `triggers` pattern we see on `null_resource` as a way to force replacing an instance when other values change.

Of course this doesn't mean that we aren't interested in potentially designing other features to meet your use-case, but I expect that those designs would not involve provisioners for the reasons mentioned above; instead, I expect we'd aim to design something that works in terms of resources themselves. If a provider like the one I suggested above (presumably used with `for_each` to manage your required dynamic number of instances) can't meet the use-case you have then knowing where that solution falls short would help to design a feature that better matches the use-case.

Thanks!
