### ISSUE TITLE
issue with aruzeRM storage account location

### ISSUE THREAD

**Issue by devopsautomationgcloud** [hashicorp/terraform#30229]
Error: creating Azure Storage Account "xxxxxxxxxxxx": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="LocationNotValid" Message="Supplied location uksouth is not valid."
│ 
│   with module.Storageaccount.azurerm_storage_account.storage_account,
│   on Modules/Storageaccount/main.tf line 2, in resource "azurerm_storage_account" "storage_account":
│    2: resource "azurerm_storage_account" "storage_account" {
│ 

Team,
I'm trying to deploy a storage account in "UKSOUTH" location and getting the above error. Below is the spec for my environment:
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0

FYI - I tried to change the azurerm version to v2.86.0, still same error. Any idea, how to go about it.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
