### ISSUE TITLE
Sensitive data update in place everytime

### ISSUE THREAD

**Issue by rmtier** [hashicorp/terraform#30240]
### Terraform Version

```
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
```

### Terraform Configuration Files

```terraform

resource "azurerm_storage_account" "storage_account" {
  count = 1
  name                      = "withoutmodule"
  resource_group_name       = "XXX"
  location                  = "West Europe"
  account_tier              = "Standard"
  account_replication_type  = "GRS"
  account_kind              = "StorageV2"
  enable_https_traffic_only = true
  is_hns_enabled            = false
  min_tls_version           = "TLS1_2"
  allow_blob_public_access  = false
}


resource "azurerm_redis_cache" "replication" {
  name                = "redis-testing"
  location            = "West Europe"
  resource_group_name = "XXX"
  capacity            = 1
  family              = "P"
  sku_name            = "Premium"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  subnet_id           = null
  private_static_ip_address = null

  dynamic redis_configuration {
    for_each = azurerm_storage_account.storage_account
    content {
      maxmemory_policy = "allkeys-lru"
      aof_backup_enabled = true
      aof_storage_connection_string_0 = redis_configuration.value.primary_connection_string
      aof_storage_connection_string_1 = redis_configuration.value.secondary_connection_string
    }
  }
}
```

### Expected Behavior

Do not detect change on aof_storage_connection_string_0 and aof_storage_connection_string_1.

Or at least do warning  (https://github.com/hashicorp/terraform/pull/28738)
```
Note: this sensitive attribute value will be marked as
sensitive, but its value is unchanged
```
### Actual Behavior

Detect change without warning.

```
 ~ redis_configuration {
        ~ aof_storage_connection_string_0 = (sensitive value)
        ~ aof_storage_connection_string_1 = (sensitive value)
           # (12 unchanged attributes hidden)
     }

```

Terraform in state has connection strings aof_storage_connection_string_0, aof_storage_connection_string_1 coded with [hidden] as:
```
"aof_storage_connection_string_0": "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=withoutmodule;AccountKey=[key hidden]",
"aof_storage_connection_string_1": "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=withoutmodule;AccountKey=[key hidden]",
```

And change state detect change everytime that it is running. I understand it can be design of terraform, but usage flexibility decline with problems like this. I am able to temporary fix this with ignore_changes, but I do not like this solution.
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3.  `terrafform plan`
### References

I was able to find issue https://github.com/hashicorp/terraform/issues/28593 (with merged commit), but I do not see any sensitive data warning output. Also I do not think it is good solution (only some kind of compromise between usability and internal implementation complexity).

**Comment by jbardin** [comment]
Hello @rmtier,

If the configuration value has not changes, which it doesn't appear to have done so from the plan output, then the values are being altered by the provider. In other words, the plan is highlighting these attributes because they are sensitive, it is indicating they have changed but isn't displaying the change because they are sensitive.

If you want to inspect the complete plan output, you can use `terraform show -json planfile`, which will include all sensitive values unmasked.

Since this appears to be an issue or question with the AzureRM provider, not with Terraform itself I'm going to close it. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
