### ISSUE TITLE
Terraform state rm command doesnt delete state

### ISSUE THREAD

**Issue by chimera-rep** [hashicorp/terraform#30257]
### Terraform Version

```
Terraform v0.14.8
```

### Terraform Command

```terraform
$ terraform state rm module.ads.module.ip_acb.aws_iam_role.this
Removed module.ads.module.ip_acb.aws_iam_role.this
Successfully removed 1 resource instance(s).
Releasing state lock. This may take a few moments...



$ terraform state show module.ads.module.ip_acb.aws_iam_role_policy_attachment.this
No instance found for the given address!
This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify 
the address to reference a specific instance.


$ terraform apply
# module.ads.module.ip_acb.aws_iam_role_policy_attachment.this will be created
  + resource "aws_iam_role_policy_attachment" "this" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::396400463349:policy/acb"
      + role       = "acb"
    }

```

### Expected Behavior

Terraform apply should say: No actions required (or something same)

### Actual Behavior

Terraform apply proposes create module.ads.module.ip_acb.aws_iam_role_policy_attachment.this

**Comment by jbardin** [comment]
Hi @chimera-rep,

Thanks for filing the issue. I think you may be confusing Terraform state with Terraform configuration. The command `terraform state rm module.ads.module.ip_acb.aws_iam_role.this` did remove the resource from the state, which is precisely why the next plan results in recreating that resource. Having that resource remain in the configuration is instructing Terraform to make sure there it always exists as configured with every plan. You must remove the resource from the configuration in order to prevent it from being created again.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by chimera-rep** [comment]
May be I just cant find the resource in the complex configuration, Thank you @jbardin
