### ISSUE TITLE
missing expression references when using for each

### ISSUE THREAD

**Issue by romiLightlytics** [hashicorp/terraform#30268]
hi, I'm using terraform v1.1.2
I'm creating few instance resources using for each expression.
each iteration, sets several attributes

on the plan output in json format, I expect to see a list that consists the input values in the for each order,
instead, I get a reference to "each.value.<input_name>" 

for example:

for_each = {
    one = {
      subnet_id         = var.subnets[0]
    }
    two = {
      subnet_id         = var.subnets[1]
    }
    three = {
      subnet_id         = var.subnets[2]
    }
  }

actual output  after: terraform show -json ->

"subnet_id": {
    "references": [
        "each.value.subnet_id",
        "each.value"
    ]
},

expected behavior ->

"subnet_id": {
    "references": [
        var.subnets[0],
        var.subnets[1],
        var.subnets[2]
    ]
},

**Comment by crw** [comment]
Thanks for the report! Adding this to the triage list.

**Comment by apparentlymart** [comment]
Hi @romiLightlytics,

Terraform's reference analysis only returns the direct references, and doesn't currently attempt to "dig deeper" and find indirect references.

It sounds like what you are asking for here is for Terraform to fully explore the dependency graph starting at the given expression and return the expanded set of all _indirect_ references starting at that expression. In your case, that would cause the result to be the following, because it would still need to include the _direct_ references to avoid breaking existing consumers who are expecting to find those:

```json
  "subnet_id": {
    "references": [
      "each.value",
      "each.value.subnet_id",
      "var.subnets",
      "var.subnets[0]",
      "var.subnets[1]",
      "var.subnets[2]"
    ]
  }
```

The behavior you showed as "actual output" matches the current intended design of Terraform, and so I'm going to reclassify this as an enhancement request to potentially expand the set of references to include all of the indirect references too.

We tend to evaluate feature requests based on the underlying use-case, since there may be other ways to meet your need which have better design tradeoffs, so in order for us to consider this it would help if you could say a little more about why it would be helpful to you for these indirect references to be included, and specifically what you intend to do with that additional information in whatever software you are writing/using which would consume that result. Thanks!

**Comment by romiLightlytics** [comment]
Hi @apparentlymart

I'm working on a unique Terraform parser for my organization, and our product is highly dependent on that parser. The missing indirect references are greatly affecting the parser's understanding of the various dependencies of the resources in the plan.

I'd highly appreciate if you could prioritize my request, this will help us a lot.
Thank you!

**Comment by apparentlymart** [comment]
Hi @romiLightlytics! Thanks for sharing the additional context about your underlying use-case.

I'm curious to know if you've tried following the direct references yourself in order to find the indirect references, and thus effectively implementing the same recursive expansion algorithm that Terraform itself would need to perform to get the result you wanted here.

One immediate complication I can see about doing that is that your program would need to be able to parse and understand Terraform's reference syntax, in order to know (for example) that `var.subnets` corresponds to the `variable "subnets"` block in the same module. That would involve replicating, at least in part, Terraform's logic for decoding reference addresses, which is technically possible to do but also, I understand, far more complicated than just matching opaque strings.

Terraform itself is doing that internally to find the edges of the dependency graph, but currently never has any need to search more than one step away from the current object because that other object will also be subject to its own dependency analysis. So far our JSON output has typically just been essentially a one-to-one relationship with data Terraform is already tracking internally, and so I think meeting your requirement here would be the first example of the JSON serializer doing significant extra work that Terraform wouldn't normally need to do for any other reason. That doesn't mean we can't do it, of course, but it does mean that we'll need to consider carefully the costs of doing so -- both ongoing maintenance costs and potential performance costs for including a potentially large amount of additional information that most callers won't need at all.

**Comment by romiLightlytics** [comment]
Hi @apparentlymart Thanks for the detailed answer.

I understand what you explained and I am aware to the Terraform logic.
But in the case I gave as an example, the reference is not var.subnets.
instead it is : ["each.value.subnet_id", "each.value"]
subnet_id is the name of the input variable on the instance resource, so it does not contain any information about the value of the variable. 
Lets say that I can understand that this instance resource is associated with var.subnets using Terrafrom Graph, and I can resolve the addresses that this variable contains.
but I do not have the information of which instance in the for each loop is associated to which subnet
I mean, how would I now that instance["one"] is associated to var.subnets[0] and not to var.subnets[1] if the only information I have is the association to var.subnets
 
for example if the for each would be: 

for_each = {
one = {
subnet_id = var.public_subnets[2]
instance_type = x
}
two = {
subnet_id = var.private_subnets[0]
instance_type = y
}
three = {
subnet_id = var.subnets[1]
instance_type = z
}
}

There is no way for me to know that the instance created with instance type y is associated to var.private_subnets[0]
It is not sufficient the knowledge that var.public_subnets, var.private_subnets and var.subnets are associated to the instance if I do not know the order and its indexes  

my request is not to resolve completely the referenced address, I am aware that it might cause performance issues,
but adding at least some information about the hard-coded values inserted to the subnet_id variable according to the for each order would help me a lot

Let me know if my explanation is clear, 
Thank you!

**Comment by apparentlymart** [comment]
Hi @romiLightlytics,

For `each.key`, `each.value`, and `count.index` in particular the situation is a little different but should still be decidable in principle: `each.key` and `each.value` are both references to the `for_each` expression of that resource, and `count.index` is a reference to the `count` expression of the resource. Therefore to find indirect dependencies `each.value` you would need to refer to the `for_each_expression` property of the corresponding resource and consult the references recorded in there.

However, I would note that this can only ever tell you that the resource depends on the entire `var.subnets`, because that is actually all that Terraform knows itself: Terraform waits until everything in that variable is ready before resolving the `for_each` expression, and so it has no ability to (and no need to) track specifically which `var.subnets` element belongs to each instance of the resource.

The best Terraform could do here, if it _were_ to fully explore the dependency graph and return all of the indirectly-depended objects, would be to list the objects that the `for_each` expression refers to directly, and as far as I can see the JSON configuration representation already contains the equivalent information required to compute that same result, if your consumer has awareness of all of Terraform's reference address types and understands what other object or expression they refer to.

**Comment by crw** [comment]
Hi @romiLightlytics, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
