### ISSUE TITLE
missing data in terraform plan (json format)

### ISSUE THREAD

**Issue by romiLightlytics** [hashicorp/terraform#30267]
hi, I'm using terraform v1.1.2
I have noticed that when I'm using policy resources that have interpolation sequence, the policy content is missing in the terraform plan output (terraform show -json)

example plan:

```
resource "aws_sns_topic" "test" {
  name = "my-topic-with-policy"
}

resource "aws_sns_topic_policy" "test" {
  arn = aws_sns_topic.test.arn
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "First",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:SendMessage",
      "Resource": "${aws_sns_topic.test.arn}"
    }
  ]
}
POLICY
}
```

If all statement attributes were hard-coded, the policy content would have been specified in the output json
Is it a known issue? 
can it be fixed? 

Thank you!

**Comment by jbardin** [comment]
Hi @romiLightlytics,

In the example you've shown here, the attribute values are not hard-coded, the `policy` attribute is a string template containing a reference to the computed value `aws_sns_topic.test.arn`, which means the value of the `policy` string cannot be known until apply. You can see this in the plan json with `policy` listed as `true` under `after_unknown` in the `resource_changes`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
