### ISSUE TITLE
Feature Request: Allow interpolation of resource names

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#30273]
It would be awesome if you could interpolate the name of a resource. In the module example below, users could choose to deploy resource into any region. I could loop over creating the `route53_record` like this:

```terraform
data "aws_lb" "us-east-1" {
    provider = aws.us-east-1

    arn = var.cell_attributes["us-east-1"].elasticloadbalancing
}

data "aws_lb" "us-west-2" {
    provider = aws.us-west-2

    arn = var.cell_attributes["us-west-2"].elasticloadbalancing
}


resource "aws_route53_record" "alias" {
  for_each = toset(["us-east-1", "us-west-2"])
  alias {
    name                   = data.aws_lb[each.key].name
    zone_id                = data.aws_lb[each.key].lb_zone_id
    evaluate_target_health = true
  }
...
}
```

### Currently I get an error:
```
╷
│ Error: Invalid reference
│ 
│   on main.tf line 169, in resource "aws_route53_record" "alias":
│  169:     name                   = data.aws_lb[each.key].name
│ 
│ The "data" object must be followed by two attribute names: the data source type and the resource name.
```

If you add a `.`
```
│ Error: Invalid attribute name
│ 
│   on main.tf line 171, in resource "aws_route53_record" "alias":
│  171:     name                   = data.aws_lb.[each.key].name
│ 
│ An attribute name is required after a dot.
```

tried `data.aws_lb.each.key.name`
```
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 171, in resource "aws_route53_record" "alias":
│  171:     name                   = data.aws_lb.each.key.name
│ 
│ A data resource "aws_lb" "each" has not been declared in the root module.
```

### Workaround

For now I have a workaround to use locals:
```terraform
locals {
    lb_info = merge({
        "us-east-1" = one(data.aws_lb.us-east-1)
        "us-west-2" = one(data.aws_lb.us-west-2)
    })
}
```

**Comment by apparentlymart** [comment]
Hi @drewmullen! Thanks for sharing this use-case.

Terraform requires all references to include at least the resource type and name because that is the minimum required to identify a node in the dependency graph, which Terraform uses in order to understand the correct evaluation order for all of your declared configuration objects.

The local value approach you showed avoids that because you've explicitly declared to Terraform that you want to treat both of those resources as a single unit for dependency resolution purposes, and so any reference to `local.lb_info` indirectly depends on both `data.aws_lb.us-west-1` and `data.aws_lb.us-west-2`. That gives Terraform the information needed to produce a correct dependency graph while still allowing you to ultimately decide dynamically which of the two resources to use.

With that said, it seems like your underlying use-case here might be better served by Terraform allowing a dynamic assignment of provider configuration to each resource instance, so that you could declare only a single `data "aws_lb"` covering both regions. That's not possible in Terraform today because Terraform resolves the resource-to-provider-configuration relationship at the same time as it resolves the dependency graph, but we do have some early hypothetical designs for allowing the use of provider configurations as values themselves, which could therefore be placed into data structures like maps and lists in the same way that other values can:

```hcl
# NOT VALID: This is a hypothetical example of one possible
# syntax for provider configurations as values.

terraform {
  required_providers {
    # This establishes that "aws" in this module refers
    # to the hashicorp/aws provider, just as in today's
    # terraform.
    aws = {
      source = "hashicorp/aws"
    }
  }
}

variable "cells" {
  type = map(object({
    # This attribute expects a provider configuration
    # associated with the hashicorp/aws provider.
    provider_config   = providerconfig(aws)
    load_balancer_arn = string
  }))
}

data "aws_lb" "example" {
  for_each = var.cells
  provider = each.value.provider_config

  load_balancer_arn = each.value.load_balancer_arn
}

resource "aws_route53_record" "example" {
  for_each = var.cells

  # ...
  alias {
    name                   = data.aws_lb.example[each.key].name
    zone_id                = data.aws_lb.example[each.key].lb_zone_id
    evaluate_target_health = true
  }
}
```

Then in the caller of this module:

```hcl
# NOT VALID: This is a hypothetical example of one possible
# syntax for provider configurations as values.

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  alias = "us-east-1"

  region = "us-east-1"
}

provider "aws" {
  alias = "us-west-2"

  region = "us-west-2"
}

module "example" {
  source = "./modules/cell-thing"

  cells = {
    a = {
      provider_config   = provider.aws.us-east-1
      load_balancer_arn = "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/my-load-balancer/1234567890123456"
    }
    b = {
      provider_config   = provider.aws.us-west-2
      load_balancer_arn = "arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/app/my-load-balancer/1234567890123456"
    }
  }
}
```

This surface-level design includes all of the information Terraform would need to understand all of the relationships between objects in principle -- the `cells` argument in the `module "example"` block is effectively serving a similar purpose as the `local.lb_info` approach you're using today, telling Terraform that `var.cells` inside the child module indirectly depends on _both_ provider configurations. We've not yet studied in detail how this would work in Terraform Core's implementation details, and also how exactly we'd be able to introduce something like this while remaining consistent with [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises) since the example above includes some examples of changing the meaning of existing valid expressions, which we cannot do. Further research in this area is not in our current scope of work due to priorities being elsewhere, but this _is_ a family of use-cases we want to address eventually.

It looks like we already have #24476 open to represent use-cases like these, so I'm going to close this one just to consolidate the discussion over there. (I know that issue is discussing a different _solution_ than you proposed here, but the underlying use-case is the same and we use enhancement issues primarily to track use-cases, rather than design proposals.)

Thanks again for sharing this.

**Comment by drewmullen** [comment]
I like your proposed solution better :D looking forward to Somday™
