### ISSUE TITLE
SecurityHub raises an InvalidAccessException: Account <REDACTED> is not an administrator for this organization when the account is the administrator

### ISSUE THREAD

**Issue by UrfTheManatee** [hashicorp/terraform#30285]
### Terraform Version

```
Terraform v1.1.2
on darwin_amd64
```

### Terraform Configuration Files

```terraform
resource "aws_securityhub_account" "cust-lz-securityhub" {}



# Auto enable security hub in organization member accounts
resource "aws_securityhub_organization_configuration" "enable_config_automatically" {
  auto_enable = true
  depends_on = [aws_securityhub_account.cust-lz-securityhub]
}

resource "aws_securityhub_organization_admin_account" "admin_account_id" {
  admin_account_id =  local.lz_info_sec_account.id
  depends_on = [aws_securityhub_organization_configuration.enable_config_automatically]

}
```

### Debug Output
```
2022-01-04T12:54:02.252Z [DEBUG] [aws-sdk-go] {}
╷

│ Error: error updating Security Hub Organization Configuration (): InvalidAccessException: Account <REDACTED> is not an administrator for this organization

│ {

│   RespMetadata: {

│     StatusCode: 401,

│     RequestID: "f4ff6036-1493-44a0-b16b-3436d5b36728"

│   },

│   Code_: "InvalidAccessException",

│   Message_: "Account <REDACTED> is not an administrator for this organization"

│ }

│ 

│   with aws_securityhub_organization_configuration.enable_config_automatically,

│   on securityhub.tf line 6, in resource "aws_securityhub_organization_configuration" "enable_config_automatically":

│    6: resource "aws_securityhub_organization_configuration" "enable_config_automatically" {

│ 
```

### Expected Behavior
When enabling SecurityHub and delegating the account, the request should have been successful considering the account is the management account for Organizations.

Note that using ```aws securityhub enable-organization-admin-account --admin-account-id=<redacted>``` does work using the exact same privileges. 

### Actual Behavior
An error is raised stating that the account is not authorized to delegate the SecurityHub administrator to another account within the organization.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context
None

### References
None

**Comment by apparentlymart** [comment]
Hi @UrfTheManatee! Sorry for this confusing error.

This message seems to be coming from the AWS provider (probably, in turn, from the actual underlying AWS API) and so isn't something we can help with in this repository, which is focused on the core Terraform runtime and CLI tool.

I would suggest instead either starting a topic about this in [the AWS provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) or, if you believe this to be a bug in the AWS provider itself (rather than a problem with the underlying AWS API) then you could open an issue about it in [the `hashicorp/aws` provider's repository](https://github.com/hashicorp/terraform-provider-aws).

The codebase in this repository isn't involved in detecting this error, and so I don't think there's anything we could change here to avoid the problem you encountered, and so I'm going to close this issue. Thanks!
