### ISSUE TITLE
Terraform Provider Schema with TypeSet and inconsistent writing to tf state

### ISSUE THREAD

**Issue by biswaranjanb** [hashicorp/terraform#30304]
I am trying to update the tf state of a field with schema `TypeSet` by using d.Set(). 
It fails to take the one from code rather it takes it from the tf script

### Terraform Version
```
Terraform version: 1.0.0
Terraform plugin sdk version : 2.10.1
```

### Terraform Script File
```
resource "hola_ranjan" "test" {
  name = "Mutok"
  kids = [
    "Lamborghini"
  ]
}
```

### Terraform Provider Code
```
package provider

import (
    "context"
    "github.com/hashicorp/terraform-plugin-sdk/v2/diag"
    "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceTest() *schema.Resource {
    return &schema.Resource{
        CreateContext: resourceTestCreate,
        ReadContext:   resourceTestRead,
        UpdateContext: resourceTestUpdate,
        DeleteContext: resourceTestDelete,
        Schema: map[string]*schema.Schema{
            "name": &schema.Schema{
                Type:     schema.TypeString,
                Required: true,
            },
            "brands": &schema.Schema{
                Type:     schema.TypeSet,
                Required: true,
                Elem: &schema.Schema{
                    Type: schema.TypeString,
                },
            },
        },
    }
}

func resourceTestCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
    d.SetId("id")
    d.Set("name", "A-Class Limousine")
    d.Set("brands", []string{"Mercedes"})
    return nil
}

func resourceTestRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
    d.Set("name", "A-Class Limousine")
    d.Set("brands", []string{"MercedesRead"})
    return nil
}

func resourceTestUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
    d.Set("name", "A-Class Limousine Updated")
    d.Set("brands", []string{"MercedesUpdate"})
    return nil
}

func resourceTestDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
    d.SetId("")
    return nil
}
```

## go mod
It contains the below entry

```
github.com/hashicorp/terraform-plugin-sdk/v2 v2.10.1
```

### Expected Behavior
<p>
When setting `Mercedes` in Create method, it should set the same in tf state.
</p>

### Actual Behavior

<p>

Usually value I am using in d.Set should have updated in the tf state but its not.
I am passing `Lamborghini` in the tf script but setting `Mercedes` in Create method. 
Instead of tf state getting set to `Mercedes`, it sets `Lamborghini.`

</p>

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

Please let us know if there is a workaround for this.
As we have added many schema types where the list is unordered using TypeSet.

I would appreciate if there is a fix for this in upcoming releases.

**Comment by jbardin** [comment]
Hi @biswaranjanb,

Assuming the example here has a typo, and `kids` is supposed to be `brands`, then the behavior of what you are describing is correct. The only issue present is that to maintain compatibility with the legacy SDK, Terraform is not reporting the attempted change error. This is likely because the set normalization mode in the SDK is reverting the invalid change before Terraform sees it, but if it does come through, it would be recorded as a warning in the logs.

The fundamental rule here is that a resource cannot overwrite what is declared in the configuration. If you want to store extra information, you will need to add another computed attribute to the resource.

Since Terraform is working as expected, and any errant behavior shown is the result of the SDK, I'm going to close this out. 
If you have more question it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

Thanks!
