### ISSUE TITLE
filesha512 produces inconsistent results

### ISSUE THREAD

**Issue by debakkerb** [hashicorp/terraform#30305]
### Terraform Version
```
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files
```terraform
resource "random_string" "encryption_key" {
  keepers = {
    regenerate = 1
  }

  length = 32
  number = true
  lower  = true
  upper  = true
}

data "template_file" "encryption_key_config" {
  template = file("${path.module}/templates/encryption-config.yaml.tpl")

  vars = {
    ENCRYPTION_KEY = base64encode(random_string.encryption_key.result)
  }
}

resource "local_file" "encryption_key_config" {
  filename = "${path.module}/output/encryption-config.yaml"
  content  = data.template_file.encryption_key_config.rendered
}

resource "null_resource" "check_file_update" {
  triggers = {
    encryption_key_sha = fileexists("${path.module}/output/encryption-config.yaml") ? filesha512("${path.module}/output/encryption-config.yaml") : "Dummy"
  }

  provisioner "local-exec" {
    command = "echo -n \"File was updated!\""
  }

  depends_on = [
    random_string.encryption_key,
    local_file.encryption_key_config,
    data.template_file.encryption_key_config
  ]
}
```

```yaml
kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: key1
          secret: ${ENCRYPTION_KEY}
    - identity: {}
```
### Expected Behavior
I'm trying to trigger the `null_resource` every time the yaml is regenerated.  However, I see inconsistent behaviour, even when adding the `depends_on` and `triggers`.

I ran `terraform apply -auto-approve` a few times in succession, updating the `keepers`-block in between running the command.  What I noticed is that each time the file was regenerated, but only on few occasions was the `null_resource` triggered. 

However, when I re-ran apply without updating the `keepers`-block, it didn't regenerate the file, but it ran the `null_resource`-block.

When I checked the `sha512sum`, I saw that the checksum had changed, but apparently the `null_resource` didn't detect the change:

Here is an example when the file was regenerated, but where it didn't upload the files to the instances:
```shell
sha512sum encryption-config.yaml
cb0f5a7e64a58e12cc6f11880470694a72d1958ca590f14db0692070c977e1bf0d460b87fb3cc3308f62101cbeb6640ecb9a1b801941bb769bd6abad70c7f688  encryption-config.yaml

sha512sum encryption-config.yaml
b20e92d19bf78facf9f240c7da6a98b274648377dac91f696f676a13f8919b33c1e812a6349fbff88c723ce96a510b11cb9f7a8ad33490201a72daafb10f23d0  encryption-config.yaml
```

### Actual Behavior
Every time the `random_string` updates, it should also run the `null_resource` block.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -auto-approve`
3. Update the `keepers`-block with a new value (doesn't really matter which one)
4. `terraform apply -auto-approve`

Run steps 3 and 4 multiple times in quick succession and check if the `null_resource` is getting triggered.

### Additional Context
N/A

### References
N/A

**Comment by jbardin** [comment]
Hi @debakkerb,

Thanks for filing the issue. The problem is not with the result of `filesha512`, rather it is a combination of the deprecated `template` provider's behavior and trying to create a file as a result of the plan action.

When you replace `random_string`, the `template_file` output cannot be calculate until that resource is recreated, and the data is not available during the planning process. The `local_file` output will not be re-created until apply, so the `null_resource` is going to read the old data which was written during the previous run. If you start this process with no output file, you will get a `Error: Provider produced inconsistent final plan` error, indicating that the plan and apply data do not match, which is a result of the creation of the file during apply. 

This example would be more commonly handled by avoiding the intermediary file altogether:

```
resource "random_string" "encryption_key" {
  keepers = {
    regenerate = 1
  }

  length = 32
  number = true
  lower  = true
  upper  = true
}

locals {
  content  = templatefile("${path.module}/templates/encryption-config.yaml.tpl",
    {
      ENCRYPTION_KEY = base64encode(random_string.encryption_key.result)
    }
  )
}

resource "null_resource" "check_file_update" {
  triggers = {
    encryption_key_sha = sha512(local.content)
  }

  provisioner "local-exec" {
    command = "echo -n \"File was updated!\""
  }
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
