### ISSUE TITLE
Terraform for AWS Resource Group unable to have multi Tag Filter

### ISSUE THREAD

**Issue by veronicalim** [hashicorp/terraform#30319]
### Terraform Version

```
0.13
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

 ~ resource_query {
          ~ query = <<~EOT
                {
                  "ResourceTypeFilters": ["AWS::AllSupported"],
                  "TagFilters": [
                    {
                      "Key": "Workstream",
                      "Values": ["Tester"]
              -     }
              +     },
              +     {
              +       "Key": "Environment",
              +       "Values": ["SIT"]
              +     },
                  ]
                }
            EOT
            type  = "TAG_FILTERS_1_0"
        }
    }

### Expected Behavior

Terraform can applied and have both "Environment" and "Workstream" tag filter at resource group. I've tested via UI - this can be done but from terraform I cannot make it. 

### Actual Behavior

Error: error updating resource query for resource group (TEST-resource-group): BadRequestException: Query not valid: Query format not valid: check JSON syntax

### Steps to Reproduce

variable "workstream_names" {
  type = list
  default = ["Tester","Development"]
}

variable "env_list" {
  type = list
  default = ["DEV","SIT"]
}

resource "aws_resourcegroups_group" "resource-group" {
  count = length(var.workstream_names)
  name  = "${var.workstream_names[count.index]}-${var.env_list}"

  resource_query {
    query = <<JSON
{
  "ResourceTypeFilters": ["AWS::AllSupported"],
  "TagFilters": [
    {
      "Key": "Workstream",
      "Values": ["${var.workstream_names[count.index]}"]
    },
    {
      "Key": "Environment",
      "Values": ["${var.env_list[count.index]}"]
    },
  ]
}
JSON
  }
}

### References

I'm also trying to have workstream map with environment variable to be like this:
["Tester","DEV"]
["Tester","SIT"]
["Development","DEV"]
["Development","SIT"]

I've followed #22263 and managed to get the expected output however when I put to the resource group terraform it keep returning invalid JSON syntax

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

I suspect the problem is that your query argument is not valid json, with a trailing comma in the filters array. You may find the [`jsonencode`](https://www.terraform.io/language/functions/jsonencode) function helpful here, as you can supply the configuration objects directly without using a string template, and ensure the serialization is always valid json.

Thanks!
