### ISSUE TITLE
Terrraform 1.1+ (1.1.0, 1.1.1, 1.1.2, 1.1.3) panics with some OS/resource combinations [plugin.(*GRPCProvider).ApplyResourceChange call]

### ISSUE THREAD

**Issue by Didainius** [hashicorp/terraform#30323]
### Description

We, `terraform-provider-vcd` team, discovered what we think is a regression in Terraform 1.1+ (1.1.0 -
1.1.3) binary. Our plugin terraform-provider-vcd 3.5.0 uses terraform-plugin-sdk v2.10.0 and crashes
with Terraform 1.1+ (works fine with 1.0.11) 1.1+ also crashes with older version 3.4.0 which used
terraform-plugin-sdk 2.7.0. The crash happens always on OS versions that are affected , but only on several resources. The investigation here is based on one resource `vcd_catalog_item`

Here are the OS Version combinations we have tested:

These work fine:

* MacOS Big Sur 11.6.2 (Intel)
* Windows 10 Pro 20H2 OS Build 19042.631

These crash always:

* MacOs Catalina 10.15.7 (Intel)
* CentOS Linux release 8.4.2105
* Ubuntu 21.10

It is important to note that our code does not use custom OS specific features (except the ones that Go itself does)

It does not happen with all resources. So far we have found this particular resource in the bug to
demonstrate this issue. 

This is the code of resource which is known to fail:
https://github.com/vmware/terraform-provider-vcd/blob/ebfa7bb01f8bdb9f727d6ebcce5ff2f416e2eefb/vcd/resource_vcd_catalog_item.go

Tiny excerpt from that crash (complete logs are linked at the bottom)

```
$ terraform apply
...
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vcd_catalog_item.TestCatalogItemDS: Creating...
vcd_catalog_item.TestCatalogItemDS: Still creating... [10s elapsed]
vcd_catalog_item.TestCatalogItemDS: Still creating... [20s elapsed]
vcd_catalog_item.TestCatalogItemDS: Still creating... [30s elapsed]
vcd_catalog_item.TestCatalogItemDS: Still creating... [40s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with vcd_catalog_item.TestCatalogItemDS,
│   on main.tf line 43, in resource "vcd_catalog_item" "TestCatalogItemDS":
│   43: resource "vcd_catalog_item" "TestCatalogItemDS" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vcd_v3.5.0 plugin:

fatal error: runtime: netpoll failed

runtime stack:
runtime.throw({0xdd2116, 0xc000113840})
	runtime/panic.go:1198 +0x71
runtime.netpoll(0xc000058000)
	runtime/netpoll_epoll.go:131 +0x316
runtime.findrunnable()
	runtime/proc.go:2756 +0x185
runtime.schedule()
	runtime/proc.go:3367 +0x239
runtime.park_m(0xc000000b60)
	runtime/proc.go:3516 +0x14d
runtime.mcall()
	runtime/asm_amd64.s:307 +0x43

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc00018fe80)
	github.com/hashicorp/go-plugin@v1.4.1/server.go:469 +0x1493
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc000089260)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/plugin/serve.go:147 +0x8e5
main.main()
	github.com/vmware/terraform-provider-vcd/v3/main.go:9 +0x34
...
```

Build OS information used to make the release 3.5.0:
go version go1.17.5 darwin/amd64

#### Resource snippet that causes the crash:
```
resource "vcd_catalog_item" "TestCatalogItemDS" {
  org     = "dainius"
  catalog = data.vcd_catalog.cat-dainius.name

  name                 = "TestCatalogItemDS"
  description          = data.vcd_catalog_item.photon-hw11.id
  ova_path             = "/root/terraform-provider-vcd/test-resources/test_vapp_template.ova"
  upload_piece_size    = 5
  #show_upload_progress = "true"

  metadata = {
    catalogItem_metadata = "catalogItem Metadata"
    catalogItem_metadata2 = "catalogItem Metadata2"
  }
}
```

### Complete logs:

STDOUT log: https://gist.github.com/Didainius/c2ca6d4ce18ec3048758026dba649e34#file-stdout-crash

Terraform trace log: https://gist.github.com/Didainius/c2ca6d4ce18ec3048758026dba649e34#file-terraform-trace-log-ubuntu-crash

Terraform trace log from successful run: https://gist.github.com/Didainius/c2ca6d4ce18ec3048758026dba649e34#file-trace-of-succesful-run-macos-catalina

**Comment by jbardin** [comment]
Hi @Didainius,

The provider is run in a separate process from Terraform, and the provider should not crash regardless of what the Terraform process does, so this is curious that you are only able to see this with specific versions of the Terraform cli.

What are you showing here is a Go runtime fatal error, but I have not seen that except on unsupported kernels, which is not the case here. Is it possible there is some virtualization layer problem with the hosts you are testing? Are these virtualized on the same hardware?

Memory corruption could cause most anything to happen, and would be the first place I would look. Do you have any usage of `unsafe`, and have you checked for data races under load?

Since this is a crash in the provider, there's not much we can do from this side, but if you have standalone reproduction and the latest Terraform releases exacerbate the problem, we may be able to help troubleshoot.

Thanks!

**Comment by Didainius** [comment]
Thanks for quick response @jbardin,

We were further investigating the issue and looks like we have pinned this  down to printing to stdout in some of our
resources (just like the one crashing) for additional user information. Internally in our code we have a function `getTerraformStdout()` https://github.com/vmware/terraform-provider-vcd/blob/master/vcd/suppress_funcs.go#L55-L62
which we have used for at least a few years starting with Terraform 0.11+ I think. It looks that this
does not print to screen anymore, but instead breaks with Terraform 1.1+.

When our function `getTerraformStdout` is modified to immediately return `os.Stdout` - it does not crash (but does not print either)

Would this possibly give any hint to the cause of it?

```go
// getTerraformStdout returns std out to write message in terraform output
func getTerraformStdout() *os.File {
	// Needed to avoid errors when uintptr(4) is used
	if v := flag.Lookup("test.v"); v == nil || v.Value.String() != "true" {
		return os.NewFile(uintptr(4), "stdout")
	} else {
		return os.Stdout
	}
}
````

**Comment by jbardin** [comment]
Thanks @Didainius,

I'm not sure exactly how that is causing the failure, but attempting to get the stdout of the Terraform process is not supported. Up until v1.1, the primary core processes did hold stdout as fd 4 under normal circumstances (though not always), but I'm not sure how that was leaked back into the plugin, since I don't think extra file descriptors should be passed to the child process anywhere, and Windows doesn't really even support that. 

That internal quirk of the primary process being wrapped and having the real stdout moved to 4 however no longer exists, which may be the change that os triggering the problem, and writing to the non-existent file descriptor eventually leads to a runtime crash.

**Comment by Didainius** [comment]
Thanks @jbardin,
So is there no way to get stdout to users? Is there an option on the table to retun it back?

We find this useful for informing users.

**Comment by jbardin** [comment]
I think even though we are not directly passing in any extra files to the plugin, the duplicate FDs 3, 4, and 5 may still have existed in the child file descriptor table after fork, setting up network FDs on higher numbers and allowing the behavior you observed. Accessing stdout was never supported, so I don't think adding adding back the unintended behavior is going to be an option.

I can replicate the same crash with older version of terraform by setting the `TF_FORK=0` environment variable. I imagine this crashed because you are directly writing to a file descriptor held by a network port for grpc, and corrupting the polling mechanism.

**Comment by Didainius** [comment]
@jbardin,
Thanks for that explanation we removed the `getTerraformStdout` function and all our STDOUT. Was just wondering - is there any master issues we could watch or upvote. I have seen this - https://github.com/hashicorp/terraform/issues/17267 - just not sure if it is the master one.

Thanks for your explanations and help for making sure this is the reason.
