### ISSUE TITLE
`try` in for_each clause of module resource incorrectly errors on failed argument

### ISSUE THREAD

**Issue by G-Goldstein** [hashicorp/terraform#30324]
I'm using a `try` block to coalesce possible values in a `for_each` clause of a `module` resource:

```
module terraform_builds {
    for_each = try(local.terraform_builds, toset([]))

    source = "./terraform-builds"
    build = each.value
    build_name = each.key
    project = var.project
    ordering = try(each.value.ordering, null)
}
```

In this particular case, `local.terraform_builds` isn't defined, so I'm expecting it to use the second argument, the empty set. However, it instead fails on the `local.terraform_builds`:

```
╷
│ Error: Reference to undeclared local value
│ 
│   on common.tf line 8, in module "terraform_builds":
│    8:     for_each = try(local.terraform_builds, toset([]))
│ 
│ A local value with the name "terraform_builds" has not been declared.
╵
```

I expect the `try` function to catch the reported error and silently use the second parameter instead. 

I'm using Terraform 1.1.3.

**Comment by jbardin** [comment]
Hi @G-Goldstein,

Thanks for filing the issue. This would be the expected result of the given configuration. If the name `local.terraform_builds` does not exist in the configuration, there is no way to pass that value to the try function for evaluation. The relevant quote from [the documentation](https://www.terraform.io/language/functions/try)

> The try function can only catch and handle dynamic errors resulting from access to data that isn't known until runtime. It will not catch errors relating to expressions that can be proven to be invalid for any input, such as a malformed resource reference.

Since this is working as designed, and does not represent a bug in Terraform itself I'm going to close out the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. If you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
