### ISSUE TITLE
Terraform apply -replace option not shown in -help

### ISSUE THREAD

**Issue by HariSekhon** [hashicorp/terraform#30348]
Terraform's more recent `terraform apply -replace` switch isn't documented in `terraform apply -help`, even though it works on the command line.

### Terraform Version
```
Terraform v1.1.3
on darwin_amd64
```

Tried `terraform apply -replace` as a workaround, hit same issue in #30350

**Comment by jbardin** [comment]
Hi @HariSekhon,

Thanks for filing the issue. The key part of the help output here is the section 

```
  If you don't provide a saved plan file then this command will also accept
  all of the plan-customization options accepted by the terraform plan command.
  For more information on those options, run:
      terraform plan -help
```

And since `-replace` is a plan option, you will find it in the plan help output

```
  -replace=resource   Force replacement of a particular resource instance using
                      its resource address. If the plan would've normally
                      produced an update or no-op action for this instance,
                      Terraform will plan to replace it instead.
```

**Comment by HariSekhon** [comment]
Ah, but given this is also a switch to `terraform apply`, wouldn't it make sense to show it there too?

**Comment by jbardin** [comment]
It's only an option for `apply` if the `apply` command is also generating the plan (i.e. there's no plan file given). Also, because the CLI library we are using does not have a good method for nested sets of flags, maintaining the help text in one location prevents the text for plan options from becoming out of date under apply. The textual reference to the plan options is a compromise for now to ensure the output is always correct.

**Comment by HariSekhon** [comment]
I thought it might be something like that,ok , thanks for the explanation.
