### ISSUE TITLE
Backup copy action throwing error

### ISSUE THREAD

**Issue by infa-knaganat** [hashicorp/terraform#30366]
Hi Team,

Please check on the below issue

Terraform version-- v0.13.7

aws provider -  version = "2.43"

Getting below error in backup copy action

Terraform tf block
----------------------------------------------
 copy_action {
      lifecycle {
        delete_after = 7
      }
      destination_vault_arn = var.backup_vault_dr_arn
    }

Error Message
----------------------
Error: Unsupported block type

  on ../../../../../../modules/backup/backup.tf line 64, in resource "aws_backup_plan" "backup_vault_plan":
  64:     copy_action {

Blocks of type "copy_action" are not expected here.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

In this case you are using the AWS provider version 2.43, which did not support `aws_backup_plan` with the `copy_action` block. 

Thanks!
