### ISSUE TITLE
Update Dockerfile on hub.docker.com and include closed-source disclaimer

### ISSUE THREAD

**Issue by MicahParks** [hashicorp/terraform#30368]
The `Dockerfile` displayed at [https://hub.docker.com/r/hashicorp/terraform/dockerfile](https://hub.docker.com/r/hashicorp/terraform/dockerfile) has the following content:

```Dockerfile
FROM golang:alpine
MAINTAINER "HashiCorp Terraform Team <terraform@hashicorp.com>"

ENV TERRAFORM_VERSION=0.10.0

RUN apk add --update git bash openssh

ENV TF_DEV=true
ENV TF_RELEASE=true

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
    git checkout v${TERRAFORM_VERSION} && \
    /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["terraform"]
```

This isn't reflective of what's in the following images (and likely more):
* `hashicorp/terraform:latest`
* `hashicorp/terraform:1.1.3`

Particularly, the `go` CLI tool is not installed:
```
$ docker run --rm -it --entrypoint=sh hashicorp/terraform go
sh: can't open 'go': No such file or directory
```

I noticed that the `Dockerfile` in this repository has a couple comments such as:
> those images include only officially-released binary from releases.hashicorp.com and are by the (closed-source) official release process

I think the `Dockerfile` hosted on Docker Hub should be updated to the current repository's version. This will prevent people from assuming Go installed and trying to use it. Also, I'm sure some organizations would care about the disclaimer.

**Comment by apparentlymart** [comment]
Hi @MicahParks! Thanks for pointing this out.

We haven't been using the image build infrastructure provided by DockerHub for many years now, and so I assume that what you linked to there is whatever `Dockerfile` we used to produce the final release that we produced using that infrastructure, and so as you note it doesn't reflect the current process at all

In particular, it seems to be using a pretty different philosophy of building Terraform from source code inside the container, whereas our official release instead include a byte-for-byte copy of the `terraform` executable from the primary `.zip` release package for `linux_amd64` in an attempt to minimize the number of minor variants there are of a particular release, which might therefore inadvertently have different Go runtime build settings.

With that said, I don't think we actually know how to update (or, ideally, entirely remove) that `Dockerfile` archived on DockerHub. We could certainly do some more research to look into that, but I want to be honest that we probably won't prioritize it immediately because we're all busy with other work at the moment.

---

Relatedly, I'll note that we're actually in the process of migrating _back_ to having the release `Dockerfile` in this open source repository, as part of adopting a new release process strategy designed by HashiCorp's release engineering team. The new process has a different architecture where software in _this_ repository is responsible for building the source artifacts, and the private part of the process is concerned only with the steps that require access to sensitive information such as notarization API keys and signing private keys.

We've already completed a first step in that direction, meaning we now have [an open source `Dockerfile`](https://github.com/hashicorp/terraform/blob/main/.github/workflows/build-Dockerfile) available. At the time I'm writing this that isn't _yet_ the one we're using for official releases, but it's describing the same steps. Once the rest of the release pipeline is ready, that Dockerfile will be the one producing the official images on DockerHub. We could potentially then publish _that_ file on DockerHub, assuming we can figure out how to update the archived `Dockerfile` without reactivating the DockerHub-hosted build process.

(The `Dockerfile` assumes a particular execution context where the `terraform` executable is available in the host system, so it isn't something you could just trivially run outside of our build process anyway, but it would at least be a more accurate description of how the official images are built.)
