### ISSUE TITLE
Output variable in state file does not match remote state

### ISSUE THREAD

**Issue by lbodor** [hashicorp/terraform#30367]
### Terraform Version

```
Terraform v1.1.2
on linux_amd64
```

#### Step 1) main.tf

```terraform
variable "a" {
}

resource "aws_ssm_parameter" "a" {
  name  = "/a"
  type  = "String"
  value = var.a
}

output "a" {
  value = aws_ssm_parameter.a.value
  sensitive = true
}
```

#### Step 2) main.tf
```terraform
variable "a" {
}

resource "null_resource" "fail" {
  provisioner "local-exec" {
    command = "exit 1"
  }
}

resource "aws_ssm_parameter" "a" {
  name  = "/a"
  type  = "String"
  value = var.a
  depends_on = [
   null_resource.fail
  ]
}

output "a" {
  value = aws_ssm_parameter.a.value
  sensitive = true
}
```

### Expected Behavior

Running Step 1 above

```bash
TF_VAR_a=x terraform apply
```

works as expected. The SSM parameter is created with value `"x"`, and the output variable reflects this value. Running Step 2, however,

```bash
TF_VAR_a=y terraform apply
```

fails to update the SSM parameter, as expected, but it does update the output variable in the state file to `"y"`, resulting in unexpected behaviour where the output does not match the SSM parameter value.

### Actual Behavior

It looks like during the refresh stage, terraform updates the output with the value of the supplied variable, rather than the current state of the remote object, breaking what looks like should be an invariant given by

```terraform
output "a" {
  value = aws_ssm_parameter.a.value
  sensitive = true
}
```
that the output variable should track the value of the remote resource. My reading of the documentation matches my expectation that during the refresh stage terraform should update the state file to reflect the remote state.

**Comment by jbardin** [comment]
Hi @lbodor,

Thanks for filing the issue. In this configuration the value of the output `a` is not generated by the `aws_ssm_parameter.a` resource, it is already determined during the plan by the value of `var.a`. You can see this in the plan output, as it will show: 

```
Changes to Outputs:
  ~ a = "x" -> "y"
```

Since this was determined during the plan, the output value is already set in the refreshed state, and the resource apply failure has no effect on that value. You would also have the same effect on the output if you ran:

```
terraform refresh -var a=y
```

If you have more questions, please feel free to open a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). 

Thanks!
