### ISSUE TITLE
Long delay in s3 processing with bitbucket pipelines,

### ISSUE THREAD

**Issue by kytang-collectivfood** [hashicorp/terraform#30381]
I am working out the bitbucket pipelines with terraform deployment. It shows the following error in bitbucket-pipelines during the init step.

![image](https://user-images.githubusercontent.com/98108030/150368934-50ae081a-aef2-4c0b-899b-6737257a4b21.png)

However, I can init the same terraform script on my laptop. I don't think that is the s3 /  dynamoDB are outage or digest value is incorrect.

Does anybody hit the same error in bitbucket pipeline with terraform???

**Comment by jbardin** [comment]
Hi @kytang-collectivfood,

It's difficult to say for sure what could cause this without a complete example. The problem described is that the state data returned from S3 does not match what Terraform last stored. An inconsistency in S3 is unlikely now given the updated consistency guarantees, so that basically leaves external modification of the state as the only reasonable possibility.

Another process modifying the state data could cause this, or multiple Terraform configurations with different DynamoDB settings could also cause the observed behavior.

If you can reproduce the problem with a consistent configuration of the Terraform CLI, please feel free to open a new issue with all the requested information in the issue template.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by kytang-collectivfood** [comment]
Thank you
