### ISSUE TITLE
Date Function to Find Datestamp of Next Day of Week

### ISSUE THREAD

**Issue by bostrowski13** [hashicorp/terraform#30380]
I'm trying to be able to find the date of the next Sunday (or whatever day) of the week for use in scheduling OpenSearch maintenance window.

### Current Terraform Version
1.0+

### Use-cases
Automatically find the date of the next Sunday (or whatever day) to use in the maintenance schedule of OpenSerach.

```
auto_tune_options {
    desired_state       = "ENABLED"
    rollback_on_disable = "NO_ROLLBACK"
    maintenance_schedule {
      cron_expression_for_recurrence = "cron(${var.auto_tune_maintenance_schedule_cron_expression})"
      start_at                       = "2022-01-01T00:00:00Z" ### Ideally i could look this up
      duration {
        value = var.auto_tune_maintenance_schedule_duration
        unit  = "HOURS"
      }
    }
  }
```

### Attempted Solutions
There isn't enough functionality in the current functions to manipulate a date to find date of the next specified day of the week.

### Proposal

return DateStamp = findNextDate(timestamp(), "Day_Of_Week")

where `Day_of_Week` could be "SUN", "SUNDAY", or 0 (like cron).

### References

I know this type of manipulation can be done in bash, for example....
```
echo '1-Sep-2014\ +'{1..7}'\ days' | xargs -n1 date -d | grep Sun
```

**Comment by apparentlymart** [comment]
Hi @bostrowski13! Thanks for sharing this use-case.

Does the provider or remote API do something undesirable if you were to just set `start_at` to the current timestamp?

Not being familiar with this target system I guess my intuition from just what you shared would be that a maintenance window would start at any instant specified by `cron_expression_for_recurrence` _if and only if_ that instant is at or after the time given in `start_at`, in which case making the cron specify Sunday and the "start at" specify the current instant would get the effect of doing maintenance on the next Sunday, but I'm sure there's something more tricky going on here so I'd like to better understand how this system behaves, just so we can explore various possible solutions/designs to meet the use-case.

[The `hashicorp/time` provider](https://registry.terraform.io/providers/hashicorp/time/latest/docs) is intended to help with this sort of problem of "snapshotting" a particular timestamp at creation time and then possibly selectively rotating it over time, but after reviewing its features I don't think it has a ready solution for your use-case either. If we had a function like the one you described here then its result could potentially populate the `rfc3339` argument of [`time_static`](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/static), but I think it would also be worth considering whether that provider itself could get some extra capabilities for generating offsets, because I expect most realistic use of such a function would need to be in conjunction with the time provider's resources anyway, or else the configuration would never converge.

Thanks again!

**Comment by bostrowski13** [comment]
Hi, yes the resource to create an opensearch_domain requires that `start_at` is in the future (can't just use timestamp).  However Street reviewing the documentation it doesn't look like this is even used except to complete the API call to create the service.  

However in order to prevent plan/apply updates every run, the timestamp can't change which would trigger this 

The `time_static` resource you suggested send like the solution for this, and so far is working well.  

Thank you!

**Comment by bostrowski13** [comment]
Time_static is the solution for this
