### ISSUE TITLE
terraform init has a bug and it always fails 

### ISSUE THREAD

**Issue by bharathsajjala** [hashicorp/terraform#30392]
Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/oci:
│ could not connect to registry.terraform.io: Failed to request discovery
│ document: Get "https://registry.terraform.io/.well-known/terraform.json":
│ net/http: request canceled while waiting for connection (Client.Timeout
│ exceeded while awaiting headers)

I have tried the dns setting solution given but it doesn't work

**Comment by jbardin** [comment]
Hi @bharathsajjala,

Thanks for filing the issue. In order to determine if this is a bug in Terraform or now we are going to need more information about the failure.

Can you please provide the version of Terraform, the host operating system, any relevant host networking configuration?

Thanks!

**Comment by bharathsajjala** [comment]
Hi , 

terraform version -> v4.60.0
It is not working even with 8.8.8.8 in dns settings in system preferences as suggested in previous bug report.
After lot of struggle I have tried with out VPN and it worked for me. 


Thank you ...!

**Comment by jbardin** [comment]
Hi @bharathsajjala,

`v4.60.0` isn't similar to any Terraform releases, and the host OS would be helpful too. What is the output of `terraform version`? The latest release should work in most cases even with the VPN, unless there are other layers of security software blocking the access to the network.

**Comment by bharathsajjala** [comment]
terraform -v

Terraform v1.1.4

**Comment by jbardin** [comment]
Could you try initializing the configuration again with the following command? (either in a new directory, or after removing `.terrraform/` and `.terraform.lock.hcl`)

```
$ GODEBUG=netdns=1 tf init >/dev/null
```

What we're looking for here is the output `go package net: using cgo DNS resolver`, which means the problem is somewhere in the host's networking configuration. If the output is instead `go package net: built with netgo build tag; using Go's DNS resolver`, we may have a regression in the release process for that architecture.

Thanks!

**Comment by jbardin** [comment]
I downloaded and verified the official `v1.1.4` `darwin_amd64` release binary was built to use the host resolver, so there's probably nothing else to do here. If you do find otherwise with your binary, please let me know. Thanks!
