### ISSUE TITLE
not able to run terraform init with assume role and s3 as backend

### ISSUE THREAD

**Issue by jainpratik163** [hashicorp/terraform#30406]
Hi,
i am trying to run `terraform ini`t with s3 backend with profile but init is failing.

### Terraform Version

```
Terraform v1.0.8
```

### Terraform Configuration Files

provider.tf
```provider "aws" {
  region  = "eu-west-1"
  profile = "sts"
  assume_role {
    role_arn     = "arn:aws:iam::xxxx:role/TestAssumeRole"
    session_name = "my_external_id"
  }

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["xxxx"]
}
```
backend.tf
```
terraform {
  backend "s3" {
    bucket         = "tfstatefiles-mlt310-uat-xxxx-eu-west-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "main-modules/ms360-efs-tf-module/cid-mlt310/terraform.tfstate"
    region         = "eu-west-1"
    profile        = "sts"
  }
}
```

### Expected Behavior
terraform init should run successfully

### Actual Behavior
getting below error
      status code: 404, request id: 54F83A8FMYTQ10JX, host id: WECtNNV3N8uN3jBuO8big/5Eizg3Vu+DcG/MxWvdG2+DWDrUnNGnt4wPTxqkiv2UBHncbLxJJdM=
╷
│ Error: Failed to get existing workspaces: S3 bucket does not exist.
│
│ The referenced S3 bucket must have been previously created. If the S3 bucket
│ was created within the last minute, please wait for a minute or two and try
│ again.
│
│ Error: NoSuchBucket: The specified bucket does not exist
│       status code: 404, request id: 54F83A8FMYTQ10JX, host id: WECtNNV3N8uN3jBuO8big/5Eizg3Vu+DcG/MxWvdG2+DWDrUnNGnt4wPTxqkiv2UBHncbLxJJdM=
│

### Steps to Reproduce
1. `terraform init`

**Comment by justinretzolk** [comment]
Hey @jainpratik163 👋 I see that you're passing in both `profile` and `assume_role` to the `aws` provider declaration, but only `profile` to the backend configuration. Does the `sts` profile you're setting in the `backend` configuration have the necessary permissions to access the bucket that the state is stored in, or does it _also_ need to assume a role in order to access that bucket? If the latter is true, you may need to look at the [assume role configuration](https://www.terraform.io/language/settings/backends/s3#assume-role-configuration) section of the S3 backend configuration documentation and adjust it accordingly.

**Comment by asksmruti** [comment]
Found the same error today. Its working fine with terraform hashicorp/aws provider 3.x.x however on 4.x.x it's throwing the error.

**Comment by asksmruti** [comment]
> Hey @jainpratik163 👋 I see that you're passing in both `profile` and `assume_role` to the `aws` provider declaration, but only `profile` to the backend configuration. Does the `sts` profile you're setting in the `backend` configuration have the necessary permissions to access the bucket that the state is stored in, or does it _also_ need to assume a role in order to access that bucket? If the latter is true, you may need to look at the [assume role configuration](https://www.terraform.io/language/settings/backends/s3#assume-role-configuration) section of the S3 backend configuration documentation and adjust it accordingly.

I am using only profile, still the same error -

**Comment by justinretzolk** [comment]
Hey @asksmruti 👋 Thank you for the additional context. Given that you're seeing errors with a specific AWS provider version, I believe that'll be separate from this issue, as I don't believe that the AWS Provider version has any impact on authentication for the S3 backend. Would you mind opening an issue in the [AWS Provider repository](https://github.com/hashicorp/terraform-provider-aws/issues) with details of what you experienced so that we can look into that?

**Comment by crw** [comment]
Closing per https://github.com/hashicorp/terraform/issues/30406#issuecomment-1055716892.
