### ISSUE TITLE
Terraform graph does not produce cycles while apply does

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform#30407]
### Terraform Version

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v4.7.0
+ provider registry.terraform.io/hashicorp/google-beta v4.7.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/innovationnorway/git v0.1.3
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
+ provider registry.terraform.io/terraform-providers/docker v2.7.2
```

### Terraform Configuration Files

https://gist.github.com/AndreasBergmeier6176/e8adeaa87a54841e64e27bf2393570ec/c617710775bbcbf951ff0f537ed55ed0730419eb

### Debug Output

https://gist.github.com/AndreasBergmeier6176/e8adeaa87a54841e64e27bf2393570ec/575b19cf89a98dae85c1596dc248c5e60c91c708

### Expected Behavior

If there really is a cycle, `terraform graph -type=apply -draw-cycles` should display it.

### Actual Behavior

`terraform apply` complains:

> Error: Cycle: module.c.google_compute_instance_template.pull (destroy deposed 83fe0757),
module.o.google_compute_instance_template.integration_test,
<...>

`terraform graph -type=apply -draw-cycles | grep red` finds no edge.

See https://gist.github.com/AndreasBergmeier6176/e8adeaa87a54841e64e27bf2393570ec/91b48e52dc6d95dd801e857986015b1e396e8103

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

and

1. `terraform init`
2. `terraform graph -type=apply -draw-cycles`

**Comment by AndreasBergmeier6176** [comment]
From a first glance `writeBody` uses a different algorithm than `Cycles` to detect cycles.

**Comment by apparentlymart** [comment]
Hi @AndreasBergmeier6176,

Creating an "apply" graph requires a plan, because that graph type is constructed from the result of the planning phase rather than from your original input configuration.

Unfortunately a historical bug, which we've preserved for compatibility for now, means that `terraform graph -type=apply` without a saved plan produces the graph of an _empty_ plan, which is of course useless because it provides no interesting feedback whatsoever.

However, I would expect you to be able to get a result more like what you expected if you save a plan file first and then pass that to your `terraform graph` call, like this:

```
terraform plan -out=tfplan
terraform graph -type=apply -draw-cycles -plan=tfplan
```

---

Incidentally, if the result of this investigation is that you get some concrete information on a situation where Terraform produces a cycle during the apply phase but not in the planning phase, we'd love to see another bug report about that because it seems like these problems crop up occasionally but so far we've not been able to gather enough information to reproduce it reliably. Our design intent is that Terraform should always detect all possible cycles during the planning phase, and so we're eager to learn more so that we might fix the root cause of the bug you've encountered here.

**Comment by AndreasBergmeier6176** [comment]
Thanks for explaining this in detail.

> Unfortunately a historical bug, which we've preserved for compatibility for now, means that terraform graph -type=apply without a saved plan produces the graph of an empty plan, which is of course useless because it provides no interesting feedback whatsoever.

That is all fine BUT maybe I am blind but there seems to no such notion in https://www.terraform.io/cli/commands/graph. I think this is then at least a doc bug.

**Comment by AndreasBergmeier6176** [comment]
> Incidentally, if the result of this investigation is that you get some concrete information on a situation where Terraform produces a cycle during the apply phase but not in the planning phase

It definitely is the case that we do not see a cycle when executing `plan` but only when executing `apply`.
We can provide our environment but have a very hard time extracting a minimal repo case.

---

Also, what we did was write a script for pruning all non-cycle edges in dot files.

A short summary of our modules:


- **ac**
  - consumes output from **d**
  - consumes output from **c**
- **d**
  - consumes output from **f**
  - consumes output from **s**
  - consumes output from **c**
- **s**
  - consumes output from **c**
- **f**
  - consumes output from **c**
- **c** 

Now when I look at the cycle edges which terraform graph produces I see:

**ac** -> **s** -> **d** -> **s** -> **f** -> **ac** -> **s** -> **c** -> ... -> **d** -> **ac**

So from a naive look - such a graph should never be produced and I would deem it impossible since our modules are acyclic.
Now there is the possibility, that edges in terraform graph have duplicate meanings but still - the cycle that terraform is reporting I cannot find in the dependencies between modules.

**Comment by jbardin** [comment]
Not all cycles are detectable within the plan graph, because the it does not contain all the information which will be used to apply the changes. The complete set of instances to be created and destroyed is not known at plan time, the plan is the point at which we compute that set of instances, and it's only during apply do they get fully realized and connected into a graph.  

Because the individual create and destroy instances are not wired up until apply, it is possible to introduce changes into the configuration which could effect the graph only at that point. An example would be changing the direction of a dependency while also replacing some of those dependencies -- the stored instances will have a different order for destruction than the new instances, which will introduce cycles.

The apply graph much larger and more complex than the plan graph, therefor the output tends to be even less useful as an end-user. There are probably also some vestiges of very old code there which tried to elide "internal" nodes from the user output to make the graph easier to understand, and as a side effect it could disconnect portions of the graph output. While we would like to eventually improve the graph output to make it more useful to end users, I think complex cycle detection is a different problem. A graph with thousands of nodes highlighting a few edges between some internal implementation details is really no more helpful than the condensed cycle output, we need to somehow translate that cycle to something more actionable by users.

If creating an "apply" graph with a complete plan (`terraform graph -type=apply -draw-cycles -plan=tfplan`) does not show the same cycle you encounter during apply, that would be a good example to double check how the dot graph is produced.

**Comment by AndreasBergmeier6176** [comment]
> If creating an "apply" graph with a complete plan (terraform graph -type=apply -draw-cycles -plan=tfplan) does not show the same cycle you encounter during apply, that would be a good example to double check how the dot graph is produced.

Sorry, I forgot to mentioned that I followed @apparentlymart advice and already am using `terraform graph -type=apply -draw-cycles -plan=tfplan` now.
It does produce cycles which are similar to `apply`.
Incidentally I just now produced a graph where cycle edges did not connect to a cycle at all (which they previously did).
Now I am at a bit of a loss - what would be the best steps to get to a working deployment again?
We are doing automated deployment so manually removing resources over and over to fix these cycles is not a good strategy.

**Comment by jbardin** [comment]
@AndreasBergmeier6176, What if any configuration changes are made leading up to the error?
 can you show the full cycle output? That may provide enough context to deduce what is setting up the cycle.

**Comment by AndreasBergmeier6176** [comment]
> What if any configuration changes are made leading up to the error?

Basically some additional modules and changing some resources to `create_before_destroy`.
Cleanup mostly.

> can you show the full cycle output?

The censored cycle looks like this:
```
Cycle: google_pubsub_subscription.o (destroy),
module.d.local.cloud_init_content (expand),
module.controller.docker_registry_image.service (destroy deposed e2082d58),
module.s.local.cloud_init (expand),
module.s.output.cloud_init (expand),
module.d.var.scores (expand),
module.f.local.cloud_init (expand),
module.f.output.cloud_init (expand),
module.d.var.features (expand),
module.d.local.image (expand),
module.d.local.cloud_init_integration_test_content (expand),
module.d.google_compute_instance_template.integration_test,
module.d.google_compute_instance_template.pull (destroy deposed d06043ef),
module.d.docker_registry_image.service (destroy deposed e4913ccf),
module.controller.var.artifact_registry_repository (expand),
module.controller.local.repository (expand),
module.controller.docker_image.service,
module.controller.docker_registry_image.service,
module.controller.docker_registry_image.service (destroy deposed 8d778f5c),
module.s.local.image (expand),
module.s.local.cloud_init_content (expand),
module.s.google_compute_instance_template.integration_test,
module.s.docker_registry_image.service,
module.s.var.artifact_registry_repository (expand),
module.s.local.repository (expand),
module.s.docker_image.service,
module.d.docker_registry_image.service,
module.f.local.image (expand),
module.f.local.cloud_init_content (expand),
module.f.google_compute_instance_template.integration_test,
module.f.var.artifact_registry_repository (expand),
module.f.local.repository (expand),
module.f.docker_image.service,
module.f.docker_registry_image.service,
module.ac.google_compute_autoscaler.pull (destroy deposed 5c00dd4d),
google_artifact_registry_repository_iam_policy.a (destroy),
module.d.google_compute_instance_template.pull,
module.d.output.compute_instance_template_pull (expand),
module.ac.var.donkey_instance_template (expand),
module.ac.google_compute_instance_group_manager.pull,
module.ac.google_compute_autoscaler.pull,
module.s.docker_registry_image.service (destroy deposed 0fad23fe),
google_artifact_registry_repository.a (destroy),
module.aco.google_artifact_registry_repository.default,
module.aco.output.artifact_registry_repository (expand),
module.d.var.artifact_registry_repository (expand),
module.d.local.repository (expand),
module.d.docker_image.service,
module.d.google_compute_instance_template.integration_test (destroy deposed 7d1751d7),
module.s.google_compute_instance_template.integration_test (destroy),
module.aco.google_artifact_registry_repository_iam_policy.default,
module.ac.google_compute_instance_group_manager.pull (destroy deposed da7f7a5a),
google_pubsub_subscription_iam_policy.o (destroy),
google_pubsub_topic.o (destroy)
```

**Comment by jbardin** [comment]
"changing some resources to `create_before_destroy`" is an example of what I mentioned earlier of reversing some dependencies in the configuration. While not quite the same as inverting references, some of the destroy order is being inverted.

Is it possible to modify the `create_before_destroy` separately from the resource changes, so that the instance state can be updated?

**Comment by AndreasBergmeier6176** [comment]
> Is it possible to modify the create_before_destroy separately from the resource changes, so that the instance state can be updated?

Well yes I can move `create_before_destroy` into another branch.

We do have big workspaces where this kind of problem keeps coming up more and more. From what I have been understanding Terraform currently cannot solve these kind of configurations on itself (e.g. applying tier create graph and later a tier delete graph). Maybe we have been using Terraform too naive so far...
