### ISSUE TITLE
Provider produced inconsistent final plan on aws_lambda_function {source_code_hash}

### ISSUE THREAD

**Issue by nashgongchan** [hashicorp/terraform#30411]
Terraform v0.15.0
on linux_amd64

I am getting "**Error: Provider produced inconsistent final plan**"

Some brief scenario, I had successfully applied the operation using "**source_code_hash = "${data.archive_file.zip.output_base64sha256}**"" method. Due to hashing replacement without any changes on the script (_main.py_), I decided to change my syntax to "**filebase64sha256("${data.archive_file.zip.output_path}")**".

With this action, I am getting an error as below:
**│ When expanding the plan for
│ module.xxxxx.aws_lambda_function.lambda-function to include new values
│ learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
│ produced an invalid new value for .source_code_hash: was
│ cty.StringVal("xxxxx"), but now
│ cty.StringVal("xxxx").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.**

To resolve this issue, I need to delete the existing lambda and create lambda again with the new syntax, which something that I cannot afford to produce on production environment.

Please advise/help to resolve this error. Thank you

**Comment by msridhar1203** [comment]
Yes. This is an issue we are also facing

**Comment by jbardin** [comment]
Hi @nashgongchan,

There are a few possible problems here, but this type of error is usually due to the use of `data.archive_file` to create an archive which is based on some other resource in the configuration. If the file can change between the plan and apply, the data source will not be able to read the correct data during the plan. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. When starting a topic there, please include a minimum reproducible example which shows the issue you are having so that we can better understand your problem.

Thanks!
