### ISSUE TITLE
Mark resource as OK

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#3041]
So, we have 'taint' that allows us to force a resource to be recreated.

It would be nice to have something similar, but to mark a resource as having been deployed correctly, even if Terraform thinks it's not.

Let me explain that a bit. Sometimes, while using the Chef provisioner, Chef won't exit 0. In most cases, it's just a warning. But the actual Chef run completed. Problem is, as far as Terraform is concerned, it needs to recreate that instance again. Which is a bit silly.

It's possible to hack the state file manually to fix that. But that seems error prone. And if you use a remote state file, you can't do it unless you disable the remote state first, hack your state file, and re-enable it remotely. A lot of work too.

**Comment by apparentlymart** [comment]
This is of course just a deeper hack rather than a solution, but you can edit manually a remote state by changing the local state, increasing the serial number near the top, and then running "terraform remote push" to force your new version to be uploaded.

I am a fan of the general idea of having some "escape hatch" commands that help you safely make changes to the state. The idea of putting a pre-existing resource id in there too "adopt" something into Terraform seems related... In both cases you are overriding Terraform's idea of the world to tell it about things it can't know on its own.

So :+1: !

**Comment by failshell** [comment]
Good to know. You optimized my ugly hack ;)

**Comment by apparentlymart** [comment]
We now have [`terraform untaint`](https://www.terraform.io/docs/commands/untaint.html), which I think addresses what was proposed here.

In addition, the subcommands of [`terraform state`](https://www.terraform.io/docs/commands/state/index.html) give us additional ways to do "state surgery" without risking syntax errors, to fix other sorts of problems.

So @failshell I'm going to close this now, since I think it's been addressed... but feel free to reopen if you think I'm mistaken.

**Comment by failshell** [comment]
That's exactly what I needed. Thanks.
