### ISSUE TITLE
`destroy` is allowed without config, but `init` cannot get providers with only state

### ISSUE THREAD

**Issue by ashishpm** [hashicorp/terraform#30437]
### Terraform Version

```
Terraform v0.13.2
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
    }
  }
  required_version = ">= 0.13"
}

resource "local_file" "test_local_file" {
  content = "This is a test file"
  filename = "test.txt"
}
```

### Expected Behavior

I am using terraform v0.13.2 after running terraform init, plan, apply when I take the terraform.tfstate file to another directory and use terrafrom v1.1.2 to destroy the configuration (terraform init, destroy) I should see the resources are deleted.

### Actual Behavior

But I am getting the following error: 
```
Error: Missing resource schema from provider
No resource schema found for local_file.
```
But using terraform v1.0.11 I am able to delete the resource.

### Steps to Reproduce

1. Copy the above configuration and run following `terraform init`, `terraform apply` using version v0.13.2
2. Make a new directory and copy the terraform.tfstate file generated in step 1
3. Using terraform v1.1.2 run `terraform init`, `terraform destroy` in the new directory

Any idea how to fix this issue?

**Comment by jbardin** [comment]
Hi @ashishpm,

Thanks for filing the issue. I'm not able to replicate the error you are showing with the v1.1 branch or the current development branch. Can you supply the trace logs from the failed `terraform destroy` command? Those may help identify the difference in your environment.

Thanks!

**Comment by ashishpm** [comment]
Hi @jbardin 
I am attaching the trace logs 
[output.txt](https://github.com/hashicorp/terraform/files/7960743/output.txt)

**Comment by jbardin** [comment]
Thanks @ashishpm,

When you moved to new directory, it appears you are not also copying the configuration. Since the stored providers are missing, and there is no configuration to locate providers, trying to destroy the state is failing to find a suitable provider for the given resource. This is not related to changing terraform versions, it would happen regardless of whether you stayed on v0.13 or started with v1.1. 

Running a normal plan at this point shows the error `Error: No configuration files`. While running `destroy` without a config is allowed though not recommended (I think that was left for backwards compatibility), it requires the providers to still be available to complete the process. Keeping the configuration in the working directory will avoid the error you're seeing, and allow the `init` process to work correctly.

**Comment by ashishpm** [comment]
@jbardin,
Keeping the `local` provider configuration in the working directory did solve the issue.

But I still have two queries:
1. Without config, `terraform init` with only state file gives following output :
```
ashishmurali@ashishmurali-mac test % terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/local...
- Installing hashicorp/local v2.1.0...
- Installed hashicorp/local v2.1.0 (signed by HashiCorp)
```
Doesn't it mean that terraform was able to locate the provider using only the state file?

2. The issue only happens with I try to destroy using v1.1, with earlier terraform versions we can destroy using only the state file

Thanks
