### ISSUE TITLE
terraform init not downloading anything 

### ISSUE THREAD

**Issue by bharathsajjala** [hashicorp/terraform#30456]
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Installing hashicorp/oci v4.61.0...

and it waits infinitely

**Comment by bharathsajjala** [comment]
Terraform v1.1.4

It is working with existing modules for which there is a lock file already present.
But for new folders/modules it is stuck

**Comment by apparentlymart** [comment]
Hi @bharathsajjala!

In order to proceed further here, we will need the detailed trace logs to see exactly where in the process Terraform is getting blocked.

To get that, use the following steps.

1. Set the environment variable `TF_LOG=trace` in your shell
2. Run exactly the same command you ran before, which should therefore achieve the same result you reported (Terraform getting blocked) but now with much more detailed trace logging.
3. Once Terraform seems to be blocked, interrupt it the same way you did before (Ctrl+C, or similar).
4. Copy and paste the full log output into a [GitHub Gist](https://gist.github.com/) and share a link to it here.

Thanks!

**Comment by jbardin** [comment]
Closing since we have not heard back in a while. If you do have more information and can supply a reproducible example, feel free to reply here or file a new issue with the information requested in the issue template.

Thanks!
