### ISSUE TITLE
TERRAFORM CRASH  Terraform version :  1.1.0 Error : runtime error: invalid memory address or nil pointer dereferencegoroutine 2983 [running]: runtime/debug.Stack()

### ISSUE THREAD

**Issue by rpuranik-tlx** [hashicorp/terraform#30455]
### Terraform Version

```
1.1.0
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hi @rpuranik-tlx,

Please try your configuration with the latest release of Terraform to ensure we're not looking a bug which has already been fixed. If you can replicate the crash, we will need the information requested in the issue template in order to help diagnose what the issue might be.

Thanks
