### ISSUE TITLE
nil entry while state import  databricks_cluster

### ISSUE THREAD

**Issue by davidxianggao** [hashicorp/terraform#30463]
=========== TF version ===========
> terraform version
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.11
+ provider registry.terraform.io/hashicorp/azuread v2.16.0
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/vault v2.24.1

=========== Error ===========
> tf import databricks_cluster.example 0123-456789-7ya8xyyz
databricks_cluster.example: Importing from ID "0123-456789-7ya8xyyz"...
╷
│ Error: nil entry in ImportState results. This is always a bug with
│ the resource that is being imported. Please report this as
│ a bug to Terraform.

=========== TF code ===========
resource "databricks_cluster" "example" {
}

**Comment by jbardin** [comment]
Hi @davidxianggao,

Sorry about the confusing error message here, it is correct that the bug is within the resource being reported, but it should be reported with the provider, not Terraform. Unfortunately this error message is outside of our direct control, as it is contained within the legacy provider SDK.

Since it is a bug in the provider, not with Terraform itself, I'll close this issue. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
