### ISSUE TITLE
Rename of state resource recursively applied to child resources?

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#30473]
Hello, I need to rename _(internal Terraform resource name)_ a AWS security group and all its `aws_security_group_rule` references for a large VPC migration.

Trying to do:

```
terraform state mv aws_security_group.vpn aws_security_group_rule.legacy-vpn
```

But the security group `vpn` has child `aws_security_group_rule` that reference the old security group name like:

```
resource "aws_security_group_rule" "vpn_ingress_4500" {
  type      = "ingress"
  from_port = "4500"
  to_port   = "4500"
  protocol  = "udp"

  cidr_blocks = [
    "0.0.0.0/0",
  ]

  security_group_id = aws_security_group.vpn.id
}
```

Will running the move automatically update the reference of each child `aws_security_group_rule` from `security_group_id = aws_security_group.vpn.id` to `security_group_id = aws_security_group.legacy-vpn.id`?

**Comment by jbardin** [comment]
Hi @nodesocket,

The `terraform state` commands only operate on the state, they do not effect the configuration in any way. 
The pattern we've chosen for future refactoring work however is based on the configuration itself, and therefore may be of use to you in this situation: https://www.terraform.io/language/modules/develop/refactoring

While the `moved` block does not attempt to rewrite configuration at all, it must be present along with the correct configuration changes in order for the plan to succeed. There is no way to define a set relationships between resources, or guarantee specific sources of data except for the configuration itself, so there would be no way for refactoring tools to understand which attributes you might want to update when moving resources leaving that to always be manual part of the refactoring operation.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
