### ISSUE TITLE
Make the sort function works with list of number or create 2 new function for list of numbers

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform#30475]
### Current Terraform Version

```
Terraform v1.1.5
on linux_amd64
```

### Use-cases

Actually, the `sort` function only support list of string. If we pass a list of number, they will be convert to list of string and sort lexicographically. 
This make this function un-usable with number of different size. 

Here is the result of the actual `sort` function: 

```
$ terraform console 
> sort([50, 0, 100])
tolist([
  "0",
  "100",
  "50",
])

```

### Attempted Solutions

The correct result should be a list of number correctly sorted

```
$ terraform console 
> sort([50, 0, 100])
tolist([
  0,
  50,
  100,
])
```

### Proposal

Do not convert list of number to list of string, and sort it by numerical value. 
Maybe we can keep `sort` as is, and create new function to sort by ascending or descending
`order(list(number), [direction = ascending])`

**Comment by crw** [comment]
Thanks for the new feature request!

**Comment by apparentlymart** [comment]
Hi @quentin9696! Thanks for sharing this feature request.

Could you also say a little about what underlying reason is causing you to need to sort a list of numbers numerically? This is the first time we've heard about such a need, and so learning more about what underlying problem you are aiming to solve can help to evaluate several different solutions to a problem. Thanks!

**Comment by drandell** [comment]
@apparentlymart one of our use-cases is that we currently have a dynamic block of arguments in a terraform resource, the end users want to supply them in a specific order but by default the for-each is sorting the map. 
When we append a numerical prefix such as 1_arg, 2_arg if the user supplies 10+ args, its then 1_arg, 10_arg, 11_arg which throws the order out of sync due to lexical sorting.

**Comment by apparentlymart** [comment]
Thanks for sharing a use-case, @drandell!

For your specific use-case, with Terraform as it exists today I'd suggest using zero-padded numbers so that the lexical sort will achieve the same result as a numeric sort. For example:

```hcl
locals {
  inputs = ["arg", "arg", "arg", "arg"]

  keys = [ for i, arg in local.inputs : format("%03d_%s", i, arg) ]
}
```

The above would make `local.keys` be `["000_arg", "001_arg", "002_arg", "003_arg"]`, which is therefore compatible with a lexical sort while preserving the original order.

However, if you literally mean [a `dynamic` block](https://www.terraform.io/language/expressions/dynamic-blocks) then it may be useful to know that a `dynamic` block can accept any type of collection, including ordered lists, because `dynamic` blocks don't need to do any tracking of individual instances between runs in the way that resource-level `for_each` would. Therefore the `local.inputs` in my example above is already a suitable collection for `dynamic` block `for_each`, with `each.key` giving the index of each element:

```hcl
  dynamic "example" {
    for_each = local.inputs
    content {
      index = each.key
      arg   = each.value
    }
  }
```

If you don't actually need to _use_ the index, and only care about preserving the order, you can just omit any references to `each.key` inside the `content` block. As long as the value you pass to `for_each` is a list, the generated blocks will follow the same ordering as the list elements.

The zero-padding advice from above would still apply for generating keys for resource-level or module-level `for_each`, because in that case Terraform _does_ need a unique tracking key string for each instance, but there's no inherent sense of ordering between instances of a resource or module and so sorting _those_ would be useful only if you are making use of the resulting objects elsewhere in your module, and want to use them in the order they were originally provided. It would probably be more appropriate to use `count` in situations like that, though.

**Comment by quentin9696** [comment]
Hi, 

Sorry for the late reply. 

I'm the same usecase. I would like to passe a map for resource creation, prioritize by the user. 
I plan to use a list of map, to keep order, but I got this error message `The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of type list of object.`. To avoid that limitation, I need to tell user of my module to explicitly define a priority. 

With you workaround, you tell me I can add zero pad to avoid my issue. 

So, here is my workaround to bypass the initial limitation with for_each: 

```hcl
variable "input" {
  type = map(object({
    priority = number
    other_value = string
  }))
  default = {
    name1 = {
      priority = 2
      other_value = "foo"
    }
    other_name = {
      priority = 1
      other_value = "bar"
    }
    just_another = {
      priority = 11
      other_value = "baz"
    }
  }
}

locals {
  order_list = sort([ for k, v in var.input: format("%03d", v.priority)])
  list_of_ordered_index_by_priority = flatten([
    for priority in local.order_list : [
      for k, v in var.input : k if format("%03d", v.priority) == priority
    ]
  ])
}

# In my use case, this null resource is a tempalate_file data source
resource "null_resource" "initial_values_transform" {
  for_each = toset(local.list_of_ordered_index_by_priority)

  triggers = {
    name = each.key
    other_value = var.input[each.key].other_value
    priority = var.input[each.key].priority
  }
}

# In my use case, this null_resource in a ct_config data source form ct_poseidon provider
resource "null_resource" "other_resource_with_priority" {
  triggers = {
    content = null_resource.initial_values_transform[local.list_of_ordered_index_by_priority[0]].triggers.other_value
    # I transform this to a string because null resource don't accept collections
    snippets = join(", ", [
      for index in slice(local.list_of_ordered_index_by_priority, 1, length(local.list_of_ordered_index_by_priority)):
        null_resource.initial_values_transform[index].triggers.other_value
    ])
  }
}

output "initial_values_transform" {
  value = null_resource.initial_values_transform
}

output "other_resource_with_priority" {
  value = null_resource.other_resource_with_priority
}

output "list_of_ordered_index_by_priority" {
  value = local.list_of_ordered_index_by_priority
}
```

I think it's a very complex workaround, and is not bullet proof (i.e 2 priority are equal). 

Maybe I miss an important feature of Terraform to solve my issue

**Comment by apparentlymart** [comment]
Hi @quentin9696,

I think the following is a shorter way to achieve your prioritized list of input objects:

```hcl
locals {
  prioritized_input = values({
    for k, v in var.input : format("%03%s", v.priority, k) => {
      name        = k
      other_value = v.other_value
    }
  })
}
```

With the default value you showed in your example, the resulting `local.prioritized_input` would be the following:

```hcl
[
  {
    name        = "other_name"
    other_value = "bar"
  },
  {
    name        = "name1"
    other_value = "foo"
  },
  {
    name        = "just_another"
    other_value = "baz"
  },
]
```

This result is ordered first by priority number (lowest first) and then by name lexically if two of the input objects have the same priority.

Note that when using `for_each` inside a `resource`, `data`, or `module` block Terraform does not apply any ordering to the instances and will in fact work on them all concurrently when possible. This ordered version may still be useful for other work in your module, such as with a `dynamic` block as we saw in the previous comments, but ordering a collection for `resource`-level `for_each` is never useful, because Terraform does not make any use of that ordering.

**Comment by quentin9696** [comment]
Hi @apparentlymart , 

Thank you for your reply. 
I know that priority is not keep with TF resource creation, but I was trying to keep my resource names with `for_each` clean. Your solution is the better and solve my issue with duplicated priority. 

I post the solution I use just in case somebody needs an example: 

```hcl 
terraform {
  experiments = [module_variable_optional_attrs]
}

variable "input" {
  type = map(object({
    priority    = optional(number)
    other_value = string
  }))
  default = {
    name1 = {
      priority    = 2
      other_value = "foo"
      vars        = "foo"
    }
    other_name = {
      priority    = 1
      other_value = "bar"
    }
    just_another = {
      priority    = 2
      other_value = "baz"
    }
  }
}

locals {
  prioritized_input = values({
    for k, v in var.input : format("%03d%s", v.priority == null ? 10 : v.priority, k) => {
      name = k
    }
  })
}

# In my use case, this null resource is a tempalate_file data source
resource "null_resource" "initial_values_transform" {
  for_each = var.input

  triggers = {
    name        = each.key
    other_value = var.input[each.key].other_value
    priority    = var.input[each.key].priority
  }
}

# In my use case, this null_resource in a ct_config data source form ct_poseidon provider
resource "null_resource" "other_resource_with_priority" {
  triggers = {
    content = null_resource.initial_values_transform[local.prioritized_input[0].name].triggers.other_value
    # I transform this to a string because null resource don't accept collections
    snippets = join(", ", [
      for key in slice(local.prioritized_input.*.name, 1, length(local.prioritized_input)) :
      null_resource.initial_values_transform[key].triggers.other_value
    ])
  }
}

output "initial_values_transform" {
  value = null_resource.initial_values_transform
}

output "other_resource_with_priority" {
  value = null_resource.other_resource_with_priority
}

output "list_of_ordered_index_by_priority" {
  value = local.prioritized_input
}
```
