### ISSUE TITLE
Terraform Cloud: Add support for installing binaries (i.e. Helm) to remote instances that execute terraform runs

### ISSUE THREAD

**Issue by rsmets** [hashicorp/terraform#30472]
I would like I way to customize the runtime env for the remote Terraform runs on the Terraform Cloud, (i.e. add binaries, plugins, etc ).

### Use-cases
So can install things like Helm for use with the Helm provider on remote runs.

### Attempted Solutions
Looked all over docs, issues and on the forum. Seems like no way to define a custom runtime env or install additional binaries. 

### Proposal
Firstly, it would be nice if there were a place to support Terraform Cloud specific feature requests. 

In regard to setting up the remote instance with the necessary peripheral binaries, I would suggest allowing one to define a Vagrant image which the instance uses for its env during runs.

**Comment by crw** [comment]
Hi! Thanks for reporting this.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can ask for help on our [Terraform Cloud & Enterprise forum](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44), or report a bug by contacting the Terraform Cloud support team at tf-cloud-support@hashicorp.com. If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
