### ISSUE TITLE
Terraform interactive input doesn't work with the root module.

### ISSUE THREAD

**Issue by rahtr** [hashicorp/terraform#30478]
### Terraform Version

```
Terraform v1.1.2
on windows_amd64
```

### Terraform Configuration Files

**child_module1.tf(C1):**

```terraform
# Create Resource Group
resource "aws_resourcegroups_group" "resourcegroups_group" {
  name = "test"

  resource_query {
    query = <<JSON
{
  "ResourceTypeFilters": [
    "AWS::EC2::Instance"
  ],
  "TagFilters": [
    {
      "Key": "project",
      "Values": ["${var.ProjectName}"]
    }
  ]
}
JSON
  }
}
```
**child_module1_variables.tf:**
```terraform
########
variable "ProjectName" {
  type = string
  description = "This name would be prefixed with the cluster names."
}
```

Now call this child module in another child module**(C2)**:
**child_module2.tf:**
```terraform
module "prepare_aws_cloud" {
      source                        = "./modules/aws/prepare_cloud_copy"
      ProjectName                   = "${var.test.ProjectName}"
}
```

**child_module2_variables.tf:**
```terraform
variable "test" {
  type = object({
    ProjectName                 = string
  })
}
```

**Now I create a root module**(R1)** which calls the child_module2.tf:**

```terraform
 terraform {
  backend "local" {
   }
 }
 module "test_deploy" {
   source = "D:\\REPO\\installer_v2.2.22.1\\installer\\aws"

   
test = {
    #ProjectName                 = ""
}

 }
```

So the dependency is as follows:
R1 calls >> C2 calls >> C1
### Debug Output

```
PS D:\tkgTest> terraform apply -input=true
╷
│ Warning: Backend configuration ignored
│
│   on .terraform\modules\test_deploy\backend.tf line 3, in terraform:
│    3:   backend "local" {
│
│ Any selected backend applies to the entire configuration, so Terraform expects provider configurations only in the root module.
│
│ This is a warning rather than an error because it's sometimes convenient to temporarily call a root module as a child module for testing purposes, but this backend configuration block will have no effect.
╵
╷
│ Error: Invalid value for module argument
│
│   on testing.tf line 21, in module "test_deploy":
│   21: test= {
│   22:     #ProjectName                 = ""
│   23: }
│
│ The given value is not suitable for child module variable "test" defined at .terraform\modules\test_deploy\variables.tf:108,1-15: attribute "ProjectName" is required.
```
### Expected Behavior

I would have expected that the user input would be taken interactively by the console as I am passing the `-input=true` flag but it doesn't seem to work.

**Comment by jbardin** [comment]
Hi @rahtr,

The terraform CLI will interactively request unset root module variables, but that is not what the example here is doing. It's not entirely clear what problem exactly you are having, but two issues to note -- 
The `Warning: Backend configuration ignored` implies that the module is not actually at the root, and is being used incorrectly. You cannot interactively get input for module variables outside of the root module.
Assigning an empty object to the `test` variable is not the same as having nothing assigned. While a default could be taken if you chose to not set anything, the given value is not of the correct type and can't be used.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
