### ISSUE TITLE
Unable to capture `terraform show -json` command output when using the HashiCorp Terraform container

### ISSUE THREAD

**Issue by AErmie** [hashicorp/terraform#30481]
When using the official HashiCorp docker container for terraform to execute the `terraform show -json` command, it is not possible to capture the output from StdOut.

### Terraform Version
```
1.1.4
```

### Terraform Configuration Files
Any example terraform config file will do in this scenario

### Debug Output
https://gist.github.com/AErmie/261a695197c8871844abfb91350fbca1

### Expected Behavior
I would expect to be able to capture the `terraform show` output, so that it can be saved as a JSON file

### Actual Behavior
The docker container runs (and will show the JSON output if you just run `terraform show -JSON` without any capture attempt). Once you add the ` > MyTFPlan.json` to the `terraform show` command, no file is created, and no output is shown.

### Steps to Reproduce
1. Run `terraform init`
2. Run `terraform plan` including creating/capturing the tfplan file using `-out`
3. Mount the terraform directory that containers the PLAN file to the docker container and from within the docker container run `terraform show -json`.
```yaml
docker run --rm \
--workdir /data \
--volume $(System.DefaultWorkingDirectory)/terraform:/data \
hashicorp/terraform:latest show \
-json MyTFPlanFile.tfplan > MyTFPlanFile.json
```

### Additional Context
The HashiCorp terraform docker container is running as part of an Azure Pipeline CI.

**Comment by apparentlymart** [comment]
Hi @AErmie,

I/O redirection like the `>MyTFPlanFile.json` you showed here is handled by the shell where you executed the command, and not by either Docker or the Terraform CLI executable running inside this container.

The typical effect of a `>` redirection is for the shell to create the given file and run the process with its stdout handle set to refer to that file, instead of to the terminal as would be the default behavior. From the perspective of the `docker` process then, the only significant difference is that if it asks the system whether stdout is a terminal then the system will say that it isn't.

I'm not entirely sure what context the Terraform daemon passes through to the container, but in [the documentation for `docker run`](https://docs.docker.com/engine/reference/commandline/run/) I see mention of an option `--attach` which is documented as "Attach to STDIN, STDOUT or STDERR".

[The longer documentation for that option](https://docs.docker.com/engine/reference/commandline/run/#attach-to-stdinstdoutstderr--a) says the following at the time of writing:

> The `-a` flag tells docker run to bind to the container’s `STDIN`, `STDOUT` or `STDERR`. This makes it possible to manipulate the output and input as needed.
>
> ```shellsession
>  $ echo "test" | docker run -i -a stdin ubuntu cat -
> ```
>
> This pipes data into a container and prints the container’s ID by attaching only to the container’s `STDIN`.
>
> ```shellsession
> $ docker run -a stderr ubuntu echo test
> ```
>
> This isn’t going to print anything unless there’s an error because we’ve only attached to the `STDERR` of the container. The container’s logs still store what’s been written to `STDERR` and `STDOUT`.
>
> ```shellsession
> cat somefile | docker run -i -a stdin mybuilder dobuild
> ```
>
> This is how piping a file into a container could be done for a build. The container’s ID will be printed after the build is done and the build logs could be retrieved using `docker logs`. This is useful if you need to pipe a file or something else into a container and retrieve the container’s ID once the container has finished running.

Although it's not explicitly stated, I'm inferring from this that by default `STDOUT` is connected to the container's logs rather than to the Docker client's own `STDOUT`, in which case it seems like the behavior you observed is what's expected for that command line: the JSON output from Terraform went into a log file somewhere instead of to the Docker client's stdout, which was in turn connected to `MyTFPlanFile.json`.

It seems that in order to get the result you were hoping for you'd need to tell Docker to connect the Terraform process's `STDOUT` to the Docker client's `STDOUT`, which would therefore mean connecting it to the file your shell created. So I would try the following, where I've just taken the command line you shared and added `--attach stdout` to it:

```shellsession
docker run --rm \
  --workdir /data \
  --volume $(System.DefaultWorkingDirectory)/terraform:/data \
  --attach stdout
  hashicorp/terraform:latest show \
  -json MyTFPlanFile.tfplan > MyTFPlanFile.json
```

This seems to be a docker behavior question more than it's a Terraform behavior question, and so our ability to address this here is limited. If what I suggested above doesn't work, I'd suggest asking about this behavior in a Docker-specific forum where hopefully the participants are more familiar with the details of how Docker can handle programs which produce data on `stdout`. Alternatively, if possible I would suggest running the main Terraform executable directly, since Docker tends to just add a lot of complexity on top of what is just a simple Linux executable file.

I hope this helps!
