### ISSUE TITLE
backend/s3: Move assume role parameters to block

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform#30495]
The assume role parameters are currently at the root level.

1. Add block `assume_role` with
  * `duration` of type duration
  * `external_id`
  * `policy`
  * `policy_arns`
  * `role_arn` (required)
  * `session_name`
  * `tags`
  * `transitive_tag_keys`
2. Deprecate
  * `role_arn`
  * `session_name`
  * `external_id`
  * `assume_role_duration_seconds`
  * `assume_role_policy`
  * `assume_role_policy_arns`
  * `assume_role_tags`
  * `assume_role_transitive_tag_keys`

**Comment by blowfishpro** [comment]
It seems like this will break the ability to set these variables via CLI arguments (e.g. `-backend-config=role_arn=...`) or via environment variables (e.g. `TF_CLI_ARGS_init='-backend-config=role_arn=...'`).  Before this is removed entirely is there any chance #21830 could be addressed so that block variables can be set via `-backend-config`, or that specific environment variables could be added for these? (or #13022 addressed but I assume that's a much deeper change within terraform)
