### ISSUE TITLE
Influence -replace behavior via environment variables

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/terraform#30498]
### Current Terraform Version
Terraform 1.0.5 on TFE v202109-2

### Use-cases
Use the TFE UI to taint resources and trigger recreation by going to the variables tab and setting `TF_REPLACE_X=azurerm_virtual_machine.vm2` or something along those lines.

### Attempted Solutions
The only way I know to manage state directly is to establish a remote backend in my code, `tf init`, and run commands from my laptop.

This is not ideal as not everything functions the same when running from my laptop and sometimes I find certain operations are not possible due to e.g. sensitive workspace variables. Also our end users often feel uncomfortable attempting these sorts of operations from terminal.

### Proposal
If we allow the `-replace` argument to be passed via env var, then we can document passing those vars in via workspace variables as a pattern to taint resources without requiring the same level of access

**Comment by jbardin** [comment]
Hi @chrisjohnson,

Rather than adding a bespoke environment variable for all possible cli arguments, we have one generalized system for adding arbitrary arguments to the CLI based on the environment: https://www.terraform.io/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name

In your case I would expect that using `TF_CLI_ARGS_plan="-replace=azurerm_virtual_machine.vm2"` would do what you expect. Does this work for your situtation?

**Comment by chrisjohnson** [comment]
<3 I will investigate this, thanks for the clarification

**Comment by chrisjohnson** [comment]
This works a treat and I think is a suitable candidate for the feature request, thanks so much!
