### ISSUE TITLE
TERRAFORM CRASH (v1.1.2 in TFC)

### ISSUE THREAD

**Issue by z-eos** [hashicorp/terraform#30523]
### Terraform version
```
1.1.2
```
on linux_amd64

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x22202c0, 0x3edab70})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/terraform/internal/cloud.(*Cloud).Operation(0xc0002d6420, {0x2a7adf0, 0xc0000520b8}, 0xc000d97440)
        /home/circleci/project/project/internal/cloud/backend.go:607 +0x4a
github.com/hashicorp/terraform/internal/command.(*Meta).RunOperation(0xc000156820, {0x7f51ce73a900, 0xc0002d6420}, 0xc000d97440)
        /home/circleci/project/project/internal/command/meta.go:401 +0xde
github.com/hashicorp/terraform/internal/command.(*ApplyCommand).Run(0xc000156820, {0xc00004c0c0, 0x0, 0x0})
        /home/circleci/project/project/internal/command/apply.go:121 +0x59b
github.com/mitchellh/cli.(*CLI).Run(0xc000424280)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.realMain()
        /home/circleci/project/project/main.go:309 +0x1509
main.main()
        /home/circleci/project/project/main.go:58 +0x19
```

**Comment by crw** [comment]
Hi @z-eos! Thanks for reporting this. We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can ask for help on our [Terraform Cloud & Enterprise forum](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44), or report a bug by contacting the Terraform Cloud support team at tf-cloud-support@hashicorp.com. If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

I am going to leave this ticket open here for the time being just in case it turns out to be a an issue in the Terraform core.

**Comment by alisdair** [comment]
Hi @z-eos. I'd second Craig's suggestion to contact Terraform Cloud support if you have a paid account, as they may be able to help you more quickly than we can.

However, this crash is most likely due to a bug in core. I'm not able to reproduce this bug locally, and it's not clear from the stack trace how this crash is happening. Can you provide more details on how you encountered this bug?

- What triggers the crash?
- Is it consistently reproducible?
- Have you found a workaround?
- Are you using the CLI integration locally, or VCS/web-triggered runs?
- Are you able to reproduce the issue with a minimal configuration on a new workspace?

If possible, please attach debug logs, by setting `TF_LOG=trace` before executing the command. Thanks in advance!

**Comment by z-eos** [comment]
hi

> However, this crash is most likely due to a bug in core. I'm not able to reproduce this bug locally, and it's not clear from the stack trace how this crash is happening. Can you provide more details on how you encountered this bug?

 
>     * What triggers the crash?

I added GCP Cloud NAT module 

>     * Is it consistently reproducible?

no, the second run didn't show this crash

>     * Have you found a workaround?

it wasn't needed
 
>     * Are you using the CLI integration locally, or VCS/web-triggered runs?

it was web-triggered run

>     * Are you able to reproduce the issue with a minimal configuration on a new workspace?

no, it didn't reproduce

**Comment by crw** [comment]
Thanks @z-eos! The next step would be to capture and submit a trace log from a reproduced instance in which this crash occurred. Thanks for the report, and we'll keep an eye out for other reports.

**Comment by crw** [comment]
Hello, I'm cleaning up old issues and I see this one did not receive a response. There also did not seem to be follow-up reports from other users, or this issue may have been closed in a follow-up report. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
