### ISSUE TITLE
Cannot build latest release from source

### ISSUE THREAD

**Issue by kevinburkesegment** [hashicorp/terraform#30530]
Steps to reproduce:

- Download the Terraform source code.
- Check out Git tag v1.1.5.
- Run `GO111MODULE=on go install -v ./...` using the latest Go release (go1.17.7).

I see the following error:

```
$ go install -v ./...
go: downloading github.com/hashicorp/go-tfe v0.19.1-0.20211020175229-e52963e079d0
internal/backend/remote/backend.go:15:2: github.com/hashicorp/go-tfe@v0.19.1-0.20211020175229-e52963e079d0: invalid version: unknown revision e52963e079d0
```

If I look in the Github repository for hashicorp/go-tfe, I can't find a tag for commit v0.19.1 or a commit SHA for e52963e079d0.

I'm able to resolve the issue by updating go-tfe to v0.24.0.

**Comment by alisdair** [comment]
Thanks for reporting this! We've restored the deleted branch which led to the build error, and v1.1.5 now builds for me locally. We also have pending upgrades for this dependency which should ship in the next 1.1 patch release.

**Comment by apparentlymart** [comment]
I think it's fair to say that _most people_ (where "most" is intentionally vague and subjective) are consuming either our own pre-built binary packages or binary packages produced by other third-parties, such as Linux distributions.

I share your surprise that those third-party packagers would not have hit this, but since it seems like the mistake here was to leave `go.mod` referring to an untagged commit it seems plausible to me that the commit was only recently dropped as part of some cleanup and so perhaps those who built from source promptly after the release didn't see the problem, because the commit was still there at that point. I think third-party packages are also unfortunately accustomed to having to patch over upstream mistakes, so it also wouldn't surprise me to learn that someone _did_ hit it but just quietly applied a patch rather than reporting it.

Clearly the learning here is that we need to be more cautious about making sure all of the dependencies are referring to real tagged releases before cutting a Terraform release. A few of our dependencies are _intentionally_ untagged because they are tightly coupled with Terraform and thus we closely track the main branch, but I do see a number of third-party modules that are in a similar state and I think this is a good prompt to set aside some time to review them and see if there's a good reason why we aren't tracking a specific tag, and to update as many of them as possible to refer to tags.

Thanks for reporting this!
