### ISSUE TITLE
Allowing the use of variables within module source parameter

### ISSUE THREAD

**Issue by geoffo-dev** [hashicorp/terraform#30546]
### Current Terraform Version
v1.0.2

### Use-cases

We are currently wrestling with an issue where we are trying to create a multi-tenant environment within AWS and want to achieve some harmony where we can update some of the modules on one tenant and not others (for testing or fix 
 purposes):

```terraform
variable "a_module_tag" {
  type        = string
  description = "The tag to use on a specific module"
  default     = "stable"
}

module "a_module" {

  source = "git::https://somegitrepo.git?ref=${var.a_module_tag}"

  name = "a_module_name"
  region = var.region

}
```

We could then specify in the tfvars an override for `a_module_tag` if we wanted to deploy a new version or test the module. If it doesn't it stays at stable. However we are unable to specify variables in the source parameter.

### Attempted Solutions

Not really certain - everything we could do would be quite messy...!

### Proposal
Allow the use of vars within the source parameter and pass the string through for the initial git clone.

### References
This seems to have been asked for before but the discussion was closed...
https://github.com/hashicorp/terraform/issues/1439

**Comment by apparentlymart** [comment]
Hi @geoffo-dev,

I think the relevant existing _open_ issue for what you're describing is #23948. Although that's admittedly framed as being specifically about Git _usernames_ rather than Git _refs_ I think the same benefits and concerns all apply, so I'm going to close this one to consolidate the discussion there.

As you'll see in the comments of that issue, I'm currently looking for examples of how other programming language ecosystems have addressed this problem. All of the language ecosystems we are familiar with require dependencies to be specified exactly, because dependency installation is a separate step from compiling or executing the program. That is true for Terraform too, and installing new dependencies during compilation or runtime seems confusing and risky.

For the specific use-case you identified, I wonder about hoisting the problem up one level: if you want to install different versions of the configuration per tenant, could you instead make the _top-level configuration_ be the artifact whose version varies by tenant, rather than the _called_ module? That would then give you full control over which you upgrade each tenant, and your top-level module can statically select whichever tag it's intended to be compatible with because it'll be the top-level module that you'll be using to orchestrate the upgrade. If that isn't appropriate then it would help if you could share your use-case along with the constraints that prevent using that solution in the other issue, just so we can have everything all in one place.

Thanks!
