### ISSUE TITLE
fmt miss aligns blocks

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#30543]
### Terraform Version
```
$ terraform -v
Terraform v1.1.6
on darwin_amd64
```

### Terraform Configuration Files
```terraform
data "aws_vpc" "main" {
  filter {
    name   = "tag:Name"
    values = [
      var.vpc-name
    ]
  }
}

```

### Debug Output
![image](https://user-images.githubusercontent.com/168366/154475566-53d175eb-6ab8-45df-a257-d9e69a3da8d5.png)

### Expected Behavior
for the name and values = sign to align

### Actual Behavior
every few versions of terraform seem to mess up the fmt and miss align instead of properly formating.
v1.1.6 is broken, while 1.1.5 was fine

### Steps to Reproduce
terraform fmt .

**Comment by apparentlymart** [comment]
Hi @FernandoMiguel,

Assuming that the right hand side of your screenshot is the result you observed, this is the intended behavior of `terraform fmt`.

The intention of aligning by equals signs is to make a series of single-line arguments scannable as if it were a table, with the values all in one column.

That sort of tabulation isn't possible for a multi-line attribute value, so any attributes which spans over multiple lines is always isolated into its own separate alignment context, which effectively means no alignment at all because there is nothing else to align with.

As with all of the rules in `fmt`, this is a subjective and ultimately arbitrary tradeoff, but it has been consistent all the way back to 0.12.0 and so it would be surprising for v1.1.5 to have behaved differently. If it did, then that version was the buggy one and the bug has now apparently been fixed, restoring the intended behavior.

Since there are only subjective preference-based arguments for changing this behavior, and to do so would create churn for many existing Terraform configurations, we don't plan to change this rule.

Thanks for reporting it!
