### ISSUE TITLE
Azure DataConnector "Storage Account"

### ISSUE THREAD

**Issue by Gill-Bates** [hashicorp/terraform#30551]
Hey there, I would like to add a Storage Account to my Sentinel Environment.

![image](https://user-images.githubusercontent.com/25774289/154644834-f32d363f-b1fe-4803-af48-84de6438fdf7.png)

Can anyone tell me how to achieve this? Apparently there is no Data Connector in Terraform for this.

![image](https://user-images.githubusercontent.com/25774289/154645072-2fb680a0-52c2-4ccb-a830-a0da5cccba29.png)

**Comment by Gill-Bates** [comment]
Oh, I see, that the SecurityAPI does not support this!

I just see that Microsoft's API supports only a small subset of Data Connectors:

https://docs.microsoft.com/en-us/powershell/module/az.securityinsights/new-azsentineldataconnector?view=azps-7.2.0#description

**Comment by kmoe** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum.  Thanks!
