### ISSUE TITLE
Azure provider should support load balancers

### ISSUE THREAD

**Issue by carmstrong** [hashicorp/terraform#3055]
Including probes and health checks.

**Comment by mtekel** [comment]
Libcloud should support Azure LB creation/manipulation: https://github.com/Azure/azure-sdk-for-go/issues/183

**Comment by aznashwan** [comment]
@carmstrong: unfortunately; most of the network load balancing and monitoring side of things were not (and probably never will be able to be) supported in the ASM-API-based azure go sdk (which is the one we used to implement the Azure provider way back when).

I'm pleased to announce that there are plans to add support for the new ARM API's soon; with which almost all available Azure features will be able to be implemented in the Terraform Azure provider as well (including load balancers) :smile: 
Updates on status and discussions here: https://github.com/hashicorp/terraform/issues/3212

**Comment by carmstrong** [comment]
> there are plans to add support for the new ARM API's soon

:+1: We actually switched to using ARM directly in Deis, so this means we'll be able to use Terraform as soon as support is added!

**Comment by gambrose** [comment]
Is there any update on this issue as #3212 is now closed.

This issue should probably be re-labeled provider/azurerm

**Comment by tombuildsstuff** [comment]
👋 hi @carmstrong / @mtekel / @aznashwan / @gambrose

Taking a look into this issue - given the context (https://github.com/deis/deis/issues/4314 / https://github.com/deis/deis/issues/4334) - I believe that @gambrose is correct in that this issue is related to AzureRM, instead of Azure Service Management (and thus should be tagged `provider/azurerm` instead of `provider/azure`)?

Support for Load Balancers was merged in #9199 - and [is available in the AzureRM Provider](https://www.terraform.io/docs/providers/azurerm/r/loadbalancer.html). As such I believe this issue can be closed?

Please feel free to re-open this issue if that's not the case :)

Thanks!
