### ISSUE TITLE
Add `salt` parameter to `bcrypt` function

### ISSUE THREAD

**Issue by kriswuollett** [hashicorp/terraform#30573]
### Current Terraform Version

```
Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.17.1
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/kbst/kustomization v0.7.2
```

### Use-case

Create hashed password entries for service accounts to be imported into supported formats like `htpasswd` entries in a applications like `nginx` for purposes like protecting state of resources in scenarios like continuous integration testing and development possibly without the need to install additional resources like provisioners like Kubernetes Operators.

### Attempted Solutions

```terraform
resource "kubernetes_secret_v1" "user-bcrypt-passwords" {
  metadata {
    name      = "user-bcrypt-passwords"
    namespace = "my-namespace"
  }
  data = {
    for user in keys(var.users) :
       user => bcrypt(random_password.user[user].result, 10)
  }
}
```

The [`bcrypt`](https://www.terraform.io/language/functions/bcrypt) function does not take in a `salt` parameter, so the above does not work since it would cause downstream resources to be recreated. 

Workarounds:

- use `data "external"` and use a script that takes in salt as part of the query
- install additional software in clusters like Kubernetes Operators for various software packages if they even exist, or can even provision user accounts

### Proposal

Add support for providing `salt` to the cryptographic functions where technically possible. Users could then use the output of resources like [`random_string`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string) to create the salt.

### References

It can be said that some users may not know how to salt passwords properly and this would be a dangerous addition of functionality. However I'd argue that users will use `data "external"` anyways and [install the required software in the run environment](https://www.terraform.io/cloud-docs/run/install-software#installing-additional-tools) if they happen to use Terraform Cloud. In that case an alternative resolution to this would be to implement requests like hashicorp/terraform-provider-random#102 so at least best practices could be automatically followed and kept up to date.

**Comment by crw** [comment]
Thanks for the feature request!

**Comment by apparentlymart** [comment]
Hi @kriswuollett! Thanks for sharing this use-case.

This `bcrypt` function was quite an early addition to Terraform, from before we'd got a good sense of what made sense to be a function and what would be better to be represented in some other way. It's one of a small set of functions that we've come to regret including but preserve for compatibility, because (as I think you've seen) it doesn't produce a "stable" result, and so it's not a pure function and doesn't meet Terraform's typical assumptions about functions.

After that we explored the solution space more and decided to handle use-cases like this with providers instead, because resources have a "memory" and so can retain a generated value between runs. You can see the outcome of those explorations with examples such as [`random_uuid` in the `hashicorp/random` provider](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/uuid) (a replacement for [the `uuid` function](https://www.terraform.io/language/functions/uuid), which has a similar problematic design as `bcrypt`), and [`tls_private_key` in the `hashicorp/tls` provider](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key) which generates an RSA or ECDSA keypair.

The `bcrypt` function has not seen as much interest as other use-cases and so nobody at HashiCorp built an official provider-based successor to that function, but I see that there was some interest in hashicorp/terraform-provider-random#102 of adding bcrypt support to `random_password` (which I noticed afterwards you already found and linked to!). I'm not involved in the design of that provider so it's not up to me to decide if that particular design would make sense, but I think that something _like_ it would be the best path forward here, and in line with other designs we've followed and recommended for similar problems.

I also found a third-party provider [`loafoe/htpasswd`](https://registry.terraform.io/providers/loafoe/htpasswd) which offers a resource type [`htpasswd_password`](https://registry.terraform.io/providers/loafoe/htpasswd/latest/docs/resources/password), which produces various different formats including a `bcrypt` attribute according to its documentation. I've not personally tried it and so I can't say with certainty that it would meet your use-case, but I'd suggest evaluating it to see if it would meet your needs.

**Comment by crw** [comment]
I am reading in the above explanation that we are unlikely to update the `bcrypt` function due to backwards-compatibility concerns. Should we instead make this a documentation issue and add some version of the above explanation to the docs? cc @laurapacilio for input.

**Comment by crw** [comment]
Thanks again for the contribution! Per https://github.com/hashicorp/terraform/issues/30573#issuecomment-1051413583, I am going to close this issue in favor of solving this functional need with https://github.com/hashicorp/terraform-provider-random/issues/102.
