### ISSUE TITLE
Multiple versions of providers getting installed

### ISSUE THREAD

**Issue by DrStrangepork** [hashicorp/terraform#30576]
### Terraform Version

```
Terraform v0.13.4
Terraform v0.14.4
Terraform v1.1.5
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.1.0"
    }
  }
}
```

### Expected Behavior

Terraform should download the version of the provider specified in the _versions.tf_ file
### Actual Behavior

Terraform instead downloads multiple versions of the same providers
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.0"...
- Finding hashicorp/null versions matching "~> 3.1.0"...
- Finding latest version of -/aws...
- Finding latest version of -/null...
- Installing hashicorp/aws v3.74.3...
- Installed hashicorp/aws v3.74.3 (self-signed, key ID 34365D9472D7468F)
- Installing hashicorp/null v3.1.0...
- Installed hashicorp/null v3.1.0 (self-signed, key ID 34365D9472D7468F)
- Installing -/aws v4.2.0...
- Installed -/aws v4.2.0 (self-signed, key ID 34365D9472D7468F)
- Installing -/null v3.1.0...
- Installed -/null v3.1.0 (self-signed, key ID 34365D9472D7468F)
```
### Steps to Reproduce

`terraform init` with any version listed above; the same problem occurs in all versions

**Comment by apparentlymart** [comment]
Hi @DrStrangepork!

The behavior you saw here with Terraform installing some un-namespaced providers (those starting with "-/") looks like the expected behavior for a configuration that is in the process of upgrading from Terraform v0.12 to v0.13, which introduced the possibility of third-party providers and thus the need to put each provider in a namespace to show who published it.

If you follow through [the v0.13 upgrade guide](https://www.terraform.io/language/upgrade-guides/0-13) using the latest v0.13 patch release, including the final step of applying a change to your infrastructure to allow Terraform to upgrade the state, then after that you should no longer see these legacy non-namespaced providers being installed. This is just a transitional step in the upgrade process so Terraform can still work with the legacy provider addresses in your old state until you have completed the upgrade.

**Comment by DrStrangepork** [comment]
I discovered comments online that addressed the problem. These commands resolved my issue:
```
terraform state replace-provider -no-color -auto-approve registry.terraform.io/-/aws hashicorp/aws
terraform state replace-provider -no-color -auto-approve registry.terraform.io/-/null hashicorp/null
```
Oddly enough, we've migrated dozens of deployments from 0.11->0.12->0.13->0.14->1.1.5, and this was the first time we incurred this issue, never had to do this `replace-provider` step.

**Comment by apparentlymart** [comment]
Hi @DrStrangepork,

Those `replace-provider` commands are indeed a way to force the change in the state. Running `terraform apply` against this configuration would also have made the same changes automatically, because in this case there is no ambiguity about which providers to migrate to.

The `replace-provider` command is there primarily to help deal with ambiguous situations, such as in-house providers where there _is_ no well-defined new fully-qualified name for them, but there's no harm in using it to manually migrate providers that Terraform would've been able to resolve automatically, if that's more convenient for you than applying a change in the usual way.
