### ISSUE TITLE
Variable type passed through TF_VAR_name

### ISSUE THREAD

**Issue by denis256** [hashicorp/terraform#30609]
Hello,
noticed that terraform fails to identify variable type if it is passed through the environment variables as TF_VAR_xyz.

### Terraform Version

```
Terraform v1.1.6
on linux_amd64

```

### Terraform Configuration Files

```terraform

#main.tf
variable "some_number" {
  default     = 3
  type        = number
  validation {
    condition = var.some_number == 3
    error_message = "Invalid number (expected 3)."
  }
}
```

### Debug Output

https://gist.github.com/denis256/9bb7e0d493fa170317c184fc30898d53

### Expected Behavior

```
$ TF_VAR_some_number=3 terraform apply
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

```
$ TF_VAR_some_number=3 terraform apply
╷
│ Error: Invalid value for variable
│ 
│   on main.tf line 1:
│    1: variable "some_number" {
│ 
│ Invalid number (expected 3).
│ 
│ This was checked by the validation rule at main.tf:4,3-13.

```

### Steps to Reproduce

1. Create an empty directory
2. Save example terraform code as main.tf in the created directory
3. Run terraform and pass variable through environment:
```
TF_VAR_some_number=3 terraform apply
```

### References

https://github.com/gruntwork-io/terragrunt/issues/2018

**Comment by alisdair** [comment]
Thanks for reporting this!

This is a bug in how root module variables are handled when type conversions are required. We addressed this with a significant refactor in #29959, which is unfortunately too large to backport to 1.1.

I spent some time just now looking for a more tactical fix to this issue which is small enough for a patch release, but was unable to find one. The issue does not exist on the latest main branch, and will be fixed with the future 1.2.0 release.
