### ISSUE TITLE
terraform.workspace gives "default" for local execution mode

### ISSUE THREAD

**Issue by minterior** [hashicorp/terraform#30601]
The statement `terraform.workspace` gives the value `default` for local execution mode even though the workspace uses the remote backend and is named.

### Terraform Version

```
Terraform v1.1.6
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  backend "remote" {
    organization = "my-organization"

    workspaces {
      name = "my-workspace"
    }
  }
}
output "workspace" {
  value = terraform.workspace
}
```

### Expected Behavior
I see "my-workspace" as the output value.

### Actual Behavior
I see "default" as the output value.

### Steps to Reproduce
1. `terraform init`
2. Set the `Execution Mode` to `Local` in Terraform Cloud for the workspace `my-workspace`.
3. `terraform plan`

#### Output using local execution mode
```
terraform plan

Changes to Outputs:
  + workspace = "default"
```

#### Output using remote execution mode
```terraform plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/my-organization/my-workspace/runs/run-5CmrhcQGa9zTr9he

Waiting for the plan to start...

Terraform v1.1.6
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...

Changes to Outputs:
  + workspace = "my-workspace"
```

**Comment by apparentlymart** [comment]
Hi @minterior,

What you described here is the intended behavior for the remote backend, because the remote workspace you selected is effectively the default (and only) local workspace for this configuration.

If you use [the native Terraform Cloud settings](https://www.terraform.io/cli/cloud/settings) instead then Terraform CLI will directly select the Terraform Cloud workspace(s) you specify, which will achieve the effect you were expecting.
