### ISSUE TITLE
Validation Function does not testing of map conditions

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform#30606]
### Terraform Version

```
1.0.8
```

### Terraform Configuration Files

```terraform
variable myMap {
  default = {}
  validation {
 condition = (length(var.myMap) > 0 ? (length(var.myMap.env) > 0 ? (length(myMap.env) == 3) : false) : true)
  error_message = "If specified, myMap.env map must have 3 elements: X, Y and Z."
}
}
```

### Expected Behavior

If there are any elements in the mapped element `myMap.env`, I should be able to test pieces of it, in this example it should make sure there are 3.

### Actual Behavior

Error: Invalid reference in variable validation...
the condition for variable "myMap" can only refer to the variable itself, using var.myMap.

### Additional Context

since `var.myMap.env` is part of `var.myMap`, it should be allowed to be tested.

### References

none found.

**Comment by jbardin** [comment]
Hi @DonBower,

You have a type in your conditional, which is what is causing the error. The error output is underlining the invalid reference, which is missing the `var.` prefix in `length(myMap.env)`.

It may also be helpful in the future to use map indexes rather than object attribute references when a map is required, as it can make a difference in some cases. You however don't have a map here, but rather hav an object because there is no type defined. Having a strict type declaration like `map(string)` can help avoid other errors, drastically limiting the possibilities of what can be passed in. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
