### ISSUE TITLE
Bring back TFE_TOKEN? 

### ISSUE THREAD

**Issue by AzySir** [hashicorp/terraform#30604]
Hi Hashi!

The removal of the TFE_TOKEN has seriously surprised me. 

I thought in terms of running TFE in an external pipeline the TFE_TOKEN for authorisation would make a lot of sense.

Could someone please guide me in the best practice for authorising a 3rd party DevOps pipeline to plug into TFE with the token?

Thanks

**Comment by apparentlymart** [comment]
Hi @AzySir,

Terraform CLI has two main mechanisms for providing credentials when authenticating to [Terraform-native services](https://www.terraform.io/internals/remote-service-discovery), which are documented in more detail under [Credentials](https://www.terraform.io/cli/config/config-file#credentials-1) in the CLI configuration page, but I'll summarize here:
* Create a CLI configuration file containing a `credentials` block, either manually or indirectly by running `terraform login HOSTNAME`.
* Configure a "credentials helper" program to fetch the credentials dynamically from some other location, such as a dedicated credentials-issuing service (like HashiCorp Vault) or from other sources like the environment.

If your requirement is to use an environment variable to configure the token for your TFE host then you could install and configure [the `terraform-credentials-env` credentials helper](https://github.com/apparentlymart/terraform-credentials-env), which is a plugin which reads credentials from its process environment.

We use this repository only for bug reports and feature requests for Terraform CLI, rather than for usage questions. For that reason, I'm going to close this issue, though if you have more questions about what I've answered here, or wish to discuss other options, I'd suggest opening a topic in [The Terraform Cloud and Terraform Enterprise community forum](https://discuss.hashicorp.com/c/terraform-core/terraform-cloud-enterprise/44) or, if you wish to discuss something sensitive about your account in particular, to use your usual Terraform Enterprise support channels.

Thanks!

**Comment by AzySir** [comment]
@apparentlymart I've checked that out - quite a weird method there. I'd recommend getting some feedback from your TFE/TFC users as to their thoughts...

**Comment by AzySir** [comment]
Also asked here: #21965
