### ISSUE TITLE
Error while creating connection in EventBridge

### ISSUE THREAD

**Issue by rakesh-devcode** [hashicorp/terraform#30615]
While Creating connection in AWS EventBridge to connect with API destination.
Getting below error:

```
aws_cloudwatch_event_connection.api_connection: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
```
### Terraform Version
```
Terraform version: 0.12.31
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_event_connection" "api_connection" {
  name = "test-connection"
  description = "Connection to connect with api using oauth authorization "
  authorization_type = "OAUTH_CLIENT_CREDENTIALS"
  auth_parameters {
    oauth {
      authorization_endpoint = local.authorization_endpoint
      http_method = "POST"

      client_parameters {
        client_id = "dummy"
        client_secret = "dummy"
      }
      oauth_http_parameters {}
    }
  }
}
```

### Expected Behavior
It should have created connections for API destination

### Actual Behavior
It gives error and exiting.

**Comment by apparentlymart** [comment]
Hi @rakesh-devcode,

The behavior you saw here suggests that the AWS provider crashed. From Terraform Core's perspective, the plugin has stopped accepting connections (because it's no longer running) and so Terraform has to abort.

Unfortunately there is nothing we can do to resolve this issue in Terraform Core, because it was the AWS provider that seems to have crashed here, and so I'm going to close this issue. Instead, I suggest reporting this in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws). When you do so, please be sure to include the full debug output requested by their issue template, because they will need that information in order to determine exactly what was happening when the provider crashed.

Thanks!
