### ISSUE TITLE
Support for KMS cli get-key-policy command

### ISSUE THREAD

**Issue by MrHash** [hashicorp/terraform#30625]
### Current Terraform Version
1.1.7

### Use-cases
It would be useful to get key policies from existing keys in order to create replicas.

### Attempted Solutions
Custom data source to call `aws kms get-key-policy` for specific key ids or aliases.

### Proposal
Implement a new data source or integrate into existing `aws_kms_key` data source https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_key

### References
see https://docs.aws.amazon.com/cli/latest/reference/kms/get-key-policy.html

**Comment by apparentlymart** [comment]
Hi @MrHash,

The functionality you're talking about seems to be long to the AWS provider rather than to Terraform Core, so you'll need to instead open an issue in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws).

This repository doesn't include any AWS-specific resource types and so there's nothing we could do to add the feature you've described in this repository, and so I'm going to close this. Thanks!
