### ISSUE TITLE
Error: Provider configuration not present

### ISSUE THREAD

**Issue by harinireddy3** [hashicorp/terraform#30628]
I am trying to remove the module reference from my code and I don't want to delete the whole infrastructure, when I remove the call to the module and run terraform plan it's complaining below error, I have provider declaration present in the root module, and child module as well, but it's still trying to use one from the child module and failing.

We cannot use terraform destroy at the moment. 
```
Error: Provider configuration not present

To work with module.rdspostgres.data.aws_route53_zone.xyz-io-private
its original provider configuration at module.rdspostgres.provider.aws is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.rdspostgres.data.aws_route53_zone.shoprunner-io-private, after which
you can remove the provider configuration again.
```

### Terraform Version
0.12

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Terraform should try to destroy resources in the module
### Actual Behavior

Terraform failing with the below error.
```
Error: Provider configuration not present

To work with module.rdspostgres.data.aws_route53_zone.shoprunner-io-private
its original provider configuration at module.rdspostgres.provider.aws is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.rdspostgres.data.aws_route53_zone.xyz-io-private, after which
you can remove the provider configuration again.
```

**Comment by jbardin** [comment]
Hi @harinireddy3,

If there was a provider configuration within the module which created the resources, then that configuration must still exist to remove the resources. This is one of the reasons we recommend always passing in providers from the root module, so that module instances can always be removed cleanly. Current Terraform releases will do a much better job at validating this for you, and making sure the correct provider is being used in most cases.

You may be able to update the configuration to remove the provider config, and refresh the resources to store the new config address, allowing you to remove the module entirely. Another option is to modify the module source to leave only the provider config temporarily while the resources are being destroyed. I'm not sure exactly which will be easier, since it depends on the complexity of the configuration, and it's been a while since I reviewed the internals of v0.12 to know for sure what the exact behavior will be.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
