### ISSUE TITLE
lookup function is not evaluated to a string

### ISSUE THREAD

**Issue by iliyahoo** [hashicorp/terraform#30627]
I have a following configuration:
```
locals {
    vol_type = "${lookup(module.config_service_instance.result_map, "NOT_EXISTED!!!", "gp3")}"
    root_block_device = "${list(map("volume_type", local.vol_type, "volume_size", var.root_volume_size, "delete_on_termination", "true"))}"
}
```
Running terraform plan I'm getting:
```
Error: module.master_node.module.ec2_instance.aws_instance.this: root_block_device: should be a list
```

It works as expected if I'm using explicitly defined string: 
```
locals {
    vol_type = "gp3"
    root_block_device = "${list(map("volume_type", local.vol_type, "volume_size", var.root_volume_size, "delete_on_termination", "true"))}"
}
```
I thing that lookup function doesn't evaluate correctly or returns a wrong data type.
It should return a string - "gp3".

### Terraform Version
```
Terraform v0.11.15
```

**Comment by jbardin** [comment]
Hi @iliyahoo,

Thanks for filing the issue. Terraform v0.11 is no longer maintained, and and still contains numerous issues related to the lack of a strong type system which we have now. You may be able to figure out how to manipulate the data into the shape you want via experimentation by assigning it to an output, but there is not going to be anything we can help fix otherwise. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
