### ISSUE TITLE
Grant single GitHub user permission to GitHub repository

### ISSUE THREAD

**Issue by EricCrosson** [hashicorp/terraform#30623]
### Current Terraform Version

```
4.20.1
```

### Use-cases

I'm trying to grant myself (a single GitHub user) access to a GitHub repository whose visibility is `private`. In the past I've used [github_team_repository](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository) to grant a GitHub _team_ access to a GitHub repository, but I can't find the analogous way to grant access to a single user.

### Attempted Solutions

I could make a one-man GitHub team and grant that team access to the GitHub repository, but that seems suboptimal.

### Proposal

If I'm not overlooking something that already exists, we could make use of a `github_user_repository` resource. It could take the user's id, repository, and permission, just like the `github_team_repository` does.

### References

This section intentionally left blank.

**Comment by apparentlymart** [comment]
Hi @EricCrosson,

It sounds like this is a feature request for the GitHub provider, which is maintained by a team at GitHub. None of that functionality belongs to this repository, and so I'm going to close this. I suggest opening a similar issue in [the provider's own repository](https://github.com/integrations/terraform-provider-github) so that the maintainers can consider it.

Thanks!

**Comment by EricCrosson** [comment]
@apparentlymart my sincere apologies, and thank you for the pointer!
