### ISSUE TITLE
apply fails with SerializationError

### ISSUE THREAD

**Issue by robins** [hashicorp/terraform#30624]
## Description

Ever so often `terraform apply` would fail with a `SerializationError`. I've seen it with both a 200 and a 400 response code ... and so don't rule out my (flaky) internet connection is partly to blame.

### Terraform Version
```
>terraform version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files
Mostly irrelevant - happening on multiple TF scripts

## Expected behavior
A retry in case terraform couldn't understand the response of a DescribeAPI.

## Actual behavior
Terraform crashes and leaves `terraform apply` half-way abandoned.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Terminal Output Screenshot(s)
```
module.replica1.module.db_instance.aws_db_instance.this[0]: Still creating... [12m41s elapsed]
module.replica1.module.db_instance.aws_db_instance.this[0]: Still creating... [12m51s elapsed]
╷
│ Error: Error retrieving DB Instances: SerializationError: failed decoding Query response
│       status code: 200, request id: xxxxxx
│ caused by: read tcp 10.55.17.234:58440->52.39.17.104:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
│
│   with module.master2.module.db_instance.aws_db_instance.this[0],
│   on ..\..\modules\db_instance\main.tf line 27, in resource "aws_db_instance" "this":
│   27: resource "aws_db_instance" "this" {
│
```

## Additional context
What is important to note is that I am having a bad day in terms of network packet-loss on my home network (~5-10% packet loss), so unsure if this is related to that.

Also, I am getting this exact error today on 2 different scripts, which points to this having a common underlying cause.

(This [issue](https://github.com/terraform-aws-modules/terraform-aws-rds/issues/390) was originally opened with the `terraform-aws-rds` project, where it was recommended that an issue be opened here instead)

## Ask
Googling, this error has been seen to happen commonly with a Windows + Golang combination and thus the request from this bug-report is to see if terraform could be more robust to catch such cases and retry if possible (at least for read-only API requests).

**Comment by apparentlymart** [comment]
Hi @robins! Sorry for this strange behavior.

This message seems to come from the AWS provider rather than from Terraform itself, and so I suggest opening a bug report about it in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws). It _does_ seem to be a network timeout error, and so packet loss does seem like a plausible reason to see this error, but the AWS provider team will be in a better position to understand exactly what Terraform was doing when encountering this error.

Since this request is not being made by Terraform Core, we won't be able to do anything to avoid it in this repository, so I'm going to close this. I'm sorry to send you on another hop of reporting upstream (since you were already redirected here by a module author), but providers are entirely separate programs and so how they handle problems such as network congestion is entirely outside of the control of Terraform Core.

Thanks!

**Comment by robins** [comment]
Thanks @apparentlymart ! ... Am new to TF and bowled over by the explanation ... since this could have easily been a one-liner "Go elsewhere" response. Much Appreciated.

Sure would open this up with provider repo soon.
