### ISSUE TITLE
"Too many command line arguments. Configuration path expected" when using multiple --var-file

### ISSUE THREAD

**Issue by kunalmehtainfosys** [hashicorp/terraform#30634]
Hi Team,

we are getting an error when we run terraform plan with multiple --var-file 
terraform plan --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.Definitions/drop/01_global/01_terraform.alert_rules/var/required.tfvars --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.AlertConfigs/drop/_alerts/ePeerReview/notifications.tfvars --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.AlertConfigs/drop/_alerts/ePeerReview/standard/app-standard_dev01_operationalinsights-workspaces__alert.tfvars  --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.AlertConfigs/drop/_alerts/ePeerReview/standard/infra-standard_dev01_dbforpostgresql-servers__alert.tfvars  --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.AlertConfigs/drop/_alerts/ePeerReview/standard/infra-standard_dev01_keyvault-vaults__alert.tfvars  --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.AlertConfigs/drop/_alerts/ePeerReview/standard/infra-standard_dev01_sql-servers-databases__alert.tfvars  --var-file=/home/vsts/work/r1/a/_Operations.AlertAutomation.AlertConfigs/drop/_alerts/ePeerReview/standard/infra-standard_dev01_storage-storageaccounts__alert.tfvars  -no-color -detailed-exitcode

Too many command line arguments. Configuration path expected.
[error]Terraform command 'plan' failed with exit code '1'.
[error]Too many command line arguments. Configuration path expected.

### Terraform Version
Terraform v0.13.7

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Plan should execute without any error.

### Actual Behavior
Too many command line arguments. Configuration path expected.
[error]Terraform command 'plan' failed with exit code '1'.
[error]Too many command line arguments. Configuration path expected.

**Comment by jbardin** [comment]
Hi @kunalmehtainfosys,

The output indicates that something in the arguments is being interpreted incorrectly, perhaps an extra whitespace or non-printable character was pasted into the command. The trace logs you get when using `TF_LOG=trace` will show the exact arguments as parsed by `terraform` and should help track down the problem.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
