### ISSUE TITLE
"Merge more than 2 tfvars file contents"

### ISSUE THREAD

**Issue by kunalmehtainfosys** [hashicorp/terraform#30640]
I have usecase where I have 3 tfvars files

1.tfvars
api_stages=[
  {
      api_id= "xxxx"
      stage="play"
  }
]

2.tfvars
api_stages=[
  {
      api_id= "yyy"
      stage="play"
  }
]

3.tfvars    
api_stages=[
  {
      api_id= "zzz"
      stage="play"
  }
]
and I am creating 1 single usage plan using this

resource "aws_api_gateway_usage_plan" "usage_plan" {
  name         = var.usage_plan_name     
   throttle_settings {
    burst_limit = var.burst_limit
    rate_limit  = var.rate_limit
  }  
   
  dynamic "api_stages" {
      for_each = var.api_stages
      content {
        api_id     = api_stages.value.api_id
        stage = api_stages.value.stage      
      }
    }
}

but terraform only picking the last data.

**Comment by jbardin** [comment]
Hi @kunalmehtainfosys,

Terraform will use the last value assigned to a variable, as described in the documentation here: https://www.terraform.io/language/values/variables#variable-definition-precedence.
If you want to merge a number of lists, you will need to assign them separately and merge them in the configuration.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by kunalmehtainfosys** [comment]
Hi @jbardin ,

Thanks for the Response, please let me know if is there any way to merge list variables having same name from different *.tfvars 

Please share a short code snippet if possible.

Regards,
Kunal
