### ISSUE TITLE
to download terraform 0.14.x , can not see where to get it 

### ISSUE THREAD

**Issue by obiutoh** [hashicorp/terraform#30666]
### Current Terraform Version

```
...
```

**Comment by kmoe** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by obiutoh** [comment]
Thanks
