### ISSUE TITLE
Error refreshing state

### ISSUE THREAD

**Issue by sanjeevim** [hashicorp/terraform#30689]
Hello Team,

I am working on the terraform 0.1.5 version.

I am using Jenkins pipeline to create AWS infrastructure like kms,s3,iam,ec2 stage by stage.

When I tried to deploy a new EC2 with help of the remote state file which is stored in the backend S3. I am getting the below error on the EC2 deploy stage. I never experienced this kind of issue in the past since, I deployed many infrastructure using Jenkins pipeline.

Please review and share your suggestions.

Unsupported state file format: The state file could not be parsed as JSON: syntax error at byte offset 10341.

Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.

echo 'Get the reference modules with the latest updated references'
Get the reference modules with the latest updated references.

Thanks,
Sanjeevi

**Comment by crw** [comment]
Hello @sanjeevim, this appears to be a question about how Terraform works, rather than a feature request or a bug report. Please try asking this question in our [Community Forum](https://discuss.hashicorp.com/c/terraform-core/27), where there are more people able to help answer your question. Thanks!
