### ISSUE TITLE
Cant create an IAM role and then assume it to build something else in AWS (can in GCP)

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#30690]
Terraform 1.1.7
Terraform AWS Provider 4.5.0

Trying to do this:

```
provider "aws" {
  region = "eu-west-1"
}

data "aws_caller_identity" "current" {}

resource "aws_iam_role" "foo" {
  name = "foo"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "foo_administrator" {
  role       = aws_iam_role.foo.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}

provider "aws" {
  alias  = "foo"
  region = "eu-west-1"
  assume_role {
    role_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/foo"
    session_name = "terraform"
  }
}

resource "aws_iam_role" "bar" {
  name = "bar"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
        }
      }
    ]
  })
  provider = aws.foo
}
```

Basically I want to create an AWS IAM Role and then assume it to do something else. 

There are numerous stack overflow articles on the web about this used to be possible, because aliased providers were not instantiated until they are first needed by a resource apply (was this ever true?) - doesnt seem to be the case now. 

(Example of SO article: https://stackoverflow.com/questions/67283766/deploying-resources-on-multiple-aws-organizations-account)

The obvious example of needing to do this is to provision an AWS Account and then assume its OrganizationAccountAccessRole to then configure the AWS Account in question. 

I believe the only way to do this currently is a 2 step terraform process, e.g. orchestrated by terragrunt, where first you create the roles in one terraform run, and then you use the roles in a 2nd terraform process to do something else. 

Just posting this here in case there is a different workaround that I'm not aware of. 

@apparentlymart noticed that you had quite a few issues with similar attempts, so hope you dont mind if I tag you in this one - e.g. https://github.com/hashicorp/terraform/issues/2430

**Comment by gtmtech** [comment]
Actually well I solved this - but I would still be interested in whether this is a dubious workaround or this is working nicely as intended.

```
provider "aws" {
  region = "eu-west-1"
}

data "aws_caller_identity" "current" {}

resource "aws_iam_role" "foo" {
  name = "foo"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "foo_administrator" {
  role       = aws_iam_role.foo.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}

resource "time_sleep" "foo_wait_10_seconds" {
  depends_on = [aws_iam_role_policy_attachment.foo_administrator]
  create_duration = "10s"
}

provider "aws" {
  alias  = "foo"
  region = "eu-west-1"
  assume_role {
    role_arn = "${aws_iam_role.foo.arn}${time_sleep.foo_wait_30_seconds.id == "nil" ? "" : ""}"
    session_name = "terraform"
  }
}

resource "aws_iam_role" "bar" {
  name = "bar"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
        }
      }
    ]
  })
  depends_on = [ time_sleep.foo_wait_30_seconds ]
  provider = aws.foo
}
```

**Comment by crw** [comment]
Hello @gtmtech,

You might want to check out the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) for the AWS provider, there may be more helpful info there. My initial read of this issue is that it has more to do with the nuance of the AWS provider than with the core of Terraform itself, and so you may get more specific feedback from AWS provider folks.  

If you want to interact with the AWS provider team directly to report a new issue, check out their repository: https://github.com/terraform-providers/terraform-provider-aws/issues. 

As you found a work-around and there does not appear to be a core issue, I am going to close this ticket, but another team member may still wander by and leave a comment. Thanks for the contribution!

**Comment by apparentlymart** [comment]
I think this might be an example use-case for #2430, but since that's already linked and remains open I think closing this seems reasonable and we can keep this use-case in mind in the ongoing effort to get to the root of what's needed for this set of use-cases around configuring one provider from results of another.
