### ISSUE TITLE
terraform fmt -check -recursive  doesn't provide any error messaging

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [hashicorp/terraform#30695]
### Current Terraform Version

```
Terraform v1.1.6
on linux_amd64
```

### Use-cases

I want `terraform fmt -check -recursive` to return additional information when a list of files is returned so that users can easily tell from CI pipelines that formatting errors exist in those files. Presently only a list of files are returned without context.

### Proposal

Modify [internal/fmt.go Run()](https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/command/fmt.go#L39) to include additional debugging information such as `Formatting errors found in:` followed by the list of files.

**Comment by kmoe** [comment]
Like `go fmt`, the output of `terraform fmt` is designed to be easy to parse with common CLI tools, which is why both format their output as a list of files separated by newlines. If `terraform fmt -check` outputs a list of files with a non-zero exit code, this gives enough information to deduce that formatting errors were found in those files. To make the output from CI pipelines more readable, we would recommend using shell commands to display this information. 

Due to Terraform v1.0 compatibility promises, it is also not possible to change the output of the existing `terraform fmt` commands.

What kinds of additional information or context would you like to see here?

**Comment by Jake-Mok-Nelson** [comment]
Thanks, @kmoe . The only real improvement I had in mind was to provide a message that the those files failed the format check. 
If an internal customer uses my pipelines for a terraform plan and the code is invalid it returns an error message, likewise for terraform apply, but a terraform fmt check failure returns a list of files without context. To me that's a little inconsistent and it has been a common point raised by the people that use my pipelines. 
But you're right that it's not hard to handle that within a bash script or by another means.
