### ISSUE TITLE
lifecycle create_before_destroy issue

### ISSUE THREAD

**Issue by kpatelpanw** [hashicorp/terraform#30700]
We have a file (gitlab_rb_us-central1) stored into GCP storage , it has some dependency as well with other resources. When the content of the file has changed Terraform tries to update the file in GCP as below plan. The problem is that it first replaces the new file and then destroy, so the file is gone. I want "-/+ destroy and then create replacement" not "+/- create replacement and then destroy" , any way to achieve it ?  

```diff
 # google_storage_bucket_object.gitlab_rb must be replaced
+/- resource "google_storage_bucket_object" "gitlab_rb" {
      ~ content        = (sensitive value)
      ~ content_type   = "text/plain; charset=utf-8" -> (known after apply)
      ~ crc32c         = "WolTPw==" -> (known after apply)
      ~ detect_md5hash = "GKRLpDotHYLtRB4ev8LdLw==" -> "different hash" # forces replacement

      ~ id             = "config-gitlab-server-dev-gitlab_rb_us-central1" -> (known after apply)
      ~ md5hash        = "GKRLpDotHYLtRB4ev8LdLw==" -> (known after apply)
        name           = "gitlab_rb_us-central1"
      ~ output_name    = "gitlab_rb_us-central1" -> (known after apply)
   ~ update in-place
      ~ storage_class  = "MULTI_REGIONAL" -> (known after apply)
+/- create replacement and then destroy
```

**Comment by jbardin** [comment]
Hi @kpatelpanw,

Terraform only uses the `create_before_destroy`(`+/-`) ordering when it is specifically declared in the configuration. The only way to avoid the given ordering is to change the configuration to remove the `create_before_destroy` requirement.

If `create_before_destroy` is not declared for the resource in question, then it is because an upstream dependency has declared it, and terraform must re-order the operation to prevent dependency cycles during apply. In that case you would need to update the configuration of that dependency, or decouple your resource from that dependency, but without an example it's difficult to say exactly what needs to be changed.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by kpatelpanw** [comment]
Thank you @jbardin for your reply and info, sure I will use community forum for any future questions, sorry I was not aware of it. 
Reg create and destroy (+/-), we have VMs with suffix and those are fine as they gets created with unique suffix so new one gets created and old ones get destroyed. But for the storage file we don;t use suffix so it looks like replacing with new one and then destroying the same file. Below is config, but let me know if any other dependent config you want me to share. I am new to terraform so sorry for asking basic questions. 

// upload the gitlab.rb configuraiton file into a "config" bucket
resource "google_storage_bucket_object" "gitlab_rb" {
  name    = format("gitlab_rb_%s%s", var.region, var.ep_prefix)
  content = data.template_file.gitlab_rb_template.rendered
  bucket  = local.config_bucket
}

**Comment by jbardin** [comment]
@kpatelpanw,

You mention that the VMs in the config use `create_before_destroy`, so if they refer to this `google_storage_bucket_object` in some way (even indirectly), it will force this to also use that replacement ordering. You must either make this resource also work with `create_before_destroy`, or remove `create_before_destroy` from the dependent resources.

**Comment by kpatelpanw** [comment]
Hi @jbardin , Understood.
Reg "_You must either make this resource also work with create_before_destroy_" , how I can make the resource so it can work with create_before_destroy? I am still trying to understand why the file gets deleted at all, does TF has any flag or smart check to not delete the file after replace, it doesn;t make sense to delete the same file which just got replaced, not sure what is the use case for this behavior. It would be helpful If you can provide some more details.

**Comment by jbardin** [comment]
@kpatelpanw,

I'm not familiar with the details of the resource, but the provider is what decides if a resource gets replaced or not, and the plan output shows that `detect_md5hash` is forcing the replacement. If you want to use `create_before_destroy`, then the resource must support it somehow by using unique identifiers. If the resource does not support it, then you cannot use `create_before_destroy`.

**Comment by jbardin** [comment]
I'm not sure what the workaround may be, since it could depend on what the remote service allows. If it's not prevented by the constraints of the remote api, you may be able to `-target` a specific resource to destroy or replace first, or you may have to do it out of band. The community forums, especially under the Google provider category will probably have more users familiar with the resources.
