### ISSUE TITLE
Importing a resource doesn't work if the module is calling other modules via for_each

### ISSUE THREAD

**Issue by applike-ss** [hashicorp/terraform#30706]
### Terraform Version

```
1.1.7
```

### Terraform Configuration Files
https://github.com/applike-ss/tf-import-issue

### Debug Output
https://gist.github.com/applike-ss/060f787190d29b707c06a0efccecdaa4

### Expected Behavior
resource should be importable, because the for_each does not matter for the resource

### Actual Behavior
resource was prepared to import, but import failed with `Invalid for_each argument` and `data.null_data_source.f will be known only after apply`

### Steps to Reproduce
* check out repo
* have an aws account (or exchange the resource against anything else that can be imported that you have an account for)
* `terraform init`
* `terraform import 'module.m[0].aws_sns_topic.t' arn:aws:sns:eu-central-1:123456789012:my-topic`

**Comment by jbardin** [comment]
Hi @applike-ss,

Thanks for filing the issue. The first error is only due to a typo in the command itself, you are passing the number `0` as the `for_each` key, but keys can only be strings. Quoting the string will avoid the error: `'module.m["0"].aws_sns_topic.t'`

The second error however does look like a bug. In essence it's another form of #27934, but since it only manifests in nested modules, we can leave this open as a separate distinct problem for now.

Thanks!
