### ISSUE TITLE
Terraform cannot detect a supported external module source type

### ISSUE THREAD

**Issue by qdupuy** [hashicorp/terraform#30716]
Hello,

From one day to the next, I encounter the following problem on my modules : 

```
│ Error: Invalid module source address
│ 
│ Module "node-termination-handler" (declared at main.tf line 287) has invalid source address "x/aws-modules/node-termination-handler": Terraform cannot detect a
│ supported external module source type for x/aws-modules/node-termination-handler.
```

main.tf :

```
module "node-termination-handler" {
  source = "x/aws-modules/node-termination-handler"
  version = "0.1.3"
  [...] 

}
```

I'm using terraform registry of gitlab, my personnal token is good.

My version is well present in the registry.

My terraformrc file content my credential.

Terraform version : v1.1.7

OS : MacOS

**Comment by qdupuy** [comment]
However, if I use the git reference like this : 

```
git::https://x/terraform/aws-modules/node-termination-handler?ref=0.1.3
```

It works

**Comment by jbardin** [comment]
Hi @qdupuy,

If there is no hostname or protocol in the `source` field, Terraform must assume that it is going to use the default Terraform registry to locate the module. I located some gitlab module registry documentation [here](https://docs.gitlab.com/ee/user/packages/terraform_module_registry/#reference-a-terraform-module), which shows the expected source format, including the hostname.

```
module "<module>" {
  source = "gitlab.com/<namespace>/<module-name>/<module-system>"
}
```

One additional constraint which they don't seem to mention, is that the system path segment for external hosts must not contain any dashes for compatibility with various systems. If you add in the host prefix to your source, the error output will be

```
│ Module "node-termination-handler" (declared at main.tf line 1) has invalid source address
│ "gitlab.com/x/aws-modules/node-termination-handler": invalid target system
│ "node-termination-handler": must be between one and 64 ASCII letters or digits.
```

In order to access this module through their registry, the system segment will need to be renamed to only contain characters within the set `[0-9a-z]`.

Since this does not represent a bug in Terraform itself, I'm going to close the issue. If you have more questions, feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by qdupuy** [comment]
Precisely, I respect the format given by gitlab.

It's just that I hid the names

@jbardin

**Comment by qdupuy** [comment]
up @jbardin / @crw

**Comment by crw** [comment]
Hi @qdupuy, I recommend taking this to the [Community Forum](https://discuss.hashicorp.com/c/terraform-core) - it should be easier to dive into this question there, and there are more viewers on the forum who could help troubleshoot and answer this question. Thanks!
