### ISSUE TITLE
Merge two List variables(same name) from two tfvars file

### ISSUE THREAD

**Issue by kunalmehtainfosys** [hashicorp/terraform#30714]
### Terraform Version

```
0.13.7
```

### Terraform Configuration Files

```terraform
Consider first tfvars file (one.tfvars) and a variable defined in it.

api_stages=[
{
api_id= "xxxx"
stage="play"
}
]

and second tfvars file (second.tfvars) also have same name variable

api_stages=[
{
api_id= "yyy"
stage="play"
}
]


How can we merge both variable into one and use in main.tf ??

```

### Expected Behavior

api_stages=[
{
api_id= "yyy"
stage="play"
},
{
api_id= "xxxx"
stage="play"
}
]

**Comment by kunalmehtainfosys** [comment]
@jbardin Hi James, can you please help on this if possible ??

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. Please open a thread in the forums and we can continue the conversation there.

Thanks!
