### ISSUE TITLE
Rename variables to inputs

### ISSUE THREAD

**Issue by mc0re** [hashicorp/terraform#30761]
### Terraform documentation link

https://www.terraform.io/language/modules/develop/structure

### Expected Behavior

The module's input parameters should be in a file `inputs.tf` or `parameters.tf`.

### Actual Behavior

The module's input parameters are in a file `variables.tf`. While the module's variables are in `local` block of `main.tf`.

### Additional Context

I find it confusing that one cannot find module's input parameters - because it's not in `variables` file one would be looking for them.

### References

https://www.terraform.io/language/modules/develop/structure

**Comment by mc0re** [comment]
Can you enlighten me on reasons why you chose to collect input parameters in a file called `variables`?

As for changing the idiom - you can always amend the published rules, say, give both names as recommended, the new one marked as preferred. In software the only constant thing is change, and I believe all programmers are very much aware of it - otherwise they wouldn't even use _Terraform_ :-)

**Comment by apparentlymart** [comment]
Thanks for that extra context, @mc0re.

So I think really your feedback here is that "variable" is a confusing name for the concept that is the opposite of "output". And indeed, I agree with you on that... variable was a historical poor choice for that concept that we are unfortunately stuck with since it has been with Terraform since its earlier versions. We describe them as "Input Variables" in the documentation to add that missing context, but this is essentially a historical language design wart that is not fixable without a significant compatibility break, which is a typical problem with any programming language after a while.

Perhaps a future opt-in edition of the Terraform language (as described in [my blog post](https://log.martinatkins.me/2021/09/25/future-of-the-terraform-language/)) can rename the `variable` block to `input` for symmetry with `output` blocks, at which point it would also be sensible to change the file naming convention to be `inputs.tf` for modules written for that newer language edition, and I suppose references to them would appear as `input.foo` instead of `var.foo`. However, we are not planning a new opt-in language edition for the foreseeable future because splitting the ecosystem in that way is always disruptive and so ought to be done infrequently and with lots of care.

In the meantime though, I don't expect we will change the recommendation about _file_ naming in isolation, because that would make the recommendations inconsistent with most existing modules and with the name of the block type most commonly used in that file. If we are going to make a change here, we should change everything together so that there is a clear breaking point between old and new, and so maintainers of modules can know which idiom to expect depending on which edition of the language a module is targeting.

**Comment by mc0re** [comment]
Thanks for taking the time to explain and for taking my opinion into consideration.
