### ISSUE TITLE
apt-key add - discontinued  please change it. 

### ISSUE THREAD

**Issue by walterlopezw** [hashicorp/terraform#30775]
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

**Comment by kmoe** [comment]
Thanks for opening the issue. Since it's not possible to determine from the issue description what you would like us to do, I'm going to close this. Please feel free to reopen after filling in the [bug report template](https://github.com/hashicorp/terraform/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) or, if this is an issue with documentation, linking to the appropriate docs page.
