### ISSUE TITLE
Azure Databricks issue installing libs in clusters

### ISSUE THREAD

**Issue by ManuelRamoss** [hashicorp/terraform#30793]
Hello

I am working with databricks and i am facing an issue deploying the libs in the databricks clusters.

![Screen Shot 2022-04-04 at 17 17 00](https://user-images.githubusercontent.com/7363275/161575966-79767fff-2aa5-4337-996d-f03271fef555.png)

I already add that depends on the workspace

![Screen Shot 2022-04-04 at 17 16 40](https://user-images.githubusercontent.com/7363275/161575893-41093ac0-3dc5-441d-bbd0-d275637e88f5.png)

Any clue? thanks!.

**Comment by apparentlymart** [comment]
Hi @ManuelRamoss!

This seems like a usage question rather than a bug report of a feature request, so I think you'd be better to ask about this in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where it's more likely to be seen by someone who is familiar with the Azure and Databricks providers.

(If you _do_ open a community forum topic, I would also ask that you copy the code into Markdown backtick code blocks rather than including pictures of code / error messages, because pictures like this are not accessible to readers who cannot see them and are not indexable by search engines.)

We use issues in this repository only for tracking bugs and enhancement requests, so I'm going to close this issue. Thanks!
