### ISSUE TITLE
Terraform client - private module registry service discovery - strange behaviour

### ISSUE THREAD

**Issue by AdamCoulterOz** [hashicorp/terraform#30795]
### Terraform Version

```
Terraform v1.1.7
on darwin_arm64
```

### Terraform Configuration Files

```terraform
module "mymodule" {
  source  = "terraform.mycompany.com.au/mycompany/mymodule/azurerm//submodule"
  version = ">= 1.0.0"
}
```

### Debug Output

```
[INFO]  Terraform version: 1.1.7
[INFO]  Go runtime version: go1.17.6
[INFO]  CLI args: []string{"terraform", "init"}
[DEBUG] Attempting to open CLI config file: .terraformrc
[INFO]  Loading CLI configuration from .terraformrc
[INFO]  CLI command args: []string{"init"}
[TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
[DEBUG] Module installer: begin mymodule
[TRACE] ModuleInstaller: mymodule is not yet installed
[TRACE] ModuleInstaller: cleaning directory .terraform/modules/mymodule prior to install of mymodule
[TRACE] ModuleInstaller: mymodule is a registry module at terraform.mycompany.com.au/mycompany/mymodule/azurerm//submodule
[DEBUG] mymodule listing available versions of terraform.mycompany.com.au/mycompany/mymodule/azurerm//submodule at terraform.mycompany.com.au
[DEBUG] Service discovery for terraform.mycompany.com.au at https://terraform.mycompany.com.au/.well-known/terraform.json
[TRACE] HTTP client GET request to https://terraform.mycompany.com.au/.well-known/terraform.json
[DEBUG] fetching module versions from "https://terraform.mycompany.com.au/.well-known/v1/modules/mycompany/mymodule/azurerm/versions"
[DEBUG] GET https://terraform.mycompany.com.au/.well-known/v1/modules/mycompany/mymodule/azurerm/versions
[TRACE] HTTP client GET request to https://terraform.mycompany.com.au/.well-known/v1/modules/mycompany/mymodule/azurerm/versions
[TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
```

The `https://terraform.mycompany.com.au/.well-known/terraform.json` returns the following:

```json
{
    "providers.v1": "v1/providers",
    "modules.v1": "v1/modules"
}
```

It all goes bad once it tries to get the module versions, as somehow the `.well-known` path is making its way into the get versions url, and it shouldn't be there?

`fetching module versions from "https://terraform.mycompany.com.au/.well-known/v1/modules/mycompany/mymodule/azurerm/versions"`

The `GET https://terraform.mycompany.com.au/.well-known/v1/modules/mycompany/mymodule/azurerm/versions` returns a `404 Not Found` which is what my module registry web server does when the url path isn't valid, but the terraform client interprets that as the module not being found, hence why the `error looking up module versions` error isn't being reached.

### Expected Behavior

The module should have been downloaded.

### Actual Behavior

```
terraform init
Initializing modules...
╷
│ Error: Module not found
│ 
│ Module "mymodule" (from test.tf:1) cannot be found in the module registry at terraform.sentral.com.au.
╵
```

### Steps to Reproduce

`terraform init`

### Additional Context

I've already debugged the client code, and found that the service URL in the below line is where my error message comes from:

https://github.com/hashicorp/terraform/blob/affe2c329561f40f13c0e94f4570321977527a77/internal/registry/client.go#L131

And several layers in it turns my relative module repo path into an absolute url, which uses the `discoURL` as the URL resolver  instead of the `hostname`?

https://github.com/hashicorp/terraform-svchost/blob/f050f53b97348772833a8f7fc1b297ec71f9fc7c/disco/host.go#L281

**Comment by apparentlymart** [comment]
Hi @AdamCoulterOz,

When resolving relative URLs during service discovery, Terraform follows the standard URL resolution algorithm -- the same as would happen for a `href` in an HTML document, for example -- to interpret the given URL relative to the document containing it, which is `https://terraform.mycompany.com.au/.well-known/terraform.json` in your case.

By my understanding of what you said, it seems like the behavior you saw was working as intended: `v1/providers` relative to the above URL is resolved by first trimming the filename part `terraform.json` and then concatenating the relative path, yielding `https://terraform.mycompany.com.au/.well-known/v1/providers`. This is the same as if you had put an HTML document at `https://terraform.mycompany.com.au/.well-known/example.html` which contained a link like `<a href="v1/providers">...</a>`.

If your intention was for the base URL to be `https://terraform.mycompany.com.au/v1/providers` then there would be a few different ways to specify that:

* Absolute: write exactly `https://terraform.mycompany.com.au/v1/providers` into the document.
* Root-relative: write `/v1/providers` into the document, causing Terraform to first truncate the whole path portion of the URL and use the given path instead.
* Relative: write `../v1/providers` into the document, specifying to first traverse out of the `.well-known/` part to reach the root, and then append `v1/providers` from there.

The other thing to watch out for here is that Terraform uses a the same standard relative URL resolution for most of the other URL wrangling it does related to the API, and so I would recommend including a trailing slash on the two paths you specified so that URLs generated relative to those will append to the end rather than risking just replacing the `modules` or `providers` segment as if it were a filename.

For example, if you use the root-relative option from the list above then the final document would look like this:

```json
{
    "providers.v1": "/v1/providers/",
    "modules.v1": "/v1/modules/"
}
```

Could you try that and let me know if it works? Thanks!

**Comment by AdamCoulterOz** [comment]
@apparentlymart - thanks so much for the thorough explanation. I understood how URL resolution works, I misunderstood how that path resolution is supposed to be relative to the discovery URL path and not just the root.

Go Playground showing how the leading `/` changes the relative path and fixes the problem.
https://go.dev/play/p/BRi_2Ck1w6j

Thanks!!
