### ISSUE TITLE
ciscodevnet/aci: interpolating on resources arguments causes wrong config order w broken dependencies

### ISSUE THREAD

**Issue by rdelmontcisco** [hashicorp/terraform#30809]
### Terraform Version

```
Terraform v1.1.7
on linux_amd64

```

### Terraform Configuration Files

```terraform
https://github.com/rdelmontcisco/tfciscodevnetbugs
```

### Debug Output

https://gist.github.com/rdelmontcisco/58a7cc7a9ecd85dfed37892b95103d77

### Expected Behavior

Expected TF creating resources with attributes defined by interpolating variables from tfvars file using for_each loop. Requirement:  scale config by iterating through variables defined in maps

### Actual Behavior

at first terraform apply, objects dependencies are broken. If doing terraform apply further without any changes in config, dependencies are resolved and configs are pushed completely 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. to resolve dependencies: `terraform apply` a couple of times more, depending on the number of objects configured

### Additional Context

None

### References

None

**Comment by jbardin** [comment]
Hi @rdelmontcisco,

I'm not familiar with the aci provider, but the configuration doesn't appear to have any references between most of the resources, so there is no way for terraform to infer the require dependency ordering.  Taking the last error for example, where `aci_subnet.demosubnet` returned an error about "Object may not exist", the configuration for that resource only refers to the input variables, therefor has no dependency on any of the other resources within the module. If there are required dependencies within the module, the configuration will need to be structured to represent those dependencies, possibly using `depends_on` when those dependencies cannot be expressed directly.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. 

Thanks!
