### ISSUE TITLE
Launch Template/EC2 Support for Auto-Recovery Setting

### ISSUE THREAD

**Issue by JohnnyBoi888** [hashicorp/terraform#30806]
Hi, wondering if we can get an ETA on when auto-recovery setting will be supported via Terraform w/ the recent new feature implemented by AWS to auto-enable on supported instance types: https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ec2-default-automatic-recovery/ (to be clear, I'm looking for a way to disable this behavior until we learn about the ramification of replaced instances), thanks!

**Comment by apparentlymart** [comment]
Hi @JohnnyBoi888,

Since this feature seems to be related to EC2 instances I think it's the responsibility of the AWS provider rather than Terraform Core. I suggest opening a feature request for this in [the AWS Provider repository](https://github.com/hashicorp/terraform-provider-aws) instead. When you do so, please be sure to fully complete that repository's feature request issue template so that the provider team can have all of the information required to understand the feature you are requesting.

This repository only contains code for the provider-agnostic core runtime, so I'm going to close this issue. Thanks!
