### ISSUE TITLE
Add techniques to the alert rule scheduled in addition to tactics from the mitre att&ck framework (azurerm_sentinel_alert_rule_scheduled)

### ISSUE THREAD

**Issue by Thz4UQgy** [hashicorp/terraform#30801]
### Current Terraform Version

Run `terraform version` to show the version, and paste the result between the ``` marks below. This will record which version was current at the time of your feature request, to help manage the request backlog.

If you're not using the latest version, please check to see if something related to your request has already been implemented in a later version.

```
3.0.2
```

### Use-cases

azurerm_sentinel_alert_rule_scheduled (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sentinel_alert_rule_scheduled) we need the possibility to add techniques to the alert rule scheduled in addition to tactics from the mitre att&ck framework. This is possible via ARM but not yet via Terraform

### Attempted Solutions

No possible workaround.

**Comment by riyadmurad** [comment]
It would be very handy to have this feature. especially we are deploying Sentinel as a Code

**Comment by apparentlymart** [comment]
Hi @Thz4UQgy,

If I'm understanding correctly, this seems to be a feature request for the Azure provider rather than for Terraform Core. Is that true? If so, please report it in the Azure provider's own repository do that the maintainers of that provider can consider it.

Provider developers do not typically monitor issues in this repository, and changes in this repository cannot add new features to those providers.

Thanks!

**Comment by Thz4UQgy** [comment]
Hi @apparentlymart 

Yes you are right it is the terraform azure provider azurerm.

Thank you ;)
