### ISSUE TITLE
[1.2.0 alpha-20220328] Irrelevant changes outside of terraform still being shown in plans

### ISSUE THREAD

**Issue by paul-civitas** [hashicorp/terraform#30833]
### Terraform Version

```
Terraform v1.2.0-alpha-20220328
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
```

### Expected Behavior

When we run a terraform plan on our redshift clusters we get a lot of notifications that our `cluster_revision_number` has changed outside of terraform. This is related to #28803

A comment on the issue says:

> Starting with v1.2, the goal for the refresh report is that only external changes which may have contributed to changes in the plan will be shown. 

So the expected behavior for 1.2 was that that refresh report wouldn't include these types of noisy changes, as we're not managing the `cluster_revision_number` via terraform, and this attribute is constantly changed by the cloud provider.

### Actual Behavior

The actual behavior is that the terraform plan shows a bunch of information about `cluster_revision_number` which makes it harder to see the relevant changes, and that there's no way to filter out this noise in the plan output.

This is especially impactful to us because the module in question can be touched by more junior engineers and 

### Steps to Reproduce

Create redshift clusters via terraform. Observe that the `cluster_revision_number` is constantly changing outside of terraform, that there's no way to suppress these messages, and that the promised improvements in 1.2 don't seem to be implemented yet even though it's currently in alpha.

### References

A comment in #28803 mentioned that this would be addressed in 1.2 but I don't see an open ticket to track the feature.

**Comment by jbardin** [comment]
Hi @paul-civitas,

Thanks for the feedback. In order to try and determine why Terraform determined the change was relevant to the plan, we would need the configuration and plan output for reference. The next alpha will hopefully improve the diff rendering to make it a bit more specific, so you may have better results as the release matures.

The goal is for Terraform to only show changes which may be relevant to the plan. As for what constitutes "relevant", that always differs by how the values are used the configuration, so the configuration is needed for us to examine why the changes were included in the plan output. There will be still cases where it's not possible to determine which _part_ of a value was contributing to the planned changes, so more attributes than necessary may be shown, but these should still only be shown when at least part of the value was used by the planned change. If you have examples to work with, that would be useful to work on improving the output.

Thanks!

**Comment by paul-civitas** [comment]
Hey this particular instance is a bit tricky to just copy paste without it including sensitive information. I'll try and find some time to create a non production workspace to reproduce this in, but it might be a bit before I can find the time to do this.

**Comment by paul-civitas** [comment]
Sorry I don't have time for this at the moment. But hopefully someone else can dig in a bit.

Looking forward to the 1.2 release!

**Comment by jbardin** [comment]
We have not heard back in a a while, so closing this out.
The implementation has been improved since the initial alpha release, but if there are still concerns, please file a new issue with a complete example showing the unexpected output.

Thanks!
