### ISSUE TITLE
Documentation: `terraform apply` help does not mention the `-destroy` flag

### ISSUE THREAD

**Issue by pjh** [hashicorp/terraform#30839]
https://www.terraform.io/cli/commands/destroy says that `terraform destroy` is an alias for `terraform apply -destroy`, but https://www.terraform.io/cli/commands/apply does not mention the `-destroy` option at all. Neither does the output when I run `terraform apply -help` (version v1.1.7).

These two docs pages are not only inconsistent with each other, but destroy should be mentioned in the `apply` documentation to help with discovery. I'm a new Terraform user and I tried to find a way to reverse the results of `terraform apply`, but I didn't see anything about this topic in the help for `apply`. I didn't know about the destroy command / flag until a team member mentioned it to me.

**Comment by apparentlymart** [comment]
Hi @pjh! Thanks for reporting this.

The section [Automatic Plan Mode](https://www.terraform.io/cli/commands/apply#automatic-plan-mode) describes this behavior indirectly: if you are running `terraform apply` without a plan file then that command will internally behave as if it is running `terraform plan` itself, and so all of the planning options are available in that case 

Since these are planning options rather than applying options, they are currently documented only on the planning page.

We are aware that this situation is non-ideal but haven't yet found a compromise that doesn't cause the apply page to effectively include all of the content from the plan page, thus obscuring the additional options that are explicitly about applying. However, we do intend to continue iterating on the organization of these documents.

**Comment by laurapacilio** [comment]
Hi @pjh thank you! I want to reiterate what Martin said - Our goal is to make sure that the `apply` page emphasizes the particulars of applying. We have several call outs on this page that let users know that they can use all of the options for plan.

However, I think it might help if we actually gave some indication about what the "planning modes" and "planning options" include when we mention them on the apply page. I created a PR that revises some of the language on the `apply` page so it's more streamlined. As part of that work, I add context for the planning modes and options, which includes listing the `-destroy` option and providing a brief description. This should help with discoverability without having to repeat all of the planning options again on the apply page.

https://github.com/hashicorp/terraform/pull/31197

Let me know if you have feedback. Thank you!
