### ISSUE TITLE
Ability to Pre-provision Resources for Acceptance Tests

### ISSUE THREAD

**Issue by GMRiley** [hashicorp/terraform#30859]
### Current Terraform Version
```
1.1.8
```

### Use-cases

I'm working on acceptance tests on a TF provider for an application that leverages aws resources. I'm trying to provision ephemeral aws resources prior to my TF provider's acceptance tests running against my service. These resources would be destroyed at the end of the testing cycle.

### Attempted Solutions

Common solution appears to be writing terraform, applying it, then running the acceptance testing. For ex: https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/kubernetes/test-infra

### Proposal

Given that we can add ExternalProviders to acceptance testing, would we also be able to leverage these to create external resources? Much like how you can PreCheck dependencies for acceptance tests, I'd like to be able to PreCheck or PreProvision cloud dependencies that would allow for my acceptance tests to run. Here we would get the ability to keep test infrastructure localized in one testing suite, while being able to perform validation or pass along data regarding infrastructure to your acceptance testing.

**Comment by apparentlymart** [comment]
Hi @GMRiley!

From what you've said here I think you are talking about the provider acceptance testing helpers in SDKv2. If so, I'd suggest opening this issue in [the SDKv2 repository](https://github.com/hashicorp/terraform-plugin-sdk) instead, since that's the repository that the SDK team routinely monitors, and that team is the one responsible for the acceptance testing functionality.

Thanks!

**Comment by GMRiley** [comment]
Thanks @apparentlymart ! I'll send it on over
