### ISSUE TITLE
Trivy triggers on go.mod dependency go.etcd.io/etcd

### ISSUE THREAD

**Issue by HammerNL89** [hashicorp/terraform#30877]
### Terraform Version

```
v1.1.8
...
```

### Terraform Configuration Files

```terraform 
...
```
### Problem
When scan our dev container that contains Terraform with Trivy. Trivy reports the following vulnerability:
![image](https://user-images.githubusercontent.com/6350295/163555588-528a2e7a-1d6b-40ad-afe6-5138b96d123a.png)
 This is triggered by the version of etcd in the [go.mod file](https://github.com/hashicorp/terraform/blob/main/go.mod):
 `go.etcd.io/etcd v0.5.0-alpha.5.0.20210428180535-15715dcf1ace`

Is there a reason for having this dependency pinned on this old version, or could this be upgraded?

**Comment by apparentlymart** [comment]
Hi @HammerNL89,

Terraform includes two backends for etcd, "etcdv2" and "etcdv3". The first of these is intentionally being a client for an older version of etcd. If you do not use either of these backends then you will not be using any code from the etcd library.

We are considering the possibility of dropping support for one or both of these backends in a future Terraform version, since they seem to be relatively unpopular compared to other backends, but we cannot do that until we complete some research to understand the impact of doing so.

**Comment by apparentlymart** [comment]
Terraform v1.3.0 includes #31347 which removed the `etcdv3` backend, and #31326 which removed the `etcd` backend, both of which were unmaintained but retained on a best effort basis as long as we were able.

The removal of both of those led to us also removing all of our references to the `go.etcd.io/etcd` module, so we no longer have a dependency on that module at all and so this codebase should no longer trigger the false-positive warning for folks who weren't using that backend anyway.

Thanks for reporting this!
