### ISSUE TITLE
Azure virtual network should support resource group

### ISSUE THREAD

**Issue by RichardKnop** [hashicorp/terraform#3089]
It should be possible to specify a resource group when defining a network.

For instance:

```
resource "azure_virtual_network" "bastion" {
  name = "foo-bastion-network"
  address_space = ["${var.virtual_network_cidr}"]
  location = "West Europe"

  subnet {
    name = "foo-bastion-subnet"
    address_prefix = "${var.bastion_cidr}"
  }
}
```

Should also support parameter `resource_group_name` just as you are able to do with Azure CLI tool:

```
azure resource create some_resource_group ...
```

**Comment by keymon** [comment]
+1

We need to create the network to use it later by other provisioner ([Azure BOSH CPI for cloufoundry](https://github.com/Azure/bosh_azure_cpi)). 

That provisioner expects the network to be in a specific resource group.

Currently we workaround it by creating the network manually with azure cli.

```
azure config mode arm
azure resource create \
	${resource_group_name} \
	${network_name} \
	Microsoft.Network/virtualNetworks \
	'West Europe' 2015-05-01-preview \
	-p "{\"addressSpace\": {\"addressPrefixes\": [\"${network_cidr}\"]},\"subnets\": [{\"name\": \"${subnet_name}\",\"properties\" : { \"addressPrefix\": \"${subnet_cidr}\"}}]}"
```

Ofc, if the network is created in a customised resource group, the instances created with `azure_instance` should be able to find that network. Maybe this requires more changes (we will add other request for that).

**Comment by aznashwan** [comment]
@RichardKnop @keymon: the initial implementation of the Azure provider used the bindings for the old ASM-based API's; as those were sadly the only ones available at the time. As a result; a lot of features seem to be missing when in fact they were plain and simply not available in the API used by the go sdk at the time.

The transition to using the new ARM-based sdk has already been set in motion. Please feel free to track/chip into the discussion here: https://github.com/hashicorp/terraform/issues/3212

**Comment by tombuildsstuff** [comment]
👋 hi @RichardKnop / @keymon / @aznashwan 

Taking a look into this issue - from what I can see this issue's actually related to AzureRM, rather than Azure Service Management - as it doesn't appear to be possible to set the resource group for a Virtual Network created via Service Management?

Support for [Virtual Networks with a resource group has been included in the Terraform AzureRM Provider](https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html) for a while now - and as such I think this issue can be closed?

Please feel free to re-open this issue if that's not the case :)

Thanks!
