### ISSUE TITLE
Lookup function ignoring default values 

### ISSUE THREAD

**Issue by Nagendran2807** [hashicorp/terraform#30890]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

resource "aws_security_group_rule" "ingress_cidr_blocks" {
    for_each = (var.create_sg && length(var.ingress_with_cidr_blocks) > 0) ? var.ingress_with_cidr_blocks : {}
     security_group_id = aws_security_group.sg[0].id
     type = "ingress"
     from_port = lookup(each.value,"from_port")
     to_port = lookup(each.value,"to_port")
     protocol = lookup(each.value,"protocol", "tcp")
     description = lookup(each.value,"description", "test rule")
     cidr_blocks = split(",", lookup(each.value,"cidr_blocks", null))
     ipv6_cidr_blocks = lookup(each.value,"ipv6_cidr_blocks", null)
}

    variable "ingress_with_cidr_blocks" {
          type = map(map(string))
           default = {
            rule1 = {
              from_port = "80"
              to_port = "80"
              cidr_blocks = "172.16.0.0/16,10.0.0.0/16"
          }                     
    }

**Comment by Nagendran2807** [comment]
Error:
Invalid value for "default" parameter: the default value must have the same type as the map elements.

Expected Behaviour:
No error

Not sure what I missed here... can anyone have a look and help on this

When I set ipv6_cidr_blocks = null then working but when I use lookup then it will throw error

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. You will also want to ensure that you are testing with the latest Terraform release, and provide a complete example which can reproduce the problem you are facing.

Thanks!
