### ISSUE TITLE
functionality of for functions

### ISSUE THREAD

**Issue by giantosti-bt** [hashicorp/terraform#30927]
### Current Terraform Version

```
1.1.9
```

### Use-cases

for loop does not work when a string (or single object) is passed as a collection "A value of type string cannot be used as the collection in a 'for' expression."
 
### Attempted Solutions

tried tolist(string), but resulted in error message "Invalid value for "v" parameter: cannot convert string to list of any single type."

**Comment by alisdair** [comment]
Hello! It's not clear to me what you expected to happen when using a `for` expression with a non-iterable value, so without more information I don't think there's much we can do here.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
