### ISSUE TITLE
AWS Redshift Serverless

### ISSUE THREAD

**Issue by alex-dolbik** [hashicorp/terraform#30976]
Hi there,

I checked terraform documentation and don't see any way to create AWS Redshift Serverless endpoint. Looks like terraform supports only redshift clusters creation.
https://aws.amazon.com/redshift/redshift-serverless

### Current Terraform Version
4.12.1

### Use-cases
Ability to use new AWS Redshift Serverless instances

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by apparentlymart** [comment]
Hi @alex-dolbik,

I think this issue is a feature request for the AWS provider, rather than for Terraform itself. Each provider is a separate program with its own repository, so we cannot make changes to provider behavior in this repository.

I suggest opening an issue in [the AWS provider's repository](https://github.com/hashicorp/terraform-provider-aws) to discuss this feature. There might already be a similar issue open, so I'd recommend searching the issues first to see if you find anything similar.

Thanks!
