### ISSUE TITLE
Provide a .tfvars equivalent that allows locals to be defined as well

### ISSUE THREAD

**Issue by zenbones** [hashicorp/terraform#30970]
The .tfvars files have obvious utility as they allow sets of variables that make sense as whole to be defined together. Far better to have these presets available so that the user of a module can ask for 'local-install.tfvars' as opposed to 'remote-install.tfvars' and know that everything will make sense without having to understand and define the separate components of each use case. By the same logic, there are sets of constants which must often be defined to encompass a use case as well. We don't want variable definitions for these things. We could, obviously, add these constants as vars to the module, and define the vars in the .tfvars files, but the implied meaning is that these things could be overridden or set independently, when that is not true. We could keep them in a .tf file as a block of locals, but then each key/value ends if being a block of if-then constructs, for example, extending our use case, if local install set thee else if remote install set those. This quickly grows into an uncomfortable hack with just a handful of use cases. What I want is a local block, or its equivalent, I can set along with my vars in a single file encompassing the entire use case.

**Comment by apparentlymart** [comment]
Hi @zenbones! Thanks for sharing this use-case.

I'd like to understand better why input variables are not the appropriate solution to your problem. Local values are _by design_ fixed expressions that only depend on data from elsewhere in the module, whereas input variables are the typical mechanism for passing data into a module.

**Comment by zenbones** [comment]
That's exactly it. What's appropriate are fixed expressions that rely on data from elsewhere in the module, but in this case that data from elsewhere are appropriately vars. Because these vars are, by definition, dynamic, that makes the local values dynamic and directly dependent on those vars. If the locals are defied in the same file as the vars then they become, essentially, constants associated with that particular set of vars. If the locals must be defined elsewhere then they become what, in other languages, would be the result of switch expressions, except terraform doesn't have switch expressions, nor should it.

.For instance we might ask for the AWS region a cluster is to be constructed in, knowing that the format of the arn is dependent upon it (for example arn:aws:... or arn:aws-cn:...).

I could define...

variable "aws_region" {
  type        = string
  description = "The aws region for this module"
}

locals {
  arn_locale = var.aws_region == "cn-north-1" ? "aws-cn" : "aws"
}

As long as AWS does not come up with another arn format (is there one for Europe, I don't know) this is ugly but serviceable. But I can see other pieces of data that are entirely dependent on vars, but do not themselves need to be vars because they can always be derived from the information the user *must* give us, but which have more than 2 use cases. But even taking this concrete example, it might be nicer to define...

us-east-1.tfvars

variables {
  aws_region = "us-east-1'
}

locals {
  arn_locale = "aws"
}

... and ...

cn-north-1.tfvars

variables {
  aws_region = "cn-north-1'
}

locals {
  arn_locale = "aws-cn"
}

I could just make the arn_locale a var, but the user does not ever need to provide it, nor should they ever be prompted for it. Each 'use case', as in each .tfvars file should provide it, or an error should be thrown. A local is great if the use cases are very few and can be handled with ternary operators, but that is always going to be ugly. A var is great for information the user can and should be prompted for if it's left out. I would like a way to provide the constants that go along with a set of vars that the user should never be prompted for.

I know this seems kind of academic, and it is, but the distinction would be great for long term maintenance of modules.

**Comment by apparentlymart** [comment]
Thanks for sharing this additional context, @zenbones.

I think the part of your framing that I still find a little confusing is that you say that there is no need for the user to provide the AWS partition ("locale" in your case) for a particular region, but yet you show it being set in a `.tfvars` file which is a file which represents user input. So in effect you have made input variables and local values exactly equivalent but in separate namespaces.

With current Terraform the usual way to solve this problem would be to use a map in a local value to look up the partition for a given region. That then ensures that the user can override only the region and the partition table is fixed as part of the module, which is the intended distinction between these two concepts.

This particular case is interesting because you are talking about a mapping that is defined by AWS itself as part of its SDKs, and so in principle the AWS provider should be able to provide this result for you. In practice [the `aws_region` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region) doesn't seem to export the partition for the selected region, but it seems to me like it could do so in principle, since the provider should have access to that information. I wonder if the AWS provider team would be prepared to add that so that you would not need to maintain your own mapping table for this.

**Comment by zenbones** [comment]
This is old and I've worked around it, and I think you're correct about whose problem this is, so I'll close this here and open something aws_region specific if I think it's worthwhile.
