### ISSUE TITLE
Issue while updating Cognito User Pool. (UpdateUserPoolInput.AccountRecoverySetting.RecoveryMechanisms)

### ISSUE THREAD

**Issue by ItsDevMonk** [hashicorp/terraform#31007]
If I create User pool with terraform it is working fine. In state file, account recovery setting is empty.
```
"attributes": {
     "account_recovery_setting": [],
     "admin_create_user_config": ....
```
But If i import the existing UserPool into terraform, then the same attribute will update like below,
 ```
"attributes": {
      "account_recovery_setting": [
       {
         "recovery_mechanism": []
       }
     ],
     "admin_create_user_config": ....
```

Since this recovery_mechanism is added to state file, I can't update anything in UserPool. If I change some data I will get the below error

```
aws_cognito_user_pool.pool: Modifying... [id=us-east-1_xxxxxy]

Error: error updating Cognito User pool (us-east-1_xxxxxy): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, UpdateUserPoolInput.AccountRecoverySetting.RecoveryMechanisms.
```

 How can I fix this? I don't have account recovery settings in tf file. But still it is giving this error.
 
 Note: This is same if I create the UserPool with terraform (not the import) and run `terraform refresh` command.
 
 I think, there is an issue during the describe UserPool api call.

**Comment by apparentlymart** [comment]
Hi @ItsDevMonk! Sorry for this confusing error.

This error message seems to be coming from the AWS provider rather than from Terraform Core, so I'd suggest starting a topic about it in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) or, if you consider this to be a bug report rather than a usage question, open an issue in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws).

This repository is only for the development of the vendor-agnostic Terraform Core language runtime and CLI tool, so we don't have the necessary expertise to help with AWS-specific problems here. For that reason, I'm going to close this issue. Thanks!
