### ISSUE TITLE
Terraform ignore lifecyle not working when it need to refresh state

### ISSUE THREAD

**Issue by imadityac** [hashicorp/terraform#31005]
### Terraform Version

```
Terraform v0.12.29
+ provider.aws v3.37.0

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "eu-central-1"
}

resource "aws_instance" "web" {
  ami           = "ami-02584c1c9d05efa69"
  instance_type = "t3.micro"
  tags = {
    Name = "myname"
   }
  lifecycle {
    ignore_changes = [
      tags["startby"], tags["stopby"]
    ]
  }
}

```

### Expected Behavior

```
aws_instance.web: Refreshing state... [id=i-xxxxxxxxxxxxxxxxx]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
### Actual Behavior

```
 ~ tags                         = {
            "Name"    = "myname"
          - "startby" = "b" -> null
        }
```
### Steps to Reproduce

Hi All

Let's consider the below scenario, 
I created AWS EC2 using the above .tf file where I only gave tag as `Name="myname"`,  and also added `startby` and `stopby` in `lifecycle ignore_changes`.

There is one automation in the account which is changing `startby` & `stopby` tags for that ec2 couple of times a day.
`startby` and `stopby` tags are containing time. which is impossible to sync with terraform every time.

Every time I am getting drifts as shown above for `startby` & `stopby` tags.

### Additional Context

This may be due to the older terraform version that I am using `0.12.29`, But it's very hard to upgrade terraform version for all infra,

is there any workaround that can helpful for me?

Thanks in Advance

**Comment by jbardin** [comment]
Hi @imadityac,

Sorry you're having difficulty with this issue. The ability to ignore individual map keys which are not set at all was added to `ignore_changes` in 0.14. The only option available prior to that would be to ignore the entire map.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
