### ISSUE TITLE
Provider needed should be configured through specific attributes by users, not  opinionated yourself.

### ISSUE THREAD

**Issue by bretagne-peiqi** [hashicorp/terraform#31004]
https://github.com/hashicorp/terraform/issues/31002

**Comment by bretagne-peiqi** [comment]
this will cause big problem for users.

**Comment by apparentlymart** [comment]
Hi @bretagne-peiqi!

I'm afraid I'm not sure what you intend this bug to represent. Could you please copy [the bug report template](https://raw.githubusercontent.com/hashicorp/terraform/main/.github/ISSUE_TEMPLATE/bug_report.md) into a new comment and provide the information it requests, so that we can learn more about what problem you're describing? Thanks!

**Comment by maxb** [comment]
I believe this is just a terse objection to the previous issue, #31002, being closed. I've commented on the previous issue and believe this one can be closed as a duplicate.

**Comment by apparentlymart** [comment]
Closing as a duplicate of the other issue.
