### ISSUE TITLE
Support "terraform output" offline flag for remotes

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#3100]
When I set up remote via `terraform remote`, then either go offline or just don't have access to the remote, I get the following behaviour:

```
$ terraform output
Error reading state: Error reloading remote state: AccessDenied: Access Denied
    status code: 403, request id: []
```

I understand the aim of terraform - trying to be up to date since the latest state will always be in that remote storage, but I think there should be a way how to just print out what's in the local state file.

e.g. `terraform output -local` or `terraform output -no-reload`

**Comment by apparentlymart** [comment]
At the time this issue was opened we had a local state cache even when remote state was enabled and that could potentially have been used to implement this.

Unfortunately since Terraform 0.9 there is no longer a local cache of the state, and so running `terraform output` in offline mode no longer makes sense and I'm going to close this.
