### ISSUE TITLE
Terraform Registry is providing inconsistent 'downloads' totals via API and the UI (for some modules)

### ISSUE THREAD

**Issue by colinwilson** [hashicorp/terraform#31022]
The Terraform Registry seems to be providing inconsistent 'Downloads over all time' information for some modules.

Using my [traefik](https://registry.terraform.io/modules/aigisuk/traefik/kubernetes/latest) module as an example

The UI shows:
![2022-05-10 02_16_38-aigisuk_traefik_kubernetes _ Terraform Registry — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/167523352-493ddbed-8798-4590-91b7-983d771fc846.png)

However, API call results in a lower value:
```
❯ curl -s https://registry.terraform.io/v1/modules/aigisuk/traefik/kubernetes | jq '.downloads'
113
```
The [namespace view](https://registry.terraform.io/namespaces/aigisuk) seems to follow the API results:
![2022-05-10 02_19_58-AIGIS _ Terraform Registry — Mozilla Firefox](https://user-images.githubusercontent.com/12916656/167523653-f216dee0-f330-4ce5-8616-c5805e671696.png)

**Comment by alex-feel** [comment]
I ran into the same problem today, and even yesterday the API was returning the correct downloads value. Today, instead of just over 2000 downloads, the [API returns](https://registry.terraform.io/v1/modules/alex-feel/zone/cloudflare) only 4 for [this module](https://github.com/alex-feel/terraform-cloudflare-zone) 🙂

**Comment by alisdair** [comment]
The registry issue has now been fixed and the correct download numbers should be returned from the API.
