### ISSUE TITLE
No way to update timeouts without an apply

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#31023]
### Terraform Version

```
v1.1.9
```

### Description

Deploy following config:

```
resource "azurerm_resource_group" "test" {
  name     = "mgd-test123"
  location = "eastus2"
}
```

The default timeouts are set:

```
$ cat terraform.tfstate | jq '.resources | .[] | select(.type == "azurerm_resource_group") | .instances[0].private' | tr -d '"' | base64 -d | jq '.["e2bfb730-ecaa-11e6-8f88-34363bc7c4c0"]'
{
  "create": 5400000000000,
  "delete": 5400000000000,
  "read": 300000000000,
  "update": 5400000000000
}
```

Adding the `timeouts` for `read = "10m"`, and refresh, the stored meta in state is not changed for the read timeout:

```
$ tf refresh
azurerm_resource_group.test: Refreshing state... [id=/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/mgd-test123]
$ cat terraform.tfstate | jq '.resources | .[] | select(.type == "azurerm_resource_group") | .instances[0].private' | tr -d '"' | base64 -d | jq '.["e2bfb730-ecaa-11e6-8f88-34363bc7c4c0"]'
{
  "create": 5400000000000,
  "delete": 5400000000000,
  "read": 300000000000,
  "update": 5400000000000
}

```

Also, the `terraform plan` shows no diff.

The only way to update the timeout is to change something in the resource to trigger an apply:

```
$ tf apply -auto-approve
...
Terraform will perform the following actions:

  # azurerm_resource_group.test will be updated in-place
  ~ resource "azurerm_resource_group" "test" {
        id       = "/subscriptions/0000/resourceGroups/mgd-test123"
        name     = "mgd-test123"
      ~ tags     = {
          + "foo" = "bar"
        }
        # (1 unchanged attribute hidden)

      + timeouts {
          + read = "10m"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

$ cat terraform.tfstate | jq '.resources | .[] | select(.type == "azurerm_resource_group") | .instances[0].private' | tr -d '"' | base64 -d | jq '.["e2bfb730-ecaa-11e6-8f88-34363bc7c4c0"]'
{
  "create": 5400000000000,
  "delete": 5400000000000,
  "read": 600000000000,
  "update": 5400000000000
}
```

This is fine in most cases, as simply updating the timeout for the resource is meaningless, until any operation happens to the resource, i.e. when applying.

However, there is an unfortunate fact that the new timeout only takes effect after the plan stage (`PlanResourceChange` in context of the proto) during apply, but not before, i.e. the read (`ReadResource` in context of the proto) during refresh is still using the old read timeout. This causes issues like https://github.com/hashicorp/terraform-provider-azurerm/issues/14213, where users are managing a collection of same typed resources, the default timeout of it is not long enough to finish the read. In that case, changing the `timeout` for read doesn't work for the `terraform apply`/`terraform plan` as the refresh part will still use the old timeout, results into timeout.

The workaround for this is:

1. Either make a dummy change for all these resources to trigger an apply (with `-fresh=false` to avoid refreshing)
2. Or recreate all these resources with timeout set before apply

Both solutions seem not ideal, so I'm submitting this issue for a dedicated way to change the timeouts in the state.

**Comment by jbardin** [comment]
Hi @magodo,

Thanks for the bug report! Unfortunately the initial read of a resource, i.e. "refresh", is not going to get any new configuration settings, because that it purposely executed without input from the configuration to get the latest known state.  from the provider. Since timeouts are a configuration setting, changes are going to require an apply to store.

Timeouts as far as Terraform is concerned are just normal attributes in the configuration, and it's up to the provider to determine how they are used. The `private` field you are inspecting here is part of the unusual manner in which the old SDK handled timeouts, and it's entirely up to the SDK to manage the data in that field (the protocol states that Terraform does not alter the `private` field at all, and it's not even decoded or read by core).

I think changing the timeouts however should be possible with an apply, so we can take a look at how this is interacting with the legacy plugin code to see what it's doing.

**Comment by jbardin** [comment]
Took a look to confirm what the SDK is doing, and it's what I suspected, changes to timeouts are discarded by the provider when there are no accompanying changes, since the SDK doesn't see that as a change in the resource. I can't recall if there is a pragmatic reason for this, or if it is an oversight, but that is something which can only be fixed in the SDK. Since the planning of timeout changes would need to be handled in the SDK, you can open a new issue in that repository for investigation. 

The timeouts requiring any apply is expected, since that is how Terraform stores changes to the configuration in the state. We can leave this open for future research into other ways to handle the situation, but there isn't much we can do directly within the currently defined resource lifecycle.

**Comment by magodo** [comment]
@jbardin Thank you for the confirmation! I've opened issue on the SDK repo: https://github.com/hashicorp/terraform-plugin-sdk/issues/963.

**Comment by crw** [comment]
As this issue has moved to the SDK, I'm going to close this one. Please let me know if I am closing this in error. Thanks!
