### ISSUE TITLE
data no matching FR

### ISSUE THREAD

**Issue by systemJine** [hashicorp/terraform#31037]
Hello.
We use data sources to import and utilize AWS real-time data.

If there is no data, an error occurs.
I want to return an empty value so that no errors occur.

Is it possible?
Thank you.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

The behavior of the data source is defined by the provider, and in most cases failure to find a resource needs to be an error since that result would be used elsewhere in the configuration. Some data sources have a plural version which is intended to find 0 or more values, but that again would be implemented by the provider itself.

Thanks!
