### ISSUE TITLE
New Releases API has broken query parameters

### ISSUE THREAD

**Issue by Jukie** [hashicorp/terraform#31033]
There's currently no way to use the [getReleasesV1](https://releases.hashicorp.com/docs/api/v1/#operation/getReleasesV1) api and get a list of releases prior to the most recent 20 (or whatever is specified for `limit`, max 20). The `after` parameter always returns the latest available release instead of the most recent release nearest to the given timestamp.

If I could offer additional feedback, even if this was fixed it'd still be challenging to get a list without hardcoding the timestamp from the first 0.1.0 release. Ideally there'd be an additional `before` param that could be used in conjunction with `after` to paginate through past releases.

There doesn't appear to be a git repo for this API so opening the issue here.

**Comment by yermulnik** [comment]
Doubling what @Jukie said. The introduction of Hashicorp Releases API was a great news, though UX appeared to be overshadowed by weird behavior of `List releases` functionality.

**Comment by mdeggies** [comment]
Hey everyone, Thanks for the report. We're currently working on a pagination fix that will resolve this, and will have it rolled out before the end of the week. We'll post here with an update once we have one.

**Comment by Jukie** [comment]
Thanks @mdeggies for the update!

**Comment by apparentlymart** [comment]
We don't really have any precedent for releases-service-related bug reports coming in through this repository so I don't really know how to label this, but in the interests of at least acknowledging it I've added our "confirmed" label instead of "new" to indicate that this is an active bug.

This seems like as good a place as any to track this for now, but I just wanted to be explicit here that there isn't a change to be made in _this_ repository to address the problem described, and so this issue isn't really participating in [our usual bug process](https://github.com/hashicorp/terraform/blob/main/BUGPROCESS.md); we'll leave this open for @mdeggies to share updates. Thanks!

**Comment by dikhan** [comment]
Hey folks, apologies for posting this here but figured it was sort of related...I have recently noticed some terraform [integration tests](https://github.com/dikhan/terraform-provider-openapi/blob/master/tests/e2e/provider_plugin_configuration_test.go#L224) failing due to the following error:

````
cannot run Terraform provider tests: unexpected Content-Type: "application/vnd+hashicorp.releases-api.v0+json"
````

This started happening right after the release maintenance https://status.hashicorp.com/incidents/tkgjbsblmhkw

Happy to open another issue if appropriate.

**Comment by mdeggies** [comment]
@dikhan, the content-type header that is returned did change post-launch. There is a section in the blog post describing the change and what to expect: https://preview.hashicorp.com/blog/announcing-the-hashicorp-releases-api

**Comment by dikhan** [comment]
@mdeggies thanks, I was able to find the place in the terraform code that fails and noticed that there's been a new release that fixes that problem: https://github.com/hashicorp/hc-install/releases/tag/v0.3.2

**Comment by mdeggies** [comment]
@dikhan, ah yes! Thank you for linking to that. We just posted a note internally letting folks know to upgrade hc-install to latest to loop in those changes. 

@Jukie, the pagination fix was just rolled out in v0.1.1 of the API service. Please feel free to open a new issue if you run into any other issues, or have any feature requests for us. :D

**Comment by Jukie** [comment]
Thanks @mdeggies I can confirm it's working now. I'll close this issue but feel free to reopen if there's something left to track around the new API changes.

**Comment by yermulnik** [comment]
Out of interest: what is the rationale for maximum of 20 entries per each reply for the list releases API call?
IMHO it may end up with a common situation of API calls requesting `total number of releases / 20` chunks more often as opposite to an option allowing to request a maximum of e.g. 100 which decreases the number of API calls by 5 in this case.

**Comment by Jukie** [comment]
@mdeggies Somewhat related issue/PR I've opened - https://github.com/hashicorp/go-version/issues/94
Sorry to ping but that repo doesn't seem to be very active or monitored.
