### ISSUE TITLE
aws: new aws_instance causes ebs volume to redo

### ISSUE THREAD

**Issue by mzupan** [hashicorp/terraform#3104]
I have the following setup

```
resource "aws_instance" "graphite" {
  ami = "${lookup(var.ami-hvm-7, var.env)}"
  instance_type = "c3.large"
  key_name = "${lookup(var.key, var.env)}"
  vpc_security_group_ids = [
    "${aws_security_group.internal-default.id}",
    "${aws_security_group.internal-web.id}",
    "${aws_security_group.internal-graphite.id}",
  ]
  subnet_id = "${aws_subnet.mgmt.2.id}"
  iam_instance_profile = "${aws_iam_instance_profile.graphite.id}"

  tags {
    CostCenter = "web"
    Name = "WEB graphite.${var.env}"
    Roles = "graphite"
  }
  user_data = "graphite.${var.env}.urthecast.com"
  private_ip = "${lookup(var.vpc-subnet, var.env)}.2.30"
}


resource "aws_ebs_volume" "graphite" {
  availability_zone = "${aws_instance.graphite.availability_zone}"
  size = 1000
  type = "io1"
  iops = "8000"
}

resource "aws_volume_attachment" "graphite-storage" {
  device_name = "/dev/xvdr"
  volume_id = "${aws_ebs_volume.graphite.id}"
  instance_id = "${aws_instance.graphite.id}"
}
```

If i try to change the AMI a `terraform plan` shows this

```
-/+ aws_ebs_volume.graphite
    availability_zone: "us-east-1d" => "${aws_instance.graphite.availability_zone}" (forces new resource)
    encrypted:         "false" => "<computed>"
    iops:              "8000" => "8000"
    kms_key_id:        "" => "<computed>"
    size:              "1000" => "1000"
    snapshot_id:       "" => "<computed>"
    type:              "io1" => "io1"

-/+ aws_instance.graphite
    ami:                               "ami-c96d82a2" => "ami-d1fc42ba" (forces new resource)
    availability_zone:                 "us-east-1d" => "<computed>"
    ebs_block_device.#:                "2" => "<computed>"
    ephemeral_block_device.#:          "0" => "<computed>"
```

the instance it's destroying is currently un us-east-1d

Forgot to mention I'm using the latest

```
Terraform v0.6.3
```

**Comment by bloopletech** [comment]
Looking at your config, your EBS volume AZ is dependent on your instance's AZ. When you change the AMI the instance is based on, terraform terminates the instance and then creates it again. AFAIK EC2 doesn't guarantee that an instance will be launched into the same AZ it was previously launched in.

I'm guessing that when terraform creates the instance again, EC2 puts it in a different AZ. Since the instances AZ has changed, the EBS volume's AZ also changes (because you linked them), and I think terraform will destroy the volume in the old AZ and then create it in the new AZ; as there is no way to 'move' an EBS volume between AZ's AFAIK.

You can either restrict your instance to a particular AZ, or restrict your EBS volume to a particular AZ; otherwise I'm not sure what you want to happen here.

(Not a project member, just an interested passerby).

**Comment by phinze** [comment]
I believe @bloopletech's explanation is correct - thanks @bloopletech!

Closing for now - feel free to follow up if your issue remains, @mzupan.
