### ISSUE TITLE
Drift detection does not take targeting into account when decoding state

### ISSUE THREAD

**Issue by zalent** [hashicorp/terraform#31052]
terraform targeting is not working starting 1.1.0 When i try to target a small subset of resources, it fails with or similar error witrh other resource.
```
 Error: Failed to decode resource from state
│ 
│ Error decoding "module.do2.module.rmq2.vsphere_virtual_machine.linux" from previous state: unsupported attribute "name"
```

however with 1.0.11 it works fine. 
also if i run  `terraform plan`  using latest version of terraform without targeting it also calculates plan without problems.

### Terraform Version
```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.1.1

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Expected Behavior
terraform calculates plan for selected subset of resources

### Actual Behavior
terraform tries to decode other resources and fails

### Steps to Reproduce

1. `terraform init`
2. `terraform plan --target=module.do3`

**Comment by jbardin** [comment]
Hi @zalent,

Thanks for filing the issue! Just to confirm, does the plan work correctly without the `-target` flag? Have you applied the entire configuration since upgrading the `vsphere` provider?

Is it possible to supply an example of the configuration used here? The error looks like it's implying `module.do2.module.rmq2.vsphere_virtual_machine.linux` should have been included in the target since it is required to evaluate the remaining resources, but we need to see how the configuration is structured to know for certain.

**Comment by jbardin** [comment]
Yes, applying the configuration as a whole would definitely allow all the resource to be properly upgraded to the new provider. I do think that `-target` should still be able to work here, so if you have any information, or can provide the trace logs from the failed plan, that would be great! This may be another case of #30745 too, which we still have not found a reproduction for.

**Comment by zalent** [comment]
same happened with azurerm provider when upgrading, tried targeting and same error occured.

**Comment by wadexu007** [comment]
same happened with gcp provider when upgrading, tried targeting and same error occured.

**Comment by Sohaib112** [comment]
The same just happened to me. But it did work after I ran `terraform init --upgrade`

**Comment by jbardin** [comment]
@ajklotz, I plan to have a PR for an upcoming patch to help address the problem. I would suggest however you work towards getting the infrastructure and configuration in a state such that you can apply a plan to all resources without the use of `-target`, at least so that the state can be updated when needed to account for CLI and provider upgrades.

**Comment by jbardin** [comment]
@ajklotz, The plan will be applied normally. The errors are from decoding the "objects changed outside of Terraform" report, which is not used during apply.
