### ISSUE TITLE
Error destroying resources due to cycles???

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#31050]
```
Error: Cycle: module.app.aws_security_group.security-group (destroy deposed 4e68ef66), module.app.aws_iam_instance_profile.iam-instance-profile (destroy deposed fab71567), null_resource.admin-provision (destroy deposed dd4ce9b3), module.app.aws_instance.instance (destroy)
```

Why does it check for cycles in objects for destruction???

### Terraform Version

```
Terraform v1.1.9
on linux_amd64
```

The mentioned objects were changed or removed from the configuration and should be deleted. But TF found some cycles and fails to apply changes.

```
  # module.app.aws_instance.instance will be destroyed
  # (because aws_instance.instance is not in configuration)


  # module.app.aws_security_group.security-group must be replaced
+/- resource "aws_security_group" "security-group" {


  # module.app.aws_iam_instance_profile.iam-instance-profile must be replaced
+/- resource "aws_iam_instance_profile" "iam-instance-profile" {

```

It should just delete these resources and don't check any cycles

**Comment by jbardin** [comment]
Hi @speller,

Resources being deleted have dependencies just like resources being created. While it's true that some resource types may be fine being removed in any order, others have dependencies that will cause them to fail when being removed in incorrect order.

If the configuration was altered such that there is a cycle between new and old instances, you may need to apply the configuration in multiple steps either separate remove the old instances, or update the dependencies before they are removed. If there was no change in configured dependencies then there could be a bug involved here, but we would need an example configuration to reproduce the issue in order to confirm.

Thanks!

**Comment by speller** [comment]
@jbardin How can I send you the state file securely without exposing it to the public?

**Comment by jbardin** [comment]
@speller, you can use KeyBase to send it to me (or just get my public key from their site), or the HashiCorp public key is posted at https://www.hashicorp.com/security.

**Comment by jbardin** [comment]
Hello,

Since we have not heard back with more information, I'm going to close this out. It is a known rough edge when a user introduces cycles between the configuration and state, and troubleshooting these are something we would like to improve. If you have more questions, fell free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
