### ISSUE TITLE
Extra attributes in TF lock Info object

### ISSUE THREAD

**Issue by bhaskarbalusani** [hashicorp/terraform#31053]
Hi,

I am using Terraform version 1.0.11.
I am using s3 and Dynamodb backend to store the lock information.

Currently, the TF lock info looks like this.
{
“LockID”: “balub-ps-tfstatebucket-2tyjg2wjrlkl/clusters/b87037d3-462c-4a8c-8392-e2f377adc14f/q7c28f12-039d-4fb6-b2ba-26e54948ac2b-md5”,
“Digest”: “ac56a5b8e8be1b024cbce9d306eef612”
}

But is there a way to add a new attribute specific to my own deployment in the dynamodb object?

{
“LockID”: “balub-ps-tfstatebucket-2tyjg2wjrlkl/networks/9c1ef159-3ad9-4235-a28a-4a3973216e70/yf051c43-7e8a-4ec0-9c59-c1b0bc78b858-md5”,
“Digest”: “1f3384180709639a4f1717c15135ed45”,
“DeploymentID” : “1234567575”
}

Is there a way to achieve this?

**Comment by jbardin** [comment]
Hi @bhaskarbalusani,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

The lock information stored in DynamoDB is an implementation detail of the AWS remote state, and is not a public interface and subject to change -- in fact it's possible that it may go away entirely in the future. Locking around Terraform CLI operations must abide by a minimal feature set that all remote state storage implementations can match, so must inherently be fairly simple. More fine grained locking behaviors and metadata storage required in complex workflows need to be orchestrated outside of the Terraform CLI.

Thanks!
