### ISSUE TITLE
Quote-escaping in `output`

### ISSUE THREAD

**Issue by EvanCarroll** [hashicorp/terraform#31051]
When outputting stuff at the end of `terraform apply`, all the variables in my output block display to the user on the terminal,

```terraform
output "ssh" {
  value = {
    ssh_web = "kitty +kitten ssh ${var.account}@${data.aws_eip.web.public_dns}$"
    ssh_db = "kitty +kitten ssh -J ${var.account}@${data.aws_eip.web.public_dns} ${var.account}@${aws_instance.db.private_dns}"
  }
}
```

The above works fine, but to be safe if I want to double quote things like this,

```terraform
output "ssh" {
  value = {
    ssh_web = "kitty +kitten ssh \"${var.account}@${data.aws_eip.web.public_dns}\""
    ssh_db = "kitty +kitten ssh -J \"${var.account}@${data.aws_eip.web.public_dns} ${var.account}@${aws_instance.db.private_dns}\""
  }
}
```

The actually escaped quote `\"` is rendered literally like `\"`. It would be nice to automatically escape these (rather than rendering the escape) in `terraform apply`. This question is inspired by [this post on stackoverflow](https://stackoverflow.com/questions/67428547/escaping-quotes-in-output-string-in-terraform/67429503#67429503), where they've got the same issue I'm having

**Comment by jbardin** [comment]
Hi @EvanCarroll,

The CLI output is a quoted string, so it would be incorrect to not escape the internal quotes. For simple primitive values you can use the `-raw` option to show the unquoted values, and for machine processing there is a `-json` flag as well.

See also #27100, #27007, and #27007

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by EvanCarroll** [comment]
It's not a question. This behavior is unintuitive. That's why it's generating tickets, and many questions on StackOverflow. I obviously understand what it's doing.

* If I have an option to "output something"
* And, if I have to quote values to construct strings in HCL. `"foo"`
* But I would like the ability to create a string which itself contains itself a quote mark `foo "bar" baz` (not HCL)
* The only option that HCL offers for creating a string with a quote, it to escape the quote. `"foo \"bar\" baz"` (HCL).
* But then `output` does not output the "quote" as I want `foo "bar" baz` it outputs the HCL-escaping of the quote `"foo \"bar\" baz"` (HCL).

`-raw` doesn't change this.

**Comment by EvanCarroll** [comment]
@jbardin Here is a suggestion for a solution. Consider my use case above. I want to output commands that correspond to the resource the cluster is provisioning. What I _want_ is the ability to put those commands after the run so I can copy-pasta them into my terminal.

```text
output "test" {
  value = {
		foo = "foo \"bar\" baz"
		bar = "foo \"bar\" baz"
	}
}
```

When I run this under `terraform apply` I get 

```
test = {
  "bar" = "foo \"bar\" baz"
  "foo" = "foo \"bar\" baz"
}
```

I simply want _any_ solution that allows `terraform apply` to produce output I can copy.

My suggestion would be something like this (keep in mind I'm new).

```
terraform {
  output = {
    quote = "$$"
  }
}
```

Which produces this (jacked this idea from postgres),

```
test = {
  "bar" = $$foo "bar" baz$$
  "foo" = $$foo "bar" baz$$
}
```

Other ideas,

```
terraform {
  output = {
    external_quote = false
  }
}
```

It's no longer valid HDL output, but outputting HDL isn't useful to me. This just interpolates the backslash escapes

```
test = {
  "bar" = foo "bar" baz
  "foo" = foo "bar" baz
}
```

I'll stop suggesting pseudo configurations. But this works too (`.env`) style,

```
test.bar=foo "bar" baz
test.foo=foo "bar" baz
```

I mean, I can think of thousand different rendering formats but ultimately I think users just want the ability to print. ;)

**Comment by jbardin** [comment]
Thanks for the examples @EvanCarroll. I think the main problem here is that none of these formats make sense within the context of an object, which is what the output is defined as. The actual value we need to show is an object with `foo` and `bar` attributes and string values.

```
{
  "bar" = "foo \"bar\" baz"
  "foo" = "foo \"bar\" baz"
}
```

We can't arbitrarily omit the object, since outputs may contain other things that aren't objects, making the distinction ambiguous. If these values are not intended to be consumes as part of a single object, then assigning them to individual outputs as strings will allow the use of `-raw`, and get the desired result.

There's also no single format which can please everyone. Any of these _could_ work in some sense, but they also all have shortcomings, fail to be unambiguous with certain values, or present yet another syntax for users to discover. Since as you say there are a thousand different possible renderings, we have settled on the the syntax matching the configuration for the default output, and structured json when you want to mechanically consume or transform the output.

Converting your example using structured output to unquoted strings might be done like so:

```
% terraform output -json test | jq -r '.[]'
foo "bar" baz
foo "bar" baz
```

Or if you want to retain the keys in the env-like syntax:
```
% terraform output -json test | jq -r 'to_entries[] | [.key, .value] | join("=")'
bar=foo "bar" baz
foo=foo "bar" baz
```

**Comment by EvanCarroll** [comment]
And parsing JSON with `jq` seems to be what people are doing right now. I'm just saying that's not what they _want_. They want the ability to print a diagnostic or report on the conclusion of `terraform apply`. 

This is how Ansible does it for reference,

```
- name: Prints two lines of messages, but only if there is an environment value set
  ansible.builtin.debug:
    msg:
    - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"
    - "These servers were built using the password of '{{ password_used }}'. Please retain this for later use."
```

That's from [their docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html).

Sure people can use jq and parse the output of the tfstate or `output` directives, but that's adding a dependency for external tooling to do some pretty basic stuff.

**Comment by jbardin** [comment]
The ansible example is for simgle string values, and is roughly equivalent to a string typed output value with `-raw`. These values can already be individually defined as outputs, or combined in a formatted string within the terraform config, e.g:

```
locals {
  test = {
    foo = "foo \"bar\" baz"
    bar = "foo \"bar\" baz"
  }
}

output "test" {
  value = join("\n", [for k, v in local.test : "${k}=${v}"])
}
```

```
% terraform output -raw test
bar=foo "bar" baz
foo=foo "bar" baz
```
