### ISSUE TITLE
Missing feature documentation: precondition and postcondition check blocks

### ISSUE THREAD

**Issue by khaliddermoumi** [hashicorp/terraform#31079]
### Current Terraform Version

1.2.0

### Use-cases
There is a new release 1.2.0, from the release documentation:
```
NEW FEATURES:
precondition and postcondition check blocks for resources, data sources, and module output values: module authors can now document assumptions and assertions about configuration and state values. If these conditions are not met, Terraform will report a custom error message to the user and halt further execution.
```
Earlier RC release also mentioned this feature. 
The problem: there seems to be no adequate documentation for it, or at least it cannot be found.

### Attempted Solutions
1. Searching Terraform docs
2. Searching the web with search engine
Result: no relevant hit

### Proposal
Add the documentation, or move it to a relevant place so it can be found.

**Comment by apparentlymart** [comment]
Hi @khaliddermoumi,

Can you say more about what you tried in order to find it? I can see that the text search index on the website doesn't seem to have it indexed yet, which is certainly a good problem to fix and I'll pass that on to the website team, but if you had some other expectation for where to find the documentation then I'd like to try to make that work too.

In the meantime, though: you can find all of the different checking features together on the page [Custom Conditions](https://www.terraform.io/language/expressions/custom-conditions).

**Comment by apparentlymart** [comment]
Hi again @khaliddermoumi!

The search index is now updated. It looks like there was an error during the website deploy yesterday, so I reran it and this time the index rebuilt successfully. Sorry for the oversight, and thanks for reporting this!
