### ISSUE TITLE
Error: Failed to install provider

### ISSUE THREAD

**Issue by Jinbingchen** [hashicorp/terraform#31080]
Hello, I suddenly encountered an error when i use the command "terraform init", the error description is as follows：

_Error: Failed to install provider

Error while installing hashicorp/oci v4.76.0: could not query provider registry for registry.terraform.io/hashicorp/oci: registry response includes invalid SHA256 hash "": %!s(<nil>)_

I did nothing while this error occured and I just don't know how to fix it.

**Comment by jbardin** [comment]
Hi @Jinbingchen,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

I'm not sure how you could have encountered this with no prior changes, but the [`oci` provider](https://registry.terraform.io/providers/oracle/oci/latest) is under the oracle namespace, not hashicorp. The usual cause for this would be an `oci` resource in the configuration with no associated provider  defined in `required_providers` resulting in Terraform using the default `hashicorp/` namespace.

If this is not the case, please feel free to start a thread in the forums, and others can try and help troubleshoot what may have gone wrong.

Thanks!

**Comment by jbardin** [comment]
Hi @Jinbingchen,

Following up to check if the registry should have ben reporting a different error here, but I forgot the `oci` provider has a special case where it's available via both the `hashicorp/` and `oracle/` namespaces. Since that's the case, you may have just been countering a transient issue with the registry service.

**Comment by Jinbingchen** [comment]
Hi @jbardin :

Thanks for you reply. I solved this problem by using hashicorp/oci v4.75.0 ,as shown in the picture, instead of v4.76.0 (the latest one). It seems that there is some bug in this version stop me from download this latest provider.

![image](https://user-images.githubusercontent.com/22073265/169432140-1e537f6c-8705-455b-b04b-a5bb1c5234d5.png)
