### ISSUE TITLE
Unable to delete the custom domain

### ISSUE THREAD

**Issue by manfrednde** [hashicorp/terraform#31108]
We are not able to destroy a custom domain as we are experiencing the following error during deletion.
```
 Error: deleting "Custom Domain: (Name \"cdn-endpoint-custom-domain\" / Endpoint Name \"xxxxresourcescigky1fd\" / Profile Name \"xxxxresourcescigky1fd\" / Resource Group \"xxxxcigky1fd\")": cdn.CustomDomainsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="Cannot delete custom domain \"cdn-xxxx.com\" because it is still directly or indirectly (using \"cdnverify\" prefix) CNAMEd to CDN endpoint \"xxxxresourcescigky1fd.azureedge.net\". Please remove the DNS CNAME record and try again."
```
We disabled Check For Custom Domain Deletion using the following command but still getting the same error.
az feature register --namespace Microsoft.Network --name BypassCnameCheckForCustomDomainDeletion

Any assistance is appreciated.

**Comment by apparentlymart** [comment]
Hi @manfrednde!

This seems to be a question about a particular provider rather than a bug report about Terraform Core, so I suggest starting a topic about it in the relevant subcategory of [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers/31).

We use issues in this repository only for bug reports and feature requests to the provider-agnostic Terraform Core behaviors, so we can't help with provider-specific problems here and thus I'm going to close this. Thanks!
