### ISSUE TITLE
aws_elasticache_cluster not waiting on aws_elasticache_subnet_group

### ISSUE THREAD

**Issue by rbowlby** [hashicorp/terraform#3115]
It appears that the aws_elasticache_cluster resource is not properly ordered after the aws_elasticache_subnet_group.

I have to run apply twice when creating an elasticache cluster with a specific subnet_group.

Here's an example snippet from a module I have:

```
resource "aws_elasticache_cluster" "upload" {
    cluster_id = "upload-${var.environment}"
    engine = "redis"
    node_type = "${var.cache_node_type}"
    port = 6379
    num_cache_nodes = "${var.num_cache_nodes}"
    parameter_group_name = "upload-${var.environment}-28"
    subnet_group_name = "upload-${var.environment}-cache-subnet"
}

resource "aws_elasticache_parameter_group" "upload" {
    name = "upload-${var.environment}-28"
    family = "redis2.8"
    description = "Cache cluster param group for upload in ${var.environment}"

    parameter {
        name = "reserved-memory"
        value = "0"
    }

    parameter {
        name = "zset-max-ziplist-entries"
        value = "128"
    }

    parameter {
        name = "zset-max-ziplist-value"
        value = "64"
    }
}

resource "aws_elasticache_subnet_group" "upload" {
    name = "upload-${var.environment}-cache-subnet"
    description = "Upload elasticache subnet group for ${var.environment}"
    subnet_ids = ["${split(",", var.subnets)}"]
}
```

**Comment by artworklv** [comment]
Same issue here.
Also, It does not destroy properly aws_elasticache_cluster if aws_elasticache_subnet_group is defined before the cluster. The error is  
`aws_elasticache_subnet_group.redis: CacheSubnetGroupInUse: Cache subnet group foobar is currently in use by a cache cluster.`

**Comment by zoltrain** [comment]
I've just run into this one too. Might be a eventual consistency issue with the AWS API?

**Comment by infonaut** [comment]
When the Cache Subnet Group is created by Terraform it becomes instantly visible from the AWS console. However whilst trying to create the Elasticache Cluster. Terraform errors with the 'Cache Subnet Group xxx does not exist." messsage.

This could be an internal consitency issue with AWS but it seems odd that the group is visible to the console but not an internal API.

The reverse is true when attempting to destroy the configuration.

This is not an ordering issue as the Subnet creation call is made before the Cluster creation call.

**Comment by catsby** [comment]
Hello Friends –

I apologize for the delay in response here. 

The core issue here is how the Terraform graph works using the reference of other resource names/ids, in order to determine their relationship. To build the graph of dependencies, Terraform relies on the configuration referencing other resources.

From the above example:

```hcl
resource "aws_elasticache_cluster" "upload" {
    cluster_id = "upload-${var.environment}"
    [...]
    subnet_group_name = "upload-${var.environment}-cache-subnet"
}

resource "aws_elasticache_subnet_group" "upload" {
    name = "upload-${var.environment}-cache-subnet"
    [...]
}
```

Both of these resources depend on the `environment` variable. However, **they do not depend on each other**. The value of `subnet_group_name` in the Cluster, and `name` in the Subnet group, will evaluate to the same value, however, there's no _connection_ between the two. The same goes for `parameter_group_name`. The example config above produces a  dependency graph like so:

![no_deps](https://cloud.githubusercontent.com/assets/61721/14147483/5fe11394-f661-11e5-90e5-18dc750cc2d6.png)

You can see there is no connection between the Subnet(s) and the ElastiCache cluster. The `subnet_group_name` of the cluster evaluates to the same name as the Subnet group, but there is no connection made. Terraform doesn't know that one needs to come before the other. 

In order to construct them so that Terraform builds the correct graph, you need to reference them like so:

```hcl
resource "aws_elasticache_cluster" "upload" {
    cluster_id = "upload-${var.environment}"
    [...]
    subnet_group_name = "${aws_elasticache_subnet_group.upload.name}"
}

resource "aws_elasticache_subnet_group" "upload" {
    name = "upload-${var.environment}-cache-subnet"
    [...]
}
```

by referencing the **resource** name directly, instead of constructing the same name individually, you create the dependency. Terraform knows to create the Subnet group first, in order to create the Cluster. The graph then looks like this:

![deps](https://cloud.githubusercontent.com/assets/61721/14147561/a3f3bc30-f661-11e5-8457-c1ecde000e18.png)

Sadly, I'm sure this reply reaches you too little too late, and I apologize for that. Hopefully it will be helpful to others in the future.
