### ISSUE TITLE
lookup not functioning in locals - terraform version 1.2.1, but hasn't been working for a while

### ISSUE THREAD

**Issue by scotttyso** [hashicorp/terraform#31161]
### Terraform Version

```
Terraform v1.2.1
```

### Terraform Configuration Files

auto.tfvars file
```terraform
tacacs = {
  "RICH" = {
    server_monitoring = [
      {
        admin_state = "diabled"
      }
    ]
    timeout           = 5
  }
}
```

Variable File
```terraform
variable "tacacs" {
  default = {
      server_monitoring = [
        {
          admin_state = "disabled"
          password    = 0
          username    = "admin"
        }
      ]
    }
  }
  type = map(object(
    {
      server_monitoring = optional(list(object(
        {
          admin_state = optional(string)
          password    = optional(number)
          username    = optional(string)
        }
      )))
  ))
}

```

locals
```terraform
locals {
  tacacs = {
    for k, v in var.tacacs :  k => {
      server_monitoring      = v.server_monitoring != null ? lookup(v.server_monitoring[0], "admin_state", "disabled") : "disabled"
      password               = v.server_monitoring != null ? lookup(v.server_monitoring[0], "password", 0) : 0
      username               = v.server_monitoring != null ? lookup(v.server_monitoring[0], "username", "admin") : "admin"
    }
  }
}
```

output for testing
```terraform
output "tacacs_hosts" {
  value = local.tacacs_hosts
}
```

From a Plan
```terraform
Changes to Outputs:
  + tacacs_hosts           = {
      + "RICH" = {
          + password               = null
          + server_monitoring      = "diabled"
          + username               = null
        }
    }
```

This should have retruned 0 and admin from the locals lookup based on what I read from the reference here

function_lookup: <https://www.terraform.io/language/functions/lookup>

### Expected Behavior

The Lookup should have worked
### Actual Behavior

The lookup did not work

**Comment by apparentlymart** [comment]
Hi @scotttyso,

The `lookup` function is intended for conditionally accessing elements of a map, to deal with the situation where a particular key isn't present at all.

In your case you have an object type which has three attributes, and so those attributes are always present but (due to being optional) may be set to `null`. The `lookup` function therefore isn't appropriate for this situation, and you should instead use [`coalesce`](https://www.terraform.io/language/functions/coalesce) which is designed for providing a fallback value when a value is `null`:

```hcl
coalesce(v.server_monitoring[0].admin_state, "disabled")
```

In the above example, `v.server_monitoring[0].admin_state` will always be valid because `admin_state` is defined as part of your object type constraint, but it can potentially have the value `null` due to the fact that you declared it as optional. In the case where it's null, `coalesce` will return `"disabled"` instead.

Given this, I think Terraform is working as designed here: given the value `{ admin_state = null }`, the `lookup` function will find that `admin_state` does exist and therefore return its value, which is `null`.

I do understand though that due to how Terraform typically makes it easy to use object values in places where maps are expected and vice-versa it was therefore surprising for Terraform to treat object types a little differently here. I think we could improve this by adding a note to [the `lookup` documentation](https://www.terraform.io/language/functions/lookup) to be explicit that it considers an element/attribute with the value `null` as being present rather than absent, and to suggest using `coalesce` instead to provide a fallback for a `null`.

**Comment by kitarp29** [comment]
Hi @apparentlymart I would like to work on it.
Could you help me to get started with this?

**Comment by scotttyso** [comment]
Thank you @apparentlymart .  I have switched to coalesce which works for my use case.  Thank you for the clarification.
