### ISSUE TITLE
no getter available for X-Terraform-Get source protocol

### ISSUE THREAD

**Issue by jbgraindorge-pubfac** [hashicorp/terraform#31186]
### Terraform Version

```
Terraform v1.2.2
```

### Terraform Configuration Files
```terraform
module "cloudfront" {
  source = "https://api.example.com/module"
  [...]
}
```

### Expected Behavior
```terraform
Downloading https://api.example.com/module cloudfront...
- cloudfront in .terraform/modules/cloudfront
```

### Actual Behavior
```terraform
Could not download module "cloudfront" (cloudfront.tf:1) source code from
│ "https://api.example.com/module": error
│ downloading 'https://api.example.com/module':
│ no getter available for X-Terraform-Get source protocol:
│ "github.com/terraform-aws-modules/terraform-aws-cloudfront?ref=v2.9.3"
```

### Steps to Reproduce
```terraform
terraform init
```

### Additional Context
We are using custom API to return modules locations and versions, it is working fine with terraform 1.2.1 but it is not working anymore with terraform 1.2.2

**Comment by jbgraindorge-pubfac** [comment]
I also opened a report in https://github.com/hashicorp/go-getter/issues/368

**Comment by jbardin** [comment]
Hi @jbgraindorge-pubfac,

Thanks for reporting the issue! Some security fixes upstream have caused the `X-Terraform-Get` response in your module registry API to get rejected to protect from unexpected protocol switching. This was not expected, but if you are in a position to work around it, the problem is triggered by your `X-Terraform-Get` not having an explicit protocol. Returning a complete URL starting with `git::https://` should get it working for now.

Thanks!
