### ISSUE TITLE
Apply now reports the -out flag is not defined

### ISSUE THREAD

**Issue by neilmca-inc** [hashicorp/terraform#31203]
### Terraform Version

```
1.2.2
```

### Terraform Configuration Files

```
First command works here...
terraform plan -var-file=qa01.tfvars -out=TerraformSandbox-ResourceGroup.qa01.20220608.3-main.tfplan
Second command doesn't...
terraform apply -auto-approve -var-file=qa01.tfvars -out=TerraformSandbox-ResourceGroup.qa01.20220608.3-main.tfplan
```

### Debug Output

Error from the second command - the apply

```
╷
│ Error: Failed to parse command-line flags
│ 
│ flag provided but not defined: -out
╵

```

### Expected Behavior

Should work as specified here
https://www.terraform.io/cli/commands/apply#:~:text=All%20planning%20modes%20and%20planning%20options%20for%20terraform%20plan%20%2D%20Customize%20how%20Terraform%20will%20create%20the%20plan.%20Only%20available%20when%20you%20run%20terraform%20apply%20without%20a%20saved%20plan%20file.

I'm pretty sure this used to work before. If it has been removed then the documentation needs clarification

### Steps to Reproduce

Use any Terraform Apply step with the -out switch e.g. 

`terraform apply -auto-approve -var-file=my.tfvars -out=my.tfplan`

### Additional Context

Using the Ubuntu 64 bit version

**Comment by jbardin** [comment]
Hi @neilmca-inc,

The `-out` flag is not an option for the `apply` command -- in the linked documentation page`-out` is shown being used with the `plan` command to generate a plan file. If you want to generate a plan for use or inspection later, then you must use `terraform plan` to do so.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
