### ISSUE TITLE
Difficulties in publishing Terraform provider

### ISSUE THREAD

**Issue by inviul** [hashicorp/terraform#31214]
My new terraform provider is released successful.

When I try to publish my provider, it’s taking longer time in buffering, and an yellow notification strip is appearing which is stating - Could not find all platform assets…missing release asset for…

I have attached the screenshot.

Provider name: terraform-provider-inviulrestap

![image](https://user-images.githubusercontent.com/28164616/172745496-00f673c9-e7a4-48b8-b18d-893431efae78.png)

**Comment by apparentlymart** [comment]
Hi @inviul!

I think you asked the same question in [a community forum post](https://discuss.hashicorp.com/t/difficulties-in-publishing-a-new-terraform-provider/40561/2), where I already responded. The registry team is already aware of that forum post (I talked with them before I responded to you) and so I'm going to close this issue just to keep the discussion consolidated in the forum. Issues in this repository are typically about the code that's included in the Terraform CLI executable, rather than about other components like Terraform Registry.

Thanks!
