### ISSUE TITLE
Add support for golang 1.18 

### ISSUE THREAD

**Issue by TomerHeber** [hashicorp/terraform#31221]
### Current Terraform Version
```
N/A
```

### Use-cases
I would like to run terraform on a docker image with golang 1.18 (for building code with generics).

### Proposal
The docker (and also go.mod) run in go 1.17.
Change the docker image to use go 1.18 (and consider upgrading go.mod from 1.17 to 1.18).

### References
https://go.dev/doc/tutorial/generics
https://go.dev/blog/go1.18

**Comment by apparentlymart** [comment]
Hi @TomerHeber,

Our official release Docker images, assuming that is what you are referring to, are only intended for running the Terraform executable bundled inside them, and not for any other purpose. Terraform itself is not yet using any Go 1.18 features, and so therefore providing a Go 1.18 toolchain is not yet necessary and therefore not a current priority. I expect that we will start using Go 1.18 at some point, but that will be driven by planned feature development rather than by supporting external use-cases like you are describing. Therefore I can't promise to do it at any particular time.

If you are intending to make use of Terraform as part a larger solution with other software, I would suggest building your own Docker images so that you can customize exactly what software is present. The Terraform CLI executables for Linux available in [the primary release packages](https://releases.hashicorp.com/terraform) are statically-compiled executables ready to be copied into any image with no other dependencies, as long as you are running Docker on a suitably new Linux kernel.

Thanks!
