### ISSUE TITLE
Terraform treats # as comment in a string 

### ISSUE THREAD

**Issue by Anu-BakingCode** [hashicorp/terraform#31230]
Use Case - Create a document_id in firestore with name "purposes#but-news"

Code 
```resource "google_firestore_document" "firestore" {
  project     = var.project
  collection  = "collection"
  document_id = "purposes#but-news"
  fields      = file("${var.env}-config.json")
}

```
Problem Statement : Terraform creates the document with id name "purposes" . It just skips the string **#but-news**

I tried \  to escape the # character  , but it throws an error

> The symbol "#" is not a valid escape sequence selector

I also tried few things like % , // , join function , EOT  to escape the # character but still No luck. But it is working for other ASCII character like @,&,1 etc except #

**Comment by jbardin** [comment]
Hi @Anu-BakingCode,

Sorry you're having trouble with this. Terraform is not treating the `#` as a comment, since if it was you would have an unclosed string which would be a syntax error. You can also see that it is executing, since you state that a resource is created, just not with the data you expect. 

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
