### ISSUE TITLE
Terraform doesn't obey conditional git config for github ssh

### ISSUE THREAD

**Issue by georgekosmidis** [hashicorp/terraform#31255]
Cloning an enterprise github repo with ssh that is  part of a conditional config ends with `git@github.com: Permission denied (publickey)`.

##Git config - main
```
[includeIf "gitdir/i:C:/XXX/Repos/"]
    path = C:\\XXX\\.gitconfig
```

##Git config - C:\\XXX\\.gitconfig
```
[core]
sshCommand = "ssh -i c:\\\\XXX\\\\.ssh\\\\XXX.pkey"
```

### Running git pull works correctly:
```
> git pull
Enter passphrase for key 'c:\XXX\pkey':xxxxxx
...pulling... 
```

### Running terraform init:
```
Downloading git::ssh://git@github.com/XXXXXX?ref=v1.0.0 for tags...
╷
│ Error: Failed to download module
│
│ Could not download module "X" (tags.tf:1) source code from "git::ssh://git@github.com/XXXXX.git":      
│ error downloading 'ssh://git@github.com/XXXXX': C:\Program Files\Git\cmd\git.exe exited with 128:     
│ Cloning into '.terraform\modules\X'...
│ git@github.com: Permission denied (publickey).
│ fatal: Could not read from remote repository.
│
│ Please make sure you have the correct access rights
│ and the repository exists.
```
### Terraform Version
Terraform v1.2.3
on windows_amd64

### Steps to Reproduce
1. Setup gitconfig with conditionally load the a config from a specific path
2. Setup the conditional gitconfig with the key file
3. Run `terraform init`

### References
- https://github.com/hashicorp/terraform/issues/18541
- https://github.com/hashicorp/terraform/issues/18869
- https://github.com/hashicorp/terraform/issues/19232
- https://github.com/hashicorp/go-getter/pull/124

### Additional Info
I ve tried the ssh config file and it works, but this way I have only one key for all github projects. 
SSH config that worked:
```
Host github.com
   HostName github.com
   PreferredAuthentications publickey
   IdentityFile ~/.ssh/id_rsa_hub
```

**Comment by apparentlymart** [comment]
Hi @georgekosmidis! Sorry for this surprising behavior, and thanks for reporting it.

Terraform _is_ internally running normal Git commands here, and so it should work in principle, but I wonder if there's something about exactly how Terraform is running Git that is making this work differently than the simple `git pull` you tried.

Perhaps if you can try a command more like the one Terraform would be running we can see if it's possible to reproduce the problem in a way that might be easier to debug, because Terraform CLI won't be "in the way" making it hard to see what exactly is going on.

Terraform delegates the problem of installing from remote module sources to an upstream library called `go-getter`, which has [some tricky logic for building the Git command line](https://github.com/hashicorp/go-getter/blob/ef2fcc6c2f8ee034f76b3c25cd0bce26155f1e08/get_git.go#L192-L229), due to an accumulation of different use-cases and odd situations over the years.

However, we can see that your source address doesn't include the `depth` argument and _does_ include the `ref` argument, and I can eliminate a few conditional branches from consideration. Therefore I _think_ Terraform would be running something like the following, taking your partially-redacted source address string at face value:

```
git clone ssh://git@github.com/XXXXXX .terraform\modules\X
```

Can you try a command like that, substituting the real URL and the real destination directly, and see if you can reproduce a similar error message as what Terraform is encountering?

Note that Terraform cannot show interactive prompts during module installation, so if running the above command causes a similar `Enter passphrase for key 'c:\XXX\pkey'` prompt as you showed in your `git pull` example then I expect that's the root cause here: in order to use an SSH key for automatic installation with Terraform you'll need to load your key into an SSH Agent first, providing your passphrase at that point, and then let the OpenSSH process that Git runs read the key from that active agent.

**Comment by georgekosmidis** [comment]
Hi @apparentlymart, 
thanks for the answer, I think you got it!

Here is what I had to do to make things work in windows:
I had to set an environment variable:  `GIT_SSH_COMMAND = C:\\Windows\\System32\\OpenSSH\\ssh.exe` and change `C:\XXX\.gitconfig` to `sshCommand = "passphrase | ssh-add c:\\XXX\\key && ssh -i c:\\XXX\\key"`

Now I know it's wrong to actually have the passphrase in there, and I am planning to have the phrase as a Github secret, but I didn't yet had time to figure out a better approach for my local environment and since `.gitconfig` isn't part of the repo I decided to push forward with other stuff and return to this later.

Thank you!
