### ISSUE TITLE
There is no function named "defaults". in terraform 1.3 alpha

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#31282]
### Terraform Version

```
Terraform v1.3.0-alpha20220608
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.19.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/vault v3.7.0```
```
Initializing provider plugins...
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Finding hashicorp/kubernetes versions matching ">= 2.10.0, >= 2.11.0"...
- Finding latest version of hashicorp/local...
- Finding hashicorp/helm versions matching ">= 2.4.1, >= 2.5.1"...
- Finding hashicorp/aws versions matching ">= 3.72.0, >= 4.0.0, >= 4.10.0, >= 4.17.1, >= 4.19.0"...
- Finding latest version of hashicorp/random...
- Finding gavinbunney/kubectl versions matching ">= 1.13.1, >= 1.14.0"...
- Finding latest version of hashicorp/null...
- Finding hashicorp/cloudinit versions matching ">= 2.0.0"...
- Finding latest version of hashicorp/vault...
- Using previously-installed hashicorp/kubernetes v2.11.0
- Using previously-installed hashicorp/local v2.2.3
- Using previously-installed hashicorp/cloudinit v2.2.0
- Using previously-installed hashicorp/vault v3.7.0
- Using previously-installed hashicorp/time v0.7.2
- Using previously-installed hashicorp/aws v4.19.0
- Using previously-installed hashicorp/random v3.3.1
- Using previously-installed gavinbunney/kubectl v1.14.0
- Using previously-installed hashicorp/null v3.1.1
- Using previously-installed hashicorp/helm v2.6.0
```

### Terraform Configuration Files
<!--
Paste the relevant parts of your Terraform configuration between the ``` marks below.

For Terraform configs larger than a few resources, or that involve multiple files, please make a GitHub repository that we can clone, rather than copy-pasting multiple files in here. For security, you can also encrypt the files using our GPG public key at https://www.hashicorp.com/security.
-->

```terraform
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/ea0922f/modules/kubernetes-addons/helm-addon/locals.tf#L6
```

### Expected Behavior
works on tf v1.2.3

### Actual Behavior
```
╵
╷
│ Error: Call to unknown function
│
│   on .terraform/modules/base_system.karpenter.eks_blueprints_kubernetes_addons_karpenter.ondat.helm_addon/modules/kubernetes-addons/helm-addon/locals.tf line 6, in locals:
│    6:   irsa_config = defaults(var.irsa_config, {
│    7:     create_kubernetes_namespace       = true
│    8:     create_kubernetes_service_account = true
│    9:   })
│     ├────────────────
│     │ var.irsa_config is a object, known only after apply
│
│ There is no function named "defaults".
╵
╷
│ Error: Call to unknown function
│
│   on .terraform/modules/base_system.karpenter.eks_blueprints_kubernetes_addons_karpenter.tetrate_istio.base/modules/kubernetes-addons/helm-addon/locals.tf line 6, in locals:
│    6:   irsa_config = defaults(var.irsa_config, {
│    7:     create_kubernetes_namespace       = true
│    8:     create_kubernetes_service_account = true
│    9:     iam_role_path                     = "/"
│   10:   })
│     ├────────────────
│     │ var.irsa_config is a object, known only after apply
│
│ There is no function named "defaults".
╵
```

**Comment by apparentlymart** [comment]
Hi @FernandoMiguel!

That `defaults` function was part of the optional attributes experiment, and has been intentionally removed in the next phase of the experiment, which has (as of last week) been de-experimentalized and will be stable in the forthcoming v1.3.0.

Alpha releases don't really have their own changelogs because they are just snapshots from the main branch, but you can read more about it in the not-yet-release v1.3.0 section in [the main branch changelog](https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md#130-unreleased). (To anyone who finds this comment in the far future: that is a time-limited link that won't work forever, but similar content should eventually be in [the v1.3 changelog](https://github.com/hashicorp/terraform/blob/v1.3/CHANGELOG.md), once there is one.)

Since this was an intentional change, I'm going to close this issue. However, if you have feedback on the new design then those working on it would love to hear it in [the optional attributes feedback topic in the community forum](https://discuss.hashicorp.com/t/request-for-feedback-optional-object-type-attributes-with-defaults-in-v1-3-alpha/40550)! Thanks.
