### ISSUE TITLE
Data source postconditions using `timestamp()` do not reevaluate at apply time

### ISSUE THREAD

**Issue by alisdair** [hashicorp/terraform#31289]
### Terraform Version
```
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/http v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

### Terraform Configuration Files
```terraform
data "http" "example" {
  url = "https://registry.terraform.io/v1/modules/hashicorp/consul/aws"

  lifecycle {
    postcondition {
      condition     = (
        formatdate("YYYYMMDDhhmmss", jsondecode(self.response_body)["published_at"]) >
        formatdate("YYYYMMDDhhmmss", timestamp())
      )
      error_message = "Time travel experiment failed."
    }
    postcondition {
      condition     = (
        formatdate("YYYYMMDDhhmmss", jsondecode(self.response_body)["published_at"]) <=
        formatdate("YYYYMMDDhhmmss", timestamp())
      )
      error_message = "Time travel experiment succeeded!"
    }
  }
}

resource "null_resource" "example" {
  depends_on = [data.http.example]
}
```

### Expected Behavior

One of the two data source postconditions should have raised an error (which one depends on whether you're a time traveller or not).

### Actual Behavior

Apply succeeded:

```shellsession
$ terraform apply -auto-approve
data.http.example: Reading...
data.http.example: Read complete after 1s [id=https://registry.terraform.io/v1/modules/hashicorp/consul/aws]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.example will be created
  + resource "null_resource" "example" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.example: Creating...
null_resource.example: Creation complete after 0s [id=6866465537958634611]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -auto-approve`

### Additional Context
The postconditions blocks have an unknown result in a refresh-only plan, indicating that they are never reevaluated after the data source executes.

**Comment by apparentlymart** [comment]
This seems to have the same root cause as #31261, which has now been fixed and so this should work as intended in the v1.3.0 release.

The problem here is that Terraform was only re-evaluating the conditions for a particular resource instance during the apply phase if that instance happened to have a real change planned for it. The most common form of that problem meant that immediately re-running `terraform plan` would belatedly show the error that should've been detected during apply. This particular variant could not ever detect the problem on a subsequent run because every new run has a fresh value of `timestamp()` decided during apply, and so there's never any situation where the condition could produce a known result.

With the change in v1.3.0 Terraform will re-evaluate all of the conditions during the apply phase, regardless of whether there's any other changes planned for a particular resource instance. That means that Terraform can re-check the condition once `timestamp()` is returning a known result (the apply time of the resource instance) and raise an error if it fails.
