### ISSUE TITLE
Force string interpolation on data structure attributes

### ISSUE THREAD

**Issue by gchamon** [hashicorp/terraform#31287]
### Current Terraform Version

```
Terraform v1.2.2
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

When sourcing a file with datasource, if that file has string interpolations, they are not rendered even when using functions like yamldecode or jsondecode. This is interesting in cases where the infrastructure is centralized in a single terraform state, but resource attributes like policies are distributed, i.e. they are version controlled in repositories other than the one holding the terraform configuration files.

### Attempted Solutions

Given `configs.yml` is a file in a github repository with something like:

```yaml
account_id: ${data.aws_caller_identity.current.account_id}
environment: ${var.environment}
```

Chaining jsonencode jsondecode won't force interpolation :

```hcl
variable "environment" {
  default = "development"
}

data "aws_caller_identity" "current" {}

data "github_repository_file" "config_file" {
  repository = "example-repository"
  branch     = "main"
  file       = "configs.yml"
}

locals {
  rendered-config = yamldecode(data.github_repository_file.config_file.content)
  re-rendered-config = jsondecode(jsonencode(local.rendered-config))
}
```

Using `template_file` datasource, `data` and `var` are not recognized inside the template:

```hcl
variable "environment" {
  default = "development"
}

data "aws_caller_identity" "current" {}

data "github_repository_file" "config_file" {
  repository = "example-repository"
  branch     = "main"
  file       = "configs.yml"
}

data "template_file" "config_file" {
  template = data.github_repository_file.config_file.content
}
```

Which will output an error:

```
Error: failed to render : <template_file>:38,34-38: Unknown variable; There is no variable named "data"
```

Passing variables to the `template_file` datasource using the `vars` attribute is not feasible, given all namespaces could be accessed in the source file potentially.

### Proposal

Maybe force string reinterpolation with a `interpolate` function:

```hcl
data "github_repository_file" "config_file" {
  repository = "example-repository"
  branch     = "main"
  file       = "configs.yml"
}

locals {
  rendered-config = yamldecode(interpolate(data.github_repository_file.config_file.content))
}
```

Or enable `template_file` to access the entire variable scope of the module:

```hcl
data "template_file" "config_file" {
  template        = data.github_repository_file.config_file.content
  expose_all_vars = true
}
```

**Comment by crw** [comment]
Thanks for this detailed feature enhancement report!

**Comment by apparentlymart** [comment]
Hi @gchamon! Thanks for sharing this use-case.

Unfortunately the requirement to specify explicit dependencies for each particular [`templatefile` function](https://www.terraform.io/language/functions/templatefile) call (or, if you are using [the legacy `hashicorp/template` provider](https://registry.terraform.io/providers/hashicorp/template), [`template_file` data resource](https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file)) is there for a practical reason: Terraform needs to be able to see ahead of time (before evaluating any expressions) which objects depend on which other objects.

When you specify the specific values to expose into the template, each one creates a necessary dependency in the graph which allows Terraform to understand when is the appropriate time to evaluate the template.

Both of the examples you shared would require Terraform to already know what's present in `data.github_repository_file.config_file.content` during graph construction, which is currently impossible because reading from that data resource is one of the actions taken _using_ the constructed graph. There is therefore a conflict in the order of operations: we cannot walk the graph before we've built the graph, and we cannot build the graph until we've walked the graph.

Therefore while I understand your use-case, I'm afraid I don't see any way to meet it within the design of the Terraform language.

**Comment by gchamon** [comment]
I understand. Having datasources interpolate variables would mean that the graph would depend on which variables are declared in them, which is not known until the datasource is read.

I guess I would have to expose a limited set of variables and use the template datasource.
