### ISSUE TITLE
Unable to parse values from yaml file

### ISSUE THREAD

**Issue by pathaknikhil87** [hashicorp/terraform#31296]
### Terraform Configuration Files

Input Yaml -- 
```terraform

resource_groups:
  resource_group_management: manual
  startegy: landscapes
  resource_group:
    - name: core-rg
      id: rg1
      sapfunc: 3a
    - name: lz-rg
      id: rg2
      sapfunc: 2a

storage_volume:
  - id: AS0
    name: thanos
    disks:
      - id: app-1
        type: swap
        volume_profile: g-p
        zone_name: us-west
        resource-group-name: rg1
        count: 1
        iops: 10001
        capacity: 128
        buffer: 2
        encryption-key:
      - id: app-2
        type: data
        mounts:
          - path: /usr/mnt
            size: 100
          - path: /usr/tax
            size: 32
        volume_profile: g-p
        zone_name: us-west
        resource-group-name: rg1
        count: 1
        iops: 10000
        capacity: 132
        encryption-key:
    tags:
      - "type": application-1
        "value": person

```
We need to parse the values from above yaml to use it in module to deploy the disk and attach it to a vm. For other similar yaml entries we are converting the input value to local using yamldecode function. 
```
locals {
 input_yaml  = yamldecode(file("./.config/test.yaml"))

  rg_name = {for val in local.input_yaml["resource_groups"]["resource_group"]:
                 val["id"] => {
                     name= val["name"]
                     sapfunc = val["sapfunc"]
                 }}
}
```
### Expected Behavior

```
Read the inputs from Yaml file and use it. If there is any other way to parse the values, please let me know. Sample code is attached...
``
[yaml_poc_2.zip](https://github.com/hashicorp/terraform/files/8957079/yaml_poc_2.zip)
`

**Comment by apparentlymart** [comment]
Hi @pathaknikhil87!

It looks like your report is missing some of the sections from our issue template: your current configuration, and the "Actual Behavior" you saw when you tried to run it.

Can you add another comment with that additional content? Or if this was a request for help rather than a bug report, please close this issue and ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) instead, since we use GitHub issues to represent bugs and feature requests, rather than questions and general discussion. Thanks!

**Comment by apparentlymart** [comment]
Hi @pathaknikhil87!

Since we didn't hear from you again after my previous question, I'm going to close this under the assumption that you found the answer you needed elsewhere. If you still have questions related to this problem, please start an issue in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
