### ISSUE TITLE
Validation fails in reusable modules with alternate provider config

### ISSUE THREAD

**Issue by agloyd01** [hashicorp/terraform#31306]
### Terraform Version

```
Terraform v1.2.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.19.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
      configuration_aliases = [ aws.alternate ]
    }
  }

  required_version = ">= 0.12"
}

resource "aws_security_group" "default_provider" {
  name = "default_provider"
}

resource "aws_security_group" "alternate_provider" {
  provider = aws.alternate
  name      = "alternate_provider"
}
```

### Debug Output

https://gist.github.com/agloyd01/6d88c2779831e4c43859e3f117370b96

### Expected Behavior

I believe my provider configuration is correct for reusable modules that take one or more alternate provider configs for creating resources. This configuration should pass validation based on the `configuration_aliases` config under `required_providers'

### Actual Behavior

Validation fails with this error:
```
Error: Provider configuration not present
│ 
│ To work with aws_security_group.alternate_provider its original provider configuration at provider["registry.terraform.io/hashicorp/aws"].alternate is required, but it has been
│ removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy
│ aws_security_group.alternate_provider, after which you can remove the provider configuration again.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### Additional Context

We run `terraform init` followed by `terraform validate` for syntax checking in a GitHub action when pull requests are opened on reusable modules. I could easily replicate the behavior in a simple, one-file example

**Comment by apparentlymart** [comment]
Hi @agloyd01!

The `terraform validate` command is designed for validating entire configurations rather than single modules, and so with today's Terraform you will need to wrap your shared module in a small wrapping root module if you want to validate it in isolation, outside of any particular "real" configuration.

That root module need only be a basic valid configuration for this provider and then a `module` block which refers to your main module using a local filesystem reference. You can then init that root module and validate within it to test whether that entire configuration, including your main module, is valid all together. This is roughly analogous to wrapping a library written in a general-purpose language into some sort of main program in order to exercise it in development without having to first embed it in a "real" application.

There is an enhancement request already open here for introducing some way to do a piecemeal validation of an incomplete configuration which has a non-root module as its "root" (sadly I didn't find it in a quick search) but that is non-trivial to achieve within Terraform's existing assumptions and so I would suggest using the approach I described above for now because I don't expect there will be a direct module validation command available in the near future.

One rough edge your report here illustrates is that Terraform Core is not handling your invalid situation very well because it's treating it as if the configuration previously existed but has now been removed, whereas I expect we could do better by detecting this specific situation (the apparent root module isn't actually valid as a root module) and returning a more relevant error message which could hopefully echo something like the advice I gave above, about making a wrapping root module for testing.

**Comment by agloyd01** [comment]
Thanks for the information; I'll take that back to our Platform team to see how we can tweak our Terraform abstraction tools and validation process.

Yes, I knew what the error really meant, but you're right, the error handling in this scenario is a bit messy.
