### ISSUE TITLE
Referencing a resource no longer supported.  Terraform requiring a String.

### ISSUE THREAD

**Issue by cbichsel-personal** [hashicorp/terraform#31308]
I've been working with terraform to provision in OCI, and I had tested the creation of Compartments, Groups, and IAM policies successfully a few weeks ago.  Today I tried to run the Terraform validate and plan commands and got errors saying string required. The argument on line 15 worked a few weeks ago.

Error: Incorrect attribute value type
│
│   on LZ Compartments.tf line 15, in resource "oci_identity_compartment" "security_compartment":
│   15:     compartment_id = [oci_identity_compartment.landingzone_compartment.id]
│     ├────────────────
│     │ oci_identity_compartment.landingzone_compartment.id will be known only after apply       
│
│ Inappropriate value for attribute "compartment_id": string required.

**Comment by jbardin** [comment]
Hi @cbichsel-personal,

The configuration snippet in the error shows you are assigning a list of a single slice to the `compartment_id` attribute, but the `compartment_id` requires a single string. I'm not sure how you initially applied the configuration, but perhaps something was changed, or upgraded in the meantime.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
