### ISSUE TITLE
terraform test fails using version >=1.2.0 with `Error: Unassigned variable`

### ISSUE THREAD

**Issue by pst** [hashicorp/terraform#31315]
### Terraform Version

```
fails on all versions >=1.2.0
```

### Terraform Configuration Files

```
See git clone below.
```

### Expected Behavior

Terraform test runs and tests pass.

### Actual Behavior

```
─── Error: non_string_values (terraform plan) ────────────────────────────────────────────────────────────────────────────
failed to create a plan
╷
│ Error: Unassigned variable
│ 
│ The input variable "test_configuration" has not been assigned a value. This is a bug in Terraform; please report it in a
│ GitHub issue.
╵
```

### Steps to Reproduce

```
git clone https://github.com/kbst/terraform-kubestack.git
cd terraform-kubestack/common/configuration/
terraform test
```

**Comment by apparentlymart** [comment]
Hi @pst! Sorry for this odd behavior, and thanks for reporting it.

I think this has come about because the current experimental test harness isn't really built to deal with variables in the test configurations, and so we don't have any automated tests covering that situation. I assume your intention here was that `var.test_configuration` would match the default value you declared for that variable when run under `terraform test`.

We did some refactoring of how Terraform Core deals with root module variables which I guess was released for the first time in v1.2.0, and so probably this is related to that. Specifically, I think before it was a different layer's responsibility to deal with the handling of default values for root module variables such that the `terraform test` caller was "getting away with" not setting them, but now the test harness ought to be explicitly marking that variable as unset when it calls Terraform Core so that Terraform Core knows it's supposed to use the default value instead.

We're currently in the process of revisiting the testing experiment for another round based on earlier feedback, so I don't know if we'll be able to prioritize fixing the previous experiment immediately when it's likely to be replaced with something a little different soon anyway. However, if I'm right that your intent was to use only the default value of that variable then for now I think you could rework that to be a local value instead and thus avoid this problem, but making sure that your tests configurations don't have any root module input variables at all. With that said, if I do end up spotting a quick fix to this while I'm loading the context back in on `terraform test` for my next work then I'll see about opening a PR for it.

**Comment by pst** [comment]
Thanks @apparentlymart I can work with locals for now. I only have a small number of places where I tried terraform test. I am looking forward to try the next iteration of terraform test.

**Comment by crw** [comment]
Thanks for the response @pst! I'm going to close this issue as this experiment is going to be replaced soon, but we'll update this issue if @apparentlymart finds that quick fix. Thanks again for the issue report!
