### ISSUE TITLE
Unable to pass workspace to -backend-config

### ISSUE THREAD

**Issue by buzzy** [hashicorp/terraform#31328]
### Terraform Version

```
1.2.2
```

### Terraform Configuration Files

```
terraform {
  backend "remote" {}
}
```

### Expected Behavior

Terraform should accept my workspaces.name variable

### Actual Behavior

Terraform complains that workspaces.name is not expected for the selected backend type

### Steps to Reproduce

```
terraform init -backend-config="hostname=xxx" -backend-config="organization=yyy" -backend-config="workspaces.name=zzz"
```
### Additional Context

```
Initializing the backend...
╷
│ Error: Invalid backend configuration argument
│
│ The backend configuration argument "workspaces.name" given on the command line is not expected for the selected backend type.
╵
```

**Comment by kmoe** [comment]
The [`-backend-config="KEY=VALUE"`](https://www.terraform.io/language/settings/backends/configuration#partial-configuration) option can be used to specify key/value pairs for the backend block, but unfortunately this will not work in the case of `workspaces`, since `workspaces` is a block, so it is not possible to use the command line flags to create a `backend` block with a `name` attribute.

Fortunately I think you can avoid this awkward experience by using the new `cloud` block, which can be configured equivalently by using environment variables to set hostname, organisation, and workspace. This should do the same thing as your existing `remote` backend configuration. Please see the docs for migrating from the `remote` backend to `cloud` block: https://www.terraform.io/cli/cloud/migrating#migrating-from-the-remote-backend

This section describes the environment variables for hostname, organisation, and workspace: https://www.terraform.io/cli/cloud/settings#environment-variables

**Comment by crw** [comment]
Hi @buzzy, per https://www.terraform.io/cli/cloud, the earliest version of TFE that supports `cloud` is 202201-1 -- do you know if you are on that version? If so, we can look into official support on the HashiCorp side. 

> Note: The CLI integration is available in Terraform 1.1.0 and later, and Terraform Enterprise 202201-1 and later. Previous versions can use the remote[ backend](https://www.terraform.io/language/settings/backends/remote).

**Comment by buzzy** [comment]
I am using the action "hashicorp/setup-terraform" and pulled version 1.2.1. Not sure why the output mentions Terraform Enterprise.

**Comment by crw** [comment]
I understand, and apologize for the confusion. We are doing a bit more digging on our end.

**Comment by kmoe** [comment]
@buzzy, the `cloud` block is a top-level block and should not be placed inside the `terraform` block. So your config schema above should instead be:

```hcl
terraform {
  ...
}
cloud {
  ...
}
```

**Comment by crw** [comment]
Hi @buzzy, the documentation is correct. So to summarize the story so far: you are attempting to use the following project:

https://github.com/hashicorp/setup-terraform

Which as part of the action does the following: 

> Configuring the [Terraform CLI configuration file](https://www.terraform.io/docs/commands/cli-config.html) with a Terraform Cloud/Enterprise hostname and API token.

You are specifying and empty `cloud` block and attempting to configure on the command line:

```
terraform init -backend-config="hostname=xxx" -backend-config="organization=yyy" -backend-config="workspaces.name=zzz"
```

When discussing this in triage, the two questions that arose are:
1. Are you trying to use this with Terraform Cloud or Terraform Enterprise? If not, what remote backend service are you using?
2. Could you please put the full contents of the error message you are seeing when attempting this operation with the cloud block as previously specified? e.g. is there more error message context around `"cloud" is not supported in this Terraform Enterprise version`?

**Comment by crw** [comment]
Closing due to lack of response. Please let us know if you have further questions or issues with this functionality.
