### ISSUE TITLE
Heredocs in arrays are not rendered correctly in output commands

### ISSUE THREAD

**Issue by C0urante** [hashicorp/terraform#31361]
### Terraform Version

```
Terraform v1.2.4
on linux_amd64
+ provider terraform.observeinc.com/observeinc/observe v0.7.0
```

### Terraform Configuration Files
Provider definitions are omitted as they do not appear to be relevant to this issue.

```terraform
locals {
    a = [
        <<-EOT
            This is a heredoc.
        EOT
    ]
    
}

output "output_arr" {
    value = local.a
}

```

### Debug Output
I've omitted this for now as it does not appear relevant; happy to provide trace output if that's not the case.

### Expected Behavior
The output should not contain a trailing comma on the same line as the delimiter word (`EOT`).

When running `terraform output`:
```terraform
output_arr = [
  <<-EOT
  This is a heredoc.
  
  EOT
]
```

### Actual Behavior
A trailing comma is included after the delimiter word.

When running `terraform output`:
```terraform
output_arr = [
  <<-EOT
  This is a heredoc.
  
  EOT,
]
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -auto-approve`
3. `terraform output`

### Additional Context
This is the easiest way to reproduce the issue, but it is not the only place where it appears, nor is it the most problematic. I ran into this while trying to copy the output from `terraform state show ...` into a terraform definition; I had to load the definition into an IDE whose syntax highlighting helped identify the issue with the heredoc never being terminated/being terminated at a much later place in the file.

### References
Similar title to https://github.com/hashicorp/terraform/issues/22031, but the underlying issue appears to be different.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @C0urante!

In general our human-oriented output of this type is intended to be "configuration-language-_like_" as an aid to understanding, but will not always be exactly valid configuration: sometimes we need to make some compromises either to make the overall result fit together well or honestly just because the logic for handling all of these edge cases can get complicated and sometimes it just doesn't seem worth the additional complexity to deal with something relatively rare. In particular, being able to cop the output from `terraform show` into configuration is not a design goal, but is a happy coincidence that _does_ work out most of the time if you're willing to make some small edits afterwards.

With that said, I agree that what this is producing is not valid Terraform language syntax, and results from Terraform making a best effort to show a multi-line string in a readable way but with a value printer that is built in such a way that the function which prints out individual strings is separate from the function that prints out a list and the commas separating its elements.

In order to make this valid in the general case would require, I think, still including a comma but placing it on a separate line from the `EOT` marker:

```
output_arr = [
  <<-EOT
    This is a heredoc.
  
  EOT
  ,

  <<-EOT
    This is a heredoc.
  
  EOT
  ,
]
```

...which looks pretty weird, because in practice in real configuration we don't typically write stuff like this. (Exactly how you _would_ write a list of heredoc templates is an interesting question; I've not seen that need arise often enough to consider there to be an established idiom for it.)

I think the tradeoff to be made here is whether it's worth whatever extra complexity this implies for the value visualization code to support a situation that comes up relatively rarely in practice and doesn't really cause a _significant_ problem for the intended use-case of humans reading the output (rather than trying to parse the output as if it were Terraform language code).

I think hidden under this bug report is a feature request: I assume that what you were looking for here is a way to generate a valid configuration for an existing object already in the state, perhaps because you ran `terraform import` to adopt an existing object that wasn't originally declared in Terraform. If that's true, it may be more productive for us to focus on that use-case and aim to design and build something to meet it, since just fixing this one particular situation to generate something that can be copy-pasted will not address the inevitable other little compromises in the `terraform show` implementation that arise from it not being designed to meet this need.

**Comment by C0urante** [comment]
> I assume that what you were looking for here is a way to generate a valid configuration for an existing object already in the state, perhaps because you ran terraform import to adopt an existing object that wasn't originally declared in Terraform. If that's true, it may be more productive for us to focus on that use-case and aim to design and build something to meet it

That's spot on. I used a `data` block to load the pre-existing resource instead of the `terraform import` command, but everything else is correct, and now that I think about it, the latter may have been more appropriate anyways. I'd love a way to grab a configuration for something that already exists in order to facilitate the onboarding use case of "get a working copy of something and make tweaks to see what changes", which is difficult when the "working copy" isn't static and is meant to be derived from something the user has created.

I was also under the impression that `terraform state show` and commands like it were intended to produce Terraform-compatible output; if this isn't the intended goal for those commands, then I can definitely see an argument to be made for allowing this "bug" to stay in order to avoid polluting the rendering logic with additional unneeded complexity. FWIW, the proposed change of placing the comma on its own line does look fine to me from an aesthetic standpoint.

I don't feel like I have a great grasp on what exactly the underlying feature request here would entail, at least not enough to file a new issue for it. But as long as this issue corresponds to unexpected but not incorrect behavior, it should probably be closed until/unless we decide to make a special exception for it. If you or someone else could file a new issue for the feature request that'd be much appreciated, but either way, I think we can close this one for now.

Thanks for the rapid, thoughtful response @apparentlymart!
