### ISSUE TITLE
Optional 2nd level objects are ignored in defaults

### ISSUE THREAD

**Issue by i2dcarrasco** [hashicorp/terraform#31368]
Hello, I'm trying to create a fully configurable 2nd level object/map into terraform using the for now experimental features `optional` and `defaults`, but on every try I do, it returns an wrong value. For example,
I want the ability to have a map inside a map wich all the values as optional, then allow to provide any of the options without to have to provide at least all the keys.

### Terraform Version
```
# terraform version
Terraform v1.2.4
on linux_amd64
```

### Terraform Configuration Files

module_test.tf
```terraform
module "test" {
    source = "./module"
}

output "test" {
  value = module.test.test
}
```

module/vars.tf
```terraform
// Test variable

variable "test" {
  type = object({
    # this works as expected because is first level key/value
    aa = optional(string)

    # This doesn't work very well if at least the first level key is not provided
    bb = optional(object({
      cc = optional(string)
    }))
  })

  default = {}
}
```

modules/locals.tf
```terraform
terraform {
  experiments = [module_variable_optional_attrs]
}

locals {
  test = defaults(var.test, 
    {
      aa = "aa"

      bb = {
        cc = "cc"
      }
    }
  ) 
}

output "test" {
  value = local.test
}
```

### Debug Output
https://gist.github.com/i2dcarrasco/fff30be0fb0800afa248b20420f03877

### Expected Behavior
Use the defaults if none is provided by the `optional` feature. I understant that is working like this to manage when the user provides a null value.

### Actual Behavior
When optional values are used, it seems to be marked as null if not provided. This causes the defaults to understand that a value was provided and then it doesn't merge the data.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
If I just provide the key of the 2nd level map then it works as expected:

```terraform
module "test" {
  source = "./module"

  test = {
    bb = {}
  }
}
```

```
# terraform apply

Changes to Outputs:
  + test = {
      + aa = "aa"
      + bb = {
          + cc = "cc"
        }
    }
```

But will be nice to allow to avoid it, because if you have two is not a problem but when you have a lot...

Best regards.

**Comment by alisdair** [comment]
Thanks for the issue. The `defaults` function does not work well for some use cases, including nested objects. For this reason, in the upcoming Terraform 1.3 release, we have implemented a different design of optional object attributes with defaults.

We've released this for early testing and feedback in the 1.3 alpha series. [Please see this forum post for more details](https://discuss.hashicorp.com/t/request-for-feedback-optional-object-type-attributes-with-defaults-in-v1-3-alpha/40550).

Part of this change will be to remove the `defaults` function altogether, so I'm marking this as closed, since we won't be changing its behaviour. If you have any feedback around this feature, we'd love to hear it over in the forum thread!
