### ISSUE TITLE
Bug report for inconsistent plan

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#31386]
Terraform 1.2.3

Error:

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.mymodule.module.myinnermodule.time_sleep.ready
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/time" produced an invalid new value for
│ .triggers["assume_role_policy"]: was cty.StringVal("{\n  \"Version\":
│ \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\":
│ \"foo\",\n      \"Effect\": \"Allow\",\n
│ \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"AWS\":
│ \"arn:aws:iam::000000000000:role/bar\"\n      }\n
│ },\n    {\n      \"Sid\": \"foo2\",\n      \"Effect\":
│ \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n
│ \"AWS\": \"arn:aws:iam::000000000000:role/bar2\"\n
│ }\n    }\n  ]\n}"), but now
│ cty.StringVal("{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"foo\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::000000000000:role/bar\"},\"Action\":\"sts:AssumeRole\"},{\"Sid\":\"foo2\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::000000000000:role/bar\"},\"Action\":\"sts:AssumeRole\"}]}").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Approximate code:

```
resource "time_sleep" "ready" {
  triggers = {
    name               = aws_iam_role.this.name
    assume_role_policy = aws_iam_role.this.assume_role_policy
    permissions_boundary = aws_iam_role.this.permissions_boundary
  }
  create_duration = "10s"
  depends_on = [
    aws_iam_role.this
  ]
}
```

The code is designed to ensure that a role is ready and can be used as aws iam is eventually consistent.

It seems minor variations in the assume_role_policy reordering itself is causing a problem with the trigger.

**Comment by jbardin** [comment]
Hi @gtmtech,

The error is partly correct here, it is a bug in the provider, and should be reported in the provider's own issue tracker, however the source of the bug in this case is the `aws` provider, not the `time` provider. I suspect tat if you look at the logs from the plan and apply process, you will see warnings from the `aws_iam_role.this` resource, about the `assume_role_policy` value being inconsistent but we have to tolerate the situation for compatibility with the legacy SDK.
Looking over at that provider's repo, there appears to already be at least one issue filed here: https://github.com/hashicorp/terraform-provider-aws/issues/23965

Since this isn't a bug in the Terraform CLI I'm going close this out, and we can follow any resolution in the aws provider issue.

Thanks!
