### ISSUE TITLE
When new resource created due to version update of provider. Dependant blocks should also executes regardless of terraform state.

### ISSUE THREAD

**Issue by Rahul-Soni28** [hashicorp/terraform#31391]
### Current Terraform Version

```
...
```

**Comment by apparentlymart** [comment]
Hi @Rahul-Soni28,

There doesn't seem to be any content in your issue report here, so I'm going to close it. If you do want to discuss the behavior you saw, please do open a new issue and answer the questions in the issue template. If you were intending to open a bug report instead of an issue, please use the bug report template so it will ask more appropriate questions for that situation. Thanks!
