### ISSUE TITLE
Lifecycle replace_triggered_by silently ignores invalid attribute access

### ISSUE THREAD

**Issue by skyfox675** [hashicorp/terraform#31401]
### Terraform Version
```
1.2.4
```

### Terraform Configuration Files

```terraform
resource "random_pet" "this" {
  length = 1
  keepers = {
      sse_encrypt = var.sse_encrypt
    }
}

resource "aws_s3_object" "this" {
  for_each = fileset(var.file_path, "**")

  content_type           = lookup(jsondecode(file("${path.module}/src/mime.json")), regex("\\.[^.]+$", each.value), null)
  content_language       = var.content_language
  cache_control          = var.cache_control
  acl                    = var.acl
  bucket                 = var.bucket_id
  storage_class          = var.storage_class
  key                    = each.value
  source                 = "${var.file_path}/${each.value}"
  etag                   = filemd5("${var.file_path}/${each.value}")
  server_side_encryption = random_pet.this.keepers.sse_encrypt ? "AES256" : null

  lifecycle {
    replace_triggered_by = [
      random_pet.this.keepers.sse_encrypt
    ]
  }
}
```

### Expected Behavior
Each instance of the for_each should have been replaced.

### Actual Behavior
A single instance of the for_each was replaced.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
This is residing in a module I maintain (https://github.com/Lupus-Metallum/terraform-aws-s3-static-website)

**Comment by jbardin** [comment]
Hi @skyfox675,

Thanks for filing the issue. I think the problem here is the syntax you are using in `replace_triggered_by`, and some missed validation to catch it. The `keepers` attribute is a map of strings, so if you wanted to address that key specifically, you would use `random_pet.this.keepers["sse_encrypt"]`. I have a feeling that the single instance was being replaced by another change in the overall configuration. Can you show the plan output from the single instance being replaced?

Note that in this case (and in most cases) you only need to reference the resource like `random_pet.this` in `replace_triggered_by`, since the change to `keepers` is going to replace the entire resource anyway. You only need to use a specific attribute reference if a change to that attribute in isolation is the desired trigger for replacement.

Thanks!

**Comment by skyfox675** [comment]
Hey @jbardin,

Thanks for the reply, this is the plan output, figured a screenshot is cleaner since the state includes ~2k resources.
![Screen Shot 2022-07-08 at 09 49 54](https://user-images.githubusercontent.com/4504420/178017024-1d681bb5-ab69-4f97-b34c-bae430b656d8.png)

I'll update to just the resource reference - `random_pet.this` in the `replace_triggered_by` and see if that resolves it.

Thanks!

**Comment by skyfox675** [comment]
Thanks for the assist @jbardin! After updating to the following, Objects are successfully being recreated by `replace_triggered_by`:
``` terraform
resource "random_pet" "this" {
  length = 1
  keepers = {
      sse_encrypt = var.sse_encrypt
    }
}

resource "aws_s3_object" "this" {
  for_each = fileset(var.file_path, "**")

  content_type           = lookup(jsondecode(file("${path.module}/src/mime.json")), regex("\\.[^.]+$", each.value), null)
  content_language       = var.content_language
  cache_control          = var.cache_control
  acl                    = var.acl
  bucket                 = var.bucket_id
  storage_class          = var.storage_class
  key                    = each.value
  source                 = "${var.file_path}/${each.value}"
  etag                   = filemd5("${var.file_path}/${each.value}")
  server_side_encryption = random_pet.this.keepers["sse_encrypt"] ? "AES256" : null

  lifecycle {
    replace_triggered_by = [
      random_pet.this
    ]
  }
}
```

**Comment by crw** [comment]
@skyfox675, thanks for the update! Is this issue resolved as a result?

**Comment by skyfox675** [comment]
@crw it is, I'll mark as closed/resolved, thanks!
