### ISSUE TITLE
terraform show crashes when state file is locked

### ISSUE THREAD

**Issue by jojje** [hashicorp/terraform#31430]
### Terraform Version

```
v1.2.4
```

### Terraform Configuration Files

```terraform
provider "null" {}
```

### Debug Output

[gist](https://gist.github.com/jojje/4a894519565d52fdce0e313fb7b317ce)

### Expected Behavior

The state/plan should have been shown, or an error message about the state file being locked should have been displayed.

### Actual Behavior

Golang process panicked (crashed)

### Steps to Reproduce

1. `terraform init`
2. `terraform console` (in another terminal, but in the same directory)
3. `terraform show`

### Additional Context

None

### References

None

**Comment by crw** [comment]
Thanks for this report.

**Comment by kmoe** [comment]
Thanks for this. I was able to reproduce this on Linux by creating a state file with invalid JSON.
In general, this crash will appear whenever Terraform is unable to access the latest state snapshot for whatever reason: the file could be corrupt, unparseable as JSON, inaccessible, etc. 

Fixed by https://github.com/hashicorp/terraform/pull/31444.
