### ISSUE TITLE
Provider configuration not present error on deleting a module

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#31436]
### Terraform Version
```
Terraform v1.2.3
on linux_amd64
```

Old configuration:

main.tf

```terraform
module "foo" {
  source = "./foo"
}
```

./foo/main.tf

```terraform
terraform {
  required_providers {
    rabbitmq = {
      source  = "cyrilgdn/rabbitmq"
    }
  }
}

provider "rabbitmq" {
...
}

resource "rabbitmq_vhost" "app" {
  name = local.infra_name
}
```

New configuration:

main.tf

```terraform
terraform {
  required_providers {
    rabbitmq = {
      source  = "cyrilgdn/rabbitmq"
    }
  }
}

provider "rabbitmq" {
...
}

resource "rabbitmq_vhost" "app" {
  name = local.infra_name
}
```

The provider configuration was moved from a module to the top-level configuration.

### Expected Behavior
Infrastructure changed accordingly.

### Actual Behavior
```none
╷
│ Error: Provider configuration not present
│ 
│ To work with module.foo.rabbitmq_vhost.app (orphan) its original
│ provider configuration at
│ module.backend.provider["registry.terraform.io/cyrilgdn/rabbitmq"] is
│ required, but it has been removed. This occurs when a provider
│ configuration is removed while objects created by that provider still exist
│ in the state. Re-add the provider configuration to destroy
│ module.backend.rabbitmq_vhost.app (orphan), after which you can remove the
│ provider configuration again.
```

The provider configuration is present, but TF doesn't see it. As there is no explicit linkage between resource and provider, TF must pick up any existing configuration in the project.

**Comment by jbardin** [comment]
Hi @speller,

Because provider instances may have different configurations, they are tracked via their location and name in the configuration, so `module.backend.provider["registry.terraform.io/cyrilgdn/rabbitmq"]` is not the same provider as `provider["registry.terraform.io/cyrilgdn/rabbitmq"]` in the root module. This is one of the reasons that provider configuration within modules is deprecated, and cannot be supported for modules using `count` or `for_each`.

In order to remove the resource, you can first move the provider configuration to the root module and apply to change the recorded provider in the state. See https://discuss.hashicorp.com/t/provider-configuration-not-present-trying-to-destroy-a-module-that-has-a-required-sub-module/41778/2 for a more detailed description.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
