### ISSUE TITLE
Terraform should know bucket name (id) before apply

### ISSUE THREAD

**Issue by ddanf** [hashicorp/terraform#31431]
Apologies if this is related to the AWS provider and not actually terraform, but it seems appropriate to put it here now.

### Current Terraform Version
tf 0.13.8
aws 4.21.10

### Use-cases
When referring to an aws_s3_bucket resource's id (bucket name) attribute, specifically inside a for_each in my case, we receive an error stating that "The "for_each" value depends on resource attributes that cannot be determined until apply".  While I get that not knowing the value could make it difficult to execute the for_each, it really seems that terraform should know that bucket.id is not an arn that is assigned when the resource is created but is actually the same as the bucket name that we assign in our declarative code.

`
aws_s3_bucket "one-fish" {
  name = var.one
  ...
}

aws_s3_bucket "two-fish" {
  name = var.two
  ...
}
// two more buckets...

aws_s3_bucket_logging "my_logs" {
  for_each = toset([
    aws_s3_bucket.one-fish.id,
    aws_s3_bucket.two-fish.id,
    aws_s3_bucket.red-fish.id,
    aws_s3_bucket.blue-fish.id
  ])
  bucket = each.key
  target_bucket = aws_s3_bucket.log-bucket.id
  target_prefix = "s3/${each.key}"
`

With many resource arguments being deprecated in favor of standalone resources, using patterns like this can really help beautify our terraform, but this does not work as-is.

### Attempted Solutions

There are of course, simple ways to fix the code above.  My fix was to replace the bucket.id references with the expressions that the bucket names are set to in my declarative code, but you could I guess just assign the keys to a map directly, but if we're hard-coding and copying expressions, let's do it right. ;)

### Proposal

When tf encounters a reference to a resource attribute, if that attribute is a value assigned by the declarative code (bucket id reports only the name, which is assigned by the arguments to the aws_s3_bucket resource), then tf should use the value from the declarative code.

**Comment by jbardin** [comment]
Hi @ddanf,

This indeed is a question about the provider, rather than Terraform core. The `aws_s3_bucket` bucket uses the `id` field not only to store and identifying string, but it is also used in configuration to imply that the resource has been completely created. The details of how the `id` attribute are used in the provider mostly come down to the use of the legacy Terraform SDK, where `id` is a special attribute which has overloaded meaning within the provider.

If the id of the bucket is deterministic, then it is technically feasible for the provider to produce that during plan, however it may not be something desirable to add to the current provider version due to constraints of the SDK. You may be able to manually generate it via other means, but the best way to do that would be a question for the AWS provider team. Do note however that having the identifier available during the plan can subtly break existing configurations patterns which also expect the `id` to only be available once the resource is created and ready during the apply process.

Since this is not an issue with the Terraform CLI, i'm going to close it out for now. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. These GitHub issues here are monitored only by a few core maintainers.

Thanks!
