### ISSUE TITLE
Terraform Cloud 2FA - Add support for FIDO2 / Webauthn

### ISSUE THREAD

**Issue by pro4tlzz** [hashicorp/terraform#31448]
Hi,

It would be very nice to have FIDO2 / Webauthn support for Terraform Cloud without using an iDP.

FIDO2 / Webauthn should be the first option to implement when developing 2FA for a service.

Thanks

**Comment by apparentlymart** [comment]
Hi @pro4tlzz! Thanks for this feedback.

For Terraform Cloud feedback I'd suggest contacting [HashiCorp Support](https://support.hashicorp.com/), since they can pass feedback onto the Terraform Cloud product teams and associate it with your account so that the teams can see which customers are requesting which features.

Terraform Cloud teams don't typically monitor this repository, since it's for the Terraform CLI and Terraform Core open source project.

I'm going to close this issue not because it isn't good feedback but just because there isn't really anything we could change _in this repository_ to address this request, and this isn't a place that folks working on Terraform Cloud will look to find feedback of this kind.

Thanks again!
