### ISSUE TITLE
Data source "external" fails on Linux platform

### ISSUE THREAD

**Issue by YuriGal** [hashicorp/terraform#31449]
### Terraform Version

```
1.1.1
```

### Terraform Configuration Files

```terraform
# data "external" "tools_accounts" {
#   program  = ["aws", "organizations", "list-accounts-for-parent", "--parent-id", local.deployment_ou, "--query", "Accounts[?Name==`${local.tools_account}`] | [0]"]
# }
```

### Debug Output

```
Error: Unexpected External Program Results
--
971 |  
972 | with data.external.tools_accounts,
973 | on cdk_bootstrap.tf line 2, in data "external" "tools_accounts":
974 | 2:   program  = ["aws", "organizations", "list-accounts-for-parent", "--parent-id", local.deployment_ou, "--query", "Accounts[?Name==`${local.tools_account}`] \| [0]"]
975 |  
976 | The data source received unexpected results after executing the program.
977 |  
978 | Program output must be a JSON encoded map of string keys and string values.
979 |  
980 | If the error is unclear, the output can be viewed by enabling Terraform's
981 | logging at TRACE level. Terraform documentation on logging:
982 | https://www.terraform.io/internals/debugging
983 |  
984 | Program: /root/.pyenv/shims/aws
985 | Result Error: json: cannot unmarshal number into Go value of type string
```

### Expected Behavior

When that external AWS CLI command runs it returns result similar to below:
```
{
    "Id": "1234567890",
    "Arn": "arn:aws:organizations::1234567890:account/o-p12345e/1234567890",
    "Email": "email@domain.com",
    "Name": "account-alias",
    "Status": "ACTIVE",
    "JoinedMethod": "CREATED",
    "JoinedTimestamp": "2022-06-15T14:00:22.158000-04:00"
}
```
It returns map of string values which satisfies the data source requirement. And it works on local laptop (Mac/Darwin) just fine. I expect it do do the same in AWS Codebuild/Linux environment.

### Actual Behavior

While running AWS Codebuild/Linux environment it throws the error mentioned in the above logs.

**Comment by apparentlymart** [comment]
Hi @YuriGal!

This error message seems to be coming from the `hashicorp/external` provider rather than Terraform CLI itself, so if you think this error is _incorrect_ (that your program is functioning correctly) then I would suggest opening an issue in [the provider's own repository](https://github.com/hashicorp/terraform-provider-external).

However, I would suggest first trying what the error message mentions: run Terraform with the `TF_LOG=trace` environment variable set in order to see the full trace logs, which should hopefully include some messaging from `terraform-provider-external` showing the raw data it received from your child program. The error message suggests that this program is generating an object property that is a JSON number instead of a JSON string, and the output you included in your message here doesn't show any such property but I wonder if it's for some reason generating a slightly different result when you run it under the `external provider.

Since this isn't a behavior in Terraform CLI or Terraform Core I'm going to close this issue, but I would encourage you to open a similar issue in the provider repository if what I suggested above doesn't convince you that the program is generating a number instead of a string as the error message claims. Thanks!

**Comment by YuriGal** [comment]
Thanks @apparentlymart! I did ran it wit trace on and got only a few addition lines
```
2022-07-15T15:48:27.147Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
--
987 | 2022-07-15T15:48:27.147Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
988 | 2022-07-15T15:48:27.147Z [DEBUG] provider: plugin process exited: path=.terraform/dil-infrastructure/providers/registry.terraform.io/hashicorp/external/2.2.2/linux_amd64/terraform-provider-external_v2.2.2_x5 pid=768
989 | 2022-07-15T15:48:27.147Z [DEBUG] provider: plugin exited
```
Will post the issue in the provider repo as you suggested.
