### ISSUE TITLE
modules should be able to configure providers from data

### ISSUE THREAD

**Issue by iamnoah** [hashicorp/terraform#31470]
### Current Terraform Version

v1.2.3

### Use-cases

When using the kubernetes provider on EKS, the provider configuration can reasonably be provided by data aws_eks_cluster and aws_eks_cluster_auth given an AWS provider and cluster name or tags. Many internal modules know the correct cluster name or tags of the EKS cluster the module is intended to target. e.g.,

```terraform
data "aws_eks_cluster" "cluster" {
  name = "foo" # well known cluster in all our AWS accounts... could be passed as a variable
}

data "aws_eks_cluster_auth" "cluster" {
  name = data.aws_eks_cluster.cluster.name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

// configure some resources in foo...
resource "kubernetes_config_map" "bar" { ... }
```

It is burdensome and error prone to specify a provider block for every usage of a module targeting a well-known cluster. Other AWS resources do not require a separate provider configuration. 

### Attempted Solutions

Legacy provider module support allows this, but the need for for_each, count, and depends_on in modules usually outweighs the annoyance of copying and pasting a provider. It would be preferable to not have to choose which configuration is duplicated.

### Proposal

I do not know what the most natural way of configuring providers like this is. One argument might be that kubernetes is not a provider in my example and the AWS module should have eks resources for all the kubernetes types.

I do not understand the issues that keep modules from declaring their own providers well enough to come up with a good solution here. Would allowing providers that are wholly configured with static values and data from a passed in provider be enough to allow this?

**Comment by jbardin** [comment]
Hi @iamnoah,

Because providers must outlive the configuration they manage, they are expected to be declared in the root module, and passed into other modules via the `providers` mapping in the module call. Putting a provider configuration with a module precludes it from ever being removed. See [Provider Within Modules](https://www.terraform.io/language/modules/develop/providers) for details about creating modules which require provider configuration.

It's not clear exactly what sort of enhancement you are looking for in this case, but have issues covering more dynamic configuration of providers, both for multiple provider instances and passing to multiple module instances (see #25244, #24476, and #19932).

If you are asking about better patterns regarding the the configuration of kubernetes providers, [the community forum](https://discuss.hashicorp.com) is a better place to ask, where there are more users familiar with the usage and details of the providers themselves.

Thanks!
