### ISSUE TITLE
Optional module requires fully configured provider

### ISSUE THREAD

**Issue by pritho** [hashicorp/terraform#31486]
### Terraform Version

```
Terraform v1.2.4
```

### Terraform Configuration Files

The main tf-file uses a Vault-module optionally
```terraform
module "use_vault" {
  source = "[PATH-TO-VAULT-MODULE]"
  count = var.use_vault ? 1 : 0
}
variable "use_vault" {
  type = boolean
  default = false
}
```

The Vault-Module has a required provider set:
```terraform
terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = ">=2.24.1"
    }
  }
  required_version = ">= 1.0.7"
}
```

### Expected Behavior

Terraform ignores the provider installation and configuration of a not used referenced module

### Actual Behavior

Terraform instantiates and configures the provider as the called module is not being used

### Additional Context

We want to use the Vault-Part optionally without having to configure tokens for unnecessary provider instantiations

**Comment by jbardin** [comment]
Hi @pritho,

Terraform cannot ignore the provider requirements for the module, because there is no way to determine if the module will be used at runtime before any configuration is evaluated. Any provider configuration must also be valid for these reasons, since validation is done statically without taking any variable values into consideration.

The ability to avoid the final configuration call to a provider however may be possible. This would be the zero-case of #19932 (since the provider cannot be configured within the module itself), so we can track any possible solutions in that issue.

Thanks!

**Comment by pritho** [comment]
Hey, thanks for your answer.
As the issue you're pointing to is 3.5y open, I think I'll need to fork the module with a second path...
