### ISSUE TITLE
aws_instance: set windows_password attr on windows instances

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#3148]
On `Read` for AWS instances, if `platform` is `Windows`, call [`GetPasswordData`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetPasswordData.html) and populate a `windows_password` attribute with its contents.

This should allow the `remote_exec` provisioner to be used on Windows instances like this:

``` js
resource "aws_instance" "foo" {
  # ...
  provisioner "remote-exec" {
    connection {
      type     = "winrm"
      password = "${self.windows_password}"
    }
  }
}
```

**Comment by antonosmond** [comment]
Thanks for raising this Paul it's exactly what we need!

**Comment by adamveld12** [comment]
What if you can provide the pem key file used to create the instance and terraform just deals with decrypting the password itself with the key? This works in principle similarly to how Packer works with Windows instances. (Packer generates a temp key file, creates the resource with it, and then gets the password for access from what I can tell).

This would be consistent with how the SSH connection works (they both would be taking a private key in this case) so it seems like it would bring some nice consistency with how they both work.

**Comment by epsilon-jpage** [comment]
This is also a blocker for me.  I need to be able to perform remote execs on a windows server but want Terraform to query AWS for the Windows password and not need me to key it in or put it in a file.

**Comment by johnjelinek** [comment]
:+1:

**Comment by deftflux** [comment]
I started a pull request [#5675](https://github.com/hashicorp/terraform/issues/5675) that implements this, since we need this function too.  It works a little differently than described here, mainly to avoid the decrypted password from ending up in the terraform state file.  This is my first time developing for terraform (and in Go for that matter), so I'd appreciate some feedback.

**Comment by mojowrkn** [comment]
Also a blocker here, any updates?

**Comment by deftflux** [comment]
Back when I implemented this feature, it worked for me.  It may need to be merged with changes released since then.  However, we no longer need to use terraform to provision windows instances in our particular use case, so I haven't done any more work on it.

The pull request is only missing acceptance tests.  At that point, it should meet their development guidelines.  Someone with some experience writing acceptance tests for terraform would be able to do this much quicker than I could.  Anyone?
