### ISSUE TITLE
Local mirror of remote modules

### ISSUE THREAD

**Issue by archoversight** [hashicorp/terraform#31492]
### Current Terraform Version

```
Terraform v1.2.5
on darwin_arm64
```

### Use-cases

I have a requirement to ship a full terraform installation + modules to an off-line location. Much like `terraform providers mirror` I would love to be able to mirror the modules that are in use so that they are in that same mirror (and even have different versions available if the versions used across the board are not the same, much like providers).

The issue I ran into just cloning/updating the modules into a `vendor` folder is that some of the modules may call out to other modules that also require a particular version/module to be downloaded, which led to having to rewrite the source code to update the module source line to point to the local copy.

This is not really sustainable, and we'd prefer not to have to rewrite all the useful modules that exist online.

### Attempted Solutions

Right now someone on the team runs terraform init locally against a dev environment, and we manually copy over the full terraform folders, and version control them for off-line or limited network access environments.

### Proposal

Having something like `terraform modules mirror` would help alleviate this issue.

### References

- https://github.com/hashicorp/terraform/issues/31301: Locks the version, which would also be useful to have, but not a direct requirement
- https://github.com/hashicorp/terraform/issues/31134: Allow installation from a mirror, I would prefer that mirror to just be a directory tree on disk, vs a HTTPS service/web server
- https://github.com/hashicorp/terraform/issues/29362: This seems to be an override per module using command line flags which seems like it would be difficult to use for hundreds of modules

**Comment by apparentlymart** [comment]
Hi @archoversight! Thanks for sharing this.

I think what you've described here amounts to the same request as #31134. Although you've framed it in slightly different terms, the `terraform providers mirror` command is only useful when combined with either the "filesystem mirror" or "network mirror" provider installation strategies, and so a hypothetical command for creating a mirror of modules would need to come also with a way to tell Terraform to use a mirror for module installation, which seems like the most likely resolution for #31134 (although it's still in design-space rather than implementation-space, so it's still open for considering other proposals).

To consolidate the discussion and the :+1: voting onto a single issue, I'm going to close this one in favor of #31134. If you don't see something in that issue that feels like it represents the use-case you were sharing here, please feel free to add a comment to that issue with similar content to your "use-cases" section of this issue, and then that'll reduce the risk of missing this when starting on future design work. Thanks!
