### ISSUE TITLE
Path globs breaks commenting blocks

### ISSUE THREAD

**Issue by skwashd** [hashicorp/terraform#31502]
### Terraform Version

```
Terraform v1.2.5
on darwin_amd64
```

### Terraform Configuration Files

```terraform
/*

data "archive_file" "lambda" {
  type        = "zip"
  source_dir  = local.lambda_build_dir
  output_path = local.lambda_zip
  depends_on  = [null_resource.lambda_build]
  excludes    = fileset(local.lambda_build_dir, "**/*.txt")
}

*/
```

### Debug Output

```sh
$ terraform validate
╷
│ Error: Argument or block definition required
│ 
│   on failure.tf line 8:
│    8:   excludes    = fileset(local.lambda_build_dir, "**/*.txt")
│ 
│ An argument or block definition is required here.
╵
╷
│ Error: Invalid multi-line string
│ 
│   on failure.tf line 8:
│    8:   excludes    = fileset(local.lambda_build_dir, "**/*.txt")
│    9: }
│ 
│ Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax.
╵
╷
│ Error: Invalid multi-line string
│ 
│   on failure.tf line 9:
│    9: }
│   10: */
│ 
│ Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or use the "heredoc" multi-line template syntax.
╵
```

### Expected Behavior

It should ignore the `*/` inside the quoted string.

### Actual Behavior

It is interpreting the `*/` inside the quoted string as the end of the comment.

### Steps to Reproduce

1. Create a new empty project2. 
2. Add the example code from the "Terraform Configuration Files" section as `failure.tf`3. 
3. `terraform validate` 
4. swear 

### Additional Context

Northing special about my setup. I tried to make the test case as isolated as possible.

**Comment by jbardin** [comment]
Hi @skwashd,

The only character pattern not allowed within a comment block is the closing `*/` digraph, and since there is no language syntax within a comment, there is no quoted string within which the parsing context would change. This is common to most languages using the same style of block comments, with the solution being to revert to individual line comments for the problematic text (Handling blocks of comments by prefixing each line is handled automatically by most code editors). 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
