### ISSUE TITLE
Not able to parse simple json, don't know what i'm doing wrong. 

### ISSUE THREAD

**Issue by anastazya** [hashicorp/terraform#31504]
I'm trying to get all the deployments in an EKS cluster, and generate other resources dependent on them, however everything i tried ends up in the same error, and i canot understand what i am doing wrong. 

My terraform versions : 

```bash
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.21.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0
```

I have this external data source : 

```tf
data "external" "getpods" {
	program = ["bash","-c" ,"kubectl get deployments --namespace ${var.namespace} | awk '{if(NR>1)print $1}' | jq -R . | jq -s ."]
	query 	= {
	}
}
```

with this output 

```tf 
output "pods" {
        value = data.external.getpods.result
}
```

The program part produces the following output ( if rand directly in bash ) : 

```bash
[
  "deployment-one",
  "deployment-two",
  "deployment-three",
  "deployment-four"
]
```
However, no matter how i tried to format the output i could never get Terraform to accept the JSON.
I allaways get this errors : 

```bash
│ Error: Unexpected External Program Results
│ 
│   with data.external.getpods,
│   on cloudwatch.tf line 2, in data "external" "getpods":
│    2: 	program = ["bash","-c" ,"kubectl get deployments --namespace ${var.namespace} | awk '{if(NR>1)print $1}' | jq -R . | jq -s ."]
│ 
│ The data source received unexpected results after executing the program.
│ 
│ Program output must be a JSON encoded map of string keys and string values.
│ 
│ If the error is unclear, the output can be viewed by enabling Terraform's logging at TRACE level. Terraform documentation on logging: https://www.terraform.io/internals/debugging
│ 
│ Program: /bin/bash
│ Result
```

Thank you !!

**Comment by jbardin** [comment]
Hi @anastazya,

The [`external` data source](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) documentation states that it expects a json object, however in your case you are returning a json array. You will need to restructure this into an object for that provider to be able to use the data.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
