### ISSUE TITLE
Terraform failing to initialise due to non-existent hashicorp/example provider

### ISSUE THREAD

**Issue by tomshort** [hashicorp/terraform#31523]
### Terraform Version

```
Terraform v1.2.5
on windows_amd64
```

### Terraform Configuration Files

```
https://github.com/tomshort/CustomProvider
```

### Debug Output

```
https://gist.github.com/tomshort/d6ebe651284875f525263be97a698b34
```

### Expected Behavior
My project should install my provider **demo** which should be used to return a UUID.

### Actual Behavior

My provider **demo** should be used as it's being installed but Terraform fails to initialise because it's trying to use the provider hashicorp/example. This provider does not exist in the registry and I'm not referencing it anywhere in my project.

### Steps to Reproduce
I am only running `terraform init` for this error.

### Additional Context

I have added a terraform.rc file with a direct exclude block but this does not change the error. It's like Terraform is failing before reaching that block.

Running `terraform providers` returns this:
```
Providers required by configuration:
.
├── provider[terraform.local/local/demo] 1.0.0
└── provider[registry.terraform.io/hashicorp/example]
```

### References

@pwd9000-ML

**Comment by jbardin** [comment]
Hi @tomshort,

Your configuration has a resource called `example_server`, and since there is no `required_providers` entry for an `example` provider Terraform is attempting to find one under the default namespace. I"m not sure what you intended to have happen here, but you need to rename the resource, remove the resource, assign the correct provider, or rename the provider to match.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
