### ISSUE TITLE
New data source meta-argument `run_once` and generate token ID

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#31549]
### Current Terraform Version

```
$ terraform -v
Terraform v1.2.2
on darwin_amd64
```

### Use-cases

This issue is similar to https://github.com/hashicorp/terraform/issues/22009 but differs in proposal and expands the explanation of the broader issue.

There are situations when a data source should only be fetched once. Usually this would indicate that you required a `resource` instead of a data source. However, there are situations when the object attributes are required prior to Terraform calculating the DAG; meaning only a data source would suffice. 

For example, you can [preview the next available CIDR block](https://github.com/hashicorp/terraform-provider-aws/issues/26070) from AWS IPAM and then use that value to calculate prefixes for subnets in a VPC (`cidrsubnets()`). This becomes a problem if you allocate the previewed cidr to a VPC because the data source then gets the next available value or if the pool has no other values, it errors ~"pool is full"

Typically you can avoid this issue by `lifecycle { ignore_changes = [ <> ]}`, in the example above (ipam), i use the "previewed cidr" range in many locals to then calculate subnets and use as outputs. It is still possible to achieve behavior using `ignore_changes` but it is cumbersome and requires a lot more changes than would be necessary if `run_once = true` were allowed on data sources.

### Attempted Solutions

Using `lifecycle` arguments

Implementing my own `run_once` in a provider. [Doesnt seem possible despite the existence of a state file entry.](https://github.com/hashicorp/terraform-provider-aws/issues/26070#issuecomment-1201332299)

### Proposal

Generate an ID for data source runs and add that to the data source state file. All providers can implement a `run_once` argument and if the value is `true` and an ID exists, skip during refresh.

If there is concern (understandably) about scope creep of making the state file entry available through the data source, using an `id` should get around that concern.

### References

- https://github.com/hashicorp/terraform/issues/22009
- https://github.com/hashicorp/terraform/issues/30973

**Comment by jbardin** [comment]
Hi @drewmullen,

Thanks for filing the issue. You start my mentioning that this type of lifecycle is more appropriate for a managed resource, which I would tend to agree with. While I'm not sure if it would be more appropriate to have a separate resource for this type of lookup, or have it be an option in the individual resources requiring the data, but either case is entirely possible with the provider protocol as it exists today.

Trying to implement this sort of hybrid lifecycle is going to run into issues within the current protocol, starting with the lack of schema migration paths to decode data sources from state when the provider schema has changed. Since either the prior state nor a prior config is available for data sources, neither this proposal nor #22009 is really implementable without some larger changes to the protocol and resource lifecycles.

Regarding your example, having a managed resource lookup and reserve the next available CIDR block during the plan seems like it should work. I would suggest continuing to explore that approach, at least for the example shown here.

**Comment by drewmullen** [comment]
Thank you for the encouragement to keep looking. I was actually able to get the resource working but I haven't been able to determine the root cause. I have some pretty complex `locals {}` calculations happening in a double-nested module and I was attempting to rely on that module output for some `for_each` resource arguments in the parent root. I [refactored](https://github.com/aws-ia/terraform-aws-vpc/pull/69) some of the references to rely on variables instead of the module output and it has unblocked me to change from the data source to a resource. 

The strange part is that I cannot seem to figure out what caused the dependency error because the module is 100% locals upon locals manipulating data. 

Is there a limit on how many modules deep you can expect `outputs` from before a dependency issue can be expected? Or for that matter, how many locals data can pass through before it creates an excessive dependency list?

**Comment by drewmullen** [comment]
Im closing the issue but if you have any input on the above question, im all ears. im really at a loss as to what the root cause is.

Again, thanks for the encouragement to take another stab at it.
