### ISSUE TITLE
terraform fmt -check returns code 3 without any error message.

### ISSUE THREAD

**Issue by bortek** [hashicorp/terraform#31543]
Runnin gterraform fmt -check returns exit code 3 without printing any error message

Looking at the source code it is unclear to me what exit code 3 does. It would be not just nice but important to have some sort of error message when exiting with error code 3.

Here is the line the code where it returns
https://github.com/hashicorp/terraform/blob/main/internal/command/fmt.go#L101

Here is my output of the run

```bash
$terraform fmt -check
main.tf
terraform.tfvars

$echo $?
3

$terraform version
Terraform v1.1.7
on linux_amd64
```

**Comment by crw** [comment]
Thanks for this report!

**Comment by matheuscscp** [comment]
same here on `v1.2.6`:

```
➜  splitwiser git:(terraform) ✗ terraform fmt -check 
main.tf
➜  splitwiser git:(terraform) ✗ echo $?
3
➜  splitwiser git:(terraform) ✗ terraform version
Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.30.0
➜  splitwiser git:(terraform) ✗ 
```

**Comment by kmoe** [comment]
Thanks for the issue. An exit code of 3 is indeed an unusual exit code without (as far as I know) conventional meaning in shell scripting. It looks like it was introduced in https://github.com/hashicorp/terraform/issues/15304, with the justification that exit codes 1 and 2 were already in use for other error types.

The help text for `terraform fmt -check` is reasonable with regards to the exit codes:
```
  -check         Check if the input is formatted. Exit status will be 0 if all
                 input is properly formatted and non-zero otherwise.
```

It does not, however, make it clear what if anything is output in this case: #31553 should fix this.

Due to Terraform's v1.0 compatibility guarantees we are not able to change exit codes or machine-readable output at this stage: this command in particular is used throughout the ecosystem and its output parsed by tooling, so adding a human-readable error message here would be a breaking change.

Fortunately, shell scripting checking for all errors can just check that the exit code is non-zero, while any more sophisticated scripting (or [Go code](https://github.com/hashicorp/terraform-exec/blob/main/tfexec/fmt.go#L110)) can make use of the precise, if esoteric, exit codes.

@bortek, @matheuscscp, is this causing you any issues apart from the lack of documentation?

**Comment by matheuscscp** [comment]
@kmoe Not really, to be honest! I realized that the purpose of this command in my CI is to just tell me that I didn't run `terraform fmt` before committing my changes, so it's actually all good. Doesn't really matter what `terraform fmt` would change, I just have to remember that I have to run it before committing my changes. Thanks!

**Comment by bortek** [comment]
I will just remove fmt command from my pipeline since it does not make any contribution from my point of view. Thanks for all the input.

**Comment by matheuscscp** [comment]
> I will just remove fmt command from my pipeline since it does not make any contribution from my point of view. Thanks for all the input.

It helps you keep your Terraform files formatted according to Terraform's recommendations :shrug: Do you have specific formatting needs?
