### ISSUE TITLE
resource random_password does not honor min_upper value

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform#31567]
When using the following:
```
resource random_password example {
  length                          = 8
  min_lower                       = 1
  min_upper                       = 1
  min_numeric                     = 1
  special                         = false
}
```
The result does not produce a password with an upper case character.

Terraform version 0.14.11

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. Since you are not on a current version of terraform, I would first verify that this problem exists with the latest versions of Terraform and the provider. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
