### ISSUE TITLE
Concat multiple arrays results an unexpected result because of a sensitive value

### ISSUE THREAD

**Issue by sakirma** [hashicorp/terraform#31580]
I decided to copy paste my issue from helm provider repository to here. 

I believe this has enough information to reproduce the problem and to understand it as well.

----

### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v1.2.6 on darwin_arm64
Provider version:  Installed hashicorp/helm v2.6.0 (signed by HashiCorp)
Kubernetes version: Client Version: v1.24.3 Kustomize Version: v4.5.4 Server Version: v1.21.7
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "loki" {
  name       = "loki"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "loki-distributed"
  version    = "0.48.4"
  replace    = true

  namespace  = var.namespace
  depends_on = [kubernetes_namespace.monitoring_namespace]

  values = concat([
    var.cluster_values.in_cluster_only ? "" : file("${path.module}/loki_cloud.yaml"),

    var.cluster_values.in_cluster_only && var.cluster_values.in_cluster_only_values.use_loki_development_values ? file("${path.module}/loki_development.yaml") : "",

    var.loki_additional_values_path == "" ? "" : file(var.loki_additional_values_path),
    var.loki_storage_config
    ],
    var.loki_additional_values,
  var.loki_additional_values_sensitive)

  set {
    name  = "loki.storageConfig.gcs.bucket_name"
    value = !var.cluster_values.in_cluster_only && var.loki_storage_config == "" ? var.loki_storage_bucket_name : ""
  }

  set {
    name  = "loki.structuredConfig.ruler.storage.gcs.bucket_name"
    value = !var.cluster_values.in_cluster_only && var.loki_storage_config == "" ? var.loki_storage_bucket_name : ""
  }

}
```

Input values example
```hcl
  loki_additional_values = [file("${path.module}/values/loki.yaml")]

  loki_additional_values_sensitive = [<<-EOT
  key: "Value"
  key1: "Value1"
  EOT
  ,
  <<-EOT
    key3: "Value"
    key1: "Value1"
  EOT
  ]
```

### Debug Output

https://gist.github.com/sakirma/f9b57f99875618f9de4907f01ee3a315

### Steps to Reproduce

1. `have a helm resource that concats multiple arrays into one for the values field`
2. `terraform plan`

### Expected Behavior

I expect to see my nonsensitive values to be displayed next to sensitive values

### Actual Behavior

```hlc
resource "helm_release" "loki" {
        id                         = "loki"
        name                       = "loki"
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change.
      ~ values                     = (sensitive)
        # (27 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

As you can see since I combine all my arrays with values (sensitive and nonsensitive) into a single array. I have to do this since values input is a single array.

And then it all becomes a sensitive

### Important Factoids

No, I run this on a k8s cluster which is running on Azure

### References

I looked it up and haven't found anything

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jbardin** [comment]
Thanks for the example @sakirma,

The `concat` function will typically preserve sensitivity only on the individual values which have it. Where it cannot maintain this is when an argument collection itself is marked `sensitive`. Because that value (the collection container) is not preserved through the transformation, the mark is "inherited" by the result, making the entire value sensitive.

I have a feeling it's not possible to have collection functions like `concat` push the sensitive flag down a level into the individual values without introducing other breaking changes in existing configurations, i.e. the `concat` function should never mutate any of the collection members, but it would have to do so in order to assign a sensitive mark to them individually. We can definitely check with the upstream `cty` library about looking into this, but the current behavior seems to be correct.

Thanks!

**Comment by sakirma** [comment]
Hey @jbardin, thanks for the detailed response.

I assume you have encountered this problem before, if so how did you solve this problem?

----

I did manage to solve this problem through a hacky way, but I did not like it since it made it look like prone to bugs. I am sharing this for people who really want this to work another way.

Basicaly this:

```terraform
values = [
     jsonencode(merge(yamldecode(var.loki_additional_values))),
     jsonencode(merge(yamldecode(var.loki_additional_values_sensitive)))
   ]
```

**Comment by jbardin** [comment]
How you solve it depends on the end goal. If you just want to strip off the sensitivity of a value (which I think is what you're trying to do with `jsonencode`?), then you can just use the `nonsensitive` function.

```
concat(var.loki_additional_values, nonsensitive(var.loki_additional_values_sensitive))
```

If you want to transfer the sensitive mark from the container to the individual elements of the collection, then you can do that with a for expression:

```
concat(var.loki_additional_values, [for v in nonsensitive(var.loki_additional_values_sensitive) : sensitive(v)])
```

**Comment by jbardin** [comment]
Since the `concat` function in the upstream `cty` library does maintain the correct marks for individual items, and it would not be correct to take marks from the containers and arbitrarily add them to individual items, it appears everything is working as intended.

If you have more question, feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
