### ISSUE TITLE
module:provider can't be a variable

### ISSUE THREAD

**Issue by cdorros** [hashicorp/terraform#3160]
it seems that the "provider" argument in a module can not be set to a variable. (aws) this makes the combination of modules/multiple providers/aliases not work so well.

my use case is multiple aws accounts, regions.

perhaps this used to not be the case, as this code example shows it being used as such:
https://github.com/hashicorp/terraform/issues/451#issuecomment-119207126

thanks!

**Comment by apparentlymart** [comment]
I think you're saying the same thing as I said in #1819 here... and so I agree. :grinning:

As far as I know this has never worked since the feature first emerged in a release. It's resulted in my maintaining a separate config for each region rather than a single config with multiple providers, since having reusable modules is more important to me.

**Comment by rosmo** [comment]
I think this is a duplicate as well: #3072

**Comment by phinze** [comment]
Yep - agreed that this is something we should address. Closing to consolidate around #1819.
