### ISSUE TITLE
Have an option to suppress reading data source lines during plan and apply

### ISSUE THREAD

**Issue by tmccombs** [hashicorp/terraform#31614]
### Current Terraform Version

```
Terraform v1.2.6
on linux_amd64
```

### Use-cases

I have a lot of data sources in my configuration. Most of them `aws_iam_policy_document`. In terraform 1.2.6, when I do a plan or apply I get a ton of messages saying things like:

```
some_data_source: Reading...
some_data_source: Read complete after 0s [id=1234]
```

These messages are spammy, not very useful, and fill up my terminal. I'd like a way to suppress them.

### Attempted Solutions

I've looked at the help for terraform plan and none of the options seem to have a way to do this.

### Proposal

Add either a CLI option, or a configuration value (or both) to suppress these messages on plan and apply

**Comment by apparentlymart** [comment]
Hi @tmccombs! Thanks for sharing this.

I think this is more-or-less the same underlying concern as we were discussing over in #27214, so I'm going to close this to consolidate the discussion over there.

As always, adding a new option will be a last resort for us in this case, because we prefer to find a better compromise for the single available behavior rather than complicating both the UI and the implementation with various different options that may interact in complicated ways. Right now my favored solution to that other issue is to have Terraform delay showing any mention of a read action unless it takes more than some arbitrary-but-considered deadline, which would in particular mean that local-compute-only data sources like `aws_iam_policy_document` should never breach the deadline and should therefore never be mentioned at all, without the need for any special options. However, that issue remains open because there are various different design proposals and tradeoffs in the discussion to consider before settling on how to move forward.

Thanks again!

**Comment by tmccombs** [comment]
Sorry, I couldn't find that issue in my search for an existing issue, since it was about slightly different output. But that approach sounds fine to me.
