### ISSUE TITLE
Utilize Artifactory as source for Terraform Providers from Terraform CLI

### ISSUE THREAD

**Issue by tsporthd** [hashicorp/terraform#31624]
### Current Terraform Version

```
Terraform v1.2.5
```

### Use-cases

Ideally we would like to be able to use Artifactory to serve up our providers as opposed to using terraform.io directly.  According to their documentation this is now supported.

We would like to be able to use a file configuration or environment variable to point to our internal Artifcatory.

As far as i can tell this capability does not yet exist.

Why are we looking for this?
There are some concerns about supply chain attack so we proxy providers so that we can scan them prior to being used.

### Attempted Solutions

We have pulled the providers down directly via a custom binary but this just adds yet another step for our developers.

### Proposal

Ideally we would be able to set TERRAFORM_PROVIDER_REGISTRY environment variable and the client would simply go there to resolve plugins.

### References

- #28385

**Comment by apparentlymart** [comment]
Hi @tsporthd! Thanks for sharing this feature request.

I believe Terraform already has the necessary building blocks for Artifactory to support this, though I must admit I'm not fully up to speed with the scope of what they recently added.

Specifically, Terraform CLI can act as a client for [the provider mirror protocol](https://www.terraform.io/internals/provider-network-mirror-protocol), which is intended to allow you to explicitly select another server as a substitute for the origin registry at a particular hostname, as long as that server implements this protocol.

If Artifactory supports this protocol, then you can use [a CLI configuration file](https://www.terraform.io/cli/config/config-file) to instruct Terraform to install _all_ providers using Artifactory's provider mirror, using an [explicit installation method configuration](https://www.terraform.io/cli/config/config-file#explicit-installation-method-configuration):

```hcl
provider_installation {
  network_mirror {
    url = "https://artifactory.example.com/something/something/"
  }
}
```

Or, if you _only_ want to mirror the providers from `registry.terraform.io` and retain the default "direct" installation method for some other hostname you use, you can use a more specific configuration like this:

```hcl
provider_installation {
  network_mirror {
    url     = "https://artifactory.example.com/something/something/"
    include = ["registry.terraform.io/*/*"]
  }
  direct {
    include = ["terraform.example.com/*/*"]
  }
}
```

The above specifies that `registry.terraform.io` providers come from the mirror while `terraform.example.com` providers should be installed directly from that host's own provider registry. Any other hostname would then behave as if it had no providers at all, because this install method configuration doesn't specify how to install from any other hostname.

Even if Artifactory currently lacks native support for this protocol, we intentionally designed the protocol to be as friendly as possible to implementing it just as a set of files in a conventional static file server, and I believe Artifactory's generic repository type can behave as one and so it would hopefully be possible to use that.

Can you give this a try and let us know what your experience is? Unfortunately I don't have an Artifactory install available to me to test with, so I may have missed some details but I'd be happy to work towards a working solution with you.

Thanks!

**Comment by brandonc** [comment]
FWIW I was able to deploy a terraform repository using Artifactory Pro. It seems to implement provider mirror and provider repository protocols.

**Comment by apparentlymart** [comment]
Hi again! With @brandonc's confirmation that it already seems to work, I'm going to close this issue.

If you find that JFrog Artifactory cannot currently interact well with the Terraform provider mirror protocol, and the Artifactory team encounters blocking challenges when implementing that protocol, we'd love to hear from them about what problems they encountered in the hope of evolving the protocol to make that work more smoothly. The provider mirror protocol is our intended and only supported way for systems like Artifactory to intermediate provider installation over the network.

Thanks!
