### ISSUE TITLE
terraform plan states no change yet terraform apply destoryed all instances after subnet id change. 

### ISSUE THREAD

**Issue by rodrickbrown** [hashicorp/terraform#3163]
I made a simple subnet-id change in my configuration 

After running terraform plan I noticed the following -- "Not sure what forces new resource means"    
subnet_id:                                 "subnet-5632b421" => "subnet-38da1561" (forces new resource)

I wasn't too worried because terraform plan showed the following output --
Plan: 0 to add, 24 to change, 0 to destroy.

After running terraform apply -- TF destroyed all my EC2 instances in this resource. 
aws_instance.prod-mesos-master.0: Destroying...
aws_instance.prod-mesos-slave.2: Destroying...
aws_instance.prod-mesos-master.1: Destroying...
aws_instance.prod-mesos-master.2: Destroying...
aws_instance.prod-mesos-slave.3: Destroying...
aws_instance.prod-mesos-slave.4: Destroying...
aws_instance.prod-mesos-slave.0: Destroying...
aws_instance.prod-mesos-slave.1: Destroying...

The output when it was completed was -- 
Apply complete! Resources: 8 added, 16 changed, 8 destroyed.

I'm using Terraform v0.6.1

**Comment by semarj** [comment]
"forces new resource" means that it is going to have to delete the resource that had this attribute change and recreate it.  I agree that it is confusing that the `Plan:` line doesn't match up to the `Resources:` line.

**Comment by apparentlymart** [comment]
Yeah, it looks like the bug is that the plan summary doesn't correctly handle the "forces new resource" items.

From looking at [the code](https://github.com/hashicorp/terraform/blob/b505d15e1e3087612f88c72cad0a0d691070b35d/command/plan.go#L136) it seems like this is being done intentionally, by adding together the count that will be modified and the count that will be replaced. It looks like this would be a pretty easy change to make it behave more like the ``apply`` summary, assuming there isn't a good reason why it's the way it is now.
