### ISSUE TITLE
Allow providers to be configured using values only known post-apply

### ISSUE THREAD

**Issue by antonyfray** [hashicorp/terraform#31649]
### Current Terraform Version
```
1.2.5
```

### Use-cases
I would like to construct a Terraform module which can deploy both an [aws_eks_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster) resource along with some [Kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs)-specific resources (such as a [kubernetes_config_map](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/config_map)), through which I can easily deploy multiple pre-configured Kubernetes clusters.

The Kubernetes provider is typically configured using attributes of the aws_eks_cluster resource - see the maintainer's [example](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_examples/eks/kubernetes-config/main.tf#L9) for more info.

As things stand, if one naively applies such a configuration, then attempts to re-configure the aws_eks_cluster resource, they run into an [error](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1307). The Kubernetes provider maintainers have [clarified](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1307#issuecomment-873089000) that this is an issue with Terraform core, rather than the provider itself. To quote:

> The cause has to do with [passing an unknown value to a provider configuration block](https://www.terraform.io/docs/language/providers/configuration.html#provider-configuration-1), which is not supported in Terraform core. To quote their docs:
> ```
> You can use expressions in the values of these configuration arguments, 
> but can only reference values that are known before the configuration is applied.
> ```

I think being able to deploy both an EKS cluster and some resources on said cluster within one apply is a reasonable use case. From the above, it seems the way to achieve this would be for Terraform core to allow providers to be configured using values known post-apply. Is this something that could be feasibly implemented, or does it go against some of Terraform's core tenets?

### Attempted Solutions
N/A

### Proposal
I'm not sure of any specific configurations that might alleviate this issue, sorry!

### References
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1307#issuecomment-873089000

**Comment by jbardin** [comment]
HI @antonyfray,

Thanks for filing the issue. The problem you are describing here is precisely _because_ Terraform allows provider to be configured with values which can't be known until apply. If the provider requires a value during the plan which is not yet known, the only way to get that value is to apply the changes. This is why we have always recommended multiple separate configurations for such situations, since that is how one would apply isolated parts of the configuration in series (`-target` can also work in some situations here, but that is not a maintainable solution either).

As for the goal of managing this type of infrastructure in a single configuration, we have issue #30937 to track ideas in that area.

Thanks
