### ISSUE TITLE
Terraform modules are are not changing null values to the default

### ISSUE THREAD

**Issue by fubarhouse** [hashicorp/terraform#31679]
### Terraform Version

```shell
Terraform v1.2.7
on linux_amd64
```

### Terraform Configuration Files

`mod1/main.tf`

```terraform
variable optional_input {
  default = 5
}

output foo {
  value = var.optional_input / 5
}
```

`main.tf`

```terraform
module mod1 {
  source         = "./mod1"
  optional_input = null
}
```

### Debug Output

```
│ Error: Operation failed
│ 
│   on mod1/main.tf line 6, in output "foo":
│    6:   value = var.optional_input / 5
│     ├────────────────
│     │ var.optional_input is null
│ 
│ Error during operation: argument must not be null.
```

### Expected Behavior

Expecting the value of `optional_input` to be set to `5` because that is specified as the default value, and the output from the module should be equal to `5/5`, however the error causes the module to fail.

### Actual Behavior

The default value is not placed in-place of the value which is not specified, and the `terraform plan` stage of lifecycle fails to complete with the error described in `Debug Output`.

### Steps to Reproduce

1. Replicate file system outlined in the configuration files step.
2. `terraform init`
3. `terraform plan`

### Additional Context

This issue was previously resolved in #24142, however in the past week sometime appears to not work in the same way.

### References

#24142

**Comment by apparentlymart** [comment]
Hi @fubarhouse,

If you want Terraform to treat `null` in the same way as leaving the argument entirely unset then you can activate that behavior with the additional `nullable` argument in your variable declaration:

```hcl
variable "optional_input" {
  default  = 5
  nullable = false
}
```

When you set `nullable = false`, Terraform will guarantee that inside the module the value of this variable will never be directly `null`. It achieves that by substituting the default value in that case, which I think matches the expected behavior you described.

Can you try that and let me know if it achieves the behavior you were hoping for?

Ideally `nullable = false` would be the default, but so far it's an opt-in behavior because the evolution of the language is constrained by [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises). A future edition of the Terraform language might change this default in exchange for some broader kinda of "whole-module" opt-in, but we have no current plans to make such a change because we'd need to accumulate a sufficient number of potential language improvements in order to overcome the high cost of introducing a not-backward-compatible new language edition.

**Comment by fubarhouse** [comment]
Perfect - thanks for the response.
Thank you for bringing my attention to this as well - it has allowed me to mitigate what I'm dealing with.
