### ISSUE TITLE
Allow lifecycle replace_triggered_by to trigger on any string change

### ISSUE THREAD

**Issue by mihok** [hashicorp/terraform#31685]
### Terraform Version

```shell
Terraform v1.2.8
on darwin_arm64
```

### Use Cases

Modularization of different components of our system and the Prevention being able to pass a resource into another module to reference it in the lifecyclee replace_triggered_by field.

If an underlying resource (needed by another resource) is trying to be replaced, the other resource should be replaced as well otherwise `terraform apply` cycles until it times out.

### Attempted Solutions

Tried following the documentation https://www.terraform.io/language/meta-arguments/lifecycle#replace_triggered_by but our system is split into module components and the resource id we try to pass in as a variable does not get recognized as a resource spitting out the following error:

│ Error: Invalid replace_triggered_by expression
│ 
│   on modules/services/services.tf line 93, in resource "aws_ecs_service" "api_service":
│   93:       var.subnet
│ 
│ Missing resource reference in replace_triggered_by expression.

### Proposal

Allow the replace_triggered_by list to allow any string value, if its changed, the resource is triggered to be replaced.

**Comment by apparentlymart** [comment]
Hi @mihok! Thanks for sharing this use-case.

The design of `replace_triggered_by` is to associate one side effect (replacing all of the instances of a resource) with some other side-effect Terraform can plan. Terraform doesn't allow referring to variables in this context because variables are side-effect-free objects: they exist only in memory during a Terraform plan, and there's no record of them after a run is complete.

However, you can achieve the effect you described by using an additional resource whose definition causes it to be updated or replaced in whatever situation you need to replace this object. If there isn't already some existing resource that meets that criteria, you could potentially introduce a [`null_resource`](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) resource (a resource type belonging to the `hashicorp/null` provider) which does nothing _except_ plan to replace itself when its `triggers` change, like this:

```hcl
resource "null_resource" "example" {
  triggers = {
    subnet = var.subnet
  }
}

resource "aws_ecs_service" "api_service" {
  # ...

  lifecycle {
    replace_triggered_by = null_resource.example
  }
}
```

The design of `null_resource` is to save the `triggers` value during initial creation and then for each subsequent plan to compare the `triggers` in the desired state (the configuration) with the `triggers` saved in the previous run's final state. If there are any differences, that resource type will tell Terraform Core that the resource instance must be replaced, thereby creating a suitable side-effect for `replace_triggered_by` to use. The key here is that a _resource_ has a prior state to compare with to decide if any action is needed, whereas an input variable alone does not.

**Comment by mihok** [comment]
Thanks for the feedback @apparentlymart !

Does this also apply to a net new null_resource? It seems like my plan suggests that its creating a null_resource, and the service needing to be replaced simply has a `updated in-place`

**Comment by apparentlymart** [comment]
Yes, the rule for `replace_triggered_by` is that it will trigger a replacement if any of the resources listed have any kind of change pending, including initial creation.

**Comment by jbardin** [comment]
Hi @mihok,

In order for the `replace_triggered_by` meta-argument to trigger replacement, there must be a _change_ in a referenced resource. The reason it does not trigger on the first apply is the same reason that variable values cannot be referenced directly, the prior value must first be stored somewhere in order to detect a change.

Currently the most convenient way to store an arbitrary value in a managed resource is using the `null_resource`, but that resource must first be created to store a value which can be changed. `replace_triggered_by` does not force replacement from an initial "create" operation, because then it would not be possible to modify a configuration to add these resources _without_ forcing their replacement.

**Comment by mihok** [comment]
Awesome that makes a lot of sense. Closing the feature request!
