### ISSUE TITLE
Why fail if nonsensitive is redundant?

### ISSUE THREAD

**Issue by sidekick-eimantas** [hashicorp/terraform#31693]
### Terraform Version

```shell
Terraform v1.2.7
on darwin_arm64
```

### Use Cases

N/A

### Attempted Solutions

N/A

### Proposal

This should not crap terraform out. At best, it should be a warning.

```sh
│ Error: Invalid function argument
│ 
│   on iam-user-test.tf line 129, in output "temp-password":
│  129:   value = nonsensitive(aws_iam_user_login_profile.user.password)
│     ├────────────────
│     │ aws_iam_user_login_profile.user.password is "abc"
│ 
│ Invalid value for "value" parameter: the given value is not sensitive, so
│ this call is redundant.
```

**Comment by crw** [comment]
Thanks for the request!

**Comment by kmoe** [comment]
Can you describe the impact of this error on your dev process? When working with sensitive attributes, we tend to err on the side of errors rather than warnings, as it were.

**Comment by Nuru** [comment]
This is really irritating, as I am working with incomplete documentation and I have an object with a sensitive member. I cannot see the non-sensitive members no matter what I do:

<details><summary>Click to reveal</summary>

I try to output the whole object, using nonsensitive:

```
│ Error: Invalid function argument
│ 
│   on main.tf line 104, in output "token":
│  104:   value     = nonsensitive(teleport_provision_token.test)
│     ├────────────────
│     │ while calling nonsensitive(value)
│     │ teleport_provision_token.test is object with 6 attributes
│ 
│ Invalid value for "value" parameter: the given value is not sensitive, so this call is redundant.
```

OK, so I take out the `nonsensitive()`:

```
│ Error: Output refers to sensitive values
│ 
│   on main.tf line 103:
│  103: output "token" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output
│ containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
```

So I am out of luck either way. I cannot output the full object no mater what. 

</details>

**Comment by vi-credo** [comment]
I can describe one use case that I faced just recently. I'm working on a module that creates among other things multiple [aws_lb_listener_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule). Module accepts an optional settings for [conditional](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#condition-blocks) settings. At the end I want to expose some information from those listeners, such as host header, and I use some for loops and so one to merge them nicely in one variable and expose to module users. Since some parameters are optional one listener may have secret information, while another does not, which triggers the error message pointed above about whole variable containing sensitive information. In ideal world I would expect to `nonsensitive()` function to accept complex variable and remove marking in all nested levels. I understand it is supposed to work as a guard, but in my case I definitely know I'm not exposing any sensitive information, yet I hit a wall due to limitation explained [here](https://github.com/hashicorp/terraform/issues/28222#issuecomment-816819118).

I hope I was able to clearly describe the use case. If not, I can try to add some code snippets.

**Comment by briceburg** [comment]
If it helps, I currently workaround this issue by wrapping the value with sensitive(), e.g. `nonsensitive(sensitive("foo"))`

working example:

```terraform
output "images" {
  value = flatten([
    for v in aws_ecs_task_definition.this : [
      for c in nonsensitive(sensitive(jsondecode(v.container_definitions))) : c.image
    ]
  ])
}
```

this was the only way I could figure to reliably output the `images`  from ecs task definitions where the container input may or may not contain sensitive values.

**Comment by dverzolla** [comment]
> If it helps, I currently workaround this issue by wrapping the value with sensitive(), e.g. `nonsensitive(sensitive("foo"))`
> 
> working example:
> 
> ```terraform
> output "images" {
>   value = flatten([
>     for v in aws_ecs_task_definition.this : [
>       for c in nonsensitive(sensitive(jsondecode(v.container_definitions))) : c.image
>     ]
>   ])
> }
> ```
> 
> this was the only way I could figure to reliably output the `images` from ecs task definitions where the container input may or may not contain sensitive values.

Tha's helped a lot.

I came here from google looking for a solution for using `nonsensitive()` and `one()` together, once terraform was throwing the error `nonsensitive is redundant`, and this workaround worked.

**Comment by joaocc** [comment]
While the workaround is very smart and very useful (thanks!), we still have an underlying issue that causes a lot of pain and time, but without an obvious benefit (as far as we could understand). 
The use cases described here and in https://github.com/hashicorp/terraform/issues/28222 are very common once we start wanting to address large cases with structured data, where returning separate elements for sensitive and non-sensitive data forces code to be less clear.
In my opinion, it would still be very valuable to either have this issue fixed (ie, allowing application of "nonsensitive()" to any data) or some rationale on why that would not be possible, especially now that a couple of workarounds exist.
Thanks!

**Comment by joaocc** [comment]
Trying to understand a bit more about this, the documentation offers a rationale:

https://developer.hashicorp.com/terraform/language/functions/nonsensitive
> nonsensitive will return an error if you pass a value that isn't marked as sensitive, because such a call would be redundant and potentially confusing or misleading to a future maintainer of your module.

However it seems from the sheer number of people complaining directly and indirectly, that this potential headache-saving is actually interfering with developer decisions of what should and should not be sensitive, and actively preventing more maintainable terraform architectures.

Despite being a TF noob, and not having much hope of this being fixed in the short time, I will be proposing a PR to address this, as previous PRs (like https://github.com/hashicorp/terraform/pull/28326 ) didn't seem to have gone far enough to address this situation.

Feedback and fixes are very welcomed.

**Comment by kmoe** [comment]
Thanks for all your comments. From v1.7.0, redundant use of `nonsensitive()` is no longer an error. Closed in https://github.com/hashicorp/terraform/pull/33856.
