### ISSUE TITLE
Terraform 1.3 module_variable_optional_attrs experiment support

### ISSUE THREAD

**Issue by jyoder-deloitte** [hashicorp/terraform#31692]
### Terraform Version

```shell
Terraform v1.3.0-alpha20220817
on darwin_amd64
```

### Use Cases

Migrating existing modules that make use of `module_variable_optional_attrs` to the new behavior requires a hard upgrade from the 0.15-1.2 syntax to the new 1.3 syntax.  Depending on how modules are wired together it may require upgrading ALL the modules in an infrastructure at one time for those of us who have made heavy use of this (handy) feature.

It would be nice if there were a way to ease in to the new syntax instead of having to convert everything all at once.

### Attempted Solutions

There are no workarounds for backward compatibility:
```
│ Error: Experiment has concluded
│
│   on k8s-cluster-roles.tf line 3, in terraform:
│    3:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The
│ final feature corresponding to this experiment differs from the
│ experimental form and is available in the Terraform language from Terraform
│ v1.3.0 onwards.
```

### Proposal

1.3 concludes the `module_variable_optional_attrs` experiment and errors when you use the old experiment flag, plus it removes the `defaults()` function that was available as part of that experiment.

I propose that 1.3 be a bridge release where it emits a deprecation warning about the experiment concluding, and that it retain the `defaults()` function ONLY when the `module_variable_optional_attrs` experiment flag is enabled.  The old behavior of allowing only one argument to `optional` should probably be preserved as well if the flag is enabled.

Starting in 1.4 the feature should be removed and the `defaults` function removed.

I realize the whole point of hiding this behind the `experiments` flag was to prevent the need for a deprecation period, but this experiment has been available (unchanged) since April 2021 and it is an extremely handy way to solve a lot of complex problems.

**Comment by apparentlymart** [comment]
Hi @jyoder-deloitte! Thanks for raising this.

We previously discussed this in #31355 and our decision from that issue stands: any module which uses optional attributes inherently requires using Terraform v1.4 or later, and so teams should wait to use it until they are ready to require Terraform v1.4 for all users of the module.

Upgrading from Terraform v1.3 to Terraform v1.4 should be easy because it continues to be subject to [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/language/v1-compatibility-promises). If that isn't true in some particular situation -- e.g. if you encounter a bug when upgrading -- please open an issue for that and we'll prioritize fixing that problem so that it's easy to upgrade to gain access to this new feature.

Thanks again!

**Comment by jyoder-deloitte** [comment]
While I do understand the reasoning, the `optional` experiment was part of every Terraform release for 18 months.  I'd be willing to bet that when 1.3 is released you will see a flood of very unhappy users complaining about no way to bridge the gap between the 1.2 `optional` syntax and 1.3 syntax.

**Comment by ericb-summit** [comment]
Yep, just hit it, fortunately found this issue.

Thing is, up till now, we could always use the latest tf in our scripts ensuring we get updates (especially security fixes).  But now with this breaking change, and no possible workaround, we can't possibly rework tens of thousands of lines of tf, so we'll just have to version lock everything to 1.2.

Which is unequivocally worse, because who knows when we will actually choose to revisit this and do the upgrade.

**Comment by apparentlymart** [comment]
Hi all,

I'm sorry that your reliance on the experiment in prior releases has caused you challenges while upgrading. We had hoped that the loud message pre-warning that the experiment was subject to change in future releases would be sufficient warning, but also understand that this feature was useful enough to tempt folks to take that risk anyway.

We need the ability to release features that are not yet subject to compatibility promises to gather feedback, and this was an example of that. In response to this situation, we have changed our policy for experimental features so that in future they will never appear in stable releases and will instead be available only in alpha releases intended for those who are explicitly aiming to try out a feature and give feedback on it _without using it in production_. This will therefore not happen again in future unless you intentionally choose to use an alpha release in production, which of course we would recommend against strongly.

**Comment by userbradley** [comment]
@ericb-summit A quick means to lock all the versions is to use [tfupdate](https://github.com/minamijoyo/tfupdate) and just give it a version, in the root directory of your repos (or repo if you're on a mono-repo)

```bash
tfupdate provider google-beta -v "1.2.x" -r ./
```

**Comment by ericb-summit** [comment]
Thanks apparentlymart  and @userbradley .

> ```shell
> tfupdate provider google-beta -v "1.2.x" -r ./
> ```

Sorry, @userbradley  but to clarify: are you saying I could use a >= 1.3 client but lock my project to use the 1.2 syntax so terraform init --upgrade would be OK even with a 1.3 client?

**Comment by userbradley** [comment]
@ericb-summit sorry let me clarify.

It was in response to:

> we'll just have to version lock everything to 1.2.

Using tfupdate provides a simple way to bulk change the provider locking. 

It may be best that you provider version lock everything, and the use a tool like [tfswitch](https://tfswitch.warrensbox.com) 

As far as using 1.2:

> terraform init --upgrade would be OK even with a 1.3 client?

No, as it will give a version mismatch, as the infra is only going to accept `1.2` opposed to `1.3`

Take a look at tfswitch, it provides a nice way to switch terraform versions without pain.

Let me know if you have any questions

**Comment by sapslaj** [comment]
Heyya @apparentlymart. My team is feeling some pain from this being an error and not a warning so I wanted to mention our use case.

We're using Terraform Cloud as a backend and making use of the remote execution mode. Each workspace has a pinned version of Terraform that is designed and tested to work with the accompanying code. The issue stems from our CI system which uses a single version (usually the latest) of Terraform to trigger the apply for all stacks. This means that for a workspace that is still set to use 1.2 or another version, we get an error when running `terraform init` since it seems the locally running Terraform in CI (which got upgraded to 1.3) detects the experiment declaration and immediately throws an error. 

```
$ terraform version   
Terraform v1.3.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/tfe v0.36.1

$ terraform init   
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Experiment has concluded
│ 
│   on modules/module-tfv1.2/main.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs]
│ 
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment
│ differs from the experimental form and is available in the Terraform language from Terraform v1.3.0 onwards.
╵
```

Downgrading the version used to trigger the apply to 1.2 causes anything new that's actually using optional attributes in 1.3 (with the accompanying 1.3 version configured for the Terraform Cloud workspace) throws an error during init since optional attributes are still an experiment in 1.2. 

```
$ terraform version            
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/tfe v0.36.1

Your version of Terraform is out of date! The latest version
is 1.3.0. You can update by downloading from https://www.terraform.io/downloads.html

$ terraform init       
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Optional object type attributes are experimental
│ 
│   on modules/module-tfv1.3/variables.tf line 8:
│    8: variable "environments" {
│ 
│ This feature is currently an opt-in experiment, subject to change in future releases based on feedback.
│ 
│ Activate the feature for this module by adding module_variable_optional_attrs to the list of active experiments.
```

So even though only a handful of modules and workspaces utilize optional attributes we're stuck at 1.2 or upgrade everything all at once to 1.3 unless we can figure something else out. We're at close to 200 Terraform Cloud workspaces so that's quite the endeavor to test that all of those work on 1.3 all at the same time.

**Comment by kaihendry** [comment]
I don't understand how to get unblocked here:

```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Experiment has concluded
│
│   on .terraform/modules/eks_observability_accelerator.operator.cert_manager/modules/irsa/versions.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental form and is available in the Terraform language from Terraform v1.3.0 onwards.
╵

╷
│ Error: Experiment has concluded
│
│   on .terraform/modules/workloads_infra.helm_addon/modules/irsa/versions.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental form and is available in the Terraform language from Terraform v1.3.0 onwards.
╵

╷
│ Error: Experiment has concluded
│
│   on .terraform/modules/eks_observability_accelerator.operator.cert_manager/modules/kubernetes-addons/helm-addon/versions.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental form and is available in the Terraform language from Terraform v1.3.0 onwards.
╵

╷
│ Error: Experiment has concluded
│
│   on .terraform/modules/workloads_infra.helm_addon/modules/kubernetes-addons/helm-addon/versions.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental form and is available in the Terraform language from Terraform v1.3.0 onwards.
```

**Comment by userbradley** [comment]
@kaihendry Remove experimental feature flag and set the module to use `1.3` - Which is not usual, as we usually don't specify provider blocks in modules (which was removed some time ago)

![image](https://user-images.githubusercontent.com/41597815/192741987-a1cf8e2b-6502-42fa-a2cf-37d1f85858e4.png)

**Comment by ericb-summit** [comment]
The new syntax for declaring defaults is much better.
