### ISSUE TITLE
Instructions to update for Linux only give you 1.2.7 - the latest is 1.2.8

### ISSUE THREAD

**Issue by williamohara** [hashicorp/terraform#31690]
### Terraform Version

```shell
Terraform v1.2.7
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

`this is not relevant to this issue`

### Debug Output

there is not a bug

### Expected Behavior

I expect to have the latest version installed - 

### Actual Behavior

the version installed is one step behind

### Steps to Reproduce

follow instructions here 

https://www.terraform.io/downloads for **Linux**

notice that it only installs 1.2.7

**Comment by apparentlymart** [comment]
Hi @williamohara! Thanks for reporting this.

When I look at the downloads page you linked I see that it includes links to download Terraform v1.2.8, rather than v1.2.7.

I'm guessing that you're talking about one of the "Package Manager" instructions instead of the "Linux Binary Download" section. Can you mention which of the sets of instructions you followed? It would help if you could share exactly the commands you ran, just to narrow down which of those package managers isn't working correctly and what exactly isn't working about it.

Thanks!

**Comment by williamohara** [comment]
package manager -- yes this one

![image](https://user-images.githubusercontent.com/17223014/186737189-b2bb6737-60db-4f5e-9b93-0794291d8741.png)

**Comment by williamohara** [comment]
i use WSL Linux and I make sure to run all my commands from the Linux OS- this is the only option for me :)

**Comment by apparentlymart** [comment]
Okay, thanks! So my conclusion from this is that it's [the APT repository](https://www.terraform.io/cli/install/apt) that is lacking a package for v1.2.8.

I'll pass that on to the team that is responsible for the APT repository. Thanks!

**Comment by alisdair** [comment]
Thanks again for the report. The issue with the package repository has been resolved, and running `sudo apt update && sudo apt install terraform` should upgrade to 1.2.8.
