### ISSUE TITLE
Boolean Coversion when passing variables and locals not working.

### ISSUE THREAD

**Issue by smurphy-mastercard** [hashicorp/terraform#31708]
### Terraform Version

```shell
terraform --version
Terraform v1.2.8
on linux_amd64
```

### Terraform Configuration Files

```locals {
  access = var.account_name == "account1"  ? "read" : false
  enable = local.access != "false"
}

variable "account_name" {
  default = "account2"
}

output "access" {
  value = local.access
}

output "enable" {
  value = local.enable
}
```

### Debug Output

https://gist.github.com/smurphy-mastercard/dd06557bd9567c1673433abd92df309d

### Expected Behavior

Ouput "access" should have string value "read"

### Actual Behavior

Output "access" has string value "false"

### Steps to Reproduce

Use provided code in a test.tf file
terraform apply

**Comment by jbardin** [comment]
Hi @smurphy-mastercard,

This can be a bit confusing at times, but here's a rundown of each expression to help clarify things

```
var.account_name == "account1"  ? "read" : false
```

This will evaluate to `"false"`, because `var.account_name` is `"account2"`, which is not equal to `"account1"`. Because he expression must result in a single type, Terraform must convert the boolean `false` value to a string to match the `"read"` value type.

```
enable = local.access != "false"
```

This evaluates to `false`, because `local.access` is the string value `"false"`.


In general you should avoid ever trying to compare to boolean literals which can fail unexpectedly when faced with an implicit type conversion elsewhere. It is also a good idea to try and avoid conversion between string and boolean values, because while we must maintain that behavior for backwards compatibility, it can often result in hard to debug problems, though again, avoiding the boolean comparisons mostly avoid the problem entirely.

Thanks
