### ISSUE TITLE
WSL2 terminal running VSCode, first terraform init would fail, consequent terraform init works. If run WSL2 outside of VSCode, terraform init always works. 

### ISSUE THREAD

**Issue by jye-aviatrix** [hashicorp/terraform#31727]
### Terraform Version

```shell
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.28.0
+ provider registry.terraform.io/hashicorp/http v3.1.0
```

### Terraform Configuration Files

```terraform
module "vgw-strongwan-site-to-site-vpn" {
  source  = "jye-aviatrix/vgw-strongwan-site-to-site-vpn/aws"
  version = "1.0.0"
  key_name  = "ec2-key-pair"
}

output "strongwan" {
  value = module.vgw-strongwan-site-to-site-vpn
}
```

### Debug Output

https://gist.github.com/jye-aviatrix/87aad49e53795860b25dd74d4a421c9b

### Expected Behavior

terraform init would work in first try

### Actual Behavior

WSL2 terminal running VSCode, first terraform init would fail, consequent terraform init works. If run WSL2 outside of VSCode, terraform init always works. 

### Steps to Reproduce

terraform init

### Additional Context

VSCode Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

WSL2 version:
5.10.102.1-microsoft-standard-WSL2

**Comment by kmoe** [comment]
Interesting report, thank you. It looks like the error is thrown by git itself:
```
/usr/bin/git exited with -1: Cloning into '.terraform/modules/vgw-strongwan-site-to-site-vpn'...
│ BUG: refs/files-backend.c:2956: initial ref transaction called with existing refs
```

Please therefore do the following in order to determine which of the various pieces are going wrong here.
1. Try running `terraform init` the same way inside WSL, but with a different module (not `vgw-strongwan-site-to-site-vpn`).
2. Try the following command inside WSL instead of `terraform init`:  `git clone https://github.com/jye-aviatrix/terraform-aws-vgw-strongwan-site-to-site-vpn . && git checkout 1.0.0`

Please also supply your version of `git`.

In the meantime, some workarounds that could conceivably fix this:
 - Update to latest version of `git` if not already using
 - Clear the module cache at `.terraform/modules/`

I'm curious as to why the "Error: Failed to download module" is printing twice. That's the only thing here that suggests to me this may be a bug in Terraform Core - otherwise the likely suspects are git, go-getter, and the peculiarities of a VSCode-on-WSL-on-Windows setup.

**Comment by crw** [comment]
Hi @jye-aviatrix, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
