### ISSUE TITLE
Error with list(object) variable type in terraform version 0.12 ; Error: "panic: inconsistent list element types (cty.Object(map[string]cty.Type{""}) then cty.Object(map[string]cty.Type{""})"

### ISSUE THREAD

**Issue by alfysalim** [hashicorp/terraform#31745]
### Terraform Version

```shell
terraform version 0.12
```

### Terraform Configuration Files

variables.tf
---------------------------
variable "stage_action" {
    type = list(object({
    stage_name       = string
    name             = string
    category         = string
    owner            = string
    provider         = string
    version          = string
    output_artifacts = any
    input_artifacts  = any
    configuration = any
    }))
    default = [{
      stage_name = ""
      category = ""
      configuration = {}
      input_artifacts = []
      name = ""
      output_artifacts = [] 
      owner = ""
      provider = ""
      version = ""
    },
    {
      stage_name = ""
      category = ""
      configuration = {}
      input_artifacts = []
      name = ""
      output_artifacts = [] 
      owner = ""
      provider = ""
      version = ""
    }]
}

### Debug Output

NA

### Expected Behavior

Should have validated successfully on executing "terraform validate"

### Actual Behavior

(https://user-images.githubusercontent.com/96526802/188582709-93e97c98-36f7-404c-b0c1-477471932017.png)

### Steps to Reproduce

terraform init
terraform validate

**Comment by jbardin** [comment]
Hi @alfysalim,

Terraform v0.12 is quite old and no longer being developed. The given example does not panic with a current version of Terraform, so it appears the issue has been fixed in more recent release.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
