### ISSUE TITLE
etcd & aws flaw

### ISSUE THREAD

**Issue by wsq2025** [hashicorp/terraform#31741]
### Terraform Version

```shell
there are two flaws found in the stable version 1.2.8:
1、etcd: https://nvd.nist.gov/vuln/detail/CVE-2018-1098
2、aws: https://nvd.nist.gov/vuln/detail/CVE-2020-8911

then I find new beta version has removed etcd component, but aws-sdk V1 is still used.
so please tell me which version can i use and what's the plan do you want to resolve in next stable version
```

### Terraform Configuration Files

1

### Debug Output

1

### Expected Behavior

1

### Actual Behavior

1

### Steps to Reproduce

1

**Comment by jbardin** [comment]
Hi @wsq2025,

Thanks for filing the issue. The shown CVEs are not relevant to the library usage within Terraform, since we neither use the aws crypto package referenced (though that appears to be an older version anyway) and Terraform never made use of Redis server internally.

If you have any security concerns, feel free to email [security@hashicorp.com](mailto:security@hashicorp.com). If you have further questions, please use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
