### ISSUE TITLE
`tostring(null)` produces null

### ISSUE THREAD

**Issue by ghostsquad** [hashicorp/terraform#31754]
### Terraform Version

```shell
Terraform v1.2.8
on darwin_amd64
```
```


### Terraform Configuration Files

```terraform
tostring(null)
```

### Debug Output

n/a

### Expected Behavior

`tostring(null)` produces an empty string `""` when null is provided. 

### Actual Behavior

`tostring(null)` produces `null`. Null doesn't work in some functions that expect strings, like `join`. This function feels like it does the wrong thing when it comes to how it handles null.

### Steps to Reproduce

tostring(null)

**Comment by jbardin** [comment]
Hi @ghostsquad,

The `tostring` function converts the _type_ of the `null` value to be a null string rather than be dynamically typed, and as the documentation points out, it would really only be used to normalize types returned in module outputs. Most of the time this conversion should not be necessary. Converting a `null` to an empty string would change the value entirely, and would also be a breaking change to the Terraform language.

If you want to conditionally convert a null string to an empty string, you can use a conditional expression like so:
```
local.s == null ? "" : local.s
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
