### ISSUE TITLE
Terraform ignores dependencies/order of operations for resources that are modified in place

### ISSUE THREAD

**Issue by vladimir-avinkin** [hashicorp/terraform#31769]
### Terraform Version

```shell
terraform version
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/hashicups v0.3.1
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

### Terraform Configuration Files

https://github.com/vladimir-avinkin/terraform-dependency-order-repro

### Debug Output

https://gist.github.com/vladimir-avinkin/f948eb7d4917e2c590d4d3172f70e144

### Expected Behavior

Terraform should respect the order of operations for dependent resources, in this case, null_resource.null[1] should have been destroyed AFTER modifying hashicups_order.cup, not before

### Actual Behavior

Despite the explicit and explicit dependency terraform destroyed null_resource.null[1] before modifying hashicups_order.cup

### Steps to Reproduce

Clone the repository, ensure that you have the required tools that are listed in README.md, then run:
  ```bash
  docker-compose up -d
  # make sure you wait for the service to be up before the next command
  curl -X POST localhost:19090/signup -d '{"username":"education", "password":"test123"}'
  terraform init
  # after that command terraform should successfully create three resources 
  terraform apply
  # now run apply with fewer dependencies
  terraform apply -var 'resource_count=1'
  ```
  
In that last apply you will see that terraform deletes `null_resource.null[1]` before modifying `hashicups_order.cups` despite
`hashicups_order.cups` implicit and explicit dependencies

### References

- I believe the same bug is described in that issue #23169

**Comment by jbardin** [comment]
Hi @vladimir-avinkin,

The example given is not missing any dependencies, the order of operations is well-defined and is being executing as they are defined. If it helps, think about the situation where `null_resource.null[1]` were being replaced, in which case `hashicups_order.cups` could not be updated until after `null_resource.null[1]` was both destroyed and re-created. The case where the resource is only being destroyed must follow the same overall oder of operations. If you want to invert this ordering, you can create `null_resource.null` using `create_before_destroy`, which will ensure the create and update operations happen _before_ the destroy operations.

Since this does not represent a bug in Terraform, I'm going to close the issue. If you have more questions, feel free to continue the conversation in the original forum thread.

Thanks!

**Comment by jbardin** [comment]
The overall order of resource actions must be consistent, regardless of whether the resource is being replaced, only deleted, or only updated. This is especially important in large configurations where it would be very confusing for users if removing vs replacing a resource subtly changed the overall order of operations causing other failures. Terraform must pick some order to use by default, and none of the choices can work for every possible configuration, so we always start from delete-then-create.

Also, once you build out more complex graphs of dependencies, there are very few topological orders which can create a valid dependency graph at all. It's tempting to assume that the simple case where you want to swap the order of operations is valid, but once that is combined into arbitrarily large graphs of changes, cycles appear making the proposed order invalid. I made some notes to help explain the basics here if you're interested: https://github.com/hashicorp/terraform/blob/main/docs/destroying.md.

**Comment by vladimir-avinkin** [comment]
Thank you for spending your time explaining that to me, I can't honestly say that I understood this document completely, so feel free to ignore my ramblings if I missed something entirely :)

But again, as I said the problem with your scenario
> If it helps, think about the situation where null_resource.null[1] were being replaced, in which case hashicups_order.cups could not be updated until after null_resource.null[1] was both destroyed and re-created.

Is not actually the order itself, but because we treat `replace (delete+create) + update` as three operations, when it's actually 4 `update + replace (delete +create)  + update`.

I can't see how the order of operations would break at all in any scenario if we just update the dependent resource twice.

**Comment by jbardin** [comment]
You cannot update the `hashicups_order` before the `null_resource` create, because the `hashicups_order` depends on the `null_resource` . Perhaps you were thinking of something like `delete -> update -> create -> update`, but that still leaves us with the problem that we need a single plan of how we are going to execute the `hashicups_order`, but there are 2 different `update` actions here for the same resource instance.

Besides the fact that the architecture of Terraform is not designed around being able to handle multiple updates like this, we also have to contend with providers (and hence the implementations of each resource) would ever expect to have multiple updates to a single resource plan or apply operation. Say for instance the dependency was used in a required attribute on the resource. The application of that first update plan would be invalid as we are breaking the invariant of giving the provider that required attribute from the configuration -- only once the dependency has been fully resolved do we have the necessary information for the update. So even if Terraform were re-imagined to have multiple actions planned per resource, in this instance we still could not insert the preliminary update because it would cause the provider to fail.
