### ISSUE TITLE
Can Terraform AWS ELB provider support configuring the SSL Cipher Suite?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#3176]
I am not sure AWS provides API endpoints or attributes for this (I spent some time looking through their docs to confirm), but I also see no mention of the cipher suite in the Terraform codebase.

I am assuming this is not possible, but I would like to be sure: Is it possible for the ELB provider to support configuring the SSL Cipher Suite used by an ELB?

**Comment by gtmtech** [comment]
+1  - definitely needed, and definitely a terraform omission.

Especially because the default ELB ciphersuite is no longer recommended to be used, and so if you want to run a compliant/secure ELB, you should be doing a custom one anyway.

Sadly this is something that terraform lacks, but cloudformation has

Do you know if anyone is scheduled to look at this @catsby ?

**Comment by anthcor** [comment]
:+1:

**Comment by catsby** [comment]
Hey @gtmtech – no, can't say anyone is looking into this. I'm not sure how it's done, is this done through Load Balancer Policy types? 

I don't believe I'll be getting to this soon, but would love to hear more on how it's done via the API

**Comment by catsby** [comment]
Looks like this is implemented in #5637! We'll review and get that in if possible.
Thanks!

**Comment by stack72** [comment]
Closed via the rebased PR in #8084

**Comment by cappellem** [comment]
+1 :)
