### ISSUE TITLE
VSphere Provider bug with depends_on and disk.

### ISSUE THREAD

**Issue by pmanno** [hashicorp/terraform#31760]
### Terraform Version

```shell
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/vsphere v2.2.0
```

### Terraform Configuration Files

https://github.com/pmanno/terraform_vsphere_bug

### Debug Output

https://github.com/pmanno/terraform_vsphere_bug/blob/main/_terraform/logs/tf_apply.log

### Expected Behavior

Build the bind server, then build the consul nodes.

### Actual Behavior

terraform apply crashes with error
```
Error: disk.0: size for disk "disk0": required option not set
with module.consul.vsphere_virtual_machine.vm[2],
 on ../../../../../modules/vsphere_consul/main.tf line 69, in resource "vsphere_virtual_machine" "vm":
 69: resource "vsphere_virtual_machine" "vm"
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @pmanno,

Sorry you're having trouble here. There's a lot going on in these modules, and it's going to be difficult to sort out what the actual problem is with so many moving parts. You also mention that if you hard-code the problematic field, you get another error, but it's unclear what that other error is exactly. 

If you want the virtual machines to be automatically built in series, you need to feed some computed attribute from the first VM into the second. If that's not possible, piping an output from the first module into the second and using `depends_on` only for that specific value should be enough to give you the ordering you're looking for. Adding `depends_on` to the entire module is also causing the data sources to be unknown during the plan, which is exacerbating the problems here.

The error about the unset `size` attribute looks like a problem with the provider, but it would require narrowing down the example to determine whether this is a problem with the data source producing an incorrect value, or the virtual machine validating it incorrectly. 

We use GitHub issues for tracking bugs and enhancements in Terraform, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. If it turns out that there's a problem with the provider, there's a link to their issue tracker from the [registry page](https://registry.terraform.io/providers/hashicorp/vsphere/latest).

Thanks!

**Comment by pmanno** [comment]
@jbardin Thanks for the guidance on things to try to get this to work.  I could run this again as-is and get you the exact error that I saw post-hardcode disk size, if you like.  It absolutely said it was a problem with the vsphere provider that I should report.  I didn't include the exact error in this case because I wanted to just present a single issue at a time... but if that information would be helpful, I'm happy to update the case with that if you like.

**Comment by jbardin** [comment]
If you can create an error which indicates there is a problem with the provider, it would be helpful to submit that in the provider's issue tracker. Since this does not appear to be an issue with the Terraform CLI, the community forums are a better location to find users with experience using various providers to try and sort out the initial configuration issues.

Thanks!
