### ISSUE TITLE
StateFunc not applied to nested attributes

### ISSUE THREAD

**Issue by fmaylinch** [hashicorp/terraform#31771]
### Terraform Version

```shell
Terraform v1.2.8
on darwin_amd64
```

### Terraform Configuration Files

```terraform
resource my_resource r1 {
  entries {
    key = "key from tf"
    value = "value from tf"
  }
}
```

### Terraform Provider Schema

```go
func myResource() *schema.Resource {
	return &schema.Resource{
		...
		Schema: map[string]*schema.Schema{
			"entries": {
				Type:     schema.TypeList,
				Required: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:     schema.TypeString,
							Required: true,
						},
						"value": {
							Type:      schema.TypeString,
							StateFunc: func(i interface{}) string {
								return "value from StateFunc"
							},
						},
					},
				},
			}
```

### Expected Behavior

State should contain `"value from StateFunc"`:

```json
    {
      "mode": "managed",
      "type": "my_resource",
      "name": "r1",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "entries": [
              {
                "key": "key from tf",
                "value": "value from StateFunc"
              }
            ],
```

### Actual Behavior

State contains `"value from tf"`:

```json
    {
      "mode": "managed",
      "type": "my_resource",
      "name": "r1",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "entries": [
              {
                "key": "key from tf",
                "value": "value from tf"
              }
            ],
```

### Steps to Reproduce

terraform init
terraform apply

### References

This seems to be related, but it talks about sets: https://github.com/hashicorp/terraform/issues/19318

**Comment by jbardin** [comment]
Hi @fmaylinch,

The SDK you are using here is not part of the Terraform CLI, and is developed as a separate project [here](https://github.com/hashicorp/terraform-plugin-sdk). That version of the SDK however is not longer actively developed, and behavioral quirks like this often need to remain frozen for backwards compatibility. You can probably find a few open issues there about the `StateFunc`, since using that like you have shown will cause incorrect behavior in the provider. The provider is not allowed to alter a configuration value, so it's even possible that the SDK _is_ applying `StateFunc`, but the provider protocol is correcting the problem to create a valid plan. There May be `WARN` entries in the core logs about inconsistencies like this too.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the SDK community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) where there are more people ready to help.

Thanks!

**Comment by fmaylinch** [comment]
Thank you. I will add a relevant issue in the SDK project:
https://github.com/hashicorp/terraform-plugin-sdk/issues/160
