### ISSUE TITLE
`import` with `remote` backend should be imported remotely

### ISSUE THREAD

**Issue by willhughes-au** [hashicorp/terraform#31770]
### Terraform Version

```shell
1.2.9
```

### Use Cases

When we manage resources through Terraform Cloud, often the API keys, secrets, and network access are only available to Terraform cloud. 

This makes running `terraform import <resource>` difficult, as then the user needs to grab copies of secrets, modify access controls, and other similar things to be able to import. 

### Attempted Solutions

At the moment manual arounds are painful, and often involve exposing, or risking the exposure of secrets.  eg in commandline histories, clipboards, etc.

### Proposal

Given all planning and applying runs remotely, import should do so as well.

**Comment by kitarp29** [comment]
Hey @willhughes-au @crw 
If this is still open I am interested in taking it up.
Could you please assign it to me??

**Comment by apparentlymart** [comment]
Hi @kitarp29! Thanks for the interest in working on this.

Unfortunately in this case the bulk of the work to make this possible would be in Terraform Cloud, which is not open source. Terraform CLI cannot run remotely any operation that the Terraform Cloud API doesn't support.

Once the Terraform Cloud teams have a design for how this will work in the API then the client part of it will be open source in this repository, but typically the Terraform Cloud teams will update the Cloud integration client here as part of implementing a new feature, so I expect the client side of this would be implemented internally too.

We can certainly track this feature request here as a placeholder, but since this is describing a Terraform Cloud feature I would suggest also requesting it via the HashiCorp support channel, because this repository is primarily monitored by the teams which work on the open source Terraform Core and Terraform CLI components, rather than Terraform Cloud.

Thanks!

**Comment by crw** [comment]
@willhughes-au, thanks for the request. As per the above comment, I'd recommend filing this through our support channels as well: https://support.hashicorp.com/hc/en-us/requests/new -- this will put the request into the commercial support channel, which has its own prioritization. Thanks!

**Comment by apparentlymart** [comment]
Hi all!

Terraform v1.5 introduced a new way to import using a normal Terraform plan and apply with [extra information in the configuration](https://developer.hashicorp.com/terraform/language/import) to tell Terraform that it should plan to adopt an existing remote object rather than plan to create a new object.

This new feature is the intended way to perform import operations with Terraform Cloud. `terraform import` does not follow a standard plan+apply flow and so cannot work within Terraform Cloud. Therefore I'm going to close this, because even though what's implemented is not exactly what was proposed it is the intended solution to the use-case that this request implied.

Thanks again for sharing this use-case!

**Comment by apparentlymart** [comment]
Hi @willhughes-au,

Support for dynamic `id` arguments in `import` blocks is coming in the forthcoming v1.6.0, which is currently in its prerelease period.
