### ISSUE TITLE
Crash from bad config file with function call

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#3179]
Relevant config line:
```hcl
  public_port = "element(${cloudstack_firewall.services-lb.rule.*.ports.*}, 0)"
```

Crash log: https://gist.github.com/glenjamin/e885c5835a324ff3d877

**Comment by glenjamin** [comment]
After fixing my syntax to not completely crash, I noticed this use of splat doesn't actually work either.

**Comment by svanharmelen** [comment]
@glenjamin just looked at this, and I think we should consider it a bug that TF crashed instead of just reporting an error even if gave it some unexpected input.

@phinze you agree?

**Comment by phinze** [comment]
Yep definitely. Adding `crash` label as well.

**Comment by phinze** [comment]
Since we landed the new HCL parser, this no longer causes a crash. :confetti_ball: 

As for the behavior of that "multi-splat" reference - that's not something we're likely to support anytime soon. I'd recommend reworking your config a bit so you can reference the values you need from input variables. You're welcome to open a fresh issue if you'd like to spec out a feature request though. :+1:
