### ISSUE TITLE
Missing aws_iam_server_certificate.certificate_chain caused diff mismatch

### ISSUE THREAD

**Issue by rafaelmagu** [hashicorp/terraform#3180]
Not really a bug, but I spent half an hour going around in circles trying to understand why things weren't working.

If you load a server certificate using `aws_iam_server_certificate` and you have an SSL signed by an authority that provides a CA bundle, be sure to include `certificate_chain`. Otherwise you'll see errors such as:

```
Error applying plan:

1 error(s) occurred:

* aws_iam_server_certificate.domain-com: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

A note on the documentation pages would be awesome.

**Comment by apparentlymart** [comment]
The fact that this surfaced as a "diffs didn't match" error points to a bug in the resource implementation... I'm not sure if it could do anything better than just returning a more intelligible error message, but it should at least do that.

**Comment by mitchellh** [comment]
Hey there. It has been a long time since there has been activity on this issue (our fault, sorry!), and the last known repro was against a very old version of Terraform. It is possible this issue still exists but we've addressed dozens of issues with the same type of error message in the past year. Could you please try again on the latest version and let us know if it doesn't work? The easiest way would be to simply open a new issue. Thanks!
