### ISSUE TITLE
Condition for empty map returns false when map is empty

### ISSUE THREAD

**Issue by tocw** [hashicorp/terraform#31803]
### Terraform Version

```shell
Terraform v1.2.9
on linux_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

https://gist.github.com/tocw/c9278b46b06a149558b10700ff6d31d7

### Expected Behavior

test = true

### Actual Behavior

test = false

### Steps to Reproduce

```
variable "map" {
  type = map(string)
  default = {}
}

output "test" {
  value = var.map == {}
}
```
```
terraform plan
```

**Comment by alisdair** [comment]
Thanks for reporting this.

The output value of `false` is the expected behaviour, as the two values under comparison are not equal. They have different types:

```
> type(var.map)
map(string)
> type({})
object({})
```

As you can see, the `{}` syntax produces a value of type `object({})`, i.e. an object with no attributes. This is convertible to a `map(string)`, so you can use it as the default value, but an equality test will notice the different types and return false.

To check if a given map (or other collection) is empty, use the `length` function:

```terraform
output "test" {
  value = length(var.map) == 0
}
```

We document this in [the "Equality Operators" section of the expressions documentation](https://www.terraform.io/language/expressions/operators#equality-operators):

> Comparisons between structural types may produce surprising results if you are not sure about the types of each of the arguments. For example, `var.list == []` may seem like it would return true if `var.list` were an empty `list`, but `[]` actually builds a value of type `tuple([])` and so the two values can never match. In this situation it's often clearer to write `length(var.list) == 0` instead.
