### ISSUE TITLE
Terraform functions to process domains

### ISSUE THREAD

**Issue by sidekick-eimantas** [hashicorp/terraform#31817]
### Terraform Version

```shell
Terraform v1.2.7
on darwin_arm64
```

### Use Cases

For example, I want to validate that a given variable is a root domain

### Attempted Solutions

String manipulation using existing string manipulation functions

### Proposal

Some functions to process domain names would be great

**Comment by crw** [comment]
Thank for this enhancement request!

**Comment by apparentlymart** [comment]
Hi @sidekick-eimantas! Indeed, thanks for sharing this feature request.

I assume that when you say "root domain" you are imagining something which can calculate the following example results:

| Input | Is Root Domain? |
|--|--|
| `example.com` | `true` |
| `example.co.uk` | `true` |
| `foo.example.com` | `false` |
| `foo.example.co.uk` | `false` |

Is that correct?

If so, I think what you are asking about is essentially a function to query [the Public Suffix List](https://publicsuffix.org/), which is a big database which records all of the domain suffixes that allow for various different entities to separately register subdomains within them.

This sort of database lookup isn't typically a good candidate for a built-in function in Terraform, because that would mean including the entire database inside the Terraform CLI executable even though it would, I expect, be used by only a small subset of module authors.

I think this use-case is a better candidate for a separate provider plugin, which could export a data source for querying the public suffix list. That plugin could include the public suffix list as part of its own packages, which means that only those who actually need it would pay the cost of downloading the package containing it.

It also means that updates to that plugin could be released independently of Terraform CLI, which means that it could (assuming a sufficiently-motivated maintainer, or some sort of automation) update promptly whenever the upstream database has new entries. Terraform CLI's release rhythm is relatively slow and so we don't typically include constantly-changing external databases as part of the core system.

The good news about providers is that anyone can write a provider plugin and publish it to the public [Terraform Registry](https://registry.terraform.io/). If you are interested, you can see the [Plugin Development](https://www.terraform.io/plugin) section of the documentation for information on how provider plugins work in Terraform. As noted above, in this case I'm imagining a provider which only exports one or two _data sources_, since the public suffix list is read-only and therefore there isn't really anything to represent using a managed resource type.

Since this particular functionality isn't a good fit for Terraform Core as a built-in function, and since we use this repository only to represent changes to Terraform CLI or Terraform Core, I'm going to close this issue. Thanks again!
