### ISSUE TITLE
Support `TypeLinkedList` schema type

### ISSUE THREAD

**Issue by AlexPykavy** [hashicorp/terraform#31811]
### Terraform Version

```shell
﻿Terraform v1.2.8
on windows_amd64
```

### Use Cases

Produce a neat and easy-to-review plan in the case of an insert in the middle of collection. Current `TypeList` will shift all subsequent elements starting from `i + 1` if we add an element at position `i`.

Let's consider some examples. Imagine that we have a resource `my_ip_whitelist` containing a list of IP addresses `ip_address`:
```
resource "my_ip_whitelist" "example" {
  name = "example"

  ip_address {
    address = "10.0.0.1"
    description = "Example IP address"
  }

  ip_address {
    address = "10.0.0.8"
    description = "Example IP address"
  }

  ip_address {
    address = "10.0.0.12"
    description = "Example IP address"
  }
}
```

Now we need to add `10.0.0.3` address to the whitelist and we place it between the first and the second, like:
```
resource "my_ip_whitelist" "example" {
  name = "example"

  ip_address {
    address = "10.0.0.1"
    description = "Example IP address"
  }

  # just added IP address
  ip_address {
    address = "10.0.0.3"
    description = "Example IP address"
  }

  ip_address {
    address = "10.0.0.8"
    description = "Example IP address"
  }

  ip_address {
    address = "10.0.0.12"
    description = "Example IP address"
  }
}
```

Now, let's look at the plan we are getting (It's not the real Terraform output. I just tried to imitate it):
- When using `TypeList`:
```
~ resource "my_ip_whitelist" "example" {
    # (1 unchanged attribute hidden)

    # (1 unchanged block hidden)

    ~ ip_address {
        ~ address = "10.0.0.8" -> "10.0.0.3"
        # (1 unchanged attribute hidden)
      }
  
    ~ ip_address {
        ~ address = "10.0.0.12" -> "10.0.0.8"
        # (1 unchanged attribute hidden)
      }

    + ip_address {
        + address = "10.0.0.12"
        + description = "Example IP address"
      }
}
```
- What I would like to see when using `TypeLinkedList`:
```
~ resource "my_ip_whitelist" "example" {
    # (1 unchanged attribute hidden)

    ip_address {
      address = "10.0.0.1"
      description = "Example IP address"
    }

    + ip_address {
        + address = "10.0.0.3"
        + description = "Example IP address"
      }
  
    ip_address {
      address = "10.0.0.8"
      description = "Example IP address"
    }

    # (1 unchanged block hidden)
}
```

### Attempted Solutions

No.

### Proposal

We can try to leverage https://pkg.go.dev/container/list collection underneath.

### References

Related issues:
- https://github.com/hashicorp/terraform-provider-azurerm/issues/18114

**Comment by jbardin** [comment]
Hi @AlexPykavy,

Thanks for the request. A linked list is a particular _implementation_ of an ordered data structure, and could in theory be used to back the internal list type, however that is only an implementation detail, and does not affect the semantics of an ordered collection of values. Since most collections of values in Terraform are relatively small, changing from an array-based structure to a linked-list structure would make no appreciable difference other than an increase in code complexity. Terraform would still need to use index-based addressing to communicate the location of each element, and the end result would be the same.

The output you are proposing is more or less a change in the diff renderer, where it could detect insertions in list backed blocks, and display only the new element rather than all elements which have a change in index. This however would pose a problem when those attribute are referenced elsewhere in the configuration, since their index is still changing, and the user needs to trace back those references to the correct index. Eliding the indexes makes this more difficult, however future versions of the diff renderer may be able to better compress these changes into a more readable format.

Provider may also chose to use other data structures like a map or set if the order of elements are important. Using an unordered data structure would then not cause later indexes to change when inserting individual elements in the set. Newer providers are also often choosing to prefer attribute-style access over blocks, which will make this output more structured and easier to interpret for new users of Terraform.

Since changing the memory layout of the list data structure is not something we intend to do, I'm going to close the issue. If you have more questions, feel free to start a discussion in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!
