### ISSUE TITLE
Getting error on terraform init: The "artifactory" backend is not supported in Terraform v1.3 or later

### ISSUE THREAD

**Issue by relgames** [hashicorp/terraform#31837]
### Terraform Version

```shell
Terraform v1.3.0
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 3.81.0"
    }
  }

  backend "artifactory" {
    url = "https://internal.host.com/artifactory"
    repo = "rnd-terraform"
    subpath = "tf-agents"
  }
}
```

### Debug Output

https://gist.github.com/relgames/6e91cb0da37c524d5d70e333629de2d4

### Expected Behavior

`terraform init` should work, like it worked in v1.0.11

### Actual Behavior

`terraform init` outputs an error

### Steps to Reproduce

1. `terraform init`

**Comment by bootswithdefer** [comment]
According to the release notes, it was removed.  https://github.com/hashicorp/terraform/pull/31711
https://github.com/hashicorp/terraform/blob/v1.3/CHANGELOG.md

**Comment by jbardin** [comment]
Sorry about the confusion @relgames, yes, v1.3 removed the deprecated `artifactory` backend. Since this does not represent a bug in Terraform, I'm going to close the issue. If you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
