### ISSUE TITLE
Change Terraform Cloud UI to show each error message by resource, rather than dumping error messages at the top of the apply section

### ISSUE THREAD

**Issue by rileygriffith** [hashicorp/terraform#31839]
### Terraform Version

```shell
N/A
```

### Use Cases

Purely cosmetic change with Terraform Cloud UI. In instances where your apply has many errors (>10), all of these error messages get dumped at the top of the apply section

For example:
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/56943883/191611730-0fcd058c-b205-463d-a7d6-c08ddb83a340.png">

### Attempted Solutions

N/A, purely a suggestion to improve the cloud UI

### Proposal

I am suggesting that these error messages be relocated to the individual item, so that when you click the drop down on the particular resource showing an error status after apply, it also gives the error message
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/56943883/191611972-a909c656-20a6-4fd0-89e4-1d1fbae3923f.png">

This seems like it would be relatively simple to implement from a frontend standpoint

**Comment by apparentlymart** [comment]
Hi @rileygriffith! Thanks for sharing this feedback.

I've labelled this as a Cloud issue so that the Terraform Cloud teams might see it, but I would suggest also sharing this request via [HashiCorp Support](https://support.hashicorp.com/) because that is the primary channel through which the Terraform Cloud teams expect to receive feedback.

(This repository is primarily for the Terraform open source project, and so it's primarily monitored by the team which maintains Terraform Core.)
