### ISSUE TITLE
InvalidAMIID.Malformed

### ISSUE THREAD

**Issue by sunilbennur** [hashicorp/terraform#31854]
### Terraform Version

```shell
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.31.0
```

### Terraform Configuration Files

variable "ami" {
   type        = string
   description = "Ubuntu AMI ID in N. Virginia Region"
   default     = "ami-09208e69ff3feb1db"
}

variable "instance_type" {
   type        = string
   description = "Instance type"
   default     = "t2.micro"
}

variable "name_tag" {
   type        = string
   description = "Name of the EC2 instance"
   default     = "My EC2 Instance"

---------------------------------------------------------------------------------main.tf.......................................................
resource "aws_instance" "my_vm" {
  ami               = "var.ami" //Ubuntu AMI
  instance_type     = "var.type"

  tags = {
    Name = "var.name_tag",
  }
}

### Debug Output

TF_LOG=trace

### Expected Behavior

aws_instance.my_vm: Creating...
╷
│ Error: creating EC2 Instance: InvalidAMIID.Malformed: Invalid id: "var.ami" (expecting "ami-...")
│ 	status code: 400, request id: f78fcaa8-c3ec-4e55-9ec7-b816f420e7e5
│ 
│   with aws_instance.my_vm,
│   on main.tf line 1, in resource "aws_instance" "my_vm":
│    1: resource "aws_instance" "my_vm" {
│ 

### Actual Behavior

aws_instance.my_vm: Creating...
╷
│ Error: creating EC2 Instance: InvalidAMIID.Malformed: Invalid id: "var.ami" (expecting "ami-...")
│ 	status code: 400, request id: f78fcaa8-c3ec-4e55-9ec7-b816f420e7e5
│ 
│   with aws_instance.my_vm,
│   on main.tf line 1, in resource "aws_instance" "my_vm":
│    1: resource "aws_instance" "my_vm" {
│ 

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

In your case you have surround the `var.ami` variable reference in quotes, passing it as a string to the resource configuration and leading to the error `Invalid id: "var.ami"`

Thanks!
