### ISSUE TITLE
Question concerning experiments = [module_variable_optional_attrs]

### ISSUE THREAD

**Issue by manfred0191** [hashicorp/terraform#31867]
### Terraform Version

```shell
1.3.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```
terraform init

### Debug Output

*

### Expected Behavior

*

### Actual Behavior

*

### Steps to Reproduce

terraform init

### Additional Context

Did I get it right, that if I am currently running on 1.2.9 and I will be waiting for 1.4.x I can use the code again that I am using now?

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

In direct answer to your question: no, the optional attributes experiment is concluded. If you are using the `defaults` function in 1.2.9, you must update your configuration to upgrade to 1.3 or later releases.
