### ISSUE TITLE
Destroy operations are not idempotent

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#31893]
### Terraform Version

```shell
v1.2.8
```

### Terraform Configuration Files

any resource or data source from at least the kubernetes or AWS provider. 

### Debug Output

...

### Expected Behavior

Destroy operations should be idempotent for data sources and resources alike. Otherwise, they are non-deterministic altogether. I started noticing the issue with some providers such as with data sources in the AWS providers and regular resources with the Kubernetes providers. After thinking for a while and reporting the issues on the specific providers' repos, I decided to raise it up in core because this pattern seems to be prevalent and the Terraform Plugin SDK nor the Terraform Framework SDK seem to encourage or facilitate testing for idempotent destroy operations. 

### Actual Behavior

destroy operations fail when remote resources do not exist. See: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1822 and https://github.com/hashicorp/terraform-provider-aws/issues/26228 

### Steps to Reproduce

1. terraform init
2. terraform apply 
3. manually delete remote resource either through AWS Console/CLI/API or GCP Console/CLI/API.
4. terraform destroy

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/26228
* https://github.com/hashicorp/terraform-provider-kubernetes/issues/1822
* https://github.com/hashicorp/terraform/pull/27408

**Comment by jbardin** [comment]
Hi @c4milo,

Thanks for filing the issue. From the description it doesn't sound like you're asking for Terraform to make the operation idempotent, because the operation has yet to be carried out, rather you are asking if Terraform would ignore errors when asked to destroy resources that do not exist.

The actual behavior here is up to the providers to implement. Terraform has no way of knowing what it means for a particular resource to exist or not, or whether a destroy operation succeeded or not. In most cases if a resource no longer exists, the destroy operation will start by calling `ReadResource` and the provider will return a `null` value. If the most recent value is `null`, indicating that the resource no longer exists, then there is nothing for Terraform to do and it will not call `ApplyResourceChange` to destroy the resource. 

Do you have specific examples and logs which show otherwise?

Thanks!

**Comment by jbardin** [comment]
@c4milo,

I think realized you may be asking specifically about the `ReadResource` behavior rather than the actual action of deleting the instance, in which case the issue is whether a provider returns an error or not with a missing resource. How to handle that error is entirely up to the provider, but we can see some guidance in the latest docs. In docs for the new provider plugin framework, the [Read method](https://www.terraform.io/plugin/framework/resources#read) has an example showing how to handle a missing resource, where it catches a 404 and returns `null` early (by calling `RemoveResource`) with no error. Depending on the situation, a warning or log message mage be applicable, but this has been the standard practice for most resources. The procedure would be a bit different for legacy providers, but the same logic would apply.

**Comment by bflad** [comment]
Just to additionally note, it is also up to providers whether the Delete method (in either sdk or framework) applies similar logic for ignoring "not found" errors by returning success instead of that class of error on destroy operations as well.

When I was working on the AWS provider awhile ago, we started implementing "disappears" acceptance testing for verifying that the Read functionality had verification of "not found" error handling to suggest recreating the resource instead of returning that error. The most recent incarnation of that documentation can be found here: https://hashicorp.github.io/terraform-provider-aws/running-and-writing-acceptance-tests/#disappears-acceptance-tests

Something similar may also be conceivable for testing the Delete behavior as well using a second `resource.TestStep` with  `Destroy: true` enabled. It might be a little trickier in that case to coerce the testing framework to delete the resource prior to running the destroy operation though. I'm guessing the best place to have that sort of discussion might be the [Plugin Development section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43).

**Comment by c4milo** [comment]
@bflad won me to it 🥇. 
 
@jbardin, thanks for such a prompt answer. I also was leaning towards kicking this ball to the providers but then I thought that this issue really effects the Terraform brand because the user experience ends up being inconsistent. It would be ideal if Terraform core somehow helps providers to be fully idempotent, either by making it easier or possible for providers to test idempotent destroy operations. Agreed with @bflad on that maybe the best venue for this discussion is the plugin framework SDK.

**Comment by jbardin** [comment]
Yes, the closest point of control here would be the SDK rather than core, and testing ideas can start from there. It doesn't sounds like there's anything to do on this side right now, so I'll close out this issue.

Thanks!
