### ISSUE TITLE
Cannot create an AWS Route53 weighted record with weight = 0

### ISSUE THREAD

**Issue by elblivion** [hashicorp/terraform#3189]
Terraform version: 0.6.3

When creating a `aws_route53_record` setting `weight = 0` I'm getting the following error, on initial resource creation only (updating weight to 0 is fine):

```
Error applying plan:

1 error(s) occurred:

* aws_route53_record.cdn_elb: InvalidInput: Invalid request
	status code: 400, request id: [956b20c7-5626-11e5-b075-33b12ae4ae3f]
```

I've tracked this down to an edge case with the `GetOk` function (https://github.com/hashicorp/terraform/blob/21d18ae2c94ae9e8b0c9964ad5af5563182fa0f0/helper/schema/resource_data.go#L77-L93), in this case this is returning a false value as the second result and the `Weight` parameter is dropped from the resource creation, thus providing an incomplete request.

I've built Terraform with the latest master skipping this check and it is able to create the record with `weight = 0` without errors. But since this is a pretty fundamental function and I don't know enough Go or Terraform I can't think of a proper solution right now - maybe identifying if the value has been passed as a variable or not like the `Compute` boolean?

Thanks,
Anthony

**Comment by radeksimko** [comment]
Reproduced,
I believe this is really caused by the nature of `schema.ResourceData.GetOk()` which returns `false` in cases where the value is considered _"Zero"_ - in case of `TypeInt` it's `0`, for `TypeString` it's `""`, for `TypeBool` it's `false` etc. ...

I would frankly not expect this behaviour from `GetOk`, but I may not know the background & consequences of that implementation, so there probably is a reason.

That said, there might be a workaround for this specific case - AFAIK (read as _"I was not checking docs thoroughly"_) `set_identifier` is field only provided for weighted records, so we could be taking `weight` in all cases where `GetOk("set_identifier")` is `true`.

**Comment by elblivion** [comment]
That works for me, I'm happy to submit a PR if this is an acceptable solution.

**Comment by radeksimko** [comment]
Sure, feel free to submit PR, we can fix this specific case.

I'm just curious about all other resources that could be affected by this `GetOk` behaviour - i.e. places where empty string or zero are valid values, but I'm not sure there's any easy way to find these.

**Comment by elblivion** [comment]
Fixed in https://github.com/hashicorp/terraform/issues/3196

**Comment by Zordrak** [comment]
Issue present in 0.6.12/13 - Can this be re-opened?

**Comment by radeksimko** [comment]
@Zordrak if you can provide a repro case - i.e. piece of code that can help us reproducing the issue, then I'd be happy to either reopen this or (more likely) open a new issue.
