### ISSUE TITLE
core: Allow offline validation of provider configuration

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#3190]
So far this was an invisible nature of `plan` for me until https://github.com/hashicorp/terraform/commit/975e1a6c2c7af386060da504b82d14e19b1deeab 

I'm looking for a way to do local, offline validation, mostly for running `terraform plan -refresh=false` in CI, which I use purely for syntax check.

I was wondering if validation that calls API (typically credentials validation, like in AWS) should be separated into a different function, that would be only called when it's really necessary (refresh, apply, destroy).

The current workaround is either to generate IAM credentials that will have permission to only run `iam.getuser` to get its own account ID (in cases where `allowed_account_ids` or `forbidden_account_ids` are defined).

I know there is a separate issue somewhere discussing syntax validation, but I'm thinking that `plan` should optionally work offline as well.

**Comment by josephholsten** [comment]
@radeksimko could use your :eyes: on #5004, which is just a rebased #3783

**Comment by apparentlymart** [comment]
I think this use-case was mostly addressed in #3783, and it's currently possible to use `terraform validate` to do this sort of offline validation with some caveats. (In particular, you need to run `terraform init` with some special options to get providers and modules installed without also initializing the backend.)

This will get more robust in the next release when we switch to the new configuration language interpreter which is able to do catch more problems via static validation (type mismatches, etc) than the current one can.

Since we're pretty close here and the remaining work is already covered by other discussions, I'm going to close this out.
