### ISSUE TITLE
"terraform" object's attributes

### ISSUE THREAD

**Issue by ousmix** [hashicorp/terraform#31900]
### Terraform Version

```shell
1.1.9
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

I know its NOT here where i should post this, but i dont find the right category. Its a simple question.

i'm using TFE and i want to store somes values related to the RunTask in variables. Here is the data i'm lookin for:

1- TFE Organisation
2- TFE Workspace (there is an object i call and it works, i use terraform.workspace)
3- User/Member that ran the task

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### Additional Context

N/A

### References

N/A

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, this repo is only monitored by a few core maintainers. It's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. If you are a Terraform Enterprise customer, you can use the usual support channels for assistance.

Thanks!
