### ISSUE TITLE
yamldecode fails to parse multiline strings in the lists

### ISSUE THREAD

**Issue by minherz** [hashicorp/terraform#31933]
### Terraform Version

```shell
1.3.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~> 1.3"
}

locals {
    file_content = file("test.yaml")
    parsed_content = yamldecode(file("test.yaml"))
}

output "file_content" {
    value = local.file_content
}

output "parsed_content" {
    value = local.parsed_content
}
```

### Debug Output

https://gist.github.com/minherz/377c3825c257a0db97f7c77e77fbe56a

### Expected Behavior
```
file_content = <<EOT
field1: "testing string"
field2:
- field3: testing string

EOT
parsed_content = {
  "field1" = "testing string"
  "field2" = [
    {
      "field3" = "testing string"
    },
  ]
}
```

### Actual Behavior
```
╷
│ Error: Error in function call
│ 
│   on main.tf line 7, in locals:
│    7:     parsed_content = yamldecode(file("test.yaml"))
│     ├────────────────
│     │ while calling yamldecode(src)
│ 
│ Call to function "yamldecode" failed: on line 5, column 1: could not find expected ':'.
```

### Steps to Reproduce

terraform init
terraform apply -auto-approve

### Additional Context

A file named `test.yaml` with the following content should be in the same directory as the Terraform configuration.

```yaml
field1: "testing string"
field2:
- field3: |
  testing string
```

**Comment by minherz** [comment]
When the `test.yaml` file defines multiline string not as a part of the array i.e.
```yaml
field1: "testing string"
field2: |
  testing string
```
the function works as expected.

**Comment by jbardin** [comment]
Hi @minherz,

Thanks for filing the issue. I haven't looked up the relevant spec yet, but the yaml you've provided is not valid in any of the usual yaml decoders I've checked. are you certain you can use a nested literal scalar like this, and if so, could you point to the specification?

Thanks!

**Comment by apparentlymart** [comment]
My understanding of the [block scalar styles](https://yaml.org/spec/1.2.2/#81-block-scalar-styles) is that the subsequent lines after the `|` marker must be intended relative to the previous line, so that the YAML parser can use the subsequent _dedent_ ("out-dent", if you prefer) to detect the end of the scalar content and return to block mapping context.

In other words, I think you need at least one space before `testing string` to make this valid YAML:

```yaml
field1: "testing string"
field2:
- field3: |
    testing string
```

Without that indent, the YAML spec calls for the parser to understand `testing string` as the next pair in the mapping, which would require it to be followed by a colon and then a value, just as the error message seems to suggest.

**Comment by minherz** [comment]
My apologies, I wrongly attributed the misbehavior. After retesting, I can confirm that the additional indentation for the content of the literal block scalar did the work.
