### ISSUE TITLE
 The value of the 'if' clause must not be null

### ISSUE THREAD

**Issue by nORKy54** [hashicorp/terraform#31942]
### Terraform Version

```shell
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

### Terraform Configuration Files

```terraform

# module1/main.tf

variable obj {
  type = map(object({
      hv_network                 = string
      ipv4                            = optional(string)
      default                        = optional(bool)
  }))
}

locals {
  my_var = one([ for v in var.obj : v if try(v.default, false) ])
}

resource "null_resource" "module1" {
}

# main.tf
module "test1" {
  source = "./module1"

  obj = { "nic1" : { "hv_network": "n1", "ipv4": "10.0.0.1" }, "nics2":  { "hv_network": "n2", "ipv4": "192.168.0.1" }}
}
```

### Debug Output

https://gist.github.com/nORKy54/860f5eae7453f9590770e82a9f1779fa

### Expected Behavior

No error

### Actual Behavior

```shell
Error: Invalid 'for' condition
│
│   on module1/main.tf line 10, in locals:
│   10:   my_var = one([ for v in var.obj : v if try(v.default, false) ])
│     ├────────────────
│     │ v.default is null
│
│ The value of the 'if' clause must not be null.
`

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

I don't understand the error. v.default is not null. Try must catch the error and return false.
If I start the terraform console and do the same test, there is no error, try return false.

### References

_No response_

**Comment by alisdair** [comment]
Thanks for the report.

You note that `v.default` is not `null`, but from your configuration it appears that it must be `null`. When you declare an object attribute as `optional`, if it is not present in the input to the variable, Terraform assigns it a `null` value. As a result, using `try` here is not appropriate.

Instead of using the local variable to assign defaults, you can use the second argument to `optional`. For example:

```hcl
variable obj {
  type = map(object({
      hv_network                 = string
      ipv4                            = optional(string)
      default                        = optional(bool, false)
  }))
}
```

Alternatively, if you need to apply different defaults in different circumstances, you can use [the `coalesce` function](https://www.terraform.io/language/functions/coalesce), which returns its first non-null argument.

Hope this helps! Unless I've misunderstood your report, this doesn't represent a bug in Terraform, so I'm going to close this issue.

**Comment by nORKy54** [comment]
oh, ok ! I'm sorry for the open issue.
Thanks you for your answer, I understand now. You can close it.
