### ISSUE TITLE
terraform --version hangs on macos

### ISSUE THREAD

**Issue by le4ker** [hashicorp/terraform#31973]
### Terraform Version

```shell
1.1.9
```

### Terraform Configuration Files

```terraform
N/A
```

### Debug Output

N/A

### Expected Behavior

`terraform -v` should print the version and exit.

### Actual Behavior

Prints

```
Terraform v1.1.9
on darwin_arm64
```

and hangs.

### Steps to Reproduce

Run `terraform --version` on darwin arm64.

### Additional Context

Dtrace output can be found [here](https://ufile.io/d8132r14).

### References

Found a similar (not the same) issue [here](https://github.com/hashicorp/terraform/issues/24375).

**Comment by jbardin** [comment]
Hi @le4ker,

Thanks for filing the issue. These problems are often caused by non-standard DNS configurations on the host. The current releases of Terraform are linked to the system resolver on `darwin_arm64`, can you verify the issue with `v1.3.2` or later?

Thanks!

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
