### ISSUE TITLE
Check if an AMI / provider image exists during terraform plan

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#3198]
While using `terraform plan` and `terraform apply`, with a sizeable environment (60+ resources), the thought came to me: _could terraform check that an image exists at a provider during terraform plan execution, rather than wait/hit the error during `terraform apply`?

I imagine this might not even be possible on all providers, but at least worth investigating?

**Comment by apparentlymart** [comment]
Interesting thought... this sort of check doesn't really fit cleanly into the current Terraform resource lifecycle AFAIK, since the diffing process is not exposed as something the provider can customize as long as it's using the ``helper/schema`` helper (which most are, including the AWS provider).

But it would definitely be nice to have the ability to include additional checks in the planning process. There have been other cases like your example where I've made a mistake in config and only found out part-way through the ``apply`` process; having these checks happen earlier would improve my confidence in the outcome of ``apply`` after a successful ``plan``.

**Comment by catsby** [comment]
Hey friends – It's been a _long_ time since we looked here, but Terraform has since gotten the addition of data source (largely from @apparentlymart himself), and here you can use the `aws_ami` datasource to accomplish this task:

- https://www.terraform.io/docs/providers/aws/d/ami.html

Thanks!
