### ISSUE TITLE
Failed to query available provider packages

### ISSUE THREAD

**Issue by issam-naouali** [hashicorp/terraform#32009]
### Terraform Version

```shell
required_version = ">= 1.1.0"
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azure: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/azure
│
│ Did you intend to use terraform-providers/azure? If so, you must specify that source address in each module which requires that provider. To see which modules are 
│ currently depending on hashicorp/azure, run the following command:
│     terraform providers
╵

### Expected Behavior

![image](https://user-images.githubusercontent.com/101259130/195734538-cae674f6-1515-4142-94a8-8f82856c1c55.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/101259130/195734494-40f50273-ff17-4066-a67f-0566ac757bd4.png)

### Steps to Reproduce

- Installing hashicorp/azurerm v3.26.0...
- Installed hashicorp/azurerm v3.26.0 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages

**Comment by jbardin** [comment]
Hi @issam-naouali,

The error indicates that you are looking for a provider called `registry.terraform.io/hashicorp/azure`, which does not not exists, and is why it cannot be found. You didn't not provide any of the requested configuration, but I would inspect that for a typo in a resource or `required_providers` block.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
