### ISSUE TITLE
Unneeded update-in-place for sensitive values when crossing providers.

### ISSUE THREAD

**Issue by palmobar** [hashicorp/terraform#32000]
### Terraform Version

```shell
1.3.1
```

### Terraform Configuration Files

```terraform
data "aws_secretsmanager_secret_version" "creds" {
  secret_id = "something"
}

locals {
  slack_api_token   = sensitive(jsondecode(data.aws_secretsmanager_secret_version.creds.secret_string)["slack_api_token"])
}

resource "mongodbatlas_alert_configuration" "restarts" {
  project_id = mongodbatlas_project.project.id
  event_type = "CLUSTER_MONGOS_IS_MISSING"
  enabled    = true

  matcher {
    field_name = "CLUSTER_NAME"
    operator   = "EQUALS"
    value      = var.cluster_name
  }

  notification {
    type_name    = "SLACK"
    api_token    = local.slack_api_token
    channel_name = var.slack_channel_name
    interval_min = 5
    delay_min    = 0
  }
}
```

### Debug Output

```
  # mongodbatlas_alert_configuration.backup_behind_schedule[0] will be updated in-place
  ~ resource "mongodbatlas_alert_configuration" "backup_behind_schedule" {
        id                     = "foo"
        # (6 unchanged attributes hidden)

      ~ notification {
          ~ api_token              = (sensitive value)
            # (22 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Expected Behavior

Once applied no further changes should be seen

### Actual Behavior

I see a lot of:

```
  # mongodbatlas_alert_configuration.backup_behind_schedule[0] will be updated in-place
  ~ resource "mongodbatlas_alert_configuration" "backup_behind_schedule" {
        id                     = "foo"
        # (6 unchanged attributes hidden)

      ~ notification {
          ~ api_token              = (sensitive value)
            # (22 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

just run terraform apply a few times

**Comment by apparentlymart** [comment]
Hi @palmobar! Thanks for reporting this.

Problems like this, where a particular change never seems to converge and the provider just keeps re-proposing the same action, are typically (but not always) caused by bugs in providers rather than in Terraform Core, so I think we will need to eliminate that possibility first.

Unfortunately this is harder to debug with a sensitive value because Terraform is not allowed to show you the actual value in the UI and so we can't see exactly what's apparently changing here.

As a first debugging step, I suggest trying the following command:

```
terraform plan -refresh-only
```

This will tell Terraform to create a special kind of plan which is focused only on detecting changes made outside of Terraform, without considering what has changed in the configuration.

What I'm interested to see here is whether this will report that any objects have changed outside of Terraform. If it _does_ describe changes outside of Terraform, but yet you know you haven't actually changed whatever it is describing, then that would indicate that the provider's logic for reading the current state from the remote system is buggy, causing it to report something has changed when it actually hasn't.

If you can share the full output from the above command I think that should help us figure out what is the next debugging step here.

Thanks!

**Comment by palmobar** [comment]
Thank you for this explanation, it indeed is a bug in the provider: https://github.com/mongodb/terraform-provider-mongodbatlas/issues/863
