### ISSUE TITLE
splat expression doesn't work for resources with for_each

### ISSUE THREAD

**Issue by thllxb** [hashicorp/terraform#32019]
### Terraform Version

```shell
$ terraform version
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

### Terraform Configuration Files

```terraform
resource "null_resource" "test" {
  for_each = { test1 = "", test2 = "" }
}

output "ids" {
  value = null_resource.test[*].id
}
```

### Debug Output

https://gist.github.com/thllxb/b0cc3ab8b561ece52798b2f72fbedb78

### Expected Behavior

The output should properly show the ID of the null resources as a list created by the splat expression.

### Actual Behavior

╷
│ Error: Unsupported attribute
│
│   on main.tf line 22, in output "ids":
│   22:   value = null_resource.test[*].id
│
│ This object does not have an attribute named "id".
╵

### Steps to Reproduce

1. terraform init

1. terraform apply

**Comment by jbardin** [comment]
Hi @thllxb,

A resource using `for_each` is represented as a `map`. Since the splat expression is intended to be used on lists of values, or access a single value as a list, it is not applicable to resources using `for_each`. See https://www.terraform.io/language/expressions/splat#splat-expressions-with-maps

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
