### ISSUE TITLE
Terraform apply doesn't stops when error occurs

### ISSUE THREAD

**Issue by kideg20** [hashicorp/terraform#32043]
### Terraform Version

```shell
Terraform v0.13.7
```

### Terraform Configuration Files

I have created module "patching" and applying it to all virtual machines (linux OS) (in my case 3 vm.) 
```terraform
module "patching" {
  source = "[url-our-git-server]"
  depends_on = [module.relays]
  for_each = var.vms

  patching = var.patching

  host        = var.vms[each.key].ip
  user        = var.vm_defaults["user_ssh"]
  private_key = module.auth.secrets["private_key"]
}
```
And module is simple it makes apt update and apt upgrade:
```terraform
resource "null_resource" "patching" {
  count = local.patching_enabled ? 1 : 0
  depends_on = [null_resource.patching-prepare[0]]
  triggers =  tomap({"id" = null_resource.patching-prepare[0].id})
  connection {
    type        = "ssh"
    host        = var.host
    user        = var.user
    private_key = var.private_key
    agent       = false
    timeout     = "15m"
  }
  provisioner "file" {
    source      = "${path.module}/templates/patching.sh"
    destination = "/tmp/patching.sh"
  }
  ### PATCHING apt update apt upgrade 
  provisioner "remote-exec" {
    inline = [
      "/bin/bash /tmp/patching.sh && rm -f /tmp/patching.sh",
    ]
  }
  ### CHECK IF REBOOT IS NEEDED AND REBOOT IF ALLOWED
  provisioner "remote-exec" {
    inline = local.reboot_allowed ? ([
      "echo 'Checking if reboot is required'",
      "test -e /var/run/reboot-required && echo 'Reboot is required. Rebooting' && sudo reboot || echo 'Reboot is not required'"
    ]) : ([ 
      "echo 'Checking if reboot is required'",
      "test -e /var/run/reboot-required && echo 'Reboot is required. But not allowed. Requires manual OS reboot' || echo 'Reboot is not required. Upgrade completed'"
    ])
    on_failure = continue
  }
  ### Sleeping until reboot is completed
  provisioner "local-exec" {
    command = "sleep ${local.reboot_timeout}"
  }
  provisioner "remote-exec" {
    inline = [
      "echo '# TO DO CREATE TESTS'",
      "echo '# TO DO LAUNCH TESTING'",
      "echo 'UPGRADE COMPLETED'",
    ]
  }
}
```

### Debug Output

module.patching["vm-01"].null_resource.patching[0]: Creating...
module.patching["vm-01"].null_resource.patching[0]: Still creating... 
module.patching["vm-02"].null_resource.patching[0]: Creating...
module.patching["vm-02"].null_resource.patching[0]: Creation complete after 1m23s
module.patching["vm-03"].null_resource.patching[0]: Creating...
module.patching["vm-03"].null_resource.patching[0]: Creation complete after 1m23s
Error: timeout - last error: dial tcp 10.35.12.99:22: i/o timeout

### Expected Behavior

module.patching["vm-01"].null_resource.patching[0]: Creating...
module.patching["vm-01"].null_resource.patching[0]: Still creating... **(Here i'm disabling network adapter from virtual machine to test condition if server will not boot after reboot, and I expect that terraform will stop processing next resource, but it continues to create resouces. And after all resources are done terraform exits with error)** 
module.patching["vm-02"].null_resource.patching[0]: Creating...
module.patching["vm-02"].null_resource.patching[0]: Creation complete after 1m23s
module.patching["vm-03"].null_resource.patching[0]: Creating...
module.patching["vm-03"].null_resource.patching[0]: Creation complete after 1m23s
Error: timeout - last error: dial tcp ipaddress:port: i/o timeout

### Actual Behavior

Terraform doesn't stop and proceeds in creating other resources. 

### Steps to Reproduce

terraform apply -parallelism=1

### References
https://github.com/hashicorp/terraform/issues/2702
_No response_

**Comment by jbardin** [comment]
Hi @kideg20,

Terraform by design will only stop executing dependent resources when there is an error, but it does not try to abort all possible operations. While any resource downstream from the error may implicitly require the errored resource to complete fully, resources being applied which have to relationship to the errored resource should not be prevented from executing correctly. Also being concurrent operations, there is no defined order between non-dependent resources, so any attempt at an interrupt would be non-deterministic.

The only way to prevent further operations after the resource errors, is to ensure that resource is somehow required by all others in the configuration, either through inclusion of some attribute in their configuration, or through judicial use of `depends_on`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
