### ISSUE TITLE
Unable to download provider configuration

### ISSUE THREAD

**Issue by gaikwadn7914** [hashicorp/terraform#32078]
### Terraform Version

```shell
v1.3.3
```

### Terraform Configuration Files

provider.tf

===
provider "github" {
}

### Debug Output

NA

### Expected Behavior

Plugin should be downloaded

### Actual Behavior

Unable to download terraform github plugins

### Steps to Reproduce

terraform init

### References

#30722

**Comment by jbardin** [comment]
Hello,

If you have questions about provider installation, please check out the community forums for any assistance. If you have a bug to report, please provide all the requested information to reproduce the issue.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
