### ISSUE TITLE
terrafom init -reconfigure does not change statefile in azurerm backend while upgrading from 0.14.11 -> 0.15.5

### ISSUE THREAD

**Issue by jeggers-88** [hashicorp/terraform#32093]
### Terraform Version

```shell
0.15.5
```

### Terraform Configuration Files

```
terraform {
  backend "azurerm" {
    resource_group_name  = "kp-terraform"
    storage_account_name = "tfstatexxxxx"
    container_name       = "tfstate"
    key                  = "all.terraform.tfstate"
  }
```

### Debug Output

-

### Expected Behavior

"terraform init -reconfigure" should generate a new statefile and store the new statefile in the remote storage. 

### Actual Behavior

The statefile in the remote storage is still the old one from terrafom 0.14.11.  

### Steps to Reproduce

terraform init -reconfigure

Starting with a tf-statefile from 0.14.4 in the remote backend.

**Comment by jbardin** [comment]
Hi @jeggers-88,

The purpose of the `-reconfigure` flag is specifically to not move the state file, and only rewrite the backend configuration. The normal init process in v0.15 will offer to migrate the state by default. Note that v0.15 is obsolete, and you should be using at least the latest from that release series, which is v1.0.11.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
