### ISSUE TITLE
Variable with type = list(object({})) without keys defined supresses provided keys

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform#32107]
### Terraform Version

```shell
1.3.3
```

### Terraform Configuration Files

```terraform
variable "test" {
  description = ""
  type        = list(object({}))
  default     = []
}

output "test" {
  value = var.test
}
```

### Debug Output

Changes to Outputs:
  + test = [
      + {},
    ]

### Expected Behavior

Keys are not suppressed 

### Actual Behavior

Keys are suppressed

### Steps to Reproduce

Create a module as above then use it like this
```
module "test" {
  source = "./modules/test"
  test = [{
    a = "a"
    b = "b"
  }]
}
```

**Comment by apparentlymart** [comment]
Hi @vladimirtiukhtin! Thanks for sharing this.

What you've described is the intended behavior of the Terraform language. You declared that your module expects a list of empty objects (that is: objects that have no attributes) and so Terraform converted the given input to match that type.

If your module expects to make use of attributes `a` and `b` then you must declare that you require those attributes:

```go
variable "test" {
  description = ""
  type = list(object({
    a = string
    b = string
  }))
  default = []
}
```

Because you are using Terraform v1.3, you can also use the new optional attributes feature to declare each of those attributes as being optional, if you wish to allow the caller to optionally omit them:

```go
variable "test" {
  description = ""
  type = list(object({
    a = optional(string)
    b = optional(string)
  }))
  default = []
}
```

In this second case, Terraform will insert null values for those attributes if they aren't set in the caller, so that the final value will conform to your type constraint.

In all cases, if you specify an exact type constraint then Terraform will convert the input type to exactly match that constraint or return an error explaining why that conversion isn't possible.

**Comment by vladimirtiukhtin** [comment]
Hi @apparentlymart 

I can't predict the keys user supplies. I tried to use a map, but for some reason it does not allow mixed types

**Comment by apparentlymart** [comment]
Hi @vladimirtiukhtin,

Let's discuss your situation further in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27). That's a better place to talk about different ways to solve a problem with today's Terraform, whereas we use GitHub issues only to discuss bugs and feature requests for Terraform.

Thanks!
