### ISSUE TITLE
Use : in key name in type definition

### ISSUE THREAD

**Issue by fs-evooq** [hashicorp/terraform#32102]
### Terraform Version

```shell
Terraform v1.2.9
on linux_amd64
```

### Terraform Configuration Files

You can quote key name
```terraform
asg = {
  ami_filters = { "tag:Version" = ["v12"] }
}
```

But not in the type definition
```terraform
variable "asg" {
  type = object({
    ami_filters = object({
      "tag:Version" = list(string)
    })
  })
}
```

See error in _debug output_ section

### Debug Output

with quotes
```text
│ Error: Invalid type specification
│ 
│   on somefile.tf line 9, in variable "asg":
│    8:     ami_filters      = object({
│    9:       "tag:Version" = list(string)
│   10:     })
│ 
│ Object constructor map keys must be attribute names.
```

and without
```terraform
│ Error: Missing attribute separator
│ 
│   on ../../aws/variables.tf line 11, in variable "asg":
│   10:     ami_filters      = object({
│   11:       tag:Version = list(string)
│ 
│ Expected a newline or comma to mark the beginning of the next attribute.
```

### Expected Behavior

It should work

### Actual Behavior

It does not work

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @fs-evooq,

The Terraform language does not allow the `:` in an [identifier](https://developer.hashicorp.com/terraform/language/syntax/configuration#identifiers). Because the `:` character has additional meaning within the language, it's not possible to use as an attribute identifier. The only way to use that character would be as part of a map key, which for the simplified example here would be of type `map(list(string))`

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
