### ISSUE TITLE
oci_core_subnet resource doesn't respect assigned route_table_id on the first run

### ISSUE THREAD

**Issue by luckeyca** [hashicorp/terraform#32112]
### Terraform Version

```shell
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/oracle/oci v4.96.0
```

### Terraform Configuration Files

```terraform

resource "oci_core_route_table" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
}

resource "oci_core_subnet" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
  cidr_block     = var.cidr_block

  route_table_id             = oci_core_route_table.this.id
}

```

OR

```
resource "oci_core_route_table" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
}

resource "oci_core_subnet" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
  cidr_block     = var.cidr_block
}

resource "oci_core_route_table_attachment" "this" {
  subnet_id = oci_core_subnet.this.id
  route_table_id             = oci_core_route_table.this.id
}
```

### Debug Output

N/A

### Expected Behavior

when running the two scripts above, the route_table_id should be assigned to the subnet when terraform runs the first time which creates the subnet.

### Actual Behavior

when run the terraform the first time, the subnet resource always get the vcn default route_table_id, rather than the route_table_id assigned, either using the route_table_id argument inside oci_core_subnet resource at the subnet creation time, or using the oci_core_route_table_attachment resource after both route table and subnet were created.

as a result, on the 2nd terraform, terraform detects an external change on the route table / subnet association and makes changes. after that, everything was fine.

I did verify on oci console through audit log to confirm there is no one makes any outside change(it's impossible because I was running the terraform back-to-back immediately in my own test environment). So it's a bug with the oci_core_subnet resource on how it handles the route_table_id at the creation time. It should NOT use VCN's default route table if route_table_id was assigned in the resource or using oci_core_route_table_attachment right after the oci_core_route_table and oci_core_subnet resources were created.

### Steps to Reproduce

```terraform

resource "oci_core_route_table" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
}

resource "oci_core_subnet" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
  cidr_block     = var.cidr_block

  route_table_id             = oci_core_route_table.this.id
}

```

OR

```
resource "oci_core_route_table" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
}

resource "oci_core_subnet" "this" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id
  cidr_block     = var.cidr_block
}

resource "oci_core_route_table_attachment" "this" {
  subnet_id = oci_core_subnet.this.id
  route_table_id             = oci_core_route_table.this.id
}
```

**Comment by apparentlymart** [comment]
Hi @luckeyca! Thanks for reporting this.

I think you are describing a behavior that belongs to this particular provider, rather than to Terraform itself. Providers are separate programs developed in their own repositories, and so there's typically nothing we can change in this repository to affect details like this.

Instead, I suggest reporting this issue in the provider's own repository. Because this is a public module, you can use its page on [Terraform Registry](https://registry.terraform.io/) to find the corresponding GitHub repository; it will be linked next to "Source Code" on the provider's details page in the registry.

Because this is describing a provider behavior rather than a Terraform behavior I'm going to close this. If I've misunderstood and this was actually intended as a Terraform Core bug report (an issue that could potentially affect any provider, rather than just this one), please let me know. Thanks!
