### ISSUE TITLE
Ingestion Private Endpoint for Purview Account

### ISSUE THREAD

**Issue by Saikiran7777** [hashicorp/terraform#32133]
### Terraform Version

```shell
terraform version 3.29
```

### Use Cases

To scan data factory and synapse we need to add Ingestion Private endpoints to Purview Account

### Attempted Solutions

From Portal We are able to Add it But not with Terraform.
![image](https://user-images.githubusercontent.com/58092827/199335440-59296b87-832e-48e4-b142-9b5bab25de95.png)

### References

https://learn.microsoft.com/en-us/azure/purview/catalog-private-link-end-to-end

**Comment by apparentlymart** [comment]
Hi @Saikiran7777!

It seems that you are talking about support for describing a particular type of object using the Azure provider for Terraform. If so, the appropriate place for that feedback is in [the Azure provider's own repository](https://github.com/hashicorp/terraform-provider-azurerm), because that is where Azure provider features would be implemented. There are no Azure-specific provider features in this codebase, so I'm going to close this issue.

Thanks!
