### ISSUE TITLE
Module Option: Flatten - treat as root module code

### ISSUE THREAD

**Issue by AlexAtkinson** [hashicorp/terraform#32149]
### Terraform Version

```shell
NA
```

### Use Cases

When managing a number of modules there is often a need to apply common configurations across all modules. A simple example of this would be common variables necessary to populate cost reporting or security tags.
My initial use case was simply to dedupe (DRY) my common variables configurations and their sometimes convoluted validations.

### Attempted Solutions

Currently I'm maintaining a directory of snippets that can be copied into module dirs as needed. They're named as snip-foo.tf, enabling a degree of automation against all snip-.*.tf files, automatically populating changes in the common-code directory into module directories. This isn't he worst approach as this can trigger tf plan as necessary.

### Proposal

Ideally the modules function would have a 'flatten' option, allowing sourced code to be treated as root, rather than child module code which necessitates handling all the inputs/outputs discretely, which is a large part of what I want to avoid.
There would have to be some namespace and provider collision handling, but it would greatly extend the potential of architectural patterns for terraform.

**Comment by apparentlymart** [comment]
Hi @AlexAtkinson! Thanks for sharing this use-case.

I think what you are proposing here is essentially the same as what was discussed in #1478. Ultimately the Terraform team decided against including that feature, and I believe all of the same tradeoffs described in the closing comment there remain true today, and so I expect the answer to this issue will be the same.

Specifically, your request to avoid specifying an explicit interface (input variables and output values) between the caller and callee is contrary to our design goals for the Terraform language, which make exactly the opposite tradeoff: the author _should_ do that extra work to intentionally design an interface so that it's clearer to a future reader of a module how the different components are interacting and how data is flowing between the modules.

If you have some other information to share about your use-case that would distinguish this from the earlier request then we'd be happy to consider it, but based on the goals you've stated so far I think unfortunately our answer will be that modules with explicit input variables and output values _are_ the supported way to address this problem, and we don't intend to offer any less structured mechanisms to achieve that.

Thanks again!

**Comment by AlexAtkinson** [comment]
Looks like a lot of +1's on that issue. While it's fine to have design goals, they need to give way to usability in the face of user demand.
This seems like a perfect scenario where you would want to make this allowance. This enhancement doesn't completely disregard the values of the initial goals, but adds the opportunity for an enhanced architectural pattern to be used for teams with the discipline to make appropriate use of the feature.

Without this flatten option I'm using a dir of snippets that require either manual copy/paste or some maintenance scripts to keep sync. Or manually edit embedded code.
With this flatten option, I get to easily maintain one config that has presence in possibly hundreds of modules.

...crud. This is terragrunt space. Haven't used it, but would like to avoid if possible.

Perhaps include it as a function apart from modules. Call it ~~import~~ include.

Hopefully this gets better traction than the other issue. Thanks.

**Comment by apparentlymart** [comment]
Hi @AlexAtkinson! Sorry I didn't see your response to this sooner.

Your response here doesn't seem to have added any new information compared to the previous discussion. I understand that you find it inconvenient to maintain explicit interfaces, but Terraform is designed for broad use by people of various levels of experience, and so anything which is easy to misuse (i.e. requiring "discipline" to use correctly) is not appropriate for Terraform.

Refactoring your configuration into multiple distinct modules that each has a well-defined interface is the way to decompose problems in Terraform. If you want everything to be in the same namespace then you can maintain all of your infrastructure together in a single module, although I would not recommend that for similar reasons to why I would not support flattening many modules into the same namespace.

We are happy to reconsider past decisions when there is material new information to add to the discussion, but since this seems to just be a re-statement of a problem that the team has already made a design decision on, I'm going to close this. Thanks!
