### ISSUE TITLE
aws_spot_instance_request doesn't respect subnet_id for non-default VPC

### ISSUE THREAD

**Issue by cdorros** [hashicorp/terraform#3214]
It appears that the aws_spot_instance_request does not respect the subnet_id parameter. Despite my setting it to a subnet in a non-default VPC, it just launches the request inside the default VPC/subnet.

Original error I was receiving before removing the security group linking to see what it would do on apply:
* aws_spot_instance_request.poppy-server: Error requesting spot instances: InvalidParameter: Security group sg-xxxxxx and subnet subnet-yyyyyy belong to different networks.
	status code: 400, request id: []

Might be somewhat related to:
https://github.com/hashicorp/terraform/issues/3154

**Comment by myoung34** [comment]
Are you positive that your SG you tried to use exists within the VPC that the subnet does?

**Comment by caarlos0** [comment]
@cdorros seems to be working on master branch.

**Comment by dmaze** [comment]
It looks like, if `associate_public_ip_address = true`, then the subnet information gets lost.

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L989 builds up the generic instance options.  If you are putting the instance into a non-default VPC, and associatePublicIPAddress is true, then the subnet information gets attached to the network interface information, not to the instance metadata as a whole; probably because AssociatePublicIpAddress is a property of the network interface not of the instance.

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_spot_instance_request.go#L84 actually submits the spot request, but this totally ignores the network interface information.

So setting `associate_public_ip_address = false` is a good workaround (and if you have things set up so that your spot instances can boot quickly and are just serving cycles to the rest of your application may even be correct).  Comparing the "instance" to "spot instance" code, it looks like there are several options that spot instance requests just don't pass on to AWS.

**Comment by catsby** [comment]
I believe this issue has been addressed by now. I apologize for the late reply. If you're still hitting this please let me know

**Comment by daddy-cool** [comment]
I got this issue today in Terraform 0.11.13 again, had to set associate_public_ip_address=false to work
