### ISSUE TITLE
Resource index: resource_type.*.property

### ISSUE THREAD

**Issue by sorenhuus** [hashicorp/terraform#32140]
### Terraform Version

```shell
Terraform v1.3.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.29.1
```

### Use Cases

Currently, if there is need to loop thru resources, for property values, they must be created using a loop (count or for_each)

While this is technical possible to do with count/for_each. It leads to complex object structures insted of having the option to do multiple, but simple, resource blocks.

### Attempted Solutions
```
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
}

resource "azurerm_storage_account" "example1" {
  name                     = "storageaccountname1"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
}

output "storage_account_names" {
  value = azurerm_storage_account.*.name
}
```

--------------------------------------------------------------------------------
```
 Error: Invalid reference
│
│   on test.tf line 31, in output "storage_account_names":
│   31:   value = azurerm_storage_account.*.name
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
```

### Proposal
```
Changes to Outputs:
  + storage_account_names = [
      + "storageaccountname",
      + "storageaccountname1",
    ]
```

**Comment by jbardin** [comment]
Hi @sorenhuus,

Resource addresses must be statically known in the Terraform language, and cannot be interpolated during evaluation. The functional equivalent to what you want would be achieved by building the resource instances using a `for_each` expressions, and then referencing the entire group of resources as a whole. This would also allow for more powerful filtering within a `for` expression in the output value.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
