### ISSUE TITLE
When using a Launch Configuration, name resources cause runtime errors

### ISSUE THREAD

**Issue by patrobinson** [hashicorp/terraform#3215]
This is more a user experience issue, caused by various implementation concerns, than an actual bug.

As per the [documentation](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html), Launch Configurations require the `lifecycle { create_before_destroy = true }` setting when used with AutoScale Groups. When using `create_before_destroy` on any resource, having a name set causes runtime errors (see #2958) such as:

```
* aws_security_group.inbound: Error creating Security Group: InvalidGroup.Duplicate: The security group 'staging-inbound' already exists for VPC 'vpc-xxxxxxx'
        status code: 400, request id: []
```

Now as per #2948 when you set create_before_destroy on any resource, all dependancies must also have create_before_destroy set. This in effect makes it not possible to set the name resource on any resources. I'm trying to make my code more modular as well, to create re-usable parts and this makes it especially difficult because all code must account for this edge case by setting create_before_destroy.

**Comment by nemski** [comment]
Actually I just realised for aws_iam_role, aws_iam_instance_profile and aws_iam_role_policy name is required so this is a bug in that instance.

**Comment by apparentlymart** [comment]
In another ticket @phinze mentioned that there is a plan to generalize this capability of generating a unique id within a name by turning it into an interpolation variable/function, thus making it usable across all resource types. Maybe he can talk a little more here about how far along that plan is, since when we were discussing it before (I don't remember where, sadly) it was just a sidebar to another discussion we were having and thus light on details.

**Comment by stack72** [comment]
Hi @patrobinson 

Not sure if this is still an issue for you or not. If it is, I suggest using `name_prefix` other than `name` on the Launch config. https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#name_prefix

Paul
