### ISSUE TITLE
Having `one` function working with maps

### ISSUE THREAD

**Issue by BzSpi** [hashicorp/terraform#32196]
### Terraform Version

```shell
1.3
```

### Use Cases

The `one` function is very handy for managing outputs as documented.

It would be fine to have this function also available for maps and not only lists.

### Attempted Solutions

It's possible to use `try` instead of `one` but it's not as handy since it does not check if map has more than one item in the collection and can hide underlying issue.

### Proposal

```
variable "include_ec2_instance" {
  type    = bool
  default = true
}

resource "aws_instance" "example" {
  for_each = to_set(var.include_ec2_instance ? ["enabled"] : [])

  # (other resource arguments...)
}

output "instance_ip_address" {
  value = one(aws_instance.example[*].private_ip)
}
```

**Comment by crw** [comment]
Thanks for this request!

**Comment by apparentlymart** [comment]
Hi @BzSpi! Thanks for this proposal.

In your example I think the problem is that you applied the `[*]` operator to a map; the `one` function call here is valid and would have worked if the expression inside it were valid.

Therefore I think you are instead proposing to make `[*]` work with maps, presumably to produce a new map with the same keys. Unfortunately we cannot change the behavior of `[*]` in that way now because it would be a breaking change for anyone relying on that operator's special treatment of non-list values, where it converts the input into a tuple of either zero or one elements in that case. Existing modules rely on that and so we cannot change it now.

For the situation you described I think adding the `values` function to discard the map keys and just get a list of the values will make your design work, as long as you know you will only ever have one element in the `for_each`:

```hcl
output "instance_ip_address" {
  value = one(values(aws_instance.example)).private_ip
}
```

The above first takes only the value from your map, producing a list of one element. Then `one` changes that into just the object from the first element. Finally, `.private_ip` takes the single attribute you want from that object.

(In the particular example you showed I think it would be more idiomatic to use conditional count rather than `for_each`, but I assume that was just a contrived example to represent your proposal and not what you would really want to do with this capability.)

**Comment by BzSpi** [comment]
:facepalm: Indeed !

The issue was between the keyboard and the chair. Thank you for your answer.
