### ISSUE TITLE
Variable keys cannot start with int

### ISSUE THREAD

**Issue by nocode99** [hashicorp/terraform#3221]
I tried searching for this particular issue, but came up empty.

Running Terraform v0.6.3 on OS X

In variables.tf, I'm trying to assign the below:

```
variable "CIDR_block_private" {
    default = {
        1a = "172.16.1.0/24"
        1b = "172.16.2.0/24"
    }
}
```

And receiving this error:
`Error loading config: Error parsing /Users/byron/Documents/Scripts/terraform/awsvpc/variables.tf: Line 21, column 3: syntax error`

If I swap '1a' and '1b' with 'a1' and 'b1' respectively, the syntax will pass.

Edit: I know putting the keys in quotations will work as well.

**Comment by apparentlymart** [comment]
I guess if this were to be fixed then it would actually be a change in [HCL](https://github.com/hashicorp/hcl) rather than in Terraform itself, since it's the HCL parser that is throwing that error. Maybe better to file this issue over there.

**Comment by mitchellh** [comment]
Languages in general requiring identifiers to begin with a non-int is relatively normal. It makes the parser considerably easier for differentiating between a number and an identifier (especially since numbers may contain letters like hex. I'd like to keep this a syntax error, though the error message could use some work! I'll look into that.
