### ISSUE TITLE
TF Openstack provider deletes security groups rule by rule

### ISSUE THREAD

**Issue by AlbertBraden** [hashicorp/terraform#32230]
### Terraform Version

```shell
Terraform v1.0.1
```

### Terraform Configuration Files

# Instance

resource "openstack_compute_instance_v2" "instance_test" {

  count           = var.instance_count

  name            = "alberttest-terraform-${count.index}"

  image_name      = var.image_name

  flavor_name     = var.flavor_name

  key_pair        = var.key_pair

  security_groups = var.security_groups

 

variable security_groups {

  default     = [“group1","group2"]

}

### Debug Output

When destroying we see security groups deleted rule by rule

### Expected Behavior

Security groups should be deleted without deleting rules first.

### Actual Behavior

Rules are deleted, and then security groups are deleted. For a group with 1000 rules, deletion of the group takes 3 seconds on our infrastructure. Rule-by-rule deletion takes 30 minutes. Increasing parallelism doesn't help; the solution is to not delete the rules. 

### Steps to Reproduce

Build Openstack cluster via TF
terraform destroy

### Additional Context

Deleting the group should be the default. In case anyone wants the old behavior, deleting rule-by-rule could be an option

**Comment by apparentlymart** [comment]
Hi @AlbertBraden,

I think you are describing the behavior of a particular Terraform provider rather than of Terraform itself. 

Terraform providers are separate plugins developed in their own repositories and released independently of Terraform CLI. For that reason, we can't typically change the behavior of providers through changes in this repository and so you should instead report this in the GitHub repository for that provider.

You can find the GitHub repository for a provider by looking it up in [Terraform Registry](https://registry.terraform.io/) and following the "Source Code" link on the provider's information page.

Because this provider isn't implemented in this repository, I'm going to close this issue. Thanks!
