### ISSUE TITLE
Performance scales poorly with module outputs

### ISSUE THREAD

**Issue by daryl-mcmillan** [hashicorp/terraform#32251]
### Terraform Version

```shell
Terraform v1.3.5
on windows_amd64
```

### Terraform Configuration Files

```terraform
# ./test.tf

module "test" {
  source = "./helper"
  for_each = toset(flatten([for x in range(1000): [for y in range(10): "${x}-${y}"]]))
  test_in = each.value
}
```

```terraform
# ./helper/helper.tf

variable "test_in" {
  type = string
}

# with no outputs terraform plan takes ~ 3 seconds

# with one output terraform plan takes ~ 37 seconds
output "test_out" {
  value = var.test_in
}

# with two outputs terraform plan takes ~ 146 seconds
output "test_out2" {
  value = var.test_in
}
```

### Debug Output

https://gist.github.com/daryl-mcmillan/5d7025228e16a09ed9f4a1417008a156

### Expected Behavior

execution time should scale ~linearly with the number of module outputs

### Actual Behavior

execution time appears to be n^2 with the total number of module outputs in the plan

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

It looks like each module output is removed from and then added to a global list: https://github.com/hashicorp/terraform/blob/730756eca23f9777362b08ce2200925a1c1506c5/internal/terraform/node_output.go#L576

And the remove operation looks like it doesn't scale very well: https://github.com/hashicorp/terraform/blob/730756eca23f9777362b08ce2200925a1c1506c5/internal/plans/changes_sync.go#L205

**Comment by jbardin** [comment]
Thanks @daryl-mcmillan,

In most cases the `RemoveOutputChange` should not be removing anything and works as a safety check. It appears that the change is added multiple times however, so that is a bug!

Even if every change were added and removed, those simple slice operations themselves are not likely to be where the time is spent. The string manipulation from the addr or cty values is quite expensive however, and a most likely what is taking the bulk of the cpu time. Changing how we handle index keys and addressing though could be a major undertaking, so I think it's probably more advantageous to investigate removing the `RemoveOutputChange` altogether.

Thanks!

**Comment by daryl-mcmillan** [comment]
Thanks - going from 1.3.5 to 1.3.6 the `terraform plan` time has been cut in half on some of our bigger projects!
