### ISSUE TITLE
Incorrect condition check ( type - list )

### ISSUE THREAD

**Issue by weeclemans** [hashicorp/terraform#32258]
### Terraform Version

```shell
Terraform v1.3.5
on linux_amd64
```

### Terraform Configuration Files

```
# ./main.tf

variable "foo" {
  type = list
  default = [ 22 ]
}

resource "null_resource" "command" {
  count = ( var.foo == [ 22 ] ) ? 1 : 0
  provisioner "local-exec" {
    command = "echo YES"
  }
}
```

A more detailed example is here [https://github.com/weeclemans/terraform-incorrect-condition-check](https://github.com/weeclemans/terraform-incorrect-condition-check)

### Debug Output

[https://gist.github.com/weeclemans/1ada11e8baa584da439aed0eb91b27f9](https://gist.github.com/weeclemans/1ada11e8baa584da439aed0eb91b27f9)

### Expected Behavior

Correct condition check when the checked value is a list.

### Actual Behavior

Comparison of the value of the local variable 'local.snow' succeeds. Comparison of the value of the regular variable 'var.foo2' fails. The same value [null] is set for both variables. The value to check is [null].

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by jbardin** [comment]
Hi @weeclemans,

Thanks for filing the issue. The variable declaration here is for a type `list(any)` which becomes a `list(number)` with the default value. That is being compared to a literal `tuple(number)` value in the count expressions, which is comparing false because they have different types. This is similar to the mistake of checking for an empty list by comparing to an empty tuple, like `var.foo2 == []`, which will also always return false.

One solution is to wrap the literal in `tolist`, so that the inferred types match.

    var.foo2 == tolist([22])

Another solution would be to verify the length and 1st value regardless of type:

    length(var.foo2) == 1 && try(var.foo2[0] == 22, false)

The naïve example however does not give any indication as to why it fails, so there is definitely room for improvement. We can combine this into the existing issue #23562 for greater visibility.

Thanks!
