### ISSUE TITLE
Allow make dev to build only one component

### ISSUE THREAD

**Issue by dlsniper** [hashicorp/terraform#3229]
Hi, while working on #3062 I've realized that I'm spending about 1.5 minutes to build all the Terraform components. Would there be any issues into having an option to build a certain component?
What I have in mind is something like `make dev provider-aws`.

Thank you.

**Comment by apparentlymart** [comment]
I've been doing this with the following rather-awkward construction:

```
go install github.com/hashicorp/terraform/builtin/bins/provider-aws && mv $GOPATH/bin/provider-aws $GOPATH/bin/terraform-provider-aws
```

Many moons ago I looked at making something like ``make dev PLUGINS="provider-aws provider-rundeck"`` but got stuck down a rathole learning about how ``gox`` works. However, maybe it would be simpler to just change ``scripts/build.sh`` to look for the ``PLUGINS`` variable and just run something like what I quoted above instead of using ``gox`` at all, since ``gox`` isn't really important when you're only building for the host architecture anyway.

**Comment by apparentlymart** [comment]
In 3af5552b549fb04a2caf921100057ea87d0fe8df I added a way to do this, slightly different to what we discussed before:

```
make plugin-dev PLUGIN=provider-aws
```

Rather than complicating the existing `dev` and `quickdev` targets further, I just made a separate target that just runs basically the thing I mentioned in my earlier comment. There's no advantage to using `gox` when building a single package for just the host architecture.
