### ISSUE TITLE
Route53 record updates on no change

### ISSUE THREAD

**Issue by dbroockman** [hashicorp/terraform#3230]
I have a SPF record in my terraform file that looks like this

```
resource "aws_route53_record" "spf" {
   zone_id = "${var.route53_domain_zoneid}"
   name = "${var.domainname}"
   type = "SPF"
   ttl = "10"
   records = ["\"include:pobox.com\""]
}
```

The SPF record needs to contain quotes on the server side.

I get this every time I ```terraform apply```:

```
aws_route53_record.spf: Modifying...
  records.3952223681: "include:pobox.com" => ""
  records.80328877:   "" => "\"include:pobox.com\""
```

**Comment by dbroockman** [comment]
Same thing with my s3 bucket policy:

```
aws_s3_bucket.main_bucket: Modifying...
  policy: "{\"Statement\":[{\"Action\":\"s3:GetObject\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":\"arn:aws:s3:::example.com/*\",\"Sid\":\"AddPerm\"}],\"Version\":\"2012-10-17\"}" => "{\"Statement\":[{\"Action\":[\"s3:GetObject\"],\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":[\"arn:aws:s3:::caopinions.org/*\"],\"Sid\":\"AddPerm\"}],\"Version\":\"2012-10-17\"}"
```

Seems like it can't tell the strings are the same because Amazon is doing formatting after the upload.

**Comment by alexintel** [comment]
@dbroockman
Which terraform version are you using? If you're using 0.6.x can you check your terraform.tfstate file to see if aws_route53_record resource is being written there? If not, that can probably be related to my bug https://github.com/hashicorp/terraform/issues/3246
Thanks,
Alex

**Comment by dbroockman** [comment]
v0.6.3


I do see route53 resources being written there.

**Comment by apparentlymart** [comment]
For the second one I think you're likely right that it's some normalization AWS is doing on the JSON. @radeksimko has been fighting issues like that all over the place.

For the first one, [the Route53 docs](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#SPFFormat) specifically call for SPF records to be formatted in quotes, so it's polite of them to just normlize it for you and not treat it as an error :grin: . Terraform is already [doing a very similar normalization for TXT](https://github.com/hashicorp/terraform/blob/57bea9f26cdc1b32145ba35a4c27a5ee7e3225c0/builtin/providers/aws/structure.go#L440) so I expect we could just alter that to match "SPF" too.

(Terraform's normalization of ``TXT`` is actually a bit aggressive since it won't allow the multiple quoted strings that Route53 supports, but I imagine that's an edge-case anyway.)

BTW, note that the Route53 docs suggest using ``TXT`` in favor of ``SPF``... but as long as AWS continues to support it I think Terraform should make it work. :)

**Comment by TheLinuxNinja** [comment]
The SPF record type was an experiment and has been deprecated. The adopted RFC calls for using a TXT record with the "v=spf1" string. See https://tools.ietf.org/html/rfc7208#page-11
