### ISSUE TITLE
`null` is not falsy

### ISSUE THREAD

**Issue by dsiguero** [hashicorp/terraform#32306]
### Terraform Version

```shell
Terraform v1.3.5 on darwin_arm64
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

I would've expected for `null` to be a falsy value, like pretty much in any programming language:

```
$ terraform console <<< 'null ? "truthy" : "falsy"'
"falsy"

$ terraform console <<< 'can(null)'
false

$ terraform console <<< 'try(null, "")'
""
```

### Actual Behavior

`null` is its own special thing, and cannot be compared to `false` when using ternary operators. 

```
$ terraform console <<< 'null ? "truthy" : "falsy"'
╷
│ Error: Null condition
│
│   on <console-input> line 1:
│   (source code not available)
│
│ The condition value is null. Conditions must either be true or false.
╵

$ terraform console <<< 'can(null)'
true

$ terraform console <<< 'try(null, "")'
null
```

### Steps to Reproduce

`terraform console <<< 'null ? "truthy" : "falsy"'`
`terraform console <<< 'can(null)'`
`terraform console <<< 'try(null, "")'`

**Comment by jbardin** [comment]
Hi @dsiguero,

While it's true that some dynamically typed languages have a notion of "truthiness", this is not universal, and not part of the language design in Terraform. Terraform is strictly typed in this sense, and comparisons between non-null values of a different types must always return false. 

Since this is working as designed, it does not represent a bug in Terraform. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues are only monitored by a few core maintainers.

Thanks!
