### ISSUE TITLE
JSONPath Operators

### ISSUE THREAD

**Issue by abrockmeyer1** [hashicorp/terraform#32314]
### Terraform Version

```shell
Terraform v1.3.3
registry.terraform.io/hashicorp/aws v4.43.0
```

### Use Cases

Use Case: To allow usage of JSONPath Operators to filter maplists in JSON.

My specific use case is using a JSONPath Operator to filter a Key-Value list of Tags for an SSM document, it works in the document test that I've performed but I cannot make it deployable with terraform

### Attempted Solutions

I have not attempted to correct this within terraform, I have only done a workaround.

**Comment by apparentlymart** [comment]
Hi @abrockmeyer1! Thanks for sharing this use-case.

I think folks on our team aren't too familiar with this requirement of applying JSONPath operators to SSM documents. To help us understand better what the requirements might be, could you add another comment sharing what you tried outside of Terraform that worked for you? That will hopefully help us understand what's missing to get equivalent functionality within Terraform.

Thanks!

**Comment by abrockmeyer1** [comment]
Sure! So I'm in the process of building an automation document in SSM. I have already built it in the AWS Console and it is working. I am rebuilding it in terraform for deployment across my organization for other use cases and ansible scripts but I ran into issues with one line of code where I'm using a filter on a JSON object with JSONPath Operators. The code snippet is below.

     "Selector":"$.Reservations[0].Instances[0].Tags[?(@.Key==Ansible)].Value"

This is taking an object returned from EC2 and filtering the object down to the value of a key-value pair. When I tried to implement this in terraform I got this error:

      Error: Error creating SSM document: InvalidDocumentContent: In step Describe, the Selector: 
     "$.Reservations[0].Instances[0].Tags[?(@.Key==Ansible)].Value" of declared output: Ansible-Script 
     is invalid. 
     Make sure: 1.Selector is a non-empty valid JSONPath expression, no longer than 300 characters. 
     2.Selector contains only the following JSONPath operations: [Dot-notated child (.), Deep-scan (..), 
     Array index ([])]. (JSONPath Operators - @ , : ? * or functions/filters are currently not supported).

This seems to be the only way I can pull this specific tag without using a separate api call or lambda, and I would like to avoid using custom script in Lambda if possible.

**Comment by apparentlymart** [comment]
Thanks for that extra context, @abrockmeyer1!

It looks like this is an error coming from the `hashicorp/aws` provider rather than from Terraform Core, and so this seems likely to be feedback for the AWS provider development team [in the provider's own repository](https://github.com/hashicorp/terraform-provider-aws) rather than for the core (provider-agnostic) Terraform language runtime.

It does seem like a good question why exactly it seems valid to use the JSONPath operators `@` and `?` when you work outside of Terraform but not when you declare the same filter string in a Terraform configuration. I actually suspect that this error isn't even from the `hashicorp/aws` provider directly but is instead coming from the remote SSM API -- prefixes like `InvalidDocumentContent: ` here are typical for API errors returned through the AWS SDK -- but that is far beyond my own expertise and so I'm only speculating here. If that's true, this may be a matter of the AWS provider encoding this string in a strange way that is confusing the remote API.
