### ISSUE TITLE
terraform fmt should allow us to ignore files

### ISSUE THREAD

**Issue by tbutler-qontigo** [hashicorp/terraform#32349]
### Terraform Version

```shell
Terraform v1.3.2
on windows_amd64
```

### Use Cases

We use Ocotpus Deploy to deploy our terraform scripts and update `terraform.tfvars` with the variable values that are valid for the target environment.
To do this, the `.tfvars` file contains octopus substitutions such as:
`foo = #{Some.Octopus.Variable}`
which `terraform fmt` does not like - it fails with 
`Expected the start of an expression, but found an invalid expression token.`

### Attempted Solutions

I can list the files for `terraform fmt` to use explicitly and not include the `.tfvars` file but this is error-prone, tedious, and does not work with `-recursive`

### Proposal

Allow the specification of files to ignore with wildcards - `*.tfvars` for example - and preferably allow the specification of multiple files.

Alternatively, perhaps such syntax could be recognised and allowed to to pass - if `terraform fmt` is about formatting the code then it should simply recoginse this is an assignment statement and ignore whether or not the value being assigned is actually valid - validation != formatting

**Comment by tbutler-qontigo** [comment]
Hi @apparentlymart 
At the moment we test things locally using a `local.tfvars` file explicitly which is not checked in to source control and then Octopus substitutes directly into `terraform.tfvars` which is checked in.

Octopus has a single "step" using a terrraform template which does the substitution into tfvar files *and* runs the terraform command so there isn't scope in that to copy files between substitution and application.

Thinking about it, perhaps this ticket should be not so much "allow us to ignore files" (though that could still have uses) and more "terraform fmt should format the files, not validate the values it is formatting" - this would allow these files to be formatted and separates formatting from validation.
I'd have thought terraform validate is where any validation should happen....of course I may have to raise the same issue for that if we get past the fmt hump ;)

**Comment by tbutler-qontigo** [comment]
Hi @apparentlymart 

Arguably we have a simple case of TOKEN1 = TOKEN2 which should be enough for the fomatter to determine it is an assignment operation and format accordingly.
It is the job of validation to determine if TOKEN2 is a valid token type - you say yourself that it checks _"that the values being assigned to various arguments are of the correct type"_ and in this case, it is not of the correct type - it is essentially an "unknown" type which is always going to fail checks for correctness

Fair enough if you want to close the issue - I totally understand where you're coming from and, even if you agreed with me, it would probably require major surgery to implement it.

I should have stuck to my original ask for the ability to ignore certain files :)

Thanks for engaging anyway.

**Comment by apparentlymart** [comment]
The key problem here is that `#{Some.Octopus.Variable}` doesn't even _have_ a type, because from Terraform's perspective it's just a bunch of garbage characters that don't even match the grammar for this file format. The definition of an argument definition is an identifier followed by an equals sign followed by an expression, and `#{Some.Octopus.Variable}` isn't an expression so `terraform fmt` can't make any assumptions about it: it has no meaning at all.

I think you are suggesting that `terraform fmt` should use an entirely separate grammar from the main one for this file format which defines an argument definition as something like:

```
identifier "=" <anything that isn't a newline>* newline
```

That's fine as far as it goes, but `terraform fmt` does more than just identify the arguments: it also needs to parse the expressions and reformat the indentation inside there.

Trying to format something that has invalid syntax -- assuming we had a formatting-specific parser that could produce a "close enough" parse tree -- would make it crucial that this parser had very carefully chosen recovery behavior so that it can avoid making a colossal mess when it inevitably misunderstands what the author was intending. Keep in mind that the primary purpose of `terraform fmt` is to format files that are written by humans who are _intending_ to write valid syntax, but who might make mistakes; if they do make mistakes, in that case it's better for the program to fail with an error than to misunderstand the input and make incorrect formatting decisions that are likely to be time-consuming to undo once you've figured out what mistake you made.

With that said, I do appreciate having this discussion, even though the answer does seem to be "no" in this case. It's always worth thinking through the pros and cons of ideas even if we ultimately conclude that the disadvantages outweigh the advantages, which I think is the case here.

My conclusion here is that the existing way to make Terraform ignore a file is to give it a name that doesn't overlap with one of the names that Terraform considers itself to "own", which means files with any of the following suffixes `.tfvars`, `.tfvars.json`, `.tf`, `.tf.json`. I do understand that the particular tool and workflow you are using makes it inconvenient to use a name that doesn't match one of Terraform's claimed suffixes, and that is unfortunate but I think something that is better addressed in that upstream tool and workflow rather than in Terraform itself, such as by changing that program to be able to use a different filename for input than for output so that any file named with the `.tfvars` suffix is valid syntax ready for Terraform to consume.

Thanks for working through this with me! I'm going to close this issue now.
