### ISSUE TITLE
Resource component for Google cloud deploy

### ISSUE THREAD

**Issue by DarioBernardo** [hashicorp/terraform#32354]
### Terraform Version

```shell
Would be great to have a resource component for google cloud deploy.
https://cloud.google.com/deploy
```

### Use Cases

Be able to automatically create CD deploy pipeline on cloud deploy using terraform

### Attempted Solutions

searched on provider repo

**Comment by apparentlymart** [comment]
Hi @DarioBernardo!

I think this is a feature request for the `hashicorp/google` provider rather than for Terraform itself. If so, the better place to share that is in [the provider's own repository](https://github.com/hashicorp/terraform-provider-google); the developers of providers do not typically look in this repository for feedback.

Thanks!
