### ISSUE TITLE
'Terraform destroy' does not run a 'terraform refresh' in background

### ISSUE THREAD

**Issue by adi-garg** [hashicorp/terraform#32371]
### Terraform Version

```shell
Terraform v1.3.6
on windows_amd64
```

### Terraform Configuration Files

```
provider "aws"{
    region="ap-south-1"
    access_key = <ACCESS KEY HERE>
    secret_key = <SECRET KEY HERE>
}

resource "aws_instance" "web" {
  ami           = "ami-074dc0a6f6c764218"
  instance_type = "t2.micro"

  tags = {
    Name = "myec2"
  }
} 
```

### Debug Output

-

### Expected Behavior

`terraform refresh` should have run in the background each time `terraform destroy` is run ,just like the case of `terraform apply`.
Terraform(`terraform destroy`)should have said no changes to be made since the infrastructure was already destroyed manually using console.
Any particular reason for not running 'refresh' in background each time `terraform destroy` runs?

### Actual Behavior

`terraform destroy` states the EC2 is to be deleted,when in actual it got removed manually by us using console.

### Steps to Reproduce

1.`terraform init`
2.`terraform plan`
3.`terraform apply`
4.Manually delete the resource from AWS GUI
5.`terraform destroy`

### References

https://developer.hashicorp.com/terraform/cli/commands/destroy
This document may be updated accordingly based on outcome of above discussion.

**Comment by jbardin** [comment]
Hello @adi-garg,

Terraform does refresh each instance during a normal destroy operation, and does not plan to delete an instance which the provider reports as already deleted. Given the example above, terraform does not show any deletion of the instance if it has already been fully terminated.

It's possible that the instance was not yet fully terminated, causing the refresh to show a different non-null state for the instance, or that the provider mis-reported the instance some how. Since this does not appear to be a bug in Terraform, I'm going to close the issue. If you more questions, it would be better to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people familiar with the provider ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by jbardin** [comment]
Hi @adi-garg,

The documentation you linked explains that `destroy` is just a shorthand for creating and applying a destroy plan, i.e. `terraform plan -destroy`, so it still has all the same expectations of running `plan` and `apply`. There are many small details included as part of a plan, and duplicating only some of these details could imply that these are functionally separate commands, which in fact they are not. If you have suggestions for the documentation to make that more clear, feel free to file a new documentation issue.

Thanks!

**Comment by adi-garg** [comment]
Hi,
Kind of disagree, stating **refresh** is run with **plan** and **apply** and leaving out **destroy** causes confusion.
Further the official documentation of `terraform destroy` should mention about refresh happening in background.

I feel the documentation should get improved with the same request instead of hastily closing the cases.

Regards.
