### ISSUE TITLE
lookup does not work in azurerm_cdn_frontdoor_firewall_policy and azurerm_cdn_frontdoor_security_policy

### ISSUE THREAD

**Issue by pamapa** [hashicorp/terraform#32433]
### Terraform Version

```shell
>terraform version
Terraform v1.3.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.36.0

Your version of Terraform is out of date! The latest version
is 1.3.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
resource "azurerm_cdn_frontdoor_firewall_policy" "policies" {
  for_each = { for policy in var.firewall_policies : policy.name => policy }
  #mode                = lookup(each.value, "mode", "Prevention") # does not work
  #mode                = each.value.mode != null ? each.value.mode : "Prevention" # works
  mode                = "a${lookup(each.value, "mode", "Prevention")}b" # hack to verify issue
```

### Debug Output

╷
│ Error: Invalid template interpolation value
│
│   on main.tf line 211, in resource "azurerm_cdn_frontdoor_firewall_policy" "policies":
│  211:   mode                = "a${lookup(each.value, "mode", "Prevention")}b" #each.value.mode != null ? each.value.mode : "Prevention"
│     ├────────────────
│     │ each.value is object with 7 attributes
│
│ The expression result is null. Cannot include a null value in a string template.

### Expected Behavior

The lookup function is evaluating to null if element is not found in object, even if I have specified the default "Prevention"

### Actual Behavior

The lookup function should fallback to the default "Prevention" if element is not found in object. 

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by pamapa** [comment]
The function `try` is also not working in side those resources:

```
╷
│ Error: Invalid dynamic for_each value
│
│   on ..\..\modules\frontdoor\main.tf line 273, in resource "azurerm_cdn_frontdoor_security_policy" "policies":
│  273:           for_each = try(each.value.endpoint_names, {})
│     ├────────────────
│     │ each.value.endpoint_names is null
│
│ Cannot use a null value in for_each.
```

**Comment by jbardin** [comment]
Hi @pamapa,

The clue about what is going on in the error is `each.value is object with 7 attributes`. You have a single object, which since the direct reference succeeded, must have an attribute named "mode". The `try` function will only return he default is the first expression fails, but since the `mode` attribute exists, and is `null`, that is what is returned. 

In order to use that value you will either ned to conditionally check for `null`, or add a default value into the variable type declaration.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
