### ISSUE TITLE
Terraform recreates resources when module version changes

### ISSUE THREAD

**Issue by yassirarezki** [hashicorp/terraform#32437]
### Terraform Version

```shell
v1.1.2
```

### Terraform Configuration Files

```terraform
module "my_module" {
  source                               = "gitlab.com/<my_module_address>"
  version                              = "0.0.2"
  account_id                       = var.account_id
  app_name                        = var.app_name
}
```

### Debug Output

Plan: 24 to add, 0 to change, 24 to destroy.

### Expected Behavior

No resources should be updated

### Actual Behavior

Terraform tries to destroy and create the same resources even if the conf of the module did not change.

### Steps to Reproduce

1. terraform init
2. terraform plan

### Additional Context

My main module relies on a module I import from a remote source: gitlab.com/<my_module_address>

When I update the version of <my_module_address>, terraform tries to destroy and update the resources even if the sole chnage between the two verions in the logical name of a single resource.

**Comment by jbardin** [comment]
Hi @yassirarezki,

If Terraform is planning to replace all resources in the module, it is because something has changed aside from the module version forcing that plan. In order for someone to assist, you would need to show an example of the module, and the resulting plan, which likely has clues to why the instances are being replaced. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
