### ISSUE TITLE
Items in `aws_cloudfront_distribution -> origin -> custom_origin_config` shoud not be required

### ISSUE THREAD

**Issue by mirumirumi** [hashicorp/terraform#32440]
### Terraform Version

```shell
- 1.4.0 (latest)
- aws provider 4.48
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#custom-origin-config-arguments

### What is the docs issue?

The following elements are listed as required in `aws_cloudfront_distribution -> origin -> custom_origin_config` .

- http_port
- https_port
- origin_ssl_protocols 

However, these elements are not written as required in CloudFormation docs(see: [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-customoriginconfig.html)).

There should be no reason for Terraform to require this value. Is there a reason?

### Proposal

To solve this problem, I think I have to change the code in Terraform, because when we do a _lint_ or _plan_, the required checks work.

**Comment by liamcervante** [comment]
Hi @mirumirumi, thanks for the report.

Terraform providers are managed in separate repositories. I will close the issue here but if you open a fresh issue within https://github.com/hashicorp/terraform-provider-aws/issues, they will be able to provide more guidance about why this might be required or take an action to fix this inconsistency.
