### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by tirelibirefe** [hashicorp/terraform#32455]
### Terraform Version

```shell
Hello,
I've installed terraform as described here >>> https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli

When I run "terraform -version" I get the following error:

$ terraform -version
Segmentation fault

Thank & Regards
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint

echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list

sudo apt update

sudo apt-get install terraform

### Expected Behavior

a working binary

### Actual Behavior

a faulty binary

### Steps to Reproduce

sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint

echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list

sudo apt update

sudo apt-get install terraform

**Comment by jbardin** [comment]
Hi @tirelibirefe,

Thanks for filing the issue. Th `terraform` binary doesn't even appear to be initialized here, since we're not seeing any of the usual CLI output. What OS and architecture are you using? Is there any output before the crash when setting `TF_LOG=trace`? Terraform only consists of a single binary, can you check if there's possible corruption in the deb by downloading and running that binary directly?

Thanks!

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
