### ISSUE TITLE
Number suffixes as described in docs result in syntax error

### ISSUE THREAD

**Issue by ThinTim** [hashicorp/terraform#3247]
The [Terraform docs](https://www.terraform.io/docs/configuration/syntax.html) state that:

* Numbers can be suffixed with kKmMgG for some multiple of 10. For example: 1k is equal to 1000.
* Numbers can be suffixed with [kKmMgG]b for power of 2 multiples, example: 1kb is equal to 1024.

However, `terraform plan` gives a syntax error when I attempt to use a suffixed number:

```
resource "..." "..." {
  threshold = 150mb
}
```

Tested on Terraform 0.6.3.

**Comment by apparentlymart** [comment]
Oh wow... I never noticed that in the docs before, nor have I ever seen it in the code.

Out of curiosity I also tried quoting the string in case it was the Terraform layer that was supposed to be handling it, rather than the HCL layer. No dice there either:

```
  * aws_ebs_volume.example: cannot parse '' as int: strconv.ParseInt: parsing "1Gb": invalid syntax
```

This would be a rather strange feature anyway, since the quantities on many resources are already expressed in mega-somethings or giga-somethings. For example, I was experimenting with an EBS volume size here, meaning that in my above example I asked for a volume of "one giga-gigabyte". Feels like even if this feature is somehow supported somewhere it's gonna be confusing when used in conjunction with attributes that already have implied exponents, so maybe better that it doesn't work...

**Comment by mavin** [comment]
I was caught by this today too.

```
resource "aws_ebs_volume" "example" {
    ...
    iops = 2k
    ...
}
```

**Comment by phinze** [comment]
Thanks for the report - this is definitely confusing!

I wonder if it worked at one point or if these are "aspirational docs" we have found. ;)

Either way, closing to keep things consolidated in #3287.
