### ISSUE TITLE
coalesce function not returning expected results with sensitive strings

### ISSUE THREAD

**Issue by Chooglin** [hashicorp/terraform#32481]
### Terraform Version

```shell
⇒ terraform -v
Terraform v1.3.6
on darwin_arm64

⇒ terraform console
> coalesce("string1", "string2")
"string1"
> coalesce("string1", sensitive("string2"))
(sensitive value)
> type("string1")
string
> type(sensitive("string1"))
string
```

### Terraform Configuration Files

This happens irrespective of config.

### Debug Output

No Debug output available.

### Expected Behavior

> coalesce("string1", sensitive("string2"))
"string1"

### Actual Behavior

> coalesce("string1", sensitive("string2"))
(sensitive value)

### Steps to Reproduce

terraform console
> coalesce("string1", sensitive("string2"))
(sensitive value)

**Comment by apparentlymart** [comment]
Hi @Chooglin! Thanks for reporting this.

I think what you were surprised by here is that `coalesce` marks is result as sensitive if any of the input values are sensitive, regardless of which one is chosen. Is that right?

By default Terraform's behavior for sensitive values is that any function call with at least one sensitive value has a sensitive result. There are a few explicitly-written exceptions to that rule for situations where the conservative rule is problematic, but broadly speaking the idea is to err on the side of being too sensitive instead of being not sensitive enough to avoid situations where Terraform might inadvertently imply the actual value of something marked as sensitive even though the value itself isn't shown.

Given that, I think we could add a special rule to coalesce that its result is sensitive only if the argument being returned is sensitive or is one the arguments _after_ a sensitive argument.

Specifically:

1. `coalesce("hello", sensitive("world"))` would return non-sensitive "hello".
2. `coalesce(null, sensitive("world"))` would return _sensitive_ "world".
3. `coalesce(null, sensitive(null), "boop")` would return _sensitive_ "boop", even though "boop" isn't sensitive itself.

Rule 3 is to avoid disclosing whether or not the second argument is `null`. Although it's not likely that someone would consider a null value in isolation to be sensitive, in real modules that sensitive null might be the result of a test whose outcome implies all or part of a sensitive value elsewhere, so someone with access to the full plan output and the configuration source code might be able to derive a sensitive value despite it not actually being shown directly.

This change would therefore only add the special rule 1: if the first argument isn't sensitive then it will be returned regardless of what values the subsequent arguments have, and so there's no way for that result to inadvertently imply the value of later arguments.

Since what you've described is the current intended behavior for `coalesce` this issue is effectively a feature request to change the design to have this special extra rule. Because this is related to the sensitive values feature it will need some security review and so I'm going to relabel this as an enhancement to represent that it's going to follow our process for making changes to Terraform's intended design, rather than our process for changing Terraform's behavior to match the existing intended design.

Thanks!

**Comment by Chooglin** [comment]
> nonsensitive(coalesce("string1", sensitive("string2")))
"string1"

> coalesce("string1", sensitive("string2"))
(sensitive)

Ok, I thought it was returning the wrong value but it's returning the correct value but making it sensitive even though it's not explicitly marked as such for caution sake.  I agree with your assessment and appreciate the quick and thorough response.
