### ISSUE TITLE
The Registry API's pagination isn't accurate

### ISSUE THREAD

**Issue by JonZeolla** [hashicorp/terraform#32533]
### Terraform Version

```shell
N/A; Terraform registry API issue
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

```bash
$ curl -s 'https://registry.terraform.io/v1/modules' | jq '.meta.next_url'
"https://registry.terraform.io/v1/modules?offset=15"
```

### Actual Behavior

```bash
$ curl -s 'https://registry.terraform.io/v1/modules' | jq '.meta.next_url'
"https:///v1/modules?offset=15"
```

### Steps to Reproduce

```bash
$ curl -s 'https://registry.terraform.io/v1/modules' | jq '.meta.next_url'
"https://registry.terraform.io/v1/modules?offset=15"
```

### Additional Context

https://github.com/hashicorp/terraform/blob/7a019fa7673d851de49b74c6fc26d385fe8f64b5/internal/registry/response/pagination.go#L39-L46

**Comment by JonZeolla** [comment]
Hmm.  Poking around more, I'm seeing some additional issues; made the issue title more broad.

After browsing to https://registry.terraform.io/browse/modules?page=1342 the page me that it's showing modules `8992 - 9000 of 12076`, but it's the last available page (in the frontend).  If I hit next, it takes me to page 1001 but I get the contents of page 1000.  Clicking page 1000 shows no visual change, and the next button doesn't seem to be able to go beyond page 1001.

After working with the API a bit more I was able to identify somewhere around 12,012 repositories (including the 422 `git clone` errors for removed/changed or private repos listed as the `source`).

**Comment by gdguesser** [comment]
Hello @JonZeolla,

The problem is that the pagination URLs generated by the API are missing the protocol and domain parts, resulting in URLs that cannot be accessed. This is likely caused by an issue with the `currentURL` parameter passed to the `NewPaginationMeta` function, which may not be including the protocol and domain parts. And Registry not being open source I guess we can't see how it's being used, right?

I think something similar has been reported before: https://github.com/hashicorp/terraform/issues/22380

**Comment by gdguesser** [comment]
Hello @JonZeolla,

Apparently, the problem is that the pagination URLs generated by the API are missing the protocol and domain parts, resulting in URLs that cannot be accessed. This is likely caused by an issue with the `currentURL` parameter passed to the `NewPaginationMeta` function, which may not be including the protocol and domain parts. I think this is happening because when we do a curl, the `currentURL` parameter is blank due to the way it's being obtained/passed to the `NewPaginationMeta` function. However, since the registry is not open-source, we can't see how it's handling the currentURL parameter.

Also for your 2nd comment, there were another issue opened: https://github.com/hashicorp/terraform/issues/22380

**Comment by gdguesser** [comment]
Hello @JonZeolla,

Apparently, the problem is that the pagination URLs generated by the API is missing the domain part, resulting in URLs that cannot be accessed. This is likely caused by an issue with the `currentURL` parameter passed to the `NewPaginationMeta` function, which may not be including the domain part. I think this is happening because when we do a curl, the `currentURL` parameter is blank due to the way it's being obtained/passed to the `NewPaginationMeta` function. However, since the registry is not open-source, we can't see how it's handling the currentURL parameter.

Also for your 2nd comment, there were another issue opened: https://github.com/hashicorp/terraform/issues/22380
