### ISSUE TITLE
Variable defined with optional attribute behaving strange

### ISSUE THREAD

**Issue by bahag-klickst** [hashicorp/terraform#32531]
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
variable "networks" {
  default = {}
  type = map(object({
    cidr              = string,
    purpose           = list(string)
    gke_networks      = optional(list(string), [])
  }))
}
```

### Debug Output

None available

### Expected Behavior

I passed the following network map:
```terraform
networks = {
      composer = {
        cidr              = "x.x.x.x/x"
        gke_networks      = ["x.x.x.x/x", "x.x.x.x/x", "x.x.x.x/x"]
        composer_networks = ["x.x.x.x/x", "x.x.x.x/x"]
        purpose           = ["Purpose1", "Purpose2"]
      }
```

I would have expected terraform to fail, as it now got a map, which does not fit the above mentioned definition as it has one additional entry (composer_networks)

### Actual Behavior

Terraform succeeded and did just ignore the entry for composer_networks

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by bflad** [comment]
Potentially related: https://github.com/hashicorp/terraform/issues/30608

**Comment by jbardin** [comment]
Hi @bahag-klickst,

Thanks for filing the issue. This is the intended behavior for terraform, which will always attempt to convert the value passed into the module. You can also read more in issue #29204.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
