### ISSUE TITLE
`jsonencode` not working with booleans and conditional expressions

### ISSUE THREAD

**Issue by daquinoaldo** [hashicorp/terraform#32550]
### Terraform Version

```shell
Terraform v1.3.7
on darwin_amd64
```

### Terraform Configuration Files

```tf
jsonencode(true ? {bool_value = true, string_value = "string"} : {})
```

The bug only happens when there is a conditional expression, and the object contains a string value.
- `jsonencode({bool_value = true, string_value = "string"})` works as expected.
- `jsonencode(true ? {bool_value = true} : {})` works as expected.

### Debug Output

Not relevant.

### Expected Behavior

```
"{\"astring\":\"string\",\"value\":true}"
```

### Actual Behavior

```
"{\"astring\":\"string\",\"value\":\"true\"}"
```

### Steps to Reproduce

```sh
echo 'jsonencode(true ? {bool_value = true, string_value = "string"} : {})' | tf console
```

**Comment by jbardin** [comment]
Hi @daquinoaldo,

The behavior you are seeing is not related to `jsonencode` at all, it's because you are passing in different types of values via the conditional expression. 

The Terraform expression:
```
true ? {bool_value = true, string_value = "string"} : {}
```

Must evaluate to a single type, and because the object types to not match the only unification possible is to convert the first object to a map by converting `true` to `"true"`. The `jsonencode` function is only faithfully converting the object passed in. Because `json` does not have any strict typing requirements, if you need to conditionally handle different types, you will need to encode them separately.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by daquinoaldo** [comment]
Thank you for your answer. Sorry for opening the issue: I thought it was a bug.

For those having the same problem, you can split the object and use the `merge` function as follows.
```tf
jsonencode(merge(true ? {bool_value = true} : {}, true ? {string_value = "string"} : {}))
```
