### ISSUE TITLE
Feature Request: Add ability to suspend resources rather than just destroy them

### ISSUE THREAD

**Issue by couling** [hashicorp/terraform#32569]
### Terraform Version

```shell
1.3.7
```

### Use Cases

We want to turn things on and off without blowing away our data or losing allocated IPs which are registered with third parties.

The problem with `prevent_destroy` is that all it does is raise an error, leaving the user to perform surgery with `terraform state rm` and subsequently `terraform import`.  

For
- Databases
- LoadBalancers with static IP addresses
- Virtual machines
- Generally stateful services with either a detachable state or the ability to suspend them

We want to be able to stop paying for these for a time, but not wholly destroy their state.  We want to be able to "suspend" them and bring them back later.  We want to do this and also (fully) tear down all other connected resources that are not needed for a switched off system.

### Attempted Solutions

A very rudimentary way of doing this for some services can be to have two separate terraform deployments, one to create the "detached state" resources and another to spin up / down the live infrastructure.

For example (AWS):
 - One deployment allocates an AWS Elastic IP, the other creates a network loadbalancer with that IP.
 - One deployment creates an EBS volume, the other creates a virtual machine and the other attaches it to a virtual machine.

However linked deployments like this makes for extremely complex terraform.  It also misses capabilities of the cloud to suspend other things.  For examples:
 - RDS instance can be torn down to produce a snapshot and spun back up from the snapshot.  In terraform there's no ability to flip between them.
 - An EC2 instance can simply be turned off, and then turned back on again.

## Simple idea
I want to type a command, eg:

    terraform suspend

and terraform will both destroy some resources and suspend others only leaving the minimal ones in place.  A subsequent command of

    terraform apply

would bring everything back, re-creating and resuming suspended resources.

### Support from providers

This will need adding to the internal API of terraform so that providers can be instructed to suspend resources and resume suspended resources.  Destroying suspended resources would be nice to have.

Obviously providers will need time to implement the new API so there needs to be backwards compatibility and even after providers have had change to implement, it won't be possible to suspend all resources.  There's logically three things that terraform could do if a provider cannot support suspend:

 - Raise Error to the user and abort
 - <strike>Warn the user and destroy the resource</strike> (Bad idea!)
 - Warn the user and leave the resource up

### Fine grained control for the user

This proposal would be made far more powerful if the user were allowed to re-map individual resources such that a destroy was replaced with a suspend or a suspend was replaced with a destroy, or suspend was replaced with leaving it on.

This would allow a user to inform Terraform how to achieve suspension in even the most complex situations.  For example a Redis server that cannot be logically suspended without data loss.  If the engineer knows it's only used as a cache and can be safely torn down without loss they could do something like this:

```terraform
resource "aws_elasticache_cluster" "example" {
  lifecycle {
    on_suspend = "destroy"
  }
  cluster_id           = "cluster-example"
  engine               = "memcached"
  node_type            = "cache.m4.large"
  num_cache_nodes      = 2
  parameter_group_name = "default.memcached1.4"
  port                 = 11211
}
```
This would result in `terraform suspend` destroying the Redis server while suspending other things.

**Comment by jbardin** [comment]
Hi @couling,

Thanks for filing the issue. The concept of "suspend" is only applicable to a small subset of resource types which Terraform can manage, so it doesn't really make sense to impose that type of lifecycle change on top of the generic lifecycle we use for managed resources. Because something like suspend would be unique to the implementation of any particular resource, it's not really possible to create a universal model with could apply equally to the subset which might be able to suspend. (The concept of "lifecycle" in Terraform does not apply to statuses like "running" or "suspended", it is more generic than that, referring more directly to the handling of the data stored in the state for that resource.)

Take the common EC2 instance for example. The lifecycle is documented here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html, which shows there are a number of possible states which all have to be accounted for and are unique to that type. Once multiple, configurable states are possible, the provider must also decide how to plan any changes for that instance in each state, and what actions it must take, e.g. if we are in `stopped` because this was an EBS backed instance, but you are requesting a change which requires the instance to be running should that return an error?, restart the instance?, hibernate again afterwards?, etc.

Since this relies on providers to implement special logic for each possible case, and many cases may not be cover-able due to API limitations, it's really up to the provider to handle this type of transition. Since providers already have the ability to implement this type of state change, and configurations could be fashioned to conditionally destroy or disable instances of any type, the concept of "suspend" is not something I would expect Terraform to adopt.

Thanks!

**Comment by couling** [comment]
Thanks for your time

Forgive me, it feels like you missed two critical point here.  

Firstly:

> Since this relies on providers to implement special logic for each possible case, and many cases may not be cover-able due to API limitations, it's really up to the provider to handle this type of transition

Though the provider could handle this transition in theory, there is no way for the user or code to instruct it to.  Terraform lacks the internal language to tell it _when_ to do this.

Secondly:

A very important detail of this proposal was to give the user ability to map a "suspend" event state to other, existing actions which providers must logical implement in some form already.

Without this, I agree that the lack of support for providers would make the feature useless.  But with this, users would be able to define their own "suspended" state even when the providers themselves don't.

--------

I realise this doesn't fit well with the existing design.

Just as a polite note, I'll say that the  inability to do a graceful tear down without burning key data and without burning our time is becoming a critically lacking feature for us which may force us away from terraform in the long run.

I'll leave it at that. Thanks for your time.

**Comment by jbardin** [comment]
Hi @couling,

Providers would add this functionality the same way as any other functionality, through resource attributes. The general "lifecycle" we speak of in Terraform basically consists of only "plan any changes" then "apply that plan".  Any suspend functionality on individual resources would still fall into that basic workflow. This means that changing a state from "running" to "stopped" is no different for providers than any other change in state, it is however more complex to implement due to the aforementioned reasons, but still must be done in the provider. Any resource which supported these changes from the provider, would inherently allow users to alter the resource state conditionally via configuration (which is basically what already happens with any configuration change). It's true that there wouldn't be a special command for this particular change in state, but changing an input variable could have the same effect, and could be applied to only the resources which can accept that type of change.

**Comment by couling** [comment]
@jbardin Yeah I think I see the solution you're suggesting.  It would require couches on every resource of the form `count = var.suspend = true ? 1 : 0` at minimum and something not dissimilar on resources which are already `count` or `for_each`.  That's going to make resource referencing _interesting_.

Though I accept "suspended" has no definition either, there's perhaps many levels of suspension to other users.

Frankly we're already burning far too many hours just trying to keep our terraform code "maintainable". Terraform already lacks:
 - truly optional resources (something or `null`, not a `count` of 0 or 1)
 - global variables accessible to all modules and sub modules
 
The added complexity of adding such couches throughout the code would definitely push us over a cliff and I'd have staff quitting in fury if I came in one morning and said _"hey folks, I've got suspension working: take a look..."_.

Anyway.  Thanks very much for your time. I do appreciate the proper thought you've given to this.
