### ISSUE TITLE
Dynamic for_each inconsistent behavior

### ISSUE THREAD

**Issue by Kirizan** [hashicorp/terraform#32581]
### Terraform Version

```shell
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.50.0
```

### Terraform Configuration Files

```terraform
resource "aws_lb" "alb" {
  dynamic "access_logs" {
#    for_each = try(lookup(var.load_balancer, "access_log"), null) != null? lookup(var.load_balancer, "access_logs") : []
    for_each = try(lookup(var.load_balancer, "access_log"), [] )
    content {
      bucket = lookup(access_logs, "bucket")
      enabled = try(lookup(access_logs, "enabled"), null)
      prefix = try(lookup(access_logs, "prefix"), null)
    }
  }
}
```

### Debug Output

│ Error: Invalid dynamic for_each value
│ 
│   on load_balancer.tf line 36, in resource "aws_lb" "alb":
│   36:     for_each = try(lookup(var.load_balancer, "access_log"), [] )
│     ├────────────────
│     │ var.load_balancer is object with 19 attributes
│ 
│ Cannot use a null value in for_each.

### Expected Behavior

I would expect the following two lines to produce the same result if there is no access_log block in var.load_balancer:

```terraform
for_each = try(lookup(var.load_balancer, "access_log"), null) != null? lookup(var.load_balancer, "access_logs") : []
for_each = try(lookup(var.load_balancer, "access_log"), [] )
```

### Actual Behavior

This line works: 
```terraform
for_each = try(lookup(var.load_balancer, "access_log"), null) != null? lookup(var.load_balancer, "access_logs") : []
```

And this line produces the error in Debug output:

```terraform
for_each = try(lookup(var.load_balancer, "access_log"), [] )
```

### Steps to Reproduce

1. terraform init
2. terraform plan

### Additional Context

Based on my understand, both for_each lines will produce an empty list `[]` if access_logs is not provided. This is not the case however. Since access_logs is not a required block, both of these lines should work when there is no access_logs block provided. 

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb

**Comment by kmoe** [comment]
Thanks for this. The behaviour is a bit unexpected. I'm not sure how the for_each value could end up null, but that error could also be wrong.

Could you include the `variable` block for `"load_balancer"` in the config example? Does it have both `access_log` and `access_logs` attributes?

**Comment by jbardin** [comment]
Hi @Kirizan,

If the expression `try(lookup(var.load_balancer, "access_log"), [] )` is resulting in `null`, then that means the `var.load_balancer` map (or object) has a key called `access_log`, and the value is `null`.  `lookup` is not going to fail if the resulting value is null, so the `try` function is not going to return the default. 

The given variable definition will replicate the behavior:
```
variable "load_balancer" {
  type = object({
    access_log = optional(set(string), null)
  })
  default = {}
}
```

The default values you have would fail too, since an empty tuple is also not a valid argument to for_each. If you are dealing with an object like this, a better expression might be:

```
for_each = var.load_balancer.access_log != null ? var.load_balancer.access_log : toset([])
```

Note that the `lookup` function is deprecated in the form used here. if you have a map you should use and index expression like `var.load_balancer["access_log"]` or `var.load_balancer.access_log` if you have an object. If you want a default from a map lookup, you can use `try` with the index expression directly.

Since it appears that you actually need to check for null, you are going to have to use a conditional in some manner, but a more complete example would be needed to give you a better expression to use. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
