### ISSUE TITLE
Support mutually exclusive moves to the same resource

### ISSUE THREAD

**Issue by skeggse** [hashicorp/terraform#32595]
### Terraform Version

```shell
Terraform v1.3.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.52.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tfe v0.41.0
```

### Use Cases

Refactoring can be tricky, and we don't always make good decisions up front. Sometimes we use one resource definition where different definitions would be preferable. Sometimes we use variant resource definitions where one would be preferable. Supporting peculiar yet unambiguous `moved` declarations would be lovely - places where there are multiple `moved` blocks that either pull from or push to the same resource, but where there's only one actual source or destination resource existing in the actual state would be great.

### Attempted Solutions

`tf state mv` or

```tf
# Even though at most one of the tfe_team_access.access["security_engineering"] and
# tfe_team_access.access["enterprise_technology"] exist in a given module instance, this still
# produces an error.
moved {
  from = tfe_team_access.access["security_engineering"]
  to   = tfe_team_access.workspace_owner
}

moved {
  from = tfe_team_access.access["enterprise_technology"]
  to   = tfe_team_access.workspace_owner
}
```

```
Error: Ambiguous move statements
[...]
Each resource instance can have moved from only one source instance.
```

### Proposal

Support multiple `moved` blocks targeting _either_ the same source or the same destination address, provided only one of the `moved` blocks matches a concrete resource.

**Comment by apparentlymart** [comment]
Hi @skeggse! Thanks for this feature request.

One of the rules we made for ourselves when designing `moved` blocks is that the validity or not of a `moved` block must be decided entirely based on the configuration and not rely on any information from the state. This was to help avoid someone accidentally writing a `moved` block that only works against one state but is ambiguous when evaluated against another.

Of course in your case you explicitly _want_ to create that ambiguity: you essentially want to promise Terraform that you'll never use this module with any prior state that has both `security_engineering` and `enterprise_technology` instance keys defined together, and then have it fail dynamically at runtime if that isn't true.

It is technically possible to do that but I think we'll need to decide whether and how to change our original design constraints to support it. I assume we'd want to somehow make it an explicit opt-in so that folks who don't have this need don't lose the original guarantee that if a `moved` block is valid then it's valid across all instances of the module.

With that said, I wonder if we can find a different way to model what you need with today's Terraform. If I'm understanding your situation correctly I think it should be possible to model it as "chained" move blocks, like this:

```hcl
moved {
  from = tfe_team_access.access["security_engineering"]
  to   = tfe_team_access.access["enterprise_technology"]
}

moved {
  from = tfe_team_access.access["enterprise_technology"]
  to   = tfe_team_access.workspace_owner
}
```

In this example I've effectively described this to Terraform as two separate refactoring changes: first, we renamed the `"security_engineering"` key to `"enterprise_technology"`, and then separately we refactored that instance be the single instance of `tfe_team_access.workspace_owner`.

The way I ordered this is arbitrary in your case because you know that you'll never have both. But this change should satisfy Terraform because it's now unambiguous even if you _do_ have a state with both keys defined: the `"enterprise_technology"` instance is the one that would get moved into `tfe_team_access.workspace_owner`, while the other one would be left behind at a now-obsolete address and so planned for deletion.

But in your happy case where only one or the other is defined, it makes no difference which one is defined because either way Terraform will move it all the way to `tfe_team_access.workspace_owner` in a single step, as if you'd upgraded across many versions of this module in a single step and so were applying the effects of multiple refactoring actions all at once.

Could you give that a try and see if that solves the problem? Thanks again!

**Comment by jonmcewen** [comment]
I found this while struggling with a convergent refactor, and the chained moved blocks trick worked for me.

**Comment by crw** [comment]
Howdy! I am cleaning up old `waiting-response` issues, and it looks like this issue has been resolved through the explanation in https://github.com/hashicorp/terraform/issues/32595#issuecomment-1410981396. Please let me know if there is still an outstanding request. Thanks!
