### ISSUE TITLE
Missing BREAKING CHANGE: for 1.4 releases re lockfile and cache changes

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#32653]
### Terraform Version

```shell
1.4.0-beta1
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

The impact related to https://github.com/hashicorp/terraform/pull/32129, https://github.com/hashicorp/terraform/pull/32494, and https://github.com/hashicorp/terraform/issues/32205 should have been explicitly called out in the `BREAKING CHANGE:` section of the 1.4.0 release notes since this change breaks a lot of people's workflows. I understand that there is a work around, with the opt out flag, but it is a breaking change that people need to implement that opt out flag to preserve the current functionality that we all depend on.

At a bare minimum, it needs to be called out in `UPGRADE NOTES:` instead of just a little sentence in the middle of the `ENHANCEMENTS:` section. 

### Actual Behavior

The information was hidden in a little sentence in the middle of the `ENHANCEMENTS:` section. 

### Steps to Reproduce

Look at https://github.com/hashicorp/terraform/releases/tag/v1.4.0-beta1

### References

- https://github.com/hashicorp/terraform/pull/32129
- https://github.com/hashicorp/terraform/pull/32494
- https://github.com/hashicorp/terraform/issues/32205

**Comment by apparentlymart** [comment]
Hi @joe-a-t,

The upgrade guide for a new minor release will typically be written during the prerelease period, which has only just started today. There will be information about this available in time for the v1.4.0 final release.

The task of doing this is already captured internally in our minor release checklist and so I'm going to close this just because nobody would think to look in GitHub for a task like this and so we're likely to just forget to close it otherwise.

Thanks for pointing this out!
