### ISSUE TITLE
Issues with coalesce function

### ISSUE THREAD

**Issue by arnoldkeiler** [hashicorp/terraform#32709]
### Terraform Version

```shell
Terraform v1.3.5
on linux_amd64
```

### Terraform Configuration Files

None

### Debug Output

> try(coalesce("", "1"), "")
"1"
> try(coalesce([], ["1"]), [])
tolist([])
> try(coalesce({}, {ID = "1"}), {})
tomap({})
>

### Expected Behavior

From the above outputs on terraform console shouldnt the list & map types also return the non-empty list & map which were passed? Or am I assuming something wrong?

### Actual Behavior

Non empty List & Map values not returned

### Steps to Reproduce

terraform console

> try(coalesce("", "1"), "")
"1"
> try(coalesce([], ["1"]), [])
tolist([])
> try(coalesce({}, {ID = "1"}), {})
tomap({})
>

**Comment by apparentlymart** [comment]
Hi @arnoldkeiler,

The documentation for this function says that it returns the first value that isn't either `null` or an empty string. The object value and tuple value you tried here are not null or empty string, so these results seem consistent with the documentation.

The special case for empty string is a holdover for backward compatibility with Terraform v0.11, which did not yet have the concept of "null" and so sometimes used an empty string as a hacky way to represent the absence of something.

Aside from this sort of historical exception to keep older modules working, null values are the correct way to represent something being absent in modern Terraform, because that avoids forcing any particular non-null values to have a special meaning. If you want to test whether a collection or structural value is "empty" in the sense of having no elements/attributes then I suggest using the `length` function and comparing the result to zero. Otherwise, of you want to represent the _absense_ of a collection e.g. in an optional input variable then I'd suggest setting the default value to `null` to represent that the default value isn't set at all.

**Comment by crw** [comment]
Thanks for this question! As it appears to be answered, I am going to close this issue - however, please let me know if there is an open issue I missed when reviewing this issue. Thanks!
