### ISSUE TITLE
Improve `moved` block to support import/delete resources to/from state

### ISSUE THREAD

**Issue by AlexPykavy** [hashicorp/terraform#32715]
### Terraform Version

```shell
Terraform v1.2.8
on windows_amd64
```

### Use Cases

- import existing resources to the Terraform state
- delete resources from the state but don't destroy them

### Attempted Solutions

Using Terraform CLI:
- `terraform import`
- `terraform state rm`

### Proposal

Adjust `moved` blocks to use `null` in the following way:
- to import resources
```
moved {
    from = null
    to   = azurerm_storage_account.main
}
```

- to remove resources
```
moved {
    from = azurerm_storage_account.main
    to   = null
}
```

**Comment by kmoe** [comment]
Thanks for the feature request.

**Comment by AlexPykavy** [comment]
Thanks for accepting it! I can try to start doing smth @jbardin , could you please share your thoughts on this feature, would it be useful?

**Comment by joe-a-t** [comment]
I get how the remove from state would work here, but that does not look feasible as sketched out for importing resources. The reason is that there are a lot of resource types where the information that is needed for importing the resource is not found/cannot be calculated from the terraform configuration block, such as when the import information is a random ID that gets generated by the API that Terraform is interacting with or some parent structure information. So I think in whatever import implementation gets provided, it would have to have a way to pass in the specific value that is expected as the second argument to the `terraform import` command instead of accepting `null` and trying to just figure it out. Something like this would make more sense to me.

```tf
import {
  from = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myresourcegroup/providers/Microsoft.Storage/storageAccounts/myaccount"
  to   = azurerm_storage_account.main
}
```

**Comment by AlexPykavy** [comment]
I agree that there can be cases where `<RESOURCE_ID>` is auto-generated. So introducing `import` block can be more general solution to the issue. On the other hand, we may just treat such cases as exceptions which can be handled only via explicit `terraform import` execution. 

I may be wrong in trying to extend the `moved` block to support this functionality and new blocks should be added like `import` and `state_rm`, but it seemed quite logical to me.

And let me describe a use case I came across. The are 2 Terraform projects with their own states and we need to move some resources from one to another. It can be done via `terraform state mv`. However, we use pipelines to run Terraform from an isolated environment and such manual intervention is inconvenient. Then I remembered about the `moved` block which perfectly suits for this task but only in scope of one state. So, I've created this issue to consider how it can be adjusted :)

**Comment by jbardin** [comment]
Thanks @AlexPykavy  and @joe-a-t!

Yes, importing requires more metadata than would be available in the `moved` block, so there would be no reason to overload the meaning of that block to make it work for another purpose. The use of `null` is probably inappropriate as well, since `moved` operates on addresses and `null` is a value, which would be inconsistent with their use elsewhere in the language.

Since both extending refactoring abilities and import are both being worked on elsewhere, I'm going to close this issue to avoid any confusion with changes to `moved` specifically.

Thanks!
