### ISSUE TITLE
To get state detail by cli

### ISSUE THREAD

**Issue by Gintoms** [hashicorp/terraform#32740]
### Terraform Version

```shell
v1.1.9
```

### Use Cases

After terraform apply, I want to reverse lookup some information from the state file.
Currently I can only use the `terraform show -json` to show the whole json.
I need to get the value of the specific resource by resource addressing just like `terraform state show`.

(i.e., here is a resource defined
```
resource module module_name {
    xxx = xxx
    count = 2
}
```
to get attribute1 from module.module_name[0]
```
terraform show -json module.module_name[0].attribute1
```

### Attempted Solutions

deal with the whole json, too long and inconvenient

**Comment by kmoe** [comment]
Generally this is achieved by using jq, e.g. 
```
terraform show -json | jq '.values.root_module.child_modules[0].resources[] | select(.address == "module.module_name[0].attribute1") | .values'
```

What happens when you try this?

**Comment by Gintoms** [comment]
> Generally this is achieved by using jq, e.g.
> 
> ```
> terraform show -json | jq '.values.root_module.child_modules[0].resources[] | select(.address == "module.module_name[0].attribute1") | .values'
> ```
> 
> What happens when you try this?

Thank you for your response

I aim to support without installing other softwares.
(: In my case, I'm not doing it locally, and requires minimal software installation
Will it be supported?

**Comment by apparentlymart** [comment]
Hi @Gintoms,

We provide JSON output with the expectation that consumers of that output will be writing tailored software to solve a particular problem, and that software will be able to extract the relevant parts of the output itself. I don't expect that we would support any kind of further filtering because different applications have different needs, so it's better for Terraform to just produce all of the data and let the consuming software take the parts needed.

`jq` is one example of software that can filter the output, but in practice most useful use of this output will involve some custom software you wrote, rather than a general-purpose tool like `jq`. Terraform is designed to be integrated with other software, so running it in a minimal environment with no other software installed is not one of our design goals.

**Comment by Gintoms** [comment]
> Hi @Gintoms,
> 
> We provide JSON output with the expectation that consumers of that output will be writing tailored software to solve a particular problem, and that software will be able to extract the relevant parts of the output itself. I don't expect that we would support any kind of further filtering because different applications have different needs, so it's better for Terraform to just produce all of the data and let the consuming software take the parts needed.
> 
> `jq` is one example of software that can filter the output, but in practice most useful use of this output will involve some custom software you wrote, rather than a general-purpose tool like `jq`. Terraform is designed to be integrated with other software, so running it in a minimal environment with no other software installed is not one of our design goals.

Ok, Thanks anyway
