### ISSUE TITLE
When changing a sensitive variable in terraform to an empty string terraform plan doesn't pick up on the changes

### ISSUE THREAD

**Issue by dreinhardt-terminus** [hashicorp/terraform#32757]
### Terraform Version

```shell
1.3.0
```

### Terraform Configuration Files

```terraform
module "example" {
  source = "./modules/example"

  example_var   = ""
}
```
within module:
```terraform
variable "example_var" {
  description = "Example variable"
  type        = string
  sensitive   = true
}

resource "kubernetes_secret_v1" "example_secret" {
  metadata {
    name      = "example"
    namespace = "example"
  }

  data = {
    example = var.example_var
  }
  }
}
```

### Debug Output

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

### Expected Behavior

When changing a sensitive value to an empty string (when it previously contained a value). I would expect terraform to show the change within the plan and attempt the change on the apply.

### Actual Behavior

Terraform plan shows no changes and no changes are made on apply.

### Steps to Reproduce

1. Put in the above config (with a value in the variable).
2. Initialize, plan, and apply.
3. Change the variable to an empty string.
4. Run terraform plan.
5. Plan output shows no changes.

**Comment by jbardin** [comment]
Hello @dreinhardt-terminus,

The fact that the value is sensitive should make no difference in the resource's plan, since that metadata is not sent to the provider. The explanation for this behavior would be that the provider is seeing the empty string as an unset value, and returning the prior value as a computed attribute in the plan instead.  You can raise the directly with the provider in the provider's project repository, linked from the their registry page.

Thanks!
