### ISSUE TITLE
null_resource provisioner "remote-exec" randomly dies with wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by azt3k** [hashicorp/terraform#32816]
### Terraform Version

```shell
Terraform v1.3.9
on darwin_arm64
```

### Terraform Configuration Files

```terraform
resource "null_resource" "web" {
  provisioner "file" {
    source      = "path/to/script"
    destination = "/tmp/setup"
  }
  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/setup",
      "/tmp/setup"
    ]
  connection {
    host = "1.2.3.4"
    type  = "ssh"
    user  = "ubuntu"
    password    = ""
    private_key = "${file(/path/to/private/key)}"
    agent       = false
  }
}
```

### Debug Output

This is hard to capture as the issue is intermittent. If I manage to capture it with a trace on I will update the issue.

```
│ Error: remote-exec provisioner error
│
│   with null_resource.web,
│   on _terraform.main.tf line 930, in resource "null_resource" "web":
│  930:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1899529462.sh": wait: remote command exited without exit status or exit signal
╵
Releasing state lock. This may take a few moments...
```

### Expected Behavior

It should reliably execute to completion

### Actual Behavior

- It randomly (10-30% of the time) does not work and dies with: `wait: remote command exited without exit status or exit signal`
- 99.9% of the time it works if you run apply again

### Steps to Reproduce

- If you run apply 10 times and each time it executes the script it will fail at least once

### Additional Context

- this has only been an issue for me in the last 12-18 months, previously it worked reliably
- Have tried using a cloud init script to set the keep alive params as outlined here: https://github.com/hashicorp/terraform/issues/18517, however this had no impact.

### References

https://github.com/hashicorp/terraform/issues/18517

**Comment by jbardin** [comment]
Hi @azt3k,

Thanks for filing the issue. I think this problem need to be debugged on the server side to see exactly what the ssh daemon is doing at the time of the error. The error is not something terraform can cause, the remote command being executed over ssh is not returning correctly, possibly because of something killing the remote ssh process. The trace logs from Terraform may help, but the debug logs from the server are probably going to be the most informative.

Thanks!

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
