### ISSUE TITLE
Request for new command/API to download Terraform cloud-generated plan and artifacts

### ISSUE THREAD

**Issue by moelasmar** [hashicorp/terraform#32844]
### Terraform Version

```shell
Terraform v1.3.9
```

### Use Cases

When utilizing Terraform cloud for a project, the `terraform plan` or `terraform apply` commands are executed remotely on the cloud as expected. However, I'm looking for a way to retrieve the resultant plan within Terraform cloud, as well as acquire any created artifacts (such as zip files) when performing `terraform apply`.

### Attempted Solutions

The solution can be a new command or API that enables me to retrieve the produced plan and any other artifacts.

**Comment by apparentlymart** [comment]
Hi @moelasmar! Thanks for this feature request.

There are already some operations in the Terraform Cloud API which represent what I think you are describing:

* [Get run details](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#get-run-details) is a good entry point to get the specific URLs/IDs required for the others I'm about to list.
* [Show a plan](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/plans#show-a-plan) retrieves the metadata about a plan.
* [Retrieve the JSON execution plan](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/plans#retrieve-the-json-execution-plan) retrieves equivalent output to what `terraform show -json PLANFILE` would achieve for a saved plan on the command line.
* [Show an apply](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/applies#show-an-apply) retrieves the metadata about the process of applying a plan.

You specifically mentioned "created artifacts (such as zip files)" but Terraform doesn't produce any artifacts like that, so I'm not sure what you mean by that part. If you can say more about what kind of artifact you are expecting to retrieve then I'll see if there's already a way to retrieve it or, if not, we could make this feature request specifically about whatever is missing from the above.

Thanks!

**Comment by moelasmar** [comment]
Hello @apparentlymart .. Thank you for your reply, I will go through the suggested APIs to check if t covers my need or not.
Regarding the generated artifacts, what I mean is that if I added some resource in a terraform project that has a local-exec provisioner to run some script that do some logic and then create a zip file that I use to deploy a Lambda function to AWS account. I am asking if it is possible to download this generated file or not.

**Comment by apparentlymart** [comment]
Hi @moelasmar,

Terraform Cloud does not retain anything from the filesystem after running `terraform apply` because Terraform is primarily designed for managing remote objects via network APIs. Although you _can_ use Terraform to modify files on local disk just because providers are arbitrary machine code, it isn't really an intended part of Terraform's design and so Terraform Cloud doesn't have any special support for it.

If you want to retain the artifacts you've generated during a Terraform run I would recommend telling Terraform to explicitly upload them to somewhere outside of the ephemeral filesystem where Terraform is running, such as using the `aws_s3_object` resource type from the `hashicorp/aws` provider to upload the files into Amazon S3.

**Comment by crw** [comment]
Howdy. I am cleaning up old `waiting-response` issues. I believe this issue may be "asked-and-answered" based on the discussion. Please let me know if there is an open feature request in this report that I am missing. Thanks!
