### ISSUE TITLE
Error: Failed to request discovery document: Get "https://app.terraform.io/.well-known/terraform.json"

### ISSUE THREAD

**Issue by nibblesnbits** [hashicorp/terraform#32862]
### Terraform Version

```shell
Terraform v1.4.0
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0
+ provider registry.terraform.io/hashicorp/azurerm v3.47.0

Your version of Terraform is out of date! The latest version
is 1.4.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
terraform {
  cloud {
    organization = "theunad"

    workspaces {
      name = "mono"
    }
  }
}
```

### Debug Output

[https://gist.github.com/nibblesnbits/4ac891a6b28848864658561f6cc944ed](https://gist.github.com/nibblesnbits/4ac891a6b28848864658561f6cc944ed)

### Expected Behavior

Should connect to Terraform Cloud

### Actual Behavior

Output is an error: `Error: Failed to request discovery document: Get "https://app.terraform.io/.well-known/terraform.json": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

### Steps to Reproduce

1. `terraform init`

### Additional Context

This also occurs with `terraform login`.

**Comment by kmoe** [comment]
According to the error message, it looks like there was a problem connecting to app.terraform.io, i.e. a network issue. We would expect this to be a transient issue. Is this still happening?

**Comment by nibblesnbits** [comment]
No, it's not a transient issue.  I tried dozens of times, both back to back and several minutes apart.
Hitting those URLs through a browser at any given point in between or immediately after pulled up the files just fine.

**Comment by sushant-kapoor17** [comment]
Hello, 
I am able to curl this URL [https://app.terraform.io/.well-known/terraform.json](https://app.terraform.io/.well-known/terraform.json) and it successfully returns the following response.
```{
  "modules.v1": "/api/registry/v1/modules/",
  "providers.v1": "/api/registry/v1/providers/",
  "motd.v1": "/api/terraform/motd",
  "state.v2": "/api/v2/",
  "tfe.v2": "/api/v2/",
  "tfe.v2.1": "/api/v2/",
  "tfe.v2.2": "/api/v2/",
  "versions.v1": "https://checkpoint-api.hashicorp.com/v1/versions/"
}
```

To further confirm this,I tried running `terraform login` with v1.4.0 and the debug log successfully connects to the url, as shown below:
```
2023-03-17T00:04:03.262+0530 [INFO]  Terraform version: 1.4.0
2023-03-17T00:04:03.262+0530 [DEBUG] using github.com/hashicorp/go-tfe v1.18.0
2023-03-17T00:04:03.262+0530 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.0
2023-03-17T00:04:03.262+0530 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-03-17T00:04:03.262+0530 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-03-17T00:04:03.262+0530 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-03-17T00:04:03.262+0530 [INFO]  Go runtime version: go1.19.6
2023-03-17T00:04:03.262+0530 [INFO]  CLI args: []string{"/home/neo/.tfenv/versions/1.4.0/terraform", "login"}
2023-03-17T00:04:03.262+0530 [DEBUG] Attempting to open CLI config file: /home/neo/.terraformrc
2023-03-17T00:04:03.262+0530 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory /home/neo/.terraform.d/plugins
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory /home/neo/.local/share/terraform/plugins
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory /usr/share/ubuntu/terraform/plugins
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2023-03-17T00:04:03.262+0530 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2023-03-17T00:04:03.262+0530 [INFO]  CLI command args: []string{"login"}
2023-03-17T00:04:03.262+0530 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
Terraform will request an API token for app.terraform.io using your browser.
```

My guess is there is some network configuration on your machine which has caused this issue. It would be good idea to check if you have got some proxy settings which are causing the timeout issue. It looks like you are on a windows environment.
Please set the proxy properties as described below in command prompt(temporary) or permanently in Windows environment variables and try running terraform commands again.

```
set HTTP_PROXY=http://{proxy-url}:{port}/
set HTTP_USER={username}
set HTTP_PASSWORD={password}
```


Hope this helps.

Cheers,
Sushant

**Comment by sushant-kapoor17** [comment]
There's also a possibility that your browser has got proxy settings embedded and is able to use them, whereas the terminal does not ?

**Comment by nibblesnbits** [comment]
I don't use any sort of proxy on my machine, but I do use 1.1.1.1 DNS servers.
But I don't have any other issues connecting to all those same URLs from any other context.
I'll reset my network configuration to a more normal setup and see what happens.

**Comment by nibblesnbits** [comment]
So yeah, turns out everything works fine when I have my DNS config set to defaults (automatic).  Any idea why this would be the case?

**Comment by sushant-kapoor17** [comment]
Hello, Thank you so much for response and trying it with DNS config set to default. 

There are not many things I can think of .... but here are a few things, if it helps:
1. Please try running this curl command with DNS set as `1.1.1.1 `
`while true; do curl -s -o /dev/null -w "%{http_code}" https://app.terraform.io/.well-known/terraform.json ; echo ; sleep 1 ; done`. 

This simply runs an indefinite curl for `app.terraform.io` URI to retrieve well formed JSON and returns the response code. If there's anything other than `200`, usually `28` is for timeout , then it might help with something. You can then change curl and remove the -o tag with http_code and switch to -v to get verbose output and see what really caused the timeout, if it does show something relevant. Although the thing that still bothers me , is how it works each time with your browser ? certs may be ? 

2. There a couple of old posts on the internet where it seems that , this issue could occur due to ISP or customer specific old routers firmware which tend to treat `1.1.1.1` as a special address. One of the resolutions mentioned , was to switch to alternate address `1.0.0.1`. However, I am not sure, if this is really true in your case, but worth a try. Here's a link for one of the post:
[https://superuser.com/questions/1625998/why-are-dns-queries-using-cloudflares-1-1-1-1-server-timing-out](https://superuser.com/questions/1625998/why-are-dns-queries-using-cloudflares-1-1-1-1-server-timing-out)

3. Looking back at the initial error message `net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers` . This basically suggests the upstream failed to resolve the URL, which does point to your DNS server i.e. 1.1.1.1. Although, it could simply be your ISP/region specific thing blocking this. May I request you to please try visiting this URL and see if you notice any issues. [ https://www.fastly-debug.com/ ](https://www.fastly-debug.com/)  and you can reach out to support@fastly.com and see if they can help out with something. 

I was going to finish with these suggestions, before I found an interesting issue, which seemed similar to your problems and it looks like this could be the issue with terraform cloud and it is a long running one as well.. Strangely, there's someone who suggested using 1.1.1.1 DNS to resolve the issue :wink:  .  

Here's the link for the issue : [https://github.com/hashicorp/terraform/issues/22774](https://github.com/hashicorp/terraform/issues/22774)

This issue has been currently marked as `resolved` with the following comments and updates as in v1.4 :
```
We addressed two areas as part of this issue:
 1. We've improved the performance of the endpoint that returns the discovery document in TFC. This improvement is available now! Hopefully with better performance we'll have fewer overall discovery document request errors.
 2. In the next terraform release (1.4), if you do run into this problem, the error message will have more context indicating that it's most likely a network issue.
  ```

so, in my opinion, this could likely be the issue you are looking for and it is worth either tagging the developer in the issue or you can email at tf-cloud@hashicorp.support or [open a request](https://support.hashicorp.com/hc/en-us/requests/new), as someone suggested in the issue.However, It won't be a bad thing to try atleast the first 2 options , I discussed in the post, before diving deep into this issue. 
Hope this helps.
Thanks.

**Comment by crw** [comment]
Thanks for the great research, @sushant-kapoor17! As this appears to be an issue with networking as opposed to an inherent issue with Terraform, I am going to close this issue. Thanks for the report, @nibblesnbits!
