### ISSUE TITLE
Documentation on https://www.terraform.io/docs/ not updated

### ISSUE THREAD

**Issue by berendt** [hashicorp/terraform#3290]
Some time ago (~ 3 weeks) #3090 (a pure documentation change) was merged. This change is not yet available on https://www.terraform.io/docs/. The documentation on https://www.terraform.io/docs/ should be published more often. If the published documentation is related to the latest release it would be nice to publish the current (master) documentation somewhere.

**Comment by catsby** [comment]
Hey @berendt –

You're absolutely right, we need to merge and push doc fixes for existing functionality more often. We dropped the ball here some with the ramp up to HashiConf and other activity, we'll do better with the upcoming release(s). 

> if the published documentation is related to the latest release it would be nice to publish the current (master) documentation somewhere.

We _try_ to maintain documentation in a release branch, e.g. `release/v0.6.3` and cherry-pick documentation updates into that branch, assuming those changes are for existing functionality (not related to changes added in `master` since the release). It's a manual process and we've fallen behind there. 

I did go ahead and cherry-pick the commit in question (thanks again for that), and re-deployed the site. You can see your changes are live now:

- https://terraform.io/docs/providers/openstack/index.html

Thanks for raising this issue. It's a manual process and I'll do my best to be more diligent about it until we figure a more automated means of keeping them up to date.

**Comment by berendt** [comment]
@catsby Thanks for the update and the explanation.
