### ISSUE TITLE
Removing a block from the middle of block list

### ISSUE THREAD

**Issue by diPhantxm** [hashicorp/terraform#32918]
### Terraform Version

```shell
Terraform v1.3.5
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.4.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

I work at Yandex and we have our terraform provider. I'm kinda new to terraform and I faced an issue with removing a block from the middle of block list. For example we have: 
```terraform
resource "yandex_mdb_postgresql_cluster" "default" {
  name        = "hosts"
  environment = "PRODUCTION"
  network_id  = yandex_vpc_network.mdb-pg-test-net.id

  config {
    version = "13"
    resources {
      resource_preset_id = "s2.micro"
      disk_type_id       = "network-ssd"
      disk_size          = 10
    }
  }

  host_master_name = "a3"

  host {
    name = "a1"
    subnet_id = yandex_vpc_subnet.mdb-pg-test-subnet-a.id
    zone = "ru-central1-a"
  }
  host {
    name = "a2"
    subnet_id = yandex_vpc_subnet.mdb-pg-test-subnet-b.id
    zone = "ru-central1-b"
  }
  host {
    name = "a3"
    subnet_id = yandex_vpc_subnet.mdb-pg-test-subnet-c.id
    zone = "ru-central1-c"
  }
}
```

When I remove the first `host`, `terraform plan` shows:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # yandex_mdb_postgresql_cluster.default will be updated in-place
  ~ resource "yandex_mdb_postgresql_cluster" "default" {
        id                  = "c9qq8b9ngc1doq46getb"
        name                = "hosts"
        # (11 unchanged attributes hidden)

      ~ host {
          ~ fqdn             = "***HIDDEN***" -> "***HIDDEN***"
          ~ name             = "a1" -> "a2"
          ~ zone             = "ru-central1-a" -> "ru-central1-b" 
        }
      ~ host {
          ~ assign_public_ip = false
          ~ fqdn             = "***HIDDEN***"
          ~ name             = "a2" -> "a3"
          ~ zone             = "ru-central1-b" -> "ru-central1-c" 
        }
      - host {
          - assign_public_ip = false -> null
          - fqdn             = "***HIDDEN***" -> null
          - name             = "a3" -> null
          - priority         = 0 -> null
          - role             = "MASTER" -> null
          - subnet_id        = "e9bphpro3ceue1k78irh" -> null
          - zone             = "ru-central1-c" -> null
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 1 to destroy.
```

As you see it suggests to change first 2 hosts and remove the third. This is an unexpected behavior.

### Attempted Solutions

I've tried changing it from `list` to `set`, the removal worked just fine, but I figured out that I couldn't change any element anymore until I remove one (maybe I had a bug in the code, not sure).
I've seen the solution for the same issue but for resources #14275, but it can only be used for resources.

### Proposal

Maybe there is a solution already, but I just don't know about it. I can identify all elements with giving a name to each host, but I don't know how to use it to solve the problem.

**Comment by jbardin** [comment]
Hi @diPhantxm,

A list is an ordered collection of values, identified by their respective indexes, so logically when you remove an item from the front of a list, the rest of the list is going have a different index. The same remaining items are still sent to the provider, and the provider can choose to handle those however it needs, but there isn't really anything else that can be done when working with an array-type data structure.

While the linked issue is about resource instances rather than attributes, the same general logic still applies. If you don't want a strictly ordered series of values, you need to use an unordered data structure like a set or map.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
