### ISSUE TITLE
Multiline support in Terraform console

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/terraform#32954]
### Terraform Version

```shell
Any/latest
```

### Use Cases

I would like to be able to post multiple lines into `terraform console`. While the console as it is is very useful, there are circumstances where being able to cut-and-paste more syntactically valid yet complex code is precluded by this limitation. See also https://discuss.hashicorp.com/t/multiline-expression-in-terraform-console/23452

### Attempted Solutions

N/A

### Proposal

Please include multiline support in `terraform console`. :)

**Comment by crw** [comment]
Thanks for this request!

**Comment by interone-ms** [comment]
Joining in as well. Our use case is developing deeply nested for expressions.

**Comment by nnsense** [comment]
"tab" completion would be nice too

**Comment by scott-culverhouse** [comment]
Whilst we are at history like shell history please ;-)

**Comment by siourdas-vasilis** [comment]
Not rocket science :)

**Comment by apparentlymart** [comment]
Hi all,

I worked on this in https://github.com/hashicorp/terraform/pull/34822 without realizing this issue was open for it.

My initial implementation was focused on making it possible to paste in multi-line expressions, since that was relatively easy to achieve without totally rewriting the console input to use a multiline-capable readline library. I hope that in future it'll be extended to support multiline _editing_ too, but if I'd chosen that scope then it would've been far too big an effort to do anything at all, so this is a compromise to deal with what seems to be the main case.

The original request in this issue was also about pasting, so I'm going to consider this issue to be "done" now that change is merged.

I see some other folks making other unrelated suggestions about the console, like persisted history and tab completion. Those are not in scope for this issue but are already covered by https://github.com/hashicorp/terraform/issues/27370 and https://github.com/hashicorp/terraform/issues/27369, so please follow (and potentially vote on) those issues if you are interested in those additional capabilities.
