### ISSUE TITLE
Terraform base64decode function is including <<-EOT EOT in the outputs

### ISSUE THREAD

**Issue by kirankumar-badiger** [hashicorp/terraform#32981]
### Terraform Version

```shell
Using OCI ORM Stack to provision the resources with terraform
```

### Terraform Configuration Files

```
data "oci_secrets_secretbundle" "bundle" {
  secret_id = var.secret_ocid
}

locals {
secret_content = base64decode(data.oci_secrets_secretbundle.bundle.secret_bundle_content.0.content)
}

output "secret_content" {
    value = local.secret_content
}
```

### Debug Output

Using OCI ORM Stack

### Expected Behavior

Only content inside the OCI vault secret should be displayed, should not include the `EOT` keyword

### Actual Behavior

```
<<-EOT
        ActualSampleText
    EOT
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @kirankumar-badiger,

Terraform renders the human readable output in a format similar to the configuration to make it more easily recognizable, so in this case a multi-line output would have heredoc delimiters.

If you want machine readable, you can use `-raw` or `-json` flags.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
