### ISSUE TITLE
/* comment closed by quoted */

### ISSUE THREAD

**Issue by BroMattMiller** [hashicorp/terraform#32999]
### Terraform Version

```shell
Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
```

### Terraform Configuration Files

```
/*
variable "test" {
  type        = string
  default = "*/"
}
*/
```

### Debug Output

https://gist.github.com/BroMattMiller/de1ea438decf5f2018ffac9abb50dafe

### Expected Behavior

The terraform console should start.

### Actual Behavior

Errors are printed and the console doesn't start.

### Steps to Reproduce

1.  terraform console

### Additional Context

If the "/" character is removed from the variable's default value, then the console starts.

**Comment by jbardin** [comment]
Hi @BroMattMiller,

Within a multiline comment there is no syntax, so there is no way to disambiguate between a closing `*/` and those same characters which happen to be part of another syntax. The commented text can't be parsed as HCL, because by definition a comment is free form text. The behavior of ending a multi-line comment on the first occurrence of the closing pattern is also consistent with other languages which use the same syntax.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
