### ISSUE TITLE
Infer object default when all fields have defaults

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [hashicorp/terraform#33008]
### Terraform Version

```shell
Terraform v1.4.2
on linux_amd64
```

### Use Cases

When creating configuration for terraform, it's easier to use defaults so we can simplify our logic. 
I want to be able to use defaults in an object partially and totally, and using the same defaults. Therefore this config
```
  nodepool = {
   enabled = true
}
```
and not setting the variable at all should have the same behavior.

### Attempted Solutions

Here's part of my variables right now:
```
variable "nodepool" {
      type = optional(object({
          enabled              = optional(bool, false)
          batchNodeCount       = optional(number, 1)
          nodePoolSoakDuration = optional(string, "3600s")
        }), {
          enabled              = false
          batchNodeCount       = 1
          nodePoolSoakDuration = "3600s"
      })
}
```

This works, but I'm duplicating the defaults

### Proposal

Terraform should infer the default for an `object` if all of its fields have defaults set, allowing for de-duplication of defaults

**Comment by jbardin** [comment]
Hi @AgustinRamiroDiaz,

The syntax you are showing is not valid, so it's unclear why you are adding the default values twice here. Using the variable `default` attribute I think you wills see the behavior you are trying to get:

```
variable "nodepool" {
  type = object({
    enabled              = optional(bool, false)
    batchNodeCount       = optional(number, 1)
    nodePoolSoakDuration = optional(string, "3600s")
  })

  default = {}
}
```

Will result in a default value of 
```
{
  "batchNodeCount" = 1
  "enabled" = false
  "nodePoolSoakDuration" = "3600s"
}
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
