### ISSUE TITLE
number cannot be optional

### ISSUE THREAD

**Issue by c33s** [hashicorp/terraform#33004]
### Terraform Version

```shell
1.4.4
```

### Terraform Configuration Files

```terraform
variable "base_group" {
  type = object({
    #description                       = optional(string)
    parent_id                         = optional(number)
  })
}
```

### Debug Output

-

### Expected Behavior

optional number values should be accepted as optional string values are `description = optional(string)` (this works)

it also does not work with `optional(number, null)` which should lead to the same result. 

sidenote the current error message is not that helpful

### Actual Behavior

```
│ Error: Invalid value for input variable
│
│   on variables.tf line 5:
│    5: variable "base_group" {
│
│ Unsuitable value for var.base_group set using the TF_VAR_base_group
│ environment variable: a number is required.
```

### Steps to Reproduce

```
terraform init
terraform plan
```

**Comment by jbardin** [comment]
Hi @c33s,

Thanks for filing the issue. I'm not able to replicate the error with the example here, using an `optional(number)` value works correctly when supplied via an environment variable, flag or file. Can you show a complete example which doesn't work?

Thanks!

**Comment by jbardin** [comment]
Since this appears to work as expected, I'm going to close out the issue for now. if you have a reproducible test case where it is not working, feel free to reply here or file a new issue. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by c33s** [comment]
@jbardin sorry for not writing back earlier. i wasn't able to reproduce it again. on the next day the error was gone.
