### ISSUE TITLE
data "aws_wafv2_rule" not supported with current TF provider

### ISSUE THREAD

**Issue by AIUPFK1** [hashicorp/terraform#33011]
### Terraform Version

```shell
Terraform v1.2.5
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

Hi Team

We have created the WAF rule grp and rate-base WAF rule inside it, we want to refer to the same in other Terraform resources (lambda env).

As per documentation, https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/waf_rule

equivalent data "aws_wafv2_rule" is present for getting the rule name data source,

Even we don't see any option to get reference
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/wafv2_rule_groupresources

also if possible please suggest a workaround for the same.

Thanks

### Attempted Solutions

Tried by using `data "aws_waf_rule"` https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/waf_rule

But getting below error as waf classic is not supporting for the same -

error -
```
Error: WAF Rules not found for name: <name given- sensitive>
│
│   with data.aws_waf_rule.waf_rule,
│   on main.tf line 8, in data "aws_waf_rule" "waf_rule":
│    8: data "aws_waf_rule" "waf_rule" {
│

```

**Comment by liamcervante** [comment]
Hi @AIUPFK1, thanks for filing this.

The Terraform providers are managed in separate repositories and by separate teams. I think what you're asking could be better answered by the AWS provider team specifically. As such, I will close this issue here and you could open a new one in the [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws) repository directly. They will know more about potential workarounds or any plans they have for future support for this kind of data source.

Thanks!
