### ISSUE TITLE
Documentation: add hyperlink between an argument and its block

### ISSUE THREAD

**Issue by aaronswainonset** [hashicorp/terraform#33022]
### Description

Please let me know if there is a better way to request documentation improvements.

As a whole, the AzureRM provider documentation would be improved if a hyperlink existed between an argument and its block. This is a fairly common feature in documentation.

Using `azurerm_linux_web_app` as an example (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app), the `site_config` argument is documented as:

> `site_config`: (Required) A `site_config` block as defined below.

From this argument, I should be able to easily navigate to the block definition by clicking a hyperlink. Ideally, the words "site_config block" in the argument description would be an anchor link, e.g: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#site_config_block .

**Comment by crw** [comment]
@aaronswainonset Thanks for this request! To be clear, the Registry team does not look at issues in the Core repo, though we often leave these open to track the resolution and for others interested in similar features to discuss. Thanks again for your feedback!

**Comment by aaronswainonset** [comment]
@crw 
I'm not sure who's responsible for the documentation, but I opened this issue in the AzureRM provider repository and it was transferred here by someone else.
Really, it would just be nice to have the documentation updated as I've described. It would make it much better to use.

**Comment by crw** [comment]
@aaronswainonset I see what you mean. I think @tombuildsstuff is saying that this would need to be a feature of the underlying documentation system, e.g. this type of inter-document linking would need to be supported by the Registry's docs rendering system in order to make this change. You can see a quick overview of the documentation generation system here: https://developer.hashicorp.com/terraform/registry/providers/docs#generating-documentation -- meaning, the docgen system would need to support inter-document linking.

**Comment by xiaxyi** [comment]
Thanks @aaronswainonset for raising this issue, seems it's in Hashicorp's backlog. Let's keep monitor the progress here. Wish we could get the fix done soon.

**Comment by opslivia** [comment]
Thank you for this suggestion. The Registry team has constrained resources at the moment. As such, we will likely not be addressing this request this year. I have taken it into our internal backlog.
