### ISSUE TITLE
Problems with `$$releasever` in userdata Template being interpreted (maybe) as process ID

### ISSUE THREAD

**Issue by rpattcorner** [hashicorp/terraform#33025]
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.32.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Terraform Configuration Files

Resource:
```
resource "aws_instance" "spoke-ami-instance" {
  user_data                            = base64encode(templatefile("${path.module}/spoke-ami-user-data.tpl", { none = 1 }))
  ami                                  = data.aws_ami.dev-std-ami.id
  instance_type                        = "t2.micro"
```
The partial entry below is from the invoked Terraform template file,
```
# Add a repository for puppet7
/bin/cat <<EOF > /etc/yum.repos.d/puppet7.repo
[puppet7]
name=Puppetlabs upstream mirror
baseurl=http://yum/yum/puppetlabs/puppet7/el/$$releasever/x86_64/
enabled=1
gpgcheck=1
gpgkey=http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet http://yum/yum/puppetlabs/RPM-GPG-KEY-puppetlabs http://yum/yum/puppetlabs/RPM-GPG-KEY-reductive http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet-20250406
metadata_expire=1800
EOF
```

### Debug Output

No errors in TF run

### Expected Behavior

Expected an escape of the `$$releasever` template portion to be written to the file as `$releasever`

### Actual Behavior

The escape of the `$$releasever` template portion was written to the instance file as:
```
[puppet7]
name=Puppetlabs upstream mirror
baseurl=http://yum/yum/puppetlabs/puppet7/el/1217releasever/x86_64/
enabled=1
gpgcheck=1
gpgkey=http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet http://yum/yum/puppetlabs/RPM-GPG-KEY-puppetlabs http://yum/yum/puppetlabs/RPM-GPG-KEY-reductive http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet-20250406
metadata_expire=1800
```

### Steps to Reproduce

Any template writing (at least) a yum repo file

### Additional Context

This may simply be an unaddressed documentation issue or a peculiar interaction with userdata.  The unexpected four digit value in `baseurl=http://yum/yum/puppetlabs/puppet7/el/**1217releasever**/x86_64/` is very likely an OS interpretation of $$ as the process id.  But it's a common use case, and:

1. The doc doesn't address escaping a pure `$` that I can see, just `${}` sequences for interpretation, and
2. If there is a workaround, it'll probably be useful to many folks

**Comment by crw** [comment]
Thanks for filing this issue.

**Comment by sushant-kapoor17** [comment]
Hello @rpattcorner ,

This issue is probably related to escaping the `$$` , but the key here is to ensure that it is handled in template file in such a way that your resultant file can work. I have tried a fix at my end on your template file and it works for me. I would like to request you to please have a look and give it a try and see if it works for you.

So, to escape the $$ sign and convert it into a resultant `$`, a backslash(`\`) needs to be prefixed. I made the following change in your `spoke-ami-user-data.tpl` file for `baseurl` field. Please note that I have also added curly braces across `releasever` since it's being used inside a string.

```javascript
baseurl=http://yum/yum/puppetlabs/puppet7/el/\$${releasever}/x86_64/
```
 This change will ensure that the `templatefile` will convert this into `\$` instead, as confirmed below. 

```javascript
$terraform console

> templatefile("${path.module}/spoke-ami-user-data.tpl", { none = 1 })
<<EOT
# Add a repository for puppet7
/bin/cat <<EOF > /etc/yum.repos.d/puppet7.repo
[puppet7]
name=Puppetlabs upstream mirror
baseurl=http://yum/yum/puppetlabs/puppet7/el/\${releasever}/x86_64/
enabled=1
gpgcheck=1
gpgkey=http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet http://yum/yum/puppetlabs/RPM-GPG-KEY-puppetlabs http://yum/yum/puppetlabs/RPM-GPG-KEY-reductive http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet-20250406
metadata_expire=1800
EOF
EOT
>  

```

And, to finally prove this works in your resultant file as expected, Here's the result of `cat`command on the generated file:

`command`:
```javascript
cat <<EOF > /etc/yum.repos.d/puppet7.repo
[puppet7]
name=Puppetlabs upstream mirror
baseurl=http://yum/yum/puppetlabs/puppet7/el/\${releasever}/x86_64/
enabled=1
gpgcheck=1
gpgkey=http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet http://yum/yum/puppetlabs/RPM-GPG-KEY-puppetlabs http://yum/yum/puppetlabs/RPM-GPG-KEY-reductive http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet-20250406
metadata_expire=1800
EOF
```

`Generated puppet7.repo file`
```bash
[puppet7]
name=Puppetlabs upstream mirror
baseurl=http://yum/yum/puppetlabs/puppet7/el/${releasever}/x86_64/
enabled=1
gpgcheck=1
gpgkey=http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet http://yum/yum/puppetlabs/RPM-GPG-KEY-puppetlabs http://yum/yum/puppetlabs/RPM-GPG-KEY-reductive http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet-20250406
metadata_expire=1800
```

Please note, the `baseurl` field in the output of `cat` command is `baseurl=http://yum/yum/puppetlabs/puppet7/el/${releasever}/x86_64/`, i.e. with a single `$` sign , which is basically what was desired. 

Hope this helps in fixing your issue. 

Thanks !

**Comment by rpattcorner** [comment]
Very nice!  The braces, while formally correct, don't seem to be required in (at least 1.3.7) Terraform, so template source like this:
```
baseurl=http://yum/yum/puppetlabs/puppet7/el/\$releasever/x86_64/
```

yields the following on the resultant server:
```
[puppet7]
name=Puppetlabs upstream mirror
baseurl=http://yum/yum/puppetlabs/puppet7/el/$releasever/x86_64/
enabled=1
gpgcheck=1
gpgkey=http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet http://yum/yum/puppetlabs/RPM-GPG-KEY-puppetlabs http://yum/yum/puppetlabs/RPM-GPG-KEY-reductive http://yum/yum/puppetlabs/RPM-GPG-KEY-puppet-20250406
metadata_expire=1800
```
Which works just fine!

Many thanks for the path forward.  Maybe a comment in documentation might help our successors?

**Comment by crw** [comment]
> Maybe a comment in documentation might help our successors?

Hi @rpattcorner, if I am not mistaken the Terraform `templatefile` escaping is documented and working correctly, whereas the issue was figuring out the right escape sequences for the underlying shell that would be interpreting the result of the `templatefile` command. Since the underlying shell could, presumably, be anything, I'm not sure that there is much for us to say that would be widely useful. Let me know if I am missing a nuance here. 

Thanks!
