### ISSUE TITLE
Unable to 👍 - Allow interpolations in lifecycle attributes

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#33031]
### Terraform Version

```shell
v1.4.5
```

### Terraform Configuration Files

```terraform
variable "prevent_destroy" {
  default = true
}

resource "null_resource" "main" {
  lifecycle {
    prevent_destroy = "${var.prevent_destroy}"
  }
}
```

### Debug Output

```
│ Error: Variables not allowed
│ 
│   on main.tf line 7, in resource "null_resource" "main":
│    7:     prevent_destroy = var.prevent_destroy
│ 
│ Variables may not be used here.
╵
╷
│ Error: Unsuitable value type
│ 
│   on main.tf line 7, in resource "null_resource" "main":
│    7:     prevent_destroy = var.prevent_destroy
│ 
│ Unsuitable value: value must be known
```

### Expected Behavior

I should be able to 👍 https://github.com/hashicorp/terraform/issues/3116 so that it can get properly prioritized to address this issue since it is a huge issue for a ton of people and the root of many many many other issues like https://github.com/hashicorp/terraform-provider-google/issues/10168

### Actual Behavior

Unable to 👍 that issue for the last 6 years so it looks like no one cares about the issue when it would most likely have the most 👍 of any Terraform issue if it was possible for users to 👍 it.

### Steps to Reproduce

1. `terraform validate`

### References

- https://github.com/hashicorp/terraform/issues/3116
- https://github.com/hashicorp/terraform/issues/24658
- https://github.com/hashicorp/terraform/issues/22544
- https://github.com/hashicorp/terraform-provider-google/issues/10168
- https://github.com/hashicorp/terraform-provider-google/issues/7868
- https://github.com/hashicorp/terraform-provider-google/issues/2078
- https://github.com/hashicorp/terraform-provider-google/issues/13661

**Comment by jbardin** [comment]
Hi @joe-a-t!

Thanks for compiling these issues. The original issue #3116 is probably no longer relevant as written -- interpolation is possible and used within `lifecycle`, but how its used depends on each individual feature of a resource's lifecycle. Asking for interpolation for `lifecycle` in general is not going to effectively change anything.

It seems you are mostly concerned with `prevent_destroy` specifically, and one reason that has not changed because it cannot do what them majority of users want it to do regardless of the ability to interpolate the value. Controlling how something is destroyed from the config doesn't work when that configuration can be removed entirely. If better control over the ability to destroy a resource is what you're after, #22544 covers this (and already shows a lot of support, but I think #24658 is probably where users should indicate their support for a more useful feature in general (or with the individual provider issues where that is applicable, since absolute control can only ever be applied outside of Terraform).

Since there is no specific bug to address here, I'm going to close the issue. If you have other concerns about enhancements which are not addressed by existing issues already, we can handle those individually in separate issues.

Thanks!

**Comment by joe-a-t** [comment]
@jbardin can you add a comment to https://github.com/hashicorp/terraform/issues/3116 pointing at the other issues? If you think 3116 is entirely invalid as written, then it should probably also get closed with pointers to the successive issues.

Right now, if you find https://github.com/hashicorp/terraform/issues/3116, it is impossible to find any of the other issues like https://github.com/hashicorp/terraform/issues/22544 that have sprung out of it because, given how the issue is locked, GitHub no longer adds a link to any other issue that references it so it's just a super frustrating black hole user experience.

**Comment by crw** [comment]
Yes, I have closed. https://github.com/hashicorp/terraform/issues/3116#issuecomment-1507612949

Thanks for kicking off this discussion @joe-a-t. We really appreciate it, and appreciate your robust dive into the relevant references.
