### ISSUE TITLE
Invalid attribute name while using each value after a dot

### ISSUE THREAD

**Issue by it-ben** [hashicorp/terraform#33036]
### Terraform Version

```shell
Terraform v1.4.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
locals {
    targets = {
    "taget1" = { targetport = 1234, stage = "dev" } 
    "target2" = { targetport = 1234, stage = qa }
    "target3" = { targetport = 1234, stage = prod }
  }
}

resource "aws_lb_listener_rule" "somerulename" {
  for_each = local.targets
  listener_arn = aws_lb_listener.default_https.arn

  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.[each.key].arn
  }

  condition {
    host_header {
      values = ["${each.key}.somedomain.com"]
    }
  }
}
```

### Debug Output

Error: Invalid attribute name
│
│   on central_alb_rules.tf line 299, in resource "aws_lb_listener_rule" "somerulename":
│  299:     target_group_arn = aws_lb_target_group.[each.key].arn
│
│ An attribute name is required after a dot.

### Expected Behavior

The arn should be filled with the each key

### Actual Behavior

Terraform expects a letter after a dot and doesn't accept a square bracket, brace or dollar.

### Steps to Reproduce

This is just a example, you can reproduce it with any other map and specifying an arn or id or else with something from your map.

**Comment by jbardin** [comment]
Hi @it-ben,

A dot must be followed by an attribute name, but you have a typo where you used a `.[each.key]` rather than `[each.key]` to index a value.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
