### ISSUE TITLE
"Failed to request discovery document" errors have returned

### ISSUE THREAD

**Issue by GavBurke** [hashicorp/terraform#33044]
### Terraform Version

```shell
Terraform v0.15.5
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "0.15.5"

  backend "gcs" {
  }

  required_providers {
    google = {
      source = "hashicorp/google"
      version = "3.66.1"
    }
    
    random = {
      source = "hashicorp/random"
      version = "3.4.3"
    }
  }
}
```

But also (it's not just one provider else I would go to them, it's the TF registry URL giving the error)

```terraform
terraform {
  required_version = "0.15.5"

  backend "azurerm" {
    container_name = "tfstate"
  }

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.92.0"
    }

    random = {
      source = "hashicorp/random"
      version = "3.4.3"
    }
  }
}
```

### Debug Output

Running Terraform init against a provider that has already downloaded is gving:

```
Using previously-installed hashicorp/azurerm v2.92.0
STDERR:

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/random: could not connect to registry.terraform.io: Failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": net/http:
request canceled while waiting for connection (Client.Timeout exceeded
while awaiting headers)
```

Whilst also getting the same error from hashicorp for Google provider too
```
Initializing provider plugins...
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/google from the dependency lock file
- Using previously-installed hashicorp/google v3.66.1
  STDERR:
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/external: could not connect to registry.terraform.io: Failed to
│ request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": net/http:
│ request canceled while waiting for connection (Client.Timeout exceeded
│ while awaiting headers)
```

And also getting the issue for _new_ inits
``` 
Initializing provider plugins... 
- terraform.io/builtin/terraform is built in to Terraform 
- Finding hashicorp/azurerm versions matching "2.92.0"... 
- Finding hashicorp/google versions matching "3.66.1"... 
- Finding latest version of hashicorp/null... 
- Finding hashicorp/kubernetes versions matching "2.14.0"... 
- Finding hashicorp/random versions matching "3.4.3"... 
- Installing hashicorp/google v3.66.1... 
- Installed hashicorp/google v3.66.1 (signed by HashiCorp) 
- Installing hashicorp/null v3.2.1... 
- Installed hashicorp/null v3.2.1 (signed by HashiCorp) 
- Installing hashicorp/kubernetes v2.14.0... 
- Installed hashicorp/kubernetes v2.14.0 (signed by HashiCorp) 
- Installing hashicorp/random v3.4.3... 
- Installed hashicorp/random v3.4.3 (signed by HashiCorp) 
Error: Failed to query available provider packages 
Could not retrieve the list of available versions for provider 
hashicorp/azurerm: could not connect to registry.terraform.io: Failed to 
request discovery document: Get 
"https://registry.terraform.io/.well-known/terraform.json": net/http: request 
canceled while waiting for connection (Client.Timeout exceeded while awaiting 
headers) 
```

And another form of the error
```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/google-beta from the dependency lock file
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/google from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Reusing previous version of ... (610 more, please see e.stdout)
  STDERR:
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/random: could not connect to registry.terraform.io: Failed to
│ request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": net/http:
│ request canceled while waiting for connection (Client.Timeout exceeded
│ while awaiting headers)
```

### Expected Behavior

The provider should just be used

### Actual Behavior

Getting an error trying to connect to Terraforms Registry

### Steps to Reproduce

1. 'terraform init'

Randomly errors with a connection to TF's registry

### Additional Context

We have changed absolutely nothing, then this issue started from midnight Friday 14th April, so has been happening inconsistently all Saturday, Sunday and today.  The issue happens from our cloud Gitlab, our hosted Octopus, from my own machine running Terraform myself.

**Comment by apparentlymart** [comment]
Hi @GavBurke! Thanks for reporting this.

Unfortunately in situations like this it's not really clear what we can do, since we don't have access to the network from which you are making requests or to the computers where you are running Terraform.

A direct read of the message you shared suggests that for some reason the response from `registry.terraform.io` is either not being return at all or is being significantly delayed. However, there could be many possible reasons why that could happen, such as packet loss on your local network, the CDN node nearest you experiencing an outage, an intermediate proxy intercepting the request and delaying it, etc. All of these and more are possible reasons we've seen for this to occur in the past.

I realize that it might also be difficult for you to collect more information, but you do at least have access to the network and computer where Terraform is running, so if you can share any more information about what you're seeing on the network when this request occurs (for example, using a packet capture tool) then that might give us a clue to work from.

(Since this is an HTTPS request you presumably won't be able to intercept the cleartext of the requests, but there might still be something interesting to observe in either the TLS handshake or the flow of encrypted packets, such as whether the IP address it's connecting to is a correct one to be using, whether there's any response coming from the server at all, etc.)

Thanks!

**Comment by snolan-amount** [comment]
We run Terraform Enterprise and we also see this error if our Terraform Enterprise server is down. That's totally expected and not an issue with Terraform at all - I just wanted to mention it in case it helps anyone else to not waste time looking into issues with the registry.

**Comment by crw** [comment]
Howdy! I am cleaning up old `waiting-response` issues. This issue seems to be missed a reproducible use case, and seems to be explained by the previous two comments. Please let us know if there is still an outstanding request. Thanks!
