### ISSUE TITLE
hashicorp repository just partially syncing

### ISSUE THREAD

**Issue by drunkez** [hashicorp/terraform#33078]
### Terraform Version

```shell
any
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

sync

### Actual Behavior

Hi
I am sorry to write this down, but maybe this github issue tracker got more attention than hashicorp forums.

Due to company policy we have to use spacewalk ( now Oracle Linux Manager ) to sync packages and distribute across environment.

As described here

https://discuss.hashicorp.com/t/unable-to-sync-repository-to-spacewalk/51948

 

We have a problem syncing the repo fully, we are able to sync only 665 packages out of 1122 overall. Oracle support suggests a problem with packages metadata, where I have to say I see a lot of difference comparing synced and failed-to-sync packages.

I have tested this even on a freshly installed Oracle Linux manager and the behavior is exactly the same, able to sync 665 packages can`t sync rest..

I`d like to discuss this with someone who`s responsible for package build maybe?

THnx

### Steps to Reproduce

create a software channel on OLM and sync hashicorp yum repository

**Comment by apparentlymart** [comment]
Hi @drunkez,

We use issues in this repository only to track defects and feature requests with the code maintained in this repository. What you've described here seems to be outside of the scope of this repository and so I'm going to close this issue.

I see that you've asked a question in the community forum and are frustrated that nobody has answered. I suspect the lack of response there is not due to a lack of attention -- various people monitor the community forum, including me -- but that you are asking about something very specific that nobody in the forum has experience with. I don't know what Oracle Linux Manager is, and I expect others who have seen your forum post don't either.

If you can share specific information about what is lacking from the HashiCorp repository _over in your community forum topic_ then I'll be happy to share that information with the release engineering team that is responsible for the RPM repository, so that they can decide how to prioritize it. I see that you've already been talking to Oracle support so hopefully they can describe exactly what their software requires, and then I can pass that on to the release engineering team.

Thanks!
