### ISSUE TITLE
templatefile() is requiring all interpolations to be declared in vars

### ISSUE THREAD

**Issue by nsb413** [hashicorp/terraform#33090]
### Terraform Version

```shell
Terraform v1.4.2
on darwin_arm64
```

### Terraform Configuration Files

NA

### Debug Output

file.js
```
//${one}
//${two}
```
```
> templatefile("functions.js",{one = "1"})
╷
│ Error: Invalid function argument
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ Invalid value for "vars" parameter: vars map does not contain key "two", referenced at functions.js:2,5-8.
╵
```

### Expected Behavior

If ${two} is missing in vars map, terraform should just ignore and only replace all the ${one} occurrences in the file.js 

### Actual Behavior

templatefile() is expected all the ${} to have key/values in vars map.

### Steps to Reproduce

```
terraform console 
templatefile("file.js",{one = "1"})
```

**Comment by jbardin** [comment]
Hi @nsb413,

The `templatefile` function is working as intended here. In order to process the template with an interpolation sequence, all named values in a sequence must be resolvable. This would be the same as writing `//${local.two}`, in which case `local.two` must also be defined. If you wish `${two}` to be escaped and printed verbatim, that can be done with the escape syntax `$${two}`.

Since this does not represent a bug in Terraform I'm going to close out the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
