### ISSUE TITLE
Terraform Output

### ISSUE THREAD

**Issue by michelefa1988** [hashicorp/terraform#33152]
### Terraform Version

```shell
1.4.6
```

### Terraform Configuration Files

NA

### Debug Output

```
The -target option is not for routine use, and is provided only for
│ exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
```

### Expected Behavior

Perhaps warning message needs to be updated to something less strong 

### Actual Behavior

NA

### Steps to Reproduce

terraform plan --target module.aks

### Additional Context

I currently have a big terraform project  which has become rather slow at times. Occasionally I have begun to use `--target` feature but I get the warning that this feature is not for routine use and cannot be used in production

What exactly does this mean? Is it a dangerous feature to use on production? Of course I understand all resources depend on each other, therefore it can be breaking, but my logic is if I want to update a minor setting on a database module, why run terraform on all modules/resources? 
I want to eliminate my concern is this warning is not due to some bugs in in terraform which can accidentally corrupt my state or something more deadly. 

Any advise on this?

```
The -target option is not for routine use, and is provided only for
│ exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
```

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

When using `-target`, there can be other changes which are not being shown to you, which could have an effect in combination with the changes you are targeting. This is what is meant by _"may not represent all of the changes requested by the current configuration"_. You can also get yourself into a situation where you cannot reliably recreate the infrastructure from the current configuration, because doing so you require applying the prior changes using the same series of targeting options.

Thanks!

**Comment by crw** [comment]
Hi @michelefa1988, apologies for the late reply. The details of `plan -target` can be found in our documentation: https://developer.hashicorp.com/terraform/cli/commands/plan#resource-targeting. The documentation has more information about this error specifically:

> This targeting capability is provided for exceptional circumstances, such as recovering from mistakes or working around Terraform limitations. It is not recommended to use -target for routine operations, since this can lead to undetected configuration drift and confusion about how the true state of resources relates to configuration.
> 
> Instead of using `-target` as a means to operate on isolated portions of very large configurations, prefer instead to break large configurations into several smaller configurations that can each be independently applied. [Data sources](https://developer.hashicorp.com/terraform/language/data-sources) can be used to access information about resources created in other configurations, allowing a complex system architecture to be broken down into more manageable parts that can be updated independently.

Thanks again!
