### ISSUE TITLE
Upgrade Go lang version in Terraform Binary to reduce vulnerabilities.

### ISSUE THREAD

**Issue by rakeshmulugu** [hashicorp/terraform#33239]
### Terraform Version

```shell
1.4.6
```

### Terraform Configuration Files

versions.tf

DockerFile

entrypoint.sh

### Debug Output

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Steps to Reproduce

Build an image with Terraform and scan the image to see the critical and high vulnerabilities.

### Additional Context

Hello,

We are building Images with Terraform, and Google Providers upgraded to the latest versions. The vulnerability scan results have critical and high vulnerabilities related to the Go lang package bundled with Terraform Binary.

The latest versions(1.20.0) of Golang have addressed these vulnerabilities, and I believe that updating to the latest version would significantly reduce the risk of security breaches in production.

Therefore, I request that the Go version be updated to the latest version. This would give us all more confidence in using the provider and reduce the risk of security issues.

Thank you for your attention to this matter. Please find the screenshot attached.

Location: /usr/bin/terraform1.4.6

![MicrosoftTeams-image (5)](https://github.com/hashicorp/terraform/assets/48657726/b19dc1a3-eaed-42f8-aaf0-87fd233c11a3)

**Comment by jbardin** [comment]
Hi @rakeshmulugu,

Future releases will be built with newer versions of the Go toolchain. The shown CVE is not relevant to Terraform, and does not warrant a new patch release.

If you have more security related questions, see also https://www.hashicorp.com/security.

Thanks!

**Comment by jbardin** [comment]
@rakeshmulugu, the security scanner you are using appears to only inspect the go runtime version embedded in the binary, but is not able to discern if particular vulnerabilities are relevant to the program in general. This tends to lead to a lot of false positives which need to be manually reviewed in order to take any action if any is necessary.

Yes, that version of Terraform was built with go1.19.6, but we can't retroactively change the go toolchain used to build a Terraform binary which was already compiled and released. Upcoming releases will use the current go1.20 compiler and runtime version.
