### ISSUE TITLE
Provider configuration not present

### ISSUE THREAD

**Issue by YoucefGuichi** [hashicorp/terraform#33242]
### Terraform Version

```shell
Terraform v1.4.6
```

### Terraform Configuration Files

```terraform
# module_x/main.tf
terraform {
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">= 1.19.0"
    }
  }
}
# root module/providers.tf
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.56.0"
    }
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">= 1.19.0"
    }
  }
}
# root_module/main.tf
module "app_7" {
  source               = "./module_x"
  // module inputs  here
}

```

### Debug Output

the following error raised when removing ```module "app_7"``` from ```root_module/main.tf```
```
Error: Provider configuration not present
 
To work with module.app_7.azurerm_postgresql_flexible_server.xxxxxx (orphan) its original provider configuration at module.app_7.provider["registry.terraform.io/hashicorp/azurerm"] is required, but it has
been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy
module.app_7.azurerm_postgresql_flexible_server.xxxxxxx (orphan), after which you can remove the provider configuration again.
```

### Expected Behavior

When removing the module the cloud resources associated with it should be destroyed.

### Actual Behavior

/

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Instating a provider inside a module is considered as anti-pattern, however the conflict here is that a non-hashicorp provider must be declared in the child module as well. am i missing something ? any suggestions to fix that issue ?

**Comment by jbardin** [comment]
Hi @YoucefGuichi 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

In this case you will need to recreate the module with at least the provider configuration to destroy the existing resources, then once the resource are no longer in the state the last of the module can be removed.

Thanks!
