### ISSUE TITLE
terraform plan command makes the parent unix process killed abruptly in case of error

### ISSUE THREAD

**Issue by ksbalas** [hashicorp/terraform#33252]
### Terraform Version

```shell
Terraform v1.4.3-dev
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
```

### Terraform Configuration Files

```terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.30.0"
    }
  }

  backend "s3" {
    bucket         = "terraform-state-us-west-2-223432432"
    key            = "terraform.tfstate"
    region         = "us-west-2" // us-west-2
    dynamodb_table = "terraform-state"
  }
}

provider "aws" {
  region  = var.aws_regionx
  profile = var.aws_profile
}

module "abc_interface_msk" {
  source              = "./modules/msk/"
  msk_cluster_name    = var.msk_cluster_name
  msk_ebs_volume_size = var.msk_ebs_volume_size
  msk_kafka_version   = var.msk_kafka_version
  msk_kafka_brokers   = var.msk_kafka_brokers
  msk_subnet_type     = var.msk_subnet_type
  msk_instance_type   = var.msk_instance_type
  count               = var.deploy_nyquist_interface_kafka ? 1 : 0
  msk_enable_iam  = var.msk_enable_iam
  msk_enable_scram = var.msk_enable_scram
}
```

### Debug Output

It has sensitive details & credentials. so not sharing

### Expected Behavior

terraform plan -var-file="${TF_ENV_VAR_FILE}" -var="aws_profile=test-admin"
exit_code=$?

echo "Hello"
echo "Exit Code from Terraform Plan: $?"
if [ $exit_code -eq 0 ]; then 
    echo "Terraform Planning Complete"
    mv main.tf.bak main.tf
    echo "main.tf is replaced with backup file"
    exit 0 
else
    echo "Terraform Planning Failed. Exit Code: $? "
    mv main.tf.bak main.tf
    echo "main.tf is replaced with backup file"
    exit 1
fi

### Actual Behavior

I'm setting up CI/CD and my terraform plan and apply is running as a unix process. 
So i was simulating if in case of terraform plan encountering any error, what is happening. Essentially there are some clean up steps which are happening after terraform plan. 

Here in this case when i created a synthetic error to test the behavior, terraform plan fails and exits with exit code 1 but it makes the whole unix process die without executing the block after terraform plan. 

### Steps to Reproduce

embed the above terraform script in to a unix script and add echo statement after terraform plan. 
if it encounters error, it fails and not executing the blocks after terraform plan.

**Comment by jbardin** [comment]
Hi @ksbalas,

A unix process cannot cause the parent process to exist, so what you describe here is not technically possible for Terraform to do. The most likely scenario is that the script is running with the `errexit` option, which will cause it to exit when encountering a non-zero exit code from a child process. If this is not the entire script verbatim, there could other issues as well, the error handling in `Exit Code from Terraform Plan` is incorrect, as it will print the status of the `echo` command rather than `terraform`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
