### ISSUE TITLE
terraform console should print the output for every newline-separated input

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform#33273]
The documentation states:

> The terraform console command can be used in non-interactive scripts by piping newline-separated commands to it. Only the output from the final command is printed unless an error occurs earlier.

and indeed this is true:

```terraform
locals {
  a = "foo"
  b = "bar"
}
```

```bash
$ printf "%s\n%s\n" "local.a" "local.b" | terraform console
"bar"
```

what's the reason for this limitation?

**Comment by paololazzari** [comment]
> The console command is structured to evaluate a single expression and return the result

That doesn't seem to be the case, e.g.:

```bash
$ printf "%s\n%s\n" "local.abc" "local.b" | terraform console
╷
│ Error: Reference to undeclared local value
│
│   on <console-input> line 1:
│   (source code not available)
│
│ A local value with the name "abc" has not been declared. Did you mean "b"?
```

so **all** expressions are evaluated, but only the last one is printed.

> it's not clear what it should do in the face of multiple expressions like you have shown

It should print out the result for all inputs

**Comment by paololazzari** [comment]
My point is that, clearly, all expressions are evaluated, otherwise I wouldn't see an error message for the first expression in the example above. So given that all expressions are evaluated, why only print one output? 

The issue you linked to is a separate thing, since I'm not talking about a non-interactive `terraform console` mode.

**Comment by jbardin** [comment]
The fact that multiple expressions are evaluated could be considered a bug, since multiple expressions are not expected. The reason for only printing one, is that evaluation can only result in a single value. As I mentioned in #32402, fixing that would probably make this input invalid in the first place.

Piping input via stdin is the non-interactive mode of the `console` command, so in order to have multiple results there would need to be a new mode of operation like in the linked issue, otherwise it would not be possible. If if the use cases were slightly different, allowing multiple commands and multiple outputs from a non-tty input source would be covered by the same solution and we can follow #32402 for any follow up.

Thanks!

**Comment by paololazzari** [comment]
This isn't complete nor is it a duplicate.

https://github.com/hashicorp/terraform/issues/32402 discusses keeping a `terraform console` process alive in the background and feeding stdin to it, i.e. a `terraform console` server.

What I am discussing here is the limitation of `terraform console` in processing stdin

**Comment by jbardin** [comment]
Whether the lifetime of the process is determined by the stdin pipe or some other factor, the process of reading multiple commands and printing multiple outputs would be the same.

Having a single issue to track the same block of work this gives the issue more visibility, increasing the possibility of getting addressed in future development cycles; and since we have linked the two issues any of particular details raised here can be also taken into consideration.
