### ISSUE TITLE
.terraform.d directory created in my homedirectory instead of XDG location

### ISSUE THREAD

**Issue by jasonkarns** [hashicorp/terraform#33289]
### Terraform Version

```shell
$ terraform version
Terraform v1.4.6
on darwin_arm64
```

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

This directory's contents should have been created in the appropriate XDG-compliant locations:
- config: `$XDG_CONFIG_HOME:-$HOME/.config/`
- cache: `$XDG_CACHE_HOME:-$HOME/.cache/`
- data: `$XDG_DATA_HOME:-$HOME/.local/share`

### Actual Behavior

A directory was created in my home directory: `~/.terraform.d/`

### Steps to Reproduce

I'm not even sure what command triggered the file creation. Likely `terraform fmt` ? 

### References

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by apparentlymart** [comment]
Hi @jasonkarns! Thanks for reporting this.

When I think about the various things that might create files in Terraform, the only one that springs to mind where the path to create is chosen by Terraform itself is the `terraform login` command, which would have written a `credentials.tfrc.json` into that directory if it were the cause. There are other parts of Terraform which _read_ from this directory, but I can't think of any others that would create the directory for you.

With that said, if we were creating Terraform anew today we would certainly use the XDG directories when running on a Linux system, but since these files are used by many historical versions of Terraform -- in some cases going back many years -- being compatible with how Terraform historically behaved has taken priority because there are lots of users who run multiple different versions of Terraform as they work with different Terraform configurations, and so retaining the current location is currently the best compromise.

Terraform behaved as designed here, so I'm going to reclassify this as a feature request to support XDG paths either in addition to or instead of the current convention, although exactly how we might achieve that will depend on what aspect of Terraform is using the directory in your case. For example, if it is `terraform login` then we'd need to consider the cost of having newer versions of Terraform write credentials into a location that older versions of Terraform would not be able to find them.

For CLI configuration in general we have #15389 open already, but I don't think that issue would cover any situation where Terraform is the one generating the files, since that of course has some different tradeoffs: we can potentially read from multiple different directories, but we can probably only write to one.

Thanks again!

**Comment by apparentlymart** [comment]
I also just noticed that you are using macOS. On macOS we follow [Apple's documented conventions](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1) for new designs, because XDG is a Linux-specific standard.

Based on that specification, I expect we'd create files in `~/Library/Application Support/terraform.io` on your platform, which would follow the conventions Terraform is already following for other situations that were implemented since we started following these platform-specific conventions.

**Comment by jasonkarns** [comment]
If I understood the two comments above correctly, then this sounds like it _is_ a bug? I am on macOS (Ventura) so if the expectation is that terraform's files would be written to `~/Library/Application Support/terraform.io`, then it sounds like terraform isn't behaving as expected? I'm an app developer so I don't typically do much with terraform other than running `terraform fmt` on our tf repo. I'll delete the directory and see if I can spot when/if it is recreated.

Whether terraform follows XDG on macOS could be a separate question that probably should be a separate feature request in that case. (Considering that it's a BSD derivative and that an exhaustive array of developer tooling and clis treat darwin as a *nix, it would seem prudent to at least respect XDG if not following Apple's own ~/Library/ recommendations. Even if only in the cases where the XDG directories exist or the XDG_* vars are set.)

**Comment by jasonkarns** [comment]
closing in favor of https://github.com/hashicorp/terraform/issues/15389

**Comment by apparentlymart** [comment]
To be clearer about what I meant above, there are two parts:
1. Terraform does not currently follow _any_ platform standards for what `terraform login` generates (again assuming that's what generated the directory here) and although we'd like to do that it's a tradeoff against breaking compatibility with existing Terraform versions that expect the generated file to be in the current location.
2. If we _did_ switch to platform standards for this, on macOS we would probably use `~/Library/Application Support/terraform.io` instead of XDG because that's the documented location " app-created data files, configuration files, templates, or other fixed or modifiable resources that are managed by the app". That would be consistent with how Terraform behaves in other situations where it _does_ follow the platform conventions, such as [the implied local plugin mirror search paths](https://developer.hashicorp.com/terraform/cli/config/config-file#implied-local-mirror-directories).
