### ISSUE TITLE
`terraform fmt` should allow disabling "align equals signs"

### ISSUE THREAD

**Issue by EggDice** [hashicorp/terraform#33281]
### Terraform Version

```shell
Terraform v1.4.6
on linux_amd64
```

### Use Cases

When `fmt` is formatting it follows this style guide:
"When multiple arguments with single-line values appear on consecutive lines at the same nesting level, align their equals signs"

Because of this, the formatted terraform code is not future-proof from the point of view of git diffs. If I add a long line to my block all other lines will be changed, which results in a bloated git diff with lines that are not changed for any real business change. A similar issue is with languages that do not support trailing commas.

### Attempted Solutions

I tried to look for flags to turn this off, but I have not found any feature. Also, we can write our own formatter, but I think it is something that would benefit a lot if available. I get if the philosophy is to not provide any reconfigurability on styling, I just thought this is really affecting more than just styling. Similar decisions have been made in other open-source tools like "prettier".

### Proposal

To have a flag on `terraform fmt` that disables the formatting equal signs.

**Comment by crw** [comment]
Thanks for this request!

**Comment by kmoe** [comment]
Thanks for the feature request. While I wasn't present for the initial design for `terraform fmt` I understand it is aligned philosophically more with `go fmt` than (for example) `prettier` or JSLint - that is, it is strongly opinionated about there being one correct format for Terraform files without further options. This makes the correct format for Terraform files more portable, as no further parameters need to be specified.

That said, `go fmt` does format imports in a non-ideal way, which is why `goimports` was created, so perhaps a similar approach would work for those aspects of Terraform formatting that have multiple valid options.
