### ISSUE TITLE
remote-exec provisioner : no such file or directory

### ISSUE THREAD

**Issue by KarimaFathi** [hashicorp/terraform#33302]
### Terraform Version

```shell
Terraform v1.4.6
on linux_amd64
```

### Terraform Configuration Files

```
resource "null_resource" "RKE2_server1_provisioning"{
  count = var.vm_count
  provisioner "remote-exec" {
    connection {
      type     = "ssh"
      user     = var.ssh_user[0]
      host     = var.ipv4_address[0]
      private_key = file(var.ssh_key)
      agent = false
    }
    scripts= [
      "/opt/RKE2/first_node_install.sh",
      "/opt/RKE2/rancher_server_install.sh",
    ]
 }
}

```

### Debug Output

https://gist.github.com/KarimaFathi/2fae6bba73722e69aa5932266d037adf

### Expected Behavior

After using the remote-exec provisioner with the scripts argument, I expected Terraform to copy these scripts to the remote machine and execute them. This expectation was based on the fact that these scripts exist in the same path on my local machine, as mentioned in the code.

### Actual Behavior

it shows that terraform failed to open the script because there is no file or directory !! 

### Steps to Reproduce

terraform apply

**Comment by apparentlymart** [comment]
Hi @KarimaFathi! Sorry this didn't work out.

Based on the error message, it seems like Terraform failed to open the first file on your _local_ system; I recognize that error message as being the one returned by the system when Terraform's own `open` system call falls.

Since I can't see what files exist on your computer, I don't know how to investigate further. What happens if you run the following command outside of Terraform, but in the same context where Terraform would be running?

```
cat /opt/RKE2/first_node_install.sh
```

**Comment by KarimaFathi** [comment]
Thank you for your answer. When I run the command, I get the script as an output, as shown in the screenshot.
<img width="359" alt="image" src="https://github.com/hashicorp/terraform/assets/135225708/6bcaf479-fec1-4b83-bb49-36168f2002dd">

**Comment by crw** [comment]
Hi @KarimaFathi, just to double-check, are you executing the `cat` command as the same user as the `terraform` command? I am just trying to eliminate a potential permissions issue as a source of the problem. Thanks!

**Comment by KarimaFathi** [comment]
Yes, it's the same user. I've given the files and the directory all the permissions just to make sure that this is not the main reason for this issue, but in vain. It still shows the same error.

**Comment by apparentlymart** [comment]
Hi @KarimaFathi! Thanks for the additional context.

Unfortunately I don't know what to suggest next. It seems that for some reason your Terraform process cannot find the file even though `cat` cannot, which suggests that somehow Terraform has a different view of the filesystem than `cat` does. However, with the information we have I don't have any guesses as to _why_ Terraform would see a different view of the filesystem.

Can you share more information about how exactly you are running Terraform? For example, exactly what commands you are running, what shell you are using, whether you're in container-based or other virtualized environment, whether any of these directories are mounted over the network, or anything else that I might not think to ask about but that is unusual about the computer where you're running Terraform?

It seems like you also omitted the early parts of the trace log you shared, because it begins with a message that can only appear in the middle of a Terraform Core action, so that cannot possibly be the first message in the log. If you can share the entire log without anything removed that might also give some clues.

From the error message it seems pretty clear that Terraform _is_ just trying a normal "open" system call and the Linux kernel is returning the "ENOENT" error code, which translates to "no such file or directory" when interpreted as an error string. So I think the question we need to answer here is: is Terraform making that system call incorrectly and therefore encountering the error, or is Terraform doing something correct but it's your surrounding system that's somehow misbehaving.

Thanks!

**Comment by KarimaFathi** [comment]
Sure, in fact, this code is just a part of a child module of the root module where I am using three modules. The first one is for provisioning the infrastructure with the vSphere provider, where I generated three virtual machines (OS: CentOS 7) with additional features. Since things were done well, I omitted the first part of the logs that concerns the first module.

The second module simply generates a token that will be used later for the RKE2 cluster. The third module is the one I am facing a problem with. It is responsible for connecting to the remote machines, copying and executing the scripts on them, and finally achieving an HA Rancher server based on RKE2.

<img width="158" alt="image" src="https://github.com/hashicorp/terraform/assets/135225708/c0b2053b-b7b7-4f30-ab62-9f3edc05403f">

And here, as you can see, I have a directory in the third module named "RKE2" because in my first attempt, I used the provisioner "file" to copy the files from the local machine to the remote ones, which was done successfully. Then, I used the provisioner "remote-exec" with the argument "inline" to make the scripts executable and execute them. However, I encountered an issue because Terraform, by default, copies these scripts to the "/tmp" directory on the remote machines with a different label like "terraform123456.sh". Consequently, it couldn't find the scripts due to this labeling.

And when I tried to force the replacement of this resource by using `terraform apply -replace=null_resource.RKE2_server1_provisioning`,  nothing changed. That's why I deleted this module from the root module. Then I ran `terraform init`  and added the module again. Right after that, I executed `terraform apply`  to proceed with the second method, which involves using the provisioner "remote-exec" along with the "scripts" argument. And that's all.

for the directories non of them was mounted over the network, actually for this project, I am working with vim editor to write shell scripts, the terraform code...

**Comment by apparentlymart** [comment]
Hi @KarimaFathi! Thanks for the additional context.

Looking at the screenshot you most recently shared, and again at the screenshot you showed earlier, I noticed that you actually looked at a file called `fist_node_install.sh` rather than `first_node_install.sh` -- notice that the "r" is missing from "first". That typo also seems to exist in the directory tree you've shared in your most recent comment.

Does it work if you change your Terraform configuration to refer to `/opt/RKE2/fist_node_install.sh` instead?

**Comment by KarimaFathi** [comment]
You are right, but the problem that I mentioned before has occurred again, which is:

│ error executing "/tmp/terraform_1927733056.sh": wait: remote command exited without exit status or exit signal

I don't know how to fix the problem since Terraform, by default, copies the scripts in /tmp with a different name.

**Comment by KarimaFathi** [comment]
This is the GitHub Gist's link for the logs :

[https://gist.github.com/KarimaFathi/d8bdcdc6edc1ba91b77a414e60bd8e19](url)
