### ISSUE TITLE
☂️ Terraform leaks state on interrupt

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform#33358]
### Terraform Version

```shell
% ./terraform --version
Terraform v1.3.9
```

### Terraform Configuration Files

I haven't spend time to reproduce with the null resource provider. I have several reported issues into the providers. In https://github.com/hashicorp/terraform-provider-google/issues/14789#issuecomment-1573717754, I was advised by terraform-provider-gcp maintainer to open an issue to terraform core as many providers are affected by the issue.

### Debug Output

See the referenced issues below

### Expected Behavior

terraform and its providers to be resilient to interrupts and to do not leak terraform state when interrupt is received. We run terraform in quite automated manner without human interaction. Everytime state leaks, a human operator has to analyse it and fix it manually.
My expectation on SIGTERM is terraform to wait until all ongoing resource creations are completed. Meanwhile terraform should not start any new resource creation after SIGTERM is received. The actual behavior currently seems to cancel the context and terraform providers log errors of type `context canceled` and leak terraform state.

### Actual Behavior

Usually terraform and its providers leak state when first terraform apply (that creates the resources) is interrupted.

### Steps to Reproduce

See the referenced issues below for proper steps to reproduce.

### References

- https://github.com/hashicorp/terraform-provider-google/issues/14782
- https://github.com/hashicorp/terraform-provider-google/issues/14789
- https://github.com/hashicorp/terraform-provider-google/issues/14790
- https://github.com/hashicorp/terraform-provider-aws/issues/31729
- https://github.com/hashicorp/terraform-provider-aws/issues/31731
- https://github.com/hashicorp/terraform-provider-aws/issues/18051

**Comment by jbardin** [comment]
Thanks @ialidzhikov. If a provider has not returned any state for Terraform to save, then there is nothing else that Terraform can do to record the resource state. Passing along the context and and returning any intermediate state where possible is the provider's responsibility. This is made easier with the newer plugin framework, but it will take some time for the legacy providers to migrate over to the new libraries.

Thanks!

**Comment by apparentlymart** [comment]
Thanks for the extra context!

Terraform's current design for handling interrupts is as @jbardin described, and from the perspective of a Terraform provider plugin this consists of Terraform Core immediately calling the provider RPC method named "Stop", concurrently with any running operations for that provider, at which point Terraform expects providers to do whatever they need to do in order to safely abort operations in progress.

From what you've described it seems like the GCP provider is responding to "Stop" by cancelling a Go context (`context.Context`) and that context is also associated with all of the API requests in progress and so the HTTP client inside the provider is immediately terminating the request and returning the "context cancelled" error you saw.

If that's true then unfortunately this is a problem entirely within that provider: Terraform Core doesn't force providers to do anything in particular in Stop, and instead just sends that request and politely waits for all of the operations in progress to complete, either successfully or with an error. The provider must ensure that it responds to that message by doing something that leaves the system in a correct state, which I think in your case would mean letting the operation run to completion and then returning its result as a success. That behavior lives within the provider, so there's nothing we could change in this repository (Terraform Core) to force a provider to handle cancellation in a different way.

**Comment by ialidzhikov** [comment]
> This is made easier with the newer plugin framework, but it will take some time for the legacy providers to migrate over to the new libraries.

Can you share more details/docs about it?

In general I am not happy at all when my issues are closed like this. The most popular terraform providers (aws,google,openstack) are leaking state/resources. I opened issues to the providers, I was advised to open issue to terraform core.

**Comment by apparentlymart** [comment]
Hi @ialidzhikov,

It seems that most of the provider-specific issues you opened remain open at the time I'm reading this. Those are the best place to continue discussing this, because providers have total control of how (and whether) they react to the "stop" signal. If a particular resource type is handling Stop inappropriately then the only place that can be fixed is in the code for that particular resource type, which lives in the provider's own codebase. There is nothing we can do about it in Terraform Core.

**Comment by jbardin** [comment]
@ialidzhikov, the plugin framework project can be found here: https://github.com/hashicorp/terraform-plugin-framework/

This is the SDK that new providers are being developed using, and existing providers are migrating towards. It provider a better overall API, type system, and fixing numerous issues inherent in the legacy SDK. 

I'm sorry you were misdirected to the core repository, but unfortunately there's not much we can do from here. It is incumbent on the providers to return any data which Terraform needs to handle. Note that in many cases the provider may not be able to do anything either, since the remote API may not have returned any useful information to store, which will always require some manual cleanup in the case of a failure during apply.
