### ISSUE TITLE
Config-driven import | fails to import google_monitoring_uptime_check_config

### ISSUE THREAD

**Issue by black-snow** [hashicorp/terraform#33375]
### Terraform Version

```shell
1.5.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "= 4.69.1"
    }
}
```

### Debug Output

There's a ton of logs but nothing that looks like it's really related to this (and the error message seems quite helpful).  
I can try to provide a redacted version if you really need it.

### Expected Behavior

Should be able to generate the code corresponding to the existing uptime check.

### Actual Behavior

Fails generating code / a plan with error message: "Error: project: required field is not set"

### Steps to Reproduce

1. create an uptime check in GCP (HTTP in my case but doesn't really matter)
2. add an import block for that resource:
```terraform
import {
  id = "<id of your check>"
  to = google_monitoring_uptime_check_config.this
}
```
3. run `terraform plan -generate-config-out=generated_resources.tf`

**Comment by kmoe** [comment]
Thanks for this.

What is the full output from `terraform plan`? This could be one of the cases in which Terraform is able to generate partial config and outputs HCL to the local directory even when the plan fails.

**Comment by jbardin** [comment]
Hi @black-snow,

If the provider does not supply the data for a required attribute (either required via schema or required via validation), Terraform won't be able to generate a valid config, and can only create a best-guess effort. Without the full output we also can't really troubleshoot this any further, but we can track #33392 which is required to allow providers to help generate more precise configurations.

Thanks

**Comment by black-snow** [comment]
#33438 sounds reasonable.

TF could probably guess the project if it's not provided or look it up. But I don't know about the process behind the scenes.

**Comment by jbardin** [comment]
@black-snow, Terraform cannot guess at anything here, because it is not aware of any details about the remote systems, it only speaks the generic plugin protocol with providers. The Google provider itself could probably work around this to allow the use of the configuration generated via import, but that's not something we can do from here. You would need to file an issue with them, however there are probably going to be a multitude of these import-related issues for many resources, and they may choose to not direct much effort to them until we have a more general solution in place.

#33438 is part of a plan so that providers don't need to work around ambiguities in the configuration, and can more directly declare what that configuration should consist of.

**Comment by black-snow** [comment]
@jbardin thanks for sharing your thoughts!
