### ISSUE TITLE
Import block documentation does not provide information regarding for_each import

### ISSUE THREAD

**Issue by lgeo3** [hashicorp/terraform#33389]
### Terraform Version

```shell
1.5.0
```

### Affected Pages

https://github.com/hashicorp/terraform/blob/main/website/docs/cli/import/index.mdx

### What is the docs issue?

In the import_block documentation we can read: 

The below example shows how to import a resource that includes [for_each](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each).
```
import {
  to = aws_instance.example["foo"]
  id = "i-abcd1234"
}
```

But the example does not provide any information regarding for_each 

### Proposal

An example with the use of for_each (I tried to figured out myself but I ended with 

```
│ An argument named "for_each" is not expected here.
```

when doing something like
```
import {
for_each = toset(["name1", "name2"])
id = each.key
to = module.my_module.gitlab_project.projects[each.key]
}
```

**Comment by ksamba-tc** [comment]
The documentation says that imports do not support interpolation strings for IDs, which means that it is impossible to use for_each since you need to hard-code the ID string.
And you cannot have multiple resources with the same ID even if they are in separate providers (there is an issue open for this already), so I don't think you can have a for_each at all here.
