### ISSUE TITLE
Could not get instance id from the instance resource type while using latest aws provider plugin version

### ISSUE THREAD

**Issue by marieswarank95** [hashicorp/terraform#33409]
### Terraform Version

```shell
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.4.0
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment

### What is the docs issue?

target_id - (Required) The ID of the target. This is the Instance ID for an instance, or the container ID for an ECS container. If the target type is ip, specify an IP address. If the target type is lambda, specify the arn of lambda.

### Proposal

latest aws provider plugin is not provide id attribute in the instance resource type. But target_group_attachment resource type is expecting id of the instance in the target_id argument while using target type as instance. Can you please check the terraform documentation whether the mentioned statement is correct or not.

### References

Please check this issue, after that you can close it.

**Comment by jbardin** [comment]
Hello,

The `aws_instance` resource does have an `id` attribute, so your problem is likely from elsewhere in your configuration. This however appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
