### ISSUE TITLE
Support `-generate-config-out` for import blocks to stdout / remote backend

### ISSUE THREAD

**Issue by mnahkies** [hashicorp/terraform#33410]
### Terraform Version

```shell
1.5.1
```

### Use Cases

Generation of resource blocks when using the remote backend, eg: terraform cloud.

### Attempted Solutions

The new `import` block feature is great, and I'm excited by the `-generate-config-out` option (ref: https://developer.hashicorp.com/terraform/cli/commands/plan#generate-config-out-path) but it doesn't currently work with the remote backend / terraform cloud.

I presume this is because it needs to write to the filesystem. If we could write the result to `stdout` then I'd guess that this limitation could be lifted.

### Proposal

Support outputting the generated config to `stdout` to allow for remote backend. This will then allow us to copy that into a local file.

**Comment by omarismail** [comment]
Hey @mnahkies ,

Are you using the `remote{}` backend or `cloud{}`?

**Comment by mnahkies** [comment]
@omarismail we're using:
```
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "<ORG>"
    workspaces {
      prefix = "001-projects-"
    }
  }
}
```

I think we originally stuck with `remote` for the `prefix` feature, though I've just noticed that `cloud` supports using tags for equivalent functionality (may be new?) so we could probably try switching to `cloud` now.

**Comment by apparentlymart** [comment]
Hi @mnahkies,

Thanks for confirming. Indeed, the remote backend is essentially deprecated for Terraform Cloud use and so is unlikely to benefit from new features in Terraform Cloud. The new Cloud integration is capable of tighter integration between CLI and Cloud due to not being "just a backend"; it won't always be possible to match everything it does in the legacy remote backend.

Please let us know how things go when you try the Cloud integration!

For our part, I wonder if there's a way that the remote backend can notice that it's being asked to do this and emit a warning explaining that the Cloud integration is required. I'm not sure though if Terraform CLI knows early enough to be able to reliably produce that warning, or if that only become apparent once the run has already started in Terraform Cloud.

**Comment by sylr** [comment]
I'm using Terraform v1.6.2 and `cloud{}` and it does not generate config locally neither:

```hcl
terraform {
  cloud {
    organization = "xxxxxxx"
    workspaces {
      name = "aws-vpc"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
```

**Comment by asaf400** [comment]
I always thought Terraform cloud is a <Insert a bad word in a polite manner here> of a product, but @sylr comments, made me laugh out loud. thanks mate.. 🤣

I am also still using 
```
terraform {
  backend "remote" {
```

but I guess there's no point in making an effort to change 🤭

**Comment by mnahkies** [comment]
Just had a chance to try this again with `terraform` v1.6.6 and the `cloud` backend. Worked perfectly, wrote the file to my local filesystem and also output in `stdout` 🎉
