### ISSUE TITLE
concise regex test

### ISSUE THREAD

**Issue by dmrzzz** [hashicorp/terraform#33425]
### Terraform Version

```shell
Terraform v1.5.1
on darwin_arm64
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/functions/regex

### What is the docs issue?

Currently:
> If the given pattern does not match at all, the regex raises an error. To test whether a given pattern matches a string, use [regexall](https://developer.hashicorp.com/terraform/language/functions/regexall) and test that the result has length greater than zero.

That's fine, but I think it's also worth pointing out that you can combine `can` with `regex` for a more concise test (which had not occurred to me until I saw [someone else mention it](https://discuss.hashicorp.com/t/how-to-filter-out-ip4-and-ip6-subnets/22556/6)).

Old way:
```hcl
cidr_blocks       = [for c in var.all_cidr_blocks : c if length(regexall(":", c)) == 0]
ipv6_cidr_blocks  = [for c in var.all_cidr_blocks : c if length(regexall(":", c)) > 0]
```

New way:
```hcl
cidr_blocks       = [for c in var.all_cidr_blocks : c if !can(regex(":", c))]
ipv6_cidr_blocks  = [for c in var.all_cidr_blocks : c if can(regex(":", c))]
```

### Proposal

If the given pattern does not match at all, the regex raises an error. To test whether a given pattern matches a string, use `can(regex(pattern, string))`, or use [regexall](https://developer.hashicorp.com/terraform/language/functions/regexall) and test that the result has length greater than zero.

**Comment by apparentlymart** [comment]
Hi @dmrzzz! Thanks for this feedback.

I think you're right about this and honestly I think it's largely the way it is just because of history: we devised `can` only after observing that there are _several_ functions where their success vs. their failure is a useful signal in its own right, but `regexall` (and this suggestion to use `length` with it) came at an earlier time when we hadn't yet discovered the more general design. The documentation for `regex` originates from back when both of those functions were introduced together, and hasn't been revisited since introducing `can`.

I think there _is_ a subtlety here that we should probably be mindful of, though: comparing `regexall`'s result length to zero is sensitive only to whether the pattern _matched_, and so if the pattern is _invalid_ `regexall` will still fail with an error. On the other hand, using `can(regex(...))` cannot distinguish between those situations: if you write an invalid regex then it will be treated just like a valid regex that didn't match.

That leaves me feeling a bit ambivalent because when I'm helping folks to use Terraform I've unfortunately quite often encountered situations where someone has accidentally written a condition that is either always true or always false but yet they haven't noticed yet because they've focused only on the main situation they care about. Therefore I get nervous about making recommendations that could potentially hide a mistake that would normally be caught.

However, I think the better solution to that problem is a combination of some kind of hinting about possible problems like I was prototyping over in #29661 and also a better story for unit testing so that it's easier for module authors to exhaustively test both the positive and negative cases of the conditions they write. If we had at least one of those two things -- ideally both -- then I'd feel better about recommending `can`.

(Notice that in #29661 the very first future idea I thought of was "Conditional expressions where the predicate provably always returns `true` or always `false`", because that really is one of the most common mistakes I see! However, this particular situation is a hard one to detect as a static analysis check because it requires proving that a particular function call will always fail or always succeed, which is not possible in general but might still be feasible in some specific cases, such as if `regex` is being used with a constant string as the given pattern.)

**Comment by dmrzzz** [comment]
@apparentlymart that's a really good point which I had completely overlooked.

In practice I personally am much more likely to write a condition that's always false because my regex is _wrong_ (as opposed to invalid), so I make a point of always testing my regexes as soon as I write them, but nonetheless you've convinced me that the existing regexall recommendation is technically superior.

That being the case, I'll withdraw my suggestion for a documentation update.  Thanks very much for taking the time to respond!
