### ISSUE TITLE
`contains` inconsistently comparing set of items to an item where an attribute contains an empty set

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [hashicorp/terraform#33460]
### Terraform Version

```shell
1.5.2
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

When checking that the following set contains the item beneath it, the result returned should be true but it is false
```terraform
toset([
  {a="one",b=toset([])},
  {a="two",b=toset(["Id"])}
])
```
Item:
```terraform
{a="one",b=toset([])}
```
When checking for this item though, the result returned is true
```terraform
{a="two",b=toset(["Id"])}
```

### Actual Behavior

The result returned when checking for `{a="one",b=toset([])}` is false

### Steps to Reproduce

1. `terraform console`
2. `contains(toset([{a="one",b=toset([])},{a="two",b=toset(["Id"])}]),{a="one",b=toset([])})` => `false`
3. `contains(toset([{a="one",b=toset([])},{a="two",b=toset(["Id"])}]),{a="two",b=toset(["Id"])})` => `true`
4. `contains(toset([{a="one",b=toset([])},{a="two",b=toset([])}]),{a="one",b=toset([])})` => `true` (set in second item no longer contains "Id")

### Additional Context

I believe the issue comes down to the same reasoning as was provided via [this comment](https://github.com/hashicorp/terraform/issues/23562#issuecomment-564071042). However, this means there's no way of comparing an item with a set where one of the attributes is a set with no values if any of the other items in the set contain an item.

**Comment by jbardin** [comment]
Hi @ScottFinlaysonGMSL,

Thanks for filing issue with excellent example. This is the same issue as the one linked, so we can combine them for better visibility. It's not that `contains` can't compare the items, it's that the items have different types in the first place because `toset([])` is not a `set(string)`. Pretty much any use of `[]` as a value which needs to be compares is probably a mistake, since it is an empty type with no element type.

If you were to make a variable with an explicit type, you can verify that it will be matched against the same value:

```
variable one {
  type = object({
    a = string
    b = set(string)
  })
  default = {
    a = "one"
    b = []
  }
}

variable two {
  type = object({
    a = string
    b = set(string)
  })
  default = {
    a = "two"
    b = ["Id"]
  }
}
```
```
> contains(toset([var.one, var.two]), var.one)
true
```

If you encounter a situation where you must use a literal value where the type cannot be correctly inferred, one way you can insert explicit types define them in a local module and pass the literal value through the module variable and output to ensure they are converted to the exact type you want.

Thanks
