### ISSUE TITLE
Add s390x support to Terraform CLI

### ISSUE THREAD

**Issue by kun-lu20** [hashicorp/terraform#33508]
### Terraform Version

```shell
Terraform v1.5.2
on linux_s390x
```

### Use Cases

Add s390x support to Terraform CLI binary, docker image and the community CI.

### Attempted Solutions

We've built Terraform and necessary provider plugins from source and run e2e tests on local s390x VMs, it worked fine.

### Proposal

We would like to work with community to enable s390x support in Terraform CLI. We feel this can be achieved based on our initial investigation - specifically:
1. s390x has full native and cross compile support of Golang
2. With some modifications to Terraform Github Actions CI we are able to successfully add s390x binary and image build jobs - please see the job logs here: [Terraform linux s390x v1.6.0-dev](https://github.com/linux-on-ibm-z/terraform/actions/runs/5414087624/jobs/9840632893) and [Build Docker image for linux_s390x](https://github.com/linux-on-ibm-z/terraform/actions/runs/5414087624/jobs/9840818037).

It appears that most provider repos are utilizing the established pipeline in https://github.com/hashicorp/ghaction-terraform-provider-release to release the multi-arch binaries. In order to add s390x support to their binaries, we just need to add `s390x` to the supported `goarch` in `.goreleaser.yml` in the provider repo.

We're happy to provide s390x Community Cloud VMs if the community needs the hardware for building and testing. Please feel free to let us know if it's a good timing to add s390x support or there is anything we can help with to make this happen. Thanks!

### References

-  https://github.com/hashicorp/terraform/issues/26522
-  https://github.com/hashicorp/terraform/issues/21283
-  https://github.com/hashicorp/terraform/pull/23979

**Comment by crw** [comment]
Hi @kun-lu20, thanks for this request! In order to provide a good user experience, we would also want to package all of our providers for this architecture, which would be a large undertaking! As this appears to be an IBM corporate initiative, I would suggest reaching out to your HashiCorp alliances manager to discuss further, as delivering this would be a large initiative involving many teams that would need to be coordinated strategically. That coordination is most likely to happen once we have business alignment on the goals of this project. Thanks again for your request!
