### ISSUE TITLE
Automatically move module when count is introduced

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#33510]
### Terraform Version

```shell
Terraform v1.5.2
on linux_amd64
```

### Use Cases

Some times we want to make a module optional, so we add

```hcl
  count = var.module_enabled ? 1 : 0
```

When we do that to resources, the resources are automatically moved from `name` to `name[0]`. I would like to see the same done with modules.

### Attempted Solutions

Manually move modules using `terraform state mv`.

### Proposal

When a module address goes from no count to `[0]`, automatically move the modules and all its resources to the new address.

**Comment by jbardin** [comment]
Hi @Nuru,

The behavior of resources automatically adjusting from a single resource to a `count` of 1 is a legacy behavior we inherited from very early terraform, before the advent of `for_each` for which there is no equivalent. In practice this change being silently made tends to still require other changes to the configuration, so the convenience is often minimal especially when the automatic change introduces confusing errors elsewhere in the config.

Now that we have the `moved` block for refactoring, making the change explicitly is preferred, since it allows Terraform to better indicate the user's intent in the plan, and record the change in the configuration.

**Comment by apparentlymart** [comment]
Thanks for the feedback, @Nuru!

In addition to what @jbardin already said, I'll add that we did consider whether it would be viable to automatically generate implied move declarations in situations like what you described here but concluded that it was not feasible because there can potentially be many of these "implied moves" all at once in a single plan and that can make it potentially ambiguous how to resolve everything.

Leaf resources are relatively simple because there is only one object to consider: the single instance of the resource itself. But moving modules changes the addresses of many resources all together, and so it's much harder to define a single clear rule for how to resolve an arbitrary number of moves all at the same time.

Explicit `moved` blocks avoid the ambiguity by allowing the module author to be explicit about how they're refactored their configuration. This was an intentional design choice to eliminate confusing ambiguity, and we don't have any plan to change that decision, so I'm going to close this.

Thanks again!
