### ISSUE TITLE
check the type of input to a `for_each` on `validate` instead of failing at `plan`

### ISSUE THREAD

**Issue by matschundbrei** [hashicorp/terraform#33521]
### Terraform Version

```shell
Terraform v1.5.3
on linux_amd64
```

### Use Cases

If I use a `list()` instead of a `set()` as input variable for a `for_each` loop, I fail at the `plan` stage. This is costing me fair amount of time. I can validate locally but to plan I usually go through a pipeline, so it would speed up development time to catch this error on validate.

### Attempted Solutions

not applicable

### Proposal

As described above, I'd like to know on `validate` if any of the variable assignments in my code have type errors.

### References

- #29539
- #29010

**Comment by jbardin** [comment]
Hi @matschundbrei,

Thanks for the enhancement request. Terraform already does static validation of the `count` and `for_each` arguments, and can present an error during `validate` when the type is known. 

The difficult case here is when the expansion argument is based on a value derived from another expanded resource. Because validation must be done with all state and variable inputs unknown to determine if the configuration is valid for all possible values, we don't have an exact type for whole expanded resource values. Because resource types can contain dynamic types themselves, they cannot be universally contained within lists, or maps and must therefor be a `tuple` or an `object`. Because there is no way to represent a `tuple` or an `object` with an unknown number of elements or attributes, the unknown value for a whole expanded resource must be a single unknown dynamic value to prevent the resource from appearing as incompatible type in different contexts.

While it would be better to be able to statically determine the type in all contexts early on during validation, it's not clear right now how that could be done with the current type system we have.

**Comment by matschundbrei** [comment]
Alright, it is what it is I guess.

Thank you for the detailed explanation!
