### ISSUE TITLE
Plannable Import switch to ignore if resource doesn't exist

### ISSUE THREAD

**Issue by jasontfox** [hashicorp/terraform#33537]
### Terraform Version

```shell
Terraform v1.5.3
```

### Use Cases

I would like to be able to write terraform that can be run against several hundred similar resource groups (in my case, AWS accounts) that contains some level of baseline configuration. I was hoping to use the new plannable import feature to add import blocks before each resource definition in order to import existing resources and then apply the standardized resource config to each after successful import. Something like:

```HCL
import {
    to = aws_iam_role.account_example_role
    id = "aws-account-example-role"
}

resource "aws_iam_role" "account_example_role" {
    name = "aws-account-example-role"
    assume_role_policy = data.aws_iam_policy_document.account_example_role_assume_policy_doc.json
}
```

### Attempted Solutions

I have attempted to use the above, but the plannable import block fails to plan if the resource does not already exist. 

### Proposal

I would like a config setting in the import block that allows for skipping the import operation if the resource does not already exist, something like:

```HCL
import {
    to = aws_iam_role.account_example_role
    id = "aws-account-example-role"
    ignore_if_does_not_exist = true
}

with perhaps a better name for the parameter :) 

### References

_No response_

**Comment by robinbowes** [comment]
I've just run into this exact issue.

I was excited to see the new import block functionality - it will make it considerably easier to take on management of existing resources. But requiring the resource to exist  breaks my mental model of how I expected this to work.

I had in mind that the logic would be:
```
if a resource of type "foo" with ID "XXX" already exists:
   import it as resource foo.bar and apply the settings defined in code
else:
  create resource foo.bar as defined in code
```

I'm not sure that combining this with #33465 enhances visibility unless you explicitly mention this use-case in that ticket. #33465 seems to consider several other issues around importing, and gets embroiled in execution phases.

The use-case in this issue seems to be fairly simple and well-defined: don't fail if the resource to be imported does not already exist.

Please re-consider your closure of this issue.

**Comment by jbardin** [comment]
@robinbowes, closing this does not mean the behavior described is not under consideration in the overall project, but it does fall under the larger topic of resource discovery which is still being researched and planned. The procedural logic you used as an example would be very accurately categorized as "Procedural resource discovery and management" as it related to importing. Because this is a large project, and numerous related issues are and will be filed, it helps to have a single point of reference to point users to for any public updates.
