### ISSUE TITLE
Automatically recycle resources that are due to be deleted

### ISSUE THREAD

**Issue by njlr** [hashicorp/terraform#33540]
### Use Cases

Suppose you do the following:

 1. Define a resource in Terraform
 2. Apply the changes (create)
 3. Make a code change to rename the Terraform resource
 4. Apply the changes (delete and create)

Terraform is not smart enough to understand that the resources has not actually changed, so it will destroy and then recreate it. 

The suggested work-around is to move the resource in the state. 

 1. Define a resource in Terraform
 2. Apply the changes (create)
 3. Make a code change to rename the Terraform resource
 4. Move the Terraform resource in the state
 4. Apply the changes (no changes to be done)

However, this is quite a lot of operational overhead for something that (most of the time) could be automatic.
### Attempted Solutions

Move the resource in the state manually

### Proposal

Resources that are marked for deletion should be made available to the planner for recycling. The planner could choose to reuse resources if this would result in fewer changes to the underlying infrastructure. This would make most routine uses of Terraform move totally automatic.

**Comment by jbardin** [comment]
Hi @njlr,

The resource renaming operation you described is handled by a [`moved` block](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring). You can change the resource name in the configuration in conjunction with the moved bock to instruct Terraform how to rename the associated resource state.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by njlr** [comment]
> Hi @njlr,
> 
> The resource renaming operation you described is handled by a [`moved` block](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring). You can change the resource name in the configuration in conjunction with the moved bock to instruct Terraform how to rename the associated resource state.
> 
> We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
> 
> Thanks!

Thanks @jbardin 

I think that my suggestion is different to the `moved` block because it would be computed automatically.

**Comment by jbardin** [comment]
@njlr, Terraform cannot compute this automatically, because there is no way to determine that a resource has been moved as opposed to replaced in the configuration without some explicit input from the user. Aside from the resolution of multiple simultaneous moves being undecidable, the user still also needs a way to declare when the intent is actually to destroy one instance and create a new one with a different identifier that only happens to have the same type.
