### ISSUE TITLE
github.com/hashicorp/terraform/states/statefile is internal; is there another library surface to read statefiles?

### ISSUE THREAD

**Issue by deitch** [hashicorp/terraform#33551]
### Terraform Version

```shell
All since 1.0.0
```

### Use Cases

Trying to read statefiles to use inside other golang programs, for example reconciliation and audit.

### Attempted Solutions

In theory, `tf state list -state=statefile` lists all the resources, and `tf state show -state=statefile resource.name` does some of it, but it requires providers, and an unscalable exec call to `tf state show` for each resource, and has many other dependencies.

### Proposal

Prior to 1.0.0, I could just import `github.com/hashicorp/terraform/states/statefile` and use it.

Is there an alternate library surface? I did look at [go.mod](https://github.com/hashicorp/terraform/blob/main/go.mod) to see if it imported anything else that might do it, even though I see it in `internal/`, and did not find anything (unsurprisingly). I also looked for other repos under github.com/hashicorp, again, unsurprisingly, to no avail, given that it is internal.

I assume that is because each version of terraform manages its own version of state? Either way, what is the right way to do this? I assume that Hashicorp itself deals with the issue as well, internally for TFC and TFE? Or is everything just wrapping calls to `terraform`?

### References

None

**Comment by deitch** [comment]
Apologies for placing it under "feature request"; there wasn't a more obvious place for it.

**Comment by jbardin** [comment]
Hi @deitch, the public interface for Terraform is through the `terraform` binary. The state is an internal structure, and not subject to any compatibility constraints, which is why the libraries are nor longer exported.

If you want a machine readable form of the current state for a given configuration, you can use `terraform show -json`.See https://developer.hashicorp.com/terraform/internals/json-format for more details.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by deitch** [comment]
Thanks @jbardin . 

That gets harder to do with lots of statefiles, different versions, etc. I think I have something in place, but it is far from perfect.

I will move this over to the community board.

Enjoy the weekend. :-)
