### ISSUE TITLE
Catch Missing SSL Cert Error in plan phase

### ISSUE THREAD

**Issue by jasonkuhrt** [hashicorp/terraform#3356]
AWS requires a SSL certificate to be supplied for any listener that uses HTTP or TLS. The plan should catch errors related to this before its every applied. Current the apply can fail like e.g.:

```
aws_elb.service: Error creating ELB: ValidationError: Secure Listeners need to specify a SSLCertificateId
    status code: 400, request id: fae6b901-66b0-11e5-9950-2f21a2e05c9e
```

**Comment by apparentlymart** [comment]
Hi @jasonkuhrt! Thanks for this request, and sorry for letting it sit here for so long.

Currently Terraform does not have a mechanism internally to do this sort of multi-argument-sensitive validation, which is why we end up delegating this check to the underlying API at apply time. #8769 is a proposal to address that, which we will hopefully get to eventually. Until then, this issue just serves as an example use-case for such a feature, so as part of our effort to prune issues that aren't likely to see any activity in the near future I'm going to close this and let it just be referenced from that other issue as a reminder of this use-case for future reference.
