### ISSUE TITLE
Terraform crash during import with check defined

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/terraform#33572]
### Terraform Version

```shell
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.9.0
```

### Terraform Configuration Files

```terraform
# the specific provider does not make a difference, this is just an AWS example
provider "aws" {
  endpoints {
    s3 = "http://minio.service.home.consul"
  }
  region                      = "ap-southeast-2"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true
}

resource "aws_s3_bucket" "bucket" {
  bucket = "distribution"
}

check "consul_health" {
  data "aws_s3_bucket" "distribution" {
    bucket = "distribution"
  }

  assert {
    condition     = data.aws_s3_bucket.distribution.arn == "arn:aws:s3:::distribution"
    error_message = "bucket arn does not equal \"arn:aws:s3:::distribution\""
  }
}
```

### Debug Output

[Crash log](https://gist.github.com/tristanmorgan/7d1b0c54d96c359332ae4556dbce8fbf) from running
```bash
TF_LOG=debug terraform import aws_s3_bucket.bucket "distribution"
```

### Expected Behavior

Successful import of resource

### Actual Behavior

Terraform crashed.

### Steps to Reproduce

Using the sample code
1. terraform init
2. terraform import aws_s3_bucket.bucket "distribution"
results in a crash

### Additional Context

The issue seems to occur when any **check block with a data source** is defined while **import**ing a resource. in this example I used a data source matching the imported resource but it could be any data source.

I initially caused the crash using the nomad provider and it does not seem to be provider specific.

**Comment by liamcervante** [comment]
Hi @tristanmorgan, thanks for filing this issue! I can confirm I am able to replicate. Just a slight clarification for clarity: It's the nested data block that is causing the crash rather than the check block itself. Still a good find, and something I will looking into fixing.

A quick explanation. The nested data blocks are missing the logic telling them to skip evaluation during an import operation. This logic has been applied to the other elements of the check block. This is then crashing when the scoped data block attempts to report it's checkable status and the system isn't expecting any checkable statuses.

Thanks again for finding this!
