### ISSUE TITLE
Count on Module with array length 1 does not get an index

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform#33591]
### Terraform Version

```shell
1.5.3
```

### Terraform Configuration Files

```terraform
module "application_token" {
  count  = length(var.application_data)
  source = "REDACTED"

  organization          = var.application_data[count.index]["organization"]
  application_name      = var.application_data[count.index]["application_name"]
  team_name             = var.application_data[count.index]["team_name"]
  execution_roles_names = var.application_data[count.index]["execution_roles_names"]
}

module "cross_account_iam_role_east_1" {
  count  = length(module.application_token)
  source = "REDACTED"

  execution_roles_names = module.application_token[count.index].execution_roles_names
  application_name      = module.application_token[count.index].application_name
  consul_http_token     = module.application_token[count.index].consul_http_token
  region                = "us-east-1"

  providers = {
    aws = aws.us-east-1
  }
}
```

### Debug Output

unobtainable

### Expected Behavior

The second module, counting over the length of the first, should be reference-able by index.

### Actual Behavior

│ Error: Unsupported attribute

│ 

│   on main.tf line 48, in module "cross_account_iam_role_east_1":

│   48:   execution_roles_names = module.application_token[count.index].execution_roles_names

│     ├────────────────

│     │ count.index is a number

│     │ module.application_token is a list of object

The above error occurs, as though I did not use count.  It seems that an array of 1 gets deemed to be not an array potentially, and when this occurs, the initial module call is treated as though count is not there, resulting in a flat object.

### Steps to Reproduce

1. create a call to a module with the count meta argument, supplying a length of 1
2. call either a looped output or resource to reference the initial module by index
3. terraform init
4. terraform plan

**Comment by jbardin** [comment]
Hi @reskin89,

It looks like you cut off the actual error from the output here, but perhaps the error is something like:
> This object does not have an attribute named "execution_roles_names"

You either need to create a corresponding output for your module, or you need to copy the same expression for the second module's input rather than trying to reference the module's input variables.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, if you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
