### ISSUE TITLE
Error while loading schemas for plugin components: Failed to obtain provisioner schema: Could not load the schema for provisioner "local_exec": failed to instantiate provisioner "local_exec" to obtain schema: unavailable provisioner "local_exec"..

### ISSUE THREAD

**Issue by henryAC3** [hashicorp/terraform#33596]
### Terraform Version

```shell
Terraform v1.5.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.60.0"
    }
  }
    backend "s3" {   
  }
  
  required_version = "1.5.4"
}
provider "aws" {
  region = var.az
}

provider "local" {}

  resource "null_resource" "generate_key_pairs" {
    count = var.create_key_pair == true ? 1 : 0
    provisioner "local_exec" {
    command = "./ssh_key_generator.sh"
    when = create
    }
  }
```

### Debug Output

https://gist.github.com/henryAC3/77fcd0138bfbceb2882166e8a7fc6f8f

### Expected Behavior

Terraform Local Exec Provisioner should have ran and executed a bash script to generate private and public keys.

### Actual Behavior

I get an error as indicated above which I have no clue how to fix and nothing on Google with anyone coming up with this exact error. 

### Steps to Reproduce

terraform init --backend.conf=backend.config
terraform plan

**Comment by jbardin** [comment]
Hi @henryAC3,

There is no provisioner named `local_exec`, the provisioner name is `local-exec`. I'm not sure if you are using it elsewhere, but the `local-exec` provisioner is unrelated to the `local` provider, but even if you are using the `local` provider an empty provider block for it is not necessary.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
