### ISSUE TITLE
`tostring` documentation shows incorrect output

### ISSUE THREAD

**Issue by gui-don** [hashicorp/terraform#33603]
### Terraform Version

```shell
1.5.3
```

Hi 👋 

Contrary to what the [documentation states](https://developer.hashicorp.com/terraform/language/functions/tostring): `tostring(null)` does not return `"null"`.

I also expect `tostring` to return non-nullable result, but that’s maybe another ticket.

### Expected Behavior

```
> tostring(null) == "null"
```

```
true
```

### Actual Behavior

Console test:
```
> tostring(null) == "null"
```

Result:
```
false
```

😮 

However:

Console test:
```
> tostring(false) == "false"
```
Result:
```
true
```

`tostring(null)` actually returns `null`.

### Steps to Reproduce

terraform console
tostring(null) == "null"

**Comment by jbardin** [comment]
Hi @gui-don,

This is the expected behavior. `tostring(null)` produces a null value of type string, whereas `null` is dynamically typed. The type conversion can be made with no conversion of the value, and does not turn the literal `null` value into its string representation. The reason for the difference in `false`, is that `false` is a boolean type which is distinct from a `string`, and is allowed to be converted to a `"false"` string for convenience and compatibility with legacy versions of Terraform.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by gui-don** [comment]
@jbardin seems to me it requires at least a note in the documentation?

**Comment by jbardin** [comment]
It is mentioned in a few places, like [Type Conversion](https://developer.hashicorp.com/terraform/language/expressions/types#type-conversion), and [Conversion of Primitive Types](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#conversion-of-primitive-types). The human-readable output tried to differentiate the types values as best it can, by making sure strings are always quoted, and wrapping values in their type conversion function when possible:

```
> tostring(1)
"1"
> tostring(false)
"false"
> tostring(null)
tostring(null)
```

**Comment by gui-don** [comment]
OK, thanks for the explanation!

However there are several things that bugs me just here: https://developer.hashicorp.com/terraform/language/functions/tostring

> tostring converts its argument to a string value.

> Only the primitive types (string, number, and bool) and null can be converted to string.

Neither of these sentences mention "type", which than is quite a different thing as I'm understanding you. Many will assume, as I did, that the null value would be converted to its string **representation** not its string **type**.

Also in the page:
> tostring(null)
> null

Which seems inaccurate, as it returns `tostring(null)` then.

**Comment by jbardin** [comment]
Oh! It seems that page you linked is just out of date. I think updating the output there will help alleviate the confusion.

**Comment by crw** [comment]
I filed a quick PR for this change. Will work with the docs team to get it reviewed. Thanks!
