### ISSUE TITLE
length  getting wrong count in

### ISSUE THREAD

**Issue by sohanyadav** [hashicorp/terraform#33664]
### Terraform Version

```shell
$ terraform -v                                
Terraform v1.5.2
on linux_386
```

### Terraform Configuration Files

```terraform

variable "networks" {
  type = map(object({
    cidr_block = string
    type       = string
  }))
  default = {
    sohan = {
      cidr_block = "10.0.0.0/24"
      type       = "public"
    }
    test2 = {
      cidr_block = "10.0.1.0/24"
      type       = "private"
    }
    // Add more entries if needed
  }
}

locals {
  private_networks = {
    for key, network in var.networks :
    network.type == "private" => network
  }

  private_network_count = length(keys(local.private_networks))
}

output "private_network_count_output" {
  value = local.private_network_count
}

...terraform config...
```

### Debug Output

Changes to Outputs:
  + private_network_count_output = 2

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

### Expected Behavior

1

### Actual Behavior

2

### Steps to Reproduce

terraform plan

**Comment by arturtamborski** [comment]
I think the actual behavior is correct.



```hcl
private_networks = {
    for key, network in var.networks :
    //                   bool => object
    network.type == "private" => network
  }
```

this will generate a map of bool => object
- the resulting type is a map, therefore it can contain only unique keys,
- and since your keys are bools, there can be only two of them (true or false)
- and because your var.network default's value has both cases covered (network.type being "private", and "public")
- then the expanded map will be something like that:

```hcl
local. private_networks = {
    true = {
      cidr_block = "10.0.0.0/24"
      type       = "public"
    }
    false = {
      cidr_block = "10.0.1.0/24"
      type       = "private"
    }
}
``` 

which is technically correct (terraform does what you told it to do), but semantically incorrect (that's not what you wanted to get here).


Judging by the variable names, what you really wanted was likely something like this?
```hcl
private_networks = {
    for key, network in var.networks :
    key => network if network.type == "private"
  }
```

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
