### ISSUE TITLE
The 'cloudinit_config' is recreated when there are changes to unrelated resource arguments.

### ISSUE THREAD

**Issue by mateuszgalar** [hashicorp/terraform#33666]
### Terraform Version

```shell
Terraform v1.5.5
```

### Terraform Configuration Files

```
resource "aws_db_instance" "database" {
  instance_class = "db.t3.micro"
  username       = "admin"
}

data "cloudinit_config" "user_data" {
  base64_encode = true

  part {
    filename     = "hello-script.sh"
    content_type = "text/x-shellscript"

    content      = aws_db_instance.database.username
  }
}
```

### Debug Output

-

### Expected Behavior

Changing a resource argument that isn't related to 'clouding_config' doesn't trigger the recreation of data.

### Actual Behavior

Modifying an argument of resource that isn't utilized in the 'cloudinit_config' lead to data reevaluation. Consequently, EC2 instances using this user data will be replaced, because of the `user_data_replace_on_change` argument being set to true.

### Steps to Reproduce

1. Create resources from attached configuration file.
2. Change `aws_db_instance.database` `instance_class`.
3. `terraform plan` - it will show changes in cloudinit_config file.

### Additional Context

It appears to be a similar issue as discussed in this thread:  https://github.com/hashicorp/terraform/issues/22655. I was able to work around this by applying the proposed there changes that involve moving the `aws_db_instance.database.username` to the locals block.

**Comment by jbardin** [comment]
Hi @mateuszgalar,

The behavior here is a result of the data source directly referencing a managed resource, which creates an implied dependency (see https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior). You generally don't need to refer to non-computed attributes of a managed resource, and can break those out into a `local` value to avoid the dependency:
```
locals {
  db_username = "admin"
}

resource "aws_db_instance" "database" {
  instance_class = "db.t3.micro"
  username       = local.db_username
}

data "cloudinit_config" "user_data" {
  base64_encode = true

  part {
    filename     = "hello-script.sh"
    content_type = "text/x-shellscript"

    content      = local.db_username
  }
}
```


We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
