### ISSUE TITLE
Terraform Should Warn if Init Will Modify a Remote Module

### ISSUE THREAD

**Issue by GLStephen** [hashicorp/terraform#33711]
### Terraform Version

```shell
Terraform v1.5.3
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.5.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

When debugging issues it is sometimes necessary to make modifications to a module. It can happen that those changes are not completely documented. An init or upgrade may wipe out those changes.

### Attempted Solutions

Forking and other workarounds.

### Proposal

 It would be nice if Terraform could indicate, similar to GIT, that "changes exist in remote modules" or something similar.

**Comment by jbardin** [comment]
Hi @GLStephen,

Can you show an example of what you mean by editing a remote module? I'm guessing that you are referring to the files stored within the `.terraform/` directory, but that directory should only be written by the CLI, so the CLI expects it to always be consistent.

Thanks!

**Comment by GLStephen** [comment]
@jbardin Thanks for the quick response. I'm admittedly new to terraform for more than toy apps, so I'm learning some of the conventions. I understand the idea behind the modules directory now based on your comment about CLI creating them.

What I'm encountering is this bug biting us on autopilot clusters: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1700

I'm trying to find the best way to maintain our infra until that patch lands. I'm encountering 3 issues:

1. maintaining a fork is complicated for a simple change
2. the downloaded source that the CLI uses doesn't appear to be local to manually patch that in
3. editing the modules directory is wrong

So, how do I pull that critical patch in the most efficient way until it lands in the official repo?

**Comment by apparentlymart** [comment]
Hi @GLStephen,

It might be useful to know that a Terraform module registry (of which [Terraform Registry](https://registry.terraform.io/) is an example) is really just an abstraction over physical storage: rather than specifying exactly where that code is, you just specify the module you want to use and then the registry maps that onto a physical artifact -- in this case, a tag in a GitHub repository -- that the address refers to.

In situations like yours that abstraction isn't really helpful: you want to use some code that hasn't been published yet, and so isn't visible through the Terraform Registry API.

You can avoid that problem in the meantime by skipping the registry abstraction and just specifying directly the underlying GitHub source referring to, for example, the commit currently associated with that PR:

```hcl
  source = "git::https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git?ref=f88afab05f8515386d5047373cc916b66c20593d"
```

Terraform Registry would, for a released version of that module, return a very similar source address just with the `ref` argument set to the appropriate release tag rather than to an exact commit as I showed above. Therefore this direct Git URL should behave the same way as the registry address would, and you can keep pointing at that unreleased commit until the change has been included in a tagged release. After that, you can either change `ref` to refer to the release tag or switch back to using a registry-style source address, which will achieve the same effect.

**Comment by GLStephen** [comment]
@apparentlymart I appreciate the support here on github, thanks for the information and that makes total sense
