### ISSUE TITLE
Invalid for_each argument (is empty set of string)

### ISSUE THREAD

**Issue by fabio-s-franco** [hashicorp/terraform#33733]
### Terraform Version

```shell
Terraform v1.5.5
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
    }
  }
}

provider "null" {

}

variable "private_prefixes" {
  type = list(string)
  default = []
}

locals {
  dns_prefixes = {
    private = toset(var.private_prefixes)
  }
}

resource "null_resource" "private_ip" {
  for_each = local.dns_prefixes.private[*]

  triggers = {
    name                = each.value
    zone_name           = "azurednszone.example"
    resource_group_name = "rg-example"
    ttl                 = 3600
    # records             = ["1.1.1.1"] # Inappropriate value for attribute "triggers": element "records": string required. (??????)
  }
}

```

### Debug Output

Trace is way too big and it would be too risky to put it here. I can gladly dig it if it becomes necessary.

### Expected Behavior

No resources are deployed with an empty set of strings

### Actual Behavior

```shell
╷
│ Error: Invalid for_each argument
│ 
│   on ../base/dns_records.tf line 12, in resource "azurerm_dns_a_record" "private_ip":
│   12:   for_each = local.dns_prefixes.private[*]
│     ├────────────────
│     │ local.dns_prefixes.private is empty set of string
│ 
│ The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of type list of string.
```

### Steps to Reproduce

```
1. init
2. plan
```

This seems to be a past bug resurfacing: [PR 22756](https://github.com/hashicorp/terraform/pull/22756)

The odd thing is also if you read the error message carefully you will notice the contradition:

`local.dns_prefixes.private is empty set of string`

The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and `you have provided a value of type list of string`.

### Additional Context

I didn't have time yet  to make a full resource independent repro, but I will try to do that soon and can update here.

**Edit:** Updated configuration to be easily reproducible with null resource.

### References

- #22756

**Comment by jbardin** [comment]
Hi @fabio-s-franco,

The given error is correct, in both ways. The value `local.dns_prefixes.private` is an empty set of strings. That is not the argument you have passed to `for_each` however, you passed the result of the [splat expression](https://developer.hashicorp.com/terraform/language/expressions/splat), `local.dns_prefixes.private[*]` which results in a list of strings, as `[*]` is equivalent to a for expression iterating over each value and adding them to a list.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by fabio-s-franco** [comment]
@jbardin If I thought this was anything else than a bug, then I would have used the forum. It was not a question hence why I referenced e previous seemingly related issue.
