### ISSUE TITLE
Terraform PLAN output options for JUNIT format

### ISSUE THREAD

**Issue by neilmca-inc** [hashicorp/terraform#33756]
### Terraform Version

```shell
1.5.6 - or any version
```

### Use Cases

To use the JUNIT output format to attach to Azure DevOps pipeline tab outputs for easy reading of Terraform PLAN output. 

There maybe other CI/CD platforms that utilise JUNIT format output

### Attempted Solutions

Other tools that operate around Terraform make attempts to do this - for example CHECKOV allows scan result output to a JUNIT format file

### Proposal

terraform plan -junit

### References

None that I am aware of

Someone has attempted to do this here - but I think it should be supported natively in Terraform itself - thanks

See the section on Terraform Plan View in this article `https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform`

`https://raw.githubusercontent.com/charleszipp/azure-pipelines-tasks-terraform/main/screenshots/overview-tfplan-view.jpg`

**Comment by apparentlymart** [comment]
Hi @neilmca-inc! Thanks for this feature request.

The initial experimental version of `terraform test` included a JUnit XML output mode for test results with a similar goal in mind.

During the design and implementation of that, we learned:
- JUnit XML is not standardized and each implementation behaves slightly differently.

    Successfully implementing it for general use requires individual testing with every single parsing implementation to find a suitable subset of the format that is cross-compatible.
- The domain model of JUnit XML was originally designed for JUnit in particular and so inherits many assumptions from that test framework.

    Test frameworks in other languages that closely followed JUnit's concepts were able to adopt it relatively well, but it's challenging to apply this format to something that doesn't follow JUnit's set of concepts closely.

    This was already challenging for `terraform test` where we needed to decide what in Terraform corresponds to the concepts "test suite", "class", etc. I feel even less sure about how we'd map a non-testing use of Terraform, like `terraform plan`, to that format.

With Terraform as currently implemented I would recommend consuming `terraform show -json PLANFILE` and translating that into JUnit XML that's suitable for your specific situation. Targeting only one JUnit XML parser is easier than targeting all of them, and you will only need to make concept-mapping decisions that suit how you personally would like to see this information in your chosen automation platform, rather than designing something that would work for many different people with different needs and preferences.

That doesn't mean that we could not implement such a thing in a future version of Terraform in principle, but given the effort involved and the general mismatch in meaning between a Terraform plan and a test suite report I don't expect we would be able to prioritize this soon. If you have some concrete ideas about how it might be designed then we would be happy to consider them, but can't promise that it will lead to actually adding this feature as requested.

Thanks!

**Comment by neilmca-inc** [comment]
Thanks for the detailed reply @apparentlymart
