### ISSUE TITLE
Force TLS1.2 to build the connection between terraform and AWS s3 bucket

### ISSUE THREAD

**Issue by xyfleet** [hashicorp/terraform#33761]
### Terraform Version

```shell
Terraform v1.3.7
```

### Use Cases

AWS is going to force to use TLS 1.2 for all of the connections to S3 bucket. We need to know if Terraform already to upgrade the connection to use TLS1.2. Or if we can configure Terraform to use TLS1.2.

### Attempted Solutions

None

**Comment by apparentlymart** [comment]
Hi @xyfleet,

I've labelled this as an issue related to the S3 backend because the backend is maintained by the AWS provider team and so this label will hopefully make the issue visible to them.

I believe the S3 backend makes its requests to AWS indirectly through the AWS SDK and so this is essentially a question of what the AWS SDK supports.

If the AWS SDK is making its requests using the TLS support in the Go language's standard library then Terraform has effectively been requiring TLS 1.2 or later since Terraform v1.1, since that was the first release of Terraform CLI that we built using Go 1.17, and Go 1.17 was the first release to require TLS 1.2 when making requests as a client.

Before Terraform v1.1 I believe Terraform _supported_ TLS 1.2 but did not yet _require_ TLS 1.2. As long as you are using Terraform v1.0.0 or later your Terraform CLI should support TLS 1.2.

I'll leave this open for the AWS provider team to confirm whether what I've written above applies to the AWS SDK / S3 backend or if the S3 backend is using a custom TLS client or custom TLS settings that might cause it to behave differently than other parts of Terraform CLI.

**Comment by xyfleet** [comment]
Thank you so much. AWS send email to us to say they will force S3 bucket to use TLS 1.2 before the end of this year(Dec 31, 2023). Just want to make sure all of us prepared for this coming change.

**Comment by gdavison** [comment]
Hi @xyfleet. We use the AWS SDK for Go for the S3 backend, and Terraform v1.6 will use the AWS SDK for Go v2. Both the SDK v1 (https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/tls.html) and v2 (https://aws.github.io/aws-sdk-go-v2/docs/security/tls/) configure a minimum TLS version of 1.2
