### ISSUE TITLE
Failed to install provider: operation not permitted - when running terraform init from within a docker container

### ISSUE THREAD

**Issue by msingh0101** [hashicorp/terraform#33773]
### Terraform Version

```shell
Terraform v1.5.6
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.17.0"
    }
    azapi = {
      source  = "Azure/azapi"
      version = "~>0.4.0"
    }
  }
}

provider "azurerm" {
  features {}
}

provider "azapi" {}
```

### Debug Output

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "~> 3.17.0"...
- Finding azure/azapi versions matching "~> 0.4.0"...
- Installing hashicorp/azurerm v3.17.0...
- Installing azure/azapi v0.4.0...

│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/azurerm v3.17.0: chmod .terraform/providers/registry.terraform.io/hashicorp/azurerm/3.17.0/linux_amd64/terraform-provider-azurerm_v3.17.0_x5: operation not permitted

│ Error: Failed to install provider
│ 
│ Error while installing azure/azapi v0.4.0: chmod .terraform/providers/registry.terraform.io/azure/azapi/0.4.0/linux_amd64/terraform-provider-azapi_v0.4.0: operation not permitted

### Expected Behavior

Im expecting this to work as it does under windows/linux outside of a container.

### Actual Behavior

I am running in VSCode IDE using a dev container.  From within the container if try to do a 'terraform init', I get the following error:

```│ Error: Failed to install provider
   │ 
   │ Error while installing hashicorp/azurerm v3.17.0: chmod .terraform/providers/registry.terraform.io/hashicorp/azurerm/3.17.0/linux_amd64/terraform-provider-azurerm_v3.17.0_x5: operation not permitted
```

As you can see from the logs it is failing when trying to change permissions of the provider library.
If i were to try this using the same path and files from just windows, it works fine.

### Steps to Reproduce

1. terraform init

### Additional Context

The container is a vscode 'devcontainer' running as user 'vscode', which is a root user and based on the following image:  
```mcr.microsoft.com/devcontainers/python:3-bullseye as v8_pi_lab_base```

im also adding the following to the end of my docker file to ensure the user im running as has permissions and ownership of the folders:
```
RUN mkdir -p $WORKSPACE_HOME
RUN chown -R vscode $WORKSPACE_HOME
RUN chmod -R 777 $WORKSPACE_HOME
```

**Comment by apparentlymart** [comment]
Hi @msingh0101,

As far as I can tell from the error message, Terraform seems to have been prevented from writing into the directory by some restriction enforced by your operating system.

Unfortunately we can't see how you have this configured, so I'm not sure what to suggest. Terraform requires the ability to create subdirectories and files into the plugin cache directory to complete installation. You will need to configure your system to allow Terraform that access.

You may be able to use the tool `strace` to see exactly what Linux system call is returning this error, which might give a clue as to what kind of access Terraform is being denied, but understanding the output of that tool requires familiarity with the Linux system call API.

If you can share the trace logs from Terraform as requested in the original issue template then we may be able to offer more specific advice.

**Comment by msingh0101** [comment]
Interestingly it's able to create the .terraform folder w/o issues, just the 'chmod' call is failing.   I will figure out how to do get the terraform trace logs and post...

**Comment by apparentlymart** [comment]
Hi @msingh0101,

One guess I would have about a failing `chmod` is if this directory belongs to a filesystem that cannot support Unix-style filesystem permissions. I'm not personally familiar with exactly how VSCode dev containers are configured, but if it's set up to provide the container access to files in the host filesystem then presumably there's some kind of adapter layer translating filesystem operations from the Linux context into equivalent filesystem operations in the host OS, in which case I expect the supported operations are constrained by what that translation layer can support and what the host OS filesystem can support.

Terraform provider plugins are executable programs and so there isn't any way to avoid the need to mark them as executable using the `chmod` operation. If they were not marked as executable then Terraform would not be able to launch the plugin during commands like `terraform plan`. Therefore you will need to configure this container so that at least the `.terraform` directory is able to support Unix-style file permissions through the `chmod` operation.

**Comment by msingh0101** [comment]
[init.log](https://github.com/hashicorp/terraform/files/12489534/init.log)

Attached is the log.  i dont see anything useful.   To answer your other questions
1. I am mounting the working folder from my windows 11 desktop  into the container. (im running Docker Desktop in this case)
2. the mount is also a google drive (G: drive on my windows filesystem, where i keep all my project files)
3. Though the above may raise some eyebrows - i have been doing this for some time and have not had any issues mounting a windows file path into my linux containers in this manner.

regarding...
>  If they were not marked as executable then Terraform would not be able to launch the plugin during commands like terraform plan. 
The file when create is already marked is already marked a r/w/x actually (in below, user vscode is root)
```
vscode ➜ .../azure/azapi/0.4.0/linux_amd64 $ ls -ltr
total 64484
-rwxrwxrwx 0 root root 66031616 Aug 31 15:22 terraform-provider-azapi_v0.4.0
```

> Note also that there are packages available to run Terraform directly on your Windows system without any need for a Linux subsystem. The Windows version of Terraform is designed to work with the features of Windows instead of the features of Linux, and so if you run Terraform directly on your Windows system instead you are less likely to run into these inconsistencies where the Linux container cannot provide the full capabilities Terraform expects of a typical Linux system.

On windows this all works fine indeed.
In the linux container im installing the linux version of terraform obviously.  Works fine for everything except this init.  for example, since the folder is mounted, i can init on windows...and then proceed to work in the container with terraform on linux w/o issues (so far).

**Comment by apparentlymart** [comment]
Thanks for that extra context.

It seems that the filesystem here cannot preserve Unix-style permissions and so in an attempt to still create a partial abstraction the filesystem just returns that everything has mode 0777 -- everyone can read, write, and execute. Is that right?

I suppose then the filesystem rejects any attempt to use chmod to set more restrictive permissions, by returning the error you showed.

Do the maintainers of whatever filesystem implementation you're using here document any advice for how to use it with software that expects a permissions-preserving filesystem? (The `mount` command can hopefully tell you exactly which filesystem it is from Linux's perspective, though perhaps that will only give half of the answer since there's presumably something in the virtual machine manager that's dealing with the "lower half" of this abstraction.)

**Comment by msingh0101** [comment]
im not sure if its Google Drive or Docker Desktop that's the issue with the file permissions in this case...
The mount command is a basic docker-compose.yaml volume mount.
But i think you are on to something there.   

Outside the container:
```-rw-r--r-- 0 mbsin 197609 230 Aug 31 15:45 modules.json```

Inside the container:
```-rwxrwxrwx 0 root root 230 Aug 31 15:45 modules.json```

**Comment by msingh0101** [comment]
well, it would seem we may not be able to use terraform in this manner due to limitations of docker on windows, and in particular the use of chmod:
https://stackoverflow.com/questions/46597290/cant-change-the-permissions-of-files-folders-on-a-volume-with-docker-windows

```Docker for Windows currrently implements host-mounted volumes based on the Microsoft SMB protocol, which does not support fine-grained, chmod control over these permissions.```

that's a shame.  wonder if it's something that can be worked around...

**Comment by apparentlymart** [comment]
I don't have a SMB/CIFS server with which to confirm this, but this seems to suggest that you can configure the cifs driver to just silently ignore chmod/chown instead of returning an error:

https://superuser.com/questions/744384/allow-chmod-on-cifs-mount

**Comment by msingh0101** [comment]
ah. i will give it a shot - just have to figure out how to set this 'noperm' in a docker-compose file

**Comment by msingh0101** [comment]
i tried this solution...but its not working.  It coluld also be that im missing something here or not doing this correctly.  any here's what i did...

in my docker-compose i declare a named volume and set the option 'noperm' and im using that as the volume for my service mount
```
volumes:
    win_mount:
      name: win_mount
      driver_opts:
        type: cifs
        o: noperm
        device: ../..
```

but once the container is up..the windows fs is mounted correctly.  But if i do a terraform init, get the  same error.

**Comment by apparentlymart** [comment]
Thanks for trying that, @msingh0101!

I'm afraid this problem is now beyond the reach of my expertise; it seems more like a Docker configuration or Linux container abstraction problem than a Terraform problem.

Can you manually create a file in the relevant directory and then run `chmod 0755 FILENAME` on it to confirm whether you get a comparable error? If this _does_ seem specific to Terraform rather than just a filesystem driver behavior then we could try to understand what Terraform is doing differently than the `chmod` command, but if this problem exists in your kernel rather than in Terraform then I'd recommend trying to seek advice in a different forum where you're more likely to find someone who has experience with this requirement of supporting (or just ignoring) `chmod` under this VM/container scenario.

**Comment by msingh0101** [comment]
i understand completely. no it's not a terraform issue.
to ur question..no i cant chmod files i newly create either within the container from that specific windows mount/volume

I'd say its more of a docker/docker desktop issue...

**Comment by crw** [comment]
Per the previous comment, closing this issue. Thanks for your feedback, and just for your information there is an official [community forum](https://discuss.hashicorp.com/c/terraform-core/27) that might be useful for taking this conversation farther. 

Thanks!
