### ISSUE TITLE
Only initialize a provider if there are resources in the graph / state

### ISSUE THREAD

**Issue by jaredfholgate** [hashicorp/terraform#33790]
### Terraform Version

```shell
Terraform v1.5.6
on windows_amd64
```

### Use Cases

I'm writing a bootstrap module where the user can choose to setup in GitHub or Azure DevOps. I'd ideally like a single module with a parameter to choose one of the other.

As it stands this is not possible, even if I use `count` to ensure there are no resources in the graph for Azure DevOps, it still attempts to initialize the provider. The provider makes an API call when initialised, which fails due to the lack of credentials.

If there are no resources in the HCL, then it does not attempt to initialise the provider.

### Attempted Solutions

- Putting the resources in a module and setting the count to 0.
- Nulling the provider settings.
- Setting `-refresh=false` makes no difference.
- Reading the code to understand what is happening.
- Using `-target=****` could be a solution, but results in nasty warning messages.

### Proposal

Terraform could read the HCL and state file, build the graph and determine that there are no resources under management even though the resource type is declared in the HCL. I.e. It does not need to make any calls to the provider for those resources for refresh or apply.

In that scenario do not attempt to initialise the context of the provider.

**Comment by jbardin** [comment]
Hi @jaredfholgate,

Thanks for filing the issue. It's not generally possible to prevent initialization of the provider early on, because the provider process must be started in order to obtain the schema to decode the configuration. I sounds however like you are looking to delay the configuration of the provider until an actual call to plan or apply a resource change. If that's the case we have #31662 which can be used to track that as a possible future enhancement.

Thanks!
