### ISSUE TITLE
The repository 'https://apt.releases.hashicorp.com victoria Release' does not have a Release file.

### ISSUE THREAD

**Issue by freebased** [hashicorp/terraform#33795]
### Terraform Version

```shell
latest
```

### Terraform Configuration Files

```
wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install terraform
```

### Debug Output

$ sudo apt update && sudo apt install terraform
Ign:1 http://linux-mint.froonix.org victoria InRelease
Hit:2 http://linux-mint.froonix.org victoria Release                                                                                                                                                
Hit:3 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                                     
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease    
Ign:6 https://apt.releases.hashicorp.com victoria InRelease
Err:7 https://apt.releases.hashicorp.com victoria Release
  404  Not Found [IP: 2600:9000:223d:3c00:18:566b:ecc0:93a1 443]
Hit:8 http://ubuntu.man.lodz.pl/ubuntu jammy InRelease
Hit:9 http://ubuntu.man.lodz.pl/ubuntu jammy-updates InRelease
Hit:10 http://ubuntu.man.lodz.pl/ubuntu jammy-backports InRelease
Reading package lists... Done
E: The repository 'https://apt.releases.hashicorp.com victoria Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Expected Behavior

200

### Actual Behavior

404

### Steps to Reproduce

1. wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
2. echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
3. sudo apt update && sudo apt install terraform

**Comment by apparentlymart** [comment]
Hi @freebased,

The name "victoria" doesn't match any of [the Debian-based distributions we build Terraform for](https://www.hashicorp.com/official-packaging-guide?product_intent=terraform).

Terraform is distributed in these `.deb` packages as a statically-linked executable that depends only on the Linux kernel system call interface, so I expect that you'll be able to use a package intended for one of the supported distributions successfully on yours as long as this distribution has an up-to-date Linux kernel.

From your `apt update` output it seems like you are already using some Ubuntu "jammy" packages on your system, and so I assume this distribution is relatively similar to that Ubuntu release. If so, you could try using "jammy" instead of "victoria" in your `hashicorp.list` file.

Since "victoria" is not one of the supported distributions, I'm going to close this issue. Hopefully the above will help you use packages from one of the Ubuntu releases to install Terraform on your system despite it not being explicitly supported. If not, I think your best available option would be to install from [the main distribution `.zip` files](https://releases.hashicorp.com/terraform/).
