### ISSUE TITLE
Data source in submodule referring to resource to be created in parent module fails to plan

### ISSUE THREAD

**Issue by Storm-BE** [hashicorp/terraform#33802]
### Terraform Version

```shell
Terraform v1.5.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.71.0

I originally tested on v1.5.1
```

### Terraform Configuration Files

`main.tf`:
```terraform
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "parent" {
  name     = "parent"
  location = "westeurope"
}

module "submodule" {
  source              = "./submodule"
  
  # You'd expect this to create an implicit dependency
  resource_group_name = azurerm_resource_group.parent.name
}

```

`submodule/main.tf`:
```terraform
variable "resource_group_name" {
  type = string
}

# This gets read during the plan, even though the `var.resource_group_name` gets a value from `azurerm_resource_group.parent.name` in the parent module
data "azurerm_resource_group" "parent" {
  name     = var.resource_group_name
}

resource "azurerm_resource_group" "sub" {
  name     = "${data.azurerm_resource_group.parent.name}-sub"
  location = "westeurope"
}
```

### Debug Output

https://gist.github.com/Storm-BE/45182b4b23666ac146ab7065c31d81b4

### Expected Behavior

I'd expect TF to produce a working plan, delaying reading the data source until that resource group actually has been created by the parent module.

### Actual Behavior

Error during plan:
```
╷
│ Error: Error: Resource Group "parent" was not found
│
│   with module.submodule.data.azurerm_resource_group.parent,
│   on submodule\main.tf line 6, in data "azurerm_resource_group" "parent":
│    6: data "azurerm_resource_group" "parent" {
│
╵
```

### Steps to Reproduce

1. terraform init
2. terraform plan

### Additional Context

I know I can work around this in this specific minimal reproduction with an explicit dependency (`depends_on`). 
However, this causes other issues in my actual project (for_each fails when the number of items is unknown during plan, because `depends_on` forces ALL data source reads to be delayed)

**Comment by jbardin** [comment]
Hi @Storm-BE,

Terraform is working as designed here. A data source is intended to be read during the plan whenever possible, so unless you specify somehow in the configuration that the `azurerm_resource_group.parent` data explicitly depends on actions taken by the `azurerm_resource_group.parent` managed resource, Terraform cannot order the resources correctly. For this reason we don't recommend ever having a managed resource and a data resource both representing the same logical resource within a single configuration. While it would be preferable to not use the data source here at all, if you must use it for some reason (usually due to some bug or inconsistency in the provider implementation), you can use `depends_on` to point to a single input variable which contains the computed outputs from the managed resource.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
