### ISSUE TITLE
With the `test` command, how to handle "known after apply"?

### ISSUE THREAD

**Issue by lorengordon** [hashicorp/terraform#33806]
### Terraform Version

```shell
terraform 1.6
```

### Use Cases

When writing terraform modules and their test configs, we occasionally find that we cannot find a way to express the module or the test in a way we want, while also avoiding all instances of "known after apply". In many cases, this is simply because in the test config, we use the `random` provider to add a random component to the "label" that gets used in the `for_each` expression in the module.

To support this in our current test setup (based on the [`tftest` python library](https://github.com/GoogleCloudPlatform/terraform-python-testing-helper)), our pytest wrapper will first check for a `prereq/` directory and apply that config first. The prereq config will output any values needed by the test config. The test config will then use the terraform_remote_state data source to retrieve the values from the local state file. Here is an example of this setup: https://github.com/plus3it/terraform-aws-tardigrade-sso-admin/tree/main/tests/test-account-assignment

I was wondering if any thought had been given to this kind of use case? Where essentially one test config may be dependent on another, and how to pass values from a dependency to another config? I see some notion of ordering execution of test configs using [`modules` in the `run` block](https://developer.hashicorp.com/terraform/language/v1.6.x/tests#modules), but it doesn't cover how to retrieve values from state in the earlier config?

### Attempted Solutions

n/a

### Proposal

None yet.

**Comment by liamcervante** [comment]
Hi @lorengordon, thanks for the feedback again. Really do appreciate it!

You can refer to outputs from previous modules using the `run.run_name.output_name` syntax both within the `variables` and `assert` blocks. For your use case, you'll just need to make sure the data you need is packaged up as outputs by the modules executed by your earlier run blocks.

This is mentioned in the beta documentation: https://developer.hashicorp.com/terraform/language/v1.6.x/tests#variable-references. I'm gonna share this issue with the docs team and we'll see if we can make this clearer and/or easier to discover. I think the feature does answer your use-case so I've tagged this as a documentation issue rather than an enhancement request.

**Comment by lorengordon** [comment]
@liamcervante Oh, that's interesting. Yes, I missed that feature in the docs. Thanks for pointing it out! 

I guess that means we would need to refactor our test configs to create variables for values we currently get from `terraform_remote_state`? I wonder if others might also prefer an integration that works with remote state? Is that something you would consider as a feature?

**Comment by liamcervante** [comment]
Yes, looking at the test that you have there to keep it in approximately the same format you would need define everything you need to share as outputs and variables and then link them together.

Somewhere in the docs we have a callout that we're looking for use cases for more in-depth state management and this is an interesting idea so I've made a note of it and will chat to our product team about it. If there is traction then realistically this is something that will arrive in `v1.7` rather than the upcoming `v1.6` release.

With the new testing framework I do think we had quite a different idea about how the testing would work compared to what you currently have. So I think if you wanted to switch (and I hope you do!) I'd recommend a larger refactor that just tweaking the input variables and output. Potentially your Terraform test file just looks like this:

```hcl
# test-account-assignment.tftest.hcl

run "prereq" {
  module {
    source = "./prereq"
  }
}

run "test_permission_set" {
  module {
    source = "../modules/permission-set"
  }

  variables {
    permission_set = {
      name        = "TARDIGRADE_TEST_${run.prereq.id}"
      description = "Test permission set - ${run.prereq.id}"
      managed_policy_attachments = [
        {
          policy_name = "ReadOnlyAccess"
        },
      ]
    }
  }
}

run "test_account_assignment" {
  module {
    source = "../modules/account-assignment"
  }

  variables {
    account_assignment = {
      principal_name = "AWS_P3_TARDIGRADE_POWERUSERS"
      principal_type = "GROUP"
      target_id      = run.prereq.account_id

      # It is not supported to use `permission_set_name` in this scenario. When the
      # permission set is created in the same config, the `permission_set_arn` must
      # be used instead. If you use `permission_set_name`, you will get an error.
      permission_set_arn = run.test_permission_set.permission_set.arn
    }
  }
}
```

You just have everything that was defined as a `local` previously now defined as an `output` from your `prereq` module (including the `aws_caller_identity`). With this approach you get rid completely of your intermediary testing configuration, and the remote state.

**Comment by lorengordon** [comment]
Oh wow, thanks @liamcervante! I totally was not expecting you to write an actual test config, based on our existing implementation. :heart:

One thing we like about the "wrapper" test configs we have, is that they also serve as an example for how to invoke the module(s) from a root module, for different use cases. So, I think we'd like to keep that. But, very impressed with the functionality you all have thought of for the `test` command. Really looking forward to using it, and we probably will refactor what we have a little bit to accommodate its expectations and features.

**Comment by liamcervante** [comment]
I'm going to close this issue without changing the documentation, I've looked through the docs we have and I can't find anywhere better to raise this feature without it being out of place.

Since, this issue was filed we have added more examples of tests throughout the global Hashicorp documentation, including a new tutorial that highlights this as a feature so hopefully these additional examples do enough to raise awareness.
