### ISSUE TITLE
Rendering template with '@' not functioning

### ISSUE THREAD

**Issue by henrynn** [hashicorp/terraform#33845]
### Terraform Version

```shell
Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.9.0
+ provider registry.terraform.io/hashicorp/azurerm v3.71.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: failed to render : <template_file>:95,26-27: Invalid character; This character is not used within the language., and 1 other diagnostic(s)
│
│   with data.template_file.nginx_reverse_proxy_script,
│   on data.tf line 1, in data "template_file" "nginx_reverse_proxy_script":
│    1: data "template_file" "nginx_reverse_proxy_script" {

### Expected Behavior

The string "${words[@]}" looks like an HCL interpolation, so terraform attempts to parse it as such, and encounters the invalid @ character.
for word in "$${words[@]}"; do
      xxxxx
done

### Actual Behavior

The string "${words[@]}" looks like an HCL interpolation, so terraform attempts to parse it as such, and encounters the invalid @ character.
for word in "$${words[@]}"; do
      xxxxx
done

### Steps to Reproduce

1. terraform init
2. terraform plan -out main.tfplan

**Comment by apparentlymart** [comment]
Hi @henrynn! Thanks for this feedback.

Unfortunately I'm not sure I understand what you are reporting. As far as I can tell you've written the same text under both "Expected Behavior" and "Actual Behavior", which suggests that Terraform is already behaving the way you expected, but I'm sure that's not what you intended to communicate.

It would also help to include a simplified version of the configuration you're working with that illustrates the problem -- and, in this case, also the template it's referring to -- so we can try to reproduce the bug for ourselves and thus determine whether we've fixed it.

Thanks!

**Comment by crw** [comment]
I am cleaning up old issues. As this issue has not received a response to the previous comment, I shall close this issue. Thanks!
