### ISSUE TITLE
Terraform Cloud Web UI "Start new run" run type selector does not fit onscreen and does not scroll

### ISSUE THREAD

**Issue by tanerjn** [hashicorp/terraform#33874]
### Terraform Version

```shell
On a Chrome browser and Iphone(Safari) the UI does not scroll down properly to chose destroy. I have to destroy resources from settings and queue destroy plan by forcing.

How to reproduce: 

From workspace choose new run
And the popped up window will not allow to scroll.
```

### Use Cases

I've tried on Chrome and Safari.

### Attempted Solutions

I believe it is a frontend issue, though not sure.

### Proposal

Scrollable window.

### References

<img width="700" alt="Screen Shot 2023-09-11 at 23 33 51" src="https://github.com/hashicorp/terraform/assets/25350481/a67a077c-66f0-4bef-b0e4-8eda342aefe9">

**Comment by apparentlymart** [comment]
Hi @tanerjn! Thanks for reporting this.

This repository is for the `terraform` CLI tool rather than for Terraform Cloud's web UI, and so folks who work on the web UI may not see this issue. I would suggest also sending a report to [HashiCorp Support](https://support.hashicorp.com/) since that is the way the Terraform Cloud teams typically expect to receive feedback like this; the support team has an internal process for passing feedback on to these teams.

**Comment by crw** [comment]
Hi @tanerjn, per Martin's comment above, please report this through [HashiCorp Support](https://support.hashicorp.com/). Thanks!
