### ISSUE TITLE
Latest github release doesn't match developer.hashicorp.com

### ISSUE THREAD

**Issue by CoryManson** [hashicorp/terraform#33887]
### Terraform Version

```shell
1.4.7
```

### Affected Pages

https://github.com/hashicorp/terraform/releases

https://developer.hashicorp.com/terraform/downloads

### What is the docs issue?

Github latest release is `1.4.7`, which appears inconsistent as last week the latest release was `1.5.7`.

https://developer.hashicorp.com/terraform/downloads is showing `1.5.7` as the latest release at time of writing.

### Proposal

Assuming the latest 1.4.7 release number was a mistake, should it have been 1.5.8?

**Comment by bflad** [comment]
Hi @CoryManson 👋 Thank you for raising this issue and sorry for the trouble. Terraform 1.5.7 is indeed the "latest" release, as in the highest release number of the stable 1.5.x series. There were 1.3.x and 1.4.x releases yesterday to resolve a specific state compatibility issue with those older versions. By default, GitHub Releases treats new releases based on time rather than based on version based. I'm double checking internally to ensure it would be okay to mark 1.5.7 as latest again and ensure that the release process includes an extra step to either automatically prevent this or manually fix it post-release in this situation. Thank you again for reporting this and your patience.

**Comment by bflad** [comment]
The 1.5.7 release in GitHub has been updated to be latest again. Thank you.
