### ISSUE TITLE
Correction to Source Address Section under provider documentation

### ISSUE THREAD

**Issue by mrpavan** [hashicorp/terraform#33911]
### Terraform Version

```shell
Terraform v1.5.7
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/providers/requirements#source-addresses

### What is the docs issue?

Placement of / is before the bracket in <HOSTNAME> portion

--- extract from documentation page ---

Source addresses consist of three parts delimited by slashes (/), as follows:

`[<HOSTNAME>/]<NAMESPACE>/<TYPE>`

### Proposal

*Proposed change is to correct the placement after the brackets enclosing <HOSTNAME> as below*

`[<HOSTNAME>]/<NAMESPACE>/<TYPE>`

**Comment by apparentlymart** [comment]
Hi @mrpavan,

The intent of this documentation is to describe two possible source address formats:

- `NAMESPACE/TYPE`
- `HOSTNAME/NAMESPACE/TYPE`

There is no form that is just `/NAMESPACE/TYPE`, so the slash is included in the brackets to indicate that it should be present only when the `HOSTNAME` portion is present.

With that said, I do think it would be clearer to just list the two possibilities directly as I did above, rather than using an unexplained shorthand as the page currently does. I agree that the current presentation is unnecessarily confusing.

Thanks for reporting this!

**Comment by mrpavan** [comment]
Hi @apparentlymart 

Thanks for quick comment. Yes it looks bit confusing as default hostname will point to registry.terraform.io however if we replace that in-place it looks like [registry.terraform.io/]NAMESPACE/TYPE and user might be confused weather to omit brackets or no unless he starts looking at other references to hostnames especially when other parts Namespace and Type having no such brackets. 

Thanks,
Pavan

**Comment by mrpavan** [comment]
🙌🏻 Thank you for suggesting necessary changes, appreciate your support
