### ISSUE TITLE
Discrepancy in behavior between Windows and Linux (Ubuntu) systems in a pipeline. While on Windows, resources are correctly destroyed and recreated upon execution, on Linux, the 'destroy' operation fails to properly eliminate resources, subsequently causing issues during resource creation.

### ISSUE THREAD

**Issue by jtsato** [hashicorp/terraform#33936]
### Terraform Version

```shell
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.83.0

Terraform v1.5.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v4.83.0
```

### Terraform Configuration Files

```terraform
[...terraform config...](https://github.com/jtsato/properties-api-terraform)
```

### Debug Output

Terraform on windows machine when infra already exists
https://gist.githubusercontent.com/jtsato/7e11b3a2ab44416d35572a406fd44a24/raw/627db3832b532ec1591b0584779d8a827bf6b770/terraform-win-second-time

Terraform on ubuntu machine when infra already exists (First Time)
https://gist.githubusercontent.com/jtsato/7917ea46b9d5a7cf57363d9568effd30/raw/b5c5d3345c32fc73fbd703f1548cb4c7fe998615/terraform-ubuntu-first-time

Terraform on ubuntu machine when infra already exists (Second Time)
https://gist.githubusercontent.com/jtsato/3ad5ef6f0a1372efa696833b25669d98/raw/f2a5938c3f9a9f03a80a33844a49c5572b6562ca/terraform-ubuntu-second-time

### Expected Behavior

I expected that every time the pipeline was executed, all resources would be destroyed and recreated.

### Actual Behavior

However, this only happens on Windows; on Linux (Ubuntu), when the 'destroy' operation is executed, resources are not properly destroyed, subsequently leading to failures during the creation process."

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`
3. `terraform providers lock \
          -platform=windows_amd64 \
          -platform=darwin_amd64 \
          -platform=linux_amd64 \
          -platform=darwin_arm64 \
          -platform=linux_arm64`
4. `terraform destroy -auto-approve -var-file=secrets.tfvars`
5. `terraform refresh -var-file=secrets.tfvars`
6. `terraform state list`
7. `terraform plan -out=tfplan.out -var-file=secrets.tfvars`
8. `terraform apply -auto-approve tfplan.out`

### Additional Context

Windows
https://github.com/jtsato/properties-api-terraform/actions/runs/6291207753
https://github.com/jtsato/properties-api-terraform/actions/runs/6291261658

Ubuntu 
https://github.com/jtsato/properties-api-terraform/actions/runs/6291287507
https://github.com/jtsato/properties-api-terraform/actions/runs/6291298492

Google Cloud Service Account Permissions:

- Artifact Registry Administrator
- Cloud Build Editor
- Cloud Functions Admin
- Cloud Run Admin
- Cloud Run Service Agent
- Pub/Sub Admin
- Role Administrator
- Secret Manager Admin
- Service Account Admin
- Service Usage Admin
- Storage Admin

The artifact is in the docker hub:
https://hub.docker.com/layers/jtsato/properties-api/v1.0.0-230923121/images/sha256-8cb1885c451aa568e3a994a925f1dcf9e7ec039cd97ed7d1bc09436c7b5d256a?context=repo

The environment variable and the secrets are in the github and they are inject when the pipeline runs.

**Comment by apparentlymart** [comment]
Hi @jtsato! I'm sorry things aren't working as you expected.

Unfortunately there's a lot going on here, including a bunch of custom automation code that I'm not familiar with, so I'm not really sure how best to start debugging this.

One thing that isn't clear to me is how exactly you are preserving state from one run to the next. I don't see any `backend` block in your configuration to configure remote state, and I don't see any steps in your workflows to save a state snapshot after the run is complete and retrieve it next time.

I'm interested in this because the first idea that comes to my mind thinking about what could cause this behavior is if the second run didn't have access to the state snapshot created by the first. In that case, each Terraform run will think it is starting with an empty world and so needs to create everything declared in the configuration.

However, if that were true then I would expect the same behavior regardless of which platform it runs on, so I assume that cannot be the entire story. Can you say more about how you're preserving state snapshots from one run to the next?

**Comment by jtsato** [comment]
Hello @apparentlymart, thank you for the response.

I did not preserve state snapshots because I wasn't aware of that.

After applying your suggestions, I had to manually destroy everything, and after three consecutive executions, it seems to be working.

![image](https://github.com/hashicorp/terraform/assets/28993739/533ec234-40f0-49d2-8326-9625f1a1dbbd)

Thank you for all the assistance.

I really appreciate your help in resolving the issue.
