### ISSUE TITLE
TransitiveReductionTransformer is reducing graphs too aggressively

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#3394]
As I found out in https://github.com/hashicorp/terraform/issues/2892 I think the reduction is a bit too aggressive.

Graph before reduction (effectively I just removed `&TransitiveReductionTransformer{},`):
![graph-after-reduction](https://cloud.githubusercontent.com/assets/287584/10255224/cfe1a042-68fd-11e5-84ba-9b633b0cca2e.png)

After reduction:

![graph-before-change](https://cloud.githubusercontent.com/assets/287584/10255214/bd3ba1ae-68fd-11e5-9d21-7bc97ae3cf56.png)

I don't call myself an expert in graph theory, but I don't think it's equivalent graph.

**Comment by mitchellh** [comment]
Going to close this since this hasn't cropped up again. If we can find a repro for this though I'll take a look! Transitive reduction could definintely have a bug but I think we'd hear about it pretty loudly. It is well tested though so if we find a repro we can easily codify as a test case and fix.
