### ISSUE TITLE
The s3 backend does not respect the NO_PROXY variable

### ISSUE THREAD

**Issue by mnival** [hashicorp/terraform#33987]
### Terraform Version

```shell
Terraform v1.6.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    bucket="tf-state-test"
    region="eu-central-1"
    key="test/test.tfstate"
  }
}
```

### Debug Output

https://gist.github.com/mnival/cb0857de9b72e2020bdc46b3ae00fbba

### Expected Behavior

For requests to http://169.254.169.254/, Terraform should not use the proxy because I have the following NO_PROXY value:
NO_PROXY=169.254.169.254
Below is the result with Curl which uses the HTTP_PROXY, HTTPS_PROXY and NO_PROXY variables:
```bash
$ curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" -v -o /dev/null
* Uses proxy env variable NO_PROXY == '169.254.169.254'
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> PUT /latest/api/token HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/8.0.1
> Accept: */*
> X-aws-ec2-metadata-token-ttl-seconds: 21600
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 56
< Content-Type: text/plain
< Date: Thu, 05 Oct 2023 09:40:58 GMT
< X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21600
< Connection: close
< Server: EC2ws
<
{ [56 bytes data]
* Closing connection 0
```

### Actual Behavior

Terraform only uses HTTP_PROXY and HTTPS_PROXY variables but not NO_PROXY. So some requests use a proxy even though they are only available when local and therefore without a proxy

### Steps to Reproduce

`terraform init`

### Additional Context

```bash
export HTTP_PROXY="http://proxy:3128"
export HTTP_PROXY="http://proxy:3128"
export NO_PROXY="169.254.169.254"
```

### References

- #33748

**Comment by DerPauli** [comment]
We encounter this problem as well, but the other way around. Our atlantis server uses Terraform v1.6.0 and can't refresh the state from S3 anymore through our corporate proxy.
The atlantis output for `terraform init` looks like:
```
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, failed to retrieve
│ credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded
│ maximum number of attempts, 3, https response error StatusCode: 0,
│ RequestID: , request send failed, Post
│ "https://sts.eu-central-1.amazonaws.com/": proxyconnect tcp: dial tcp :0:
│ connect: connection refused
│ 
```

**Comment by StevenKGER** [comment]
We encounter this problem as well.

It seems like it's due to #33765 and there due to https://github.com/hashicorp/aws-sdk-go-base/pull/81.

![image](https://github.com/hashicorp/terraform/assets/22663042/37dc9788-2f21-4956-8f21-01bba0a0200e)
[This function returns always the same url - therefore ignoring `NO_PROXY`.](https://github.com/hashicorp/aws-sdk-go-base/blob/d023bdce9acc9b79737d608de0e5bcdb0b1b7e96/internal/config/config.go#L114) 

An issue should be raised in [aws-sdk-go-base](https://github.com/hashicorp/aws-sdk-go-base) to support `NO_PROXY` settings and **after** it has been changed here, we can add `NO_PROXY` again. Otherwise reverting the changes which have been added with the minor update 1.6.0 can recover the old working state.

**Comment by joaquin386** [comment]
Mmmm we have to stuck our terraform to 1.5.2 because of this error.

**Comment by wernerwws** [comment]
Is there any workaround?

**Comment by joaquin386** [comment]
@wernerwws 1.5.2 will work 1.6.X will not
