### ISSUE TITLE
GIT_SSH_COMMAND env var ignored when downloading modules - Host key verification failed

### ISSUE THREAD

**Issue by StephenKing** [hashicorp/terraform#33985]
### Terraform Version

```shell
1.6.0
```

### Terraform Configuration Files

```terraform
module "this" {
  source = "git@github.com:org/tf-module?ref=1.0.1"
}
```

### Debug Output

N/A, sorry

### Expected Behavior

When using an SSH key on GitHub and the following configuration, download of modules should continue to work.

```
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
```

### Actual Behavior

Terraform fails downloading modules with error:

```
 ╷
 │ Error: Failed to download module
 │ 
 │   on file.tf line 11:
 │   11: module "this" {
 │ 
 │ Could not download module "this" (file.tf:11)
 │ source code from
 │ "git::ssh://git@github.com/org/tf-module.git?ref=1.0.1":
 │ error downloading
 │ 'ssh://git@github.com/org/tf-module.git?ref=1.0.1':
 │ /usr/bin/git exited with 128: Cloning into
 │ '.terraform/modules/this'...
 │ Host key verification failed.
 │ fatal: Could not read from remote repository.
 │ 
 │ Please make sure you have the correct access rights
 │ and the repository exists.
 
 ```

### Steps to Reproduce

```
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"

terraform init
```

### Additional Context

Works with 1.5.x

### References

- #28968

**Comment by xsaero00** [comment]
Thanks for creating the issue. I'll follow it for updates.

**Comment by crw** [comment]
Thanks for filing this issue! I am labeling `upstream` as I presume the issue is actually in go-getter, per: https://github.com/hashicorp/go-getter/pull/300.

**Comment by apparentlymart** [comment]
I'm not super familiar with the upstream go-getter git setup, but after staring at the diff in hashicorp/go-getter#300 for a while it looks to me that:

- Before this change, it would always remove `GIT_SSH_COMMAND` from the inherited environment, but then would always append it back again at the end. It looks like the old version did have a bug when `GIT_SSH_COMMAND` wasn't set _at all_ -- it would always set it, thereby overriding whatever was configured in the user's git configuration. But if `GIT_SSH_COMMAND` was intentionally set then it would preserve it.
- After this change, it now removes `GIT_SSH_COMMAND` from the inherited environment and only adds it back if an SSH key is provided. This means that for any git source address that doesn't include an explicit SSH key (which is typical for Terraform; that option is mainly there for other go-getter callers) go-getter is effectively stripping out any existing `GIT_SSH_COMMAND` environment variable.

That interpretation seems consistent with the original report here, since I see it includes an explicit `GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"` which go-getter now silently removes before launching git.

If I'm right in this assessment, I think in the meantime it would be possible to work around it by setting that setting in a git configuration file instead of via the environment. The original purpose of that change seems to have been to make it _possible_ to use the configuration file instead of the environment, but it has instead made it _mandatory_ to use the configuration file.

```shell
git config core.sshCommand 'ssh -o StrictHostKeyChecking=no' 
```

Of course, that will disable strict host key checking for all use of `git` on your system, so if you use this temporary workaround please take care if you use `git` for other purposes on your system; you may be vulnerable to "man-in-the-middle" attacks.

Since go-getter is a shared dependency across many different applications I expect we'll need to negotiate a little to make a change there, but it does seem like it should be possible to implement what I expect was intended for that PR in the first place: to leave `GIT_SSH_COMMAND` _totally unchanged_ if there is no SSH key, rather than removing it entirely.

**Comment by StephenKing** [comment]
Thanks @apparentlymart for your thorough analysis. Makes sense to me what you write.

**Comment by ryandiamond23** [comment]
Seeing the same on 1.6.0, pinning Docker image to 1.5.7 doesn’t reproduce so seems to be an issue with the newest version.
