### ISSUE TITLE
Sensitive values should be allowed in conditionals in `for_each`

### ISSUE THREAD

**Issue by joshua-hancox** [hashicorp/terraform#34061]
### Terraform Version

```shell
Terraform v1.6.1
on linux_amd64
```

### Terraform Configuration Files

```terraform
resource "tls_private_key" "this" {

  for_each = var.ssh_key == null ? { "key" = {} } : {}

  algorithm = "RSA"
  rsa_bits  = 4096
}

```

### Debug Output

```
Error: Invalid for_each argument
  on .terraform/modules/aks_primary/resource-tls.tf line 7, in resource "tls_private_key" "this":
   7:   for_each = var.ssh_key == null ? { "key" = {} } : {}
    ├────────────────
    │ var.ssh_key has a sensitive value
Sensitive values, or values derived from sensitive values, cannot be used
as for_each arguments. If used, the sensitive value could be exposed as a
resource instance key.
```

### Expected Behavior

Terraform understands that the value `var.ssh_key` is only being used to determine which object to loop over, not as a key itself.

### Actual Behavior

Terraform treats any sensitive value in a `for_each` statement as unacceptable.

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

This was not an issue with terraform `1.5.x`, but I guess there wasn't a check there for sensitive values in the for_each keys at all?

**Comment by apparentlymart** [comment]
Hi @joshua-hancox! Thanks for reporting this.

Terraform is behaving as designed here, because as far as Terraform knows the "nullness" of `var.ssh_key` might be part of what is sensitive about the value, and allowing what you tried here would disclose whether the value was null to anyone who can see the plan output, and can thus know whether there were zero or one instances of this resource.

In your case you don't consider the "nullness" of this value to be a sensitive characteristic, and you can tell Terraform that by declaring the result of the predicate expression as "non-sensitive":

```hcl
  for_each = nonsensitive(var.ssh_key == null) ? { "key" = {} } : {}
```

That extra assertion tells Terraform that it's okay to disclose whether this value is null, even though the value is otherwise still sensitive. Terraform should therefore infer that the result of this conditional isn't sensitive either, because deciding it did not depend on any sensitive information.

The modelling of sensitive values is intentionally conservative by default on the assumption that it's better to return an error than to accidentally disclose something sensitive. The `nonsensitive` function allows you to hint to Terraform when it is being too conservative, based on your own knowledge of what is important to conceal vs. okay to show.

Would the above solution work for you?

**Comment by joshua-hancox** [comment]
Sure @apparentlymart, I'll update my module. Thanks.
