### ISSUE TITLE
terraform test parses all global variables instead of just what it needs

### ISSUE THREAD

**Issue by CodeBehind** [hashicorp/terraform#34070]
### Terraform Version

```shell
Terraform v1.6.1
```

### Terraform Configuration Files

```terraform
  variable "myvar_a" {
      type = string
  }
  
  output "my_output" {
      value = var.myvar_a
  }
```

### Debug Output

```
│ Error: Variables not allowed
│
│   on <value for var.myvar_b> line 1:
│   (source code not available)
│
│ Variables may not be used here.
```

### Expected Behavior

test.tftest.hcl... in progress

run "run"... pass
test.tftest.hcl... tearing down
test.tftest.hcl... pass

Success! 1 passed, 0 failed.

### Actual Behavior

# Testing with 
Just add this as "test.tftest.hcl" to the root folder.
```hcl
  run "run" {
      command = plan 
  
      assert {
          condition = length(var.myvar_a) > 1 
          error_message = "Is not greater than 1"
      }
  }
```

When i run a "terraform plan" or a "terraform test " while having "TF_VAR_myvar_a" set in my environment, both commands are doing the same (they succeed like expected). 

When i now add TF_VAR_myvar_b (it's not declared in my main.tf file) terraform plan ignores the variable and still succeeds, while terraform test is failing with the mentioned debug output. 

I think terraform test should ignore unused variables as terraform plan does, due to having multiple projects with different variables and secrets set via environment variables. 

### Steps to Reproduce

1. Create main.tf with the content of the terraform configuration.
2. Create test.tftest.hcl with the content of the tftest.hcl configuration from above.
3. Add TF_VAR_myvar_a to your environment variables with any text
4. Run terraform init
5. Run terraform plan 
6. Run terraform test 
7. Now add TF_VAR_myvar_b to your environment with any text 
8. Run terraform plan 
9. Run terraform test <--- this produces the error

**Comment by liamcervante** [comment]
Hi @CodeBehind, thanks for filing this.

The terraform test framework is different to the normal plan and apply configuration in that it can reference dynamic variables that aren't declared upfront in a configuration file. This means that you could change your condition to something like `length(var.myvar_a) > length(var.myvar_b)` and then provide the value for `myvar_b` directly in the test file, or via the command line / environment variables, without needing to declare it within a configuration file.

That's the explanation as to why the behaviour is different between `terraform test` and `terraform plan` - the plan command is only processing the variables that are explicitly declared while the test command is allowing dynamic definitions.

The error you are seeing is due to the way Terraform is having to parse those variables that have no definition in any configuration. As there is no configuration that declares an expected type, Terraform is having to deduce the type from the raw value. To do this, it uses the HCL encoding for types. For example:

* `export TF_VAR_myvar_b=myvalue`
  * The concrete value for this is simply `myvalue` which HCL interprets as a variable reference as if you were writing an attribute value in a Terraform configuration file.
* `export TF_VAR_myvar_b='"myvalue"'`
  * The concrete value for this is `"myvalue"` including the quotation marks, which HCL interprets as a string.

The error you see is the first case in which Terraform says it cannot interpret the value as no variable references are allowed at that point. I think your example would work if you declared `myvar_b` using the syntax in the second case.

Hopefully that all makes sense. I will say that the error message isn't very good - so I'm gonna leave this open and we'll see if we can improve that error message to make the fix / workaroud clearer.

**Comment by liamcervante** [comment]
I had a quick look at improving the error message here, but I actually noticed that it shouldn't be too difficult to add in some kind of "relevant variable" metric so that `terraform test` does actually only process the variables it needs. That would bring the behaviour more closely in line with `terraform plan` and `terraform apply` and would also fix the error reported here (as `terraform test` wouldn't attempt to process the variable so it wouldn't attempt to parse it at all).

**Comment by CodeBehind** [comment]
Hi @liamcervante, 

thank you very much for your detailed explanation. 
I have tested your workaround, sadly it is not working. 

I wrote this in my .env file: 

```
TF_VAR_myvar_a="TestValue"
TF_VAR_myvar_b="TestValue"
```

The error stays the same.
For the moment i can filter the unneeded variables out with a little script of my own but i'm pretty sure your Idea of bringing test closer to plan and apply would be the best solution for this.
