### ISSUE TITLE
Reopen #24677

### ISSUE THREAD

**Issue by itay-grudev** [hashicorp/terraform#34075]
### Terraform Version

```shell
1.6.1
"hashicorp/azurerm" = "3.75"
```

### Terraform Configuration Files

```tf
resource "azurerm_storage_account" "terraform_storage" {
  name = var.storage_account_name
  resource_group_name = var.rg_name
  location = var.region
  account_tier = "Standard"
  account_replication_type = "GRS"
  account_kind = "Storage"
  
  network_rules {
  default_action = "Deny"
  virtual_network_subnet_ids = [data.azurerm_subnet.publicsubnet.id]
  }
}
resource "azurerm_storage_container" "mycontainer" {
  name = "walfiles"
  storage_account_name = azurerm_storage_account.terraform_storage.name
  container_access_type = "private"
}
```

### Debug Output

```
Error: retrieving Container "walfiles" (Account "storagename" / Resource Group "rgname"): containers.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.
```

### Expected Behavior

It should create a container.

### Actual Behavior

An error that doesn't make sense as the user has all the necessary permissions and is able to create said resources otherwise.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Could you please reopen #24677. I have an identical issue two years later, all of the permissions to execute the operation and latest versions of terraform and `hashicorp/azurerm`.

### References

- #24677

**Comment by liamcervante** [comment]
Hi @itay-grudev, this looks like an issue with the Azure provider specifically rather than Terraform Core. The azure provider is managed in a separate repository: https://github.com/hashicorp/terraform-provider-azurerm

I can see we have a few issues open there which seem related to this already:

- https://github.com/hashicorp/terraform-provider-azurerm/issues/17936
- https://github.com/hashicorp/terraform-provider-azurerm/issues/2977 

You can follow those issues for updates on this from the Azure team, or file a new issue there if you think your issue is different from those listed.

Thanks for raising this!
