### ISSUE TITLE
SIGSEGV when saving remote state in Terraform 1.6.0-dev and up

### ISSUE THREAD

**Issue by dradtke** [hashicorp/terraform#34094]
### Terraform Version

```shell
Terraform v1.6.1
on linux_amd64
```

### Terraform Configuration Files

N/A

### Debug Output

Can be provided if needed, but I think the stack trace should be enough.

### Expected Behavior

The apply should have completed successfully.

### Actual Behavior

The apply failed with

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11e9936]

goroutine 486 [running]:
github.com/hashicorp/go-tfe.(*stateVersions).Upload.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/go-tfe@v1.34.0/state_version.go:294 +0xb6
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 26
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96
```

### Steps to Reproduce

Set up a Terraform project with an Artifactory backend, and run

```sh
$ terraform apply
```

### Additional Context

We are using Artifactory internally to hold our remote state, and to host some custom internal providers.

However, we don't believe these providers are the issue, since the stack trace does not reference them, and our changes are still being applied successfully even when Terraform crashes; it's only the remote state that does not get saved.

**Comment by radditude** [comment]
Thanks for reporting! This looks to be a known issue around handling upstream errors from the server when uploading state using the `remote` or `cloud` backends. That is to say, it's likely that Artifactory returned a non-success error code when saving state, which unfortunately resulted in this panic rather than a more helpful error. 

The fix has already been addressed in https://github.com/hashicorp/terraform/pull/34074 and should be released in v1.6.2.
