### ISSUE TITLE
Dependency Managment with Multiple datasources which depend on each other

### ISSUE THREAD

**Issue by sass1997** [hashicorp/terraform#34126]
### Terraform Version

```shell
1.5.1
```

### Terraform Configuration Files

module a
```terraform
resource "helm_release" "example" {
  name       = "my-local-chart"
  chart      = "./charts/example"
}
```

module b
```terraform
data "gitlab_repository_tree" "components_list" {
  project   = "/test/test"
  ref       = "main"
  path      = "components"
  recursive = true
}

data "gitlab_repository_file" "application_yaml" {
  depends_on = [data.gitlab_repository_tree.components_list]
  count = length(try(local.components_tree, []))
  project   = data.gitlab_repository_tree.components_list.project
  ref       = data.gitlab_repository_tree.components_list.ref
  file_path = local.components_tree[count.index].path
}

resource "gitlab_deploy_key_enable" "shared_projects" {
  count      = length(try(distinct(local.components_list), []))
  project    = local.components_list[count.index]
  key_id     = "123"
}


locals {
components_tree = [for component in data.gitlab_repository_tree.components_list : component if component.name == "readme.ml"]
components_list = [for component in data.gitlab_repository_file.application_yaml : base64decode(component.content)]

}
```

main.tf

```terraform
module "install" {
  source = "./modules/a"
}

module "config" {
  depends_on = [
    module.install
  ]
  source = "./modules/b"
}
```

### Debug Output

not possible

### Expected Behavior

I have deleted a resource in module A and now I get the error: the "count" value depends on resource attributes that cannot be determined until apply.

If I readd the resource in module A nothing is complaining anymore.

I have made mutliple iterations of development until I had the state postet in Configuration Files. In my opinio since I have the try included it shouldn't throw any errors

### Actual Behavior

Plan results in error

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply
4. "Delete the resouce in module a"
5. terraform init
6. terraform plan -> error happens

**Comment by jbardin** [comment]
Hi @sass1997,

You have added `depends_on` to the `config` module, which means everything in that module depends on all changes in the install module, so the data sources cannot be read until that first module's changes have been applied. Changes would ned to be applied in the same manner as the initial apply, which could be done using `-target`. If you have multiple layers of infrastructure, it is usually better to manage those layers from separate configuration.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by sass1997** [comment]
Do you have any recommandations how I could extend the depends on so that data sources aren't affected and it's guaranteed on the init installation everything in module A is applied before going to the module b?

**Comment by jbardin** [comment]
Are `gitlab_repository_file` and `gitlab_repository_tree` some of the resources created in the first module? If that's the case you should not be representing the same resource via a data source and a managed resource in the same configuration. The resources created by the first module should be exposed via outputs, and consumed via inputs in the second module (this is the general pattern even if these are not created in the first module.

If that's not the case, it would be better to create a more complete example and start a new topic in the discussion forums.

As for using `try`, that doesn't do anything, because dependencies are determined via static references, not at runtime, and your `depends_on` statically declares that _everything_ in module b always depends on _all_ changes in module a.

Thanks!
