### ISSUE TITLE
Import fails for AWS security groups in non-default region

### ISSUE THREAD

**Issue by cfiske** [hashicorp/terraform#34131]
### Terraform Version

```shell
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.8.0
```

### Terraform Configuration Files

```
provider "aws" {
  region = "us-east-1"
}

provider "aws" {
  alias  = "use2"
  region = "us-east-2"
}

module "my_us_east_1_vpc" {
  source = "./modules/vpc"

  region         = "us-east-1"
  vpc_cidr       = cidrsubnet(var.cidr, 3, 1)
}

module "my_us_east_2_vpc" {
  source = "./modules/vpc"

  providers = {
    aws = aws.use2
  }

  region         = "us-east-2"
  vpc_cidr       = cidrsubnet(var.cidr, 3, 4)
}

resource "aws_security_group" "my_sg" {
  for_each    = toset(keys(local.my_vpc_ids))
  name        = "my_sg"
  description = "Allow traffic"

  vpc_id = local.my_vpc_ids[each.value]
}
```

### Debug Output

https://gist.github.com/cfiske/8f0878ef87f0cb768fe532302bbb56b4

### Expected Behavior

Security group my_sg["us-east-2"] should have been imported.

### Actual Behavior

| Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to
│ "aws_security_group.my_sg[\"us-east-2\"]", the provider detected that no
│ object exists with the given id. Only pre-existing objects can be imported;
│ check that the id is correct and that it is associated with the provider's
│ configured region or endpoint, or use "terraform apply" to create a new
│ remote object for this resource.

### Steps to Reproduce

1. `terraform init`
2. `terraform import 'aws_security_group.my_sg["us-east-2"]' sg-0c5f*************3b`

### Additional Context

The SG ID does exist in us-east-2, as verified with
```
aws ec2 describe-security-groups --region us-east-2 --group-ids sg-0c5f************3b
```

This works fine importing `aws_security_group.my_sg["us-east-1"]` (and its respective SG ID) which is in the default provider region. For any non-default region it fails. I can't pass a `provider` to the security group resource, so I assume it is meant to be using the provider of the supplied `vpc_id`.

`terraform plan` and `terraform apply` correctly plan/create this security group in us-east-2.

I initially had an issue similar to #33905 but when I started looking at the debug logs it turns out the downstream security group is having this import failure.

**Comment by cfiske** [comment]
From the debug logs, it seems it's querying the SG ID against us-east-1 instead of us-east-2:

```
2023-10-24T18:31:10.381Z [DEBUG] provider.terraform-provider-aws_v5.8.0_x5: HTTP Request Sent: [trim] aws.service=EC2 [trim] @module=aws aws.operation=DescribeSecurityGroups aws.region=us-east-1 tf_resource_type=aws_security_group @caller=github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.32/logger.go:96 http.method=POST http.url=https://ec2.us-east-1.amazonaws.com/ net.peer.name=ec2.us-east-1.amazonaws.com tf_rpc=ReadResource http.flavor=1.1 http.request.body="Acti*********************oups&GroupId.1=sg-0c5f*********303b&Version=2016-11-15
```

**Comment by apparentlymart** [comment]
Hi @cfiske! Sorry this didn't work as you intended.

In the configuration you've shared, I see two provider configurations, with the addresses `aws` and `aws.use2`. You've used `aws` for `module.my_us_east_1_vpc` by implication, and you've used `aws.use2` for `module.my_us_east_2_vpc` by explicitly selecting it using the `providers` argument.

Your `resource "aws_security_group" "my_sg"` block does not include a `provider` argument and therefore it's implied to belong to the configuration named `aws`, which is the one associated with us-east-1.

With all of that said then, what Terraform did here seems to be correct: it tried to import the object using the provider that's (implicitly) associated with this resource block. If you want that resource to be managed by the other configuration then you'd need to declare that explicitly in a similar way as you did for the second `module` block, but this time using the singular `provider` because a resource has only one provider:

```hcl
resource "aws_security_group" "my_sg" {
  provider = aws.use2

  # ...
}
```

From context I guess what you want is to have a mixture of some security groups in `us-east-1` and some in `us-east-2`. If you want to do that then you'll need to write two separate `resource "aws_security_group"` blocks, each one selecting a different provider configuration, similar to what you did for the two `module` blocks.

**Comment by cfiske** [comment]
Thanks for the quick response and clarification. I ended up moving it into a module, since if I have to duplicate something I would prefer to duplicate module calls over resource definitions.

I did try passing a provider to the security group resource, but it failed. I likely just had the syntax wrong.
