### ISSUE TITLE
Terraform test: Evaluate validation of variables when creating test setup

### ISSUE THREAD

**Issue by bebold-jhr** [hashicorp/terraform#34189]
### Terraform Version

```shell
Terraform v1.6.2
on darwin_arm64
```

### Use Cases

I was checking out terraform test and one thing that would be very beneficial is having the test evaluate the variables using their original validations.
When I was writing tests I was able to create `variabes` blocks having any content although my variables  do have validation in place. So in order to guarantee valid test data and be able to test the validation blocks of a variable as well, it would be great if the tests would evaluate the injected input the exact same way the original code does.

### Attempted Solutions

-

### Proposal

I don't how it's implemented at the moment, but just passing the values to the original variables and using their validation evaluation sounds plausible to me.

**Comment by liamcervante** [comment]
Hi @bebold-jhr, can you provide some example configuration in which the variable validations are not being applied? All validations implemented in the configuration under test should be checked as part of the execution of the run block. If this is not happening then we have a bug rather than a feature request.

Thanks!

**Comment by bebold-jhr** [comment]
Hello @liamcervante,
when creating a minimal reproducible example, I realized that my condition was faulty. So basically terraform test already made me find an error in the implementation.
