### ISSUE TITLE
Making changes to dme_record don't seem to take effect

### ISSUE THREAD

**Issue by philp** [hashicorp/terraform#3420]
If I've already applied a `me_record` resource with `terraform apply`, and then make changes and run `terraform apply` again, the changes don't appear to have an effect.

I don't see any error messages. The output appears to indicate that everything has run fine, but I can see that changes haven't taken effect when looking in the DNS Made Easy control panel.

**Comment by benosman** [comment]
I'm having the same issues with dme_record, along with GH-9034 makes it pretty much unusable.

I'm having issues setting any kind of record with an empty name field. Name field is required so must be present.

### Terraform Version
Terraform v0.7.4

### Affected Resource(s)
- dme_record

### Terraform Configuration Files
```hcl

resource "dme_record" "a_record" {
  domainid = "${var.domainid}"
  name = "test"
  type = "A"
  value = "8.8.8.8"
  ttl = "600"
  gtdLocation = "DEFAULT"
}

```

### Debug Output
No errors

### Expected Behavior
Record should have been modified

### Actual Behavior
Success reported, but no changes made on dnsmadeeasy. 

Running again shows the same change being made, but still no modification at DME.

### Steps to Reproduce
1. `terraform apply`
2. modify name of record name ` name = "test2"`
3. `terraform apply`

### References

- GH-2241
- https://github.com/soniah/dnsmadeeasy/issues/3

**Comment by bdwyertech** [comment]
👍

**Comment by scumola** [comment]
This bug seems to have shown up again.  Adding and deleting work great.  Modifying a record looks successful, but actually no change is made.
