### ISSUE TITLE
 Requesting enable automate DNS Configuration for the VM

### ISSUE THREAD

**Issue by karim20230** [hashicorp/terraform#34229]
### Terraform Version

```shell
Terraform v1.5.7
```

### Description

 There is a challenge in automatically configuring DNS names for virtual machines (VMs) within the Terraform setup.  This feature is crucial for accessibility of the VMs.

### Current Behavior:

Currently, there is no automated way to configure DNS names for VMs, requiring manual intervention post-creation.

### Proposal

We expect a feature that allows for the automatic assignment and configuration of DNS names for VMs during their creation.

### Steps to Reproduce:

Provision a VM using Terraform.
Attempt to automatically configure a DNS name for the VM.

**Comment by liamcervante** [comment]
Hi @karim20230, thanks for filing this! Which provider are you using to create virtual machines at the moment? This repository is focused on Terraform core and the Terraform providers are managed separately and independently. I will close this issue here and you should reopen it directly with the provider you are using for VM management. Thanks!

**Comment by karim20230** [comment]
hey @liamcervante thanks, moved the issue  to the azure prov..
