### ISSUE TITLE
Remove dependency on git binary for terraform module fetching

### ISSUE THREAD

**Issue by alita1991** [hashicorp/terraform#34232]
### Terraform Version

```shell
1.6.3
```

### Use Cases

Currently, Terraform relies on the presence of the git binary for fetching modules. This creates a dependency that might not align with all user environments, leading to potential issues, especially in environments where git is not a standard tool or where users prefer alternative version control systems.

### Attempted Solutions

Tested HTTPS fetch, but it didn't work because the module usually depends on other modules that require git.

### Proposal

One solution to address this problem is by replacing the usage of git with a go-native implementation, like https://github.com/go-git/go-git, which is used in multiple projects already.

**Comment by apparentlymart** [comment]
Hi @alita1991! Thanks for reporting this.

We will not be able to move away from running the `git` CLI tool because existing users depend on various details of its behavior that are not necessarily replicated by other implementations, such as exactly how it runs `ssh` when cloning over SSH, exactly how it obtains credentials, etc. This behavior is protected by the Terraform v1.x compatibility promises.

If you wish to use a module that is published in a Git repository then having the `git` CLI tool installed is a requirement and unfortunately I don't see any viable path to removing that requirement.

If you do not wish to install `git` in the environment where you are running Terraform then I would suggest copying the modules you intend to use to a different location and depending on them from there instead. As you noted, that might also require creating local copies of indirect dependencies and then modifying your direct dependencies to access those indirect dependencies from another location.

**Comment by crw** [comment]
Thanks for your request @alita1991! Per @apparentlymart's comment, as this is the intended design and there is a work-around, I am going to close this issue. Thanks again for your feedback!
