### ISSUE TITLE
Represent the planned to import in TF plan output

### ISSUE THREAD

**Issue by chumvan** [hashicorp/terraform#34246]
### Terraform Version

```shell
Terraform v1.5.5
```

### Use Cases

The use case is to automate the infrastructure management using Terraform in the Azure DevOps pipeline. This results in a two-stage pipeline one for `terraform plan` and one for `terraform apply` where the later consumes the output from the first . When importing existing resources into the Terraform state, the Terraform plan command does not reflect these imported resources in the `out.plan` file. This becomes a challenge in automation workflows, particularly in CI/CD pipelines.
The goal is to achieve an integration of Terraform within automated workflows where the Terraform plan output accurately represents the current state of infrastructure, including newly imported resources.

### Attempted Solutions

We could get the resulted changes in the `out.plan` for most of the the Terraform commands, but not from the `import` as it is not presented.

### Proposal

This could be implemented as an additional flag in the Terraform plan command, like `--include-imports`, which when set to true, makes the plan output aware of any resources imported into the state since the last plan execution.

```hcl
terraform plan -out=out.plan --include-imports
```

**Comment by apparentlymart** [comment]
Hi @chumvan,

If you use [config-based import](https://developer.hashicorp.com/terraform/language/import) then the import information will be included in the plan.

I assume you are using the `terraform import` command instead, which is effectively making its own import-only plan and applying it all as a single operation, and so by the time it's finished all of the work is done and there's nothing left for the next `terraform plan` to propose.

It sounds like you might want to do importing as part of planning. If so, I'd suggest trying the configuration-driven import as I linked above.

If that approach isn't suitable, we've also previously considered allowing import operations to be specified on the command line when creating a plan, similar to how the `-replace` option allows forcing Terraform to replace something without editing the configuration. Importing is a more complex operation to describe in the command line since it requires two options, but a hypothetical example of how that might be designed would be:

```
terraform plan -import=resource_type.name=remote_id
```

I imagine the above as being a plannable equivalent of `terraform import resource_type.name remote_id`.

If the configuration-based approach isn't sufficient for your situation, I'd be interested to learn if this plan-options-based approach would be a better fit. It would also help to understand why the configuration-driven approach isn't suitable for your situation in case there's a design change we could make to _that_ to make it more suitable for your goal.

Thanks!

**Comment by chumvan** [comment]
Thanks for your reply, @apparentlymart.

I think I should have provided more context for our case. 

We are using the config-based import approach as you mentioned with the to-be-imported resources defined in the `import{}` block and then run `terraform plan` with that updated code. We could see from the to-be-imported resources in the log, something like this 
```
...
Plan: 3 to import, 0 to add, 0 to change, 0 to destroy.
```
However, our pipeline relies on the `out.plan` file from the `terraform plan` phase to proceed with further automated tasks, so the end-behaviors of the pipeline differ depending on for example if there are any changes or there are any imported resources. [here](https://developer.hashicorp.com/terraform/internals/json-format) is the official `out.plan` file format. We could parse JSON file to get almost all we needed in the `resource_changes` field. Correct me if we have missed something in here, but for now the output file does not contain the resources in the `import{}` blocks. If there is one, please point us toward it, if there is not yet, maybe this could be a promising proposal for the `terraform plan` command.

I hope this clarify somewhat the situation, and please let me know if there is more I can provide.

**Comment by apparentlymart** [comment]
Hi @chumvan! Thanks for the additional context.

The CLI UI produced by default with `terraform plan` is itself implemented in terms of the same data that `terraform show -json PLANFILE` produces, and so the fact that the main plan output is able to describe import actions suggests that there must be a representation of which objects are being imported in that data somewhere.

I'm not an expert on that part of Terraform so I'm not sure off the top of my head but I suspect this is a documentation omission rather than a functionality omission.

Hopefully one of my colleagues who was involved in the import implementation can give more details here when they see it, but for the moment I would suggest trying to create a plan which has a nonzero import count like you illustrated and then exporting it with `terraform show -json planfile`, and then search in the result for the resource type you were importing. I suspect you will find a representation of import metadata in there, in which case I think this bug can represent just fixing the missing documentation for those elements.

**Comment by kmoe** [comment]
Thanks for this. The documentation is indeed out of date and needs to be fixed. Here's an example of how resources being imported are represented in the plan file.

### Config

```hcl
resource "random_string" "foo" {
  length = 3
}

import {
  to = random_string.foo
  id = "foo"
}

resource "random_string" "bar" {
  length = 4
}
```

Here we're importing the resource `foo` and creating the resource `bar.` I've added both to show the differences in the `resource_changes` entries.

### Commands

```
$ terraform plan -out=tfplan
$ terraform show -json tfplan | jq
```

### Output

Irrelevant parts removed.

```json
{
  "format_version": "1.2",
  "terraform_version": "1.7.0-dev",
  "planned_values": {
    "root_module": {
      "resources": [
        {
          "address": "random_string.bar",
          "mode": "managed",
          "type": "random_string",
          "name": "bar",
          "provider_name": "registry.terraform.io/hashicorp/random",
          "schema_version": 2,
          "values": {
            "keepers": null,
            "length": 4,
            "lower": true,
            "min_lower": 0,
            "min_numeric": 0,
            "min_special": 0,
            "min_upper": 0,
            "number": true,
            "numeric": true,
            "override_special": null,
            "special": true,
            "upper": true
          },
          "sensitive_values": {}
        },
        {
          "address": "random_string.foo",
          "mode": "managed",
          "type": "random_string",
          "name": "foo",
          "provider_name": "registry.terraform.io/hashicorp/random",
          "schema_version": 2,
          "values": {
            "id": "foo",
            "keepers": null,
            "length": 3,
            "lower": true,
            "min_lower": 0,
            "min_numeric": 0,
            "min_special": 0,
            "min_upper": 0,
            "number": true,
            "numeric": true,
            "override_special": null,
            "result": "foo",
            "special": true,
            "upper": true
          },
          "sensitive_values": {}
        }
      ]
    }
  },
  "resource_changes": [
    {
      "address": "random_string.bar",
      "mode": "managed",
      "type": "random_string",
      "name": "bar",
      "provider_name": "registry.terraform.io/hashicorp/random",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "keepers": null,
          "length": 4,
          "lower": true,
          "min_lower": 0,
          "min_numeric": 0,
          "min_special": 0,
          "min_upper": 0,
          "number": true,
          "numeric": true,
          "override_special": null,
          "special": true,
          "upper": true
        },
        "after_unknown": {
          "id": true,
          "result": true
        },
        "before_sensitive": false,
        "after_sensitive": {}
      }
    },
    {
      "address": "random_string.foo",
      "mode": "managed",
      "type": "random_string",
      "name": "foo",
      "provider_name": "registry.terraform.io/hashicorp/random",
      "change": {
        "actions": [
          "no-op"
        ],
        "before": {
          "id": "foo",
          "keepers": null,
          "length": 3,
          "lower": true,
          "min_lower": 0,
          "min_numeric": 0,
          "min_special": 0,
          "min_upper": 0,
          "number": true,
          "numeric": true,
          "override_special": null,
          "result": "foo",
          "special": true,
          "upper": true
        },
        "after": {
          "id": "foo",
          "keepers": null,
          "length": 3,
          "lower": true,
          "min_lower": 0,
          "min_numeric": 0,
          "min_special": 0,
          "min_upper": 0,
          "number": true,
          "numeric": true,
          "override_special": null,
          "result": "foo",
          "special": true,
          "upper": true
        },
        "after_unknown": {},
        "before_sensitive": {},
        "after_sensitive": {},
        "importing": {
          "id": "foo"
        }
      }
    }
  ],
  "prior_state": {...},
  "configuration": {
    "provider_config": {
      "random": {
        "name": "random",
        "full_name": "registry.terraform.io/hashicorp/random"
      }
    },
    "root_module": {
      "resources": [
        {
          "address": "random_string.bar",
          "mode": "managed",
          "type": "random_string",
          "name": "bar",
          "provider_config_key": "random",
          "expressions": {
            "length": {
              "constant_value": 4
            }
          },
          "schema_version": 2
        },
        {
          "address": "random_string.foo",
          "mode": "managed",
          "type": "random_string",
          "name": "foo",
          "provider_config_key": "random",
          "expressions": {
            "length": {
              "constant_value": 3
            }
          },
          "schema_version": 2
        }
      ]
    }
  },
  "timestamp": "2023-11-17T10:08:46Z",
  "errored": false
}
```

There are two entries in `resource_changes`. The one for `random_string.bar` has a `change.actions` value of `["create"]` because this resource is being created (and not also replaced). The entry for `random_string.foo` has a `change.actions` of `["no-op"]`. This is because the actions in this list represent actions Terraform is asking the _provider_ to perform on apply, and in the case of a simple import there is nothing further for the provider to do.

The relevant key to look for is `importing`. This is currently always an object with an `id` field whose value is the import ID of the object being imported.

All resources being imported as part of the plan will have an entry in `resource_changes` with a non-null value for `importing`. If this key is absent then the resource is not being imported. The action for the resource could be `"no-op"` or `"update"`, since it is possible to import and update a resource in the same plan.

@chumvan, does this give you enough information to work with in your pipeline?

**Comment by kmoe** [comment]
It's also worth noting that, somewhat confusingly, `"import"` _is_ considered an "action" in the machine-readable JSON UI, i.e. the streaming JSON logs you get when you run

```
$ terraform plan -json
```

In the case of the example above you will get the following output:

```
{"@level":"info","@message":"Terraform 1.7.0-dev","@module":"terraform.ui","@timestamp":"2023-11-17T10:38:39.487788Z","terraform":"1.7.0-dev","type":"version","ui":"1.2"}
{"@level":"info","@message":"random_string.foo: Refreshing state... [id=foo]","@module":"terraform.ui","@timestamp":"2023-11-17T10:38:39.747045Z","hook":{"resource":{"addr":"random_string.foo","module":"","resource":"random_string.foo","implied_provider":"random","resource_type":"random_string","resource_name":"foo","resource_key":null},"id_key":"id","id_value":"foo"},"type":"refresh_start"}
{"@level":"info","@message":"random_string.foo: Refresh complete [id=foo]","@module":"terraform.ui","@timestamp":"2023-11-17T10:38:39.748713Z","hook":{"resource":{"addr":"random_string.foo","module":"","resource":"random_string.foo","implied_provider":"random","resource_type":"random_string","resource_name":"foo","resource_key":null},"id_key":"id","id_value":"foo"},"type":"refresh_complete"}
{"@level":"info","@message":"random_string.bar: Plan to create","@module":"terraform.ui","@timestamp":"2023-11-17T10:38:39.769030Z","change":{"resource":{"addr":"random_string.bar","module":"","resource":"random_string.bar","implied_provider":"random","resource_type":"random_string","resource_name":"bar","resource_key":null},"action":"create"},"type":"planned_change"}
{"@level":"info","@message":"random_string.foo: Plan to import","@module":"terraform.ui","@timestamp":"2023-11-17T10:38:39.769169Z","change":{"resource":{"addr":"random_string.foo","module":"","resource":"random_string.foo","implied_provider":"random","resource_type":"random_string","resource_name":"foo","resource_key":null},"action":"import","importing":{"id":"foo"}},"type":"planned_change"}
{"@level":"info","@message":"Plan: 1 to import, 1 to add, 0 to change, 0 to destroy.","@module":"terraform.ui","@timestamp":"2023-11-17T10:38:39.769197Z","changes":{"add":1,"change":0,"import":1,"remove":0,"operation":"plan"},"type":"change_summary"}
```

Parsing these logs is another option. We've also just merged a PR improving the docs for this output! https://github.com/hashicorp/terraform/pull/34217

**Comment by chumvan** [comment]
@kmoe Thank you for your reply! I think the `importing`  field is what we were looking for. As for any resources that need to be imported, the `resource_changes` must have a not-null `importing` field. I think it should be enough for us to parse the 
`out.plan` JSON file to get this field. We are checking this approach out now.

If `importing` is available in the `out.plan` then the documentation is outdated as it was our source to check for these available fields.
