### ISSUE TITLE
Terraform cloud agent for ARM architecture

### ISSUE THREAD

**Issue by kerlexov** [hashicorp/terraform#34258]
### Terraform Version

```shell
Terraform v1.6.4
on linux_arm64
```

### Use Cases

Run terraform cloud agent on ARM based hardware.

### Attempted Solutions

docker run -e TFC_AGENT_TOKEN -e TFC_AGENT_NAME hashicorp/tfc-agent:latest
Unable to find image 'hashicorp/tfc-agent:latest' locally
latest: Pulling from hashicorp/tfc-agent
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

**Comment by apparentlymart** [comment]
Hi @kerlexov! Thanks for this feature request.

This repository is only for Terraform CLI and Terraform Core, so the folks who work on Terraform Cloud Agent do not expect to find feedback here. I'd suggest sending this feedback to [HashiCorp Support](https://support.hashicorp.com/) instead, since that's the way the Terraform Cloud teams typically expect to receive feedback.

Since we use issues in this repository primarily to represent work items that can be resolved by code changes in this same repository, I'm going to close this. It's a valid request in general, but there's nothing we could change in this codebase to make it happen.

Thanks again!

**Comment by crw** [comment]
Just an add-on note to that, @kerlexov: if you are using Terraform Cloud free tier, support may tell you to open the issue in GitHub. I will make sure this ticket is seen by the product management team. Thanks for your request!
