### ISSUE TITLE
Slowness of kubernetes provider and azurerm provider

### ISSUE THREAD

**Issue by cveld** [hashicorp/terraform#34254]
### Terraform Version

```shell
Terraform v1.6.3
on windows_amd64
```

### Terraform Configuration Files

```terraform
locals {
  resource_group_name = "rg-test"
  name                = "test"
  subscription_id     = "redacted"
}

data "azurerm_kubernetes_cluster" "default" {
  name                = local.name
  resource_group_name = local.resource_group_name
}

provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.default.kube_config.0.host
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.default.kube_admin_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.default.kube_admin_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_admin_config.0.cluster_ca_certificate)
}

provider "azurerm" {
  features {}
  subscription_id = local.subscription_id
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0.0, < 4.0.0"
    }
  }
}

```

### Debug Output

https://gist.github.com/cveld/5d69297a96d319ddb6a17aa90e726f2a

### Expected Behavior

This configuration provides initialization only and run split second. Of course I would allow for a slower first run. This should hit some cache structures and following runs should run split second.

### Actual Behavior

The plan takes almost 30 seconds to complete. This is very cumbersome for quick inner dev loops.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @cveld,

Thanks for filing the issue. Looking at the logs, there doesn't appear to be any delays caused by Terraform itself, was there something specific you are looking at? Most of the time was spent waiting for the Azure provider to complete configuration, which is probably due to numerous API calls it needs to make to authenticate with the necessary services for operation.

If you want to further investigate performance issues with specific providers, it would be better to open issues directly with those providers, as those are developed independently from Terraform.

Thanks!

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
