### ISSUE TITLE
Improve error message: configuring Terraform AWS Provider: failed to get shared config profile, private-cloud-seeknow

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#34256]
### Terraform Version

```shell
Terraform v1.6.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Terraform Configuration Files

```terraform
$ cat provider.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }

    local = {
      source = "hashicorp/local"
      version = "2.3.0"
    }

    # Needed to upgrade old Portal projects
    null = {
      source = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      Project = var.project_name
    }
  }
}
```

### Debug Output

```
data.external.get_audit_output: Reading...
data.external.get_audit_output: Read complete after 1s [id=-]

Changes to Outputs:
  + iguides_bucket_name = "-portal-iguides"
  + project_name        = ""
  + user_bucket_name    = "-portal-users"

You can apply this plan to save these new output values to the Terraform state, without
changing any real infrastructure.
╷
│ Error: configuring Terraform AWS Provider: failed to get shared config profile, private-cloud-seeknow
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 21, in provider "aws":
│   21: provider "aws" {
│
```

### Expected Behavior

More clear error message. I do not understand which shared config is requested.

### Actual Behavior

Not clear error message

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @EugenKon! Thanks for reporting this.

Unfortunately this error message is from the `hashicorp/aws` provider rather than from Terraform itself, and so if it's going to be improved that would need to be done in [the provider's own repository](https://github.com/hashicorp/terraform-provider-aws).

A separate team maintains that provider, so please share this feedback in an issue in the provider's repository instead. Thanks!

**Comment by EugenKon** [comment]
OMG. Is it possible to see the source of the error message? I already posted two times in a wrong repository =(

**Comment by apparentlymart** [comment]
I'm sorry for the confusion about where the error message originates from, @EugenKon. Terraform doesn't _explicitly_ mention it because in most cases (i.e. when _not_ trying to file a bug report) it doesn't really matter what part of the system an error originated from.

With that said, if you see a message that says `with provider["registry.terraform.io/hashicorp/aws"],` above the source snippet, that typically means that the message came from the provider itself rather than from Terraform Core, or at least that Terraform Core was reacting to something the provider itself decided. This is also true when the line is something like `with aws_instance.example,`: whichever provider that resource is managed by is typically providing either the error message directly or the information that caused the error to be shown.

**Comment by EugenKon** [comment]
Thanks for explanation.
