### ISSUE TITLE
The `sort()` function converts a set to a list

### ISSUE THREAD

**Issue by Stretch96** [hashicorp/terraform#34284]
### Terraform Version

```shell
Terraform v1.6.4
on darwin_arm64
```

### Terraform Configuration Files

```terraform
variable "my_list" {
  description = "A list of things"
  type        = list(string)
  default     = ["b", "a", "c"]
}

locals {
  my_list = sort(toset(var.my_list))
}

resource "local_file" "my_files" {
  for_each = local.my_list

  filename = each.value
  content  = "foo"
}
```

### Debug Output

```
$ terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid for_each argument
│
│   on bug-report.tf line 12, in resource "local_file" "my_files":
│   12:   for_each = local.my_list
│     ├────────────────
│     │ local.my_list is list of string with 3 elements
│
│ The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of
│ type list of string.
```

### Expected Behavior

When sorting a set, it should remain as a set?

### Actual Behavior

A set is converted to a list

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

I guess this might be a discussion on what the actual behavior should be
It can be easily avoided by sorting and then converting to a list, as long as the conversion doesn't modify the indexes of the items

I also confirmed the behavior in terraform console:

```
> type(tolist(["hi"]))
list(string)
> type(toset(tolist(["hi"])))
set(string)
> type(sort(toset(tolist(["hi"]))))
list(string)
```

**Comment by liamcervante** [comment]
Hi @Stretch96, thanks for filing this!

Sets are inherently unordered so the only way to retain an order over the returned value is for it to be a list. If you attempted to convert the returned list back into a set any imposed order would be lost. With that in mind I think the current behaviour is correct. When you want to sort the set data structure that output is ordered by whatever the sort criteria was, and so you have a list regardless of the input type.

For your use case, you can use the count meta-attribute instead of foreach and retrieve the items from the sorted list by index.

Thanks!
