### ISSUE TITLE
Instance module.abc.data.aws_lambda_invocation.xyz["123"] is marked as having a change pending but that change is not recorded in the plan.

### ISSUE THREAD

**Issue by andresvia** [hashicorp/terraform#34310]
### Terraform Version

```shell
Terraform v1.3.5
on f00
+ provider registry.terraform.io/hashicorp/aws v5.26.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
```

### Terraform Configuration Files

```terraform
data "aws_lambda_invocation" "xyz" {
  for_each      = { for k, v in local.functions : k => v if lookup(v, "xyz", null) != null }
  function_name = module.foo.bar[each.key].baz
  input         = jsonencode(each.value["xyz"]["foobar"])
  // make it happen only during apply (trying to fix the change not recorded in plan)
  depends_on = [null_resource.apply_anchor]
  lifecycle {
    postcondition {
      condition     = jsondecode(self.result) == each.value["xyz"]["barfoo"]
      error_message = "wanted barfoo but got something else"
    }
  }
}
```

### Debug Output

```
╷
│ Error: Missing pending object in plan
│ 
│   on abc/abc.tf line 420:
│  420: data "aws_lambda_invocation" "xyz" {
│ 
│ Instance
│ module.abc.data.aws_lambda_invocation.xyz["123"] is
│ marked as having a change pending but that change is not recorded in the
│ plan. This is a bug in Terraform; please report it.
╵
Releasing state lock. This may take a few moments...
```

### Expected Behavior

It should either work all the time or fail all the time. Ideally work all the time and not fail randomly sometimes.

### Actual Behavior

It fails sometimes.

### Steps to Reproduce

```
terraform init
terraform plan -out tf.plan
terraform apply tf.plan
```

**Comment by apparentlymart** [comment]
Hi @andresvia! Sorry this didn't work as intended, and thanks for reporting it.

To understand what happened here I expect we'll need to review the full trace log that we requested in our issue template. You've shared normal output rather than the "Debug Output", and so there isn't enough information here to understand why this invariant was not upheld.

To produce the full trace output:

1. Set the environment variable TF_LOG=trace
2. Run the same `terraform plan -out tf.plan` command you ran before, and save the verbose log output to a file.
3. Run the same `terraform apply tf.plan` command you ran before, and save its verbose log output to a separate file.
4. Add both of those files to a [GitHub Gist](https://gist.github.com/) and share the link to that Gist here.

In this particular case I expect we'll need to see the full trace logs for both the plan phase _and_ the apply phase, because this problem seems to span across both of the phases: the `terraform plan` command seems to have generated an invalid plan file, and the `terraform apply` command is then detecting that error and reporting it with this error message.

Thanks!

**Comment by andresvia** [comment]
@apparentlymart don't need to be sorry, I'm thankful for the work done on Terraform, I did a quick Google for `terraform reporting strip sensitive information when TF_LOG=trace` is there a canonical way to do it? Maybe a tool or regex to remove all traces of information that may identify the account or AWS user?

**Comment by apparentlymart** [comment]
Hi @andresvia,

Different organizations have different opinions about what is "sensitive", so there is no tool for that. You'd need to review the output yourself and decide what you consider to be sensitive. Of course, if you remove too much then the output won't be useful, so I'd encourage focusing mainly on eliminating personally-identifying information like specific IP addresses or names/ids that are in global namespaces that others could potentially access, and less on generic information like which resource types you are using and how they are related to one another.

**Comment by jbardin** [comment]
Hi @andresvia,

One other thing to check is that v1.3 was released over a year ago, and there have been many issues fixed since then. You may want to confirm this still happens with a current version of Terraform.

Thanks!

**Comment by andresvia** [comment]
I know I've been very quiet about this issue, I just want to report that I tried it in `1.5.3` and it is still happening. My eventual reproduction of the problem will use `1.5.3`.

**Comment by rwblokzijl** [comment]
I managed to reproduce this in a minimal example:
```terraform
resource "null_resource" "resource_name" {
}
data "null_data_source" "data_source_name" {
  # Increase number of resources to increase the changes of error (issue is non-deterministic)
  for_each = toset(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", ])
  lifecycle {
    postcondition {
      # To repoduce
      # Either condition OR error_message must use self.outputs, success of fail does not matter
      condition = self.outputs == null
      # Must depend on resource not known until apply
      error_message = null_resource.resource_name.id
    }
  }
}

```
Just run `terraform plan` with this config. If it doesn't fail, run it again.

Terraform --version:
```
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.3
```
