### ISSUE TITLE
aws provider allowed_account_ids does not work with iam instance profile

### ISSUE THREAD

**Issue by mnylen** [hashicorp/terraform#3431]
provider "aws" {
      region = "${var.region}"
      allowed_account_ids = ["${var.allowed_account_id}"]
    }

With this provider config, terraform apply fails when running on EC2 instance with IAM instance profile. The error message I'm getting this:

    * Failed getting account ID from IAM: ValidationError: Must specify userName when calling with non-User credentials
          status code: 400, request id: [...]

If I remove the allowed_account_ids attribute, it starts to work.

**Comment by mnylen** [comment]
Terraform version: 0.6.3

**Comment by stack72** [comment]
@mnylen are you providing IAM keys as well? or just the region and allowed_account_ids?

**Comment by radeksimko** [comment]
@stack72 I don't think he is.

> when running on EC2 instance with IAM instance profile

which means that credentials are coming from the internal metadata service.

**Comment by apparentlymart** [comment]
This is handled [in `config.go`](https://github.com/hashicorp/terraform/blob/8e79f0cb3adee3ffac1ead66e677738a2d557bc0/builtin/providers/aws/config.go#L233).

It looks like the implementation is to call [iam:GetUser](http://docs.aws.amazon.com/IAM/latest/APIReference/API_GetUser.html) with no `UserName` argument. According to the docs that returns "the user making the request". Makes sense that this wouldn't work for an instance profile since that's not a user, and so there is no "current user" to return.

The particular error you are getting seems to have been fixed in b95e7a976ca1f9761f24d647199752b684d0b7b8, where it became silently ignored. However, I think a bug may still remain here: if the `GetUser` call fails then we presumably won't have a user ARN, and so line 248 will either produce a crash or an empty string.

So all of this is to say: as currently implemented it doesn't look like ``allowed_account_ids`` can work with instance profile credentials, since we depend on being able to retrieve the user object making the request. In the next version of Terraform this will behave differently, but may stil have some issues in this case.

**Comment by stack72** [comment]
@radeksimko d'oh! Missed that :(

**Comment by apparentlymart** [comment]
It looks like in the case where we're running with instance credentials we can get an instance profile ARN from the metadata endpoint `http://169.254.169.254/latest/meta-data/iam/info`.

Perhaps it would be sensible to detect whether we got the credentials from the environment or from the instance metadata, and do the account checks differently in the latter case so we'll get the right result from the metadata API.

**Comment by radeksimko** [comment]
> we can get an instance profile ARN from the metadata endpoint http://169.254.169.254/latest/meta-data/iam/info.

That looks like a good plan. :+1:

**Comment by bwalding** [comment]
There doesn't appear to be a great solution for identifying the current account (they're all hacks) when dealing with IAM/STS assume-role generated credentials.

Since an account always has security groups - you could pull the `OwnerId` off the first entry. The downside for a regular program would be that it may not have access to security groups, but I would assume Terraform would always have at least read access to them.

`aws ec2 describe-security-groups`

**Comment by radeksimko** [comment]
> Since an account always has security groups

I'm afraid this isn't true. It is possible to remove the default ones in the default VPC and I wouldn't rely on any security groups outside of default VPC either. You don't really need any SGs in cases where you're running background jobs.

I think that gracefully falling back to the metadata endpoint if IAM call fails is ok.
Here's an example of response from that endpoint:

```json
{
  "Code" : "Success",
  "LastUpdated" : "2015-10-28T16:49:39Z",
  "InstanceProfileArn" : "arn:aws:iam::101636750127:instance-profile/aws-elasticbeanstalk-ec2-role",
  "InstanceProfileId" : "AIPAREU6ES7PV7RYRYPIC"
}
```

**Comment by apparentlymart** [comment]
Right... I think it doesn't even need to be implemented as a fallback, because Terraform "knows" whether it got the credentials from the instance metadata, and so it knows it's using an instance profile without needing to try the initial `GetUser` request to see if it will fail.

**Comment by catsby** [comment]
Hey all – doing a review of old issues , is this still relevant?

**Comment by radeksimko** [comment]
This is still relevant. Essentially https://github.com/hashicorp/terraform/pull/3313 caused that `allowed_account_ids`/`forbidden_account_ids` are being ignored and any commands are just executed.

**Comment by roderickrandolph** [comment]
As a fallback when a user name is not provided (i.e. STS roles/credentials) why not attempt to grab the first IAM user's ARN within the account and parse out that user's account ID. It would require the `iam:ListUsers` permission which is one more than the `iam:GetUser` permission that's currently required for `allowed_account_ids` /  `forbidden_account_ids` to work anyway.

It's certainly a hack but it'll work since all users within an account will have the same ID and terraform requires at least one user to exist.

**Comment by roderickrandolph** [comment]
I hit this problem while using terraform and STS outside of an instance (i.e. where instance metadata is not available)

**Comment by roderickrandolph** [comment]
d'oh looks like #4290 may solve the problem

**Comment by radeksimko** [comment]
See https://github.com/hashicorp/terraform/pull/5030
I just tested that ^ with both EC2 & instance profile and federated account and it worked aok.
Any feedback is welcomed, especially before we merge that PR.

**Comment by radeksimko** [comment]
Fixed via https://github.com/hashicorp/terraform/pull/5030 and https://github.com/hashicorp/terraform/pull/6536 which is also re-enabling credentials validation on EC2 instance (will be part of `0.7.0` release).
