### ISSUE TITLE
State file 

### ISSUE THREAD

**Issue by Acenl12** [hashicorp/terraform#34321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

To be honest in nowadays api's world it's a shame in my opinion that you have to use a state file in a storage account to be able to use terraform to deploy code. Please suggest more cloud native ways and implement those 
Over the years i have seen many issues with the state file and organizations moving away from Terraform 

### New or Affected Resource(s)/Data Source(s)

Azurerm

### Potential Terraform Configuration

```
terraform {
  backend "azurerm" {
    resource_group_name   = "your-resource-group"
    storage_account_name   = "your-storage-account"
    container_name         = "your-container"
    key                    = "terraform.tfstate"
  }
}
```

**Comment by jbardin** [comment]
Hi @Acenl12,

Terraform requires some way to store external state to operate as it does, there is no way around that. Also, because Terraform is not specific to any individual cloud service, the state storage must be done via some sort of generic API which can be applied equally to many different services.

Since there isn't any concrete proposal or bug shown here I'm going to close the issue. If you want to discuss other theoretical designs of Terraform, or have questions about managing state, or why it is implemented the way it is, I would suggest using [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!
