### ISSUE TITLE
Invalid availability zone for subnet

### ISSUE THREAD

**Issue by chris-hailstorm** [hashicorp/terraform#3434]
It appears AWS has a temporary or permanent ban on creating subnets in us-east-1a.  Error message:

* aws_subnet.subnet_a: Error creating subnet: InvalidParameterValue: Value (us-east-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1b, us-east-1c, us-east-1d, us-east-1e.
	status code: 400, request id: []

This is while working through the "aws-intermediate-consul-cluster" example.  My AWS_REGION value is us-east-1.  I don't provide the -1a anywhere, assuming this comes from Terraform in some way?

**Comment by stack72** [comment]
@chris-hailstorm can you link me to the example you are looking at? I can spin it up and see

**Comment by phinze** [comment]
@chris-hailstorm thanks for the report - the issue here is that AZs are named differently per account, so there's no way to predict which AZs are available for every user

On the "aws-intermediate-consul-cluster" example, you can set the AZs used by subnets in the "subnets" input variable: https://github.com/hashicorp/atlas-examples/blob/master/consul-cluster/aws-intermediate-consul-cluster/terraform/variables.tf#L33-L35
