### ISSUE TITLE
Trim() output drops first character of expected output if it is "c"

### ISSUE THREAD

**Issue by vanastassiou** [hashicorp/terraform#34408]
### Terraform Version

```shell
$ terraform --version
Terraform v1.6.5
on darwin_arm64
```
```


### Terraform Configuration Files

No config used, just string manipulation in console


### Debug Output

N/A, done in console

### Expected Behavior

```
$ terraform console
> trim("cat-service", "service")
"cat-"
> trim("dog-service", "service")
"dog-"
> trim("catdog-service", "service")
"catdog-"
> trim("dogcat-service", "service")
"dogcat-"
```

### Actual Behavior

```
$ terraform console
> trim("cat-service", "service")
"at-"
> trim("dog-service", "service")
"dog-"
> trim("catdog-service", "service")
"atdog-"
> trim("dogcat-service", "service")
"dogcat-"
```

### Steps to Reproduce

In `terraform console`:

```
> trim("cat-service", "service")
> trim("dog-service", "service")
> trim("catdog-service", "service")
> trim("dogcat-service", "service")
```

### Additional Context

_No response_

### References

_No response_

**Comment by jbardin** [comment]
Hi @vanastassiou,

The second argument to [`trim`](https://developer.hashicorp.com/terraform/language/functions/trim) is a character _set_, not a prefix or suffix (note this is common in many language functions, and not specific to Terraform)

> Every occurrence of a character in the second argument is removed from the start and end of the string specified in the first argument.

The `c` is removed, because `c` is in the set of characters provided in the second argument. If you want to remove a specific prefix or suffix,  there are the [`trimprefix`](https://developer.hashicorp.com/terraform/language/functions/trimprefix) and [`trimsuffix`](https://developer.hashicorp.com/terraform/language/functions/trimsuffix) functions. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by vanastassiou** [comment]
Hi James,

Thanks for the clarification. It's clear I misunderstood the original documentation.
