### ISSUE TITLE
Add a `template` function to process a template directly from a string value

### ISSUE THREAD

**Issue by ankon** [hashicorp/terraform#34412]
### Terraform Version

```shell
Terraform v1.6.5
on linux_amd64
```

I checked the documentation for 1.7.x as well.

### Use Cases

Terraform provides a `templatefile` function, which takes the path to a template on the file system, and a set of variables as context. I propose a `template` function that does the same, but takes a string to interpolate directly.

Use case: I'm configuring alerts in our monitoring system, and end up having similar expressions (queries) for multiple environments and applications. For instance: `SELECT apdex(apm.service.apdex) FROM Metric WHERE entity.guid = 'MAGIC VALUE HERE'`. Ideally I keep the query templates separate from the actual environment/application definition, so that I can quickly produce matching alerts for _all_ environments and applications.

Templating would work great: `SELECT apdex(apm.service.apdex) FROM Metric WHERE entity.guid = '${app_config.guid}'`.

### Attempted Solutions

Reasonably straight-forward: Store the query templates each in a file, and use `templatefile(path-to-file, { app_config: { ... } }` to use them.

### Proposal

The `template` function would make my life easier, and also improve readability of the code.

**Comment by 6525146** [comment]
I nade halp

**Comment by crw** [comment]
Thanks for this feature request! If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!

**Comment by ankon** [comment]
Hmm. I tried searching, and didn't find that. Yes, from a initial read it's the same request. I do notice that there is a lot of discussion there, and am wondering whether maybe it makes sense to prototype this out?

**Comment by crw** [comment]
As announced at HashiConf, there is a plan to support external functions, which is most likely how this will be implemented. If you did prototype an implementation, it would likely not be reviewed and need to be converted to an external function down the road. It is not implemented today because the team did not want an `eval` function for Terraform. However, with external functions on the horizon, it seems inevitable, so there is a small chance the team may still implement a version of this just to have some control over the implementation. In any case, thanks for thinking about it.
