### ISSUE TITLE
Import block with 'for_each' causes Terraform to expect a non-existent 'each' provider

### ISSUE THREAD

**Issue by AP-Hunt** [hashicorp/terraform#34440]
### Terraform Version

```shell
Terraform v1.7.0-beta2
on darwin_amd64
```

### Terraform Configuration Files

```terraform
provider "aws" {
    region = "eu-west-2"
}

resource "aws_route53_hosted_zone" "zoneA" {
    name = "example.com"
}

resource "aws_route53_hosted_zone" "nameB" {
    name = "example.org"
}

locals {
    imports = {
        "aws_route53_hosted_zone.zoneA" = "XYZ098"
        "aws_route53_hosted_zone.zoneB" = "ABC123"
    }
}

import {
    for_each = local.imports
    to = each.key
    id = each.value
}
```

### Debug Output

https://gist.github.com/AP-Hunt/13cbb1dc8d8894fa1a3ff8aa591422ac

### Expected Behavior

I would have expected the code above to be equivalent to

```terraform
import {
    to = aws_route53_hosted_zone.zoneA
    id = "XYZ098"
}

import {
    to = aws_route53_hosted_zone.zoneB
    id = "ABC123"
}
```

### Actual Behavior

`terraform init` failed, with a message about looking for a provider called 'each' which doesn't exist.

### Steps to Reproduce

Copy minimal replication code, then `terraform init`

**Comment by jbardin** [comment]
Hi @AP-Hunt,

Thanks for filing the issue, and trying out the beta! Terraform cannot interpolate a resource address, which must be statically defined in the configuration. This is causing Terraform to try and find a resource type named `each` rather than a resource type named `aws_route53_hosted_zone`. Importing to multiple resource blocks requires an import block for each resource.

What the `for_each` feature does allow however, is for interpolation of index keys within a resource address. Your configuration could be structured more like this:

```
resource "aws_route53_hosted_zone" "example" {
  for_each = {
    "zoneA" = "example.com",
    "zoneB" = "example.org"
  }
  name = each.value
}

locals {
    imports = {
        "zoneA" = "XYZ098"
        "zoneB" = "ABC123"
    }
}

import {
    for_each = local.imports
    to = aws_route53_hosted_zone.example[each.key]
    id = each.value
}
```
