### ISSUE TITLE
Terraform always detects non-empty plans on version <1.4.0 and empty plans on version >=1.4.0 for Plugin Framework resources with nullable Optional & Computed attributes

### ISSUE THREAD

**Issue by maastha** [hashicorp/terraform#34460]
### Terraform Version

```shell
Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.13.1

and

Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.13.1
```

### Terraform Configuration Files

```terraform
resource "mongodbatlas_advanced_cluster" "cluster-no-oc-collections" {
  project_id   = mongodbatlas_project.project.id
  name         = "tested-cluster-single-provider2"
  cluster_type = "REPLICASET"

   replication_specs =[{
    region_configs =[{
      electable_specs =[{
        instance_size = "M10"
        node_count    = 3
      }]
      analytics_specs =[{
        instance_size = "M10"
        node_count    = 1
      }]
      provider_name = "AWS"
      priority      = 7
      region_name   = "US_EAST_1"
    }]
  }]
}


resource "mongodbatlas_advanced_cluster" "cluster-with-collections" {
  project_id   = mongodbatlas_project.project.id
  name         = "cluster-single-with-collec2"
  cluster_type = "REPLICASET"

  bi_connector_config =[{
    enabled = true
    read_preference = "secondary"
  }]

    advanced_configuration =[{
    oplog_size_mb                        = 999
    sample_refresh_interval_bi_connector = 300
  }]

   replication_specs =[{
    region_configs =[{
      electable_specs =[{
        instance_size = "M10"
        node_count    = 3
      }]
      analytics_specs =[{
        instance_size = "M10"
        node_count    = 1
      }]
      provider_name = "AWS"
      priority      = 7
      region_name   = "US_EAST_1"
    }]
  }]
}
```

### Debug Output

https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-terraform1-3-5-log 
https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-terraform1-4-0-log

### Expected Behavior

- Terraform should always give empty plans/`No changes.`  on Terraform versions >1.0

- Terraform should show which attributes could be causing drift detection in all versions

### Actual Behavior

- Terraform produces drift detection/non-empty plans on Terraform versions <1.4.0. Even if user applies the plan, the plan still continues to stay non-empty every time `terraform plan` is run

- Terraform gives empty plans/`No changes.` on Terraform versions >=1.4.0

- There is no difference in the final state after apply on versions 1.3.5 vs 1.4.0 but the plan detection is still different on both versions.

- There is no way to understand exactly what attribute could be causing the drift detection as all Optional & Computed attributes and nested attributes show with a `(known after apply)`

### Steps to Reproduce

1. Create resource with Plugin SDKv2-based version of provider 
2. Upgrade to resource with Plugin Framework-based version of provider
3. Run `terraform plan` 

Repeat above steps on Terraform versions 1.3.5 and 1.4.0

### Additional Context

We are migrating a resource from Plugin SDKv2 to Plugin Framework (Plugin protocol 6 with muxing). Our resource has a few Optional & Computed ListNestedAttributes with nested attribute lists. Most attributes/list nested attributes are optional & computed which means the user may/may not provide values for these AND the API may/may not return values for these and in such cases these attributes can be null.

Upon migration, for Terraform versions 1.4.0+ we are able to successfully avoid any drift detection for resources previously created with the Plugin SDKv2-based implementation of the resource so that once our users upgrade our provider to use the migrated resource they don’t encounter any unnecessary non-empty plans.
However, this is not the case for Terraform versions 1.2.x or 1.3.x and we get non-empty plans with the migrated resource.

During migration we were aware that we could lose compatibility with Terraform versions <1.0 but we are now struggling to stay compatible with <1.4.0 which is a fairly recent version of Terraform hence we need to be able to support Terraform versions >1.0 (or >1.1.6 due to muxing) if we need to migrate to the Plugin Framework.

tfplan JSON files for versions 1.3.5 and 1.4.0:
https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-tfplan-1-3-5-json
https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-tfplan-1-4-0-json

.tfstate files for versions 1.3.5 and 1.4.0:
https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-tfstate_after_apply_1-3-5-tfstate
https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-tfstate_after_apply_1-4-0-tfstate

original .tfstate file for created resources implemented in Plugin SDK:
https://gist.github.com/maastha/0fc749417b8b79f44620f395458b7607#file-tfstate_after_create_from_plugin_sdkv2_based_resource-tfstate

### References

https://github.com/hashicorp/terraform-plugin-framework/issues/883

**Comment by bflad** [comment]
Hi @maastha 👋 Thank you for creating this issue with a bunch of relevant details on this complex topic.

I'm not typically responsible for triaging issues in this issue tracker, however I want to provide some additional context for you and the Terraform core maintainers that eventually triage this issue from the core perspective since I am in the process of investigating something that appears very related in https://github.com/hashicorp/terraform-plugin-framework/issues/898. The timing is quite coincidental.

Quick upfront terminology note: `(known after apply)` in the human-readable plan output is the representation of Terraform's concept of an unknown value.

The managed resource planning process can be a somewhat careful dance between Terraform core and whatever is on the provider side of the protocol when the `PlanResourceChange` RPC request is sent to the provider. In your case, terraform-plugin-framework is handling the `PlanResourceChange` RPC logic, which has [its own plan modification behaviors](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#plan-modification-process). For legacy reasons, Terraform will call `PlanResourceChange` even when there is no resource configuration change, which has some unfortunate consequences.

The important terraform-plugin-framework context to mention:

- Its planning implementation is heavily dependent on the proposed new state created by Terraform currently. Additional details about the proposed new state data can be found in the [resource instance change lifecycle documentation](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md), but its essentially a merging of configuration values on top on the prior state with some consideration of the schema definition.
- When that proposed new state differs from the prior state, it then assumes that there must have been an "update" to the resource and will transform the proposed new state data to replace any null configuration values with unknown values. This is an important Terraform error prevention mechanism for practitioners as Terraform requires that providers must return applied state that exactly matches the planned state (response terminology for the proposed new state) except that unknown values can be filled in. This is why in practice you have to use the awkwardly named `UseStateForUnknown` plan modifier to "fix" the planned state by preserving the prior state value (remove the plan difference) if you know that an update will not change a value. Otherwise without this automatic behavior, provider developers would have to explicitly define every computed attribute that can potentially change on updates and constantly deal with bug reports from practitioners when cases are missed.

I think the behavior change you are seeing from differing Terraform versions may be due to https://github.com/hashicorp/terraform/pull/32551, which was introduced in v1.4.0-beta1 and would cause Terraform to send different proposed new state data in nested attribute situations like this (a null value instead of the prior state). Nested attribute support is only in terraform-plugin-framework, so terraform-plugin-sdk resources would not have been affected. 

We have considered in the past whether the framework (or any provider side implementation really) should actually use Terraform's proposed new state data. It is effectively a best guess at what will happen to a resource state after a "change" since the data will be constructed even without changes and since the protocol (and therefore Terraform) is not exposed to all possible details or behaviors imposed by the system behind the provider implementation, such as default API values, to fully know what would happen from a data perspective.

I'm going to stop here because I do not want to get any further into speaking about any particular opinions or potential solutions until the core maintainers can chime in, but I hope this additional context will maybe shed some additional insight about the various systems and behaviors at play here.

**Comment by jbardin** [comment]
Hi @maastha,

Thanks for filing the issue. Can you explain further what the desired resolution would be for this? From my reading of the issue, it sounds like Terraform improved the plan generation around v1.4, so the bug has been fix as it now matches your expectations.

**Comment by maastha** [comment]
@jbardin 

Yes, agreed that the improved plan generation helps, but only with higher Terraform versions. As per [documentation](https://developer.hashicorp.com/terraform/plugin/framework/migrating/mux#terraform-1-x-compatibility-example), when migrating existing resources to Plugin Framework (protocol 6 and muxing), we expect to stay compatible with Terraform versions 1.1.6+.
On the contrary, the behavior mentioned in this issue renders us incompatible with Terraform versions <1.4.0 as the plans **are never empty.**

My assumption would be that now that providers are migrating to the Plugin Framework and coming across more and more use-cases with null values, in order to maintain compatibility with Terraform versions 1.1.6+, the desired resolution for this would be to have these fixes backported to older supported versions as well because v1.4.0 is fairly recent and likely not a lot of customers have upgraded yet.
Is that a possibility at all? 

If not, it doesn't look feasible to migrate complex resources to the Plugin Framework as we lose compatibility with older versions and this should be communicated by Hashicorp.

Please let me know if I am missing anything.

**Comment by maastha** [comment]
@bflad Thank you so much for all your guidance throughout this migration!

>This is why in practice you have to use the awkwardly named UseStateForUnknown plan modifier to "fix" the planned state by preserving the prior state value (remove the plan difference) if you know that an update will not change a value. 

I understand and we have used UseStateForUnknown where ever possible, but as you mentioned, this can be done "if you know that an update will not change a value", but for cases where the value can change, what could be our options there?

**Comment by jbardin** [comment]
@maastha,

We don't actively support minor versions other than the current release. The v1 compatibility guarantees help to make keeping up to date as smooth as possible, and users are expected to be on the latest release. Also, as you can see in this case, the change was significant enough that it requires a minor release precisely because it alters the planning behavior.

**Comment by maastha** [comment]
@jbardin I understand, so then is it correct to say that migration to Plugin Framework (protocol 6) can break compatibility with older Terraform versions contrary to v1.1.6+ as claimed in the documentation because of how plan generation works especially around nullable objects?

**Comment by jbardin** [comment]
@maastha, Terraform core only operates at the level of the plugin protocol, the library used for interfacing the provider code with the protocol is largely irrelevant. The only major difference on the core side is that providers using the older SDK are allowed to create invalid plans within certain limitations for backwards compatibility. If the provider was creating creating completely valid plans with the SDK, then switching to an equivalent schema with the framework would work in exactly the same manner. 

I have not had time to go through the prior conversations from the the linked issue in detail, but it sounds like what is going on may have roughly worked like:
- The SDK-based provider was relying invalid plans to hide certain changes proposed by core.
- Migrating to the framework used the proposed plan value to avoid errors, which happened to highlight differences in the plan, even though the desired plan would have been also valid under the protocol.
- Terraform v1.4 improved the mechanism used to to propose new plan values, which covered more provider use cases, and happen to align with the desired plan for the provider.

Note that the changes mentioned in v1.4 are also only changes to the _proposed_ state value in the planning process, the provider is still free to alter that proposed value within the contract of the instance change lifecycle. This means that it is possible to create a matching plan in v1.1-v1.3, it just requires more manual work from the provider (though that may be difficult depending on the facilities offered by the framework, I don't know how much customization is available and at what level of detail).

So "compatibility" here is kind of difficult to pin down. Terraform is technically compatible at the protocol level throughout -- but the matrix of legacy SDK bugs, latent core and provider bugs, framework and core enhancements, desired behavior, and implementation effort required, are inevitably going to leave certain combinations not functioning as one may want. So for your use case, it may be possible to match the plan with v1.1-v1.3 with enough effort, or you could say that your use case is only compatible with version v1.4 onward.

**Comment by maastha** [comment]
>So for your use case, it may be possible to match the plan with v1.1-v1.3 with enough effort,

We understand, unfortunately adding to the issue here is that on these versions Terraform also doesn't tell us exactly what attribute causes the plan difference for us to try to "match" the plan and so the output is essentially just full of "(known after apply)". I understand that this happens because as @bflad mentioned :
>When that proposed new state differs from the prior state, it then assumes that there must have been an "update" to the resource and will transform the proposed new state data to replace any null configuration values with unknown values.

But I have been unable to figure out what causes that difference even from the JSON plan output.

**Comment by jbardin** [comment]
> But I have been unable to figure out what causes that difference even from the JSON plan output to be able to do anything about it

My guess the easiest way to determine those would be to see which attributes were changed in the plan output and not marked as "unknown". You could also log the plan data from within the provider to see what is being sent as the prior state, config, and proposed state. The usual culprit in old providers is going to be zero-values an null being interchanged, since the legacy SDK did not have a null value.

There may be other clues in the `resource_drift` section of the plan json, which will show saved state and the state returned from the `ReadResource` which may be indicative of inconsistencies within the provider. Ideally there will be no changes in the `resource_drift` unless actual changes have taken place outside of Terraform. If the resource plans with a perpetual change, and nothing is changing outside of Terraform, then the trigger is likely to show up here.
