### ISSUE TITLE
removed block does not remove submodules of a module from state, but destroys submodule resources instead

### ISSUE THREAD

**Issue by treksler** [hashicorp/terraform#34475]
### Terraform Version

```shell
1.7.0-rc1
```

### Terraform Configuration Files

default docker image for 1.7.0-rc1 from dockerhub. no config changes

### Debug Output

N/A

### Expected Behavior

i expect removing a module from state to remove all resources and submodule resources from state. I am assuming this is how terraform state rm works (correct me if i am wrong)

### Actual Behavior

terraform plan said that all resources in that module would be removed from state (as expected), but all resources that were in a submodule of that module would be destroyed!! wowza!!!

this is ok:
```
# module.eks-ingress.kubernetes_service.nlb["ingress-nginx-controller"] will no longer be managed by Terraform, but will not be destroyed
 # (destroy = false is set in the configuration)
```
this is not ok:
```
# module.eks-ingress.module.acm["*.whatever.com"].aws_acm_certificate.this[0] will be destroyed
  # (because aws_acm_certificate.this is not in configuration)
```
  ...
`Plan: 0 to add, 0 to change, 6 to destroy.
`

### Steps to Reproduce

1. add a module with a submodule to state
2. delete the code that calls the module and add a removed block for that module
3. notice that everything in submodule of the module is marked for destruction when you run the plan

### Additional Context

in order to work around i had to explicitly define the removed blocks for all submodules

```
removed {
  from = module.eks-ingress
  lifecycle {
    destroy = false
  }
}

removed {
  from = module.eks-ingress.module.acm
  lifecycle {
    destroy = false
  }
}

```

**Comment by liamcervante** [comment]
I've found the root cause, here's an example: https://github.com/hashicorp/terraform/blob/main/internal/terraform/node_resource_plan_orphan.go#L150C2-L150C2

Essentially, the resources are only checking if the modules they are in exactly match a removed module while they should be checking if the module they are is in contained within a removed module. Luckily, we already have a function for checking this: `TargetContains`. So, should be a simple fix 🤞
