### ISSUE TITLE
Sending Anonymous Analytics/Report data from customers using provider

### ISSUE THREAD

**Issue by marcosuma** [hashicorp/terraform#34484]
### Terraform Version

```shell
latest
```

### Use Cases

Our team owns the [MongoDB Atlas provider](https://github.com/mongodb/terraform-provider-mongodbatlas).
I am looking for ways to further improve customer experience and anonymously detect potential bugs and failures customers encounter when using our provider.

I thought about this and from a technical perspective it should not be complicated to do it. I am more interested here from a Hashicorp standpoint if:

* is this something that you are aware other providers are doing?
* would it be a supported practice?
* how could I explicitly ask customers if they are ok in sending data anonymously?

### Attempted Solutions

Customers report issues to us. Most of the time provided information in incomplete and this slow the investigation process down.

### Proposal

Looking for ways on how this could be handled with some analytics/report mechanisms that could be handled at provider level but that could eventually be supported in some standard way by Hashicorp Terraform itself.

**Comment by apparentlymart** [comment]
Hi @marcosuma! Thanks for starting this discussion.

This question would be best answered by the team who maintains the provider SDK/framework and related concerns, and I see that you've also opened [a topic in the community forum](https://discuss.hashicorp.com/t/sending-analytics-data-from-our-mongodb-atlas-provider-when-customer-encounter-failures/61428), and so I'm going to close this one just because this is not really an enhancement request in the sense that we'd add something to this codebase and then mark it as done, and so the community forum seems like a better place to discuss this.

I also sent a note internally to the aforementioned team to let them know this question is here, so hopefully they'll get in touch in the community forum soon.

Thanks again!
