### ISSUE TITLE
Consider having terraform validate raise an error if provider block defined without whitespace

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/terraform#34507]
### Terraform Version

```shell
Terraform v1.6.5
on darwin_arm64
```

### Use Cases

The following `provider` block definition within configuration validates successfully when `terraform validate` is executed:

```tf
provider"random"{}
```

### Attempted Solutions

N/A

### Proposal

Consider having `terraform validate` raise an error if a provider block definition without whitespace is detected. For instance:

```tf
provider"random"{}
```

**Comment by jbardin** [comment]
Hi @bendbennett,

This would be a change to the HCL language rather than something we could do in Terraform, and it would be a breaking change at that. While it certainly doesn't match the preferred style, it still parses and could be present int configurations, even if it's just a typo.

As long as the individual tokens can be extracted, the config still parses correctly, this for instances is also valid:

```
resource"terraform_data"name{
input="yuck"
}
```

**Comment by apparentlymart** [comment]
If I recall correctly, I would expect `terraform fmt` to reformat the original example to have the space that's conventionally included.

If you're using `terraform validate` as part of some pre-merge automated checks then you could potentially also run `terraform fmt` and fail the check if it proposes any changes. This will also enforce all of the other style rules that `terraform fmt` imposes.

**Comment by bendbennett** [comment]
Thanks for the feedback @jbardin and @apparentlymart.

I'll close this out.
