### ISSUE TITLE
Introduce first class function types to Terraform

### ISSUE THREAD

**Issue by leptonyu** [hashicorp/terraform#34508]
### Terraform Version

```shell
1.6.6
```

### Use Cases

I want to implement reduce functions like `max`, `min`, `sum`.

### Attempted Solutions

The best way to implement such functions is providing `fold`. But it requires function as parameter.

### Proposal

1. Introducing `function` as a new `type`. 
2. Allow first-order function only as `type`.

### References

- https://en.wikipedia.org/wiki/Fold_(higher-order_function) .
- https://jsonnet.org/ref/stdlib.html , see `std.foldl(func, arr, init)`.

**Comment by apparentlymart** [comment]
Hi @leptonyu!

Just so that we can get a better idea of what exactly this feature would allow you to do if implemented, can you give some examples of functions you would implement with it that are not already offered in Terraform? (Terraform already has [`min`](https://developer.hashicorp.com/terraform/language/functions/min), [`max`](https://developer.hashicorp.com/terraform/language/functions/max), and [`sum`](https://developer.hashicorp.com/terraform/language/functions/sum) as builtins.)

**Comment by apparentlymart** [comment]
Hi @leptonyu! Thanks for those examples.

I think it's important to recognize that Haskell is a general-purpose programming language in which defining functions is in a sense the most prominent programming activity, whereas the Terraform language is a domain-specific language intended primarily for declaring objects and describing relationships between them.

For that reason, the Terraform language focuses primarily on _using functions already provided elsewhere_, rather than implementing new ones. We've historically preferred to add useful built-in functions to the language itself so that they are ready to use in modules without definition, and in a forthcoming release we are intending to extend that by allowing provider plugins to contribute their own functions so that functions written in other languages can be exposed into Terraform without modifying the core codebase.

Terraform already has either an operator or a built-in function for each of the examples you shared. They are of course not actually implemented in terms of fold as they might be in Haskell, but they exist nonetheless and therefore reimplementing them in terms of fold would be redundant.

The intention of my question was to see if there is something you want to implement that would not make sense as a built-in or provider-contributed function (e.g. because it is a very specialized need that is unlikely to arise in any other module), which could therefore justify having fold as an escape hatch. Given that your proposal amounts to a significant change to both Terraform language syntax and to the type system, the benefit would need to be significant to make that seem a better investment than implementing the specific higher-level function you need as either a built-in or as a provider-contributed function written in another language and exposed to Terraform via the plugin protocol.

Thanks again!

**Comment by crw** [comment]
Based on the description above, I am going to close this issue. Thanks for the feature request!
