### ISSUE TITLE
Terraform crash when using conditional expression with Twingate provider

### ISSUE THREAD

**Issue by alexherington** [hashicorp/terraform#34540]
### Terraform Version

```shell
Terraform v1.7.0
on darwin_arm64
+ provider registry.terraform.io/twingate/twingate v2.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    twingate = {
      source  = "Twingate/twingate"
      version = "~> 2.0"
    }
  }
}

provider "twingate" {
  api_token = "redacted"
  network   = "redacted"
}

variable "tcp_port_list" {
  default = ["80", "443"]
}

resource "twingate_resource" "twingate" {
  name              = "example"
  address           = "example.com"
  remote_network_id = "redacted"

  protocols = {
    tcp = length(var.tcp_port_list) == 0 ? { policy = "ALLOW_ALL" } : { policy = "RESTRICTED", ports = var.tcp_port_list }
  }
}
```

### Debug Output

[Debut output gist](https://gist.github.com/alexherington/751ba513782cac1f1edf0e80f385db2f)

### Expected Behavior

Terraform should've either planned successfully or thrown an error with a description.

### Actual Behavior

Terraform crashed, leaving the remote state locked.

### Steps to Reproduce

1. Replace relevant attributes
2. `terraform init`
3. `terraform plan`

### Additional Context

On line 25:
```terraform
tcp = length(var.tcp_port_list) == 0 ? { policy = "ALLOW_ALL" } : { policy = "RESTRICTED", ports = var.tcp_port_list }
```
If the true value is changed to `{ policy = "ALLOW_ALL", ports = [] }` the plan will be successful. Also setting the type of variable `tcp_port_list` to `list(string)` allows a successful plan.

I've done some limited resting using the AWS provider and haven't been able to reproduce the same issue.

**Comment by jbardin** [comment]
Hi @alexherington,

Thanks for filing the issue! There are two pieces causing trouble here. The first is that the type of the `tcp_port_list ` variable is not defined, so Terraform is not able to fully validate `tcp` expression statically. The workaround is pretty simple and improves the configuration anyway, add the type to the variable declaration:
```
variable "tcp_port_list" {
  type = list(string)
  default = ["80", "443"]
}
```

The actual crash is still a bug however, probably due to the encoding of what is an incompatible type resulting from the expression.

**Comment by jbardin** [comment]
We have an upstream fix here: https://github.com/zclconf/go-cty/pull/175, and can close this issue once we bump the dependency for an upcoming release.

**Comment by apparentlymart** [comment]
(While wearing `cty` maintainer hat)

I've merged the upstream fix to cty, in case you'd like to open a PR to upgrade Terraform's dependency.

---

(While wearing HashiCorp-employee-working-on-Terraform hat) 

I think this example configuration has a remaining problem that this upstream fix won't change: the two results from the conditional expression have different result types, and once `ports` is typed as a set of strings Terraform won't be able to find a single type that they can both convert to.

Assuming that the provider has typed this argument as a bunch of nested object types with optional attributes, the following should work as an alternative:

```hcl
    tcp = {
      policy = length(var.tcp_port_list) != 0 ? "RESTRICTED": "ALLOW_ALL"
      ports  = length(var.tcp_port_list) != 0 ? var.tcp_port_list : null
    }
```

Alternatively, if you don't want to duplicate the predicate about the collection length, you can include an explicit `null` assignment for `ports` so that both result types can agree on being an object type with those two attributes:

```hcl
    tcp = (
      length(var.tcp_port_list) == 0 ?
      { policy = "ALLOW_ALL", ports = null } :
      { policy = "RESTRICTED", ports = var.tcp_port_list }
    )
```

I wrapped it over multiple lines because I find that easier to read, but that's just a style thing and you can leave it all on one line if you want. The `ports = null` in the first result is the important thing here.
