### ISSUE TITLE
`fmt`: should optionally enforce quotations around resource type and name labels

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#34559]
### Terraform Version

```shell
n/a
```

### Use Cases

Today it is valid HCL to have unquoted strings for HCL resource type and name label. `terraform fmt` however applies quotes regardless. It would be nice for `fmt` to be configurable to enforce / fix quotes vs no quotes 

```hcl
resource resource_type name_label {}
```

`$ terraform fmt`

```hcl
resource "resource_type" "name_label" {}
```

`$ terraform fmt --no-quotes`

```hcl
resource resource_type name_label {}
```

### Attempted Solutions

n/a

### Proposal

see "use cases"

**Comment by apparentlymart** [comment]
Hi @drewmullen! Thanks for raising this.

The `terraform fmt` command is designed to enforce one specific set of style rules as a baseline for what had emerged as the "idiomatic style" back when it was introduced. It is intentionally not customizable, because that would be contrary to the goal of having a single idiomatic style. This also has an additional benefit that when Terraform is generating code itself (such as with `import` blocks) it can follow the one idiomatic style and thus be immediately consistent with existing codebases following that style, without having to inherit a wealth of customization options.

I understand that you have a personal preference to use a different style. You are of course welcome to use your own local style if you wish, but you will need to use a different tool (possibly written directly by you) to enforce that style, if you wish to do so. Custom style preferences are not in scope for the `terraform fmt` command.

What I've written above is stated in some different words in [the documentation for `terraform fmt`](https://developer.hashicorp.com/terraform/cli/commands/fmt), and is unlikely to change because the same design tradeoffs still hold.

Thanks!
