### ISSUE TITLE
cdktf init fails when using terraform cloud for state managment

### ISSUE THREAD

**Issue by razine-bensari** [hashicorp/terraform#34583]
### Terraform Version

```shell
CDKTF 0.20.2
```

### Terraform Configuration Files

N/A

### Debug Output

When I run the following command:

`cdktf init --template=go --providers=kreuzwerker/docker`

I get this:
<img width="1001" alt="Screenshot 2024-01-27 at 12 22 36 AM" src="https://github.com/hashicorp/terraform/assets/34013446/f2ce9731-8d55-4994-a0ca-255bc94e8234">

The standard input remains blocking. Even after the token was generated on the browser 

### Expected Behavior

There should be a way to input the token for the cdktf init using terraform cloud as the state management instead of local

### Actual Behavior

standard input is blocked

### Steps to Reproduce

`cdktf init --template=go --providers=kreuzwerker/docker `

**Comment by apparentlymart** [comment]
Hi @razine-bensari,

In this issue you seem to be describing a behavior that's part of CDK for Terraform, rather than of Terraform CLI/Core. 

Please report this issue in [the CDK for Terraform repository](https://github.com/hashicorp/terraform-cdk) instead. [The code that implements that behavior](https://github.com/hashicorp/terraform-cdk/blob/38fa7a0e296c597412a184dc1d779713806b6373/packages/cdktf-cli/src/bin/cmds/helper/terraform-login.ts#L12) is in that repository, so there isn't anything we could change in _this_ repository to improve the situation you've reported.

Thanks!

**Comment by razine-bensari** [comment]
> Hi @razine-bensari,
> 
> In this issue you seem to be describing a behavior that's part of CDK for Terraform, rather than of Terraform CLI/Core.
> 
> Please report this issue in [the CDK for Terraform repository](https://github.com/hashicorp/terraform-cdk) instead. [The code that implements that behavior](https://github.com/hashicorp/terraform-cdk/blob/38fa7a0e296c597412a184dc1d779713806b6373/packages/cdktf-cli/src/bin/cmds/helper/terraform-login.ts) is in that repository, so there isn't anything we could change in _this_ repository to improve the situation you've reported.
> 
> Thanks!

You are right!

Reported it in the correct repository and raised a fix as well. Thank you!
