### ISSUE TITLE
Terraform continues to create resources after error

### ISSUE THREAD

**Issue by panfiva** [hashicorp/terraform#34593]
### Terraform Version

```shell
Terraform v1.7.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.34.0

Your version of Terraform is out of date! The latest version
is 1.7.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

``` terraform
terraform {
  required_version = ">=1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.34.0"
    }
  }
}


provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

# -----------------------------------
# Create IGW
# -----------------------------------
resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.vpc.id

}

# -----------------------------------
# Read Availability Zones
# -----------------------------------
data "aws_availability_zones" "aws_availability_zone" {
  state = "available"
  filter {
    name   = "region-name"
    values = ["us-east-1"]
  }
}


resource "aws_subnet" "public" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.0.1.0/24"
  availability_zone = data.aws_availability_zones.aws_availability_zone.names[0]

  depends_on = [aws_internet_gateway.igw]
}


resource "aws_subnet" "private" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.0.2.0/24"
  availability_zone = data.aws_availability_zones.aws_availability_zone.names[0]
}

resource "aws_instance" "ec2_terminal" {
  ami           = data.aws_ami.server_image_22_04.id
  instance_type = "t2.small"

  # this is designed to fail, since ID is invalid
  network_interface {
    network_interface_id = "eni-02084ccf6827ceaaa"
    device_index         = 0
  }

  network_interface {
    network_interface_id = aws_network_interface.terminal_priv_int.id
    device_index         = 1
  }

  instance_initiated_shutdown_behavior = "terminate"
}

resource "aws_network_interface" "terminal_priv_int" {
  subnet_id         = aws_subnet.private.id
  source_dest_check = true
}

data "aws_ami" "server_image_22_04" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
}


resource "terraform_data" "delay" {
  provisioner "local-exec" {
    command = "sleep 25"
  }
  depends_on = [aws_subnet.public, aws_subnet.private]
}

resource "aws_subnet" "public_2" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.0.3.0/24"
  availability_zone = data.aws_availability_zones.aws_availability_zone.names[0]

  depends_on = [terraform_data.delay]
}



```

### Debug Output

https://gist.github.com/panfiva/7800e252820df21f79ac834d81a62c0a

### Expected Behavior

After EC2 creation aws_instance.ec2_terminal fails since eni-02084ccf6827ceaaa does not exist, error should be logged immediately, terraform should terminate.

```
Plan: 8 to add, 0 to change, 0 to destroy.
aws_vpc.vpc: Creating...
aws_vpc.vpc: Still creating... [10s elapsed]
aws_vpc.vpc: Creation complete after 12s [id=vpc-097bff71c4c794e30]
aws_internet_gateway.igw: Creating...
aws_subnet.private: Creating...
aws_internet_gateway.igw: Creation complete after 0s [id=igw-0153eb8bcf5deee2c]
aws_subnet.public: Creating...
aws_subnet.private: Creation complete after 0s [id=subnet-025bc41cf4f93db0b]
aws_network_interface.terminal_priv_int: Creating...
aws_subnet.public: Creation complete after 1s [id=subnet-063e8873c24341fb1]
terraform_data.delay: Creating...
terraform_data.delay: Provisioning with 'local-exec'...
terraform_data.delay (local-exec): Executing: ["/bin/sh" "-c" "sleep 25"]
aws_network_interface.terminal_priv_int: Creation complete after 1s [id=eni-046d6a7ed57851372]
aws_instance.ec2_terminal: Creating...
terraform_data.delay: Still creating... [10s elapsed]
terraform_data.delay: Still creating... [20s elapsed]
terraform_data.delay: Creation complete after 25s [id=840805e7-0ef5-3fb7-cfdb-36b7ef58ea2a]
aws_subnet.public_2: Creating...
aws_subnet.public_2: Creation complete after 0s [id=subnet-022846d12f470e2e4]
╷
│ Error: creating EC2 Instance: InvalidNetworkInterfaceID.NotFound: The networkInterface ID 'eni-02084ccf6827ceaaa' does not exist
│       status code: 400, request id: d5016b19-8885-46a9-adb4-655da703ac11
│ 
│   with aws_instance.ec2_terminal,
│   on test.tf line 57, in resource "aws_instance" "ec2_terminal":
│   57: resource "aws_instance" "ec2_terminal" {
│ 
╵
```

### Actual Behavior

terraform does not immediately logs an error; instead, it waits till currently-building resources (`terraform_data.delay`) are created.

After that, terraform starts building other resources that have not yet executed (`aws_subnet.public_2: Creating`)

Only after all resources finished creating, terraform exits with error message

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

To trigger error, we used a network interface with a hard-coded ID that no longer exists.

```
  network_interface {
    network_interface_id = "eni-02084ccf6827ceaaa"
    device_index         = 0
  }
 ```

This mimics what we see in production -  terraform frequently fails to create EC2 as it fails to find `aws_terform_interface` objects it created right before ec2 provisioning. I suspect this issue is caused by some latencies that exist in AWS - resources report as created, however not visible in AWS APIs (https://github.com/hashicorp/terraform-provider-aws/issues/35568)

**Comment by jbardin** [comment]
Hi @panfiva,

Terraform appears to be working as designed here. When the `aws_instance` fails, Terraform will halt process all downstream resources. In your configuration however, there are no references to `aws_instance.ec2_terminal`, so there there are no other side effects from the resource creation failing. All the other resources actions are already in-process, and need to be completed to not lose track of the instance data. If Terraform were to abort immediately, it would orphan some number of the other resources, leaving no way for it to recover or delete them later, forcing you to manually find and remove them through the AWS console or API.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by jbardin** [comment]
@panfiva, a resource failing is not necessarily a fatal error across the entire configuration. Resources which have pending changes that are not dependent on the failure can proceed, and are expected to be completed per the plan, as Terraform's goal is apply as much of the desired system state as possible. Some configurations may be worse off trying to abort everything else, than if they ran to completion with only the failed resource being tainted (perhaps the changes are expected to be run as a single group, perhaps the setup for these operations is extremely time consuming, there are other possibilities). In your case, the the configuration has no relationship between `aws_instance.ec2_terminal` and `aws_subnet.public_2`, and Terraform cannot assume a relationship so applies the latter because the application of the changes may be required for entirely different reasons.

Either way, this is how Terraform was designed, and it's working as such, so it does not represent a bug. It's possible we could fashion this into an enhancement request, maybe something like "fail as quickly as possible"? It's not guaranteed to prevent other changes from completing of course, but could theoretically stop later changes in some cases. This wouldn't be expected in most production uses of Terraform, but perhaps for development and testing it could be worthwhile?
