### ISSUE TITLE
terraform_data output unclear

### ISSUE THREAD

**Issue by atamgp** [hashicorp/terraform#34597]
### Terraform Version

```shell
1.7.x
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/resources/terraform-data#output

### What is the docs issue?

Is is unclear to me what is usability of terraform_data output is.

Is it mere a looping of the provided input or is it possible to generate output for usage in other resources, this would be very usefull and an example would be appreciated (could not find one)

**Comment by jbardin** [comment]
Thanks @atamgp!

I'm not sure exactly what to put in there, as it's not a feature you normally would ned to use. There is no canonical example, because it shouldn't need to be used, and only comes up when trying to work around a misbehavior resource of some sort, or maybe to create a minimal reproducible example to display some other combination of behaviors.

The description may be short, but it is accurate. The `output` attribute reflects the `input` attribute, and is `unknown` during the initial plan (and IIRC the documentation writers reduced the wording from the draft to make it as succinct as possible). We could probably add a few words about how it would be unknown when `input` is changed as well, which may help clarify things, but the `input`+`output` attributes will tend to be a kind of "you'll know when you need it" feature.

**Comment by atamgp** [comment]
So there is no way from within a local-exec provisioner to alter the output?

**Comment by atamgp** [comment]
thanks, I will close this
