### ISSUE TITLE
comparisons in assertions could attempt to match types automatically

### ISSUE THREAD

**Issue by andrew-sweet-db** [hashicorp/terraform#34652]
### Terraform Version

```shell
Terraform v1.7.3
on windows_amd64
```

### Terraform Configuration Files

**main.tf**
```terraform
output "foo" {
  value = []
}

output "bar" {
  value = compact([])
}
```

**test.tftest.hcl**
```terraform
run "test" {
  assert {
    condition = output.foo == []
    error_message = "foo != []"
  }

  assert {
    condition     = output.foo == compact([])
    error_message = "foo != compact([])"
  }

  assert {
    condition = output.bar == []
    error_message = "bar != []"
  }

  assert {
    condition     = output.bar == compact([])
    error_message = "bar != compact([])"
  }
}
```

### Debug Output

Unable to provide via gist, sorry. Standard error.output:
```
$ terraform test
test.tftest.hcl... in progress
  run "test"... fail
╷
│ Error: Test assertion failed
│
│   on test.tftest.hcl line 8, in run "test":
│    8:     condition     = output.foo == compact([])
│     ├────────────────
│     │ output.foo is empty tuple
│
│ foo != compact([])
╵
╷
│ Error: Test assertion failed
│
│   on test.tftest.hcl line 13, in run "test":
│   13:     condition = output.bar == []
│     ├────────────────
│     │ output.bar is empty list of string
│
│ bar != []
╵
test.tftest.hcl... tearing down
test.tftest.hcl... fail

Failure! 0 passed, 1 failed.

```

### Expected Behavior

All assertions should pass.

### Actual Behavior

Two assertions fail. The error message indicates that the internal type checking is differentiating between and empty tuple and empty list of string.

### Steps to Reproduce

terraform test

### Additional Context

I am not aware of a way as a condition author that can specify a empty tuple as opposed to an empty list of string - the only available literal is ```[]```.

**Comment by liamcervante** [comment]
Hi @andrew-sweet-db, thanks for filing this.

Just a quick note, this isn't specific to the testing framework. I think all assertions including input validations, and pre- and post-conditions will also behave in the same way as you've highlighted here.

A potential workaround here would be to use the [`length` function](https://developer.hashicorp.com/terraform/language/functions/length) to check for emptyness instead of building an empty collection. For example:

```
  assert {
    condition     = length(output.bar) == 0
    error_message = "bar is not empty"
  }
```

I'm going to tweak the title of this issue, and mark it as an enhancement instead of a bug. This is an example of some missing functionality, rather than Terraform not behaving as documented.

Thanks!

**Comment by jbardin** [comment]
Yes, this is a deliberate choice of the type language, dissimilar types are never compared as equal, and should not be compared to one another. Checking the length of the collection is the correct usage. We already have an existing request for this here: #31439, and other similar requests like #34018
