### ISSUE TITLE
running terraform plan in windows 10 pro but shows unsupported platform error User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.

### ISSUE THREAD

**Issue by XiaoYue2-22** [hashicorp/terraform#34733]
### Terraform Version

```shell
Any version


azure-cli 2.57.0

core 2.57.0
telemetry 1.1.0

Dependencies:
msal 1.26.0
azure-mgmt-resource 23.1.0b2


Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\usernametest.azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec 4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

### Terraform Configuration Files

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      # Root module should specify the maximum provider version
      # The ~> operator is a convenient shorthand for allowing only patch releases within a specific minor release.
      version = "3.68.0"
    }
  }
}    

provider "azurerm" {
  subscription_id = "***"
  tenant_id       = "***"
  features {}
}

### Debug Output

running terraform plan in windows 10 pro but shows unsupported platform error
C:\test>terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors. Trace ID: 37aa6e06-04c6-4059-bc87-8e9f87137300 Correlation ID: 1779b0de-6ac2-44d5-b97a-64f69d477f3d Timestamp: 2024-02-26 09:09:47Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com/.default
│
│ with provider["registry.terraform.io/hashicorp/azurerm"],
│ on providers.tf line 12, in provider "azurerm":
│ 12: provider "azurerm" {

### Expected Behavior

should be success

### Actual Behavior

│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors. Trace ID: 37aa6e06-04c6-4059-bc87-8e9f87137300 Correlation ID: 1779b0de-6ac2-44d5-b97a-64f69d477f3d Timestamp: 2024-02-26 09:09:47Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com/.default
│
│ with provider["registry.terraform.io/hashicorp/azurerm"],
│ on providers.tf line 12, in provider "azurerm":
│ 12: provider "azurerm" {

### Steps to Reproduce

just run terraform plan in virtual machine with version windows pro 10

### Additional Context

n/a

### References

n/a

**Comment by liamcervante** [comment]
Hi @XiaoYue2-22, thanks for filing this! It looks like the error message you are seeing is originating from the Azure CLI rather than Terraform itself. Does running the Azure CLI directly on your VM work, or are you only seeing this error message when it is executed through Terraform?

 I notice the error message you have to run `az login` interactively, there's more information about authenticating with azure via the CLI here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli. It looks like you have to login manually first, before Terraform can execute without any additional credentials.

**Comment by XiaoYue2-22** [comment]
Hello @liamcervante , Azure CLI works for me when I execute az login, I did login from web browser, after this, I tried command terraform plan, it shows like this

**Comment by liamcervante** [comment]
Thanks @XiaoYue2-22!

Sorry for bouncing you around but since the Terraform providers are managed in separate repositories, I think you'll probably get more accurate help by posting either into our [discussion forums](https://discuss.hashicorp.com/tags/c/terraform-providers/31/azure) or raising this as a bug directly within the `azurerm` repository: https://github.com/hashicorp/terraform-provider-azurerm. 

As such, I will close the issue here and you can reopen directly with our azure team.

Thanks!

**Comment by XiaoYue2-22** [comment]
sure, thanks!
