### ISSUE TITLE
Specify more clearly in for expressions ordering in set(!=string)

### ISSUE THREAD

**Issue by dancer1325** [hashicorp/terraform#34739]
### Terraform Version

```shell
Terraform v1.3.9
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/expressions/for#element-ordering

It also applie to new and older versions. _Example:_ https://developer.hashicorp.com/terraform/language/v1.1.x/expressions/for#element-ordering

### What is the docs issue?

It's prety vague the commentary

> For sets of other types, Terraform uses an arbitrary ordering that may change in future versions of Terraform.

* Is that ordering algorithm in these cases changing frequently?
* Why couldn't we indicate precisely how it works?
* Based on commentary, it's assumed to expect different results, even based on execution?

### Proposal

I am not fammiliarized with the code of `for`expressions, but I would like to get something in the documentation or remove this commentary

**Comment by apparentlymart** [comment]
Hi @dancer1325,

The intention of this documentation is specifically to say that you should not rely on the ordering, and that changes to it will not be considered as a breaking change. The effective ordering is a side-effect of how sets are stored in memory, but that is at a level of abstraction far beneath how the Terraform language is specified.

I don't expect that we would say anything more specific here because that would effectively freeze the current implementation of sets, and thus prevent future optimization work and possibly new features that cause Terraform to need to track additional information about values that would be relevant to the question if set membership.

If you have a situation where ordering is significant, then list types are the appropriate data type to use.

**Comment by crw** [comment]
Per the above, I am going to close this issue. Please feel free to respond and also let me know if this issue has been closed in error or prematurely. Thanks!

**Comment by dancer1325** [comment]
Thanks @apparentlymart for the fast reply !! 🚀  https://github.com/hashicorp/terraform/issues/34739#issuecomment-1967583258

@crw , fine for me to close
