### ISSUE TITLE
Using .json in terraform test causes an issue with aws mock provider

### ISSUE THREAD

**Issue by ramongalate** [hashicorp/terraform#34764]
### Terraform Version

```shell
Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```
NDA

### Debug Output

NDA

### Expected Behavior

when using terraform test I expected  it to be able to create data sources that are properly created, even with overriding data didn't help either

### Actual Behavior

When i define a data source:
```
data "aws_iam_policy_document" "lambda_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}
```
then use it with .json, i get several invalid characters like below:
```
│ Error: "assume_role_policy" contains an invalid JSON: invalid character '3' after top-level value
│ 
│   with <redacted>,
│   on modules/lambda/main.tf line 46, in resource "aws_iam_role" "lambda_role":
│   46:   assume_role_policy = data.aws_iam_policy_document.lambda_assume_role_policy.json
```

### Steps to Reproduce

create a data resource in terraform for a mock aws provider 

then terraform init and test

**Comment by apparentlymart** [comment]
Hi @ramongalate! Thanks for reporting this.

My first instinct was to say that this is an AWS provider issue because you are describing the behavior of one of that provider's resource types, but you also mentioned "_mock_ aws provider", so I'd like to understand more about what you're doing here.

Are you talking about provider mocking in the sense of the `terraform test` command and its test scenario language? If so, it would be helpful to share your `.tftest.hcl` file to illustrate how you've configured the mock value for this provider. It seems like it's not configured to return valid JSON, and so the provider's validation rules are correctly rejecting the assigned value. I'd like to understand more about _why_ it isn't valid JSON, but if you are mocking the provider then it's your mock configuration that would be deciding what that value should be.

**Comment by ramongalate** [comment]
Hi @apparentlymart ,

I create the mock provider for our main.tf file to use 
```
mock_provider "aws" { 
}

mock_provider "aws" { 
  alias               = "replica"
}

mock_provider "aws" { 
  alias               = "us-east-1"
}


variables{
...define the variables to use
}
```
then it would try to create this:
```
resource "aws_iam_role" "lambda_role" {
  name               = "${var.name}_lambda_role"
  path               = "/${var.name}/"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role_policy.json
  tags               = var.tags
}

data "aws_iam_policy_document" "lambda_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}
```
I have tried to also override the data and resource values for the json encoding of the data object and resource, which gives also the same error:
```

mock_provider "aws" { 
  override_data {
    target = module.signer.data.aws_iam_policy_document.lambda_assume_role_policy.json
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
  override_resource {
    target = module.signer.aws_iam_role.lambda_role
    values = {
      assume_role_policy       = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
}

mock_provider "aws" { 
  alias               = "replica"
  override_data {
    target = module.signer.data.aws_iam_policy_document.lambda_assume_role_policy
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
  override_resource {
    target = module.signer.aws_iam_role.lambda_role
    values = {
      assume_role_policy       = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
}

mock_provider "aws" { 
  alias               = "us-east-1"
  override_data {
    target = module.signer.data.aws_iam_policy_document.lambda_assume_role_policy
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
  override_resource {
    target = module.signer.aws_iam_role.lambda_role
    values = {
      assume_role_policy       = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
}
```

**Comment by liamcervante** [comment]
Hi @ramongalate, thanks for filing this.

The approach in your second comment is the right thing to do here, but I see a small typo that is probably causing problems for you.

Firstly, you only need to override the data block and not the `aws_iam_role` resource. The mock providers and override blocks will only populate computed attributes, so setting the `assume_role_policy` on the resource via the testing framework won't have any affect as that value is expected to be provided in the configuration.

So, the only thing you need to override in this particular case is the `aws_iam_policy_document` data source. In your main (non-aliased) provider you have an additional `.json` suffix at the end of your target address which means the override isn't targeting the data source and so that particular override block isn't being applied. I think the following should work for you:

```hcl
mock_provider "aws" { 
  override_data {
    target = module.signer.data.aws_iam_policy_document.lambda_assume_role_policy
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  }
}
```

There is still a bug in here, in that Terraform should know that the target address you provided is invalid and could have provided an error for you pointing that out. Interestingly enough, I've discovered it does provide an error for you if the target address is targeting something in the root module but that behaviour seems to be lost when child modules are being targeted.

I'll leave this open and look into improving that error message. Hopefully, the override blocks work for you once the target address is fixed. If not, please let me know and I can keep investigating.

**Comment by ramongalate** [comment]
Hi @liamcervante, the issue was indeed in my code, but the .json was a typo I made here.

The actual problem was that i reused the same module with the data source, so I had to make several override_data statements so that every usage of the module was encompassed. From the error it only mentioned the file source, but in the code I had to override all the module instances.

```terraform 
mock_provider "aws" {
  
  override_data {
    target = module.migrator.data.aws_iam_policy_document.lambda_assume_role_policy
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  } 
  override_data {
    target = module.signer.data.aws_iam_policy_document.lambda_assume_role_policy
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Effect\":\"Allow\",\"Sid\":\"\"}]}"
    }
  } 
```

Thank you for all your help and a great feature addition!

**Comment by ramongalate** [comment]
Hi @liamcervante,

I just came across an issue that left me really stumped in the testing framework:

When defining resources with for each like 
```
resource "aws_acm_certificate" "crl_cert" {
  provider                  = aws.us-east-1
  domain_name               = "crl.${var.external_domain_name}"
  validation_method         = "DNS"
  subject_alternative_names = ["cps.${var.external_domain_name}", "repository.${var.external_domain_name}"]
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "crl_cert_validation" {
  provider = aws.us-east-1
  for_each = {
    for dvo in aws_acm_certificate.crl_cert.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 30
  type            = each.value.type
  zone_id         = var.external_hosted_zone_id
}
```

it gives errors like :

```
 Error: Invalid for_each argument
│ 
│   on main.tf line 593, in resource "aws_route53_record" "crl_cert_validation":
│  593:   for_each = {
│  594:     for dvo in aws_acm_certificate.crl_cert.domain_validation_options : dvo.domain_name => {
│  595:       name   = dvo.resource_record_name
│  596:       record = dvo.resource_record_value
│  597:       type   = dvo.resource_record_type
│  598:     }
│  599:   }
│     ├────────────────
│     │ aws_acm_certificate.crl_cert.domain_validation_options is a set of object, known only after apply
│ 
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
│ 
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and place apply-time results only in the map values.
│ 
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.
```

I tried to fix it with overriding the resource : 

```
  # crl cert validation
  override_resource {
    target = aws_acm_certificate.crl_cert
    values = {
      domain_validation_options = [
        {
          domain_name           = "domain.com"
          resource_record_name  = "_somehash.domain.com"
          resource_record_type  = "CNAME"
          resource_record_value = "SOME_LONG_STRING.acm-validations.aws."
        }
      ]
    }
  }
```

but it doesn't really work.

Since the documentation doesn't have any examples of how to use override_resource, i don't actually know if it was an issue caused by me or an unthought of interaction.

**Comment by liamcervante** [comment]
Hi @ramongalate, this is an unfortunate collision of multiple different circumstances stemming both from limitations in the mock providers and limitations within the `for_each` attribute itself. 

Apologies for the long comment. Firstly, I wanted to include some context and background so you understand the underlying behaviour. I do have a specific workaround that might work, for which you can skip to right at the end.

The way the mock providers work is by always returning simple `(known after apply)` values during the planning stage for all computed attributes, and then populating those values during the apply operation. Unfortunately, this is true even if you have provided a value for the computed attributes - it still doesn't include that value until the apply stage. So overriding the values doesn't prevent this specific error.

The specific error you are seeing here is a [known issue](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#limitations-on-values-used-in-for_each) in Terraform when using `(known after apply)` values with `count` and `for_each` attributes. 

That you would see it here is a result of differences in behaviour between the mock provider and the real provider. In this particular case, the real provider would not return an unknown value for the `domain_validation_options` attribute during the plan while the mock provider is. This is why you are seeing this behaviour now while testing with the mock provider, and likely wouldn't have seen it before using the real provider. Unfortunately, we don't have a way for the mock providers to know how a given provider does respond to certain computed attributes during planning so we default to the chosen approach (returning `(known after apply)`) which is wrong/different in this specific case. Potentially, there's a feature request in here somewhere that we could allow users to tell the mocks and overrides which way to behave but there's nothing we can do about it right now.

A potential workaround would be for you to create a run block that selectively creates the `aws_acm_certificate` first, then the computed attributes (either overridden or automatically created by the mock provider) would be known during the planning stage of subsequent run blocks:

```hcl
# This run block will create the required aws_acm_certificate without 
# creating any other infrastructure.
run "create_acm_certificate" {
  plan_options {
    target = [
      aws_acm_certificate.crl_cert
    ]
  }
}

# This run block can now create the aws_route53_record resources
# as the domain_validation_options are concretely known.
run "do_the_real_test" {
  # Your tests go in here.
}
```

I know the above isn't great as it's not representative of the way your configuration will be applied in real life, but depending on what you're trying to test this could allow you to execute that particular part of your configuration.

There's an action item for me in here to raise this with my product manager to see if we can introduce the behaviour switch I mentioned above. This would allow you to say that for this particular overridden resource it return all the information it has as early as possible instead of holding it back until the apply stage. This isn't something that will arrive particularly quickly though.

Hopefully that all makes sense to you!

**Comment by ramongalate** [comment]
Hey @liamcervante , thanks for the kind explanation. It makes much more sense now!

Im going to try and make it work for this particular use case. Since this part of the code isn't really the part I wish to test, it shouldn't pose an issue.

Thanks again!
