### ISSUE TITLE
Missing function parameter name produces error indicating function does not exist

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/terraform#34777]
### Terraform Version

```shell
Terraform v1.8.0-dev
on darwin_arm64

(built with v1.8.0-alpha20240228)
```

### Terraform Configuration Files

N/A

### Debug Output

https://gist.github.com/bendbennett/06fd39fb973276f979c016f072fa3329

### Expected Behavior

Expected an error indicating that the name for a function parameter was missing.

### Actual Behavior

```shell
=== RUN   TestAccV6FunctionBool
    function_bool_test.go:17: Step 1/1 error: Error running pre-apply plan: exit status 1
        
        Error: Unknown provider function
        
          on terraform_plugin_test.tf line 13, in output "test":
          13:                                   value = provider::corner::bool(true)
        
        There is no function named "provider::corner::bool". Ensure that provider
        name "corner" is declared in this module's required_providers block, and that
        this provider offers a function named "bool".
```

### Steps to Reproduce

The following is taken from [terraform-provider-corner](https://github.com/hashicorp/terraform-provider-corner/pull/210#discussion_r1474322835).

This test will generate the `Unknown provider function` described.
Uncommenting `//Name: "param",` resolves this issue.

```go
func TestAccV6FunctionBool(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			//tfversion.SkipBelow(tfversion.Version1_8_0),
		},
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			//nolint:unparam // False positive in unparam related to map: https://github.com/mvdan/unparam/issues/40
			"corner": func() (tfprotov6.ProviderServer, error) {
				return Server(), nil
			},
		},
		Steps: []resource.TestStep{
			{
				Config: `
				output "test" {
					value = provider::corner::bool(true)
				}`,
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownOutputValue("test", knownvalue.Bool(true)),
				},
			},
		},
	})
}

func Server() tfprotov6.ProviderServer {
	return &server{
		functions: map[string]*tfprotov6.Function{
			"bool": {
				Parameters: []*tfprotov6.FunctionParameter{
					{
						//Name: "param",
						Type: tftypes.Bool,
					},
				},
				Return: &tfprotov6.FunctionReturn{
					Type: tftypes.Bool,
				},
			},
		},
		functionRouter: functionRouter{
			"bool": functionBool{},
		},
	}
}
```

### References

- hashicorp/terraform-provider-corner#210

**Comment by jbardin** [comment]
@bendbennett, I think you may be inadvertently running a different version of Terraform than what's on `main`. I get the same `Failed to load plugin schemas` error with a local test, and when running the provider unit tests, with the text _function "bool" declares invalid name "" for parameter 0_.

Even running alpha20240228 however should still work, since that error check has been there the whole time, so I'm not sure where this is failing for you yet.

**Comment by jbardin** [comment]
Found it! I think the test runs `validate` first in isolation even though it will be run again a the start of the next steps. That `validate` call appears to load the provider through a different path that bypasses the schema checks. Will investigate ...

**Comment by jbardin** [comment]
OK, turns out we catch this in most situations situations because the early `Input` action loads all the schemas. If cli input is disabled, then we are still likely to catch it again when loading the schemas for resources. If there are no resources, and we're not looking for input, then the function schema isn't loaded until the very last moment when there is no chance to catch the error, because it was assumed that it must have been loaded previously.

**Comment by bendbennett** [comment]
Thanks for diving into this and providing the extra context and clarification James, much appreciated.
