### ISSUE TITLE
Set the default registry URL

### ISSUE THREAD

**Issue by sgorshkov85** [hashicorp/terraform#34862]
### Terraform Version

```shell
1.5.7
```

### Use Cases

We want to deploy our infrastructure resources on the workers without access to public resources such as external provider registries(e.q. https://registry.terraform.io/) and external modules. For such needs, we deployed a cache repository: local-registry.ourcompany.com
Updating the required_providers for each module is not an option because some modules depend on other external modules where versions.tf files cannot be changed.

### Attempted Solutions

1. Use a terragrunt generator to make a temporary version.tf file with a valid source URL. It doesn't work for modules with submodules
2. Tried to configure https://opentofu.org/docs/cli/config/config-file/#provider-installation
`provider_installation { network_mirror { url = "https://local-registry.ourcompany.com/" include = ["hashicorp/*"] } direct { exclude = ["hashicorp/*"] }  }  disable_checkpoint = true`
It doesn't work because our cache uses https://developer.hashicorp.com/terraform/internals/v1.5.x/remote-service-discovery and the local config file should point to the provider registry with https://developer.hashicorp.com/terraform/internals/v1.5.x/provider-network-mirror-protocol configured.
I might lose something. It could be a way to set/override the default registry URL.

### Proposal

Please add the possibility of setting the default registry URL via an environment variable or CLI parameter.

**Comment by apparentlymart** [comment]
Hi @sgorshkov85,

The network mirror protocol is indeed the way to meet this use-case. It allows you to host providers in a secondary location _without_ changing what namespace they belong to.

You've deployed a separate registry rather than a mirror. A registry can only host providers in its own namespace. You should deploy a provider mirror instead, which will then allow you to act as an alternative source for providers which belong to other registry namespaces, including `registry.terraform.io`.

**Comment by crw** [comment]
Please let us know if you need more help with this question. It may also be helpful to leverage [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by sgorshkov85** [comment]
Hi @apparentlymart, 
 As for me changing the default URL will be the easiest way to solve such an issue. 
 **registry.terraform.io/hashicorp/aws -> local-registry.ourcompany.com/hashicorp/aws**
  
  It looks like this: 

 ` required_providers {
 aws =
{ source = "local-registry.ourcompany.com/hashicorp/aws" } 
}`

 For some reason(I am not a developer) the registry URL is hardcoded. Example:
https://github.com/hashicorp/terraform/blob/eecbfbf2cccedfb581469ee63599c4b4abc5c60f/internal/registry/regsrc/regsrc.go#L10  
 
 If I understand [the documentation](https://developer.hashicorp.com/terraform/internals/v1.5.x/provider-network-mirror-protocol) correctly - this implementation requires configuring the network mirror host. 
 As for me, it makes sense if:
 1. We manage our custom providers
 2. The providers as any artifact should be scanned for vulnerabilities
 
  The official Hashicorp registry is a trusted source, so the requirements mentioned above are irrelevant.

**Comment by apparentlymart** [comment]
The important detail here is that Terraform uses these hostnames both as a "direct" physical location (which registry to ask if there's no mirrors specified) and as an identifier for a namespace.

When a module declares that it depends on `foo/bar`, that's documented as being a shorthand for _the identifier_ `registry.terraform.io/foo/bar`.

"Provider mirrors" are Terraform's mechanism for hosting a provider in a different place than the registry that owns its namespace. That allows you to change where a provider comes from without changing its unique identfier.

Preserving the unique identifiers is important because if one module declares that it depends on `foo/bar` while another module declares that it depends on `registry.terraform.io/foo/bar` then they must be treated as depending on the same provider, because that's how the provider address syntax has always been defined and existing modules are allowed to rely on that.

If you want to host providers that belong to someone else's namespace on your own server, then you should implement a provider mirror.
