### ISSUE TITLE
Adding resource dependencies when updating, prunes references

### ISSUE THREAD

**Issue by jacobbednarz** [hashicorp/terraform#34861]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.2.2
```

### Terraform Configuration Files

<details open><summary>initial configuration</summary>

```terraform
resource "null_resource" "example_1" {
  provisioner "local-exec" {
    command = "echo 1"
  }
}
```

</details>

<details open><summary>second configuration</summary>

```terraform
resource "null_resource" "example_1" {
  provisioner "local-exec" {
    command = "echo 1 ${null_resource.example_2.id}"
  }
}

resource "null_resource" "example_2" {
  provisioner "local-exec" {
    command = "echo 2"
  }
}
```

</details>

### Debug Output

initial run - https://gist.github.com/jacobbednarz/74fc51f45d0ba1dfc0d79fe0b3129ddd#file-initial-log
second run - https://gist.github.com/jacobbednarz/74fc51f45d0ba1dfc0d79fe0b3129ddd#file-second-log

### Expected Behavior

Terraform should walk the graph as it already correctly does but create/update the resources needed to resolve new references in order to use their values.

### Actual Behavior

Terraform walks the graph but prunes resources that were referenced as part of the update as they do not exist in state.

### Steps to Reproduce

- create a terraform file locally with the contents of `initial configuration`
- `terraform apply`
- update your terraform file locally with the contents of `second configuration`
- terraform apply
- notice that only the new resource is created, nothing is shown as updated despite the references changing, Terraform sees the new dependency and the debug logs call out that references are pruned (snipped from `second.log`).

```
[DEBUG] ProviderTransformer: "null_resource.example_1 (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/hashicorp/null"]
[DEBUG] ProviderTransformer: "null_resource.example_2 (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/hashicorp/null"]
[DEBUG] ReferenceTransformer: "null_resource.example_1 (expand)" references: [null_resource.example_2 (expand)]
[DEBUG] ReferenceTransformer: "null_resource.example_2 (expand)" references: []
[DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/hashicorp/null\"]" references: []
[DEBUG] Starting graph walk: walkPlan
[DEBUG] created provider logger: level=debug
...
[DEBUG] Resource instance state not found for node "null_resource.example_2", instance null_resource.example_2
[DEBUG] ReferenceTransformer: "null_resource.example_2" references: []
[DEBUG] refresh: null_resource.example_2: no state, so not refreshing
```

### Additional Context

While I've demonstrated it with the `null_resource` provider here, this is a problem in other providers (such as the Cloudflare provider, that I maintain) where a resource will be updated between runs with an attribute that references another resource and ends up being silently dropped resulting in needing to run the `apply` operations twice to get the desired state.

**Comment by jbardin** [comment]
Hi @jacobbednarz,

The output from the logs doesn't have enough detail to see all of the dependencies, but the trace logs will show there is an edge from `example_1` to `example_2`. Since there is no change to `example_1`, there just isn't anything to show in the output. This is working as designed, but did you have a more complex example perhaps which was not working?

Thanks!

**Comment by apparentlymart** [comment]
I sense that this issue represents a misunderstanding of how provisioners behave. Provisioners are, by default, run only during the creation of an object. You can optionally set `when = destroy` to configure a provisioner that happens when an object is being destroyed. There is not currently any such thing as an "update-time provisioner".

Should we interpret this issue as a feature request for some way to run arbitrary commands during the update action for a resource? It seems like there's also an implied requirement that it run even when the resource _isn't_ being updated, which means that there needs to be some other rule for deciding when to run it, but we can discuss that further if I'm on the right track about what you are asking about.

**Comment by jacobbednarz** [comment]
thanks for the details here @jbardin and @apparentlymart - apologies on the bum steer here, it's not necessarily related to provisioners but was instead intended to have a minimal demonstration. i thought it was a good repro but perhaps more confusing than helpful, sorry!

the problem i'm attempting to demonstrate here is present in the Cloudflare provider. 

<details open><summary>initial configuration</summary>

```terraform
resource "cloudflare_access_group" "warp_enforcement" {
  account_id = var.account_id
  name       = "Warp Enforcement"

  include {
    auth_method = "swk"
  }

  require {
    external_evaluation {
      evaluate_url = "https://example.com"
      keys_url     = "https://example.com/keys"
    }
  }
}
```
</summary>

- run `terraform apply`
- initial trace: https://gist.github.com/jacobbednarz/05d74d4571f9d78d6a7bfd7504708a0f#file-initial_trace-log

<details open><summary>second configuration</summary>

```terraform
resource "cloudflare_access_group" "warp_enforcement" {
  account_id = var.account_id
  name       = "Warp Enforcement"

  include {
    auth_method = "swk"
  }

  require {
    external_evaluation {
      evaluate_url = "https://example.com"
      keys_url     = "https://example.com/keys"
    }
    device_posture = [cloudflare_device_posture_rule.warp.id]
  }
}

resource "cloudflare_device_posture_rule" "warp" {
  account_id = var.account_id
  type       = "warp"
  name       = "Warp"
}
```
</summary>

noting the diff between the first and second runs

```diff
  resource "cloudflare_access_group" "warp_enforcement" {
    account_id = var.account_id
    name       = "Warp Enforcement"

    include {
      auth_method = "swk"
    }

    require {
      external_evaluation {
        evaluate_url = "https://example.com"
        keys_url     = "https://example.com/keys"
      }
+      device_posture = [cloudflare_device_posture_rule.warp.id]
    }
  }

+  resource "cloudflare_device_posture_rule" "warp" {
+    account_id = var.account_id
+    type       = "warp"
+    name       = "Warp"
+  }
```

- run `terraform apply`
- secondary trace: https://gist.github.com/jacobbednarz/05d74d4571f9d78d6a7bfd7504708a0f#file-secondary_trace-log

to reiterate, my expectation is the Terraform would notice the change in `cloudflare_access_group` and see it has a dependency on `cloudflare_device_posture_rule` and evaluate that first.

**Comment by jbardin** [comment]
Thanks @jacobbednarz,

In the trace output you can see the plan contains warnings about the `warp_enforcement` resource:

```
WARN]  Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for cloudflare_access_group.warp_enforcement, but we are tolerating it because it is using the legacy plugin SDK.
...
```
which contains incorrectly planned attributes for the `require` block object. This means that the provider is overwriting your changes in the plan, which is what is causing the confusion here.

This is an issue which should be filed directly with the provider. It is however not easy to work around these limitations in the legacy SDK, and will probably need to wait until they can update the resources to the new provider framework.

Thanks!

**Comment by jacobbednarz** [comment]
As the provider maintainer, what tooling or debugging is needed to dig further into this one and identify specifically what is wrong with the plan? "produced an invalid plan" has become a bit of a catch all for idiosyncrasies in SDKv2 and it's just the norm so I largely ignore these now (for better or worse). 

If the solution is to migrate to the framework plugin, we can definitely explore that but I would like to ensure there isn't anything here that I'm missing before going down that route.

**Comment by jbardin** [comment]
Oh, I can try to add more detail here! In short, Terraform is obligated to follow the plan returned by the provider, and the provider isn't returning the change in the plan. You can see immediately after the error terraform writes `recorded NoOp change for cloudflare_access_group.warp_enforcement`

The error details could be a little confusing here, because the `device_posture` is the an attribute which is _not_ mentioned in the error, and I think that's because it is actually the only attribute which is technically valid! A provider can choose to keep the prior value of an attribute if it determines the change makes no meaningful difference (see https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md, and I think the framework user docs have more words written about this but don't have the links handy). So the error itself is not indicative of the problem, the same result could be generated without error, but it is an easy red flag to search for when dealing with the SDK.

Looking at your schema this is not part of a computed attribute or object, I'm not sure exactly what is going wrong, but I have a feeling it's related to the `unknown` value passed in which was not handled consistently within the SDK. That you could test by simply putting a static new value in `device_posture` and see if it shows up in the plan. You may be able to record what is happening within a `CustomizeDiffFunc` (in the SDK terminology), and if not at least make more sense of the problem, you have the option to write back a more correct plan in place of what the SDK returned.

**Comment by apparentlymart** [comment]
Indeed, this particular warning is a warning specifically _because_ Terraform can't reliably distinguish between incorrect provider behavior or incorrect SDK behavior for the legacy SDK, and so unfortunately it takes some closer examination, and unfortunately also some experience, to distinguish the two.

Let's examine the full warning:

```
2024-03-20T08:27:32.380+1100 [WARN]  Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for cloudflare_access_group.warp_enforcement, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .include[0].group: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].ip_list: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].everyone: planned value cty.False for a non-computed attribute
      - .include[0].email: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].ip: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].login_method: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].certificate: planned value cty.False for a non-computed attribute
      - .include[0].device_posture: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].common_name: planned value cty.StringVal("") for a non-computed attribute
      - .include[0].geo: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].service_token: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .include[0].any_valid_service_token: planned value cty.False for a non-computed attribute
      - .include[0].email_domain: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].certificate: planned value cty.False for a non-computed attribute
      - .require[0].ip: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].any_valid_service_token: planned value cty.False for a non-computed attribute
      - .require[0].email_domain: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].ip_list: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].login_method: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].email: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].geo: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].group: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].service_token: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .require[0].auth_method: planned value cty.StringVal("") for a non-computed attribute
      - .require[0].everyone: planned value cty.False for a non-computed attribute
      - .require[0].common_name: planned value cty.StringVal("") for a non-computed attribute
```

These all seem to me like classic quirks of the legacy SDK: Terraform v0.11 didn't have any concept of `null` yet, and the SDK thinks it's talking to Terraform v0.11, so instead of indicating that all of these attributes are null it instead sets each one to some "empty value" of the corresponding type: `""` for strings, `false` for booleans, `0` for numbers, an empty list for a list, and empty set for a set. (Not all of those cases are represented here, but I'm trying to be general in the hope it helps with debugging this sort of problem in future.)

I note though that `.require[0].device_posture` is _not_ mentioned in this warning, and so it seems that the SDK handled that specific one correctly. "Correctly" means that the planned value matches the configured value, which I expect in this case would be `[ (known after apply) ]` or, as `cty` would spell it, `cty.ListVal([]cty.Value{cty.UnknownVal(cty.String)})`.

However, it then goes on to say:

```
2024-03-20T08:27:32.381+1100 [TRACE] writeChange: recorded NoOp change for cloudflare_access_group.warp_enforcement
```

Which suggests that somehow Terraform decided that this list containing an unknown value is equal to the prior state. I don't know this provider well, but in the log I see what I assume is the request made by [`ReadContext`](https://github.com/cloudflare/terraform-provider-cloudflare/blob/9c52c21c63893465aeaf7cd9d72944b41995d560/internal/sdkv2provider/resource_cloudflare_access_group.go#L35-L70):

```
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0: {
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:   "result": {
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "id": "12fb141c-67dc-47a0-b88e-1b7e3e7439cd",
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "name": "Warp Enforcement",
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "uid": "12fb141c-67dc-47a0-b88e-1b7e3e7439cd",
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "include": [
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:       {
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:         "auth_method": {
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:           "auth_method": "swk"
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:         }
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:       }
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     ],
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "require": [
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:       {
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:         "external_evaluation": {
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:           "keys_url": "https://example.com/keys",
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:           "evaluate_url": "https://example.com"
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:         }
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:       }
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     ],
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "exclude": [],
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "created_at": "2024-03-19T21:18:58Z",
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:     "updated_at": "2024-03-19T21:18:58Z"
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:   },
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:   "success": true,
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:   "errors": [],
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0:   "messages": []
2024-03-20T08:27:32.352+1100 [DEBUG] provider.terraform-provider-cloudflare_v4.26.0: }
```

There's no value for `.require[0].device_posture` here, so [nothing should get added to `devicePostureRuleIDs`](https://github.com/cloudflare/terraform-provider-cloudflare/blob/9c52c21c63893465aeaf7cd9d72944b41995d560/internal/sdkv2provider/resource_cloudflare_access_group.go#L516-L519) and so [`the prior state should have an empty list for the `device_posture` attribute](https://github.com/cloudflare/terraform-provider-cloudflare/blob/9c52c21c63893465aeaf7cd9d72944b41995d560/internal/sdkv2provider/resource_cloudflare_access_group.go#L640-L642).

With all of that said then, it isn't clear to me how we're ending up with a "no-op" action for this resource: the configuration has a list of length one, and the prior state has a list of length zero. The result of the provider must also have a list of length one or else `device_posture` would be mentioned in the warning about the plan being invalid.

@jbardin do you have some extra context here that I'm missing?

**Comment by jacobbednarz** [comment]
thank you both for the details here 🙇 there are definitely a couple of API design decisions here that make debugging these types of issues harder but still appreciate the insight.

i'll take a look and see what i can come out with if i'm always defining the value _or_ we move the framework plugin failing that.
