### ISSUE TITLE
Drop dynamodb requirements for S3 locks

### ISSUE THREAD

**Issue by dimoschi** [hashicorp/terraform#34920]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_arm64
```

### Use Cases

* S3 for state management is one of the strongest alternatives to remote, however a dynamodb is required for state locking, which increases complexity, although not by much.

### Attempted Solutions

Based on the current implementation of S3 there isn't an alternate solution.

### Proposal

AWS S3 nowadays comes with an object lock mechanism, which could be utilized instead of relying to DynamoDB to lock the state. Per AWS docs (https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html#object-lock-legal-holds) the object lock uses WORM, that can be applied on demand (legal hold), which would prevent multiple runs from altering the state.

### References

- #27070

**Comment by apparentlymart** [comment]
Thanks for sharing this, @dimoschi.

These new S3 features seem more motivated by legal/compliance than by being a synchronization mechanism, so I think we'll need to study more closely to find out what consistency guarantees it provides, but I agree that this does seem like an interesting alternative to using DynamoDB.

The S3 backend is maintained by the AWS provider team rather than by the Terraform Core team, so I'm going to label this to make it visible to them for consideration.

In the meantime, if you or anyone else has references to specific information about what consistency guarantees S3 offers for object lock -- for example, is it safe to assume that the lock is in effect for all clients as soon as the API server responds? -- that could help with determining whether this feature is sufficient to meet Terraform's needs for workspace state locking.

Thanks again!

**Comment by bschaatsbergen** [comment]
Briefly reading up on the documentation of the S3 Object locking it seems to be only available on buckets with versioning enabled:
> Object Lock works only in buckets that have S3 Versioning enabled.
Source: https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html

**Comment by bschaatsbergen** [comment]
Hi @dimoschi,

For more context, please refer to #35625 and #35661, where we are actively tracking and prototyping an S3-native backend implementation. This effort instead builds on the recently released [conditional writes](https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/) feature.

**Comment by bschaatsbergen** [comment]
Closing this in favor to focus on tracking the above referenced issue and PR.
