### ISSUE TITLE
terraform import fails - for_each aws_eip resource

### ISSUE THREAD

**Issue by Jithinxavi** [hashicorp/terraform#34944]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.43.0
```

### Terraform Configuration Files

```
variable "eip_allocation_ids" {
  type        = list
  description = "List of release AWS CLB Ip allocation ids"
  default = ["eipalloc-0aa6ae8533661fc9b","eipalloc-041e73fb4e8cca8c9"]
}

variable "appd_stable_ips" {
  type        = list
  description = "List of release AWS CLB Ip address"
  default = []
}
```

main.tf
```
import {
  for_each = toset(var.eip_allocation_ids)
  to =  module.elastic_ip.aws_eip.elastic_ip[each.key]
  id =  each.value
}


module "elastic_ip" {
  source           = "path-to-module/elastic_ip"

  stable_ips                  = tolist(var.appd_stable_ips)
  new_eip                     = var.new_eip
  custom_tags             = local.tags
}
```

Module
```
resource "aws_eip" "elastic_ip" {
  for_each      = length(var.appd_stable_ips) != 0 ? toset(var.stable_ips) : toset(var.new_eip)

  address           = length(var.appd_stable_ips) != 0 ? each.value : null
  domain            = "vpc"
  tags              = var.custom_tags
  lifecycle {
    ignore_changes = [
      tags["CreatedDate"]
    ]
  }
}
```

### Debug Output

Planning failed. Terraform encountered an error while generating this plan.
╷
╷
│ Error: Configuration for import target does not exist
│
│ The configuration for the given import
│ module.elastic_ip.aws_eip.elastic_ip["eipalloc-041e73fb4e8cca8c9"] does not
│ exist. All target instances must have an associated configuration to be
│ imported.
╵

### Expected Behavior

The provided list of EIP Allocation IDs should be imported to the terraform state.

### Actual Behavior

When I run the terraform plan command, it throws the following error output.
```
Planning failed. Terraform encountered an error while generating this plan.
╷
╷
│ Error: Configuration for import target does not exist
│
│ The configuration for the given import
│ module.elastic_ip.aws_eip.elastic_ip["eipalloc-041e73fb4e8cca8c9"] does not
│ exist. All target instances must have an associated configuration to be
│ imported.
╵
╵```

Compared to other resources aws_eip id(allocation_id) gets generated during the creation of the resources and not sure how we can pass the id while importing the resource

### Steps to Reproduce


    terraform init
    terraform apply


### Additional Context

_No response_

### References

_No response_

**Comment by jbardin** [comment]
Hi @Jithinxavi,

What the error means is that there is no corresponding `"eipalloc-041e73fb4e8cca8c9"` entry in the resource `for_each` expression, so there is no configured instance which you can import into. Make sure that a plan without the `import` block would attempt to create the `"eipalloc-041e73fb4e8cca8c9"` instance to be certain that the configuration is correct.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
