### ISSUE TITLE
[Bug]: `aws_datasync_task` - variable not populated or Plan inconsistent

### ISSUE THREAD

**Issue by remi-f-artelia** [hashicorp/terraform#34970]
### Terraform Version

```shell
Terraform v1.7.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v5.43.0
```

### Terraform Configuration Files

Terraform config is described in the [gist](https://gist.github.com/remi-f-artelia/7c7f970eb4574dc5368aaed2d911b25a)

I tried a lot of different changes in the code and at some point, I thought the issue was coming from the `schedule_expression` block, so I commented it. 

The error

```
│ Error: Missing required argument
│
│   with aws_datasync_task.this["dc1_archives_mrs"],
│   on main.tf line 1, in resource "aws_datasync_task" "this":
│    1: resource "aws_datasync_task" "this" {
│
│ The argument "schedule.0.schedule_expression" is required, but no definition was found.
```

But it seems it's not working either as you can see in the following [gist](https://gist.github.com/remi-f-artelia/7c7f970eb4574dc5368aaed2d911b25a)

The main concern I have is that most of the time, the `var.datasync_task_list` is considered as empty if I go t o `terraform console`.
But sometimes, it is recognized (when I comment some parts) and some errors will pop like

> The given value is not suitable for var.datasync_task_list declared at variables.tf:2,1-30: element "share_name": attribute "options": element "security_descriptor_copy_flags": object required.

> The given value is not suitable for var.datasync_task_list declared at variables.tf:2,1-30: element "share_name": attribute "options": element "transfer_mode": object required.

> The given value is not suitable for var.datasync_task_list declared at variables.tf:2,1-30: element "share_name": attribute "options": element "task_queueing": object required.

> The given value is not suitable for var.datasync_task_list declared at variables.tf:2,1-30: element "share_name": attribute "task_report_config": element "output_type": object required.

> The given value is not suitable for var.datasync_task_list declared at variables.tf:2,1-30: element "share_name": attribute "task_report_config": element "s3_object_versioning": object required.
...

### Debug Output

Debug output can be found into the [gist](https://gist.github.com/remi-f-artelia/7c7f970eb4574dc5368aaed2d911b25a)

### Expected Behavior

The plan should be consistent between different plan

### Actual Behavior

The plan is inconsistent. It says 
> The final value for var.datasync_task_list is missing in Terraform's evaluation context. This is a bug in Terraform; please report it!

### Steps to Reproduce

1. copy the different files from the [gist](https://gist.github.com/remi-f-artelia/7c7f970eb4574dc5368aaed2d911b25a) locally
2. terraform init
3. terraform plan
4. view the error

### Additional Context

I opened [an issue](https://github.com/hashicorp/terraform-provider-aws/issues/36758) to the aws provider first but [they seems to think](https://github.com/hashicorp/terraform-provider-aws/issues/36758#issuecomment-2043109890) it's more terraform core relative than the provider itself.
That's why I'm opening this issue in the terraform core repository.

I was using Terraform `v1.6.6` and I just upgraded to `v1.7.5` but it's the same behaviour.

I used the same model of module I did for `datasync_location_smb` or `datasync_location_s3` which are working correctly.

### References

Here is the [referenced issue](https://gist.github.com/remi-f-artelia/7c7f970eb4574dc5368aaed2d911b25a) from the aws terraform provider

**Comment by jbardin** [comment]
Hi @remi-f-artelia,

The errors from the configuration you've shown here, while difficult to understand because of the size and structure of the input variable, are because the configuration does not match the variable type. Your `options` and `task_report_config` values are defined as being a map of objects, but the input you are providing is only a single object.

That however does not reflect the other errors you mentioned. The `The final value for var.datasync_task_list is missing in Terraform's evaluation context` error would be a bug in Terraform, though it may just be a result of cascading errors when the wrong type was used. If that is reproducible for you, you could try with the latest v1.8 release which handles the values differently and cannot produce the same error message.

The error `The argument "schedule.0.schedule_expression" is required, but no definition was found` is definitely coming from the provider, but looks to be caused by not having a `schedule_expression` attribute in your input data. If you do have a value for `schedule_expression` then it would be a bug in the provider.

**Comment by remi-f-artelia** [comment]
Hi @jbardin 
Thanks for your answer. I was able to import tasks I've created with aws cli since I updated my tf version to `v1.8.0` as you suggested.

I did not try to create new ones yet (missing time unfortunately)

For the the error `The argument "schedule.0.schedule_expression" is required, but no definition was found` it's another issue so I consider this issue as solved.
