### ISSUE TITLE
can't build v1.8.0- kubernetes libraries not found

### ISSUE THREAD

**Issue by andrew-at-stratis** [hashicorp/terraform#35000]
### Terraform Version

```shell
v1.8.0
```

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

building terraform should compleate 

```shell
go build -ldflags "-w -s -X 'github.com/hashicorp/terraform/version.dev=no'" -o bin/ .
```

### Actual Behavior

```shellsession
$ go build -ldflags "-w -s -X 'github.com/hashicorp/terraform/version.dev=no'" -o bin/ .
go: downloading k8s.io/utils v0.0.0-20220728103510-ee6ede2d64ed
../../go/pkg/mod/k8s.io/apimachinery@v0.25.5/pkg/util/validation/validation.go:28:2: k8s.io/utils@v0.0.0-20220728103510-ee6ede2d64ed: read "https://proxy.golang.org/cached-only/k8s.io/utils/@v/v0.0.0-20220728103510-ee6ede2d64ed.zip": stream error: stream ID 1; NO_ERROR; received from peer
../../go/pkg/mod/k8s.io/apimachinery@v0.25.5/pkg/labels/selector.go:30:2: k8s.io/utils@v0.0.0-20220728103510-ee6ede2d64ed: read "https://proxy.golang.org/cached-only/k8s.io/utils/@v/v0.0.0-20220728103510-ee6ede2d64ed.zip": stream error: stream ID 1; NO_ERROR; received from peer
../../go/pkg/mod/k8s.io/apimachinery@v0.25.5/pkg/util/wait/wait.go:28:2: k8s.io/utils@v0.0.0-20220728103510-ee6ede2d64ed: read "https://proxy.golang.org/cached-only/k8s.io/utils/@v/v0.0.0-20220728103510-ee6ede2d64ed.zip": stream error: stream ID 1; NO_ERROR; received from peer
../../go/pkg/mod/k8s.io/client-go@v0.25.5/util/flowcontrol/backoff.go:25:2: k8s.io/utils@v0.0.0-20220728103510-ee6ede2d64ed: read "https://proxy.golang.org/cached-only/k8s.io/utils/@v/v0.0.0-20220728103510-ee6ede2d64ed.zip": stream error: stream ID 1; NO_ERROR; received from peer
../../go/pkg/mod/k8s.io/client-go@v0.25.5/util/flowcontrol/backoff.go:26:2: k8s.io/utils@v0.0.0-20220728103510-ee6ede2d64ed: read "https://proxy.golang.org/cached-only/k8s.io/utils/@v/v0.0.0-20220728103510-ee6ede2d64ed.zip": stream error: stream ID 1; NO_ERROR; received from peer
internal/backend/remote-state/kubernetes/client.go:24:2: k8s.io/utils@v0.0.0-20220728103510-ee6ede2d64ed: read "https://proxy.golang.org/cached-only/k8s.io/utils/@v/v0.0.0-20220728103510-ee6ede2d64ed.zip": stream error: stream ID 1; NO_ERROR; received from peer
```

### Steps to Reproduce

git clone git@github.com:hashicorp/terraform.git
git checkout v1.8.0
go build -ldflags "-w -s -X 'github.com/hashicorp/terraform/version.dev=no'" -o bin/ .

**Comment by apparentlymart** [comment]
Hi @andrew-at-stratis! Sorry this didn't work.

The errors you've described seem to describe your Go toolchain failing to connect to the official Go module proxy at `proxy.golang.org`.

Unfortunately the URL mentioned repeatedly in the error message are reachable for me (directly via an HTTP client) and I was still able to rebuild my local dev version of Terraform even after clearly my local Go module cache, so I cannot reproduce your error.

Does something in your environment block access to the proxy run by the Go team? Have you had similar trouble with any other Go modules?

If you set the environment variable `GOPROXY=direct` then the Go toolchain should connect directly to the upstream module source rather than trying to use the Go proxy, which should therefore avoid it trying to connect to this `proxy.golang.org` URL. That might help if your connections to that proxy service are being blocked.

Unfortunately the Terraform team does not run the Go module proxy or have any control over it, so I don't think there's anything we can do to change the behavior of the Go toolchain on your system.

**Comment by andrew-at-stratis** [comment]
Thanks for verifying the links. I suspect the problem is in my VPN network environment.
