### ISSUE TITLE
panic while applying a plan

### ISSUE THREAD

**Issue by hmlanigan** [hashicorp/terraform#35039]
### Terraform Version

```shell
$ terraform version
Terraform v1.8.1-dev
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.13.1

Your version of Terraform is out of date! The latest version
is 1.8.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

https://gist.github.com/hmlanigan/d6eb0ce0efffae54681c9d47ae0720a5

### Expected Behavior

terraform should not panic

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: value is marked, so must be unmarked first
goroutine 216 [running]:
runtime/debug.Stack()
	/snap/go/10585/src/runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/logging/panic.go:84 +0x18b
panic({0x2e00120?, 0x3d32c90?})
	/snap/go/10585/src/runtime/panic.go:770 +0x132
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/root/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt({{{0x3d75908?, 0xc000944a10?}}, {0x30d15e0?, 0xc000aca4f8?}})
	/root/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/value_ops.go:1125 +0x5b
github.com/zclconf/go-cty/cty.UnknownAsNull({{{0x3d75908?, 0xc000944a10?}}, {0x30d15e0?, 0xc000aca4f8?}})
	/root/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/unknown_as_null.go:41 +0x1b9
github.com/zclconf/go-cty/cty.UnknownAsNull({{{0x3d758d0?, 0xc000944a60?}}, {0x2f38d40?, 0xc000b41710?}})
	/root/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/unknown_as_null.go:53 +0x3bb
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).apply(0xc000b6ad88, {0x3d986a8, 0xc000c393b0}, 0xc0013ba000?, 0xc0013ba000, 0xc0009a5860, {{{{0x0, 0x0}}, {0x0, 0x0}}, ...}, ...)
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/terraform/node_resource_abstract_instance.go:2582 +0x1d55
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc000de4800, {0x3d986a8, 0xc000c393b0})
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/terraform/node_resource_apply_instance.go:309 +0xf96
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).Execute(0x18?, {0x3d986a8?, 0xc000c393b0?}, 0x70?)
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/terraform/node_resource_apply_instance.go:145 +0x9a
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0003c7a40, {0x3d986a8, 0xc000c393b0}, {0x78b2c9109200, 0xc000de4800})
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/terraform/graph_walk_context.go:153 +0xbb
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x346ff80, 0xc000de4800})
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/terraform/graph.go:112 +0x62a
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc00120d800, {0x346ff80, 0xc000de4800}, 0xc000e3c7c0)
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/dag/walk.go:384 +0x2d7
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 183
	/build/snapcraft-terraform-042b192c7624d48261d394e0860e021d/parts/terraform/build/internal/dag/walk.go:307 +0xff3

### Steps to Reproduce

`terraform init --upgrade && terraform plan && terraform apply` during development of a new feature for the juju terraform provider plugin.

### Additional Context

I added the following code to a provider while working to get import working:

```
diff --git a/internal/provider/resource_secret.go b/internal/provider/resource_secret.go
index 9a200a5..b9b53f9 100644
--- a/internal/provider/resource_secret.go
+++ b/internal/provider/resource_secret.go
@@ -46,6 +46,8 @@ type secretResourceModel struct {
        SecretId types.String `tfsdk:"secret_id"`
        // Info is the description of the secret. This attribute is optional for all actions.
        Info types.String `tfsdk:"info"`
+       // ID is used during terraform import.
+       ID types.String `tfsdk:"id"`
 }

 // ImportState reads the secret based on the model name and secret name to be
@@ -137,6 +139,11 @@ func (s *secretResource) Schema(_ context.Context, req resource.SchemaRequest, r
                                Description: "The description of the secret.",
                                Optional:    true,
                        },
+                       "id": schema.StringAttribute{
+                               Description: "The ID of the secret.",
+                               Computed:    true,
+                               Optional:    true,
+                       },
                },
        }
 }
```

secretResourceModel is the structure which represents the schema. ID was not used anywhere.

**Comment by liamcervante** [comment]
Hi @hmlanigan, thanks for filing this!

The specific trigger for this is the provider returning an unknown value for one of the attributes (probably the `id` attribute) during the apply operation alongside a sensitive attribute. Terraform definitely shouldn't be crashing, so there is a bug within Terraform Core here but you can avoid the crash by ensuring there is no unknown value returned by any of the attributes of a resource after an apply operation.

I'll write a follow up comment with recommendations on how to fix this in case anyone else has time to look at it before I get around to it!

**Comment by liamcervante** [comment]
For anyone looking into fixing this:

- Terraform checks if the value returned by the provider contains any unknown values [here](https://github.com/hashicorp/terraform/blob/1d73e490c47c197fd35e7ae74681255029f3b790/internal/terraform/node_resource_abstract_instance.go#L2557).
- Terraform then adds error diagnostics via the [cty.Walk](https://github.com/hashicorp/terraform/blob/1d73e490c47c197fd35e7ae74681255029f3b790/internal/terraform/node_resource_abstract_instance.go#L2561) function in order to highlight the specific problematic attributes.
- Terraform then attempts to convert all [unknowns to null](https://github.com/hashicorp/terraform/blob/1d73e490c47c197fd35e7ae74681255029f3b790/internal/terraform/node_resource_abstract_instance.go#L2582) so follow up operations that assume there are unknowns will still work. Since the diagnostics have been added the overall operation will fail regardless, but Terraform attempts to perform as much validation as possible which is why it carries on with replaced value.

The crash we see here happens because prior to all of this Terraform has already restored the sensitive marks to the value: https://github.com/hashicorp/terraform/blob/1d73e490c47c197fd35e7ae74681255029f3b790/internal/terraform/node_resource_abstract_instance.go#L2497. 

Many of the `cty` operations fail if the values have been marked and that is what we see in this case. The fix is to either remove and reapply the marks around the `UnknownToNull` function call, or to delay the reintroduction of the marks in the first place until after this check has been applied. The first fix means removing and reapplying the marks an additional time, which is going to be inefficient, however since we're responding to an error case that might be okay. The second fix is better, but we need to make sure we don't introduce some additional path where the new value is getting returned without the marks applied at all. My quick look now does suggest nothing does require the marks before the unknown check so I think it should be okay.

Hopefully this is helpful if anyone else picks this up before I get back to it.
