### ISSUE TITLE
provider/aws: Prevent users from mixing top-level and nested EBS volume declarations at validate stage

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#3511]
Users should not be able to both specify any `ebs_block_devices` in an instance, as well as have that instance included in a `volume_attachment` resource. 

Doing so causes a plan/refresh loop, due to the conflicting count of EBS Block devices. 

See https://github.com/hashicorp/terraform/issues/3262 as an example

**Comment by gtmtech** [comment]
@catsby  Is there any chance of making terraform so that these CAN co-exist. 

Its useful to be able to have one ebs volume with delete_on_termination, and one without.

Either that or the `aws_volume_attachment` resource needs a delete_on_termination too, so if the instance is removed, it propagates to removing the volume too.

**Comment by mitchellh** [comment]
Hey @catsby, closing this since we're not working on it atm and I actually do believe there are enhancement requests for a global validation function. We'll leave it at that for now.
