### ISSUE TITLE
Terraform module source as zip not working

### ISSUE THREAD

**Issue by sahitkumarreddy** [hashicorp/terraform#35149]
### Terraform Version

```shell
1.8.3

Same issue in 1.7.4 and 1.6.6 as well
```

### Terraform Configuration Files

```terraform
module "vm" {
  source = "https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/archive/refs/tags/v0.13.0.zip"

name = "myVM"
}


```
**Error: argument name not expected here**

Take any zip whether it is AWS or Azure the error is same

### Debug Output

On terraform validate 

**Error: argument name not expected here**

### Expected Behavior

Terraform validate should work

### Actual Behavior

On terraform validate 

**Error: argument name not expected here**

### Steps to Reproduce

`terraform validate`

### Additional Context

The source zip should get extracted to the current module folder (here .terraform/modules/vm), but when using source as zip the contents are getting extracted to a sub folder (.terraform/modules/vm/terraform-azurerm-avm-res-compute-virtualmachine). So Terraform module is not able to take even the required arguments

**Comment by jbardin** [comment]
Hi @sahitkumarreddy,

The zip file you are referencing consists of a single directory named `terraform-azurerm-avm-res-compute-virtualmachine-0.13.0` which contains the module data, so it appears that the existence of the directory in what is being extracted would be expected. 

The notations for accessing a subdirectory is to use a `//` and the path within the archive to point to the source you want. Adding `//terraform-azurerm-avm-res-compute-virtualmachine-0.13.0` to your `source` path with unpack the specific directory, and if you know there only exactly 1 directory in the archive, you can use `//*` as well. 

https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
