### ISSUE TITLE
Removing `create_before_destroy` and applying a replacement with `-refresh=false` will not destroy old resource

### ISSUE THREAD

**Issue by michael-sterling** [hashicorp/terraform#35218]
### Terraform Version

```shell
Terraform v1.8.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/local v2.5.1
```

### Terraform Configuration Files

First `apply` Original Terraform:
```terraform
resource "local_file" "main" {
  content  = "test"
  filename = "foo.txt"

  lifecycle {
    create_before_destroy = true
  }
}
```

Then change to Updated Terraform and `apply -refresh=false`:
```terraform
resource "local_file" "main" {
  content  = "test"
  filename = "bar.txt"
}
```

### Debug Output

https://gist.github.com/michael-sterling/48f32d53123769faf17c05e06ed583be

### Expected Behavior

The plan for `apply -refresh=false` looks like this:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # local_file.main must be replaced
-/+ resource "local_file" "main" {
      ~ content_base64sha256 = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=" -> (known after apply)
      ~ content_base64sha512 = "7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==" -> (known after apply)
      ~ content_md5          = "098f6bcd4621d373cade4e832627b4f6" -> (known after apply)
      ~ content_sha1         = "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> (known after apply)
      ~ content_sha256       = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08" -> (known after apply)
      ~ content_sha512       = "ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff" -> (known after apply)
      ~ filename             = "foo.txt" -> "bar.txt" # forces replacement
      ~ id                   = "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I would expect `foo.txt` to be deleted as the plan states.

### Actual Behavior

Both `foo.txt` and `bar.txt` exist. `foo.txt` is no longer tracked in Terraform state.

The `apply` part of the `apply -refresh=false` output confirms it did not attempt to delete `foo.txt`:

```
local_file.main: Creating...
local_file.main: Creation complete after 0s [id=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. Create a `main.tf` with "Original Terraform" above
2. `terraform init`
3. `terraform apply -auto-approve`
4. Update `main.tf` to the "Updated Terraform" above
5. `terraform apply -refresh=false -auto-approve`

**Comment by jbardin** [comment]
Hi @michael-sterling,

Thanks for filing the issue! This is an unusual consistency problem caused by changing `create_before_destroy` without allowing the resource to refresh the `create_before_destroy` value stored in the state. The current situation is a bit of a compromise, because in most cases we have to abide by the `create_before_destroy` value which is stored in the state; however when the resource is being replaced we try to allow it to be updated from the configuration so that users aren't required to apply the change in `create_before_destroy` separately, or manually update the state if that change order were going to fail for some reason.

I'm not sure exactly where the change is being lost, but it is clear that Terraform is building up the actions with `local_file.main` as `create_before_destroy` for the destroy node (which is what is stored in state) and destroy-then-create for the create node, which appears to be causing a conflict in the order the changes are stored during the apply process.
