### ISSUE TITLE
try() function in provider block doesn't work as expected

### ISSUE THREAD

**Issue by qbaze** [hashicorp/terraform#35217]
### Terraform Version

```shell
1.8.3
```

### Terraform Configuration Files

```terraform
provider "google" {
  project = "sampleproject"
  region = try(var.region, "us-central1")
}
```

### Debug Output

https://gist.github.com/qbaze/622fe824faaba804ae06767df74ebbae

### Expected Behavior

try() should return a fallback value i.e. `us-central1' as var.region is not defined

### Actual Behavior

Although it's wrapped with the try() function the exception is thrown instead of a fallback value
```
  An input variable with the name "region" has not been declared. This
│ variable can be declared with a variable "region" {} block.
```

### Steps to Reproduce

terraform plan

**Comment by jbardin** [comment]
Hi @qbaze,

The `try` function is intended to be used when the type of the object may not be known, so it can't be determined _until runtime_ whether the expression will evaluate correctly. The expression `var.region` only refers to a single input variable which must be declared statically, therefor cannot fail at runtime.

If you want to fallback to a default value within the variable, it can be declared as the variable's `default` value. Otherwise, a simple conditional expression could be used to set the default

```
region = var.region != null ? var.region : "us-central1"
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
