### ISSUE TITLE
Terraform fmt indents strangely when a multiline list is between two single-line values

### ISSUE THREAD

**Issue by whi-tw** [hashicorp/terraform#35221]
### Terraform Version

```shell
❯ terraform version
Terraform v1.8.3
on darwin_arm64
```
```


### Terraform Configuration Files

```terraform
module "some_module" {
  source             = "../../../modules/some-module"
  somekey1           = "value1"
  anotherkey2        = "value2"
  listkey3           = [
    "listitem1",
    "listitem2"
  ]
  someadditionalkey4 = true
}
```

### Debug Output

n/a, `fmt` doesn't produce trace logs

### Expected Behavior

`terraform fmt` does not make any changes as the formatting is good

### Actual Behavior

File is formatted to this:

```terraform
module "some_module" {
  source      = "../../../modules/some-module"
  somekey1    = "value1"
  anotherkey2 = "value2"
  listkey3 = [
    "listitem1",
    "listitem2"
  ]
  someadditionalkey4 = true
}
```

Diff output:

```diff
--- old/scratch.tf
+++ new/scratch.tf
@@ -1,8 +1,8 @@
 module "some_module" {
-  source             = "../../../modules/some-module"
-  somekey1           = "value1"
-  anotherkey2        = "value2"
-  listkey3           = [
+  source      = "../../../modules/some-module"
+  somekey1    = "value1"
+  anotherkey2 = "value2"
+  listkey3 = [
     "listitem1",
     "listitem2"
   ]
```

### Steps to Reproduce

1. create a file as above
2. `terraform fmt`

**Comment by apparentlymart** [comment]
Hi @whi-tw,

The result you shared is correct output according to the design of the formatter: equals signs are aligned only for sequences of single-line arguments, and so introducing an argument which is wrapped over multiple lines and has its own nested indentation ends the sequence, so that the nested indented content can be formatted independently.

If you would like all of your single-line arguments to be formatted together then I would suggest reordering the arguments so that the multi-line ones appear last and thus the single-line ones all appear together as a single sequence.

I understand that you would have preferred a different formatting convention here. The format command aims to provide an idiomatic style for Terraform, but it cannot possibly please everyone. If you decide that you cannot tolerate the conventions followed by the formatter then you have the option of not using it, or writing/using an alternative formatter, but of course that will then mean your own Terraform code will not follow the typical style that some other contributors might expect.

**Comment by crw** [comment]
Per the previous comment, I am going to close this issue. Please re-open if this is being closed in error. Thanks!
