### ISSUE TITLE
Piping terraform version where the right side of the pipe closes hangs forever

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#3523]
We have a check we use to make sure the user's version of terraform is sufficiently up to date that has this:

`terraform version | head -n 1 | sed -e 's/^Terraform v\(.*\)$/\1/'`

to extract the version. Because `head` closes the pipe once it has read enough lines, `terraform version` hangs forever writing to STDOUT.

Expected behavior:

`terraform version` exits even when writing to a broken pipe.

cc/ @2rs2ts

**Comment by catsby** [comment]
Hey @jszwedko can you help me understand here, what should `terraform version | head -n 1 | sed -e 's/^Terraform v\(.*\)$/\1/'` produce? 

For me it it outputs `0.6.5-dev (1bfd4b0f7175688d00e344f0ddb6ea6295d11468+CHANGES)` and gives me my prompt back. What are you seeing, and what _should_ I be seeing?

**Comment by apparentlymart** [comment]
I can repro, so I wonder if this is OS-specific? I'm on a Linux system (Ubuntu 15.04, to be precise. Or rather, to be vivid.)

Specifically what I see is that the output is printed out -- in my case ``0.6.4-dev`` -- and then it hangs. Hitting Ctrl+C gets me back to the prompt.

Since it's `head` that's the key here, I can drop the `sed` part and get the same effect:

```
$ terraform version | head -n 1
Terraform v0.6.4-dev
^C
$ _
```

**Comment by apparentlymart** [comment]
Looking at my process table before I hit ^C, I see that ``terraform version`` still running but ``head`` is not. Digging some more...

**Comment by apparentlymart** [comment]
Confirmed that if I temporarily disable the remainder of the ``terraform version`` implementation, so that it just prints out the one line and exits, then it works.

I'd expect either the ``ui`` library (which is what's writing here) would get `EPIPE` (which it would then ignore, but that doesn't seem like a big deal here) or the process would get a `SIGPIPE` signal, but apparently I don't completely understand all of the interactions involved in a pipe.

**Comment by apparentlymart** [comment]
Ahh, I think the reason for the inconsistency is that ``terraform version`` generates only one line of output unless the terraform version is older than current. So this hang would apply only once the running terraform becomes non-latest.

**Comment by apparentlymart** [comment]
@jszwedko if you make a `.terraformrc` file in your homedir containing the following:

```js
disable_checkpoint = true
```

I believe that should disable the "current version" check and prevent ``terraform version`` from creating any more output after the version number. Can you check if that works for you?

Obviously that's just a workaround and not a fix, but I'd like to get confirmation that my theory is sound before trying to dig in further, and I want to make sure I am seeing the same issue as you are.

**Comment by jszwedko** [comment]
@catsby apologies, it only breaks if `terraform version` outputs more than one line (though you can get it to break even in that case if you do something like `terraform version | foobar` where `foobar` doesn't exist and breaks the pipe immediately).

@apparentlymart thank you, I didn't know about `disable_checkpoint = true`. We worked around this by introducing an intermediate state in our scripts where we save the output to a variable.

**Comment by jszwedko** [comment]
@apparentlymart but yes! Your understanding is correct.

**Comment by mitchellh** [comment]
This appears to work on master now. I just ran it without a hang so it must be fixed somewhere!
