### ISSUE TITLE
TypeList order not preserved

### ISSUE THREAD

**Issue by zaalbarxx** [hashicorp/terraform#35269]
### Terraform Version

```shell
Terraform v1.8.2
on windows_amd64
```

### Terraform Configuration Files

```terraform
resource "fusionauth_form_field" "country_select" {
  key = "registration.data.country"
  name = "Country Select"
  control = "select"
  description = "Form field for selecting user country"
  type = "string"
  required = true
  options = ["AFG", "ALD", "AZB", "BZA", "ZX"]
  data = {
    country = true
  }
}
```

### Debug Output

2024-05-31T16:23:01.672+0200 [WARN]  unexpected data:
  terraform.local/fusionauth/fusionauth:stdout=
  | &{0x85a060 map[1560497164:ZX 1584592837:ALD 2026381776:AFG 277057409:AZB 689664940:BZA] {{{} 1} {0 0}}}
  |  [ZX ALD AFG AZB BZA] [ZX ALD AFG AZB BZA]
  

### Expected Behavior

Order of elements in list should be preserved, same as the one provided in Terraform config.

 ["AFG", "ALD", "AZB", "BZA", "ZX"] (correct)

instead of [ZX ALD AFG AZB BZA]

### Actual Behavior

Order of elements seem to be wrong when using either `TypeSet` or `TypeList` schema type

### Steps to Reproduce

Consider resource 
```
resource "fusionauth_form_field" "country_select2" {
  key = "registration.data.country"
  name = "Country Select"
  control = "select"
  description = "Form field for selecting user country"
  type = "string"
  required = true
  options = ["AFG", "ALD", "AZB", "BZA", "ZX"]
  data = {
    country = true
  }
}
```
When this resources is created the order of options is incorrect. With my limited knowledge about Go, I tried to track what is wrong and it looks like data coming from `schema.Schema` object is already in wrong order.

### Additional Context

It is related to FusionAuth provider, but from what I understand this is not an issue with the provider itself, but rather implementation/parser of schema ?

**Comment by apparentlymart** [comment]
Hi @zaalbarxx! Thanks for reporting this. 

I'm not familiar with the provider you are discussing here. Is that an open source provider whose source code we could study to try to understand more about what's going on here? Thanks!

**Comment by zaalbarxx** [comment]
Sorry, to bothering you, I checked it incorrectly, the provider is indeed using `TypeSet` which as far as I understand is ignores order of values, but enforces uniqueness of values. Is it therefore possible to use `TypeList` along with validation function ? From what I tried it seems that currently it is not possible to provide `ValidateFunc` for either `TypeSet` or `TypeList`, so it is not possible to manually check if all of `TypeList` values are indeed unique ?

**Comment by apparentlymart** [comment]
Hi @zaalbarxx,

Thanks for following up. 

Unfortunately your follow-up questions are about some design details of the legacy Terraform plugin SDK, which I personally have not worked on for several years and so I don't recall enough to answer definitively.

If the SDK does not permit validation of list or set attributes then a possible alternative would be to use a `CustomizeDiff` function at the resource type level, and design it to return an error if the entries are not unique but change nothing if the lists are valid. That would cause the problem to be detected during the plan phase rather than during the apply phase, but would still be effective to prevent trying to apply an invalid configuration.

If you are not already deeply invested in the SDK for this provider then you might also consider using the modern plugin framework instead, which has fewer strange quirks due to being designed for modern Terraform. If course, this suggestion is only if you haven't already written substantial code against the SDK; if you have then rewriting everything just to solve this problem probably isn't justifiable.

**Comment by zaalbarxx** [comment]
Hmmm, I'm pretty sure that the provider is using the new version of the SDK, not legacy one, at least from what I understand looking at `go.mod` https://github.com/FusionAuth/terraform-provider-fusionauth/blob/main/go.mod

But I guess that even if it uses the newest version it may be using the old API, am I correct here?

**Comment by apparentlymart** [comment]
Yeah, `github.com/hashicorp/terraform-plugin-sdk/v2` is "the legacy SDK", which is in occasional-maintenance mode and unlikely to support any substantial new features.

The "modern plugin framework" is [`github.com/hashicorp/terraform-plugin-framework`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework), which is essentially a "reboot" of the plugin development experience that isn't backward-compatible with Terraform v0.11 and therefore doesn't need to preserve all of the old assumptions that the legacy SDK carried forward in an attempt to support both legacy and modern Terraform at the same time.

You can find more details on the differences in [Framework and SDKv2 Feature Comparison](https://developer.hashicorp.com/terraform/plugin/framework/migrating/benefits). I mentioned it in this case specifically because [Collection Type Validation](https://developer.hashicorp.com/terraform/plugin/framework/migrating/benefits#collection-type-validation) is one of the listed benefits of the new framework in comparison to the old SDK.

Most of the official providers are still making significant use of the old SDK though, since code that's already working is best left alone until there's a specific reason to change it. So if you're similarly invested in the old SDK I don't intend what I've said here as pressure to throw away your existing work. I was mentioning the new framework just in case you were still relatively early in developing this provider, and thus switching now (before _becoming_ too invested in the old SDK) might be justified if it allows you to describe the design of your target API more straightforwardly.

**Comment by zaalbarxx** [comment]
Wonderful, thanks for clarification, have a nice day! 🍻
