### ISSUE TITLE
db_subnet_group_name and publicly_accessible interaction

### ISSUE THREAD

**Issue by ben-dov** [hashicorp/terraform#35353]
### Terraform Version

```shell
1.7.5
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#db_subnet_group_name

### What is the docs issue?

related to #3789
the [document page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#db_subnet_group_name) mistakenly asserts that `db_subnet_group_name` is required if `publicly_accessible = false` (which is the default).
but it seems in the [cli](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html):
>If DBSubnetGroupName isn't specified, and PubliclyAccessible isn't specified, the following applies:
> * If the default VPC in the target Region doesn’t have an internet gateway attached to it, the DB instance is private.
> * If the default VPC in the target Region has an internet gateway attached to it, the DB instance is public.

### Proposal

the docs should reflect the correct logic

### References

https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html

**Comment by liamcervante** [comment]
Hi @ben-dov, thanks for filing this!

The Terraform providers are actually managed within their own separate repositories. I believe this issue relates to the AWS provider which is managed here: https://github.com/hashicorp/terraform-provider-aws

I will close this issue here, and you should reopen it directly with the relevant provider.

Thanks!
