### ISSUE TITLE
Minimal plan/apply

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform#35382]
### Terraform Version

```shell
Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.13.1
+ provider registry.terraform.io/hashicorp/azuread v2.50.0
+ provider registry.terraform.io/hashicorp/azurerm v3.104.0
+ provider registry.terraform.io/hashicorp/random v3.6.1

Your version of Terraform is out of date! The latest version
is 1.8.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

End goals:
1. Reduce time it takes to `plan` and `apply`
2. Reduce concurrency clashes
3. Reduce likelihood of external change breaks your change
4. Reduce likelihood of unrelated API problem breaks your change
5. Reduce Cloud API limits exhaustion
6. Reduce CO2 emissions and compute resource waste

### Attempted Solutions

1. `apply -target=..` not possible with VCS-driven TFE.
2. `plan -target=..` not possible with index changes.
3. Split code to smaller Workspaces/states causes more parallelism, exhausting API limits even faster

### Proposal

Calling out to the masterminds here - especially @apparentlymart 🫡 - to validate this idea aiming to increase TF(E)'s efficiency. 

As time goes, size and complexity of our deployments grows. We do more and more often, automatically. I.e. every commit triggers a TFE plan of the entire code. This is desired, but takes time and eats up cloud API limits, because it is inefficient.

**I'm suggesting to decouple TF's desired state capabilities from its apply capabilities.**
- I think desired state check should run in background periodically (or when called), and either alert or correct.
- **But `plan` and `apply` should only worry about resources that are changing in my code.** 👈 (at least if I opt into)

<details>
  <summary>Example use-case and possible issues (click to expand)</summary>
I have VPC and 300 VMs in my state. I change name of VM5. I don't need TF to refresh the other 299 VMs during `apply`.
- Now imagine someone changed VM2 meanwhile. Now I have to include his change in my code about VM5, or make a separate prereq PR. (changes could come also from CSP itself or from external automation, like corrective Policy)
  - Instead I should be able to fix VM2 separately later - once DSC check detects and reports drift.
- Now imagine that VPC API is down. I can't `apply` my VM change because the full TFE `plan` won't complete successfully. I need to wait for the VPC API to recover.
- Now imagine 3 people are properly changing 3 VMs separately in 3 PRs. That's 3x300 API calls while we only needed to make 3 calls.
</details>

I believe this would help everyone, including out planet.
Terraform behaves very inefficiently today, literally abusing and wasting Cloud resources for read calls. We keep hearing we must stop eating beef due to CO2 emissions - well, we could measure the CO2 literally wasted by API calls nobody needed to make, whilst prolonging the time the TF user has to wait to get the information they actually needed.

For context: Azure and GCP give limit of about 25 reads/sec per Project/Subscription.
Especially in hub-and-spoke topologies where all spokes always (re)read `data` on hub resources, this limit is very limiting.

What I don't know is how difficult this might be to implement? Ideally as an optional choice for TFE customers to enable/disable. 
Thanks for your inputs and comments. ☺️

**Comment by liamcervante** [comment]
Hi @Tbohunek, thanks for filing this. I believe there is significant overlap with the request you've made here and the one tracked in https://github.com/hashicorp/terraform/issues/35290. As such, I'm going to close this issue here but you should have a look at the other issue. If you think there's something I've missed that makes this a significantly different request than the linked one, add a comment here explaining why / how and I can reopen for you 👍 

Something that the other issue calls out, and you haven't mentioned is that it is not easy for Terraform to know what has actually changed within the code. The proposed solution (in the other issue) is for the entire configuration after the last apply to be included in the state file so that it can be read and compared to the current configuration. This has other problems

> Terraform behaves very inefficiently today, literally abusing and wasting Cloud resources for read calls

If you simply wish to disable read calls during planning then the command `terraform plan -refresh=false` will do that for you today. This command does also achieve an approximation of the request you've made in that only resources that have different configuration to what is stored in the state will be included in the plan. However, it is not perfect as providers are still called to plan the resource, but often the plan command itself doesn't actually use any cloud resources.

**Comment by Tbohunek** [comment]
Thanks for quick response @liamcervante , there is indeed overlap in these two requests. I would replay the relevant part over, but first let's clarify a few things.

Is it possible to achieve equivalent of `terraform plan -refresh=false` in Terraform Enterprise (TFE)?

**Comment by liamcervante** [comment]
I'm not super familiar with the Terraform Cloud / Enterprise implementation, but based on the docs it seems like this is supported via the API or CLI integrations, but not directly through the GUI: https://developer.hashicorp.com/terraform/cloud-docs/run/modes-and-options#skipping-automatic-state-refresh

If you have an enterprise contract with us, you should be able to raise a feature request for Terraform Enterprise via our support team asking if the Cloud / Enterprise teams could look into supporting `-refresh=false` in the Enterprise GUI. This channel is mainly focused on the core (offline) CLI workflow and Terraform community edition.

**Comment by Tbohunek** [comment]
Thank you @liamcervante , yeah we will raise this with our account team.
If this flag is supported in the TF CLI, then it should be matter of TFE adding a boolean flag into the Workspace settings.

Maybe one last question: can this be done via Env vars as well?

**Comment by apparentlymart** [comment]
I do think it's still worth asking the question about this potentially being an official HCP Terraform setting, but FWIW today you can force the effect of adding any specific arguments to a Terraform CLI execution in HCP Terraform by changing the workspace settings to include one of [the environment variables that Terraform CLI supports for specifying additional arguments](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name).

In this case since `-refresh=false` is only relevant for the `plan` subcommand you'd set the environment variable `TF_CLI_ARGS_plan` to `-refresh=false`, which would therefore add that option only for that one command. (Most other commands would consider it to be an error.)

**Comment by Tbohunek** [comment]
Yeah, we found that and already tested moments ago @apparentlymart .
It works but has unintended effects: It doesn't refresh even resources that you explicitly `-target`.
I will do a more testing, see how viable is it to cover at least some use-cases..

**Comment by apparentlymart** [comment]
The `-target` argument can only possibly make Terraform perform _fewer_ actions, never more. So indeed, you cannot use `-target` to cause Terraform to refresh something it would not have refreshed otherwise.

I was only intending to answer the question of how you can use `-refresh=false` (as currently implemented) in HCP Terraform, not to comment on your original idea which (if I'm understanding the above correctly) is now absorbed into the scope of https://github.com/hashicorp/terraform/issues/35290.

**Comment by Tbohunek** [comment]
I know. I'll have to append the diff into that issue, because I cover a bit different angle.

Meanwhile this makes me smile too:
![image](https://github.com/hashicorp/terraform/assets/16520646/384eca1d-3326-4a78-a213-94aa689c3cdb)
I understand this isn't meant to work, I do it to confirm that `-refres=false` doesn't meet the use-case objectives.

For now I will use it though, because there's currently an issue with one of the APIs, and it's failure blocks the entire TFE plan, so this helps us out as a workaround for the API problem.
