### ISSUE TITLE
tf state file not updated if the terraform execution is interrupted

### ISSUE THREAD

**Issue by divam20** [hashicorp/terraform#35386]
### Terraform Version

```shell
Terraform 0.12.29
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

NA

### Expected Behavior

Since the terraform execution failed, the tfd plan should have shown the output that these resources need to be recreated or show only the resources which were not created in the previous execution of terraform.

### Actual Behavior

Terraform was trying to create all the resources again and the state file was not updated

### Steps to Reproduce

terraform init
terraform plan
terraform apply
Ctrl + C
terraform plan

Note: This is not happening everytime

**Comment by liamcervante** [comment]
Hi @divam20, thanks for filing this. The version of Terraform you are using (v0.12.29) is nearing 4 years old, it is possible that the state file management story has been improved since then. Are you able to test this with the latest release (v1.8.5) and confirm that this is still a concern? Thanks!

**Comment by apparentlymart** [comment]
The intended behavior for current versions of Terraform is that the first interrupt during an apply causes Terraform to write a state snapshot as soon as possible, tell providers that they should safely cancel any active operations as an as possible, and then aggressively write new state snapshots each time one of the active operations completes in a way that would update the state. A second interrupt caused Terraform to quit immediately, which is likely to cause state data loss. 

I don't remember when the above behaviors were each added. It is quite possible that Terraform v0.12 is too old to behave in this way.

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
