### ISSUE TITLE
Add support for TF_CHDIR env variable

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/terraform#35418]
### Terraform Version

```shell
1.8.5
```

### Use Cases

We want to move our `.tf` files out of repo root into a `tf` subfolder, but in order to do that one would have to add `-chdir=tf` to every single terraform command.

### Attempted Solutions

I thought I could do `export TF_CLI_ARGS='-chdir=ansible'`, but it does not work:
```
 > terraform state list               
Error parsing command-line flags: flag provided but not defined: -chdir
```

### Proposal

Add support for reading `TF_CHDIR` to provide default value for `-chdir` global flag in order to make use of a subfolder in a project iplicit.

### References

- https://github.com/hashicorp/terraform/issues/22734#issuecomment-788865551

**Comment by liamcervante** [comment]
Hi @jakubgs, thanks for filing this.

I think your attempted solution should work, but Terraform is failing to parse the environment variables properly as they contain the embedded `=` symbol. While I work to confirm this is an actual bug, can you try running with the following env var instead:

```
export TF_CLI_ARGS='-chdir ansible'
```
 
I think by replacing the embedded equal symbol with a simple space whatever is causing the incorrect parsing is skipped. As both with and without the equals symbol are valid inputs for flags within Terraform this might unblock you while we work on a fix for this.

**Comment by apparentlymart** [comment]
Hi @jakubgs! Thanks for sharing this use-case.

The `-chdir` option is included to help with situations where some automation wants to have Terraform work in a different directory just for one specific command, without affecting the state (including the current working directory, or environment variables) of the calling process.

That justification doesn't seem to extend to environment variables because I would expect it's just as easy to change your shell's working directory as it is to change an environment variable in your shell. Instead of running `export TF_CLI_ARGS='-chdir=ansible'` you could have run `cd ansible`, and then this would have worked with the same number of commands.

Therefore my initial instinct is that you have a relatively esoteric need here that probably isn't common enough to justify being built in, and that you could instead write your own wrapper script to use in your repository if you think it would be beneficial for how you've laid things out. 

However, if the original issue comment garners a significant number of 👍 reactions then I'll treat that as a signal that this is less esoteric than I thought it was. (If you are reading this with the intention of voting, please make sure to add the reaction to the top level issue message and not to my comment here, because the Terraform team uses voting on the issues themselves as one input to prioritization.)

**Comment by jakubgs** [comment]
That's understandable. My purpose is probably a niche one.

I just want to de-cluttering the root of our fleet repos by moving all multitude of terraform files into `tf` folder, the same way all Ansible stuff in under `ansible`. The thing about ansible is that it's quite easy to just do:
```
ansible-playbook ansible/something.yml
```
While with terraform you'd have to do a separate flag for that:
```
terraform -chdir=tf plan
```
But I guess this could be achieved with an alias: `alias tf=terraform -chdir=tf`

Which is a good enough solution. Honestly, my main surprise was at how `TF_CLI_ARGS` worked and that there was not global equivalent, but considering there's only one global flag that actually does anything it's not that surprising.

**Comment by apparentlymart** [comment]
Thanks for that extra context, @jakubgs.

Indeed, I acknowledge that it's a bit of a gap that you can't set this argument using an environment variable but yet you can set others.

The technicial reason for that is rather mundane: the environment variable works by inserting arguments immediately after the subcommand, which is the location for command-specific options. Global options (of which there is currently only one, as you say) must appear before the subcommand name, so the environmental variable doesn't work for them. 

We could potentially add an environment variable for inserting extra options in the global options location, but it would be a bit tricky since we'd need to make sure it only allows "option-like" arguments in that position; no positional arguments are allowed there. With only one global option available and with the need to set it from the environment seeming quite niche, I don't think we can justify that additional complexity.

Thank you for being understanding about this tradeoff.
