### ISSUE TITLE
Lifecycle create_before_destroy does not propagate to dependant resources

### ISSUE THREAD

**Issue by igoratencompass** [hashicorp/terraform#35446]
### Terraform Version

```shell
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.49.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.11.2
+ provider registry.terraform.io/mongodb/mongodbatlas v1.1.1
```

### Terraform Configuration Files

```terraform
# variables.tf
variable "vpn" {
  type = object({
    enabled   = bool
  })
  default = {
    enabled   = false
  }
}

# variables.tfvars
vpn = {
  enabled     = true
}

# main.tf
module "vpn" {
    source  = "./modules/vpn"
    count   = var.vpn["enabled"] ? 1 : 0

    vpc_id        = # id of an existing VPC
    subnet_ids    = # list of subnet IDs in the VPC
    ami_id        = "ami-031a6a3cbaebd96fd" # Ubuntu focal ap-southeast-2
    instance_type = "t3.micro"
    key_name      = "" # ssh key name in the account
}

# ./modules/vpn/main.tf
resource "aws_autoscaling_group" "vpn" {
  name = "my-vpn-asg-${substr(aws_launch_template.vpn.name,length(aws_launch_template.vpn.name)-2,length(aws_launch_template.vpn.name)-1)}-${aws_launch_template.vpn.latest_version}"

  vpc_zone_identifier       = var.subnet_ids
  max_size                  = 1
  min_size                  = 1
  health_check_grace_period = 60
  default_cooldown          = 60
  health_check_type         = "EC2"
  desired_capacity          = 1
  force_delete              = true

  launch_template {
    id      = aws_launch_template.vpn.id
    version = "$Latest"
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_launch_template" "vpn" {
  name_prefix   = "vpn-access-vpn-lt-"

  image_id      = var.ami_id
  instance_type = var.instance_type
  key_name      = var.key_name

  user_data     = base64encode(data.template_file.vpn.rendered)

  iam_instance_profile {
    name        = aws_iam_instance_profile.vpn.name
  }

  depends_on = [
    aws_iam_role_policy.vpn-access,
  ]

  vpc_security_group_ids = [aws_security_group.vpn.id]

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_security_group" "vpn" {
  name = "vpn-access-vpn-sg"
  ingress {
    from_port   = 12345
    to_port     = 12345
    protocol    = "tcp"
    self        = true
    description = "TCP self"
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  vpc_id = var.vpc_id
}

data "template_file" "vpn" {
  template = file("${path.module}/userdata.sh")
  vars = {}
}

resource "aws_iam_instance_profile" "vpn" {
  name = "my-vpn-profile"
  role = aws_iam_role.vpn.name
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_iam_role" "vpn" {
  name               = "my-vpn-iam-ec2role"
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.vpn.json

  lifecycle {
    create_before_destroy = true
  }
}

data "aws_iam_policy_document" "vpn" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role_policy" "vpn-access" {
  name   = "my-vpn-role-policy"
  role   = aws_iam_role.vpn.id
  policy = data.aws_iam_policy_document.vpn-access.json
}

data "aws_iam_policy_document" "vpn-access" {
  statement {
    sid       = "ListEC2andASG"
    effect    = "Allow"
    resources = ["*"]
    actions = [
      "ec2:DescribeInstances",
      "autoscaling:DescribeAutoScalingInstances",
      "autoscaling:DescribeAutoScalingGroups",
    ]
  }
}
```

### Debug Output

```
2024-07-10T18:48:34.627+1000 [DEBUG] ReferenceTransformer: "module.vpn.aws_launch_template.vpn (expand)" references: [ module.vpn.aws_security_group.vpn (expand) ]
2024-07-10T18:48:34.633+1000 [DEBUG] ReferenceTransformer: "module.vpn.aws_autoscaling_group.vpn (expand)" references: [ module.vpn.aws_launch_template.vpn (expand)]
```

### Expected Behavior

As per the Lifecycle documentation https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#create_before_destroy, the `create_before_destroy` parameter should propagate to all dependency resources and saved in the state file:
```
Note that Terraform propagates and applies the create_before_destroy meta-attribute behaviour 
to all resource dependencies. For example, if create_before_destroy is enabled on resource A but 
not on resource B, but resource A is dependent on resource B, then Terraform enables create_before_destroy 
for resource B implicitly by default and stores it to the state file. You cannot override create_before_destroy 
to false on resource B because that would imply dependency cycles in the graph.
```

### Actual Behavior

This is not happening from what I can see. As per the debug log I have the following dependency:
```
module.vpn.aws_autoscaling_group.vpn -> module.vpn.aws_launch_template.vpn -> module.vpn.aws_security_group.vpn 
```
The `module.vpn.aws_launch_template.vpn` has `create_before_destroy = true` and depends on `module.vpn.aws_security_group.vpn` that does not have `create_before_destroy` enabled. According to the above linked documentation, this parameter should propagate to the `module.vpn.aws_security_group.vpn` resource and get stored in the terraform state file. That is not happening for me, there is no `"create_before_destroy": true` in the state file for this resource:
```
   {
      "module": "module.vpn[0]",
      "mode": "managed",
      "type": "aws_security_group",
      "name": "vpn",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
      <snip>
          "dependencies": [
            "module.vpc.aws_vpc.environment"
          ]
        }
      ]
    }
```
hence I get a cycle dependency upon resources destroy when I set `vpn.enabled = false` **after** the resources have initially been created (which is exactly what should happen as per the doc cited).
```
╷
│ Error: Cycle: module.vpn[0].aws_autoscaling_group.vpn (destroy), aws_autoscaling_notification.main[0], module.vpn[0].aws_launch_template.vpn (destroy), module.vpn[0].aws_security_group.vpn (destroy)
│
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

Then disable the `vpn` module by setting the `vpn.enabled = false` and run:

1. `terraform plan`

which errors with the above mentioned cycle.

### Additional Context

If I manually update the terraform state file and add `"create_before_destroy": true` to the `aws_autoscaling_group` resource the cycle is gone.

Trying to add the `create_before_destroy` lifecycle to the `aws_autoscaling_group` resource in the module does not make any difference and the `plan` stage is failing with the same cycle error (expected since the state file is still missing the needed parameter).

**Comment by liamcervante** [comment]
Hi @igoratencompass, thanks for filing this.

The error message about the cycle mentions another resource `aws_autoscaling_notification.main[0]` that has not been included in your configuration, are you able to share the configuration you have for that resource?

The behaviour you described as a result of setting `vpn.enabled = false` shouldn't really be affected by the `create_before_destroy` behaviour so I agree it is curious that you see behaviour changes when manually setting that value in the state file. In this case, I'd expect the mentioned resources to simply be destroyed (since the module is being removed) while the `create_before_destroy` setting is only applicable during replace operations (where a piece of infrastructure needs to be destroyed and then created) which shouldn't be the case here.

I'd have a better idea about what is causing the cycle if I could see the missing resource that is involved in the cycle, and separately I will have a look to see if I can work out why the `create_before_destroy` setting is even relevant to your example.

**Comment by igoratencompass** [comment]
Hi @liamcervante , first thanks for looking into this, your quick reply is very much appreciated.

Sorry I missed to mention the `aws_autoscaling_notification.main[0]` trying to keep the case as concise and focused as possible. The thing is I ruled out this resource out of the equation by removing its reference to the `module.vpn[0]` resource:

```
resource "aws_autoscaling_notification" "main" {
  count = var.sns.enabled ? 1 : 0
  group_names = compact([
    length(module.bastion) > 0 ? module.bastion.*.bastion_asg_name[0] : "",
    <snip>
    #length(module.vpn) > 0 ? module.vpn.*.vpn_asg_name[0] : "",  # <======= commented out to test the cycle
  ])
  notifications  = [
    "autoscaling:EC2_INSTANCE_LAUNCH",
    "autoscaling:EC2_INSTANCE_TERMINATE",
    "autoscaling:EC2_INSTANCE_LAUNCH_ERROR",
    "autoscaling:EC2_INSTANCE_TERMINATE_ERROR"
  ]
  topic_arn = aws_sns_topic.main[count.index].arn
}
```
which made no difference the cycle error was still there.

**Comment by igoratencompass** [comment]
Hi @jbardin , thanks for your input that is very much appreciated as always.

> I think the most likely explanation here is that the dependencies stored in the state do not agree with the current configuration,

This is what I'm thinking as well although not sure how and when would this happen. We use CI/CD, S3 state backend and DynamoDB for locking in all our Terraform projects _but_ I can't rule the possibility that someone at some point did a manual change to the state file and caused some damage. The same module is used across dozens of projects and this one is the only one having the issue for some reason. 

> or less likely the state was created with an earlier version of terraform which contained a bug that failed to record the dependencies correctly.

This is also possible, not all of our projects are of same age, some have been around for a very long time (since 2015) and have undergone a long string of TF updates.

> After creating a similar broken configuration and state structure to what is shown here, completing a plan&apply with `enabled=true` will ensure the state is updated before proceeding.

Good point, I will for sure dedicate some time into testing this as well, thanks.

**Comment by igoratencompass** [comment]
@liamcervante @jbardin 

Just an observation and some questions coming out of it. Regarding the statement:
```
Note that Terraform propagates and applies the create_before_destroy meta-attribute behaviour 
to all resource dependencies. For example, if create_before_destroy is enabled on resource A but 
not on resource B, but resource A is dependent on resource B, then Terraform enables create_before_destroy 
for resource B implicitly by default and stores it to the state file. You cannot override create_before_destroy 
to false on resource B because that would imply dependency cycles in the graph.
```
does it maybe mean an _explicit_ dependency between the resources like resources mentioned in `depends_on` statement? Asking because for example the `aws_launch_template` resource has an explicit dependency on `aws_iam_role_policy` resource:
```
  depends_on = [
    aws_iam_role_policy.vpn-access,
  ]
```
which does not have any `lifecycle` setup but it does have `"create_before_destroy": true` inserted by TF in the state file. Since this did not happen for the `aws_autoscaling_group` (and assuming the state file has not been tampered with) is it maybe because of the implicit dependency? Or maybe this `aws_autoscaling_group` resource has a special treatment for some reason in the logic due to its complexity?

**Comment by liamcervante** [comment]
Hi @igoratencompass, I think there’s some confusion between your last message and the original bug filed. I wouldn’t expect the `aws_autoscaling_group` to have `create_before_destroy` inserted automatically as it is at the end of the dependency chain. The `aws_launch_template` having `create_before_destroy` set implies that its dependencies (the `aws_iam_instance_profile`, `aws_iam_role_policy`, and `aws_security_group` resources) also have it set, but it doesn’t imply the things that depend on it (the `aws_autoscaling_group` resource) have it set.

In the original bug you call out `aws_security_group` as not having the correct value in the state, but in your most recent comment you mention `aws_autoscaling_group` and I just wanted to clarify which direction the `create_before_destroy` attribute propagates.

Also, the `depends_on` attribute creates an explicit dependency in the same way a normal reference does. I don’t think there’s any difference between these two forms of dependencies from Terraform’s perspective.

I have been able to replicate this, but in a way that isn’t particularly helpful as it does require editing the state file manually. Essentially, if I go and remove the `create_before_destroy` attribute from the dependency in the state file, then try and run a `terraform plan` with `enabled = false` then I see the error about the cycle, but so far I’ve not been able to replicate this in a way that Terraform has left the state file in a bad shape.  In addition, James’ workaround (of completing a full `terraform plan` and `terraform apply` cycle with `enabled = true`) does resolve the issue for me in that it fixes the state file by putting the attribute I removed back in.

Given that James’ workaround didn’t work for you, it seems that the bug here is really that for whatever reason Terraform seems to not be writing `create_before_destroy` into the `aws_security_group`. This is something I definitely haven’t been able to replicate, as Terraform so far has not only behaved but also recovered automatically whenever I’ve tried to deliberately break something. If we were to try and investigate that, we'd need a minimal reproduction case that reliably displays the problematic behaviour. Since we're applying the configurations you've shared with us from scratch and not seeing the issue and you have multiple configurations that share this module that also don't display the behaviour, it's difficult for us to investigate this.

As a very hacky approach to unblock this particular use case, you could always try and manually edit the state file to add the missing `create_before_destroy` attribute in, since it definitely seems in this case something outside Terraform has managed to break the troublesome state file.

**Comment by igoratencompass** [comment]
Hi @liamcervante ,

> In the original bug you call out `aws_security_group` as not having the correct value in the state, but in your most recent comment you mention `aws_autoscaling_group` and I just wanted to clarify which direction the `create_before_destroy` attribute propagates.

You are right, copy-paster error I corrected it in the post above. Sorry about that :-/

And since this is one of case that I solved by editing the state file as mentioned I don't think there is a need spending any more time on it. I'm happy to close this case.

Thank you all for your time and effort.
