### ISSUE TITLE
Cross-reference Input Variable Validation error

### ISSUE THREAD

**Issue by Amarquier** [hashicorp/terraform#35455]
### Terraform Version

```shell
$ terraform -version
Terraform v1.9.2
on linux_amd64
```

### Terraform Configuration Files

```
variable "private_subnet_cidr_blocks" {
  description = <<-EOT
Private Routed subnet CIDR block list. Eg. ["10.0.0.0/28"].
Conflicts with private_subnet_cidr_blocks_size
EOT
  type        = list(string)
  default     = []
   validation {
     condition     = var.private_subnet_cidr_blocks_size == []
     error_message = "Can't use both CIDR blocks and CIDR blocks size at the same time"
   }
}

variable "private_subnet_cidr_blocks_size" {
  description = <<-EOT
Private Routed subnet CIDR block list. Eg. [”28"].
Conflicts with private_subnet_cidr_blocks
EOT
  type        = list(string)
  default     = []
   validation {
     condition     = var.private_subnet_cidr_blocks == []
     error_message = "Can't use both CIDR blocks and CIDR blocks size at the same time"
   }
}
```

### Debug Output

Setting the variable TF_LOG=trace didn't changed the output.

### Expected Behavior

According to [this post](https://discuss.hashicorp.com/t/experiment-feedback-input-variable-validation-can-cross-reference-other-objects/66644) I should be able to cross reference other variables in the "validation" section of my variable since terraform 1.9.0.
I used versions 1.9.0, 1.9.1 and 1.9.2 without success.

### Actual Behavior

│ Error: Invalid variable validation condition
│ 
│   on variables.tf line 352, in variable "private_subnet_cidr_blocks_size":
│  352:     condition     = var.private_subnet_cidr_blocks == []
│ 
│ **The condition for variable "private_subnet_cidr_blocks_size" must refer to**
│ **var.private_subnet_cidr_blocks_size in order to test incoming values.**

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

We are using terragrunt over terraform.
Terraform required version is ">= 1.9.0" for our repo.

**Comment by liamcervante** [comment]
Hi @Amarquier, thanks for filing this!

My understanding of the error message is that while you can refer to other variables, you must still refer to the original variable within the condition as well. As such I believe this is a case of Terraform working as designed.

However, I think even if you were to update the conditions so they passed this validation check you would see a second error message referencing the cycle that has been created. Since the variables now refer to each other, they both need the other one to be evaluated by Terraform before themselves, which is impossible since they refer to each other.

I think you can model what you are trying to do by just validating one of them, and referencing both:

```
variable "private_subnet_cidr_blocks" {
  description = <<-EOT
Private Routed subnet CIDR block list. Eg. ["10.0.0.0/28"].
Conflicts with private_subnet_cidr_blocks_size
EOT
  type        = list(string)
  default     = []
}

variable "private_subnet_cidr_blocks_size" {
  description = <<-EOT
Private Routed subnet CIDR block list. Eg. [”28"].
Conflicts with private_subnet_cidr_blocks
EOT
  type        = list(string)
  default     = []
   validation {
     condition     = condition = length(var.private_subnet_cidr_blocks) > 0 ? length(var.private_subnet_cidr_blocks_size) == 0  : length(var.private_subnet_cidr_blocks_size) > 0
     error_message = "Can't use both CIDR blocks and CIDR blocks size at the same time"
   }
}
```

The validation rules for all the variables are executed on every operation, even if those variables are set to the default values so you don't need to validate both of them as the validation rule of a single one can validate both.

Note, the rule I've written means that at exactly one of the those two variables must be set. You'll need to tweak it slightly if at most one can be set, but both could be empty.

**Comment by Amarquier** [comment]
Hello, I tuned it a bit so both can be empty and it works, thanks for pointing me in the right direction !
