### ISSUE TITLE
Changes on TypeSet and TypeList attributes when it is null in state file 

### ISSUE THREAD

**Issue by shanye997** [hashicorp/terraform#35475]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_arm64
+ provider registry.terraform.io/aliyun/alicloud v1.227.0
```

### Terraform Configuration Files

```terraform

import {
	id = "rm-xxxx"
	to = alicloud_db_instance.instance-import
}	
```

### Debug Output

no

### Expected Behavior

no changes

### Actual Behavior

![image](https://github.com/user-attachments/assets/0e97f2e4-b255-4754-8fb5-5a715e198e6c)

### Steps to Reproduce

1. terraform plan -out=tf.tfplan -generate-config-out=generate.tf
2. terraform apply tf.tfplan             
3. terraform plan

### Additional Context

Hi!

I want to import resource into alicloud_db_instance.  The type of attribute `security_group_ids` is TypeSet.
In the read function of this resource,  the security_group_ids will not be set if the content is null, so I got `"security_group_ids": null` in state file after `terraform import`.
After the import command, when I execute `terraform plan`, it shows the changes on `security_group_ids`. If I apply the changes, the `security_group_ids` in state file will be modified to `[]` and the problem is solved. But if the type of attribute is TypeList, the diff will not disappear after I execute `terraform apply` command.

How can I solve this problem? Should all TypeList or TypeSet attributes be set in read function?

**Comment by liamcervante** [comment]
Hi @shanye997, thanks for filing this!

I see in [the implementation](https://github.com/aliyun/terraform-provider-alicloud/blob/ed4adec8c5e751d1ae18c03fe9de0de4f1265afe/alicloud/resource_alicloud_db_instance.go#L212-L217) of this resource, that the `security_group_ids` attribute is marked as `computed` which means if it is not set in the config, the expectation is that it will be set by the provider.

I also see when the resource is read the `security_group_ids` is only set if the number of ids is greater than 0, which explains why it is null in the state after import: https://github.com/aliyun/terraform-provider-alicloud/blob/ed4adec8c5e751d1ae18c03fe9de0de4f1265afe/alicloud/resource_alicloud_db_instance.go#L1815-L1818

So, I think what's happening here is when the resource is imported it sets the value to null, and then later when it is planned the provider proposes creating the empty value you see here. I don't think this is anything that Terraform Core is doing unfortunately. Potentially, returning an empty collection within the read function instead of a not setting anything may fix this for you.

I'm going to close the issue here as it's not something that Terraform Core would normally help with - I don't know where the empty list / set is coming from and the experts for this will be our developer experience team. It's likely this behaviour is controlled by the SDK, so you could file an issue directly with the SDK in https://github.com/hashicorp/terraform-plugin-sdk, or alternatively posting in [the Discuss forums](https://discuss.hashicorp.com/) where you you will find help from the community who have seen this issue before. 

Thanks!

**Comment by liamcervante** [comment]
>  I raised this issue to confirm if the null value and empty collection is different to TypeSet and TypeList in Terraform Core

This is indeed true. A `null` attribute of any kind is generally treated as being "not set", while an empty collection behaves the same as any kind of set / provider attribute.

> Besides, I found if the type of attribute is TypeList, the diff will not disappear after I execute terraform apply command. I'm wondering why TypeSet and TypeList attributes don't behave the same way.

This, I think, shouldn't be true. Terraform Core doesn't (or at least shouldn't be) varying the way it treats attributes in terms of null vs not null regardless of the type. However, there may be differences in the way the SDK handles different types, there are layers of indirection between Terraform Core and the code that you write that attempt to normalise and standardise various provider behaviours. I don't know whether that kind of behaviour is expected, however, and that could be better answered by the team over in the SDK repository.

> should the developer of Providers avoid to setting nothing in this type of attribute

In general, I'd say the answer to this question is yes. There is a lot of implicity and uncertainty around the meaning of null and unset values. I think the new provider-framework does a better job of handling this than the SDK. But, setting a concrete value anywhere goes a long way in resolving any kind of uncertainty that comes from having null values in the state.

**Comment by shanye997** [comment]
Hi @liamcervante !
It's very helpful! Thanks a lot!
