### ISSUE TITLE
aws_elasticache_cluster - Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by mormayr** [hashicorp/terraform#35470]
### Terraform Version

```shell
1.7.5
```

### Terraform Configuration Files

```terraform

terraform {
  required_version = ">= 0.15.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.58.0"
    } 
}

resource "aws_elasticache_cluster" "this" {
...
  apply_immediately = true
...
}

output "provisioned_nodes" {
  value = join(",", formatlist("%s:%s", aws_elasticache_cluster.this[0].cache_nodes[*].address, aws_elasticache_cluster.this[0].cache_nodes[*].port))
}

```

### Debug Output

N/A

### Expected Behavior

the `provisioned_nodes` output to be the same in plan and apply stages. 

### Actual Behavior

When modifying the number of cache nodes in an existing cluster, the `provisioned_nodes` output is different in plan and apply stages. 
In the plan stage, it returns the number of the cache nodes in the existing cluster, and apply returns the new number of nodes, causing the apply stage to fail. 

### Steps to Reproduce

1. create an aws_elasticache_cluster with x cache nodes 
2. alter the number of cache nodes in the cluster
3. run plan + apply 

### Additional Context

`│ Error: Provider produced inconsistent final plan
`

**Comment by apparentlymart** [comment]
Hi @mormayr!

The "Provider produced inconsistent final plan" error typically reflects a bug in the provider plugin rather than in Terraform Core. Please report this in [the AWS provider's repository](https://github.com/hashicorp/terraform-provider-aws) instead, and then the provider development team can open a bug here themselves if they conclude that Terraform Core was incorrect to treat this response as "inconsistent". Thanks!
