### ISSUE TITLE
Same statefile produces semi-random failures during destroy

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform#35503]
### Terraform Version

```shell
Terraform v1.9.2
on linux_amd64
+ provider registry.terraform.io/datadrivers/nexus v2.3.0
+ provider registry.terraform.io/drfaust92/bitbucket v2.42.0
+ provider registry.terraform.io/hashicorp/archive v2.4.2
+ provider registry.terraform.io/hashicorp/aws v5.59.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
+ provider registry.terraform.io/poseidon/ct v0.13.0
```

### Terraform Configuration Files

This is private code, and I think it's not relevant in this case

### Debug Output

I try but github tell me the file is too large. Do you have any other place for a 500MB file ?

### Expected Behavior

The plan should be a success each time

### Actual Behavior

Randomly got issue that looks like this (not the same error each time, and sometimes the plan pass without error, see more in the additional context)

```
╷
│ Error: Invalid index
│ 
│   on /tmp/testTerraform/modules/example.jenkins.efs.kms/main.tf line 328, in output "kms_key":
│  328:         aws_kms_alias.this[key].arn,
│     ├────────────────
│     │ aws_kms_alias.this is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
╵
```

### Steps to Reproduce

1. terraform destroy -var=aws_assume_role='REDACTED' -var=deployer_name='REDACTED' -refresh=false

### Additional Context

Hello :wave: 

We have weird issue with TF. 

Our inits, plans, and applies never failed but the destroys are *randomly* failing.

Tested in various environments:

With our CI, we have about a 90% failure rate.
With my laptop, it's around a 50% failure rate.
With my colleague laptop, there is no failure.

Context of tests, for every environments:
- Using exactly the same state.
- Identical terraform.hcl.lock.
- Identical state folder (TF_DATA_DIR) content
- All machines with at least 16GB RAM and 8 CPUs

The command is `TF_DATA_DIR=/tmp/testTerraform TF_LOG=trace TF_LOG_PATH=tf.log terraform destroy -var=aws_assume_role='REDACTED'`

The errors change, but each are a the flavor of “The given key does not identify an element in this collection value.”. For example:
╷
│ Error: Invalid index
│ 
│   on /tmp/testTerraform/modules/example.jenkins.efs.kms/main.tf line 328, in output "kms_key":
│  328:         aws_kms_alias.this[key].arn,
│     ├────────────────
│     │ aws_kms_alias.this is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
╵
As if the statefile was incomplete (it’s not). They occur during the destroy plan, the refresh goes well.

I’m enclosing:
- A trace of a failed destroy
- A trace of a successful - but not applied - destroy

We cannot reproduce the issue with Terraform 1.8

Is there any more tests we can perform to help pin point what’s going on?

**Comment by jbardin** [comment]
Hi @quentin9696,

Thanks for filing the issue. You could try generating the logs with `TF_LOG_CORE=trace` and see if that helps reduce the size, some providers are very verbose in the log output. The fact that it's an output failing during destroy is a good clue, as well as it being intermittent. I have an idea where to start looking, but if you do get the logs that might help too.

**Comment by quentin9696** [comment]
Hi @jbardin 

Thank you for your reply. We are already is log core and files are 350MB and 500MB. Do you have any clue where I can push logs to you?

**Comment by jbardin** [comment]
If that's the raw log size. Rather than creating a gist could you compress the data and attach the file?

**Comment by quentin9696** [comment]
I forget that option. Here are logs: 

[tf.log.fail.zip](https://github.com/user-attachments/files/16381323/tf.log.fail.zip)
[tf.log.sucess.zip](https://github.com/user-attachments/files/16381324/tf.log.sucess.zip)

**Comment by jbardin** [comment]
Thanks for the logs @quentin9696, would it be possible to also provide the configuration? I could ask for specific parts, like the `output.kms_key` block from `example.jenkins.efs.kms/main.tf`, but we may have to go back and forth a few times to figure out how the dependencies are organized.

The graph is the same for both logs (which makes sense since this is the same config and state), so my guess is that your configuration is somehow triggering a case where Terraform is not correctly setting a dependency between some nodes, causing the order to be undefined.

**Comment by gui-don** [comment]
@jbardin half of our code is close-sourced and licensed under our company name.

I’m gonna try to obtain validation to share the code with you but we would need a private channel for this. Would it be ok for you or do you see an alternative?

**Comment by gui-don** [comment]
No problem, just got the approval!

@quentin9696 is gonna send you the exact Terraform state (.terraform) containing initialized projects. So you can browse the complex structure freely, with the exception of account IDs if the appear, will be redacted.

**Comment by quentin9696** [comment]
@jbardin the email have been send. Let me know if you need anything else

**Comment by jbardin** [comment]
Hi @quentin9696, you said this plan works consistently with v1.8, would it be possible to get the `TF_LOG_CORE=trace` log from that version for comparison? The sheer size of this config is making it hard to track down and replicate what might be happening.

**Comment by gui-don** [comment]
I’m gonna try to generate these today.
Since I have a potentially different `terraform.tfstate` and environment, I’m gonna try to regenerate a tf. 1.9.2 success, 1.9.2 fail along with a 1.8.5 success. If I can’t quentin’s gonna do it next week.

Additional information to help you debug:
- we had high error rates specifically in big an complex tests like the one you have;
- powerful machines *seems to* have a slightly higher success rate, while still failing often (we’ve tried up to 16c 32GB);
- setting TF_LOG *seems to* lower the success rate drastically;
- changing the runtime *seems to* have an effect on the success rate (docker succeed more, podman fails more, direct binary usage seems to be between the two);
- we didn’t see significant difference with different OSes (tried latest fedora, archlinux, unbuntu 22, ubuntu 24);

**Comment by jbardin** [comment]
Thank you @quentin9696  and @gui-don! The problem is cause by the new feature to allow references from variable validation rules. Those new references on their own are causing Terraform to build an incorrect graph during destroy in combination with expanded modules and their outputs, but that usually still works as expected. It takes some specific misalignments between the configuration and the state (usually from an incomplete prior apply or destroy) to actually cause the error you're seeing during the plan.

**Comment by gui-don** [comment]
Awesome finding. Thanks!

It’s true that we could consistently have the issue in case of a prior apply failure (e.g. resource limit on AWS), so that makes sense.

**Comment by quentin9696** [comment]
@jbardin thank you for your reactivity on that one !
