### ISSUE TITLE
"Invalid template interpolation value" after moving value to local

### ISSUE THREAD

**Issue by natedogith1** [hashicorp/terraform#35564]
### Terraform Version

```shell
Terraform v1.9.3
on windows_386
+ provider registry.terraform.io/hashicorp/null v3.2.2
```

### Terraform Configuration Files

main.tf
```terraform
module "test_module" {
  source = "./test_module"
  input = null
}
```

no-error test_module/main.tf
```terraform
variable "input" {

}

locals { 
  #test_value = "|${var.input}|"
}

resource "null_resource" "base" {
  count=0
  #triggers = {input=local.test_value}
  triggers = {input="|${var.input}|"}
}
```

error test_module/main.tf
```terraform
variable "input" {

}

locals { 
  test_value = "|${var.input}|"
}

resource "null_resource" "base" {
  count=0
  triggers = {input=local.test_value}
  #triggers = {input="|${var.input}|"}
}
```

### Debug Output

no-error test_module/main.tf: https://gist.github.com/natedogith1/314f22246634830e9b6364507ef9f6b2
error test_module/main.tf: https://gist.github.com/natedogith1/2cb7835c9dc3ff101ac5349cfb431fbb

### Expected Behavior

Both versions of test_module/main.tf should behave the same

### Actual Behavior

The test_module/main.tf the directly references the value succeeds, but the one that puts the value in locals errors.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @natedogith1

The difference you are seeing here is that with `count=0` the configuration for the `null_resource` is not fully evaluated, and the error is never surfaced. If you had `count=1` then you would get the same null value error within that configuration too.
The `local` value always needs to be evaluated, and the error is hit before we even get to determine if the `null_resource` is going to be evaluated or not.

**Comment by jbardin** [comment]
Hi @natedogith1, Terraform is working as designed, I'm not sure what a resolution here would be. You have an invalid expression for `local.test_value`, and terraform is returning an appropriate error. The solution would normally be to use an expression which handled the `null` case and resulted in a string.

```
test_value = var.input != null ? "|${var.input}|" : ""
```

**Comment by natedogith1** [comment]
Would it make sense to have terraform only evaluate locals when they're used, same as it seems to do with resources with a count specified?

**Comment by jbardin** [comment]
As far as the configuration is concerned `local.test_value` is being used, because it is referenced from `null_resource.base` and needs to be evaluated before we can evaluate  to find out what isn't used.

The evaluation of the `count` argument is acting like a conditional here, so you could sort of think of the config body as being an expression that resembles: 

```
body = count != 0 ? {triggers = {input = local.test_value"}} : {}
```

All references within the resource block must be resolved before we start to evaluate the resource block.

Now technically even if `local.test_value` isn't referenced, it currently will still be evaluated (in most versions at least, what happens to unused values is an implementation detail. If at any point in the future known values are stored in the plan for various reasons then we still might need it for the apply operation). Terraform doesn't try to prune out evaluation nodes except during destroy operations, because it aims to prove as thoroughly as possible the configuration is valid. Evaluating a `null` into a string template is invalid, and the expression should be changed to handle that. If the input variable should never be `null`, then it should be declared with `nullable=false` and a suitable non-null default so you never need the conditional checks.

**Comment by apparentlymart** [comment]
It seems to me that the closest equivalent to the original example would be for the local value to be a list that could have zero or one elements:

```hcl
variable "input" {

}

locals { 
  test_value = tolist(["|${var.input}|"])
  # or:
  # test_value = tolist([])
}

resource "null_resource" "base" {
  count    = length(local.test_value)
  triggers = {input = local.test_value}
}
```

The length of `local.test_value` then serves the same purpose as the `count` originally had.

I assume that in the real configuration this was based on that the `count` was conditional based on something from elsewhere, in which case the condition from `count` would move to be a condition in the local value expression instead.

That is, instead of writing the following in the `resource` block...

```hcl
  count = var.predicate ? 1 : 0
```

...you'd move that condition into the local value expression...

```hcl
locals { 
  test_value = var.predicate ? ["|${var.input}|"] : []
}
```

...and so then the template using `var.input` would be evaluated only if `var.predicate` is true, as before.
