### ISSUE TITLE
Dependency chain in aws_iam resources insufficient

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#3557]
I have a terraform configuration which creates

* aws_instance
* using an iam_instance_profile
* using an iam_role
* an iam_role_policy attached to the iam_role.

The dependency chain of terraform should insist that each resource is fully created before creating the dependent resource. But it doesnt (terraform 0.6.3)

Instead I have to terraform *3 times* in order to get the desired state.

The first time I get:

aws_iam_instance_profile.foo: Error adding role foo-iam-role to IAM instance profile foo_iam_instance_profile: NoSuchEntity: The role with name foo-iam-role cannot be found. 
	status code: 404, request id: [...]

The second time I get:

aws_instance.bar: Error launching source instance: InvalidParameterValue: IAM Instance Profile "arn:aws:iam::############:instance-profile/bar_iam_instance_profile" has no associated IAM Roles

The third time, it finally terraforms into place.

Either terraform is not checking the result of some of the iam resources its creating, or its trying to create the dependent resources too quickly, or there is no proper dependency checking. The dependency chain of IAM seems horribly broken.

**Comment by catsby** [comment]
Hey @gtmtech – do you have an example config I can test with?

IAM has given us grief in the past, in that we'll issue `CREATE` commands that report `SUCCESS`, but follow up `READ` calls essentially give a 404. The IAM docs mention that it can take some time for all resource to propagate, and there isn't much we can do there other than add `sleep()` commands.

If you have an example config I can try to confirm this is the case.

**Comment by catsby** [comment]
Closing from inactivity for now. If you do have a config that reproduces this I can re-open and take a look. Thanks!

**Comment by vancluever** [comment]
@catsby I'm think this is the issue that I'm referencing in my PR (see #4093). I'm going to fool around with waiters on the weekend (see [here](https://github.com/aws/aws-sdk-go/blob/ce51895e994693d65ab997ae48032bf13a9290b7/private/waiter/waiter.go)) to see if this helps.

Also see [the pre-existing IAM waiters](https://github.com/aws/aws-sdk-go/blob/ce51895e994693d65ab997ae48032bf13a9290b7/service/iam/waiters.go), although these waiters only cover a few of the scenarios that may be needed. I'm personally seeing them on IAM roles, policies, and/or policy attachments.

**Comment by gatoruso** [comment]
After a couple of months of steady terraform use, an invocation of apply hit an error creating an IAM instance profile because the specified IAM role (created during the same invocation) was not found:
```
* aws_iam_instance_profile.node_instance_profile: Error adding role node_iam_role-8304ddc0-03a0-40ba-afae-042d790db41c to IAM instance profile node_instance_profile-8304ddc0-03a0-40ba-afae-042d790db41c: NoSuchEntity: Role not found for node_iam_role-8304ddc0-03a0-40ba-afae-042d790db41c
```
Later, we confirmed that both the IAM role and (oddly) the instance profile had been created. Our best guess is we hit the IAM API behavior described in https://github.com/hashicorp/terraform/issues/3557#issuecomment-149711293. Unfortunately, we can't reproduce this ourselves, and don't have the debug logs for this invocation of apply.

**Comment by gatoruso** [comment]
Our terraform configuration includes an IAM instance profile, and a role that is added to this profile. We run integration tests that use this configuration dozens of times per day, and we are hitting this issue around once per day.

@catsby I agree with you that the root cause appears to be the IAM service, which is [eventually consistent by design](http://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency). I will try to reproduce the issue by applying a minimal configuration (i.e. profile and role only) repeatedly, with the expectation that it will eventually happen. I'll post the results.

If the root cause can be reproduced, then I propose adding a retry to [the method to add a role to a profile](https://github.com/hashicorp/terraform/blob/v0.8.7/builtin/providers/aws/resource_aws_iam_instance_profile.go#L138), and to other methods that invoke the IAM API. Whenever the IAM API returns a 404, the method will retry, up to some finite amount of time. The potential downside is in this arguably unusual case: If the 404 is not due to eventual consistency but because the resource was deleted, then the retries will only waste time.

**Comment by santiagopoli** [comment]
Hi, I'm having this exact issue using the 1.13.0 version of the AWS Provider. I was able to fix it by adding a sleep in a local executor, but it's not very nice.
