### ISSUE TITLE
Type conversion of empty map in conditional expressions

### ISSUE THREAD

**Issue by cyuanli** [hashicorp/terraform#35662]
### Terraform Version

```shell
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.6.2
```

### Terraform Configuration Files

```terraform
locals {
  outer_map = true ? {
    inner_map = {
      key = "value"
    }
  } : {}
}

resource "random_string" "default" {
  length = lookup(local.outer_map, "inner_map", {}) != {} ? 4 : 2
}
```

### Debug Output

https://gist.github.com/cyuanli/7bf788279dbddb48bec71808bf4ea11d

### Expected Behavior

The type of `local.outer_map` should be accepted by `lookup` with default `{}`. It should create a `random_string` with `length = 4`.

### Actual Behavior

An error is thrown: 
```
╷
│ Error: Invalid function argument
│
│   on test.tf line 10, in resource "random_string" "default":
│   10:   length = lookup(local.outer_map, "inner_map", {}) != {} ? 4 : 2
│     ├────────────────
│     │ while calling lookup(inputMap, key, default...)
│
│ Invalid value for "default" parameter: the default value must have the same type as the map elements.
╵
```

### Steps to Reproduce

1. `terraform init`
1. `terraform validate`

### Additional Context

The two expressions work fine on their own:
```
  outer_map = {
    inner_map = {
      key = "value"
    }
  }
```
```
  outer_map = {}
```
It is the automatic conversion of the conditional expression that casts them into a type that is not accepted by `lookup`.

**Comment by jbardin** [comment]
Hi @cyuanli,

There are a few issues with this configuration, but you are correct that the results can be somewhat confusing until one is more familiar with the type system used in Terraform.

Because the conditional expression has differently typed literals in the tru and false clauses, Terraform must find a unified type that satisfies both branches, which in this case it is a `map(object({key: string}))`. This map+object type is failing to unify back again with an empty object type, probably due to a combination of a somewhat simplistic algorithm in unification, and the fact that an empty object is not really a useful resulting type for the function.

One would not normally write configuration like this however, since an empty object (`{}`) is in a sense a singleton value and only ever equal to another explicit empty object (the same goes for empty tuple, `[]`). So even if the `lookup` called succeeded in converting the type, the resulting value could never be equal to `{}`.  If you want to indicate the absence of a value you should use `null` which can represent any type. 

A valid way of writing this expression would be:
```
lookup(local.outer_map, "inner_map", null) != null
```

If this type of check is being done because the type of the input data is unknown, it is often better to use the [`try` function](https://developer.hashicorp.com/terraform/language/functions/try) instead, which can handle more dynamically typed data, but an empty object literal should still be avoided as a sentinel value for comparison.
