### ISSUE TITLE
Possible dependency issue with change to launch configuration

### ISSUE THREAD

**Issue by eoliphan** [hashicorp/terraform#3567]
I'm having an issue where when I update a launch configuration, the plan phase correctly reports a -/+ for the configuration itself, but doesn't mention the autoscaling group that uses it.  And sure enough, when I attempt to apply it I get a

```
 aws_launch_configuration.launchconfig: ResourceInUse: Cannot delete launch configuration xxx because it is attached to AutoScalingGroup yyy
```

Shoudn't terraform know about the dependency and recreate the ASG, etc as necessary as well?

**Comment by catsby** [comment]
Hey @eoliphan – can you share the configuration you're using that demonstrates this? Omit any secrets please :smile: . If it's a typical setup, you're unlikely to be changing the Launch Configurations `name` property, which is what the ASG is depending on. 

Unfortunately, the AWS API does not offer any update method for Launch Configurations; they must be completely destroyed and recreated. As you've found, a Launch Configuration cannot be destroyed if an exiting AutoScaling Group is using it. Recreating the ASG is likely not the desired behavior here either. 

What you can do is omit the `name` property from the LC, and let Terraform auto assign it a unique id. Then include the `create_before_destroy` lifecycle block to both the Launch Configuration, which instructs Terraform to create a new LC before trying to destroy the old one. Because the `name` which the ASG depends on is now changing, it too will show a change. 

Terraform will create the new LC, update the ASG, and then destroy the old LC. This strategy is also mentioned here in the docs:

- https://terraform.io/docs/providers/aws/r/launch_configuration.html

There's also an important note about the `create_before_destroy` lifecycle block here:

- https://terraform.io/docs/configuration/resources.html

Sorry for the trouble here, we're a bit limited by the API at the moment.

**Comment by eoliphan** [comment]
Hi, do you want me to try this prior to sending it over? and yeah it's 'named' so that would seem to run into this issue as you've outlined it.

**Comment by catsby** [comment]
If that's clearly the case, then I suppose I don't need the configuration file. Until the AWS API provides an Update method for Launch Configurations, we're at the mercy of using this nameless `create_before_destroy` workaround. 

I'm going to close this for now, let me know if there's anything else I can do here.
