### ISSUE TITLE
I am not able to create multiple VMs which belong to the same service

### ISSUE THREAD

**Issue by ravbaba** [hashicorp/terraform#3568]
I am able to create VMs  but only if each of them belong to a separate service but if I am trying the below code to create multiple VMs assigned to the same service I am not able to create anything. Is there something wrong with my code or it is a bug?

```
resource "azure_hosted_service" "terraform-service" {
    name = "terraform-service"
    location = "North Europe"
    ephemeral_contents = false
    description = "Hosted service created by Terraform."
    label = "tf-hs-01"
}

resource "azure_instance" "web" {
    name = "terraform-test-${count.index}"
    count = 3
    hosted_service_name = "${azure_hosted_service.terraform-service.name}"
    image = "Ubuntu Server 14.04 LTS"
    size = "Basic_A1"
    storage_service_name = "yourstorage"
    location = "West US"
    username = "terraform"
    password = "Pass!admin123"

    endpoint {
        name = "SSH"
        protocol = "tcp"
        public_port = 22
        private_port = 22
    }
}
```

I got the error:

```
* Error creating instance terraform-test-0: Error response from Azure. Code: ConflictError, Message: The specified deployment slot Production is occupied.
* Error creating instance terraform-test-2: Error response from Azure. Code: ConflictError, Message: The specified deployment slot Production is occupied.

```

**Comment by kbxkb** [comment]
This is a big one. Facing the same issue. Tried a lot of different things, still getting the same issue. It appears that Azure-wise there is a solution. The last post on this thread discusses the solution from the Azure side: http://answers.flyppdevportal.com/categories/azure/azuredevelopment.aspx?ID=4d8faa0e-557c-4a97-b76b-c611ab21cec8

Agreed that the solution from Azure side is ugly, but still should work. Can someone implement the solution on the terraform side please? Thanks!

**Comment by coreyperkins** [comment]
I am seeing this as well. I can make it happen two different ways.

1) Create a config with a single hosted service and a single azure instance. Plan/Apply. Then, add a second azure instance to the config and do another Plan/Apply.

2) Create a config with a single hosted service and two azure instances. Plan/Apply. End result will be that one of the instances will get created and you'll receive the error message above when it tries to create the second instance.

Pretty well limits what you can do with Azure atm.

**Comment by kbxkb** [comment]
+1 To fix this problem, we have to

(1) add an AddRole function here: https://github.com/Azure/azure-sdk-for-go/blob/master/management/virtualmachine/client.go

(2) use that function in resource_azure_instance.go here: https://github.com/hashicorp/terraform/blob/master/builtin/providers/azure/resource_azure_instance.go

(in resourceAzureInstanceCreate(...) and possibly in Update/Delete as well - so that when an azure instance is created, and hosted_service_name is specified, it should call this new AddRole function and add the new VM to an existing cloud service. However, it may be tricky and error-prone, as there is already some not-so-readable logic around "has_dedicated_service", so the developer who added that piece of logic should probably do it and test it properly)

**Comment by kbxkb** [comment]
@mitchellh @catsby @armon @phinze - Sorry to spam you, but I am assuming one or more among you have the power to assign this bug to me. I am actively working on this, and will have a fix that i can submit a pull request for soon. I have already made changes to the underlying azure-sdk-for-go code, and my changes were merged today (see https://github.com/Azure/azure-sdk-for-go/pull/234)

Thanks

**Comment by kbxkb** [comment]
Update - this bug is fixed on my fork. Depends on some changes that needed to be made to azure-sdk-for-go. The last of such changes to azure-sdk-for-go is pending as a pull request here: https://github.com/Azure/azure-sdk-for-go/pull/238. Previous changes to azure-sdk-for-go have been accepted and merged in this pull request: https://github.com/Azure/azure-sdk-for-go/pull/234

Once azure-sdk-for-go is updated, I will submit terraform changes as a pull request.

Requesting assignment of this bug to me. Thanks.

**Comment by kbxkb** [comment]
If anyone is interested to review the fix, it is contained to one file in terraform (resource_azure_instance.go), but it depends on some changes made to azure-sdk-for-go - they can view the changes here: https://github.com/hashicorp/terraform/compare/master...kbxkb:master

**Comment by kbxkb** [comment]
Update: A fix for this bug is awaiting to be reviewed, accepted and merged: https://github.com/hashicorp/terraform/pull/4199
