### ISSUE TITLE
Chef Provisioner: Don't overwrite existing /etc/chef/first-boot.json

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#3572]
It would be nice if `terraform-provisioner-chef` did not overwrite an existing `/etc/chef/first-boot.json` when it runs. We would like to dynamically upload a json attributes file based on a var but are unable to because the provisioner replaces the existing file. 

We want to be able to do something like this. 

```
resource "openstack_compute_instance_v2" "server" {
  name = "test-server"
  provisioner "file" {
      source = "chef/${var.chef-attrib-json}"
      destination = "/etc/chef/first-boot.json"
  }
  provisioner "chef" {
    run_list = ["role[test-server]"]
    ...
  }
  ...
}
```

**Comment by svanharmelen** [comment]
@mtougeron I think we can add an option to the Chef provisioner to specify a `first-boot.json` file (or the content for the `first-boot.json` file) that can be used instead of having the provisioner buildup that file for you based on the given config.

What would be harder is having both like you show in your example. The initial `run_list` is part of the `first-boot.json`, so if you specify a `first-boot.json` the `run_list` info should already be in there. Would that be a problem? If not we can add this feature by adding a new parameter.

**Comment by mtougeron** [comment]
The -j and -r flags would be preferred in my scenario.

**Comment by RCM7** [comment]
:+1:

**Comment by partamonov** [comment]
It's also can be useful to remove all data except attributes from `first-boot.json`.
* environment with `-e ENVIRONMENT`
* log_to_file with `-L LOG_FILE_PATH`

Another thing, if we will have only attributes in `first-boot.json` then we can also place attributes as rendered template_file, this will allow bypass limitations on attributes structure.

```
{
  "key": [
    {
      "subkey": "value"
    }
  ]
}
```

**Comment by svanharmelen** [comment]
Currently there are only attributes and the `run_list` in the `first-boot.json`. In newer 12.x Chef clients we could pass the `run_list` using the `-r` parameter leaving the `first-boot.json` file with only the attributes, but that is not possible with Chef 11.x clients. So I'm a little hesitant to go that route...

I'm currently looking at another angle to fix/improve this, but will need to test some stuff first. Will update this issue early next week or so.

**Comment by partamonov** [comment]
Ahh, true. I was absolutely sure I used -r in 11, but it was for knife bootstrap.
