### ISSUE TITLE
prevent_destroy prevents initial creation

### ISSUE THREAD

**Issue by mcqj** [hashicorp/terraform#35758]
### Terraform Version

```shell
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.68.0
```

### Terraform Configuration Files

```terraform
resource "aws_dynamodb_table" "xxx_table" {
  name           = "${var.prefix}_roleplays_${var.stage}"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "xxxId"

  attribute {
    name = "xxxId"
    type = "S"
  }

  attribute {
    name = "createdAt"
    type = "N"
  }

  attribute {
    name = "createdBy"
    type = "S"
  }

  tags = {
    Name        = "xxx table"
    Environment = var.stage
  }

   point_in_time_recovery {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }
}
...terraform config...
```

### Debug Output

NA

### Expected Behavior

Resource should be created.

### Actual Behavior

Terraform gave an error saying that the plan called for the resource to be destroyed when prevent_destroy was set to true. In fact, this is the first time running the plan so no resources have ever been created, so the plan should not call for a resource to be deleted when that resource has never been created.

### Steps to Reproduce

Use terraform resource to create a dynamo db table with prevent_destroy and run terraform apply.

**Comment by jbardin** [comment]
Hi @mcqj,

There must be something not shown here, because the error associated with `prevent_destroy` don't be shown unless there is actually a destroy or replace operation being planned. This means there must be some pre-existing state which contains the resource you are trying to change, either from a forgotten earlier state, or maybe via an import of the resource. Can you show a complete example of what you are trying to do?

**Comment by mcqj** [comment]
Hi @jbardin
