### ISSUE TITLE
Terraform errors when computed field value changes during an apply

### ISSUE THREAD

**Issue by amanshallow** [hashicorp/terraform#35765]
### Terraform Version

```shell
Terraform v1.9.6
on linux_amd64
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

Terraform should not return an error with `refresh=false` when a computed field changes during an apply.

### Actual Behavior

We have a computed field in our provider which changes after each apply. When creating a plan with `refresh=false` and running the apply it's failing because the new state value doesn't match the existing value with `Error: Provider produced inconsistent result after apply`. For example, the plan doesn't show the values(known after apply) so it shouldn't be failing when the value changes because that's expected for computed values.

### Steps to Reproduce

Apply a Terraform plan where a provider field is marked as Computed and expected to change after the apply. Terraform should not reject the update since the behavior is expected. 

### Additional Context

It should be noted that we do not use any plan modifiers for this field and it is of type `map[string]string`.

**Comment by jbardin** [comment]
Hi @amanshallow,

The situation you describe would be consistent with the provider not correctly updating the value during the plan, or not marking that value as computed during the plan in order to update it during apply. Whatever the situation is however, the provider _must_ always apply what it described in the plan, so a change in value between plan and apply is simply not allowed.

If your attribute updates with every apply, then the attribute must have a plan modifier to mark it as unknown if there are any changes, and update it to the correct value during apply. It sounds like you are relying on the refresh to catch this drift after the apply happens instead of applying the change directly (in other words, a `plan -refresh-only` should show no changes after apply).

If there is some support missing in the provider framework to handle this, I would suggest opening an issue with that project. If you have more questions about developing the provider for this type of resource, it would be better to ask in the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43), since this repo is only monitored by a few core developers.

Thanks!
