### ISSUE TITLE
Static validation bug (I think)

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform#35777]
### Terraform Version

```shell
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.15.0
+ provider registry.terraform.io/hashicorp/azuread v2.53.1
+ provider registry.terraform.io/hashicorp/azurerm v4.2.0
+ provider registry.terraform.io/hashicorp/random v3.6.3
```

### Terraform Configuration Files

```terraform
locals {
  nsg_rules = false ? {} : {
    rule1 = {
      priority = "262"
      ports    = "*"
      sources  = "this"
    }
    rule2 = {
      priority     = "263"
      ports        = "80"
      destinations = "this"
      tickets      = [134]
    }
  }
}
```

### Debug Output

│ Error: Inconsistent conditional result types
│ 
│   on main.tf line 107, in locals:
│  107:   nsg_rules = var.deploy == false ? {} : {
│  108:     rule1 = {
│  109:       priority         = "262"
│  112:       ports            = "*"
│  113:       sources          = "this"
│  115:       tickets          = []
│  116:     }
│  117:     rule2 = {
│  118:       priority         = "263"
│  121:       ports            = "80"
│  123:       destinations = "this"
│  124:       tickets          = [4182]
│  125:     }
│  126:   }
│     ├────────────────
│     │ var.deploy is true
│ 
│ The true and false result expressions must have consistent types. The
│ 'false' value includes object attribute "rule2", which is absent in
│ the 'true' value.
╵
 Operation failed: failed running terraform plan (exit 1)

### Expected Behavior

Plan succeeds.
Value of the local is passed into a module variable of defined type with defaults set that fill missing values.
```terraform
variable "nsg_rules" {
  type = map(object({
    access                 = optional(string, "Allow")
    protocol               = optional(string, "Tcp")
    priority               = string
    ports                  = optional(string, null)
    sources                = optional(string, "")
    destinations           = optional(string, "")
    tickets                = optional(list(number), [])
  }))
  description = "Map of maps of Inbound NSG Rules definitions"
  default     = {}
}
```

### Actual Behavior

Terraform requires to set `tickets = []` and `destinations = ""` in `rule1`, and `sources = ""` in `rule2`.

I believe this is static validation bug, which makes Terraform require all the same keys be defined in both maps.
But the weird part is this only happens after the addition of `tickets = [1234]`. Before then, one map defines only `sources` and the other only `destinations` and validation is happy with the difference!
The only pointer I see is that `tickets` is a `list()`, not a `string`, and addition of it in one map somehow changes how the whole evaluation. Still I think it's a bug. 🐛 

### Steps to Reproduce

1. define code like this
```terraform
locals {
  nsg_rules = false ? {} : {
    rule1 = {
      priority     = "262"
      ports        = "*"
      sources      = "this"
    }
    rule2 = {
      priority     = "263"
      ports        = "80"
      destinations = "this"
    }
  }
}
```
2. `terraform plan` -> everything is fine
3. add `tickets = [1]` into `rule2`
4. `terraform plan` -> FAILS
5. add `sources = ""` to `rule2` and `destinations = ""` and `tickets = []`  to `rule1`
6. `terraform plan` -> everything is fine

**Comment by jbardin** [comment]
Hi @Tbohunek,

The error you have is correct, the true expression is a single instance of an empty object type, and the false expression is an object with multiple nested object attributes. The overall expression must return a single type so that terraform can evaluation the entire configuration is valid regardless of which branch is taken.

Terraform will attempt to unify the types from the true and false branches, but that's not (currently) possible with what you have. The only resolution which would work here would be to find an object type which is a superset of the nested object, and use a `map` of that type (the same type as `nsg_rules`) so that it is a valid conversion from `{}`. As you can see, adding the missing attributes allows terraform to find a common type and convert the overall type to a map.

Thanks!

**Comment by Tbohunek** [comment]
Thanks for the explanation @jbardin , makes sense!

You say "currently", suggesting there might be a change in the future? Any references?
Naive assumption is that Terraform actually sees also all the attributes that come from the object defaults, but that clearly isn't the case, and implementing that behavior isn't worthwhile.

**Comment by jbardin** [comment]
"Currently" was just hedging against possible type inference improvements in the future, but there are no specific plans ;) 
The defaults don't come into play here, because the `local.nsg_rules` expression is evaluated separately, before it can be passed into the variable.

What's more likely is that a future version could have a way to declare more expressive inline type constraints. In the meantime for tricky situations I've used a local module with no other purpose than to declare specific variable types which are reflected as outputs to do the necessary conversions.
