### ISSUE TITLE
object or map of objects attribute of object variable has incorrect default value in tests

### ISSUE THREAD

**Issue by berahtlv** [hashicorp/terraform#35801]
### Terraform Version

```shell
Terraform v1.9.6
```

### Terraform Configuration Files

main.tf
```terraform
variable "object" {
  type = object({
    disks = optional(map(object({
      size = optional(number)
    })))
    root_disk = optional(object({
      size = optional(number)
    }))
  })
}
```
main.tftest.hcl
```terraform
run "object" {

  command = plan

  variables {
    object = {
    }
  }

  assert {
    condition = var.object == {
      disks = tomap(null)
      root_disk = null
    }
    error_message = "Value is incorrect"
  }
}

```

### Debug Output

terraform console
```
> var.object
{
  "disks" = tomap(null) /* of object */
  "root_disk" = null /* object */
}
```
terraform test
```
main.tftest.hcl... in progress
  run "object"... fail
╷
│ Error: Test assertion failed
│ 
│   on main.tftest.hcl line 57, in run "object":
│   57:     condition = var.object == {
│   58:       disks = tomap(null)
│   59:       root_disk = null
│   60:     }
│     ├────────────────
│     │ var.object is object with 2 attributes
│ 
│ Value is incorrect
╵
main.tftest.hcl... tearing down
main.tftest.hcl... fail

Failure! 0 passed, 1 failed.
```

### Expected Behavior

The test is passing.

### Actual Behavior

The test fails. An issue arises if a nested object or map of objects has a null value. In the case of assigning the `size` attribute test is passing.

Updated variables block:
```terraform
  variables {
    object = {
      root_disk = {
        size = 45
      }
      disks = {
        data = {
          size = 125
        }
      }
    }
  }
```
Update assert block:
```terraform
  assert {
    condition = var.object == {
      disks = tomap({
        data = {
          size = 125
        }
      })
      root_disk = {
        size = 45
      }
    }
    error_message = "Value is incorrect"
  }
```

### Steps to Reproduce

terraform test

**Comment by jbardin** [comment]
Hi @berahtlv,

The code is working here as expected, because equality always compares precise types first, and you have not created an object of the same type. The object literal in your condition has the type:
```
object({
    disks: map(dynamic),
    root_disk: dynamic,
})
```
which is not going to match the. There are no default values, because you are not passing a value into the input variable, which is where the type constraint with the defaults is defined. The only way to get the exact same type conversion right now would be to create a module with the same type constraints and pass the value through for comparison. In general it's more reliable to compare the attributes you want directly rather than as a group in nested literals.

We do have open enhancement requests already for easier inline type conversions, like #23562, #26164, #27643, etc.

Thanks!
