### ISSUE TITLE
[v1.10.0-alpha20240926] "An argument definition must end with a newline." for assume_role

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#35816]
### Terraform Version

```shell
Terraform v1.10.0-alpha20240926
on darwin_arm64
```

### Terraform Configuration Files

```terraform
...
assume_role    = { role_arn = "arn:aws:iam::XXXX:role/terraform" }
...
```

### Debug Output

```terraform
│ Error: Missing newline after argument
│
│   on dev.backend.tfvars line 4:
│    4: assume_role    = role_arn = "arn:aws:iam::XXXXXX:role/terraform"
│
│ An argument definition must end with a newline.
```

### Expected Behavior

for s3 backend to init just like 1.9 did

### Actual Behavior

does not like the partial config 

### Steps to Reproduce

`terraform init -backend-config dev.backend.tfvars -reconfigure -upgrade`

**Comment by jbardin** [comment]
Hi @FernandoMiguel,

I can't get the same error you have here, but according to the

**Comment by FernandoMiguel** [comment]
> Hi @FernandoMiguel,
> 
> I can't get the same error you have here, but according to the 

According to the.... What?
I think you press enter a tad to fast 😎

**Comment by jbardin** [comment]
sorry! somehow submitted while typing ;)

**Comment by jbardin** [comment]
I assume the change was intentional, but it should probably be called out better as a breaking change. The CHANGELOG entry is also incorrect since `assume_role` is not a block and must be assigned as a list of objects.

**Comment by FernandoMiguel** [comment]
> I assume the change was intentional, but it should probably be called out better as a breaking change. The CHANGELOG entry is also incorrect since `assume_role` is not a block and must be assigned as a list of objects.

I reviewed the alpha docs and it mentions nothing as a change to partial config either.

I understand it's an alpha, but one would expect breaking changes documentation to go out at the same time as features, or prevents testers from providing quality feedback, or even make us not as interested in testing newer releases.

**Comment by jbardin** [comment]
I agree, that's why I've left this open for the AWS team to review and update before any beta release is cut.

Sometimes it's just unfortunate timing. Alpha releases aren't planned, as they get cut whenever any team has something new to test. They aren't always meant for public consumption, and definitely never intended for production use. This means that other than all unit tests passing, some things may be in an incomplete or even broken state. Thank you for testing, but alpha's are very much expected to have some rough edges.

**Comment by FernandoMiguel** [comment]
Not my first rodeo.
I know how to stay clear of issues.
But when given the chance and having a test env I do try early releases.
Sometimes you catch tiny bugs, sometimes bigger ones.
I could have just have left this one pass, but felt like it could be fixed and help others who face the same issue.

Anyway, being a breaking change means at some point in the future we will need to modify yet again the backend config.
So the early I know about it, the more prepared can our teams be.

**Comment by gdavison** [comment]
Sorry, we missed marking this change a breaking.

We're going to be rolling back this change, as it has implications both here and with a similar change in hashicorp/terraform-provider-awscc. We were trying to keep feature parity between the two providers and the S3 backend, but because the provider configuration for AWS uses the old Terraform Plugin SDK v2 instead of the Terraform Plugin Framework, the schema changes were not breaking there, but were in AWSCC and the S3 backend.

We will be revisiting this feature after Terraform v1.10.0
