### ISSUE TITLE
datadog ignore_server_certificate_error doesn't work

### ISSUE THREAD

**Issue by ailicic** [hashicorp/terraform#35828]
### Terraform Version

```shell
Terraform v1.9.7
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.9.0
+ provider registry.terraform.io/datadog/datadog v3.46.0
+ provider registry.terraform.io/hashicorp/azuread v2.43.0
+ provider registry.terraform.io/hashicorp/azurerm v3.95.0
+ provider registry.terraform.io/hashicorp/helm v2.15.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.32.0
```

### Terraform Configuration Files

```test_definitions = [
    {
      test_name  = "Checking the health of the <>"
      test_url   = "<>"
      locations  = ["pl:testing-internal-ssl-certificates-66a26dc1da1cf9bc7fa32f1b7b71c90d"]
      follow_redirects = true
      message = "Synthetic Test for for <> service is failing"
      status = "live"
      tick_every = 36000
      test_tags = ["created-by:terraform", "env:dev"] 
      timeout = 30
      ignore_server_certificate_error = true
    },
```

### Debug Output

```console
 # datadog_synthetics_test.synthetic_tests["1"] will be created
  + resource "datadog_synthetics_test" "synthetic_tests" {
      + id         = (known after apply)
      + locations  = [
          + "pl:testing-internal-ssl-certificates-66a26dc1da1cf9bc7fa32f1b7b71c90d",
        ]
      + message    = "Synthetic Test for for <> service is failing"
      + monitor_id = (known after apply)
      + name       = "Checking the health of the <> service2"
      + status     = "live"
      + subtype    = "http"
      + tags       = [
          + "created-by:terraform",
          + "env:dev",
        ]
      + type       = "api"

      + assertion {
          + operator = "is"
          + target   = "200"
          + type     = "statusCode"
        }

      + options_list {
          + follow_redirects                = true
          + http_version                    = "any"
          + ignore_server_certificate_error = true
          + min_location_failed             = 1
          + tick_every                      = 60
        }

      + request_definition {
          + method  = "GET"
          + timeout = 30
          + url     = "<>"
        }
    }
```

### Expected Behavior

In datadog synthetic monitor I expect ignore_server_certificate_error checkbox to be marked (enabled) 

### Actual Behavior

Even if terraform output says that ignore_server_certificate_error is enabled it's actually disabled and if I enabled it manually and run terraform apply with enabled ignore_server_certificate_error it will return it to disabled

### Steps to Reproduce

```console
terraform init
terraform apply
```

### Additional Context

I tested it so far on multiple repos and I'm seeing the same problem, it seems that whatever you set as value for ignore_server_certificate_error (true or false) terraform will set it as false in datadog portal

**Comment by bschaatsbergen** [comment]
Hi @ailicic,

Thank you for reporting this. Since it appears to be related to the `datadog` Terraform provider, the best place to raise this would be in [their repository](https://github.com/DataDog/terraform-provider-datadog), where it can get more attention and potentially a (documentation) fix.

According to the documentation [here](https://docs.datadoghq.com/synthetics/browser_tests/?tab=certificate), it appears that the `ignore_server_certificates_error` argument is only applicable to browser-based synthetic tests. I couldn’t find any mention of it being relevant for API testing.  I suspect this argument is only respected when `type` is set to `browser`, not when it’s set to `api`.

Depending on your requirements, you might want to consider omitting the `ignore_server_certificates_error` argument and instead try setting:
```hcl
options_list {
  allow_insecure = true
}
```

This option allows loading insecure content for an HTTP request in an API test.
