### ISSUE TITLE
 Terraform Plan Shows Resource Recreation After Importing State

### ISSUE THREAD

**Issue by NitishGupta9282** [hashicorp/terraform#35887]
### Terraform Version

```shell
Old Version: 0.14.1
New Version: 1.6.6
```

### Terraform Configuration Files

After upgrading Terraform from version 0.14.1 to 1.6.6, We are getting one issue with the new versions. Even after successfully imported resources into the Terraform state, upon running terraform plan, it indicates that the imported resources need to be recreated, which was not the case with the previous version. We are using remote gcs backend.

### Debug Output

Cant share the output

### Expected Behavior

Terraform should not recreate the resources.

### Actual Behavior

Terraform is recreating the resources even after import

### Steps to Reproduce

Commands we are using for our operations
1) terraform init --input=false --reconfigure
2) `terraform {action} -var-file={common_tfvars} -var-file={db_tfvars} {resource_string}`
2) `terraform plan -var-file="${tfvars_file}" -input=false -out "${tfplan_file}";`

**Comment by jbardin** [comment]
Hello,

If Terraform is planning to replace resources, the plan output will show which resources, and specifically which attributes changes the provider has determined force the replacement. This could be due to a change in the provider or something in the configuration, but the decision to replace a resource always comes from the provider.

It's possible you are running into one of the use cases for #33438, but without any example example configuration or plan output it's unclear what is going on.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks
