### ISSUE TITLE
replace() result for a "//" doesn't work like expected.

### ISSUE THREAD

**Issue by macetw** [hashicorp/terraform#35894]
### Terraform Version

```shell
~ > terraform version
Terraform v1.9.8
on darwin_arm64
```
```


### Terraform Configuration Files

No relevant configuration is needed to reproduce.

### Debug Output

In the terraform console ...

(running with TF_LOG produced no extra output)
```
> replace("foo", "//", "/")
"/f/o/o/"
```

### Expected Behavior

```
> replace("foo", "//", "/")
"foo"
> replace("fo//o", "//", "/")
"fo/o"
```

### Actual Behavior

```
> replace("foo", "//", "/")
"/f/o/o/"
> replace("fo//o", "//", "/")
"/f/o/////o/"
```

### Steps to Reproduce

`terraform console`
`replace("foo", "//", "/")`

### Additional Context

_No response_

### References

https://github.com/hashicorp/terraform/issues/8709

This looks like a bug you fixed for double backslashes. This is about forward slashes.

**Comment by jbardin** [comment]
Hi @macetw,

According to the [`replace` documentation](https://developer.hashicorp.com/terraform/language/functions/replace) 
> If substring is wrapped in forward slashes, it is treated as a regular expression, using the same pattern syntax as [regex](https://developer.hashicorp.com/terraform/language/functions/regex)

Since your regex matches an empty string, it will insert the replacement string at every empty substring, which ends up being between each character.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by macetw** [comment]
The solution here is to use this:
```replace("fo//", "////", "/")```
