### ISSUE TITLE
Duplicate diagnostic warning for ephemeral reference in `check` block

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#35931]
### Terraform Version

```shell
1.10.0-dev (248b10e483f8ab27bac3db2fd1979b7f7a39281a)
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
    }
  }
}

ephemeral "random_password" "example" {
  length = 12
}

check "test" {
  assert {
    condition     = ephemeral.random_password.example.result == "foo"
    error_message = "password is not foo but ${ephemeral.random_password.example.result}"
  }
}
```

### Debug Output

https://gist.github.com/radeksimko/25af355588d0379fa96fcaab7c2517d8

### Expected Behavior

Warnings not to be duplicated between plan & apply.

### Actual Behavior

Duplicate warning diagnostic after `terraform apply`

```sh
$ terraform apply
```
```
ephemeral.random_password.example: Opening...
ephemeral.random_password.example: Opening complete after 0s
ephemeral.random_password.example: Closing...
ephemeral.random_password.example: Closing complete after 0s

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
ephemeral.random_password.example: Opening...
ephemeral.random_password.example: Opening complete after 0s
ephemeral.random_password.example: Closing...
ephemeral.random_password.example: Closing complete after 0s
╷
│ Warning: Check block assertion failed
│
│   on main.tf line 15, in check "test":
│   15:     condition     = ephemeral.random_password.example.result == "foo"
│
│ This check failed, but has an invalid error message as described in the other accompanying messages.
╵
╷
│ Warning: Error message refers to ephemeral values
│
│   on main.tf line 16, in check "test":
│   16:     error_message = "password is not foo but ${ephemeral.random_password.example.result}"
│
│ The error expression used to explain this condition refers to ephemeral values, so Terraform will not display the resulting message.
│
│ You can correct this by removing references to ephemeral values, or by using the ephemeralasnull() function on the references to not reveal ephemeral data.
│
│ (and one more similar warning elsewhere)
╵
```

note the last line

> (and one more similar warning elsewhere)

When I try to disable warning consolidation, I can see the exact same warning.

Also this does not occur on `terraform plan`.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
This may have something to do with how checks are recorded in the plan. It's not clear how ephemeral resources were supposed to interact with those, since they are run anew during both plan and apply. I opted to let them be recorded and then check them again during apply to avoid conflicts, as apply currently expects all checks to be present in the plan, but maybe that's causing something to be duplicated.

**Comment by liamcervante** [comment]
This might be the same thing that led me to add this: https://github.com/hashicorp/terraform/blob/main/internal/backend/local/backend_apply.go#L187-L212

Basically, if the plan and apply are just run consecutively without human interaction (eg. because of `-auto-approve` or no changes) then it merges all the diagnostics from the plan and apply together and you get the duplicate

We usually mark all diagnostics from check blocks with a specific extra like [this](https://github.com/hashicorp/terraform/blob/main/internal/terraform/node_resource_abstract_instance.go#L2076-L2080), or just directly like [this](https://github.com/hashicorp/terraform/blob/main/internal/terraform/eval_conditions.go#L139-L141). Terraform then removes those diagnostics from the plan diagnostics before executing the apply since there not helpful anyway as the checks do just get re-executed and reported during the apply stage and the user isn't going to see them before everything is applied anyway.

This particular diagnostic might not be getting the correct extra added somehow, and so isn't being deduplicated?
