### ISSUE TITLE
True locally scoped affective within the same file declared

### ISSUE THREAD

**Issue by tom10271** [hashicorp/terraform#35960]
### Terraform Version

```shell
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.74.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.33.0
```

### Use Cases

Our company have teams and different teams have multiple K8s projects. Our terraform project structure is to create a standalone folder as the team K8s terraform project and it contains multiple files each represents a K8s project. There are values within the file repeated within each file. Here is an example of a typical project-xxx.tf, see `project-a` in `project_name`, `containers`, `image`, `secret_env_vars`.

```tf
module "project-a-k8s-config" {
    for_each = {
        prod = {}
    }

    source = "../../modules/deployment"

    namespace    = "team-a"
    project_name = "project-a-${each.key}"

    containers = {
        "project-a-${each.key}" = {
            image_pull_policy = "Always"
            image             = "123123123.dkr.ecr.us-east-2.amazonaws.com/project-a:latest${each.key != "prod" ? "-${each.key}" : ""}"
            port              = [8964]

            env_vars = merge({
                EMAIL_SMTP     = 'smtp.sendgrid.net'
                EMAIL_PORT     = '587'
                EMAIL_USERNAME = 'apikey'
            }, try(each.value.env_vars, {}))

            secret_env_vars = {
                for name in [
                    "EMAIL_PASSWORD"
                ] :
                name => ["project-a-v1", name]
            }

            expose_to_ingress_wizard = {
                internal         = false
                port             = 8964
                healthcheck-path = "/"
            }
        },
    }

    ingress = [
        {
            host         = "whatever${ each.key != "prod" ? "-${each.key}" : "" }.asdasd.com"
            acm_cert_arn = "arn:aws:acm:us-east-2:123123123:certificate/xxxx"
        }
    ]
}
```

### Attempted Solutions

We can create a locals by 
```tf
locals {
    project_name = {
        project-a = "project-a"
        project-b = "project-b"
        project-c = "project-c"
        project-d = "project-d"
    }
}
```

but obviously this will be lengthy to use.

Using for_each with our module is not ideal either because although typically project.tf looks like above, however some of them might need to mount volume, maybe EFS, S3, EBS, making composing one single module to do different things depends on each.value complicated.

### Proposal

 If we can declare something maybe

```tf
var {
     project_name = "project-a"
}
```

which scoped within the same file unlike locals which is global with in the same Terraform project, I can just type var.project for replacing "project-a" in `project_name`, `containers`, `image`, `secret_env_vars`.

**Comment by jbardin** [comment]
Hi @tom10271,

HCL, like a lot of compiled programming languages, has no file scope and relies on lexical components within the language to define the scope. In Terraform, that "scope" is the module, and the best way to reduce the amount of symbols within the scope is to break it into smaller discrete modules. Changing the language module on which Terraform is built would be quite a drastic change.

Assuming that these smaller sections of code are not sharing any state, since you intend for them to only be accessible within their own files, it should be fairly easy to move those files into modules of their own. If that's not possible, that would indicate there are references between the files, so they would still need to be included in the broader scope.
