### ISSUE TITLE
add overall service activity and operational health with the Services page

### ISSUE THREAD

**Issue by DaliStabl** [hashicorp/terraform#35969]
### Terraform Version

```shell
1.9.8.
```

### Use Cases

AWS has implemented a new feature allowing to view overall service activity and operational health with the Services page https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Services-page.html but it is not supported in Terraform yet

### Attempted Solutions

no i did not try

**Comment by liamcervante** [comment]
Hi @DaliStabl , thanks for filing this! This seems to be a feature request within the AWS provider. The AWS provider is managed in a dedicated repository, separate to Terraform Core. I will close the issue here, but you should reopen this directly with the AWS provider: https://github.com/hashicorp/terraform-provider-aws/issues. Thanks!
