### ISSUE TITLE
Allow precondition checks to access the plan's action for that resource

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#36229]
### Terraform Version

```shell
1.10.2
```

### Use Cases

Because https://github.com/hashicorp/terraform/issues/22544 has still not been implemented and mainstream providers such as the Google provider have had to add a lot of custom deletion protection functionality (eg https://github.com/hashicorp/terraform-provider-google/issues/20308), it is commonly an issue that someone tries deleting a bucket or other resource that has deletion protection enabled without first disabling the deletion protection. Because this cannot currently be flagged without custom tooling, it results in a cumbersome situation where someone merges the PR trying to delete the resource while deletion protection is still enabled, the apply fails, they have to make a second PR and re-add the resource with deletion protection disabled, then a third PR removing the resource again after that second PR has been successfully applied. It would be far better if we could just have the initial PR generate a plan failure.

### Attempted Solutions

Currently, we have to build custom tooling to inspect both the configuration and state file to check for this situation prior to a failed apply. 

### Proposal

Add some type of `action` meta-argument that can be used inside a precondition block so that we can write conditionals that trigger an error on plan if the condition is something like `action == "delete" && var.deletion_protection == true`.

An even better alternative would be a way for this logic to be baked into the relevant providers so that everyone could get it for free that the Google provider will just error if it generates a plan that tries to delete a resource currently protected by some type of deletion protection argument.

### References

- https://github.com/hashicorp/terraform/issues/22544
- https://github.com/hashicorp/terraform-provider-google/issues/20308

**Comment by jbardin** [comment]
Hi @joe-a-t,

Resource preconditions are evaluated before the planing operation, or even evaluating the resource's configuration, so there is no action at that point in time to compare with.

As far as custom tooling is concerned, the plan contains all the necessary information and is how external policies are generally applied. There shouldn't be any need to try and interpret the config and prior state to determine the planned actions, which is technically not possible because the plan is determined by the provider.

While the larger problem of policy enforcement is going to be left to external tooling, the existing issues around `prevent_destroy` already have plenty of discussion, though no there hasn't been a solid solution as of yet. Aside from the already linked issues, there are #24658, and #33437 too. Since this idea isn't possible to implement, we can follow the existing issues for any further development

**Comment by joe-a-t** [comment]
By saying 

> There shouldn't be any need to try and interpret the config and prior state to determine the planned actions, which is technically not possible because the plan is determined by the provider.

Are you implying that it would currently be possible for the Google provider to have this type of check and error the plan if the plan would destroy a resource that currently has deletion protection enabled?

**Comment by jbardin** [comment]
I might be possible to hook into postconditions, though it's also kind of stretching the idea of "conditions". If this comes around in project work again we can reconcile all the linked issues and consider if conditions are a suitable place to try something like this. 

Yes, the provider can return diagnostics along with the plan. That case of a provider wanting to reject a destroy action is specifically why we ensure that a destroy plan is also sent to the provider.
