### ISSUE TITLE
FreeBSD download missing terraform-provider-docker

### ISSUE THREAD

**Issue by wathiede** [hashicorp/terraform#3627]
The 0.6.5 & 0.6.6 FreeBSD zips provided at https://terraform.io/downloads.html are missing terraform-provider-docker (at least in the 64-bit versions I checked).  Running `gmake dev` builds this binary on my machine, so I'm guessing it is a bug in the process that generates the zip files.  I couldn't find where this is controlled in the source, so I'm filing an issue instead of sending a pull request.

**Comment by jen20** [comment]
Hi @wathiede - thanks for reporting this. As of the current `master` branch, the zip file is included in the zip packages generated for FreeBSD. @phinze mentioned that there had previously been an upstream dependency issue building on FreeBSD which looks to have been resolved.

However, as part of identifying this I *did* discover that OpenBSD is not building correctly, because of something in `github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/system`. I'll open a new issue to track that and try to submit a patch upstream.
