### ISSUE TITLE
terraform plan should not update the statefile

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#3631]
terraform plan should not update the statefile. It is annoying that it does, even when the refresh position is exactly the same, as if using git to store state then it looks like there are constantly things to commit during the development phase.

**Comment by farridav** [comment]
+1, I have the same issue.. I'm testing my plans on my CI box, and was alarmed to see that my read-only IAM user needed write permission to the s3 bucket i store my state in.... keen to hear if this will be fixed....

**Comment by catsby** [comment]
Hey all –

Part of constructing an accurate plan of any changes that need to be made, in order to match your desired state with your actual state, is to refresh and get an up to date picture of your current actual state. That's the part where we reach out to the Provider(s) and get updated information, and update the state file to match what the Provider(s) view of the world is. 

Put simply, if you have a simple EC2 Instance and you have `count = 3`, and 2 have gone down since your last plan/apply, a Terraform `plan` wouldn't know to create 2 more instances without refreshing. 

Or course, your situations vary, so you can run `plan` without first refreshing the state file:

    $ terraform plan -refresh=false 

This way `plan` will not update the state file. 

I believe the behavior is correct, but would love to hear more from either of you on why you feel it needs to be changed, and we can certainly consider it.

**Comment by farridav** [comment]
Hi @catsby thanks for your prompt reply, I guess the reason this threw me is because `plan` comes across to me as a theoretical action, and would not update anything (the state file or the resources), whereas `refresh` and `apply` behave as expected.

I can change my `plan` implementation (now i know of the `refresh` flag).. thanks for that..

I'm using remote state, so the state file changing under VC doesn't affect me.. I think @gtmtech's concerns are of a different nature to mine..

**Comment by jedineeper** [comment]
Hi @catsby, my use case is that I would like to locally "terraform plan" my work to check for changes and my syntax against the current remote state without pushing any update back to Atlas. My local token has no permissions to write to the Atlas state because I use Atlas exclusively to manage the state for me via Github.

I'm sure I've seen a ticket for this previously but can't find it today.

**Comment by gtmtech** [comment]
I'm happy for this to be closed - I think your explanation is very sensible and the behaviour is very sensible. It makes much more sense to default to a refresh (and thus change the state) than not to. And I see the documentation provides details of this.
