### ISSUE TITLE
Add support for VMware vRealize Automation

### ISSUE THREAD

**Issue by liquidstate** [hashicorp/terraform#3642]
In addition to the support for vSphere added in #3419, would it be possible to implement support for [VMware vRealize Automation](http://www.vmware.com/uk/products/vrealize-automation) too?

vRA is a multi-tenancy hybrid cloud platform, which lets users deploy machines from a service catalog.  It's mostly used to deploy VM templates, but it also supports Amazon, OpenStack, and even physicals. 

It has a REST API - https://developercenter.vmware.com/web/sdk/6.2.0/vrealize-automation
It has a command line tool - https://developercenter.vmware.com/tool/cloudclient/3.3.1

**Comment by khalaan** [comment]
And while it doesn't necessary mean a 1:1 conversion there is an excellent vmware-vra gem that could be used as a reference for structuring requests even up to their 7.0.1 release.

**Comment by liquidstate** [comment]
WIP Pull Request at https://github.com/hashicorp/terraform/pull/10893 ... contributions welcome!

**Comment by stack72** [comment]
Hi @liquidstate,

Thanks so much for the request for this new provider!

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

@stack72
