### ISSUE TITLE
Allow providing stub resources / read-only resources to improve modularity.

### ISSUE THREAD

**Issue by preflightsiren** [hashicorp/terraform#3646]
I've found with my use of terraform you often need to provide a mixture of environment details from computed information (eg. instance id's) and often pre-generated resources (eg. vpc id's or subnet id's).

This becomes an issue for terraform to manage such a core/common/reused resource like VPCs, if you have a mixture of managed/unmanaged resources. The issue comes about when terraform wants to teardown the whole VPC and rebuild it, but there's an unmanaged resource in there preventing the VPC from being destroyed. Now you're stuck. Either teardown the instance manually or separate out the VPC from your application and include more process.

**My braindump solution:**
using https://github.com/hashicorp/terraform/tree/master/examples/aws-two-tier as an example, if you need to move the app into a VPC environment it ends up looking like:

```
resource "aws_security_group" "default" {
  name = "terraform_example"
  description = "Used in the terraform"
  vpc_id = "vpc-123456789"
```

or if you use variables extensively like this:

```
resource "aws_security_group" "default" {
  name = "terraform_example"
  description = "Used in the terraform"
  vpc_id = "${var.vpc_id}"
}
```

but wouldn't it be nicer to refer to an actual aws resource and be able to reference all the properties, but without having terraform try to apply configuration changes to it?

**very rough solution**

```
resource "aws_vpc" "main" {
    id = "vpc-123456789"
}

resource "aws_security_group" "default" {
  name = "terraform_example"
  description = "Used in the terraform"
  vpc_id = "${aws_vpc.main.vpc_id}"
}
```

then terraform can provide feedback like: "Hey that vpc with id: vpc-123456789 doesn't exist!"
and your security group gets configured based upon computed values, but without any of the headache of terraform plans deciding the only way to solve this plan is to burn it all down and start over.

Love to hear your thoughts

-Seb

**Comment by radeksimko** [comment]
I believe the possible solution for this is being discussed thoroughly in https://github.com/hashicorp/terraform/issues/4169 and being implemented in https://github.com/hashicorp/terraform/pull/4705

**Comment by apparentlymart** [comment]
Hi @preflightsiren! I just stumbled across this old issue while looking for something else.

As of one of the Terraform 0.7 releases (I forget exactly which one) we have an `aws_vpc` *data source* which I think should meet the use-case you were looking for here, with some slightly different syntax:

```
data "aws_vpc" "main" {
    id = "vpc-123456789"
}

resource "aws_security_group" "default" {
  name = "terraform_example"
  description = "Used in the terraform"
  vpc_id = "${data.aws_vpc.main.vpc_id}"
}
```

The `data` block creates a "data resource", which is like a read-only resource (as you proposed) that fetches data from some data source; in this case, [the aws_vpc data source](https://www.terraform.io/docs/providers/aws/d/vpc.html).

And just as you suggested, if a matching VPC isn't found then that's a fatal error that prevents the `aws_security_group` from being planned, rather than waiting and failing at apply time.

[The newer aws-networking example](https://github.com/hashicorp/terraform/tree/master/examples/aws-networking) elaborates on this idea, showing how one might create a set of AWS networking resources in a modular way using a mixture of Terraform modules and data resources.

Since I think this is now possible -- albeit not *exactly* as you proposed -- I'm going to close this now; please do let me know if you think there's more here that hasn't been implemented yet, and we can figure out whether to reopen this or create a more focused issue to capture the remaining proposal.
