### ISSUE TITLE
AWS: default egress policy for security groups caused a lot of pain

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform#3647]
I've wasted a lot of time trying to figure out why instances can receive traffic but cannot send. After checking routing tables, network ACLs, etc, and basically going around in circles with no success, I eventually stumbled upon that piece of documentation that describes how Terraform takes a non-standard approach (opposite to AWS default) to creating security groups. For any Terraform-created security group, outbound traffic is blocked by default.

**WHY?**

Just think of all the cases in the past when someone changed the default on something very obvious and generally agreed-upon. Remember the frustration you've experienced trying to troubleshoot that thing? Yeah, that's what I've felt today.

Please, change this evil non-standard behavior. Your prospective users will thank you.

**Comment by catsby** [comment]
Hey @FlorinAndrei –

Thanks for reaching out to us about this. I sincerely apologize for the trouble you’ve had here, especially since I’m the author of this “feature”. This behavior was introduced in https://github.com/hashicorp/terraform/pull/1765 , which contains some backstory and thought process, and I’ll expand on here.

Terraform is a declarative tool. We take a configuration file and we apply it to infrastructure, using Provider APIs to enforce our “view of the world” . We found that with Security Groups, AWS would add a default Egress rule to any Security Group we created, as you’re well aware. Normally, we do not like to contradict a Providers defaults, however this created a few surprises for us and our users:

- an “empty” security group, with no rules specified, did in fact receive a rule via the default. Right out of the gate, our declaration was not being honored. It was impossible for Terraform to create an empty security group (in a VPC). To remove the default rule, users had to use the console or API/CLI directly
- because of Terraforms declarative model, many users assumed that if they did not specify the “allow all” egress rule, they were required to add it. When attempting to add said rule, AWS would report an error about a duplicate rule that already existed
- users who specify any other rules were surprised to find that their SG had an additional rule they did not specify. This was a surprise, but also had security implication. For example, specifying a rule to only allow a SG to egress to another SG appeared to work, however because of the default, anything in the SG could actually talk to anyone. This gave the appearance of locking down a groups egress communications, but in reality it was wide open 

I think the later point was the key factor in this decision, but all were pain points we were attempting to address. For experienced AWS users like yourself who expect this default rule to be there, this decision would likely be a surprise, but we felt it was the best decision. Better to default to “talk to no one” then to allow “talk to anyone”, we think. 

> Just think of all the cases in the past when someone changed the default on something very obvious and generally agreed-upon. Remember the frustration you've experienced trying to troubleshoot that thing? Yeah, that's what I've felt today.

I know this pain. I am truly sorry I caused this to happen to you. I hope in reading this you at least understand our thought process and reasons for making the decision. Unfortunately by _not_ removing the default rule, we were lying to our users who declared security groups _without_ this rule. Because of this, and the other reasons cited, I don’t believe we’ll be changing the behavior. 

We truly don’t want to confuse or frustrate anyone. Do you think we could have made this more explicit? We do have the behavior documented (https://terraform.io/docs/providers/aws/r/security_group.html), but maybe we could do better to draw attention to it? We also [log][1] when we remove the default rule, but I realize this only shows if you’re running in verbose mode (for example, with `TF_LOG=1` when running `apply`). If you have any suggestions on how we could have better notified you and saved you those hours of frustration we’ll gladly consider them. 

We’re going to close this issue since the functionality we’ve gone through a lot of pros and cons as outlined above and we and the users we worked with on it believe we’ve made the right approach. But as we said, we’re open to better documenting this so its less of a surprise for experienced AWS users as thats not our intention. Please respond and we’ll take a look. Thanks!

[1]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_security_group.go#L220

**Comment by FlorinAndrei** [comment]
Giving it some thought after a while, it makes sense. I understand where you're coming from.

What would probably help is adding a tiny one-line notification at the end after terraform apply, along the lines of "hey, we've created an outbound security group with no rules, is that what you really want?" After you're used to Terraform you'll probably ignore it, but beginners might avoid unnecessary head-scratching.

Thank you.

**Comment by iigorkarpov** [comment]
Following the same logic, terraform should not generate

aws_key_pair.deployer: Error import KeyPair: InvalidKeyPair.Duplicate: The key pair 'mykey' already exists

error, should it?

If it is a declarative tool, it should be something like: 'well, it's already in, great.'

Am I wrong?
