### ISSUE TITLE
[feature request] Libvirt provider support

### ISSUE THREAD

**Issue by orangepeelbeef** [hashicorp/terraform#3661]
Requesting libvirt provider support for terraform

**Comment by mitchellh** [comment]
Thanks! We're definitely interested in expanding provider support for Terraform. We tend to close these sorts of issues unless they're paired with a PR since we don't have any immediate plan to work on this (and we have a backlog of quite a few other issues to tackle). 

If you or someone you know wants to work on adding this, we're happy to help you and work with you to get it into core. Otherwise, we're aware of the request and we'll try to get it in at some point in the future, but in all honesty probably not this year without community help. Thanks!

**Comment by dmacvicar** [comment]
I have started one at https://github.com/dmacvicar/terraform-provider-libvirt in case you want to help.

**Comment by paxsonsa** [comment]
Bump for this

**Comment by deknos** [comment]
Supporting libvirt/KVM on a (remote) host out of the box would REALLY help adoption, since users could try terraform on their local machines before they deploy stuff into the cloud

**Comment by pgonin** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt has now reached 0.5
We use it quite heavily.
What would be missing to have an official terraform-provider in https://github.com/terraform-providers
What are the criteria ?

**Comment by dmacvicar** [comment]
Does it make sense? The only advantage of official providers is the installation, which automatically downloads the binary on `terraform init`. However, _libvirt_ provider links against a library that is system dependent. I ignore how sophisticated is the build system it is used to build these official providers.
We offer binaries for popular platforms, thanks that we build in [OBS](https://openbuildservice.org/).
