### ISSUE TITLE
GoDaddy Provider

### ISSUE THREAD

**Issue by adamveld12** [hashicorp/terraform#3673]
Adding a GoDaddy provider would be pretty cool.

Here is a link to their [API documentation](https://developer.godaddy.com/doc#!/_v1_domains/recordReplace/ArrayOfDNSRecord).

**Comment by tylerFowler** [comment]
Would be particularly nice for configuring AWS Route53 DNS records on a GoDaddy domain, which requires you to enter the Amazon NS (`aws_route53_zone.*.name_servers`) records for subdomains.

**Comment by n3integration** [comment]
I took a stab at a basic [GoDaddy provider](https://github.com/n3integration/terraform-godaddy) to manage domain name records.

**Comment by ClanLeader** [comment]
I use asphostportal.com here. It is simple to host .net core site with them.

**Comment by RowdyElectron** [comment]
Has anyone tried this: https://github.com/n3integration/terraform-godaddy

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!
