### ISSUE TITLE
Support AWS APIGateway

### ISSUE THREAD

**Issue by danielrmeyer** [hashicorp/terraform#3675]
I would like to be able to use terraform to configure the AWS APIGateway.

It seems to be supported via aws-sdk-go now: https://github.com/aws/aws-sdk-go/issues/338

**Comment by BetaGrumm** [comment]
Roger this. +1

**Comment by pauldtong** [comment]
+1

**Comment by petitbon** [comment]
+1

**Comment by Joseph-R** [comment]
+1.   Pretty critical for a gateway + lambda setup on some services.

**Comment by johannesboyne** [comment]
+1

**Comment by cliffano** [comment]
+1

**Comment by alexander-bobin** [comment]
+1, this would be amazing. Thanks for all your hard work guys

**Comment by swestcott** [comment]
PR is open https://github.com/hashicorp/terraform/pull/4295

**Comment by ajlanghorn** [comment]
:+1:

**Comment by errordeveloper** [comment]
Another :+1:, if it helps!

**Comment by radeksimko** [comment]
Hi all :wave:  ,
just FYI, support for most of the API Gateway resources have been merged as part of https://github.com/hashicorp/terraform/pull/4295 and will be part of the next release.

However I'm keeping this open as there's a few more resources left to be implemented for API Gateway:

 - `aws_api_gateway_authorizer`
 - `aws_api_gateway_base_path_mapping`
 - `aws_api_gateway_domain_name`
 - `aws_api_gateway_stage`

and also caching support which was left out in the initial PR.

**Comment by brian-polly** [comment]
As of now, it looks like stage _is_ supported, right? that's what aws_api_gateway_deployment does? 
Agreed that the base_path_mapping and domain_name would be really sweet to include.

The lack of custom authorizer support is really crushing, though. As far as I know, this means that I can't use terraform to update a stack where I implement them, because there's not even a way to specify authorizer_id in aws_api_gateway_method, the way there is in Amazon's API. 

http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html

**Comment by dustyburwell** [comment]
Now that the API/CLI/SDKs support [importing a rest API](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) via swagger format, it would be pretty great to support that here as well. I'd rather not have to write a swagger-terraform translation step.

**Comment by dustyburwell** [comment]
Having spent a bit of time looking at the new import API, it seems like it would be non-trivial to support API importing. I looked to the `aws_s3_bucket_object` resource for inspiration, but the gateway API requires a stage for you to export the API json, and there don't appear to be any attributes (analogous to the `etag` on an s3 object) on the API resource that would serve as a test for the need to update.

Are there any other useful resource examples we could draw inspiration from? It doesn't seem reasonable to always update, especially with such a big resource.

**Comment by llarsson** [comment]
+1 on @dustyburwell's request for importing via Swagger. Since that is already available in AWS, it would be very nice to see that here, too. [Importing Swagger files seems simple to do via the AWS API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), but I am not familiar with the Terraform code base to contribute a patch.

**Comment by jon077** [comment]
+1 for importing Swagger into API Gateway

**Comment by pagemedias** [comment]
+1 for importing Swagger into API Gateway for sure!

**Comment by seradin** [comment]
+1 for importing Swagger into API Gateway

**Comment by jasonmacdonald** [comment]
+1 from me for importing swagger files as well. And now it seems cloudformation supports it :(

**Comment by erick-thompson** [comment]
+1 I'll add to the chorus. Swagger into API Gateway would be very useful.

**Comment by n-my** [comment]
FYI I've created a separated issue for importing Swagger into API Gateway [#11034](https://github.com/hashicorp/terraform/issues/11034)

**Comment by apparentlymart** [comment]
Hi all! Thanks for all the great discussion here around API Gateway features.

We (the Terraform team) are doing a bit of pruning of old issues that don't have a clear scope or short-term action plan. We'd love to support more features of API Gateway in addition to what was already added but we specifically don't currently have plans to implement these.

Since the scope of this issue is rather vague it's unclear that it could ever truly be "done" and so I'm going to close it. However, we'd be happy to review any PRs for specific enhancements to Terraform's API Gateway support.
