### ISSUE TITLE
Mesos/Marathon Provider

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform#3676]
It would be very helpful if terraform had a provider for Mesos, most likely through the Marathon REST api, for setting up/scaling docker environments.

**Comment by iamthemuffinman** [comment]
+1

**Comment by nickm4062** [comment]
+1

**Comment by mikljohansson** [comment]
Found this, haven't tried it though

https://github.com/Banno/terraform-provider-marathon

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!
