### ISSUE TITLE
CloudFlare shouldn't error when record already exists

### ISSUE THREAD

**Issue by abevoelker** [hashicorp/terraform#3715]
Before I started using Terraform, I already had some DNS records created in CloudFlare for a project I'm working on. But I want to use Terraform going forward, so I grabbed a zone export file and wrote some Terraform resources to match it.

Unfortunately, Terraform errors out if the record already exists:

```
Error applying plan:

8 error(s) occurred:

* cloudflare_record.mail-4: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.mail-3: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.dkim: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.mail-2: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.spf-staging: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.mail-1: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.spf: Failed to create CloudFlare Record: API Error: The record already exists.
* cloudflare_record.mail-5: Failed to create CloudFlare Record: API Error: The record already exists
```

I think Terraform should be changed to not error out for this specific error when creating DNS records if the values are identical; if the values vary it should delete and recreate the records.

In the meantime to work around my issue I guess I either have to delete my DNS records and quickly recreate them (not very safe) or figure out the `.tfstate` file format and try to manually manipulate it.

**Comment by sarkis** [comment]
:+1: experiencing the exact problem here, agree this is a problem with the provider as well.

**Comment by apparentlymart** [comment]
Terraform's general policy is to avoid quietly "taking ownership" of pre-existing resources, since once Terraform is managing a resource it may get updated or deleted by Terraform and cause irreparable damage to existing infrastructure that the user did not intend to manage with Terraform.

However, I can certainly empathize with the frustration here having gone through similar hurdles migrating other pre-Terraform infrastructure to be managed by Terraform. This is a specific case of the (really old!) general issue #581 which is about Terraform having first-class support for this sort of thing.

The best workaround in the short term is to manually edit the state file, as you mentioned. When forced to do this, I usually use Terraform to create a new placeholder resource of the same type, see what gets written into the state, and then duplicate the state for the placeholder and edit it to make it match with the pre-existing objects. Far from ideal, but it works... :disappointed:

I'm sorry that there isn't a better answer for this in Terraform today. The third-party tool [terraforming](http://terraforming.dtan4.net/) aims to address this for AWS resources, but it doesn't currently generalize to other providers like Cloudflare, and that's actually the root of the difficulty with supporting this in Terraform: each resource needs its own "import" implementation, and there's currently no allowance for that in Terraform's architecture.

For now, I'm going to close this issue to consolidate the discussion in #581.
