### ISSUE TITLE
Support hiding outputs on apply

### ISSUE THREAD

**Issue by gwilym** [hashicorp/terraform#3765]
Since outputs can be inspected with `terraform output`, an option to hide the outputs list when running `apply` may improve usability over time for large sets of outputs, and may improve security in the case where your outputs include secrets which are meant to be fed into other systems rather than printed on screen (or placed in a logfile).

A minor request which I'm currently working around through some creative `sed` usage.

**Comment by mwarkentin** [comment]
Outputs can be marked as sensitive now which helps with the security issue.

**Comment by teamterraform** [comment]
Hi @gwilym! Sorry for the long silence here.

As @mwarkentin noted, we added support for marking output values as sensitive some time ago in order to deal with that particular concern. While we understand that the output-printing can be overwhelming in configurations with very large numbers of outputs, in practice that doesn't seem to have been a common problem four years on, and so unless something changes we're going to decide for now that the impact of a special option for this is not significant enough to justify the additional testing/maintenance burden of supporting it.

Thanks for this proposal!
