### ISSUE TITLE
Unable to Apply a Change to ECS service

### ISSUE THREAD

**Issue by brianknight10** [hashicorp/terraform#3787]
I was looking to change the container port for the ELB associated with my ECS service. I changed my `aws_ecs_service` task from:

```
resource "aws_ecs_service" "event" {
	name = "event"
	cluster = "${aws_ecs_cluster.event.id}"
	task_definition = "${aws_ecs_task_definition.event.arn}"
	desired_count = 4
	iam_role = "${terraform_remote_state.vpc.output.iam_ecs_service_role_id}"
	load_balancer {
		elb_name = "${aws_elb.event.name}"
		container_name = "event"
		container_port = 8080
	}
}
```
to:
```
resource "aws_ecs_service" "event" {
	name = "event"
	cluster = "${aws_ecs_cluster.event.id}"
	task_definition = "${aws_ecs_task_definition.event.arn}"
	desired_count = 4
	iam_role = "${terraform_remote_state.vpc.output.iam_ecs_service_role_id}"
	load_balancer {
		elb_name = "${aws_elb.event.name}"
		container_name = "event"
		container_port = 80
	}
}
```

After creating a plan, the applied failed with the message of: `* aws_ecs_service.event: diffs didn't match during apply. This is a bug with Terraform and should be reported.`

This may or may not be related to #3444. This happened on Atlas running v.0.6.6.

**Comment by radeksimko** [comment]
Thanks for the report,
in case like this (`diffs didn't match`) it would help if you can provide the full debug log (minus any secrets, obviously). Then we'd at least know which field is causing the problem and what's the actual diff.

Since you're using `terraform_remote_state`, I believe this is related to https://github.com/hashicorp/terraform/issues/2765 .
@apparentlymart is working on a fix for all similar issues in https://github.com/hashicorp/terraform/pull/3060

**Comment by catsby** [comment]
Hey all – we haven't heard back in a while so I'm going to go ahead and close this. I suspect too that it's covered in one of the other issues referenced. 

Thanks!
