### ISSUE TITLE
Cycle Issue with template files after upgrade.

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/terraform#3812]
I am getting the following error, this has only started to happen after upgrading to 0.6.6.

```
Error running plan: 3 error(s) occurred:

* Cycle: aws_autoscaling_group.deis-router, template_file.deis-router, aws_launch_configuration.deis-router, aws_launch_configuration.deis-router (destroy), template_file.deis-router (destroy)
* Cycle: template_file.deis-feature-worker (destroy), template_file.deis-feature-worker, aws_launch_configuration.deis-feature-worker, aws_autoscaling_group.deis-feature-workers, aws_launch_configuration.deis-feature-worker (destroy)
* Cycle: aws_launch_configuration.deis-production-worker, aws_autoscaling_group.deis-production-workers, aws_launch_configuration.deis-production-worker (destroy), template_file.deis-production-worker (destroy), template_file.deis-production-worker
```

**Comment by catsby** [comment]
Hey @jwaldrip – you don't have a pared down config that demonstrates this by chance, do you?

**Comment by jwaldrip** [comment]
Check out http https://github.com/brandfolder/infrastructure. That's the config being used.


- Jason

-----

Jason Waldrip
Chief Technology Officer
Brandfolder.com
email| jason.waldrip@brandfolder.com
office |720-744-0311(tel:720-744-0311)
mobile |646-460-5959(tel:646-460-5959)

**Comment by apparentlymart** [comment]
@jwaldrip I think this might be another case of the issue that was documented in #2944.

For example, your `aws_autoscaling_group.deis-router` depends on `aws_launch_configuration.deis-router`, and the latter is `create_before_destroy` but the former isn't. Setting them *both* to `create_before_destroy` (and possibly also your `template_file.deis-router`) might clear up the first of those three cycles. If that works, I expect the same sort of approach will fix the others.

This is a pretty common problem people have with Terraform; it's probably worth adding a special case to the cycle detector to detect and report this case in a more specific way. Ideally it would report it early before the resources are even created, rather than letting you create a bunch of stuff and then breaking later when you try to destroy parts of it.

**Comment by mitchellh** [comment]
This is also probably fixed now magically with our automatic CBD upgrade we do to non-CBD resources. At least in this case!
