### ISSUE TITLE
Moving google_compute_address to other google_compute_instance fails

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#3841]
When moving the nat_ip attribute below to a different google_compute_instance it fails because the old instance doesn't release the ip address.

```
    network_interface {
        network = "${google_compute_network.network.name}"
        access_config {
            nat_ip = "${google_compute_address.some_address.address}"
        }
    }
```

When terraform tries to attach the ip address to the new vm the following error is thrown:

```
* google_compute_instance.new_vm_for_ip_address: code: INVALID_USAGE
invalid_usage {
  user_visible_reason: "Specified IP address is already allocated to an instance."
  resource {
    resource_type: INSTANCE
    resource_name: "new-vm-for-ip-address"
    project {
      canonical_project_id: 912090993447
    }
    scope {
      scope_type: ZONE
      scope_name: "europe-west1-b"
    }
  }
}
```

The plan didn't show any modifications to the old vm on forehand, where I would expect it to give the machine a new ip address or destroy and recreate the machine.

**Comment by lwander** [comment]
If you just remove that IP from a single machine without assigning it to a new one, does it work as expected?

**Comment by JorritSalverda** [comment]
No, it says there are no changes in that case.

**Comment by sparkprime** [comment]
This is an interesting problem.  A work around is to assign a different IP.  You could also remove the access_config entirely and then put it back in another step.

I don't know what Terraform should do in this case.  Logically speaking, you are expressing that you don't care what ip is on the first instance, by removing the declaration of a specific ip.  So Terraform is correct in not re-assigning a random IP (which is the behavior of the GCE API as well, I think).  We could force this by removing & re-adding the access config.  @phinze ?

@lwander : Can you check the code and see if that's consistent with what I think is going on?

**Comment by sparkprime** [comment]
Oh if you're trying to do them in parallel, this will never work.  You have to do 2 terraform applies here because otherwise there is a race condition.

**Comment by lwander** [comment]
The race condition @sparkprime pointed out isn't something we can fix on the provider end, so you'd have to take his approach and do this in 2 applies.

The other issue is that `nat_ip` is marked as `computed`, causing Terraform to not pick up on changes made to that field by the user. I'm guessing it's done this way because GCE will assign an IP if you don't specify one. I'm tempted to fix this by breaking `nat_ip` into 2 fields, `nat_ip` and `nat_ip_assigned`. `nat_ip` could be a user specified address, `"ephemeral"`, or blank (treated as `"ephemeral"`). `nat_ip_assigned` would be a computed field carrying the actual value of the address. Existing `compute_instance` resources won't break, since the `nat_ip` field will either be interpreted as `"ephemeral"` if they are blank which matches existing behavior, or the existing address will be used as before. The issue comes in with existing resources that depend on this address when it is left blank. A `state_migrate` function won't help since we can't change resources that depend on the instance leaving configurations to break unexpectedly. 

@catsby, @phinze, do you have any ideas on what to do?

**Comment by phinze** [comment]
Hey folks,

> I don't know what Terraform should do in this case. Logically speaking, you are expressing that you don't care what ip is on the first instance, by removing the declaration of a specific ip. So Terraform is correct in not re-assigning a random IP (which is the behavior of the GCE API as well, I think). 

Yep! This is correct behavior for a `Computed` attribute.

> I'm tempted to fix this by breaking nat_ip into 2 fields, nat_ip and nat_ip_assigned. nat_ip could be a user specified address, "ephemeral", or blank (treated as "ephemeral").

I always hesitate to go down a "special case attribute" road, so let's see if there's a way to solve this use case in another way and we can circle back around to a solution like that.

In similar situations in other providers we have modeled the "attachment" or "association" as itself a declarative CRUD resource. This allows it to go through a normal lifecycle where create == attach and destroy == detach. One example of this is [`aws_volume_attachment`](https://terraform.io/docs/providers/aws/r/volume_attachment.html).

Could an approach like that help us here?

**Comment by sparkprime** [comment]
In principle, "resetting" the IP by removing and re-creating an accessconfig within the resource may actually get you the same IP again, since it's random.  I wonder if what we should be encouraging people to do is to be more explicit by either assigning a fresh temporary ip to the instance, or removing the access_config altogether (so there is no ip assigned).  Then in a second apply re-assigning the old ip to the new instance.  I think that's the only way that can be guaranteed to work.

**Comment by sparkprime** [comment]
@phinze I don't understand what difference it makes having a separate resource like that.  I'm thinking it's like denormalization of a relational database.  I think there should be an equivalent there -- either you hit create/destroy of the new resource, or, if you put it in one or other of the resources being linked together, you'll hit the udpate of that resource.  What's the practical difference there?

**Comment by lwander** [comment]
@phinze, the issue I was trying to fix with an extra attribute is that in the [GCE representation](https://cloud.google.com/compute/docs/reference/latest/instances#networkInterfaces.accessConfigs) the `networkInterfaces.accessConfigs.natIp` field is used to mean two things:

1. If it is empty, assign a random IP, and provide it by value in the response resource.

2. If it is filled, attempt to assign that IP, and if successful, keep that value in the response resource.

If we leave this field as `computed`, it won't pick up on user changes as noticed by @JorritSalverda. If we make it `optional`, and the user leaves it blank to be assigned a random IP, Terraform can't write to that field without generating a non-empty diff (`"" != "<assigned ip>"`) on `apply`.

**Comment by phinze** [comment]
Reviewing the thread here along with those linked docs, I think in this case you might be right that the duplicate fields are the best way forward.

> The other issue is that nat_ip is marked as computed, causing Terraform to not pick up on changes made to that field by the user.

Point of clarification here: `Computed`, `Optional` fields will pick up changes made by the user that result in a non-empty value. The key difference is in how they treat attribute _omission_. `Computed` fields treat omission as "whatever the provider says it is", while non-`Computed` fields treat omission as "user specified empty explicitly, any value that shows up in this attribute should trigger a diff because it needs to be cleared out."

I'm trying to picture what core support for this situation would look like, and I'm coming up at a loss. Ideas welcome there, but in the meantime, `nat_ip` and `assigned_nat_ip` aren't looking so bad after all. :grinning:

**Comment by lwander** [comment]
Following up with @JorritSalverda - have you taken a look at the fix? We can't deal with the race condition @sparkprime pointed out above due to Terraform constraints.

**Comment by catsby** [comment]
Hello – it's been quite some time, so I'm going to assume this is resolved and close the issue. Thanks!
