### ISSUE TITLE
Support MFA on AWS

### ISSUE THREAD

**Issue by philk** [hashicorp/terraform#390]
It looks like Terraform doesn't currently support using Multi-factor Auth for AWS (unless I'm missing something). Not currently a major issue for us but we'd love to be able to use it in the future.

Useful links:
- [AWS Security Token Service][1]
- [Boto's implementation][2]

[1]: http://docs.aws.amazon.com/STS/latest/UsingSTS/Welcome.html
[2]: https://github.com/boto/boto/pull/1942/files

**Comment by koendc** [comment]
In order to use the AWS security token, you need to:
1. provide empty strings for access_key and secret_key:
```
    provider "aws" {
        access_key = ""
        secret_key = ""
    }
```
2. Make sure you don't have the environment variables set as mentioned in the terraform documentation
3. Use these environment variables instead:  `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SECURITY_TOKEN`.

**Comment by mitchellh** [comment]
FIxed

**Comment by nwhite-sf** [comment]
This appears to be out of date with 0.10.7. I tried setting the AWS_SESSION_TOKEN, AWS_ACCESS_KEY. and AWS_SECRET_ACCESS_KEY to the values returned by `aws -profile MY_PROFILE sts get-session-token --duration-seconds 129600 but that didn't seem to work. I'm sure I am doing this wrong. Thoughts?
