### ISSUE TITLE
what's the proper way of dealing with an instance marked for retirement?

### ISSUE THREAD

**Issue by rgs1** [hashicorp/terraform#3915]
In AWS (surely there's something similar in other environments) an instance can be marked for retirement:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-retirement.html

From a quick git grep in the repo and search in the issues tracker, I couldn't see any logic to handle these instances. Has any thought been put into what Terraform should provide to deal with these instances (or maybe there is a way of doing this already)?

**Comment by apparentlymart** [comment]
This is a very good question.

So far when I've encountered this problem I've just manually run `terraform taint` on the resource in question and had Terraform rebuild it, but I've only done this so far for instances thwt were ephemeral anyway, and so they were designed to be replaced often.

One way to deal with this issue, at least for EBS-based instances, is to restart the instance so that it migrates to new hardware. That could potentially be done outside of Terraform, but for Terraform to do it would look like what was disussed in #1579.

We could potentially have an option on the `ec2_instance` resource that tells Terraform to explicitly restart an instance when it's retired, which could then just be done as part of "updating" the instance, but it's not great to do that sort of multi-step workflow inside a single resource action because Terraform can't easily represent the intermediate steps in the state and thus won't be able to recover well if any part of the process fails.

So yeah... definitely an important use-case but one I think Terraform's current model doesn't handle very well. Thanks for starting this discussion! I'm curious to see what other folks come up with.

**Comment by k3ypad** [comment]
There is a feature in AWS that allows for this: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-recover.html

It would be great to see the aws_cloudwatch_metric_alarm handle this - however the external AWS API only supports ARNs (for sns publishing and autoscaling actions): http://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html

A proper solution for this is blocked pending AWS supporting this via their APIs.
I'd urge us all to log feature requests via support for this.

**Comment by k3ypad** [comment]
Good news actually, I was being silly.

There is a way to deal with these and Terraform does support them - use the ARNs found here:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UsingAlarmActions.html
 in the "alarm_action" to auto recover an instance

**Comment by shorn** [comment]
Had a AWS instance die on me over the weekend.
When I tainted the instance, TF just hung for ages, then timed out.  EC2 instance was not shutting down when I ran terminate from the console.

It was actually just my bastion instance, so not that big a deal - but I needed to get TF going again in order to do some other stuff with my infrastructure.

I ended up having to edit the tfstate file. I just deleted the "tainted" attribute and left "primary" as null.
Then when I ran apply it told me it was going to create the instance and update associated resources (instead of destroying the old instance).  Which is what it did and everything was fine again.

Yes, this still leaves me with my problematic resource sitting around - but now I can investigate the problem at my leisure, instead of having to deal with the problem immediately just so I can get TF working again in order to do anything with my infrastructure (the EC2 instance did shut down eventually, but it just took ages to do it). 

There's always going to be situations where TF can't help you get rid of a problematic resource (regardless of which cloud provider you're using).  
What I needed was for TF to help me with a quick way to work around problematic resources - not random advice on how to deal with AWS infrastructure.

What I think I wanted was a way to tell TF "forget about this resource, pretend it doesn't exist".  
I recommend there should be something like a "forget" command or a force option to the taint command.  The intent being to force TF to act like it knows nothing about the broken resource, similarly to when the resource is first created, for example.

**Comment by cwarden** [comment]
I have an alarm set on the `StatusCheckFailed_System` metric with `arn:aws:automate:us-east-1:ec2:recover` alarm action.  When the ec2 instance was retired, the alarm entered the `INSUFFICIENT_DATA` state rather than the `ALARM` state.

Using the recover action as an insufficient data action doesn't seem right.  Any other ideas?
