### ISSUE TITLE
Status report for Remote State Config

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#3991]
While using Terraform remote state, I end up wanting to confirm the state/status of the remote config. A simple dump of the current config info and sync status would be so very helpful - I propose: `terraform remote status`

**Comment by cleung2010** [comment]
Any updates on this? If this feature is available, we could at least script some guard mechanism against the potential issue described in #4584.

**Comment by teamterraform** [comment]
Hello! Sorry for the long silence here.

This issue comes from before the introduction of "backends" in Terraform 0.9, and so it's discussing the `terraform remote` command that no longer exists in recent versions of Terraform, and so we're going to close this one out. Thanks for this suggestion, and sorry again for the delay in responding to it.
