### ISSUE TITLE
can you create a gitter channel rather than irc?

### ISSUE THREAD

**Issue by cordoval** [hashicorp/terraform#4027]

**Comment by mitchellh** [comment]
Sorry, but we prefer IRC as our method of communication for open source projects. It isn't trendy, but it is consistent. We have a wide ranging group of users who all have their own opinions on what chat method should be used but IRC is a good common denominator. 

You can also use the mailing list if you don't want to use IRC.

**Comment by cordoval** [comment]
yeah i surrender to your genius, i only proposed because i just received a lot of help on the docker channel at gitter. No prob, i shall use whatever is available.

**Comment by mitchellh** [comment]
No problem, we may look at it at some point especially because it has an IRC bridge. For now, we're sticking with what we have!

**Comment by phanect** [comment]
+1

Because IRC doesn't support log, users live in very different time zone from US/EU have less chance to get supported. Most people are sleeping when I'm asking.

As @mitchellh pointed out, [Gitter have IRC bridge](https://irc.gitter.im/), and users who prefer IRC still can use their favorite clients.

**Comment by cordoval** [comment]
oh nice, @phanect yeah, the only hassle is that there are not just one repository so multiple for all hashicorp stuff, including consul and what have you :blush: so they see the big picture.

**Comment by jen20** [comment]
@cordoval there is also a channel on the [HangOps](http://signup.hangops.com) Slack where some of the Terraform team and contributors hang out from time to time. You may also want to look into irccloud, which provides similar log semantics to Slack/Gitter etc for IRC channels.

**Comment by phanect** [comment]
>  the only hassle is that there are not just one repository so multiple for all hashicorp stuff, including consul and what have you :blush:

Year, maybe we can help modifying readme.

> there is also a channel on the HangOps Slack where some of the Terraform team and contributors hang out from time to time.

Oh, I didn't know that. I wonder if I can post question there.

> You may also want to look into irccloud, which provides similar log semantics to Slack/Gitter etc for IRC channels.

"Migrating" to irccloud is also a good idea, but it doesn't support OAuth signup and a little bit tough to signup, so I wonder if people prefers another IRC client.
If most people who gives answer use IRC client without log support, they don't see questions posted while they are sleeping.

If Hashicorp projects migrate to Gitter and paste Gitter badge on Readme, I expect more people use Gitter rather than IRC client. Gitter supports Github login and it is not messy to create account.
If Slack, it doesn't support IRC and everyone has to use Slack UI. So even people have to new Slack account with password, it is not so big problem for me, but maybe problematic for some.
