### ISSUE TITLE
Should "apply" check that the serial of the state hasn't changed since the creation of the plan?

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#4055]
From what I've seen, it is possible to create a plan against the state with serial `x`, modify the state to have the serial `x+2`, then apply the plan against the state with serial `x+2`.
This actually updates the serial to `x+1`, sending us "back in time".

Is this the expected behaviour?

I was under the impression that if the serial of the state has been updated since the creation of the plan, the plan needed to be recreated.

**Comment by ColinHebert** [comment]
@catsby any news?

**Comment by apparentlymart** [comment]
I've been keeping [a log of cases where Terraform failed to protect me from silly errors](https://gist.github.com/apparentlymart/657885e730d1e5abc6ea) and this was the first thing on my list.

I agree that this would be a great improvement to help prevent mistakes, so :+1: from me.

I would also like to make Terraform produce an empty plan file when there are no changes to make, rather than exiting successfully without writing out the plan file... as I mention in my doc, if you're using terraform interactively at a CLI then it's likely that have an existing plan file from an earlier run, and one can easily forget that Terraform won't write out empty plans and accidentally try to apply the stale plan.

**Comment by catsby** [comment]
This certainly sounds like a good idea, I'll discuss internally to see what we can do and/or review https://github.com/hashicorp/terraform/pull/4616

**Comment by jszwedko** [comment]
@apparentlymart can you comment on whether this issue is addressed by 0.9?

**Comment by ColinHebert** [comment]
Timed out
