### ISSUE TITLE
CLI Crash - running 'terraform plan'

### ISSUE THREAD

**Issue by rvanoo** [hashicorp/terraform#4081]
See attached crash log. Terraform v0.6.7

[crash.txt](https://github.com/hashicorp/terraform/files/45305/crash.txt)

**Comment by rvanoo** [comment]
Reverting to 0.6.6 (this is all on Ubuntu 12.04 LTS) does the trick.

**Comment by jen20** [comment]
Hi @rvanoo! Thanks for reporting this. This looks like you're running into the issue fixed by #4024, which will be in a point release immediately after the (US) holiday season is over and everyone is back at work. Since we've already fixed the issue, I'm going to close this issue - if you want to follow issue #4024 I'll update that with a comment when the release is made.

In the meantime, there are a couple of options available to you:

- revert to 0.6.6 (as it appears you have already done)
- build from the `master` branch which contains the fix. You will need a Go programming language development environment for this, but it should be as straightforward as cloning the repository and then running `make updatedeps` and `make dev`.
