### ISSUE TITLE
Deleting a Lambda does not delete event source mappings?

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#4089]
Further to #3897, <del>it looks like if there is already the correct access to a Kinesis stream from a Lambda, it tries to create the mapping automatically</del>, (**note, I think this is actually because the workaround was applied. See below.**) as the workaround that is detailed there breaks with the `The event source arn and function provided mapping already exists` error.

However, the following mapping gets created disabled and requires manual activation afterwards. The abridged issue in the console:

```
Batch size: 100, Last result: PROBLEM: Function not found under accountId 123456789012 in database
(Service: null; Status Code: 0; Error Code: null; Request ID: null)
```

I don't have any mapping stuff in my template when this happens, so the only thing that I can think of is SDK/API issue or something? I'm going to look at the source to see if I can find some sort of confirmation.

**Comment by vancluever** [comment]
I'm kind of wondering if this is partially the issue:

```
// When you delete a function the associated resource policy is also deleted.
// You will need to delete the event source mappings explicitly.
```

From the Go SDK, `func DeleteFunction`

Possibly deleting the function is not deleting the mappings?

**Comment by vancluever** [comment]
Corrected the subject to reflect the current state of the tool and what more probably what is happening.

Educated guess here, but I'd imagine since Terraform does not support event source mappings currently it's not really thinking about wiping any that might be around after deleting the function.

**Comment by vancluever** [comment]
Submitted PR to add `aws_lambda_event_source_mapping` (referenced back to here). This does not directly fix this "bug", but it should reduce the scenarios where it would come up.

**Comment by radeksimko** [comment]
@vancluever Thanks for implementing the `aws_lambda_event_source_mapping`, however I don't think that what you're describing in this issue this is a bug or behaviour which should be changed.

The essential philosophy of Terraform is to only manage resources that are defined in its config(s) which helps us preventing conflicts with other tools that may be managing different parts of the infrastructure.

The preferred approach at the moment is to error out in case Terraform would try to remove a resource that has some dependencies which are managed outside of Terraform.

If you choose to use two or more tools, each to manage different part of your infrastructure, you will likely be choosing between tools that don't stamp on each others' toes and I'd like Terraform to be one of the choices, hence I'm inclined to close this issue.

Feel free to come up with reasons why the described behaviour should be changed, otherwise I'll close this in couple of days.

**Comment by vancluever** [comment]
Hey @radeksimko, sorry if leaving this open had given the impression that this was still a concern for me! Yeah no, I'm totally fine with what you just mentioned, and as far as I'm concerned #4093 made this a non-issue. Closing this now.

Cheers!
