### ISSUE TITLE
[feature request] [terraform-provider-tls] Add public key to resource output

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#4134]
It would be nice if the `tls_private_key` provider also allowed you to get the public key associated with the newly created private key.

**Comment by apparentlymart** [comment]
Hmm yeah this is a good idea. Honestly I'm not sure why I didn't just implement that the first time since the code is already using a hash of the public key as the internal resource id, so it's already doing [all of the work to obtain it](https://github.com/hashicorp/terraform/blob/f6fd41e7b54b38176090557c4a13e18c86e46fbe/builtin/providers/tls/resource_private_key.go#L115).

I'm a bit snowed under to implement this right now but I will try to return to and work on this in a few weeks, unless someone else wants to attack it. I think it should be be an easy enough change and could be a good "my first Terraform change" for someone who is looking for one.

It looks like it's just a matter of declaring a new `public_key_pem` attribute in the schema and then doing something like this:

```go
pubKeyPemBlock := &pem.Block{Type: "PUBLIC KEY", Bytes: pubKeyBytes}
d.Set("public_key_pem", string(pem.EncodeToMemory(pubKeyPemBlock)))
```

**Comment by mtougeron** [comment]
@apparentlymart No rush on this one. Learning Go is on my to-do list for Dec so if no one gets to it before me I'll take a crack at it. :)

**Comment by simar7** [comment]
hey @apparentlymart I just wrote a diff to solve this, I'm still new to terraform and go so I'm still unsure how I can test this out. Do you have any ideas?
