### ISSUE TITLE
question: provisioning to non static IP

### ISSUE THREAD

**Issue by joeblew99** [hashicorp/terraform#4151]
I am using terraform and atlas, but i also now need to use it to provision to boxes out in the field.
These boxes are normal linux boxes, and run docker and lxc or whatever.

It's a bit like IOT style topology, and so the way you interact is the same as a botnet.
The field server polls in occasionally, and you give it instructions what to do next.
In the data center, sou maintain a basic state of each field server, so you always know what state it's in.

Thoughts?

**Comment by mitchellh** [comment]
I'm sorry no one ever responded here, issues aren't the best place for questions. 

Please ask questions like this on the mailing list or our other community resources.

Because it has been so long though, I'll answer as best I can: while Terraform ultimately requires a specific IP/address to provision to, you can interpolate that value from other locations. So, perhaps a data source or another resource is the proper place to grab your dynamic address.
