### ISSUE TITLE
Allow to specify AWS.Region endpoint to support Eucalyptus flavor of EC2

### ISSUE THREAD

**Issue by elyast** [hashicorp/terraform#416]
Feature request, allow to specify endpoint as following: 
```
    region "region x" {
      ec2_endpoint = "http://eucalyptus.escloc57.eecloud.nsn-net.net:8773/services/Eucalyptus"
      s3_endpoint = "..."
    }
```
How to use goamz with euca: https://www.eucalyptus.com/blog/2014/04/24/using-golang-eucalyptus

**Comment by phinze** [comment]
We've had recent users reporting success in using Terraform with Eucalyptus, so I'm going to mark this as closed. Feel free to lobby for reopening if there's still something we're missing in the latest version.

**Comment by elyast** [comment]
care to share sample config?

**Comment by phinze** [comment]
@elyast sure! Here's the issue where working config was being tossed around: https://github.com/hashicorp/terraform/issues/1752#issuecomment-97778713

**Comment by elyast** [comment]
@phinze looking at the config I am not sure how do u specify region url, additionally looking at: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/config.go#L127 its hard to believe "eucalyptus" is proper region name...

but if you want to track this feature in #1752 fine with me

**Comment by phinze** [comment]
Hmm good point @elyast, I wonder if @jeevanullas was working with a custom local build. Your logic makes perfect sense - reopening to track here. Sorry for the mixup!

**Comment by jeevanullas** [comment]
Hi All,

Thanks @phinze for the ping here. @elyast as terraform uses AWS SDK for Go we just modified the relevant endpoint maps in SDK for Go. This helps us because we also use AWS SDK for Go outside of Terraform. In case you are wondering this is how we did it: https://github.com/jeevanullas/aws-sdk-go/commit/a35daa3ae18113d182e202419f00a750c266bd3d

By the way this code in terraform here https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/config.go#L125-L138 can be removed because it is an extra check on the valid regions. Terraform is using AWS SDK for Go so it should rely IMHO on AWS SDK for Go to do the validation.

Please let me know if you have any questions.

Cheers,
Deependra

**Comment by lwade** [comment]
+1 ref removing https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/config.go#L125-L138

**Comment by catsby** [comment]
An advantage of `ValidateRegion` is that we can validate the region in the `plan` phase of things. Without it, using an invalid region will generate an error at `apply` time.

**Comment by catsby** [comment]
Hey friends – I've merged #4263 which allows you to set a custom endpoint for ELB, EC2 and such, so I'm going to close this. Let us know if you need anything else.

**Comment by iamfuzz** [comment]
Hi, I tried running the asg aws example against a Euca 4.2.2 cloud but it bails out due to "eucalyptus" being an invalid region name.  Can you patch the provided go sdk to allow for it as a region name? Thanks!

**Comment by gad0lin** [comment]
+1, without ability to pass region validation it can't be used.

**Comment by zkorinek** [comment]
+1 without the possibility to define custom region, the custom endpoints not working.

**Comment by gad0lin** [comment]
Any chance to remove check against hardcoded endpoint. I have been using terraform on ec2 but can't use it against internal Eucalyptus clouds .
