### ISSUE TITLE
Support for java aws lambda function

### ISSUE THREAD

**Issue by rfhayashi** [hashicorp/terraform#4314]
I've tried to create an aws_lambda_function with "java" runtime but got the following error:

```
* aws_lambda_function.jenkins_startup: Error creating Lambda function: ValidationException: 1 validation error detected: Value 'java' at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [nodejs]
status code: 400, request id: c76fa561-a289-11e5-8e32-2b1f89243f06
```

Are there plans to support java runtime?

**Comment by jen20** [comment]
Hi @rfhayashi - thanks for opening an issue. This error is actually coming from the AWS API rather than Terraform. We don't actually validate the `runtime` argument to `aws_lambda_function`.

As per the documentation for the `lambda:CreateFunction` operation you need to specify `java8` as the runtime type for Java. I just verified this works correctly, so I'll close this for now - if changing `java -> java8` does not fix your issue please re-open it!

**Comment by rfhayashi** [comment]
Thank you @jen20. It does work.
