### ISSUE TITLE
[feature request] provider/aws: add support for R53 traffic flow

### ISSUE THREAD

**Issue by myoung34** [hashicorp/terraform#4333]
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/traffic-flow.html

I know this will go on the backburner with all the others, but the ability to set this up via terraform would be a god-send

**Comment by chrisburrell** [comment]
+1

**Comment by myoung34** [comment]
Any changes to this?

**Comment by stack72** [comment]
Hi @myoung34 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
