### ISSUE TITLE
ingress egress port

### ISSUE THREAD

**Issue by dnascimento** [hashicorp/terraform#4349]
To allow HTTP and HTTPS your template gets full of:
  ingress {
      from_port = 80
      to_port = 80
      protocol = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
      from_port = 443
      to_port = 443
      protocol = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
  }

It would be great to have a **port** key.  The port range doesn't make sense in most of cases.

**Comment by phinze** [comment]
Hi @dnascimento, thanks for the feedback. I agree that the `from_port` / `to_port` pair is a bit clunky to use.

The thing is, we're matching the upstream AWS API here, and it's our policy to avoid too much divergence from the upstream provider APIs so that anybody learning about AWS from their docs will understand how to use Terraform to interact with AWS resources.

It's an unfortunate side effect of this policy that some APIs are not as elegant as we would like them to be, but we have found that the consistency is worth it.

I hope this helps to explain things! I'm going to close this issue, but feel free to follow up if you'd like to discuss further. :grinning:
