### ISSUE TITLE
remote config and git

### ISSUE THREAD

**Issue by jeroenjacobs1205** [hashicorp/terraform#4360]
Hi,

I started experimenting with TerraForm remote config in S3, to avoid merge conflicts in git regarding the state file.

However, things don't seem to be that easy. After configuring remote config, you end up with .terraform folder which still contains a copy of your state file. Is this cached copy always refreshed when doing an "apply"? Or do I need to do a "terraform pull" and "terraform push" before and after I do "terraform apply"?

Wouldn't it be better if the .terraform folder only contains a reference to the remote config parameters? Then, when we run "terraform apply", let it pull a new cached copy, apply the changes, and then push it back? Then remove the temporary cached states if the push is successful?

I'm also confused about how "terraform plan" fits into this. It seems to change the state file too, which IMHO shouldn't happen as it is just a simulation of your changes, and not an actual change.

What is the best way to avoid git merge conflicts with TerraForm in general?

**Comment by apparentlymart** [comment]
The interactions around remote state in Terraform are a little tricky, but to answer your questions first:

* Terraform will generally pull and push the remote state for you automatically. The local cache is really just that: a cache. You can usually ignore it.
* `terraform plan` changes the state file because by default it implies a `terraform refresh`, which updates the state to match the "real world" as much as possible. For example, if you have added a tag to an EC2 instance via the AWS console, the `refresh` step will notice this and incorporate it in the state so that the diff is based on the current state rather than than the state at last apply. You can override this behavior by passing `-refresh=false` to the `plan` command, but you should do that only if you're sure that the infrastructure is not changing outside of Terraform.

On top of those questions, you should know that once you're using remote state you need to make sure that everyone who is working on your same infrastructure *always* sets up remote state before interacting with the config, or else will appear that no infrastructure exists and Terraform will want to create a duplicate set of infrastructure. There is currently no way to tell Terraform within the configuration that remote state is available, though that is something we were discussing a while back in #1964.

When it comes to merge conflicts, since the Terraform state is a snapshot of the current state of the world, the resolution of such a conflict will almost always be to keep the newer version, because it's likely to be the most complete and accurate. The problem arises when multiple users run `terraform apply` at one time, and create two competing "current states" that each have a different instance of some resource. The remote state mechanism doesn't help with this either, since it provides no locking capabilities. In order to prevent this problem it is necessary to ensure that only one `terraform` operation is happening at a time per state.

Currently the only pre-packaged solution to locking state is to run Terraform with Hashicorp Atlas, as described at the bottom of [the remote state page](https://terraform.io/docs/state/remote.html).

At work we currently deal with this in a rather ad-hoc way by just announcing changes to "bottleneck" infrastructure in our internal chat. By "bottleneck" here I mean the infrastructure that has many people working on it because it is core to our architecture, vs some of our less-critical peripheral infrastructure that doesn't prevent such a problem because there are relatively few people touching it. Not ideal, but it's mostly working for our small team right now aside.

**Comment by jeroenjacobs1205** [comment]
Thanks for clearing this up.
