### ISSUE TITLE
ECS Service erroring out due to eventually-consistent IAM role

### ISSUE THREAD

**Issue by cordoval** [hashicorp/terraform#4375]
aws_autoscaling_group.ecs-cluster: Creation complete
Error applying plan:

1 error(s) occurred:
- aws_ecs_service.lead-validation: InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions.
  status code: 400, request id: dca57d15-a4ef-11e5-9749-03d1427e2486

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

after terraform apply again, it passes

**Comment by radeksimko** [comment]
Your assumption is correct, this is caused by the eventual consistency nature of IAM.

We've been fighting with this all over the place, oddly it seems to be visible most in ECS... I'm not sure if it means that AWS treats ECS differently or whether people just manipulate with this IAM role here more often, so that the issue is more visible here. It may also be less visible in EC2 Instance Profiles purely because starting EC2 instance takes more time (I'm really just guessing).

Here is a sample from my debug log supporting the theory:

```
2015/12/22 13:55:25 [DEBUG] Creating ECS service: {
  ClientToken: "terraform-jorhmd4mrjbvbcikqyoune32zu",
  Cluster: "arn:aws:ecs:us-west-2:229213142987:cluster/terraformecstest11",
  DesiredCount: 1,
  LoadBalancers: [{
      ContainerName: "ghost",
      ContainerPort: 2368,
      LoadBalancerName: "tf-lb-orxnwpsknbgc5dhm6guvpq2rje"
    }],
  Role: "EcsService",
  ServiceName: "ghost",
  TaskDefinition: "arn:aws:ecs:us-west-2:229213142987:task-definition/ghost_service:56"
}
2015/12/22 13:55:25 [DEBUG] Waiting for state to become: success
2015/12/22 13:55:26 [DEBUG] Trying to create ECS service again: "Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions."
2015/12/22 13:55:27 [DEBUG] ECS service created: arn:aws:ecs:us-west-2:229213142987:service/ghost
2015/12/22 13:55:27 [DEBUG] Updating ECS service arn:aws:ecs:us-west-2:229213142987:service/ghost
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalWriteState
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalIf
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalWriteDiff
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalIf
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalWriteState
2015/12/22 13:55:27 [DEBUG] root: eval: *terraform.EvalApplyPost
2015/12/22 13:55:27 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_ecs_service.ghost: InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions.
	status code: 400, request id: 1511a6fc-a8ab-11e5-bc54-1dd530d1af1e
```

As you can see ^ the error is **coming from the Update call**, which means that ECS API actually allows you to create a new ECS service at one point, purely because it talks to a part of IAM which already has the IAM policy, but the Update call hits a different part which doesn't have that yet, hence it fails.

I've described this problem in depth here:
https://github.com/hashicorp/terraform/pull/3928#issue-116996897

KMS is apparently affected by this too.

**Comment by russmac** [comment]
I have the same issue except that multiple applies has no effect. Destroy and apply also doesnt resolve it.

2016/03/03 17:16:02 [DEBUG] terraform-provider-aws: 2016/03/03 17:16:02 [DEBUG] Trying to create ECS service again: "Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions."
2016/03/03 17:16:02 [DEBUG] terraform-provider-aws: 2016/03/03 17:16:02 [TRACE] Waiting 500ms before next try

**Comment by brikis98** [comment]
Same problem here. Also with ECS.
