### ISSUE TITLE
OVH Provider

### ISSUE THREAD

**Issue by KFishner** [hashicorp/terraform#443]
OVH as a provider option

https://api.ovh.com/

**Comment by armetiz** [comment]
I'm interested about this feature.

**Comment by musicformellons** [comment]
+1 interested!!

**Comment by VincentCasse** [comment]
OVH API allow now adding extra hardware using public cloud APIs : https://api.ovh.com/console/#/cloud/project#GET

Because OVH public cloud is based on Openstack, you can use provider "Openstack" in terraform to use OVH cloud before a better integration : https://www.terraform.io/docs/providers/openstack/index.html

**Comment by musicformellons** [comment]
cool! would it work to combine ovh dedicated servers with ovh public cloud servers using hashicorp tooling?

**Comment by VincentCasse** [comment]
OVH dedicated servers are not "openstack compliant". There is an API to manage it, but the API is really different. So, that's not possible to use Openstack provider to manager dedicated servers.

But, I could be a good idea to integrate it into a specific OVH provider!

**Comment by Tails** [comment]
+1
they are the biggest host. definitely useful

**Comment by Durtdiver** [comment]
+1

**Comment by jcftang** [comment]
+1 would be good to have an OVH provider

**Comment by admdwrf** [comment]
+1

**Comment by millerjp** [comment]
+1

**Comment by stack72** [comment]
There is a provider for this in existance- https://github.com/yanndegat/terraform-provider-ovh

We are trying to work with that author on bringing it into the terraform project
