### ISSUE TITLE
making datadir configurable?

### ISSUE THREAD

**Issue by calvinfo** [hashicorp/terraform#4487]
Hey guys, would you be amenable to making `datadir` configurable for commands like `plan`, `remote` and `apply`? I'm happy to add a PR for it.

Our use case is that we want to isolate `.tfstate` files, but keep most of the `.tf` configuration being planned from the same repo. We could move the `datadir` around outside, but it'd be nice if you could just pass a flag to the binary and it'd use whatever folder was passed to it.

**Comment by phinze** [comment]
Hi @calvinfo!

The `plan`, `remote`, and `apply` commands all accept the `-state` flag to specify a `.tfstate` file you'd like to use for the run. The config is processed from either the current working directory or the path specified by the first argument after the command.

I believe this should address the use case you're describing, but let me know if not and we can continue to discuss!

**Comment by calvinfo** [comment]
Gotcha, I think there might be a bug then where the remote state doesn't actually respect the `-state` flag, since it seems to hardcode to `.terraform/terraform.tfstate` when copying to the local path in my debugging. 

I'll try coming up with a test case for it tomorrow. If that works, then that will do nicely!

**Comment by phinze** [comment]
Ah yeah that may be possible - it's less common to customize the state location using remote state, so I could see us having a bug hiding in there.

Going to close this since we have the functionality in place and I'll keep an eye out for a fresh bug report from you. :+1:

**Comment by glasser** [comment]
@phinze Probably this is the line in question, among others: https://github.com/hashicorp/terraform/blob/f257895d/command/state.go#L182

The module path is also hard-coded.

We'd like to be able to just an env var in our wrapper script to override the data dir, rather than carefully ensure that it is passed to precisely the commands that know about it.  Our use case is being able to use a single source directory to act on multiple environments: for example, the ability to bring up multiple fully independent environments in parallel for testing.  Right now I find myself doing a whole lot of `cp -R dev dev2` or just saying "oh well, I'm deploying to my dev environment, guess I can't run the integration tests in parallel".

I have an almost-ready PR. Would be great to reopen this issue.
