### ISSUE TITLE
Removing overridden default value does not trigger diff

### ISSUE THREAD

**Issue by yissachar** [hashicorp/terraform#4501]
Let's say I have the following VPC definition:

``` hcl
resource "aws_vpc" "main" {
    cidr_block = "10.0.0.0/16"
    enable_dns_hostnames = true

    tags {
        Name = "main"
    }
}
```

I've set `enable_dns_hostnames` to `true`, overriding the default value of `false`. I apply the changes and go on my way. A little while later I decide that I don't want to enable DNS hostnames after all, so I remove that line, assuming that it will revert to the default of `false`. But when I run `terraform plan` it tells me that no changes were detected. In order to trigger a diff detection I have to explicitly set `enable_dns_hostnames` to `false`, which seems wrong.

**Comment by apparentlymart** [comment]
The `enable_dns_hostnames` attribute is a member of a weird class of arguments that are both "Optional" and "Computed" at the same time.

In user-oriented terms, this means that the value is optional but if you don't specify it then its value isn't known until after the object has been created, since the default is defined by the remote API. Once a resource has been created, Terraform will just accept whatever value the server currently has unless you specifically override it.

The trick with this sort of attribute is that Terraform uses the presence or absense of the configuration as the trigger to decide whether you want to accept the server's default or override your own. When you removed the `enable_dns_hostnames = true` you effectively told Terraform "I don't care"; explicitly specifying `false` tells Terraform that you want to override the value the server has.

While I agree this is a little surprising, it *is* the intended behavior. It doesn't help that the Terraform docs don't really ever talk about this special Optional+Computed case; perhaps we could consider this a ticket to clarify this somehow in the documentation?

**Comment by yissachar** [comment]
That explanation makes sense. Would definitely be nice to have this explained somewhere in the docs.

**Comment by mildwonkey** [comment]
Since this is a very old issue, and the AWS provider documentation is in the aws provider repository, I am going to close this issue. If this is still a problem, please open a new issue with the aws provider. Thanks!
