### ISSUE TITLE
splat syntax not documented as announced

### ISSUE THREAD

**Issue by henning** [hashicorp/terraform#4507]
in https://www.terraform.io/docs/configuration/interpolation.html we read:

"You can also use the splat syntax to get a list of all the attributes: ${aws_instance.web.*.id}. This is documented in more detail in the resource configuration page."

This is not true for the linked page https://www.terraform.io/docs/configuration/resources.html

Neither is this syntax form with a star shown anywhere on the mentioned page as an example, nor is the word "splat" anywhere used in this page. 

I get a basic idea how this thing is supposed to work based on existing code in a project started by someone else, but not documentation on the terraform reference on how exactly it is working and to be used or adjusted.

**Comment by apparentlymart** [comment]
Hi @henning! Sorry for the long silence here.

The documentation is seeing some considerable reorganization in preparation for the v0.12.0 final release, and so the "interpolation" page where you found this dead link will be replaced with [a new "expressions" page](https://github.com/hashicorp/terraform/blob/master/website/docs/configuration/expressions.html.md) which now has [a full section on splat expressions](https://github.com/hashicorp/terraform/blob/master/website/docs/configuration/expressions.html.md#splat-expressions).

Since v0.12 is still in its pre-release phase (alpha1 was released last week) this documentation is not yet visible on the website, but the new content I linked above will be pushed to the website to coincide with the v0.12.0 final release.

The syntax is now covered fully on the expressions page because Terraform v0.12 will introduce a generalized form of this syntax that works with any list value in the language, whereas in v0.11 and prior it was a special case only for resources with `count` set.

Thanks for pointing this out, and sorry again for the long delay in fixing it.
