### ISSUE TITLE
Diffs don't match for aws_route53_record

### ISSUE THREAD

**Issue by jmstone617** [hashicorp/terraform#4538]
I got the following error when running `terraform apply`. This was after a few successful applies and then a destroy:

> - aws_route53_record.www: diffs didn't match during apply. This is a bug with Terraform and should be reported.

What other information can I provide to help with this?

**Comment by phinze** [comment]
Hi @jmstone617 - could you provide the configuration (with sensitive information omitted) that generated this error message?

**Comment by jmstone617** [comment]
Here is the record:

    resource "aws_route53_record" "www" {
	    zone_id = "${aws_route53_zone.primary.zone_id}"
	    name = "www"
	    type = "A"
	
	    alias {
            name = "ourdomain.com"
            zone_id = "${aws_route53_record.primary.zone_id}"
            evaluate_target_health = false
          }
    }

It's related to this record:

    resource "aws_route53_record" "primary" {
	    zone_id = "${aws_route53_zone.primary.zone_id}"
	    name = "ourdomain.com"
	    type = "A"
	    ttl = 300
	    records = [ip_address]
    }

**Comment by sysadmin1139** [comment]
I got the same error when I change the record type from `A` to `CNAME`. That state-change seemed to trigger it.

**Comment by mitchellh** [comment]
Hey there. It has been a long time since there has been activity on this issue (our fault, sorry!), and the last known repro was against a very old version of Terraform. It is possible this issue still exists but we've addressed dozens of issues with the same type of error message in the past year. Could you please try again on the latest version and let us know if it doesn't work? The easiest way would be to simply open a new issue. Thanks!
