### ISSUE TITLE
[feature request] Provide ability to programmatically determine if changes need to be/were applied

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#4549]
Right now when you run `terraform plan`, so long as the plan execution succeeds, it will return a `0` respond code. This is of course appropriate as `terraform` worked, but it unfortunately doesn't provide a non-human output option for whether or not changes are necessary. We are forced to parse the output looking at the bottom for the # of resources created, changed or destroyed. The same is true for `terraform apply`. We would like to be able to run one or both of these commands on a regular basis to keep our infrastructure up-to-date and receive notifications when a resource was modified.

**Comment by apparentlymart** [comment]
A workaround for this would be to use a different filename in the `-out` argument each time you run, and then use the presence of the file as the test.

However, I was actually getting ready to suggest that Terraform should always produce a plan file on successful plan, even if it's empty. My rationale was that several times I've absent-mindedly run `terraform apply` after producing an empty plan and had it try to re-apply whatever was in the stale plan file I already had on disk.

There is another issue on here somewhere (Which I couldn't find in a quick search, sadly) about making the plan files JSON so that they can potentially be inspected by other tools so that e.g. the plan can be automatically checked for some "should never happen" cases and rejected, rather than relying on humans to do this.

Not sure what the best path is here, but I certainly agree that the current behavior is non-ideal for a number of reasons.

**Comment by phinze** [comment]
We do have this feature on `terraform plan` to determine whether changes are necessary:

https://www.terraform.io/docs/commands/plan.html#_detailed_exitcode

Does that address your use case, @mtougeron?

**Comment by mtougeron** [comment]
Okay, now I feel foolish for missing that in the docs. :( Thanks!

**Comment by tjlee0909** [comment]
Hi, I'd like to re-open this conversation about having machine-parseable output for 'terraform plan'.

We are implementing our own simple auto-scaling solution on top of Terraform for our non-AWS nodes we have. As a part of monitoring, we are planning on outputting metrics to wavefront on the volume of adjustments we are making to the cluster during peak and off hours.

We also want to use this monitoring to check on some more simple things, such as how often we have to bring up dead/tainted nodes (we plan on running 'terraform plan'/'terraform apply' on a cron to keep our various clusters sized correctly).

While I recognize there are workarounds and alternative options to all of the things I listed, I'd love to have this feature to make our existing solutions easier.

**Comment by afeld** [comment]
Thoughts about having an equivalent flag for `terraform apply`?

**Comment by quixand** [comment]
This would be a really useful feature. At the moment we have to read through heaps of stdout text to see changes when what we really need is a programatic output that we can post-process. I'm surprised this is not a default feature, anyone working at scale in an enterprise environment needs automation features and interoperability. 

Personally I would like to see the number of changes and the modules that are changing so that I can enrich the UI of whatever build agent I'm using.

**Comment by apparentlymart** [comment]
Hi all,

The issue to follow for machine-readable plan output is #3353.
