### ISSUE TITLE
aws_lambda_function doesn't support a python runtime

### ISSUE THREAD

**Issue by pearcec** [hashicorp/terraform#4570]
* aws_lambda_function.functionname: Error creating Lambda function: ValidationException: 1 validation error detected: Value 'Python 2.7' at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [nodejs]

```code
resource "aws_lambda_function" "rdsSnapshotRegionalCopy" {
    filename = "rdsSnapshotRegionalCopy.zip"
    function_name = "rdsSnapshotRegionalCopy"
    role = "${aws_iam_role.lambda_role_event.arn}"
    handler = "exports.test"
    timeout = 30
    runtime = "Python 2.7"
}

**Comment by phinze** [comment]
Hi @pearcec - that's an error coming back from the AWS API. I wonder if all runtimes are not available via the API yet? Or perhaps all runtimes are not available in all regions?

I'd recommend checking in with AWS support - we'd love to know what you find out!

**Comment by thebeefcake** [comment]
How did you go with this one @pearcec ? I am running into the same error.

**Comment by yxd-hde** [comment]
It should be `runtime="python2.7"` instead of `runtime = "Python 2.7"`

**Comment by apparentlymart** [comment]
I've retagged this as "documentation" since it seems to be working as expected but the expectations are not clear in the docs. @pearcec did something in the Terraform docs or examples lead you to think that "Python 2.7" was a valid value here, or were you just trying the string shown in the AWS UI?

It looks like the docs link to the AWS API reference for the list of valid values, so I'm not sure there's much more we can do here, though perhaps we could put a non-default `runtime` value in the example to make it more obvious that the UI display values are not what is used here.

**Comment by jantman** [comment]
I'd call this fixed personally... the TF docs have a clear link to https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestBody for runtimes, which specifies valid values of ``nodejs | nodejs4.3 | java8 | python2.7``

**Comment by apparentlymart** [comment]
Thanks for the reminder, @jantman. I made a small tweak to link to [the Runtime field definition directly](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime), in the hope that it's easier for people to quickly see the valid values.
