### ISSUE TITLE
timeout value from ENV variables for fetching IAM credentials over ec2 metadata

### ISSUE THREAD

**Issue by psihodelik** [hashicorp/terraform#4653]
I am experimenting with using tunneled EC2 metadata API 
(local EC2 endpoint ssh-tunneled to ec2 ).

Since it takes some time until connection is established terraform will set useIAM to False 
and will not query EC2 metadata API.

Code in question is here:

```
// We only look in the EC2 metadata API if we can connect
// to the metadata service within a reasonable amount of time
metadataURL := os.Getenv("AWS_METADATA_URL")
if metadataURL == "" {
    metadataURL = "http://169.254.169.254:80/latest"
}
c := http.Client{
    Timeout: 100 * time.Millisecond,
}
```

If I could set environment variable, something like TF_EC2_TIMEOUT=5000
and if terraform would use that value instead 100 all would work.

Right now expected timeout is just too short.

Any chance to implement this feature ? :)

**Comment by conorgil** [comment]
@psihodelik I am having the same issue and I am typing out my details to contribute to this issue in another comment. However, I recommend updating the title of this issue to something more directly related. Your suggestion of adding an env var is an interesting one, but is not related to the underlying bug. I would have found the issue easier to locate if it were titled something like `Terraform timeout loading IAM credentials via AWS EC2 metadata API` or something like that. Just my 2 cents.

**Comment by conorgil** [comment]
Also, the section of the code which contains the timeout referenced in the OP description is [here](https://github.com/hashicorp/terraform/blob/ad57b445e91e2ee4141b284477c1b9eb4b11b820/builtin/providers/aws/auth_helpers.go#L94).

**Comment by conorgil** [comment]
I am encountering the same issue as the OP. My EC2 instances are loading creds from an IAM profile and the initial request to the AWS EC2 metadata API is taking 5+ seconds to complete. I have been using IAM profiles for well over a year without issue and I recently updated to terraform `v0.7.7` when I encountered the timeout issue.

To reproduce, I launch a fresh `m3.medium` EC2 instance on `dedicated` tenancy and run the following:

```
:~$ TF_LOG=DEBUG AWS_DEFAULT_REGION=us-east-1 terraform remote config -backend=S3 -backend-config bucket=my_bucket -backend-config key=my_key -backend-config encrypt=true
2016/10/26 20:42:34 [INFO] Terraform version: 0.7.7  fa6a83ebdc323f2b415779786e102e69ddbf9a48
2016/10/26 20:42:34 [INFO] CLI args: []string{"/usr/local/bin/terraform", "remote", "config", "-backend=S3", "-backend-config", "bucket=my_bucket", "-backend-config", "key=my_key", "-backend-config", "encrypt=true"}
2016/10/26 20:42:34 [DEBUG] Detected home directory from env var: /home/someone
2016/10/26 20:42:34 [DEBUG] Detected home directory from env var: /home/someone
2016/10/26 20:42:34 [DEBUG] Attempting to open CLI config file: /home/someone/.terraformrc
2016/10/26 20:42:34 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/10/26 20:42:34 [DEBUG] Detected home directory from env var: /home/someone
2016/10/26 20:42:34 [WARN] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
1 error(s) occurred:

* No valid credential sources found for AWS S3 remote.
Please see https://www.terraform.io/docs/state/remote/s3.html for more information on
providing credentials for the AWS S3 remote

If the error message above mentions requiring or modifying configuration
options, these are set using the `-backend-config` flag. Example:
-backend-config="name=foo" to set the `name` configuration
2016/10/26 20:42:34 [DEBUG] plugin: waiting for all plugin processes to complete...
```

If I rerun the command, it works as expected. This is a huge problem for my automated scripts and implies some type of timing issue.

If I launch a fresh EC2 instance again and have the first command I run be directly to the AWS EC2 metadata API, we can see that it takes over 5 seconds:

```
$ time curl http://169.254.169.254/latest/meta-data/instance-id
i-b2dd9e2b
real    0m5.704s
user    0m0.016s
sys    0m0.008s
$ time curl http://169.254.169.254/latest/meta-data/instance-id
i-b2dd9e2b
real    0m0.074s
user    0m0.009s
sys    0m0.025s
```

Now, I know that this request *should* be very fast and if it were indeed as fast as it should be, then `terraform` would not have any issues. Unfortunately, I am getting this error on all of my EC2 instances and I'm blocked right now. I would love a work around in which I could conditionally change the terraform timeout value so that I could increase it to get unblocked.
