### ISSUE TITLE
"terraform shell" to easily SSH/WinRM into a deployed machine

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#4665]
Terraform has enough information in the configuration and state to be able to log into any EC2 instance or other server that it runs provisioners on.

As a helper for debugging/management, it would be nice to exploit this information for getting into login shells on such servers:

```
$ terraform shell aws_instance.main
```

This would:
- Load the config as normal
- Find the referenced resource and instantiate it enough to get its connection info
- Use either `ssh` or `winrm` (using the same logic as used to decide inside the `file` and `remote-exec` provisioners) to run a login shell on the remote machine using the same credentials that Terraform would've used to execute commands or copy files.

This would of course not be useful in _all_ cases. For example, when an Auto-Scaling Group Terraform does not have connection info and this would need to be obtained from elsewhere. I expect this would be primarily useful in cases where Terraform provisioners are being used, as a way to log in to a host and inspect/debug the provisioner results just after instance provisioning without having to manually look up the connection information.

**Comment by teamterraform** [comment]
As part of some general issue review, we're going to close this one out for now since there are no plans on the horizon to implement it and in any case it's not really compatible with emergent practices of using short-lived credentials to access hosts, with disabling remote admin access altogether on hosts and treating them as appliances, etc.

While this doesn't mean that such a feature can never be implemented, it's unlikely that this would rise to the top of the priority list any time soon, and current trends suggest that a feature like this will become less important over time.
