### ISSUE TITLE
important changes from Amazon

### ISSUE THREAD

**Issue by opokhvalit** [hashicorp/terraform#4675]
I've got a message from Amazon today. IMO AWS provider need to be reviewed and changed

Notifications x
We're transitioning instance IDs and reservation IDs to a longer format

AWS is transitioning instance IDs and reservation IDs to a longer format. The old format is a resource identifier followed by an 8-character string, and the new format is a resource identifier followed by a 17-character string. You have until December 2016 to opt in to the longer format.

If you do not take any action, you will be opted in automatically on December 2016, when all new instance IDs and Reservation IDs will be created with the longer format. Until the deadline, you can opt in and out of the new format as needed. Only newly created resources receive longer IDs; existing resources are unaffected.

Manage your transition to longer instance IDs and reservation IDs with Resource ID length management, and read more about the new format.*

**Comment by catsby** [comment]
Hey @opokhvalit thanks for opening this issue. We heard about the longer IDs a while back and did do a quick scan for any impact it may have on Terraform and came to the conclusion that it would not affect us. 

Now that longer IDs are available, I took them for a spin. I first spun up some instances with the short form, and then opt-ed in. I was able to spin up more resources with the long instance id and manage them all with no noticeable difference, so I think we're good here.

If you have found a specific area you feel we should re-examine please let us know! Otherwise I'm going to close this for now, as I don't believe we're affected. Thank you!
