### ISSUE TITLE
Cloudtrail - Can't set "Apply trail to all regions" to yes in terraform

### ISSUE THREAD

**Issue by jmelfi** [hashicorp/terraform#4723]
We've been using terraform for some time to configure our AWS infrastructure and have been liking it.  

When configuring Cloudtrail Trails, it should be possible to change the trail from the default (only apply to the region that it is created in) to applying to all AWS envs.  This is helpful since we have one global policy that gets analyzed in batch.

Currently changing this manually is not an issue, as terraform does not find that there is a change in the state.

**Comment by radeksimko** [comment]
Hi @jmelfi 
I actually wanted to add support for MultiRegion into `aws_cloudtrail` back in December. Specifically on the 18th.

The reason it has not reached Terraform codebase yet is because there was a known bug in the CloudTrail API.

It was impossible to disable multi-region support & global service events both at the same time (in one API call). The error coming out of such API call was

> A client error (InvalidParameterCombinationException) occurred when calling the UpdateTrail operation: Multi-Region trail must include global service events.

I have reached out to AWS on the 18th and reported this. The response I received back follows:

> Hello Radek,
> I just got feedback from cloudtrail team and they have confirmed that this is a bug in AWS CLI. This issue will be fixed in upcoming release.
> Thank you for helping us in identifying this issue.

I will try and test the API again soon to see if this bug has been fixed. If it was, then there's nothing preventing us from implementing it. :wink:

**Comment by radeksimko** [comment]
I just quickly reran a few commands from that mentioned support ticket with AWS and it seems the bug was fixed. :smile:

**Comment by jmelfi** [comment]
@radeksimko thanks for the quick reply here!  It would be awesome for this to get added in.  Looking forward to it!

**Comment by brentaustin** [comment]
+1

**Comment by radeksimko** [comment]
Recently merged https://github.com/hashicorp/terraform/pull/4939 implemented this option.

**Comment by jmelfi** [comment]
@radeksimko thanks for the update on this merge and fix.  I'll be looking at this today or tomorrow.
