### ISSUE TITLE
Allowing count in schema.Resource attribute types

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#4726]
Say I want to do this:

```
resource "aws_elb" "elb {
  ...
  listener {
    count = "${length(split(",", var.service_ports))}"
    instance_port = "${element(split(",", var.service_ports), count.index)}"
    instance_protocol = "http"
    lb_port = "${element(split(",", var.service_ports), count.index)}"
    lb_protocol = "http"
  }
  ...
}
```

I get right now:

```
aws_elb.elb: listener.0: invalid or unknown key: count
```

Should this work? Would be nice if it did!

**Comment by radeksimko** [comment]
Hi @vancluever ,
I think the preferred approach I've seen elsewhere is to have a separate resource, in this case it would be `aws_elb_listener` or something along those lines. You would be then able to use `count` parameter there.

We use this pattern in [`aws_security_group`](https://www.terraform.io/docs/providers/aws/r/security_group.html) & [`aws_security_group_rule`](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html).

I've been actually thinking of creating such resource a while back, but the problem with ELBs generally is that AWS requires at least 1 listener for each ELB, therefore it is impossible to create ELB without any listeners.

This AWS limitation makes implementing such resource a bit more difficult as we'd have to make some decisions about which listener is actually managed where in order to detect outside changes (listeners added/removed outside of Terraform).

I'm happy to add such resource when/if Amazon decides to remove this limitation, but until then, I don't think there's much we can do.

**Comment by jen20** [comment]
Hi @vancluever! Currently this isn't supported internally by Terraform - as @radeksimko says you can only apply a count to a top level resource, and the ELB doesn't really suit having the listeners split out into their own resource. This would probably need core changes to support in the general case - we are tracking that change here: #2275. If you're interested in following progress there, please follow that issue - to keep the discussion in one place, I'll close this one for now. Thanks for raising it though - this is definitely a valid use case we need to look at supporting!

**Comment by vancluever** [comment]
Thanks for the response guys!

**Comment by jsalva** [comment]
+1

**Comment by rcsavage** [comment]
AWS Supports creating ELBs without listeners now.

**Comment by radeksimko** [comment]
@rcsavage can you provide more details? I don't think they do - if you try creating ELB w/out listeners you get the following error:

> ValidationError: Listeners cannot be empty
>	status code: 400, request id: 3f97af33-be61-11e7-84a9-d987020ab444
