### ISSUE TITLE
Creating dynamic amount of Route53 Records

### ISSUE THREAD

**Issue by jasonf20** [hashicorp/terraform#4731]
I would like to be able to use Route53 health checks for my DNS records. For this to work (as far as I understand it) I need seperate DNS records for each ip I would like to have a health check for (otherwise one failing will cause the whole record to "fail").

The number of servers is configurable so currently I create the DNS record like so:

```
resource "aws_route53_record" "myserver" {
  zone_id = "${var.zone_id}"
  name = "myserver${var.delimiter}${var.domain_suffix}"
  set_identifier = "${var.set_identifier}"

  type = "A"
  ttl = "${var.ttl}"
  weight = 1

  records = ["${split(", ",var.instance_public_ips)}"]
}
```

the `var.instance_public_ips` are all the ips of my servers. I would like to have a health check for each of these ips and a matching record for each of these.

Is this possible currently? If not what could be done for this to work?

**Comment by mitchellh** [comment]
I'm so sorry we didn't respond, but issues aren't the best place for general questions. Please ask our community resources such as the mailing list or Gitter. Its been so long I'm sure by now you've either done this or probably just left the project because of it!

To answer your question: you can probably use `count ` and `${count.index}` on a resource in order to mimic looping behavior.
