### ISSUE TITLE
Magic strings for aws_instance.private_ip

### ISSUE THREAD

**Issue by lusis** [hashicorp/terraform#4800]
As terraform has no conditionals (and honestly I think that's fine even if it does complicate flows a bit), It would be nice if various resources supported magic strings that triggered a default behavior.

Currently if I want to have the flexibility to have a module for provisioning an instance, I have to create two modules if I want static for one and dhcp for another in a VPC.

I propose that `private_ip` supports a string such as `DHCP`. This would allow us to write modules that support conditional scenarios. `private_ip` can still remain optional for backwards compatibility and end-users get the ability to make modules just a bit more reusable.

The biggest gotchas I see are ensuring that because private_ip is a an attribute, using `DHCP` as the value should NOT constantly trigger a change (which in this case would be a risk as there is a value there that has to be checked.

**Comment by whitmo** [comment]
sounds dope. +1

**Comment by apparentlymart** [comment]
Hi @lusis! Thanks for this feature request and sorry we let it sit here idle for so long.

In the mean time Terraform has got basic support for conditional expressions, so it should work now to write something like this:

```
    private_ip = "${var.use_dhcp ? "" : "10.1.2.1"}"
```

The conditional support still has quite a few limitations but we are likely to improve on it in future as more use-cases emerge, so I'm going to close this specific issue since general conditional support is the most likely way we would attempt to solve the problem you've expressed here.

**Comment by magec** [comment]
This enforces a new resource next time a plan is run, private_ip set to "" only works at creation time.

**Comment by rlees85** [comment]
Any update on this? The proposed workaround does not work.
