### ISSUE TITLE
Changing security group rule from CIDR to sec group causes diff mismatch.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#4803]
If I do an initial `apply` with an `aws_security_group_rule` that uses `cidr_blocks`, then change that rule to use `source_security_group_id`, Terraform returns the error `diffs didn't match during apply. This is a bug with Terraform and should be reported.`. Interestingly, if I do the reverse, start with a `source_security_group_id` then change it to `cidr_blocks`, it works fine.

This is with Terraform v0.6.9. 

Full config and log are at https://gist.github.com/clstokes/af31ed27ed33fa651e71.

```
tf-bug $ terraform apply
aws_security_group.other: Refreshing state... (ID: sg-6ac78813)
aws_security_group.default_egress: Refreshing state... (ID: sg-6dc78814)
aws_security_group_rule.default_egress: Refreshing state... (ID: sgrule-821154362)
aws_security_group_rule.default_egress: Destroying...
aws_security_group_rule.default_egress: Destruction complete
Error applying plan:

1 error(s) occurred:

* aws_security_group_rule.default_egress: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

I checked other open diff mismatch bugs, but this seems to be a distinct case from the others.

**Comment by mitchellh** [comment]
Hey there. It has been a long time since there has been activity on this issue (our fault, sorry!), and the last known repro was against a very old version of Terraform. It is possible this issue still exists but we've addressed dozens of issues with the same type of error message in the past year. Could you please try again on the latest version and let us know if it doesn't work? The easiest way would be to simply open a new issue. Thanks!

**Comment by clstokes** [comment]
Confirmed this error doesn't occur anymore with Terraform v0.7.11.
