### ISSUE TITLE
Interpolation in 'provider =' value for aws_vpc is broken

### ISSUE THREAD

**Issue by pll** [hashicorp/terraform#4845]
I would expect this to work:

```
provider "aws" {
  alias = "0"
  region = "us-east-1"
}

provider "aws" {
  alias = "1"
  region = "us-west-1"
}

provider "aws" {
  alias = "2"
  region = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  count = 3
  provider = "aws.${count.index}"
  cidr_block = "10.${count.index}.0.0/16"
}
```

Instead, I get:

```
$ terraform plan 
provider.aws.${lookup(var.regions, count.index)}.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: 
```

Even changing it to something like this:

```
variable "count" {
  default = "1"
}

variable "regions" {
  default = {
     "0" = "east"
     "1" = "west"
     "2" = "eu"
}
provider "aws" {
  alias = "east"
  region = "us-east-1"
}

provider "aws" {
  alias = "west"
  region = "us-west-1"
}

provider "aws" {
  alias = "eu"
  region = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  count = 3
  provider = "aws.${lookup(var.regions, count.index)}"
  cidr_block = "10.${count.index}.0.0/16"
}
```

fails to work in the same way:

```
$ terraform plan 
provider.aws.${lookup(var.regions, count.index)}.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: 

```

**Comment by tobyclemson** [comment]
I also ran into this issue. Is there any workaround?

**Comment by Aitem** [comment]
+1  Same problem

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

This seems to be covering the same use-case as #3656, so I'm going to close this out just to consolidate the discussion.

Terraform generally doesn't allow interpolation in the so-called "meta-arguments" because they need to be evaluated during Terraform's graph-building step (in a sense, the "compile" step of the Terraform language) while expressions cannot be evaluated until the graph _walk_ (the "run" step). This is similar to the idea that in many of programming languages you can't use variables in the names of types and functions, because they are something dealt with at compile time rather than at runtime.

However, we would still like to do something about the use-case of choosing a provider, so although it's unlikely to be solved by permitting arbitrary interpolation of provider addresses the issue #3656 is intended to represent the general use-case, with a design still to be determined.
