### ISSUE TITLE
aws_db_security_group > unavailable resource (because of API version ?)

### ISSUE THREAD

**Issue by frntn** [hashicorp/terraform#486]
You cannot create a `aws_db_security_group` resource using terraform.
The plan is OK but the apply ouputs the following :
```
aws_db_security_group.ha-rds: Creating...
  description:    "" => "RDS security group"
  ingress.#:      "" => "1"
  ingress.0.cidr: "" => "10.34.128.0/17"
  name:           "" => "securitygrp-ha-rds"

aws_db_security_group.ha-rds: Error: 1 error(s) occurred:

* Error authorizing security group ingress: InvalidParameterValue: VPC DB Security Groups cannot be modified with this API version.  Please use an API version between 2012-01-15 and 2012-10-31 to modify this group.
```
This is an optionnal argument for `aws_db_instance` but it may be considered as an important issue because we are not able to create the resource type at all.

--
version: terraform v0.3.0
platform: linux (debian wheezy)

**Comment by radeksimko** [comment]
Two acceptance tests also fail due to this issue when running against account that does not have EC2-classic (all accounts created after Dec 2013?):

```
=== RUN TestAccAWSDBInstance
--- FAIL: TestAccAWSDBInstance (6.17s)
	testing.go:121: Step 0 error: Error applying: 1 error(s) occurred:

		* 1 error(s) occurred:

		* Error authorizing security group ingress: InvalidParameterValue: VPC DB Security Groups cannot be modified with this API version.  Please use an API version between 2012-01-15 and 2012-10-31 to modify this group.
=== RUN TestAccAWSDBSecurityGroup
--- FAIL: TestAccAWSDBSecurityGroup (4.65s)
	testing.go:121: Step 0 error: Error applying: 1 error(s) occurred:

		* 1 error(s) occurred:

		* Error authorizing security group ingress: InvalidParameterValue: VPC DB Security Groups cannot be modified with this API version.  Please use an API version between 2012-01-15 and 2012-10-31 to modify this group.
```

So it might be a good idea to start deprecating that resource and more importantly fix the acceptance tests for both environments.
I'm not sure what the right solution should be:
1. Fall back to `aws_security_group` if a particular error comes up during apply stage
2. Somehow try to grab an account creation date somewhere a decide what to do based on that.
3. Make `aws_db_security_group` a simple proxy to `aws_security_group` - I'm not sure how much it differs, I've never used the DB one. It might cause issue to people still using old accounts with EC2-Classic.

**Comment by catsby** [comment]
I have a pull request open (#1043) that updates the DB Instance resource to use github.com/awslabs/aws-sdk-go. It also removes the offending acceptance test mentioned here, and  updates the documentation. 

As @frntn pointed out, DB security groups controls access for DB instance outside of a VPC. Since VPCs are the default now and new accounts *only* have VPC (as opposed to EC2-Classic), DB security groups are being marked as deprecated in the documentation. 

If you're not in a VPC, you can still use them, but most people should be in a VPC now.

If this clears things up for everyone going forward, I'll close this issue. Thanks!

**Comment by catsby** [comment]
#1043 was just merged. If there's no object, I'll close this on Friday
