### ISSUE TITLE
Documentation is misleading / Taint - lifecycle priority; Tainting aws_launch_configuration for ebs changes causes "Cannot delete launch configuration"

### ISSUE THREAD

**Issue by packplusplus** [hashicorp/terraform#4884]
When you have an autoscaling group and you want to be able to update the launch config without any dependence errors, you take the name out of the launch config and add "lifecycle {create_before_destroy = true}" to the launch config (as documented on [aws_launch_configuration](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html)). If you need to update the launch config's EBS settings, terraform does not see changes (also documented on  [aws_launch_configuration](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html).  The docs also say if you want to change the EBS settings, you can taint the launch config to pick up the changes. However, if you taint the launch config then you get a "ResourceInUse: Cannot delete launch configuration..." for the launch config. So it seems that taint takes precedence over a lifecycle directive and everyone has a bad time.

To work around it (now that I'm using encrypted volumes like a good boy), I manually untainted the launch config, and added a "name_prefix" to the launch config (new feature in 0.6.10). TF picked up there was a change and the apply went fine. 

I'm assuming with the encrypted ebs volume now supported on launch configs, others are going to run into this. 

So, I'm not sure what exactly to do here. 
- Can tf start detecting ebs changes as actual changes? 
- Should taint respect the lifecycle directive? 
- Should the docs suggest updating name_prefix instead of taint when you update ebs settings?
- Does 0.7 remove this sort of edge case from popping up?

**Comment by ouroboros8** [comment]
Taint should absolutely respect lifecycle directives IMO; I am having the same problem trying to use terraform to redeploy autoscaling groups as described [here](https://robmorgan.id.au/posts/rolling-deploys-on-aws-using-terraform/); the plan was to have jenkins taint the launch config in order to force a redeployment, but I guess that won't work.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
