### ISSUE TITLE
config: Allow deprecation/warnings for built-in functions

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#4914]
https://github.com/hashicorp/terraform/pull/4899#issuecomment-177129604
I'm pulling this out to track it in a separate issue and to find out if there is any interest in such feature.

The aim is to allow maintainers/developers to mark a specific feature of builtin function or the whole function as deprecated and print warning if user uses the deprecated function or feature of function in the terraform config.

**Comment by teamterraform** [comment]
Although we do not have a specialized feature for reporting warnings for functions specifically, the new diagnostics mechanism introduced for Terraform 0.12 allows for reporting warnings from potentially any codepath, as long as it is plumbed for diagnostics. We don't currently have a specific need for a function to be deprecated, and so we may still have a little such "plumbing" to do when that arises, but we'll close this issue for now since functions are just one possible place that warning messages might be required and the general approach to adding them would now be largely the same regardless of the feature.

(An exception is warnings from providers, which are still very constrained by the existing SDK API and old RPC protocol, but Terraform Core is _ready_ to receive warnings from providers once the SDK is equipped to return them. That's just one part of the general effort to prepare the SDK to use 0.12 features, though.)
