### ISSUE TITLE
Support for volumes in task definitions

### ISSUE THREAD

**Issue by kennyg** [hashicorp/terraform#4916]
I would like to startup a task on each ECS instance for monitoring, following this guide: https://aws.amazon.com/blogs/compute/running-an-amazon-ecs-task-on-every-instance/  
the terraform ecs_task_definition resource supports loading the container definitions. would it be possible to support loading the raw json including the volumes array via the file method?

**Comment by radeksimko** [comment]
Hi @kennyg 
I believe that volumes are supported since the very beginning of `aws_ecs_task_definition` existence.

See docs at https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html#volume

Feel free to reopen the issue if I misunderstood your question or create a new one if `volume` doesn't work as you expected.

**Comment by radeksimko** [comment]
> the terraform ecs_task_definition resource supports loading the container definitions. would it be possible to support loading the raw json including the volumes array via the file method?

This would be tricky, since volume is a separate parameter in the API & SDK, so we'd effectively have to let the user provide the whole thing (`family` included) via JSON. The idea behind supporting JSON was - as you mentioned - to make it easy for users to bring examples or other existing configs over to Terraform, but as it seems, it can make things more difficult.

We're currently in the middle of the same problem in K8S provider. So far it looks like we'll just end up translating JSON into HCL automatically. See the reasons & concerns we expressed there: https://github.com/hashicorp/terraform/pull/3453

The current limitation that already exists for ECS Task Definition is that you cannot use `count` & related interpolation features with containers as these are defined inside the JSON array.

Note that HCL can be transparently translated into JSON (and visa versa), so you could use something like [`jsonnet`](https://github.com/google/jsonnet) to construct the right JSON format for Terraform.
