### ISSUE TITLE
Terraform reporting cycle after adding s3 bucket policy

### ISSUE THREAD

**Issue by aldarund** [hashicorp/terraform#4932]
After adding an s3 policy my terraform build stop working with following error.

```
Initialized blank state with remote state enabled!
Remote state configured and pulled.
Error while asking for variable input:

1 error(s) occurred:

* Cycle: aws_s3_bucket.rent_front_s3, template_file.s3_website_policy
```

Here is the change that caused this:

http://clip2net.com/s/3tIWDee

Is there a workaround for this? How can i make my terraform build in working state.

**Comment by radeksimko** [comment]
I think this is a valid error - Terraform does not know which resource to create first as you're cross referencing between them:

<img width="521" alt="screen shot 2016-02-01 at 22 01 57" src="https://cloud.githubusercontent.com/assets/287584/12731156/adae5974-c92f-11e5-89fe-6e75ea4cdf39.png">

One solution would be to reference the variable name instead of the bucket name. i.e.

```hcl
    vars {
        s3_bucket = "${var.s3_front_bucket_name}"
    }
```

Maybe we could introduce another resource `aws_s3_bucket_policy` and then you could solve this problem cleanly - 1. create the bucket to allow referencing 2. create the template and use the bucket name 3. use the template to attach the policy

**Comment by aldarund** [comment]
Well, i will try. But one point - if i launch same plan on fresh instance, it will work without this error. This error appears only if i added a policy to existing bucket.

**Comment by radeksimko** [comment]
> This error appears only if i added a policy to existing bucket.

I think it makes sense, that's because attaching the policy causes the cross-reference, hence cyclic dependency.

**Comment by mitchellh** [comment]
Closing, answered
