### ISSUE TITLE
GetOk returning exists=false for zero values

### ISSUE THREAD

**Issue by Carles-Figuerola** [hashicorp/terraform#4936]
When a boolean is set to false, the GetOk helper will unset the `exists` return value because it assumes a zero value is an unexpected return value. 
```
resource "resource" "foo" {
    bar = false
}
```
```
val, ok := d.GetOk("bar"); ok {
    log.Printf("%v, %v", val.(bool), ok)
}
```
Will print `false, false`, whereas I would expect it to be `false, true`

I would expect that values of the `int` or `bool` type, would be set by the user to  `0` or `false` as a valid value. Could this behaviour be changed?

**Comment by phinze** [comment]
Hi @Carles-Figuerola - I agree this is a bit confusing. It's due to some history around `GetOk` that I just [typed up over here](https://github.com/hashicorp/terraform/issues/5694#issuecomment-197907334).

We're going to solve this by introducing a proper concept for providers to check whether a given key is set in config or not, and #5694 is going to track that work. So I'll close this issue so we can consolidate our efforts there. Feel free to follow up if you have further questions on this! :+1:

**Comment by Carles-Figuerola** [comment]
Yes, that's exactly it. Thank you very much!
