### ISSUE TITLE
Resource aws_security_group: security_groups and cidr_blocks arguments behaviour changed

### ISSUE THREAD

**Issue by egarbi** [hashicorp/terraform#4972]
I had this resource working fine in my config with version 0.6.9:
```
# Security Group for Kibana
resource "aws_security_group" "kibana" {
  name = "${lookup(var.domain,var.env)}-kibanasg"
  description = "Security Group to allow traffic to Kibana 4"

  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = ["${var.vpn_cidr}"]
  }
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    security_groups = ["${aws_security_group.intel-elb.id}"]
  }
  vpc_id = "${aws_vpc.testing.id}"
}
```
After upgrade terraform was in a loop trying to change that one:
```
~ aws_security_group.kibana
    ingress.#:                                     "1" => "2"
    ingress.1077726638.cidr_blocks.#:              "0" => "0"
    ingress.1077726638.from_port:                  "" => "80"
    ingress.1077726638.protocol:                   "" => "tcp"
    ingress.1077726638.security_groups.#:          "0" => "1"
    ingress.1077726638.security_groups.1533921316: "" => "sg-xxxxxxxx"
    ingress.1077726638.self:                       "" => "0"
    ingress.1077726638.to_port:                    "" => "80"
    ingress.2033728067.cidr_blocks.#:              "0" => "1"
    ingress.2033728067.cidr_blocks.0:              "" => "192.168.240.0/24"
    ingress.2033728067.from_port:                  "" => "80"
    ingress.2033728067.protocol:                   "" => "tcp"
    ingress.2033728067.security_groups.#:          "0" => "0"
    ingress.2033728067.self:                       "" => "0"
    ingress.2033728067.to_port:                    "" => "80"
    ingress.26868539.cidr_blocks.#:                "1" => "0"
    ingress.26868539.cidr_blocks.0:                "192.168.240.0/24" => ""
    ingress.26868539.from_port:                    "80" => "0"
    ingress.26868539.protocol:                     "tcp" => ""
    ingress.26868539.security_groups.#:            "1" => "0"
    ingress.26868539.security_groups.1533921316:   "sg-xxxxxxxx" => ""
    ingress.26868539.self:                         "0" => "0"
    ingress.26868539.to_port:                      "80" => "0"
```
re-writing the file as below, fixed the issue:
```
# Security Group for Kibana
resource "aws_security_group" "kibana" {
  name = "${lookup(var.domain,var.env)}-kibanasg"
  description = "Security Group to allow traffic to Kibana 4"

  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = ["${var.vpn_cidr}"]
    security_groups = ["${aws_security_group.intel-elb.id}"]
  }
  vpc_id = "${aws_vpc.testing.id}"
}
```
but... according to [docs](https://www.terraform.io/docs/providers/aws/r/security_group.html#cidr_blocks) cidr_blocks and security_groups arguments can NOT be used in the same rule.
Has something changed

**Comment by sysadmin1139** [comment]
The docs do seem to be out of date. I'm using the combined syntax in a rule, and it hasn't complained.

**Comment by catsby** [comment]
Hello there – 

Thanks for the report - and sorry for the trouble here! We are indeed tracking an issue with security group rules since v0.6.10 - you can find the main thread here #4872.

I (@catsby) am working on a fix for the issue, which involves a re-working of `resource_security_group`'s internals a bit, but in the meantime your workaround options are:

- consolidate rules by type/port (so you'd merge the two rules in your example into a single ingress block mentioning both `security_groups` and `cidr_blocks`)
- run v0.6.9 or earlier until a fix lands

I apologize for the difficulties. Going forward the plan is to enforce the separation of `cidr_blocks` and `security_groups` as documented, but for now you'd need to consolidate them. I'm sorry for this trouble! I'm working to get this sorted as soon a possible. 

For now, I'm going to close this thread so we can keep things consolidated over in #4872. Feel free to follow up if you have further questions though! :+1:
