### ISSUE TITLE
Issue running chef provisioning on ubuntu trusty instance.

### ISSUE THREAD

**Issue by swade1987** [hashicorp/terraform#4992]
I tried to run the following provisioning on my new AWS ubuntu trusty instance.

 ```
provisioner "chef"  {
        environment = "_default"
        run_list = ["bamboo::default"]
        node_name = "bamboo-server"
        server_url = "example.com"
        validation_client_name = "parliamentary-digital-service-validator"
        validation_key = "${file("parliamentary-digital-service-validator.pem")}"
        ssl_verify_mode = ":verify_none"
        
        connection {
            user = "ubuntu"
            private_key = "${file("../files/XYZ.pem")}"
       }
    }
```

However, I received the following error: https://gist.github.com/swade1987/f4db01a88c8ee762a31d

Anybody got any ideas how to resolve this?

**Comment by svanharmelen** [comment]
The error you are showing is actually a Chef error. So the provisioner executed correctly, but a recipe in your run_list is having a problem. The smelly part is this:

```
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-53.89_amd64.deb  404  Not Found [IP: 91.189.91.15 80]
```

If you manually try that URL in your browser you'll also get that same 404 HTTP error, so that is the thing you need to fix :wink:
