### ISSUE TITLE
Add -C, --chdir flag

### ISSUE THREAD

**Issue by tj** [hashicorp/terraform#5017]
Unless I'm blind there isn't one, but it would be a nice little addition IMO, I know you can `(cd foo/bar/baz && terraform plan)` etc but -C is a little cleaner, though certainly not a top priority with all the other issues!

**Comment by radeksimko** [comment]
:+1: Agreed, I've been thinking about this for quite a while, just didn't get to write it up into an issue. Thanks!

**Comment by apparentlymart** [comment]
I'd actually kinda like for Terraform to never actually rely on the current working directory and always resolve paths relative to the config file they are defined in, but I expect my dream will never come true because it's a bit late in Terraform's life for such a breaking change.

**Comment by mitchellh** [comment]
@apparentlymart It was actually a design decision to _not_ do this. I've done both with Vagrant and then Packer. With Vagrant, everything is relative to wherever the "Vagrantfile" is. With Packer, everything is relative to the pwd. Both have their issues.

With Terraform, we chose being explicit is the best case: use the `${path.FOO}` variables. They are there so that you can make everything relative to the pwd, the file, the module, etc. Whatever you want! So you're actually able to make modules that are completely location independent.

**Comment by apparentlymart** [comment]
Indeed. Using `${path.module}` explicitly works okay to make a position-independent module, it's just frustrating to me that pwd is the default because it's easy to forget to add `${path.module}` and accidentally make a module that only works as top-level but fails when you try to use it as a child module, or try to use it from a different directory. This is a mistake I've seen somewhat frequently, and it causes confusion each time someone in my team encounters it for the first time.

This `-C` flag is interesting because it solves the latter problem -- trying to use a top-level module when pwd isn't the module's directory -- but can't do anything to address the other problem of a child module that accidentally broke its ability to be re-used by referencing a relative path.

Again not actually suggesting that this be changed, since I'm sure lots of folks are depending on the current behavior, but it felt like this feature request was coming from a similar place as I'm coming from: folks don't initially know about the `path.*` interpolations and then get surprised when they find out (one way or another) that they are required.

**Comment by mitchellh** [comment]
I'm not against the `-C` change, there are other reasons it is nice as well (not having to specify a new state path, etc.). I'm just bringing up the `path` vars as the solution we chose for path-independent modules.

**Comment by DavidGamba** [comment]
I am trying to run multiple `terraform plan -detailed-exitcode` in different goroutines, to detect if any of my different stacks has drifted or if there is something that needs to be applied.

I can't `Chdir` in my goroutine because changing dirs applies to all goroutines, I would like to be able to pass the working directory to terraform for it to work from there.
Right now, I have no choice but to do one plan at a time.

**Comment by DavidGamba** [comment]
@apparentlymart Thank you so much, I don't normally shell out to external commands. I think that will do it for me.

**Comment by apparentlymart** [comment]
A new `-chdir` option is now included in the main branch, and is available for some early (non-production!) testing with [Terraform v0.14.0-alpha20200910](https://releases.hashicorp.com/terraform/0.14.0-alpha20200910/). This feature will be included in the forthcoming Terraform v0.14.0 release.

Documentation for it will follow closer to the release, but for now the high-level idea is that you can write `-chdir=DIR` after the `terraform` command but before the subcommand, like this:

```
terraform -chdir=foo/bar/baz plan
```

When you use this option, Terraform will switch to the given directory immediately after it completes the CLI bootstrapping (including reading the CLI config) and before the subcommand begins running. It is almost entirely equivalent to explicitly running `cd foo/bar/baz` first, but with the exception that `path.cwd` will reflect the directory you run the command from, not the overridden directory. If you want the overridden directory then you can use `path.root` to get the path of the root module, as before.
