### ISSUE TITLE
create_before_destroy not effective on aws_instance resource

### ISSUE THREAD

**Issue by levinotik** [hashicorp/terraform#502]
I've mentioned this as part of another issue (https://github.com/hashicorp/terraform/issues/477), but wanted to open an issue for this specifically. I have tried using 

```
lifecycle { 
    create_before_destroy = true 
}
```

in my aws_instance resource and it does not seem to have any effect; the old instances are destroyed prior to creating the new ones.

I'm using a binaries directly from master - v0.3.2.dev (a70eee51bffc300eb91282d7662f9b2134f9cd2f)

**Comment by joescii** [comment]
I _appears_ that this has has been corrected by the release of 0.3.5.  Running without `create_before_destory`:

```
aws_instance.pac2: Destroying...
aws_instance.pac1: Destroying...
aws_instance.pac1: Destruction complete
aws_instance.pac1: Creating...
(...)
aws_instance.pac2: Destruction complete
aws_instance.pac2: Creating...
(...)
aws_instance.pac1: Creation complete
aws_instance.pac2: Creation complete
```

Running with `create_before_destory` on each of the two instances:

```
aws_instance.pac2: Creating...
(...)
aws_instance.pac1: Creating...
(...)
aws_instance.pac1: Creation complete
aws_instance.pac2: Creation complete
aws_instance.pac2: Destroying...
aws_instance.pac1: Destroying...
aws_instance.pac1: Destruction complete
aws_instance.pac2: Destruction complete
```

**Comment by armon** [comment]
Yeah there was a lot of work in fixing this in 0.3.5 and it's heavily tested, so I think it *should* be working fine now. Please confirm if you still see it however @levinotik

**Comment by catsby** [comment]
We believe this issue was resolved in the recent v0.4.0 release. Please try upgrading (the latest at this time os v0.4.2) and let us know if you still run into this. 

Thanks!

**Comment by levinotik** [comment]
Will do, thanks guys.

**Comment by mstuparu** [comment]
I am running into this with 0.5.2 Mac OS X Yosemite 10.10.3. I mark 2 instances as tained and then try to recreate, always destroys them before creating new ones

**Comment by phinze** [comment]
Hi @mstuparu - that's the current expected behavior for `taint`. The "tainted" concept indicates "this resource cannot perform the service required of it" - it's used by Terraform internally for failure scenarios like when provisioners error out. Currently, to trigger the `create_before_destroy` behavior you need to create a diff by changing a field that would cause the resource to be replaced.

That being said, it does seem like we should have a mechanism for manually triggering replacement in a way that respects CBD. I'll file this as a separate issue and link it here.
