### ISSUE TITLE
null_resource trigger - more documentation/examples

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#5047]
Would it be possible to have more doco or a couple of concrete examples for the triggers on null resource please?

https://www.terraform.io/docs/provisioners/null_resource.html

I'm trying to get it to run whenever a specific routing table has a gateway_id instead of a nat_gateway_id:

```
/* Main routing table*/
resource "aws_route_table" "main" {
    vpc_id = "${aws_vpc.main-vpc.id}"
    tags {
    Name = "${var.customer_prefix}-main-routetable"
    Description = "${var.aws_label}"
    }     

    # Route all non VPC traffic through the NAT
    route {
        cidr_block = "0.0.0.0/0"
        gateway_id = "${aws_internet_gateway.internet_gw.id}"
    } 
}
```

This is done because I need the script to attach the internet gateway initially for WinRM provisioning, and then my last step is a "hardening" script using Amazon tools to alter the route table as below, the command works, I just can't work out how to "trigger" it to create/update the null resource either everytime apply runs or if there is a gateway instead of a nat_gateway attached:

`"AWS_ACCESS_KEY_ID=${var.access_key} AWS_SECRET_ACCESS_KEY=${var.secret_key} aws ec2  replace-route --region ${var.aws_region} --route-table-id ${aws_route_table.main.id} --destination-cidr-block \"0.0.0.0/0\" --nat-gateway-id ${aws_nat_gateway.nat_gw.id}"`

**Comment by apparentlymart** [comment]
The `null_resource` triggers don't directly support conditional operations, so assuming I'm understanding your use-case correctly I think you'd need to combine `null_resource` with a wrapper script that evaluates the conditional.

However, your use-case is complicated by the fact that Terraform's interpolation syntax doesn't support very well retrieving items from a set, like the set of routes; there isn't really a good way to express "interpolate the `gateway_id` from the route whose `cidr_block` is `0.0.0.0/0`".

A further problem is that if you change the route table outside of Terraform's view then on the next run Terraform will want to change it back again.

So with all of this said, I think the most practical way to achieve your goal would be to describe in the Terraform config the *final* state, where the default route is to the NAT gateway, and then use provisioner steps to temporarily adjust the routes:

```js
resource "aws_route_table" "main" {
    vpc_id = "${aws_vpc.main-vpc.id}"
    tags {
    Name = "${var.customer_prefix}-main-routetable"
    Description = "${var.aws_label}"
    }     

    # Route all non VPC traffic through the NAT
    route {
        cidr_block = "0.0.0.0/0"
        gateway_id = "${aws_internet_gateway.internet_gw.id}"
    } 
}

resource "some_other" "resource" {
    // ... resource attributes

    // Temporarily route directly to the internet gateway during provisioning
    provisioner "local-exec" {
        command = "aws ec2 replace-route --region ${var.aws_region} --route-table-id ${aws_route_table.main.id} --destination-cidr-block \"0.0.0.0/0\" --nat-gateway-id ${aws_internet_gateway.internet_gw.id}"
    }

    provisioner "..." {
        // whatever actual provisioning step you needed to do
    }

    // Now put back the NAT gateway
    provisioner "local-exec" {
        command = "aws ec2 replace-route --region ${var.aws_region} --route-table-id ${aws_route_table.main.id} --destination-cidr-block \"0.0.0.0/0\" --nat-gateway-id ${aws_nat_gateway.nat_gw.id}"
    }
}
```

This is not ideal either, since it requires care to ensure that two different resources don't get provisioned at once and cause a race condition on the route table changes. But a key advantage of this formulation is that if something goes wrong and the route table is left in an inconsistent state, a subsequent Terraform run will converge it back to the "hardened" state, rather than reverting to the "unhardened" state.

I'd also consider whether there's some more specific route that you could create that could be permanently directed at the internet gateway. I don't know what about WinRM provisioning requires Internet access, but if there's some particular set of hosts that your instances are interacting with then perhaps you could install individual routes for those target hosts, leaving the default route permanently directed at the NAT gateway.

Sorry I don't have a more direct answer to your question, but I hope some of this is helpful to you.

**Comment by davehodgson** [comment]
Thanks Martin, I was just about to start working through the idea when I re-read you question: 

> I don't know what about WinRM provisioning requires Internet access

Your question is exactly the challenge I needed, you are quite right, they dont! What they do need is a public IP that is accessible and the NAT gateway removes that. I had previously tested it by manually switching the route table but all I was doing was removing the NAT, the IGW just happened to be the first route table option on the UI, but it would work equally well with the default route table.

They don't need the internet gateway directly for WinRM, but once they go behind the NAT gateway they become invisible from outside the VPC effectively so WinRM can't get to them.

Therefore if I make the association to the NAT gateway execute as the final steps by using depends_on then effectively I leave the WinRM hole open all through the provisioning and then close it by associating the NAT route table.

Also handy because I can put the remote-exec calls to close the security group rules allowing winRM to the non NAT instances in at that point as well and just taint the NAT gateway effectively using it as the "hardening" step

Thanks again for spending the time to think about it

Perhaps a feature suggestion could be to support conditional triggers on the null resource, if I could for example say trigger when 1 = 2 then it would just update the null resource every time, not sure if there is another use case for this or not though

**Comment by apparentlymart** [comment]
Oh now I read your response I think I understand your situation: you're trying to provision a host in a remote VPC where Terraform is running "outside of the VPC" and thus can't address the private IP addresses of the instances.

In which case, I know this problem well/ In my environment we have this problem not only with SSH but also with MySQL, Rundeck, InfluxDB, Grafana, Consul and more! At first, when the problem was only SSH, we'd considered somehow temporarily exposing port 22 to the world during provisioning, but once the problem became generally accessing various private infrastructure services it became clear that it wasn't a scalable/tenable solution.

FWIW, the workaround I landed on was to run Terraform on a host inside the VPC. These days we're orchestrating this with other tools to run Terraform via a web UI, but at first the flow was to just SSH into a special admin host and manually run Terraform there. That way our primary concern is managing access to that admin host, and then applying the right set of constraints on that admin host so that it's able to do access the appropriate network resources to complete the Terraform run.

A key part of the setup is that we separate our low-level network configuration setup into an entirely separate Terraform config from the rest. The network configuration specifies the VPC but no instances except for that admin host. Once that's applied (which requires some manual steps outside of Terraform, that are "automated" via a separate script because it's an infrequent process and Terraform's not well-suited) we then complete the rest of the setup by running Terraform on the admin host, where then everything proceeds as expected.

I'm not sure how well this solution maps on to a (presumed?) Windows infrastructure but maybe there's some adaptation of it that can work for you.

**Comment by mitchellh** [comment]
Closing since its answered

**Comment by kfries-em** [comment]
`
