### ISSUE TITLE
[aws] mixing security_groups, cidr_blocks and self in security groups

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/terraform#5061]
So, while trying to debug an issue I've discovered this is valid syntax.

```
provider "aws" {
  region = "eu-west-1"
}

resource "aws_security_group" "test-group" {
  name = "mismatched-sg-test"

  ingress {
    from_port = 1234
    to_port = 1234
    protocol = "tcp"
    security_groups = ["${aws_security_group.test-group-elb.id}"]
    cidr_blocks = ["10.25.0.0/16"]
    self = true
  }
}

resource "aws_security_group" "test-group-elb" {
  name = "mismatched-sg-test-elb"
}
```

Is this intentional? It's previously not been possible to mix these together. If it is, awesome, if not, it is actually valid in 0.6.11, thought someone should know.

**Comment by alexlafreniere** [comment]
Also confused about how security group syntax changed in v0.6.11. The docs state specifically that cidr_blocks cannot be used with security_groups, but it works great for me on v0.6.11. Not only does combining security_groups and cidr_blocks in a single rule work, but breaking security groups and cidr blocks into their own otherwise identical rules causes Terraform to want to modify that security group on every apply. Very confusing that the docs say one thing but the only way to prevent your plans/applies from filling up with "fake" changes to security groups is to do the opposite.

**Comment by tphummel** [comment]
I'm seeing this behavior too on both v0.6.11 and now in v0.6.12. I can confirm a single `ingress` block with both `security_groups` and `cidr_blocks` arguments works. as well as two separate `ingress` blocks to separate the `security_groups` and `cidr_blocks` arguments also works. 

More problematic is that I see the case described by @alexlafreniere where my plan shows the security group needs modification on every `plan` run. on `apply` it reports the security group was modified successfully. Then on an immediate `plan` again, it shows the same modifications are still needed. I haven't been able to successfully fix this by doing state surgery, which is how i normally work around stuff like this. any ideas would be welcome. 

i saw a thread on the mailing list that seemed like it could be related but tough to say for sure: https://groups.google.com/forum/#!searchin/terraform-tool/security$20group$20changes/terraform-tool/fx4R9Ts4MWE/h9AHJKlABgAJ

**Comment by mitchellh** [comment]
This should be fixed now
