### ISSUE TITLE
crash: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by darrensony** [hashicorp/terraform#5128]
Terraform 0.6.9, Mac OSX. Also occurs on Terraform 0.6.11. 

Attempting to use a list as a list.

[tf-crash-069.txt](https://github.com/hashicorp/terraform/files/129410/tf-crash.txt)
[tf-crash-0611.txt](https://github.com/hashicorp/terraform/files/129417/tf-crash-0611.txt)

Following example for creating DNS zone and DNS Resource record at https://www.terraform.io/docs/providers/aws/r/route53_zone.html; 

````
## Code from web page
resource "aws_route53_record" "dev-ns" {
    zone_id = "${aws_route53_zone.main.zone_id}"
    name = "dev.example.com"
    type = "NS"
    ttl = "30"
    records = [
        "${aws_route53_zone.dev.name_servers.0}",
        "${aws_route53_zone.dev.name_servers.1}",
        "${aws_route53_zone.dev.name_servers.2}",
        "${aws_route53_zone.dev.name_servers.3}"
    ]
}
````

I thought _**Hey, that records ID is forcing a list context with [] and explicitly listing name servers... why don't I just use the list itself?**_

````
    records = "${aws_route53_zone.dev.name_servers.*}"
````

Boom. Crash.

**Comment by apparentlymart** [comment]
@darrensony sorry that this crashed on you...

The correct syntax for interpolating a list like that is to create a single-element list with the interpolation inside it, like this:

```js
records = ["${aws_route53_zone.dev.name_servers.*}"]
```

However, it's definitely a bug that this was a crash and not a helpful error message.

Unfortunately IIRC Terraform doesn't actually currently support that globbing syntax for list attributes. It's been a while since I tried to do this so I'm a little rusty on the right way to write it but I'd also try this, if the example above doesn't work:

```js
records = ["${aws_route53_zone.dev.name_servers}"]
```

IIRC this is the correct way to write this because `name_servers` is itself already a list, whereas the `*` syntax is used to *produce* a list by selecting a scalar attribute from each of a set of separate resources created using `count`.

**Comment by phinze** [comment]
Hi @darrensony - thanks for the report. I just tied to reproduce this on 0.6.11 and got errors instead of panics.

With config:

```tf
resource "aws_route53_zone" "main" {
  name = "main.example.com"
}
resource "aws_route53_zone" "dev" {
  name = "dev.example.com"
}
resource "aws_route53_record" "dev-ns" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  name    = "dev.example.com"
  type    = "NS"
  ttl     = "30"
  records = "${aws_route53_zone.dev.name_servers.*}"
}
```

I get:

```
Errors:

  * aws_route53_record.dev-ns: records: should be a list
```

And if I wrap the `records` value it in brackets I get:

```
1 error(s) occurred:

* Resource 'aws_route53_zone.dev' does not have attribute 'name_servers.*' for variable 'aws_route53_zone.dev.name_servers.*'
```

Is there something that's missing from my config that might be necessary to reproduce this?

**Comment by darrensony** [comment]
Unfortunately, after the crash and submitting the bug, I re-wrote the code.  I think the only possible difference was that the two zones were in two different files...

Just tried it again, and I'm seeing the same behaviour as @phinze 

(1): ````records = "${aws_route53_zone.dev.name_servers.*}"````
Gives error "records: should be a list" at compile time

(2): ````records = ["${aws_route53_zone.dev.name_servers.*}"]````
Gives "does not have attribute"

I also tried @apparentlymart's second suggestion, and it works
(3): ````records = ["${aws_route53_zone.dev.name_servers}"]````

Since I can no longer reproduce it, and you can't reproduce it, I'll close this bug. Thanks for your time.
