### ISSUE TITLE
ASG and non-ASG managed instances on the same ELB

### ISSUE THREAD

**Issue by j4ybee** [hashicorp/terraform#5132]
I am in a bit of a pickle, needing to have two "core" instances with EIPs on the same load balancer as additional instances managed by an auto scaling group. When I run `terraform plan` after the auto scaling scales out additional instances (and after they were added to the ELB) they are not in the state file and therefore mark for removal.

Of course the reason for this is that the ELB is managed by two different resources: the ASG on one hand and the instance creation outside the ASG on the other. The instance creation resp. instance registration with the ELB outside the ASG overwrites the instances registered by the ASG.

I know that this is the correct/expected behavior (in most cases), but is there a way around this problem with the tools at hand?

**Comment by mitchellh** [comment]
As far as I know there isn't a way to do this currently with TF but I may be wrong since we have so many AWS resources now its hard to know 100%. Try asking in the mailing list or chat room since you'll get better responses there. :) The folks on the issue tracker are generally core folks working on bugs!
