### ISSUE TITLE
provider/aws: Add support for Redshift destination in Firehose resource

### ISSUE THREAD

**Issue by Bowbaq** [hashicorp/terraform#5152]
Since Redshift is now supported, it would be very nice to add support to the Firehose resource. I can start work on this, but I wanted to check if anybody else was working on it first. We've been using a bash script in the meantime and it's ugly...

**Comment by catsby** [comment]
Hey @Bowbaq – I'm unaware of anyone working on this at the moment, we'd be happy to have it! Please be aware of our [contributing guidelines][1], which should explain some of the standards we hope to have for all our pull requests.

Thanks again, and us know if you have any questions along the way!

[1]: https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md

**Comment by dminnear** [comment]
I'm starting to work on this and I have a question. As you can see in the [docs](http://docs.aws.amazon.com/cli/latest/reference/firehose/create-delivery-stream.html), you can either give a redshift configuration or an s3 configuration. Nested inside the redshift configuration is all of the configuration options for s3.

This brings up an interesting problem since right now in `resource_aws_kinesis_firehose_delivery_stream.go` everything in the top level schema is for the s3 configuration. So I'm not sure the best way to resolve this problem.

1. We could add the redshift configuration at the top level as well and make the fields optional. And then check when we have the destination set to redshift that the fields we need are defined. This would keep existing code working while also extending functionality so that we can now create delivery streams for redshift. There are overlap fields however (such as "role_arn") so we would have to give them more specific names.

2. We could create a subschema for redshift destination configuration that allows us to set the additional fields if we set the destination to redshift. This will not break existing code, but it's a bit detached from the nesting of the command line config argument.

3. We could create two subschemas. One for the s3 configuration and one for the redshift configuration. Then the schema best reflects the command line arguments, but this will break existing terraform files.

What do you suggest?

**Comment by catsby** [comment]
Hey @dminnear sorry for the silence here.

Looking over the docs, it's my understanding that you can either have S3, or Redshift for the destination. It's just coincidence that the Redshift requires S3 as an intermediary :)

My thinking is that we go for option 1. Either way, we need S3 information. In the code we should simply check if Redshift information has been specified, and go down that path. 

Make sense? Apologies again for the silence!

**Comment by dminnear** [comment]
I already opened https://github.com/hashicorp/terraform/pull/5304

Feel free to discuss changes on there!

**Comment by jeshuaborges** [comment]
Pinging... Has been a review or there is any conversation or review of #5304? Thanks!

/cc @catsby

**Comment by stack72** [comment]
Fixed by #7375
