### ISSUE TITLE
Core vs Plugin

### ISSUE THREAD

**Issue by imduffy15** [hashicorp/terraform#5186]
Hi All,

What attributes must exist for something to become a core terraform feature? When is it preferred for something to be a plugin rather than a core feature?

For example, the following is very helpful and might be used by many organisations https://github.com/prudhvitella/terraform-provider-infoblox/ should it be brought into the core (assuming original author is OK with it) or should it be maintained as a plugin?

Thanks,

Ian.

**Comment by apparentlymart** [comment]
@imduffy15 in this particular case the plugin was submitted for consideration to be in the main distribution in #4006.

Ultimately we concluded that this one would be better maintained out-of-tree because nobody on the Terraform maintainers team has access to Infoblox devices in order to run pre-release acceptance tests, etc. As @phinze mentioned there, this decision could potentially be reversed if there is demand for such support being in core.

**Comment by imduffy15** [comment]
Perfect! Thank you very much @apparentlymart that is very reasonable and increases the overall quality of the project.

Thank you :)
