### ISSUE TITLE
Namecheap DNS support

### ISSUE THREAD

**Issue by flxfxp** [hashicorp/terraform#520]
https://www.namecheap.com/support/api/intro.aspx

**Comment by LukeHoersten** [comment]
Any progress on this?

**Comment by mitchellh** [comment]
Not yet, would love any contributions though. :)

**Comment by rgl** [comment]
I would like to chip in! What's the best way to contribute? fork terraform and add the provider there? or do it externally?

**Comment by rgl** [comment]
I've took a closer look at the API but I'm afraid this is going to be quite painful to implement in the same vain as the dnsimple provider... :-(

The namecheap API only has a [setHosts](https://www.namecheap.com/support/api/methods/domains-dns/set-hosts.aspx) method that sets the entire set of DNS RRs. There is no way to directly identify each  RR or modify them individually.

So, how should we implement this?

I'm seeing two possibilities:

1. a single `namecheap_dns_hosts` resource with multiple `namecheap_dns_record` child resouces? which, I'm hopping, can be translated into a single call to setHosts.
2. or a complex solution that has multiple top-level `namecheap_dns_record` resources, each identified by its (type,name) (with the complexity that we can have multiple RR for the same (type,name) pair... so somehow this has to be handled) that translates into multiple calls to getHosts/transform/setHosts (atomically).

Thoughts?

**Comment by LukeHoersten** [comment]
Actually it's different but it's not too bad. Sending Namecheap a full DNS hosts snapshot every time removes the complexity of uniquely identifying things on our end and their and (and what happens when those get out of sink).

So really the task is just how best to represent the full DNS records table in Terraform syntax.

I like your solution #2 because it makes it a hell of a lot easier to have a module register all your hosts. Is there any way to defer the getHosts/transform/setHosts until the end so they can all be collected up and run as a single snapshot?

**Comment by HX-Rd** [comment]
Hi.
I have implemented this provider and created a [WIP] pull request.
I'm not really a go developer any comments on the code is appreciated. I haven't really been committing to the open source community so sorry in advance if i messed up the pull request. But enough excuses. 
I'm having some problems vendoring in the dependency, get the error
godep: Package (github.com/hashicorp/terraform/builtin/providers/namecheap)
I tried keeping the implementation in the same fashion as the other DNS providers.
Acceptance tests run fine on my dev build.

**Comment by artburkart** [comment]
Since they're not linked: https://github.com/hashicorp/terraform/pull/5846

**Comment by OranguTech** [comment]
Bumping here as well. Note that the NC API appears to have not been touched since 2014: https://www.namecheap.com/support/api/change-log.aspx

feedback@namecheap.com seems to be most frictionless method to ask for changes. Might be worth it for customers (and Hashi) to start (politely) raising tickets as well?

**Comment by mildwonkey** [comment]
Hi @flxfxp and everyone else who has chimed in on this request! 

Our Provider Development Program is the process by which new providers can be brought into that organization and published into the HashiCorp-maintained plugin repository. This process is primarily aimed at vendors who wish to develop plugins for their own services (in this case, for Namecheap themselves to develop a provider to this service) and we acknowledge that this process is more "heavy" than ideal for a third-party developer, but we are open to discussing bringing in a community-maintained provider if the maintainer(s) are willing to support the provider and to collaborate with the vendor on maintenance if they later wish to join the program themselves.

I did find https://github.com/adamdecaf/terraform-provider-namecheap, referenced in #5846, and perhaps the maintainer of that repository might be interested in onboarding into the HashiCorp-maintained plugin repository. 

Since the provider onboarding process happens outside of the Terraform repository, and so there's no further action we could take here on this, I'm going to close this out.
