### ISSUE TITLE
RFE: new function `ifeq`

### ISSUE THREAD

**Issue by syskill** [hashicorp/terraform#5261]
I have been writing some Terraform modules for our AWS infrastructure and find myself writing a couple particularly awful fragments of code over and over again:

```
replace(replace(var.vpcid, "/.+/", "something for vpc"), "/^$/", "something for classic")
replace(replace(var.vpcid, "/^$/", "something for classic"), "/^vpc-/", "something for vpc")
```

(We're trying to get out of EC2 Classic, please don't judge.)

It would ease my work considerably if there were a function that worked like this:

```
ifeq(var.vpcid, "/./", "something for vpc", "something for classic")
ifeq(var.vpcid, "", "something for classic", "something for vpc")
```

That is, `ifeq` compares its first argument to the second, which may be a regular expression. If they match, the return value is the third argument. If not, the return value is the fourth argument.

How about it? I'd try to implement it myself, but unfortunately I don't know any Go. (Again, please don't judge.)

**Comment by johnt337** [comment]
I don't know if this helps, but I find that you can use tfvars as K/V with the lookup() function.
So you can create keys like this in a dev.tfvars file

```
# deployment configuration
deployment.version         = "1.2"
deployment.environment     = "dev"
deployment.region          = "us-east-1"
deployment.os              = "coreos"
deployment.os_version      = "835.13.0"
deployment.instance_size   = "t2.medium"
...

# ami library by region and version
amis.us-east-1.coreos.835.8.0 = "ami-1a642670"
amis.us-east-1.coreos.835.13.0 = "ami-7f3a0b15"
amis.us-west-2.coreos.835.8.0 = "ami-e0342681"
amis.us-west-2.coreos.835.13.0 = "ami-4f00e32f"
````

And from your deployment.tf

```
...
/* will hold our ami lookups */
variable "amis" {
  default {}
}

/* will hold our incoming deployment options */
variable "deployment" {
  default {}
}

...
image_id = "${lookup(var.amis,format("%s.%s.%s",lookup(var.deployment,"region"),lookup(var.deployment,"os"),lookup(var.deployment,"os_version")))}"
...
```

At runtime just include 

```
--var-file=./dev.tfvars
```

Its equally ugly unfortunately, but i've found that using aws_instance count N or aws_autoscaling_group with a tfvars file reduces the amount you need to write in order to describe a generic cluster configuration.

Using it for elb & instance disk configs works pretty well too.

The real pain is not being to create a first class dynamic variable without it being injected.

I like the use of the regex btw.

**Comment by syskill** [comment]
I am using that technique elsewhere but it doesn't help at all here.

**Comment by syskill** [comment]
That is a neat trick but has nothing to do with my issue.

**Comment by johnt337** [comment]
Sorry I couldn't help.

**Comment by apparentlymart** [comment]
Hi @syskill,

Thanks for the use-case and suggestion! We've been collecting use-cases for conditional logic over in #1604 and this seems like a good new example of a conditional expression rather than a conditional resource.

If I think about a future state where both conditional expressions and conditional resources were supported, I think I'd be tempted to add some boolean operators to the expression language so that the same syntax could be used in both cases.

So for your use-case, you might say something like this:

```js
if(var.vpcid != "", "something for vpc", "something for classic")
```

...and then this same expression syntax could be used as a special attribute on a conditional resource:

```js
resource "foo" "bar" {
    // ...

    only_if = "${var.vpcid != ''}"
}
```

Currently Terraform supports only basic arithmetic operators (`+`, `-`, `*`, `/`) but with some improvements to the parser I expect we could support `!=`, `==`, `<`, etc, and possibly also boolean combinators like `and`, `or`.

However, your proposal is certainly easier to implement in the short term, since the interpolation language is already sophisticated enough to deal with functions. The only funky thing I see is that it looks like your function is more like `ifmatch` than `ifeq`, since the second argument is (if I'm not mistaken) a regexp.

**Comment by syskill** [comment]
Hi @apparentlymart,

`ifmatch` is probably more appropriate. I figured the second argument should be similar to the `replace` function's second argument, which may be either a regexp or a literal string.

I like the idea of boolean operators. An `only_if` meta-attribute sounds useful, but maybe susceptible to overuse, and I think it would impose a large readability cost on real-world configs.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

I'm just looking through some older issues that were using an older labeling scheme and thus weren't found on previous passes through the issues.

Back in Terraform 0.8.0 we added support for a conditional operator and various comparison operators. This means the example in my earlier comment can be written like this:

```hcl
var.vpcid != "" ? "something for vpc" : "something for classic"
```

The initial implementation of that had some limitations, the most important of which was that it still required both result expressions to be resolvable even though only one would be returned. These issues are fixed in master ready for inclusion in the forthcoming v0.12.0 release.

Since I believe that meets the use-case of this issue, I'm going to close this out. Sorry for not catching this at the time when we were preparing the v0.8.0 release.
