### ISSUE TITLE
Terraform unable to create ecs_service if iam_role is set

### ISSUE THREAD

**Issue by egoldschmidt** [hashicorp/terraform#5292]
I've come across an issue in which an ECS service apparently cannot be created if `iam_role` is set. As you can see from this example I've set it to the ARN of the default ECS service user, but I've tried a custom user to no avil. The only thing that appears to resolve the problem is removing the `iam_role` field altogether. Obviously this is a non-starter because we need ELBs, so any ideas would be appreciated.

```
module.vpn_service.aws_ecs_service.vpn: Creating...
  cluster:                                 "" => "arn:aws:ecs:us-west-2:xxx:cluster/vpn"
  desired_count:                           "" => "1"
  iam_role:                                "" => "arn:aws:iam::xxx:role/ecsServiceRole"
  load_balancer.#:                         "" => "2"
  load_balancer.3901468935.container_name: "" => "vpn"
  load_balancer.3901468935.container_port: "" => "943"
  load_balancer.3901468935.elb_name:       "" => "vpn-elb"
  load_balancer.450980314.container_name:  "" => "vpn"
  load_balancer.450980314.container_port:  "" => "443"
  load_balancer.450980314.elb_name:        "" => "vpn-elb"
  name:                                    "" => "vpn"
  task_definition:                         "" => "arn:aws:ecs:us-west-2:xxx:task-definition/vpn:4"
Error applying plan:

1 error(s) occurred:

* aws_ecs_service.vpn: timeout while waiting for state to become '[success]'
```

**Comment by egoldschmidt** [comment]
I should add that I'm seeing this using Atlas running TF 0.6.11

**Comment by egoldschmidt** [comment]
And this is what we get from CloudTrail: 

![image](https://cloud.githubusercontent.com/assets/931480/13273975/4dec6c22-da5c-11e5-98ad-3d8f38095ffd.png)

**Comment by radeksimko** [comment]
Hi @egoldschmidt 
is this intermittent or do you see this error all the time?

Would you mind sharing a minimal repro case with us (i.e. terraform config including at least `aws_ecs_service` & `aws_ecs_task_definition` and the IAM role minus any secrets)?

**Comment by egoldschmidt** [comment]
Thanks for the quick response @radeksimko . After trying to nail down the perfect repro case I believe I found the source of the issue: I had set `lifecycle { create_before_destroy = true }` on the service, task definition, and ELBs. Presumably TF is trying to create another service with the same name? The opaque error from Amazon didn't help (and looking at the raw CloudTrail payloads was no more useful).

This begs the question: is there any way to safely adjust an `aws_ecs_service` without possibly blowing everything away? Sure, most params live in the task definition (which is safe), but it would be nice if simply exposing a new port via an ELB didn't cost you downtime.

**Comment by egoldschmidt** [comment]
Actually, there was at least one other issue: I had multiple `load_balancer` blocks, [which is apparently invalid](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html): `There is a limit of one load balancer per service`. Unfortunately neither AWS nor Terraform gave good feedback in this case, which made tracking down the source very difficult. We might want to consider amending the docs to not imply that multiple `load_balancer` blocks are valid

**Comment by radeksimko** [comment]
> I had set lifecycle { create_before_destroy = true } on the service, task definition, and ELBs. Presumably TF is trying to create another service with the same name?

I've been wondering myself almost since ECS was first released how to do this... in fact I plan to discuss it with our AWS account manager next week. Few ideas I had in mind include dynamic port assignment on the ELB level from ECS agent, ELB 1-to-N port mapping support (none of which are supported by AWS today) or Route53 weighted records. I will see if something useful comes up from the discussion next week and eventually build an example as a TF config to address this. Right now I don't think there is any easy solution for this.

> Sure, most params live in the task definition (which is safe), but it would be nice if simply exposing a new port via an ELB didn't cost you downtime.

Changing ECS svc load balancers is [destructive action on the API level](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html), there isn't much we can do about it.

> I had multiple load_balancer blocks, which is apparently invalid: There is a limit of one load balancer per service. Unfortunately neither AWS nor Terraform gave good feedback in this case, which made tracking down the source very difficult.

That is a good catch! Would you mind submitting this as a separate issue, so we don't lost this suggestion?

**Comment by egoldschmidt** [comment]
Submitted #5336

**Comment by mtougeron** [comment]
We've run into a similar issue as well. We ended up changing the name of the `aws_iam_instance_profile`, `aws_iam_role`, and `aws_iam_role_policy` resources attached to the `aws_ecs_cluster` due to naming conflicts. When running `terraform apply` it would error with the same `timeout while waiting for state to become '[success]'` error message.

When running with `TF_LOG=debug TF_LOG_PATH=tf.log` this message was in the log `2016/02/29 15:15:18 [DEBUG] terraform-provider-aws: 2016/02/29 15:15:18 [DEBUG] Trying to create ECS service again: "Creation of service was not idempotent."`

We have `lifecycle { create_before_destroy = true }` configured on all the ECS resources.

**Comment by CpuID** [comment]
Seeing the same error `timeout while waiting for state to become '[success]'` here, don't have any `lifecycle` rules configured on the resources.

**Comment by CpuID** [comment]
Aha - running with TF_LOG=debug, spotted something:

```
2016/03/30 15:24:01 [DEBUG] terraform-provider-aws: 2016/03/30 15:24:01 [DEBUG] Trying to create ECS service again: "The container mycontainernamehere did not have a container port 80 defined."
```

May be unrelated after all... digging further.

**Comment by CpuID** [comment]
The interesting behaviour here is it will retry every 10 seconds for at least a couple of minutes with the above error. We may need to blacklist certain error messages or codes from allowing a retry? So we can fast fail when there is a misconfiguration?
