### ISSUE TITLE
claudflare do not allow changing record type

### ISSUE THREAD

**Issue by nolith** [hashicorp/terraform#5316]
I changed a cloudflare record from CNAME to A and terraform planned it for editing but this type of change is not allowed.

Here the log (ip and domains redacted)

```
cloudflare_record.example: Modifying...
  type:  "CNAME" => "A"
  value: "example.com" => "127.0.0.1"
Error applying plan:

1 error(s) occurred:

* cloudflare_record.example: Failed to update CloudFlare Record: API Error: Editing types after a record has been created is not allowed.
```
terraform v0.6.11

**Comment by stack72** [comment]
Hi @nolith - unfortunately this is something that CloudFlare forbids rather than terraform. What you would need to do in this case would be to create a new piece of terraform config and then let terraform destroy the old record.

So effectively a destroy then create rather than an update

Hopefully this helps

Paul

**Comment by coen-hyde** [comment]
But shouldn't the destroy -> create be something that Terraform takes care of?

**Comment by stack72** [comment]
@coen-hyde - you are indeed correct - just making a fix for this right now.

Paul
