### ISSUE TITLE
"subject" of TLS_SELF_SIGNED_CERT is not documented

### ISSUE THREAD

**Issue by sheerun** [hashicorp/terraform#5343]
Hey,

The documentations says:

> subject - (Required) The subject for which a certificate is being requested. This is a nested configuration block whose structure is described below.

But "described below" block is not present.

https://www.terraform.io/docs/providers/tls/r/self_signed_cert.html#subject

**Comment by apparentlymart** [comment]
Thanks for pointing this out, @sheerun.

This bit of the doc was copied from `tls_cert_request`, since `tls_self_signed_cert`is basically just a shorthand around `tls_cert_request` and `tls_locally_signed_cert`. Rather than duplicating the doc and risking it getting out of sync, I just made it link to the corresponding docs on `tls_cert_request`.
