### ISSUE TITLE
Add ability to update nameservers of domains registered through AWS Route 53

### ISSUE THREAD

**Issue by garyp** [hashicorp/terraform#5368]
It'd be really useful if Terraform could automatically update the whois nameserver records for a domain registered through AWS Route 53 when that domain's zone is being managed via Route 53.

That is, the current `aws_route53_zone` resource defines a `name_servers` attribute for getting the list of nameservers that AWS assigned to the zone. For domains that are registered via Route 53 (http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/registrar.html), I'd like Terraform to use the [UpdateDomainNameservers API](https://docs.aws.amazon.com/Route53/latest/APIReference/api-update-domain-name-servers.html) to update the domain's nameservers using the `aws_route53_zone.name_servers` attribute.

It would probably make sense to model a new `aws_route53_domain` resource that supports the registered domain API: https://docs.aws.amazon.com/Route53/latest/APIReference/actions-on-domain-registrations.html.

**Comment by stack72** [comment]
@garyp how about the first first pass we do:

* domain_contact
* domain_contact_privacy
* nameservers

It would be based off an existing domain

Thoughts?

**Comment by garyp** [comment]
@stack72 That sounds great. All I really care about at the moment is nameservers so that I don't have to go manually update the domain's nameservers based on what `aws_route53_zone` auto-allocates. Everything else is gravy for future automation :)

**Comment by grebois** [comment]
+1

**Comment by apparentlymart** [comment]
Trying to think ahead a bit just to make sure we get the model of `aws_route53_domain` as future-proof as possible.. that would presumably mean we use the following operations:
* `Create`: `RegisterDomain` and then much of what's listed for `Update` below
* `Update`: `RenewDomain`, `EnableDomainAutoRenew`, `EnableDomainTransferLock`, `UpdateDomainContact`, `UpdateDomainContactPrivacy`, `UpdateDomainNameservers`
* `Read`: `GetDomainDetail`
* `Delete`: Doesn't seem to have any meaningful mapping

Some wrinkles:
* `RegisterDomain` implicitly creates a zone. Our existing `aws_route53_zone` resource expects to create a fresh one, so we'll need to think about how we model Terraform "taking control" over a zone created via `aws_route53_domain`.
* Some of these operations seem to be asynchronous; we'll need to figure out if Terraform should poll for them to complete before it considers the resource to be successfully created/updated.
* What will we do about `Delete`?

Certainly don't need to implement all of the above on a first pass, but it'd be good to think about how this resource might evolve to cover more of this API surface in future so that we're not forced to break compatibility in a later change.
