### ISSUE TITLE
Allow multiple aws_route53_zone_association's

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#5373]
I'm trying to associate a route53 zone to multiple VPCs with Terraform, but can't figure out how to do it.

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs.html
http://docs.aws.amazon.com/Route53/latest/APIReference/API_AssociateVPCWithHostedZone.html

So i _expected_ something like this to work:

```
resource "aws_route53_zone_association" "main" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  vpc_id = ["${aws_vpc.first.id}", "${aws_vpc.second.id}", "${aws_vpc.third.id}"]
}
```

But <code>vpc_id</code> can't take a list...
- aws_route53_zone_association.main: vpc_id must be a single value, not a list

I'm running Terraform **v0.6.11**

Am I missing something, or isn't this implemented (yet)?

Adding the second and third VPC in the AWS Console work just fine.

**Comment by stack72** [comment]
@FransUrbo, the current way to do this would be to have 1 association per VPC_id. The current AWS SDK only allows 1 association to be made per API call. therefore, we would need to loop over the VPC_ids. 

At least when you specify 3 associations separately, terraform can try and parallelise them :)

Would it help to make the documentation clear that only 1 VPC_ID per association is allowed?

Paul

**Comment by FransUrbo** [comment]
From my understanding of the documentation linked in the issue, every <code>POST</code> creates a new association... ?

**Comment by stack72** [comment]
@FransUrbo, the SDK that Terraform uses is based on this cli call

http://docs.aws.amazon.com/cli/latest/reference/route53/associate-vpc-with-hosted-zone.html

As you can see this takes 1 zone id per 1 vpc id.

**Comment by FransUrbo** [comment]
I see nothing in that that suggests that it will overwrite ("not support" multiple requests) the last one or all of it if called multiple times...

**Comment by stack72** [comment]
@FransUrbo my apologies if i mistakenly suggested that adding an array would overwrite entries. That was not what i was saying. I am merely stating that having an array of VPC_IDs would mean terraform would perform a loop and call the api and create the association 1 vpc id after another

**Comment by FransUrbo** [comment]
Yes, that was what I thought it would do. But it's not accepting an array/list at the moment...

**Comment by FransUrbo** [comment]
*bump* Any progress on this?

**Comment by radeksimko** [comment]
@FransUrbo I think what you want to achieve probably makes sense. Changing the existing DSL in a backward-compatible manner is a challenge, and is unlikely to happen (soon). Maybe we could introduce something like `vpc_ids` and make `vpc_id` & `vpc_ids` mutually exclusive?

I assume these are VPCs for different customers that you host in the same account?
Understanding the use case (_if_ you can share it with us) would be helpful.

I think the easiest solution is something like this:

```hcl
variable "vpc_cidrs" {
  default = {
    "first" = "10.0.0.0/16"
    "second" = "20.0.0.0/16"
    "third" = "30.0.0.0/16"
  }
}

variable "vpc_names" {
  default = "first,second,third"
}

resource "aws_vpc" "main" {
  count = "${length(split(",", var.vpc_names))}"
  cidr_block = "${lookup(var.vpc_cidrs, element(split(",", var.vpc_names), count.index))}"
}

resource "aws_route53_zone" "main" {
  vpc_id = "${aws_vpc.main.0.id}"
  name = "notexample.com"
}

resource "aws_route53_zone_association" "second" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  vpc_id = "${aws_vpc.main.1.id}"
}

resource "aws_route53_zone_association" "third" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  vpc_id = "${aws_vpc.main.2.id}"
}
```

I first thought that the `*` expansion would help in the association resource, but unfortunately the AWS API requires at least 1 VPC ID to be assigned when creating a private zone - i.e. **it is impossible to create a private zone without attaching the first VPC**.

This also makes the implementation of `vpc_ids` (list) slightly more difficult/challenging (probably not impossible though). It would probably need to be `ForceNew: true` because we'd have to choose the initial VPC ID for the zone. If user decided to remove any from the list we'd have to recreate the whole zone (=> recreate all records in the zone too) and reattach all VPCs again. :boom: 

This also means that adding a new VPC ID into existing list would always cause recreation of the zone, even though it may not be necessary. :boom: 

A PR with `vpc_ids` is welcomed, but personally if I would end up in a situation where I need to attach multiple VPCs to a single zone, I would rather copy-paste the `aws_route53_zone_association` and/or maybe done something clever with `count` and `+/- 1`.

When talking about DNS, availability/durability should take priority over clean code IMO.

**Comment by radeksimko** [comment]
Here is an example of slightly cleaner solution with some fancy interpolation:

```hcl
variable "vpc_cidrs" {
  default = {
    "first" = "10.0.0.0/16"
    "second" = "20.0.0.0/16"
    "third" = "30.0.0.0/16"
  }
}

variable "vpc_names" {
  default = "first,second,third"
}

resource "aws_vpc" "main" {
  count = "${length(split(",", var.vpc_names))}"
  cidr_block = "${lookup(var.vpc_cidrs, element(split(",", var.vpc_names), count.index))}"
}

resource "aws_route53_zone" "main" {
  vpc_id = "${aws_vpc.main.0.id}"
  name = "notexample.com"
}

resource "aws_route53_zone_association" "second" {
  count = "${length(split(",", var.vpc_names)) - 1}"
  zone_id = "${aws_route53_zone.main.zone_id}"
  vpc_id = "${element(aws_vpc.main.*.id, count.index+1)}"
}
```

Here the zone gets recreated only if the first VPC in the list is changed and adding a new zone is a matter of adding 1 line into `vpc_cidrs` map and `vpc_names` list. The support for maps/lists will be improved soon.

Looking at a fairly clean solution for this problem above and thinking about the difficulties we'd have to deal with when implementing `vpc_ids`, I would suggest closing this - do you agree @FransUrbo ?

**Comment by FransUrbo** [comment]
The (current) use case is that I have:

1. An "admin" VPC where some core services resides (such as Salt, Graylog, Jenkins master and swarms etc) which all the others use.
  * Because of this, this VPC needs two-way access to the other VPCs. Services here needs to be able to RESPOND to a request from other hosts in other VPCs, but also PUSH to other hosts in other VPCs.
2. A DB VPC (doh :) - where all the database(s) reside (also used by all the others).
  * This only need two-way access to "one" (it needs to SEND a query to "one", but also "RESPOND" to a query from "one"), all others need a one-way access to this VPC.
3. A "Development" (staging) VPC where the (our) software is base-tested (such as "does it compile", "does it install", "does it start up" etc).
  * Only need a two-way access to "one" and a one-way access to "two".
4. A "Integration" VPC (where more thorough software tests are done).
  * Only need a two-way access to "one" and a one-way access to "two".

Each VPC ("environment") is a separate module in TF, with some scripting to add new ones as the need arises (we have a couple more lined up, but I need to get these fully working first). "Inside" each VPC is a number of ASGs, one per service.

And this is the part of the DNS/route53. It need access to the Jenkins master (etc) via the **host name**, because the IP changes as AWS kills or replaces the instances (I haven't actually checked if AWS updates the zone if/when it replaces an instance, but I'll assume it does for now :).

So the "one" VPC needs to "share" its route53 zone with the others (by default, you can only access a route53 zone from within the VPC that created it). This is currently done using the AWS Console, but I'd prefer to have Terraform do this.

Also, "three" and "four" needs host name access to the master DB (for the same reason). But because TF doesn't support "sharing" the zone with more than one VPC (yet), I haven't put that part in yet.

I don't have much opinion on how you solve this in code, but although I know absolutely no Go, I am quite an experienced programmer (in other languages) and figuring out if a variable is a list (array) or a string should be reasonably straight forward (?). For backwards compatibility that is. But calling it <code>vpc_ids</code> (list) instead of <code>vpc_id</code> (string) seems a lot easier and I'm happy with that. So in pseudo code:

* if vpc_id:
  * is it a string
    * do magic once
  * is it a list
    * do magic several times

[or:]

* if vpc_id:
  * do magic once
* else if vpc_ids:
  * do magic several times

**Comment by radeksimko** [comment]
@FransUrbo Thanks a lot for further explanation of your use-case. It makes total sense to me.

> But because TF doesn't support "sharing" the zone with more than one VPC (yet), I haven't put that part in yet.

Well, it does - try re-reading my code examples above. It may not be super-clean as it involves some code duplication, but it works (it effectively does what you want).

I see that [the CloudFormation team](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-vpcs) managed to implement this quite nicely - they don't require replacement for updates, as long as there's always at least 1 VPC.

In Terraform we would need to introduce some core schema changes - probably something like `ForceNewWhen: func()` which would trigger replacement only in certain cases (no VPC -> 1+ VPCs or 1+ VPCs -> no VPC).

I submitted a separate issue for this: https://github.com/hashicorp/terraform/issues/5895

I will keep this open then, since I think we might be able to get around the schema limitation and then eventually implement this.

Does any of the two examples above work for you in the meantime?

**Comment by FransUrbo** [comment]
I rather not have to maintain a <code>vpc_names</code> variable as well (it starting to be complicated enough). But I'll do that in the meantime. Thanx.

**Comment by FransUrbo** [comment]
However, this gave me an idea, based on your example. But you're using <code>count.index</code> in the loop.

```
variable "vpc_names" { default = "first,second,third" }

resource "aws_route53_zone_association" "main" {
  count = "${length(split(",", var.vpc_names)) - 1}"
  zone_id = "${module.admin.zone_id}"
  vpc_id = "${element(module.*.vpc_id, SOMETHING_TO_USE_THE_NAME)}"
}
```

**Comment by FransUrbo** [comment]
Looking at the *Interpolation* documentation, this is how I envisioned it:

```
  vpc_id = "${element(module.*.vpc_id, lookup(var.vpc_names, count.index+1))}"
```

But that just gave me:

```
* aws_route53_zone_association.main: missing dependency: module.*.output.vpc_id
```

**Comment by FransUrbo** [comment]
This *kinda* works

```
variable "vpc_names" {
  default = {
    "0" = "first"
    "1" = "second"
    "2" = "third"
  }
}

resource "aws_route53_zone_association" "main" {
  count = "${length(var.vpc_names) / 2 - 1}"
  zone_id = "${module.admin.route53_zone_id}"
  vpc_id = "${format("module.%s.vpc_id", lookup(var.vpc_names, count.index))}"
}
```

**plan** doesn't complain, but once **apply** runs, I get:

```
* aws_route53_zone_association.main.1: InvalidVPCId: The VPC: module.second.vpc_id you provided either is not found or doesn't belong to you.
        status code: 400, request id: d0446b0e-f666-11e5-8780-257673150e4c
* aws_route53_zone_association.main.2: InvalidVPCId: The VPC: module.third.vpc_id you provided either is not found or doesn't belong to you.
        status code: 400, request id: d043f6b0-f666-11e5-ade1-094c33004367
* aws_route53_zone_association.main.0: InvalidVPCId: The VPC: module.first.vpc_id you provided either is not found or doesn't belong to you.
        status code: 400, request id: d044b949-f666-11e5-922b-f549521909a7
```

**Comment by radeksimko** [comment]
@FransUrbo Yeah, I didn't realize you have module per VPC (which is totally reasonable thing to do). 

Unfortunately it is currently not possible to iterate over modules (which is related to [the use of `count` in modules](https://github.com/hashicorp/terraform/issues/1471) generally) neither it is possible to use interpolation around module names/keys (like you did above w/ `format` function), so I think you're going to have to stick with the first example I posted above - duplicated `aws_route53_zone_association`.

I'm afraid atm there isn't more elegant solution for this (yet).

**Comment by FransUrbo** [comment]
@radeksimko Perfect! That worked like a charm!
