### ISSUE TITLE
[feature request] JSON generator

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#5383]
Now that PR #4906 switches from using a map to a raw json string, it makes it necessary to build JSON by hand. This is extremely error prone. It would be nice if there was a way to have a helper to build JSON for you.

e.g., the json could be defined like

```
resource "json" "foo" {
  vars {
    my-var    = "123abc"
    something = "yes"
    my-array  = ["one", "two"]
    my-users  = ["${var.json.user1}", "${var.json.user1}"]
  }
}

resource "json" "user1" {
  vars {
    name    = "user1"
    home    = "/home/user1"
  }
}

resource "json" "user2" {
  vars {
    name    = "user2"
    home    = "/home/user2"
  }
}

resource "json" "bar" {
  vars {
    foo      = "${json.foo}"
    my-name  = "mike"
    my-count = 5
  }
}
```

where the output of `${json.bar.rendered}` would be

```
{
  "foo": {
    "my-var": "123abc",
    "something": "yes",
    "my-array": ["one", "two"],
    "my-users": [
      {
        "name": "user1",
        "home": "/home/user1"
      },
      {
        "name": "user2",
        "home": "/home/user2"
      }
    ]
  },
  "my-name": "mike",
  "my-count": 5
}
```

**Comment by apparentlymart** [comment]
Unfortunately in Terraform's current design it's hard to support a resource like this since the resource schema's type system doesn't allow for "arbitrary recursive data structure" as a field type. This is what #3026 was about.

However, I do agree that this would be useful... it's annoying to produce JSON using just string concatenation/interpolation, because its syntax is so strict.

I've added the "thinking" tag to this for now, which means that we'll reflect on this for now and see if there is a reasonable way to do it.

**Comment by mtougeron** [comment]
I totally understand. As I think about it this morning, perhaps it doesn't belong as a normal `resource` but more of a interpolation function that can be used in templates. IDK, just trying to think of ways to not build JSON by hand and not have to create json files via a different process before running terraform. :/

**Comment by mtougeron** [comment]
This request is taken care of with the `jsonencode(item)` interpolation function.
