### ISSUE TITLE
Unable to enable instance recovery on Terraform created instances

### ISSUE THREAD

**Issue by stonith** [hashicorp/terraform#5390]
When Terraform creates instances, instance recovery is not available as an option in Cloudwatch. I was able to track this down to a bug in the AWS API. AWS is looking to fix this on their end however it's probably going to take some time as it may break functionality. 

If you specify ephemeral storage via the API on an instance type that doesn't support ephemeral storage ie. C4, T2, etc. the block devices are created in AWS's system but not visible to the user in the instance OS, AWS Console, or API. I had to have a support person confirm that they saw the block devices on their end. As per the [Instance Recovery](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-recover.html) documentation: "Currently, the recover action is not supported for... instances launched with block device mappings for instance store volumes." which means the invisible block devices end up blocking the instance recovery option.

Steps to Reproduce:
- create an instance that supports instance recovery ie. T2, C4, etc with Terraform (or AWS API AND specify ephemeral storage)
- attempt to enable instance recovery on the instance by creating a Cloudwatch alarm with the instance recovery action

Comparions
- create same instance via AWS Web Console and enable instance recovery
- create same instance via AWS API WITHOUT specifying ephemeral storage and enable instance recovery

**Comment by jen20** [comment]
Hi @stonith! Thanks for opening the issue. I'm going to merge this into #5388 (as it is marginally older), which I think is referencing the same thing. It looks like this should be fixable.

**Comment by timonwong** [comment]
@jen20 
Hi, I think actually this is a bit different than #5388, actually, the problem is that there are invalid ephemeral block devices attached to the instance, when using an EBS-only instance and AMI images with block mappings defined.

From terraform source code: https://github.com/hashicorp/terraform/blob/7c58896f3069bf83a8209d7b9f1e99eb72629d50/builtin/providers/aws/resource_aws_instance.go#L841
I learned that device mapping are fetched from AMI through `fetchRootDeviceName()` and append to BDM directly without checking ephemerals.

Since #5388 is closed, IMO I think it's better to address this issue here?
