### ISSUE TITLE
Docker Cloud

### ISSUE THREAD

**Issue by jonsharratt** [hashicorp/terraform#5394]
```
As a developer
I want to be able to provision using docker cloud as a provider
So that I can provision my infrastructure via Docker Cloud
```

Just been trying out Docker Cloud, so far rather impressed was wondering if we could start looking at adding it as a new provider.  Interestingly if it was supported then itself has providers support, not sure what people think in regards to using Terraform for provisioning?

**Comment by jen20** [comment]
Hi @jonsharratt! Thanks for opening this issue. I've not looked at Docker Cloud yet, but it's quite possible there is scope for a Terraform provider. Unfortunately given the backlog of issues and pull requests right now it's unlikely to make it to the top of our stack in the very near future. If yourself and/or others are willing to work on a provider though, we'd be happy to review it and merge as per our [contribution guidelines](https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md)!

**Comment by nextrevision** [comment]
I added a few resources a little while back when it was called tutum in a PR that is still open (#4353). It just needs to be refactored (and retested with Docker Cloud).

**Comment by roylines** [comment]
I'd love to help work on this if anyone wants to join me

**Comment by nextrevision** [comment]
I'm refactoring the PR I mentioned above to be Docker Cloud instead of Tutum. Should have something up today. Most of it is the same, however, there are a few things that need to be modified. They have a go library for interacting with the service (github.com/docker/go-dockercloud), but it leaves a bit to be desired as the API exposes much more than the library, even for common types like services. The library is lagging a bit behind, from what I can tell, so it's a bit tough to add all the features supported by the API until the library catches up.

**Comment by nextrevision** [comment]
Pushed up the refactor to the provider to make it Docker Cloud instead of Tutum (#4353). @roylines would be more than happy to collaborate on this.

**Comment by willrstern** [comment]
Is there any update on this one by any chance?  It would be awesome to be able to manage clusters and stacks in code!

**Comment by dylangrafmyre** [comment]
Update please! This would be great!! Thanks! What else can be done to make this happen?

**Comment by roylines** [comment]
What remains to be done on this? Is it just a case of an admin checking over the pull request #4353 ?

**Comment by djsnowsill** [comment]
Any update on this? If i can help out in any way please let me know

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

**Comment by nextrevision** [comment]
Hey @stack72, I've had PR #4353 open for a little longer than this ticket. It has been ready to merge for over a year now, but has received no feedback from a TF member. I stopped periodically rebasing it because I never heard anything. Are there any plans to move on that PR?

**Comment by stack72** [comment]
Hi @nextrevision 

I can look at that PR for you - please can you rebase it while i start looking

Thanks

Paul
