### ISSUE TITLE
Function to access a random element of an array

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5479]
Currently, I do this to ensure that instances are distributed across multiple availability zones:

```
resource "aws_instance" "instance" {
  availability_zone = "${element(split(",", var.availability_zones), count.index)}"
  count = "${var.count}"
}
```

As a result, I end up with a lot of instances running in the first availability zone. It would be useful here is terraform had some sort of `random_element` function which could access a random element of `${var.availability_zones}`. Alternatively, maybe this is something that could be set on the provider-level instead. Perhaps something like this:

```
provider "aws" {
  distribute_availability_zones = true
}
```

**Comment by radeksimko** [comment]
Hi @joshuaspence 
I personally think that most of the problems you mentioned can (and in most cases should) be addressed by using autoscaling groups instead of standalone EC2 instances, but I'll keep this open to see if someone comes up with any other use case for `random()` function.

**Comment by doertedev** [comment]
We use terraform in our fleet for firing up boxes on demand and then suddenly drop the statefile afterwards. In order to automate this, we want to throw this into $CIsoftware for nomad. The current workaround consists of a wrapper Rakefile that throws this random availabilityzone into the terraform command as a variable. This might be really useful.

**Comment by apparentlymart** [comment]
Hi @joshuaspence, @doertedev,

In a recent Terraform version we added [the "random" provider](https://www.terraform.io/docs/providers/random/index.html), and in particular [the `random_shuffle` resource](https://www.terraform.io/docs/providers/random/r/shuffle.html) that can implement exactly the use-case you're describing here... it's even the example on the docs page. :grinning:

This provider uses the Terraform state to avoid the random numbers "flapping" from one run to the next, but if you truly do want a different random result on each run then either discarding the whole state file (as @doertedev described) or specifically tainting the `random_shuffle` instance can be used to achieve that.

Since it seems like this use-case is now handled, I'm going to close this. Please let me know if there's another detail here that I missed...
