### ISSUE TITLE
Cannot taint aws_lambda_permission

### ISSUE THREAD

**Issue by tj** [hashicorp/terraform#5484]
Deleted a function (outside of Terraform) and now it just hangs for 30-60s finally resulting in:

```
aws_lambda_permission.checks_sns_invoke_check_processor: timeout while waiting for state to become '[success]'
```

I tried tainting and re-planing but I get the same result. I guess this might also be a bug with it not detecting a missing permission?

I added the function back and permission back via the AWS CLI, then it was fine.

**Comment by tj** [comment]
Also is there a nicer way to ignore this sort of issue? I'm a little worried about using it in prod now, if I have to fix something quickly and terraform has some funky bug I'll have to do it manually and the state will be much worse off than before

**Comment by radeksimko** [comment]
Sorry for the troubles.

I think this will be fixed via https://github.com/hashicorp/terraform/pull/5460

> I guess this might also be a bug with it not detecting a missing permission?

That may also be true, it is tracked under https://github.com/hashicorp/terraform/pull/5205

**Comment by jen20** [comment]
Hi @tj! As @radeksimko identifies, the error message being elided here is part of a wider group of issues which is being tracked by a meta-issue over at #5537, and the other option is tracked at #5205. Consequently I'll close this issue in favour of continuing the discussion over there in order to keep it in one place. Thanks for reporting this!
