### ISSUE TITLE
terrraform is trying to recreate my redshift cluster because of : publicly_accessible: "" => "0"

### ISSUE THREAD

**Issue by frederic-jomedia** [hashicorp/terraform#5494]
I created my redshift cluster with terraform and did not set publicly_accessible (because of the default = true)
Cluster was created without any issue but now, if I run terraform plan, terraform wants to destroy and re created the redshfit cluster because of : 
publicly_accessible:                 "" => "0" (forces new resource)

It seems that terraform sees the value emptied event if in AWS I have : Publicly Accessible	Yes
Also this parameter should not trigger a re creation of the all cluster.

I might have created it with version V0.6.11 and now running V0.6.12

**Comment by catsby** [comment]
Hey @frederic-jomedia – sorry for the trouble here. This behavior was changed in #5262 and documented in the CHANGELOG as a backwards incompatible change in v0.6.12:

- https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0612-february-24-2016

Basically, the default _should_ be `true` here, and now it is. A Redshift cluster created before v0.6.12 was incorrectly getting a default of `false`, e.g. it was not publicly accessible. 

This is of course assuming you did create the cluster with v0.6.11. If you did not please let me know, otherwise I'm going to close this for now. Sorry for the trouble

**Comment by frederic-jomedia** [comment]
Is there a way to "hack" the tfstate so I can still use terraform to handle my redshift cluster ? because plan wants to recreate it now

tx

**Comment by frederic-jomedia** [comment]
Also it still should not recreate the cluster for a change that can be done on AWS side without any impact on the cluster and the data

**Comment by catsby** [comment]
I believe you can insert the 0 for publicly accessible in your statefile, but I would verify that with a plan to ensure :smile: 

> Also it still should not recreate the cluster for a change that can be done on AWS side without any impact on the cluster and the data

Absolutely correct. I opened https://github.com/hashicorp/terraform/issues/5540 to track that separately, and I'm going to close this. The change should be simple enough, but I may not get to it this week.

Thanks, and sorry for the hassle here

**Comment by catsby** [comment]
@frederic-jomedia hey, small update, while we have #5540 open to track the change to make this not be a force new operation, we've found out that said operation is not actually exposed in the API at all yet. We'll leave that issue open and get it done when it's finally exposed in the API.

**Comment by frederic-jomedia** [comment]
Hello,
tx for the feedback.
I  added 
` "publicly_accessible": "true",`
to terraform.tfstate
and it did the trick

I will follow #5540
