### ISSUE TITLE
Referencing `docker_container.*.ports.*.external` does not work

### ISSUE THREAD

**Issue by geovanisouza92** [hashicorp/terraform#5510]
I'm trying to referencing a `docker_container` resource ports, but is does outputs anything, even if the external port is fixed. The workaround is inform the external port through variable, then use it on interpolations.

[Here](https://gist.github.com/geovanisouza92/fbef3aa9e0ae734350b1) is an example of configuration files and results.

**Comment by jen20** [comment]
Hi @geovanisouza92! I don't think there is an easy workaround for this at the moment, and the implementation makes it difficult to do multiple "splats" in one interpolation such as `docker_container.*.ports.*.external` would require right now. For now the best workaround is to buffer via a variable, which you have already used by the look of it. This is something that we might come around to in the future, but for now I'm going to close it - feel free to reopen if you have further questions. Thanks for opening this issue!

**Comment by geovanisouza92** [comment]
Hi @jen20,Thank you for reply!

I expressed myself badly. I don't intended to use splats, but simple references to the first external port of each container, like

```hcl
output "foo" {
  value = "${docker_container.mysql.ports.0.external}" # Here
}
```

Another thing that I noticed is event `terraform refresh` command isn't capable to read the port from the running container. Digging through the code, I saw [this](https://github.com/hashicorp/terraform/blob/master/builtin/providers/docker/resource_docker_container_funcs.go#L234), so I think that the method `resourceDockerContainerRead` should read the ports and set the `ResourceData` object. I hope that this could make any sense.

Thank you.

**Comment by apparentlymart** [comment]
Hi @geovanisouza92! Sorry for the long silence here... this issue was using an old labeling scheme, and so we missed it on previous passes of posting updates.

It seems like this issue is covering the same needs as #17048, so I'm going to close it just to consolidate the discussion over there. I've previously posted some updates in that issue about plans for the next major release that will, I think, get you what you needed here.

("double-splats" is not in scope for that, but I see you clarified in your later comment that this wasn't what you needed anyway.)
