### ISSUE TITLE
Add a function for minifying JSON

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#5526]
The AWS API is very fussy with the `wlm_json_configuration` parameter for `aws_redshift_parameter_group`. If you attempt to use a multi-lined JSON string, the AWS API will return an error:

```
* aws_redshift_parameter_group.analytics: Error modifying Redshift Parameter Group: InvalidParameterValue: Invalid JSON for wlm_json_configuration: Multi line JSON is not allowed
    status code: 400, request id: REDACTED
```

It would be great if Terraform had some some of "minify" function which removed whitespace from the JSON string so that it can be used for this parameter.

**Comment by jen20** [comment]
Hi @joshuaspence! Thanks for reporting this and opening an issue. I agree that a general purpose JSON minifying interpolation function is a good idea (cc @phinze and @catsby for second opinions there).

In this case I think we could also view this as a bug in `aws_redshift_parameter_group` - if that API has such specific requirements perhaps we should consider formatting the JSON correctly as part of making the API calls. I believe @stack72 did most of the work on RedShift, so I'll loop him in here too for comment.

**Comment by apparentlymart** [comment]
Hi @joshuaspence! Thanks again for reporting this, and sorry for letting it sit here so long.

It's pretty weird for an API to constrain JSON such that newlines are not allowed, so I agree with @jen20 here that it'd be better to approach this as a fix within `aws_redshift_parameter_group` to automatically minify the JSON. That way Terraform will just "do the right thing" without the need for configuration authors to do anything unusual.

With that said, we (the Terraform team) are not planning to work on this in the near future, so I'm going to close this as part of our effort to prune issues that are likely to remain stale.

If you or anyone else is motivated to work on this, we'd love to review a PR!

**Comment by jefftucker** [comment]
@apparentlymart Any chance we could re-open this as a feature request for a more general-purpose json minify function?  My use case is different than what is presented here.  AWS has character maximums for IAM policy documents and some of the suggested guidance from AWS is to strip whitespace as much as possible for lengthy policies (of which I have plenty).  What I'd like is to have the policy itself in a nice human-readable format that is also a template that I can consume with the templatefile() function.  What I'd like to be able to do is define a policy attribute (or resource) with something like this:
`policy = jsonminify(templatefile("filename.tpl", param1, param2, ...))` 
so it reads my nicely-formatted template, applies the values that I give it, then will minify the result.  I could store the policy templates on their own and minify them as a pre-build step in my CI pipeline before invoking terraform, however I don't think that a "normal" json minification utility would really do the trick since I doubt it would properly handle template directives.  It would also be nice for me to be able to turn on the right level of logging/debugging and be able to see the output of the file both pre and post minification just in case I screw something up.

I'd be happy to create a new issue if that would be more useful/appropriate but I figured I'd comment here first since searching for existing feature requests turned up this one and the "minify" function that is proposed here is precisely what I'm requesting.

**Comment by apparentlymart** [comment]
As of Terraform 0.12, you can produce minified JSON using a round-trip through `jsondecode` and `jsonencode`, because `jsonencode` always produces minimal JSON:

```hcl
  policy = jsonencode(jsondecode(templatefile("filename.tpl", {})))
```

Since minification is not something we expect to see done routinely in Terraform configurations (as I noted before, the providers should do whatever preparation is needed to make user input work with the remote API), we're not likely to add a specialized function just for that purpose, but at least with the above pattern you can now do it in unusual situations where the provider isn't yet applying the necessary transformation.

In this case where your template is presumbly producing just JSON anyway, I'd suggest a modification: write the template itself to use `jsonencode` so that you can use the full Terraform expression language to produce your result, and not have to deal with finicky JSON formatting concerns:

```
${jsonencode({
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "example",
      "Effect": "Allow",
      "Action": ["s3:ListAllMyBuckets"],
      "Principal": [service_arn],
    },
    # etc, etc
  ],
})
```

The result will automatically be minified because, as noted above, `jsonencode` always produces minimal JSON. Terraform's expression language permits things that JSON alone does not, such as inline comments, trailing commas on the last item in an object or array, direct references to template variables, and [`for` expressions](https://www.terraform.io/docs/configuration/expressions.html#for-expressions) for constructing arrays and objects dynamically.
