### ISSUE TITLE
Set windows host name using Terraform

### ISSUE THREAD

**Issue by mohamaa** [hashicorp/terraform#5530]
Guys i am new to Terraform and very happy to see the functionality and ease it provides to provision multiple instances at once.

My issue for now is :
I want to set the host name same as tag name for an aws windows server using Terraform, but its not working or possible or i may be missing something ?

my current code to add tag name is :
```
# Specify the provider and access details
provider "aws" {
	access_key = "${var.aws_access}" 
	secret_key = "${var.secret_key}" 
	region = "us-east-1"
}

resource "aws_instance" "terraform-run" {
  count= "${var.count}"
  instance_type = "${var.instance_type}"
  ami = "${var.ami}" 
  key_name = "${var.key_name}"
  security_groups = ["${compact(split(",", var.security_groups))}"]
	tags {
        Name = "e${var.zone}${var.chef_env}${var.type}_${format("%03d", count.index + 1)}"
    }
    connection {
		type = "winrm"
		user =  "${var.admin_username}"
		password = "${var.admin_password}"
	}
 }
```
Is it possible to set the host name as per user defined names ? the way we could do for tag names ?
Please note : I don't want to reboot the server after renaming the host name.

**Comment by jen20** [comment]
Hi @mohamaa! Thanks for opening an issue. I'm not sure this is the optimal place to get this question answered however - I'm not aware of a way to set the Windows hostname of an EC2 instance via tagging in the AWS API. As far as I know the only way to set a hostname without a reboot is to do it at the specialisation phase of sysprep.

You may want to look into the [EC2 Config Service documentation](https://aws.amazon.com/developertools/5562082477397515) for more information about how EC2 instances generate hostnames and so forth, and what you can do to control that.

I'm going to close this since I'm not sure there's much that Terraform itself can do to help out here, but feel free to follow up if you have any further questions!
