### ISSUE TITLE
AWS_ROUTE, AWS_ROUTE_TABLE and instance_id

### ISSUE THREAD

**Issue by y3ti** [hashicorp/terraform#5531]
Hi,

I have a question about AWS_ROUTE, AWS_ROUTE_TABLE and instance_id. I have checked the documentation:

https://www.terraform.io/docs/providers/aws/r/route.html
https://www.terraform.io/docs/providers/aws/r/route_table.html

Why the `instance_id` has a different meaning for AWS_ROUTE and AWS_ROUTE_TABLE?

```
AWS_ROUTE:

instance_id - (Optional) An ID of a NAT instance.

AWS_ROUTE_TABLE:

instance_id - (Optional) The EC2 instance ID.
```

This is only a mistake in documentation or the argument `instance_id` has got realy a different meaning?

**Comment by jen20** [comment]
Hi @y3ti! This was an issue with clarity of our documentation error which I've fixed in #5539. Most likely if you're specifying an `instance_id` in a route table it will be one that is running NAT, although this is now less common thanks to NAT Gateway. Consequently I've updated `aws_route` documentation to match `aws_route_table` and the AWS documentation. Thanks for reporting this!
