### ISSUE TITLE
provider/aws: SG Rules should accept SG Name for `source_security_group_` in EC2 Classic

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#5555]
https://github.com/hashicorp/terraform/issues/5532 points out that, in EC2 Classic, we need to reference the group _name_ for `source_security_group_id`. 

While we can "fix" this by documenting the need for the name in Classic, a better solution would be to add `source_security_group_name` to the fields and check for it in [resource_security_group_rule.go](https://github.com/hashicorp/terraform/blob/v0.6.12/builtin/providers/aws/resource_aws_security_group_rule.go#L404), only picking it up if `source_security_group_id` is not found

**Comment by xsb** [comment]
My personal opinion is that in case it gets splitted in 2 parameters it would add more complexity (can't use both at the same time, can't use `source_security_group_name` in VPC and can't use `source_security_group_id` in EC2 Classic). So I think it's simpler to keep using `source_security_group_id` but add proper documentation explaining that in EC2 Classic the ID is the name. Even the documentation would be simpler than having to explain why the resource needs two different parameters that are mutually exclusive.

It also makes more sense to focus in naming VPC resources well because new AWS accounts (and even entire AWS regions) doesn't support EC2 Classic.

**Comment by xsb** [comment]
Changing my opinion as I write, haha. Althoug I think it's way easier with a single parameter, if we strictly follow the AWS API there should be two different parameters. For example, the aws cli uses `--group-id` for EC2-VPC and `--group-name` for EC2-Classic.

So in the end it depends on how strictly Terraform wants to follow the upstream provider API conventions over its own ability to offer a simplified interface.

**Comment by dfboyd** [comment]
I ran into this today, and I've run into it in the past.  I think you need to apply more validation: you can tell when an SG is part of a VPC or not; and if it is, you need to require group-to-group rules to have `source_security_group_id` to be populated with `aws_security_group.whatever.id`; and if the SG is not a VPC SG, then you need to require `source_security_group_name` to be present and populated with `aws_security_group.whatever.name`.  That way the last part of the parameter (`name`, or `id`) and the output-value from the source security group should match.
