### ISSUE TITLE
Option to summarize list of CIDR's in aws security group

### ISSUE THREAD

**Issue by jaisingh** [hashicorp/terraform#5562]
When inputs for security groups are created if there are too many the security group cannot be created. It would be nice to add a flag to optionally summarize the list of IP's into a blocks. 

Eg:
```
listOfIps := []string {
"192.168.0.0/32",
"192.168.0.1/32",
"192.168.0.2/32",
"192.168.0.3/32",
}
```
would summarize into: 192.168.0.0/30 

This result would get added to the security group instead of the 4 original ip's.

**Comment by phinze** [comment]
Hi @jaisingh - interesting idea!

I can definitely see how this would be useful, however I think this falls outside of the type of behavior that should be part of Terraform itself. It's important that we keep Terraform's behavior as clear and predictable as possible, and adding summarization behavior like this - while it might be convenient for certain use cases - introduces an additional layer of complexity.

To illustrate this complexity, let's talk out a few scenarios assuming Terraform did summarize in the example you gave:

 * What happens when I add a `.4/32` to the list? Should Terraform remove the summarized CIDR and add 5 `/32` rules? Or should it keep the `/30` and add one `/32`?
 * What about if I add up through `.7`? Should we keep the `/30` and add 4 `/32`s or should we remove the `/30` and add a single `/29`?
 * Say we elect to go with a `/29`, then I remove just the `.6` entry, now Terraform needs to remove the `/29` and figure out that it needs to re-add either 7 `/32` entries or 1 `/30` and 3 `/32`s to cover the list.

As you can see, there's a lot of nuance and complexity here, and I think teaching Terraform what to do is going to take more effort and cause more bugs than just leaving it up to the operator.

Given all the above, I'm going to close this thread. I hope this all makes sense! Feel free to follow up if you'd like to discuss further.
