### ISSUE TITLE
provider/aws: Support Windows OpsWorks Stacks

### ISSUE THREAD

**Issue by EEDARIT** [hashicorp/terraform#5569]
Trying to create an AWS_OPSWORKS_STACK with "default_OS" set to "Microsoft Windows Server 2012 R2 Base" returns:

`* aws_opsworks_stack.test: ValidationException: Configuration Manager: can't be changed from Chef::11.4 to Chef::12.2, must be Chef::0.9`

OpsWorks Windows stacks need to be created with Chef 12.2 ([info](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_CreateStack.html#opsworks-CreateStack-request-ChefConfiguration)) and you can't change a Linux stack to a Windows stack once it has been created ([info](http://docs.aws.amazon.com/opsworks/latest/userguide/workinginstances-os.html)).

Looking at the [OpsWorks Go file](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_opsworks_stack.go) it appears that it is creating a default stack first, which is Linux, and then trying to update the other settings once the stack is created. Since you can't change a Linux stack to a Windows stack, this implementation won't work as far as I understand it.

**Comment by apparentlymart** [comment]
Yeah, this definitely looks like a bug. As you said @EEDARIT, it's erroneously trying to transform the stack from Linux to Windows.

The implementation here is trying to make a minimal stack in Create and then update it in Update in order to reduce code duplication, but in retrospect it'd be better to find a way to refactor this a bit so that it can just create stuff the right way to begin with. This is complicated by the fact that `CreateStackInput` and `UpdateStackInput` are not the same type, so it's difficult to write this generically in Go.

**Comment by phinze** [comment]
The fix in #5724 looked simple enough to pull in as is while we work on a larger fix. Seems reasonable to add DefaultOs on the initial create if that fixes up the windows code path. Will leave this open to continue discuss amore holistic fix.

**Comment by stack72** [comment]
Closed in #6244
