### ISSUE TITLE
google network attribute usage inconsistent

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#5584]
For different resources in the google cloud provider the usage of the network attribute is inconsistent.

For example the **google_compute_subnetwork** uses self_link:

_network = "${google_compute_network.default.self_link}"_

Whereas the **google_compute_firewall** uses name:

_network = "${google_compute_network.default.name}"_

This might be an inconsistency in the google apis, but makes it unpredictable how to use terraform.

**Comment by jen20** [comment]
Hi @JorritSalverda! It looks like we do some additional work in the `google_compute_firewall` resource to [get the network in order to get attributes from it](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_firewall.go#L210-L215) - this allows for specifying the friendly name of, for example, a network which was created outside of Terraform. In this case ideally we should have chosen to perform the GET on all networks and allow you to use `${google_compute_network.whatever.name}`, or require the `self_link` in all cases.

One of the decisions made with Terraform was to match the provider APIs very closely, unless they make little sense, but some resources predate that decision or were missed, and this is one of them. Changing these resources would result in existing users having working configuration broken, however, resulting in backwards compatibility problems, however, so sadly there is not a simple fix here.

One possible approach is to deprecate the `network` attribute and introduce two new ones - `network_name` where we perform the lookup and `network_id` or `network_self_link` which does not. This does diverge from the underlying API but introduces better usability in my opinion. Let's loop in @lwander who maintains the Google Cloud provider for a second opinion here. Thanks for bringing this to our attention, @JorritSalverda!

**Comment by lwander** [comment]
Ideally, when writing a resource, we should avoid requiring attributes like `self_link` whenever possible since the link encodes the version of the API used to read/create/update that resource. This makes updating APIs painful, as suddenly resources depending on anothers `self_link` see a value change when the underlying resource may have remained the same. This is a divergence from the official APIs, but IMO a valuable one for the sake of usability. 

This is a work item for the Google provider. Either @evandbrown or I should try to tackle this when we find time.

**Comment by sl1pm4t** [comment]
@jen20, @lwander - rather than deprecated the `network` attribute, we could attempt to detect whether the user has provided a link or a simple name, and handle accordingly?!
I'm happy to do the implementation if you don't have any objections to this approach. I have a vague memory that one of the google resources already behaves this way.

**Comment by lwander** [comment]
That sounds good to me - other GCP resources do this as well, I just also can't remember where I've seen that pattern.
