### ISSUE TITLE
aws_instance: TF is ignoring the new root_block_device value

### ISSUE THREAD

**Issue by rafabordon** [hashicorp/terraform#5640]
Terraform version 0.6.12
The AMI used had 30gb by default.We wanted to enlarge the block device to 50gb.'terraform plan' didn´t notice the change.

**Comment by zhefanlin** [comment]
Having this similar problem on 0.6.13
When using "root_device_block" in aws_instance resource block, to create a windows intance, AMI had 40GB by default, I set the root_block device size to 50GB, 

"terraform plan" did noticed the change, but after "terraform apply", the block device /dev/sda1 on AWS console still 40GB, besides the /dev/sda1, there was another device called xvdco which is 50GB. 

I log in that instance, couldn't find xvdco in windows disk manager, the disk C:\ was still defualt 40GB 

Sometimes it works correctly, but sometimes not.

If I use "ebs_block_device" plus device_name="/dev/sda1" instead of "root_block device", it works fine everytime, root disk got attached and mount correctly, but it will recreate instance resource if I want to re-apply without destroy it.
