### ISSUE TITLE
health_check_grace_period default value for AWS ELB health checks for Autoscaling group

### ISSUE THREAD

**Issue by anosulchik** [hashicorp/terraform#5658]
Looks like terraform sets health_check_grace_period to 0 (zero) as a default value when aws_autoscaling_group is configured with health_check_type = "ELB". According to AWS documentation it should be 300 (5 minutes):

`By default, the health check grace period is 5 minutes`

http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/healthcheck.html

**Comment by phinze** [comment]
Hi @anosulchik - in the API, the `HealthCheckGracePeriod` parameter is required when the `HealthCheckType` parameter is `"ELB"`, otherwise you get an error message as reported in #3327.

We do have a [note in the docs](https://github.com/hashicorp/terraform/blame/master/website/source/docs/providers/aws/r/autoscaling_group.html.markdown#L115) but it's a bit far down from the actual attribute reference.

I wonder if we should just pull the default of 300s down into Terraform as a default, which I believe would make the behavior a bit simpler for everybody. It has the tradeoff that if the default changes for whatever reason on the AWS side we'd have to play catch up, but it seems unlikely enough to not worry about.

/cc @stack72

**Comment by anosulchik** [comment]
Thanks for your reply, @phinze. To my opinion it would natural to make terraform to set default value the same as it does Amazon for ELB checks -- 300 sec. Just to prevent confusion that may case default value = 0 when this argument is not specified for ELB check in ASG.
