### ISSUE TITLE
Need a "GetExists" or similar for determining if a key is set in a configuration 

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#5694]
For AWS AutoScaling groups, `max/min/desired` capacity can be `0`, so we added the code in https://github.com/hashicorp/terraform/pull/4693 to no longer use `GetOk` in checking these values, and instead just use `Get`. 

https://github.com/hashicorp/terraform/issues/5681 reminds us that simply omitting `desired_capacity` should be allowed, too, since it's not actually required in the API. 

We need to be know if a key was set at all, not just if it was set and not a non-default value. 

`d.Get`: 

```
// If you want to test if something is set at all in the configuration,
// use GetOk.
```

`d.GetOk`:

```
// GetOk returns the data for the given key and whether or not the key
// has been set to a non-zero value at some point.
```

We need to check if it's been set, regardless of the non-default status or not

**Comment by stack72** [comment]
This ^^ :) Will be an awesome addition!

**Comment by phinze** [comment]
Definitely agreed that `func (d *ResourceData) IsSetInConfig(key string) bool` or something would be useful!

So the history here is that `GetOk` at once point _claimed_ to be able to tell whether a value existed in the state, but it turned out to be broken. So in #993 we "fixed the glitch" in part by changing up the semantics of `GetOk` such that `ok` meant "non-zero" instead of the claimed-but-broken "present in config".

As @mitchellh mentioned there [in a comment](https://github.com/hashicorp/terraform/pull/993#issuecomment-74791008):

> ...you can't tell if something is _set or not_. I looked around, and I don't think anything wanted this behavior (in builtins). If we want to support that in the future I think it'll require core changes to annotate the Diff about where the data came from.

So this issue can be the home for the fact that we do indeed want to support that in the future. :grin: As Mitchell says, it'll be a decent amount of work to thread through metadata in the diff such that we can properly detect absence from config vs default values. But I think it's probably worth it for the benefit it gives to provider authors.

**Comment by stack72** [comment]
This is going to solve quite a few issues regarding setting of 0. I have linked a few that I have found so far

**Comment by ab** [comment]
Anything that would be useful to help with / test out here? Just ran into #5681.

**Comment by brycefisher** [comment]
I just ran into https://github.com/hashicorp/terraform/issues/5069 when trying to provision DNS MX records on DigitalOcean. Is this issue resolved in master?

**Comment by jbmchuck** [comment]
+1, ran into this in another context.

**Comment by apparentlymart** [comment]
In #15723 we added `GetOkExists`, which does _approximately_ what was requested here.

We suspect it has some caveats on edge-cases where something is removed when already set to the default in the state, due to some details of how diffs and state are represented internally. In practice, it seems like it's been working well enough to be useful in the main case, and the remaining caveats should be dealt with via some long-term work to improve how we represent diffs and state so that "unset" is a separate idea from the zero value.

Since the broader work on the internal representations of things is on our radar (though not actually a GitHub issue, since it's a bit too broad/undefined at this time) and we've seen some success using `GetOkExists` in spite of the theoretical quirks, I'm going to close this issue. If people find issues related to the edge-cases I alluded to above then I'd encourage reporting them as separate, new issues where we can more easily get into the details.
