### ISSUE TITLE
AWS: Can't update certificate associated with ELB

### ISSUE THREAD

**Issue by saliceti** [hashicorp/terraform#5713]
Tested on terraform 0.6.13

This happens when an IAM is already associated with an ELB, and you try to upload a new certificate.

The certificate is not updated but deleted and recreated. Terraform complains that it is already associated with an ELB. It doesn't try to recreate the ELB.

The workaround is to delete the ELB manually.

```
aws_iam_server_certificate.logsearch: Destroying...
[...]
* aws_iam_server_certificate.logsearch: DeleteConflict: Certificate: ASCAJMZ2C7D5UUOIU7HMA is currently in use by arn:aws:elasticloadbalancing:eu-west-1:595665891067:loadbalancer/colin-march-logsearch-elb. Please remove it first before deleting it from IAM.
	status code: 409, request id: 65fe377d-ed00-11e5-a5db-2734c0d2c9f8
```

**Comment by stack72** [comment]
Hi @saliceti,

Thanks for the bug report. Please can you share a sample of your config (minus secrets) that can help us recreate this issue?

Paul

**Comment by saliceti** [comment]
Of course:

```
resource "aws_iam_server_certificate" "logsearch" {
  name = "${var.env}-logsearch"
  certificate_body = "${file("logsearch.crt")}"
  private_key = "${file("logsearch.key")}"
}

resource "aws_elb" "logsearch_elb" {
  name = "${var.env}-logsearch-elb"
  subnets = ["${split(",", var.infra_subnet_ids)}"]
  idle_timeout = "${var.elb_idle_timeout}"
  cross_zone_load_balancing = "true"
  security_groups = [
    "${aws_security_group.logsearch_elb.id}",
  ]

  health_check {
    target = "TCP:5602"
    interval = "${var.health_check_interval}"
    timeout = "${var.health_check_timeout}"
    healthy_threshold = "${var.health_check_healthy}"
    unhealthy_threshold = "${var.health_check_unhealthy}"
  }

  listener {
    instance_port = 5602
    instance_protocol = "http"
    lb_port = 443
    lb_protocol = "https"
    ssl_certificate_id = "${aws_iam_server_certificate.logsearch.arn}"
  }
}
```

**Comment by catsby** [comment]
Hey @saliceti – 

The trick here is to use the `lifecycle` block, and add `create_before_destroy`. Ex:

```hcl
resource "aws_iam_server_certificate" "test_cert" {
  name_prefix = "${var.env}-logsearch-"
  certificate_body = "${file("logsearch.crt")}"
  private_key = "${file("logsearch.key")}"

  lifecycle {
    create_before_destroy = true
  }
}
```

Two important parts that make this possible:

- The `lifecycle` block here instructs Terraform that it needs to create a new resource, before it tries to destroy the old one. This allows you to create a new certificate, update the ELB with the new one, and then destroy the old, thus avoiding this dependency error. 
- Using `name_prefix` instead of `name`: this allows Terraform to generate a unique name for your resource, avoiding name conflicts when it tries to create the new resource prior to destroying the current one. The `name_prefix` allows you to prefix the name with something meaningful, but still allows us to add uniqueness to the end.

I'm going to close this, let m know if you have any other questions, or if this doesn't solve your problem!

**Comment by saliceti** [comment]
Hi @catsby thanks for the detailed explanation, I will give it a try.

Any reason why this is not default behaviour in terraform?

Could this be documented, maybe in [iam server certificate](https://www.terraform.io/docs/providers/aws/r/iam_server_certificate.html) as this looks like a common use case.

**Comment by catsby** [comment]
Hey @saliceti –

It can be difficult to determine _when_ Terraform should make this a default behavior, and when it should not. E.g. when should it go out of it's way and make this kind of lifecycle decision for you, and when should it just stop and give you an error. Hopefully in the future we'll have a better picture of that, but for now we'd rather default to not making big choices like that for you.

In the meantime, I've sent https://github.com/hashicorp/terraform/pull/5887 as a PR to the documentation, that explains this situation for IAM Server Certs and provides example config. Hopefully that is helpful to others in the future.

Sorry for the trouble!

**Comment by saliceti** [comment]
Good work. Thanks @catsby!
