### ISSUE TITLE
aws_instance : Can we wait for "shutting-down" instead of "terminated" state when destroying resource?

### ISSUE THREAD

**Issue by shanielh** [hashicorp/terraform#5742]
This is the lifecycle of ec2 instance: 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

It states that after "terminating" an instance it goes into the `shutting-down` state and after full termination it goes to `terminated` state.

The code that waits for `terminated` state is here : 

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L1083

So, I think that's possible to change it to wait for `terminated` / `shutting-down` state. Another question that rises is whether it interrupt to other resources (like connected volumes and network interfaces).

Oh, And the reason I would like to wait for `shutting-down` state and not `terminated` is because it became slow :disappointed:

**Comment by jen20** [comment]
Hi @shanielh! Thanks for opening an issue. I don't think this is a good idea at this stage, because if an instance is only in the "shutting down" state, it is not actually gone (as you point out), and so resources which depend on it being gone (e.g. a subnet or a VPC) cannot be destroyed. I am willing to be convinced otherwise however - if you have a good way of avoiding this please reopen the issue!

**Comment by shanielh** [comment]
Hi @jen20, Thanks for the fast answer. You're probably right and know about this more than I do, My terraform scripts does contain volumes, vpc's and instances that depend on instances. Most of the "destruction" time is consumed by waiting for `terminated` state. When instances are waiting for other instances, It might slow the destroy operation really badly. I hope that someday AWS will fix it, or that terraform will wait for shutting down state and continue as much as possible until it must wait for shutdown (destroying VPCs, volume attachments, etc'...).
