### ISSUE TITLE
Directory service creation exports malformed DNS IP addresses

### ISSUE THREAD

**Issue by saswatp** [hashicorp/terraform#5837]
One of the exported attribute after creation of directory service is a list of DNS IP address for that directory service. This piece seems to be broken. When I create a directory service and print the output , it comes malformed . Directory service gets created fine but DNS server IP comes like the following : 

B780FFEC-B661-4EB8-9236-A01737AD98B610.0.10.105B780FFEC-B661-4EB8-9236-A01737AD98B610.0.90.46B780FFEC-B661-4EB8-9236-A01737AD98B6

Here is the terraform version : terraform version
Terraform v0.6.15-dev (b20f680cbf0505825e6ae173c5986243683d8eb3)

v0.6.13 release version also has the same problem.

This issue should be easily reproduced using the example code in documentation page.

```hcl
resource "aws_directory_service_directory" "sse-ad-service" {
  name = "${var.ad_service_domain}"
  password = "${var.ad_service_password}"
  size = "${var.ad_service_size}" 

  vpc_settings {
    vpc_id = "${var.vpc_id}"
    subnet_ids = ["${split(",", module.subnets.subnet_ids)}"]
  }
}

output "ad_service_dns"  { 
    value = "${aws_directory_service_directory.sse-ad-service.dns_ip_addresses}" 
}
```

_formatting update by catsby_

**Comment by catsby** [comment]
Hey @saswatp – The DNS IP Addresses are a _set_, so you need to **join** them for the output:

```hcl
# old
output "ad_service_dns" {
  value = "${aws_directory_service_directory.sse-ad-service.dns_ip_addresses}"
}

#new
output "ad_service_dns_joined" {
  value = "${join(",",aws_directory_service_directory.sse-ad-service.dns_ip_addresses)}"
}
```

Output:

```
Outputs:

ad_service_dns = B780FFEC-B661-4EB8-9236-A01737AD98B610.1.1.10B780FFEC-B661-4EB8-9236-A01737AD98B610.1.3.252B780FFEC-B661-4EB8-9236-A01737AD98B6
ad_service_dns_other = 10.1.1.10,10.1.3.252
```

Sorry for the confusion! Let us know if you need anything else :smile:

**Comment by saswatp** [comment]
Cool , Thanks ! It would be nice if you updated the documentation.

**Comment by aaomoware** [comment]
the above didn't work for me... 

passing the returned  value of join to the aws_route53_record's records attribute failed. Rightly so. 

Solution: split() the return value of join. The return value of join, in this case, is "0.0.0.0,0.0.0.0"

resource "aws_route53_record" "badboy-ad" {
   zone_id = "${var.simpleAD_m_route53_zone_id}"
   name = "${var.simpleAD_m_route53_name}-${var.env_colour}"
   type = "${var.simpleAD_m_route53_type}"
   ttl = "${var.simpleAD_m_route53_ttl}"
   records = ["${split(",",(join(",",aws_directory_service_directory.simpleAD.dns_ip_addresses)))}"]
}

https://www.terraform.io/docs/configuration/interpolation.html
"split(delim, string) - Splits the string previously created by join back into a list. This is useful for pushing lists through module outputs since they currently only support string values."
}


hope it helps..
