### ISSUE TITLE
feature request: syntax sugar for time related numbers

### ISSUE THREAD

**Issue by conorgil** [hashicorp/terraform#5985]
I just updated some hard coded values in my Terraform files from "magic numbers" to something more readable after reviewing the [Configuration syntax](https://www.terraform.io/docs/configuration/syntax.html). For example, changing `262144` into `256Kb`. It would be awesome if there were some additional syntax sugar for handling magic numbers related to time.

For example:

```
resource "aws_sqs_queue" "my_queue" {
  name = "my_queue"
  delay_seconds = 0
  visibility_timeout_seconds = 30

  # old magic number
  max_message_size = 262144

  # updated for readability
  max_message_size = 256Kb

  # this is what I have now
  message_retention_seconds = 1209600  # 14 days

  # this would be great
  message_retention_seconds = 14days

  receive_wait_time_seconds = 20
}
`

The above example assumes that `14days` would be turned into seconds. However, it might require additional thought if there are use-cases where users would expect it to be turned into milliseconds or something else.

Food for thought.
```

**Comment by teamterraform** [comment]
Hi @conorgil! Thanks for sharing this use-case, and sorry for the long silence here.

We considered the idea of adding explicit units to the language as part of the improvements for Terraform 0.12, but ultimately elected not to implement this feature.

This sort of decision is always a tradeoff between making the language more expressive and giving Terraform itself more information vs. the amount a user has to learn in order to read and understand a Terraform configuration. While united dimensions are useful in some particular cases, in practice it seems that they haven't come up enough to justify the additional complexity of a first-class language feature.

Instead, this joins a number of other situations that Terraform aims to handle by convention rather than via an explicit feature. By this we mean that Terraform Core itself and multiple providers all "agree" on a particular primitive representation of a certain idea. A prominent existing example is that timestamps in Terraform are conventionally represented as strings of the form `YYYY-MM-DDThh:mm:ssZ`, and although that isn't a first-class type in the language, the date/time-related built-in functions and timestamp fields in providers all agree on this representation and can thus be composed without any special effort.

Similarly, Terraform has a convention for representing durations which is canonically represented by the second argument to [`timeadd`](https://www.terraform.io/docs/configuration/functions/timeadd.html). Durations haven't come up in practice in providers nearly as often as timestamps have (and timestamps are already quite rare), so there aren't so many examples, but if a provider _does_ need to represent a duration then we'd encourage using the same duration microsyntax.

There isn't yet a convention for representing storage sizes measured in multiples of bytes, which is unfortunate since they seem to be more common than timestamps. This is likely because Terraform itself doesn't have any built-in functions dealing specifically with these, and instead they are most commonly handled using normal arithmetic.

We're going to close this now to represent the decision not to include an explicit unit syntax in the language. Thank you for sharing the use-case, and hopefully the above rationale makes sense for why we made the decision we did here.
