### ISSUE TITLE
Integrate terraform plan with cloudformation changesets

### ISSUE THREAD

**Issue by torfredrik** [hashicorp/terraform#6014]
When a cloudformation stack is changed in terraform the `terraform plan` only shows a change to the stack, it would be useful to know the underlying resource changes that will occur. An easy way to add this feature is using [cloudformation change sets ](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets.html).

**Comment by chenrui333** [comment]
That would be a nice feature. #

**Comment by apparentlymart** [comment]
Seems like a potential use-case for #8769, though it doesn't fit all that great with my current framing of the problem since it looks like a CloudFormation changeset is a first-class object whose lifecycle ought to be managed, rather than just something we can create during plan and then leave dangling.

**Comment by torfredrik** [comment]
That is correct, cleaning up the change set after a plan should be the way to go about it.

**Comment by lorengordon** [comment]
> That is correct, cleaning up the change set after a plan should be the way to go about it.

That seems wrong to me... if you create a changeset in the plan, then you should execute the changeset in the apply.
