### ISSUE TITLE
openstack_networking_subnet_v2 creating gateway address

### ISSUE THREAD

**Issue by linuxus** [hashicorp/terraform#6031]
Hello,
when using openstack_networking_subnet_v2 resource it creates the gateway_ip address in the subnet although I did not specifically set this as gateway_ip option. This creates an issue when using multiple subnets and attaching them to instances (VMs) as multiple network interfaces. The operating system sees 2 default gateways and sometimes the routing logic do not work as intended. For example eth0 should have the real default gateway but eth1 gets higher metric and because a gateway is set on the subnet's dhcp via terraform network traffic has unexpected behaviour.

How can we turn off gateway_ip to none via terraform if we do not want a default gateway setting on a particular subnet?

Thanks,
Abdi

**Comment by jtopjian** [comment]
@linuxus Coincidentally I ran into this same problem, even before seeing your issue 😄 

I have a PR opened in both Terraform and Gophercloud to resolve this. Hang tight!

**Comment by linuxus** [comment]
@jtopjian Excellent... thanks for the update. I'm assuming there is no value to set on this attribute but just a key in the resource config.

**Comment by jtopjian** [comment]
@linuxus The patch has been merged and will be in the next release of Terraform. In order to disable the gateway, you'll need to set the following new attribute on the subnet:

```no_gateway = true```

The reasons for the new attribute and not just building onto the `gateway_ip` attribute are:

1. Similar behavior with the Neutron client package
2. Having no value on `gateway_ip` will cause Neutron to create a default gateway implicitly.

Let me know if you have any questions or issues 😄
