### ISSUE TITLE
[aws][bug] Ambigious error message when trying to delete ebs volume

### ISSUE THREAD

**Issue by thebenwaters** [hashicorp/terraform#6038]
Terraform v0.6.14
```
terraform plan -destroy -target module.name
```
```
aws_ebs_volume.xxxxxx: Error reading EC2 volume vol-XXXXXXX: &awserr.requestError{awsError:(*awserr.baseError)(0xc820407600), statusCode:403, requestID:""}
````

**Comment by apparentlymart** [comment]
Hi @thebenwaters,

This one looks like a straightforward error: [the format string](https://github.com/hashicorp/terraform/blob/d1ac7d3b2e1be2f32092275340f33a2d73f7b31a/builtin/providers/aws/resource_aws_ebs_volume.go#L189) for this error message is using `%#v` (show full data structure) rather than `%s` (show string representation).

**Comment by apparentlymart** [comment]
Thanks for creating this issue, @thebenwaters! I checked in a quick fix, which should hopefully take care of this.
