### ISSUE TITLE
question on ignoring uuid

### ISSUE THREAD

**Issue by thebenwaters** [hashicorp/terraform#6040]
```
resource "aws_route53_zone" "name" {
	name = "name.com"
    lifecycle {
        ignore_changes = ["name_servers"]
    }
}
```

My output is always
```
nameservers = B780FFEC-B661-4EB8-9236-A01737AD98B6[NAMESERVER]B780FFEC-B661-4EB8-9236-A01737AD98B6[NAMESERVER]B780FFEC-B661-4EB8-9236-A01737AD98B6[NAMESERVER]B780FFEC-B661-4EB8-9236-A01737AD98B6[NAMESERVER]B780FFEC-B661-4EB8-9236-A01737AD98B6
```

I just want a list of the [NAMESERVER] how can I get rid of the uuid? I thought the ignore changes would ignore it

**Comment by apparentlymart** [comment]
Hi @thebenwaters,

I assume you also have a block like this in your config:

```js
output "nameservers" {
    value = "${aws_route53_zone.name.nameservers}"
}
```

In which case, this looks like the same issue we were discussing over in #5999. I posted a comment in that issue with a workaround; in the forthcoming major release 0.7 Terraform will get first-class support for lists that should make it do what you expected here.

I'm going to close this issue to consolidate around #5999, but if it turns out that my assumption above is wrong and this is a different issue then we can certainly re-open it.

**Comment by thebenwaters** [comment]
Thank you!
