### ISSUE TITLE
provider/aws : Opsworks fails on update

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#6077]
Opsworks fails during updates:

```shell
Error applying plan:

1 error(s) occurred:

* aws_opsworks_stack.main: ValidationException: Custom Cookbooks Source's Type: Unsupported scm type
        status code: 400, request id: *snip*
```

This is due to the provider "computing" empty fields and adding it to the JSON request:

```shell
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:   CustomCookbooksSource: {
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Password: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Revision: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     SshKey: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Type: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Url: "",
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:     Username: ""
2016/04/07 19:17:06 [DEBUG] terraform-provider-aws:   },
```

**Comment by catsby** [comment]
Hey @u2mejc – do you have a simple config that demonstrates this problem? The `computed` flag tells Terraform that the API may return data and to not worry about it; the resource itself is not populating empty data on it's own. Or, it shouldn't :smile: 

I did some debugging, and found that the `CustomCookbooksSource` source that's returned from `DescribeStacks` call [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_opsworks_stack.go#L255) is coming back empty, instead of the typical `nil`. As a result we're storing empty values when we should omit it if nothing there is found. Do you think you could adjust #6078 to account for that?

**Comment by u2mejc** [comment]
Please see comments in PR: https://github.com/hashicorp/terraform/pull/6078
