### ISSUE TITLE
Blocked: Unable to pass a hash map to a Module

### ISSUE THREAD

**Issue by codeweft** [hashicorp/terraform#6084]
I am creating vpc and subnet's in multiple zones based on available zones for a region. My tfvars file is:
```
zone_count = "2"
zones.zone0 = "us-east-1a"
zones.zone1 = "us-east-1b"
zones.zone3 = "us-east-1c"
```
tfvars is different for different environments. zone_count  is used to decide the number of zones to create a subnet in a specific region i.e  if zone count is 2, I end up creating subnet in zone0 and zone1 and not in zone3

My module for creating the subnet accepts the zone_count and zones and eventually spit's out the vpc and subnet id's, used eventually to create a bastion instance. Due to this limitation I am unable to pass multiple zones as a map from my calling module.

This is a major blocker for me. Any workaround or help would highly appreciated

**Comment by jrnt30** [comment]
There is a workaround which you could use in the meantime.  Instead of relying on multiple variables as input, you can use a comma separated list for your zone listing and then use interpolation to select the appropriate versions.  Similar issue/example to: 

https://github.com/hashicorp/terraform/issues/6239#issuecomment-213006703

**Comment by codeweft** [comment]
Thanks for the response. I ended up using the workaround for this. I can understand that this is probably because of the limitations of HCL itself. I wonder why HCL was developed the way it is. Ruby would have been best suited and more flexible for writing tf scripts.

**Comment by mitchellh** [comment]
This is now possible with native lists/maps in 0.7.0
