### ISSUE TITLE
Feature: AWS KMS Encryption / Decryption Provider

### ISSUE THREAD

**Issue by coen-hyde** [hashicorp/terraform#6133]
Hi,

It would be quite useful if a KMS encryption provider existed. Similar to the template provider but encrypts the input. My use case is to encrypt sensitive data with a kms key and put it in the user_data script. Currently I am uploading the encrypted data to s3 and downloading it on to the machine on boot. However for small amounts of data it would be nicer to just put the encrypted data in the user_data.

**Comment by stack72** [comment]
Hi @coen-hyde 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
