### ISSUE TITLE
Too many providers in core package

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#6134]
I see more and more providers to be included in default terraform package and they vary a lot: from DNS services (there are 4 already) to generic OSS databases (influx, postgresql). 

Even today it looks a bit bloated with providers and the size of all of them combined is quite big. Not saying also that testing them (acceptance tests) all inside main repo is probably a difficult and slow task to do.

Is there a plan to make terraform really modular? Would be great to have some workflow for installing providers from elsewhere, in a way similar how programming dependenices are resolved (see rubygems, pip etc). And then leave core of terraform with only core ( :) ) providers and move all the rest in separate repos. 

What do you think about? Does it make sense?

**Comment by apparentlymart** [comment]
@Fodoj part of this is planned to be addressed by #6013, which will embed all of the default providers inside the main Terraform binary rather than having a separate binary for each plugin.

Terraform is currently going for a "batteries included" distribution model somewhat like the Linux kernel. 

This definitely has some downsides... for example, the structure of the documentation on the website is currently straining to scale to this many providers/resources and should probably be reworked if this path continues. But it also has some benefits: a broad base of support in the Terraform core means that most users don't need to install anything except the main distribution in order to make use of Terraform, and it's very easy to describe what's needed by just specifying what Terraform version is required for a particular configuration... no dependency hell, no package management headaches, etc.

Centralized acceptance testing creates a broad base of plugins creates a baseline of quality that could not be assumed if the ecosystem were a variety of packages in different states of development by different people.

I'm only speaking for myself here and I can't speak to Terraform's roadmap, but I like the current model. It's likely its limit will be found eventually, but I personally don't think we've got there yet.

**Comment by Fodoj** [comment]
Thanks, looks like #6013 will improve situation quite a bit.
