### ISSUE TITLE
aws_db_security_group makes a modify on every subsequent plan/apply.

### ISSUE THREAD

**Issue by Vidimensional** [hashicorp/terraform#6158]
### Terraform Version

```
$ terraform -version
Terraform v0.6.14
```
### Affected Resource(s)
- aws_db_security_group
### Terraform Configuration Files

[Complete config file](https://gist.github.com/Vidimensional/4bb02abd383f0aeb7be5652e5939c2e1)

``` hcl
(...)
resource "aws_db_security_group" "postgres" {
  name        = "postgres-securitygroup"
  description = "RDS PostgreSQL security group"

  ingress {
    security_group_id     = "${aws_security_group.example.id}"
    security_group_owner_id = "${aws_security_group.example.owner_id}"
  }
}
(...)
```
### Debug Output

https://gist.github.com/Vidimensional/b8c460b43905cc18a63b3741f970592e
### Expected Behavior

When we execute a `terraform plan` after a `terraform apply` (without editing anything on the config files, of course), the planning shouldn't show anything to change.
### Actual Behavior

Every time we execute `terraform plan` after a `terraform apply` it suggests a change on `aws_db_security_group`:

```
~ aws_db_security_group.postgres
    ingress.2906156442.cidr:                    "" => ""
    ingress.3436579327.cidr:                    "" => ""
    ingress.3436579327.security_group_id:       "" => "sg-1a6c7070"
    ingress.3436579327.security_group_name:     "" => "<computed>"
    ingress.3436579327.security_group_owner_id: "" => "709693308983"
```
### Steps to Reproduce
1. Using the provided configuration.
2. `terraform apply`
3. `terraform plan`
### Important Factoids

This case is using EC2 classic networking.

**Comment by xsb** [comment]
I did some tests based on this scenario and can confirm that this only happens when the ingress rule points to an EC2 security group, I only tried with EC2 Classic. The bug doesn't appear if the rule points to a CIDR, in that case the lifecycle of the rule is correct.

`terraform apply` tries to create a new ingress rule at each execution. That's easy to check because the rule being created have a different ID than the one in the status file although there are no actual changes in the code.
