### ISSUE TITLE
Allow the PUT method in the http remote state backend

### ISSUE THREAD

**Issue by aespinosa** [hashicorp/terraform#6190]
This is in addition to the POST method in https://github.com/hashicorp/terraform/blob/master/state/remote/http.go#L135

My use case is I want to use Nexus [1](or any WebDAV enabled server) to store my remote state in.  As I understand, for WebDAV, placing individual files needs the PUT method instead of POST [2].

Allowing the http backend's `Put()` method to be configured to send PUT requests should be able to address this, I think. Unless you folks think that having a separate webdav backend makes more sense moving forward.

[1] https://books.sonatype.com/nexus-book/3.0/reference/raw.html#_uploading_files_to_hosted_raw_repositories
[2] http://www.webdav.org/specs/rfc2518.html#rfc.section.8.5

**Comment by miked0004** [comment]
+1 for this feature or a Nexus remote state backend

**Comment by rhoml** [comment]
+1 This feature is so needed.

From my perspective I can't use Atlas, or S3 because of INFOSEC concerns, we can't use consul either because of the 512kb limit on the K/V which we will hit pretty fast and we don't want to move from nexus into artifactory just to support Terraform. So been able to implement Nexus would simplify our workflow a lot. Because we don't feel so confident about git either.

**Comment by awwright** [comment]
PUT is the correct method to be using.

POST isn't guaranteed to update the resource... it might delete the resource, it might create a totally unrelated resource, it might do nothing at all. This is a really dangerous HTTP method to be calling by default.

**Comment by apparentlymart** [comment]
Hi all,

Since Terraform v0.10.3 this backend has supported [`update_method`](https://www.terraform.io/docs/backends/types/http.html#update_method) as a way to select a different method for updating remote state.
