### ISSUE TITLE
Google Cloud Dataproc resource

### ISSUE THREAD

**Issue by shpsec-dennis** [hashicorp/terraform#6312]
Hi there,

Feature request for having a dataproc\* resource(s) for Terraform. 

https://cloud.google.com/dataproc/

Regards,

Dennis O.

**Comment by eladamitpxi** [comment]
+1

**Comment by maartenvandenbogaard** [comment]
would be great.

**Comment by ppodolny** [comment]
+1

**Comment by danawillow** [comment]
Hey all, I'm starting to look into this and would love some opinions of what your expectations are for a dataproc resource- what the types would be, what configuration parameters you need, etc. I'm also making the assumption that destroying the job resource should correspond to deleting it (rather than just canceling it), but would appreciate opinions there too.

cc @joe-boyce since I think you/people you know are interested.

**Comment by joe-boyce** [comment]
Thanks @danawillow, i'll make the relevant parties aware of this ticket and will get their input

**Comment by grubernaut** [comment]
Hey @danawillow, okay to assign this one to you given your previous comment?

**Comment by danawillow** [comment]
Sure! Just assigned to myself.
