### ISSUE TITLE
Empty JSON objects were ignored, now give error

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#6368]
### Terraform Version

Terraform v0.6.16-dev (0194cfda0afb53702985730a54bfef608b9b4eeb)
### Affected Resource(s)

core
### Terraform Configuration Files

``` json
{
    "resource": {
        "google_compute_disk": {},
    }
}
```
### Debug Output

```
test.tf: position -: resource must be followed by exactly two strings, a type and a name
```
### Expected Behavior

Should ignore the empty object (this was the old behavior).  I do not know when the regression occurred.

**Comment by dev-head** [comment]
I am seeing this behavior as well. I think the default behavior would be for terraform to accept it and allow us to turn down the previously defined resources. 

Terraform Version
------------------
```
Terraform v0.7.4
```

Terraform Config (partial to show where i'm using it)
-----------------

```
{
  "resource": {
    "aws_elb": {}
  }
}
```

Output
-------
```
Error loading config: Error loading tf.json: position -: resource must be followed by exactly two strings, a type and a name
```

**Comment by apparentlymart** [comment]
Hi all! Sorry for the long silence here.

Given that this behavior has been in place for some time now, I think we will accept it as the expected behavior and close it. We've been moving towards having the JSON-based parser be more strict in what it accepts in order to give better feedback on correct usage, and this seems consistent with that even though it was apparently at the time an unexpected change.

In the forthcoming v0.12 release there will at least be a more informative error message for this situation, that is more tailored to the JSON syntax.

![](https://user-images.githubusercontent.com/20180/48106204-5720c980-e1ef-11e8-9f88-01afe6830037.png)
