### ISSUE TITLE
`terraform fmt` adds extra lines in comment blocks

### ISSUE THREAD

**Issue by BrianHicks** [hashicorp/terraform#6375]
### Terraform Version

```
$ terraform -v
Terraform v0.6.15
```
### Affected Resource(s)

n/a
### Terraform Configuration Files

``` hcl
# this is a long comment block spanning multiple lines. I would expect
# `terraform fmt` to keep the lines together, but it doesn't.
```
### Debug Output

https://gist.github.com/BrianHicks/45196caa7824eb6758ea071ecf2974b0
### Expected Behavior

The comment block should have been left intact, as in the sample above.
### Actual Behavior

Actual output:

``` hcl


# this is a long comment block spanning multiple lines. I would expect


# `terraform fmt` to keep the lines together, but it doesn't.

```

All newlines included.
### Steps to Reproduce
1. paste the above configuration into `x.tf`
2. run `terraform fmt x.tf`
3. observe the resulting file contents
### Important Factoids

Installed via homebrew
### References

Couldn't find any.

**Comment by dcarley** [comment]
There's an issue and PR in the upstream parser for this:
- hashicorp/hcl#108
- hashicorp/hcl#113

**Comment by dangerp** [comment]
I ran into this issue as well, and I found a fairly simple workaround.  For any multiline comments that are not attached to a resource (meaning there is an empty line between the comment and the resource), simply use the HCL syntax for a multiline comment instead of multiple single line comments.  For example, instead of

```
# this is a long comment block spanning multiple lines. I would expect
# `terraform fmt` to keep the lines together, but it doesn't.
```
do this instead:
```
/*
this is a long comment block spanning multiple lines. I would expect
`terraform fmt` to keep the lines together, but it only does so if you use 
proper multiline comment syntax
*/
```

As far as I can tell, the hcl printer is treating each standalone comment line as a separate comment, therefore they are separated by empty lines.  I would still consider this a bug in hcl, but at least I can use `terraform fmt` without spurious empty lines being added.

**Comment by mitchellh** [comment]
This is fixed!
