### ISSUE TITLE
using splat within a connection to get self.private_ip doesn't work.

### ISSUE THREAD

**Issue by kuberkaul** [hashicorp/terraform#6450]
Hi there,

Terraform v0.6.15

Affected Resource(s)
Please list the resources as a list, for example:
- connection

``` hcl
# The Google Compute Engine Instance Group Manager API creates and manages pools of homogeneous Compute Engine virtual machine instances from a common instance template
resource "google_compute_instance_group_manager" "djin-dev-search" {
  name        = "djin-dev-search-instances"
  description = "This is compute instances group manager for instances while scaling. This is spawned off the template"

  base_instance_name = "djin-dev-search"
  instance_template  = "${google_compute_instance_template.djin-dev-search.self_link}"
  update_strategy    = "NONE"
  zone               = "us-east1-b"

  #target_pools = ["${google_compute_target_pool.foobar.self_link}"]
  target_size  = 2

  named_port {
    name = "https"
    port = 443
  }

  named_port {
    name = "ssh"
    port = 22
  }


  named_port {
    name = "http"
    port = 80
  }

  provisioner "file" {
    source = "${var.install_script_src_path}"
    destination = "${var.install_script_dest_path}"
    connection {
      type = "ssh"
      user = "xyz"
      host =  "${self.private_ip}"
      private_key = "${file("${var.private_key_path}")}"
      agent = false
    }
  }

  /*provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "xyz"
      host =  "${self.private_ip}"
      private_key = "${file("${var.private_key_path}")}"
      agent = false
    }
    inline = [
      "chmod +x ${var.install_script_dest_path}"
    ]
  }
}
```
### Debug Output

Error applying plan:
1 error(s) occurred:
- Resource 'google_compute_instance_group_manager.djin-dev-search.0' does not have attribute 'private_ip' for variable 'google_compute_instance_group_manager.djin-dev-search.0.private_ip'

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
### Important Factoids

**Running this for Google Cloud Platform.**

The issue is here : `host =  "${self.private_ip}"`
How do I use splat is such a scenario to get private_ip for both the vm's created. Also, is the keyword not private_ip for getting the internal ip of instances ? 

I also tried : `${self.*.private_ip}`

**Comment by kuberkaul** [comment]
@phinze  - Any workaround for this or am I missing something here ?

**Comment by kuberkaul** [comment]
@jen20 @mitchellh  - ping ?

**Comment by apparentlymart** [comment]
Hi @kuberkaul,

I don't really know the Google Cloud stuff at all, but since nobody more knowledgeable responded I'll take a stab at this.

The error message is trying to tell you that the resource `google_compute_instance_group_manager` doesn't have an attribute called `private_ip`, which seems to be true according to the documentation. So as far as I can tell, Terraform is behaving as expected here.

However, I think what you're really asking here is a more general question: how can you use Terraform to provision the instances implicitly created by the instance group manager resource? Unfortunately I think that the answer for now is that you can't; in order to do this, you'd need to be able to retrieve the created instance group, retrieve each of the instances, and then get their IP addresses from there... and right now that sort of complexity cannot be represented in Terraform.

In the future it may be possible for us to add *data sources* -- a new concept coming in 0.7 -- that would allow you to read the data needed here and then use it to configure a provisioner, but it would still require considerably more configuration than I expect you would like.

In the mean time, if you need to run provisioners here you may need to instead create individual instances with Terraform, such that Terraform can then "see" their IP addresses in order to provision them.

**Comment by kuberkaul** [comment]
Thanks @apparentlymart

**Comment by mitchellh** [comment]
Answered

**Comment by gremlin961** [comment]
In case anyone in the future comes across this, you can get the private IP of the instance using
host = "${self.network_interface.0.network_ip}"

Replace 0 with the number of the NIC if using multiple interfaces.
