### ISSUE TITLE
Remote States - ${path.module{ hardcodes the full machine path in the state file (intended?)

### ISSUE THREAD

**Issue by mechastorm** [hashicorp/terraform#6459]
I was wondering is this intended and is it something we need to take into account when adopting remote states. 

We are currently adopting remote states for our usage of terraform and having Jenkins run our terraform plan and apply commands to simplify auditing and controls. 

What we have found is on terraform stacks that use the ${path.moduel}, the value is hardcoded on the tfstate file. This complicates matter when we run terraform apply on another location as this is usually run on another location/machine that would not have access to the locaiton where terraform plan was run.

Is this expected behaviour and something we should take into account for when using remote states?

### Terraform Version
0.6.15

### Affected Resource(s)
path.module - mostly usage in template_file

### Expected Behavior
Unknown

### Actual Behavior
The tfstate file has the path to the file hardcoded

### Steps to Reproduce
Run terraform plan on Machine A and generate a plan
Run terraform apply on Machine B with the generated plan

**Comment by apparentlymart** [comment]
Hi @mechastorm! Thanks for this question.

In general we've been moving away from including filenames directly in Terraform configs for a number of reasons, including this one. Instead, we now prefer to make an attribute for the file's *contents* and use the `file(...)` to fill it, so that it's the contents rather than the filename that get written into the state.

For `template_file` in particular, the recommendation is now to use the `template` argument instead of the `filename` argument:

```hcl
resource "template_file" "init" {
    template = "${file("${path.module}/init.tpl")}"

    vars {
        consul_address = "${aws_instance.consul.private_ip}"
    }
}
```

**Comment by phinze** [comment]
@apparentlymart's comment here is precisely the direction we are heading in - if you have a specific example that you're having trouble with we can help you figure out how to refactor it to deal in file contents rather than paths.

In the meantime I'm going to close this as answered! 👍
