### ISSUE TITLE
Docker images don't get updated on instance 

### ISSUE THREAD

**Issue by hnarimani** [hashicorp/terraform#6486]
### Terraform Version
Terraform v0.6.9
### Affected Resource(s)
 aws_instance

Hi,
I  updating frequntly the Container images and after that terraform apply , every thing work fine but image don't get update on instance.

I have to manually reboot the instance to get image updated. 

Please help on this issue .
 Thanks

**Comment by hnarimani** [comment]
Any update please?

**Comment by stack72** [comment]
Hi @hnarimani 

Apologies that no one has gotten back to you here. If you can, please can you post the terraform configuration (minus any sensitive information) so that we can try and understand what the error is?

Is the error related to aws_instance or docker containers (as the title suggests)?

Thanks

Paul

**Comment by stack72** [comment]
Hi @hnarimani 

I am going to go ahead and close this out - if you feel this is still an issue then please do post the config that you had for this so we can try and recreate it

Thanks

Paul
