### ISSUE TITLE
elb fails to add to state if health check fails during 

### ISSUE THREAD

**Issue by thebenwaters** [hashicorp/terraform#6496]
Hi there,
### Terraform Version

```
Terraform v0.6.15
```
### Affected Resource(s)
- aws_elb
### Debug Output

```
Error applying plan:

1 error(s) occurred:

* aws_elb.dev_elb: Failure configuring health check for ELB: ValidationError: 1 validation error detected: Value '1' at 'healthCheck.unhealthyThreshold' failed to satisfy constraint: Member must have value greater than or equal to 2
        status code: 400, request id: 9ebd9952-12a8-11e6-860e-37a14da199da
```
### Expected Behavior

The elb should have been added to the state
### Actual Behavior

Elb was created, but not added to state
### Steps to Reproduce

Create an elb that will have an unhealthy startup
### Important Factoids

This is more of an issue with the AWS api. It returns an error but still creates, but it says specifically health check instead of delb

**Comment by apparentlymart** [comment]
Hi @thebenwaters!

This is a funny one. While creating an `aws_elb` we first create the load balancer and [use partial state to save what we did so far](https://github.com/hashicorp/terraform/blob/6ac312e682819b2241077c5dd4bce6c24e47856b/builtin/providers/aws/resource_aws_elb.go#L280), and then we run the `Update` logic to take care of all the things that require additional API calls.

At first glance it seems like the partial state mechanism isn't working properly here, since the code looks like it's doing the right thing. However, I'm going to leave the "provider/aws" tag on this until someone has delved a little deeper and verified that this is the case and there isn't just some funny bug in the resource code that I didn't spot/
