### ISSUE TITLE
Share provider info between terraform directories

### ISSUE THREAD

**Issue by clintonm9** [hashicorp/terraform#6510]
Is there a way to share a set of provider credentials across different terraform directories? 

I was trying to use a module, but I haven't been able to figure it out.

Cheers!

**Comment by phinze** [comment]
Hi @clintonm9 - provider configuration inherits down the module tree, so however you configure your providers at the top level will be available down in modules.

Sounds like you tried to use a Terraform module with your provider config, which won't work since the provider config does not automatically inherit _up_ the module tree.

My personal preferred way to share provider creds is to always configure my providers with the documented environment variables. You can just omit the credentials from the config and let them be picked up. Some providers will also pick up credentials from other standard locations. These locations are documented on the provider's page in the docs (e.g. [here's AWS](https://www.terraform.io/docs/providers/aws/#authentication)).

I hope this helps! Closing this for now, but feel free to follow up if you have additional questions.

**Comment by tmccombs** [comment]
> My personal preferred way to share provider creds is to always configure my providers with the documented environment variables.

I think  there are some situations where that doesn't work. For example, if you have multiple aws providers with aliases, or if your s3 backend needs different AWS credentials than your provider.
