### ISSUE TITLE
Terraform fmt adds spaces to commented here-docs, every run returns output to STDOUT

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#6524]
### Terraform Version

`Terraform v0.6.15`
### Affected Resource(s)

Any HCL object stanza (resource, module, variable, etc...)
### Terraform Configuration Files

``` hcl
resource "provider" "resource" {
  /*
  SPACE_SENSITIVE_CODE = <<EOF
yaml code:
   foo: ""
   bar: ""
EOF
  */
}
```
### Debug Output

**Nada**, fmt doesn't appear to support TF_LOG=debug nor trace. Should this be a separate issue? Would be nice to understand how a code block was evaluated.
### Panic Output

n/a
### Expected Behavior

Exit 0, without output to stdout. Not add spaces, and not send anything to stdout (since the command always returns exit 0, regardless of input).
### Actual Behavior

Continues to add spaces to here doc, damaging whitespace sensitive code and breaking CI by always returning output to stdout.

```
$cat test.tf
resource "provider" "resource" {
  /*
  SPACE_SENSITIVE_CODE = <<EOF
yaml code:
  foo: ""
  bar: ""
EOF
  */
}
$ terraform fmt test.tf && cat test.tf
resource "provider" "resource" {
  /*
    SPACE_SENSITIVE_CODE = <<EOF
  yaml code:
     foo: ""
     bar: ""
  EOF
    */
}
$ terraform fmt test.tf && cat test.tf
test.tf
resource "provider" "resource" {
  /*
      SPACE_SENSITIVE_CODE = <<EOF
    yaml code:
       foo: ""
       bar: ""
    EOF
      */
}
$ terraform fmt test.tf && cat test.tf
test.tf
resource "provider" "resource" {
  /*
        SPACE_SENSITIVE_CODE = <<EOF
      yaml code:
         foo: ""
         bar: ""
      EOF
        */
}
$ terraform fmt test.tf && cat test.tf
test.tf
resource "provider" "resource" {
  /*
          SPACE_SENSITIVE_CODE = <<EOF
        yaml code:
           foo: ""
           bar: ""
        EOF
          */
}
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `$ terraform fmt test.tf`

**Comment by apparentlymart** [comment]
Hi @u2mejc! Thanks for this report.

It looks like in your example the heredoc is actually inside a multi-line comment, and so `go fmt` is fiddling with the comment rather than the heredoc. I expect the parser doesn't even know there's a heredoc in there, because it'd just treat the comment as a single opaque stream of characters.

Issue #6375 describes another weird thing that `fmt` does with comments... maybe it's just trying to be a bit too "clever" when it comes to formatting comments, and it'd be better to treat their context as fixed and not try to reformat the content at all.

However, I certainly agree that it's a bug that iterative runs of `fmt` produce progressively more indentation! `fmt` should converge on a stable state, regardless of what that fixed state is.

Just as with that other issue, the change here would likely be in the `hcl` library itself rather than in Terraform, but I think we can keep this ticket to track the issue from Terraform's perspective.

**Comment by u2mejc** [comment]
Thx Martin, and you're correct, it's commented here-docs specifically. I appended the title.

Related, do you think the hcl library should have a verbose option in terraform debug? Presently, if gives no output, even in trace.
