### ISSUE TITLE
Add Sticky Session Support to AWS ELB

### ISSUE THREAD

**Issue by 2deviant** [hashicorp/terraform#656]
A simple boolean would suffice:
```javascript
sticky_sessions = true
```
`false` by default.

**Comment by joescii** [comment]
Yep, needed here too.  Nonetheless, thanks for the awesome tool! :+1:

**Comment by joescii** [comment]
I've made a workaround for my use case.  I always create a new ELB, so I can safely add session stickiness every time after I run terraform.  I call the AWS CLI similarly to this:

```bash
# Set ELB session stickiness
aws elb create-lb-cookie-stickiness-policy \
  --load-balancer-name ${ELB_NAME} \
  --policy-name MyStickySessionPolicy 
aws elb set-load-balancer-policies-of-listener \
  --load-balancer-name ${ELB_NAME} \
  --load-balancer-port 80 \
  --policy-names MyStickySessionPolicy
```

Because you can set the cookie expiration, this can't be a trivial boolean property.  It also will need to be specified in the context of a listener.

**Comment by ojongerius** [comment]
+1

**Comment by jeffb-stell** [comment]
It would be ideal if multiple cookie policies could be selected from, see

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateAppCookieStickinessPolicy.html

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLBCookieStickinessPolicy.html

**Comment by phinze** [comment]
Done in master!
