### ISSUE TITLE
Provider documentation: list known issues by resource type

### ISSUE THREAD

**Issue by Preskton** [hashicorp/terraform#6618]
As a user of Terraform, I want known issues/proposed enhancements to be tagged by resource type so that I can quickly determine a) if I can use Terraform in an environment, and b) if I choose to do so, I have a quick list of items I may need to work around.

What I'm trying to avoid is starting on a Terraform only to find that a particular resource type isn't quite as baked as the documentation makes it seem.

This could be an extended set of tags in GitHub, e.g. `provider/azurerm/azurerm_subnet`.  Ideally, this would appear as a "known issues" list in the Terraform docs and not just GitHub.

**Comment by phinze** [comment]
Interesting idea @Preskton!

I'm curious - did you have this experience with any specific resources? I wonder if in the near term we can just correct the rough patches you hit.

The more general case of linking GitHub github labels to the docs pages is an interesting one. I'll think more on that.

In the meantime, definitely let us know if you encountered specific issues in the docs and we can get those areas improved!

**Comment by Preskton** [comment]
@phinze No particular area in mind, but I've been using the Azure RM, vSphere, and AWS providers quite a bit.  What I'm trying to avoid is situations where I tell a client we'll be using terraform, we run into a snag because of a bug or known issue, and we blow a sprint commitment (or worse, replatform entirely).  At this point, I personally have a decent idea of what's baked vs not, but I figure this would be good general information, especially as new defects/enhancements are proposed.

**Comment by teamterraform** [comment]
Hi @Preskton! Sorry for the long silence here.

The providers are now maintained in [separate codebases](https://github.com/terraform-providers), so there's no change we could make in _this_ repository to get the information you were looking for here.

However, the AzureRM provider team in particular now uses per-_service_ tagging on issues, so while it's not quite as precise as you were hoping you can now at least constrain the issues to the service that your potential resource type belongs to. For example:

* [Storage-related issues](https://github.com/terraform-providers/terraform-provider-azurerm/issues?q=is%3Aissue+is%3Aopen+label%3Aservice%2Fstorage)
* [Virtual network-related issues](https://github.com/terraform-providers/terraform-provider-azurerm/issues?q=is%3Aissue+is%3Aopen+label%3Aservice%2Fvirtual-networks)
* [Virtual machine-related issues](https://github.com/terraform-providers/terraform-provider-azurerm/issues?q=is%3Aissue+is%3Aopen+label%3Aservice%2Fvirtual-machine)

These labeling schemes vary from provider to provider, but several other of the larger providers have adopted similar approaches.

With that said, since the provider issues are now out of scope for this codebase, we're going to close this issue. Hopefully the tagging schemes the provider teams are now using will help you get the information you were looking for, even if not exactly as detailed as you had requested.
