### ISSUE TITLE
endpoint_auto_confirms and confirmation_timeout_in_minutes for sqs endpoints

### ISSUE THREAD

**Issue by scheffield** [hashicorp/terraform#6652]
Hi,

I recently upgraded to version `0.6.16`. Now I get changes for my sns subscriptions which look as follows:

```
~ aws_sns_topic_subscription.foo-subscription
    confirmation_timeout_in_minutes: "" => "1"
    endpoint_auto_confirms:          "" => "false"
```

The protocol I'm subscribing to is `sqs`. From what I understand (reading the documentation: http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html#SendMessageToHttp.prepare) auto confirm makes only sense for http/https endpoints. Applying the changes affects the terraform state but not the actual subscription. I recon the change was introduced by https://github.com/hashicorp/terraform/pull/4711

Please find my actual configuration and other infos below.
### Terraform Version

`Terraform v0.6.16`
### Affected Resource(s)
- `aws_sns_topic_subscription`
### Terraform Configuration Files

``` hcl
resource "aws_sns_topic" "foo" {
  name = "foo-topic"
}

resource "aws_sns_topic_subscription" "foo-subscription" {
  topic_arn = "arn:aws:sns:us-east-1:************:foo"
  protocol = "sqs"
  endpoint = "arn:aws:sqs:us-east-1************:foo-queue"
  raw_message_delivery = true
  depends_on = ["aws_sns_topic.foo"]
}
```

**Comment by stack72** [comment]
Hi @scheffield 

My apologies this slipped through the net here and has taken so long to get back to you. In a situation like this, we usually take care of a state migration so that the user still gets the same behaviour

In this case, the changes themselves were not breaking changes - as you said, they changed the state only and not the subscription

We will endeavour to make sure that users do not see this type of behaviour in the future. This will only have affected those people who upgraded to 0.6.16 onwards

Paul
