### ISSUE TITLE
Escaping HIL program delimiters

### ISSUE THREAD

**Issue by SydOps** [hashicorp/terraform#6655]
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
- aws_instance

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

    * template_file.userdata.0: failed to render : parse error: syntax error

### Expected Behavior
What should have happened?
aws instance should be created.

### Actual Behavior
What actually happened?

not created.

In terraform template file, it doesn’t support `bash`'s  `${string/#substring/replacement}`, even you comment it (put `#` in front of the line).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Sample one: 

    ROLE=role::haproxy
    ansible-playbook -c localhost ${ROLE##*:}

I want to get `haproxy`, but failed.

Sample two:

    IP=10.0.0.1
    INVENTORY=${IP//./_}   

I want to get `10_0_0_1`, but failed.

For example, in second command, I have to replace with sed command: 

    INVENTORY=$(echo $IP|sed 's/\./_/g')

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by jen20** [comment]
Hi @SydOps! Assuming I'm understanding your problem correctly, the actual issue here is that by opening a `${}` block you are invoking HIL (our interpolation language) and this is indeed a syntax error there. To prevent that I believe you can use `$${ content }`.

I'll go ahead and close this issue for now - if you have further questions on this please feel free to reopen it!
