### ISSUE TITLE
Gotchas when using vCloud Director

### ISSUE THREAD

**Issue by nickvth** [hashicorp/terraform#6660]
Issue I have with Terraform combined with vCloud Director so far is that it does not make the call to VMWare's Guest Customisation to set the VM hostname to match the vApp name and the VM name as displayed in vCloud Director. When the VMs boot up, they have the same hostname as the VM that was cloned from the vApp Template used. Also you can not create multiple vm's inside a vApp.

Reference: http://robcoward.blogspot.nl/2016/03/vcloud-director-and-terraform.html

Error changing vmname: &errors.errorString{s:"Error with vm name change: &errors.errorString{s:\"vApp doesn't contain any children, aborting customization\"}"}

**Comment by jbarrio** [comment]
@nickvth which version of vCloud Director are you using? Trying this provider against vCloud 5.1 and I can't login:

`* Something went wrong: error authorizing: error parsing error body for non-200 request: EOF`

It seems that the POST request that the provider performs is missing something for version 5.1.

**Comment by robcoward** [comment]
@jbarrio, sorry, only just picked up this issue. Have you got it working yet ? I found that the terraform provider for vCloud Director is particularly fussy with its API URL. Other clients and libraries I've used seem to cope with just using https://api.myvcloud.net but terraform requires the full path, eg. https://api.myvcloud.net/api
Without the /api path, I seem to remember getting a similar error authorizing message to the one you gave.

**Comment by robcoward** [comment]
@nickvth - I assume that you are launching linux VMs and not windows ? I can confirm that as the code currently stands, the relevant guest customisation api call is only made by terraform when you also include an initscript. This is what I use now I've discovered this, at it works consistently for me now, setting both the hostname correctly and also giving me the ability to login with ssh keys rather than password.
```
resource "vcd_vapp" "gluster" {
    name        = "${format("gluster%02d", count.index + 1)}.${var.domain_name}"
    catalog_name  = "${var.catalog}"
    template_name = "${var.vapp_template}"
    memory        = "${var.memory}"
    cpus          = "${var.cpu_count}"
    network_name  = "${var.network_name}"

    count         = "${var.num_nodes}"

    initscript    = "mkdir -p ${var.ssh_user_home}/.ssh; echo \"${var.ssh_key_pub}\" >> ${var.ssh_user_home}/.ssh/authorized_keys; chmod -R go-rwx ${var.ssh_user_home}/.ssh; restorecon -Rv ${var.ssh_user_home}/.ssh"
}
```

**Comment by anilybba** [comment]
@robcoward - what do you think would be the best way to approach having that guest customization API call trigger every time, even without providing an initscript? Maybe having a default initscript in the resource that's effectively a no-op? Something cleaner / smarter?

I'm asking because I'm about to dig into the provider code to see about extending it for some things I need (multiple networks on a vm, for example). I figure I can look at this too...

**Comment by yaelda** [comment]
@jbarrio @robcoward  I'm having the same issue as jbarrio.  Using this provider against vCloud 5.1. Receiving:
`wrong: error authorizing: error parsing error body for non-200 request: EOF`

I have used the correct path, with "/api" at the end.  I have managed to use the Python-SDK to communicate with my vCloud Director.

Any thoughts?

Thanks.
