### ISSUE TITLE
Allow running provisioners on existing resource

### ISSUE THREAD

**Issue by cornfeedhobo** [hashicorp/terraform#6676]
### Terraform Version
Terraform v0.6.15

### Affected Resource(s)
terraform core

### Expected Behavior
Provision inter-dependent resources

### Actual Behavior
Cycle error

### Steps to Reproduce
I created a mocked up module to describe this guide: https://aws.amazon.com/articles/2781451301784570
https://github.com/cornfeedhobo/aws_vpc_nat_ha

### References
- GH-745

### Summary
This issue comes when provisioning is planned, and data about the other node being started is needed. Thus, I think the referenced issue is relevant.
Please take a look and let me know if there is another way to solve this. Thanks!

**Comment by jen20** [comment]
Hi @cornfeedhobo! I haven't tried running the example yet, but as a quick (better) fix for HA NAT you could probably use the newer NAT Gateway service from AWS. I don't think we have a good way to achieve the "provision once all the data required" type scenario described here. In my experience it is better to make the instances self-managing and have them introspect the AWS API for the data they require (authenticating via an Instance Profile) rather than have a provisioner do this.

**Comment by cornfeedhobo** [comment]
@jen20 Thanks for the tip, the NAT Gateway service does seem much much better. But to address your point, the instances do self-manage, it just is through bash scripts that are provisioned using information gathered about both nodes. I think this is a decent example where making provisioning occur after all resources have been created, might be a more flexible approach. The configuration definitions could stay the same, just the order of execution would need to moved.

**Comment by cornfeedhobo** [comment]
@jen20 Thank you for your initial response. I have come to believe this can be reconciled using the newly added `null_resource` resource.
