### ISSUE TITLE
InvalidChangeBatch when replacing CNAME with A record

### ISSUE THREAD

**Issue by dtaylor-desk** [hashicorp/terraform#6679]
I'm using Terraform 0.6.15. If I have a CNAME, then decide I want an A record instead with that same name, the CNAME is deleted, the A record is created, but the A record is created before destruction of the CNAME completes. This results in an `InvalidChangeBatch` error like the following:

```
aws_route53_record.host123_cname: Destroying...
aws_route53_record.host123_a: Creating...
  fqdn:               "" => "<computed>"
  name:               "" => "host123.domain"
  records.#:          "" => "1"
  records.2521858098: "" => "1.2.3.4"
  ttl:                "" => "60"
  type:               "" => "A"
  weight:             "" => "-1"
  zone_id:            "" => "QWE123ASD456ZXC789"
aws_route53_record.host123_cname: Destruction complete
Error applying plan:

1 error(s) occurred:

* aws_route53_record.host123_a: InvalidChangeBatch: RRSet of type A with DNS name host123.domain. is not permitted because a conflicting RRSet of type  CNAME with the same DNS name already exists in zone domain.
	status code: 400, request id: qwe123asd456zxc789
```

In my particular use case I created an instance with an EIP and a CNAME that referred to `aws_instance.my_instance.public_dns`. Then I realised that this only works after two applies (see https://github.com/hashicorp/terraform/issues/3216) so I decided to use an A record instead that referred to `aws_eip.my_instance_eip.public_ip`. When I ran the apply to switch from the CNAME to the A record I encountered the error above.

I believe this happens due to AWS's "eventual consistency" and that it's not safe to assume a successful delete has freed a resource. In which case, I think Terraform should check if a reused record name is available before trying to create the record.

**Comment by catsby** [comment]
Hey @dtaylor-desk thanks for reporting this. Are you by change using `create_before_destroy` in the optional `lifecycle` block?

**Comment by catsby** [comment]
Did some digging and posting my notes, as I'm not sure I can get to this today and maybe someone else can pick it up:

I found that this is happening because of the way we're orchestrating the delete of records here:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_route53_record.go#L401

To delete, we POST a change with type DELETE, and we get back a change ID. We're likely getting "accepted" on first try, but we aren't waiting for it to be `INSYNC` across Route53. 

Instead of just going with that accepted, I think that we need to get the Change ID and poll that, waiting for an `INSYNC` status:

- http://docs.aws.amazon.com/Route53/latest/APIReference/API_GetChange.html#API_GetChange_Errors

We already do this change polling in the CREATE method.

I _think_ that's what we're hitting here. If you have an easy config that demonstrates this I would appreciate it! Otherwise I can probably throw one together with the steps you've provided. Thanks!

**Comment by dtaylor-desk** [comment]
Hi @catsby, no I was not using `create_before_destroy` in either the CNAME or A record.

**Comment by dtaylor-desk** [comment]
For what it's worth @catsby, I think you're 100% correct about needing to poll after the change.
