### ISSUE TITLE
Add support for Ravello

### ISSUE THREAD

**Issue by ErikEvenson** [hashicorp/terraform#6686]
Add support for Ravello and the Ravello API:

https://www.ravellosystems.com/ravello-api-doc/

Ravello is a nice tool to make AWS and Google cloud act like bare metal for application training and dev/test for things like openstack deploys.

**Comment by lindhor** [comment]
Upvote! Would be great!!

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!
