### ISSUE TITLE
aws_cloudfront_distribution shouldn't require restrictions key

### ISSUE THREAD

**Issue by cweagans** [hashicorp/terraform#6721]
### Terraform Version

v0.6.15
### Affected Resource(s)
- aws_cloudfront_distribution
### Terraform Configuration Files

``` hcl
resource "aws_cloudfront_distribution" "sitename_cloudfront" {
  origin {
    domain_name = "${aws_s3_bucket.bucket_id.website_endpoint}"
    origin_id = "${aws_s3_bucket.bucket_id.id}"
  }

  enabled = true
  default_root_object = "index.html"

  aliases = [
    "domain1.com",
    "domain2.com"
  ]

  default_cache_behavior {
    allowed_methods = ["GET", "HEAD", "OPTIONS"]
    cached_methods = ["GET", "HEAD", "OPTIONS"]
    target_origin_id = "${aws_s3_bucket.bucket_id.id}"

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl = 0
    default_ttl = 3600
    max_ttl = 86400
  }

  # Use only edge servers in USA and EU.
  price_class = "PriceClass_100"

  viewer_certificate {
    acm_certificate_arn = "[mycert]"
    minimum_protocol_version = "TLSv1"
    ssl_support_method = "sni-only"
  }

}
```
### Expected Behavior

The cloudfront distribution should have been created with no restrictions (geo or otherwise).
### Actual Behavior

```
Errors:

  * aws_cloudfront_distribution.sitename_cloudfront: "restrictions": required field is not set
```
### Important Factoids

If the `restrictions` key isn't set, perhaps just considering this the default would work:

``` hcl
  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }
```

**Comment by vancluever** [comment]
@cweagans I agree that this is kind of weird. This was the intended original behaviour - however, if I remember correctly, while the distribution configuration created with the absent `Restrictions` parameter, it would not update without one.

The other part is that it's hard (or was not entirely 100% obvious to me how I would accomplish it) to create a default of a complex structure in Terraform via schema. However, my knowledge of TF has increased quite a bit in the couple of months since I initially wrote this, so I might take another crack at it.
