### ISSUE TITLE
Terraform destroy still unecessarily broken

### ISSUE THREAD

**Issue by t-pascal** [hashicorp/terraform#6772]
There are perhaps a few hundred issues related to create_before_destroy bugs, especially one that was fixed in 0.6.13 or so with `destroy`. There are a handful of remaining edge cases where terraform destroy will not function due to false cycle and parser-related bugs. #2359 fixed maybe 80% of the errors but we've run into several that are harder to pinpoint or identify.

Let me make it simple: `terraform destroy` should go and destroy the objects in the state file without complaining and without errors. Full stop.

Here is a very clear and elucidating example of why `destroy` is currently (still) broken:
1. Validate, plan, and apply your favourite terraform file.
2. Now try to destroy it. If `terraform destroy` fails, create an empty plan file with no resources.
3. `terraform apply` that empty plan (use the same state file from step 1 above)
4. Your resources are magically destroyed.

We have resorted to having an empty "destroy" plan that we use to destroy instead of using `terraform destroy`. Please make `terraform destroy` actually destroy. You can use the above workaround algorithm internally if needed. It seems that `destroy` attempts to parse, validate, and cycle through the supplied plan. This seems incorrect to me. `destroy` should look only at the state file and go all Godzilla on the thing.

I understand there are (still) some edge cases including but not limited to:
1. S3 buckets with objects cannot/should not be destroyed unless marked as force delete. But an s3 destroy error is reasonable and even considered a feature. As long as you emit an error and continue while skipping any depended resources (can't think of anything that depends on an s3 bucket) that satisfies the behaviour most people expect.
2. Destroy protection may be on. I would argue this is what you get for using destroy on a destroy protected resource. I don't know how you handle this. I would prefer you skip the resource and emit a warning. In my example above with the empty plan, you could start the destroy steps with an empty plan, then add in any destroy-protected resources and any dependent resources. Then execute this new pseudo plan. Something like that.
3. Any others?

Remember, `terraform destroy` means "destroy".

**Comment by phinze** [comment]
Hi @t-pascal - great write up! I have been working on many of the `terraform destroy` bugs you reference and have reached some very similar conclusions.

----

> Let me make it simple: terraform destroy should go and destroy the objects in the state file without complaining and without errors. Full stop.

Yes absolutely! I 100% agree with this.

Here's a bit more context from my time in core. The current implementation of `terraform destroy` builds and walks the same config-based graph that is used by `plan` and `apply`. The logic behind this strategy seemed sound: simply generate a plan like we normally do but instead of reaching out to each provider to determine what should happen to a given resource - Terraform core always marks the resource for destruction. We'd then get a Plan we could walk just like any other Plan - it just so happened to trigger all destroys.

As we started getting bug reports and feature requests about `terraform destroy`, we began to learn an important use case: `destroy` in contexts where the config might not have all its inputs. Or maybe destroy in contexts where the config is invalid or even totally unavailable. We also started to see the edge cases around things like `prevent_destroy` and `-target`.

In addressing the bugs that have come up, we've needed to do more and more special casing (stuff like https://github.com/hashicorp/terraform/pull/6614) - enough that I think it's worth exploring a more holistic rethinking of the implementation.

> It seems that `destroy` attempts to parse, validate, and cycle through the supplied plan. This seems incorrect to me. `destroy` should look only at the state file and go all Godzilla on the thing.

Yep! This is the same conclusion I have reached - instead of starting with the Config, I think we need to start with the State.

We still need to build up a dependency graph so we can destroy resources in the correct order, but this is information we record into the state. I think any metadata we need from the config in order to behave properly (e.g. prevent_destroy) can be written into the state.

> I understand there are (still) some edge cases including but not limited to...

I appreciate you kicking off the edge case discussion - we will indeed need to generate and walk through each of these affected scenarios and determine the proper behavior. I'll think more about this.

----

As far as next steps go, our normal process for deeper core changes like this is to write an RFC that includes a detailed spec. We can build up that document collaboratively if you like (which would help push the effort forward more consistently), or we can queue it up for one of us core devs to pick it up (which would likely be on a more ambigous timeline). Let me know your thoughts on that side. For now, tagging this issue `thinking`, since that's what I'll be doing. :grinning:

Thanks again for the time and thought you've put in to this topic - I do feel like this path will get us to a significantly more robust `terraform destroy`. 👍

**Comment by t-pascal** [comment]
Thanks for your quick reply. I can assist in reviewing and commenting on an RFC. I'm not sure I can create one.

I am more than willing to test releases and comment on whether fixes are working.

**Comment by neillturner** [comment]
Thanks for this. Very helpful that work-around to  terraform destroy cycle errors is to apply an empty plan with no resources which deletes all  the resources and then you can do a terraform destroy successfully. 

 It makes no sense that doing an apply empty plan followed by a destroy is not the same as doing a destroy. In fact surely internally a destroy should be implemented like applying an empty plan?   

Ofcourse destroy could have an option say ignore_cycle which by default is set to false which would mean that the current destroy behaviour is maintained. 

Then if someone does a destroy with ignore_cycle set to true it would internally apply an empty plan and then doing a destroy.

**Comment by dhawal55** [comment]
Agreed!! Destroy still has some quirky behavior. I had a working set of TF config files, upgraded to terraform v0.7.1, changed template_file resource to data sources and now getting dependency issues when destroying.
![terraform_view](https://cloud.githubusercontent.com/assets/3484309/17943961/7d8f4172-69f2-11e6-8faf-cc907f502827.png)

**Comment by mitchellh** [comment]
There are certainly still destroy issues but the the high level plan that @t-pascal brought up during the original is now in place as of 0.7.8 behind the `terraform destroy -Xnew-destroy` flag. This is the "experimental" new destroy graph that will be the default in 0.8.0.

This new graph uses purely the state and requires no configuration to build a destroy. This results in a much simpler destroy that completely ignores create-before-destroy and so on. 

With that in place, we can start focusing on destroy bugs much more easily and I'm going to close this high-level issue.
