### ISSUE TITLE
tfvars takes precedence over env vars

### ISSUE THREAD

**Issue by Jonnymcc** [hashicorp/terraform#6778]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
core

### Terraform Configuration Files
A tfvars file with vars like ebs_snapshot_id
and env vars like TF_VAR_ebs_snapshot_id

### Debug Output
N/a

### Panic Output
n/a

### Expected Behavior
env  vars should override the values in tfvars.

### Actual Behavior
tfvars values take precedence over env vars.

### Steps to Reproduce
n/a

### Important Factoids
Nothing atypical.

### References
None

**Comment by mitchellh** [comment]
Our precedence order is actually (later items overwrite earlier):

  1. Env vars

  2. terraform.tfvars

  3. `-var` and `-var-file` depending on the order (left to right order)

So this is working as we intend. Env vars have the lowest precedence if they're present. We can do a better job documenting these exact rules (which have been the rules since these features were implemented), so I'm doing that now. 

At this point it may actually break more things to change this behavior. I blind tested a few people and they all said the above order when I told them the list of things (not in the above order) and asked them to order how it'd override. So I think in the worst case its unclear and there isn't a right answer, and given we haven't gotten many (potentially any) other issues on this, I think its working intuitively enough
