### ISSUE TITLE
Cannot disable final snapshot in aws_rds_cluster resource

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#6786]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_rds_cluster

### Terraform Configuration Files
```hcl
resource "aws_rds_cluster" "cluster" {
  cluster_identifier = "foo"
  master_username = "username"
  master_password = "password"

  final_snapshot_identifier = ""
}
```

### Expected Behavior
The final snapshot should be disabled.

### Actual Behavior
You get the error `aws_rds_cluster.cluster: only alphanumeric characters and hyphens allowed in "final_snapshot_identifier"`. 

### Steps to Reproduce
1. Create the template above
1. `terraform apply`

### References
The [first regex](https://github.com/hashicorp/terraform/blob/27f05b8e3b64bb67cbefc6a38df6b4a21c504291/builtin/providers/aws/resource_aws_rds_cluster.go#L92) in the `ValidateFunc` for `aws_rds_cluster` is what causes issues. It should allow spaces.

As a longer-term fix, this resource should probably support a `skip_final_snapshot` parameter, similar to the ones in `aws_db_instance` and `aws_instance`.

**Comment by catsby** [comment]
Hey @brikis98 – thanks for writing in. In order to skip the final snapshot, please omit the `final_snapshot_identifier` configuration attribute entirely. The first regex fails because we're providing a value here, and that value is an empty string. It's documented here that the attribute should be omitted unless you do in fact want a final snapshot (the default then is to always skip the final snapshot unless specified):

- https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#final_snapshot_identifier

That all said, @stack72 has started a PR (#6795) to add a new attribute to be more explicit here with skipping the snapshots, and being more consistent with our current DB Instance resource. I apologize for the vague configuration attributes here :) We'll get it cleaned up and hopefully be more user friendly and consistent in the next release. Thanks!

**Comment by brikis98** [comment]
@catsby I can't omit it because I'm creating the aws_rds_cluster in a module and the `final_snapshot_identifier` is passed in as a parameter. AFAIK, there is no way to do an if-statement and conditionally set or not set a variable in Terraform (as a side note, supporting `null` in HCL to distinguish between empty and unset would be a handy way to handle this case in other places too).

A `skip_final_snapshot` param is a reasonable alternative, but I'm not sure how much work that involved and figured I'd try this PR as an immediate solution.

**Comment by catsby** [comment]
@brikis98 yeah we've seen that before, using a resource in a module, so the value is empty for this case. The `skip_final_snapshot` should help here; if true, we'll ignore `final_snapshot_identifier`. For DB Instance, the default of `final_snapshot_identifier` is `true`. Does that sound reasonable?

**Comment by brikis98** [comment]
@catsby Yeah, that will work, thanks.

**Comment by catsby** [comment]
Awesome! We merged #6795, it should go out in the next release. Thanks again!

**Comment by brikis98** [comment]
Awesome, thank you!

**Comment by kodani** [comment]
if anyone still facing the issue. check .tfstat file you will find `skip_final_snapshot`, make it  "true". you will be able to delete RDS.
