### ISSUE TITLE
Terraform upgrade to 0.6.14 -> 0.6.16 results in resources constantly being recreated

### ISSUE THREAD

**Issue by mpas** [hashicorp/terraform#6850]
Hi there,

when trying to upgrade from TF 0.6.14 to 0.6.16 we run into an issue that AWS resources are constantly being recreated. We tried the following scenario..

- Roll out a fresh version of the infra using [TF 0.6.14]
    - **tf apply**
- Check if the infra is correctly applied using terraform plan [TF 0.6.14]
    - **tf plan**

We got the confirmation that everything seems to be ok, now upgrade to **_TF 0.6.16_** and execute a **tf plan**

The result is that lots of resources are going to be recreated because of security group changes and other somehow recalculated container_definitions.

Example: Recreate because of security group updates:
```   
    security_groups.#:           "0" => "1" (forces new resource)
    security_groups.2142877382:  "" => "sg-7e44e905" (forces new resource)
```

Example: Recreate because of container definition:
```
container_definitions: "ccb864e490b69a17ed8a820ade600f1135f1b946" => "d8fd12c344f1677ea08887de8b78136fb376ea03" (forces new resource)
```

A downgrade to TF 0.6.14 is not possible because of the state file changes. 

Any clue what is happening?

**Comment by allandrick** [comment]
I am having the same issue.  It is provisioning in AWS but never updating the flag in the tfstate file.

**Comment by bsft-it-git** [comment]
We are also seeing this issue; however, we are also seeing it on new Terraform files written after the 0.6.16 upgrade.

**Comment by catsby** [comment]
Hey friends –

This is due to a regression regarding using `security_groups` when in a VPC, and not using `vpc_security_group_ids`, that was introduced into v0.6.16. Here's another issue that reported this:

- https://github.com/hashicorp/terraform/issues/6416
- My comment explaining things: https://github.com/hashicorp/terraform/issues/6416#issuecomment-219145065

The change was reverted in https://github.com/hashicorp/terraform/pull/6664 . In the future, we'll likely switch this back to requiring `vpc_security_group_ids`, but we'll make note of it in the CHANGELOG and be more explicit. Sorry for the trouble!
