### ISSUE TITLE
Search for AWS AMIs

### ISSUE THREAD

**Issue by beastie29a** [hashicorp/terraform#6862]
Feature Request

Could the same functionality as the Ansible's ec2_ami_find module be added to the AWS provider? 

https://docs.ansible.com/ansible/ec2_ami_find_module.html

Use Case:
Instead of updating a static AMI ID inside of a module, the "find" could grab the latest AMI each time by specifying the Owner ID, region and any other specific attribute such as virtualization type.

**Comment by vancluever** [comment]
@beastie29a incidentally, I had an old PR for this: #4396, however it was held off on so that @apparentlymart could get in his #6598, which would enable this to be a first-class data source and not be subject to some issues during planning and applies in certain situations. If you need it in a pinch, I have been keeping my PR up to date and using it in our own configurations, but I will be starting work soon to refactor it as a new data source so it can get upstream, hopefully. Cheers!

**Comment by beastie29a** [comment]
@vancluever I see it, don't know why it didn't come up in a search before, but it looks like exactly what I was requesting.  I think I can go ahead and close this then.

**Comment by vancluever** [comment]
I just finished refreshing this for data sources and will be putting in the PR shortly :)

**Comment by stack72** [comment]
hi @beastie29a 

I believe the data source work takes care of this :)

https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/d/ami.html.markdown

P.
