### ISSUE TITLE
terraform doesnt set name for rds replica

### ISSUE THREAD

**Issue by kszarlej** [hashicorp/terraform#6949]
Hi there :)

terraform creates read replicas without setting name correctly. As a result the created read-replica has the same name as the database that should be replicated. because name in .tf files is different than on AWS terraform wants always to recreate the read replica. 

### Terraform Version

Terraform v0.6.15

### Affected Resource(s)

- aws_db_instance

This issue affects only this single resource listed above.

aws_db_instance config I use

```hcl
resource "aws_db_instance" "fancyrds-replica" {
  identifier = "fancyrds-replica"
  replicate_source_db = "${aws_db_instance.fancyrds.name}-${var.environment}"
  instance_class = "db.t2.micro"
  storage_type = "standard"
  name = "fancyrds-replica"
  multi_az = false
  password = "${var.rds_fancyrds_replica_password}"
  publicly_accessible = false
  apply_immediately = true
  vpc_security_group_ids = ["${aws_security_group.rds-fancyrds-replica.id}"]
}
```

The replicated database is called `fancyrds`. As a result terraform creates read-replica with name `fancyrds` and not `fancyrds-replica` and on next apply terraform will recreate it (again giving it wrong name).

**Comment by catsby** [comment]
Hello –

The `name` field which you're referencing is the name of the _database_, not to be confused with the name of the _AWS RDS Database Instance_. A replicated database will have the same database name by design; providing a different name in the replica resource will cause the plan you're seeing. 

Because replication is simply an attribute of the same resource (`aws_db_instance`), it still has the `name` field available, but it should not be used for replication. For differentiating your Database Leader from any replicate, you provide a unique name for the database `identifier` (`fancyrds-replica` in your example).

For your configuration provided, I recommend you remove the `name` attribute from your `fancyrds-replica` resource. The `name` will be derived from the leader database. 

Hope this helps!
