### ISSUE TITLE
New provider: Sentry

### ISSUE THREAD

**Issue by conorgil** [hashicorp/terraform#6968]
It would be great if there was a provider for the [Sentry API](https://docs.getsentry.com/hosted/api/).

Use-case: We are currently using Terraform to provision the infrastructure in our AWS account for each environment (production, test, staging, etc). In that environment, we also provision the static infrastructure for each service which we will run (e.g. ELBs, Security Groups, etc). It would be very useful if we could also include in our Terraform scripts the creation of a Sentry project for each service we are running in a given environment so that we do not need to create them manually.

**Comment by jianyuan** [comment]
I'm working on this at the moment: https://github.com/jianyuan/terraform-provider-sentry

**Comment by mwarkentin** [comment]
What would the process for moving something like this into core be?

**Comment by mattfysh** [comment]
🤘

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!
