### ISSUE TITLE
Add aws_api_gateway_stage to allow enabling CloudWatch metrics per method

### ISSUE THREAD

**Issue by bwidmeier** [hashicorp/terraform#6972]
### Terraform Version

0.6.16
### Affected Resource(s)

aws_api_gateway_method
### Feature Request

I would like to be able to specify whether or not CloudWatch metrics are enabled for a given API Gateway method. This is currently possible through the AWS UI and API, as well as through the Go SDK (http://docs.aws.amazon.com/sdk-for-go/api/service/apigateway.html#type-UpdateMethodInput).
### Notes

It does not appear to me to be possible to set whether metrics are enabled while creating the method (other than through the UI). It seems necessary to make an update call after creation time.
### Use case

I have an API being powered by API Gateway. I want the metrics associated with the API Gateway components to be useable in my third party metrics dashboard. Unfortunately, I cannot export them to Graphite until they exist in CloudWatch. Currently, I am working around this by running a Python script to enable the CloudWatch metrics after all of my `terraform apply` invocations.

**Comment by radeksimko** [comment]
Hi @bwidmeier 
this is currently not possible because of missing `aws_api_gateway_stage` which has the method-specific logging settings.

You can get aggregated metrics for all methods and (unfortunately) _all APIs in the same region_ by specifying [`cloudwatch_role_arn` in `aws_api_gateway_account`](https://www.terraform.io/docs/providers/aws/r/api_gateway_account.html#cloudwatch_role_arn).

It is on my list to finish the `aws_api_gateway_stage` implementation https://github.com/hashicorp/terraform/commit/5fc35d42ba492cc0cb59523639cc88ddfac82641 at some point, but that list is quite long at this point, yet priorities are changing as we speak. 😄

**Comment by mtougeron** [comment]
@radeksimko Is there any chance that `aws_api_gateway_stage` will support this at some point?

**Comment by gliptak** [comment]
Would ```aws_api_gateway_stage``` be supported on ```Terraform v0.8.4```? The current documentation doesn't have a ```stage``` section:

https://www.terraform.io/docs/providers/aws/r/api_gateway_deployment.html

Thanks

**Comment by mkjois** [comment]
@radeksimko Do you have any updates on your implementation of the stage resource at [`5fc35d42`](https://github.com/hashicorp/terraform/commit/5fc35d42ba492cc0cb59523639cc88ddfac82641)?

**Comment by radeksimko** [comment]
@mkjois The main reason I kept this aside for such a long time is because of a bug in the upstream service API.

Specifically when you try to disable a cache, the cache cluster will enter `DELETE_IN_PROGRESS` state and remains there forever. This was acknowledged by the AWS via official support channel in September 2016 and was not fixed since then (at least last time I checked - a few weeks ago).

Worst case scenario would be just not waiting, but that may have some caveats (most likely inability to modify/create the cache in the following x minutes).

**Comment by mkjois** [comment]
I see, that's unfortunate. Fortunately for me my use case didn't involve anything beyond just creating all my required stages prior to any deployments, and I don't yet need any heavy stage configuration. I can work around that, but hopefully this can work out soon.

**Comment by JJK801** [comment]
+1 @mkjois 

@radeksimko isn't it possible to implements the basics (maintain stage on the api) as we can create deployments without deleting the other stage or deploy on every stage each times ?

**Comment by radeksimko** [comment]
@JJK801 just to be clear the status `DELETE_IN_PROGRESS` is related to the cache cluster (effectively CloudFront), not the stage itself. I have something else on my radar for the following few weeks, but I'll check with AWS if the bug has been fixed and if not, then I'd probably just submit the implementation as is and mention the caveats clearly in the docs.
