### ISSUE TITLE
aws_db_instance does not apply publicly_accessible at creation time

### ISSUE THREAD

**Issue by aarcro** [hashicorp/terraform#7035]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "webapp_db" {
  allocated_storage   = "${var.webapp_db_size}"  
  engine              = "${var.webapp_db_engine}" 
  engine_version      = "${var.webapp_db_engine_version}"   
  instance_class      = "${var.webapp_db_instance_class}" 
  storage_type        = "gp2"                             /* General Purpose SSD */
  name                = "${var.webapp_db_user}"
  username            = "${var.webapp_db_user}" 
  password            = "${var.webapp_db_password}" 
  publicly_accessible = false 
}                                                                                                             

variable "webapp_db_user" {
  description = "Name of the user that will connect, also name of DB"
  default     = "webapp"
}

variable "webapp_db_password" {}

variable "webapp_db_engine" {
  default = "mysql"
}

variable "webapp_db_engine_version" {
  default = "5.6.27"
}

variable "webapp_db_instance_class" {
  default = "db.t2.micro"
}

variable "webapp_db_size" {
  description = "Database size in gigs (mysql minimum is 5gb)"
  default     = 5
}
```

### Expected Behavior
Database created with publicly_accessible set to false

### Actual Behavior
Database was created with publicly_accessible set to true

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The database is created with `publicly_accessible: true` despite the configuration, but running plan and apply again (with no modification to the .tf file) will change to `publicly_accessible: false`

**Comment by stack72** [comment]
Hi @aarcro 

My apologies you can into this issue. I know (from experience) that AWS needs specific conditions for `publicly_accessible = false`

From the AWS Docs:

```
--publicly-accessible | --no-publicly-accessible (boolean)

Specifies the accessibility options for the DB instance. A value of true specifies an Internet-facing instance with a publicly resolvable DNS name, which resolves to a public IP address. A value of false specifies an internal instance with a DNS name that resolves to a private IP address.
Default: The default behavior varies depending on whether a VPC has been requested or not. The following list shows the default behavior in each case.
Default VPC: true
VPC: false
If no DB subnet group has been specified as part of the request and the PubliclyAccessible value has not been set, the DB instance will be publicly accessible. If a specific DB subnet group has been specified as part of the request and the PubliclyAccessible value has not been set, the DB instance will be private.
```

I will get the documentation updated for this field to make sure this information is in there

Paul

**Comment by aarcro** [comment]
I'll look for the doc updates, but I don't quite follow. putting `publicly_accessible = false` in the config is expected to generate a `publicly_accessible = true` rds instance under certain conditions?

**Comment by stack72** [comment]
@aarcro sorry, what the docs are saying is that you can only use publicly_accessible = false when you are putting the instance into a VPC via a subnet group. Otherwise if you set it to false and these conditions are not met, then AWS will default it to true

**Comment by aarcro** [comment]
Ahh, but it's not a hard limit, since you can re-run apply and it will change to non-public. Using a VPC other than the default is near the top of my list though.

**Comment by catsby** [comment]
I think the crux of this issue is that `publicly_accessible` is an optional, computed attribute here, and when we're constructing the `CREATE` call, we're using `d.GetOk` to determine if we should add whatever `publicly_accessible` is in the config:

```
		if attr, ok := d.GetOk("publicly_accessible"); ok {
			opts.PubliclyAccessible = aws.Bool(attr.(bool))
		}
```

(from https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go#L568, others)

Unfortunately in this block `d.GetOk` will not evaluate to true if `publicly_accessible` is `false` in the config, so the block is not invoked, and you get the AWS default, in your case, `true`. 

Future runs pick up this change because it's seen as a change from what Terraform then reads into the state. In the `UPDATE` method, we don't use `GetOk`, but just grab the value if there's been a change, thus putting this in the proper state. 

Normally we'd just give it a default value and use `d.Get`, and document the default. The fact that AWS has 2 defaults makes that less that perfect, but I think if we document that the default is `false` we can add that and get around this issue.

**Comment by stack72** [comment]
Hi @aarcro 

After the advice from @catsby here, I have a PR that is just running the tests to make sure all looks ok

P.
