### ISSUE TITLE
Add support to associate an EIP to an instance belonging in aws-autoscaling-group

### ISSUE THREAD

**Issue by shuoy** [hashicorp/terraform#7060]
I created an ASG (  min_size = "1", max_size = "1", desired_capacity = "1") to make my jump-box host able to recover if it goes down. And I need to associate it to an EIP.

I know that if I created this jump-box with aws_instance resource, I could do the association easily. But since my instance is created from aws_autoscaling_group, I can't find a way doing so. I think I need to have something like:

resource "aws_eip_association" "eip_assoc" {
  instance_id = "${aws_autoscaling_group.bastion.0.id}"
  allocation_id = "${aws_eip.bastion_eip.id}"
}

Is there a work around? Or is this a reasonable feature request?

My need seems similar to this one https://github.com/hashicorp/terraform/issues/938, particularly comments from @threetee and @egarbi,  although its context is a NAT box and route table.

**Comment by kwilczynski** [comment]
@shuoy I am not sure if this would even be possible. To solve this problem, you can pass Elastic IP via a a tag, and then have something query this tag via User Data (or otherwise) to get the value, and then re-associate the EIP from within. This is quite a common user pattern. With proper IAM restrictions it should work and be reasonably safe.

**Comment by stack72** [comment]
Hi @shuoy 

Unfortunately we won;t be able to support this request. Instances on an ASG can change at anytime. Terraform doesn't actually manage these instances. 

Thanks for the question

Paul
