### ISSUE TITLE
Plan doesn't flag duplicate resource names

### ISSUE THREAD

**Issue by swade1987** [hashicorp/terraform#7072]
Unfortunately "terraform plan" doesn't pick up duplicate named resources you have to wait until "terraform apply" to see this as an error.

**Comment by catsby** [comment]
Hey @swade1987 – you are correct, Terraform does not (typically) know a given providers criteria for naming resources, which may or may not require unique resource names, and so cannot (yet) enforce them. In truth, each Terraform resource in your configuration is evaluated independently and does not have any knowledge of any other resource (e.g. an `aws_instance` has no knowledge of any other `aws_instance` in your configuration), so there's not much we can do at this time.

There is discussion/plans/ideas around adding inter-resource validation in the future, but nothing concrete at the moment. 

Sorry for the trouble!

**Comment by jpbochi** [comment]
shouldn't this issue remain open to track this discussion/plan/idea? Or is it being tracked somewhere else? I just got hit by it.

**Comment by catsby** [comment]
Hey @jpbochi can you clarify what you've been hit by? This issue is from some time ago, and re-reading it I'm not sure ensuring resources are named without conflict is something Terraform should concern itself with, at least at `plan` time. 

Can you clarify what error or situation you encountered, so I can think on it?

**Comment by jpbochi** [comment]
@catsby sure. The sequence of events was something like this.

1. I had infrastructure define with one `aws_cloudwatch_event_rule` and everything was fine.
2. I added a new `aws_cloudwatch_event_rule` with the same name as the existing one.
3. TF correctly intended to create a new resource. However, probably because AWS uniquely identifies those by their name, the result was that the existing Event Rule was modified. IIRC, the previous event targets belonging to that rule were kept and new ones were added. In a way, the new rule was a merge of the two intended rules.

To fix the problem, I had to delete both rules from the tf file and AWS, and then create them again. Luckily, nothing was lost. An equivalent issue with other types of resources might cause some problems though.

One important point to note is that, when the new `aws_cloudwatch_event_rule` was applied, terraform executed without any errors or warnings. If a colleague of mine haven't caught the name collision so fast, we would have lost one event rule and could have days to notice the problem. Finding out what happened by then could have been very frustrating.

I think the best behaviour would be for TF to detect these name collisions and refuse to apply the new/modified resource. This fix might be specific to the AWS provider, I think.
