### ISSUE TITLE
Terraform local-exec does not work on Cygwin

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#7077]
### Terraform Version

Any version - but see https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/local-exec/resource_provisioner.go#L41-L47 for offending lines

### Affected Resource(s)
All resources
- local-exec

Try terraforming a local-exec with a command of "bin/foo.sh arg1 arg2". It doesnt work under CYGWIN. This is because the code WRONGLY detects the OS as windows and not linux/unix, as it should when running under cygwin - so it uses CMD /C  to start the command. Unfortunately, this treats further slashes in the command itself as flags to CMD.

It needs a bit of a rewrite to support CYGWIN here

**Comment by rvodden** [comment]
The file provisioner doesn't work either - that's likely related. I've got a bug open for that here:

https://github.com/hashicorp/terraform/issues/6627

**Comment by jen20** [comment]
Hi @gtmtech! Unfortunately we rely on the Go runtime mechanism (runtime.GOOS) for detecting which OS we are running on, and that appears to be detecting Cygwin environments as Windows. My suspicion is that this is statically compiled into the binary rather than runtime detection. At this stage I don't think we want to add code to Terraform to special case Cygwin - it seems like something which should be addressed in the Go runtime. You can, however, run from a normal Windows environment as a workaround.
