### ISSUE TITLE
Deleted aws_customer_gateway is still updated

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#7136]
Terraform still performs updates to a deleted AWS customer gateway (CGW). Like terminated EC2 instances, deleted CGWS linger around for a time after they've been deleted with a state of `deleted`. While in `deleted` state, Terraform will continue to apply changes to the CQW.

### Terraform Version
```
$ terraform version
Terraform v0.6.16
```

### Affected Resource(s)
- aws_customer_gateway

### Terraform Configuration Files
```hcl
resource "aws_customer_gateway" "main" {
  bgp_asn    = 60000
  ip_address = "172.83.124.10"
  type       = "ipsec.1"

  tags {
    Name = "recreate-test"
  }
}

output "cgw_id" {
  value = "${aws_customer_gateway.main.id}"
}
```

### Expected Behavior
Terraform should recognize that the CGW has been deleted and re-create it if still present in my configuration.

### Actual Behavior
Terraform applies changes to the deleted CGW.

### Steps to Reproduce
1. `terraform apply`
1. `aws ec2 describe-customer-gateways --customer-gateway-id $(terraform output cgw_id)`
1. `aws ec2 delete-customer-gateway --customer-gateway-id $(terraform output cgw_id)`
1. `aws ec2 describe-customer-gateways --customer-gateway-id $(terraform output cgw_id)`
1. Check for `deleted` status in previous step.
1. `terraform apply`
1. Observe Terraform updating the deleted CGW.

**Comment by stack72** [comment]
Hey @clstokes 

Here is what I have found:

1. terraform apply of your code creates a gateway
2. Deleting the gateway from the console and then terraform plan shows no changes
3. made some code changes to remove `deleted` from state
4. terraform plan now shows the following:

```
+ aws_customer_gateway.main
    bgp_asn:    "60000"
    ip_address: "172.83.124.10"
    tags.%:     "1"
    tags.Name:  "recreate-test"
    type:       "ipsec.1"


Plan: 1 to add, 0 to change, 0 to destroy.
```

5. terraform apply succeeds

*the issue here is that the gateway_id changes* - when we pass in the create again to AWS, it creates a NEW gateway, rather than updating the old one

<img width="792" alt="screen shot 2016-06-29 at 13 37 20" src="https://cloud.githubusercontent.com/assets/227823/16452101/abc85382-3dfe-11e6-9d9a-92f5cc576ad9.png">

Is this acceptable behaviour for you?

Paul

**Comment by clstokes** [comment]
Hey @stack72, I think this is exactly what we need - essentially treated the _deleted_ gateway as if AWS returned a 404 that it no longer existed.
