### ISSUE TITLE
Documentation for aws_availability_zones uses interpolation on count

### ISSUE THREAD

**Issue by madpawel** [hashicorp/terraform#7159]
The documentation for [aws_availability_zones](https://github.com/hashicorp/terraform/blob/v0.7.0-rc2/website/source/docs/providers/aws/d/availability_zones.html.markdown) currently refers to interpolation on a count, which is not permitted. This should probably refer to a distributing IP ranges from a variable over the availability zones instead?

**Comment by apparentlymart** [comment]
This was fixed as part of #7162 by updating the docs. Thanks for the report, @madpawel!

Since we already have #1497 open for the idea that more interesting interpolations should be allowed in `count`, I'm going to close this one out to consolidate any further discussion about this over there. Hopefully one day we get to roll back my doc fix in #7162 because the original example works. :grinning:
