### ISSUE TITLE
Do not store config in state

### ISSUE THREAD

**Issue by raphink** [hashicorp/terraform#7179]
### Terraform Version

v0.6.16
### Expected Behavior

Config and state should be stored in separate files for idempotency reasons. This would save users from having to [write Makefiles and such](http://karlcode.owtelse.com/blog/2015/09/01/working-with-terraform-remote-statefile/) to manage remote state configs.
### Actual Behavior

Remote config and state are stored in the same `terraform.tfstate` file, mixing configuration and data.

**Comment by raphink** [comment]
I traced this to https://github.com/hashicorp/terraform/blob/master/command/state.go#L212, where the Terraform state object is passed to `remote.NewClient`.

**Comment by apparentlymart** [comment]
This seems somewhat related to #1964. Perhaps if we were to address #1964 (move the remote configuration into the main Terraform config, rather than having it be a separate thing to set up) this would address your concern, @raphink?

**Comment by raphink** [comment]
Yes and no. For the use case I have now, we are indeed using a single S3 bucket with a varying path per terraform root, but there could be cases where we'd want to use different S3 buckets (because different projects might use different AWS accounts).

**Comment by jen20** [comment]
Hi @raphink! I'm not entirely certain of the idempotency benefit that would be brought by this - can you (or perhaps @apparentlymart) elaborate a bit on your suggestion of what information would be added to and removed from the various files involved?

**Comment by apparentlymart** [comment]
Hi @raphink! Sorry for the long silence here.

Back in Terraform v0.9 we did indeed split these two artifacts by making the `.terraform/terraform.tfstate` file _only_ include the backend configuration (the filename was retained for compatibility purposes, even though it's not really a "state" anymore) and keeping the state data itself only in the remote data store.

We missed this on previous update passes because it was labeled in and old way that our filters didn't catch. Sorry about that!
