### ISSUE TITLE
Terraform apply ELB after taint ec2 instance

### ISSUE THREAD

**Issue by Meabed** [hashicorp/terraform#7210]
### Terraform Version
0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_elb

### Debug Output
[Gist](https://gist.github.com/Meabed/8cd033e046b2c63df20c0435b59ee9a7)

### Expected Behavior
Success and attach the new instance to elb

### Actual Behavior
failed - i have to run terraform apply 3 times to succeed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform taint aws_instance.be_a.2`
2. `terraform apply`

**Comment by n8gard** [comment]
I can confirm this exact same behavior. I linked my same issue.

**Comment by catsby** [comment]
Hello – to help me understand, the steps here are:

1) create an Instance
2) Create an ELB, list instance from above in `instances` attribute of elb
3) Apply so that they are linked

At that point, everything is setup. then:

1) taint the instance
2) apply 

Expected:

- ELB gets associated with new instance

Actual: 

- Diffs error

That sound correct?

**Comment by Meabed** [comment]
yes.
and if you run 3 times, you get success.

**Comment by jbardin** [comment]
Hi @Meabed,

This was recently fixed by #7205. It should work as expected in the next release.

Thanks!

**Comment by Meabed** [comment]
great, Thanks !
