### ISSUE TITLE
Variables are not inspectable

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#729]
It would be super handy to know what variables can be set. `apply` and whatnot already do this so they can prompt interactively if `--input=true`, but there does not seem to be any other way to get at this information.

The closest solution seems to be running `terraform plan --input=false`, which will complain about any unset variables that don't have defaults. However, I doubt the format of that error is a stable or robust interface, and it still leaves no way to get at variables which do have defaults. It also does not expose the variable description.

Possible use cases:
- custom web interface to apply Terraform programs
- management console to my Terraform-deployed application
- automated documentation generation for modules

**Comment by knuckolls** [comment]
+1

**Comment by ketzacoatl** [comment]
+1

**Comment by teamterraform** [comment]
Hi everyone! Sorry for the long silence here.

A while back we released a separate library and tool [`terraform-config-inspect`](https://github.com/hashicorp/terraform-config-inspect) which is intended to support this sort of analysis use-case. The library in that repository is the same code used by the Terraform Registry to analyze the interface of public modules, and for the module configuration UI in Terraform Cloud. It's designed to accept Terraform configurations targeting Terraform versions from 0.10 to 0.12 at the time of writing. We intend to maintain it for any additional language changes that affect it, as the other Terraform components using this will also need to accept those changes.

We've also defined a [JSON Output Format](https://www.terraform.io/docs/internals/json-format.html) for configuration, state, and plan so that external software can more easily consume these artifacts. Currently there isn't a command for inspecting configuration directly, since we retrofitted this format into `terraform show` and it supports only rendering plans and state snapshots. We do intend to generalize this to some sort of `terraform inspect`-like thing in the future, but we're not prioritizing that for the moment because `terraform-config-inspect` is already meeting a number of the common configuration-inspection use-cases (including analyzing variables).

We're going to close this now with [`terraform-config-inspect`](https://github.com/hashicorp/terraform-config-inspect) as the answer for the time being. We may invest more in this area in future, but we'll wait until there are more concrete plans before opening new issues to discuss those. Hopefully `terraform-config-inspect` is useful for tool integrations in the mean time. Thanks for sharing these use-cases!
