### ISSUE TITLE
azurerm - req - configurable api endpoint to support azure stack

### ISSUE THREAD

**Issue by tasquith** [hashicorp/terraform#7299]
Hi,

I'm looking into Azure Stack and terraform/packer at the moment. I've not found a way of configuring the API endpoint to access anything other than the default public cloud via these tools.

I can see that the azure-sdk-for-go supports this, I'm not sure about riviera though.

https://github.com/Azure/azure-sdk-for-go/issues/330

Are there any timescales for adding configurable endpoint support? I understand Azure Stack is not generally available until november, but it would be nice to prove against the technical preview.

Regards,

Tom

**Comment by cbednarski** [comment]
I made a [note in the related packer issue](https://github.com/mitchellh/packer/issues/3648#issuecomment-228413132) about naming environment variables for the various endpoints. If you have any additional feedback on this please drop a note there so we can keep in sync.

**Comment by tasquith** [comment]
@cbednarski @stack72 

Hi Guys,

I need to prove this ASAP, so I'm going to take a cut of this and change any references to management.azure.com to our local url. With the dependencies, i.e the SDK and riviera, how can I update dependencies to local develop versions as I can see I need to make changes in those too.

I'm new to go, so any resources you could point me at regarding this would be gratefully received.

Kind Regards,
Tom

**Comment by cbednarski** [comment]
@tasquith To get `go` installed the most important step is to [setup your GOPATH](https://golang.org/doc/install). The TL;DR version is to [download go](https://golang.org/dl) and add this to your `.bashrc` file: `export GOPATH=$HOME/go`.

After this you can:

    go get github.com/hashicorp/terraform
    cd $GOPATH/src/github.com/hashicorp/terraform
    mkdir bin
    go build -o bin/terraform .

to build from master. Use `go get` rather than `git clone` so the files are placed in the right location. The new binary will be under `bin/terraform`.

To make changes, you can edit riviera and SDK files under `$GOPATH/src/github.com/hashicorp/terraform/vendor`. These files are included in the terraform repository so you don't need to download them separately. After editing, just run `go build -o bin/terraform .` again to rebuild.

**Comment by tasquith** [comment]
@cbednarski thanks - that's a massive help :)

**Comment by tasquith** [comment]
@stack72 this enhancement/issue seems to be unrelated to the commit that you've linked this to. Please can this be reopened?

**Comment by stack72** [comment]
Apologies for tagging the wrong issue :(

**Comment by tasquith** [comment]
@stack72 - no worries, cheers! I see you are now a HashiCorp member too, does that mean I can formally bug you regarding AzureRM? ;P

**Comment by dankimmel** [comment]
The ability to deploy to an on-prem Azure Stack setup would be very beneficial for my organization as well. Have there been any updates on this since July, or should we look into alternatives?

**Comment by stack72** [comment]
@tasquith thanks to the work just added by @pmcatominey in #11026, we will soon be able to start looking at implementing this change

**Comment by tasquith** [comment]
Thanks @stack72 and @pmcatominey :)

**Comment by stack72** [comment]
@pmcatominey thoughts on this ?

**Comment by martinbjorgan** [comment]
Hi guys, 

Any updates on Azure stack support in terraform?
