### ISSUE TITLE
Terraform does not retrieve metadata_full from Atlas correctly

### ISSUE THREAD

**Issue by kartikrao** [hashicorp/terraform#732]
We are using an atlas artifact created with Packer to provision multiple instances with Terraform.

In our terraform file, the ami is set to "`${atlas_artifact.etforms.metadata_full.region-ap-southeast-2}`"

Running `terraform apply` or `terraform plan` results in 

> Error creating plan: Resource 'atlas_artifact.etforms' does not have attribute 'metadata_full.region-ap-southeast-2' for variable 'atlas_artifact.etforms.metadata_full.region-ap-southeast-2'

**To make this work**
* Set ami to `${atlas_artifact.etforms.id}` 
* Run `terraform apply`
* Apply fails with **InvalidAMIID.Malformed** since the id attribute is formatted as `region:ami`.
* Now set ami attribute back to "`${atlas_artifact.etforms.metadata_full.region-ap-southeast-2}`"
* Rerun `terraform apply`
* Works

From what I can see in the `tfstate` file, terraform is not fetching / caching `metadata_full` from Atlas for the artifact in the correct sequence.

The `.tfstate` file has artifact metadata after step 3 above.

**Comment by nathanpalmer** [comment]
I ran into a similar issue yesterday. I couldn't use metadata_full until I ran apply once with this in

```
resource "atlas_artifact" "web" {
  name = "nathanpalmer/web-artifact"
  type = "aws.ami"
}
```

Then I could use the metadata_full reference. That doesn't seem right, as I would expect the dependency to run the resource for atlas first.

**Comment by armon** [comment]
I see. The bug is that TF is failing in the planning phase because the metadata is materialized until the apply phase. Basically the validation is overly aggressive. The apply will properly run the atlas_artifact before the dependent resource, but it's not even getting that far since planning is done first.

**Comment by ravbaba** [comment]
I have the same problem, are there any plans to fix it? It would be really useful to get ami in this way:
```
 ami = "${lookup(atlas_artifact.mesos-master.metadata_full, concat("region-", var.region))}"
```
especially when you have an artifact with all the regions.

**Comment by rocky1201** [comment]
@kartikrao : your workaround doesn't seem to work for me.
@mitchellh : any plan to get this fixed anytime soon?

**Comment by catsby** [comment]
Hey all – 

`${atlas_artifact.etforms.metadata_full.region-ap-southeast-2}` is a common pattern in Terraform configurations that use Atlas. We even showcase it in an example of ours:

- https://github.com/hashicorp/atlas-examples/blob/master/HAProxy-Nodejs/terraform/main.tf#L79

@kartikrao – it's been some time since you posted this issue, and I apologize for the silence here. If you could be so kind as to update me if you're still getting this/these errors? 

@rocky1201 – I assume you're attempting the same `${atlas_artifact.etforms.metadata_full.region-ap-southeast-2}` format, and getting an error? Can you tell me what version of Terraform you're using? 

Thanks!

**Comment by ravbaba** [comment]
Hi catsby,
your example works but problem is that most people want to have an access to metadata_full regions dynamically as I've already mentioned it before

```
ami = "${lookup(atlas_artifact.mesos-master.metadata_full, concat("region-", var.region))}"
```
that would be the most flexible option for all of us.

**Comment by clstokes** [comment]
@ravbaba There's a separate open issue for more dynamic metadata lookup at #2731.

**Comment by ravbaba** [comment]
@clstokes sorry for that

**Comment by clstokes** [comment]
@ravbaba No problem at all! I was just pointing out the other issue if you wanted to add any commentary there. :+1:

**Comment by kartikrao** [comment]
Tried this again on terraform 0.6.3 and I can see the plan phase succeeding.

+1 on fixing #2731

**Comment by phinze** [comment]
Looks like this particular issue is taken care of and #2731 has the remaining work. :+1:
