### ISSUE TITLE
Change cycle if vpc_security_group_ids given in security_groups

### ISSUE THREAD

**Issue by underthink** [hashicorp/terraform#7361]
Hi,

We've seen an issue with Terraform getting into a destroy/re-create loop when given an instance config with a security group specified in the instance's 'security_groups' property, rather than the (correct) 'vpc_security_group_ids' property, in a non-default VPC.

This seems to happen because when applying, Terraform correctly figures out that the security group should be in 'vpc_security_group_ids' and applies that. This final, applied config differs from what the .tf files specify the state should be, so it will tear down the instance to try and add the security group to the 'security_groups' property... but once again applying it to 'vpc_security_group_ids'.

This is on Terraform v0.6.16.

I can reproduce this with the config:

```
resource "aws_security_group" "issue_sg" {
  name = "terraform_issue_test_sg"
  vpc_id = "vpc-15c33971"
}

resource "aws_instance" "terraform_issue_test_inst" {
  ami = "ami-fab8e98d"
  instance_type = "t2.small"
  security_groups = [ "${aws_security_group.issue_sg.id}" ]
  subnet_id = "subnet-d809a9bc"
}
```

Stdout is https://gist.github.com/underthink/b7b18974befb44d802d9d31260d6f954; debug output from stderr while applying is https://gist.github.com/underthink/8c06c3683e521584ff361b5c8dced70c.

Would it make sense to have either some kind of 'that doesn't make sense' error, or the same transformation to happen before the plan, to avoid the continual re-configuration on future plannings?

Cheers,
Rob

**Comment by catsby** [comment]
Hey @underthink – sorry you ran into this. There's a note in [the changelog](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0615-april-22-2016) that covers this issue, regardless it's unfortunate to exist at all.

The reason for both `security_groups` and `vpc_security_group_ids` is that, on EC2 Classic, you cannot change the security group(s) of an instance while it is running. Because Terraform adheres to the Immutable Infrastructure, we don't support stopping instances to modify them, so to modify them is to destroy and recreate them. 

Instances in a VPC do not have this limitation. To keep things simple, because Terraform doesn't really know if you're in Classic or not, we have two separate config options. In previous version of Terraform we did allow this however, as there is an exception in there, but we've decided going forward VPC users need to transition over.

> Would it make sense to have either some kind of 'that doesn't make sense' error

I admit I don't really know how this would be done. Because the API calls succeed, Terraform can't really distinguish this kind of difference. 

I hope I've cleared some things up here. I'm sorry for the trouble.
