### ISSUE TITLE
provider/openstack: remote-exect fails when using openstack_networking_port_v2

### ISSUE THREAD

**Issue by jon-proulx** [hashicorp/terraform#7401]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
`remote-exec` provisioner when using `openstack` provider with `openstack_networking_port_v2` resource

When specifying network configuration in openstack_networking_port_v2 resource (rather than in openstack_compute_instance_v2 resource) the remote provisioner returns a Null host which effectively execute the remote commands locally.

### Sample Config

```
# We assume the user has all other OpenSatck auth bits in shell

# define a single VM 
resource "openstack_compute_instance_v2" "terraformed" {
  region      = "REGION1
  name        = "port-test"
  image_name  = "Ubuntu-14.04LTS"
  flavor_name = "m1.1core"

  network {
    port = "${openstack_networking_port_v2.port_1.id}"
  }

  provisioner "remote-exec" {
    inline = [ 
      "echo terraform executed > /tmp/foo"
    ]
  }
}

resource "openstack_networking_port_v2" "port_1" {
  name = "test_port_1"
  admin_state_up = "true"

  # unfortunately we seem to need ids rather than names here
  network_id = "0a1d0a27-cffa-4de3-92c5-9d3fd3f2e74d"
  security_group_ids = [ 
    "2f02d20a-8dca-49b7-b26f-b6ce9fddaf4f",
    "ca1e5ed7-dae8-4605-987b-fadaeeb30461",
  ]

}
```

### To Reproduce
terraform apply

### Expected result 
Running OpenStack VM with "terraform executed"  written to /tmp/foo on REMOTE system

### Actual result
Running OpenStack VM with "terraform executed"  written to /tmp/foo on LOCAL system

### Relevant output
```
openstack_compute_instance_v2.terraformed: Provisioning with 'remote-exec'...
openstack_compute_instance_v2.terraformed (remote-exec): Connecting to remote host via SSH...
openstack_compute_instance_v2.terraformed (remote-exec):   Host:
openstack_compute_instance_v2.terraformed (remote-exec):   User: root
openstack_compute_instance_v2.terraformed (remote-exec):   Password: false
openstack_compute_instance_v2.terraformed (remote-exec):   Private key: false
openstack_compute_instance_v2.terraformed (remote-exec):   SSH Agent: true
openstack_compute_instance_v2.terraformed: Still creating... (30s elapsed)
openstack_compute_instance_v2.terraformed (remote-exec): Connected!
openstack_compute_instance_v2.terraformed: Creation complete
```
Note blank host entry this should show the remote host's IP address

**Comment by jtopjian** [comment]
Hi Jon,

Confirmed this is a bug. If you do a `terraform show` once everything is built, you can see that the instance resource does not have any access information:

```
openstack_compute_instance_v2.test-instance:
  id = e917b1ed-490e-4e7d-8a99-dc40cad6b1cf
  access_ip_v4 =
  access_ip_v6 =
  flavor_id = 99
  flavor_name = m1.tform
  image_id = d0f50597-e8fa-45d6-9c66-42bebc407a9f
  image_name = CirrOS
  metadata.% = 0
  name = test-instance
  network.# = 1
  network.0.access_network = false
  network.0.fixed_ip_v4 =
  network.0.fixed_ip_v6 =
  network.0.floating_ip =
  network.0.mac =
  network.0.name =
  network.0.port = 8b852ffa-a77b-4580-8376-c3ac36742f5d
  network.0.uuid =
  region = RegionOne
  security_groups.# = 0
  stop_before_destroy = false
  volume.# = 0
```

I'll look into getting this fixed. Might be very similar to #6874.

**Comment by jtopjian** [comment]
After just a few minutes of investigation, I think I stumbled over a big rabbit hole. 

Focusing just on v4 addresses, the access IP (which is used for the Connection info) is determined by first checking if the instance has a floating IP then falling back to the fixed IP. This works pretty well when the instance is not configured to use ports -- as this bug report proves.

In order to have the Instance resource report back what IPs are on the Port, Terraform will have to query the port. One problem is that [ports](https://www.terraform.io/docs/providers/openstack/r/networking_port_v2.html) can support multiple fixed IPs. One quick fix is to just use the first discovered fixed IP on the port. But that's not a good long-term solution.

There's also the issue of the floating IP. A Neutron-based [Floating IP](https://www.terraform.io/docs/providers/openstack/r/networking_floatingip_v2.html) is attached to a Port. So now the Instance resource must make a second query to discover if it has any floating IPs. 

Getting this information back into the Instance resource isn't impossible... but very complicated. It might even be a bad design decision for how Terraform interacts with OpenStack.

All is not lost, though. `terraform show` will display all network information within the Port resource:

```
openstack_networking_port_v2.test-port:
  id = 8b852ffa-a77b-4580-8376-c3ac36742f5d
  admin_state_up = true
  device_id =
  device_owner =
  fixed_ip.# = 2
  fixed_ip.0.ip_address = 10.1.2.3
  fixed_ip.0.subnet_id = be80ac25-f20d-4be8-a22f-86a0d71893d5
  fixed_ip.1.ip_address = 10.1.2.4
  fixed_ip.1.subnet_id = be80ac25-f20d-4be8-a22f-86a0d71893d5
  mac_address = fa:16:3e:ba:3d:af
  name = test-port
  network_id = 075ef6ad-7ffe-4067-87f9-3b562b5891d6
  region = RegionOne
  security_group_ids.# = 0
  tenant_id = 4997de8fb40e4fff969bc47e469a4258
```

This information can be used within the Terraform configuration, so you can modify the Connection parameters like so:

```hcl
resource "openstack_compute_instance_v2" "terraformed" {
  region      = "REGION1
  name        = "port-test"
  image_name  = "Ubuntu-14.04LTS"
  flavor_name = "m1.1core"

  network {
    port = "${openstack_networking_port_v2.port_1.id}"
  }

  connection {
    user = "root"
    host = "${openstack_networking_port_v2.port_1.fixed_ip.0.ip_address}"
    private_key = "~/path/to/key"
  }

  provisioner "remote-exec" {
    inline = [ 
      "echo terraform executed > /tmp/foo"
    ]
  }
}
```

And if you need to access the instance via a floating IP, substitute the "port" for a "floatingip" in the `connection` block.

I'd say this is the way to go for now. Possibly indefinitely.

**Comment by jon-proulx** [comment]
Works for me.

Guess the question is where to document this.  If it is a general (not openstack specific) for hosts with multiple interfaces as I suspect form what you're saying adding  a bit of explanation to the provisioner/remote-exec docs would be appropriate

**Comment by jtopjian** [comment]
Indeed. I'll try to get some doc patches for the OpenStack Instance page, the OpenStack Port page, and the general provisioning page.
