### ISSUE TITLE
-target=module.foo doesn't recursively pick up -target=module.foo.module.bar

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#7404]
### Terraform Version

`Terraform v0.6.16`
### Affected Resource(s)

core
### Expected Behavior

I'd expect `-target=module.foo` to recurse.
### Actual Behavior

`terraform plan -target=module.foo` won't implicitly `-target=module.foo.module.bar`
### Steps to Reproduce

Define a module that that defines another module.

**Comment by jen20** [comment]
Hi @davedash! This does sound somewhat counter to expectations, though I haven't yet tried to reproduce this. I'm going to loop in @phinze in case he has any input as to the history of why this might be the case, or whether it is actually a bug. Thanks for opening an issue!

**Comment by orclev** [comment]
More data points for this. We're seeing something similar but not **exactly** this. I'm honestly not sure what the behavior being demonstrated is. 

We've got a number of resources in two modules, that also include sub-modules. One of the two modules has already been created, but has been modified a bit, and the other module is new. When running a terraform plan it reports 66 resources to add, 17 to modify which is expected. If we provide a -target directive and specify only the module that hasn't been created yet it reports 6 resources to be created, mostly the ones directly found in the module itself, but also one resource in one of the nested modules. Interestingly if we instead specify the target to be the already provisioned module instead of the expected 17 modifications it reports no changes necessary.

I'm kind of stumped on what's going on here. Initially I thought it wasn't picking up sub-modules, but that doesn't seem to actually be the case. Something is **definitely** wrong, I'm just not sure what.

**Comment by apparentlymart** [comment]
I think this is talking about the same issue as #5190.

**Comment by mitchellh** [comment]
Agreed with @apparentlymart, closing as dup please check #5190!
