### ISSUE TITLE
terraform plan crash with crash.log

### ISSUE THREAD

**Issue by rbuels** [hashicorp/terraform#7432]
Running on OS X El Cap, with Terraform v0.6.16, I encountered a terraform crash, which also produced a crash.log file and a message asking me to submit a ticket with it.  So here it is.

I was running `terraform plan` using a terraform.tfstate and *.tf files that were generated by https://github.com/dtan4/terraforming, so the tfstate file might be malformed or something, I don't know.

[On Dropbox](https://www.dropbox.com/s/0168cogn5rxxast/crash.tar.gz.crypt?dl=0) is a tarfile of the full contents of the directory, including the crash.log, encrypted with the HashiCorp public key shown at https://www.hashicorp.com/security.html.

Hope this is useful to you, I'm very impressed with the HashiCorp toolchain so far.  👍

**Comment by catsby** [comment]
Hey @rbuels thanks for the detailed information. I looked into the crash and I _believe_ this specific crash would be fixed with https://github.com/hashicorp/terraform/pull/6851, which I coincidentally merged just a few hours ago. 

Is this something you're sitting on, e.g. you're blocked by this crash?

**Comment by catsby** [comment]
Hey @rbuels we haven't heard back so I'm going to consider this resolved by #6851. If you're still hitting this after the v0.7.0 release, please let us know!
