### ISSUE TITLE
Feature request: ability to use a temporary key when creating an EC2 instance

### ISSUE THREAD

**Issue by timmytofu** [hashicorp/terraform#7457]
I'd like to use a temporary, inline key when creating an EC2 resource. That key is used for the default account on the machine, but the key is not permanently added to the AWS account as one of the choices of keys to use. It would be great if TF could be set to generate and output the keypair, but if not at least one could put the public key inline, e.g. in lieu of `key_name = "whatever"`, have `instance_key = "ssh-rsa AAAAB…"`. I can do this with external tools in a way, but I have to add an `aws_key_pair` resource which I have to go back and destroy. I'd rather the key be totally transient, as Packer does with the temp key it uses to provision an instance for imaging.

**Comment by stack72** [comment]
Hi @timmytofu 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
