### ISSUE TITLE
aws_iam_policy_document data don't generate ids properties

### ISSUE THREAD

**Issue by blackjid** [hashicorp/terraform#7499]
### Terraform Version
Terraform v0.7.0-rc2 (46a0709bba004d8b6e0eedad411270b3ae135a9e)

### Affected Resource(s)
- aws_iam_policy_document

### Terraform Configuration Files
```hcl
data "aws_iam_policy_document" "key_store_kms" {
  id = "key-consolepolicy-2"
  statement {
    id = "Enable IAM User Permissions"
    actions = ["kms:*"]
    resources = ["*"]
  }
}
```

### Expected Behavior
Adding the `id` arguments to the policy document and the statements I would expect the generated json would have the equivalent `Id` and `Sid` properties fot the policy and the statement.

```json
{
  "Id": "key-consolepolicy-2",
  "Statement": [
    {
      "Sid": "Enable IAM User Permissions",
      "Action": "kms:*",
      "Resource": "*"
    }
  ]
}
```

### Actual Behavior
The policy `Id` and the statement `Sid` are omited in the json

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jen20** [comment]
At the same time as this we can add support for the version field for services which require a specific non-default version for particular behaviour.

**Comment by apparentlymart** [comment]
@jen20 the rationale for not making the version overridable was that different policy schema versions would presumably require changes to the logic for this data source, rather than just simply changing the version string.

I suppose we *could* add a version attribute and then make the data source check it against a set of known versions, possibly doing conditional behavior depending on the given version. That will make things more complex though, since right now it's just serializing from structs using `encoding/json`.

Are there some specific examples of AWS services that require particular IAM versions, or is it safe for us to just support the latest version and assume it will be accepted everywhere? (I am hopeful but not optimistic for the latter!)
