### ISSUE TITLE
Openstack provider doesn't recognize port connected to instance lifecycle

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#7559]
### Terraform Version
0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_port_v2
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl

provider "openstack" {
  tenant_name = "my_tenant"
}

resource "openstack_networking_port_v2" "test" {
  name = "test"
  network_id = "my_network_port"
  admin_state_up = "true"
  region = "my_region"
}

resource "openstack_compute_instance_v2" "test" {
  region = "my_region"
  name = "test_ports"
  image_name = "ubuntu"
  flavor_name = "m1.medium"

  network  {
    port = "${openstack_networking_port_v2.test.id}"
  }
  key_pair = "my-key"
}
```

### Actual Behavior

In my Openstack install (Icehouse), when an instance is deleted, its associated network port gets cascade deleted.

I initially create these resources.  Everything is fine.  I then make a change to the compute_instance which requires recreation and rerun `terraform apply`.  Terraform errors out creating the compute_instance because the port doesn't exist anymore; it was deleted by Openstack and terraform doesn't realize it.

### Expected Behavior

Terraform should see that the port doesn't exist and recreate it if needed.

**Comment by jtopjian** [comment]
I just tried this in a devstack Mitaka environment and can confirm that the port does not get deleted in this case. So it looks like this is either old Icehouse behavior or something custom going on in your environment - can you confirm the latter?

Unfortunately there's nothing Terraform can do in this case since OpenStack is deleting resources in a chained fashion when they should be distinct/isolated.

Looks like this behavior is also related to your troubles in #7558. :/

**Comment by kiall** [comment]
Older versions of OpenStack Nova would delete the Neutron port associated with an instance, regardless of if that port was pre-created and supplied (e.g. the terraform templates above), or if it was autocreated by Nova for the instance.

This Nova bug was fixed in OpenStack Liberty (which happens to be the oldest version of OpenStack which is not EOL).

https://review.openstack.org/#/c/126309/

**Comment by jtopjian** [comment]
@kiall Thank you for the confirmation 😄 

Unless I'm mistaken, there's no way around this in versions of OpenStack prior to Kilo, so I'm going to close this issue. However, please let me know if anyone has any questions or would like to discuss further.
