### ISSUE TITLE
Openstack provider treats instances in `ERROR/NOSTATE` as successfully created

### ISSUE THREAD

**Issue by matthughes** [hashicorp/terraform#7581]
Provisioning a compute instance sometimes leaves that instance in ERROR/NOSTATE in Openstack.  Terraform reports that there was an issue creating the resources in question.  However, subsequent `terraform plan` does nothing.  IMO, it should delete/recreate the failed instances.

### Terraform Version
0.6.16
### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2
- openstack_compute_servergroup_v2

### Terraform Configuration Files
```hcl

provider "openstack" {
  tenant_name = "${var.os_tenant}"
}

resource "openstack_compute_keypair_v2" "test" {
  name = "test"
  public_key = "${var.public_key}"
  region = "${var.os_region}"
}

resource "openstack_compute_servergroup_v2" "test" {
  name = "test"
  policies = ["anti-affinity"]
  region = "${var.os_region}"
}

resource "openstack_compute_instance_v2" "test" {
  region = "${var.os_region}"
  count = "10"
  name = "test"
  image_name = "${var.operating_system}"
  flavor_name = "m1.tiny"
  network  {
    name = "Public_AGILE"
  }
  key_pair = "${openstack_compute_keypair_v2.test.name}"
  scheduler_hints {
    group = "${openstack_compute_servergroup_v2.test.id}"
  }
}
```

### Debug Output
https://gist.github.com/matthughes/b0dc44dbdbfa64cdcf38a95c851269a5

### Expected Behavior
Subsequent `terraform plan`/`terraform apply` should attempt to reschedule the failed resources.

### Actual Behavior
`terraform plan`/`terraform apply` act as if the plan has been successful and all instances created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Notice some instances went into ERROR/NOSTATE
3. `terraform plan` shows nothing

### Important Factoids
In this case, the reason some nodes go into ERROR/NOSTATE is because the scheduler is having issues satisfying the anti-affinity rules.

**Comment by jtopjian** [comment]
@matthughes Thanks for reporting this one.

This is possible to do manually by doing:

```shell
$ terraform taint openstack_compute_instance_v2.test.n
$ terraform plan
$ terraform apply
```

You'll probably have to manually clean up the ERROR'd instances with either the `nova` or `openstack` command as well.

Unfortunately Terraform isn't able to "auto-taint" resources upon build failure at this time. I think the main reason is because of the large amount of use cases on why a resource would fail to build and determining when it would truly be appropriate to do an automatic rebuild.

I'm going to close this issue since things are working as they should, but please feel free to comment or re-open if you'd like to discuss more. 😄
