### ISSUE TITLE
0.6.16 escaping double quotes is not working

### ISSUE THREAD

**Issue by vysakhqb** [hashicorp/terraform#7645]
I was trying to do

```
inline = [
   "echo aws_key_name = \"${var.aws_key_name}\" >> terraform.txt"
]
```

As the expected  output was like
`aws_key_name = "keyname"`

instead it gives
`aws_key_name = keyname`

**Comment by welearnednothing** [comment]
This is because double quotes have a specific meaning in Bash, thus they must be escaped for them to be output.

In Bash
`echo aws_key_name = "[my key name]"`
outputs:
`aws_key_name = [my key name]`

`echo aws_key_name = \"[my key name]\"`
outsputs:
`aws_key_name = "[my key name]"`

Thus the following will achieve what you'd like:
```
inline = [
   "echo aws_key_name = \\\"${var.aws_key_name}\\\" >> terraform.txt"
]
```

Note you need to escape both the quotes as well as the slash so that it's interpreted as a literal slash.
