### ISSUE TITLE
Terraform plan fails if cloud formation stack has been deleted manually

### ISSUE THREAD

**Issue by devinsba** [hashicorp/terraform#7665]
Similar to a bunch of other issues/PRs

#4198

#4941

**Comment by stack72** [comment]
Hi @devinsba 

Thanks for reporting the issue here. Hopefully it hasn't caused too many issues for you! There is already a fix in progress for this

https://github.com/hashicorp/terraform/pull/5606

I am going to close this as a duplicate so that we can track everything to do with the issue there

please let me know if there are any issues here

Paul

**Comment by devinsba** [comment]
Nope, was able to work around it by modifying the state file, just more annoying when using remote state also
