### ISSUE TITLE
provider/vsphere: Create VMs with static IP

### ISSUE THREAD

**Issue by ACluelessOne** [hashicorp/terraform#7699]
Hi,
I would like to ask if it is possible to set the VMs created by terraform apply to have static IP address?

**Comment by stack72** [comment]
Hi @ACluelessOne 

Please can you tell me what resource you are using to try and create VMs?

Paul

**Comment by ACluelessOne** [comment]
terraform version 0.6.16
Trying to set up mantl using CentOS7 and vcenter

**Comment by ACluelessOne** [comment]
i tried to make the template be static IP and use terraform apply, but will fail due to error message 
```
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by mrjcleaver** [comment]
I agree an example for this would be helpful.

It's common in vmWare to assign IP addresses statically. So we need an example of a resource block wherein a set of named servers are set up, the IP addresses fixed from a base and referenced by name.

**Comment by mrjcleaver** [comment]
https://github.com/hashicorp/terraform/issues/7714 has a partial (seemingly non-working) answer.

**Comment by mitchellh** [comment]
Thanks @mrjcleaver, closing for that.

Questions like this are best asked on the mailing list or chat room. The issue tracker isn't a great place for back and force usage questions since we [maintainers] are generally just going through looking for bugs/features to tackle. If your questions in the community ultimately turn into a bug/feature then an issue is a great place to post it.
