### ISSUE TITLE
Docker 1.12 Clustering/Service Support

### ISSUE THREAD

**Issue by willrstern** [hashicorp/terraform#7704]
Docker 1.12 supports native clustering, orchestration & service definitions, which will be a tremendous feature to add to the Docker Provider.  It's in RC status now, but putting it on the radar as it will be released very soon.

**Comment by kyhavlov** [comment]
I think this is waiting on https://github.com/fsouza/go-dockerclient to be updated to support the new service stuff in 1.12, then we can add a resource for it.

**Comment by burdiyan** [comment]
Maybe it's possible to use "native" docker client library for Go from Docker? https://github.com/docker/docker/tree/master/client I don't know what was the reason to use `fsouza` library. Anyone here knows why it's used instead of the native one?

Maybe I could create a PR implementing service resource for Docker Swarm Mode, but using library from Docker, if maintainers will allow that. This should be a really cool feature to have in Terraform I believe.

P.S. I'm really new to Terraform, but code for providers looks really simple.

**Comment by burdiyan** [comment]
Just tried to create a service with Terraform on my local machine. It seems to be working, so looks like it totally viable to use native Docker client library for Go, by retrieving the tlsconfig and host URL from the `fsouza` client passed as `meta`.

So if maintainers are OK with using https://github.com/docker/docker/tree/master/client for that maybe I could create a PR. But can't promise anything about time, sincerely.

**Comment by dmportella** [comment]
is this happening I mean not the clustering but the move from the open source API to the official docker one?

**Comment by ThinkBriK** [comment]
As far as I know https://github.com/fsouza/go-dockerclient has been updated to support 1.12 features. It could be a killer feature to have this one in 0.9 !

**Comment by cie** [comment]
You might be interested in this: https://github.com/sjourdan/docker-swarm-mode-demo

**Comment by stack72** [comment]
Hi @willrstern 

Thanks so much for the request for this enhancement!

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

Thanks!

@stack72

**Comment by tyler-smith** [comment]
@stack72 I understand closing stale issues, but I just came across this and may have some interest in working on it to some degree. Specifically I'd like to add a `docker_service` resource type. If that were added (with tests/docs/etc) would it potentially be accepted? Or is the idea being rejected altogether?

I've not written code for Terraform directly so I need to evaluate, but I'm in need of this so unless I find another route soon I'll be looking at how to implement it.

**Comment by stack72** [comment]
Hi @tyler-smith 

We would happily accept a PR to add this - we just won't be able to work on this ourselves

Paul
