### ISSUE TITLE
Variable interpolation doesn't work for floats

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#7887]
I'm testing Terraform at HEAD and it seems that variable interpolation inside a string assumes that arguments are integers. For example, the following snippet fails:

```
data "template_file" "test" {
  template = "${x + y}"

  vars {
    x = 0.001
    y = 0.002
  }
}
```

The error message is:

```
Error applying plan:

1 error(s) occurred:

* data.template_file.test: failed to render : __builtin_StringToInt: strconv.ParseInt: parsing "0.001": invalid syntax

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

It looks like `x` and `y` are being parsed as integers rather than floats because `${0.001 + 0.002}` works fine.

**Comment by kwilczynski** [comment]
@joshuaspence I am curious, what is your use case?

**Comment by phinze** [comment]
Hi @joshuaspence - thanks for the report. I seem to recall this being an issue for a little bit now, but I can't find the duplicate right now. I'll link back if it comes up.

You should be able to work around this bug by forcing float math by adding `0.0 +` to the front of your expression. Hope that helps!

**Comment by joshuaspence** [comment]
The use case is that I'm building a Grafana dashboard and I want to set a threshold on a graph to be just-a-little-bit-smaller-than an integer value. I was trying to do this as `${number_of_instances - epsilon}`.

**Comment by joshuaspence** [comment]
Thanks for the workaround @phinze.

**Comment by kwilczynski** [comment]
@joshuaspence ah, got it. Thank you!

**Comment by phinze** [comment]
Turns out we need to rethink this fix - reopening!

**Comment by mengesb** [comment]
So I have a use case here surrounding cidr math.

```
> "${(5/2.0)}"
2
> "${(5.0/2)}"
2.5
> "${(5/2)}"
2
```

The above shows that if the numerator is a float, then floating point math is initialized. I would presume that it should always be floating point math, and we could use the `ceil()` or `floor()` functions to return integers as a result of unwanted floating point returns.

My use case is computing subnet space within a given cidr.  For example we have 5 total subnets, I need to compute the largest subnet within a given subnet (for example, 10.20.30.0/24).

Needing 5 subnets in a /24 subnet means the largest subnet size I can use is /27 - `${cidrsubnet("10.20.30.0/24", ceil(5/2), count.index)}` SHOULD return subnets:
- 10.20.30.0/27
- 10.20.30.32/27
- 10.20.30.64/27
- 10.20.30.96/27
- 10.20.30.128/27

However; `${ceil(5/2)}` currently returns 2, so the bits are /26 in the math, and I fall over the subnet limitation for the size.

Since I am breaking up that 5 into "2 + 3" and instead of forcing the user to input "2.0 + 3.0" I'm not getting floating point math. I think it is reasonable to return a float in ALL situations of division

**Comment by mitchellh** [comment]
Hey @mengesb there is a new issue that was just opened today actually and we've committed to this behavior. I'm going to close this but would you mind watching that issue (should be easy to find with label:bug label:core since it was today).

**Comment by mengesb** [comment]
Seems that math in general has some issues:

```
> "${2 + 3.1}"
5
> "${2.1 + 3}"
5.1
```

**Comment by mengesb** [comment]
Reference: #10778

**Comment by jmervine** [comment]
May not help, but in working with percentages, I was able to use the following work around

```
locals {
  pct = 75
  total = 32
  desired = "${floor(local.total * (local.pct / 100))}"
}
```
