### ISSUE TITLE
STUN Provider, Data Source

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#7992]
This is an idea I had that I'm mostly just leaving here for my own reference later, though of course feedback on it is welcome.

STUN is a protocol for determining the public IP address that packets from a particular host are likely to appear to come from when sent to other hosts on the public internet. In cases when NAT is in use, the goal is for this to return the public-facing IP address of the NAT gateway.

There may be some interesting use-cases around dynamically configuring AWS security groups and similar things in other providers so that the Terraform host can access them for a single Terraform run:

``` hcl
data "stun_result" "local" {
  server = "stun1.l.google.com"
}

resource "aws_security_group" "terraform" {
  # ...

  # Allow SSH access from the host where Terraform is running
  ingress {
    cidr_blocks = ["${data.stun_result.local.ip_address}/32"]

    from_port = 22
    to_port   = 22

    protocol = "tcp"
  }
}
```

(This is inspired by a use case given in the comments of #7971)

This is a funny sort of thing since it is likely that the security group would get modified each time Terraform runs on a new host, and two concurrent runs of Terraform would certainly race against each other. Not sure yet if this is a valuable thing or just a silly idea, but wanted to capture it here to remind me to think about it some more and see what other people think.

**Comment by kwilczynski** [comment]
@apparentlymart this is a very nice idea! And very useful.

For example, when you create a new test environment just for yourself, it would be amazing to get the external IP address added automatically to the Security Groups so that the TCP/22 and ports used by, for example OpenVPN, are automatically only allowing access for me.

I would love that!

**Comment by yawn** [comment]
If it's just about the external IP address, a reflector service like `http://checkip.amazonaws.com/` could be used. No IPv6 support there though, but there are very likely others.

**Comment by YakDriver** [comment]
This would be very helpful! Would be cool if it could handle multiple servers (if one were too busy) and IPv4 and IPv6. Maybe along the lines of... 
```
data "stun_result" "local" {
  servers = ["stun1.l.google.com", "http://checkip.amazonaws.com", "http://icanhazip.com"]
}

locals {
  local_ip_v4 = "${data.stun_result.local.ip_v4}"
  local_ip_v6 = "${data.stun_result.local.ip_v6}"
}
```
I would personally love it if it worked with IP-like results without being overly strict about protocol.

Currently, data-http is too strict. See this example:
```
data "http" "ip1" {
  url = "http://checkip.amazonaws.com"
}
```
Barfs with:
```Error: Error refreshing state: 1 error(s) occurred:

* data.http.ip: 1 error(s) occurred:

* data.http.ip: data.http.ip: Content-Type is not a text type. Got: 

```
Despite:
```
$ ip=$(curl http://checkip.amazonaws.com)
$ echo $ip
250.250.192.25
```

**Comment by kwilczynski** [comment]
Hi @YakDriver,

I used external resource to implement this for the time being (sadly, more dependencies).

You can see the code [here](https://github.com/kwilczynski/terraform-templates/tree/master/modules/common/origin).

**Comment by YakDriver** [comment]
Cool! Thanks @kwilczynski 

I found a pretty simple solution [(here)](https://groups.google.com/forum/#!topic/terraform-tool/v_nBUpapLyQ) .  Doesn't work for checkip.amazonaws.com (my preference) since that site doesn't set a content type.

```
data "http" "ip" {
  url = "http://ipv4.icanhazip.com"
}

resource "aws_security_group" "ssh_sg" {
 #...
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${chomp(data.http.ip.body)}/32"]
  }
}
```
Without `chomp` it barfs because I guess icanhazip returns some whitespace and http-data doesn't automagically trim.

**Comment by teamterraform** [comment]
Hi all!

In the time since this issue was originally opened, HTTP-based IP address detection services have become a far more common way to meet this need than the STUN protocol.

For that reason, we're going to close this one out now. There's no reason why a STUN provider could not still be created, but the Terraform team at HashiCorp does not plan to invest in it and these days providers are not developed inside this repository anyway, so such development would need to be in a separate repository.

As some commenters noted above, the `http` data source can be used to fetch IP address information from the HTTP-based IP address checking services that return data in a format Terraform is able to read, which many of them do.
