### ISSUE TITLE
Coalesce not honouring empty list

### ISSUE THREAD

**Issue by ManushB** [hashicorp/terraform#8013]
### Terraform Version

0.7
### Terraform Configuration Files

```
variable "vpc_id" { "default"="vpc-*****" }
variable "vpc" { "default"=0}

resource "aws_vpc" "vpc" {
  count      = "${var.vpc}"
  cidr_block = "172.31.0.0/16"
  tags {
    Name = "abc"
  }
}
resource "aws_security_group" "sg" {
  description = "Best security group in the world"
  vpc_id      = "${coalesce(var.vpc_id,element(aws_vpc.vpc.*.id,0))}"
  tags {
    Name      = "abc"
  }
}

```
### Debug Output

Error running plan: 1 error(s) occurred:
- element: element() may not be used with an empty list in:

${coalesce(var.vpc_id,element(aws_vpc.vpc.*.id,0))}
### Expected Behavior

Security Group should have been created.
### Steps to Reproduce
1. `terraform apply`

This was not seen with the 0.6.16 version. Is this a bug? If not, can you suggest any workaround?

**Comment by jen20** [comment]
Hi @ManushB! Thanks for opening an issue here. I'm not sure that this is the correct interpretation of the error message - it relates to `element` not being usable with an empty list (which is correct), rather than `coalesce`? Can you describe what you're trying to achieve here - currently this behaviour looks correct to me.

**Comment by ManushB** [comment]
Hi @jen20,  I have a requirement of spawning the vm with new or existing vpc and I don't want to make separate tf files. The above configuration will work in case of new on setting vpc as 1 and vpc_id as "". But the existing vpc won't work using current config.  
In my opinion,  coalesce should not bother considering the second element, if the first element is not null. Hence rejecting the error raised by second element.

**Comment by ste-bah** [comment]
Hi @jen20 - I have also got a similar issue to this which works fine up to 0.6.16 and is going to be problematic as the VPC module we have created is used with multiple production and non production VPC's which can have 0 private subnets and up to 6. currently we create the nat gateways likes so:

`resource "aws_nat_gateway" "nat" {
  allocation_id = "${element(aws_eip.nat.*.id, count.index)}"
  subnet_id     = "${element(split(",", var.public_subnet_ids), count.index)}"
  count         = "${var.nat_gateways_count}"
  depends_on = ["aws_internet_gateway.igw"]
}`

Then we allocate a nat gateway for each private subnet network route table like so:

`resource "aws_route" "nat_gateway" {
  route_table_id         = "${element(aws_route_table.private.*.id, count.index)}"
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = "${element(aws_nat_gateway.nat.*.id, count.index)}"
  count                  = "${var.pri_count}"
  depends_on             = ["aws_route_table.private"]
}`

this however now leads to the following error in 0.7.X when there are 0 private subnets when running terraform plan or terraform apply:

`Error running plan: 2 error(s) occurred:

* element: element() may not be used with an empty list in:

${element(aws_nat_gateway.nat.*.id, count.index)}
* element: element() may not be used with an empty list in:

${element(aws_nat_gateway.nat.*.id, count.index)}`

Is there are work around available for this scenario which is no destructive ?

**Comment by bartonTetra** [comment]
Has anyone figured out how to work around this? I am experiencing the same problem and am unable to move to v7 as a result.

**Comment by ManushB** [comment]
Hey @bartonTetra,

I think you can use something like this:
`vpc_id = "${element(compact(concat(var.vpc_id,aws_vpc.cpe_vpc.*.id)),0)}"`

You can use compact and concat together instead of colesce for terraform versions >= 0.7

**Comment by apparentlymart** [comment]
Hi @ManushB, and everyone else who commented here! Sorry we left this issue neglected for so long.

It is intentional that the `element` function doesn't work with an empty list, since requesting the first element of an empty list would not produce any reasonable result.

It looks like the goal of the original question was to allow a variable to override a resource attribute. It looks like @ManushB eventually found a way to express that:

```
  vpc_id = "${element(compact(concat(list(var.vpc_id), aws_vpc.cpe_vpc.*.id)), 0)}"
```

The above expression should work because it ensures that the list passed to `element` always has at least one element.

This pattern of concatenating lists together, ensuring that at least one of the list always has at least one item, is a good general pattern for this sort of conditional behavior in Terraform.

In an earlier comment @ManushB suggested that `coalesce` should not evaluate its second argument if the first is non-empty. I agree that this makes sense in principle, though since `coalesce` is just a function (rather than a built-in language feature) the interpolation language doesn't know that `coalesce` will ignore some of its arguments. The new conditional operator would in principle allow that but currently has a similar limitation as tracked in #11566. Since we already have an issue for making the conditional operator work as expected, I'm going to close this one and consolidate discussion over there assuming that we will recommend use of the conditional operator for situations like this in future.

Thanks again to everyone for the great discussion here!
