### ISSUE TITLE
Digital Ocean Volume creation fails

### ISSUE THREAD

**Issue by romanvbabenko** [hashicorp/terraform#8023]
My account is absolutely clean, so there're any volumes
Terraform v0.7.0
osx: latest release, completely updated

```
resource "digitalocean_volume" "data0" {
  region      = "nyc1"
  name        = "baz"
  size        = 100
  description = "an example volume"
}
```

* digitalocean_volume.data0: Error creating Volume: POST https://api.digitalocean.com/v2/volumes: 409 (request "f049e453-09da-45d9-9efe-f8185cc35422") already exists

**Comment by kwilczynski** [comment]
Apologies for troubles @romanvbabenko.

I have tried to reproduce this, as similarly, my account is empty (since I only use DigitalOcean in a blue moon, so to speak). It seem to be working fine for me, as per the following template:

```
resource "digitalocean_volume" "data0" {
  region      = "nyc1"
  name        = "test-volume-123"
  size        = 1
  description = "test volume 123"
}
```

Then, the plan and apply:

(plan)
```
+ digitalocean_volume.data0
    description:   "test volume 123"
    droplet_ids.#: "<computed>"
    name:          "test-volume-123"
    region:        "nyc1"
    size:          "1"


Plan: 1 to add, 0 to change, 0 to destroy.
```

(apply)

```
digitalocean_volume.data0: Creating...
  description:   "" => "test volume 123"
  droplet_ids.#: "" => "<computed>"
  name:          "" => "test-volume-123"
  region:        "" => "nyc1"
  size:          "" => "1"
digitalocean_volume.data0: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

I even got to destroy the volume just fine:

```
digitalocean_volume.data0: Refreshing state... (ID: 01eca561-5ba1-11e6-8836-000f53315a41)
digitalocean_volume.data0: Destroying...
digitalocean_volume.data0: Destruction complete

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

Make sure that you do not have any volumes. The only way how I could reproduce this to get it to fail exactly like it did for you, is when I created volume via the web interface, and then tried to apply the plan with Terraform:

```
digitalocean_volume.data0: Creating...
  description:   "" => "test volume 123"
  droplet_ids.#: "" => "<computed>"
  name:          "" => "test-volume-123"
  region:        "" => "nyc1"
  size:          "" => "1"
Error applying plan:

1 error(s) occurred:

* digitalocean_volume.data0: Error creating Volume: POST https://api.digitalocean.com/v2/volumes: 409 (request "831bd7d4-04ec-4aee-8661-845c0549d691") already exists
```

To add, an attempt to create a volume in an unsupported region results in an error:

```
* digitalocean_volume.data0: Error creating Volume: POST https://api.digitalocean.com/v2/volumes: 422 Storage is not supported for this region
```

Which is expected, of course.

You can enable debug output for Terraform as per [Debugging Terraform](https://www.terraform.io/docs/internals/debugging.html), and then include the output somewhere so we can have a look.

**Comment by romanvbabenko** [comment]
Yep, no probs to create volume. The (sh)it happens when I assigns created volume to droplet.

e.g.

```
resource "digitalocean_volume" "data0" {
  region      = "nyc1"
  name        = "data0"
  size        = 1
  description = "an example volume"
}

resource "digitalocean_droplet" "app0" {
    image = "ubuntu-16-04-x64"
    name = "app0"
    region = "fra1"
    size = "512mb"
    ssh_keys = ["${var.ssh_fingerprint}"]
    volume_ids = ["${digitalocean_volume.data0.id}"]
    ...
} 

but 

```
* digitalocean_droplet.app0: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 404 (request "62c29c27-613e-4c22-917f-94ba19709262") volume not found
```

In addition, the volume creates, but somehow cannot be found and attached.

**Comment by romanvbabenko** [comment]
Gotcha! The droplet and the volume must be at the same region.
Digital Ocean could be more specific in this case, e.g. volume not found in the region<name of region> of droplet.

Thanks.

**Comment by kwilczynski** [comment]
@romanvbabenko ah nice! You sorted it out!

Sadly, they don't mention this, plus the volumes can only be used in two regions at the moment, which is also quite confusing (you need to read the blog post announcement to find about this).
