### ISSUE TITLE
Performance with a lot of data

### ISSUE THREAD

**Issue by ivanjaros** [hashicorp/terraform#8095]
Hi,
I am thinking about using Terraform for more than basic setup - like managing DNS, databases and so on which can result in a lot of entries and massive config.

Has someone did some performance testing with huge config yet? (I use GCE).

**Comment by mitchellh** [comment]
We haven't done any formal benchmarking but we've seen real world configs with thousands of resources run without an issue. At a certain scale its very common to see the Terraform configs split simply as a necessity to work with the org structure rather than fighting TF scalability itself.

If we can do any specific testing for you or we can fix any performance issues you find please let us know.
