### ISSUE TITLE
Cannot output all resource information

### ISSUE THREAD

**Issue by samdunne** [hashicorp/terraform#8097]
Hey there,

I am trying to get terraform to output all information about a resource. I'm unsure if this is expected behaviour or whether it is an improvement. What I want to achieve is al follows:

Say I am creating a number of subnets on AWS like this:

```hcl
resource "aws_subnet" "subnet" {
  count = "${length(var.example)}"

  vpc_id = "${aws_vpc.vpc.id}"

  cidr_block        = "${lookup(var.example, count.index))}"
  availability_zone = "${element(keys(var.example), count.index)}"
}
```

I would like to be able to do the following:

```hcl
output "subnets" {
  value = "${aws_subnet.subnet.*}"
}
```

I should then have all information about those resources as an output. Currently this will run, no errors occur but the output is empty.

### Terraform Version
0.7.0

### Affected Resource(s)
Terraform Core

**Comment by imduffy15** [comment]
This is really useful for the data provider remote states. It would enable us to share complex resources between provisions.

**Comment by mitchellh** [comment]
This is currently expected. We don't have any plans to be able to support this because the structure of a resource can get very complex very fast. Rather, what we recommend doing is working through this via `terraform state` commands or if you need it in a config to just have outputs for each attribute you need. 

I know this isn't 100% ideal but i've never seen a use case for more than a handful of attributes and you can splat those. I also know that your use case can be very different and completely valid, but there hasn't been a strong request for this sort of thing to justify the amount of core changes necessary to make this work. :(
