### ISSUE TITLE
Guide to setting up vnet to vnet connection in azure with terraform

### ISSUE THREAD

**Issue by jonathan-kosgei** [hashicorp/terraform#8131]
Is it possible to automate the creation of a vnet to vnet connection between subscriptions on azure with terraform? Has anyone done this before?

**Comment by pmcatominey** [comment]
Hi @jonathan-kosgei,

Are you referring to Virtual Network Gateways or Virtual Network Peering which just entered public  preview recently, or something else?

I've got a mostly-complete PR for Virtual Network Gateways and their Connection resource, I'm waiting for the Azure team to update me on an API issue found while testing.

#8041 is the issue for tracking Virtual Network Peering, you can see there it's currently blocked by the Azure SDK for Go lacking methods to interact with that resource.

**Comment by pmcatominey** [comment]
Hi @jonathan-kosgei,

Peering can be used to connect networks between subscriptions, however it cannot link Classic VNets to other Classic VNets.
The requirements and limits are described in the [documentation](https://azure.microsoft.com/en-us/documentation/articles/virtual-network-peering-overview/).

If you aren't able to use Peering due to it's limits then you may have to use a [Virtual Network Gateway](https://azure.microsoft.com/en-gb/documentation/articles/vpn-gateway-about-vpngateways/) to connect the networks.

Neither of these resources are available in Terraform yet however.

**Comment by stack72** [comment]
Closed via #8168
