### ISSUE TITLE
provider/openstack: No way to get attachment device

### ISSUE THREAD

**Issue by PLoic** [hashicorp/terraform#8145]
Hi,

I use openstack provider I want to get attachment device from `openstack_blockstorage_volume_v1`, but when I do a `terraform show` I see something like `attachment.3251164618.device = /dev/vdb` and when I'm trying to do with `${openstack_blockstorage_volume_v1.BlockStorage.attachment.device}` in my .tf file I get `'Resource 'openstack_blockstorage_volume_v1.BlockStorage' does not have attribute 'attachment.device' for variable 'openstack_blockstorage_volume_v1.BlockStorage.attachment.device''`.

So are there any way to get this value ?

Thanks in advance

**Comment by jtopjian** [comment]
Per our conversation on the mailing list, IIRC, doing a splat or similar on the attribute didn't work the last time I tried this. I'll try it again.

If it doesn't work, I'll use this Issue as a reminder to look at refactoring the attachment attributes.

I've also been kicking around the idea of making a new `openstack_blockstorage_attachment_vx` resource to specifically handle the volume attachments.

**Comment by PLoic** [comment]
Ok, yes I have also opened this issue in doubt.
Thanks for your help :)

**Comment by quentinus95** [comment]
@jtopjian any news on this issue ?

Thx

**Comment by jtopjian** [comment]
Yes! I'm so sorry.

Two new resources were added a few releases ago:

* [openstack_compute_volume_attach_v2](https://www.terraform.io/docs/providers/openstack/r/compute_volume_attach_v2.html)
* [openstack_blockstorage_volume_attach_v2](https://www.terraform.io/docs/providers/openstack/r/blockstorage_volume_attach_v2.html)

One uses the Compute API and one uses the Block Storage API. Because of that, they expose different attributes. IMO, when in doubt, use `openstack_compute_volume_attach_v2`, which exposes the `device` attribute. This is currently the most confident method of obtaining the device of an attached volume.

Using this resource will require changing existing manifests around, though: instead of specifying a volume in the Instance's `volume` block, it'll now have to be attached with this resource. That might also cause any provisioning to be pushed to a new resource (or using a generic null_provider resource), but, IMO, that's inevitable as more resources are added to a manifest.

One other solution is to use the Instance's `block_device` argument. The [openstack_compute_instance_v2](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html) docs have been updated with more examples of how to use `block_device` as well as make note of a [referece](http://docs.openstack.org/developer/nova/block_device_mapping.html) for further info.

While using `block_device` doesn't expose device names, it should provide a more consistent means of predictable device names.

I'm going to consider this issue closed, but please let me know if you have any questions about the above.
