### ISSUE TITLE
plan doesn't warn if a disk size is over limit

### ISSUE THREAD

**Issue by juliangamble** [hashicorp/terraform#8209]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.6.14

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

module "canary-abs-hosts" {
  ami = "${var.ami}"
  source = "./abs-host"
  server-count = 1
  instance-type = "r3.4xlarge"
  data-size = "2000"
  security-group-ids = "${aws_security_group.rancher-host-new-sg.id}"
  availability-zones = "${consul_keys.common.var.sec-a-zone}"
  subnets = "${consul_keys.common.var.sec-a-subnet}"
  ebs-optimised = true
  work-load-type = "Dynamic"
  label = "${var.label}"
  nickname = "XXX"
  INFLUX_TAG = "XXX"
  DNS_IP = "10.42.16.2"
  PROXY_ENABLED="true"
  DOCKER_LABEL="[\"XXX\"]"
  RANCHER_ENV_KEY="XXX"
  HOST_LABEL="disk=large"
  "auto-start" = "0 21 * * 0-4,7"
  "auto-stop" = "0 13 * * *"
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: 
```
Error applying plan:

1 error(s) occurred:

* aws_ebs_volume.data: Error creating EC2 volume: InvalidParameterValue: Volume of 2000GiB is too large for volume type standard; maximum is 1024GiB
        status code: 400, request id:
```

### Expected Behavior

This didn't occur until `terraform apply` - it should have occurred at `terraform apply`. 

### Actual Behavior

The disk size blew up on the `terraform apply`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an instance with the following configuration

  instance-type = "r3.4xlarge"
  data-size = "2000"

2. Run `terraform plan`

3. Observe that there is no warning. 

4. Run `terraform apply`

5. Observe that it blows up

**Comment by apparentlymart** [comment]
Hi @juliangamble! Sorry that Terraform didn't meet expectations here.

It seems like this is an example use-case for the general idea discussed in #4170. Currently Terraform lacks a mechanism for pre-validating configuration against the remote API, and I think that would be necessary here since Terraform should not hard-code its own idea of these constraints in case they are changed in future.

Validating the settings against the API of course requires that there is an API endpoint that can give us that information. I'm not sure if doing a `CreateVolume` call with `DryRun` set to true would catch this sort of situation where the request is permitted from an access control perspective but is not valid semantically... but we could give that a try if Terraform were to get a core mechanism to deal with this sort of thing.

**Comment by mitchellh** [comment]
We've purposely tried to avoid any sort of validation logic like this in Terraform since we don't want Terraform to assume too much about the semantics of how resources are created. We instead prefer to have the creation fail at runtime since Terraform is designed to be particularly good at partial state and retrying. So if you get an error, you can just fix it and run `terraform apply` again safely.

@apparentlymart is right that we'd need some new core mechanisms to work this through. We've up to this point avoided any network activity in the validation step so even if `DryRun` worked I think it is not worth it at this point since this is one case of probably thousands and this isn't an area we're interested in chasing down right now.

I'd love to get to a point where this can be a priority. Until then, I hope you can feel comfortable running `apply` more than once. It is safe!
