### ISSUE TITLE
Feature request:  multi-line strings for resource argument values

### ISSUE THREAD

**Issue by adampats** [hashicorp/terraform#8210]
Hello,

Considering that resource argument value strings can get quite long column-wise, I thought I'd propose an additional formatting option to spread a string across multiple lines that would potentially escape white-space and / or newlines.  The currently supported HEREDOC style option is great for capturing a raw block of text with all the formatting, but this is not very useful for doing regular strings within a resource for the purposes of keeping the code clean / readable.

Example:

```hcl
tags {
  Name = <<EOF
${var.global["product"]}-${var.global["project"]}-
app-web-inbound-elb-${var.global["environment"]}
EOF
}
```

Resultant plan output (notice the newlines):
```
tags.Name:                              "product-project-\napp-web-inbound-elb-dev\n"
```

I would think using a mechanism available in many other languages would be more appropriate for this use-case, i.e. something similar to Groovy's triple quote:

```hcl
tags {
  Name = """
    ${var.global["product"]}-${var.global["project"]}-\
    app-web-inbound-elb-${var.global["environment"]}
  """
}
```

Although, this example is quite trivial, some fancier strings that include multiple interpolations, etc can get extremely long and even with editor word wrap are still quite ugly / difficult to read.  Thoughts?

### Terraform Version
Terraform v0.7.0

### References
HCL HEREDOC support:  https://github.com/hashicorp/hcl/issues/34

**Comment by apparentlymart** [comment]
Hi @adampats!

I'm not familiar with Groovy, so would you mind helping me understand the specific behavior you're looking for here?

From that example, it seems like what you want is a kind of multi-line string literal where leading and trailing space characters, along with the newlines themselves, are stripped from the string. Is that right? That does sound useful, if so!

From a UX perspective we should probably treat carefully with what specific punctuation we choose here. `"""` means different things in different languages (e.g. in Python it encloses something behaving a lot like a heredoc in Terraform) and so it might create a "false cognate" that causes some users to misunderstand what it does, since Terraform users are coming from many different programming language communities.

I feel kinda tempted to just make HCL support multi-line single-quoted strings, with it removing all newlines and the spaces around them as (I think) you suggest. This way it will hopefully look sufficiently different to both Groovy and Python that no-one will be confused by the similarity, and shouldn't be a compatibility constraint since multi-line strings are not allowed in HCL today.

**Comment by apparentlymart** [comment]
Thinking a bit more here, I think whatever we would do to address this issue would actually be an HCL change rather than a Terraform change, so maybe we should move this issue over there so it's more visible to all of the folks working on the different projects that use HCL.

**Comment by adampats** [comment]
Yes, you interpreted my intended functionality correctly - a multi-line string literal with all the white-space and newlines removed (or at least escaped).  I also agree about the single-quote syntax to avoid confusion.

Another option would be to break it up using string concatenation operators and a new-line escape, similar to (how I do it) in Python:

```hcl
tags {
  Name = "${var.foo}-${var.bar}-" + \
    "my-application-elb-${var.baz}"
}
```

I'll open an issue under HCL.

**Comment by mitchellh** [comment]
Thanks, HCL is the right place for this.
