### ISSUE TITLE
AWS_ROUTE53_DELEGATION_SET cannot be used from another account?

### ISSUE THREAD

**Issue by BerndWessels** [hashicorp/terraform#8252]
### Terraform Version
0.7.0

### Affected Resource(s)
AWS_ROUTE53_DELEGATION_SET
AWS_ROUTE53_HOSTED_ZONE

### Expected Behavior
It should be possible to use a single `reusable delegation set` to create multiple `hosted zones`.

### Actual Behavior
I cannot figure out how a `reusable delegation set` in AWS account A can be used to create a `hosted zone` in AWS account B, using `terraform`.

### References
For more details see [this stackoverflow question](http://stackoverflow.com/questions/38992732/how-to-create-a-hosted-zone-using-a-reusable-delegation-set-in-another-aws-a)

**Comment by jarrodjackson** [comment]
@BerndWessels As Far As I Know (AFAIK), AWS does not support the concept of sharing resources across accounts, per se.  A user/application in one AWS account can `assume role` in another account in order to access resources in another account, but the resources themselves are still tied to their respective accounts.

You can still delegate a hosted zone from one account to a hosted zone in another account by the normal DNS mechanisms, though.

**Comment by BerndWessels** [comment]
@jarrodjackson thanks.

Yes after talking to AWS and others this seems to be the case. The whole `cross account` area in AWS is not that easy to discover.

As you mentioned I solved this particular problem by add a NS record in the root account that points to the name servers of the subdomain acount.
