### ISSUE TITLE
Crash while attempting to import a database option group

### ISSUE THREAD

**Issue by kunaljham** [hashicorp/terraform#8332]
[crash.txt](https://github.com/hashicorp/terraform/files/427896/crash.txt)

**Comment by mitchellh** [comment]
Can you please share some info about your DB option group named "staging-baymax-option-group" ? There is something about it that we aren't accounting for in our import code but I'd love to see what that is.

**Comment by kunaljham** [comment]
sure! 
```
resource "aws_db_option_group" "baymax" {
  name = "${var.env}-baymax-option-group"
  option_group_description = "option group"
  engine_name = "mysql"
  major_engine_version = "5.7"

  option {
    option_name = "MARIADB_AUDIT_PLUGIN"
    option_settings {
      name = "SERVER_AUDIT_EVENTS"
      value = "CONNECT"
    }
  }
}

```

**Comment by stack72** [comment]
Hi @kunaljham 

Thanks for reporting this - I believe I have found the issue. I am looking into this now

Paul

**Comment by stack72** [comment]
@kunaljham (and @mitchellh)

Just a FYI, the issue here is that when you enable an option group, not all the default values (provided by AWS) have values. We were not safe guarding this in the code:

<img width="1204" alt="screen shot 2016-09-26 at 13 56 19" src="https://cloud.githubusercontent.com/assets/227823/18835014/05caf0a0-83f1-11e6-9c97-05f0e67461d9.png">

Notice some of the settings are marked with `-`

This is now working as expected in the PR above

Paul
