### ISSUE TITLE
Proposal: plugin manager

### ISSUE THREAD

**Issue by StyleT** [hashicorp/terraform#8347]
Hi there,

I see that terraform provides easy way to extend it's functionality via plugins. But currently if I want to use this feature I'm facing with the following issues:
- I have no place where I can search for available modules. Like we have in [nodejs](https://www.npmjs.com/) & [php](https://packagist.org/)
- For plugin installation I should be aware about Go build process and have appropriate build tools installed. See example [here](https://github.com/bakins/terraform-provider-coreos#install) & [here](https://github.com/makethunder/terraform-provider-etcd#installation) for example.
- I can't specify list of required plugins for my TF config & install them in 1 click. Like I can do for nodejs with `package.json` & php with `composer.json`

Looks likes that this causes small ecosystem of TF plugins. Especially comparing to huge amount of work around TF itself. 

Please correct me if I missed something 😉 
### Terraform Version

0.7.1

**Comment by jen20** [comment]
Hi @StyleT! I have discussed this in the past with @phinze and @mitchellh, and we came to the conclusion that this was something we will look into at some point in the future, but in terms of major feature work will probably be a while off. I've tagged this as `thinking` for now, we'll circle back to this when it gets scheduled on the roadmap. Thanks for opening an issue!

**Comment by cemo** [comment]
Is there something news on this @mitchellh, @jen20, @phinze ?

**Comment by StyleT** [comment]
Also I'm pretty sure that current way of TF development when we have a LOT of providers bundled inside TF & each change inside those providers requires approval of core TF team leads to nowhere.

**Comment by StyleT** [comment]
In perfect case TF can be shipped without any providers at all (except template, remote state, etc..) & all necessary ones can be installed via package manager.

**Comment by apparentlymart** [comment]
Hi @StyleT, @cemo,

We are currently working on some foundational parts of this, allowing plugins to be installed automatically.

The immediate-term goal is to make it easier to release changes to individual "builtin" providers (which will no longer be "built in" in), rather than having everything wrapped up in a single big-bang release that makes upgrading risky. In the first phase third-party plugins won't be supported for automatic installation, since we want to make sure we've got the model right before creating compatibility constraints, but that is the longer-term goal.

More news on this when we have it!

**Comment by pbar1** [comment]
Any movement on this in the past year? I've been contemplating making something like this.

**Comment by mildwonkey** [comment]
@pbar1 I believe this issue can be closed, since provider plugins were removed from core last summer: https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10

Here's the updated [provider documentation](https://www.terraform.io/docs/providers/) which included information on building and using custom providers.

Is there a more specific feature you were looking for that isn't covered here?

**Comment by pbar1** [comment]
I'm thinking of something like a plugin manager for third-party plugins, kind of like `zplug` for ZSH and `vim-plug` for Vim. Or maybe even better than that, if it'd be possible to specify the location (similar to remote modules) of a third-party provider plugin. Maybe something like this:

```
provider "example-third-party" {
  source  = "terraform-example-providers/foo/bar"
  version = "1.0.0"
  
  # configure the provider here
}
```

This way, if your project depends on a custom provider like this, it could be more easily vendored. I could see differing operating systems being a problem, but it seems you could solve that by leveraging `go get`.

**Comment by ringods** [comment]
@mildwonkey what is not covered yet for third-party providers is the automatic download. This is currently only supported for the providers officially supported by Hashicorp.

**Comment by apparentlymart** [comment]
Hi all! Sorry for the silence here.

There is a more recent issue #15252 that we've been posting updates to; we honestly lost track of this one because it dates back to before the providers were split out of Terraform Core at all.

As you can see from my comments over in #15252, this is still a goal and the plan of action for it is to work with the team that maintains Terraform Registry to incorporate provider indexing into it along with its current mission of module indexing. That will also include the definition of another registry protocol that can be implemented by others who want to run their own registry, and it will be available also as part of the integrated private registry offered by Terraform Enterprise.

Some groundwork for that is being laid by the registry team right now. We'll share more about this over in #15252 as the plans solidify. I'm going to close this issue just to consolidate the discussion over in the other issue, so we won't lose track of this one again.
