### ISSUE TITLE
How to contribute and build on Windows ?

### ISSUE THREAD

**Issue by BerndWessels** [hashicorp/terraform#8361]
Hi there,

I'd like to contribute to terraform and build some AWS resources like Cognito which are not supported yet by terraform.

But I just can't get it to build on Windows. I followed the few instructions available but then

`nmake` fails with `illegal character '?' in macro`

`cygwin` `make` fails with `gofmtcheck.sh: line 2: $'\r': command not found`

How do you guys build on Windows (build the Windows executable)?

### Terraform Version
master

**Comment by jen20** [comment]
Hi @BerndWessels! Thanks for opening an issue, and considering making contributions! Right now the story for building on Windows is pretty much non-existent - everyone on the Terraform team is a *nix user of various persuasions. The released Windows binaries are [cross-compiled](http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5) using the (excellent) native support which has been present since Go 1.5.

By far the easiest way right now to work on Terraform on Windows is to use a virtual machine running under [Vagrant](https://www.vagrantup.com), using the supplied [Vagrantfile](https://github.com/hashicorp/terraform/blob/master/Vagrantfile) which will bring up an Ubuntu 14.04 machine with all the necessary tools. Depending on how far the new Linux system call emulation has progressed on Windows 10 that may be another option. It might also be possible to build Terraform on Windows using various combinations of `go build` - it should be possible to put together the correct set by reading through the Makefile.

If you manage to fix up the Makefile to work with Cygwin or msys-supplied Make, we'll be happy to merge any necessary changes provided they don't break building on other operating systems.

**Comment by trung** [comment]
I made an attempt but until https://github.com/golang/go/issues/18468 got fixed, I won't be able to proceed
