### ISSUE TITLE
aws_db_option_group apply_immediately argument

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#8421]
### Terraform Version
0.7.1

### Affected Resource(s)
aws_db_option_group

The documentation lists the `apply_immediately = true` argument for the `aws_db_option_group` resource but it throws an error when trying to run a `terraform plan` when it's added to a config file following the example in the documentation - https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/r/db_option_group.html.markdown#example-usage

Also tried adding the `apply_immediately = true` in the `option` block but that doesn't work either.

**Comment by stack72** [comment]
Hi @PurrBiscuit 

This is actually a bit of an error on the code AND the documentation, currently we *always* `apply_immediately`:

```
modifyOpts := &rds.ModifyOptionGroupInput{
			OptionGroupName:  aws.String(d.Id()),
			ApplyImmediately: aws.Bool(true),
		}
```

Notice we are setting to true here! If you feel there are cases when we wouldn't want this to be the behaviour then I can modify the code to accept the parameter, otherwise I can update the documentation

Thoughts?

Paul

**Comment by PurrBiscuit** [comment]
I think just updating the documentation to remove that argument would be good if it's already defaulting to true.

**Comment by stack72** [comment]
On it now - will also note that we are setting this to be true

**Comment by stack72** [comment]
@PurrBiscuit thanks for this - will merge the PR and push to the site right now :)
