### ISSUE TITLE
Question: How to specify the region of AWS Lambda function ?

### ISSUE THREAD

**Issue by pradeepchhetri-nd** [hashicorp/terraform#8427]
Hi,

Is there a way to specify the region in which to create the AWS lambda function. I wasn't able to find a way to specify that in the aws_lambda_function docs.

Thanks.

**Comment by stack72** [comment]
Hi @pradeepchhetri-nd 

The region to which you are running terraform is the region to which the function will be created. 

So if you have terraform config like this:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_lambda_function" "test_lambda" {
    filename = "lambda_function_payload.zip"
    function_name = "lambda_function_name"
    role = "${aws_iam_role.iam_for_lambda.arn}"
    handler = "exports.test"
    source_code_hash = "${base64sha256(file("lambda_function_payload.zip"))}"
}
```

Then the lambda will be created in US-West-2. If you do not specify a region to the provider, Terraform will use the default region in your profile (if set). Otherwise it will prompt you for a region

Hope this helps

Paul

**Comment by pradeepchhetri-nd** [comment]
@stack72 Thank you very much for the detailed response.

**Comment by skhabeeb42** [comment]
var s3 = new AWS.S3({region: 'us-east-1'});

**Comment by mildwonkey** [comment]
@shredding yes, you can do that. You'll need to set up a second AWS provider with the desired region. 
See https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances for more information. Hope that helps!
