### ISSUE TITLE
Ensure incorrect case fails in plan

### ISSUE THREAD

**Issue by AMMullan** [hashicorp/terraform#8470]
We've run into a small bug in TF v0.7.1 where using upper case for things like **aws_network_acl_rule.protocol** passes testing when using plan but fails when applying (a colleague used uppercase TCP).

Can we please make this consistent, either fail in plan also or allow upper case (though, for consistency I'd prefer the first option).

Please let me know if you need further info.

**Comment by mitchellh** [comment]
We don't reimplement all the validation logic of the various cloud service providers within Terraform itself, we only check for basic required/optional values. Its a fine line and not entirely clear but we try to avoid enum checking, format checking (in most cases), etc. since we prefer the errors to come from the API rather than playing keep-up with all the semantics of the cloud providers.

In this case I believe Terraform behaved correctly: the plan told you what it would try to do, it tried to do it, and the cloud provider gave us an error. Terraform's partial state feature should've handled this properly so that you can fix it, plan again, apply again, and only do the remaining work.
