### ISSUE TITLE
Validate command doesn't do globbing

### ISSUE THREAD

**Issue by tonglil** [hashicorp/terraform#8497]
It would be great if the `validate` command can accept globbing and perform the validation.

In a repo with directories like:

```
├── app1
│   ├── config.toml
│   ├── src/
│   ├── packer/
│   └── terraform/
├── app2
│   ├── README.md
│   ├── src/
│   └── terraform/
└── app3
    ├── README.md
    ├── packer/
    └── terraform/
```

It would be great to validate all Terraform configs with one command.
### Terraform Version

v0.7.1
### Expected Behavior

```
terraform validate */**/*
Error loading files Error parsing /Users/xxx/project/config/terraform/ec2.tf: At 16:5: error parsing list, expected comma or list end, got: STRING
```
### Actual Behavior

```
terraform validate */**/*
Error loading files No Terraform configuration files found in directory: /Users/xxx/project
```
### Steps to Reproduce

`terraform validate */**/* in a higher up directory that contains terraform config files`

**Comment by mitchellh** [comment]
This isn't as simple as globbing, since Terraform expects each path to be the root of a Terraform _module_ and it is currently an error to specify a path that isn't one (contains no TF files), since that would be "invalid". 

I'm open to some way to do this but not sure what the proper behavior should be.

**Comment by teamterraform** [comment]
Hi @tonglil! Sorry for the long silence here.

The `terraform validate` command, as with most other commands, isn't really consuming individual directories as arguments but rather module trees that are rooted at a module in the one given directory. `terraform validate` shares the same loading logic as all other commands, and so to implement this sort of multi-directory validation would cause it to diverge quite a lot from the other commands. In particular, `terraform validate` needs to be able to activate the provider plugins used in a particular configuration in order to obtain the schema, and so it requires a fully-initialized (with `terraform init`) working directory for the target module.

Since it seems like this problem hasn't come up too often in practice, it seems like the complexity it would imply outweighs the impact of implementing it, and so unfortunately we're going to close this. Thanks for sharing this use case, and sorry we didn't respond to it sooner.

**Comment by tonglil** [comment]
Thanks for following up on this age old issue.
After using terraform over the years, you are right, it isn't a significant issue.
