### ISSUE TITLE
Website page(s) for community-related tooling such as unofficial providers

### ISSUE THREAD

**Issue by mrjcleaver** [hashicorp/terraform#8522]
Re: https://github.com/hashicorp/terraform/issues/8518 I was surprised that providers not supported by Hashicorp are not listed at all. 

History shows this leads us to duplication, wasted effort, disappointment and slower speed to market.
- https://github.com/Banno/terraform-provider-vsphere
- https://github.com/mkuzmin/terraform-vsphere

How about on the Providers page have a link to a wiki or similar so people can share what:
- they have built 
- would want to build or 
- would want to use?

Then others can pitch in.

I assume this doesn't exist as it wasn't mentioned in the answer to 8518.

Thanks,
   Martin.

**Comment by mitchellh** [comment]
I'd be open to having a community page on the website that lists not only providers but other Terraform related tooling that the community has created. If we want to use this issue as a way to collect those things I can add that page sometime.

**Comment by teamterraform** [comment]
Hi @mrjcleaver! Sorry for the long silence.

We now have [a page listing community providers](https://www.terraform.io/docs/providers/type/community-index.html), which addresses the need you originally raised.

We don't have a page for capturing community tools _in general_, but we also don't really have the resources right now to manage one, so we're going to close this out.

Fortunately, in the time since this issue was created there has emerged a convention for curated lists of tools and libraries for an application to be named "Awesome ...", and so you can find many such lists maintained by third-parties by searching for "awesome terraform" on your favorite search engine. We're very grateful to the maintainers of those lists for taking the time to curate those resources.
