### ISSUE TITLE
Vars are not uploaded to Atlas with terraform push in 0.7.2

### ISSUE THREAD

**Issue by roman-gliffy** [hashicorp/terraform#8546]
### Terraform Version

0.7.2
### Terraform Configuration Files

https://github.com/hashicorp/atlas-examples/tree/master/consul-cluster
### Expected Behavior

Vars should be uploaded
### Actual Behavior

Vars are missing in 0.7.2
### Steps to Reproduce

```
git clone git@github.com:hashicorp/atlas-examples.git
cd consul-cluster
./shared/ssh_keys/generate_key_pair.sh atlas-example
```
1. `docker run -ti --rm -e ATLAS_TOKEN=$ATLAS_TOKEN -v $PWD:/data terraform:0.7.2 remote config -backend="Atlas" -backend-config="name=$ATLAS_USERNAME/consul-cluster-0.7.2`
2. `docker run -ti --rm -e ATLAS_TOKEN=$ATLAS_TOKEN -v $PWD:/data terraform:0.7.2 get -update aws-intermediate-consul-cluster/terraform/`
3. `docker run -ti --rm -e ATLAS_TOKEN=$ATLAS_TOKEN -v $PWD:/data terraform:0.7.2 push -vcs=false -name="someorg/consul-cluster-1"`

If same run with terraform v0.6.16 - vars are uploaded
### Important Factoids

I've used different terraform versions in docker, but it doesn't matter. I've tried with the downloaded binary as well:

```
(v0.7.2)
/tmp/terraform push -vcs=false -name="org/consul-cluster-2"
Uploading Terraform configuration...
Configuration "org/consul-cluster-2" uploaded! (v1)
```

Notice the difference in output:

```
(v0.6.16)
terraform push -vcs=false -name="org/consul-cluster-3"
The following variables will be set or overwritten within Atlas from
their local values. All other variables are already set within Atlas.
If you want to modify the value of a variable, use the Atlas web
interface or set it locally and use the -overwrite flag.

  * key_data_private
  * key_data_public

Uploading Terraform configuration...
Configuration "org/consul-cluster-3" uploaded! (v1)
```

Regression or am I missing a change in config options or something?

Edited: link to repo

**Comment by apparentlymart** [comment]
Hi @roman-gliffy! Sorry for the long silence here.

This issue is from before I joined the team so I'm not sure what was going on back then, but the `terraform push` command is no longer available since the API it was talking to is now longer available with the shutdown of Atlas.

Therefore I'm going to close this. If anyone finds this in future wondering about setting variables in Terraform Enterprise, the former functionality of `terraform push` is now (approximately) available in [the separate Terraform Enterprise CLI tool](https://github.com/hashicorp/tfe-cli), which works with the newer Terraform Enterprise API rather than the now-EOL Atlas one.
