### ISSUE TITLE
vSphere: creating a VM with an existing vmdk will not work

### ISSUE THREAD

**Issue by ChloeTigre** [hashicorp/terraform#8552]
Hello,

I'm working on the vSphere code of Terraform and have noticed a strange quirk.

@tkak, @dkalleg you worked on that so I'm pinging you guys but of course anyone may contribute.

at the end of the `func addHardDisk` (L1323 in `master`), we see

``` go
       …
        return vm.AddDevice(context.TODO(), disk)
    } else {
        log.Printf("[DEBUG] addHardDisk: Disk already present.\n")
        return nil
    }
```

When you specify a disk with a vmdk, the diskPath necessarily already points to an existing VMDK hence the disk will never be attached to the VM. There's no reason whatsoever to specify a vmdk path if the said disk does not already exist.

So I guess this is a bug.

I'll work on a patch since I need this feature. Can you confirm that it does not work as expected ?

**Comment by dkalleg** [comment]
Hey @ChloeTigre , I'm hoping you can clarify a bit since I'm not sure what you're pointing out.  Two questions:
1) `the diskPath necessarily already points to an existing VMDK hence the disk will never be attached to the VM.` - Why wouldn't a vmdk be attached when the user specifies a path?  I'm wondering if you mean to say 'if a vmdk is already associated with a vm, then that vmdk cannot be associated with *another* vm', which is true.  But that would be a user-error to provide an already mounted disk.
2) `There's no reason whatsoever to specify a vmdk path if the said disk does not already exist.` - You're right that this function does not work with a vmdk path which doesn't point to anything. The assumption is that the user (prior to the call to addHardDisk) either use the virtual_disk resource to create a vmdk or upload a vmdk file to a datastore.

Could you explain your use case a bit more?  I'm not understanding the bug you're seeing.

Thanks

**Comment by ChloeTigre** [comment]
Hey @dkalleg 

Basically, I upload a VMDK to vSphere (I worked on a patch to allow disk images cloning using vsphere_file resources, but that's out of the scope of this ticket)

If I add a 

```hcl
disk {
  vmdk = "DATASTORE/path/to/cloned.vmdk"
  size = 8
}
```

the current code tries to *create* the VMDK and this fails because it already exists. I just want it to *attach* this VMDK in that case and fail if and only if it cannot either create or attach it (a VMDK cannot be attached, AFAIK, to 2 VMs).

I want to work on a patch for that or if you people have one upcoming I'll gladly test it.

**Comment by ChloeTigre** [comment]
Hello,

'been working on a patch. It's based on my refactored code base though so we may need to adjust… or go forward with this rebased code base.

See https://github.com/ChloeTigre/terraform/pull/8/files

**Comment by dkalleg** [comment]
Hi @ChloeTigre, thanks for explaining.  I see the distinction now.  There was an assumption that the user could not specify the size of an existing vmdk (which has a size).  Providing a size with a vmdk is analogous to a resize. Which isn't supported today.

So is your patch adding a resize for an existing vmdk?

**Comment by ChloeTigre** [comment]
Yes.

It is supported in my patch. I support disk resizes as a whole. However this has been done all on a refactored code base so we'll need to review it and merge it first. (a pr is open if you want to give a hand)

**Comment by mrjcleaver** [comment]
+1 for this.

**Comment by strongjz** [comment]
Are there any ideas when this bug will be fixed/released?

**Comment by bhchew** [comment]
+1
