### ISSUE TITLE
[feature request][archive_file] Allow source_file to be list of files

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#8565]
Hi, it would be nice if the `archive_file` resource allowed `source_file` and `source_dir` to be lists. It would also be nice if they were not mutually exclusive.

For example, I'd like to use the following config to support my aws lambda functions.

``` hcl
resource "archive_file" "sesbounce" {
  type = "zip"
  source_file = [
    "${path.module}/sesbounce.py",
    "${path.module}/shared/common.py"
  ]
  source_dir = [
    "${path.module}/pip_modules/"
  ]

  output_path = "${path.module}/_files/sesbounce.zip"
}

resource "aws_lambda_function" "sesbounce" {
  filename = "${path.module}/_files/sesbounce.zip"
  function_name = "sesbounce"
  role = "${aws_iam_role.iam_for_lambda.arn}"
  handler = "sesbounce.handler_ses_bounce"
  source_code_hash = "${base64sha256(file("_files/sesbounce.zip"))}"
}
```

**Comment by Ninir** [comment]
I would like to augment @mtougeron idea with the following, which would make the archive resource even more powerful & flexible.

We could benefit from 2 new attributes in order to handle more cases:
* `append_files` list of files to include
* `exclude_files`, list of files to exclude

##### Use-case 1: Include files from multiple paths
Let's say you need to deploy a lambda to 2 different environments: dev and prod. This lambda aims to send data to a Google Service. You then need credentials that are different between the dev & prod.
Embedding the 2 files is a security issue (a developer in the dev env could gain access to the prod one) so a no-go in this case.

An idea to handle this would be to dynamically add the appropriate config file in the archive, following this:
```hcl
resource "archive_file" "init" {
    type = "zip"
    source_content_filename = "${path.module}/init.tpl"
    output_path = "${path.module}/files/init.zip"
    source_dir = "../mycode"
    append_files = [
        "../myconfig/config-${myenv}"
    ]
}
```

##### Use-case 2: Exclude files from an archive (for instance to reduce the total size of the archive)
Let's say you're doing some Python in your Lambda and you want to exclude some library files (boto3, pip binaries if using virtualenvs, etc.)

The use-case would match this:
```hcl
resource "archive_file" "init" {
    type = "zip"
    source_content_filename = "${path.module}/init.tpl"
    output_path = "${path.module}/files/init.zip"
    source_dir = "../mycode"
    exclude_files = [
        "../mycode/bin",
        "../mycode/lib/boto3",
        "../mycode/env/lib/python2.7/site-packages/pip"
    ]
}
```

What do you guys think?

**Comment by stumyp** [comment]
:+1: 
Or, if possible allow to provide directory name instead of file name, so it creates archive out of all directory instead.

Thank you

**Comment by Ninir** [comment]
@stumyp this is already the case as far as I understand what you meant :)

**Comment by w32-blaster** [comment]
Would be great to have list of files/dirs.
