### ISSUE TITLE
Feature Request: Support for Autoscaling on Spot Fleets

### ISSUE THREAD

**Issue by justintime** [hashicorp/terraform#8693]
Recent support was added to TF that enabled the ability to spin up AWS Spot Fleets: https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html

Since that time, AWS recently announced that they now support AutoScaling on Spot Fleet: https://aws.amazon.com/blogs/aws/new-auto-scaling-for-ec2-spot-fleets/  

It would be truly awesome to be able to configure autoscaling on our spot fleet requests!

**Comment by niclic** [comment]
I was just about to push a PR with this feature.

**Comment by niclic** [comment]
See https://github.com/hashicorp/terraform/pull/8697

**Comment by beastie29a** [comment]
Also have a need for this feature along with automated bidding. Thanks

**Comment by beastie29a** [comment]
@niclic, I apologize for the confusion. Was just wondering what the status of PR #8697 was and didn't want to add to the noise in that thread.

**Comment by niclic** [comment]
@beastie29a 

It's been a while since I reviewed #8697, but the last time I looked I recommended it be merged _as is_. It needs a rebase as I explained in this [comment](https://github.com/hashicorp/terraform/pull/8697#issuecomment-256754881), but that should be it.

I'm hoping it can be reviewed and merged soon as it seems some other folks would like to take advantage of this feature too.

Looks like the terraform team are making their way through the backlog of PRs, so hopefully soon?

**Comment by stack72** [comment]
Closed via #8697

**Comment by niclic** [comment]
With this feature finally merged, you may encounter a backwards compatibility issue. Both the `arn` and `name` attributes were removed form the `aws_appautoscaling_target` resource. Unfortunately, these attributes were _not_ annotated with the `Deprecated` or `Removed` fields. Neither `arn` or `name` are required by `aws_appautoscaling_target` but you may have included them in your configurations and may encounter an error when using version `v.0.8.6`. 

See this note for details: https://github.com/hashicorp/terraform/pull/8697#issuecomment-278797631
