### ISSUE TITLE
Requiring "terraform get" for local filesystem module paths is poor for usability

### ISSUE THREAD

**Issue by sigil66** [hashicorp/terraform#8703]
### Terraform Version
Terraform v0.7.1

### Affected Resource(s)
Please list the resources as a list, for example:
- modules

### Expected Behavior
I would expect that for local modules:

```
module "hai" {
  source = "./modules/hai"
}
```

that terraform get not be required to be run. Alternatively an alternate syntax could be provided that does not require this linking step.

### Actual Behavior
I am prompted to run terraform get.

**Comment by mitchellh** [comment]
I don't disagree with you, but I also don't think it passes my threshold of "annoying enough" to make it worthwhile to special case local paths right now. The implementation as it is is very uniform and supports a vast swath of source URLs. It is easier to have a single code path to handle this rather than special case.
