### ISSUE TITLE
Add support for AWS CloudSearch

### ISSUE THREAD

**Issue by assembledadam** [hashicorp/terraform#8710]
Has been discussed before, but is yet to be integrated into Terraform AFAIK.

There is no CloudFormation resource for this, so I expect it means either having to create a custom resource or utilising the AWS API.

**Comment by kwilczynski** [comment]
@assembledadam you are correct, it would require creating a custom resource.

We always welcome Pull Requests and contributions, thus should you be in a burning need for this to be added, I would be more than happy to lend you a hand to get started. Adding a custom resource is not really that hard these days, plus contributing to the project is very rewarding.

In the meantime, please check this excellent talk by @stack72 which should give you a very good overview how to get started: https://www.youtube.com/watch?v=2BvpqmFpchI

I am sure you will find this talk quite insightful.

**Comment by kwilczynski** [comment]
Related #1786.

**Comment by idntfy** [comment]
+1

**Comment by stack72** [comment]
Hi @assembledadam 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
