### ISSUE TITLE
Terraform should support deprovisioners

### ISSUE THREAD

**Issue by liquidgecka** [hashicorp/terraform#8725]
Terraform can run scripts/actions when an instance is initially started, it would be great if it could run actions when an instance is _terminated_ too! For example, when I remove a node, I would love to remove its associated key in salt, which requires sshing to the salt master to perform the operation. As it stands I have to do that on my own but it would be great if terraform did it for me!

**Comment by marco-m** [comment]
@liquidgecka I was thinking the same (removing the minion key from the salt master). On the other hand, if the infra is autoscaling, Tf would not even see new minions coming and going, so maybe at the end the only robust way is to use the specific infra API to notify the salt master of the events (new minion, minion destroyed). I was wondering if you though about this.

**Comment by apparentlymart** [comment]
Hi @liquidgecka, @marco-m,

This is a pretty old issue that honestly just fell of our radar :confounded: but Terraform 0.9.0 added the idea of [_Destroy-time Provisioners_](https://www.terraform.io/docs/provisioners/index.html#destroy-time-provisioners) which allow provisioners to be run at destroy time _in certain situations_ as described in that documentation page.

As @marco-m noted, it's usually recommended to use features like autoscaling rather than having Terraform launch instances directly, in which case the instances must be able to manage their own lifecycle using code and configuration included in their machine images, rather than depending on Terraform to do it. We offer provisioners for the less-common situation where direct management of a single instance is the right approach, e.g. when spinning up dev/test environments.

Note that a Terraform provisioner with a given configuration will take the same action regardless of whether it's run at create or destroy time, so it's the user's responsibility to configure the destroy-time provisioner to take destroy-appropriate actions. The more complex provisioners that interact directly with configuration management systems, such as `chef` and `salt-masterless`, are generally only useful for create-time provisioning, so destroy-time provisioning will usually use `local-exec` and `remote-exec` for more direct control over the actions taken.

Since destroy-time provisioners are now in Terraform, I'm going to close this. Sorry this issue was missed when syncing up after the 0.9 release!

**Comment by liquidgecka** [comment]
Autoscaling really doesn't work for all use cases though. We spin up machines that need to have a direct IP on the internet which is something autoscale can't do. (or at least can't do with route53 integrations and such).

But I believe that the when = "destroy" works for us. I will have to go add it to test. =)

**Comment by marco-m** [comment]
Thanks @apparentlymart for the explanation.
