### ISSUE TITLE
Terraform Does Not Support Custom Regions

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/terraform#8783]
Terraform version `0.7`

Terraform has hard-coded regions for AWS while we use `terraform` for provisioning clusters in an EC2 compliant on premise cloud solution. This forces us to use only those regions which are recognized by terraform (in our case `us-east-1` and `phl-1`). Is there any workaround?

**Comment by kwilczynski** [comment]
@vrenjith hi there! Sorry that you are having a problem!

At the moment the code vide verify whether you have a correct AWS region set either in your environment or via other means. This means that anything which is not supported by AWS at the moment would cause a failure, and to my knowledge there is no way to workaround this at present.

I believe, we would have to add an extra option allowing for Terraform invocation bypassing region check, or change the check completely to pass anything as-is. Not sure which approach would be more desirable for the core maintainers.

To add, any compliant and/or AWS alike should support AWS official SDK, otherwise when you open an issue containing a genuine problem, it might be difficult for us to troubleshoot and possible fix it, keep this in mind. We would do our at most best to help, but sometimes it is not easy to work against a third-party.

**Comment by apparentlymart** [comment]
Hi @vrenjith! Thanks for this request.

I think this might be a different way of asking the same question posed in #6535. What do you think? If so, I'd like to close this issue and consolidate the discussion there.

**Comment by vrenjith** [comment]
That's right, we track track this under #6535 and close this one.
