### ISSUE TITLE
more builders

### ISSUE THREAD

**Issue by ceh** [hashicorp/terraform#879]
All platform builds that are made available on https://terraform.io/downloads.html should have an associated builder such that failures can be catched as early as possible.

Rationale, see multiple test failures on Windows:
* #878 
* #876 
* #872

Travis CI does currently not support FreeBSD, OpenBSD, nor Windows.
OS X is in beta and can be enabled according to http://docs.travis-ci.com/user/multi-os/

Alternatives? https://build.golang.org and http://build.camlistore.org comes to mind.

Related: hashicorp/consul#639

**Comment by mitchellh** [comment]
Thanks, we agree that this would be ideal. As of currently its still not easy enough to build out this infrastructure. I know because we tried to do it for Vagrant, and have for Vagrant installers. The best scenario here is to likely just wait out until more CI services have other platforms, since managing these puts a fairly large burden on people and its not something we want to pick up. 

There also isn't an "easy" way to do this. In short, it is: 1.) Find provider, 2.) Setup machine 3.) [MAYBE] Make automation for machine, not uniform on different OS 4.) Install system like Buildbot or similar to watch for changes, perhaps configure to master, 5.) Maintain over time with all changes (Go updates).

As I said, I know from experience that that process is a lot hairier than it looks, and I don't think we have the human resources to make that happen right now.

**Comment by ceh** [comment]
@mitchellh I realize that it is a lot of work and that it will require a large amount of resources.

That's why I opened an issue, because the community might be of help here since HashiCorp employees probably already have their hands full. (_Keep up the good work!_)
