### ISSUE TITLE
Update azurerm provider  to not require provider resource registration privileges

### ISSUE THREAD

**Issue by darinhoward** [hashicorp/terraform#8824]
### Actual Behavior

Using the **azurerm** provider **registerAzureResourceProvidersWithSubscription** is called. This requires the account in use to have access to register resources w/ a subscription. 
### Expected Behavior

The call being used could be replaced w/ https://msdn.microsoft.com/en-us/library/azure/dn790534.aspx that displays resource registration state without requiring the user to have access to change it. 
### Terraform Version

0.7.3  
### Related Commit

https://github.com/hashicorp/terraform/commit/c90718d1acbdc9ba66dfe0c88158245e3f44cff9

**Comment by jen20** [comment]
Hi @darinhoward! This is a possibility, but ultimately would need delegating to each resource or risk adding a bunch of additional network calls during provider configuration. I'm not opposed to either approach necessarily - I always thought the current mechanism was a hack and saw it as temporary. This needs some more thought in order to not ruin user experience - however, this is part of the underlying API so unavoidable.

**Comment by superseb** [comment]
Created https://github.com/jen20/riviera/issues/21 to create a fix for this.
