### ISSUE TITLE
Crash: unexpected EOF in azurerm_virtual_machine

### ISSUE THREAD

**Issue by tpetchel** [hashicorp/terraform#8843]
```
Error applying plan:

2 error(s) occurred:

* azurerm_virtual_machine.chef_server: unexpected EOF
* Script exited with non-zero exit status: 1
```

I am able to apply other Terraform plans, including on Azure. This one is different in that I'm bringing up Chef server from the Azure Marketplace. In fact, it's that `azurerm_virtual_machine` resource that's failing.

Gist available [here](https://gist.github.com/tpetchel/927425e8d83c4bb500b268224011dbbe) (Edited)
- Sorry for not providing a more minimal repo case.
- Any work-arounds are super appreciated 😸

**Comment by tpetchel** [comment]
Forgot to mention:

```
$ terraform --version
Terraform v0.7.3
```

**Comment by jen20** [comment]
Hi @tpetchel! To me this looks like the chef server image has a script running as user data (or whatever the Azure equivalent is) that is exiting with a non-successful status code and failing the resource creation. Unfortunately the crash log is truncated - it doesn't contain the relevant panic information. The main.tf file in the gist seems to relate to AWS rather than Azure? Could you clarify? Thanks!

**Comment by tpetchel** [comment]
Hi @jen20,

Thanks for the fast reply - apologies for the botched gist. Multitasking fail :) 

I created a new one gist here: https://gist.github.com/tpetchel/927425e8d83c4bb500b268224011dbbe

I do believe this is a crash bug because I get this in the output when I `terraform apply`:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by pmcatominey** [comment]
Hi @tpetchel 

I've looked at what caused the panic from the version of Terraform used at the time (0.7.3). This was a bug with how the `plan` block was read which was fixed in #10626 and was released as part of 0.8.0.

Let me know if you have any further issues.

Thanks!

**Comment by anupam0611** [comment]
I'm using terraform version 0.8.8 and running into same issue. Trying to launch resources in Azure from RHEL 7.3 and running into issues.
Snippet of my file:
# Configure the Microsoft Azure Provider

provider "azurerm" {
subscription_id = ""
client_id       = ""
client_secret   = ""
tenant_id       = ""
}

# Create a resource group
 resource "azurerm_resource_group" "test" {
  name     = "azuretest"
  location = "West US 2"
}

resource "azure_instance" "windows" {
  name                 = "terraform-test"
  hosted_service_name  = "terraformdemo1"
  image                = "Windows Server 2012 R2 Datacenter"
  size                 = "Basic_A1"
  storage_service_name = "terra"
  location             = "West US 2"
  username             = ""
  password             = ""

  endpoint {
    name         = "RDP"
    protocol     = "tcp"
    public_port  = 3389
    private_port = 3389
  }
}

output "azure-ips" {
value = "${join(",",azure_instance.windows.*.name)}:${join(",", azure_instance.windows.*.vip_address)}"
}


Error:

[root@ip-172-31-16-53 anupam]# terraform plan
var.azure_settings_file
  Enter a value: abc-credentials.publishsettings

provider.azure.publish_settings
  Enter a value:

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error refreshing state: 1 error(s) occurred:

* Insufficient configuration data. Please specify either a 'settings_file'
or both a 'subscription_id' and 'certificate'.

**Comment by ajitesh06** [comment]
hi @anupam0611 I'm facing the same issue, It would be great if u can guide me towards the solution. Thanks

**Comment by tombuildsstuff** [comment]
Hey @anupam0611 @ajitesh06 

The configuration posted above uses a combination of both the AzureRM provider and the older Azure (Service Management) Provider - you can note which of the two you're using by looking at the start of the resource name: resources in the AzureRM provider start with `azurerm` - and in the older Azure Service Management provider with `azure`.

[Here's an example of how to create a Virtual Machine using the AzureRM Provider](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#example-usage-with-managed-disks-recommended-) - which is I believe what you're after here? Otherwise, [here's an equivalent example for the older Azure Service Management provider](https://www.terraform.io/docs/providers/azure/r/instance.html)

Thanks!
