### ISSUE TITLE
Ability to get N elemets from a list

### ISSUE THREAD

**Issue by dene14** [hashicorp/terraform#8846]
Hi there,

is there any ability to get a sublist from a list? After data sources release (damn, they're so sweet) that become really desired functional.

For e.g. there is "aws_availability_zones" data source and we can easily allocate multi-zoned environment with interpolation, however in some cases there is 5 AZ available whereas only 2 required for particular project. Is there any way to do that or can we expect such feature soon?

**Comment by apparentlymart** [comment]
Hi @dene14!

There isn't a direct way to do this right now, but I have some workarounds for you:

If you specifically want the first two in the list, and you know there are at least two (which for AWS Availability Zones seems like a reasonable assumption) then you can just list them out manually:

```hcl
[
  "${data.aws_availability_zones.available.names[0]",
  "${data.aws_availability_zones.available.names[1]",
]
```

We also have the `random_shuffle` resource, whose initial use-case was to pick any two AZs from the available set:

```hcl
resource "random_shuffle" "az" {
  input = ["${data.aws_availability_zones.available.names}"]
  result_count = 2
}
```

If you use this one, it's important to understand [the constraints and caveats relating to the `random` provider](https://www.terraform.io/docs/providers/random/index.html).

With all of that said, a function for slicing a sub-list out of a list seems like a very reasonable request, so I'll leave this issue here as a request for that. :grinning:

**Comment by wr0ngway** [comment]
👍 a `slice` interpolation function would do it for me
`slice(begin_idx[, end_idx])` where an index can be negative to indicate counting back from the the end of the list, and end_index is optional to indicate slicing to the end of the list.

**Comment by ewbankkit** [comment]
One way I've found of working around the lack of such functionality is to use the `replace()` function on a string representation of the list. For example, to remove the last ID from a list of subnet IDs:
```
"${split(",", replace(join(",", aws_subnet.foo.*.id), "/,subnet-[[:xdigit:]]+$/", ""))}"
```
* Create a string representation of the list using `join()`
* Manipulate using `replace()` and the power of regular expressions
* List-ify the result using `split()`

BTW, not recommending this as in any way maintainable in the long term 😄.
