### ISSUE TITLE
Unable to destroy resources nested in modules.

### ISSUE THREAD

**Issue by BrokenFlame** [hashicorp/terraform#8850]
TerraForm v0.7.3
Terraform is no longer able to destroy AWS resources nested in modules which are dependant on variables contained in the module definition.

To reproduce this:
Create a TerraForm module named "environment.tf", in the environment.tf declare and refer to a folder containing AWS_Subnets.tf. In the environment.tf declare a variable "vpc_subnets" = 2

In the AWS_Subnets declare:
```
resource "aws_subnet" "public" {
    count = "${var.vpc_subnets}"
    availability_zone = "eu-west-1"
    vpc_id = "vac-0001"
    cidr_block = "${cidrsubnet("10.0.0.0/16", 3, count.index )}"
}
```

This will build the infrastructure fine.
```
terraform apply -target=module.environment
```

However you won't be able to destroy the infrastructure
```
terraform destroy -target=module.envionment
```

ERROR:
```
*** 1:3: unknown variable accessed: var.vpc_subnets in:
${var.vpc_subnets}**
```

**Comment by BrokenFlame** [comment]
This is on TerraForm 0.7.3

**Comment by mitchellh** [comment]
Unfortunately I can't reproduce this.

From your description, it sounds like you may be defining the variable in the _root_ module rather than the "environment" module. Variables must be defined within the module that uses them. 

You may have suddenly hit this error because we only enabled verification that variables are defined perhaps 3 or 4 releases ago. This used to happen in prior releases and at some point broke so we were fixing that issue but it did catch some people unaware.
