### ISSUE TITLE
lifecycle  prevent_destroy not working for aws_eip resource

### ISSUE THREAD

**Issue by icadariu** [hashicorp/terraform#8851]
Hi,

Terraform ignores lifecycle prevent_destroy on aws_eip resource:

### Terraform Version
Terraform v0.7.3

### Affected Resource(s)
- aws_eip

### Terraform Configuration Files
```hcl
resource "aws_eip" "eip_nat" {
  instance                    = "${aws_instance.nat.id}"
  vpc                         = true
  lifecycle { prevent_destroy = true }
}
```

### Debug Output
module.nat_instance.aws_eip.eip_nat: Destroying...
module.nat_instance.aws_eip.eip_nat: Destruction complete

### Steps to Reproduce
`terraform apply`

**Comment by icadariu** [comment]
Anyone

**Comment by gregoryguillou** [comment]
:+1:  It looks like it globally broken ; I've tried with random_id and null_resource and, as you can see from below:

```
cat locker.tf
resource "random_id" "locker" {
  byte_length = 8
  lifecycle {
      prevent_destroy = true
  }
}
```

When I remove the resource, I can delete it no error:

```
mv locker.tf locker.tf.disabled
terraform apply 
random_id.locker: Destroying...
random_id.locker: Destruction complete
Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

I'm running Terraform 0.7.4

**Comment by gregoryguillou** [comment]
Hello,

I've pushed the investigations furthermore. It actually works as expected (even though I would have expected more):
- if you perform a ```terraform destroy``` or ```terraform plan -destroy``` you get the error telling you cannot destroy the resource. 
- however, if you remove the file containing the resource from the model and run ```terraform apply``` it deletes the resource no problem

It cannot do more since there is nothing in the state file saying the resource cannot be destroyed. Since the command you run is ```apply``` and not ```destroy```, it is probably not a bug but somehow the expected behavior.
  
Gregory

**Comment by gregoryguillou** [comment]
Hello @icadariu

@phinze has suggested terraform should, somehow at some point, store the prevent_destroy lifecycle property in the state file (see https://github.com/hashicorp/terraform/issues/6772 ). However its not the case yet (0.7.4). If you'd deleted the resource with a ```terraform apply``` like I understand you did and like I did, this is unfortunately not a bug but somehow expected. 

I would love to have the lifecycle stored in the state file as an enhancement of Terraform. Maybe you should open an enhancement request.

Gregory

**Comment by icadariu** [comment]
@gregoryguillou Thanks for your help. You are right.
