### ISSUE TITLE
Feature request: new data source for aws_subnet

### ISSUE THREAD

**Issue by zms** [hashicorp/terraform#8860]
Is there a way to query subnets using new data source like we can for AWS AMIs?  If not, would you please consider adding this?

Additional data sources that would be very useful: VPC, routing tables, DHCP option set, security groups and network ACLs.

*Scenario*: This is will allow me to query and use subnets dynamically when deploying specific types of workloads in subnets suitable for them (based on NACLs and routing etc.) without having to query them externally and populating variables before calling terraform.  The scripts then also become portable between VPCs without hardcoded dependencies (as long filter pattern is satisfied).

**Comment by apparentlymart** [comment]
Thanks for the feature request, @zms.

I'm working on this over in #6819. I still have a little work to do there before it can be merged but hopefully it won't be too long.

I haven't covered everything you've listed in there yet, but we should be able to add the remaining stuff pretty easily afterwards since the structure of all of these is basically the same.

**Comment by mfischer-zd** [comment]
Yes please!

**Comment by zms** [comment]
@apparentlymart: thank you.  looking forward to it.  just say the word if you need any testing. :)

**Comment by apparentlymart** [comment]
I just realized that I left this dangling when #6819 was merged.

[`aws_subnet`](https://www.terraform.io/docs/providers/aws/d/subnet.html) was introduced in the 0.7.6 release. We also added [`aws_vpc`](https://www.terraform.io/docs/providers/aws/d/vpc.html) in 0.7.6 and `aws_security_group` will be in the forthcoming 0.7.8 release.

We didn't get routing tables or DHCP option sets in yet, but they are unlikely to be difficult since they can re-use the helper functions added for the first set of VPC data sources, but I'm going to close this issue out and we can attack those in separate PRs.

Thanks again for the feature request, and for the patience while I got it done!
