### ISSUE TITLE
provider/aws: Allow setting security token via provider configuration

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform#8996]
I'd like to use multiple providers to deploy resources into two AWS accounts.  But my only access is via IAM roles.  So I can't supply a static key pair to the providers, and have to use env vars.  

Below is a simplified version of my config with two accounts, alpha and omega.  Suppose I setup alpha STS creds in my environment and run terraform.  Then I get "Account ID not allowed" error for the omega resources.

If `-target` is used to specify a resource associated with the current environment credentials, terraform works fine.  With a real config, this is tedious and error-prone.  But it means some nearby features would get this kind of cross-account deployment working:
1. If the current account is not in a provider's `allowed_account_ids`, skip all resources associated with that provider.
2. Allow `-target` to take a provider alias.  Interpret this like `-target` was specified for each resource that depends on the specified provider.
3. Permit the aws provider to take `security_token`, so STS credentials could be passed in at runtime via a variable.
### Terraform Version

Terraform v0.7.4
### Affected Resource(s)
- `aws_*`
- `provider.aws`
### Terraform Configuration Files

``` hcl
provider "aws" {
  alias = "alpha"
  region = "us-east-1"
  allowed_account_ids = ["${var.alpha}"]
}

provider "aws" {
  alias = "omega"
  region = "us-east-1"
  allowed_account_ids = ["${var.omega}"]
}

resource "aws_iam_role" "alpha-role" {
  provider = "aws.alpha"

  name = "alpha-role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_iam_role" "omega-role" {
  provider = "aws.omega"

  name = "omega-role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": ["arn:aws:iam::${var.alpha}:role/alpha-role"]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}
```
### References

Originally submitted as a comment about the crash on GH-8923 before I knew terraform v0.7.4 was released.

**Comment by apparentlymart** [comment]
Hi @rvandegrift. Sorry for the problems here.

Probably the most likely short-term solution here is your option 3: allow setting the security token via a new provider argument. That way it can potentially set using Terraform variables and then in turn using environment variables again:

```
provider "aws" {
  # ...

  security_token = "${var.alpha_security_token}"
}
```

```
export TF_VAR_alpha_security_token=abc123abc123
terraform plan ...
```

The other options you suggested are interesting; I want to reflect on those a little more since it feels like an odd UX for Terraform to just silently ignore something, so we'd need to figure out the right way to Terraform to explain what's going on and lead the user in this case.

A further option, and one I would usually recommend, is to split your configuration into two modules, each of which creates only the infrastructure in one account. Then apply each of them separately and optionally make a third module that uses the `terraform_remote_state` data source to capture the outputs of the two "physical" modules and present the result as a single, unified "logical" module for other configurations to consume.

**Comment by rvandegrift** [comment]
Agreed the UX could be weird.  I think options 1 and 2 should be discarded - those ideas only work in simple cases.

Suppose three resources are split between the two accounts.  `alpha-1` depends on `omega-1` which depends on `alpha-2`.  There's no cycle here.  But options 1 and 2 would require at least two terraform runs against alpha to complete the deployment.  More complicated cross-account dependencies would require more flip-flops between the accounts to complete all of the work.  That's a pretty bad user experience.

Option 3 avoids that issue by making all providers available for the existing dependency resolution.
