### ISSUE TITLE
Terraform documentation lists IAM policy resources key as optional, but without it AWS rejects the document

### ISSUE THREAD

**Issue by farmdawgnation** [hashicorp/terraform#9002]
### Terraform Version

> Terraform v0.7.4

### Affected Resource(s)

- aws_iam_policy data source

### Expected Behavior

Either Terraform should have created a valid aws_iam_policy without me specifying resources, because [the documentation](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html) indicates that the parameter is optional (see below), or the documentation should be updated to reflect that this parameter should not be optional.

<img width="712" alt="screen shot 2016-09-22 at 4 13 08 pm" src="https://cloud.githubusercontent.com/assets/620189/18764459/7e85e528-80df-11e6-943c-ea5512227fa7.png">

### Actual Behavior

I got the following error:

```
MalformedPolicyDocument: Policy statement must contain resources.
```

### Steps to Reproduce

Create an IAM policy like so:

```
data "aws_iam_policy_document" "bad" {
    statement = {
        actions = [
            "cloudwatch:PutMetricData"
        ]
    }
}

resource "aws_iam_policy" "bad_policy" {
    name = "this-wont-work"
    description = "A policy that blows up."
    policy = "${data.aws_iam_policy_document.bad.json}"
}
```

And attempt to create this policy in AWS with Terraform.

**Comment by optimisticanshul** [comment]
@farmdawgnation i don't think resource will be optional in this.

**Comment by vancluever** [comment]
@farmdawgnation - Sorry for the confusion here. Unfortunately this is a bit of a confusing subject - the field is optional *in Terraform* - but not in the AWS policy you are sending the document to (an IAM policy).

If this policy was being applied as a resource policy (ie: S3, KMS, etc), then it's optional, because the resource is known in that instance, however, you may need to supply other items like `principal`.

Just wanted to clear that up. It does sound like it's a good idea to update the documentation to be a little more specific, but hopefully this help you with what you are trying to do in the meantime!

**Comment by apparentlymart** [comment]
Indeed this is an issue with "layering"... the generic `aws_iam_policy_document` data source doesn't know what you plan to do with this policy, so it can't enforce additional constraints that are present on certain services, nor document them specifically.

This tends to be a problem within official AWS docs too... they will say "an IAM policy document" without describing specifically what aspects of it are required or implied.

We could perhaps address this by adding more docs to the resource attributes where policies are expected. e.g. in the documentation for the `aws_iam_policy` argument `policy` we could state that in this particular case the policy *must* include at least one resource expression in each policy statement.
