### ISSUE TITLE
Pending PRs and Documentation Backlog

### ISSUE THREAD

**Issue by mrjcleaver** [hashicorp/terraform#9076]
Terraform is moving along at a cracking pace... to the extent that the outstanding contributions forms a significant queue.

Whereas providers such as vsphere used to be external but are now built-in I get the sense that changes were more readily incorporated when held in isolated provider projects.

I assume the core system is taking a cautious approach, but there are PRs dating back 4 months.

It would be useful:
1) If there was a designated vsphere integration fork that was more aggressive at integrating PRs(*) and outstanding documentation
2) If there was a documentated vsphere centric tutorial that could be checked out and followed

  (*) E.g. for vsphere... https://github.com/hashicorp/terraform/pulls?utf8=✓&q=is%3Apr%20is%3Aopen%20vsphere has 10+ PRs dating back 4 months

**Comment by mrjcleaver** [comment]
@chrislovecnm - thoughts?

**Comment by mitchellh** [comment]
Hey @mrjcleaver. I agree, and it sounds like your concerns are with vSphere specifically. Our outstanding issue with the vSphere provider is that it is a COMMUNITY provider[1] and yet we don't have a ton of attention given to it. We might have one core committer on it... but I'm not sure on that.

Community providers require a champion from the community (1 or more) to help drive it forward otherwise they can and will stagnate. We only ask that community members adhere to our contribution guidelines related to testing and so on. For example, jtopj1an (replace 1 with "i", didn't want to ping him) is our primary OpenStack maintainer and he does a really fantastic job keeping OpenStack up to date and bug free.

An issue for HashiCorp employees who can and do look at community providers routinely is that we don't yet have a vSphere cluster up and running to verify changes. This means that we just can't merge those PRs until someone in the community validates them for us. We're also working on this and we're close!

Meanwhile, we're also engaging in conversations with VMware and other companies to try to find a way to more officially support vSphere. Most of those conversations are necessarilly under NDA so I'm not allowed to say anything related to their contents until we have a resolution.

I hope this answers your questions about this!

[1]: https://www.hashicorp.com/blog/terraform-improve.html
