### ISSUE TITLE
crash when building route53 stuff

### ISSUE THREAD

**Issue by serialdoom** [hashicorp/terraform#9091]
### Terraform Version
#terraform -v
Terraform v0.7.3

Your version of Terraform is out of date! The latest version
is 0.7.4. You can update by downloading from www.terraform.io

### Affected Resource(s)
- aws_route53_record

### Terraform Configuration Files
https://drive.google.com/open?id=0B6JMz9WnoXZAbGJ3d1ZfaGFXcTA
(gpg encrypted)

### Panic Output
https://gist.github.com/serialdoom/ab4b80699376f04fd49d9d84bf4e2d03

### Expected Behavior
create a bunch of route53 entries

### Actual Behavior
crash

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @serialdoom 

Thanks for opening the issue here - apologies this has caused you issues! Luckily, I *just* merged a PR this morning that actually fixes your issue (#9049) - this will be included in the Terraform 0.7.5 release

Please keep an eye out for that and upgrade to get the fix

Sorry again

Paul

**Comment by serialdoom** [comment]
@stack72 can you have a look if [this](https://drive.google.com/open?id=0B6JMz9WnoXZAZWxSNnp2WmV0ZEE) is the same failure ? this happened when doing a 

```
terraform destroy
```

[command line log](https://gist.github.com/serialdoom/0f1509ec9534ead71183acf6fda09aab)

**Comment by stack72** [comment]
Hi @serialdoom

It is indeed the same error. Basically, I introduced a change to the mix that polled for Deletes to be in sync so that creates could happen afterwards - this was breaking a good old fashioned delete.

We had the following code:

```
respRaw, err := deleteRoute53RecordSet(conn, req)
	if err != nil {
		return errwrap.Wrapf("[ERR]: Error building changeset: {{err}}", err)
	}

	changeInfo := respRaw.(*route53.ChangeResourceRecordSetsOutput).ChangeInfo
	
	err = waitForRoute53RecordSetToSync(conn, cleanChangeID(*changeInfo.Id))
	if err != nil {
		return err
	}
```

When it was an actual delete and there was no change info waiting to be synced, we then tried to dereference the pointer changeInfo.Id when it had no value

This was the issue. If you want, you can build TF from master and try it locally and check that the scenario is working for you - would that make you more confident?

P.

**Comment by serialdoom** [comment]
im cool - just checking to make sure i didnt stumble upon another issue.
Cheers!

**Comment by stack72** [comment]
well worth checking! :)
