### ISSUE TITLE
Hacky syntax!?

### ISSUE THREAD

**Issue by dennybaa** [hashicorp/terraform#9095]
Hello everybody,

terraform is a great tool, however it's very often creates crazy limitations due to its syntax...

Obviously there are tons of not-implemented things one of them **map of lists**.  I'm trying to merge hashes for further writing them json into and even with all the whistles terraform has it's still nontrivial.

I end up doing smth like this

```
data "null_data_source" "attributes" {
    inputs {
        jsonbody = "{ ${join(",",
            list(
                "${jsonencode("run_list")}: ${jsonencode(var.run_list)}",
                "${replace(jsonencode(var.attributes), "^{|}$", "")}"
            )
        )} }"
    }
}
```

which is totally inappropriate)))

So again I'm voting for fixing syntax issues and basic data structures. What seems to me will make terraform experience enjoyable is normal esacping, here again please:

```
variable "name" {
    type = "string"
    default = "{}"
}

output "name" {
    ### How this supposed to be?
    value = "${replace(var.name, "{", "")}"
}
```

Basic quoting things like `\"`, or `\{` or smth else I don't know even what, they don't work and it's already **0.7** version. Disappointing...

**Comment by mrjcleaver** [comment]
The Hashicorp EU conference keynote, around the 18 minute mark, introduces List and Map.

**Comment by dennybaa** [comment]
@mrjcleaver Thanks, I know it well. Btw it's also pretty well covered in the tf documentation.
In fact, though basic data structures exist, they don't work for many things including template generation and evaluation.

Do you have another point of view? 

Maybe you could suggest how to make this work

```
variable "list" { default = ["hello", "world"] }
variable "map" { default = { hello = "world" } }

data "null_data_source" "foo" {
    inputs {
        list_not_working = ["${var.list}"]
    }
}

data "null_data_source" "bar" {
    inputs {
        map_not_working = "${var.map}"
    }
}
```

Or maybe this

```
data "null_data_source" "attributes" {
    inputs {
        jsonbody = "${jsonencode(
            merge(
                map("run_list", var.run_list), var.attributes
                ))}"
    }
}
# ==>
Errors:

  * jsonencode: map values must be strings in
```

**Comment by apparentlymart** [comment]
Hi @dennybaa! Sorry for the long silence here.

This issue seems to be covering a general dissatisfaction with limitations with the Terraform Language, which I can understand completely. However, that means it's hard to reach a point were we could definitively call this issue "done".

We've made a lot of investments in the Terraform Language for the forthcoming v0.12.0 release which are now in the master branch. Some of the headline features are covered in [the preview blog series](https://www.hashicorp.com/blog/terraform-0-1-2-preview) from a few months ago, though it also includes some rework of low-level aspects to make basic data structures and expressions work in a more intuitive way, which I think will address many of your frustrations here.

Since I'm not sure how else to think about the completion of this issue, I'm going to close this out now assuming that the work already merged in master addresses most of the problems here. I'm sure there will be some different feedback after the release of further things we could refine, but we can discuss those in separate issues with a more defined scope.

Thanks for reporting this feedback, and sorry again for letting this sit here for so long.
