### ISSUE TITLE
Terraform does not detect existing kinesis stream

### ISSUE THREAD

**Issue by boompig** [hashicorp/terraform#9141]
### Terraform Version
Terraform v0.7.0

### Affected Resource(s)
- aws_kinesis_stream
- aws_s3_bucket
- aws_iam_role

### Terraform Configuration Files
```hcl
resource "aws_kinesis_stream" "kinesis_stream" {
        # providing the arn allows to avoid creating duplicate resource and getting errors
        arn = "arn:aws:kinesis:${var.region}:${var.account_id}:stream/${var.kinesis_stream}"
    name = "${var.kinesis_stream}"
    shard_count = 1
}
```

Note that the error persists if I include the ARN (which is redundant) or no.

Also note: there is no way to specify region outside the ARN.

### Expected Behavior
During `terraform plan`, if stream exists should not output stream creation as part of the plan.

### Actual Behavior
Clipped output from `terraform plan` (after running `terraform apply` once with the same config file):

```
+ aws_kinesis_stream.kinesis_stream
```

After applying

### Steps to Reproduce
```
terraform plan
terraform apply
terraform plan
```

with configuration file above

**Comment by boompig** [comment]
Also persists after `terraform refresh` followed by `terraform plan`.

Looking at the debug log, this is probably the relevant line:
```
2016/09/29 18:00:45 [DEBUG] refresh: aws_kinesis_stream.kinesis_stream: no state, not refreshing
```

**Comment by boompig** [comment]
Also note that there are similar problems with resources `aws_s3_bucket` and `aws_iam_role`.

**Comment by boompig** [comment]
I suspect this has something to with the the lack of `Importer` line in the resource declaration lines. For example [resource_aws_lambda_function](https://github.com/hashicorp/terraform/blob/v0.7.0/builtin/providers/aws/resource_aws_lambda_function.go#L27) does have it while [resource_aws_kinesis_stream](https://github.com/hashicorp/terraform/blob/v0.7.0/builtin/providers/aws/resource_aws_kinesis_stream.go#L22) does not. This is also true for `aws_s3_bucket` and `aws_iam_role` in the affected version.

**Comment by apparentlymart** [comment]
Hi @boompig!

Currently Terraform never intentionally "takes ownership" of an existing resource. This is to reduce the risk that the user will unintentionally update or delete something pre-existing when intending to create something.

In some cases, such as with `aws_s3_bucket_object`, we are unable to distinguish between the "create" and "update" actions due to limitations of the underlying API. But in most cases we deliberately distinguish these cases, intentionally returning an error in the event that an existing resource is in conflict.

As you noticed, we have some initial and growing support for importing various resources, but import is only supported as explicit user action with [the `terraform import` command](https://www.terraform.io/docs/import/usage.html). For any resource for which an importer has been implemented, you should be able to avoid the issue you're describing by explicitly importing it before you plan and apply.

New importers are being added over time, so I'm sure `aws_kinesis_stream` will eventually get one. Since what you described is actually intended behavior I'm going to close this, though do feel free to open a separate feature request for an `aws_kinesis_stream` importer if that feature is important to you.

In the mean time, the following article may be useful in working around the lack of a Kinesis Stream importer by exploiting some knowledge of how Terraform represents these things internally. It was written some time ago for Terraform 0.3, but the techniques described are still possible today:
https://dark.ca/2015/01/27/handling-extant-resources-in-terraform/
