### ISSUE TITLE
Adding accelerate_status on S3 bucket should change the id of the bucket

### ISSUE THREAD

**Issue by plorent** [hashicorp/terraform#9183]
When adding 'accelerate_status=Enabled' on an existing S3 bucket, a 'terraform plan' will not change other resources that depend on the id of the S3 bucket.
When enabling Transfer Acceleration, the endpoint will change so other resources must be changed to use the new endpoint.

Terraform v0.7.4

**Comment by stack72** [comment]
Hi @plorent 

Is it true that the endpoint for a resource changes? Have you got a config that can reproduce this? It *should* just be a PUT request on a bucket that doesn't affect the bucket's endpoint

Paul

**Comment by plorent** [comment]
From the AWS documentation:
"When uploading to or downloading from the Transfer Acceleration enabled bucket you must use the bucket endpoint domain name bucketname.s3-accelerate.amazonaws.com to get accelerated data transfers."
http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

**Comment by plorent** [comment]
The id of the bucket will indeed not change and as far as I can tell, Transfer Acceleration can be leveraged using the Amazon SDK. While a question remains why we can set accelerate_status in Terraform, this is not a bug.

**Comment by kwilczynski** [comment]
@plorent hi there! Thank you for getting in touch about this.

There is no easy path to solve this problem at the moment, especially if we have enabled acceleration after creating the S3 bucket. Especially since the ID would not change, plus changing the original ID internally is probably not a desirable outcome - it might trigger a cascade of changes and/or updates which might cause a lot of grief to the existing infrastructure.

You could try to solve this problem by having an output from a module to wrap around bucket creation that changes depending on whether the option is set (e.g. by having a variable you could inspect, etc.), or alternatively create the S3 bucket with the option enabled at the beginning. Albeit, I need to check whether the endpoint handed back is the updated one (which supports acceleration), or the old one (which might be the case regardless of whether acceleration is enabled or not, and it would mean that AWS leaves using new endpoint URL to you).

**Comment by catsby** [comment]
Hello @plorent – 

Sorry to say that I don't believe this is a bug with Terraform. There seems to be 2 defined URLs for using the accelerate feature, so I recommend using these formats:

``
${aws_s3_bucket.bucket_resource.bucket}.s3-accelerate.amazonaws.com
${aws_s3_bucket.bucket_resource.bucket}.s3-accelerate.dualstack.amazonaws.com
```

Doing so will cause any downstream resources to change, if the S3 resource `bucket_resource` were to change.

**Comment by plorent** [comment]
Agree (already posted that it's not a bug). The SDK must be leveraged to use the acceleration.
