### ISSUE TITLE
depends_on should be used in destroy to order resource destruction

### ISSUE THREAD

**Issue by goraxe** [hashicorp/terraform#9211]
Hey

In a vpc setup I have going, I have an instance that depends_on a internet gateway and a route table association.  When I terraform destroy the internet gateway is destroyed before the instance.  The gateway cannot be destroyed until the instance has been removed.  So I need manual intervention to 

### Terraform Version
v0.7.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_internet_gateway
- aws_subnet
- aws_vpc
- aws_route_table
- aws_main_route_table_association
- aws_route_table_assocaiation

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Sorry can't, company copyright and what not.   Might be able to come up with a test case if required.  

### Expected Behavior
The instances should have been shutdown as reverse dependencies, before the IGW 

### Actual Behavior
The IGW is sent the destroy API call before the instances.  The IGW cannot be destroyed until the EIP have been released.  So terraform errors out

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
nope

### References
not as far as I know.  Did a quick search to check if a know issue already

**Comment by mitchellh** [comment]
I added tests for this in 68dcb93, both a high-level black box-ish test as well as a test on the graph construction itself. Both properly create the edge so that `depends_on` is taken into account.

I also made a test where the configuration is deleted and only the state with the dependencies is kept and even in that case the destroy ordering is correct. 

And finally, for good measure, I created a real config with a VPC, internet gateway, subnets, etc. trying to match your basic use case. The destroy ordering there (with -parallelism=1 for strict ordering, so no races) is also correct.

Ultimately, I couldn't reproduce this issue in any case. There are a couple scenarios here: 1.) it was fixed recently. or 2.) you may have a typo in your `depends_on` field.
