### ISSUE TITLE
aws_key_pair can only use aws_provider region.

### ISSUE THREAD

**Issue by dmikalova** [hashicorp/terraform#9247]
### Terraform Version
0.7.4

### Affected Resource(s)
aws_key_pair

### Terraform Configuration Files
Any standard config will work.
```hcl
resource "aws_key_pair" "mod" {
  key_name   = "${var.key_name}"
  public_key = "${var.pub_key_file}"
}
```

### Expected Behavior
You should be able to create a key pair in any region.

### Actual Behavior
You can only create a key pair in the aws_provider's default region.

### Important Factoids
You can work around this with provider aliases.

```hcl
provider "aws" {
  alias  = "${var.region}"
  region = "${var.region}"
}

resource "aws_key_pair" "mod" {
  provider = "aws.${var.region}"

  key_name   = "${var.key_name}"
  public_key = "${var.pub_key_file}"

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by apparentlymart** [comment]
Hello!

In general for regionalized resources Terraform will only create things in the provider's configured region, because the provider uses the set of API endpoints for that region and they are not able to create objects for other regions.

Is there a reason why you are interested in foreign region *security groups* in particular, or is this just a general observation about the AWS provider in general? As you noted, having multiple instances of the provider using aliases is the intended way to do this that generalizes across all resources.

**Comment by dmikalova** [comment]
Hmm, I just started making our terraform config multiregion and these are the only resources that caused an issue. But now that I'm looking at other resources they all work like this - it looks like I just ended up taking the region declaration for granted.

Closing the issue now that I see it's expected behaviour.

**Comment by mabushey** [comment]
This should not be closed out. "Expected behavior" != correct behavior.
