### ISSUE TITLE
How to use -var with terraform get ?

### ISSUE THREAD

**Issue by ctindel** [hashicorp/terraform#9329]
I don't seem to be able to use terraform get with the -var option working with modules.  Please advise.  Here's an example based on the module documentation example:

main.tf:

```
module "child" {
    source = "./child"

    memory = "${var.memory}"
}

output "child_memory" {
    value = "${module.child.received}"
}
```

child/main.tf:

```
variable "memory" {}

output "received" {
    value = "${var.memory}"
}
```

If I just run "terraform get" I see:

#terraform get
Get: file:///Users/ctindel/tmp/tftest/child
Error loading Terraform: module root: 1 error(s) occurred:

* module 'child': unknown variable referenced: 'memory'. define it with 'variable' blocks

And if I run terraform get -var 'memory=1G' I get a usage error.

Please advise.

### Terraform Version

Terraform v0.7.5

**Comment by apparentlymart** [comment]
Hi @ctindel,

I think the problem here is that you have referenced `var.memory` in your top-level `main.tf`, but that variable isn't defined there. Each module has its own set of variables, so if you want to have a "memory" variable in both the parent and child module then both of them need to have a `variable "memory"` block.

This error is not telling you that you need to add a `-var` argument, but rather that the `variable "memory"` block is missing from the configuration. `terraform get` doesn't resolve variables, so there's no need to set `-var` arguments on that command.

**Comment by ctindel** [comment]
@apparentlymart thanks for that, I really appreciate it.  It does seem to be working now!
