### ISSUE TITLE
how to get grantee information of AWS S3 bucket into control

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#9362]
Terraform v0.7.5

I import existed bucket by `terraform import aws_s3_bucket.bucket bucket-name`, but I can not find information about grantee in the tfstate file, like below:

![screen shot 2016-10-14 at 09 53 39](https://cloud.githubusercontent.com/assets/759107/19372357/50bf9062-91f6-11e6-8e63-87c3b3885994.png)

How to get this information in to terraform control?

**Comment by kwilczynski** [comment]
@hanks hi there! I believe this is not yet supported (the fine grained permission on the buckets).

**Comment by hanks** [comment]
@kwilczynski Thank  you for your apply.  :)

**Comment by kwilczynski** [comment]
@haklop hi! I have a good news, though. There are tickets opened to implement this, and I looked at adding this myself, therefore keep an eye on upcoming releases. And thank you for patience!

**Comment by ameir** [comment]
This is something I bumped into recently.  Is this still something that's in the plans?

**Comment by jonathanhle** [comment]
+1

**Comment by mildwonkey** [comment]
Hi all,

Issues with the terraform aws provider should be opened in the [aws provider repository](https://github.com/terraform-providers/terraform-provider-aws).

Because this closed issue is generating notifications for subscribers, I am going to lock it and encourage anyone experiencing issues with the aws provider to open tickets [there](https://github.com/terraform-providers/terraform-provider-aws).

Please continue to open issues here for any other terraform issues you encounter, and thanks!
