### ISSUE TITLE
Feature Request: support count (and other meta-parameters) on module

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform#9423]
Hi there,

It'd be splendid if `count` , and potentially ALL meta-parameters, could be a reserved and operable for modules. The primary aim is really to support `count` specifically, however all meta-parameters are very useful in controlling flow and operation of Terraform plans.

In the case of `count` support, this also greatly simplifies `terraform get`, where it would get the module once, and link to the singular download.

### Terraform Version
v0.7.5

### Affected Resource(s)
- module

### Terraform Configuration Files
```hcl
module "foo"
  count = 4
  ...
}
```
vs.
```hcl
module "foo1"
  ...
}
module "foo2"
  ...
}
module "foo3"
  ...
}
module "foo4"
  ...
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The module is repeated with the input variables N times where N = count

### Actual Behavior
A variable `count` is populated with the value provided to `count`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
N/A

### References
Searched, but unable to find due to the frequency that `module` and `count` are used - too many results to sift.

**Comment by apparentlymart** [comment]
Hi @mengesb!

Thanks for this feature request. There is in fact a pretty old issue #953 about this already, but I can understand that you wouldn't find it since it's way back in the triple-digit issues!

Having this capability would be a pretty awesome way to deal with repeated groups of resources, so I'm definitely excited about it... but see #953 for the various discussions about why this unfortunately isn't as easy as it first appears :disappointed:

I'm going to close this one to consolidate over there, but thanks again for taking the time to open this, and for the effort at trying to track down an existing issue. :grinning:
