### ISSUE TITLE
provider/aws: Support Import aws_codedeploy_app

### ISSUE THREAD

**Issue by jakauppila** [hashicorp/terraform#9427]
Just tossing this out there as a feature request for importing aws_codedeploy_app. We're running an infrastructure pipeline between our application environments that share an aws_codedeploy_app; ideally we could run an import on it during our runs so everything outside of the first execution could pick it up.

I may try and take a look at the other import PRs and take a stab at it if I can get the time to.

**Comment by brmcconn** [comment]
+1  
I am in a similar situation with CodeDeploy applications shared across environments in separate terraform executions (separate state file per environment). Without being able to import aws_codedeploy_app, we have to hardcode the app name into our terraform config for aws_codedeploy_deployment_group rather than referencing to it IE:

resource "aws_codedeploy_deployment_group" "foo" {
    app_name = **"${aws_codedeploy_app.foo_app.name}"**
    deployment_group_name = "bar"
    service_role_arn = "${aws_iam_role.foo_role.arn}"

    ec2_tag_filter {
        key = "filterkey"
        type = "KEY_AND_VALUE"
        value = "filtervalue"
    }

**Comment by Jakauppila** [comment]
@jen20 Here's the issue for the resource that you added when we chatted at the other day at re:Invent.
