### ISSUE TITLE
Certificate private keys not hashed for `aws_api_gateway_domain_name` resource

### ISSUE THREAD

**Issue by henrytk** [hashicorp/terraform#9452]
### Affected Resource(s)
- `aws_api_gateway_domain_name`
### Expected Behavior

Based on the behaviour of the `aws_iam_server_certificate` resource I would expect the [`certificate_private_key`](https://github.com/hashicorp/terraform/blob/v0.7.7/builtin/providers/aws/resource_aws_api_gateway_domain_name.go#L39) field to be hashed before being stored in the state file.

The expected implementation would be a `StateFunc`, such as the pre-existing [`normalizeCert`](https://github.com/hashicorp/terraform/blob/v0.7.7/builtin/providers/aws/resource_aws_iam_server_certificate.go#L199-L216) function which is [used to hash the private key](https://github.com/hashicorp/terraform/blob/v0.7.7/builtin/providers/aws/resource_aws_iam_server_certificate.go#L50) of the `aws_iam_server_certificate` resource.
### Actual Behavior

The certificate private key is stored as plain text.

**Comment by apparentlymart** [comment]
Hi @henrytk,

There are some complexities around this technique of hashing things in the state... in general we can only do it for fields that are only dealt with on "create", e.g. on resources where all/most attributes "force new resource", because otherwise it breaks our ability to diff the state against the config and detect the need for an update.

I'm not sure if that's true in this case, but I just wanted to leave this note here for anyone who decides to try to tackle this issue... in general we won't be able to 100% guarantee that no secrets end up in the state, so in the long run I expect we'll look at ways to securely store the state itself.

**Comment by mkuzmin** [comment]
I'm working on Docker provider in #9520, and met the same issue.

This is a direct promise of the [interface](https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L97-L100):
> 	// StateFunc is a function called to change the value of this before
>	// storing it in the state (and likewise before comparing for diffs).
>	// The use for this is for example with large strings, you may want
>	// to simply store the hash of it.

Why does it break an ability to diff the state? The function can be applied to a new value the same way, as it was applied in last run.

Secrets is an obvious use case, but for large file content it's also required.

**Comment by henrytk** [comment]
Related to https://github.com/hashicorp/terraform/issues/10043
