### ISSUE TITLE
Kong provider

### ISSUE THREAD

**Issue by mytototo** [hashicorp/terraform#9476]
Hey!

Do you have any plan about supporting Kong as a provider?

Thanks.

**Comment by dmportella** [comment]
I was considering writing one if ppl are interested

**Comment by mytototo** [comment]
@dmportella: I'm definitely interested in a Kong provider. And so they are https://github.com/Mashape/kong/issues/608. There are 2 Kong providers for now but nothing official or reliable yet. Unfortunately.

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

**Comment by tecnobrat** [comment]
Wanted to leave this here: https://github.com/WeKnowSports/terraform-provider-kong

Looks like someone has already written something.

**Comment by jaygorrell** [comment]
I know this is closed, but would still love to see something official make it in for this. The above is a great start though! Kong is getting fairly popular and there's really no great way to manage the configuration at all - runtime curl calls isn't the most repeatable (or stateful).

For others landing here, Kongfig is a _decent_ alternative but it has it's own little quirks. It's currently my choice until something more complete lands in Terraform though.

**Comment by kevholditch** [comment]
@jaygorrell check out https://github.com/kevholditch/terraform-provider-kong its pretty fully featured up to Kong 0.12.x.  Fully tested against kong docker containers.  See waht you think

**Comment by dmportella** [comment]
@jaygorrell I have and its pretty good. I am currently using it to setup 2 environments and all is good no complaints.
