### ISSUE TITLE
Feature Request: add Ceph RGW S3 provider

### ISSUE THREAD

**Issue by jmunhoz** [hashicorp/terraform#9505]
Ceph is a distributed object store and file system designed to provide performance, reliability and scalability at the PB scale. It would be great having a Ceph RGW S3 provider in Terraform.

In the Ceph project we are catching up with the S3 spec related to the main use cases but we would need to support custom use cases in RGW and/or avoiding some AWS services (IAM, etc). After having a look in the AWS S3 provider a new RGW S3 provider could make sense. This new RGW S3 provider would be the perfect place to evolve and catch-up with the current Ceph RGW S3 status and particularities, without major impact in the AWS S3 provider.

We would have also to resolve some challenges while developing the provider. The way how it would integrate with open libraries (minio, aws-sdk-go?, etc) to support the major S3 use cases, checking RGW S3 current limitations with those libraries (possible hardwired regions, lacking of feature support, etc)...

The idea would be using the official AWS S3 provider (resources, data sources, etc) as model to follow and handling deviations where required but always having a functional version with each new iteration.

The first proposed patchset would keep the focus on the following goals:
- adding the right RGW S3 provider scaffolding
- adding minio-go as dependency via vendoring
- adding two minimal use cases working to get the previous goals in place

We would suggest 'bucket resource's creation and removal' in order to start things rolling. In detail, we could start supporting the following simple configuration:

```tf
variable "bucket" {
    default = "my-default-bucket"
    type = "string"
}

provider "rgw" {
    access_key = "MY_ACCESS_KEY"
    secret_key = "MY_SECRET_KEY"
    s3endpoint = "my.rgw.test.server:8000"
    region = "global"
}

resource "rgw_s3_bucket" "mybucket" {
    bucket = "my-bucket"
}
```

Related to the development/test/review cycle. I guess asking for one initial PR could make sense. We would use this PR to get all things in place, receiving feedback, etc. One possible first PR could be based on

https://github.com/jmunhoz/terraform/commits/rgw-s3-provider

Notice it is lacking of testing cases, doc, etc. If this approach makes sense all those missing bits could be part of the first iteration.

Thanks,
Javier

**Comment by phinze** [comment]
This sounds like a good play to me @jmunhoz! Agreed that this should be it's own provider.

I wonder if it would be clearer in Terraform's context to just name the provider `ceph` instead of `rgw`? Seems like the "Object/Rados Gateway" is a subset of Ceph functionality, so perhaps it could be mentioned in the resource name? `ceph_rgw_bucket`?

Other than the naming questions, I think your suggestions for an initial PR make a lot of sense. Once we have:

 * Reviewed Implementation
 * Docs in the `website/` subdirectory
 * Acceptance Tests w/ a way for us to run them in our nightly builds

Then we should be good to go!

**Comment by ronaldtse** [comment]
Thanks @jmunhoz -- this is a sorely needed provider in terraform given that Ceph is getting more popular by day! Look forward being able to use this soon.

**Comment by jmunhoz** [comment]
Hey @ronaldtse! Yes, it is in my TODO jumping in this provider ASAP. I have been a bit busy these last months working on the Minio client (and library) support with Ceph and right now I am finishing some urgent work on the Ceph S3 POST API upstream but I hope having a look in the short term. At least, I would like to provide a new iteration covering documentation and acceptance tests to get feedback from @phinze and the team Thanks!

**Comment by stack72** [comment]
Hi @jmunhoz,

Thanks so much for the request for this new provider!

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

@stack72

**Comment by dimm0** [comment]
Is it still not possible to use anything other than Amazon S3? I'd like to store my state in Ceph S3 bucket...
