### ISSUE TITLE
DefaultFunc is always called

### ISSUE THREAD

**Issue by renier** [hashicorp/terraform#9512]
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)

Any resources with a property that uses a DefaultFunc generating a unique value every time it is executed.
### Example code

https://github.com/softlayer/terraform-provider-softlayer/blob/aa6f146/softlayer/resource_softlayer_virtual_guest.go#L56-L72
### Description

I have a resource (linke above) with a property (optional in my case) that has a DefaultFunc defined. The DefaultFunc generates a unique value every time it is called.

After creating the resource, if I check again with plan, Terraform detects a change in the property. Even though it is already set and the same in the cloud and in the state file (but not set in the .tf file since it is going with the default).
I don't understand the behavior for why would Terraform call DefaultFunc for a resource property that already has a state that has value in that property.
### Expected Behavior

I would have expected Terraform not to call DefaultFunc for a property that already has a value in the state for it. Am I misunderstanding the intent of DefaultFunc? Or some subtle aspect about how Terraform calculates the change diff?

**Comment by apparentlymart** [comment]
Hi @renier!

`DefaultFunc` is there to populate the *config* rather than the state, so this is working as intended from Terraform's perspective... `DefaultFunc` will be called as long as there is no explicit value provided in the configuration. `DefaultFunc` should return a stable value, rather than something that varies on each run. So this resource is violating Terraform's expectations in that regard.

It looks like the idea here was to make the default be a random value. Here's a way to achieve that:

* Set the name to be `Computed` as well as `Optional`, which tells Terraform that this attribute gets populated by the provider when not provided in the config.
* Remove the `DefaultFunc` and instead implement this "default" inside the logic for the `Create` and/or `Update` functions, by calling `d.SetId("name", generatedName)`.
* Terraform will ignore this attribute for diffing *unless* the user provides an explicit value in config that disagrees with what is stored in the state.

The above is approximately the pattern followed to implement the `name_prefix` attribute on some of the AWS resources, which is used as an alternative to `name` when a random suffix is desired.

**Comment by renier** [comment]
@apparentlymart Thanks for the workarounds. I already have one in the link above, but I'll think about that.

> DefaultFunc is there to populate the config rather than the state

It can't be to populate the config, as Terraform won't modify your .tf config file. It will create/modify the state, though.

> so this is working as intended from Terraform's perspective...

Basically, if there is already a value for that property, Terraform ignores that fact and looks up the default value again, to compare against the state. That is weird and unexpected.

Furthermore, the documentation says this about Default/DefaultFunc (_helper/schema/schema.go_):
```
// If this is non-nil, then this will be a default value that is used
// when this item is not set in the configuration/state.
```

Another way of saying that last bit: _"the default value won't be used if it is set in the configuration or **state**"_. Or how else to read that _"configuration/**state**"_ phrase?

Given that, you can't help but think that DefaultFunc will not be called if there is already a value in the state or config for the corresponding property.

> DefaultFunc should return a stable value, rather than something that varies on each run. So this resource is violating Terraform's expectations in that regard.

The documentations says (from _helper/schema/schema.go_):
```
// DefaultFunc can be specified if you want a dynamic default value.
```

So the returned value can be dynamic as long as it is stable ??? At the least, tricky. At the most, contradictory.

**Comment by apparentlymart** [comment]
Hi @renier! Sorry that I let this sit here idle for so long.

After reading over our discussion here again, my conclusion was that the `Default` and `DefaultFunc` features *do* behave the way I described and that is their intended behavior, but you are right that the comments associated with these were confusing and misleading. Therefore I decided to resolve this by updating the comments rather than changing the design.

My suggestions in my earlier comment are how we deal with "create-time defaults" (that is, things that have defaults at Create time but are sticky afterwards, which is what you seemed to want to do here). This would be my recommendation for those implementing similar features in new resources.
