### ISSUE TITLE
Feature Request: Support importing vsphere_virtual_machine resources

### ISSUE THREAD

**Issue by jaredledvina** [hashicorp/terraform#9535]
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)
- vsphere_virtual_machine
### Expected Behavior

The following command would successfully import the resource into the tfstate file. 

```
terraform import vsphere_virtual_machine.name id
```
### Actual Behavior

The command above fails with:

```
❯ terraform import vsphere_virtual_machine.name id
provider.vsphere.password
  The user password for vSphere API operations.

  Enter a value: <super-secret-password>

provider.vsphere.user
  The user name for vSphere API operations.

  Enter a value: <username>

provider.vsphere.vsphere_server
  The vSphere Server name for vSphere API operations.

  Enter a value: <fqdn>

vsphere_virtual_machine.name: Importing from ID "id"...
Error importing: 1 error(s) occurred:

* import vsphere_virtual_machine.name (id: id): resource vsphere_virtual_machine doesn't support import
```

**Comment by davwilliams** [comment]
Any update on this? vSphere is a major platform that we provision infrastructure for using TF (and it's still #1 in the enterprise), but often are faced with the need to "import" existing infrastructure. We would be happy to contribute this functionality, but don't completely understand the import functionality as it's not well-documented and only a few supported platforms to compare to.

**Comment by fkgre** [comment]
+1

**Comment by billyjsubs** [comment]
+1
I too am starting to investigate the possibilities here. If I find any further information on importing I will update here,....hopefully somebody else has encountered this also and could advise.

**Comment by mpuckett159** [comment]
Based on the error in the OP the issue was that the provider was not configured properly. It is necessary to have the following configured in your environment:

```
provider "vsphere" {
  user = "username"
  password = "password"
  vsphere_server = "FQDNorIP"
  allow_unverified_ssl = true
}
```

I have mine in a general configuration.tf file where I have a bunch of static information defined for the environment.

In addition, you can find the exact syntax for how to designate the VM to import [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html) towards the bottom under the Import section header. Specifically, the command will look like:

`terraform import vsphere_virtual_machine.vm /datacentername/vm/folder/vmname`

I am successfully executing this with the following versions of Terraform and the vSphere provider:
Terraform v0.11.11
provider.vsphere v1.9.1
