### ISSUE TITLE
Creating an argument reference using external Variables- Terraform

### ISSUE THREAD

**Issue by siddharthan64** [hashicorp/terraform#9542]
I'm creating my instances in two different regions - one for production (us-west-1) and one for staging (us-west-2). My Bastion host is in the same region (us-west-1) as production instances.

If I ssh the staging instances from the bastion host, I use the public ip of the instance (different VPC) and private ip for the production instances (same VPC). How can I handle this on Terraform? Is it possible to generate argument references using a variable? I'm looking at something like the connection block below:

```

variable "ipType" {}

connection {
      host = "${aws_instance.web.${var.ipType}}"
      type = "ssh"
      user = "ubuntu"
      agent = "true"
     }
```

In this I can update the variable using the cmd: 

`terraform apply -var 'ipType=private_ip'`

I'm on Terraform v0.7.6

**Comment by pselle** [comment]
Hello @siddharthan64 ! A lot of time has passed on this issue, and I hope you found some guidance elsewhere! I'm going to close this, as we use GitHub issues for tracking bugs and enhancements rather than for questions.

We suggest that folks use our [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
