### ISSUE TITLE
Support request for iam_oidc_provider

### ISSUE THREAD

**Issue by soulware** [hashicorp/terraform#9638]
SAML provider is supported - 
https://www.terraform.io/docs/providers/aws/r/iam_saml_provider.html

It would be great if something similar was available for OpenID Connect Provider - 
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html

**Comment by stack72** [comment]
Hi @soulware 

Thanks so much for the request! 

Sorry we took so long to get back to you. While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs.

If you are still interested in this feature being part of Terraform, then we would gladly review a Pull Request.

Thanks

@stack72
