### ISSUE TITLE
Provide a link to the latest release of terraform

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#9803]
Currently https://releases.hashicorp.com/terraform/ presents a list of every version of terraform ever released.

It would be nice to be able to get the latest version available (released) from https://releases.hashicorp.com/terraform/latest/ with a full link such as https://releases.hashicorp.com/terraform/latest/ terraform_latest_freebsd_amd64.zip

I know not everyone wants to rely on this behaviour, but it helps to be able to point to the latest version and leave the responsibility of making sure the version is the expected one to the user.

**Comment by sethvargo** [comment]
Hey @ColinHebert 

Thank you for opening an issue. You might not recognize my name, since I'm not involved in the day-to-day workings of Terraform. One of my responsibilities is to manage the HashiCorp releases service, and Paul asked me to take a look at this issue.

In short, we intentionally do not provide a pointer to the "latest" version of any of our software downloads. This was a very intentional and very deliberate choice, and I'd would like to explain the reasoning. As part of the [Tao of HashiCorp](https://www.hashicorp.com/blog/tao-of-hashicorp.html), we believe in Versioning through Codification and Automation through Codification. These two concepts are key in building a successful and sustainable platform. It is _highly discouraged_ that you "ride the latest version" of any software package, not just HashiCorp. It is important to note that this is not a reflection of the quality of the software or release; it is a property of a well-built system. At any point in time, you should be able to reproduce a build. Using a remote URL whose target changes voids the possibility of having a reproducible build. We do not advocate downloading the latest version of Terraform (or any HashiCorp software), and encourage users to pick a version and then coordinate an upgrade effectively.

In case you are unaware, the HashiCorp Releases Service features a [full JSON API](https://www.hashicorp.com/blog/hashicorp-and-fastly.html#json-api) which provides machine-parsable version information. Here is a quick `jq` that would let you download the latest version of Terraform, but you should be strongly advised that we do not recommend this.

```shell
$ OSARCH="linux_amd64"
$ RESULT=$(curl -s https://releases.hashicorp.com/terraform/index.json)
$ LATEST=$(echo $RESULT | jq -r '.versions | keys | sort_by(. | split(".") | map(tonumber?))[-1]')
$ curl -s $(echo $RESULT | jq -r '.versions."0.7.8".builds | map(.url) | max_by(match("$OSARCH")))
```

Right now, that will return "0.7.8", which you can use to query for the version information:

```shell

```

**Comment by ColinHebert** [comment]
I agree with the sentiment of avoiding blind upgrades. In this case the process we're following is this one:

- Download the latest version of each of the pieces of software we need (in a docker image/AWS ami/Whatnot)
 - Run a series of tests against the generated image ensuring that the version we're using is the expected one (ie, a serverspec test ensuring that the "latest" version we expect is 0.7.7, etc.).
- In case of build failure, the expected latest version needs to be updated in the test suite.

The build process is executed automatically on a regular basis. Any upgrade of the "latest" version of anything we use ends up in an expected build failure.
This ensures that we're keeping our everything up to date (security updates, bugfixes, etc.).
Each update is notifying us automatically (as our build breaks, on purpose) which avoids having to keep track of multiple projects moving at different speed (push vs poll).
In case of unacceptable release (bugged release, etc.) it is possible to pin temporarily to a version of our choice.

Obviously the entire process relies on being able to easily access the latest version of any software.

**Comment by alexharv074** [comment]
Totally disagree.

It is like saying, "yum update should not be allowed to exist because that would make it too easy to get the latest versions of software".

At some points in the CI/CD pipeline, infrastructure code should be versioned; at other points, it should not. It is completely normal, in the development phase of the infrastructure, to always fetch the latest version of everything. Then, at some point, a versioned snapshot of components is promoted to a release candidate, tested and released.

My use-case for fetching the latest version is entirely valid, thank you very much.

**Comment by alexharv074** [comment]
By the way, while we're on the subject of preaching best practices to your customers; when is HashiCorp going to provide, you know, a unit testing framework for Terraform?

**Comment by sethvargo** [comment]
Hi @alexharv074 

Thank you for your feedback. I replied on the Packer issue to your first comment. We do have have plans to provide a unit test framework for Terraform at this time.

**Comment by alexharv074** [comment]
Perhaps add a link to Test Driven Development by Kent Beck somewhere inside the "Tao of Hashicorp" 
 https://www.amazon.com/Test-Driven-Development-Kent-Beck/dp/0321146530

**Comment by polvoazul** [comment]
Also, is there a reason not to provide real yum/apt packages? I would like to understand the design decision behind it.

**Comment by sethvargo** [comment]
That's not doing any kind of GPG or checksum validation. I'd recommend just using something simple like [I did in this gist](https://gist.github.com/sethvargo/c9269d4f71a259a99f3e1a207079f306) instead...

**Comment by nodesocket** [comment]
@sethvargo I have an open issue to do checksum validation if you'd like to contribute :-)

https://github.com/elasticbyte/hashipm/issues/1

**Comment by zioalex** [comment]
> Thanks for that link `https://checkpoint-api.hashicorp.com/v1/check/terraform` to get the latest version id.
> 
> My ansible role to get latest terraform if anyone come here from google.
> 
> ```yaml
> - name: get latest terraform version id
>   uri:
>     url: 'https://checkpoint-api.hashicorp.com/v1/check/terraform'
>     method: GET
>     status_code: 200
>     timeout: 10
>   register: release
> 
> - set_fact:
>     version: "{{ release.json | json_query('current_version') }}"
> 
> - name: terraform is present
>   get_url:
>     url: 'https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip'
>     dest: '/tmp/terraform.zip'
> ```

@hoto  can you please share how to use such ansible piece?
