### ISSUE TITLE
Error: Beanstalk Application still exists 

### ISSUE THREAD

**Issue by dev1x** [hashicorp/terraform#9849]
### Terraform Version
0.7.8

### Affected Resource(s)
aws_elastic_beanstalk_application

### Terraform Configuration Files
```hcl
resource "aws_elastic_beanstalk_application" "bs_app" {
  name           = "${var.app_name}"
  description = "${var.bs_app_description}"
}


resource "aws_elastic_beanstalk_environment" "bs_env" {
  application                 = "${var.app_name}"
  name                          = "${var.env_name}"
  solution_stack_name = "${var.solution_stack}"
  description                 = "${var.bs_env_description}"
```

### Expected Behavior
No errors. The beanstalk application should only be destroyed after the destruction of the environments within the module.

### Actual Behavior
Within my module there was an error output regarding trying to delete the beanstalk application before the beanstalk environments that it has.
This should only happen in the end after the destruction of all the other resources on the module that are within the application.

```hcl
Error applying plan:

1 error(s) occurred:

* aws_elastic_beanstalk_application.bs_app: Beanstalk Application still exists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

**Comment by catsby** [comment]
Hey @dev1x – the reason this is happening is because Terraform is unaware of the link between your `aws_elastic_beanstalk_environment.bs_env ` resource and the `aws_elastic_beanstalk_application.bs_app` resource, due to the way you're using the variables. 

Terraform determines relationships based on interpolations. A more typical setup would bel like so:

```
resource "aws_elastic_beanstalk_application" "bs_app" {
  name           = "${var.app_name}"
  description = "${var.bs_app_description}"
}


resource "aws_elastic_beanstalk_environment" "bs_env" {
  application                 = "${aws_elastic_beanstalk_application.bs_app.name}"
  [...]
}
```

This is demonstrated in the documentations:

- https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_environment.html

By constructing your configuration with that kind of interpolation, Terraform determine that the env depends on the app, and both creates and destroys them in the correct order. 

The way your configuration is show, Terraform can not determine the relation; they could simply be named the same, coincidentally. 

Hope that helps!

**Comment by dev1x** [comment]
makes sense, thanks @catsby :-)
