### ISSUE TITLE
Validate the ability to write state file before applying a plan

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#9931]
If you provide a non-writeable `-state-out` parameter, terraform will first create a bunch of resources and then fail. I think terraform should validate whether or not the state file can be written before creating any resources.

As an example, I had a bunch of resources created and then a failure with the message: `Failed to save state: open foo/bar: is a directory`. I had to look at the output to determine what resources were created and then had to go back and manually destroy them before starting over.

**Comment by apparentlymart** [comment]
This is a good idea, @thegedge... I guess we could just write back the same data we've retrieved to make sure it works.

Longer term a locking feature like #5036 could solve this more robustly by taking some sort of lock (depending on what backend is in use) for the duration, with the lock acquisition also serving to prove (modulo network outages, etc) that a subsequent write can succeed without conflicts.

**Comment by teamterraform** [comment]
Hi @thegedge! Sorry for the long silence.

For several major versions now Terraform has begun `terraform apply` by writing a refreshed snapshot of the state to the backend, prior to taking any actions from the plan. This has the side-effect of also verifying that that the backend is writable.

Unfortunately there are still situations where the backend can _become_ unwritable during an apply process, such as if the backend requires credentials and those credentials have expired in the meantime. To account for that, Terraform now has a set of fallback behaviors that will attempt to capture the state locally if the backend is unreachable at the final write after apply, so that it's easier to recover from that situation.

Between those two changes, we think that's addressed the request you made here, so we're going to close this out. Thanks for raising this, and sorry again for the slow response.
