### ISSUE TITLE
Missing resource on openstack for ip association

### ISSUE THREAD

**Issue by rhoml** [hashicorp/terraform#9947]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.7.7

### Affected Resource(s)
Please list the resources as a list, for example:
- compute_instance_v2

In terraform there is a missing resource regarding openstack instances. Potentially we'd like to destroy an instance but it doesn't mean that if the instance has a floating ip this ip should be released back to the pool of ips. We'd like to still keep the ip on the designated tenant since this can be an ip that is provisioned on a LB or even whitelisted on a provider.

In AWS this is fixed with the eip_association resource.

**Comment by jtopjian** [comment]
hm. If an instance with a Floating IP is destroyed, the expected behavior is for the Floating IP to be given back to the tenant. The only reason a Floating IP should ever be released back into the pool is if the Floating IP resource itself is destroyed (and if you allocated a Floating IP out of band of Terraform and statically specified the IP in the instance resource, it should never be released back into the pool).

Can you provide a full Terraform configuration that is triggering this behavior?

As well, are you able to reproduce this situation _outside_ of Terraform? For example, if you use the `nova` or `openstack` command line tools to allocate a Floating IP, create an instance, attach the Floating IP to the instance, and then destroy the instance, was the Floating IP released back into the pool?

**Comment by rhoml** [comment]
So you are write we were doing some other nasty thing. When destroying the instance that was causing this behavior.

What if we just want to disassociate an ip at a given time?

**Comment by jtopjian** [comment]
> What if we just want to disassociate an ip at a given time?

Totally valid. 😄 

I will mark this Issue as an enhancement for a floating IP associate resource.

**Comment by rhoml** [comment]
Brilliant thanks

**Comment by jtopjian** [comment]
@rhoml Quick note: You should be able to remove the floating IP info from the instance in the configuration. Upon applying, the floating IP should be disassociated. There are some acceptance tests that ensure this functionality works, but it's always possible this behavior reacts differently in different environments.

The dedicated resources are still a good idea, especially to get around any edge cases.

**Comment by jtopjian** [comment]
@rhoml I forgot to tag this issue when https://github.com/hashicorp/terraform/pull/12190 was merged, but there's now a `compute_floatingip_associate_v2` resource. It was added in the last release of Terraform. :)

I'm going to close this issue, but please open a new issue if you find any problems with the new resource.
