### ISSUE TITLE
core: "terraform fix" command

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#9949]
Breaking changes may be introduced to the DSL syntax from time to time and it would be helpful to have a way to fix/upgrade the old incompatible syntax to the new DSL.

Inspiration comes from Packer:
https://www.packer.io/docs/command-line/fix.html

```sh
terraform fix old_tpl.tf > new_tpl.tf
```

**Comment by teamterraform** [comment]
For Terraform 0.12 we did a specialized form of this as [`terraform 0.12upgrade`](https://www.terraform.io/docs/commands/0.12upgrade.html). That ended up being a pretty specialized process because it's required to read in using the old configuration parser and write out using the new syntax, and thus the implementation of it doesn't really generalize well to be a `terraform fix` command for future use.

With that said, it's not really possible to know what sorts of things a `terraform fix` command would do without a specific situation to deal with. `packer fix` does semantic rewrites rather than syntactic ones as `terraform 0.12upgrade` does, and perhaps that will be useful, but we'll close this for now until there's a more concrete thing to fix, and we can decide at that point whether that becomes a permanent `terraform fix` command or whether we'll continue the pattern of a one-off specialized upgrade tool like `terraform 0.12upgrade` was.
