### ISSUE TITLE
VSPHERE_VIRTUAL_DISK apply fails in vSphere 6.0.0

### ISSUE THREAD

**Issue by SuperMatt** [hashicorp/terraform#9960]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.9

### Affected Resource(s)
VSPHERE_VIRTUAL_DISK

### Terraform Configuration Files
main.tf
```
variable etcd_target {}

variable etcd_username {}

variable etcd_password {}

variable terraform_state_file {}

variable vcenter_username {}

variable vcenter_password {}

variable size {}

variable name {}

variable vcenter_server {}

variable vcenter_datastore {}

variable datacenter {}

variable type {}

variable "types" {
	default {
		eager = "eagerZeroedThick"
		lazy = "lazy"
		thin = "thin"
	}
}

variable "dc" {
  default = {
    dc1  = "dc1.example.com"
    dc2    = "dc2.example.com"
    dc3    = "dc3.example.com"
    dc4    = "dc4.example.com"
  }
}

data "terraform_remote_state" "generic_vmware" {
  backend = "etcd"

  config {
    path      = "${var.terraform_state_file}"
    endpoints = "${var.etcd_target}"
    username  = "${var.etcd_username}"
    password  = "${var.etcd_password}"
  }
}

provider "vsphere" {
  allow_unverified_ssl = true
  user                 = "${var.vcenter_username}"
  password             = "${var.vcenter_password}"
  vsphere_server       = "${lookup(var.dc, var.vcenter_server)}"
}

resource "vsphere_virtual_disk" "disk" {
	size = "${var.size}"
	vmdk_path = "${var.name}.vmdk"
	datacenter = "${var.datacenter}"
	datastore = "${var.vcenter_datastore}"
	type = "${lookup(var.types, var.type)}"
}

output "diskname" {
	value = "${join(",",vsphere_virtual_disk.disk.*.vmdk_path)}"
}
```

### Debug Output
https://gist.github.com/SuperMatt/c73e7809afe3a993f064ea8db6125f09

### Panic Output
https://gist.github.com/SuperMatt/8fe1a626c3eefc807330d614741e6a3e

### Expected Behavior
Terraform should create a disk in vmware, then report that is completed successfully.

### Actual Behavior
Terraform successfully creates the disk, but before the result is passed back to the client to confirm it was all OK, the crash occurs. This means that there is a new disk, but the terraform state does not reflect this. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Ensure you have a vSphere version 6.0.0
2. Fill in the required variables for your own vSphere
3. Run terraform apply

### Important Factoids
This works for vSphere 5.5

### References
None.

**Comment by Galorhallen** [comment]
Hello,
   we are experiencing the same issue.

### Terraform Version
Terraform v0.8.6

### Affected Resource(s)
- vsphere_virtual_disk


### Terraform Configuration Files
vm-config.tf
```hcl
provider "vsphere" {
	vsphere_server = "<REDACTED>"
	user = "<REDACTED>"
	password = "<REDACTED>"
	allow_unverified_ssl = true
}
```

volume.tf
```hcl
resource "vsphere_virtual_disk" "test_disk" {
    size = 2
    vmdk_path = "test_disk.vmdk"
    datacenter = "Datacenter"
    datastore = "datastore"
    type = "lazy"
}
```

### Debug Output
Plan trace log: [https://gist.github.com/Galorhallen/08a4975602e20f71c425b393322fe372](https://gist.github.com/Galorhallen/08a4975602e20f71c425b393322fe372)
Apply trace log: [https://gist.github.com/Galorhallen/5051e216322e07dad4eeac52d2af81d7](https://gist.github.com/Galorhallen/5051e216322e07dad4eeac52d2af81d7)

### Panic Output
[https://gist.github.com/Galorhallen/eb210e680cdad0cd7226ad8cb4cd10ba](https://gist.github.com/Galorhallen/eb210e680cdad0cd7226ad8cb4cd10ba)

### Expected Behavior
Terraform should create a disk in VMware and then report that the operation is completed successfully

### Actual Behavior
Terraform successully create the disk on VMware, but before the results are reported back to Terraform the crash occurs.
Terraform is unaweare of the new disk,

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
VMware vSphere version: 6.0.0, 3634793

Reading the panic output, it appears that the problem occures while interacting with govmomi library.

### References
None.

**Comment by Galorhallen** [comment]
Hello again,
  analyzing the crash log it seems that the panic occur in the govmomi library. #This [commit](https://github.com/vmware/govmomi/blob/master/task/wait.go) seems related.

Has anyone already tried to compile terraform against a newer version of govmomy?

Thanks in advance.
